if(WIN32)
  set(ACLOUDVIEWER_EXECUTABLE_INSTALL_PATH
      ${CMAKE_INSTALL_PREFIX}/${ACloudViewer_DEST_FOLDER}/${MAIN_APP_NAME}/${MAIN_APP_NAME}.exe
  )

  set(CC_PYTHON_ENV_NAME "Python")
  set(CC_PLUGIN_INSTALL_DIR ${CMAKE_INSTALL_PREFIX}/${ACloudViewer_DEST_FOLDER}/${MAIN_APP_NAME}/plugins)
  set(CC_PYTHON_INSTALL_DIR "${CC_PLUGIN_INSTALL_DIR}/${CC_PYTHON_ENV_NAME}")
elseif(APPLE)
  set(ACLOUDVIEWER_EXECUTABLE_INSTALL_PATH
      ${CMAKE_INSTALL_PREFIX}/${MAIN_APP_NAME}/${MAIN_APP_NAME}.app
  )
else()
  set(ACLOUDVIEWER_EXECUTABLE_INSTALL_PATH
      ${CMAKE_INSTALL_PREFIX}/bin/${MAIN_APP_NAME}/${MAIN_APP_NAME}
  )
  set(CC_PLUGIN_PATH_VALUE
      "${CMAKE_INSTALL_PREFIX}/plugins"
  )
endif()
