// ----------------------------------------------------------------------------
// -                        CloudViewer: www.cloudViewer.org                  -
// ----------------------------------------------------------------------------
// Copyright (c) 2018-2024 www.cloudViewer.org
// SPDX-License-Identifier: MIT
// ----------------------------------------------------------------------------

// Matcher-only accuracy gate. The fixture was generated by
// export_loma_matcher_reference.py from the pinned upstream ONNX model.

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <map>
#include <set>
#include <utility>
#include <vector>

#include "aicore/loma_capi.h"

namespace {

constexpr char kMagic[] = "LOMRF01";

template <typename T>
bool Read(std::ifstream& stream, T* value) {
    return static_cast<bool>(
            stream.read(reinterpret_cast<char*>(value), sizeof(*value)));
}

bool ReadFloats(std::ifstream& stream,
                std::vector<float>* values,
                size_t count) {
    values->resize(count);
    return static_cast<bool>(stream.read(
            reinterpret_cast<char*>(values->data()), count * sizeof(float)));
}

struct Reference {
    uint32_t n0 = 0;
    uint32_t n1 = 0;
    uint32_t dimension = 0;
    uint32_t width = 0;
    uint32_t height = 0;
    std::vector<float> pixels0;
    std::vector<float> pixels1;
    std::vector<float> descriptors0;
    std::vector<float> descriptors1;
    std::map<std::pair<int32_t, int32_t>, float> matches;
};

bool LoadReference(const char* path, Reference* reference) {
    std::ifstream stream(path, std::ios::binary);
    char magic[sizeof(kMagic)]{};
    uint32_t version = 0;
    uint32_t count = 0;
    if (!stream.read(magic, sizeof(magic)) ||
        std::memcmp(magic, kMagic, sizeof(kMagic)) != 0 ||
        !Read(stream, &version) || !Read(stream, &reference->n0) ||
        !Read(stream, &reference->n1) || !Read(stream, &reference->dimension) ||
        !Read(stream, &reference->width) || !Read(stream, &reference->height) ||
        !Read(stream, &count) || version != 1 || reference->n0 == 0 ||
        reference->n1 == 0 || reference->dimension == 0 || count == 0) {
        return false;
    }
    if (!ReadFloats(stream, &reference->pixels0, 2 * reference->n0) ||
        !ReadFloats(stream, &reference->pixels1, 2 * reference->n1) ||
        !ReadFloats(
                stream, &reference->descriptors0,
                static_cast<size_t>(reference->n0) * reference->dimension) ||
        !ReadFloats(
                stream, &reference->descriptors1,
                static_cast<size_t>(reference->n1) * reference->dimension)) {
        return false;
    }
    for (uint32_t index = 0; index < count; ++index) {
        int32_t index0 = -1;
        int32_t index1 = -1;
        float score = 0.0f;
        if (!Read(stream, &index0) || !Read(stream, &index1) ||
            !Read(stream, &score) || index0 < 0 ||
            index0 >= static_cast<int32_t>(reference->n0) || index1 < 0 ||
            index1 >= static_cast<int32_t>(reference->n1) ||
            !std::isfinite(score)) {
            return false;
        }
        reference->matches[{index0, index1}] = score;
    }
    return stream.peek() == std::ifstream::traits_type::eof();
}

std::vector<aicore_loma_keypoint> Keypoints(const std::vector<float>& pixels) {
    std::vector<aicore_loma_keypoint> result(pixels.size() / 2);
    for (size_t index = 0; index < result.size(); ++index) {
        result[index] = {pixels[2 * index], pixels[2 * index + 1]};
    }
    return result;
}

}  // namespace

int main() {
    const char* model = std::getenv("AICORE_TEST_LOMA_GGUF");
    const char* fixture = std::getenv("AICORE_TEST_LOMA_REFERENCE");
    const char* device = std::getenv("AICORE_TEST_DEVICE");
    if (model == nullptr || fixture == nullptr || model[0] == '\0' ||
        fixture[0] == '\0') {
        std::fprintf(stderr,
                     "SKIP: set AICORE_TEST_LOMA_GGUF and "
                     "AICORE_TEST_LOMA_REFERENCE\n");
        return 77;
    }
    if (device == nullptr || device[0] == '\0') device = "cpu";

    Reference reference;
    if (!LoadReference(fixture, &reference)) {
        std::fprintf(stderr, "invalid LoMa ONNX-reference fixture\n");
        return 1;
    }
    const auto keypoints0 = Keypoints(reference.pixels0);
    const auto keypoints1 = Keypoints(reference.pixels1);
    const aicore_loma_features image0 = {
            keypoints0.data(),
            static_cast<int32_t>(reference.n0),
            reference.descriptors0.data(),
            static_cast<int32_t>(reference.dimension),
            static_cast<int32_t>(reference.width),
            static_cast<int32_t>(reference.height)};
    const aicore_loma_features image1 = {
            keypoints1.data(),
            static_cast<int32_t>(reference.n1),
            reference.descriptors1.data(),
            static_cast<int32_t>(reference.dimension),
            static_cast<int32_t>(reference.width),
            static_cast<int32_t>(reference.height)};
    aicore_loma_matcher_options* options = aicore_loma_matcher_options_new();
    aicore_loma_matcher_options_set_device(options, device);
    aicore_loma_matcher_options_set_min_score(options, 0.1);
    aicore_loma_matcher_ctx* context = aicore_loma_matcher_load(model, options);
    aicore_loma_matcher_options_free(options);
    if (!aicore_loma_matcher_is_ready(context)) {
        std::fprintf(stderr, "LoMa load failed: %s\n",
                     aicore_loma_matcher_last_error(context));
        aicore_loma_matcher_free(context);
        return 1;
    }
    aicore_loma_match* raw_matches = nullptr;
    int32_t count = 0;
    const int rc = aicore_loma_matcher_run(context, &image0, &image1,
                                           &raw_matches, &count);
    std::set<std::pair<int32_t, int32_t>> predicted;
    std::map<std::pair<int32_t, int32_t>, float> predicted_scores;
    for (int32_t index = 0; index < count; ++index) {
        if (raw_matches[index].idx0 < 0 || raw_matches[index].idx1 < 0 ||
            !std::isfinite(raw_matches[index].score)) {
            std::fprintf(stderr, "LoMa returned an invalid match\n");
            aicore_loma_free_matches(raw_matches);
            aicore_loma_matcher_free(context);
            return 1;
        }
        const auto pair = std::make_pair(raw_matches[index].idx0,
                                         raw_matches[index].idx1);
        predicted.insert(pair);
        predicted_scores[pair] = raw_matches[index].score;
    }
    aicore_loma_free_matches(raw_matches);
    const std::set<std::pair<int32_t, int32_t>> expected = [&] {
        std::set<std::pair<int32_t, int32_t>> output;
        for (const auto& entry : reference.matches) output.insert(entry.first);
        return output;
    }();
    size_t true_positive = 0;
    float max_score_error = 0.0f;
    for (const auto& pair : predicted) {
        const auto expected_it = reference.matches.find(pair);
        if (expected_it != reference.matches.end()) {
            ++true_positive;
            max_score_error = std::max(
                    max_score_error,
                    std::abs(predicted_scores[pair] - expected_it->second));
        }
    }
    const double precision =
            predicted.empty()
                    ? 0.0
                    : static_cast<double>(true_positive) / predicted.size();
    const double recall =
            expected.empty()
                    ? 0.0
                    : static_cast<double>(true_positive) / expected.size();
    std::printf(
            "{\"suite\":\"loma-matcher-reference\",\"device\":\"%s\","
            "\"expected\":%zu,\"predicted\":%zu,\"tp\":%zu,"
            "\"precision\":%.8f,\"recall\":%.8f,"
            "\"max_score_error\":%.8g}\n",
            device, expected.size(), predicted.size(), true_positive, precision,
            recall, max_score_error);
    aicore_loma_matcher_free(context);
    if (rc != 0 || precision < 0.995 || recall < 0.995 ||
        max_score_error > 1e-3f) {
        std::fprintf(stderr, "LoMa matcher P/R gate failed\n");
        return 1;
    }
    return 0;
}
