name: python3.8
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ninja
  - pkg-config
  - boost=1.84.0 # pcl or vtk
  - flann=1.9.*
  - qhull=2020.2
  - xerces-c=3.2.* # reconstruction
  - qt=5.15.8
  - ffmpeg=6.1.*
  - nodejs  # jupyter
  - rust   # fix missing cargo when pip install pywinpty