name: python_qt6
channels:
  - conda-forge
dependencies:
  - python=3.13
  - ninja
  - pkg-config
  - eigen=3.4.*
  - boost=1.85.* # pcl and reconstruction
  - flann=1.9.*
  - qhull=2020.2
  - xerces-c=3.2.* # reconstruction or PLUGIN_IO_QE57
  - qt6-main>=6.4.*
  - cgal=6.*
  - ffmpeg=7.1.*
  - openssl # For curl build on Windows
  - libcurl=8.14.* # For curl support
  - nodejs  # jupyter
  - rust   # fix missing cargo when pip install pywinpty
  - pip: # maturin>1.7.8 breaks dependency y-py (Python 3.12) and pywinpty (Python 3.8) wheel building
    # https://github.com/MichaIng/DietPi/issues/7329#issuecomment-2565130837
    - maturin==1.7.8