name: cloudViewer
channels:
  - conda-forge
dependencies:
  - python=3.8
  # - eigen=3.4.*
  - ninja
  # pcl or vtk
  - boost=1.84.0
  - flann=1.9.*
  - qhull=2020.2
  - xerces-c=3.2.*
  - qt=5.15.8
  # only macos and windows due to issues with cgal on linux
  - cgal=5.*
  - ffmpeg=6.1.*
  - zlib=1.2.*
  - laszip
