name: python3.8
channels:
  - conda-forge
dependencies:
  - python=3.8
  # - eigen=3.4.*
  - ninja
  - boost=1.84.0
  # will auto install required dependencies like vtk-9.2.6 and qt-5.15.8
  - pcl=1.14.0
  - ffmpeg=6.1.*
  - xerces-c=3.2.* # reconstruction
