name: cloudViewer_qt6
channels:
  - conda-forge
dependencies:
  - python=3.13
  - ninja
  - pkg-config
  - openssl
  - libcurl=8.14.*
  - pcl=1.15.1 # will auto install required dependencies like vtk-9.4.2 and qt-6.9.2
  - qt6-main>=6.4.*
  - cgal=6.*
  - ffmpeg=7.1.*
  - xerces-c=3.2.* # reconstruction or PLUGIN_IO_QE57
  - zlib=1.3.* # PLUGIN_IO_QPHOTOSCAN
  - laszip # PLUGIN_IO_QLAS
  - pip: # for python plugins
    - numpy>=1.18.0
    - pybind11>=2.6.0
    - typing_extensions
