name: python_qt6
channels:
  - conda-forge
dependencies:
  - python=3.13
  - ninja
  - pkg-config
  - openssl
  - libcurl=8.14.*
  - qt6-main>=6.4.* # reconstruction
  - xerces-c=3.2.* # reconstruction
  - cgal=6.* # facets
  - ffmpeg=7.1.*
  - typing_extensions # fix pytorch import missing issues
