name: python3.8
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ninja
  - openssl
  - libcurl=8.14.*
  - qt=5.15.* # reconstruction
  - xerces-c=3.2.* # reconstruction
  - cgal=5.* # facets
  - ffmpeg=6.1.*
