name: cloudViewer
channels:
  - conda-forge
dependencies:
  - python=3.8
  # - eigen=3.4.*
  - ninja
  - pkg-config
  - boost=1.84.*
  - pcl=1.14.0 # will auto install required dependencies like vtk-9.2.6 and qt-5.15.8
  - qt=5.15.*
  - cgal=5.*
  - ffmpeg=6.1.*
  - xerces-c=3.2.* # reconstruction or PLUGIN_IO_QE57
  - zlib=1.2.* # PLUGIN_IO_QPHOTOSCAN
  - laszip # PLUGIN_IO_QLAS
  - pip:
    - numpy
    - pybind11>=2.6.0
