name: python3.8
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ninja
  - pkg-config
  - eigen=3.4.*
  - boost=1.84.* # pcl or vtk
  - flann=1.9.*
  - qhull=2020.2
  - xerces-c=3.2.* # reconstruction
  - qt=5.15.* # reconstruction
  - cgal=5.* # facets
  - ffmpeg=6.1.*
  - nodejs  # jupyter
  - rust   # fix missing cargo when pip install pywinpty
  - pip: # maturin>1.7.8 breaks dependency y-py (Python 3.12) and pywinpty (Python 3.8) wheel building
    # https://github.com/MichaIng/DietPi/issues/7329#issuecomment-2565130837
    - maturin==1.7.8