name: python3.8
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ninja
  - pkg-config
  - openssl
  - libcurl=8.14.*
  - boost=1.84.* # reconstruction
  - qt=5.15.* # reconstruction
  - xerces-c=3.2.* # reconstruction
  - cgal=5.* # facets
  - ffmpeg=6.1.*
  - typing_extensions # fix pytorch import missing issues
