name: python3.8
channels:
  - conda-forge
dependencies:
  - python=3.8
  # - eigen=3.4.*
  - ninja
  # pcl or vtk
  - boost=1.84.0
  - flann=1.9.*
  - qhull=2020.2
  # reconstruction or PLUGIN_IO_QE57
  - xerces-c=3.2.*
  - qt=5.15.8
  # only support macos and windows due to issues with cgal on linux
  - cgal=5.*
  - ffmpeg=6.1.*
  - zlib=1.2.*
  # PLUGIN_IO_QLAS
  - laszip
  # jupyter
  - nodejs
  # fix missing cargo when pip install pywinpty
  - rust
