contact_links:
  - name: Link to ACloudViewer Documentation and Tutorials
    url: https://www.cloudViewer.org/docs/latest/
    about: "Read the documentation and tutorials for ACloudViewer."
  - name: Link to ACloudViewer Discord Server
    url: https://discord.gg/D35BGvn
    about: "Get in touch with the ACloudViewer community on Discord."
