#!/usr/bin/env python3
"""Fill English placeholder translations in ACloudViewer_zh.ts (safe regex)."""

from __future__ import annotations

import re
import sys
import time
from pathlib import Path

try:
    from deep_translator import GoogleTranslator
except ImportError:
    GoogleTranslator = None  # type: ignore

TS_PATH = Path(__file__).resolve().parents[1] / "ACloudViewer_zh.ts"

PAIR_RE = re.compile(
    r"<source>(?P<source>.*?)</source>\s*"
    r'<translation(?P<attrs>[^>]*)>(?P<translation>.*?)</translation>',
    re.DOTALL,
)

KEEP_ENGLISH = {
    "fps", "kbps", "COLMAP", "GLB", "PLY", "SLAM", "Python", "Runtime", "Geosat",
    "SACMODEL_PARALLEL_LINE", "SACMODEL_PERPENDICULAR_PLANE", "SACMODEL_PARALLEL_LINES",
    "SACMODEL_NORMAL_PLANE", "SACMODEL_NORMAL_SPHERE", "SACMODEL_PARALLEL_PLANE",
    "SACMODEL_NORMAL_PARALLEL_PLANE",
}

GLOSSARY = {
    "OK": "确定",
    "Ok": "确定",
    "Cancel": "取消",
    "Apply": "应用",
    "Close": "关闭",
    "Yes": "是",
    "No": "否",
    "Save": "保存",
    "Open": "打开",
    "Delete": "删除",
    "Add": "添加",
    "Remove": "移除",
    "Run": "运行",
    "Stop": "停止",
    "Reset": "重置",
    "Help": "帮助",
    "Warning": "警告",
    "Error": "错误",
    "Information": "信息",
    "Settings": "设置",
    "Options": "选项",
    "Browse": "浏览",
    "Export": "导出",
    "Import": "导入",
    "Load": "加载",
    "Download": "下载",
    "Upload": "上传",
    "Search": "搜索",
    "Filter": "滤波",
    "Mesh": "网格",
    "Point Cloud": "点云",
    "Registration": "配准",
    "Save As": "另存为",
    "Header": "表头",
    "Header:": "表头：",
    "Separator": "分隔符",
    "separator": "分隔符",
    "space": "空格",
    "whitespace": "空白符",
    "semicolon": "分号",
    "comma": "逗号",
    "tabulation": "制表符",
    "order": "顺序",
    "Million": "百万",
    "Show Nodes": "显示节点",
    "Closed Loop": "闭合环",
    "Cloud1 name": "点云1名称",
    "Cloud2 name": "点云2名称",
    "Show labels in 2D": "在 2D 中显示标签",
    "Skip lines": "跳过行",
    "columns title": "列标题",
    "General parameter setting": "常规参数设置",
    "Advanced parameter setting": "高级参数设置",
    "reset boundary": "重置边界",
    "points size": "点大小",
    "angular step": "角度步长",
    "max distance": "最大距离",
    "Classifier file": "分类器文件",
    "Overall accuracy": "总体精度",
    "Show/hide the distance label": "显示/隐藏距离标签",
    "Show/hide contour control nodes": "显示/隐藏轮廓控制节点",
    "Close the contour to form a loop": "闭合轮廓形成环",
    "Width of the contour line": "轮廓线宽度",
    "Width of the distance line": "距离线宽度",
    "Show/hide the distance line": "显示/隐藏距离线",
    "Cloth Simulation Filter": "布料模拟滤波",
    "Slope processing": "坡度处理",
    "from MSC file": "从 MSC 文件",
    "For test purpose!": "仅供测试！",
    "generate one SF per scale with roughness": "为每个尺度生成带粗糙度的标量场",
    "Show classifier behavior on": "显示分类器行为于",
    "3DMASC Classify": "3DMASC 分类",
    "TEST on (optional)": "测试对象（可选）",
    "use active SF to locally refine the classification": "使用活动标量场局部细化分类",
    "Use confidence threshold for classification": "使用置信度阈值进行分类",
    "Cannot read file %1:\n%2.": "无法读取文件 %1：\n%2。",
    "Cannot write file %1:\n%2.": "无法写入文件 %1：\n%2。",
    "Dialog was not correctly filled in": "对话框未正确填写",
    "Errors while computing": "计算时出错",
    "Thread already in use!": "线程已被占用！",
    "Undefined error in %1 module": "%1 模块中发生未定义错误",
    "use comma as decimal character": "使用逗号作为小数点",
    "Save alpha channel": "保存 Alpha 通道",
    "Save colors as float values (0-1)": "将颜色保存为浮点值 (0-1)",
    "Save RGB color components as floats values between 0 and 1": "将 RGB 颜色分量保存为 0 到 1 之间的浮点值",
    "+ comment/header lines skipped: 0": "+ 已跳过的注释/表头行：0",
    "(ASCII code:%i)": "（ASCII 码：%i）",
    "Alpha(0 ? Convex : Concave)": "Alpha（0 ? 凸 : 凹）",
    "Show labels in 2D (not recommended over 50).\nOtherwise labels are shown in 3D.": "在 2D 中显示标签（超过 50 个时不推荐）。\n否则标签在 3D 中显示。",
    "Apply a manipulation to the current camera using the buttons on the left.": "使用左侧按钮对当前相机进行操作。",
    "The separation between eyes (in degrees). This is used when rendering in stereo mode.": "双眼间距（度）。立体渲染模式下使用。",
    "In order to get a faster classifier, you can decrease the number of scales used (keeping only the smallest ones).": "为加快分类器，可减少使用的尺度数量（仅保留最小尺度）。",
    "MSC files are generated by the original CANUPO tool (by N. Brodu)": "MSC 文件由原始 CANUPO 工具（N. Brodu）生成",
    "qCANUPO (disclaimer)": "qCANUPO（免责声明）",
    "ULR Scene Mesh": "ULR 场景网格",
    "Line Width:": "线宽：",
    "Show Label": "显示标签",
    "Closing in %1 s": "%1 秒后关闭",
}


def has_chinese(text: str) -> bool:
    return bool(re.search(r"[\u4e00-\u9fff]", text))


def should_translate(source: str) -> bool:
    s = source.strip()
    if not s or has_chinese(s):
        return False
    if s in KEEP_ENGLISH:
        return False
    if re.match(r"^[\[\(].*[\]\)]$", s):
        return False
    if re.match(r"^[A-Za-z0-9_\-\.\/\\:\+\*\(\)\[\]{}%&]+$", s) and len(s) < 20:
        return False
    if s.startswith("&lt;") and len(s) > 80:
        return True
    if " " in s or len(s) > 18 or s.endswith(":") or s.endswith("..."):
        return True
    return False


def protect_placeholders(text: str) -> tuple[str, list[str]]:
    tokens: list[str] = []

    def repl(match: re.Match[str]) -> str:
        tokens.append(match.group(0))
        return f"__PH{len(tokens)-1}__"

    protected = re.sub(
        r"%[0-9]+(?:n|N|l|L|ld|lld|u|llu|f|F|e|E|g|G|x|X|p|s|d)?|\n|&(?:amp|lt|gt|quot|apos);|&(?:[A-Za-z]+);",
        repl,
        text,
    )
    return protected, tokens


def restore_placeholders(text: str, tokens: list[str]) -> str:
    for i, token in enumerate(tokens):
        text = text.replace(f"__PH{i}__", token)
    return text


def build_memory(text: str) -> dict[str, str]:
    memory: dict[str, str] = {}
    for m in PAIR_RE.finditer(text):
        attrs = m.group("attrs")
        if 'type="vanished"' in attrs:
            continue
        src = m.group("source").strip()
        tr = m.group("translation").strip()
        if src and tr and src != tr and has_chinese(tr):
            memory[src] = tr
    return memory


def translate_text(text: str, memory: dict[str, str], cache: dict[str, str], translator) -> str:
    if text in cache:
        return cache[text]
    if text in GLOSSARY:
        cache[text] = GLOSSARY[text]
        return cache[text]
    if text in memory:
        cache[text] = memory[text]
        return cache[text]

    protected, tokens = protect_placeholders(text)
    if not re.search(r"[A-Za-z]", protected):
        cache[text] = text
        return text
    if GoogleTranslator is None:
        cache[text] = text
        return text

    try:
        translated = translator.translate(protected)
    except Exception:
        time.sleep(1.0)
        try:
            translated = translator.translate(protected)
        except Exception:
            cache[text] = text
            return text

    result = restore_placeholders(translated, tokens)
    result = result.replace("点云云", "点云").replace("网格格", "网格")
    cache[text] = result
    time.sleep(0.02)
    return result


def main() -> int:
    use_api = "--api" in sys.argv
    text = TS_PATH.read_text(encoding="utf-8")
    memory = build_memory(text)
    cache: dict[str, str] = {}
    translator = GoogleTranslator(source="en", target="zh-CN") if GoogleTranslator and use_api else None
    updated = 0

    def repl(m: re.Match[str]) -> str:
        nonlocal updated
        attrs = m.group("attrs")
        if 'type="vanished"' in attrs:
            return m.group(0)
        src_raw = m.group("source")
        tr_raw = m.group("translation")
        src = src_raw.strip()
        tr = tr_raw.strip()

        needs_fix = src == tr or 'type="unfinished"' in attrs
        if not needs_fix:
            return m.group(0)
        if 'type="unfinished"' in attrs and tr and tr != "..." and has_chinese(tr):
            clean_attrs = attrs.replace(' type="unfinished"', "")
            updated += 1
            return f"<source>{src_raw}</source>\n        <translation{clean_attrs}>{tr_raw}</translation>"

        if not should_translate(src):
            if 'type="unfinished"' in attrs and tr in ("", "..."):
                clean_attrs = attrs.replace(' type="unfinished"', "")
                updated += 1
                return f"<source>{src_raw}</source>\n        <translation{clean_attrs}>{src_raw}</translation>"
            return m.group(0)

        new_tr = translate_text(src, memory, cache, translator) if (use_api or src in GLOSSARY or src in memory) else src
        if new_tr == tr or (not has_chinese(new_tr) and new_tr == src):
            return m.group(0)

        clean_attrs = attrs.replace(' type="unfinished"', "")
        updated += 1
        return f"<source>{src_raw}</source>\n        <translation{clean_attrs}>{new_tr}</translation>"

    new_text = PAIR_RE.sub(repl, text)
    TS_PATH.write_text(new_text, encoding="utf-8")
    print(f"Updated translations: {updated}")
    print(f"Cache size: {len(cache)}")
    print(f"API mode: {use_api}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
