ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/estimators/absolute_pose_test.cc File Reference
absolute_pose_test.cc File Reference
#include "util/testing.h"
#include <Eigen/Core>
#include "base/pose.h"
#include "base/similarity_transform.h"
#include "estimators/absolute_pose.h"
#include "estimators/essential_matrix.h"
#include "optim/ransac.h"
#include "util/random.h"
Macros
#define TEST_NAME "base/absolute_pose"
Functions
BOOST_AUTO_TEST_CASE (TestP3P)
BOOST_AUTO_TEST_CASE (TestEPNP)
BOOST_AUTO_TEST_CASE (TestEPNP_BrokenSolveSignCase)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/absolute_pose"
Definition at line 32 of file absolute_pose_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/3]
BOOST_AUTO_TEST_CASE (TestEPNP)
Definition at line 106 of file absolute_pose_test.cc.
References e, colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::Estimate(), colmap::SimilarityTransform3::Matrix(), colmap::RANSACOptions::max_error, colmap::EPNPEstimator::Residuals(), colmap::SetPRNGSeed(), and colmap::SimilarityTransform3::TransformPoint().
BOOST_AUTO_TEST_CASE() [2/3]
BOOST_AUTO_TEST_CASE (TestEPNP_BrokenSolveSignCase)
Definition at line 166 of file absolute_pose_test.cc.
References colmap::EPNPEstimator::Estimate().
BOOST_AUTO_TEST_CASE() [3/3]
BOOST_AUTO_TEST_CASE (TestP3P)
Definition at line 46 of file absolute_pose_test.cc.
References e, colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::Estimate(), colmap::SimilarityTransform3::Matrix(), colmap::RANSACOptions::max_error, colmap::P3PEstimator::Residuals(), colmap::SetPRNGSeed(), and colmap::SimilarityTransform3::TransformPoint().