ACloudViewer: /root/ACloudViewer/app/main.cpp File Reference
main.cpp File Reference
#include "MainWindow.h"
#include "ecvApplication.h"
#include "ecvCommandLineParser.h"
#include "ecvPersistentSettings.h"
#include "ecvSettingManager.h"
#include "ecvUIManager.h"
#include <CPUInfo.h>
#include <CVLog.h>
#include <CVTools.h>
#include <MemoryInfo.h>
#include <ecvColorScalesManager.h>
#include <ecvGuiParameters.h>
#include <ecvNormalVectors.h>
#include <FileIOFilter.h>
#include <ecvGlobalShiftManager.h>
#include <QDir>
#include <QSurfaceFormat>
#include <QMessageBox>
#include <QOffscreenSurface>
#include <QOpenGLContext>
#include <QOpenGLFunctions>
#include <QPixmap>
#include <QSplashScreen>
#include <QStorageInfo>
#include <QSysInfo>
#include <QTime>
#include <QTimer>
#include <QTranslator>
#include <QtWidgets/QApplication>
#include "CommonSettings.h"
#include "ecvTranslationManager.h"
#include "ecvPluginInterface.h"
#include "ecvPluginManager.h"
Functions
QString GetTotalMemoryInfo ()
QString GetStorageInfo ()
QString GetCPUInfo ()
QString GetGPUInfo ()
void PrintSystemHardwareInfo ()
void InitEnvironment ()
int main (int argc, char *argv[])
Function Documentation
GetCPUInfo()
QString GetCPUInfo ()
Definition at line 117 of file main.cpp.
References cloudViewer::utility::CPUInfo::GetInstance(), cloudViewer::utility::CPUInfo::ModelName(), cloudViewer::utility::CPUInfo::NumCores(), cloudViewer::utility::CPUInfo::NumThreads(), and result.
Referenced by PrintSystemHardwareInfo().
GetGPUInfo()
QString GetGPUInfo ()
Definition at line 157 of file main.cpp.
References context, and version.
Referenced by PrintSystemHardwareInfo().
GetStorageInfo()
QString GetStorageInfo ()
Definition at line 96 of file main.cpp.
Referenced by PrintSystemHardwareInfo().
GetTotalMemoryInfo()
QString GetTotalMemoryInfo ()
Definition at line 81 of file main.cpp.
References cloudViewer::system::getMemoryInfo(), and cloudViewer::system::MemoryInfo::totalRam.
Referenced by PrintSystemHardwareInfo().
InitEnvironment()
void InitEnvironment ()
Definition at line 225 of file main.cpp.
References Settings::CONFIG_PATH, CVLog::EnableMessageBackup(), ccPluginManager::get(), ccColorScalesManager::GetUniqueInstance(), ccNormalVectors::GetUniqueInstance(), ecvSettingManager::getValue(), ecvPS::GlobalShift(), ecvSettingManager::Init(), ccPluginManager::loadPlugins(), ecvPS::MaxAbsCoord(), ecvPS::MaxAbsDiag(), ecvGlobalShiftManager::MaxBoundgBoxDiagonal(), ecvGlobalShiftManager::MaxCoordinateAbsValue(), CVLog::Print(), ecvGlobalShiftManager::SetMaxBoundgBoxDiagonal(), and ecvGlobalShiftManager::SetMaxCoordinateAbsValue().
Referenced by main().
main()
int main (int argc, char * argv[])
release global structures
Definition at line 271 of file main.cpp.
References MainWindow::addToDB(), Settings::APP_LOGO, Settings::APP_START_LOGO, Settings::APP_TITLE, QUIWidget::BtnMenu, MainWindow::ChangeStyle(), context, QUIWidget::createTrayMenu(), ecvPS::CurrentTheme(), Settings::DEFAULT_STYLE, MainWindow::DestroyInstance(), CVLog::Error(), format, CVTools::FromQString(), ccPluginManager::get(), ccTranslationManager::get(), ecvSettingManager::getValue(), InitEnvironment(), ecvApplicationBase::InitOpenGL(), MainWindow::initPlugins(), QUIWidget::Lab_Ico, ccTranslationManager::loadTranslation(), ecvGlobalShiftManager::MaxBoundgBoxDiagonal(), ecvGlobalShiftManager::MaxCoordinateAbsValue(), ccCommandLineParser::Parse(), CVLog::Print(), PrintSystemHardwareInfo(), ecvSettingManager::ReleaseInstance(), result, QUIWidget::setAlignment(), QUIWidget::setCode(), QUIWidget::setMainWidget(), QUIWidget::setPixmap(), QUIWidget::setStyle(), QUIWidget::setTitle(), MainWindow::setUiManager(), QUIWidget::setVisible(), MainWindow::TheInstance(), ecvPS::ThemeSettings(), Settings::UI_WRAPPER, and FileIOFilter::UnregisterAll().
PrintSystemHardwareInfo()
void PrintSystemHardwareInfo ()
Definition at line 190 of file main.cpp.
References GetCPUInfo(), GetGPUInfo(), GetStorageInfo(), GetTotalMemoryInfo(), and CVLog::Print().
Referenced by main().