ACloudViewer: /root/ACloudViewer/libs/CV_io/src/AsciiFilter.cpp File Reference
AsciiFilter.cpp File Reference
#include "AsciiFilter.h"
#include <CVLog.h>
#include <ScalarField.h>
#include <ecv2DLabel.h>
#include <ecvHObjectCaster.h>
#include <ecvPointCloud.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <cassert>
#include <cstring>
#include <QFile>
#include <QFileInfo>
#include <QScopedPointer>
#include <QSharedPointer>
#include <QtCompat.h>
Classes
struct cloudAttributesDescriptor
Functions
void clearStructure (cloudAttributesDescriptor &cloudDesc)
cloudAttributesDescriptor prepareCloud (const AsciiOpenDlg::Sequence &openSequence, unsigned numberOfPoints, int &maxIndex, unsigned step=1)
Variables
static int s_defaultSkippedLineCount = 0
static int s_outputCoordPrecision = 8
static int s_outputSFPrecision = 6
static int s_outputSeparatorIndex = 0
static bool s_saveSFBeforeColor = false
static bool s_saveColumnsNamesHeader = false
static bool s_savePointCountHeader = false
Function Documentation
clearStructure()
void clearStructure (cloudAttributesDescriptor & cloudDesc)
Definition at line 520 of file AsciiFilter.cpp.
References cloudAttributesDescriptor::cloud, and cloudAttributesDescriptor::reset().
prepareCloud()
cloudAttributesDescriptor prepareCloud (const AsciiOpenDlg::Sequence & openSequence, unsigned numberOfPoints, int & maxIndex, unsigned step = 1)
Definition at line 526 of file AsciiFilter.cpp.
References ccPointCloud::addScalarField(), cloudAttributesDescriptor::alphaIndex, ASCII_OPEN_DLG_A, ASCII_OPEN_DLG_Af, ASCII_OPEN_DLG_B, ASCII_OPEN_DLG_Bf, ASCII_OPEN_DLG_G, ASCII_OPEN_DLG_Gf, ASCII_OPEN_DLG_Grey, ASCII_OPEN_DLG_Label, ASCII_OPEN_DLG_None, ASCII_OPEN_DLG_NX, ASCII_OPEN_DLG_NY, ASCII_OPEN_DLG_NZ, ASCII_OPEN_DLG_R, ASCII_OPEN_DLG_Rf, ASCII_OPEN_DLG_RGB32f, ASCII_OPEN_DLG_RGB32i, ASCII_OPEN_DLG_Scalar, ASCII_OPEN_DLG_X, ASCII_OPEN_DLG_Y, ASCII_OPEN_DLG_Z, cloudAttributesDescriptor::blueIndex, cloudAttributesDescriptor::cloud, cloudAttributesDescriptor::fRgbaIndex, cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudAttributesDescriptor::greenIndex, cloudAttributesDescriptor::greyIndex, cloudAttributesDescriptor::hasFloatRGBColors, cloudAttributesDescriptor::hasNorms, cloudAttributesDescriptor::hasRGBColors, cloudAttributesDescriptor::iRgbaIndex, cloudAttributesDescriptor::labelIndex, cloudAttributesDescriptor::redIndex, CCShareable::release(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveThePointsTable(), ccPointCloud::reserveTheRGBTable(), cloudAttributesDescriptor::scalarFields, cloudAttributesDescriptor::scalarIndexes, ccObject::setName(), ccDrawableObject::showColors(), ccDrawableObject::showNormals(), type, cloudAttributesDescriptor::updateMaxIndex(), CVLog::Warning(), cloudAttributesDescriptor::xCoordIndex, cloudAttributesDescriptor::xNormIndex, cloudAttributesDescriptor::yCoordIndex, cloudAttributesDescriptor::yNormIndex, cloudAttributesDescriptor::zCoordIndex, and cloudAttributesDescriptor::zNormIndex.
Referenced by AsciiFilter::loadCloudFromFormatedAsciiStream().
Variable Documentation
s_defaultSkippedLineCount
int s_defaultSkippedLineCount = 0 static
Definition at line 35 of file AsciiFilter.cpp.
Referenced by AsciiFilter::SetDefaultSkippedLineCount().
s_outputCoordPrecision
int s_outputCoordPrecision = 8 static
Definition at line 36 of file AsciiFilter.cpp.
Referenced by AsciiFilter::saveToFile(), and AsciiFilter::SetOutputCoordsPrecision().
s_outputSeparatorIndex
int s_outputSeparatorIndex = 0 static
Definition at line 38 of file AsciiFilter.cpp.
Referenced by AsciiFilter::saveToFile(), and AsciiFilter::SetOutputSeparatorIndex().
s_outputSFPrecision
int s_outputSFPrecision = 6 static
Definition at line 37 of file AsciiFilter.cpp.
Referenced by AsciiFilter::saveToFile(), and AsciiFilter::SetOutputSFPrecision().
s_saveColumnsNamesHeader
bool s_saveColumnsNamesHeader = false static
Definition at line 40 of file AsciiFilter.cpp.
Referenced by AsciiFilter::SaveColumnsNamesHeader(), and AsciiFilter::saveToFile().
s_savePointCountHeader
bool s_savePointCountHeader = false static
Definition at line 41 of file AsciiFilter.cpp.
Referenced by AsciiFilter::SavePointCountHeader(), and AsciiFilter::saveToFile().
s_saveSFBeforeColor
bool s_saveSFBeforeColor = false static
Definition at line 39 of file AsciiFilter.cpp.
Referenced by AsciiFilter::SaveSFBeforeColor(), and AsciiFilter::saveToFile().