ACloudViewer: /root/ACloudViewer/libs/CV_io/src/AsciiOpenDlg.cpp File Reference
AsciiOpenDlg.cpp File Reference
#include <ui_openAsciiFileDlg.h>
#include "AsciiOpenDlg.h"
#include "FileIOFilter.h"
#include <ecvPointCloud.h>
#include <QComboBox>
#include <QDialogButtonBox>
#include <QFile>
#include <QLineEdit>
#include <QMessageBox>
#include <QPushButton>
#include <QScreen>
#include <QSpinBox>
#include <QTableWidget>
#include <QTableWidgetItem>
#include <QTextStream>
#include <QToolButton>
#include <QtCompat.h>
#include <cassert>
#include <cstdio>
#include <cstring>
Classes
struct AsciiOpenContext
Dialog 'context'.
Functions
static bool CouldBeX (const QString &colHeader)
static bool CouldBeY (const QString &colHeader)
static bool CouldBeZ (const QString &colHeader)
static bool CouldBeRf (const QString &colHeader)
static bool CouldBeGf (const QString &colHeader)
static bool CouldBeBf (const QString &colHeader)
static bool CouldBeAf (const QString &colHeader)
static bool CouldBeR (const QString &colHeader)
static bool CouldBeG (const QString &colHeader)
static bool CouldBeB (const QString &colHeader)
static bool CouldBeA (const QString &colHeader)
static bool CouldBeNx (const QString &colHeader)
static bool CouldBeNy (const QString &colHeader)
static bool CouldBeNz (const QString &colHeader)
static bool CouldBeGrey (const QString &colHeader)
static bool CouldBeRGBi (const QString &colHeader)
static bool CouldBeRGBf (const QString &colHeader)
static bool CouldBeScal (const QString &colHeader)
static bool CouldBeLabel (const QString &colHeader)
static int EnabledBits (unsigned bitField)
Variables
static double s_maxCloudSizeDoubleSpinBoxValue
static unsigned s_maxLabelCount = 256
static AsciiOpenContext s_asciiOpenContext
Semi-persistent loading context.
static const unsigned MAX_COLUMNS
static const unsigned LINES_READ_FOR_STATS
static const unsigned DISPLAYED_LINES = 20
static unsigned X_BIT = 1
static unsigned Y_BIT = 2
static unsigned Z_BIT = 4
static unsigned W_BIT = 8
static unsigned XYZ_BITS = X_BIT | Y_BIT | Z_BIT
static unsigned XYZW_BITS = XYZ_BITS | W_BIT
Function Documentation
CouldBeA()
static bool CouldBeA (const QString & colHeader) static
Definition at line 231 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::A().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeAf()
static bool CouldBeAf (const QString & colHeader) static
Definition at line 216 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::Af().
CouldBeB()
static bool CouldBeB (const QString & colHeader) static
Definition at line 227 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::B().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeBf()
static bool CouldBeBf (const QString & colHeader) static
Definition at line 213 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::Bf().
Referenced by AsciiOpenDlg::updateTable().
CouldBeG()
static bool CouldBeG (const QString & colHeader) static
Definition at line 223 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::G().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeGf()
static bool CouldBeGf (const QString & colHeader) static
Definition at line 210 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::Gf().
Referenced by AsciiOpenDlg::updateTable().
CouldBeGrey()
static bool CouldBeGrey (const QString & colHeader) static
Definition at line 248 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::Grey().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeLabel()
static bool CouldBeLabel (const QString & colHeader) static
Definition at line 260 of file AsciiOpenDlg.cpp.
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeNx()
static bool CouldBeNx (const QString & colHeader) static
Definition at line 235 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::Nx().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeNy()
static bool CouldBeNy (const QString & colHeader) static
Definition at line 239 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::Ny().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeNz()
static bool CouldBeNz (const QString & colHeader) static
Definition at line 243 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::Nz().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeR()
static bool CouldBeR (const QString & colHeader) static
Definition at line 219 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::R().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeRf()
static bool CouldBeRf (const QString & colHeader) static
Definition at line 207 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::Rf().
Referenced by AsciiOpenDlg::updateTable().
CouldBeRGBf()
static bool CouldBeRGBf (const QString & colHeader) static
Definition at line 254 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::RGB32f().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeRGBi()
static bool CouldBeRGBi (const QString & colHeader) static
Definition at line 251 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::RGB32i().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeScal()
static bool CouldBeScal (const QString & colHeader) static
Definition at line 257 of file AsciiOpenDlg.cpp.
Referenced by AsciiOpenDlg::updateTable().
CouldBeX()
static bool CouldBeX (const QString & colHeader) static
Definition at line 198 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::X().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeY()
static bool CouldBeY (const QString & colHeader) static
Definition at line 201 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::Y().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
CouldBeZ()
static bool CouldBeZ (const QString & colHeader) static
Definition at line 204 of file AsciiOpenDlg.cpp.
References AsciiHeaderColumns::Z().
Referenced by AsciiOpenDlg::safeSequence(), and AsciiOpenDlg::updateTable().
EnabledBits()
static int EnabledBits (unsigned bitField) static
Definition at line 277 of file AsciiOpenDlg.cpp.
References count, W_BIT, X_BIT, Y_BIT, and Z_BIT.
Referenced by AsciiOpenDlg::updateTable().
Variable Documentation
DISPLAYED_LINES
const unsigned DISPLAYED_LINES = 20 static
Definition at line 268 of file AsciiOpenDlg.cpp.
Referenced by AsciiOpenDlg::updateTable().
LINES_READ_FOR_STATS
const unsigned LINES_READ_FOR_STATS static
Initial value:
=
        200
Definition at line 266 of file AsciiOpenDlg.cpp.
Referenced by AsciiOpenDlg::updateTable().
MAX_COLUMNS
const unsigned MAX_COLUMNS static
Initial value:
=
        512
Definition at line 264 of file AsciiOpenDlg.cpp.
Referenced by AsciiOpenDlg::updateTable().
s_asciiOpenContext
AsciiOpenContext s_asciiOpenContext static
Semi-persistent loading context.
Definition at line 97 of file AsciiOpenDlg.cpp.
Referenced by AsciiOpenDlg::applyAll(), AsciiOpenDlg::ResetApplyAll(), and AsciiOpenDlg::restorePreviousContext().
s_maxCloudSizeDoubleSpinBoxValue
double s_maxCloudSizeDoubleSpinBoxValue static
Initial value:
=
        (CC_MAX_NUMBER_OF_POINTS_PER_CLOUD / 1.0e6)
Definition at line 43 of file AsciiOpenDlg.cpp.
Referenced by AsciiOpenDlg::apply(), and AsciiOpenDlg::AsciiOpenDlg().
s_maxLabelCount
unsigned s_maxLabelCount = 256 static
Definition at line 47 of file AsciiOpenDlg.cpp.
Referenced by AsciiOpenDlg::updateTable().
W_BIT
unsigned W_BIT = 8 static
Definition at line 273 of file AsciiOpenDlg.cpp.
Referenced by EnabledBits(), and AsciiOpenDlg::updateTable().
X_BIT
unsigned X_BIT = 1 static
Definition at line 270 of file AsciiOpenDlg.cpp.
Referenced by EnabledBits(), and AsciiOpenDlg::updateTable().
XYZ_BITS
unsigned XYZ_BITS = X_BIT | Y_BIT | Z_BIT static
Definition at line 274 of file AsciiOpenDlg.cpp.
Referenced by AsciiOpenDlg::updateTable().
XYZW_BITS
unsigned XYZW_BITS = XYZ_BITS | W_BIT static
Definition at line 275 of file AsciiOpenDlg.cpp.
Y_BIT
unsigned Y_BIT = 2 static
Definition at line 271 of file AsciiOpenDlg.cpp.
Referenced by EnabledBits(), and AsciiOpenDlg::updateTable().
Z_BIT
unsigned Z_BIT = 4 static
Definition at line 272 of file AsciiOpenDlg.cpp.
Referenced by EnabledBits(), and AsciiOpenDlg::updateTable().