ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/balance.c File Reference
balance.c File Reference
#include "metis.h"
Functions
void Bnd2WayBalance (CtrlType *ctrl, GraphType *graph, int *tpwgts)
void General2WayBalance (CtrlType *ctrl, GraphType *graph, int *tpwgts)
void Balance2Way (CtrlType *ctrl, GraphType *graph, int *tpwgts, float ubfactor)
Function Documentation
Balance2Way()
void Balance2Way (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 24 of file balance.c.
References abs(), Bnd2WayBalance(), General2WayBalance(), graphdef::nbnd, graphdef::nvtxs, and graphdef::pwgts.
Bnd2WayBalance()
void Bnd2WayBalance (CtrlType * ctrl, GraphType * graph, int * tpwgts)
Definition at line 51 of file balance.c.
References abs(), graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, graphdef::id, idxamax, idxset, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, graphdef::nvtxs, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueUpdate, graphdef::pwgts, RandomPermute, SWAP, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by Balance2Way().
General2WayBalance()
void General2WayBalance (CtrlType * ctrl, GraphType * graph, int * tpwgts)
Definition at line 177 of file balance.c.
References abs(), graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, graphdef::id, idxamax, idxset, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, graphdef::nvtxs, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueUpdate, graphdef::pwgts, RandomPermute, SWAP, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by Balance2Way().