ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/essential_matrix_test.cc File Reference
essential_matrix_test.cc File Reference
#include "util/testing.h"
#include <Eigen/Geometry>
#include "base/essential_matrix.h"
#include "base/pose.h"
#include "base/projection.h"
Macros
#define TEST_NAME "base/essential_matrix"
Functions
BOOST_AUTO_TEST_CASE (TestDecomposeEssentialMatrix)
BOOST_AUTO_TEST_CASE (TestEssentialMatrixFromPose)
BOOST_AUTO_TEST_CASE (TestEssentialMatrixFromPoses)
BOOST_AUTO_TEST_CASE (TestPoseFromEssentialMatrix)
BOOST_AUTO_TEST_CASE (TestFindOptimalImageObservations)
BOOST_AUTO_TEST_CASE (TestEpipoleFromEssentialMatrix)
BOOST_AUTO_TEST_CASE (TestInvertEssentialMatrix)
BOOST_AUTO_TEST_CASE (TestRefineEssentialMatrix)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/essential_matrix"
Definition at line 32 of file essential_matrix_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/8]
BOOST_AUTO_TEST_CASE (TestDecomposeEssentialMatrix)
Definition at line 43 of file essential_matrix_test.cc.
References colmap::DecomposeEssentialMatrix(), e, colmap::EssentialMatrixFromPose(), and colmap::EulerAnglesToRotationMatrix().
BOOST_AUTO_TEST_CASE() [2/8]
BOOST_AUTO_TEST_CASE (TestEpipoleFromEssentialMatrix)
Definition at line 147 of file essential_matrix_test.cc.
References colmap::EpipoleFromEssentialMatrix(), colmap::EssentialMatrixFromPose(), and colmap::EulerAnglesToRotationMatrix().
BOOST_AUTO_TEST_CASE() [3/8]
BOOST_AUTO_TEST_CASE (TestEssentialMatrixFromPose)
Definition at line 57 of file essential_matrix_test.cc.
References colmap::EssentialMatrixFromPose(), and colmap::EulerAnglesToRotationMatrix().
BOOST_AUTO_TEST_CASE() [4/8]
BOOST_AUTO_TEST_CASE (TestEssentialMatrixFromPoses)
Definition at line 68 of file essential_matrix_test.cc.
References colmap::ComposeProjectionMatrix(), e, colmap::EssentialMatrixFromAbsolutePoses(), colmap::EssentialMatrixFromPose(), and colmap::EulerAnglesToRotationMatrix().
BOOST_AUTO_TEST_CASE() [5/8]
BOOST_AUTO_TEST_CASE (TestFindOptimalImageObservations)
Definition at line 116 of file essential_matrix_test.cc.
References colmap::ComposeProjectionMatrix(), colmap::EssentialMatrixFromPose(), colmap::EulerAnglesToRotationMatrix(), and colmap::FindOptimalImageObservations().
BOOST_AUTO_TEST_CASE() [6/8]
BOOST_AUTO_TEST_CASE (TestInvertEssentialMatrix)
Definition at line 158 of file essential_matrix_test.cc.
References colmap::EssentialMatrixFromPose(), colmap::EulerAnglesToRotationMatrix(), and colmap::InvertEssentialMatrix().
BOOST_AUTO_TEST_CASE() [7/8]
BOOST_AUTO_TEST_CASE (TestPoseFromEssentialMatrix)
Definition at line 81 of file essential_matrix_test.cc.
References colmap::ComposeProjectionMatrix(), colmap::EssentialMatrixFromPose(), colmap::EulerAnglesToRotationMatrix(), and colmap::PoseFromEssentialMatrix().
BOOST_AUTO_TEST_CASE() [8/8]
BOOST_AUTO_TEST_CASE (TestRefineEssentialMatrix)
Definition at line 169 of file essential_matrix_test.cc.
References colmap::ComposeProjectionMatrix(), colmap::EssentialMatrixFromPose(), colmap::EulerAnglesToRotationMatrix(), and colmap::RefineEssentialMatrix().