ACloudViewer: /root/ACloudViewer/libs/CV_io/src/BinFilter.cpp File Reference
BinFilter.cpp File Reference
#include "BinFilter.h"
#include <QApplication>
#include <QFileInfo>
#include <QMessageBox>
#include <QtConcurrentRun>
#include <ecv2DLabel.h>
#include <ecvCameraSensor.h>
#include <ecvCircle.h>
#include <ecvDisc.h>
#include <ecvFacet.h>
#include <ecvFlags.h>
#include <ecvGenericPointCloud.h>
#include <ecvHObjectCaster.h>
#include <ecvImage.h>
#include <ecvMaterialSet.h>
#include <ecvMesh.h>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <ecvSensor.h>
#include <ecvSubMesh.h>
#include <cassert>
#include <cstring>
#include <unordered_set>
#include <unistd.h>
#include <ctime>
Classes
union HeaderFlags
Per-cloud header flags (old style)
Functions
static int ReadEntityHeader (QFile &in, unsigned &numberOfPoints, HeaderFlags &header)
bool Match (ccHObject *object, unsigned uniqueID, CV_CLASS_ENUM expectedType)
ccHObject * FindRobust (ccHObject *root, ccHObject *source, const ccObject::LoadedIDMap &oldToNewIDMap, unsigned oldUniqueID, CV_CLASS_ENUM expectedType)
static bool ContinueAfterError (bool &forceLoadAfterError, bool couldBeAMemoryIssue=false)
Helper function to ask user whether to continue after an error.
Variables
static short s_lastSavedFileBinVersion = 0
Last saved file version.
Function Documentation
ContinueAfterError()
static bool ContinueAfterError (bool & forceLoadAfterError, bool couldBeAMemoryIssue = false) static
Helper function to ask user whether to continue after an error.
Definition at line 388 of file BinFilter.cpp.
FindRobust()
ccHObject* FindRobust (ccHObject * root, ccHObject * source, const ccObject::LoadedIDMap & oldToNewIDMap, unsigned oldUniqueID, CV_CLASS_ENUM expectedType)
Definition at line 353 of file BinFilter.cpp.
References ccHObject::find(), ccHObject::getChild(), ccHObject::getChildrenNumber(), ccHObject::getParent(), ccObject::isKindOf(), and Match().
Match()
bool Match (ccHObject * object, unsigned uniqueID, CV_CLASS_ENUM expectedType) inline
Definition at line 346 of file BinFilter.cpp.
Referenced by FindRobust().
ReadEntityHeader()
static int ReadEntityHeader (QFile & in, unsigned & numberOfPoints, HeaderFlags & header) static
Definition at line 113 of file BinFilter.cpp.
Variable Documentation
s_lastSavedFileBinVersion
short s_lastSavedFileBinVersion = 0 static
Last saved file version.
Definition at line 49 of file BinFilter.cpp.
Referenced by BinFilter::GetLastSavedFileVersion(), and BinFilter::saveToFile().