ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/util/bitmap_test.cc File Reference
bitmap_test.cc File Reference
#include "util/testing.h"
#include "util/bitmap.h"
Macros
#define TEST_NAME "util/bitmap"
Functions
BOOST_AUTO_TEST_CASE (TestBitmapColorEmpty)
BOOST_AUTO_TEST_CASE (TestBitmapGrayColor)
BOOST_AUTO_TEST_CASE (TestBitmapColorCast)
BOOST_AUTO_TEST_CASE (TestEmpty)
BOOST_AUTO_TEST_CASE (TestAllocateRGB)
BOOST_AUTO_TEST_CASE (TestAllocateGrey)
BOOST_AUTO_TEST_CASE (TestDeallocate)
BOOST_AUTO_TEST_CASE (TestBitsPerPixel)
BOOST_AUTO_TEST_CASE (TestNumBytes)
BOOST_AUTO_TEST_CASE (TestConvertToRowMajorArrayRGB)
BOOST_AUTO_TEST_CASE (TestConvertToRowMajorArrayGrey)
BOOST_AUTO_TEST_CASE (TestConvertToColMajorArrayRGB)
BOOST_AUTO_TEST_CASE (TestConvertToColMajorArrayGrey)
BOOST_AUTO_TEST_CASE (TestGetAndSetPixelRGB)
BOOST_AUTO_TEST_CASE (TestGetAndSetPixelGrey)
BOOST_AUTO_TEST_CASE (TestGetScanlineRGB)
BOOST_AUTO_TEST_CASE (TestGetScanlineGrey)
BOOST_AUTO_TEST_CASE (TestFill)
BOOST_AUTO_TEST_CASE (TestInterpolateNearestNeighbor)
BOOST_AUTO_TEST_CASE (TestInterpolateBilinear)
BOOST_AUTO_TEST_CASE (TestSmoothRGB)
BOOST_AUTO_TEST_CASE (TestSmoothGrey)
BOOST_AUTO_TEST_CASE (TestRescaleRGB)
BOOST_AUTO_TEST_CASE (TestRescaleGrey)
BOOST_AUTO_TEST_CASE (TestClone)
BOOST_AUTO_TEST_CASE (TestCloneAsRGB)
BOOST_AUTO_TEST_CASE (TestCloneAsGrey)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "util/bitmap"
Definition at line 32 of file bitmap_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/27]
BOOST_AUTO_TEST_CASE (TestAllocateGrey)
Definition at line 82 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::Channels(), colmap::Bitmap::Height(), colmap::Bitmap::IsGrey(), colmap::Bitmap::IsRGB(), and colmap::Bitmap::Width().
BOOST_AUTO_TEST_CASE() [2/27]
BOOST_AUTO_TEST_CASE (TestAllocateRGB)
Definition at line 72 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::Channels(), colmap::Bitmap::Height(), colmap::Bitmap::IsGrey(), colmap::Bitmap::IsRGB(), and colmap::Bitmap::Width().
BOOST_AUTO_TEST_CASE() [3/27]
BOOST_AUTO_TEST_CASE (TestBitmapColorCast)
Definition at line 55 of file bitmap_test.cc.
References colmap::BitmapColor< T >::b, colmap::BitmapColor< T >::Cast(), colmap::BitmapColor< T >::g, and colmap::BitmapColor< T >::r.
BOOST_AUTO_TEST_CASE() [4/27]
BOOST_AUTO_TEST_CASE (TestBitmapColorEmpty)
Definition at line 39 of file bitmap_test.cc.
References color.
BOOST_AUTO_TEST_CASE() [5/27]
BOOST_AUTO_TEST_CASE (TestBitmapGrayColor)
Definition at line 48 of file bitmap_test.cc.
References color.
BOOST_AUTO_TEST_CASE() [6/27]
BOOST_AUTO_TEST_CASE (TestBitsPerPixel)
Definition at line 104 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), and colmap::Bitmap::BitsPerPixel().
BOOST_AUTO_TEST_CASE() [7/27]
BOOST_AUTO_TEST_CASE (TestClone)
Definition at line 359 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::Channels(), colmap::Bitmap::Clone(), colmap::Bitmap::Data(), colmap::Bitmap::Height(), and colmap::Bitmap::Width().
BOOST_AUTO_TEST_CASE() [8/27]
BOOST_AUTO_TEST_CASE (TestCloneAsGrey)
Definition at line 379 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::Channels(), colmap::Bitmap::CloneAsGrey(), colmap::Bitmap::Data(), colmap::Bitmap::Height(), and colmap::Bitmap::Width().
BOOST_AUTO_TEST_CASE() [9/27]
BOOST_AUTO_TEST_CASE (TestCloneAsRGB)
Definition at line 369 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::Channels(), colmap::Bitmap::CloneAsRGB(), colmap::Bitmap::Data(), colmap::Bitmap::Height(), and colmap::Bitmap::Width().
BOOST_AUTO_TEST_CASE() [10/27]
BOOST_AUTO_TEST_CASE (TestConvertToColMajorArrayGrey)
Definition at line 182 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::ConvertToColMajorArray(), and colmap::Bitmap::SetPixel().
BOOST_AUTO_TEST_CASE() [11/27]
BOOST_AUTO_TEST_CASE (TestConvertToColMajorArrayRGB)
Definition at line 159 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::ConvertToColMajorArray(), and colmap::Bitmap::SetPixel().
BOOST_AUTO_TEST_CASE() [12/27]
BOOST_AUTO_TEST_CASE (TestConvertToRowMajorArrayGrey)
Definition at line 144 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::ConvertToRowMajorArray(), and colmap::Bitmap::SetPixel().
BOOST_AUTO_TEST_CASE() [13/27]
BOOST_AUTO_TEST_CASE (TestConvertToRowMajorArrayRGB)
Definition at line 121 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::ConvertToRowMajorArray(), and colmap::Bitmap::SetPixel().
BOOST_AUTO_TEST_CASE() [14/27]
BOOST_AUTO_TEST_CASE (TestDeallocate)
Definition at line 92 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::Channels(), colmap::Bitmap::Deallocate(), colmap::Bitmap::Height(), colmap::Bitmap::IsGrey(), colmap::Bitmap::IsRGB(), colmap::Bitmap::NumBytes(), and colmap::Bitmap::Width().
BOOST_AUTO_TEST_CASE() [15/27]
BOOST_AUTO_TEST_CASE (TestEmpty)
Definition at line 63 of file bitmap_test.cc.
References colmap::Bitmap::Channels(), colmap::Bitmap::Height(), colmap::Bitmap::IsGrey(), colmap::Bitmap::IsRGB(), and colmap::Bitmap::Width().
BOOST_AUTO_TEST_CASE() [16/27]
BOOST_AUTO_TEST_CASE (TestFill)
Definition at line 248 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), color, colmap::Bitmap::Fill(), colmap::Bitmap::GetPixel(), colmap::Bitmap::Height(), colmap::Bitmap::Width(), x, and y.
BOOST_AUTO_TEST_CASE() [17/27]
BOOST_AUTO_TEST_CASE (TestGetAndSetPixelGrey)
Definition at line 206 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), color, colmap::Bitmap::GetPixel(), and colmap::Bitmap::SetPixel().
BOOST_AUTO_TEST_CASE() [18/27]
BOOST_AUTO_TEST_CASE (TestGetAndSetPixelRGB)
Definition at line 197 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), color, colmap::Bitmap::GetPixel(), and colmap::Bitmap::SetPixel().
BOOST_AUTO_TEST_CASE() [19/27]
BOOST_AUTO_TEST_CASE (TestGetScanlineGrey)
Definition at line 234 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), color, colmap::Bitmap::Fill(), colmap::Bitmap::GetPixel(), and colmap::Bitmap::GetScanline().
BOOST_AUTO_TEST_CASE() [20/27]
BOOST_AUTO_TEST_CASE (TestGetScanlineRGB)
Definition at line 218 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), color, colmap::Bitmap::Fill(), colmap::Bitmap::GetPixel(), and colmap::Bitmap::GetScanline().
BOOST_AUTO_TEST_CASE() [21/27]
BOOST_AUTO_TEST_CASE (TestInterpolateBilinear)
Definition at line 277 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), color, colmap::Bitmap::Fill(), colmap::Bitmap::InterpolateBilinear(), and colmap::Bitmap::SetPixel().
BOOST_AUTO_TEST_CASE() [22/27]
BOOST_AUTO_TEST_CASE (TestInterpolateNearestNeighbor)
Definition at line 261 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), color, colmap::Bitmap::Fill(), colmap::Bitmap::InterpolateNearestNeighbor(), and colmap::Bitmap::SetPixel().
BOOST_AUTO_TEST_CASE() [23/27]
BOOST_AUTO_TEST_CASE (TestNumBytes)
Definition at line 112 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), and colmap::Bitmap::NumBytes().
BOOST_AUTO_TEST_CASE() [24/27]
BOOST_AUTO_TEST_CASE (TestRescaleGrey)
Definition at line 344 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::Channels(), colmap::Bitmap::Clone(), colmap::Bitmap::Height(), colmap::Bitmap::Rescale(), and colmap::Bitmap::Width().
BOOST_AUTO_TEST_CASE() [25/27]
BOOST_AUTO_TEST_CASE (TestRescaleRGB)
Definition at line 329 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::Channels(), colmap::Bitmap::Clone(), colmap::Bitmap::Height(), colmap::Bitmap::Rescale(), and colmap::Bitmap::Width().
BOOST_AUTO_TEST_CASE() [26/27]
BOOST_AUTO_TEST_CASE (TestSmoothGrey)
Definition at line 314 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::Channels(), colmap::Bitmap::Height(), colmap::Bitmap::SetPixel(), colmap::Bitmap::Smooth(), colmap::Bitmap::Width(), x, and y.
BOOST_AUTO_TEST_CASE() [27/27]
BOOST_AUTO_TEST_CASE (TestSmoothRGB)
Definition at line 291 of file bitmap_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::Channels(), color, colmap::Bitmap::GetPixel(), colmap::Bitmap::Height(), colmap::Bitmap::SetPixel(), colmap::Bitmap::Smooth(), colmap::Bitmap::Width(), x, and y.