ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/camera_models_test.cc File Reference
camera_models_test.cc File Reference
#include "util/testing.h"
#include "base/camera_models.h"
Macros
#define TEST_NAME "base/camera_models"
Functions
template<typename CameraModel >
void TestWorldToImageToWorld (const std::vector< double > params, const double u0, const double v0)
template<typename CameraModel >
void TestImageToWorldToImage (const std::vector< double > params, const double x0, const double y0)
template<typename CameraModel >
void TestModel (const std::vector< double > &params)
BOOST_AUTO_TEST_CASE (TestSimplePinhole)
BOOST_AUTO_TEST_CASE (TestPinhole)
BOOST_AUTO_TEST_CASE (TestSimpleRadial)
BOOST_AUTO_TEST_CASE (TestRadial)
BOOST_AUTO_TEST_CASE (TestOpenCV)
BOOST_AUTO_TEST_CASE (TestOpenCVFisheye)
BOOST_AUTO_TEST_CASE (TestFullOpenCV)
BOOST_AUTO_TEST_CASE (TestFOV)
BOOST_AUTO_TEST_CASE (TestSimpleRadialFisheye)
BOOST_AUTO_TEST_CASE (TestRadialFisheye)
BOOST_AUTO_TEST_CASE (TestThinPrismFisheye)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/camera_models"
Definition at line 32 of file camera_models_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/11]
BOOST_AUTO_TEST_CASE (TestFOV)
Definition at line 180 of file camera_models_test.cc.
References colmap::CameraModelInitializeParams(), e, and colmap::FOVCameraModel::model_id.
BOOST_AUTO_TEST_CASE() [2/11]
BOOST_AUTO_TEST_CASE (TestFullOpenCV)
Definition at line 173 of file camera_models_test.cc.
BOOST_AUTO_TEST_CASE() [3/11]
BOOST_AUTO_TEST_CASE (TestOpenCV)
Definition at line 161 of file camera_models_test.cc.
BOOST_AUTO_TEST_CASE() [4/11]
BOOST_AUTO_TEST_CASE (TestOpenCVFisheye)
Definition at line 167 of file camera_models_test.cc.
BOOST_AUTO_TEST_CASE() [5/11]
BOOST_AUTO_TEST_CASE (TestPinhole)
Definition at line 138 of file camera_models_test.cc.
BOOST_AUTO_TEST_CASE() [6/11]
BOOST_AUTO_TEST_CASE (TestRadial)
Definition at line 150 of file camera_models_test.cc.
BOOST_AUTO_TEST_CASE() [7/11]
BOOST_AUTO_TEST_CASE (TestRadialFisheye)
Definition at line 202 of file camera_models_test.cc.
BOOST_AUTO_TEST_CASE() [8/11]
BOOST_AUTO_TEST_CASE (TestSimplePinhole)
Definition at line 133 of file camera_models_test.cc.
BOOST_AUTO_TEST_CASE() [9/11]
BOOST_AUTO_TEST_CASE (TestSimpleRadial)
Definition at line 143 of file camera_models_test.cc.
BOOST_AUTO_TEST_CASE() [10/11]
BOOST_AUTO_TEST_CASE (TestSimpleRadialFisheye)
Definition at line 195 of file camera_models_test.cc.
BOOST_AUTO_TEST_CASE() [11/11]
BOOST_AUTO_TEST_CASE (TestThinPrismFisheye)
Definition at line 213 of file camera_models_test.cc.
TestImageToWorldToImage()
template<typename CameraModel > void TestImageToWorldToImage (const std::vector< double > params, const double x0, const double y0)
Definition at line 53 of file camera_models_test.cc.
References colmap::CameraModelImageToWorld(), e, x, and y.
TestModel()
template<typename CameraModel > void TestModel (const std::vector< double > & params)
Definition at line 66 of file camera_models_test.cc.
References colmap::CameraModelExtraParamsIdxs(), colmap::CameraModelFocalLengthIdxs(), colmap::CameraModelHasBogusParams(), colmap::CameraModelIdToName(), colmap::CameraModelImageToWorldThreshold(), colmap::CameraModelInitializeParams(), colmap::CameraModelNameToId(), colmap::CameraModelNumParams(), colmap::CameraModelParamsInfo(), colmap::CameraModelPrincipalPointIdxs(), colmap::CameraModelVerifyParams(), colmap::ExistsCameraModelWithId(), colmap::ExistsCameraModelWithName(), size, x, and y.
TestWorldToImageToWorld()
template<typename CameraModel > void TestWorldToImageToWorld (const std::vector< double > params, const double u0, const double v0)
Definition at line 40 of file camera_models_test.cc.
References colmap::CameraModelWorldToImage(), e, x, and y.