ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/camera_test.cc File Reference
camera_test.cc File Reference
#include "util/testing.h"
#include "base/camera.h"
#include "base/camera_models.h"
Macros
#define TEST_NAME "base/camera"
Functions
BOOST_AUTO_TEST_CASE (TestEmpty)
BOOST_AUTO_TEST_CASE (TestCameraId)
BOOST_AUTO_TEST_CASE (TestModelId)
BOOST_AUTO_TEST_CASE (TestWidthHeight)
BOOST_AUTO_TEST_CASE (TestFocalLength)
BOOST_AUTO_TEST_CASE (TestPriorFocalLength)
BOOST_AUTO_TEST_CASE (TestPrincipalPoint)
BOOST_AUTO_TEST_CASE (TestParamIdxs)
BOOST_AUTO_TEST_CASE (TestCalibrationMatrix)
BOOST_AUTO_TEST_CASE (TestParamsInfo)
BOOST_AUTO_TEST_CASE (TestParams)
BOOST_AUTO_TEST_CASE (TestParamsToString)
BOOST_AUTO_TEST_CASE (TestParamsFromString)
BOOST_AUTO_TEST_CASE (TestVerifyParams)
BOOST_AUTO_TEST_CASE (TestIsUndistorted)
BOOST_AUTO_TEST_CASE (TestHasBogusParams)
BOOST_AUTO_TEST_CASE (TestInitializeWithId)
BOOST_AUTO_TEST_CASE (TestInitializeWithName)
BOOST_AUTO_TEST_CASE (TestImageToWorld)
BOOST_AUTO_TEST_CASE (TestImageToWorldThreshold)
BOOST_AUTO_TEST_CASE (TestWorldToImage)
BOOST_AUTO_TEST_CASE (TestRescale)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/camera"
Definition at line 32 of file camera_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/22]
BOOST_AUTO_TEST_CASE (TestCalibrationMatrix)
Definition at line 141 of file camera_test.cc.
References colmap::Camera::CalibrationMatrix(), colmap::Camera::InitializeWithId(), and colmap::PinholeCameraModel::model_id.
BOOST_AUTO_TEST_CASE() [2/22]
BOOST_AUTO_TEST_CASE (TestCameraId)
Definition at line 56 of file camera_test.cc.
References colmap::Camera::CameraId(), colmap::kInvalidCameraId, and colmap::Camera::SetCameraId().
BOOST_AUTO_TEST_CASE() [3/22]
BOOST_AUTO_TEST_CASE (TestEmpty)
Definition at line 40 of file camera_test.cc.
References colmap::Camera::CameraId(), colmap::Camera::FocalLengthIdxs(), colmap::Camera::HasPriorFocalLength(), colmap::Camera::Height(), colmap::kInvalidCameraId, colmap::kInvalidCameraModelId, colmap::Camera::ModelId(), colmap::Camera::ModelName(), colmap::Camera::NumParams(), colmap::Camera::Params(), colmap::Camera::ParamsData(), colmap::Camera::ParamsInfo(), colmap::Camera::ParamsToString(), and colmap::Camera::Width().
BOOST_AUTO_TEST_CASE() [4/22]
BOOST_AUTO_TEST_CASE (TestFocalLength)
Definition at line 91 of file camera_test.cc.
References colmap::Camera::FocalLength(), colmap::Camera::FocalLengthX(), colmap::Camera::FocalLengthY(), colmap::Camera::InitializeWithId(), colmap::SimplePinholeCameraModel::model_id, colmap::PinholeCameraModel::model_id, colmap::Camera::SetFocalLength(), colmap::Camera::SetFocalLengthX(), and colmap::Camera::SetFocalLengthY().
BOOST_AUTO_TEST_CASE() [5/22]
BOOST_AUTO_TEST_CASE (TestHasBogusParams)
Definition at line 226 of file camera_test.cc.
References colmap::Camera::HasBogusParams(), colmap::Camera::InitializeWithId(), colmap::SimplePinholeCameraModel::model_id, colmap::SimpleRadialCameraModel::model_id, and colmap::Camera::Params().
BOOST_AUTO_TEST_CASE() [6/22]
BOOST_AUTO_TEST_CASE (TestImageToWorld)
Definition at line 298 of file camera_test.cc.
References colmap::Camera::ImageToWorld(), and colmap::Camera::InitializeWithName().
BOOST_AUTO_TEST_CASE() [7/22]
BOOST_AUTO_TEST_CASE (TestImageToWorldThreshold)
Definition at line 309 of file camera_test.cc.
References colmap::Camera::ImageToWorldThreshold(), colmap::Camera::InitializeWithName(), colmap::Camera::SetFocalLength(), and colmap::Camera::SetFocalLengthY().
BOOST_AUTO_TEST_CASE() [8/22]
BOOST_AUTO_TEST_CASE (TestInitializeWithId)
Definition at line 244 of file camera_test.cc.
References colmap::Camera::CameraId(), colmap::Camera::ExtraParamsIdxs(), colmap::Camera::FocalLength(), colmap::Camera::FocalLengthIdxs(), colmap::Camera::HasBogusParams(), colmap::Camera::HasPriorFocalLength(), colmap::Camera::Height(), colmap::Camera::InitializeWithId(), colmap::kInvalidCameraId, colmap::SimplePinholeCameraModel::model_id, colmap::Camera::ModelId(), colmap::Camera::ModelName(), colmap::SimplePinholeCameraModel::num_params, colmap::Camera::NumParams(), colmap::Camera::Params(), colmap::Camera::ParamsInfo(), colmap::Camera::ParamsToString(), colmap::Camera::PrincipalPointIdxs(), colmap::Camera::PrincipalPointX(), colmap::Camera::PrincipalPointY(), colmap::Camera::VerifyParams(), and colmap::Camera::Width().
BOOST_AUTO_TEST_CASE() [9/22]
BOOST_AUTO_TEST_CASE (TestInitializeWithName)
Definition at line 271 of file camera_test.cc.
References colmap::Camera::CameraId(), colmap::Camera::ExtraParamsIdxs(), colmap::Camera::FocalLength(), colmap::Camera::FocalLengthIdxs(), colmap::Camera::HasBogusParams(), colmap::Camera::HasPriorFocalLength(), colmap::Camera::Height(), colmap::Camera::InitializeWithName(), colmap::kInvalidCameraId, colmap::SimplePinholeCameraModel::model_id, colmap::Camera::ModelId(), colmap::Camera::ModelName(), colmap::SimplePinholeCameraModel::num_params, colmap::Camera::NumParams(), colmap::Camera::Params(), colmap::Camera::ParamsInfo(), colmap::Camera::ParamsToString(), colmap::Camera::PrincipalPointIdxs(), colmap::Camera::PrincipalPointX(), colmap::Camera::PrincipalPointY(), colmap::Camera::VerifyParams(), and colmap::Camera::Width().
BOOST_AUTO_TEST_CASE() [10/22]
BOOST_AUTO_TEST_CASE (TestIsUndistorted)
Definition at line 204 of file camera_test.cc.
References colmap::Camera::InitializeWithId(), colmap::Camera::IsUndistorted(), colmap::SimplePinholeCameraModel::model_id, colmap::SimpleRadialCameraModel::model_id, colmap::RadialCameraModel::model_id, colmap::OpenCVCameraModel::model_id, colmap::FullOpenCVCameraModel::model_id, and colmap::Camera::SetParams().
BOOST_AUTO_TEST_CASE() [11/22]
BOOST_AUTO_TEST_CASE (TestModelId)
Definition at line 63 of file camera_test.cc.
References colmap::kInvalidCameraModelId, colmap::SimplePinholeCameraModel::model_id, colmap::SimpleRadialCameraModel::model_id, colmap::Camera::ModelId(), colmap::Camera::ModelName(), colmap::SimplePinholeCameraModel::num_params, colmap::SimpleRadialCameraModel::num_params, colmap::Camera::NumParams(), colmap::Camera::SetModelId(), and colmap::Camera::SetModelIdFromName().
BOOST_AUTO_TEST_CASE() [12/22]
BOOST_AUTO_TEST_CASE (TestParamIdxs)
Definition at line 130 of file camera_test.cc.
References colmap::Camera::ExtraParamsIdxs(), colmap::Camera::FocalLengthIdxs(), colmap::FullOpenCVCameraModel::model_id, colmap::Camera::PrincipalPointIdxs(), and colmap::Camera::SetModelId().
BOOST_AUTO_TEST_CASE() [13/22]
BOOST_AUTO_TEST_CASE (TestParams)
Definition at line 157 of file camera_test.cc.
References colmap::Camera::InitializeWithId(), colmap::SimplePinholeCameraModel::model_id, colmap::Camera::NumParams(), colmap::Camera::Params(), colmap::Camera::ParamsData(), and colmap::Camera::SetParams().
BOOST_AUTO_TEST_CASE() [14/22]
BOOST_AUTO_TEST_CASE (TestParamsFromString)
Definition at line 183 of file camera_test.cc.
References colmap::SimplePinholeCameraModel::model_id, colmap::Camera::Params(), colmap::Camera::SetModelId(), and colmap::Camera::SetParamsFromString().
BOOST_AUTO_TEST_CASE() [15/22]
BOOST_AUTO_TEST_CASE (TestParamsInfo)
Definition at line 150 of file camera_test.cc.
References colmap::SimpleRadialCameraModel::model_id, colmap::Camera::ParamsInfo(), and colmap::Camera::SetModelId().
BOOST_AUTO_TEST_CASE() [16/22]
BOOST_AUTO_TEST_CASE (TestParamsToString)
Definition at line 177 of file camera_test.cc.
References colmap::Camera::InitializeWithId(), colmap::SimplePinholeCameraModel::model_id, and colmap::Camera::ParamsToString().
BOOST_AUTO_TEST_CASE() [17/22]
BOOST_AUTO_TEST_CASE (TestPrincipalPoint)
Definition at line 117 of file camera_test.cc.
References colmap::Camera::InitializeWithId(), colmap::PinholeCameraModel::model_id, colmap::Camera::PrincipalPointX(), colmap::Camera::PrincipalPointY(), colmap::Camera::SetPrincipalPointX(), and colmap::Camera::SetPrincipalPointY().
BOOST_AUTO_TEST_CASE() [18/22]
BOOST_AUTO_TEST_CASE (TestPriorFocalLength)
Definition at line 108 of file camera_test.cc.
References colmap::Camera::HasPriorFocalLength(), and colmap::Camera::SetPriorFocalLength().
BOOST_AUTO_TEST_CASE() [19/22]
BOOST_AUTO_TEST_CASE (TestRescale)
Definition at line 333 of file camera_test.cc.
References colmap::Camera::FocalLength(), colmap::Camera::FocalLengthX(), colmap::Camera::FocalLengthY(), colmap::Camera::Height(), colmap::Camera::InitializeWithName(), colmap::Camera::PrincipalPointX(), colmap::Camera::PrincipalPointY(), colmap::Camera::Rescale(), and colmap::Camera::Width().
BOOST_AUTO_TEST_CASE() [20/22]
BOOST_AUTO_TEST_CASE (TestVerifyParams)
Definition at line 195 of file camera_test.cc.
References colmap::Camera::InitializeWithId(), colmap::SimplePinholeCameraModel::model_id, colmap::Camera::Params(), and colmap::Camera::VerifyParams().
BOOST_AUTO_TEST_CASE() [21/22]
BOOST_AUTO_TEST_CASE (TestWidthHeight)
Definition at line 79 of file camera_test.cc.
References colmap::Camera::Height(), colmap::Camera::SetHeight(), colmap::Camera::SetWidth(), and colmap::Camera::Width().
BOOST_AUTO_TEST_CASE() [22/22]
BOOST_AUTO_TEST_CASE (TestWorldToImage)
Definition at line 322 of file camera_test.cc.
References colmap::Camera::InitializeWithName(), and colmap::Camera::WorldToImage().