ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/camera_rig_test.cc File Reference
camera_rig_test.cc File Reference
#include "util/testing.h"
#include "base/camera_rig.h"
Macros
#define TEST_NAME "base/camera_rig"
Functions
BOOST_AUTO_TEST_CASE (TestEmpty)
BOOST_AUTO_TEST_CASE (TestAddCamera)
BOOST_AUTO_TEST_CASE (TestAddSnapshot)
BOOST_AUTO_TEST_CASE (TestCheck)
BOOST_AUTO_TEST_CASE (TestComputeScale)
BOOST_AUTO_TEST_CASE (TestComputeRelativePoses)
BOOST_AUTO_TEST_CASE (TestComputeAbsolutePose)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/camera_rig"
Definition at line 32 of file camera_rig_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/7]
BOOST_AUTO_TEST_CASE (TestAddCamera)
Definition at line 47 of file camera_rig_test.cc.
References colmap::CameraRig::AddCamera(), colmap::ComposeIdentityQuaternion(), colmap::CameraRig::GetCameraIds(), colmap::CameraRig::HasCamera(), colmap::CameraRig::NumCameras(), colmap::CameraRig::NumSnapshots(), colmap::CameraRig::RelativeQvec(), and colmap::CameraRig::RelativeTvec().
BOOST_AUTO_TEST_CASE() [2/7]
BOOST_AUTO_TEST_CASE (TestAddSnapshot)
Definition at line 75 of file camera_rig_test.cc.
References colmap::CameraRig::AddCamera(), colmap::CameraRig::AddSnapshot(), colmap::ComposeIdentityQuaternion(), colmap::CameraRig::GetCameraIds(), colmap::CameraRig::NumCameras(), colmap::CameraRig::NumSnapshots(), and colmap::CameraRig::Snapshots().
BOOST_AUTO_TEST_CASE() [3/7]
BOOST_AUTO_TEST_CASE (TestCheck)
Definition at line 112 of file camera_rig_test.cc.
References colmap::CameraRig::AddCamera(), colmap::Reconstruction::AddCamera(), colmap::Reconstruction::AddImage(), colmap::CameraRig::AddSnapshot(), colmap::Camera::CameraId(), colmap::CameraRig::Check(), colmap::ComposeIdentityQuaternion(), colmap::Camera::InitializeWithName(), colmap::Camera::SetCameraId(), colmap::Image::SetCameraId(), colmap::Image::SetImageId(), and colmap::CameraRig::SetRefCameraId().
BOOST_AUTO_TEST_CASE() [4/7]
BOOST_AUTO_TEST_CASE (TestComputeAbsolutePose)
Definition at line 288 of file camera_rig_test.cc.
References colmap::CameraRig::AddCamera(), colmap::Reconstruction::AddCamera(), colmap::Reconstruction::AddImage(), colmap::CameraRig::AddSnapshot(), colmap::Camera::CameraId(), colmap::CameraRig::Check(), colmap::ComposeIdentityQuaternion(), colmap::CameraRig::ComputeAbsolutePose(), colmap::Camera::InitializeWithName(), colmap::Camera::SetCameraId(), colmap::Image::SetCameraId(), colmap::Image::SetImageId(), colmap::Image::SetQvec(), colmap::CameraRig::SetRefCameraId(), and colmap::Image::SetTvec().
BOOST_AUTO_TEST_CASE() [5/7]
BOOST_AUTO_TEST_CASE (TestComputeRelativePoses)
Definition at line 203 of file camera_rig_test.cc.
References colmap::CameraRig::AddCamera(), colmap::Reconstruction::AddCamera(), colmap::Reconstruction::AddImage(), colmap::CameraRig::AddSnapshot(), colmap::Camera::CameraId(), colmap::CameraRig::Check(), colmap::ComposeIdentityQuaternion(), colmap::CameraRig::ComputeRelativePoses(), colmap::Camera::InitializeWithName(), colmap::CameraRig::RelativeQvec(), colmap::CameraRig::RelativeTvec(), colmap::Camera::SetCameraId(), colmap::Image::SetCameraId(), colmap::Image::SetImageId(), colmap::Image::SetQvec(), colmap::CameraRig::SetRefCameraId(), and colmap::Image::SetTvec().
BOOST_AUTO_TEST_CASE() [6/7]
BOOST_AUTO_TEST_CASE (TestComputeScale)
Definition at line 159 of file camera_rig_test.cc.
References colmap::CameraRig::AddCamera(), colmap::Reconstruction::AddCamera(), colmap::Reconstruction::AddImage(), colmap::CameraRig::AddSnapshot(), colmap::Camera::CameraId(), colmap::CameraRig::Check(), colmap::ComposeIdentityQuaternion(), colmap::CameraRig::ComputeScale(), colmap::Reconstruction::Image(), colmap::Camera::InitializeWithName(), colmap::IsNaN(), colmap::Camera::SetCameraId(), colmap::Image::SetCameraId(), colmap::Image::SetImageId(), colmap::Image::SetQvec(), colmap::CameraRig::SetRefCameraId(), and colmap::Image::SetTvec().
BOOST_AUTO_TEST_CASE() [7/7]
BOOST_AUTO_TEST_CASE (TestEmpty)
Definition at line 39 of file camera_rig_test.cc.
References colmap::CameraRig::GetCameraIds(), colmap::CameraRig::HasCamera(), colmap::CameraRig::NumCameras(), and colmap::CameraRig::NumSnapshots().