ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/cc2DLabel.cpp File Reference
cc2DLabel.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecv2DLabel.h>
#include <ecvGenericMesh.h>
#include <ecvGenericPointCloud.h>
#include "../casters.h"
Functions
void define_cc2DLabel (py::module &m)
Function Documentation
define_cc2DLabel()
void define_cc2DLabel (py::module & m)
Definition at line 21 of file cc2DLabel.cpp.
References cc2DLabel::addPickedPoint(), cc2DLabel::clear(), cc2DLabel::PickedPoint::cloud, cc2DLabel::PickedPoint::cloudOrVertices(), cc2DLabel::displayPointLegend(), cc2DLabel::PickedPoint::entity(), cc2DLabel::PickedPoint::entityCenterPoint, cc2DLabel::getLabelContent(), cc2DLabel::getPickedPoint(), cc2DLabel::PickedPoint::getPointPosition(), cc2DLabel::getRawName(), cc2DLabel::getTitle(), cc2DLabel::PickedPoint::getUniqueID(), cc2DLabel::PickedPoint::index, cc2DLabel::isCollapsed(), cc2DLabel::isDisplayedIn2D(), cc2DLabel::isPointLegendDisplayed(), cc2DLabel::PickedPoint::itemTitle(), cc2DLabel::PickedPoint::mesh, cc2DLabel::PickedPoint::pos2D, cc2DLabel::PickedPoint::prefix(), cc2DLabel::setCollapsed(), cc2DLabel::setDisplayedIn2D(), cc2DLabel::setPosition(), cc2DLabel::setRelativeMarkerScale(), cc2DLabel::size(), and cc2DLabel::PickedPoint::uv.
Referenced by define_qcc_db().