ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccCameraSensor.cpp File Reference
ccCameraSensor.cpp File Reference
#include <pybind11/native_enum.h>
#include <pybind11/pybind11.h>
#include <ecvCameraSensor.h>
#include <ecvMesh.h>
#include <ecvPointCloud.h>
#include "../casters.h"
Functions
void define_ccCameraSensor (py::module &m)
Function Documentation
define_ccCameraSensor()
void define_ccCameraSensor (py::module & m)
Definition at line 20 of file ccCameraSensor.cpp.
References ccCameraSensor::IntrinsicParameters::arrayHeight, ccCameraSensor::IntrinsicParameters::arrayWidth, ccCameraSensor::FrustumInformation::center, data, ccCameraSensor::FrustumInformation::drawFrustum, ccCameraSensor::FrustumInformation::drawSidePlanes, ccCameraSensor::FrustumInformation::frustumCorners, ccCameraSensor::FrustumInformation::frustumHull, ccCameraSensor::getHorizFocal_pix(), ccCameraSensor::getIntrinsicParameters(), ccCameraSensor::IntrinsicParameters::GetKinectDefaults(), ccCameraSensor::LensDistortionParameters::getModel(), ccCameraSensor::getVerticalFov_rad(), ccCameraSensor::IntrinsicParameters::horizFocal_pix(), ccCameraSensor::FrustumInformation::initFrustumCorners(), ccCameraSensor::FrustumInformation::initFrustumHull(), ccCameraSensor::FrustumInformation::isComputed, ccCameraSensor::RadialDistortionParameters::k1, ccCameraSensor::RadialDistortionParameters::k2, ccCameraSensor::ExtendedRadialDistortionParameters::k3, ccCameraSensor::setIntrinsicParameters(), ccCameraSensor::setVertFocal_pix(), ccCameraSensor::setVerticalFov_rad(), ccCameraSensor::IntrinsicParameters::skew, ccCameraSensor::IntrinsicParameters::vertFocal_pix, ccCameraSensor::IntrinsicParameters::vFOV_rad, x, y, z, ccCameraSensor::IntrinsicParameters::zFar_mm, and ccCameraSensor::IntrinsicParameters::zNear_mm.
Referenced by define_qcc_db().