ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccCircle.cpp File Reference
ccCircle.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvCircle.h>
#include <ecvObject.h>
#include <ecvPolyline.h>
#include "../casters.h"
Functions
void define_ccCircle (py::module &m)
Function Documentation
define_ccCircle()
void define_ccCircle (py::module & m)
Definition at line 21 of file ccCircle.cpp.
References ccCircle::clone(), ccCircle::getRadius(), ccCircle::getResolution(), ccUniqueIDGenerator::InvalidUniqueID, ccCircle::setRadius(), and ccCircle::setResolution().
Referenced by define_qcc_db().