ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/Runtime/ccCommandLine.cpp File Reference
ccCommandLine.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvCommandLineInterface.h>
#include <ecvGenericMesh.h>
#include "../../wrapper/pycc/src/casters.h"
Functions
PYBIND11_MAKE_OPAQUE (std::vector< CLCloudDesc >)
PYBIND11_MAKE_OPAQUE (std::vector< CLMeshDesc >)
void define_ccCommandLine (py::module &m)
Function Documentation
define_ccCommandLine()
void define_ccCommandLine (py::module & m)
Definition at line 23 of file ccCommandLine.cpp.
References CLEntityDesc::basename, CLOUD, ccCommandLineInterface::clouds(), ccCommandLineInterface::GlobalShiftOptions::customGlobalShift, ccCommandLineInterface::exportEntity(), filename, CLEntityDesc::getEntity(), ccCommandLineInterface::getExportFilename(), GROUP, CLGroupDesc::groupEntity, CLEntityDesc::indexInFile, MESH, CLMeshDesc::mesh, ccCommandLineInterface::meshes(), ccCommandLineInterface::GlobalShiftOptions::mode, ccCommandLineInterface::NoOptions, CLEntityDesc::path, CLCloudDesc::pc, ccCommandLineInterface::saveClouds(), and ccCommandLineInterface::saveMeshes().
Referenced by PYBIND11_EMBEDDED_MODULE().
PYBIND11_MAKE_OPAQUE() [1/2]
PYBIND11_MAKE_OPAQUE (std::vector< CLCloudDesc >)
PYBIND11_MAKE_OPAQUE() [2/2]
PYBIND11_MAKE_OPAQUE (std::vector< CLMeshDesc >)