ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccColorScale.cpp File Reference
ccColorScale.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvColorScale.h>
#include <QColor>
#include "../casters.h"
Functions
void define_ccColorScale (py::module &m)
Function Documentation
define_ccColorScale()
void define_ccColorScale (py::module & m)
Definition at line 21 of file ccColorScale.cpp.
References ccColorScale::clear(), ccColorScale::customLabels(), ccColorScale::DEFAULT_STEPS, ccColorScale::generateNewUuid(), ccColorScaleElement::getColor(), ccColorScale::getColorByIndex(), ccColorScale::getColorByRelativePos(), ccColorScale::getColorByValue(), ccColorScale::getName(), ccColorScaleElement::getRelativePos(), ccColorScale::getRelativePosition(), ccColorScale::getUuid(), ccColorScale::insert(), ccColorScale::isLocked(), ccColorScale::isRelative(), ccColorScaleElement::IsSmaller(), ccColorScale::LoadFromXML(), ccColorScale::MAX_STEPS, ccColorScale::MIN_STEPS, ccColorScale::remove(), ccColorScale::saveAsXML(), ccColorScale::setAbsolute(), ccColorScaleElement::setColor(), ccColorScale::setCustomLabels(), ccColorScale::setLocked(), ccColorScale::setName(), ccColorScale::setRelative(), ccColorScaleElement::setRelativePos(), ccColorScale::setUuid(), ccColorScale::step(), ccColorScale::stepCount(), ccColorScale::Label::text, ccColorScale::update(), and ccColorScale::Label::value.
Referenced by define_qcc_db().