ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/cccorelib.cpp File Reference
cccorelib.cpp File Reference
#include <limits>
#include <pybind11/functional.h>
#include <pybind11/numpy.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <AutoSegmentationTools.h>
#include <BoundingBox.h>
#include <CVGeom.h>
#include <CVPointCloud.h>
#include <ChamferDistanceTransform.h>
#include <GenericProgressCallback.h>
#include <GeometricalAnalysisTools.h>
#include <Grid3D.h>
#include <ReferenceCloud.h>
#include <TrueKdTree.h>
#include "cccorelib.h"
Classes
class NumpyCloud
Functions
void define_AutoSegmentationTools (py::module &)
void define_BoundingBox (py::module &)
void define_CCGeom (py::module &)
void define_CCMath (py::module &)
void define_CCConst (py::module &)
void define_CCShareable (py::module &)
void define_ChamferDistanceTransform (py::module &)
void define_CloudSamplingTools (py::module &)
void define_DgmOctree (py::module &)
void define_DgmOctreeReferenceCloud (py::module &)
void define_GenericCloud (py::module &)
void define_TrueKdTree (py::module &)
void define_GenericDistribution (py::module &)
void define_StatisticalTestingTools (py::module &)
void define_GenericTriangle (py::module &)
void define_SimpleTriangle (py::module &)
void define_GenericIndexedCloud (py::module &)
void define_GenericProgressCallback (py::module &)
void define_GeometricalAnalysisTools (py::module &)
void define_GenericMesh (py::module &)
void define_SimpleMesh (py::module &cccorelib)
void define_GenericIndexedMesh (py::module &)
void define_WeibullDistribution (py::module &)
void define_ScalarField (py::module &cccorelib)
void define_ScalarFieldTools (py::module &cccorelib)
void define_RegistrationTools (py::module &cccorelib)
void define_ReferenceCloud (py::module &cccorelib)
void define_Polyline (py::module &cccorelib)
void define_PointProjectionTools (py::module &cccorelib)
void define_GenericIndexedCloudPersist (py::module &cccorelib)
void define_PointCloud (py::module &cccorelib)
void define_GenericOctree (py::module &cccorelib)
void define_KdTree (py::module &cccorelib)
void define_LocalModel (py::module &cccorelib)
void define_ManualSegmentationTools (py::module &)
void define_CCMiscTools (py::module &)
void define_NormalDistribution (py::module &)
void define_Delaunay2dMesh (py::module &)
void define_ErrorFunction (py::module &)
void define_FastMarching (py::module &)
void define_DistanceComputationTools (py::module &)
void define_cccorelib (py::module &m)
PYBIND11_MODULE (cccorelib, m)
Function Documentation
define_AutoSegmentationTools()
void define_AutoSegmentationTools (py::module & cccorelib)
Definition at line 18 of file AutoSegmentationTools.cpp.
References cloudViewer::AutoSegmentationTools::extractConnectedComponents(), cloudViewer::AutoSegmentationTools::frontPropagationBasedSegmentation(), and cloudViewer::AutoSegmentationTools::labelConnectedComponents().
Referenced by define_cccorelib().
define_BoundingBox()
void define_BoundingBox (py::module & cccorelib)
Definition at line 16 of file BoundingBox.cpp.
References cloudViewer::BoundingBoxTpl< PointCoordinateType >::add(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::clear(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::computeVolume(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::contains(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::getCenter(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::getDiagNorm(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::getDiagNormd(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::getDiagVec(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::getMaxBoxDim(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::getMinBoxDim(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::isValid(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::minDistTo(), and cloudViewer::BoundingBoxTpl< PointCoordinateType >::setValidity().
Referenced by define_cccorelib().
define_CCConst()
void define_CCConst (py::module & cccorelib)
Definition at line 15 of file CCConst.cpp.
References CHAMFER_111, CHAMFER_345, CV_LOCAL_MODEL_MIN_SIZE, LS, NAN_VALUE, NO_MODEL, PC_NAN, PC_ONE, POINT_HIDDEN, POINT_OUT_OF_FOV, POINT_OUT_OF_RANGE, POINT_VISIBLE, QUADRIC, SQRT_3, TRI, ZERO_TOLERANCE_D, ZERO_TOLERANCE_F, ZERO_TOLERANCE_POINT_COORDINATE, and ZERO_TOLERANCE_SCALAR.
Referenced by define_cccorelib().
define_cccorelib()
void define_cccorelib (py::module & m)
Definition at line 261 of file cccorelib.cpp.
References define_AutoSegmentationTools(), define_BoundingBox(), define_CCConst(), define_CCGeom(), define_CCMath(), define_CCMiscTools(), define_CCShareable(), define_ChamferDistanceTransform(), define_CloudSamplingTools(), define_Delaunay2dMesh(), define_DgmOctree(), define_DgmOctreeReferenceCloud(), define_DistanceComputationTools(), define_ErrorFunction(), define_FastMarching(), define_GenericCloud(), define_GenericDistribution(), define_GenericIndexedCloud(), define_GenericIndexedCloudPersist(), define_GenericIndexedMesh(), define_GenericMesh(), define_GenericOctree(), define_GenericProgressCallback(), define_GenericTriangle(), define_GeometricalAnalysisTools(), define_KdTree(), define_LocalModel(), define_ManualSegmentationTools(), define_NormalDistribution(), define_PointCloud(), define_PointProjectionTools(), define_Polyline(), define_ReferenceCloud(), define_RegistrationTools(), define_ScalarField(), define_ScalarFieldTools(), define_SimpleMesh(), define_SimpleTriangle(), define_StatisticalTestingTools(), define_TrueKdTree(), and define_WeibullDistribution().
Referenced by PYBIND11_MODULE().
define_CCGeom()
void define_CCGeom (py::module & cccorelib)
Definition at line 138 of file CCGeom.cpp.
References DEFINE_CCVECTOR3, DEFINE_TUPLE3TPL, and DEFINE_VECTOR2TPL_TYPE.
Referenced by define_cccorelib().
define_CCMath()
void define_CCMath (py::module & cccorelib)
Definition at line 15 of file CCMath.cpp.
References cloudViewer::DegreesToRadians(), cloudViewer::GreaterThanEpsilon(), cloudViewer::LessThanEpsilon(), and cloudViewer::RadiansToDegrees().
Referenced by define_cccorelib().
define_CCMiscTools()
void define_CCMiscTools (py::module & cccorelib)
Definition at line 15 of file CCMiscTools.cpp.
References cloudViewer::CCMiscTools::ComputeBaseVectors(), cloudViewer::CCMiscTools::EnlargeBox(), cloudViewer::CCMiscTools::MakeMinAndMaxCubical(), cloudViewer::CCMiscTools::TriBoxOverlap(), and cloudViewer::CCMiscTools::TriBoxOverlapd().
Referenced by define_cccorelib().
define_CCShareable()
void define_CCShareable (py::module & cccorelib)
Definition at line 17 of file CCShareable.cpp.
References CCShareable::getLinkCount(), CCShareable::link(), and CCShareable::release().
Referenced by define_cccorelib().
define_ChamferDistanceTransform()
void define_ChamferDistanceTransform (py::module & cccorelib)
Definition at line 15 of file ChamferDistanceTransform.cpp.
References cloudViewer::ChamferDistanceTransform::init(), cloudViewer::ChamferDistanceTransform::MAX_DIST, cloudViewer::ChamferDistanceTransform::propagateDistance(), and size.
Referenced by define_cccorelib().
define_CloudSamplingTools()
void define_CloudSamplingTools (py::module & cccorelib)
Definition at line 21 of file CloudSamplingTools.cpp.
References cloudViewer::CloudSamplingTools::SFModulationParams::a, cloudViewer::CloudSamplingTools::SFModulationParams::b, cloudViewer::CloudSamplingTools::SFModulationParams::enabled, cloudViewer::CloudSamplingTools::noiseFilter(), cloudViewer::CloudSamplingTools::resampleCloudSpatially(), cloudViewer::CloudSamplingTools::resampleCloudWithOctree(), cloudViewer::CloudSamplingTools::resampleCloudWithOctreeAtLevel(), cloudViewer::CloudSamplingTools::sorFilter(), cloudViewer::CloudSamplingTools::subsampleCloudRandomly(), cloudViewer::CloudSamplingTools::subsampleCloudWithOctree(), and cloudViewer::CloudSamplingTools::subsampleCloudWithOctreeAtLevel().
Referenced by define_cccorelib().
define_Delaunay2dMesh()
void define_Delaunay2dMesh (py::module & cccorelib)
Definition at line 19 of file Delaynay2dMesh.cpp.
References cloudViewer::Delaunay2dMesh::Available(), cloudViewer::Delaunay2dMesh::buildMesh(), cloudViewer::Delaunay2dMesh::getAssociatedCloud(), cloudViewer::Delaunay2dMesh::getTriangleVertIndexesArray(), cloudViewer::Delaunay2dMesh::linkMeshWith(), cloudViewer::Delaunay2dMesh::removeOuterTriangles(), cloudViewer::Delaunay2dMesh::removeTrianglesWithEdgesLongerThan(), cloudViewer::Delaunay2dMesh::TesselateContour(), and cloudViewer::Delaunay2dMesh::USE_ALL_POINTS.
Referenced by define_cccorelib().
define_DgmOctree()
void define_DgmOctree (py::module & cccorelib)
Definition at line 21 of file DgmOctree.cpp.
Referenced by define_cccorelib().
define_DgmOctreeReferenceCloud()
void define_DgmOctreeReferenceCloud (py::module & cccorelib)
Definition at line 16 of file DgmOctreeReferenceCloud.cpp.
References cloudViewer::DgmOctreeReferenceCloud::forwardIterator().
Referenced by define_cccorelib().
define_DistanceComputationTools()
void define_DistanceComputationTools (py::module & cccorelib)
Definition at line 15 of file DistanceComputationTools.cpp.
Referenced by define_cccorelib().
define_ErrorFunction()
void define_ErrorFunction (py::module & cccorelib)
Definition at line 15 of file ErrorFunction.cpp.
References cloudViewer::c_erfRelativeError, cloudViewer::ErrorFunction::erf(), and cloudViewer::ErrorFunction::erfc().
Referenced by define_cccorelib().
define_FastMarching()
void define_FastMarching (py::module & cccorelib)
Definition at line 18 of file FastMarching.cpp.
References cloudViewer::c_FastMarchingNeighbourPosShift, cloudViewer::FastMarching::cleanLastPropagation(), cloudViewer::FastMarching::getTime(), cloudViewer::FastMarching::setExtendedConnectivity(), and cloudViewer::FastMarching::setSeedCell().
Referenced by define_cccorelib().
define_GenericCloud()
void define_GenericCloud (py::module & cccorelib)
Definition at line 16 of file GenericCloud.cpp.
References cloudViewer::GenericCloud::enableScalarField(), cloudViewer::GenericCloud::forEach(), cloudViewer::GenericCloud::getBoundingBox(), cloudViewer::GenericCloud::getNextPoint(), cloudViewer::GenericCloud::getPointScalarValue(), cloudViewer::GenericCloud::placeIteratorAtBeginning(), cloudViewer::GenericCloud::setPointScalarValue(), cloudViewer::GenericCloud::size(), and cloudViewer::GenericCloud::testVisibility().
Referenced by define_cccorelib().
define_GenericDistribution()
void define_GenericDistribution (py::module & cccorelib)
Definition at line 20 of file GenericDistribution.cpp.
References cloudViewer::GenericDistribution::computeChi2Dist(), cloudViewer::GenericDistribution::computeP(), cloudViewer::GenericDistribution::computeParameters(), cloudViewer::GenericDistribution::computePfromZero(), cloudViewer::GenericDistribution::getName(), and cloudViewer::GenericDistribution::isValid().
Referenced by define_cccorelib().
define_GenericIndexedCloud()
void define_GenericIndexedCloud (py::module & cccorelib)
Definition at line 15 of file GenericIndexedCloud.cpp.
References size, and patch::to_string().
Referenced by define_cccorelib().
define_GenericIndexedCloudPersist()
void define_GenericIndexedCloudPersist (py::module & cccorelib)
Definition at line 16 of file GenericIndexedCloudPersist.cpp.
References cloudViewer::GenericIndexedCloudPersist::getPointPersistentPtr().
Referenced by define_cccorelib().
define_GenericIndexedMesh()
void define_GenericIndexedMesh (py::module & cccorelib)
Definition at line 17 of file GenericIndexedMesh.cpp.
References cloudViewer::GenericIndexedMesh::_getTriangle(), cloudViewer::GenericIndexedMesh::getNextTriangleVertIndexes(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, and size.
Referenced by define_cccorelib().
define_GenericMesh()
void define_GenericMesh (py::module & cccorelib)
Definition at line 16 of file GenericMesh.cpp.
References cloudViewer::GenericMesh::_getNextTriangle(), cloudViewer::GenericMesh::forEach(), cloudViewer::GenericMesh::getBoundingBox(), cloudViewer::GenericMesh::placeIteratorAtBeginning(), and cloudViewer::GenericMesh::size().
Referenced by define_cccorelib().
define_GenericOctree()
void define_GenericOctree (py::module & cccorelib)
Definition at line 16 of file GenericOctree.cpp.
Referenced by define_cccorelib().
define_GenericProgressCallback()
void define_GenericProgressCallback (py::module & cccorelib)
Definition at line 15 of file GenericProgressCallback.cpp.
References cloudViewer::GenericProgressCallback::isCancelRequested(), cloudViewer::NormalizedProgress::oneStep(), cloudViewer::NormalizedProgress::reset(), cloudViewer::NormalizedProgress::scale(), cloudViewer::GenericProgressCallback::setInfo(), cloudViewer::GenericProgressCallback::setMethodTitle(), cloudViewer::GenericProgressCallback::start(), cloudViewer::NormalizedProgress::steps(), cloudViewer::GenericProgressCallback::stop(), cloudViewer::GenericProgressCallback::textCanBeEdited(), and cloudViewer::GenericProgressCallback::update().
Referenced by define_cccorelib().
define_GenericTriangle()
void define_GenericTriangle (py::module & cccorelib)
Definition at line 17 of file GenericTriangle.cpp.
References cloudViewer::GenericTriangle::_getA(), cloudViewer::GenericTriangle::_getB(), and cloudViewer::GenericTriangle::_getC().
Referenced by define_cccorelib().
define_GeometricalAnalysisTools()
void define_GeometricalAnalysisTools (py::module & cccorelib)
Definition at line 19 of file GeometricalAnalysisTools.cpp.
Referenced by define_cccorelib().
define_KdTree()
void define_KdTree (py::module & cccorelib)
Definition at line 20 of file KdTree.cpp.
References cloudViewer::KDTree::buildFromCloud(), cloudViewer::KDTree::getAssociatedCloud(), and points.
Referenced by define_cccorelib().
define_LocalModel()
void define_LocalModel (py::module & cccorelib)
Definition at line 15 of file LocalModel.cpp.
References cloudViewer::LocalModel::computeDistanceFromModelToPoint(), cloudViewer::LocalModel::getCenter(), cloudViewer::LocalModel::getSquareSize(), and cloudViewer::LocalModel::getType().
Referenced by define_cccorelib().
define_ManualSegmentationTools()
void define_ManualSegmentationTools (py::module & cccorelib)
Definition at line 20 of file ManualSegmentationTools.cpp.
Referenced by define_cccorelib().
define_NormalDistribution()
void define_NormalDistribution (py::module & cccorelib)
Definition at line 17 of file NormalDistribution.cpp.
References cloudViewer::NormalDistribution::computeParameters(), cloudViewer::NormalDistribution::computeRobustParameters(), cloudViewer::NormalDistribution::getMu(), cloudViewer::NormalDistribution::getSigma2(), cloudViewer::core::make_pair(), and cloudViewer::NormalDistribution::setParameters().
Referenced by define_cccorelib().
define_PointCloud()
void define_PointCloud (py::module & cccorelib)
Definition at line 14 of file PointCloud.cpp.
References DEFINE_POINTCLOUDTPL.
Referenced by define_cccorelib().
define_PointProjectionTools()
void define_PointProjectionTools (py::module & cccorelib)
Definition at line 22 of file PointProjectionTools.cpp.
References cloudViewer::DELAUNAY_2D_AXIS_ALIGNED, and cloudViewer::DELAUNAY_2D_BEST_LS_PLANE.
Referenced by define_cccorelib().
define_Polyline()
void define_Polyline (py::module & cccorelib)
Definition at line 15 of file Polyline.cpp.
References cloudViewer::Polyline::clear(), cloudViewer::Polyline::isClosed(), and cloudViewer::Polyline::setClosed().
Referenced by define_cccorelib().
define_ReferenceCloud()
void define_ReferenceCloud (py::module & cccorelib)
Definition at line 19 of file ReferenceCloud.cpp.
References std::swap().
Referenced by define_cccorelib().
define_RegistrationTools()
void define_RegistrationTools (py::module & cccorelib)
Definition at line 17 of file RegistrationTools.cpp.
References cloudViewer::ICPRegistrationTools::Parameters::adjustScale, cloudViewer::HornRegistrationTools::ComputeRMS(), cloudViewer::ICPRegistrationTools::Parameters::convType, cloudViewer::ICPRegistrationTools::Parameters::dataWeights, cloudViewer::ICPRegistrationTools::Parameters::filterOutFarthestPoints, cloudViewer::RegistrationTools::FilterTransformation(), cloudViewer::ICPRegistrationTools::Parameters::finalOverlapRatio, cloudViewer::HornRegistrationTools::FindAbsoluteOrientation(), cloudViewer::ICPRegistrationTools::Parameters::maxThreadCount, cloudViewer::ICPRegistrationTools::Parameters::minRMSDecrease, cloudViewer::ICPRegistrationTools::Parameters::modelWeights, cloudViewer::ICPRegistrationTools::Parameters::nbMaxIterations, cloudViewer::ICPRegistrationTools::Register(), cloudViewer::FPCSRegistrationTools::RegisterClouds(), cloudViewer::ICPRegistrationTools::Parameters::samplingLimit, and cloudViewer::ICPRegistrationTools::Parameters::transformationFilters.
Referenced by define_cccorelib().
define_ScalarField()
void define_ScalarField (py::module & cccorelib)
Definition at line 155 of file ScalarField.cpp.
References cloudViewer::ScalarField::addElement(), cloudViewer::ScalarField::computeMeanAndVariance(), cloudViewer::ScalarField::computeMinAndMax(), copy, count, cloudViewer::ScalarField::currentSize(), cloudViewer::ScalarField::fill(), cloudViewer::ScalarField::flagValueAsInvalid(), ScalarFieldView::get_item(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), cloudViewer::ScalarField::getName(), ScalarFieldView::len(), cloudViewer::ScalarField::NaN(), cloudViewer::ScalarField::reserveSafe(), cloudViewer::ScalarField::resizeSafe(), ScalarFieldView::set_item(), cloudViewer::ScalarField::setName(), cloudViewer::ScalarField::setValue(), size, and cloudViewer::ScalarField::ValidValue().
Referenced by define_cccorelib().
define_ScalarFieldTools()
void define_ScalarFieldTools (py::module & cccorelib)
Definition at line 25 of file ScalarFieldTools.cpp.
References cloudViewer::ScalarFieldTools::computeScalarFieldExtremas(), cloudViewer::KMeanClass::maxValue, cloudViewer::KMeanClass::mean, cloudViewer::KMeanClass::minValue, and cloudViewer::ScalarFieldTools::SetScalarValueToNaN().
Referenced by define_cccorelib().
define_SimpleMesh()
void define_SimpleMesh (py::module & cccorelib)
Definition at line 18 of file SimpleMesh.cpp.
References cloudViewer::SimpleMesh::addTriangle(), cloudViewer::SimpleMesh::capacity(), cloudViewer::SimpleMesh::clear(), cloudViewer::SimpleMesh::reserve(), cloudViewer::SimpleMesh::resize(), and cloudViewer::SimpleMesh::vertices().
Referenced by define_cccorelib().
define_SimpleTriangle()
void define_SimpleTriangle (py::module & cccorelib)
Definition at line 17 of file SimpleTriangle.cpp.
References cloudViewer::SimpleRefTriangle::A, cloudViewer::SimpleTriangle::A, cloudViewer::SimpleRefTriangle::B, cloudViewer::SimpleTriangle::B, cloudViewer::SimpleRefTriangle::C, and cloudViewer::SimpleTriangle::C.
Referenced by define_cccorelib().
define_StatisticalTestingTools()
void define_StatisticalTestingTools (py::module & cccorelib)
Definition at line 21 of file StatisticalTestingTools.cpp.
References cloudViewer::StatisticalTestingTools::computeAdaptativeChi2Dist(), cloudViewer::StatisticalTestingTools::computeChi2Fractile(), cloudViewer::StatisticalTestingTools::computeChi2Probability(), and cloudViewer::StatisticalTestingTools::testCloudWithStatisticalModel().
Referenced by define_cccorelib().
define_TrueKdTree()
void define_TrueKdTree (py::module & cccorelib)
Definition at line 22 of file TrueKdTree.cpp.
References error(), points, and cloudViewer::DistanceComputationTools::RMS.
Referenced by define_cccorelib().
define_WeibullDistribution()
void define_WeibullDistribution (py::module & cccorelib)
Definition at line 15 of file WeibullDistribution.cpp.
References cloudViewer::WeibullDistribution::computeMode(), cloudViewer::WeibullDistribution::computeSkewness(), cloudViewer::WeibullDistribution::getOtherParameters(), cloudViewer::WeibullDistribution::getParameters(), cloudViewer::WeibullDistribution::getValueShift(), cloudViewer::WeibullDistribution::setParameters(), and cloudViewer::WeibullDistribution::setValueShift().
Referenced by define_cccorelib().
PYBIND11_MODULE()
PYBIND11_MODULE (cccorelib , m)
Definition at line 342 of file cccorelib.cpp.
References define_cccorelib().