ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccColorScalesManager.cpp File Reference
ccColorScalesManager.cpp File Reference
#include <pybind11/native_enum.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvColorScalesManager.h>
#include <QColor>
#include "../casters.h"
Functions
void define_ccColorScalesManager (py::module &m)
Function Documentation
define_ccColorScalesManager()
void define_ccColorScalesManager (py::module & m)
Definition at line 22 of file ccColorScalesManager.cpp.
References ccColorScalesManager::addScale(), ccColorScalesManager::fromPersistentSettings(), ccColorScalesManager::getDefaultScale(), ccColorScalesManager::GetDefaultScale(), ccColorScalesManager::GetDefaultScaleUUID(), ccColorScalesManager::getScale(), ccColorScalesManager::GetUniqueInstance(), ccColorScalesManager::ReleaseUniqueInstance(), ccColorScalesManager::removeScale(), and ccColorScalesManager::toPersistentSettings().
Referenced by define_qcc_db().