ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccCone.cpp File Reference
ccCone.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvCone.h>
#include "../casters.h"
Functions
void define_ccCone (py::module &m)
Function Documentation
define_ccCone()
void define_ccCone (py::module & m)
Definition at line 19 of file ccCone.cpp.
References ccCone::DEFAULT_DRAWING_PRECISION, ccCone::getBottomCenter(), ccCone::getBottomRadius(), ccCone::getHeight(), ccCone::getLargeCenter(), ccCone::getLargeRadius(), ccCone::getSmallCenter(), ccCone::getSmallRadius(), ccCone::getTopCenter(), ccCone::getTopRadius(), ccCone::isSnoutMode(), ccCone::setBottomRadius(), ccCone::setHeight(), and ccCone::setTopRadius().
Referenced by define_qcc_db().