ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccCylinder.cpp File Reference
ccCylinder.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvCone.h>
#include <ecvCylinder.h>
#include "../casters.h"
Functions
void define_ccCylinder (py::module &m)
Function Documentation
define_ccCylinder()
void define_ccCylinder (py::module & m)
Definition at line 20 of file ccCylinder.cpp.
References ccCylinder::DEFAULT_DRAWING_PRECISION, ccCone::getBottomRadius(), and ccCylinder::setBottomRadius().
Referenced by define_qcc_db().