ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccDisc.cpp File Reference
ccDisc.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvDisc.h>
#include <ecvGLMatrix.h>
#include <ecvGenericPrimitive.h>
#include "../casters.h"
Functions
void define_ccDisc (py::module &m)
Function Documentation
define_ccDisc()
void define_ccDisc (py::module & m)
Definition at line 21 of file ccDisc.cpp.
References ccDisc::clone(), ccDisc::DEFAULT_DRAWING_PRECISION, ccDisc::getRadius(), and ccDisc::setRadius().
Referenced by define_qcc_db().