ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccDrawableObject.cpp File Reference
ccDrawableObject.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvDrawableObject.h>
#include <ecvGenericDisplayTools.h>
Functions
void define_ccDrawableObject (py::module &m)
Function Documentation
define_ccDrawableObject()
void define_ccDrawableObject (py::module & m)
Definition at line 18 of file ccDrawableObject.cpp.
References ccDrawableObject::addClipPlanes(), ccDrawableObject::colorsShown(), ccDrawableObject::draw(), ccDrawableObject::enableGLTransformation(), ccDrawableObject::getGLTransformation(), ccDrawableObject::getTempColor(), ccDrawableObject::hasColors(), ccDrawableObject::hasDisplayedScalarField(), ccDrawableObject::hasNormals(), ccDrawableObject::hasScalarFields(), ccDrawableObject::isColorOverridden(), ccDrawableObject::isGLTransEnabled(), ccDrawableObject::isSelected(), ccDrawableObject::isVisibilityLocked(), ccDrawableObject::isVisible(), ccDrawableObject::lockVisibility(), ccDrawableObject::nameShownIn3D(), ccDrawableObject::normalsShown(), ccDrawableObject::removeAllClipPlanes(), ccDrawableObject::resetGLTransformation(), ccDrawableObject::rotateGL(), ccDrawableObject::setGLTransformation(), ccDrawableObject::setSelected(), ccDrawableObject::setTempColor(), ccDrawableObject::setVisible(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccDrawableObject::showNameIn3D(), ccDrawableObject::showNormals(), ccDrawableObject::showSF(), ccDrawableObject::toggleClipPlanes(), ccDrawableObject::toggleColors(), ccDrawableObject::toggleMaterials(), ccDrawableObject::toggleNormals(), ccDrawableObject::toggleSF(), ccDrawableObject::toggleShowName(), ccDrawableObject::toggleVisibility(), and ccDrawableObject::translateGL().
Referenced by define_qcc_db().