ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccGBLSensor.cpp File Reference
ccGBLSensor.cpp File Reference
#include <pybind11/native_enum.h>
#include <pybind11/pybind11.h>
#include <ecvGBLSensor.h>
#include "../casters.h"
Functions
void define_ccGBLSensor (py::module &m)
Function Documentation
define_ccGBLSensor()
void define_ccGBLSensor (py::module & m)
Definition at line 18 of file ccGBLSensor.cpp.
References ccGBLSensor::computeAutoParameters(), ccGBLSensor::GetErrorString(), ccGBLSensor::getMaxPitch(), ccGBLSensor::getMaxYaw(), ccGBLSensor::getMinPitch(), ccGBLSensor::getMinYaw(), ccGBLSensor::getPitchStep(), ccGBLSensor::getRotationOrder(), ccGBLSensor::getSensorRange(), ccGBLSensor::getUncertainty(), ccGBLSensor::getYawStep(), ccGBLSensor::pitchIsShifted(), ccGBLSensor::setPitchRange(), ccGBLSensor::setPitchStep(), ccGBLSensor::setRotationOrder(), ccGBLSensor::setSensorRange(), ccGBLSensor::setUncertainty(), ccGBLSensor::setYawRange(), ccGBLSensor::setYawStep(), and ccGBLSensor::yawIsShifted().
Referenced by define_qcc_db().