ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccGenericDisplayTools.cpp File Reference
ccGenericDisplayTools.cpp File Reference
#include "../casters.h"
#include <pybind11/native_enum.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <QPointF>
#include <QSize>
#include <ecvGenericDisplayTools.h>
Functions
void define_ccGenericDisplayTools (py::module &m)
Function Documentation
define_ccGenericDisplayTools()
void define_ccGenericDisplayTools (py::module & m)
Definition at line 22 of file ccGenericDisplayTools.cpp.
References ccGLCameraParameters::fov_deg, ccGLCameraParameters::modelViewMat, ccGLCameraParameters::perspective, ccGLCameraParameters::pixelSize, ccGLCameraParameters::project(), ccGLCameraParameters::projectionMat, and ccGLCameraParameters::unproject().
Referenced by define_qcc_db().