ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccGenericPrimitive.cpp File Reference
ccGenericPrimitive.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvGLMatrix.h>
#include <ecvGenericPrimitive.h>
#include <ecvMesh.h>
#include "../casters.h"
Functions
void define_ccGenericPrimitive (py::module &m)
Function Documentation
define_ccGenericPrimitive()
void define_ccGenericPrimitive (py::module & m)
Definition at line 21 of file ccGenericPrimitive.cpp.
References ccGenericPrimitive::getDrawingPrecision(), ccGenericPrimitive::getTransformation(), ccGenericPrimitive::getTypeName(), ccGenericPrimitive::hasDrawingPrecision(), ccGenericPrimitive::setColor(), and ccGenericPrimitive::setDrawingPrecision().
Referenced by define_qcc_db().