ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccGenericMesh.cpp File Reference
ccGenericMesh.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvGenericMesh.h>
#include <ecvMaterialSet.h>
#include <ecvPointCloud.h>
Functions
void define_ccGenericMesh (py::module &m)
Function Documentation
define_ccGenericMesh()
void define_ccGenericMesh (py::module & m)
Definition at line 19 of file ccGenericMesh.cpp.
References ccGenericMesh::capacity(), ccGenericMesh::getAssociatedCloud(), ccGenericMesh::getMaterialSet(), ccGenericMesh::getTexCoordinatesTable(), ccGenericMesh::getTriangleMtlIndex(), ccGenericMesh::hasMaterials(), ccGenericMesh::hasPerTriangleTexCoordIndexes(), ccGenericMesh::hasTextures(), ccGenericMesh::hasTriNormals(), and ccGenericMesh::refreshBB().
Referenced by define_qcc_db().