ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/ccgraph.c File Reference
ccgraph.c File Reference
#include "metis.h"
Functions
void CreateCoarseGraph (CtrlType *ctrl, GraphType *graph, int cnvtxs, idxtype *match, idxtype *perm)
void CreateCoarseGraphNoMask (CtrlType *ctrl, GraphType *graph, int cnvtxs, idxtype *match, idxtype *perm)
void CreateCoarseGraph_NVW (CtrlType *ctrl, GraphType *graph, int cnvtxs, idxtype *match, idxtype *perm)
GraphType * SetUpCoarseGraph (GraphType *graph, int cnvtxs, int dovsize)
void ReAdjustMemory (GraphType *graph, GraphType *cgraph, int dovsize)
Function Documentation
CreateCoarseGraph()
void CreateCoarseGraph (CtrlType * ctrl, GraphType * graph, int cnvtxs, idxtype * match, idxtype * perm)
Definition at line 22 of file ccgraph.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERTP, workspacedef::auxcore, graphdef::cmap, controldef::ContractTmr, CreateCoarseGraphNoMask(), DBG_TIME, controldef::dbglvl, HTLENGTH, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::nvwgt, OP_KVMETIS, controldef::optype, ReAdjustMemory(), saxpy, scopy, SetUpCoarseGraph(), starttimer, stoptimer, graphdef::vsize, graphdef::vwgt, controldef::wspace, and graphdef::xadj.
CreateCoarseGraph_NVW()
void CreateCoarseGraph_NVW (CtrlType * ctrl, GraphType * graph, int cnvtxs, idxtype * match, idxtype * perm)
Definition at line 330 of file ccgraph.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERTP, workspacedef::auxcore, graphdef::cmap, controldef::ContractTmr, DBG_TIME, controldef::dbglvl, HTLENGTH, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::nvwgt, ReAdjustMemory(), SetUpCoarseGraph(), starttimer, stoptimer, graphdef::vwgt, controldef::wspace, and graphdef::xadj.
CreateCoarseGraphNoMask()
void CreateCoarseGraphNoMask (CtrlType * ctrl, GraphType * graph, int cnvtxs, idxtype * match, idxtype * perm)
Definition at line 195 of file ccgraph.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, ASSERTP, workspacedef::auxcore, graphdef::cmap, controldef::ContractTmr, DBG_TIME, controldef::dbglvl, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::nvwgt, OP_KVMETIS, controldef::optype, ReAdjustMemory(), saxpy, scopy, SetUpCoarseGraph(), starttimer, stoptimer, graphdef::vsize, graphdef::vwgt, controldef::wspace, and graphdef::xadj.
Referenced by CreateCoarseGraph().
ReAdjustMemory()
void ReAdjustMemory (GraphType * graph, GraphType * cgraph, int dovsize)
Definition at line 543 of file ccgraph.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::cmap, graphdef::gdata, idxcopy, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::vsize, graphdef::vwgt, and graphdef::xadj.
Referenced by CreateCoarseGraph(), CreateCoarseGraph_NVW(), and CreateCoarseGraphNoMask().
SetUpCoarseGraph()
GraphType* SetUpCoarseGraph (GraphType * graph, int cnvtxs, int dovsize)
Definition at line 479 of file ccgraph.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::cmap, graphdef::coarser, CreateGraph, graphdef::finer, fmalloc, graphdef::gdata, idxmalloc, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::nvwgt, graphdef::vsize, graphdef::vwgt, and graphdef::xadj.
Referenced by CreateCoarseGraph(), CreateCoarseGraph_NVW(), and CreateCoarseGraphNoMask().