ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/Runtime/ccGuiPythonInstance.cpp File Reference
ccGuiPythonInstance.cpp File Reference
#include "ccGuiPythonInstance.h"
#include <ecvDisplayTools.h>
#include <ecvMainAppInterface.h>
#include <ecvPointCloud.h>
#include <QMainWindow>
#include <stdexcept>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include "../../wrapper/pycc/src/casters.h"
Macros
#define slots Q_SLOTS
#define signals Q_SIGNALS
Functions
static void ThrowForFileError (CC_FILE_ERROR error)
void define_ccGUIPythonInstance (py::module &m)
Macro Definition Documentation
signals
#define signals Q_SIGNALS
Definition at line 11 of file ccGuiPythonInstance.cpp.
slots
#define slots Q_SLOTS
Definition at line 10 of file ccGuiPythonInstance.cpp.
Function Documentation
define_ccGUIPythonInstance()
void define_ccGUIPythonInstance (py::module & m)
Definition at line 201 of file ccGuiPythonInstance.cpp.
References ccGuiPythonInstance::addToDB(), ccGuiPythonInstance::app(), ccGuiPythonInstance::dbRootObject(), ccGuiPythonInstance::disableAll(), ccGuiPythonInstance::enableAll(), ccGuiPythonInstance::freezeUI(), ccGuiPythonInstance::getMainWindow(), ccGuiPythonInstance::getSelectedEntities(), ccGuiPythonInstance::haveOneSelection(), ccGuiPythonInstance::haveSelection(), ccGuiPythonInstance::loadFile(), ccGuiPythonInstance::redrawAll(), ccGuiPythonInstance::refreshAll(), ccGuiPythonInstance::removeFromDB(), ccGuiPythonInstance::setSelectedInDB(), and ccGuiPythonInstance::updateUI().
Referenced by PYBIND11_EMBEDDED_MODULE().
ThrowForFileError()
static void ThrowForFileError (CC_FILE_ERROR error) static
Definition at line 31 of file ccGuiPythonInstance.cpp.
References CC_FERR_BAD_ARGUMENT, CC_FERR_BAD_ENTITY_TYPE, CC_FERR_BROKEN_DEPENDENCY_ERROR, CC_FERR_CANCELED_BY_USER, CC_FERR_CONSOLE_ERROR, CC_FERR_FILE_WAS_WRITTEN_BY_UNKNOWN_PLUGIN, CC_FERR_INTERNAL, CC_FERR_MALFORMED_FILE, CC_FERR_NO_ERROR, CC_FERR_NO_LOAD, CC_FERR_NO_SAVE, CC_FERR_NOT_ENOUGH_MEMORY, CC_FERR_NOT_IMPLEMENTED, CC_FERR_READING, CC_FERR_THIRD_PARTY_LIB_EXCEPTION, CC_FERR_THIRD_PARTY_LIB_FAILURE, CC_FERR_UNKNOWN_FILE, CC_FERR_WRITING, CC_FERR_WRONG_FILE_TYPE, and error().
Referenced by ccGuiPythonInstance::loadFile().