ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccIndexedTransformation.cpp File Reference
ccIndexedTransformation.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvIndexedTransformation.h>
#include "../casters.h"
Functions
void define_ccIndexedTransformation (py::module &m)
Function Documentation
define_ccIndexedTransformation()
void define_ccIndexedTransformation (py::module & m)
Definition at line 19 of file ccIndexedTransformation.cpp.
References ccIndexedTransformation::getIndex(), ccIndexedTransformation::Interpolate(), ccIndexedTransformation::inverse(), ccIndexedTransformation::setIndex(), and ccIndexedTransformation::transposed().
Referenced by define_qcc_db().