ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccInteractor.cpp File Reference
ccInteractor.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecv2DLabel.h>
Functions
void define_ccInteractor (py::module &m)
Function Documentation
define_ccInteractor()
void define_ccInteractor (py::module & m)
Definition at line 17 of file ccInteractor.cpp.
References ccInteractor::acceptClick(), ccInteractor::move2D(), and ccInteractor::move3D().
Referenced by define_qcc_db().