ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qMPlane/src/ccItemTree.cpp File Reference
ccItemTree.cpp File Reference
#include "ccItemTree.h"
#include "ccMPlaneErrors.h"
#include <ecvDisplayTools.h>
Functions
bool compareObjects (QString name, ccHObject *object, CC_ITEM_TREE::CC_TYPES_MAP type)
Function Documentation
compareObjects()
bool compareObjects (QString name, ccHObject * object, CC_ITEM_TREE::CC_TYPES_MAP type)
Definition at line 15 of file ccItemTree.cpp.
References ccObject::getName(), ccObject::isKindOf(), name, and type.
Referenced by CC_ITEM_TREE::findItemInHierarchy().