ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccLog.cpp File Reference
ccLog.cpp File Reference
#include <pybind11/native_enum.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include "../casters.h"
#include <CVLog.h>
Functions
void define_ccLog (py::module &m)
Function Documentation
define_ccLog()
void define_ccLog (py::module & m)
Definition at line 20 of file ccLog.cpp.
References CVLog::Error(), CVLog::LogMessage(), CVLog::Print(), CVLog::TheInstance(), and CVLog::Warning().
Referenced by define_qcc_db().