ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccMaterial.cpp File Reference
ccMaterial.cpp File Reference
#include "../casters.h"
#include "ecvMaterial.h"
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <QImage>
Functions
void define_ccMaterial (py::module &m)
Function Documentation
define_ccMaterial()
void define_ccMaterial (py::module & m)
Definition at line 19 of file ccMaterial.cpp.
References ccMaterial::AddTexture(), ccMaterial::compare(), ccMaterial::fromFile(), ccMaterial::getAmbient(), ccMaterial::getDiffuseBack(), ccMaterial::getDiffuseFront(), ccMaterial::getEmission(), ccMaterial::getIllum(), ccMaterial::getName(), ccMaterial::getShininessBack(), ccMaterial::getShininessFront(), ccMaterial::getSpecular(), ccMaterial::getTexture(), ccMaterial::GetTexture(), ccMaterial::getTextureFilename(), ccMaterial::getTextureID(), ccMaterial::getUniqueIdentifier(), ccMaterial::hasTexture(), ccMaterial::isSerializable(), ccMaterial::loadAndSetTexture(), ccMaterial::minimumFileVersion(), ccMaterial::releaseTexture(), ccMaterial::ReleaseTextures(), ccMaterial::setAmbient(), ccMaterial::setDiffuse(), ccMaterial::setDiffuseBack(), ccMaterial::setDiffuseFront(), ccMaterial::setEmission(), ccMaterial::setIllum(), ccMaterial::setName(), ccMaterial::setShininess(), ccMaterial::setShininessBack(), ccMaterial::setShininessFront(), ccMaterial::setSpecular(), ccMaterial::setTexture(), ccMaterial::setTransparency(), and ccMaterial::toFile().