ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccMaterialSet.cpp File Reference
ccMaterialSet.cpp File Reference
#include "../casters.h"
#include "ecvMaterialSet.h"
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
Functions
void define_ccMaterialSet (py::module &m)
Function Documentation
define_ccMaterialSet()
void define_ccMaterialSet (py::module & m)
Definition at line 17 of file ccMaterialSet.cpp.
References ccMaterialSet::addMaterial(), ccMaterialSet::append(), ccMaterialSet::clone(), ccMaterialSet::findMaterialByName(), ccMaterialSet::findMaterialByUniqueID(), ccMaterialSet::getClassID(), ccMaterialSet::isSerializable(), ccMaterialSet::isShareable(), ccMaterialSet::ParseMTL(), and ccMaterialSet::saveAsMTL().