ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccMesh.cpp File Reference
ccMesh.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvGenericMesh.h>
#include <ecvGenericPointCloud.h>
#include <ecvMesh.h>
#include <ecvPointCloud.h>
Functions
void define_ccMesh (py::module &m)
Function Documentation
define_ccMesh()
void define_ccMesh (py::module & m)
Definition at line 20 of file ccMesh.cpp.
References ccMesh::addTriangle(), ccMesh::addTriangles(), and ccMesh::setAssociatedCloud().
Referenced by define_qcc_db().