ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccNormalVectors.cpp File Reference
ccNormalVectors.cpp File Reference
#include <pybind11/native_enum.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvNormalVectors.h>
#include <ecvProgressDialog.h>
Functions
void define_ccNormalVectors (py::module &m)
Function Documentation
define_ccNormalVectors()
void define_ccNormalVectors (py::module & m)
Definition at line 19 of file ccNormalVectors.cpp.
References ccNormalVectors::GetNormal(), ccNormalVectors::GetNormIndex(), ccNormalVectors::GetNumberOfVectors(), ccNormalVectors::GetUniqueInstance(), and ccNormalVectors::ReleaseUniqueInstance().
Referenced by define_qcc_db().