ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccObject.cpp File Reference
ccObject.cpp File Reference
#include <pybind11/native_enum.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvBBox.h>
#include <ecvGenericDisplayTools.h>
#include <ecvHObject.h>
#include <ecvObject.h>
#include <ecvShiftedObject.h>
#include "../casters.h"
Functions
void removePatient (py::object &nurse, py::object &patient)
void setDeletable (py::object &object, bool state)
template<typename T >
py::object castToFakeOwnedObject (T &&obj)
void define_ccObject (py::module &m)
Function Documentation
castToFakeOwnedObject()
template<typename T > py::object castToFakeOwnedObject (T && obj)
This is a hack.
This function creates a py::object from a value but it makes the object think it does not own the data so when the ref count reaches 0 it does no call the destructor unless setDeletable(obj, true) was called in between
Definition at line 70 of file ccObject.cpp.
References setDeletable().
Referenced by define_ccObject().
define_ccObject()
void define_ccObject (py::module & m)
Definition at line 77 of file ccObject.cpp.
References ccHObject::applyGLTransformation_recursive(), castToFakeOwnedObject(), ccShiftedObject::copyGlobalShiftAndScale(), data, ccHObject::detachAllChildren(), ccHObject::detachChild(), ccHObject::find(), ccHObject::getChildCountRecursive(), ccHObject::getChildIndex(), ccHObject::getChildrenNumber(), ccHObject::getDisplayBB_recursive(), ccHObject::getFirstChild(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccHObject::getGLTransformationHistory(), ccHObject::getIndex(), ccHObject::getLastChild(), ccObject::getMetaData(), ccObject::getName(), ccHObject::getParent(), ccObject::getUniqueID(), ccObject::hasMetaData(), ccHObject::isAncestorOf(), ccObject::isCustom(), ccObject::isEnabled(), ccHObject::isGroup(), ccObject::isHierarchy(), ccObject::isLeaf(), ccObject::isLocked(), ccShiftedObject::isShifted(), ccHObject::notifyGeometryUpdate(), ccObject::removeMetaData(), removePatient(), ccHObject::resetGLTransformationHistory(), setDeletable(), ccObject::setEnabled(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccHObject::setGLTransformationHistory(), ccObject::setLocked(), ccObject::setMetaData(), ccObject::setName(), ccHObject::swapChildren(), and ccObject::toggleActivation().
Referenced by define_qcc_db().
removePatient()
void removePatient (py::object & nurse, py::object & patient)
Definition at line 26 of file ccObject.cpp.
Referenced by define_ccObject().
setDeletable()
void setDeletable (py::object & object, bool state)
Definition at line 51 of file ccObject.cpp.
Referenced by castToFakeOwnedObject(), and define_ccObject().