ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccPlane.cpp File Reference
ccPlane.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include "../casters.h"
#include <GenericIndexedCloudPersist.h>
#include <ecvPlane.h>
Functions
void define_ccPlane (py::module &m)
Function Documentation
define_ccPlane()
void define_ccPlane (py::module & m)
Definition at line 20 of file ccPlane.cpp.
References ccPlane::Fit(), ccPlane::flip(), ccPlane::getCenter(), ccPlanarEntityInterface::getNormal(), ccPlane::getXWidth(), ccPlane::getYWidth(), ccPlanarEntityInterface::normalVectorIsShown(), ccPlane::setXWidth(), ccPlane::setYWidth(), and ccPlanarEntityInterface::showNormalVector().
Referenced by define_qcc_db().