ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccPolyline.cpp File Reference
ccPolyline.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <GenericIndexedCloudPersist.h>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include "../casters.h"
Functions
void define_ccPolyline (py::module &m)
Function Documentation
define_ccPolyline()
void define_ccPolyline (py::module & m)
Definition at line 21 of file ccPolyline.cpp.
References ccPolyline::computeLength(), ccPolyline::getColor(), ccPolyline::getVertexMarkerWidth(), ccPolyline::getWidth(), ccPolyline::importParametersFrom(), ccPolyline::is2DMode(), ccPolyline::samplePoints(), ccPolyline::segmentCount(), ccPolyline::set2DMode(), ccPolyline::setColor(), ccPolyline::setForeground(), ccPolyline::setVertexMarkerWidth(), ccPolyline::setWidth(), ccPolyline::showArrow(), ccPolyline::showVertices(), ccPolyline::smoothChaikin(), and ccPolyline::verticesShown().
Referenced by define_qcc_db().