ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccPointCloud.cpp File Reference
ccPointCloud.cpp File Reference
#include "../casters.h"
#include <ecvAdvancedTypes.h>
#include <ecvColorTypes.h>
#include <climits>
#include <cstdint>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <pybind11/pytypes.h>
#include <type_traits>
#include <vector>
#include <pybind11/functional.h>
#include <pybind11/numpy.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include "wrappers.h"
Functions
void define_ccPointCloud (py::module &m)
Function Documentation
define_ccPointCloud()
void define_ccPointCloud (py::module & m)
Definition at line 36 of file ccPointCloud.cpp.
References ccPointCloud::addNorm(), PyCC::addPointsFromArrays(), ccPointCloud::colorize(), colors, ccPointCloud::computeNormalsWithGrids(), ccPointCloud::computeNormalsWithOctree(), ccPointCloud::crop2D(), DEFINE_POINTCLOUDTPL, ccPointCloud::getCurrentDisplayedScalarField(), ccPointCloud::getCurrentDisplayedScalarFieldIndex(), max(), ccPointCloud::orientNormalsTowardViewPoint(), ccPointCloud::orientNormalsWithFM(), ccPointCloud::orientNormalsWithMST(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveThePointsTable(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::setCurrentDisplayedScalarField(), ccPointCloud::setPointNormal(), ccGenericPointCloud::setPointSize(), ccPointCloud::sfColorScaleShown(), ccPointCloud::showSFColorsScale(), ccPointCloud::shrinkToFit(), size, and patch::to_string().
Referenced by define_qcc_db().