ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qCompass/src/ccPointPair.cpp File Reference
ccPointPair.cpp File Reference
#include "ccPointPair.h"
#include <ecvDisplayTools.h>
Functions
static QSharedPointer< ccSphere > c_unitPointMarker (nullptr)
static QSharedPointer< ccCylinder > c_bodyMarker (nullptr)
static QSharedPointer< ccCone > c_headMarker (nullptr)
Function Documentation
c_bodyMarker()
static QSharedPointer<ccCylinder> c_bodyMarker (nullptr) static
Referenced by ccPointPair::drawMeOnly().
c_headMarker()
static QSharedPointer<ccCone> c_headMarker (nullptr) static
Referenced by ccPointPair::drawMeOnly().
c_unitPointMarker()
static QSharedPointer<ccSphere> c_unitPointMarker (nullptr) static
Referenced by ccPointPair::drawMeOnly().