ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccQuadric.cpp File Reference
ccQuadric.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvQuadric.h>
#include <utility>
#include "../casters.h"
Functions
void define_ccQuadric (py::module &m)
Function Documentation
define_ccQuadric()
void define_ccQuadric (py::module & m)
Definition at line 21 of file ccQuadric.cpp.
References ccQuadric::DEFAULT_DRAWING_PRECISION, ccQuadric::Fit(), for(), ccQuadric::getEquationCoefs(), ccQuadric::getEquationDims(), ccQuadric::getEquationString(), ccQuadric::getMaxCorner(), ccQuadric::getMinCorner(), name, and ccQuadric::projectOnQuadric().
Referenced by define_qcc_db().