ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccRasterGrid.cpp File Reference
ccRasterGrid.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvPointCloud.h>
#include <ecvProgressDialog.h>
#include <ecvRasterGrid.h>
#include "../casters.h"
Functions
void define_ccRasterGrid (py::module &m)
Function Documentation
define_ccRasterGrid()
void define_ccRasterGrid (py::module & m)
Definition at line 21 of file ccRasterGrid.cpp.
References ccRasterCell::color, ccRasterGrid::computeCellCenter(), ccRasterGrid::computeCellPos(), ccRasterGrid::ComputeGridSize(), ccRasterGrid::convertToCloud(), ccRasterGrid::fillEmptyCells(), ccRasterGrid::fillWith(), ccRasterGrid::GetDefaultFieldName(), ccRasterGrid::gridStep, ccRasterCell::h, ccRasterGrid::hasColors, ccRasterGrid::height, ccRasterGrid::isValid(), ccRasterCell::maxHeight, ccRasterGrid::maxHeight, ccRasterGrid::meanHeight, ccRasterGrid::minCorner, ccRasterCell::minHeight, ccRasterGrid::minHeight, ccRasterCell::nbPoints, ccRasterGrid::nonEmptyCellCount, ccRasterCell::pointIndex, ccRasterGrid::reset(), ccRasterGrid::setValid(), ccRasterGrid::updateCellStats(), ccRasterGrid::updateNonEmptyCellCount(), ccRasterGrid::valid, ccRasterGrid::validCellCount, and ccRasterGrid::width.
Referenced by define_qcc_db().