ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccScalarField.cpp File Reference
ccScalarField.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvScalarField.h>
#include "../../cccorelib/src/wrappers.h"
Functions
void define_ccScalarField (py::module &m)
Function Documentation
define_ccScalarField()
void define_ccScalarField (py::module & m)
Definition at line 19 of file ccScalarField.cpp.
References ccScalarField::alwaysShowZero(), ccScalarField::areNaNValuesShownInGrey(), ccScalarField::displayRange(), ccScalarField::getColor(), ccScalarField::getColorRampSteps(), ccScalarField::getColorScale(), ccScalarField::getGlobalShift(), ccScalarField::getHistogram(), ccScalarField::getModificationFlag(), ccScalarField::getValueColor(), ccScalarField::importParametersFrom(), ccScalarField::Range::inbound(), ccScalarField::Range::isInbound(), ccScalarField::Range::isInRange(), ccScalarField::isZeroAlwaysShown(), ccScalarField::logSaturationRange(), ccScalarField::logScale(), ccScalarField::Range::max(), ccScalarField::Range::maxRange(), ccScalarField::mayHaveHiddenValues(), ccScalarField::Range::min(), ccScalarField::Range::range(), ccScalarField::saturationRange(), ccScalarField::Range::setBounds(), ccScalarField::setColorRampSteps(), ccScalarField::setColorScale(), ccScalarField::setGlobalShift(), ccScalarField::setLogScale(), ccScalarField::setMaxDisplayed(), ccScalarField::setMinDisplayed(), ccScalarField::setModificationFlag(), ccScalarField::setSaturationStart(), ccScalarField::setSaturationStop(), ccScalarField::Range::setStart(), ccScalarField::Range::setStop(), ccScalarField::setSymmetricalScale(), ccScalarField::showNaNValuesInGrey(), ccScalarField::Range::start(), ccScalarField::Range::stop(), and ccScalarField::symmetricalScale().
Referenced by define_qcc_db().