ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccSensor.cpp File Reference
ccSensor.cpp File Reference
#include <pybind11/native_enum.h>
#include <pybind11/pybind11.h>
#include <ecvGenericDisplayTools.h>
#include <ecvSensor.h>
#include "../casters.h"
Functions
void define_ccSensor (py::module &m)
Function Documentation
define_ccSensor()
void define_ccSensor (py::module & m)
Definition at line 19 of file ccSensor.cpp.
References ccSensor::addPosition(), ccSensor::applyViewport(), ccSensor::checkVisibility(), ccSensor::getAbsoluteTransformation(), ccSensor::getActiveAbsoluteCenter(), ccSensor::getActiveAbsoluteRotation(), ccSensor::getActiveAbsoluteTransformation(), ccSensor::getActiveIndex(), ccSensor::getGraphicScale(), ccSensor::getRigidTransformation(), GROUND_BASED_LIDAR, max(), min(), ccSensor::setActiveIndex(), ccSensor::setGraphicScale(), ccSensor::setRigidTransformation(), and UNKNOWN_SENSOR.
Referenced by define_qcc_db().