ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccSerializableObject.cpp File Reference
ccSerializableObject.cpp File Reference
#include "../casters.h"
#include "ecvSerializableObject.h"
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
Functions
void define_ccSerializableObject (py::module &m)
void define_ccSerializationHelper (py::module &m)
Function Documentation
define_ccSerializableObject()
void define_ccSerializableObject (py::module & m)
Definition at line 17 of file ccSerializableObject.cpp.
References ccSerializableObject::CorruptError(), ccSerializableObject::fromFile(), ccSerializableObject::isSerializable(), ccSerializableObject::MemoryError(), ccSerializableObject::minimumFileVersion(), ccSerializableObject::ReadError(), ccSerializableObject::toFile(), and ccSerializableObject::WriteError().
define_ccSerializationHelper()
void define_ccSerializationHelper (py::module & m)
Definition at line 31 of file ccSerializableObject.cpp.
References ccSerializationHelper::CoordsFromDataStream(), and ccSerializationHelper::ScalarsFromDataStream().