ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/CCShareable.cpp File Reference
CCShareable.cpp File Reference
#include <pybind11/pybind11.h>
#include <CVShareable.h>
#include "wrappers.h"
Functions
void define_CCShareable (py::module &cccorelib)
Function Documentation
define_CCShareable()
void define_CCShareable (py::module & cccorelib)
Definition at line 17 of file CCShareable.cpp.
References CCShareable::getLinkCount(), CCShareable::link(), and CCShareable::release().
Referenced by define_cccorelib().