ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccSubMesh.cpp File Reference
ccSubMesh.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvMesh.h>
#include <ecvSubMesh.h>
#include "../casters.h"
Functions
void define_ccSubMesh (py::module &m)
Function Documentation
define_ccSubMesh()
void define_ccSubMesh (py::module & m)
Definition at line 20 of file ccSubMesh.cpp.
References ccSubMesh::addTriangleIndex(), ccSubMesh::clear(), ccSubMesh::forwardIterator(), ccSubMesh::getAssociatedMesh(), ccSubMesh::getCurrentTriGlobalIndex(), ccSubMesh::getTriGlobalIndex(), ccSubMesh::reserve(), ccSubMesh::resize(), ccSubMesh::setAssociatedMesh(), and ccSubMesh::setTriangleIndex().
Referenced by define_qcc_db().