ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccViewPortParameters.cpp File Reference
ccViewPortParameters.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvViewportParameters.h>
#include <QRect>
#include "../casters.h"
Functions
void define_ccViewPortParameters (py::module &m)
Function Documentation
define_ccViewPortParameters()
void define_ccViewPortParameters (py::module & m)
Definition at line 21 of file ccViewPortParameters.cpp.
References ecvViewportParameters::cameraAspectRatio, ecvViewportParameters::computeDistanceToHalfWidthRatio(), ecvViewportParameters::computeDistanceToWidthRatio(), ecvViewportParameters::computePixelSize(), ecvViewportParameters::computeViewMatrix(), ecvViewportParameters::computeWidthAtFocalDist(), ecvViewportParameters::defaultLineWidth, ecvViewportParameters::defaultPointSize, ecvViewportParameters::fov_deg, ecvViewportParameters::getCameraCenter(), ecvViewportParameters::getFocalDistance(), ecvViewportParameters::getPivotPoint(), ecvViewportParameters::getRotationCenter(), ecvViewportParameters::getUpDir(), ecvViewportParameters::getViewDir(), ecvViewportParameters::objectCenteredView, ecvViewportParameters::perspectiveView, ecvViewportParameters::setCameraCenter(), ecvViewportParameters::setFocalDistance(), ecvViewportParameters::setPivotPoint(), ecvViewportParameters::viewMat, ecvViewportParameters::zFar, ecvViewportParameters::zNear, and ecvViewportParameters::zNearCoef.
Referenced by define_qcc_db().