ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccViewportObject.cpp File Reference
ccViewportObject.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecv2DViewportLabel.h>
#include <ecv2DViewportObject.h>
#include "../casters.h"
Functions
void define_ccViewportObject (py::module &m)
Function Documentation
define_ccViewportObject()
void define_ccViewportObject (py::module & m)
Definition at line 20 of file ccViewportObject.cpp.
References cc2DViewportObject::getParameters(), and cc2DViewportObject::setParameters().
Referenced by define_qcc_db().