ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/ccWaveform.cpp File Reference
ccWaveform.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <ecvWaveform.h>
#include "../casters.h"
Functions
void define_ccWaveform (py::module &m)
Function Documentation
define_ccWaveform()
void define_ccWaveform (py::module & m)
Definition at line 19 of file ccWaveform.cpp.
References ccWaveform::applyRigidTransformation(), ccWaveform::beamDir(), ccWaveformProxy::beamDir(), WaveformDescriptor::bitsPerSample, ccWaveform::byteCount(), ccWaveformProxy::byteCount(), ccWaveformProxy::data(), ccWaveform::dataOffset(), ccWaveformProxy::descriptor(), ccWaveform::descriptorID(), ccWaveformProxy::descriptorID(), WaveformDescriptor::digitizerGain, WaveformDescriptor::digitizerOffset, ccWaveform::echoTime_ps(), ccWaveformProxy::echoTime_ps(), ccWaveformProxy::getRawSample(), ccWaveform::getRawSample(), ccWaveformProxy::getSamplePos(), ccWaveform::getSamplePos(), ccWaveformProxy::isValid(), max(), min(), WaveformDescriptor::numberOfSamples, ccWaveform::returnIndex(), WaveformDescriptor::samplingRate_ps, ccWaveform::setBeamDir(), ccWaveform::setDataDescription(), ccWaveform::setDataOffset(), ccWaveform::setDescriptorID(), ccWaveform::setEchoTime_ps(), ccWaveform::setReturnIndex(), ccWaveformProxy::toASCII(), ccWaveform::toASCII(), ccWaveform::ToASCII(), and ccWaveformProxy::waveform().
Referenced by define_qcc_db().