ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/ChamferDistanceTransform.cpp File Reference
ChamferDistanceTransform.cpp File Reference
#include <pybind11/pybind11.h>
#include <ChamferDistanceTransform.h>
Functions
void define_ChamferDistanceTransform (py::module &cccorelib)
Function Documentation
define_ChamferDistanceTransform()
void define_ChamferDistanceTransform (py::module & cccorelib)
Definition at line 15 of file ChamferDistanceTransform.cpp.
References cloudViewer::ChamferDistanceTransform::init(), cloudViewer::ChamferDistanceTransform::MAX_DIST, cloudViewer::ChamferDistanceTransform::propagateDistance(), and size.
Referenced by define_cccorelib().