ACloudViewer: ecvApplication Class Reference
ecvApplication Class Reference
#include <ecvApplication.h>
Public Member Functions
ecvApplication (int &argc, char **argv, bool isCommandLine)
Public Member Functions inherited from ecvApplicationBase
ecvApplicationBase (int &argc, char **argv, bool isCommandLine, const QString &version)
bool isCommandLine () const
QString versionStr () const
QString versionLongStr (bool includeOS) const
const QString & translationPath () const
bool setAppStyle (const QString &styleKey)
Set the application style.
Static Public Member Functions
static QString GetMinVersionForFileVersion (short fileVersion)
Static Public Member Functions inherited from ecvApplicationBase
static void InitOpenGL ()
Protected Member Functions
bool event (QEvent *inEvent) override
Detailed Description
Definition at line 30 of file ecvApplication.h.
Constructor & Destructor Documentation
ecvApplication()
ecvApplication::ecvApplication (int & argc, char ** argv, bool isCommandLine)
Definition at line 81 of file ecvApplication.cpp.
References FileIO::setWriterInfo(), and ecvApplicationBase::versionStr().
Member Function Documentation
event()
bool ecvApplication::event (QEvent * inEvent) override protected
Definition at line 89 of file ecvApplication.cpp.
References MainWindow::addToDB(), event, and MainWindow::TheInstance().
GetMinVersionForFileVersion()
QString ecvApplication::GetMinVersionForFileVersion (short fileVersion) static
Returns the minimum version of CloudViewer required to load a given file version
Definition at line 77 of file ecvApplication.cpp.
References FileVersionToVersion::getMinVersion(), and s_fileVersionToVersion.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvApplication.h
/root/ACloudViewer/app/ecvApplication.cpp