ACloudViewer: ccQtHelpers Class Reference
ccQtHelpers Class Reference
#include <ecvQtHelpers.h>
Static Public Member Functions
static void SetButtonColor (QAbstractButton *button, const QColor &col)
Sets a button background color.
static int GetMaxThreadCount (int idealThreadCount)
Returns the ideal number of threads/cores.
static int GetMaxThreadCount ()
Returns the ideal number of threads/cores with Qt Concurrent.
Detailed Description
Definition at line 14 of file ecvQtHelpers.h.
Member Function Documentation
GetMaxThreadCount() [1/2]
static int ccQtHelpers::GetMaxThreadCount () inline static
Returns the ideal number of threads/cores with Qt Concurrent.
Definition at line 39 of file ecvQtHelpers.h.
GetMaxThreadCount() [2/2]
static int ccQtHelpers::GetMaxThreadCount (int idealThreadCount) inline static
Returns the ideal number of threads/cores.
Definition at line 28 of file ecvQtHelpers.h.
SetButtonColor()
static void ccQtHelpers::SetButtonColor (QAbstractButton * button, const QColor & col) inline static
Sets a button background color.
Definition at line 17 of file ecvQtHelpers.h.
Referenced by ccAlignDlg::ccAlignDlg(), ccColorGradientDlg::ccColorGradientDlg(), ccOrderChoiceDlg::ccOrderChoiceDlg(), ccRegistrationDlg::ccRegistrationDlg(), ccColorGradientDlg::changeFirstColor(), ccColorGradientDlg::changeSecondColor(), FastGlobalRegistrationDialog::FastGlobalRegistrationDialog(), ccColorScaleEditorDialog::onStepModified(), ccColorScaleEditorDialog::onStepSelected(), DistanceMapGenerationDlg::overlayGridColorChanged(), and DistanceMapGenerationDlg::overlaySymbolsColorChanged().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CVPluginAPI/include/ecvQtHelpers.h