ACloudViewer: colmap::BundleAdjustmentCostFunction< CameraModel > Class Template Reference
colmap::BundleAdjustmentCostFunction< CameraModel > Class Template Reference
#include <cost_functions.h>
Public Member Functions
BundleAdjustmentCostFunction (const Eigen::Vector2d &point2D)
template<typename T >
bool operator() (const T *const qvec, const T *const tvec, const T *const point3D, const T *const camera_params, T *residuals) const
Static Public Member Functions
static ceres::CostFunction * Create (const Eigen::Vector2d &point2D)
Detailed Description
template<typename CameraModel>
class colmap::BundleAdjustmentCostFunction< CameraModel >
Definition at line 20 of file cost_functions.h.
Constructor & Destructor Documentation
BundleAdjustmentCostFunction()
template<typename CameraModel > colmap::BundleAdjustmentCostFunction< CameraModel >::BundleAdjustmentCostFunction (const Eigen::Vector2d & point2D) inline explicit
Definition at line 22 of file cost_functions.h.
Referenced by colmap::BundleAdjustmentCostFunction< CameraModel >::Create().
Member Function Documentation
Create()
template<typename CameraModel > static ceres::CostFunction* colmap::BundleAdjustmentCostFunction< CameraModel >::Create (const Eigen::Vector2d & point2D) inline static
Definition at line 25 of file cost_functions.h.
References colmap::BundleAdjustmentCostFunction< CameraModel >::BundleAdjustmentCostFunction().
Referenced by BOOST_AUTO_TEST_CASE().
operator()()
template<typename CameraModel > template<typename T > bool colmap::BundleAdjustmentCostFunction< CameraModel >::operator() (const T *const qvec, const T *const tvec, const T *const point3D, const T *const camera_params, T * residuals) const inline
Definition at line 33 of file cost_functions.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/base/cost_functions.h