ACloudViewer: cvGenericFilter Class Reference
cvGenericFilter Class Reference abstract
#include <cvGenericFilter.h>
Public Member Functions
cvGenericFilter (QWidget *parent=nullptr)
virtual ~cvGenericFilter ()
virtual void apply ()=0
virtual void start ()
virtual void update ()
virtual void reset ()
virtual void restoreOrigin ()
virtual ccHObject * getOutput ()
virtual void getOutput (std::vector< ccHObject * > &outputSlices, std::vector< ccPolyline * > &outputContours)
virtual bool initModel ()
virtual bool setInput (ccHObject *obj)
virtual void shift (const CCVector3d &v)
Shifts the current interactor.
virtual void updateUi ()
virtual void showInteractor (bool state)
virtual void getInteractorInfos (ccBBox &bbox, ccGLMatrixd &trans)
virtual void getInteractorTransformation (ccGLMatrixd &trans)
virtual void getInteractorBounds (ccBBox &bbox)
virtual void clearAllActor ()
void setUpViewer (PclUtils::PCLVis *viewer)
void showOutline (bool show=true)
void setNegative (bool state)
void setInteractor (vtkRenderWindowInteractor *interactor)
vtkRenderWindowInteractor * getInteractor ()
Protected Types
enum DisplayEffect { Opaque , Transparent , Points , Wireframe }
Protected Slots
void onDoubleClick (int x, int y)
Protected Member Functions
virtual void modelReady ()
virtual void dataChanged ()
virtual void colorsChanged ()
void setDisplayEffect (DisplayEffect effect)
DisplayEffect displayEffect () const
void safeOff (vtk3DWidget *widget)
virtual void initFilter ()
virtual void createUi ()
void updateSize ()
void UpdateScalarRange ()
void applyDisplayEffect ()
void setScalarBarColors (const QColor &clr1, const QColor &clr2)
QColor color1 () const
QColor color2 () const
void setScalarRange (double min, double max)
double scalarMin () const
double scalarMax () const
vtkSmartPointer< vtkDataArray > getActorScalars (vtkSmartPointer< vtkActor > actor)
int getDefaultScalarInterpolationForDataSet (vtkDataSet *data)
vtkSmartPointer< vtkLookupTable > createLookupTable (double min, double max)
template<class ConfigClass >
void setupConfigWidget (ConfigClass *cc)
template<class DataObject , class Mapper >
void createActorFromData (vtkDataObject *dataObj)
void showScalarBar (bool show=true)
void setOutlineColor (const QColor &clr)
bool isValidPolyData () const
bool isValidDataSet () const
void addActor (const vtkSmartPointer< vtkProp > actor)
void removeActor (const vtkSmartPointer< vtkProp > actor)
void setResultData (vtkSmartPointer< vtkDataObject > data)
vtkSmartPointer< vtkDataObject > resultData () const
Protected Attributes
Ui::GenericFilterDlg * m_ui = nullptr
DisplayEffect m_displayEffect = Opaque
vtkDataObject * m_dataObject = nullptr
vtkSmartPointer< vtkDataObject > m_resultData
bool m_keepMode
bool m_negative
bool m_meshMode
bool m_preview
std::string m_id
ccHObject * m_entity = nullptr
PclUtils::PCLVis * m_viewer = nullptr
vtkRenderWindowInteractor * m_interactor = nullptr
vtkSmartPointer< vtkActor > m_modelActor
vtkSmartPointer< vtkLODActor > m_filterActor
vtkSmartPointer< vtkScalarBarActor > m_scalarBar
vtkSmartPointer< vtkActor > m_outlineActor
QColor m_color1 = Qt::blue
QColor m_color2 = Qt::red
double m_scalarMin = 0.0
double m_scalarMax = 1.0
Static Protected Attributes
static const int MAX_PREVIEW_NUMBER = 20e4
Detailed Description
Definition at line 46 of file cvGenericFilter.h.
Member Enumeration Documentation
DisplayEffect
enum cvGenericFilter::DisplayEffect protected
Enumerator
Opaque
Transparent
Points
Wireframe
Definition at line 88 of file cvGenericFilter.h.
Constructor & Destructor Documentation
cvGenericFilter()
cvGenericFilter::cvGenericFilter (QWidget * parent = nullptr) explicit
Definition at line 50 of file cvGenericFilter.cpp.
References ecvDisplayTools::doubleButtonClicked(), onDoubleClick(), and ecvDisplayTools::TheInstance().
~cvGenericFilter()
cvGenericFilter::~cvGenericFilter () virtual
Definition at line 63 of file cvGenericFilter.cpp.
References m_dataObject, m_ui, and VtkUtils::vtkSafeDelete().
Member Function Documentation
addActor()
void cvGenericFilter::addActor (const vtkSmartPointer< vtkProp > actor) protected
Definition at line 393 of file cvGenericFilter.cpp.
References PclUtils::PCLVis::addActorToRenderer(), and m_viewer.
Referenced by cvSliceFilter::apply(), cvClipFilter::apply(), cvDecimateFilter::apply(), cvGlyphFilter::apply(), cvIsoSurfaceFilter::apply(), cvSmoothFilter::apply(), cvStreamlineFilter::apply(), cvThresholdFilter::apply(), createActorFromData(), cvCutFilter::showContourLines(), showOutline(), and showScalarBar().
apply()
virtual void cvGenericFilter::apply () pure virtual
Implemented in cvThresholdFilter, cvStreamlineFilter, cvSmoothFilter, cvProbeFilter, cvIsoSurfaceFilter, cvGlyphFilter, cvDecimateFilter, cvClipFilter, and cvSliceFilter.
Referenced by cvCutFilter::dataChanged(), cvCutFilter::onCenterChanged(), cvCutFilter::onNormalChanged(), cvCutFilter::onOriginChanged(), cvCutFilter::onPlanesChanged(), cvCutFilter::onPreview(), cvCutFilter::onRadiusChanged(), cvCutFilter::setNormal(), cvCutFilter::setOrigin(), cvCutFilter::shift(), and PclFiltersTool::start().
applyDisplayEffect()
void cvGenericFilter::applyDisplayEffect () protected
Definition at line 254 of file cvGenericFilter.cpp.
References createLookupTable(), m_displayEffect, m_modelActor, m_scalarMax, m_scalarMin, Opaque, Points, Transparent, update(), and Wireframe.
Referenced by cvSliceFilter::apply(), cvClipFilter::apply(), cvDecimateFilter::apply(), cvGlyphFilter::apply(), cvIsoSurfaceFilter::apply(), cvStreamlineFilter::apply(), cvThresholdFilter::apply(), onDoubleClick(), and setDisplayEffect().
clearAllActor()
void cvGenericFilter::clearAllActor () virtual
Reimplemented in cvThresholdFilter, cvStreamlineFilter, cvSmoothFilter, cvSliceFilter, cvProbeFilter, cvIsoSurfaceFilter, cvGlyphFilter, cvDecimateFilter, cvCutFilter, and cvClipFilter.
Definition at line 403 of file cvGenericFilter.cpp.
References m_filterActor, m_meshMode, m_modelActor, m_outlineActor, m_scalarBar, m_viewer, and removeActor().
Referenced by PclFiltersTool::clear(), cvCutFilter::clearAllActor(), cvDecimateFilter::clearAllActor(), cvGlyphFilter::clearAllActor(), cvIsoSurfaceFilter::clearAllActor(), cvProbeFilter::clearAllActor(), cvSmoothFilter::clearAllActor(), and cvStreamlineFilter::clearAllActor().
color1()
QColor cvGenericFilter::color1 () const protected
Definition at line 349 of file cvGenericFilter.cpp.
References m_color1.
color2()
QColor cvGenericFilter::color2 () const protected
Definition at line 351 of file cvGenericFilter.cpp.
References m_color2.
colorsChanged()
void cvGenericFilter::colorsChanged () protected virtual
Reimplemented in cvIsoSurfaceFilter.
Definition at line 193 of file cvGenericFilter.cpp.
References createLookupTable(), m_filterActor, m_modelActor, m_scalarBar, m_scalarMax, m_scalarMin, m_viewer, and update().
Referenced by setScalarBarColors().
createActorFromData()
template<class DataObject , class Mapper > void cvGenericFilter::createActorFromData (vtkDataObject * dataObj) protected
Definition at line 429 of file cvGenericFilter.cpp.
References addActor(), data, dataChanged(), CVLog::Error(), m_dataObject, m_modelActor, modelReady(), update(), and VTK_CREATE.
createLookupTable()
vtkSmartPointer< vtkLookupTable > cvGenericFilter::createLookupTable (double min, double max) protected
Definition at line 376 of file cvGenericFilter.cpp.
References m_color1, m_color2, Utils::qColor2HSV(), and VTK_CREATE.
Referenced by cvSliceFilter::apply(), cvIsoSurfaceFilter::apply(), cvThresholdFilter::apply(), applyDisplayEffect(), colorsChanged(), cvIsoSurfaceFilter::colorsChanged(), cvIsoSurfaceFilter::modelReady(), and showScalarBar().
createUi()
virtual void cvGenericFilter::createUi () inline protected virtual
Reimplemented in cvStreamlineFilter, cvSmoothFilter, cvProbeFilter, cvIsoSurfaceFilter, cvGlyphFilter, cvDecimateFilter, and cvCutFilter.
Definition at line 95 of file cvGenericFilter.h.
Referenced by cvCutFilter::createUi(), cvDecimateFilter::createUi(), cvGlyphFilter::createUi(), cvIsoSurfaceFilter::createUi(), cvProbeFilter::createUi(), cvSmoothFilter::createUi(), and cvStreamlineFilter::createUi().
dataChanged()
virtual void cvGenericFilter::dataChanged () inline protected virtual
Reimplemented in cvStreamlineFilter, cvSmoothFilter, cvProbeFilter, cvIsoSurfaceFilter, cvGlyphFilter, cvDecimateFilter, and cvCutFilter.
Definition at line 77 of file cvGenericFilter.h.
Referenced by createActorFromData(), reset(), and start().
displayEffect()
cvGenericFilter::DisplayEffect cvGenericFilter::displayEffect () const protected
Definition at line 227 of file cvGenericFilter.cpp.
References m_displayEffect.
getActorScalars()
vtkSmartPointer< vtkDataArray > cvGenericFilter::getActorScalars (vtkSmartPointer< vtkActor > actor) protected
Definition at line 362 of file cvGenericFilter.cpp.
Referenced by cvIsoSurfaceFilter::initFilter().
getDefaultScalarInterpolationForDataSet()
int cvGenericFilter::getDefaultScalarInterpolationForDataSet (vtkDataSet * data) protected
Definition at line 369 of file cvGenericFilter.cpp.
References data.
Referenced by cvIsoSurfaceFilter::clearAllActor().
getInteractor()
vtkRenderWindowInteractor* cvGenericFilter::getInteractor () inline
Definition at line 85 of file cvGenericFilter.h.
References m_interactor.
Referenced by cvCutFilter::updateCutWidget().
getInteractorBounds()
virtual void cvGenericFilter::getInteractorBounds (ccBBox & bbox) inline virtual
Reimplemented in cvStreamlineFilter, cvProbeFilter, and cvCutFilter.
Definition at line 72 of file cvGenericFilter.h.
Referenced by PclFiltersTool::getBox(), and getInteractorInfos().
getInteractorInfos()
void cvGenericFilter::getInteractorInfos (ccBBox & bbox, ccGLMatrixd & trans) virtual
Definition at line 188 of file cvGenericFilter.cpp.
References getInteractorBounds(), and getInteractorTransformation().
Referenced by PclFiltersTool::get().
getInteractorTransformation()
virtual void cvGenericFilter::getInteractorTransformation (ccGLMatrixd & trans) inline virtual
Reimplemented in cvStreamlineFilter, cvProbeFilter, and cvCutFilter.
Definition at line 70 of file cvGenericFilter.h.
Referenced by getInteractorInfos().
getOutput() [1/2]
ccHObject * cvGenericFilter::getOutput () virtual
Reimplemented in cvThresholdFilter, cvStreamlineFilter, cvSmoothFilter, cvSliceFilter, cvProbeFilter, cvIsoSurfaceFilter, cvGlyphFilter, cvDecimateFilter, and cvClipFilter.
Definition at line 143 of file cvGenericFilter.cpp.
References vtk2cc::ConvertToMesh(), vtk2cc::ConvertToPointCloud(), m_meshMode, result, resultData(), and CVLog::Warning().
Referenced by PclFiltersTool::getOutput(), cvClipFilter::getOutput(), cvDecimateFilter::getOutput(), cvIsoSurfaceFilter::getOutput(), cvSmoothFilter::getOutput(), cvStreamlineFilter::getOutput(), cvThresholdFilter::getOutput(), and getOutput().
getOutput() [2/2]
void cvGenericFilter::getOutput (std::vector< ccHObject * > & outputSlices, std::vector< ccPolyline * > & outputContours) virtual
Definition at line 168 of file cvGenericFilter.cpp.
References getOutput().
initFilter()
virtual void cvGenericFilter::initFilter () inline protected virtual
Reimplemented in cvThresholdFilter, cvStreamlineFilter, cvSmoothFilter, cvProbeFilter, cvIsoSurfaceFilter, cvGlyphFilter, cvDecimateFilter, and cvCutFilter.
Definition at line 94 of file cvGenericFilter.h.
Referenced by cvCutFilter::initFilter(), cvDecimateFilter::initFilter(), cvGlyphFilter::initFilter(), cvProbeFilter::initFilter(), cvStreamlineFilter::initFilter(), and start().
initModel()
bool cvGenericFilter::initModel () virtual
Definition at line 106 of file cvGenericFilter.cpp.
References PclUtils::PCLVis::getActorById(), m_dataObject, m_id, m_modelActor, m_preview, m_resultData, m_viewer, and MAX_PREVIEW_NUMBER.
Referenced by restoreOrigin(), and setInput().
isValidDataSet()
bool cvGenericFilter::isValidDataSet () const protected
Definition at line 476 of file cvGenericFilter.cpp.
References m_dataObject.
Referenced by cvClipFilter::apply(), cvClipFilter::getOutput(), cvCutFilter::modelReady(), cvCutFilter::resetBoxWidget(), cvCutFilter::resetPlaneWidget(), cvCutFilter::resetSphereWidget(), cvCutFilter::updateCutWidget(), and UpdateScalarRange().
isValidPolyData()
bool cvGenericFilter::isValidPolyData () const protected
Definition at line 472 of file cvGenericFilter.cpp.
References m_dataObject.
Referenced by cvClipFilter::apply(), cvClipFilter::getOutput(), cvCutFilter::modelReady(), cvCutFilter::resetBoxWidget(), cvCutFilter::resetPlaneWidget(), cvCutFilter::resetSphereWidget(), cvCutFilter::updateCutWidget(), and UpdateScalarRange().
modelReady()
void cvGenericFilter::modelReady () protected virtual
Reimplemented in cvStreamlineFilter, cvProbeFilter, cvIsoSurfaceFilter, cvGlyphFilter, and cvCutFilter.
Definition at line 177 of file cvGenericFilter.cpp.
References showOutline(), and ecvDisplayTools::UpdateCamera().
Referenced by createActorFromData(), cvCutFilter::modelReady(), cvGlyphFilter::modelReady(), cvIsoSurfaceFilter::modelReady(), cvProbeFilter::modelReady(), cvStreamlineFilter::modelReady(), and start().
onDoubleClick
void cvGenericFilter::onDoubleClick (int x, int y) protected slot
Definition at line 68 of file cvGenericFilter.cpp.
References applyDisplayEffect().
Referenced by cvGenericFilter().
removeActor()
void cvGenericFilter::removeActor (const vtkSmartPointer< vtkProp > actor) protected
Definition at line 398 of file cvGenericFilter.cpp.
References m_viewer, and PclUtils::PCLVis::removeActorFromRenderer().
Referenced by clearAllActor(), cvCutFilter::clearAllActor(), and cvGlyphFilter::clearAllActor().
reset()
void cvGenericFilter::reset (void) virtual
Definition at line 208 of file cvGenericFilter.cpp.
References dataChanged(), and update().
Referenced by PclFiltersTool::reset().
restoreOrigin()
void cvGenericFilter::restoreOrigin () virtual
Definition at line 213 of file cvGenericFilter.cpp.
References initModel(), m_viewer, and start().
Referenced by PclFiltersTool::restore().
resultData()
vtkSmartPointer< vtkDataObject > cvGenericFilter::resultData () const protected
Definition at line 468 of file cvGenericFilter.cpp.
References m_resultData.
Referenced by getOutput(), and cvIsoSurfaceFilter::getOutput().
safeOff()
void cvGenericFilter::safeOff (vtk3DWidget * widget) protected
Definition at line 480 of file cvGenericFilter.cpp.
Referenced by cvCutFilter::clearAllActor(), cvProbeFilter::clearAllActor(), cvStreamlineFilter::clearAllActor(), cvCutFilter::showInteractor(), cvProbeFilter::showInteractor(), cvStreamlineFilter::showInteractor(), and cvCutFilter::updateCutWidget().
scalarMax()
double cvGenericFilter::scalarMax () const protected
Definition at line 360 of file cvGenericFilter.cpp.
References m_scalarMax.
Referenced by cvSliceFilter::apply().
scalarMin()
double cvGenericFilter::scalarMin () const protected
Definition at line 358 of file cvGenericFilter.cpp.
References m_scalarMin.
Referenced by cvSliceFilter::apply().
setDisplayEffect()
void cvGenericFilter::setDisplayEffect (cvGenericFilter::DisplayEffect effect) protected
Definition at line 220 of file cvGenericFilter.cpp.
References applyDisplayEffect(), and m_displayEffect.
Referenced by cvDecimateFilter::initFilter(), cvProbeFilter::initFilter(), and cvIsoSurfaceFilter::onComboBoxIndexChanged().
setInput()
bool cvGenericFilter::setInput (ccHObject * obj) virtual
Definition at line 85 of file cvGenericFilter.cpp.
References CVLog::Error(), ccHObject::getViewId(), initModel(), ccObject::isKindOf(), m_entity, m_id, m_meshMode, CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, and updateUi().
Referenced by PclFiltersTool::setInputData().
setInteractor()
void cvGenericFilter::setInteractor (vtkRenderWindowInteractor * interactor)
Definition at line 460 of file cvGenericFilter.cpp.
References m_interactor.
Referenced by setUpViewer().
setNegative()
void cvGenericFilter::setNegative (bool state) inline
Definition at line 83 of file cvGenericFilter.h.
References m_negative.
Referenced by cvCutFilter::createUi(), and PclFiltersTool::setNegative().
setOutlineColor()
void cvGenericFilter::setOutlineColor (const QColor & clr) protected
Definition at line 331 of file cvGenericFilter.cpp.
References m_outlineActor, update(), and Utils::vtkColor().
setResultData()
void cvGenericFilter::setResultData (vtkSmartPointer< vtkDataObject > data) protected
Definition at line 464 of file cvGenericFilter.cpp.
References data, and m_resultData.
Referenced by cvClipFilter::getOutput(), cvDecimateFilter::getOutput(), cvIsoSurfaceFilter::getOutput(), cvSmoothFilter::getOutput(), cvStreamlineFilter::getOutput(), cvThresholdFilter::getOutput(), and cvCutFilter::showContourLines().
setScalarBarColors()
void cvGenericFilter::setScalarBarColors (const QColor & clr1, const QColor & clr2) protected
Definition at line 340 of file cvGenericFilter.cpp.
References colorsChanged(), m_color1, and m_color2.
Referenced by cvIsoSurfaceFilter::on_gradientCombo_activated().
setScalarRange()
void cvGenericFilter::setScalarRange (double min, double max) protected
Definition at line 353 of file cvGenericFilter.cpp.
References m_scalarMax, and m_scalarMin.
Referenced by cvCutFilter::modelReady(), cvIsoSurfaceFilter::modelReady(), and UpdateScalarRange().
setupConfigWidget()
template<class ConfigClass > void cvGenericFilter::setupConfigWidget (ConfigClass * cc) inline protected
Definition at line 123 of file cvGenericFilter.h.
References m_ui.
Referenced by cvCutFilter::createUi(), cvDecimateFilter::createUi(), cvGlyphFilter::createUi(), cvIsoSurfaceFilter::createUi(), cvProbeFilter::createUi(), cvSmoothFilter::createUi(), and cvStreamlineFilter::createUi().
setUpViewer()
void cvGenericFilter::setUpViewer (PclUtils::PCLVis * viewer)
Definition at line 182 of file cvGenericFilter.cpp.
References PclUtils::PCLVis::getRenderWindowInteractor(), m_viewer, and setInteractor().
Referenced by PclFiltersTool::initialize().
shift()
virtual void cvGenericFilter::shift (const CCVector3d & v) inline virtual
Shifts the current interactor.
Reimplemented in cvStreamlineFilter, cvProbeFilter, and cvCutFilter.
Definition at line 65 of file cvGenericFilter.h.
Referenced by PclFiltersTool::shift().
showInteractor()
virtual void cvGenericFilter::showInteractor (bool state) inline virtual
Reimplemented in cvStreamlineFilter, cvProbeFilter, cvGlyphFilter, and cvCutFilter.
Definition at line 68 of file cvGenericFilter.h.
Referenced by PclFiltersTool::showInteractor().
showOutline()
void cvGenericFilter::showOutline (bool show = true)
Definition at line 308 of file cvGenericFilter.cpp.
References addActor(), CVLog::Error(), m_dataObject, m_outlineActor, update(), VTK_CREATE, and VtkUtils::vtkInitOnce().
Referenced by modelReady(), and PclFiltersTool::showOutline().
showScalarBar()
void cvGenericFilter::showScalarBar (bool show = true) protected
Definition at line 285 of file cvGenericFilter.cpp.
References addActor(), createLookupTable(), m_scalarBar, m_scalarMax, m_scalarMin, and update().
Referenced by cvCutFilter::modelReady(), and cvIsoSurfaceFilter::modelReady().
start()
void cvGenericFilter::start (void) virtual
Definition at line 71 of file cvGenericFilter.cpp.
References dataChanged(), initFilter(), modelReady(), and update().
Referenced by restoreOrigin(), and PclFiltersTool::start().
update()
void cvGenericFilter::update () virtual
Definition at line 203 of file cvGenericFilter.cpp.
References ecvDisplayTools::UpdateScreen().
Referenced by cvProbeFilter::apply(), cvSmoothFilter::apply(), applyDisplayEffect(), colorsChanged(), cvIsoSurfaceFilter::colorsChanged(), createActorFromData(), reset(), setOutlineColor(), cvCutFilter::showContourLines(), showOutline(), showScalarBar(), and start().
UpdateScalarRange()
void cvGenericFilter::UpdateScalarRange () protected
Definition at line 242 of file cvGenericFilter.cpp.
References isValidDataSet(), isValidPolyData(), m_dataObject, and setScalarRange().
Referenced by cvCutFilter::resetBoxWidget(), and cvCutFilter::resetPlaneWidget().
updateSize()
void cvGenericFilter::updateSize () protected
Definition at line 231 of file cvGenericFilter.cpp.
Referenced by cvCutFilter::updateCutWidget().
updateUi()
virtual void cvGenericFilter::updateUi () inline virtual
Reimplemented in cvCutFilter.
Definition at line 67 of file cvGenericFilter.h.
Referenced by setInput().
Member Data Documentation
m_color1
QColor cvGenericFilter::m_color1 = Qt::blue protected
Definition at line 170 of file cvGenericFilter.h.
Referenced by color1(), createLookupTable(), and setScalarBarColors().
m_color2
QColor cvGenericFilter::m_color2 = Qt::red protected
Definition at line 171 of file cvGenericFilter.h.
Referenced by color2(), createLookupTable(), and setScalarBarColors().
m_dataObject
vtkDataObject* cvGenericFilter::m_dataObject = nullptr protected
Definition at line 153 of file cvGenericFilter.h.
Referenced by cvSliceFilter::apply(), cvClipFilter::apply(), cvDecimateFilter::apply(), cvGlyphFilter::apply(), cvIsoSurfaceFilter::apply(), cvProbeFilter::apply(), cvSmoothFilter::apply(), cvStreamlineFilter::apply(), cvThresholdFilter::apply(), createActorFromData(), cvStreamlineFilter::dataChanged(), cvClipFilter::getOutput(), initModel(), isValidDataSet(), isValidPolyData(), cvCutFilter::modelReady(), cvIsoSurfaceFilter::modelReady(), cvStreamlineFilter::modelReady(), cvCutFilter::resetBoxWidget(), cvCutFilter::resetPlaneWidget(), cvCutFilter::resetSphereWidget(), cvCutFilter::showContourLines(), showOutline(), cvCutFilter::updateCutWidget(), UpdateScalarRange(), and ~cvGenericFilter().
m_displayEffect
DisplayEffect cvGenericFilter::m_displayEffect = Opaque protected
Definition at line 152 of file cvGenericFilter.h.
Referenced by applyDisplayEffect(), displayEffect(), and setDisplayEffect().
m_entity
ccHObject* cvGenericFilter::m_entity = nullptr protected
Definition at line 161 of file cvGenericFilter.h.
Referenced by cvIsoSurfaceFilter::getOutput(), cvSliceFilter::getOutput(), and setInput().
m_filterActor
vtkSmartPointer<vtkLODActor> cvGenericFilter::m_filterActor protected
Definition at line 166 of file cvGenericFilter.h.
Referenced by cvSliceFilter::apply(), cvClipFilter::apply(), cvDecimateFilter::apply(), cvGlyphFilter::apply(), cvIsoSurfaceFilter::apply(), cvSmoothFilter::apply(), cvStreamlineFilter::apply(), cvThresholdFilter::apply(), clearAllActor(), colorsChanged(), cvIsoSurfaceFilter::colorsChanged(), cvStreamlineFilter::getOutput(), cvIsoSurfaceFilter::initFilter(), and cvGlyphFilter::showInteractor().
m_id
std::string cvGenericFilter::m_id protected
Definition at line 160 of file cvGenericFilter.h.
Referenced by initModel(), and setInput().
m_interactor
vtkRenderWindowInteractor* cvGenericFilter::m_interactor = nullptr protected
Definition at line 163 of file cvGenericFilter.h.
Referenced by getInteractor(), and setInteractor().
m_keepMode
bool cvGenericFilter::m_keepMode protected
Definition at line 156 of file cvGenericFilter.h.
Referenced by cvSliceFilter::apply(), cvClipFilter::apply(), cvDecimateFilter::apply(), cvSmoothFilter::apply(), cvDecimateFilter::cvDecimateFilter(), cvDecimateFilter::dataChanged(), and cvSmoothFilter::dataChanged().
m_meshMode
bool cvGenericFilter::m_meshMode protected
Definition at line 158 of file cvGenericFilter.h.
Referenced by cvDecimateFilter::apply(), cvIsoSurfaceFilter::apply(), cvSmoothFilter::apply(), clearAllActor(), getOutput(), cvIsoSurfaceFilter::getOutput(), cvCutFilter::initFilter(), cvIsoSurfaceFilter::initFilter(), cvCutFilter::modelReady(), setInput(), and cvCutFilter::showContourLines().
m_modelActor
vtkSmartPointer<vtkActor> cvGenericFilter::m_modelActor protected
Definition at line 165 of file cvGenericFilter.h.
Referenced by applyDisplayEffect(), clearAllActor(), cvIsoSurfaceFilter::clearAllActor(), colorsChanged(), cvIsoSurfaceFilter::colorsChanged(), createActorFromData(), cvIsoSurfaceFilter::initFilter(), cvSmoothFilter::initFilter(), initModel(), and cvCutFilter::updateCutWidget().
m_negative
bool cvGenericFilter::m_negative protected
Definition at line 157 of file cvGenericFilter.h.
Referenced by cvClipFilter::apply(), cvClipFilter::getOutput(), and setNegative().
m_outlineActor
vtkSmartPointer<vtkActor> cvGenericFilter::m_outlineActor protected
Definition at line 168 of file cvGenericFilter.h.
Referenced by clearAllActor(), setOutlineColor(), and showOutline().
m_preview
bool cvGenericFilter::m_preview protected
Definition at line 159 of file cvGenericFilter.h.
Referenced by cvClipFilter::apply(), cvCutFilter::createUi(), cvClipFilter::getOutput(), cvCutFilter::initFilter(), initModel(), cvCutFilter::onPreview(), and cvCutFilter::updateUi().
m_resultData
vtkSmartPointer<vtkDataObject> cvGenericFilter::m_resultData protected
Definition at line 154 of file cvGenericFilter.h.
Referenced by initModel(), resultData(), and setResultData().
m_scalarBar
vtkSmartPointer<vtkScalarBarActor> cvGenericFilter::m_scalarBar protected
Definition at line 167 of file cvGenericFilter.h.
Referenced by cvIsoSurfaceFilter::apply(), cvThresholdFilter::apply(), clearAllActor(), colorsChanged(), cvIsoSurfaceFilter::colorsChanged(), cvIsoSurfaceFilter::modelReady(), and showScalarBar().
m_scalarMax
double cvGenericFilter::m_scalarMax = 1.0 protected
Definition at line 173 of file cvGenericFilter.h.
Referenced by applyDisplayEffect(), colorsChanged(), scalarMax(), setScalarRange(), and showScalarBar().
m_scalarMin
double cvGenericFilter::m_scalarMin = 0.0 protected
Definition at line 172 of file cvGenericFilter.h.
Referenced by applyDisplayEffect(), colorsChanged(), scalarMin(), setScalarRange(), and showScalarBar().
m_ui
Ui::GenericFilterDlg* cvGenericFilter::m_ui = nullptr protected
Definition at line 150 of file cvGenericFilter.h.
Referenced by setupConfigWidget(), and ~cvGenericFilter().
m_viewer
PclUtils::PCLVis* cvGenericFilter::m_viewer = nullptr protected
Definition at line 162 of file cvGenericFilter.h.
Referenced by addActor(), clearAllActor(), cvIsoSurfaceFilter::clearAllActor(), colorsChanged(), initModel(), removeActor(), restoreOrigin(), and setUpViewer().
MAX_PREVIEW_NUMBER
const int cvGenericFilter::MAX_PREVIEW_NUMBER = 20e4 static protected
Definition at line 174 of file cvGenericFilter.h.
Referenced by initModel().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/cvGenericFilter.h
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/cvGenericFilter.cpp