ACloudViewer: CorrespondenceMatchingDialog Class Reference
CorrespondenceMatchingDialog Class Reference
CANUPO plugin's training dialog.
#include <CorrespondenceMatchingDialog.h>
Public Member Functions
CorrespondenceMatchingDialog (ecvMainAppInterface *app)
Default constructor.
ccPointCloud * getModel1Cloud ()
Get model #1 point cloud.
ccPointCloud * getModel2Cloud ()
Get model #2 point cloud.
ccPointCloud * getModelCloudByIndex (int index)
ccPointCloud * getEvaluationCloud ()
Get evaluation point cloud.
void loadParamsFromPersistentSettings ()
Loads parameters from persistent settings.
void saveParamsToPersistentSettings ()
Saves parameters to persistent settings.
bool getScales (std::vector< float > &scales) const
Returns input scales.
int getMaxThreadCount () const
Returns the max number of threads to use.
float getVoxelGridLeafSize () const
float getModelSearchRadius () const
Returns the Model Search Radius.
float getSceneSearchRadius () const
Returns the Scene Search Radius.
float getShotDescriptorRadius () const
Returns the Shot Descriptor Radius.
float getNormalKSearch () const
Returns the normal KSearch.
bool getVerificationFlag () const
bool isGCActivated () const
float getGcConsensusSetResolution () const
float getGcMinClusterSize () const
float getHoughLRFRadius () const
float getHoughBinSize () const
float getHoughThreshold () const
void refreshCloudComboBox ()
Protected Slots
void onCloudChanged (int)
Protected Member Functions
bool validParameters () const
QString getEntityName (ccHObject *obj)
ccPointCloud * getCloudFromCombo (QComboBox *comboBox, ccHObject *dbRoot)
Protected Attributes
ecvMainAppInterface * m_app
Gives access to the application (data-base, UI, etc.)
Detailed Description
CANUPO plugin's training dialog.
Definition at line 20 of file CorrespondenceMatchingDialog.h.
Constructor & Destructor Documentation
CorrespondenceMatchingDialog()
CorrespondenceMatchingDialog::CorrespondenceMatchingDialog (ecvMainAppInterface * app)
Default constructor.
Definition at line 28 of file CorrespondenceMatchingDialog.cpp.
References loadParamsFromPersistentSettings(), and onCloudChanged().
Member Function Documentation
getCloudFromCombo()
ccPointCloud * CorrespondenceMatchingDialog::getCloudFromCombo (QComboBox * comboBox, ccHObject * dbRoot) protected
Definition at line 316 of file CorrespondenceMatchingDialog.cpp.
References ccHObject::find(), ccObject::isA(), and CV_TYPES::POINT_CLOUD.
Referenced by getEvaluationCloud(), getModel1Cloud(), and getModel2Cloud().
getEntityName()
QString CorrespondenceMatchingDialog::getEntityName (ccHObject * obj) protected
Definition at line 303 of file CorrespondenceMatchingDialog.cpp.
References ccObject::getName(), ccObject::getUniqueID(), and name.
Referenced by refreshCloudComboBox().
getEvaluationCloud()
ccPointCloud * CorrespondenceMatchingDialog::getEvaluationCloud ()
Get evaluation point cloud.
Definition at line 242 of file CorrespondenceMatchingDialog.cpp.
References getCloudFromCombo(), and m_app.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getGcConsensusSetResolution()
float CorrespondenceMatchingDialog::getGcConsensusSetResolution () const
Definition at line 138 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getGcMinClusterSize()
float CorrespondenceMatchingDialog::getGcMinClusterSize () const
Definition at line 142 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getHoughBinSize()
float CorrespondenceMatchingDialog::getHoughBinSize () const
Definition at line 150 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getHoughLRFRadius()
float CorrespondenceMatchingDialog::getHoughLRFRadius () const
Definition at line 146 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getHoughThreshold()
float CorrespondenceMatchingDialog::getHoughThreshold () const
Definition at line 154 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getMaxThreadCount()
int CorrespondenceMatchingDialog::getMaxThreadCount () const
Returns the max number of threads to use.
Definition at line 110 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getModel1Cloud()
ccPointCloud * CorrespondenceMatchingDialog::getModel1Cloud ()
Get model #1 point cloud.
Definition at line 210 of file CorrespondenceMatchingDialog.cpp.
References getCloudFromCombo(), and m_app.
Referenced by getModelCloudByIndex().
getModel2Cloud()
ccPointCloud * CorrespondenceMatchingDialog::getModel2Cloud ()
Get model #2 point cloud.
Definition at line 219 of file CorrespondenceMatchingDialog.cpp.
References getCloudFromCombo(), and m_app.
Referenced by getModelCloudByIndex().
getModelCloudByIndex()
ccPointCloud * CorrespondenceMatchingDialog::getModelCloudByIndex (int index)
Definition at line 228 of file CorrespondenceMatchingDialog.cpp.
References getModel1Cloud(), and getModel2Cloud().
Referenced by CorrespondenceMatching::compute(), and CorrespondenceMatching::getParametersFromDialog().
getModelSearchRadius()
float CorrespondenceMatchingDialog::getModelSearchRadius () const
Returns the Model Search Radius.
Definition at line 118 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getNormalKSearch()
float CorrespondenceMatchingDialog::getNormalKSearch () const
Returns the normal KSearch.
Definition at line 130 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getScales()
bool CorrespondenceMatchingDialog::getScales (std::vector< float > & scales) const
Returns input scales.
Definition at line 166 of file CorrespondenceMatchingDialog.cpp.
References cloudViewer::utility::floor(), and QtCompat::SkipEmptyParts.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getSceneSearchRadius()
float CorrespondenceMatchingDialog::getSceneSearchRadius () const
Returns the Scene Search Radius.
Definition at line 122 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getShotDescriptorRadius()
float CorrespondenceMatchingDialog::getShotDescriptorRadius () const
Returns the Shot Descriptor Radius.
Definition at line 126 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getVerificationFlag()
bool CorrespondenceMatchingDialog::getVerificationFlag () const
Definition at line 114 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
getVoxelGridLeafSize()
float CorrespondenceMatchingDialog::getVoxelGridLeafSize () const
Definition at line 158 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
isGCActivated()
bool CorrespondenceMatchingDialog::isGCActivated () const
Definition at line 134 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::getParametersFromDialog().
loadParamsFromPersistentSettings()
void CorrespondenceMatchingDialog::loadParamsFromPersistentSettings ()
Loads parameters from persistent settings.
Definition at line 247 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatchingDialog().
onCloudChanged
void CorrespondenceMatchingDialog::onCloudChanged (int dummy) protected slot
Definition at line 206 of file CorrespondenceMatchingDialog.cpp.
References validParameters().
Referenced by CorrespondenceMatchingDialog().
refreshCloudComboBox()
void CorrespondenceMatchingDialog::refreshCloudComboBox ()
Definition at line 50 of file CorrespondenceMatchingDialog.cpp.
References getEntityName(), m_app, name, and CV_TYPES::POINT_CLOUD.
Referenced by CorrespondenceMatching::openInputDialog().
saveParamsToPersistentSettings()
void CorrespondenceMatchingDialog::saveParamsToPersistentSettings ()
Saves parameters to persistent settings.
Definition at line 286 of file CorrespondenceMatchingDialog.cpp.
Referenced by CorrespondenceMatching::openInputDialog().
validParameters()
bool CorrespondenceMatchingDialog::validParameters () const protected
Definition at line 89 of file CorrespondenceMatchingDialog.cpp.
Referenced by onCloudChanged().
Member Data Documentation
m_app
ecvMainAppInterface* CorrespondenceMatchingDialog::m_app protected
Gives access to the application (data-base, UI, etc.)
Definition at line 77 of file CorrespondenceMatchingDialog.h.
Referenced by getEvaluationCloud(), getModel1Cloud(), getModel2Cloud(), and refreshCloudComboBox().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Recognitions/dialogs/CorrespondenceMatchingDialog.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Recognitions/dialogs/CorrespondenceMatchingDialog.cpp