ACloudViewer: ccPluginUIManager Class Reference
ccPluginUIManager Class Reference
Plugin UI manager.
#include <ecvPluginUIManager.h>
Public Member Functions
ccPluginUIManager (ecvMainAppInterface *appInterface, QWidget *parent)
~ccPluginUIManager ()
void init ()
QMenu * pluginMenu () const
QMenu * pclAlgorithmMenu () const
QToolBar * mainPluginToolbar ()
QList< QToolBar * > & additionalPluginToolbars ()
QAction * actionShowMainPluginToolbar ()
QToolBar * glPclToolbar ()
QAction * actionShowPCLAlgorithmToolbar ()
void updateMenus ()
void handleSelectionChanged ()
void showAboutDialog () const
Static Public Member Functions
static bool isPythonPluginToolbar (QToolBar *toolbar)
Detailed Description
Plugin UI manager.
Definition at line 28 of file ecvPluginUIManager.h.
Constructor & Destructor Documentation
ccPluginUIManager()
ccPluginUIManager::ccPluginUIManager (ecvMainAppInterface * appInterface, QWidget * parent)
Definition at line 24 of file ecvPluginUIManager.cpp.
~ccPluginUIManager()
ccPluginUIManager::~ccPluginUIManager ()
Definition at line 42 of file ecvPluginUIManager.cpp.
Member Function Documentation
actionShowMainPluginToolbar()
QAction * ccPluginUIManager::actionShowMainPluginToolbar ()
Definition at line 237 of file ecvPluginUIManager.cpp.
Referenced by MainWindow::initPlugins().
actionShowPCLAlgorithmToolbar()
QAction * ccPluginUIManager::actionShowPCLAlgorithmToolbar ()
Definition at line 243 of file ecvPluginUIManager.cpp.
Referenced by MainWindow::initPlugins().
additionalPluginToolbars()
QList< QToolBar * > & ccPluginUIManager::additionalPluginToolbars ()
Definition at line 233 of file ecvPluginUIManager.cpp.
Referenced by MainWindow::freezeUI(), ecvLayoutManager::hideAdditionalPluginToolbars(), and MainWindow::initPlugins().
glPclToolbar()
QToolBar * ccPluginUIManager::glPclToolbar ()
Definition at line 241 of file ecvPluginUIManager.cpp.
Referenced by MainWindow::initPlugins().
handleSelectionChanged()
void ccPluginUIManager::handleSelectionChanged ()
Definition at line 266 of file ecvPluginUIManager.cpp.
References ECV_PCL_ALGORITHM_PLUGIN, ECV_STD_PLUGIN, ecvMainAppInterface::getSelectedEntities(), ccPclPluginInterface::onNewSelection(), and ccStdPluginInterface::onNewSelection().
init()
void ccPluginUIManager::init ()
Definition at line 44 of file ecvPluginUIManager.cpp.
References ECV_IO_FILTER_PLUGIN, ECV_PCL_ALGORITHM_PLUGIN, ECV_STD_PLUGIN, ccPluginManager::get(), ccDefaultPluginInterface::getDescription(), ccDefaultPluginInterface::getIcon(), ecvMainAppInterface::getSelectedEntities(), ccDefaultPluginInterface::isCore(), ccPluginManager::pluginList(), ccPclPluginInterface::setMainAppInterface(), and ccStdPluginInterface::setMainAppInterface().
Referenced by MainWindow::initPlugins().
isPythonPluginToolbar()
bool ccPluginUIManager::isPythonPluginToolbar (QToolBar * toolbar) static
Definition at line 247 of file ecvPluginUIManager.cpp.
Referenced by ecvLayoutManager::hideAdditionalPluginToolbars(), and MainWindow::initPlugins().
mainPluginToolbar()
QToolBar * ccPluginUIManager::mainPluginToolbar ()
Definition at line 231 of file ecvPluginUIManager.cpp.
Referenced by MainWindow::freezeUI(), and MainWindow::initPlugins().
pclAlgorithmMenu()
QMenu * ccPluginUIManager::pclAlgorithmMenu () const
Definition at line 227 of file ecvPluginUIManager.cpp.
Referenced by MainWindow::initPlugins().
pluginMenu()
QMenu * ccPluginUIManager::pluginMenu () const
Definition at line 225 of file ecvPluginUIManager.cpp.
Referenced by MainWindow::initPlugins().
showAboutDialog()
void ccPluginUIManager::showAboutDialog () const
Definition at line 285 of file ecvPluginUIManager.cpp.
References ccPluginManager::get(), ccPluginInfoDlg::setPluginList(), and ccPluginInfoDlg::setPluginPaths().
updateMenus()
void ccPluginUIManager::updateMenus ()
Definition at line 255 of file ecvPluginUIManager.cpp.
References ecvMainAppInterface::getActiveWindow().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/pluginManager/ecvPluginUIManager.h
/root/ACloudViewer/app/pluginManager/ecvPluginUIManager.cpp