ACloudViewer: WaitingSpinnerWidget Class Reference
WaitingSpinnerWidget Class Reference
#include <WaitingSpinnerWidget.h>
Public Slots
void start ()
void stop ()
Public Member Functions
WaitingSpinnerWidget (QWidget *parent=nullptr, bool centerOnParent=true, bool disableParentWhenSpinning=true)
WaitingSpinnerWidget (Qt::WindowModality modality, QWidget *parent=nullptr, bool centerOnParent=true, bool disableParentWhenSpinning=true)
void setColor (QColor color)
void setRoundness (qreal roundness)
void setMinimumTrailOpacity (qreal minimumTrailOpacity)
void setTrailFadePercentage (qreal trail)
void setRevolutionsPerSecond (qreal revolutionsPerSecond)
void setNumberOfLines (int lines)
void setLineLength (int length)
void setLineWidth (int width)
void setInnerRadius (int radius)
QColor color ()
qreal roundness ()
qreal minimumTrailOpacity ()
qreal trailFadePercentage ()
qreal revolutionsPersSecond ()
int numberOfLines ()
int lineLength ()
int lineWidth ()
int innerRadius ()
bool isSpinning () const
Protected Member Functions
void paintEvent (QPaintEvent *paintEvent) override
Detailed Description
Definition at line 39 of file WaitingSpinnerWidget.h.
Constructor & Destructor Documentation
WaitingSpinnerWidget() [1/2]
WaitingSpinnerWidget::WaitingSpinnerWidget (QWidget * parent = nullptr, bool centerOnParent = true, bool disableParentWhenSpinning = true) explicit
Constructor for "standard" widget behaviour - use this constructor if you wish to, e.g. embed your widget in another.
Definition at line 18 of file WaitingSpinnerWidget.cpp.
WaitingSpinnerWidget() [2/2]
WaitingSpinnerWidget::WaitingSpinnerWidget (Qt::WindowModality modality, QWidget * parent = nullptr, bool centerOnParent = true, bool disableParentWhenSpinning = true) explicit
Constructor - use this constructor to automatically create a modal ("blocking") spinner on top of the calling widget/window. If a valid parent widget is provided, "centreOnParent" will ensure that QtWaitingSpinner automatically centres itself on it, if not, "centreOnParent" is ignored.
Definition at line 28 of file WaitingSpinnerWidget.cpp.
Member Function Documentation
color()
QColor WaitingSpinnerWidget::color ()
Definition at line 159 of file WaitingSpinnerWidget.cpp.
Referenced by paintEvent(), and setColor().
innerRadius()
int WaitingSpinnerWidget::innerRadius ()
Definition at line 199 of file WaitingSpinnerWidget.cpp.
isSpinning()
bool WaitingSpinnerWidget::isSpinning () const
Definition at line 204 of file WaitingSpinnerWidget.cpp.
lineLength()
int WaitingSpinnerWidget::lineLength ()
Definition at line 189 of file WaitingSpinnerWidget.cpp.
lineWidth()
int WaitingSpinnerWidget::lineWidth ()
Definition at line 194 of file WaitingSpinnerWidget.cpp.
minimumTrailOpacity()
qreal WaitingSpinnerWidget::minimumTrailOpacity ()
Definition at line 169 of file WaitingSpinnerWidget.cpp.
Referenced by setMinimumTrailOpacity().
numberOfLines()
int WaitingSpinnerWidget::numberOfLines ()
Definition at line 184 of file WaitingSpinnerWidget.cpp.
paintEvent()
void WaitingSpinnerWidget::paintEvent (QPaintEvent * paintEvent) override protected
Definition at line 66 of file WaitingSpinnerWidget.cpp.
References color().
revolutionsPersSecond()
qreal WaitingSpinnerWidget::revolutionsPersSecond ()
Definition at line 179 of file WaitingSpinnerWidget.cpp.
roundness()
qreal WaitingSpinnerWidget::roundness ()
Definition at line 164 of file WaitingSpinnerWidget.cpp.
Referenced by setRoundness().
setColor()
void WaitingSpinnerWidget::setColor (QColor color)
Definition at line 214 of file WaitingSpinnerWidget.cpp.
References color().
setInnerRadius()
void WaitingSpinnerWidget::setInnerRadius (int radius)
Definition at line 153 of file WaitingSpinnerWidget.cpp.
setLineLength()
void WaitingSpinnerWidget::setLineLength (int length)
Definition at line 141 of file WaitingSpinnerWidget.cpp.
References length().
setLineWidth()
void WaitingSpinnerWidget::setLineWidth (int width)
Definition at line 147 of file WaitingSpinnerWidget.cpp.
References width.
setMinimumTrailOpacity()
void WaitingSpinnerWidget::setMinimumTrailOpacity (qreal minimumTrailOpacity)
Definition at line 230 of file WaitingSpinnerWidget.cpp.
References minimumTrailOpacity().
setNumberOfLines()
void WaitingSpinnerWidget::setNumberOfLines (int lines)
Definition at line 134 of file WaitingSpinnerWidget.cpp.
setRevolutionsPerSecond()
void WaitingSpinnerWidget::setRevolutionsPerSecond (qreal revolutionsPerSecond)
Definition at line 219 of file WaitingSpinnerWidget.cpp.
setRoundness()
void WaitingSpinnerWidget::setRoundness (qreal roundness)
Definition at line 209 of file WaitingSpinnerWidget.cpp.
References max(), min(), and roundness().
setTrailFadePercentage()
void WaitingSpinnerWidget::setTrailFadePercentage (qreal trail)
Definition at line 225 of file WaitingSpinnerWidget.cpp.
start
void WaitingSpinnerWidget::start (void) slot
Definition at line 99 of file WaitingSpinnerWidget.cpp.
stop
void WaitingSpinnerWidget::stop () slot
Definition at line 117 of file WaitingSpinnerWidget.cpp.
trailFadePercentage()
qreal WaitingSpinnerWidget::trailFadePercentage ()
Definition at line 174 of file WaitingSpinnerWidget.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/WaitingSpinnerWidget.h
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/WaitingSpinnerWidget.cpp