ACloudViewer: cloudViewer::data::DownloadDataset Class Reference
cloudViewer::data::DownloadDataset Class Reference
Dataset class with one or more downloaded file.
#include <Dataset.h>
Public Member Functions
DownloadDataset (const std::string &prefix, const DataDescriptor &data_descriptor, const std::string &data_root="")
DownloadDataset (const std::string &prefix, const std::vector< DataDescriptor > &data_descriptors, const std::string &data_root="")
virtual ~DownloadDataset ()
Public Member Functions inherited from cloudViewer::data::Dataset
Dataset (const std::string &prefix, const std::string &data_root="")
Parameterized Constructor.
virtual ~Dataset ()
const std::string GetDataRoot () const
Get data root directory. The data root is set at construction time or automatically determined.
const std::string GetPrefix () const
Get prefix for the dataset.
const std::string GetDownloadDir () const
Get absolute path to download directory. i.e. ${data_root}/download/${prefix}.
const std::string GetExtractDir () const
Get absolute path to extract directory. i.e. ${data_root}/extract/${prefix}.
Protected Member Functions
bool HasDownloaded (const DataDescriptor &data_descriptor) const
Check if all files are downloaded and MD5 checksums are valid.
Protected Member Functions inherited from cloudViewer::data::Dataset
void CheckPathsExist (const std::vector< std::string > &paths) const
Check if the paths exists after extraction.
Protected Attributes
std::vector< DataDescriptor > data_descriptors_
Protected Attributes inherited from cloudViewer::data::Dataset
std::string data_root_
CloudViewer data root.
std::string prefix_
Dataset prefix.
Detailed Description
Dataset class with one or more downloaded file.
Parameters
prefix Prefix of the dataset. The data is downloaded in ${data_root}/download/${prefix} and extracted in ${data_root}/extract/${prefix}.
data_descriptor Information about a file to be downloaded.
data_root Path to the dataset root.
Definition at line 152 of file Dataset.h.
Constructor & Destructor Documentation
DownloadDataset() [1/2]
cloudViewer::data::DownloadDataset::DownloadDataset (const std::string & prefix, const DataDescriptor & data_descriptor, const std::string & data_root = "")
Definition at line 83 of file Dataset.cpp.
References cloudViewer::data::data_descriptor.
DownloadDataset() [2/2]
cloudViewer::data::DownloadDataset::DownloadDataset (const std::string & prefix, const std::vector< DataDescriptor > & data_descriptors, const std::string & data_root = "")
Definition at line 90 of file Dataset.cpp.
References cloudViewer::utility::filesystem::Copy(), cloudViewer::data::data_descriptor, cloudViewer::data::data_descriptors, cloudViewer::utility::filesystem::DirectoryExists(), cloudViewer::utility::DownloadFromMirrors(), cloudViewer::utility::Extract(), cloudViewer::data::DataDescriptor::extract_in_subdir_, cloudViewer::data::Dataset::GetDownloadDir(), cloudViewer::data::Dataset::GetExtractDir(), cloudViewer::utility::filesystem::GetFileNameWithoutDirectory(), HasDownloaded(), cloudViewer::utility::IsSupportedCompressedFilePath(), LogError, cloudViewer::utility::filesystem::MakeDirectoryHierarchy(), cloudViewer::data::DataDescriptor::md5_, and cloudViewer::data::DataDescriptor::urls_.
~DownloadDataset()
virtual cloudViewer::data::DownloadDataset::~DownloadDataset () inline virtual
Definition at line 162 of file Dataset.h.
Member Function Documentation
HasDownloaded()
bool cloudViewer::data::DownloadDataset::HasDownloaded (const DataDescriptor & data_descriptor) const protected
Check if all files are downloaded and MD5 checksums are valid.
Definition at line 137 of file Dataset.cpp.
References cloudViewer::data::data_descriptor, cloudViewer::utility::filesystem::DirectoryExists(), cloudViewer::utility::filesystem::FileExists(), cloudViewer::data::Dataset::GetDownloadDir(), cloudViewer::utility::filesystem::GetFileNameWithoutDirectory(), cloudViewer::utility::GetMD5(), cloudViewer::data::DataDescriptor::md5_, and cloudViewer::data::DataDescriptor::urls_.
Referenced by DownloadDataset().
Member Data Documentation
data_descriptors_
std::vector<DataDescriptor> cloudViewer::data::DownloadDataset::data_descriptors_ protected
Definition at line 167 of file Dataset.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/data/Dataset.h
/root/ACloudViewer/libs/cloudViewer/data/Dataset.cpp