ACloudViewer: qCanupoProcess Class Reference
qCanupoProcess Class Reference
CANUPO process (classify)
#include <qCanupoProcess.h>
Classes
struct ClassifyParams
Classify parameters.
Static Public Member Functions
static bool Classify (QString classifierFilename, const ClassifyParams &params, ccPointCloud *cloud, cloudViewer::GenericIndexedCloudPersist *corePoints, CorePointDescSet &corePointsDescriptors, ccPointCloud *realCorePoints=nullptr, ecvMainAppInterface *app=nullptr, QWidget *parentWidget=nullptr, bool silent=false)
Classify a point cloud.
Detailed Description
CANUPO process (classify)
Definition at line 24 of file qCanupoProcess.h.
Member Function Documentation
Classify()
bool qCanupoProcess::Classify (QString classifierFilename, const ClassifyParams & params, ccPointCloud * cloud, cloudViewer::GenericIndexedCloudPersist * corePoints, CorePointDescSet & corePointsDescriptors, ccPointCloud * realCorePoints = nullptr, ecvMainAppInterface * app = nullptr, QWidget * parentWidget = nullptr, bool silent = false) static
Classify a point cloud.
Definition at line 218 of file qCanupoProcess.cpp.
References ccPointCloud::addScalarField(), ecvMainAppInterface::addToDB(), cloudViewer::DgmOctree::build(), CANUPO_PER_LEVEL_ADDITIONAL_SF_NAME, Classifier::class1, Classifier::class2, Classifier::classify(), cloudViewer::ReferenceCloud::clear(), qCanupoTools::ComputeCorePointsDescriptors(), cloudViewer::ScalarField::computeMinAndMax(), ccGenericPointCloud::computeOctree(), computer, corePoints, ccPointCloud::deleteScalarField(), DESC_DIMENSIONALITY, CorePointDescSet::descriptorID(), CorePointDescSet::dimPerScale(), ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, error(), fabs(), cloudViewer::ScalarField::fill(), cloudViewer::DgmOctree::findBestLevelForAGivenNeighbourhoodSizeExtraction(), cloudViewer::DgmOctree::findPointNeighbourhood(), CorePointDescSet::fromByteArray(), ScaleParamsComputer::GetByID(), ccPointCloud::getCurrentDisplayedScalarField(), ccObject::getMetaData(), cloudViewer::ScalarField::getName(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), ccGenericPointCloud::getOctree(), ccGenericPointCloud::getOctreeProxy(), ccHObject::getParent(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), invalidDescriptors, Classifier::Load(), NAN_VALUE, ScaleParamsComputer::needSF(), nProgress, octree, octreeLevel, cloudViewer::NormalizedProgress::oneStep(), params, CorePointDesc::params, processCanceled, RefinePointClassif(), roughnessSFs, s_canupoMSCMetaData, CorePointDescSet::scales(), ccPointCloud::setCurrentDisplayedScalarField(), ecvProgressDialog::setInfo(), ccObject::setMetaData(), ecvProgressDialog::setMethodTitle(), cloudViewer::ScalarField::setValue(), ccDrawableObject::showSF(), cloudViewer::GenericCloud::size(), cloudViewer::PointCloudTpl< T >::size(), ecvProgressDialog::start(), qCanupoTools::TestVectorsOverlap(), CorePointDescSet::toByteArray(), and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by qCanupoPlugin::doClassifyAction(), and CommandCanupoClassif::process().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCanupo/include/qCanupoProcess.h
/root/ACloudViewer/plugins/core/Standard/qCanupo/src/qCanupoProcess.cpp