ACloudViewer: ecvOptions Class Reference
ecvOptions Class Reference
Main application options.
#include <ecvOptions.h>
Public Member Functions
ecvOptions ()
Default constructor.
void reset ()
Resets parameters to default values.
void fromPersistentSettings ()
Loads from persistent DB.
void toPersistentSettings () const
Saves to persistent DB.
Static Public Member Functions
static const ecvOptions & Instance ()
Returns the stored values of each parameter.
static void ReleaseInstance ()
Release unique instance (if any)
static void Set (const ecvOptions &options)
Sets parameters.
Public Attributes
bool normalsDisplayedByDefault
Whether to display the normals by default or not.
bool useNativeDialogs
Use native load/save dialogs.
CVLog::MessageLevelFlags logVerbosityLevel
Log/console verbosity level (reuses CVLog::MessageLevelFlags)
bool askForConfirmationBeforeQuitting
Ask for confirmation before quitting.
Static Protected Member Functions
static ecvOptions & InstanceNonConst ()
Returns the stored values of each parameter.
Detailed Description
Main application options.
Definition at line 19 of file ecvOptions.h.
Constructor & Destructor Documentation
ecvOptions()
ecvOptions::ecvOptions ()
Default constructor.
Definition at line 34 of file ecvOptions.cpp.
References reset().
Referenced by InstanceNonConst().
Member Function Documentation
fromPersistentSettings()
void ecvOptions::fromPersistentSettings ()
Loads from persistent DB.
Definition at line 43 of file ecvOptions.cpp.
References askForConfirmationBeforeQuitting, ecvSettingManager::getValue(), CVLog::LOG_STANDARD, logVerbosityLevel, normalsDisplayedByDefault, and useNativeDialogs.
Instance()
static const ecvOptions& ecvOptions::Instance () inline static
Returns the stored values of each parameter.
Definition at line 48 of file ecvOptions.h.
Referenced by MainWindow::addToDB(), ccDisplayOptionsDlg::ccDisplayOptionsDlg(), and ECVFileDialogOptions().
InstanceNonConst()
ecvOptions & ecvOptions::InstanceNonConst () static protected
Returns the stored values of each parameter.
Definition at line 21 of file ecvOptions.cpp.
References ecvOptions(), and s_options.
Referenced by Set().
ReleaseInstance()
void ecvOptions::ReleaseInstance () static
Release unique instance (if any)
Definition at line 30 of file ecvOptions.cpp.
References s_options.
reset()
void ecvOptions::reset (void)
Resets parameters to default values.
Definition at line 36 of file ecvOptions.cpp.
References askForConfirmationBeforeQuitting, CVLog::LOG_STANDARD, logVerbosityLevel, normalsDisplayedByDefault, and useNativeDialogs.
Referenced by ecvOptions(), and ccDisplayOptionsDlg::reset().
Set()
void ecvOptions::Set (const ecvOptions & options) static
Sets parameters.
Definition at line 32 of file ecvOptions.cpp.
References InstanceNonConst().
Referenced by ccDisplayOptionsDlg::apply(), and ccDisplayOptionsDlg::doReject().
toPersistentSettings()
void ecvOptions::toPersistentSettings () const
Saves to persistent DB.
Definition at line 61 of file ecvOptions.cpp.
References askForConfirmationBeforeQuitting, logVerbosityLevel, normalsDisplayedByDefault, ecvSettingManager::setValue(), and useNativeDialogs.
Referenced by ccDisplayOptionsDlg::doAccept().
Member Data Documentation
askForConfirmationBeforeQuitting
bool ecvOptions::askForConfirmationBeforeQuitting
Ask for confirmation before quitting.
Definition at line 31 of file ecvOptions.h.
Referenced by fromPersistentSettings(), ccDisplayOptionsDlg::refresh(), reset(), and toPersistentSettings().
logVerbosityLevel
CVLog::MessageLevelFlags ecvOptions::logVerbosityLevel
Log/console verbosity level (reuses CVLog::MessageLevelFlags)
Definition at line 28 of file ecvOptions.h.
Referenced by ccDisplayOptionsDlg::apply(), ccDisplayOptionsDlg::changeLogVerbosityLevel(), fromPersistentSettings(), ccDisplayOptionsDlg::refresh(), reset(), and toPersistentSettings().
normalsDisplayedByDefault
bool ecvOptions::normalsDisplayedByDefault
Whether to display the normals by default or not.
Definition at line 22 of file ecvOptions.h.
Referenced by MainWindow::addToDB(), fromPersistentSettings(), ccDisplayOptionsDlg::refresh(), reset(), and toPersistentSettings().
useNativeDialogs
bool ecvOptions::useNativeDialogs
Use native load/save dialogs.
Definition at line 25 of file ecvOptions.h.
Referenced by fromPersistentSettings(), ccDisplayOptionsDlg::refresh(), reset(), and toPersistentSettings().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVAppCommon/include/ecvOptions.h
/root/ACloudViewer/libs/CVAppCommon/src/ecvOptions.cpp