ACloudViewer: cloudViewer::t::io::RealSenseSensor Class Reference
cloudViewer::t::io::RealSenseSensor Class Reference
RealSense camera discovery, configuration, streaming and recording.
#include <RealSenseSensor.h>
Public Member Functions
RealSenseSensor ()
Default constructor. Initialize with default settings.
RealSenseSensor (const RealSenseSensor &)=delete
RealSenseSensor & operator= (const RealSenseSensor &)=delete
virtual ~RealSenseSensor () override
virtual bool InitSensor (const RealSenseSensorConfig &sensor_config=RealSenseSensorConfig{}, size_t sensor_index=0, const std::string &filename="")
virtual bool InitSensor (const RGBDSensorConfig &sensor_config, size_t sensor_index=0, const std::string &filename="") override
virtual bool StartCapture (bool start_record=false) override
virtual void PauseRecord () override
virtual void ResumeRecord () override
virtual geometry::RGBDImage CaptureFrame (bool wait=true, bool align_depth_to_color=true) override
virtual uint64_t GetTimestamp () const override
virtual void StopCapture () override
Stop capturing frames.
virtual const RGBDVideoMetadata & GetMetadata () const override
Get metadata of the RealSense video capture.
virtual std::string GetFilename () const override
Get filename being written.
virtual const std::string ToString () const
Text Description.
Public Member Functions inherited from cloudViewer::t::io::RGBDSensor
RGBDSensor ()
Default constructor. Initialize with default settings.
virtual ~RGBDSensor ()
virtual const std::string ToString () const
Text Description.
Static Public Member Functions
static std::vector< RealSenseValidConfigs > EnumerateDevices ()
static bool ListDevices ()
Detailed Description
RealSense camera discovery, configuration, streaming and recording.
Definition at line 28 of file RealSenseSensor.h.
Constructor & Destructor Documentation
RealSenseSensor() [1/2]
cloudViewer::t::io::RealSenseSensor::RealSenseSensor ()
Default constructor. Initialize with default settings.
Definition at line 116 of file RealSenseSensor.cpp.
References cloudViewer::t::io::RealSenseSensorConfig::ConvertToNativeConfig().
RealSenseSensor() [2/2]
cloudViewer::t::io::RealSenseSensor::RealSenseSensor (const RealSenseSensor &) delete
~RealSenseSensor()
cloudViewer::t::io::RealSenseSensor::~RealSenseSensor () override virtual
Definition at line 123 of file RealSenseSensor.cpp.
References StopCapture().
Member Function Documentation
CaptureFrame()
geometry::RGBDImage cloudViewer::t::io::RealSenseSensor::CaptureFrame (bool wait = true, bool align_depth_to_color = true) override virtual
Acquire the next synchronized RGBD frameset from the camera.
Parameters
wait If true wait for the next frame set, else return immediately with an empty RGBDImage if it is not yet available.
align_depth_to_color Enable aligning WFOV depth image to the color image in visualizer.
Implements cloudViewer::t::io::RGBDSensor.
Definition at line 256 of file RealSenseSensor.cpp.
References cloudViewer::t::geometry::RGBDImage::color_, cloudViewer::t::io::RGBDVideoMetadata::color_dt_, cloudViewer::t::geometry::RGBDImage::depth_, cloudViewer::t::io::RGBDVideoMetadata::depth_dt_, error(), and LogError.
EnumerateDevices()
std::vector< RealSenseValidConfigs > cloudViewer::t::io::RealSenseSensor::EnumerateDevices () static
Query all connected RealSense cameras for their capabilities.
Returns
A list of devices and their supported capabilities.
Definition at line 46 of file RealSenseSensor.cpp.
References context, format, patch::to_string(), and cloudViewer::t::io::RealSenseValidConfigs::valid_configs.
Referenced by ListDevices().
GetFilename()
virtual std::string cloudViewer::t::io::RealSenseSensor::GetFilename () const inline override virtual
Get filename being written.
Implements cloudViewer::t::io::RGBDSensor.
Definition at line 111 of file RealSenseSensor.h.
GetMetadata()
virtual const RGBDVideoMetadata& cloudViewer::t::io::RealSenseSensor::GetMetadata () const inline override virtual
Get metadata of the RealSense video capture.
Implements cloudViewer::t::io::RGBDSensor.
Definition at line 106 of file RealSenseSensor.h.
GetTimestamp()
virtual uint64_t cloudViewer::t::io::RealSenseSensor::GetTimestamp () const inline override virtual
Get current timestamp (in us)
See https://intelrealsense.github.io/librealsense/doxygen/classrs2_1_1frame.html#a25f71d45193f2f4d77960320276b83f1 for more details.
Implements cloudViewer::t::io::RGBDSensor.
Definition at line 100 of file RealSenseSensor.h.
InitSensor() [1/2]
bool cloudViewer::t::io::RealSenseSensor::InitSensor (const RealSenseSensorConfig & sensor_config = RealSenseSensorConfig{}, size_t sensor_index = 0, const std::string & filename = "") virtual
Initialize sensor (optional).
Configure sensor with custom settings. If this is skipped, default settings will be used. You can enable recording to a bag file by specifying a filename.
Parameters
sensor_config Camera configuration, such as resolution and framerate. A serial number can be entered here to connect to a specific camera.
sensor_index Connect to a camera at this position in the enumeration of RealSense cameras that are currently connected. Use EnumerateDevices() or ListDevices() to obtain a list of connected cameras. This is ignored if sensor_config contains a serial entry.
filename Save frames to a bag file
Returns
true if a camera was found and initialized with the given settings, else false.
Definition at line 125 of file RealSenseSensor.cpp.
References cloudViewer::t::io::RealSenseSensorConfig::config_, context, cloudViewer::t::io::RGBDVideoMetadata::ConvertFromJsonValue(), cloudViewer::t::io::RealSenseSensorConfig::ConvertToNativeConfig(), cloudViewer::utility::filesystem::DirectoryExists(), cloudViewer::utility::filesystem::FileExists(), cloudViewer::utility::filesystem::GetFileParentDirectory(), cloudViewer::t::io::RealSenseSensorConfig::GetMetadataJson(), cloudViewer::t::io::RealSenseSensorConfig::GetPixelDtypes(), LogError, cloudViewer::utility::filesystem::MakeDirectoryHierarchy(), and profile.
Referenced by InitSensor().
InitSensor() [2/2]
virtual bool cloudViewer::t::io::RealSenseSensor::InitSensor (const RGBDSensorConfig & sensor_config, size_t sensor_index = 0, const std::string & filename = "") inline override virtual
Initialize sensor (optional).
Configure sensor with custom settings. If this is skipped, default settings will be used. You can enable recording to a file by specifying a filename.
Parameters
sensor_config Camera configuration, such as resolution and framerate. A serial number can be entered here to connect to a specific camera.
sensor_index Connect to a camera at this position in the enumeration of RealSense cameras that are currently connected. Use EnumerateDevices() or ListDevices() to obtain a list of connected cameras and their capabilities. This is ignored if sensor_config contains a "serial" entry.
filename Save frames to this file.
Returns
true if a camera was found and initialized with the given settings, else false.
Implements cloudViewer::t::io::RGBDSensor.
Definition at line 64 of file RealSenseSensor.h.
References InitSensor().
ListDevices()
bool cloudViewer::t::io::RealSenseSensor::ListDevices () static
List all RealSense cameras connected to the system along with their capabilities. Use this listing to select an appropriate configuration for a camera.
Definition at line 24 of file RealSenseSensor.cpp.
References EnumerateDevices(), LogInfo, and LogWarning.
operator=()
RealSenseSensor& cloudViewer::t::io::RealSenseSensor::operator= (const RealSenseSensor &) delete
PauseRecord()
void cloudViewer::t::io::RealSenseSensor::PauseRecord () override virtual
Pause recording to the bag file.
Warning
If this is called immediately after StartCapture(), the bag file may have an incorrect end time.
Implements cloudViewer::t::io::RGBDSensor.
Definition at line 228 of file RealSenseSensor.cpp.
References LogDebug.
ResumeRecord()
void cloudViewer::t::io::RealSenseSensor::ResumeRecord () override virtual
Resume recording to the bag file. The file will contain discontinuous segments.
Implements cloudViewer::t::io::RGBDSensor.
Definition at line 235 of file RealSenseSensor.cpp.
References error(), LogDebug, and LogError.
StartCapture()
bool cloudViewer::t::io::RealSenseSensor::StartCapture (bool start_record = false) override virtual
Start capturing synchronized depth and color frames.
Parameters
start_record start recording to the specified bag file as well.
Implements cloudViewer::t::io::RGBDSensor.
Definition at line 198 of file RealSenseSensor.cpp.
References cloudViewer::t::io::RGBDVideoMetadata::ConvertFromJsonValue(), error(), cloudViewer::t::io::RealSenseSensorConfig::GetMetadataJson(), cloudViewer::t::io::RealSenseSensorConfig::GetPixelDtypes(), LogError, LogInfo, LogWarning, and profile.
StopCapture()
void cloudViewer::t::io::RealSenseSensor::StopCapture () override virtual
Stop capturing frames.
Implements cloudViewer::t::io::RGBDSensor.
Definition at line 289 of file RealSenseSensor.cpp.
References LogInfo.
Referenced by ~RealSenseSensor().
ToString()
virtual const std::string cloudViewer::t::io::RGBDSensor::ToString inline
Text Description.
Definition at line 81 of file RGBDSensor.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/t/io/sensor/realsense/RealSenseSensor.h
/root/ACloudViewer/libs/cloudViewer/t/io/sensor/realsense/RealSenseSensor.cpp