ACloudViewer: cloudViewer::core::Dtype Class Reference
cloudViewer::core::Dtype Class Reference
#include <Dtype.h>
Public Types
enum class DtypeCode {
Undefined , Bool , Int , UInt ,
Float , Object
}
Public Member Functions
Dtype ()
Dtype (DtypeCode dtype_code, int64_t byte_size, const std::string &name)
int64_t ByteSize () const
DtypeCode GetDtypeCode () const
bool IsObject () const
std::string ToString () const
bool operator== (const Dtype &other) const
bool operator!= (const Dtype &other) const
Static Public Member Functions
template<typename T >
static const Dtype FromType ()
template<>
const Dtype FromType ()
template<>
const Dtype FromType ()
template<>
const Dtype FromType ()
template<>
const Dtype FromType ()
template<>
const Dtype FromType ()
template<>
const Dtype FromType ()
template<>
const Dtype FromType ()
template<>
const Dtype FromType ()
template<>
const Dtype FromType ()
template<>
const Dtype FromType ()
template<>
const Dtype FromType ()
Static Public Attributes
static const Dtype Undefined
static const Dtype Float32
static const Dtype Float64
static const Dtype Int8
static const Dtype Int16
static const Dtype Int32
static const Dtype Int64
static const Dtype UInt8
static const Dtype UInt16
static const Dtype UInt32
static const Dtype UInt64
static const Dtype Bool
Detailed Description
Definition at line 21 of file Dtype.h.
Member Enumeration Documentation
DtypeCode
enum cloudViewer::core::Dtype::DtypeCode strong
Enumerator
Undefined
Bool
Int
UInt
Float
Object
Definition at line 37 of file Dtype.h.
Constructor & Destructor Documentation
Dtype() [1/2]
cloudViewer::core::Dtype::Dtype () inline
Definition at line 46 of file Dtype.h.
Dtype() [2/2]
cloudViewer::core::Dtype::Dtype (DtypeCode dtype_code, int64_t byte_size, const std::string & name) explicit
Definition at line 54 of file Dtype.cpp.
References LogError, and name.
Member Function Documentation
ByteSize()
int64_t cloudViewer::core::Dtype::ByteSize () const inline
Definition at line 59 of file Dtype.h.
Referenced by cloudViewer::core::AdvancedIndexer::AdvancedIndexer(), cloudViewer::core::Tensor::AssertTemplateDtype(), cloudViewer::core::HashMap::CheckKeyCompatibility(), cloudViewer::core::HashMap::CheckValueCompatibility(), cloudViewer::core::kernel::CopyCPU(), cloudViewer::core::kernel::CopySYCL(), cloudViewer::core::CreateCPUHashBackend(), cloudViewer::t::io::CreateNumpyHeader(), cloudViewer::t::geometry::ipp::Dilate(), cloudViewer::t::geometry::ipp::Filter(), cloudViewer::t::geometry::ipp::FilterSobel(), cloudViewer::core::HashBackendBuffer::GetKeyDsize(), cloudViewer::core::Tensor::IndexExtract(), cloudViewer::core::kernel::IndexGetCPU(), cloudViewer::core::kernel::IndexGetSYCL(), cloudViewer::core::kernel::IndexSetCPU(), cloudViewer::core::kernel::IndexSetSYCL(), cloudViewer::core::Tensor::ReinterpretCast(), cloudViewer::t::geometry::ipp::Remap(), cloudViewer::t::geometry::PointCloud::RemoveDuplicatedPoints(), cloudViewer::visualization::rendering::FilamentRenderer::RequestReadPixels(), cloudViewer::core::Tensor::Slice(), cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::TArrayIndexer(), cloudViewer::core::Tensor::Tensor(), cloudViewer::core::TensorRef::TensorRef(), cloudViewer::core::eigen_converter::TensorToEigenVectorNxVector(), cloudViewer::core::Tensor::ToString(), and cloudViewer::t::io::WriteNpzOneTensor().
FromType() [1/12]
template<typename T > static const Dtype cloudViewer::core::Dtype::FromType () inline static
Convert from C++ types to Dtype. Known types are explicitly specialized, e.g. FromType<float>(). Unsupported type results in an exception.
Definition at line 55 of file Dtype.h.
References LogError.
FromType() [2/12]
template<> const Dtype cloudViewer::core::Dtype::FromType () inline static
Definition at line 92 of file Dtype.h.
References Float32.
FromType() [3/12]
template<> const Dtype cloudViewer::core::Dtype::FromType () inline static
Definition at line 97 of file Dtype.h.
References Float64.
FromType() [4/12]
template<> const Dtype cloudViewer::core::Dtype::FromType () inline static
Definition at line 102 of file Dtype.h.
References Int8.
FromType() [5/12]
template<> const Dtype cloudViewer::core::Dtype::FromType () inline static
Definition at line 107 of file Dtype.h.
References Int16.
FromType() [6/12]
template<> const Dtype cloudViewer::core::Dtype::FromType () inline static
Definition at line 112 of file Dtype.h.
References Int32.
FromType() [7/12]
template<> const Dtype cloudViewer::core::Dtype::FromType () inline static
Definition at line 117 of file Dtype.h.
References Int64.
FromType() [8/12]
template<> const Dtype cloudViewer::core::Dtype::FromType () inline static
Definition at line 122 of file Dtype.h.
References UInt8.
FromType() [9/12]
template<> const Dtype cloudViewer::core::Dtype::FromType () inline static
Definition at line 127 of file Dtype.h.
References UInt16.
FromType() [10/12]
template<> const Dtype cloudViewer::core::Dtype::FromType () inline static
Definition at line 132 of file Dtype.h.
References UInt32.
FromType() [11/12]
template<> const Dtype cloudViewer::core::Dtype::FromType () inline static
Definition at line 137 of file Dtype.h.
References UInt64.
FromType() [12/12]
template<> const Dtype cloudViewer::core::Dtype::FromType () inline static
Definition at line 142 of file Dtype.h.
References Bool.
GetDtypeCode()
DtypeCode cloudViewer::core::Dtype::GetDtypeCode () const inline
Definition at line 61 of file Dtype.h.
Referenced by cloudViewer::core::HashMap::Init(), cloudViewer::t::geometry::TriangleMesh::SelectByIndex(), and cloudViewer::t::io::NumpyArray::ToTensor().
IsObject()
bool cloudViewer::core::Dtype::IsObject () const inline
Definition at line 63 of file Dtype.h.
Referenced by cloudViewer::core::Tensor::AssertTemplateDtype(), cloudViewer::core::kernel::CopyCPU(), cloudViewer::core::kernel::CopySYCL(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::kernel::IndexGetCPU(), cloudViewer::core::kernel::IndexGetSYCL(), cloudViewer::core::kernel::IndexSetCPU(), cloudViewer::core::kernel::IndexSetSYCL(), cloudViewer::core::Tensor::ScalarPtrToString(), and cloudViewer::core::Tensor::To().
operator!=()
bool cloudViewer::core::Dtype::operator!= (const Dtype & other) const
Definition at line 69 of file Dtype.cpp.
operator==()
bool cloudViewer::core::Dtype::operator== (const Dtype & other) const
Definition at line 64 of file Dtype.cpp.
ToString()
std::string cloudViewer::core::Dtype::ToString () const inline
Definition at line 65 of file Dtype.h.
References name_.
Referenced by cloudViewer::core::AddMM(), cloudViewer::core::AdvancedIndexer::AdvancedIndexer(), cloudViewer::core::Tensor::AssertTemplateDtype(), cloudViewer::core::tensor_check::AssertTensorDtype_(), cloudViewer::core::tensor_check::AssertTensorDtypes_(), cloudViewer::t::geometry::CheckBlockCoordinates(), cloudViewer::t::geometry::CheckDepthTensor(), cloudViewer::t::geometry::CheckExtrinsicTensor(), cloudViewer::t::geometry::CheckIntrinsicTensor(), cloudViewer::t::geometry::TriangleMesh::CreateBox(), cloudViewer::t::geometry::TriangleMesh::CreateText(), cloudViewer::t::io::DtypeToChar(), cloudViewer::t::geometry::vtkutils::DtypeToVtkType(), cloudViewer::core::TensorList::Extend(), cloudViewer::t::geometry::TriangleMesh::FromLegacy(), cloudViewer::t::geometry::AxisAlignedBoundingBox::FromLegacy(), cloudViewer::t::geometry::LineSet::FromLegacy(), cloudViewer::t::geometry::OrientedBoundingBox::FromLegacy(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Indexer::Indexer(), cloudViewer::ml::contrib::KnnSearch(), cloudViewer::core::Matmul(), cloudViewer::t::geometry::AxisAlignedBoundingBox::operator+=(), cloudViewer::ml::contrib::RadiusSearch(), cloudViewer::core::Tensor::ReinterpretCast(), cloudViewer::t::geometry::ipp::Remap(), cloudViewer::t::geometry::TriangleMesh::SelectByIndex(), cloudViewer::io::rpc::SetMeshData(), cloudViewer::t::io::DepthNoiseSimulator::Simulate(), cloudViewer::core::Tensor::To(), cloudViewer::t::geometry::PointCloud::ToLegacy(), cloudViewer::t::geometry::RGBDImage::ToString(), cloudViewer::t::geometry::TensorMap::ToString(), cloudViewer::core::Tensor::ToString(), and cloudViewer::core::kernel::UnaryEW().
Member Data Documentation
Bool
const Dtype cloudViewer::core::Dtype::Bool static
Definition at line 34 of file Dtype.h.
Referenced by FromType(), cloudViewer::t::geometry::VoxelBlockGrid::RayCast(), and cloudViewer::t::geometry::PointCloud::SelectByMask().
Float32
const Dtype cloudViewer::core::Dtype::Float32 static
Definition at line 24 of file Dtype.h.
Referenced by cloudViewer::t::geometry::kernel::voxel_grid::ExtractPointCloud(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractTriangleMesh(), FromType(), cloudViewer::t::io::GetDtypeFromPCDHeaderField(), cloudViewer::t::geometry::kernel::voxel_grid::Integrate(), cloudViewer::t::geometry::PointCloud::ProjectToRGBDImage(), cloudViewer::t::geometry::VoxelBlockGrid::RayCast(), cloudViewer::t::geometry::kernel::voxel_grid::RayCast(), cloudViewer::t::io::ReadTriangleMeshUsingASSIMP(), and cloudViewer::t::io::WriteTriangleMeshUsingASSIMP().
Float64
const Dtype cloudViewer::core::Dtype::Float64 static
Definition at line 25 of file Dtype.h.
Referenced by cloudViewer::t::geometry::CheckExtrinsicTensor(), cloudViewer::t::geometry::CheckIntrinsicTensor(), cloudViewer::t::pipelines::kernel::ComputePoseColoredICP(), cloudViewer::t::pipelines::kernel::ComputePoseDopplerICP(), FromType(), cloudViewer::t::io::GetDtypeFromPCDHeaderField(), and cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU().
Int16
const Dtype cloudViewer::core::Dtype::Int16 static
Definition at line 27 of file Dtype.h.
Referenced by FromType(), and cloudViewer::t::io::GetDtypeFromPCDHeaderField().
Int32
const Dtype cloudViewer::core::Dtype::Int32 static
Definition at line 28 of file Dtype.h.
Referenced by cloudViewer::t::geometry::CheckBlockCoordinates(), FromType(), cloudViewer::t::io::GetDtypeFromPCDHeaderField(), and cloudViewer::core::HashBackendBuffer::HashBackendBuffer().
Int64
const Dtype cloudViewer::core::Dtype::Int64 static
Definition at line 29 of file Dtype.h.
Referenced by cloudViewer::t::pipelines::registration::CorrespondencesFromFeatures(), FromType(), cloudViewer::t::io::GetDtypeFromPCDHeaderField(), cloudViewer::t::geometry::VoxelBlockGrid::GetVoxelIndices(), cloudViewer::t::geometry::VoxelBlockGrid::RayCast(), and cloudViewer::t::io::ReadTriangleMeshUsingASSIMP().
Int8
const Dtype cloudViewer::core::Dtype::Int8 static
Definition at line 26 of file Dtype.h.
Referenced by FromType(), and cloudViewer::t::io::GetDtypeFromPCDHeaderField().
UInt16
const Dtype cloudViewer::core::Dtype::UInt16 static
Definition at line 31 of file Dtype.h.
Referenced by FromType(), and cloudViewer::t::io::GetDtypeFromPCDHeaderField().
UInt32
const Dtype cloudViewer::core::Dtype::UInt32 static
Definition at line 32 of file Dtype.h.
Referenced by FromType(), cloudViewer::t::io::GetDtypeFromPCDHeaderField(), and cloudViewer::t::io::WriteTriangleMeshUsingASSIMP().
UInt64
const Dtype cloudViewer::core::Dtype::UInt64 static
Definition at line 33 of file Dtype.h.
Referenced by FromType(), and cloudViewer::t::io::GetDtypeFromPCDHeaderField().
UInt8
const Dtype cloudViewer::core::Dtype::UInt8 static
Definition at line 30 of file Dtype.h.
Referenced by FromType(), cloudViewer::t::io::GetDtypeFromPCDHeaderField(), cloudViewer::t::geometry::kernel::voxel_grid::Integrate(), cloudViewer::t::geometry::PointCloud::ProjectToRGBDImage(), cloudViewer::t::geometry::VoxelBlockGrid::Save(), and cloudViewer::t::io::WriteTriangleMeshUsingASSIMP().
Undefined
const Dtype cloudViewer::core::Dtype::Undefined static
Definition at line 23 of file Dtype.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/core/Dtype.h
/root/ACloudViewer/libs/cloudViewer/core/Dtype.cpp