ACloudViewer: colmap::SiftGPUFeatureMatcher Class Reference
colmap::SiftGPUFeatureMatcher Class Reference
#include <matching.h>
Public Types
typedef internal::FeatureMatcherData Input
typedef internal::FeatureMatcherData Output
Public Types inherited from colmap::Thread
enum { STARTED_CALLBACK = INT_MIN , FINISHED_CALLBACK }
Public Member Functions
SiftGPUFeatureMatcher (const SiftMatchingOptions &options, FeatureMatcherCache *cache, JobQueue< Input > *input_queue, JobQueue< Output > *output_queue)
Public Member Functions inherited from colmap::FeatureMatcherThread
FeatureMatcherThread (const SiftMatchingOptions &options, FeatureMatcherCache *cache)
void SetMaxNumMatches (const int max_num_matches)
Public Member Functions inherited from colmap::Thread
Thread ()
virtual ~Thread ()=default
virtual void Start ()
virtual void Stop ()
virtual void Pause ()
virtual void Resume ()
virtual void Wait ()
bool IsStarted ()
bool IsStopped ()
bool IsPaused ()
bool IsRunning ()
bool IsFinished ()
void BlockIfPaused ()
bool CheckValidSetup ()
void AddCallback (const int id, const std::function< void()> &func)
const Timer & GetTimer () const
Protected Member Functions
void Run () override
void GetDescriptorData (const int index, const image_t image_id, const FeatureDescriptors **descriptors_ptr)
Protected Member Functions inherited from colmap::Thread
void RegisterCallback (const int id)
void Callback (const int id) const
std::thread::id GetThreadId () const
void SignalValidSetup ()
void SignalInvalidSetup ()
Protected Attributes
JobQueue< Input > * input_queue_
JobQueue< Output > * output_queue_
std::unique_ptr< OpenGLContextManager > opengl_context_
std::array< image_t, 2 > prev_uploaded_image_ids_
std::array< FeatureDescriptors, 2 > prev_uploaded_descriptors_
Protected Attributes inherited from colmap::FeatureMatcherThread
SiftMatchingOptions options_
FeatureMatcherCache * cache_
Detailed Description
Definition at line 235 of file matching.h.
Member Typedef Documentation
Input
typedef internal::FeatureMatcherData colmap::SiftGPUFeatureMatcher::Input
Definition at line 237 of file matching.h.
Output
typedef internal::FeatureMatcherData colmap::SiftGPUFeatureMatcher::Output
Definition at line 238 of file matching.h.
Constructor & Destructor Documentation
SiftGPUFeatureMatcher()
colmap::SiftGPUFeatureMatcher::SiftGPUFeatureMatcher (const SiftMatchingOptions & options, FeatureMatcherCache * cache, JobQueue< Input > * input_queue, JobQueue< Output > * output_queue)
Definition at line 411 of file matching.cc.
References colmap::SiftMatchingOptions::Check(), colmap::kInvalidImageId, opengl_context_, colmap::FeatureMatcherThread::options_, and prev_uploaded_image_ids_.
Member Function Documentation
GetDescriptorData()
void colmap::SiftGPUFeatureMatcher::GetDescriptorData (const int index, const image_t image_id, const FeatureDescriptors ** descriptors_ptr) protected
Definition at line 488 of file matching.cc.
References colmap::FeatureMatcherThread::cache_, colmap::FeatureMatcherCache::GetDescriptors(), prev_uploaded_descriptors_, and prev_uploaded_image_ids_.
Referenced by Run().
Run()
void colmap::SiftGPUFeatureMatcher::Run () override protected virtual
Implements colmap::Thread.
Definition at line 428 of file matching.cc.
References colmap::FeatureMatcherThread::cache_, colmap::CreateSiftGPUMatcher(), data, e, QtCompat::endl(), colmap::FeatureMatcherCache::ExistsDescriptors(), GetDescriptorData(), input_queue_, colmap::Thread::IsStopped(), colmap::MatchSiftFeaturesGPU(), colmap::SiftMatchingOptions::max_num_matches, opengl_context_, colmap::FeatureMatcherThread::options_, output_queue_, colmap::Thread::SignalInvalidSetup(), and colmap::Thread::SignalValidSetup().
Member Data Documentation
input_queue_
JobQueue<Input>* colmap::SiftGPUFeatureMatcher::input_queue_ protected
Definition at line 252 of file matching.h.
Referenced by Run().
opengl_context_
std::unique_ptr<OpenGLContextManager> colmap::SiftGPUFeatureMatcher::opengl_context_ protected
Definition at line 255 of file matching.h.
Referenced by Run(), and SiftGPUFeatureMatcher().
output_queue_
JobQueue<Output>* colmap::SiftGPUFeatureMatcher::output_queue_ protected
Definition at line 253 of file matching.h.
Referenced by Run().
prev_uploaded_descriptors_
std::array<FeatureDescriptors, 2> colmap::SiftGPUFeatureMatcher::prev_uploaded_descriptors_ protected
Definition at line 259 of file matching.h.
Referenced by GetDescriptorData().
prev_uploaded_image_ids_
std::array<image_t, 2> colmap::SiftGPUFeatureMatcher::prev_uploaded_image_ids_ protected
Definition at line 258 of file matching.h.
Referenced by GetDescriptorData(), and SiftGPUFeatureMatcher().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/feature/matching.h
/root/ACloudViewer/libs/Reconstruction/src/feature/matching.cc