ACloudViewer: cloudViewer::t::io::RealSenseSensorConfig Class Reference
cloudViewer::t::io::RealSenseSensorConfig Class Reference
#include <RealSenseSensorConfig.h>
Public Member Functions
RealSenseSensorConfig ()
Default constructor, default configs will be used.
RealSenseSensorConfig (const std::unordered_map< std::string, std::string > &config)
Initialize config with a map.
bool ConvertToJsonValue (Json::Value &value) const override
bool ConvertFromJsonValue (const Json::Value &value) override
rs2::config ConvertToNativeConfig () const
Convert to RealSense config.
Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
virtual ~IJsonConvertible ()
virtual std::string ToString () const
Convert to a styled string representation of JSON data for display.
Static Public Member Functions
static Json::Value GetMetadataJson (const rs2::pipeline_profile &profile)
Get metadata for a streaming RealSense camera or bag file.
static void GetPixelDtypes (const rs2::pipeline_profile &profile, RGBDVideoMetadata &metadata)
static std::pair< core::Dtype, uint8_t > get_dtype_channels (int rs2_format_enum)
Static Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
static bool EigenVector3dFromJsonArray (Eigen::Vector3d &vec, const Json::Value &value)
static bool EigenVector3dToJsonArray (const Eigen::Vector3d &vec, Json::Value &value)
static bool EigenVector4dFromJsonArray (Eigen::Vector4d &vec, const Json::Value &value)
static bool EigenVector4dToJsonArray (const Eigen::Vector4d &vec, Json::Value &value)
static bool EigenMatrix3dFromJsonArray (Eigen::Matrix3d &mat, const Json::Value &value)
static bool EigenMatrix3dToJsonArray (const Eigen::Matrix3d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d_u &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d_u &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d_u &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d_u &mat, Json::Value &value)
Public Attributes
std::unordered_map< std::string, std::string > config_
Detailed Description
Configuration for a RealSense camera
See RealSense documentation for the set of configuration values. Supported configuration options will be specific to a device and other chosen options. https://intelrealsense.github.io/librealsense/doxygen/rs__option_8h.html https://intelrealsense.github.io/librealsense/doxygen/rs__sensor_8h.html
{
// Pick a specific device, leave empty to pick the first available
// device
   {"serial": ""},
// pixel format for color frames
   {"color_format": "RS2_FORMAT_ANY"},
// (width, height): Leave 0 to let RealSense pick a supported width or
// height
   {"color_resolution": "0,0"},
// pixel format for depth frames
   {"depth_format": "RS2_FORMAT_ANY"},
// (width, height): Leave 0 to let RealSense pick a supported width or
// height
   {"depth_resolution": "0,0"},
// framerate for both color and depth streams. Leave 0 to let RealSense
// pick a supported framerate
   {"fps": "0"},
// Controls depth computation on the device. Supported values are
// specific to device family (SR300, RS400, L500). Leave empty to pick
// the default.
   {"visual_preset": ""}
}
Definition at line 63 of file RealSenseSensorConfig.h.
Constructor & Destructor Documentation
RealSenseSensorConfig() [1/2]
cloudViewer::t::io::RealSenseSensorConfig::RealSenseSensorConfig ()
Default constructor, default configs will be used.
Definition at line 143 of file RealSenseSensorConfig.cpp.
References config_, and cloudViewer::t::io::standard_config.
RealSenseSensorConfig() [2/2]
cloudViewer::t::io::RealSenseSensorConfig::RealSenseSensorConfig (const std::unordered_map< std::string, std::string > & config)
Initialize config with a map.
Definition at line 145 of file RealSenseSensorConfig.cpp.
References config_.
Member Function Documentation
ConvertFromJsonValue()
bool cloudViewer::t::io::RealSenseSensorConfig::ConvertFromJsonValue (const Json::Value & value) override virtual
Implements cloudViewer::utility::IJsonConvertible.
Definition at line 160 of file RealSenseSensorConfig.cpp.
References config_.
ConvertToJsonValue()
bool cloudViewer::t::io::RealSenseSensorConfig::ConvertToJsonValue (Json::Value & value) const override virtual
Implements cloudViewer::utility::IJsonConvertible.
Definition at line 153 of file RealSenseSensorConfig.cpp.
References config_.
ConvertToNativeConfig()
rs2::config cloudViewer::t::io::RealSenseSensorConfig::ConvertToNativeConfig () const
Convert to RealSense config.
Definition at line 167 of file RealSenseSensorConfig.cpp.
References config_, format, height, and width.
Referenced by cloudViewer::t::io::RealSenseSensor::InitSensor(), and cloudViewer::t::io::RealSenseSensor::RealSenseSensor().
get_dtype_channels()
std::pair< core::Dtype, uint8_t > cloudViewer::t::io::RealSenseSensorConfig::get_dtype_channels (int rs2_format_enum) static
Convert rs2_format enum to CloudViewer Dtype and number of channels
Parameters
rs2_format_enum An int is accepted instead of rs2_format enum to prevent dependence on the realsense headers.
Definition at line 117 of file RealSenseSensorConfig.cpp.
References cloudViewer::core::make_pair(), cloudViewer::core::UInt16, and cloudViewer::core::UInt8.
Referenced by GetPixelDtypes().
GetMetadataJson()
Json::Value cloudViewer::t::io::RealSenseSensorConfig::GetMetadataJson (const rs2::pipeline_profile & profile) static
Get metadata for a streaming RealSense camera or bag file.
Definition at line 224 of file RealSenseSensorConfig.cpp.
References cloudViewer::camera::PinholeCameraIntrinsic::ConvertToJsonValue(), LogError, profile, and cloudViewer::camera::PinholeCameraIntrinsic::SetIntrinsics().
Referenced by cloudViewer::t::io::RealSenseSensor::InitSensor(), cloudViewer::t::io::RSBagReader::Open(), and cloudViewer::t::io::RealSenseSensor::StartCapture().
GetPixelDtypes()
void cloudViewer::t::io::RealSenseSensorConfig::GetPixelDtypes (const rs2::pipeline_profile & profile, RGBDVideoMetadata & metadata) static
Get pixel data types for color and depth streams. These will be set in metadata.color_dt_, metadata.color_channels_ and metadata.depth_dt_
Definition at line 204 of file RealSenseSensorConfig.cpp.
References cloudViewer::t::io::RGBDVideoMetadata::color_channels_, cloudViewer::t::io::RGBDVideoMetadata::color_dt_, cloudViewer::t::io::RGBDVideoMetadata::depth_dt_, get_dtype_channels(), LogError, profile, cloudViewer::core::UInt16, and cloudViewer::core::UInt8.
Referenced by cloudViewer::t::io::RealSenseSensor::InitSensor(), cloudViewer::t::io::RSBagReader::Open(), and cloudViewer::t::io::RealSenseSensor::StartCapture().
Member Data Documentation
config_
std::unordered_map<std::string, std::string> cloudViewer::t::io::RealSenseSensorConfig::config_
Definition at line 93 of file RealSenseSensorConfig.h.
Referenced by ConvertFromJsonValue(), ConvertToJsonValue(), ConvertToNativeConfig(), cloudViewer::t::io::RealSenseSensor::InitSensor(), and RealSenseSensorConfig().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/t/io/sensor/realsense/RealSenseSensorConfig.h
/root/ACloudViewer/libs/cloudViewer/t/io/sensor/realsense/RealSenseSensorConfig.cpp