ACloudViewer: colmap::IncrementalMapper Class Reference
colmap::IncrementalMapper Class Reference
#include <incremental_mapper.h>
Classes
struct LocalBundleAdjustmentReport
struct Options
Public Member Functions
IncrementalMapper (const DatabaseCache *database_cache)
void BeginReconstruction (Reconstruction *reconstruction)
void EndReconstruction (const bool discard)
bool FindInitialImagePair (const Options &options, image_t *image_id1, image_t *image_id2)
std::vector< image_t > FindNextImages (const Options &options)
bool RegisterInitialImagePair (const Options &options, const image_t image_id1, const image_t image_id2)
bool RegisterNextImage (const Options &options, const image_t image_id)
size_t TriangulateImage (const IncrementalTriangulator::Options &tri_options, const image_t image_id)
size_t Retriangulate (const IncrementalTriangulator::Options &tri_options)
size_t CompleteTracks (const IncrementalTriangulator::Options &tri_options)
size_t MergeTracks (const IncrementalTriangulator::Options &tri_options)
LocalBundleAdjustmentReport AdjustLocalBundle (const Options &options, const BundleAdjustmentOptions &ba_options, const IncrementalTriangulator::Options &tri_options, const image_t image_id, const std::unordered_set< point3D_t > &point3D_ids)
bool AdjustGlobalBundle (const Options &options, const BundleAdjustmentOptions &ba_options)
size_t FilterImages (const Options &options)
size_t FilterPoints (const Options &options)
const Reconstruction & GetReconstruction () const
size_t NumTotalRegImages () const
size_t NumSharedRegImages () const
const std::unordered_set< point3D_t > & GetModifiedPoints3D ()
void ClearModifiedPoints3D ()
Detailed Description
Definition at line 39 of file incremental_mapper.h.
Constructor & Destructor Documentation
IncrementalMapper()
colmap::IncrementalMapper::IncrementalMapper (const DatabaseCache * database_cache) explicit
Definition at line 99 of file incremental_mapper.cc.
Member Function Documentation
AdjustGlobalBundle()
bool colmap::IncrementalMapper::AdjustGlobalBundle (const Options & options, const BundleAdjustmentOptions & ba_options)
Definition at line 689 of file incremental_mapper.cc.
References colmap::BundleAdjustmentConfig::AddImage(), colmap::Reconstruction::FilterObservationsWithNegativeDepth(), colmap::IncrementalMapper::Options::fix_existing_images, colmap::Reconstruction::Normalize(), colmap::Reconstruction::RegImageIds(), colmap::BundleAdjustmentConfig::SetConstantPose(), colmap::BundleAdjustmentConfig::SetConstantTvec(), and colmap::BundleAdjuster::Solve().
AdjustLocalBundle()
IncrementalMapper::LocalBundleAdjustmentReport colmap::IncrementalMapper::AdjustLocalBundle (const Options & options, const BundleAdjustmentOptions & ba_options, const IncrementalTriangulator::Options & tri_options, const image_t image_id, const std::unordered_set< point3D_t > & point3D_ids)
Definition at line 569 of file incremental_mapper.cc.
References colmap::BundleAdjustmentConfig::AddImage(), colmap::BundleAdjustmentConfig::AddVariablePoint(), colmap::IncrementalMapper::Options::Check(), colmap::IncrementalMapper::Options::filter_max_reproj_error, colmap::IncrementalMapper::Options::filter_min_tri_angle, colmap::Reconstruction::FilterPoints3D(), colmap::Reconstruction::FilterPoints3DInImages(), colmap::IncrementalMapper::Options::fix_existing_images, colmap::Point3D::HasError(), image, colmap::Reconstruction::Image(), colmap::BundleAdjustmentConfig::Images(), colmap::Track::Length(), colmap::IncrementalMapper::LocalBundleAdjustmentReport::num_adjusted_observations, colmap::IncrementalMapper::LocalBundleAdjustmentReport::num_completed_observations, colmap::IncrementalMapper::LocalBundleAdjustmentReport::num_filtered_observations, colmap::IncrementalMapper::LocalBundleAdjustmentReport::num_merged_observations, colmap::Reconstruction::Point3D(), colmap::BundleAdjustmentConfig::SetConstantCamera(), colmap::BundleAdjustmentConfig::SetConstantPose(), colmap::BundleAdjustmentConfig::SetConstantTvec(), colmap::BundleAdjuster::Solve(), colmap::BundleAdjuster::Summary(), and colmap::Point3D::Track().
BeginReconstruction()
void colmap::IncrementalMapper::BeginReconstruction (Reconstruction * reconstruction)
Definition at line 107 of file incremental_mapper.cc.
References colmap::DatabaseCache::CorrespondenceGraph(), colmap::kInvalidImagePairId, colmap::Reconstruction::Load(), colmap::Reconstruction::RegImageIds(), and colmap::Reconstruction::SetUp().
Referenced by colmap::RunImageRegistrator(), and colmap::RunPointTriangulator().
ClearModifiedPoints3D()
void colmap::IncrementalMapper::ClearModifiedPoints3D ()
Definition at line 821 of file incremental_mapper.cc.
CompleteTracks()
size_t colmap::IncrementalMapper::CompleteTracks (const IncrementalTriangulator::Options & tri_options)
Definition at line 556 of file incremental_mapper.cc.
Referenced by colmap::CompleteAndMergeTracks().
EndReconstruction()
void colmap::IncrementalMapper::EndReconstruction (const bool discard)
Definition at line 132 of file incremental_mapper.cc.
References colmap::Reconstruction::RegImageIds(), and colmap::Reconstruction::TearDown().
Referenced by colmap::RunImageRegistrator(), and colmap::RunPointTriangulator().
FilterImages()
size_t colmap::IncrementalMapper::FilterImages (const Options & options)
Definition at line 773 of file incremental_mapper.cc.
References colmap::IncrementalMapper::Options::Check(), colmap::Reconstruction::FilterImages(), colmap::IncrementalMapper::Options::max_extra_param, colmap::IncrementalMapper::Options::max_focal_length_ratio, colmap::IncrementalMapper::Options::min_focal_length_ratio, and colmap::Reconstruction::NumRegImages().
Referenced by colmap::FilterImages().
FilterPoints()
size_t colmap::IncrementalMapper::FilterPoints (const Options & options)
Definition at line 797 of file incremental_mapper.cc.
References colmap::IncrementalMapper::Options::Check(), colmap::IncrementalMapper::Options::filter_max_reproj_error, colmap::IncrementalMapper::Options::filter_min_tri_angle, and colmap::Reconstruction::FilterAllPoints3D().
Referenced by colmap::FilterPoints().
FindInitialImagePair()
bool colmap::IncrementalMapper::FindInitialImagePair (const Options & options, image_t * image_id1, image_t * image_id2)
Definition at line 146 of file incremental_mapper.cc.
References colmap::IncrementalMapper::Options::Check(), colmap::DatabaseCache::ExistsImage(), colmap::Database::ImagePairToPairId(), and colmap::kInvalidImageId.
FindNextImages()
std::vector< image_t > colmap::IncrementalMapper::FindNextImages (const Options & options)
Definition at line 203 of file incremental_mapper.cc.
References colmap::IncrementalMapper::Options::abs_pose_min_num_inliers, colmap::IncrementalMapper::Options::Check(), float, image, colmap::IncrementalMapper::Options::image_selection_method, colmap::Reconstruction::Images(), colmap::IncrementalMapper::Options::max_reg_trials, colmap::IncrementalMapper::Options::MAX_VISIBLE_POINTS_NUM, colmap::IncrementalMapper::Options::MAX_VISIBLE_POINTS_RATIO, and colmap::IncrementalMapper::Options::MIN_UNCERTAINTY.
GetModifiedPoints3D()
const std::unordered_set< point3D_t > & colmap::IncrementalMapper::GetModifiedPoints3D ()
Definition at line 817 of file incremental_mapper.cc.
GetReconstruction()
const Reconstruction & colmap::IncrementalMapper::GetReconstruction () const
Definition at line 804 of file incremental_mapper.cc.
MergeTracks()
size_t colmap::IncrementalMapper::MergeTracks (const IncrementalTriangulator::Options & tri_options)
Definition at line 562 of file incremental_mapper.cc.
Referenced by colmap::CompleteAndMergeTracks().
NumSharedRegImages()
size_t colmap::IncrementalMapper::NumSharedRegImages () const
Definition at line 813 of file incremental_mapper.cc.
NumTotalRegImages()
size_t colmap::IncrementalMapper::NumTotalRegImages () const
Definition at line 809 of file incremental_mapper.cc.
RegisterInitialImagePair()
bool colmap::IncrementalMapper::RegisterInitialImagePair (const Options & options, const image_t image_id1, const image_t image_id2)
Definition at line 259 of file incremental_mapper.cc.
References colmap::Track::AddElement(), colmap::Reconstruction::AddPoint3D(), colmap::CalculateTriangulationAngle(), colmap::Reconstruction::Camera(), colmap::Image::CameraId(), colmap::IncrementalMapper::Options::Check(), colmap::ComposeIdentityQuaternion(), colmap::DatabaseCache::CorrespondenceGraph(), colmap::DegToRad(), colmap::Track::Element(), colmap::CorrespondenceGraph::FindCorrespondencesBetweenImages(), colmap::HasPointPositiveDepth(), colmap::Reconstruction::Image(), colmap::TrackElement::image_id, colmap::Database::ImagePairToPairId(), colmap::Camera::ImageToWorld(), colmap::IncrementalMapper::Options::init_min_tri_angle, colmap::Reconstruction::NumRegImages(), colmap::Image::Point2D(), colmap::TrackElement::point2D_idx, colmap::Image::ProjectionCenter(), colmap::Image::ProjectionMatrix(), colmap::Image::Qvec(), colmap::TwoViewGeometry::qvec, colmap::Reconstruction::RegisterImage(), colmap::Track::Reserve(), colmap::TriangulatePoint(), colmap::Image::Tvec(), colmap::TwoViewGeometry::tvec, and colmap::Point2D::XY().
RegisterNextImage()
bool colmap::IncrementalMapper::RegisterNextImage (const Options & options, const image_t image_id)
Definition at line 345 of file incremental_mapper.cc.
References colmap::IncrementalMapper::Options::abs_pose_max_error, colmap::IncrementalMapper::Options::abs_pose_min_inlier_ratio, colmap::IncrementalMapper::Options::abs_pose_min_num_inliers, colmap::IncrementalMapper::Options::abs_pose_refine_extra_params, colmap::IncrementalMapper::Options::abs_pose_refine_focal_length, colmap::Reconstruction::AddObservation(), colmap::DatabaseCache::Camera(), colmap::Reconstruction::Camera(), colmap::Image::CameraId(), colmap::IncrementalMapper::Options::Check(), colmap::RANSACOptions::confidence, colmap::DatabaseCache::CorrespondenceGraph(), QtCompat::endl(), colmap::AbsolutePoseEstimationOptions::estimate_focal_length, colmap::EstimateAbsolutePose(), colmap::Reconstruction::ExistsImage(), colmap::CorrespondenceGraph::FindTransitiveCorrespondences(), colmap::Camera::HasBogusParams(), colmap::Point2D::HasPoint3D(), colmap::Camera::HasPriorFocalLength(), image, colmap::Reconstruction::Image(), colmap::Image::IsRegistered(), colmap::RANSACOptions::max_error, colmap::IncrementalMapper::Options::max_extra_param, colmap::AbsolutePoseEstimationOptions::max_focal_length_ratio, colmap::IncrementalMapper::Options::max_focal_length_ratio, colmap::RANSACOptions::max_num_trials, colmap::AbsolutePoseEstimationOptions::min_focal_length_ratio, colmap::IncrementalMapper::Options::min_focal_length_ratio, colmap::RANSACOptions::min_inlier_ratio, colmap::RANSACOptions::min_num_trials, colmap::AbsolutePoseEstimationOptions::num_focal_length_samples, colmap::AbsolutePoseEstimationOptions::num_threads, colmap::IncrementalMapper::Options::num_threads, colmap::Reconstruction::NumRegImages(), colmap::Camera::Params(), colmap::Image::Point2D(), colmap::Reconstruction::Point3D(), colmap::Point2D::Point3DId(), colmap::AbsolutePoseEstimationOptions::ransac_options, colmap::AbsolutePoseRefinementOptions::refine_extra_params, colmap::AbsolutePoseRefinementOptions::refine_focal_length, colmap::RefineAbsolutePose(), colmap::Reconstruction::RegisterImage(), colmap::Camera::SetParams(), colmap::Point2D::XY(), and colmap::Point3D::XYZ().
Referenced by colmap::RunImageRegistrator().
Retriangulate()
size_t colmap::IncrementalMapper::Retriangulate (const IncrementalTriangulator::Options & tri_options)
Definition at line 550 of file incremental_mapper.cc.
TriangulateImage()
size_t colmap::IncrementalMapper::TriangulateImage (const IncrementalTriangulator::Options & tri_options, const image_t image_id)
Definition at line 543 of file incremental_mapper.cc.
Referenced by colmap::RunPointTriangulator().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/sfm/incremental_mapper.h
/root/ACloudViewer/libs/Reconstruction/src/sfm/incremental_mapper.cc