ACloudViewer: Test_CreationClass Class Reference
Test_CreationClass Class Reference
#include <test_creationclass.h>
Public Member Functions
Test_CreationClass ()
virtual void addLayer (const DL_LayerData &data)
virtual void addPoint (const DL_PointData &data)
virtual void addLine (const DL_LineData &data)
virtual void addArc (const DL_ArcData &data)
virtual void addCircle (const DL_CircleData &data)
virtual void addPolyline (const DL_PolylineData &data)
virtual void addVertex (const DL_VertexData &data)
virtual void add3dFace (const DL_3dFaceData &data)
void printAttributes ()
Public Member Functions inherited from DL_CreationAdapter
DL_CreationAdapter ()
virtual ~DL_CreationAdapter ()
virtual void processCodeValuePair (unsigned int, const std::string &)
virtual void endSection ()
virtual void addLinetype (const DL_LinetypeData &)
virtual void addLinetypeDash (double)
virtual void addBlock (const DL_BlockData &)
virtual void endBlock ()
virtual void addTextStyle (const DL_StyleData &)
virtual void addXLine (const DL_XLineData &)
virtual void addRay (const DL_RayData &)
virtual void addEllipse (const DL_EllipseData &)
virtual void addSpline (const DL_SplineData &)
virtual void addControlPoint (const DL_ControlPointData &)
virtual void addFitPoint (const DL_FitPointData &)
virtual void addKnot (const DL_KnotData &)
virtual void addInsert (const DL_InsertData &)
virtual void addMText (const DL_MTextData &)
virtual void addMTextChunk (const std::string &)
virtual void addText (const DL_TextData &)
virtual void addArcAlignedText (const DL_ArcAlignedTextData &)
virtual void addAttribute (const DL_AttributeData &)
virtual void addDimAlign (const DL_DimensionData &, const DL_DimAlignedData &)
virtual void addDimLinear (const DL_DimensionData &, const DL_DimLinearData &)
virtual void addDimRadial (const DL_DimensionData &, const DL_DimRadialData &)
virtual void addDimDiametric (const DL_DimensionData &, const DL_DimDiametricData &)
virtual void addDimAngular (const DL_DimensionData &, const DL_DimAngularData &)
virtual void addDimAngular3P (const DL_DimensionData &, const DL_DimAngular3PData &)
virtual void addDimOrdinate (const DL_DimensionData &, const DL_DimOrdinateData &)
virtual void addLeader (const DL_LeaderData &)
virtual void addLeaderVertex (const DL_LeaderVertexData &)
virtual void addHatch (const DL_HatchData &)
virtual void addTrace (const DL_TraceData &)
virtual void addSolid (const DL_SolidData &)
virtual void addImage (const DL_ImageData &)
virtual void linkImage (const DL_ImageDefData &)
virtual void addHatchLoop (const DL_HatchLoopData &)
virtual void addHatchEdge (const DL_HatchEdgeData &)
virtual void addXRecord (const std::string &)
virtual void addXRecordString (int, const std::string &)
virtual void addXRecordReal (int, double)
virtual void addXRecordInt (int, int)
virtual void addXRecordBool (int, bool)
virtual void addXDataApp (const std::string &)
virtual void addXDataString (int, const std::string &)
virtual void addXDataReal (int, double)
virtual void addXDataInt (int, int)
virtual void addDictionary (const DL_DictionaryData &)
virtual void addDictionaryEntry (const DL_DictionaryEntryData &)
virtual void endEntity ()
virtual void addComment (const std::string &)
virtual void setVariableVector (const std::string &, double, double, double, int)
virtual void setVariableString (const std::string &, const std::string &, int)
virtual void setVariableInt (const std::string &, int, int)
virtual void setVariableDouble (const std::string &, double, int)
virtual void endSequence ()
Public Member Functions inherited from DL_CreationInterface
DL_CreationInterface ()
virtual ~DL_CreationInterface ()
void setAttributes (const DL_Attributes &attrib)
DL_Attributes getAttributes ()
void setExtrusion (double dx, double dy, double dz, double elevation)
DL_Extrusion * getExtrusion ()
Additional Inherited Members
Protected Attributes inherited from DL_CreationInterface
DL_Attributes attributes
DL_Extrusion * extrusion
Detailed Description
This class takes care of the entities read from the file. Usually such a class would probably store the entities. this one just prints some information about them to stdout.
Author
Andrew Mustun
Definition at line 37 of file test_creationclass.h.
Constructor & Destructor Documentation
Test_CreationClass()
Test_CreationClass::Test_CreationClass ()
Default constructor.
Definition at line 34 of file test_creationclass.cpp.
Member Function Documentation
add3dFace()
void Test_CreationClass::add3dFace (const DL_3dFaceData & data) virtual
Called for every 3dface start
Reimplemented from DL_CreationAdapter.
Definition at line 97 of file test_creationclass.cpp.
References data, and printAttributes().
addArc()
void Test_CreationClass::addArc (const DL_ArcData & data) virtual
Sample implementation of the method which handles arc entities.
Reimplemented from DL_CreationAdapter.
Definition at line 64 of file test_creationclass.cpp.
References data, and printAttributes().
addCircle()
void Test_CreationClass::addCircle (const DL_CircleData & data) virtual
Sample implementation of the method which handles circle entities.
Reimplemented from DL_CreationAdapter.
Definition at line 73 of file test_creationclass.cpp.
References data, and printAttributes().
addLayer()
void Test_CreationClass::addLayer (const DL_LayerData & data) virtual
Sample implementation of the method which handles layers.
Reimplemented from DL_CreationAdapter.
Definition at line 39 of file test_creationclass.cpp.
References data, and printAttributes().
addLine()
void Test_CreationClass::addLine (const DL_LineData & data) virtual
Sample implementation of the method which handles line entities.
Reimplemented from DL_CreationAdapter.
Definition at line 55 of file test_creationclass.cpp.
References data, and printAttributes().
addPoint()
void Test_CreationClass::addPoint (const DL_PointData & data) virtual
Sample implementation of the method which handles point entities.
Reimplemented from DL_CreationAdapter.
Definition at line 47 of file test_creationclass.cpp.
References data, and printAttributes().
addPolyline()
void Test_CreationClass::addPolyline (const DL_PolylineData & data) virtual
Sample implementation of the method which handles polyline entities.
Reimplemented from DL_CreationAdapter.
Definition at line 82 of file test_creationclass.cpp.
References data, and printAttributes().
addVertex()
void Test_CreationClass::addVertex (const DL_VertexData & data) virtual
Sample implementation of the method which handles vertices.
Reimplemented from DL_CreationAdapter.
Definition at line 91 of file test_creationclass.cpp.
References data, and printAttributes().
printAttributes()
void Test_CreationClass::printAttributes ()
Definition at line 106 of file test_creationclass.cpp.
References DL_CreationInterface::attributes, DL_Attributes::getColor(), DL_Attributes::getLayer(), DL_Attributes::getLinetype(), and DL_Attributes::getWidth().
Referenced by add3dFace(), addArc(), addCircle(), addLayer(), addLine(), addPoint(), addPolyline(), and addVertex().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_io/extern/dxflib/examples/readwrite/test_creationclass.h
/root/ACloudViewer/libs/CV_io/extern/dxflib/examples/readwrite/test_creationclass.cpp