ACloudViewer: FastGlobalRegistrationDialog Class Reference
FastGlobalRegistrationDialog Class Reference
Fast Global Registration dialog.
#include <FastGlobalRegistrationDlg.h>
Public Member Functions
FastGlobalRegistrationDialog (const std::vector< ccPointCloud * > &allClouds, QWidget *parent=nullptr)
Default constructor.
~FastGlobalRegistrationDialog () override
Default destructor.
double getFeatureRadius () const
Returns the feature descritor comptation radius.
ccPointCloud * getReferenceCloud ()
Returns the 'reference' cloud.
void saveParameters () const
Saves parameters for next call.
Protected Member Functions
void autoEstimateRadius ()
void referenceEntityChanged (int index)
void updateGUI ()
Protected Attributes
std::vector< ccPointCloud * > clouds
All clouds (input)
unsigned referencesCloudUinqueID
Reference cloud unique ID.
Detailed Description
Fast Global Registration dialog.
Definition at line 35 of file FastGlobalRegistrationDlg.h.
Constructor & Destructor Documentation
FastGlobalRegistrationDialog()
FastGlobalRegistrationDialog::FastGlobalRegistrationDialog (const std::vector< ccPointCloud * > & allClouds, QWidget * parent = nullptr)
Default constructor.
Definition at line 23 of file FastGlobalRegistrationDlg.cpp.
References autoEstimateRadius(), clouds, ccOctree::GuessNaiveRadius(), max(), ecvColor::red(), referenceEntityChanged(), referencesCloudUinqueID, s_featureRadius, updateGUI(), and ecvColor::yellow().
~FastGlobalRegistrationDialog()
FastGlobalRegistrationDialog::~FastGlobalRegistrationDialog () override
Default destructor.
Definition at line 65 of file FastGlobalRegistrationDlg.cpp.
References clouds, ecvDisplayTools::RedrawDisplay(), and ecvDisplayTools::SetRedrawRecursive().
Member Function Documentation
autoEstimateRadius()
void FastGlobalRegistrationDialog::autoEstimateRadius () protected
Definition at line 137 of file FastGlobalRegistrationDlg.cpp.
References clouds, CVLog::Error(), ccOctree::GuessBestRadiusAutoComputeOctree(), max(), and params.
Referenced by FastGlobalRegistrationDialog().
getFeatureRadius()
double FastGlobalRegistrationDialog::getFeatureRadius () const
Returns the feature descritor comptation radius.
Definition at line 87 of file FastGlobalRegistrationDlg.cpp.
Referenced by FastGlobalRegistrationFilter::getParametersFromDialog(), and saveParameters().
getReferenceCloud()
ccPointCloud * FastGlobalRegistrationDialog::getReferenceCloud ()
Returns the 'reference' cloud.
Definition at line 79 of file FastGlobalRegistrationDlg.cpp.
References clouds, and referencesCloudUinqueID.
Referenced by FastGlobalRegistrationFilter::getParametersFromDialog(), and updateGUI().
referenceEntityChanged()
void FastGlobalRegistrationDialog::referenceEntityChanged (int index) protected
Definition at line 131 of file FastGlobalRegistrationDlg.cpp.
References referencesCloudUinqueID, and updateGUI().
Referenced by FastGlobalRegistrationDialog().
saveParameters()
void FastGlobalRegistrationDialog::saveParameters () const
Saves parameters for next call.
Definition at line 75 of file FastGlobalRegistrationDlg.cpp.
References getFeatureRadius(), and s_featureRadius.
Referenced by FastGlobalRegistrationFilter::getParametersFromDialog().
updateGUI()
void FastGlobalRegistrationDialog::updateGUI () protected
Definition at line 91 of file FastGlobalRegistrationDlg.cpp.
References clouds, ccObject::getName(), getReferenceCloud(), ccObject::getUniqueID(), ecvColor::red(), ecvDisplayTools::RedrawDisplay(), referencesCloudUinqueID, ccDrawableObject::setForceRedraw(), ecvDisplayTools::SetRedrawRecursive(), ccDrawableObject::setTempColor(), ccDrawableObject::setVisible(), and ecvColor::yellow().
Referenced by FastGlobalRegistrationDialog(), and referenceEntityChanged().
Member Data Documentation
clouds
std::vector<ccPointCloud*> FastGlobalRegistrationDialog::clouds protected
All clouds (input)
Definition at line 64 of file FastGlobalRegistrationDlg.h.
Referenced by autoEstimateRadius(), FastGlobalRegistrationDialog(), getReferenceCloud(), updateGUI(), and ~FastGlobalRegistrationDialog().
referencesCloudUinqueID
unsigned FastGlobalRegistrationDialog::referencesCloudUinqueID protected
Reference cloud unique ID.
Definition at line 67 of file FastGlobalRegistrationDlg.h.
Referenced by FastGlobalRegistrationDialog(), getReferenceCloud(), referenceEntityChanged(), and updateGUI().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/dialogs/FastGlobalRegistrationDlg.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/dialogs/FastGlobalRegistrationDlg.cpp