ACloudViewer: ccOverlayDialog Class Reference
ccOverlayDialog Class Reference
Generic overlay dialog interface.
#include <ecvOverlayDialog.h>
Signals
void processFinished (bool accepted)
Signal emitted when process is finished.
void shortcutTriggered (int key)
Signal emitted when an overridden key shortcut is pressed.
void shown ()
Signal emitted when a 'show' event is detected.
Public Member Functions
ccOverlayDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::FramelessWindowHint|Qt::Tool)
Default constructor.
~ccOverlayDialog () override
Destructor.
virtual bool linkWith (QWidget *win)
Links the overlay dialog with a MDI window.
virtual bool start ()
Starts process.
virtual void stop (bool accepted)
Stops process/dialog.
void reject () override
void addOverridenShortcut (Qt::Key key)
bool started () const
Returns whether the tool is currently started or not.
Protected Slots
virtual void onLinkedWindowDeletion (QObject *object=nullptr)
Slot called when the linked window is deleted (calls 'onClose')
Protected Member Functions
bool eventFilter (QObject *obj, QEvent *e) override
Protected Attributes
QWidget * m_associatedWin
Associated (MDI) window.
bool m_processing
Running/processing state.
QList< int > m_overriddenKeys
Overridden keys.
Detailed Description
Generic overlay dialog interface.
Definition at line 17 of file ecvOverlayDialog.h.
Constructor & Destructor Documentation
ccOverlayDialog()
ccOverlayDialog::ccOverlayDialog (QWidget * parent = nullptr, Qt::WindowFlags flags = Qt::FramelessWindowHint | Qt::Tool) explicit
Default constructor.
Definition at line 25 of file ecvOverlayDialog.cpp.
~ccOverlayDialog()
ccOverlayDialog::~ccOverlayDialog () override
Destructor.
Definition at line 30 of file ecvOverlayDialog.cpp.
References onLinkedWindowDeletion().
Member Function Documentation
addOverridenShortcut()
void ccOverlayDialog::addOverridenShortcut (Qt::Key key)
Adds a keyboard shortcut (single key) that will be overridden from the associated window When an overridden key is pressed, the shortcutTriggered(int) signal is emitted.
Definition at line 114 of file ecvOverlayDialog.cpp.
References m_overriddenKeys.
Referenced by ccCompassDlg::ccCompassDlg(), ccGraphicalSegmentationTool::ccGraphicalSegmentationTool(), ccGraphicalTransformationTool::ccGraphicalTransformationTool(), ccTracePolylineTool::ccTracePolylineTool(), ecvAnnotationsTool::ecvAnnotationsTool(), and ecvMeasurementTool::ecvMeasurementTool().
eventFilter()
bool ccOverlayDialog::eventFilter (QObject * obj, QEvent * e) override protected
Definition at line 118 of file ecvOverlayDialog.cpp.
References m_overriddenKeys, shortcutTriggered(), and shown().
linkWith()
bool ccOverlayDialog::linkWith (QWidget * win) virtual
Links the overlay dialog with a MDI window.
Warning: link can't be modified while dialog is displayed/process is running!
Returns
success
Reimplemented in ecvCameraParamEditDlg, ccTracePolylineTool, ccPointPropertiesDlg, ccPointPickingGenericInterface, ccPointPairRegistrationDlg, ecvMeasurementTool, ccGraphicalTransformationTool, ccGraphicalSegmentationTool, ecvFilterTool, ecvFilterByLabelDlg, ecvAnnotationsTool, and ecvAnimationParamDlg.
Definition at line 32 of file ecvOverlayDialog.cpp.
References m_associatedWin, m_processing, onLinkedWindowDeletion(), and CVLog::Warning().
Referenced by ccMPlaneDlgController::ccMPlaneDlgController(), qCloudLayers::doAction(), ccCompass::doAction(), ecvAnimationParamDlg::linkWith(), ecvAnnotationsTool::linkWith(), ecvFilterByLabelDlg::linkWith(), ecvFilterTool::linkWith(), ccGraphicalSegmentationTool::linkWith(), ccGraphicalTransformationTool::linkWith(), ecvMeasurementTool::linkWith(), ccPointPairRegistrationDlg::linkWith(), ccPointPickingGenericInterface::linkWith(), ccTracePolylineTool::linkWith(), onLinkedWindowDeletion(), and stop().
onLinkedWindowDeletion
void ccOverlayDialog::onLinkedWindowDeletion (QObject * object = nullptr) protected virtual slot
Slot called when the linked window is deleted (calls 'onClose')
Definition at line 74 of file ecvOverlayDialog.cpp.
References linkWith(), m_processing, and stop().
Referenced by linkWith(), and ~ccOverlayDialog().
processFinished
void ccOverlayDialog::processFinished (bool accepted) signal
Signal emitted when process is finished.
Parameters
accepted specifies how the process finished (accepted or not)
Referenced by stop().
reject()
void ccOverlayDialog::reject () override
Definition at line 102 of file ecvOverlayDialog.cpp.
References stop().
shortcutTriggered
void ccOverlayDialog::shortcutTriggered (int key) signal
Signal emitted when an overridden key shortcut is pressed.
See ccOverlayDialog::addOverridenShortcut
Referenced by ccCompassDlg::ccCompassDlg(), ccGraphicalSegmentationTool::ccGraphicalSegmentationTool(), ccGraphicalTransformationTool::ccGraphicalTransformationTool(), ccTracePolylineTool::ccTracePolylineTool(), ecvAnnotationsTool::ecvAnnotationsTool(), ecvMeasurementTool::ecvMeasurementTool(), and eventFilter().
shown
void ccOverlayDialog::shown () signal
Signal emitted when a 'show' event is detected.
Referenced by eventFilter(), and MainWindow::registerOverlayDialog().
start()
bool ccOverlayDialog::start () virtual
Starts process.
Returns
success
Reimplemented in ccCloudLayersDlg, ecvCameraParamEditDlg, ccTracePolylineTool, ccPointPropertiesDlg, ccPointPickingGenericInterface, ccPointPairRegistrationDlg, ecvMeasurementTool, ccGraphicalTransformationTool, ccGraphicalSegmentationTool, ecvFilterTool, ecvFilterByLabelDlg, ecvAnnotationsTool, and ecvAnimationParamDlg.
Definition at line 80 of file ecvOverlayDialog.cpp.
References m_processing.
Referenced by ccCompass::enableMapMode(), ecvAnimationParamDlg::start(), ecvAnnotationsTool::start(), ecvFilterByLabelDlg::start(), ecvFilterTool::start(), ccGraphicalSegmentationTool::start(), ccGraphicalTransformationTool::start(), ecvMeasurementTool::start(), ccPointPairRegistrationDlg::start(), ccPointPickingGenericInterface::start(), ccTracePolylineTool::start(), ccCloudLayersDlg::start(), and ccCompass::startMeasuring().
started()
bool ccOverlayDialog::started () const inline
Returns whether the tool is currently started or not.
Definition at line 57 of file ecvOverlayDialog.h.
Referenced by MainWindow::onItemPicked().
stop()
void ccOverlayDialog::stop (bool accepted) virtual
Stops process/dialog.
Automatically emits the 'processFinished' signal (with input state as argument).
Parameters
accepted process/dialog result
Reimplemented in ccPointPropertiesDlg, ccPointPickingGenericInterface, ccPointPairRegistrationDlg, ecvMeasurementTool, ccGraphicalTransformationTool, ecvFilterTool, ecvFilterByLabelDlg, ecvAnnotationsTool, ccCloudLayersDlg, ccTracePolylineTool, and ccGraphicalSegmentationTool.
Definition at line 91 of file ecvOverlayDialog.cpp.
References linkWith(), m_processing, and processFinished().
Referenced by ccCompass::enableMeasureMode(), ccMPlaneDlgController::onCloseButtonPressed(), onLinkedWindowDeletion(), reject(), ccGraphicalSegmentationTool::stop(), ccTracePolylineTool::stop(), ccCloudLayersDlg::stop(), ecvAnnotationsTool::stop(), ecvFilterByLabelDlg::stop(), ecvFilterTool::stop(), ccGraphicalTransformationTool::stop(), ecvMeasurementTool::stop(), ccPointPairRegistrationDlg::stop(), ccPointPickingGenericInterface::stop(), and ccCompass::stopMeasuring().
Member Data Documentation
m_associatedWin
QWidget* ccOverlayDialog::m_associatedWin protected
Associated (MDI) window.
Definition at line 84 of file ecvOverlayDialog.h.
Referenced by ecvAnimationParamDlg::enableListener(), ccPointPairRegistrationDlg::init(), linkWith(), ecvAnimationParamDlg::linkWith(), ecvAnimationParamDlg::onItemPicked(), and ecvAnimationParamDlg::processPickedItem().
m_overriddenKeys
QList<int> ccOverlayDialog::m_overriddenKeys protected
Overridden keys.
Definition at line 90 of file ecvOverlayDialog.h.
Referenced by addOverridenShortcut(), and eventFilter().
m_processing
bool ccOverlayDialog::m_processing protected
Running/processing state.
Definition at line 87 of file ecvOverlayDialog.h.
Referenced by linkWith(), ecvMeasurementTool::onItemPicked(), ccPointPickingGenericInterface::onItemPicked(), onLinkedWindowDeletion(), start(), ecvAnimationParamDlg::start(), ecvAnnotationsTool::start(), ecvFilterTool::start(), ccGraphicalTransformationTool::start(), ecvMeasurementTool::start(), and stop().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVPluginAPI/include/ecvOverlayDialog.h
/root/ACloudViewer/libs/CVPluginAPI/src/ecvOverlayDialog.cpp