ACloudViewer: BundlerImportDlg Class Reference
BundlerImportDlg Class Reference
Dialog for importation of Snavely's Bundler files.
#include <BundlerImportDlg.h>
Public Types
enum OrthoRectMethod { OPTIMIZED , DIRECT_UNDISTORTED , DIRECT }
Image ortho-rectification methods.
Public Member Functions
BundlerImportDlg (QWidget *parent=0)
Default constructor.
virtual ~BundlerImportDlg ()
Destructor.
bool importKeypoints () const
Returns whether keypoints should be imported.
bool useAlternativeKeypoints () const
Returns whether alternative keypoints should be used.
bool importImages () const
Returns whether images should be imported.
bool undistortImages () const
Returns whether images should be undistorted.
bool orthoRectifyImagesAsClouds () const
Returns whether images should be ortho-rectified as clouds.
bool orthoRectifyImagesAsImages () const
Returns whether images should be ortho-rectified as images.
bool generateColoredDTM () const
Returns whether colored pseudo-DTM should be generated.
bool keepImagesInMemory () const
Returns images should be kept in memory or not.
OrthoRectMethod getOrthorectificationMethod () const
Returns the ortho-rectification method (for images)
void setKeypointsCount (unsigned count)
Sets keypoints count on initialization.
void setCamerasCount (unsigned count)
Sets cameras count on initialization.
void setVer (unsigned majorVer, unsigned minorVer)
Sets file version on initialization.
void setImageListFilename (const QString &filename)
Sets default image list filename (full path)
QString getImageListFilename () const
Gets image list filename (full path)
void setAltKeypointsFilename (const QString &filename)
Sets default alternative keypoints filename (full path)
QString getAltKeypointsFilename () const
Gets alternative keypoints filename (full path)
double getScaleFactor () const
Returns scale factor.
unsigned getDTMVerticesCount () const
Returns desired number of vertices for DTM.
bool getOptionalTransfoMatrix (ccGLMatrix &mat)
Returns the optional transformation matrix (if defined)
Protected Slots
void browseImageListFilename ()
void browseAltKeypointsFilename ()
void acceptAndSaveSettings ()
Protected Member Functions
void initFromPersistentSettings ()
Inits dialog state from persistent settings.
void saveToPersistentSettings ()
Saves dialog state from persistent settings.
Detailed Description
Dialog for importation of Snavely's Bundler files.
Definition at line 19 of file BundlerImportDlg.h.
Member Enumeration Documentation
OrthoRectMethod
enum BundlerImportDlg::OrthoRectMethod
Image ortho-rectification methods.
Enumerator
OPTIMIZED
DIRECT_UNDISTORTED
DIRECT
Definition at line 48 of file BundlerImportDlg.h.
Constructor & Destructor Documentation
BundlerImportDlg()
BundlerImportDlg::BundlerImportDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 26 of file BundlerImportDlg.cpp.
References acceptAndSaveSettings(), browseAltKeypointsFilename(), browseImageListFilename(), and initFromPersistentSettings().
~BundlerImportDlg()
BundlerImportDlg::~BundlerImportDlg () virtual
Destructor.
Definition at line 41 of file BundlerImportDlg.cpp.
Member Function Documentation
acceptAndSaveSettings
void BundlerImportDlg::acceptAndSaveSettings () protected slot
Definition at line 103 of file BundlerImportDlg.cpp.
References ccGLMatrixTpl< double >::FromString().
Referenced by BundlerImportDlg().
browseAltKeypointsFilename
void BundlerImportDlg::browseAltKeypointsFilename () protected slot
Definition at line 244 of file BundlerImportDlg.cpp.
Referenced by BundlerImportDlg().
browseImageListFilename
void BundlerImportDlg::browseImageListFilename () protected slot
Definition at line 235 of file BundlerImportDlg.cpp.
Referenced by BundlerImportDlg().
generateColoredDTM()
bool BundlerImportDlg::generateColoredDTM () const
Returns whether colored pseudo-DTM should be generated.
Definition at line 171 of file BundlerImportDlg.cpp.
Referenced by initFromPersistentSettings(), and BundlerFilter::loadFileExtended().
getAltKeypointsFilename()
QString BundlerImportDlg::getAltKeypointsFilename () const
Gets alternative keypoints filename (full path)
Definition at line 231 of file BundlerImportDlg.cpp.
Referenced by BundlerFilter::loadFileExtended().
getDTMVerticesCount()
unsigned BundlerImportDlg::getDTMVerticesCount () const
Returns desired number of vertices for DTM.
Definition at line 257 of file BundlerImportDlg.cpp.
Referenced by BundlerFilter::loadFileExtended().
getImageListFilename()
QString BundlerImportDlg::getImageListFilename () const
Gets image list filename (full path)
Definition at line 223 of file BundlerImportDlg.cpp.
Referenced by BundlerFilter::loadFileExtended().
getOptionalTransfoMatrix()
bool BundlerImportDlg::getOptionalTransfoMatrix (ccGLMatrix & mat)
Returns the optional transformation matrix (if defined)
Definition at line 261 of file BundlerImportDlg.cpp.
References ccGLMatrixTpl< T >::data(), ccGLMatrixTpl< float >::FromString(), and ccGLMatrixTpl< T >::toZero().
Referenced by BundlerFilter::loadFileExtended().
getOrthorectificationMethod()
BundlerImportDlg::OrthoRectMethod BundlerImportDlg::getOrthorectificationMethod () const
Returns the ortho-rectification method (for images)
Definition at line 182 of file BundlerImportDlg.cpp.
References DIRECT, DIRECT_UNDISTORTED, and OPTIMIZED.
Referenced by BundlerFilter::loadFileExtended().
getScaleFactor()
double BundlerImportDlg::getScaleFactor () const
Returns scale factor.
Definition at line 253 of file BundlerImportDlg.cpp.
Referenced by BundlerFilter::loadFileExtended().
importImages()
bool BundlerImportDlg::importImages () const
Returns whether images should be imported.
Definition at line 151 of file BundlerImportDlg.cpp.
Referenced by initFromPersistentSettings(), and BundlerFilter::loadFileExtended().
importKeypoints()
bool BundlerImportDlg::importKeypoints () const
Returns whether keypoints should be imported.
Definition at line 146 of file BundlerImportDlg.cpp.
Referenced by initFromPersistentSettings(), and BundlerFilter::loadFileExtended().
initFromPersistentSettings()
void BundlerImportDlg::initFromPersistentSettings () protected
Inits dialog state from persistent settings.
Definition at line 43 of file BundlerImportDlg.cpp.
References generateColoredDTM(), importImages(), importKeypoints(), keepImagesInMemory(), and undistortImages().
Referenced by BundlerImportDlg().
keepImagesInMemory()
bool BundlerImportDlg::keepImagesInMemory () const
Returns images should be kept in memory or not.
Definition at line 176 of file BundlerImportDlg.cpp.
Referenced by initFromPersistentSettings(), and BundlerFilter::loadFileExtended().
orthoRectifyImagesAsClouds()
bool BundlerImportDlg::orthoRectifyImagesAsClouds () const
Returns whether images should be ortho-rectified as clouds.
Definition at line 161 of file BundlerImportDlg.cpp.
Referenced by BundlerFilter::loadFileExtended().
orthoRectifyImagesAsImages()
bool BundlerImportDlg::orthoRectifyImagesAsImages () const
Returns whether images should be ortho-rectified as images.
Definition at line 166 of file BundlerImportDlg.cpp.
Referenced by BundlerFilter::loadFileExtended().
saveToPersistentSettings()
void BundlerImportDlg::saveToPersistentSettings () protected
Saves dialog state from persistent settings.
setAltKeypointsFilename()
void BundlerImportDlg::setAltKeypointsFilename (const QString & filename)
Sets default alternative keypoints filename (full path)
Definition at line 227 of file BundlerImportDlg.cpp.
References filename.
Referenced by BundlerFilter::loadFileExtended().
setCamerasCount()
void BundlerImportDlg::setCamerasCount (unsigned count)
Sets cameras count on initialization.
Definition at line 210 of file BundlerImportDlg.cpp.
References count.
Referenced by BundlerFilter::loadFileExtended().
setImageListFilename()
void BundlerImportDlg::setImageListFilename (const QString & filename)
Sets default image list filename (full path)
Definition at line 219 of file BundlerImportDlg.cpp.
References filename.
Referenced by BundlerFilter::loadFileExtended().
setKeypointsCount()
void BundlerImportDlg::setKeypointsCount (unsigned count)
Sets keypoints count on initialization.
Definition at line 198 of file BundlerImportDlg.cpp.
References count.
Referenced by BundlerFilter::loadFileExtended().
setVer()
void BundlerImportDlg::setVer (unsigned majorVer, unsigned minorVer)
Sets file version on initialization.
Definition at line 215 of file BundlerImportDlg.cpp.
Referenced by BundlerFilter::loadFileExtended().
undistortImages()
bool BundlerImportDlg::undistortImages () const
Returns whether images should be undistorted.
Definition at line 155 of file BundlerImportDlg.cpp.
Referenced by initFromPersistentSettings(), and BundlerFilter::loadFileExtended().
useAlternativeKeypoints()
bool BundlerImportDlg::useAlternativeKeypoints () const
Returns whether alternative keypoints should be used.
Definition at line 142 of file BundlerImportDlg.cpp.
Referenced by BundlerFilter::loadFileExtended().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qAdditionalIO/include/BundlerImportDlg.h
/root/ACloudViewer/plugins/core/IO/qAdditionalIO/src/BundlerImportDlg.cpp