ACloudViewer: QtCompatTextCodec Class Reference
QtCompatTextCodec Class Reference
#include <QtCompat.h>
Public Member Functions
QtCompatTextCodec (QStringConverter::Encoding encoding=QStringConverter::System)
QByteArray fromUnicode (const QString &str)
QString toUnicode (const char *chars, int len=-1)
QString toUnicode (const QByteArray &ba)
Detailed Description
Definition at line 584 of file QtCompat.h.
Constructor & Destructor Documentation
QtCompatTextCodec()
QtCompatTextCodec::QtCompatTextCodec (QStringConverter::Encoding encoding = QStringConverter::System) inline
Definition at line 589 of file QtCompat.h.
Member Function Documentation
fromUnicode()
QByteArray QtCompatTextCodec::fromUnicode (const QString & str) inline
Definition at line 594 of file QtCompat.h.
References result.
Referenced by QTextCodec::fromUnicode().
toUnicode() [1/2]
QString QtCompatTextCodec::toUnicode (const char * chars, int len = -1) inline
Definition at line 610 of file QtCompat.h.
References result.
Referenced by GetPythonExeVersion(), PythonConfig::initFromPythonExecutable(), and QTextCodec::toUnicode().
toUnicode() [2/2]
QString QtCompatTextCodec::toUnicode (const QByteArray & ba) inline
Definition at line 632 of file QtCompat.h.
References result.
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/QtCompat.h