ACloudViewer: colmap::CameraRig Class Reference
colmap::CameraRig Class Reference
#include <camera_rig.h>
Public Member Functions
CameraRig ()
size_t NumCameras () const
size_t NumSnapshots () const
bool HasCamera (const camera_t camera_id) const
camera_t RefCameraId () const
void SetRefCameraId (const camera_t camera_id)
std::vector< camera_t > GetCameraIds () const
const std::vector< std::vector< image_t > > & Snapshots () const
void AddCamera (const camera_t camera_id, const Eigen::Vector4d &rel_qvec, const Eigen::Vector3d &rel_tvec)
void AddSnapshot (const std::vector< image_t > &image_ids)
void Check (const Reconstruction &reconstruction) const
Eigen::Vector4d & RelativeQvec (const camera_t camera_id)
const Eigen::Vector4d & RelativeQvec (const camera_t camera_id) const
Eigen::Vector3d & RelativeTvec (const camera_t camera_id)
const Eigen::Vector3d & RelativeTvec (const camera_t camera_id) const
double ComputeScale (const Reconstruction &reconstruction) const
bool ComputeRelativePoses (const Reconstruction &reconstruction)
void ComputeAbsolutePose (const size_t snapshot_idx, const Reconstruction &reconstruction, Eigen::Vector4d *abs_qvec, Eigen::Vector3d *abs_tvec) const
Detailed Description
Definition at line 25 of file camera_rig.h.
Constructor & Destructor Documentation
CameraRig()
colmap::CameraRig::CameraRig ()
Definition at line 38 of file camera_rig.cc.
Member Function Documentation
AddCamera()
void colmap::CameraRig::AddCamera (const camera_t camera_id, const Eigen::Vector4d & rel_qvec, const Eigen::Vector3d & rel_tvec)
Definition at line 68 of file camera_rig.cc.
References HasCamera(), and NumSnapshots().
Referenced by BOOST_AUTO_TEST_CASE().
AddSnapshot()
void colmap::CameraRig::AddSnapshot (const std::vector< image_t > & image_ids)
Definition at line 79 of file camera_rig.cc.
References NumCameras(), and colmap::VectorContainsDuplicateValues().
Referenced by BOOST_AUTO_TEST_CASE().
Check()
void colmap::CameraRig::Check (const Reconstruction & reconstruction) const
Definition at line 86 of file camera_rig.cc.
References colmap::Reconstruction::ExistsCamera(), colmap::Reconstruction::ExistsImage(), HasCamera(), image, colmap::Reconstruction::Image(), and NumCameras().
Referenced by BOOST_AUTO_TEST_CASE().
ComputeAbsolutePose()
void colmap::CameraRig::ComputeAbsolutePose (const size_t snapshot_idx, const Reconstruction & reconstruction, Eigen::Vector4d * abs_qvec, Eigen::Vector3d * abs_tvec) const
Definition at line 230 of file camera_rig.cc.
References colmap::AverageQuaternions(), colmap::ConcatenateQuaternions(), image, colmap::Reconstruction::Image(), colmap::InvertPose(), colmap::QuaternionRotatePoint(), RelativeQvec(), and RelativeTvec().
Referenced by BOOST_AUTO_TEST_CASE().
ComputeRelativePoses()
bool colmap::CameraRig::ComputeRelativePoses (const Reconstruction & reconstruction)
Definition at line 167 of file camera_rig.cc.
References colmap::AverageQuaternions(), colmap::ComposeIdentityQuaternion(), colmap::ComputeRelativePose(), QtCompat::endl(), image, colmap::Reconstruction::Image(), colmap::kInvalidCameraId, NumSnapshots(), colmap::Image::Qvec(), RelativeQvec(), RelativeTvec(), and colmap::Image::Tvec().
Referenced by BOOST_AUTO_TEST_CASE().
ComputeScale()
double colmap::CameraRig::ComputeScale (const Reconstruction & reconstruction) const
Definition at line 128 of file camera_rig.cc.
References e, image, colmap::Reconstruction::Image(), NumCameras(), NumSnapshots(), colmap::ProjectionCenterFromPose(), RelativeQvec(), and RelativeTvec().
Referenced by BOOST_AUTO_TEST_CASE().
GetCameraIds()
std::vector< camera_t > colmap::CameraRig::GetCameraIds () const
Definition at line 55 of file camera_rig.cc.
References NumCameras().
Referenced by BOOST_AUTO_TEST_CASE().
HasCamera()
bool colmap::CameraRig::HasCamera (const camera_t camera_id) const
Definition at line 44 of file camera_rig.cc.
Referenced by AddCamera(), BOOST_AUTO_TEST_CASE(), Check(), and SetRefCameraId().
NumCameras()
size_t colmap::CameraRig::NumCameras () const
Definition at line 40 of file camera_rig.cc.
Referenced by AddSnapshot(), BOOST_AUTO_TEST_CASE(), Check(), ComputeScale(), and GetCameraIds().
NumSnapshots()
size_t colmap::CameraRig::NumSnapshots () const
Definition at line 42 of file camera_rig.cc.
Referenced by AddCamera(), BOOST_AUTO_TEST_CASE(), ComputeRelativePoses(), and ComputeScale().
RefCameraId()
camera_t colmap::CameraRig::RefCameraId () const
Definition at line 48 of file camera_rig.cc.
RelativeQvec() [1/2]
Eigen::Vector4d & colmap::CameraRig::RelativeQvec (const camera_t camera_id)
Definition at line 112 of file camera_rig.cc.
Referenced by BOOST_AUTO_TEST_CASE(), ComputeAbsolutePose(), ComputeRelativePoses(), and ComputeScale().
RelativeQvec() [2/2]
const Eigen::Vector4d & colmap::CameraRig::RelativeQvec (const camera_t camera_id) const
Definition at line 116 of file camera_rig.cc.
RelativeTvec() [1/2]
Eigen::Vector3d & colmap::CameraRig::RelativeTvec (const camera_t camera_id)
Definition at line 120 of file camera_rig.cc.
Referenced by BOOST_AUTO_TEST_CASE(), ComputeAbsolutePose(), ComputeRelativePoses(), and ComputeScale().
RelativeTvec() [2/2]
const Eigen::Vector3d & colmap::CameraRig::RelativeTvec (const camera_t camera_id) const
Definition at line 124 of file camera_rig.cc.
SetRefCameraId()
void colmap::CameraRig::SetRefCameraId (const camera_t camera_id)
Definition at line 50 of file camera_rig.cc.
References HasCamera().
Referenced by BOOST_AUTO_TEST_CASE().
Snapshots()
const std::vector< std::vector< image_t > > & colmap::CameraRig::Snapshots () const
Definition at line 64 of file camera_rig.cc.
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/camera_rig.h
/root/ACloudViewer/libs/Reconstruction/src/base/camera_rig.cc