ACloudViewer: QCPScatterStyle Class Reference
QCPScatterStyle Class Reference
Represents the visual appearance of scatter points.
#include <qcustomplot.h>
Public Types
enum ScatterProperty {
spNone = 0x00 , spPen = 0x01 , spBrush = 0x02 , spSize = 0x04 ,
spShape = 0x08 , spAll = 0xFF
}
enum ScatterShape {
ssNone , ssDot , ssCross , ssPlus ,
ssCircle , ssDisc , ssSquare , ssDiamond ,
ssStar , ssTriangle , ssTriangleInverted , ssCrossSquare ,
ssPlusSquare , ssCrossCircle , ssPlusCircle , ssPeace ,
ssPixmap , ssCustom , ssNone , ssDot ,
ssCross , ssPlus , ssCircle , ssDisc ,
ssSquare , ssDiamond , ssStar , ssTriangle ,
ssTriangleInverted , ssCrossSquare , ssPlusSquare , ssCrossCircle ,
ssPlusCircle , ssPeace , ssPixmap , ssCustom
}
enum ScatterShape {
ssNone , ssDot , ssCross , ssPlus ,
ssCircle , ssDisc , ssSquare , ssDiamond ,
ssStar , ssTriangle , ssTriangleInverted , ssCrossSquare ,
ssPlusSquare , ssCrossCircle , ssPlusCircle , ssPeace ,
ssPixmap , ssCustom , ssNone , ssDot ,
ssCross , ssPlus , ssCircle , ssDisc ,
ssSquare , ssDiamond , ssStar , ssTriangle ,
ssTriangleInverted , ssCrossSquare , ssPlusSquare , ssCrossCircle ,
ssPlusCircle , ssPeace , ssPixmap , ssCustom
}
Public Member Functions
QCPScatterStyle ()
QCPScatterStyle (ScatterShape shape, double size=6)
QCPScatterStyle (ScatterShape shape, const QColor &color, double size)
QCPScatterStyle (ScatterShape shape, const QColor &color, const QColor &fill, double size)
QCPScatterStyle (ScatterShape shape, const QPen &pen, const QBrush &brush, double size)
QCPScatterStyle (const QPixmap &pixmap)
QCPScatterStyle (const QPainterPath &customPath, const QPen &pen, const QBrush &brush=Qt::NoBrush, double size=6)
double size () const
ScatterShape shape () const
QPen pen () const
QBrush brush () const
QPixmap pixmap () const
QPainterPath customPath () const
void setFromOther (const QCPScatterStyle &other, ScatterProperties properties)
void setSize (double size)
void setShape (ScatterShape shape)
void setPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setPixmap (const QPixmap &pixmap)
void setCustomPath (const QPainterPath &customPath)
bool isNone () const
bool isPenDefined () const
void undefinePen ()
void applyTo (QCPPainter *painter, const QPen &defaultPen) const
void drawShape (QCPPainter *painter, const QPointF &pos) const
void drawShape (QCPPainter *painter, double x, double y) const
QCPScatterStyle ()
QCPScatterStyle (ScatterShape shape, double size=6)
QCPScatterStyle (ScatterShape shape, const QColor &color, double size)
QCPScatterStyle (ScatterShape shape, const QColor &color, const QColor &fill, double size)
QCPScatterStyle (ScatterShape shape, const QPen &pen, const QBrush &brush, double size)
QCPScatterStyle (const QPixmap &pixmap)
QCPScatterStyle (const QPainterPath &customPath, const QPen &pen, const QBrush &brush=Qt::NoBrush, double size=6)
double size () const
ScatterShape shape () const
QPen pen () const
QBrush brush () const
QPixmap pixmap () const
QPainterPath customPath () const
void setSize (double size)
void setShape (ScatterShape shape)
void setPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setPixmap (const QPixmap &pixmap)
void setCustomPath (const QPainterPath &customPath)
bool isNone () const
bool isPenDefined () const
void applyTo (QCPPainter *painter, const QPen &defaultPen) const
void drawShape (QCPPainter *painter, QPointF pos) const
void drawShape (QCPPainter *painter, double x, double y) const
Protected Attributes
double mSize
ScatterShape mShape
QPen mPen
QBrush mBrush
QPixmap mPixmap
QPainterPath mCustomPath
bool mPenDefined
Detailed Description
Represents the visual appearance of scatter points.
This class holds information about shape, color and size of scatter points. In plottables like QCPGraph it is used to store how scatter points shall be drawn. For example, QCPGraph::setScatterStyle takes a QCPScatterStyle instance.
A scatter style consists of a shape (setShape), a line color (setPen) and possibly a fill (setBrush), if the shape provides a fillable area. Further, the size of the shape can be controlled with setSize.
Specifying a scatter style
You can set all these configurations either by calling the respective functions on an instance:
Or you can use one of the various constructors that take different parameter combinations, making it easy to specify a scatter style in a single call, like so:
qcpscatterstyle-creation-2
Leaving the color/pen up to the
plottable
There are two constructors which leave the pen undefined: QCPScatterStyle() and QCPScatterStyle(ScatterShape shape, double size). If those constructors are used, a call to isPenDefined will return false. It leads to scatter points that inherit the pen from the plottable that uses the scatter style. Thus, if such a scatter style is passed to QCPGraph, the line color of the graph (QCPGraph::setPen) will be used by the scatter points. This makes it very convenient to set up typical scatter settings:
qcpscatterstyle-shortcreation
Notice that it wasn't even necessary to explicitly call a QCPScatterStyle constructor. This works because QCPScatterStyle provides a constructor that can transform a ScatterShape directly into a QCPScatterStyle instance (that's the QCPScatterStyle(ScatterShape shape, double size) constructor with a default for size). In those cases, C++ allows directly supplying a ScatterShape, where actually a QCPScatterStyle is expected.
Custom shapes and pixmaps
QCPScatterStyle supports drawing custom shapes and arbitrary pixmaps as scatter points.
For custom shapes, you can provide a QPainterPath with the desired shape to the setCustomPath function or call the constructor that takes a painter path. The scatter shape will automatically be set to ssCustom.
For pixmaps, you call setPixmap with the desired QPixmap. Alternatively you can use the constructor that takes a QPixmap. The scatter shape will automatically be set to ssPixmap. Note that setSize does not influence the appearance of the pixmap.
Definition at line 2695 of file qcustomplot.h.
Member Enumeration Documentation
ScatterProperty
enum QCPScatterStyle::ScatterProperty
Represents the various properties of a scatter style instance. For example, this enum is used to specify which properties of QCPSelectionDecorator::setScatterStyle will be used when highlighting selected data points.
Specific scatter properties can be transferred between QCPScatterStyle instances via setFromOther.
Enumerator
spNone
0x00 None
spPen
0x01 The pen property, see setPen
spBrush
0x02 The brush property, see setBrush
spSize
0x04 The size property, see setSize
spShape
0x08 The shape property, see setShape
spAll
0xFF All properties
Definition at line 2707 of file qcustomplot.h.
ScatterShape [1/2]
enum QCPScatterStyle::ScatterShape
Defines the shape used for scatter points.
On plottables/items that draw scatters, the sizes of these visualizations (with exception of ssDot and ssPixmap) can be controlled with the setSize function. Scatters are drawn with the pen and brush specified with setPen and setBrush.
Enumerator
ssNone
no scatter symbols are drawn (e.g. in QCPGraph, data only represented with lines)
ssDot
\enumimage{ssDot.png} a single pixel (use ssDisc or ssCircle if you want a round shape with a certain radius)
ssCross
\enumimage{ssCross.png} a cross
ssPlus
\enumimage{ssPlus.png} a plus
ssCircle
\enumimage{ssCircle.png} a circle
ssDisc
\enumimage{ssDisc.png} a circle which is filled with the pen's color (not the brush as with ssCircle)
ssSquare
\enumimage{ssSquare.png} a square
ssDiamond
\enumimage{ssDiamond.png} a diamond
ssStar
\enumimage{ssStar.png} a star with eight arms, i.e. a combination of cross and plus
ssTriangle
\enumimage{ssTriangle.png} an equilateral triangle, standing on baseline
ssTriangleInverted
\enumimage{ssTriangleInverted.png} an equilateral triangle, standing on corner
ssCrossSquare
\enumimage{ssCrossSquare.png} a square with a cross inside
ssPlusSquare
\enumimage{ssPlusSquare.png} a square with a plus inside
ssCrossCircle
\enumimage{ssCrossCircle.png} a circle with a cross inside
ssPlusCircle
\enumimage{ssPlusCircle.png} a circle with a plus inside
ssPeace
\enumimage{ssPeace.png} a circle, with one vertical and two downward diagonal lines
ssPixmap
a custom pixmap specified by setPixmap, centered on the data point coordinates
ssCustom
custom painter operations are performed per scatter (As QPainterPath, see setCustomPath)
ssNone
no scatter symbols are drawn (e.g. in QCPGraph, data only represented with lines)
ssDot
\enumimage{ssDot.png} a single pixel (use ssDisc or ssCircle if you want a round shape with a certain radius)
ssCross
\enumimage{ssCross.png} a cross
ssPlus
\enumimage{ssPlus.png} a plus
ssCircle
\enumimage{ssCircle.png} a circle
ssDisc
\enumimage{ssDisc.png} a circle which is filled with the pen's color (not the brush as with ssCircle)
ssSquare
\enumimage{ssSquare.png} a square
ssDiamond
\enumimage{ssDiamond.png} a diamond
ssStar
\enumimage{ssStar.png} a star with eight arms, i.e. a combination of cross and plus
ssTriangle
\enumimage{ssTriangle.png} an equilateral triangle, standing on baseline
ssTriangleInverted
\enumimage{ssTriangleInverted.png} an equilateral triangle, standing on corner
ssCrossSquare
\enumimage{ssCrossSquare.png} a square with a cross inside
ssPlusSquare
\enumimage{ssPlusSquare.png} a square with a plus inside
ssCrossCircle
\enumimage{ssCrossCircle.png} a circle with a cross inside
ssPlusCircle
\enumimage{ssPlusCircle.png} a circle with a plus inside
ssPeace
\enumimage{ssPeace.png} a circle, with one vertical and two downward diagonal lines
ssPixmap
a custom pixmap specified by setPixmap, centered on the data point coordinates
ssCustom
custom painter operations are performed per scatter (As QPainterPath, see setCustomPath)
Definition at line 2732 of file qcustomplot.h.
ScatterShape [2/2]
enum QCPScatterStyle::ScatterShape
Defines the shape used for scatter points.
On plottables/items that draw scatters, the sizes of these visualizations (with exception of ssDot and ssPixmap) can be controlled with the setSize function. Scatters are drawn with the pen and brush specified with setPen and setBrush.
Enumerator
ssNone
no scatter symbols are drawn (e.g. in QCPGraph, data only represented with lines)
ssDot
\enumimage{ssDot.png} a single pixel (use ssDisc or ssCircle if you want a round shape with a certain radius)
ssCross
\enumimage{ssCross.png} a cross
ssPlus
\enumimage{ssPlus.png} a plus
ssCircle
\enumimage{ssCircle.png} a circle
ssDisc
\enumimage{ssDisc.png} a circle which is filled with the pen's color (not the brush as with ssCircle)
ssSquare
\enumimage{ssSquare.png} a square
ssDiamond
\enumimage{ssDiamond.png} a diamond
ssStar
\enumimage{ssStar.png} a star with eight arms, i.e. a combination of cross and plus
ssTriangle
\enumimage{ssTriangle.png} an equilateral triangle, standing on baseline
ssTriangleInverted
\enumimage{ssTriangleInverted.png} an equilateral triangle, standing on corner
ssCrossSquare
\enumimage{ssCrossSquare.png} a square with a cross inside
ssPlusSquare
\enumimage{ssPlusSquare.png} a square with a plus inside
ssCrossCircle
\enumimage{ssCrossCircle.png} a circle with a cross inside
ssPlusCircle
\enumimage{ssPlusCircle.png} a circle with a plus inside
ssPeace
\enumimage{ssPeace.png} a circle, with one vertical and two downward diagonal lines
ssPixmap
a custom pixmap specified by setPixmap, centered on the data point coordinates
ssCustom
custom painter operations are performed per scatter (As QPainterPath, see setCustomPath)
ssNone
no scatter symbols are drawn (e.g. in QCPGraph, data only represented with lines)
ssDot
\enumimage{ssDot.png} a single pixel (use ssDisc or ssCircle if you want a round shape with a certain radius)
ssCross
\enumimage{ssCross.png} a cross
ssPlus
\enumimage{ssPlus.png} a plus
ssCircle
\enumimage{ssCircle.png} a circle
ssDisc
\enumimage{ssDisc.png} a circle which is filled with the pen's color (not the brush as with ssCircle)
ssSquare
\enumimage{ssSquare.png} a square
ssDiamond
\enumimage{ssDiamond.png} a diamond
ssStar
\enumimage{ssStar.png} a star with eight arms, i.e. a combination of cross and plus
ssTriangle
\enumimage{ssTriangle.png} an equilateral triangle, standing on baseline
ssTriangleInverted
\enumimage{ssTriangleInverted.png} an equilateral triangle, standing on corner
ssCrossSquare
\enumimage{ssCrossSquare.png} a square with a cross inside
ssPlusSquare
\enumimage{ssPlusSquare.png} a square with a plus inside
ssCrossCircle
\enumimage{ssCrossCircle.png} a circle with a cross inside
ssPlusCircle
\enumimage{ssPlusCircle.png} a circle with a plus inside
ssPeace
\enumimage{ssPeace.png} a circle, with one vertical and two downward diagonal lines
ssPixmap
a custom pixmap specified by setPixmap, centered on the data point coordinates
ssCustom
custom painter operations are performed per scatter (As QPainterPath, see setCustomPath)
Definition at line 357 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPScatterStyle() [1/14]
QCPScatterStyle::QCPScatterStyle ()
Creates a new QCPScatterStyle instance with size set to 6. No shape, pen or brush is defined.
Since the pen is undefined (isPenDefined returns false), the scatter color will be inherited from the plottable that uses this scatter style.
Definition at line 10324 of file qcustomplot.cpp.
QCPScatterStyle() [2/14]
QCPScatterStyle::QCPScatterStyle (ScatterShape shape, double size = 6)
Creates a new QCPScatterStyle instance with shape set to shape and size to size. No pen or brush is defined.
Since the pen is undefined (isPenDefined returns false), the scatter color will be inherited from the plottable that uses this scatter style.
Definition at line 10338 of file qcustomplot.cpp.
QCPScatterStyle() [3/14]
QCPScatterStyle::QCPScatterStyle (ScatterShape shape, const QColor & color, double size)
Creates a new QCPScatterStyle instance with shape set to shape, the pen color set to color, and size to size. No brush is defined, i.e. the scatter point will not be filled.
Definition at line 10350 of file qcustomplot.cpp.
QCPScatterStyle() [4/14]
QCPScatterStyle::QCPScatterStyle (ScatterShape shape, const QColor & color, const QColor & fill, double size)
Creates a new QCPScatterStyle instance with shape set to shape, the pen color set to color, the brush color to fill (with a solid pattern), and size to size.
Definition at line 10364 of file qcustomplot.cpp.
QCPScatterStyle() [5/14]
QCPScatterStyle::QCPScatterStyle (ScatterShape shape, const QPen & pen, const QBrush & brush, double size)
Creates a new QCPScatterStyle instance with shape set to shape, the pen set to pen, the brush to brush, and size to size.
Warning
In some cases it might be tempting to directly use a pen style like Qt::NoPen as pen and a color like Qt::blue as brush. Notice however, that the corresponding call
QCPScatterStyle(QCPScatterShape::ssCircle, Qt::NoPen, Qt::blue, 5)
doesn't necessarily lead C++ to use this constructor in some cases, but might mistake Qt::NoPen for a QColor and use the QCPScatterStyle(ScatterShape shape, const QColor &color, const QColor &fill, double size) constructor instead (which will lead to an unexpected look of the scatter points). To prevent this, be more explicit with the parameter types. For example, use QBrush(Qt::blue) instead of just Qt::blue, to clearly point out to the compiler that this constructor is wanted.
Definition at line 10390 of file qcustomplot.cpp.
QCPScatterStyle() [6/14]
QCPScatterStyle::QCPScatterStyle (const QPixmap & pixmap)
Creates a new QCPScatterStyle instance which will show the specified pixmap. The scatter shape is set to ssPixmap.
Definition at line 10404 of file qcustomplot.cpp.
QCPScatterStyle() [7/14]
QCPScatterStyle::QCPScatterStyle (const QPainterPath & customPath, const QPen & pen, const QBrush & brush = Qt::NoBrush, double size = 6)
Creates a new QCPScatterStyle instance with a custom shape that is defined via customPath. The scatter shape is set to ssCustom.
The custom shape line will be drawn with pen and filled with brush. The size has a slightly different meaning than for built-in scatter points: The custom path will be drawn scaled by a factor of size/6.0. Since the default size is 6, the custom path will appear in its original size by default. To for example double the size of the path, set size to 12.
Creates a new QCPScatterStyle instance with a custom shape that is defined via customPath. The scatter shape is set to ssCustom.
The custom shape line will be drawn with pen and filled with brush. The size has a slightly different meaning than for built-in scatter points: The custom path will be drawn scaled by a factor of size/6.0. Since the default size is 6, the custom path will appear at a its natural size by default. To double the size of the path for example, set size to 12.
Definition at line 10422 of file qcustomplot.cpp.
QCPScatterStyle() [8/14]
QCPScatterStyle::QCPScatterStyle ()
QCPScatterStyle() [9/14]
QCPScatterStyle::QCPScatterStyle (ScatterShape shape, double size = 6)
QCPScatterStyle() [10/14]
QCPScatterStyle::QCPScatterStyle (ScatterShape shape, const QColor & color, double size)
QCPScatterStyle() [11/14]
QCPScatterStyle::QCPScatterStyle (ScatterShape shape, const QColor & color, const QColor & fill, double size)
QCPScatterStyle() [12/14]
QCPScatterStyle::QCPScatterStyle (ScatterShape shape, const QPen & pen, const QBrush & brush, double size)
QCPScatterStyle() [13/14]
QCPScatterStyle::QCPScatterStyle (const QPixmap & pixmap)
QCPScatterStyle() [14/14]
QCPScatterStyle::QCPScatterStyle (const QPainterPath & customPath, const QPen & pen, const QBrush & brush = Qt::NoBrush, double size = 6)
Member Function Documentation
applyTo() [1/2]
void QCPScatterStyle::applyTo (QCPPainter * painter, const QPen & defaultPen) const
Applies the pen and the brush of this scatter style to painter. If this scatter style has an undefined pen (isPenDefined), sets the pen of painter to defaultPen instead.
This function is used by plottables (or any class that wants to draw scatters) just before a number of scatters with this style shall be drawn with the painter.
See also
drawShape
Definition at line 10538 of file qcustomplot.cpp.
References mBrush, mPen, mPenDefined, and QCPPainter::setPen().
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPStatisticalBox::drawOutliers(), QCPCurve::drawScatterPlot(), QCPGraph::drawScatterPlot(), and QCPStatisticalBox::drawStatisticalBox().
applyTo() [2/2]
void QCPScatterStyle::applyTo (QCPPainter * painter, const QPen & defaultPen) const
brush() [1/2]
QBrush QCPScatterStyle::brush () const inline
Definition at line 2806 of file qcustomplot.h.
Referenced by setBrush(), and setFromOther().
brush() [2/2]
QBrush QCPScatterStyle::brush () const inline
Definition at line 430 of file qcustomplot.h.
customPath() [1/2]
QPainterPath QCPScatterStyle::customPath () const inline
Definition at line 2808 of file qcustomplot.h.
Referenced by setCustomPath(), and setFromOther().
customPath() [2/2]
QPainterPath QCPScatterStyle::customPath () const inline
Definition at line 432 of file qcustomplot.h.
drawShape() [1/4]
void QCPScatterStyle::drawShape (QCPPainter * painter, const QPointF & pos) const
Draws the scatter shape with painter at position pos.
This function does not modify the pen or the brush on the painter, as applyTo is meant to be called before scatter points are drawn with drawShape.
See also
applyTo
Definition at line 10553 of file qcustomplot.cpp.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPStatisticalBox::drawOutliers(), QCPCurve::drawScatterPlot(), QCPGraph::drawScatterPlot(), drawShape(), and QCPStatisticalBox::drawStatisticalBox().
drawShape() [2/4]
void QCPScatterStyle::drawShape (QCPPainter * painter, double x, double y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Draws the scatter shape with painter at position x and y.
Definition at line 10560 of file qcustomplot.cpp.
References QCPPainter::drawLine(), mCustomPath, mPixmap, mShape, mSize, ssCircle, ssCross, ssCrossCircle, ssCrossSquare, ssCustom, ssDiamond, ssDisc, ssDot, ssNone, ssPeace, ssPixmap, ssPlus, ssPlusCircle, ssPlusSquare, ssSquare, ssStar, ssTriangle, ssTriangleInverted, x, and y.
drawShape() [3/4]
void QCPScatterStyle::drawShape (QCPPainter * painter, double x, double y) const
drawShape() [4/4]
void QCPScatterStyle::drawShape (QCPPainter * painter, QPointF pos) const
Draws the scatter shape with painter at position pos.
This function does not modify the pen or the brush on the painter, as applyTo is meant to be called before scatter points are drawn with drawShape.
See also
applyTo
Definition at line 523 of file qcustomplot.cpp.
References drawShape().
isNone() [1/2]
bool QCPScatterStyle::isNone () const inline
Returns whether the scatter shape is ssNone.
See also
setShape
Definition at line 2821 of file qcustomplot.h.
Referenced by QCPGraph::draw(), QCPCurve::draw(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPCurve::getCurveData(), QCPCurve::pointDistance(), and QCPGraph::pointDistance().
isNone() [2/2]
bool QCPScatterStyle::isNone () const inline
Definition at line 443 of file qcustomplot.h.
isPenDefined() [1/2]
bool QCPScatterStyle::isPenDefined () const inline
Returns whether a pen has been defined for this scatter style.
The pen is undefined if a constructor is called that does not carry pen as parameter. Those are QCPScatterStyle() and QCPScatterStyle(ScatterShape shape, double size). If the pen is undefined, the pen of the respective plottable will be used for drawing scatters.
If a pen was defined for this scatter style instance, and you now wish to undefine the pen, call undefinePen.
See also
setPen
Returns whether a pen has been defined for this scatter style.
The pen is undefined if a constructor is called that does not carry pen as parameter. Those are QCPScatterStyle() and QCPScatterStyle(ScatterShape shape, double size). If the pen is left undefined, the scatter color will be inherited from the plottable that uses this scatter style.
See also
setPen
Definition at line 2822 of file qcustomplot.h.
Referenced by setFromOther().
isPenDefined() [2/2]
bool QCPScatterStyle::isPenDefined () const inline
Definition at line 444 of file qcustomplot.h.
pen() [1/2]
QPen QCPScatterStyle::pen () const inline
Definition at line 2805 of file qcustomplot.h.
Referenced by setFromOther(), and setPen().
pen() [2/2]
QPen QCPScatterStyle::pen () const inline
Definition at line 429 of file qcustomplot.h.
pixmap() [1/2]
QPixmap QCPScatterStyle::pixmap () const inline
Definition at line 2807 of file qcustomplot.h.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), setFromOther(), and setPixmap().
pixmap() [2/2]
QPixmap QCPScatterStyle::pixmap () const inline
Definition at line 431 of file qcustomplot.h.
setBrush() [1/2]
void QCPScatterStyle::setBrush (const QBrush & brush)
Sets the brush that will be used to fill scatter points to brush. Note that not all scatter shapes have fillable areas. For example, ssPlus does not while ssCircle does.
See also
setPen
Definition at line 10495 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by setFromOther().
setBrush() [2/2]
void QCPScatterStyle::setBrush (const QBrush & brush)
setCustomPath() [1/2]
void QCPScatterStyle::setCustomPath (const QPainterPath & customPath)
Sets the custom shape that will be drawn as scatter point to customPath.
The scatter shape is automatically set to ssCustom.
Definition at line 10514 of file qcustomplot.cpp.
References customPath(), mCustomPath, setShape(), and ssCustom.
Referenced by setFromOther().
setCustomPath() [2/2]
void QCPScatterStyle::setCustomPath (const QPainterPath & customPath)
setFromOther()
void QCPScatterStyle::setFromOther (const QCPScatterStyle & other, ScatterProperties properties)
Copies the specified properties from the other scatter style to this scatter style.
Definition at line 10437 of file qcustomplot.cpp.
References brush(), customPath(), isPenDefined(), pen(), pixmap(), setBrush(), setCustomPath(), setPen(), setPixmap(), setShape(), setSize(), shape(), size(), spBrush, spPen, spShape, spSize, ssCustom, ssPixmap, and undefinePen().
setPen() [1/2]
void QCPScatterStyle::setPen (const QPen & pen)
Sets the pen that will be used to draw scatter points to pen.
If the pen was previously undefined (see isPenDefined), the pen is considered defined after a call to this function, even if pen is Qt::NoPen. If you have defined a pen previously by calling this function and now wish to undefine the pen, call undefinePen.
See also
setBrush
Sets the pen that will be used to draw scatter points to pen.
If the pen was previously undefined (see isPenDefined), the pen is considered defined after a call to this function, even if pen is Qt::NoPen.
See also
setBrush
Definition at line 10483 of file qcustomplot.cpp.
References mPen, mPenDefined, and pen().
Referenced by setFromOther().
setPen() [2/2]
void QCPScatterStyle::setPen (const QPen & pen)
setPixmap() [1/2]
void QCPScatterStyle::setPixmap (const QPixmap & pixmap)
Sets the pixmap that will be drawn as scatter point to pixmap.
Note that setSize does not influence the appearance of the pixmap.
The scatter shape is automatically set to ssPixmap.
Definition at line 10504 of file qcustomplot.cpp.
References mPixmap, pixmap(), setShape(), and ssPixmap.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), and setFromOther().
setPixmap() [2/2]
void QCPScatterStyle::setPixmap (const QPixmap & pixmap)
setShape() [1/2]
void QCPScatterStyle::setShape (QCPScatterStyle::ScatterShape shape)
Sets the shape to shape.
Note that the calls setPixmap and setCustomPath automatically set the shape to ssPixmap and ssCustom, respectively.
See also
setSize
Definition at line 10469 of file qcustomplot.cpp.
References mShape, and shape().
Referenced by setCustomPath(), setFromOther(), and setPixmap().
setShape() [2/2]
void QCPScatterStyle::setShape (ScatterShape shape)
setSize() [1/2]
void QCPScatterStyle::setSize (double size)
Sets the size (pixel diameter) of the drawn scatter points to size.
See also
setShape
Definition at line 10459 of file qcustomplot.cpp.
References mSize, and size().
Referenced by setFromOther().
setSize() [2/2]
void QCPScatterStyle::setSize (double size)
shape() [1/2]
ScatterShape QCPScatterStyle::shape () const inline
Definition at line 2804 of file qcustomplot.h.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), setFromOther(), and setShape().
shape() [2/2]
ScatterShape QCPScatterStyle::shape () const inline
Definition at line 428 of file qcustomplot.h.
size() [1/2]
double QCPScatterStyle::size () const inline
Definition at line 2803 of file qcustomplot.h.
Referenced by QCPCurve::draw(), QCPGraph::drawError(), QCPCurve::getCurveData(), setFromOther(), and setSize().
size() [2/2]
double QCPScatterStyle::size () const inline
Definition at line 427 of file qcustomplot.h.
undefinePen()
void QCPScatterStyle::undefinePen ()
Sets this scatter style to have an undefined pen (see isPenDefined for what an undefined pen implies).
A call to setPen will define a pen.
Definition at line 10525 of file qcustomplot.cpp.
References mPenDefined.
Referenced by setFromOther().
Member Data Documentation
mBrush
QBrush QCPScatterStyle::mBrush protected
Definition at line 2833 of file qcustomplot.h.
Referenced by applyTo(), and setBrush().
mCustomPath
QPainterPath QCPScatterStyle::mCustomPath protected
Definition at line 2835 of file qcustomplot.h.
Referenced by drawShape(), and setCustomPath().
mPen
QPen QCPScatterStyle::mPen protected
Definition at line 2832 of file qcustomplot.h.
Referenced by applyTo(), and setPen().
mPenDefined
bool QCPScatterStyle::mPenDefined protected
Definition at line 2838 of file qcustomplot.h.
Referenced by applyTo(), setPen(), and undefinePen().
mPixmap
QPixmap QCPScatterStyle::mPixmap protected
Definition at line 2834 of file qcustomplot.h.
Referenced by drawShape(), and setPixmap().
mShape
ScatterShape QCPScatterStyle::mShape protected
Definition at line 2831 of file qcustomplot.h.
Referenced by drawShape(), and setShape().
mSize
double QCPScatterStyle::mSize protected
Definition at line 2830 of file qcustomplot.h.
Referenced by drawShape(), and setSize().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp