ACloudViewer: BinaryNode Class Reference
BinaryNode Class Reference
#include <BinaryNode.h>
Static Public Member Functions
static int CenterCount (int depth)
static int CornerCount (int depth)
static int CumulativeCenterCount (int maxDepth)
static int CumulativeCornerCount (int maxDepth)
static int CenterIndex (int depth, int offSet)
static int CornerIndex (int depth, int offSet)
static int CornerIndex (int maxDepth, int depth, int offSet, int forwardCorner)
template<class Real >
static Real Width (int depth)
template<class Real >
static void CenterAndWidth (int depth, int offset, Real &center, Real &width)
template<class Real >
static void CornerAndWidth (int depth, int offset, Real &corner, Real &width)
template<class Real >
static void CenterAndWidth (int idx, Real &center, Real &width)
template<class Real >
static void CornerAndWidth (int idx, Real &corner, Real &width)
static void CenterDepthAndOffset (int idx, int &depth, int &offset)
static void CornerDepthAndOffset (int idx, int &depth, int &offset)
Detailed Description
Definition at line 32 of file BinaryNode.h.
Member Function Documentation
CenterAndWidth() [1/2]
template<class Real > static void BinaryNode::CenterAndWidth (int depth, int offset, Real & center, Real & width) inline static
Definition at line 44 of file BinaryNode.h.
References offset, and width.
Referenced by CenterAndWidth().
CenterAndWidth() [2/2]
template<class Real > static void BinaryNode::CenterAndWidth (int idx, Real & center, Real & width) inline static
Definition at line 46 of file BinaryNode.h.
References CenterAndWidth(), CenterDepthAndOffset(), offset, and width.
CenterCount()
static int BinaryNode::CenterCount (int depth) inline static
Definition at line 35 of file BinaryNode.h.
Referenced by BSplineData< Degree >::TotalSampleCount().
CenterDepthAndOffset()
static void BinaryNode::CenterDepthAndOffset (int idx, int & depth, int & offset) inline static
Definition at line 58 of file BinaryNode.h.
References offset.
Referenced by CenterAndWidth(), and BSplineData< Degree >::FactorFunctionIndex().
CenterIndex()
static int BinaryNode::CenterIndex (int depth, int offSet) inline static
Definition at line 39 of file BinaryNode.h.
Referenced by BSplineData< Degree >::FunctionIndex().
CornerAndWidth() [1/2]
template<class Real > static void BinaryNode::CornerAndWidth (int depth, int offset, Real & corner, Real & width) inline static
Definition at line 45 of file BinaryNode.h.
References offset, and width.
Referenced by CornerAndWidth().
CornerAndWidth() [2/2]
template<class Real > static void BinaryNode::CornerAndWidth (int idx, Real & corner, Real & width) inline static
Definition at line 52 of file BinaryNode.h.
References CornerAndWidth(), CornerDepthAndOffset(), offset, and width.
CornerCount()
static int BinaryNode::CornerCount (int depth) inline static
Definition at line 36 of file BinaryNode.h.
Referenced by BSplineData< Degree >::TotalSampleCount().
CornerDepthAndOffset()
static void BinaryNode::CornerDepthAndOffset (int idx, int & depth, int & offset) inline static
Definition at line 63 of file BinaryNode.h.
References offset.
Referenced by CornerAndWidth(), and BSplineData< Degree >::FactorFunctionIndex().
CornerIndex() [1/2]
static int BinaryNode::CornerIndex (int depth, int offSet) inline static
Definition at line 40 of file BinaryNode.h.
Referenced by BSplineData< Degree >::FunctionIndex().
CornerIndex() [2/2]
static int BinaryNode::CornerIndex (int maxDepth, int depth, int offSet, int forwardCorner) inline static
Definition at line 42 of file BinaryNode.h.
CumulativeCenterCount()
static int BinaryNode::CumulativeCenterCount (int maxDepth) inline static
Definition at line 37 of file BinaryNode.h.
Referenced by BSplineData< Degree >::TotalFunctionCount().
CumulativeCornerCount()
static int BinaryNode::CumulativeCornerCount (int maxDepth) inline static
Definition at line 38 of file BinaryNode.h.
Referenced by BSplineData< Degree >::TotalFunctionCount().
Width()
template<class Real > static Real BinaryNode::Width (int depth) inline static
Definition at line 43 of file BinaryNode.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/BinaryNode.h