ACloudViewer: cloudViewer::t::geometry::kernel::TArrayIndexer< index_t > Class Template Reference
cloudViewer::t::geometry::kernel::TArrayIndexer< index_t > Class Template Reference
#include <GeometryIndexer.h>
Public Member Functions
TArrayIndexer ()
TArrayIndexer (const core::Tensor &ndarray, index_t active_dims)
TArrayIndexer (const core::SizeVector &shape)
Only used for simple shapes.
CLOUDVIEWER_HOST_DEVICE index_t ElementByteSize ()
CLOUDVIEWER_HOST_DEVICE index_t NumElements ()
CLOUDVIEWER_HOST_DEVICE void CoordToWorkload (index_t x_in, index_t y_in, index_t *workload) const
2D coordinate => workload
CLOUDVIEWER_HOST_DEVICE void CoordToWorkload (index_t x_in, index_t y_in, index_t z_in, index_t *workload) const
3D coordinate => workload
CLOUDVIEWER_HOST_DEVICE void CoordToWorkload (index_t x_in, index_t y_in, index_t z_in, index_t t_in, index_t *workload) const
4D coordinate => workload
CLOUDVIEWER_HOST_DEVICE void WorkloadToCoord (index_t workload, index_t *x_out, index_t *y_out) const
Workload => 2D coordinate.
CLOUDVIEWER_HOST_DEVICE void WorkloadToCoord (index_t workload, index_t *x_out, index_t *y_out, index_t *z_out) const
Workload => 3D coordinate.
CLOUDVIEWER_HOST_DEVICE void WorkloadToCoord (index_t workload, index_t *x_out, index_t *y_out, index_t *z_out, index_t *t_out) const
Workload => 4D coordinate.
CLOUDVIEWER_HOST_DEVICE bool InBoundary (float x, float y) const
CLOUDVIEWER_HOST_DEVICE bool InBoundary (float x, float y, float z) const
CLOUDVIEWER_HOST_DEVICE bool InBoundary (float x, float y, float z, float t) const
CLOUDVIEWER_HOST_DEVICE index_t GetShape (int i) const
CLOUDVIEWER_HOST_DEVICE void * GetDataPtr () const
template<typename T >
CLOUDVIEWER_HOST_DEVICE T * GetDataPtr (index_t x) const
template<typename T >
CLOUDVIEWER_HOST_DEVICE T * GetDataPtr (index_t x, index_t y) const
template<typename T >
CLOUDVIEWER_HOST_DEVICE T * GetDataPtr (index_t x, index_t y, index_t z) const
template<typename T >
CLOUDVIEWER_HOST_DEVICE T * GetDataPtr (index_t x, index_t y, index_t z, index_t t) const
Detailed Description
template<typename index_t>
class cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >
Definition at line 162 of file GeometryIndexer.h.
Constructor & Destructor Documentation
TArrayIndexer() [1/3]
template<typename index_t > cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::TArrayIndexer () inline
Definition at line 164 of file GeometryIndexer.h.
References cloudViewer::t::geometry::kernel::MAX_RESOLUTION_DIMS.
TArrayIndexer() [2/3]
template<typename index_t > cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::TArrayIndexer (const core::Tensor & ndarray, index_t active_dims) inline
Definition at line 170 of file GeometryIndexer.h.
References cloudViewer::core::Dtype::ByteSize(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::IsContiguous(), LogError, cloudViewer::t::geometry::kernel::MAX_RESOLUTION_DIMS, and cloudViewer::core::Tensor::NumDims().
TArrayIndexer() [3/3]
template<typename index_t > cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::TArrayIndexer (const core::SizeVector & shape) inline
Only used for simple shapes.
Definition at line 204 of file GeometryIndexer.h.
References LogError, cloudViewer::t::geometry::kernel::MAX_RESOLUTION_DIMS, and cloudViewer::core::SmallVectorBase< Size_T >::size().
Member Function Documentation
CoordToWorkload() [1/3]
template<typename index_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::CoordToWorkload (index_t x_in, index_t y_in, index_t * workload) const inline
2D coordinate => workload
Definition at line 240 of file GeometryIndexer.h.
Referenced by cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr().
CoordToWorkload() [2/3]
template<typename index_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::CoordToWorkload (index_t x_in, index_t y_in, index_t z_in, index_t * workload) const inline
3D coordinate => workload
Definition at line 246 of file GeometryIndexer.h.
CoordToWorkload() [3/3]
template<typename index_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::CoordToWorkload (index_t x_in, index_t y_in, index_t z_in, index_t t_in, index_t * workload) const inline
4D coordinate => workload
Definition at line 252 of file GeometryIndexer.h.
ElementByteSize()
template<typename index_t > CLOUDVIEWER_HOST_DEVICE index_t cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::ElementByteSize () inline
Definition at line 227 of file GeometryIndexer.h.
GetDataPtr() [1/5]
template<typename index_t > CLOUDVIEWER_HOST_DEVICE void* cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr () const inline
Definition at line 318 of file GeometryIndexer.h.
Referenced by cloudViewer::t::geometry::kernel::image::CreateNormalMapCPU(), cloudViewer::t::geometry::kernel::image::CreateVertexMapCPU(), cloudViewer::t::geometry::kernel::voxel_grid::DeviceGetLinearIdx(), cloudViewer::t::geometry::kernel::voxel_grid::EstimateRangeCPU(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractPointCloudCPU(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractTriangleMeshCPU(), cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU(), cloudViewer::t::geometry::kernel::pointcloud::ProjectCPU(), cloudViewer::t::geometry::kernel::image::PyrDownDepthCPU(), cloudViewer::t::geometry::kernel::voxel_grid::RayCastCPU(), and cloudViewer::t::io::DepthNoiseSimulator::Simulate().
GetDataPtr() [2/5]
template<typename index_t > template<typename T > CLOUDVIEWER_HOST_DEVICE T* cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr (index_t x) const inline
Definition at line 321 of file GeometryIndexer.h.
GetDataPtr() [3/5]
template<typename index_t > template<typename T > CLOUDVIEWER_HOST_DEVICE T* cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr (index_t x, index_t y) const inline
Definition at line 327 of file GeometryIndexer.h.
References cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::CoordToWorkload().
GetDataPtr() [4/5]
template<typename index_t > template<typename T > CLOUDVIEWER_HOST_DEVICE T* cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr (index_t x, index_t y, index_t z) const inline
Definition at line 335 of file GeometryIndexer.h.
References cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::CoordToWorkload().
GetDataPtr() [5/5]
template<typename index_t > template<typename T > CLOUDVIEWER_HOST_DEVICE T* cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr (index_t x, index_t y, index_t z, index_t t) const inline
Definition at line 345 of file GeometryIndexer.h.
References cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::CoordToWorkload().
GetShape()
template<typename index_t > CLOUDVIEWER_HOST_DEVICE index_t cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetShape (int i) const inline
Definition at line 314 of file GeometryIndexer.h.
Referenced by cloudViewer::t::geometry::kernel::image::CreateNormalMapCPU(), cloudViewer::t::geometry::kernel::voxel_grid::DepthTouchCPU(), cloudViewer::t::geometry::kernel::image::PyrDownDepthCPU(), and cloudViewer::t::geometry::kernel::pointcloud::UnprojectCPU().
InBoundary() [1/3]
template<typename index_t > CLOUDVIEWER_HOST_DEVICE bool cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::InBoundary (float x, float y) const inline
Definition at line 295 of file GeometryIndexer.h.
Referenced by cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU(), and cloudViewer::t::geometry::kernel::pointcloud::ProjectCPU().
InBoundary() [2/3]
template<typename index_t > CLOUDVIEWER_HOST_DEVICE bool cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::InBoundary (float x, float y, float z) const inline
Definition at line 299 of file GeometryIndexer.h.
InBoundary() [3/3]
template<typename index_t > CLOUDVIEWER_HOST_DEVICE bool cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::InBoundary (float x, float y, float z, float t) const inline
Definition at line 305 of file GeometryIndexer.h.
NumElements()
template<typename index_t > CLOUDVIEWER_HOST_DEVICE index_t cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::NumElements () inline
Definition at line 231 of file GeometryIndexer.h.
WorkloadToCoord() [1/3]
template<typename index_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::WorkloadToCoord (index_t workload, index_t * x_out, index_t * y_out) const inline
Workload => 2D coordinate.
Definition at line 263 of file GeometryIndexer.h.
Referenced by cloudViewer::t::io::DepthNoiseSimulator::Simulate().
WorkloadToCoord() [2/3]
template<typename index_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::WorkloadToCoord (index_t workload, index_t * x_out, index_t * y_out, index_t * z_out) const inline
Workload => 3D coordinate.
Definition at line 271 of file GeometryIndexer.h.
WorkloadToCoord() [3/3]
template<typename index_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::WorkloadToCoord (index_t workload, index_t * x_out, index_t * y_out, index_t * z_out, index_t * t_out) const inline
Workload => 4D coordinate.
Definition at line 282 of file GeometryIndexer.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/t/geometry/kernel/GeometryIndexer.h