ACloudViewer: cloudViewer::core::sy::SYCLContext Class Reference
cloudViewer::core::sy::SYCLContext Class Reference
#include <SYCLContext.h>
Public Member Functions
SYCLContext (SYCLContext const &)=delete
void operator= (SYCLContext const &)=delete
bool IsAvailable ()
Returns true if there is at least one SYCL devices.
bool IsDeviceAvailable (const Device &device)
Returns true if the specified SYCL device is available.
std::vector< Device > GetAvailableSYCLDevices ()
Returns a list of all available SYCL devices.
sycl::queue GetDefaultQueue (const Device &device)
Get the default SYCL queue given an CloudViewer device.
SYCLDevice GetDeviceProperties (const Device &device)
Get SYCL device properties given an CloudViewer device.
Static Public Member Functions
static SYCLContext & GetInstance ()
Get singleton instance.
Detailed Description
Singleton SYCL context manager. It maintains:
A default queue for each SYCL device
Definition at line 41 of file SYCLContext.h.
Constructor & Destructor Documentation
SYCLContext()
cloudViewer::core::sy::SYCLContext::SYCLContext (SYCLContext const &) delete
Member Function Documentation
GetAvailableSYCLDevices()
std::vector< Device > cloudViewer::core::sy::SYCLContext::GetAvailableSYCLDevices ()
Returns a list of all available SYCL devices.
Definition at line 35 of file SYCLContext.cpp.
Referenced by cloudViewer::core::sy::GetAvailableSYCLDevices().
GetDefaultQueue()
sycl::queue cloudViewer::core::sy::SYCLContext::GetDefaultQueue (const Device & device)
Get the default SYCL queue given an CloudViewer device.
Definition at line 43 of file SYCLContext.cpp.
Referenced by cloudViewer::core::AddMMSYCL(), cloudViewer::core::kernel::ArangeSYCL(), cloudViewer::core::kernel::CopySYCL(), cloudViewer::core::kernel::IndexAddSYCL_(), cloudViewer::core::kernel::IndexGetSYCL(), cloudViewer::core::kernel::IndexSetSYCL(), cloudViewer::core::InverseSYCL(), cloudViewer::core::LeastSquaresSYCL(), cloudViewer::core::LUSYCL(), cloudViewer::core::MatmulSYCL(), cloudViewer::core::ParallelForSYCL(), cloudViewer::core::SolveSYCL(), cloudViewer::core::SVDSYCL(), and cloudViewer::core::TriuSYCL().
GetDeviceProperties()
SYCLDevice cloudViewer::core::sy::SYCLContext::GetDeviceProperties (const Device & device) inline
Get SYCL device properties given an CloudViewer device.
Definition at line 62 of file SYCLContext.h.
Referenced by cloudViewer::core::sy::GetDeviceType().
GetInstance()
SYCLContext & cloudViewer::core::sy::SYCLContext::GetInstance () static
Get singleton instance.
Definition at line 25 of file SYCLContext.cpp.
Referenced by cloudViewer::core::AddMMSYCL(), cloudViewer::core::kernel::ArangeSYCL(), cloudViewer::core::kernel::CopySYCL(), cloudViewer::core::sy::GetAvailableSYCLDevices(), cloudViewer::core::sy::GetDeviceType(), cloudViewer::core::kernel::IndexAddSYCL_(), cloudViewer::core::kernel::IndexGetSYCL(), cloudViewer::core::kernel::IndexSetSYCL(), cloudViewer::core::InverseSYCL(), cloudViewer::core::sy::IsAvailable(), cloudViewer::core::sy::IsDeviceAvailable(), cloudViewer::core::LeastSquaresSYCL(), cloudViewer::core::LUSYCL(), cloudViewer::core::MatmulSYCL(), cloudViewer::core::ParallelForSYCL(), cloudViewer::core::SolveSYCL(), cloudViewer::core::SVDSYCL(), and cloudViewer::core::TriuSYCL().
IsAvailable()
bool cloudViewer::core::sy::SYCLContext::IsAvailable ()
Returns true if there is at least one SYCL devices.
Definition at line 30 of file SYCLContext.cpp.
Referenced by cloudViewer::core::sy::IsAvailable().
IsDeviceAvailable()
bool cloudViewer::core::sy::SYCLContext::IsDeviceAvailable (const Device & device)
Returns true if the specified SYCL device is available.
Definition at line 32 of file SYCLContext.cpp.
Referenced by cloudViewer::core::sy::IsDeviceAvailable().
operator=()
void cloudViewer::core::sy::SYCLContext::operator= (SYCLContext const &) delete
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/core/SYCLContext.h
/root/ACloudViewer/libs/cloudViewer/core/SYCLContext.cpp