ACloudViewer: ccOrderChoiceDlg Class Reference
ccOrderChoiceDlg Class Reference
Dialog to assign roles to two entities (e.g. compared/reference)
#include <ecvOrderChoiceDlg.h>
Public Member Functions
ccOrderChoiceDlg (ccHObject *firstEntity, QString firstRole, ccHObject *secondEntity, QString secondRole, ecvMainAppInterface *app=0)
Default constructor.
virtual ~ccOrderChoiceDlg ()
Destructor.
ccHObject * getFirstEntity ()
Returns the first entity (new order)
ccHObject * getSecondEntity ()
Returns the second entity (new order)
Protected Slots
void swap ()
Swaps the entities.
Protected Member Functions
void setColorsAndLabels ()
Sets the right colors to the entities and updates the dialog.
Protected Attributes
Ui_RoleChoiceDialog * m_gui
ecvMainAppInterface * m_app
ccHObject * m_firstEnt
ccHObject * m_secondEnt
bool m_useInputOrder
Detailed Description
Dialog to assign roles to two entities (e.g. compared/reference)
Definition at line 18 of file ecvOrderChoiceDlg.h.
Constructor & Destructor Documentation
ccOrderChoiceDlg()
ccOrderChoiceDlg::ccOrderChoiceDlg (ccHObject * firstEntity, QString firstRole, ccHObject * secondEntity, QString secondRole, ecvMainAppInterface * app = 0)
Default constructor.
Definition at line 26 of file ecvOrderChoiceDlg.cpp.
References m_gui, ecvColor::red(), ccQtHelpers::SetButtonColor(), setColorsAndLabels(), swap(), and ecvColor::yellow().
~ccOrderChoiceDlg()
ccOrderChoiceDlg::~ccOrderChoiceDlg () virtual
Destructor.
Definition at line 51 of file ecvOrderChoiceDlg.cpp.
References ccDrawableObject::enableTempColor(), m_app, m_firstEnt, m_gui, m_secondEnt, ecvMainAppInterface::refreshAll(), and ecvDisplayTools::SetRedrawRecursive().
Member Function Documentation
getFirstEntity()
ccHObject * ccOrderChoiceDlg::getFirstEntity ()
Returns the first entity (new order)
Definition at line 72 of file ecvOrderChoiceDlg.cpp.
References m_firstEnt, m_secondEnt, and m_useInputOrder.
Referenced by ccEntityAction::interpolateSFs(), and setColorsAndLabels().
getSecondEntity()
ccHObject * ccOrderChoiceDlg::getSecondEntity ()
Returns the second entity (new order)
Definition at line 76 of file ecvOrderChoiceDlg.cpp.
References m_firstEnt, m_secondEnt, and m_useInputOrder.
Referenced by setColorsAndLabels().
setColorsAndLabels()
void ccOrderChoiceDlg::setColorsAndLabels () protected
Sets the right colors to the entities and updates the dialog.
Definition at line 80 of file ecvOrderChoiceDlg.cpp.
References getFirstEntity(), ccObject::getName(), getSecondEntity(), m_app, m_gui, ecvColor::red(), ecvMainAppInterface::refreshAll(), ccObject::setEnabled(), ecvDisplayTools::SetRedrawRecursive(), ccDrawableObject::setTempColor(), ccDrawableObject::setVisible(), and ecvColor::yellow().
Referenced by ccOrderChoiceDlg(), and swap().
swap
void ccOrderChoiceDlg::swap () protected slot
Swaps the entities.
Definition at line 109 of file ecvOrderChoiceDlg.cpp.
References m_useInputOrder, and setColorsAndLabels().
Referenced by ccOrderChoiceDlg().
Member Data Documentation
m_app
ecvMainAppInterface* ccOrderChoiceDlg::m_app protected
Definition at line 47 of file ecvOrderChoiceDlg.h.
Referenced by setColorsAndLabels(), and ~ccOrderChoiceDlg().
m_firstEnt
ccHObject* ccOrderChoiceDlg::m_firstEnt protected
Definition at line 48 of file ecvOrderChoiceDlg.h.
Referenced by getFirstEntity(), getSecondEntity(), and ~ccOrderChoiceDlg().
m_gui
Ui_RoleChoiceDialog* ccOrderChoiceDlg::m_gui protected
Definition at line 46 of file ecvOrderChoiceDlg.h.
Referenced by ccOrderChoiceDlg(), setColorsAndLabels(), and ~ccOrderChoiceDlg().
m_secondEnt
ccHObject* ccOrderChoiceDlg::m_secondEnt protected
Definition at line 49 of file ecvOrderChoiceDlg.h.
Referenced by getFirstEntity(), getSecondEntity(), and ~ccOrderChoiceDlg().
m_useInputOrder
bool ccOrderChoiceDlg::m_useInputOrder protected
Definition at line 50 of file ecvOrderChoiceDlg.h.
Referenced by getFirstEntity(), getSecondEntity(), and swap().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvOrderChoiceDlg.h
/root/ACloudViewer/app/ecvOrderChoiceDlg.cpp