ACloudViewer: cloudViewer::LogWidget Class Reference
cloudViewer::LogWidget Class Reference
#include <LogWidget.h>
Public Member Functions
LogWidget (QWidget *parent, const int max_num_blocks=100000)
~LogWidget ()
void Append (const std::string &text)
void Flush ()
void Clear ()
Detailed Description
Definition at line 49 of file LogWidget.h.
Constructor & Destructor Documentation
LogWidget()
cloudViewer::LogWidget::LogWidget (QWidget * parent, const int max_num_blocks = 100000)
Definition at line 20 of file LogWidget.cpp.
References Clear(), and Flush().
~LogWidget()
cloudViewer::LogWidget::~LogWidget ()
Definition at line 71 of file LogWidget.cpp.
References CVLog::LOG_STANDARD, and CVLog::LogMessage().
Member Function Documentation
Append()
void cloudViewer::LogWidget::Append (const std::string & text)
Definition at line 89 of file LogWidget.cpp.
References QtCompatRegExpOption::CaseInsensitive, CVLog::LOG_ERROR, CVLog::LOG_STANDARD, CVLog::LOG_WARNING, CVLog::LogMessage(), and qtCompatRegExpMatch().
Clear()
void cloudViewer::LogWidget::Clear ()
Definition at line 184 of file LogWidget.cpp.
Referenced by LogWidget().
Flush()
void cloudViewer::LogWidget::Flush ()
Definition at line 172 of file LogWidget.cpp.
Referenced by LogWidget().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/reconstruction/LogWidget.h
/root/ACloudViewer/app/reconstruction/LogWidget.cpp