ACloudViewer: SiftGPUEX Class Reference
SiftGPUEX Class Reference
#include <SiftGPU.h>
Public Member Functions
SiftGPUEX ()
void SetView (int view, int sub_view, char *title)
void DisplaySIFT ()
void ToggleDisplayDebug ()
void RandomizeColor ()
void GetImageDimension (int &w, int &h)
void GetInitWindowPotition (int &x, int &y)
Public Member Functions inherited from SiftGPU
const char * GetCurrentImagePath ()
virtual void SetImageList (int nimage, const char **filelist)
virtual int GetFeatureNum ()
virtual void SaveSIFT (const char *szFileName)
virtual void GetFeatureVector (SiftKeypoint *keys, float *descriptors)
virtual void SetKeypointList (int num, const SiftKeypoint *keys, int keys_have_orientation=1)
virtual int CreateContextGL ()
virtual int VerifyContextGL ()
virtual int IsFullSupported ()
virtual void SetVerbose (int verbose=4)
void SetVerboseBrief ()
virtual void ParseParam (int argc, const char **argv)
virtual int RunSIFT (const char *imgpath)
virtual int RunSIFT (int index)
virtual int RunSIFT (int width, int height, const void *data, unsigned int gl_format, unsigned int gl_type)
virtual int RunSIFT ()
virtual int RunSIFT (int num, const SiftKeypoint *keys, int keys_have_orientation=1)
SiftGPU (int np=1)
virtual ~SiftGPU ()
virtual void SetActivePyramid (int)
virtual int GetImageCount ()
virtual void SetTightPyramid (int tight=1)
virtual int AllocatePyramid (int width, int height)
virtual void SetMaxDimension (int sz)
int GetFeatureCountThreshold ()
int GetMaxOrientation ()
int GetMaxDimension ()
Public Member Functions inherited from SiftParam
void ParseSiftParam ()
float GetLevelSigma (int lev)
float GetInitialSmoothSigma (int octave_min)
SiftParam ()
Additional Inherited Members
Public Types inherited from SiftGPU
enum { SIFTGPU_NOT_SUPPORTED = 0 , SIFTGPU_PARTIAL_SUPPORTED = 1 , SIFTGPU_FULL_SUPPORTED = 2 }
typedef struct SiftGPU::SiftKeypoint SiftKeypoint
Public Attributes inherited from SiftGPU
int gpu_index = 0
float _timing [10]
Public Attributes inherited from SiftParam
float * _sigma
float _sigma_skip0
float _sigma_skip1
float _sigma0
float _sigman
int _sigma_num
int _dog_level_num
int _level_num
int _level_min
int _level_max
int _level_ds
float _dog_threshold
float _edge_threshold
Protected Member Functions inherited from SiftGPU
void InitSiftGPU ()
void LoadImageList (const char *imlist)
Static Protected Member Functions inherited from SiftGPU
static void PrintUsage ()
Protected Attributes inherited from SiftGPU
int _current
int _initialized
int _image_loaded
char * _imgpath
char * _outpath
ImageList * _list
GLTexInput * _texImage
SiftPyramid * _pyramid
Detailed Description
Definition at line 227 of file SiftGPU.h.
Constructor & Destructor Documentation
SiftGPUEX()
SiftGPUEX::SiftGPUEX ()
Definition at line 99 of file SiftGPU.cpp.
References GlobalParam::_UseSiftGPUEX, and NULL.
Member Function Documentation
DisplaySIFT()
void SiftGPUEX::DisplaySIFT ()
Definition at line 601 of file SiftGPU.cpp.
References GlobalParam::_texTarget, SiftPyramid::DATA_DOG, SiftPyramid::DATA_GAUSSIAN, SiftPyramid::DATA_GRAD, SiftPyramid::DATA_KEYPOINT, NULL, ShaderMan::UseShaderDisplayDOG(), ShaderMan::UseShaderDisplayGaussian(), ShaderMan::UseShaderDisplayGrad(), and ShaderMan::UseShaderDisplayKeypoints().
GetImageDimension()
void SiftGPUEX::GetImageDimension (int & w, int & h)
Definition at line 1413 of file SiftGPU.cpp.
GetInitWindowPotition()
void SiftGPUEX::GetInitWindowPotition (int & x, int & y)
Definition at line 1420 of file SiftGPU.cpp.
References GlobalParam::_WindowInitX, and GlobalParam::_WindowInitY.
RandomizeColor()
void SiftGPUEX::RandomizeColor ()
Definition at line 109 of file SiftGPU.cpp.
SetView()
void SiftGPUEX::SetView (int view, int sub_view, char * title)
Definition at line 633 of file SiftGPU.cpp.
ToggleDisplayDebug()
void SiftGPUEX::ToggleDisplayDebug ()
Definition at line 1259 of file SiftGPU.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/SiftGPU.h
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/SiftGPU.cpp