ACloudViewer: ccWaveDialog Class Reference
ccWaveDialog Class Reference
Waveform dialog.
#include <ecvWaveformDialog.h>
Public Member Functions
ccWaveDialog (ccPointCloud *cloud, ccPickingHub *pickingHub, QWidget *parent=nullptr)
Default constructor.
~ccWaveDialog () override
Destructor.
ccWaveWidget * waveWidget ()
Returns the encapsulated widget.
virtual void onItemPicked (const PickedItem &pi) override
Method called whenever an item is picked.
Public Member Functions inherited from ccPickingListener
virtual ~ccPickingListener ()=default
Protected Member Functions
void onPointIndexChanged (int)
void updateCurrentWaveform ()
void onPointPickingButtonToggled (bool)
void onExportWaveAsCSV ()
Protected Attributes
ccPointCloud * m_cloud
Associated point cloud.
ccWaveWidget * m_widget
Wave widget.
ccPickingHub * m_pickingHub
Picking hub.
Ui_WaveDialog * m_gui
GUI.
double m_waveMax
Maximum wave amplitude (for all points)
Detailed Description
Waveform dialog.
Definition at line 96 of file ecvWaveformDialog.h.
Constructor & Destructor Documentation
ccWaveDialog()
ccWaveDialog::ccWaveDialog (ccPointCloud * cloud, ccPickingHub * pickingHub, QWidget * parent = nullptr) explicit
Default constructor.
Definition at line 308 of file ecvWaveformDialog.cpp.
References ccPointCloud::computeFWFAmplitude(), ccObject::getName(), m_gui, m_waveMax, m_widget, onExportWaveAsCSV(), onPointIndexChanged(), onPointPickingButtonToggled(), CVLog::Print(), cloudViewer::PointCloudTpl< T >::size(), updateCurrentWaveform(), and CVLog::Warning().
~ccWaveDialog()
ccWaveDialog::~ccWaveDialog () override
Destructor.
Definition at line 361 of file ecvWaveformDialog.cpp.
References m_gui.
Member Function Documentation
onExportWaveAsCSV()
void ccWaveDialog::onExportWaveAsCSV () protected
Definition at line 412 of file ecvWaveformDialog.cpp.
References ecvPS::CurrentPath(), ecvFileUtils::defaultDocPath(), filename, ccWaveformProxy::isValid(), m_cloud, m_gui, ccWaveformProxy::numberOfSamples(), ecvPS::SaveFile(), ccWaveformProxy::toASCII(), ccPointCloud::waveformProxy(), and ccPointCloud::waveforms().
Referenced by ccWaveDialog().
onItemPicked()
void ccWaveDialog::onItemPicked (const PickedItem & pi) override virtual
Method called whenever an item is picked.
Implements ccPickingListener.
Definition at line 380 of file ecvWaveformDialog.cpp.
References ccPickingListener::PickedItem::entity, ccPickingListener::PickedItem::entityCenter, ccPickingListener::PickedItem::itemIndex, m_cloud, and m_gui.
onPointIndexChanged()
void ccWaveDialog::onPointIndexChanged (int index) protected
Definition at line 363 of file ecvWaveformDialog.cpp.
References ccWaveWidget::init(), m_cloud, m_gui, m_waveMax, m_widget, and ccWaveWidget::refresh().
Referenced by ccWaveDialog(), and updateCurrentWaveform().
onPointPickingButtonToggled()
void ccWaveDialog::onPointPickingButtonToggled (bool state) protected
Definition at line 391 of file ecvWaveformDialog.cpp.
References ccPickingHub::addListener(), CVLog::Error(), m_gui, m_pickingHub, and ccPickingHub::removeListener().
Referenced by ccWaveDialog().
updateCurrentWaveform()
void ccWaveDialog::updateCurrentWaveform () protected
Definition at line 387 of file ecvWaveformDialog.cpp.
References m_gui, and onPointIndexChanged().
Referenced by ccWaveDialog().
waveWidget()
ccWaveWidget* ccWaveDialog::waveWidget () inline
Returns the encapsulated widget.
Definition at line 108 of file ecvWaveformDialog.h.
References m_widget.
Member Data Documentation
m_cloud
ccPointCloud* ccWaveDialog::m_cloud protected
Associated point cloud.
Definition at line 121 of file ecvWaveformDialog.h.
Referenced by onExportWaveAsCSV(), onItemPicked(), and onPointIndexChanged().
m_gui
Ui_WaveDialog* ccWaveDialog::m_gui protected
GUI.
Definition at line 130 of file ecvWaveformDialog.h.
Referenced by ccWaveDialog(), onExportWaveAsCSV(), onItemPicked(), onPointIndexChanged(), onPointPickingButtonToggled(), updateCurrentWaveform(), and ~ccWaveDialog().
m_pickingHub
ccPickingHub* ccWaveDialog::m_pickingHub protected
Picking hub.
Definition at line 127 of file ecvWaveformDialog.h.
Referenced by onPointPickingButtonToggled().
m_waveMax
double ccWaveDialog::m_waveMax protected
Maximum wave amplitude (for all points)
Definition at line 133 of file ecvWaveformDialog.h.
Referenced by ccWaveDialog(), and onPointIndexChanged().
m_widget
ccWaveWidget* ccWaveDialog::m_widget protected
Wave widget.
Definition at line 124 of file ecvWaveformDialog.h.
Referenced by ccWaveDialog(), onPointIndexChanged(), and waveWidget().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvWaveformDialog.h
/root/ACloudViewer/app/ecvWaveformDialog.cpp