ACloudViewer: ccContourExtractorDlg Class Reference
ccContourExtractorDlg Class Reference
Dialog for debugging contour extraction.
#include <ecvContourExtractorDlg.h>
Public Member Functions
ccContourExtractorDlg (QWidget *parent=0)
Default constructor.
void init ()
Initializes the display.
void displayMessage (QString message, bool waitForUserConfirmation=false)
Display a new message.
void waitForUser (unsigned defaultDelay_ms=100)
Waits for user action.
QMainWindow * win ()
Returns associated GL window.
void zoomOn (const ccBBox &bbox)
Zooms on a given 2D region (3D bouding-box considered in 2D only)
void refresh ()
Forces refresh.
void addToDisplay (ccHObject *obj, bool noDependency=true)
Adds an entity to the (2D/3D) display.
void removFromDisplay (ccHObject *obj)
Removes an entity from the (2D/3D) display.
bool isSkipped () const
Returns whether the dialog has been 'skipped' or not.
Protected Slots
void onSkipButtonClicked ()
When the skip button is clicked.
Protected Attributes
bool m_skipped
Skip flag.
QEventLoop m_loop
Local event loop.
Detailed Description
Dialog for debugging contour extraction.
Definition at line 25 of file ecvContourExtractorDlg.h.
Constructor & Destructor Documentation
ccContourExtractorDlg()
ccContourExtractorDlg::ccContourExtractorDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 25 of file ecvContourExtractorDlg.cpp.
Member Function Documentation
addToDisplay()
void ccContourExtractorDlg::addToDisplay (ccHObject * obj, bool noDependency = true)
Adds an entity to the (2D/3D) display.
Definition at line 83 of file ecvContourExtractorDlg.cpp.
References ecvDisplayTools::AddToOwnDB().
Referenced by ccContourExtractor::ExtractConcaveHull2D().
displayMessage()
void ccContourExtractorDlg::displayMessage (QString message, bool waitForUserConfirmation = false)
Display a new message.
Definition at line 102 of file ecvContourExtractorDlg.cpp.
References m_skipped, and waitForUser().
Referenced by ccContourExtractor::ExtractConcaveHull2D().
init()
void ccContourExtractorDlg::init ()
Initializes the display.
Definition at line 32 of file ecvContourExtractorDlg.cpp.
References ecvColor::black(), ecvDisplayTools::DisplayOverlayEntities(), ecvDisplayTools::GetDisplayParameters(), ecvDisplayTools::GetMainWindow(), ecvDisplayTools::INTERACT_CLICKABLE_ITEMS, ecvDisplayTools::INTERACT_PAN, ecvDisplayTools::INTERACT_ZOOM_CAMERA, m_loop, ecvDisplayTools::NO_PICKING, onSkipButtonClicked(), params, ecvDisplayTools::SetDisplayParameters(), ecvDisplayTools::SetInteractionMode(), ecvDisplayTools::SetPerspectiveState(), ecvDisplayTools::SetPickingMode(), and ecvColor::white().
Referenced by ccContourExtractor::ExtractConcaveHull2D().
isSkipped()
bool ccContourExtractorDlg::isSkipped () const
Returns whether the dialog has been 'skipped' or not.
Definition at line 79 of file ecvContourExtractorDlg.cpp.
Referenced by ccContourExtractor::ExtractConcaveHull2D().
onSkipButtonClicked
void ccContourExtractorDlg::onSkipButtonClicked () protected slot
When the skip button is clicked.
Definition at line 109 of file ecvContourExtractorDlg.cpp.
References m_skipped.
Referenced by init().
refresh()
void ccContourExtractorDlg::refresh ()
Forces refresh.
Definition at line 96 of file ecvContourExtractorDlg.cpp.
References m_skipped, and ecvDisplayTools::RedrawDisplay().
Referenced by ccContourExtractor::ExtractConcaveHull2D().
removFromDisplay()
void ccContourExtractorDlg::removFromDisplay (ccHObject * obj)
Removes an entity from the (2D/3D) display.
Definition at line 90 of file ecvContourExtractorDlg.cpp.
References ecvDisplayTools::RemoveFromOwnDB().
Referenced by ccContourExtractor::ExtractConcaveHull2D().
waitForUser()
void ccContourExtractorDlg::waitForUser (unsigned defaultDelay_ms = 100)
Waits for user action.
Definition at line 115 of file ecvContourExtractorDlg.cpp.
References m_loop, m_skipped, and cloudViewer::utility::Sleep().
Referenced by displayMessage().
win()
QMainWindow* ccContourExtractorDlg::win () inline
Returns associated GL window.
Definition at line 42 of file ecvContourExtractorDlg.h.
References ecvDisplayTools::GetMainWindow().
zoomOn()
void ccContourExtractorDlg::zoomOn (const ccBBox & bbox)
Zooms on a given 2D region (3D bouding-box considered in 2D only)
Definition at line 68 of file ecvContourExtractorDlg.cpp.
References Vector3Tpl< double >::fromArray(), cloudViewer::BoundingBoxTpl< T >::getCenter(), cloudViewer::BoundingBoxTpl< T >::getDiagVec(), ecvDisplayTools::GetScreenRect(), max(), ecvDisplayTools::SetCameraPos(), ecvDisplayTools::SetPixelSize(), Tuple3Tpl< Type >::u, Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
Referenced by ccContourExtractor::ExtractConcaveHull2D().
Member Data Documentation
m_loop
QEventLoop ccContourExtractorDlg::m_loop protected
Local event loop.
Definition at line 67 of file ecvContourExtractorDlg.h.
Referenced by init(), and waitForUser().
m_skipped
bool ccContourExtractorDlg::m_skipped protected
Skip flag.
Definition at line 65 of file ecvContourExtractorDlg.h.
Referenced by displayMessage(), onSkipButtonClicked(), refresh(), and waitForUser().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvContourExtractorDlg.h
/root/ACloudViewer/app/ecvContourExtractorDlg.cpp