ACloudViewer: cloudViewer::visualization::gui::PyWindow Class Reference
cloudViewer::visualization::gui::PyWindow Class Reference
Public Member Functions
PyWindow (const std::string &title, int flags=0)
PyWindow (const std::string &title, int width, int height, int flags=0)
PyWindow (const std::string &title, int x, int y, int width, int height, int flags=0)
Public Member Functions inherited from cloudViewer::visualization::gui::Window
Window (const std::string &title, int flags=0)
Window (const std::string &title, int width, int height, int flags=0)
Window (const std::string &title, int x, int y, int width, int height, int flags=0)
virtual ~Window ()
const Theme & GetTheme () const
visualization::rendering::Renderer & GetRenderer () const
Rect GetOSFrame () const
void SetOSFrame (const Rect &r)
const char * GetTitle () const
void SetTitle (const char *title)
void SizeToFit ()
void SetSize (const Size &size)
Sets the size of the window in pixels. Includes menubar on Linux.
Size GetSize () const
Rect GetContentRect () const
float GetScaling () const
Returns the scaling factor from OS pixels to device pixels.
Point GlobalToWindowCoord (int global_x, int global_y)
Returns the global point (in OS pixels) in window local coordinates.
bool IsVisible () const
void Show (bool vis=true)
void Close ()
void SetNeedsLayout ()
Instructs the window to relayout before the next draw.
void PostRedraw ()
void SetTopmost (bool topmost)
void RaiseToTop () const
bool IsActiveWindow () const
void SetFocusWidget (Widget *w)
Sets.
void AddChild (std::shared_ptr< Widget > w)
void SetOnMenuItemActivated (Menu::ItemId item_id, std::function< void()> callback)
void SetOnTickEvent (std::function< bool()> callback)
void SetOnClose (std::function< bool()> callback)
void SetOnKeyEvent (std::function< bool(const KeyEvent &)> callback)
void ShowDialog (std::shared_ptr< Dialog > dlg)
void CloseDialog ()
Closes the dialog.
void ShowMessageBox (const char *title, const char *message)
void DestroyWindow ()
virtual void OnMenuItemSelected (Menu::ItemId item_id)
virtual void OnDragDropped (const char *path)
void ShowMenu (bool show)
int GetMouseMods () const
std::string GetWebRTCUID () const
void OnDraw ()
void OnResize ()
void OnMouseEvent (const MouseEvent &e)
void OnKeyEvent (const KeyEvent &e)
void OnTextInput (const TextInputEvent &e)
void OnTickEvent (const TickEvent &e)
WindowSystem::OSWindow GetOSWindow () const
Public Attributes
std::function< void(const LayoutContext &)> on_layout_
Protected Member Functions
void Layout (const LayoutContext &context) override
Protected Member Functions inherited from cloudViewer::visualization::gui::Window
virtual Size CalcPreferredSize ()
LayoutContext GetLayoutContext ()
const std::vector< std::shared_ptr< Widget > > & GetChildren () const
Additional Inherited Members
Static Public Attributes inherited from cloudViewer::visualization::gui::Window
static const int FLAG_HIDDEN = (1 << 0)
static const int FLAG_TOPMOST = (1 << 1)
Detailed Description
Definition at line 78 of file gui.cpp.
Constructor & Destructor Documentation
PyWindow() [1/3]
cloudViewer::visualization::gui::PyWindow::PyWindow (const std::string & title, int flags = 0) inline explicit
Definition at line 82 of file gui.cpp.
PyWindow() [2/3]
cloudViewer::visualization::gui::PyWindow::PyWindow (const std::string & title, int width, int height, int flags = 0) inline
Definition at line 84 of file gui.cpp.
PyWindow() [3/3]
cloudViewer::visualization::gui::PyWindow::PyWindow (const std::string & title, int x, int y, int width, int height, int flags = 0) inline
Definition at line 86 of file gui.cpp.
Member Function Documentation
Layout()
void cloudViewer::visualization::gui::PyWindow::Layout (const LayoutContext & context) inline override protected virtual
Lays out all the widgets in the window. If all children of the window are layouts, this function does not need to be overridden.
Reimplemented from cloudViewer::visualization::gui::Window.
Definition at line 97 of file gui.cpp.
References context, cloudViewer::visualization::gui::Window::GetChildren(), cloudViewer::visualization::gui::Window::Layout(), and on_layout_.
Member Data Documentation
on_layout_
std::function<void(const LayoutContext &)> cloudViewer::visualization::gui::PyWindow::on_layout_
Definition at line 94 of file gui.cpp.
Referenced by Layout(), and cloudViewer::visualization::gui::pybind_gui_classes().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Python/pybind/visualization/gui/gui.cpp