ACloudViewer: cloudViewer::t::io::RGBDVideoReader Class Reference
cloudViewer::t::io::RGBDVideoReader Class Reference abstract
#include <RGBDVideoReader.h>
Public Member Functions
RGBDVideoReader ()
virtual ~RGBDVideoReader ()
virtual bool IsOpened () const =0
Check If the RGBD video file is opened.
virtual bool IsEOF () const =0
Check if the RGBD video file is all read.
virtual bool Open (const std::string &filename)=0
virtual void Close ()=0
Close the opened RGBD video playback.
virtual RGBDVideoMetadata & GetMetadata ()=0
Get reference to the metadata of the RGBD video playback.
virtual const RGBDVideoMetadata & GetMetadata () const =0
Get metadata of the RGBD video playback.
virtual bool SeekTimestamp (uint64_t timestamp)=0
Seek to the timestamp (in us).
virtual uint64_t GetTimestamp () const =0
Get current timestamp (in us).
virtual t::geometry::RGBDImage NextFrame ()=0
Get next frame from the RGBD video playback and returns the RGBD object.
virtual void SaveFrames (const std::string &frame_path, uint64_t start_time_us=0, uint64_t end_time_us=UINT64_MAX)
virtual std::string GetFilename () const =0
Return filename being read.
virtual std::string ToString () const
Text description.
Static Public Member Functions
static std::unique_ptr< RGBDVideoReader > Create (const std::string &filename)
Factory function to create object based on RGBD video file type.
Detailed Description
Definition at line 18 of file RGBDVideoReader.h.
Constructor & Destructor Documentation
RGBDVideoReader()
cloudViewer::t::io::RGBDVideoReader::RGBDVideoReader () inline
Definition at line 20 of file RGBDVideoReader.h.
~RGBDVideoReader()
virtual cloudViewer::t::io::RGBDVideoReader::~RGBDVideoReader () inline virtual
Definition at line 21 of file RGBDVideoReader.h.
Member Function Documentation
Close()
virtual void cloudViewer::t::io::RGBDVideoReader::Close () pure virtual
Close the opened RGBD video playback.
Implemented in cloudViewer::t::io::RSBagReader.
Create()
std::unique_ptr< RGBDVideoReader > cloudViewer::t::io::RGBDVideoReader::Create (const std::string & filename) static
Factory function to create object based on RGBD video file type.
Definition at line 80 of file RGBDVideoReader.cpp.
References compare, filename, LogError, and cloudViewer::utility::ToLower().
GetFilename()
virtual std::string cloudViewer::t::io::RGBDVideoReader::GetFilename () const pure virtual
Return filename being read.
Implemented in cloudViewer::t::io::RSBagReader.
Referenced by ToString().
GetMetadata() [1/2]
virtual const RGBDVideoMetadata& cloudViewer::t::io::RGBDVideoReader::GetMetadata () const pure virtual
Get metadata of the RGBD video playback.
Implemented in cloudViewer::t::io::RSBagReader.
GetMetadata() [2/2]
virtual RGBDVideoMetadata& cloudViewer::t::io::RGBDVideoReader::GetMetadata () pure virtual
Get reference to the metadata of the RGBD video playback.
Implemented in cloudViewer::t::io::RSBagReader.
Referenced by SaveFrames(), and ToString().
GetTimestamp()
virtual uint64_t cloudViewer::t::io::RGBDVideoReader::GetTimestamp () const pure virtual
Get current timestamp (in us).
Implemented in cloudViewer::t::io::RSBagReader.
Referenced by SaveFrames(), and ToString().
IsEOF()
virtual bool cloudViewer::t::io::RGBDVideoReader::IsEOF () const pure virtual
Check if the RGBD video file is all read.
Implemented in cloudViewer::t::io::RSBagReader.
Referenced by SaveFrames().
IsOpened()
virtual bool cloudViewer::t::io::RGBDVideoReader::IsOpened () const pure virtual
Check If the RGBD video file is opened.
Implemented in cloudViewer::t::io::RSBagReader.
Referenced by SaveFrames(), and ToString().
NextFrame()
virtual t::geometry::RGBDImage cloudViewer::t::io::RGBDVideoReader::NextFrame () pure virtual
Get next frame from the RGBD video playback and returns the RGBD object.
Implemented in cloudViewer::t::io::RSBagReader.
Referenced by SaveFrames().
Open()
virtual bool cloudViewer::t::io::RGBDVideoReader::Open (const std::string & filename) pure virtual
Open an RGBD video playback.
Parameters
filename Path to the RGBD video file.
Implemented in cloudViewer::t::io::RSBagReader.
SaveFrames()
void cloudViewer::t::io::RGBDVideoReader::SaveFrames (const std::string & frame_path, uint64_t start_time_us = 0, uint64_t end_time_us = UINT64_MAX) virtual
Save synchronized and aligned individual frames to subfolders.
Parameters
frame_path Frames will be stored in stream subfolders 'color' and 'depth' here. The intrinsic camera calibration for the color stream will be saved in 'intrinsic.json'.
start_time_us (default 0) Start saving frames from this time (us)
end_time_us (default video length) Save frames till this time (us)
Definition at line 34 of file RGBDVideoReader.cpp.
References format, GetMetadata(), GetTimestamp(), IsEOF(), IsOpened(), LogError, cloudViewer::utility::filesystem::MakeDirectoryHierarchy(), NextFrame(), SeekTimestamp(), and cloudViewer::io::WriteIJsonConvertibleToJSON().
SeekTimestamp()
virtual bool cloudViewer::t::io::RGBDVideoReader::SeekTimestamp (uint64_t timestamp) pure virtual
Seek to the timestamp (in us).
Implemented in cloudViewer::t::io::RSBagReader.
Referenced by SaveFrames().
ToString()
std::string cloudViewer::t::io::RGBDVideoReader::ToString () const virtual
Text description.
Definition at line 23 of file RGBDVideoReader.cpp.
References format, GetFilename(), GetMetadata(), GetTimestamp(), and IsOpened().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/t/io/sensor/RGBDVideoReader.h
/root/ACloudViewer/libs/cloudViewer/t/io/sensor/RGBDVideoReader.cpp