ACloudViewer: ccMPlaneDlgController Class Reference
ccMPlaneDlgController Class Reference
#include <ccMPlaneDlgController.h>
Public Member Functions
ccMPlaneDlgController (ecvMainAppInterface *app)
void openDialog (ccPointCloud *selectedCloud)
Protected Slots
void onCloseButtonPressed ()
void onNewTab (int tabIndex)
void onMeasureNameChanged (QTableWidgetItem *)
void onMeasurementModeChanged ()
void onFittingPointDelete (int index)
void onNormalCheckBoxClicked (bool checked)
void onSaveButtonClicked ()
virtual void onItemPicked (const ccPickingListener::PickedItem &pi) override
Detailed Description
Definition at line 26 of file ccMPlaneDlgController.h.
Constructor & Destructor Documentation
ccMPlaneDlgController()
ccMPlaneDlgController::ccMPlaneDlgController (ecvMainAppInterface * app) explicit
Definition at line 20 of file ccMPlaneDlgController.cpp.
References onCloseButtonPressed(), onFittingPointDelete(), onMeasurementModeChanged(), onMeasureNameChanged(), onNewTab(), onNormalCheckBoxClicked(), onSaveButtonClicked(), ccMPlaneDlg::signalCloseButtonPressed(), ccMPlaneDlg::signalFittingPointDelete(), ccMPlaneDlg::signalMeasurementModeChanged(), ccMPlaneDlg::signalMeasureNameChanged(), ccMPlaneDlg::signalSaveButtonClicked(), ccMPlaneDlg::signalShowNormalCheckBoxClicked(), and ccMPlaneDlg::signalTabChanged().
Member Function Documentation
onCloseButtonPressed
void ccMPlaneDlgController::onCloseButtonPressed () protected slot
Definition at line 52 of file ccMPlaneDlgController.cpp.
References ccMPlaneDlg::clearFittingPoints(), and ccMPlaneDlg::clearMeasurementPoints().
Referenced by ccMPlaneDlgController().
onFittingPointDelete
void ccMPlaneDlgController::onFittingPointDelete (int index) protected slot
Definition at line 90 of file ccMPlaneDlgController.cpp.
References ccMPlaneDlg::selectFittingPoint().
Referenced by ccMPlaneDlgController().
onItemPicked
void ccMPlaneDlgController::onItemPicked (const ccPickingListener::PickedItem & pi) override protected virtual slot
Definition at line 131 of file ccMPlaneDlgController.cpp.
References ccObject::isKindOf(), CV_TYPES::POINT_CLOUD, ccMPlaneDlg::selectFittingPoint(), and sourceCloud.
onMeasurementModeChanged
void ccMPlaneDlgController::onMeasurementModeChanged () protected slot
Definition at line 84 of file ccMPlaneDlgController.cpp.
References ccMPlaneDlg::isSignedMeasurement().
Referenced by ccMPlaneDlgController().
onMeasureNameChanged
void ccMPlaneDlgController::onMeasureNameChanged (QTableWidgetItem * item) protected slot
Definition at line 72 of file ccMPlaneDlgController.cpp.
References ccMPlaneDlg::renameMeasurement().
Referenced by ccMPlaneDlgController().
onNewTab
void ccMPlaneDlgController::onNewTab (int tabIndex) protected slot
Definition at line 67 of file ccMPlaneDlgController.cpp.
Referenced by ccMPlaneDlgController().
onNormalCheckBoxClicked
void ccMPlaneDlgController::onNormalCheckBoxClicked (bool checked) protected slot
Definition at line 102 of file ccMPlaneDlgController.cpp.
References ecvDisplayTools::SetRedrawRecursive().
Referenced by ccMPlaneDlgController().
onSaveButtonClicked
void ccMPlaneDlgController::onSaveButtonClicked () protected slot
Definition at line 113 of file ccMPlaneDlgController.cpp.
References QtCompat::endl(), point::x, and point::y.
Referenced by ccMPlaneDlgController().
openDialog()
void ccMPlaneDlgController::openDialog (ccPointCloud * selectedCloud)
Definition at line 42 of file ccMPlaneDlgController.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qMPlane/src/ccMPlaneDlgController.h
/root/ACloudViewer/plugins/core/Standard/qMPlane/src/ccMPlaneDlgController.cpp