ACloudViewer: ccPropertiesTreeDelegate Class Reference
ccPropertiesTreeDelegate Class Reference
GUI properties list dialog element.
#include <ecvPropertiesTreeDelegate.h>
Public Types
enum CC_PROPERTY_ROLE {
OBJECT_NO_PROPERTY = 0 , OBJECT_NAME , OBJECT_VISIBILITY , OBJECT_OPACITY ,
OBJECT_CURRENT_DISPLAY , OBJECT_NORMALS_SHOWN , OBJECT_COLOR_SOURCE , OBJECT_POLYLINE_WIDTH ,
OBJECT_SENSOR_DRAW_FRUSTUM , OBJECT_SENSOR_DRAW_FRUSTUM_PLANES , OBJECT_SF_SHOW_SCALE , OBJECT_OCTREE_LEVEL ,
OBJECT_OCTREE_TYPE , OBJECT_MESH_WIRE , OBJECT_MESH_POINTS , OBJECT_MESH_STIPPLING ,
OBJECT_MESH_TEXTUREFILE , OBJECT_CURRENT_SCALAR_FIELD , OBJECT_CURRENT_COLOR_RAMP , OBJECT_IMAGE_ALPHA ,
OBJECT_APPLY_IMAGE_VIEWPORT , OBJECT_APPLY_SENSOR_VIEWPORT , OBJECT_CLOUD_SF_EDITOR , OBJECT_SENSOR_MATRIX_EDITOR ,
OBJECT_SENSOR_DISPLAY_SCALE , OBJECT_SENSOR_UNCERTAINTY , OBJECT_COLOR_RAMP_STEPS , OBJECT_MATERIALS ,
OBJECT_APPLY_LABEL_VIEWPORT , OBJECT_UPDATE_LABEL_VIEWPORT , OBJECT_LABEL_DISP_2D , OBJECT_LABEL_POINT_LEGEND ,
OBJECT_PRIMITIVE_PRECISION , OBJECT_CIRCLE_RESOLUTION , OBJECT_SPHERE_RADIUS , OBJECT_CIRCLE_RADIUS ,
OBJECT_DISC_RADIUS , OBJECT_CONE_HEIGHT , OBJECT_CONE_BOTTOM_RADIUS , OBJECT_CONE_TOP_RADIUS ,
OBJECT_CLOUD_POINT_SIZE , OBJECT_NAME_IN_3D , OBJECT_FACET_CONTOUR , OBJECT_FACET_MESH ,
OBJECT_PLANE_NORMAL_VECTOR , OBJECT_SENSOR_INDEX , OBJECT_SHOW_TRANS_BUFFER_PATH , OBJECT_SHOW_TRANS_BUFFER_TRIHDERONS ,
OBJECT_TRANS_BUFFER_TRIHDERONS_SCALE , OBJECT_HISTORY_MATRIX_EDITOR , OBJECT_GLTRANS_MATRIX_EDITOR , OBJECT_COORDINATE_SYSTEM_DISP_PLANES ,
OBJECT_COORDINATE_SYSTEM_DISP_AXES , OBJECT_COORDINATE_SYSTEM_AXES_WIDTH , OBJECT_COORDINATE_SYSTEM_DISP_SCALE , OBJECT_SELECTION_HOVER_COLOR ,
OBJECT_SELECTION_PRESELECTED_COLOR , OBJECT_SELECTION_SELECTED_COLOR , OBJECT_SELECTION_BOUNDARY_COLOR , OBJECT_SELECTION_HOVER_OPACITY ,
OBJECT_SELECTION_PRESELECTED_OPACITY , OBJECT_SELECTION_SELECTED_OPACITY , OBJECT_SELECTION_BOUNDARY_OPACITY , OBJECT_SELECTION_SHOW_TOOLTIPS ,
OBJECT_SELECTION_MAX_ATTRIBUTES , OBJECT_VIEW_USE_LIGHT_KIT , OBJECT_VIEW_LIGHT_KIT_INTENSITY , OBJECT_VIEW_DATA_AXES_GRID_VISIBLE ,
OBJECT_VIEW_DATA_AXES_GRID_EDIT , OBJECT_VIEW_CAMERA_ORIENTATION_WIDGET , OBJECT_VIEW_CENTER_AXES_VISIBILITY , TREE_VIEW_HEADER
}
Delegate items roles.
Signals
void ccObjectPropertiesChanged (ccHObject *hObject) const
void ccObjectAppearanceChanged (ccHObject *hObject, bool forceRedraw=true) const
void ccObjectAndChildrenAppearanceChanged (ccHObject *hObject, bool forceRedraw=true) const
void requestClearSelection () const
Request to clear all selection data (prevents crashes from stale references)
Public Member Functions
ccPropertiesTreeDelegate (QStandardItemModel *_model, QAbstractItemView *_view, QObject *parent=0)
Default constructor.
virtual ~ccPropertiesTreeDelegate ()
Default destructor.
virtual QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void updateEditorGeometry (QWidget *editor, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void setEditorData (QWidget *editor, const QModelIndex &index) const
virtual void unbind ()
void fillModel (ccHObject *hObject)
Fill property view with QItems corresponding to object's type.
ccHObject * getCurrentObject ()
Returns currently bound object.
void clearModel ()
Clear the model completely.
void setVisualizer (ecvGenericVisualizer3D *viewer)
Set visualizer for other property editors.
Protected Member Functions
void addSeparator (QString title)
void appendRow (QStandardItem *leftItem, QStandardItem *rightItem, bool openPersistentEditor=false)
void appendWideRow (QStandardItem *item, bool openPersistentEditor=true)
void fillWithHObject (ccHObject *)
void fillWithPointCloud (ccGenericPointCloud *)
void fillSFWithPointCloud (ccGenericPointCloud *)
void fillWithMesh (ccGenericMesh *)
void fillWithFacet (ccFacet *)
void fillWithPlanarEntity (ccPlanarEntityInterface *)
void fillWithSensor (ccSensor *)
void fillWithTransBuffer (ccIndexedTransformationBuffer *)
void fillWithPolyline (ccPolyline *)
void fillWithPrimitive (ccGenericPrimitive *)
void fillWithPointOctree (ccOctree *)
void fillWithPointKdTree (ccKdTree *)
void fillWithImage (ccImage *)
void fillWithLabel (cc2DLabel *)
void fillWithViewportObject (cc2DViewportObject *)
void fillWithGBLSensor (ccGBLSensor *)
void fillWithCameraSensor (ccCameraSensor *)
void fillWithMaterialSet (ccMaterialSet *)
void fillWithShareable (CCShareable *)
void fillWithMetaData (ccObject *)
void fillWithShifted (ccShiftedObject *)
void fillWithCoordinateSystem (const ccCoordinateSystem *)
void fillWithSelectionProperties ()
void fillWithViewProperties ()
template<class Type , int N, class ComponentType >
void fillWithCCArray (ccArray< Type, N, ComponentType > *)
bool isWideEditor (int itemData) const
Returns whether the editor is wide (i.e. spans on two columns) or not.
void updateModel ()
Updates the current model (assuming object is the same)
QMap< QString, QString > getCurrentMeshTexturePathMap () const
Get texture path map for current mesh object.
void clearMeshTexturePathMap (ccHObject *mesh)
Clear texture path map for a specific mesh object.
Protected Attributes
ccHObject * m_currentObject
QStandardItemModel * m_model
QAbstractItemView * m_view
QMap< ccHObject *, QMap< QString, QString > > m_meshTexturePathMaps
ecvGenericVisualizer3D * m_viewer
Visualizer for other property editors.
CC_PROPERTY_ROLE m_lastFocusItemRole
Last focused item role (used to force scroll focus after model update)
Detailed Description
GUI properties list dialog element.
Definition at line 45 of file ecvPropertiesTreeDelegate.h.
Member Enumeration Documentation
CC_PROPERTY_ROLE
enum ccPropertiesTreeDelegate::CC_PROPERTY_ROLE
Delegate items roles.
Enumerator
OBJECT_NO_PROPERTY
OBJECT_NAME
OBJECT_VISIBILITY
OBJECT_OPACITY
OBJECT_CURRENT_DISPLAY
OBJECT_NORMALS_SHOWN
OBJECT_COLOR_SOURCE
OBJECT_POLYLINE_WIDTH
OBJECT_SENSOR_DRAW_FRUSTUM
OBJECT_SENSOR_DRAW_FRUSTUM_PLANES
OBJECT_SF_SHOW_SCALE
OBJECT_OCTREE_LEVEL
OBJECT_OCTREE_TYPE
OBJECT_MESH_WIRE
OBJECT_MESH_POINTS
OBJECT_MESH_STIPPLING
OBJECT_MESH_TEXTUREFILE
OBJECT_CURRENT_SCALAR_FIELD
OBJECT_CURRENT_COLOR_RAMP
OBJECT_IMAGE_ALPHA
OBJECT_APPLY_IMAGE_VIEWPORT
OBJECT_APPLY_SENSOR_VIEWPORT
OBJECT_CLOUD_SF_EDITOR
OBJECT_SENSOR_MATRIX_EDITOR
OBJECT_SENSOR_DISPLAY_SCALE
OBJECT_SENSOR_UNCERTAINTY
OBJECT_COLOR_RAMP_STEPS
OBJECT_MATERIALS
OBJECT_APPLY_LABEL_VIEWPORT
OBJECT_UPDATE_LABEL_VIEWPORT
OBJECT_LABEL_DISP_2D
OBJECT_LABEL_POINT_LEGEND
OBJECT_PRIMITIVE_PRECISION
OBJECT_CIRCLE_RESOLUTION
OBJECT_SPHERE_RADIUS
OBJECT_CIRCLE_RADIUS
OBJECT_DISC_RADIUS
OBJECT_CONE_HEIGHT
OBJECT_CONE_BOTTOM_RADIUS
OBJECT_CONE_TOP_RADIUS
OBJECT_CLOUD_POINT_SIZE
OBJECT_NAME_IN_3D
OBJECT_FACET_CONTOUR
OBJECT_FACET_MESH
OBJECT_PLANE_NORMAL_VECTOR
OBJECT_SENSOR_INDEX
OBJECT_SHOW_TRANS_BUFFER_PATH
OBJECT_SHOW_TRANS_BUFFER_TRIHDERONS
OBJECT_TRANS_BUFFER_TRIHDERONS_SCALE
OBJECT_HISTORY_MATRIX_EDITOR
OBJECT_GLTRANS_MATRIX_EDITOR
OBJECT_COORDINATE_SYSTEM_DISP_PLANES
OBJECT_COORDINATE_SYSTEM_DISP_AXES
OBJECT_COORDINATE_SYSTEM_AXES_WIDTH
OBJECT_COORDINATE_SYSTEM_DISP_SCALE
OBJECT_SELECTION_HOVER_COLOR
OBJECT_SELECTION_PRESELECTED_COLOR
OBJECT_SELECTION_SELECTED_COLOR
OBJECT_SELECTION_BOUNDARY_COLOR
OBJECT_SELECTION_HOVER_OPACITY
OBJECT_SELECTION_PRESELECTED_OPACITY
OBJECT_SELECTION_SELECTED_OPACITY
OBJECT_SELECTION_BOUNDARY_OPACITY
OBJECT_SELECTION_SHOW_TOOLTIPS
OBJECT_SELECTION_MAX_ATTRIBUTES
OBJECT_VIEW_USE_LIGHT_KIT
OBJECT_VIEW_LIGHT_KIT_INTENSITY
OBJECT_VIEW_DATA_AXES_GRID_VISIBLE
OBJECT_VIEW_DATA_AXES_GRID_EDIT
OBJECT_VIEW_CAMERA_ORIENTATION_WIDGET
OBJECT_VIEW_CENTER_AXES_VISIBILITY
TREE_VIEW_HEADER
Definition at line 50 of file ecvPropertiesTreeDelegate.h.
Constructor & Destructor Documentation
ccPropertiesTreeDelegate()
ccPropertiesTreeDelegate::ccPropertiesTreeDelegate (QStandardItemModel * _model, QAbstractItemView * _view, QObject * parent = 0)
Default constructor.
Definition at line 139 of file ecvPropertiesTreeDelegate.cpp.
References m_model, and m_view.
~ccPropertiesTreeDelegate()
ccPropertiesTreeDelegate::~ccPropertiesTreeDelegate () virtual
Default destructor.
Definition at line 153 of file ecvPropertiesTreeDelegate.cpp.
References unbind().
Member Function Documentation
addSeparator()
void ccPropertiesTreeDelegate::addSeparator (QString title) protected
Definition at line 369 of file ecvPropertiesTreeDelegate.cpp.
References m_model, m_view, and TREE_VIEW_HEADER.
Referenced by fillModel(), fillSFWithPointCloud(), fillWithCameraSensor(), fillWithCCArray(), fillWithCoordinateSystem(), fillWithFacet(), fillWithGBLSensor(), fillWithHObject(), fillWithImage(), fillWithLabel(), fillWithMaterialSet(), fillWithMesh(), fillWithMetaData(), fillWithPointCloud(), fillWithPointKdTree(), fillWithPointOctree(), fillWithPolyline(), fillWithPrimitive(), fillWithSensor(), fillWithShareable(), fillWithTransBuffer(), fillWithViewportObject(), and fillWithViewProperties().
appendRow()
void ccPropertiesTreeDelegate::appendRow (QStandardItem * leftItem, QStandardItem * rightItem, bool openPersistentEditor = false) protected
Definition at line 327 of file ecvPropertiesTreeDelegate.cpp.
References m_model, and m_view.
Referenced by fillSFWithPointCloud(), fillWithCameraSensor(), fillWithCCArray(), fillWithCoordinateSystem(), fillWithFacet(), fillWithGBLSensor(), fillWithHObject(), fillWithImage(), fillWithLabel(), fillWithMaterialSet(), fillWithMesh(), fillWithMetaData(), fillWithPlanarEntity(), fillWithPointCloud(), fillWithPointKdTree(), fillWithPointOctree(), fillWithPolyline(), fillWithPrimitive(), fillWithSensor(), fillWithShareable(), fillWithShifted(), fillWithTransBuffer(), fillWithViewportObject(), and fillWithViewProperties().
appendWideRow()
void ccPropertiesTreeDelegate::appendWideRow (QStandardItem * item, bool openPersistentEditor = true) protected
Definition at line 349 of file ecvPropertiesTreeDelegate.cpp.
References m_model, m_view, and CVLog::Warning().
Referenced by fillModel(), fillSFWithPointCloud(), and fillWithSensor().
ccObjectAndChildrenAppearanceChanged
void ccPropertiesTreeDelegate::ccObjectAndChildrenAppearanceChanged (ccHObject * hObject, bool forceRedraw = true) const signal
Referenced by ccDBRoot::ccDBRoot().
ccObjectAppearanceChanged
void ccPropertiesTreeDelegate::ccObjectAppearanceChanged (ccHObject * hObject, bool forceRedraw = true) const signal
Referenced by ccDBRoot::ccDBRoot().
ccObjectPropertiesChanged
void ccPropertiesTreeDelegate::ccObjectPropertiesChanged (ccHObject * hObject) const signal
Referenced by ccDBRoot::ccDBRoot().
clearMeshTexturePathMap()
void ccPropertiesTreeDelegate::clearMeshTexturePathMap (ccHObject * mesh) protected
Clear texture path map for a specific mesh object.
Definition at line 2858 of file ecvPropertiesTreeDelegate.cpp.
References m_meshTexturePathMaps.
clearModel()
void ccPropertiesTreeDelegate::clearModel ()
Clear the model completely.
Definition at line 496 of file ecvPropertiesTreeDelegate.cpp.
References m_currentObject, m_model, and unbind().
createEditor()
QWidget * ccPropertiesTreeDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Definition at line 1293 of file ecvPropertiesTreeDelegate.cpp.
References ccColorScaleSelector::colorScaleEditorSummoned(), ccColorScaleSelector::colorScaleSelected(), sfEditDlg::entitySFHasChanged(), ccCoordinateSystem::getAxisWidth(), ccCoordinateSystem::getDisplayScale(), ccSensor::getIndexBounds(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudViewer::PointCloudTpl< T >::getScalarFieldName(), ccColorScalesManager::GetUniqueInstance(), ccDrawableObject::hasColors(), ccDrawableObject::hasScalarFields(), ccColorScaleSelector::init(), ecvTextureFileSelector::init(), isWideEditor(), m_currentObject, m_model, ccCoordinateSystem::MAX_AXIS_WIDTH_F, MAX_LINE_WIDTH_F, cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, MAX_POINT_SIZE_F, ccColorScale::MAX_STEPS, ccOctree::MEAN_CUBES, ccOctree::MEAN_POINTS, ccCoordinateSystem::MIN_AXIS_WIDTH_F, MIN_LINE_WIDTH_F, MIN_POINT_SIZE_F, ccColorScale::MIN_STEPS, OBJECT_APPLY_LABEL_VIEWPORT, OBJECT_APPLY_SENSOR_VIEWPORT, OBJECT_CIRCLE_RADIUS, OBJECT_CIRCLE_RESOLUTION, OBJECT_CLOUD_POINT_SIZE, OBJECT_CLOUD_SF_EDITOR, OBJECT_COLOR_RAMP_STEPS, OBJECT_COLOR_SOURCE, OBJECT_CONE_BOTTOM_RADIUS, OBJECT_CONE_HEIGHT, OBJECT_CONE_TOP_RADIUS, OBJECT_COORDINATE_SYSTEM_AXES_WIDTH, OBJECT_COORDINATE_SYSTEM_DISP_SCALE, OBJECT_CURRENT_COLOR_RAMP, OBJECT_CURRENT_DISPLAY, OBJECT_CURRENT_SCALAR_FIELD, OBJECT_DISC_RADIUS, OBJECT_GLTRANS_MATRIX_EDITOR, OBJECT_HISTORY_MATRIX_EDITOR, OBJECT_IMAGE_ALPHA, OBJECT_MESH_TEXTUREFILE, OBJECT_OCTREE_LEVEL, OBJECT_OCTREE_TYPE, OBJECT_OPACITY, OBJECT_POLYLINE_WIDTH, OBJECT_PRIMITIVE_PRECISION, OBJECT_SENSOR_DISPLAY_SCALE, OBJECT_SENSOR_INDEX, OBJECT_SENSOR_MATRIX_EDITOR, OBJECT_SENSOR_UNCERTAINTY, OBJECT_SPHERE_RADIUS, OBJECT_TRANS_BUFFER_TRIHDERONS_SCALE, OBJECT_UPDATE_LABEL_VIEWPORT, OBJECT_VIEW_DATA_AXES_GRID_EDIT, OBJECT_VIEW_DATA_AXES_GRID_VISIBLE, OBJECT_VIEW_LIGHT_KIT_INTENSITY, SEPARATOR_STYLESHEET(), ecvTextureFileSelector::textureFileEditorSummoned(), ecvTextureFileSelector::textureFileSelected(), ccHObjectCaster::ToCoordinateSystem(), ccHObjectCaster::ToPointCloud(), ccHObjectCaster::ToSensor(), TREE_VIEW_HEADER, and ccOctree::WIRE.
fillModel()
void ccPropertiesTreeDelegate::fillModel (ccHObject * hObject)
Fill property view with QItems corresponding to object's type.
Definition at line 200 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendWideRow(), CV_TYPES::CAMERA_SENSOR, CV_TYPES::COORDINATESYSTEM, CV_TYPES::FACET, fillWithCameraSensor(), fillWithCCArray(), fillWithCoordinateSystem(), fillWithFacet(), fillWithGBLSensor(), fillWithHObject(), fillWithImage(), fillWithLabel(), fillWithMaterialSet(), fillWithMesh(), fillWithMetaData(), fillWithPointCloud(), fillWithPointKdTree(), fillWithPointOctree(), fillWithPolyline(), fillWithPrimitive(), fillWithTransBuffer(), fillWithViewportObject(), fillWithViewProperties(), CV_TYPES::GBL_SENSOR, ccHObject::getViewId(), CV_TYPES::IMAGE, ccObject::isA(), ccDrawableObject::isGLTransEnabled(), ccObject::isHierarchy(), ccObject::isKindOf(), CV_TYPES::LABEL_2D, m_currentObject, m_model, m_view, CV_TYPES::MATERIAL_SET, CV_TYPES::MESH, CV_TYPES::NORMAL_INDEXES_ARRAY, CV_TYPES::NORMALS_ARRAY, OBJECT_GLTRANS_MATRIX_EDITOR, OBJECT_HISTORY_MATRIX_EDITOR, PERSISTENT_EDITOR(), CV_TYPES::POINT_CLOUD, CV_TYPES::POINT_KDTREE, CV_TYPES::POINT_OCTREE, CV_TYPES::POLY_LINE, CV_TYPES::PRIMITIVE, CVLog::Print(), CV_TYPES::RGB_COLOR_ARRAY, CV_TYPES::SENSOR, CV_TYPES::TEX_COORDS_ARRAY, ccHObjectCaster::To2DLabel(), ccHObjectCaster::To2DViewportObject(), ccHObjectCaster::ToCameraSensor(), ccHObjectCaster::ToCoordinateSystem(), ccHObjectCaster::ToFacet(), ccHObjectCaster::ToGBLSensor(), ccHObjectCaster::ToGenericMesh(), ccHObjectCaster::ToGenericPointCloud(), ccHObjectCaster::ToImage(), ccHObjectCaster::ToKdTree(), ccHObjectCaster::ToOctree(), ccHObjectCaster::ToPolyline(), ccHObjectCaster::ToPrimitive(), CV_TYPES::TRANS_BUFFER, unbind(), CV_TYPES::VIEWPORT_2D_LABEL, and CV_TYPES::VIEWPORT_2D_OBJECT.
Referenced by ccDBRoot::showPropertiesView(), and updateModel().
fillSFWithPointCloud()
void ccPropertiesTreeDelegate::fillSFWithPointCloud (ccGenericPointCloud * _obj) protected
Definition at line 705 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), appendWideRow(), CHECKABLE_ITEM(), ccPointCloud::getCurrentDisplayedScalarField(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), ITEM(), m_model, OBJECT_CLOUD_SF_EDITOR, OBJECT_COLOR_RAMP_STEPS, OBJECT_CURRENT_COLOR_RAMP, OBJECT_CURRENT_SCALAR_FIELD, OBJECT_SF_SHOW_SCALE, PERSISTENT_EDITOR(), ccPointCloud::sfColorScaleShown(), and ccHObjectCaster::ToPointCloud().
Referenced by fillWithMesh(), and fillWithPointCloud().
fillWithCameraSensor()
void ccPropertiesTreeDelegate::fillWithCameraSensor (ccCameraSensor * _obj) protected
Definition at line 1163 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), ccCameraSensor::IntrinsicParameters::arrayHeight, ccCameraSensor::IntrinsicParameters::arrayWidth, CHECKABLE_ITEM(), fillWithSensor(), ccCameraSensor::frustumIsDrawn(), ccCameraSensor::frustumPlanesAreDrawn(), ccCameraSensor::getIntrinsicParameters(), ITEM(), m_model, OBJECT_SENSOR_DRAW_FRUSTUM, OBJECT_SENSOR_DRAW_FRUSTUM_PLANES, ccCameraSensor::IntrinsicParameters::pixelSize_mm, ccCameraSensor::IntrinsicParameters::principal_point, cloudViewer::RadiansToDegrees(), ccCameraSensor::IntrinsicParameters::skew, ccCameraSensor::IntrinsicParameters::vertFocal_pix, and ccCameraSensor::IntrinsicParameters::vFOV_rad.
Referenced by fillModel().
fillWithCCArray()
template<class Type , int N, class ComponentType > void ccPropertiesTreeDelegate::fillWithCCArray (ccArray< Type, N, ComponentType > * _obj) protected
Definition at line 1244 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), fillWithShareable(), ccObject::getName(), ITEM(), m_model, and e57::toString().
Referenced by fillModel().
fillWithCoordinateSystem()
void ccPropertiesTreeDelegate::fillWithCoordinateSystem (const ccCoordinateSystem * _obj) protected
Definition at line 611 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), ccCoordinateSystem::axisLinesAreShown(), ccCoordinateSystem::axisPlanesAreShown(), CHECKABLE_ITEM(), ccCoordinateSystem::getOrigin(), ITEM(), m_model, OBJECT_COORDINATE_SYSTEM_AXES_WIDTH, OBJECT_COORDINATE_SYSTEM_DISP_AXES, OBJECT_COORDINATE_SYSTEM_DISP_PLANES, OBJECT_COORDINATE_SYSTEM_DISP_SCALE, OBJECT_MESH_STIPPLING, origin, and PERSISTENT_EDITOR().
Referenced by fillModel().
fillWithFacet()
void ccPropertiesTreeDelegate::fillWithFacet (ccFacet * _obj) protected
Definition at line 789 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), CHECKABLE_ITEM(), fillWithPlanarEntity(), ccFacet::getCenter(), ccFacet::getContour(), ccFacet::getPolygon(), ccFacet::getRMS(), ccFacet::getSurface(), ccDrawableObject::isVisible(), ITEM(), m_model, OBJECT_FACET_CONTOUR, OBJECT_FACET_MESH, e57::toString(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by fillModel().
fillWithGBLSensor()
void ccPropertiesTreeDelegate::fillWithGBLSensor (ccGBLSensor * _obj) protected
Definition at line 1113 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), fillWithSensor(), ccGBLSensor::getMaxPitch(), ccGBLSensor::getMaxYaw(), ccGBLSensor::getMinPitch(), ccGBLSensor::getMinYaw(), ccGBLSensor::getPitchStep(), ccGBLSensor::getYawStep(), ITEM(), m_model, OBJECT_SENSOR_UNCERTAINTY, PERSISTENT_EDITOR(), and cloudViewer::RadiansToDegrees().
Referenced by fillModel().
fillWithHObject()
void ccPropertiesTreeDelegate::fillWithHObject (ccHObject * _obj) protected
Definition at line 504 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), CHECKABLE_ITEM(), ccHObject::getBB_recursive(), cloudViewer::BoundingBoxTpl< T >::getCenter(), ccHObject::getChildrenNumber(), cloudViewer::BoundingBoxTpl< T >::getDiagVec(), ccObject::getName(), ccHObject::getOwnFitBB(), ccHObject::getSelectionBehavior(), ccGLMatrixTpl< T >::getTranslationAsVec3D(), ccObject::getUniqueID(), ccDrawableObject::hasColors(), ccDrawableObject::hasNormals(), ccDrawableObject::hasScalarFields(), ccObject::isLocked(), cloudViewer::BoundingBoxTpl< T >::isValid(), ccDrawableObject::isVisibilityLocked(), ccDrawableObject::isVisible(), ITEM(), m_model, ccDrawableObject::nameShownIn3D(), ccDrawableObject::normalsShown(), OBJECT_COLOR_SOURCE, OBJECT_CURRENT_DISPLAY, OBJECT_NAME, OBJECT_NAME_IN_3D, OBJECT_NORMALS_SHOWN, OBJECT_VISIBILITY, PERSISTENT_EDITOR(), ccHObject::SELECTION_FIT_BBOX, ccShiftedObject::toGlobal3d(), ccHObjectCaster::ToShifted(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by fillModel().
fillWithImage()
void ccPropertiesTreeDelegate::fillWithImage (ccImage * _obj) protected
Definition at line 990 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), ccImage::getAssociatedSensor(), ccImage::getH(), ccImage::getW(), ITEM(), m_model, OBJECT_APPLY_IMAGE_VIEWPORT, OBJECT_IMAGE_ALPHA, and PERSISTENT_EDITOR().
Referenced by fillModel().
fillWithLabel()
void ccPropertiesTreeDelegate::fillWithLabel (cc2DLabel * _obj) protected
Definition at line 1012 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), CHECKABLE_ITEM(), cc2DLabel::getLabelContent(), cc2DLabel::isDisplayedIn2D(), cc2DLabel::isPointLegendDisplayed(), ITEM(), m_model, OBJECT_LABEL_DISP_2D, OBJECT_LABEL_POINT_LEGEND, and ecvGui::Parameters().
Referenced by fillModel().
fillWithMaterialSet()
void ccPropertiesTreeDelegate::fillWithMaterialSet (ccMaterialSet * _obj) protected
Definition at line 1217 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), fillWithShareable(), ITEM(), and m_model.
Referenced by fillModel().
fillWithMesh()
void ccPropertiesTreeDelegate::fillWithMesh (ccGenericMesh * _obj) protected
Definition at line 845 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), CHECKABLE_ITEM(), fillSFWithPointCloud(), ccGenericMesh::getAssociatedCloud(), ccGenericMesh::hasMaterials(), ccObject::isA(), ccHObject::isAncestorOf(), ccObject::isLocked(), ccGenericMesh::isShownAsPoints(), ccGenericMesh::isShownAsWire(), ITEM(), m_model, ccGenericMesh::materialsShown(), OBJECT_MATERIALS, OBJECT_MESH_POINTS, OBJECT_MESH_STIPPLING, OBJECT_MESH_TEXTUREFILE, OBJECT_MESH_WIRE, PERSISTENT_EDITOR(), cloudViewer::GenericMesh::size(), CV_TYPES::SUB_MESH, and e57::toString().
Referenced by fillModel().
fillWithMetaData()
void ccPropertiesTreeDelegate::fillWithMetaData (ccObject * _obj) protected
Definition at line 383 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), ITEM(), m_model, and ccObject::metaData().
Referenced by fillModel().
fillWithPlanarEntity()
void ccPropertiesTreeDelegate::fillWithPlanarEntity (ccPlanarEntityInterface * _obj) protected
Definition at line 824 of file ecvPropertiesTreeDelegate.cpp.
References appendRow(), CHECKABLE_ITEM(), ccNormalVectors::ConvertNormalToDipAndDipDir(), ccPlanarEntityInterface::getNormal(), ITEM(), ccPlanarEntityInterface::normalVectorIsShown(), OBJECT_PLANE_NORMAL_VECTOR, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by fillWithFacet(), and fillWithPrimitive().
fillWithPointCloud()
void ccPropertiesTreeDelegate::fillWithPointCloud (ccGenericPointCloud * _obj) protected
Definition at line 640 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), fillSFWithPointCloud(), fillWithShifted(), ccPointCloud::fwfData(), ccPointCloud::fwfDescriptors(), ccPointCloud::grid(), ccPointCloud::gridCount(), ccPointCloud::hasFWF(), ccObject::isA(), ITEM(), m_model, OBJECT_CLOUD_POINT_SIZE, PERSISTENT_EDITOR(), CV_TYPES::POINT_CLOUD, cloudViewer::GenericCloud::size(), e57::toString(), and ccPointCloud::waveforms().
Referenced by fillModel().
fillWithPointKdTree()
void ccPropertiesTreeDelegate::fillWithPointKdTree (ccKdTree * _obj) protected
Definition at line 954 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), cloudViewer::TrueKdTree::getMaxError(), cloudViewer::TrueKdTree::getMaxErrorType(), ITEM(), m_model, cloudViewer::DistanceComputationTools::MAX_DIST, cloudViewer::DistanceComputationTools::MAX_DIST_68_PERCENT, cloudViewer::DistanceComputationTools::MAX_DIST_95_PERCENT, cloudViewer::DistanceComputationTools::MAX_DIST_99_PERCENT, and cloudViewer::DistanceComputationTools::RMS.
Referenced by fillModel().
fillWithPointOctree()
void ccPropertiesTreeDelegate::fillWithPointOctree (ccOctree * _obj) protected
Definition at line 919 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), cloudViewer::DgmOctree::getCellNumber(), cloudViewer::DgmOctree::getCellSize(), ccOctree::getDisplayedLevel(), ITEM(), m_model, cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, OBJECT_OCTREE_LEVEL, OBJECT_OCTREE_TYPE, PERSISTENT_EDITOR(), and e57::toString().
Referenced by fillModel().
fillWithPolyline()
void ccPropertiesTreeDelegate::fillWithPolyline (ccPolyline * _obj) protected
Definition at line 885 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), CV_TYPES::CIRCLE, ccPolyline::computeLength(), fillWithShifted(), ccObject::isA(), ITEM(), m_model, OBJECT_CIRCLE_RADIUS, OBJECT_CIRCLE_RESOLUTION, OBJECT_POLYLINE_WIDTH, PERSISTENT_EDITOR(), cloudViewer::ReferenceCloud::size(), and e57::toString().
Referenced by fillModel().
fillWithPrimitive()
void ccPropertiesTreeDelegate::fillWithPrimitive (ccGenericPrimitive * _obj) protected
Definition at line 750 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), CV_TYPES::CONE, CV_TYPES::CYLINDER, CV_TYPES::DISC, fillWithPlanarEntity(), ccGenericPrimitive::getTypeName(), ccGenericPrimitive::hasDrawingPrecision(), ccObject::isA(), ccObject::isKindOf(), ITEM(), m_model, OBJECT_CONE_BOTTOM_RADIUS, OBJECT_CONE_HEIGHT, OBJECT_CONE_TOP_RADIUS, OBJECT_DISC_RADIUS, OBJECT_PRIMITIVE_PRECISION, OBJECT_SPHERE_RADIUS, PERSISTENT_EDITOR(), CV_TYPES::PLANE, and CV_TYPES::SPHERE.
Referenced by fillModel().
fillWithSelectionProperties()
void ccPropertiesTreeDelegate::fillWithSelectionProperties () protected
fillWithSensor()
void ccPropertiesTreeDelegate::fillWithSensor (ccSensor * _obj) protected
Definition at line 1076 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), appendWideRow(), ccSensor::getIndexBounds(), ccSensor::getPositions(), ITEM(), m_model, OBJECT_APPLY_SENSOR_VIEWPORT, OBJECT_SENSOR_DISPLAY_SCALE, OBJECT_SENSOR_INDEX, OBJECT_SENSOR_MATRIX_EDITOR, and PERSISTENT_EDITOR().
Referenced by fillWithCameraSensor(), and fillWithGBLSensor().
fillWithShareable()
void ccPropertiesTreeDelegate::fillWithShareable (CCShareable * _obj) protected
Definition at line 1229 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), CCShareable::getLinkCount(), ITEM(), and m_model.
Referenced by fillWithCCArray(), and fillWithMaterialSet().
fillWithShifted()
void ccPropertiesTreeDelegate::fillWithShifted (ccShiftedObject * _obj) protected
Definition at line 596 of file ecvPropertiesTreeDelegate.cpp.
References appendRow(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ITEM(), m_model, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by fillWithPointCloud(), and fillWithPolyline().
fillWithTransBuffer()
void ccPropertiesTreeDelegate::fillWithTransBuffer (ccIndexedTransformationBuffer * _obj) protected
Definition at line 1052 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), CHECKABLE_ITEM(), ccIndexedTransformationBuffer::isPathShonwAsPolyline(), ITEM(), m_model, OBJECT_SHOW_TRANS_BUFFER_PATH, OBJECT_SHOW_TRANS_BUFFER_TRIHDERONS, OBJECT_TRANS_BUFFER_TRIHDERONS_SCALE, PERSISTENT_EDITOR(), and ccIndexedTransformationBuffer::triherdonsShown().
Referenced by fillModel().
fillWithViewportObject()
void ccPropertiesTreeDelegate::fillWithViewportObject (cc2DViewportObject * _obj) protected
Definition at line 1032 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), ccObject::getName(), ITEM(), m_model, OBJECT_APPLY_LABEL_VIEWPORT, OBJECT_UPDATE_LABEL_VIEWPORT, and PERSISTENT_EDITOR().
Referenced by fillModel().
fillWithViewProperties()
void ccPropertiesTreeDelegate::fillWithViewProperties () protected
Definition at line 407 of file ecvPropertiesTreeDelegate.cpp.
References addSeparator(), appendRow(), CV_TYPES::FACET, ccHObject::getBB_recursive(), ccHObject::getChildrenNumber(), ecvDisplayTools::getDataAxesGridProperties(), ccHObject::getViewId(), CV_TYPES::IMAGE, ccPolyline::is2DMode(), ccObject::isA(), ccObject::isKindOf(), cloudViewer::BoundingBoxTpl< T >::isValid(), ITEM(), CV_TYPES::LABEL_2D, m_currentObject, m_model, CV_TYPES::MATERIAL_SET, CV_TYPES::MESH, CV_TYPES::NORMAL_INDEXES_ARRAY, CV_TYPES::NORMALS_ARRAY, OBJECT_OPACITY, OBJECT_VIEW_DATA_AXES_GRID_VISIBLE, OBJECT_VIEW_LIGHT_KIT_INTENSITY, PERSISTENT_EDITOR(), CV_TYPES::POINT_CLOUD, CV_TYPES::POLY_LINE, CV_TYPES::PRIMITIVE, CV_TYPES::RGB_COLOR_ARRAY, cloudViewer::ReferenceCloud::size(), CV_TYPES::TEX_COORDS_ARRAY, ecvDisplayTools::TheInstance(), ccHObjectCaster::ToPolyline(), CV_TYPES::VIEWPORT_2D_LABEL, and CV_TYPES::VIEWPORT_2D_OBJECT.
Referenced by fillModel().
getCurrentMeshTexturePathMap()
QMap< QString, QString > ccPropertiesTreeDelegate::getCurrentMeshTexturePathMap () const protected
Get texture path map for current mesh object.
Definition at line 2849 of file ecvPropertiesTreeDelegate.cpp.
References m_currentObject, and m_meshTexturePathMaps.
getCurrentObject()
ccHObject * ccPropertiesTreeDelegate::getCurrentObject ()
Returns currently bound object.
Definition at line 196 of file ecvPropertiesTreeDelegate.cpp.
References m_currentObject.
Referenced by ccDBRoot::reflectObjectPropChange().
isWideEditor()
bool ccPropertiesTreeDelegate::isWideEditor (int itemData) const protected
Returns whether the editor is wide (i.e. spans on two columns) or not.
Definition at line 1276 of file ecvPropertiesTreeDelegate.cpp.
References OBJECT_CLOUD_SF_EDITOR, OBJECT_GLTRANS_MATRIX_EDITOR, OBJECT_HISTORY_MATRIX_EDITOR, OBJECT_SENSOR_MATRIX_EDITOR, and TREE_VIEW_HEADER.
Referenced by createEditor(), setEditorData(), and updateEditorGeometry().
requestClearSelection
void ccPropertiesTreeDelegate::requestClearSelection () const signal
Request to clear all selection data (prevents crashes from stale references)
Note
Emitted when objects might have been deleted or selection tools state changes
setEditorData()
void ccPropertiesTreeDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const virtual
Definition at line 1965 of file ecvPropertiesTreeDelegate.cpp.
References ecvTextureFileSelector::addItem(), Settings::APP_TITLE, MatrixDisplayDlg::clear(), ccDrawableObject::colorsShown(), context, ccMaterial::DIFFUSE, CV_TYPES::FACET, sfEditDlg::fillDialogWith(), MatrixDisplayDlg::fillDialogWith(), ccSensor::getActiveAbsoluteTransformation(), ccSensor::getActiveIndex(), ccCone::getBottomRadius(), ccHObject::getChildrenNumber(), ccScalarField::getColorRampSteps(), ccScalarField::getColorScale(), ccPointCloud::getCurrentDisplayedScalarField(), ccPointCloud::getCurrentDisplayedScalarFieldIndex(), ecvDisplayTools::getDataAxesGridProperties(), ccGenericPrimitive::getDrawingPrecision(), ccDrawableObject::getGLTransformation(), ccHObject::getGLTransformationHistory(), ccSensor::getGraphicScale(), ccCone::getHeight(), ecvDisplayTools::getLightIntensity(), ccGenericMesh::getMaterialSet(), ccObject::getName(), ccDrawableObject::getOpacity(), ccGenericPointCloud::getPointSize(), ccCircle::getRadius(), ccDisc::getRadius(), ccSphere::getRadius(), ccCircle::getResolution(), MainWindow::getSelectedEntities(), ccCone::getTopRadius(), ccGBLSensor::getUncertainty(), ccHObject::getViewId(), ccPolyline::getWidth(), ccDrawableObject::hasColors(), ccDrawableObject::hasScalarFields(), image, ecvTextureFileSelector::init(), isWideEditor(), m_currentObject, m_meshTexturePathMaps, m_model, CV_TYPES::MESH, OBJECT_CIRCLE_RADIUS, OBJECT_CIRCLE_RESOLUTION, OBJECT_CLOUD_POINT_SIZE, OBJECT_CLOUD_SF_EDITOR, OBJECT_COLOR_RAMP_STEPS, OBJECT_COLOR_SOURCE, OBJECT_CONE_BOTTOM_RADIUS, OBJECT_CONE_HEIGHT, OBJECT_CONE_TOP_RADIUS, OBJECT_CURRENT_COLOR_RAMP, OBJECT_CURRENT_DISPLAY, OBJECT_CURRENT_SCALAR_FIELD, OBJECT_DISC_RADIUS, OBJECT_GLTRANS_MATRIX_EDITOR, OBJECT_HISTORY_MATRIX_EDITOR, OBJECT_IMAGE_ALPHA, OBJECT_MESH_TEXTUREFILE, OBJECT_OCTREE_LEVEL, OBJECT_OCTREE_TYPE, OBJECT_OPACITY, OBJECT_POLYLINE_WIDTH, OBJECT_PRIMITIVE_PRECISION, OBJECT_SENSOR_DISPLAY_SCALE, OBJECT_SENSOR_INDEX, OBJECT_SENSOR_MATRIX_EDITOR, OBJECT_SENSOR_UNCERTAINTY, OBJECT_SPHERE_RADIUS, OBJECT_TRANS_BUFFER_TRIHDERONS_SCALE, OBJECT_VIEW_DATA_AXES_GRID_VISIBLE, OBJECT_VIEW_LIGHT_KIT_INTENSITY, octree, ecvGui::Parameters(), CV_TYPES::POINT_CLOUD, CV_TYPES::POLY_LINE, CV_TYPES::PRIMITIVE, SetComboBoxIndex(), ecvDisplayTools::setDataAxesGridProperties(), SetDoubleSpinBoxValue(), ccColorScaleSelector::setSelectedScale(), ecvTextureFileSelector::setSelectedTexturefile(), SetSpinBoxValue(), ccDrawableObject::sfShown(), ecvGui::ParamStruct::showBBOnSelected, MainWindow::TheInstance(), ecvDisplayTools::TheInstance(), ccHObjectCaster::ToCircle(), ccHObjectCaster::ToCone(), ccHObjectCaster::ToDisc(), ccHObjectCaster::ToGBLSensor(), ccHObjectCaster::ToGenericMesh(), ccHObjectCaster::ToGenericPointCloud(), ccHObjectCaster::ToImage(), ccHObjectCaster::ToOctree(), ccHObjectCaster::ToPointCloud(), ccHObjectCaster::ToPolyline(), ccHObjectCaster::ToPrimitive(), ccHObjectCaster::ToSensor(), ccHObjectCaster::ToSphere(), ccHObjectCaster::ToTransBuffer(), TREE_VIEW_HEADER, ccIndexedTransformationBuffer::triherdonsDisplayScale(), ecvDisplayTools::UpdateScreen(), and AxesGridProperties::visible.
setVisualizer()
void ccPropertiesTreeDelegate::setVisualizer (ecvGenericVisualizer3D * viewer) inline
Set visualizer for other property editors.
Definition at line 171 of file ecvPropertiesTreeDelegate.h.
References m_viewer.
sizeHint()
QSize ccPropertiesTreeDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Definition at line 155 of file ecvPropertiesTreeDelegate.cpp.
References m_model, OBJECT_CLOUD_POINT_SIZE, OBJECT_CLOUD_SF_EDITOR, OBJECT_COLOR_RAMP_STEPS, OBJECT_COLOR_SOURCE, OBJECT_CURRENT_COLOR_RAMP, OBJECT_CURRENT_DISPLAY, OBJECT_CURRENT_SCALAR_FIELD, OBJECT_GLTRANS_MATRIX_EDITOR, OBJECT_HISTORY_MATRIX_EDITOR, OBJECT_MESH_TEXTUREFILE, OBJECT_OCTREE_TYPE, OBJECT_OPACITY, OBJECT_POLYLINE_WIDTH, and OBJECT_SENSOR_MATRIX_EDITOR.
unbind()
void ccPropertiesTreeDelegate::unbind () virtual
Definition at line 189 of file ecvPropertiesTreeDelegate.cpp.
References m_meshTexturePathMaps, and m_model.
Referenced by clearModel(), fillModel(), ccDBRoot::hidePropertiesView(), and ~ccPropertiesTreeDelegate().
updateEditorGeometry()
void ccPropertiesTreeDelegate::updateEditorGeometry (QWidget * editor, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Definition at line 1907 of file ecvPropertiesTreeDelegate.cpp.
References isWideEditor(), m_model, and m_view.
updateModel()
void ccPropertiesTreeDelegate::updateModel () protected
Updates the current model (assuming object is the same)
Definition at line 2841 of file ecvPropertiesTreeDelegate.cpp.
References fillModel(), and m_currentObject.
Member Data Documentation
m_currentObject
ccHObject* ccPropertiesTreeDelegate::m_currentObject protected
Definition at line 281 of file ecvPropertiesTreeDelegate.h.
Referenced by clearModel(), createEditor(), fillModel(), fillWithViewProperties(), getCurrentMeshTexturePathMap(), getCurrentObject(), setEditorData(), and updateModel().
m_lastFocusItemRole
CC_PROPERTY_ROLE ccPropertiesTreeDelegate::m_lastFocusItemRole protected
Last focused item role (used to force scroll focus after model update)
Definition at line 291 of file ecvPropertiesTreeDelegate.h.
m_meshTexturePathMaps
QMap<ccHObject*, QMap<QString, QString> > ccPropertiesTreeDelegate::m_meshTexturePathMaps mutable protected
Texture path maps indexed by mesh object pointer Maps mesh object -> (texture name -> texture path) Mutable to allow modification in const methods (setEditorData)
Definition at line 287 of file ecvPropertiesTreeDelegate.h.
Referenced by clearMeshTexturePathMap(), getCurrentMeshTexturePathMap(), setEditorData(), and unbind().
m_model
QStandardItemModel* ccPropertiesTreeDelegate::m_model protected
Definition at line 282 of file ecvPropertiesTreeDelegate.h.
Referenced by addSeparator(), appendRow(), appendWideRow(), ccPropertiesTreeDelegate(), clearModel(), createEditor(), fillModel(), fillSFWithPointCloud(), fillWithCameraSensor(), fillWithCCArray(), fillWithCoordinateSystem(), fillWithFacet(), fillWithGBLSensor(), fillWithHObject(), fillWithImage(), fillWithLabel(), fillWithMaterialSet(), fillWithMesh(), fillWithMetaData(), fillWithPointCloud(), fillWithPointKdTree(), fillWithPointOctree(), fillWithPolyline(), fillWithPrimitive(), fillWithSensor(), fillWithShareable(), fillWithShifted(), fillWithTransBuffer(), fillWithViewportObject(), fillWithViewProperties(), setEditorData(), sizeHint(), unbind(), and updateEditorGeometry().
m_view
QAbstractItemView* ccPropertiesTreeDelegate::m_view protected
Definition at line 283 of file ecvPropertiesTreeDelegate.h.
Referenced by addSeparator(), appendRow(), appendWideRow(), ccPropertiesTreeDelegate(), fillModel(), and updateEditorGeometry().
m_viewer
ecvGenericVisualizer3D* ccPropertiesTreeDelegate::m_viewer protected
Visualizer for other property editors.
Definition at line 289 of file ecvPropertiesTreeDelegate.h.
Referenced by setVisualizer().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/db_tree/ecvPropertiesTreeDelegate.h
/root/ACloudViewer/app/db_tree/ecvPropertiesTreeDelegate.cpp