ACloudViewer: cloudViewer::core::nns::NNSIndex Class Reference
cloudViewer::core::nns::NNSIndex Class Reference abstract
#include <NNSIndex.h>
Public Member Functions
NNSIndex ()
Default Constructor.
virtual ~NNSIndex ()
NNSIndex (const NNSIndex &)=delete
NNSIndex & operator= (const NNSIndex &)=delete
virtual bool SetTensorData (const Tensor &dataset_points, const Dtype &index_dtype)=0
virtual bool SetTensorData (const Tensor &dataset_points, double radius, const Dtype &index_dtype)=0
virtual std::pair< Tensor, Tensor > SearchKnn (const Tensor &query_points, int knn) const =0
virtual std::tuple< Tensor, Tensor, Tensor > SearchRadius (const Tensor &query_points, const Tensor &radii, bool sort) const =0
virtual std::tuple< Tensor, Tensor, Tensor > SearchRadius (const Tensor &query_points, double radius, bool sort) const =0
virtual std::tuple< Tensor, Tensor, Tensor > SearchHybrid (const Tensor &query_points, double radius, int max_knn) const =0
int GetDimension () const
size_t GetDatasetSize () const
Dtype GetDtype () const
Device GetDevice () const
Dtype GetIndexDtype () const
Protected Attributes
Tensor dataset_points_
Dtype index_dtype_
Detailed Description
Definition at line 21 of file NNSIndex.h.
Constructor & Destructor Documentation
NNSIndex() [1/2]
cloudViewer::core::nns::NNSIndex::NNSIndex () inline
Default Constructor.
Definition at line 24 of file NNSIndex.h.
~NNSIndex()
virtual cloudViewer::core::nns::NNSIndex::~NNSIndex () inline virtual
Definition at line 25 of file NNSIndex.h.
NNSIndex() [2/2]
cloudViewer::core::nns::NNSIndex::NNSIndex (const NNSIndex &) delete
Member Function Documentation
GetDatasetSize()
size_t cloudViewer::core::nns::NNSIndex::GetDatasetSize () const
Get size of the dataset points.
Returns
number of points in dataset.
Definition at line 19 of file NNSIndex.cpp.
References dataset_points_, and cloudViewer::core::Tensor::GetShape().
Referenced by cloudViewer::core::nns::NanoFlannIndex::SearchKnn(), and cloudViewer::core::nns::FixedRadiusIndex::SetTensorData().
GetDevice()
Device cloudViewer::core::nns::NNSIndex::GetDevice () const
Get device of the dataset points.
Returns
device of dataset points.
Definition at line 26 of file NNSIndex.cpp.
References dataset_points_, and cloudViewer::core::Tensor::GetDevice().
Referenced by cloudViewer::core::nns::FixedRadiusIndex::SearchHybrid(), cloudViewer::core::nns::NanoFlannIndex::SearchHybrid(), cloudViewer::core::nns::KnnIndex::SearchKnn(), cloudViewer::core::nns::NanoFlannIndex::SearchKnn(), cloudViewer::core::nns::FixedRadiusIndex::SearchRadius(), cloudViewer::core::nns::NanoFlannIndex::SearchRadius(), and cloudViewer::core::nns::FixedRadiusIndex::SetTensorData().
GetDimension()
int cloudViewer::core::nns::NNSIndex::GetDimension () const
Get dimension of the dataset points.
Returns
dimension of dataset points.
Definition at line 14 of file NNSIndex.cpp.
References dataset_points_, and cloudViewer::core::Tensor::GetShape().
Referenced by cloudViewer::core::nns::FixedRadiusIndex::SearchHybrid(), cloudViewer::core::nns::NanoFlannIndex::SearchHybrid(), cloudViewer::core::nns::KnnIndex::SearchKnn(), cloudViewer::core::nns::NanoFlannIndex::SearchKnn(), cloudViewer::core::nns::FixedRadiusIndex::SearchRadius(), and cloudViewer::core::nns::NanoFlannIndex::SearchRadius().
GetDtype()
Dtype cloudViewer::core::nns::NNSIndex::GetDtype () const
Get dtype of the dataset points.
Returns
dtype of dataset points.
Definition at line 24 of file NNSIndex.cpp.
References dataset_points_, and cloudViewer::core::Tensor::GetDtype().
Referenced by cloudViewer::core::nns::FixedRadiusIndex::SearchHybrid(), cloudViewer::core::nns::NanoFlannIndex::SearchHybrid(), cloudViewer::core::nns::KnnIndex::SearchKnn(), cloudViewer::core::nns::NanoFlannIndex::SearchKnn(), cloudViewer::core::nns::FixedRadiusIndex::SearchRadius(), cloudViewer::core::nns::NanoFlannIndex::SearchRadius(), cloudViewer::core::nns::NanoFlannIndex::SetTensorData(), and cloudViewer::core::nns::FixedRadiusIndex::SetTensorData().
GetIndexDtype()
Dtype cloudViewer::core::nns::NNSIndex::GetIndexDtype () const
Get dtype of indices.
Returns
dtype of indices.
Definition at line 28 of file NNSIndex.cpp.
References index_dtype_.
Referenced by cloudViewer::core::nns::FixedRadiusIndex::SearchHybrid(), cloudViewer::core::nns::NanoFlannIndex::SearchHybrid(), cloudViewer::core::nns::KnnIndex::SearchKnn(), cloudViewer::core::nns::NanoFlannIndex::SearchKnn(), cloudViewer::core::nns::FixedRadiusIndex::SearchRadius(), cloudViewer::core::nns::NanoFlannIndex::SearchRadius(), and cloudViewer::core::nns::NanoFlannIndex::SetTensorData().
operator=()
NNSIndex& cloudViewer::core::nns::NNSIndex::operator= (const NNSIndex &) delete
SearchHybrid()
virtual std::tuple<Tensor, Tensor, Tensor> cloudViewer::core::nns::NNSIndex::SearchHybrid (const Tensor & query_points, double radius, int max_knn) const pure virtual
Perform hybrid search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}.
radius Radius.
max_knn Maximum number of neighbor to search per query point.
Returns
Tuple of Tensors, (indices, distances, counts):
indices: Tensor of shape {n, knn}, with dtype Int32.
distances: Tensor of shape {n, knn}, with dtype Float32.
counts: Tensor of shape {n, 1}, with dtype Int32.
Implemented in cloudViewer::core::nns::NanoFlannIndex, cloudViewer::core::nns::FixedRadiusIndex, and cloudViewer::core::nns::KnnIndex.
SearchKnn()
virtual std::pair<Tensor, Tensor> cloudViewer::core::nns::NNSIndex::SearchKnn (const Tensor & query_points, int knn) const pure virtual
Perform K nearest neighbor search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}, same dtype with dataset_points.
knn Number of nearest neighbor to search.
Returns
Pair of Tensors: (indices, distances):
indices: Tensor of shape {n, knn}, with dtype Int32.
distances: Tensor of shape {n, knn}, same dtype with dataset_points.
Implemented in cloudViewer::core::nns::NanoFlannIndex, cloudViewer::core::nns::KnnIndex, and cloudViewer::core::nns::FixedRadiusIndex.
SearchRadius() [1/2]
virtual std::tuple<Tensor, Tensor, Tensor> cloudViewer::core::nns::NNSIndex::SearchRadius (const Tensor & query_points, const Tensor & radii, bool sort) const pure virtual
Perform radius search with multiple radii.
Parameters
query_points Query points. Must be 2D, with shape {n, d}, same dtype with dataset_points.
radii list of radius. Must be 1D, with shape {n, }.
Returns
Tuple of Tensors: (indices, distances, num_neighbors):
indices: Tensor of shape {total_num_neighbors,}, dtype Int32.
distances: Tensor of shape {total_num_neighbors,}, same dtype with dataset_points.
num_neighbors: Tensor of shape {n,}, dtype Int32.
Implemented in cloudViewer::core::nns::NanoFlannIndex, cloudViewer::core::nns::FixedRadiusIndex, and cloudViewer::core::nns::KnnIndex.
SearchRadius() [2/2]
virtual std::tuple<Tensor, Tensor, Tensor> cloudViewer::core::nns::NNSIndex::SearchRadius (const Tensor & query_points, double radius, bool sort) const pure virtual
Perform radius search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}, same dtype with dataset_points.
radius Radius.
Returns
Tuple of Tensors, (indices, distances, num_neighbors):
indices: Tensor of shape {total_num_neighbors,}, dtype Int32.
distances: Tensor of shape {total_num_neighbors,}, same dtype with dataset_points.
num_neighbors: Tensor of shape {n}, dtype Int32.
Implemented in cloudViewer::core::nns::NanoFlannIndex, cloudViewer::core::nns::FixedRadiusIndex, and cloudViewer::core::nns::KnnIndex.
SetTensorData() [1/2]
virtual bool cloudViewer::core::nns::NNSIndex::SetTensorData (const Tensor & dataset_points, const Dtype & index_dtype) pure virtual
Set the data for the nearest neighbor search.
Parameters
dataset_points Dataset points for KDTree construction. Must be 2D, with shape {n, d}.
Returns
Returns true if the construction success, otherwise false.
Implemented in cloudViewer::core::nns::NanoFlannIndex, cloudViewer::core::nns::KnnIndex, and cloudViewer::core::nns::FixedRadiusIndex.
SetTensorData() [2/2]
virtual bool cloudViewer::core::nns::NNSIndex::SetTensorData (const Tensor & dataset_points, double radius, const Dtype & index_dtype) pure virtual
Set the data for the nearest neighbor search.
Parameters
dataset_points Dataset points for KDTree construction. Must be 2D, with shape {n, d}.
Returns
Returns true if the construction success, otherwise false.
Implemented in cloudViewer::core::nns::NanoFlannIndex, cloudViewer::core::nns::KnnIndex, and cloudViewer::core::nns::FixedRadiusIndex.
Member Data Documentation
dataset_points_
Tensor cloudViewer::core::nns::NNSIndex::dataset_points_ protected
Definition at line 120 of file NNSIndex.h.
Referenced by GetDatasetSize(), GetDevice(), GetDimension(), GetDtype(), cloudViewer::core::nns::NanoFlannIndex::SearchHybrid(), cloudViewer::core::nns::NanoFlannIndex::SearchKnn(), cloudViewer::core::nns::NanoFlannIndex::SearchRadius(), cloudViewer::core::nns::NanoFlannIndex::SetTensorData(), cloudViewer::core::nns::KnnIndex::SetTensorData(), and cloudViewer::core::nns::FixedRadiusIndex::SetTensorData().
index_dtype_
Dtype cloudViewer::core::nns::NNSIndex::index_dtype_ protected
Definition at line 121 of file NNSIndex.h.
Referenced by GetIndexDtype(), cloudViewer::core::nns::NanoFlannIndex::SearchRadius(), cloudViewer::core::nns::NanoFlannIndex::SetTensorData(), cloudViewer::core::nns::KnnIndex::SetTensorData(), and cloudViewer::core::nns::FixedRadiusIndex::SetTensorData().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/core/nns/NNSIndex.h
/root/ACloudViewer/libs/cloudViewer/core/nns/NNSIndex.cpp