ACloudViewer: cloudViewer::core::CUDAHashBackendBufferAccessor Class Reference
cloudViewer::core::CUDAHashBackendBufferAccessor Class Reference
#include <CUDAHashBackendBufferAccessor.h>
Public Member Functions
__host__ void Setup (HashBackendBuffer &hashmap_buffer)
__host__ void Shutdown (const Device &device)
__device__ buf_index_t DeviceAllocate ()
__device__ void DeviceFree (buf_index_t ptr)
__device__ void * GetKeyPtr (buf_index_t ptr)
__device__ void * GetValuePtr (buf_index_t ptr, int value_idx=0)
Public Attributes
buf_index_t * heap_
int * heap_top_ = nullptr
uint8_t * keys_
int64_t key_dsize_
size_t n_values_
uint8_t ** values_
int64_t common_block_size_
int64_t * value_dsizes_
int64_t * value_blocks_per_element_
int64_t capacity_
Detailed Description
Definition at line 24 of file CUDAHashBackendBufferAccessor.h.
Member Function Documentation
DeviceAllocate()
__device__ buf_index_t cloudViewer::core::CUDAHashBackendBufferAccessor::DeviceAllocate () inline
Definition at line 79 of file CUDAHashBackendBufferAccessor.h.
References heap_, and heap_top_.
Referenced by cloudViewer::core::STDGPUInsertKernel().
DeviceFree()
__device__ void cloudViewer::core::CUDAHashBackendBufferAccessor::DeviceFree (buf_index_t ptr) inline
Definition at line 83 of file CUDAHashBackendBufferAccessor.h.
References heap_, and heap_top_.
Referenced by cloudViewer::core::EraseKernelPass1(), cloudViewer::core::InsertKernelPass2(), and cloudViewer::core::STDGPUEraseKernel().
GetKeyPtr()
__device__ void* cloudViewer::core::CUDAHashBackendBufferAccessor::GetKeyPtr (buf_index_t ptr) inline
Definition at line 88 of file CUDAHashBackendBufferAccessor.h.
References key_dsize_, and keys_.
Referenced by cloudViewer::core::InsertKernelPass0(), cloudViewer::core::STDGPUInsertKernel(), and cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::WarpFindKey().
GetValuePtr()
__device__ void* cloudViewer::core::CUDAHashBackendBufferAccessor::GetValuePtr (buf_index_t ptr, int value_idx = 0) inline
Definition at line 91 of file CUDAHashBackendBufferAccessor.h.
References value_dsizes_, and values_.
Referenced by cloudViewer::core::InsertKernelPass2(), and cloudViewer::core::STDGPUInsertKernel().
Setup()
__host__ void cloudViewer::core::CUDAHashBackendBufferAccessor::Setup (HashBackendBuffer & hashmap_buffer) inline
Definition at line 26 of file CUDAHashBackendBufferAccessor.h.
References capacity_, CLOUDVIEWER_CUDA_CHECK, common_block_size_, cloudViewer::core::HashBackendBuffer::HeapTop::cuda, cloudViewer::core::HashBackendBuffer::GetCapacity(), cloudViewer::core::HashBackendBuffer::GetCommonBlockSize(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::HashBackendBuffer::GetDevice(), cloudViewer::core::HashBackendBuffer::GetHeapTop(), cloudViewer::core::HashBackendBuffer::GetIndexHeap(), cloudViewer::core::HashBackendBuffer::GetKeyBuffer(), cloudViewer::core::HashBackendBuffer::GetKeyDsize(), cloudViewer::core::HashBackendBuffer::GetValueBlocksPerElement(), cloudViewer::core::HashBackendBuffer::GetValueBuffers(), cloudViewer::core::HashBackendBuffer::GetValueDsizes(), heap_, heap_top_, key_dsize_, keys_, cloudViewer::core::MemoryManager::Malloc(), cloudViewer::core::MemoryManager::MemcpyFromHost(), n_values_, cloudViewer::core::cuda::Synchronize(), value_blocks_per_element_, value_dsizes_, and values_.
Shutdown()
__host__ void cloudViewer::core::CUDAHashBackendBufferAccessor::Shutdown (const Device & device) inline
Definition at line 73 of file CUDAHashBackendBufferAccessor.h.
References cloudViewer::core::MemoryManager::Free(), value_blocks_per_element_, value_dsizes_, and values_.
Member Data Documentation
capacity_
int64_t cloudViewer::core::CUDAHashBackendBufferAccessor::capacity_
Definition at line 110 of file CUDAHashBackendBufferAccessor.h.
Referenced by Setup().
common_block_size_
int64_t cloudViewer::core::CUDAHashBackendBufferAccessor::common_block_size_
Definition at line 105 of file CUDAHashBackendBufferAccessor.h.
Referenced by Setup().
heap_
buf_index_t* cloudViewer::core::CUDAHashBackendBufferAccessor::heap_
Definition at line 96 of file CUDAHashBackendBufferAccessor.h.
Referenced by DeviceAllocate(), DeviceFree(), cloudViewer::core::InsertKernelPass0(), and Setup().
heap_top_
int* cloudViewer::core::CUDAHashBackendBufferAccessor::heap_top_ = nullptr
Definition at line 97 of file CUDAHashBackendBufferAccessor.h.
Referenced by DeviceAllocate(), DeviceFree(), and Setup().
key_dsize_
int64_t cloudViewer::core::CUDAHashBackendBufferAccessor::key_dsize_
Definition at line 100 of file CUDAHashBackendBufferAccessor.h.
Referenced by GetKeyPtr(), and Setup().
keys_
uint8_t* cloudViewer::core::CUDAHashBackendBufferAccessor::keys_
Definition at line 99 of file CUDAHashBackendBufferAccessor.h.
Referenced by GetKeyPtr(), and Setup().
n_values_
size_t cloudViewer::core::CUDAHashBackendBufferAccessor::n_values_
Definition at line 102 of file CUDAHashBackendBufferAccessor.h.
Referenced by Setup().
value_blocks_per_element_
int64_t* cloudViewer::core::CUDAHashBackendBufferAccessor::value_blocks_per_element_
Definition at line 108 of file CUDAHashBackendBufferAccessor.h.
Referenced by cloudViewer::core::InsertKernelPass2(), Setup(), Shutdown(), and cloudViewer::core::STDGPUInsertKernel().
value_dsizes_
int64_t* cloudViewer::core::CUDAHashBackendBufferAccessor::value_dsizes_
Definition at line 107 of file CUDAHashBackendBufferAccessor.h.
Referenced by GetValuePtr(), Setup(), and Shutdown().
values_
uint8_t** cloudViewer::core::CUDAHashBackendBufferAccessor::values_
Definition at line 103 of file CUDAHashBackendBufferAccessor.h.
Referenced by GetValuePtr(), Setup(), and Shutdown().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/hashmap/CUDA/CUDAHashBackendBufferAccessor.h