ACloudViewer: ccNormalComputationDlg Class Reference
ccNormalComputationDlg Class Reference
Dialog for normal computation.
#include <ecvNormalComputationDlg.h>
Public Member Functions
ccNormalComputationDlg (bool withScanGrid, bool withSensor, QWidget *parent=nullptr)
Default constructor.
CV_LOCAL_MODEL_TYPES getLocalModel () const
Returns the local model chosen for normal computation.
void setLocalModel (CV_LOCAL_MODEL_TYPES model)
Sets the local model chosen for normal computation.
void setRadius (PointCoordinateType radius)
Sets default value for local neighbourhood radius.
void setPreferredOrientation (ccNormalVectors::Orientation orientation)
Sets the preferred orientation.
void setCloud (ccPointCloud *cloud)
Sets the currently selected cloud (required for 'auto' feature)
bool useScanGridsForComputation () const
Returns whether scan grids should be used for computation.
double getMinGridAngle_deg () const
Returns the min angle for grid triangles.
void setMinGridAngle_deg (double value)
Sets the min angle for grid triangles.
PointCoordinateType getRadius () const
Returns local neighbourhood radius.
bool orientNormals () const
Returns whether normals should be oriented or not.
bool useScanGridsForOrientation () const
Returns whether scan grids should be used for normals orientation.
bool useSensorsForOrientation () const
Returns whether scan grids should be used for normals computation.
bool usePreferredOrientation () const
Returns whether a preferred orientation should be used.
ccNormalVectors::Orientation getPreferredOrientation () const
Returns the preferred orientation (if any)
bool useMSTOrientation () const
int getMSTNeighborCount () const
Returns the number of neighbors for Minimum Spanning Tree (MST)
void setMSTNeighborCount (int n)
Sets the number of neighbors for Minimum Spanning Tree (MST)
Protected Slots
void localModelChanged (int index)
On local model change.
void autoEstimateRadius ()
Automatically estimate the local surface radius.
Protected Attributes
ccPointCloud * m_cloud
Selected cloud.
Detailed Description
Dialog for normal computation.
Definition at line 18 of file ecvNormalComputationDlg.h.
Constructor & Destructor Documentation
ccNormalComputationDlg()
ccNormalComputationDlg::ccNormalComputationDlg (bool withScanGrid, bool withSensor, QWidget * parent = nullptr) explicit
Default constructor.
Parameters
withScanGrid whether the selection contains some structured point clouds
withSensor whether the selection contains some sensors associated to the point clouds
parent parent widget
Definition at line 21 of file ecvNormalComputationDlg.cpp.
References autoEstimateRadius(), and localModelChanged().
Member Function Documentation
autoEstimateRadius
void ccNormalComputationDlg::autoEstimateRadius () protected slot
Automatically estimate the local surface radius.
Definition at line 175 of file ecvNormalComputationDlg.cpp.
References ccGenericPointCloud::computeOctree(), CVLog::Error(), ccObject::getName(), ccGenericPointCloud::getOctree(), ccNormalVectors::GuessBestRadius(), and m_cloud.
Referenced by ccNormalComputationDlg().
getLocalModel()
CV_LOCAL_MODEL_TYPES ccNormalComputationDlg::getLocalModel () const
Returns the local model chosen for normal computation.
Definition at line 79 of file ecvNormalComputationDlg.cpp.
References LS, QUADRIC, and TRI.
Referenced by ccEntityAction::computeNormals().
getMinGridAngle_deg()
double ccNormalComputationDlg::getMinGridAngle_deg () const
Returns the min angle for grid triangles.
Definition at line 128 of file ecvNormalComputationDlg.cpp.
Referenced by ccEntityAction::computeNormals().
getMSTNeighborCount()
int ccNormalComputationDlg::getMSTNeighborCount () const
Returns the number of neighbors for Minimum Spanning Tree (MST)
Definition at line 160 of file ecvNormalComputationDlg.cpp.
Referenced by ccEntityAction::computeNormals().
getPreferredOrientation()
ccNormalVectors::Orientation ccNormalComputationDlg::getPreferredOrientation () const
Returns the preferred orientation (if any)
Definition at line 164 of file ecvNormalComputationDlg.cpp.
References ccNormalVectors::PREVIOUS, and ccNormalVectors::UNDEFINED.
Referenced by ccEntityAction::computeNormals().
getRadius()
PointCoordinateType ccNormalComputationDlg::getRadius () const
Returns local neighbourhood radius.
Definition at line 110 of file ecvNormalComputationDlg.cpp.
Referenced by ccEntityAction::computeNormals().
localModelChanged
void ccNormalComputationDlg::localModelChanged (int index) protected slot
On local model change.
Definition at line 93 of file ecvNormalComputationDlg.cpp.
Referenced by ccNormalComputationDlg().
orientNormals()
bool ccNormalComputationDlg::orientNormals () const
Returns whether normals should be oriented or not.
Definition at line 136 of file ecvNormalComputationDlg.cpp.
Referenced by ccEntityAction::computeNormals().
setCloud()
void ccNormalComputationDlg::setCloud (ccPointCloud * cloud)
Sets the currently selected cloud (required for 'auto' feature)
Definition at line 104 of file ecvNormalComputationDlg.cpp.
References m_cloud, and ccDrawableObject::setVisible().
Referenced by ccEntityAction::computeNormals().
setLocalModel()
void ccNormalComputationDlg::setLocalModel (CV_LOCAL_MODEL_TYPES model)
Sets the local model chosen for normal computation.
Definition at line 60 of file ecvNormalComputationDlg.cpp.
References LS, QUADRIC, and TRI.
Referenced by ccEntityAction::computeNormals().
setMinGridAngle_deg()
void ccNormalComputationDlg::setMinGridAngle_deg (double value)
Sets the min angle for grid triangles.
Definition at line 132 of file ecvNormalComputationDlg.cpp.
Referenced by ccEntityAction::computeNormals().
setMSTNeighborCount()
void ccNormalComputationDlg::setMSTNeighborCount (int n)
Sets the number of neighbors for Minimum Spanning Tree (MST)
Definition at line 156 of file ecvNormalComputationDlg.cpp.
Referenced by ccEntityAction::computeNormals().
setPreferredOrientation()
void ccNormalComputationDlg::setPreferredOrientation (ccNormalVectors::Orientation orientation)
Sets the preferred orientation.
Definition at line 114 of file ecvNormalComputationDlg.cpp.
References ccNormalVectors::UNDEFINED.
Referenced by ccEntityAction::computeNormals().
setRadius()
void ccNormalComputationDlg::setRadius (PointCoordinateType radius)
Sets default value for local neighbourhood radius.
Definition at line 100 of file ecvNormalComputationDlg.cpp.
Referenced by ccEntityAction::computeNormals().
useMSTOrientation()
bool ccNormalComputationDlg::useMSTOrientation () const
Returns whether a Minimum Spanning Tree (MST) should be used for normals orientation
Definition at line 152 of file ecvNormalComputationDlg.cpp.
Referenced by ccEntityAction::computeNormals().
usePreferredOrientation()
bool ccNormalComputationDlg::usePreferredOrientation () const
Returns whether a preferred orientation should be used.
Definition at line 148 of file ecvNormalComputationDlg.cpp.
useScanGridsForComputation()
bool ccNormalComputationDlg::useScanGridsForComputation () const
Returns whether scan grids should be used for computation.
Definition at line 124 of file ecvNormalComputationDlg.cpp.
Referenced by ccEntityAction::computeNormals().
useScanGridsForOrientation()
bool ccNormalComputationDlg::useScanGridsForOrientation () const
Returns whether scan grids should be used for normals orientation.
Definition at line 140 of file ecvNormalComputationDlg.cpp.
Referenced by ccEntityAction::computeNormals().
useSensorsForOrientation()
bool ccNormalComputationDlg::useSensorsForOrientation () const
Returns whether scan grids should be used for normals computation.
Definition at line 144 of file ecvNormalComputationDlg.cpp.
Referenced by ccEntityAction::computeNormals().
Member Data Documentation
m_cloud
ccPointCloud* ccNormalComputationDlg::m_cloud protected
Selected cloud.
Definition at line 94 of file ecvNormalComputationDlg.h.
Referenced by autoEstimateRadius(), and setCloud().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvNormalComputationDlg.h
/root/ACloudViewer/app/ecvNormalComputationDlg.cpp