ACloudViewer: ecvEntitySelectionDialog Class Reference
ecvEntitySelectionDialog Class Reference
Dialog to select one or multiple entities.
#include <ecvEntitySelectionDlg.h>
Public Slots
void selectAll ()
Selects all entities.
void selectNone ()
Selects all entities.
Public Member Functions
ecvEntitySelectionDialog (const ccHObject::Container &entities, bool multiSelectionEnabled, int defaultSelectedIndex=0, QWidget *parent=0, QString label=QString())
Default constructor.
virtual ~ecvEntitySelectionDialog ()
Destructor.
int getSelectedIndex () const
Returns the selected index (unique selection mode)
void getSelectedIndexes (std::vector< int > &indexes) const
Returns the selected indexes (multi-selection mode)
Static Public Member Functions
static int SelectEntity (const ccHObject::Container &entities, int defaultSelectedIndex=0, QWidget *parent=0, QString label=QString())
Static shortcut: unique selection mode.
static bool SelectEntities (const ccHObject::Container &entities, std::vector< int > &indexes, QWidget *parent=0, QString label=QString())
Static shortcut: multi-selection mode.
Protected Attributes
Ui_EntitySelectionDialog * m_ui
Associated ui.
Detailed Description
Dialog to select one or multiple entities.
Definition at line 36 of file ecvEntitySelectionDlg.h.
Constructor & Destructor Documentation
ecvEntitySelectionDialog()
ecvEntitySelectionDialog::ecvEntitySelectionDialog (const ccHObject::Container & entities, bool multiSelectionEnabled, int defaultSelectedIndex = 0, QWidget * parent = 0, QString label = QString())
Default constructor.
Definition at line 17 of file ecvEntitySelectionDlg.cpp.
References m_ui, selectAll(), and selectNone().
~ecvEntitySelectionDialog()
ecvEntitySelectionDialog::~ecvEntitySelectionDialog () virtual
Destructor.
Definition at line 61 of file ecvEntitySelectionDlg.cpp.
References m_ui.
Member Function Documentation
getSelectedIndex()
int ecvEntitySelectionDialog::getSelectedIndex () const
Returns the selected index (unique selection mode)
Definition at line 74 of file ecvEntitySelectionDlg.cpp.
References m_ui.
Referenced by SelectEntity().
getSelectedIndexes()
void ecvEntitySelectionDialog::getSelectedIndexes (std::vector< int > & indexes) const
Returns the selected indexes (multi-selection mode)
Definition at line 80 of file ecvEntitySelectionDlg.cpp.
References m_ui.
Referenced by SelectEntities().
selectAll
void ecvEntitySelectionDialog::selectAll () slot
Selects all entities.
Definition at line 68 of file ecvEntitySelectionDlg.cpp.
References m_ui.
Referenced by ecvEntitySelectionDialog().
SelectEntities()
bool ecvEntitySelectionDialog::SelectEntities (const ccHObject::Container & entities, std::vector< int > & indexes, QWidget * parent = 0, QString label = QString()) static
Static shortcut: multi-selection mode.
Definition at line 110 of file ecvEntitySelectionDlg.cpp.
References getSelectedIndexes().
SelectEntity()
int ecvEntitySelectionDialog::SelectEntity (const ccHObject::Container & entities, int defaultSelectedIndex = 0, QWidget * parent = 0, QString label = QString()) static
Static shortcut: unique selection mode.
Definition at line 97 of file ecvEntitySelectionDlg.cpp.
References getSelectedIndex().
selectNone
void ecvEntitySelectionDialog::selectNone () slot
Selects all entities.
Definition at line 70 of file ecvEntitySelectionDlg.cpp.
References m_ui.
Referenced by ecvEntitySelectionDialog().
Member Data Documentation
m_ui
Ui_EntitySelectionDialog* ecvEntitySelectionDialog::m_ui protected
Associated ui.
Definition at line 77 of file ecvEntitySelectionDlg.h.
Referenced by ecvEntitySelectionDialog(), getSelectedIndex(), getSelectedIndexes(), selectAll(), selectNone(), and ~ecvEntitySelectionDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvEntitySelectionDlg.h
/root/ACloudViewer/app/ecvEntitySelectionDlg.cpp