ACloudViewer: cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane Class Reference
cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane Class Reference
#include <TransformationEstimation.h>
Public Member Functions
TransformationEstimationPointToPlane ()
Default constructor.
~TransformationEstimationPointToPlane () override
TransformationEstimationPointToPlane (const RobustKernel &kernel)
Constructor that takes as input a RobustKernel.
TransformationEstimationType GetTransformationEstimationType () const override
double ComputeRMSE (const geometry::PointCloud &source, const geometry::PointCloud &target, const core::Tensor &correspondences) const override
Computes RMSE (double) for PointToPlane method, between two pointclouds, given correspondences.
core::Tensor ComputeTransformation (const geometry::PointCloud &source, const geometry::PointCloud &target, const core::Tensor &correspondences, const core::Tensor &current_transform=core::Tensor::Eye(4, core::Float64, core::Device("CPU:0")), const std::size_t iteration=0) const override
Estimates the transformation matrix for PointToPlane method, a tensor of shape {4, 4}, and dtype Float64 on CPU device.
Public Member Functions inherited from cloudViewer::t::pipelines::registration::TransformationEstimation
TransformationEstimation ()
Default Constructor.
virtual ~TransformationEstimation ()
Public Attributes
RobustKernel kernel_ = RobustKernel(RobustKernelMethod::L2Loss, 1.0, 1.0)
RobustKernel for outlier rejection.
Detailed Description
Class to estimate a transformation matrix tensor of shape {4, 4}, dtype Float64, on CPU device for point to plane distance.
Definition at line 155 of file TransformationEstimation.h.
Constructor & Destructor Documentation
TransformationEstimationPointToPlane() [1/2]
cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane::TransformationEstimationPointToPlane () inline
Default constructor.
Definition at line 158 of file TransformationEstimation.h.
~TransformationEstimationPointToPlane()
cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane::~TransformationEstimationPointToPlane () inline override
Definition at line 159 of file TransformationEstimation.h.
TransformationEstimationPointToPlane() [2/2]
cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane::TransformationEstimationPointToPlane (const RobustKernel & kernel) inline explicit
Constructor that takes as input a RobustKernel.
Parameters
kernel Any of the implemented statistical robust kernel for outlier rejection.
Definition at line 165 of file TransformationEstimation.h.
Member Function Documentation
ComputeRMSE()
double cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane::ComputeRMSE (const geometry::PointCloud & source, const geometry::PointCloud & target, const core::Tensor & correspondences) const override virtual
Computes RMSE (double) for PointToPlane method, between two pointclouds, given correspondences.
Parameters
source Source pointcloud. (Float32 or Float64 type).
target Target pointcloud. (Float32 or Float64 type). It must contain normals of the same shape and dtype as the positions.
correspondences Tensor of type Int64 containing indices of corresponding target points, where the value is the target index and the index of the value itself is the source index. It contains -1 as value at index with no correspondence.
Implements cloudViewer::t::pipelines::registration::TransformationEstimation.
Definition at line 99 of file TransformationEstimation.cpp.
References AssertTensorDevice, AssertTensorDtype, cloudViewer::t::pipelines::registration::AssertValidCorrespondences(), error(), cloudViewer::core::Float64, cloudViewer::t::geometry::PointCloud::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::PointCloud::GetPointNormals(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), cloudViewer::t::geometry::PointCloud::HasPointPositions(), cloudViewer::core::Tensor::IndexGet(), LogError, cloudViewer::core::Tensor::Mul_(), cloudViewer::core::Tensor::Ne(), cloudViewer::core::Tensor::Reshape(), cloudViewer::core::Tensor::Sum(), and cloudViewer::t::geometry::kernel::image::To().
ComputeTransformation()
core::Tensor cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane::ComputeTransformation (const geometry::PointCloud & source, const geometry::PointCloud & target, const core::Tensor & correspondences, const core::Tensor & current_transform = core::Tensor::Eye(4, core::Float64, core::Device("CPU:0")), const std::size_t iteration = 0) const override virtual
Estimates the transformation matrix for PointToPlane method, a tensor of shape {4, 4}, and dtype Float64 on CPU device.
Parameters
source Source pointcloud. (Float32 or Float64 type).
target Target pointcloud. (Float32 or Float64 type). It must contain normals of the same shape and dtype as the positions.
correspondences Tensor of type Int64 containing indices of corresponding target points, where the value is the target index and the index of the value itself is the source index. It contains -1 as value at index with no correspondence.
current_transform The current pose estimate of ICP.
iteration The current iteration number of the ICP algorithm.
Returns
transformation between source to target, a tensor of shape {4, 4}, type Float64 on CPU device.
Implements cloudViewer::t::pipelines::registration::TransformationEstimation.
Definition at line 134 of file TransformationEstimation.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, cloudViewer::t::pipelines::registration::AssertValidCorrespondences(), cloudViewer::t::pipelines::kernel::ComputePosePointToPlane(), cloudViewer::t::geometry::PointCloud::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::t::geometry::PointCloud::GetPointNormals(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), cloudViewer::t::geometry::PointCloud::HasPointPositions(), LogError, and cloudViewer::t::pipelines::kernel::PoseToTransformation().
GetTransformationEstimationType()
TransformationEstimationType cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane::GetTransformationEstimationType () const inline override virtual
Implements cloudViewer::t::pipelines::registration::TransformationEstimation.
Definition at line 169 of file TransformationEstimation.h.
Member Data Documentation
kernel_
RobustKernel cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane::kernel_ = RobustKernel(RobustKernelMethod::L2Loss, 1.0, 1.0)
RobustKernel for outlier rejection.
Definition at line 212 of file TransformationEstimation.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/t/pipelines/registration/TransformationEstimation.h
/root/ACloudViewer/libs/cloudViewer/t/pipelines/registration/TransformationEstimation.cpp