ACloudViewer: colmap::FundamentalMatrixEightPointEstimator Class Reference
colmap::FundamentalMatrixEightPointEstimator Class Reference
#include <fundamental_matrix.h>
Public Types
typedef Eigen::Vector2d X_t
typedef Eigen::Vector2d Y_t
typedef Eigen::Matrix3d M_t
Static Public Member Functions
static std::vector< M_t > Estimate (const std::vector< X_t > &points1, const std::vector< Y_t > &points2)
static void Residuals (const std::vector< X_t > &points1, const std::vector< Y_t > &points2, const M_t &F, std::vector< double > *residuals)
Static Public Attributes
static const int kMinNumSamples = 8
Detailed Description
Definition at line 69 of file fundamental_matrix.h.
Member Typedef Documentation
M_t
typedef Eigen::Matrix3d colmap::FundamentalMatrixEightPointEstimator::M_t
Definition at line 73 of file fundamental_matrix.h.
X_t
typedef Eigen::Vector2d colmap::FundamentalMatrixEightPointEstimator::X_t
Definition at line 71 of file fundamental_matrix.h.
Y_t
typedef Eigen::Vector2d colmap::FundamentalMatrixEightPointEstimator::Y_t
Definition at line 72 of file fundamental_matrix.h.
Member Function Documentation
Estimate()
std::vector< FundamentalMatrixEightPointEstimator::M_t > colmap::FundamentalMatrixEightPointEstimator::Estimate (const std::vector< X_t > & points1, const std::vector< Y_t > & points2) static
Definition at line 152 of file fundamental_matrix.cc.
References colmap::CenterAndNormalizeImagePoints(), x, and y.
Referenced by BOOST_AUTO_TEST_CASE().
Residuals()
void colmap::FundamentalMatrixEightPointEstimator::Residuals (const std::vector< X_t > & points1, const std::vector< Y_t > & points2, const M_t & F, std::vector< double > * residuals) static
Definition at line 195 of file fundamental_matrix.cc.
References colmap::ComputeSquaredSampsonError().
Member Data Documentation
kMinNumSamples
const int colmap::FundamentalMatrixEightPointEstimator::kMinNumSamples = 8 static
Definition at line 76 of file fundamental_matrix.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/estimators/fundamental_matrix.h
/root/ACloudViewer/libs/Reconstruction/src/estimators/fundamental_matrix.cc