ACloudViewer: cloudViewer::visualization::SelectionPolygonVolume Class Reference
cloudViewer::visualization::SelectionPolygonVolume Class Reference
Select a polygon volume for cropping.
#include <SelectionPolygonVolume.h>
Public Member Functions
~SelectionPolygonVolume () override
bool ConvertToJsonValue (Json::Value &value) const override
bool ConvertFromJsonValue (const Json::Value &value) override
std::shared_ptr< ccPointCloud > CropPointCloud (const ccPointCloud &input) const
std::shared_ptr< ccMesh > CropTriangleMesh (const ccMesh &input) const
std::vector< size_t > CropInPolygon (const ccPointCloud &input) const
Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
virtual ~IJsonConvertible ()
virtual std::string ToString () const
Convert to a styled string representation of JSON data for display.
Public Attributes
std::string orthogonal_axis_ = ""
One of {x, y, z}.
std::vector< Eigen::Vector3d > bounding_polygon_
Bounding polygon boundary.
double axis_min_ = 0.0
Minimum axis value.
double axis_max_ = 0.0
Maximum axis value.
Additional Inherited Members
Static Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
static bool EigenVector3dFromJsonArray (Eigen::Vector3d &vec, const Json::Value &value)
static bool EigenVector3dToJsonArray (const Eigen::Vector3d &vec, Json::Value &value)
static bool EigenVector4dFromJsonArray (Eigen::Vector4d &vec, const Json::Value &value)
static bool EigenVector4dToJsonArray (const Eigen::Vector4d &vec, Json::Value &value)
static bool EigenMatrix3dFromJsonArray (Eigen::Matrix3d &mat, const Json::Value &value)
static bool EigenMatrix3dToJsonArray (const Eigen::Matrix3d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d_u &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d_u &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d_u &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d_u &mat, Json::Value &value)
Detailed Description
Select a polygon volume for cropping.
Definition at line 28 of file SelectionPolygonVolume.h.
Constructor & Destructor Documentation
~SelectionPolygonVolume()
cloudViewer::visualization::SelectionPolygonVolume::~SelectionPolygonVolume () inline override
Definition at line 30 of file SelectionPolygonVolume.h.
Member Function Documentation
ConvertFromJsonValue()
bool cloudViewer::visualization::SelectionPolygonVolume::ConvertFromJsonValue (const Json::Value & value) override virtual
Implements cloudViewer::utility::IJsonConvertible.
Definition at line 38 of file SelectionPolygonVolume.cpp.
References axis_max_, axis_min_, bounding_polygon_, cloudViewer::utility::IJsonConvertible::EigenVector3dFromJsonArray(), LogWarning, and orthogonal_axis_.
ConvertToJsonValue()
bool cloudViewer::visualization::SelectionPolygonVolume::ConvertToJsonValue (Json::Value & value) const override virtual
Implements cloudViewer::utility::IJsonConvertible.
Definition at line 19 of file SelectionPolygonVolume.cpp.
References axis_max_, axis_min_, bounding_polygon_, cloudViewer::utility::IJsonConvertible::EigenVector3dToJsonArray(), and orthogonal_axis_.
CropInPolygon()
std::vector< size_t > cloudViewer::visualization::SelectionPolygonVolume::CropInPolygon (const ccPointCloud & input) const
Function to crop point cloud with polygon boundaries
Parameters
input The input point Cloud.
Definition at line 103 of file SelectionPolygonVolume.cpp.
References cloudViewer::PointCloudTpl< T >::getPoints().
Referenced by cloudViewer::visualization::pybind_visualization_utility().
CropPointCloud()
std::shared_ptr< ccPointCloud > cloudViewer::visualization::SelectionPolygonVolume::CropPointCloud (const ccPointCloud & input) const
Function to crop point cloud.
Parameters
input The input point cloud.
Definition at line 72 of file SelectionPolygonVolume.cpp.
References bounding_polygon_, and orthogonal_axis_.
Referenced by cloudViewer::visualization::pybind_visualization_utility().
CropTriangleMesh()
std::shared_ptr< ccMesh > cloudViewer::visualization::SelectionPolygonVolume::CropTriangleMesh (const ccMesh & input) const
Function to crop crop triangle mesh.
Parameters
input The input triangle mesh.
Definition at line 84 of file SelectionPolygonVolume.cpp.
References bounding_polygon_, ccMesh::getAssociatedCloud(), LogWarning, orthogonal_axis_, and ccMesh::size().
Referenced by cloudViewer::visualization::pybind_visualization_utility().
Member Data Documentation
axis_max_
double cloudViewer::visualization::SelectionPolygonVolume::axis_max_ = 0.0
Maximum axis value.
Definition at line 67 of file SelectionPolygonVolume.h.
Referenced by ConvertFromJsonValue(), ConvertToJsonValue(), and cloudViewer::visualization::pybind_visualization_utility().
axis_min_
double cloudViewer::visualization::SelectionPolygonVolume::axis_min_ = 0.0
Minimum axis value.
Definition at line 65 of file SelectionPolygonVolume.h.
Referenced by ConvertFromJsonValue(), ConvertToJsonValue(), and cloudViewer::visualization::pybind_visualization_utility().
bounding_polygon_
std::vector<Eigen::Vector3d> cloudViewer::visualization::SelectionPolygonVolume::bounding_polygon_
Bounding polygon boundary.
Definition at line 63 of file SelectionPolygonVolume.h.
Referenced by ConvertFromJsonValue(), ConvertToJsonValue(), CropPointCloud(), CropTriangleMesh(), and cloudViewer::visualization::pybind_visualization_utility().
orthogonal_axis_
std::string cloudViewer::visualization::SelectionPolygonVolume::orthogonal_axis_ = ""
One of {x, y, z}.
Definition at line 61 of file SelectionPolygonVolume.h.
Referenced by ConvertFromJsonValue(), ConvertToJsonValue(), CropPointCloud(), CropTriangleMesh(), and cloudViewer::visualization::pybind_visualization_utility().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/utility/SelectionPolygonVolume.h
/root/ACloudViewer/libs/cloudViewer/visualization/utility/SelectionPolygonVolume.cpp