ACloudViewer: Utils::ColorSeries Class Reference
Utils::ColorSeries Class Reference
#include <colorseries.h>
Public Types
enum Scheme {
Spectrum , Warm , Cool , Blues ,
WildFlower , Citrus
}
Public Member Functions
ColorSeries ()
~ColorSeries ()
void setScheme (Scheme scheme)
Scheme scheme () const
QColor color (int index) const
QColor nextColor () const
Detailed Description
Definition at line 17 of file colorseries.h.
Member Enumeration Documentation
Scheme
enum Utils::ColorSeries::Scheme
Enumerator
Spectrum
Warm
Cool
Blues
WildFlower
Citrus
Definition at line 19 of file colorseries.h.
Constructor & Destructor Documentation
ColorSeries()
Utils::ColorSeries::ColorSeries ()
Definition at line 65 of file colorseries.cpp.
~ColorSeries()
Utils::ColorSeries::~ColorSeries ()
Definition at line 67 of file colorseries.cpp.
Member Function Documentation
color()
QColor Utils::ColorSeries::color (int index) const
Definition at line 78 of file colorseries.cpp.
References ecvColor::black(), Blues, Citrus, Cool, Spectrum, Warm, and WildFlower.
Referenced by nextColor().
nextColor()
QColor Utils::ColorSeries::nextColor () const
Definition at line 108 of file colorseries.cpp.
References color().
Referenced by cvProbeFilter::apply().
scheme()
ColorSeries::Scheme Utils::ColorSeries::scheme () const
Definition at line 76 of file colorseries.cpp.
Referenced by setScheme().
setScheme()
void Utils::ColorSeries::setScheme (ColorSeries::Scheme scheme)
Definition at line 69 of file colorseries.cpp.
References scheme().
Referenced by cvProbeFilter::apply().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/colorseries.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/colorseries.cpp