ACloudViewer: ccExportCoordToSFDlg Class Reference
ccExportCoordToSFDlg Class Reference
Dialog to choose which dimension(s) (X, Y or Z) should be exported as SF(s)
#include <ecvExportCoordToSFDlg.h>
Public Member Functions
ccExportCoordToSFDlg (QWidget *parent=0)
Default constructor.
bool exportX () const
Returns whether X dimension should be exported.
bool exportY () const
Returns whether Y dimension should be exported.
bool exportZ () const
Returns whether Z dimension should be exported.
Detailed Description
Dialog to choose which dimension(s) (X, Y or Z) should be exported as SF(s)
Definition at line 13 of file ecvExportCoordToSFDlg.h.
Constructor & Destructor Documentation
ccExportCoordToSFDlg()
ccExportCoordToSFDlg::ccExportCoordToSFDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 10 of file ecvExportCoordToSFDlg.cpp.
Member Function Documentation
exportX()
bool ccExportCoordToSFDlg::exportX () const
Returns whether X dimension should be exported.
Definition at line 15 of file ecvExportCoordToSFDlg.cpp.
Referenced by ccEntityAction::exportCoordToSF(), ccEntityAction::exportNormalToSF(), and ccEntityAction::sfSetAsCoord().
exportY()
bool ccExportCoordToSFDlg::exportY () const
Returns whether Y dimension should be exported.
Definition at line 17 of file ecvExportCoordToSFDlg.cpp.
Referenced by ccEntityAction::exportCoordToSF(), ccEntityAction::exportNormalToSF(), and ccEntityAction::sfSetAsCoord().
exportZ()
bool ccExportCoordToSFDlg::exportZ () const
Returns whether Z dimension should be exported.
Definition at line 19 of file ecvExportCoordToSFDlg.cpp.
Referenced by ccEntityAction::exportCoordToSF(), ccEntityAction::exportNormalToSF(), and ccEntityAction::sfSetAsCoord().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvExportCoordToSFDlg.h
/root/ACloudViewer/app/ecvExportCoordToSFDlg.cpp