ACloudViewer: cloudViewer::StaticVector< T > Class Template Reference
cloudViewer::StaticVector< T > Class Template Reference
#include <StaticVector.h>
Public Member Functions
StaticVector ()
StaticVector (int n)
StaticVector (int n, const T &value)
const T & operator[] (int index) const
T & operator[] (int index)
void clear ()
Iterator begin ()
Iterator end ()
ConstIterator begin () const
ConstIterator end () const
Reference front ()
ConstReference front () const
Reference back ()
ConstReference back () const
const std::vector< T > & getData () const
std::vector< T > & getDataWritable ()
int size () const
bool empty () const
size_t capacity () const
void reserve (int n)
void resize (int n)
void resize (int n, T value)
void resize_with (int n, const T &val)
void swap (StaticVector &other)
void assign (int n, T value)
void shrink_to_fit ()
void reserveAddIfNeeded (int nplanned, int ntoallocated)
void reserveAdd (int ntoallocated)
void push_back (const T &val)
void push_front (const T &val)
void push_back_arr (StaticVector< T > *arr)
void push_back_arr (StaticVector< T > &arr)
void remove (int i)
int push_back_distinct (const T &val)
T pop ()
int indexOf (const T &value) const
int indexOfSorted (const T &value) const
int indexOfNearestSorted (const T &value) const
int minValId () const
int maxValId () const
Detailed Description
template<class T>
class cloudViewer::StaticVector< T >
Definition at line 26 of file StaticVector.h.
Constructor & Destructor Documentation
StaticVector() [1/3]
template<class T > cloudViewer::StaticVector< T >::StaticVector () inline
Definition at line 35 of file StaticVector.h.
StaticVector() [2/3]
template<class T > cloudViewer::StaticVector< T >::StaticVector (int n) inline
Definition at line 37 of file StaticVector.h.
StaticVector() [3/3]
template<class T > cloudViewer::StaticVector< T >::StaticVector (int n, const T & value) inline
Definition at line 39 of file StaticVector.h.
Member Function Documentation
assign()
template<class T > void cloudViewer::StaticVector< T >::assign (int n, T value) inline
Definition at line 69 of file StaticVector.h.
back() [1/2]
template<class T > Reference cloudViewer::StaticVector< T >::back () inline
Definition at line 56 of file StaticVector.h.
back() [2/2]
template<class T > ConstReference cloudViewer::StaticVector< T >::back () const inline
Definition at line 57 of file StaticVector.h.
begin() [1/2]
template<class T > Iterator cloudViewer::StaticVector< T >::begin () inline
Definition at line 47 of file StaticVector.h.
begin() [2/2]
template<class T > ConstIterator cloudViewer::StaticVector< T >::begin () const inline
Definition at line 50 of file StaticVector.h.
capacity()
template<class T > size_t cloudViewer::StaticVector< T >::capacity () const inline
Definition at line 63 of file StaticVector.h.
clear()
template<class T > void cloudViewer::StaticVector< T >::clear () inline
Definition at line 45 of file StaticVector.h.
empty()
template<class T > bool cloudViewer::StaticVector< T >::empty () const inline
Definition at line 62 of file StaticVector.h.
Referenced by cloudViewer::saveArrayOfArraysToFile(), and cloudViewer::sizeOfStaticVector().
end() [1/2]
template<class T > Iterator cloudViewer::StaticVector< T >::end () inline
Definition at line 48 of file StaticVector.h.
end() [2/2]
template<class T > ConstIterator cloudViewer::StaticVector< T >::end () const inline
Definition at line 51 of file StaticVector.h.
front() [1/2]
template<class T > Reference cloudViewer::StaticVector< T >::front () inline
Definition at line 53 of file StaticVector.h.
front() [2/2]
template<class T > ConstReference cloudViewer::StaticVector< T >::front () const inline
Definition at line 54 of file StaticVector.h.
getData()
template<class T > const std::vector<T>& cloudViewer::StaticVector< T >::getData () const inline
Definition at line 59 of file StaticVector.h.
Referenced by cloudViewer::StaticVector< T >::push_back_arr().
getDataWritable()
template<class T > std::vector<T>& cloudViewer::StaticVector< T >::getDataWritable () inline
Definition at line 60 of file StaticVector.h.
indexOf()
template<class T > int cloudViewer::StaticVector< T >::indexOf (const T & value) const inline
Definition at line 109 of file StaticVector.h.
indexOfNearestSorted()
template<class T > int cloudViewer::StaticVector< T >::indexOfNearestSorted (const T & value) const inline
Definition at line 116 of file StaticVector.h.
indexOfSorted()
template<class T > int cloudViewer::StaticVector< T >::indexOfSorted (const T & value) const inline
Definition at line 114 of file StaticVector.h.
References cloudViewer::indexOf().
maxValId()
template<class T > int cloudViewer::StaticVector< T >::maxValId () const inline
Definition at line 136 of file StaticVector.h.
minValId()
template<class T > int cloudViewer::StaticVector< T >::minValId () const inline
Definition at line 130 of file StaticVector.h.
operator[]() [1/2]
template<class T > T& cloudViewer::StaticVector< T >::operator[] (int index) inline
Definition at line 43 of file StaticVector.h.
operator[]() [2/2]
template<class T > const T& cloudViewer::StaticVector< T >::operator[] (int index) const inline
Definition at line 41 of file StaticVector.h.
pop()
template<class T > T cloudViewer::StaticVector< T >::pop () inline
Definition at line 103 of file StaticVector.h.
push_back()
template<class T > void cloudViewer::StaticVector< T >::push_back (const T & val) inline
Definition at line 83 of file StaticVector.h.
Referenced by cloudViewer::cloneArrayOfArrays().
push_back_arr() [1/2]
template<class T > void cloudViewer::StaticVector< T >::push_back_arr (StaticVector< T > & arr) inline
Definition at line 91 of file StaticVector.h.
References cloudViewer::StaticVector< T >::getData().
push_back_arr() [2/2]
template<class T > void cloudViewer::StaticVector< T >::push_back_arr (StaticVector< T > * arr) inline
Definition at line 87 of file StaticVector.h.
References cloudViewer::StaticVector< T >::getData().
Referenced by cloudViewer::cloneArrayOfArrays().
push_back_distinct()
template<class T > int cloudViewer::StaticVector< T >::push_back_distinct (const T & val) inline
Definition at line 97 of file StaticVector.h.
References cloudViewer::indexOf().
push_front()
template<class T > void cloudViewer::StaticVector< T >::push_front (const T & val) inline
Definition at line 85 of file StaticVector.h.
remove()
template<class T > void cloudViewer::StaticVector< T >::remove (int i) inline
Definition at line 95 of file StaticVector.h.
reserve()
template<class T > void cloudViewer::StaticVector< T >::reserve (int n) inline
Definition at line 64 of file StaticVector.h.
Referenced by cloudViewer::cloneArrayOfArrays(), and cloudViewer::loadArrayOfArraysFromFile().
reserveAdd()
template<class T > void cloudViewer::StaticVector< T >::reserveAdd (int ntoallocated) inline
Definition at line 79 of file StaticVector.h.
reserveAddIfNeeded()
template<class T > void cloudViewer::StaticVector< T >::reserveAddIfNeeded (int nplanned, int ntoallocated) inline
Definition at line 73 of file StaticVector.h.
References size.
resize() [1/2]
template<class T > void cloudViewer::StaticVector< T >::resize (int n) inline
Definition at line 65 of file StaticVector.h.
Referenced by cloudViewer::loadArrayFromFile(), and cloudViewer::loadArrayOfArraysFromFile().
resize() [2/2]
template<class T > void cloudViewer::StaticVector< T >::resize (int n, T value) inline
Definition at line 66 of file StaticVector.h.
resize_with()
template<class T > void cloudViewer::StaticVector< T >::resize_with (int n, const T & val) inline
Definition at line 67 of file StaticVector.h.
Referenced by cloudViewer::loadArrayOfArraysFromFile().
shrink_to_fit()
template<class T > void cloudViewer::StaticVector< T >::shrink_to_fit () inline
Definition at line 71 of file StaticVector.h.
size()
template<class T > int cloudViewer::StaticVector< T >::size () const inline
Definition at line 61 of file StaticVector.h.
Referenced by cloudViewer::loadArrayFromFileIntoArray(), cloudViewer::saveArrayOfArraysToFile(), cloudViewer::saveArrayToFile(), and cloudViewer::sizeOfStaticVector().
swap()
template<class T > void cloudViewer::StaticVector< T >::swap (StaticVector< T > & other) inline
Definition at line 68 of file StaticVector.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/StaticVector.h