ACloudViewer: PCVCommand Class Reference
PCVCommand Class Reference
#include <PCVCommand.h>
Public Member Functions
PCVCommand ()
~PCVCommand () override=default
bool process (ccCommandLineInterface &cmd) override
Main process.
Public Member Functions inherited from ccCommandLineInterface::Command
Command (const QString &name, const QString &keyword)
Default constructor.
virtual ~Command ()=default
Static Public Member Functions
static bool Process (const ccHObject::Container &candidates, const std::vector< CCVector3 > &rays, bool meshIsClosed, unsigned resolution, ecvProgressDialog *progressDlg=nullptr, ecvMainAppInterface *app=nullptr)
Additional Inherited Members
Public Types inherited from ccCommandLineInterface::Command
using Shared = QSharedPointer< Command >
Shared type.
Public Attributes inherited from ccCommandLineInterface::Command
QString m_name
Command name.
QString m_keyword
Command keyword.
Detailed Description
Definition at line 35 of file PCVCommand.h.
Constructor & Destructor Documentation
PCVCommand()
PCVCommand::PCVCommand ()
Definition at line 29 of file PCVCommand.cpp.
~PCVCommand()
PCVCommand::~PCVCommand () override default
Member Function Documentation
process()
bool PCVCommand::process (ccCommandLineInterface & cmd) override virtual
Main process.
Implements ccCommandLineInterface::Command.
Definition at line 148 of file PCVCommand.cpp.
References ccCommandLineInterface::arguments(), ccCommandLineInterface::autoSaveMode(), ccCommandLineInterface::clouds(), COMMAND_PCV_180, COMMAND_PCV_IS_CLOSED, COMMAND_PCV_N_RAYS, COMMAND_PCV_RESOLUTION, ccCommandLineInterface::error(), ccCommandLineInterface::exportEntity(), PCV::GenerateRays(), ccCommandLineInterface::IsCommand(), ccCommandLineInterface::meshes(), ccCommandLineInterface::print(), and Process().
Process()
bool PCVCommand::Process (const ccHObject::Container & candidates, const std::vector< CCVector3 > & rays, bool meshIsClosed, unsigned resolution, ecvProgressDialog * progressDlg = nullptr, ecvMainAppInterface * app = nullptr) static
Definition at line 31 of file PCVCommand.cpp.
References ccPointCloud::addScalarField(), CC_PCV_FIELD_LABEL_NAME, ccScalarField::computeMinAndMax(), count, ccPointCloud::deleteScalarField(), ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, ccGenericMesh::getAssociatedCloud(), ccColorScalesManager::GetDefaultScale(), ccObject::getName(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), ccColorScalesManager::GREY, PCV::Launch(), CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, ccScalarField::setColorScale(), ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentScalarField(), ccDrawableObject::showSF(), ccHObjectCaster::ToGenericMesh(), ccHObjectCaster::ToPointCloud(), and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by process().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCV/include/PCVCommand.h
/root/ACloudViewer/plugins/core/Standard/qPCV/src/PCVCommand.cpp