ACloudViewer: StereogramWidget Class Reference
StereogramWidget Class Reference
Orientation-based classification widget.
#include <stereogramDlg.h>
Signals
void pointClicked (double dip_deg, double dipDir_deg)
Signal emitted when the mouse (left) button is clicked.
Public Member Functions
StereogramWidget (QWidget *parent=0)
Default constructor.
virtual ~StereogramWidget ()
Destructor.
bool init (double angularStep_deg, ccHObject *facetGroup, double resolution_deg=2.0)
Sets current parameters.
void getMeanDir (double &meanDip_deg, double &meanDipDir_deg)
Returns the mean dip direction and dip.
virtual int heightForWidth (int w) const
void setDensityColorScale (ccColorScale::Shared colorScale)
Sets density color scale.
ccColorScale::Shared getDensityColorScale () const
Returns density color scale.
void setDensityColorScaleSteps (unsigned steps)
Sets density color scale steps.
unsigned getDensityColorScaleSteps () const
Returns density color scale steps.
void setTicksFreq (int freq)
Sets the ticks frequency (0 = no ticks)
void showHSVRing (bool state)
Whether to show the 'HSV' ring or not.
void enableMouseTracking (bool state, double dipSpan_deg=30, double dipDirSpan_deg=30)
Enables or not the mouse tracking mode.
void setTrackedCenter (double dip_deg, double dipDir_deg)
Sets tracked center position.
Protected Member Functions
virtual void paintEvent (QPaintEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
Protected Attributes
double m_angularStep_deg
Angular step (in degrees)
FacetDensityGrid * m_densityGrid
Density grid.
double m_meanDipDir_deg
Mean dip direction (in degrees)
double m_meanDip_deg
Mean dip (in degrees)
ccColorScale::Shared m_densityColorScale
Density color scale.
unsigned m_densityColorScaleSteps
Density color scale steps.
int m_ticksFreq
Ticks frequency.
bool m_showHSVRing
Whether to show the 'HSV' ring or not.
bool m_trackMouseClick
Mouse tracking.
double m_clickDip_deg
Last mouse click equivalent dip (in degrees)
double m_clickDipDir_deg
Last mouse click equivalent dip direction (in degrees)
double m_clickDipSpan_deg
Click area span along dip (in degrees)
double m_clickDipDirSpan_deg
Click area span along dip direction (in degrees)
QPoint m_center
Stereogram center (pixels)
int m_radius
Stereogram radius (pixels)
Detailed Description
Orientation-based classification widget.
Definition at line 39 of file stereogramDlg.h.
Constructor & Destructor Documentation
StereogramWidget()
StereogramWidget::StereogramWidget (QWidget * parent = 0)
Default constructor.
Definition at line 61 of file stereogramDlg.cpp.
~StereogramWidget()
StereogramWidget::~StereogramWidget () virtual
Destructor.
Definition at line 90 of file stereogramDlg.cpp.
References m_densityGrid.
Member Function Documentation
enableMouseTracking()
void StereogramWidget::enableMouseTracking (bool state, double dipSpan_deg = 30, double dipDirSpan_deg = 30)
Enables or not the mouse tracking mode.
Definition at line 294 of file stereogramDlg.cpp.
References m_clickDip_deg, m_clickDipDir_deg, m_clickDipDirSpan_deg, m_clickDipSpan_deg, m_trackMouseClick, and pointClicked().
Referenced by StereogramDialog::onFilterEnabled(), and StereogramDialog::onFilterSizeChanged().
getDensityColorScale()
ccColorScale::Shared StereogramWidget::getDensityColorScale () const inline
Returns density color scale.
Definition at line 68 of file stereogramDlg.h.
References m_densityColorScale.
getDensityColorScaleSteps()
unsigned StereogramWidget::getDensityColorScaleSteps () const inline
Returns density color scale steps.
Definition at line 76 of file stereogramDlg.h.
References m_densityColorScaleSteps.
getMeanDir()
void StereogramWidget::getMeanDir (double & meanDip_deg, double & meanDipDir_deg) inline
Returns the mean dip direction and dip.
Definition at line 55 of file stereogramDlg.h.
References m_meanDip_deg, and m_meanDipDir_deg.
Referenced by StereogramDialog::init().
heightForWidth()
virtual int StereogramWidget::heightForWidth (int w) const inline virtual
Definition at line 61 of file stereogramDlg.h.
init()
bool StereogramWidget::init (double angularStep_deg, ccHObject * facetGroup, double resolution_deg = 2.0)
Sets current parameters.
Definition at line 94 of file stereogramDlg.cpp.
References cloudViewer::utility::ceil(), ccNormalVectors::ConvertNormalToDipAndDipDir(), count, FacetDensityGrid::ddSteps, cloudViewer::DegreesToRadians(), CV_TYPES::FACET, ccHObject::filterChildren(), cloudViewer::utility::floor(), ccFacet::getNormal(), ccPlane::getNormal(), ccPointCloud::getPointNormal(), ccFacet::getSurface(), FacetDensityGrid::grid, ccPointCloud::hasNormals(), CV_TYPES::HIERARCHY_OBJECT, ccObject::isA(), m_angularStep_deg, m_clickDip_deg, m_clickDipDir_deg, m_densityGrid, m_meanDip_deg, m_meanDipDir_deg, FacetDensityGrid::minMaxDensity, Vector3Tpl< Type >::normalize(), nProgress, cloudViewer::NormalizedProgress::oneStep(), CV_TYPES::PLANE, CV_TYPES::POINT_CLOUD, FacetDensityGrid::rSteps, ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), cloudViewer::PointCloudTpl< T >::size(), ecvProgressDialog::start(), FacetDensityGrid::step_deg, FacetDensityGrid::step_R, ecvProgressDialog::stop(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by StereogramDialog::init().
mousePressEvent()
void StereogramWidget::mousePressEvent (QMouseEvent * e) protected virtual
Definition at line 263 of file stereogramDlg.cpp.
References e, m_center, m_clickDip_deg, m_clickDipDir_deg, m_radius, m_trackMouseClick, pointClicked(), and cloudViewer::RadiansToDegrees().
paintEvent()
void StereogramWidget::paintEvent (QPaintEvent * e) protected virtual
Definition at line 312 of file stereogramDlg.cpp.
References ecvColor::RgbTpl< Type >::b, ecvColor::black(), cloudViewer::utility::ceil(), FacetDensityGrid::ddSteps, cloudViewer::DegreesToRadians(), event, ecvColor::RgbTpl< Type >::g, FacetsClassifier::GenerateSubfamilyColor(), FacetDensityGrid::grid, height, m_angularStep_deg, m_center, m_clickDip_deg, m_clickDipDir_deg, m_clickDipDirSpan_deg, m_clickDipSpan_deg, m_densityColorScale, m_densityColorScaleSteps, m_densityGrid, m_meanDipDir_deg, m_radius, m_showHSVRing, m_ticksFreq, m_trackMouseClick, ecvColor::magenta(), FacetDensityGrid::minMaxDensity, ecvColor::RgbTpl< Type >::r, ecvColor::red(), FacetDensityGrid::rSteps, FacetDensityGrid::step_deg, FacetDensityGrid::step_R, ecvColor::white(), width, and X.
pointClicked
void StereogramWidget::pointClicked (double dip_deg, double dipDir_deg) signal
Signal emitted when the mouse (left) button is clicked.
Parameters
dip_deg dip angle (in degrees)
dipDir_deg dip direction angle (in degrees)
Referenced by enableMouseTracking(), and mousePressEvent().
setDensityColorScale()
void StereogramWidget::setDensityColorScale (ccColorScale::Shared colorScale) inline
Sets density color scale.
Definition at line 64 of file stereogramDlg.h.
References m_densityColorScale.
Referenced by StereogramDialog::colorScaleChanged(), and StereogramDialog::StereogramDialog().
setDensityColorScaleSteps()
void StereogramWidget::setDensityColorScaleSteps (unsigned steps) inline
Sets density color scale steps.
Definition at line 72 of file stereogramDlg.h.
References m_densityColorScaleSteps.
Referenced by StereogramDialog::colorScaleChanged(), and StereogramDialog::onDensityColorStepsChanged().
setTicksFreq()
void StereogramWidget::setTicksFreq (int freq) inline
Sets the ticks frequency (0 = no ticks)
Definition at line 81 of file stereogramDlg.h.
References m_ticksFreq.
Referenced by StereogramDialog::onTicksFreqChanged(), and StereogramDialog::StereogramDialog().
setTrackedCenter()
void StereogramWidget::setTrackedCenter (double dip_deg, double dipDir_deg)
Sets tracked center position.
Definition at line 307 of file stereogramDlg.cpp.
References m_clickDip_deg, and m_clickDipDir_deg.
Referenced by StereogramDialog::onFilterCenterChanged().
showHSVRing()
void StereogramWidget::showHSVRing (bool state) inline
Whether to show the 'HSV' ring or not.
Definition at line 84 of file stereogramDlg.h.
References m_showHSVRing.
Referenced by StereogramDialog::onHSVColorsToggled().
Member Data Documentation
m_angularStep_deg
double StereogramWidget::m_angularStep_deg protected
Angular step (in degrees)
Definition at line 108 of file stereogramDlg.h.
Referenced by init(), and paintEvent().
m_center
QPoint StereogramWidget::m_center protected
Stereogram center (pixels)
Definition at line 141 of file stereogramDlg.h.
Referenced by mousePressEvent(), and paintEvent().
m_clickDip_deg
double StereogramWidget::m_clickDip_deg protected
Last mouse click equivalent dip (in degrees)
Definition at line 132 of file stereogramDlg.h.
Referenced by enableMouseTracking(), init(), mousePressEvent(), paintEvent(), and setTrackedCenter().
m_clickDipDir_deg
double StereogramWidget::m_clickDipDir_deg protected
Last mouse click equivalent dip direction (in degrees)
Definition at line 134 of file stereogramDlg.h.
Referenced by enableMouseTracking(), init(), mousePressEvent(), paintEvent(), and setTrackedCenter().
m_clickDipDirSpan_deg
double StereogramWidget::m_clickDipDirSpan_deg protected
Click area span along dip direction (in degrees)
Definition at line 138 of file stereogramDlg.h.
Referenced by enableMouseTracking(), and paintEvent().
m_clickDipSpan_deg
double StereogramWidget::m_clickDipSpan_deg protected
Click area span along dip (in degrees)
Definition at line 136 of file stereogramDlg.h.
Referenced by enableMouseTracking(), and paintEvent().
m_densityColorScale
ccColorScale::Shared StereogramWidget::m_densityColorScale protected
Density color scale.
Definition at line 119 of file stereogramDlg.h.
Referenced by getDensityColorScale(), paintEvent(), and setDensityColorScale().
m_densityColorScaleSteps
unsigned StereogramWidget::m_densityColorScaleSteps protected
Density color scale steps.
Definition at line 121 of file stereogramDlg.h.
Referenced by getDensityColorScaleSteps(), paintEvent(), and setDensityColorScaleSteps().
m_densityGrid
FacetDensityGrid* StereogramWidget::m_densityGrid protected
Density grid.
Definition at line 111 of file stereogramDlg.h.
Referenced by init(), paintEvent(), and ~StereogramWidget().
m_meanDip_deg
double StereogramWidget::m_meanDip_deg protected
Mean dip (in degrees)
Definition at line 116 of file stereogramDlg.h.
Referenced by getMeanDir(), and init().
m_meanDipDir_deg
double StereogramWidget::m_meanDipDir_deg protected
Mean dip direction (in degrees)
Definition at line 114 of file stereogramDlg.h.
Referenced by getMeanDir(), init(), and paintEvent().
m_radius
int StereogramWidget::m_radius protected
Stereogram radius (pixels)
Definition at line 143 of file stereogramDlg.h.
Referenced by mousePressEvent(), and paintEvent().
m_showHSVRing
bool StereogramWidget::m_showHSVRing protected
Whether to show the 'HSV' ring or not.
Definition at line 127 of file stereogramDlg.h.
Referenced by paintEvent(), and showHSVRing().
m_ticksFreq
int StereogramWidget::m_ticksFreq protected
Ticks frequency.
Definition at line 124 of file stereogramDlg.h.
Referenced by paintEvent(), and setTicksFreq().
m_trackMouseClick
bool StereogramWidget::m_trackMouseClick protected
Mouse tracking.
Definition at line 130 of file stereogramDlg.h.
Referenced by enableMouseTracking(), mousePressEvent(), and paintEvent().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qFacets/include/stereogramDlg.h
/root/ACloudViewer/plugins/core/Standard/qFacets/src/stereogramDlg.cpp