ACloudViewer: cloudViewer::visualization::rendering::FilamentMaterialModifier Class Reference
cloudViewer::visualization::rendering::FilamentMaterialModifier Class Reference
#include <FilamentEntitiesMods.h>
Public Member Functions
FilamentMaterialModifier (const std::shared_ptr< filament::MaterialInstance > &material_instance, const MaterialInstanceHandle &id)
FilamentMaterialModifier ()=default
void Reset ()
void Init (const std::shared_ptr< filament::MaterialInstance > &material_instance, const MaterialInstanceHandle &id)
MaterialModifier & SetParameter (const char *parameter, int value) override
MaterialModifier & SetParameter (const char *parameter, float value) override
MaterialModifier & SetParameter (const char *parameter, const Eigen::Vector3f &value) override
MaterialModifier & SetColor (const char *parameter, const Eigen::Vector3f &value, bool srgb) override
MaterialModifier & SetColor (const char *parameter, const Eigen::Vector4f &value, bool srgb) override
MaterialModifier & SetTexture (const char *parameter, const TextureHandle &texture, const TextureSamplerParameters &sampler) override
MaterialModifier & SetDoubleSided (bool double_sided) override
MaterialInstanceHandle Finish () override
Public Member Functions inherited from cloudViewer::visualization::rendering::MaterialModifier
virtual ~MaterialModifier ()=default
Static Public Member Functions
static filament::TextureSampler SamplerFromSamplerParameters (const TextureSamplerParameters &sampler_config)
Detailed Description
Definition at line 25 of file FilamentEntitiesMods.h.
Constructor & Destructor Documentation
FilamentMaterialModifier() [1/2]
cloudViewer::visualization::rendering::FilamentMaterialModifier::FilamentMaterialModifier (const std::shared_ptr< filament::MaterialInstance > & material_instance, const MaterialInstanceHandle & id)
Definition at line 99 of file FilamentEntitiesMods.cpp.
References Init().
FilamentMaterialModifier() [2/2]
cloudViewer::visualization::rendering::FilamentMaterialModifier::FilamentMaterialModifier () default
Member Function Documentation
Finish()
MaterialInstanceHandle cloudViewer::visualization::rendering::FilamentMaterialModifier::Finish () override virtual
Implements cloudViewer::visualization::rendering::MaterialModifier.
Definition at line 211 of file FilamentEntitiesMods.cpp.
References cloudViewer::visualization::rendering::REHandle< EntityType::MaterialInstance >::kBad.
Init()
void cloudViewer::visualization::rendering::FilamentMaterialModifier::Init (const std::shared_ptr< filament::MaterialInstance > & material_instance, const MaterialInstanceHandle & id)
Definition at line 115 of file FilamentEntitiesMods.cpp.
References LogWarning.
Referenced by FilamentMaterialModifier().
Reset()
void cloudViewer::visualization::rendering::FilamentMaterialModifier::Reset ()
Definition at line 105 of file FilamentEntitiesMods.cpp.
References cloudViewer::visualization::rendering::REHandle< EntityType::MaterialInstance >::kBad, and LogWarning.
SamplerFromSamplerParameters()
TextureSampler cloudViewer::visualization::rendering::FilamentMaterialModifier::SamplerFromSamplerParameters (const TextureSamplerParameters & sampler_config) static
Definition at line 52 of file FilamentEntitiesMods.cpp.
References cloudViewer::visualization::rendering::TextureSamplerParameters::filter_mag, cloudViewer::visualization::rendering::TextureSamplerParameters::filter_min, cloudViewer::visualization::rendering::TextureSamplerParameters::Linear, cloudViewer::visualization::rendering::TextureSamplerParameters::LinearMipmapLinear, cloudViewer::visualization::rendering::TextureSamplerParameters::LinearMipmapNearest, cloudViewer::visualization::rendering::TextureSamplerParameters::Nearest, cloudViewer::visualization::rendering::TextureSamplerParameters::NearestMipmapLinear, cloudViewer::visualization::rendering::TextureSamplerParameters::NearestMipmapNearest, cloudViewer::visualization::rendering::TextureSamplerParameters::wrap_u, cloudViewer::visualization::rendering::TextureSamplerParameters::wrap_v, and cloudViewer::visualization::rendering::TextureSamplerParameters::wrap_w.
Referenced by SetTexture().
SetColor() [1/2]
MaterialModifier & cloudViewer::visualization::rendering::FilamentMaterialModifier::SetColor (const char * parameter, const Eigen::Vector3f & value, bool srgb) override virtual
Implements cloudViewer::visualization::rendering::MaterialModifier.
Definition at line 155 of file FilamentEntitiesMods.cpp.
References color.
SetColor() [2/2]
MaterialModifier & cloudViewer::visualization::rendering::FilamentMaterialModifier::SetColor (const char * parameter, const Eigen::Vector4f & value, bool srgb) override virtual
Implements cloudViewer::visualization::rendering::MaterialModifier.
Definition at line 168 of file FilamentEntitiesMods.cpp.
References color.
SetDoubleSided()
MaterialModifier & cloudViewer::visualization::rendering::FilamentMaterialModifier::SetDoubleSided (bool double_sided) override virtual
Implements cloudViewer::visualization::rendering::MaterialModifier.
Definition at line 204 of file FilamentEntitiesMods.cpp.
SetParameter() [1/3]
MaterialModifier & cloudViewer::visualization::rendering::FilamentMaterialModifier::SetParameter (const char * parameter, const Eigen::Vector3f & value) override virtual
Implements cloudViewer::visualization::rendering::MaterialModifier.
Definition at line 145 of file FilamentEntitiesMods.cpp.
SetParameter() [2/3]
MaterialModifier & cloudViewer::visualization::rendering::FilamentMaterialModifier::SetParameter (const char * parameter, float value) override virtual
Implements cloudViewer::visualization::rendering::MaterialModifier.
Definition at line 136 of file FilamentEntitiesMods.cpp.
SetParameter() [3/3]
MaterialModifier & cloudViewer::visualization::rendering::FilamentMaterialModifier::SetParameter (const char * parameter, int value) override virtual
Implements cloudViewer::visualization::rendering::MaterialModifier.
Definition at line 127 of file FilamentEntitiesMods.cpp.
Referenced by cloudViewer::visualization::rendering::FilamentView::PreRender().
SetTexture()
MaterialModifier & cloudViewer::visualization::rendering::FilamentMaterialModifier::SetTexture (const char * parameter, const TextureHandle & texture, const TextureSamplerParameters & sampler) override virtual
Implements cloudViewer::visualization::rendering::MaterialModifier.
Definition at line 181 of file FilamentEntitiesMods.cpp.
References cloudViewer::visualization::rendering::EngineInstance::GetResourceManager(), cloudViewer::visualization::rendering::FilamentResourceManager::GetTexture(), LogWarning, and SamplerFromSamplerParameters().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentEntitiesMods.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentEntitiesMods.cpp