ACloudViewer: colmap::FundamentalMatrixSevenPointEstimator Class Reference
colmap::FundamentalMatrixSevenPointEstimator Class Reference
#include <fundamental_matrix.h>
Public Types
typedef Eigen::Vector2d X_t
typedef Eigen::Vector2d Y_t
typedef Eigen::Matrix3d M_t
Static Public Member Functions
static std::vector< M_t > Estimate (const std::vector< X_t > &points1, const std::vector< Y_t > &points2)
static void Residuals (const std::vector< X_t > &points1, const std::vector< Y_t > &points2, const M_t &F, std::vector< double > *residuals)
Static Public Attributes
static const int kMinNumSamples = 7
Detailed Description
Definition at line 27 of file fundamental_matrix.h.
Member Typedef Documentation
M_t
typedef Eigen::Matrix3d colmap::FundamentalMatrixSevenPointEstimator::M_t
Definition at line 31 of file fundamental_matrix.h.
X_t
typedef Eigen::Vector2d colmap::FundamentalMatrixSevenPointEstimator::X_t
Definition at line 29 of file fundamental_matrix.h.
Y_t
typedef Eigen::Vector2d colmap::FundamentalMatrixSevenPointEstimator::Y_t
Definition at line 30 of file fundamental_matrix.h.
Member Function Documentation
Estimate()
std::vector< FundamentalMatrixSevenPointEstimator::M_t > colmap::FundamentalMatrixSevenPointEstimator::Estimate (const std::vector< X_t > & points1, const std::vector< Y_t > & points2) static
Definition at line 49 of file fundamental_matrix.cc.
References coeffs(), e, and colmap::FindPolynomialRootsCompanionMatrix().
Referenced by BOOST_AUTO_TEST_CASE().
Residuals()
void colmap::FundamentalMatrixSevenPointEstimator::Residuals (const std::vector< X_t > & points1, const std::vector< Y_t > & points2, const M_t & F, std::vector< double > * residuals) static
Definition at line 145 of file fundamental_matrix.cc.
References colmap::ComputeSquaredSampsonError().
Member Data Documentation
kMinNumSamples
const int colmap::FundamentalMatrixSevenPointEstimator::kMinNumSamples = 7 static
Definition at line 34 of file fundamental_matrix.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/estimators/fundamental_matrix.h
/root/ACloudViewer/libs/Reconstruction/src/estimators/fundamental_matrix.cc