ACloudViewer: RegionGrowingSegmentation Class Reference
RegionGrowingSegmentation Class Reference
Region Growing Segmentation.
#include <RegionGrowingSegmentation.h>
Public Member Functions
RegionGrowingSegmentation ()
virtual ~RegionGrowingSegmentation ()
virtual int compute ()
Performs the actual filter job.
Public Member Functions inherited from BasePclModule
BasePclModule (PclModuleDescription desc=PclModuleDescription(), ccPluginInterface *parent_plugin=0)
Default constructor.
QAction * getAction ()
Get the action associated with the button used in menu and toolbar creation.
QString getStatusTip () const
Returns the status tip.
QString getModuleName () const
Returns the name of the filter.
QString getEntryName () const
Returns the entry name.
QIcon getIcon () const
Returns the icon associated with the button.
void setShowProgressBar (bool status)
Sets whether to show a progressbar while computing or not.
std::vector< std::string > getSelectedAvailableScalarFields ()
ccPointCloud * getSelectedEntityAsCCPointCloud () const
Returns the first selected entity as a ccPointCloud.
ccHObject * getSelectedEntityAsCCHObject () const
Returns the first selected entity as a ccHObject.
ccHObject::Container getSelectedThatHaveMetaData (const QString key) const
Get selected object that also have the provided metadata key.
void getAllEntitiesOfType (CV_CLASS_ENUM type, ccHObject::Container &entities)
Returns all the objects in db tree of type "type".
void getAllEntitiesThatHaveMetaData (QString key, ccHObject::Container &entities)
void getSelectedEntitiesThatAreCCPointCloud (ccHObject::Container &entities)
get all entities that are selected and that also are cc_point_cloud
void getSelectedEntitiesThatAre (CV_CLASS_ENUM kind, ccHObject::Container &entities)
int hasSelectedRGB ()
Returns 1 if the first selected entity has RGB info.
int hasSelectedScalarField ()
Returns 1 if the first selected entity has at least one scalar field.
int hasSelectedScalarField (std::string field_name)
int isFirstSelectedCcPointCloud ()
Returns 1 if the first selected object is a ccPointCloud.
virtual void updateSelectedEntities (const ccHObject::Container &selectedEntities)
Updates the internal copy of selected entities.
void setMainAppInterface (ecvMainAppInterface *app)
Sets associated CC application interface (to access DB)
ecvMainAppInterface * getMainAppInterface ()
ccPluginInterface * getParentPlugin () const
Returns the associated parent plugin interface.
Protected Member Functions
virtual int checkSelected ()
Checks if current selection is compliant with the filter.
virtual int openInputDialog ()
virtual void getParametersFromDialog ()
Collects parameters from the filter dialog (if openDialog is successful)
virtual int checkParameters ()
virtual QString getErrorMessage (int errorCode)
Returns the error message corresponding to a given error code.
Protected Member Functions inherited from BasePclModule
virtual int openOutputDialog ()
virtual int start ()
Starts computation.
virtual void initAction ()
Initializes the corresponding action.
void throwError (int errCode)
Protected Attributes
RegionGrowingSegmentationDlg * m_dialog
bool m_basedRgb
int m_k_search
int m_min_cluster_size
int m_max_cluster_size
unsigned int m_neighbour_number
float m_smoothness_theta
float m_curvature
int m_min_cluster_size_rgb
float m_neighbors_distance
float m_point_color_diff
float m_region_color_diff
Protected Attributes inherited from BasePclModule
QAction * m_action
Forces the Ui to be updated.
ccHObject::Container m_selected
Pointer to the main window.
PclModuleDescription m_desc
Associated dialog.
ecvMainAppInterface * m_app
Associated application interface.
ccPluginInterface * m_parent_plugin
associated parent plugin of the filter
bool m_show_progress
Do we want to show a progress bar when the filter works?
Additional Inherited Members
Signals inherited from BasePclModule
void entityHasChanged (ccHObject *)
Signal emitted when an entity is (visually) modified.
void newEntity (ccHObject *)
Signal emitted when a new entity is created by the filter.
void newErrorMessage (QString)
Signal emitted when a new error message is produced.
Protected Slots inherited from BasePclModule
int performAction ()
Returns is called when the dialog window is accepted.
Detailed Description
Region Growing Segmentation.
Definition at line 18 of file RegionGrowingSegmentation.h.
Constructor & Destructor Documentation
RegionGrowingSegmentation()
RegionGrowingSegmentation::RegionGrowingSegmentation ()
Definition at line 32 of file RegionGrowingSegmentation.cpp.
~RegionGrowingSegmentation()
RegionGrowingSegmentation::~RegionGrowingSegmentation () virtual
Definition at line 51 of file RegionGrowingSegmentation.cpp.
References m_dialog.
Member Function Documentation
checkParameters()
int RegionGrowingSegmentation::checkParameters () protected virtual
Checks that the parameters retrieved by getParametersFromDialog are valid Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Returns
1 if parameters are valid (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 115 of file RegionGrowingSegmentation.cpp.
checkSelected()
int RegionGrowingSegmentation::checkSelected () protected virtual
Checks if current selection is compliant with the filter.
If not, an error is returned and computation stops. By default, baseclass method simply checks that selection is composed of one and only one ccPointCloud. This method should be overridden if necessary.
Returns
1 if selection is compliant (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 56 of file RegionGrowingSegmentation.cpp.
References BasePclModule::isFirstSelectedCcPointCloud().
compute()
int RegionGrowingSegmentation::compute () virtual
Performs the actual filter job.
This method MUST be re-implemented by derived filter
Returns
1 if successful (error code otherwise)
Implements BasePclModule.
Definition at line 117 of file RegionGrowingSegmentation.cpp.
References ccHObject::addChild(), pcl2cc::Convert(), FROM_PCL_CLOUD, cc2smReader::getAsSM(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccHObject::getParent(), PCLModules::GetRegionGrowing(), PCLModules::GetRegionGrowingRGB(), BasePclModule::getSelectedEntityAsCCPointCloud(), m_basedRgb, m_curvature, m_k_search, m_max_cluster_size, m_min_cluster_size, m_min_cluster_size_rgb, m_neighbors_distance, m_neighbour_number, m_point_color_diff, m_region_color_diff, m_smoothness_theta, name, BasePclModule::newEntity(), result, ccObject::setEnabled(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccObject::setName(), and TO_PCL_CLOUD.
getErrorMessage()
QString RegionGrowingSegmentation::getErrorMessage (int errorCode) protected virtual
Returns the error message corresponding to a given error code.
Each filter have a set of possible error message to be used given bt getFilterErrorMessage() Baseclass implementation provides some generic messages.
Note
These messages can be replaced by re-implementing this method and handling the same codes BEFORE calling the baseclass method
Reimplemented from BasePclModule.
Definition at line 177 of file RegionGrowingSegmentation.cpp.
References BasePclModule::getErrorMessage().
getParametersFromDialog()
void RegionGrowingSegmentation::getParametersFromDialog () protected virtual
Collects parameters from the filter dialog (if openDialog is successful)
Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Reimplemented from BasePclModule.
Definition at line 84 of file RegionGrowingSegmentation.cpp.
References m_basedRgb, m_curvature, m_dialog, m_max_cluster_size, m_min_cluster_size, m_min_cluster_size_rgb, m_neighbors_distance, m_neighbour_number, m_point_color_diff, m_region_color_diff, and m_smoothness_theta.
openInputDialog()
int RegionGrowingSegmentation::openInputDialog () protected virtual
Opens the input dialog window. Where the user can supply parameters for the computation Automatically called by performAction. Does nothing by default. Must be overridden if a dialog must be displayed.
Returns
1 if dialog has been successfully executed, 0 if canceled, negative error code otherwise
Reimplemented from BasePclModule.
Definition at line 64 of file RegionGrowingSegmentation.cpp.
References ecvMainAppInterface::getActiveWindow(), BasePclModule::getSelectedEntityAsCCPointCloud(), ccPointCloud::hasColors(), ccPointCloud::hasScalarFields(), BasePclModule::m_app, m_basedRgb, and m_dialog.
Member Data Documentation
m_basedRgb
bool RegionGrowingSegmentation::m_basedRgb protected
Definition at line 36 of file RegionGrowingSegmentation.h.
Referenced by compute(), getParametersFromDialog(), and openInputDialog().
m_curvature
float RegionGrowingSegmentation::m_curvature protected
Definition at line 44 of file RegionGrowingSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_dialog
RegionGrowingSegmentationDlg* RegionGrowingSegmentation::m_dialog protected
Definition at line 34 of file RegionGrowingSegmentation.h.
Referenced by getParametersFromDialog(), openInputDialog(), and ~RegionGrowingSegmentation().
m_k_search
int RegionGrowingSegmentation::m_k_search protected
Definition at line 39 of file RegionGrowingSegmentation.h.
Referenced by compute().
m_max_cluster_size
int RegionGrowingSegmentation::m_max_cluster_size protected
Definition at line 41 of file RegionGrowingSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_min_cluster_size
int RegionGrowingSegmentation::m_min_cluster_size protected
Definition at line 40 of file RegionGrowingSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_min_cluster_size_rgb
int RegionGrowingSegmentation::m_min_cluster_size_rgb protected
Definition at line 47 of file RegionGrowingSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_neighbors_distance
float RegionGrowingSegmentation::m_neighbors_distance protected
Definition at line 48 of file RegionGrowingSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_neighbour_number
unsigned int RegionGrowingSegmentation::m_neighbour_number protected
Definition at line 42 of file RegionGrowingSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_point_color_diff
float RegionGrowingSegmentation::m_point_color_diff protected
Definition at line 49 of file RegionGrowingSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_region_color_diff
float RegionGrowingSegmentation::m_region_color_diff protected
Definition at line 50 of file RegionGrowingSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_smoothness_theta
float RegionGrowingSegmentation::m_smoothness_theta protected
Definition at line 43 of file RegionGrowingSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Segmentations/RegionGrowingSegmentation.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Segmentations/RegionGrowingSegmentation.cpp