ACloudViewer: colmap::mvs::NormalMap Class Reference
colmap::mvs::NormalMap Class Reference
#include <normal_map.h>
Public Member Functions
NormalMap ()
NormalMap (const size_t width, const size_t height)
NormalMap (const Mat< float > &mat)
void Rescale (const float factor)
void Downsize (const size_t max_width, const size_t max_height)
Bitmap ToBitmap () const
Public Member Functions inherited from colmap::mvs::Mat< float >
Mat ()
Mat (const size_t width, const size_t height, const size_t depth)
size_t GetWidth () const
size_t GetHeight () const
size_t GetDepth () const
size_t GetNumBytes () const
float Get (const size_t row, const size_t col, const size_t slice=0) const
void GetSlice (const size_t row, const size_t col, float *values) const
float * GetPtr ()
const float * GetPtr () const
const std::vector< float > & GetData () const
void Set (const size_t row, const size_t col, const float value)
void Set (const size_t row, const size_t col, const size_t slice, const float value)
void Fill (const float value)
void Read (const std::string &path)
void Write (const std::string &path) const
Additional Inherited Members
Protected Attributes inherited from colmap::mvs::Mat< float >
size_t width_
size_t height_
size_t depth_
std::vector< float > data_
Detailed Description
Definition at line 20 of file normal_map.h.
Constructor & Destructor Documentation
NormalMap() [1/3]
colmap::mvs::NormalMap::NormalMap ()
Definition at line 39 of file normal_map.cc.
NormalMap() [2/3]
colmap::mvs::NormalMap::NormalMap (const size_t width, const size_t height)
Definition at line 41 of file normal_map.cc.
NormalMap() [3/3]
colmap::mvs::NormalMap::NormalMap (const Mat< float > & mat) explicit
Definition at line 44 of file normal_map.cc.
References colmap::mvs::Mat< float >::data_, colmap::mvs::Mat< T >::GetData(), and colmap::mvs::Mat< T >::GetDepth().
Member Function Documentation
Downsize()
void colmap::mvs::NormalMap::Downsize (const size_t max_width, const size_t max_height)
Definition at line 88 of file normal_map.cc.
References colmap::mvs::Mat< float >::height_, Rescale(), and colmap::mvs::Mat< float >::width_.
Referenced by BOOST_AUTO_TEST_CASE().
Rescale()
void colmap::mvs::NormalMap::Rescale (const float factor)
Definition at line 50 of file normal_map.cc.
References colmap::mvs::Mat< float >::data_, colmap::DownsampleImage(), colmap::mvs::Mat< float >::Get(), colmap::mvs::Mat< float >::height_, normal, offset, colmap::mvs::Mat< float >::Set(), and colmap::mvs::Mat< float >::width_.
Referenced by BOOST_AUTO_TEST_CASE(), and Downsize().
ToBitmap()
Bitmap colmap::mvs::NormalMap::ToBitmap () const
Definition at line 97 of file normal_map.cc.
References colmap::Bitmap::Allocate(), color, colmap::mvs::Mat< float >::depth_, colmap::mvs::Mat< float >::GetSlice(), colmap::mvs::Mat< float >::height_, normal, colmap::Bitmap::SetPixel(), colmap::mvs::Mat< float >::width_, x, and y.
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/mvs/normal_map.h
/root/ACloudViewer/libs/Reconstruction/src/mvs/normal_map.cc