ACloudViewer: ecvCustomLabelsWidget Class Reference
ecvCustomLabelsWidget Class Reference
ParaView-style Custom Labels Editor Widget.
#include <ecvCustomLabelsWidget.h>
Public Member Functions
ecvCustomLabelsWidget (QWidget *parent=nullptr)
~ecvCustomLabelsWidget () override
QList< QPair< double, QString > > getLabels () const
void setLabels (const QList< QPair< double, QString >> &labels)
void clearLabels ()
Detailed Description
ParaView-style Custom Labels Editor Widget.
Table with "Value" and "Label" columns, plus Add/Remove buttons.
Definition at line 23 of file ecvCustomLabelsWidget.h.
Constructor & Destructor Documentation
ecvCustomLabelsWidget()
ecvCustomLabelsWidget::ecvCustomLabelsWidget (QWidget * parent = nullptr) explicit
Definition at line 16 of file ecvCustomLabelsWidget.cpp.
~ecvCustomLabelsWidget()
ecvCustomLabelsWidget::~ecvCustomLabelsWidget () override default
Member Function Documentation
clearLabels()
void ecvCustomLabelsWidget::clearLabels ()
Definition at line 133 of file ecvCustomLabelsWidget.cpp.
getLabels()
QList< QPair< double, QString > > ecvCustomLabelsWidget::getLabels () const
Definition at line 100 of file ecvCustomLabelsWidget.cpp.
Referenced by ecvAxesGridDialog::getXAxisCustomLabels(), ecvAxesGridDialog::getYAxisCustomLabels(), and ecvAxesGridDialog::getZAxisCustomLabels().
setLabels()
void ecvCustomLabelsWidget::setLabels (const QList< QPair< double, QString >> & labels)
Definition at line 117 of file ecvCustomLabelsWidget.cpp.
Referenced by ecvAxesGridDialog::setXAxisCustomLabels(), ecvAxesGridDialog::setYAxisCustomLabels(), and ecvAxesGridDialog::setZAxisCustomLabels().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/db_tree/ecvCustomLabelsWidget.h
/root/ACloudViewer/app/db_tree/ecvCustomLabelsWidget.cpp