ACloudViewer: ecvSettingManager Class Reference
ecvSettingManager Class Reference
#include <ecvSettingManager.h>
Signals
void modified ()
Public Member Functions
~ecvSettingManager () override
Destructor.
virtual void saveState (const QMainWindow &window, const QString &key)
virtual void saveState (const QDialog &dialog, const QString &key)
virtual void restoreState (const QString &key, QMainWindow &window)
virtual void restoreState (const QString &key, QDialog &dialog)
virtual void alertSettingsModified ()
QString backup (const QString &filename=QString())
virtual void clear ()
virtual void sync ()
virtual Status status () const
virtual bool isAtomicSyncRequired () const
virtual void setAtomicSyncRequired (bool enable)
virtual void beginGroup (const QString &prefix)
virtual void endGroup ()
virtual QString group () const
virtual int beginReadArray (const QString &prefix)
virtual void beginWriteArray (const QString &prefix, int size=-1)
virtual void endArray ()
virtual void setArrayIndex (int i)
virtual QStringList allKeys () const
virtual QStringList childKeys () const
virtual QStringList childGroups () const
virtual bool isWritable () const
virtual void setValue (const QString &key, const QVariant &value)
virtual QVariant value (const QString &key, const QVariant &defaultValue=QVariant()) const
virtual void remove (const QString &key)
virtual bool contains (const QString &key) const
virtual void setFallbacksEnabled (bool b)
virtual bool fallbacksEnabled () const
virtual QString fileName () const
virtual Format format () const
virtual Scope scope () const
virtual QString organizationName () const
virtual QString applicationName () const
Static Public Member Functions
static ecvSettingManager * TheInstance (bool autoInit=true)
Returns the (unique) static instance.
static void ReleaseInstance ()
Releases unique instance.
static void Init (const QString &path)
static void setValue (const QString &section, const QString &key, const QVariant &value)
static void removeNode (const QString &section)
static void removeKey (const QString &section, const QString &key)
static QVariant getValue (const QString &section, const QString &key, const QVariant &defaultValue=QVariant())
Protected Member Functions
virtual void sanityCheckDock (QDockWidget *docke_widget)
Detailed Description
Definition at line 22 of file ecvSettingManager.h.
Constructor & Destructor Documentation
~ecvSettingManager()
ecvSettingManager::~ecvSettingManager () inline override
Destructor.
Definition at line 28 of file ecvSettingManager.h.
Member Function Documentation
alertSettingsModified()
void ecvSettingManager::alertSettingsModified () virtual
Calling this method will cause the modified signal to be emitted.
Definition at line 44 of file ecvSettingManager.cpp.
References modified().
Referenced by ecvCameraParamEditDlg::AddCurrentViewpointToCustomViewpoints(), ecvCameraParamEditDlg::ConfigureCustomViewpoints(), ecvCameraParamEditDlg::DeleteCustomViewpoint(), and ecvCameraParamEditDlg::SetToCurrentViewpoint().
allKeys()
QStringList ecvSettingManager::allKeys () const virtual
Definition at line 336 of file ecvSettingManager.cpp.
References s_manager.
applicationName()
QString ecvSettingManager::applicationName () const virtual
Definition at line 393 of file ecvSettingManager.cpp.
References s_manager.
backup()
QString ecvSettingManager::backup (const QString & filename = QString())
Creates a new backup file for the current settings. If filename is empty, then a backup file name will automatically be picked. On success returns the backup file name, on failure an empty string is returned.
Definition at line 220 of file ecvSettingManager.cpp.
References copy, fileName(), and sync().
beginGroup()
void ecvSettingManager::beginGroup (const QString & prefix) virtual
Definition at line 308 of file ecvSettingManager.cpp.
References s_manager.
Referenced by ecvCameraParamEditDlg::AddCurrentViewpointToCustomViewpoints(), ecvCameraParamEditDlg::ApplyCustomViewpoint(), ecvCameraParamEditDlg::ConfigureCustomViewpoints(), ecvCameraParamEditDlg::CustomViewpointConfigurations(), ecvCameraParamEditDlg::CustomViewpointToolTips(), ecvCameraParamEditDlg::DeleteCustomViewpoint(), restoreState(), saveState(), and ecvCameraParamEditDlg::SetToCurrentViewpoint().
beginReadArray()
int ecvSettingManager::beginReadArray (const QString & prefix) virtual
Definition at line 320 of file ecvSettingManager.cpp.
References s_manager.
beginWriteArray()
void ecvSettingManager::beginWriteArray (const QString & prefix, int size = -1) virtual
Definition at line 324 of file ecvSettingManager.cpp.
References s_manager, and size.
childGroups()
QStringList ecvSettingManager::childGroups () const virtual
Definition at line 344 of file ecvSettingManager.cpp.
References s_manager.
childKeys()
QStringList ecvSettingManager::childKeys () const virtual
Definition at line 340 of file ecvSettingManager.cpp.
References s_manager.
clear()
void ecvSettingManager::clear () virtual
Definition at line 292 of file ecvSettingManager.cpp.
References s_manager.
contains()
bool ecvSettingManager::contains (const QString & key) const virtual
Definition at line 365 of file ecvSettingManager.cpp.
References s_manager.
Referenced by restoreState().
endArray()
void ecvSettingManager::endArray () virtual
Definition at line 328 of file ecvSettingManager.cpp.
References s_manager.
endGroup()
void ecvSettingManager::endGroup () virtual
Definition at line 312 of file ecvSettingManager.cpp.
References s_manager.
Referenced by ecvCameraParamEditDlg::AddCurrentViewpointToCustomViewpoints(), ecvCameraParamEditDlg::ApplyCustomViewpoint(), ecvCameraParamEditDlg::ConfigureCustomViewpoints(), ecvCameraParamEditDlg::CustomViewpointConfigurations(), ecvCameraParamEditDlg::CustomViewpointToolTips(), ecvCameraParamEditDlg::DeleteCustomViewpoint(), restoreState(), saveState(), and ecvCameraParamEditDlg::SetToCurrentViewpoint().
fallbacksEnabled()
bool ecvSettingManager::fallbacksEnabled () const virtual
Definition at line 373 of file ecvSettingManager.cpp.
References s_manager.
fileName()
QString ecvSettingManager::fileName () const virtual
Definition at line 377 of file ecvSettingManager.cpp.
References s_manager.
Referenced by backup(), and Init().
format()
QSettings::Format ecvSettingManager::format () const virtual
Definition at line 381 of file ecvSettingManager.cpp.
References s_manager.
getValue()
QVariant ecvSettingManager::getValue (const QString & section, const QString & key, const QVariant & defaultValue = QVariant()) static
Definition at line 283 of file ecvSettingManager.cpp.
References result, and s_manager.
Referenced by ecvRecentFiles::addFilePath(), ecvOptions::fromPersistentSettings(), ecvAnnotationsTool::importClassesFromFile(), ecvConsole::Init(), InitEnvironment(), and main().
group()
QString ecvSettingManager::group () const virtual
Definition at line 316 of file ecvSettingManager.cpp.
References s_manager.
Init()
void ecvSettingManager::Init (const QString & path) static
Definition at line 228 of file ecvSettingManager.cpp.
References fileName(), and s_manager.
Referenced by InitEnvironment().
isAtomicSyncRequired()
bool ecvSettingManager::isAtomicSyncRequired () const virtual
Definition at line 300 of file ecvSettingManager.cpp.
References s_manager.
isWritable()
bool ecvSettingManager::isWritable () const virtual
Definition at line 348 of file ecvSettingManager.cpp.
References s_manager.
modified
void ecvSettingManager::modified () signal
Referenced by alertSettingsModified().
organizationName()
QString ecvSettingManager::organizationName () const virtual
Definition at line 389 of file ecvSettingManager.cpp.
References s_manager.
ReleaseInstance()
void ecvSettingManager::ReleaseInstance () static
Releases unique instance.
Definition at line 42 of file ecvSettingManager.cpp.
References s_manager.
Referenced by main().
remove()
void ecvSettingManager::remove (const QString & key) virtual
Definition at line 361 of file ecvSettingManager.cpp.
References s_manager.
Referenced by ecvCameraParamEditDlg::ConfigureCustomViewpoints(), and ecvCameraParamEditDlg::DeleteCustomViewpoint().
removeKey()
void ecvSettingManager::removeKey (const QString & section, const QString & key) static
Definition at line 277 of file ecvSettingManager.cpp.
References s_manager.
Referenced by ecvRecentFiles::ecvRecentFiles().
removeNode()
void ecvSettingManager::removeNode (const QString & section) static
Definition at line 273 of file ecvSettingManager.cpp.
References s_manager.
restoreState() [1/2]
void ecvSettingManager::restoreState (const QString & key, QDialog & dialog) virtual
Definition at line 58 of file ecvSettingManager.cpp.
References beginGroup(), contains(), endGroup(), and value().
restoreState() [2/2]
void ecvSettingManager::restoreState (const QString & key, QMainWindow & window) virtual
Definition at line 84 of file ecvSettingManager.cpp.
References beginGroup(), contains(), endGroup(), sanityCheckDock(), and value().
sanityCheckDock()
void ecvSettingManager::sanityCheckDock (QDockWidget * docke_widget) protected virtual
ensure that when window state is being loaded, if dock windows are beyond the viewport, we correct them.
Definition at line 106 of file ecvSettingManager.cpp.
Referenced by restoreState().
saveState() [1/2]
void ecvSettingManager::saveState (const QDialog & dialog, const QString & key) virtual
Definition at line 47 of file ecvSettingManager.cpp.
References beginGroup(), endGroup(), and setValue().
saveState() [2/2]
void ecvSettingManager::saveState (const QMainWindow & window, const QString & key) virtual
Definition at line 75 of file ecvSettingManager.cpp.
References beginGroup(), endGroup(), and setValue().
scope()
QSettings::Scope ecvSettingManager::scope () const virtual
Definition at line 385 of file ecvSettingManager.cpp.
References s_manager.
setArrayIndex()
void ecvSettingManager::setArrayIndex (int i) virtual
Definition at line 332 of file ecvSettingManager.cpp.
References s_manager.
setAtomicSyncRequired()
void ecvSettingManager::setAtomicSyncRequired (bool enable) virtual
Definition at line 304 of file ecvSettingManager.cpp.
References s_manager.
setFallbacksEnabled()
void ecvSettingManager::setFallbacksEnabled (bool b) virtual
Definition at line 369 of file ecvSettingManager.cpp.
References s_manager.
setValue() [1/2]
void ecvSettingManager::setValue (const QString & key, const QVariant & value) virtual
Definition at line 352 of file ecvSettingManager.cpp.
References s_manager, and value().
setValue() [2/2]
void ecvSettingManager::setValue (const QString & section, const QString & key, const QVariant & value) static
Definition at line 264 of file ecvSettingManager.cpp.
References s_manager, and value().
Referenced by ecvCameraParamEditDlg::AddCurrentViewpointToCustomViewpoints(), ecvRecentFiles::addFilePath(), ecvCameraParamEditDlg::ConfigureCustomViewpoints(), ecvCameraParamEditDlg::DeleteCustomViewpoint(), ecvConsole::EnableQtMessages(), ecvAnnotationsTool::importClassesFromFile(), saveState(), ecvApplicationBase::setAppStyle(), ecvCameraParamEditDlg::SetToCurrentViewpoint(), and ecvOptions::toPersistentSettings().
status()
QSettings::Status ecvSettingManager::status () const virtual
Definition at line 296 of file ecvSettingManager.cpp.
References s_manager.
sync()
void ecvSettingManager::sync () virtual
Definition at line 294 of file ecvSettingManager.cpp.
References s_manager.
Referenced by backup().
TheInstance()
ecvSettingManager * ecvSettingManager::TheInstance (bool autoInit = true) static
Returns the (unique) static instance.
Parameters
autoInit automatically initialize the console instance (with no widget!) if not done already
Definition at line 34 of file ecvSettingManager.cpp.
References s_manager.
Referenced by ecvCameraParamEditDlg::AddCurrentViewpointToCustomViewpoints(), ecvCameraParamEditDlg::ApplyCustomViewpoint(), ecvCameraParamEditDlg::ConfigureCustomViewpoints(), ecvCameraParamEditDlg::CustomViewpointConfigurations(), ecvCameraParamEditDlg::CustomViewpointToolTips(), ecvCameraParamEditDlg::DeleteCustomViewpoint(), ecvCameraParamEditDlg::ecvCameraParamEditDlg(), and ecvCameraParamEditDlg::SetToCurrentViewpoint().
value()
QVariant ecvSettingManager::value (const QString & key, const QVariant & defaultValue = QVariant()) const virtual
Definition at line 356 of file ecvSettingManager.cpp.
References s_manager.
Referenced by ecvCameraParamEditDlg::ApplyCustomViewpoint(), ecvCameraParamEditDlg::DeleteCustomViewpoint(), restoreState(), and setValue().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVAppCommon/include/ecvSettingManager.h
/root/ACloudViewer/libs/CVAppCommon/src/ecvSettingManager.cpp