ACloudViewer: QCPAbstractItem Class Reference
QCPAbstractItem Class Reference abstract
The abstract base class for all items in a plot.
#include <qcustomplot.h>
Signals
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
void layerChanged (QCPLayer *newLayer)
Public Member Functions
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const =0
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const =0
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
virtual ~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Protected Member Functions
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)=0
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual QPointF anchorPixelPosition (int anchorId) const
double rectDistance (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)=0
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual QPointF anchorPixelPoint (int anchorId) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual void mousePressEvent (QMouseEvent *event, const QVariant &details)
virtual void mouseMoveEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseReleaseEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseDoubleClickEvent (QMouseEvent *event, const QVariant &details)
virtual void wheelEvent (QWheelEvent *event)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Detailed Description
The abstract base class for all items in a plot.
In QCustomPlot, items are supplemental graphical elements that are neither plottables (QCPAbstractPlottable) nor axes (QCPAxis). While plottables are always tied to two axes and thus plot coordinates, items can also be placed in absolute coordinates independent of any axes. Each specific item has at least one QCPItemPosition member which controls the positioning. Some items are defined by more than one coordinate and thus have two or more QCPItemPosition members (For example, QCPItemRect has topLeft and bottomRight).
This abstract base class defines a very basic interface like visibility and clipping. Since this class is abstract, it can't be instantiated. Use one of the subclasses or create a subclass yourself to create new items.
The built-in items are:
QCPItemLine A line defined by a start and an end point. May have different ending styles on each side (e.g. arrows).
QCPItemStraightLine A straight line defined by a start and a direction point. Unlike QCPItemLine, the straight line is infinitely long and has no endings.
QCPItemCurve A curve defined by start, end and two intermediate control points. May have different ending styles on each side (e.g. arrows).
QCPItemRect A rectangle
QCPItemEllipse An ellipse
QCPItemPixmap An arbitrary pixmap
QCPItemText A text label
QCPItemBracket A bracket which may be used to reference/highlight certain parts in the plot.
QCPItemTracer An item that can be attached to a QCPGraph and sticks to its data points, given a key coordinate.
Clipping
Items are by default clipped to the main axis rect (they are only visible inside the axis rect). To make an item visible outside that axis rect, disable clipping via setClipToAxisRect(false).
On the other hand if you want the item to be clipped to a different axis rect, specify it via setClipAxisRect. This clipAxisRect property of an item is only used for clipping behaviour, and in principle is independent of the coordinate axes the item might be tied to via its position members (QCPItemPosition::setAxes). However, it is common that the axis rect for clipping also contains the axes used for the item positions.
Using items
First you instantiate the item you want to use and add it to the plot:
by default, the positions of the item are bound to the x- and y-Axis of the plot. So we can just set the plot coordinates where the line should start/end:
If we don't want the line to be positioned in plot coordinates but a different coordinate system, e.g. absolute pixel positions on the QCustomPlot surface, we need to change the position type like this:
can set the coordinates, this time in pixels:
the line visible on the entire QCustomPlot, by disabling clipping to the axis rect:
qcpitemline-creation-5
For more advanced plots, it is even possible to set different types and parent anchors per X/Y coordinate of an item position, using for example QCPItemPosition::setTypeX or QCPItemPosition::setParentAnchorX. For details, see the documentation of QCPItemPosition.
Creating own items
To create an own item, you implement a subclass of QCPAbstractItem. These are the pure virtual functions, you must implement:
selectTest
draw
See the documentation of those functions for what they need to do.
Allowing the item to be positioned
As mentioned, item positions are represented by QCPItemPosition members. Let's assume the new item shall have only one point as its position (as opposed to two like a rect or multiple like a polygon). You then add a public member of type QCPItemPosition like so:
QCPItemPosition * const myPosition;
the const makes sure the pointer itself can't be modified from the user of your new item (the QCPItemPosition instance it points to, can be modified, of course). The initialization of this pointer is made easy with the createPosition function. Just assign the return value of this function to each QCPItemPosition in the constructor of your item. createPosition takes a string which is the name of the position, typically this is identical to the variable name. For example, the constructor of QCPItemExample could look like this:
QCPItemExample::QCPItemExample(QCustomPlot *parentPlot) :
  QCPAbstractItem(parentPlot),
  myPosition(createPosition("myPosition"))
{
  // other constructor code
}
The draw function
To give your item a visual representation, reimplement the draw function and use the passed QCPPainter to draw the item. You can retrieve the item position in pixel coordinates from the position member(s) via QCPItemPosition::pixelPosition.
To optimize performance you should calculate a bounding rect first (don't forget to take the pen width into account), check whether it intersects the clipRect, and only draw the item at all if this is the case.
The selectTest function
Your implementation of the selectTest function may use the helpers QCPVector2D::distanceSquaredToLine and rectDistance. With these, the implementation of the selection test becomes significantly simpler for most items. See the documentation of selectTest for what the function parameters mean and what the function should return.
Providing anchors
Providing anchors (QCPItemAnchor) starts off like adding a position. First you create a public member, e.g.
QCPItemAnchor * const bottom;
and create it in the constructor with the createAnchor function, assigning it a name and an anchor id (an integer enumerating all anchors on the item, you may create an own enum for this). Since anchors can be placed anywhere, relative to the item's position(s), your item needs to provide the position of every anchor with the reimplementation of the anchorPixelPosition(int anchorId) function.
In essence the QCPItemAnchor is merely an intermediary that itself asks your item for the pixel position when anything attached to the anchor needs to know the coordinates.
In QCustomPlot, items are supplemental graphical elements that are neither plottables (QCPAbstractPlottable) nor axes (QCPAxis). While plottables are always tied to two axes and thus plot coordinates, items can also be placed in absolute coordinates independent of any axes. Each specific item has at least one QCPItemPosition member which controls the positioning. Some items are defined by more than one coordinate and thus have two or more QCPItemPosition members (For example, QCPItemRect has topLeft and bottomRight).
This abstract base class defines a very basic interface like visibility and clipping. Since this class is abstract, it can't be instantiated. Use one of the subclasses or create a subclass yourself to create new items.
The built-in items are:
QCPItemLine A line defined by a start and an end point. May have different ending styles on each side (e.g. arrows).
QCPItemStraightLine A straight line defined by a start and a direction point. Unlike QCPItemLine, the straight line is infinitely long and has no endings.
QCPItemCurve A curve defined by start, end and two intermediate control points. May have different ending styles on each side (e.g. arrows).
QCPItemRect A rectangle
QCPItemEllipse An ellipse
QCPItemPixmap An arbitrary pixmap
QCPItemText A text label
QCPItemBracket A bracket which may be used to reference/highlight certain parts in the plot.
QCPItemTracer An item that can be attached to a QCPGraph and sticks to its data points, given a key coordinate.
Clipping
Items are by default clipped to the main axis rect (they are only visible inside the axis rect). To make an item visible outside that axis rect, disable clipping via setClipToAxisRect(false).
On the other hand if you want the item to be clipped to a different axis rect, specify it via setClipAxisRect. This clipAxisRect property of an item is only used for clipping behaviour, and in principle is independent of the coordinate axes the item might be tied to via its position members (QCPItemPosition::setAxes). However, it is common that the axis rect for clipping also contains the axes used for the item positions.
Using items
First you instantiate the item you want to use and add it to the plot:
by default, the positions of the item are bound to the x- and y-Axis of the plot. So we can just set the plot coordinates where the line should start/end:
If we don't want the line to be positioned in plot coordinates but a different coordinate system, e.g. absolute pixel positions on the QCustomPlot surface, we need to change the position type like this:
can set the coordinates, this time in pixels:
the line visible on the entire QCustomPlot, by disabling clipping to the axis rect:
qcpitemline-creation-5
For more advanced plots, it is even possible to set different types and parent anchors per X/Y coordinate of an item position, using for example QCPItemPosition::setTypeX or QCPItemPosition::setParentAnchorX. For details, see the documentation of QCPItemPosition.
Creating own items
To create an own item, you implement a subclass of QCPAbstractItem. These are the pure virtual functions, you must implement:
selectTest
draw
See the documentation of those functions for what they need to do.
Allowing the item to be positioned
As mentioned, item positions are represented by QCPItemPosition members. Let's assume the new item shall have only one point as its position (as opposed to two like a rect or multiple like a polygon). You then add a public member of type QCPItemPosition like so:
QCPItemPosition * const myPosition;
the const makes sure the pointer itself can't be modified from the user of your new item (the QCPItemPosition instance it points to, can be modified, of course). The initialization of this pointer is made easy with the createPosition function. Just assign the return value of this function to each QCPItemPosition in the constructor of your item. createPosition takes a string which is the name of the position, typically this is identical to the variable name. For example, the constructor of QCPItemExample could look like this:
QCPItemExample::QCPItemExample(QCustomPlot *parentPlot) :
  QCPAbstractItem(parentPlot),
  myPosition(createPosition("myPosition"))
{
  // other constructor code
}
The draw function
To give your item a visual representation, reimplement the draw function and use the passed QCPPainter to draw the item. You can retrieve the item position in pixel coordinates from the position member(s) via QCPItemPosition::pixelPoint.
To optimize performance you should calculate a bounding rect first (don't forget to take the pen width into account), check whether it intersects the clipRect, and only draw the item at all if this is the case.
The selectTest function
Your implementation of the selectTest function may use the helpers distSqrToLine and rectSelectTest. With these, the implementation of the selection test becomes significantly simpler for most items. See the documentation of selectTest for what the function parameters mean and what the function should return.
Providing anchors
Providing anchors (QCPItemAnchor) starts off like adding a position. First you create a public member, e.g.
QCPItemAnchor * const bottom;
and create it in the constructor with the createAnchor function, assigning it a name and an anchor id (an integer enumerating all anchors on the item, you may create an own enum for this). Since anchors can be placed anywhere, relative to the item's position(s), your item needs to provide the position of every anchor with the reimplementation of the anchorPixelPoint(int anchorId) function.
In essence the QCPItemAnchor is merely an intermediary that itself asks your item for the pixel position when anything attached to the anchor needs to know the coordinates.
Definition at line 4081 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPAbstractItem() [1/2]
QCPAbstractItem::QCPAbstractItem (QCustomPlot * parentPlot) explicit
Base class constructor which initializes base class members.
Definition at line 12657 of file qcustomplot.cpp.
References QCustomPlot::axisRects(), QCPLayerable::parentPlot(), QCustomPlot::registerItem(), setClipAxisRect(), and setClipToAxisRect().
~QCPAbstractItem() [1/2]
QCPAbstractItem::~QCPAbstractItem () virtual
Definition at line 12671 of file qcustomplot.cpp.
References mAnchors.
QCPAbstractItem() [2/2]
QCPAbstractItem::QCPAbstractItem (QCustomPlot * parentPlot)
~QCPAbstractItem() [2/2]
virtual QCPAbstractItem::~QCPAbstractItem () virtual
Member Function Documentation
anchor() [1/2]
QCPItemAnchor * QCPAbstractItem::anchor (const QString & name) const
Returns the QCPItemAnchor with the specified name. If this item doesn't have an anchor by that name, returns 0.
This function provides an alternative way to access item anchors. Normally, you access anchors direcly by their member pointers (which typically have the same variable name as name).
See also
anchors, position
Definition at line 12775 of file qcustomplot.cpp.
References mAnchors, and name.
anchor() [2/2]
QCPItemAnchor* QCPAbstractItem::anchor (const QString & name) const
anchorPixelPoint()
QPointF QCPAbstractItem::anchorPixelPoint (int anchorId) const protected virtual
Reimplemented in QCPItemBracket, QCPItemPixmap, QCPItemEllipse, QCPItemText, and QCPItemRect.
Definition at line 8869 of file qcustomplot.cpp.
Referenced by QCPItemAnchor::pixelPoint().
anchorPixelPosition()
QPointF QCPAbstractItem::anchorPixelPosition (int anchorId) const protected virtual
Reimplemented in QCPItemBracket, QCPItemPixmap, QCPItemEllipse, QCPItemText, and QCPItemRect.
Definition at line 12888 of file qcustomplot.cpp.
Referenced by QCPItemAnchor::pixelPosition().
anchors() [1/2]
QList< QCPItemAnchor * > QCPAbstractItem::anchors () const inline
Returns all anchors of the item in a list. Note that since a position (QCPItemPosition) is always also an anchor, the list will also contain the positions of this item.
See also
positions, anchor
Definition at line 4115 of file qcustomplot.h.
anchors() [2/2]
QList<QCPItemAnchor *> QCPAbstractItem::anchors () const inline
Definition at line 1971 of file qcustomplot.h.
applyDefaultAntialiasingHint() [1/2]
void QCPAbstractItem::applyDefaultAntialiasingHint (QCPPainter * painter) const protected virtual
Implements QCPLayerable.
Definition at line 12831 of file qcustomplot.cpp.
References QCP::aeItems, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
applyDefaultAntialiasingHint() [2/2]
virtual void QCPAbstractItem::applyDefaultAntialiasingHint (QCPPainter * painter) const protected virtual
Implements QCPLayerable.
clipAxisRect() [1/2]
QCPAxisRect * QCPAbstractItem::clipAxisRect () const
Definition at line 12679 of file qcustomplot.cpp.
References mClipAxisRect.
clipAxisRect() [2/2]
QCPAxisRect* QCPAbstractItem::clipAxisRect () const
clipRect() [1/2]
QRect QCPAbstractItem::clipRect () const protected virtual
Reimplemented from QCPLayerable.
Definition at line 12810 of file qcustomplot.cpp.
References mClipAxisRect, mClipToAxisRect, QCPLayerable::mParentPlot, and QCustomPlot::viewport().
Referenced by QCPItemStraightLine::draw(), QCPItemLine::draw(), QCPItemCurve::draw(), QCPItemRect::draw(), QCPItemText::draw(), QCPItemEllipse::draw(), QCPItemPixmap::draw(), QCPItemTracer::draw(), QCPItemBracket::draw(), QCustomPlot::itemAt(), and QCPItemTracer::selectTest().
clipRect() [2/2]
virtual QRect QCPAbstractItem::clipRect () const protected virtual
Reimplemented from QCPLayerable.
clipToAxisRect() [1/2]
bool QCPAbstractItem::clipToAxisRect () const inline
Definition at line 4097 of file qcustomplot.h.
Referenced by QCustomPlot::itemAt().
clipToAxisRect() [2/2]
bool QCPAbstractItem::clipToAxisRect () const inline
Definition at line 1953 of file qcustomplot.h.
createAnchor() [1/2]
QCPItemAnchor * QCPAbstractItem::createAnchor (const QString & name, int anchorId) protected
Definition at line 12949 of file qcustomplot.cpp.
References hasAnchor(), mAnchors, QCPLayerable::mParentPlot, name, and QCPItemAnchor.
createAnchor() [2/2]
QCPItemAnchor* QCPAbstractItem::createAnchor (const QString & name, int anchorId) protected
createPosition() [1/2]
QCPItemPosition * QCPAbstractItem::createPosition (const QString & name) protected
Definition at line 12912 of file qcustomplot.cpp.
References QCustomPlot::axisRect(), hasAnchor(), mAnchors, QCPLayerable::mParentPlot, mPositions, name, QCPItemPosition::ptPlotCoords, QCPItemPosition::setAxes(), QCPItemPosition::setAxisRect(), QCPItemPosition::setCoords(), QCPItemPosition::setType(), QCustomPlot::xAxis, and QCustomPlot::yAxis.
createPosition() [2/2]
QCPItemPosition* QCPAbstractItem::createPosition (const QString & name) protected
deselectEvent() [1/2]
void QCPAbstractItem::deselectEvent (bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 12976 of file qcustomplot.cpp.
References mSelectable, mSelected, and setSelected().
deselectEvent() [2/2]
virtual void QCPAbstractItem::deselectEvent (bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
distSqrToLine()
double QCPAbstractItem::distSqrToLine (const QPointF & start, const QPointF & end, const QPointF & point) const protected
Definition at line 8794 of file qcustomplot.cpp.
References a.
Referenced by rectSelectTest().
draw() [1/2]
void QCPAbstractItem::draw (QCPPainter * painter) protected pure virtual
Implements QCPLayerable.
Implemented in QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, QCPItemStraightLine, QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, and QCPItemStraightLine.
draw() [2/2]
virtual void QCPAbstractItem::draw (QCPPainter * painter) protected pure virtual
Implements QCPLayerable.
Implemented in QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, QCPItemStraightLine, QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, and QCPItemStraightLine.
hasAnchor() [1/2]
bool QCPAbstractItem::hasAnchor (const QString & name) const
Returns whether this item has an anchor with the specified name.
Note that you can check for positions with this function, too. This is because every position is also an anchor (QCPItemPosition inherits from QCPItemAnchor).
See also
anchor, position
Definition at line 12792 of file qcustomplot.cpp.
References mAnchors, and name.
Referenced by createAnchor(), and createPosition().
hasAnchor() [2/2]
bool QCPAbstractItem::hasAnchor (const QString & name) const
position() [1/2]
QCPItemPosition * QCPAbstractItem::position (const QString & name) const
Returns the QCPItemPosition with the specified name. If this item doesn't have a position by that name, returns 0.
This function provides an alternative way to access item positions. Normally, you access positions direcly by their member pointers (which typically have the same variable name as name).
See also
positions, anchor
Definition at line 12757 of file qcustomplot.cpp.
References mPositions, and name.
position() [2/2]
QCPItemPosition* QCPAbstractItem::position (const QString & name) const
positions() [1/2]
QList< QCPItemPosition * > QCPAbstractItem::positions () const inline
Returns all positions of the item in a list.
See also
anchors, position
Definition at line 4114 of file qcustomplot.h.
positions() [2/2]
QList<QCPItemPosition *> QCPAbstractItem::positions () const inline
Definition at line 1970 of file qcustomplot.h.
rectDistance()
double QCPAbstractItem::rectDistance (const QRectF & rect, const QPointF & pos, bool filledRect) const protected
Definition at line 12849 of file qcustomplot.cpp.
References QCPVector2D::distanceSquaredToLine(), QCPLayerable::mParentPlot, result, and QCustomPlot::selectionTolerance().
Referenced by QCPItemRect::selectTest(), QCPItemText::selectTest(), QCPItemPixmap::selectTest(), and QCPItemTracer::selectTest().
rectSelectTest()
double QCPAbstractItem::rectSelectTest (const QRectF & rect, const QPointF & pos, bool filledRect) const protected
Definition at line 8831 of file qcustomplot.cpp.
References distSqrToLine(), QCPLayerable::mParentPlot, result, and QCustomPlot::selectionTolerance().
selectable() [1/2]
bool QCPAbstractItem::selectable () const inline
Definition at line 4099 of file qcustomplot.h.
Referenced by QCustomPlot::itemAt(), and setSelectable().
selectable() [2/2]
bool QCPAbstractItem::selectable () const inline
Definition at line 1955 of file qcustomplot.h.
selectableChanged [1/2]
void QCPAbstractItem::selectableChanged (bool selectable) signal
Referenced by setSelectable().
selectableChanged [2/2]
void QCPAbstractItem::selectableChanged (bool selectable) signal
selected() [1/2]
bool QCPAbstractItem::selected () const inline
Definition at line 4100 of file qcustomplot.h.
Referenced by QCustomPlot::selectedItems(), and setSelected().
selected() [2/2]
bool QCPAbstractItem::selected () const inline
Definition at line 1956 of file qcustomplot.h.
selectEvent() [1/2]
void QCPAbstractItem::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 12961 of file qcustomplot.cpp.
References event, mSelectable, mSelected, and setSelected().
selectEvent() [2/2]
virtual void QCPAbstractItem::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
selectionCategory() [1/2]
QCP::Interaction QCPAbstractItem::selectionCategory () const protected virtual
Reimplemented from QCPLayerable.
Definition at line 12986 of file qcustomplot.cpp.
References QCP::iSelectItems.
selectionCategory() [2/2]
virtual QCP::Interaction QCPAbstractItem::selectionCategory () const protected virtual
Reimplemented from QCPLayerable.
selectionChanged [1/2]
void QCPAbstractItem::selectionChanged (bool selected) signal
This signal is emitted when the selection state of this item has changed, either by user interaction or by a direct call to setSelected.
Referenced by setSelected().
selectionChanged [2/2]
void QCPAbstractItem::selectionChanged (bool selected) signal
selectTest() [1/2]
virtual double QCPAbstractItem::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const pure virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Reimplemented from QCPLayerable.
Implemented in QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, QCPItemStraightLine, QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, and QCPItemStraightLine.
Referenced by QCustomPlot::itemAt().
selectTest() [2/2]
virtual double QCPAbstractItem::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const pure virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Reimplemented from QCPLayerable.
Implemented in QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, QCPItemStraightLine, QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, and QCPItemStraightLine.
setClipAxisRect() [1/2]
void QCPAbstractItem::setClipAxisRect (QCPAxisRect * rect)
Sets the clip axis rect. It defines the rect that will be used to clip the item when setClipToAxisRect is set to true.
See also
setClipToAxisRect
Definition at line 12701 of file qcustomplot.cpp.
References mClipAxisRect, mClipToAxisRect, and QCPLayerable::setParentLayerable().
Referenced by QCPAbstractItem().
setClipAxisRect() [2/2]
void QCPAbstractItem::setClipAxisRect (QCPAxisRect * rect)
setClipToAxisRect() [1/2]
void QCPAbstractItem::setClipToAxisRect (bool clip)
Sets whether the item shall be clipped to an axis rect or whether it shall be visible on the entire QCustomPlot. The axis rect can be set with setClipAxisRect.
See also
setClipAxisRect
Definition at line 12690 of file qcustomplot.cpp.
References mClipAxisRect, mClipToAxisRect, and QCPLayerable::setParentLayerable().
Referenced by QCPAbstractItem().
setClipToAxisRect() [2/2]
void QCPAbstractItem::setClipToAxisRect (bool clip)
setSelectable() [1/2]
void QCPAbstractItem::setSelectable (bool selectable)
Sets whether the user can (de-)select this item by clicking on the QCustomPlot surface. (When QCustomPlot::setInteractions contains QCustomPlot::iSelectItems.)
However, even when selectable was set to false, it is possible to set the selection manually, by calling setSelected.
See also
QCustomPlot::setInteractions, setSelected
Definition at line 12716 of file qcustomplot.cpp.
References mSelectable, selectable(), and selectableChanged().
setSelectable() [2/2]
Q_SLOT void QCPAbstractItem::setSelectable (bool selectable)
setSelected() [1/2]
void QCPAbstractItem::setSelected (bool selected)
Sets whether this item is selected or not. When selected, it might use a different visual appearance (e.g. pen and brush), this depends on the specific item though.
The entire selection mechanism for items is handled automatically when QCustomPlot::setInteractions contains QCustomPlot::iSelectItems. You only need to call this function when you wish to change the selection state manually.
This function can change the selection state even when setSelectable was set to false.
emits the selectionChanged signal when selected is different from the previous selection state.
See also
setSelectable, selectTest
Definition at line 12740 of file qcustomplot.cpp.
References mSelected, selected(), and selectionChanged().
Referenced by deselectEvent(), and selectEvent().
setSelected() [2/2]
Q_SLOT void QCPAbstractItem::setSelected (bool selected)
Member Data Documentation
mAnchors
QList< QCPItemAnchor * > QCPAbstractItem::mAnchors protected
Definition at line 4129 of file qcustomplot.h.
Referenced by anchor(), createAnchor(), createPosition(), hasAnchor(), and ~QCPAbstractItem().
mClipAxisRect
QPointer< QCPAxisRect > QCPAbstractItem::mClipAxisRect protected
Definition at line 4127 of file qcustomplot.h.
Referenced by clipAxisRect(), clipRect(), setClipAxisRect(), and setClipToAxisRect().
mClipToAxisRect
bool QCPAbstractItem::mClipToAxisRect protected
Definition at line 4126 of file qcustomplot.h.
Referenced by clipRect(), setClipAxisRect(), and setClipToAxisRect().
mPositions
QList< QCPItemPosition * > QCPAbstractItem::mPositions protected
Definition at line 4128 of file qcustomplot.h.
Referenced by createPosition(), and position().
mSelectable
bool QCPAbstractItem::mSelectable protected
Definition at line 4130 of file qcustomplot.h.
Referenced by deselectEvent(), selectEvent(), QCPItemStraightLine::selectTest(), QCPItemLine::selectTest(), QCPItemCurve::selectTest(), QCPItemRect::selectTest(), QCPItemText::selectTest(), QCPItemEllipse::selectTest(), QCPItemPixmap::selectTest(), QCPItemTracer::selectTest(), QCPItemBracket::selectTest(), and setSelectable().
mSelected
bool QCPAbstractItem::mSelected protected
Definition at line 4130 of file qcustomplot.h.
Referenced by deselectEvent(), QCPItemRect::mainBrush(), QCPItemText::mainBrush(), QCPItemEllipse::mainBrush(), QCPItemTracer::mainBrush(), QCPItemText::mainColor(), QCPItemText::mainFont(), QCPItemStraightLine::mainPen(), QCPItemLine::mainPen(), QCPItemCurve::mainPen(), QCPItemRect::mainPen(), QCPItemText::mainPen(), QCPItemEllipse::mainPen(), QCPItemPixmap::mainPen(), QCPItemTracer::mainPen(), QCPItemBracket::mainPen(), selectEvent(), and setSelected().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp