ACloudViewer: ecvCameraParamEditDlg Class Reference
ecvCameraParamEditDlg Class Reference
Dialog to interactively edit the camera pose parameters.
#include <ecvCameraParamEditDlg.h>
Public Slots
void linkWith (QMdiSubWindow *qWin)
Links this dialog with a given sub-window.
void updatePivotPoint (const CCVector3d &P)
Updates dialog values with pivot point.
void updateViewMode ()
Updates current view mode.
void pivotChanged ()
void rotationFactorChanged (double)
void zfactorSliderMoved (int val)
void pickPointAsPivot (bool)
void processPickedItem (ccHObject *, unsigned, int, int, const CCVector3 &)
Public Member Functions
ecvCameraParamEditDlg (QWidget *parent, ccPickingHub *pickingHub)
Default constructor.
~ecvCameraParamEditDlg () override
Destructor.
bool start () override
Starts process.
bool linkWith (QWidget *win) override
Links the overlay dialog with a MDI window.
void onItemPicked (const PickedItem &pi) override
Method called whenever an item is picked.
bool setCameraTool (ecvGenericCameraTool *tool)
void SetCameraGroupsEnabled (bool enabled)
Public Member Functions inherited from ccOverlayDialog
ccOverlayDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::FramelessWindowHint|Qt::Tool)
Default constructor.
~ccOverlayDialog () override
Destructor.
virtual void stop (bool accepted)
Stops process/dialog.
void reject () override
void addOverridenShortcut (Qt::Key key)
bool started () const
Returns whether the tool is currently started or not.
Public Member Functions inherited from ccPickingListener
virtual ~ccPickingListener ()=default
Static Public Member Functions
static bool ConfigureCustomViewpoints (QWidget *parentWidget)
static bool AddCurrentViewpointToCustomViewpoints ()
static bool ApplyCustomViewpoint (int CustomViewpointIndex)
static bool DeleteCustomViewpoint (int CustomViewpointIndex)
static bool SetToCurrentViewpoint (int CustomViewpointIndex)
static QStringList CustomViewpointToolTips ()
static QStringList CustomViewpointConfigurations ()
Protected Types
using PushedMatricesMapType = std::map< QWidget *, ccGLMatrixd >
Type of the pushed matrices map structure.
using PushedMatricesMapElement = std::pair< QWidget *, ccGLMatrixd >
Type of an element of the pushed matrices map structure.
Protected Slots
void updateCamera ()
void cameraChanged ()
Protected Slots inherited from ccOverlayDialog
virtual void onLinkedWindowDeletion (QObject *object=nullptr)
Slot called when the linked window is deleted (calls 'onClose')
Protected Member Functions
void initWith (QWidget *win)
Inits dialog values with specified window.
void updateUi ()
Protected Member Functions inherited from ccOverlayDialog
bool eventFilter (QObject *obj, QEvent *e) override
Protected Attributes
PushedMatricesMapType pushedMatrices
Pushed camera matrices (per window)
ccPickingHub * m_pickingHub
Picking hub.
Protected Attributes inherited from ccOverlayDialog
QWidget * m_associatedWin
Associated (MDI) window.
bool m_processing
Running/processing state.
QList< int > m_overriddenKeys
Overridden keys.
Additional Inherited Members
Signals inherited from ccOverlayDialog
void processFinished (bool accepted)
Signal emitted when process is finished.
void shortcutTriggered (int key)
Signal emitted when an overridden key shortcut is pressed.
void shown ()
Signal emitted when a 'show' event is detected.
Detailed Description
Dialog to interactively edit the camera pose parameters.
Definition at line 29 of file ecvCameraParamEditDlg.h.
Member Typedef Documentation
PushedMatricesMapElement
using ecvCameraParamEditDlg::PushedMatricesMapElement = std::pair<QWidget*, ccGLMatrixd> protected
Type of an element of the pushed matrices map structure.
Definition at line 151 of file ecvCameraParamEditDlg.h.
PushedMatricesMapType
using ecvCameraParamEditDlg::PushedMatricesMapType = std::map<QWidget*, ccGLMatrixd> protected
Type of the pushed matrices map structure.
Definition at line 149 of file ecvCameraParamEditDlg.h.
Constructor & Destructor Documentation
ecvCameraParamEditDlg()
ecvCameraParamEditDlg::ecvCameraParamEditDlg (QWidget * parent, ccPickingHub * pickingHub) explicit
Default constructor.
Definition at line 113 of file ecvCameraParamEditDlg.cpp.
References ecvDisplayTools::AutoPickPivotAtCenter(), cameraChanged(), ecvDisplayTools::cameraParamChanged(), ConfigureCustomViewpoints(), pickPointAsPivot(), pivotChanged(), rotationFactorChanged(), ecvDisplayTools::TheInstance(), ecvSettingManager::TheInstance(), updateCamera(), and zfactorSliderMoved().
~ecvCameraParamEditDlg()
ecvCameraParamEditDlg::~ecvCameraParamEditDlg () override
Destructor.
Definition at line 198 of file ecvCameraParamEditDlg.cpp.
Member Function Documentation
AddCurrentViewpointToCustomViewpoints()
bool ecvCameraParamEditDlg::AddCurrentViewpointToCustomViewpoints () static
Add the current viewpoint to the custom viewpoints
Definition at line 666 of file ecvCameraParamEditDlg.cpp.
References ecvSettingManager::alertSettingsModified(), ecvSettingManager::beginGroup(), ecvGenericCameraTool::CurrentCameraParam, CustomViewpointConfigurations(), ecvSettingManager::endGroup(), ecvSettingManager::setValue(), ecvSettingManager::TheInstance(), and ecvGenericCameraTool::CameraInfo::toString().
Referenced by ecvCustomViewpointsToolbar::addCurrentViewpointToCustomViewpoints().
ApplyCustomViewpoint()
bool ecvCameraParamEditDlg::ApplyCustomViewpoint (int CustomViewpointIndex) static
Change camera positing to an indexed custom viewpoints
Definition at line 706 of file ecvCameraParamEditDlg.cpp.
References ApplyCustomViewpoint(), ecvSettingManager::beginGroup(), ecvGenericCameraTool::CurrentCameraParam, ecvSettingManager::endGroup(), ecvGenericCameraTool::CameraInfo::loadConfig(), ecvGenericCameraTool::SaveBuffer(), ecvSettingManager::TheInstance(), and ecvSettingManager::value().
Referenced by ApplyCustomViewpoint().
cameraChanged
void ecvCameraParamEditDlg::cameraChanged () protected slot
Definition at line 368 of file ecvCameraParamEditDlg.cpp.
References ecvGenericCameraTool::updateCameraParameters(), and updateUi().
Referenced by ecvCameraParamEditDlg().
ConfigureCustomViewpoints()
bool ecvCameraParamEditDlg::ConfigureCustomViewpoints (QWidget * parentWidget) static
Open the CustomViewpointDialog to configure customViewpoints
Definition at line 621 of file ecvCameraParamEditDlg.cpp.
References ecvSettingManager::alertSettingsModified(), ecvSettingManager::beginGroup(), ConfigureCustomViewpoints(), ecvGenericCameraTool::CurrentCameraParam, CustomViewpointConfigurations(), CustomViewpointToolTips(), ecvSettingManager::endGroup(), ecvCustomViewpointButtonDlg::getConfigurations(), ecvCustomViewpointButtonDlg::getToolTips(), ecvSettingManager::remove(), ecvSettingManager::setValue(), ecvSettingManager::TheInstance(), and ecvGenericCameraTool::CameraInfo::toString().
Referenced by ConfigureCustomViewpoints(), and ecvCameraParamEditDlg().
CustomViewpointConfigurations()
QStringList ecvCameraParamEditDlg::CustomViewpointConfigurations () static
Return the list of custom viewpoint configurations
Definition at line 775 of file ecvCameraParamEditDlg.cpp.
References ecvSettingManager::beginGroup(), ecvCustomViewpointButtonDlg::DEFAULT_TOOLTIP, ecvSettingManager::endGroup(), ecvCustomViewpointButtonDlg::MAXIMUM_NUMBER_OF_ITEMS, ecvCustomViewpointButtonDlg::MINIMUM_NUMBER_OF_ITEMS, and ecvSettingManager::TheInstance().
Referenced by AddCurrentViewpointToCustomViewpoints(), and ConfigureCustomViewpoints().
CustomViewpointToolTips()
QStringList ecvCameraParamEditDlg::CustomViewpointToolTips () static
Return the list of custom viewpoints tooltups
Definition at line 790 of file ecvCameraParamEditDlg.cpp.
References ecvSettingManager::beginGroup(), ecvCustomViewpointButtonDlg::DEFAULT_TOOLTIP, ecvSettingManager::endGroup(), ecvCustomViewpointButtonDlg::MAXIMUM_NUMBER_OF_ITEMS, ecvCustomViewpointButtonDlg::MINIMUM_NUMBER_OF_ITEMS, and ecvSettingManager::TheInstance().
Referenced by ConfigureCustomViewpoints(), DeleteCustomViewpoint(), and ecvCustomViewpointsToolbar::updateCustomViewpointActions().
DeleteCustomViewpoint()
bool ecvCameraParamEditDlg::DeleteCustomViewpoint (int CustomViewpointIndex) static
Delete an indexed custom viewpoint
Definition at line 725 of file ecvCameraParamEditDlg.cpp.
References ecvSettingManager::alertSettingsModified(), ecvSettingManager::beginGroup(), CustomViewpointToolTips(), ecvSettingManager::endGroup(), ecvSettingManager::remove(), ecvSettingManager::setValue(), ecvSettingManager::TheInstance(), and ecvSettingManager::value().
Referenced by ecvCustomViewpointsToolbar::DeleteCustomViewpoint().
initWith()
void ecvCameraParamEditDlg::initWith (QWidget * win) protected
Inits dialog values with specified window.
Definition at line 294 of file ecvCameraParamEditDlg.cpp.
References ecvGenericCameraTool::updateCameraParameters(), updateUi(), and updateViewMode().
Referenced by linkWith().
linkWith [1/2]
void ecvCameraParamEditDlg::linkWith (QMdiSubWindow * qWin) slot
Links this dialog with a given sub-window.
Definition at line 254 of file ecvCameraParamEditDlg.cpp.
References linkWith().
linkWith() [2/2]
bool ecvCameraParamEditDlg::linkWith (QWidget * win) override virtual
Links the overlay dialog with a MDI window.
Warning: link can't be modified while dialog is displayed/process is running!
Returns
success
Reimplemented from ccOverlayDialog.
Definition at line 262 of file ecvCameraParamEditDlg.cpp.
References initWith(), ccOverlayDialog::linkWith(), ccOverlayDialog::m_associatedWin, ecvDisplayTools::perspectiveStateChanged(), pickPointAsPivot(), ecvDisplayTools::pivotPointChanged(), ecvDisplayTools::TheInstance(), updatePivotPoint(), and updateViewMode().
Referenced by linkWith().
onItemPicked()
void ecvCameraParamEditDlg::onItemPicked (const PickedItem & pi) override virtual
Method called whenever an item is picked.
Implements ccPickingListener.
Definition at line 213 of file ecvCameraParamEditDlg.cpp.
References Vector3Tpl< double >::fromArray(), ccOverlayDialog::m_associatedWin, m_pickingHub, ccPickingListener::PickedItem::P3D, pickPointAsPivot(), ecvDisplayTools::SetPivotPoint(), Tuple3Tpl< Type >::u, and ecvDisplayTools::UpdateScreen().
pickPointAsPivot
void ecvCameraParamEditDlg::pickPointAsPivot (bool state) slot
Definition at line 852 of file ecvCameraParamEditDlg.cpp.
References ccPickingHub::addListener(), ecvDisplayTools::DEFAULT_PICKING, CVLog::Error(), ecvDisplayTools::itemPicked(), ccOverlayDialog::m_associatedWin, m_pickingHub, ecvDisplayTools::POINT_OR_TRIANGLE_PICKING, processPickedItem(), ccPickingHub::removeListener(), ecvDisplayTools::SetPickingMode(), and ecvDisplayTools::TheInstance().
Referenced by ecvCameraParamEditDlg(), linkWith(), onItemPicked(), and processPickedItem().
pivotChanged
void ecvCameraParamEditDlg::pivotChanged () slot
Definition at line 456 of file ecvCameraParamEditDlg.cpp.
References ecvGenericCameraTool::CurrentCameraParam, ccOverlayDialog::m_associatedWin, and ecvGenericCameraTool::CameraInfo::pivot.
Referenced by ecvCameraParamEditDlg().
processPickedItem
void ecvCameraParamEditDlg::processPickedItem (ccHObject * entity, unsigned , int , int , const CCVector3 & P) slot
Definition at line 226 of file ecvCameraParamEditDlg.cpp.
References Vector3Tpl< double >::fromArray(), ccOverlayDialog::m_associatedWin, pickPointAsPivot(), ecvDisplayTools::SetPivotPoint(), Tuple3Tpl< Type >::u, and ecvDisplayTools::UpdateScreen().
Referenced by pickPointAsPivot().
rotationFactorChanged
void ecvCameraParamEditDlg::rotationFactorChanged (double val) slot
Definition at line 469 of file ecvCameraParamEditDlg.cpp.
References ecvGenericCameraTool::CurrentCameraParam, and ecvGenericCameraTool::CameraInfo::rotationFactor.
Referenced by ecvCameraParamEditDlg().
SetCameraGroupsEnabled()
void ecvCameraParamEditDlg::SetCameraGroupsEnabled (bool enabled)
Definition at line 484 of file ecvCameraParamEditDlg.cpp.
setCameraTool()
bool ecvCameraParamEditDlg::setCameraTool (ecvGenericCameraTool * tool)
Definition at line 206 of file ecvCameraParamEditDlg.cpp.
SetToCurrentViewpoint()
bool ecvCameraParamEditDlg::SetToCurrentViewpoint (int CustomViewpointIndex) static
Set an indexed custom viewpoint to the current viewpoint
Definition at line 759 of file ecvCameraParamEditDlg.cpp.
References ecvSettingManager::alertSettingsModified(), ecvSettingManager::beginGroup(), ecvGenericCameraTool::CurrentCameraParam, ecvSettingManager::endGroup(), ecvSettingManager::setValue(), ecvSettingManager::TheInstance(), and e57::toString().
Referenced by ecvCustomViewpointsToolbar::SetToCurrentViewpoint().
start()
bool ecvCameraParamEditDlg::start (void) override virtual
Starts process.
Returns
success
Reimplemented from ccOverlayDialog.
Definition at line 244 of file ecvCameraParamEditDlg.cpp.
References ccOverlayDialog::m_processing, and ccOverlayDialog::start().
updateCamera
void ecvCameraParamEditDlg::updateCamera () protected slot
Definition at line 341 of file ecvCameraParamEditDlg.cpp.
References ecvGenericCameraTool::CameraInfo::clippRange, ecvGenericCameraTool::CurrentCameraParam, ecvGenericCameraTool::CameraInfo::eyeAngle, ecvGenericCameraTool::CameraInfo::focal, ecvGenericCameraTool::CameraInfo::position, ecvGenericCameraTool::CameraInfo::rotationFactor, ecvGenericCameraTool::CameraInfo::viewAngle, ecvGenericCameraTool::CameraInfo::viewUp, Vector2Tpl< Type >::x, Tuple3Tpl< Type >::x, Vector2Tpl< Type >::y, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ecvCameraParamEditDlg().
updatePivotPoint
void ecvCameraParamEditDlg::updatePivotPoint (const CCVector3d & P) slot
Updates dialog values with pivot point.
Definition at line 313 of file ecvCameraParamEditDlg.cpp.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by linkWith().
updateUi()
void ecvCameraParamEditDlg::updateUi () protected
Definition at line 382 of file ecvCameraParamEditDlg.cpp.
References ecvGenericCameraTool::CameraInfo::clippRange, ecvGenericCameraTool::CurrentCameraParam, ecvGenericCameraTool::CameraInfo::eyeAngle, ecvGenericCameraTool::CameraInfo::focal, ecvGenericCameraTool::CameraInfo::pivot, ecvGenericCameraTool::CameraInfo::position, ecvGenericCameraTool::CameraInfo::rotationFactor, ecvGenericCameraTool::CameraInfo::viewAngle, ecvGenericCameraTool::CameraInfo::viewUp, Vector2Tpl< Type >::x, Tuple3Tpl< Type >::x, Vector2Tpl< Type >::y, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by cameraChanged(), and initWith().
updateViewMode
void ecvCameraParamEditDlg::updateViewMode () slot
Updates current view mode.
Definition at line 325 of file ecvCameraParamEditDlg.cpp.
References ecvGenericDisplayTools::GetPerspectiveState(), and ccOverlayDialog::m_associatedWin.
Referenced by initWith(), and linkWith().
zfactorSliderMoved
void ecvCameraParamEditDlg::zfactorSliderMoved (int val) slot
Definition at line 479 of file ecvCameraParamEditDlg.cpp.
Referenced by ecvCameraParamEditDlg().
Member Data Documentation
m_pickingHub
ccPickingHub* ecvCameraParamEditDlg::m_pickingHub protected
Picking hub.
Definition at line 157 of file ecvCameraParamEditDlg.h.
Referenced by onItemPicked(), and pickPointAsPivot().
pushedMatrices
PushedMatricesMapType ecvCameraParamEditDlg::pushedMatrices protected
Pushed camera matrices (per window)
Definition at line 154 of file ecvCameraParamEditDlg.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVAppCommon/include/ecvCameraParamEditDlg.h
/root/ACloudViewer/libs/CVAppCommon/src/ecvCameraParamEditDlg.cpp