ACloudViewer: colmap::mvs::CachedWorkspace Class Reference
colmap::mvs::CachedWorkspace Class Reference
#include <workspace.h>
Public Member Functions
CachedWorkspace (const Options &options)
void Load (const std::vector< std::string > &image_names) override
void ClearCache ()
const Bitmap & GetBitmap (const int image_idx) override
const DepthMap & GetDepthMap (const int image_idx) override
const NormalMap & GetNormalMap (const int image_idx) override
Public Member Functions inherited from colmap::mvs::Workspace
Workspace (const Options &options)
const Options & GetOptions () const
const Model & GetModel () const
std::string GetBitmapPath (const int image_idx) const
std::string GetDepthMapPath (const int image_idx) const
std::string GetNormalMapPath (const int image_idx) const
bool HasBitmap (const int image_idx) const
bool HasDepthMap (const int image_idx) const
bool HasNormalMap (const int image_idx) const
Additional Inherited Members
Protected Member Functions inherited from colmap::mvs::Workspace
std::string GetFileName (const int image_idx) const
Protected Attributes inherited from colmap::mvs::Workspace
Options options_
Model model_
Detailed Description
Definition at line 81 of file workspace.h.
Constructor & Destructor Documentation
CachedWorkspace()
colmap::mvs::CachedWorkspace::CachedWorkspace (const Options & options)
Definition at line 173 of file workspace.cc.
Member Function Documentation
ClearCache()
void colmap::mvs::CachedWorkspace::ClearCache () inline
Definition at line 87 of file workspace.h.
References colmap::MemoryConstrainedLRUCache< key_t, value_t >::Clear().
GetBitmap()
const Bitmap & colmap::mvs::CachedWorkspace::GetBitmap (const int image_idx) override virtual
Reimplemented from colmap::mvs::Workspace.
Definition at line 178 of file workspace.cc.
References colmap::MemoryConstrainedLRUCache< key_t, value_t >::Get(), colmap::mvs::Workspace::GetBitmapPath(), colmap::mvs::Workspace::Options::image_as_rgb, colmap::mvs::Model::images, colmap::mvs::Workspace::Options::max_image_size, colmap::mvs::Workspace::model_, colmap::mvs::Workspace::options_, and colmap::MemoryConstrainedLRUCache< key_t, value_t >::UpdateNumBytes().
GetDepthMap()
const DepthMap & colmap::mvs::CachedWorkspace::GetDepthMap (const int image_idx) override virtual
Reimplemented from colmap::mvs::Workspace.
Definition at line 194 of file workspace.cc.
References colmap::MemoryConstrainedLRUCache< key_t, value_t >::Get(), colmap::mvs::Workspace::GetDepthMapPath(), colmap::mvs::Model::images, colmap::mvs::Workspace::Options::max_image_size, colmap::mvs::Workspace::model_, colmap::mvs::Workspace::options_, and colmap::MemoryConstrainedLRUCache< key_t, value_t >::UpdateNumBytes().
GetNormalMap()
const NormalMap & colmap::mvs::CachedWorkspace::GetNormalMap (const int image_idx) override virtual
Reimplemented from colmap::mvs::Workspace.
Definition at line 210 of file workspace.cc.
References colmap::MemoryConstrainedLRUCache< key_t, value_t >::Get(), colmap::mvs::Workspace::GetNormalMapPath(), colmap::mvs::Model::images, colmap::mvs::Workspace::Options::max_image_size, colmap::mvs::Workspace::model_, colmap::mvs::Workspace::options_, and colmap::MemoryConstrainedLRUCache< key_t, value_t >::UpdateNumBytes().
Load()
void colmap::mvs::CachedWorkspace::Load (const std::vector< std::string > & image_names) inline override virtual
Reimplemented from colmap::mvs::Workspace.
Definition at line 85 of file workspace.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/mvs/workspace.h
/root/ACloudViewer/libs/Reconstruction/src/mvs/workspace.cc