ACloudViewer: PdmsTools::PdmsCommands::Orientation Class Reference
PdmsTools::PdmsCommands::Orientation Class Reference
#include <PdmsTools.h>
Public Member Functions
Orientation ()
virtual bool handle (Token t)
virtual bool handle (PointCoordinateType numvalue)
virtual bool handle (const char *str)
virtual bool isValid () const
bool getAxes (CCVector3 &x, CCVector3 &y, CCVector3 &z) const
virtual bool execute (PdmsObjects::GenericItem *&item) const
Public Member Functions inherited from PdmsTools::PdmsCommands::Command
Command (Token t)
Command (const Command &com)
virtual ~Command ()
Public Attributes
Coordinates orientation [3]
Reference refs [3]
Command * current
int component
Public Attributes inherited from PdmsTools::PdmsCommands::Command
Token command
Protected Member Functions
int getNbComponents () const
Static Protected Member Functions
static bool axisFromCoords (const Coordinates &coords, CCVector3 &u)
Additional Inherited Members
Static Public Member Functions inherited from PdmsTools::PdmsCommands::Command
static Command * Create (Token t)
Factory.
Detailed Description
Definition at line 577 of file PdmsTools.h.
Constructor & Destructor Documentation
Orientation()
PdmsTools::PdmsCommands::Orientation::Orientation () inline
Definition at line 584 of file PdmsTools.h.
References component, and current.
Member Function Documentation
axisFromCoords()
bool Orientation::axisFromCoords (const Coordinates & coords, CCVector3 & u) static protected
Definition at line 488 of file PdmsTools.cpp.
References cloudViewer::DegreesToRadians(), PdmsTools::PdmsCommands::Coordinates::getNbComponents(), and PdmsTools::PdmsCommands::Coordinates::getVector().
execute()
bool Orientation::execute (PdmsObjects::GenericItem *& item) const virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 508 of file PdmsTools.cpp.
References PdmsTools::PdmsObjects::GenericItem::orientationReferences, and PdmsTools::PdmsObjects::GenericItem::setOrientation().
getAxes()
bool Orientation::getAxes (CCVector3 & x, CCVector3 & y, CCVector3 & z) const
Definition at line 442 of file PdmsTools.cpp.
References PdmsTools::PDMS_DOWN, PdmsTools::PDMS_EST, PdmsTools::PDMS_NORTH, PdmsTools::PDMS_SOUTH, PdmsTools::PDMS_UP, PdmsTools::PDMS_WEST, PdmsTools::PDMS_X, PdmsTools::PDMS_Y, and PdmsTools::PDMS_Z.
getNbComponents()
int Orientation::getNbComponents () const protected
Definition at line 502 of file PdmsTools.cpp.
handle() [1/3]
bool Orientation::handle (const char * str) virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 425 of file PdmsTools.cpp.
handle() [2/3]
bool Orientation::handle (PointCoordinateType numvalue) virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 421 of file PdmsTools.cpp.
handle() [3/3]
bool Orientation::handle (Token t) virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 382 of file PdmsTools.cpp.
References PdmsTools::PdmsToken::isCoordinate(), PdmsTools::PDMS_AND, PdmsTools::PDMS_IS, and PdmsTools::PDMS_WRT.
isValid()
bool Orientation::isValid () const virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 429 of file PdmsTools.cpp.
References PdmsTools::PdmsToken::isCoordinate(), and PdmsTools::PDMS_WRT.
Member Data Documentation
component
int PdmsTools::PdmsCommands::Orientation::component
Definition at line 582 of file PdmsTools.h.
Referenced by Orientation().
current
Command* PdmsTools::PdmsCommands::Orientation::current
Definition at line 581 of file PdmsTools.h.
Referenced by Orientation().
orientation
Coordinates PdmsTools::PdmsCommands::Orientation::orientation[3]
Definition at line 579 of file PdmsTools.h.
refs
Reference PdmsTools::PdmsCommands::Orientation::refs[3]
Definition at line 580 of file PdmsTools.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsTools.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsTools.cpp