ACloudViewer: PclPointCloudColorHandlerLUT< PointT > Class Template Reference
PclPointCloudColorHandlerLUT< PointT > Class Template Reference
#include <PclPointCloudColorHandlerLUT.h>
Public Types
typedef pcl::PointCloud< PointT > PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
typedef std::shared_ptr< PclPointCloudColorHandlerLUT< PointT > > Ptr
typedef std::shared_ptr< const PclPointCloudColorHandlerLUT< PointT > > ConstPtr
Public Member Functions
PclPointCloudColorHandlerLUT ()
Constructor.
PclPointCloudColorHandlerLUT (const PointCloudConstPtr &cloud)
Constructor.
virtual ~PclPointCloudColorHandlerLUT ()
Destructor.
bool isCapable () const
Check if this handler is capable of handling the input data or not.
virtual std::string getName () const
Abstract getName method.
virtual std::string getFieldName () const
Abstract getFieldName method.
virtual bool getColor (vtkSmartPointer< vtkDataArray > &scalars) const
Obtain the actual color for the input dataset as vtk scalars.
virtual vtkSmartPointer< vtkDataArray > getColor () const
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Set the input cloud to be used.
void setLabel (int *value)
Detailed Description
template<typename PointT>
class PclPointCloudColorHandlerLUT< PointT >
Definition at line 26 of file PclPointCloudColorHandlerLUT.h.
Member Typedef Documentation
ConstPtr
template<typename PointT > typedef std::shared_ptr<const PclPointCloudColorHandlerLUT<PointT> > PclPointCloudColorHandlerLUT< PointT >::ConstPtr
Definition at line 34 of file PclPointCloudColorHandlerLUT.h.
PointCloud
template<typename PointT > typedef pcl::PointCloud<PointT> PclPointCloudColorHandlerLUT< PointT >::PointCloud
Definition at line 28 of file PclPointCloudColorHandlerLUT.h.
PointCloudConstPtr
template<typename PointT > typedef PointCloud::ConstPtr PclPointCloudColorHandlerLUT< PointT >::PointCloudConstPtr
Definition at line 30 of file PclPointCloudColorHandlerLUT.h.
PointCloudPtr
template<typename PointT > typedef PointCloud::Ptr PclPointCloudColorHandlerLUT< PointT >::PointCloudPtr
Definition at line 29 of file PclPointCloudColorHandlerLUT.h.
Ptr
template<typename PointT > typedef std::shared_ptr<PclPointCloudColorHandlerLUT<PointT> > PclPointCloudColorHandlerLUT< PointT >::Ptr
Definition at line 32 of file PclPointCloudColorHandlerLUT.h.
Constructor & Destructor Documentation
PclPointCloudColorHandlerLUT() [1/2]
template<typename PointT > PclPointCloudColorHandlerLUT< PointT >::PclPointCloudColorHandlerLUT () inline
Constructor.
Definition at line 37 of file PclPointCloudColorHandlerLUT.h.
PclPointCloudColorHandlerLUT() [2/2]
template<typename PointT > PclPointCloudColorHandlerLUT< PointT >::PclPointCloudColorHandlerLUT (const PointCloudConstPtr & cloud) inline
Constructor.
Definition at line 42 of file PclPointCloudColorHandlerLUT.h.
References PclPointCloudColorHandlerLUT< PointT >::setInputCloud().
~PclPointCloudColorHandlerLUT()
template<typename PointT > virtual PclPointCloudColorHandlerLUT< PointT >::~PclPointCloudColorHandlerLUT () inline virtual
Destructor.
Definition at line 48 of file PclPointCloudColorHandlerLUT.h.
Member Function Documentation
getColor() [1/2]
template<typename PointT > virtual vtkSmartPointer<vtkDataArray> PclPointCloudColorHandlerLUT< PointT >::getColor () const inline virtual
Definition at line 95 of file PclPointCloudColorHandlerLUT.h.
References PclCloudLUT::at(), color, and colors.
getColor() [2/2]
template<typename PointT > virtual bool PclPointCloudColorHandlerLUT< PointT >::getColor (vtkSmartPointer< vtkDataArray > & scalars) const inline virtual
Obtain the actual color for the input dataset as vtk scalars.
Parameters
[out] scalars the output scalars containing the color for the dataset
Returns
true if the operation was successful (the handler is capable and the input cloud was given as a valid pointer), false otherwise
Definition at line 66 of file PclPointCloudColorHandlerLUT.h.
References PclCloudLUT::at(), color, and colors.
getFieldName()
template<typename PointT > virtual std::string PclPointCloudColorHandlerLUT< PointT >::getFieldName () const inline virtual
Abstract getFieldName method.
Definition at line 58 of file PclPointCloudColorHandlerLUT.h.
getName()
template<typename PointT > virtual std::string PclPointCloudColorHandlerLUT< PointT >::getName () const inline virtual
Abstract getName method.
Definition at line 55 of file PclPointCloudColorHandlerLUT.h.
isCapable()
template<typename PointT > bool PclPointCloudColorHandlerLUT< PointT >::isCapable () const inline
Check if this handler is capable of handling the input data or not.
Definition at line 52 of file PclPointCloudColorHandlerLUT.h.
setInputCloud()
template<typename PointT > virtual void PclPointCloudColorHandlerLUT< PointT >::setInputCloud (const PointCloudConstPtr & cloud) inline virtual
Set the input cloud to be used.
Parameters
[in] cloud the input cloud to be used by the handler
Definition at line 127 of file PclPointCloudColorHandlerLUT.h.
Referenced by PclPointCloudColorHandlerLUT< PointT >::PclPointCloudColorHandlerLUT().
setLabel()
template<typename PointT > void PclPointCloudColorHandlerLUT< PointT >::setLabel (int * value) inline
Definition at line 131 of file PclPointCloudColorHandlerLUT.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/PCLEngine/Tools/ColorTools/PclPointCloudColorHandlerLUT.h