ACloudViewer: cloudViewer::visualization::rendering::TLineSetBuffersBuilder Class Reference
cloudViewer::visualization::rendering::TLineSetBuffersBuilder Class Reference
#include <FilamentGeometryBuffersBuilder.h>
Public Member Functions
TLineSetBuffersBuilder (const t::geometry::LineSet &geometry)
filament::RenderableManager::PrimitiveType GetPrimitiveType () const override
Buffers ConstructBuffers () override
filament::Box ComputeAABB () override
Public Member Functions inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
virtual ~GeometryBuffersBuilder ()=default
virtual void SetDownsampleThreshold (size_t min_points)
virtual void SetWideLines ()
virtual void SetAdjustColorsForSRGBToneMapping (bool adjust)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
using Buffers = std::tuple< VertexBufferHandle, IndexBufferHandle, IndexBufferHandle >
using IndexType = std::uint32_t
Static Public Member Functions inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
static std::unique_ptr< GeometryBuffersBuilder > GetBuilder (const ccHObject &geometry)
static std::unique_ptr< GeometryBuffersBuilder > GetBuilder (const t::geometry::Geometry &geometry)
Static Protected Member Functions inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
static void DeallocateBuffer (void *buffer, size_t size, void *user_ptr)
static IndexBufferHandle CreateIndexBuffer (size_t max_index, size_t n_subsamples=SIZE_MAX)
Protected Attributes inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
size_t downsample_threshold_ = SIZE_MAX
bool wide_lines_ = false
bool adjust_colors_for_srgb_tonemapping_ = true
Detailed Description
Definition at line 215 of file FilamentGeometryBuffersBuilder.h.
Constructor & Destructor Documentation
TLineSetBuffersBuilder()
cloudViewer::visualization::rendering::TLineSetBuffersBuilder::TLineSetBuffersBuilder (const t::geometry::LineSet & geometry) explicit
Definition at line 366 of file LineSetBuffers.cpp.
References colors, cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDtype(), cloudViewer::t::geometry::LineSet::GetLineColors(), cloudViewer::t::geometry::LineSet::GetLineIndices(), cloudViewer::t::geometry::LineSet::GetPointPositions(), cloudViewer::t::geometry::LineSet::HasLineColors(), cloudViewer::t::geometry::LineSet::HasLineIndices(), LogWarning, cloudViewer::t::geometry::LineSet::To(), cloudViewer::core::Tensor::To(), cloudViewer::core::UInt32, and cloudViewer::core::UInt8.
Member Function Documentation
ComputeAABB()
filament::Box cloudViewer::visualization::rendering::TLineSetBuffersBuilder::ComputeAABB () override virtual
Implements cloudViewer::visualization::rendering::GeometryBuffersBuilder.
Definition at line 633 of file LineSetBuffers.cpp.
References cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::t::geometry::LineSet::GetMaxBound(), cloudViewer::t::geometry::LineSet::GetMinBound(), max(), and min().
ConstructBuffers()
GeometryBuffersBuilder::Buffers cloudViewer::visualization::rendering::TLineSetBuffersBuilder::ConstructBuffers () override virtual
Implements cloudViewer::visualization::rendering::GeometryBuffersBuilder.
Definition at line 551 of file LineSetBuffers.cpp.
References cloudViewer::visualization::rendering::GeometryBuffersBuilder::DeallocateBuffer(), cloudViewer::visualization::rendering::EngineInstance::GetInstance(), cloudViewer::visualization::rendering::EngineInstance::GetResourceManager(), cloudViewer::visualization::rendering::VertexBuffer, and cloudViewer::visualization::rendering::GeometryBuffersBuilder::wide_lines_.
GetPrimitiveType()
RenderableManager::PrimitiveType cloudViewer::visualization::rendering::TLineSetBuffersBuilder::GetPrimitiveType () const override virtual
Implements cloudViewer::visualization::rendering::GeometryBuffersBuilder.
Definition at line 403 of file LineSetBuffers.cpp.
References cloudViewer::visualization::rendering::GeometryBuffersBuilder::wide_lines_.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentGeometryBuffersBuilder.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/LineSetBuffers.cpp