ACloudViewer: VtkUtils::Surface Class Reference
VtkUtils::Surface Class Reference
#include <surface.h>
Public Member Functions
Surface (QWidget *parent=nullptr)
virtual ~Surface ()
void setPoints (const QList< Point3F > &points)
Public Member Functions inherited from VtkUtils::VtkWidget
VtkWidget (QWidget *parent=nullptr)
virtual ~VtkWidget ()
void setMultiViewports (bool multi=true)
bool multiViewports () const
void createActorFromVTKDataSet (const vtkSmartPointer< vtkDataSet > &data, vtkSmartPointer< vtkLODActor > &actor, bool use_scalars=true)
void addActor (vtkProp *actor, const QColor &clr=Qt::black)
void addViewProp (vtkProp *prop)
QList< vtkProp * > actors () const
void setActorsVisible (bool visible)
void setActorVisible (vtkProp *actor, bool visible)
bool actorVisible (vtkProp *actor)
void setBackgroundColor (const QColor &clr)
void setBackgroundColor ()
QColor backgroundColor () const
vtkRenderer * defaultRenderer ()
bool defaultRendererTaken () const
void showOrientationMarker (bool show=true)
vtkRenderWindow * GetRenderWindow ()
QVTKInteractor * GetInteractor ()
Protected Member Functions
virtual void renderSurface ()
vtkActor * surfaceActor () const
Protected Member Functions inherited from VtkUtils::VtkWidget
void setBounds (double *bounds)
double xMin () const
double xMax () const
double yMin () const
double yMax () const
double zMin () const
double zMax () const
Detailed Description
Definition at line 18 of file surface.h.
Constructor & Destructor Documentation
Surface()
VtkUtils::Surface::Surface (QWidget * parent = nullptr) explicit
Definition at line 29 of file surface.cpp.
~Surface()
VtkUtils::Surface::~Surface () virtual
Definition at line 33 of file surface.cpp.
Member Function Documentation
renderSurface()
void VtkUtils::Surface::renderSurface () protected virtual
Reimplemented in VtkUtils::Contour.
Definition at line 40 of file surface.cpp.
References VtkUtils::VtkWidget::defaultRenderer(), surfaceActor(), VTK_CREATE, VtkUtils::Point3F::x, VtkUtils::Point3F::y, and VtkUtils::Point3F::z.
Referenced by setPoints().
setPoints()
void VtkUtils::Surface::setPoints (const QList< Point3F > & points)
Definition at line 35 of file surface.cpp.
References points, and renderSurface().
surfaceActor()
vtkActor * VtkUtils::Surface::surfaceActor () const protected
Definition at line 65 of file surface.cpp.
References VtkUtils::vtkInitOnce().
Referenced by VtkUtils::Contour::renderSurface(), and renderSurface().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/surface.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/surface.cpp