ACloudViewer: cloudViewer::visualization::rendering::MatrixInteractorLogic Class Reference
cloudViewer::visualization::rendering::MatrixInteractorLogic Class Reference
#include <MatrixInteractorLogic.h>
Public Types
enum class DragType { MOUSE , WHEEL , TWO_FINGER }
Public Member Functions
virtual ~MatrixInteractorLogic ()
void SetViewSize (int width, int height)
int GetViewWidth () const
int GetViewHeight () const
const ccBBox & GetBoundingBox () const
virtual void SetBoundingBox (const ccBBox &bounds)
Eigen::Vector3f GetCenterOfRotation () const
void SetMouseDownInfo (const Camera::Transform &matrix, const Eigen::Vector3f &center_of_rotation)
const Camera::Transform & GetMatrix () const
virtual void Rotate (int dx, int dy)
virtual void RotateWorld (int dx, int dy, const Eigen::Vector3f &x_axis, const Eigen::Vector3f &y_axis)
virtual void RotateZ (int dx, int dy)
Rotates about the forward axis of the matrix.
virtual void RotateZWorld (int dx, int dy, const Eigen::Vector3f &forward)
virtual void Dolly (float dy, DragType drag_type)
virtual void Dolly (float z_dist, Camera::Transform matrix)
Protected Member Functions
void SetMatrix (const Camera::Transform &matrix)
float CalcRotateRadians (int dx, int dy)
float CalcRotateZRadians (int dx, int dy)
float CalcDollyDist (float dy, DragType drag_type, const Camera::Transform &matrix)
Protected Attributes
int view_width_ = 1
int view_height_ = 1
double model_size_ = 20.0
ccBBox model_bounds_
Eigen::Vector3f center_of_rotation_
Camera::Transform matrix_at_mouse_down_
Eigen::Vector3f center_of_rotation_at_mouse_down_
Detailed Description
Base class for rotating and dollying (translating along forward axis). Could be used for a camera, or also something else, like a the direction of a directional light.
Definition at line 21 of file MatrixInteractorLogic.h.
Member Enumeration Documentation
DragType
enum cloudViewer::visualization::rendering::MatrixInteractorLogic::DragType strong
Enumerator
MOUSE
WHEEL
TWO_FINGER
Definition at line 57 of file MatrixInteractorLogic.h.
Constructor & Destructor Documentation
~MatrixInteractorLogic()
cloudViewer::visualization::rendering::MatrixInteractorLogic::~MatrixInteractorLogic () virtual
Definition at line 14 of file MatrixInteractorLogic.cpp.
Member Function Documentation
CalcDollyDist()
float cloudViewer::visualization::rendering::MatrixInteractorLogic::CalcDollyDist (float dy, DragType drag_type, const Camera::Transform & matrix) protected
Definition at line 189 of file MatrixInteractorLogic.cpp.
References center_of_rotation_, dist(), length(), max(), model_size_, MOUSE, TWO_FINGER, and WHEEL.
Referenced by Dolly(), and cloudViewer::visualization::rendering::ModelInteractorLogic::Dolly().
CalcRotateRadians()
float cloudViewer::visualization::rendering::MatrixInteractorLogic::CalcRotateRadians (int dx, int dy) protected
Definition at line 128 of file MatrixInteractorLogic.cpp.
References M_PI, and view_height_.
Referenced by Rotate(), cloudViewer::visualization::rendering::ModelInteractorLogic::Rotate(), and RotateWorld().
CalcRotateZRadians()
float cloudViewer::visualization::rendering::MatrixInteractorLogic::CalcRotateZRadians (int dx, int dy) protected
Definition at line 157 of file MatrixInteractorLogic.cpp.
References M_PI, and view_height_.
Referenced by RotateZ(), cloudViewer::visualization::rendering::ModelInteractorLogic::RotateZ(), and RotateZWorld().
Dolly() [1/2]
void cloudViewer::visualization::rendering::MatrixInteractorLogic::Dolly (float dy, DragType drag_type) virtual
Moves the matrix along the forward axis. (This is one type of zoom.)
Reimplemented in cloudViewer::visualization::rendering::CameraInteractorLogic, and cloudViewer::visualization::rendering::ModelInteractorLogic.
Definition at line 163 of file MatrixInteractorLogic.cpp.
References CalcDollyDist(), dist(), matrix_at_mouse_down_, and MOUSE.
Referenced by cloudViewer::visualization::rendering::CameraInteractorLogic::Dolly(), and cloudViewer::visualization::gui::RotationInteractor::Mouse().
Dolly() [2/2]
void cloudViewer::visualization::rendering::MatrixInteractorLogic::Dolly (float z_dist, Camera::Transform matrix) virtual
Reimplemented in cloudViewer::visualization::rendering::CameraInteractorLogic.
Definition at line 175 of file MatrixInteractorLogic.cpp.
GetBoundingBox()
const ccBBox & cloudViewer::visualization::rendering::MatrixInteractorLogic::GetBoundingBox () const
Definition at line 25 of file MatrixInteractorLogic.cpp.
References model_bounds_.
GetCenterOfRotation()
Eigen::Vector3f cloudViewer::visualization::rendering::MatrixInteractorLogic::GetCenterOfRotation () const
Definition at line 34 of file MatrixInteractorLogic.cpp.
References center_of_rotation_.
Referenced by cloudViewer::visualization::gui::RotationInteractor::GetCenterOfRotation().
GetMatrix()
const Camera::Transform & cloudViewer::visualization::rendering::MatrixInteractorLogic::GetMatrix () const
Definition at line 52 of file MatrixInteractorLogic.cpp.
Referenced by cloudViewer::visualization::rendering::CameraInteractorLogic::Dolly(), cloudViewer::visualization::rendering::LightDirectionInteractorLogic::GetCurrentDirection(), cloudViewer::visualization::rendering::IBLRotationInteractorLogic::GetCurrentRotation(), cloudViewer::visualization::rendering::CameraInteractorLogic::Pan(), cloudViewer::visualization::rendering::CameraInteractorLogic::Rotate(), cloudViewer::visualization::rendering::CameraInteractorLogic::RotateFly(), cloudViewer::visualization::rendering::CameraInteractorLogic::RotateZ(), cloudViewer::visualization::rendering::RotationInteractorLogic::StartMouseDrag(), and cloudViewer::visualization::rendering::LightDirectionInteractorLogic::UpdateMouseDragUI().
GetViewHeight()
int cloudViewer::visualization::rendering::MatrixInteractorLogic::GetViewHeight () const
Definition at line 23 of file MatrixInteractorLogic.cpp.
References view_height_.
Referenced by cloudViewer::visualization::gui::PickPointsInteractor::DoPick().
GetViewWidth()
int cloudViewer::visualization::rendering::MatrixInteractorLogic::GetViewWidth () const
Definition at line 21 of file MatrixInteractorLogic.cpp.
References view_width_.
Referenced by cloudViewer::visualization::gui::PickPointsInteractor::DoPick().
Rotate()
void cloudViewer::visualization::rendering::MatrixInteractorLogic::Rotate (int dx, int dy) virtual
Rotates about an axis defined by dx * matrixLeft, dy * matrixUp. dy is assumed to be in window-style coordinates, that is, going up produces a negative dy. The axis goes through the center of rotation.
Reimplemented in cloudViewer::visualization::rendering::ModelInteractorLogic, cloudViewer::visualization::rendering::LightDirectionInteractorLogic, cloudViewer::visualization::rendering::IBLRotationInteractorLogic, cloudViewer::visualization::rendering::CameraSphereInteractorLogic, and cloudViewer::visualization::rendering::CameraInteractorLogic.
Definition at line 56 of file MatrixInteractorLogic.cpp.
References CalcRotateRadians(), center_of_rotation_, dist(), and matrix_at_mouse_down_.
Referenced by cloudViewer::visualization::gui::RotationInteractor::Mouse(), cloudViewer::visualization::rendering::CameraInteractorLogic::Rotate(), and cloudViewer::visualization::rendering::CameraInteractorLogic::RotateFly().
RotateWorld()
void cloudViewer::visualization::rendering::MatrixInteractorLogic::RotateWorld (int dx, int dy, const Eigen::Vector3f & x_axis, const Eigen::Vector3f & y_axis) virtual
Same as Rotate() except that the dx-axis and the dy-axis are specified
Definition at line 101 of file MatrixInteractorLogic.cpp.
References CalcRotateRadians(), center_of_rotation_, dist(), and matrix_at_mouse_down_.
Referenced by cloudViewer::visualization::rendering::IBLRotationInteractorLogic::Rotate(), cloudViewer::visualization::rendering::LightDirectionInteractorLogic::Rotate(), and cloudViewer::visualization::rendering::IBLRotationInteractorLogic::RotateZ().
RotateZ()
void cloudViewer::visualization::rendering::MatrixInteractorLogic::RotateZ (int dx, int dy) virtual
Rotates about the forward axis of the matrix.
Reimplemented in cloudViewer::visualization::rendering::ModelInteractorLogic, cloudViewer::visualization::rendering::IBLRotationInteractorLogic, and cloudViewer::visualization::rendering::CameraInteractorLogic.
Definition at line 133 of file MatrixInteractorLogic.cpp.
References CalcRotateZRadians(), and matrix_at_mouse_down_.
Referenced by cloudViewer::visualization::gui::RotationInteractor::Mouse(), and cloudViewer::visualization::rendering::CameraInteractorLogic::RotateZ().
RotateZWorld()
void cloudViewer::visualization::rendering::MatrixInteractorLogic::RotateZWorld (int dx, int dy, const Eigen::Vector3f & forward) virtual
Definition at line 144 of file MatrixInteractorLogic.cpp.
References CalcRotateZRadians(), center_of_rotation_, and matrix_at_mouse_down_.
SetBoundingBox()
void cloudViewer::visualization::rendering::MatrixInteractorLogic::SetBoundingBox (const ccBBox & bounds) virtual
Reimplemented in cloudViewer::visualization::rendering::ModelInteractorLogic, and cloudViewer::visualization::rendering::CameraInteractorLogic.
Definition at line 29 of file MatrixInteractorLogic.cpp.
References ccBBox::GetMaxBound(), ccBBox::GetMinBound(), model_bounds_, and model_size_.
Referenced by cloudViewer::visualization::rendering::CameraInteractorLogic::SetBoundingBox(), and cloudViewer::visualization::rendering::ModelInteractorLogic::SetBoundingBox().
SetMatrix()
void cloudViewer::visualization::rendering::MatrixInteractorLogic::SetMatrix (const Camera::Transform & matrix) protected
Definition at line 48 of file MatrixInteractorLogic.cpp.
Referenced by cloudViewer::visualization::rendering::RotationInteractorLogic::Pan(), and cloudViewer::visualization::rendering::CameraSphereInteractorLogic::Rotate().
SetMouseDownInfo()
void cloudViewer::visualization::rendering::MatrixInteractorLogic::SetMouseDownInfo (const Camera::Transform & matrix, const Eigen::Vector3f & center_of_rotation)
Definition at line 38 of file MatrixInteractorLogic.cpp.
References center_of_rotation_, center_of_rotation_at_mouse_down_, and matrix_at_mouse_down_.
Referenced by cloudViewer::visualization::rendering::CameraInteractorLogic::Dolly(), cloudViewer::visualization::rendering::CameraInteractorLogic::RotateFly(), cloudViewer::visualization::rendering::CameraInteractorLogic::SetBoundingBox(), cloudViewer::visualization::rendering::ModelInteractorLogic::SetBoundingBox(), cloudViewer::visualization::rendering::IBLRotationInteractorLogic::StartMouseDrag(), cloudViewer::visualization::rendering::LightDirectionInteractorLogic::StartMouseDrag(), cloudViewer::visualization::rendering::RotationInteractorLogic::StartMouseDrag(), cloudViewer::visualization::rendering::CameraInteractorLogic::StartMouseDrag(), and cloudViewer::visualization::rendering::ModelInteractorLogic::StartMouseDrag().
SetViewSize()
void cloudViewer::visualization::rendering::MatrixInteractorLogic::SetViewSize (int width, int height)
Definition at line 16 of file MatrixInteractorLogic.cpp.
References height, view_height_, view_width_, and width.
Referenced by cloudViewer::visualization::gui::PickInteractor::SetViewSize().
Member Data Documentation
center_of_rotation_
Eigen::Vector3f cloudViewer::visualization::rendering::MatrixInteractorLogic::center_of_rotation_ protected
Definition at line 72 of file MatrixInteractorLogic.h.
Referenced by CalcDollyDist(), cloudViewer::visualization::rendering::CameraInteractorLogic::Dolly(), GetCenterOfRotation(), cloudViewer::visualization::rendering::RotationInteractorLogic::Pan(), cloudViewer::visualization::rendering::ModelInteractorLogic::Pan(), Rotate(), cloudViewer::visualization::rendering::CameraSphereInteractorLogic::Rotate(), cloudViewer::visualization::rendering::ModelInteractorLogic::Rotate(), RotateWorld(), cloudViewer::visualization::rendering::ModelInteractorLogic::RotateZ(), RotateZWorld(), cloudViewer::visualization::rendering::RotationInteractorLogic::SetCenterOfRotation(), SetMouseDownInfo(), cloudViewer::visualization::rendering::RotationInteractorLogic::StartMouseDrag(), cloudViewer::visualization::rendering::CameraInteractorLogic::StartMouseDrag(), cloudViewer::visualization::rendering::CameraSphereInteractorLogic::StartMouseDrag(), cloudViewer::visualization::rendering::ModelInteractorLogic::StartMouseDrag(), and cloudViewer::visualization::rendering::CameraInteractorLogic::Zoom().
center_of_rotation_at_mouse_down_
Eigen::Vector3f cloudViewer::visualization::rendering::MatrixInteractorLogic::center_of_rotation_at_mouse_down_ protected
Definition at line 75 of file MatrixInteractorLogic.h.
Referenced by cloudViewer::visualization::rendering::RotationInteractorLogic::CalcPanVectorWorld(), cloudViewer::visualization::rendering::RotationInteractorLogic::Pan(), cloudViewer::visualization::rendering::ModelInteractorLogic::Pan(), SetMouseDownInfo(), and cloudViewer::visualization::rendering::CameraInteractorLogic::Zoom().
matrix_at_mouse_down_
Camera::Transform cloudViewer::visualization::rendering::MatrixInteractorLogic::matrix_at_mouse_down_ protected
Definition at line 74 of file MatrixInteractorLogic.h.
Referenced by Dolly(), cloudViewer::visualization::rendering::ModelInteractorLogic::Dolly(), cloudViewer::visualization::rendering::RotationInteractorLogic::Pan(), Rotate(), RotateWorld(), RotateZ(), RotateZWorld(), SetMouseDownInfo(), and cloudViewer::visualization::rendering::CameraInteractorLogic::Zoom().
model_bounds_
ccBBox cloudViewer::visualization::rendering::MatrixInteractorLogic::model_bounds_ protected
Definition at line 71 of file MatrixInteractorLogic.h.
Referenced by GetBoundingBox(), SetBoundingBox(), cloudViewer::visualization::rendering::RotationInteractorLogic::UpdateCameraFarPlane(), and cloudViewer::visualization::rendering::LightDirectionInteractorLogic::UpdateMouseDragUI().
model_size_
double cloudViewer::visualization::rendering::MatrixInteractorLogic::model_size_ = 20.0 protected
Definition at line 70 of file MatrixInteractorLogic.h.
Referenced by CalcDollyDist(), SetBoundingBox(), and cloudViewer::visualization::rendering::LightDirectionInteractorLogic::StartMouseDrag().
view_height_
int cloudViewer::visualization::rendering::MatrixInteractorLogic::view_height_ = 1 protected
Definition at line 69 of file MatrixInteractorLogic.h.
Referenced by cloudViewer::visualization::rendering::RotationInteractorLogic::CalcPanVectorWorld(), CalcRotateRadians(), CalcRotateZRadians(), GetViewHeight(), cloudViewer::visualization::rendering::CameraSphereInteractorLogic::Rotate(), SetViewSize(), and cloudViewer::visualization::rendering::CameraInteractorLogic::Zoom().
view_width_
int cloudViewer::visualization::rendering::MatrixInteractorLogic::view_width_ = 1 protected
Definition at line 68 of file MatrixInteractorLogic.h.
Referenced by GetViewWidth(), cloudViewer::visualization::rendering::CameraSphereInteractorLogic::Rotate(), SetViewSize(), and cloudViewer::visualization::rendering::CameraInteractorLogic::Zoom().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/MatrixInteractorLogic.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/MatrixInteractorLogic.cpp