ACloudViewer: vtkPVPostFilter Class Reference
vtkPVPostFilter Class Reference
#include <vtkPVPostFilter.h>
Public Member Functions
vtkTypeMacro (vtkPVPostFilter, vtkDataObjectAlgorithm)
void PrintSelf (ostream &os, vtkIndent indent) override
vtkExecutive * CreateDefaultExecutive () override
Static Public Member Functions
static vtkPVPostFilter * New ()
static std::string DefaultComponentName (int componentNumber, int componentCount)
Protected Member Functions
vtkPVPostFilter ()
~vtkPVPostFilter () override
int FillInputPortInformation (int port, vtkInformation *info) override
int RequestDataObject (vtkInformation *, vtkInformationVector **, vtkInformationVector *) override
int RequestData (vtkInformation *, vtkInformationVector **, vtkInformationVector *) override
int DoAnyNeededConversions (vtkDataObject *output)
int DoAnyNeededConversions (vtkDataSet *dataset)
int DoAnyNeededConversions (vtkDataSet *output, const char *requested_name, int fieldAssociation, const char *demangled_name, const char *demagled_component_name)
void CellDataToPointData (vtkDataSet *output, const char *name)
void PointDataToCellData (vtkDataSet *output, const char *name)
int ExtractComponent (vtkDataSetAttributes *dsa, const char *requested_name, const char *demangled_name, const char *demagled_component_name)
Detailed Description
Definition at line 15 of file vtkPVPostFilter.h.
Constructor & Destructor Documentation
vtkPVPostFilter()
vtkPVPostFilter::vtkPVPostFilter () protected
Definition at line 127 of file vtkPVPostFilter.cxx.
References vtkPVPostFilterExecutive::New().
~vtkPVPostFilter()
vtkPVPostFilter::~vtkPVPostFilter () override protected
Definition at line 138 of file vtkPVPostFilter.cxx.
Member Function Documentation
CellDataToPointData()
void vtkPVPostFilter::CellDataToPointData (vtkDataSet * output, const char * name) protected
Definition at line 385 of file vtkPVPostFilter.cxx.
References name.
Referenced by DoAnyNeededConversions().
CreateDefaultExecutive()
vtkExecutive * vtkPVPostFilter::CreateDefaultExecutive () override
We need to override this method because the composite data pipeline is not what we want. Instead we need the PVCompositeDataPipeline so that we can figure out what we conversion(s) we need to do
Definition at line 143 of file vtkPVPostFilter.cxx.
References vtkPVPostFilterExecutive::New().
DefaultComponentName()
std::string vtkPVPostFilter::DefaultComponentName (int componentNumber, int componentCount) static
Definition at line 149 of file vtkPVPostFilter.cxx.
Referenced by ExtractComponent().
DoAnyNeededConversions() [1/3]
int vtkPVPostFilter::DoAnyNeededConversions (vtkDataObject * output) protected
Definition at line 256 of file vtkPVPostFilter.cxx.
Referenced by DoAnyNeededConversions(), and RequestData().
DoAnyNeededConversions() [2/3]
int vtkPVPostFilter::DoAnyNeededConversions (vtkDataSet * dataset) protected
Definition at line 284 of file vtkPVPostFilter.cxx.
References DoAnyNeededConversions(), name, and vtkPVPostFilterExecutive::POST_ARRAYS_TO_PROCESS().
DoAnyNeededConversions() [3/3]
int vtkPVPostFilter::DoAnyNeededConversions (vtkDataSet * output, const char * requested_name, int fieldAssociation, const char * demangled_name, const char * demagled_component_name) protected
Definition at line 306 of file vtkPVPostFilter.cxx.
References CellDataToPointData(), ExtractComponent(), NULL, and PointDataToCellData().
ExtractComponent()
int vtkPVPostFilter::ExtractComponent (vtkDataSetAttributes * dsa, const char * requested_name, const char * demangled_name, const char * demagled_component_name) protected
Definition at line 478 of file vtkPVPostFilter.cxx.
References DefaultComponentName(), and NULL.
Referenced by DoAnyNeededConversions().
FillInputPortInformation()
int vtkPVPostFilter::FillInputPortInformation (int port, vtkInformation * info) override protected
Definition at line 179 of file vtkPVPostFilter.cxx.
New()
static vtkPVPostFilter* vtkPVPostFilter::New () static
PointDataToCellData()
void vtkPVPostFilter::PointDataToCellData (vtkDataSet * output, const char * name) protected
Definition at line 407 of file vtkPVPostFilter.cxx.
References name.
Referenced by DoAnyNeededConversions().
PrintSelf()
void vtkPVPostFilter::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 568 of file vtkPVPostFilter.cxx.
RequestData()
int vtkPVPostFilter::RequestData (vtkInformation * , vtkInformationVector ** inputVector, vtkInformationVector * outputVector) override protected
Definition at line 215 of file vtkPVPostFilter.cxx.
References DoAnyNeededConversions(), and vtkPVPostFilterExecutive::POST_ARRAYS_TO_PROCESS().
RequestDataObject()
int vtkPVPostFilter::RequestDataObject (vtkInformation * , vtkInformationVector ** inputVector, vtkInformationVector * outputVector) override protected
Definition at line 186 of file vtkPVPostFilter.cxx.
vtkTypeMacro()
vtkPVPostFilter::vtkTypeMacro (vtkPVPostFilter , vtkDataObjectAlgorithm)
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkPVPostFilter.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkPVPostFilter.cxx