ACloudViewer: cloudViewer::NormalDistribution Class Reference
cloudViewer::NormalDistribution Class Reference
The Normal/Gaussian statistical distribution.
#include <NormalDistribution.h>
Public Member Functions
NormalDistribution ()
NormalDistribution constructor.
NormalDistribution (ScalarType _mu, ScalarType _sigma2)
NormalDistribution constructor.
bool computeParameters (const ScalarContainer &values) override
Computes the distribution parameters from a set of values.
double computeP (ScalarType x) const override
Computes the probability of x.
double computePfromZero (ScalarType x) const override
Computes the cumulative probability between 0 and x.
double computeP (ScalarType x1, ScalarType x2) const override
Computes the cumulative probability between x1 and x2.
double computeChi2Dist (const GenericCloud *Yk, unsigned numberOfClasses, int *histo=nullptr) override
Computes the Chi2 distance (related to the Chi2 Test)
const char * getName () const override
Returns distribution name.
bool getParameters (ScalarType &_mu, ScalarType &_sigma2) const
Returns the distribution parameters.
bool setParameters (ScalarType _mu, ScalarType _sigma2)
Sets the distribution parameters.
ScalarType getMu () const
Returns the distribution mean.
ScalarType getSigma2 () const
Returns the distribution variance.
bool computeParameters (const GenericCloud *cloud)
bool computeRobustParameters (const ScalarContainer &values, double nSigma)
Public Member Functions inherited from cloudViewer::GenericDistribution
GenericDistribution ()
Default constructor.
virtual ~GenericDistribution ()=default
Default destructor.
virtual bool isValid () const
Indicates if the distribution parameters are valid.
Protected Member Functions
virtual bool setChi2ClassesPositions (unsigned numberOfClasses)
Compute each Chi2 class limits.
Protected Member Functions inherited from cloudViewer::GenericDistribution
void setValid (bool state)
Sets distribution current validity.
Protected Attributes
ScalarType m_mu
Mean.
ScalarType m_sigma2
Variance.
double m_qFactor
Exponential quotient.
double m_normFactor
Normalization factor.
std::vector< ScalarType > m_chi2ClassesPositions
Chi2 classes limits.
std::vector< ScalarType > m_Pi
Structure used during the Chi2 distance computation.
Protected Attributes inherited from cloudViewer::GenericDistribution
bool m_isValid
Whether the distribution is in a valid state or not.
Additional Inherited Members
Public Types inherited from cloudViewer::GenericDistribution
using ScalarContainer = std::vector< ScalarType >
Scalar values container.
Detailed Description
The Normal/Gaussian statistical distribution.
Implements the GenericDistribution interface.
Definition at line 18 of file NormalDistribution.h.
Constructor & Destructor Documentation
NormalDistribution() [1/2]
NormalDistribution::NormalDistribution ()
NormalDistribution constructor.
Definition at line 24 of file NormalDistribution.cpp.
NormalDistribution() [2/2]
NormalDistribution::NormalDistribution (ScalarType _mu, ScalarType _sigma2)
NormalDistribution constructor.
Distrubtion parameters can be directly set during object construction.
Parameters
_mu the normal distribution mean
_sigma2 the normal distribution variance
Definition at line 31 of file NormalDistribution.cpp.
References setParameters().
Member Function Documentation
computeChi2Dist()
double NormalDistribution::computeChi2Dist (const GenericCloud * Yk, unsigned numberOfClasses, int * histo = nullptr) override virtual
Computes the Chi2 distance (related to the Chi2 Test)
Computes the Chi2 distance from a group of point, accordingly to a certain number of classes (see Chi2 test theory for more information). The result of projecting each point (or more precisely each scalar value associated to each point) in the different classes can be stored in an array (of the same size as the number of classes). To do so, such an array (already allocated in memory) should be passed as an argument. Warning: be sure to activate an OUTPUT scalar field on the input cloud
Parameters
Yk a group of points
numberOfClasses the number of classes for the Chi2 Test
histo an array to store the values projection result (optional)
Returns
the Chi2 distance (or -1.0 if an error occurred)
Implements cloudViewer::GenericDistribution.
Definition at line 164 of file NormalDistribution.cpp.
References cloudViewer::ScalarFieldTools::countScalarFieldValidValues(), cloudViewer::GenericCloud::getPointScalarValue(), m_chi2ClassesPositions, m_Pi, setChi2ClassesPositions(), cloudViewer::GenericCloud::size(), and cloudViewer::ScalarField::ValidValue().
computeP() [1/2]
double NormalDistribution::computeP (ScalarType x) const override virtual
Computes the probability of x.
Parameters
x the variable
Returns
the probabilty
Implements cloudViewer::GenericDistribution.
Definition at line 64 of file NormalDistribution.cpp.
References m_mu, m_normFactor, m_qFactor, and x.
computeP() [2/2]
double NormalDistribution::computeP (ScalarType x1, ScalarType x2) const override virtual
Computes the cumulative probability between x1 and x2.
x1 should be lower than x2
Parameters
x1 the lower boundary
x2 the upper boundary
Returns
the cumulative probabilty
Implements cloudViewer::GenericDistribution.
Definition at line 69 of file NormalDistribution.cpp.
References cloudViewer::ErrorFunction::erf(), m_mu, and m_sigma2.
computeParameters() [1/2]
bool NormalDistribution::computeParameters (const GenericCloud * cloud)
Computes the distribution parameters from a point cloud (with scalar values)
Definition at line 82 of file NormalDistribution.cpp.
References cloudViewer::GenericCloud::getPointScalarValue(), setParameters(), cloudViewer::GenericDistribution::setValid(), cloudViewer::GenericCloud::size(), and cloudViewer::ScalarField::ValidValue().
computeParameters() [2/2]
bool NormalDistribution::computeParameters (const ScalarContainer & values) override virtual
Computes the distribution parameters from a set of values.
Parameters
values a set of scalar values
Returns
true (if the computation succeeded) or false (if not)
Implements cloudViewer::GenericDistribution.
Definition at line 109 of file NormalDistribution.cpp.
References setParameters(), cloudViewer::GenericDistribution::setValid(), and cloudViewer::ScalarField::ValidValue().
Referenced by computeRobustParameters(), define_NormalDistribution(), and cloudViewer::ICPRegistrationTools::Register().
computePfromZero()
double NormalDistribution::computePfromZero (ScalarType x) const override virtual
Computes the cumulative probability between 0 and x.
Parameters
x the upper boundary
Returns
the cumulative probabilty
Implements cloudViewer::GenericDistribution.
Definition at line 76 of file NormalDistribution.cpp.
References cloudViewer::ErrorFunction::erf(), m_mu, m_sigma2, and x.
Referenced by setChi2ClassesPositions().
computeRobustParameters()
bool NormalDistribution::computeRobustParameters (const ScalarContainer & values, double nSigma)
Computes robust parameters for the distribution from an array of scalar values Specific method to compute the parameters directly from an array (vector) of scalar values, without associated points. After a first pass, only the values close enough to the mean (in terms of nSigma times the initial variance) are kept to make a second and more robust evaluation of the parameters.
Parameters
values the scalar values
nSigma the values filtering interval size ([mu -nSigma * stddev : mu + nSigma * stddev])
Returns
the validity of the computed parameters
Definition at line 135 of file NormalDistribution.cpp.
References computeParameters(), m_mu, m_sigma2, and setParameters().
Referenced by define_NormalDistribution().
getMu()
ScalarType cloudViewer::NormalDistribution::getMu () const inline
Returns the distribution mean.
Definition at line 56 of file NormalDistribution.h.
Referenced by define_NormalDistribution().
getName()
const char* cloudViewer::NormalDistribution::getName () const inline override virtual
Returns distribution name.
Implements cloudViewer::GenericDistribution.
Definition at line 39 of file NormalDistribution.h.
getParameters()
bool NormalDistribution::getParameters (ScalarType & _mu, ScalarType & _sigma2) const
Returns the distribution parameters.
Parameters
_mu a field to transmit the distribution mean
_sigma2 a field to transmit the distribution variance return the parameters validity
Definition at line 35 of file NormalDistribution.cpp.
References cloudViewer::GenericDistribution::isValid(), m_mu, and m_sigma2.
Referenced by cloudViewer::ICPRegistrationTools::Register(), and cloudViewer::StatisticalTestingTools::testCloudWithStatisticalModel().
getSigma2()
ScalarType cloudViewer::NormalDistribution::getSigma2 () const inline
Returns the distribution variance.
Definition at line 59 of file NormalDistribution.h.
Referenced by define_NormalDistribution().
setChi2ClassesPositions()
bool NormalDistribution::setChi2ClassesPositions (unsigned numberOfClasses) protected virtual
Compute each Chi2 class limits.
This method is used (internally) to accelerate the Chi2 distance computation.
Parameters
numberOfClasses the number of classes that will be used for Chi2 distance computation
Returns
success
Definition at line 221 of file NormalDistribution.cpp.
References computePfromZero(), cloudViewer::GenericDistribution::isValid(), m_chi2ClassesPositions, m_mu, m_Pi, m_sigma2, x, and y.
Referenced by computeChi2Dist().
setParameters()
bool NormalDistribution::setParameters (ScalarType _mu, ScalarType _sigma2)
Sets the distribution parameters.
Parameters
_mu the distribution mean
_sigma2 the distribution variance return the parameters validity
Definition at line 43 of file NormalDistribution.cpp.
References cloudViewer::GenericDistribution::isValid(), m_chi2ClassesPositions, m_mu, m_normFactor, M_PI, m_Pi, m_qFactor, m_sigma2, and cloudViewer::GenericDistribution::setValid().
Referenced by computeParameters(), computeRobustParameters(), define_NormalDistribution(), NormalDistribution(), CommandStatTest::process(), and ccEntityAction::statisticalTest().
Member Data Documentation
m_chi2ClassesPositions
std::vector<ScalarType> cloudViewer::NormalDistribution::m_chi2ClassesPositions protected
Chi2 classes limits.
Used internally. Stores both limits for each class in a vector (min_class_1, max_class_1, min_class_2, max_class_2, etc.).
Definition at line 98 of file NormalDistribution.h.
Referenced by computeChi2Dist(), setChi2ClassesPositions(), and setParameters().
m_mu
ScalarType cloudViewer::NormalDistribution::m_mu protected
Mean.
Definition at line 86 of file NormalDistribution.h.
Referenced by computeP(), computePfromZero(), computeRobustParameters(), getParameters(), setChi2ClassesPositions(), and setParameters().
m_normFactor
double cloudViewer::NormalDistribution::m_normFactor protected
Normalization factor.
Definition at line 92 of file NormalDistribution.h.
Referenced by computeP(), and setParameters().
m_Pi
std::vector<ScalarType> cloudViewer::NormalDistribution::m_Pi protected
Structure used during the Chi2 distance computation.
Definition at line 101 of file NormalDistribution.h.
Referenced by computeChi2Dist(), setChi2ClassesPositions(), and setParameters().
m_qFactor
double cloudViewer::NormalDistribution::m_qFactor protected
Exponential quotient.
Definition at line 90 of file NormalDistribution.h.
Referenced by computeP(), and setParameters().
m_sigma2
ScalarType cloudViewer::NormalDistribution::m_sigma2 protected
Variance.
Definition at line 88 of file NormalDistribution.h.
Referenced by computeP(), computePfromZero(), computeRobustParameters(), getParameters(), setChi2ClassesPositions(), and setParameters().
The documentation for this class was generated from the following files:
/root/ACloudViewer/core/include/NormalDistribution.h
/root/ACloudViewer/core/src/NormalDistribution.cpp