ACloudViewer: Square Class Reference
Square Class Reference
#include <MarchingCubes.h>
Static Public Member Functions
static int CornerIndex (int x, int y)
static int AntipodalCornerIndex (int idx)
static void FactorCornerIndex (int idx, int &x, int &y)
static int EdgeIndex (int orientation, int i)
static void FactorEdgeIndex (int idx, int &orientation, int &i)
static int ReflectCornerIndex (int idx, int edgeIndex)
static int ReflectEdgeIndex (int idx, int edgeIndex)
static void EdgeCorners (int idx, int &c1, int &c2)
Static Public Attributes
static const unsigned int CORNERS =4
static const unsigned int EDGES =4
static const unsigned int FACES =1
Detailed Description
Definition at line 36 of file MarchingCubes.h.
Member Function Documentation
AntipodalCornerIndex()
int Square::AntipodalCornerIndex (int idx) static
Definition at line 34 of file MarchingCubes.cpp.
References CornerIndex(), and FactorCornerIndex().
CornerIndex()
int Square::CornerIndex (int x, int y) static
Definition at line 39 of file MarchingCubes.cpp.
Referenced by AntipodalCornerIndex(), EdgeCorners(), MarchingSquares::GetIndex(), and ReflectCornerIndex().
EdgeCorners()
void Square::EdgeCorners (int idx, int & c1, int & c2) static
Definition at line 66 of file MarchingCubes.cpp.
References CornerIndex(), and FactorEdgeIndex().
Referenced by MarchingSquares::HasEdgeRoots().
EdgeIndex()
int Square::EdgeIndex (int orientation, int i) static
Definition at line 41 of file MarchingCubes.cpp.
Referenced by ReflectEdgeIndex().
FactorCornerIndex()
void Square::FactorCornerIndex (int idx, int & x, int & y) static
Definition at line 40 of file MarchingCubes.cpp.
Referenced by AntipodalCornerIndex(), and ReflectCornerIndex().
FactorEdgeIndex()
void Square::FactorEdgeIndex (int idx, int & orientation, int & i) static
Definition at line 54 of file MarchingCubes.cpp.
Referenced by EdgeCorners(), and ReflectEdgeIndex().
ReflectCornerIndex()
int Square::ReflectCornerIndex (int idx, int edgeIndex) static
Definition at line 87 of file MarchingCubes.cpp.
References CornerIndex(), and FactorCornerIndex().
ReflectEdgeIndex()
int Square::ReflectEdgeIndex (int idx, int edgeIndex) static
Definition at line 80 of file MarchingCubes.cpp.
References EdgeIndex(), and FactorEdgeIndex().
Member Data Documentation
CORNERS
const unsigned int Square::CORNERS =4 static
Definition at line 39 of file MarchingCubes.h.
Referenced by MarchingSquares::GetIndex().
EDGES
const unsigned int Square::EDGES =4 static
Definition at line 39 of file MarchingCubes.h.
FACES
const unsigned int Square::FACES =1 static
Definition at line 39 of file MarchingCubes.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/MarchingCubes.h
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/MarchingCubes.cpp