ACloudViewer: ccAlignDlg Class Reference
ccAlignDlg Class Reference
Rough registration dialog.
#include <ecvAlignDlg.h>
Public Types
enum CC_SAMPLING_METHOD { NONE = 0 , RANDOM , SPACE , OCTREE }
Public Member Functions
ccAlignDlg (ccGenericPointCloud *data, ccGenericPointCloud *model, QWidget *parent=nullptr)
virtual ~ccAlignDlg ()
unsigned getNbTries ()
double getOverlap ()
double getDelta ()
ccGenericPointCloud * getModelObject ()
ccGenericPointCloud * getDataObject ()
CC_SAMPLING_METHOD getSamplingMethod ()
bool isNumberOfCandidatesLimited ()
unsigned getMaxNumberOfCandidates ()
cloudViewer::ReferenceCloud * getSampledModel ()
cloudViewer::ReferenceCloud * getSampledData ()
Protected Slots
void swapModelAndData ()
void modelSliderReleased ()
void dataSliderReleased ()
void modelSamplingRateChanged (double value)
void dataSamplingRateChanged (double value)
void estimateDelta ()
void changeSamplingMethod (int index)
void toggleNbMaxCandidates (bool activ)
Protected Member Functions
void setColorsAndLabels ()
Protected Attributes
ccGenericPointCloud * modelObject
'Model' cloud (static)
ccGenericPointCloud * dataObject
'Data' cloud (static)
Ui::AlignDialog * m_ui
Detailed Description
Rough registration dialog.
Definition at line 25 of file ecvAlignDlg.h.
Member Enumeration Documentation
CC_SAMPLING_METHOD
enum ccAlignDlg::CC_SAMPLING_METHOD
Enumerator
NONE
RANDOM
SPACE
OCTREE
Definition at line 29 of file ecvAlignDlg.h.
Constructor & Destructor Documentation
ccAlignDlg()
ccAlignDlg::ccAlignDlg (ccGenericPointCloud * data, ccGenericPointCloud * model, QWidget * parent = nullptr)
Definition at line 28 of file ecvAlignDlg.cpp.
References changeSamplingMethod(), dataObject, dataSamplingRateChanged(), dataSliderReleased(), estimateDelta(), m_ui, modelObject, modelSamplingRateChanged(), modelSliderReleased(), NONE, ecvColor::red(), ccQtHelpers::SetButtonColor(), setColorsAndLabels(), swapModelAndData(), toggleNbMaxCandidates(), and ecvColor::yellow().
~ccAlignDlg()
ccAlignDlg::~ccAlignDlg () virtual
Definition at line 74 of file ecvAlignDlg.cpp.
References dataObject, ccDrawableObject::enableTempColor(), and modelObject.
Member Function Documentation
changeSamplingMethod
void ccAlignDlg::changeSamplingMethod (int index) protected slot
Definition at line 375 of file ecvAlignDlg.cpp.
References ccGenericPointCloud::computeOctree(), dataObject, dataSliderReleased(), dist(), cloudViewer::GenericCloud::getBoundingBox(), ccGenericPointCloud::getOctree(), m_ui, cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, modelObject, modelSliderReleased(), NONE, OCTREE, RANDOM, cloudViewer::GenericCloud::size(), and SPACE.
Referenced by ccAlignDlg(), and swapModelAndData().
dataSamplingRateChanged
void ccAlignDlg::dataSamplingRateChanged (double value) protected slot
Definition at line 286 of file ecvAlignDlg.cpp.
References dataObject, getSampledData(), getSamplingMethod(), m_ui, OCTREE, RANDOM, cloudViewer::GenericCloud::size(), cloudViewer::ReferenceCloud::size(), and SPACE.
Referenced by ccAlignDlg(), and dataSliderReleased().
dataSliderReleased
void ccAlignDlg::dataSliderReleased () protected slot
Definition at line 231 of file ecvAlignDlg.cpp.
References dataSamplingRateChanged(), getSamplingMethod(), m_ui, and SPACE.
Referenced by ccAlignDlg(), and changeSamplingMethod().
estimateDelta
void ccAlignDlg::estimateDelta () protected slot
Definition at line 332 of file ecvAlignDlg.cpp.
References cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::GeometricalAnalysisTools::ComputeLocalDensityApprox(), count, cloudViewer::GeometricalAnalysisTools::DENSITY_KNN, cloudViewer::PointCloudTpl< T >::enableScalarField(), CVLog::Error(), cloudViewer::ReferenceCloud::getPoint(), cloudViewer::PointCloudTpl< T >::getPointScalarValue(), getSampledData(), m_ui, cloudViewer::GeometricalAnalysisTools::NoError, cloudViewer::PointCloudTpl< T >::reserve(), cloudViewer::PointCloudTpl< T >::size(), and cloudViewer::ReferenceCloud::size().
Referenced by ccAlignDlg().
getDataObject()
ccGenericPointCloud * ccAlignDlg::getDataObject ()
Definition at line 87 of file ecvAlignDlg.cpp.
References dataObject.
getDelta()
double ccAlignDlg::getDelta ()
Definition at line 83 of file ecvAlignDlg.cpp.
References m_ui.
getMaxNumberOfCandidates()
unsigned ccAlignDlg::getMaxNumberOfCandidates ()
Definition at line 97 of file ecvAlignDlg.cpp.
References m_ui.
getModelObject()
ccGenericPointCloud * ccAlignDlg::getModelObject ()
Definition at line 85 of file ecvAlignDlg.cpp.
References modelObject.
getNbTries()
unsigned ccAlignDlg::getNbTries ()
Definition at line 79 of file ecvAlignDlg.cpp.
References m_ui.
getOverlap()
double ccAlignDlg::getOverlap ()
Definition at line 81 of file ecvAlignDlg.cpp.
References m_ui.
getSampledData()
cloudViewer::ReferenceCloud * ccAlignDlg::getSampledData ()
Definition at line 152 of file ecvAlignDlg.cpp.
References cloudViewer::ReferenceCloud::addPointIndex(), dataObject, CVLog::Error(), ccGenericPointCloud::getOctree(), getSamplingMethod(), m_ui, OCTREE, RANDOM, cloudViewer::CloudSamplingTools::resampleCloudSpatially(), cloudViewer::GenericCloud::size(), SPACE, cloudViewer::CloudSamplingTools::subsampleCloudRandomly(), and cloudViewer::CloudSamplingTools::subsampleCloudWithOctreeAtLevel().
Referenced by dataSamplingRateChanged(), and estimateDelta().
getSampledModel()
cloudViewer::ReferenceCloud * ccAlignDlg::getSampledModel ()
Definition at line 101 of file ecvAlignDlg.cpp.
References cloudViewer::ReferenceCloud::addPointIndex(), CVLog::Error(), ccGenericPointCloud::getOctree(), getSamplingMethod(), m_ui, modelObject, OCTREE, RANDOM, cloudViewer::CloudSamplingTools::resampleCloudSpatially(), cloudViewer::GenericCloud::size(), SPACE, cloudViewer::CloudSamplingTools::subsampleCloudRandomly(), and cloudViewer::CloudSamplingTools::subsampleCloudWithOctreeAtLevel().
Referenced by modelSamplingRateChanged().
getSamplingMethod()
ccAlignDlg::CC_SAMPLING_METHOD ccAlignDlg::getSamplingMethod ()
Definition at line 89 of file ecvAlignDlg.cpp.
References m_ui.
Referenced by dataSamplingRateChanged(), dataSliderReleased(), getSampledData(), getSampledModel(), modelSamplingRateChanged(), and modelSliderReleased().
isNumberOfCandidatesLimited()
bool ccAlignDlg::isNumberOfCandidatesLimited ()
Definition at line 93 of file ecvAlignDlg.cpp.
References m_ui.
modelSamplingRateChanged
void ccAlignDlg::modelSamplingRateChanged (double value) protected slot
Definition at line 240 of file ecvAlignDlg.cpp.
References getSampledModel(), getSamplingMethod(), m_ui, modelObject, OCTREE, RANDOM, cloudViewer::GenericCloud::size(), cloudViewer::ReferenceCloud::size(), and SPACE.
Referenced by ccAlignDlg(), and modelSliderReleased().
modelSliderReleased
void ccAlignDlg::modelSliderReleased () protected slot
Definition at line 222 of file ecvAlignDlg.cpp.
References getSamplingMethod(), m_ui, modelSamplingRateChanged(), and SPACE.
Referenced by ccAlignDlg(), and changeSamplingMethod().
setColorsAndLabels()
void ccAlignDlg::setColorsAndLabels () protected
Definition at line 201 of file ecvAlignDlg.cpp.
References dataObject, ccObject::getName(), m_ui, modelObject, ecvColor::red(), ecvDisplayTools::RedrawDisplay(), ccDrawableObject::setTempColor(), ccDrawableObject::setVisible(), and ecvColor::yellow().
Referenced by ccAlignDlg(), and swapModelAndData().
swapModelAndData
void ccAlignDlg::swapModelAndData () protected slot
Definition at line 216 of file ecvAlignDlg.cpp.
References changeSamplingMethod(), dataObject, m_ui, modelObject, setColorsAndLabels(), and std::swap().
Referenced by ccAlignDlg().
toggleNbMaxCandidates
void ccAlignDlg::toggleNbMaxCandidates (bool activ) protected slot
Definition at line 484 of file ecvAlignDlg.cpp.
References m_ui.
Referenced by ccAlignDlg().
Member Data Documentation
dataObject
ccGenericPointCloud* ccAlignDlg::dataObject protected
'Data' cloud (static)
Definition at line 62 of file ecvAlignDlg.h.
Referenced by ccAlignDlg(), changeSamplingMethod(), dataSamplingRateChanged(), getDataObject(), getSampledData(), setColorsAndLabels(), swapModelAndData(), and ~ccAlignDlg().
m_ui
Ui::AlignDialog* ccAlignDlg::m_ui protected
Definition at line 66 of file ecvAlignDlg.h.
Referenced by ccAlignDlg(), changeSamplingMethod(), dataSamplingRateChanged(), dataSliderReleased(), estimateDelta(), getDelta(), getMaxNumberOfCandidates(), getNbTries(), getOverlap(), getSampledData(), getSampledModel(), getSamplingMethod(), isNumberOfCandidatesLimited(), modelSamplingRateChanged(), modelSliderReleased(), setColorsAndLabels(), swapModelAndData(), and toggleNbMaxCandidates().
modelObject
ccGenericPointCloud* ccAlignDlg::modelObject protected
'Model' cloud (static)
Definition at line 59 of file ecvAlignDlg.h.
Referenced by ccAlignDlg(), changeSamplingMethod(), getModelObject(), getSampledModel(), modelSamplingRateChanged(), setColorsAndLabels(), swapModelAndData(), and ~ccAlignDlg().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvAlignDlg.h
/root/ACloudViewer/app/ecvAlignDlg.cpp