ACloudViewer: ccColorGradientDlg Class Reference
ccColorGradientDlg Class Reference
Dialog to define a color gradient (default, with 2 colors, banding, etc.)
#include <ecvColorGradientDlg.h>
Public Types
enum GradientType { Default , TwoColors , Banding }
Gradient types.
Public Member Functions
ccColorGradientDlg (QWidget *parent)
Default constructor.
GradientType getType () const
Returns selected gradient type.
void setType (GradientType type)
Sets the currently activated type.
void getColors (QColor &first, QColor &second) const
Returns the two colors of the gradient ('TwoColors' mode)
double getBandingFrequency () const
Returns the frequency of the gradient ('Banding' mode)
unsigned char getDimension () const
Returns the ramp dimension.
Protected Slots
void changeFirstColor ()
void changeSecondColor ()
Detailed Description
Dialog to define a color gradient (default, with 2 colors, banding, etc.)
Definition at line 16 of file ecvColorGradientDlg.h.
Member Enumeration Documentation
GradientType
enum ccColorGradientDlg::GradientType
Gradient types.
Enumerator
Default
TwoColors
Banding
Definition at line 24 of file ecvColorGradientDlg.h.
Constructor & Destructor Documentation
ccColorGradientDlg()
ccColorGradientDlg::ccColorGradientDlg (QWidget * parent) explicit
Default constructor.
Definition at line 26 of file ecvColorGradientDlg.cpp.
References changeFirstColor(), changeSecondColor(), s_firstColor(), s_lastDimIndex, s_lastFreq, s_lastType(), s_secondColor(), ccQtHelpers::SetButtonColor(), and setType().
Member Function Documentation
changeFirstColor
void ccColorGradientDlg::changeFirstColor () protected slot
Definition at line 90 of file ecvColorGradientDlg.cpp.
References s_firstColor(), and ccQtHelpers::SetButtonColor().
Referenced by ccColorGradientDlg().
changeSecondColor
void ccColorGradientDlg::changeSecondColor () protected slot
Definition at line 98 of file ecvColorGradientDlg.cpp.
References s_secondColor(), and ccQtHelpers::SetButtonColor().
Referenced by ccColorGradientDlg().
getBandingFrequency()
double ccColorGradientDlg::getBandingFrequency () const
Returns the frequency of the gradient ('Banding' mode)
Definition at line 83 of file ecvColorGradientDlg.cpp.
References s_lastFreq.
Referenced by ccEntityAction::setColorGradient().
getColors()
void ccColorGradientDlg::getColors (QColor & first, QColor & second) const
Returns the two colors of the gradient ('TwoColors' mode)
Definition at line 77 of file ecvColorGradientDlg.cpp.
References s_firstColor(), and s_secondColor().
Referenced by ccEntityAction::setColorGradient().
getDimension()
unsigned char ccColorGradientDlg::getDimension () const
Returns the ramp dimension.
Definition at line 43 of file ecvColorGradientDlg.cpp.
References s_lastDimIndex.
Referenced by ccEntityAction::setColorGradient().
getType()
ccColorGradientDlg::GradientType ccColorGradientDlg::getType () const
Returns selected gradient type.
Definition at line 64 of file ecvColorGradientDlg.cpp.
References Banding, Default, s_lastType(), and TwoColors.
Referenced by ccEntityAction::setColorGradient().
setType()
void ccColorGradientDlg::setType (ccColorGradientDlg::GradientType type)
Sets the currently activated type.
Definition at line 48 of file ecvColorGradientDlg.cpp.
References Banding, Default, TwoColors, and type.
Referenced by ccColorGradientDlg().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvColorGradientDlg.h
/root/ACloudViewer/app/ecvColorGradientDlg.cpp