ACloudViewer: vtk2cc Class Reference
vtk2cc Class Reference
CC to PCL cloud converter.
#include <vtk2cc.h>
Static Public Member Functions
static ccPointCloud * ConvertToPointCloud (vtkPolyData *polydata, bool silent=false)
static ccMesh * ConvertToMesh (vtkPolyData *polydata, bool silent=false)
static ccPolyline * ConvertToPolyline (vtkPolyData *polydata, bool silent=false)
static ccPolyline * ConvertToPolyline (ccPointCloud *vertices)
static std::vector< ccHObject * > ConvertToMultiPolylines (vtkPolyData *polydata, QString baseName="Slice", const ecvColor::Rgb &color=ecvColor::green)
Detailed Description
CC to PCL cloud converter.
Definition at line 23 of file vtk2cc.h.
Member Function Documentation
ConvertToMesh()
ccMesh * vtk2cc::ConvertToMesh (vtkPolyData * polydata, bool silent = false) static
Definition at line 290 of file vtk2cc.cpp.
References ccHObject::addChild(), ccMesh::addTriangle(), ConvertToPointCloud(), ccMesh::getTriNormsTable(), normals, ccMesh::reserve(), ccObject::setEnabled(), ccObject::setLocked(), ccObject::setName(), ccMesh::shrinkToFit(), ccPointCloud::shrinkToFit(), and CVLog::Warning().
Referenced by cvGenericFilter::getOutput().
ConvertToMultiPolylines()
ccHObject::Container vtk2cc::ConvertToMultiPolylines (vtkPolyData * polydata, QString baseName = "Slice", const ecvColor::Rgb & color = ecvColor::green) static
Definition at line 460 of file vtk2cc.cpp.
References cloudViewer::PointCloudTpl< T >::addPoint(), color, ConvertToPolyline(), CVLog::Error(), Vector3Tpl< PointCoordinateType >::fromArray(), ccPointCloud::hasNormals(), ccPointCloud::hasScalarFields(), ecvColor::red(), ccPointCloud::reserve(), ccPolyline::set2DMode(), ccPointCloud::setCurrentDisplayedScalarField(), ccObject::setEnabled(), ccObject::setName(), ccGenericPointCloud::setPointSize(), ccDrawableObject::setTempColor(), ccDrawableObject::showColors(), ccDrawableObject::showNormals(), ccDrawableObject::showSF(), cloudViewer::PointCloudTpl< T >::size(), and cloudViewer::ReferenceCloud::size().
Referenced by cvIsoSurfaceFilter::getOutput(), and cvSliceFilter::getOutput().
ConvertToPointCloud()
ccPointCloud * vtk2cc::ConvertToPointCloud (vtkPolyData * polydata, bool silent = false) static
Definition at line 53 of file vtk2cc.cpp.
References ccPointCloud::addNorm(), ccPointCloud::addRGBColor(), ccPointCloud::addScalarField(), color, colors, ccScalarField::computeMinAndMax(), Vector3Tpl< PointCoordinateType >::fromArray(), name, normal, normals, CCShareable::release(), cloudViewer::ScalarField::reserveSafe(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveTheRGBTable(), ccPointCloud::resize(), cloudViewer::ScalarField::resizeSafe(), ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::PointCloudTpl< T >::setPoint(), cloudViewer::ScalarField::setValue(), ccDrawableObject::showColors(), ccDrawableObject::showNormals(), ccDrawableObject::showSF(), and CVLog::Warning().
Referenced by ConvertToMesh(), ConvertToPolyline(), and cvGenericFilter::getOutput().
ConvertToPolyline() [1/2]
ccPolyline * vtk2cc::ConvertToPolyline (ccPointCloud * vertices) static
Definition at line 412 of file vtk2cc.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), Vector3Tpl< PointCoordinateType >::fromArray(), cloudViewer::PointCloudTpl< T >::getPoint(), ecvColor::green(), ccObject::isKindOf(), cloudViewer::LessThanEpsilon(), CV_TYPES::POINT_CLOUD, cloudViewer::ReferenceCloud::reserve(), ccPolyline::set2DMode(), cloudViewer::Polyline::setClosed(), ccObject::setName(), ccDrawableObject::setTempColor(), ccDrawableObject::setVisible(), ccDrawableObject::showColors(), cloudViewer::PointCloudTpl< T >::size(), ccHObjectCaster::ToPointCloud(), and Tuple3Tpl< Type >::u.
ConvertToPolyline() [2/2]
ccPolyline * vtk2cc::ConvertToPolyline (vtkPolyData * polydata, bool silent = false) static
Definition at line 392 of file vtk2cc.cpp.
References ConvertToPointCloud(), CVLog::Error(), cloudViewer::PointCloudTpl< T >::size(), and CVLog::Warning().
Referenced by CurveFittingTool::CurveFitting::BsplineFitting(), ConvertToMultiPolylines(), and cvContourTool::getOutput().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Utils/vtk2cc.h
/root/ACloudViewer/libs/PCLEngine/Utils/vtk2cc.cpp