ACloudViewer: STLFilter Class Reference
STLFilter Class Reference
StereoLithography file I/O filter.
#include <STLFilter.h>
Public Member Functions
STLFilter ()
virtual CC_FILE_ERROR loadFile (const QString &filename, ccHObject &container, LoadParameters &parameters) override
Loads one or more entities from a file.
virtual bool canSave (CV_CLASS_ENUM type, bool &multiple, bool &exclusive) const override
Returns whether this I/O filter can save the specified type of entity.
virtual CC_FILE_ERROR saveToFile (ccHObject *entity, const QString &filename, const SaveParameters &parameters) override
Saves an entity (or a group of) to a file.
Public Member Functions inherited from FileIOFilter
virtual ~FileIOFilter ()=default
bool importSupported () const
Returns whether this I/O filter can import files.
bool exportSupported () const
Returns whether this I/O filter can export files.
const QStringList & getFileFilters (bool onImport) const
Returns the file filter(s) for this I/O filter.
QString getDefaultExtension () const
Returns the default file extension.
virtual void unregister ()
Called when the filter is unregistered.
Protected Member Functions
CC_FILE_ERROR saveToASCIIFile (ccGenericMesh *mesh, FILE *theFile, QWidget *parentWidget=0)
Custom save method.
CC_FILE_ERROR saveToBINFile (ccGenericMesh *mesh, FILE *theFile, QWidget *parentWidget=0)
CC_FILE_ERROR loadASCIIFile (QFile &fp, ccMesh *mesh, ccPointCloud *vertices, LoadParameters &parameters)
Custom load method for ASCII files.
CC_FILE_ERROR loadBinaryFile (QFile &fp, ccMesh *mesh, ccPointCloud *vertices, LoadParameters &parameters)
Custom load method for binary files.
Protected Member Functions inherited from FileIOFilter
FileIOFilter (const FilterInfo &info)
void setImportExtensions (const QStringList &extensions)
void setImportFileFilterStrings (const QStringList &filterStrings)
void setExportFileFilterStrings (const QStringList &filterStrings)
Additional Inherited Members
Public Types inherited from FileIOFilter
enum FilterFeature {
NoFeatures = 0x0000 , Import = 0x00001 , Export = 0x0002 , BuiltIn = 0x0004 ,
DynamicInfo = 0x0008
}
using Shared = QSharedPointer< FileIOFilter >
Shared type.
using FilterContainer = std::vector< FileIOFilter::Shared >
Type of a I/O filters container.
Static Public Member Functions inherited from FileIOFilter
static QStringList ImportFilterList ()
static ccHObject * LoadFromFile (const QString &filename, LoadParameters &parameters, Shared filter, CC_FILE_ERROR &result)
Loads one or more entities from a file with a known filter.
static ccHObject * LoadFromFile (const QString &filename, LoadParameters &parameters, CC_FILE_ERROR &result, const QString &fileFilter=QString())
Loads one or more entities from a file with known type.
static CC_FILE_ERROR SaveToFile (ccHObject *entities, const QString &filename, const SaveParameters &parameters, Shared filter)
static CC_FILE_ERROR SaveToFile (ccHObject *entities, const QString &filename, const SaveParameters &parameters, const QString &fileFilter)
static bool HandleGlobalShift (const CCVector3d &P, CCVector3d &Pshift, bool &preserveCoordinateShift, LoadParameters &loadParameters, bool useInputCoordinatesShiftIfPossible=false)
Shortcut to the ecvGlobalShiftManager mechanism specific for files.
static void DisplayErrorMessage (CC_FILE_ERROR err, const QString &action, const QString &filename)
Displays (to console) the message corresponding to a given error code.
static bool CheckForSpecialChars (const QString &filename)
Returns whether special characters are present in the input string.
static void ResetSesionCounter ()
static unsigned IncreaseSesionCounter ()
static void Register (Shared filter)
Registers a new filter.
static Shared GetFilter (const QString &fileFilter, bool onImport)
Returns the filter corresponding to the given 'file filter'.
static Shared FindBestFilterForExtension (const QString &ext)
Returns the best filter (presumably) to open a given file extension.
static const FilterContainer & GetFilters ()
Returns the set of all registered filters.
static void UnregisterAll ()
Unregisters all filters.
Static Protected Attributes inherited from FileIOFilter
static constexpr float DEFAULT_PRIORITY = 25.0f
Detailed Description
StereoLithography file I/O filter.
See http://www.ennex.com/~fabbers/StL.asp
Definition at line 19 of file STLFilter.h.
Constructor & Destructor Documentation
STLFilter()
STLFilter::STLFilter ()
Definition at line 35 of file STLFilter.cpp.
References FileIOFilter::Export, and FileIOFilter::Import.
Member Function Documentation
canSave()
bool STLFilter::canSave (CV_CLASS_ENUM type, bool & multiple, bool & exclusive) const override virtual
Returns whether this I/O filter can save the specified type of entity.
Parameters
type entity type
multiple whether the filter can save multiple instances of this entity at once
exclusive whether the filter can only save this type of entity if selected or if it can be mixed with other types
Returns
whether the entity type can be saved
Reimplemented from FileIOFilter.
Definition at line 41 of file STLFilter.cpp.
References CV_TYPES::MESH, and type.
loadASCIIFile()
CC_FILE_ERROR STLFilter::loadASCIIFile (QFile & fp, ccMesh * mesh, ccPointCloud * vertices, LoadParameters & parameters) protected
Custom load method for ASCII files.
Definition at line 372 of file STLFilter.cpp.
References cloudViewer::PointCloudTpl< T >::addPoint(), ccMesh::addTriangle(), ccMesh::addTriangleNormalIndexes(), cloudViewer::PointCloudTpl< T >::capacity(), ccMesh::capacity(), CC_FERR_MALFORMED_FILE, CC_FERR_NO_ERROR, CC_FERR_NOT_ENOUGH_MEMORY, CC_FERR_READING, Vector3Tpl< PointCoordinateType >::fromArray(), ccNormalVectors::GetNormIndex(), ccMesh::getTriNormsTable(), FileIOFilter::HandleGlobalShift(), name, normals, FileIOFilter::LoadParameters::parentWidget, ccMesh::removePerTriangleNormalIndexes(), ccMesh::reserve(), ccPointCloud::reserve(), ccMesh::reservePerTriangleNormalIndexes(), result, ccShiftedObject::setGlobalShift(), ccObject::setName(), ccMesh::setTriNormsTable(), QtCompat::SkipEmptyParts, Tuple3Tpl< Type >::u, CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by loadFile().
loadBinaryFile()
CC_FILE_ERROR STLFilter::loadBinaryFile (QFile & fp, ccMesh * mesh, ccPointCloud * vertices, LoadParameters & parameters) protected
Custom load method for binary files.
Definition at line 682 of file STLFilter.cpp.
References a, cloudViewer::PointCloudTpl< T >::addPoint(), ccMesh::addTriangle(), ccMesh::addTriangleNormalIndexes(), CC_FERR_NO_ERROR, CC_FERR_NOT_ENOUGH_MEMORY, CC_FERR_READING, Vector3Tpl< PointCoordinateType >::fromArray(), ccNormalVectors::GetNormIndex(), ccMesh::getTriNormsTable(), FileIOFilter::HandleGlobalShift(), normals, nProgress, cloudViewer::NormalizedProgress::oneStep(), FileIOFilter::LoadParameters::parentWidget, ccMesh::removePerTriangleNormalIndexes(), ccMesh::reserve(), ccPointCloud::reserve(), ccMesh::reservePerTriangleNormalIndexes(), ccShiftedObject::setGlobalShift(), ccObject::setName(), ccMesh::setTriNormsTable(), Tuple3Tpl< Type >::u, CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by loadFile().
loadFile()
CC_FILE_ERROR STLFilter::loadFile (const QString & filename, ccHObject & container, LoadParameters & parameters) override virtual
Loads one or more entities from a file.
This method must be implemented by children classes.
Parameters
filename file to load
container container to store loaded entities
parameters generic loading parameters
Returns
error
Reimplemented from FileIOFilter.
Definition at line 264 of file STLFilter.cpp.
References ccHObject::addChild(), CC_FERR_MALFORMED_FILE, CC_FERR_NO_ERROR, CC_FERR_READING, ccMesh::DefaultMergeDulicateVerticesLevel, filename, ccMesh::getAssociatedCloud(), ccMesh::getTriNormsTable(), loadASCIIFile(), loadBinaryFile(), ccMesh::mergeDuplicatedVertices(), name, normals, FileIOFilter::LoadParameters::parentWidget, CVLog::Print(), ccObject::setEnabled(), ccObject::setLocked(), ccObject::setName(), ccMesh::setTriNormsTable(), ccGenericMesh::showNormals(), ccMesh::shrinkToFit(), ccPointCloud::shrinkToFit(), cloudViewer::PointCloudTpl< T >::size(), ccMesh::size(), and CVLog::Warning().
saveToASCIIFile()
CC_FILE_ERROR STLFilter::saveToASCIIFile (ccGenericMesh * mesh, FILE * theFile, QWidget * parentWidget = 0) protected
Custom save method.
Definition at line 193 of file STLFilter.cpp.
References CC_FERR_CANCELED_BY_USER, CC_FERR_NO_ERROR, CC_FERR_WRITING, ccGenericMesh::getAssociatedCloud(), ccObject::getName(), cloudViewer::GenericIndexedMesh::getNextTriangleVertIndexes(), cloudViewer::GenericIndexedCloudPersist::getPointPersistentPtr(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, cloudViewer::NormalizedProgress::oneStep(), cloudViewer::GenericMesh::placeIteratorAtBeginning(), cloudViewer::GenericMesh::size(), ccShiftedObject::toGlobal3d(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by saveToFile().
saveToBINFile()
CC_FILE_ERROR STLFilter::saveToBINFile (ccGenericMesh * mesh, FILE * theFile, QWidget * parentWidget = 0) protected
Definition at line 96 of file STLFilter.cpp.
References CC_FERR_CANCELED_BY_USER, CC_FERR_NO_ERROR, CC_FERR_WRITING, Vector3Tpl< float >::fromArray(), ccGenericMesh::getAssociatedCloud(), ccObject::getName(), cloudViewer::GenericIndexedMesh::getNextTriangleVertIndexes(), cloudViewer::GenericIndexedCloudPersist::getPointPersistentPtr(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, ccShiftedObject::isShifted(), cloudViewer::NormalizedProgress::oneStep(), cloudViewer::GenericMesh::placeIteratorAtBeginning(), cloudViewer::GenericMesh::size(), Tuple3Tpl< Type >::u, and CVLog::Warning().
Referenced by saveToFile().
saveToFile()
CC_FILE_ERROR STLFilter::saveToFile (ccHObject * entity, const QString & filename, const SaveParameters & parameters) override virtual
Saves an entity (or a group of) to a file.
This method must be implemented by children classes.
Parameters
entity entity (or group of) to save
filename filename
parameters generic saving parameters
Returns
error
Reimplemented from FileIOFilter.
Definition at line 52 of file STLFilter.cpp.
References FileIOFilter::SaveParameters::alwaysDisplaySaveDialog, CC_FERR_BAD_ARGUMENT, CC_FERR_BAD_ENTITY_TYPE, CC_FERR_NO_ERROR, CC_FERR_WRITING, filename, ccObject::getName(), ccObject::isKindOf(), CV_TYPES::MESH, result, saveToASCIIFile(), saveToBINFile(), cloudViewer::GenericMesh::size(), ccHObjectCaster::ToGenericMesh(), and CVLog::Warning().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_io/include/STLFilter.h
/root/ACloudViewer/libs/CV_io/src/STLFilter.cpp