ACloudViewer: FrameBufferObject Class Reference
FrameBufferObject Class Reference
#include <FrameBufferObject.h>
Public Member Functions
void BindFBO ()
FrameBufferObject (int autobind=1)
~FrameBufferObject ()
Static Public Member Functions
static void DeleteGlobalFBO ()
static void UnattachTex (GLenum attachment)
static void UnbindFBO ()
static void AttachDepthTexture (GLenum textureTarget, GLuint texID)
static void AttachTexture (GLenum textureTarget, GLenum attachment, GLuint texID)
static void AttachRenderBuffer (GLenum attachment, GLuint buffID)
static void UnattachRenderBuffer (GLenum attachment)
Static Public Attributes
static int UseSingleFBO =1
Detailed Description
Definition at line 28 of file FrameBufferObject.h.
Constructor & Destructor Documentation
FrameBufferObject()
FrameBufferObject::FrameBufferObject (int autobind = 1)
Definition at line 38 of file FrameBufferObject.cpp.
References UseSingleFBO.
~FrameBufferObject()
FrameBufferObject::~FrameBufferObject ()
Definition at line 51 of file FrameBufferObject.cpp.
References UseSingleFBO.
Member Function Documentation
AttachDepthTexture()
void FrameBufferObject::AttachDepthTexture (GLenum textureTarget, GLuint texID) static
Definition at line 69 of file FrameBufferObject.cpp.
AttachRenderBuffer()
void FrameBufferObject::AttachRenderBuffer (GLenum attachment, GLuint buffID) static
Definition at line 95 of file FrameBufferObject.cpp.
AttachTexture()
void FrameBufferObject::AttachTexture (GLenum textureTarget, GLenum attachment, GLuint texID) static
Definition at line 75 of file FrameBufferObject.cpp.
BindFBO()
void FrameBufferObject::BindFBO ()
Definition at line 80 of file FrameBufferObject.cpp.
Referenced by PyramidGL::GenerateFeatureDisplayVBO().
DeleteGlobalFBO()
void FrameBufferObject::DeleteGlobalFBO () static
Definition at line 60 of file FrameBufferObject.cpp.
References UseSingleFBO.
Referenced by PyramidGL::CleanUpAfterSIFT().
UnattachRenderBuffer()
void FrameBufferObject::UnattachRenderBuffer (GLenum attachment) static
Definition at line 101 of file FrameBufferObject.cpp.
UnattachTex()
void FrameBufferObject::UnattachTex (GLenum attachment) static
Definition at line 90 of file FrameBufferObject.cpp.
Referenced by PyramidNaive::ComputeGradient(), PyramidPacked::ComputeGradient(), PyramidNaive::DetectKeypointsEX(), PyramidPacked::DetectKeypointsEX(), PyramidGL::GetFeatureDescriptors(), PyramidNaive::GetFeatureOrientations(), and PyramidPacked::GetFeatureOrientations().
UnbindFBO()
void FrameBufferObject::UnbindFBO () static
Definition at line 85 of file FrameBufferObject.cpp.
Member Data Documentation
UseSingleFBO
int FrameBufferObject::UseSingleFBO =1 static
Definition at line 33 of file FrameBufferObject.h.
Referenced by DeleteGlobalFBO(), FrameBufferObject(), SiftGPU::ParseParam(), and ~FrameBufferObject().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/FrameBufferObject.h
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/FrameBufferObject.cpp