ACloudViewer: vtkDiscretizableColorTransferFunctionCustom Class Reference
vtkDiscretizableColorTransferFunctionCustom Class Reference
#include <vtkDiscretizableColorTransferFunctionCustom.h>
Public Member Functions
vtkTypeMacro (vtkDiscretizableColorTransferFunctionCustom, vtkDiscretizableColorTransferFunction)
void PrintSelf (ostream &os, vtkIndent indent) override
virtual void SetAnnotationsInFullSet (vtkAbstractArray *values, vtkStringArray *annotations)
vtkGetObjectMacro (AnnotatedValuesInFullSet, vtkAbstractArray)
vtkGetObjectMacro (AnnotationsInFullSet, vtkStringArray)
virtual vtkIdType SetAnnotationInFullSet (vtkVariant value, std::string annotation)
virtual vtkIdType SetAnnotationInFullSet (std::string value, std::string annotation)
virtual void ResetAnnotationsInFullSet ()
void SetIndexedColorRGB (unsigned int index, const double rgb[3])
void SetIndexedColorRGBA (unsigned int index, const double rgba[4])
void ResetActiveAnnotatedValues ()
void SetActiveAnnotatedValue (std::string value)
void SetNumberOfIndexedColorsInFullSet (int n)
int GetNumberOfIndexedColorsInFullSet ()
void SetIndexedColorInFullSet (unsigned int index, double r, double g, double b)
void GetIndexedColorInFullSet (unsigned int index, double rgb[3])
void SetNumberOfIndexedOpacitiesInFullSet (int n)
int GetNumberOfIndexedOpacitiesInFullSet ()
void SetIndexedOpacityInFullSet (unsigned int index, double alpha)
void GetIndexedOpacityInFullSet (unsigned int index, double *alpha)
vtkSetMacro (UseActiveValues, bool)
vtkGetMacro (UseActiveValues, bool)
vtkBooleanMacro (UseActiveValues, bool)
void Build () override
Static Public Member Functions
static vtkDiscretizableColorTransferFunctionCustom * New ()
Protected Member Functions
vtkDiscretizableColorTransferFunctionCustom ()
~vtkDiscretizableColorTransferFunctionCustom () override
Detailed Description
Definition at line 17 of file vtkDiscretizableColorTransferFunctionCustom.h.
Constructor & Destructor Documentation
vtkDiscretizableColorTransferFunctionCustom()
vtkDiscretizableColorTransferFunctionCustom::vtkDiscretizableColorTransferFunctionCustom () protected
Definition at line 20 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
References NULL.
~vtkDiscretizableColorTransferFunctionCustom()
vtkDiscretizableColorTransferFunctionCustom::~vtkDiscretizableColorTransferFunctionCustom () override protected
Definition at line 35 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
Member Function Documentation
Build()
void vtkDiscretizableColorTransferFunctionCustom::Build () override
Override to set only the active annotations
Definition at line 289 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
References color, GetIndexedColorInFullSet(), GetIndexedOpacityInFullSet(), and SetIndexedColorRGBA().
GetIndexedColorInFullSet()
void vtkDiscretizableColorTransferFunctionCustom::GetIndexedColorInFullSet (unsigned int index, double rgb[3])
Definition at line 225 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
References rgb.
Referenced by Build().
GetIndexedOpacityInFullSet()
void vtkDiscretizableColorTransferFunctionCustom::GetIndexedOpacityInFullSet (unsigned int index, double * alpha)
Definition at line 276 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
Referenced by Build().
GetNumberOfIndexedColorsInFullSet()
int vtkDiscretizableColorTransferFunctionCustom::GetNumberOfIndexedColorsInFullSet ()
Definition at line 219 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
GetNumberOfIndexedOpacitiesInFullSet()
int vtkDiscretizableColorTransferFunctionCustom::GetNumberOfIndexedOpacitiesInFullSet ()
Definition at line 269 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
New()
static vtkDiscretizableColorTransferFunctionCustom* vtkDiscretizableColorTransferFunctionCustom::New () static
PrintSelf()
void vtkDiscretizableColorTransferFunctionCustom::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 346 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
ResetActiveAnnotatedValues()
void vtkDiscretizableColorTransferFunctionCustom::ResetActiveAnnotatedValues ()
Definition at line 168 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
ResetAnnotationsInFullSet()
void vtkDiscretizableColorTransferFunctionCustom::ResetAnnotationsInFullSet () virtual
Definition at line 154 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
References SetAnnotationsInFullSet().
SetActiveAnnotatedValue()
void vtkDiscretizableColorTransferFunctionCustom::SetActiveAnnotatedValue (std::string value)
Definition at line 176 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
SetAnnotationInFullSet() [1/2]
vtkIdType vtkDiscretizableColorTransferFunctionCustom::SetAnnotationInFullSet (std::string value, std::string annotation) virtual
Definition at line 137 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
References SetAnnotationInFullSet(), and x.
SetAnnotationInFullSet() [2/2]
vtkIdType vtkDiscretizableColorTransferFunctionCustom::SetAnnotationInFullSet (vtkVariant value, std::string annotation) virtual
Definition at line 109 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
Referenced by SetAnnotationInFullSet().
SetAnnotationsInFullSet()
void vtkDiscretizableColorTransferFunctionCustom::SetAnnotationsInFullSet (vtkAbstractArray * values, vtkStringArray * annotations) virtual
Parallel API to API for annotated values to set/get the full list of annotations. A subset of the full list will be used.
Definition at line 59 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
Referenced by ResetAnnotationsInFullSet().
SetIndexedColorInFullSet()
void vtkDiscretizableColorTransferFunctionCustom::SetIndexedColorInFullSet (unsigned int index, double r, double g, double b)
Definition at line 199 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
References rgb, and SetNumberOfIndexedColorsInFullSet().
SetIndexedColorRGB()
void vtkDiscretizableColorTransferFunctionCustom::SetIndexedColorRGB (unsigned int index, const double rgb[3]) inline
Add colors to use when IndexedLookup is true. SetIndexedColor() will automatically call SetNumberOfIndexedColors(index+1) if the current number of indexed colors is not sufficient for the specified index and all will be initialized to the RGBA/RGB values passed to this call.
Definition at line 48 of file vtkDiscretizableColorTransferFunctionCustom.h.
References rgb.
SetIndexedColorRGBA()
void vtkDiscretizableColorTransferFunctionCustom::SetIndexedColorRGBA (unsigned int index, const double rgba[4]) inline
Definition at line 51 of file vtkDiscretizableColorTransferFunctionCustom.h.
Referenced by Build().
SetIndexedOpacityInFullSet()
void vtkDiscretizableColorTransferFunctionCustom::SetIndexedOpacityInFullSet (unsigned int index, double alpha)
Definition at line 251 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
References SetNumberOfIndexedOpacitiesInFullSet().
SetNumberOfIndexedColorsInFullSet()
void vtkDiscretizableColorTransferFunctionCustom::SetNumberOfIndexedColorsInFullSet (int n)
Definition at line 183 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
Referenced by SetIndexedColorInFullSet().
SetNumberOfIndexedOpacitiesInFullSet()
void vtkDiscretizableColorTransferFunctionCustom::SetNumberOfIndexedOpacitiesInFullSet (int n)
Definition at line 237 of file vtkDiscretizableColorTransferFunctionCustom.cpp.
Referenced by SetIndexedOpacityInFullSet().
vtkBooleanMacro()
vtkDiscretizableColorTransferFunctionCustom::vtkBooleanMacro (UseActiveValues , bool)
vtkGetMacro()
vtkDiscretizableColorTransferFunctionCustom::vtkGetMacro (UseActiveValues , bool)
vtkGetObjectMacro() [1/2]
vtkDiscretizableColorTransferFunctionCustom::vtkGetObjectMacro (AnnotatedValuesInFullSet , vtkAbstractArray)
vtkGetObjectMacro() [2/2]
vtkDiscretizableColorTransferFunctionCustom::vtkGetObjectMacro (AnnotationsInFullSet , vtkStringArray)
vtkSetMacro()
vtkDiscretizableColorTransferFunctionCustom::vtkSetMacro (UseActiveValues , bool)
Set whether to use restrict annotations to only the values designated as active. Off by default.
vtkTypeMacro()
vtkDiscretizableColorTransferFunctionCustom::vtkTypeMacro (vtkDiscretizableColorTransferFunctionCustom , vtkDiscretizableColorTransferFunction)
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Utility/vtkDiscretizableColorTransferFunctionCustom.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Utility/vtkDiscretizableColorTransferFunctionCustom.cpp