ACloudViewer: cloudViewer::t::io::DepthNoiseSimulator Class Reference
cloudViewer::t::io::DepthNoiseSimulator Class Reference
#include <ImageIO.h>
Public Member Functions
DepthNoiseSimulator (const std::string &noise_model_path)
Constructor.
geometry::Image Simulate (const geometry::Image &im_src, float depth_scale=1000.0)
Apply noise model to a depth image.
core::Tensor GetNoiseModel () const
Return the noise model.
void EnableDeterministicDebugMode ()
Enable deterministic debug mode. All normally distributed noise will be replaced by 0.
Detailed Description
Simulate depth image noise from a given noise distortion model. The distortion model is based on Teichman et. al. "Unsupervised intrinsic calibration of depth sensors via SLAM" RSS 2009. Also see Redwood dataset
Definition at line 79 of file ImageIO.h.
Constructor & Destructor Documentation
DepthNoiseSimulator()
cloudViewer::t::io::DepthNoiseSimulator::DepthNoiseSimulator (const std::string & noise_model_path) explicit
Constructor.
Parameters
noise_model Path to the noise model file. See http://redwood-data.org/indoor/dataset.html for the format. Or, you may use one of our example datasets, e.g., RedwoodIndoorLivingRoom1.
Definition at line 99 of file ImageIO.cpp.
References cloudViewer::core::Float32, LogError, cloudViewer::utility::filesystem::CFile::Open(), cloudViewer::utility::filesystem::CFile::ReadLine(), and cloudViewer::core::Tensor::Zeros().
Member Function Documentation
EnableDeterministicDebugMode()
void cloudViewer::t::io::DepthNoiseSimulator::EnableDeterministicDebugMode () inline
Enable deterministic debug mode. All normally distributed noise will be replaced by 0.
Definition at line 104 of file ImageIO.h.
GetNoiseModel()
core::Tensor cloudViewer::t::io::DepthNoiseSimulator::GetNoiseModel () const inline
Return the noise model.
Definition at line 100 of file ImageIO.h.
Simulate()
geometry::Image cloudViewer::t::io::DepthNoiseSimulator::Simulate (const geometry::Image & im_src, float depth_scale = 1000.0)
Apply noise model to a depth image.
Parameters
im_src Source depth image, must be with dtype UInt16 or Float32, channels==1.
depth_scale Scale factor to the depth image. As a sanity check, if the dtype is Float32, the depth_scale must be 1.0. If the dtype is is UInt16, the depth_scale is typically larger than 1.0, e.g. it can be 1000.0.
Returns
Noisy depth image with the same shape and dtype as im_src.
Definition at line 158 of file ImageIO.cpp.
References cloudViewer::t::geometry::Image::AsTensor(), cloudViewer::core::Tensor::Clone(), CLOUDVIEWER_DEVICE, cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Float32, cloudViewer::t::geometry::Image::GetChannels(), cloudViewer::t::geometry::Image::GetCols(), cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::t::geometry::Image::GetDtype(), cloudViewer::t::geometry::Image::GetRows(), height, LogError, LogWarning, max(), min(), cloudViewer::core::ParallelFor(), cloudViewer::t::geometry::kernel::image::To(), cloudViewer::core::Tensor::To(), cloudViewer::core::Dtype::ToString(), cloudViewer::core::UInt16, width, and cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::WorkloadToCoord().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/t/io/ImageIO.h
/root/ACloudViewer/libs/cloudViewer/t/io/ImageIO.cpp