ACloudViewer: colmap::RANSAC< Estimator, SupportMeasurer, Sampler > Class Template Reference
colmap::RANSAC< Estimator, SupportMeasurer, Sampler > Class Template Reference
#include <ransac.h>
Classes
struct Report
Public Member Functions
RANSAC (const RANSACOptions &options)
Report Estimate (const std::vector< typename Estimator::X_t > &X, const std::vector< typename Estimator::Y_t > &Y)
Static Public Member Functions
static size_t ComputeNumTrials (const size_t num_inliers, const size_t num_samples, const double confidence, const double num_trials_multiplier)
Public Attributes
Estimator estimator
Sampler sampler
SupportMeasurer support_measurer
Protected Attributes
RANSACOptions options_
Detailed Description
template<typename Estimator, typename SupportMeasurer = InlierSupportMeasurer, typename Sampler = RandomSampler>
class colmap::RANSAC< Estimator, SupportMeasurer, Sampler >
Definition at line 56 of file ransac.h.
Constructor & Destructor Documentation
RANSAC()
template<typename Estimator , typename SupportMeasurer , typename Sampler > colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::RANSAC (const RANSACOptions & options) explicit
Definition at line 120 of file ransac.h.
Member Function Documentation
ComputeNumTrials()
template<typename Estimator , typename SupportMeasurer , typename Sampler > size_t colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::ComputeNumTrials (const size_t num_inliers, const size_t num_samples, const double confidence, const double num_trials_multiplier) static
Definition at line 136 of file ransac.h.
References cloudViewer::utility::ceil(), and kMinNumSamples.
Referenced by colmap::retrieval::VoteAndVerify().
Estimate()
template<typename Estimator , typename SupportMeasurer , typename Sampler > RANSAC< Estimator, SupportMeasurer, Sampler >::Report colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::Estimate (const std::vector< typename Estimator::X_t > & X, const std::vector< typename Estimator::Y_t > & Y)
Definition at line 159 of file ransac.h.
References kMinNumSamples, colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::Report::num_trials, colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::Report::success, and X.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::EstimateManhattanWorldFrame(), and colmap::EstimateRelativePose().
Member Data Documentation
estimator
template<typename Estimator , typename SupportMeasurer = InlierSupportMeasurer, typename Sampler = RandomSampler> Estimator colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::estimator
Definition at line 107 of file ransac.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::ComputeAlignmentBetweenReconstructions().
options_
template<typename Estimator , typename SupportMeasurer = InlierSupportMeasurer, typename Sampler = RandomSampler> RANSACOptions colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::options_ protected
Definition at line 112 of file ransac.h.
sampler
template<typename Estimator , typename SupportMeasurer = InlierSupportMeasurer, typename Sampler = RandomSampler> Sampler colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::sampler
Definition at line 108 of file ransac.h.
support_measurer
template<typename Estimator , typename SupportMeasurer = InlierSupportMeasurer, typename Sampler = RandomSampler> SupportMeasurer colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::support_measurer
Definition at line 109 of file ransac.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/optim/ransac.h