ACloudViewer: cloudViewer::core::SmallVectorImpl< T > Class Template Reference
cloudViewer::core::SmallVectorImpl< T > Class Template Reference
#include <SmallVector.h>
Public Types
using iterator = typename SuperClass::iterator
using const_iterator = typename SuperClass::const_iterator
using reference = typename SuperClass::reference
using size_type = typename SuperClass::size_type
Public Types inherited from cloudViewer::core::SmallVectorTemplateCommon< T, typename >
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = std::reverse_iterator< iterator >
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Public Member Functions
SmallVectorImpl (const SmallVectorImpl &)=delete
~SmallVectorImpl ()
void clear ()
void resize (size_type N)
void resize_for_overwrite (size_type N)
Like resize, but T is POD, the new values won't be initialized.
void truncate (size_type N)
Like resize, but requires that N is less than size().
void resize (size_type N, ValueParamT NV)
void reserve (size_type N)
void pop_back_n (size_type NumItems)
T pop_back_val ()
void swap (SmallVectorImpl &RHS)
template<typename in_iter , typename = std::enable_if_t<std::is_convertible< typename std::iterator_traits<in_iter>::iterator_category, std::input_iterator_tag>::value>>
void append (in_iter in_start, in_iter in_end)
Add the specified range to the end of the SmallVector.
void append (size_type NumInputs, ValueParamT Elt)
Append NumInputs copies of Elt to the end.
void append (std::initializer_list< T > IL)
void append (const SmallVectorImpl &RHS)
void assign (size_type NumElts, ValueParamT Elt)
template<typename in_iter , typename = std::enable_if_t<std::is_convertible< typename std::iterator_traits<in_iter>::iterator_category, std::input_iterator_tag>::value>>
void assign (in_iter in_start, in_iter in_end)
void assign (std::initializer_list< T > IL)
void assign (const SmallVectorImpl &RHS)
iterator erase (const_iterator CI)
iterator erase (const_iterator CS, const_iterator CE)
iterator insert (iterator I, T &&Elt)
iterator insert (iterator I, const T &Elt)
iterator insert (iterator I, size_type NumToInsert, ValueParamT Elt)
template<typename ItTy , typename = std::enable_if_t<std::is_convertible< typename std::iterator_traits<ItTy>::iterator_category, std::input_iterator_tag>::value>>
iterator insert (iterator I, ItTy From, ItTy To)
void insert (iterator I, std::initializer_list< T > IL)
template<typename... ArgTypes>
reference emplace_back (ArgTypes &&...Args)
SmallVectorImpl & operator= (const SmallVectorImpl &RHS)
SmallVectorImpl & operator= (SmallVectorImpl &&RHS)
bool operator== (const SmallVectorImpl &RHS) const
bool operator!= (const SmallVectorImpl &RHS) const
bool operator< (const SmallVectorImpl &RHS) const
bool operator> (const SmallVectorImpl &RHS) const
bool operator<= (const SmallVectorImpl &RHS) const
bool operator>= (const SmallVectorImpl &RHS) const
Public Member Functions inherited from cloudViewer::core::SmallVectorTemplateBase< T, bool >
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
Public Member Functions inherited from cloudViewer::core::SmallVectorTemplateCommon< T, typename >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >
size_t size () const
size_t capacity () const
bool empty () const
Protected Types
using ValueParamT = typename SuperClass::ValueParamT
Protected Types inherited from cloudViewer::core::SmallVectorTemplateBase< T, bool >
using ValueParamT = const T &
Protected Member Functions
SmallVectorImpl (unsigned N)
void assignRemote (SmallVectorImpl &&RHS)
Protected Member Functions inherited from cloudViewer::core::SmallVectorTemplateBase< T, bool >
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
T * mallocForGrow (size_t MinSize, size_t &NewCapacity)
void moveElementsForGrow (T *NewElts)
void takeAllocationForGrow (T *NewElts, size_t NewCapacity)
Transfer ownership of the allocation, finishing up grow().
const T * reserveForParamAndGetAddress (const T &Elt, size_t N=1)
T * reserveForParamAndGetAddress (T &Elt, size_t N=1)
void growAndAssign (size_t NumElts, const T &Elt)
template<typename... ArgTypes>
T & growAndEmplaceBack (ArgTypes &&...Args)
Protected Member Functions inherited from cloudViewer::core::SmallVectorTemplateCommon< T, typename >
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSize, size_t TSize)
bool isSmall () const
void resetToSmall ()
Put this vector in a state of being small.
bool isReferenceToRange (const void *V, const void *First, const void *Last) const
Return true if V is an internal reference to the given range.
bool isReferenceToStorage (const void *V) const
Return true if V is an internal reference to this vector.
bool isRangeInStorage (const void *First, const void *Last) const
bool isSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
void assertSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Check whether Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToAdd (const void *Elt, size_t N=1)
void assertSafeToReferenceAfterClear (const T *From, const T *To)
Check whether any part of the range will be invalidated by clearing.
template<class ItTy , std::enable_if_t< !std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToReferenceAfterClear (ItTy, ItTy)
void assertSafeToAddRange (const T *From, const T *To)
Check whether any part of the range will be invalidated by growing.
template<class ItTy , std::enable_if_t< !std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToAddRange (ItTy, ItTy)
Protected Member Functions inherited from cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (size_t MinSize, size_t TSize, size_t &NewCapacity)
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
void set_size (size_t N)
Additional Inherited Members
Static Protected Member Functions inherited from cloudViewer::core::SmallVectorTemplateBase< T, bool >
static void destroy_range (T *S, T *E)
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
static T && forward_value_param (T &&V)
static const T & forward_value_param (const T &V)
Static Protected Member Functions inherited from cloudViewer::core::SmallVectorTemplateCommon< T, typename >
template<class U >
static const T * reserveForParamAndGetAddressImpl (U *This, const T &Elt, size_t N)
Static Protected Member Functions inherited from cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Protected Attributes inherited from cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >
void * BeginX
SmallVectorSizeType< T > Size
SmallVectorSizeType< T > Capacity
Static Protected Attributes inherited from cloudViewer::core::SmallVectorTemplateBase< T, bool >
static constexpr bool TakesParamByValue = false
Detailed Description
template<typename T>
class cloudViewer::core::SmallVectorImpl< T >
This class consists of common code factored out of the SmallVector class to reduce code duplication based on the SmallVector 'N' template parameter.
Definition at line 616 of file SmallVector.h.
Member Typedef Documentation
const_iterator
template<typename T > using cloudViewer::core::SmallVectorImpl< T >::const_iterator = typename SuperClass::const_iterator
Definition at line 621 of file SmallVector.h.
iterator
template<typename T > using cloudViewer::core::SmallVectorImpl< T >::iterator = typename SuperClass::iterator
Definition at line 620 of file SmallVector.h.
reference
template<typename T > using cloudViewer::core::SmallVectorImpl< T >::reference = typename SuperClass::reference
Definition at line 622 of file SmallVector.h.
size_type
template<typename T > using cloudViewer::core::SmallVectorImpl< T >::size_type = typename SuperClass::size_type
Definition at line 623 of file SmallVector.h.
ValueParamT
template<typename T > using cloudViewer::core::SmallVectorImpl< T >::ValueParamT = typename SuperClass::ValueParamT protected
Definition at line 627 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorImpl() [1/2]
template<typename T > cloudViewer::core::SmallVectorImpl< T >::SmallVectorImpl (unsigned N) inline explicit protected
Definition at line 630 of file SmallVector.h.
SmallVectorImpl() [2/2]
template<typename T > cloudViewer::core::SmallVectorImpl< T >::SmallVectorImpl (const SmallVectorImpl< T > &) delete
~SmallVectorImpl()
template<typename T > cloudViewer::core::SmallVectorImpl< T >::~SmallVectorImpl () inline
Definition at line 644 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), and cloudViewer::core::SmallVectorTemplateCommon< T, typename >::isSmall().
Member Function Documentation
append() [1/4]
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::append (const SmallVectorImpl< T > & RHS) inline
Definition at line 741 of file SmallVector.h.
References cloudViewer::core::SmallVectorImpl< T >::append(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), and cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end().
Referenced by cloudViewer::core::SmallVectorImpl< T >::append().
append() [2/4]
template<typename T > template<typename in_iter , typename = std::enable_if_t<std::is_convertible< typename std::iterator_traits<in_iter>::iterator_category, std::input_iterator_tag>::value>> void cloudViewer::core::SmallVectorImpl< T >::append (in_iter in_start, in_iter in_end) inline
Add the specified range to the end of the SmallVector.
Definition at line 724 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::assertSafeToAddRange(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorImpl< T >::reserve(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::uninitialized_copy().
Referenced by cloudViewer::core::SmallVectorImpl< T >::assign(), cloudViewer::core::SmallVectorImpl< T >::insert(), cloudViewer::core::SmallVectorImpl< T >::resize(), and cloudViewer::core::SmallVector< T, N >::SmallVector().
append() [3/4]
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::append (size_type NumInputs, ValueParamT Elt) inline
Append NumInputs copies of Elt to the end.
Definition at line 733 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size().
append() [4/4]
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::append (std::initializer_list< T > IL) inline
Definition at line 739 of file SmallVector.h.
References cloudViewer::core::SmallVectorImpl< T >::append().
Referenced by cloudViewer::core::SmallVectorImpl< T >::append().
assign() [1/4]
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::assign (const SmallVectorImpl< T > & RHS) inline
Definition at line 777 of file SmallVector.h.
References cloudViewer::core::SmallVectorImpl< T >::assign(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), and cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end().
Referenced by cloudViewer::core::SmallVectorImpl< T >::assign().
assign() [2/4]
template<typename T > template<typename in_iter , typename = std::enable_if_t<std::is_convertible< typename std::iterator_traits<in_iter>::iterator_category, std::input_iterator_tag>::value>> void cloudViewer::core::SmallVectorImpl< T >::assign (in_iter in_start, in_iter in_end) inline
Definition at line 766 of file SmallVector.h.
References cloudViewer::core::SmallVectorImpl< T >::append(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterClear(), and cloudViewer::core::SmallVectorImpl< T >::clear().
assign() [3/4]
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::assign (size_type NumElts, ValueParamT Elt) inline
Definition at line 743 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::destroy_range(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::growAndAssign(), min(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size().
Referenced by cloudViewer::core::SmallVector< T, N >::operator=(), and cloudViewer::core::SmallVector< T, N >::SmallVector().
assign() [4/4]
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::assign (std::initializer_list< T > IL) inline
Definition at line 772 of file SmallVector.h.
References cloudViewer::core::SmallVectorImpl< T >::append(), and cloudViewer::core::SmallVectorImpl< T >::clear().
assignRemote()
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::assignRemote (SmallVectorImpl< T > && RHS) inline protected
Definition at line 632 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::BeginX, cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::Capacity, cloudViewer::core::SmallVectorTemplateBase< T, bool >::destroy_range(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::isSmall(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::Size.
Referenced by cloudViewer::core::SmallVector< T, N >::operator=(), and cloudViewer::core::SmallVectorImpl< T >::operator=().
clear()
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::clear () inline
Definition at line 650 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::destroy_range(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::Size.
Referenced by cloudViewer::core::SmallVectorImpl< T >::assign(), cloudViewer::core::SmallVectorImpl< T >::operator=(), and cloudViewer::t::io::ParsePropertyDict().
emplace_back()
template<typename T > template<typename... ArgTypes> reference cloudViewer::core::SmallVectorImpl< T >::emplace_back (ArgTypes &&... Args) inline
Definition at line 995 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::back(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack(), LLVM_UNLIKELY, cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size().
erase() [1/2]
template<typename T > iterator cloudViewer::core::SmallVectorImpl< T >::erase (const_iterator CI) inline
Definition at line 779 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::isReferenceToStorage(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::pop_back().
Referenced by cloudViewer::core::HashMap::CheckKeyCompatibility(), cloudViewer::core::HashMap::CheckValueCompatibility(), cloudViewer::core::Tensor::IndexExtract(), cloudViewer::t::geometry::VoxelBlockGrid::Load(), and cloudViewer::core::AdvancedIndexPreprocessor::RestrideTensor().
erase() [2/2]
template<typename T > iterator cloudViewer::core::SmallVectorImpl< T >::erase (const_iterator CS, const_iterator CE) inline
Definition at line 794 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::destroy_range(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::isRangeInStorage(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size().
insert() [1/5]
template<typename T > iterator cloudViewer::core::SmallVectorImpl< T >::insert (iterator I, const T & Elt) inline
Definition at line 857 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateBase< T, bool >::forward_value_param().
insert() [2/5]
template<typename T > template<typename ItTy , typename = std::enable_if_t<std::is_convertible< typename std::iterator_traits<ItTy>::iterator_category, std::input_iterator_tag>::value>> iterator cloudViewer::core::SmallVectorImpl< T >::insert (iterator I, ItTy From, ItTy To) inline
Definition at line 929 of file SmallVector.h.
References cloudViewer::core::SmallVectorImpl< T >::append(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::assertSafeToAddRange(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), copy, cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::isReferenceToStorage(), cloudViewer::core::SmallVectorImpl< T >::reserve(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size(), cloudViewer::t::geometry::kernel::image::To(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::uninitialized_copy(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::uninitialized_move().
insert() [3/5]
template<typename T > iterator cloudViewer::core::SmallVectorImpl< T >::insert (iterator I, size_type NumToInsert, ValueParamT Elt) inline
Definition at line 861 of file SmallVector.h.
References cloudViewer::core::SmallVectorImpl< T >::append(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::isReferenceToStorage(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::TakesParamByValue, and cloudViewer::core::SmallVectorTemplateBase< T, bool >::uninitialized_move().
insert() [4/5]
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::insert (iterator I, std::initializer_list< T > IL) inline
Definition at line 990 of file SmallVector.h.
References cloudViewer::core::SmallVectorImpl< T >::insert().
insert() [5/5]
template<typename T > iterator cloudViewer::core::SmallVectorImpl< T >::insert (iterator I, T && Elt) inline
Definition at line 853 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateBase< T, bool >::forward_value_param().
Referenced by cloudViewer::core::shape_util::Concat(), cloudViewer::core::HashMap::GetKeyTensor(), cloudViewer::core::HashMap::GetValueTensor(), cloudViewer::core::HashMap::GetValueTensors(), cloudViewer::core::SmallVectorImpl< T >::insert(), cloudViewer::core::AdvancedIndexPreprocessor::RestrideTensor(), cloudViewer::core::AdvancedIndexPreprocessor::RunPreprocess(), and cloudViewer::t::geometry::VoxelBlockGrid::VoxelBlockGrid().
operator!=()
template<typename T > bool cloudViewer::core::SmallVectorImpl< T >::operator!= (const SmallVectorImpl< T > & RHS) const inline
Definition at line 1012 of file SmallVector.h.
operator<()
template<typename T > bool cloudViewer::core::SmallVectorImpl< T >::operator< (const SmallVectorImpl< T > & RHS) const inline
Definition at line 1016 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), and cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end().
operator<=()
template<typename T > bool cloudViewer::core::SmallVectorImpl< T >::operator<= (const SmallVectorImpl< T > & RHS) const inline
Definition at line 1021 of file SmallVector.h.
operator=() [1/2]
template<typename T > SmallVectorImpl< T > & cloudViewer::core::SmallVectorImpl< T >::operator= (const SmallVectorImpl< T > & RHS)
Definition at line 1063 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), cloudViewer::core::SmallVectorImpl< T >::clear(), copy, cloudViewer::core::SmallVectorTemplateBase< T, bool >::destroy_range(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::grow(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size(), cloudViewer::core::SmallVectorBase< Size_T >::size(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::uninitialized_copy().
Referenced by cloudViewer::core::SmallVector< T, N >::operator=(), and cloudViewer::core::SmallVector< T, N >::SmallVector().
operator=() [2/2]
template<typename T > SmallVectorImpl< T > & cloudViewer::core::SmallVectorImpl< T >::operator= (SmallVectorImpl< T > && RHS)
Definition at line 1112 of file SmallVector.h.
References cloudViewer::core::SmallVectorImpl< T >::assignRemote(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), cloudViewer::core::SmallVectorImpl< T >::clear(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::destroy_range(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::grow(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::uninitialized_move().
operator==()
template<typename T > bool cloudViewer::core::SmallVectorImpl< T >::operator== (const SmallVectorImpl< T > & RHS) const inline
Definition at line 1008 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorBase< Size_T >::size(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size().
operator>()
template<typename T > bool cloudViewer::core::SmallVectorImpl< T >::operator> (const SmallVectorImpl< T > & RHS) const inline
Definition at line 1020 of file SmallVector.h.
operator>=()
template<typename T > bool cloudViewer::core::SmallVectorImpl< T >::operator>= (const SmallVectorImpl< T > & RHS) const inline
Definition at line 1022 of file SmallVector.h.
pop_back_n()
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::pop_back_n (size_type NumItems) inline
Definition at line 706 of file SmallVector.h.
References cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size(), and cloudViewer::core::SmallVectorImpl< T >::truncate().
pop_back_val()
template<typename T > T cloudViewer::core::SmallVectorImpl< T >::pop_back_val () inline
Definition at line 711 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::back(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::pop_back().
reserve()
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::reserve (size_type N) inline
Definition at line 702 of file SmallVector.h.
References cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::grow().
Referenced by cloudViewer::core::SmallVectorImpl< T >::append(), cloudViewer::core::SmallVectorImpl< T >::insert(), and cloudViewer::core::SmallVectorImpl< T >::swap().
resize() [1/2]
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::resize (size_type N) inline
Definition at line 678 of file SmallVector.h.
Referenced by cloudViewer::core::tensor_init::InferShape(), and cloudViewer::core::shape_util::ReductionShape().
resize() [2/2]
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::resize (size_type N, ValueParamT NV) inline
Definition at line 690 of file SmallVector.h.
References cloudViewer::core::SmallVectorImpl< T >::append(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size(), and cloudViewer::core::SmallVectorImpl< T >::truncate().
resize_for_overwrite()
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::resize_for_overwrite (size_type N) inline
Like resize, but T is POD, the new values won't be initialized.
Definition at line 681 of file SmallVector.h.
swap()
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::swap (SmallVectorImpl< T > & RHS)
Definition at line 1026 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorBase< Size_T >::BeginX, cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::BeginX, cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::Capacity, cloudViewer::core::SmallVectorBase< Size_T >::Capacity, cloudViewer::core::SmallVectorTemplateBase< T, bool >::destroy_range(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::isSmall(), cloudViewer::core::SmallVectorImpl< T >::reserve(), cloudViewer::core::SmallVectorBase< Size_T >::set_size(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::Size, cloudViewer::core::SmallVectorBase< Size_T >::Size, cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size(), cloudViewer::core::SmallVectorBase< Size_T >::size(), std::swap(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::uninitialized_copy().
Referenced by std::swap().
truncate()
template<typename T > void cloudViewer::core::SmallVectorImpl< T >::truncate (size_type N) inline
Like resize, but requires that N is less than size().
Definition at line 684 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::destroy_range(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size().
Referenced by cloudViewer::core::SmallVectorImpl< T >::pop_back_n(), and cloudViewer::core::SmallVectorImpl< T >::resize().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/SmallVector.h