ACloudViewer: ccGeomFeaturesDlg Class Reference
ccGeomFeaturesDlg Class Reference
Dialog for computing the density of a point clouds.
#include <ecvGeomFeaturesDlg.h>
Classes
struct Option
Public Member Functions
ccGeomFeaturesDlg (QWidget *parent=nullptr)
Default constructor.
void setSelectedFeatures (const ccLibAlgorithms::GeomCharacteristicSet &features)
Sets selected features.
bool getSelectedFeatures (ccLibAlgorithms::GeomCharacteristicSet &features) const
Returns selected features.
void setRadius (double r)
Sets the default kernel radius (for 'precise' mode only)
double getRadius () const
Returns the kernel radius (for 'precise' mode only)
void setUpDirection (const CCVector3 &upDir)
Sets the 'up direction' (and enables the group at the same time)
CCVector3 * getUpDirection () const
Returns the 'up direction' if any is defined (nullptr otherwise)
void reset ()
reset the whole dialog
Protected Attributes
std::vector< Option > m_options
Detailed Description
Dialog for computing the density of a point clouds.
Definition at line 19 of file ecvGeomFeaturesDlg.h.
Constructor & Destructor Documentation
ccGeomFeaturesDlg()
ccGeomFeaturesDlg::ccGeomFeaturesDlg (QWidget * parent = nullptr) explicit
Default constructor.
Definition at line 14 of file ecvGeomFeaturesDlg.cpp.
References cloudViewer::Neighbourhood::Anisotropy, cloudViewer::GeometricalAnalysisTools::Curvature, cloudViewer::GeometricalAnalysisTools::DENSITY_2D, cloudViewer::GeometricalAnalysisTools::DENSITY_3D, cloudViewer::GeometricalAnalysisTools::DENSITY_KNN, cloudViewer::Neighbourhood::EigenEntropy, cloudViewer::Neighbourhood::EigenValue1, cloudViewer::Neighbourhood::EigenValue2, cloudViewer::Neighbourhood::EigenValue3, cloudViewer::Neighbourhood::EigenValuesSum, cloudViewer::GeometricalAnalysisTools::Feature, cloudViewer::Neighbourhood::GAUSSIAN_CURV, cloudViewer::Neighbourhood::Linearity, cloudViewer::GeometricalAnalysisTools::LocalDensity, m_options, cloudViewer::Neighbourhood::MEAN_CURV, cloudViewer::GeometricalAnalysisTools::MomentOrder1, cloudViewer::Neighbourhood::NORMAL_CHANGE_RATE, cloudViewer::Neighbourhood::Omnivariance, cloudViewer::Neighbourhood::PCA1, cloudViewer::Neighbourhood::PCA2, cloudViewer::Neighbourhood::Planarity, reset(), cloudViewer::GeometricalAnalysisTools::Roughness, cloudViewer::Neighbourhood::Sphericity, cloudViewer::Neighbourhood::SurfaceVariation, and cloudViewer::Neighbourhood::Verticality.
Member Function Documentation
getRadius()
double ccGeomFeaturesDlg::getRadius () const
Returns the kernel radius (for 'precise' mode only)
Definition at line 165 of file ecvGeomFeaturesDlg.cpp.
getSelectedFeatures()
bool ccGeomFeaturesDlg::getSelectedFeatures (ccLibAlgorithms::GeomCharacteristicSet & features) const
Returns selected features.
Definition at line 146 of file ecvGeomFeaturesDlg.cpp.
References m_options.
getUpDirection()
CCVector3 * ccGeomFeaturesDlg::getUpDirection () const
Returns the 'up direction' if any is defined (nullptr otherwise)
Definition at line 116 of file ecvGeomFeaturesDlg.cpp.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
reset()
void ccGeomFeaturesDlg::reset ()
reset the whole dialog
Definition at line 173 of file ecvGeomFeaturesDlg.cpp.
References m_options.
Referenced by ccGeomFeaturesDlg(), and setSelectedFeatures().
setRadius()
void ccGeomFeaturesDlg::setRadius (double r)
Sets the default kernel radius (for 'precise' mode only)
Definition at line 169 of file ecvGeomFeaturesDlg.cpp.
setSelectedFeatures()
void ccGeomFeaturesDlg::setSelectedFeatures (const ccLibAlgorithms::GeomCharacteristicSet & features)
Sets selected features.
Definition at line 131 of file ecvGeomFeaturesDlg.cpp.
References m_options, and reset().
setUpDirection()
void ccGeomFeaturesDlg::setUpDirection (const CCVector3 & upDir)
Sets the 'up direction' (and enables the group at the same time)
Definition at line 109 of file ecvGeomFeaturesDlg.cpp.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Member Data Documentation
m_options
std::vector<Option> ccGeomFeaturesDlg::m_options protected
Definition at line 53 of file ecvGeomFeaturesDlg.h.
Referenced by ccGeomFeaturesDlg(), getSelectedFeatures(), reset(), and setSelectedFeatures().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvGeomFeaturesDlg.h
/root/ACloudViewer/app/ecvGeomFeaturesDlg.cpp