ACloudViewer: LasOpenDialog Class Reference
LasOpenDialog Class Reference
Dialog shown to the user when opening a LAS file.
#include <LasOpenDialog.h>
Public Types
enum class Action { Load , Tile }
Public Member Functions
LasOpenDialog (QWidget *parent=nullptr)
Default constructor.
void setInfo (int versionMinor, int pointFormatId, qulonglong numPoints)
void setAvailableScalarFields (const std::vector< LasScalarField > &scalarFields, const std::vector< LasExtraScalarField > &extraScalarFields)
void filterOutNotChecked (std::vector< LasScalarField > &scalarFields, std::vector< LasExtraScalarField > &extraScalarFields)
bool shouldIgnoreFieldsWithDefaultValues () const
bool shouldForce8bitColors () const
double timeShiftValue () const
Action action () const
LasTilingOptions tilingOptions () const
void resetShouldSkipDialog ()
bool shouldSkipDialog () const
Detailed Description
Dialog shown to the user when opening a LAS file.
Definition at line 44 of file LasOpenDialog.h.
Member Enumeration Documentation
Action
enum LasOpenDialog::Action strong
Enumerator
Load
The user wants to load the file in ACloudViewer.
Tile
The user wants to tile the file into multiple smaller ones.
Definition at line 50 of file LasOpenDialog.h.
Constructor & Destructor Documentation
LasOpenDialog()
LasOpenDialog::LasOpenDialog (QWidget * parent = nullptr) explicit
Default constructor.
Definition at line 54 of file LasOpenDialog.cpp.
Member Function Documentation
action()
LasOpenDialog::Action LasOpenDialog::action () const
Returns the action the user wants to do.
The action is based on the active tab when the user accepted the dialog.
Definition at line 210 of file LasOpenDialog.cpp.
References Load, Tile, and TILLING_TAB_INDEX.
Referenced by LasIOFilter::loadFile().
filterOutNotChecked()
void LasOpenDialog::filterOutNotChecked (std::vector< LasScalarField > & scalarFields, std::vector< LasExtraScalarField > & extraScalarFields)
Removes from the lists scalar fields and extra scalar fields which the user unchecked from the list of fields to load.
Definition at line 149 of file LasOpenDialog.cpp.
References RemoveFalse().
Referenced by LasIOFilter::loadFile().
resetShouldSkipDialog()
void LasOpenDialog::resetShouldSkipDialog ()
Definition at line 199 of file LasOpenDialog.cpp.
Referenced by LasIOFilter::loadFile().
setAvailableScalarFields()
void LasOpenDialog::setAvailableScalarFields (const std::vector< LasScalarField > & scalarFields, const std::vector< LasExtraScalarField > & extraScalarFields)
Sets the list of standard LAS scalar fields as well as user defined extra LAS scalar fields that are available in the file that the user is able to check which one should be loaded.
Definition at line 114 of file LasOpenDialog.cpp.
References CreateItem(), and height.
Referenced by LasIOFilter::loadFile().
setInfo()
void LasOpenDialog::setInfo (int versionMinor, int pointFormatId, qulonglong numPoints)
Set some informations about the file to be displayed to the user.
Definition at line 104 of file LasOpenDialog.cpp.
References LasDetails::HasGpsTime(), LasDetails::HasRGB(), and e57::toString().
Referenced by LasIOFilter::loadFile().
shouldForce8bitColors()
bool LasOpenDialog::shouldForce8bitColors () const
Returns whether the user wants to treat the rgb from the file as 8-bit components.
Definition at line 164 of file LasOpenDialog.cpp.
Referenced by LasIOFilter::loadFile().
shouldIgnoreFieldsWithDefaultValues()
bool LasOpenDialog::shouldIgnoreFieldsWithDefaultValues () const
Returns whether the user wants to ignore (not load) fields for which values are all default values.
Definition at line 159 of file LasOpenDialog.cpp.
Referenced by LasIOFilter::loadFile().
shouldSkipDialog()
bool LasOpenDialog::shouldSkipDialog () const
Definition at line 194 of file LasOpenDialog.cpp.
Referenced by LasIOFilter::loadFile().
tilingOptions()
LasTilingOptions LasOpenDialog::tilingOptions () const
Returns the tiling options.
Only valid when the action is Tiling
Definition at line 222 of file LasOpenDialog.cpp.
References max().
Referenced by LasIOFilter::loadFile().
timeShiftValue()
double LasOpenDialog::timeShiftValue () const
Returns quiet_NaN if the time shift value should be automatically found.
Otherwise, returns the value manually specified by the user.
Definition at line 169 of file LasOpenDialog.cpp.
Referenced by LasIOFilter::loadFile().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qLASIO/include/LasOpenDialog.h
/root/ACloudViewer/plugins/core/IO/qLASIO/src/LasOpenDialog.cpp