ACloudViewer: NormDipAndDipDirFieldWrapper Class Reference
NormDipAndDipDirFieldWrapper Class Reference
#include <ScalarFieldWrappers.h>
Public Types
enum Mode { Dip = 0 , DipDir = 1 }
Public Types inherited from IScalarFieldWrapper
using Shared = QSharedPointer< IScalarFieldWrapper >
Public Member Functions
NormDipAndDipDirFieldWrapper (const ccPointCloud *cloud, Mode mode)
virtual double pointValue (unsigned index) const override
virtual bool isValid () const
virtual QString getName () const
virtual size_t size () const override
Public Member Functions inherited from IScalarFieldWrapper
virtual ~IScalarFieldWrapper ()
Protected Attributes
const ccPointCloud * m_cloud
Mode m_mode
Detailed Description
Definition at line 89 of file ScalarFieldWrappers.h.
Member Enumeration Documentation
Mode
enum NormDipAndDipDirFieldWrapper::Mode
Enumerator
Dip
DipDir
Definition at line 91 of file ScalarFieldWrappers.h.
Constructor & Destructor Documentation
NormDipAndDipDirFieldWrapper()
NormDipAndDipDirFieldWrapper::NormDipAndDipDirFieldWrapper (const ccPointCloud * cloud, Mode mode) inline
Definition at line 93 of file ScalarFieldWrappers.h.
Member Function Documentation
getName()
virtual QString NormDipAndDipDirFieldWrapper::getName () const inline virtual
Implements IScalarFieldWrapper.
Definition at line 105 of file ScalarFieldWrappers.h.
References m_mode.
isValid()
virtual bool NormDipAndDipDirFieldWrapper::isValid () const inline virtual
Implements IScalarFieldWrapper.
Definition at line 102 of file ScalarFieldWrappers.h.
References ccPointCloud::hasNormals(), and m_cloud.
pointValue()
virtual double NormDipAndDipDirFieldWrapper::pointValue (unsigned index) const inline override virtual
Implements IScalarFieldWrapper.
Definition at line 96 of file ScalarFieldWrappers.h.
References ccNormalVectors::ConvertNormalToDipAndDipDir(), Dip, ccPointCloud::getPointNormal(), m_cloud, and m_mode.
size()
virtual size_t NormDipAndDipDirFieldWrapper::size (void) const inline override virtual
Implements IScalarFieldWrapper.
Definition at line 109 of file ScalarFieldWrappers.h.
References m_cloud, and cloudViewer::PointCloudTpl< T >::size().
Member Data Documentation
m_cloud
const ccPointCloud* NormDipAndDipDirFieldWrapper::m_cloud protected
Definition at line 112 of file ScalarFieldWrappers.h.
Referenced by isValid(), pointValue(), and size().
m_mode
Mode NormDipAndDipDirFieldWrapper::m_mode protected
Definition at line 113 of file ScalarFieldWrappers.h.
Referenced by getName(), and pointValue().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/q3DMASC/ScalarFieldWrappers.h