ACloudViewer: QCPLayerable Class Reference
QCPLayerable Class Reference abstract
Base class for all drawable objects.
#include <qcustomplot.h>
Signals
void layerChanged (QCPLayer *newLayer)
void layerChanged (QCPLayer *newLayer)
Public Member Functions
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
virtual ~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
bool realVisibility () const
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
bool realVisibility () const
Protected Member Functions
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const =0
virtual void draw (QCPPainter *painter)=0
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual void mousePressEvent (QMouseEvent *event, const QVariant &details)
virtual void mouseMoveEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseReleaseEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseDoubleClickEvent (QMouseEvent *event, const QVariant &details)
virtual void wheelEvent (QWheelEvent *event)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const =0
virtual void draw (QCPPainter *painter)=0
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Detailed Description
Base class for all drawable objects.
This is the abstract base class most visible objects derive from, e.g. plottables, axes, grid etc.
Every layerable is on a layer (QCPLayer) which allows controlling the rendering order by stacking the layers accordingly.
For details about the layering mechanism, see the QCPLayer documentation.
Definition at line 887 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPLayerable() [1/2]
QCPLayerable::QCPLayerable (QCustomPlot * plot, QString targetLayer = QString(), QCPLayerable * parentLayerable = 0)
Creates a new QCPLayerable instance.
Since QCPLayerable is an abstract base class, it can't be instantiated directly. Use one of the derived classes.
If plot is provided, it automatically places itself on the layer named targetLayer. If targetLayer is an empty string, it places itself on the current layer of the plot (see QCustomPlot::setCurrentLayer).
It is possible to provide 0 as plot. In that case, you should assign a parent plot at a later time with initializeParentPlot.
The layerable's parent layerable is set to parentLayerable, if provided. Direct layerable parents are mainly used to control visibility in a hierarchy of layerables. This means a layerable is only drawn, if all its ancestor layerables are also visible. Note that parentLayerable does not become the QObject-parent (for memory management) of this layerable, plot does. It is not uncommon to set the QObject-parent to something else in the constructors of QCPLayerable subclasses, to guarantee a working destruction hierarchy.
Creates a new QCPLayerable instance.
Since QCPLayerable is an abstract base class, it can't be instantiated directly. Use one of the derived classes.
If plot is provided, it automatically places itself on the layer named targetLayer. If targetLayer is an empty string, it places itself on the current layer of the plot (see QCustomPlot::setCurrentLayer).
It is possible to provide 0 as plot. In that case, you should assign a parent plot at a later time with initializeParentPlot.
The layerable's parent layerable is set to parentLayerable, if provided. Direct layerable parents are mainly used to control visibility in a hierarchy of layerables. This means a layerable is only drawn, if all its ancestor layerables are also visible. Note that parentLayerable does not become the QObject-parent (for memory management) of this layerable, plot does.
Definition at line 1300 of file qcustomplot.cpp.
References QCustomPlot::currentLayer(), mParentPlot, and setLayer().
~QCPLayerable() [1/2]
QCPLayerable::~QCPLayerable () virtual
Definition at line 1318 of file qcustomplot.cpp.
References mLayer, and QCPLayer::removeChild().
QCPLayerable() [2/2]
QCPLayerable::QCPLayerable (QCustomPlot * plot, QString targetLayer = QString(), QCPLayerable * parentLayerable = 0)
~QCPLayerable() [2/2]
QCPLayerable::~QCPLayerable ()
Member Function Documentation
antialiased() [1/2]
bool QCPLayerable::antialiased () const inline
Definition at line 907 of file qcustomplot.h.
antialiased() [2/2]
bool QCPLayerable::antialiased () const inline
Definition at line 592 of file qcustomplot.h.
applyAntialiasingHint() [1/2]
void QCPLayerable::applyAntialiasingHint (QCPPainter * painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const protected
Definition at line 1526 of file qcustomplot.cpp.
References QCustomPlot::antialiasedElements(), mParentPlot, QCustomPlot::notAntialiasedElements(), and QCPPainter::setAntialiasing().
Referenced by QCPSelectionRect::applyDefaultAntialiasingHint(), QCPGrid::applyDefaultAntialiasingHint(), QCPAxis::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractItem::applyDefaultAntialiasingHint(), QCPAbstractLegendItem::applyDefaultAntialiasingHint(), QCPLegend::applyDefaultAntialiasingHint(), QCPTextElement::applyDefaultAntialiasingHint(), QCPPlotTitle::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyErrorBarsAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPGrid::drawGridLines(), QCPStatisticalBox::drawStatisticalBox(), and QCPGrid::drawSubGridLines().
applyAntialiasingHint() [2/2]
void QCPLayerable::applyAntialiasingHint (QCPPainter * painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const protected
applyDefaultAntialiasingHint() [1/2]
virtual void QCPLayerable::applyDefaultAntialiasingHint (QCPPainter * painter) const protected pure virtual
Implemented in QCPColorScale, QCPPlotTitle, QCPLegend, QCPAbstractLegendItem, QCPAxisRect, QCPAbstractItem, QCPAbstractPlottable, QCPAxis, QCPGrid, QCPLayoutElement, QCPColorScale, QCPTextElement, QCPLegend, QCPAbstractLegendItem, QCPAxisRect, QCPAbstractItem, QCPAbstractPlottable, QCPAxis, QCPGrid, QCPLayoutElement, and QCPSelectionRect.
Referenced by QCPLayer::draw().
applyDefaultAntialiasingHint() [2/2]
virtual void QCPLayerable::applyDefaultAntialiasingHint (QCPPainter * painter) const protected pure virtual
Implemented in QCPColorScale, QCPPlotTitle, QCPLegend, QCPAbstractLegendItem, QCPAxisRect, QCPAbstractItem, QCPAbstractPlottable, QCPAxis, QCPGrid, QCPLayoutElement, QCPColorScale, QCPTextElement, QCPLegend, QCPAbstractLegendItem, QCPAxisRect, QCPAbstractItem, QCPAbstractPlottable, QCPAxis, QCPGrid, QCPLayoutElement, and QCPSelectionRect.
clipRect() [1/2]
QRect QCPLayerable::clipRect () const protected virtual
Reimplemented in QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, QCPAbstractLegendItem, QCPAbstractItem, and QCPAbstractPlottable.
Definition at line 1585 of file qcustomplot.cpp.
References mParentPlot, and QCustomPlot::viewport().
Referenced by QCPLayer::draw().
clipRect() [2/2]
virtual QRect QCPLayerable::clipRect () const protected virtual
Reimplemented in QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, QCPAbstractLegendItem, QCPAbstractItem, and QCPAbstractPlottable.
deselectEvent() [1/2]
void QCPLayerable::deselectEvent (bool * selectionStateChanged) protected virtual
Reimplemented in QCPPlotTitle, QCPLegend, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, QCPAxis, QCPTextElement, QCPLegend, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, and QCPAxis.
Definition at line 1647 of file qcustomplot.cpp.
Referenced by QCustomPlot::deselectAll(), QCustomPlot::processPointSelection(), and QCustomPlot::processRectSelection().
deselectEvent() [2/2]
virtual void QCPLayerable::deselectEvent (bool * selectionStateChanged) protected virtual
Reimplemented in QCPPlotTitle, QCPLegend, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, QCPAxis, QCPTextElement, QCPLegend, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, and QCPAxis.
draw() [1/2]
virtual void QCPLayerable::draw (QCPPainter * painter) protected pure virtual
Implemented in QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, QCPBarsWithText, QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, QCPItemStraightLine, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPPlotTitle, QCPLegend, QCPPlottableLegendItem, QCPAxisRect, QCPAxis, QCPGrid, QCPLayoutElement, QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, QCPItemStraightLine, QCPErrorBars, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPTextElement, QCPLegend, QCPPlottableLegendItem, QCPAxisRect, QCPAxis, QCPGrid, QCPLayoutElement, QCPSelectionRect, QCPArrow, QCPHiddenArea, QCPColoredBars, and QCPBarsWithText.
Referenced by QCPLayer::draw().
draw() [2/2]
virtual void QCPLayerable::draw (QCPPainter * painter) protected pure virtual
Implemented in QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, QCPBarsWithText, QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, QCPItemStraightLine, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPPlotTitle, QCPLegend, QCPPlottableLegendItem, QCPAxisRect, QCPAxis, QCPGrid, QCPLayoutElement, QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, QCPItemStraightLine, QCPErrorBars, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPTextElement, QCPLegend, QCPPlottableLegendItem, QCPAxisRect, QCPAxis, QCPGrid, QCPLayoutElement, QCPSelectionRect, QCPArrow, QCPHiddenArea, QCPColoredBars, and QCPBarsWithText.
initializeParentPlot() [1/2]
void QCPLayerable::initializeParentPlot (QCustomPlot * parentPlot) protected
Definition at line 1462 of file qcustomplot.cpp.
References mParentPlot, parentPlot(), and parentPlotInitialized().
Referenced by QCPLayout::adoptElement(), QCPLayoutElement::parentPlotInitialized(), QCPAxisRect::QCPAxisRect(), and QCustomPlot::QCustomPlot().
initializeParentPlot() [2/2]
void QCPLayerable::initializeParentPlot (QCustomPlot * parentPlot) protected
layer() [1/2]
QCPLayer* QCPLayerable::layer () const inline
Definition at line 906 of file qcustomplot.h.
Referenced by QCustomPlot::addPlottable(), QCPSelectionRect::moveSelection(), moveToLayer(), QCustomPlot::processRectSelection(), QCustomPlot::registerItem(), QCustomPlot::registerPlottable(), and setLayer().
layer() [2/2]
QCPLayer* QCPLayerable::layer () const inline
Definition at line 591 of file qcustomplot.h.
layerChanged [1/2]
void QCPLayerable::layerChanged (QCPLayer * newLayer) signal
This signal is emitted when the layer of this layerable changes, i.e. this layerable is moved to a different layer.
See also
setLayer
Referenced by moveToLayer().
layerChanged [2/2]
void QCPLayerable::layerChanged (QCPLayer * newLayer) signal
mouseDoubleClickEvent()
void QCPLayerable::mouseDoubleClickEvent (QMouseEvent * event, const QVariant & details) protected virtual
This event gets called when the user presses the mouse button a second time in a double-click, while the cursor is over the layerable. Whether a cursor is over the layerable is decided by a preceding call to selectTest.
The mouseDoubleClickEvent is called instead of the second mousePressEvent. So in the case of a double-click, the event succession is pressEvent – releaseEvent – doubleClickEvent – releaseEvent.
The current pixel position of the cursor on the QCustomPlot widget is accessible via event->pos(). The parameter details contains layerable-specific details about the hit, which were generated in the previous call to selectTest. For example, One-dimensional plottables like QCPGraph or QCPBars convey the clicked data point in the details parameter, as QCPDataSelection packed as QVariant. Multi-part objects convey the specific SelectablePart that was hit (e.g. QCPAxis::SelectablePart in the case of axes).
Similarly to mousePressEvent, once a layerable has accepted the mouseDoubleClickEvent, it is considered the mouse grabber and will receive all following calls to mouseMoveEvent and mouseReleaseEvent for this mouse interaction (a "mouse interaction" in this context ends with the release).
The default implementation does nothing except explicitly ignoring the event with event->ignore().
See also
mousePressEvent, mouseMoveEvent, mouseReleaseEvent, wheelEvent
Reimplemented in QCPTextElement.
Definition at line 1755 of file qcustomplot.cpp.
mouseMoveEvent()
void QCPLayerable::mouseMoveEvent (QMouseEvent * event, const QPointF & startPos) protected virtual
This event gets called when the user moves the mouse while holding a mouse button, after this layerable has become the mouse grabber by accepting the preceding mousePressEvent.
The current pixel position of the cursor on the QCustomPlot widget is accessible via event->pos(). The parameter startPos indicates the position where the initial mousePressEvent occured, that started the mouse interaction.
The default implementation does nothing.
See also
mousePressEvent, mouseReleaseEvent, mouseDoubleClickEvent, wheelEvent
Reimplemented in QCPColorScale, QCPAxisRect, and QCPAxis.
Definition at line 1700 of file qcustomplot.cpp.
mousePressEvent()
void QCPLayerable::mousePressEvent (QMouseEvent * event, const QVariant & details) protected virtual
This event gets called when the user presses a mouse button while the cursor is over the layerable. Whether a cursor is over the layerable is decided by a preceding call to selectTest.
The current pixel position of the cursor on the QCustomPlot widget is accessible via event->pos(). The parameter details contains layerable-specific details about the hit, which were generated in the previous call to selectTest. For example, One-dimensional plottables like QCPGraph or QCPBars convey the clicked data point in the details parameter, as QCPDataSelection packed as QVariant. Multi-part objects convey the specific SelectablePart that was hit (e.g. QCPAxis::SelectablePart in the case of axes).
QCustomPlot uses an event propagation system that works the same as Qt's system. If your layerable doesn't reimplement the mousePressEvent or explicitly calls event->ignore() in its reimplementation, the event will be propagated to the next layerable in the stacking order.
Once a layerable has accepted the mousePressEvent, it is considered the mouse grabber and will receive all following calls to mouseMoveEvent or mouseReleaseEvent for this mouse interaction (a "mouse interaction" in this context ends with the release).
The default implementation does nothing except explicitly ignoring the event with event->ignore().
See also
mouseMoveEvent, mouseReleaseEvent, mouseDoubleClickEvent, wheelEvent
Reimplemented in QCPColorScale, QCPTextElement, QCPAxisRect, and QCPAxis.
Definition at line 1680 of file qcustomplot.cpp.
mouseReleaseEvent()
void QCPLayerable::mouseReleaseEvent (QMouseEvent * event, const QPointF & startPos) protected virtual
This event gets called when the user releases the mouse button, after this layerable has become the mouse grabber by accepting the preceding mousePressEvent.
The current pixel position of the cursor on the QCustomPlot widget is accessible via event->pos(). The parameter startPos indicates the position where the initial mousePressEvent occured, that started the mouse interaction.
The default implementation does nothing.
See also
mousePressEvent, mouseMoveEvent, mouseDoubleClickEvent, wheelEvent
Reimplemented in QCPColorScale, QCPTextElement, QCPAxisRect, and QCPAxis.
Definition at line 1719 of file qcustomplot.cpp.
moveToLayer() [1/2]
bool QCPLayerable::moveToLayer (QCPLayer * layer, bool prepend) protected
Definition at line 1499 of file qcustomplot.cpp.
References QCPLayer::addChild(), layer(), layerChanged(), mLayer, mParentPlot, QCPLayer::name(), QCPLayer::parentPlot(), and QCPLayer::removeChild().
Referenced by setLayer().
moveToLayer() [2/2]
bool QCPLayerable::moveToLayer (QCPLayer * layer, bool prepend) protected
parentLayerable() [1/2]
QCPLayerable * QCPLayerable::parentLayerable () const inline
Returns the parent layerable of this layerable. The parent layerable is used to provide visibility hierarchies in conjunction with the method realVisibility. This way, layerables only get drawn if their parent layerables are visible, too.
Note that a parent layerable is not necessarily also the QObject parent for memory management. Further, a layerable doesn't always have a parent layerable, so this function may return 0.
A parent layerable is set implicitly when placed inside layout elements and doesn't need to be set manually by the user.
Returns the parent layerable of this layerable. The parent layerable is used to provide visibility hierarchies in conjunction with the method realVisibility. This way, layerables only get drawn if their parent layerables are visible, too.
Note that a parent layerable is not necessarily also the QObject parent for memory management. Further, a layerable doesn't always have a parent layerable, so this function may return 0.
A parent layerable is set implicitly with when placed inside layout elements and doesn't need to be set manually by the user.
Definition at line 905 of file qcustomplot.h.
Referenced by setParentLayerable().
parentLayerable() [2/2]
QCPLayerable* QCPLayerable::parentLayerable () const inline
Definition at line 590 of file qcustomplot.h.
parentPlot() [1/2]
QCustomPlot* QCPLayerable::parentPlot () const inline
Definition at line 904 of file qcustomplot.h.
Referenced by QCustomPlot::addGraph(), QCustomPlot::addItem(), QCustomPlot::addPlottable(), QCPAbstractPlottable::addToLegend(), QCPLayout::adoptElement(), initializeParentPlot(), parentPlotInitialized(), QCPLayoutElement::parentPlotInitialized(), QCPLegend::parentPlotInitialized(), QCPAbstractItem::QCPAbstractItem(), QCPAbstractPlottable::QCPAbstractPlottable(), QCPPlotTitle::QCPPlotTitle(), QCPTextElement::QCPTextElement(), QCustomPlot::registerItem(), QCustomPlot::registerPlottable(), QCPAxisRect::removeAxis(), and QCPItemTracer::setGraph().
parentPlot() [2/2]
QCustomPlot* QCPLayerable::parentPlot () const inline
Definition at line 589 of file qcustomplot.h.
parentPlotInitialized() [1/2]
void QCPLayerable::parentPlotInitialized (QCustomPlot * parentPlot) protected virtual
Reimplemented in QCPLegend, QCPLayoutElement, QCPLegend, and QCPLayoutElement.
Definition at line 1557 of file qcustomplot.cpp.
References parentPlot().
Referenced by initializeParentPlot().
parentPlotInitialized() [2/2]
virtual void QCPLayerable::parentPlotInitialized (QCustomPlot * parentPlot) protected virtual
Reimplemented in QCPLegend, QCPLayoutElement, QCPLegend, and QCPLayoutElement.
realVisibility() [1/2]
bool QCPLayerable::realVisibility () const
Returns whether this layerable is visible, taking the visibility of the layerable parent and the visibility of this layerable's layer into account. This is the method that is consulted to decide whether a layerable shall be drawn or not.
If this layerable has a direct layerable parent (usually set via hierarchies implemented in subclasses, like in the case of QCPLayoutElement), this function returns true only if this layerable has its visibility set to true and the parent layerable's realVisibility returns true.
Returns whether this layerable is visible, taking the visibility of the layerable parent and the visibility of the layer this layerable is on into account. This is the method that is consulted to decide whether a layerable shall be drawn or not.
If this layerable has a direct layerable parent (usually set via hierarchies implemented in subclasses, like in the case of QCPLayoutElement), this function returns true only if this layerable has its visibility set to true and the parent layerable's realVisibility returns true.
If this layerable doesn't have a direct layerable parent, returns the state of this layerable's visibility.
Definition at line 1384 of file qcustomplot.cpp.
References mLayer, mParentLayerable, mVisible, and QCPLayer::visible().
Referenced by QCustomPlot::axisRectAt(), QCPLayer::draw(), and QCustomPlot::layoutElementAt().
realVisibility() [2/2]
bool QCPLayerable::realVisibility () const
selectEvent() [1/2]
void QCPLayerable::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) protected virtual
Reimplemented in QCPPlotTitle, QCPLegend, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, QCPAxis, QCPTextElement, QCPLegend, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, and QCPAxis.
Definition at line 1625 of file qcustomplot.cpp.
References event.
Referenced by QCustomPlot::processPointSelection().
selectEvent() [2/2]
virtual void QCPLayerable::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) protected virtual
Reimplemented in QCPPlotTitle, QCPLegend, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, QCPAxis, QCPTextElement, QCPLegend, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, and QCPAxis.
selectionCategory() [1/2]
QCP::Interaction QCPLayerable::selectionCategory () const protected virtual
Reimplemented in QCPLegend, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, QCPAxis, QCPLegend, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, and QCPAxis.
Definition at line 1572 of file qcustomplot.cpp.
References QCP::iSelectOther.
Referenced by QCustomPlot::processPointSelection(), and QCustomPlot::processRectSelection().
selectionCategory() [2/2]
virtual QCP::Interaction QCPLayerable::selectionCategory () const protected virtual
Reimplemented in QCPLegend, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, QCPAxis, QCPLegend, QCPAbstractLegendItem, QCPAbstractItem, QCPAbstractPlottable, and QCPAxis.
selectTest() [1/2]
double QCPLayerable::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Reimplemented in QCPSelectableCursor, QCPAbstractItem, QCPAbstractPlottable, QCPAbstractItem, QCPAbstractPlottable, QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, QCPItemStraightLine, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPPlotTitle, QCPLegend, QCPAbstractLegendItem, QCPAxis, QCPLayoutInset, QCPLayoutElement, QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, QCPItemStraightLine, QCPErrorBars, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPTextElement, QCPLegend, QCPAbstractLegendItem, QCPAbstractPlottable1D< DataType >, QCPAbstractPlottable1D< QCPFinancialData >, QCPAbstractPlottable1D< QCPStatisticalBoxData >, QCPAbstractPlottable1D< QCPGraphData >, QCPAbstractPlottable1D< QCPBarsData >, QCPAbstractPlottable1D< QCPCurveData >, QCPAxis, QCPLayoutInset, and QCPLayoutElement.
Definition at line 1435 of file qcustomplot.cpp.
selectTest() [2/2]
virtual double QCPLayerable::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
Reimplemented in QCPSelectableCursor, QCPAbstractItem, QCPAbstractPlottable, QCPAbstractItem, QCPAbstractPlottable, QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, QCPItemStraightLine, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPPlotTitle, QCPLegend, QCPAbstractLegendItem, QCPAxis, QCPLayoutInset, QCPLayoutElement, QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, QCPItemStraightLine, QCPErrorBars, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPTextElement, QCPLegend, QCPAbstractLegendItem, QCPAbstractPlottable1D< DataType >, QCPAbstractPlottable1D< QCPFinancialData >, QCPAbstractPlottable1D< QCPStatisticalBoxData >, QCPAbstractPlottable1D< QCPGraphData >, QCPAbstractPlottable1D< QCPBarsData >, QCPAbstractPlottable1D< QCPCurveData >, QCPAxis, QCPLayoutInset, and QCPLayoutElement.
setAntialiased() [1/2]
void QCPLayerable::setAntialiased (bool enabled)
Sets whether this object will be drawn antialiased or not.
Note that antialiasing settings may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 1371 of file qcustomplot.cpp.
References mAntialiased.
Referenced by AnglesCustomPlot::createQCPBars(), QCPAxis::QCPAxis(), QCPGrid::QCPGrid(), QCPLegend::QCPLegend(), QCPPlottableLegendItem::QCPPlottableLegendItem(), ccHistogramWindow::refresh(), and WolmanCustomPlot::WolmanCustomPlot().
setAntialiased() [2/2]
void QCPLayerable::setAntialiased (bool enabled)
setLayer() [1/4]
bool QCPLayerable::setLayer (const QString & layerName)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets the layer of this layerable object by name
Returns true on success, i.e. if layerName is a valid layer name.
Definition at line 1351 of file qcustomplot.cpp.
References layer(), QCustomPlot::layer(), mParentPlot, and setLayer().
setLayer() [2/4]
bool QCPLayerable::setLayer (const QString & layerName)
setLayer() [3/4]
bool QCPLayerable::setLayer (QCPLayer * layer)
Sets the layer of this layerable object. The object will be placed on top of the other objects already on layer.
If layer is 0, this layerable will not be on any layer and thus not appear in the plot (or interact/receive events).
Returns true if the layer of this layerable was successfully changed to layer.
Sets the layer of this layerable object. The object will be placed on top of the other objects already on layer.
Returns true on success, i.e. if layer is a valid layer.
Definition at line 1342 of file qcustomplot.cpp.
References layer(), and moveToLayer().
Referenced by QCustomPlot::addPlottable(), QCPAbstractLegendItem::QCPAbstractLegendItem(), QCPAxis::QCPAxis(), QCPLayerable(), QCPPlotTitle::QCPPlotTitle(), QCustomPlot::QCustomPlot(), QCustomPlot::registerItem(), QCustomPlot::registerPlottable(), and setLayer().
setLayer() [4/4]
Q_SLOT bool QCPLayerable::setLayer (QCPLayer * layer)
setParentLayerable() [1/2]
void QCPLayerable::setParentLayerable (QCPLayerable * parentLayerable) protected
Definition at line 1487 of file qcustomplot.cpp.
References mParentLayerable, and parentLayerable().
Referenced by QCPLayout::adoptElement(), QCPAxisRect::QCPAxisRect(), QCPLayout::releaseElement(), QCPAbstractItem::setClipAxisRect(), and QCPAbstractItem::setClipToAxisRect().
setParentLayerable() [2/2]
void QCPLayerable::setParentLayerable (QCPLayerable * parentLayerable) protected
setVisible() [1/2]
void QCPLayerable::setVisible (bool on)
Sets the visibility of this layerable object. If an object is not visible, it will not be drawn on the QCustomPlot surface, and user interaction with it (e.g. click and selection) is not possible.
Definition at line 1330 of file qcustomplot.cpp.
References mVisible.
Referenced by cvProbeFilter::createUi(), QCPItemEllipse::draw(), QCPAxis::QCPAxis(), QCPAxisRect::QCPAxisRect(), QCustomPlot::QCustomPlot(), ccHistogramWindow::refresh(), ccHistogramWindow::setAxisLabels(), ccWaveWidget::setAxisLabels(), and QCPAxisRect::setupFullAxesBox().
setVisible() [2/2]
void QCPLayerable::setVisible (bool on)
visible() [1/2]
bool QCPLayerable::visible () const inline
Definition at line 903 of file qcustomplot.h.
Referenced by QCPGrid::setSubGridVisible(), and QCPAxis::setupTickVectors().
visible() [2/2]
bool QCPLayerable::visible () const inline
Definition at line 588 of file qcustomplot.h.
wheelEvent()
void QCPLayerable::wheelEvent (QWheelEvent * event) protected virtual
This event gets called when the user turns the mouse scroll wheel while the cursor is over the layerable. Whether a cursor is over the layerable is decided by a preceding call to selectTest.
The current pixel position of the cursor on the QCustomPlot widget is accessible via event->pos().
The event->delta() indicates how far the mouse wheel was turned, which is usually +/- 120 for single rotation steps. However, if the mouse wheel is turned rapidly, multiple steps may accumulate to one event, making event->delta() larger. On the other hand, if the wheel has very smooth steps or none at all, the delta may be smaller.
The default implementation does nothing.
See also
mousePressEvent, mouseMoveEvent, mouseReleaseEvent, mouseDoubleClickEvent
Reimplemented in QCPColorScale, QCPAxisRect, QCPLayoutElement, QCPColorScale, QCPAxisRect, and QCPAxis.
Definition at line 1779 of file qcustomplot.cpp.
Referenced by QCustomPlot::wheelEvent().
Member Data Documentation
mAntialiased
bool QCPLayerable::mAntialiased protected
Definition at line 932 of file qcustomplot.h.
Referenced by QCPSelectionRect::applyDefaultAntialiasingHint(), QCPGrid::applyDefaultAntialiasingHint(), QCPAxis::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractItem::applyDefaultAntialiasingHint(), QCPAbstractLegendItem::applyDefaultAntialiasingHint(), QCPLegend::applyDefaultAntialiasingHint(), QCPTextElement::applyDefaultAntialiasingHint(), QCPPlotTitle::applyDefaultAntialiasingHint(), and setAntialiased().
mLayer
QCPLayer * QCPLayerable::mLayer protected
Definition at line 931 of file qcustomplot.h.
Referenced by moveToLayer(), realVisibility(), and ~QCPLayerable().
mParentLayerable
QPointer< QCPLayerable > QCPLayerable::mParentLayerable protected
Definition at line 930 of file qcustomplot.h.
Referenced by realVisibility(), and setParentLayerable().
mParentPlot
QCustomPlot * QCPLayerable::mParentPlot protected
Definition at line 929 of file qcustomplot.h.
Referenced by QCPAxisRect::addAxis(), QCPAbstractPlottable::addToLegend(), QCPLayout::adoptElement(), applyAntialiasingHint(), QCPAxis::calculateMargin(), QCPFinancial::candlestickSelectTest(), clipRect(), QCPAbstractItem::clipRect(), QCPColorScale::colorMaps(), QCPAbstractItem::createAnchor(), QCPAbstractItem::createPosition(), QCPAxis::draw(), QCPGraph::drawLinePlot(), QCPAxis::graphs(), QCPAxisRect::graphs(), initializeParentPlot(), QCPAxis::items(), QCPAxisRect::items(), QCPAxisRect::layoutChanged(), QCPAxis::mouseMoveEvent(), QCPAxisRect::mouseMoveEvent(), QCPAxis::mousePressEvent(), QCPAxisRect::mousePressEvent(), QCPAxis::mouseReleaseEvent(), QCPAxisRect::mouseReleaseEvent(), moveToLayer(), QCPAxis::plottables(), QCPAxisRect::plottables(), QCPCurve::pointDistance(), QCPGraph::pointDistance(), QCPAbstractPlottable::QCPAbstractPlottable(), QCPAxis::QCPAxis(), QCPAxisRect::QCPAxisRect(), QCPGraph::QCPGraph(), QCPLayerable(), QCPAbstractItem::rectDistance(), QCPAbstractItem::rectSelectTest(), QCPLayout::releaseElement(), QCPAbstractPlottable::removeFromLegend(), QCPLayoutElement::selectTest(), QCPLayoutInset::selectTest(), QCPAxis::selectTest(), QCPAbstractLegendItem::selectTest(), QCPLegend::selectTest(), QCPTextElement::selectTest(), QCPBars::selectTest(), QCPStatisticalBox::selectTest(), QCPColorMap::selectTest(), QCPItemEllipse::selectTest(), QCPItemTracer::selectTest(), QCPPlotTitle::selectTest(), QCPGraph::setChannelFillGraph(), QCPItemTracer::setGraph(), setLayer(), QCPAxis::setupTickVectors(), QCPItemTracer::updatePosition(), QCPAxis::wheelEvent(), QCPAxisRect::wheelEvent(), and QCPLegend::~QCPLegend().
mVisible
bool QCPLayerable::mVisible protected
Definition at line 928 of file qcustomplot.h.
Referenced by QCPAxis::calculateMargin(), QCPAxis::getPartAt(), realVisibility(), and setVisible().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp