ACloudViewer: cloudViewer::core::IsDevice Class Reference
cloudViewer::core::IsDevice Class Reference abstract
#include <Device.h>
Public Member Functions
IsDevice ()=default
virtual ~IsDevice ()=default
virtual core::Device GetDevice () const =0
bool IsCPU () const
bool IsCUDA () const
bool IsSYCL () const
Detailed Description
Abstract class to provide IsXXX() functionality to check device location. Need to implement GetDevice().
Definition at line 88 of file Device.h.
Constructor & Destructor Documentation
IsDevice()
cloudViewer::core::IsDevice::IsDevice () default
~IsDevice()
virtual cloudViewer::core::IsDevice::~IsDevice () virtual default
Member Function Documentation
GetDevice()
virtual core::Device cloudViewer::core::IsDevice::GetDevice () const pure virtual
Implemented in cloudViewer::t::geometry::PyGeometry< GeometryBase >, cloudViewer::t::geometry::TriangleMesh, cloudViewer::t::geometry::RGBDImage, cloudViewer::t::geometry::PointCloud, cloudViewer::t::geometry::LineSet, cloudViewer::t::geometry::Image, cloudViewer::t::geometry::OrientedBoundingBox, cloudViewer::t::geometry::AxisAlignedBoundingBox, cloudViewer::core::Tensor, cloudViewer::core::HashSet, cloudViewer::core::HashMap, and cloudViewer::t::geometry::Geometry.
Referenced by IsCPU(), IsCUDA(), and IsSYCL().
IsCPU()
bool cloudViewer::core::IsDevice::IsCPU () const inline
Definition at line 95 of file Device.h.
References cloudViewer::core::Device::CPU, GetDevice(), and cloudViewer::core::Device::GetType().
Referenced by cloudViewer::core::kernel::BinaryEW(), cloudViewer::t::geometry::PointCloud::ComputeBoundaryPoints(), cloudViewer::t::pipelines::kernel::ComputeFPFHFeature(), cloudViewer::t::pipelines::kernel::ComputeInformationMatrix(), cloudViewer::t::geometry::PointCloud::ComputeMetrics(), cloudViewer::t::geometry::TriangleMesh::ComputeMetrics(), cloudViewer::t::pipelines::kernel::ComputePoseColoredICP(), cloudViewer::t::pipelines::kernel::ComputePosePointToPlane(), cloudViewer::t::pipelines::kernel::ComputeRtPointToPoint(), cloudViewer::t::geometry::ComputeTriangleAreasHelper(), cloudViewer::t::geometry::TriangleMesh::ComputeTriangleNormals(), cloudViewer::t::geometry::TriangleMesh::ComputeVertexNormals(), cloudViewer::t::geometry::Image::Dilate(), cloudViewer::t::geometry::PointCloud::EstimateColorGradients(), cloudViewer::t::geometry::PointCloud::EstimateNormals(), cloudViewer::t::geometry::kernel::voxel_grid::EstimateRange(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractPointCloud(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractTriangleMesh(), cloudViewer::t::pipelines::kernel::FillInRigidAlignmentTerm(), cloudViewer::t::pipelines::kernel::FillInSLACAlignmentTerm(), cloudViewer::t::pipelines::kernel::FillInSLACRegularizerTerm(), cloudViewer::t::geometry::Image::Filter(), cloudViewer::t::geometry::Image::FilterBilateral(), cloudViewer::t::geometry::Image::FilterGaussian(), cloudViewer::t::geometry::Image::FilterSobel(), cloudViewer::t::geometry::kernel::pointcloud::GetPointMaskWithinAABB(), cloudViewer::t::geometry::kernel::pointcloud::GetPointMaskWithinOBB(), cloudViewer::t::geometry::kernel::voxel_grid::GetVoxelCoordinatesAndFlattenedIndices(), cloudViewer::core::kernel::IndexAdd_(), cloudViewer::core::kernel::IndexGet(), cloudViewer::core::kernel::IndexSet(), cloudViewer::t::geometry::kernel::voxel_grid::Integrate(), cloudViewer::core::kernel::NonZero(), cloudViewer::t::geometry::PointCloud::NormalizeNormals(), cloudViewer::t::geometry::TriangleMesh::NormalizeNormals(), cloudViewer::t::geometry::PointCloud::OrientNormalsToAlignWithDirection(), cloudViewer::t::geometry::PointCloud::OrientNormalsTowardsCameraLocation(), cloudViewer::t::geometry::kernel::pointcloud::Project(), cloudViewer::t::geometry::TriangleMesh::ProjectImagesToAlbedo(), cloudViewer::core::pybind_core_hashmap(), cloudViewer::core::pybind_core_hashset(), cloudViewer::core::pybind_core_tensor(), cloudViewer::t::geometry::pybind_geometry_class(), cloudViewer::t::geometry::pybind_image(), cloudViewer::core::kernel::Reduction(), cloudViewer::t::geometry::Image::Resize(), cloudViewer::t::geometry::Image::RGBToGray(), cloudViewer::t::geometry::TriangleMesh::SamplePointsUniformly(), cloudViewer::core::TensorToPyArray(), cloudViewer::t::geometry::Image::To(), and cloudViewer::t::geometry::kernel::pointcloud::Unproject().
IsCUDA()
bool cloudViewer::core::IsDevice::IsCUDA () const inline
Definition at line 99 of file Device.h.
References cloudViewer::core::Device::CUDA, GetDevice(), and cloudViewer::core::Device::GetType().
Referenced by cloudViewer::core::kernel::BinaryEW(), cloudViewer::t::geometry::PointCloud::ComputeBoundaryPoints(), cloudViewer::t::pipelines::kernel::ComputeInformationMatrix(), cloudViewer::t::pipelines::kernel::ComputePoseColoredICP(), cloudViewer::t::pipelines::kernel::ComputePosePointToPlane(), cloudViewer::t::pipelines::kernel::ComputeRtPointToPoint(), cloudViewer::t::geometry::ComputeTriangleAreasHelper(), cloudViewer::t::geometry::TriangleMesh::ComputeTriangleNormals(), cloudViewer::t::geometry::TriangleMesh::ComputeVertexNormals(), cloudViewer::t::geometry::CreatePointCloudWithNormals(), cloudViewer::t::geometry::Image::Dilate(), cloudViewer::t::geometry::PointCloud::EstimateColorGradients(), cloudViewer::t::geometry::PointCloud::EstimateNormals(), cloudViewer::t::geometry::kernel::voxel_grid::EstimateRange(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractPointCloud(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractTriangleMesh(), cloudViewer::t::pipelines::kernel::FillInRigidAlignmentTerm(), cloudViewer::t::pipelines::kernel::FillInSLACAlignmentTerm(), cloudViewer::t::pipelines::kernel::FillInSLACRegularizerTerm(), cloudViewer::t::geometry::Image::Filter(), cloudViewer::t::geometry::Image::FilterBilateral(), cloudViewer::t::geometry::Image::FilterGaussian(), cloudViewer::t::geometry::Image::FilterSobel(), cloudViewer::core::nns::NearestNeighborSearch::FixedRadiusIndex(), cloudViewer::core::nns::NearestNeighborSearch::FixedRadiusSearch(), cloudViewer::core::HashBackendBuffer::GetHeapTopIndex(), cloudViewer::t::geometry::kernel::pointcloud::GetPointMaskWithinAABB(), cloudViewer::t::geometry::kernel::pointcloud::GetPointMaskWithinOBB(), cloudViewer::t::geometry::kernel::voxel_grid::GetVoxelCoordinatesAndFlattenedIndices(), cloudViewer::core::nns::NearestNeighborSearch::HybridIndex(), cloudViewer::core::nns::NearestNeighborSearch::HybridSearch(), cloudViewer::core::kernel::IndexAdd_(), cloudViewer::core::kernel::IndexGet(), cloudViewer::core::kernel::IndexSet(), cloudViewer::t::geometry::kernel::voxel_grid::Integrate(), cloudViewer::core::nns::NearestNeighborSearch::KnnIndex(), cloudViewer::core::nns::NearestNeighborSearch::KnnSearch(), cloudViewer::core::kernel::NonZero(), cloudViewer::t::geometry::PointCloud::NormalizeNormals(), cloudViewer::t::geometry::TriangleMesh::NormalizeNormals(), cloudViewer::t::geometry::PointCloud::OrientNormalsToAlignWithDirection(), cloudViewer::t::geometry::PointCloud::OrientNormalsTowardsCameraLocation(), cloudViewer::t::geometry::kernel::pointcloud::Project(), cloudViewer::core::pybind_core_hashmap(), cloudViewer::core::pybind_core_hashset(), cloudViewer::core::pybind_core_tensor(), cloudViewer::t::geometry::pybind_geometry_class(), cloudViewer::core::kernel::Reduction(), cloudViewer::t::geometry::Image::Resize(), cloudViewer::t::geometry::Image::RGBToGray(), cloudViewer::core::nns::KnnIndex::SetTensorData(), cloudViewer::core::Tensor::ToString(), and cloudViewer::t::geometry::kernel::pointcloud::Unproject().
IsSYCL()
bool cloudViewer::core::IsDevice::IsSYCL () const inline
Definition at line 103 of file Device.h.
References GetDevice(), cloudViewer::core::Device::GetType(), and cloudViewer::core::Device::SYCL.
Referenced by cloudViewer::core::kernel::BinaryEW(), cloudViewer::core::kernel::CopySYCL(), cloudViewer::core::kernel::IndexAdd_(), cloudViewer::core::kernel::IndexGet(), cloudViewer::core::kernel::IndexSet(), cloudViewer::core::kernel::NonZero(), cloudViewer::core::kernel::Reduction(), and cloudViewer::core::Tensor::ToString().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/Device.h