ACloudViewer: cloudViewer::t::geometry::Geometry Class Reference
cloudViewer::t::geometry::Geometry Class Reference abstract
The base geometry class.
#include <Geometry.h>
Public Types
enum class GeometryType {
Unspecified = 0 , PointCloud = 1 , VoxelGrid = 2 , Octree = 3 ,
LineSet = 4 , MeshBase = 5 , TriangleMesh = 6 , HalfEdgeTriangleMesh = 7 ,
Image = 8 , RGBDImage = 9 , TetraMesh = 10 , OrientedBoundingBox = 11 ,
AxisAlignedBoundingBox = 12
}
Specifies possible geometry types.
Public Member Functions
virtual ~Geometry ()
virtual Geometry & Clear ()=0
Clear all elements in the geometry.
virtual bool IsEmpty () const =0
Returns true iff the geometry is empty.
virtual core::Device GetDevice () const =0
Returns the device of the geometry.
GeometryType GetGeometryType () const
Returns one of registered geometry types.
int Dimension () const
Returns whether the geometry is 2D or 3D.
std::string GetName () const
void SetName (const std::string &name)
Public Member Functions inherited from cloudViewer::core::IsDevice
IsDevice ()=default
virtual ~IsDevice ()=default
bool IsCPU () const
bool IsCUDA () const
bool IsSYCL () const
Protected Member Functions
Geometry (GeometryType type, int dimension)
Parameterized Constructor.
Detailed Description
The base geometry class.
Definition at line 23 of file Geometry.h.
Member Enumeration Documentation
GeometryType
enum cloudViewer::t::geometry::Geometry::GeometryType strong
Specifies possible geometry types.
Enumerator
Unspecified
Unspecified geometry type.
PointCloud
PointCloud.
VoxelGrid
VoxelGrid.
Octree
Octree.
LineSet
LineSet.
MeshBase
MeshBase.
TriangleMesh
TriangleMesh.
HalfEdgeTriangleMesh
HalfEdgeTriangleMesh.
Image
Image.
RGBDImage
RGBDImage.
TetraMesh
TetraMesh.
OrientedBoundingBox
OrientedBoundingBox.
AxisAlignedBoundingBox
AxisAlignedBoundingBox.
Definition at line 28 of file Geometry.h.
Constructor & Destructor Documentation
~Geometry()
virtual cloudViewer::t::geometry::Geometry::~Geometry () inline virtual
Definition at line 58 of file Geometry.h.
Geometry()
cloudViewer::t::geometry::Geometry::Geometry (GeometryType type, int dimension) inline protected
Parameterized Constructor.
Parameters
type Specifies the type of geometry of the object constructed.
dimension Specifies whether the dimension is 2D or 3D.
Definition at line 65 of file Geometry.h.
Member Function Documentation
Clear()
virtual Geometry& cloudViewer::t::geometry::Geometry::Clear () pure virtual
Clear all elements in the geometry.
Implemented in cloudViewer::t::geometry::TriangleMesh, cloudViewer::t::geometry::RGBDImage, cloudViewer::t::geometry::PointCloud, cloudViewer::t::geometry::LineSet, cloudViewer::t::geometry::Image, cloudViewer::t::geometry::OrientedBoundingBox, and cloudViewer::t::geometry::AxisAlignedBoundingBox.
Dimension()
int cloudViewer::t::geometry::Geometry::Dimension () const inline
Returns whether the geometry is 2D or 3D.
Definition at line 82 of file Geometry.h.
GetDevice()
virtual core::Device cloudViewer::t::geometry::Geometry::GetDevice () const pure virtual
Returns the device of the geometry.
Implements cloudViewer::core::IsDevice.
Implemented in cloudViewer::t::geometry::TriangleMesh, cloudViewer::t::geometry::RGBDImage, cloudViewer::t::geometry::PointCloud, cloudViewer::t::geometry::LineSet, cloudViewer::t::geometry::Image, cloudViewer::t::geometry::OrientedBoundingBox, and cloudViewer::t::geometry::AxisAlignedBoundingBox.
GetGeometryType()
GeometryType cloudViewer::t::geometry::Geometry::GetGeometryType () const inline
Returns one of registered geometry types.
Definition at line 79 of file Geometry.h.
Referenced by cloudViewer::t::geometry::vtkutils::CreateVtkPolyDataFromGeometry(), and cloudViewer::visualization::rendering::GeometryBuffersBuilder::GetBuilder().
GetName()
std::string cloudViewer::t::geometry::Geometry::GetName () const inline
Definition at line 84 of file Geometry.h.
IsEmpty()
virtual bool cloudViewer::t::geometry::Geometry::IsEmpty () const pure virtual
Returns true iff the geometry is empty.
Implemented in cloudViewer::t::geometry::TriangleMesh, cloudViewer::t::geometry::RGBDImage, cloudViewer::t::geometry::PointCloud, cloudViewer::t::geometry::LineSet, cloudViewer::t::geometry::Image, cloudViewer::t::geometry::OrientedBoundingBox, and cloudViewer::t::geometry::AxisAlignedBoundingBox.
Referenced by cloudViewer::visualization::rendering::FilamentScene::AddGeometry().
SetName()
void cloudViewer::t::geometry::Geometry::SetName (const std::string & name) inline
Definition at line 85 of file Geometry.h.
References name.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/t/geometry/Geometry.h