ACloudViewer: ProjectionFilter Class Reference
ProjectionFilter Class Reference
Projection Filter.
#include <ProjectionFilter.h>
Public Member Functions
ProjectionFilter ()
virtual ~ProjectionFilter ()
virtual int compute ()
Performs the actual filter job.
Public Member Functions inherited from BasePclModule
BasePclModule (PclModuleDescription desc=PclModuleDescription(), ccPluginInterface *parent_plugin=0)
Default constructor.
QAction * getAction ()
Get the action associated with the button used in menu and toolbar creation.
QString getStatusTip () const
Returns the status tip.
QString getModuleName () const
Returns the name of the filter.
QString getEntryName () const
Returns the entry name.
QIcon getIcon () const
Returns the icon associated with the button.
void setShowProgressBar (bool status)
Sets whether to show a progressbar while computing or not.
std::vector< std::string > getSelectedAvailableScalarFields ()
ccPointCloud * getSelectedEntityAsCCPointCloud () const
Returns the first selected entity as a ccPointCloud.
ccHObject * getSelectedEntityAsCCHObject () const
Returns the first selected entity as a ccHObject.
ccHObject::Container getSelectedThatHaveMetaData (const QString key) const
Get selected object that also have the provided metadata key.
void getAllEntitiesOfType (CV_CLASS_ENUM type, ccHObject::Container &entities)
Returns all the objects in db tree of type "type".
void getAllEntitiesThatHaveMetaData (QString key, ccHObject::Container &entities)
void getSelectedEntitiesThatAreCCPointCloud (ccHObject::Container &entities)
get all entities that are selected and that also are cc_point_cloud
void getSelectedEntitiesThatAre (CV_CLASS_ENUM kind, ccHObject::Container &entities)
int hasSelectedRGB ()
Returns 1 if the first selected entity has RGB info.
int hasSelectedScalarField ()
Returns 1 if the first selected entity has at least one scalar field.
int hasSelectedScalarField (std::string field_name)
int isFirstSelectedCcPointCloud ()
Returns 1 if the first selected object is a ccPointCloud.
virtual void updateSelectedEntities (const ccHObject::Container &selectedEntities)
Updates the internal copy of selected entities.
void setMainAppInterface (ecvMainAppInterface *app)
Sets associated CC application interface (to access DB)
ecvMainAppInterface * getMainAppInterface ()
ccPluginInterface * getParentPlugin () const
Returns the associated parent plugin interface.
Protected Member Functions
virtual int openInputDialog ()
virtual int checkParameters ()
virtual void getParametersFromDialog ()
Collects parameters from the filter dialog (if openDialog is successful)
virtual QString getErrorMessage (int errorCode)
Returns the error message corresponding to a given error code.
Protected Member Functions inherited from BasePclModule
virtual int checkSelected ()
Checks if current selection is compliant with the filter.
virtual int openOutputDialog ()
virtual int start ()
Starts computation.
virtual void initAction ()
Initializes the corresponding action.
void throwError (int errCode)
Protected Attributes
ProjectionFilterDlg * m_dialog
bool m_projectionMode
float m_coefficientA
float m_coefficientB
float m_coefficientC
float m_coefficientD
bool m_useVoxelGrid
float m_leafSize
bool m_useKnn
int m_knn_radius
float m_normalSearchRadius
float m_boundarySearchRadius
float m_boundaryAngleThreshold
Protected Attributes inherited from BasePclModule
QAction * m_action
Forces the Ui to be updated.
ccHObject::Container m_selected
Pointer to the main window.
PclModuleDescription m_desc
Associated dialog.
ecvMainAppInterface * m_app
Associated application interface.
ccPluginInterface * m_parent_plugin
associated parent plugin of the filter
bool m_show_progress
Do we want to show a progress bar when the filter works?
Additional Inherited Members
Signals inherited from BasePclModule
void entityHasChanged (ccHObject *)
Signal emitted when an entity is (visually) modified.
void newEntity (ccHObject *)
Signal emitted when a new entity is created by the filter.
void newErrorMessage (QString)
Signal emitted when a new error message is produced.
Protected Slots inherited from BasePclModule
int performAction ()
Returns is called when the dialog window is accepted.
Detailed Description
Projection Filter.
Definition at line 15 of file ProjectionFilter.h.
Constructor & Destructor Documentation
ProjectionFilter()
ProjectionFilter::ProjectionFilter ()
Definition at line 26 of file ProjectionFilter.cpp.
~ProjectionFilter()
ProjectionFilter::~ProjectionFilter () virtual
Definition at line 46 of file ProjectionFilter.cpp.
References m_dialog.
Member Function Documentation
checkParameters()
int ProjectionFilter::checkParameters () protected virtual
Checks that the parameters retrieved by getParametersFromDialog are valid Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Returns
1 if parameters are valid (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 91 of file ProjectionFilter.cpp.
compute()
int ProjectionFilter::compute () virtual
Performs the actual filter job.
This method MUST be re-implemented by derived filter
Returns
1 if successful (error code otherwise)
Implements BasePclModule.
Definition at line 93 of file ProjectionFilter.cpp.
References ccHObject::addChild(), PCLModules::ComputeNormals< PointT, NormalT >(), pcl2cc::Convert(), FROM_PCL_CLOUD, PCLModules::GetBoundaryCloud< PointT, NormalT >(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccObject::getName(), cc2smReader::getNormals(), ccHObject::getParent(), PCLModules::GetProjection(), BasePclModule::getSelectedEntityAsCCPointCloud(), cc2smReader::getXYZ2(), ccPointCloud::hasNormals(), m_boundaryAngleThreshold, m_boundarySearchRadius, m_coefficientA, m_coefficientB, m_coefficientC, m_coefficientD, m_knn_radius, m_leafSize, m_normalSearchRadius, m_projectionMode, m_useKnn, m_useVoxelGrid, name, BasePclModule::newEntity(), normals, ecvColor::Generator::Random(), result, ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccObject::setName(), ccPointCloud::setRGBColor(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), TO_PCL_CLOUD, and PCLModules::VoxelGridFilter< PointT >().
getErrorMessage()
QString ProjectionFilter::getErrorMessage (int errorCode) protected virtual
Returns the error message corresponding to a given error code.
Each filter have a set of possible error message to be used given bt getFilterErrorMessage() Baseclass implementation provides some generic messages.
Note
These messages can be replaced by re-implementing this method and handling the same codes BEFORE calling the baseclass method
Reimplemented from BasePclModule.
Definition at line 193 of file ProjectionFilter.cpp.
References BasePclModule::getErrorMessage().
getParametersFromDialog()
void ProjectionFilter::getParametersFromDialog () protected virtual
Collects parameters from the filter dialog (if openDialog is successful)
Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Reimplemented from BasePclModule.
Definition at line 60 of file ProjectionFilter.cpp.
References m_boundaryAngleThreshold, m_coefficientA, m_coefficientB, m_coefficientC, m_coefficientD, m_dialog, m_knn_radius, m_leafSize, m_normalSearchRadius, m_projectionMode, m_useKnn, and m_useVoxelGrid.
openInputDialog()
int ProjectionFilter::openInputDialog () protected virtual
Opens the input dialog window. Where the user can supply parameters for the computation Automatically called by performAction. Does nothing by default. Must be overridden if a dialog must be displayed.
Returns
1 if dialog has been successfully executed, 0 if canceled, negative error code otherwise
Reimplemented from BasePclModule.
Definition at line 51 of file ProjectionFilter.cpp.
References ecvMainAppInterface::getActiveWindow(), BasePclModule::m_app, and m_dialog.
Member Data Documentation
m_boundaryAngleThreshold
float ProjectionFilter::m_boundaryAngleThreshold protected
Definition at line 47 of file ProjectionFilter.h.
Referenced by compute(), and getParametersFromDialog().
m_boundarySearchRadius
float ProjectionFilter::m_boundarySearchRadius protected
Definition at line 46 of file ProjectionFilter.h.
Referenced by compute().
m_coefficientA
float ProjectionFilter::m_coefficientA protected
Definition at line 35 of file ProjectionFilter.h.
Referenced by compute(), and getParametersFromDialog().
m_coefficientB
float ProjectionFilter::m_coefficientB protected
Definition at line 36 of file ProjectionFilter.h.
Referenced by compute(), and getParametersFromDialog().
m_coefficientC
float ProjectionFilter::m_coefficientC protected
Definition at line 37 of file ProjectionFilter.h.
Referenced by compute(), and getParametersFromDialog().
m_coefficientD
float ProjectionFilter::m_coefficientD protected
Definition at line 38 of file ProjectionFilter.h.
Referenced by compute(), and getParametersFromDialog().
m_dialog
ProjectionFilterDlg* ProjectionFilter::m_dialog protected
Definition at line 30 of file ProjectionFilter.h.
Referenced by getParametersFromDialog(), openInputDialog(), and ~ProjectionFilter().
m_knn_radius
int ProjectionFilter::m_knn_radius protected
Definition at line 44 of file ProjectionFilter.h.
Referenced by compute(), and getParametersFromDialog().
m_leafSize
float ProjectionFilter::m_leafSize protected
Definition at line 42 of file ProjectionFilter.h.
Referenced by compute(), and getParametersFromDialog().
m_normalSearchRadius
float ProjectionFilter::m_normalSearchRadius protected
Definition at line 45 of file ProjectionFilter.h.
Referenced by compute(), and getParametersFromDialog().
m_projectionMode
bool ProjectionFilter::m_projectionMode protected
Definition at line 32 of file ProjectionFilter.h.
Referenced by compute(), and getParametersFromDialog().
m_useKnn
bool ProjectionFilter::m_useKnn protected
Definition at line 43 of file ProjectionFilter.h.
Referenced by compute(), and getParametersFromDialog().
m_useVoxelGrid
bool ProjectionFilter::m_useVoxelGrid protected
Definition at line 41 of file ProjectionFilter.h.
Referenced by compute(), and getParametersFromDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/ProjectionFilter.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/ProjectionFilter.cpp