ACloudViewer: ccSNECloud Class Reference
ccSNECloud Class Reference
#include <ccSNECloud.h>
Public Member Functions
ccSNECloud ()
ccSNECloud (ccPointCloud *obj)
void updateMetadata ()
Public Member Functions inherited from ccPointCloud
ccPointCloud (QString name=QString()) throw ()
Default constructor.
ccPointCloud (const ccPointCloud &cloud)
ccPointCloud (const std::vector< Eigen::Vector3d > &points, const std::string &name="cloud")
~ccPointCloud () override
Default destructor.
CV_CLASS_ENUM getClassID () const override
Returns class ID.
ccPointCloud * partialClone (const cloudViewer::ReferenceCloud *selection, int *warnings=nullptr, bool withChildEntities=true) const
Creates a new point cloud object from a ReferenceCloud (selection)
ccPointCloud * cloneThis (ccPointCloud *destCloud=nullptr, bool ignoreChildren=false)
Clones this entity.
ccGenericPointCloud * clone (ccGenericPointCloud *destCloud=nullptr, bool ignoreChildren=false) override
Clones this entity.
ccPointCloud & operator= (const ccPointCloud &cloud)
Fuses another 3D entity with this one.
const ccPointCloud & operator+= (const ccPointCloud &cloud)
const ccPointCloud & operator+= (ccPointCloud *)
ccPointCloud operator+ (const ccPointCloud &cloud) const
void clear () override
Clears the entity from all its points and features.
void unalloactePoints ()
Erases the cloud points.
void unallocateColors ()
Erases the cloud colors.
void unallocateNorms ()
Erases the cloud normals.
void colorsHaveChanged ()
void normalsHaveChanged ()
Notify a modification of normals display parameters or contents.
void pointsHaveChanged ()
Notify a modification of points display parameters or contents.
bool reserve (unsigned numberOfPoints) override
Reserves memory for all the active features.
bool reserveThePointsTable (unsigned _numberOfPoints)
Reserves memory to store the points coordinates.
bool reserveTheRGBTable ()
Reserves memory to store the RGB colors.
bool reserveTheNormsTable ()
Reserves memory to store the compressed normals.
bool resize (unsigned numberOfPoints) override
Resizes all the active features arrays.
bool resizeTheRGBTable (bool fillWithWhite=false)
Resizes the RGB colors array.
bool resizeTheNormsTable ()
Resizes the compressed normals array.
void shrinkToFit ()
Removes unused capacity.
ccScalarField * getCurrentDisplayedScalarField () const
Returns the currently displayed scalar (or 0 if none)
int getCurrentDisplayedScalarFieldIndex () const
Returns the currently displayed scalar field index (or -1 if none)
void setCurrentDisplayedScalarField (int index)
Sets the currently displayed scalar field.
void deleteScalarField (int index) override
Deletes a specific scalar field.
void deleteAllScalarFields () override
Deletes all scalar fields associated to this cloud.
int addScalarField (const char *uniqueName) override
Creates a new scalar field and registers it.
bool sfColorScaleShown () const
Returns whether color scale should be displayed or not.
void showSFColorsScale (bool state)
Sets whether color scale should be displayed or not.
size_t gridCount () const
Returns the number of associated grids.
Grid::Shared & grid (size_t gridIndex)
Returns an associated grid.
const Grid::Shared & grid (size_t gridIndex) const
Returns an associated grid (const verson)
bool addGrid (Grid::Shared grid)
Adds an associated grid.
void removeGrids ()
Remove all associated grids.
ccMesh * triangulateGrid (const Grid &grid, double minTriangleAngle_deg=0.0) const
Meshes a scan grid.
bool computeNormalsWithGrids (double minTriangleAngle_deg=1.0, ecvProgressDialog *pDlg=nullptr)
Compute the normals with the associated grid structure(s)
bool orientNormalsWithGrids (ecvProgressDialog *pDlg=nullptr)
Orient the normals with the associated grid structure(s)
bool orientNormalsTowardViewPoint (CCVector3 &VP, ecvProgressDialog *pDlg=nullptr)
Normals are forced to point to O.
bool computeNormalsWithOctree (CV_LOCAL_MODEL_TYPES model, ccNormalVectors::Orientation preferredOrientation, PointCoordinateType defaultRadius, ecvProgressDialog *pDlg=nullptr)
Compute the normals by approximating the local surface around each point.
bool orientNormalsWithMST (unsigned kNN=6, ecvProgressDialog *pDlg=nullptr)
Orient the normals with a Minimum Spanning Tree.
bool orientNormalsWithFM (unsigned char level, ecvProgressDialog *pDlg=nullptr)
Orient normals with Fast Marching.
bool hasFWF () const
Returns whether the cloud has associated Full WaveForm data.
ccWaveformProxy waveformProxy (unsigned index) const
Returns a proxy on a given waveform.
FWFDescriptorSet & fwfDescriptors ()
Gives access to the FWF descriptors.
const FWFDescriptorSet & fwfDescriptors () const
Gives access to the FWF descriptors (const version)
std::vector< ccWaveform > & waveforms ()
Gives access to the associated FWF data.
const std::vector< ccWaveform > & waveforms () const
Gives access to the associated FWF data (const version)
bool reserveTheFWFTable ()
Reserves the FWF table.
bool resizeTheFWFTable ()
Resizes the FWF table.
SharedFWFDataContainer & fwfData ()
Gives access to the associated FWF data container.
const SharedFWFDataContainer & fwfData () const
Gives access to the associated FWF data container (const version)
bool compressFWFData ()
Compresses the associated FWF data container.
bool computeFWFAmplitude (double &minVal, double &maxVal, ecvProgressDialog *pDlg=nullptr) const
Computes the maximum amplitude of all associated waveforms.
void clearFWFData ()
Clears all associated FWF data.
CCVector3 computeGravityCenter ()
Returns the cloud gravity center.
void invalidateBoundingBox () override
Invalidates bounding box.
void getDrawingParameters (glDrawParams &params) const override
Returns main OpenGL parameters for this entity.
unsigned getUniqueIDForDisplay () const override
Returns object unqiue ID used for display.
bool hasColors () const override
Returns whether colors are enabled or not.
bool hasNormals () const override
Returns whether normals are enabled or not.
bool hasScalarFields () const override
Returns whether one or more scalar fields are instantiated.
bool hasDisplayedScalarField () const override
Returns whether an active scalar field is available or not.
unsigned char testVisibility (const CCVector3 &P) const override
bool normalsAvailable () const override
Returns whether normals are available.
const CCVector3 * getNormal (unsigned pointIndex) const override
If per-point normals are available, returns the one at a specific index.
const ecvColor::Rgb * getScalarValueColor (ScalarType d) const override
Returns color corresponding to a given scalar value.
const ecvColor::Rgb * getPointScalarValueColor (unsigned pointIndex) const override
Returns color corresponding to a given point associated scalar value.
ScalarType getPointDisplayedDistance (unsigned pointIndex) const override
Returns scalar value associated to a given point.
const ecvColor::Rgb & getPointColor (unsigned pointIndex) const override
Returns color corresponding to a given point.
const ColorsTableType & getPointColors () const
ecvColor::Rgb & getPointColorPtr (size_t pointIndex)
Eigen::Vector3d getEigenColor (size_t index) const
std::vector< Eigen::Vector3d > getEigenColors () const
void setEigenColors (const std::vector< Eigen::Vector3d > &colors)
const CompressedNormType & getPointNormalIndex (unsigned pointIndex) const override
Returns compressed normal corresponding to a given point.
const CCVector3 & getPointNormal (unsigned pointIndex) const override
Returns normal corresponding to a given point.
CCVector3 & getPointNormalPtr (size_t pointIndex) const
std::vector< CCVector3 > getPointNormals () const
std::vector< CCVector3 * > getPointNormalsPtr () const
void setPointNormals (const std::vector< CCVector3 > &normals)
Eigen::Vector3d getEigenNormal (size_t index) const
std::vector< Eigen::Vector3d > getEigenNormals () const
void setEigenNormals (const std::vector< Eigen::Vector3d > &normals)
cloudViewer::ReferenceCloud * crop (const ccBBox &box, bool inside=true) override
Crops the cloud inside (or outside) a bounding box.
cloudViewer::ReferenceCloud * crop (const ecvOrientedBBox &bbox) override
virtual void applyRigidTransformation (const ccGLMatrix &trans) override
Applies a rigid transformation (rotation + translation)
virtual void scale (PointCoordinateType fx, PointCoordinateType fy, PointCoordinateType fz, CCVector3 center=CCVector3(0, 0, 0)) override
Multiplies all coordinates by constant factors (one per dimension)
void refreshBB () override
Forces bounding-box update.
ccGenericPointCloud * createNewCloudFromVisibilitySelection (bool removeSelectedPoints=false, VisibilityTableType *visTable=nullptr, std::vector< int > *newIndexesOfRemainingPoints=nullptr, bool silent=false, cloudViewer::ReferenceCloud *selection=nullptr) override
bool removeVisiblePoints (VisibilityTableType *visTable=nullptr, std::vector< int > *newIndexes=nullptr) override
Removes all the 'visible' points (as defined by the visibility array)
void enableVisibilityCheck (bool state)
bool hasSensor () const
Returns whether the mesh as an associated sensor or not.
QSharedPointer< cloudViewer::ReferenceCloud > computeCPSet (ccGenericPointCloud &otherCloud, cloudViewer::GenericProgressCallback *progressCb=nullptr, unsigned char octreeLevel=0)
Computes the closest point of this cloud relatively to another cloud.
bool interpolateColorsFrom (ccGenericPointCloud *cloud, cloudViewer::GenericProgressCallback *progressCb=nullptr, unsigned char octreeLevel=0)
Interpolate colors from another cloud (nearest neighbor only)
void setPointColor (size_t pointIndex, const ecvColor::Rgb &col)
Sets a particular point color.
void setPointColor (size_t pointIndex, const ecvColor::Rgba &col)
void setPointColor (size_t pointIndex, const Eigen::Vector3d &col)
void setEigenColor (size_t index, const Eigen::Vector3d &color)
void setPointNormalIndex (size_t pointIndex, CompressedNormType norm)
Sets a particular point compressed normal.
void setPointNormal (size_t pointIndex, const CCVector3 &N)
Sets a particular point normal (shortcut)
void setEigenNormal (size_t index, const Eigen::Vector3d &normal)
void addNormIndex (CompressedNormType index)
Pushes a compressed normal vector.
void addNorm (const CCVector3 &N)
Pushes a normal vector on stack (shortcut)
void addEigenNorm (const Eigen::Vector3d &N)
void addEigenNorms (const std::vector< Eigen::Vector3d > &normals)
void addNorms (const std::vector< CCVector3 > &Ns)
void addNorms (const std::vector< CompressedNormType > &idxes)
std::vector< CompressedNormType > getNorms () const
void getNorms (std::vector< CompressedNormType > &idxes) const
void addNormAtIndex (const PointCoordinateType *N, unsigned index)
Adds a normal vector to the one at a specific index.
void setNormsTable (NormsIndexesTableType *norms)
Sets the (compressed) normals table.
bool convertNormalToRGB ()
Converts normals to RGB colors.
bool convertNormalToDipDirSFs (ccScalarField *dipSF, ccScalarField *dipDirSF)
Converts normals to two scalar fields: 'dip' and 'dip direction'.
void addRGBColor (const ecvColor::Rgb &C)
Pushes an RGB color on stack.
void addRGBColors (const std::vector< ecvColor::Rgb > &colors)
void addEigenColor (const Eigen::Vector3d &color)
void addEigenColors (const std::vector< Eigen::Vector3d > &colors)
void addRGBColor (ColorCompType r, ColorCompType g, ColorCompType b)
Pushes an RGB color on stack (shortcut)
void addGreyColor (ColorCompType g)
Pushes a grey color on stack (shortcut)
bool convertRGBToGreyScale ()
Converts RGB to grey scale colors.
bool colorize (float r, float g, float b)
Multiplies all color components of all points by coefficients.
bool setRGBColorByHeight (unsigned char heightDim, ccColorScale::Shared colorScale)
Assigns color to points proportionnaly to their 'height'.
bool setRGBColorByBanding (unsigned char dim, double freq)
Assigns color to points by 'banding'.
bool convertCurrentScalarFieldToColors (bool mixWithExistingColor=false)
bool setRGBColorWithCurrentScalarField (bool mixWithExistingColor=false)
Sets RGB colors with current scalar field (values & parameters)
bool setRGBColor (ColorCompType r, ColorCompType g, ColorCompType b)
Set a unique color for the whole cloud (shortcut)
bool setRGBColor (const ecvColor::Rgb &col)
Set a unique color for the whole cloud.
bool applyFilterToRGB (PointCoordinateType sigma, PointCoordinateType sigmaSF, RgbFilterOptions filterParams, cloudViewer::GenericProgressCallback *progressCb=nullptr)
Applies a spatial Gaussian filter on RGB colors.
void invertNormals ()
Inverts normals (if any)
ccPointCloud * filterPointsByScalarValue (ScalarType minVal, ScalarType maxVal, bool outside=false)
Filters out points whose scalar values falls into an interval.
ccPointCloud * filterPointsByScalarValue (std::vector< ScalarType > values, bool outside=false)
Filters out points whose scalar values falls into an interval.
void hidePointsByScalarValue (ScalarType minVal, ScalarType maxVal)
Hides points whose scalar values falls into an interval.
void hidePointsByScalarValue (std::vector< ScalarType > values)
Hides points whose scalar values falls into an interval.
ccPointCloud * unroll (UnrollMode mode, UnrollBaseParams *params, bool exportDeviationSF=false, double startAngle_deg=0.0, double stopAngle_deg=360.0, cloudViewer::GenericProgressCallback *progressCb=nullptr) const
Unrolls the cloud and its normals on a cylinder or a cone.
void addColorRampInfo (CC_DRAW_CONTEXT &context)
Adds associated SF color ramp info to current GL context.
int addScalarField (ccScalarField *sf)
Adds an existing scalar field to this cloud.
ColorsTableType * rgbColors () const
Returns pointer on RGB colors table.
NormsIndexesTableType * normals () const
Returns pointer on compressed normals indexes table.
cloudViewer::ReferenceCloud * crop2D (const ccPolyline *poly, unsigned char orthoDim, bool inside=true)
Crops the cloud inside (or outside) a 2D polyline.
const ccPointCloud & append (ccPointCloud *cloud, unsigned pointCountBefore, bool ignoreChildren=false)
Appends a cloud to this one.
bool enhanceRGBWithIntensitySF (int sfIdx, bool useCustomIntensityRange=false, double minI=0.0, double maxI=1.0)
bool exportCoordToSF (bool exportDims[3])
Exports the specified coordinate dimension(s) to scalar field(s)
bool setCoordFromSF (bool importDims[3], cloudViewer::ScalarField *sf, PointCoordinateType defaultValueForNaN)
Sets coordinate(s) from a scalar field.
bool exportNormalToSF (bool exportDims[3])
Exports the specified normal dimension(s) to scalar field(s)
virtual bool IsEmpty () const override
virtual Eigen::Vector3d GetMinBound () const override
Returns min bounds for geometry coordinates.
virtual Eigen::Vector3d GetMaxBound () const override
Returns max bounds for geometry coordinates.
virtual Eigen::Vector3d GetCenter () const override
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const override
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const override
virtual ccPointCloud & Transform (const Eigen::Matrix4d &trans) override
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual ccPointCloud & Translate (const Eigen::Vector3d &translation, bool relative=true) override
Apply translation to the geometry coordinates.
ccPointCloud & Translate (const CCVector3 &T)
virtual ccPointCloud & Scale (const double s, const Eigen::Vector3d &center) override
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual ccPointCloud & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center) override
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
bool HasCovariances () const
Returns 'true' if the point cloud contains per-point covariance matrix.
ccPointCloud & NormalizeNormals ()
Normalize point normals to length 1.`.
std::shared_ptr< ccPointCloud > SelectByIndex (const std::vector< size_t > &indices, bool invert=false) const
Function to select points from input ccPointCloud into output ccPointCloud.
ccPointCloud & RemoveNonFinitePoints (bool remove_nan=true, bool remove_infinite=true)
Remove all points fromt he point cloud that have a nan entry, or infinite entries.
std::shared_ptr< ccPointCloud > VoxelDownSample (double voxel_size)
Function to downsample input ccPointCloud into output ccPointCloud with a voxel.
std::tuple< std::shared_ptr< ccPointCloud >, Eigen::MatrixXi, std::vector< std::vector< int > > > VoxelDownSampleAndTrace (double voxel_size, const Eigen::Vector3d &min_bound, const Eigen::Vector3d &max_bound, bool approximate_class=false) const
Function to downsample using geometry.ccPointCloud.VoxelDownSample.
std::shared_ptr< ccPointCloud > UniformDownSample (size_t every_k_points) const
Function to downsample input ccPointCloud into output ccPointCloud uniformly.
std::shared_ptr< ccPointCloud > RandomDownSample (double sampling_ratio) const
Function to downsample input pointcloud into output pointcloud randomly.
std::shared_ptr< ccPointCloud > FarthestPointDownSample (const size_t num_samples, const size_t start_index=0) const
Function to downsample input pointcloud into output pointcloud with a set of points has farthest distance.
std::shared_ptr< ccPointCloud > Crop (const ccBBox &bbox) const
Function to crop ccPointCloud into output ccPointCloud.
std::shared_ptr< ccPointCloud > Crop (const ecvOrientedBBox &bbox) const
Function to crop ccPointCloud into output ccPointCloud.
std::tuple< std::shared_ptr< ccPointCloud >, std::vector< size_t > > RemoveRadiusOutliers (size_t nb_points, double search_radius) const
Function to remove points that have less than nb_points in a sphere of a given radius.
std::tuple< std::shared_ptr< ccPointCloud >, std::vector< size_t > > RemoveStatisticalOutliers (size_t nb_neighbors, double std_ratio) const
Function to remove points that are further away from their nb_neighbor neighbors in average.
bool EstimateNormals (const cloudViewer::geometry::KDTreeSearchParam &search_param=cloudViewer::geometry::KDTreeSearchParamKNN(), bool fast_normal_computation=true)
Function to compute the normals of a point cloud.
bool OrientNormalsToAlignWithDirection (const Eigen::Vector3d &orientation_reference=Eigen::Vector3d(0.0, 0.0, 1.0))
Function to orient the normals of a point cloud.
bool OrientNormalsTowardsCameraLocation (const Eigen::Vector3d &camera_location=Eigen::Vector3d::Zero())
Function to orient the normals of a point cloud.
void OrientNormalsConsistentTangentPlane (size_t k)
Function to consistently orient estimated normals based on consistent tangent planes as described in Hoppe et al., "Surface Reconstruction from Unorganized Points", 1992.
std::vector< double > ComputePointCloudDistance (const ccPointCloud &target)
Function to compute the point to point distances between point clouds.
void EstimateCovariances (const cloudViewer::geometry::KDTreeSearchParam &search_param=cloudViewer::geometry::KDTreeSearchParamKNN())
Function to compute the covariance matrix for each point of a point cloud.
std::vector< double > ComputeMahalanobisDistance () const
Function to compute the Mahalanobis distance for points in an input point cloud.
std::vector< double > ComputeNearestNeighborDistance () const
double ComputeResolution () const
std::tuple< std::shared_ptr< ccMesh >, std::vector< size_t > > ComputeConvexHull () const
Function that computes the convex hull of the point cloud using qhull.
std::tuple< std::shared_ptr< ccMesh >, std::vector< size_t > > HiddenPointRemoval (const Eigen::Vector3d &camera_location, const double radius) const
This is an implementation of the Hidden Point Removal operator described in Katz et. al. 'Direct Visibility of Point Sets', 2007.
std::vector< int > ClusterDBSCAN (double eps, size_t min_points, bool print_progress=false) const
Cluster ccPointCloud using the DBSCAN algorithm Ester et al., "A Density-Based Algorithm for Discovering Clusters in Large Spatial Databases with Noise", 1996.
std::tuple< Eigen::Vector4d, std::vector< size_t > > SegmentPlane (const double distance_threshold=0.01, const int ransac_n=3, const int num_iterations=100) const
Segment ccPointCloud plane using the RANSAC algorithm.
std::shared_ptr< ccPointCloud > CreateFromVoxelGrid (const cloudViewer::geometry::VoxelGrid &voxel_grid)
Function to create a PointCloud from a VoxelGrid.
ccPointCloud & PaintUniformColor (const Eigen::Vector3d &color)
Assigns each vertex in the ccMesh the same color.
bool initLOD ()
Intializes the LOD structure.
void clearLOD ()
Clears the LOD structure.
Public Member Functions inherited from cloudViewer::PointCloudTpl< ccGenericPointCloud >
PointCloudTpl ()
Default constructor.
virtual ~PointCloudTpl ()
Default destructor.
unsigned size () const override
void forEach (GenericCloud::genericPointAction action) override
void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax) override
void placeIteratorAtBeginning () override
const CCVector3 * getNextPoint () override
bool enableScalarField () override
bool isScalarFieldEnabled () const override
void setPointScalarValue (unsigned pointIndex, ScalarType value) override
ScalarType getPointScalarValue (unsigned pointIndex) const override
const CCVector3 * getPoint (unsigned index) const override
void getPoint (unsigned index, CCVector3 &P) const override
void getPoint (unsigned index, double P[3]) const override
CCVector3 * getPointPtr (size_t index)
std::vector< CCVector3 > & getPoints ()
const std::vector< CCVector3 > & getPoints () const
const CCVector3 * getPointPersistentPtr (unsigned index) override
const CCVector3 * getPointPersistentPtr (unsigned index) const
void reset ()
Clears the cloud database.
void addPoint (const CCVector3 &P)
Adds a 3D point to the database.
void addPoint (double x, double y, double z)
void addPoint (double xyz[3])
void setPoint (size_t index, const CCVector3 &P)
void setEigenPoint (size_t index, const Eigen::Vector3d &point)
void addEigenPoint (const Eigen::Vector3d &point)
void addPoints (const std::vector< CCVector3 > &points)
void addPoints (const std::vector< Eigen::Vector3d > &points)
Eigen::Vector3d getEigenPoint (size_t index) const
std::vector< Eigen::Vector3d > getEigenPoints () const
void setEigenPoints (const std::vector< Eigen::Vector3d > &points)
unsigned getNumberOfScalarFields () const
Returns the number of associated (and active) scalar fields.
ScalarField * getScalarField (int index) const
Returns a pointer to a specific scalar field.
const char * getScalarFieldName (int index) const
Returns the name of a specific scalar field.
int getScalarFieldIndexByName (const char *name) const
Returns the index of a scalar field represented by its name.
ScalarField * getCurrentInScalarField () const
Returns the scalar field currently associated to the cloud input.
ScalarField * getCurrentOutScalarField () const
Returns the scalar field currently associated to the cloud output.
void setCurrentInScalarField (int index)
Sets the INPUT scalar field.
int getCurrentInScalarFieldIndex ()
Returns current INPUT scalar field index (or -1 if none)
void setCurrentOutScalarField (int index)
Sets the OUTPUT scalar field.
int getCurrentOutScalarFieldIndex ()
Returns current OUTPUT scalar field index (or -1 if none)
void setCurrentScalarField (int index)
Sets both the INPUT & OUTPUT scalar field.
bool renameScalarField (int index, const char *newName)
Renames a specific scalar field.
unsigned capacity () const
Returns cloud capacity (i.e. reserved size)
Public Member Functions inherited from ccGenericPointCloud
ccGenericPointCloud (QString name=QString())
Default constructor.
ccGenericPointCloud (const ccGenericPointCloud &cloud)
Copy constructor.
~ccGenericPointCloud () override
Default destructor.
virtual ccOctree::Shared computeOctree (cloudViewer::GenericProgressCallback *progressCb=nullptr, bool autoAddChild=true)
Computes the cloud octree.
virtual ccOctree::Shared getOctree () const
Returns the associated octree (if any)
virtual void setOctree (ccOctree::Shared octree, bool autoAddChild=true)
Sets the associated octree.
virtual ccOctreeProxy * getOctreeProxy () const
Returns the associated octree proxy (if any)
virtual void deleteOctree ()
Erases the octree.
virtual VisibilityTableType & getTheVisibilityArray ()
Returns associated visibility array.
virtual const VisibilityTableType & getTheVisibilityArray () const
Returns associated visibility array (const version)
virtual cloudViewer::ReferenceCloud * getTheVisiblePoints (const VisibilityTableType *visTable=nullptr, bool silent=false, cloudViewer::ReferenceCloud *selection=nullptr) const
Returns a ReferenceCloud equivalent to the visibility array.
virtual bool isVisibilityTableInstantiated () const
Returns whether the visibility array is allocated or not.
virtual bool resetVisibilityArray ()
Resets the associated visibility array.
virtual void invertVisibilityArray ()
Inverts the visibility array.
virtual void unallocateVisibilityArray ()
Erases the points visibility information.
ccBBox getOwnBB (bool withGLFeatures=false) override
Returns the entity's own bounding-box.
bool isSerializable () const override
Returns whether object is serializable of not.
void setPointSize (unsigned size=0)
Sets point size.
unsigned char getPointSize () const
Returns current point size.
void importParametersFrom (const ccGenericPointCloud *cloud)
Imports the parameters from another cloud.
bool pointPicking (const CCVector2d &clickPos, const ccGLCameraParameters &camera, int &nearestPointIndex, double &nearestSquareDist, double pickWidth=2.0, double pickHeight=2.0, bool autoComputeOctree=false)
Point picking (brute force or octree-driven)
std::tuple< Eigen::Vector3d, Eigen::Matrix3d > computeMeanAndCovariance () const
cloudViewer::SquareMatrixd computeCovariance () const
Public Member Functions inherited from ccShiftedObject
ccShiftedObject (QString name=QString())
Default constructor.
ccShiftedObject (const ccShiftedObject &s)
Copy constructor.
void copyGlobalShiftAndScale (const ccShiftedObject &s)
Copies the Global Shift and Scale from another entity.
virtual void setGlobalShift (double x, double y, double z)
Sets shift applied to original coordinates (information storage only)
virtual void setGlobalShift (const CCVector3d &shift)
Sets shift applied to original coordinates (information storage only)
virtual const CCVector3d & getGlobalShift () const
Returns the shift applied to original coordinates.
virtual void setGlobalScale (double scale)
virtual double getGlobalScale () const
Returns the scale applied to original coordinates.
bool isShifted () const
Returns whether the cloud is shifted or not.
template<typename T >
CCVector3d toGlobal3d (const Vector3Tpl< T > &Plocal) const
Returns the point back-projected into the original coordinates system.
template<typename T >
CCVector3d toLocal3d (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
template<typename T >
CCVector3 toLocal3pc (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner) override
GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false) override
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual Eigen::Vector2d GetMin2DBound () const
virtual Eigen::Vector2d GetMax2DBound () const
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual ccBBox getOwnFitBB (ccGLMatrix &trans)
Returns best-fit bounding-box (if available)
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col)
Draws the entity (and its children) bounding-box.
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
bool isSerializable () const override
Returns whether object is serializable of not.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual const ccGLMatrix & getGLTransformationHistory () const
Returns the transformation 'history' matrix.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual bool normalsShown () const
Returns whether normals are shown or not.
virtual void showNormals (bool state)
Sets normals visibility.
virtual void toggleNormals ()
Toggles normals display state.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void toggleMaterials ()
Toggles material display state.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Public Member Functions inherited from cloudViewer::GenericIndexedCloudPersist
~GenericIndexedCloudPersist () override=default
Default destructor.
Public Member Functions inherited from cloudViewer::GenericIndexedCloud
~GenericIndexedCloud () override=default
Default destructor.
Public Member Functions inherited from cloudViewer::GenericCloud
GenericCloud ()=default
Default constructor.
virtual ~GenericCloud ()=default
Default destructor.
virtual bool hasPoints () const
Public Member Functions inherited from ccMeasurement
ccMeasurement ()
virtual ~ccMeasurement ()
void setDefaultColor (const ecvColor::Rgb &col)
void setHighlightColor (const ecvColor::Rgb &col)
void setActiveColor (const ecvColor::Rgb &col)
void setAlternateColor (const ecvColor::Rgb &col)
ecvColor::Rgb getMeasurementColour () const
void setActive (bool isActive)
void setHighlight (bool isActive)
void setAlternate (bool isActive)
void setNormal ()
Static Public Member Functions
static bool isSNECloud (ccHObject *obj)
Static Public Member Functions inherited from ccPointCloud
static ccPointCloud * From (const cloudViewer::GenericIndexedCloud *cloud, const ccGenericPointCloud *sourceCloud=nullptr)
Creates a new point cloud object from a GenericIndexedCloud.
static ccPointCloud * From (cloudViewer::GenericCloud *cloud, const ccGenericPointCloud *sourceCloud=nullptr)
Creates a new point cloud object from a GenericCloud.
static ccPointCloud * From (const ccPointCloud *sourceCloud, const std::vector< size_t > &indices, bool invert=false)
Function to select points from input ccPointCloud into output ccPointCloud.
static std::vector< Eigen::Matrix3d > EstimatePerPointCovariances (const ccPointCloud &input, const cloudViewer::geometry::KDTreeSearchParam &search_param=cloudViewer::geometry::KDTreeSearchParamKNN())
Static function to compute the covariance matrix for each point of a point cloud. Doesn't change the input PointCloud, just outputs the covariance matrices.
static std::shared_ptr< ccPointCloud > CreateFromDepthImage (const cloudViewer::geometry::Image &depth, const cloudViewer::camera::PinholeCameraIntrinsic &intrinsic, const Eigen::Matrix4d &extrinsic=Eigen::Matrix4d::Identity(), double depth_scale=1000.0, double depth_trunc=1000.0, int stride=1, bool project_valid_depth_only=true)
Factory function to create a pointcloud from a depth image and a camera model.
static std::shared_ptr< ccPointCloud > CreateFromRGBDImage (const cloudViewer::geometry::RGBDImage &image, const cloudViewer::camera::PinholeCameraIntrinsic &intrinsic, const Eigen::Matrix4d &extrinsic=Eigen::Matrix4d::Identity(), bool project_valid_depth_only=true)
Factory function to create a pointcloud from an RGB-D image and a camera model.
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Protected Member Functions
virtual void drawMeOnly (CC_DRAW_CONTEXT &context) override
Draws the entity only (not its children)
Protected Member Functions inherited from ccPointCloud
void applyGLTransformation (const ccGLMatrix &trans) override
Applies a GL transformation to the entity.
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
void notifyGeometryUpdate () override
void swapPoints (unsigned firstIndex, unsigned secondIndex) override
virtual void removePoints (size_t index) override
void releaseVBOs ()
Release VBOs.
Protected Member Functions inherited from cloudViewer::PointCloudTpl< ccGenericPointCloud >
CCVector3 * point (unsigned index)
Returns non const access to a given point.
const CCVector3 * point (unsigned index) const
Returns const access to a given point.
Protected Member Functions inherited from ccShiftedObject
bool saveShiftInfoToFile (QFile &out) const
Serialization helper (output)
bool loadShiftInfoFromFile (QFile &in)
Serialization helper (input)
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void drawNameIn3D ()
Draws the entity name in 3D.
virtual void onDeletionOf (const ccHObject *obj)
This method is called when another object is deleted.
virtual void onUpdateOf (ccHObject *obj)
This method is called when another object (geometry) is updated.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Additional Inherited Members
Public Types inherited from ccPointCloud
enum CLONE_WARNINGS { WRN_OUT_OF_MEM_FOR_COLORS = 1 , WRN_OUT_OF_MEM_FOR_NORMALS = 2 , WRN_OUT_OF_MEM_FOR_SFS = 4 , WRN_OUT_OF_MEM_FOR_FWF = 8 }
Warnings for the partialClone method (bit flags)
enum RGB_FILTER_TYPES {
NONE , BILATERAL , GAUSSIAN , MEAN ,
MEDIAN
}
RGB filter types.
enum UnrollMode { CYLINDER = 0 , CONE = 1 , STRAIGHTENED_CONE = 2 , STRAIGHTENED_CONE2 = 3 }
using BaseClass = cloudViewer::PointCloudTpl< ccGenericPointCloud >
Base class (shortcut)
using FWFDescriptorSet = QMap< uint8_t, WaveformDescriptor >
Waveform descriptors set.
using FWFDataContainer = std::vector< uint8_t >
Waveform data container.
using SharedFWFDataContainer = QSharedPointer< const FWFDataContainer >
Public Types inherited from ccGenericPointCloud
using VisibilityTableType = std::vector< unsigned char >
Array of "visibility" information for each point.
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Public Types inherited from cloudViewer::GenericCloud
using genericPointAction = std::function< void(const CCVector3 &, ScalarType &)>
Generic function applied to a point (used by foreach)
Public Attributes inherited from ccPointCloud
std::vector< Eigen::Matrix3d > covariances_
Covariance Matrix for each point.
Protected Attributes inherited from ccPointCloud
ColorsTableType * m_rgbColors
Colors.
NormsIndexesTableType * m_normals
Normals (compressed)
bool m_sfColorScaleDisplayed
ccScalarField * m_currentDisplayedScalarField
Currently displayed scalar field.
int m_currentDisplayedScalarFieldIndex
Currently displayed scalar field index.
std::vector< Grid::Shared > m_grids
Associated grid structure.
bool m_visibilityCheckEnabled
Whether visibility check is available or not (during comparison)
vboSet m_vboManager
Set of VBOs attached to this cloud.
ccPointCloudLOD * m_lod
L.O.D. structure.
FWFDescriptorSet m_fwfDescriptors
General waveform descriptors.
std::vector< ccWaveform > m_fwfWaveforms
Per-point waveform accessors.
SharedFWFDataContainer m_fwfData
Waveforms raw data storage.
Protected Attributes inherited from cloudViewer::PointCloudTpl< ccGenericPointCloud >
std::vector< CCVector3 > m_points
3D Points database
BoundingBox m_bbox
Bounding-box.
unsigned m_currentPointIndex
'Iterator' on the points db
std::vector< ScalarField * > m_scalarFields
Associated scalar fields.
int m_currentInScalarFieldIndex
Index of current scalar field used for input.
int m_currentOutScalarFieldIndex
Index of current scalar field used for output.
Protected Attributes inherited from ccGenericPointCloud
VisibilityTableType m_pointsVisibility
Per-point visibility table.
unsigned char m_pointSize
Point size (won't be applied if 0)
Protected Attributes inherited from ccShiftedObject
CCVector3d m_globalShift
Global shift (typically applied at loading time)
double m_globalScale
Global scale (typically applied at loading time)
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Protected Attributes inherited from ccMeasurement
bool m_isActive = false
bool m_isHighlighted = false
bool m_isAlternate = false
ecvColor::Rgb m_active_colour = ecvColor::yellow
ecvColor::Rgb m_highlight_colour = ecvColor::green
ecvColor::Rgb m_alternate_colour = ecvColor::cyan
ecvColor::Rgb m_normal_colour = ecvColor::blue
Detailed Description
Definition at line 16 of file ccSNECloud.h.
Constructor & Destructor Documentation
ccSNECloud() [1/2]
ccSNECloud::ccSNECloud ()
Definition at line 15 of file ccSNECloud.cpp.
References updateMetadata().
ccSNECloud() [2/2]
ccSNECloud::ccSNECloud (ccPointCloud * obj)
Definition at line 17 of file ccSNECloud.cpp.
References ccObject::getName(), ccObject::setName(), and updateMetadata().
Member Function Documentation
drawMeOnly()
void ccSNECloud::drawMeOnly (CC_DRAW_CONTEXT & context) override protected virtual
Draws the entity only (not its children)
Reimplemented from ccPointCloud.
Definition at line 45 of file ccSNECloud.cpp.
References ccScalarField::areNaNValuesShownInGrey(), ecvColor::RgbTpl< Type >::b, context, ccScalarField::displayRange(), ccPointCloud::drawMeOnly(), ecvColor::RgbTpl< Type >::g, ccScalarField::getColor(), ecvDisplayTools::GetCurrentScreen(), ecvDisplayTools::GetGLCameraParameters(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::getPoint(), ccPointCloud::getPointNormal(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::getScalarField(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::getScalarFieldIndexByName(), cloudViewer::ScalarField::getValue(), ecvDisplayTools::GetViewportParameters(), ccScalarField::Range::isInRange(), ccGenericPointCloud::isVisibilityTableInstantiated(), length(), ccPointCloud::m_currentDisplayedScalarField, ccGenericPointCloud::m_pointsVisibility, MACRO_Draw3D, MACRO_Foreground, POINT_VISIBLE, ecvColor::RgbTpl< Type >::r, and cloudViewer::PointCloudTpl< ccGenericPointCloud >::size().
isSNECloud()
bool ccSNECloud::isSNECloud (ccHObject * obj) static
Definition at line 36 of file ccSNECloud.cpp.
References ccObject::hasMetaData().
Referenced by ccCompass::estimateP21(), ccCompass::estimateStrain(), and ccCompass::tryLoading().
updateMetadata()
void ccSNECloud::updateMetadata ()
Definition at line 28 of file ccSNECloud.cpp.
References ccObject::setMetaData().
Referenced by ccSNECloud().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCompass/include/ccSNECloud.h
/root/ACloudViewer/plugins/core/Standard/qCompass/src/ccSNECloud.cpp