ACloudViewer: colmap::OverlappingImagesWidget Class Reference
colmap::OverlappingImagesWidget Class Reference
#include <database_management_widget.h>
Public Member Functions
OverlappingImagesWidget (QWidget *parent, OptionManager *options, Database *database)
void ShowMatches (const std::vector< Image > &images, const image_t image_id)
Detailed Description
Definition at line 66 of file database_management_widget.h.
Constructor & Destructor Documentation
OverlappingImagesWidget()
colmap::OverlappingImagesWidget::OverlappingImagesWidget (QWidget * parent, OptionManager * options, Database * database)
Definition at line 218 of file database_management_widget.cc.
Member Function Documentation
ShowMatches()
void colmap::OverlappingImagesWidget::ShowMatches (const std::vector< Image > & images, const image_t image_id)
Definition at line 232 of file DatabaseManagementWidget.cpp.
References cloudViewer::MatchesTab::Reload(), cloudViewer::TwoViewGeometriesTab::Reload(), and patch::to_string().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/database_management_widget.h
/root/ACloudViewer/app/reconstruction/DatabaseManagementWidget.cpp
/root/ACloudViewer/libs/Reconstruction/src/ui/database_management_widget.cc