ACloudViewer: cloudViewer::GenericIndexedCloud Class Reference
cloudViewer::GenericIndexedCloud Class Reference abstract
A generic 3D point cloud with index-based point access.
#include <GenericIndexedCloud.h>
Public Member Functions
~GenericIndexedCloud () override=default
Default destructor.
virtual const CCVector3 * getPoint (unsigned index) const =0
Returns the ith point.
virtual void getPoint (unsigned index, CCVector3 &P) const =0
Returns the ith point.
virtual void getPoint (unsigned index, double P[3]) const
virtual bool normalsAvailable () const
Returns whether normals are available.
virtual const CCVector3 * getNormal (unsigned index) const
If per-point normals are available, returns the one at a specific index.
Public Member Functions inherited from cloudViewer::GenericCloud
GenericCloud ()=default
Default constructor.
virtual ~GenericCloud ()=default
Default destructor.
virtual unsigned size () const =0
Returns the number of points.
virtual bool hasPoints () const
virtual void forEach (genericPointAction action)=0
Fast iteration mechanism.
virtual void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax)=0
Returns the cloud bounding box.
virtual unsigned char testVisibility (const CCVector3 &P) const
virtual void placeIteratorAtBeginning ()=0
Sets the cloud iterator at the beginning.
virtual const CCVector3 * getNextPoint ()=0
Returns the next point (relatively to the global iterator position)
virtual bool enableScalarField ()=0
Enables the scalar field associated to the cloud.
virtual bool isScalarFieldEnabled () const =0
Returns true if the scalar field is enabled, false otherwise.
virtual void setPointScalarValue (unsigned pointIndex, ScalarType value)=0
Sets the ith point associated scalar value.
virtual ScalarType getPointScalarValue (unsigned pointIndex) const =0
Returns the ith point associated scalar value.
Additional Inherited Members
Public Types inherited from cloudViewer::GenericCloud
using genericPointAction = std::function< void(const CCVector3 &, ScalarType &)>
Generic function applied to a point (used by foreach)
Detailed Description
A generic 3D point cloud with index-based point access.
Implements the GenericCloud interface.
Definition at line 18 of file GenericIndexedCloud.h.
Constructor & Destructor Documentation
~GenericIndexedCloud()
cloudViewer::GenericIndexedCloud::~GenericIndexedCloud () override default
Default destructor.
Member Function Documentation
getNormal()
virtual const CCVector3* cloudViewer::GenericIndexedCloud::getNormal (unsigned index) const inline virtual
If per-point normals are available, returns the one at a specific index.
Warning
If overriden, this method should return a valid normal for all points
Reimplemented in ccPointCloud, and cloudViewer::PointCloud.
Definition at line 59 of file GenericIndexedCloud.h.
getPoint() [1/3]
virtual const CCVector3* cloudViewer::GenericIndexedCloud::getPoint (unsigned index) const pure virtual
Returns the ith point.
Virtual method to request a point with a specific index. WARNINGS:
the returned object may not be persistent!
THIS METHOD MAY NOT BE COMPATIBLE WITH PARALLEL STRATEGIES (see the DgmOctree::executeFunctionForAllCellsAtLevel_MT and DgmOctree::executeFunctionForAllCellsAtStartingLevel_MT methods). Consider the other version of getPoint instead or the GenericIndexedCloudPersist class.
Parameters
index of the requested point (between 0 and the cloud size minus 1)
Returns
the requested point (undefined behavior if index is invalid)
Implemented in cloudViewer::ReferenceCloud, cloudViewer::PointCloudTpl< ccGenericPointCloud >, cloudViewer::PointCloudTpl< GenericIndexedCloudPersist >, and cloudViewer::DgmOctreeReferenceCloud.
Referenced by CCCloudToDraco(), ComputeFacetExtensions(), ComputeMathOpWithNearestNeighbor(), DistanceMapGenerationTool::ComputeRadialDist(), DistanceMapGenerationTool::ComputeSurfacesAndVolumes(), DistanceMapGenerationTool::ConvertMapToCloud(), DistanceMapGenerationTool::ConvertProfileToMesh(), ccMPlanePoint::getCoordinates(), masc::ContextBasedFeature::prepare(), masc::Tools::PrepareFeatures(), RefinePointClassif(), MAFilter::saveToFile(), LASFilter::saveToFile(), ToFbxMesh(), and MinimumCutSegmentationDlg::updateForeGroundPoint().
getPoint() [2/3]
virtual void cloudViewer::GenericIndexedCloud::getPoint (unsigned index, CCVector3 & P) const pure virtual
Returns the ith point.
Virtual method to request a point with a specific index. Index must be valid (undefined behavior if index is invalid)
Parameters
index of the requested point (between 0 and the cloud size minus 1)
P output point
Implemented in cloudViewer::ReferenceCloud, cloudViewer::PointCloudTpl< ccGenericPointCloud >, cloudViewer::PointCloudTpl< GenericIndexedCloudPersist >, and cloudViewer::DgmOctreeReferenceCloud.
getPoint() [3/3]
virtual void cloudViewer::GenericIndexedCloud::getPoint (unsigned index, double P[3]) const inline virtual
Reimplemented in cloudViewer::ReferenceCloud, cloudViewer::PointCloudTpl< ccGenericPointCloud >, cloudViewer::PointCloudTpl< GenericIndexedCloudPersist >, and cloudViewer::DgmOctreeReferenceCloud.
Definition at line 45 of file GenericIndexedCloud.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
normalsAvailable()
virtual bool cloudViewer::GenericIndexedCloud::normalsAvailable () const inline virtual
Returns whether normals are available.
Reimplemented in ccPointCloud, and cloudViewer::PointCloud.
Definition at line 53 of file GenericIndexedCloud.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/GenericIndexedCloud.h