ACloudViewer: ccMapWindow Class Reference
ccMapWindow Class Reference
2D map display window
#include <ccMapWindow.h>
Public Member Functions
ccMapWindow (QWidget *parent=0)
Default constructor.
virtual ~ccMapWindow ()
Destructor.
void setAssociatedScalarField (ccScalarField *sf)
Sets associated scalar-field.
void showSF (bool state)
Whether to show associated SF or not.
bool sfShown () const
Returns whether associated SF should be shown or not.
ccScalarField * getAssociatedScalarField () const
Returns associated scalar field.
virtual void getContext (CC_DRAW_CONTEXT &context)
Protected Attributes
ccScalarField * m_sfForRampDisplay
Associated scalar field.
bool m_showSF
Whether to show or not the associated SF.
Detailed Description
2D map display window
Definition at line 15 of file ccMapWindow.h.
Constructor & Destructor Documentation
ccMapWindow()
ccMapWindow::ccMapWindow (QWidget * parent = 0) inline explicit
Default constructor.
Definition at line 18 of file ccMapWindow.h.
~ccMapWindow()
virtual ccMapWindow::~ccMapWindow () inline virtual
Destructor.
Definition at line 22 of file ccMapWindow.h.
References setAssociatedScalarField().
Member Function Documentation
getAssociatedScalarField()
ccScalarField* ccMapWindow::getAssociatedScalarField () const inline
Returns associated scalar field.
Definition at line 44 of file ccMapWindow.h.
References m_sfForRampDisplay.
Referenced by DistanceMapGenerationDlg::colorScaleChanged(), DistanceMapGenerationDlg::updateHeightUnits(), and DistanceMapGenerationDlg::updateZoom().
getContext()
virtual void ccMapWindow::getContext (CC_DRAW_CONTEXT & context) inline virtual
Definition at line 49 of file ccMapWindow.h.
References context, ecvDisplayTools::GetContext(), m_sfForRampDisplay, and m_showSF.
setAssociatedScalarField()
void ccMapWindow::setAssociatedScalarField (ccScalarField * sf) inline
Sets associated scalar-field.
This scalar field will be used for color ramp display.
Definition at line 27 of file ccMapWindow.h.
References CCShareable::link(), m_sfForRampDisplay, and CCShareable::release().
Referenced by DistanceMapGenerationDlg::clearView(), DistanceMapGenerationDlg::update(), and ~ccMapWindow().
sfShown()
bool ccMapWindow::sfShown () const inline
Returns whether associated SF should be shown or not.
Definition at line 41 of file ccMapWindow.h.
References m_showSF.
Referenced by DistanceMapGenerationDlg::updateZoom().
showSF()
void ccMapWindow::showSF (bool state) inline
Whether to show associated SF or not.
Definition at line 38 of file ccMapWindow.h.
References m_showSF.
Referenced by DistanceMapGenerationDlg::DistanceMapGenerationDlg(), and DistanceMapGenerationDlg::toggleColorScaleDisplay().
Member Data Documentation
m_sfForRampDisplay
ccScalarField* ccMapWindow::m_sfForRampDisplay protected
Associated scalar field.
Definition at line 60 of file ccMapWindow.h.
Referenced by getAssociatedScalarField(), getContext(), and setAssociatedScalarField().
m_showSF
bool ccMapWindow::m_showSF protected
Whether to show or not the associated SF.
Definition at line 63 of file ccMapWindow.h.
Referenced by getContext(), sfShown(), and showSF().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qSRA/include/ccMapWindow.h