ACloudViewer: ccKdTreeForFacetExtraction Class Reference
ccKdTreeForFacetExtraction Class Reference
#include <kdTreeForFacetExtraction.h>
Public Member Functions
ccKdTreeForFacetExtraction ()
Default constructor.
Static Public Member Functions
static bool FuseCells (ccKdTree *kdTree, double maxError, cloudViewer::DistanceComputationTools::ERROR_MEASURES errorMeasure, double maxAngle_deg, PointCoordinateType overlapCoef=1, bool closestFirst=true, cloudViewer::GenericProgressCallback *progressCb=0)
Fuses cells.
Detailed Description
Definition at line 13 of file kdTreeForFacetExtraction.h.
Constructor & Destructor Documentation
ccKdTreeForFacetExtraction()
ccKdTreeForFacetExtraction::ccKdTreeForFacetExtraction ()
Default constructor.
Member Function Documentation
FuseCells()
bool ccKdTreeForFacetExtraction::FuseCells (ccKdTree * kdTree, double maxError, cloudViewer::DistanceComputationTools::ERROR_MEASURES errorMeasure, double maxAngle_deg, PointCoordinateType overlapCoef = 1, bool closestFirst = true, cloudViewer::GenericProgressCallback * progressCb = 0) static
Fuses cells.
Creates a new scalar fields with the groups indexes.
Parameters
kdTree Kd-tree
maxError max error after fusion (see errorMeasure)
errorMeasure error measure type
maxAngle_deg maximum angle between two sets to allow fusion (in degrees)
overlapCoef maximum relative distance between two sets to accept fusion (1 = no distance, < 1 = overlap, > 1 = gap)
closestFirst
Definition at line 52 of file kdTreeForFacetExtraction.cpp.
References cloudViewer::ReferenceCloud::add(), ccKdTree::associatedGenericCloud(), CandidateDistAscendingComparison(), cloudViewer::DistanceComputationTools::ComputeCloud2PlaneDistance(), cloudViewer::DegreesToRadians(), DescendingLeafSizeComparison(), Vector3Tpl< Type >::dot(), cloudViewer::PointCloudTpl< T >::enableScalarField(), cloudViewer::TrueKdTree::Leaf::error, error(), fabs(), cloudViewer::ReferenceCloud::getAssociatedCloud(), cloudViewer::Neighbourhood::getGravityCenter(), cloudViewer::TrueKdTree::getLeaves(), cloudViewer::Neighbourhood::getLSPlane(), ccKdTree::getNeighborLeaves(), cloudViewer::ReferenceCloud::getPoint(), ccObject::isA(), nProgress, cloudViewer::NormalizedProgress::oneStep(), ParallelSort, cloudViewer::TrueKdTree::Leaf::planeEq, CV_TYPES::POINT_CLOUD, cloudViewer::TrueKdTree::Leaf::points, cloudViewer::GenericProgressCallback::setInfo(), cloudViewer::GenericProgressCallback::setMethodTitle(), cloudViewer::ReferenceCloud::setPointScalarValue(), cloudViewer::ReferenceCloud::size(), cloudViewer::GenericProgressCallback::start(), cloudViewer::GenericProgressCallback::textCanBeEdited(), cloudViewer::GenericProgressCallback::update(), cloudViewer::TrueKdTree::Leaf::userData, and CVLog::Warning().
Referenced by qFacets::extractFacets().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qFacets/include/kdTreeForFacetExtraction.h
/root/ACloudViewer/plugins/core/Standard/qFacets/src/kdTreeForFacetExtraction.cpp