ACloudViewer: cloudViewer::GenericCloud Class Reference
cloudViewer::GenericCloud Class Reference abstract
#include <GenericCloud.h>
Public Types
using genericPointAction = std::function< void(const CCVector3 &, ScalarType &)>
Generic function applied to a point (used by foreach)
Public Member Functions
GenericCloud ()=default
Default constructor.
virtual ~GenericCloud ()=default
Default destructor.
virtual unsigned size () const =0
Returns the number of points.
virtual bool hasPoints () const
virtual void forEach (genericPointAction action)=0
Fast iteration mechanism.
virtual void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax)=0
Returns the cloud bounding box.
virtual unsigned char testVisibility (const CCVector3 &P) const
virtual void placeIteratorAtBeginning ()=0
Sets the cloud iterator at the beginning.
virtual const CCVector3 * getNextPoint ()=0
Returns the next point (relatively to the global iterator position)
virtual bool enableScalarField ()=0
Enables the scalar field associated to the cloud.
virtual bool isScalarFieldEnabled () const =0
Returns true if the scalar field is enabled, false otherwise.
virtual void setPointScalarValue (unsigned pointIndex, ScalarType value)=0
Sets the ith point associated scalar value.
virtual ScalarType getPointScalarValue (unsigned pointIndex) const =0
Returns the ith point associated scalar value.
Detailed Description
A generic 3D point cloud interface for data communication between library and client applications
Definition at line 20 of file GenericCloud.h.
Member Typedef Documentation
genericPointAction
using cloudViewer::GenericCloud::genericPointAction = std::function<void(const CCVector3&, ScalarType&)>
Generic function applied to a point (used by foreach)
Definition at line 29 of file GenericCloud.h.
Constructor & Destructor Documentation
GenericCloud()
cloudViewer::GenericCloud::GenericCloud () default
Default constructor.
~GenericCloud()
virtual cloudViewer::GenericCloud::~GenericCloud () virtual default
Default destructor.
Member Function Documentation
enableScalarField()
virtual bool cloudViewer::GenericCloud::enableScalarField () pure virtual
Enables the scalar field associated to the cloud.
If the scalar field structure is not yet initialized/allocated, this method gives the signal for its creation. Otherwise, if possible the structure size should be pre-reserved with the same number of elements as the point cloud.
Implemented in NumpyCloud, cloudViewer::ReferenceCloud, cloudViewer::PointCloudTpl< ccGenericPointCloud >, cloudViewer::PointCloudTpl< GenericIndexedCloudPersist >, and cloudViewer::DgmOctreeReferenceCloud.
Referenced by qCanupoTools::ComputeCorePointsDescriptors(), and define_GenericCloud().
forEach()
virtual void cloudViewer::GenericCloud::forEach (genericPointAction action) pure virtual
Fast iteration mechanism.
Virtual method to apply a function to the whole cloud
Parameters
action the function to apply (see GenericCloud::genericPointAction)
Implemented in NumpyCloud, cloudViewer::ReferenceCloud, cloudViewer::DgmOctreeReferenceCloud, cloudViewer::PointCloudTpl< ccGenericPointCloud >, and cloudViewer::PointCloudTpl< GenericIndexedCloudPersist >.
Referenced by define_GenericCloud().
getBoundingBox()
virtual void cloudViewer::GenericCloud::getBoundingBox (CCVector3 & bbMin, CCVector3 & bbMax) pure virtual
Returns the cloud bounding box.
Virtual method to request the cloud bounding box limits
Parameters
bbMin lower bounding-box limits (Xmin,Ymin,Zmin)
bbMax higher bounding-box limits (Xmax,Ymax,Zmax)
Implemented in NumpyCloud, cloudViewer::ReferenceCloud, cloudViewer::PointCloudTpl< ccGenericPointCloud >, cloudViewer::PointCloudTpl< GenericIndexedCloudPersist >, and cloudViewer::DgmOctreeReferenceCloud.
Referenced by PCVContext::associateToEntity(), and define_GenericCloud().
getNextPoint()
virtual const CCVector3* cloudViewer::GenericCloud::getNextPoint () pure virtual
Returns the next point (relatively to the global iterator position)
Virtual method to handle the cloud global iterator. Global iterator position should be increased by one each time this method is called. Warning:
the returned object may not be persistent!
THIS METHOD MAY NOT BE COMPATIBLE WITH PARALLEL STRATEGIES (see the DgmOctree::executeFunctionForAllCellsAtLevel_MT and DgmOctree::executeFunctionForAllCellsAtStartingLevel_MT methods).
Returns
pointer on next point (or 0 if no more)
Implemented in NumpyCloud, cloudViewer::ReferenceCloud, cloudViewer::PointCloudTpl< ccGenericPointCloud >, cloudViewer::PointCloudTpl< GenericIndexedCloudPersist >, and cloudViewer::DgmOctreeReferenceCloud.
Referenced by define_GenericCloud(), PCVContext::GLAccumPixel(), and cloudViewer::Grid3D< Type >::intersectWith().
getPointScalarValue()
virtual ScalarType cloudViewer::GenericCloud::getPointScalarValue (unsigned pointIndex) const pure virtual
Returns the ith point associated scalar value.
Implemented in cloudViewer::ReferenceCloud, cloudViewer::PointCloudTpl< ccGenericPointCloud >, cloudViewer::PointCloudTpl< GenericIndexedCloudPersist >, and cloudViewer::DgmOctreeReferenceCloud.
Referenced by CCCloudToDraco(), define_GenericCloud(), and ScalarDialog::onItemPicked().
hasPoints()
virtual bool cloudViewer::GenericCloud::hasPoints () const inline virtual
Definition at line 37 of file GenericCloud.h.
References size.
Referenced by cloudViewer::t::geometry::PointCloud::FromLegacy(), ccPolyline::IsEmpty(), and cloudViewer::io::rpc::SetPointCloud().
isScalarFieldEnabled()
virtual bool cloudViewer::GenericCloud::isScalarFieldEnabled () const pure virtual
Returns true if the scalar field is enabled, false otherwise.
Implemented in NumpyCloud, cloudViewer::ReferenceCloud, cloudViewer::PointCloudTpl< ccGenericPointCloud >, cloudViewer::PointCloudTpl< GenericIndexedCloudPersist >, and cloudViewer::DgmOctreeReferenceCloud.
placeIteratorAtBeginning()
virtual void cloudViewer::GenericCloud::placeIteratorAtBeginning () pure virtual
Sets the cloud iterator at the beginning.
Virtual method to handle the cloud global iterator
Implemented in NumpyCloud, cloudViewer::ReferenceCloud, cloudViewer::PointCloudTpl< ccGenericPointCloud >, cloudViewer::PointCloudTpl< GenericIndexedCloudPersist >, and cloudViewer::DgmOctreeReferenceCloud.
Referenced by define_GenericCloud(), PCVContext::GLAccumPixel(), and cloudViewer::Grid3D< Type >::intersectWith().
setPointScalarValue()
virtual void cloudViewer::GenericCloud::setPointScalarValue (unsigned pointIndex, ScalarType value) pure virtual
Sets the ith point associated scalar value.
Implemented in cloudViewer::ReferenceCloud, cloudViewer::PointCloudTpl< ccGenericPointCloud >, cloudViewer::PointCloudTpl< GenericIndexedCloudPersist >, and cloudViewer::DgmOctreeReferenceCloud.
Referenced by define_GenericCloud(), and FastMarchingForFacetExtraction::updateFlagsTable().
size()
virtual unsigned cloudViewer::GenericCloud::size () const pure virtual
Returns the number of points.
Virtual method to request the cloud size
Returns
the cloud size
Implemented in NumpyCloud, cloudViewer::ReferenceCloud, cloudViewer::PointCloudTpl< ccGenericPointCloud >, cloudViewer::PointCloudTpl< GenericIndexedCloudPersist >, and cloudViewer::DgmOctreeReferenceCloud.
Referenced by CCCloudToDraco(), CCMeshToDraco(), qCanupoProcess::Classify(), ConvexConcaveHullReconstruction::compute(), GreedyTriangulation::compute(), MarchingCubeReconstruction::compute(), NurbsSurfaceReconstruction::compute(), PoissonReconstruction::compute(), qM3C2Process::Compute(), qCanupoTools::ComputeCorePointsDescriptors(), qM3C2Normals::ComputeCorePointsNormals(), ComputeFacetExtensions(), ComputeMathOpWithNearestNeighbor(), DistanceMapGenerationTool::ComputeRadialDist(), DistanceMapGenerationTool::ComputeSurfacesAndVolumes(), DistanceMapGenerationTool::ConvertMapToCloud(), DistanceMapGenerationTool::ConvertProfileToMesh(), define_GenericCloud(), qPCV::doAction(), StereogramDialog::exportCurrentSelection(), qFacets::exportFacets(), PCVContext::GLAccumPixel(), cloudViewer::Grid3D< Type >::intersectWith(), masc::ContextBasedFeature::prepare(), masc::PointFeature::prepare(), masc::Tools::PrepareFeatures(), PNFilter::saveToFile(), PVFilter::saveToFile(), MAFilter::saveToFile(), LASFilter::saveToFile(), FastMarchingForFacetExtraction::step(), ToFbxMesh(), and qM3C2Normals::UpdateNormalOrientationsWithCloud().
testVisibility()
virtual unsigned char cloudViewer::GenericCloud::testVisibility (const CCVector3 & P) const inline virtual
Returns a given point visibility state (relatively to a sensor for instance) Generic method to request a point visibility (should be overloaded if this functionality is required). The point visibility is such as defined in Daniel Girardeau-Montaut's PhD manuscript (see Chapter 2, section 2-3-3). In this case, a ground based laser sensor model should be used to determine it. This method is called before performing any point-to-cloud comparison. If the result is not POINT_VISIBLE, then the comparison won't be performed and the scalar field value associated to this point will be this visibility value.
Parameters
P the 3D point to test
Returns
visibility (default: POINT_VISIBLE)
Reimplemented in ccPointCloud, and cloudViewer::ReferenceCloud.
Definition at line 65 of file GenericCloud.h.
References POINT_VISIBLE.
Referenced by define_GenericCloud().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/GenericCloud.h