ACloudViewer: VtkUtils::AnsysFileReader Class Reference
VtkUtils::AnsysFileReader Class Reference
#include <filereaderutils.h>
Public Member Functions
AnsysFileReader (QObject *parent=nullptr)
void run ()
Public Member Functions inherited from VtkUtils::AbstractFileReader
AbstractFileReader (QObject *parent=nullptr)
void setFileName (const QString &file)
QString fileName () const
void setTitle (const QString &title)
QString title () const
Public Member Functions inherited from VtkUtils::ReaderTempl< vtkGenericDataObjectReader >
virtual vtkDataObject * dataObject () const
vtkGenericDataObjectReader * reader () const
Protected Member Functions
void interpretFormatString (char *line, int &fieldStart, int &fieldWidth, int &expectedLineLength) const
void interpretFormatStringEx (char *line, int &firstFieldWidth, int &fieldStart, int &fieldWidth, int &expectedLineLength) const
void interpret (const char *fmt, int &fieldWidth, int &linelen) const
Additional Inherited Members
Signals inherited from VtkUtils::AbstractFileReader
void finished ()
Protected Attributes inherited from VtkUtils::AbstractFileReader
QString m_fileName
QString m_title
Protected Attributes inherited from VtkUtils::ReaderTempl< vtkGenericDataObjectReader >
vtkGenericDataObjectReader * m_reader
vtkDataObject * m_dataObject
Detailed Description
Definition at line 132 of file filereaderutils.h.
Constructor & Destructor Documentation
AnsysFileReader()
VtkUtils::AnsysFileReader::AnsysFileReader (QObject * parent = nullptr) explicit
Definition at line 605 of file filereaderutils.cpp.
Member Function Documentation
interpret()
void VtkUtils::AnsysFileReader::interpret (const char * fmt, int & fieldWidth, int & linelen) const protected
Definition at line 880 of file filereaderutils.cpp.
Referenced by interpretFormatString(), and interpretFormatStringEx().
interpretFormatString()
void VtkUtils::AnsysFileReader::interpretFormatString (char * line, int & fieldStart, int & fieldWidth, int & expectedLineLength) const protected
Definition at line 812 of file filereaderutils.cpp.
References interpret().
interpretFormatStringEx()
void VtkUtils::AnsysFileReader::interpretFormatStringEx (char * line, int & firstFieldWidth, int & fieldStart, int & fieldWidth, int & expectedLineLength) const protected
Definition at line 841 of file filereaderutils.cpp.
References interpret().
Referenced by run().
run()
void VtkUtils::AnsysFileReader::run ()
Definition at line 608 of file filereaderutils.cpp.
References QtCompat::endl(), VtkUtils::AbstractFileReader::fileName(), VtkUtils::AbstractFileReader::finished(), interpretFormatStringEx(), VtkUtils::ReaderTempl< vtkGenericDataObjectReader >::m_dataObject, VtkUtils::AbstractFileReader::m_title, MAX_ANSYS_LINE, and STRNCASECMP.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/filereaderutils.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/filereaderutils.cpp