ACloudViewer: cloudViewer::ThreadControlWidget Class Reference
cloudViewer::ThreadControlWidget Class Reference
#include <ThreadControlWidget.h>
Public Member Functions
ThreadControlWidget (QWidget *parent)
void StartThread (const QString &progress_text, const bool stoppable, colmap::Thread *thread)
void StartFunction (const QString &progress_text, const std::function< void()> &func)
Detailed Description
Definition at line 19 of file ThreadControlWidget.h.
Constructor & Destructor Documentation
ThreadControlWidget()
cloudViewer::ThreadControlWidget::ThreadControlWidget (QWidget * parent) explicit
Definition at line 17 of file ThreadControlWidget.cpp.
Member Function Documentation
StartFunction()
void cloudViewer::ThreadControlWidget::StartFunction (const QString & progress_text, const std::function< void()> & func)
Definition at line 79 of file ThreadControlWidget.cpp.
References Run(), and StartThread().
StartThread()
void cloudViewer::ThreadControlWidget::StartThread (const QString & progress_text, const bool stoppable, colmap::Thread * thread)
Definition at line 34 of file ThreadControlWidget.cpp.
References ecvColor::LookUpTable::at().
Referenced by cloudViewer::AutomaticReconstructionWidget::Run(), cloudViewer::SIFTExtractionWidget::Run(), cloudViewer::ImportFeaturesWidget::Run(), cloudViewer::ExhaustiveMatchingTab::Run(), cloudViewer::SequentialMatchingTab::Run(), cloudViewer::VocabTreeMatchingTab::Run(), cloudViewer::SpatialMatchingTab::Run(), cloudViewer::TransitiveMatchingTab::Run(), cloudViewer::CustomMatchingTab::Run(), and StartFunction().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/reconstruction/ThreadControlWidget.h
/root/ACloudViewer/app/reconstruction/ThreadControlWidget.cpp