ACloudViewer: EditCameraTool Class Reference
EditCameraTool Class Reference
#include <EditCameraTool.h>
Public Member Functions
EditCameraTool (ecvGenericVisualizer3D *viewer)
~EditCameraTool () override
Public Member Functions inherited from ecvGenericCameraTool
ecvGenericCameraTool ()
~ecvGenericCameraTool () override
virtual void saveCameraConfiguration (const std::string &file)
virtual void loadCameraConfiguration (const std::string &file)
virtual void resetViewDirection (double look_x, double look_y, double look_z, double up_x, double up_y, double up_z)
virtual void setAutoPickPivotAtCenter (bool state)
virtual void updateCamera ()=0
virtual void updateCameraParameters ()=0
Static Public Member Functions
static void UpdateCameraInfo ()
static void UpdateCamera ()
static void SetVisualizer (ecvGenericVisualizer3D *viewer)
Static Public Member Functions inherited from ecvGenericCameraTool
static void SaveBuffer ()
Additional Inherited Members
Public Types inherited from ecvGenericCameraTool
enum CameraAdjustmentType { Roll = 0 , Elevation , Azimuth , Zoom }
Public Slots inherited from ecvGenericCameraTool
void UpdateCamera ()
Static Public Attributes inherited from ecvGenericCameraTool
static CameraInfo OldCameraParam
static CameraInfo CurrentCameraParam
Detailed Description
Definition at line 16 of file EditCameraTool.h.
Constructor & Destructor Documentation
EditCameraTool()
EditCameraTool::EditCameraTool (ecvGenericVisualizer3D * viewer)
Definition at line 83 of file EditCameraTool.cpp.
References SetVisualizer().
~EditCameraTool()
EditCameraTool::~EditCameraTool () override
Definition at line 90 of file EditCameraTool.cpp.
Member Function Documentation
SetVisualizer()
void EditCameraTool::SetVisualizer (ecvGenericVisualizer3D * viewer) static
Definition at line 92 of file EditCameraTool.cpp.
References s_viewer, and CVLog::Warning().
Referenced by EditCameraTool(), UpdateCamera(), and UpdateCameraInfo().
UpdateCamera()
void EditCameraTool::UpdateCamera () static
Definition at line 121 of file EditCameraTool.cpp.
References ecvGenericCameraTool::CameraInfo::clippRange, ecvGenericCameraTool::CurrentCameraParam, ecvGenericCameraTool::CameraInfo::eyeAngle, ecvGenericCameraTool::CameraInfo::focal, PclUtils::PCLVis::getCurrentRenderer(), ecvDisplayTools::GetVisualizer3D(), PclUtils::PCLVis::getVtkCamera(), ecvGenericCameraTool::CameraInfo::pivot, ecvGenericCameraTool::CameraInfo::position, ecvGenericCameraTool::CameraInfo::rotationFactor, s_camera, s_viewer, PclUtils::PCLVis::setCenterOfRotation(), PclUtils::PCLVis::setRotationFactor(), SetVisualizer(), Vector2Tpl< Type >::u, Tuple3Tpl< Type >::u, PclUtils::PCLVis::UpdateScreen(), ecvGenericCameraTool::CameraInfo::viewAngle, and ecvGenericCameraTool::CameraInfo::viewUp.
Referenced by ecvCustomViewpointsToolbar::ApplyCustomViewpoint().
UpdateCameraInfo()
void EditCameraTool::UpdateCameraInfo () static
Definition at line 103 of file EditCameraTool.cpp.
References ecvGenericCameraTool::CameraInfo::clippRange, ecvGenericCameraTool::CurrentCameraParam, ecvGenericCameraTool::CameraInfo::eyeAngle, ecvGenericCameraTool::CameraInfo::focal, PclUtils::PCLVis::getCenterOfRotation(), PclUtils::PCLVis::getRotationFactor(), ecvDisplayTools::GetVisualizer3D(), PclUtils::PCLVis::getVtkCamera(), ecvGenericCameraTool::OldCameraParam, ecvGenericCameraTool::CameraInfo::pivot, ecvGenericCameraTool::CameraInfo::position, ecvGenericCameraTool::CameraInfo::rotationFactor, s_camera, s_viewer, SetVisualizer(), Vector2Tpl< Type >::u, Tuple3Tpl< Type >::u, ecvGenericCameraTool::CameraInfo::viewAngle, and ecvGenericCameraTool::CameraInfo::viewUp.
Referenced by ecvCustomViewpointsToolbar::addCurrentViewpointToCustomViewpoints().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/CameraTools/EditCameraTool.h
/root/ACloudViewer/libs/PCLEngine/Tools/CameraTools/EditCameraTool.cpp