ACloudViewer: SaveDracoFileDlg Class Reference
SaveDracoFileDlg Class Reference
DRACO file (https://github.com/google/draco) saving dialog.
#include <SaveDracoFileDlg.h>
Public Member Functions
SaveDracoFileDlg (QWidget *parent=nullptr)
Default constructor.
virtual ~SaveDracoFileDlg ()=default
Destructor.
void reset ()
Resets default values.
Protected Member Functions
void initFromPersistentSettings ()
Inits dialog state from persistent settings.
void saveToPersistentSettings ()
Saves dialog state from persistent settings.
Detailed Description
DRACO file (https://github.com/google/draco) saving dialog.
Definition at line 34 of file SaveDracoFileDlg.h.
Constructor & Destructor Documentation
SaveDracoFileDlg()
SaveDracoFileDlg::SaveDracoFileDlg (QWidget * parent = nullptr) explicit
Default constructor.
Definition at line 19 of file SaveDracoFileDlg.cpp.
References initFromPersistentSettings(), reset(), Reset(), and saveToPersistentSettings().
~SaveDracoFileDlg()
virtual SaveDracoFileDlg::~SaveDracoFileDlg () virtual default
Destructor.
Member Function Documentation
initFromPersistentSettings()
void SaveDracoFileDlg::initFromPersistentSettings () protected
Inits dialog state from persistent settings.
Definition at line 31 of file SaveDracoFileDlg.cpp.
References DefaultCoordsQuant, DefaultNormQuant, and DefaultSFQuant.
Referenced by SaveDracoFileDlg().
reset()
void SaveDracoFileDlg::reset (void)
Resets default values.
Definition at line 65 of file SaveDracoFileDlg.cpp.
References DefaultCoordsQuant, DefaultNormQuant, and DefaultSFQuant.
Referenced by SaveDracoFileDlg().
saveToPersistentSettings()
void SaveDracoFileDlg::saveToPersistentSettings () protected
Saves dialog state from persistent settings.
Definition at line 51 of file SaveDracoFileDlg.cpp.
Referenced by SaveDracoFileDlg().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qDracoIO/include/SaveDracoFileDlg.h
/root/ACloudViewer/plugins/core/IO/qDracoIO/src/SaveDracoFileDlg.cpp