ACloudViewer: cloudViewer::pipelines::registration::PoseGraphNode Class Reference
cloudViewer::pipelines::registration::PoseGraphNode Class Reference
Node of PoseGraph.
#include <PoseGraph.h>
Public Member Functions
PoseGraphNode (const Eigen::Matrix4d &pose=Eigen::Matrix4d::Identity())
Default Constructor.
~PoseGraphNode ()
bool ConvertToJsonValue (Json::Value &value) const override
bool ConvertFromJsonValue (const Json::Value &value) override
Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
virtual ~IJsonConvertible ()
virtual std::string ToString () const
Convert to a styled string representation of JSON data for display.
Public Attributes
Eigen::Matrix4d_u pose_
Additional Inherited Members
Static Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
static bool EigenVector3dFromJsonArray (Eigen::Vector3d &vec, const Json::Value &value)
static bool EigenVector3dToJsonArray (const Eigen::Vector3d &vec, Json::Value &value)
static bool EigenVector4dFromJsonArray (Eigen::Vector4d &vec, const Json::Value &value)
static bool EigenVector4dToJsonArray (const Eigen::Vector4d &vec, Json::Value &value)
static bool EigenMatrix3dFromJsonArray (Eigen::Matrix3d &mat, const Json::Value &value)
static bool EigenMatrix3dToJsonArray (const Eigen::Matrix3d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d_u &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d_u &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d_u &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d_u &mat, Json::Value &value)
Detailed Description
Node of PoseGraph.
Definition at line 23 of file PoseGraph.h.
Constructor & Destructor Documentation
PoseGraphNode()
cloudViewer::pipelines::registration::PoseGraphNode::PoseGraphNode (const Eigen::Matrix4d & pose = Eigen::Matrix4d::Identity()) inline
Default Constructor.
Definition at line 26 of file PoseGraph.h.
~PoseGraphNode()
cloudViewer::pipelines::registration::PoseGraphNode::~PoseGraphNode ()
Definition at line 17 of file PoseGraph.cpp.
Member Function Documentation
ConvertFromJsonValue()
bool cloudViewer::pipelines::registration::PoseGraphNode::ConvertFromJsonValue (const Json::Value & value) override virtual
Implements cloudViewer::utility::IJsonConvertible.
Definition at line 32 of file PoseGraph.cpp.
References cloudViewer::utility::IJsonConvertible::EigenMatrix4dFromJsonArray(), LogWarning, pose_, and Value.
Referenced by cloudViewer::pipelines::registration::PoseGraph::ConvertFromJsonValue().
ConvertToJsonValue()
bool cloudViewer::pipelines::registration::PoseGraphNode::ConvertToJsonValue (Json::Value & value) const override virtual
Implements cloudViewer::utility::IJsonConvertible.
Definition at line 19 of file PoseGraph.cpp.
References cloudViewer::utility::IJsonConvertible::EigenMatrix4dToJsonArray(), pose_, and Value.
Member Data Documentation
pose_
Eigen::Matrix4d_u cloudViewer::pipelines::registration::PoseGraphNode::pose_
Definition at line 35 of file PoseGraph.h.
Referenced by ConvertFromJsonValue(), ConvertToJsonValue(), and cloudViewer::pipelines::registration::GetRelativePoses().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/pipelines/registration/PoseGraph.h
/root/ACloudViewer/libs/cloudViewer/pipelines/registration/PoseGraph.cpp