ACloudViewer: ccCone Class Reference
ccCone Class Reference
Cone (primitive)
#include <ecvCone.h>
Public Member Functions
ccCone (PointCoordinateType bottomRadius, PointCoordinateType topRadius, PointCoordinateType height, PointCoordinateType xOff=0, PointCoordinateType yOff=0, const ccGLMatrix *transMat=0, QString name=QString("Cone"), unsigned precision=DEFAULT_DRAWING_PRECISION)
Default constructor.
ccCone (QString name=QString("Cone"))
Simplified constructor.
virtual CV_CLASS_ENUM getClassID () const override
Returns class ID.
PointCoordinateType getHeight () const
Returns height.
void setHeight (PointCoordinateType height)
Sets height.
PointCoordinateType getBottomRadius () const
Returns bottom radius.
virtual void setBottomRadius (PointCoordinateType radius)
Sets bottom radius.
PointCoordinateType getTopRadius () const
Returns top radius.
virtual void setTopRadius (PointCoordinateType radius)
Sets top radius.
virtual CCVector3 getBottomCenter () const
Returns cone axis bottom end point after applying transformation.
virtual CCVector3 getTopCenter () const
Returns cone axis top end point after applying transformation.
virtual CCVector3 getSmallCenter () const
Returns cone axis end point associated with whichever radii is smaller.
virtual CCVector3 getLargeCenter () const
Returns cone axis end point associated with whichever radii is larger.
virtual PointCoordinateType getSmallRadius () const
Returns whichever cone radii is smaller.
virtual PointCoordinateType getLargeRadius () const
Returns whichever cone radii is larger.
virtual bool isSnoutMode () const
Returns true if the Cone was created in snout mode.
virtual QString getTypeName () const override
Returns type name (sphere, cylinder, etc.)
virtual bool hasDrawingPrecision () const override
Whether drawing is dependent on 'precision' parameter.
virtual ccGenericPrimitive * clone () const override
Clones primitive.
Public Member Functions inherited from ccGenericPrimitive
ccGenericPrimitive (QString name=QString(), const ccGLMatrix *transMat=nullptr)
Default constructor.
CV_CLASS_ENUM getClassID () const override
Returns class ID.
virtual void setColor (const ecvColor::Rgb &col)
Sets primitive color (shortcut)
const ccGenericPrimitive & operator+= (const ccGenericPrimitive &prim)
Add operator.
virtual bool setDrawingPrecision (unsigned steps)
Sets drawing precision.
virtual unsigned getDrawingPrecision () const
Returns drawing precision (or 0 if feature is not supported)
virtual ccGLMatrix & getTransformation ()
Returns the transformation that is currently applied to the vertices.
virtual const ccGLMatrix & getTransformation () const
const ccGLMatrix & getGLTransformationHistory () const override
inherited methods (ccHObject)
virtual void clearDrawings ()
virtual void hideShowDrawings (CC_DRAW_CONTEXT &context)
Public Member Functions inherited from ccMesh
ccMesh (ccGenericPointCloud *vertices=nullptr)
Default ccMesh constructor.
ccMesh (const ccMesh &mesh)
ccMesh (const std::vector< Eigen::Vector3d > &vertices, const std::vector< Eigen::Vector3i > &triangles)
Parameterized Constructor.
ccMesh (cloudViewer::GenericIndexedMesh *giMesh, ccGenericPointCloud *giVertices)
ccMesh constructor (from a cloudViewer::GenericIndexedMesh)
~ccMesh () override
Default destructor.
CV_CLASS_ENUM getClassID () const override
Returns class ID.
void setAssociatedCloud (ccGenericPointCloud *cloud)
Sets the associated vertices cloud (warning)
ccMesh * cloneMesh (ccGenericPointCloud *vertices=nullptr, ccMaterialSet *clonedMaterials=nullptr, NormsIndexesTableType *clonedNormsTable=nullptr, TextureCoordsContainer *cloneTexCoords=nullptr)
Clones this entity.
ccMesh * partialClone (const std::vector< unsigned > &triangleIndices, int *warnings=nullptr) const
Creates a new mesh from a selection of triangles (partial clone)
bool merge (const ccMesh *mesh, bool createSubMesh)
Merges another mesh into this one.
ccMesh & operator= (const ccMesh &mesh)
ccMesh & operator+= (const ccMesh &mesh)
ccMesh operator+ (const ccMesh &mesh) const
void clear ()
unsigned getUniqueIDForDisplay () const override
Returns object unqiue ID used for display.
ccBBox getOwnBB (bool withGLFeatures=false) override
Returns the entity's own bounding-box.
bool isSerializable () const override
Returns whether object is serializable of not.
const ccGLMatrix & getGLTransformationHistory () const override
Returns the transformation 'history' matrix.
ccGenericPointCloud * getAssociatedCloud () const override
Returns the vertices cloud.
void refreshBB () override
Forces bounding-box update.
bool interpolateNormalsBC (unsigned triIndex, const CCVector3d &w, CCVector3 &N) override
Interpolates normal(s) inside a given triangle.
bool interpolateColors (unsigned triIndex, const CCVector3 &P, ecvColor::Rgb &C) override
Interpolates RGB colors inside a given triangle.
void computeInterpolationWeights (unsigned triIndex, const CCVector3 &P, CCVector3d &weights) const override
Returns the (barycentric) interpolation weights for a given triangle.
bool getColorFromMaterial (unsigned triIndex, const CCVector3 &P, ecvColor::Rgb &C, bool interpolateColorIfNoTexture) override
bool getVertexColorFromMaterial (unsigned triIndex, unsigned char vertIndex, ecvColor::Rgb &C, bool returnColorIfNoTexture) override
unsigned capacity () const override
Returns max capacity.
void forEach (genericTriangleAction action) override
Fast iteration mechanism.
void placeIteratorAtBeginning () override
Places the mesh iterator at the beginning.
cloudViewer::GenericTriangle * _getNextTriangle () override
Returns the next triangle (relatively to the global iterator position)
cloudViewer::GenericTriangle * _getTriangle (unsigned triangleIndex) override
Returns the ith triangle.
cloudViewer::VerticesIndexes * getNextTriangleVertIndexes () override
cloudViewer::VerticesIndexes * getTriangleVertIndexes (unsigned triangleIndex) override
Returns the indexes of the vertices of a given triangle.
virtual void getTriangleVertices (unsigned triangleIndex, CCVector3 &A, CCVector3 &B, CCVector3 &C) const override
Returns the vertices of a given triangle.
virtual void getTriangleVertices (unsigned triangleIndex, double A[3], double B[3], double C[3]) const override
unsigned int getVerticeSize () const
Eigen::Vector3d getVertice (size_t index) const
void setVertice (size_t index, const Eigen::Vector3d &vertice)
void addVertice (const Eigen::Vector3d &vertice)
std::vector< Eigen::Vector3d > getEigenVertices () const
void addEigenVertices (const std::vector< Eigen::Vector3d > &vertices)
void setEigenVertices (const std::vector< Eigen::Vector3d > &vertices)
Eigen::Vector3d getVertexNormal (size_t index) const
void setVertexNormal (size_t index, const Eigen::Vector3d &normal)
void addVertexNormal (const Eigen::Vector3d &normal)
std::vector< Eigen::Vector3d > getVertexNormals () const
void addVertexNormals (const std::vector< Eigen::Vector3d > &normals)
void setVertexNormals (const std::vector< Eigen::Vector3d > &normals)
Eigen::Vector3d getVertexColor (size_t index) const
void setVertexColor (size_t index, const Eigen::Vector3d &color)
void addVertexColor (const Eigen::Vector3d &color)
std::vector< Eigen::Vector3d > getVertexColors () const
ColorsTableType * getVertexColorsPtr ()
void addVertexColors (const std::vector< Eigen::Vector3d > &colors)
void setVertexColors (const std::vector< Eigen::Vector3d > &colors)
bool HasVertices () const
std::vector< CCVector3 > & getVerticesPtr ()
const std::vector< CCVector3 > & getVertices () const
virtual unsigned size () const override
Returns the number of triangles.
void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax) override
Returns the mesh bounding-box.
bool normalsAvailable () const override
Returns whether normals are available.
bool interpolateNormals (unsigned triIndex, const CCVector3 &P, CCVector3 &N) override
Interpolates normal(s) inside a given triangle.
void getTriangleVertIndexes (size_t triangleIndex, Eigen::Vector3i &vertIndx) const
virtual const cloudViewer::VerticesIndexes * getTriangleVertIndexes (unsigned triangleIndex) const
bool hasColors () const override
Returns whether colors are enabled or not.
bool hasNormals () const override
Returns whether normals are enabled or not.
bool HasVertexNormals () const
bool hasScalarFields () const override
Returns whether one or more scalar fields are instantiated.
bool hasDisplayedScalarField () const override
Returns whether an active scalar field is available or not.
bool normalsShown () const override
Returns whether normals are shown or not.
void toggleMaterials () override
Toggles material display state.
void invertNormals ()
Inverts normals (if any)
void shiftTriangleIndexes (unsigned shift)
Shifts all triangles indexes.
void flipTriangles ()
Flips the triangle.
void addTriangle (unsigned i1, unsigned i2, unsigned i3)
Adds a triangle to the mesh.
void addTriangle (const cloudViewer::VerticesIndexes &triangle)
void addTriangle (const Eigen::Vector3i &index)
void addTriangles (const std::vector< Eigen::Vector3i > &triangles)
void setTriangle (size_t index, const Eigen::Vector3i &triangle)
void setTriangles (const std::vector< Eigen::Vector3i > &triangles)
Eigen::Vector3i getTriangle (size_t index) const
std::vector< Eigen::Vector3i > getTriangles () const
triangleIndexesContainer * getTrianglesPtr () const
bool reserve (std::size_t n)
Reserves the memory to store the vertex indexes (3 per triangle)
bool reserveAssociatedCloud (std::size_t n, bool init_color=false, bool init_normal=false)
bool resize (size_t n)
Resizes the array of vertex indexes (3 per triangle)
bool resizeAssociatedCloud (std::size_t n)
void shrinkToFit ()
Removes unused capacity.
void shrinkVertexToFit ()
bool hasTriNormals () const override
Returns whether the mesh has per-triangle normals.
bool HasTriangleNormals () const
void getTriangleNormalIndexes (unsigned triangleIndex, int &i1, int &i2, int &i3) const override
Returns a triplet of normal indexes for a given triangle (if any)
bool getTriangleNormals (unsigned triangleIndex, CCVector3 &Na, CCVector3 &Nb, CCVector3 &Nc) const override
Returns a given triangle normal.
bool getTriangleNormals (unsigned triangleIndex, double Na[3], double Nb[3], double Nc[3]) const override
bool getTriangleNormals (unsigned triangleIndex, Eigen::Vector3d &Na, Eigen::Vector3d &Nb, Eigen::Vector3d &Nc) const override
std::vector< Eigen::Vector3d > getTriangleNormals () const
std::vector< CCVector3 * > getTriangleNormalsPtr () const
Eigen::Vector3d getTriangleNorm (size_t index) const
bool setTriangleNorm (size_t index, const Eigen::Vector3d &triangle_normal)
bool setTriangleNormalIndexes (size_t triangleIndex, CompressedNormType value)
CompressedNormType getTriangleNormalIndexes (size_t triangleIndex)
bool addTriangleNorm (const CCVector3 &N)
bool addTriangleNorm (const Eigen::Vector3d &N)
std::vector< Eigen::Vector3d > getTriangleNorms () const
bool setTriangleNorms (const std::vector< Eigen::Vector3d > &triangle_normals)
bool addTriangleNorms (const std::vector< Eigen::Vector3d > &triangle_normals)
NormsIndexesTableType * getTriNormsTable () const override
Returns per-triangle normals shared array.
void setTriNormsTable (NormsIndexesTableType *triNormsTable, bool autoReleaseOldTable=true)
Sets per-triangle normals array (may be shared)
void clearTriNormals ()
Removes per-triangle normals.
bool arePerTriangleNormalsEnabled () const
Returns whether per triangle normals are enabled.
bool reservePerTriangleNormalIndexes ()
Reserves memory to store per-triangle triplets of normal indexes.
void addTriangleNormalIndexes (int i1, int i2, int i3)
Adds a triplet of normal indexes for next triangle.
void setTriangleNormalIndexes (unsigned triangleIndex, int i1, int i2, int i3)
Sets a triplet of normal indexes for a given triangle.
void removePerTriangleNormalIndexes ()
Removes any per-triangle triplets of normal indexes.
void invertPerTriangleNormals ()
Invert per-triangle normals.
bool hasMaterials () const override
const ccMaterialSet * getMaterialSet () const override
int getTriangleMtlIndex (unsigned triangleIndex) const override
Returns a given triangle material indexes.
bool convertMaterialsToVertexColors ()
Converts materials to vertex colors.
bool hasPerTriangleMtlIndexes () const
Returns whether this mesh as per-triangle material index.
bool reservePerTriangleMtlIndexes ()
Reserves memory to store per-triangle material index.
void removePerTriangleMtlIndexes ()
Removes any per-triangle material indexes.
void addTriangleMtlIndex (int mtlIndex)
Adds triangle material index for next triangle.
void setTriangleMtlIndexesTable (triangleMaterialIndexesSet *matIndexesTable, bool autoReleaseOldTable=true)
Sets per-triangle material indexes array.
const triangleMaterialIndexesSet * getTriangleMtlIndexesTable () const
Returns the per-triangle material indexes array.
void setTriangleMtlIndex (unsigned triangleIndex, int mtlIndex)
Sets triangle material indexes.
void setMaterialSet (ccMaterialSet *materialSet, bool autoReleaseOldMaterialSet=true)
Sets associated material set (may be shared)
bool hasTextures () const override
Returns whether textures are available for this mesh.
TextureCoordsContainer * getTexCoordinatesTable () const override
Returns per-triangle texture coordinates array.
void getTriangleTexCoordinates (unsigned triIndex, TexCoords2D *&tx1, TexCoords2D *&tx2, TexCoords2D *&tx3) const override
Returns per-triangle texture coordinates (pointer to)
void getTexCoordinates (unsigned index, TexCoords2D *&tx) const override
bool hasPerTriangleTexCoordIndexes () const override
Returns whether this mesh as per-triangle triplets of tex coords indexes.
void getTriangleTexCoordinatesIndexes (unsigned triangleIndex, int &i1, int &i2, int &i3) const override
Returns the triplet of tex coords indexes for a given triangle.
void setTexCoordinatesTable (TextureCoordsContainer *texCoordsTable, bool autoReleaseOldTable=true)
Sets per-triangle texture coordinates array (may be shared)
bool reservePerTriangleTexCoordIndexes ()
Reserves memory to store per-triangle triplets of tex coords indexes.
void removePerTriangleTexCoordIndexes ()
Remove per-triangle tex coords indexes.
void addTriangleTexCoordIndexes (int i1, int i2, int i3)
Adds a triplet of tex coords indexes for next triangle.
void setTriangleTexCoordIndexes (unsigned triangleIndex, int i1, int i2, int i3)
Sets a triplet of tex coords indexes for a given triangle.
bool computeNormals (bool perVertex)
Computes normals.
bool computePerVertexNormals ()
Computes per-vertex normals.
bool computePerTriangleNormals ()
Computes per-triangle normals.
bool laplacianSmooth (unsigned nbIteration=100, PointCoordinateType factor=static_cast< PointCoordinateType >(0.01), ecvProgressDialog *progressCb=nullptr)
Laplacian smoothing.
bool processScalarField (MESH_SCALAR_FIELD_PROCESS process)
ccMesh * subdivide (PointCoordinateType maxArea) const
ccMesh * createNewMeshFromSelection (bool removeSelectedTriangles, std::vector< int > *newIndexesOfRemainingTriangles=nullptr, bool withChildEntities=false)
Creates a new mesh with the selected vertices only.
void swapTriangles (unsigned index1, unsigned index2)
Swaps two triangles.
void removeTriangles (size_t index)
void transformTriNormals (const ccGLMatrix &trans)
Transforms the mesh per-triangle normals.
bool mergeDuplicatedVertices (unsigned char octreeLevel=DefaultMergeDulicateVerticesLevel, QWidget *parentWidget=nullptr)
Merges duplicated vertices.
bool hasAdjacencyList () const
Returns true if the mesh contains adjacency normals.
bool hasTriangleUvs () const
bool hasTriangleMaterialIds () const
bool hasEigenTextures () const
Returns true if the mesh has texture.
virtual bool IsEmpty () const override
virtual Eigen::Vector3d GetMinBound () const override
Returns min bounds for geometry coordinates.
virtual Eigen::Vector3d GetMaxBound () const override
Returns max bounds for geometry coordinates.
virtual Eigen::Vector3d GetCenter () const override
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const override
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const override
virtual ccMesh & Transform (const Eigen::Matrix4d &transformation) override
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual ccMesh & Translate (const Eigen::Vector3d &translation, bool relative=true) override
Apply translation to the geometry coordinates.
virtual ccMesh & Scale (const double s, const Eigen::Vector3d &center) override
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual ccMesh & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center) override
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
ccMesh & PaintUniformColor (const Eigen::Vector3d &color)
Assigns each vertex in the ccMesh the same color.
std::tuple< std::shared_ptr< ccMesh >, std::vector< size_t > > ComputeConvexHull () const
std::unordered_map< Eigen::Vector2i, double, cloudViewer::utility::hash_eigen< Eigen::Vector2i > > ComputeEdgeWeightsCot (const std::unordered_map< Eigen::Vector2i, std::vector< int >, cloudViewer::utility::hash_eigen< Eigen::Vector2i >> &edges_to_vertices, double min_weight=std::numeric_limits< double >::lowest()) const
Function that computes for each edge in the triangle mesh and passed as parameter edges_to_vertices the cot weight.
ccMesh & ComputeTriangleNormals (bool normalized=true)
Function to compute triangle normals, usually called before rendering.
ccMesh & ComputeVertexNormals (bool normalized=true)
Function to compute vertex normals, usually called before rendering.
ccMesh & NormalizeNormals ()
ccMesh & ComputeAdjacencyList ()
Function to compute adjacency list, call before adjacency list is.
ccMesh & RemoveDuplicatedVertices ()
Function that removes duplicated verties, i.e., vertices that have identical coordinates.
ccMesh & RemoveDuplicatedTriangles ()
Function that removes duplicated triangles, i.e., removes triangles that reference the same three vertices, independent of their order.
ccMesh & RemoveUnreferencedVertices ()
This function removes vertices from the triangle mesh that are not referenced in any triangle of the mesh.
ccMesh & RemoveDegenerateTriangles ()
Function that removes degenerate triangles, i.e., triangles that reference a single vertex multiple times in a single triangle.
ccMesh & RemoveNonManifoldEdges ()
Function that removes all non-manifold edges, by successively deleting triangles with the smallest surface area adjacent to the non-manifold edge until the number of adjacent triangles to the edge is <= 2.
ccMesh & MergeCloseVertices (double eps)
Function that will merge close by vertices to a single one. The vertex position, normal and color will be the average of the vertices.
std::shared_ptr< ccMesh > FilterSharpen (int number_of_iterations, double strength, FilterScope scope=FilterScope::All) const
Function to sharpen triangle mesh.
std::shared_ptr< ccMesh > FilterSmoothSimple (int number_of_iterations, FilterScope scope=FilterScope::All) const
Function to smooth triangle mesh with simple neighbour average.
std::shared_ptr< ccMesh > FilterSmoothLaplacian (int number_of_iterations, double lambda, FilterScope scope=FilterScope::All) const
Function to smooth triangle mesh using Laplacian.
std::shared_ptr< ccMesh > FilterSmoothTaubin (int number_of_iterations, double lambda=0.5, double mu=-0.53, FilterScope scope=FilterScope::All) const
Function to smooth triangle mesh using method of Taubin, "Curve and Surface Smoothing Without Shrinkage", 1995. Applies in each iteration two times FilterSmoothLaplacian, first with lambda and second with mu as smoothing parameter. This method avoids shrinkage of the triangle mesh.
int EulerPoincareCharacteristic () const
std::vector< Eigen::Vector2i > GetNonManifoldEdges (bool allow_boundary_edges=true) const
bool IsEdgeManifold (bool allow_boundary_edges=true) const
std::vector< int > GetNonManifoldVertices () const
bool IsVertexManifold () const
std::vector< Eigen::Vector2i > GetSelfIntersectingTriangles () const
bool IsSelfIntersecting () const
bool IsBoundingBoxIntersecting (const ccMesh &other) const
bool IsIntersecting (const ccMesh &other) const
bool IsOrientable () const
bool IsWatertight () const
bool OrientTriangles ()
std::unordered_map< Eigen::Vector2i, std::vector< int >, cloudViewer::utility::hash_eigen< Eigen::Vector2i > > GetEdgeToTrianglesMap () const
std::unordered_map< Eigen::Vector2i, std::vector< int >, cloudViewer::utility::hash_eigen< Eigen::Vector2i > > GetEdgeToVerticesMap () const
double GetTriangleArea (size_t triangle_idx) const
double GetSurfaceArea () const
double GetSurfaceArea (std::vector< double > &triangle_areas) const
double GetVolume () const
Eigen::Vector4d GetTrianglePlane (size_t triangle_idx) const
std::shared_ptr< ccPointCloud > SamplePointsUniformlyImpl (size_t number_of_points, std::vector< double > &triangle_areas, double surface_area, bool use_triangle_normal, int seed)
std::shared_ptr< ccPointCloud > SamplePointsUniformly (size_t number_of_points, bool use_triangle_normal=false, int seed=-1)
std::shared_ptr< ccPointCloud > SamplePointsPoissonDisk (size_t number_of_points, double init_factor=5, const std::shared_ptr< ccPointCloud > pcl_init=nullptr, bool use_triangle_normal=false, int seed=-1)
std::shared_ptr< ccMesh > SubdivideMidpoint (int number_of_iterations) const
std::shared_ptr< ccMesh > SubdivideLoop (int number_of_iterations) const
std::shared_ptr< ccMesh > SimplifyVertexClustering (double voxel_size, SimplificationContraction contraction=SimplificationContraction::Average) const
std::shared_ptr< ccMesh > SimplifyQuadricDecimation (int target_number_of_triangles, double maximum_error=std::numeric_limits< double >::infinity(), double boundary_weight=1.0) const
std::shared_ptr< ccMesh > SelectByIndex (const std::vector< size_t > &indices, bool cleanup=true) const
std::shared_ptr< ccMesh > Crop (const ccBBox &bbox) const
std::shared_ptr< ccMesh > Crop (const ecvOrientedBBox &bbox) const
std::tuple< std::vector< int >, std::vector< size_t >, std::vector< double > > ClusterConnectedTriangles () const
Function that clusters connected triangles, i.e., triangles that are connected via edges are assigned the same cluster index.
void RemoveTrianglesByIndex (const std::vector< size_t > &triangle_indices)
This function removes the triangles with index in triangle_indices. Call RemoveUnreferencedVertices to clean up vertices afterwards.
void RemoveTrianglesByMask (const std::vector< bool > &triangle_mask)
This function removes the triangles that are masked in triangle_mask. Call RemoveUnreferencedVertices to clean up vertices afterwards.
void RemoveVerticesByIndex (const std::vector< size_t > &vertex_indices)
This function removes the vertices with index in vertex_indices. Note that also all triangles associated with the vertices are removeds.
void RemoveVerticesByMask (const std::vector< bool > &vertex_mask)
This function removes the vertices that are masked in vertex_mask. Note that also all triangles associated with the vertices are removed..
std::shared_ptr< ccMesh > DeformAsRigidAsPossible (const std::vector< int > &constraint_vertex_indices, const std::vector< Eigen::Vector3d > &constraint_vertex_positions, size_t max_iter, DeformAsRigidAsPossibleEnergy energy=DeformAsRigidAsPossibleEnergy::Spokes, double smoothed_alpha=0.01) const
This function deforms the mesh using the method by Sorkine and Alexa, "As-Rigid-As-Possible Surface Modeling", 2007.
Public Member Functions inherited from ccGenericMesh
ccGenericMesh (QString name=QString())
Default constructor.
~ccGenericMesh () override=default
Destructor.
void showNormals (bool state) override
Sets normals visibility.
virtual bool isShownAsWire () const
Returns whether the mesh is displayed as wired or with plain facets.
virtual void showWired (bool state)
Sets whether mesh should be displayed as a wire or with plain facets.
virtual bool isShownAsPoints () const
Returns whether the mesh is displayed as wired or with plain facets.
virtual void showPoints (bool state)
virtual bool triNormsShown () const
Returns whether per-triangle normals are shown or not.
virtual void showTriNorms (bool state)
Sets whether to show or not per-triangle normals.
virtual bool materialsShown () const
Sets whether textures/material should be displayed or not.
virtual void showMaterials (bool state)
Sets whether textures should be displayed or not.
virtual bool stipplingEnabled () const
Returns whether polygon stippling is enabled or not.
void enableStippling (bool state)
Enables polygon stippling.
ccPointCloud * samplePoints (bool densityBased, double samplingParameter, bool withNormals, bool withRGB, bool withTexture, cloudViewer::GenericProgressCallback *pDlg=nullptr)
Samples points on a mesh.
void importParametersFrom (const ccGenericMesh *mesh)
Imports the parameters from another mesh.
virtual bool trianglePicking (const CCVector2d &clickPos, const ccGLCameraParameters &camera, int &nearestTriIndex, double &nearestSquareDist, CCVector3d &nearestPoint, CCVector3d *barycentricCoords=nullptr) const
Brute force triangle picking.
virtual bool trianglePicking (unsigned triIndex, const CCVector2d &clickPos, const ccGLCameraParameters &camera, CCVector3d &point, CCVector3d *barycentricCoords=nullptr) const
Triangle picking (single triangle)
bool computePointPosition (unsigned triIndex, const CCVector2d &uv, CCVector3 &P, bool warningIfOutside=true) const
void setGlobalShift (const CCVector3d &shift) override
Sets shift applied to original coordinates (information storage only)
void setGlobalScale (double scale) override
const CCVector3d & getGlobalShift () const override
Returns the shift applied to original coordinates.
double getGlobalScale () const override
Returns the scale applied to original coordinates.
bool updateTextures (const std::string &texture_file)
bool updateTextures (const std::vector< std::string > &texture_files)
Public Member Functions inherited from cloudViewer::GenericIndexedMesh
GenericIndexedMesh ()=default
~GenericIndexedMesh () override=default
Default destructor.
Public Member Functions inherited from cloudViewer::GenericMesh
GenericMesh ()=default
virtual ~GenericMesh ()=default
Default destructor.
virtual bool hasTriangles () const
Public Member Functions inherited from ccShiftedObject
ccShiftedObject (QString name=QString())
Default constructor.
ccShiftedObject (const ccShiftedObject &s)
Copy constructor.
void copyGlobalShiftAndScale (const ccShiftedObject &s)
Copies the Global Shift and Scale from another entity.
virtual void setGlobalShift (double x, double y, double z)
Sets shift applied to original coordinates (information storage only)
bool isShifted () const
Returns whether the cloud is shifted or not.
template<typename T >
CCVector3d toGlobal3d (const Vector3Tpl< T > &Plocal) const
Returns the point back-projected into the original coordinates system.
template<typename T >
CCVector3d toLocal3d (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
template<typename T >
CCVector3 toLocal3pc (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner) override
GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false) override
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual Eigen::Vector2d GetMin2DBound () const
virtual Eigen::Vector2d GetMax2DBound () const
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual ccBBox getOwnFitBB (ccGLMatrix &trans)
Returns best-fit bounding-box (if available)
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col)
Draws the entity (and its children) bounding-box.
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
virtual void notifyGeometryUpdate ()
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual void getDrawingParameters (glDrawParams &params) const
Returns main OpenGL parameters for this entity.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual void toggleNormals ()
Toggles normals display state.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Static Public Attributes
static const unsigned DEFAULT_DRAWING_PRECISION = 24
Default drawing precision.
Static Public Attributes inherited from ccGenericPrimitive
static const int MIN_DRAWING_PRECISION = 4
Minimum drawing precision.
Static Public Attributes inherited from ccMesh
static const unsigned char DefaultMergeDulicateVerticesLevel = 10
Default octree level for the 'mergeDuplicatedVertices' algorithm.
Protected Member Functions
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
virtual bool buildUp () override
Builds primitive.
Protected Member Functions inherited from ccGenericPrimitive
void applyGLTransformation (const ccGLMatrix &trans) override
Inherited from ccGenericMesh.
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
virtual bool updateRepresentation ()
Updates internal representation (as a mesh)
bool init (unsigned vertCount, bool vertNormals, unsigned faceCount, unsigned faceNormCount)
Inits internal structures.
void applyTransformationToVertices ()
Applies associated transformation to vertices.
ccGenericPrimitive * finishCloneJob (ccGenericPrimitive *primitive) const
Finished 'clone' job (vertices color, etc.)
ccPointCloud * vertices ()
Returns vertices.
Protected Member Functions inherited from ccMesh
void FilterSmoothLaplacianHelper (std::shared_ptr< ccMesh > &mesh, const std::vector< CCVector3 > &prev_vertices, const std::vector< CCVector3 > &prev_vertex_normals, const ColorsTableType &prev_vertex_colors, const std::vector< std::unordered_set< int >> &adjacency_list, double lambda, bool filter_vertex, bool filter_normal, bool filter_color) const
void drawMeOnly (CC_DRAW_CONTEXT &context) override
Enables (OpenGL) stipple mask.
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
void applyGLTransformation (const ccGLMatrix &trans) override
Applies a GL transformation to the entity.
void onUpdateOf (ccHObject *obj) override
This method is called when another object (geometry) is updated.
void onDeletionOf (const ccHObject *obj) override
This method is called when another object is deleted.
void computeInterpolationWeights (const cloudViewer::VerticesIndexes &vertIndexes, const CCVector3 &P, CCVector3d &weights) const
bool interpolateNormals (const cloudViewer::VerticesIndexes &vertIndexes, const CCVector3d &w, CCVector3 &N, const Tuple3i *triNormIndexes=nullptr)
bool interpolateColors (const cloudViewer::VerticesIndexes &vertIndexes, const CCVector3 &P, ecvColor::Rgb &C)
bool pushSubdivide (unsigned indexA, unsigned indexB, unsigned indexC)
Used internally by 'subdivide'.
virtual void showNormals_extended (bool p)
Protected Member Functions inherited from ccGenericMesh
virtual bool trianglePicking (unsigned triIndex, const CCVector2d &clickPos, const ccGLMatrix &trans, bool noGLTrans, const ccGenericPointCloud &vertices, const ccGLCameraParameters &camera, CCVector3d &point, CCVector3d *barycentricCoords=nullptr) const
Triangle picking (single triangle)
void handleColorRamp (CC_DRAW_CONTEXT &context)
Handles the color ramp display.
Protected Member Functions inherited from ccShiftedObject
bool saveShiftInfoToFile (QFile &out) const
Serialization helper (output)
bool loadShiftInfoFromFile (QFile &in)
Serialization helper (input)
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void drawNameIn3D ()
Draws the entity name in 3D.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Protected Attributes
PointCoordinateType m_bottomRadius
Bottom radius.
PointCoordinateType m_topRadius
Top radius.
PointCoordinateType m_xOff
Displacement of axes along X-axis (Snout mode)
PointCoordinateType m_yOff
Displacement of axes along Y-axis (Snout mode)
PointCoordinateType m_height
Height.
Protected Attributes inherited from ccGenericPrimitive
ccGLMatrix m_transformation
Associated transformation (applied to vertices)
unsigned m_drawPrecision
Drawing precision (for primitives that support this feature)
Protected Attributes inherited from ccMesh
ccGenericPointCloud * m_associatedCloud
associated cloud (vertices)
NormsIndexesTableType * m_triNormals
Per-triangle normals.
TextureCoordsContainer * m_texCoords
Texture coordinates.
ccMaterialSet * m_materials
Materials.
triangleIndexesContainer * m_triVertIndexes
Triangles' vertices indexes (3 per triangle)
unsigned m_globalIterator
Iterator on the list of triangles.
cloudViewer::SimpleRefTriangle m_currentTriangle
Dump triangle structure to transmit temporary data.
ccBBox m_bBox
Bounding-box.
triangleMaterialIndexesSet * m_triMtlIndexes
Per-triangle material indexes.
triangleTexCoordIndexesSet * m_texCoordIndexes
Mesh tex coords indexes (per-triangle)
triangleNormalsIndexesSet * m_triNormalIndexes
Mesh normals indexes (per-triangle)
Protected Attributes inherited from ccGenericMesh
bool m_triNormsShown
Per-triangle normals display flag.
bool m_materialsShown
Texture/material display flag.
bool m_showWired
Wireframe display mode.
bool m_showPoints
points display mode
bool m_stippling
Polygon stippling state.
Protected Attributes inherited from ccShiftedObject
CCVector3d m_globalShift
Global shift (typically applied at loading time)
double m_globalScale
Global scale (typically applied at loading time)
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Additional Inherited Members
Public Types inherited from ccMesh
enum MESH_SCALAR_FIELD_PROCESS { SMOOTH_MESH_SF , ENHANCE_MESH_SF }
Mesh scalar field processes.
using triangleIndexesContainer = ccArray< cloudViewer::VerticesIndexes, 3, unsigned >
Container of per-triangle vertices indexes (3)
using triangleMaterialIndexesSet = ccArray< int, 1, int >
Container of per-triangle material descriptors.
Public Types inherited from cloudViewer::GenericMesh
enum class SimplificationContraction { Average , Quadric }
Indicates the method that is used for mesh simplification if multiple vertices are combined to a single one.
enum class FilterScope { All , Color , Normal , Vertex }
Indicates the scope of filter operations.
enum class DeformAsRigidAsPossibleEnergy { Spokes , Smoothed }
using genericTriangleAction = std::function< void(GenericTriangle &)>
Generic function to apply to a triangle (used by foreach)
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Static Public Member Functions inherited from ccMesh
static cloudViewer::VerticesIndexes GetOrderedTriangle (int vidx0, int vidx1, int vidx2)
static ccMesh * Triangulate (ccGenericPointCloud *cloud, cloudViewer::TRIANGULATION_TYPES type, bool updateNormals=false, PointCoordinateType maxEdgeLength=0, unsigned char dim=2)
Creates a Delaunay 2.5D mesh from a point cloud.
static ccMesh * TriangulateTwoPolylines (ccPolyline *p1, ccPolyline *p2, CCVector3 *projectionDir=nullptr)
Creates a Delaunay 2.5D mesh from two polylines.
static double ComputeTriangleArea (const Eigen::Vector3d &p0, const Eigen::Vector3d &p1, const Eigen::Vector3d &p2)
Function that computes the area of a mesh triangle.
static Eigen::Vector3i GetEigneOrderedTriangle (int vidx0, int vidx1, int vidx2)
static Eigen::Vector4d ComputeTrianglePlane (const Eigen::Vector3d &p0, const Eigen::Vector3d &p1, const Eigen::Vector3d &p2)
static Eigen::Vector2i GetOrderedEdge (int vidx0, int vidx1)
Helper function to get an edge with ordered vertex indices.
static std::shared_ptr< ccMesh > CreateFromPointCloudAlphaShape (const ccPointCloud &pcd, double alpha, std::shared_ptr< cloudViewer::geometry::TetraMesh > tetra_mesh=nullptr, std::vector< size_t > *pt_map=nullptr)
Alpha shapes are a generalization of the convex hull. With decreasing alpha value the shape schrinks and creates cavities. See Edelsbrunner and Muecke, "Three-Dimensional Alpha Shapes", 1994.
static std::shared_ptr< ccMesh > CreateFromPointCloudBallPivoting (const ccPointCloud &pcd, const std::vector< double > &radii)
static std::tuple< std::shared_ptr< ccMesh >, std::vector< double > > CreateFromPointCloudPoisson (const ccPointCloud &pcd, size_t depth=8, size_t width=0, float scale=1.1f, bool linear_fit=false, float point_weight=2.f, float samples_per_node=1.5f, int boundary_type=2, int n_threads=-1)
Function that computes a triangle mesh from a oriented PointCloud pcd. This implements the Screened Poisson Reconstruction proposed in Kazhdan and Hoppe, "Screened Poisson Surface Reconstruction", 2013. This function uses the original implementation by Kazhdan. See https://github.com/mkazhdan/PoissonRecon.
static std::shared_ptr< ccMesh > CreateTetrahedron (double radius=1.0, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreateOctahedron (double radius=1.0, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreateIcosahedron (double radius=1.0, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreatePlane (double width=1.0, double height=1.0, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreateBox (double width=1.0, double height=1.0, double depth=1.0, bool create_uv_map=false, bool map_texture_to_each_face=false)
static std::shared_ptr< ccMesh > CreateSphere (double radius=1.0, int resolution=20, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreateCylinder (double radius=1.0, double height=2.0, int resolution=20, int split=4, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreateCone (double radius=1.0, double height=2.0, int resolution=20, int split=1, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreateTorus (double torus_radius=1.0, double tube_radius=0.5, int radial_resolution=30, int tubular_resolution=20)
static std::shared_ptr< ccMesh > CreateArrow (double cylinder_radius=1.0, double cone_radius=1.5, double cylinder_height=5.0, double cone_height=4.0, int resolution=20, int cylinder_split=4, int cone_split=1)
static std::shared_ptr< ccMesh > CreateCoordinateFrame (double size=1.0, const Eigen::Vector3d &origin=Eigen::Vector3d(0.0, 0.0, 0.0))
static std::shared_ptr< ccMesh > CreateMobius (int length_split=70, int width_split=15, int twists=1, double radius=1, double flatness=1, double width=1, double scale=1)
Static Public Member Functions inherited from ccGenericMesh
static bool IsCloudVerticesOfMesh (ccGenericPointCloud *cloud, ccGenericMesh **mesh=nullptr)
Helper to determine if the input cloud acts as vertices of a mesh.
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Public Attributes inherited from ccMesh
std::vector< std::unordered_set< int > > adjacency_list_
std::vector< Eigen::Vector2d > triangle_uvs_
List of uv coordinates per triangle.
std::vector< std::pair< std::string, Material > > materials_
std::vector< int > triangle_material_ids_
List of material ids.
std::vector< cloudViewer::geometry::Image > textures_
Textures of the image.
Protected Types inherited from ccMesh
using triangleTexCoordIndexesSet = ccArray< Tuple3i, 3, int >
Set of triplets of indexes referring to mesh texture coordinates.
using triangleNormalsIndexesSet = ccArray< Tuple3i, 3, int >
Set of triplets of indexes referring to mesh normals.
Static Protected Member Functions inherited from ccGenericMesh
static CCVector3 * GetVertexBuffer ()
static CCVector3 * GetNormalsBuffer ()
static ecvColor::Rgb * GetColorsBuffer ()
static unsigned * GetWireVertexIndexes ()
Returns a pre-initialized array of vertex indexes for wired display.
Detailed Description
Cone (primitive)
3D cone primitive
Definition at line 16 of file ecvCone.h.
Constructor & Destructor Documentation
ccCone() [1/2]
ccCone::ccCone (PointCoordinateType bottomRadius, PointCoordinateType topRadius, PointCoordinateType height, PointCoordinateType xOff = 0, PointCoordinateType yOff = 0, const ccGLMatrix * transMat = 0, QString name = QString("Cone"), unsigned precision = DEFAULT_DRAWING_PRECISION)
Default constructor.
Cone axis corresponds to the 'Z' dimension by default
Parameters
bottomRadius cone bottom radius
topRadius cone top radius
height cone height (transformation should point to the axis center)
xOff displacement of axes along X-axis (Snout mode)
yOff displacement of axes along Y-axis (Snout mode)
transMat optional 3D transformation (can be set afterwards with ccDrawableObject::setGLTransformation)
name name
precision drawing precision (angular step = 360/precision)
Definition at line 14 of file ecvCone.cpp.
References ccGenericPrimitive::MIN_DRAWING_PRECISION, and ccGenericPrimitive::setDrawingPrecision().
Referenced by clone().
ccCone() [2/2]
ccCone::ccCone (QString name = QString("Cone"))
Simplified constructor.
For ccHObject factory only!
Definition at line 34 of file ecvCone.cpp.
Member Function Documentation
buildUp()
bool ccCone::buildUp () override protected virtual
Builds primitive.
Transformation will be applied afterwards!
Returns
success
Implements ccGenericPrimitive.
Definition at line 48 of file ecvCone.cpp.
References ccArray< Type, N, ComponentType >::addElement(), cloudViewer::PointCloudTpl< T >::addPoint(), ccMesh::addTriangle(), ccMesh::addTriangleNormalIndexes(), Vector3Tpl< Type >::cross(), CVLog::Error(), ccNormalVectors::GetNormIndex(), ccGenericPrimitive::init(), cloudViewer::LessThanEpsilon(), m_bottomRadius, ccGenericPrimitive::m_drawPrecision, m_height, M_PI, m_topRadius, ccMesh::m_triNormals, ccMesh::m_triVertIndexes, m_xOff, m_yOff, ccGenericPrimitive::MIN_DRAWING_PRECISION, Vector3Tpl< Type >::normalize(), ccHObject::notifyGeometryUpdate(), ccGenericMesh::showTriNorms(), Tuple3Tpl< Type >::u, ccGenericPrimitive::vertices(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by setBottomRadius(), setHeight(), and setTopRadius().
clone()
ccGenericPrimitive * ccCone::clone () const override virtual
Clones primitive.
Implements ccGenericPrimitive.
Reimplemented in ccCylinder.
Definition at line 42 of file ecvCone.cpp.
References ccCone(), ccGenericPrimitive::finishCloneJob(), ccObject::getName(), m_bottomRadius, ccGenericPrimitive::m_drawPrecision, m_height, m_topRadius, ccGenericPrimitive::m_transformation, m_xOff, and m_yOff.
fromFile_MeOnly()
bool ccCone::fromFile_MeOnly (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override protected virtual
Loads own object data.
Called by 'fromFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
in input file
dataVersion file version
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Reimplemented from ccHObject.
Definition at line 299 of file ecvCone.cpp.
getBottomCenter()
CCVector3 ccCone::getBottomCenter () const virtual
Returns cone axis bottom end point after applying transformation.
Definition at line 233 of file ecvCone.cpp.
References ccGLMatrixTpl< T >::apply(), ccGenericPrimitive::getGLTransformationHistory(), m_height, m_xOff, and m_yOff.
Referenced by define_ccCone(), getLargeCenter(), and getSmallCenter().
getBottomRadius()
PointCoordinateType ccCone::getBottomRadius () const inline
Returns bottom radius.
Definition at line 60 of file ecvCone.h.
Referenced by define_ccCone(), define_ccCylinder(), GetConeProfile(), and ccPropertiesTreeDelegate::setEditorData().
getClassID()
virtual CV_CLASS_ENUM ccCone::getClassID () const inline override virtual
Returns class ID.
Implements ccObject.
Reimplemented in ccCylinder.
Definition at line 49 of file ecvCone.h.
References CV_TYPES::CONE.
getHeight()
PointCoordinateType ccCone::getHeight () const inline
Returns height.
Definition at line 52 of file ecvCone.h.
Referenced by define_ccCone(), GetConeProfile(), and ccPropertiesTreeDelegate::setEditorData().
getLargeCenter()
CCVector3 ccCone::getLargeCenter () const virtual
Returns cone axis end point associated with whichever radii is larger.
Definition at line 253 of file ecvCone.cpp.
References getBottomCenter(), getTopCenter(), m_bottomRadius, and m_topRadius.
Referenced by define_ccCone().
getLargeRadius()
PointCoordinateType ccCone::getLargeRadius () const virtual
Returns whichever cone radii is larger.
Definition at line 267 of file ecvCone.cpp.
References m_bottomRadius, and m_topRadius.
Referenced by define_ccCone().
getSmallCenter()
CCVector3 ccCone::getSmallCenter () const virtual
Returns cone axis end point associated with whichever radii is smaller.
Definition at line 246 of file ecvCone.cpp.
References getBottomCenter(), getTopCenter(), m_bottomRadius, and m_topRadius.
Referenced by define_ccCone().
getSmallRadius()
PointCoordinateType ccCone::getSmallRadius () const virtual
Returns whichever cone radii is smaller.
Definition at line 260 of file ecvCone.cpp.
References m_bottomRadius, and m_topRadius.
Referenced by define_ccCone().
getTopCenter()
CCVector3 ccCone::getTopCenter () const virtual
Returns cone axis top end point after applying transformation.
Definition at line 239 of file ecvCone.cpp.
References ccGLMatrixTpl< T >::apply(), ccGenericPrimitive::getGLTransformationHistory(), m_height, m_xOff, and m_yOff.
Referenced by define_ccCone(), getLargeCenter(), and getSmallCenter().
getTopRadius()
PointCoordinateType ccCone::getTopRadius () const inline
Returns top radius.
Definition at line 70 of file ecvCone.h.
Referenced by define_ccCone(), GetConeProfile(), and ccPropertiesTreeDelegate::setEditorData().
getTypeName()
virtual QString ccCone::getTypeName () const inline override virtual
Returns type name (sphere, cylinder, etc.)
Implements ccGenericPrimitive.
Reimplemented in ccCylinder.
Definition at line 97 of file ecvCone.h.
hasDrawingPrecision()
virtual bool ccCone::hasDrawingPrecision () const inline override virtual
Whether drawing is dependent on 'precision' parameter.
Reimplemented from ccGenericPrimitive.
Definition at line 98 of file ecvCone.h.
isSnoutMode()
virtual bool ccCone::isSnoutMode () const inline virtual
Returns true if the Cone was created in snout mode.
Definition at line 94 of file ecvCone.h.
Referenced by define_ccCone().
minimumFileVersion_MeOnly()
short ccCone::minimumFileVersion_MeOnly () const override protected virtual
Returns the minimum file version required to save this instance's own data To be overloaded (but still called ;) by subclass. Used internally by minimumFileVersion() to compute the overall minimum.
Reimplemented from ccHObject.
Definition at line 294 of file ecvCone.cpp.
References ccGenericPrimitive::minimumFileVersion_MeOnly().
setBottomRadius()
void ccCone::setBottomRadius (PointCoordinateType radius) virtual
Sets bottom radius.
Warning
changes primitive content (calls ccGenericPrimitive::updateRepresentation)
Reimplemented in ccCylinder.
Definition at line 213 of file ecvCone.cpp.
References ccGenericPrimitive::applyTransformationToVertices(), buildUp(), and m_bottomRadius.
Referenced by define_ccCone(), ccCylinder::setBottomRadius(), and ccCylinder::setTopRadius().
setHeight()
void ccCone::setHeight (PointCoordinateType height)
Sets height.
Warning
changes primitive content (calls ccGenericPrimitive::updateRepresentation)
Definition at line 203 of file ecvCone.cpp.
References ccGenericPrimitive::applyTransformationToVertices(), buildUp(), height, and m_height.
Referenced by define_ccCone().
setTopRadius()
void ccCone::setTopRadius (PointCoordinateType radius) virtual
Sets top radius.
Warning
changes primitive content (calls ccGenericPrimitive::updateRepresentation)
Reimplemented in ccCylinder.
Definition at line 223 of file ecvCone.cpp.
References ccGenericPrimitive::applyTransformationToVertices(), buildUp(), and m_topRadius.
Referenced by define_ccCone().
toFile_MeOnly()
bool ccCone::toFile_MeOnly (QFile & out, short dataVersion) const override protected virtual
Save own object data.
Called by 'toFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
out output file
dataVersion target file version for compatibility control
Reimplemented from ccHObject.
Definition at line 274 of file ecvCone.cpp.
Member Data Documentation
DEFAULT_DRAWING_PRECISION
const unsigned ccCone::DEFAULT_DRAWING_PRECISION = 24 static
Default drawing precision.
Warning
Never pass a 'constant initializer' by reference
Definition at line 21 of file ecvCone.h.
Referenced by define_ccCone().
m_bottomRadius
PointCoordinateType ccCone::m_bottomRadius protected
Bottom radius.
Definition at line 112 of file ecvCone.h.
Referenced by buildUp(), clone(), ccCylinder::clone(), getLargeCenter(), getLargeRadius(), getSmallCenter(), getSmallRadius(), and setBottomRadius().
m_height
PointCoordinateType ccCone::m_height protected
Height.
Definition at line 124 of file ecvCone.h.
Referenced by buildUp(), clone(), ccCylinder::clone(), getBottomCenter(), getTopCenter(), and setHeight().
m_topRadius
PointCoordinateType ccCone::m_topRadius protected
Top radius.
Definition at line 115 of file ecvCone.h.
Referenced by buildUp(), clone(), getLargeCenter(), getLargeRadius(), getSmallCenter(), getSmallRadius(), ccCylinder::setBottomRadius(), and setTopRadius().
m_xOff
PointCoordinateType ccCone::m_xOff protected
Displacement of axes along X-axis (Snout mode)
Definition at line 118 of file ecvCone.h.
Referenced by buildUp(), clone(), getBottomCenter(), and getTopCenter().
m_yOff
PointCoordinateType ccCone::m_yOff protected
Displacement of axes along Y-axis (Snout mode)
Definition at line 121 of file ecvCone.h.
Referenced by buildUp(), clone(), getBottomCenter(), and getTopCenter().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/ecvCone.h
/root/ACloudViewer/libs/CV_db/src/ecvCone.cpp