ACloudViewer: vtkCameraManipulator Class Reference
vtkCameraManipulator Class Reference
#include <vtkCameraManipulator.h>
Public Member Functions
vtkTypeMacro (vtkCameraManipulator, vtkObject)
void PrintSelf (ostream &os, vtkIndent indent) override
virtual void StartInteraction ()
virtual void EndInteraction ()
virtual void OnMouseMove (int x, int y, vtkRenderer *ren, vtkRenderWindowInteractor *iren)
virtual void OnButtonDown (int x, int y, vtkRenderer *ren, vtkRenderWindowInteractor *iren)
virtual void OnButtonUp (int x, int y, vtkRenderer *ren, vtkRenderWindowInteractor *iren)
virtual void OnKeyUp (vtkRenderWindowInteractor *iren)
virtual void OnKeyDown (vtkRenderWindowInteractor *iren)
vtkSetMacro (Button, int)
vtkGetMacro (Button, int)
vtkSetMacro (Shift, int)
vtkGetMacro (Shift, int)
vtkBooleanMacro (Shift, int)
vtkSetMacro (Control, int)
vtkGetMacro (Control, int)
vtkBooleanMacro (Control, int)
vtkSetVector3Macro (Center, double)
vtkGetVector3Macro (Center, double)
vtkSetMacro (RotationFactor, double)
vtkGetMacro (RotationFactor, double)
vtkSetStringMacro (ManipulatorName)
vtkGetStringMacro (ManipulatorName)
void SetGUIHelper (vtkCameraManipulatorGUIHelper *)
vtkGetObjectMacro (GUIHelper, vtkCameraManipulatorGUIHelper)
Static Public Member Functions
static vtkCameraManipulator * New ()
Protected Member Functions
vtkCameraManipulator ()
~vtkCameraManipulator () override
void ComputeDisplayCenter (vtkRenderer *ren)
Protected Attributes
char * ManipulatorName
int Button
int Shift
int Control
double Center [3]
double RotationFactor
double DisplayCenter [2]
vtkCameraManipulatorGUIHelper * GUIHelper
Detailed Description
Definition at line 17 of file vtkCameraManipulator.h.
Constructor & Destructor Documentation
vtkCameraManipulator()
vtkCameraManipulator::vtkCameraManipulator () protected
Definition at line 26 of file vtkCameraManipulator.cxx.
References Button, Center, Control, DisplayCenter, GUIHelper, ManipulatorName, RotationFactor, and Shift.
~vtkCameraManipulator()
vtkCameraManipulator::~vtkCameraManipulator () override protected
Definition at line 41 of file vtkCameraManipulator.cxx.
References SetGUIHelper().
Member Function Documentation
ComputeDisplayCenter()
void vtkCameraManipulator::ComputeDisplayCenter (vtkRenderer * ren) protected
Definition at line 83 of file vtkCameraManipulator.cxx.
References Center, and DisplayCenter.
Referenced by vtkPVTrackballRotate::OnButtonDown(), and vtkPVTrackballRoll::OnMouseMove().
EndInteraction()
void vtkCameraManipulator::EndInteraction () virtual
Definition at line 53 of file vtkCameraManipulator.cxx.
Referenced by VTKExtensions::vtkCustomInteractorStyle::OnButtonUp(), and vtkPVInteractorStyle::OnButtonUp().
New()
static vtkCameraManipulator* vtkCameraManipulator::New () static
OnButtonDown()
void vtkCameraManipulator::OnButtonDown (int x, int y, vtkRenderer * ren, vtkRenderWindowInteractor * iren) virtual
Reimplemented in vtkPVTrackballZoomToMouse, vtkPVTrackballZoom, vtkPVTrackballRotate, vtkPVTrackballRoll, vtkPVTrackballMultiRotate, vtkPVJoystickFly, vtkTrackballPan, vtkPVTrackballPan, and vtkPVTrackballMoveActor.
Definition at line 58 of file vtkCameraManipulator.cxx.
Referenced by VTKExtensions::vtkCustomInteractorStyle::OnButtonDown(), vtkPVInteractorStyle::OnButtonDown(), and vtkPVTrackballMultiRotate::OnButtonDown().
OnButtonUp()
void vtkCameraManipulator::OnButtonUp (int x, int y, vtkRenderer * ren, vtkRenderWindowInteractor * iren) virtual
Reimplemented in vtkPVTrackballZoom, vtkPVTrackballRotate, vtkPVTrackballRoll, vtkPVTrackballMultiRotate, vtkPVJoystickFly, vtkTrackballPan, vtkPVTrackballPan, and vtkPVTrackballMoveActor.
Definition at line 63 of file vtkCameraManipulator.cxx.
Referenced by VTKExtensions::vtkCustomInteractorStyle::OnButtonUp(), vtkPVInteractorStyle::OnButtonUp(), and vtkPVTrackballMultiRotate::OnButtonUp().
OnKeyDown()
void vtkCameraManipulator::OnKeyDown (vtkRenderWindowInteractor * iren) virtual
Reimplemented in vtkPVTrackballRotate.
Definition at line 78 of file vtkCameraManipulator.cxx.
Referenced by VTKExtensions::vtkCustomInteractorStyle::OnKeyDown(), and vtkPVInteractorStyle::OnKeyDown().
OnKeyUp()
void vtkCameraManipulator::OnKeyUp (vtkRenderWindowInteractor * iren) virtual
These methods are called on all registered manipulators, not just the active one. Hence, these should just be used to record state and not perform any interactions.
Reimplemented in vtkPVTrackballRotate.
Definition at line 73 of file vtkCameraManipulator.cxx.
Referenced by VTKExtensions::vtkCustomInteractorStyle::OnKeyUp(), and vtkPVInteractorStyle::OnKeyUp().
OnMouseMove()
void vtkCameraManipulator::OnMouseMove (int x, int y, vtkRenderer * ren, vtkRenderWindowInteractor * iren) virtual
Reimplemented in vtkPVTrackballZoomToMouse, vtkPVTrackballZoom, vtkPVTrackballRotate, vtkPVTrackballRoll, vtkPVTrackballMultiRotate, vtkPVJoystickFly, vtkTrackballPan, vtkPVTrackballPan, and vtkPVTrackballMoveActor.
Definition at line 68 of file vtkCameraManipulator.cxx.
Referenced by VTKExtensions::vtkCustomInteractorStyle::OnMouseMove(), vtkPVInteractorStyle::OnMouseMove(), and vtkPVTrackballMultiRotate::OnMouseMove().
PrintSelf()
void vtkCameraManipulator::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 96 of file vtkCameraManipulator.cxx.
References Button, Center, Control, QtCompat::endl(), GUIHelper, ManipulatorName, RotationFactor, and Shift.
SetGUIHelper()
void vtkCameraManipulator::SetGUIHelper (vtkCameraManipulatorGUIHelper *)
Get/Set the GUI helper.
Referenced by ~vtkCameraManipulator().
StartInteraction()
void vtkCameraManipulator::StartInteraction () virtual
Event bindings controlling the effects of pressing mouse buttons or moving the mouse.
Definition at line 48 of file vtkCameraManipulator.cxx.
Referenced by VTKExtensions::vtkCustomInteractorStyle::OnButtonDown(), and vtkPVInteractorStyle::OnButtonDown().
vtkBooleanMacro() [1/2]
vtkCameraManipulator::vtkBooleanMacro (Control , int)
vtkBooleanMacro() [2/2]
vtkCameraManipulator::vtkBooleanMacro (Shift , int)
vtkGetMacro() [1/4]
vtkCameraManipulator::vtkGetMacro (Button , int)
vtkGetMacro() [2/4]
vtkCameraManipulator::vtkGetMacro (Control , int)
vtkGetMacro() [3/4]
vtkCameraManipulator::vtkGetMacro (RotationFactor , double)
vtkGetMacro() [4/4]
vtkCameraManipulator::vtkGetMacro (Shift , int)
vtkGetObjectMacro()
vtkCameraManipulator::vtkGetObjectMacro (GUIHelper , vtkCameraManipulatorGUIHelper)
vtkGetStringMacro()
vtkCameraManipulator::vtkGetStringMacro (ManipulatorName)
vtkGetVector3Macro()
vtkCameraManipulator::vtkGetVector3Macro (Center , double)
vtkSetMacro() [1/4]
vtkCameraManipulator::vtkSetMacro (Button , int)
These settings determine which button and modifiers the manipulator responds to. Button can be either 1 (left), 2 (middle), and 3 right.
vtkSetMacro() [2/4]
vtkCameraManipulator::vtkSetMacro (Control , int)
vtkSetMacro() [3/4]
vtkCameraManipulator::vtkSetMacro (RotationFactor , double)
Set and get the rotation factor.
vtkSetMacro() [4/4]
vtkCameraManipulator::vtkSetMacro (Shift , int)
vtkSetStringMacro()
vtkCameraManipulator::vtkSetStringMacro (ManipulatorName)
Set and get the manipulator name.
vtkSetVector3Macro()
vtkCameraManipulator::vtkSetVector3Macro (Center , double)
For setting the center of rotation.
vtkTypeMacro()
vtkCameraManipulator::vtkTypeMacro (vtkCameraManipulator , vtkObject)
Member Data Documentation
Button
int vtkCameraManipulator::Button protected
Definition at line 109 of file vtkCameraManipulator.h.
Referenced by PrintSelf(), and vtkCameraManipulator().
Center
double vtkCameraManipulator::Center[3] protected
Definition at line 113 of file vtkCameraManipulator.h.
Referenced by ComputeDisplayCenter(), vtkPVTrackballRoll::OnMouseMove(), vtkPVTrackballRotate::OnMouseMove(), PrintSelf(), vtkPVTrackballRotate::PrintSelf(), and vtkCameraManipulator().
Control
int vtkCameraManipulator::Control protected
Definition at line 111 of file vtkCameraManipulator.h.
Referenced by PrintSelf(), and vtkCameraManipulator().
DisplayCenter
double vtkCameraManipulator::DisplayCenter[2] protected
Definition at line 115 of file vtkCameraManipulator.h.
Referenced by ComputeDisplayCenter(), vtkPVTrackballRoll::OnMouseMove(), and vtkCameraManipulator().
GUIHelper
vtkCameraManipulatorGUIHelper* vtkCameraManipulator::GUIHelper protected
Definition at line 118 of file vtkCameraManipulator.h.
Referenced by PrintSelf(), and vtkCameraManipulator().
ManipulatorName
char* vtkCameraManipulator::ManipulatorName protected
Definition at line 107 of file vtkCameraManipulator.h.
Referenced by PrintSelf(), and vtkCameraManipulator().
RotationFactor
double vtkCameraManipulator::RotationFactor protected
Definition at line 114 of file vtkCameraManipulator.h.
Referenced by vtkPVTrackballRotate::OnMouseMove(), PrintSelf(), and vtkCameraManipulator().
Shift
int vtkCameraManipulator::Shift protected
Definition at line 110 of file vtkCameraManipulator.h.
Referenced by PrintSelf(), and vtkCameraManipulator().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/InteractionStyle/vtkCameraManipulator.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/InteractionStyle/vtkCameraManipulator.cxx