ACloudViewer: SiftGPU Class Reference
SiftGPU Class Reference
#include <SiftGPU.h>
Classes
struct SiftKeypoint
Public Types
enum { SIFTGPU_NOT_SUPPORTED = 0 , SIFTGPU_PARTIAL_SUPPORTED = 1 , SIFTGPU_FULL_SUPPORTED = 2 }
typedef struct SiftGPU::SiftKeypoint SiftKeypoint
Public Member Functions
const char * GetCurrentImagePath ()
virtual void SetImageList (int nimage, const char **filelist)
virtual int GetFeatureNum ()
virtual void SaveSIFT (const char *szFileName)
virtual void GetFeatureVector (SiftKeypoint *keys, float *descriptors)
virtual void SetKeypointList (int num, const SiftKeypoint *keys, int keys_have_orientation=1)
virtual int CreateContextGL ()
virtual int VerifyContextGL ()
virtual int IsFullSupported ()
virtual void SetVerbose (int verbose=4)
void SetVerboseBrief ()
virtual void ParseParam (int argc, const char **argv)
virtual int RunSIFT (const char *imgpath)
virtual int RunSIFT (int index)
virtual int RunSIFT (int width, int height, const void *data, unsigned int gl_format, unsigned int gl_type)
virtual int RunSIFT ()
virtual int RunSIFT (int num, const SiftKeypoint *keys, int keys_have_orientation=1)
SiftGPU (int np=1)
virtual ~SiftGPU ()
virtual void SetActivePyramid (int)
virtual int GetImageCount ()
virtual void SetTightPyramid (int tight=1)
virtual int AllocatePyramid (int width, int height)
virtual void SetMaxDimension (int sz)
int GetFeatureCountThreshold ()
int GetMaxOrientation ()
int GetMaxDimension ()
Public Member Functions inherited from SiftParam
void ParseSiftParam ()
float GetLevelSigma (int lev)
float GetInitialSmoothSigma (int octave_min)
SiftParam ()
Public Attributes
int gpu_index = 0
float _timing [10]
Public Attributes inherited from SiftParam
float * _sigma
float _sigma_skip0
float _sigma_skip1
float _sigma0
float _sigman
int _sigma_num
int _dog_level_num
int _level_num
int _level_min
int _level_max
int _level_ds
float _dog_threshold
float _edge_threshold
Protected Member Functions
void InitSiftGPU ()
void LoadImageList (const char *imlist)
Static Protected Member Functions
static void PrintUsage ()
Protected Attributes
int _current
int _initialized
int _image_loaded
char * _imgpath
char * _outpath
ImageList * _list
GLTexInput * _texImage
SiftPyramid * _pyramid
Detailed Description
Definition at line 112 of file SiftGPU.h.
Member Typedef Documentation
SiftKeypoint
typedef struct SiftGPU::SiftKeypoint SiftGPU::SiftKeypoint
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
SIFTGPU_NOT_SUPPORTED
SIFTGPU_PARTIAL_SUPPORTED
SIFTGPU_FULL_SUPPORTED
Definition at line 115 of file SiftGPU.h.
Constructor & Destructor Documentation
SiftGPU()
SiftGPU::SiftGPU (int np = 1) explicit
Definition at line 84 of file SiftGPU.cpp.
References _MAX_PATH, and NULL.
~SiftGPU()
SiftGPU::~SiftGPU () virtual
Definition at line 119 of file SiftGPU.cpp.
Member Function Documentation
AllocatePyramid()
int SiftGPU::AllocatePyramid (int width, int height) virtual
Definition at line 1336 of file SiftGPU.cpp.
References GlobalParam::_octave_min_default, height, and width.
CreateContextGL()
int SiftGPU::CreateContextGL () virtual
Definition at line 1278 of file SiftGPU.cpp.
References GlobalParam::_UseCUDA, GlobalParam::_UseOpenCL, and GlobalUtil::CreateWindowEZ().
GetCurrentImagePath()
const char* SiftGPU::GetCurrentImagePath () inline
Definition at line 157 of file SiftGPU.h.
References _imgpath.
GetFeatureCountThreshold()
int SiftGPU::GetFeatureCountThreshold ()
Definition at line 1361 of file SiftGPU.cpp.
References GlobalParam::_FeatureCountThreshold.
GetFeatureNum()
int SiftGPU::GetFeatureNum () virtual
Definition at line 1312 of file SiftGPU.cpp.
GetFeatureVector()
void SiftGPU::GetFeatureVector (SiftKeypoint * keys, float * descriptors) virtual
Definition at line 1317 of file SiftGPU.cpp.
References GlobalParam::_DescriptorPPT, descriptors, and NULL.
GetImageCount()
int SiftGPU::GetImageCount () virtual
Definition at line 1376 of file SiftGPU.cpp.
GetMaxDimension()
int SiftGPU::GetMaxDimension ()
Definition at line 1371 of file SiftGPU.cpp.
References GlobalParam::_texMaxDim.
GetMaxOrientation()
int SiftGPU::GetMaxOrientation ()
Definition at line 1366 of file SiftGPU.cpp.
References GlobalParam::_MaxOrientation.
InitSiftGPU()
void SiftGPU::InitSiftGPU () inline protected
Definition at line 129 of file SiftGPU.cpp.
References GlobalParam::_DeviceIndex, GlobalParam::_GoodOpenGL, GlobalParam::_InitPyramidHeight, GlobalParam::_InitPyramidWidth, GlobalParam::_UseCUDA, GlobalParam::_UseOpenCL, GlobalParam::_usePackedTex, GlobalParam::_verbose, ClockTimer::InitHighResolution(), GlobalUtil::StartTimer(), and GlobalUtil::StopTimer().
IsFullSupported()
int SiftGPU::IsFullSupported () virtual
Definition at line 1302 of file SiftGPU.cpp.
References GlobalParam::_FullSupported, and GlobalParam::_GoodOpenGL.
LoadImageList()
void SiftGPU::LoadImageList (const char * imlist) protected
Definition at line 1163 of file SiftGPU.cpp.
References _MAX_PATH.
ParseParam()
void SiftGPU::ParseParam (int argc, const char ** argv) virtual
Definition at line 706 of file SiftGPU.cpp.
References GlobalParam::_BinarySIFT, GlobalParam::_DarknessAdaption, GlobalParam::_debug, GlobalParam::_DescriptorPPT, GlobalParam::_DescriptorWindowFactor, GlobalParam::_DeviceIndex, SiftParam::_dog_level_num, SiftParam::_dog_threshold, SiftParam::_edge_threshold, GlobalParam::_ExitAfterSIFT, GlobalParam::_FeatureCountThreshold, GlobalParam::_FeatureTexBlock, GlobalParam::_FilterWidthFactor, GlobalParam::_FitMemoryCap, GlobalParam::_FixedOrientation, GlobalParam::_ForceTightPyramid, GlobalParam::_InitPyramidHeight, GlobalParam::_InitPyramidWidth, GlobalParam::_KeepExtremumSign, GlobalParam::_KeyPointListForceLevel0, GlobalParam::_ListGenGPU, GlobalParam::_ListGenSkipGPU, GlobalParam::_LoweOrigin, GlobalParam::_MaxFeaturePercent, GlobalParam::_MaxLevelFeatureNum, GlobalParam::_MaxOrientation, GlobalParam::_MulitiOrientationThreshold, GlobalParam::_NarrowFeatureTex, GlobalParam::_NormalizedSIFT, GlobalParam::_octave_min_default, GlobalParam::_octave_num_default, GlobalParam::_OrientationPack2, GlobalParam::_OrientationWindowFactor, GlobalParam::_PreProcessOnCPU, _stricmp, GlobalParam::_SubpixelLocalization, GlobalParam::_texMaxDim, GlobalParam::_texMinDim, GlobalParam::_TruncateMethod, GlobalParam::_UseCUDA, GlobalParam::_UseDynamicIndexing, GlobalParam::_UseOpenCL, GlobalParam::_usePackedTex, GlobalParam::_WindowDisplay, GlobalParam::_WindowInitX, GlobalParam::_WindowInitY, MAKEINT1, MAKEINT2, MAKEINT3, MAKEINT4, max(), min(), NULL, GlobalUtil::SelectDisplay(), STRING_TO_INT, and FrameBufferObject::UseSingleFBO.
PrintUsage()
void SiftGPU::PrintUsage () static protected
Definition at line 658 of file SiftGPU.cpp.
RunSIFT() [1/5]
int SiftGPU::RunSIFT () virtual
Definition at line 273 of file SiftGPU.cpp.
References GlobalParam::_ExitAfterSIFT, GlobalParam::_GoodOpenGL, GlobalParam::_UseCUDA, GlobalParam::_UseOpenCL, GlobalParam::_UseSiftGPUEX, GlobalParam::_verbose, QtCompat::endl(), GlobalUtil::FitViewPort(), GlobalUtil::GetElapsedTime(), height, GlobalUtil::SetGLParam(), GlobalUtil::StartTimer(), GlobalUtil::StopTimer(), and width.
RunSIFT() [2/5]
int SiftGPU::RunSIFT (const char * imgpath) virtual
Definition at line 250 of file SiftGPU.cpp.
RunSIFT() [3/5]
int SiftGPU::RunSIFT (int index) virtual
Definition at line 194 of file SiftGPU.cpp.
RunSIFT() [4/5]
int SiftGPU::RunSIFT (int num, const SiftKeypoint * keys, int keys_have_orientation = 1) virtual
Definition at line 266 of file SiftGPU.cpp.
RunSIFT() [5/5]
int SiftGPU::RunSIFT (int width, int height, const void * data, unsigned int gl_format, unsigned int gl_type) virtual
Definition at line 213 of file SiftGPU.cpp.
References GlobalParam::_GoodOpenGL, GlobalUtil::GetElapsedTime(), height, NULL, GlobalUtil::SetGLParam(), GlobalUtil::StartTimer(), GlobalUtil::StopTimer(), and width.
SaveSIFT()
void SiftGPU::SaveSIFT (const char * szFileName) virtual
Definition at line 1307 of file SiftGPU.cpp.
SetActivePyramid()
virtual void SiftGPU::SetActivePyramid (int) inline virtual
Definition at line 205 of file SiftGPU.h.
SetImageList()
void SiftGPU::SetImageList (int nimage, const char ** filelist) virtual
Definition at line 1153 of file SiftGPU.cpp.
SetKeypointList()
void SiftGPU::SetKeypointList (int num, const SiftKeypoint * keys, int keys_have_orientation = 1) virtual
Definition at line 355 of file SiftGPU.cpp.
SetMaxDimension()
void SiftGPU::SetMaxDimension (int sz) virtual
Definition at line 1353 of file SiftGPU.cpp.
References GlobalParam::_texMaxDim, and GlobalParam::_texMaxDimGL.
SetTightPyramid()
void SiftGPU::SetTightPyramid (int tight = 1) virtual
Definition at line 1331 of file SiftGPU.cpp.
References GlobalParam::_ForceTightPyramid.
SetVerbose()
void SiftGPU::SetVerbose (int verbose = 4) virtual
Definition at line 370 of file SiftGPU.cpp.
References GlobalParam::_timingL, GlobalParam::_timingO, GlobalParam::_timingS, GlobalParam::_UseSiftGPUEX, and GlobalParam::_verbose.
Referenced by SetVerboseBrief().
SetVerboseBrief()
void SiftGPU::SetVerboseBrief () inline
Definition at line 182 of file SiftGPU.h.
References SetVerbose().
VerifyContextGL()
int SiftGPU::VerifyContextGL () virtual
Definition at line 1296 of file SiftGPU.cpp.
References GlobalParam::_FullSupported, and GlobalParam::_GoodOpenGL.
Member Data Documentation
_current
int SiftGPU::_current protected
Definition at line 131 of file SiftGPU.h.
_image_loaded
int SiftGPU::_image_loaded protected
Definition at line 137 of file SiftGPU.h.
_imgpath
char* SiftGPU::_imgpath protected
Definition at line 139 of file SiftGPU.h.
Referenced by GetCurrentImagePath().
_initialized
int SiftGPU::_initialized protected
Definition at line 135 of file SiftGPU.h.
_list
ImageList* SiftGPU::_list protected
Definition at line 143 of file SiftGPU.h.
_outpath
char* SiftGPU::_outpath protected
Definition at line 141 of file SiftGPU.h.
_pyramid
SiftPyramid* SiftGPU::_pyramid protected
Definition at line 147 of file SiftGPU.h.
_texImage
GLTexInput* SiftGPU::_texImage protected
Definition at line 145 of file SiftGPU.h.
_timing
float SiftGPU::_timing[10]
Definition at line 156 of file SiftGPU.h.
gpu_index
int SiftGPU::gpu_index = 0
Definition at line 122 of file SiftGPU.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/SiftGPU.h
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/SiftGPU.cpp