ACloudViewer: ccRegistrationDlg Class Reference
ccRegistrationDlg Class Reference
Point cloud or mesh registration dialog.
#include <ecvRegistrationDlg.h>
Public Types
typedef cloudViewer::ICPRegistrationTools::CONVERGENCE_TYPE ConvergenceMethod
Public Member Functions
ccRegistrationDlg (ccHObject *data, ccHObject *model, QWidget *parent=nullptr)
Default constructor.
virtual ~ccRegistrationDlg ()
Default destructor.
ConvergenceMethod getConvergenceMethod () const
Returns convergence method.
unsigned getMaxIterationCount () const
Returns max number of iterations.
unsigned getFinalOverlap () const
Returns the approximated final overlap.
double getMinRMSDecrease () const
Returns minimum RMS decrease between two consecutive iterations.
void setMinRMSDecrease (double value)
Sets the minimum RMS decrease between two consecutive iterations.
bool removeFarthestPoints () const
Returns whether farthest points should be ignored at each iteration.
unsigned randomSamplingLimit () const
Returns the limit above which clouds should be randomly resampled.
ccHObject * getModelEntity ()
Returns 'model' entity.
ccHObject * getDataEntity ()
Returns 'data' entity.
bool useDataSFAsWeights () const
Whether to use data displayed SF as weights.
bool useModelSFAsWeights () const
Whether to use model displayed SF as weights.
bool useC2MSignedDistances () const
Whether to use signed distances when the reference is a mesh.
cloudViewer::ICPRegistrationTools::NORMALS_MATCHING normalsMatchingOption () const
Method to take normals into account.
bool adjustScale () const
Returns whether to adjust the scale during optimization.
int getTransformationFilters () const
Returns active transformation filters.
int getMaxThreadCount () const
Returns the maximum number of threads.
void saveParameters () const
Saves parameters for next call.
Static Public Member Functions
static double GetAbsoluteMinRMSDecrease ()
Protected Member Functions
void swapModelAndData ()
void updateGUI ()
Protected Attributes
ccHObject * modelEntity
'Model' entity
ccHObject * dataEntity
'Data' entity
Detailed Description
Point cloud or mesh registration dialog.
Definition at line 20 of file ecvRegistrationDlg.h.
Member Typedef Documentation
ConvergenceMethod
typedef cloudViewer::ICPRegistrationTools::CONVERGENCE_TYPE ccRegistrationDlg::ConvergenceMethod
Definition at line 34 of file ecvRegistrationDlg.h.
Constructor & Destructor Documentation
ccRegistrationDlg()
ccRegistrationDlg::ccRegistrationDlg (ccHObject * data, ccHObject * model, QWidget * parent = nullptr)
Default constructor.
Definition at line 48 of file ecvRegistrationDlg.cpp.
References data, dataEntity, GetAbsoluteMinRMSDecrease(), modelEntity, ecvColor::red(), s_adjustScale, s_finalOverlap, s_maxIterationCount, s_maxThreadCount, s_normalsMatchingOption, s_pointsRemoval, s_randomSamplingLimit, s_rmsDifference, s_rotComboIndex, s_transCheckboxes, s_useC2MSignedDistances, s_useDataSFAsWeights, s_useErrorDifferenceCriterion, s_useModelSFAsWeights, ccQtHelpers::SetButtonColor(), setMinRMSDecrease(), swapModelAndData(), updateGUI(), and ecvColor::yellow().
~ccRegistrationDlg()
ccRegistrationDlg::~ccRegistrationDlg () virtual
Default destructor.
Definition at line 104 of file ecvRegistrationDlg.cpp.
References dataEntity, ccDrawableObject::enableTempColor(), modelEntity, ecvDisplayTools::RedrawDisplay(), and ecvDisplayTools::SetRedrawRecursive().
Member Function Documentation
adjustScale()
bool ccRegistrationDlg::adjustScale () const
Returns whether to adjust the scale during optimization.
This is useful for co-registration of lidar and photogrammetric clouds for instance.
Definition at line 164 of file ecvRegistrationDlg.cpp.
Referenced by saveParameters().
GetAbsoluteMinRMSDecrease()
double ccRegistrationDlg::GetAbsoluteMinRMSDecrease () static
Returns the theoretical mininmum RMS decrease between two consecutive iterations
Definition at line 188 of file ecvRegistrationDlg.cpp.
Referenced by ccRegistrationDlg().
getConvergenceMethod()
ccRegistrationDlg::ConvergenceMethod ccRegistrationDlg::getConvergenceMethod () const
Returns convergence method.
Definition at line 210 of file ecvRegistrationDlg.cpp.
References cloudViewer::ICPRegistrationTools::MAX_ERROR_CONVERGENCE, and cloudViewer::ICPRegistrationTools::MAX_ITER_CONVERGENCE.
getDataEntity()
ccHObject * ccRegistrationDlg::getDataEntity ()
Returns 'data' entity.
Definition at line 135 of file ecvRegistrationDlg.cpp.
References dataEntity.
getFinalOverlap()
unsigned ccRegistrationDlg::getFinalOverlap () const
Returns the approximated final overlap.
Definition at line 180 of file ecvRegistrationDlg.cpp.
getMaxIterationCount()
unsigned ccRegistrationDlg::getMaxIterationCount () const
Returns max number of iterations.
Only valid if registration method is 'ITERATION_REG'.
Definition at line 176 of file ecvRegistrationDlg.cpp.
Referenced by saveParameters().
getMaxThreadCount()
int ccRegistrationDlg::getMaxThreadCount () const
Returns the maximum number of threads.
Definition at line 184 of file ecvRegistrationDlg.cpp.
Referenced by saveParameters().
getMinRMSDecrease()
double ccRegistrationDlg::getMinRMSDecrease () const
Returns minimum RMS decrease between two consecutive iterations.
Only valid if registration method is 'MAX_ERROR_REG'.
Definition at line 190 of file ecvRegistrationDlg.cpp.
Referenced by saveParameters().
getModelEntity()
ccHObject * ccRegistrationDlg::getModelEntity ()
Returns 'model' entity.
Definition at line 137 of file ecvRegistrationDlg.cpp.
References modelEntity.
getTransformationFilters()
int ccRegistrationDlg::getTransformationFilters () const
Returns active transformation filters.
See cloudViewer::RegistrationTools::TRANSFORMATION_FILTERS.
Definition at line 218 of file ecvRegistrationDlg.cpp.
References cloudViewer::RegistrationTools::SKIP_RXY, cloudViewer::RegistrationTools::SKIP_RXZ, cloudViewer::RegistrationTools::SKIP_RYZ, cloudViewer::RegistrationTools::SKIP_TX, cloudViewer::RegistrationTools::SKIP_TY, and cloudViewer::RegistrationTools::SKIP_TZ.
normalsMatchingOption()
cloudViewer::ICPRegistrationTools::NORMALS_MATCHING ccRegistrationDlg::normalsMatchingOption () const
Method to take normals into account.
Definition at line 155 of file ecvRegistrationDlg.cpp.
References cloudViewer::ICPRegistrationTools::NO_NORMAL.
randomSamplingLimit()
unsigned ccRegistrationDlg::randomSamplingLimit () const
Returns the limit above which clouds should be randomly resampled.
Definition at line 172 of file ecvRegistrationDlg.cpp.
Referenced by saveParameters().
removeFarthestPoints()
bool ccRegistrationDlg::removeFarthestPoints () const
Returns whether farthest points should be ignored at each iteration.
This is a trick to improve registration for slightly different clouds.
Definition at line 168 of file ecvRegistrationDlg.cpp.
Referenced by saveParameters().
saveParameters()
void ccRegistrationDlg::saveParameters () const
Saves parameters for next call.
Definition at line 116 of file ecvRegistrationDlg.cpp.
References adjustScale(), getMaxIterationCount(), getMaxThreadCount(), getMinRMSDecrease(), randomSamplingLimit(), removeFarthestPoints(), s_adjustScale, s_finalOverlap, s_maxIterationCount, s_maxThreadCount, s_normalsMatchingOption, s_pointsRemoval, s_randomSamplingLimit, s_rmsDifference, s_rotComboIndex, s_transCheckboxes, s_useC2MSignedDistances, s_useDataSFAsWeights, s_useErrorDifferenceCriterion, and s_useModelSFAsWeights.
setMinRMSDecrease()
void ccRegistrationDlg::setMinRMSDecrease (double value)
Sets the minimum RMS decrease between two consecutive iterations.
Only valid if registration method is 'MAX_ERROR_REG'.
Definition at line 202 of file ecvRegistrationDlg.cpp.
Referenced by ccRegistrationDlg().
swapModelAndData()
void ccRegistrationDlg::swapModelAndData () protected
Definition at line 276 of file ecvRegistrationDlg.cpp.
References dataEntity, modelEntity, std::swap(), and updateGUI().
Referenced by ccRegistrationDlg().
updateGUI()
void ccRegistrationDlg::updateGUI () protected
Definition at line 245 of file ecvRegistrationDlg.cpp.
References dataEntity, ccObject::getName(), ccDrawableObject::hasDisplayedScalarField(), ccDrawableObject::hasNormals(), ccObject::isKindOf(), CV_TYPES::MESH, modelEntity, CV_TYPES::POINT_CLOUD, ecvColor::red(), ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::SetRedrawRecursive(), ccDrawableObject::setTempColor(), ccDrawableObject::setVisible(), and ecvColor::yellow().
Referenced by ccRegistrationDlg(), and swapModelAndData().
useC2MSignedDistances()
bool ccRegistrationDlg::useC2MSignedDistances () const
Whether to use signed distances when the reference is a mesh.
Definition at line 149 of file ecvRegistrationDlg.cpp.
useDataSFAsWeights()
bool ccRegistrationDlg::useDataSFAsWeights () const
Whether to use data displayed SF as weights.
Definition at line 139 of file ecvRegistrationDlg.cpp.
useModelSFAsWeights()
bool ccRegistrationDlg::useModelSFAsWeights () const
Whether to use model displayed SF as weights.
Definition at line 144 of file ecvRegistrationDlg.cpp.
Member Data Documentation
dataEntity
ccHObject* ccRegistrationDlg::dataEntity protected
'Data' entity
Definition at line 115 of file ecvRegistrationDlg.h.
Referenced by ccRegistrationDlg(), getDataEntity(), swapModelAndData(), updateGUI(), and ~ccRegistrationDlg().
modelEntity
ccHObject* ccRegistrationDlg::modelEntity protected
'Model' entity
Definition at line 112 of file ecvRegistrationDlg.h.
Referenced by ccRegistrationDlg(), getModelEntity(), swapModelAndData(), updateGUI(), and ~ccRegistrationDlg().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvRegistrationDlg.h
/root/ACloudViewer/app/ecvRegistrationDlg.cpp