ACloudViewer: cloudViewer::io::MKVWriter Class Reference
cloudViewer::io::MKVWriter Class Reference
#include <MKVWriter.h>
Public Member Functions
MKVWriter ()
virtual ~MKVWriter ()
bool IsOpened ()
bool Open (const std::string &filename, const _k4a_device_configuration_t &config, _k4a_device_t *device)
void Close ()
bool SetMetadata (const MKVMetadata &metadata)
bool NextFrame (_k4a_capture_t *)
Detailed Description
Definition at line 23 of file MKVWriter.h.
Constructor & Destructor Documentation
MKVWriter()
cloudViewer::io::MKVWriter::MKVWriter ()
Definition at line 21 of file MKVWriter.cpp.
~MKVWriter()
virtual cloudViewer::io::MKVWriter::~MKVWriter () inline virtual
Definition at line 26 of file MKVWriter.h.
Member Function Documentation
Close()
void cloudViewer::io::MKVWriter::Close ()
Definition at line 52 of file MKVWriter.cpp.
References cloudViewer::io::k4a_plugin::k4a_record_close(), cloudViewer::io::k4a_plugin::k4a_record_flush(), and LogWarning.
Referenced by Open().
IsOpened()
bool cloudViewer::io::MKVWriter::IsOpened ()
Definition at line 40 of file MKVWriter.cpp.
Referenced by NextFrame(), and Open().
NextFrame()
bool cloudViewer::io::MKVWriter::NextFrame (_k4a_capture_t *)
Definition at line 59 of file MKVWriter.cpp.
References IsOpened(), cloudViewer::io::k4a_plugin::k4a_record_write_capture(), and LogWarning.
Open()
bool cloudViewer::io::MKVWriter::Open (const std::string & filename, const _k4a_device_configuration_t & config, _k4a_device_t * device)
Definition at line 23 of file MKVWriter.cpp.
References Close(), IsOpened(), cloudViewer::io::k4a_plugin::k4a_record_create(), and LogWarning.
SetMetadata()
bool cloudViewer::io::MKVWriter::SetMetadata (const MKVMetadata & metadata)
Definition at line 42 of file MKVWriter.cpp.
References cloudViewer::io::k4a_plugin::k4a_record_write_header(), and LogWarning.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/io/sensor/azure_kinect/MKVWriter.h
/root/ACloudViewer/libs/cloudViewer/io/sensor/azure_kinect/MKVWriter.cpp