ACloudViewer: colmap::ImageViewerWidget Class Reference
colmap::ImageViewerWidget Class Reference
#include <image_viewer_widget.h>
Public Member Functions
ImageViewerWidget (QWidget *parent)
void ShowBitmap (const Bitmap &bitmap)
void ShowPixmap (const QPixmap &pixmap)
void ReadAndShow (const std::string &path)
Protected Member Functions
void resizeEvent (QResizeEvent *event)
void closeEvent (QCloseEvent *event)
void ZoomIn ()
void ZoomOut ()
void Save ()
Protected Attributes
QGridLayout * grid_layout_
QHBoxLayout * button_layout_
Detailed Description
Definition at line 33 of file image_viewer_widget.h.
Constructor & Destructor Documentation
ImageViewerWidget()
colmap::ImageViewerWidget::ImageViewerWidget (QWidget * parent) explicit
Definition at line 51 of file image_viewer_widget.cc.
References button_layout_, grid_layout_, Save(), ZoomIn(), and ZoomOut().
Member Function Documentation
closeEvent()
void colmap::ImageViewerWidget::closeEvent (QCloseEvent * event) protected
Definition at line 103 of file image_viewer_widget.cc.
References colmap::ImageViewerGraphicsScene::ImagePixmapItem().
ReadAndShow()
void colmap::ImageViewerWidget::ReadAndShow (const std::string & path)
Definition at line 121 of file image_viewer_widget.cc.
References QtCompat::endl(), cloudViewer::t::geometry::path, colmap::Bitmap::Read(), and ShowBitmap().
resizeEvent()
void colmap::ImageViewerWidget::resizeEvent (QResizeEvent * event) protected
Definition at line 97 of file image_viewer_widget.cc.
References event.
Save()
void colmap::ImageViewerWidget::Save () protected
Definition at line 138 of file image_viewer_widget.cc.
References colmap::ImageViewerGraphicsScene::ImagePixmapItem().
Referenced by ImageViewerWidget().
ShowBitmap()
void colmap::ImageViewerWidget::ShowBitmap (const Bitmap & bitmap)
Definition at line 107 of file image_viewer_widget.cc.
References colmap::BitmapToQImageRGB(), and ShowPixmap().
Referenced by ReadAndShow(), and colmap::MatchMatrixWidget::Show().
ShowPixmap()
void colmap::ImageViewerWidget::ShowPixmap (const QPixmap & pixmap)
Definition at line 111 of file image_viewer_widget.cc.
References colmap::ImageViewerGraphicsScene::ImagePixmapItem().
Referenced by colmap::FeatureImageViewerWidget::ReadAndShowWithKeypoints(), colmap::FeatureImageViewerWidget::ReadAndShowWithMatches(), ShowBitmap(), and colmap::FeatureImageViewerWidget::ShowOrHide().
ZoomIn()
void colmap::ImageViewerWidget::ZoomIn () protected
Definition at line 130 of file image_viewer_widget.cc.
Referenced by ImageViewerWidget().
ZoomOut()
void colmap::ImageViewerWidget::ZoomOut () protected
Definition at line 134 of file image_viewer_widget.cc.
Referenced by ImageViewerWidget().
Member Data Documentation
button_layout_
QHBoxLayout* colmap::ImageViewerWidget::button_layout_ protected
Definition at line 55 of file image_viewer_widget.h.
Referenced by colmap::FeatureImageViewerWidget::FeatureImageViewerWidget(), and ImageViewerWidget().
grid_layout_
QGridLayout* colmap::ImageViewerWidget::grid_layout_ protected
Definition at line 54 of file image_viewer_widget.h.
Referenced by ImageViewerWidget().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/image_viewer_widget.h
/root/ACloudViewer/libs/Reconstruction/src/ui/image_viewer_widget.cc