ACloudViewer: ccNoteTool Class Reference
ccNoteTool Class Reference
#include <ccNoteTool.h>
Public Member Functions
ccNoteTool ()
virtual ~ccNoteTool ()
virtual void toolActivated () override
virtual void toolDisactivated () override
void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccPointCloud *cloud, const CCVector3 &P) override
Public Member Functions inherited from ccTool
virtual ~ccTool ()
void initializeTool (ecvMainAppInterface *app)
virtual void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccHObject *pickedObject, const CCVector3 &P)
virtual void onNewSelection (const ccHObject::Container &selectedEntities)
virtual void accept ()
virtual void cancel ()
virtual bool canUndo ()
virtual void undo ()
Additional Inherited Members
Protected Member Functions inherited from ccTool
ccTool ()
Protected Attributes inherited from ccTool
ecvMainAppInterface * m_app
QWidget * m_window
Detailed Description
Definition at line 19 of file ccNoteTool.h.
Constructor & Destructor Documentation
ccNoteTool()
ccNoteTool::ccNoteTool ()
Definition at line 10 of file ccNoteTool.cpp.
~ccNoteTool()
ccNoteTool::~ccNoteTool () virtual
Definition at line 12 of file ccNoteTool.cpp.
Member Function Documentation
pointPicked()
void ccNoteTool::pointPicked (ccHObject * insertPoint, unsigned itemIdx, ccPointCloud * cloud, const CCVector3 & P) override virtual
Reimplemented from ccTool.
Definition at line 15 of file ccNoteTool.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), ecvMainAppInterface::addToDB(), ecvMainAppInterface::dbRootObject(), ccHObject::getChild(), ecvMainAppInterface::getMainWindow(), ccObject::getName(), ccTool::m_app, and ccObject::setName().
toolActivated()
void ccNoteTool::toolActivated () override virtual
Reimplemented from ccTool.
Definition at line 71 of file ccNoteTool.cpp.
toolDisactivated()
void ccNoteTool::toolDisactivated () override virtual
Reimplemented from ccTool.
Definition at line 76 of file ccNoteTool.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCompass/include/ccNoteTool.h
/root/ACloudViewer/plugins/core/Standard/qCompass/src/ccNoteTool.cpp