ACloudViewer: cloudViewer::ImageViewerWidget Class Reference
cloudViewer::ImageViewerWidget Class Reference
#include <ImageViewerWidget.h>
Public Member Functions
ImageViewerWidget (QWidget *parent)
void ShowBitmap (const colmap::Bitmap &bitmap)
void ShowPixmap (const QPixmap &pixmap)
void ReadAndShow (const std::string &path)
Protected Member Functions
void resizeEvent (QResizeEvent *event)
void closeEvent (QCloseEvent *event)
void ZoomIn ()
void ZoomOut ()
void Save ()
Protected Attributes
QGridLayout * grid_layout_
QHBoxLayout * button_layout_
Detailed Description
Definition at line 36 of file ImageViewerWidget.h.
Constructor & Destructor Documentation
ImageViewerWidget()
cloudViewer::ImageViewerWidget::ImageViewerWidget (QWidget * parent) explicit
Definition at line 34 of file ImageViewerWidget.cpp.
References button_layout_, grid_layout_, Save(), ZoomIn(), and ZoomOut().
Member Function Documentation
closeEvent()
void cloudViewer::ImageViewerWidget::closeEvent (QCloseEvent * event) protected
Definition at line 88 of file ImageViewerWidget.cpp.
References cloudViewer::ImageViewerGraphicsScene::ImagePixmapItem().
ReadAndShow()
void cloudViewer::ImageViewerWidget::ReadAndShow (const std::string & path)
Definition at line 106 of file ImageViewerWidget.cpp.
References QtCompat::endl(), cloudViewer::t::geometry::path, colmap::Bitmap::Read(), and ShowBitmap().
resizeEvent()
void cloudViewer::ImageViewerWidget::resizeEvent (QResizeEvent * event) protected
Definition at line 82 of file ImageViewerWidget.cpp.
References event.
Save()
void cloudViewer::ImageViewerWidget::Save () protected
Definition at line 123 of file ImageViewerWidget.cpp.
References cloudViewer::ImageViewerGraphicsScene::ImagePixmapItem().
Referenced by ImageViewerWidget().
ShowBitmap()
void cloudViewer::ImageViewerWidget::ShowBitmap (const colmap::Bitmap & bitmap)
Definition at line 92 of file ImageViewerWidget.cpp.
References colmap::BitmapToQImageRGB(), and ShowPixmap().
Referenced by ReadAndShow(), and cloudViewer::MatchMatrixWidget::Show().
ShowPixmap()
void cloudViewer::ImageViewerWidget::ShowPixmap (const QPixmap & pixmap)
Definition at line 96 of file ImageViewerWidget.cpp.
References cloudViewer::ImageViewerGraphicsScene::ImagePixmapItem().
Referenced by cloudViewer::FeatureImageViewerWidget::ReadAndShowWithKeypoints(), cloudViewer::FeatureImageViewerWidget::ReadAndShowWithMatches(), ShowBitmap(), and cloudViewer::FeatureImageViewerWidget::ShowOrHide().
ZoomIn()
void cloudViewer::ImageViewerWidget::ZoomIn () protected
Definition at line 115 of file ImageViewerWidget.cpp.
Referenced by ImageViewerWidget().
ZoomOut()
void cloudViewer::ImageViewerWidget::ZoomOut () protected
Definition at line 119 of file ImageViewerWidget.cpp.
Referenced by ImageViewerWidget().
Member Data Documentation
button_layout_
QHBoxLayout* cloudViewer::ImageViewerWidget::button_layout_ protected
Definition at line 58 of file ImageViewerWidget.h.
Referenced by cloudViewer::FeatureImageViewerWidget::FeatureImageViewerWidget(), and ImageViewerWidget().
grid_layout_
QGridLayout* cloudViewer::ImageViewerWidget::grid_layout_ protected
Definition at line 57 of file ImageViewerWidget.h.
Referenced by ImageViewerWidget().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/reconstruction/ImageViewerWidget.h
/root/ACloudViewer/app/reconstruction/ImageViewerWidget.cpp