ACloudViewer: cloudViewer::core::SlabNodeManager Class Reference
cloudViewer::core::SlabNodeManager Class Reference
#include <SlabNodeManager.h>
Public Member Functions
SlabNodeManager (const Device &device)
~SlabNodeManager ()
void Reset ()
std::vector< int > CountSlabsPerSuperblock ()
Public Attributes
SlabNodeManagerImpl impl_
Device device_
Detailed Description
Definition at line 219 of file SlabNodeManager.h.
Constructor & Destructor Documentation
SlabNodeManager()
cloudViewer::core::SlabNodeManager::SlabNodeManager (const Device & device) inline
Random coefficients for allocator's hash function.
In the light version, we put num_super_blocks super blocks within a single array.
Definition at line 221 of file SlabNodeManager.h.
References device_, cloudViewer::core::SlabNodeManagerImpl::hash_coef_, impl_, cloudViewer::core::kSuperBlocks, cloudViewer::core::kUIntsPerSuperBlock, cloudViewer::core::MemoryManager::Malloc(), cloudViewer::utility::random::RandUint32(), Reset(), and cloudViewer::core::SlabNodeManagerImpl::super_blocks_.
~SlabNodeManager()
cloudViewer::core::SlabNodeManager::~SlabNodeManager () inline
Definition at line 233 of file SlabNodeManager.h.
References device_, cloudViewer::core::MemoryManager::Free(), impl_, and cloudViewer::core::SlabNodeManagerImpl::super_blocks_.
Member Function Documentation
CountSlabsPerSuperblock()
std::vector<int> cloudViewer::core::SlabNodeManager::CountSlabsPerSuperblock () inline
Definition at line 250 of file SlabNodeManager.h.
References CLOUDVIEWER_CUDA_CHECK, copy, cloudViewer::core::CountSlabsPerSuperblockKernel(), impl_, cloudViewer::core::kBlocksPerSuperBlock, cloudViewer::core::kSuperBlocks, cloudViewer::core::kThreadsPerBlock, result, and cloudViewer::core::cuda::Synchronize().
Reset()
void cloudViewer::core::SlabNodeManager::Reset () inline
Definition at line 235 of file SlabNodeManager.h.
References CLOUDVIEWER_CUDA_CHECK, impl_, cloudViewer::core::kBlocksPerSuperBlock, cloudViewer::core::kSlabsPerBlock, cloudViewer::core::kSuperBlocks, cloudViewer::core::kUIntsPerSuperBlock, cloudViewer::core::SlabNodeManagerImpl::super_blocks_, and cloudViewer::core::cuda::Synchronize().
Referenced by SlabNodeManager().
Member Data Documentation
device_
Device cloudViewer::core::SlabNodeManager::device_
Definition at line 276 of file SlabNodeManager.h.
Referenced by SlabNodeManager(), and ~SlabNodeManager().
impl_
SlabNodeManagerImpl cloudViewer::core::SlabNodeManager::impl_
Definition at line 275 of file SlabNodeManager.h.
Referenced by CountSlabsPerSuperblock(), Reset(), SlabNodeManager(), and ~SlabNodeManager().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/hashmap/CUDA/SlabNodeManager.h