ACloudViewer: colmap::EPNPEstimator Class Reference
colmap::EPNPEstimator Class Reference
#include <absolute_pose.h>
Public Types
typedef Eigen::Vector2d X_t
typedef Eigen::Vector3d Y_t
typedef Eigen::Matrix3x4d M_t
Static Public Member Functions
static std::vector< M_t > Estimate (const std::vector< X_t > &points2D, const std::vector< Y_t > &points3D)
static void Residuals (const std::vector< X_t > &points2D, const std::vector< Y_t > &points3D, const M_t &proj_matrix, std::vector< double > *residuals)
Static Public Attributes
static const int kMinNumSamples = 4
Detailed Description
Definition at line 72 of file absolute_pose.h.
Member Typedef Documentation
M_t
typedef Eigen::Matrix3x4d colmap::EPNPEstimator::M_t
Definition at line 79 of file absolute_pose.h.
X_t
typedef Eigen::Vector2d colmap::EPNPEstimator::X_t
Definition at line 75 of file absolute_pose.h.
Y_t
typedef Eigen::Vector3d colmap::EPNPEstimator::Y_t
Definition at line 77 of file absolute_pose.h.
Member Function Documentation
Estimate()
std::vector< EPNPEstimator::M_t > colmap::EPNPEstimator::Estimate (const std::vector< X_t > & points2D, const std::vector< Y_t > & points3D) static
Definition at line 183 of file absolute_pose.cc.
Referenced by BOOST_AUTO_TEST_CASE().
Residuals()
void colmap::EPNPEstimator::Residuals (const std::vector< X_t > & points2D, const std::vector< Y_t > & points3D, const M_t & proj_matrix, std::vector< double > * residuals) static
Definition at line 197 of file absolute_pose.cc.
References colmap::ComputeSquaredReprojectionError().
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
kMinNumSamples
const int colmap::EPNPEstimator::kMinNumSamples = 4 static
Definition at line 82 of file absolute_pose.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/estimators/absolute_pose.h
/root/ACloudViewer/libs/Reconstruction/src/estimators/absolute_pose.cc