ACloudViewer: cloudViewer::visualization::rendering::GeometryBuffersBuilder Class Reference
cloudViewer::visualization::rendering::GeometryBuffersBuilder Class Reference abstract
#include <FilamentGeometryBuffersBuilder.h>
Public Types
using Buffers = std::tuple< VertexBufferHandle, IndexBufferHandle, IndexBufferHandle >
using IndexType = std::uint32_t
Public Member Functions
virtual ~GeometryBuffersBuilder ()=default
virtual filament::RenderableManager::PrimitiveType GetPrimitiveType () const =0
virtual void SetDownsampleThreshold (size_t min_points)
virtual void SetWideLines ()
virtual void SetAdjustColorsForSRGBToneMapping (bool adjust)
virtual Buffers ConstructBuffers ()=0
virtual filament::Box ComputeAABB ()=0
Static Public Member Functions
static std::unique_ptr< GeometryBuffersBuilder > GetBuilder (const ccHObject &geometry)
static std::unique_ptr< GeometryBuffersBuilder > GetBuilder (const t::geometry::Geometry &geometry)
Static Protected Member Functions
static void DeallocateBuffer (void *buffer, size_t size, void *user_ptr)
static IndexBufferHandle CreateIndexBuffer (size_t max_index, size_t n_subsamples=SIZE_MAX)
Protected Attributes
size_t downsample_threshold_ = SIZE_MAX
bool wide_lines_ = false
bool adjust_colors_for_srgb_tonemapping_ = true
Detailed Description
Definition at line 60 of file FilamentGeometryBuffersBuilder.h.
Member Typedef Documentation
Buffers
using cloudViewer::visualization::rendering::GeometryBuffersBuilder::Buffers = std::tuple<VertexBufferHandle, IndexBufferHandle, IndexBufferHandle>
Definition at line 65 of file FilamentGeometryBuffersBuilder.h.
IndexType
using cloudViewer::visualization::rendering::GeometryBuffersBuilder::IndexType = std::uint32_t
Definition at line 68 of file FilamentGeometryBuffersBuilder.h.
Constructor & Destructor Documentation
~GeometryBuffersBuilder()
virtual cloudViewer::visualization::rendering::GeometryBuffersBuilder::~GeometryBuffersBuilder () virtual default
Member Function Documentation
ComputeAABB()
virtual filament::Box cloudViewer::visualization::rendering::GeometryBuffersBuilder::ComputeAABB () pure virtual
Implemented in cloudViewer::visualization::rendering::TLineSetBuffersBuilder, cloudViewer::visualization::rendering::TPointCloudBuffersBuilder, cloudViewer::visualization::rendering::TMeshBuffersBuilder, cloudViewer::visualization::rendering::LineSetBuffersBuilder, cloudViewer::visualization::rendering::PointCloudBuffersBuilder, and cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder.
ConstructBuffers()
virtual Buffers cloudViewer::visualization::rendering::GeometryBuffersBuilder::ConstructBuffers () pure virtual
Implemented in cloudViewer::visualization::rendering::TLineSetBuffersBuilder, cloudViewer::visualization::rendering::TGaussianSplatBuffersBuilder, cloudViewer::visualization::rendering::TPointCloudBuffersBuilder, cloudViewer::visualization::rendering::TMeshBuffersBuilder, cloudViewer::visualization::rendering::LineSetBuffersBuilder, cloudViewer::visualization::rendering::PointCloudBuffersBuilder, and cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder.
CreateIndexBuffer()
IndexBufferHandle cloudViewer::visualization::rendering::GeometryBuffersBuilder::CreateIndexBuffer (size_t max_index, size_t n_subsamples = SIZE_MAX) static protected
Definition at line 90 of file PointCloudBuffers.cpp.
References dist(), cloudViewer::utility::floor(), Runtime::GetInstance(), and min().
Referenced by cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::ConstructBuffers(), and cloudViewer::visualization::rendering::TGaussianSplatBuffersBuilder::ConstructBuffers().
DeallocateBuffer()
void cloudViewer::visualization::rendering::GeometryBuffersBuilder::DeallocateBuffer (void * buffer, size_t size, void * user_ptr) static protected
Definition at line 305 of file FilamentGeometryBuffersBuilder.cpp.
Referenced by cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::LineSetBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TMeshBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TGaussianSplatBuffersBuilder::ConstructBuffers(), and cloudViewer::visualization::rendering::TLineSetBuffersBuilder::ConstructBuffers().
GetBuilder() [1/2]
std::unique_ptr< GeometryBuffersBuilder > cloudViewer::visualization::rendering::GeometryBuffersBuilder::GetBuilder (const ccHObject & geometry) static
Definition at line 228 of file FilamentGeometryBuffersBuilder.cpp.
References CV_TYPES::BBOX, cloudViewer::geometry::LineSet::CreateFromAxisAlignedBoundingBox(), cloudViewer::geometry::LineSet::CreateFromOrientedBoundingBox(), ccHObject::getClassID(), CV_TYPES::LINESET, CV_TYPES::MESH, octree, CV_TYPES::ORIENTED_BBOX, CV_TYPES::POINT_CLOUD, CV_TYPES::POINT_OCTREE2, and CV_TYPES::VOXEL_GRID.
Referenced by cloudViewer::visualization::rendering::FilamentScene::AddGeometry().
GetBuilder() [2/2]
std::unique_ptr< GeometryBuffersBuilder > cloudViewer::visualization::rendering::GeometryBuffersBuilder::GetBuilder (const t::geometry::Geometry & geometry) static
Definition at line 277 of file FilamentGeometryBuffersBuilder.cpp.
References cloudViewer::t::geometry::Geometry::GetGeometryType(), and cloudViewer::t::geometry::PointCloud::IsGaussianSplat().
GetPrimitiveType()
virtual filament::RenderableManager::PrimitiveType cloudViewer::visualization::rendering::GeometryBuffersBuilder::GetPrimitiveType () const pure virtual
Implemented in cloudViewer::visualization::rendering::TLineSetBuffersBuilder, cloudViewer::visualization::rendering::TPointCloudBuffersBuilder, cloudViewer::visualization::rendering::TMeshBuffersBuilder, cloudViewer::visualization::rendering::LineSetBuffersBuilder, cloudViewer::visualization::rendering::PointCloudBuffersBuilder, and cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder.
SetAdjustColorsForSRGBToneMapping()
virtual void cloudViewer::visualization::rendering::GeometryBuffersBuilder::SetAdjustColorsForSRGBToneMapping (bool adjust) inline virtual
Definition at line 92 of file FilamentGeometryBuffersBuilder.h.
References adjust_colors_for_srgb_tonemapping_.
SetDownsampleThreshold()
virtual void cloudViewer::visualization::rendering::GeometryBuffersBuilder::SetDownsampleThreshold (size_t min_points) inline virtual
Definition at line 84 of file FilamentGeometryBuffersBuilder.h.
References downsample_threshold_.
SetWideLines()
virtual void cloudViewer::visualization::rendering::GeometryBuffersBuilder::SetWideLines () inline virtual
Definition at line 90 of file FilamentGeometryBuffersBuilder.h.
References wide_lines_.
Member Data Documentation
adjust_colors_for_srgb_tonemapping_
bool cloudViewer::visualization::rendering::GeometryBuffersBuilder::adjust_colors_for_srgb_tonemapping_ = true protected
Definition at line 102 of file FilamentGeometryBuffersBuilder.h.
Referenced by cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ConstructBuffers(), and SetAdjustColorsForSRGBToneMapping().
downsample_threshold_
size_t cloudViewer::visualization::rendering::GeometryBuffersBuilder::downsample_threshold_ = SIZE_MAX protected
Definition at line 100 of file FilamentGeometryBuffersBuilder.h.
Referenced by cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TGaussianSplatBuffersBuilder::ConstructBuffers(), and SetDownsampleThreshold().
wide_lines_
bool cloudViewer::visualization::rendering::GeometryBuffersBuilder::wide_lines_ = false protected
Definition at line 101 of file FilamentGeometryBuffersBuilder.h.
Referenced by cloudViewer::visualization::rendering::LineSetBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TLineSetBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::LineSetBuffersBuilder::GetPrimitiveType(), cloudViewer::visualization::rendering::TLineSetBuffersBuilder::GetPrimitiveType(), and SetWideLines().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentGeometryBuffersBuilder.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentGeometryBuffersBuilder.cpp
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/PointCloudBuffers.cpp