ACloudViewer: PclUtils::renders::MultiTextureRenderer Class Reference
PclUtils::renders::MultiTextureRenderer Class Reference
Multi-texture renderer.
#include <MultiTextureRenderer.h>
Public Member Functions
MultiTextureRenderer ()
~MultiTextureRenderer () override=default
bool CanHandle (size_t material_count, bool has_pbr_textures, bool has_multiple_map_kd) const override
Check if this renderer can handle the given material.
RenderingMode GetMode () const override
Get the rendering mode this renderer implements.
bool Apply (vtkLODActor *actor, const class ccMaterialSet *materials, vtkPolyData *polydata, vtkRenderer *renderer) override
Apply rendering to actor.
bool Update (vtkActor *actor, const class ccMaterialSet *materials, vtkPolyData *polydata, vtkRenderer *renderer) override
Update existing actor with new materials.
std::string GetName () const override
Get renderer name for logging.
bool ApplyMaterial (ccMaterial::CShared material, vtkActor *actor, float intensity_scale=1.0f) const
Apply material properties to actor.
Public Member Functions inherited from PclUtils::renders::TextureRendererBase
TextureRendererBase ()=default
virtual ~TextureRendererBase ()=default
Additional Inherited Members
Protected Member Functions inherited from PclUtils::renders::TextureRendererBase
void ClearTextures (vtkActor *actor)
Helper: Clear all textures from actor.
bool ValidateActor (vtkActor *actor) const
Helper: Validate actor.
bool ValidateMaterials (const class ccMaterialSet *materials) const
Helper: Validate materials.
Detailed Description
Multi-texture renderer.
Traditional multi-texture rendering using VTK's multi-texture API. Supports multiple textures with blending modes (REPLACE, ADD). Used when:
Multiple map_Kd textures are present (VTK PBR limitation)
Traditional texture rendering is preferred
Definition at line 32 of file MultiTextureRenderer.h.
Constructor & Destructor Documentation
MultiTextureRenderer()
PclUtils::renders::MultiTextureRenderer::MultiTextureRenderer () default
~MultiTextureRenderer()
PclUtils::renders::MultiTextureRenderer::~MultiTextureRenderer () override default
Member Function Documentation
Apply()
bool PclUtils::renders::MultiTextureRenderer::Apply (vtkLODActor * actor, const class ccMaterialSet * materials, vtkPolyData * polydata, vtkRenderer * renderer) override virtual
Apply rendering to actor.
Parameters
actor VTK actor to render
materials Material set
polydata Polygon data (for texture coordinates)
renderer VTK renderer (for lighting setup)
Returns
true on success
Implements PclUtils::renders::TextureRendererBase.
Definition at line 67 of file MultiTextureRenderer.cpp.
References ecvColor::RgbaTpl< Type >::a, ApplyMaterial(), PclUtils::renders::TextureRendererBase::ClearTextures(), CVLog::Error(), CVTools::FromQString(), ccMaterial::GetTexture(), CVLog::Print(), CVLog::PrintDebug(), PclUtils::renders::TextureRendererBase::ValidateActor(), PclUtils::renders::TextureRendererBase::ValidateMaterials(), and CVLog::Warning().
Referenced by Update().
ApplyMaterial()
bool PclUtils::renders::MultiTextureRenderer::ApplyMaterial (ccMaterial::CShared material, vtkActor * actor, float intensity_scale = 1.0f) const
Apply material properties to actor.
Note
This is a public method that can be used standalone
Definition at line 582 of file MultiTextureRenderer.cpp.
References ecvColor::RgbaTpl< Type >::a, ecvColor::RgbaTpl< Type >::b, ecvColor::RgbaTpl< Type >::g, and ecvColor::RgbaTpl< Type >::r.
Referenced by Apply().
CanHandle()
bool PclUtils::renders::MultiTextureRenderer::CanHandle (size_t material_count, bool has_pbr_textures, bool has_multiple_map_kd) const override virtual
Check if this renderer can handle the given material.
Parameters
material_count Number of materials
has_pbr_textures Whether material has PBR textures
has_multiple_map_kd Whether material has multiple map_Kd textures
Returns
true if this renderer can handle the material
Implements PclUtils::renders::TextureRendererBase.
Definition at line 51 of file MultiTextureRenderer.cpp.
GetMode()
RenderingMode PclUtils::renders::MultiTextureRenderer::GetMode () const override virtual
Get the rendering mode this renderer implements.
Implements PclUtils::renders::TextureRendererBase.
Definition at line 63 of file MultiTextureRenderer.cpp.
References PclUtils::renders::MULTI_TEXTURE.
GetName()
std::string PclUtils::renders::MultiTextureRenderer::GetName () const override virtual
Get renderer name for logging.
Implements PclUtils::renders::TextureRendererBase.
Definition at line 446 of file MultiTextureRenderer.cpp.
Update()
bool PclUtils::renders::MultiTextureRenderer::Update (vtkActor * actor, const class ccMaterialSet * materials, vtkPolyData * polydata, vtkRenderer * renderer) override virtual
Update existing actor with new materials.
Parameters
actor VTK actor to update
materials Material set
polydata Polygon data
renderer VTK renderer
Returns
true on success
Implements PclUtils::renders::TextureRendererBase.
Definition at line 428 of file MultiTextureRenderer.cpp.
References Apply(), PclUtils::renders::TextureRendererBase::ValidateActor(), PclUtils::renders::TextureRendererBase::ValidateMaterials(), and CVLog::Warning().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/PclUtils/renders/textured/MultiTextureRenderer.h
/root/ACloudViewer/libs/PCLEngine/PclUtils/renders/textured/MultiTextureRenderer.cpp