ACloudViewer: PlyVertex< Real > Class Template Reference
PlyVertex< Real > Class Template Reference
#include <Ply.h>
Public Types
typedef PlyVertex Wrapper
Public Member Functions
PlyVertex (void)
PlyVertex (Point3D< Real > p)
PlyVertex operator+ (PlyVertex p) const
PlyVertex operator- (PlyVertex p) const
template<class _Real >
PlyVertex operator* (_Real s) const
template<class _Real >
PlyVertex operator/ (_Real s) const
PlyVertex & operator+= (PlyVertex p)
PlyVertex & operator-= (PlyVertex p)
template<class _Real >
PlyVertex & operator*= (_Real s)
template<class _Real >
PlyVertex & operator/= (_Real s)
Public Attributes
Point3D< Real > point
Static Public Attributes
static const int ReadComponents =3
static const int WriteComponents =3
static PlyProperty ReadProperties []
static PlyProperty WriteProperties []
Detailed Description
template<class Real>
class PlyVertex< Real >
Definition at line 251 of file Ply.h.
Member Typedef Documentation
Wrapper
template<class Real > typedef PlyVertex PlyVertex< Real >::Wrapper
Definition at line 254 of file Ply.h.
Constructor & Destructor Documentation
PlyVertex() [1/2]
template<class Real > PlyVertex< Real >::PlyVertex (void) inline
Definition at line 263 of file Ply.h.
Referenced by PlyVertex< Real >::operator*(), PlyVertex< Real >::operator+(), PlyVertex< Real >::operator-(), and PlyVertex< Real >::operator/().
PlyVertex() [2/2]
template<class Real > PlyVertex< Real >::PlyVertex (Point3D< Real > p) inline
Definition at line 264 of file Ply.h.
Member Function Documentation
operator*()
template<class Real > template<class _Real > PlyVertex PlyVertex< Real >::operator* (_Real s) const inline
Definition at line 267 of file Ply.h.
References PlyVertex< Real >::PlyVertex().
operator*=()
template<class Real > template<class _Real > PlyVertex& PlyVertex< Real >::operator*= (_Real s) inline
Definition at line 271 of file Ply.h.
operator+()
template<class Real > PlyVertex PlyVertex< Real >::operator+ (PlyVertex< Real > p) const inline
Definition at line 265 of file Ply.h.
References PlyVertex< Real >::PlyVertex(), and PlyVertex< Real >::point.
operator+=()
template<class Real > PlyVertex& PlyVertex< Real >::operator+= (PlyVertex< Real > p) inline
Definition at line 269 of file Ply.h.
References PlyVertex< Real >::point.
operator-()
template<class Real > PlyVertex PlyVertex< Real >::operator- (PlyVertex< Real > p) const inline
Definition at line 266 of file Ply.h.
References PlyVertex< Real >::PlyVertex(), and PlyVertex< Real >::point.
operator-=()
template<class Real > PlyVertex& PlyVertex< Real >::operator-= (PlyVertex< Real > p) inline
Definition at line 270 of file Ply.h.
References PlyVertex< Real >::point.
operator/()
template<class Real > template<class _Real > PlyVertex PlyVertex< Real >::operator/ (_Real s) const inline
Definition at line 268 of file Ply.h.
References PlyVertex< Real >::PlyVertex().
operator/=()
template<class Real > template<class _Real > PlyVertex& PlyVertex< Real >::operator/= (_Real s) inline
Definition at line 272 of file Ply.h.
Member Data Documentation
point
template<class Real > Point3D< Real > PlyVertex< Real >::point
Definition at line 261 of file Ply.h.
Referenced by operator*(), PlyVertex< Real >::operator+(), PlyVertex< Real >::operator+=(), PlyVertex< Real >::operator-(), and PlyVertex< Real >::operator-=().
ReadComponents
template<class Real > const int PlyVertex< Real >::ReadComponents =3 static
Definition at line 256 of file Ply.h.
ReadProperties
template<class Real > PlyProperty PlyVertex< Real >::ReadProperties static
Initial value:
=
{
    {  strdup ( "x" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyVertex , point.coords[0] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "y" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyVertex , point.coords[1] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "z" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyVertex , point.coords[2] ) ) , 0 , 0 , 0 , 0 }
}
Definition at line 258 of file Ply.h.
WriteComponents
template<class Real > const int PlyVertex< Real >::WriteComponents =3 static
Definition at line 257 of file Ply.h.
WriteProperties
template<class Real > PlyProperty PlyVertex< Real >::WriteProperties static
Initial value:
=
{
    {  strdup ( "x" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyVertex , point.coords[0] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "y" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyVertex , point.coords[1] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "z" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyVertex , point.coords[2] ) ) , 0 , 0 , 0 , 0 }
}
Definition at line 259 of file Ply.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/Ply.h