ACloudViewer: ccPluginManager Class Reference
ccPluginManager Class Reference
#include <ecvPluginManager.h>
Public Member Functions
~ccPluginManager () override=default
void setPaths (const QStringList &paths)
QStringList pluginPaths ()
void loadPlugins ()
ccPluginInterfaceList & pluginList ()
bool isEnabled (const ccPluginInterface *plugin) const
void setPluginEnabled (const ccPluginInterface *plugin, bool enabled)
Static Public Member Functions
static ccPluginManager & get ()
Protected Member Functions
ccPluginManager (QObject *parent=nullptr)
Detailed Description
Definition at line 20 of file ecvPluginManager.h.
Constructor & Destructor Documentation
~ccPluginManager()
ccPluginManager::~ccPluginManager () override default
ccPluginManager()
ccPluginManager::ccPluginManager (QObject * parent = nullptr) explicit protected
Definition at line 94 of file ecvPluginManager.cpp.
Member Function Documentation
get()
ccPluginManager & ccPluginManager::get () static
Definition at line 96 of file ecvPluginManager.cpp.
Referenced by ecvApplicationBase::ecvApplicationBase(), ccPluginUIManager::init(), InitEnvironment(), main(), ccPluginInfoDlg::setPluginList(), and ccPluginUIManager::showAboutDialog().
isEnabled()
bool ccPluginManager::isEnabled (const ccPluginInterface * plugin) const
Definition at line 230 of file ecvPluginManager.cpp.
References ccPluginInterface::IID().
loadPlugins()
void ccPluginManager::loadPlugins ()
Definition at line 104 of file ecvPluginManager.cpp.
References ECV_IO_FILTER_PLUGIN, ECV_STD_PLUGIN, ecvApp, ccPluginInterface::getCustomObjectsFactory(), ccIOPluginInterface::getFilters(), ccPluginInterface::getName(), ccDefaultPluginInterface::getName(), ccExternalFactory::Container::GetUniqueInstance(), pluginList(), CVLog::Print(), and FileIOFilter::Register().
Referenced by InitEnvironment().
pluginList()
ccPluginInterfaceList & ccPluginManager::pluginList ()
Definition at line 199 of file ecvPluginManager.cpp.
Referenced by ccPluginUIManager::init(), and loadPlugins().
pluginPaths()
QStringList ccPluginManager::pluginPaths ()
Definition at line 102 of file ecvPluginManager.cpp.
setPaths()
void ccPluginManager::setPaths (const QStringList & paths)
Definition at line 98 of file ecvPluginManager.cpp.
Referenced by ecvApplicationBase::ecvApplicationBase().
setPluginEnabled()
void ccPluginManager::setPluginEnabled (const ccPluginInterface * plugin, bool enabled)
Definition at line 209 of file ecvPluginManager.cpp.
References ccPluginInterface::IID().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVAppCommon/include/ecvPluginManager.h
/root/ACloudViewer/libs/CVAppCommon/src/ecvPluginManager.cpp