ACloudViewer: cloudViewer::visualization::gui::NumberEdit Class Reference
cloudViewer::visualization::gui::NumberEdit Class Reference
#include <NumberEdit.h>
Classes
struct Impl
Public Types
enum Type { INT , DOUBLE }
Public Types inherited from cloudViewer::visualization::gui::Widget
enum class DrawResult { NONE , REDRAW , RELAYOUT }
enum class EventResult { IGNORED , CONSUMED , DISCARD }
Public Member Functions
NumberEdit (Type type)
~NumberEdit ()
int GetIntValue () const
double GetDoubleValue () const
void SetValue (double val)
double GetMinimumValue () const
double GetMaximumValue () const
void SetLimits (double min_value, double max_value)
int GetDecimalPrecision ()
void SetDecimalPrecision (int num_digits)
void SetPreferredWidth (int width)
void SetOnValueChanged (std::function< void(double)> on_changed)
Size CalcPreferredSize (const LayoutContext &context, const Constraints &constraints) const override
Widget::DrawResult Draw (const DrawContext &context) override
Public Member Functions inherited from cloudViewer::visualization::gui::Widget
Widget ()
Widget (const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Widget ()
virtual void AddChild (std::shared_ptr< Widget > child)
virtual const std::vector< std::shared_ptr< Widget > > GetChildren () const
virtual const Rect & GetFrame () const
Returns the frame size in pixels.
virtual void SetFrame (const Rect &f)
virtual const Color & GetBackgroundColor () const
virtual bool IsDefaultBackgroundColor () const
virtual void SetBackgroundColor (const Color &color)
virtual bool IsVisible () const
virtual void SetVisible (bool vis)
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
virtual void SetTooltip (const char *text)
virtual const char * GetTooltip () const
virtual Size CalcMinimumSize (const LayoutContext &context) const
virtual void Layout (const LayoutContext &context)
virtual EventResult Mouse (const MouseEvent &e)
virtual EventResult Key (const KeyEvent &e)
virtual DrawResult Tick (const TickEvent &e)
Additional Inherited Members
Static Public Attributes inherited from cloudViewer::visualization::gui::Widget
static constexpr int DIM_GROW = 10000
Protected Member Functions inherited from cloudViewer::visualization::gui::Widget
void DrawImGuiPushEnabledState ()
void DrawImGuiPopEnabledState ()
void DrawImGuiTooltip ()
Detailed Description
Definition at line 18 of file NumberEdit.h.
Member Enumeration Documentation
Type
enum cloudViewer::visualization::gui::NumberEdit::Type
Enumerator
INT
DOUBLE
Definition at line 22 of file NumberEdit.h.
Constructor & Destructor Documentation
NumberEdit()
cloudViewer::visualization::gui::NumberEdit::NumberEdit (Type type) explicit
Definition at line 42 of file NumberEdit.cpp.
References patch::to_string(), and type.
~NumberEdit()
cloudViewer::visualization::gui::NumberEdit::~NumberEdit ()
Definition at line 47 of file NumberEdit.cpp.
Member Function Documentation
CalcPreferredSize()
Size cloudViewer::visualization::gui::NumberEdit::CalcPreferredSize (const LayoutContext & context, const Constraints & constraints) const override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 90 of file NumberEdit.cpp.
References abs(), cloudViewer::utility::ceil(), context, height, INT, max(), and width.
Draw()
Widget::DrawResult cloudViewer::visualization::gui::NumberEdit::Draw (const DrawContext & context) override virtual
Draws the widget. If this is a Dear ImGUI widget, this is where the actual event processing happens. Return NONE if no action needs to be taken, REDRAW if the widget needs to be redrawn (e.g. its value changed), and RELAYOUT if the widget wishes to change size.
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 117 of file NumberEdit.cpp.
References cloudViewer::visualization::gui::colorToImgui(), context, cloudViewer::visualization::gui::Widget::DrawImGuiPopEnabledState(), cloudViewer::visualization::gui::Widget::DrawImGuiPushEnabledState(), cloudViewer::visualization::gui::Widget::DrawImGuiTooltip(), frame, cloudViewer::visualization::gui::Widget::GetFrame(), INT, cloudViewer::visualization::gui::Widget::NONE, cloudViewer::visualization::gui::Widget::REDRAW, result, SetValue(), and width.
GetDecimalPrecision()
int cloudViewer::visualization::gui::NumberEdit::GetDecimalPrecision ()
Definition at line 76 of file NumberEdit.cpp.
GetDoubleValue()
double cloudViewer::visualization::gui::NumberEdit::GetDoubleValue () const
Definition at line 51 of file NumberEdit.cpp.
GetIntValue()
int cloudViewer::visualization::gui::NumberEdit::GetIntValue () const
Definition at line 49 of file NumberEdit.cpp.
GetMaximumValue()
double cloudViewer::visualization::gui::NumberEdit::GetMaximumValue () const
Definition at line 63 of file NumberEdit.cpp.
GetMinimumValue()
double cloudViewer::visualization::gui::NumberEdit::GetMinimumValue () const
Definition at line 61 of file NumberEdit.cpp.
SetDecimalPrecision()
void cloudViewer::visualization::gui::NumberEdit::SetDecimalPrecision (int num_digits)
Definition at line 78 of file NumberEdit.cpp.
SetLimits()
void cloudViewer::visualization::gui::NumberEdit::SetLimits (double min_value, double max_value)
Definition at line 65 of file NumberEdit.cpp.
References INT, max(), and min().
SetOnValueChanged()
void cloudViewer::visualization::gui::NumberEdit::SetOnValueChanged (std::function< void(double)> on_changed)
Definition at line 86 of file NumberEdit.cpp.
SetPreferredWidth()
void cloudViewer::visualization::gui::NumberEdit::SetPreferredWidth (int width)
Definition at line 82 of file NumberEdit.cpp.
References width.
SetValue()
void cloudViewer::visualization::gui::NumberEdit::SetValue (double val)
Definition at line 53 of file NumberEdit.cpp.
References INT.
Referenced by Draw().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/NumberEdit.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/NumberEdit.cpp