ACloudViewer: colmap::RelativePoseCostFunction Class Reference
colmap::RelativePoseCostFunction Class Reference
#include <cost_functions.h>
Public Member Functions
RelativePoseCostFunction (const Eigen::Vector2d &x1, const Eigen::Vector2d &x2)
template<typename T >
bool operator() (const T *const qvec, const T *const tvec, T *residuals) const
Static Public Member Functions
static ceres::CostFunction * Create (const Eigen::Vector2d &x1, const Eigen::Vector2d &x2)
Detailed Description
Definition at line 205 of file cost_functions.h.
Constructor & Destructor Documentation
RelativePoseCostFunction()
colmap::RelativePoseCostFunction::RelativePoseCostFunction (const Eigen::Vector2d & x1, const Eigen::Vector2d & x2) inline
Definition at line 207 of file cost_functions.h.
Referenced by Create().
Member Function Documentation
Create()
static ceres::CostFunction* colmap::RelativePoseCostFunction::Create (const Eigen::Vector2d & x1, const Eigen::Vector2d & x2) inline static
Definition at line 211 of file cost_functions.h.
References RelativePoseCostFunction().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::RefineRelativePose().
operator()()
template<typename T > bool colmap::RelativePoseCostFunction::operator() (const T *const qvec, const T *const tvec, T * residuals) const inline
Definition at line 219 of file cost_functions.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/base/cost_functions.h