ACloudViewer: ccColorScaleSelector Class Reference
ccColorScaleSelector Class Reference
Advanced editor for color scales.
#include <ecvColorScaleSelector.h>
Signals
void colorScaleSelected (int)
Signal emitted when a color scale is selected.
void colorScaleEditorSummoned ()
Public Member Functions
ccColorScaleSelector (ccColorScalesManager *manager, QWidget *parent, QString defaultButtonIconPath=QString())
Default constructor.
void init ()
Inits selector with the Color Scales Manager.
void setSelectedScale (QString uuid)
Sets selected combo box item (scale) by UUID.
ccColorScale::Shared getSelectedScale () const
Returns currently selected color scale.
ccColorScale::Shared getScale (int index) const
Returns a given color scale by index.
Protected Attributes
ccColorScalesManager * m_manager
Color scales manager.
QComboBox * m_comboBox
Color scales combo-box.
QToolButton * m_button
Spawn color scale editor button.
Detailed Description
Advanced editor for color scales.
Combo-box + shortcut to color scale editor
Definition at line 23 of file ecvColorScaleSelector.h.
Constructor & Destructor Documentation
ccColorScaleSelector()
ccColorScaleSelector::ccColorScaleSelector (ccColorScalesManager * manager, QWidget * parent, QString defaultButtonIconPath = QString())
Default constructor.
Definition at line 18 of file ecvColorScaleSelector.cpp.
References m_button, m_comboBox, m_manager, and cloudViewer::core::Maximum().
Member Function Documentation
colorScaleEditorSummoned
void ccColorScaleSelector::colorScaleEditorSummoned () signal
Signal emitted when the user clicks on the 'Spawn Color scale editor' button
Referenced by ccPropertiesTreeDelegate::createEditor(), and init().
colorScaleSelected
void ccColorScaleSelector::colorScaleSelected (int) signal
Signal emitted when a color scale is selected.
Referenced by ccPropertiesTreeDelegate::createEditor(), init(), and setSelectedScale().
getScale()
ccColorScale::Shared ccColorScaleSelector::getScale (int index) const
Returns a given color scale by index.
Definition at line 83 of file ecvColorScaleSelector.cpp.
References ccColorScalesManager::getScale(), m_comboBox, and m_manager.
Referenced by getSelectedScale().
getSelectedScale()
ccColorScale::Shared ccColorScaleSelector::getSelectedScale () const
Returns currently selected color scale.
Definition at line 79 of file ecvColorScaleSelector.cpp.
References getScale(), and m_comboBox.
Referenced by StereogramDialog::colorScaleChanged(), DistanceMapGenerationDlg::colorScaleChanged(), DistanceMapGenerationDlg::exportMapAsCloud(), DistanceMapGenerationDlg::exportMapAsMesh(), DistanceMapGenerationDlg::saveToPersistentSettings(), StereogramDialog::spawnColorScaleEditor(), DistanceMapGenerationDlg::spawnColorScaleEditor(), DistanceMapGenerationDlg::update(), and DistanceMapGenerationDlg::updateMapTexture().
init()
void ccColorScaleSelector::init ()
Inits selector with the Color Scales Manager.
Definition at line 44 of file ecvColorScaleSelector.cpp.
References colorScaleEditorSummoned(), colorScaleSelected(), m_button, m_comboBox, m_manager, and ccColorScalesManager::map().
Referenced by ccPropertiesTreeDelegate::createEditor(), DistanceMapGenerationDlg::DistanceMapGenerationDlg(), StereogramDialog::spawnColorScaleEditor(), DistanceMapGenerationDlg::spawnColorScaleEditor(), and StereogramDialog::StereogramDialog().
setSelectedScale()
void ccColorScaleSelector::setSelectedScale (QString uuid)
Sets selected combo box item (scale) by UUID.
Definition at line 93 of file ecvColorScaleSelector.cpp.
References colorScaleSelected(), and m_comboBox.
Referenced by DistanceMapGenerationDlg::DistanceMapGenerationDlg(), DistanceMapGenerationDlg::initFromPersistentSettings(), ccPropertiesTreeDelegate::setEditorData(), StereogramDialog::spawnColorScaleEditor(), DistanceMapGenerationDlg::spawnColorScaleEditor(), and StereogramDialog::StereogramDialog().
Member Data Documentation
m_button
QToolButton* ccColorScaleSelector::m_button protected
Spawn color scale editor button.
Definition at line 61 of file ecvColorScaleSelector.h.
Referenced by ccColorScaleSelector(), and init().
m_comboBox
QComboBox* ccColorScaleSelector::m_comboBox protected
Color scales combo-box.
Definition at line 58 of file ecvColorScaleSelector.h.
Referenced by ccColorScaleSelector(), getScale(), getSelectedScale(), init(), and setSelectedScale().
m_manager
ccColorScalesManager* ccColorScaleSelector::m_manager protected
Color scales manager.
Definition at line 55 of file ecvColorScaleSelector.h.
Referenced by ccColorScaleSelector(), getScale(), and init().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVPluginAPI/include/ecvColorScaleSelector.h
/root/ACloudViewer/libs/CVPluginAPI/src/ecvColorScaleSelector.cpp