ACloudViewer: QTextCodec Class Reference
QTextCodec Class Reference
#include <quazip.h>
Public Member Functions
QByteArray fromUnicode (const QString &str) const
QString toUnicode (const QByteArray &ba) const
QString toUnicode (const char *chars, int len=-1) const
Static Public Member Functions
static QTextCodec * codecForLocale ()
static QTextCodec * codecForName (const char *name)
Detailed Description
Definition at line 36 of file quazip.h.
Member Function Documentation
codecForLocale()
static QTextCodec* QTextCodec::codecForLocale () inline static
Definition at line 44 of file quazip.h.
References qtCompatCodecForLocale().
codecForName()
static QTextCodec* QTextCodec::codecForName (const char * name) inline static
Definition at line 50 of file quazip.h.
References name, and qtCompatCodecForName().
Referenced by QuaZip::setCommentCodec(), QuaZip::setDefaultFileNameCodec(), and QuaZip::setFileNameCodec().
fromUnicode()
QByteArray QTextCodec::fromUnicode (const QString & str) const inline
Definition at line 61 of file quazip.h.
References QtCompatTextCodec::fromUnicode().
toUnicode() [1/2]
QString QTextCodec::toUnicode (const char * chars, int len = -1) const inline
Definition at line 69 of file quazip.h.
References QtCompatTextCodec::toUnicode().
toUnicode() [2/2]
QString QTextCodec::toUnicode (const QByteArray & ba) const inline
Definition at line 65 of file quazip.h.
References QtCompatTextCodec::toUnicode().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/IO/qPhotoscanIO/extern/quazip/quazip/quazip/quazip.h