ACloudViewer: qCanupoPlugin Class Reference
qCanupoPlugin Class Reference
CANUPO plugin.
#include <qCanupo.h>
Protected Slots
void doClassifyAction ()
void doTrainAction ()
Protected Attributes
QAction * m_classifyAction
Calssift action.
QAction * m_trainAction
Train action.
ccHObject::Container m_selectedEntities
Currently selected entities.
Detailed Description
CANUPO plugin.
See "3D Terrestrial lidar data classification of complex natural scenes using a multi-scale dimensionality criterion: applications in geomorphology", N. Brodu, D. Lague, 2012, Computer Vision and Pattern Recognition
Definition at line 21 of file qCanupo.h.
Member Function Documentation
doClassifyAction
void qCanupoPlugin::doClassifyAction () protected slot
Definition at line 93 of file qCanupo.cpp.
References ccHObject::addChild(), qCanupoProcess::Classify(), corePoints, error(), qCanupoClassifDialog::getConfidenceTrehshold(), qCanupoClassifDialog::getCorePointsCloud(), qCanupoClassifDialog::getCorePointsCloudSource(), qCanupoClassifDialog::getMaxThreadCount(), qCanupoClassifDialog::getMscFilename(), ccObject::getName(), CorePointDescSet::loadFromMSC(), m_selectedEntities, qCanupoClassifDialog::MSC_FILE, qCanupoClassifDialog::ORIGINAL, qCanupoClassifDialog::OTHER, params, ccPointCloud::partialClone(), CV_TYPES::POINT_CLOUD, cloudViewer::CloudSamplingTools::resampleCloudSpatially(), qCanupoClassifDialog::saveParamsToPersistentSettings(), ccObject::setName(), ccDrawableObject::setRedraw(), ecvDisplayTools::SetRedrawRecursive(), ShowClassifyDisclaimer(), qCanupoClassifDialog::SUBSAMPLED, and qCanupoClassifDialog::useSF().
doTrainAction
void qCanupoPlugin::doTrainAction () protected slot
Definition at line 254 of file qCanupo.cpp.
References qCanupoTools::ComputeCorePointsDescriptors(), computer, ScaleParamsComputer::GetByID(), qCanupoTrainingDialog::getClass1Cloud(), qCanupoTrainingDialog::getClass2Cloud(), ccPointCloud::getCurrentDisplayedScalarField(), qCanupoTrainingDialog::getDescriptorID(), qCanupoTrainingDialog::getEvaluationCloud(), qCanupoTrainingDialog::getMaxThreadCount(), ccObject::getName(), qCanupoTrainingDialog::getOriginPointCloud(), qCanupoTrainingDialog::getScales(), invalidDescriptors, ScaleParamsComputer::needSF(), qCanupoTrainingDialog::saveParamsToPersistentSettings(), ShowTrainDisclaimer(), cloudViewer::PointCloudTpl< T >::size(), cloudViewer::CloudSamplingTools::subsampleCloudRandomly(), and qCanupo2DViewDialog::trainClassifier().
Member Data Documentation
m_classifyAction
QAction* qCanupoPlugin::m_classifyAction protected
Calssift action.
Definition at line 43 of file qCanupo.h.
m_selectedEntities
ccHObject::Container qCanupoPlugin::m_selectedEntities protected
Currently selected entities.
Definition at line 48 of file qCanupo.h.
Referenced by doClassifyAction().
m_trainAction
QAction* qCanupoPlugin::m_trainAction protected
Train action.
Definition at line 45 of file qCanupo.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCanupo/include/qCanupo.h
/root/ACloudViewer/plugins/core/Standard/qCanupo/src/qCanupo.cpp