ACloudViewer: colmap::MatchMatrixWidget Class Reference
colmap::MatchMatrixWidget Class Reference
#include <match_matrix_widget.h>
Public Member Functions
MatchMatrixWidget (QWidget *parent, OptionManager *options)
void Show ()
Public Member Functions inherited from colmap::ImageViewerWidget
ImageViewerWidget (QWidget *parent)
void ShowBitmap (const Bitmap &bitmap)
void ShowPixmap (const QPixmap &pixmap)
void ReadAndShow (const std::string &path)
Additional Inherited Members
Protected Member Functions inherited from colmap::ImageViewerWidget
void resizeEvent (QResizeEvent *event)
void closeEvent (QCloseEvent *event)
void ZoomIn ()
void ZoomOut ()
void Save ()
Protected Attributes inherited from colmap::ImageViewerWidget
QGridLayout * grid_layout_
QHBoxLayout * button_layout_
Detailed Description
Definition at line 16 of file match_matrix_widget.h.
Constructor & Destructor Documentation
MatchMatrixWidget()
colmap::MatchMatrixWidget::MatchMatrixWidget (QWidget * parent, OptionManager * options)
Definition at line 36 of file match_matrix_widget.cc.
Member Function Documentation
Show()
void colmap::MatchMatrixWidget::Show ()
Definition at line 41 of file match_matrix_widget.cc.
References colmap::Bitmap::Allocate(), colmap::JetColormap::Blue(), color, colmap::OptionManager::database_path, colmap::Bitmap::Fill(), colmap::JetColormap::Green(), colmap::Database::NumImages(), colmap::Database::ReadAllImages(), colmap::Database::ReadTwoViewGeometryNumInliers(), colmap::JetColormap::Red(), colmap::Bitmap::SetPixel(), and colmap::ImageViewerWidget::ShowBitmap().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/match_matrix_widget.h
/root/ACloudViewer/libs/Reconstruction/src/ui/match_matrix_widget.cc