ACloudViewer: colmap::mvs::Image Class Reference
colmap::mvs::Image Class Reference
#include <image.h>
Public Member Functions
Image ()
Image (const std::string &path, const size_t width, const size_t height, const float *K, const float *R, const float *T)
size_t GetWidth () const
size_t GetHeight () const
void SetBitmap (const Bitmap &bitmap)
const Bitmap & GetBitmap () const
const std::string & GetPath () const
const float * GetR () const
const float * GetT () const
const float * GetK () const
const float * GetP () const
const float * GetInvP () const
const float * GetViewingDirection () const
void Rescale (const float factor)
void Rescale (const float factor_x, const float factor_y)
void Downsize (const size_t max_width, const size_t max_height)
Detailed Description
Definition at line 22 of file image.h.
Constructor & Destructor Documentation
Image() [1/2]
colmap::mvs::Image::Image ()
Definition at line 42 of file image.cc.
Image() [2/2]
colmap::mvs::Image::Image (const std::string & path, const size_t width, const size_t height, const float * K, const float * R, const float * T)
Definition at line 44 of file image.cc.
Member Function Documentation
Downsize()
void colmap::mvs::Image::Downsize (const size_t max_width, const size_t max_height)
Definition at line 83 of file image.cc.
References Rescale().
GetBitmap()
const Bitmap & colmap::mvs::Image::GetBitmap () const inline
Definition at line 91 of file image.h.
GetHeight()
size_t colmap::mvs::Image::GetHeight () const inline
Definition at line 89 of file image.h.
Referenced by colmap::mvs::PatchMatch::Check().
GetInvP()
const float * colmap::mvs::Image::GetInvP () const inline
Definition at line 103 of file image.h.
GetK()
const float * colmap::mvs::Image::GetK () const inline
Definition at line 99 of file image.h.
GetP()
const float * colmap::mvs::Image::GetP () const inline
Definition at line 101 of file image.h.
GetPath()
const std::string & colmap::mvs::Image::GetPath () const inline
Definition at line 93 of file image.h.
GetR()
const float * colmap::mvs::Image::GetR () const inline
Definition at line 95 of file image.h.
GetT()
const float * colmap::mvs::Image::GetT () const inline
Definition at line 97 of file image.h.
GetViewingDirection()
const float * colmap::mvs::Image::GetViewingDirection () const inline
Definition at line 105 of file image.h.
GetWidth()
size_t colmap::mvs::Image::GetWidth () const inline
Definition at line 87 of file image.h.
Referenced by colmap::mvs::PatchMatch::Check().
Rescale() [1/2]
void colmap::mvs::Image::Rescale (const float factor)
Definition at line 60 of file image.cc.
Referenced by Downsize().
Rescale() [2/2]
void colmap::mvs::Image::Rescale (const float factor_x, const float factor_y)
Definition at line 62 of file image.cc.
References colmap::mvs::ComposeInverseProjectionMatrix(), colmap::mvs::ComposeProjectionMatrix(), colmap::Bitmap::Data(), and colmap::Bitmap::Rescale().
SetBitmap()
void colmap::mvs::Image::SetBitmap (const Bitmap & bitmap)
Definition at line 54 of file image.cc.
References colmap::Bitmap::Height(), and colmap::Bitmap::Width().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/mvs/image.h
/root/ACloudViewer/libs/Reconstruction/src/mvs/image.cc