ACloudViewer: vtkScalarBarWidgetCustom Class Reference
vtkScalarBarWidgetCustom Class Reference
#include <vtkScalarBarWidgetCustom.h>
Public Member Functions
vtkTypeMacro (vtkScalarBarWidgetCustom, vtkBorderWidget)
void PrintSelf (ostream &os, vtkIndent indent) override
virtual void SetRepresentation (vtkScalarBarRepresentation *rep) override
vtkScalarBarRepresentation * GetScalarBarRepresentation ()
virtual void SetScalarBarActor (vtkScalarBarActor *actor) override
virtual vtkScalarBarActor * GetScalarBarActor () override
void CreateDefaultRepresentation () override
void CreateDefaultScalarBarActor ()
Static Public Member Functions
static vtkScalarBarWidgetCustom * New ()
Protected Member Functions
vtkScalarBarWidgetCustom ()
~vtkScalarBarWidgetCustom () override
Detailed Description
Definition at line 14 of file vtkScalarBarWidgetCustom.h.
Constructor & Destructor Documentation
vtkScalarBarWidgetCustom()
vtkScalarBarWidgetCustom::vtkScalarBarWidgetCustom () protected
Definition at line 28 of file vtkScalarBarWidgetCustom.cpp.
~vtkScalarBarWidgetCustom()
vtkScalarBarWidgetCustom::~vtkScalarBarWidgetCustom () override protected default
Member Function Documentation
CreateDefaultRepresentation()
void vtkScalarBarWidgetCustom::CreateDefaultRepresentation () override
Create the default widget representation if one is not set.
Definition at line 73 of file vtkScalarBarWidgetCustom.cpp.
References vtkScalarBarRepresentationCustom::LowerRightCorner, vtkScalarBarRepresentationCustom::New(), and SetRepresentation().
Referenced by GetScalarBarActor(), and SetScalarBarActor().
CreateDefaultScalarBarActor()
void vtkScalarBarWidgetCustom::CreateDefaultScalarBarActor ()
Definition at line 84 of file vtkScalarBarWidgetCustom.cpp.
References vtkContext2DScalarBarActor::New(), and SetScalarBarActor().
GetScalarBarActor()
vtkScalarBarActor * vtkScalarBarWidgetCustom::GetScalarBarActor () override virtual
Definition at line 62 of file vtkScalarBarWidgetCustom.cpp.
References CreateDefaultRepresentation(), and GetScalarBarRepresentation().
Referenced by PclTools::UpdateScalarBar().
GetScalarBarRepresentation()
vtkScalarBarRepresentation* vtkScalarBarWidgetCustom::GetScalarBarRepresentation () inline
Return the representation as a vtkScalarBarRepresentation.
Definition at line 30 of file vtkScalarBarWidgetCustom.h.
Referenced by GetScalarBarActor(), and SetScalarBarActor().
New()
static vtkScalarBarWidgetCustom* vtkScalarBarWidgetCustom::New () static
PrintSelf()
void vtkScalarBarWidgetCustom::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 97 of file vtkScalarBarWidgetCustom.cpp.
References QtCompat::endl().
SetRepresentation()
void vtkScalarBarWidgetCustom::SetRepresentation (vtkScalarBarRepresentation * rep) override virtual
Specify an instance of vtkWidgetRepresentation used to represent this widget in the scene. Note that the representation is a subclass of vtkProp so it can be added to the renderer independent of the widget.
Definition at line 42 of file vtkScalarBarWidgetCustom.cpp.
Referenced by CreateDefaultRepresentation().
SetScalarBarActor()
void vtkScalarBarWidgetCustom::SetScalarBarActor (vtkScalarBarActor * actor) override virtual
Get the ScalarBar used by this Widget. One is created automatically.
Definition at line 48 of file vtkScalarBarWidgetCustom.cpp.
References CreateDefaultRepresentation(), and GetScalarBarRepresentation().
Referenced by CreateDefaultScalarBarActor(), and PclTools::UpdateScalarBar().
vtkTypeMacro()
vtkScalarBarWidgetCustom::vtkTypeMacro (vtkScalarBarWidgetCustom , vtkBorderWidget)
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Widgets/vtkScalarBarWidgetCustom.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Widgets/vtkScalarBarWidgetCustom.cpp