ACloudViewer: ccRasterizeTool Class Reference
ccRasterizeTool Class Reference
Rasterize tool (dialog)
#include <ecvRasterizeTool.h>
Classes
struct ExportBands
Bands to be exported.
Public Member Functions
ccRasterizeTool (ccGenericPointCloud *cloud, QWidget *parent=0)
Default constructor.
~ccRasterizeTool ()
Destructor.
Public Member Functions inherited from cc2Point5DimEditor
cc2Point5DimEditor ()
Default constructor.
virtual ~cc2Point5DimEditor ()
Destructor.
Static Public Member Functions
static bool ExportGeoTiff (QString outputFilename, const ExportBands &exportBands, ccRasterGrid::EmptyCellFillOption fillEmptyCellsStrategy, const ccRasterGrid &grid, const ccBBox &gridBBox, unsigned char Z, double customHeightForEmptyCells=std::numeric_limits< double >::quiet_NaN(), ccGenericPointCloud *originCloud=0, int visibleSfIndex=-1)
Exports a raster grid as a geotiff file.
Protected Types
enum LayerType { LAYER_HEIGHT = 0 , LAYER_RGB = 1 , LAYER_SF = 2 }
Layer types.
Protected Slots
ccPointCloud * generateCloud (bool autoExport=true) const
Exports the grid as a cloud.
void generateRaster () const
Exports the grid as a raster.
void generateMesh () const
Exports the grid as a mesh.
void exportContourLines ()
Exports the (already generated) contour lines.
void generateContours ()
Generates a contour plot.
void generateHillshade ()
Generates hillshade.
void removeContourLines ()
Removes all displayed contour lines.
void testAndAccept ()
Accepts the dialog (if some conditions are met) and save settings.
void testAndReject ()
Rejects the dialog (if some conditions are met)
void saveSettings ()
Save persistent settings and 'accept' dialog.
void activeLayerChanged (int, bool autoRedraw=true)
Called when the active layer changes.
void projectionDirChanged (int)
Called when the projection direction changes.
void projectionTypeChanged (int)
Called when the projection type changes.
void resampleOptionToggled (bool)
Called when the 'resampled' option changes.
void sfProjectionTypeChanged (int)
Called when the SF projection type changes.
virtual bool showGridBoxEditor () override
void fillEmptyCellStrategyChanged (int)
Called when the empty cell filling strategy changes.
void gridOptionChanged ()
Called when the an option of the grid generation has changed.
void updateGridInfo ()
Updates the gid info.
void updateGridAndDisplay ()
Update the grid and the 2D display.
virtual void generateImage () const
Exports the grid as an image.
virtual void generateASCIIMatrix () const
Exports the grid as an ASCII matrix.
Protected Member Functions
virtual double getGridStep () const override
Returns projection grid step.
virtual unsigned char getProjectionDimension () const override
Returns projection dimension.
virtual ccRasterGrid::ProjectionType getTypeOfProjection () const override
Returns type of projection.
double getCustomHeightForEmptyCells () const
Returns user defined height for empty cells.
ccRasterGrid::EmptyCellFillOption getFillEmptyCellsStrategyExt (double &emptyCellsHeight, double &minHeight, double &maxHeight) const
Returns strategy for empty cell filling (extended version)
bool exportAsSF (ccRasterGrid::ExportableFields field) const
bool resampleOriginalCloud () const
ccRasterGrid::ProjectionType getTypeOfSFInterpolation () const
Returns type of SF interpolation.
virtual void gridIsUpToDate (bool state) override
Declares whether the grid is up-to-date or not.
void loadSettings ()
Load persistent settings.
bool updateGrid (bool interpolateSF=false)
Updates the grid.
bool canClose ()
Tests if the dialog can be safely closed.
void addNewContour (ccPolyline *poly, double height, unsigned subIndex)
Adds a new contour line.
ccPointCloud * convertGridToCloud (const std::vector< ccRasterGrid::ExportableFields > &exportedFields, bool interpolateSF, bool interpolateColors, bool copyHillshadeSF, QString activeSFName, bool exportToOriginalCS) const
Converts the grid to a cloud with scalar field(s)
Protected Member Functions inherited from cc2Point5DimEditor
virtual ccBBox getCustomBBox () const
Returns custom bbox.
virtual void update2DDisplayZoom (ccBBox &box)
Updates the 2D display zoom.
virtual bool showGridBoxEditor ()
Show grid box editor and update.
virtual QString getGridSizeAsString () const
Returns the grid size as a string.
virtual bool getGridSize (unsigned &width, unsigned &height) const
Returns the grid size.
void createBoundingBoxEditor (const ccBBox &gridBBox, QWidget *parent)
Creates the bounding-box editor.
void create2DView (QFrame *parentFrame)
Creates the 2D view.
ccRasterGrid::EmptyCellFillOption getFillEmptyCellsStrategy (QComboBox *comboBox) const
Returns the empty cell strategy (for a given combo-box)
ccPointCloud * convertGridToCloud (const std::vector< ccRasterGrid::ExportableFields > &exportedFields, bool interpolateSF, bool interpolateColors, bool resampleInputCloudXY, bool resampleInputCloudZ, ccGenericPointCloud *inputCloud, bool fillEmptyCells, double emptyCellsHeight, bool exportToOriginalCS) const
Shortcut to ccRasterGrid::convertToCloud.
Protected Attributes
ccGenericPointCloud * m_cloud
Associated cloud.
std::vector< ccPolyline * > m_contourLines
Contour lines.
Protected Attributes inherited from cc2Point5DimEditor
ccRasterGrid m_grid
Raster grid.
ccBoundingBoxEditorDlg * m_bbEditorDlg
Associated dialog.
ccPointCloud * m_rasterCloud
'Raster' cloud
Detailed Description
Rasterize tool (dialog)
Definition at line 23 of file ecvRasterizeTool.h.
Member Enumeration Documentation
LayerType
enum ccRasterizeTool::LayerType protected
Layer types.
Enumerator
LAYER_HEIGHT
LAYER_RGB
LAYER_SF
Definition at line 178 of file ecvRasterizeTool.h.
Constructor & Destructor Documentation
ccRasterizeTool()
ccRasterizeTool::ccRasterizeTool (ccGenericPointCloud * cloud, QWidget * parent = 0)
Default constructor.
Definition at line 44 of file ecvRasterizeTool.cpp.
References activeLayerChanged(), cc2Point5DimEditor::create2DView(), cc2Point5DimEditor::createBoundingBoxEditor(), exportContourLines(), fillEmptyCellStrategyChanged(), generateASCIIMatrix(), generateCloud(), generateContours(), generateHillshade(), generateImage(), generateMesh(), generateRaster(), ccRasterGrid::GetDefaultFieldName(), cloudViewer::ScalarField::getName(), ccObject::getName(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), ccGenericPointCloud::getOwnBB(), cloudViewer::PointCloudTpl< T >::getScalarField(), gridIsUpToDate(), gridOptionChanged(), ccDrawableObject::hasColors(), ccDrawableObject::hasScalarFields(), ccObject::isA(), LAYER_HEIGHT, LAYER_RGB, LAYER_SF, loadSettings(), m_cloud, ccRasterGrid::PER_CELL_VALUE, CV_TYPES::POINT_CLOUD, projectionDirChanged(), projectionTypeChanged(), removeContourLines(), resampleOptionToggled(), ccObject::setEnabled(), sfProjectionTypeChanged(), showGridBoxEditor(), cloudViewer::GenericCloud::size(), testAndAccept(), testAndReject(), updateGridAndDisplay(), and updateGridInfo().
~ccRasterizeTool()
ccRasterizeTool::~ccRasterizeTool ()
Destructor.
Definition at line 180 of file ecvRasterizeTool.cpp.
References removeContourLines().
Member Function Documentation
activeLayerChanged
void ccRasterizeTool::activeLayerChanged (int layerIndex, bool autoRedraw = true) protected slot
Called when the active layer changes.
Definition at line 273 of file ecvRasterizeTool.cpp.
References ccScalarField::displayRange(), ccPointCloud::getCurrentDisplayedScalarField(), ecvDisplayTools::GetMainWindow(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), gridIsUpToDate(), ccPointCloud::hasColors(), ccDrawableObject::hasScalarFields(), HILLSHADE_FIELD_NAME, LAYER_RGB, LAYER_SF, m_cloud, cc2Point5DimEditor::m_rasterCloud, ccScalarField::Range::max(), ccScalarField::Range::min(), ccScalarField::Range::range(), ecvDisplayTools::RedrawDisplay(), ccPointCloud::setCurrentDisplayedScalarField(), ccDrawableObject::showColors(), and ccDrawableObject::showSF().
Referenced by ccRasterizeTool(), and updateGridAndDisplay().
addNewContour()
void ccRasterizeTool::addNewContour (ccPolyline * poly, double height, unsigned subIndex) protected
Adds a new contour line.
Definition at line 1644 of file ecvRasterizeTool.cpp.
References ecvDisplayTools::AddToOwnDB(), ecvColor::darkGrey(), ccScalarField::getColor(), ccPointCloud::getCurrentDisplayedScalarField(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ecvDisplayTools::GetMainWindow(), height, m_cloud, m_contourLines, cc2Point5DimEditor::m_rasterCloud, ccPolyline::setColor(), ccPolyline::setGlobalScale(), ccPolyline::setGlobalShift(), ccObject::setName(), ccPolyline::setWidth(), ccDrawableObject::showColors(), and cloudViewer::ReferenceCloud::size().
Referenced by generateContours().
canClose()
bool ccRasterizeTool::canClose () protected
Tests if the dialog can be safely closed.
Definition at line 486 of file ecvRasterizeTool.cpp.
References m_contourLines.
Referenced by testAndAccept(), and testAndReject().
convertGridToCloud()
ccPointCloud * ccRasterizeTool::convertGridToCloud (const std::vector< ccRasterGrid::ExportableFields > & exportedFields, bool interpolateSF, bool interpolateColors, bool copyHillshadeSF, QString activeSFName, bool exportToOriginalCS) const protected
Converts the grid to a cloud with scalar field(s)
Definition at line 558 of file ecvRasterizeTool.cpp.
References ccPointCloud::addScalarField(), cc2Point5DimEditor::convertGridToCloud(), cloudViewer::ScalarField::currentSize(), getFillEmptyCellsStrategyExt(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), getTypeOfProjection(), HILLSHADE_FIELD_NAME, ccEntityAction::interpolateColors(), ccRasterGrid::isValid(), ccRasterGrid::LEAVE_EMPTY, m_cloud, cc2Point5DimEditor::m_grid, cc2Point5DimEditor::m_rasterCloud, ccRasterGrid::maxHeight, ccRasterGrid::minHeight, ccRasterGrid::PROJ_AVERAGE_VALUE, resampleOriginalCloud(), ccPointCloud::setCurrentDisplayedScalarField(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), cloudViewer::PointCloudTpl< T >::size(), and CVLog::Warning().
Referenced by generateCloud(), and updateGridAndDisplay().
exportAsSF()
bool ccRasterizeTool::exportAsSF (ccRasterGrid::ExportableFields field) const protected
Returns whether a given field count should be exported as SF (only if a cloud is generated!)
Definition at line 214 of file ecvRasterizeTool.cpp.
References ccRasterGrid::PER_CELL_AVG_VALUE, ccRasterGrid::PER_CELL_COUNT, ccRasterGrid::PER_CELL_MAX_VALUE, ccRasterGrid::PER_CELL_MIN_VALUE, ccRasterGrid::PER_CELL_VALUE_RANGE, and ccRasterGrid::PER_CELL_VALUE_STD_DEV.
Referenced by generateCloud().
exportContourLines
void ccRasterizeTool::exportContourLines () protected slot
Exports the (already generated) contour lines.
Definition at line 2044 of file ecvRasterizeTool.cpp.
References ccHObject::addChild(), MainWindow::addToDB(), cloudViewer::ReferenceCloud::getAssociatedCloud(), ecvDisplayTools::GetMainWindow(), ccObject::getName(), cloudViewer::PointCloudTpl< T >::getPoint(), getProjectionDimension(), cloudViewer::ReferenceCloud::invalidateBoundingBox(), ccPointCloud::invalidateBoundingBox(), m_cloud, m_contourLines, CVLog::Print(), ecvDisplayTools::RemoveFromOwnDB(), ccDrawableObject::showColors(), cloudViewer::PointCloudTpl< T >::size(), MainWindow::TheInstance(), Tuple3Tpl< Type >::u, Tuple3Tpl< Type >::x, X, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccRasterizeTool().
ExportGeoTiff()
bool ccRasterizeTool::ExportGeoTiff (QString outputFilename, const ExportBands & exportBands, ccRasterGrid::EmptyCellFillOption fillEmptyCellsStrategy, const ccRasterGrid & grid, const ccBBox & gridBBox, unsigned char Z, double customHeightForEmptyCells = std::numeric_limits<double>::quiet_NaN(), ccGenericPointCloud * originCloud = 0, int visibleSfIndex = -1) static
Exports a raster grid as a geotiff file.
Definition at line 1038 of file ecvRasterizeTool.cpp.
References ccRasterizeTool::ExportBands::allSFs, color, ccRasterizeTool::ExportBands::density, error(), CVLog::Error(), FALSE, ccRasterGrid::FILL_AVERAGE_HEIGHT, ccRasterGrid::FILL_CUSTOM_HEIGHT, ccRasterGrid::FILL_MAXIMUM_HEIGHT, ccRasterGrid::FILL_MINIMUM_HEIGHT, ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccRasterGrid::gridStep, ccRasterizeTool::ExportBands::height, ccRasterGrid::height, ccRasterGrid::INTERPOLATE_DELAUNAY, cloudViewer::BoundingBoxTpl< T >::isValid(), ccRasterGrid::LEAVE_EMPTY, max(), cloudViewer::BoundingBoxTpl< T >::maxCorner(), ccRasterGrid::maxHeight, ccRasterGrid::meanHeight, min(), cloudViewer::BoundingBoxTpl< T >::minCorner(), ccRasterGrid::minHeight, CVLog::Print(), CVLog::PrintDebug(), ccRasterizeTool::ExportBands::rgb, ccRasterGrid::rows, ccRasterGrid::scalarFields, Tuple3Tpl< Type >::u, ccRasterGrid::validCellCount, ccRasterizeTool::ExportBands::visibleSF, ccRasterGrid::width, and X.
Referenced by generateRaster(), and CommandRasterize::process().
fillEmptyCellStrategyChanged
void ccRasterizeTool::fillEmptyCellStrategyChanged (int) protected slot
Called when the empty cell filling strategy changes.
Definition at line 341 of file ecvRasterizeTool.cpp.
References ccRasterGrid::FILL_CUSTOM_HEIGHT, cc2Point5DimEditor::getFillEmptyCellsStrategy(), gridIsUpToDate(), and ccRasterGrid::INTERPOLATE_DELAUNAY.
Referenced by ccRasterizeTool().
generateASCIIMatrix
void ccRasterizeTool::generateASCIIMatrix () const protected virtual slot
Exports the grid as an ASCII matrix.
Definition at line 2275 of file ecvRasterizeTool.cpp.
References ecvFileUtils::defaultDocPath(), getFillEmptyCellsStrategyExt(), ccRasterGrid::height, ecvPS::HeightGridGeneration(), ccRasterGrid::isValid(), cc2Point5DimEditor::m_grid, ccRasterGrid::maxHeight, ccRasterGrid::minHeight, CVLog::Print(), ccRasterGrid::rows, CVLog::Warning(), and ccRasterGrid::width.
Referenced by ccRasterizeTool().
generateCloud
ccPointCloud * ccRasterizeTool::generateCloud (bool autoExport = true) const protected slot
Exports the grid as a cloud.
Definition at line 804 of file ecvRasterizeTool.cpp.
References ccHObject::addChild(), MainWindow::addToDB(), convertGridToCloud(), CVLog::Error(), exportAsSF(), ccObject::getName(), ccHObject::getParent(), getTypeOfSFInterpolation(), ccRasterGrid::INVALID_PROJECTION_TYPE, ccObject::isEnabled(), ccRasterGrid::isValid(), LAYER_SF, m_cloud, cc2Point5DimEditor::m_grid, ccRasterGrid::PER_CELL_AVG_VALUE, ccRasterGrid::PER_CELL_COUNT, ccRasterGrid::PER_CELL_MAX_VALUE, ccRasterGrid::PER_CELL_MIN_VALUE, ccRasterGrid::PER_CELL_VALUE, ccRasterGrid::PER_CELL_VALUE_RANGE, ccRasterGrid::PER_CELL_VALUE_STD_DEV, CVLog::Print(), ccObject::setEnabled(), MainWindow::TheInstance(), and CVLog::Warning().
Referenced by ccRasterizeTool(), and generateMesh().
generateContours
void ccRasterizeTool::generateContours () protected slot
Generates a contour plot.
Definition at line 1680 of file ecvRasterizeTool.cpp.
References ccHObject::addChild(), addNewContour(), cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::ReferenceCloud::addPointIndex(), Isolines< T >::createOnePixelBorder(), cloudViewer::ScalarField::currentSize(), error(), CVLog::Error(), Isolines< T >::find(), cloudViewer::utility::floor(), cloudViewer::ReferenceCloud::getAssociatedCloud(), Isolines< T >::getContourLength(), Isolines< T >::getContourX(), Isolines< T >::getContourY(), ccPointCloud::getCurrentDisplayedScalarField(), cc2Point5DimEditor::getCustomBBox(), ecvDisplayTools::GetMainWindow(), cloudViewer::ScalarField::getMax(), ccObject::getMetaData(), cloudViewer::ScalarField::getMin(), cloudViewer::GenericIndexedCloud::getPoint(), getProjectionDimension(), cloudViewer::ScalarField::getValue(), ccRasterGrid::gridStep, height, ccRasterGrid::height, Isolines< T >::isContourClosed(), cloudViewer::BoundingBoxTpl< T >::isValid(), ccRasterGrid::isValid(), LAYER_HEIGHT, LAYER_RGB, m_contourLines, cc2Point5DimEditor::m_grid, cc2Point5DimEditor::m_rasterCloud, max(), ccPolyline::MetaKeyConstAltitude(), min(), cloudViewer::BoundingBoxTpl< T >::minCorner(), nProgress, cloudViewer::NormalizedProgress::oneStep(), params, CVLog::Print(), CVLog::PrintDebug(), ecvDisplayTools::RedrawDisplay(), removeContourLines(), cloudViewer::ReferenceCloud::reserve(), ccPointCloud::reserve(), ccRasterGrid::rows, cloudViewer::Polyline::setClosed(), ccObject::setEnabled(), ecvProgressDialog::setInfo(), ccObject::setMetaData(), ecvProgressDialog::setMethodTitle(), Isolines< T >::setThreshold(), cloudViewer::ReferenceCloud::size(), size, ecvProgressDialog::start(), Tuple3Tpl< Type >::u, cloudViewer::ScalarField::ValidValue(), ccRasterGrid::width, Tuple3Tpl< Type >::x, X, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccRasterizeTool().
generateHillshade
void ccRasterizeTool::generateHillshade () protected slot
Generates hillshade.
Definition at line 1408 of file ecvRasterizeTool.cpp.
References ccPointCloud::addScalarField(), ccScalarField::computeMinAndMax(), cloudViewer::ScalarField::currentSize(), cloudViewer::DegreesToRadians(), CVLog::Error(), fabs(), cloudViewer::ScalarField::fill(), ccColorScalesManager::GetDefaultScale(), ecvDisplayTools::GetMainWindow(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), ccColorScalesManager::GREY, ccRasterGrid::gridStep, ccRasterCell::h, ccRasterGrid::height, HILLSHADE_FIELD_NAME, ccRasterGrid::isValid(), LAYER_SF, cc2Point5DimEditor::m_grid, M_PI, cc2Point5DimEditor::m_rasterCloud, max(), NAN_VALUE, ecvDisplayTools::RedrawDisplay(), CCShareable::release(), cloudViewer::ScalarField::reserveSafe(), ccRasterGrid::rows, ccScalarField::setColorScale(), ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::ScalarField::setValue(), ccDrawableObject::showSF(), cloudViewer::PointCloudTpl< T >::size(), and ccRasterGrid::width.
Referenced by ccRasterizeTool().
generateImage
void ccRasterizeTool::generateImage () const protected virtual slot
Exports the grid as an image.
Definition at line 2144 of file ecvRasterizeTool.cpp.
References ecvColor::RgbTpl< Type >::b, ecvFileUtils::defaultDocPath(), CVLog::Error(), ccRasterGrid::FILL_AVERAGE_HEIGHT, ccRasterGrid::FILL_CUSTOM_HEIGHT, ccRasterGrid::FILL_MAXIMUM_HEIGHT, ccRasterGrid::FILL_MINIMUM_HEIGHT, cloudViewer::utility::floor(), ecvColor::RgbTpl< Type >::g, ccScalarField::getColorScale(), ccPointCloud::getCurrentDisplayedScalarField(), getFillEmptyCellsStrategyExt(), ImageFileFilter::GetSaveFilename(), ccRasterGrid::height, ecvPS::HeightGridGeneration(), ccRasterGrid::isValid(), ccRasterGrid::LEAVE_EMPTY, cloudViewer::LessThanEpsilon(), ecvColor::lightGrey(), cc2Point5DimEditor::m_grid, cc2Point5DimEditor::m_rasterCloud, ccRasterGrid::maxHeight, ccRasterGrid::minHeight, CVLog::Print(), ecvColor::RgbTpl< Type >::r, ccRasterGrid::rows, e57::toString(), and ccRasterGrid::width.
Referenced by ccRasterizeTool().
generateMesh
void ccRasterizeTool::generateMesh () const protected slot
Exports the grid as a mesh.
Definition at line 870 of file ecvRasterizeTool.cpp.
References ccHObject::addChild(), MainWindow::addToDB(), ccDrawableObject::colorsShown(), cloudViewer::PointProjectionTools::computeTriangulation(), cloudViewer::DELAUNAY_2D_AXIS_ALIGNED, CVLog::Error(), generateCloud(), ccObject::getName(), ccHObject::getParent(), getProjectionDimension(), m_cloud, CVLog::Print(), ccObject::setEnabled(), ccObject::setName(), ccDrawableObject::setVisible(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), and MainWindow::TheInstance().
Referenced by ccRasterizeTool().
generateRaster
void ccRasterizeTool::generateRaster () const protected slot
Exports the grid as a raster.
Definition at line 933 of file ecvRasterizeTool.cpp.
References ccRasterizeTool::ExportBands::allSFs, ecvFileUtils::defaultDocPath(), ccRasterizeTool::ExportBands::density, CVLog::Error(), ExportGeoTiff(), cc2Point5DimEditor::getCustomBBox(), getCustomHeightForEmptyCells(), cc2Point5DimEditor::getFillEmptyCellsStrategy(), getProjectionDimension(), ccRasterGrid::hasColors, ccRasterizeTool::ExportBands::height, ccRasterGrid::height, ecvPS::HeightGridGeneration(), ccObject::isA(), ccRasterGrid::isValid(), LAYER_SF, m_cloud, cc2Point5DimEditor::m_grid, CV_TYPES::POINT_CLOUD, ccRasterizeTool::ExportBands::rgb, ccRasterGrid::scalarFields, e57::toString(), ccRasterizeTool::ExportBands::visibleSF, and ccRasterGrid::width.
Referenced by ccRasterizeTool().
getCustomHeightForEmptyCells()
double ccRasterizeTool::getCustomHeightForEmptyCells () const protected
Returns user defined height for empty cells.
Definition at line 355 of file ecvRasterizeTool.cpp.
Referenced by generateRaster(), and getFillEmptyCellsStrategyExt().
getFillEmptyCellsStrategyExt()
ccRasterGrid::EmptyCellFillOption ccRasterizeTool::getFillEmptyCellsStrategyExt (double & emptyCellsHeight, double & minHeight, double & maxHeight) const protected
Returns strategy for empty cell filling (extended version)
Definition at line 2099 of file ecvRasterizeTool.cpp.
References ccRasterGrid::FILL_AVERAGE_HEIGHT, ccRasterGrid::FILL_CUSTOM_HEIGHT, ccRasterGrid::FILL_MAXIMUM_HEIGHT, ccRasterGrid::FILL_MINIMUM_HEIGHT, getCustomHeightForEmptyCells(), cc2Point5DimEditor::getFillEmptyCellsStrategy(), ccRasterGrid::height, ccRasterGrid::INTERPOLATE_DELAUNAY, ccRasterGrid::LEAVE_EMPTY, cc2Point5DimEditor::m_grid, ccRasterGrid::maxHeight, ccRasterGrid::meanHeight, ccRasterGrid::minHeight, ccRasterGrid::validCellCount, and ccRasterGrid::width.
Referenced by convertGridToCloud(), generateASCIIMatrix(), and generateImage().
getGridStep()
double ccRasterizeTool::getGridStep () const override protected virtual
Returns projection grid step.
Implements cc2Point5DimEditor.
Definition at line 210 of file ecvRasterizeTool.cpp.
Referenced by updateGrid().
getProjectionDimension()
unsigned char ccRasterizeTool::getProjectionDimension () const override protected virtual
Returns projection dimension.
Returns
dimension as int (0: X, 1: Y, 2:Z)
Implements cc2Point5DimEditor.
Definition at line 240 of file ecvRasterizeTool.cpp.
Referenced by exportContourLines(), generateContours(), generateMesh(), generateRaster(), and updateGrid().
getTypeOfProjection()
ccRasterGrid::ProjectionType ccRasterizeTool::getTypeOfProjection () const override protected virtual
Returns type of projection.
Implements cc2Point5DimEditor.
Definition at line 359 of file ecvRasterizeTool.cpp.
References ccRasterGrid::INVALID_PROJECTION_TYPE, ccRasterGrid::PROJ_AVERAGE_VALUE, ccRasterGrid::PROJ_MAXIMUM_VALUE, and ccRasterGrid::PROJ_MINIMUM_VALUE.
Referenced by convertGridToCloud(), resampleOptionToggled(), and updateGrid().
getTypeOfSFInterpolation()
ccRasterGrid::ProjectionType ccRasterizeTool::getTypeOfSFInterpolation () const protected
Returns type of SF interpolation.
interpolateSFCheckBox->isEnabled() ||
Definition at line 375 of file ecvRasterizeTool.cpp.
References ccRasterGrid::INVALID_PROJECTION_TYPE, ccRasterGrid::PROJ_AVERAGE_VALUE, ccRasterGrid::PROJ_MAXIMUM_VALUE, and ccRasterGrid::PROJ_MINIMUM_VALUE.
Referenced by generateCloud(), updateGrid(), and updateGridAndDisplay().
gridIsUpToDate()
void ccRasterizeTool::gridIsUpToDate (bool state) override protected virtual
Declares whether the grid is up-to-date or not.
Implements cc2Point5DimEditor.
Definition at line 544 of file ecvRasterizeTool.cpp.
Referenced by activeLayerChanged(), ccRasterizeTool(), fillEmptyCellStrategyChanged(), gridOptionChanged(), projectionDirChanged(), projectionTypeChanged(), sfProjectionTypeChanged(), and updateGridAndDisplay().
gridOptionChanged
void ccRasterizeTool::gridOptionChanged () protected slot
Called when the an option of the grid generation has changed.
Definition at line 353 of file ecvRasterizeTool.cpp.
References gridIsUpToDate().
Referenced by ccRasterizeTool(), and resampleOptionToggled().
loadSettings()
void ccRasterizeTool::loadSettings () protected
Load persistent settings.
Definition at line 400 of file ecvRasterizeTool.cpp.
References ecvPS::HeightGridGeneration().
Referenced by ccRasterizeTool().
projectionDirChanged
void ccRasterizeTool::projectionDirChanged (int dir) protected slot
Called when the projection direction changes.
Definition at line 268 of file ecvRasterizeTool.cpp.
References gridIsUpToDate(), and updateGridInfo().
Referenced by ccRasterizeTool().
projectionTypeChanged
void ccRasterizeTool::projectionTypeChanged (int index) protected slot
Called when the projection type changes.
Definition at line 254 of file ecvRasterizeTool.cpp.
References gridIsUpToDate(), and ccRasterGrid::PROJ_AVERAGE_VALUE.
Referenced by ccRasterizeTool().
removeContourLines
void ccRasterizeTool::removeContourLines () protected slot
Removes all displayed contour lines.
Definition at line 182 of file ecvRasterizeTool.cpp.
References ecvDisplayTools::GetMainWindow(), m_contourLines, ecvDisplayTools::RedrawDisplay(), and ecvDisplayTools::RemoveFromOwnDB().
Referenced by ccRasterizeTool(), generateContours(), updateGrid(), and ~ccRasterizeTool().
resampleOptionToggled
void ccRasterizeTool::resampleOptionToggled (bool state) protected slot
Called when the 'resampled' option changes.
Definition at line 247 of file ecvRasterizeTool.cpp.
References getTypeOfProjection(), gridOptionChanged(), and ccRasterGrid::PROJ_AVERAGE_VALUE.
Referenced by ccRasterizeTool().
resampleOriginalCloud()
bool ccRasterizeTool::resampleOriginalCloud () const protected
Returns whether the output cloud should use the original cloud or the grid as 'support'
Definition at line 235 of file ecvRasterizeTool.cpp.
Referenced by convertGridToCloud().
saveSettings
void ccRasterizeTool::saveSettings () protected slot
Save persistent settings and 'accept' dialog.
Definition at line 512 of file ecvRasterizeTool.cpp.
References ecvPS::HeightGridGeneration().
Referenced by testAndAccept().
sfProjectionTypeChanged
void ccRasterizeTool::sfProjectionTypeChanged (int index) protected slot
Called when the SF projection type changes.
Definition at line 264 of file ecvRasterizeTool.cpp.
References gridIsUpToDate().
Referenced by ccRasterizeTool().
showGridBoxEditor
bool ccRasterizeTool::showGridBoxEditor () override protected virtual slot
Definition at line 197 of file ecvRasterizeTool.cpp.
References cc2Point5DimEditor::showGridBoxEditor(), and updateGridInfo().
Referenced by ccRasterizeTool().
testAndAccept
void ccRasterizeTool::testAndAccept () protected slot
Accepts the dialog (if some conditions are met) and save settings.
Definition at line 499 of file ecvRasterizeTool.cpp.
References canClose(), and saveSettings().
Referenced by ccRasterizeTool().
testAndReject
void ccRasterizeTool::testAndReject () protected slot
Rejects the dialog (if some conditions are met)
Definition at line 506 of file ecvRasterizeTool.cpp.
References canClose().
Referenced by ccRasterizeTool().
updateGrid()
bool ccRasterizeTool::updateGrid (bool interpolateSF = false) protected
Updates the grid.
Definition at line 696 of file ecvRasterizeTool.cpp.
References CVLog::Error(), ccRasterGrid::fillWith(), Vector3Tpl< double >::fromArray(), cc2Point5DimEditor::getCustomBBox(), cc2Point5DimEditor::getFillEmptyCellsStrategy(), cc2Point5DimEditor::getGridSize(), getGridStep(), getProjectionDimension(), getTypeOfProjection(), getTypeOfSFInterpolation(), ccRasterGrid::gridStep, ccRasterGrid::height, ccRasterGrid::init(), ccRasterGrid::INTERPOLATE_DELAUNAY, ccEntityAction::interpolateSFs(), ccRasterGrid::INVALID_PROJECTION_TYPE, cloudViewer::BoundingBoxTpl< T >::isValid(), m_cloud, cc2Point5DimEditor::m_grid, ccRasterGrid::maxHeight, cloudViewer::BoundingBoxTpl< T >::minCorner(), ccRasterGrid::minHeight, CVLog::Print(), removeContourLines(), ccRasterGrid::rows, Tuple3Tpl< Type >::u, and ccRasterGrid::width.
Referenced by updateGridAndDisplay().
updateGridAndDisplay
void ccRasterizeTool::updateGridAndDisplay () protected slot
Update the grid and the 2D display.
Definition at line 632 of file ecvRasterizeTool.cpp.
References activeLayerChanged(), ecvDisplayTools::AddToOwnDB(), convertGridToCloud(), CVLog::Error(), ccHObject::getDisplayBB_recursive(), ecvDisplayTools::GetMainWindow(), getTypeOfSFInterpolation(), gridIsUpToDate(), HILLSHADE_FIELD_NAME, ccRasterGrid::INVALID_PROJECTION_TYPE, LAYER_RGB, LAYER_SF, cc2Point5DimEditor::m_rasterCloud, ccRasterGrid::PER_CELL_VALUE, ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::RemoveFromOwnDB(), cc2Point5DimEditor::update2DDisplayZoom(), and updateGrid().
Referenced by ccRasterizeTool().
updateGridInfo
void ccRasterizeTool::updateGridInfo () protected slot
Updates the gid info.
Definition at line 206 of file ecvRasterizeTool.cpp.
References cc2Point5DimEditor::getGridSizeAsString().
Referenced by ccRasterizeTool(), projectionDirChanged(), and showGridBoxEditor().
Member Data Documentation
m_cloud
ccGenericPointCloud* ccRasterizeTool::m_cloud protected
Associated cloud.
Definition at line 181 of file ecvRasterizeTool.h.
Referenced by activeLayerChanged(), addNewContour(), ccRasterizeTool(), convertGridToCloud(), exportContourLines(), generateCloud(), generateMesh(), generateRaster(), and updateGrid().
m_contourLines
std::vector<ccPolyline*> ccRasterizeTool::m_contourLines protected
Contour lines.
Definition at line 184 of file ecvRasterizeTool.h.
Referenced by addNewContour(), canClose(), exportContourLines(), generateContours(), and removeContourLines().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvRasterizeTool.h
/root/ACloudViewer/app/ecvRasterizeTool.cpp