ACloudViewer: cvCustomAxisHandleRepresentation Class Reference
cvCustomAxisHandleRepresentation Class Reference
Handle representation with custom translation axis support.
#include <cvCustomAxisHandleRepresentation.h>
Public Member Functions
vtkTypeMacro (cvCustomAxisHandleRepresentation, vtkPointHandleRepresentation3D)
void PrintSelf (ostream &os, vtkIndent indent) override
void SetCustomTranslationAxisOn ()
Enable custom translation axis mode.
void SetCustomTranslationAxisOff ()
Disable custom translation axis mode.
void SetCustomTranslationAxis (double axis[3])
Set the custom translation axis vector.
void SetCustomTranslationAxis (double x, double y, double z)
vtkGetVector3Macro (CustomTranslationAxis, double)
Get the custom translation axis.
bool IsCustomAxisEnabled () const
Check if custom translation axis is enabled.
void GetTranslationVector (const double *p1, const double *p2, double *v) const override
Override GetTranslationVector to support custom axis.
void Translate (const double *p1, const double *p2) override
Override Translate to support custom axis.
void Translate (const double *v) override
Static Public Member Functions
static cvCustomAxisHandleRepresentation * New ()
Protected Member Functions
cvCustomAxisHandleRepresentation ()
~cvCustomAxisHandleRepresentation () override
Protected Attributes
bool CustomAxisEnabled
double CustomTranslationAxis [3]
Detailed Description
Handle representation with custom translation axis support.
This class extends vtkPointHandleRepresentation3D to add support for custom translation axes, which is available in VTK 9.3+ but not in earlier versions. It follows ParaView's implementation approach.
Definition at line 24 of file cvCustomAxisHandleRepresentation.h.
Constructor & Destructor Documentation
cvCustomAxisHandleRepresentation()
cvCustomAxisHandleRepresentation::cvCustomAxisHandleRepresentation () protected
Definition at line 19 of file cvCustomAxisHandleRepresentation.cpp.
References CustomTranslationAxis.
~cvCustomAxisHandleRepresentation()
cvCustomAxisHandleRepresentation::~cvCustomAxisHandleRepresentation () override protected default
Member Function Documentation
GetTranslationVector()
void cvCustomAxisHandleRepresentation::GetTranslationVector (const double * p1, const double * p2, double * v) const override
Override GetTranslationVector to support custom axis.
Definition at line 74 of file cvCustomAxisHandleRepresentation.cpp.
References CustomAxisEnabled, and CustomTranslationAxis.
Referenced by Translate().
IsCustomAxisEnabled()
bool cvCustomAxisHandleRepresentation::IsCustomAxisEnabled () const inline
Check if custom translation axis is enabled.
Definition at line 61 of file cvCustomAxisHandleRepresentation.h.
References CustomAxisEnabled.
New()
static cvCustomAxisHandleRepresentation* cvCustomAxisHandleRepresentation::New () static
PrintSelf()
void cvCustomAxisHandleRepresentation::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 138 of file cvCustomAxisHandleRepresentation.cpp.
References CustomAxisEnabled, and CustomTranslationAxis.
SetCustomTranslationAxis() [1/2]
void cvCustomAxisHandleRepresentation::SetCustomTranslationAxis (double axis[3])
Set the custom translation axis vector.
Parameters
axis The axis vector (will be normalized internally)
Definition at line 48 of file cvCustomAxisHandleRepresentation.cpp.
References CustomTranslationAxis.
Referenced by SetCustomTranslationAxis().
SetCustomTranslationAxis() [2/2]
void cvCustomAxisHandleRepresentation::SetCustomTranslationAxis (double x, double y, double z)
Definition at line 66 of file cvCustomAxisHandleRepresentation.cpp.
References SetCustomTranslationAxis(), x, y, and z.
SetCustomTranslationAxisOff()
void cvCustomAxisHandleRepresentation::SetCustomTranslationAxisOff ()
Disable custom translation axis mode.
Definition at line 40 of file cvCustomAxisHandleRepresentation.cpp.
References CustomAxisEnabled.
Referenced by cvConstrainedDistanceWidget::ProcessKeyEvents().
SetCustomTranslationAxisOn()
void cvCustomAxisHandleRepresentation::SetCustomTranslationAxisOn ()
Enable custom translation axis mode.
Definition at line 30 of file cvCustomAxisHandleRepresentation.cpp.
References CustomAxisEnabled.
Referenced by cvConstrainedDistanceWidget::ProcessKeyEvents().
Translate() [1/2]
void cvCustomAxisHandleRepresentation::Translate (const double * p1, const double * p2) override
Override Translate to support custom axis.
Definition at line 109 of file cvCustomAxisHandleRepresentation.cpp.
References GetTranslationVector().
Translate() [2/2]
void cvCustomAxisHandleRepresentation::Translate (const double * v) override
Definition at line 117 of file cvCustomAxisHandleRepresentation.cpp.
References CustomAxisEnabled, and CustomTranslationAxis.
vtkGetVector3Macro()
cvCustomAxisHandleRepresentation::vtkGetVector3Macro (CustomTranslationAxis , double)
Get the custom translation axis.
vtkTypeMacro()
cvCustomAxisHandleRepresentation::vtkTypeMacro (cvCustomAxisHandleRepresentation , vtkPointHandleRepresentation3D)
Member Data Documentation
CustomAxisEnabled
bool cvCustomAxisHandleRepresentation::CustomAxisEnabled protected
Definition at line 80 of file cvCustomAxisHandleRepresentation.h.
Referenced by GetTranslationVector(), IsCustomAxisEnabled(), PrintSelf(), SetCustomTranslationAxisOff(), SetCustomTranslationAxisOn(), and Translate().
CustomTranslationAxis
double cvCustomAxisHandleRepresentation::CustomTranslationAxis[3] protected
Definition at line 81 of file cvCustomAxisHandleRepresentation.h.
Referenced by cvCustomAxisHandleRepresentation(), GetTranslationVector(), PrintSelf(), SetCustomTranslationAxis(), and Translate().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/ConstrainedWidgets/cvCustomAxisHandleRepresentation.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/ConstrainedWidgets/cvCustomAxisHandleRepresentation.cpp