ACloudViewer: colmap::ReconstructionManager Class Reference
colmap::ReconstructionManager Class Reference
#include <reconstruction_manager.h>
Public Member Functions
ReconstructionManager ()
ReconstructionManager (ReconstructionManager &&other)
ReconstructionManager & operator= (ReconstructionManager &&other)
size_t Size () const
const Reconstruction & Get (const size_t idx) const
Reconstruction & Get (const size_t idx)
size_t Add ()
void Delete (const size_t idx)
void Clear ()
size_t Read (const std::string &path)
void Write (const std::string &path, const OptionManager *options) const
Detailed Description
Definition at line 16 of file reconstruction_manager.h.
Constructor & Destructor Documentation
ReconstructionManager() [1/2]
colmap::ReconstructionManager::ReconstructionManager ()
Definition at line 39 of file reconstruction_manager.cc.
ReconstructionManager() [2/2]
colmap::ReconstructionManager::ReconstructionManager (ReconstructionManager && other)
Definition at line 41 of file reconstruction_manager.cc.
Member Function Documentation
Add()
size_t colmap::ReconstructionManager::Add ()
Definition at line 64 of file reconstruction_manager.cc.
References Size().
Referenced by BOOST_AUTO_TEST_CASE(), and Read().
Clear()
void colmap::ReconstructionManager::Clear ()
Definition at line 75 of file reconstruction_manager.cc.
Referenced by BOOST_AUTO_TEST_CASE(), cloudViewer::AutomaticReconstructionWidget::Run(), and colmap::AutomaticReconstructionWidget::Run().
Delete()
void colmap::ReconstructionManager::Delete (const size_t idx)
Definition at line 70 of file reconstruction_manager.cc.
Referenced by BOOST_AUTO_TEST_CASE().
Get() [1/2]
Reconstruction & colmap::ReconstructionManager::Get (const size_t idx)
Definition at line 60 of file reconstruction_manager.cc.
Get() [2/2]
const Reconstruction & colmap::ReconstructionManager::Get (const size_t idx) const
Definition at line 56 of file reconstruction_manager.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::AutomaticReconstructionController::RunDenseMapper(), colmap::RunMapper(), cloudViewer::ReconstructionManagerWidget::Update(), and colmap::ReconstructionManagerWidget::Update().
operator=()
ReconstructionManager & colmap::ReconstructionManager::operator= (ReconstructionManager && other)
Definition at line 46 of file reconstruction_manager.cc.
Read()
size_t colmap::ReconstructionManager::Read (const std::string & path)
Definition at line 77 of file reconstruction_manager.cc.
References Add(), and cloudViewer::t::geometry::path.
Referenced by cloudViewer::ReconstructionWidget::ImportReconstruction(), colmap::MainWindow::ImportReconstruction(), and colmap::RunMapper().
Size()
size_t colmap::ReconstructionManager::Size () const
Definition at line 54 of file reconstruction_manager.cc.
Referenced by Add(), BOOST_AUTO_TEST_CASE(), colmap::AutomaticReconstructionController::RunDenseMapper(), colmap::RunHierarchicalMapper(), colmap::RunMapper(), cloudViewer::ReconstructionManagerWidget::SelectedReconstructionIdx(), colmap::ReconstructionManagerWidget::SelectedReconstructionIdx(), cloudViewer::ReconstructionManagerWidget::SelectReconstruction(), colmap::ReconstructionManagerWidget::SelectReconstruction(), cloudViewer::ReconstructionManagerWidget::Update(), and colmap::ReconstructionManagerWidget::Update().
Write()
void colmap::ReconstructionManager::Write (const std::string & path, const OptionManager * options) const
Definition at line 83 of file reconstruction_manager.cc.
References colmap::CreateDirIfNotExists(), colmap::JoinPaths(), cloudViewer::core::make_pair(), cloudViewer::t::geometry::path, patch::to_string(), and colmap::OptionManager::Write().
Referenced by colmap::RunHierarchicalMapper().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/reconstruction_manager.h
/root/ACloudViewer/libs/Reconstruction/src/base/reconstruction_manager.cc