ACloudViewer: cloudViewer::visualization::rendering::View Class Reference
cloudViewer::visualization::rendering::View Class Reference abstract
#include <View.h>
Public Types
enum class TargetBuffers : std::uint8_t {
None = 0u , Color = 1u , Depth = 2u , Stencil = 4u ,
ColorAndDepth = Color | Depth , ColorAndStencil = Color | Stencil , DepthAndStencil = Depth | Stencil , All = Color | Depth | Stencil
}
enum class Mode : std::uint8_t {
Color = 0u , Depth , Normals , ColorMapX ,
ColorMapY , ColorMapZ
}
enum class ShadowType : std::uint8_t { kPCF , kVSM }
Public Member Functions
virtual ~View ()
virtual void SetDiscardBuffers (const TargetBuffers &buffers)=0
virtual Mode GetMode () const =0
virtual void SetMode (Mode mode)=0
virtual void SetWireframe (bool enable)=0
virtual void SetSampleCount (int n)=0
virtual int GetSampleCount () const =0
virtual void SetViewport (std::int32_t x, std::int32_t y, std::uint32_t w, std::uint32_t h)=0
virtual std::array< int, 4 > GetViewport () const =0
virtual void SetPostProcessing (bool enabled)=0
virtual void SetAmbientOcclusion (bool enabled, bool ssct_enabled=false)=0
virtual void SetBloom (bool enabled, float strength=0.5f, int spread=6)=0
virtual void SetAntiAliasing (bool enabled, bool temporal=false)=0
virtual void SetShadowing (bool enabled, ShadowType type)=0
virtual void SetColorGrading (const ColorGradingParams &color_grading)=0
virtual void ConfigureForColorPicking ()=0
virtual void EnableViewCaching (bool enable)=0
virtual bool IsCached () const =0
virtual TextureHandle GetColorBuffer ()=0
virtual Camera * GetCamera () const =0
Detailed Description
Definition at line 24 of file View.h.
Member Enumeration Documentation
Mode
enum cloudViewer::visualization::rendering::View::Mode : std::uint8_t strong
Enumerator
Color
Depth
Normals
ColorMapX
ColorMapY
ColorMapZ
Definition at line 38 of file View.h.
ShadowType
enum cloudViewer::visualization::rendering::View::ShadowType : std::uint8_t strong
Enumerator
kPCF
kVSM
Definition at line 48 of file View.h.
TargetBuffers
enum cloudViewer::visualization::rendering::View::TargetBuffers : std::uint8_t strong
Enumerator
None
Color
Depth
Stencil
ColorAndDepth
ColorAndStencil
DepthAndStencil
All
Definition at line 26 of file View.h.
Constructor & Destructor Documentation
~View()
virtual cloudViewer::visualization::rendering::View::~View () inline virtual
Definition at line 53 of file View.h.
Member Function Documentation
ConfigureForColorPicking()
virtual void cloudViewer::visualization::rendering::View::ConfigureForColorPicking () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
EnableViewCaching()
virtual void cloudViewer::visualization::rendering::View::EnableViewCaching (bool enable) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
GetCamera()
virtual Camera* cloudViewer::visualization::rendering::View::GetCamera () const pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
Referenced by cloudViewer::visualization::rendering::CloudViewerScene::GetCamera(), and cloudViewer::visualization::rendering::Renderer::RenderToDepthImage().
GetColorBuffer()
virtual TextureHandle cloudViewer::visualization::rendering::View::GetColorBuffer () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
GetMode()
virtual Mode cloudViewer::visualization::rendering::View::GetMode () const pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
GetSampleCount()
virtual int cloudViewer::visualization::rendering::View::GetSampleCount () const pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
GetViewport()
virtual std::array<int, 4> cloudViewer::visualization::rendering::View::GetViewport () const pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
Referenced by cloudViewer::visualization::rendering::Renderer::RenderToDepthImage(), and cloudViewer::visualization::rendering::Renderer::RenderToImage().
IsCached()
virtual bool cloudViewer::visualization::rendering::View::IsCached () const pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
SetAmbientOcclusion()
virtual void cloudViewer::visualization::rendering::View::SetAmbientOcclusion (bool enabled, bool ssct_enabled = false) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
SetAntiAliasing()
virtual void cloudViewer::visualization::rendering::View::SetAntiAliasing (bool enabled, bool temporal = false) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
SetBloom()
virtual void cloudViewer::visualization::rendering::View::SetBloom (bool enabled, float strength = 0.5f, int spread = 6) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
SetColorGrading()
virtual void cloudViewer::visualization::rendering::View::SetColorGrading (const ColorGradingParams & color_grading) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
SetDiscardBuffers()
virtual void cloudViewer::visualization::rendering::View::SetDiscardBuffers (const TargetBuffers & buffers) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
SetMode()
virtual void cloudViewer::visualization::rendering::View::SetMode (Mode mode) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
SetPostProcessing()
virtual void cloudViewer::visualization::rendering::View::SetPostProcessing (bool enabled) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
SetSampleCount()
virtual void cloudViewer::visualization::rendering::View::SetSampleCount (int n) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
SetShadowing()
virtual void cloudViewer::visualization::rendering::View::SetShadowing (bool enabled, ShadowType type) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
SetViewport()
virtual void cloudViewer::visualization::rendering::View::SetViewport (std::int32_t x, std::int32_t y, std::uint32_t w, std::uint32_t h) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
Referenced by cloudViewer::visualization::gui::Application::RenderToDepthImage(), and cloudViewer::visualization::gui::Application::RenderToImage().
SetWireframe()
virtual void cloudViewer::visualization::rendering::View::SetWireframe (bool enable) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentView.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/View.h