ACloudViewer: cloudViewer::utility::VerbosityContextManager Class Reference
cloudViewer::utility::VerbosityContextManager Class Reference
#include <Logging.h>
Public Member Functions
VerbosityContextManager (VerbosityLevel level)
void Enter ()
void Exit ()
Detailed Description
Definition at line 293 of file Logging.h.
Constructor & Destructor Documentation
VerbosityContextManager()
cloudViewer::utility::VerbosityContextManager::VerbosityContextManager (VerbosityLevel level) inline
Definition at line 295 of file Logging.h.
Member Function Documentation
Enter()
void cloudViewer::utility::VerbosityContextManager::Enter () inline
Definition at line 297 of file Logging.h.
References cloudViewer::utility::Logger::GetInstance(), cloudViewer::utility::Logger::GetVerbosityLevel(), and cloudViewer::utility::Logger::SetVerbosityLevel().
Exit()
void cloudViewer::utility::VerbosityContextManager::Exit () inline
Definition at line 302 of file Logging.h.
References cloudViewer::utility::Logger::GetInstance(), and cloudViewer::utility::Logger::SetVerbosityLevel().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/Logging.h