ACloudViewer: LiteWindow Class Reference
LiteWindow Class Reference
#include <LiteWindow.h>
Public Member Functions
LiteWindow ()
virtual ~LiteWindow ()
int IsValid ()
void MakeCurrent ()
void Create (int x=-1, int y=-1, const char *display=NULL)
Detailed Description
Definition at line 4 of file LiteWindow.h.
Constructor & Destructor Documentation
LiteWindow()
LiteWindow::LiteWindow () inline
Definition at line 6 of file LiteWindow.h.
~LiteWindow()
virtual LiteWindow::~LiteWindow () inline virtual
Definition at line 7 of file LiteWindow.h.
Member Function Documentation
Create()
void LiteWindow::Create (int x = -1, int y = -1, const char * display = NULL) inline
Definition at line 10 of file LiteWindow.h.
Referenced by GlobalUtil::CreateWindowEZ().
IsValid()
int LiteWindow::IsValid () inline
Definition at line 8 of file LiteWindow.h.
Referenced by GlobalUtil::CreateWindowEZ().
MakeCurrent()
void LiteWindow::MakeCurrent () inline
Definition at line 9 of file LiteWindow.h.
Referenced by GlobalUtil::CreateWindowEZ().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/LiteWindow.h