ACloudViewer: VtkUtils::AngleWidgetObserver Class Reference
VtkUtils::AngleWidgetObserver Class Reference
#include <anglewidgetobserver.h>
Signals
void angleChanged (double angle)
void worldPoint1Changed (double *pos)
void worldPoint2Changed (double *pos)
void worldCenterChanged (double *pos)
void displayPoint1Changed (double *pos)
void displayPoint2Changed (double *pos)
void displayCenterChanged (double *pos)
Public Member Functions
AngleWidgetObserver (QObject *parent=nullptr)
Public Member Functions inherited from VtkUtils::AbstractWidgetObserver
AbstractWidgetObserver (QObject *parent=0)
virtual ~AbstractWidgetObserver ()
void attach (vtkInteractorObserver *widget)
Protected Member Functions
void Execute (vtkObject *caller, unsigned long eventId, void *callData)
Additional Inherited Members
Protected Attributes inherited from VtkUtils::AbstractWidgetObserver
vtkInteractorObserver * m_widget = nullptr
Detailed Description
Definition at line 14 of file anglewidgetobserver.h.
Constructor & Destructor Documentation
AngleWidgetObserver()
VtkUtils::AngleWidgetObserver::AngleWidgetObserver (QObject * parent = nullptr) explicit
Definition at line 20 of file anglewidgetobserver.cpp.
Member Function Documentation
angleChanged
void VtkUtils::AngleWidgetObserver::angleChanged (double angle) signal
Referenced by Execute().
displayCenterChanged
void VtkUtils::AngleWidgetObserver::displayCenterChanged (double * pos) signal
Referenced by Execute().
displayPoint1Changed
void VtkUtils::AngleWidgetObserver::displayPoint1Changed (double * pos) signal
Referenced by Execute().
displayPoint2Changed
void VtkUtils::AngleWidgetObserver::displayPoint2Changed (double * pos) signal
Referenced by Execute().
Execute()
void VtkUtils::AngleWidgetObserver::Execute (vtkObject * caller, unsigned long eventId, void * callData) protected virtual
Implements VtkUtils::AbstractWidgetObserver.
Definition at line 23 of file anglewidgetobserver.cpp.
References angleChanged(), displayCenterChanged(), displayPoint1Changed(), displayPoint2Changed(), CVLog::Warning(), worldCenterChanged(), worldPoint1Changed(), and worldPoint2Changed().
worldCenterChanged
void VtkUtils::AngleWidgetObserver::worldCenterChanged (double * pos) signal
Referenced by Execute().
worldPoint1Changed
void VtkUtils::AngleWidgetObserver::worldPoint1Changed (double * pos) signal
Referenced by Execute().
worldPoint2Changed
void VtkUtils::AngleWidgetObserver::worldPoint2Changed (double * pos) signal
Referenced by Execute().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/anglewidgetobserver.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/anglewidgetobserver.cpp