ACloudViewer: ccPlanarEntityInterface Class Reference
ccPlanarEntityInterface Class Reference abstract
Interface for a planar entity.
#include <ecvPlanarEntityInterface.h>
Public Member Functions
ccPlanarEntityInterface ()
Default constructor.
ccPlanarEntityInterface (unsigned int id)
void showNormalVector (bool state)
Show normal vector.
bool normalVectorIsShown () const
Whether normal vector is shown or not.
virtual CCVector3 getNormal () const =0
Returns the entity normal.
void glDrawNormal (CC_DRAW_CONTEXT &context, const CCVector3 &pos, float scale, const ecvColor::Rgb *color=0)
Draws a normal vector (OpenGL)
void clearNormalVector (CC_DRAW_CONTEXT &context)
Protected Attributes
bool m_showNormalVector
Whether the facet normal vector should be displayed or not.
unsigned int m_uniqueId
QString m_bodyId
QString m_headId
Detailed Description
Interface for a planar entity.
Definition at line 18 of file ecvPlanarEntityInterface.h.
Constructor & Destructor Documentation
ccPlanarEntityInterface() [1/2]
ccPlanarEntityInterface::ccPlanarEntityInterface ()
Default constructor.
ccPlanarEntityInterface() [2/2]
ccPlanarEntityInterface::ccPlanarEntityInterface (unsigned int id)
Member Function Documentation
clearNormalVector()
void ccPlanarEntityInterface::clearNormalVector (CC_DRAW_CONTEXT & context)
getNormal()
virtual CCVector3 ccPlanarEntityInterface::getNormal () const pure virtual
Returns the entity normal.
Implemented in ccPlane, and ccFacet.
Referenced by define_ccPlane().
glDrawNormal()
void ccPlanarEntityInterface::glDrawNormal (CC_DRAW_CONTEXT & context, const CCVector3 & pos, float scale, const ecvColor::Rgb * color = 0)
Draws a normal vector (OpenGL)
normalVectorIsShown()
bool ccPlanarEntityInterface::normalVectorIsShown () const inline
Whether normal vector is shown or not.
Definition at line 27 of file ecvPlanarEntityInterface.h.
References m_showNormalVector.
Referenced by define_ccPlane().
showNormalVector()
void ccPlanarEntityInterface::showNormalVector (bool state) inline
Show normal vector.
Definition at line 25 of file ecvPlanarEntityInterface.h.
References m_showNormalVector.
Referenced by ccFitPlane::ccFitPlane(), qFacets::createFacets(), define_ccPlane(), RDBFilter::loadFile(), and ccCompass::recurseNormals().
Member Data Documentation
m_bodyId
QString ccPlanarEntityInterface::m_bodyId protected
Definition at line 45 of file ecvPlanarEntityInterface.h.
m_headId
QString ccPlanarEntityInterface::m_headId protected
Definition at line 46 of file ecvPlanarEntityInterface.h.
m_showNormalVector
bool ccPlanarEntityInterface::m_showNormalVector protected
Whether the facet normal vector should be displayed or not.
Definition at line 42 of file ecvPlanarEntityInterface.h.
Referenced by normalVectorIsShown(), and showNormalVector().
m_uniqueId
unsigned int ccPlanarEntityInterface::m_uniqueId protected
Definition at line 43 of file ecvPlanarEntityInterface.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvPlanarEntityInterface.h