ACloudViewer: cloudViewer::FeatureImageViewerWidget Class Reference
cloudViewer::FeatureImageViewerWidget Class Reference
#include <ImageViewerWidget.h>
Public Member Functions
FeatureImageViewerWidget (QWidget *parent, const std::string &switch_text)
void ReadAndShowWithKeypoints (const std::string &path, const colmap::FeatureKeypoints &keypoints, const std::vector< char > &tri_mask)
void ReadAndShowWithMatches (const std::string &path1, const std::string &path2, const colmap::FeatureKeypoints &keypoints1, const colmap::FeatureKeypoints &keypoints2, const colmap::FeatureMatches &matches)
Public Member Functions inherited from cloudViewer::ImageViewerWidget
ImageViewerWidget (QWidget *parent)
void ShowBitmap (const colmap::Bitmap &bitmap)
void ShowPixmap (const QPixmap &pixmap)
void ReadAndShow (const std::string &path)
Protected Member Functions
void ShowOrHide ()
Protected Member Functions inherited from cloudViewer::ImageViewerWidget
void resizeEvent (QResizeEvent *event)
void closeEvent (QCloseEvent *event)
void ZoomIn ()
void ZoomOut ()
void Save ()
Protected Attributes
QPixmap image1_
QPixmap image2_
bool switch_state_
QPushButton * switch_button_
const std::string switch_text_
Protected Attributes inherited from cloudViewer::ImageViewerWidget
QGridLayout * grid_layout_
QHBoxLayout * button_layout_
Detailed Description
Definition at line 61 of file ImageViewerWidget.h.
Constructor & Destructor Documentation
FeatureImageViewerWidget()
cloudViewer::FeatureImageViewerWidget::FeatureImageViewerWidget (QWidget * parent, const std::string & switch_text)
Definition at line 140 of file ImageViewerWidget.cpp.
References cloudViewer::ImageViewerWidget::button_layout_, ShowOrHide(), switch_button_, and switch_text_.
Member Function Documentation
ReadAndShowWithKeypoints()
void cloudViewer::FeatureImageViewerWidget::ReadAndShowWithKeypoints (const std::string & path, const colmap::FeatureKeypoints & keypoints, const std::vector< char > & tri_mask)
Definition at line 153 of file ImageViewerWidget.cpp.
References QtCompat::endl(), image1_, image2_, ecvColor::magenta(), cloudViewer::t::geometry::path, ecvColor::red(), cloudViewer::ImageViewerWidget::ShowPixmap(), and switch_state_.
Referenced by cloudViewer::DatabaseImageViewerWidget::ShowImageWithId().
ReadAndShowWithMatches()
void cloudViewer::FeatureImageViewerWidget::ReadAndShowWithMatches (const std::string & path1, const std::string & path2, const colmap::FeatureKeypoints & keypoints1, const colmap::FeatureKeypoints & keypoints2, const colmap::FeatureMatches & matches)
Definition at line 193 of file ImageViewerWidget.cpp.
References QtCompat::endl(), image1_, image2_, cloudViewer::ImageViewerWidget::ShowPixmap(), and switch_state_.
ShowOrHide()
void cloudViewer::FeatureImageViewerWidget::ShowOrHide () protected
Definition at line 220 of file ImageViewerWidget.cpp.
References image1_, image2_, cloudViewer::ImageViewerWidget::ShowPixmap(), switch_button_, switch_state_, and switch_text_.
Referenced by FeatureImageViewerWidget().
Member Data Documentation
image1_
QPixmap cloudViewer::FeatureImageViewerWidget::image1_ protected
Definition at line 78 of file ImageViewerWidget.h.
Referenced by ReadAndShowWithKeypoints(), ReadAndShowWithMatches(), and ShowOrHide().
image2_
QPixmap cloudViewer::FeatureImageViewerWidget::image2_ protected
Definition at line 79 of file ImageViewerWidget.h.
Referenced by ReadAndShowWithKeypoints(), ReadAndShowWithMatches(), and ShowOrHide().
switch_button_
QPushButton* cloudViewer::FeatureImageViewerWidget::switch_button_ protected
Definition at line 81 of file ImageViewerWidget.h.
Referenced by FeatureImageViewerWidget(), and ShowOrHide().
switch_state_
bool cloudViewer::FeatureImageViewerWidget::switch_state_ protected
Definition at line 80 of file ImageViewerWidget.h.
Referenced by ReadAndShowWithKeypoints(), ReadAndShowWithMatches(), and ShowOrHide().
switch_text_
const std::string cloudViewer::FeatureImageViewerWidget::switch_text_ protected
Definition at line 82 of file ImageViewerWidget.h.
Referenced by FeatureImageViewerWidget(), and ShowOrHide().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/reconstruction/ImageViewerWidget.h
/root/ACloudViewer/app/reconstruction/ImageViewerWidget.cpp