ACloudViewer: colmap::MinSTGraphCut< node_t, value_t > Class Template Reference
colmap::MinSTGraphCut< node_t, value_t > Class Template Reference
#include <graph_cut.h>
Classes
struct Edge
Public Types
typedef boost::adjacency_list_traits< boost::vecS, boost::vecS, boost::directedS > graph_traits_t
typedef graph_traits_t::edge_descriptor edge_descriptor_t
typedef graph_traits_t::vertices_size_type vertices_size_t
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, size_t, Edge > graph_t
Public Member Functions
MinSTGraphCut (const size_t num_nodes)
size_t NumNodes () const
size_t NumEdges () const
void AddNode (const node_t node_idx, const value_t source_capacity, const value_t sink_capacity)
void AddEdge (const node_t node_idx1, const node_t node_idx2, const value_t capacity, const value_t reverse_capacity)
value_t Compute ()
bool IsConnectedToSource (const node_t node_idx) const
bool IsConnectedToSink (const node_t node_idx) const
Detailed Description
template<typename node_t, typename value_t>
class colmap::MinSTGraphCut< node_t, value_t >
Definition at line 40 of file graph_cut.h.
Member Typedef Documentation
edge_descriptor_t
template<typename node_t , typename value_t > typedef graph_traits_t::edge_descriptor colmap::MinSTGraphCut< node_t, value_t >::edge_descriptor_t
Definition at line 45 of file graph_cut.h.
graph_t
template<typename node_t , typename value_t > typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, size_t, Edge> colmap::MinSTGraphCut< node_t, value_t >::graph_t
Definition at line 59 of file graph_cut.h.
graph_traits_t
template<typename node_t , typename value_t > typedef boost:: adjacency_list_traits<boost::vecS, boost::vecS, boost::directedS> colmap::MinSTGraphCut< node_t, value_t >::graph_traits_t
Definition at line 44 of file graph_cut.h.
vertices_size_t
template<typename node_t , typename value_t > typedef graph_traits_t::vertices_size_type colmap::MinSTGraphCut< node_t, value_t >::vertices_size_t
Definition at line 46 of file graph_cut.h.
Constructor & Destructor Documentation
MinSTGraphCut()
template<typename node_t , typename value_t > colmap::MinSTGraphCut< node_t, value_t >::MinSTGraphCut (const size_t num_nodes)
Definition at line 98 of file graph_cut.h.
Member Function Documentation
AddEdge()
template<typename node_t , typename value_t > void colmap::MinSTGraphCut< node_t, value_t >::AddEdge (const node_t node_idx1, const node_t node_idx2, const value_t capacity, const value_t reverse_capacity)
Definition at line 142 of file graph_cut.h.
Referenced by BOOST_AUTO_TEST_CASE().
AddNode()
template<typename node_t , typename value_t > void colmap::MinSTGraphCut< node_t, value_t >::AddNode (const node_t node_idx, const value_t source_capacity, const value_t sink_capacity)
Definition at line 112 of file graph_cut.h.
Referenced by BOOST_AUTO_TEST_CASE().
Compute()
template<typename node_t , typename value_t > value_t colmap::MinSTGraphCut< node_t, value_t >::Compute
Definition at line 164 of file graph_cut.h.
References vertex_index.
Referenced by BOOST_AUTO_TEST_CASE().
IsConnectedToSink()
template<typename node_t , typename value_t > bool colmap::MinSTGraphCut< node_t, value_t >::IsConnectedToSink (const node_t node_idx) const
Definition at line 186 of file graph_cut.h.
Referenced by BOOST_AUTO_TEST_CASE().
IsConnectedToSource()
template<typename node_t , typename value_t > bool colmap::MinSTGraphCut< node_t, value_t >::IsConnectedToSource (const node_t node_idx) const
Definition at line 180 of file graph_cut.h.
Referenced by BOOST_AUTO_TEST_CASE().
NumEdges()
template<typename node_t , typename value_t > size_t colmap::MinSTGraphCut< node_t, value_t >::NumEdges
Definition at line 107 of file graph_cut.h.
Referenced by BOOST_AUTO_TEST_CASE().
NumNodes()
template<typename node_t , typename value_t > size_t colmap::MinSTGraphCut< node_t, value_t >::NumNodes
Definition at line 102 of file graph_cut.h.
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/base/graph_cut.h