ACloudViewer: cloudViewer::io::rpc::DummyMessageProcessor Class Reference
cloudViewer::io::rpc::DummyMessageProcessor Class Reference
#include <DummyMessageProcessor.h>
Public Member Functions
DummyMessageProcessor ()
std::shared_ptr< zmq::message_t > ProcessMessage (const messages::Request &req, const messages::SetMeshData &msg, const msgpack::object_handle &obj) override
std::shared_ptr< zmq::message_t > ProcessMessage (const messages::Request &req, const messages::GetMeshData &msg, const msgpack::object_handle &obj) override
std::shared_ptr< zmq::message_t > ProcessMessage (const messages::Request &req, const messages::SetCameraData &msg, const msgpack::object_handle &obj) override
std::shared_ptr< zmq::message_t > ProcessMessage (const messages::Request &req, const messages::SetProperties &msg, const msgpack::object_handle &obj) override
std::shared_ptr< zmq::message_t > ProcessMessage (const messages::Request &req, const messages::SetActiveCamera &msg, const msgpack::object_handle &obj) override
std::shared_ptr< zmq::message_t > ProcessMessage (const messages::Request &req, const messages::SetTime &msg, const msgpack::object_handle &obj) override
Public Member Functions inherited from cloudViewer::io::rpc::MessageProcessorBase
MessageProcessorBase ()
Constructs a receiver listening on the specified address.
virtual ~MessageProcessorBase ()
Detailed Description
Message processor implementation which always returns a successful status. This class is meant for testing puproses.
Definition at line 21 of file DummyMessageProcessor.h.
Constructor & Destructor Documentation
DummyMessageProcessor()
cloudViewer::io::rpc::DummyMessageProcessor::DummyMessageProcessor () inline
Definition at line 23 of file DummyMessageProcessor.h.
Member Function Documentation
ProcessMessage() [1/6]
std::shared_ptr<zmq::message_t> cloudViewer::io::rpc::DummyMessageProcessor::ProcessMessage (const messages::Request & req, const messages::GetMeshData & msg, const msgpack::object_handle & obj) inline override virtual
Reimplemented from cloudViewer::io::rpc::MessageProcessorBase.
Definition at line 31 of file DummyMessageProcessor.h.
References cloudViewer::io::rpc::CreateStatusOKMsg().
ProcessMessage() [2/6]
std::shared_ptr<zmq::message_t> cloudViewer::io::rpc::DummyMessageProcessor::ProcessMessage (const messages::Request & req, const messages::SetActiveCamera & msg, const msgpack::object_handle & obj) inline override virtual
Reimplemented from cloudViewer::io::rpc::MessageProcessorBase.
Definition at line 49 of file DummyMessageProcessor.h.
References cloudViewer::io::rpc::CreateStatusOKMsg().
ProcessMessage() [3/6]
std::shared_ptr<zmq::message_t> cloudViewer::io::rpc::DummyMessageProcessor::ProcessMessage (const messages::Request & req, const messages::SetCameraData & msg, const msgpack::object_handle & obj) inline override virtual
Reimplemented from cloudViewer::io::rpc::MessageProcessorBase.
Definition at line 37 of file DummyMessageProcessor.h.
References cloudViewer::io::rpc::CreateStatusOKMsg().
ProcessMessage() [4/6]
std::shared_ptr<zmq::message_t> cloudViewer::io::rpc::DummyMessageProcessor::ProcessMessage (const messages::Request & req, const messages::SetMeshData & msg, const msgpack::object_handle & obj) inline override virtual
Function for processing a msg.
Parameters
req The Request object that accompanies the msg object.
msg The message to be processed
obj The handle to the object from which the msg was unpacked. Can be used for custom unpacking.
Reimplemented from cloudViewer::io::rpc::MessageProcessorBase.
Definition at line 25 of file DummyMessageProcessor.h.
References cloudViewer::io::rpc::CreateStatusOKMsg().
ProcessMessage() [5/6]
std::shared_ptr<zmq::message_t> cloudViewer::io::rpc::DummyMessageProcessor::ProcessMessage (const messages::Request & req, const messages::SetProperties & msg, const msgpack::object_handle & obj) inline override virtual
Reimplemented from cloudViewer::io::rpc::MessageProcessorBase.
Definition at line 43 of file DummyMessageProcessor.h.
References cloudViewer::io::rpc::CreateStatusOKMsg().
ProcessMessage() [6/6]
std::shared_ptr<zmq::message_t> cloudViewer::io::rpc::DummyMessageProcessor::ProcessMessage (const messages::Request & req, const messages::SetTime & msg, const msgpack::object_handle & obj) inline override virtual
Reimplemented from cloudViewer::io::rpc::MessageProcessorBase.
Definition at line 55 of file DummyMessageProcessor.h.
References cloudViewer::io::rpc::CreateStatusOKMsg().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/io/rpc/DummyMessageProcessor.h