ACloudViewer: pcl2cc Class Reference
pcl2cc Class Reference
PCL to CC cloud converter.
#include <sm2cc.h>
Static Public Member Functions
static ccMesh * Convert (PCLTextureMesh::ConstPtr textureMesh)
Converts a PCL point cloud to a ccPointCloud.
static ccPointCloud * Convert (const PCLCloud &pclCloud, bool ignoreScalars=false, bool ignoreRgb=false)
static ccMesh * Convert (const PCLCloud &pclCloud, const std::vector< pcl::Vertices > &polygons, bool ignoreScalars=false, bool ignoreRgb=false)
static bool CopyXYZ (const PCLCloud &pclCloud, ccPointCloud &ccCloud, uint8_t coordinateType)
static bool CopyNormals (const PCLCloud &pclCloud, ccPointCloud &ccCloud)
static bool CopyRGB (const PCLCloud &pclCloud, ccPointCloud &ccCloud)
static bool CopyScalarField (const PCLCloud &pclCloud, const std::string &sfName, ccPointCloud &ccCloud, bool overwriteIfExist=true)
static void FromPCLMaterial (const PCLMaterial &inMaterial, ccMaterial::Shared &outMaterial)
Detailed Description
PCL to CC cloud converter.
Definition at line 25 of file sm2cc.h.
Member Function Documentation
Convert() [1/3]
ccPointCloud * pcl2cc::Convert (const PCLCloud & pclCloud, bool ignoreScalars = false, bool ignoreRgb = false) static
Definition at line 465 of file sm2cc.cpp.
References CopyNormals(), CopyRGB(), CopyScalarField(), CopyXYZ(), ExistField(), fields, and name.
Convert() [2/3]
ccMesh * pcl2cc::Convert (const PCLCloud & pclCloud, const std::vector< pcl::Vertices > & polygons, bool ignoreScalars = false, bool ignoreRgb = false) static
Definition at line 545 of file sm2cc.cpp.
References ccHObject::addChild(), ccMesh::addTriangle(), Convert(), ccMesh::getTriNormsTable(), normals, ccMesh::reserve(), ccObject::setEnabled(), ccObject::setLocked(), ccObject::setName(), ccMesh::shrinkToFit(), and ccPointCloud::shrinkToFit().
Convert() [3/3]
static ccMesh* pcl2cc::Convert (PCLTextureMesh::ConstPtr textureMesh) static
Converts a PCL point cloud to a ccPointCloud.
Referenced by ecvTools::AddPointCloud(), ExtractSIFT::compute(), GeneralFilters::compute(), MLSSmoothingUpsampling::compute(), ProjectionFilter::compute(), StatisticalOutliersRemover::compute(), CorrespondenceMatching::compute(), TemplateAlignment::compute(), MinimumCutSegmentation::compute(), RegionGrowingSegmentation::compute(), ConvexConcaveHullReconstruction::compute(), GreedyTriangulation::compute(), MarchingCubeReconstruction::compute(), NurbsCurveFitting::compute(), NurbsSurfaceReconstruction::compute(), PoissonReconstruction::compute(), Convert(), ecvTools::GetPolylines(), and PcdFilter::loadFile().
CopyNormals()
bool pcl2cc::CopyNormals (const PCLCloud & pclCloud, ccPointCloud & ccCloud) static
Definition at line 124 of file sm2cc.cpp.
References ccPointCloud::addNorm(), FROM_PCL_CLOUD, ccPointCloud::reserveTheNormsTable(), and ccDrawableObject::showNormals().
Referenced by NormalEstimation::compute(), and Convert().
CopyRGB()
bool pcl2cc::CopyRGB (const PCLCloud & pclCloud, ccPointCloud & ccCloud) static
Definition at line 150 of file sm2cc.cpp.
References ccPointCloud::addRGBColor(), FROM_PCL_CLOUD, ccPointCloud::reserveTheRGBTable(), and ccDrawableObject::showColors().
Referenced by Convert().
CopyScalarField()
bool pcl2cc::CopyScalarField (const PCLCloud & pclCloud, const std::string & sfName, ccPointCloud & ccCloud, bool overwriteIfExist = true) static
Definition at line 170 of file sm2cc.cpp.
References cloudViewer::ScalarField::addElement(), ccPointCloud::addScalarField(), ccScalarField::computeMinAndMax(), ccPointCloud::deleteScalarField(), FROM_PCL_CLOUD, cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), name, CCShareable::release(), cloudViewer::ScalarField::reserveSafe(), scalar, ccPointCloud::setCurrentDisplayedScalarField(), ccDrawableObject::showSF(), and CVLog::Warning().
Referenced by NormalEstimation::compute(), and Convert().
CopyXYZ()
bool pcl2cc::CopyXYZ (const PCLCloud & pclCloud, ccPointCloud & ccCloud, uint8_t coordinateType) static
Definition at line 88 of file sm2cc.cpp.
References ccPointCloud::reserve(), and CVLog::Warning().
Referenced by Convert().
FromPCLMaterial()
void pcl2cc::FromPCLMaterial (const PCLMaterial & inMaterial, ccMaterial::Shared & outMaterial) static
Definition at line 311 of file sm2cc.cpp.
References CVTools::ExtractDigitAlpha(), cloudViewer::utility::filesystem::GetFileParentDirectory(), image, ecvColor::night(), CVTools::ToNativeSeparators(), CVTools::ToQString(), and CVLog::Warning().
Referenced by PclUtils::renders::MeshTextureApplier::ApplyPBRTextures().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Utils/sm2cc.h
/root/ACloudViewer/libs/PCLEngine/Utils/sm2cc.cpp