ACloudViewer: fgr::CApp Class Reference
fgr::CApp Class Reference
#include <FastGlobalRegistration.h>
Public Member Functions
CApp (double div_factor=1.4, bool use_absolute_scale=false, double max_corr_dist=0.025, int iteration_number=64, float tuple_scale=0.95f, size_t tuple_max_cnt=1000)
void LoadFeature (const Points &pts, const Features &feat)
void NormalizePoints ()
void AdvancedMatching (bool crossCheck=true, bool tupleConstraint=true)
bool OptimizePairwise (bool decrease_mu=true)
Eigen::Matrix4f GetOutputTrans () const
Detailed Description
Definition at line 18 of file FastGlobalRegistration.h.
Constructor & Destructor Documentation
CApp()
fgr::CApp::CApp (double div_factor = 1.4, bool use_absolute_scale = false, double max_corr_dist = 0.025, int iteration_number = 64, float tuple_scale = 0.95f, size_t tuple_max_cnt = 1000) inline
Definition at line 20 of file FastGlobalRegistration.h.
Member Function Documentation
AdvancedMatching()
void CApp::AdvancedMatching (bool crossCheck = true, bool tupleConstraint = true)
BUILD FLANNTREE
INITIAL MATCHING
TUPLE CONSTRAINT
Definition at line 101 of file FastGlobalRegistration.cpp.
References AlignedIndex, BuildKDTree(), NULL, CVLog::Print(), ReferenceIndex, SearchKDTree(), Similar(), size, and std::swap().
Referenced by FastGlobalRegistrationFilter::compute().
GetOutputTrans()
Eigen::Matrix4f CApp::GetOutputTrans () const
Definition at line 382 of file FastGlobalRegistration.cpp.
References AlignedIndex, and ReferenceIndex.
Referenced by FastGlobalRegistrationFilter::compute().
LoadFeature()
void CApp::LoadFeature (const Points & pts, const Features & feat)
Definition at line 34 of file FastGlobalRegistration.cpp.
Referenced by FastGlobalRegistrationFilter::compute().
NormalizePoints()
void CApp::NormalizePoints ()
Definition at line 239 of file FastGlobalRegistration.cpp.
Referenced by FastGlobalRegistrationFilter::compute().
OptimizePairwise()
bool CApp::OptimizePairwise (bool decrease_mu = true)
Definition at line 289 of file FastGlobalRegistration.cpp.
References AlignedIndex, ReferenceIndex, result, and TransformPoints().
Referenced by FastGlobalRegistrationFilter::compute().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/FastGlobalRegistration.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/FastGlobalRegistration.cpp