ACloudViewer: CCShareable Class Reference
CCShareable Class Reference
#include <CVShareable.h>
Public Member Functions
CCShareable ()
Default constructor.
virtual void link ()
Increase counter.
virtual void release ()
Decrease counter and deletes object when 0.
virtual unsigned getLinkCount () const
Returns the current link count.
Protected Member Functions
virtual ~CCShareable ()
Destructor.
Protected Attributes
unsigned m_linkCount
Links counter.
Detailed Description
Definition at line 22 of file CVShareable.h.
Constructor & Destructor Documentation
CCShareable()
CCShareable::CCShareable ()
Default constructor.
Definition at line 27 of file CVShareable.cpp.
~CCShareable()
CCShareable::~CCShareable () protected virtual
Destructor.
private to avoid deletion with 'delete' operator
Definition at line 42 of file CVShareable.cpp.
References std::swap().
Member Function Documentation
getLinkCount()
virtual unsigned CCShareable::getLinkCount () const inline virtual
Returns the current link count.
Returns
current link count
Definition at line 40 of file CVShareable.h.
Referenced by define_CCShareable(), and ccPropertiesTreeDelegate::fillWithShareable().
link()
void CCShareable::link () virtual
Increase counter.
Should be called when this object is 'attached' to another one.
Definition at line 33 of file CVShareable.cpp.
References m_linkCount.
Referenced by ccPointCloud::addScalarField(), ccMesh::ccMesh(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), ccComparisonDlg::computeDistances(), ccMesh::createNewMeshFromSelection(), define_CCShareable(), qFacets::extractFacets(), ccHistogramWindow::fromSF(), ObjFilter::loadFile(), DRCFilter::loadFile(), PlyFilter::loadFile(), PrepareLASField(), ccMesh::reservePerTriangleMtlIndexes(), ccMesh::reservePerTriangleNormalIndexes(), ccMesh::reservePerTriangleTexCoordIndexes(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveTheRGBTable(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), ccMapWindow::setAssociatedScalarField(), ccMesh::setMaterialSet(), ccPointCloud::setNormsTable(), ccMesh::setTexCoordinatesTable(), ccMesh::setTriangleMtlIndexesTable(), and ccMesh::setTriNormsTable().
release()
void CCShareable::release () virtual
Decrease counter and deletes object when 0.
Should be called when this object is 'detached'.
Definition at line 35 of file CVShareable.cpp.
References m_linkCount.
Referenced by ccPointCloud::addEigenColors(), ccPointCloud::addEigenNorms(), cloudViewer::PointCloudTpl< T >::addScalarField(), ccPointCloud::addScalarField(), ccMesh::addTriangleNorm(), ccPointCloud::append(), masc::Classifier::classify(), ccArray< Type, N, ComponentType >::clone(), ccMaterialSet::clone(), NormsIndexesTableType::clone(), NormsTableType::clone(), ColorsTableType::clone(), RGBAColorsTableType::clone(), TextureCoordsContainer::clone(), qM3C2Process::Compute(), ccNormalVectors::ComputeCloudNormals(), ccComparisonDlg::computeDistances(), ccPointCloud::computeNormalsWithOctree(), ccMesh::computePerTriangleNormals(), cloudViewer::ScalarFieldTools::computeScalarFieldGradient(), DistanceMapGenerationTool::ConvertMapToCloud(), vtk2cc::ConvertToPointCloud(), pcl2cc::CopyScalarField(), copyScalarFields(), ccMesh::createNewMeshFromSelection(), define_CCShareable(), qPoissonRecon::doAction(), FromFbxMesh(), ccHistogramWindow::fromSF(), cloudViewer::AutoSegmentationTools::frontPropagationBasedSegmentation(), ccRasterizeTool::generateHillshade(), CSVMatrixFilter::loadFile(), ObjFilter::loadFile(), PTXFilter::loadFile(), VTKFilter::loadFile(), SimpleBinFilter::loadFile(), DRCFilter::loadFile(), PlyFilter::loadFile(), LoadScan(), masc::PointFeature::prepare(), prepareCloud(), PrepareLASField(), masc::Feature::PrepareSF(), ccMesh::removePerTriangleMtlIndexes(), ccMesh::removePerTriangleNormalIndexes(), ccMesh::removePerTriangleTexCoordIndexes(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveTheRGBTable(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), ccMapWindow::setAssociatedScalarField(), ccMesh::setMaterialSet(), ccPointCloud::setNormsTable(), ccMesh::setTexCoordinatesTable(), ccMesh::setTriangleMtlIndexesTable(), ccMesh::setTriNormsTable(), ccMesh::transformTriNormals(), ccPointCloud::unallocateColors(), ccPointCloud::unallocateNorms(), and ccMesh::~ccMesh().
Member Data Documentation
m_linkCount
unsigned CCShareable::m_linkCount protected
Links counter.
Definition at line 54 of file CVShareable.h.
Referenced by link(), and release().
The documentation for this class was generated from the following files:
/root/ACloudViewer/core/include/CVShareable.h
/root/ACloudViewer/core/src/CVShareable.cpp