ACloudViewer: cloudViewer::core::SlabNodeManagerImpl Class Reference
cloudViewer::core::SlabNodeManagerImpl Class Reference
#include <SlabNodeManager.h>
Public Member Functions
SlabNodeManagerImpl ()
__device__ __forceinline__ uint32_t * get_unit_ptr_from_slab (const buf_index_t &next_slab_ptr, const uint32_t &lane_id)
__device__ __forceinline__ uint32_t * get_ptr_for_bitmap (const uint32_t super_block_idx, const uint32_t bitmap_idx)
__device__ void Init (uint32_t &tid, uint32_t &lane_id)
__device__ uint32_t WarpAllocate (const uint32_t &lane_id)
__device__ void FreeUntouched (buf_index_t ptr)
Public Attributes
uint32_t * super_blocks_
A pointer to each super-block.
uint32_t hash_coef_
hash_coef (register): used as (16 bits, 16 bits) for hashing.
Detailed Description
Definition at line 48 of file SlabNodeManager.h.
Constructor & Destructor Documentation
SlabNodeManagerImpl()
cloudViewer::core::SlabNodeManagerImpl::SlabNodeManagerImpl () inline
Definition at line 50 of file SlabNodeManager.h.
Member Function Documentation
FreeUntouched()
__device__ void cloudViewer::core::SlabNodeManagerImpl::FreeUntouched (buf_index_t ptr) inline
Definition at line 134 of file SlabNodeManager.h.
References cloudViewer::core::kSlabsPerBlock, cloudViewer::core::kUIntsPerSuperBlock, and super_blocks_.
Referenced by cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::FreeSlab().
get_ptr_for_bitmap()
__device__ __forceinline__ uint32_t* cloudViewer::core::SlabNodeManagerImpl::get_ptr_for_bitmap (const uint32_t super_block_idx, const uint32_t bitmap_idx) inline
Definition at line 61 of file SlabNodeManager.h.
References cloudViewer::core::kUIntsPerSuperBlock, and super_blocks_.
get_unit_ptr_from_slab()
__device__ __forceinline__ uint32_t* cloudViewer::core::SlabNodeManagerImpl::get_unit_ptr_from_slab (const buf_index_t & next_slab_ptr, const uint32_t & lane_id) inline
Definition at line 57 of file SlabNodeManager.h.
References super_blocks_.
Referenced by cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::SlabEntryPtrFromNodes().
Init()
__device__ void cloudViewer::core::SlabNodeManagerImpl::Init (uint32_t & tid, uint32_t & lane_id) inline
Definition at line 68 of file SlabNodeManager.h.
References cloudViewer::core::kSlabsPerBlock, cloudViewer::core::kUIntsPerSuperBlock, and super_blocks_.
Referenced by cloudViewer::core::CountElemsPerBucketKernel(), cloudViewer::core::EraseKernelPass0(), cloudViewer::core::FindKernel(), cloudViewer::core::GetActiveIndicesKernel(), and cloudViewer::core::InsertKernelPass1().
WarpAllocate()
__device__ uint32_t cloudViewer::core::SlabNodeManagerImpl::WarpAllocate (const uint32_t & lane_id) inline
Definition at line 78 of file SlabNodeManager.h.
References cloudViewer::core::kBlockMaskBits, cloudViewer::core::kNotFoundFlag, cloudViewer::core::kSlabMaskBits, cloudViewer::core::kSlabsPerBlock, cloudViewer::core::kSuperBlockMaskBits, cloudViewer::core::kSyncLanesMask, cloudViewer::core::kUIntsPerSuperBlock, and super_blocks_.
Referenced by cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::AllocateSlab().
Member Data Documentation
hash_coef_
uint32_t cloudViewer::core::SlabNodeManagerImpl::hash_coef_
hash_coef (register): used as (16 bits, 16 bits) for hashing.
Definition at line 206 of file SlabNodeManager.h.
Referenced by cloudViewer::core::SlabNodeManager::SlabNodeManager().
super_blocks_
uint32_t* cloudViewer::core::SlabNodeManagerImpl::super_blocks_
A pointer to each super-block.
Definition at line 204 of file SlabNodeManager.h.
Referenced by FreeUntouched(), get_ptr_for_bitmap(), get_unit_ptr_from_slab(), Init(), cloudViewer::core::SlabNodeManager::Reset(), cloudViewer::core::SlabNodeManager::SlabNodeManager(), WarpAllocate(), and cloudViewer::core::SlabNodeManager::~SlabNodeManager().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/hashmap/CUDA/SlabNodeManager.h