ACloudViewer: cloudViewer::ml::op_util::Dim Class Reference
cloudViewer::ml::op_util::Dim Class Reference
Class for dimensions for which the value should be inferred.
#include <ShapeChecking.h>
Public Member Functions
Dim ()
Dim (const std::string &name)
Dim (int64_t value, const std::string &name="")
Dim (const Dim &other)
~Dim ()
Dim & operator= (const Dim &)=delete
int64_t & value ()
bool & constant ()
bool assign (int64_t a)
std::string ToString (bool show_value=true)
Detailed Description
Class for dimensions for which the value should be inferred.
Definition at line 50 of file ShapeChecking.h.
Constructor & Destructor Documentation
Dim() [1/4]
cloudViewer::ml::op_util::Dim::Dim () inline explicit
Definition at line 52 of file ShapeChecking.h.
Dim() [2/4]
cloudViewer::ml::op_util::Dim::Dim (const std::string & name) inline explicit
Definition at line 54 of file ShapeChecking.h.
Dim() [3/4]
cloudViewer::ml::op_util::Dim::Dim (int64_t value, const std::string & name = "") inline
Definition at line 57 of file ShapeChecking.h.
Dim() [4/4]
cloudViewer::ml::op_util::Dim::Dim (const Dim & other) inline
Definition at line 60 of file ShapeChecking.h.
~Dim()
cloudViewer::ml::op_util::Dim::~Dim () inline
Definition at line 66 of file ShapeChecking.h.
Member Function Documentation
assign()
bool cloudViewer::ml::op_util::Dim::assign (int64_t a) inline
tries to assign a value to the Dim if not marked as constant and compares the Dim value with the value to be assigned.
Definition at line 86 of file ShapeChecking.h.
References constant(), and value().
Referenced by cloudViewer::ml::op_util::operator==().
constant()
bool& cloudViewer::ml::op_util::Dim::constant () inline
Definition at line 77 of file ShapeChecking.h.
Referenced by assign(), cloudViewer::ml::op_util::GetValue(), and ToString().
operator=()
Dim& cloudViewer::ml::op_util::Dim::operator= (const Dim &) delete
ToString()
std::string cloudViewer::ml::op_util::Dim::ToString (bool show_value = true) inline
Definition at line 94 of file ShapeChecking.h.
References constant(), patch::to_string(), and value().
Referenced by cloudViewer::ml::op_util::GetString().
value()
int64_t& cloudViewer::ml::op_util::Dim::value () inline
Definition at line 70 of file ShapeChecking.h.
Referenced by assign(), cloudViewer::ml::op_util::GetValue(), and ToString().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/ml/ShapeChecking.h