ACloudViewer: ccMeasurementDevice Class Reference
ccMeasurementDevice Class Reference
#include <ccMeasurementDevice.h>
Public Member Functions
ccMeasurementDevice (ecvMainAppInterface *app)
ccPlane * fitPlaneToPoints (const std::vector< ccMPlanePoint > &fittingPoints, const QString &planeName) const
void createScalarFieldForCloud (const ccPlane *plane, ccPointCloud *cloud, bool signedMeasurement) const
void deleteScalarFieldFromCloud (ccPointCloud *cloud) const
float measurePointToPlaneDistance (const ccPlane *plane, const CCVector3 &point, bool signedMeasurement) const
Detailed Description
Definition at line 19 of file ccMeasurementDevice.h.
Constructor & Destructor Documentation
ccMeasurementDevice()
ccMeasurementDevice::ccMeasurementDevice (ecvMainAppInterface * app) inline explicit
Definition at line 21 of file ccMeasurementDevice.h.
Member Function Documentation
createScalarFieldForCloud()
void ccMeasurementDevice::createScalarFieldForCloud (const ccPlane * plane, ccPointCloud * cloud, bool signedMeasurement) const
Definition at line 37 of file ccMeasurementDevice.cpp.
References ccScalarField::computeMinAndMax(), ccPlane::getEquation(), ccPlane::getNormal(), ccHObject::redrawDisplay(), ccPointCloud::setCurrentDisplayedScalarField(), ccDrawableObject::showSF(), ccPointCloud::showSFColorsScale(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
deleteScalarFieldFromCloud()
void ccMeasurementDevice::deleteScalarFieldFromCloud (ccPointCloud * cloud) const
Definition at line 61 of file ccMeasurementDevice.cpp.
References ccPointCloud::deleteScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), MPLANE_SCALARFIELD_NAME, and ccHObject::redrawDisplay().
fitPlaneToPoints()
ccPlane * ccMeasurementDevice::fitPlaneToPoints (const std::vector< ccMPlanePoint > & fittingPoints, const QString & planeName) const
Definition at line 16 of file ccMeasurementDevice.cpp.
References ccPlane::Fit(), and ccPointCloud::reserveThePointsTable().
measurePointToPlaneDistance()
float ccMeasurementDevice::measurePointToPlaneDistance (const ccPlane * plane, const CCVector3 & point, bool signedMeasurement) const
Definition at line 70 of file ccMeasurementDevice.cpp.
References cloudViewer::DistanceComputationTools::computePoint2PlaneDistance(), ccPlane::getEquation(), ccPlane::getNormal(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qMPlane/src/ccMeasurementDevice.h
/root/ACloudViewer/plugins/core/Standard/qMPlane/src/ccMeasurementDevice.cpp