ACloudViewer: qCloudLayers Class Reference
qCloudLayers Class Reference
#include <qCloudLayers.h>
Protected Member Functions
void doAction ()
Slot called when associated action is triggered.
Protected Member Functions inherited from ccDefaultPluginInterface
ccDefaultPluginInterface (const QString &resourcePath=QString())
Additional Inherited Members
Public Types inherited from ccPluginInterface
typedef QList< Contact > ContactList
using ReferenceList = QList< Reference >
Public Member Functions inherited from ccStdPluginInterface
ccStdPluginInterface (const QString &resourcePath=QString())
Default constructor.
virtual ~ccStdPluginInterface () override=default
Destructor.
virtual CC_PLUGIN_TYPE getType () const override
Returns plugin type (standard or OpenGL filter)
virtual void setMainAppInterface (ecvMainAppInterface *app)
Sets application entry point.
virtual ecvMainAppInterface * getMainAppInterface ()
A callback pointer to the main app interface for use by plugins.
virtual void dispToConsole (QString message, ecvMainAppInterface::ConsoleMessageLevel level=ecvMainAppInterface::STD_CONSOLE_MESSAGE)
Shortcut to ecvMainAppInterface::dispToConsole.
Public Member Functions inherited from ccDefaultPluginInterface
virtual ~ccDefaultPluginInterface ()
virtual bool isCore () const override
Is this plugin a core plugin?
virtual QString getName () const override
Returns (short) name (for menu entry, etc.)
virtual QString getDescription () const override
Returns long name/description (for tooltip, etc.)
virtual QIcon getIcon () const override
Returns icon.
virtual ReferenceList getReferences () const override
virtual ContactList getAuthors () const override
virtual ContactList getMaintainers () const override
Public Member Functions inherited from ccPluginInterface
virtual ~ccPluginInterface ()=default
Virtual destructor.
virtual bool start ()
Starts the plugin.
virtual void stop ()
Stops the plugin.
virtual ccExternalFactory * getCustomObjectsFactory () const
Returns the plugin's custom object factory (if any)
virtual void registerCommands (ccCommandLineInterface *cmd)
Optional: registers commands (for the command line mode)
Protected Attributes inherited from ccStdPluginInterface
ecvMainAppInterface * m_app
Main application interface.
Detailed Description
Definition at line 31 of file qCloudLayers.h.
Member Function Documentation
doAction()
void qCloudLayers::doAction () protected
Slot called when associated action is triggered.
Definition at line 52 of file qCloudLayers.cpp.
References ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, CVLog::Error(), ecvMainAppInterface::getActiveWindow(), ecvMainAppInterface::getMainWindow(), ecvMainAppInterface::getSelectedEntities(), ccPointCloud::hasScalarFields(), ecvMainAppInterface::haveOneSelection(), ccOverlayDialog::linkWith(), ccStdPluginInterface::m_app, CV_TYPES::POINT_CLOUD, ecvMainAppInterface::registerOverlayDialog(), ccCloudLayersDlg::setPointCloud(), ccCloudLayersDlg::start(), ecvMainAppInterface::updateOverlayDialogsPlacement(), and ecvMainAppInterface::updateUI().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCloudLayers/include/qCloudLayers.h
/root/ACloudViewer/plugins/core/Standard/qCloudLayers/src/qCloudLayers.cpp