ACloudViewer: cloudViewer::visualization::gui::BitmapWindowSystem Class Reference
cloudViewer::visualization::gui::BitmapWindowSystem Class Reference
#include <BitmapWindowSystem.h>
Classes
struct Impl
Public Types
enum class Rendering { NORMAL , HEADLESS }
using OnDrawCallback = std::function< void(Window *, std::shared_ptr< core::Tensor >)>
Public Types inherited from cloudViewer::visualization::gui::WindowSystem
using OSWindow = void *
Public Member Functions
BitmapWindowSystem (Rendering mode=Rendering::NORMAL)
~BitmapWindowSystem ()
void Initialize () override
void Uninitialize () override
void SetOnWindowDraw (OnDrawCallback callback)
void WaitEventsTimeout (double timeout_secs) override
OSWindow CreateOSWindow (Window *o3d_window, int width, int height, const char *title, int flags) override
void DestroyWindow (OSWindow w) override
Size GetScreenSize (OSWindow w) override
void PostRedrawEvent (OSWindow w) override
void PostMouseEvent (OSWindow w, const MouseEvent &e)
void PostKeyEvent (OSWindow w, const KeyEvent &e)
void PostTextInputEvent (OSWindow w, const TextInputEvent &e)
bool GetWindowIsVisible (OSWindow w) const override
void ShowWindow (OSWindow w, bool show) override
void RaiseWindowToTop (OSWindow w) override
bool IsActiveWindow (OSWindow w) const override
Point GetWindowPos (OSWindow w) const override
void SetWindowPos (OSWindow w, int x, int y) override
Size GetWindowSize (OSWindow w) const override
void SetWindowSize (OSWindow w, int width, int height) override
Size GetWindowSizePixels (OSWindow w) const override
void SetWindowSizePixels (OSWindow w, const Size &size) override
float GetWindowScaleFactor (OSWindow w) const override
float GetUIScaleFactor (OSWindow w) const override
void SetWindowTitle (OSWindow w, const char *title) override
Point GetMousePosInWindow (OSWindow w) const override
int GetMouseButtons (OSWindow w) const override
void CancelUserClose (OSWindow w) override
void * GetNativeDrawable (OSWindow w) override
rendering::FilamentRenderer * CreateRenderer (OSWindow w) override
void ResizeRenderer (OSWindow w, rendering::FilamentRenderer *renderer) override
MenuBase * CreateOSMenu () override
Public Member Functions inherited from cloudViewer::visualization::gui::WindowSystem
virtual ~WindowSystem ()
Additional Inherited Members
Static Public Attributes inherited from cloudViewer::visualization::gui::WindowSystem
static constexpr int FLAG_VISIBLE = 0
static constexpr int FLAG_HIDDEN = (1 << 0)
static constexpr int FLAG_TOPMOST = (1 << 1)
Detailed Description
Definition at line 28 of file BitmapWindowSystem.h.
Member Typedef Documentation
OnDrawCallback
using cloudViewer::visualization::gui::BitmapWindowSystem::OnDrawCallback = std::function<void(Window*, std::shared_ptr<core::Tensor>)>
Definition at line 41 of file BitmapWindowSystem.h.
Member Enumeration Documentation
Rendering
enum cloudViewer::visualization::gui::BitmapWindowSystem::Rendering strong
Enumerator
NORMAL
HEADLESS
Definition at line 30 of file BitmapWindowSystem.h.
Constructor & Destructor Documentation
BitmapWindowSystem()
cloudViewer::visualization::gui::BitmapWindowSystem::BitmapWindowSystem (Rendering mode = Rendering::NORMAL)
Definition at line 132 of file BitmapWindowSystem.cpp.
References cloudViewer::visualization::rendering::EngineInstance::EnableHeadless(), HEADLESS, and LogWarning.
~BitmapWindowSystem()
cloudViewer::visualization::gui::BitmapWindowSystem::~BitmapWindowSystem ()
Definition at line 144 of file BitmapWindowSystem.cpp.
Member Function Documentation
CancelUserClose()
void cloudViewer::visualization::gui::BitmapWindowSystem::CancelUserClose (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 278 of file BitmapWindowSystem.cpp.
CreateOSMenu()
MenuBase * cloudViewer::visualization::gui::BitmapWindowSystem::CreateOSMenu () override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 313 of file BitmapWindowSystem.cpp.
CreateOSWindow()
WindowSystem::OSWindow cloudViewer::visualization::gui::BitmapWindowSystem::CreateOSWindow (Window * o3d_window, int width, int height, const char * title, int flags) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Reimplemented in cloudViewer::visualization::webrtc_server::WebRTCWindowSystem.
Definition at line 170 of file BitmapWindowSystem.cpp.
References height, o3d_window, and width.
CreateRenderer()
rendering::FilamentRenderer * cloudViewer::visualization::gui::BitmapWindowSystem::CreateRenderer (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 282 of file BitmapWindowSystem.cpp.
References frame, cloudViewer::visualization::rendering::EngineInstance::GetInstance(), cloudViewer::visualization::rendering::EngineInstance::GetResourceManager(), GetWindowSizePixels(), image, and size.
DestroyWindow()
void cloudViewer::visualization::gui::BitmapWindowSystem::DestroyWindow (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Reimplemented in cloudViewer::visualization::webrtc_server::WebRTCWindowSystem.
Definition at line 179 of file BitmapWindowSystem.cpp.
GetMouseButtons()
int cloudViewer::visualization::gui::BitmapWindowSystem::GetMouseButtons (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 274 of file BitmapWindowSystem.cpp.
GetMousePosInWindow()
Point cloudViewer::visualization::gui::BitmapWindowSystem::GetMousePosInWindow (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 270 of file BitmapWindowSystem.cpp.
GetNativeDrawable()
void * cloudViewer::visualization::gui::BitmapWindowSystem::GetNativeDrawable (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 280 of file BitmapWindowSystem.cpp.
GetScreenSize()
Size cloudViewer::visualization::gui::BitmapWindowSystem::GetScreenSize (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 166 of file BitmapWindowSystem.cpp.
GetUIScaleFactor()
float cloudViewer::visualization::gui::BitmapWindowSystem::GetUIScaleFactor (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 266 of file BitmapWindowSystem.cpp.
GetWindowIsVisible()
bool cloudViewer::visualization::gui::BitmapWindowSystem::GetWindowIsVisible (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 225 of file BitmapWindowSystem.cpp.
GetWindowPos()
Point cloudViewer::visualization::gui::BitmapWindowSystem::GetWindowPos (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 233 of file BitmapWindowSystem.cpp.
References frame.
GetWindowScaleFactor()
float cloudViewer::visualization::gui::BitmapWindowSystem::GetWindowScaleFactor (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 262 of file BitmapWindowSystem.cpp.
GetWindowSize()
Size cloudViewer::visualization::gui::BitmapWindowSystem::GetWindowSize (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 242 of file BitmapWindowSystem.cpp.
References frame.
Referenced by GetWindowSizePixels().
GetWindowSizePixels()
Size cloudViewer::visualization::gui::BitmapWindowSystem::GetWindowSizePixels (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 254 of file BitmapWindowSystem.cpp.
References GetWindowSize().
Referenced by CreateRenderer(), and ResizeRenderer().
Initialize()
void cloudViewer::visualization::gui::BitmapWindowSystem::Initialize () override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 146 of file BitmapWindowSystem.cpp.
IsActiveWindow()
bool cloudViewer::visualization::gui::BitmapWindowSystem::IsActiveWindow (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 231 of file BitmapWindowSystem.cpp.
PostKeyEvent()
void cloudViewer::visualization::gui::BitmapWindowSystem::PostKeyEvent (OSWindow w, const KeyEvent & e)
Definition at line 214 of file BitmapWindowSystem.cpp.
PostMouseEvent()
void cloudViewer::visualization::gui::BitmapWindowSystem::PostMouseEvent (OSWindow w, const MouseEvent & e)
Definition at line 209 of file BitmapWindowSystem.cpp.
PostRedrawEvent()
void cloudViewer::visualization::gui::BitmapWindowSystem::PostRedrawEvent (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 204 of file BitmapWindowSystem.cpp.
Referenced by cloudViewer::visualization::webrtc_server::WebRTCWindowSystem::OnDataChannelMessage(), and cloudViewer::visualization::webrtc_server::WebRTCWindowSystem::SendInitFrames().
PostTextInputEvent()
void cloudViewer::visualization::gui::BitmapWindowSystem::PostTextInputEvent (OSWindow w, const TextInputEvent & e)
Definition at line 219 of file BitmapWindowSystem.cpp.
RaiseWindowToTop()
void cloudViewer::visualization::gui::BitmapWindowSystem::RaiseWindowToTop (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 229 of file BitmapWindowSystem.cpp.
ResizeRenderer()
void cloudViewer::visualization::gui::BitmapWindowSystem::ResizeRenderer (OSWindow w, rendering::FilamentRenderer * renderer) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 307 of file BitmapWindowSystem.cpp.
References GetWindowSizePixels(), size, and cloudViewer::visualization::rendering::FilamentRenderer::UpdateBitmapSwapChain().
SetOnWindowDraw()
void cloudViewer::visualization::gui::BitmapWindowSystem::SetOnWindowDraw (OnDrawCallback callback)
Definition at line 150 of file BitmapWindowSystem.cpp.
References callback.
SetWindowPos()
void cloudViewer::visualization::gui::BitmapWindowSystem::SetWindowPos (OSWindow w, int x, int y) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 237 of file BitmapWindowSystem.cpp.
SetWindowSize()
void cloudViewer::visualization::gui::BitmapWindowSystem::SetWindowSize (OSWindow w, int width, int height) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 247 of file BitmapWindowSystem.cpp.
References height, and width.
Referenced by SetWindowSizePixels().
SetWindowSizePixels()
void cloudViewer::visualization::gui::BitmapWindowSystem::SetWindowSizePixels (OSWindow w, const Size & size) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 258 of file BitmapWindowSystem.cpp.
References SetWindowSize(), and size.
SetWindowTitle()
void cloudViewer::visualization::gui::BitmapWindowSystem::SetWindowTitle (OSWindow w, const char * title) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 268 of file BitmapWindowSystem.cpp.
ShowWindow()
void cloudViewer::visualization::gui::BitmapWindowSystem::ShowWindow (OSWindow w, bool show) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 227 of file BitmapWindowSystem.cpp.
Uninitialize()
void cloudViewer::visualization::gui::BitmapWindowSystem::Uninitialize () override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 148 of file BitmapWindowSystem.cpp.
WaitEventsTimeout()
void cloudViewer::visualization::gui::BitmapWindowSystem::WaitEventsTimeout (double timeout_secs) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 155 of file BitmapWindowSystem.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/BitmapWindowSystem.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/BitmapWindowSystem.cpp