ACloudViewer: ccMeasurementRecorder Class Reference
ccMeasurementRecorder Class Reference
#include <ccMeasurementRecorder.h>
Public Member Functions
ccMeasurementRecorder (ccPointCloud *rootCloud, ecvMainAppInterface *app)
void loadDataFromSelectedCloud ()
void addFittingPoint (const ccPickingListener::PickedItem &item)
void deleteFittingPoint (unsigned int index)
void renameFittingPoint (const QString &newName, unsigned int fittingPointIndex)
const std::vector< ccMPlanePoint > & getFittingPoints () const
unsigned int getActualFittingPointIndex () const
unsigned int getFittingPointAmount () const
void addMeasurementPoint (const ccPickingListener::PickedItem &item, float distance)
const std::vector< ccMPlanePoint > & getMeasurementPoints () const
bool renameMeasurement (const QString &newName, unsigned int measurementIndex)
void updateMeasurement (float distance, unsigned int measurementIndex)
ccPlane * getPlane () const
void setPlane (const ccPlane *plane)
void deletePlane ()
Detailed Description
Definition at line 21 of file ccMeasurementRecorder.h.
Constructor & Destructor Documentation
ccMeasurementRecorder()
ccMeasurementRecorder::ccMeasurementRecorder (ccPointCloud * rootCloud, ecvMainAppInterface * app) inline
Definition at line 23 of file ccMeasurementRecorder.h.
Member Function Documentation
addFittingPoint()
void ccMeasurementRecorder::addFittingPoint (const ccPickingListener::PickedItem & item)
Definition at line 46 of file ccMeasurementRecorder.cpp.
References ccHObject::addChild(), CC_ITEM_TREE::createPointLabel2D(), and getActualFittingPointIndex().
addMeasurementPoint()
void ccMeasurementRecorder::addMeasurementPoint (const ccPickingListener::PickedItem & item, float distance)
Definition at line 56 of file ccMeasurementRecorder.cpp.
References ccHObject::addChild(), and CC_ITEM_TREE::createPointLabel2D().
deleteFittingPoint()
void ccMeasurementRecorder::deleteFittingPoint (unsigned int index)
Definition at line 154 of file ccMeasurementRecorder.cpp.
deletePlane()
void ccMeasurementRecorder::deletePlane ()
Definition at line 147 of file ccMeasurementRecorder.cpp.
Referenced by setPlane().
getActualFittingPointIndex()
unsigned int ccMeasurementRecorder::getActualFittingPointIndex () const
Definition at line 31 of file ccMeasurementRecorder.cpp.
Referenced by addFittingPoint().
getFittingPointAmount()
unsigned int ccMeasurementRecorder::getFittingPointAmount () const
Definition at line 35 of file ccMeasurementRecorder.cpp.
getFittingPoints()
const std::vector< ccMPlanePoint > & ccMeasurementRecorder::getFittingPoints () const
Definition at line 21 of file ccMeasurementRecorder.cpp.
getMeasurementPoints()
const std::vector< ccMPlanePoint > & ccMeasurementRecorder::getMeasurementPoints () const
Definition at line 26 of file ccMeasurementRecorder.cpp.
getPlane()
ccPlane * ccMeasurementRecorder::getPlane () const
Definition at line 127 of file ccMeasurementRecorder.cpp.
loadDataFromSelectedCloud()
void ccMeasurementRecorder::loadDataFromSelectedCloud ()
Definition at line 39 of file ccMeasurementRecorder.cpp.
renameFittingPoint()
void ccMeasurementRecorder::renameFittingPoint (const QString & newName, unsigned int fittingPointIndex)
Definition at line 159 of file ccMeasurementRecorder.cpp.
renameMeasurement()
bool ccMeasurementRecorder::renameMeasurement (const QString & newName, unsigned int measurementIndex)
Definition at line 105 of file ccMeasurementRecorder.cpp.
setPlane()
void ccMeasurementRecorder::setPlane (const ccPlane * plane)
Definition at line 129 of file ccMeasurementRecorder.cpp.
References abs(), ccHObject::addChild(), deletePlane(), cloudViewer::PointCloudTpl< T >::getBoundingBox(), length(), max(), ccPlane::setXWidth(), ccPlane::setYWidth(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
updateMeasurement()
void ccMeasurementRecorder::updateMeasurement (float distance, unsigned int measurementIndex)
Definition at line 122 of file ccMeasurementRecorder.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qMPlane/src/ccMeasurementRecorder.h
/root/ACloudViewer/plugins/core/Standard/qMPlane/src/ccMeasurementRecorder.cpp