ACloudViewer: VtkUtils::TableModel Class Reference
VtkUtils::TableModel Class Reference
#include <tablemodel.h>
Signals
void rowsChanged (int oldRows, int newRows)
void columnsChanged (int oldCols, int newCols)
Public Member Functions
TableModel (int column, int row, QObject *parent=nullptr)
TableModel (const ccHObject *objContainer, QObject *parent=nullptr)
void updateData (const ccHObject *objContainer)
virtual ~TableModel ()
void random (int min=-5, int max=5)
void resize (int column, int row)
void clear ()
int randomMin ()
int randomMax ()
void setHorizontalHeaderData (const QVariantList &data)
QVariantList horizontalHeaderData () const
void setVerticalHeaderData (const QVariantList &data)
QVariantList verticalHeaderData () const
int rowCount (const QModelIndex &parent=QModelIndex()) const
int columnCount (const QModelIndex &parent=QModelIndex()) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
qreal data (int row, int col) const
QVector< Tuple3ui > verticesData () const
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
bool setData (int row, int column, const QVariant &value)
Qt::ItemFlags flags (const QModelIndex &index) const
Detailed Description
Definition at line 21 of file tablemodel.h.
Constructor & Destructor Documentation
TableModel() [1/2]
VtkUtils::TableModel::TableModel (int column, int row, QObject * parent = nullptr) explicit
Definition at line 28 of file tablemodel.cpp.
TableModel() [2/2]
VtkUtils::TableModel::TableModel (const ccHObject * objContainer, QObject * parent = nullptr) explicit
Definition at line 46 of file tablemodel.cpp.
References updateData().
~TableModel()
VtkUtils::TableModel::~TableModel () virtual
Definition at line 108 of file tablemodel.cpp.
References clear().
Member Function Documentation
clear()
void VtkUtils::TableModel::clear ()
Definition at line 147 of file tablemodel.cpp.
Referenced by updateData(), and ~TableModel().
columnCount()
int VtkUtils::TableModel::columnCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 187 of file tablemodel.cpp.
Referenced by VtkUtils::ModelToPointsConverter::run(), VtkUtils::ModelToVectorsConverter::run(), and VtkUtils::ModelToVtkTableConverter::run().
columnsChanged
void VtkUtils::TableModel::columnsChanged (int oldCols, int newCols) signal
Referenced by resize().
data() [1/2]
QVariant VtkUtils::TableModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Definition at line 213 of file tablemodel.cpp.
Referenced by VtkUtils::ModelToPointsConverter::run(), VtkUtils::ModelToVectorsConverter::run(), VtkUtils::ModelToVtkTableConverter::run(), setHorizontalHeaderData(), and setVerticalHeaderData().
data() [2/2]
qreal VtkUtils::TableModel::data (int row, int col) const
Definition at line 223 of file tablemodel.cpp.
flags()
Qt::ItemFlags VtkUtils::TableModel::flags (const QModelIndex & index) const
Definition at line 243 of file tablemodel.cpp.
headerData()
QVariant VtkUtils::TableModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Definition at line 192 of file tablemodel.cpp.
horizontalHeaderData()
QVariantList VtkUtils::TableModel::horizontalHeaderData () const
Definition at line 169 of file tablemodel.cpp.
random()
void VtkUtils::TableModel::random (int min = -5, int max = 5)
Definition at line 110 of file tablemodel.cpp.
References Utils::random().
randomMax()
int VtkUtils::TableModel::randomMax ()
Definition at line 160 of file tablemodel.cpp.
randomMin()
int VtkUtils::TableModel::randomMin ()
Definition at line 158 of file tablemodel.cpp.
resize()
void VtkUtils::TableModel::resize (int column, int row)
Definition at line 123 of file tablemodel.cpp.
References columnsChanged(), and rowsChanged().
Referenced by VtkUtils::PointsToModelConverter::run().
rowCount()
int VtkUtils::TableModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 182 of file tablemodel.cpp.
Referenced by VtkUtils::ModelToPointsConverter::run(), VtkUtils::ModelToVectorsConverter::run(), and VtkUtils::ModelToVtkTableConverter::run().
rowsChanged
void VtkUtils::TableModel::rowsChanged (int oldRows, int newRows) signal
Referenced by resize().
setData() [1/2]
bool VtkUtils::TableModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
Definition at line 227 of file tablemodel.cpp.
Referenced by VtkUtils::PointsToModelConverter::run(), and setData().
setData() [2/2]
bool VtkUtils::TableModel::setData (int row, int column, const QVariant & value)
Definition at line 238 of file tablemodel.cpp.
References setData().
setHorizontalHeaderData()
void VtkUtils::TableModel::setHorizontalHeaderData (const QVariantList & data)
Definition at line 162 of file tablemodel.cpp.
References data().
setVerticalHeaderData()
void VtkUtils::TableModel::setVerticalHeaderData (const QVariantList & data)
Definition at line 173 of file tablemodel.cpp.
References data().
updateData()
void VtkUtils::TableModel::updateData (const ccHObject * objContainer)
Definition at line 51 of file tablemodel.cpp.
References clear(), ccDrawableObject::colorsShown(), count, ccHObject::getChild(), ccHObject::getChildrenNumber(), cloudViewer::GenericIndexedCloud::getPoint(), ccGenericPointCloud::getTheVisibilityArray(), cloudViewer::GenericIndexedMesh::getTriangleVertIndexes(), cloudViewer::VerticesIndexes::i, cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, ccObject::isKindOf(), CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, POINT_VISIBLE, cloudViewer::GenericCloud::size(), cloudViewer::GenericMesh::size(), ccHObjectCaster::ToGenericPointCloud(), and Tuple3Tpl< Type >::u.
Referenced by TableModel().
verticalHeaderData()
QVariantList VtkUtils::TableModel::verticalHeaderData () const
Definition at line 180 of file tablemodel.cpp.
verticesData()
QVector< Tuple3ui > VtkUtils::TableModel::verticesData () const
Definition at line 225 of file tablemodel.cpp.
Referenced by VtkUtils::ModelToPointsConverter::vertices().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/tablemodel.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/tablemodel.cpp