ACloudViewer: masc::Tools Class Reference
masc::Tools Class Reference
#include <q3DMASCTools.h>
Public Types
typedef QMap< QString, ccPointCloud * > NamedClouds
Static Public Member Functions
static bool LoadTrainingFile (QString filename, Feature::Set &rawFeatures, std::vector< double > &scales, NamedClouds &loadedClouds, TrainParameters &parameters, CorePoints *corePoints=nullptr, QWidget *parent=nullptr)
static bool LoadClassifierCloudLabels (QString filename, QList< QString > &labels, QString &corePointsLabel, bool &filenamesSpecified, QMap< QString, QString > &rolesAndNames)
static bool LoadClassifier (QString filename, NamedClouds &clouds, Feature::Set &rawFeatures, masc::Classifier &classifier, QWidget *parent=nullptr)
static bool LoadFile (const QString &filename, Tools::NamedClouds *clouds, bool cloudsAreProvided, std::vector< Feature::Shared > *rawFeatures=nullptr, std::vector< double > *rawScales=nullptr, masc::CorePoints *corePoints=nullptr, masc::Classifier *classifier=nullptr, TrainParameters *parameters=nullptr, QWidget *parent=nullptr)
static bool SaveClassifier (QString filename, const Feature::Set &features, const QString corePointsRole, const masc::Classifier &classifier, QWidget *parent=nullptr)
static bool PrepareFeatures (const CorePoints &corePoints, Feature::Set &features, QString &error, cloudViewer::GenericProgressCallback *progressCb=nullptr, SFCollector *generatedScalarFields=nullptr)
static bool RandomSubset (ccPointCloud *cloud, float ratio, cloudViewer::ReferenceCloud *inRatioSubset, cloudViewer::ReferenceCloud *outRatioSubset)
static cloudViewer::ScalarField * RetrieveSF (const ccPointCloud *cloud, const QString &sfName, bool caseSensitive=true)
static cloudViewer::ScalarField * GetClassificationSF (const ccPointCloud *cloud)
Helper: returns the classification SF associated to a cloud (if any)
Detailed Description
Definition at line 41 of file q3DMASCTools.h.
Member Typedef Documentation
NamedClouds
typedef QMap<QString, ccPointCloud*> masc::Tools::NamedClouds
Definition at line 43 of file q3DMASCTools.h.
Member Function Documentation
GetClassificationSF()
cloudViewer::ScalarField * Tools::GetClassificationSF (const ccPointCloud * cloud) static
Helper: returns the classification SF associated to a cloud (if any)
Definition at line 1591 of file q3DMASCTools.cpp.
References cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), LAS_CLASSIFICATION, and LAS_FIELD_NAMES.
Referenced by masc::ContextBasedFeature::checkValidity(), masc::Classifier::classify(), q3DMASCPlugin::doTrainAction(), masc::Classifier::evaluate(), masc::ContextBasedFeature::prepare(), and masc::Classifier::train().
LoadClassifier()
bool Tools::LoadClassifier (QString filename, NamedClouds & clouds, Feature::Set & rawFeatures, masc::Classifier & classifier, QWidget * parent = nullptr) static
Definition at line 962 of file q3DMASCTools.cpp.
References filename, and LoadFile().
Referenced by q3DMASCPlugin::doClassifyAction().
LoadClassifierCloudLabels()
bool Tools::LoadClassifierCloudLabels (QString filename, QList< QString > & labels, QString & corePointsLabel, bool & filenamesSpecified, QMap< QString, QString > & rolesAndNames) static
Definition at line 101 of file q3DMASCTools.cpp.
References filename, and CVLog::Warning().
Referenced by q3DMASCPlugin::doClassifyAction(), q3DMASCPlugin::doTrainAction(), and Command3DMASCClassif::process().
LoadFile()
bool Tools::LoadFile (const QString & filename, Tools::NamedClouds * clouds, bool cloudsAreProvided, std::vector< Feature::Shared > * rawFeatures = nullptr, std::vector< double > * rawScales = nullptr, masc::CorePoints * corePoints = nullptr, masc::Classifier * classifier = nullptr, TrainParameters * parameters = nullptr, QWidget * parent = nullptr) static
Definition at line 745 of file q3DMASCTools.cpp.
References masc::RandomTreesParams::activeVarCount, FileIOFilter::LoadParameters::alwaysDisplayLoadDialog, FileIOFilter::LoadParameters::coordinatesShift, FileIOFilter::LoadParameters::coordinatesShiftEnabled, corePoints, CreateFeaturesFromCommand(), ecvGlobalShiftManager::DIALOG_IF_NECESSARY, filename, masc::Classifier::fromFile(), masc::Classifier::isValid(), masc::RandomTreesParams::maxDepth, masc::RandomTreesParams::maxTreeCount, masc::RandomTreesParams::minSampleCount, FileIOFilter::LoadParameters::parentWidget, CVLog::Print(), ReadCloud(), ReadCorePoints(), ReadScales(), FileIOFilter::ResetSesionCounter(), masc::TrainParameters::rt, FileIOFilter::LoadParameters::shiftHandlingMode, masc::TrainParameters::testDataRatio, and CVLog::Warning().
Referenced by LoadClassifier(), LoadTrainingFile(), and Command3DMASCClassif::process().
LoadTrainingFile()
bool Tools::LoadTrainingFile (QString filename, Feature::Set & rawFeatures, std::vector< double > & scales, NamedClouds & loadedClouds, TrainParameters & parameters, CorePoints * corePoints = nullptr, QWidget * parent = nullptr) static
Definition at line 971 of file q3DMASCTools.cpp.
References corePoints, filename, and LoadFile().
Referenced by q3DMASCPlugin::doTrainAction().
PrepareFeatures()
bool Tools::PrepareFeatures (const CorePoints & corePoints, Feature::Set & features, QString & error, cloudViewer::GenericProgressCallback * progressCb = nullptr, SFCollector * generatedScalarFields = nullptr) static
Definition at line 1031 of file q3DMASCTools.cpp.
References cloudViewer::DgmOctree::NearestNeighboursSearchStruct::cellCenter, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::cellPos, cloudViewer::DgmOctree::computeCellCenter(), ccGenericPointCloud::computeOctree(), masc::Feature::ContextBasedFeature, FeaturesAndScales::contextBasedFeaturesPerScale, corePoints, CVLog::Error(), FeaturesAndScales::featureCount, cloudViewer::DgmOctree::findBestLevelForAGivenNeighbourhoodSizeExtraction(), cloudViewer::DgmOctree::findNeighborsInASphereStartingFromCell(), ccObject::getName(), ccGenericPointCloud::getOctree(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::DgmOctree::getTheCellPosWhichIncludesThePoint(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::level, masc::Feature::NeighborhoodFeature, FeaturesAndScales::neighborhoodFeaturesPerScale, masc::Feature::NO_OPERATION, nProgress, octree, octreeLevel, cloudViewer::NormalizedProgress::oneStep(), masc::Feature::PointFeature, FeaturesAndScales::pointFeaturesPerScale, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::pointsInNeighbourhood, CVLog::Print(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::queryPoint, FeaturesAndScales::scales, cloudViewer::GenericProgressCallback::setInfo(), cloudViewer::GenericProgressCallback::setMethodTitle(), cloudViewer::GenericCloud::size(), sourceCloud, cloudViewer::GenericProgressCallback::start(), and CVLog::Warning().
Referenced by q3DMASCPlugin::doClassifyAction(), q3DMASCPlugin::doTrainAction(), and Command3DMASCClassif::process().
RandomSubset()
bool Tools::RandomSubset (ccPointCloud * cloud, float ratio, cloudViewer::ReferenceCloud * inRatioSubset, cloudViewer::ReferenceCloud * outRatioSubset) static
Definition at line 1512 of file q3DMASCTools.cpp.
References cloudViewer::ReferenceCloud::addPointIndex(), cloudViewer::ReferenceCloud::clear(), cloudViewer::utility::floor(), cloudViewer::ReferenceCloud::getAssociatedCloud(), cloudViewer::ReferenceCloud::reserve(), cloudViewer::PointCloudTpl< T >::size(), cloudViewer::ReferenceCloud::size(), size, and CVLog::Warning().
Referenced by q3DMASCPlugin::doTrainAction().
RetrieveSF()
cloudViewer::ScalarField * Tools::RetrieveSF (const ccPointCloud * cloud, const QString & sfName, bool caseSensitive = true) static
Definition at line 993 of file q3DMASCTools.cpp.
References cloudViewer::ScalarField::getName(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudViewer::PointCloudTpl< T >::getScalarField(), and cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName().
Referenced by masc::PointFeature::retrieveField().
SaveClassifier()
bool Tools::SaveClassifier (QString filename, const Feature::Set & features, const QString corePointsRole, const masc::Classifier & classifier, QWidget * parent = nullptr) static
Definition at line 43 of file q3DMASCTools.cpp.
References QtCompat::endl(), CVLog::Error(), filename, masc::Classifier::toFile(), and CVLog::Warning().
Referenced by q3DMASCPlugin::doTrainAction().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/q3DMASC/q3DMASCTools.h
/root/ACloudViewer/plugins/core/Standard/q3DMASC/q3DMASCTools.cpp