ACloudViewer: colmap::P3PEstimator Class Reference
colmap::P3PEstimator Class Reference
#include <absolute_pose.h>
Public Types
typedef Eigen::Vector2d X_t
typedef Eigen::Vector3d Y_t
typedef Eigen::Matrix3x4d M_t
Static Public Member Functions
static std::vector< M_t > Estimate (const std::vector< X_t > &points2D, const std::vector< Y_t > &points3D)
static void Residuals (const std::vector< X_t > &points2D, const std::vector< Y_t > &points3D, const M_t &proj_matrix, std::vector< double > *residuals)
Static Public Attributes
static const int kMinNumSamples = 3
Detailed Description
Definition at line 26 of file absolute_pose.h.
Member Typedef Documentation
M_t
typedef Eigen::Matrix3x4d colmap::P3PEstimator::M_t
Definition at line 33 of file absolute_pose.h.
X_t
typedef Eigen::Vector2d colmap::P3PEstimator::X_t
Definition at line 29 of file absolute_pose.h.
Y_t
typedef Eigen::Vector3d colmap::P3PEstimator::Y_t
Definition at line 31 of file absolute_pose.h.
Member Function Documentation
Estimate()
std::vector< P3PEstimator::M_t > colmap::P3PEstimator::Estimate (const std::vector< X_t > & points2D, const std::vector< Y_t > & points3D) static
Definition at line 47 of file absolute_pose.cc.
References a, coeffs(), e, colmap::FindPolynomialRootsCompanionMatrix(), x, and y.
Residuals()
void colmap::P3PEstimator::Residuals (const std::vector< X_t > & points2D, const std::vector< Y_t > & points3D, const M_t & proj_matrix, std::vector< double > * residuals) static
Definition at line 176 of file absolute_pose.cc.
References colmap::ComputeSquaredReprojectionError().
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
kMinNumSamples
const int colmap::P3PEstimator::kMinNumSamples = 3 static
Definition at line 36 of file absolute_pose.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/estimators/absolute_pose.h
/root/ACloudViewer/libs/Reconstruction/src/estimators/absolute_pose.cc