ACloudViewer: colmap::mvs::DepthMap Class Reference
colmap::mvs::DepthMap Class Reference
#include <depth_map.h>
Public Member Functions
DepthMap ()
DepthMap (const size_t width, const size_t height, const float depth_min, const float depth_max)
DepthMap (const Mat< float > &mat, const float depth_min, const float depth_max)
float GetDepthMin () const
float GetDepthMax () const
float Get (const size_t row, const size_t col) const
void Rescale (const float factor)
void Downsize (const size_t max_width, const size_t max_height)
Bitmap ToBitmap (const float min_percentile, const float max_percentile) const
Public Member Functions inherited from colmap::mvs::Mat< float >
Mat ()
Mat (const size_t width, const size_t height, const size_t depth)
size_t GetWidth () const
size_t GetHeight () const
size_t GetDepth () const
size_t GetNumBytes () const
float Get (const size_t row, const size_t col, const size_t slice=0) const
void GetSlice (const size_t row, const size_t col, float *values) const
float * GetPtr ()
const float * GetPtr () const
const std::vector< float > & GetData () const
void Set (const size_t row, const size_t col, const float value)
void Set (const size_t row, const size_t col, const size_t slice, const float value)
void Fill (const float value)
void Read (const std::string &path)
void Write (const std::string &path) const
Additional Inherited Members
Protected Attributes inherited from colmap::mvs::Mat< float >
size_t width_
size_t height_
size_t depth_
std::vector< float > data_
Detailed Description
Definition at line 19 of file depth_map.h.
Constructor & Destructor Documentation
DepthMap() [1/3]
colmap::mvs::DepthMap::DepthMap ()
Definition at line 40 of file depth_map.cc.
DepthMap() [2/3]
colmap::mvs::DepthMap::DepthMap (const size_t width, const size_t height, const float depth_min, const float depth_max)
Definition at line 42 of file depth_map.cc.
DepthMap() [3/3]
colmap::mvs::DepthMap::DepthMap (const Mat< float > & mat, const float depth_min, const float depth_max)
Definition at line 48 of file depth_map.cc.
References colmap::mvs::Mat< float >::data_, colmap::mvs::Mat< T >::GetData(), and colmap::mvs::Mat< T >::GetDepth().
Member Function Documentation
Downsize()
void colmap::mvs::DepthMap::Downsize (const size_t max_width, const size_t max_height)
Definition at line 75 of file depth_map.cc.
References colmap::mvs::Mat< float >::height_, Rescale(), and colmap::mvs::Mat< float >::width_.
Referenced by BOOST_AUTO_TEST_CASE().
Get()
float colmap::mvs::DepthMap::Get (const size_t row, const size_t col) const inline
Definition at line 54 of file depth_map.h.
References colmap::mvs::Mat< float >::data_, and colmap::mvs::Mat< float >::width_.
Referenced by ToBitmap().
GetDepthMax()
float colmap::mvs::DepthMap::GetDepthMax () const inline
Definition at line 52 of file depth_map.h.
Referenced by BOOST_AUTO_TEST_CASE().
GetDepthMin()
float colmap::mvs::DepthMap::GetDepthMin () const inline
Definition at line 50 of file depth_map.h.
Referenced by BOOST_AUTO_TEST_CASE().
Rescale()
void colmap::mvs::DepthMap::Rescale (const float factor)
Definition at line 57 of file depth_map.cc.
References colmap::mvs::Mat< float >::data_, colmap::DownsampleImage(), colmap::mvs::Mat< float >::height_, and colmap::mvs::Mat< float >::width_.
Referenced by BOOST_AUTO_TEST_CASE(), and Downsize().
ToBitmap()
Bitmap colmap::mvs::DepthMap::ToBitmap (const float min_percentile, const float max_percentile) const
Definition at line 84 of file depth_map.cc.
References colmap::Bitmap::Allocate(), colmap::JetColormap::Blue(), color, colmap::mvs::Mat< float >::data_, colmap::Bitmap::Fill(), Get(), colmap::JetColormap::Green(), colmap::mvs::Mat< float >::height_, colmap::Percentile(), colmap::JetColormap::Red(), colmap::Bitmap::SetPixel(), colmap::mvs::Mat< float >::width_, x, and y.
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/mvs/depth_map.h
/root/ACloudViewer/libs/Reconstruction/src/mvs/depth_map.cc