ACloudViewer: cloudViewer::t::io::RGBDSensor Class Reference
cloudViewer::t::io::RGBDSensor Class Reference abstract
Interface class for control of RGBD cameras.
#include <RGBDSensor.h>
Public Member Functions
RGBDSensor ()
Default constructor. Initialize with default settings.
virtual ~RGBDSensor ()
virtual bool InitSensor (const RGBDSensorConfig &sensor_config, size_t sensor_index=0, const std::string &filename="")=0
virtual bool StartCapture (bool start_record=false)=0
virtual void PauseRecord ()=0
Pause recording to the file.
virtual void ResumeRecord ()=0
virtual geometry::RGBDImage CaptureFrame (bool wait=true, bool align_depth_to_color=true)=0
virtual uint64_t GetTimestamp () const =0
Get current timestamp (in us).
virtual void StopCapture ()=0
Stop capturing frames.
virtual const RGBDVideoMetadata & GetMetadata () const =0
Get const reference to the metadata of the RGBD video capture.
virtual std::string GetFilename () const =0
Get filename being written.
virtual const std::string ToString () const
Text Description.
Detailed Description
Interface class for control of RGBD cameras.
Definition at line 22 of file RGBDSensor.h.
Constructor & Destructor Documentation
RGBDSensor()
cloudViewer::t::io::RGBDSensor::RGBDSensor () inline
Default constructor. Initialize with default settings.
Definition at line 25 of file RGBDSensor.h.
~RGBDSensor()
virtual cloudViewer::t::io::RGBDSensor::~RGBDSensor () inline virtual
Definition at line 26 of file RGBDSensor.h.
Member Function Documentation
CaptureFrame()
virtual geometry::RGBDImage cloudViewer::t::io::RGBDSensor::CaptureFrame (bool wait = true, bool align_depth_to_color = true) pure virtual
Acquire the next synchronized RGBD frameset from the camera.
Parameters
align_depth_to_color Enable aligning WFOV depth image to the color image in visualizer.
wait If true wait for the next frame set, else return immediately with an empty RGBDImage if it is not yet available
Implemented in cloudViewer::t::io::RealSenseSensor.
GetFilename()
virtual std::string cloudViewer::t::io::RGBDSensor::GetFilename () const pure virtual
Get filename being written.
Implemented in cloudViewer::t::io::RealSenseSensor.
Referenced by ToString().
GetMetadata()
virtual const RGBDVideoMetadata& cloudViewer::t::io::RGBDSensor::GetMetadata () const pure virtual
Get const reference to the metadata of the RGBD video capture.
Implemented in cloudViewer::t::io::RealSenseSensor.
Referenced by ToString().
GetTimestamp()
virtual uint64_t cloudViewer::t::io::RGBDSensor::GetTimestamp () const pure virtual
Get current timestamp (in us).
Implemented in cloudViewer::t::io::RealSenseSensor.
Referenced by ToString().
InitSensor()
virtual bool cloudViewer::t::io::RGBDSensor::InitSensor (const RGBDSensorConfig & sensor_config, size_t sensor_index = 0, const std::string & filename = "") pure virtual
Initialize sensor (optional).
Configure sensor with custom settings. If this is skipped, default settings will be used. You can enable recording to a file by specifying a filename.
Parameters
sensor_config Camera configuration, such as resolution and framerate. A serial number can be entered here to connect to a specific camera.
sensor_index Connect to a camera at this position in the enumeration of RealSense cameras that are currently connected. Use EnumerateDevices() or ListDevices() to obtain a list of connected cameras and their capabilities. This is ignored if sensor_config contains a "serial" entry.
filename Save frames to this file.
Returns
true if a camera was found and initialized with the given settings, else false.
Implemented in cloudViewer::t::io::RealSenseSensor.
PauseRecord()
virtual void cloudViewer::t::io::RGBDSensor::PauseRecord () pure virtual
Pause recording to the file.
Implemented in cloudViewer::t::io::RealSenseSensor.
ResumeRecord()
virtual void cloudViewer::t::io::RGBDSensor::ResumeRecord () pure virtual
Resume recording to the file. The file will contain discontinuous segments.
Implemented in cloudViewer::t::io::RealSenseSensor.
StartCapture()
virtual bool cloudViewer::t::io::RGBDSensor::StartCapture (bool start_record = false) pure virtual
Start capturing synchronized depth and color frames.
Parameters
start_record start recording to the specified file as well.
Implemented in cloudViewer::t::io::RealSenseSensor.
StopCapture()
virtual void cloudViewer::t::io::RGBDSensor::StopCapture () pure virtual
Stop capturing frames.
Implemented in cloudViewer::t::io::RealSenseSensor.
ToString()
virtual const std::string cloudViewer::t::io::RGBDSensor::ToString () const inline virtual
Text Description.
Definition at line 81 of file RGBDSensor.h.
References format, GetFilename(), GetMetadata(), GetTimestamp(), and patch::to_string().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/t/io/sensor/RGBDSensor.h