ACloudViewer: PCLModules::FeatureCloud Class Reference
PCLModules::FeatureCloud Class Reference
#include <PCLModules.h>
Public Types
typedef pcl::PointCloud< NormalT > SurfaceNormals
typedef pcl::PointCloud< pcl::FPFHSignature33 > LocalFeatures
typedef pcl::search::KdTree< PointT > SearchMethod
Public Member Functions
FeatureCloud ()
~FeatureCloud ()
void setNormalRadius (float normalRadius)
void setFeatureRadius (float featureRadius)
void setmaxThreadCount (int maxThreadCount)
void setInputCloud (PointCloudT::Ptr xyz)
void loadInputCloud (const std::string &pcd_file)
PointCloudT::Ptr getPointCloud () const
SurfaceNormals::Ptr getSurfaceNormals () const
LocalFeatures::Ptr getLocalFeatures () const
Protected Member Functions
void processInput ()
void computeSurfaceNormals ()
void computeLocalFeatures ()
Detailed Description
Definition at line 1451 of file PCLModules.h.
Member Typedef Documentation
LocalFeatures
typedef pcl::PointCloud<pcl::FPFHSignature33> PCLModules::FeatureCloud::LocalFeatures
Definition at line 1455 of file PCLModules.h.
SearchMethod
typedef pcl::search::KdTree<PointT> PCLModules::FeatureCloud::SearchMethod
Definition at line 1456 of file PCLModules.h.
SurfaceNormals
typedef pcl::PointCloud<NormalT> PCLModules::FeatureCloud::SurfaceNormals
Definition at line 1454 of file PCLModules.h.
Constructor & Destructor Documentation
FeatureCloud()
PCLModules::FeatureCloud::FeatureCloud ()
Definition at line 350 of file PCLModules.cpp.
~FeatureCloud()
PCLModules::FeatureCloud::~FeatureCloud () inline
Definition at line 1459 of file PCLModules.h.
Member Function Documentation
computeLocalFeatures()
void PCLModules::FeatureCloud::computeLocalFeatures () protected
Definition at line 370 of file PCLModules.cpp.
computeSurfaceNormals()
void PCLModules::FeatureCloud::computeSurfaceNormals () protected
Definition at line 364 of file PCLModules.cpp.
References PCLModules::ComputeNormals< PointT, NormalT >().
getLocalFeatures()
LocalFeatures::Ptr PCLModules::FeatureCloud::getLocalFeatures () const inline
Definition at line 1485 of file PCLModules.h.
Referenced by PCLModules::TemplateMatching::align(), and PCLModules::TemplateMatching::setTargetCloud().
getPointCloud()
PointCloudT::Ptr PCLModules::FeatureCloud::getPointCloud () const inline
Definition at line 1479 of file PCLModules.h.
Referenced by PCLModules::TemplateMatching::align(), TemplateAlignment::compute(), and PCLModules::TemplateMatching::setTargetCloud().
getSurfaceNormals()
SurfaceNormals::Ptr PCLModules::FeatureCloud::getSurfaceNormals () const inline
Definition at line 1482 of file PCLModules.h.
loadInputCloud()
void PCLModules::FeatureCloud::loadInputCloud (const std::string & pcd_file)
Definition at line 357 of file PCLModules.cpp.
References processInput().
processInput()
void PCLModules::FeatureCloud::processInput () inline protected
Definition at line 1489 of file PCLModules.h.
Referenced by loadInputCloud().
setFeatureRadius()
void PCLModules::FeatureCloud::setFeatureRadius (float featureRadius) inline
Definition at line 1462 of file PCLModules.h.
Referenced by TemplateAlignment::compute().
setInputCloud()
void PCLModules::FeatureCloud::setInputCloud (PointCloudT::Ptr xyz) inline
Definition at line 1470 of file PCLModules.h.
Referenced by TemplateAlignment::compute().
setmaxThreadCount()
void PCLModules::FeatureCloud::setmaxThreadCount (int maxThreadCount) inline
Definition at line 1465 of file PCLModules.h.
Referenced by TemplateAlignment::compute().
setNormalRadius()
void PCLModules::FeatureCloud::setNormalRadius (float normalRadius) inline
Definition at line 1461 of file PCLModules.h.
Referenced by TemplateAlignment::compute().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/PclUtils/PCLModules.h
/root/ACloudViewer/libs/PCLEngine/PclUtils/PCLModules.cpp