ACloudViewer: ccTopologyTool Class Reference
ccTopologyTool Class Reference
#include <ccTopologyTool.h>
Public Member Functions
ccTopologyTool ()
virtual ~ccTopologyTool ()
virtual void toolActivated () override
virtual void toolDisactivated () override
virtual void onNewSelection (const ccHObject::Container &selectedEntities) override
void accept () override
void cancel () override
Public Member Functions inherited from ccTool
virtual ~ccTool ()
void initializeTool (ecvMainAppInterface *app)
virtual void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccHObject *pickedObject, const CCVector3 &P)
virtual void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccPointCloud *cloud, const CCVector3 &P)
virtual bool canUndo ()
virtual void undo ()
Static Public Attributes
static int RELATIONSHIP = ccTopologyRelation::YOUNGER_THAN
Protected Attributes
int m_firstPick = -1
Protected Attributes inherited from ccTool
ecvMainAppInterface * m_app
QWidget * m_window
Additional Inherited Members
Protected Member Functions inherited from ccTool
ccTool ()
Detailed Description
Definition at line 21 of file ccTopologyTool.h.
Constructor & Destructor Documentation
ccTopologyTool()
ccTopologyTool::ccTopologyTool ()
Definition at line 14 of file ccTopologyTool.cpp.
~ccTopologyTool()
ccTopologyTool::~ccTopologyTool () virtual
Definition at line 16 of file ccTopologyTool.cpp.
Member Function Documentation
accept()
void ccTopologyTool::accept () override virtual
Reimplemented from ccTool.
Definition at line 67 of file ccTopologyTool.cpp.
References toolActivated(), and toolDisactivated().
Referenced by onNewSelection().
cancel()
void ccTopologyTool::cancel () override virtual
Reimplemented from ccTool.
Definition at line 76 of file ccTopologyTool.cpp.
References toolDisactivated().
onNewSelection()
void ccTopologyTool::onNewSelection (const ccHObject::Container & selectedEntities) override virtual
Reimplemented from ccTool.
Definition at line 19 of file ccTopologyTool.cpp.
References accept(), ccGeoObject::addRelationTo(), ecvDisplayTools::DisplayNewMessage(), ccGeoObject::getGeoObjectParent(), ccObject::getUniqueID(), ecvDisplayTools::LOWER_LEFT_MESSAGE, ccTool::m_app, m_firstPick, and RELATIONSHIP.
toolActivated()
void ccTopologyTool::toolActivated () override virtual
Reimplemented from ccTool.
Definition at line 55 of file ccTopologyTool.cpp.
References ecvDisplayTools::DisplayNewMessage(), and ecvDisplayTools::LOWER_LEFT_MESSAGE.
Referenced by accept().
toolDisactivated()
void ccTopologyTool::toolDisactivated () override virtual
Reimplemented from ccTool.
Definition at line 62 of file ccTopologyTool.cpp.
References m_firstPick.
Referenced by accept(), and cancel().
Member Data Documentation
m_firstPick
int ccTopologyTool::m_firstPick = -1 protected
Definition at line 43 of file ccTopologyTool.h.
Referenced by onNewSelection(), and toolDisactivated().
RELATIONSHIP
int ccTopologyTool::RELATIONSHIP = ccTopologyRelation::YOUNGER_THAN static
Definition at line 45 of file ccTopologyTool.h.
Referenced by onNewSelection(), ccCompass::setEquivalent(), ccCompass::setFollows(), and ccCompass::setYoungerThan().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCompass/include/ccTopologyTool.h
/root/ACloudViewer/plugins/core/Standard/qCompass/src/ccTopologyTool.cpp