ACloudViewer: cloudViewer::visualization::rendering::FilamentScene Class Reference
cloudViewer::visualization::rendering::FilamentScene Class Reference
#include <FilamentScene.h>
Public Member Functions
FilamentScene (filament::Engine &engine, FilamentResourceManager &resource_mgr, Renderer &renderer)
~FilamentScene ()
Scene * Copy () override
ViewHandle AddView (std::int32_t x, std::int32_t y, std::uint32_t w, std::uint32_t h) override
View * GetView (const ViewHandle &view_id) const override
void SetViewActive (const ViewHandle &view_id, bool is_active) override
void SetRenderOnce (const ViewHandle &view_id) override
void RemoveView (const ViewHandle &view_id) override
void AddCamera (const std::string &camera_name, std::shared_ptr< Camera > cam) override
void RemoveCamera (const std::string &camera_name) override
void SetActiveCamera (const std::string &camera_name) override
bool AddGeometry (const std::string &object_name, const ccHObject &geometry, const MaterialRecord &material, const std::string &downsampled_name="", size_t downsample_threshold=SIZE_MAX) override
bool AddGeometry (const std::string &object_name, const t::geometry::Geometry &geometry, const MaterialRecord &material, const std::string &downsampled_name="", size_t downsample_threshold=SIZE_MAX) override
bool AddGeometry (const std::string &object_name, const TriangleMeshModel &model) override
bool HasGeometry (const std::string &object_name) const override
void UpdateGeometry (const std::string &object_name, const t::geometry::PointCloud &point_cloud, uint32_t update_flags) override
void RemoveGeometry (const std::string &object_name) override
void ShowGeometry (const std::string &object_name, bool show) override
bool GeometryIsVisible (const std::string &object_name) override
void SetGeometryTransform (const std::string &object_name, const Transform &transform) override
Transform GetGeometryTransform (const std::string &object_name) override
ccBBox GetGeometryBoundingBox (const std::string &object_name) override
void GeometryShadows (const std::string &object_name, bool cast_shadows, bool receive_shadows) override
void SetGeometryCulling (const std::string &object_name, bool enable) override
void SetGeometryPriority (const std::string &object_name, uint8_t priority) override
void OverrideMaterial (const std::string &object_name, const MaterialRecord &material) override
void QueryGeometry (std::vector< std::string > &geometry) override
void OverrideMaterialAll (const MaterialRecord &material, bool shader_only=true) override
bool AddPointLight (const std::string &light_name, const Eigen::Vector3f &color, const Eigen::Vector3f &position, float intensity, float falloff, bool cast_shadows) override
bool AddSpotLight (const std::string &light_name, const Eigen::Vector3f &color, const Eigen::Vector3f &position, const Eigen::Vector3f &direction, float intensity, float falloff, float inner_cone_angle, float outer_cone_angle, bool cast_shadows) override
bool AddDirectionalLight (const std::string &light_name, const Eigen::Vector3f &color, const Eigen::Vector3f &direction, float intensity, bool cast_shadows) override
Light & GetLight (const std::string &light_name) override
void RemoveLight (const std::string &light_name) override
void UpdateLight (const std::string &light_name, const Light &light) override
void UpdateLightColor (const std::string &light_name, const Eigen::Vector3f &color) override
void UpdateLightPosition (const std::string &light_name, const Eigen::Vector3f &position) override
void UpdateLightDirection (const std::string &light_name, const Eigen::Vector3f &direction) override
void UpdateLightIntensity (const std::string &light_name, float intensity) override
void UpdateLightFalloff (const std::string &light_name, float falloff) override
void UpdateLightConeAngles (const std::string &light_name, float inner_cone_angle, float outer_cone_angle) override
void EnableLightShadow (const std::string &light_name, bool cast_shadows) override
void SetSunLight (const Eigen::Vector3f &direction, const Eigen::Vector3f &color, float intensity) override
void EnableSunLight (bool enable) override
void EnableSunLightShadows (bool enable) override
void SetSunLightColor (const Eigen::Vector3f &color) override
Eigen::Vector3f GetSunLightColor () override
void SetSunLightIntensity (float intensity) override
float GetSunLightIntensity () override
void SetSunLightDirection (const Eigen::Vector3f &direction) override
Eigen::Vector3f GetSunLightDirection () override
void SetSunAngularRadius (float radius) override
void SetSunHaloSize (float size) override
void SetSunHaloFalloff (float falloff) override
bool SetIndirectLight (const std::string &ibl_name) override
const std::string & GetIndirectLight () override
void EnableIndirectLight (bool enable) override
void SetIndirectLightIntensity (float intensity) override
float GetIndirectLightIntensity () override
void SetIndirectLightRotation (const Transform &rotation) override
Transform GetIndirectLightRotation () override
void ShowSkybox (bool show) override
bool GetSkyboxVisible () const override
void SetBackground (const Eigen::Vector4f &color, const std::shared_ptr< geometry::Image > image=nullptr) override
void SetBackground (TextureHandle image) override
void EnableGroundPlane (bool enable, GroundPlane plane) override
void SetGroundPlaneColor (const Eigen::Vector4f &color) override
void RenderToImage (std::function< void(std::shared_ptr< geometry::Image >)> callback) override
Size of image is the size of the window.
void RenderToDepthImage (std::function< void(std::shared_ptr< geometry::Image >)> callback) override
Size of image is the size of the window.
void Draw (filament::Renderer &renderer)
void HideRefractedMaterials (bool hide=true)
filament::Scene * GetNativeScene () const
Public Member Functions inherited from cloudViewer::visualization::rendering::Scene
Scene (Renderer &renderer)
virtual ~Scene ()=default
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::rendering::Scene
enum class GroundPlane { XZ , XY , YZ }
using Transform = Eigen::Transform< float, 3, Eigen::Affine >
Static Public Attributes inherited from cloudViewer::visualization::rendering::Scene
static const uint32_t kUpdatePointsFlag = (1 << 0)
static const uint32_t kUpdateNormalsFlag = (1 << 1)
static const uint32_t kUpdateColorsFlag = (1 << 2)
static const uint32_t kUpdateUv0Flag = (1 << 3)
Protected Attributes inherited from cloudViewer::visualization::rendering::Scene
Renderer & renderer_
Detailed Description
Definition at line 68 of file FilamentScene.h.
Constructor & Destructor Documentation
FilamentScene()
cloudViewer::visualization::rendering::FilamentScene::FilamentScene (filament::Engine & engine, FilamentResourceManager & resource_mgr, Renderer & renderer)
Definition at line 151 of file FilamentScene.cpp.
Referenced by Copy().
~FilamentScene()
cloudViewer::visualization::rendering::FilamentScene::~FilamentScene ()
Definition at line 162 of file FilamentScene.cpp.
References cloudViewer::visualization::rendering::FilamentResourceManager::Destroy().
Member Function Documentation
AddCamera()
void cloudViewer::visualization::rendering::FilamentScene::AddCamera (const std::string & camera_name, std::shared_ptr< Camera > cam) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 287 of file FilamentScene.cpp.
AddDirectionalLight()
bool cloudViewer::visualization::rendering::FilamentScene::AddDirectionalLight (const std::string & light_name, const Eigen::Vector3f & color, const Eigen::Vector3f & direction, float intensity, bool cast_shadows) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1329 of file FilamentScene.cpp.
References color, ecvColor::light(), LogWarning, cloudViewer::core::make_pair(), and result.
AddGeometry() [1/3]
bool cloudViewer::visualization::rendering::FilamentScene::AddGeometry (const std::string & object_name, const ccHObject & geometry, const MaterialRecord & material, const std::string & downsampled_name = "", size_t downsample_threshold = SIZE_MAX) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 309 of file FilamentScene.cpp.
References cloudViewer::visualization::rendering::GeometryBuffersBuilder::GetBuilder(), ccHObject::getClassID(), ib, ccHObject::IsEmpty(), LogDebug, LogWarning, cloudViewer::visualization::rendering::MaterialRecord::shader, cloudViewer::visualization::rendering::MaterialRecord::sRGB_color, and vb.
Referenced by AddGeometry().
AddGeometry() [2/3]
bool cloudViewer::visualization::rendering::FilamentScene::AddGeometry (const std::string & object_name, const t::geometry::Geometry & geometry, const MaterialRecord & material, const std::string & downsampled_name = "", size_t downsample_threshold = SIZE_MAX) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 370 of file FilamentScene.cpp.
References cloudViewer::visualization::rendering::GeometryBuffersBuilder::GetBuilder(), ib, cloudViewer::t::geometry::Geometry::IsEmpty(), LogWarning, cloudViewer::visualization::rendering::MaterialRecord::shader, cloudViewer::visualization::rendering::MaterialRecord::sRGB_color, and vb.
AddGeometry() [3/3]
bool cloudViewer::visualization::rendering::FilamentScene::AddGeometry (const std::string & object_name, const TriangleMeshModel & model) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 444 of file FilamentScene.cpp.
References AddGeometry(), LogWarning, cloudViewer::visualization::rendering::TriangleMeshModel::materials_, cloudViewer::visualization::rendering::TriangleMeshModel::meshes_, and patch::to_string().
AddPointLight()
bool cloudViewer::visualization::rendering::FilamentScene::AddPointLight (const std::string & light_name, const Eigen::Vector3f & color, const Eigen::Vector3f & position, float intensity, float falloff, bool cast_shadows) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1251 of file FilamentScene.cpp.
References color, ecvColor::light(), LogWarning, cloudViewer::core::make_pair(), position, and result.
AddSpotLight()
bool cloudViewer::visualization::rendering::FilamentScene::AddSpotLight (const std::string & light_name, const Eigen::Vector3f & color, const Eigen::Vector3f & position, const Eigen::Vector3f & direction, float intensity, float falloff, float inner_cone_angle, float outer_cone_angle, bool cast_shadows) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1287 of file FilamentScene.cpp.
References color, ecvColor::light(), LogWarning, cloudViewer::core::make_pair(), position, and result.
AddView()
ViewHandle cloudViewer::visualization::rendering::FilamentScene::AddView (std::int32_t x, std::int32_t y, std::uint32_t w, std::uint32_t h) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 239 of file FilamentScene.cpp.
References cloudViewer::visualization::rendering::View::DepthAndStencil, and cloudViewer::visualization::rendering::REHandle< EntityType::View >::Next().
Referenced by cloudViewer::visualization::gui::ImguiFilamentBridge::ImguiFilamentBridge().
Copy()
Scene * cloudViewer::visualization::rendering::FilamentScene::Copy () override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 178 of file FilamentScene.cpp.
References copy, FilamentScene(), GetGeometryTransform(), cloudViewer::visualization::rendering::FilamentView::kAllLayersMask, cloudViewer::visualization::rendering::FilamentView::kMainLayer, LogWarning, name, cloudViewer::visualization::rendering::Scene::renderer_, and result.
Draw()
void cloudViewer::visualization::rendering::FilamentScene::Draw (filament::Renderer & renderer)
Definition at line 1934 of file FilamentScene.cpp.
EnableGroundPlane()
void cloudViewer::visualization::rendering::FilamentScene::EnableGroundPlane (bool enable, GroundPlane plane) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1805 of file FilamentScene.cpp.
References cloudViewer::visualization::rendering::MaterialRecord::base_color, cloudViewer::visualization::rendering::MaterialRecord::ground_plane_axis, HasGeometry(), OverrideMaterial(), cloudViewer::visualization::rendering::MaterialRecord::shader, ShowGeometry(), cloudViewer::visualization::rendering::Scene::XY, and cloudViewer::visualization::rendering::Scene::YZ.
EnableIndirectLight()
void cloudViewer::visualization::rendering::FilamentScene::EnableIndirectLight (bool enable) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1619 of file FilamentScene.cpp.
References ecvColor::light().
EnableLightShadow()
void cloudViewer::visualization::rendering::FilamentScene::EnableLightShadow (const std::string & light_name, bool cast_shadows) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1449 of file FilamentScene.cpp.
References ecvColor::light().
EnableSunLight()
void cloudViewer::visualization::rendering::FilamentScene::EnableSunLight (bool enable) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1491 of file FilamentScene.cpp.
EnableSunLightShadows()
void cloudViewer::visualization::rendering::FilamentScene::EnableSunLightShadows (bool enable) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1502 of file FilamentScene.cpp.
GeometryIsVisible()
bool cloudViewer::visualization::rendering::FilamentScene::GeometryIsVisible (const std::string & object_name) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 702 of file FilamentScene.cpp.
GeometryShadows()
void cloudViewer::visualization::rendering::FilamentScene::GeometryShadows (const std::string & object_name, bool cast_shadows, bool receive_shadows) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 781 of file FilamentScene.cpp.
GetGeometryBoundingBox()
ccBBox cloudViewer::visualization::rendering::FilamentScene::GetGeometryBoundingBox (const std::string & object_name) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 759 of file FilamentScene.cpp.
References max(), min(), and result.
GetGeometryTransform()
FilamentScene::Transform cloudViewer::visualization::rendering::FilamentScene::GetGeometryTransform (const std::string & object_name) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 744 of file FilamentScene.cpp.
Referenced by Copy().
GetIndirectLight()
const std::string & cloudViewer::visualization::rendering::FilamentScene::GetIndirectLight () override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1617 of file FilamentScene.cpp.
GetIndirectLightIntensity()
float cloudViewer::visualization::rendering::FilamentScene::GetIndirectLightIntensity () override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1638 of file FilamentScene.cpp.
References ecvColor::light().
GetIndirectLightRotation()
FilamentScene::Transform cloudViewer::visualization::rendering::FilamentScene::GetIndirectLightRotation () override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1652 of file FilamentScene.cpp.
References ecvColor::light().
GetLight()
Light & cloudViewer::visualization::rendering::FilamentScene::GetLight (const std::string & light_name) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1364 of file FilamentScene.cpp.
GetNativeScene()
filament::Scene* cloudViewer::visualization::rendering::FilamentScene::GetNativeScene () const inline
Definition at line 219 of file FilamentScene.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::FilamentView(), and cloudViewer::visualization::rendering::FilamentView::SetScene().
GetSkyboxVisible()
bool cloudViewer::visualization::rendering::FilamentScene::GetSkyboxVisible () const override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1676 of file FilamentScene.cpp.
GetSunLightColor()
Eigen::Vector3f cloudViewer::visualization::rendering::FilamentScene::GetSunLightColor () override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1530 of file FilamentScene.cpp.
GetSunLightDirection()
Eigen::Vector3f cloudViewer::visualization::rendering::FilamentScene::GetSunLightDirection () override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1566 of file FilamentScene.cpp.
GetSunLightIntensity()
float cloudViewer::visualization::rendering::FilamentScene::GetSunLightIntensity () override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1516 of file FilamentScene.cpp.
GetView()
View * cloudViewer::visualization::rendering::FilamentScene::GetView (const ViewHandle & view_id) const override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 258 of file FilamentScene.cpp.
HasGeometry()
bool cloudViewer::visualization::rendering::FilamentScene::HasGeometry (const std::string & object_name) const override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 532 of file FilamentScene.cpp.
Referenced by EnableGroundPlane(), and SetGroundPlaneColor().
HideRefractedMaterials()
void cloudViewer::visualization::rendering::FilamentScene::HideRefractedMaterials (bool hide = true)
Definition at line 1950 of file FilamentScene.cpp.
References ShowGeometry().
Referenced by cloudViewer::visualization::rendering::FilamentRenderToBuffer::Render().
OverrideMaterial()
void cloudViewer::visualization::rendering::FilamentScene::OverrideMaterial (const std::string & object_name, const MaterialRecord & material) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1227 of file FilamentScene.cpp.
Referenced by EnableGroundPlane(), and SetBackground().
OverrideMaterialAll()
void cloudViewer::visualization::rendering::FilamentScene::OverrideMaterialAll (const MaterialRecord & material, bool shader_only = true) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1241 of file FilamentScene.cpp.
QueryGeometry()
void cloudViewer::visualization::rendering::FilamentScene::QueryGeometry (std::vector< std::string > & geometry) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1235 of file FilamentScene.cpp.
RemoveCamera()
void cloudViewer::visualization::rendering::FilamentScene::RemoveCamera (const std::string & camera_name) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 290 of file FilamentScene.cpp.
RemoveGeometry()
void cloudViewer::visualization::rendering::FilamentScene::RemoveGeometry (const std::string & object_name) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 673 of file FilamentScene.cpp.
RemoveLight()
void cloudViewer::visualization::rendering::FilamentScene::RemoveLight (const std::string & light_name) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1375 of file FilamentScene.cpp.
References ecvColor::light().
RemoveView()
void cloudViewer::visualization::rendering::FilamentScene::RemoveView (const ViewHandle & view_id) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 283 of file FilamentScene.cpp.
RenderToDepthImage()
void cloudViewer::visualization::rendering::FilamentScene::RenderToDepthImage (std::function< void(std::shared_ptr< geometry::Image >)> callback) override virtual
Size of image is the size of the window.
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1856 of file FilamentScene.cpp.
References callback, cloudViewer::visualization::rendering::Scene::renderer_, and cloudViewer::visualization::rendering::Renderer::RenderToDepthImage().
RenderToImage()
void cloudViewer::visualization::rendering::FilamentScene::RenderToImage (std::function< void(std::shared_ptr< geometry::Image >)> callback) override virtual
Size of image is the size of the window.
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1850 of file FilamentScene.cpp.
References callback, cloudViewer::visualization::rendering::Scene::renderer_, and cloudViewer::visualization::rendering::Renderer::RenderToImage().
SetActiveCamera()
void cloudViewer::visualization::rendering::FilamentScene::SetActiveCamera (const std::string & camera_name) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 292 of file FilamentScene.cpp.
SetBackground() [1/2]
void cloudViewer::visualization::rendering::FilamentScene::SetBackground (const Eigen::Vector4f & color, const std::shared_ptr< geometry::Image > image = nullptr) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1714 of file FilamentScene.cpp.
References cloudViewer::visualization::rendering::MaterialRecord::albedo_img, cloudViewer::visualization::rendering::MaterialRecord::aspect_ratio, cloudViewer::visualization::rendering::MaterialRecord::base_color, color, cloudViewer::visualization::rendering::FilamentResourceManager::Destroy(), image, cloudViewer::visualization::rendering::FilamentResourceManager::kDefaultTexture, OverrideMaterial(), cloudViewer::visualization::rendering::MaterialRecord::shader, and cloudViewer::visualization::rendering::FilamentResourceManager::UpdateTexture().
SetBackground() [2/2]
void cloudViewer::visualization::rendering::FilamentScene::SetBackground (TextureHandle image) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1763 of file FilamentScene.cpp.
References cloudViewer::visualization::rendering::FilamentResourceManager::GetTexture(), image, cloudViewer::visualization::rendering::TextureSamplerParameters::LinearClamp(), cloudViewer::visualization::rendering::Renderer::ModifyMaterial(), cloudViewer::visualization::rendering::Scene::renderer_, cloudViewer::visualization::rendering::MaterialModifier::SetParameter(), and cloudViewer::visualization::rendering::MaterialModifier::SetTexture().
SetGeometryCulling()
void cloudViewer::visualization::rendering::FilamentScene::SetGeometryCulling (const std::string & object_name, bool enable) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 794 of file FilamentScene.cpp.
SetGeometryPriority()
void cloudViewer::visualization::rendering::FilamentScene::SetGeometryPriority (const std::string & object_name, uint8_t priority) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 806 of file FilamentScene.cpp.
SetGeometryTransform()
void cloudViewer::visualization::rendering::FilamentScene::SetGeometryTransform (const std::string & object_name, const Transform & transform) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 729 of file FilamentScene.cpp.
SetGroundPlaneColor()
void cloudViewer::visualization::rendering::FilamentScene::SetGroundPlaneColor (const Eigen::Vector4f & color) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1824 of file FilamentScene.cpp.
References HasGeometry().
SetIndirectLight()
bool cloudViewer::visualization::rendering::FilamentScene::SetIndirectLight (const std::string & ibl_name) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1574 of file FilamentScene.cpp.
References cloudViewer::visualization::rendering::Renderer::AddIndirectLight(), cloudViewer::visualization::rendering::Renderer::AddSkybox(), cloudViewer::visualization::rendering::FilamentResourceManager::Destroy(), cloudViewer::visualization::rendering::FilamentResourceManager::GetIndirectLight(), cloudViewer::visualization::rendering::FilamentResourceManager::GetSkybox(), ecvColor::light(), cloudViewer::visualization::rendering::Scene::renderer_, and ShowSkybox().
SetIndirectLightIntensity()
void cloudViewer::visualization::rendering::FilamentScene::SetIndirectLightIntensity (float intensity) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1632 of file FilamentScene.cpp.
References ecvColor::light().
SetIndirectLightRotation()
void cloudViewer::visualization::rendering::FilamentScene::SetIndirectLightRotation (const Transform & rotation) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1645 of file FilamentScene.cpp.
References ecvColor::light().
SetRenderOnce()
void cloudViewer::visualization::rendering::FilamentScene::SetRenderOnce (const ViewHandle & view_id) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 275 of file FilamentScene.cpp.
SetSunAngularRadius()
void cloudViewer::visualization::rendering::FilamentScene::SetSunAngularRadius (float radius) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1545 of file FilamentScene.cpp.
SetSunHaloFalloff()
void cloudViewer::visualization::rendering::FilamentScene::SetSunHaloFalloff (float falloff) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1559 of file FilamentScene.cpp.
SetSunHaloSize()
void cloudViewer::visualization::rendering::FilamentScene::SetSunHaloSize (float size) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1552 of file FilamentScene.cpp.
References size.
SetSunLight()
void cloudViewer::visualization::rendering::FilamentScene::SetSunLight (const Eigen::Vector3f & direction, const Eigen::Vector3f & color, float intensity) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1480 of file FilamentScene.cpp.
References color.
SetSunLightColor()
void cloudViewer::visualization::rendering::FilamentScene::SetSunLightColor (const Eigen::Vector3f & color) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1523 of file FilamentScene.cpp.
References color.
SetSunLightDirection()
void cloudViewer::visualization::rendering::FilamentScene::SetSunLightDirection (const Eigen::Vector3f & direction) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1538 of file FilamentScene.cpp.
SetSunLightIntensity()
void cloudViewer::visualization::rendering::FilamentScene::SetSunLightIntensity (float intensity) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1509 of file FilamentScene.cpp.
SetViewActive()
void cloudViewer::visualization::rendering::FilamentScene::SetViewActive (const ViewHandle & view_id, bool is_active) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 267 of file FilamentScene.cpp.
ShowGeometry()
void cloudViewer::visualization::rendering::FilamentScene::ShowGeometry (const std::string & object_name, bool show) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 688 of file FilamentScene.cpp.
Referenced by EnableGroundPlane(), HideRefractedMaterials(), and ShowSkybox().
ShowSkybox()
void cloudViewer::visualization::rendering::FilamentScene::ShowSkybox (bool show) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1662 of file FilamentScene.cpp.
References ShowGeometry().
Referenced by SetIndirectLight().
UpdateGeometry()
void cloudViewer::visualization::rendering::FilamentScene::UpdateGeometry (const std::string & object_name, const t::geometry::PointCloud & point_cloud, uint32_t update_flags) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 540 of file FilamentScene.cpp.
References cloudViewer::t::geometry::PointCloud::CPU(), cloudViewer::core::Device::CUDA, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointColors(), cloudViewer::t::geometry::PointCloud::GetPointNormals(), cloudViewer::t::geometry::PointCloud::GetPoints(), cloudViewer::visualization::rendering::FilamentResourceManager::GetVertexBuffer(), cloudViewer::t::geometry::PointCloud::HasPointAttr(), cloudViewer::t::geometry::PointCloud::HasPointColors(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), cloudViewer::visualization::rendering::Scene::kUpdateColorsFlag, cloudViewer::visualization::rendering::Scene::kUpdateNormalsFlag, cloudViewer::visualization::rendering::Scene::kUpdatePointsFlag, cloudViewer::visualization::rendering::Scene::kUpdateUv0Flag, LogWarning, normals, and points.
UpdateLight()
void cloudViewer::visualization::rendering::FilamentScene::UpdateLight (const std::string & light_name, const Light & light) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1370 of file FilamentScene.cpp.
UpdateLightColor()
void cloudViewer::visualization::rendering::FilamentScene::UpdateLightColor (const std::string & light_name, const Eigen::Vector3f & color) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1384 of file FilamentScene.cpp.
References color, and ecvColor::light().
UpdateLightConeAngles()
void cloudViewer::visualization::rendering::FilamentScene::UpdateLightConeAngles (const std::string & light_name, float inner_cone_angle, float outer_cone_angle) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1443 of file FilamentScene.cpp.
UpdateLightDirection()
void cloudViewer::visualization::rendering::FilamentScene::UpdateLightDirection (const std::string & light_name, const Eigen::Vector3f & direction) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1409 of file FilamentScene.cpp.
References ecvColor::light().
UpdateLightFalloff()
void cloudViewer::visualization::rendering::FilamentScene::UpdateLightFalloff (const std::string & light_name, float falloff) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1432 of file FilamentScene.cpp.
References ecvColor::light().
UpdateLightIntensity()
void cloudViewer::visualization::rendering::FilamentScene::UpdateLightIntensity (const std::string & light_name, float intensity) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1421 of file FilamentScene.cpp.
References ecvColor::light().
UpdateLightPosition()
void cloudViewer::visualization::rendering::FilamentScene::UpdateLightPosition (const std::string & light_name, const Eigen::Vector3f & position) override virtual
Implements cloudViewer::visualization::rendering::Scene.
Definition at line 1395 of file FilamentScene.cpp.
References ecvColor::light(), and position.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentScene.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentScene.cpp