ACloudViewer: colmap::RigBundleAdjustmentCostFunction< CameraModel > Class Template Reference
colmap::RigBundleAdjustmentCostFunction< CameraModel > Class Template Reference
#include <cost_functions.h>
Public Member Functions
RigBundleAdjustmentCostFunction (const Eigen::Vector2d &point2D)
template<typename T >
bool operator() (const T *const rig_qvec, const T *const rig_tvec, const T *const rel_qvec, const T *const rel_tvec, const T *const point3D, const T *const camera_params, T *residuals) const
Static Public Member Functions
static ceres::CostFunction * Create (const Eigen::Vector2d &point2D)
Detailed Description
template<typename CameraModel>
class colmap::RigBundleAdjustmentCostFunction< CameraModel >
Definition at line 140 of file cost_functions.h.
Constructor & Destructor Documentation
RigBundleAdjustmentCostFunction()
template<typename CameraModel > colmap::RigBundleAdjustmentCostFunction< CameraModel >::RigBundleAdjustmentCostFunction (const Eigen::Vector2d & point2D) inline explicit
Definition at line 142 of file cost_functions.h.
Referenced by colmap::RigBundleAdjustmentCostFunction< CameraModel >::Create().
Member Function Documentation
Create()
template<typename CameraModel > static ceres::CostFunction* colmap::RigBundleAdjustmentCostFunction< CameraModel >::Create (const Eigen::Vector2d & point2D) inline static
Definition at line 145 of file cost_functions.h.
References colmap::RigBundleAdjustmentCostFunction< CameraModel >::RigBundleAdjustmentCostFunction().
Referenced by BOOST_AUTO_TEST_CASE().
operator()()
template<typename CameraModel > template<typename T > bool colmap::RigBundleAdjustmentCostFunction< CameraModel >::operator() (const T *const rig_qvec, const T *const rig_tvec, const T *const rel_qvec, const T *const rel_tvec, const T *const point3D, const T *const camera_params, T * residuals) const inline
Definition at line 153 of file cost_functions.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/base/cost_functions.h