ACloudViewer: cloudViewer::visualization::gui::WindowSystem Class Reference
cloudViewer::visualization::gui::WindowSystem Class Reference abstract
#include <WindowSystem.h>
Public Types
using OSWindow = void *
Public Member Functions
virtual ~WindowSystem ()
virtual void Initialize ()=0
virtual void Uninitialize ()=0
virtual void WaitEventsTimeout (double timeout_secs)=0
virtual Size GetScreenSize (OSWindow w)=0
virtual OSWindow CreateOSWindow (Window *o3d_window, int width, int height, const char *title, int flags)=0
virtual void DestroyWindow (OSWindow w)=0
virtual void PostRedrawEvent (OSWindow w)=0
virtual bool GetWindowIsVisible (OSWindow w) const =0
virtual void ShowWindow (OSWindow w, bool show)=0
virtual void RaiseWindowToTop (OSWindow w)=0
virtual bool IsActiveWindow (OSWindow w) const =0
virtual Point GetWindowPos (OSWindow w) const =0
virtual void SetWindowPos (OSWindow w, int x, int y)=0
virtual Size GetWindowSize (OSWindow w) const =0
virtual void SetWindowSize (OSWindow w, int width, int height)=0
virtual Size GetWindowSizePixels (OSWindow w) const =0
virtual void SetWindowSizePixels (OSWindow w, const Size &size)=0
virtual float GetWindowScaleFactor (OSWindow w) const =0
virtual float GetUIScaleFactor (OSWindow w) const =0
virtual void SetWindowTitle (OSWindow w, const char *title)=0
virtual Point GetMousePosInWindow (OSWindow w) const =0
virtual int GetMouseButtons (OSWindow w) const =0
virtual void CancelUserClose (OSWindow w)=0
virtual void * GetNativeDrawable (OSWindow w)=0
virtual rendering::FilamentRenderer * CreateRenderer (OSWindow w)=0
virtual void ResizeRenderer (OSWindow w, rendering::FilamentRenderer *renderer)=0
virtual MenuBase * CreateOSMenu ()=0
Static Public Attributes
static constexpr int FLAG_VISIBLE = 0
static constexpr int FLAG_HIDDEN = (1 << 0)
static constexpr int FLAG_TOPMOST = (1 << 1)
Detailed Description
WindowSystem (and its derived classes) are internal to CloudViewer and not intended to be used directly. Internal users should get the WindowSystem object using Application::GetInstance().GetWindowSystem().
Definition at line 27 of file WindowSystem.h.
Member Typedef Documentation
OSWindow
using cloudViewer::visualization::gui::WindowSystem::OSWindow = void*
Definition at line 29 of file WindowSystem.h.
Constructor & Destructor Documentation
~WindowSystem()
virtual cloudViewer::visualization::gui::WindowSystem::~WindowSystem () inline virtual
Definition at line 31 of file WindowSystem.h.
Member Function Documentation
CancelUserClose()
virtual void cloudViewer::visualization::gui::WindowSystem::CancelUserClose (OSWindow w) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::Close().
CreateOSMenu()
virtual MenuBase* cloudViewer::visualization::gui::WindowSystem::CreateOSMenu () pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
CreateOSWindow()
virtual OSWindow cloudViewer::visualization::gui::WindowSystem::CreateOSWindow (Window * o3d_window, int width, int height, const char * title, int flags) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, cloudViewer::visualization::gui::BitmapWindowSystem, and cloudViewer::visualization::webrtc_server::WebRTCWindowSystem.
CreateRenderer()
virtual rendering::FilamentRenderer* cloudViewer::visualization::gui::WindowSystem::CreateRenderer (OSWindow w) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
DestroyWindow()
virtual void cloudViewer::visualization::gui::WindowSystem::DestroyWindow (OSWindow w) pure virtual
Implemented in cloudViewer::visualization::webrtc_server::WebRTCWindowSystem, cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::DestroyWindow().
GetMouseButtons()
virtual int cloudViewer::visualization::gui::WindowSystem::GetMouseButtons (OSWindow w) const pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
GetMousePosInWindow()
virtual Point cloudViewer::visualization::gui::WindowSystem::GetMousePosInWindow (OSWindow w) const pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
GetNativeDrawable()
virtual void* cloudViewer::visualization::gui::WindowSystem::GetNativeDrawable (OSWindow w) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
GetScreenSize()
virtual Size cloudViewer::visualization::gui::WindowSystem::GetScreenSize (OSWindow w) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::OnResize().
GetUIScaleFactor()
virtual float cloudViewer::visualization::gui::WindowSystem::GetUIScaleFactor (OSWindow w) const pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
GetWindowIsVisible()
virtual bool cloudViewer::visualization::gui::WindowSystem::GetWindowIsVisible (OSWindow w) const pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::IsVisible().
GetWindowPos()
virtual Point cloudViewer::visualization::gui::WindowSystem::GetWindowPos (OSWindow w) const pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::GetOSFrame(), and cloudViewer::visualization::gui::Window::GlobalToWindowCoord().
GetWindowScaleFactor()
virtual float cloudViewer::visualization::gui::WindowSystem::GetWindowScaleFactor (OSWindow w) const pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::GetScaling().
GetWindowSize()
virtual Size cloudViewer::visualization::gui::WindowSystem::GetWindowSize (OSWindow w) const pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
GetWindowSizePixels()
virtual Size cloudViewer::visualization::gui::WindowSystem::GetWindowSizePixels (OSWindow w) const pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::GetSize().
Initialize()
virtual void cloudViewer::visualization::gui::WindowSystem::Initialize () pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
IsActiveWindow()
virtual bool cloudViewer::visualization::gui::WindowSystem::IsActiveWindow (OSWindow w) const pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::IsActiveWindow().
PostRedrawEvent()
virtual void cloudViewer::visualization::gui::WindowSystem::PostRedrawEvent (OSWindow w) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::PostRedraw().
RaiseWindowToTop()
virtual void cloudViewer::visualization::gui::WindowSystem::RaiseWindowToTop (OSWindow w) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::RaiseToTop().
ResizeRenderer()
virtual void cloudViewer::visualization::gui::WindowSystem::ResizeRenderer (OSWindow w, rendering::FilamentRenderer * renderer) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::OnResize().
SetWindowPos()
virtual void cloudViewer::visualization::gui::WindowSystem::SetWindowPos (OSWindow w, int x, int y) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::SetOSFrame().
SetWindowSize()
virtual void cloudViewer::visualization::gui::WindowSystem::SetWindowSize (OSWindow w, int width, int height) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::SetSize().
SetWindowSizePixels()
virtual void cloudViewer::visualization::gui::WindowSystem::SetWindowSizePixels (OSWindow w, const Size & size) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
SetWindowTitle()
virtual void cloudViewer::visualization::gui::WindowSystem::SetWindowTitle (OSWindow w, const char * title) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::SetTitle().
ShowWindow()
virtual void cloudViewer::visualization::gui::WindowSystem::ShowWindow (OSWindow w, bool show) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Referenced by cloudViewer::visualization::gui::Window::Show().
Uninitialize()
virtual void cloudViewer::visualization::gui::WindowSystem::Uninitialize () pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
WaitEventsTimeout()
virtual void cloudViewer::visualization::gui::WindowSystem::WaitEventsTimeout (double timeout_secs) pure virtual
Implemented in cloudViewer::visualization::gui::GLFWWindowSystem, and cloudViewer::visualization::gui::BitmapWindowSystem.
Member Data Documentation
FLAG_HIDDEN
constexpr int cloudViewer::visualization::gui::WindowSystem::FLAG_HIDDEN = (1 << 0) static constexpr
Definition at line 41 of file WindowSystem.h.
Referenced by cloudViewer::visualization::gui::GLFWWindowSystem::CreateOSWindow(), and cloudViewer::visualization::gui::Window::Window().
FLAG_TOPMOST
constexpr int cloudViewer::visualization::gui::WindowSystem::FLAG_TOPMOST = (1 << 1) static constexpr
Definition at line 42 of file WindowSystem.h.
Referenced by cloudViewer::visualization::gui::GLFWWindowSystem::CreateOSWindow(), and cloudViewer::visualization::gui::Window::Window().
FLAG_VISIBLE
constexpr int cloudViewer::visualization::gui::WindowSystem::FLAG_VISIBLE = 0 static constexpr
Definition at line 40 of file WindowSystem.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/WindowSystem.h