ACloudViewer: Jacobi< Scalar > Class Template Reference
Jacobi< Scalar > Class Template Reference
Jacobi eigen vectors/values decomposition.
#include <Jacobi.h>
Public Types
using SquareMatrix = cloudViewer::SquareMatrixTpl< Scalar >
using EigenValues = std::vector< Scalar >
Static Public Member Functions
static bool ComputeEigenValuesAndVectors2 (const SquareMatrix &matrix, SquareMatrix &eigenVectors, EigenValues &eigenValues, unsigned maxIterationCount=50)
Computes the eigenvalues and eigenvectors of a given square matrix.
static bool ComputeEigenValuesAndVectors (const SquareMatrix &matrix, SquareMatrix &eigenVectors, EigenValues &eigenValues, bool absoluteValues=true, unsigned maxIterationCount=50)
Computes eigen vectors (and values) with the Jacobian method.
static bool SortEigenValuesAndVectors (SquareMatrix &eigenVectors, EigenValues &eigenValues)
static bool GetEigenVector (const SquareMatrix &eigenVectors, unsigned index, Scalar eigenVector[])
Returns the given eigenvector.
static bool GetMaxEigenValueAndVector (const SquareMatrix &eigenVectors, const EigenValues &eigenValues, Scalar &maxEigenValue, Scalar maxEigenVector[])
Returns the biggest eigenvalue and its associated eigenvector.
static bool GetMinEigenValueAndVector (const SquareMatrix &eigenVectors, const EigenValues &eigenValues, Scalar &minEigenValue, Scalar minEigenVector[])
Returns the smallest eigenvalue and its associated eigenvector.
Detailed Description
template<typename Scalar>
class Jacobi< Scalar >
Jacobi eigen vectors/values decomposition.
Definition at line 23 of file Jacobi.h.
Member Typedef Documentation
EigenValues
template<typename Scalar > using Jacobi< Scalar >::EigenValues = std::vector<Scalar>
Definition at line 26 of file Jacobi.h.
SquareMatrix
template<typename Scalar > using Jacobi< Scalar >::SquareMatrix = cloudViewer::SquareMatrixTpl<Scalar>
Definition at line 25 of file Jacobi.h.
Member Function Documentation
ComputeEigenValuesAndVectors()
template<typename Scalar > static bool Jacobi< Scalar >::ComputeEigenValuesAndVectors (const SquareMatrix & matrix, SquareMatrix & eigenVectors, EigenValues & eigenValues, bool absoluteValues = true, unsigned maxIterationCount = 50) inline static
Computes eigen vectors (and values) with the Jacobian method.
See the Numerical Recipes.
Definition at line 183 of file Jacobi.h.
References abs(), cloudViewer::SquareMatrixTpl< Scalar >::isValid(), cloudViewer::SquareMatrixTpl< Scalar >::m_values, ROTATE, cloudViewer::SquareMatrixTpl< Scalar >::size(), and cloudViewer::SquareMatrixTpl< Scalar >::toIdentity().
Referenced by ccCompass::estimateStrain(), and ccCompass::estimateStructureNormals().
ComputeEigenValuesAndVectors2()
template<typename Scalar > static bool Jacobi< Scalar >::ComputeEigenValuesAndVectors2 (const SquareMatrix & matrix, SquareMatrix & eigenVectors, EigenValues & eigenValues, unsigned maxIterationCount = 50) inline static
Computes the eigenvalues and eigenvectors of a given square matrix.
It uses Rutishauser's modfications of the classical Jacobi rotation method with threshold pivoting.
 Note: this code is inspired from John Burkardt's 'jacobi_eigenvalue'
code See https://people.sc.fsu.edu/~jburkardt/cpp_src/jacobi_eigenvalue/jacobi_eigenvalue.cpp
 \warning DGM: this method gives strange results in some particular
cases!!!
 \param[in] matrix input square matrix
 \param[out] eigenVectors eigenvectors (as a square matrix)
 \param[out] eigenValues eigenvalues
 \param[in] maxIterationCount max number of iteration (optional)
 \return success
Definition at line 45 of file Jacobi.h.
References cloudViewer::SquareMatrixTpl< Scalar >::isValid(), cloudViewer::SquareMatrixTpl< Scalar >::m_values, cloudViewer::SquareMatrixTpl< Scalar >::size(), and cloudViewer::SquareMatrixTpl< Scalar >::toIdentity().
GetEigenVector()
template<typename Scalar > static bool Jacobi< Scalar >::GetEigenVector (const SquareMatrix & eigenVectors, unsigned index, Scalar eigenVector[]) inline static
Returns the given eigenvector.
Parameters
eigenVectors eigenvectors (as a square matrix)
index requested eigenvector index (< eigenvectors matrix size)
eigenVector output vector (size = matrix size)
Returns
success
Definition at line 364 of file Jacobi.h.
References cloudViewer::SquareMatrixTpl< Scalar >::m_values, and cloudViewer::SquareMatrixTpl< Scalar >::size().
Referenced by Jacobi< Scalar >::GetMaxEigenValueAndVector(), and Jacobi< Scalar >::GetMinEigenValueAndVector().
GetMaxEigenValueAndVector()
template<typename Scalar > static bool Jacobi< Scalar >::GetMaxEigenValueAndVector (const SquareMatrix & eigenVectors, const EigenValues & eigenValues, Scalar & maxEigenValue, Scalar maxEigenVector[]) inline static
Returns the biggest eigenvalue and its associated eigenvector.
Parameters
eigenVectors eigenvectors (as a square matrix)
eigenValues eigenvalues
maxEigenValue biggest eigenvalue
maxEigenVector eigenvector vector corresponding to the biggest eigenvalue
Returns
success
Definition at line 385 of file Jacobi.h.
References Jacobi< Scalar >::GetEigenVector(), cloudViewer::SquareMatrixTpl< Scalar >::isValid(), and cloudViewer::SquareMatrixTpl< Scalar >::size().
GetMinEigenValueAndVector()
template<typename Scalar > static bool Jacobi< Scalar >::GetMinEigenValueAndVector (const SquareMatrix & eigenVectors, const EigenValues & eigenValues, Scalar & minEigenValue, Scalar minEigenVector[]) inline static
Returns the smallest eigenvalue and its associated eigenvector.
Parameters
eigenVectors eigenvectors (as a square matrix)
eigenValues eigenvalues
minEigenValue smallest eigenvalue
minEigenVector eigenvector vector corresponding to the smallest eigenvalue
Returns
success
Definition at line 410 of file Jacobi.h.
References Jacobi< Scalar >::GetEigenVector(), cloudViewer::SquareMatrixTpl< Scalar >::isValid(), and cloudViewer::SquareMatrixTpl< Scalar >::size().
Referenced by ComputeCorePointNormal().
SortEigenValuesAndVectors()
template<typename Scalar > static bool Jacobi< Scalar >::SortEigenValuesAndVectors (SquareMatrix & eigenVectors, EigenValues & eigenValues) inline static
Sorts the eigenvectors in the decreasing order of their associated eigenvalues
Parameters
eigenVectors eigenvectors (as a square matrix)
eigenValues eigenvalues
Returns
success
Definition at line 333 of file Jacobi.h.
References cloudViewer::SquareMatrixTpl< Scalar >::isValid(), cloudViewer::SquareMatrixTpl< Scalar >::m_values, cloudViewer::SquareMatrixTpl< Scalar >::size(), and std::swap().
Referenced by DimensionalityScaleParamsComputer::computeScaleParams(), ccCompass::estimateStrain(), and ccCompass::estimateStructureNormals().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/Jacobi.h