ACloudViewer: cc2Point5DimEditor Class Reference
cc2Point5DimEditor Class Reference abstract
2.5D data editor (generic interface)
#include <ecv2.5DimEditor.h>
Public Member Functions
cc2Point5DimEditor ()
Default constructor.
virtual ~cc2Point5DimEditor ()
Destructor.
Protected Member Functions
virtual double getGridStep () const =0
Returns projection grid step.
virtual unsigned char getProjectionDimension () const =0
Returns projection dimension.
virtual ccRasterGrid::ProjectionType getTypeOfProjection () const =0
Returns type of projection.
virtual ccBBox getCustomBBox () const
Returns custom bbox.
virtual void gridIsUpToDate (bool state)=0
Declares whether the grid is up-to-date or not.
virtual void update2DDisplayZoom (ccBBox &box)
Updates the 2D display zoom.
virtual bool showGridBoxEditor ()
Show grid box editor and update.
virtual QString getGridSizeAsString () const
Returns the grid size as a string.
virtual bool getGridSize (unsigned &width, unsigned &height) const
Returns the grid size.
void createBoundingBoxEditor (const ccBBox &gridBBox, QWidget *parent)
Creates the bounding-box editor.
void create2DView (QFrame *parentFrame)
Creates the 2D view.
ccRasterGrid::EmptyCellFillOption getFillEmptyCellsStrategy (QComboBox *comboBox) const
Returns the empty cell strategy (for a given combo-box)
ccPointCloud * convertGridToCloud (const std::vector< ccRasterGrid::ExportableFields > &exportedFields, bool interpolateSF, bool interpolateColors, bool resampleInputCloudXY, bool resampleInputCloudZ, ccGenericPointCloud *inputCloud, bool fillEmptyCells, double emptyCellsHeight, bool exportToOriginalCS) const
Shortcut to ccRasterGrid::convertToCloud.
Protected Attributes
ccRasterGrid m_grid
Raster grid.
ccBoundingBoxEditorDlg * m_bbEditorDlg
Associated dialog.
ccPointCloud * m_rasterCloud
'Raster' cloud
Detailed Description
2.5D data editor (generic interface)
Definition at line 21 of file ecv2.5DimEditor.h.
Constructor & Destructor Documentation
cc2Point5DimEditor()
cc2Point5DimEditor::cc2Point5DimEditor ()
Default constructor.
Definition at line 30 of file ecv2.5DimEditor.cpp.
~cc2Point5DimEditor()
cc2Point5DimEditor::~cc2Point5DimEditor () virtual
Destructor.
Definition at line 32 of file ecv2.5DimEditor.cpp.
References ecvDisplayTools::GetMainWindow(), m_rasterCloud, and ecvDisplayTools::RemoveFromOwnDB().
Member Function Documentation
convertGridToCloud()
ccPointCloud * cc2Point5DimEditor::convertGridToCloud (const std::vector< ccRasterGrid::ExportableFields > & exportedFields, bool interpolateSF, bool interpolateColors, bool resampleInputCloudXY, bool resampleInputCloudZ, ccGenericPointCloud * inputCloud, bool fillEmptyCells, double emptyCellsHeight, bool exportToOriginalCS) const protected
Shortcut to ccRasterGrid::convertToCloud.
Definition at line 174 of file ecv2.5DimEditor.cpp.
References ccRasterGrid::convertToCloud(), getCustomBBox(), getProjectionDimension(), ccEntityAction::interpolateColors(), cloudViewer::BoundingBoxTpl< T >::isValid(), and m_grid.
Referenced by ccVolumeCalcTool::convertGridToCloud(), and ccRasterizeTool::convertGridToCloud().
create2DView()
void cc2Point5DimEditor::create2DView (QFrame * parentFrame) protected
Creates the 2D view.
Definition at line 63 of file ecv2.5DimEditor.cpp.
References ecvGui::ParamStruct::backgroundCol, ecvColor::black(), ecvGui::ParamStruct::colorScaleUseShader, ecvGui::ParamStruct::decimateMeshOnMove, ecvGui::ParamStruct::displayCross, ecvDisplayTools::DisplayOverlayEntities(), ecvGui::ParamStruct::drawBackgroundGradient, ecvDisplayTools::GetDisplayParameters(), ecvDisplayTools::INTERACT_CLICKABLE_ITEMS, ecvDisplayTools::INTERACT_PAN, ecvDisplayTools::INTERACT_ZOOM_CAMERA, ecvDisplayTools::NO_PICKING, ecvDisplayTools::SetDisplayParameters(), ecvDisplayTools::SetInteractionMode(), ecvDisplayTools::SetPerspectiveState(), ecvDisplayTools::SetPickingMode(), ecvGui::ParamStruct::textDefaultCol, and ecvColor::white().
Referenced by ccRasterizeTool::ccRasterizeTool(), and ccVolumeCalcTool::ccVolumeCalcTool().
createBoundingBoxEditor()
void cc2Point5DimEditor::createBoundingBoxEditor (const ccBBox & gridBBox, QWidget * parent) protected
Creates the bounding-box editor.
Definition at line 55 of file ecv2.5DimEditor.cpp.
References m_bbEditorDlg, and ccBoundingBoxEditorDlg::setBaseBBox().
Referenced by ccRasterizeTool::ccRasterizeTool(), and ccVolumeCalcTool::ccVolumeCalcTool().
getCustomBBox()
ccBBox cc2Point5DimEditor::getCustomBBox () const protected virtual
Returns custom bbox.
Definition at line 118 of file ecv2.5DimEditor.cpp.
References ccBoundingBoxEditorDlg::getBox(), and m_bbEditorDlg.
Referenced by convertGridToCloud(), ccRasterizeTool::generateContours(), ccRasterizeTool::generateRaster(), getGridSize(), ccVolumeCalcTool::updateGrid(), and ccRasterizeTool::updateGrid().
getFillEmptyCellsStrategy()
ccRasterGrid::EmptyCellFillOption cc2Point5DimEditor::getFillEmptyCellsStrategy (QComboBox * comboBox) const protected
Returns the empty cell strategy (for a given combo-box)
Definition at line 198 of file ecv2.5DimEditor.cpp.
References ccRasterGrid::FILL_AVERAGE_HEIGHT, ccRasterGrid::FILL_CUSTOM_HEIGHT, ccRasterGrid::FILL_MAXIMUM_HEIGHT, ccRasterGrid::FILL_MINIMUM_HEIGHT, ccRasterGrid::INTERPOLATE_DELAUNAY, and ccRasterGrid::LEAVE_EMPTY.
Referenced by ccVolumeCalcTool::ceilFillEmptyCellStrategyChanged(), ccRasterizeTool::fillEmptyCellStrategyChanged(), ccRasterizeTool::generateRaster(), ccRasterizeTool::getFillEmptyCellsStrategyExt(), ccVolumeCalcTool::groundFillEmptyCellStrategyChanged(), ccVolumeCalcTool::updateGrid(), and ccRasterizeTool::updateGrid().
getGridSize()
bool cc2Point5DimEditor::getGridSize (unsigned & width, unsigned & height) const protected virtual
Returns the grid size.
Definition at line 94 of file ecv2.5DimEditor.cpp.
References ccRasterGrid::ComputeGridSize(), getCustomBBox(), getGridStep(), and getProjectionDimension().
Referenced by getGridSizeAsString(), ccVolumeCalcTool::updateGrid(), and ccRasterizeTool::updateGrid().
getGridSizeAsString()
QString cc2Point5DimEditor::getGridSizeAsString () const protected virtual
Returns the grid size as a string.
Definition at line 109 of file ecv2.5DimEditor.cpp.
References getGridSize().
Referenced by ccRasterizeTool::updateGridInfo(), and ccVolumeCalcTool::updateGridInfo().
getGridStep()
virtual double cc2Point5DimEditor::getGridStep () const protected pure virtual
Returns projection grid step.
Implemented in ccVolumeCalcTool, and ccRasterizeTool.
Referenced by getGridSize().
getProjectionDimension()
virtual unsigned char cc2Point5DimEditor::getProjectionDimension () const protected pure virtual
Returns projection dimension.
Returns
dimension as int (0: X, 1: Y, 2:Z)
Implemented in ccVolumeCalcTool, and ccRasterizeTool.
Referenced by convertGridToCloud(), getGridSize(), and showGridBoxEditor().
getTypeOfProjection()
virtual ccRasterGrid::ProjectionType cc2Point5DimEditor::getTypeOfProjection () const protected pure virtual
Returns type of projection.
Implemented in ccVolumeCalcTool, and ccRasterizeTool.
gridIsUpToDate()
virtual void cc2Point5DimEditor::gridIsUpToDate (bool state) protected pure virtual
Declares whether the grid is up-to-date or not.
Implemented in ccVolumeCalcTool, and ccRasterizeTool.
Referenced by showGridBoxEditor().
showGridBoxEditor()
bool cc2Point5DimEditor::showGridBoxEditor () protected virtual
Show grid box editor and update.
Returns
whether the box was modified or not
Definition at line 41 of file ecv2.5DimEditor.cpp.
References ccBoundingBoxEditorDlg::exec(), getProjectionDimension(), gridIsUpToDate(), m_bbEditorDlg, and ccBoundingBoxEditorDlg::set2DMode().
Referenced by ccRasterizeTool::showGridBoxEditor(), and ccVolumeCalcTool::showGridBoxEditor().
update2DDisplayZoom()
void cc2Point5DimEditor::update2DDisplayZoom (ccBBox & box) protected virtual
Updates the 2D display zoom.
Definition at line 122 of file ecv2.5DimEditor.cpp.
References cloudViewer::utility::ceil(), ecvDisplayTools::Deprecate3DLayer(), Vector3Tpl< double >::fromArray(), cloudViewer::BoundingBoxTpl< T >::getCenter(), ecvDisplayTools::GetMainWindow(), ecvDisplayTools::GetViewportParameters(), ccRasterGrid::gridStep, ecvDisplayTools::Height(), ccRasterGrid::height, ecvDisplayTools::InvalidateViewport(), ecvDisplayTools::InvalidateVisualization(), ccRasterGrid::isValid(), m_grid, ecvViewportParameters::pixelSize, ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::SetCameraPos(), ecvDisplayTools::SetPivotPoint(), ecvDisplayTools::SetPointSize(), ecvDisplayTools::SetViewportParameters(), Tuple3Tpl< Type >::u, ecvDisplayTools::Width(), ccRasterGrid::width, and ecvViewportParameters::zoom.
Referenced by ccRasterizeTool::updateGridAndDisplay(), and ccVolumeCalcTool::updateGridAndDisplay().
Member Data Documentation
m_bbEditorDlg
ccBoundingBoxEditorDlg* cc2Point5DimEditor::m_bbEditorDlg protected
Associated dialog.
Definition at line 90 of file ecv2.5DimEditor.h.
Referenced by createBoundingBoxEditor(), getCustomBBox(), and showGridBoxEditor().
m_grid
ccRasterGrid cc2Point5DimEditor::m_grid protected
Raster grid.
Definition at line 87 of file ecv2.5DimEditor.h.
Referenced by ccRasterizeTool::convertGridToCloud(), convertGridToCloud(), ccVolumeCalcTool::exportGridAsCloud(), ccRasterizeTool::generateASCIIMatrix(), ccRasterizeTool::generateCloud(), ccRasterizeTool::generateContours(), ccRasterizeTool::generateHillshade(), ccRasterizeTool::generateImage(), ccRasterizeTool::generateRaster(), ccRasterizeTool::getFillEmptyCellsStrategyExt(), update2DDisplayZoom(), ccVolumeCalcTool::updateGrid(), and ccRasterizeTool::updateGrid().
m_rasterCloud
ccPointCloud* cc2Point5DimEditor::m_rasterCloud protected
'Raster' cloud
Definition at line 93 of file ecv2.5DimEditor.h.
Referenced by ccRasterizeTool::activeLayerChanged(), ccRasterizeTool::addNewContour(), ccRasterizeTool::convertGridToCloud(), ccRasterizeTool::generateContours(), ccRasterizeTool::generateHillshade(), ccRasterizeTool::generateImage(), ccRasterizeTool::updateGridAndDisplay(), ccVolumeCalcTool::updateGridAndDisplay(), and ~cc2Point5DimEditor().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecv2.5DimEditor.h
/root/ACloudViewer/app/ecv2.5DimEditor.cpp