ACloudViewer: ccPlaneEditDlg Class Reference
ccPlaneEditDlg Class Reference
Dialog to create (or edit the parameters) of a plane.
#include <ecvPlaneEditDlg.h>
Public Slots
void pickPointAsCenter (bool)
void onDipDirChanged (double)
void onDipDirModified (bool)
void onNormalChanged (double)
Public Member Functions
ccPlaneEditDlg (ccPickingHub *pickingHub, QWidget *parent)
Default constructor.
virtual ~ccPlaneEditDlg ()
Destructor.
void initWithPlane (ccPlane *plane)
Links this dialog with an existing plane.
void updatePlane (ccPlane *plane)
Updates a plane with the current parameters.
virtual void onItemPicked (const PickedItem &pi)
Inherited from ccPickingListener.
Public Member Functions inherited from ccPickingListener
virtual ~ccPickingListener ()=default
Protected Slots
void saveParamsAndAccept ()
Protected Attributes
ccPlane * m_associatedPlane
Associated plane (if any)
ccPickingHub * m_pickingHub
Picking hub.
Detailed Description
Dialog to create (or edit the parameters) of a plane.
Definition at line 26 of file ecvPlaneEditDlg.h.
Constructor & Destructor Documentation
ccPlaneEditDlg()
ccPlaneEditDlg::ccPlaneEditDlg (ccPickingHub * pickingHub, QWidget * parent) explicit
Default constructor.
Definition at line 31 of file ecvPlaneEditDlg.cpp.
References onDipDirChanged(), onDipDirModified(), onNormalChanged(), pickPointAsCenter(), s_center, s_dip, s_dipDir, s_height, s_upward, s_width, saveParamsAndAccept(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
~ccPlaneEditDlg()
ccPlaneEditDlg::~ccPlaneEditDlg () virtual
Destructor.
Definition at line 89 of file ecvPlaneEditDlg.cpp.
Member Function Documentation
initWithPlane()
void ccPlaneEditDlg::initWithPlane (ccPlane * plane)
Links this dialog with an existing plane.
Definition at line 210 of file ecvPlaneEditDlg.cpp.
References ccPlane::getCenter(), ccPlane::getNormal(), ccPlane::getXWidth(), ccPlane::getYWidth(), m_associatedPlane, onNormalChanged(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
onDipDirChanged
void ccPlaneEditDlg::onDipDirChanged (double) slot
Definition at line 134 of file ecvPlaneEditDlg.cpp.
References ccNormalVectors::ConvertDipAndDipDirToNormal(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccPlaneEditDlg(), and onDipDirModified().
onDipDirModified
void ccPlaneEditDlg::onDipDirModified (bool) slot
Definition at line 130 of file ecvPlaneEditDlg.cpp.
References onDipDirChanged().
Referenced by ccPlaneEditDlg().
onItemPicked()
void ccPlaneEditDlg::onItemPicked (const PickedItem & pi) virtual
Inherited from ccPickingListener.
Implements ccPickingListener.
Definition at line 198 of file ecvPlaneEditDlg.cpp.
References ccPickingListener::PickedItem::entity, ccPickingListener::PickedItem::P3D, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
onNormalChanged
void ccPlaneEditDlg::onNormalChanged (double) slot
Definition at line 155 of file ecvPlaneEditDlg.cpp.
References ccNormalVectors::ConvertNormalToDipAndDipDir(), Vector3Tpl< Type >::normalize(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccPlaneEditDlg(), and initWithPlane().
pickPointAsCenter
void ccPlaneEditDlg::pickPointAsCenter (bool state) slot
Definition at line 178 of file ecvPlaneEditDlg.cpp.
References ccPickingHub::addListener(), CVLog::Error(), m_pickingHub, and ccPickingHub::removeListener().
Referenced by ccPlaneEditDlg().
saveParamsAndAccept
void ccPlaneEditDlg::saveParamsAndAccept () protected slot
Definition at line 93 of file ecvPlaneEditDlg.cpp.
References MainWindow::addToDB(), m_associatedPlane, ccHObject::redrawDisplay(), s_center, s_dip, s_dipDir, s_height, s_upward, s_width, MainWindow::TheInstance(), updatePlane(), MainWindow::updatePropertiesView(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccPlaneEditDlg().
updatePlane()
void ccPlaneEditDlg::updatePlane (ccPlane * plane)
Updates a plane with the current parameters.
Definition at line 249 of file ecvPlaneEditDlg.cpp.
References ccHObject::applyGLTransformation_recursive(), ccNormalVectors::ConvertDipAndDipDirToNormal(), cloudViewer::DegreesToRadians(), Vector3Tpl< Type >::dot(), fabs(), ccGLMatrixTpl< float >::FromToRotation(), ccPlane::getCenter(), ccPlane::getNormal(), ccGLMatrixTpl< T >::getTranslationAsVec3D(), ccPlane::getXWidth(), ccPlane::getYWidth(), height, ccGLMatrixTpl< T >::initFromParameters(), PC_ONE, CVLog::Print(), ccGLMatrixTpl< T >::setTranslation(), ccPlane::setXWidth(), ccPlane::setYWidth(), ccGLMatrixTpl< T >::toString(), width, and Tuple3Tpl< Type >::z.
Referenced by saveParamsAndAccept().
Member Data Documentation
m_associatedPlane
ccPlane* ccPlaneEditDlg::m_associatedPlane protected
Associated plane (if any)
Definition at line 60 of file ecvPlaneEditDlg.h.
Referenced by initWithPlane(), and saveParamsAndAccept().
m_pickingHub
ccPickingHub* ccPlaneEditDlg::m_pickingHub protected
Picking hub.
Definition at line 63 of file ecvPlaneEditDlg.h.
Referenced by pickPointAsCenter().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvPlaneEditDlg.h
/root/ACloudViewer/app/ecvPlaneEditDlg.cpp