ACloudViewer: cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder Class Reference
cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder Class Reference
#include <FilamentGeometryBuffersBuilder.h>
Public Member Functions
TriangleMeshBuffersBuilder (const ccMesh &geometry)
filament::RenderableManager::PrimitiveType GetPrimitiveType () const override
Buffers ConstructBuffers () override
filament::Box ComputeAABB () override
Public Member Functions inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
virtual ~GeometryBuffersBuilder ()=default
virtual void SetDownsampleThreshold (size_t min_points)
virtual void SetWideLines ()
virtual void SetAdjustColorsForSRGBToneMapping (bool adjust)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
using Buffers = std::tuple< VertexBufferHandle, IndexBufferHandle, IndexBufferHandle >
using IndexType = std::uint32_t
Static Public Member Functions inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
static std::unique_ptr< GeometryBuffersBuilder > GetBuilder (const ccHObject &geometry)
static std::unique_ptr< GeometryBuffersBuilder > GetBuilder (const t::geometry::Geometry &geometry)
Static Protected Member Functions inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
static void DeallocateBuffer (void *buffer, size_t size, void *user_ptr)
static IndexBufferHandle CreateIndexBuffer (size_t max_index, size_t n_subsamples=SIZE_MAX)
Protected Attributes inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
size_t downsample_threshold_ = SIZE_MAX
bool wide_lines_ = false
bool adjust_colors_for_srgb_tonemapping_ = true
Detailed Description
Definition at line 110 of file FilamentGeometryBuffersBuilder.h.
Constructor & Destructor Documentation
TriangleMeshBuffersBuilder()
cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::TriangleMeshBuffersBuilder (const ccMesh & geometry) explicit
Definition at line 356 of file TriangleMeshBuffers.cpp.
Member Function Documentation
ComputeAABB()
filament::Box cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::ComputeAABB () override virtual
Implements cloudViewer::visualization::rendering::GeometryBuffersBuilder.
Definition at line 451 of file TriangleMeshBuffers.cpp.
References ccMesh::GetAxisAlignedBoundingBox(), max(), and min().
ConstructBuffers()
GeometryBuffersBuilder::Buffers cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::ConstructBuffers () override virtual
Implements cloudViewer::visualization::rendering::GeometryBuffersBuilder.
Definition at line 364 of file TriangleMeshBuffers.cpp.
References cloudViewer::visualization::rendering::GeometryBuffersBuilder::DeallocateBuffer(), cloudViewer::visualization::rendering::EngineInstance::GetInstance(), cloudViewer::visualization::rendering::EngineInstance::GetResourceManager(), ccMesh::getVertexNormal(), ccMesh::getVerticeSize(), has_colors, ccMesh::hasNormals(), ccMesh::hasTriangleUvs(), normals, stride, and cloudViewer::visualization::rendering::VertexBuffer.
GetPrimitiveType()
RenderableManager::PrimitiveType cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::GetPrimitiveType () const override virtual
Implements cloudViewer::visualization::rendering::GeometryBuffersBuilder.
Definition at line 359 of file TriangleMeshBuffers.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentGeometryBuffersBuilder.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/TriangleMeshBuffers.cpp