ACloudViewer: colmap::LORANSAC< Estimator, LocalEstimator, SupportMeasurer, Sampler > Class Template Reference
colmap::LORANSAC< Estimator, LocalEstimator, SupportMeasurer, Sampler > Class Template Reference
#include <loransac.h>
Public Member Functions
LORANSAC (const RANSACOptions &options)
Report Estimate (const std::vector< typename Estimator::X_t > &X, const std::vector< typename Estimator::Y_t > &Y)
Public Member Functions inherited from colmap::RANSAC< Estimator, InlierSupportMeasurer, RandomSampler >
RANSAC (const RANSACOptions &options)
Report Estimate (const std::vector< typename Estimator::X_t > &X, const std::vector< typename Estimator::Y_t > &Y)
Public Attributes
LocalEstimator local_estimator
Public Attributes inherited from colmap::RANSAC< Estimator, InlierSupportMeasurer, RandomSampler >
Estimator estimator
RandomSampler sampler
InlierSupportMeasurer support_measurer
Additional Inherited Members
Static Public Member Functions inherited from colmap::RANSAC< Estimator, InlierSupportMeasurer, RandomSampler >
static size_t ComputeNumTrials (const size_t num_inliers, const size_t num_samples, const double confidence, const double num_trials_multiplier)
Protected Attributes inherited from colmap::RANSAC< Estimator, InlierSupportMeasurer, RandomSampler >
RANSACOptions options_
Detailed Description
template<typename Estimator, typename LocalEstimator, typename SupportMeasurer = InlierSupportMeasurer, typename Sampler = RandomSampler>
class colmap::LORANSAC< Estimator, LocalEstimator, SupportMeasurer, Sampler >
Definition at line 30 of file loransac.h.
Constructor & Destructor Documentation
LORANSAC()
template<typename Estimator , typename LocalEstimator , typename SupportMeasurer , typename Sampler > colmap::LORANSAC< Estimator, LocalEstimator, SupportMeasurer, Sampler >::LORANSAC (const RANSACOptions & options) explicit
Definition at line 63 of file loransac.h.
Member Function Documentation
Estimate()
template<typename Estimator , typename LocalEstimator , typename SupportMeasurer , typename Sampler > LORANSAC< Estimator, LocalEstimator, SupportMeasurer, Sampler >::Report colmap::LORANSAC< Estimator, LocalEstimator, SupportMeasurer, Sampler >::Estimate (const std::vector< typename Estimator::X_t > & X, const std::vector< typename Estimator::Y_t > & Y)
Definition at line 72 of file loransac.h.
References kMinNumSamples, colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::Report::num_trials, colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::Report::success, and X.
Referenced by colmap::Reconstruction::AlignRobust(), BOOST_AUTO_TEST_CASE(), colmap::ComputeAlignmentBetweenReconstructions(), colmap::TwoViewGeometry::DetectWatermark(), colmap::TwoViewGeometry::EstimateCalibrated(), and colmap::TwoViewGeometry::EstimateUncalibrated().
Member Data Documentation
local_estimator
template<typename Estimator , typename LocalEstimator , typename SupportMeasurer = InlierSupportMeasurer, typename Sampler = RandomSampler> LocalEstimator colmap::LORANSAC< Estimator, LocalEstimator, SupportMeasurer, Sampler >::local_estimator
Definition at line 47 of file loransac.h.
Referenced by colmap::ComputeAlignmentBetweenReconstructions().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/optim/loransac.h