ACloudViewer: BallPivoting Class Reference
BallPivoting Class Reference
Public Member Functions
BallPivoting (const ccPointCloud &pcd)
virtual ~BallPivoting ()
bool ComputeBallCenter (int vidx1, int vidx2, int vidx3, double radius, Eigen::Vector3d &center)
BallPivotingEdgePtr GetLinkingEdge (const BallPivotingVertexPtr &v0, const BallPivotingVertexPtr &v1)
void CreateTriangle (const BallPivotingVertexPtr &v0, const BallPivotingVertexPtr &v1, const BallPivotingVertexPtr &v2, const Eigen::Vector3d &center)
Eigen::Vector3d ComputeFaceNormal (const Eigen::Vector3d &v0, const Eigen::Vector3d &v1, const Eigen::Vector3d &v2)
bool IsCompatible (const BallPivotingVertexPtr &v0, const BallPivotingVertexPtr &v1, const BallPivotingVertexPtr &v2)
BallPivotingVertexPtr FindCandidateVertex (const BallPivotingEdgePtr &edge, double radius, Eigen::Vector3d &candidate_center)
void ExpandTriangulation (double radius)
bool TryTriangleSeed (const BallPivotingVertexPtr &v0, const BallPivotingVertexPtr &v1, const BallPivotingVertexPtr &v2, const std::vector< int > &nb_indices, double radius, Eigen::Vector3d &center)
bool TrySeed (BallPivotingVertexPtr &v, double radius)
void FindSeedTriangle (double radius)
std::shared_ptr< ccMesh > Run (const std::vector< double > &radii)
Detailed Description
Definition at line 145 of file SurfaceReconstructionBallPivoting.cpp.
Constructor & Destructor Documentation
BallPivoting()
BallPivoting::BallPivoting (const ccPointCloud & pcd) inline
Definition at line 147 of file SurfaceReconstructionBallPivoting.cpp.
References ccPointCloud::addNorms(), cloudViewer::PointCloudTpl< T >::addPoints(), ccPointCloud::addRGBColors(), ccPointCloud::getEigenNormal(), cloudViewer::PointCloudTpl< T >::getEigenPoint(), ccPointCloud::getPointColors(), ccPointCloud::getPointNormals(), cloudViewer::PointCloudTpl< T >::getPoints(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), LogError, ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveThePointsTable(), ccPointCloud::reserveTheRGBTable(), ccObject::setEnabled(), ccObject::setLocked(), and cloudViewer::PointCloudTpl< T >::size().
~BallPivoting()
virtual BallPivoting::~BallPivoting () inline virtual
Definition at line 180 of file SurfaceReconstructionBallPivoting.cpp.
Member Function Documentation
ComputeBallCenter()
bool BallPivoting::ComputeBallCenter (int vidx1, int vidx2, int vidx3, double radius, Eigen::Vector3d & center) inline
Definition at line 186 of file SurfaceReconstructionBallPivoting.cpp.
References a, e, and height.
ComputeFaceNormal()
Eigen::Vector3d BallPivoting::ComputeFaceNormal (const Eigen::Vector3d & v0, const Eigen::Vector3d & v1, const Eigen::Vector3d & v2) inline
Definition at line 300 of file SurfaceReconstructionBallPivoting.cpp.
References normal.
CreateTriangle()
void BallPivoting::CreateTriangle (const BallPivotingVertexPtr & v0, const BallPivotingVertexPtr & v1, const BallPivotingVertexPtr & v2, const Eigen::Vector3d & center) inline
Definition at line 252 of file SurfaceReconstructionBallPivoting.cpp.
References e, e2, BallPivotingVertex::edges_, BallPivotingVertex::idx_, LogDebug, BallPivotingVertex::normal_, BallPivotingVertex::point_, and BallPivotingVertex::UpdateType().
ExpandTriangulation()
void BallPivoting::ExpandTriangulation (double radius) inline
Definition at line 486 of file SurfaceReconstructionBallPivoting.cpp.
References BallPivotingEdge::Front, LogDebug, and BallPivotingVertex::type_.
FindCandidateVertex()
BallPivotingVertexPtr BallPivoting::FindCandidateVertex (const BallPivotingEdgePtr & edge, double radius, Eigen::Vector3d & candidate_center) inline
Definition at line 328 of file SurfaceReconstructionBallPivoting.cpp.
References a, e, BallPivotingVertex::idx_, LogDebug, LogError, M_PI, BallPivotingVertex::point_, and cloudViewer::utility::IntersectionTest::PointsCoplanar().
FindSeedTriangle()
void BallPivoting::FindSeedTriangle (double radius) inline
Definition at line 669 of file SurfaceReconstructionBallPivoting.cpp.
References LogDebug.
GetLinkingEdge()
BallPivotingEdgePtr BallPivoting::GetLinkingEdge (const BallPivotingVertexPtr & v0, const BallPivotingVertexPtr & v1) inline
Definition at line 239 of file SurfaceReconstructionBallPivoting.cpp.
References BallPivotingVertex::edges_.
IsCompatible()
bool BallPivoting::IsCompatible (const BallPivotingVertexPtr & v0, const BallPivotingVertexPtr & v1, const BallPivotingVertexPtr & v2) inline
Definition at line 311 of file SurfaceReconstructionBallPivoting.cpp.
References e, BallPivotingVertex::idx_, LogDebug, normal, BallPivotingVertex::normal_, and BallPivotingVertex::point_.
Run()
std::shared_ptr<ccMesh> BallPivoting::Run (const std::vector< double > & radii) inline
Definition at line 681 of file SurfaceReconstructionBallPivoting.cpp.
References LogDebug, LogError, normals, and radii.
Referenced by ccMesh::CreateFromPointCloudBallPivoting().
TrySeed()
bool BallPivoting::TrySeed (BallPivotingVertexPtr & v, double radius) inline
Definition at line 586 of file SurfaceReconstructionBallPivoting.cpp.
References e2, BallPivotingVertex::idx_, LogDebug, BallPivotingVertex::point_, and BallPivotingVertex::type_.
TryTriangleSeed()
bool BallPivoting::TryTriangleSeed (const BallPivotingVertexPtr & v0, const BallPivotingVertexPtr & v1, const BallPivotingVertexPtr & v2, const std::vector< int > & nb_indices, double radius, Eigen::Vector3d & center) inline
Definition at line 528 of file SurfaceReconstructionBallPivoting.cpp.
References e, BallPivotingVertex::idx_, LogDebug, and BallPivotingVertex::point_.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/src/SurfaceReconstructionBallPivoting.cpp