ACloudViewer: ConfusionMatrix Class Reference
ConfusionMatrix Class Reference
#include <confusionmatrix.h>
Public Types
enum metrics { PRECISION = 0 , RECALL = 1 , F1_SCORE = 2 }
Public Member Functions
ConfusionMatrix (const std::vector< ScalarType > &actual, const std::vector< ScalarType > &predicted)
~ConfusionMatrix () override
void computePrecisionRecallF1Score (cv::Mat &matrix, cv::Mat &precisionRecallF1Score, cv::Mat &vec_TP_FN)
float computeOverallAccuracy (cv::Mat &matrix)
void compute (const std::vector< ScalarType > &actual, const std::vector< ScalarType > &predicted)
void setSessionRun (QString session, int run)
bool save (QString filePath)
float getOverallAccuracy ()
Detailed Description
Definition at line 21 of file confusionmatrix.h.
Member Enumeration Documentation
metrics
enum ConfusionMatrix::metrics
Enumerator
PRECISION
RECALL
F1_SCORE
Definition at line 25 of file confusionmatrix.h.
Constructor & Destructor Documentation
ConfusionMatrix()
ConfusionMatrix::ConfusionMatrix (const std::vector< ScalarType > & actual, const std::vector< ScalarType > & predicted) explicit
Definition at line 42 of file confusionmatrix.cpp.
References compute().
~ConfusionMatrix()
ConfusionMatrix::~ConfusionMatrix () override
Definition at line 62 of file confusionmatrix.cpp.
Member Function Documentation
compute()
void ConfusionMatrix::compute (const std::vector< ScalarType > & actual, const std::vector< ScalarType > & predicted)
Definition at line 144 of file confusionmatrix.cpp.
References computeOverallAccuracy(), computePrecisionRecallF1Score(), F1_SCORE, GetColor(), PRECISION, and RECALL.
Referenced by ConfusionMatrix().
computeOverallAccuracy()
float ConfusionMatrix::computeOverallAccuracy (cv::Mat & matrix)
Definition at line 121 of file confusionmatrix.cpp.
References NAN_VALUE.
Referenced by compute().
computePrecisionRecallF1Score()
void ConfusionMatrix::computePrecisionRecallF1Score (cv::Mat & matrix, cv::Mat & precisionRecallF1Score, cv::Mat & vec_TP_FN)
Definition at line 67 of file confusionmatrix.cpp.
References F1_SCORE, NAN_VALUE, PRECISION, and RECALL.
Referenced by compute().
getOverallAccuracy()
float ConfusionMatrix::getOverallAccuracy ()
Definition at line 308 of file confusionmatrix.cpp.
Referenced by Train3DMASCDialog::saveTraces().
save()
bool ConfusionMatrix::save (QString filePath)
Definition at line 277 of file confusionmatrix.cpp.
References QtCompat::endl(), CVLog::Error(), F1_SCORE, PRECISION, and RECALL.
Referenced by Train3DMASCDialog::saveTraces().
setSessionRun()
void ConfusionMatrix::setSessionRun (QString session, int run)
Definition at line 269 of file confusionmatrix.cpp.
Referenced by Train3DMASCDialog::saveTraces().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/q3DMASC/confusionmatrix.h
/root/ACloudViewer/plugins/core/Standard/q3DMASC/confusionmatrix.cpp