ACloudViewer: VtkUtils::ModelToVectorsConverter Class Reference
VtkUtils::ModelToVectorsConverter Class Reference
#include <modeltovectorsconverter.h>
Public Member Functions
ModelToVectorsConverter (TableModel *model)
void run ()
QList< Vector4F > vectors () const
Public Member Functions inherited from VtkUtils::SignalledRunnable
SignalledRunnable ()
Additional Inherited Members
Signals inherited from VtkUtils::SignalledRunnable
void finished ()
Detailed Description
Definition at line 16 of file modeltovectorsconverter.h.
Constructor & Destructor Documentation
ModelToVectorsConverter()
VtkUtils::ModelToVectorsConverter::ModelToVectorsConverter (TableModel * model)
Definition at line 16 of file modeltovectorsconverter.cpp.
Member Function Documentation
run()
void VtkUtils::ModelToVectorsConverter::run ()
Definition at line 19 of file modeltovectorsconverter.cpp.
References VtkUtils::TableModel::columnCount(), VtkUtils::TableModel::data(), VtkUtils::SignalledRunnable::finished(), and VtkUtils::TableModel::rowCount().
vectors()
QList< Vector4F > VtkUtils::ModelToVectorsConverter::vectors () const
Definition at line 44 of file modeltovectorsconverter.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/modeltovectorsconverter.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/modeltovectorsconverter.cpp