ACloudViewer: cloudViewer::visualization::ViewControl Class Reference
cloudViewer::visualization::ViewControl Class Reference
View controller for visualizer.
#include <ViewControl.h>
Public Types
enum ProjectionType { Perspective = 0 , Orthogonal = 1 }
Public Member Functions
virtual ~ViewControl ()
void SetViewMatrices (const Eigen::Matrix4d &model_matrix=Eigen::Matrix4d::Identity())
bool ConvertToViewParameters (ViewParameters &status) const
Function to get equivalent view parameters (support orthogonal)
bool ConvertFromViewParameters (const ViewParameters &status)
void SetZoom (const double zoom)
void SetUp (const Eigen::Vector3d &up)
void SetFront (const Eigen::Vector3d &front)
void SetLookat (const Eigen::Vector3d &lookat)
bool ConvertToPinholeCameraParameters (camera::PinholeCameraParameters &parameters)
bool ConvertFromPinholeCameraParameters (const camera::PinholeCameraParameters &parameters, bool allow_arbitrary=false)
ProjectionType GetProjectionType () const
void SetProjectionParameters ()
virtual void Reset ()
virtual void ChangeFieldOfView (double step)
virtual void ChangeWindowSize (int width, int height)
virtual void Scale (double scale)
virtual void Rotate (double x, double y, double xo=0.0, double yo=0.0)
Function to process rotation.
virtual void Translate (double x, double y, double xo=0.0, double yo=0.0)
Function to process translation.
virtual void CameraLocalTranslate (double forward, double right, double up)
virtual void CameraLocalRotate (double x, double y, double xo=0.0, double yo=0.0)
virtual void ResetCameraLocalRotate ()
virtual void Roll (double x)
const ccBBox & GetBoundingBox () const
void ResetBoundingBox ()
void FitInGeometry (const ccHObject &geometry)
double GetFieldOfView () const
Function to get field of view.
gl_util::GLMatrix4f GetMVPMatrix () const
gl_util::GLMatrix4f GetProjectionMatrix () const
gl_util::GLMatrix4f GetViewMatrix () const
gl_util::GLMatrix4f GetModelMatrix () const
gl_util::GLVector3f GetEye () const
gl_util::GLVector3f GetLookat () const
gl_util::GLVector3f GetUp () const
gl_util::GLVector3f GetFront () const
gl_util::GLVector3f GetRight () const
int GetWindowWidth () const
int GetWindowHeight () const
double GetZNear () const
double GetZFar () const
void SetConstantZNear (double z_near)
void SetConstantZFar (double z_far)
void UnsetConstantZNear ()
void UnsetConstantZFar ()
Static Public Attributes
static const double FIELD_OF_VIEW_MAX = 90.0
static const double FIELD_OF_VIEW_MIN = 5.0
static const double FIELD_OF_VIEW_DEFAULT = 60.0
static const double FIELD_OF_VIEW_STEP = 5.0
static const double ZOOM_DEFAULT = 0.7
static const double ZOOM_MIN = 0.02
static const double ZOOM_MAX = 2.0
static const double ZOOM_STEP = 0.02
static const double ROTATION_RADIAN_PER_PIXEL = 0.003
Protected Attributes
int window_width_ = 0
int window_height_ = 0
ccBBox bounding_box_
Eigen::Vector3d eye_
Eigen::Vector3d lookat_
Eigen::Vector3d up_
Eigen::Vector3d front_
Eigen::Vector3d right_
double distance_
double field_of_view_
double zoom_
double view_ratio_
double aspect_
double z_near_
double z_far_
double constant_z_near_ = -1
double constant_z_far_ = -1
gl_util::GLMatrix4f projection_matrix_
gl_util::GLMatrix4f view_matrix_
gl_util::GLMatrix4f model_matrix_
gl_util::GLMatrix4f MVP_matrix_
Eigen::Vector3d start_local_rotate_up_
Eigen::Vector3d start_local_rotate_right_
Eigen::Vector3d start_local_rotate_front_
Eigen::Vector3d start_local_rotate_eye_
Eigen::Vector3d start_local_rotate_lookat_
double local_rotate_up_accum_
double local_rotate_right_accum_
Detailed Description
View controller for visualizer.
Definition at line 25 of file ViewControl.h.
Member Enumeration Documentation
ProjectionType
enum cloudViewer::visualization::ViewControl::ProjectionType
Enumerator
Perspective
Orthogonal
Definition at line 39 of file ViewControl.h.
Constructor & Destructor Documentation
~ViewControl()
virtual cloudViewer::visualization::ViewControl::~ViewControl () inline virtual
Definition at line 45 of file ViewControl.h.
Member Function Documentation
CameraLocalRotate()
void cloudViewer::visualization::ViewControl::CameraLocalRotate (double x, double y, double xo = 0.0, double yo = 0.0) virtual
Definition at line 317 of file ViewControl.cpp.
References distance_, front_, local_rotate_right_accum_, local_rotate_up_accum_, lookat_, M_PI, SetProjectionParameters(), start_local_rotate_eye_, start_local_rotate_front_, start_local_rotate_lookat_, start_local_rotate_right_, start_local_rotate_up_, up_, view_ratio_, and window_height_.
CameraLocalTranslate()
void cloudViewer::visualization::ViewControl::CameraLocalTranslate (double forward, double right, double up) virtual
Definition at line 309 of file ViewControl.cpp.
References front_, lookat_, right_, SetProjectionParameters(), and up_.
ChangeFieldOfView()
void cloudViewer::visualization::ViewControl::ChangeFieldOfView (double step) virtual
Function to change field of view.
Parameters
step The step to change field of view.
Reimplemented in cloudViewer::visualization::ViewControlWithEditing, and cloudViewer::visualization::ViewControlWithCustomAnimation.
Definition at line 264 of file ViewControl.cpp.
References field_of_view_, FIELD_OF_VIEW_MAX, FIELD_OF_VIEW_MIN, FIELD_OF_VIEW_STEP, max(), min(), and SetProjectionParameters().
Referenced by cloudViewer::visualization::ViewControlWithCustomAnimation::ChangeFieldOfView(), and cloudViewer::visualization::ViewControlWithEditing::ChangeFieldOfView().
ChangeWindowSize()
void cloudViewer::visualization::ViewControl::ChangeWindowSize (int width, int height) virtual
Definition at line 272 of file ViewControl.cpp.
References aspect_, height, SetProjectionParameters(), width, window_height_, and window_width_.
ConvertFromPinholeCameraParameters()
bool cloudViewer::visualization::ViewControl::ConvertFromPinholeCameraParameters (const camera::PinholeCameraParameters & parameters, bool allow_arbitrary = false)
Function to get view controller from pinhole camera parameters.
Parameters
parameters The pinhole camera parameter to convert from.
allow_arbitrary Allow an arbitrary pinhole camera parameters. This can be useful to render images or depthmaps without any restriction in window size, FOV and zoom.
Definition at line 173 of file ViewControl.cpp.
References abs(), bounding_box_, distance_, dot(), cloudViewer::camera::PinholeCameraParameters::extrinsic_, eye_, field_of_view_, FIELD_OF_VIEW_MAX, FIELD_OF_VIEW_MIN, front_, ccBBox::GetCenter(), ccBBox::GetMaxExtent(), GetProjectionType(), cloudViewer::camera::PinholeCameraParameters::intrinsic_, LogWarning, lookat_, M_PI, max(), min(), right_, up_, view_ratio_, window_height_, window_width_, zoom_, ZOOM_MAX, and ZOOM_MIN.
Referenced by cloudViewer::visualization::ViewControlWithCustomAnimation::LoadTrajectoryFromCameraTrajectory().
ConvertFromViewParameters()
bool cloudViewer::visualization::ViewControl::ConvertFromViewParameters (const ViewParameters & status)
Definition at line 97 of file ViewControl.cpp.
References bounding_box_, cloudViewer::visualization::ViewParameters::boundingbox_max_, cloudViewer::visualization::ViewParameters::boundingbox_min_, field_of_view_, cloudViewer::visualization::ViewParameters::field_of_view_, front_, cloudViewer::visualization::ViewParameters::front_, ccBBox::IsEmpty(), lookat_, cloudViewer::visualization::ViewParameters::lookat_, cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), SetProjectionParameters(), cloudViewer::BoundingBoxTpl< T >::setValidity(), up_, cloudViewer::visualization::ViewParameters::up_, zoom_, and cloudViewer::visualization::ViewParameters::zoom_.
Referenced by cloudViewer::visualization::ViewControlWithEditing::SetEditingMode(), and cloudViewer::visualization::ViewControlWithCustomAnimation::SetViewControlFromTrajectory().
ConvertToPinholeCameraParameters()
bool cloudViewer::visualization::ViewControl::ConvertToPinholeCameraParameters (camera::PinholeCameraParameters & parameters)
Function to get equivalent pinhole camera parameters (does not support orthogonal since it is not a real camera view).
Parameters
The pinhole camera parameter to convert to.
Definition at line 130 of file ViewControl.cpp.
References cloudViewer::camera::PinholeCameraParameters::extrinsic_, eye_, field_of_view_, front_, GetProjectionType(), cloudViewer::camera::PinholeCameraParameters::intrinsic_, LogWarning, M_PI, right_, SetProjectionParameters(), up_, window_height_, and window_width_.
ConvertToViewParameters()
bool cloudViewer::visualization::ViewControl::ConvertToViewParameters (ViewParameters & status) const
Function to get equivalent view parameters (support orthogonal)
Definition at line 86 of file ViewControl.cpp.
References bounding_box_, cloudViewer::visualization::ViewParameters::boundingbox_max_, cloudViewer::visualization::ViewParameters::boundingbox_min_, field_of_view_, cloudViewer::visualization::ViewParameters::field_of_view_, front_, cloudViewer::visualization::ViewParameters::front_, ccBBox::GetMaxBound(), ccBBox::GetMinBound(), lookat_, cloudViewer::visualization::ViewParameters::lookat_, up_, cloudViewer::visualization::ViewParameters::up_, zoom_, and cloudViewer::visualization::ViewParameters::zoom_.
Referenced by cloudViewer::visualization::ViewControlWithCustomAnimation::AddKeyFrame(), cloudViewer::visualization::ViewControlWithCustomAnimation::LoadTrajectoryFromCameraTrajectory(), cloudViewer::visualization::ViewControlWithEditing::SetEditingMode(), and cloudViewer::visualization::ViewControlWithCustomAnimation::UpdateKeyFrame().
FitInGeometry()
void cloudViewer::visualization::ViewControl::FitInGeometry (const ccHObject & geometry) inline
Definition at line 135 of file ViewControl.h.
References CV_TYPES::BBOX, bounding_box_, CV_TYPES::FACET, ccBBox::GetAxisAlignedBoundingBox(), CV_TYPES::IMAGE2, ccObject::isKindOf(), CV_TYPES::LINESET, CV_TYPES::MESH, CV_TYPES::MESH_BASE, CV_TYPES::ORIENTED_BBOX, CV_TYPES::POINT_CLOUD, CV_TYPES::POINT_OCTREE2, CV_TYPES::POLY_LINE, CV_TYPES::RGBD_IMAGE, SetProjectionParameters(), and CV_TYPES::VOXEL_GRID.
GetBoundingBox()
const ccBBox& cloudViewer::visualization::ViewControl::GetBoundingBox () const inline
Definition at line 131 of file ViewControl.h.
References bounding_box_.
Referenced by cloudViewer::visualization::Visualizer::BuildUtilities(), and cloudViewer::visualization::SelectionPolygon::CreateSelectionPolygonVolume().
GetEye()
gl_util::GLVector3f cloudViewer::visualization::ViewControl::GetEye () const inline
Definition at line 162 of file ViewControl.h.
References eye_.
GetFieldOfView()
double cloudViewer::visualization::ViewControl::GetFieldOfView () const inline
Function to get field of view.
Definition at line 155 of file ViewControl.h.
References field_of_view_.
GetFront()
gl_util::GLVector3f cloudViewer::visualization::ViewControl::GetFront () const inline
Definition at line 165 of file ViewControl.h.
References front_.
GetLookat()
gl_util::GLVector3f cloudViewer::visualization::ViewControl::GetLookat () const inline
Definition at line 163 of file ViewControl.h.
References lookat_.
GetModelMatrix()
gl_util::GLMatrix4f cloudViewer::visualization::ViewControl::GetModelMatrix () const inline
Definition at line 161 of file ViewControl.h.
References model_matrix_.
GetMVPMatrix()
gl_util::GLMatrix4f cloudViewer::visualization::ViewControl::GetMVPMatrix () const inline
Definition at line 156 of file ViewControl.h.
References MVP_matrix_.
Referenced by cloudViewer::visualization::SelectionPolygon::CreateSelectionPolygonVolume().
GetProjectionMatrix()
gl_util::GLMatrix4f cloudViewer::visualization::ViewControl::GetProjectionMatrix () const inline
Definition at line 157 of file ViewControl.h.
References projection_matrix_.
GetProjectionType()
ViewControl::ProjectionType cloudViewer::visualization::ViewControl::GetProjectionType () const
Definition at line 230 of file ViewControl.cpp.
References field_of_view_, FIELD_OF_VIEW_MIN, and cloudViewer::visualization::gl_util::Perspective().
Referenced by cloudViewer::visualization::ViewControlWithCustomAnimation::ChangeFieldOfView(), ConvertFromPinholeCameraParameters(), ConvertToPinholeCameraParameters(), SetProjectionParameters(), and SetViewMatrices().
GetRight()
gl_util::GLVector3f cloudViewer::visualization::ViewControl::GetRight () const inline
Definition at line 166 of file ViewControl.h.
References right_.
GetUp()
gl_util::GLVector3f cloudViewer::visualization::ViewControl::GetUp () const inline
Definition at line 164 of file ViewControl.h.
References up_.
GetViewMatrix()
gl_util::GLMatrix4f cloudViewer::visualization::ViewControl::GetViewMatrix () const inline
Definition at line 160 of file ViewControl.h.
References view_matrix_.
GetWindowHeight()
int cloudViewer::visualization::ViewControl::GetWindowHeight () const inline
Definition at line 168 of file ViewControl.h.
References window_height_.
Referenced by cloudViewer::visualization::SelectionPolygon::CreateSelectionPolygonVolume().
GetWindowWidth()
int cloudViewer::visualization::ViewControl::GetWindowWidth () const inline
Definition at line 167 of file ViewControl.h.
References window_width_.
Referenced by cloudViewer::visualization::SelectionPolygon::CreateSelectionPolygonVolume().
GetZFar()
double cloudViewer::visualization::ViewControl::GetZFar () const inline
Definition at line 170 of file ViewControl.h.
References z_far_.
GetZNear()
double cloudViewer::visualization::ViewControl::GetZNear () const inline
Definition at line 169 of file ViewControl.h.
References z_near_.
Reset()
void cloudViewer::visualization::ViewControl::Reset () virtual
Reimplemented in cloudViewer::visualization::ViewControlWithEditing, and cloudViewer::visualization::ViewControlWithCustomAnimation.
Definition at line 238 of file ViewControl.cpp.
References bounding_box_, field_of_view_, FIELD_OF_VIEW_DEFAULT, front_, ccBBox::GetCenter(), lookat_, SetProjectionParameters(), up_, zoom_, and ZOOM_DEFAULT.
Referenced by cloudViewer::visualization::ViewControlWithCustomAnimation::Reset(), and cloudViewer::visualization::ViewControlWithEditing::Reset().
ResetBoundingBox()
void cloudViewer::visualization::ViewControl::ResetBoundingBox () inline
Definition at line 133 of file ViewControl.h.
References bounding_box_, and cloudViewer::BoundingBoxTpl< T >::clear().
ResetCameraLocalRotate()
void cloudViewer::visualization::ViewControl::ResetCameraLocalRotate () virtual
Definition at line 360 of file ViewControl.cpp.
References eye_, front_, local_rotate_right_accum_, local_rotate_up_accum_, lookat_, right_, start_local_rotate_eye_, start_local_rotate_front_, start_local_rotate_lookat_, start_local_rotate_right_, start_local_rotate_up_, and up_.
Referenced by SetProjectionParameters().
Roll()
void cloudViewer::visualization::ViewControl::Roll (double x) virtual
Parameters
x is the distances the mouse cursor has moved. Coordinates are measured in screen coordinates relative to the top-left corner of the window client area.
Definition at line 370 of file ViewControl.cpp.
References front_, ROTATION_RADIAN_PER_PIXEL, SetProjectionParameters(), and up_.
Rotate()
void cloudViewer::visualization::ViewControl::Rotate (double x, double y, double xo = 0.0, double yo = 0.0) virtual
Function to process rotation.
Coordinates are measured in screen coordinates relative to the top-left corner of the window client area.
Parameters
x The distance the mouse cursor has moved in x-axis.
y The distance the mouse cursor has moved in y-axis.
xo Original point coordinate of the mouse in x-axis.
yo Original point coordinate of the mouse in y-axis.
Reimplemented in cloudViewer::visualization::ViewControlWithEditing, and cloudViewer::visualization::ViewControlWithCustomAnimation.
Definition at line 284 of file ViewControl.cpp.
References front_, right_, ROTATION_RADIAN_PER_PIXEL, SetProjectionParameters(), and up_.
Referenced by cloudViewer::visualization::ViewControlWithCustomAnimation::AddSpinKeyFrames(), cloudViewer::visualization::ViewControlWithCustomAnimation::Rotate(), and cloudViewer::visualization::ViewControlWithEditing::Rotate().
Scale()
void cloudViewer::visualization::ViewControl::Scale (double scale) virtual
Function to process scaling
Parameters
scale is the scale ratio.
Reimplemented in cloudViewer::visualization::ViewControlWithEditing, and cloudViewer::visualization::ViewControlWithCustomAnimation.
Definition at line 279 of file ViewControl.cpp.
References max(), min(), SetProjectionParameters(), zoom_, ZOOM_MAX, ZOOM_MIN, and ZOOM_STEP.
Referenced by cloudViewer::visualization::ViewControlWithCustomAnimation::Scale(), and cloudViewer::visualization::ViewControlWithEditing::Scale().
SetConstantZFar()
void cloudViewer::visualization::ViewControl::SetConstantZFar (double z_far) inline
Function to change the far z-plane of the visualizer to a constant value, i.e., independent of zoom and bounding box size.
Parameters
z_far The depth of the far z-plane of the visualizer.
Definition at line 181 of file ViewControl.h.
References constant_z_far_.
SetConstantZNear()
void cloudViewer::visualization::ViewControl::SetConstantZNear (double z_near) inline
Function to change the near z-plane of the visualizer to a constant value, i.e., independent of zoom and bounding box size.
Parameters
z_near The depth of the near z-plane of the visualizer.
Definition at line 176 of file ViewControl.h.
References constant_z_near_.
SetFront()
void cloudViewer::visualization::ViewControl::SetFront (const Eigen::Vector3d & front)
Definition at line 120 of file ViewControl.cpp.
References front_, and SetProjectionParameters().
Referenced by cloudViewer::visualization::DrawGeometries().
SetLookat()
void cloudViewer::visualization::ViewControl::SetLookat (const Eigen::Vector3d & lookat)
Definition at line 110 of file ViewControl.cpp.
References lookat_, and SetProjectionParameters().
Referenced by cloudViewer::visualization::DrawGeometries().
SetProjectionParameters()
void cloudViewer::visualization::ViewControl::SetProjectionParameters ()
Definition at line 247 of file ViewControl.cpp.
References bounding_box_, distance_, eye_, field_of_view_, FIELD_OF_VIEW_STEP, front_, ccBBox::GetMaxExtent(), GetProjectionType(), lookat_, M_PI, cloudViewer::visualization::gl_util::Perspective(), ResetCameraLocalRotate(), right_, up_, view_ratio_, and zoom_.
Referenced by CameraLocalRotate(), CameraLocalTranslate(), ChangeFieldOfView(), cloudViewer::visualization::ViewControlWithCustomAnimation::ChangeFieldOfView(), ChangeWindowSize(), ConvertFromViewParameters(), ConvertToPinholeCameraParameters(), FitInGeometry(), Reset(), cloudViewer::visualization::ViewControlWithEditing::Reset(), Roll(), cloudViewer::visualization::ViewControlWithEditing::Rotate(), Rotate(), Scale(), SetFront(), SetLookat(), SetUp(), SetZoom(), and Translate().
SetUp()
void cloudViewer::visualization::ViewControl::SetUp (const Eigen::Vector3d & up)
Definition at line 115 of file ViewControl.cpp.
References SetProjectionParameters(), and up_.
Referenced by cloudViewer::visualization::DrawGeometries().
SetViewMatrices()
void cloudViewer::visualization::ViewControl::SetViewMatrices (const Eigen::Matrix4d & model_matrix = Eigen::Matrix4d::Identity())
Function to set view points This function obtains OpenGL context and calls OpenGL functions to set the view point.
Definition at line 38 of file ViewControl.cpp.
References aspect_, bounding_box_, constant_z_far_, constant_z_near_, distance_, eye_, field_of_view_, ccBBox::GetMaxExtent(), GetProjectionType(), LogWarning, cloudViewer::visualization::gl_util::LookAt(), lookat_, max(), model_matrix_, MVP_matrix_, cloudViewer::visualization::gl_util::Ortho(), cloudViewer::visualization::gl_util::Perspective(), projection_matrix_, up_, view_matrix_, view_ratio_, window_height_, window_width_, z_far_, and z_near_.
SetZoom()
void cloudViewer::visualization::ViewControl::SetZoom (const double zoom)
Definition at line 125 of file ViewControl.cpp.
References SetProjectionParameters(), and zoom_.
Referenced by cloudViewer::visualization::DrawGeometries().
Translate()
void cloudViewer::visualization::ViewControl::Translate (double x, double y, double xo = 0.0, double yo = 0.0) virtual
Function to process translation.
Coordinates are measured in screen coordinates relative to the top-left corner of the window client area.
Parameters
x Distance the mouse cursor has moved in x-axis.
y Distance the mouse cursor has moved in y-axis.
xo Original point coordinate of the mouse in x-axis.
yo Original point coordinate of the mouse in y-axis.
Reimplemented in cloudViewer::visualization::ViewControlWithEditing, and cloudViewer::visualization::ViewControlWithCustomAnimation.
Definition at line 298 of file ViewControl.cpp.
References eye_, lookat_, right_, SetProjectionParameters(), up_, view_ratio_, and window_height_.
Referenced by cloudViewer::visualization::ViewControlWithCustomAnimation::Translate(), and cloudViewer::visualization::ViewControlWithEditing::Translate().
UnsetConstantZFar()
void cloudViewer::visualization::ViewControl::UnsetConstantZFar () inline
Function to remove a previously set constant z far value, i.e., far z-plane of the visualizer is dynamically set dependent on zoom and bounding box size.
Definition at line 189 of file ViewControl.h.
References constant_z_far_.
UnsetConstantZNear()
void cloudViewer::visualization::ViewControl::UnsetConstantZNear () inline
Function to remove a previously set constant z near value, i.e., near z-plane of the visualizer is dynamically set dependent on zoom and bounding box size.
Definition at line 185 of file ViewControl.h.
References constant_z_near_.
Member Data Documentation
aspect_
double cloudViewer::visualization::ViewControl::aspect_ protected
Definition at line 204 of file ViewControl.h.
Referenced by ChangeWindowSize(), and SetViewMatrices().
bounding_box_
ccBBox cloudViewer::visualization::ViewControl::bounding_box_ protected
Definition at line 194 of file ViewControl.h.
Referenced by ConvertFromPinholeCameraParameters(), ConvertFromViewParameters(), ConvertToViewParameters(), FitInGeometry(), GetBoundingBox(), Reset(), cloudViewer::visualization::ViewControlWithEditing::Reset(), ResetBoundingBox(), SetProjectionParameters(), and SetViewMatrices().
constant_z_far_
double cloudViewer::visualization::ViewControl::constant_z_far_ = -1 protected
Definition at line 208 of file ViewControl.h.
Referenced by SetConstantZFar(), SetViewMatrices(), and UnsetConstantZFar().
constant_z_near_
double cloudViewer::visualization::ViewControl::constant_z_near_ = -1 protected
Definition at line 207 of file ViewControl.h.
Referenced by SetConstantZNear(), SetViewMatrices(), and UnsetConstantZNear().
distance_
double cloudViewer::visualization::ViewControl::distance_ protected
Definition at line 200 of file ViewControl.h.
Referenced by CameraLocalRotate(), ConvertFromPinholeCameraParameters(), SetProjectionParameters(), and SetViewMatrices().
eye_
Eigen::Vector3d cloudViewer::visualization::ViewControl::eye_ protected
Definition at line 195 of file ViewControl.h.
Referenced by ConvertFromPinholeCameraParameters(), ConvertToPinholeCameraParameters(), GetEye(), ResetCameraLocalRotate(), SetProjectionParameters(), SetViewMatrices(), and Translate().
field_of_view_
double cloudViewer::visualization::ViewControl::field_of_view_ protected
Definition at line 201 of file ViewControl.h.
Referenced by ChangeFieldOfView(), cloudViewer::visualization::ViewControlWithCustomAnimation::ChangeFieldOfView(), ConvertFromPinholeCameraParameters(), ConvertFromViewParameters(), ConvertToPinholeCameraParameters(), ConvertToViewParameters(), GetFieldOfView(), GetProjectionType(), Reset(), cloudViewer::visualization::ViewControlWithEditing::Reset(), SetProjectionParameters(), and SetViewMatrices().
FIELD_OF_VIEW_DEFAULT
const double cloudViewer::visualization::ViewControl::FIELD_OF_VIEW_DEFAULT = 60.0 static
Definition at line 29 of file ViewControl.h.
Referenced by Reset().
FIELD_OF_VIEW_MAX
const double cloudViewer::visualization::ViewControl::FIELD_OF_VIEW_MAX = 90.0 static
Definition at line 27 of file ViewControl.h.
Referenced by ChangeFieldOfView(), and ConvertFromPinholeCameraParameters().
FIELD_OF_VIEW_MIN
const double cloudViewer::visualization::ViewControl::FIELD_OF_VIEW_MIN = 5.0 static
Definition at line 28 of file ViewControl.h.
Referenced by ChangeFieldOfView(), ConvertFromPinholeCameraParameters(), GetProjectionType(), cloudViewer::visualization::ViewControlWithCustomAnimation::IsValidPinholeCameraTrajectory(), and cloudViewer::visualization::ViewControlWithEditing::Reset().
FIELD_OF_VIEW_STEP
const double cloudViewer::visualization::ViewControl::FIELD_OF_VIEW_STEP = 5.0 static
Definition at line 30 of file ViewControl.h.
Referenced by ChangeFieldOfView(), and SetProjectionParameters().
front_
Eigen::Vector3d cloudViewer::visualization::ViewControl::front_ protected
Definition at line 198 of file ViewControl.h.
Referenced by CameraLocalRotate(), CameraLocalTranslate(), ConvertFromPinholeCameraParameters(), ConvertFromViewParameters(), ConvertToPinholeCameraParameters(), ConvertToViewParameters(), GetFront(), Reset(), cloudViewer::visualization::ViewControlWithEditing::Reset(), ResetCameraLocalRotate(), Roll(), Rotate(), SetFront(), and SetProjectionParameters().
local_rotate_right_accum_
double cloudViewer::visualization::ViewControl::local_rotate_right_accum_ protected
Definition at line 220 of file ViewControl.h.
Referenced by CameraLocalRotate(), and ResetCameraLocalRotate().
local_rotate_up_accum_
double cloudViewer::visualization::ViewControl::local_rotate_up_accum_ protected
Definition at line 219 of file ViewControl.h.
Referenced by CameraLocalRotate(), and ResetCameraLocalRotate().
lookat_
Eigen::Vector3d cloudViewer::visualization::ViewControl::lookat_ protected
Definition at line 196 of file ViewControl.h.
Referenced by CameraLocalRotate(), CameraLocalTranslate(), ConvertFromPinholeCameraParameters(), ConvertFromViewParameters(), ConvertToViewParameters(), GetLookat(), Reset(), cloudViewer::visualization::ViewControlWithEditing::Reset(), ResetCameraLocalRotate(), SetLookat(), SetProjectionParameters(), SetViewMatrices(), and Translate().
model_matrix_
gl_util::GLMatrix4f cloudViewer::visualization::ViewControl::model_matrix_ protected
Definition at line 211 of file ViewControl.h.
Referenced by GetModelMatrix(), and SetViewMatrices().
MVP_matrix_
gl_util::GLMatrix4f cloudViewer::visualization::ViewControl::MVP_matrix_ protected
Definition at line 212 of file ViewControl.h.
Referenced by GetMVPMatrix(), and SetViewMatrices().
projection_matrix_
gl_util::GLMatrix4f cloudViewer::visualization::ViewControl::projection_matrix_ protected
Definition at line 209 of file ViewControl.h.
Referenced by GetProjectionMatrix(), and SetViewMatrices().
right_
Eigen::Vector3d cloudViewer::visualization::ViewControl::right_ protected
Definition at line 199 of file ViewControl.h.
Referenced by CameraLocalTranslate(), ConvertFromPinholeCameraParameters(), ConvertToPinholeCameraParameters(), GetRight(), ResetCameraLocalRotate(), cloudViewer::visualization::ViewControlWithEditing::Rotate(), Rotate(), SetProjectionParameters(), and Translate().
ROTATION_RADIAN_PER_PIXEL
const double cloudViewer::visualization::ViewControl::ROTATION_RADIAN_PER_PIXEL = 0.003 static
Definition at line 37 of file ViewControl.h.
Referenced by cloudViewer::visualization::ViewControlWithCustomAnimation::AddSpinKeyFrames(), Roll(), and Rotate().
start_local_rotate_eye_
Eigen::Vector3d cloudViewer::visualization::ViewControl::start_local_rotate_eye_ protected
Definition at line 217 of file ViewControl.h.
Referenced by CameraLocalRotate(), and ResetCameraLocalRotate().
start_local_rotate_front_
Eigen::Vector3d cloudViewer::visualization::ViewControl::start_local_rotate_front_ protected
Definition at line 216 of file ViewControl.h.
Referenced by CameraLocalRotate(), and ResetCameraLocalRotate().
start_local_rotate_lookat_
Eigen::Vector3d cloudViewer::visualization::ViewControl::start_local_rotate_lookat_ protected
Definition at line 218 of file ViewControl.h.
Referenced by CameraLocalRotate(), and ResetCameraLocalRotate().
start_local_rotate_right_
Eigen::Vector3d cloudViewer::visualization::ViewControl::start_local_rotate_right_ protected
Definition at line 215 of file ViewControl.h.
Referenced by CameraLocalRotate(), and ResetCameraLocalRotate().
start_local_rotate_up_
Eigen::Vector3d cloudViewer::visualization::ViewControl::start_local_rotate_up_ protected
Definition at line 214 of file ViewControl.h.
Referenced by CameraLocalRotate(), and ResetCameraLocalRotate().
up_
Eigen::Vector3d cloudViewer::visualization::ViewControl::up_ protected
Definition at line 197 of file ViewControl.h.
Referenced by CameraLocalRotate(), CameraLocalTranslate(), ConvertFromPinholeCameraParameters(), ConvertFromViewParameters(), ConvertToPinholeCameraParameters(), ConvertToViewParameters(), GetUp(), Reset(), cloudViewer::visualization::ViewControlWithEditing::Reset(), ResetCameraLocalRotate(), Roll(), cloudViewer::visualization::ViewControlWithEditing::Rotate(), Rotate(), SetProjectionParameters(), SetUp(), SetViewMatrices(), and Translate().
view_matrix_
gl_util::GLMatrix4f cloudViewer::visualization::ViewControl::view_matrix_ protected
Definition at line 210 of file ViewControl.h.
Referenced by GetViewMatrix(), and SetViewMatrices().
view_ratio_
double cloudViewer::visualization::ViewControl::view_ratio_ protected
Definition at line 203 of file ViewControl.h.
Referenced by CameraLocalRotate(), ConvertFromPinholeCameraParameters(), SetProjectionParameters(), SetViewMatrices(), and Translate().
window_height_
int cloudViewer::visualization::ViewControl::window_height_ = 0 protected
Definition at line 193 of file ViewControl.h.
Referenced by CameraLocalRotate(), ChangeWindowSize(), ConvertFromPinholeCameraParameters(), ConvertToPinholeCameraParameters(), GetWindowHeight(), cloudViewer::visualization::ViewControlWithEditing::Rotate(), SetViewMatrices(), and Translate().
window_width_
int cloudViewer::visualization::ViewControl::window_width_ = 0 protected
Definition at line 192 of file ViewControl.h.
Referenced by ChangeWindowSize(), ConvertFromPinholeCameraParameters(), ConvertToPinholeCameraParameters(), GetWindowWidth(), cloudViewer::visualization::ViewControlWithEditing::Rotate(), and SetViewMatrices().
z_far_
double cloudViewer::visualization::ViewControl::z_far_ protected
Definition at line 206 of file ViewControl.h.
Referenced by GetZFar(), and SetViewMatrices().
z_near_
double cloudViewer::visualization::ViewControl::z_near_ protected
Definition at line 205 of file ViewControl.h.
Referenced by GetZNear(), and SetViewMatrices().
zoom_
double cloudViewer::visualization::ViewControl::zoom_ protected
Definition at line 202 of file ViewControl.h.
Referenced by ConvertFromPinholeCameraParameters(), ConvertFromViewParameters(), ConvertToViewParameters(), Reset(), cloudViewer::visualization::ViewControlWithEditing::Reset(), Scale(), SetProjectionParameters(), and SetZoom().
ZOOM_DEFAULT
const double cloudViewer::visualization::ViewControl::ZOOM_DEFAULT = 0.7 static
Definition at line 32 of file ViewControl.h.
Referenced by Reset(), and cloudViewer::visualization::ViewControlWithEditing::Reset().
ZOOM_MAX
const double cloudViewer::visualization::ViewControl::ZOOM_MAX = 2.0 static
Definition at line 34 of file ViewControl.h.
Referenced by ConvertFromPinholeCameraParameters(), and Scale().
ZOOM_MIN
const double cloudViewer::visualization::ViewControl::ZOOM_MIN = 0.02 static
Definition at line 33 of file ViewControl.h.
Referenced by ConvertFromPinholeCameraParameters(), and Scale().
ZOOM_STEP
const double cloudViewer::visualization::ViewControl::ZOOM_STEP = 0.02 static
Definition at line 35 of file ViewControl.h.
Referenced by Scale().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/ViewControl.h
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/ViewControl.cpp