ACloudViewer: VtkUtils::VtkWidget Class Reference
VtkUtils::VtkWidget Class Reference
#include <vtkwidget.h>
Public Member Functions
VtkWidget (QWidget *parent=nullptr)
virtual ~VtkWidget ()
void setMultiViewports (bool multi=true)
bool multiViewports () const
void createActorFromVTKDataSet (const vtkSmartPointer< vtkDataSet > &data, vtkSmartPointer< vtkLODActor > &actor, bool use_scalars=true)
void addActor (vtkProp *actor, const QColor &clr=Qt::black)
void addViewProp (vtkProp *prop)
QList< vtkProp * > actors () const
void setActorsVisible (bool visible)
void setActorVisible (vtkProp *actor, bool visible)
bool actorVisible (vtkProp *actor)
void setBackgroundColor (const QColor &clr)
void setBackgroundColor ()
QColor backgroundColor () const
vtkRenderer * defaultRenderer ()
bool defaultRendererTaken () const
void showOrientationMarker (bool show=true)
vtkRenderWindow * GetRenderWindow ()
QVTKInteractor * GetInteractor ()
Protected Member Functions
void setBounds (double *bounds)
double xMin () const
double xMax () const
double yMin () const
double yMax () const
double zMin () const
double zMax () const
Detailed Description
Definition at line 37 of file vtkwidget.h.
Constructor & Destructor Documentation
VtkWidget()
VtkUtils::VtkWidget::VtkWidget (QWidget * parent = nullptr) explicit
Definition at line 130 of file vtkwidget.cpp.
References defaultRenderer().
~VtkWidget()
VtkUtils::VtkWidget::~VtkWidget () virtual
Definition at line 136 of file vtkwidget.cpp.
Member Function Documentation
actors()
QList< vtkProp * > VtkUtils::VtkWidget::actors () const
Definition at line 276 of file vtkwidget.cpp.
actorVisible()
bool VtkUtils::VtkWidget::actorVisible (vtkProp * actor)
Definition at line 286 of file vtkwidget.cpp.
addActor()
void VtkUtils::VtkWidget::addActor (vtkProp * actor, const QColor & clr = Qt::black)
Definition at line 204 of file vtkwidget.cpp.
References defaultRenderer(), defaultRendererTaken(), GetRenderWindow(), and Utils::vtkColor().
addViewProp()
void VtkUtils::VtkWidget::addViewProp (vtkProp * prop)
Definition at line 244 of file vtkwidget.cpp.
References defaultRenderer(), defaultRendererTaken(), and GetRenderWindow().
backgroundColor()
QColor VtkUtils::VtkWidget::backgroundColor () const
Definition at line 311 of file vtkwidget.cpp.
createActorFromVTKDataSet()
void VtkUtils::VtkWidget::createActorFromVTKDataSet (const vtkSmartPointer< vtkDataSet > & data, vtkSmartPointer< vtkLODActor > & actor, bool use_scalars = true)
FIXME disabling backface culling due to known VTK bug: vtkTextActors are not shown when there is a vtkActor with backface culling on present in the scene Please see VTK bug tracker for more details: http://www.vtk.org/Bug/view.php?id=12588
Definition at line 158 of file vtkwidget.cpp.
References data, and VtkUtils::getDefaultScalarInterpolationForDataSet().
defaultRenderer()
vtkRenderer * VtkUtils::VtkWidget::defaultRenderer ()
Definition at line 313 of file vtkwidget.cpp.
References GetRenderWindow(), and VtkUtils::vtkInitOnce().
Referenced by addActor(), addViewProp(), VtkUtils::Contour::renderSurface(), VtkUtils::Surface::renderSurface(), and VtkWidget().
defaultRendererTaken()
bool VtkUtils::VtkWidget::defaultRendererTaken () const
Definition at line 321 of file vtkwidget.cpp.
Referenced by addActor(), and addViewProp().
GetInteractor()
QVTKInteractor* VtkUtils::VtkWidget::GetInteractor () inline
Definition at line 68 of file vtkwidget.h.
Referenced by showOrientationMarker().
GetRenderWindow()
vtkRenderWindow* VtkUtils::VtkWidget::GetRenderWindow () inline
Definition at line 67 of file vtkwidget.h.
Referenced by addActor(), addViewProp(), defaultRenderer(), and setBackgroundColor().
multiViewports()
bool VtkUtils::VtkWidget::multiViewports () const
Definition at line 144 of file vtkwidget.cpp.
setActorsVisible()
void VtkUtils::VtkWidget::setActorsVisible (bool visible)
Definition at line 278 of file vtkwidget.cpp.
setActorVisible()
void VtkUtils::VtkWidget::setActorVisible (vtkProp * actor, bool visible)
Definition at line 282 of file vtkwidget.cpp.
setBackgroundColor() [1/2]
void VtkUtils::VtkWidget::setBackgroundColor ()
Definition at line 288 of file vtkwidget.cpp.
setBackgroundColor() [2/2]
void VtkUtils::VtkWidget::setBackgroundColor (const QColor & clr)
Definition at line 293 of file vtkwidget.cpp.
References GetRenderWindow().
setBounds()
void VtkUtils::VtkWidget::setBounds (double * bounds) protected
Definition at line 344 of file vtkwidget.cpp.
Referenced by VtkUtils::Contour::renderSurface().
setMultiViewports()
void VtkUtils::VtkWidget::setMultiViewports (bool multi = true)
Definition at line 138 of file vtkwidget.cpp.
showOrientationMarker()
void VtkUtils::VtkWidget::showOrientationMarker (bool show = true)
Definition at line 326 of file vtkwidget.cpp.
References GetInteractor(), and VTK_CREATE.
xMax()
double VtkUtils::VtkWidget::xMax () const protected
Definition at line 351 of file vtkwidget.cpp.
xMin()
double VtkUtils::VtkWidget::xMin () const protected
Definition at line 349 of file vtkwidget.cpp.
yMax()
double VtkUtils::VtkWidget::yMax () const protected
Definition at line 355 of file vtkwidget.cpp.
yMin()
double VtkUtils::VtkWidget::yMin () const protected
Definition at line 353 of file vtkwidget.cpp.
zMax()
double VtkUtils::VtkWidget::zMax () const protected
Definition at line 359 of file vtkwidget.cpp.
Referenced by VtkUtils::Contour::setNumberOfContours().
zMin()
double VtkUtils::VtkWidget::zMin () const protected
Definition at line 357 of file vtkwidget.cpp.
Referenced by VtkUtils::Contour::setNumberOfContours().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/vtkwidget.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/vtkwidget.cpp