ACloudViewer: DL_WriterA Class Reference
DL_WriterA Class Reference
#include <dl_writer_ascii.h>
Public Member Functions
DL_WriterA (const char *fname, DL_Codes::version version=DL_Codes::AC1015)
virtual ~DL_WriterA ()
bool openFailed () const
void close () const
void dxfReal (int gc, double value) const
void dxfInt (int gc, int value) const
void dxfHex (int gc, int value) const
void dxfString (int gc, const char *value) const
void dxfString (int gc, const std::string &value) const
Public Member Functions inherited from DL_Writer
DL_Writer (DL_Codes::version version)
virtual ~DL_Writer ()
void section (const char *name) const
void sectionHeader () const
void sectionTables () const
void sectionBlocks () const
void sectionEntities () const
void sectionClasses () const
void sectionObjects () const
void sectionEnd () const
void table (const char *name, int num, int h=0) const
void tableLayers (int num) const
void tableLinetypes (int num) const
void tableAppid (int num) const
void tableStyle (int num) const
void tableEnd () const
void dxfEOF () const
void comment (const char *text) const
void entity (const char *entTypeName) const
void entityAttributes (const DL_Attributes &attrib) const
void subClass (const char *sub) const
void tableLayerEntry (unsigned long int h=0) const
void tableLinetypeEntry (unsigned long int h=0) const
void tableAppidEntry (unsigned long int h=0) const
void sectionBlockEntry (unsigned long int h=0) const
void sectionBlockEntryEnd (unsigned long int h=0) const
void color (int col=256) const
void linetype (const char *lt) const
void linetypeScale (double scale) const
void lineWeight (int lw) const
void coord (int gc, double x, double y, double z=0) const
void coordTriplet (int gc, const double *value) const
void resetHandle () const
unsigned long handle (int gc=5) const
unsigned long getNextHandle () const
unsigned long incHandle () const
void setModelSpaceHandle (unsigned long h)
unsigned long getModelSpaceHandle ()
void setPaperSpaceHandle (unsigned long h)
unsigned long getPaperSpaceHandle ()
void setPaperSpace0Handle (unsigned long h)
unsigned long getPaperSpace0Handle ()
virtual void dxfBool (int gc, bool value) const
Static Public Member Functions
static void strReplace (char *str, char src, char dest)
Additional Inherited Members
Protected Attributes inherited from DL_Writer
unsigned long m_handle
unsigned long modelSpaceHandle
unsigned long paperSpaceHandle
unsigned long paperSpace0Handle
DL_Codes::version version
Detailed Description
Implements functions defined in DL_Writer for writing low level DXF constructs to an ASCII format DXF file.
@para fname File name of the file to be created. @para version DXF version. Defaults to DL_VERSION_2002.
Todo:
What if fname is NULL? Or fname can't be opened for another reason?
Definition at line 50 of file dl_writer_ascii.h.
Constructor & Destructor Documentation
DL_WriterA()
DL_WriterA::DL_WriterA (const char * fname, DL_Codes::version version = DL_Codes::AC1015) inline
Definition at line 52 of file dl_writer_ascii.h.
~DL_WriterA()
virtual DL_WriterA::~DL_WriterA () inline virtual
Definition at line 54 of file dl_writer_ascii.h.
Member Function Documentation
close()
void DL_WriterA::close () const
Closes the output file.
Definition at line 40 of file dl_writer_ascii.cpp.
Referenced by main(), DxfProfilesExporter::SaveHorizontalProfiles(), DxfFilter::saveToFile(), DxfProfilesExporter::SaveVerticalProfiles(), and testWriting().
dxfHex()
void DL_WriterA::dxfHex (int gc, int value) const virtual
Writes a hex int variable to the DXF file.
Parameters
gc Group code.
value Int value
Implements DL_Writer.
Definition at line 102 of file dl_writer_ascii.cpp.
References dxfString().
Referenced by DL_Dxf::writeAppDictionary(), DL_Dxf::writeBlockRecord(), DL_Dxf::writeDictionaryEntry(), DL_Dxf::writeDimStyle(), DL_Dxf::writeHeader(), DL_Dxf::writeImage(), DL_Dxf::writeImageDef(), DL_Dxf::writeLayer(), DL_Dxf::writeObjects(), DL_Dxf::writeUcs(), DL_Dxf::writeView(), DL_Dxf::writeVPort(), and DL_Dxf::writeXRecord().
dxfInt()
void DL_WriterA::dxfInt (int gc, int value) const virtual
Writes an int variable to the DXF file.
Parameters
gc Group code.
value Int value
Implements DL_Writer.
Definition at line 91 of file dl_writer_ascii.cpp.
Referenced by DxfProfilesExporter::SaveHorizontalProfiles(), DxfFilter::saveToFile(), DxfProfilesExporter::SaveVerticalProfiles(), DL_Dxf::writeAppDictionary(), DL_Dxf::writeAppid(), DL_Dxf::writeAttribute(), DL_Dxf::writeBlock(), DL_Dxf::writeBlockRecord(), DL_Dxf::writeDimAligned(), DL_Dxf::writeDimAngular(), DL_Dxf::writeDimAngular3P(), DL_Dxf::writeDimDiametric(), DL_Dxf::writeDimLinear(), DL_Dxf::writeDimOrdinate(), DL_Dxf::writeDimRadial(), DL_Dxf::writeDimStyle(), DL_Dxf::writeDimStyleOverrides(), DL_Dxf::writeHatch1(), DL_Dxf::writeHatch2(), DL_Dxf::writeHatchEdge(), DL_Dxf::writeHatchLoop1(), DL_Dxf::writeHatchLoop2(), DL_Dxf::writeImage(), DL_Dxf::writeImageDef(), DL_Dxf::writeInsert(), DL_Dxf::writeLayer(), DL_Dxf::writeLeader(), DL_Dxf::writeLinetype(), DL_Dxf::writeMText(), DL_Dxf::writeObjects(), DL_Dxf::writePolyline(), DL_Dxf::writeSpline(), DL_Dxf::writeStyle(), DL_Dxf::writeText(), DL_Dxf::writeUcs(), DL_Dxf::writeView(), DL_Dxf::writeVPort(), and DL_Dxf::writeXRecord().
dxfReal()
void DL_WriterA::dxfReal (int gc, double value) const virtual
Writes a real (double) variable to the DXF file.
Parameters
gc Group code.
value Double value
Implements DL_Writer.
Definition at line 54 of file dl_writer_ascii.cpp.
References DL_Codes::AC1009_MIN, dxfString(), strReplace(), and DL_Writer::version.
Referenced by DxfProfilesExporter::SaveHorizontalProfiles(), DxfFilter::saveToFile(), DxfProfilesExporter::SaveVerticalProfiles(), DL_Dxf::writeArc(), DL_Dxf::writeAttribute(), DL_Dxf::writeCircle(), DL_Dxf::writeControlPoint(), DL_Dxf::writeDimAligned(), DL_Dxf::writeDimAngular(), DL_Dxf::writeDimAngular3P(), DL_Dxf::writeDimDiametric(), DL_Dxf::writeDimLinear(), DL_Dxf::writeDimOrdinate(), DL_Dxf::writeDimRadial(), DL_Dxf::writeDimStyle(), DL_Dxf::writeDimStyleOverrides(), DL_Dxf::writeEllipse(), DL_Dxf::writeFitPoint(), DL_Dxf::writeHatch1(), DL_Dxf::writeHatch2(), DL_Dxf::writeHatchEdge(), DL_Dxf::writeImage(), DL_Dxf::writeImageDef(), DL_Dxf::writeInsert(), DL_Dxf::writeKnot(), DL_Dxf::writeLeader(), DL_Dxf::writeLeaderVertex(), DL_Dxf::writeLinetype(), DL_Dxf::writeMText(), DL_Dxf::writeObjects(), DL_Dxf::writeSolid(), DL_Dxf::writeStyle(), DL_Dxf::writeText(), DL_Dxf::writeTrace(), DL_Dxf::writeVertex(), DL_Dxf::writeVPort(), and DL_Dxf::writeXRecord().
dxfString() [1/2]
void DL_WriterA::dxfString (int gc, const char * value) const virtual
Writes a string variable to the DXF file.
Parameters
gc Group code.
value String
Implements DL_Writer.
Definition at line 114 of file dl_writer_ascii.cpp.
References NULL.
Referenced by dxfHex(), dxfReal(), DxfProfilesExporter::SaveHorizontalProfiles(), DxfFilter::saveToFile(), DxfProfilesExporter::SaveVerticalProfiles(), DL_Dxf::write3dFace(), DL_Dxf::writeAppDictionary(), DL_Dxf::writeAppid(), DL_Dxf::writeArc(), DL_Dxf::writeAttribute(), DL_Dxf::writeBlock(), DL_Dxf::writeBlockRecord(), DL_Dxf::writeCircle(), DL_Dxf::writeComment(), DL_Dxf::writeDictionaryEntry(), DL_Dxf::writeDimAligned(), DL_Dxf::writeDimAngular(), DL_Dxf::writeDimAngular3P(), DL_Dxf::writeDimDiametric(), DL_Dxf::writeDimLinear(), DL_Dxf::writeDimOrdinate(), DL_Dxf::writeDimRadial(), DL_Dxf::writeDimStyle(), DL_Dxf::writeDimStyleOverrides(), DL_Dxf::writeEllipse(), DL_Dxf::writeHatch1(), DL_Dxf::writeHatch2(), DL_Dxf::writeHeader(), DL_Dxf::writeImage(), DL_Dxf::writeImageDef(), DL_Dxf::writeInsert(), DL_Dxf::writeLayer(), DL_Dxf::writeLeader(), DL_Dxf::writeLine(), DL_Dxf::writeLinetype(), DL_Dxf::writeMText(), DL_Dxf::writeObjects(), DL_Dxf::writeObjectsEnd(), DL_Dxf::writePoint(), DL_Dxf::writePolyline(), DL_Dxf::writeRay(), DL_Dxf::writeSolid(), DL_Dxf::writeSpline(), DL_Dxf::writeStyle(), DL_Dxf::writeText(), DL_Dxf::writeTrace(), DL_Dxf::writeUcs(), DL_Dxf::writeVertex(), DL_Dxf::writeView(), DL_Dxf::writeVPort(), DL_Dxf::writeXLine(), and DL_Dxf::writeXRecord().
dxfString() [2/2]
void DL_WriterA::dxfString (int gc, const std::string & value) const virtual
Must be overwritten by the implementing class to write a string to the file.
Parameters
gc Group code.
value The string.
Implements DL_Writer.
Definition at line 124 of file dl_writer_ascii.cpp.
openFailed()
bool DL_WriterA::openFailed () const
Return values
true Opening file has failed.
false Otherwise.
Definition at line 46 of file dl_writer_ascii.cpp.
Referenced by DL_Dxf::out().
strReplace()
void DL_WriterA::strReplace (char * str, char src, char dest) static
Replaces every occurence of src with dest in the null terminated str.
Definition at line 132 of file dl_writer_ascii.cpp.
Referenced by dxfReal().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_io/extern/dxflib/src/dl_writer_ascii.h
/root/ACloudViewer/libs/CV_io/extern/dxflib/src/dl_writer_ascii.cpp