ACloudViewer: PdmsTools::PdmsObjects::GenericItem Class Reference
PdmsTools::PdmsObjects::GenericItem Class Reference abstract
Generic item.
#include <PdmsTools.h>
Public Member Functions
GenericItem ()
Default constructor.
virtual ~GenericItem ()
Destructor.
virtual bool setPosition (const CCVector3 &p)
virtual bool setOrientation (const CCVector3 &x, const CCVector3 &y, const CCVector3 &z)
virtual bool convertCoordinateSystem ()
virtual GenericItem * getRoot ()
virtual bool push (GenericItem *i)=0
virtual void remove (GenericItem *i)
virtual bool isGroupElement ()
virtual bool isDesignElement ()
virtual Token getType () const
virtual bool setValue (Token t, PointCoordinateType value)
virtual GenericItem * scan (const char *str)
virtual bool scan (Token t, std::vector< GenericItem * > &array)
virtual std::pair< int, int > write (std::ostream &output, int nbtabs=0) const =0
Public Attributes
GenericItem * owner
Parent imte.
GenericItem * creator
Creator item.
CCVector3 position
Object position.
CCVector3 orientation [3]
Object orientation (X,Y and Z)
bool isCoordinateSystemUpToDate
Coordinate system update flag.
GenericItem * positionReference
Reference object (position)
GenericItem * orientationReferences [3]
Reference(s) object(s) (orientation)
char name [c_max_str_length]
Name.
Protected Member Functions
bool isOrientationValid (unsigned i) const
bool completeOrientation ()
Detailed Description
Generic item.
Definition at line 137 of file PdmsTools.h.
Constructor & Destructor Documentation
GenericItem()
GenericItem::GenericItem ()
Default constructor.
Definition at line 873 of file PdmsTools.cpp.
References name, orientation, and orientationReferences.
~GenericItem()
virtual PdmsTools::PdmsObjects::GenericItem::~GenericItem () inline virtual
Destructor.
Definition at line 162 of file PdmsTools.h.
Member Function Documentation
completeOrientation()
bool GenericItem::completeOrientation () protected
Definition at line 908 of file PdmsTools.cpp.
References Vector3Tpl< Type >::cross(), isOrientationValid(), Vector3Tpl< Type >::normalize(), orientation, and Vector3Tpl< Type >::orthogonal().
Referenced by convertCoordinateSystem().
convertCoordinateSystem()
bool GenericItem::convertCoordinateSystem () virtual
Reimplemented in PdmsTools::PdmsObjects::GroupElement.
Definition at line 969 of file PdmsTools.cpp.
References completeOrientation(), convertCoordinateSystem(), isCoordinateSystemUpToDate, isOrientationValid(), orientation, orientationReferences, owner, position, and positionReference.
Referenced by convertCoordinateSystem(), PdmsTools::PdmsObjects::GroupElement::convertCoordinateSystem(), and PdmsParser::parseSessionContent().
getRoot()
virtual GenericItem* PdmsTools::PdmsObjects::GenericItem::getRoot () inline virtual
Definition at line 172 of file PdmsTools.h.
References owner.
Referenced by PdmsTools::PdmsCommands::Reference::execute(), PdmsTools::PdmsCommands::ElementCreation::execute(), PdmsParser::parseSessionContent(), PdmsParser::processCurrentToken(), and PdmsParser::~PdmsParser().
getType()
virtual Token PdmsTools::PdmsObjects::GenericItem::getType () const inline virtual
Reimplemented in PdmsTools::PdmsObjects::Extrusion, PdmsTools::PdmsObjects::Loop, PdmsTools::PdmsObjects::Vertex, PdmsTools::PdmsObjects::Box, PdmsTools::PdmsObjects::Snout, PdmsTools::PdmsObjects::Pyramid, PdmsTools::PdmsObjects::Cone, PdmsTools::PdmsObjects::Dish, PdmsTools::PdmsObjects::RTorus, PdmsTools::PdmsObjects::CTorus, PdmsTools::PdmsObjects::SCylinder, and PdmsTools::PdmsObjects::GroupElement.
Definition at line 183 of file PdmsTools.h.
References PdmsTools::PDMS_INVALID_TOKEN.
Referenced by PdmsTools::PdmsObjects::GroupElement::push(), PdmsTools::PdmsObjects::Loop::push(), PdmsTools::PdmsObjects::Extrusion::push(), and scan().
isDesignElement()
virtual bool PdmsTools::PdmsObjects::GenericItem::isDesignElement () inline virtual
Reimplemented in PdmsTools::PdmsObjects::DesignElement.
Definition at line 182 of file PdmsTools.h.
Referenced by PdmsTools::PdmsObjects::DesignElement::push().
isGroupElement()
virtual bool PdmsTools::PdmsObjects::GenericItem::isGroupElement () inline virtual
Reimplemented in PdmsTools::PdmsObjects::GroupElement.
Definition at line 181 of file PdmsTools.h.
isOrientationValid()
bool GenericItem::isOrientationValid (unsigned i) const protected
Definition at line 904 of file PdmsTools.cpp.
References cloudViewer::GreaterThanEpsilon(), and orientation.
Referenced by completeOrientation(), and convertCoordinateSystem().
push()
virtual bool PdmsTools::PdmsObjects::GenericItem::push (GenericItem * i) pure virtual
Implemented in PdmsTools::PdmsObjects::Extrusion, PdmsTools::PdmsObjects::Loop, PdmsTools::PdmsObjects::GroupElement, and PdmsTools::PdmsObjects::DesignElement.
Referenced by PdmsTools::PdmsCommands::ElementCreation::execute(), PdmsTools::PdmsObjects::DesignElement::push(), and PdmsTools::PdmsObjects::GroupElement::push().
remove()
virtual void PdmsTools::PdmsObjects::GenericItem::remove (GenericItem * i) inline virtual
Reimplemented in PdmsTools::PdmsObjects::Extrusion, PdmsTools::PdmsObjects::Loop, PdmsTools::PdmsObjects::GroupElement, and PdmsTools::PdmsObjects::DesignElement.
Definition at line 178 of file PdmsTools.h.
Referenced by PdmsTools::PdmsObjects::DesignElement::push(), PdmsTools::PdmsObjects::GroupElement::push(), PdmsTools::PdmsObjects::Loop::push(), and PdmsTools::PdmsObjects::Extrusion::push().
scan() [1/2]
virtual GenericItem* PdmsTools::PdmsObjects::GenericItem::scan (const char * str) inline virtual
Reimplemented in PdmsTools::PdmsObjects::GroupElement.
Definition at line 189 of file PdmsTools.h.
References name.
Referenced by PdmsTools::PdmsCommands::Reference::execute(), PdmsTools::PdmsCommands::ElementCreation::execute(), and PdmsTools::PdmsObjects::GroupElement::scan().
scan() [2/2]
bool GenericItem::scan (Token t, std::vector< GenericItem * > & array) virtual
Reimplemented in PdmsTools::PdmsObjects::GroupElement.
Definition at line 1024 of file PdmsTools.cpp.
References getType(), and memfail.
setOrientation()
bool GenericItem::setOrientation (const CCVector3 & x, const CCVector3 & y, const CCVector3 & z) virtual
Definition at line 895 of file PdmsTools.cpp.
References orientation.
Referenced by PdmsTools::PdmsCommands::Orientation::execute().
setPosition()
bool GenericItem::setPosition (const CCVector3 & p) virtual
Reimplemented in PdmsTools::PdmsObjects::Vertex.
Definition at line 890 of file PdmsTools.cpp.
References position.
Referenced by PdmsTools::PdmsCommands::Position::execute().
setValue()
virtual bool PdmsTools::PdmsObjects::GenericItem::setValue (Token t, PointCoordinateType value) inline virtual
Reimplemented in PdmsTools::PdmsObjects::Extrusion, PdmsTools::PdmsObjects::Box, PdmsTools::PdmsObjects::Snout, PdmsTools::PdmsObjects::Pyramid, PdmsTools::PdmsObjects::Cone, PdmsTools::PdmsObjects::Dish, PdmsTools::PdmsObjects::RTorus, PdmsTools::PdmsObjects::CTorus, and PdmsTools::PdmsObjects::SCylinder.
Definition at line 186 of file PdmsTools.h.
Referenced by PdmsTools::PdmsCommands::NumericalValue::execute(), and PdmsTools::PdmsCommands::DistanceValue::execute().
write()
virtual std::pair<int, int> PdmsTools::PdmsObjects::GenericItem::write (std::ostream & output, int nbtabs = 0) const pure virtual
Implemented in PdmsTools::PdmsObjects::Extrusion, PdmsTools::PdmsObjects::Loop, PdmsTools::PdmsObjects::Vertex, PdmsTools::PdmsObjects::Box, PdmsTools::PdmsObjects::Snout, PdmsTools::PdmsObjects::Pyramid, PdmsTools::PdmsObjects::Cone, PdmsTools::PdmsObjects::Dish, PdmsTools::PdmsObjects::RTorus, PdmsTools::PdmsObjects::CTorus, PdmsTools::PdmsObjects::SCylinder, and PdmsTools::PdmsObjects::GroupElement.
Member Data Documentation
creator
GenericItem* PdmsTools::PdmsObjects::GenericItem::creator
Creator item.
Definition at line 142 of file PdmsTools.h.
Referenced by PdmsTools::PdmsCommands::ElementCreation::execute().
isCoordinateSystemUpToDate
bool PdmsTools::PdmsObjects::GenericItem::isCoordinateSystemUpToDate
Coordinate system update flag.
Definition at line 149 of file PdmsTools.h.
Referenced by convertCoordinateSystem(), and PdmsTools::PdmsObjects::GroupElement::convertCoordinateSystem().
name
char PdmsTools::PdmsObjects::GenericItem::name[c_max_str_length]
Name.
Definition at line 157 of file PdmsTools.h.
Referenced by PdmsTools::PdmsCommands::Name::execute(), PdmsTools::PdmsCommands::ElementCreation::execute(), GenericItem(), PdmsTools::PdmsObjects::GroupElement::GroupElement(), PDMSFilter::loadFile(), scan(), PdmsTools::PdmsObjects::GroupElement::write(), PdmsTools::PdmsObjects::SCylinder::write(), PdmsTools::PdmsObjects::CTorus::write(), PdmsTools::PdmsObjects::RTorus::write(), PdmsTools::PdmsObjects::Dish::write(), PdmsTools::PdmsObjects::Cone::write(), and PdmsTools::PdmsObjects::Box::write().
orientation
CCVector3 PdmsTools::PdmsObjects::GenericItem::orientation[3]
Object orientation (X,Y and Z)
Definition at line 147 of file PdmsTools.h.
Referenced by completeOrientation(), convertCoordinateSystem(), GenericItem(), isOrientationValid(), setOrientation(), PdmsTools::PdmsObjects::SCylinder::write(), PdmsTools::PdmsObjects::CTorus::write(), PdmsTools::PdmsObjects::RTorus::write(), PdmsTools::PdmsObjects::Dish::write(), PdmsTools::PdmsObjects::Cone::write(), and PdmsTools::PdmsObjects::Box::write().
orientationReferences
GenericItem* PdmsTools::PdmsObjects::GenericItem::orientationReferences[3]
Reference(s) object(s) (orientation)
Definition at line 154 of file PdmsTools.h.
Referenced by convertCoordinateSystem(), PdmsTools::PdmsCommands::Orientation::execute(), and GenericItem().
owner
GenericItem* PdmsTools::PdmsObjects::GenericItem::owner
Parent imte.
Definition at line 140 of file PdmsTools.h.
Referenced by convertCoordinateSystem(), PdmsTools::PdmsCommands::Reference::execute(), PdmsTools::PdmsCommands::ElementCreation::execute(), PdmsTools::PdmsCommands::ElementEnding::execute(), getRoot(), PdmsTools::PdmsObjects::DesignElement::push(), PdmsTools::PdmsObjects::GroupElement::push(), PdmsTools::PdmsObjects::Loop::push(), and PdmsTools::PdmsObjects::Extrusion::push().
position
CCVector3 PdmsTools::PdmsObjects::GenericItem::position
Object position.
Definition at line 145 of file PdmsTools.h.
Referenced by convertCoordinateSystem(), setPosition(), PdmsTools::PdmsObjects::SCylinder::write(), PdmsTools::PdmsObjects::CTorus::write(), PdmsTools::PdmsObjects::RTorus::write(), PdmsTools::PdmsObjects::Dish::write(), PdmsTools::PdmsObjects::Cone::write(), and PdmsTools::PdmsObjects::Box::write().
positionReference
GenericItem* PdmsTools::PdmsObjects::GenericItem::positionReference
Reference object (position)
Definition at line 152 of file PdmsTools.h.
Referenced by convertCoordinateSystem(), and PdmsTools::PdmsCommands::Position::execute().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsTools.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsTools.cpp