ACloudViewer: flann::lsh::LshTable< ElementType > Class Template Reference
flann::lsh::LshTable< ElementType > Class Template Reference
#include <lsh_table.h>
Public Types
typedef std::map< BucketKey, Bucket > BucketsSpace
typedef std::vector< Bucket > BucketsSpeed
Public Member Functions
LshTable ()
LshTable (unsigned int, unsigned int)
void add (unsigned int value, const ElementType *feature)
void add (const std::vector< std::pair< size_t, ElementType * > > &features)
const Bucket * getBucketFromKey (BucketKey key) const
size_t getKey (const ElementType *) const
LshStats getStats () const
LshTable (unsigned int feature_size, unsigned int subsignature_size)
size_t getKey (const unsigned char *feature) const
LshStats getStats () const
Detailed Description
template<typename ElementType>
class flann::lsh::LshTable< ElementType >
Lsh hash table. As its key is a sub-feature, and as usually the size of it is pretty small, we keep it as a continuous memory array. The value is an index in the corpus of features (we keep it as an unsigned int for pure memory reasons, it could be a size_t)
Definition at line 125 of file lsh_table.h.
Member Typedef Documentation
BucketsSpace
template<typename ElementType > typedef std::map<BucketKey, Bucket> flann::lsh::LshTable< ElementType >::BucketsSpace
A container of all the feature indices. Optimized for space
Definition at line 133 of file lsh_table.h.
BucketsSpeed
template<typename ElementType > typedef std::vector<Bucket> flann::lsh::LshTable< ElementType >::BucketsSpeed
A container of all the feature indices. Optimized for speed
Definition at line 138 of file lsh_table.h.
Constructor & Destructor Documentation
LshTable() [1/3]
template<typename ElementType > flann::lsh::LshTable< ElementType >::LshTable () inline
Default constructor
Definition at line 142 of file lsh_table.h.
LshTable() [2/3]
template<typename ElementType > flann::lsh::LshTable< ElementType >::LshTable (unsigned int , unsigned int) inline
Default constructor Create the mask and allocate the memory
Parameters
feature_size is the size of the feature (considered as a ElementType[])
key_size is the number of bits that are turned on in the feature
Definition at line 151 of file lsh_table.h.
References QtCompat::endl().
LshTable() [3/3]
flann::lsh::LshTable< unsigned char >::LshTable (unsigned int feature_size, unsigned int subsignature_size) inline
Definition at line 358 of file lsh_table.h.
References cloudViewer::utility::ceil().
Member Function Documentation
add() [1/2]
template<typename ElementType > void flann::lsh::LshTable< ElementType >::add (const std::vector< std::pair< size_t, ElementType * > > & features) inline
Add a set of features to the table
Parameters
dataset the values to store
Definition at line 188 of file lsh_table.h.
References flann::lsh::LshTable< ElementType >::add().
add() [2/2]
template<typename ElementType > void flann::lsh::LshTable< ElementType >::add (unsigned int value, const ElementType * feature) inline
Add a feature to the table
Parameters
value the value to store for that feature
feature the feature itself
Definition at line 161 of file lsh_table.h.
References flann::lsh::LshTable< ElementType >::getKey(), and flann::DynamicBitset::set().
Referenced by flann::lsh::LshTable< ElementType >::add(), flann::LshIndex< Distance >::addPoints(), and flann::LshIndex< Distance >::buildIndexImpl().
getBucketFromKey()
template<typename ElementType > const Bucket* flann::lsh::LshTable< ElementType >::getBucketFromKey (BucketKey key) const inline
Get a bucket given the key
Parameters
key
Returns
Definition at line 205 of file lsh_table.h.
References flann::DynamicBitset::test().
getKey() [1/2]
template<typename ElementType > size_t flann::lsh::LshTable< ElementType >::getKey (const ElementType *) const inline
Compute the sub-signature of a feature
Definition at line 234 of file lsh_table.h.
References QtCompat::endl().
Referenced by flann::lsh::LshTable< ElementType >::add().
getKey() [2/2]
size_t flann::lsh::LshTable< unsigned char >::getKey (const unsigned char * feature) const inline
Return the Subsignature of a feature
Parameters
feature the feature to analyze
Definition at line 400 of file lsh_table.h.
getStats() [1/2]
template<typename ElementType > LshStats flann::lsh::LshTable< ElementType >::getStats () const
Get statistics about the table
Returns
getStats() [2/2]
LshStats flann::lsh::LshTable< unsigned char >::getStats () const inline
Definition at line 433 of file lsh_table.h.
References flann::lsh::LshStats::bucket_size_max_, flann::lsh::LshStats::bucket_size_mean_, flann::lsh::LshStats::bucket_size_median_, flann::lsh::LshStats::bucket_size_min_, flann::lsh::LshStats::bucket_sizes_, flann::lsh::LshStats::n_buckets_, and flann::lsh::LshStats::size_histogram_.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/util/lsh_table.h