ACloudViewer: DrawMeOnlyVisitor Class Reference
DrawMeOnlyVisitor Class Reference
Recursive visitor for ccKdTree::drawMeOnly.
Public Member Functions
DrawMeOnlyVisitor (const ccBBox &box)
void visit (CC_DRAW_CONTEXT &context, ccKdTree::BaseNode *node)
Protected Attributes
ccBBox m_drawCellBBox
unsigned int m_count
Detailed Description
Recursive visitor for ccKdTree::drawMeOnly.
Definition at line 77 of file ecvKdTree.cpp.
Constructor & Destructor Documentation
DrawMeOnlyVisitor()
DrawMeOnlyVisitor::DrawMeOnlyVisitor (const ccBBox & box) inline
Definition at line 79 of file ecvKdTree.cpp.
Member Function Documentation
visit()
void DrawMeOnlyVisitor::visit (CC_DRAW_CONTEXT & context, ccKdTree::BaseNode * node) inline
Definition at line 81 of file ecvKdTree.cpp.
References ccGLDrawContext::bbDefaultCol, context, ecvDisplayTools::DrawBBox(), ECV_SHAPE, ECV_WIREFRAME_MODE, ecvColor::green(), cloudViewer::TrueKdTree::BaseNode::isNode(), cloudViewer::TrueKdTree::Node::leftChild, m_count, m_drawCellBBox, cloudViewer::BoundingBoxTpl< T >::maxCorner(), ccGLDrawContext::meshRenderingMode, cloudViewer::BoundingBoxTpl< T >::minCorner(), ecvDisplayTools::RemoveEntities(), ccGLDrawContext::removeEntityType, ccGLDrawContext::removeViewID, cloudViewer::TrueKdTree::Node::rightChild, cloudViewer::TrueKdTree::Node::splitDim, cloudViewer::TrueKdTree::Node::splitValue, Tuple3Tpl< Type >::u, ccGLDrawContext::viewID, and ccGLDrawContext::visible.
Referenced by ccKdTree::drawMeOnly().
Member Data Documentation
m_count
unsigned int DrawMeOnlyVisitor::m_count protected
Definition at line 124 of file ecvKdTree.cpp.
Referenced by visit().
m_drawCellBBox
ccBBox DrawMeOnlyVisitor::m_drawCellBBox protected
Definition at line 123 of file ecvKdTree.cpp.
Referenced by visit().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/src/ecvKdTree.cpp