ACloudViewer: colmap::TriangulationEstimator Class Reference
colmap::TriangulationEstimator Class Reference
#include <triangulation.h>
Classes
struct PointData
struct PoseData
Public Types
enum class ResidualType { ANGULAR_ERROR , REPROJECTION_ERROR }
typedef PointData X_t
typedef PoseData Y_t
typedef Eigen::Vector3d M_t
Public Member Functions
void SetMinTriAngle (const double min_tri_angle)
void SetResidualType (const ResidualType residual_type)
std::vector< M_t > Estimate (const std::vector< X_t > &point_data, const std::vector< Y_t > &pose_data) const
void Residuals (const std::vector< X_t > &point_data, const std::vector< Y_t > &pose_data, const M_t &xyz, std::vector< double > *residuals) const
Static Public Attributes
static const int kMinNumSamples = 2
Detailed Description
Definition at line 28 of file triangulation.h.
Member Typedef Documentation
M_t
typedef Eigen::Vector3d colmap::TriangulationEstimator::M_t
Definition at line 63 of file triangulation.h.
X_t
typedef PointData colmap::TriangulationEstimator::X_t
Definition at line 61 of file triangulation.h.
Y_t
typedef PoseData colmap::TriangulationEstimator::Y_t
Definition at line 62 of file triangulation.h.
Member Enumeration Documentation
ResidualType
enum colmap::TriangulationEstimator::ResidualType strong
Enumerator
ANGULAR_ERROR
REPROJECTION_ERROR
Definition at line 30 of file triangulation.h.
Member Function Documentation
Estimate()
std::vector< TriangulationEstimator::M_t > colmap::TriangulationEstimator::Estimate (const std::vector< X_t > & point_data, const std::vector< Y_t > & pose_data) const
Definition at line 55 of file triangulation.cc.
References colmap::CalculateTriangulationAngle(), colmap::HasPointPositiveDepth(), points, colmap::TriangulateMultiViewPoint(), and colmap::TriangulatePoint().
Residuals()
void colmap::TriangulationEstimator::Residuals (const std::vector< X_t > & point_data, const std::vector< Y_t > & pose_data, const M_t & xyz, std::vector< double > * residuals) const
Definition at line 111 of file triangulation.cc.
References ANGULAR_ERROR, colmap::CalculateNormalizedAngularError(), colmap::CalculateSquaredReprojectionError(), and REPROJECTION_ERROR.
SetMinTriAngle()
void colmap::TriangulationEstimator::SetMinTriAngle (const double min_tri_angle)
Definition at line 46 of file triangulation.cc.
SetResidualType()
void colmap::TriangulationEstimator::SetResidualType (const ResidualType residual_type)
Definition at line 51 of file triangulation.cc.
Member Data Documentation
kMinNumSamples
const int colmap::TriangulationEstimator::kMinNumSamples = 2 static
Definition at line 70 of file triangulation.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/estimators/triangulation.h
/root/ACloudViewer/libs/Reconstruction/src/estimators/triangulation.cc