ACloudViewer: cloudViewer::pipelines::registration::TransformationEstimationPointToPlane Class Reference
cloudViewer::pipelines::registration::TransformationEstimationPointToPlane Class Reference
#include <TransformationEstimation.h>
Public Member Functions
TransformationEstimationPointToPlane ()
Default Constructor.
~TransformationEstimationPointToPlane () override
TransformationEstimationPointToPlane (std::shared_ptr< RobustKernel > kernel)
Constructor that takes as input a RobustKernel.
TransformationEstimationType GetTransformationEstimationType () const override
double ComputeRMSE (const ccPointCloud &source, const ccPointCloud &target, const CorrespondenceSet &corres) const override
Eigen::Matrix4d ComputeTransformation (const ccPointCloud &source, const ccPointCloud &target, const CorrespondenceSet &corres) const override
Public Member Functions inherited from cloudViewer::pipelines::registration::TransformationEstimation
TransformationEstimation ()
Default Constructor.
virtual ~TransformationEstimation ()
Public Attributes
std::shared_ptr< RobustKernel > kernel_ = std::make_shared<L2Loss>()
shared_ptr to an Abstract RobustKernel that could mutate at runtime.
Detailed Description
Class to estimate a transformation for point to plane distance.
Definition at line 111 of file TransformationEstimation.h.
Constructor & Destructor Documentation
TransformationEstimationPointToPlane() [1/2]
cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::TransformationEstimationPointToPlane () inline
Default Constructor.
Definition at line 114 of file TransformationEstimation.h.
~TransformationEstimationPointToPlane()
cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::~TransformationEstimationPointToPlane () inline override
Definition at line 115 of file TransformationEstimation.h.
TransformationEstimationPointToPlane() [2/2]
cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::TransformationEstimationPointToPlane (std::shared_ptr< RobustKernel > kernel) inline explicit
Constructor that takes as input a RobustKernel.
Parameters
kernel Any of the implemented statistical robust kernel for outlier rejection.
Definition at line 119 of file TransformationEstimation.h.
Member Function Documentation
ComputeRMSE()
double cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::ComputeRMSE (const ccPointCloud & source, const ccPointCloud & target, const CorrespondenceSet & corres) const override virtual
Compute RMSE between source and target points cloud given correspondences.
Parameters
source Source point cloud.
target Target point cloud.
corres Correspondence set between source and target point cloud.
Implements cloudViewer::pipelines::registration::TransformationEstimation.
Definition at line 46 of file TransformationEstimation.cpp.
References ccPointCloud::getEigenNormal(), cloudViewer::PointCloudTpl< T >::getEigenPoint(), and ccPointCloud::hasNormals().
ComputeTransformation()
Eigen::Matrix4d cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::ComputeTransformation (const ccPointCloud & source, const ccPointCloud & target, const CorrespondenceSet & corres) const override virtual
Compute transformation from source to target point cloud given correspondences.
Parameters
source Source point cloud.
target Target point cloud.
corres Correspondence set between source and target point cloud.
Implements cloudViewer::pipelines::registration::TransformationEstimation.
Definition at line 60 of file TransformationEstimation.cpp.
References cloudViewer::utility::ComputeJTJandJTr(), ccPointCloud::getEigenNormal(), cloudViewer::PointCloudTpl< T >::getEigenPoint(), ccPointCloud::hasNormals(), kernel_, and cloudViewer::utility::SolveJacobianSystemAndObtainExtrinsicMatrix().
GetTransformationEstimationType()
TransformationEstimationType cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::GetTransformationEstimationType () const inline override virtual
Implements cloudViewer::pipelines::registration::TransformationEstimation.
Definition at line 124 of file TransformationEstimation.h.
Member Data Documentation
kernel_
std::shared_ptr<RobustKernel> cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::kernel_ = std::make_shared<L2Loss>()
shared_ptr to an Abstract RobustKernel that could mutate at runtime.
Definition at line 138 of file TransformationEstimation.h.
Referenced by ComputeTransformation().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/pipelines/registration/TransformationEstimation.h
/root/ACloudViewer/libs/cloudViewer/pipelines/registration/TransformationEstimation.cpp