ACloudViewer: ccInteractor Class Reference
ccInteractor Class Reference
Interactor interface (entity that can be dragged or clicked in a 3D view)
#include <ecvInteractor.h>
Public Member Functions
virtual ~ccInteractor ()=default
virtual bool acceptClick (int x, int y, Qt::MouseButton button)
Called on mouse click.
virtual bool move2D (int x, int y, int dx, int dy, int screenWidth, int screenHeight)
Called on mouse move (for 2D interactors)
virtual bool move3D (const CCVector3d &u)
Called on mouse move (for 3D interactors)
Detailed Description
Interactor interface (entity that can be dragged or clicked in a 3D view)
Definition at line 20 of file ecvInteractor.h.
Constructor & Destructor Documentation
~ccInteractor()
virtual ccInteractor::~ccInteractor () virtual default
Member Function Documentation
acceptClick()
virtual bool ccInteractor::acceptClick (int x, int y, Qt::MouseButton button) inline virtual
Called on mouse click.
Reimplemented in cc2DLabel.
Definition at line 25 of file ecvInteractor.h.
Referenced by define_ccInteractor().
move2D()
virtual bool ccInteractor::move2D (int x, int y, int dx, int dy, int screenWidth, int screenHeight) inline virtual
Called on mouse move (for 2D interactors)
Returns
true if a movement occurs
Reimplemented in ccClipBox, and cc2DLabel.
Definition at line 32 of file ecvInteractor.h.
Referenced by define_ccInteractor().
move3D()
virtual bool ccInteractor::move3D (const CCVector3d & u) inline virtual
Called on mouse move (for 3D interactors)
Returns
true if a movement occurs
Reimplemented in ccClipBox.
Definition at line 40 of file ecvInteractor.h.
Referenced by define_ccInteractor().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvInteractor.h