ACloudViewer: qHoughNormals Class Reference
qHoughNormals Class Reference
#include <qHoughNormals.h>
Protected Member Functions
void doAction ()
Slot called when associated action is triggered.
Protected Attributes
QAction * m_action
Associated action.
Detailed Description
Wrapper to the 'normals_Hough' library (https://github.com/aboulch/normals_Hough) "Deep Learning for Robust Normal Estimation in Unstructured Point Clouds" by Alexandre Boulch and Renaud Marlet, Symposium of Geometry Processing 2016, Computer Graphics Forum
Definition at line 18 of file qHoughNormals.h.
Member Function Documentation
doAction()
void qHoughNormals::doAction () protected
Slot called when associated action is triggered.
Definition at line 63 of file qHoughNormals.cpp.
References Eigen_Normal_Estimator::density_sensitive(), CVLog::Error(), Eigen_Normal_Estimator::estimate_normals(), Eigen_Normal_Estimator::get_K(), Eigen_Normal_Estimator::get_K_density(), Eigen_Normal_Estimator::get_n_phi(), Eigen_Normal_Estimator::get_n_rot(), Eigen_Normal_Estimator::get_T(), Eigen_Normal_Estimator::get_tol_angle_rad(), cloudViewer::PointCloudTpl< T >::getPoint(), qHoughNormalsDialog::Parameters::K, qHoughNormalsDialog::Parameters::k_density, max(), Eigen_Normal_Estimator::maxProgressCounter(), qHoughNormalsDialog::Parameters::n_phi, qHoughNormalsDialog::Parameters::n_rot, normals, CV_TYPES::POINT_CLOUD, ccPointCloud::resizeTheNormsTable(), s_params, ccPointCloud::setPointNormal(), Eigen_Normal_Estimator::setProgressCallback(), ccDrawableObject::showNormals(), cloudViewer::PointCloudTpl< T >::size(), qHoughNormalsDialog::Parameters::T, qHoughNormalsDialog::Parameters::tol_angle_rad, qHoughNormalsDialog::Parameters::use_density, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Member Data Documentation
m_action
QAction* qHoughNormals::m_action protected
Associated action.
Definition at line 42 of file qHoughNormals.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qHoughNormals/include/qHoughNormals.h
/root/ACloudViewer/plugins/core/Standard/qHoughNormals/src/qHoughNormals.cpp