ACloudViewer: cloudViewer::geometry::Image Class Reference
cloudViewer::geometry::Image Class Reference
The Image class stores image with customizable width, height, num of channels and bytes per channel.
#include <Image.h>
Public Types
enum class ColorToIntensityConversionType { Equal , Weighted }
Specifies whether R, G, B channels have the same weight when converting to intensity. Only used for Image with 3 channels.
enum class FilterType {
Gaussian3 , Gaussian5 , Gaussian7 , Sobel3Dx ,
Sobel3Dy
}
Specifies the Image filter type.
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Public Member Functions
Image (const char *name="Image")
Default Constructor.
~Image () override
virtual bool isSerializable () const override
Returns whether object is serializable of not.
virtual CV_CLASS_ENUM getClassID () const override
Returns unique class ID.
virtual ccBBox getOwnBB (bool withGLFeatures=false) override
Returns the entity's own bounding-box.
Image & Clear ()
virtual bool IsEmpty () const override
virtual Eigen::Vector2d GetMin2DBound () const override
virtual Eigen::Vector2d GetMax2DBound () const override
bool TestImageBoundary (double u, double v, double inner_margin=0.0) const
Test if coordinate (u, v) is located in the inner_marge of the image.
virtual bool HasData () const
Returns true if the Image has valid data.
Image & Prepare (int width, int height, int num_of_channels, int bytes_per_channel)
Prepare Image properties and allocate Image buffer.
int BytesPerLine () const
Returns data size per line (row, or the width) in bytes.
std::pair< bool, double > FloatValueAt (double u, double v) const
std::shared_ptr< Image > CreateFloatImage (Image::ColorToIntensityConversionType type=Image::ColorToIntensityConversionType::Weighted) const
Return a gray scaled float type image.
template<typename T >
T * PointerAt (int u, int v) const
Function to access the raw data of a single-channel Image.
template<typename T >
T * PointerAt (int u, int v, int ch) const
Function to access the raw data of a multi-channel Image.
std::shared_ptr< Image > ConvertDepthToFloatImage (double depth_scale=1000.0, double depth_trunc=3.0) const
std::shared_ptr< Image > Transpose () const
std::shared_ptr< Image > FlipHorizontal () const
Function to flip image horizontally (from left to right).
std::shared_ptr< Image > FlipVertical () const
Function to flip image vertically (upside down).
std::shared_ptr< Image > Filter (Image::FilterType type) const
Function to filter image with pre-defined filtering type.
std::shared_ptr< Image > Filter (const std::vector< double > &dx, const std::vector< double > &dy) const
Function to filter image with arbitrary dx, dy separable filters.
std::shared_ptr< Image > FilterHorizontal (const std::vector< double > &kernel) const
std::shared_ptr< Image > Downsample () const
Function to 2x image downsample using simple 2x2 averaging.
std::shared_ptr< Image > Dilate (int half_kernel_size=1) const
Function to dilate 8bit mask map.
Image & LinearTransform (double scale=1.0, double offset=0.0)
Image & ClipIntensity (double min=0.0, double max=1.0)
template<typename T >
std::shared_ptr< Image > CreateImageFromFloatImage () const
ImagePyramid CreatePyramid (size_t num_of_levels, bool with_gaussian_filter=true) const
Function to create image pyramid.
std::shared_ptr< Image > CreateDepthBoundaryMask (double depth_threshold_for_discontinuity_check=0.1, int half_dilation_kernel_size_for_discontinuity_map=3) const
Function to create a depthmap boundary mask from depth image.
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual Eigen::Vector3d GetMinBound () const
Returns min bounds for geometry coordinates.
virtual Eigen::Vector3d GetMaxBound () const
Returns max bounds for geometry coordinates.
virtual Eigen::Vector3d GetCenter () const
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const
virtual ccHObject & Transform (const Eigen::Matrix4d &transformation)
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual ccHObject & Translate (const Eigen::Vector3d &translation, bool relative=true)
Apply translation to the geometry coordinates.
virtual ccHObject & Scale (const double s, const Eigen::Vector3d &center)
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center)
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false)
virtual bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner)
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual ccBBox getOwnFitBB (ccGLMatrix &trans)
Returns best-fit bounding-box (if available)
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col)
Draws the entity (and its children) bounding-box.
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
virtual void notifyGeometryUpdate ()
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual unsigned getUniqueIDForDisplay () const
Returns object unqiue ID used for display.
virtual const ccGLMatrix & getGLTransformationHistory () const
Returns the transformation 'history' matrix.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual void getDrawingParameters (glDrawParams &params) const
Returns main OpenGL parameters for this entity.
virtual bool hasColors () const
Returns whether colors are enabled or not.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual bool hasNormals () const
Returns whether normals are enabled or not.
virtual bool normalsShown () const
Returns whether normals are shown or not.
virtual void showNormals (bool state)
Sets normals visibility.
virtual void toggleNormals ()
Toggles normals display state.
virtual bool hasDisplayedScalarField () const
Returns whether an active scalar field is available or not.
virtual bool hasScalarFields () const
Returns whether one or more scalar fields are instantiated.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void toggleMaterials ()
Toggles material display state.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Static Public Member Functions
static std::shared_ptr< Image > CreateDepthToCameraDistanceMultiplierFloatImage (const camera::PinholeCameraIntrinsic &intrinsic)
static ImagePyramid FilterPyramid (const ImagePyramid &input, Image::FilterType type)
Function to filter image pyramid.
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Public Attributes
int width_ = 0
Width of the image.
int height_ = 0
Height of the image.
int num_of_channels_ = 0
Number of chanels in the image.
int bytes_per_channel_ = 0
Number of bytes per channel.
std::vector< uint8_t > data_
Image storage buffer.
Protected Member Functions
virtual void drawMeOnly (CC_DRAW_CONTEXT &context) override
Draws the entity only (not its children)
virtual void onDeletionOf (const ccHObject *obj) override
This method is called when another object is deleted.
void AllocateDataBuffer ()
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void applyGLTransformation (const ccGLMatrix &trans)
Applies a GL transformation to the entity.
virtual bool toFile_MeOnly (QFile &out, short dataVersion) const
Save own object data.
virtual bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Loads own object data.
virtual short minimumFileVersion_MeOnly () const
virtual void drawNameIn3D ()
Draws the entity name in 3D.
virtual void onUpdateOf (ccHObject *obj)
This method is called when another object (geometry) is updated.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Additional Inherited Members
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Detailed Description
The Image class stores image with customizable width, height, num of channels and bytes per channel.
Definition at line 33 of file Image.h.
Member Enumeration Documentation
ColorToIntensityConversionType
enum cloudViewer::geometry::Image::ColorToIntensityConversionType strong
Specifies whether R, G, B channels have the same weight when converting to intensity. Only used for Image with 3 channels.
When Weighted is used R, G, B channels are weighted according to the Digital ITU BT.601 standard: I = 0.299 * R + 0.587 * G + 0.114 * B.
Enumerator
Equal
R, G, B channels have equal weights.
Weighted
Weighted R, G, B channels: I = 0.299 * R + 0.587 * G + 0.114 * B.
Definition at line 42 of file Image.h.
FilterType
enum cloudViewer::geometry::Image::FilterType strong
Specifies the Image filter type.
Enumerator
Gaussian3
Gaussian filter of size 3 x 3.
Gaussian5
Gaussian filter of size 5 x 5.
Gaussian7
Gaussian filter of size 7 x 7.
Sobel3Dx
Sobel filter along X-axis.
Sobel3Dy
Sobel filter along Y-axis.
Definition at line 52 of file Image.h.
Constructor & Destructor Documentation
Image()
cloudViewer::geometry::Image::Image (const char * name = "Image") inline
Default Constructor.
Definition at line 67 of file Image.h.
~Image()
cloudViewer::geometry::Image::~Image () inline override
Definition at line 68 of file Image.h.
Member Function Documentation
AllocateDataBuffer()
void cloudViewer::geometry::Image::AllocateDataBuffer () inline protected
Definition at line 213 of file Image.h.
BytesPerLine()
int cloudViewer::geometry::Image::BytesPerLine () const inline
Returns data size per line (row, or the width) in bytes.
Definition at line 122 of file Image.h.
Referenced by cloudViewer::visualization::Visualizer::CaptureDepthFloatBuffer(), cloudViewer::visualization::Visualizer::CaptureDepthImage(), cloudViewer::visualization::Visualizer::CaptureDepthPointCloud(), cloudViewer::visualization::Visualizer::CaptureScreenFloatBuffer(), cloudViewer::visualization::Visualizer::CaptureScreenImage(), FlipHorizontal(), FlipVertical(), cloudViewer::t::geometry::Image::FromLegacy(), cloudViewer::t::geometry::Image::ToLegacy(), and Transpose().
Clear()
Image & cloudViewer::geometry::Image::Clear ()
Definition at line 30 of file Image.cpp.
References bytes_per_channel_, data_, height_, num_of_channels_, and width_.
Referenced by cloudViewer::visualization::SelectionPolygon::Clear(), and cloudViewer::geometry::RGBDImage::Clear().
ClipIntensity()
Image & cloudViewer::geometry::Image::ClipIntensity (double min = 0.0, double max = 1.0)
Function to clipping pixel intensities.
Parameters
min is lower bound.
max is upper bound.
Definition at line 112 of file Image.cpp.
References bytes_per_channel_, float, height_, LogError, num_of_channels_, width_, x, and y.
ConvertDepthToFloatImage()
std::shared_ptr< Image > cloudViewer::geometry::Image::ConvertDepthToFloatImage (double depth_scale = 1000.0, double depth_trunc = 3.0) const
Definition at line 97 of file Image.cpp.
References CreateFloatImage(), float, x, and y.
Referenced by cloudViewer::geometry::RGBDImage::CreateFromColorAndDepth(), and ccPointCloud::CreateFromDepthImage().
CreateDepthBoundaryMask()
std::shared_ptr< Image > cloudViewer::geometry::Image::CreateDepthBoundaryMask (double depth_threshold_for_discontinuity_check = 0.1, int half_dilation_kernel_size_for_discontinuity_map = 3) const
Function to create a depthmap boundary mask from depth image.
Definition at line 374 of file Image.cpp.
References CreateFloatImage(), height, Sobel3Dx, Sobel3Dy, and width.
CreateDepthToCameraDistanceMultiplierFloatImage()
std::shared_ptr< Image > cloudViewer::geometry::Image::CreateDepthToCameraDistanceMultiplierFloatImage (const camera::PinholeCameraIntrinsic & intrinsic) static
Factory function to create a float image composed of multipliers that convert depth values into camera distances (ImageFactory.cpp) The multiplier function M(u,v) is defined as: M(u, v) = sqrt(1 + ((u - cx) / fx) ^ 2 + ((v - cy) / fy) ^ 2) This function is used as a convenient function for performance optimization in volumetric integration (see Core/Integration/TSDFVolume.h).
Definition at line 17 of file ImageFactory.cpp.
References float, cloudViewer::camera::PinholeCameraIntrinsic::GetFocalLength(), cloudViewer::camera::PinholeCameraIntrinsic::GetPrincipalPoint(), cloudViewer::camera::PinholeCameraIntrinsic::height_, and cloudViewer::camera::PinholeCameraIntrinsic::width_.
Referenced by cloudViewer::pipelines::integration::ScalableTSDFVolume::Integrate(), and cloudViewer::pipelines::integration::UniformTSDFVolume::Integrate().
CreateFloatImage()
std::shared_ptr< Image > cloudViewer::geometry::Image::CreateFloatImage (Image::ColorToIntensityConversionType type = Image::ColorToIntensityConversionType::Weighted) const
Return a gray scaled float type image.
Definition at line 47 of file ImageFactory.cpp.
References bytes_per_channel_, data_, Equal, float, height_, IsEmpty(), num_of_channels_, type, Weighted, and width_.
Referenced by ConvertDepthToFloatImage(), CreateDepthBoundaryMask(), and cloudViewer::pipelines::odometry::InitializeRGBDOdometry().
CreateImageFromFloatImage()
template<typename T > template std::shared_ptr< Image > cloudViewer::geometry::Image::CreateImageFromFloatImage< uint16_t > () const
Function to change data types of image crafted for specific usage such as single channel float image -> 8-bit RGB or 16-bit depth image.
Definition at line 107 of file ImageFactory.cpp.
References bytes_per_channel_, data_, height_, LogError, num_of_channels_, and width_.
CreatePyramid()
ImagePyramid cloudViewer::geometry::Image::CreatePyramid (size_t num_of_levels, bool with_gaussian_filter = true) const
Function to create image pyramid.
Definition at line 129 of file ImageFactory.cpp.
References bytes_per_channel_, Gaussian3, LogError, and num_of_channels_.
Referenced by cloudViewer::geometry::RGBDImage::CreatePyramid().
Dilate()
std::shared_ptr< Image > cloudViewer::geometry::Image::Dilate (int half_kernel_size = 1) const
Function to dilate 8bit mask map.
Definition at line 338 of file Image.cpp.
References bytes_per_channel_, height_, LogError, num_of_channels_, TestImageBoundary(), width_, x, and y.
Downsample()
std::shared_ptr< Image > cloudViewer::geometry::Image::Downsample () const
Function to 2x image downsample using simple 2x2 averaging.
Definition at line 139 of file Image.cpp.
References bytes_per_channel_, cloudViewer::utility::floor(), height_, LogError, num_of_channels_, width_, x, and y.
drawMeOnly()
virtual void cloudViewer::geometry::Image::drawMeOnly (CC_DRAW_CONTEXT & context) inline override protected virtual
Draws the entity only (not its children)
Reimplemented from ccHObject.
Definition at line 82 of file Image.h.
Filter() [1/2]
std::shared_ptr< Image > cloudViewer::geometry::Image::Filter (const std::vector< double > & dx, const std::vector< double > & dy) const
Function to filter image with arbitrary dx, dy separable filters.
Definition at line 248 of file Image.cpp.
References bytes_per_channel_, FilterHorizontal(), LogError, and num_of_channels_.
Filter() [2/2]
std::shared_ptr< Image > cloudViewer::geometry::Image::Filter (Image::FilterType type) const
Function to filter image with pre-defined filtering type.
Definition at line 209 of file Image.cpp.
References bytes_per_channel_, Gaussian3, Gaussian5, Gaussian7, LogError, num_of_channels_, Sobel3Dx, Sobel3Dy, and type.
FilterHorizontal()
std::shared_ptr< Image > cloudViewer::geometry::Image::FilterHorizontal (const std::vector< double > & kernel) const
Definition at line 170 of file Image.cpp.
References bytes_per_channel_, float, cloudViewer::utility::floor(), height_, LogError, num_of_channels_, width_, x, and y.
Referenced by Filter().
FilterPyramid()
ImagePyramid cloudViewer::geometry::Image::FilterPyramid (const ImagePyramid & input, Image::FilterType type) static
Function to filter image pyramid.
Definition at line 238 of file Image.cpp.
References type.
FlipHorizontal()
std::shared_ptr< Image > cloudViewer::geometry::Image::FlipHorizontal () const
Function to flip image horizontally (from left to right).
Definition at line 310 of file Image.cpp.
References bytes_per_channel_, BytesPerLine(), copy, data_, height_, num_of_channels_, width_, x, and y.
FlipVertical()
std::shared_ptr< Image > cloudViewer::geometry::Image::FlipVertical () const
Function to flip image vertically (upside down).
Definition at line 293 of file Image.cpp.
References bytes_per_channel_, BytesPerLine(), copy, data_, height_, num_of_channels_, width_, and y.
FloatValueAt()
std::pair< bool, double > cloudViewer::geometry::Image::FloatValueAt (double u, double v) const
Function to access the bilinear interpolated float value of a (single-channel) float image. Returns a tuple, where the first bool indicates if the u,v coordinates are within the image dimensions, and the second double value is the interpolated pixel value.
Definition at line 58 of file Image.cpp.
References bytes_per_channel_, height_, cloudViewer::core::make_pair(), num_of_channels_, and width_.
Referenced by cloudViewer::geometry::VoxelGrid::CarveDepthMap(), cloudViewer::geometry::VoxelGrid::CarveSilhouette(), cloudViewer::pipelines::color_map::ComputeJacobianAndResidualNonRigid(), and cloudViewer::pipelines::color_map::ComputeJacobianAndResidualRigid().
getClassID()
virtual CV_CLASS_ENUM cloudViewer::geometry::Image::getClassID () const inline override virtual
Returns unique class ID.
Reimplemented from ccHObject.
Definition at line 74 of file Image.h.
References CV_TYPES::IMAGE2.
GetMax2DBound()
Eigen::Vector2d cloudViewer::geometry::Image::GetMax2DBound () const override virtual
Reimplemented from ccHObject.
Definition at line 43 of file Image.cpp.
References height_, and width_.
GetMin2DBound()
Eigen::Vector2d cloudViewer::geometry::Image::GetMin2DBound () const override virtual
Reimplemented from ccHObject.
Definition at line 39 of file Image.cpp.
getOwnBB()
ccBBox cloudViewer::geometry::Image::getOwnBB (bool withGLFeatures = false) override virtual
Returns the entity's own bounding-box.
Children bboxes are ignored.
Parameters
withGLFeatures whether to take into account display-only elements (if any)
Returns
bounding-box
Reimplemented from ccHObject.
Definition at line 47 of file Image.cpp.
References ccHObject::GetAxisAlignedBoundingBox().
HasData()
virtual bool cloudViewer::geometry::Image::HasData () const inline virtual
Returns true if the Image has valid data.
Definition at line 103 of file Image.h.
IsEmpty()
virtual bool cloudViewer::geometry::Image::IsEmpty () const inline override virtual
Reimplemented from ccHObject.
Definition at line 87 of file Image.h.
Referenced by CreateFloatImage(), and cloudViewer::t::geometry::Image::FromLegacy().
isSerializable()
virtual bool cloudViewer::geometry::Image::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccHObject.
Definition at line 71 of file Image.h.
LinearTransform()
Image & cloudViewer::geometry::Image::LinearTransform (double scale = 1.0, double offset = 0.0)
Function to linearly transform pixel intensities image_new = scale * image + offset.
Definition at line 126 of file Image.cpp.
References bytes_per_channel_, float, height_, LogError, num_of_channels_, offset, width_, x, and y.
Referenced by cloudViewer::pipelines::odometry::NormalizeIntensity().
onDeletionOf()
void cloudViewer::geometry::Image::onDeletionOf (const ccHObject * obj) override protected virtual
This method is called when another object is deleted.
For internal use.
Reimplemented from ccHObject.
Definition at line 28 of file Image.cpp.
References ccHObject::onDeletionOf().
PointerAt() [1/2]
template<typename T > template uint16_t * cloudViewer::geometry::Image::PointerAt< uint16_t > (int u, int v) const
Function to access the raw data of a single-channel Image.
Definition at line 77 of file Image.cpp.
References data_, and width_.
Referenced by cloudViewer::pipelines::odometry::AddElementToCorrespondenceMap(), cloudViewer::pipelines::odometry::ComputeCorrespondence(), cloudViewer::pipelines::odometry::RGBDOdometryJacobianFromColorTerm::ComputeJacobianAndResidual(), cloudViewer::pipelines::odometry::RGBDOdometryJacobianFromHybridTerm::ComputeJacobianAndResidual(), cloudViewer::io::ConvertBGRAToRGB(), cloudViewer::pipelines::odometry::ConvertDepthImageToXYZImage(), cloudViewer::pipelines::odometry::CountCorrespondence(), cloudViewer::geometry::RGBDImage::CreateFromNYUFormat(), cloudViewer::geometry::RGBDImage::CreateFromSUNFormat(), cloudViewer::pipelines::odometry::InitializeCorrespondenceMap(), cloudViewer::pipelines::integration::UniformTSDFVolume::IntegrateWithDepthToCameraDistanceMultiplier(), cloudViewer::pipelines::odometry::MergeCorrespondenceMaps(), cloudViewer::pipelines::odometry::NormalizeIntensity(), cloudViewer::pipelines::odometry::PreprocessDepth(), and cloudViewer::pipelines::color_map::QueryImageIntensity().
PointerAt() [2/2]
template<typename T > template uint16_t * cloudViewer::geometry::Image::PointerAt< uint16_t > (int u, int v, int ch) const
Function to access the raw data of a multi-channel Image.
Definition at line 87 of file Image.cpp.
References data_, num_of_channels_, and width_.
Prepare()
Image& cloudViewer::geometry::Image::Prepare (int width, int height, int num_of_channels, int bytes_per_channel) inline
Prepare Image properties and allocate Image buffer.
Definition at line 109 of file Image.h.
Referenced by cloudViewer::visualization::Visualizer::CaptureDepthFloatBuffer(), cloudViewer::visualization::Visualizer::CaptureDepthImage(), cloudViewer::visualization::Visualizer::CaptureDepthPointCloud(), cloudViewer::visualization::Visualizer::CaptureScreenFloatBuffer(), cloudViewer::visualization::Visualizer::CaptureScreenImage(), cloudViewer::visualization::SelectionPolygon::FillPolygon(), cloudViewer::pipelines::odometry::InitializeCorrespondenceMap(), and cloudViewer::t::geometry::Image::ToLegacy().
TestImageBoundary()
bool cloudViewer::geometry::Image::TestImageBoundary (double u, double v, double inner_margin = 0.0) const
Test if coordinate (u, v) is located in the inner_marge of the image.
Parameters
u Coordinate along the width dimension.
v Coordinate along the height dimension.
inner_margin The inner margin from the image boundary.
Returns
Returns true if coordinate (u, v) is located in the inner_marge of the image.
Definition at line 51 of file Image.cpp.
References height_, and width_.
Referenced by cloudViewer::pipelines::color_map::ComputeJacobianAndResidualNonRigid(), cloudViewer::pipelines::color_map::ComputeJacobianAndResidualRigid(), Dilate(), and cloudViewer::pipelines::color_map::QueryImageIntensity().
Transpose()
std::shared_ptr< Image > cloudViewer::geometry::Image::Transpose () const
Definition at line 262 of file Image.cpp.
References bytes_per_channel_, BytesPerLine(), copy, data_, height_, num_of_channels_, width_, x, and y.
Member Data Documentation
bytes_per_channel_
int cloudViewer::geometry::Image::bytes_per_channel_ = 0
Number of bytes per channel.
Definition at line 225 of file Image.h.
Referenced by cloudViewer::pipelines::odometry::CheckRGBDImagePair(), Clear(), ClipIntensity(), cloudViewer::io::ConvertBGRAToRGB(), cloudViewer::pipelines::odometry::ConvertDepthImageToXYZImage(), CreateFloatImage(), ccPointCloud::CreateFromDepthImage(), CreateImageFromFloatImage(), CreatePyramid(), Dilate(), Downsample(), Filter(), FilterHorizontal(), FlipHorizontal(), FlipVertical(), FloatValueAt(), cloudViewer::t::geometry::Image::FromLegacy(), LinearTransform(), and Transpose().
data_
std::vector<uint8_t> cloudViewer::geometry::Image::data_
Image storage buffer.
Definition at line 227 of file Image.h.
Referenced by cloudViewer::visualization::Visualizer::CaptureDepthFloatBuffer(), cloudViewer::visualization::Visualizer::CaptureDepthImage(), cloudViewer::visualization::Visualizer::CaptureDepthPointCloud(), cloudViewer::visualization::Visualizer::CaptureScreenFloatBuffer(), cloudViewer::visualization::Visualizer::CaptureScreenImage(), Clear(), CreateFloatImage(), CreateImageFromFloatImage(), cloudViewer::visualization::SelectionPolygon::FillPolygon(), FlipHorizontal(), FlipVertical(), cloudViewer::t::geometry::Image::FromLegacy(), PointerAt(), cloudViewer::t::geometry::Image::ToLegacy(), and Transpose().
height_
int cloudViewer::geometry::Image::height_ = 0
Height of the image.
Definition at line 221 of file Image.h.
Referenced by cloudViewer::visualization::Visualizer::CaptureDepthFloatBuffer(), cloudViewer::visualization::Visualizer::CaptureDepthImage(), cloudViewer::visualization::Visualizer::CaptureDepthPointCloud(), cloudViewer::visualization::Visualizer::CaptureScreenFloatBuffer(), cloudViewer::visualization::Visualizer::CaptureScreenImage(), cloudViewer::geometry::VoxelGrid::CarveDepthMap(), cloudViewer::geometry::VoxelGrid::CarveSilhouette(), cloudViewer::pipelines::odometry::CheckImagePair(), Clear(), ClipIntensity(), cloudViewer::pipelines::odometry::ComputeCorrespondence(), cloudViewer::io::ConvertBGRAToRGB(), cloudViewer::pipelines::odometry::ConvertDepthImageToXYZImage(), cloudViewer::pipelines::odometry::CountCorrespondence(), CreateFloatImage(), cloudViewer::geometry::RGBDImage::CreateFromColorAndDepth(), cloudViewer::geometry::RGBDImage::CreateFromNYUFormat(), cloudViewer::geometry::RGBDImage::CreateFromSUNFormat(), CreateImageFromFloatImage(), Dilate(), Downsample(), FilterHorizontal(), FlipHorizontal(), FlipVertical(), FloatValueAt(), cloudViewer::t::geometry::Image::FromLegacy(), GetMax2DBound(), cloudViewer::geometry::RGBDImage::GetMax2DBound(), cloudViewer::pipelines::odometry::InitializeCorrespondenceMap(), LinearTransform(), cloudViewer::pipelines::odometry::MergeCorrespondenceMaps(), cloudViewer::pipelines::odometry::NormalizeIntensity(), TestImageBoundary(), cloudViewer::t::geometry::Image::ToLegacy(), and Transpose().
num_of_channels_
int cloudViewer::geometry::Image::num_of_channels_ = 0
Number of chanels in the image.
Definition at line 223 of file Image.h.
Referenced by cloudViewer::pipelines::odometry::CheckRGBDImagePair(), Clear(), ClipIntensity(), cloudViewer::io::ConvertBGRAToRGB(), cloudViewer::pipelines::odometry::ConvertDepthImageToXYZImage(), CreateFloatImage(), ccPointCloud::CreateFromDepthImage(), CreateImageFromFloatImage(), CreatePyramid(), Dilate(), Downsample(), Filter(), FilterHorizontal(), FlipHorizontal(), FlipVertical(), FloatValueAt(), cloudViewer::t::geometry::Image::FromLegacy(), LinearTransform(), PointerAt(), and Transpose().
width_
int cloudViewer::geometry::Image::width_ = 0
Width of the image.
Definition at line 219 of file Image.h.
Referenced by cloudViewer::visualization::Visualizer::CaptureDepthFloatBuffer(), cloudViewer::visualization::Visualizer::CaptureDepthImage(), cloudViewer::visualization::Visualizer::CaptureDepthPointCloud(), cloudViewer::geometry::VoxelGrid::CarveDepthMap(), cloudViewer::geometry::VoxelGrid::CarveSilhouette(), cloudViewer::pipelines::odometry::CheckImagePair(), Clear(), ClipIntensity(), cloudViewer::pipelines::odometry::ComputeCorrespondence(), cloudViewer::io::ConvertBGRAToRGB(), cloudViewer::pipelines::odometry::ConvertDepthImageToXYZImage(), cloudViewer::pipelines::odometry::CountCorrespondence(), CreateFloatImage(), cloudViewer::geometry::RGBDImage::CreateFromColorAndDepth(), cloudViewer::geometry::RGBDImage::CreateFromNYUFormat(), cloudViewer::geometry::RGBDImage::CreateFromSUNFormat(), CreateImageFromFloatImage(), Dilate(), Downsample(), FilterHorizontal(), FlipHorizontal(), FlipVertical(), FloatValueAt(), cloudViewer::t::geometry::Image::FromLegacy(), GetMax2DBound(), cloudViewer::geometry::RGBDImage::GetMax2DBound(), cloudViewer::pipelines::odometry::InitializeCorrespondenceMap(), LinearTransform(), cloudViewer::pipelines::odometry::MergeCorrespondenceMaps(), cloudViewer::pipelines::odometry::NormalizeIntensity(), PointerAt(), TestImageBoundary(), and Transpose().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/Image.h
/root/ACloudViewer/libs/CV_db/src/Image.cpp
/root/ACloudViewer/libs/CV_db/src/ImageFactory.cpp