ACloudViewer: cloudViewer::visualization::rendering::PyOffscreenRenderer Class Reference
cloudViewer::visualization::rendering::PyOffscreenRenderer Class Reference
Public Member Functions
PyOffscreenRenderer (int width, int height, const std::string &resource_path)
~PyOffscreenRenderer ()
CloudViewerScene * GetScene ()
std::shared_ptr< geometry::Image > RenderToImage ()
std::shared_ptr< geometry::Image > RenderToDepthImage (bool z_in_view_space=false)
void SetupCamera (const camera::PinholeCameraIntrinsic &intrinsic, const Eigen::Matrix4d &extrinsic)
void SetupCamera (const Eigen::Matrix3d &intrinsic, const Eigen::Matrix4d &extrinsic, int intrinsic_width_px, int intrinsic_height_px)
void SetupCamera (float verticalFoV, const Eigen::Vector3f &center, const Eigen::Vector3f &eye, const Eigen::Vector3f &up, float nearClip=-1.0f, float farClip=-1.0f)
Detailed Description
Definition at line 31 of file rendering.cpp.
Constructor & Destructor Documentation
PyOffscreenRenderer()
cloudViewer::visualization::rendering::PyOffscreenRenderer::PyOffscreenRenderer (int width, int height, const std::string & resource_path) inline
Definition at line 33 of file rendering.cpp.
References cloudViewer::visualization::rendering::EngineInstance::EnableHeadless(), cloudViewer::visualization::rendering::EngineInstance::GetInstance(), cloudViewer::visualization::rendering::EngineInstance::GetResourceManager(), height, cloudViewer::visualization::gui::InitializeForPython(), and width.
~PyOffscreenRenderer()
cloudViewer::visualization::rendering::PyOffscreenRenderer::~PyOffscreenRenderer () inline
Definition at line 48 of file rendering.cpp.
References cloudViewer::visualization::rendering::EngineInstance::DestroyInstance().
Member Function Documentation
GetScene()
CloudViewerScene* cloudViewer::visualization::rendering::PyOffscreenRenderer::GetScene () inline
Definition at line 55 of file rendering.cpp.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
RenderToDepthImage()
std::shared_ptr<geometry::Image> cloudViewer::visualization::rendering::PyOffscreenRenderer::RenderToDepthImage (bool z_in_view_space = false) inline
Definition at line 61 of file rendering.cpp.
References cloudViewer::visualization::gui::RenderToDepthImageWithoutWindow().
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
RenderToImage()
std::shared_ptr<geometry::Image> cloudViewer::visualization::rendering::PyOffscreenRenderer::RenderToImage () inline
Definition at line 57 of file rendering.cpp.
References cloudViewer::visualization::gui::RenderToImageWithoutWindow().
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
SetupCamera() [1/3]
void cloudViewer::visualization::rendering::PyOffscreenRenderer::SetupCamera (const camera::PinholeCameraIntrinsic & intrinsic, const Eigen::Matrix4d & extrinsic) inline
Definition at line 67 of file rendering.cpp.
References cloudViewer::camera::PinholeCameraIntrinsic::height_, cloudViewer::camera::PinholeCameraIntrinsic::intrinsic_matrix_, and cloudViewer::camera::PinholeCameraIntrinsic::width_.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
SetupCamera() [2/3]
void cloudViewer::visualization::rendering::PyOffscreenRenderer::SetupCamera (const Eigen::Matrix3d & intrinsic, const Eigen::Matrix4d & extrinsic, int intrinsic_width_px, int intrinsic_height_px) inline
Definition at line 73 of file rendering.cpp.
References cloudViewer::visualization::rendering::CloudViewerScene::GetBoundingBox(), cloudViewer::visualization::rendering::CloudViewerScene::GetCamera(), and cloudViewer::visualization::rendering::Camera::SetupCameraAsPinholeCamera().
SetupCamera() [3/3]
void cloudViewer::visualization::rendering::PyOffscreenRenderer::SetupCamera (float verticalFoV, const Eigen::Vector3f & center, const Eigen::Vector3f & eye, const Eigen::Vector3f & up, float nearClip = -1.0f, float farClip = -1.0f) inline
Definition at line 82 of file rendering.cpp.
References cloudViewer::visualization::rendering::Camera::CalcFarPlane(), cloudViewer::visualization::rendering::Camera::CalcNearPlane(), cloudViewer::visualization::rendering::CloudViewerScene::GetBoundingBox(), cloudViewer::visualization::rendering::CloudViewerScene::GetCamera(), and cloudViewer::visualization::rendering::Camera::Vertical.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Python/pybind/visualization/rendering/rendering.cpp