ACloudViewer: cloudViewer::visualization::gui::ImguiFilamentBridge Class Reference
cloudViewer::visualization::gui::ImguiFilamentBridge Class Reference
#include <ImguiFilamentBridge.h>
Classes
struct Impl
Public Member Functions
ImguiFilamentBridge (visualization::rendering::FilamentRenderer *renderer, const Size &window_size)
~ImguiFilamentBridge ()
void CreateAtlasTextureAlpha8 (unsigned char *pixels, int width, int height, int bytes_per_px)
void Update (ImDrawData *imguiData)
void OnWindowResized (const Window &window)
Detailed Description
Definition at line 57 of file ImguiFilamentBridge.h.
Constructor & Destructor Documentation
ImguiFilamentBridge()
cloudViewer::visualization::gui::ImguiFilamentBridge::ImguiFilamentBridge (visualization::rendering::FilamentRenderer * renderer, const Size & window_size)
Definition at line 133 of file ImguiFilamentBridge.cpp.
References cloudViewer::visualization::rendering::FilamentScene::AddView(), cloudViewer::visualization::rendering::FilamentRenderer::ConvertToGuiScene(), cloudViewer::visualization::rendering::FilamentRenderer::CreateScene(), cloudViewer::visualization::rendering::FilamentRenderer::GetGuiScene(), cloudViewer::visualization::gui::Application::GetInstance(), cloudViewer::visualization::rendering::EngineInstance::GetInstance(), cloudViewer::visualization::gui::Application::GetResourcePath(), cloudViewer::visualization::gui::Size::height, cloudViewer::visualization::gui::LoadMaterialTemplate(), and cloudViewer::visualization::gui::Size::width.
~ImguiFilamentBridge()
cloudViewer::visualization::gui::ImguiFilamentBridge::~ImguiFilamentBridge ()
Definition at line 194 of file ImguiFilamentBridge.cpp.
References cloudViewer::visualization::rendering::EngineInstance::GetInstance(), ib, and vb.
Member Function Documentation
CreateAtlasTextureAlpha8()
void cloudViewer::visualization::gui::ImguiFilamentBridge::CreateAtlasTextureAlpha8 (unsigned char * pixels, int width, int height, int bytes_per_px)
Definition at line 168 of file ImguiFilamentBridge.cpp.
References cloudViewer::visualization::rendering::EngineInstance::GetInstance(), height, cloudViewer::visualization::gui::kUiBlitTexParamName, size, and width.
OnWindowResized()
void cloudViewer::visualization::gui::ImguiFilamentBridge::OnWindowResized (const Window & window)
Definition at line 353 of file ImguiFilamentBridge.cpp.
References cloudViewer::visualization::gui::Window::GetSize(), cloudViewer::visualization::rendering::Camera::Ortho, and size.
Update()
void cloudViewer::visualization::gui::ImguiFilamentBridge::Update (ImDrawData * imguiData)
Definition at line 254 of file ImguiFilamentBridge.cpp.
References cloudViewer::visualization::rendering::EngineInstance::GetInstance(), cloudViewer::visualization::rendering::EngineInstance::GetResourceManager(), cloudViewer::visualization::rendering::FilamentResourceManager::GetTexture(), cloudViewer::visualization::gui::kImageTexParamName, and LogError.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/ImguiFilamentBridge.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/ImguiFilamentBridge.cpp