ACloudViewer: vtkUndoElement Class Reference
vtkUndoElement Class Reference abstract
#include <vtkUndoElement.h>
Public Member Functions
vtkTypeMacro (vtkUndoElement, vtkObject)
void PrintSelf (ostream &os, vtkIndent indent) override
virtual int Undo ()=0
virtual int Redo ()=0
vtkGetMacro (Mergeable, bool)
virtual bool Merge (vtkUndoElement *vtkNotUsed(new_element))
virtual void SetUndoSetWorkingContext (vtkCollection *workCTX)
Protected Member Functions
vtkUndoElement ()
~vtkUndoElement () override
vtkSetMacro (Mergeable, bool)
Protected Attributes
bool Mergeable
vtkCollection * UndoSetWorkingContext
Detailed Description
Definition at line 14 of file vtkUndoElement.h.
Constructor & Destructor Documentation
vtkUndoElement()
vtkUndoElement::vtkUndoElement () protected
Definition at line 20 of file vtkUndoElement.cxx.
References Mergeable.
~vtkUndoElement()
vtkUndoElement::~vtkUndoElement () override protected
Definition at line 26 of file vtkUndoElement.cxx.
Member Function Documentation
Merge()
virtual bool vtkUndoElement::Merge (vtkUndoElement * vtkNotUsednew_element) inline virtual
Called on the older element in the UndoSet to merge with the element being added if both the elements are mergeable. Returns if the merge was successful. Default implementation doesn't do anything.
Definition at line 49 of file vtkUndoElement.h.
Referenced by vtkUndoSet::AddElement().
PrintSelf()
void vtkUndoElement::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 31 of file vtkUndoElement.cxx.
References QtCompat::endl(), and Mergeable.
Redo()
virtual int vtkUndoElement::Redo () pure virtual
Redo the operation encaspsulated by this element.
Returns
the status of the operation, 1 on success, 0 otherwise.
Referenced by vtkUndoSet::Redo(), and vtkUndoSet::Undo().
SetUndoSetWorkingContext()
virtual void vtkUndoElement::SetUndoSetWorkingContext (vtkCollection * workCTX) inline virtual
Definition at line 60 of file vtkUndoElement.h.
Referenced by vtkUndoSet::Redo(), and vtkUndoSet::Undo().
Undo()
virtual int vtkUndoElement::Undo () pure virtual
Undo the operation encapsulated by this element.
Returns
the status of the operation, 1 on success, 0 otherwise.
Referenced by vtkUndoSet::Redo(), and vtkUndoSet::Undo().
vtkGetMacro()
vtkUndoElement::vtkGetMacro (Mergeable , bool)
Returns if this undo element can be merged with other undo elements. When an undo element is added to a vtkUndoSet unsing AddElement, an attempt is made to "merge" the element with the most recently added undo element, if any, if both the undo elements are mergeable.
vtkSetMacro()
vtkUndoElement::vtkSetMacro (Mergeable , bool) protected
vtkTypeMacro()
vtkUndoElement::vtkTypeMacro (vtkUndoElement , vtkObject)
Member Data Documentation
Mergeable
bool vtkUndoElement::Mergeable protected
Subclasses must set this flag to enable merging of consecutive elements in an UndoSet.
Definition at line 73 of file vtkUndoElement.h.
Referenced by PrintSelf(), and vtkUndoElement().
UndoSetWorkingContext
vtkCollection* vtkUndoElement::UndoSetWorkingContext protected
Definition at line 75 of file vtkUndoElement.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkUndoElement.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkUndoElement.cxx