ACloudViewer: cloudViewer::visualization::rendering::ColorGradingParams Class Reference
cloudViewer::visualization::rendering::ColorGradingParams Class Reference
Manages.
#include <ColorGrading.h>
Public Types
enum class Quality : std::uint8_t { kLow , kMedium , kHigh , kUltra }
Quality level of color grading operations.
enum class ToneMapping : std::uint8_t {
kLinear = 0 , kAcesLegacy = 1 , kAces = 2 , kFilmic = 3 ,
kUchimura = 4 , kReinhard = 5 , kDisplayRange = 6
}
Public Member Functions
ColorGradingParams (Quality q, ToneMapping algorithm)
void SetQuality (Quality q)
Quality GetQuality () const
void SetToneMapping (ToneMapping algorithm)
ToneMapping GetToneMapping () const
void SetTemperature (float temperature)
float GetTemperature () const
void SetTint (float tint)
float GetTint () const
void SetContrast (float contrast)
float GetContrast () const
void SetVibrance (float vibrance)
float GetVibrance () const
void SetSaturation (float saturation)
float GetSaturation () const
void SetChannelMixer (const Eigen::Vector3f &red, const Eigen::Vector3f &green, const Eigen::Vector3f &blue)
Eigen::Vector3f GetMixerRed () const
Eigen::Vector3f GetMixerGreen () const
Eigen::Vector3f GetMixerBlue () const
void SetShadowMidtoneHighlights (const Eigen::Vector4f &shadows, const Eigen::Vector4f &midtones, const Eigen::Vector4f &highlights, const Eigen::Vector4f &ranges)
Eigen::Vector4f GetShadows () const
Eigen::Vector4f GetMidtones () const
Eigen::Vector4f GetHighlights () const
Eigen::Vector4f GetRanges () const
void SetSlopeOffsetPower (const Eigen::Vector3f &slope, const Eigen::Vector3f &offset, const Eigen::Vector3f &power)
Eigen::Vector3f GetSlope () const
Eigen::Vector3f GetOffset () const
Eigen::Vector3f GetPower () const
void SetCurves (const Eigen::Vector3f &shadow_gamma, const Eigen::Vector3f &midpoint, const Eigen::Vector3f &highlight_scale)
Eigen::Vector3f GetShadowGamma () const
Eigen::Vector3f GetMidpoint () const
Eigen::Vector3f GetHighlightScale () const
Detailed Description
Manages.
Definition at line 18 of file ColorGrading.h.
Member Enumeration Documentation
Quality
enum cloudViewer::visualization::rendering::ColorGradingParams::Quality : std::uint8_t strong
Quality level of color grading operations.
Enumerator
kLow
kMedium
kHigh
kUltra
Definition at line 21 of file ColorGrading.h.
ToneMapping
enum cloudViewer::visualization::rendering::ColorGradingParams::ToneMapping : std::uint8_t strong
Enumerator
kLinear
kAcesLegacy
kAces
kFilmic
kUchimura
kReinhard
kDisplayRange
Definition at line 23 of file ColorGrading.h.
Constructor & Destructor Documentation
ColorGradingParams()
cloudViewer::visualization::rendering::ColorGradingParams::ColorGradingParams (Quality q, ToneMapping algorithm)
Definition at line 16 of file ColorGrading.cpp.
Member Function Documentation
GetContrast()
float cloudViewer::visualization::rendering::ColorGradingParams::GetContrast () const inline
Definition at line 48 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetHighlights()
Eigen::Vector4f cloudViewer::visualization::rendering::ColorGradingParams::GetHighlights () const inline
Definition at line 69 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetHighlightScale()
Eigen::Vector3f cloudViewer::visualization::rendering::ColorGradingParams::GetHighlightScale () const inline
Definition at line 84 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetMidpoint()
Eigen::Vector3f cloudViewer::visualization::rendering::ColorGradingParams::GetMidpoint () const inline
Definition at line 83 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetMidtones()
Eigen::Vector4f cloudViewer::visualization::rendering::ColorGradingParams::GetMidtones () const inline
Definition at line 68 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetMixerBlue()
Eigen::Vector3f cloudViewer::visualization::rendering::ColorGradingParams::GetMixerBlue () const inline
Definition at line 61 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetMixerGreen()
Eigen::Vector3f cloudViewer::visualization::rendering::ColorGradingParams::GetMixerGreen () const inline
Definition at line 60 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetMixerRed()
Eigen::Vector3f cloudViewer::visualization::rendering::ColorGradingParams::GetMixerRed () const inline
Definition at line 59 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetOffset()
Eigen::Vector3f cloudViewer::visualization::rendering::ColorGradingParams::GetOffset () const inline
Definition at line 76 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetPower()
Eigen::Vector3f cloudViewer::visualization::rendering::ColorGradingParams::GetPower () const inline
Definition at line 77 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetQuality()
Quality cloudViewer::visualization::rendering::ColorGradingParams::GetQuality () const inline
Definition at line 36 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetRanges()
Eigen::Vector4f cloudViewer::visualization::rendering::ColorGradingParams::GetRanges () const inline
Definition at line 70 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetSaturation()
float cloudViewer::visualization::rendering::ColorGradingParams::GetSaturation () const inline
Definition at line 54 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetShadowGamma()
Eigen::Vector3f cloudViewer::visualization::rendering::ColorGradingParams::GetShadowGamma () const inline
Definition at line 82 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetShadows()
Eigen::Vector4f cloudViewer::visualization::rendering::ColorGradingParams::GetShadows () const inline
Definition at line 67 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetSlope()
Eigen::Vector3f cloudViewer::visualization::rendering::ColorGradingParams::GetSlope () const inline
Definition at line 75 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetTemperature()
float cloudViewer::visualization::rendering::ColorGradingParams::GetTemperature () const inline
Definition at line 42 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetTint()
float cloudViewer::visualization::rendering::ColorGradingParams::GetTint () const inline
Definition at line 45 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetToneMapping()
ToneMapping cloudViewer::visualization::rendering::ColorGradingParams::GetToneMapping () const inline
Definition at line 39 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
GetVibrance()
float cloudViewer::visualization::rendering::ColorGradingParams::GetVibrance () const inline
Definition at line 51 of file ColorGrading.h.
Referenced by cloudViewer::visualization::rendering::FilamentView::SetColorGrading().
SetChannelMixer()
void cloudViewer::visualization::rendering::ColorGradingParams::SetChannelMixer (const Eigen::Vector3f & red, const Eigen::Vector3f & green, const Eigen::Vector3f & blue)
Definition at line 39 of file ColorGrading.cpp.
References ecvColor::blue(), ecvColor::green(), and ecvColor::red().
SetContrast()
void cloudViewer::visualization::rendering::ColorGradingParams::SetContrast (float contrast)
Definition at line 31 of file ColorGrading.cpp.
SetCurves()
void cloudViewer::visualization::rendering::ColorGradingParams::SetCurves (const Eigen::Vector3f & shadow_gamma, const Eigen::Vector3f & midpoint, const Eigen::Vector3f & highlight_scale)
Definition at line 66 of file ColorGrading.cpp.
SetQuality()
void cloudViewer::visualization::rendering::ColorGradingParams::SetQuality (Quality q)
Definition at line 19 of file ColorGrading.cpp.
SetSaturation()
void cloudViewer::visualization::rendering::ColorGradingParams::SetSaturation (float saturation)
Definition at line 35 of file ColorGrading.cpp.
SetShadowMidtoneHighlights()
void cloudViewer::visualization::rendering::ColorGradingParams::SetShadowMidtoneHighlights (const Eigen::Vector4f & shadows, const Eigen::Vector4f & midtones, const Eigen::Vector4f & highlights, const Eigen::Vector4f & ranges)
Definition at line 47 of file ColorGrading.cpp.
SetSlopeOffsetPower()
void cloudViewer::visualization::rendering::ColorGradingParams::SetSlopeOffsetPower (const Eigen::Vector3f & slope, const Eigen::Vector3f & offset, const Eigen::Vector3f & power)
Definition at line 58 of file ColorGrading.cpp.
References offset.
SetTemperature()
void cloudViewer::visualization::rendering::ColorGradingParams::SetTemperature (float temperature)
Definition at line 25 of file ColorGrading.cpp.
SetTint()
void cloudViewer::visualization::rendering::ColorGradingParams::SetTint (float tint)
Definition at line 29 of file ColorGrading.cpp.
SetToneMapping()
void cloudViewer::visualization::rendering::ColorGradingParams::SetToneMapping (ToneMapping algorithm)
Definition at line 21 of file ColorGrading.cpp.
SetVibrance()
void cloudViewer::visualization::rendering::ColorGradingParams::SetVibrance (float vibrance)
Definition at line 33 of file ColorGrading.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/ColorGrading.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/ColorGrading.cpp