ACloudViewer: Quadric Class Reference
Quadric Class Reference
Public Member Functions
Quadric ()
Quadric (const Eigen::Vector4d &plane, double weight=1)
Quadric & operator+= (const Quadric &other)
Quadric operator+ (const Quadric &other) const
double Eval (const Eigen::Vector3d &v) const
bool IsInvertible () const
Eigen::Vector3d Minimum () const
Public Attributes
Eigen::Matrix3d A_
A_ = n . n^T, where n is the plane normal.
Eigen::Vector3d b_
double c_
c_ = d . d, where d the non-normal component pf the plane parameters
Detailed Description
Error quadric that is used to minimize the squared distance of a point to its neigbhouring triangle planes. Cf. "Simplifying Surfaces with Color and Texture using Quadric Error Metrics" by Garland and Heckbert.
Definition at line 25 of file TriangleMeshSimplification.cpp.
Constructor & Destructor Documentation
Quadric() [1/2]
Quadric::Quadric () inline
Definition at line 27 of file TriangleMeshSimplification.cpp.
Quadric() [2/2]
Quadric::Quadric (const Eigen::Vector4d & plane, double weight = 1) inline
Definition at line 33 of file TriangleMeshSimplification.cpp.
Member Function Documentation
Eval()
double Quadric::Eval (const Eigen::Vector3d & v) const inline
Definition at line 55 of file TriangleMeshSimplification.cpp.
Referenced by ccMesh::SimplifyQuadricDecimation().
IsInvertible()
bool Quadric::IsInvertible () const inline
Definition at line 61 of file TriangleMeshSimplification.cpp.
References e.
Referenced by ccMesh::SimplifyQuadricDecimation(), and ccMesh::SimplifyVertexClustering().
Minimum()
Eigen::Vector3d Quadric::Minimum () const inline
Definition at line 63 of file TriangleMeshSimplification.cpp.
Referenced by ccMesh::SimplifyQuadricDecimation(), and ccMesh::SimplifyVertexClustering().
operator+()
Quadric Quadric::operator+ (const Quadric & other) const inline
Definition at line 47 of file TriangleMeshSimplification.cpp.
References A_, b_, and c_.
operator+=()
Quadric& Quadric::operator+= (const Quadric & other) inline
Definition at line 40 of file TriangleMeshSimplification.cpp.
References A_, b_, and c_.
Member Data Documentation
A_
Eigen::Matrix3d Quadric::A_
A_ = n . n^T, where n is the plane normal.
Definition at line 67 of file TriangleMeshSimplification.cpp.
Referenced by operator+(), and operator+=().
b_
Eigen::Vector3d Quadric::b_
b_ = d . n, where n is the plane normal and d the non-normal component of the plane parameters
Definition at line 70 of file TriangleMeshSimplification.cpp.
Referenced by operator+(), and operator+=().
c_
double Quadric::c_
c_ = d . d, where d the non-normal component pf the plane parameters
Definition at line 72 of file TriangleMeshSimplification.cpp.
Referenced by operator+(), and operator+=().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/src/TriangleMeshSimplification.cpp