ACloudViewer: SiftMatchGL Class Reference
SiftMatchGL Class Reference
#include <SiftMatch.h>
Public Member Functions
SiftMatchGL (int max_sift, int use_glsl)
virtual ~SiftMatchGL ()
bool Allocate (int max_sift, int mbm) override
void InitSiftMatch ()
void SetMaxSift (int max_sift) override
void SetDescriptors (int index, int num, const unsigned char *descriptor, int id=-1)
void SetDescriptors (int index, int num, const float *descriptor, int id=-1)
void SetFeautreLocation (int index, const float *locatoins, int gap)
int GetSiftMatch (int max_match, uint32_t match_buffer[][2], float distmax, float ratiomax, int mbm)
int GetGuidedSiftMatch (int max_match, uint32_t match_buffer[][2], float *H, float *F, float distmax, float ratiomax, float hdistmax, float fdistmax, int mbm)
Public Member Functions inherited from SiftMatchGPU
int CreateContextGL ()
int VerifyContextGL ()
SiftMatchGPU (int max_sift=4096)
virtual void SetLanguage (int gpu_language)
virtual void SetDeviceParam (int argc, char **argv)
virtual int GetMaxSift () const
virtual ~SiftMatchGPU ()
void SetFeatureLocation (int index, const SiftGPU::SiftKeypoint *keys)
Additional Inherited Members
Public Types inherited from SiftMatchGPU
enum SIFTMATCH_LANGUAGE { SIFTMATCH_SAME_AS_SIFTGPU = 0 , SIFTMATCH_GLSL = 2 , SIFTMATCH_CUDA = 3 , SIFTMATCH_CUDA_DEVICE0 = 3 }
Public Attributes inherited from SiftMatchGPU
int gpu_index = 0
Protected Member Functions inherited from SiftMatchGPU
virtual int _CreateContextGL ()
virtual int _VerifyContextGL ()
Protected Attributes inherited from SiftMatchGPU
int __max_sift
Detailed Description
Definition at line 28 of file SiftMatch.h.
Constructor & Destructor Documentation
SiftMatchGL()
SiftMatchGL::SiftMatchGL (int max_sift, int use_glsl)
Definition at line 45 of file SiftMatch.cpp.
References SiftMatchGPU::__max_sift, and NULL.
~SiftMatchGL()
SiftMatchGL::~SiftMatchGL () virtual
Definition at line 59 of file SiftMatch.cpp.
Member Function Documentation
Allocate()
bool SiftMatchGL::Allocate (int max_sift, int mbm) override virtual
Reimplemented from SiftMatchGPU.
Definition at line 67 of file SiftMatch.cpp.
References SetMaxSift().
GetGuidedSiftMatch()
int SiftMatchGL::GetGuidedSiftMatch (int max_match, uint32_t match_buffer[][2], float * H, float * F, float distmax, float ratiomax, float hdistmax, float fdistmax, int mbm) virtual
Reimplemented from SiftMatchGPU.
Definition at line 410 of file SiftMatch.cpp.
References GLTexImage::AttachToFBO(), GLTexImage::BindTex(), GLTexImage::DrawQuad(), GLTexImage::FitTexViewPort(), GLTexImage::SetImageSize(), GLTexImage::UnbindMultiTex(), and ProgramGPU::UseProgram().
GetSiftMatch()
int SiftMatchGL::GetSiftMatch (int max_match, uint32_t match_buffer[][2], float distmax, float ratiomax, int mbm) virtual
Reimplemented from SiftMatchGPU.
Definition at line 521 of file SiftMatch.cpp.
References GlobalParam::_texTarget, GLTexImage::AttachToFBO(), GLTexImage::BindTex(), GLTexImage::DrawQuad(), GLTexImage::FitTexViewPort(), GLTexImage::SetImageSize(), and ProgramGPU::UseProgram().
InitSiftMatch()
void SiftMatchGL::InitSiftMatch () virtual
Reimplemented from SiftMatchGPU.
Definition at line 124 of file SiftMatch.cpp.
References GlobalParam::_GoodOpenGL, and GlobalUtil::InitGLParam().
SetDescriptors() [1/2]
void SiftMatchGL::SetDescriptors (int index, int num, const float * descriptor, int id = -1) virtual
Reimplemented from SiftMatchGPU.
Definition at line 211 of file SiftMatch.cpp.
References SiftMatchGPU::__max_sift, GlobalParam::_texTarget, GLTexImage::BindTex(), descriptors, GLTexImage::SetImageSize(), and GLTexImage::UnbindTex().
SetDescriptors() [2/2]
void SiftMatchGL::SetDescriptors (int index, int num, const unsigned char * descriptor, int id = -1) virtual
Reimplemented from SiftMatchGPU.
Definition at line 135 of file SiftMatch.cpp.
References SiftMatchGPU::__max_sift, GlobalParam::_texTarget, GLTexImage::BindTex(), descriptors, GLTexImage::SetImageSize(), and GLTexImage::UnbindTex().
SetFeautreLocation()
void SiftMatchGL::SetFeautreLocation (int index, const float * locatoins, int gap) virtual
Reimplemented from SiftMatchGPU.
Definition at line 173 of file SiftMatch.cpp.
References GlobalParam::_texTarget, GLTexImage::BindTex(), GLTexImage::SetImageSize(), and GLTexImage::UnbindTex().
SetMaxSift()
void SiftMatchGL::SetMaxSift (int max_sift) override virtual
Reimplemented from SiftMatchGPU.
Definition at line 72 of file SiftMatch.cpp.
References SiftMatchGPU::__max_sift, and GlobalParam::_texMaxDimGL.
Referenced by Allocate().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/SiftMatch.h
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/SiftMatch.cpp