ACloudViewer: cloudViewer::io::AzureKinectSensorConfig Class Reference
cloudViewer::io::AzureKinectSensorConfig Class Reference
#include <AzureKinectSensorConfig.h>
Public Member Functions
AzureKinectSensorConfig ()
Default constructor, default configs will be used.
AzureKinectSensorConfig (const std::unordered_map< std::string, std::string > &config)
Initialize config with a map.
bool ConvertToJsonValue (Json::Value &value) const override
bool ConvertFromJsonValue (const Json::Value &value) override
void ConvertFromNativeConfig (const _k4a_device_configuration_t &k4a_config)
_k4a_device_configuration_t ConvertToNativeConfig () const
Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
virtual ~IJsonConvertible ()
virtual std::string ToString () const
Convert to a styled string representation of JSON data for display.
Public Attributes
std::unordered_map< std::string, std::string > config_
Static Protected Member Functions
static bool IsValidConfig (const std::unordered_map< std::string, std::string > &config, bool verbose=true)
Additional Inherited Members
Static Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
static bool EigenVector3dFromJsonArray (Eigen::Vector3d &vec, const Json::Value &value)
static bool EigenVector3dToJsonArray (const Eigen::Vector3d &vec, Json::Value &value)
static bool EigenVector4dFromJsonArray (Eigen::Vector4d &vec, const Json::Value &value)
static bool EigenVector4dToJsonArray (const Eigen::Vector4d &vec, Json::Value &value)
static bool EigenMatrix3dFromJsonArray (Eigen::Matrix3d &mat, const Json::Value &value)
static bool EigenMatrix3dToJsonArray (const Eigen::Matrix3d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d_u &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d_u &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d_u &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d_u &mat, Json::Value &value)
Detailed Description
AzureKinect sensor configuration.
Definition at line 27 of file AzureKinectSensorConfig.h.
Constructor & Destructor Documentation
AzureKinectSensorConfig() [1/2]
cloudViewer::io::AzureKinectSensorConfig::AzureKinectSensorConfig ()
Default constructor, default configs will be used.
Definition at line 126 of file AzureKinectSensorConfig.cpp.
References config_, and cloudViewer::io::standard_config.
AzureKinectSensorConfig() [2/2]
cloudViewer::io::AzureKinectSensorConfig::AzureKinectSensorConfig (const std::unordered_map< std::string, std::string > & config)
Initialize config with a map.
Definition at line 219 of file AzureKinectSensorConfig.cpp.
References config_, IsValidConfig(), and LogWarning.
Member Function Documentation
ConvertFromJsonValue()
bool cloudViewer::io::AzureKinectSensorConfig::ConvertFromJsonValue (const Json::Value & value) override virtual
Implements cloudViewer::utility::IJsonConvertible.
Definition at line 246 of file AzureKinectSensorConfig.cpp.
References config_, and IsValidConfig().
ConvertFromNativeConfig()
void cloudViewer::io::AzureKinectSensorConfig::ConvertFromNativeConfig (const _k4a_device_configuration_t & k4a_config)
Definition at line 262 of file AzureKinectSensorConfig.cpp.
References config_, IsValidConfig(), cloudViewer::io::k4a_color_resolution_t_to_string, cloudViewer::io::k4a_depth_mode_t_to_string, cloudViewer::io::k4a_fps_t_to_string, cloudViewer::io::k4a_image_format_t_to_string, cloudViewer::io::k4a_wired_sync_mode_t_to_string, LogError, and patch::to_string().
ConvertToJsonValue()
bool cloudViewer::io::AzureKinectSensorConfig::ConvertToJsonValue (Json::Value & value) const override virtual
Implements cloudViewer::utility::IJsonConvertible.
Definition at line 231 of file AzureKinectSensorConfig.cpp.
References config_.
ConvertToNativeConfig()
k4a_device_configuration_t cloudViewer::io::AzureKinectSensorConfig::ConvertToNativeConfig () const
Definition at line 282 of file AzureKinectSensorConfig.cpp.
References config_, cloudViewer::io::string_to_k4a_color_resolution_t, cloudViewer::io::string_to_k4a_depth_mode_t, cloudViewer::io::string_to_k4a_fps_t, cloudViewer::io::string_to_k4a_image_format_t(), and cloudViewer::io::string_to_k4a_wired_sync_mode_t.
Referenced by cloudViewer::io::AzureKinectSensor::Connect(), and cloudViewer::io::AzureKinectRecorder::OpenRecord().
IsValidConfig()
bool cloudViewer::io::AzureKinectSensorConfig::IsValidConfig (const std::unordered_map< std::string, std::string > & config, bool verbose = true) static protected
Definition at line 130 of file AzureKinectSensorConfig.cpp.
References LogWarning, cloudViewer::io::standard_config, cloudViewer::io::string_to_k4a_color_resolution_t, cloudViewer::io::string_to_k4a_depth_mode_t, cloudViewer::io::string_to_k4a_fps_t, cloudViewer::io::string_to_k4a_image_format_t(), and cloudViewer::io::string_to_k4a_wired_sync_mode_t.
Referenced by AzureKinectSensorConfig(), ConvertFromJsonValue(), and ConvertFromNativeConfig().
Member Data Documentation
config_
std::unordered_map<std::string, std::string> cloudViewer::io::AzureKinectSensorConfig::config_
Definition at line 43 of file AzureKinectSensorConfig.h.
Referenced by AzureKinectSensorConfig(), ConvertFromJsonValue(), ConvertFromNativeConfig(), ConvertToJsonValue(), and ConvertToNativeConfig().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/io/sensor/azure_kinect/AzureKinectSensorConfig.h
/root/ACloudViewer/libs/cloudViewer/io/sensor/azure_kinect/AzureKinectSensorConfig.cpp