ACloudViewer: MinimumCutSegmentationDlg Class Reference
MinimumCutSegmentationDlg Class Reference
#include <MinimumCutSegmentationDlg.h>
Public Slots
void updateForeGroundPoint ()
void onLabelChanged (int)
Public Member Functions
MinimumCutSegmentationDlg (ecvMainAppInterface *app)
void refreshLabelComboBox ()
Protected Member Functions
QString getEntityName (ccHObject *obj)
cc2DLabel * get2DLabelFromCombo (QComboBox *comboBox, ccHObject *dbRoot)
Protected Attributes
ecvMainAppInterface * m_app
Gives access to the application (data-base, UI, etc.)
Detailed Description
Definition at line 22 of file MinimumCutSegmentationDlg.h.
Constructor & Destructor Documentation
MinimumCutSegmentationDlg()
MinimumCutSegmentationDlg::MinimumCutSegmentationDlg (ecvMainAppInterface * app) explicit
Definition at line 17 of file MinimumCutSegmentationDlg.cpp.
References onLabelChanged().
Member Function Documentation
get2DLabelFromCombo()
cc2DLabel * MinimumCutSegmentationDlg::get2DLabelFromCombo (QComboBox * comboBox, ccHObject * dbRoot) protected
Definition at line 97 of file MinimumCutSegmentationDlg.cpp.
References ccHObject::find(), ccObject::isA(), and CV_TYPES::LABEL_2D.
Referenced by updateForeGroundPoint().
getEntityName()
QString MinimumCutSegmentationDlg::getEntityName (ccHObject * obj) protected
Definition at line 84 of file MinimumCutSegmentationDlg.cpp.
References ccObject::getName(), ccObject::getUniqueID(), and name.
Referenced by refreshLabelComboBox().
onLabelChanged
void MinimumCutSegmentationDlg::onLabelChanged (int dummy) slot
Definition at line 27 of file MinimumCutSegmentationDlg.cpp.
References updateForeGroundPoint().
Referenced by MinimumCutSegmentationDlg().
refreshLabelComboBox()
void MinimumCutSegmentationDlg::refreshLabelComboBox ()
Definition at line 31 of file MinimumCutSegmentationDlg.cpp.
References getEntityName(), CV_TYPES::LABEL_2D, m_app, name, and updateForeGroundPoint().
Referenced by MinimumCutSegmentation::openInputDialog().
updateForeGroundPoint
void MinimumCutSegmentationDlg::updateForeGroundPoint () slot
Definition at line 64 of file MinimumCutSegmentationDlg.cpp.
References cc2DLabel::PickedPoint::cloud, get2DLabelFromCombo(), cc2DLabel::getPickedPoint(), cloudViewer::GenericIndexedCloud::getPoint(), cc2DLabel::PickedPoint::index, m_app, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by onLabelChanged(), and refreshLabelComboBox().
Member Data Documentation
m_app
ecvMainAppInterface* MinimumCutSegmentationDlg::m_app protected
Gives access to the application (data-base, UI, etc.)
Definition at line 36 of file MinimumCutSegmentationDlg.h.
Referenced by refreshLabelComboBox(), and updateForeGroundPoint().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Segmentations/dialogs/MinimumCutSegmentationDlg.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Segmentations/dialogs/MinimumCutSegmentationDlg.cpp