ACloudViewer: VtkUtils::SignalBlocker Class Reference
VtkUtils::SignalBlocker Class Reference
#include <signalblocker.h>
Public Member Functions
SignalBlocker (QObject *object=nullptr)
~SignalBlocker ()
void addObject (QObject *object)
Detailed Description
Definition at line 16 of file signalblocker.h.
Constructor & Destructor Documentation
SignalBlocker()
VtkUtils::SignalBlocker::SignalBlocker (QObject * object = nullptr) explicit
Definition at line 12 of file signalblocker.cpp.
References addObject().
~SignalBlocker()
VtkUtils::SignalBlocker::~SignalBlocker ()
Definition at line 21 of file signalblocker.cpp.
Member Function Documentation
addObject()
void VtkUtils::SignalBlocker::addObject (QObject * object)
Definition at line 14 of file signalblocker.cpp.
Referenced by cvGlyphFilter::cvGlyphFilter(), cvCutFilter::modelReady(), cvStreamlineFilter::modelReady(), cvCutFilter::onCenterChanged(), cvCutFilter::onNormalChanged(), cvCutFilter::onOriginChanged(), and SignalBlocker().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/signalblocker.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/signalblocker.cpp