ACloudViewer: ccWaveformProxy Class Reference
ccWaveformProxy Class Reference
Waveform proxy.
#include <ecvWaveform.h>
Public Member Functions
ccWaveformProxy (const ccWaveform &w, const WaveformDescriptor &d, const uint8_t *storage)
Default constructor.
bool isValid () const
Returns whether the waveform (proxy) is valid or not.
uint8_t descriptorID () const
Returns the associated descriptor (ID)
uint32_t getRawSample (uint32_t i) const
Returns the (raw) value of a given sample.
double getSample (uint32_t i) const
Returns the (real) value of a given sample (in volts)
double getRange (double &minVal, double &maxVal) const
Returns the range of (real) samples.
bool decodeSamples (std::vector< double > &values) const
Decodes the samples and store them in a vector.
bool toASCII (const QString &filename) const
Exports (real) samples to an ASCII file.
CCVector3 getSamplePos (float i, const CCVector3 &P0) const
Returns the sample position in 3D.
uint32_t byteCount () const
Returns the number of allocated bytes.
const uint8_t * data () const
Gives access to the internal data.
const CCVector3f & beamDir () const
Returns the beam direction.
float echoTime_ps () const
Returns the echo time (in picoseconds)
uint32_t numberOfSamples () const
Returns the number of samples.
const WaveformDescriptor & descriptor () const
Returns the descriptor.
const ccWaveform & waveform () const
Returns the waveform.
Protected Attributes
const ccWaveform & m_w
Associated ccWaveform instance.
const WaveformDescriptor & m_d
Associated descriptor.
const uint8_t * m_storage
Associated storage data.
Detailed Description
Waveform proxy.
For easier access to the waveform data
Definition at line 189 of file ecvWaveform.h.
Constructor & Destructor Documentation
ccWaveformProxy()
ccWaveformProxy::ccWaveformProxy (const ccWaveform & w, const WaveformDescriptor & d, const uint8_t * storage) inline
Default constructor.
Definition at line 192 of file ecvWaveform.h.
Member Function Documentation
beamDir()
const CCVector3f& ccWaveformProxy::beamDir () const inline
Returns the beam direction.
Definition at line 245 of file ecvWaveform.h.
Referenced by define_ccWaveform().
byteCount()
uint32_t ccWaveformProxy::byteCount () const inline
Returns the number of allocated bytes.
Definition at line 239 of file ecvWaveform.h.
Referenced by define_ccWaveform().
data()
const uint8_t* ccWaveformProxy::data () const inline
Gives access to the internal data.
Definition at line 242 of file ecvWaveform.h.
Referenced by define_ccWaveform().
decodeSamples()
bool ccWaveformProxy::decodeSamples (std::vector< double > & values) const inline
Decodes the samples and store them in a vector.
Definition at line 224 of file ecvWaveform.h.
descriptor()
const WaveformDescriptor& ccWaveformProxy::descriptor () const inline
Returns the descriptor.
Definition at line 254 of file ecvWaveform.h.
Referenced by define_ccWaveform().
descriptorID()
uint8_t ccWaveformProxy::descriptorID () const inline
Returns the associated descriptor (ID)
Warning
A value of zero indicates that there is no associated waveform data.
Definition at line 206 of file ecvWaveform.h.
Referenced by define_ccWaveform(), and LASFWFFilter::saveToFile().
echoTime_ps()
float ccWaveformProxy::echoTime_ps () const inline
Returns the echo time (in picoseconds)
Definition at line 248 of file ecvWaveform.h.
Referenced by define_ccWaveform().
getRange()
double ccWaveformProxy::getRange (double & minVal, double & maxVal) const inline
Returns the range of (real) samples.
Definition at line 219 of file ecvWaveform.h.
getRawSample()
uint32_t ccWaveformProxy::getRawSample (uint32_t i) const inline
Returns the (raw) value of a given sample.
Definition at line 209 of file ecvWaveform.h.
Referenced by define_ccWaveform().
getSample()
double ccWaveformProxy::getSample (uint32_t i) const inline
Returns the (real) value of a given sample (in volts)
Definition at line 214 of file ecvWaveform.h.
getSamplePos()
CCVector3 ccWaveformProxy::getSamplePos (float i, const CCVector3 & P0) const inline
Returns the sample position in 3D.
Definition at line 234 of file ecvWaveform.h.
Referenced by define_ccWaveform().
isValid()
bool ccWaveformProxy::isValid () const inline
Returns whether the waveform (proxy) is valid or not.
Definition at line 198 of file ecvWaveform.h.
Referenced by define_ccWaveform(), and LASFWFFilter::saveToFile().
numberOfSamples()
uint32_t ccWaveformProxy::numberOfSamples () const inline
Returns the number of samples.
Definition at line 251 of file ecvWaveform.h.
toASCII()
bool ccWaveformProxy::toASCII (const QString & filename) const inline
Exports (real) samples to an ASCII file.
Definition at line 229 of file ecvWaveform.h.
Referenced by define_ccWaveform().
waveform()
const ccWaveform& ccWaveformProxy::waveform () const inline
Returns the waveform.
Definition at line 256 of file ecvWaveform.h.
Referenced by define_ccWaveform(), and LASFWFFilter::saveToFile().
Member Data Documentation
m_d
const WaveformDescriptor& ccWaveformProxy::m_d protected
Associated descriptor.
Definition at line 262 of file ecvWaveform.h.
m_storage
const uint8_t* ccWaveformProxy::m_storage protected
Associated storage data.
Definition at line 264 of file ecvWaveform.h.
m_w
const ccWaveform& ccWaveformProxy::m_w protected
Associated ccWaveform instance.
Definition at line 260 of file ecvWaveform.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/eCV_db/include/ecvWaveform.h