ACloudViewer: ccSelectChildrenDlg Class Reference
ccSelectChildrenDlg Class Reference
Minimal dialog to pick one element in a list (combo box)
#include <ecvSelectChildrenDlg.h>
Public Member Functions
ccSelectChildrenDlg (QWidget *parent=nullptr)
Default constructor.
~ccSelectChildrenDlg () override
void addType (QString typeName, CV_CLASS_ENUM type)
Add an element to the 'type' combo box.
CV_CLASS_ENUM getSelectedType ()
Returns the selected type.
QString getSelectedName ()
Returns the selected name (if any)
bool getStrictMatchState () const
Returns the state of the strict type checkbox.
bool getTypeIsUsed () const
bool getNameIsRegex () const
if the name must be considered as regex
bool getNameMatchIsUsed () const
if performing name-match (regex or not)
Protected Slots
void onAccept ()
Called when the dialog is accepted.
Detailed Description
Minimal dialog to pick one element in a list (combo box)
Definition at line 21 of file ecvSelectChildrenDlg.h.
Constructor & Destructor Documentation
ccSelectChildrenDlg()
ccSelectChildrenDlg::ccSelectChildrenDlg (QWidget * parent = nullptr) explicit
Default constructor.
Definition at line 19 of file ecvSelectChildrenDlg.cpp.
References onAccept(), s_lastName, s_lastNameState, s_lastTypeState, s_lastTypeStrictState, and s_lastUseRegex.
~ccSelectChildrenDlg()
ccSelectChildrenDlg::~ccSelectChildrenDlg () override
Definition at line 33 of file ecvSelectChildrenDlg.cpp.
Member Function Documentation
addType()
void ccSelectChildrenDlg::addType (QString typeName, CV_CLASS_ENUM type)
Add an element to the 'type' combo box.
Definition at line 38 of file ecvSelectChildrenDlg.cpp.
References s_lastType, and type.
Referenced by ccDBRoot::selectByTypeAndName().
getNameIsRegex()
bool ccSelectChildrenDlg::getNameIsRegex () const
if the name must be considered as regex
Definition at line 82 of file ecvSelectChildrenDlg.cpp.
Referenced by onAccept(), and ccDBRoot::selectByTypeAndName().
getNameMatchIsUsed()
bool ccSelectChildrenDlg::getNameMatchIsUsed () const
if performing name-match (regex or not)
Definition at line 86 of file ecvSelectChildrenDlg.cpp.
Referenced by ccDBRoot::selectByTypeAndName().
getSelectedName()
QString ccSelectChildrenDlg::getSelectedName ()
Returns the selected name (if any)
Definition at line 66 of file ecvSelectChildrenDlg.cpp.
Referenced by ccDBRoot::selectByTypeAndName().
getSelectedType()
CV_CLASS_ENUM ccSelectChildrenDlg::getSelectedType ()
Returns the selected type.
Definition at line 56 of file ecvSelectChildrenDlg.cpp.
References CV_TYPES::HIERARCHY_OBJECT.
Referenced by onAccept(), and ccDBRoot::selectByTypeAndName().
getStrictMatchState()
bool ccSelectChildrenDlg::getStrictMatchState () const
Returns the state of the strict type checkbox.
Definition at line 74 of file ecvSelectChildrenDlg.cpp.
Referenced by ccDBRoot::selectByTypeAndName().
getTypeIsUsed()
bool ccSelectChildrenDlg::getTypeIsUsed () const
if the type checkbox is checked the children are filtered before checking the name for matches
Definition at line 78 of file ecvSelectChildrenDlg.cpp.
Referenced by ccDBRoot::selectByTypeAndName().
onAccept
void ccSelectChildrenDlg::onAccept () protected slot
Called when the dialog is accepted.
Definition at line 47 of file ecvSelectChildrenDlg.cpp.
References getNameIsRegex(), getSelectedType(), s_lastName, s_lastNameState, s_lastType, s_lastTypeState, s_lastTypeStrictState, and s_lastUseRegex.
Referenced by ccSelectChildrenDlg().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvSelectChildrenDlg.h
/root/ACloudViewer/app/ecvSelectChildrenDlg.cpp