ACloudViewer: ecvPS Class Reference
ecvPS Class Reference
Persistent settings key (to be used with QSettings)
#include <ecvPersistentSettings.h>
Static Public Member Functions
static const QString LoadFile ()
static const QString SaveFile ()
static const QString ThemeSettings ()
static const QString CurrentTheme ()
static const QString MainWindowSettings ()
static const QString MainWinGeom ()
static const QString MainWinState ()
static const QString CurrentPath ()
static const QString TextureFilePath ()
static const QString SelectedImageInputFilter ()
static const QString SelectedInputFilter ()
static const QString SelectedOutputFilterCloud ()
static const QString SelectedOutputFilterMesh ()
static const QString SelectedOutputFilterImage ()
static const QString SelectedOutputFilterPoly ()
static const QString DuplicatePointsGroup ()
static const QString DuplicatePointsMinDist ()
static const QString HeightGridGeneration ()
static const QString VolumeCalculation ()
static const QString Console ()
static const QString GlobalShift ()
static const QString MaxAbsCoord ()
static const QString MaxAbsDiag ()
static const QString AutoPickRotationCenter ()
static const QString AutoShowCenter ()
static const QString AutoShowReconstructionToolBar ()
static const QString CustomLayoutGeom ()
static const QString CustomLayoutState ()
static const QString DoNotRestoreWindowGeometry ()
static const QString Shortcuts ()
static const QString AppStyle ()
Detailed Description
Persistent settings key (to be used with QSettings)
Definition at line 16 of file ecvPersistentSettings.h.
Member Function Documentation
AppStyle()
static const QString ecvPS::AppStyle () inline static
Definition at line 106 of file ecvPersistentSettings.h.
AutoPickRotationCenter()
static const QString ecvPS::AutoPickRotationCenter () inline static
Definition at line 85 of file ecvPersistentSettings.h.
Referenced by MainWindow::MainWindow().
AutoShowCenter()
static const QString ecvPS::AutoShowCenter () inline static
Definition at line 88 of file ecvPersistentSettings.h.
Referenced by MainWindow::MainWindow().
AutoShowReconstructionToolBar()
static const QString ecvPS::AutoShowReconstructionToolBar () inline static
Definition at line 91 of file ecvPersistentSettings.h.
Console()
static const QString ecvPS::Console () inline static
Definition at line 75 of file ecvPersistentSettings.h.
Referenced by ecvConsole::EnableQtMessages(), and ecvConsole::Init().
CurrentPath()
static const QString ecvPS::CurrentPath () inline static
Definition at line 39 of file ecvPersistentSettings.h.
Referenced by ccColorScaleEditorDialog::exportCurrentScale(), MatrixDisplayDlg::exportToASCII(), ecvAnnotationsTool::importClassesFromFile(), ccColorScaleEditorDialog::importScale(), ccApplyTransformationDlg::loadFromASCIIFile(), ccHistogramWindowDlg::onExportToCSV(), G3PointPlots::onExportToCSV(), ccHistogramWindowDlg::onExportToImage(), G3PointPlots::onExportToImage(), and ccWaveDialog::onExportWaveAsCSV().
CurrentTheme()
static const QString ecvPS::CurrentTheme () inline static
Definition at line 27 of file ecvPersistentSettings.h.
Referenced by main().
CustomLayoutGeom()
static const QString ecvPS::CustomLayoutGeom () inline static
Definition at line 94 of file ecvPersistentSettings.h.
Referenced by ecvLayoutManager::restoreCustomLayout(), and ecvLayoutManager::saveCustomLayout().
CustomLayoutState()
static const QString ecvPS::CustomLayoutState () inline static
Definition at line 97 of file ecvPersistentSettings.h.
Referenced by ecvLayoutManager::restoreCustomLayout(), and ecvLayoutManager::saveCustomLayout().
DoNotRestoreWindowGeometry()
static const QString ecvPS::DoNotRestoreWindowGeometry () inline static
Definition at line 100 of file ecvPersistentSettings.h.
Referenced by MainWindow::MainWindow().
DuplicatePointsGroup()
static const QString ecvPS::DuplicatePointsGroup () inline static
Definition at line 63 of file ecvPersistentSettings.h.
DuplicatePointsMinDist()
static const QString ecvPS::DuplicatePointsMinDist () inline static
Definition at line 66 of file ecvPersistentSettings.h.
GlobalShift()
static const QString ecvPS::GlobalShift () inline static
Definition at line 76 of file ecvPersistentSettings.h.
Referenced by InitEnvironment().
HeightGridGeneration()
static const QString ecvPS::HeightGridGeneration () inline static
Definition at line 69 of file ecvPersistentSettings.h.
Referenced by ccRasterizeTool::generateASCIIMatrix(), ccRasterizeTool::generateImage(), ccRasterizeTool::generateRaster(), ccRasterizeTool::loadSettings(), and ccRasterizeTool::saveSettings().
LoadFile()
static const QString ecvPS::LoadFile () inline static
Definition at line 18 of file ecvPersistentSettings.h.
Referenced by ecvRecentFiles::addFilePath(), ecvRecentFiles::ecvRecentFiles(), MatrixDisplayDlg::exportToASCII(), ecvAnnotationsTool::importClassesFromFile(), ccColorScaleEditorDialog::importScale(), and ccApplyTransformationDlg::loadFromASCIIFile().
MainWindowSettings()
static const QString ecvPS::MainWindowSettings () inline static
Definition at line 30 of file ecvPersistentSettings.h.
MainWinGeom()
static const QString ecvPS::MainWinGeom () inline static
Definition at line 33 of file ecvPersistentSettings.h.
Referenced by ecvLayoutManager::restoreDefaultLayout(), ecvLayoutManager::restoreGUILayout(), and ecvLayoutManager::saveGUILayout().
MainWinState()
static const QString ecvPS::MainWinState () inline static
Definition at line 36 of file ecvPersistentSettings.h.
Referenced by ecvLayoutManager::restoreDefaultLayout(), ecvLayoutManager::restoreGUILayout(), and ecvLayoutManager::saveGUILayout().
MaxAbsCoord()
static const QString ecvPS::MaxAbsCoord () inline static
Definition at line 79 of file ecvPersistentSettings.h.
Referenced by InitEnvironment().
MaxAbsDiag()
static const QString ecvPS::MaxAbsDiag () inline static
Definition at line 82 of file ecvPersistentSettings.h.
Referenced by InitEnvironment().
SaveFile()
static const QString ecvPS::SaveFile () inline static
Definition at line 21 of file ecvPersistentSettings.h.
Referenced by ccColorScaleEditorDialog::exportCurrentScale(), ccHistogramWindowDlg::onExportToCSV(), G3PointPlots::onExportToCSV(), ccHistogramWindowDlg::onExportToImage(), G3PointPlots::onExportToImage(), and ccWaveDialog::onExportWaveAsCSV().
SelectedImageInputFilter()
static const QString ecvPS::SelectedImageInputFilter () inline static
Definition at line 45 of file ecvPersistentSettings.h.
SelectedInputFilter()
static const QString ecvPS::SelectedInputFilter () inline static
Definition at line 48 of file ecvPersistentSettings.h.
SelectedOutputFilterCloud()
static const QString ecvPS::SelectedOutputFilterCloud () inline static
Definition at line 51 of file ecvPersistentSettings.h.
SelectedOutputFilterImage()
static const QString ecvPS::SelectedOutputFilterImage () inline static
Definition at line 57 of file ecvPersistentSettings.h.
SelectedOutputFilterMesh()
static const QString ecvPS::SelectedOutputFilterMesh () inline static
Definition at line 54 of file ecvPersistentSettings.h.
SelectedOutputFilterPoly()
static const QString ecvPS::SelectedOutputFilterPoly () inline static
Definition at line 60 of file ecvPersistentSettings.h.
Shortcuts()
static const QString ecvPS::Shortcuts () inline static
Definition at line 103 of file ecvPersistentSettings.h.
Referenced by ecvShortcutDialog::restoreShortcutsFromQSettings().
TextureFilePath()
static const QString ecvPS::TextureFilePath () inline static
Definition at line 42 of file ecvPersistentSettings.h.
ThemeSettings()
static const QString ecvPS::ThemeSettings () inline static
Definition at line 24 of file ecvPersistentSettings.h.
Referenced by main().
VolumeCalculation()
static const QString ecvPS::VolumeCalculation () inline static
Definition at line 72 of file ecvPersistentSettings.h.
Referenced by ccVolumeCalcTool::loadSettings(), and ccVolumeCalcTool::saveSettings().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CVPluginAPI/include/ecvPersistentSettings.h