ACloudViewer: cvGlyphFilter Class Reference
cvGlyphFilter Class Reference
#include <cvGlyphFilter.h>
Public Member Functions
cvGlyphFilter (QWidget *parent=nullptr)
virtual void apply () override
virtual ccHObject * getOutput () override
virtual void clearAllActor () override
virtual void showInteractor (bool state) override
Public Member Functions inherited from cvGenericFilter
cvGenericFilter (QWidget *parent=nullptr)
virtual ~cvGenericFilter ()
virtual void start ()
virtual void update ()
virtual void reset ()
virtual void restoreOrigin ()
virtual void getOutput (std::vector< ccHObject * > &outputSlices, std::vector< ccPolyline * > &outputContours)
virtual bool initModel ()
virtual bool setInput (ccHObject *obj)
virtual void shift (const CCVector3d &v)
Shifts the current interactor.
virtual void updateUi ()
virtual void getInteractorInfos (ccBBox &bbox, ccGLMatrixd &trans)
virtual void getInteractorTransformation (ccGLMatrixd &trans)
virtual void getInteractorBounds (ccBBox &bbox)
void setUpViewer (PclUtils::PCLVis *viewer)
void showOutline (bool show=true)
void setNegative (bool state)
void setInteractor (vtkRenderWindowInteractor *interactor)
vtkRenderWindowInteractor * getInteractor ()
Protected Member Functions
virtual void modelReady () override
virtual void createUi () override
virtual void initFilter () override
virtual void dataChanged () override
Protected Member Functions inherited from cvGenericFilter
virtual void colorsChanged ()
void setDisplayEffect (DisplayEffect effect)
DisplayEffect displayEffect () const
void safeOff (vtk3DWidget *widget)
void updateSize ()
void UpdateScalarRange ()
void applyDisplayEffect ()
void setScalarBarColors (const QColor &clr1, const QColor &clr2)
QColor color1 () const
QColor color2 () const
void setScalarRange (double min, double max)
double scalarMin () const
double scalarMax () const
vtkSmartPointer< vtkDataArray > getActorScalars (vtkSmartPointer< vtkActor > actor)
int getDefaultScalarInterpolationForDataSet (vtkDataSet *data)
vtkSmartPointer< vtkLookupTable > createLookupTable (double min, double max)
template<class ConfigClass >
void setupConfigWidget (ConfigClass *cc)
template<class DataObject , class Mapper >
void createActorFromData (vtkDataObject *dataObj)
void showScalarBar (bool show=true)
void setOutlineColor (const QColor &clr)
bool isValidPolyData () const
bool isValidDataSet () const
void addActor (const vtkSmartPointer< vtkProp > actor)
void removeActor (const vtkSmartPointer< vtkProp > actor)
void setResultData (vtkSmartPointer< vtkDataObject > data)
vtkSmartPointer< vtkDataObject > resultData () const
Additional Inherited Members
Protected Types inherited from cvGenericFilter
enum DisplayEffect { Opaque , Transparent , Points , Wireframe }
Protected Slots inherited from cvGenericFilter
void onDoubleClick (int x, int y)
Protected Attributes inherited from cvGenericFilter
Ui::GenericFilterDlg * m_ui = nullptr
DisplayEffect m_displayEffect = Opaque
vtkDataObject * m_dataObject = nullptr
vtkSmartPointer< vtkDataObject > m_resultData
bool m_keepMode
bool m_negative
bool m_meshMode
bool m_preview
std::string m_id
ccHObject * m_entity = nullptr
PclUtils::PCLVis * m_viewer = nullptr
vtkRenderWindowInteractor * m_interactor = nullptr
vtkSmartPointer< vtkActor > m_modelActor
vtkSmartPointer< vtkLODActor > m_filterActor
vtkSmartPointer< vtkScalarBarActor > m_scalarBar
vtkSmartPointer< vtkActor > m_outlineActor
QColor m_color1 = Qt::blue
QColor m_color2 = Qt::red
double m_scalarMin = 0.0
double m_scalarMax = 1.0
Static Protected Attributes inherited from cvGenericFilter
static const int MAX_PREVIEW_NUMBER = 20e4
Detailed Description
Definition at line 18 of file cvGlyphFilter.h.
Constructor & Destructor Documentation
cvGlyphFilter()
cvGlyphFilter::cvGlyphFilter (QWidget * parent = nullptr) explicit
Definition at line 39 of file cvGlyphFilter.cpp.
References VtkUtils::SignalBlocker::addObject(), and createUi().
Member Function Documentation
apply()
void cvGlyphFilter::apply () override virtual
Implements cvGenericFilter.
Definition at line 60 of file cvGlyphFilter.cpp.
References cvGenericFilter::addActor(), cvGenericFilter::applyDisplayEffect(), cvGenericFilter::m_dataObject, cvGenericFilter::m_filterActor, VTK_CREATE, Utils::vtkColor(), and VtkUtils::vtkInitOnce().
Referenced by dataChanged(), and modelReady().
clearAllActor()
void cvGlyphFilter::clearAllActor () override virtual
Reimplemented from cvGenericFilter.
Definition at line 139 of file cvGlyphFilter.cpp.
References cvGenericFilter::clearAllActor(), and cvGenericFilter::removeActor().
createUi()
void cvGlyphFilter::createUi () override protected virtual
Reimplemented from cvGenericFilter.
Definition at line 151 of file cvGlyphFilter.cpp.
References cvGenericFilter::createUi(), and cvGenericFilter::setupConfigWidget().
Referenced by cvGlyphFilter().
dataChanged()
void cvGlyphFilter::dataChanged () override protected virtual
Reimplemented from cvGenericFilter.
Definition at line 166 of file cvGlyphFilter.cpp.
References apply().
getOutput()
ccHObject * cvGlyphFilter::getOutput () override virtual
Reimplemented from cvGenericFilter.
Definition at line 121 of file cvGlyphFilter.cpp.
initFilter()
void cvGlyphFilter::initFilter () override protected virtual
Reimplemented from cvGenericFilter.
Definition at line 158 of file cvGlyphFilter.cpp.
References cvGenericFilter::initFilter().
modelReady()
void cvGlyphFilter::modelReady () override protected virtual
Reimplemented from cvGenericFilter.
Definition at line 146 of file cvGlyphFilter.cpp.
References apply(), and cvGenericFilter::modelReady().
showInteractor()
void cvGlyphFilter::showInteractor (bool state) override virtual
Reimplemented from cvGenericFilter.
Definition at line 130 of file cvGlyphFilter.cpp.
References cvGenericFilter::m_filterActor.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/cvGlyphFilter.h
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/cvGlyphFilter.cpp