ACloudViewer: cloudViewer::LocalModel Class Reference
cloudViewer::LocalModel Class Reference abstract
Local modelization (generic interface)
#include <LocalModel.h>
Public Member Functions
virtual ~LocalModel ()=default
Destructor.
virtual CV_LOCAL_MODEL_TYPES getType () const =0
Returns the model type.
const CCVector3 & getCenter () const
Returns the model center.
PointCoordinateType getSquareSize () const
Returns the model max radius (squared)
virtual ScalarType computeDistanceFromModelToPoint (const CCVector3 *P, CCVector3 *nearestPoint=nullptr) const =0
Compute the (unsigned) distance between a 3D point and this model.
Static Public Member Functions
static LocalModel * New (CV_LOCAL_MODEL_TYPES type, Neighbourhood &subset, const CCVector3 &center, PointCoordinateType squaredRadius)
Factory.
Protected Member Functions
LocalModel (const CCVector3 &center, PointCoordinateType squaredRadius)
Constructor.
Protected Attributes
CCVector3 m_modelCenter
Center.
PointCoordinateType m_squaredRadius
Max radius (squared)
Detailed Description
Local modelization (generic interface)
Local surface approximation of a point cloud
Definition at line 17 of file LocalModel.h.
Constructor & Destructor Documentation
~LocalModel()
virtual cloudViewer::LocalModel::~LocalModel () virtual default
Destructor.
LocalModel()
LocalModel::LocalModel (const CCVector3 & center, PointCoordinateType squaredRadius) protected
Constructor.
Parameters
center model "center"
squaredRadius model max "radius" (squared)
Definition at line 161 of file LocalModel.cpp.
Member Function Documentation
computeDistanceFromModelToPoint()
virtual ScalarType cloudViewer::LocalModel::computeDistanceFromModelToPoint (const CCVector3 * P, CCVector3 * nearestPoint = nullptr) const pure virtual
Compute the (unsigned) distance between a 3D point and this model.
Parameters
[in] P the query point
[out] nearestPoint returns the nearest point (optional)
Returns
the (unsigned) distance (or NAN_VALUE if the computation failed)
Implemented in DelaunayLocalModel, LSLocalModel, and QuadricLocalModel.
Referenced by cloudViewer::DistanceComputationTools::computeCellHausdorffDistanceWithLocalModel(), and define_LocalModel().
getCenter()
const CCVector3& cloudViewer::LocalModel::getCenter () const inline
Returns the model center.
Definition at line 37 of file LocalModel.h.
References m_modelCenter.
Referenced by define_LocalModel().
getSquareSize()
PointCoordinateType cloudViewer::LocalModel::getSquareSize () const inline
Returns the model max radius (squared)
Definition at line 40 of file LocalModel.h.
References m_squaredRadius.
Referenced by define_LocalModel().
getType()
virtual CV_LOCAL_MODEL_TYPES cloudViewer::LocalModel::getType () const pure virtual
Returns the model type.
Implemented in QuadricLocalModel, DelaunayLocalModel, and LSLocalModel.
Referenced by define_LocalModel().
New()
LocalModel * LocalModel::New (CV_LOCAL_MODEL_TYPES type, Neighbourhood & subset, const CCVector3 & center, PointCoordinateType squaredRadius) static
Factory.
Parameters
type the model type
subset (small) set of points from which to compute the local model
center model "center"
squaredRadius model max radius (squared)
Definition at line 165 of file LocalModel.cpp.
References cloudViewer::Neighbourhood::DUPLICATE_VERTICES, cloudViewer::Neighbourhood::getGravityCenter(), cloudViewer::Neighbourhood::getLSPlane(), cloudViewer::Neighbourhood::getQuadric(), cloudViewer::Neighbourhood::IGNORE_MAX_EDGE_LENGTH, LS, NO_MODEL, QUADRIC, TRI, cloudViewer::Neighbourhood::triangulateOnPlane(), type, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by cloudViewer::DistanceComputationTools::computeCellHausdorffDistanceWithLocalModel().
Member Data Documentation
m_modelCenter
CCVector3 cloudViewer::LocalModel::m_modelCenter protected
Center.
Definition at line 59 of file LocalModel.h.
Referenced by getCenter().
m_squaredRadius
PointCoordinateType cloudViewer::LocalModel::m_squaredRadius protected
Max radius (squared)
Definition at line 62 of file LocalModel.h.
Referenced by getSquareSize().
The documentation for this class was generated from the following files:
/root/ACloudViewer/core/include/LocalModel.h
/root/ACloudViewer/core/src/LocalModel.cpp