ACloudViewer: ProjectView Class Reference
ProjectView Class Reference final
#include <ProjectView.h>
Public Member Functions
ProjectView (QWidget *parent=nullptr)
void setRootPath (const QString &path)
QString relativePathAt (const QModelIndex &index) const
QString absolutePathAt (const QModelIndex &index) const
Detailed Description
Definition at line 17 of file ProjectView.h.
Constructor & Destructor Documentation
ProjectView()
ProjectView::ProjectView (QWidget * parent = nullptr) inline explicit
Definition at line 24 of file ProjectView.h.
References ProjectViewContextMenu, ProjectViewContextMenu::requested(), and size.
Member Function Documentation
absolutePathAt()
QString ProjectView::absolutePathAt (const QModelIndex & index) const inline
Definition at line 53 of file ProjectView.h.
References relativePathAt().
Referenced by ProjectViewContextMenu::requested().
relativePathAt()
QString ProjectView::relativePathAt (const QModelIndex & index) const inline
Definition at line 48 of file ProjectView.h.
Referenced by absolutePathAt().
setRootPath()
void ProjectView::setRootPath (const QString & path) inline
Definition at line 42 of file ProjectView.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/CodeEditor/ProjectView.h