ACloudViewer: cloudViewer::visualization::gui::PySceneWidget Class Reference
cloudViewer::visualization::gui::PySceneWidget Class Reference
Public Member Functions
void SetOnMouse (std::function< int(const MouseEvent &)> f)
void SetOnKey (std::function< int(const KeyEvent &)> f)
Widget::EventResult Mouse (const MouseEvent &e) override
Widget::EventResult Key (const KeyEvent &e) override
Public Member Functions inherited from cloudViewer::visualization::gui::SceneWidget
SceneWidget ()
~SceneWidget () override
void SetFrame (const Rect &f) override
void SetViewControls (Controls mode)
void SetupCamera (float verticalFoV, const ccBBox &scene_bounds, const Eigen::Vector3f &center_of_rotation)
void SetupCamera (const camera::PinholeCameraIntrinsic &intrinsic, const Eigen::Matrix4d &extrinsic, const ccBBox &scene_bounds)
void SetupCamera (const Eigen::Matrix3d &intrinsic, const Eigen::Matrix4d &extrinsic, int intrinsic_width_px, int intrinsic_height_px, const ccBBox &scene_bounds)
void LookAt (const Eigen::Vector3f &center, const Eigen::Vector3f &eye, const Eigen::Vector3f &up)
void SetOnCameraChanged (std::function< void(visualization::rendering::Camera *)> on_cam_changed)
Eigen::Vector3f GetCenterOfRotation () const
void SetCenterOfRotation (const Eigen::Vector3f &center)
void SetOnSunDirectionChanged (std::function< void(const Eigen::Vector3f &)> on_dir_changed)
void SetScene (std::shared_ptr< rendering::CloudViewerScene > scene)
std::shared_ptr< rendering::CloudViewerScene > GetScene () const
rendering::View * GetRenderView () const
void EnableSceneCaching (bool enable)
void ForceRedraw ()
void SetRenderQuality (Quality level)
Quality GetRenderQuality () const
void GoToCameraPreset (CameraPreset preset)
void SetSunInteractorEnabled (bool enable)
void SetPickableGeometry (const std::vector< PickableGeometry > &geometry)
void SetPickablePointSize (int px)
void SetOnPointsPicked (std::function< void(const std::map< std::string, std::vector< std::pair< size_t, Eigen::Vector3d >>> &, int)> on_picked)
void SetOnStartedPolygonPicking (std::function< void()> on_poly_pick)
void DoPolygonPick (PolygonPickAction action)
std::shared_ptr< Label3D > AddLabel (const Eigen::Vector3f &pos, const char *text)
void RemoveLabel (std::shared_ptr< Label3D > label)
void ClearLabels ()
Widget::DrawResult Draw (const DrawContext &context) override
Widget::DrawResult Tick (const TickEvent &e) override
Public Member Functions inherited from cloudViewer::visualization::gui::Widget
Widget ()
Widget (const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Widget ()
virtual void AddChild (std::shared_ptr< Widget > child)
virtual const std::vector< std::shared_ptr< Widget > > GetChildren () const
virtual const Rect & GetFrame () const
Returns the frame size in pixels.
virtual const Color & GetBackgroundColor () const
virtual bool IsDefaultBackgroundColor () const
virtual void SetBackgroundColor (const Color &color)
virtual bool IsVisible () const
virtual void SetVisible (bool vis)
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
virtual void SetTooltip (const char *text)
virtual const char * GetTooltip () const
virtual Size CalcPreferredSize (const LayoutContext &context, const Constraints &constraints) const
virtual Size CalcMinimumSize (const LayoutContext &context) const
virtual void Layout (const LayoutContext &context)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::gui::SceneWidget
enum Controls {
ROTATE_CAMERA , ROTATE_CAMERA_SPHERE , FLY , ROTATE_SUN ,
ROTATE_IBL , ROTATE_MODEL , PICK_POINTS
}
enum class Quality { FAST , BEST }
enum class CameraPreset { PLUS_X , PLUS_Y , PLUS_Z }
enum class PolygonPickAction { CANCEL = 0 , SELECT }
Public Types inherited from cloudViewer::visualization::gui::Widget
enum class DrawResult { NONE , REDRAW , RELAYOUT }
enum class EventResult { IGNORED , CONSUMED , DISCARD }
Static Public Attributes inherited from cloudViewer::visualization::gui::Widget
static constexpr int DIM_GROW = 10000
Protected Member Functions inherited from cloudViewer::visualization::gui::Widget
void DrawImGuiPushEnabledState ()
void DrawImGuiPopEnabledState ()
void DrawImGuiTooltip ()
Detailed Description
Definition at line 255 of file gui.cpp.
Member Function Documentation
Key()
Widget::EventResult cloudViewer::visualization::gui::PySceneWidget::Key (const KeyEvent & e) inline override virtual
Widgets that use Dear ImGUI should not need to override this, as Dear ImGUI will take care of all the key handling during the Draw().
Reimplemented from cloudViewer::visualization::gui::SceneWidget.
Definition at line 283 of file gui.cpp.
References cloudViewer::visualization::gui::Widget::CONSUMED, cloudViewer::visualization::gui::CONSUMED, cloudViewer::visualization::gui::HANDLED, cloudViewer::visualization::gui::Widget::IGNORED, cloudViewer::visualization::gui::IGNORED, cloudViewer::visualization::gui::SceneWidget::Key(), and result.
Referenced by cloudViewer::visualization::gui::pybind_gui_classes().
Mouse()
Widget::EventResult cloudViewer::visualization::gui::PySceneWidget::Mouse (const MouseEvent & e) inline override virtual
Widgets that use Dear ImGUI should not need to override this, as Dear ImGUI will take care of all the mouse handling during the Draw().
Reimplemented from cloudViewer::visualization::gui::SceneWidget.
Definition at line 262 of file gui.cpp.
References cloudViewer::visualization::gui::Widget::CONSUMED, cloudViewer::visualization::gui::CONSUMED, cloudViewer::visualization::gui::HANDLED, cloudViewer::visualization::gui::Widget::IGNORED, cloudViewer::visualization::gui::IGNORED, cloudViewer::visualization::gui::SceneWidget::Mouse(), and result.
Referenced by cloudViewer::visualization::gui::pybind_gui_classes().
SetOnKey()
void cloudViewer::visualization::gui::PySceneWidget::SetOnKey (std::function< int(const KeyEvent &)> f) inline
Definition at line 260 of file gui.cpp.
Referenced by cloudViewer::visualization::gui::pybind_gui_classes().
SetOnMouse()
void cloudViewer::visualization::gui::PySceneWidget::SetOnMouse (std::function< int(const MouseEvent &)> f) inline
Definition at line 259 of file gui.cpp.
Referenced by cloudViewer::visualization::gui::pybind_gui_classes().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Python/pybind/visualization/gui/gui.cpp