ACloudViewer: cloudViewer::PointCloudTpl< T > Class Template Reference
cloudViewer::PointCloudTpl< T > Class Template Reference
#include <PointCloudTpl.h>
Public Member Functions
PointCloudTpl ()
Default constructor.
virtual ~PointCloudTpl ()
Default destructor.
unsigned size () const override
void forEach (GenericCloud::genericPointAction action) override
void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax) override
void placeIteratorAtBeginning () override
const CCVector3 * getNextPoint () override
bool enableScalarField () override
bool isScalarFieldEnabled () const override
void setPointScalarValue (unsigned pointIndex, ScalarType value) override
ScalarType getPointScalarValue (unsigned pointIndex) const override
const CCVector3 * getPoint (unsigned index) const override
CCVector3 * getPointPtr (size_t index)
std::vector< CCVector3 > & getPoints ()
const std::vector< CCVector3 > & getPoints () const
void getPoint (unsigned index, CCVector3 &P) const override
void getPoint (unsigned index, double P[3]) const override
const CCVector3 * getPointPersistentPtr (unsigned index) override
const CCVector3 * getPointPersistentPtr (unsigned index) const
virtual bool resize (unsigned newCount)
Resizes the point database.
virtual bool reserve (unsigned newCapacity)
Reserves memory for the point database.
void reset ()
Clears the cloud database.
void addPoint (const CCVector3 &P)
Adds a 3D point to the database.
void setPoint (size_t index, const CCVector3 &P)
void setEigenPoint (size_t index, const Eigen::Vector3d &point)
void addEigenPoint (const Eigen::Vector3d &point)
void addPoint (double x, double y, double z)
void addPoint (double xyz[3])
void addPoints (const std::vector< CCVector3 > &points)
void addPoints (const std::vector< Eigen::Vector3d > &points)
Eigen::Vector3d getEigenPoint (size_t index) const
std::vector< Eigen::Vector3d > getEigenPoints () const
void setEigenPoints (const std::vector< Eigen::Vector3d > &points)
virtual void invalidateBoundingBox ()
Invalidates bounding box.
unsigned getNumberOfScalarFields () const
Returns the number of associated (and active) scalar fields.
ScalarField * getScalarField (int index) const
Returns a pointer to a specific scalar field.
const char * getScalarFieldName (int index) const
Returns the name of a specific scalar field.
int getScalarFieldIndexByName (const char *name) const
Returns the index of a scalar field represented by its name.
ScalarField * getCurrentInScalarField () const
Returns the scalar field currently associated to the cloud input.
ScalarField * getCurrentOutScalarField () const
Returns the scalar field currently associated to the cloud output.
void setCurrentInScalarField (int index)
Sets the INPUT scalar field.
int getCurrentInScalarFieldIndex ()
Returns current INPUT scalar field index (or -1 if none)
void setCurrentOutScalarField (int index)
Sets the OUTPUT scalar field.
int getCurrentOutScalarFieldIndex ()
Returns current OUTPUT scalar field index (or -1 if none)
void setCurrentScalarField (int index)
Sets both the INPUT & OUTPUT scalar field.
virtual int addScalarField (const char *uniqueName)
Creates a new scalar field and registers it.
bool renameScalarField (int index, const char *newName)
Renames a specific scalar field.
virtual void deleteScalarField (int index)
Deletes a specific scalar field.
virtual void deleteAllScalarFields ()
Deletes all scalar fields associated to this cloud.
unsigned capacity () const
Returns cloud capacity (i.e. reserved size)
Protected Member Functions
virtual void swapPoints (unsigned firstIndex, unsigned secondIndex)
Swaps two points (and their associated scalar values!)
CCVector3 * point (unsigned index)
Returns non const access to a given point.
const CCVector3 * point (unsigned index) const
Returns const access to a given point.
Protected Attributes
std::vector< CCVector3 > m_points
3D Points database
BoundingBox m_bbox
Bounding-box.
unsigned m_currentPointIndex
'Iterator' on the points db
std::vector< ScalarField * > m_scalarFields
Associated scalar fields.
int m_currentInScalarFieldIndex
Index of current scalar field used for input.
int m_currentOutScalarFieldIndex
Index of current scalar field used for output.
Detailed Description
template<class T>
class cloudViewer::PointCloudTpl< T >
A storage-efficient point cloud structure that can also handle an unlimited number of scalar fields
Definition at line 23 of file PointCloudTpl.h.
Constructor & Destructor Documentation
PointCloudTpl()
template<class T > cloudViewer::PointCloudTpl< T >::PointCloudTpl () inline
Default constructor.
Definition at line 29 of file PointCloudTpl.h.
~PointCloudTpl()
template<class T > virtual cloudViewer::PointCloudTpl< T >::~PointCloudTpl () inline virtual
Default destructor.
Definition at line 36 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::deleteAllScalarFields().
Member Function Documentation
addEigenPoint()
template<class T > void cloudViewer::PointCloudTpl< T >::addEigenPoint (const Eigen::Vector3d & point) inline
Definition at line 290 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::addPoint().
Referenced by cloudViewer::pipelines::integration::ScalableTSDFVolume::ExtractTriangleMesh(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractTriangleMesh(), cloudViewer::io::ReadModelUsingAssimp(), cloudViewer::io::ReadPointCloudFromXYZ(), cloudViewer::io::ReadPointCloudFromXYZN(), cloudViewer::io::ReadPointCloudFromXYZRGB(), cloudViewer::io::ReadPointCloudInMemoryFromXYZ(), cloudViewer::io::ReadTriangleMeshFromGLTF(), and cloudViewer::io::ReadTriangleMeshFromOBJ().
addPoint() [1/3]
template<class T > void cloudViewer::PointCloudTpl< T >::addPoint (const CCVector3 & P) inline
Adds a 3D point to the database.
To assure the best efficiency, the database memory must have already been reserved (with PointCloud::reserve). Otherwise nothing happens.
Parameters
P a 3D point
Definition at line 246 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_bbox, cloudViewer::PointCloudTpl< T >::m_points, cloudViewer::BoundingBoxTpl< T >::setValidity(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by cloudViewer::PointCloudTpl< T >::addEigenPoint(), qCanupo2DViewDialog::addOrSelectPoint(), cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::PointCloudTpl< T >::addPoints(), MeshWrapper< Real >::addVertex(), cloudViewer::visualization::Visualizer::CaptureDepthPointCloud(), ccTopologyRelation::constructGraphic(), contourPoly(), contourPoly2(), DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertMapToCloud(), DistanceMapGenerationTool::ConvertProfileToMesh(), ccCompass::estimateP21(), ccCompass::estimateStructureNormals(), GrainsAsEllipsoids::exportResultsAsCloud(), FromFbxMesh(), GetConeProfile(), getDensity(), getMortarMaps(), STEPFilter::importStepFile(), InitializeOutputCloud(), ProfileLoader::Load(), LoadCloud(), CSVMatrixFilter::loadFile(), SalomeHydroFilter::loadFile(), SinusxFilter::loadFile(), SoiFilter::loadFile(), LASFWFFilter::loadFile(), LASFilter::loadFile(), RDBFilter::loadFile(), DistanceMapGenerationDlg::loadOverlaySymbols(), LoadScan(), masc::ContextBasedFeature::prepare(), cloudViewer::visualization::MessageProcessor::ProcessMessage(), qCanupo2DViewDialog::resetBoundary(), rotY(), DistanceMapGenerationDlg::toggleOverlayGrid(), Cloth::toMesh(), and qCanupoTools::TrainClassifier().
addPoint() [2/3]
template<class T > void cloudViewer::PointCloudTpl< T >::addPoint (double x, double y, double z) inline
Definition at line 292 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::addPoint().
addPoint() [3/3]
template<class T > void cloudViewer::PointCloudTpl< T >::addPoint (double xyz[3]) inline
Definition at line 298 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::addPoint().
Referenced by cloudViewer::PointCloudTpl< T >::addPoint().
addPoints() [1/2]
template<class T > void cloudViewer::PointCloudTpl< T >::addPoints (const std::vector< CCVector3 > & points) inline
Definition at line 300 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::addPoint(), and points.
Referenced by cloudViewer::PointCloudTpl< T >::addPoints(), and cloudViewer::t::geometry::PointCloud::ToLegacy().
addPoints() [2/2]
template<class T > void cloudViewer::PointCloudTpl< T >::addPoints (const std::vector< Eigen::Vector3d > & points) inline
Definition at line 306 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::addPoints(), Vector3Tpl< PointCoordinateType >::fromArrayContainer(), cloudViewer::PointCloudTpl< T >::m_points, points, and cloudViewer::PointCloudTpl< T >::setEigenPoints().
addScalarField()
template<class T > virtual int cloudViewer::PointCloudTpl< T >::addScalarField (const char * uniqueName) inline virtual
Creates a new scalar field and registers it.
Warnings:
the name must be unique (the method will fail if a SF with the same name already exists)
this method DOES resize the scalar field to match the current cloud size
Parameters
uniqueName scalar field name (must be unique)
Returns
index of this new scalar field (or -1 if an error occurred)
Reimplemented in ccPointCloud.
Definition at line 448 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::PointCloudTpl< T >::m_scalarFields, CCShareable::release(), cloudViewer::ScalarField::resizeSafe(), and cloudViewer::PointCloudTpl< T >::size().
Referenced by cloudViewer::PointCloudTpl< T >::enableScalarField().
capacity()
template<class T > unsigned cloudViewer::PointCloudTpl< T >::capacity () const inline
Returns cloud capacity (i.e. reserved size)
Definition at line 540 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_points.
Referenced by MeshWrapper< Real >::checkVertexCapacity(), STEPFilter::importStepFile(), LasWaveformLoader::LasWaveformLoader(), SalomeHydroFilter::loadFile(), SinusxFilter::loadFile(), LASFilter::loadFile(), and DistanceMapGenerationDlg::loadOverlaySymbols().
deleteAllScalarFields()
template<class T > virtual void cloudViewer::PointCloudTpl< T >::deleteAllScalarFields () inline virtual
Deletes all scalar fields associated to this cloud.
Reimplemented in ccPointCloud.
Definition at line 530 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_currentInScalarFieldIndex, cloudViewer::PointCloudTpl< T >::m_currentOutScalarFieldIndex, and cloudViewer::PointCloudTpl< T >::m_scalarFields.
Referenced by cloudViewer::PointCloudTpl< T >::reset(), and cloudViewer::PointCloudTpl< T >::~PointCloudTpl().
deleteScalarField()
template<class T > virtual void cloudViewer::PointCloudTpl< T >::deleteScalarField (int index) inline virtual
Deletes a specific scalar field.
WARNING: this operation may modify the scalar fields order (especially if the deleted SF is not the last one). However current IN & OUT scalar fields will stay up-to-date (while their index may change).
Parameters
index index of scalar field to be deleted
Reimplemented in ccPointCloud.
Definition at line 499 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_currentInScalarFieldIndex, cloudViewer::PointCloudTpl< T >::m_currentOutScalarFieldIndex, cloudViewer::PointCloudTpl< T >::m_scalarFields, and std::swap().
enableScalarField()
template<class T > bool cloudViewer::PointCloudTpl< T >::enableScalarField () inline override
Definition at line 77 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::addScalarField(), cloudViewer::PointCloudTpl< T >::getCurrentInScalarField(), cloudViewer::PointCloudTpl< T >::getCurrentOutScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::PointCloudTpl< T >::m_currentInScalarFieldIndex, cloudViewer::PointCloudTpl< T >::m_currentOutScalarFieldIndex, cloudViewer::PointCloudTpl< T >::m_points, and cloudViewer::ScalarField::resizeSafe().
Referenced by FastMarchingForFacetExtraction::ExtractPlanarFacets(), and ccKdTreeForFacetExtraction::FuseCells().
forEach()
template<class T > void cloudViewer::PointCloudTpl< T >::forEach (GenericCloud::genericPointAction action) inline override
Definition at line 42 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::getCurrentOutScalarField(), cloudViewer::PointCloudTpl< T >::m_points, and cloudViewer::PointCloudTpl< T >::size().
getBoundingBox()
template<class T > void cloudViewer::PointCloudTpl< T >::getBoundingBox (CCVector3 & bbMin, CCVector3 & bbMax) inline override
Definition at line 57 of file PointCloudTpl.h.
References cloudViewer::BoundingBoxTpl< T >::add(), cloudViewer::BoundingBoxTpl< T >::clear(), cloudViewer::BoundingBoxTpl< T >::isValid(), cloudViewer::PointCloudTpl< T >::m_bbox, cloudViewer::PointCloudTpl< T >::m_points, cloudViewer::BoundingBoxTpl< T >::maxCorner(), and cloudViewer::BoundingBoxTpl< T >::minCorner().
Referenced by qRansacSD::doAction(), GrainsAsEllipsoids::fitEllipsoidToGrain(), getDensity(), getMortarMaps(), and ccMeasurementRecorder::setPlane().
getCurrentInScalarField()
template<class T > ScalarField* cloudViewer::PointCloudTpl< T >::getCurrentInScalarField () const inline
Returns the scalar field currently associated to the cloud input.
See PointCloud::setPointScalarValue.
Returns
a pointer to the currently defined INPUT scalar field (or 0 if none)
Definition at line 391 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::getScalarField(), and cloudViewer::PointCloudTpl< T >::m_currentInScalarFieldIndex.
Referenced by cloudViewer::PointCloudTpl< T >::enableScalarField(), and cloudViewer::PointCloudTpl< T >::isScalarFieldEnabled().
getCurrentInScalarFieldIndex()
template<class T > int cloudViewer::PointCloudTpl< T >::getCurrentInScalarFieldIndex () inline
Returns current INPUT scalar field index (or -1 if none)
Definition at line 413 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_currentInScalarFieldIndex.
getCurrentOutScalarField()
template<class T > ScalarField* cloudViewer::PointCloudTpl< T >::getCurrentOutScalarField () const inline
Returns the scalar field currently associated to the cloud output.
See PointCloud::getPointScalarValue.
Returns
a pointer to the currently defined OUTPUT scalar field (or 0 if none)
Definition at line 400 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::getScalarField(), and cloudViewer::PointCloudTpl< T >::m_currentOutScalarFieldIndex.
Referenced by cloudViewer::PointCloudTpl< T >::enableScalarField(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), and cloudViewer::PointCloudTpl< T >::forEach().
getCurrentOutScalarFieldIndex()
template<class T > int cloudViewer::PointCloudTpl< T >::getCurrentOutScalarFieldIndex () inline
Returns current OUTPUT scalar field index (or -1 if none)
Definition at line 426 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_currentOutScalarFieldIndex.
getEigenPoint()
template<class T > Eigen::Vector3d cloudViewer::PointCloudTpl< T >::getEigenPoint (size_t index) const inline
Definition at line 320 of file PointCloudTpl.h.
References Vector3Tpl< double >::fromArray(), and cloudViewer::PointCloudTpl< T >::point().
Referenced by cloudViewer::pipelines::registration::AdvancedMatching(), cloudViewer::pipelines::registration::CorrespondenceCheckerBasedOnEdgeLength::Check(), cloudViewer::pipelines::registration::CorrespondenceCheckerBasedOnDistance::Check(), cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::ComputeRMSE(), cloudViewer::pipelines::registration::TransformationEstimationForGeneralizedICP::ComputeRMSE(), cloudViewer::pipelines::registration::TransformationEstimationPointToPoint::ComputeRMSE(), cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::ComputeRMSE(), cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::ComputeTransformation(), cloudViewer::pipelines::registration::TransformationEstimationForGeneralizedICP::ComputeTransformation(), cloudViewer::pipelines::registration::TransformationEstimationPointToPoint::ComputeTransformation(), cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::ComputeTransformation(), cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ConstructBuffers(), cloudViewer::pipelines::registration::EvaluateRANSACBasedOnCorrespondence(), cloudViewer::pipelines::registration::GetInformationMatrixFromPointClouds(), cloudViewer::pipelines::registration::GetRegistrationResultAndCorrespondences(), cloudViewer::pipelines::registration::OptimizePairwiseRegistration(), cloudViewer::io::WritePointCloudInMemoryToXYZ(), cloudViewer::io::WritePointCloudToPLY(), cloudViewer::io::WritePointCloudToPTS(), cloudViewer::io::WritePointCloudToXYZ(), cloudViewer::io::WritePointCloudToXYZN(), and cloudViewer::io::WritePointCloudToXYZRGB().
getEigenPoints()
template<class T > std::vector<Eigen::Vector3d> cloudViewer::PointCloudTpl< T >::getEigenPoints () const inline
Definition at line 324 of file PointCloudTpl.h.
References Vector3Tpl< PointCoordinateType >::fromArrayContainer(), and cloudViewer::PointCloudTpl< T >::m_points.
Referenced by cloudViewer::t::geometry::PointCloud::FromLegacy().
getNextPoint()
template<class T > const CCVector3* cloudViewer::PointCloudTpl< T >::getNextPoint () inline override
Definition at line 71 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_currentPointIndex, and cloudViewer::PointCloudTpl< T >::m_points.
getNumberOfScalarFields()
template<class T > unsigned cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields () const inline
Returns the number of associated (and active) scalar fields.
Returns
the number of active scalar fields
Definition at line 345 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_scalarFields.
Referenced by ccCloudLayersHelper::apply(), CCCloudToDraco(), masc::PointFeature::checkValidity(), qCanupoProcess::Classify(), LasField::GetLASFields(), ccCloudLayersHelper::getScalarFields(), BasePclModule::getSelectedAvailableScalarFields(), ccCompass::importFoliations(), ccCompass::importLineations(), LasSaveDialog::LasSaveDialog(), PopulatePMFields(), PopulateSFCombo(), masc::PointFeature::retrieveField(), masc::Tools::RetrieveSF(), SimpleBinFilter::saveToFile(), LASFWFFilter::saveToFile(), and LASFilter::saveToFile().
getPoint() [1/3]
template<class T > const CCVector3* cloudViewer::PointCloudTpl< T >::getPoint (unsigned index) const inline override
Definition at line 143 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::point().
Referenced by ccTrace::calculateOptimumSearchRadius(), qCanupoProcess::Classify(), G3Point::G3PointAction::cleanLabels(), cloud2binary(), G3Point::G3PointAction::cluster(), qVoxFallProcess::Compute(), ComputeM3C2DistForPoint(), DistanceMapGenerationTool::ComputeMinAndMaxLatitude_rad(), DistanceMapGenerationTool::ComputeRadialDist(), DistanceMapGenerationTool::ComputeSurfacesAndVolumes(), contourPoly(), contourPoly2(), ConverFromTo(), DistanceMapGenerationTool::ConvertCloudToConical(), DistanceMapGenerationTool::ConvertCloudToCylindrical(), DistanceMapGenerationTool::CreateMap(), qCSF::doAction(), qHoughNormals::doAction(), ccTrace::drawMeOnly(), ccCompass::estimateP21(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), GrainsAsEllipsoids::fitEllipsoidToGrain(), get_subset(), getCommonPtsIdx(), getDensity(), getMortarMaps(), PointCloudWrapper< Real >::getPoint(), ccTrace::getSegmentCostGrad(), GrainsAsEllipsoids::GrainsAsEllipsoids(), qM3C2Tools::GuessBestParams(), ccCompass::importFoliations(), ccCompassImport::importFoliations(), ccCompass::importLineations(), ccCompassImport::importLineations(), ccTrace::insertWaypoint(), G3Point::G3PointAction::CloudAdaptor::kdtree_get_pt(), ccTrace::optimizeSegment(), optRotY(), DimScalarFieldWrapper::pointValue(), masc::ContextBasedFeature::prepare(), CommandCSF::process(), RefinePointClassif(), rotY(), LasSaver::saveNextPoint(), SimpleBinFilter::saveToFile(), LASFWFFilter::saveToFile(), G3Point::G3PointAction::segment(), toTranslatedVector(), and G3Point::G3PointAction::wolman().
getPoint() [2/3]
template<class T > void cloudViewer::PointCloudTpl< T >::getPoint (unsigned index, CCVector3 & P) const inline override
Definition at line 151 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::point().
getPoint() [3/3]
template<class T > void cloudViewer::PointCloudTpl< T >::getPoint (unsigned index, double P[3]) const inline override
Definition at line 154 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::point(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
getPointPersistentPtr() [1/2]
template<class T > const CCVector3* cloudViewer::PointCloudTpl< T >::getPointPersistentPtr (unsigned index) const inline
Definition at line 163 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::point().
getPointPersistentPtr() [2/2]
template<class T > const CCVector3* cloudViewer::PointCloudTpl< T >::getPointPersistentPtr (unsigned index) inline override
Definition at line 160 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::point().
Referenced by SaveScan().
getPointPtr()
template<class T > CCVector3* cloudViewer::PointCloudTpl< T >::getPointPtr (size_t index) inline
Definition at line 146 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::point().
Referenced by cloudViewer::io::ReadTriangleMeshFromSTL().
getPoints() [1/2]
template<class T > std::vector<CCVector3>& cloudViewer::PointCloudTpl< T >::getPoints () inline
Definition at line 149 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_points.
Referenced by cloudViewer::visualization::SelectionPolygonVolume::CropInPolygon(), cloudViewer::io::rpc::SetPointCloud(), and cloudViewer::io::rpc::SetTriangleMesh().
getPoints() [2/2]
template<class T > const std::vector<CCVector3>& cloudViewer::PointCloudTpl< T >::getPoints () const inline
Definition at line 150 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_points.
getPointScalarValue()
template<class T > ScalarType cloudViewer::PointCloudTpl< T >::getPointScalarValue (unsigned pointIndex) const inline override
Definition at line 134 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_currentOutScalarFieldIndex, and cloudViewer::PointCloudTpl< T >::m_scalarFields.
Referenced by ccTrace::buildCurvatureCost(), ccTrace::buildGradientCost(), masc::ContextBasedFeature::computeValue(), ccCompass::estimateStrain(), getMortarMaps(), ccTrace::getSegmentCostCurve(), and ccTrace::getSegmentCostGrad().
getScalarField()
template<class T > ScalarField* cloudViewer::PointCloudTpl< T >::getScalarField (int index) const inline
Returns a pointer to a specific scalar field.
Parameters
index a scalar field index
Returns
a pointer to a ScalarField structure, or 0 if the index is invalid.
Definition at line 354 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_scalarFields.
Referenced by ccCloudLayersHelper::apply(), ccTrace::buildCurvatureCost(), ccTrace::buildGradientCost(), CCCloudToDraco(), ccCloudLayersHelper::changeCode(), masc::Classifier::classify(), qCanupoProcess::Classify(), qM3C2Process::Compute(), DistanceMapGenerationTool::ComputeRadialDist(), qPCV::doAction(), qSRA::doProjectCloudDistsInGrid(), ccCompass::estimateStructureNormals(), masc::Classifier::evaluate(), GrainsAsEllipsoids::exportResultsAsCloud(), qFacets::extractFacets(), LasSaveDialog::fieldsToSave(), LasExtraScalarFieldCard::fillField(), TreeIso::Final_seg_pcd(), G3Point::G3PointAction::fit(), masc::Tools::GetClassificationSF(), cloudViewer::PointCloudTpl< T >::getCurrentInScalarField(), cloudViewer::PointCloudTpl< T >::getCurrentOutScalarField(), LasField::GetLASFields(), getMortarMaps(), ccTrace::getSegmentCostCurve(), ccTrace::getSegmentCostGrad(), GetSource(), LasSaveDialog::handleComboBoxChange(), ccCompass::importFoliations(), ccCompassImport::importFoliations(), ccCompass::importLineations(), ccCompassImport::importLineations(), TreeIso::Init_seg_pcd(), TreeIso::Intermediate_seg_pcd(), LasExtraScalarField::MatchExtraBytesToScalarFields(), ccCloudLayersHelper::mouseMove(), ccCloudLayersHelper::moveItem(), ccTrace::optimizePath(), masc::Feature::PrepareSF(), PCVCommand::Process(), cloudViewer::PointCloudTpl< T >::renameScalarField(), ccCloudLayersHelper::restoreState(), masc::PointFeature::retrieveField(), masc::Tools::RetrieveSF(), SaveScan(), ccCloudLayersHelper::saveState(), SimpleBinFilter::saveToFile(), LASFWFFilter::saveToFile(), LASFilter::saveToFile(), LasDetails::SelectBestVersion(), and G3Point::G3PointAction::wolman().
getScalarFieldIndexByName()
template<class T > int cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName (const char * name) const inline
Returns the index of a scalar field represented by its name.
Parameters
name a scalar field name
Returns
an index (-1 if the scalar field couldn't be found)
Definition at line 375 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_scalarFields, and name.
Referenced by cloudViewer::PointCloudTpl< T >::addScalarField(), masc::Feature::CheckSFExistence(), masc::PointFeature::checkValidity(), masc::Classifier::classify(), qCanupoProcess::Classify(), qVoxFallProcess::Compute(), DistanceMapGenerationTool::ComputeRadialDist(), ccMeasurementDevice::deleteScalarFieldFromCloud(), qPCV::doAction(), qSRA::doProjectCloudDistsInGrid(), cloudViewer::PointCloudTpl< T >::enableScalarField(), ccCompass::estimateStrain(), masc::Classifier::evaluate(), qFacets::extractFacets(), LasSaveDialog::fieldsToSave(), LasExtraScalarFieldCard::fillField(), TreeIso::Final_seg_pcd(), G3Point::G3PointAction::fit(), masc::Tools::GetClassificationSF(), G3Point::G3PointAction::GetG3PointAction(), getMortarMaps(), ccTrace::getSegmentCostCurve(), ccTrace::getSegmentCostGrad(), GetSource(), LasSaveDialog::handleComboBoxChange(), BasePclModule::hasSelectedScalarField(), ccCompass::importFoliations(), ccCompass::importLineations(), TreeIso::Init_seg_pcd(), TreeIso::Intermediate_seg_pcd(), ccTrace::isCurvaturePrecomputed(), ccTrace::isGradientPrecomputed(), LoadScan(), LasExtraScalarField::MatchExtraBytesToScalarFields(), ccTrace::optimizePath(), masc::ContextBasedFeature::prepare(), masc::Feature::PrepareSF(), PCVCommand::Process(), SFCollector::releaseSFs(), RemoveScalarField(), cloudViewer::PointCloudTpl< T >::renameScalarField(), masc::Tools::RetrieveSF(), SaveScan(), LASFWFFilter::saveToFile(), LasDetails::SelectBestVersion(), and G3Point::G3PointAction::wolman().
getScalarFieldName()
template<class T > const char* cloudViewer::PointCloudTpl< T >::getScalarFieldName (int index) const inline
Returns the name of a specific scalar field.
Parameters
index a scalar field index
Returns
a pointer to a string structure (null-terminated array of characters), or 0 if the index is invalid.
Definition at line 365 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_scalarFields.
Referenced by ccCloudLayersHelper::getScalarFields(), BasePclModule::getSelectedAvailableScalarFields(), ccCompass::importFoliations(), ccCompass::importLineations(), LasSaveDialog::LasSaveDialog(), PopulateSFCombo(), SaveScan(), and SimpleBinFilter::saveToFile().
invalidateBoundingBox()
template<class T > virtual void cloudViewer::PointCloudTpl< T >::invalidateBoundingBox () inline virtual
Invalidates bounding box.
Bounding box will be recomputed next time a request is made to 'getBoundingBox'.
Reimplemented in ccPointCloud.
Definition at line 338 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_bbox, and cloudViewer::BoundingBoxTpl< T >::setValidity().
Referenced by cloudViewer::PointCloudTpl< T >::reset().
isScalarFieldEnabled()
template<class T > bool cloudViewer::PointCloudTpl< T >::isScalarFieldEnabled () const inline override
Definition at line 110 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::getCurrentInScalarField(), and cloudViewer::PointCloudTpl< T >::m_points.
placeIteratorAtBeginning()
template<class T > void cloudViewer::PointCloudTpl< T >::placeIteratorAtBeginning () inline override
Definition at line 69 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_currentPointIndex.
Referenced by cloudViewer::PointCloudTpl< T >::reset().
point() [1/2]
template<class T > CCVector3* cloudViewer::PointCloudTpl< T >::point (unsigned index) inline protected
Returns non const access to a given point.
WARNING: index must be valid
Parameters
index point index
Returns
pointer on point stored data
Definition at line 564 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_points, and cloudViewer::PointCloudTpl< T >::size().
Referenced by cloudViewer::PointCloudTpl< T >::getEigenPoint(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::PointCloudTpl< T >::getPointPersistentPtr(), cloudViewer::PointCloudTpl< T >::getPointPtr(), and cloudViewer::PointCloudTpl< T >::setEigenPoint().
point() [2/2]
template<class T > const CCVector3* cloudViewer::PointCloudTpl< T >::point (unsigned index) const inline protected
Returns const access to a given point.
WARNING: index must be valid
Parameters
index point index
Returns
pointer on point stored data
Definition at line 574 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_points, and cloudViewer::PointCloudTpl< T >::size().
renameScalarField()
template<class T > bool cloudViewer::PointCloudTpl< T >::renameScalarField (int index, const char * newName) inline
Renames a specific scalar field.
Warning: name must not be already given to another SF!
Parameters
index scalar field index
newName new name
Returns
success
Definition at line 481 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), and cloudViewer::ScalarField::setName().
reserve()
template<class T > virtual bool cloudViewer::PointCloudTpl< T >::reserve (unsigned newCapacity) inline virtual
Reserves memory for the point database.
This method tries to reserve some memory to store points that will be inserted later (with PointCloud::addPoint). If the new number of points is smaller than the actual one, nothing happens.
Parameters
newNumberOfPoints the new number of points
Returns
true if the method succeeds, false otherwise
Reimplemented in ccSymbolCloud, and ccPointCloud.
Definition at line 213 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_points, and cloudViewer::PointCloudTpl< T >::m_scalarFields.
reset()
template<class T > void cloudViewer::PointCloudTpl< T >::reset () inline
Clears the cloud database.
Equivalent to resize(0).
Definition at line 233 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::deleteAllScalarFields(), cloudViewer::PointCloudTpl< T >::invalidateBoundingBox(), cloudViewer::PointCloudTpl< T >::m_points, and cloudViewer::PointCloudTpl< T >::placeIteratorAtBeginning().
resize()
template<class T > virtual bool cloudViewer::PointCloudTpl< T >::resize (unsigned newCount) inline virtual
Resizes the point database.
The cloud database is resized with the specified size. If the new size is smaller, the overflooding points will be deleted. If its greater, the database is filled with blank points (warning, the PointCloud::addPoint method will insert points after those ones).
Parameters
newNumberOfPoints the new number of points
Returns
true if the method succeeds, false otherwise
Reimplemented in ccSymbolCloud, ccPointCloud, and cloudViewer::PointCloud.
Definition at line 175 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_points, and cloudViewer::PointCloudTpl< T >::m_scalarFields.
setCurrentInScalarField()
template<class T > void cloudViewer::PointCloudTpl< T >::setCurrentInScalarField (int index) inline
Sets the INPUT scalar field.
This scalar field will be used by the PointCloud::setPointScalarValue method.
Parameters
index a scalar field index (or -1 if none)
Definition at line 408 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_currentInScalarFieldIndex.
Referenced by ccTrace::buildCurvatureCost(), ccTrace::buildGradientCost(), and cloudViewer::PointCloudTpl< T >::setCurrentScalarField().
setCurrentOutScalarField()
template<class T > void cloudViewer::PointCloudTpl< T >::setCurrentOutScalarField (int index) inline
Sets the OUTPUT scalar field.
This scalar field will be used by the PointCloud::getPointScalarValue method.
Parameters
index a scalar field index (or -1 if none)
Definition at line 421 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_currentOutScalarFieldIndex.
Referenced by ccTrace::buildGradientCost(), ccCompass::estimateStrain(), masc::ContextBasedFeature::prepare(), and cloudViewer::PointCloudTpl< T >::setCurrentScalarField().
setCurrentScalarField()
template<class T > void cloudViewer::PointCloudTpl< T >::setCurrentScalarField (int index) inline
Sets both the INPUT & OUTPUT scalar field.
This scalar field will be used by both PointCloud::getPointScalarValue and PointCloud::setPointScalarValue methods.
Parameters
index a scalar field index
Definition at line 435 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::setCurrentInScalarField(), and cloudViewer::PointCloudTpl< T >::setCurrentOutScalarField().
Referenced by ccTrace::buildCurvatureCost(), ccTrace::buildGradientCost(), qPCV::doAction(), ccCompass::estimateP21(), qFacets::extractFacets(), ccTrace::getSegmentCostCurve(), ccTrace::getSegmentCostGrad(), ccTrace::optimizePath(), and PCVCommand::Process().
setEigenPoint()
template<class T > void cloudViewer::PointCloudTpl< T >::setEigenPoint (size_t index, const Eigen::Vector3d & point) inline
Definition at line 272 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_points, cloudViewer::PointCloudTpl< T >::point(), and cloudViewer::PointCloudTpl< T >::size().
Referenced by cloudViewer::PointCloudTpl< T >::setEigenPoints().
setEigenPoints()
template<class T > void cloudViewer::PointCloudTpl< T >::setEigenPoints (const std::vector< Eigen::Vector3d > & points) inline
Definition at line 327 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_points, points, and cloudViewer::PointCloudTpl< T >::setEigenPoint().
Referenced by cloudViewer::PointCloudTpl< T >::addPoints(), and GrainsAsEllipsoids::updateMeshAndLineSet().
setPoint()
template<class T > void cloudViewer::PointCloudTpl< T >::setPoint (size_t index, const CCVector3 & P) inline
Definition at line 259 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_points, cloudViewer::PointCloudTpl< T >::size(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by cloudViewer::io::ReadPointCloudFromPTS().
setPointScalarValue()
template<class T > void cloudViewer::PointCloudTpl< T >::setPointScalarValue (unsigned pointIndex, ScalarType value) inline override
Definition at line 120 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_currentInScalarFieldIndex, and cloudViewer::PointCloudTpl< T >::m_scalarFields.
Referenced by ccTrace::bakePathToScalarField(), ccTrace::buildCurvatureCost(), ccTrace::buildGradientCost(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), and ccTrace::optimizeSegment().
size()
template<class T > unsigned cloudViewer::PointCloudTpl< T >::size () const inline override
Definition at line 38 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_points.
Referenced by qCanupo2DViewDialog::addOrSelectPoint(), cloudViewer::PointCloudTpl< T >::addScalarField(), ccTrace::bakePathToScalarField(), ccTrace::buildCurvatureCost(), ccTrace::buildGradientCost(), G3Point::G3PointAction::buildStacksFromG3PointLabelSF(), ccTrace::calculateOptimumSearchRadius(), ccCloudLayersHelper::ccCloudLayersHelper(), masc::ContextBasedFeature::checkValidity(), MeshWrapper< Real >::checkVertexCapacity(), masc::Classifier::classify(), qCanupoProcess::Classify(), cloud2binary(), qM3C2Process::Compute(), ComputeFeatures(), ComputeKmeansClustering(), DistanceMapGenerationTool::ComputeMinAndMaxLatitude_rad(), DistanceMapGenerationTool::ComputeRadialDist(), DistanceMapGenerationTool::ComputeSurfacesAndVolumes(), cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ConstructBuffers(), contourPoly(), ConverFromTo(), DistanceMapGenerationTool::ConvertCloudToConical(), DistanceMapGenerationTool::ConvertCloudToCylindrical(), DistanceMapGenerationTool::ConvertMapToCloud(), DistanceMapGenerationTool::CreateMap(), qCSF::doAction(), qHoughNormals::doAction(), qPoissonRecon::doAction(), qCanupoPlugin::doTrainAction(), ccCompass::estimateP21(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), masc::Classifier::evaluate(), GrainsAsEllipsoids::exportResultsAsCloud(), qFacets::extractFacets(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), cloudViewer::pipelines::integration::ScalableTSDFVolume::ExtractTriangleMesh(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractTriangleMesh(), cloudViewer::pipelines::registration::FastGlobalRegistrationBasedOnFeatureMatching(), TreeIso::Final_seg_pcd(), GrainsAsEllipsoids::fitEllipsoidToGrain(), cloudViewer::PointCloudTpl< T >::forEach(), G3Point::G3PointAction::getBorders(), PointCloudWrapper< Real >::getColor(), getCommonPtsIdx(), GetKeyCluster(), getMortarMaps(), PointCloudWrapper< Real >::getNormal(), PointCloudWrapper< Real >::getPoint(), cloudViewer::pipelines::registration::GetRegistrationResultAndCorrespondences(), qM3C2Tools::GuessBestParams(), LasWaveformSaver::handlePoint(), LasScalarFieldLoader::handleRGBValue(), ccCompass::importFoliations(), ccCompassImport::importFoliations(), ccCompass::importLineations(), ccCompassImport::importLineations(), STEPFilter::importStepFile(), StereogramWidget::init(), TreeIso::Init_seg_pcd(), TreeIso::Intermediate_seg_pcd(), G3Point::G3PointAction::CloudAdaptor::kdtree_get_point_count(), CSVMatrixFilter::loadFile(), SalomeHydroFilter::loadFile(), SinusxFilter::loadFile(), DRCFilter::loadFile(), LASFWFFilter::loadFile(), LASFilter::loadFile(), RDBFilter::loadFile(), DistanceMapGenerationDlg::loadOverlaySymbols(), LasWaveformLoader::loadWaveform(), G3Point::G3PointAction::merge(), ccCloudLayersHelper::mouseMove(), ccTrace::optimizeSegment(), optRotY(), cloudViewer::PointCloudTpl< T >::point(), masc::CorePoints::prepare(), masc::ContextBasedFeature::prepare(), masc::Feature::PrepareSF(), CommandCSF::process(), ccCloudLayersHelper::projectCloud(), masc::Tools::RandomSubset(), cloudViewer::io::ReadPointCloud(), cloudViewer::io::ReadTriangleMeshFromOBJ(), cloudViewer::pipelines::registration::RegistrationRANSACBasedOnFeatureMatching(), ccCloudLayersHelper::restoreState(), masc::PointFeature::retrieveField(), rotY(), LasSaver::saveNextPoint(), SaveScan(), ccCloudLayersHelper::saveState(), PcdFilter::saveToFile(), SimpleBinFilter::saveToFile(), LASFWFFilter::saveToFile(), G3Point::G3PointAction::segment(), cloudViewer::PointCloudTpl< T >::setEigenPoint(), cloudViewer::PointCloudTpl< T >::setPoint(), ccCloudLayersHelper::setVisible(), masc::CorePoints::size(), PointCloudWrapper< Real >::size(), NormDipAndDipDirFieldWrapper::size(), DimScalarFieldWrapper::size(), ColorScalarFieldWrapper::size(), toTranslatedVector(), masc::Classifier::train(), StereogramDialog::updateFacetsFilter(), cloudViewer::visualization::VisualizerWithVertexSelection::UpdateGeometry(), GrainsAsEllipsoids::updateMeshAndLineSet(), DistanceMapGenerationDlg::updateZoom(), G3Point::G3PointAction::wolman(), cloudViewer::io::WritePointCloud(), cloudViewer::io::WritePointCloudInMemoryToXYZ(), cloudViewer::io::WritePointCloudToPLY(), cloudViewer::io::WritePointCloudToPTS(), cloudViewer::io::WritePointCloudToXYZ(), cloudViewer::io::WritePointCloudToXYZN(), and cloudViewer::io::WritePointCloudToXYZRGB().
swapPoints()
template<class T > virtual void cloudViewer::PointCloudTpl< T >::swapPoints (unsigned firstIndex, unsigned secondIndex) inline protected virtual
Swaps two points (and their associated scalar values!)
Reimplemented in ccPointCloud.
Definition at line 546 of file PointCloudTpl.h.
References cloudViewer::PointCloudTpl< T >::m_points, cloudViewer::PointCloudTpl< T >::m_scalarFields, and std::swap().
Member Data Documentation
m_bbox
template<class T > BoundingBox cloudViewer::PointCloudTpl< T >::m_bbox protected
Bounding-box.
Definition at line 583 of file PointCloudTpl.h.
Referenced by cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::PointCloudTpl< T >::getBoundingBox(), and cloudViewer::PointCloudTpl< T >::invalidateBoundingBox().
m_currentInScalarFieldIndex
template<class T > int cloudViewer::PointCloudTpl< T >::m_currentInScalarFieldIndex protected
Index of current scalar field used for input.
Definition at line 592 of file PointCloudTpl.h.
Referenced by cloudViewer::PointCloudTpl< T >::deleteAllScalarFields(), cloudViewer::PointCloudTpl< T >::deleteScalarField(), cloudViewer::PointCloudTpl< T >::enableScalarField(), cloudViewer::PointCloudTpl< T >::getCurrentInScalarField(), cloudViewer::PointCloudTpl< T >::getCurrentInScalarFieldIndex(), cloudViewer::PointCloudTpl< T >::setCurrentInScalarField(), and cloudViewer::PointCloudTpl< T >::setPointScalarValue().
m_currentOutScalarFieldIndex
template<class T > int cloudViewer::PointCloudTpl< T >::m_currentOutScalarFieldIndex protected
Index of current scalar field used for output.
Definition at line 595 of file PointCloudTpl.h.
Referenced by cloudViewer::PointCloudTpl< T >::deleteAllScalarFields(), cloudViewer::PointCloudTpl< T >::deleteScalarField(), cloudViewer::PointCloudTpl< T >::enableScalarField(), cloudViewer::PointCloudTpl< T >::getCurrentOutScalarField(), cloudViewer::PointCloudTpl< T >::getCurrentOutScalarFieldIndex(), cloudViewer::PointCloudTpl< T >::getPointScalarValue(), and cloudViewer::PointCloudTpl< T >::setCurrentOutScalarField().
m_currentPointIndex
template<class T > unsigned cloudViewer::PointCloudTpl< T >::m_currentPointIndex protected
'Iterator' on the points db
Definition at line 586 of file PointCloudTpl.h.
Referenced by cloudViewer::PointCloudTpl< T >::getNextPoint(), and cloudViewer::PointCloudTpl< T >::placeIteratorAtBeginning().
m_points
template<class T > std::vector<CCVector3> cloudViewer::PointCloudTpl< T >::m_points protected
3D Points database
Definition at line 580 of file PointCloudTpl.h.
Referenced by cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::PointCloudTpl< T >::addPoints(), cloudViewer::PointCloudTpl< T >::capacity(), cloudViewer::PointCloudTpl< T >::enableScalarField(), cloudViewer::PointCloudTpl< T >::forEach(), cloudViewer::PointCloudTpl< T >::getBoundingBox(), cloudViewer::PointCloudTpl< T >::getEigenPoints(), cloudViewer::PointCloudTpl< T >::getNextPoint(), cloudViewer::PointCloudTpl< T >::getPoints(), cloudViewer::PointCloudTpl< T >::isScalarFieldEnabled(), cloudViewer::PointCloudTpl< T >::point(), cloudViewer::PointCloudTpl< T >::reserve(), cloudViewer::PointCloudTpl< T >::reset(), cloudViewer::PointCloudTpl< T >::resize(), cloudViewer::PointCloudTpl< T >::setEigenPoint(), cloudViewer::PointCloudTpl< T >::setEigenPoints(), cloudViewer::PointCloudTpl< T >::setPoint(), cloudViewer::PointCloudTpl< T >::size(), and cloudViewer::PointCloudTpl< T >::swapPoints().
m_scalarFields
template<class T > std::vector<ScalarField*> cloudViewer::PointCloudTpl< T >::m_scalarFields protected
Associated scalar fields.
Definition at line 589 of file PointCloudTpl.h.
Referenced by cloudViewer::PointCloudTpl< T >::addScalarField(), cloudViewer::PointCloudTpl< T >::deleteAllScalarFields(), cloudViewer::PointCloudTpl< T >::deleteScalarField(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudViewer::PointCloudTpl< T >::getPointScalarValue(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::PointCloudTpl< T >::getScalarFieldName(), cloudViewer::PointCloudTpl< T >::reserve(), cloudViewer::PointCloudTpl< T >::resize(), cloudViewer::PointCloudTpl< T >::setPointScalarValue(), and cloudViewer::PointCloudTpl< T >::swapPoints().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/PointCloudTpl.h