ACloudViewer: ecvUpdateDlg Class Reference
ecvUpdateDlg Class Reference
#include <ecvUpdateDlg.h>
Public Slots
void resetFields ()
void checkForUpdates ()
void updateChangelog (const QString &url)
void displayAppcast (const QString &url, const QByteArray &reply)
Public Member Functions
ecvUpdateDlg (QWidget *parent=nullptr)
~ecvUpdateDlg ()
Detailed Description
Definition at line 19 of file ecvUpdateDlg.h.
Constructor & Destructor Documentation
ecvUpdateDlg()
ecvUpdateDlg::ecvUpdateDlg (QWidget * parent = nullptr) explicit
Definition at line 23 of file ecvUpdateDlg.cpp.
References checkForUpdates(), displayAppcast(), QSimpleUpdater::getInstance(), resetFields(), and updateChangelog().
~ecvUpdateDlg()
ecvUpdateDlg::~ecvUpdateDlg ()
Definition at line 50 of file ecvUpdateDlg.cpp.
Member Function Documentation
checkForUpdates
void ecvUpdateDlg::checkForUpdates () slot
Definition at line 70 of file ecvUpdateDlg.cpp.
References QSimpleUpdater::checkForUpdates(), QSimpleUpdater::setDownloaderEnabled(), QSimpleUpdater::setMandatoryUpdate(), QSimpleUpdater::setModuleVersion(), QSimpleUpdater::setNotifyOnFinish(), QSimpleUpdater::setNotifyOnUpdate(), QSimpleUpdater::setUseCustomAppcast(), Settings::UPDATE_RUL, and version.
Referenced by ecvUpdateDlg().
displayAppcast
void ecvUpdateDlg::displayAppcast (const QString & url, const QByteArray & reply) slot
Definition at line 104 of file ecvUpdateDlg.cpp.
References Settings::UPDATE_RUL.
Referenced by ecvUpdateDlg().
resetFields
void ecvUpdateDlg::resetFields () slot
Definition at line 56 of file ecvUpdateDlg.cpp.
References Settings::APP_VERSION.
Referenced by ecvUpdateDlg().
updateChangelog
void ecvUpdateDlg::updateChangelog (const QString & url) slot
Definition at line 95 of file ecvUpdateDlg.cpp.
References QSimpleUpdater::getChangelog(), and Settings::UPDATE_RUL.
Referenced by ecvUpdateDlg().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvUpdateDlg.h
/root/ACloudViewer/app/ecvUpdateDlg.cpp