ACloudViewer: cloudViewer::pipelines::registration::TransformationEstimationForColoredICP Class Reference
cloudViewer::pipelines::registration::TransformationEstimationForColoredICP Class Reference
#include <ColoredICP.h>
Public Member Functions
~TransformationEstimationForColoredICP () override
TransformationEstimationType GetTransformationEstimationType () const override
TransformationEstimationForColoredICP (double lambda_geometric=0.968, std::shared_ptr< RobustKernel > kernel=std::make_shared< L2Loss >())
double ComputeRMSE (const ccPointCloud &source, const ccPointCloud &target, const CorrespondenceSet &corres) const override
Eigen::Matrix4d ComputeTransformation (const ccPointCloud &source, const ccPointCloud &target, const CorrespondenceSet &corres) const override
Public Member Functions inherited from cloudViewer::pipelines::registration::TransformationEstimation
TransformationEstimation ()
Default Constructor.
virtual ~TransformationEstimation ()
Public Attributes
double lambda_geometric_ = 0.968
std::shared_ptr< RobustKernel > kernel_ = std::make_shared<L2Loss>()
shared_ptr to an Abstract RobustKernel that could mutate at runtime.
Detailed Description
Definition at line 25 of file ColoredICP.h.
Constructor & Destructor Documentation
~TransformationEstimationForColoredICP()
cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::~TransformationEstimationForColoredICP () inline override
Definition at line 27 of file ColoredICP.h.
TransformationEstimationForColoredICP()
cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::TransformationEstimationForColoredICP (double lambda_geometric = 0.968, std::shared_ptr< RobustKernel > kernel = std::make_shared<L2Loss>()) inline explicit
Definition at line 33 of file ColoredICP.h.
References lambda_geometric_.
Member Function Documentation
ComputeRMSE()
double cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::ComputeRMSE (const ccPointCloud & source, const ccPointCloud & target, const CorrespondenceSet & corres) const override virtual
Compute RMSE between source and target points cloud given correspondences.
Parameters
source Source point cloud.
target Target point cloud.
corres Correspondence set between source and target point cloud.
Implements cloudViewer::pipelines::registration::TransformationEstimation.
Definition at line 209 of file ColoredICP.cpp.
References colors, dot(), ccPointCloud::getEigenNormal(), cloudViewer::PointCloudTpl< T >::getEigenPoint(), ccPointCloud::getPointColor(), lambda_geometric_, and ecvColor::RgbTpl< Type >::ToEigen().
ComputeTransformation()
Eigen::Matrix4d cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::ComputeTransformation (const ccPointCloud & source, const ccPointCloud & target, const CorrespondenceSet & corres) const override virtual
Compute transformation from source to target point cloud given correspondences.
Parameters
source Source point cloud.
target Target point cloud.
corres Correspondence set between source and target point cloud.
Implements cloudViewer::pipelines::registration::TransformationEstimation.
Definition at line 117 of file ColoredICP.cpp.
References colors, dot(), ccPointCloud::getEigenNormal(), cloudViewer::PointCloudTpl< T >::getEigenPoint(), ccPointCloud::getPointColor(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), kernel_, lambda_geometric_, LogError, cloudViewer::utility::SolveJacobianSystemAndObtainExtrinsicMatrix(), and ecvColor::RgbTpl< Type >::ToEigen().
GetTransformationEstimationType()
TransformationEstimationType cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::GetTransformationEstimationType () const inline override virtual
Implements cloudViewer::pipelines::registration::TransformationEstimation.
Definition at line 29 of file ColoredICP.h.
Member Data Documentation
kernel_
std::shared_ptr<RobustKernel> cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::kernel_ = std::make_shared<L2Loss>()
shared_ptr to an Abstract RobustKernel that could mutate at runtime.
Definition at line 54 of file ColoredICP.h.
Referenced by ComputeTransformation().
lambda_geometric_
double cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::lambda_geometric_ = 0.968
Definition at line 52 of file ColoredICP.h.
Referenced by ComputeRMSE(), ComputeTransformation(), and TransformationEstimationForColoredICP().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/pipelines/registration/ColoredICP.h
/root/ACloudViewer/libs/cloudViewer/pipelines/registration/ColoredICP.cpp