ACloudViewer: ccColorScaleEditorWidget Class Reference
ccColorScaleEditorWidget Class Reference
Color scale editor dialog.
#include <ecvColorScaleEditorWidget.h>
Signals
void stepSelected (int index)
Signal emitted when a slider is selected.
void stepModified (int index)
Signal emitted when a slider is modified.
Public Member Functions
ccColorScaleEditorWidget (QWidget *parent=nullptr, Qt::Orientation orientation=Qt::Horizontal)
Default constructor.
~ccColorScaleEditorWidget () override=default
Destructor.
int getStepCount () const
Returns the current number of color scale steps.
const ColorScaleElementSlider * getStep (int index)
Returns a given slider (pointer on)
void setStepColor (int index, QColor color)
Sets a given slider color.
void setStepRelativePosition (int index, double relativePos)
Sets a given slider relative position.
int getSelectedStepIndex () const
Returns currently selected step index.
void setSelectedStepIndex (int index, bool silent=false)
Sets currently selected step index.
void deleteStep (int index)
Deletes a given step.
void exportColorScale (ccColorScale::Shared &destScale) const
Exports the current color scale.
void importColorScale (ccColorScale::Shared scale)
Imports the current color scale.
void showLabels (bool state)
Sets whether to show the color elements labels or not.
void setLabelColor (QColor color)
Sets the labels color.
void setLabelPrecision (int precision)
Sets the labels precision.
void setSliders (SharedColorScaleElementSliders sliders) override
Sets associated sliders set.
Public Member Functions inherited from ColorScaleEditorBaseWidget
ColorScaleEditorBaseWidget (SharedColorScaleElementSliders sliders, Qt::Orientation orientation, int margin, QWidget *parent=nullptr)
Defautl constructor.
int length () const
Returns useful length.
Qt::Orientation getOrientation () const
Returns orientation.
int getMargin () const
Returns margin.
Protected Slots
void onPointClicked (double relativePos)
Slot called when a 'point' is clicked on the color bar.
void onSliderModified (int sliderIndex)
Slot called when a slider is moved or its color is changed.
void onSliderSelected (int sliderIndex)
Slot called when a slider is selected.
Protected Attributes
ColorBarWidget * m_colorBarWidget
Associated color bar.
SlidersWidget * m_slidersWidget
Associated sliders widget.
SliderLabelWidget * m_labelsWidget
Associated (sliders) labels widget.
Protected Attributes inherited from ColorScaleEditorBaseWidget
SharedColorScaleElementSliders m_sliders
Associated sliders.
Qt::Orientation m_orientation
Orientation.
int m_margin
Margin.
Detailed Description
Color scale editor dialog.
Definition at line 224 of file ecvColorScaleEditorWidget.h.
Constructor & Destructor Documentation
ccColorScaleEditorWidget()
ccColorScaleEditorWidget::ccColorScaleEditorWidget (QWidget * parent = nullptr, Qt::Orientation orientation = Qt::Horizontal)
Default constructor.
Definition at line 500 of file ecvColorScaleEditorWidget.cpp.
References SlidersWidget::addNewSlider(), ecvColor::blue(), DEFAULT_LABEL_HEIGHT, m_colorBarWidget, m_labelsWidget, ColorScaleEditorBaseWidget::m_orientation, ColorScaleEditorBaseWidget::m_sliders, m_slidersWidget, onPointClicked(), onSliderModified(), onSliderSelected(), and ecvColor::red().
~ccColorScaleEditorWidget()
ccColorScaleEditorWidget::~ccColorScaleEditorWidget () override default
Destructor.
Member Function Documentation
deleteStep()
void ccColorScaleEditorWidget::deleteStep (int index)
Deletes a given step.
Warning: first and last steps shouldn't be deleted!
Definition at line 693 of file ecvColorScaleEditorWidget.cpp.
References ColorScaleEditorBaseWidget::m_sliders, and onSliderSelected().
Referenced by ccColorScaleEditorDialog::deletecSelectedStep().
exportColorScale()
void ccColorScaleEditorWidget::exportColorScale (ccColorScale::Shared & destScale) const
Exports the current color scale.
Definition at line 660 of file ecvColorScaleEditorWidget.cpp.
References ColorScaleEditorBaseWidget::m_sliders.
Referenced by ccColorScaleEditorDialog::copyCurrentScale(), and ccColorScaleEditorDialog::saveCurrentScale().
getSelectedStepIndex()
int ccColorScaleEditorWidget::getSelectedStepIndex () const inline
Returns currently selected step index.
Definition at line 253 of file ecvColorScaleEditorWidget.h.
Referenced by ccColorScaleEditorDialog::changeSelectedStepColor(), ccColorScaleEditorDialog::changeSelectedStepValue(), ccColorScaleEditorDialog::deletecSelectedStep(), and ccColorScaleEditorDialog::setScaleModeToRelative().
getStep()
const ColorScaleElementSlider* ccColorScaleEditorWidget::getStep (int index) inline
Returns a given slider (pointer on)
Definition at line 242 of file ecvColorScaleEditorWidget.h.
Referenced by ccColorScaleEditorDialog::changeSelectedStepColor(), ccColorScaleEditorDialog::changeSelectedStepValue(), and ccColorScaleEditorDialog::onStepModified().
getStepCount()
int ccColorScaleEditorWidget::getStepCount () const inline
Returns the current number of color scale steps.
Definition at line 237 of file ecvColorScaleEditorWidget.h.
Referenced by ccColorScaleEditorDialog::changeSelectedStepValue(), ccColorScaleEditorDialog::deletecSelectedStep(), ccColorScaleEditorDialog::onStepModified(), and ccColorScaleEditorDialog::onStepSelected().
importColorScale()
void ccColorScaleEditorWidget::importColorScale (ccColorScale::Shared scale)
Imports the current color scale.
Definition at line 645 of file ecvColorScaleEditorWidget.cpp.
References SlidersWidget::addNewSlider(), color, ColorScaleEditorBaseWidget::m_sliders, and m_slidersWidget.
Referenced by ccColorScaleEditorDialog::setActiveScale().
onPointClicked
void ccColorScaleEditorWidget::onPointClicked (double relativePos) protected slot
Slot called when a 'point' is clicked on the color bar.
Definition at line 566 of file ecvColorScaleEditorWidget.cpp.
References SlidersWidget::addNewSlider(), color, DEFAULT_SLIDER_SYMBOL_SIZE, ColorScaleEditorBaseWidget::length(), m_colorBarWidget, ColorScaleEditorBaseWidget::m_sliders, m_slidersWidget, onSliderModified(), SlidersWidget::select(), and ecvColor::white().
Referenced by ccColorScaleEditorWidget().
onSliderModified
void ccColorScaleEditorWidget::onSliderModified (int sliderIndex) protected slot
Slot called when a slider is moved or its color is changed.
Definition at line 611 of file ecvColorScaleEditorWidget.cpp.
References m_colorBarWidget, m_labelsWidget, m_slidersWidget, and stepModified().
Referenced by ccColorScaleEditorWidget(), onPointClicked(), setStepColor(), and setStepRelativePosition().
onSliderSelected
void ccColorScaleEditorWidget::onSliderSelected (int sliderIndex) protected slot
Slot called when a slider is selected.
Definition at line 639 of file ecvColorScaleEditorWidget.cpp.
References m_slidersWidget, and stepSelected().
Referenced by ccColorScaleEditorWidget(), and deleteStep().
setLabelColor()
void ccColorScaleEditorWidget::setLabelColor (QColor color)
Sets the labels color.
Definition at line 679 of file ecvColorScaleEditorWidget.cpp.
References color, m_labelsWidget, and SliderLabelWidget::setTextColor().
setLabelPrecision()
void ccColorScaleEditorWidget::setLabelPrecision (int precision)
Sets the labels precision.
Definition at line 686 of file ecvColorScaleEditorWidget.cpp.
References m_labelsWidget, and SliderLabelWidget::setPrecision().
setSelectedStepIndex()
void ccColorScaleEditorWidget::setSelectedStepIndex (int index, bool silent = false)
Sets currently selected step index.
Definition at line 704 of file ecvColorScaleEditorWidget.cpp.
References m_slidersWidget, and SlidersWidget::select().
Referenced by ccColorScaleEditorDialog::changeSelectedStepValue().
setSliders()
void ccColorScaleEditorWidget::setSliders (SharedColorScaleElementSliders sliders) override virtual
Sets associated sliders set.
Reimplemented from ColorScaleEditorBaseWidget.
Definition at line 624 of file ecvColorScaleEditorWidget.cpp.
References SlidersWidget::addNewSlider(), ColorScaleEditorBaseWidget::m_sliders, and m_slidersWidget.
Referenced by ccColorScaleEditorDialog::changeSelectedStepValue().
setStepColor()
void ccColorScaleEditorWidget::setStepColor (int index, QColor color)
Sets a given slider color.
Definition at line 709 of file ecvColorScaleEditorWidget.cpp.
References color, ColorScaleEditorBaseWidget::m_sliders, and onSliderModified().
Referenced by ccColorScaleEditorDialog::changeSelectedStepColor().
setStepRelativePosition()
void ccColorScaleEditorWidget::setStepRelativePosition (int index, double relativePos)
Sets a given slider relative position.
Definition at line 716 of file ecvColorScaleEditorWidget.cpp.
References ColorScaleEditorBaseWidget::m_sliders, m_slidersWidget, onSliderModified(), SlidersWidget::updateAllSlidersPos(), and SlidersWidget::updateSliderPos().
Referenced by ccColorScaleEditorDialog::changeSelectedStepValue().
showLabels()
void ccColorScaleEditorWidget::showLabels (bool state)
Sets whether to show the color elements labels or not.
Definition at line 672 of file ecvColorScaleEditorWidget.cpp.
References m_labelsWidget.
stepModified
void ccColorScaleEditorWidget::stepModified (int index) signal
Signal emitted when a slider is modified.
Referenced by onSliderModified().
stepSelected
void ccColorScaleEditorWidget::stepSelected (int index) signal
Signal emitted when a slider is selected.
Referenced by onSliderSelected().
Member Data Documentation
m_colorBarWidget
ColorBarWidget* ccColorScaleEditorWidget::m_colorBarWidget protected
Associated color bar.
Definition at line 304 of file ecvColorScaleEditorWidget.h.
Referenced by ccColorScaleEditorWidget(), onPointClicked(), and onSliderModified().
m_labelsWidget
SliderLabelWidget* ccColorScaleEditorWidget::m_labelsWidget protected
Associated (sliders) labels widget.
Definition at line 310 of file ecvColorScaleEditorWidget.h.
Referenced by ccColorScaleEditorWidget(), onSliderModified(), setLabelColor(), setLabelPrecision(), and showLabels().
m_slidersWidget
SlidersWidget* ccColorScaleEditorWidget::m_slidersWidget protected
Associated sliders widget.
Definition at line 307 of file ecvColorScaleEditorWidget.h.
Referenced by ccColorScaleEditorWidget(), importColorScale(), onPointClicked(), onSliderModified(), onSliderSelected(), setSelectedStepIndex(), setSliders(), and setStepRelativePosition().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVPluginAPI/include/ecvColorScaleEditorWidget.h
/root/ACloudViewer/libs/CVPluginAPI/src/ecvColorScaleEditorWidget.cpp