ACloudViewer: qM3C2Dialog Class Reference
qM3C2Dialog Class Reference
M3C2 plugin's main dialog.
#include <qM3C2Dialog.h>
Public Types
enum ExportOptions { PROJECT_ON_CLOUD1 , PROJECT_ON_CLOUD2 , PROJECT_ON_CORE_POINTS }
Exportation options.
Public Member Functions
qM3C2Dialog (ccPointCloud *cloud1, ccPointCloud *cloud2, ecvMainAppInterface *app)
Default constructor.
ccPointCloud * getCloud1 () const
Returns cloud #1.
ccPointCloud * getCloud2 () const
Returns cloud #2.
ccPointCloud * getCorePointsCloud () const
Get core points cloud (if any)
void setCorePointsCloud (ccPointCloud *cloud)
Sets the core points cloud.
ccPointCloud * getNormalsOrientationCloud () const
Returns the cloud to be used for normals orientation (if any)
qM3C2Normals::ComputationMode getNormalsComputationMode () const
Returns selected normals computation mode.
unsigned getMinPointsForStats (unsigned defaultValue=5) const
ExportOptions getExportOption () const
Returns selected export option.
bool keepOriginalCloud () const
int getMaxThreadCount () const
Returns the max number of threads to use.
bool loadParamsFromFile (QString filename)
Loads parameters from persistent settings.
void loadParamsFromPersistentSettings ()
Loads parameters from persistent settings.
void saveParamsToPersistentSettings ()
Saves parameters to persistent settings.
Protected Slots
void swapClouds ()
void setCloud1Visibility (bool)
void setCloud2Visibility (bool)
void saveParamsToFile ()
void loadParamsFromFile ()
void guessParamsSlow ()
void projDestIndexChanged (int)
void onUpdateNormalComboBoxChanged (int)
void updateNormalComboBox ()
Updates the normalSourceComboBox.
Protected Member Functions
void guessParams (bool fastMode)
Guess parameters from the cloud #1.
void setClouds (ccPointCloud *cloud1, ccPointCloud *cloud2)
Sets clouds.
void loadParamsFrom (const QSettings &settings)
Load parameters from QSettings.
void saveParamsTo (QSettings &settings)
Saves parameters to QSettings.
void setupPrecisionMapsTab ()
Setups the precision maps tab.
Protected Attributes
ecvMainAppInterface * m_app
ccPointCloud * m_cloud1
ccPointCloud * m_cloud2
ccPointCloud * m_corePointsCloud
Detailed Description
M3C2 plugin's main dialog.
Definition at line 22 of file qM3C2Dialog.h.
Member Enumeration Documentation
ExportOptions
enum qM3C2Dialog::ExportOptions
Exportation options.
Enumerator
PROJECT_ON_CLOUD1
PROJECT_ON_CLOUD2
PROJECT_ON_CORE_POINTS
Definition at line 57 of file qM3C2Dialog.h.
Constructor & Destructor Documentation
qM3C2Dialog()
qM3C2Dialog::qM3C2Dialog (ccPointCloud * cloud1, ccPointCloud * cloud2, ecvMainAppInterface * app)
Default constructor.
Definition at line 65 of file qM3C2Dialog.cpp.
References ecvMainAppInterface::dbRootObject(), ccHObject::filterChildren(), GetEntityName(), guessParamsSlow(), loadParamsFromFile(), loadParamsFromPersistentSettings(), m_app, onUpdateNormalComboBoxChanged(), CV_TYPES::POINT_CLOUD, projDestIndexChanged(), saveParamsToFile(), setCloud1Visibility(), setCloud2Visibility(), setClouds(), swapClouds(), and updateNormalComboBox().
Member Function Documentation
getCloud1()
ccPointCloud* qM3C2Dialog::getCloud1 () const inline
Returns cloud #1.
Definition at line 32 of file qM3C2Dialog.h.
References m_cloud1.
Referenced by qM3C2Process::Compute(), and define_m3c2_plugin().
getCloud2()
ccPointCloud* qM3C2Dialog::getCloud2 () const inline
Returns cloud #2.
Definition at line 34 of file qM3C2Dialog.h.
References m_cloud2.
Referenced by qM3C2Process::Compute(), and define_m3c2_plugin().
getCorePointsCloud()
ccPointCloud * qM3C2Dialog::getCorePointsCloud () const
Get core points cloud (if any)
Returns either cloud #1 or the cloud specified in the combo box. It can also return a null pointer if the user has requested sub-sampling.
Definition at line 301 of file qM3C2Dialog.cpp.
References ecvMainAppInterface::dbRootObject(), GetCloudFromCombo(), m_app, m_cloud1, and m_corePointsCloud.
Referenced by qM3C2Process::Compute(), and define_m3c2_plugin().
getExportOption()
qM3C2Dialog::ExportOptions qM3C2Dialog::getExportOption () const
Returns selected export option.
Definition at line 370 of file qM3C2Dialog.cpp.
References PROJECT_ON_CLOUD1, PROJECT_ON_CLOUD2, and PROJECT_ON_CORE_POINTS.
Referenced by qM3C2Process::Compute(), define_m3c2_plugin(), and projDestIndexChanged().
getMaxThreadCount()
int qM3C2Dialog::getMaxThreadCount () const
Returns the max number of threads to use.
Definition at line 396 of file qM3C2Dialog.cpp.
Referenced by qM3C2Process::Compute(), and define_m3c2_plugin().
getMinPointsForStats()
unsigned qM3C2Dialog::getMinPointsForStats (unsigned defaultValue = 5) const
Returns the minimum number of points to compute stats (confidence mainly)
Definition at line 400 of file qM3C2Dialog.cpp.
References max().
Referenced by qM3C2Process::Compute(), and guessParams().
getNormalsComputationMode()
qM3C2Normals::ComputationMode qM3C2Dialog::getNormalsComputationMode () const
Returns selected normals computation mode.
Definition at line 345 of file qM3C2Dialog.cpp.
References qM3C2Normals::DEFAULT_MODE, ccPointCloud::hasNormals(), qM3C2Normals::HORIZ_MODE, m_cloud1, qM3C2Normals::MULTI_SCALE_MODE, qM3C2Normals::USE_CLOUD1_NORMALS, qM3C2Normals::USE_CORE_POINTS_NORMALS, and qM3C2Normals::VERT_MODE.
Referenced by qM3C2Process::Compute(), loadParamsFrom(), and saveParamsTo().
getNormalsOrientationCloud()
ccPointCloud * qM3C2Dialog::getNormalsOrientationCloud () const
Returns the cloud to be used for normals orientation (if any)
Definition at line 314 of file qM3C2Dialog.cpp.
References ecvMainAppInterface::dbRootObject(), GetCloudFromCombo(), and m_app.
Referenced by qM3C2Process::Compute(), and define_m3c2_plugin().
guessParams()
void qM3C2Dialog::guessParams (bool fastMode) protected
Guess parameters from the cloud #1.
Definition at line 701 of file qM3C2Dialog.cpp.
References getMinPointsForStats(), qM3C2Tools::GuessBestParams(), m_app, m_cloud1, m_cloud2, and params.
Referenced by guessParamsSlow(), and setClouds().
guessParamsSlow
void qM3C2Dialog::guessParamsSlow () inline protected slot
Definition at line 89 of file qM3C2Dialog.h.
References guessParams().
Referenced by qM3C2Dialog().
keepOriginalCloud()
bool qM3C2Dialog::keepOriginalCloud () const
Returns whether the original cloud should be kept instead of creating a new output one Only valid if the export option is PROJECT_ON_CORE_POINTS.
Definition at line 391 of file qM3C2Dialog.cpp.
Referenced by qM3C2Process::Compute(), and define_m3c2_plugin().
loadParamsFrom()
void qM3C2Dialog::loadParamsFrom (const QSettings & settings) protected
Load parameters from QSettings.
Definition at line 412 of file qM3C2Dialog.cpp.
References qM3C2Normals::DEFAULT_MODE, getNormalsComputationMode(), qM3C2Normals::HORIZ_MODE, qM3C2Normals::MULTI_SCALE_MODE, normalScale, cloudViewer::ScalarField::setValue(), qM3C2Normals::USE_CLOUD1_NORMALS, qM3C2Normals::USE_CORE_POINTS_NORMALS, qM3C2Normals::VERT_MODE, and CVLog::Warning().
Referenced by loadParamsFromFile(), and loadParamsFromPersistentSettings().
loadParamsFromFile [1/2]
void qM3C2Dialog::loadParamsFromFile () protected slot
Definition at line 637 of file qM3C2Dialog.cpp.
References ecvFileUtils::defaultDocPath(), and filename.
Referenced by define_m3c2_plugin(), and qM3C2Dialog().
loadParamsFromFile() [2/2]
bool qM3C2Dialog::loadParamsFromFile (QString filename)
Loads parameters from persistent settings.
Definition at line 658 of file qM3C2Dialog.cpp.
References filename, and loadParamsFrom().
Referenced by CommandM3C2::process().
loadParamsFromPersistentSettings()
void qM3C2Dialog::loadParamsFromPersistentSettings ()
Loads parameters from persistent settings.
Definition at line 407 of file qM3C2Dialog.cpp.
References loadParamsFrom().
Referenced by define_m3c2_plugin(), and qM3C2Dialog().
onUpdateNormalComboBoxChanged
void qM3C2Dialog::onUpdateNormalComboBoxChanged (int) protected slot
Definition at line 238 of file qM3C2Dialog.cpp.
References qM3C2Normals::USE_CLOUD1_NORMALS, and qM3C2Normals::USE_CORE_POINTS_NORMALS.
Referenced by qM3C2Dialog().
projDestIndexChanged
void qM3C2Dialog::projDestIndexChanged (int index) protected slot
Definition at line 386 of file qM3C2Dialog.cpp.
References getExportOption(), and PROJECT_ON_CORE_POINTS.
Referenced by qM3C2Dialog().
saveParamsTo()
void qM3C2Dialog::saveParamsTo (QSettings & settings) protected
Saves parameters to QSettings.
Definition at line 589 of file qM3C2Dialog.cpp.
References getNormalsComputationMode().
Referenced by saveParamsToFile(), and saveParamsToPersistentSettings().
saveParamsToFile
void qM3C2Dialog::saveParamsToFile () protected slot
Definition at line 673 of file qM3C2Dialog.cpp.
References ecvFileUtils::defaultDocPath(), filename, and saveParamsTo().
Referenced by qM3C2Dialog().
saveParamsToPersistentSettings()
void qM3C2Dialog::saveParamsToPersistentSettings ()
Saves parameters to persistent settings.
Definition at line 584 of file qM3C2Dialog.cpp.
References saveParamsTo().
Referenced by define_m3c2_plugin().
setCloud1Visibility
void qM3C2Dialog::setCloud1Visibility (bool state) protected slot
Definition at line 323 of file qM3C2Dialog.cpp.
References m_app, m_cloud1, ecvMainAppInterface::refreshAll(), ccDrawableObject::setVisible(), and ecvMainAppInterface::updateUI().
Referenced by qM3C2Dialog().
setCloud2Visibility
void qM3C2Dialog::setCloud2Visibility (bool state) protected slot
Definition at line 334 of file qM3C2Dialog.cpp.
References m_app, m_cloud2, ecvMainAppInterface::refreshAll(), ccDrawableObject::setVisible(), and ecvMainAppInterface::updateUI().
Referenced by qM3C2Dialog().
setClouds()
void qM3C2Dialog::setClouds (ccPointCloud * cloud1, ccPointCloud * cloud2) protected
Sets clouds.
Definition at line 208 of file qM3C2Dialog.cpp.
References GetEntityName(), guessParams(), ccDrawableObject::isVisible(), m_cloud1, m_cloud2, s_firstTimeInit, and setupPrecisionMapsTab().
Referenced by qM3C2Dialog(), and swapClouds().
setCorePointsCloud()
void qM3C2Dialog::setCorePointsCloud (ccPointCloud * cloud) inline
Sets the core points cloud.
Definition at line 44 of file qM3C2Dialog.h.
References m_corePointsCloud.
Referenced by define_m3c2_plugin(), and CommandM3C2::process().
setupPrecisionMapsTab()
void qM3C2Dialog::setupPrecisionMapsTab () protected
Setups the precision maps tab.
Warning
'setClouds' must have been already called
Definition at line 184 of file qM3C2Dialog.cpp.
References ccPointCloud::hasScalarFields(), m_cloud1, m_cloud2, and PopulatePMFields().
Referenced by setClouds().
swapClouds
void qM3C2Dialog::swapClouds () protected slot
Definition at line 203 of file qM3C2Dialog.cpp.
References m_cloud1, m_cloud2, setClouds(), and updateNormalComboBox().
Referenced by qM3C2Dialog().
updateNormalComboBox
void qM3C2Dialog::updateNormalComboBox () protected slot
Updates the normalSourceComboBox.
Definition at line 255 of file qM3C2Dialog.cpp.
References ecvMainAppInterface::dbRootObject(), qM3C2Normals::DEFAULT_MODE, GetCloudFromCombo(), ccPointCloud::hasNormals(), m_app, m_cloud1, qM3C2Normals::USE_CLOUD1_NORMALS, and qM3C2Normals::USE_CORE_POINTS_NORMALS.
Referenced by qM3C2Dialog(), and swapClouds().
Member Data Documentation
m_app
ecvMainAppInterface* qM3C2Dialog::m_app protected
Definition at line 114 of file qM3C2Dialog.h.
Referenced by getCorePointsCloud(), getNormalsOrientationCloud(), guessParams(), qM3C2Dialog(), setCloud1Visibility(), setCloud2Visibility(), and updateNormalComboBox().
m_cloud1
ccPointCloud* qM3C2Dialog::m_cloud1 protected
Definition at line 116 of file qM3C2Dialog.h.
Referenced by getCloud1(), getCorePointsCloud(), getNormalsComputationMode(), guessParams(), setCloud1Visibility(), setClouds(), setupPrecisionMapsTab(), swapClouds(), and updateNormalComboBox().
m_cloud2
ccPointCloud* qM3C2Dialog::m_cloud2 protected
Definition at line 117 of file qM3C2Dialog.h.
Referenced by getCloud2(), guessParams(), setCloud2Visibility(), setClouds(), setupPrecisionMapsTab(), and swapClouds().
m_corePointsCloud
ccPointCloud* qM3C2Dialog::m_corePointsCloud protected
Definition at line 118 of file qM3C2Dialog.h.
Referenced by getCorePointsCloud(), and setCorePointsCloud().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qM3C2/include/qM3C2Dialog.h
/root/ACloudViewer/plugins/core/Standard/qM3C2/src/qM3C2Dialog.cpp