ACloudViewer: ccColorFromScalarDlg Class Reference
ccColorFromScalarDlg Class Reference
Dialog to change the color levels.
#include <ecvColorFromScalarDlg.h>
Public Member Functions
ccColorFromScalarDlg (QWidget *parent, ccPointCloud *pointCloud)
Default constructor.
~ccColorFromScalarDlg ()
void refreshDisplay ()
void updateHistogram (int)
Static Public Attributes
static constexpr int c_channelCount = 4
Protected Member Functions
void onChannelChangedR (int)
void onChannelChangedG (int)
void onChannelChangedB (int)
void onChannelChangedA (int)
void updateChannel (int)
void updateSpinBoxLimits (int)
void setDefaultSatValuePerChannel (int)
void updateColormaps ()
void minChangedR (double val)
void maxChangedR (double val)
void minChangedG (double val)
void maxChangedG (double val)
void minChangedB (double val)
void maxChangedB (double val)
void minChangedA (double val)
void maxChangedA (double val)
void minSpinChangedR (double val)
void maxSpinChangedR (double val)
void minSpinChangedG (double val)
void maxSpinChangedG (double val)
void minSpinChangedB (double val)
void maxSpinChangedB (double val)
void minSpinChangedA (double val)
void maxSpinChangedA (double val)
void toggleFixedR ()
void toggleFixedG ()
void toggleFixedB ()
void toggleFixedA ()
void toggleColors (int val)
void toggleColorMode (bool state)
void minChanged (int n, double val, bool slider)
void maxChanged (int n, double val, bool slider)
void onApply ()
void disableAllButCancel ()
void resizeEvent (QResizeEvent *event)
Protected Attributes
bool m_prevFixed [c_channelCount]
ccHistogramWindow * m_histograms [c_channelCount]
Associated histogram view.
ccScalarField * m_scalars [c_channelCount]
QComboBox * m_combos [c_channelCount]
QDoubleSpinBox * m_boxes_min [c_channelCount]
QDoubleSpinBox * m_boxes_max [c_channelCount]
QLabel * m_labels_min [c_channelCount]
QLabel * m_labels_max [c_channelCount]
QCheckBox * m_reverse [c_channelCount]
double m_minSat [c_channelCount]
double m_maxSat [c_channelCount]
ccColorScale::Shared m_colors [c_channelCount]
Associated colour scales.
ccPointCloud * m_cloud
Associated point cloud (color source)
ccColorScale::Shared m_storedOrigColorScale
Associated point cloud scalar field original scale (to restore on exit)
ccScalarField::Range m_storedOrigSatRange
ccScalarField::Range m_storedOrigDisplayRange
bool m_systemInvalid
Detailed Description
Dialog to change the color levels.
Definition at line 25 of file ecvColorFromScalarDlg.h.
Constructor & Destructor Documentation
ccColorFromScalarDlg()
ccColorFromScalarDlg::ccColorFromScalarDlg (QWidget * parent, ccPointCloud * pointCloud)
Default constructor.
Definition at line 29 of file ecvColorFromScalarDlg.cpp.
References c_channelCount, disableAllButCancel(), ccScalarField::displayRange(), CVLog::Error(), ccHistogramWindow::fromBinArray(), ccScalarField::getColorScale(), ccPointCloud::getCurrentDisplayedScalarField(), ccPointCloud::getCurrentDisplayedScalarFieldIndex(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudViewer::PointCloudTpl< T >::getScalarFieldName(), m_boxes_max, m_boxes_min, m_cloud, m_colors, m_combos, m_histograms, m_labels_max, m_labels_min, m_prevFixed, m_reverse, m_scalars, m_storedOrigColorScale, m_storedOrigDisplayRange, m_storedOrigSatRange, m_systemInvalid, maxChangedA(), maxChangedB(), maxChangedG(), maxChangedR(), maxSpinChangedA(), maxSpinChangedB(), maxSpinChangedG(), maxSpinChangedR(), minChangedA(), minChangedB(), minChangedG(), minChangedR(), minSpinChangedA(), minSpinChangedB(), minSpinChangedG(), minSpinChangedR(), onApply(), onChannelChangedA(), onChannelChangedB(), onChannelChangedG(), onChannelChangedR(), ccHObject::redrawDisplay(), ccScalarField::saturationRange(), ccScalarField::setColorScale(), ccPointCloud::setCurrentDisplayedScalarField(), setDefaultSatValuePerChannel(), ccHistogramWindow::setRefreshAfterResize(), ccHistogramWindow::sfMaxSatValChanged(), ccHistogramWindow::sfMinSatValChanged(), toggleColorMode(), toggleColors(), toggleFixedA(), toggleFixedB(), toggleFixedG(), toggleFixedR(), updateChannel(), updateColormaps(), and updateHistogram().
~ccColorFromScalarDlg()
ccColorFromScalarDlg::~ccColorFromScalarDlg ()
Definition at line 245 of file ecvColorFromScalarDlg.cpp.
References ccPointCloud::getCurrentDisplayedScalarField(), m_cloud, m_storedOrigColorScale, m_storedOrigDisplayRange, m_storedOrigSatRange, m_systemInvalid, ccScalarField::Range::max(), ccScalarField::Range::min(), ccHObject::redrawDisplay(), ccScalarField::setColorScale(), ccScalarField::setMaxDisplayed(), ccScalarField::setMinDisplayed(), ccScalarField::setSaturationStart(), and ccScalarField::setSaturationStop().
Member Function Documentation
disableAllButCancel()
void ccColorFromScalarDlg::disableAllButCancel () protected
Definition at line 681 of file ecvColorFromScalarDlg.cpp.
References c_channelCount, m_boxes_max, m_boxes_min, m_combos, m_histograms, m_labels_max, m_labels_min, and m_reverse.
Referenced by ccColorFromScalarDlg().
maxChanged()
void ccColorFromScalarDlg::maxChanged (int n, double val, bool slider) protected
Definition at line 565 of file ecvColorFromScalarDlg.cpp.
References c_channelCount, CVLog::Error(), m_boxes_max, m_colors, m_histograms, m_maxSat, m_minSat, m_scalars, ccScalarField::setColorScale(), and ccHistogramWindow::setMaxSatValue().
Referenced by maxChangedA(), maxChangedB(), maxChangedG(), maxChangedR(), maxSpinChangedA(), maxSpinChangedB(), maxSpinChangedG(), and maxSpinChangedR().
maxChangedA()
void ccColorFromScalarDlg::maxChangedA (double val) inline protected
Definition at line 57 of file ecvColorFromScalarDlg.h.
References maxChanged().
Referenced by ccColorFromScalarDlg().
maxChangedB()
void ccColorFromScalarDlg::maxChangedB (double val) inline protected
Definition at line 55 of file ecvColorFromScalarDlg.h.
References maxChanged().
Referenced by ccColorFromScalarDlg().
maxChangedG()
void ccColorFromScalarDlg::maxChangedG (double val) inline protected
Definition at line 53 of file ecvColorFromScalarDlg.h.
References maxChanged().
Referenced by ccColorFromScalarDlg().
maxChangedR()
void ccColorFromScalarDlg::maxChangedR (double val) inline protected
Definition at line 51 of file ecvColorFromScalarDlg.h.
References maxChanged().
Referenced by ccColorFromScalarDlg().
maxSpinChangedA()
void ccColorFromScalarDlg::maxSpinChangedA (double val) inline protected
Definition at line 65 of file ecvColorFromScalarDlg.h.
References maxChanged().
Referenced by ccColorFromScalarDlg().
maxSpinChangedB()
void ccColorFromScalarDlg::maxSpinChangedB (double val) inline protected
Definition at line 63 of file ecvColorFromScalarDlg.h.
References maxChanged().
Referenced by ccColorFromScalarDlg().
maxSpinChangedG()
void ccColorFromScalarDlg::maxSpinChangedG (double val) inline protected
Definition at line 61 of file ecvColorFromScalarDlg.h.
References maxChanged().
Referenced by ccColorFromScalarDlg().
maxSpinChangedR()
void ccColorFromScalarDlg::maxSpinChangedR (double val) inline protected
Definition at line 59 of file ecvColorFromScalarDlg.h.
References maxChanged().
Referenced by ccColorFromScalarDlg().
minChanged()
void ccColorFromScalarDlg::minChanged (int n, double val, bool slider) protected
Definition at line 541 of file ecvColorFromScalarDlg.cpp.
References c_channelCount, CVLog::Error(), m_boxes_min, m_colors, m_histograms, m_maxSat, m_minSat, m_scalars, ccScalarField::setColorScale(), and ccHistogramWindow::setMinSatValue().
Referenced by minChangedA(), minChangedB(), minChangedG(), minChangedR(), minSpinChangedA(), minSpinChangedB(), minSpinChangedG(), and minSpinChangedR().
minChangedA()
void ccColorFromScalarDlg::minChangedA (double val) inline protected
Definition at line 56 of file ecvColorFromScalarDlg.h.
References minChanged().
Referenced by ccColorFromScalarDlg().
minChangedB()
void ccColorFromScalarDlg::minChangedB (double val) inline protected
Definition at line 54 of file ecvColorFromScalarDlg.h.
References minChanged().
Referenced by ccColorFromScalarDlg().
minChangedG()
void ccColorFromScalarDlg::minChangedG (double val) inline protected
Definition at line 52 of file ecvColorFromScalarDlg.h.
References minChanged().
Referenced by ccColorFromScalarDlg().
minChangedR()
void ccColorFromScalarDlg::minChangedR (double val) inline protected
Definition at line 50 of file ecvColorFromScalarDlg.h.
References minChanged().
Referenced by ccColorFromScalarDlg().
minSpinChangedA()
void ccColorFromScalarDlg::minSpinChangedA (double val) inline protected
Definition at line 64 of file ecvColorFromScalarDlg.h.
References minChanged().
Referenced by ccColorFromScalarDlg().
minSpinChangedB()
void ccColorFromScalarDlg::minSpinChangedB (double val) inline protected
Definition at line 62 of file ecvColorFromScalarDlg.h.
References minChanged().
Referenced by ccColorFromScalarDlg().
minSpinChangedG()
void ccColorFromScalarDlg::minSpinChangedG (double val) inline protected
Definition at line 60 of file ecvColorFromScalarDlg.h.
References minChanged().
Referenced by ccColorFromScalarDlg().
minSpinChangedR()
void ccColorFromScalarDlg::minSpinChangedR (double val) inline protected
Definition at line 58 of file ecvColorFromScalarDlg.h.
References minChanged().
Referenced by ccColorFromScalarDlg().
onApply()
void ccColorFromScalarDlg::onApply () protected
Definition at line 589 of file ecvColorFromScalarDlg.cpp.
References c_channelCount, ccPointCloud::colorsHaveChanged(), ecvColor::FromQColora(), cloudViewer::ScalarField::getValue(), ccPointCloud::hasColors(), ecvColor::Convert::hsv2rgb(), m_boxes_min, m_cloud, m_maxSat, m_minSat, m_scalars, m_systemInvalid, ecvColor::MAX, ccHObject::redrawDisplay(), ccPointCloud::resizeTheRGBTable(), rgb, ccPointCloud::setPointColor(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), and cloudViewer::PointCloudTpl< T >::size().
Referenced by ccColorFromScalarDlg().
onChannelChangedA()
void ccColorFromScalarDlg::onChannelChangedA (int) inline protected
Definition at line 44 of file ecvColorFromScalarDlg.h.
References updateChannel().
Referenced by ccColorFromScalarDlg().
onChannelChangedB()
void ccColorFromScalarDlg::onChannelChangedB (int) inline protected
Definition at line 43 of file ecvColorFromScalarDlg.h.
References updateChannel().
Referenced by ccColorFromScalarDlg().
onChannelChangedG()
void ccColorFromScalarDlg::onChannelChangedG (int) inline protected
Definition at line 42 of file ecvColorFromScalarDlg.h.
References updateChannel().
Referenced by ccColorFromScalarDlg().
onChannelChangedR()
void ccColorFromScalarDlg::onChannelChangedR (int) inline protected
Definition at line 41 of file ecvColorFromScalarDlg.h.
References updateChannel().
Referenced by ccColorFromScalarDlg().
refreshDisplay()
void ccColorFromScalarDlg::refreshDisplay ()
Definition at line 376 of file ecvColorFromScalarDlg.cpp.
References c_channelCount, m_systemInvalid, and updateHistogram().
Referenced by resizeEvent(), toggleColorMode(), and toggleColors().
resizeEvent()
void ccColorFromScalarDlg::resizeEvent (QResizeEvent * event) protected
Definition at line 536 of file ecvColorFromScalarDlg.cpp.
References refreshDisplay().
setDefaultSatValuePerChannel()
void ccColorFromScalarDlg::setDefaultSatValuePerChannel (int n) protected
Definition at line 514 of file ecvColorFromScalarDlg.cpp.
References c_channelCount, CVLog::Error(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), m_boxes_max, m_boxes_min, m_colors, m_histograms, m_maxSat, m_minSat, m_scalars, m_systemInvalid, ccScalarField::setColorScale(), ccHistogramWindow::setMaxSatValue(), ccHistogramWindow::setMinSatValue(), and updateSpinBoxLimits().
Referenced by ccColorFromScalarDlg(), updateChannel(), and updateHistogram().
toggleColorMode()
void ccColorFromScalarDlg::toggleColorMode (bool state) protected
Definition at line 367 of file ecvColorFromScalarDlg.cpp.
References m_systemInvalid, refreshDisplay(), and updateColormaps().
Referenced by ccColorFromScalarDlg().
toggleColors()
void ccColorFromScalarDlg::toggleColors (int val) protected
Definition at line 357 of file ecvColorFromScalarDlg.cpp.
References m_systemInvalid, refreshDisplay(), and updateColormaps().
Referenced by ccColorFromScalarDlg().
toggleFixedA()
void ccColorFromScalarDlg::toggleFixedA () inline protected
Definition at line 69 of file ecvColorFromScalarDlg.h.
References updateChannel().
Referenced by ccColorFromScalarDlg().
toggleFixedB()
void ccColorFromScalarDlg::toggleFixedB () inline protected
Definition at line 68 of file ecvColorFromScalarDlg.h.
References updateChannel().
Referenced by ccColorFromScalarDlg().
toggleFixedG()
void ccColorFromScalarDlg::toggleFixedG () inline protected
Definition at line 67 of file ecvColorFromScalarDlg.h.
References updateChannel().
Referenced by ccColorFromScalarDlg().
toggleFixedR()
void ccColorFromScalarDlg::toggleFixedR () inline protected
Definition at line 66 of file ecvColorFromScalarDlg.h.
References updateChannel().
Referenced by ccColorFromScalarDlg().
updateChannel()
void ccColorFromScalarDlg::updateChannel (int n) protected
Definition at line 492 of file ecvColorFromScalarDlg.cpp.
References c_channelCount, ccHistogramWindow::clear(), CVLog::Error(), ccHistogramWindow::fromSF(), cloudViewer::PointCloudTpl< T >::getScalarField(), m_cloud, m_combos, m_histograms, m_scalars, m_systemInvalid, setDefaultSatValuePerChannel(), and updateHistogram().
Referenced by ccColorFromScalarDlg(), onChannelChangedA(), onChannelChangedB(), onChannelChangedG(), onChannelChangedR(), toggleFixedA(), toggleFixedB(), toggleFixedG(), and toggleFixedR().
updateColormaps()
void ccColorFromScalarDlg::updateColormaps () protected
Definition at line 259 of file ecvColorFromScalarDlg.cpp.
References ecvColor::RgbTpl< Type >::b, ecvColor::black(), ecvColor::blue(), c_channelCount, ecvColor::RgbTpl< Type >::g, ecvColor::green(), ecvColor::Convert::hsv2rgb(), m_colors, m_systemInvalid, ecvColor::RgbTpl< Type >::r, ecvColor::red(), and ecvColor::white().
Referenced by ccColorFromScalarDlg(), toggleColorMode(), and toggleColors().
updateHistogram()
void ccColorFromScalarDlg::updateHistogram (int n)
Definition at line 385 of file ecvColorFromScalarDlg.cpp.
References c_channelCount, ccHistogramWindow::clear(), CVLog::Error(), m_boxes_max, m_boxes_min, m_colors, m_combos, m_histograms, m_labels_max, m_labels_min, m_prevFixed, m_reverse, m_scalars, m_systemInvalid, cloudViewer::core::None, ccHistogramWindow::refresh(), QCustomPlot::replot(), ccHistogramWindow::setAxisDisplayOption(), ccHistogramWindow::setAxisLabels(), ccScalarField::setColorScale(), setDefaultSatValuePerChannel(), ccScalarField::setSaturationStart(), ccScalarField::setSaturationStop(), and ccHistogramWindow::setSFInteractionMode().
Referenced by ccColorFromScalarDlg(), refreshDisplay(), and updateChannel().
updateSpinBoxLimits()
void ccColorFromScalarDlg::updateSpinBoxLimits (int n) protected
Definition at line 457 of file ecvColorFromScalarDlg.cpp.
References c_channelCount, CVLog::Error(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), cloudViewer::PointCloudTpl< T >::getScalarField(), m_boxes_max, m_boxes_min, m_cloud, m_combos, m_maxSat, m_minSat, and m_systemInvalid.
Referenced by setDefaultSatValuePerChannel().
Member Data Documentation
c_channelCount
constexpr int ccColorFromScalarDlg::c_channelCount = 4 static constexpr
Definition at line 34 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), disableAllButCancel(), maxChanged(), minChanged(), onApply(), refreshDisplay(), setDefaultSatValuePerChannel(), updateChannel(), updateColormaps(), updateHistogram(), and updateSpinBoxLimits().
m_boxes_max
QDoubleSpinBox* ccColorFromScalarDlg::m_boxes_max[c_channelCount] protected
Definition at line 90 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), disableAllButCancel(), maxChanged(), setDefaultSatValuePerChannel(), updateHistogram(), and updateSpinBoxLimits().
m_boxes_min
QDoubleSpinBox* ccColorFromScalarDlg::m_boxes_min[c_channelCount] protected
Definition at line 89 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), disableAllButCancel(), minChanged(), onApply(), setDefaultSatValuePerChannel(), updateHistogram(), and updateSpinBoxLimits().
m_cloud
ccPointCloud* ccColorFromScalarDlg::m_cloud protected
Associated point cloud (color source)
Definition at line 100 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), onApply(), updateChannel(), updateSpinBoxLimits(), and ~ccColorFromScalarDlg().
m_colors
ccColorScale::Shared ccColorFromScalarDlg::m_colors[c_channelCount] protected
Associated colour scales.
Definition at line 98 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), maxChanged(), minChanged(), setDefaultSatValuePerChannel(), updateColormaps(), and updateHistogram().
m_combos
QComboBox* ccColorFromScalarDlg::m_combos[c_channelCount] protected
Definition at line 88 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), disableAllButCancel(), updateChannel(), updateHistogram(), and updateSpinBoxLimits().
m_histograms
ccHistogramWindow* ccColorFromScalarDlg::m_histograms[c_channelCount] protected
Associated histogram view.
Definition at line 82 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), disableAllButCancel(), maxChanged(), minChanged(), setDefaultSatValuePerChannel(), updateChannel(), and updateHistogram().
m_labels_max
QLabel* ccColorFromScalarDlg::m_labels_max[c_channelCount] protected
Definition at line 92 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), disableAllButCancel(), and updateHistogram().
m_labels_min
QLabel* ccColorFromScalarDlg::m_labels_min[c_channelCount] protected
Definition at line 91 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), disableAllButCancel(), and updateHistogram().
m_maxSat
double ccColorFromScalarDlg::m_maxSat[c_channelCount] protected
Definition at line 96 of file ecvColorFromScalarDlg.h.
Referenced by maxChanged(), minChanged(), onApply(), setDefaultSatValuePerChannel(), and updateSpinBoxLimits().
m_minSat
double ccColorFromScalarDlg::m_minSat[c_channelCount] protected
Definition at line 95 of file ecvColorFromScalarDlg.h.
Referenced by maxChanged(), minChanged(), onApply(), setDefaultSatValuePerChannel(), and updateSpinBoxLimits().
m_prevFixed
bool ccColorFromScalarDlg::m_prevFixed[c_channelCount] protected
Definition at line 80 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), and updateHistogram().
m_reverse
QCheckBox* ccColorFromScalarDlg::m_reverse[c_channelCount] protected
Definition at line 93 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), disableAllButCancel(), and updateHistogram().
m_scalars
ccScalarField* ccColorFromScalarDlg::m_scalars[c_channelCount] protected
Definition at line 85 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), maxChanged(), minChanged(), onApply(), setDefaultSatValuePerChannel(), updateChannel(), and updateHistogram().
m_storedOrigColorScale
ccColorScale::Shared ccColorFromScalarDlg::m_storedOrigColorScale protected
Associated point cloud scalar field original scale (to restore on exit)
Definition at line 102 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), and ~ccColorFromScalarDlg().
m_storedOrigDisplayRange
ccScalarField::Range ccColorFromScalarDlg::m_storedOrigDisplayRange protected
Definition at line 104 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), and ~ccColorFromScalarDlg().
m_storedOrigSatRange
ccScalarField::Range ccColorFromScalarDlg::m_storedOrigSatRange protected
Definition at line 103 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), and ~ccColorFromScalarDlg().
m_systemInvalid
bool ccColorFromScalarDlg::m_systemInvalid protected
Definition at line 106 of file ecvColorFromScalarDlg.h.
Referenced by ccColorFromScalarDlg(), onApply(), refreshDisplay(), setDefaultSatValuePerChannel(), toggleColorMode(), toggleColors(), updateChannel(), updateColormaps(), updateHistogram(), updateSpinBoxLimits(), and ~ccColorFromScalarDlg().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvColorFromScalarDlg.h
/root/ACloudViewer/app/ecvColorFromScalarDlg.cpp