ACloudViewer: qSRA Class Reference
qSRA Class Reference
Surface of Revolution Analysis plugin.
#include <qSRA.h>
Public Member Functions
qSRA (QObject *parent=nullptr)
Default constructor.
virtual ~qSRA ()=default
virtual void onNewSelection (const ccHObject::Container &selectedEntities) override
virtual QList< QAction * > getActions () override
Get a list of actions for this plugin.
Public Member Functions inherited from ccStdPluginInterface
ccStdPluginInterface (const QString &resourcePath=QString())
Default constructor.
virtual ~ccStdPluginInterface () override=default
Destructor.
virtual CC_PLUGIN_TYPE getType () const override
Returns plugin type (standard or OpenGL filter)
virtual void setMainAppInterface (ecvMainAppInterface *app)
Sets application entry point.
virtual ecvMainAppInterface * getMainAppInterface ()
A callback pointer to the main app interface for use by plugins.
virtual void dispToConsole (QString message, ecvMainAppInterface::ConsoleMessageLevel level=ecvMainAppInterface::STD_CONSOLE_MESSAGE)
Shortcut to ecvMainAppInterface::dispToConsole.
Public Member Functions inherited from ccDefaultPluginInterface
virtual ~ccDefaultPluginInterface ()
virtual bool isCore () const override
Is this plugin a core plugin?
virtual QString getName () const override
Returns (short) name (for menu entry, etc.)
virtual QString getDescription () const override
Returns long name/description (for tooltip, etc.)
virtual QIcon getIcon () const override
Returns icon.
virtual ReferenceList getReferences () const override
virtual ContactList getAuthors () const override
virtual ContactList getMaintainers () const override
Public Member Functions inherited from ccPluginInterface
virtual ~ccPluginInterface ()=default
Virtual destructor.
virtual bool start ()
Starts the plugin.
virtual void stop ()
Stops the plugin.
virtual ccExternalFactory * getCustomObjectsFactory () const
Returns the plugin's custom object factory (if any)
virtual void registerCommands (ccCommandLineInterface *cmd)
Optional: registers commands (for the command line mode)
Protected Slots
void loadProfile () const
Loads profile from a dedicated file.
void computeCloud2ProfileRadialDist () const
Computes cloud-to-profile radial distances.
void projectCloudDistsInGrid () const
Projects the cloud distances into a 2D grid.
Protected Member Functions
void doProjectCloudDistsInGrid (ccPointCloud *cloud, ccPolyline *polyline) const
bool doComputeRadialDists (ccPointCloud *cloud, ccPolyline *polyline) const
Computes cloud-to-profile radial distances.
Protected Member Functions inherited from ccDefaultPluginInterface
ccDefaultPluginInterface (const QString &resourcePath=QString())
Protected Attributes
QAction * m_doLoadProfile
Associated action.
QAction * m_doCompareCloudToProfile
Associated action.
QAction * m_doProjectCloudDists
Associated action.
Protected Attributes inherited from ccStdPluginInterface
ecvMainAppInterface * m_app
Main application interface.
Additional Inherited Members
Public Types inherited from ccPluginInterface
typedef QList< Contact > ContactList
using ReferenceList = QList< Reference >
Detailed Description
Surface of Revolution Analysis plugin.
Definition at line 16 of file qSRA.h.
Constructor & Destructor Documentation
qSRA()
qSRA::qSRA (QObject * parent = nullptr) explicit
Default constructor.
Definition at line 40 of file qSRA.cpp.
~qSRA()
virtual qSRA::~qSRA () virtual default
Member Function Documentation
computeCloud2ProfileRadialDist
void qSRA::computeCloud2ProfileRadialDist () const protected slot
Computes cloud-to-profile radial distances.
Definition at line 304 of file qSRA.cpp.
References ccHObject::addChild(), ecvMainAppInterface::addToDB(), CV_TYPES::CONE, ecvMainAppInterface::dispToConsole(), doComputeRadialDists(), doProjectCloudDistsInGrid(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, GetConeProfile(), ecvMainAppInterface::getMainWindow(), ecvMainAppInterface::getSelectedEntities(), ecvColor::green(), ccStdPluginInterface::m_app, CV_TYPES::POINT_CLOUD, CV_TYPES::POLY_LINE, ccPolyline::set2DMode(), ccPolyline::setColor(), ccDrawableObject::setVisible(), ccPolyline::setWidth(), and ccDrawableObject::showColors().
Referenced by getActions().
doComputeRadialDists()
bool qSRA::doComputeRadialDists (ccPointCloud * cloud, ccPolyline * polyline) const protected
Computes cloud-to-profile radial distances.
Definition at line 382 of file qSRA.cpp.
References DistanceMapGenerationTool::ComputeRadialDist(), ecvMainAppInterface::dispToConsole(), ccStdPluginInterface::m_app, ecvMainAppInterface::refreshAll(), ccDrawableObject::setRedraw(), ecvDisplayTools::SetRedrawRecursive(), ecvMainAppInterface::updateUI(), and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by computeCloud2ProfileRadialDist().
doProjectCloudDistsInGrid()
void qSRA::doProjectCloudDistsInGrid (ccPointCloud * cloud, ccPolyline * polyline) const protected
Projects the cloud distances into a 2D grid (needs the revolution profile)
Definition at line 456 of file qSRA.cpp.
References CVLog::Error(), ccPointCloud::getCurrentDisplayedScalarField(), ecvMainAppInterface::getMainWindow(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), ccStdPluginInterface::m_app, m_doCompareCloudToProfile, RADIAL_DIST_SF_NAME, and CVLog::Warning().
Referenced by computeCloud2ProfileRadialDist(), and projectCloudDistsInGrid().
getActions()
QList< QAction * > qSRA::getActions () override virtual
Get a list of actions for this plugin.
Implements ccStdPluginInterface.
Definition at line 47 of file qSRA.cpp.
References computeCloud2ProfileRadialDist(), loadProfile(), m_doCompareCloudToProfile, m_doLoadProfile, m_doProjectCloudDists, and projectCloudDistsInGrid().
loadProfile
void qSRA::loadProfile () const protected slot
Loads profile from a dedicated file.
Definition at line 146 of file qSRA.cpp.
References ProfileImportDlg::absoluteHeightValues(), ccHObject::addChild(), ecvMainAppInterface::addToDB(), ccGLMatrixTpl< T >::data(), ecvFileUtils::defaultDocPath(), ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, filename, ProfileImportDlg::getAxisDimension(), GetDefaultContainer(), ProfileImportDlg::getFilename(), ecvMainAppInterface::getMainWindow(), ProfileLoader::Load(), ccStdPluginInterface::m_app, cloudViewer::t::geometry::path, ccPolyline::set2DMode(), ProfileImportDlg::setDefaultFilename(), ccDrawableObject::setGLTransformation(), DistanceMapGenerationTool::SetPolylineHeightShift(), DistanceMapGenerationTool::SetPoylineOrigin(), DistanceMapGenerationTool::SetPoylineRevolDim(), ccGLMatrixTpl< T >::setTranslation(), ecvMainAppInterface::STD_CONSOLE_MESSAGE, and Tuple3Tpl< Type >::u.
Referenced by getActions().
onNewSelection()
void qSRA::onNewSelection (const ccHObject::Container & selectedEntities) override virtual
This method is called by the main application whenever the entity selection changes Does nothing by default. Should be re-implemented by the plugin if necessary.
Parameters
selectedEntities currently selected entities
Reimplemented from ccStdPluginInterface.
Definition at line 92 of file qSRA.cpp.
References CV_TYPES::CONE, m_doCompareCloudToProfile, m_doLoadProfile, m_doProjectCloudDists, CV_TYPES::POINT_CLOUD, and CV_TYPES::POLY_LINE.
projectCloudDistsInGrid
void qSRA::projectCloudDistsInGrid () const protected slot
Projects the cloud distances into a 2D grid.
Definition at line 408 of file qSRA.cpp.
References CV_TYPES::CONE, doProjectCloudDistsInGrid(), GetConeProfile(), ecvMainAppInterface::getSelectedEntities(), ccStdPluginInterface::m_app, CV_TYPES::POINT_CLOUD, and CV_TYPES::POLY_LINE.
Referenced by getActions().
Member Data Documentation
m_doCompareCloudToProfile
QAction* qSRA::m_doCompareCloudToProfile protected
Associated action.
Definition at line 55 of file qSRA.h.
Referenced by doProjectCloudDistsInGrid(), getActions(), and onNewSelection().
m_doLoadProfile
QAction* qSRA::m_doLoadProfile protected
Associated action.
Definition at line 53 of file qSRA.h.
Referenced by getActions(), and onNewSelection().
m_doProjectCloudDists
QAction* qSRA::m_doProjectCloudDists protected
Associated action.
Definition at line 57 of file qSRA.h.
Referenced by getActions(), and onNewSelection().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qSRA/include/qSRA.h
/root/ACloudViewer/plugins/core/Standard/qSRA/src/qSRA.cpp