ACloudViewer: cloudViewer::Polyline Class Reference
cloudViewer::Polyline Class Reference
A simple polyline class.
#include <Polyline.h>
Public Member Functions
Polyline (GenericIndexedCloudPersist *associatedCloud)
Polyline constructor.
bool isClosed () const
Returns whether the polyline is closed or not.
void setClosed (bool state)
Sets whether the polyline is closed or not.
void clear (bool unusedParam=true) override
Clears the cloud.
Public Member Functions inherited from cloudViewer::ReferenceCloud
ReferenceCloud (GenericIndexedCloudPersist *associatedCloud)
Default constructor.
ReferenceCloud (const ReferenceCloud &refCloud)
Copy constructor.
~ReferenceCloud () override=default
Destructor.
unsigned size () const override
Returns the number of points.
void forEach (genericPointAction action) override
Fast iteration mechanism.
void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax) override
Returns the cloud bounding box.
unsigned char testVisibility (const CCVector3 &P) const override
void placeIteratorAtBeginning () override
Sets the cloud iterator at the beginning.
const CCVector3 * getNextPoint () override
Returns the next point (relatively to the global iterator position)
bool enableScalarField () override
Enables the scalar field associated to the cloud.
bool isScalarFieldEnabled () const override
Returns true if the scalar field is enabled, false otherwise.
void setPointScalarValue (unsigned pointIndex, ScalarType value) override
Sets the ith point associated scalar value.
ScalarType getPointScalarValue (unsigned pointIndex) const override
Returns the ith point associated scalar value.
const CCVector3 * getPoint (unsigned index) const override
Returns the ith point.
void getPoint (unsigned index, CCVector3 &P) const override
Returns the ith point.
void getPoint (unsigned index, double P[3]) const override
const CCVector3 * getPointPersistentPtr (unsigned index) override
Returns the ith point as a persistent pointer.
virtual unsigned getPointGlobalIndex (unsigned localIndex) const
virtual const CCVector3 * getCurrentPointCoordinates () const
Returns the coordinates of the point pointed by the current element.
virtual unsigned getCurrentPointGlobalIndex () const
Returns the global index of the point pointed by the current element.
virtual ScalarType getCurrentPointScalarValue () const
Returns the current point associated scalar value.
virtual void setCurrentPointScalarValue (ScalarType value)
Sets the current point associated scalar value.
virtual void forwardIterator ()
Forwards the local element iterator.
virtual bool addPointIndex (unsigned globalIndex)
Point global index insertion mechanism.
virtual bool addPointIndex (unsigned firstIndex, unsigned lastIndex)
Point global index insertion mechanism (range)
virtual void setPointIndex (unsigned localIndex, unsigned globalIndex)
Sets global index for a given element.
virtual bool reserve (unsigned n)
Reserves some memory for hosting the point references.
virtual bool resize (unsigned n)
Presets the size of the vector used to store point references.
virtual unsigned capacity () const
Returns max capacity.
virtual void swap (unsigned i, unsigned j)
Swaps two point references.
virtual void removeCurrentPointGlobalIndex ()
Removes current element.
virtual void removePointGlobalIndex (unsigned localIndex)
Removes a given element.
virtual GenericIndexedCloudPersist * getAssociatedCloud ()
Returns the associated (source) cloud.
virtual const GenericIndexedCloudPersist * getAssociatedCloud () const
Returns the associated (source) cloud (const version)
virtual void setAssociatedCloud (GenericIndexedCloudPersist *cloud)
Sets the associated (source) cloud.
bool add (const ReferenceCloud &cloud)
Add another reference cloud.
void invalidateBoundingBox ()
Invalidates the bounding-box.
Public Member Functions inherited from cloudViewer::GenericIndexedCloudPersist
~GenericIndexedCloudPersist () override=default
Default destructor.
Public Member Functions inherited from cloudViewer::GenericIndexedCloud
~GenericIndexedCloud () override=default
Default destructor.
virtual bool normalsAvailable () const
Returns whether normals are available.
virtual const CCVector3 * getNormal (unsigned index) const
If per-point normals are available, returns the one at a specific index.
Public Member Functions inherited from cloudViewer::GenericCloud
GenericCloud ()=default
Default constructor.
virtual ~GenericCloud ()=default
Default destructor.
virtual bool hasPoints () const
Protected Attributes
bool m_isClosed
Closing state.
Protected Attributes inherited from cloudViewer::ReferenceCloud
ReferencesContainer m_theIndexes
Indexes of (some of) the associated cloud points.
std::atomic< unsigned > m_globalIterator
Iterator on the point references container.
BoundingBox m_bbox
Bounding-box.
GenericIndexedCloudPersist * m_theAssociatedCloud
Associated cloud.
std::mutex m_mutex
For concurrent access.
Additional Inherited Members
Public Types inherited from cloudViewer::GenericCloud
using genericPointAction = std::function< void(const CCVector3 &, ScalarType &)>
Generic function applied to a point (used by foreach)
Protected Types inherited from cloudViewer::ReferenceCloud
using ReferencesContainer = std::vector< unsigned int >
Container of 3D point indexes.
Detailed Description
A simple polyline class.
The polyline is considered as a cloud of points (in a specific order) with a open/closed state information.
Definition at line 20 of file Polyline.h.
Constructor & Destructor Documentation
Polyline()
Polyline::Polyline (GenericIndexedCloudPersist * associatedCloud) explicit
Polyline constructor.
Definition at line 12 of file Polyline.cpp.
Member Function Documentation
clear()
void Polyline::clear (bool releaseMemory = true) override virtual
Clears the cloud.
Thread safe.
Reimplemented from cloudViewer::ReferenceCloud.
Definition at line 15 of file Polyline.cpp.
References cloudViewer::ReferenceCloud::clear(), and m_isClosed.
Referenced by ccGraphicalSegmentationTool::addPointToPolyline(), ccGraphicalSegmentationTool::closePolyLine(), ccGraphicalSegmentationTool::closeRectangle(), ccTopologyRelation::constructGraphic(), define_Polyline(), ccGraphicalSegmentationTool::doActionUseExistingPolyline(), ccContourExtractor::ExtractFlatContour(), ccTrace::finalizePath(), ccPolyline::operator=(), ccGraphicalSegmentationTool::pauseSegmentationMode(), qCanupo2DViewDialog::resetBoundary(), ccGraphicalSegmentationTool::start(), and ccGraphicalSegmentationTool::updatePolyLine().
isClosed()
bool cloudViewer::Polyline::isClosed () const inline
Returns whether the polyline is closed or not.
Definition at line 26 of file Polyline.h.
Referenced by ccPolyline::computeLength(), define_Polyline(), ccGraphicalSegmentationTool::doActionUseExistingPolyline(), PCLDisplayTools::drawWidgets(), ccTracePolylineTool::polylineOverSampling(), DxfFilter::saveToFile(), SinusxFilter::saveToFile(), ccGraphicalSegmentationTool::segment(), ccPolyline::segmentCount(), ccEntityAction::setColor(), ccPolyline::smoothChaikin(), ccPolyline::split(), and ccMesh::TriangulateTwoPolylines().
setClosed()
void cloudViewer::Polyline::setClosed (bool state) inline
Sets whether the polyline is closed or not.
Definition at line 29 of file Polyline.h.
Referenced by ccGraphicalSegmentationTool::addPointToPolyline(), ccGraphicalSegmentationTool::ccGraphicalSegmentationTool(), ccPolyline::ccPolyline(), ccPolyline::Circle(), ccGraphicalSegmentationTool::closePolyLine(), contourPoly(), contourPoly2(), vtk2cc::ConvertToPolyline(), define_Polyline(), ccGraphicalSegmentationTool::doActionUseExistingPolyline(), ccGraphicalSegmentationTool::doExportSegmentationPolyline(), ccContourExtractor::ExtractConcaveHull2D(), ccContourExtractor::ExtractFlatContour(), ccRasterizeTool::generateContours(), GetConeProfile(), cvContourTool::getOutput(), ecvTools::GetPolylines(), ccPolyline::importParametersFrom(), ProfileLoader::Load(), SinusxFilter::loadFile(), QVTKWidgetCustom::mouseMoveEvent(), CommandCrop2D::process(), ccPolyline::split(), and ccGraphicalSegmentationTool::updatePolyLine().
Member Data Documentation
m_isClosed
bool cloudViewer::Polyline::m_isClosed protected
Closing state.
Definition at line 36 of file Polyline.h.
Referenced by clear(), ccPolyline::createNewPolylinesFromSelection(), ccPolyline::drawMeOnly(), and ccPolyline::importParametersFrom().
The documentation for this class was generated from the following files:
/root/ACloudViewer/core/include/Polyline.h
/root/ACloudViewer/core/src/Polyline.cpp