ACloudViewer: ccCommandLineInterface Class Reference
ccCommandLineInterface Class Reference abstract
Command line interface.
#include <ecvCommandLineInterface.h>
Classes
struct CLLoadParameters
struct Command
Generic command interface.
struct GlobalShiftOptions
Global Shift options.
Public Types
enum class ExportOption {
NoOptions = 0x0 , ForceCloud = 0x1 , ForceMesh = 0x2 , ForceHierarchy = 0x4 ,
ForceNoTimestamp = 0x8
}
Public Member Functions
ccCommandLineInterface ()
Default constructor.
virtual ~ccCommandLineInterface ()=default
virtual bool registerCommand (Command::Shared command)=0
Registers a new command.
virtual QString getExportFilename (const CLEntityDesc &entityDesc, QString extension=QString(), QString suffix=QString(), QString *baseOutputFilename=nullptr, bool forceNoTimestamp=false) const =0
Returns the name of a to-be-exported entity.
virtual QString exportEntity (CLEntityDesc &entityDesc, const QString &suffix=QString(), QString *outputFilename=nullptr, ccCommandLineInterface::ExportOptions options=ExportOption::NoOptions)=0
Exports a cloud or a mesh.
virtual bool saveClouds (QString suffix=QString(), bool allAtOnce=false, const QString *allAtOnceFileName=nullptr)=0
Saves all clouds.
virtual bool saveMeshes (QString suffix=QString(), bool allAtOnce=false, const QString *allAtOnceFileName=nullptr)=0
Saves all meshes.
virtual void removeClouds (bool onlyLast=false)=0
Removes all clouds (or only the last one ;)
virtual void removeMeshes (bool onlyLast=false)=0
Removes all meshes (or only the last one ;)
virtual QStringList & arguments ()=0
Returns the list of arguments.
virtual const QStringList & arguments () const =0
Returns the list of arguments (const version)
virtual ecvProgressDialog * progressDialog ()
Returns a (shared) progress dialog (if any is available)
virtual QDialog * widgetParent ()
Returns a (widget) parent (if any is available)
virtual CLLoadParameters & fileLoadingParams ()
File loading parameters.
virtual bool importFile (QString filename, const GlobalShiftOptions &globalShiftOptions, FileIOFilter::Shared filter=FileIOFilter::Shared(nullptr))=0
Loads a file with a specific filter.
virtual QString cloudExportFormat () const =0
Returns the current cloud(s) export format.
virtual QString cloudExportExt () const =0
Returns the current cloud(s) export extension (warning: can be anything)
virtual QString meshExportFormat () const =0
Returns the current mesh(es) export format.
virtual QString meshExportExt () const =0
Returns the current mesh(es) export extension (warning: can be anything)
virtual QString hierarchyExportFormat () const =0
Returns the current hierarchy(ies) export format.
virtual QString hierarchyExportExt () const =0
virtual void setCloudExportFormat (QString format, QString ext)=0
Sets the current cloud(s) export format and extension.
virtual void setMeshExportFormat (QString format, QString ext)=0
Sets the current mesh(es) export format and extension.
virtual void setHierarchyExportFormat (QString format, QString ext)=0
Sets the current hierarchy(ies) export format and extension.
virtual void print (const QString &message) const =0
virtual void warning (const QString &message) const =0
virtual bool error (const QString &message) const =0
virtual std::vector< CLCloudDesc > & clouds ()
Currently opened point clouds and their filename.
virtual const std::vector< CLCloudDesc > & clouds () const
Currently opened point clouds and their filename (const version)
virtual std::vector< CLMeshDesc > & meshes ()
Currently opened meshes and their filename.
virtual const std::vector< CLMeshDesc > & meshes () const
Currently opened meshes and their filename (const version)
void toggleSilentMode (bool state)
Toggles silent mode.
bool silentMode () const
Returns the silent mode.
void toggleAutoSaveMode (bool state)
bool autoSaveMode () const
void toggleAddTimestamp (bool state)
bool addTimestamp () const
void setNumericalPrecision (int p)
Sets the numerical precision.
int numericalPrecision () const
Returns the numerical precision.
bool nextCommandIsGlobalShift () const
Returns whether the nex command is the '-GLOBAL_SHIFT' option.
bool processGlobalShiftCommand (GlobalShiftOptions &options)
Static Public Member Functions
static bool IsCommand (const QString &token, const char *command)
Test whether a command line token is a valid command keyword or not.
Protected Attributes
std::vector< CLCloudDesc > m_clouds
Currently opened point clouds and their filename.
std::vector< CLMeshDesc > m_meshes
Currently opened meshes and their filename.
bool m_silentMode
Silent mode.
bool m_autoSaveMode
Whether files should be automatically saved (after each process) or not.
bool m_addTimestamp
Whether a timestamp should be automatically added to output files or not.
int m_precision
Default numerical precision for ASCII output.
CLLoadParameters m_loadingParameters
File loading parameters.
Detailed Description
Command line interface.
Definition at line 112 of file ecvCommandLineInterface.h.
Member Enumeration Documentation
ExportOption
enum ccCommandLineInterface::ExportOption strong
Enumerator
NoOptions
ForceCloud
ForceMesh
ForceHierarchy
ForceNoTimestamp
Definition at line 119 of file ecvCommandLineInterface.h.
Constructor & Destructor Documentation
ccCommandLineInterface()
ccCommandLineInterface::ccCommandLineInterface ()
Default constructor.
Definition at line 113 of file ecvCommandLineInterface.cpp.
~ccCommandLineInterface()
virtual ccCommandLineInterface::~ccCommandLineInterface () virtual default
Member Function Documentation
addTimestamp()
bool ccCommandLineInterface::addTimestamp () const
Returns whether a timestamp should be automatically added to output files or not
Definition at line 161 of file ecvCommandLineInterface.cpp.
References m_addTimestamp.
Referenced by CommandMatchBestFitPlane::process(), CommandICP::process(), CommandSaveClouds::process(), CommandSaveMeshes::process(), CommandRasterize::process(), and CommandVolume25D::process().
arguments() [1/2]
virtual const QStringList& ccCommandLineInterface::arguments () const pure virtual
Returns the list of arguments (const version)
Implemented in ccCommandLineParser.
arguments() [2/2]
virtual QStringList& ccCommandLineInterface::arguments () pure virtual
Returns the list of arguments.
Implemented in ccCommandLineParser.
Referenced by CommandChangeOutputFormat::getFileFormatFilter(), GetSFIndexOrName(), CommandRANSAC::makePathIfPossible(), nextCommandIsGlobalShift(), CommandSave::ParseFileNames(), PythonPluginCommand::Args::parseFrom(), CommandCrossSection::process(), CommandChangeCloudOutputFormat::process(), CommandChangeMeshOutputFormat::process(), CommandChangeHierarchyOutputFormat::process(), CommandLoad::process(), CommandOctreeNormal::process(), CommandSubsample::process(), CommandExtractCCs::process(), CommandCurvature::process(), CommandApproxDensity::process(), CommandDensity::process(), CommandSFGradient::process(), CommandRoughness::process(), CommandApplyTransformation::process(), CommandSFColorScale::process(), CommandSFConvertToRGB::process(), CommandFilterBySFValue::process(), CommandComputeMeshVolume::process(), CommandSetActiveSF::process(), CommandRemoveSF::process(), CommandMatchBestFitPlane::process(), CommandOrientNormalsMST::process(), CommandSORFilter::process(), CommandSampleMesh::process(), CommandCrop::process(), CommandCoordToSF::process(), CommandCrop2D::process(), CommandColorBanding::process(), CommandDist::process(), CommandStatTest::process(), CommandDelaunayTri::process(), CommandSFArithmetic::process(), CommandSFOperation::process(), CommandSFRename::process(), CommandICP::process(), CommandChangePLYExportFormat::process(), CommandSaveClouds::process(), CommandSaveMeshes::process(), CommandAutoSave::process(), CommandLogFile::process(), CommandMoment::process(), CommandFeature::process(), CommandRasterize::process(), CommandVolume25D::process(), BundlerCommand::process(), FBXCommand::process(), CommandLoadLASFWF::process(), CommandSaveLASFWF::process(), Command3DMASCClassif::process(), CommandCanupoClassif::process(), CommandCSF::process(), CommandM3C2::process(), PCDCommand::process(), PCVCommand::process(), CommandRANSAC::process(), CommandTreeIso::process(), processGlobalShiftCommand(), and ReadDensityType().
autoSaveMode()
bool ccCommandLineInterface::autoSaveMode () const
Returns whether files should be automatically saved (after each process) or not
Definition at line 155 of file ecvCommandLineInterface.cpp.
References m_autoSaveMode.
Referenced by CommandOctreeNormal::process(), CommandInvertNormal::process(), CommandConvertNormalsToDipAndDipDir::process(), CommandConvertNormalsToSFs::process(), CommandSubsample::process(), CommandExtractCCs::process(), CommandCurvature::process(), CommandApproxDensity::process(), CommandDensity::process(), CommandSFGradient::process(), CommandRoughness::process(), CommandApplyTransformation::process(), CommandSFColorScale::process(), CommandSFConvertToRGB::process(), CommandFilterBySFValue::process(), CommandMergeMeshes::process(), CommandMergeClouds::process(), CommandMatchBBCenters::process(), CommandMatchBestFitPlane::process(), CommandOrientNormalsMST::process(), CommandSORFilter::process(), CommandExtractVertices::process(), CommandSampleMesh::process(), CommandCrop::process(), CommandCoordToSF::process(), CommandCrop2D::process(), CommandColorBanding::process(), CommandDist::process(), CommandStatTest::process(), CommandDelaunayTri::process(), CommandSFArithmetic::process(), CommandSFOperation::process(), CommandSFRename::process(), CommandICP::process(), CommandMoment::process(), CommandFeature::process(), CommandRasterize::process(), CommandVolume25D::process(), Command3DMASCClassif::process(), CommandCanupoClassif::process(), CommandM3C2::process(), PCVCommand::process(), and CommandRANSAC::process().
cloudExportExt()
virtual QString ccCommandLineInterface::cloudExportExt () const pure virtual
Returns the current cloud(s) export extension (warning: can be anything)
Implemented in ccCommandLineParser.
Referenced by CommandChangeCloudOutputFormat::process(), CommandSaveClouds::process(), and CommandSaveLASFWF::process().
cloudExportFormat()
virtual QString ccCommandLineInterface::cloudExportFormat () const pure virtual
Returns the current cloud(s) export format.
Implemented in ccCommandLineParser.
Referenced by CommandChangeCloudOutputFormat::process(), CommandSaveClouds::process(), and CommandSaveLASFWF::process().
clouds() [1/2]
std::vector< CLCloudDesc > & ccCommandLineInterface::clouds () virtual
Currently opened point clouds and their filename.
Definition at line 133 of file ecvCommandLineInterface.cpp.
References m_clouds.
Referenced by define_ccCommandLine(), ccCommandLineParser::importFile(), CommandCrossSection::process(), CommandClearNormals::process(), CommandOctreeNormal::process(), CommandInvertNormal::process(), CommandConvertNormalsToDipAndDipDir::process(), CommandConvertNormalsToSFs::process(), CommandSubsample::process(), CommandExtractCCs::process(), CommandCurvature::process(), CommandApproxDensity::process(), CommandDensity::process(), CommandSFGradient::process(), CommandRoughness::process(), CommandApplyTransformation::process(), CommandDropGlobalShift::process(), CommandSFColorScale::process(), CommandSFConvertToRGB::process(), CommandFilterBySFValue::process(), CommandMergeClouds::process(), CommandSetActiveSF::process(), CommandRemoveAllSFs::process(), CommandRemoveSF::process(), CommandRemoveRGB::process(), CommandRemoveNormals::process(), CommandRemoveScanGrids::process(), CommandMatchBBCenters::process(), CommandMatchBestFitPlane::process(), CommandOrientNormalsMST::process(), CommandSORFilter::process(), CommandExtractVertices::process(), CommandSampleMesh::process(), CommandCrop::process(), CommandCoordToSF::process(), CommandCrop2D::process(), CommandColorBanding::process(), CommandDist::process(), CommandCPS::process(), CommandStatTest::process(), CommandDelaunayTri::process(), CommandSFArithmetic::process(), CommandSFOperation::process(), CommandSFRename::process(), CommandICP::process(), CommandSaveClouds::process(), CommandMoment::process(), CommandFeature::process(), CommandRasterize::process(), CommandVolume25D::process(), Command3DMASCClassif::process(), CommandCanupoClassif::process(), CommandCSF::process(), CommandM3C2::process(), PCVCommand::process(), CommandRANSAC::process(), and CommandTreeIso::process().
clouds() [2/2]
const std::vector< CLCloudDesc > & ccCommandLineInterface::clouds () const virtual
Currently opened point clouds and their filename (const version)
Definition at line 135 of file ecvCommandLineInterface.cpp.
References m_clouds.
error()
virtual bool ccCommandLineInterface::error (const QString & message) const pure virtual
Implemented in ccCommandLineParser.
Referenced by CommandChangeOutputFormat::getFileFormatFilter(), CommandRANSAC::makePathIfPossible(), CommandSave::ParseFileNames(), PythonPluginCommand::Args::parseFrom(), CommandCrossSection::process(), CommandChangeCloudOutputFormat::process(), CommandChangeMeshOutputFormat::process(), CommandChangeHierarchyOutputFormat::process(), CommandLoad::process(), CommandClearNormals::process(), CommandOctreeNormal::process(), CommandInvertNormal::process(), CommandConvertNormalsToDipAndDipDir::process(), CommandConvertNormalsToSFs::process(), CommandSubsample::process(), CommandExtractCCs::process(), CommandCurvature::process(), CommandApproxDensity::process(), CommandDensity::process(), CommandSFGradient::process(), CommandRoughness::process(), CommandApplyTransformation::process(), CommandDropGlobalShift::process(), CommandSFColorScale::process(), CommandSFConvertToRGB::process(), CommandFilterBySFValue::process(), CommandComputeMeshVolume::process(), CommandMergeMeshes::process(), CommandMergeClouds::process(), CommandSetActiveSF::process(), CommandRemoveSF::process(), CommandMatchBBCenters::process(), CommandMatchBestFitPlane::process(), CommandOrientNormalsMST::process(), CommandSORFilter::process(), CommandExtractVertices::process(), CommandSampleMesh::process(), CommandCrop::process(), CommandCoordToSF::process(), CommandCrop2D::process(), CommandColorBanding::process(), CommandDist::process(), CommandCPS::process(), CommandStatTest::process(), CommandDelaunayTri::process(), CommandSFArithmetic::process(), CommandSFOperation::process(), CommandSFRename::process(), CommandICP::process(), CommandChangePLYExportFormat::process(), CommandSaveClouds::process(), CommandSaveMeshes::process(), CommandAutoSave::process(), CommandLogFile::process(), CommandMoment::process(), CommandFeature::process(), CommandRasterize::process(), CommandVolume25D::process(), BundlerCommand::process(), FBXCommand::process(), CommandLoadLASFWF::process(), Command3DMASCClassif::process(), CommandCanupoClassif::process(), CommandCSF::process(), CommandM3C2::process(), PCDCommand::process(), PCVCommand::process(), PythonPluginCommand::process(), CommandRANSAC::process(), CommandTreeIso::process(), processGlobalShiftCommand(), and ReadDensityType().
exportEntity()
virtual QString ccCommandLineInterface::exportEntity (CLEntityDesc & entityDesc, const QString & suffix = QString(), QString * outputFilename = nullptr, ccCommandLineInterface::ExportOptions options = ExportOption::NoOptions) pure virtual
Exports a cloud or a mesh.
Returns
error string (if any)
Implemented in ccCommandLineParser.
Referenced by define_ccCommandLine(), CommandCrossSection::process(), CommandOctreeNormal::process(), CommandInvertNormal::process(), CommandConvertNormalsToDipAndDipDir::process(), CommandConvertNormalsToSFs::process(), CommandSubsample::process(), CommandExtractCCs::process(), CommandFilterBySFValue::process(), CommandMergeMeshes::process(), CommandMergeClouds::process(), CommandMatchBBCenters::process(), CommandMatchBestFitPlane::process(), CommandOrientNormalsMST::process(), CommandSORFilter::process(), CommandExtractVertices::process(), CommandSampleMesh::process(), CommandCrop::process(), CommandCoordToSF::process(), CommandCrop2D::process(), CommandDist::process(), CommandCPS::process(), CommandStatTest::process(), CommandDelaunayTri::process(), CommandSFArithmetic::process(), CommandSFOperation::process(), CommandSFRename::process(), CommandICP::process(), CommandRasterize::process(), CommandVolume25D::process(), Command3DMASCClassif::process(), CommandCanupoClassif::process(), CommandCSF::process(), CommandM3C2::process(), PCVCommand::process(), and CommandRANSAC::process().
fileLoadingParams()
ccCommandLineInterface::CLLoadParameters & ccCommandLineInterface::fileLoadingParams () virtual
File loading parameters.
Definition at line 129 of file ecvCommandLineInterface.cpp.
References m_loadingParameters.
Referenced by CommandForceNormalsComputation::process().
getExportFilename()
virtual QString ccCommandLineInterface::getExportFilename (const CLEntityDesc & entityDesc, QString extension = QString(), QString suffix = QString(), QString * baseOutputFilename = nullptr, bool forceNoTimestamp = false) const pure virtual
Returns the name of a to-be-exported entity.
Implemented in ccCommandLineParser.
Referenced by define_ccCommandLine(), and CommandRasterize::process().
hierarchyExportExt()
virtual QString ccCommandLineInterface::hierarchyExportExt () const pure virtual
Returns the current hierarchy(ies) export extension (warning: can be anything)
Implemented in ccCommandLineParser.
Referenced by CommandChangeHierarchyOutputFormat::process().
hierarchyExportFormat()
virtual QString ccCommandLineInterface::hierarchyExportFormat () const pure virtual
Returns the current hierarchy(ies) export format.
Implemented in ccCommandLineParser.
Referenced by CommandChangeHierarchyOutputFormat::process().
importFile()
virtual bool ccCommandLineInterface::importFile (QString filename, const GlobalShiftOptions & globalShiftOptions, FileIOFilter::Shared filter = FileIOFilter::Shared(nullptr)) pure virtual
Loads a file with a specific filter.
Automatically dispatches the entities between the clouds and meshes sets.
Implemented in ccCommandLineParser.
Referenced by CommandLoad::process(), and CommandLoadLASFWF::process().
IsCommand()
bool ccCommandLineInterface::IsCommand (const QString & token, const char * command) static
Test whether a command line token is a valid command keyword or not.
Definition at line 119 of file ecvCommandLineInterface.cpp.
Referenced by nextCommandIsGlobalShift(), ccCommandLineParser::Parse(), CommandChangeCloudOutputFormat::process(), CommandChangeMeshOutputFormat::process(), CommandChangeHierarchyOutputFormat::process(), CommandLoad::process(), CommandOctreeNormal::process(), CommandApproxDensity::process(), CommandDensity::process(), CommandComputeMeshVolume::process(), CommandMatchBestFitPlane::process(), CommandCrop::process(), CommandCrop2D::process(), CommandDist::process(), CommandDelaunayTri::process(), CommandICP::process(), CommandRasterize::process(), CommandVolume25D::process(), BundlerCommand::process(), FBXCommand::process(), Command3DMASCClassif::process(), CommandCanupoClassif::process(), CommandCSF::process(), PCVCommand::process(), and CommandTreeIso::process().
meshes() [1/2]
std::vector< CLMeshDesc > & ccCommandLineInterface::meshes () virtual
Currently opened meshes and their filename.
Definition at line 139 of file ecvCommandLineInterface.cpp.
References m_meshes.
Referenced by define_ccCommandLine(), ccCommandLineParser::importFile(), CommandCrossSection::process(), CommandClearNormals::process(), CommandInvertNormal::process(), CommandApplyTransformation::process(), CommandDropGlobalShift::process(), CommandComputeMeshVolume::process(), CommandMergeMeshes::process(), CommandRemoveAllSFs::process(), CommandRemoveSF::process(), CommandRemoveRGB::process(), CommandRemoveNormals::process(), CommandRemoveScanGrids::process(), CommandMatchBBCenters::process(), CommandMatchBestFitPlane::process(), CommandExtractVertices::process(), CommandSampleMesh::process(), CommandCrop::process(), CommandColorBanding::process(), CommandDist::process(), CommandDelaunayTri::process(), CommandSFArithmetic::process(), CommandSFOperation::process(), CommandSFRename::process(), CommandICP::process(), CommandSaveMeshes::process(), CommandRasterize::process(), CommandVolume25D::process(), PCVCommand::process(), and CommandRANSAC::process().
meshes() [2/2]
const std::vector< CLMeshDesc > & ccCommandLineInterface::meshes () const virtual
Currently opened meshes and their filename (const version)
Definition at line 141 of file ecvCommandLineInterface.cpp.
References m_meshes.
meshExportExt()
virtual QString ccCommandLineInterface::meshExportExt () const pure virtual
Returns the current mesh(es) export extension (warning: can be anything)
Implemented in ccCommandLineParser.
Referenced by CommandChangeMeshOutputFormat::process(), and CommandSaveMeshes::process().
meshExportFormat()
virtual QString ccCommandLineInterface::meshExportFormat () const pure virtual
Returns the current mesh(es) export format.
Implemented in ccCommandLineParser.
Referenced by CommandChangeMeshOutputFormat::process(), and CommandSaveMeshes::process().
nextCommandIsGlobalShift()
bool ccCommandLineInterface::nextCommandIsGlobalShift () const
Returns whether the nex command is the '-GLOBAL_SHIFT' option.
Definition at line 167 of file ecvCommandLineInterface.cpp.
References arguments(), and IsCommand().
Referenced by CommandLoad::process(), and CommandLoadLASFWF::process().
numericalPrecision()
int ccCommandLineInterface::numericalPrecision () const
Returns the numerical precision.
Definition at line 165 of file ecvCommandLineInterface.cpp.
References m_precision.
Referenced by CommandChangeCloudOutputFormat::process(), CommandMatchBestFitPlane::process(), and CommandICP::process().
print()
virtual void ccCommandLineInterface::print (const QString & message) const pure virtual
Implemented in ccCommandLineParser.
Referenced by GetSFIndexOrName(), CommandRANSAC::makePathIfPossible(), CommandCrossSection::process(), CommandChangeCloudOutputFormat::process(), CommandChangeMeshOutputFormat::process(), CommandChangeHierarchyOutputFormat::process(), CommandLoad::process(), CommandClearNormals::process(), CommandOctreeNormal::process(), CommandInvertNormal::process(), CommandConvertNormalsToDipAndDipDir::process(), CommandConvertNormalsToSFs::process(), CommandSubsample::process(), CommandExtractCCs::process(), CommandCurvature::process(), CommandApproxDensity::process(), CommandDensity::process(), CommandSFGradient::process(), CommandRoughness::process(), CommandApplyTransformation::process(), CommandDropGlobalShift::process(), CommandSFColorScale::process(), CommandSFConvertToRGB::process(), CommandFilterBySFValue::process(), CommandComputeMeshVolume::process(), CommandMergeMeshes::process(), CommandMergeClouds::process(), CommandSetActiveSF::process(), CommandRemoveSF::process(), CommandMatchBBCenters::process(), CommandMatchBestFitPlane::process(), CommandOrientNormalsMST::process(), CommandSORFilter::process(), CommandExtractVertices::process(), CommandSampleMesh::process(), CommandCrop::process(), CommandCoordToSF::process(), CommandCrop2D::process(), CommandColorBanding::process(), CommandDist::process(), CommandCPS::process(), CommandStatTest::process(), CommandDelaunayTri::process(), CommandSFArithmetic::process(), CommandSFOperation::process(), CommandSFRename::process(), CommandICP::process(), CommandAutoSave::process(), CommandMoment::process(), CommandFeature::process(), CommandRasterize::process(), CommandVolume25D::process(), BundlerCommand::process(), FBXCommand::process(), CommandLoadLASFWF::process(), Command3DMASCClassif::process(), CommandCanupoClassif::process(), CommandCSF::process(), CommandM3C2::process(), PCDCommand::process(), PCVCommand::process(), PythonPluginCommand::process(), CommandRANSAC::process(), and CommandTreeIso::process().
processGlobalShiftCommand()
bool ccCommandLineInterface::processGlobalShiftCommand (GlobalShiftOptions & options)
Check the current command line argument stack against the 'COMMAND_OPEN_SHIFT_ON_LOAD' keyword and process the following commands if necessary
Warning
This method assumes the 'COMMAND_OPEN_SHIFT_ON_LOAD' argument has already been removed from the argument stack
Definition at line 172 of file ecvCommandLineInterface.cpp.
References arguments(), ccCommandLineInterface::GlobalShiftOptions::AUTO_GLOBAL_SHIFT, ccCommandLineInterface::GlobalShiftOptions::CUSTOM_GLOBAL_SHIFT, ccCommandLineInterface::GlobalShiftOptions::customGlobalShift, error(), ccCommandLineInterface::GlobalShiftOptions::FIRST_GLOBAL_SHIFT, ccCommandLineInterface::GlobalShiftOptions::mode, ccCommandLineInterface::GlobalShiftOptions::NO_GLOBAL_SHIFT, size, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by CommandLoad::process(), and CommandLoadLASFWF::process().
progressDialog()
ecvProgressDialog * ccCommandLineInterface::progressDialog () virtual
Returns a (shared) progress dialog (if any is available)
Definition at line 124 of file ecvCommandLineInterface.cpp.
Referenced by CommandSubsample::process().
registerCommand()
virtual bool ccCommandLineInterface::registerCommand (Command::Shared command) pure virtual
Registers a new command.
Returns
success
Referenced by q3DMASCPlugin::registerCommands(), qCSF::registerCommands(), qPCV::registerCommands(), and PythonPlugin::registerCommands().
removeClouds()
virtual void ccCommandLineInterface::removeClouds (bool onlyLast = false) pure virtual
Removes all clouds (or only the last one ;)
Implemented in ccCommandLineParser.
Referenced by CommandCrossSection::process(), CommandClear::process(), CommandClearClouds::process(), CommandPopClouds::process(), and CommandCSF::process().
removeMeshes()
virtual void ccCommandLineInterface::removeMeshes (bool onlyLast = false) pure virtual
Removes all meshes (or only the last one ;)
Implemented in ccCommandLineParser.
Referenced by CommandCrossSection::process(), CommandMergeMeshes::process(), CommandExtractVertices::process(), CommandClear::process(), CommandClearMeshes::process(), and CommandPopMeshes::process().
saveClouds()
virtual bool ccCommandLineInterface::saveClouds (QString suffix = QString(), bool allAtOnce = false, const QString * allAtOnceFileName = nullptr) pure virtual
Saves all clouds.
Parameters
suffix optional suffix
allAtOnce whether to save all clouds in the same file or one cloud per file
Returns
success
Implemented in ccCommandLineParser.
Referenced by define_ccCommandLine(), CommandCurvature::process(), CommandApproxDensity::process(), CommandDensity::process(), CommandSFGradient::process(), CommandRoughness::process(), CommandApplyTransformation::process(), CommandSFColorScale::process(), CommandSFConvertToRGB::process(), CommandColorBanding::process(), CommandSaveClouds::process(), CommandMoment::process(), CommandFeature::process(), and CommandSaveLASFWF::process().
saveMeshes()
virtual bool ccCommandLineInterface::saveMeshes (QString suffix = QString(), bool allAtOnce = false, const QString * allAtOnceFileName = nullptr) pure virtual
Saves all meshes.
Parameters
suffix optional suffix
allAtOnce whether to save all meshes in the same file or one mesh per file
Returns
success
Implemented in ccCommandLineParser.
Referenced by define_ccCommandLine(), CommandApplyTransformation::process(), CommandColorBanding::process(), and CommandSaveMeshes::process().
setCloudExportFormat()
virtual void ccCommandLineInterface::setCloudExportFormat (QString format, QString ext) pure virtual
Sets the current cloud(s) export format and extension.
Implemented in ccCommandLineParser.
Referenced by CommandChangeCloudOutputFormat::process(), CommandSaveClouds::process(), and CommandSaveLASFWF::process().
setHierarchyExportFormat()
virtual void ccCommandLineInterface::setHierarchyExportFormat (QString format, QString ext) pure virtual
Sets the current hierarchy(ies) export format and extension.
Implemented in ccCommandLineParser.
Referenced by CommandChangeHierarchyOutputFormat::process().
setMeshExportFormat()
virtual void ccCommandLineInterface::setMeshExportFormat (QString format, QString ext) pure virtual
Sets the current mesh(es) export format and extension.
Implemented in ccCommandLineParser.
Referenced by CommandChangeMeshOutputFormat::process(), and CommandSaveMeshes::process().
setNumericalPrecision()
void ccCommandLineInterface::setNumericalPrecision (int p)
Sets the numerical precision.
Definition at line 163 of file ecvCommandLineInterface.cpp.
References m_precision.
silentMode()
bool ccCommandLineInterface::silentMode () const
Returns the silent mode.
Definition at line 149 of file ecvCommandLineInterface.cpp.
References m_silentMode.
Referenced by ccCommandLineParser::exportEntity(), CommandOctreeNormal::process(), CommandSubsample::process(), CommandExtractCCs::process(), CommandOrientNormalsMST::process(), CommandSORFilter::process(), CommandSampleMesh::process(), CommandStatTest::process(), CommandLogFile::process(), CommandRasterize::process(), CommandVolume25D::process(), Command3DMASCClassif::process(), CommandCanupoClassif::process(), CommandM3C2::process(), and CommandRANSAC::process().
toggleAddTimestamp()
void ccCommandLineInterface::toggleAddTimestamp (bool state)
Sets whether a timestamp should be automatically added to output files or not
Definition at line 157 of file ecvCommandLineInterface.cpp.
References m_addTimestamp.
Referenced by CommandSaveClouds::process(), CommandSaveMeshes::process(), and CommandSetNoTimestamp::process().
toggleAutoSaveMode()
void ccCommandLineInterface::toggleAutoSaveMode (bool state)
Sets whether files should be automatically saved (after each process) or not
Definition at line 151 of file ecvCommandLineInterface.cpp.
References m_autoSaveMode.
Referenced by CommandAutoSave::process().
toggleSilentMode()
void ccCommandLineInterface::toggleSilentMode (bool state)
Toggles silent mode.
Must be called BEFORE calling start.
Definition at line 145 of file ecvCommandLineInterface.cpp.
References m_silentMode.
warning()
virtual void ccCommandLineInterface::warning (const QString & message) const pure virtual
Implemented in ccCommandLineParser.
Referenced by GetEmptyCellFillingStrategy(), GetProjectionType(), GetSFIndexOrName(), CommandCrossSection::process(), CommandChangeCloudOutputFormat::process(), CommandInvertNormal::process(), CommandConvertNormalsToDipAndDipDir::process(), CommandConvertNormalsToSFs::process(), CommandSubsample::process(), CommandExtractCCs::process(), CommandSFGradient::process(), CommandSFConvertToRGB::process(), CommandComputeMeshVolume::process(), CommandMergeMeshes::process(), CommandMergeClouds::process(), CommandSetActiveSF::process(), CommandRemoveSF::process(), CommandMatchBBCenters::process(), CommandMatchBestFitPlane::process(), CommandOrientNormalsMST::process(), CommandExtractVertices::process(), CommandCrop2D::process(), CommandColorBanding::process(), CommandDist::process(), CommandCPS::process(), CommandDelaunayTri::process(), CommandRasterize::process(), CommandVolume25D::process(), and CommandRANSAC::process().
widgetParent()
QDialog * ccCommandLineInterface::widgetParent () virtual
Returns a (widget) parent (if any is available)
Reimplemented in ccCommandLineParser.
Definition at line 126 of file ecvCommandLineInterface.cpp.
Referenced by CommandOctreeNormal::process(), CommandConvertNormalsToSFs::process(), CommandSubsample::process(), CommandExtractCCs::process(), CommandCurvature::process(), CommandApproxDensity::process(), CommandDensity::process(), CommandSFGradient::process(), CommandRoughness::process(), CommandOrientNormalsMST::process(), CommandSORFilter::process(), CommandSampleMesh::process(), CommandDist::process(), CommandStatTest::process(), CommandICP::process(), CommandMoment::process(), CommandFeature::process(), CommandRasterize::process(), CommandVolume25D::process(), Command3DMASCClassif::process(), CommandCSF::process(), and CommandM3C2::process().
Member Data Documentation
m_addTimestamp
bool ccCommandLineInterface::m_addTimestamp protected
Whether a timestamp should be automatically added to output files or not.
Definition at line 334 of file ecvCommandLineInterface.h.
Referenced by addTimestamp(), ccCommandLineParser::getExportFilename(), and toggleAddTimestamp().
m_autoSaveMode
bool ccCommandLineInterface::m_autoSaveMode protected
Whether files should be automatically saved (after each process) or not.
Definition at line 331 of file ecvCommandLineInterface.h.
Referenced by autoSaveMode(), and toggleAutoSaveMode().
m_clouds
std::vector<CLCloudDesc> ccCommandLineInterface::m_clouds protected
Currently opened point clouds and their filename.
Definition at line 322 of file ecvCommandLineInterface.h.
Referenced by clouds(), ccCommandLineParser::importFile(), ccCommandLineParser::removeClouds(), and ccCommandLineParser::saveClouds().
m_loadingParameters
CLLoadParameters ccCommandLineInterface::m_loadingParameters protected
File loading parameters.
Definition at line 340 of file ecvCommandLineInterface.h.
Referenced by fileLoadingParams(), and ccCommandLineParser::importFile().
m_meshes
std::vector<CLMeshDesc> ccCommandLineInterface::m_meshes protected
Currently opened meshes and their filename.
Definition at line 325 of file ecvCommandLineInterface.h.
Referenced by ccCommandLineParser::importFile(), meshes(), ccCommandLineParser::removeMeshes(), and ccCommandLineParser::saveMeshes().
m_precision
int ccCommandLineInterface::m_precision protected
Default numerical precision for ASCII output.
Definition at line 337 of file ecvCommandLineInterface.h.
Referenced by numericalPrecision(), and setNumericalPrecision().
m_silentMode
bool ccCommandLineInterface::m_silentMode protected
Silent mode.
Definition at line 328 of file ecvCommandLineInterface.h.
Referenced by silentMode(), and toggleSilentMode().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVPluginAPI/include/ecvCommandLineInterface.h
/root/ACloudViewer/libs/CVPluginAPI/src/ecvCommandLineInterface.cpp