ACloudViewer: VtkUtils::ImplicitPlaneWidgetObserver Class Reference
VtkUtils::ImplicitPlaneWidgetObserver Class Reference
#include <implicitplanewidgetobserver.h>
Signals
void originChanged (double *origin)
void normalChanged (double *normal)
Public Member Functions
ImplicitPlaneWidgetObserver (QObject *parent=nullptr)
Public Member Functions inherited from VtkUtils::AbstractWidgetObserver
AbstractWidgetObserver (QObject *parent=0)
virtual ~AbstractWidgetObserver ()
void attach (vtkInteractorObserver *widget)
Protected Member Functions
void Execute (vtkObject *caller, unsigned long eventId, void *callData)
Additional Inherited Members
Protected Attributes inherited from VtkUtils::AbstractWidgetObserver
vtkInteractorObserver * m_widget = nullptr
Detailed Description
Definition at line 14 of file implicitplanewidgetobserver.h.
Constructor & Destructor Documentation
ImplicitPlaneWidgetObserver()
VtkUtils::ImplicitPlaneWidgetObserver::ImplicitPlaneWidgetObserver (QObject * parent = nullptr) explicit
Definition at line 14 of file implicitplanewidgetobserver.cpp.
Member Function Documentation
Execute()
void VtkUtils::ImplicitPlaneWidgetObserver::Execute (vtkObject * caller, unsigned long eventId, void * callData) protected virtual
Implements VtkUtils::AbstractWidgetObserver.
Definition at line 17 of file implicitplanewidgetobserver.cpp.
References normalChanged(), and originChanged().
normalChanged
void VtkUtils::ImplicitPlaneWidgetObserver::normalChanged (double * normal) signal
Referenced by Execute().
originChanged
void VtkUtils::ImplicitPlaneWidgetObserver::originChanged (double * origin) signal
Referenced by Execute().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/implicitplanewidgetobserver.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/implicitplanewidgetobserver.cpp