ACloudViewer: Vector3Tpl< Type > Class Template Reference
Vector3Tpl< Type > Class Template Reference
3D Vector (templated version)
#include <CVGeom.h>
Public Member Functions
Vector3Tpl ()
Default constructor.
Vector3Tpl (Type _x, Type _y, Type _z)
Constructor from a triplet of coordinates.
Vector3Tpl (const Type p[])
Constructor from an array of 3 elements.
Vector3Tpl (const Vector2Tpl< Type > &t2D, Type c)
Constructor from a 2D vector (and a third value)
operator Vector3Tpl< double > () const
Vector3Tpl< double > toDouble () const
Cast operator to a double vector (explicit call version)
Vector3Tpl< float > toFloat () const
Vector3Tpl< PointCoordinateType > toPC () const
Vector3Tpl (const Eigen::Matrix< float, 3, 1 > &v)
Copy Function.
Vector3Tpl (const Eigen::Matrix< double, 3, 1 > &v)
Vector3Tpl & operator= (const Eigen::Matrix< double, 3, 1 > &v)
Assignment Function.
Vector3Tpl & operator= (const Eigen::Matrix< float, 3, 1 > &v)
Vector3Tpl & operator+= (const Eigen::Matrix< double, 3, 1 > &v)
In-place addition operator.
Vector3Tpl & operator-= (const Eigen::Matrix< double, 3, 1 > &v)
In-place subtraction operator.
Vector3Tpl & operator*= (const Eigen::Matrix< double, 3, 1 > &v)
In-place product operator.
Vector3Tpl operator- (const Eigen::Matrix< double, 3, 1 > &v) const
Subtraction operator.
Vector3Tpl operator+ (const Eigen::Matrix< double, 3, 1 > &v) const
Addition operator.
Vector3Tpl operator* (const Eigen::Matrix< double, 3, 1 > &v) const
Cross product operator.
Type operator&& (const Eigen::Matrix< double, 3, 1 > &v) const
Dot product operator.
Type & operator() (unsigned i)
Direct coordinate access.
const Type & operator() (unsigned i) const
Direct coordinate access (const)
Type maxCoeff () const
x,y,z maximum
Type prod () const
x,y,z product
Type dot (const Vector3Tpl &v) const
Dot product.
Vector3Tpl cross (const Vector3Tpl &v) const
Cross product.
Type norm2 () const
Returns vector square norm.
double norm2d () const
Returns vector square norm (forces double precision output)
Type norm () const
Returns vector norm.
double normd () const
Returns vector norm (forces double precision output)
void normalize ()
Sets vector norm to unity.
Vector3Tpl orthogonal () const
Returns a normalized vector which is orthogonal to this one.
Vector3Tpl operator- () const
Inverse operator.
Vector3Tpl & operator+= (const Vector3Tpl &v)
In-place addition operator.
Vector3Tpl & operator-= (const Vector3Tpl &v)
In-place subtraction operator.
Vector3Tpl & operator*= (Type v)
In-place multiplication (by a scalar) operator.
Vector3Tpl & operator/= (Type v)
In-place division (by a scalar) operator.
Vector3Tpl operator+ (const Vector3Tpl &v) const
Addition operator.
Vector3Tpl operator- (const Vector3Tpl &v) const
Subtraction operator.
Vector3Tpl operator* (Type s) const
Multiplication operator.
Vector3Tpl operator/ (Type s) const
Division operator.
Vector3Tpl operator* (const Vector3Tpl &v) const
Cross product operator.
Type operator&& (const Vector3Tpl &v) const
Dot product operator.
Type & operator[] (unsigned i)
Direct coordinate access.
const Type & operator[] (unsigned i) const
Direct coordinate access (const)
Type angle_rad (const Vector3Tpl &v) const
Returns the angle to another vector (in radians - in [0, pi].
double angle_radd (const Vector3Tpl &v) const
Public Member Functions inherited from Tuple3Tpl< Type >
std::size_t rows () const
std::size_t dimensions () const
Type * data ()
const Type * data () const
Tuple3Tpl ()
Default constructor.
Tuple3Tpl (Type a, Type b, Type c)
Constructor from a triplet of values.
Tuple3Tpl (const Type p[])
Constructor from an array of 3 elements.
Tuple3Tpl operator- () const
Inverse operator.
Tuple3Tpl & operator+= (const Tuple3Tpl &v)
In-place addition operator.
Tuple3Tpl & operator-= (const Tuple3Tpl &v)
In-place subtraction operator.
Tuple3Tpl & operator*= (Type v)
In-place multiplication (by a scalar) operator.
Tuple3Tpl & operator/= (Type v)
In-place division (by a scalar) operator.
Tuple3Tpl operator+ (const Tuple3Tpl &v) const
Addition operator.
Tuple3Tpl operator- (const Tuple3Tpl &v) const
Subtraction operator.
Tuple3Tpl operator* (Type s) const
Multiplication operator.
Tuple3Tpl operator/ (Type s) const
Division operator.
Static Public Member Functions
static Vector3Tpl fromArray (const int a[3])
Constructor from an int array.
static Vector3Tpl fromArray (const float a[3])
Constructor from a float array.
static Vector3Tpl fromArray (const double a[3])
Constructor from a double array.
static Vector3Tpl fromArray (const Eigen::Matrix< double, 3, 1 > &a)
Constructor from a Eigen vector.
static Eigen::Matrix< Type, 3, 1 > fromArray (const Vector3Tpl< float > &a)
static Eigen::Matrix< Type, 3, 1 > fromArray (const Vector3Tpl< double > &a)
static std::vector< Eigen::Matrix< double, 3, 1 > > fromArrayContainer (const std::vector< Vector3Tpl< Type >> &container)
static std::vector< Vector3Tpl > fromArrayContainer (const std::vector< Eigen::Matrix< double, 3, 1 >> &container)
static void vdivide (const Type p[], Type s, Type r[])
static void vdivide (Type p[], Type s)
static void vmultiply (const Type p[], Type s, Type r[])
static void vmultiply (Type p[], Type s)
static Type vdot (const Type p[], const Type q[])
static double vdotd (const Type p[], const Type q[])
static void vcross (const Type p[], const Type q[], Type r[])
static void vcopy (const Type p[], Type q[])
static void vset (Type p[], Type s)
static void vset (Type p[], Type x, Type y, Type z)
static void vadd (const Type p[], const Type q[], Type r[])
static void vsubstract (const Type p[], const Type q[], Type r[])
static void vcombination (Type a, const Type p[], Type b, const Type q[], Type r[])
static void vcombination (const Type p[], Type b, const Type q[], Type r[])
static void vnormalize (Type p[])
static Type vnorm2 (const Type p[])
static double vnorm2d (const Type p[])
static Type vdistance2 (const Type p[], const Type q[])
static double vdistance2d (const Type p[], const Type q[])
static Type vnorm (const Type p[])
static double vnormd (const Type p[])
static Type vdistance (const Type p[], const Type q[])
static double vdistanced (const Type p[], const Type q[])
static void vorthogonal (const Type p[], Type q[])
static Type vangle_rad (const Type p[], const Type q[])
static double vangle_radd (const Type p[], const Type q[])
Additional Inherited Members
Public Attributes inherited from Tuple3Tpl< Type >
union {
struct {
Type x
Type y
Type z
}
Type u [3]
};
Detailed Description
template<typename Type>
class Vector3Tpl< Type >
3D Vector (templated version)
Definition at line 223 of file CVGeom.h.
Constructor & Destructor Documentation
Vector3Tpl() [1/6]
template<typename Type > Vector3Tpl< Type >::Vector3Tpl () inline
Default constructor.
Inits vector to (0, 0, 0).
Definition at line 235 of file CVGeom.h.
Referenced by Vector3Tpl< Type >::cross(), Vector3Tpl< Type >::fromArray(), Vector3Tpl< Type >::fromArrayContainer(), Vector3Tpl< Type >::operator*(), Vector3Tpl< Type >::operator+(), Vector3Tpl< Type >::operator-(), and Vector3Tpl< Type >::operator/().
Vector3Tpl() [2/6]
template<typename Type > Vector3Tpl< Type >::Vector3Tpl (Type _x, Type _y, Type _z) inline
Constructor from a triplet of coordinates.
Inits vector to (x,y,z).
Definition at line 240 of file CVGeom.h.
Vector3Tpl() [3/6]
template<typename Type > Vector3Tpl< Type >::Vector3Tpl (const Type p[]) inline explicit
Constructor from an array of 3 elements.
Definition at line 244 of file CVGeom.h.
Vector3Tpl() [4/6]
template<typename Type > Vector3Tpl< Type >::Vector3Tpl (const Vector2Tpl< Type > & t2D, Type c) inline explicit
Constructor from a 2D vector (and a third value)
Definition at line 247 of file CVGeom.h.
Vector3Tpl() [5/6]
template<typename Type > Vector3Tpl< Type >::Vector3Tpl (const Eigen::Matrix< float, 3, 1 > & v) inline
Copy Function.
Definition at line 327 of file CVGeom.h.
Vector3Tpl() [6/6]
template<typename Type > Vector3Tpl< Type >::Vector3Tpl (const Eigen::Matrix< double, 3, 1 > & v) inline
Definition at line 328 of file CVGeom.h.
Member Function Documentation
angle_rad()
template<typename Type > Type Vector3Tpl< Type >::angle_rad (const Vector3Tpl< Type > & v) const inline
Returns the angle to another vector (in radians - in [0, pi].
Definition at line 497 of file CVGeom.h.
References Tuple3Tpl< Type >::u, and Vector3Tpl< Type >::vangle_rad().
angle_radd()
template<typename Type > double Vector3Tpl< Type >::angle_radd (const Vector3Tpl< Type > & v) const inline
Definition at line 498 of file CVGeom.h.
References Tuple3Tpl< Type >::u, and Vector3Tpl< Type >::vangle_radd().
cross()
template<typename Type > Vector3Tpl Vector3Tpl< Type >::cross (const Vector3Tpl< Type > & v) const inline
Cross product.
Definition at line 412 of file CVGeom.h.
References Vector3Tpl< Type >::Vector3Tpl(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by PdmsTools::PdmsObjects::GenericItem::completeOrientation(), ComputeFacetExtensions(), ccCompass::estimateStrain(), qFacets::exportFacets(), ccGLMatrixTpl< T >::FromToRotation(), ccGLMatrixTpl< T >::FromViewDirAndUpDir(), cloudViewer::Grid3D< Type >::intersectWith(), RDBFilter::loadFile(), Vector3Tpl< Type >::operator*(), cloudViewer::Neighbourhood::projectPointsOn2DPlane(), Ray< T >::radialSquareDistance(), Ray< T >::squareDistances(), ccLineation::updateMetadata(), and ccThickness::updateMetadata().
dot()
template<typename Type > Type Vector3Tpl< Type >::dot (const Vector3Tpl< Type > & v) const inline
Dot product.
Definition at line 408 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by qCanupo2DViewDialog::addOrSelectPoint(), FacetsClassifier::CommputeHDistBetweenFacets(), ComputeFacetExtensions(), FastMarchingForFacetExtraction::computeTCoefApprox(), qFacets::createFacets(), Plane::distance(), ccCompass::estimateStructureNormals(), ccTrace::fitPlane(), ccGLMatrixTpl< T >::FromToRotation(), ccKdTreeForFacetExtraction::FuseCells(), ccCompass::importFoliations(), ccCompassImport::importFoliations(), cloudViewer::Grid3D< Type >::intersectWith(), Vector3Tpl< Type >::operator&&(), OrientPointNormalWithCloud(), cloudViewer::Neighbourhood::projectPointsOn2DPlane(), ccLineation::updateMetadata(), and ccThickness::updateMetadata().
fromArray() [1/6]
template<typename Type > static Vector3Tpl Vector3Tpl< Type >::fromArray (const double a[3]) inline static
Constructor from a double array.
Definition at line 278 of file CVGeom.h.
References Vector3Tpl< Type >::Vector3Tpl().
fromArray() [2/6]
template<typename Type > static Vector3Tpl Vector3Tpl< Type >::fromArray (const Eigen::Matrix< double, 3, 1 > & a) inline static
Constructor from a Eigen vector.
Definition at line 284 of file CVGeom.h.
References Vector3Tpl< Type >::Vector3Tpl().
fromArray() [3/6]
template<typename Type > static Vector3Tpl Vector3Tpl< Type >::fromArray (const float a[3]) inline static
Constructor from a float array.
Definition at line 273 of file CVGeom.h.
References Vector3Tpl< Type >::Vector3Tpl().
fromArray() [4/6]
template<typename Type > static Vector3Tpl Vector3Tpl< Type >::fromArray (const int a[3]) inline static
Constructor from an int array.
Definition at line 268 of file CVGeom.h.
References Vector3Tpl< Type >::Vector3Tpl().
Referenced by ccGLMatrixTpl< T >::getColumnAsVec3D(), Vector3Tpl< Type >::toFloat(), and Vector3Tpl< Type >::toPC().
fromArray() [5/6]
template<typename Type > static Eigen::Matrix<Type, 3, 1> Vector3Tpl< Type >::fromArray (const Vector3Tpl< double > & a) inline static
Definition at line 294 of file CVGeom.h.
fromArray() [6/6]
template<typename Type > static Eigen::Matrix<Type, 3, 1> Vector3Tpl< Type >::fromArray (const Vector3Tpl< float > & a) inline static
Definition at line 288 of file CVGeom.h.
fromArrayContainer() [1/2]
template<typename Type > static std::vector<Vector3Tpl> Vector3Tpl< Type >::fromArrayContainer (const std::vector< Eigen::Matrix< double, 3, 1 >> & container) inline static
Definition at line 314 of file CVGeom.h.
References points, and Vector3Tpl< Type >::Vector3Tpl().
fromArrayContainer() [2/2]
template<typename Type > static std::vector<Eigen::Matrix<double, 3, 1> > Vector3Tpl< Type >::fromArrayContainer (const std::vector< Vector3Tpl< Type >> & container) inline static
Definition at line 301 of file CVGeom.h.
References points.
maxCoeff()
template<typename Type > Type Vector3Tpl< Type >::maxCoeff () const inline
x,y,z maximum
Definition at line 402 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
norm()
template<typename Type > Type Vector3Tpl< Type >::norm () const inline
Returns vector norm.
Definition at line 424 of file CVGeom.h.
References Vector3Tpl< Type >::norm2d().
Referenced by qCanupo2DViewDialog::addOrSelectPoint(), ComputePMUncertainty(), ccPointPair::drawMeOnly(), cloudViewer::BoundingBoxTpl< T >::getDiagNorm(), cloudViewer::BoundingBoxTpl< T >::minDistTo(), Plane::setCoefficients(), and qAnimationDlg::smoothTrajectory().
norm2()
template<typename Type > Type Vector3Tpl< Type >::norm2 () const inline
Returns vector square norm.
Definition at line 417 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by qCanupo2DViewDialog::addOrSelectPoint(), ComputeFacetExtensions(), ComputePMUncertainty(), FastMarchingForFacetExtraction::computeTCoefApprox(), ccCompass::estimateStrain(), qFacets::exportFacets(), GetGlobalShift(), ccGLMatrixTpl< T >::getParameters(), ccTrace::insertWaypoint(), cloudViewer::Grid3D< Type >::intersectWith(), ccGLMatrixTpl< T >::invert(), SimpleBinFilter::loadFile(), LASFWFFilter::loadFile(), LasIOFilter::loadFile(), LASFilter::loadFile(), OrientPointNormalWithCloud(), SimpleBinFilter::saveToFile(), and ccGLMatrixTpl< T >::zRotation().
norm2d()
template<typename Type > double Vector3Tpl< Type >::norm2d () const inline
Returns vector square norm (forces double precision output)
Definition at line 419 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by Vector3Tpl< Type >::norm(), Vector3Tpl< Type >::normalize(), Vector3Tpl< Type >::normd(), Ray< T >::radialSquareDistance(), SaveScan(), Ray< T >::squareDistances(), and Ray< T >::squareDistanceToOrigin().
normalize()
template<typename Type > void Vector3Tpl< Type >::normalize () inline
Sets vector norm to unity.
Definition at line 428 of file CVGeom.h.
References Vector3Tpl< Type >::norm2d().
Referenced by PdmsTools::PdmsObjects::GenericItem::completeOrientation(), ComputeCorePointNormal(), ComputeFacetExtensions(), FastMarchingForFacetExtraction::computeTCoefApprox(), ccCompass::estimateStrain(), qFacets::exportFacets(), ccGLMatrixTpl< T >::FromViewDirAndUpDir(), qM3C2Tools::GuessBestParams(), StereogramWidget::init(), ccGLMatrixTpl< T >::initFromParameters(), LoadScan(), qM3C2Normals::MakeNormalsHorizontal(), cloudViewer::Neighbourhood::projectPointsOn2DPlane(), Ray< T >::Ray(), MascaretFilter::saveToFile(), ccLineation::updateMetadata(), and ccThickness::updateMetadata().
normd()
template<typename Type > double Vector3Tpl< Type >::normd () const inline
Returns vector norm (forces double precision output)
Definition at line 426 of file CVGeom.h.
References Vector3Tpl< Type >::norm2d().
Referenced by cloudViewer::BoundingBoxTpl< T >::getDiagNormd().
operator Vector3Tpl< double >()
template<typename Type > Vector3Tpl< Type >::operator Vector3Tpl< double > () const inline
Cast operator to a double vector (no loss of precision, can be done silently)
Definition at line 252 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator&&() [1/2]
template<typename Type > Type Vector3Tpl< Type >::operator&& (const Eigen::Matrix< double, 3, 1 > & v) const inline
Dot product operator.
Definition at line 385 of file CVGeom.h.
References Vector3Tpl< Type >::dot().
operator&&() [2/2]
template<typename Type > Type Vector3Tpl< Type >::operator&& (const Vector3Tpl< Type > & v) const inline
Dot product operator.
Definition at line 491 of file CVGeom.h.
References Vector3Tpl< Type >::dot().
operator()() [1/2]
template<typename Type > Type& Vector3Tpl< Type >::operator() (unsigned i) inline
Direct coordinate access.
Definition at line 397 of file CVGeom.h.
References Tuple3Tpl< Type >::u.
operator()() [2/2]
template<typename Type > const Type& Vector3Tpl< Type >::operator() (unsigned i) const inline
Direct coordinate access (const)
Definition at line 399 of file CVGeom.h.
References Tuple3Tpl< Type >::u.
operator*() [1/3]
template<typename Type > Vector3Tpl Vector3Tpl< Type >::operator* (const Eigen::Matrix< double, 3, 1 > & v) const inline
Cross product operator.
Definition at line 380 of file CVGeom.h.
References Vector3Tpl< Type >::cross().
operator*() [2/3]
template<typename Type > Vector3Tpl Vector3Tpl< Type >::operator* (const Vector3Tpl< Type > & v) const inline
Cross product operator.
Definition at line 489 of file CVGeom.h.
References Vector3Tpl< Type >::cross().
operator*() [3/3]
template<typename Type > Vector3Tpl Vector3Tpl< Type >::operator* (Type s) const inline
Multiplication operator.
Definition at line 481 of file CVGeom.h.
References Vector3Tpl< Type >::Vector3Tpl(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator*=() [1/2]
template<typename Type > Vector3Tpl& Vector3Tpl< Type >::operator*= (const Eigen::Matrix< double, 3, 1 > & v) inline
In-place product operator.
Definition at line 360 of file CVGeom.h.
operator*=() [2/2]
template<typename Type > Vector3Tpl& Vector3Tpl< Type >::operator*= (Type v) inline
In-place multiplication (by a scalar) operator.
Definition at line 459 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator+() [1/2]
template<typename Type > Vector3Tpl Vector3Tpl< Type >::operator+ (const Eigen::Matrix< double, 3, 1 > & v) const inline
Addition operator.
Definition at line 373 of file CVGeom.h.
References Vector3Tpl< Type >::Vector3Tpl(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator+() [2/2]
template<typename Type > Vector3Tpl Vector3Tpl< Type >::operator+ (const Vector3Tpl< Type > & v) const inline
Addition operator.
Definition at line 473 of file CVGeom.h.
References Vector3Tpl< Type >::Vector3Tpl(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator+=() [1/2]
template<typename Type > Vector3Tpl& Vector3Tpl< Type >::operator+= (const Eigen::Matrix< double, 3, 1 > & v) inline
In-place addition operator.
Definition at line 345 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator+=() [2/2]
template<typename Type > Vector3Tpl& Vector3Tpl< Type >::operator+= (const Vector3Tpl< Type > & v) inline
In-place addition operator.
Definition at line 445 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator-() [1/3]
template<typename Type > Vector3Tpl Vector3Tpl< Type >::operator- () const inline
Inverse operator.
Definition at line 440 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator-() [2/3]
template<typename Type > Vector3Tpl Vector3Tpl< Type >::operator- (const Eigen::Matrix< double, 3, 1 > & v) const inline
Subtraction operator.
Definition at line 366 of file CVGeom.h.
References Vector3Tpl< Type >::Vector3Tpl(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator-() [3/3]
template<typename Type > Vector3Tpl Vector3Tpl< Type >::operator- (const Vector3Tpl< Type > & v) const inline
Subtraction operator.
Definition at line 477 of file CVGeom.h.
References Vector3Tpl< Type >::Vector3Tpl(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator-=() [1/2]
template<typename Type > Vector3Tpl& Vector3Tpl< Type >::operator-= (const Eigen::Matrix< double, 3, 1 > & v) inline
In-place subtraction operator.
Definition at line 352 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator-=() [2/2]
template<typename Type > Vector3Tpl& Vector3Tpl< Type >::operator-= (const Vector3Tpl< Type > & v) inline
In-place subtraction operator.
Definition at line 452 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator/()
template<typename Type > Vector3Tpl Vector3Tpl< Type >::operator/ (Type s) const inline
Division operator.
Definition at line 485 of file CVGeom.h.
References Vector3Tpl< Type >::Vector3Tpl(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator/=()
template<typename Type > Vector3Tpl& Vector3Tpl< Type >::operator/= (Type v) inline
In-place division (by a scalar) operator.
Definition at line 466 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator=() [1/2]
template<typename Type > Vector3Tpl& Vector3Tpl< Type >::operator= (const Eigen::Matrix< double, 3, 1 > & v) inline
Assignment Function.
Definition at line 331 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator=() [2/2]
template<typename Type > Vector3Tpl& Vector3Tpl< Type >::operator= (const Eigen::Matrix< float, 3, 1 > & v) inline
Definition at line 337 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator[]() [1/2]
template<typename Type > Type& Vector3Tpl< Type >::operator[] (unsigned i) inline
Direct coordinate access.
Definition at line 493 of file CVGeom.h.
References Tuple3Tpl< Type >::u.
operator[]() [2/2]
template<typename Type > const Type& Vector3Tpl< Type >::operator[] (unsigned i) const inline
Direct coordinate access (const)
Definition at line 495 of file CVGeom.h.
References Tuple3Tpl< Type >::u.
orthogonal()
template<typename Type > Vector3Tpl Vector3Tpl< Type >::orthogonal () const inline
Returns a normalized vector which is orthogonal to this one.
Definition at line 433 of file CVGeom.h.
References Tuple3Tpl< Type >::u, and Vector3Tpl< Type >::vorthogonal().
Referenced by PdmsTools::PdmsObjects::GenericItem::completeOrientation().
prod()
template<typename Type > Type Vector3Tpl< Type >::prod () const inline
x,y,z product
Definition at line 406 of file CVGeom.h.
References abs(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by cloudViewer::BoundingBoxTpl< T >::volume().
toDouble()
template<typename Type > Vector3Tpl<double> Vector3Tpl< Type >::toDouble () const inline
Cast operator to a double vector (explicit call version)
Definition at line 255 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by DecodeCamera(), ccShiftedObject::toGlobal3d(), ccShiftedObject::toLocal3d(), and ccShiftedObject::toLocal3pc().
toFloat()
template<typename Type > Vector3Tpl<float> Vector3Tpl< Type >::toFloat () const inline
Cast operator to a float vector (potential loss of precision, should be called explicitely)
Definition at line 258 of file CVGeom.h.
References Vector3Tpl< Type >::fromArray(), and Tuple3Tpl< Type >::u.
toPC()
template<typename Type > Vector3Tpl<PointCoordinateType> Vector3Tpl< Type >::toPC () const inline
Cast operator to the default vector type (potential loss of precision, should be called explicitely)
Definition at line 263 of file CVGeom.h.
References Vector3Tpl< Type >::fromArray(), and Tuple3Tpl< Type >::u.
Referenced by cloudViewer::PointProjectionTools::Transformation::apply(), and ccShiftedObject::toLocal3pc().
vadd()
template<typename Type > static void Vector3Tpl< Type >::vadd (const Type p[], const Type q[], Type r[]) inline static
Definition at line 544 of file CVGeom.h.
vangle_rad()
template<typename Type > static Type Vector3Tpl< Type >::vangle_rad (const Type p[], const Type q[]) inline static
Definition at line 624 of file CVGeom.h.
References max(), min(), Vector3Tpl< Type >::vdot(), and Vector3Tpl< Type >::vnorm().
Referenced by Vector3Tpl< Type >::angle_rad().
vangle_radd()
template<typename Type > static double Vector3Tpl< Type >::vangle_radd (const Type p[], const Type q[]) inline static
Definition at line 635 of file CVGeom.h.
References max(), min(), Vector3Tpl< Type >::vdotd(), and Vector3Tpl< Type >::vnormd().
Referenced by Vector3Tpl< Type >::angle_radd().
vcombination() [1/2]
template<typename Type > static void Vector3Tpl< Type >::vcombination (const Type p[], Type b, const Type q[], Type r[]) inline static
Definition at line 561 of file CVGeom.h.
vcombination() [2/2]
template<typename Type > static void Vector3Tpl< Type >::vcombination (Type a, const Type p[], Type b, const Type q[], Type r[]) inline static
Definition at line 555 of file CVGeom.h.
vcopy()
template<typename Type > static void Vector3Tpl< Type >::vcopy (const Type p[], Type q[]) inline static
Definition at line 533 of file CVGeom.h.
vcross()
template<typename Type > static void Vector3Tpl< Type >::vcross (const Type p[], const Type q[], Type r[]) inline static
Definition at line 528 of file CVGeom.h.
vdistance()
template<typename Type > static Type Vector3Tpl< Type >::vdistance (const Type p[], const Type q[]) inline static
Definition at line 598 of file CVGeom.h.
References Vector3Tpl< Type >::vdistance2().
vdistance2()
template<typename Type > static Type Vector3Tpl< Type >::vdistance2 (const Type p[], const Type q[]) inline static
Definition at line 581 of file CVGeom.h.
Referenced by Vector3Tpl< Type >::vdistance().
vdistance2d()
template<typename Type > static double Vector3Tpl< Type >::vdistance2d (const Type p[], const Type q[]) inline static
Definition at line 586 of file CVGeom.h.
Referenced by Vector3Tpl< Type >::vdistanced().
vdistanced()
template<typename Type > static double Vector3Tpl< Type >::vdistanced (const Type p[], const Type q[]) inline static
Definition at line 601 of file CVGeom.h.
References Vector3Tpl< Type >::vdistance2d().
vdivide() [1/2]
template<typename Type > static void Vector3Tpl< Type >::vdivide (const Type p[], Type s, Type r[]) inline static
Definition at line 500 of file CVGeom.h.
Referenced by Vector3Tpl< Type >::vnormalize().
vdivide() [2/2]
template<typename Type > static void Vector3Tpl< Type >::vdivide (Type p[], Type s) inline static
Definition at line 505 of file CVGeom.h.
vdot()
template<typename Type > static Type Vector3Tpl< Type >::vdot (const Type p[], const Type q[]) inline static
Definition at line 520 of file CVGeom.h.
Referenced by Vector3Tpl< Type >::vangle_rad().
vdotd()
template<typename Type > static double Vector3Tpl< Type >::vdotd (const Type p[], const Type q[]) inline static
Definition at line 523 of file CVGeom.h.
Referenced by Vector3Tpl< Type >::vangle_radd().
vmultiply() [1/2]
template<typename Type > static void Vector3Tpl< Type >::vmultiply (const Type p[], Type s, Type r[]) inline static
Definition at line 510 of file CVGeom.h.
vmultiply() [2/2]
template<typename Type > static void Vector3Tpl< Type >::vmultiply (Type p[], Type s) inline static
Definition at line 515 of file CVGeom.h.
vnorm()
template<typename Type > static Type Vector3Tpl< Type >::vnorm (const Type p[]) inline static
Definition at line 594 of file CVGeom.h.
References Vector3Tpl< Type >::vnorm2().
Referenced by Vector3Tpl< Type >::vangle_rad().
vnorm2()
template<typename Type > static Type Vector3Tpl< Type >::vnorm2 (const Type p[]) inline static
Definition at line 573 of file CVGeom.h.
Referenced by Vector3Tpl< Type >::vnorm(), and Vector3Tpl< Type >::vnormalize().
vnorm2d()
template<typename Type > static double Vector3Tpl< Type >::vnorm2d (const Type p[]) inline static
Definition at line 576 of file CVGeom.h.
Referenced by Vector3Tpl< Type >::vnormd().
vnormalize()
template<typename Type > static void Vector3Tpl< Type >::vnormalize (Type p[]) inline static
Definition at line 569 of file CVGeom.h.
References Vector3Tpl< Type >::vdivide(), and Vector3Tpl< Type >::vnorm2().
Referenced by Vector3Tpl< Type >::vorthogonal().
vnormd()
template<typename Type > static double Vector3Tpl< Type >::vnormd (const Type p[]) inline static
Definition at line 595 of file CVGeom.h.
References Vector3Tpl< Type >::vnorm2d().
Referenced by Vector3Tpl< Type >::vangle_radd().
vorthogonal()
template<typename Type > static void Vector3Tpl< Type >::vorthogonal (const Type p[], Type q[]) inline static
Definition at line 605 of file CVGeom.h.
References abs(), and Vector3Tpl< Type >::vnormalize().
Referenced by Vector3Tpl< Type >::orthogonal().
vset() [1/2]
template<typename Type > static void Vector3Tpl< Type >::vset (Type p[], Type s) inline static
Definition at line 538 of file CVGeom.h.
vset() [2/2]
template<typename Type > static void Vector3Tpl< Type >::vset (Type p[], Type x, Type y, Type z) inline static
Definition at line 539 of file CVGeom.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
vsubstract()
template<typename Type > static void Vector3Tpl< Type >::vsubstract (const Type p[], const Type q[], Type r[]) inline static
Definition at line 550 of file CVGeom.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/CVGeom.h