ACloudViewer: Plane Class Reference
Plane Class Reference
#include <ecvFrustum.h>
Public Member Functions
Plane ()
virtual ~Plane ()=default
void setCoefficients (float a, float b, float c, float d)
float distance (const CCVector3f &p) const
Public Attributes
CCVector3f normal
float constCoef
Detailed Description
Definition at line 16 of file ecvFrustum.h.
Constructor & Destructor Documentation
Plane()
Plane::Plane () inline
Definition at line 18 of file ecvFrustum.h.
~Plane()
virtual Plane::~Plane () virtual default
Member Function Documentation
distance()
float Plane::distance (const CCVector3f & p) const inline
Definition at line 37 of file ecvFrustum.h.
References constCoef, Vector3Tpl< Type >::dot(), and normal.
setCoefficients()
void Plane::setCoefficients (float a, float b, float c, float d) inline
Definition at line 22 of file ecvFrustum.h.
References constCoef, Vector3Tpl< Type >::norm(), and normal.
Referenced by Frustum::initfromMPMatrix().
Member Data Documentation
constCoef
float Plane::constCoef
Definition at line 43 of file ecvFrustum.h.
Referenced by distance(), and setCoefficients().
normal
CCVector3f Plane::normal
Definition at line 42 of file ecvFrustum.h.
Referenced by distance(), and setCoefficients().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvFrustum.h