ACloudViewer: cloudViewer::visualization::GuiSettingsView Class Reference
cloudViewer::visualization::GuiSettingsView Class Reference
#include <GuiSettingsView.h>
Public Member Functions
GuiSettingsView (GuiSettingsModel &model, const gui::Theme &theme, const std::string &resource_path, std::function< void(const char *)> on_load_ibl)
void ShowFileMaterialEntry (bool show)
void EnableEstimateNormals (bool enable)
void Update ()
Public Member Functions inherited from cloudViewer::visualization::gui::Vert
Vert ()
Vert (int spacing, const Margins &margins=Margins())
Vert (int spacing, const Margins &margins, const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Vert ()
int GetPreferredWidth () const
void SetPreferredWidth (int w)
Public Member Functions inherited from cloudViewer::visualization::gui::Layout1D
Layout1D (Dir dir, int spacing, const Margins &margins, const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Layout1D ()
int GetSpacing () const
const Margins & GetMargins () const
void SetSpacing (int spacing)
void SetMargins (const Margins &margins)
Size CalcPreferredSize (const LayoutContext &context, const Constraints &constraints) const override
void Layout (const LayoutContext &context) override
void AddFixed (int size)
Adds a fixed number of pixels after the previously added widget.
void AddStretch ()
Public Member Functions inherited from cloudViewer::visualization::gui::Widget
Widget ()
Widget (const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Widget ()
virtual void AddChild (std::shared_ptr< Widget > child)
virtual const std::vector< std::shared_ptr< Widget > > GetChildren () const
virtual const Rect & GetFrame () const
Returns the frame size in pixels.
virtual void SetFrame (const Rect &f)
virtual const Color & GetBackgroundColor () const
virtual bool IsDefaultBackgroundColor () const
virtual void SetBackgroundColor (const Color &color)
virtual bool IsVisible () const
virtual void SetVisible (bool vis)
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
virtual void SetTooltip (const char *text)
virtual const char * GetTooltip () const
virtual Size CalcMinimumSize (const LayoutContext &context) const
virtual DrawResult Draw (const DrawContext &context)
virtual EventResult Mouse (const MouseEvent &e)
virtual EventResult Key (const KeyEvent &e)
virtual DrawResult Tick (const TickEvent &e)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::gui::Layout1D
enum Dir { VERT , HORIZ }
Public Types inherited from cloudViewer::visualization::gui::Widget
enum class DrawResult { NONE , REDRAW , RELAYOUT }
enum class EventResult { IGNORED , CONSUMED , DISCARD }
Static Public Member Functions inherited from cloudViewer::visualization::gui::Vert
static std::shared_ptr< Layout1D::Fixed > MakeFixed (int size)
static std::shared_ptr< Layout1D::Stretch > MakeStretch ()
Static Public Member Functions inherited from cloudViewer::visualization::gui::Layout1D
static void debug_PrintPreferredSizes (Layout1D *layout, const LayoutContext &context, const Constraints &constraints, int depth=0)
Static Public Attributes inherited from cloudViewer::visualization::gui::Widget
static constexpr int DIM_GROW = 10000
Protected Member Functions inherited from cloudViewer::visualization::gui::Layout1D
int GetMinorAxisPreferredSize () const
void SetMinorAxisPreferredSize (int size)
Margins & GetMutableMargins ()
Protected Member Functions inherited from cloudViewer::visualization::gui::Widget
void DrawImGuiPushEnabledState ()
void DrawImGuiPopEnabledState ()
void DrawImGuiTooltip ()
Detailed Description
Definition at line 32 of file GuiSettingsView.h.
Constructor & Destructor Documentation
GuiSettingsView()
cloudViewer::visualization::GuiSettingsView::GuiSettingsView (GuiSettingsModel & model, const gui::Theme & theme, const std::string & resource_path, std::function< void(const char *)> on_load_ibl)
Definition at line 40 of file GuiSettingsView.cpp.
References cloudViewer::visualization::gui::Widget::AddChild(), cloudViewer::visualization::gui::Layout1D::AddFixed(), cloudViewer::utility::ceil(), color, cloudViewer::visualization::GuiSettingsModel::CUSTOM_IBL, cloudViewer::visualization::CUSTOM_LIGHTING, cloudViewer::visualization::GuiSettingsModel::DEFAULT_IBL, cloudViewer::visualization::GuiSettingsModel::EstimateNormalsClicked(), cloudViewer::visualization::gui::Color::GetBlue(), cloudViewer::visualization::GuiSettingsModel::GetCurrentMaterials(), cloudViewer::utility::filesystem::GetFileNameWithoutDirectory(), cloudViewer::visualization::gui::Color::GetGreen(), cloudViewer::visualization::GuiSettingsModel::GetLighting(), cloudViewer::visualization::gui::Color::GetRed(), cloudViewer::visualization::GuiSettingsModel::LightingProfile::ibl_enabled, cloudViewer::visualization::GuiSettingsModel::LightingProfile::ibl_intensity, cloudViewer::visualization::gui::Slider::INT, cloudViewer::visualization::GuiSettingsModel::lighting_profiles_, cloudViewer::utility::filesystem::ListFilesInDirectory(), cloudViewer::visualization::GuiSettingsModel::Materials::lit, cloudViewer::visualization::MakeSlider(), name, cloudViewer::visualization::GuiSettingsModel::prefab_materials_, cloudViewer::visualization::GuiSettingsModel::ResetColors(), cloudViewer::visualization::GuiSettingsModel::SetBackgroundColor(), cloudViewer::visualization::GuiSettingsModel::SetBasicMode(), cloudViewer::visualization::GuiSettingsModel::SetCurrentMaterialColor(), cloudViewer::visualization::GuiSettingsModel::SetCustomLighting(), cloudViewer::visualization::GuiSettingsModel::SetLightingProfile(), cloudViewer::visualization::GuiSettingsModel::SetLitMaterial(), cloudViewer::visualization::gui::Layout1D::SetMargins(), cloudViewer::visualization::GuiSettingsModel::SetMaterialType(), cloudViewer::visualization::GuiSettingsModel::SetPointSize(), cloudViewer::visualization::GuiSettingsModel::SetShowAxes(), cloudViewer::visualization::GuiSettingsModel::SetShowGround(), cloudViewer::visualization::GuiSettingsModel::SetShowSkybox(), cloudViewer::visualization::GuiSettingsModel::SetSunFollowsCamera(), cloudViewer::visualization::GuiSettingsModel::SetWireframeMode(), size, cloudViewer::visualization::GuiSettingsModel::LightingProfile::sun_color, cloudViewer::visualization::GuiSettingsModel::LightingProfile::sun_dir, cloudViewer::visualization::GuiSettingsModel::LightingProfile::sun_enabled, cloudViewer::visualization::GuiSettingsModel::LightingProfile::sun_intensity, theme, and Update().
Member Function Documentation
EnableEstimateNormals()
void cloudViewer::visualization::GuiSettingsView::EnableEstimateNormals (bool enable)
Definition at line 343 of file GuiSettingsView.cpp.
ShowFileMaterialEntry()
void cloudViewer::visualization::GuiSettingsView::ShowFileMaterialEntry (bool show)
Definition at line 325 of file GuiSettingsView.cpp.
References cloudViewer::visualization::GuiSettingsModel::DEFAULT_MATERIAL_NAME, and cloudViewer::visualization::GuiSettingsModel::MATERIAL_FROM_FILE_NAME.
Update()
void cloudViewer::visualization::GuiSettingsView::Update ()
Definition at line 347 of file GuiSettingsView.cpp.
References cloudViewer::visualization::CUSTOM_LIGHTING, cloudViewer::visualization::GuiSettingsModel::DEFAULT_MATERIAL_NAME, cloudViewer::visualization::GuiSettingsModel::GetBackgroundColor(), cloudViewer::visualization::GuiSettingsModel::GetCurrentMaterials(), cloudViewer::visualization::GuiSettingsModel::GetDisplayingPointClouds(), cloudViewer::visualization::GuiSettingsModel::GetLighting(), cloudViewer::visualization::GuiSettingsModel::GetMaterialType(), cloudViewer::visualization::GuiSettingsModel::GetShowAxes(), cloudViewer::visualization::GuiSettingsModel::GetShowSkybox(), cloudViewer::visualization::GuiSettingsModel::GetUserHasChangedColor(), cloudViewer::visualization::GuiSettingsModel::GetUserHasCustomizedLighting(), and LogWarning.
Referenced by GuiSettingsView().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/GuiSettingsView.h
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/GuiSettingsView.cpp