ACloudViewer: FastGlobalRegistrationFilter Class Reference
FastGlobalRegistrationFilter Class Reference
#include <FastGlobalRegistrationFilter.h>
Public Member Functions
FastGlobalRegistrationFilter ()
~FastGlobalRegistrationFilter () override
Public Member Functions inherited from BasePclModule
BasePclModule (PclModuleDescription desc=PclModuleDescription(), ccPluginInterface *parent_plugin=0)
Default constructor.
QAction * getAction ()
Get the action associated with the button used in menu and toolbar creation.
QString getStatusTip () const
Returns the status tip.
QString getModuleName () const
Returns the name of the filter.
QString getEntryName () const
Returns the entry name.
QIcon getIcon () const
Returns the icon associated with the button.
void setShowProgressBar (bool status)
Sets whether to show a progressbar while computing or not.
std::vector< std::string > getSelectedAvailableScalarFields ()
ccPointCloud * getSelectedEntityAsCCPointCloud () const
Returns the first selected entity as a ccPointCloud.
ccHObject * getSelectedEntityAsCCHObject () const
Returns the first selected entity as a ccHObject.
ccHObject::Container getSelectedThatHaveMetaData (const QString key) const
Get selected object that also have the provided metadata key.
void getAllEntitiesOfType (CV_CLASS_ENUM type, ccHObject::Container &entities)
Returns all the objects in db tree of type "type".
void getAllEntitiesThatHaveMetaData (QString key, ccHObject::Container &entities)
void getSelectedEntitiesThatAreCCPointCloud (ccHObject::Container &entities)
get all entities that are selected and that also are cc_point_cloud
void getSelectedEntitiesThatAre (CV_CLASS_ENUM kind, ccHObject::Container &entities)
int hasSelectedRGB ()
Returns 1 if the first selected entity has RGB info.
int hasSelectedScalarField ()
Returns 1 if the first selected entity has at least one scalar field.
int hasSelectedScalarField (std::string field_name)
int isFirstSelectedCcPointCloud ()
Returns 1 if the first selected object is a ccPointCloud.
virtual void updateSelectedEntities (const ccHObject::Container &selectedEntities)
Updates the internal copy of selected entities.
void setMainAppInterface (ecvMainAppInterface *app)
Sets associated CC application interface (to access DB)
ecvMainAppInterface * getMainAppInterface ()
ccPluginInterface * getParentPlugin () const
Returns the associated parent plugin interface.
Protected Member Functions
virtual int compute () override
Performs the actual filter job.
virtual void getParametersFromDialog () override
Collects parameters from the filter dialog (if openDialog is successful)
virtual int checkSelected () override
Checks if current selection is compliant with the filter.
virtual QString getErrorMessage (int errorCode) override
Returns the error message corresponding to a given error code.
Protected Member Functions inherited from BasePclModule
virtual int openInputDialog ()
virtual int openOutputDialog ()
virtual int checkParameters ()
virtual int start ()
Starts computation.
virtual void initAction ()
Initializes the corresponding action.
void throwError (int errCode)
Protected Attributes
std::vector< ccPointCloud * > m_alignedClouds
ccPointCloud * m_referenceCloud
double m_featureRadius
Protected Attributes inherited from BasePclModule
QAction * m_action
Forces the Ui to be updated.
ccHObject::Container m_selected
Pointer to the main window.
PclModuleDescription m_desc
Associated dialog.
ecvMainAppInterface * m_app
Associated application interface.
ccPluginInterface * m_parent_plugin
associated parent plugin of the filter
bool m_show_progress
Do we want to show a progress bar when the filter works?
Additional Inherited Members
Signals inherited from BasePclModule
void entityHasChanged (ccHObject *)
Signal emitted when an entity is (visually) modified.
void newEntity (ccHObject *)
Signal emitted when a new entity is created by the filter.
void newErrorMessage (QString)
Signal emitted when a new error message is produced.
Protected Slots inherited from BasePclModule
int performAction ()
Returns is called when the dialog window is accepted.
Detailed Description
Filter based on "Q.-Y. Zhou, J. Park, and V. Koltun, Fast Global Registration, ECCV, 2016." See https://github.com/isl-org/FastGlobalRegistration
Definition at line 37 of file FastGlobalRegistrationFilter.h.
Constructor & Destructor Documentation
FastGlobalRegistrationFilter()
FastGlobalRegistrationFilter::FastGlobalRegistrationFilter ()
Definition at line 37 of file FastGlobalRegistrationFilter.cpp.
~FastGlobalRegistrationFilter()
FastGlobalRegistrationFilter::~FastGlobalRegistrationFilter () override
Definition at line 48 of file FastGlobalRegistrationFilter.cpp.
Member Function Documentation
checkSelected()
int FastGlobalRegistrationFilter::checkSelected () override protected virtual
Checks if current selection is compliant with the filter.
If not, an error is returned and computation stops. By default, baseclass method simply checks that selection is composed of one and only one ccPointCloud. This method should be overridden if necessary.
Returns
1 if selection is compliant (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 62 of file FastGlobalRegistrationFilter.cpp.
References BasePclModule::m_selected, and CV_TYPES::POINT_CLOUD.
compute()
int FastGlobalRegistrationFilter::compute () override protected virtual
Performs the actual filter job.
This method MUST be re-implemented by derived filter
Returns
1 if successful (error code otherwise)
Implements BasePclModule.
Definition at line 189 of file FastGlobalRegistrationFilter.cpp.
References fgr::CApp::AdvancedMatching(), ComputeFeatures(), ConverFromTo(), ccGLMatrixTpl< T >::data(), fgr::CApp::GetOutputTrans(), ccPointCloud::hasNormals(), fgr::CApp::LoadFeature(), m_alignedClouds, m_featureRadius, m_referenceCloud, fgr::CApp::NormalizePoints(), fgr::CApp::OptimizePairwise(), CVLog::Print(), ccGLMatrixTpl< T >::toString(), and CVLog::Warning().
getErrorMessage()
QString FastGlobalRegistrationFilter::getErrorMessage (int errorCode) override protected virtual
Returns the error message corresponding to a given error code.
Each filter have a set of possible error message to be used given bt getFilterErrorMessage() Baseclass implementation provides some generic messages.
Note
These messages can be replaced by re-implementing this method and handling the same codes BEFORE calling the baseclass method
Reimplemented from BasePclModule.
Definition at line 50 of file FastGlobalRegistrationFilter.cpp.
References BasePclModule::getErrorMessage(), and NoNormals.
getParametersFromDialog()
void FastGlobalRegistrationFilter::getParametersFromDialog () override protected virtual
Collects parameters from the filter dialog (if openDialog is successful)
Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Reimplemented from BasePclModule.
Definition at line 145 of file FastGlobalRegistrationFilter.cpp.
References FastGlobalRegistrationDialog::getFeatureRadius(), ecvMainAppInterface::getMainWindow(), FastGlobalRegistrationDialog::getReferenceCloud(), ccPointCloud::hasNormals(), m_alignedClouds, BasePclModule::m_app, m_featureRadius, m_referenceCloud, BasePclModule::m_selected, CV_TYPES::POINT_CLOUD, ccPointCloud::reserve(), FastGlobalRegistrationDialog::saveParameters(), and ccHObjectCaster::ToPointCloud().
Member Data Documentation
m_alignedClouds
std::vector<ccPointCloud*> FastGlobalRegistrationFilter::m_alignedClouds protected
Definition at line 50 of file FastGlobalRegistrationFilter.h.
Referenced by compute(), and getParametersFromDialog().
m_featureRadius
double FastGlobalRegistrationFilter::m_featureRadius protected
Definition at line 52 of file FastGlobalRegistrationFilter.h.
Referenced by compute(), and getParametersFromDialog().
m_referenceCloud
ccPointCloud* FastGlobalRegistrationFilter::m_referenceCloud protected
Definition at line 51 of file FastGlobalRegistrationFilter.h.
Referenced by compute(), and getParametersFromDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/FastGlobalRegistrationFilter.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/FastGlobalRegistrationFilter.cpp