ACloudViewer: DistanceMapGenerationDlg Class Reference
DistanceMapGenerationDlg Class Reference
Dialog for generating a distance map (surface of revolution)
#include <distanceMapGenerationDlg.h>
Public Types
enum ANGULAR_UNIT { ANG_DEG , ANG_RAD , ANG_GRAD }
Angular units.
enum ProjectionMode { PROJ_CYLINDRICAL , PROJ_CONICAL }
Projection mode.
Public Member Functions
DistanceMapGenerationDlg (ccPointCloud *cloud, ccScalarField *sf, ccPolyline *polyline, ecvMainAppInterface *app=0)
Default constructor.
virtual ~DistanceMapGenerationDlg ()
Default destructor.
ANGULAR_UNIT getAngularUnit () const
Returns selected angular unit.
QString getAngularUnitString () const
Returns selected angular unit as a string.
QString getCondensedAngularUnitString () const
Returns selected angular unit as a condensed string.
QString getHeightUnitString () const
Returns height unit.
DistanceMapGenerationTool::FillStrategyType getFillingStrategy () const
Returns the grid filling strategy.
DistanceMapGenerationTool::EmptyCellFillOption getEmptyCellFillingOption () const
Returns the empty cells filling option.
ProjectionMode getProjectionMode () const
Returns current projection mode.
void getGridXValues (double &minX, double &maxX, double &step, ANGULAR_UNIT unit=ANG_RAD) const
Returns the current 'X' parameters.
void getGridYValues (double &minY, double &maxY, double &step, ANGULAR_UNIT unit=ANG_RAD) const
Returns the current 'Y' parameters.
double getScaleYStep (ANGULAR_UNIT unit=ANG_RAD) const
Returns scale 'Y' step (current unit)
Protected Slots
void projectionModeChanged (int)
void angularUnitChanged (int)
void updateGridSteps ()
void updateProfileRevolDim (int)
void updateProfileOrigin ()
void colorScaleChanged (int)
void spawnColorScaleEditor ()
void updateHeightUnits ()
void exportMapAsCloud ()
void exportMapAsMesh ()
void exportMapAsGrid ()
void exportMapAsImage ()
void exportProfilesAsDXF ()
void loadOverlaySymbols ()
void clearOverlaySymbols ()
void overlaySymbolsSizeChanged (int)
void overlaySymbolsColorChanged ()
void overlayGridColorChanged ()
void labelFontSizeChanged (int)
void labelPrecisionChanged (int)
void baseRadiusChanged (double)
void colorRampStepsChanged (int)
void toggleOverlayGrid (bool)
void changeGridColor ()
void changeSymbolColor ()
void toggleColorScaleDisplay (bool)
void updateVolumes ()
void updateOverlayGrid ()
Updates overlat grid (if any)
void update ()
Updates map (and display)
Protected Member Functions
QSharedPointer< DistanceMapGenerationTool::Map > updateMap ()
Updates internal map.
void updateMapTexture ()
Updates internal map texture (if any)
void updateZoom (ccBBox &box)
Updates 2D view zoom.
void clearView ()
Clears the 3D view.
double getBaseRadius () const
Returns currently applicable base radius.
double getSpinboxAngularValue (QDoubleSpinBox *spinBox, DistanceMapGenerationDlg::ANGULAR_UNIT unit) const
Returns the angle in a particular spinbox in the specified units.
void initFromPersistentSettings ()
Loads parameters from persistent settings.
void saveToPersistentSettings ()
Saves parameters to persistent settings.
void updateMinAndMaxLimits ()
Updates the min and max limits (fields)
Protected Attributes
ecvMainAppInterface * m_app
Application interface.
ccPointCloud * m_cloud
Associated cloud.
ccPolyline * m_profile
Associated profile.
ccScalarField * m_sf
Associated scalar field.
QSharedPointer< DistanceMapGenerationTool::Map > m_map
Internal map structure.
ANGULAR_UNIT m_angularUnits
Current angular units.
ccMapWindow * m_window
2D display
ccColorScaleSelector * m_colorScaleSelector
Color scale selector.
ccSymbolCloud * m_xLabels
X labels.
ccSymbolCloud * m_yLabels
Y labels.
QColor m_gridColor
Grid color.
QColor m_symbolColor
Symbols color.
Detailed Description
Dialog for generating a distance map (surface of revolution)
Definition at line 35 of file distanceMapGenerationDlg.h.
Member Enumeration Documentation
ANGULAR_UNIT
enum DistanceMapGenerationDlg::ANGULAR_UNIT
Angular units.
Enumerator
ANG_DEG
ANG_RAD
ANG_GRAD
Definition at line 50 of file distanceMapGenerationDlg.h.
ProjectionMode
enum DistanceMapGenerationDlg::ProjectionMode
Projection mode.
Enumerator
PROJ_CYLINDRICAL
PROJ_CONICAL
Definition at line 70 of file distanceMapGenerationDlg.h.
Constructor & Destructor Documentation
DistanceMapGenerationDlg()
DistanceMapGenerationDlg::DistanceMapGenerationDlg (ccPointCloud * cloud, ccScalarField * sf, ccPolyline * polyline, ecvMainAppInterface * app = 0)
Default constructor.
Definition at line 94 of file distanceMapGenerationDlg.cpp.
References ecvDisplayTools::AddToOwnDB(), ecvGenericDisplayTools::ALIGN_HMIDDLE, ecvGenericDisplayTools::ALIGN_HRIGHT, ecvGenericDisplayTools::ALIGN_VBOTTOM, ecvGenericDisplayTools::ALIGN_VMIDDLE, angularUnitChanged(), baseRadiusChanged(), ecvColor::black(), changeGridColor(), changeSymbolColor(), clearOverlaySymbols(), colorRampStepsChanged(), colorScaleChanged(), DEFAULT_LABEL_MARGIN, ecvDisplayTools::DisplayOverlayEntities(), exportMapAsCloud(), exportMapAsGrid(), exportMapAsImage(), exportMapAsMesh(), exportProfilesAsDXF(), ccScalarField::getColorScale(), ccColorScalesManager::GetDefaultScale(), ecvDisplayTools::GetDisplayParameters(), ccGenericPointCloud::getOwnBB(), DistanceMapGenerationTool::GetPoylineMetaData(), initFromPersistentSettings(), ecvDisplayTools::INTERACT_CLICKABLE_ITEMS, ecvDisplayTools::INTERACT_PAN, ecvDisplayTools::INTERACT_ZOOM_CAMERA, DxfProfilesExporter::IsEnabled(), cloudViewer::BoundingBoxTpl< T >::isValid(), labelFontSizeChanged(), labelPrecisionChanged(), loadOverlaySymbols(), m_angularUnits, m_app, m_cloud, m_colorScaleSelector, m_profile, m_sf, m_window, m_xLabels, m_yLabels, ccColorScale::MAX_STEPS, cloudViewer::BoundingBoxTpl< T >::maxCorner(), ccColorScale::MIN_STEPS, cloudViewer::BoundingBoxTpl< T >::minCorner(), DistanceMapGenerationTool::ProfileMetaData::origin, overlayGridColorChanged(), overlaySymbolsColorChanged(), overlaySymbolsSizeChanged(), params, projectionModeChanged(), DistanceMapGenerationTool::ProfileMetaData::revolDim, ecvDisplayTools::SetDisplayParameters(), ecvDisplayTools::SetInteractionMode(), ccSymbolCloud::setLabelAlignmentFlags(), ecvDisplayTools::SetPerspectiveState(), ccSymbolCloud::setSymbolSize(), ccMapWindow::showSF(), ccSymbolCloud::showSymbols(), spawnColorScaleEditor(), toggleColorScaleDisplay(), toggleOverlayGrid(), Tuple3Tpl< Type >::u, update(), updateGridSteps(), updateHeightUnits(), updateMinAndMaxLimits(), updateOverlayGrid(), updateProfileOrigin(), updateProfileRevolDim(), updateVolumes(), ecvColor::white(), Tuple3Tpl< Type >::x, XLABEL_CLOUD_NAME, Tuple3Tpl< Type >::y, YLABEL_CLOUD_NAME, and Tuple3Tpl< Type >::z.
~DistanceMapGenerationDlg()
DistanceMapGenerationDlg::~DistanceMapGenerationDlg () virtual
Default destructor.
Definition at line 341 of file distanceMapGenerationDlg.cpp.
Member Function Documentation
angularUnitChanged
void DistanceMapGenerationDlg::angularUnitChanged (int index) protected slot
Definition at line 883 of file distanceMapGenerationDlg.cpp.
References ANG_DEG, ANG_GRAD, ANG_RAD, getAngularUnitString(), getSpinboxAngularValue(), m_angularUnits, M_PI, cloudViewer::RadiansToDegrees(), SetSpinBoxValues(), and updateOverlayGrid().
Referenced by DistanceMapGenerationDlg(), and initFromPersistentSettings().
baseRadiusChanged
void DistanceMapGenerationDlg::baseRadiusChanged (double) protected slot
Definition at line 1109 of file distanceMapGenerationDlg.cpp.
References getBaseRadius(), ecvDisplayTools::GetViewportParameters(), m_window, params, ecvDisplayTools::RedrawDisplay(), and ecvDisplayTools::SetViewportParameters().
Referenced by DistanceMapGenerationDlg(), and projectionModeChanged().
changeGridColor
void DistanceMapGenerationDlg::changeGridColor () protected slot
Definition at line 1914 of file distanceMapGenerationDlg.cpp.
References m_gridColor, and overlayGridColorChanged().
Referenced by DistanceMapGenerationDlg().
changeSymbolColor
void DistanceMapGenerationDlg::changeSymbolColor () protected slot
Definition at line 1923 of file distanceMapGenerationDlg.cpp.
References m_symbolColor, and overlaySymbolsColorChanged().
Referenced by DistanceMapGenerationDlg().
clearOverlaySymbols
void DistanceMapGenerationDlg::clearOverlaySymbols () protected slot
Definition at line 1584 of file distanceMapGenerationDlg.cpp.
References ccHObject::filterChildren(), ecvDisplayTools::GetOwnDB(), m_window, m_xLabels, m_yLabels, CV_TYPES::POINT_CLOUD, ecvDisplayTools::RedrawDisplay(), and ecvDisplayTools::RemoveFromOwnDB().
Referenced by DistanceMapGenerationDlg(), update(), and updateProfileOrigin().
clearView()
void DistanceMapGenerationDlg::clearView () protected
Clears the 3D view.
Definition at line 604 of file distanceMapGenerationDlg.cpp.
References ccHObject::filterChildren(), ecvDisplayTools::GetOwnDB(), m_window, m_xLabels, m_yLabels, CV_TYPES::MESH, CV_TYPES::POLY_LINE, ecvDisplayTools::RemoveFromOwnDB(), ccMapWindow::setAssociatedScalarField(), and ccDrawableObject::setVisible().
Referenced by projectionModeChanged(), and update().
colorRampStepsChanged
void DistanceMapGenerationDlg::colorRampStepsChanged (int) protected slot
Definition at line 1694 of file distanceMapGenerationDlg.cpp.
References colorScaleChanged().
Referenced by DistanceMapGenerationDlg().
colorScaleChanged
void DistanceMapGenerationDlg::colorScaleChanged (int) protected slot
Definition at line 827 of file distanceMapGenerationDlg.cpp.
References ccMapWindow::getAssociatedScalarField(), m_colorScaleSelector, m_window, ecvDisplayTools::RedrawDisplay(), ccScalarField::setColorRampSteps(), ccScalarField::setColorScale(), and updateMapTexture().
Referenced by colorRampStepsChanged(), and DistanceMapGenerationDlg().
exportMapAsCloud
void DistanceMapGenerationDlg::exportMapAsCloud () protected slot
Definition at line 1186 of file distanceMapGenerationDlg.cpp.
References DistanceMapGenerationTool::ConvertMapToCloud(), getBaseRadius(), ccPointCloud::getCurrentDisplayedScalarField(), ccObject::getName(), m_app, m_cloud, m_colorScaleSelector, m_map, m_profile, ccScalarField::setColorScale(), and ccObject::setName().
Referenced by DistanceMapGenerationDlg().
exportMapAsGrid
void DistanceMapGenerationDlg::exportMapAsGrid () protected slot
Definition at line 1268 of file distanceMapGenerationDlg.cpp.
References ConvertAngleFromRad(), ecvFileUtils::defaultDocPath(), getAngularUnitString(), getHeightUnitString(), m_angularUnits, m_app, m_map, and DistanceMapGenerationTool::SaveMapAsCSVMatrix().
Referenced by DistanceMapGenerationDlg().
exportMapAsImage
void DistanceMapGenerationDlg::exportMapAsImage () protected slot
Definition at line 1307 of file distanceMapGenerationDlg.cpp.
References ecvDisplayTools::GlHeight(), ecvDisplayTools::GlWidth(), m_app, m_window, and ecvDisplayTools::RenderToFile().
Referenced by DistanceMapGenerationDlg().
exportMapAsMesh
void DistanceMapGenerationDlg::exportMapAsMesh () protected slot
Definition at line 1214 of file distanceMapGenerationDlg.cpp.
References DistanceMapGenerationTool::ProfileMetaData::computeCloudToProfileOriginTrans(), DistanceMapGenerationTool::ConvertMapToImage(), DistanceMapGenerationTool::ConvertProfileToMesh(), ccObject::getName(), DistanceMapGenerationTool::GetPoylineMetaData(), m_app, m_cloud, m_colorScaleSelector, m_map, m_profile, and ccObject::setName().
Referenced by DistanceMapGenerationDlg().
exportProfilesAsDXF
void DistanceMapGenerationDlg::exportProfilesAsDXF () protected slot
Definition at line 1323 of file distanceMapGenerationDlg.cpp.
References ANG_RAD, ConvertAngleFromRad(), getAngularUnitString(), getCondensedAngularUnitString(), getHeightUnitString(), DxfProfilesExportDlg::getHorizFilename(), DistanceMapGenerationTool::GetPolylineHeightShift(), getScaleYStep(), getSpinboxAngularValue(), DxfProfilesExportDlg::getVertFilename(), m_angularUnits, m_app, m_map, M_PI, m_profile, params, DxfProfilesExporter::SaveHorizontalProfiles(), and DxfProfilesExporter::SaveVerticalProfiles().
Referenced by DistanceMapGenerationDlg().
getAngularUnit()
DistanceMapGenerationDlg::ANGULAR_UNIT DistanceMapGenerationDlg::getAngularUnit () const
Returns selected angular unit.
Definition at line 460 of file distanceMapGenerationDlg.cpp.
References ANG_DEG, ANG_GRAD, ANG_RAD, and m_angularUnits.
getAngularUnitString()
QString DistanceMapGenerationDlg::getAngularUnitString () const
Returns selected angular unit as a string.
Definition at line 475 of file distanceMapGenerationDlg.cpp.
References m_angularUnits.
Referenced by angularUnitChanged(), exportMapAsGrid(), and exportProfilesAsDXF().
getBaseRadius()
double DistanceMapGenerationDlg::getBaseRadius () const protected
Returns currently applicable base radius.
Warning: return always 1 for concial projection mode!
Definition at line 1103 of file distanceMapGenerationDlg.cpp.
References getProjectionMode(), and PROJ_CONICAL.
Referenced by baseRadiusChanged(), and exportMapAsCloud().
getCondensedAngularUnitString()
QString DistanceMapGenerationDlg::getCondensedAngularUnitString () const
Returns selected angular unit as a condensed string.
Definition at line 490 of file distanceMapGenerationDlg.cpp.
References m_angularUnits.
Referenced by exportProfilesAsDXF(), and toggleOverlayGrid().
getEmptyCellFillingOption()
DistanceMapGenerationTool::EmptyCellFillOption DistanceMapGenerationDlg::getEmptyCellFillingOption () const
Returns the empty cells filling option.
Definition at line 1138 of file distanceMapGenerationDlg.cpp.
References DistanceMapGenerationTool::FILL_INTERPOLATE, DistanceMapGenerationTool::FILL_WITH_ZERO, and DistanceMapGenerationTool::LEAVE_EMPTY.
Referenced by updateMap().
getFillingStrategy()
DistanceMapGenerationTool::FillStrategyType DistanceMapGenerationDlg::getFillingStrategy () const
Returns the grid filling strategy.
Definition at line 1123 of file distanceMapGenerationDlg.cpp.
References DistanceMapGenerationTool::FILL_STRAT_AVG_DIST, DistanceMapGenerationTool::FILL_STRAT_MAX_DIST, DistanceMapGenerationTool::FILL_STRAT_MIN_DIST, and DistanceMapGenerationTool::INVALID_STRATEGY_TYPE.
Referenced by updateMap().
getGridXValues()
void DistanceMapGenerationDlg::getGridXValues (double & minX, double & maxX, double & step, ANGULAR_UNIT unit = ANG_RAD) const
Returns the current 'X' parameters.
Always correspond to angular values
Definition at line 996 of file distanceMapGenerationDlg.cpp.
References getSpinboxAngularValue().
Referenced by toggleOverlayGrid(), and updateGridSteps().
getGridYValues()
void DistanceMapGenerationDlg::getGridYValues (double & minY, double & maxY, double & step, ANGULAR_UNIT unit = ANG_RAD) const
Returns the current 'Y' parameters.
Depends on the current projection mode (i.e. height or latitude). The 'unit' parameter is only required for Conical mode.
Definition at line 1006 of file distanceMapGenerationDlg.cpp.
References getProjectionMode(), getSpinboxAngularValue(), PROJ_CONICAL, and PROJ_CYLINDRICAL.
Referenced by toggleOverlayGrid(), update(), updateGridSteps(), and updateMap().
getHeightUnitString()
QString DistanceMapGenerationDlg::getHeightUnitString () const
Returns height unit.
Definition at line 1118 of file distanceMapGenerationDlg.cpp.
Referenced by exportMapAsGrid(), exportProfilesAsDXF(), toggleOverlayGrid(), and updateHeightUnits().
getProjectionMode()
DistanceMapGenerationDlg::ProjectionMode DistanceMapGenerationDlg::getProjectionMode () const
Returns current projection mode.
Definition at line 446 of file distanceMapGenerationDlg.cpp.
References PROJ_CONICAL, and PROJ_CYLINDRICAL.
Referenced by getBaseRadius(), getGridYValues(), getScaleYStep(), loadOverlaySymbols(), projectionModeChanged(), toggleOverlayGrid(), update(), updateMap(), updateMapTexture(), and updateVolumes().
getScaleYStep()
double DistanceMapGenerationDlg::getScaleYStep (ANGULAR_UNIT unit = ANG_RAD) const
Returns scale 'Y' step (current unit)
The 'unit' parameter is only required for Conical mode.
Definition at line 1028 of file distanceMapGenerationDlg.cpp.
References getProjectionMode(), getSpinboxAngularValue(), and PROJ_CYLINDRICAL.
Referenced by exportProfilesAsDXF(), and toggleOverlayGrid().
getSpinboxAngularValue()
double DistanceMapGenerationDlg::getSpinboxAngularValue (QDoubleSpinBox * spinBox, DistanceMapGenerationDlg::ANGULAR_UNIT unit) const protected
Returns the angle in a particular spinbox in the specified units.
Definition at line 505 of file distanceMapGenerationDlg.cpp.
References ConvertAngleFromRad(), ConvertAngleToRad(), and m_angularUnits.
Referenced by angularUnitChanged(), exportProfilesAsDXF(), getGridXValues(), getGridYValues(), getScaleYStep(), toggleOverlayGrid(), and updateMap().
initFromPersistentSettings()
void DistanceMapGenerationDlg::initFromPersistentSettings () protected
Loads parameters from persistent settings.
Definition at line 1988 of file distanceMapGenerationDlg.cpp.
References angularUnitChanged(), m_colorScaleSelector, and updateHeightUnits().
Referenced by DistanceMapGenerationDlg().
labelFontSizeChanged
void DistanceMapGenerationDlg::labelFontSizeChanged (int) protected slot
Definition at line 1662 of file distanceMapGenerationDlg.cpp.
References ccHObject::getChild(), ccHObject::getChildrenNumber(), ecvDisplayTools::GetDisplayParameters(), ecvDisplayTools::GetOwnDB(), ccObject::isA(), m_window, params, CV_TYPES::POINT_CLOUD, ecvDisplayTools::RedrawDisplay(), and ecvDisplayTools::SetDisplayParameters().
Referenced by DistanceMapGenerationDlg().
labelPrecisionChanged
void DistanceMapGenerationDlg::labelPrecisionChanged (int prec) protected slot
Definition at line 1683 of file distanceMapGenerationDlg.cpp.
References ecvDisplayTools::GetDisplayParameters(), m_window, params, ecvDisplayTools::RedrawDisplay(), and ecvDisplayTools::SetDisplayParameters().
Referenced by DistanceMapGenerationDlg().
loadOverlaySymbols
void DistanceMapGenerationDlg::loadOverlaySymbols () protected slot
Definition at line 1414 of file distanceMapGenerationDlg.cpp.
References ccSymbolCloud::addLabel(), cloudViewer::PointCloudTpl< T >::addPoint(), ecvDisplayTools::AddToOwnDB(), cloudViewer::PointCloudTpl< T >::capacity(), DistanceMapGenerationTool::ProfileMetaData::computeCloudToSurfaceOriginTrans(), DistanceMapGenerationTool::ConvertCloudToConical(), DistanceMapGenerationTool::ConvertCloudToCylindrical(), ecvFileUtils::defaultDocPath(), error(), DistanceMapGenerationTool::GetPoylineMetaData(), getProjectionMode(), m_app, m_map, m_profile, m_symbolColor, m_window, DistanceMapGenerationTool::ProfileMetaData::origin, PROJ_CYLINDRICAL, qtCompatSplitRegex(), ecvDisplayTools::RedrawDisplay(), ccSymbolCloud::reserveLabelArray(), ccPointCloud::reserveThePointsTable(), DistanceMapGenerationTool::ProfileMetaData::revolDim, ccSymbolCloud::setFontSize(), ccSymbolCloud::setSymbolSize(), ccDrawableObject::setTempColor(), ccDrawableObject::setVisible(), ccPointCloud::shrinkToFit(), cloudViewer::PointCloudTpl< T >::size(), QtCompat::SkipEmptyParts, and Tuple3Tpl< Type >::u.
Referenced by DistanceMapGenerationDlg().
overlayGridColorChanged
void DistanceMapGenerationDlg::overlayGridColorChanged () protected slot
Definition at line 1639 of file distanceMapGenerationDlg.cpp.
References ccHObject::getChild(), ccHObject::getChildrenNumber(), ecvDisplayTools::GetOwnDB(), ccObject::isA(), m_gridColor, m_window, m_xLabels, m_yLabels, CV_TYPES::POLY_LINE, ecvDisplayTools::RedrawDisplay(), and ccDrawableObject::setTempColor().
Referenced by changeGridColor(), and DistanceMapGenerationDlg().
overlaySymbolsColorChanged
void DistanceMapGenerationDlg::overlaySymbolsColorChanged () protected slot
Definition at line 1617 of file distanceMapGenerationDlg.cpp.
References ccHObject::getChild(), ccHObject::getChildrenNumber(), ecvDisplayTools::GetOwnDB(), ccObject::isA(), m_symbolColor, m_window, m_xLabels, m_yLabels, CV_TYPES::POINT_CLOUD, ecvDisplayTools::RedrawDisplay(), and ccDrawableObject::setTempColor().
Referenced by changeSymbolColor(), and DistanceMapGenerationDlg().
overlaySymbolsSizeChanged
void DistanceMapGenerationDlg::overlaySymbolsSizeChanged (int size) protected slot
Definition at line 1600 of file distanceMapGenerationDlg.cpp.
References ccHObject::getChild(), ccHObject::getChildrenNumber(), ecvDisplayTools::GetOwnDB(), ccObject::isA(), m_window, m_xLabels, m_yLabels, CV_TYPES::POINT_CLOUD, and ecvDisplayTools::RedrawDisplay().
Referenced by DistanceMapGenerationDlg().
projectionModeChanged
void DistanceMapGenerationDlg::projectionModeChanged (int) protected slot
Definition at line 411 of file distanceMapGenerationDlg.cpp.
References baseRadiusChanged(), clearView(), getProjectionMode(), m_map, PROJ_CONICAL, PROJ_CYLINDRICAL, update(), and updateGridSteps().
Referenced by DistanceMapGenerationDlg().
saveToPersistentSettings()
void DistanceMapGenerationDlg::saveToPersistentSettings () protected
Saves parameters to persistent settings.
Definition at line 2073 of file distanceMapGenerationDlg.cpp.
References m_colorScaleSelector.
Referenced by update().
spawnColorScaleEditor
void DistanceMapGenerationDlg::spawnColorScaleEditor () protected slot
Definition at line 846 of file distanceMapGenerationDlg.cpp.
References ccColorScalesManager::BGYR, m_app, and m_colorScaleSelector.
Referenced by DistanceMapGenerationDlg().
toggleColorScaleDisplay
void DistanceMapGenerationDlg::toggleColorScaleDisplay (bool state) protected slot
Definition at line 1932 of file distanceMapGenerationDlg.cpp.
References m_window, ecvDisplayTools::RedrawDisplay(), and ccMapWindow::showSF().
Referenced by DistanceMapGenerationDlg().
toggleOverlayGrid
void DistanceMapGenerationDlg::toggleOverlayGrid (bool state) protected slot
Definition at line 1702 of file distanceMapGenerationDlg.cpp.
References ccHObject::addChild(), ccSymbolCloud::addLabel(), cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::ReferenceCloud::addPointIndex(), ecvDisplayTools::AddToOwnDB(), ANG_RAD, cloudViewer::utility::ceil(), ccSymbolCloud::clear(), DistanceMapGenerationTool::ConicalProjectN(), ConvertAngleFromRad(), ccHObject::filterChildren(), getCondensedAngularUnitString(), getGridXValues(), getGridYValues(), getHeightUnitString(), ecvDisplayTools::GetOwnDB(), getProjectionMode(), getScaleYStep(), getSpinboxAngularValue(), ccDrawableObject::isVisible(), m_angularUnits, m_app, m_gridColor, m_map, m_window, m_xLabels, m_yLabels, max(), PC_ONE, CV_TYPES::POLY_LINE, PROJ_CONICAL, DistanceMapGenerationTool::ProjectPointOnCone(), ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::RemoveFromOwnDB(), ccPointCloud::reserve(), ccSymbolCloud::reserve(), ccSymbolCloud::reserveLabelArray(), ccPolyline::set2DMode(), ccPolyline::setColor(), ccObject::setEnabled(), ccDrawableObject::setTempColor(), ccDrawableObject::setVisible(), ccDrawableObject::showColors(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by DistanceMapGenerationDlg(), and updateOverlayGrid().
update
void DistanceMapGenerationDlg::update () protected slot
Updates map (and display)
Definition at line 630 of file distanceMapGenerationDlg.cpp.
References cloudViewer::ScalarField::addElement(), ecvDisplayTools::AddToOwnDB(), ANG_RAD, clearOverlaySymbols(), clearView(), ccScalarField::computeMinAndMax(), DistanceMapGenerationTool::ConvertConicalMapToMesh(), ccColorScalesManager::GetDefaultScale(), ccHObject::getDisplayBB_recursive(), getGridYValues(), ecvDisplayTools::GetOwnDB(), getProjectionMode(), m_app, m_colorScaleSelector, m_map, m_window, PROJ_CONICAL, PROJ_CYLINDRICAL, saveToPersistentSettings(), ccMapWindow::setAssociatedScalarField(), ccScalarField::setColorRampSteps(), ccScalarField::setColorScale(), ccGLMatrixTpl< T >::setTranslation(), ccDrawableObject::setVisible(), ccGenericMesh::showNormals(), updateHeightUnits(), updateMap(), updateMapTexture(), updateVolumes(), and updateZoom().
Referenced by DistanceMapGenerationDlg(), and projectionModeChanged().
updateGridSteps
void DistanceMapGenerationDlg::updateGridSteps () protected slot
Definition at line 1079 of file distanceMapGenerationDlg.cpp.
References cloudViewer::utility::ceil(), getGridXValues(), getGridYValues(), m_angularUnits, and max().
Referenced by DistanceMapGenerationDlg(), and projectionModeChanged().
updateHeightUnits
void DistanceMapGenerationDlg::updateHeightUnits () protected slot
Definition at line 733 of file distanceMapGenerationDlg.cpp.
References ccMapWindow::getAssociatedScalarField(), getHeightUnitString(), m_window, cloudViewer::ScalarField::setName(), and updateOverlayGrid().
Referenced by DistanceMapGenerationDlg(), initFromPersistentSettings(), and update().
updateMap()
QSharedPointer< DistanceMapGenerationTool::Map > DistanceMapGenerationDlg::updateMap () protected
Updates internal map.
Definition at line 1153 of file distanceMapGenerationDlg.cpp.
References ANG_RAD, DistanceMapGenerationTool::ProfileMetaData::computeCloudToSurfaceOriginTrans(), DistanceMapGenerationTool::CreateMap(), getEmptyCellFillingOption(), getFillingStrategy(), getGridYValues(), DistanceMapGenerationTool::GetPoylineMetaData(), getProjectionMode(), getSpinboxAngularValue(), m_app, m_cloud, m_profile, m_sf, PROJ_CONICAL, and DistanceMapGenerationTool::ProfileMetaData::revolDim.
Referenced by update().
updateMapTexture()
void DistanceMapGenerationDlg::updateMapTexture () protected
Updates internal map texture (if any)
Definition at line 745 of file distanceMapGenerationDlg.cpp.
References DistanceMapGenerationTool::ConvertMapToImage(), ecvDisplayTools::GetOwnDB(), getProjectionMode(), m_app, m_colorScaleSelector, m_map, m_window, CV_TYPES::MESH, CV_TYPES::PLANE, PROJ_CONICAL, PROJ_CYLINDRICAL, and ecvDisplayTools::RedrawDisplay().
Referenced by colorScaleChanged(), and update().
updateMinAndMaxLimits()
void DistanceMapGenerationDlg::updateMinAndMaxLimits () protected
Updates the min and max limits (fields)
Definition at line 343 of file distanceMapGenerationDlg.cpp.
References DistanceMapGenerationTool::ProfileMetaData::computeCloudToSurfaceOriginTrans(), DistanceMapGenerationTool::ComputeMinAndMaxLatitude_rad(), ConvertAngleFromRad(), cloudViewer::ReferenceCloud::getPoint(), DistanceMapGenerationTool::GetPoylineMetaData(), height, DistanceMapGenerationTool::ProfileMetaData::heightShift, m_angularUnits, m_cloud, m_profile, DistanceMapGenerationTool::ProfileMetaData::revolDim, cloudViewer::ReferenceCloud::size(), Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
Referenced by DistanceMapGenerationDlg(), and updateProfileOrigin().
updateOverlayGrid
void DistanceMapGenerationDlg::updateOverlayGrid () protected slot
Updates overlat grid (if any)
Definition at line 1698 of file distanceMapGenerationDlg.cpp.
References toggleOverlayGrid().
Referenced by angularUnitChanged(), DistanceMapGenerationDlg(), and updateHeightUnits().
updateProfileOrigin
void DistanceMapGenerationDlg::updateProfileOrigin () protected slot
Definition at line 1047 of file distanceMapGenerationDlg.cpp.
References clearOverlaySymbols(), DistanceMapGenerationTool::GetPoylineMetaData(), DistanceMapGenerationTool::ProfileMetaData::heightShift, m_profile, DistanceMapGenerationTool::ProfileMetaData::origin, DistanceMapGenerationTool::ProfileMetaData::revolDim, DistanceMapGenerationTool::SetPolylineHeightShift(), DistanceMapGenerationTool::SetPoylineOrigin(), Tuple3Tpl< Type >::u, and updateMinAndMaxLimits().
Referenced by DistanceMapGenerationDlg().
updateProfileRevolDim
void DistanceMapGenerationDlg::updateProfileRevolDim (int dim) protected slot
Definition at line 1036 of file distanceMapGenerationDlg.cpp.
References m_profile, and DistanceMapGenerationTool::SetPoylineRevolDim().
Referenced by DistanceMapGenerationDlg().
updateVolumes
void DistanceMapGenerationDlg::updateVolumes () protected slot
Definition at line 1939 of file distanceMapGenerationDlg.cpp.
References DistanceMapGenerationTool::ComputeSurfacesAndVolumes(), getProjectionMode(), m_map, m_profile, DistanceMapGenerationTool::Measures::negative, DistanceMapGenerationTool::Measures::positive, PROJ_CONICAL, DistanceMapGenerationTool::Measures::theoretical, and DistanceMapGenerationTool::Measures::total.
Referenced by DistanceMapGenerationDlg(), and update().
updateZoom()
void DistanceMapGenerationDlg::updateZoom (ccBBox & box) protected
Updates 2D view zoom.
Definition at line 517 of file distanceMapGenerationDlg.cpp.
References ecvGui::ParamStruct::colorScaleRampWidth, ecvDisplayTools::Deprecate3DLayer(), Vector3Tpl< double >::fromArray(), ccMapWindow::getAssociatedScalarField(), cloudViewer::BoundingBoxTpl< T >::getCenter(), cloudViewer::BoundingBoxTpl< T >::getDiagNorm(), cloudViewer::BoundingBoxTpl< T >::getDiagVec(), ecvDisplayTools::GetDisplayParameters(), ccSymbolCloud::getFontSize(), ccSymbolCloud::getLabel(), ecvDisplayTools::GetTextDisplayFont(), ecvDisplayTools::GetViewportParameters(), ecvDisplayTools::GlHeight(), ecvDisplayTools::GlWidth(), cloudViewer::GreaterThanEpsilon(), ecvDisplayTools::InvalidateViewport(), ecvDisplayTools::InvalidateVisualization(), cloudViewer::BoundingBoxTpl< T >::isValid(), ccDrawableObject::isVisible(), m_window, m_yLabels, max(), cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), params, ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::SetCameraPos(), ecvDisplayTools::SetPivotPoint(), ecvDisplayTools::SetViewportParameters(), ccMapWindow::sfShown(), cloudViewer::PointCloudTpl< T >::size(), Tuple3Tpl< Type >::u, width, Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
Referenced by update().
Member Data Documentation
m_angularUnits
ANGULAR_UNIT DistanceMapGenerationDlg::m_angularUnits protected
Current angular units.
Definition at line 184 of file distanceMapGenerationDlg.h.
Referenced by angularUnitChanged(), DistanceMapGenerationDlg(), exportMapAsGrid(), exportProfilesAsDXF(), getAngularUnit(), getAngularUnitString(), getCondensedAngularUnitString(), getSpinboxAngularValue(), toggleOverlayGrid(), updateGridSteps(), and updateMinAndMaxLimits().
m_app
ecvMainAppInterface* DistanceMapGenerationDlg::m_app protected
Application interface.
Definition at line 169 of file distanceMapGenerationDlg.h.
Referenced by DistanceMapGenerationDlg(), exportMapAsCloud(), exportMapAsGrid(), exportMapAsImage(), exportMapAsMesh(), exportProfilesAsDXF(), loadOverlaySymbols(), spawnColorScaleEditor(), toggleOverlayGrid(), update(), updateMap(), and updateMapTexture().
m_cloud
ccPointCloud* DistanceMapGenerationDlg::m_cloud protected
Associated cloud.
Definition at line 172 of file distanceMapGenerationDlg.h.
Referenced by DistanceMapGenerationDlg(), exportMapAsCloud(), exportMapAsMesh(), updateMap(), and updateMinAndMaxLimits().
m_colorScaleSelector
ccColorScaleSelector* DistanceMapGenerationDlg::m_colorScaleSelector protected
Color scale selector.
Definition at line 190 of file distanceMapGenerationDlg.h.
Referenced by colorScaleChanged(), DistanceMapGenerationDlg(), exportMapAsCloud(), exportMapAsMesh(), initFromPersistentSettings(), saveToPersistentSettings(), spawnColorScaleEditor(), update(), and updateMapTexture().
m_gridColor
QColor DistanceMapGenerationDlg::m_gridColor protected
Grid color.
Definition at line 198 of file distanceMapGenerationDlg.h.
Referenced by changeGridColor(), overlayGridColorChanged(), and toggleOverlayGrid().
m_map
QSharedPointer<DistanceMapGenerationTool::Map> DistanceMapGenerationDlg::m_map protected
Internal map structure.
Definition at line 181 of file distanceMapGenerationDlg.h.
Referenced by exportMapAsCloud(), exportMapAsGrid(), exportMapAsMesh(), exportProfilesAsDXF(), loadOverlaySymbols(), projectionModeChanged(), toggleOverlayGrid(), update(), updateMapTexture(), and updateVolumes().
m_profile
ccPolyline* DistanceMapGenerationDlg::m_profile protected
Associated profile.
Definition at line 175 of file distanceMapGenerationDlg.h.
Referenced by DistanceMapGenerationDlg(), exportMapAsCloud(), exportMapAsMesh(), exportProfilesAsDXF(), loadOverlaySymbols(), updateMap(), updateMinAndMaxLimits(), updateProfileOrigin(), updateProfileRevolDim(), and updateVolumes().
m_sf
ccScalarField* DistanceMapGenerationDlg::m_sf protected
Associated scalar field.
Definition at line 178 of file distanceMapGenerationDlg.h.
Referenced by DistanceMapGenerationDlg(), and updateMap().
m_symbolColor
QColor DistanceMapGenerationDlg::m_symbolColor protected
Symbols color.
Definition at line 201 of file distanceMapGenerationDlg.h.
Referenced by changeSymbolColor(), loadOverlaySymbols(), and overlaySymbolsColorChanged().
m_window
ccMapWindow* DistanceMapGenerationDlg::m_window protected
2D display
Definition at line 187 of file distanceMapGenerationDlg.h.
Referenced by baseRadiusChanged(), clearOverlaySymbols(), clearView(), colorScaleChanged(), DistanceMapGenerationDlg(), exportMapAsImage(), labelFontSizeChanged(), labelPrecisionChanged(), loadOverlaySymbols(), overlayGridColorChanged(), overlaySymbolsColorChanged(), overlaySymbolsSizeChanged(), toggleColorScaleDisplay(), toggleOverlayGrid(), update(), updateHeightUnits(), updateMapTexture(), and updateZoom().
m_xLabels
ccSymbolCloud* DistanceMapGenerationDlg::m_xLabels protected
X labels.
Definition at line 193 of file distanceMapGenerationDlg.h.
Referenced by clearOverlaySymbols(), clearView(), DistanceMapGenerationDlg(), overlayGridColorChanged(), overlaySymbolsColorChanged(), overlaySymbolsSizeChanged(), and toggleOverlayGrid().
m_yLabels
ccSymbolCloud* DistanceMapGenerationDlg::m_yLabels protected
Y labels.
Definition at line 195 of file distanceMapGenerationDlg.h.
Referenced by clearOverlaySymbols(), clearView(), DistanceMapGenerationDlg(), overlayGridColorChanged(), overlaySymbolsColorChanged(), overlaySymbolsSizeChanged(), toggleOverlayGrid(), and updateZoom().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qSRA/include/distanceMapGenerationDlg.h
/root/ACloudViewer/plugins/core/Standard/qSRA/src/distanceMapGenerationDlg.cpp