ACloudViewer: colmap::RandomSampler Class Reference
colmap::RandomSampler Class Reference
#include <random_sampler.h>
Public Member Functions
RandomSampler (const size_t num_samples)
void Initialize (const size_t total_num_samples) override
size_t MaxNumSamples () override
std::vector< size_t > Sample () override
Public Member Functions inherited from colmap::Sampler
Sampler ()
Sampler (const size_t num_samples)
template<typename X_t >
void SampleX (const X_t &X, X_t *X_rand)
template<typename X_t , typename Y_t >
void SampleXY (const X_t &X, const Y_t &Y, X_t *X_rand, Y_t *Y_rand)
Detailed Description
Definition at line 17 of file random_sampler.h.
Constructor & Destructor Documentation
RandomSampler()
colmap::RandomSampler::RandomSampler (const size_t num_samples) explicit
Definition at line 40 of file random_sampler.cc.
Member Function Documentation
Initialize()
void colmap::RandomSampler::Initialize (const size_t total_num_samples) override virtual
Implements colmap::Sampler.
Definition at line 43 of file random_sampler.cc.
Referenced by BOOST_AUTO_TEST_CASE().
MaxNumSamples()
size_t colmap::RandomSampler::MaxNumSamples () override virtual
Implements colmap::Sampler.
Definition at line 49 of file random_sampler.cc.
Referenced by BOOST_AUTO_TEST_CASE().
Sample()
std::vector< size_t > colmap::RandomSampler::Sample () override virtual
Implements colmap::Sampler.
Definition at line 53 of file random_sampler.cc.
References colmap::Shuffle().
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/optim/random_sampler.h
/root/ACloudViewer/libs/Reconstruction/src/optim/random_sampler.cc