ACloudViewer: ccTracePolylineTool Class Reference
ccTracePolylineTool Class Reference
Graphical Polyline Tracing tool.
#include <ecvTracePolylineTool.h>
Classes
struct SegmentGLParams
Viewport parameters (used for picking)
Public Member Functions
ccTracePolylineTool (ccPickingHub *pickingHub, QWidget *parent)
Default constructor.
virtual ~ccTracePolylineTool ()
Destructor.
virtual bool linkWith (QWidget *win) override
Links the overlay dialog with a MDI window.
virtual bool start () override
Starts process.
virtual void stop (bool accepted) override
Stops process/dialog.
Public Member Functions inherited from ccOverlayDialog
ccOverlayDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::FramelessWindowHint|Qt::Tool)
Default constructor.
~ccOverlayDialog () override
Destructor.
void reject () override
void addOverridenShortcut (Qt::Key key)
bool started () const
Returns whether the tool is currently started or not.
Public Member Functions inherited from ccPickingListener
virtual ~ccPickingListener ()=default
virtual void onItemPicked (const PickedItem &pi)=0
Method called whenever an item is picked.
Protected Slots
void apply ()
void cancel ()
void exportLine ()
void continueEdition ()
void resetLine ()
void closePolyLine (int x=0, int y=0)
void updatePolyLineTip (int x, int y, Qt::MouseButtons buttons)
void onWidthSizeChanged (int)
void onShortcutTriggered (int)
To capture overridden shortcuts (pause button, etc.)
virtual void onItemPicked (const PickedItem &pi) override
Inherited from ccPickingListener.
Protected Slots inherited from ccOverlayDialog
virtual void onLinkedWindowDeletion (QObject *object=nullptr)
Slot called when the linked window is deleted (calls 'onClose')
Protected Member Functions
void restart (bool reset)
Restarts the edition mode.
void resetTip ()
void updateTip ()
void resetPoly3D ()
void updatePoly3D ()
ccPolyline * polylineOverSampling (unsigned steps) const
Oversamples the active 3D polyline.
Protected Member Functions inherited from ccOverlayDialog
bool eventFilter (QObject *obj, QEvent *e) override
Protected Attributes
ccPolyline * m_polyTip
2D polyline (for the currently edited part)
ccPointCloud * m_polyTipVertices
2D polyline vertices
ccPolyline * m_poly3D
3D polyline
ccPointCloud * m_poly3DVertices
3D polyline vertices
std::vector< SegmentGLParams > m_segmentParams
Viewport parameters use to draw each segment of the polyline.
bool m_done
Current process state.
ccPickingHub * m_pickingHub
Picking hub.
Protected Attributes inherited from ccOverlayDialog
QWidget * m_associatedWin
Associated (MDI) window.
bool m_processing
Running/processing state.
QList< int > m_overriddenKeys
Overridden keys.
Additional Inherited Members
Signals inherited from ccOverlayDialog
void processFinished (bool accepted)
Signal emitted when process is finished.
void shortcutTriggered (int key)
Signal emitted when an overridden key shortcut is pressed.
void shown ()
Signal emitted when a 'show' event is detected.
Detailed Description
Graphical Polyline Tracing tool.
Definition at line 28 of file ecvTracePolylineTool.h.
Constructor & Destructor Documentation
ccTracePolylineTool()
ccTracePolylineTool::ccTracePolylineTool (ccPickingHub * pickingHub, QWidget * parent) explicit
Default constructor.
Definition at line 50 of file ecvTracePolylineTool.cpp.
References ccHObject::addChild(), ccOverlayDialog::addOverridenShortcut(), cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::ReferenceCloud::addPointIndex(), apply(), cancel(), continueEdition(), exportLine(), ecvColor::green(), m_polyTip, m_polyTipVertices, onShortcutTriggered(), onWidthSizeChanged(), cloudViewer::ReferenceCloud::reserve(), ccPointCloud::reserve(), resetLine(), ccPolyline::set2DMode(), ccObject::setEnabled(), ccPolyline::setForeground(), ccDrawableObject::setTempColor(), ccPolyline::setWidth(), and ccOverlayDialog::shortcutTriggered().
~ccTracePolylineTool()
ccTracePolylineTool::~ccTracePolylineTool () virtual
Destructor.
Definition at line 107 of file ecvTracePolylineTool.cpp.
References m_poly3D, and m_polyTip.
Member Function Documentation
apply
void ccTracePolylineTool::apply () protected slot
Definition at line 592 of file ecvTracePolylineTool.cpp.
References exportLine(), and stop().
Referenced by ccTracePolylineTool(), and onShortcutTriggered().
cancel
void ccTracePolylineTool::cancel () protected slot
Definition at line 597 of file ecvTracePolylineTool.cpp.
References resetLine(), and stop().
Referenced by ccTracePolylineTool(), and onShortcutTriggered().
closePolyLine
void ccTracePolylineTool::closePolyLine (int x = 0, int y = 0) protected slot
Definition at line 483 of file ecvTracePolylineTool.cpp.
References m_done, m_pickingHub, m_poly3D, m_polyTip, ecvDisplayTools::NO_PICKING, ccPickingHub::removeListener(), resetLine(), ccObject::setEnabled(), ecvDisplayTools::SetPickingMode(), cloudViewer::ReferenceCloud::size(), and updateTip().
Referenced by linkWith().
continueEdition
void ccTracePolylineTool::continueEdition () inline protected slot
Definition at line 49 of file ecvTracePolylineTool.h.
References restart().
Referenced by ccTracePolylineTool().
exportLine
void ccTracePolylineTool::exportLine () protected slot
Definition at line 559 of file ecvTracePolylineTool.cpp.
References MainWindow::addToDB(), ecvColor::green(), m_poly3D, m_poly3DVertices, m_segmentParams, polylineOverSampling(), resetLine(), resetPoly3D(), ccPolyline::setColor(), ccDrawableObject::setTempColor(), and MainWindow::TheInstance().
Referenced by apply(), and ccTracePolylineTool().
linkWith()
bool ccTracePolylineTool::linkWith (QWidget * win) override virtual
Links the overlay dialog with a MDI window.
Warning: link can't be modified while dialog is displayed/process is running!
Returns
success
Reimplemented from ccOverlayDialog.
Definition at line 263 of file ecvTracePolylineTool.cpp.
References closePolyLine(), ccOverlayDialog::linkWith(), m_poly3D, m_polyTip, ecvDisplayTools::mouseMoved(), ecvDisplayTools::rightButtonClicked(), ecvDisplayTools::TheInstance(), and updatePolyLineTip().
onItemPicked
void ccTracePolylineTool::onItemPicked (const PickedItem & pi) override protected virtual slot
Inherited from ccPickingListener.
Definition at line 407 of file ecvTracePolylineTool.cpp.
References ccHObject::addChild(), cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::ReferenceCloud::addPointIndex(), ccPickingListener::PickedItem::clickPoint, ccPickingListener::PickedItem::entity, CVLog::Error(), ecvDisplayTools::GetCurrentScreen(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), cloudViewer::PointCloudTpl< T >::getPointPersistentPtr(), ecvColor::green(), m_poly3D, m_poly3DVertices, m_polyTip, m_polyTipVertices, m_segmentParams, ccPickingListener::PickedItem::P3D, cloudViewer::ReferenceCloud::reserve(), ccPointCloud::reserve(), ccPolyline::set2DMode(), ccObject::setEnabled(), ccPolyline::setGlobalScale(), ccPolyline::setGlobalShift(), ccDrawableObject::setRedraw(), ccDrawableObject::setTempColor(), ccPolyline::setWidth(), cloudViewer::PointCloudTpl< T >::size(), ccHObjectCaster::ToGenericPointCloud(), ecvDisplayTools::ToVtkCoordinates(), updatePoly3D(), Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
onShortcutTriggered
void ccTracePolylineTool::onShortcutTriggered (int key) protected slot
To capture overridden shortcuts (pause button, etc.)
Definition at line 119 of file ecvTracePolylineTool.cpp.
References apply(), and cancel().
Referenced by ccTracePolylineTool().
onWidthSizeChanged
void ccTracePolylineTool::onWidthSizeChanged (int width) protected slot
Definition at line 603 of file ecvTracePolylineTool.cpp.
References ecvDisplayTools::GetCurrentScreen(), m_poly3D, m_polyTip, ccPolyline::setWidth(), updatePoly3D(), updateTip(), and width.
Referenced by ccTracePolylineTool().
polylineOverSampling()
ccPolyline * ccTracePolylineTool::polylineOverSampling (unsigned steps) const protected
Oversamples the active 3D polyline.
Definition at line 135 of file ecvTracePolylineTool.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), ccHObject::filterChildren(), Vector3Tpl< PointCoordinateType >::fromArray(), ecvDisplayTools::GetCurrentScreen(), ccObject::getName(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::PointCloudTpl< T >::getPoint(), ecvDisplayTools::GetSceneDB(), ccPolyline::importParametersFrom(), cloudViewer::Polyline::isClosed(), ccObject::isEnabled(), m_poly3D, m_poly3DVertices, m_segmentParams, CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, ccGenericPointCloud::pointPicking(), cloudViewer::ReferenceCloud::reserve(), cloudViewer::PointCloudTpl< T >::size(), cloudViewer::ReferenceCloud::size(), ccGenericMesh::trianglePicking(), Tuple3Tpl< Type >::u, and CVLog::Warning().
Referenced by exportLine().
resetLine
void ccTracePolylineTool::resetLine () inline protected slot
Definition at line 50 of file ecvTracePolylineTool.h.
References restart().
Referenced by cancel(), ccTracePolylineTool(), closePolyLine(), exportLine(), and start().
resetPoly3D()
void ccTracePolylineTool::resetPoly3D () protected
Definition at line 622 of file ecvTracePolylineTool.cpp.
References ecvDisplayTools::GetCurrentScreen(), ccHObject::getViewId(), m_poly3D, ecvDisplayTools::RemoveWidgets(), and WIDGET_POLYLINE.
Referenced by exportLine(), and restart().
resetTip()
void ccTracePolylineTool::resetTip () protected
Definition at line 639 of file ecvTracePolylineTool.cpp.
References ecvDisplayTools::GetCurrentScreen(), ccHObject::getViewId(), m_polyTip, ecvDisplayTools::RemoveWidgets(), and WIDGET_POLYLINE.
Referenced by stop().
restart()
void ccTracePolylineTool::restart (bool reset) protected
Restarts the edition mode.
Definition at line 515 of file ecvTracePolylineTool.cpp.
References ccPickingHub::addListener(), CVLog::Error(), m_done, m_pickingHub, m_poly3D, m_poly3DVertices, m_polyTip, m_segmentParams, resetPoly3D(), ccObject::setEnabled(), and updateTip().
Referenced by continueEdition(), and resetLine().
start()
bool ccTracePolylineTool::start () override virtual
Starts process.
Returns
success
Reimplemented from ccOverlayDialog.
Definition at line 284 of file ecvTracePolylineTool.cpp.
References ecvDisplayTools::GetCurrentScreen(), ecvDisplayTools::INTERACT_CTRL_PAN, ecvDisplayTools::INTERACT_SIG_MOUSE_MOVED, ecvDisplayTools::INTERACT_SIG_RB_CLICKED, m_pickingHub, m_poly3D, m_polyTip, ecvDisplayTools::NO_PICKING, ccPickingHub::removeListener(), resetLine(), s_defaultPickingRadius, s_overSamplingCount, ecvDisplayTools::SetInteractionMode(), ecvDisplayTools::SetPickingMode(), ccOverlayDialog::start(), ecvDisplayTools::TRANSFORM_CAMERA(), and CVLog::Warning().
stop()
void ccTracePolylineTool::stop (bool accepted) override virtual
Stops process/dialog.
Automatically emits the 'processFinished' signal (with input state as argument).
Parameters
accepted process/dialog result
Reimplemented from ccOverlayDialog.
Definition at line 317 of file ecvTracePolylineTool.cpp.
References ecvDisplayTools::DisplayNewMessage(), ecvDisplayTools::GetCurrentScreen(), m_pickingHub, m_polyTip, ecvDisplayTools::MANUAL_SEGMENTATION_MESSAGE, ccPickingHub::removeListener(), resetTip(), s_defaultPickingRadius, s_overSamplingCount, ecvDisplayTools::SetInteractionMode(), ccOverlayDialog::stop(), ecvDisplayTools::TRANSFORM_CAMERA(), and ecvDisplayTools::UPPER_CENTER_MESSAGE.
Referenced by apply(), and cancel().
updatePoly3D()
void ccTracePolylineTool::updatePoly3D () protected
Definition at line 631 of file ecvTracePolylineTool.cpp.
References ecvDisplayTools::DrawWidgets(), ecvDisplayTools::GetCurrentScreen(), m_poly3D, and WIDGET_POLYLINE.
Referenced by onItemPicked(), and onWidthSizeChanged().
updatePolyLineTip
void ccTracePolylineTool::updatePolyLineTip (int x, int y, Qt::MouseButtons buttons) protected slot
Definition at line 341 of file ecvTracePolylineTool.cpp.
References ecvDisplayTools::GetCurrentScreen(), ecvDisplayTools::GetGLCameraParameters(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::PointCloudTpl< T >::getPointPersistentPtr(), ccObject::isEnabled(), m_done, m_poly3DVertices, m_polyTip, m_polyTipVertices, ccGLCameraParameters::project(), ccObject::setEnabled(), cloudViewer::PointCloudTpl< T >::size(), ecvDisplayTools::ToVtkCoordinates(), updateTip(), Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
Referenced by linkWith().
updateTip()
void ccTracePolylineTool::updateTip () protected
Definition at line 648 of file ecvTracePolylineTool.cpp.
References ecvDisplayTools::DrawWidgets(), ecvDisplayTools::GetCurrentScreen(), m_polyTip, and WIDGET_POLYLINE.
Referenced by closePolyLine(), onWidthSizeChanged(), restart(), and updatePolyLineTip().
Member Data Documentation
m_done
bool ccTracePolylineTool::m_done protected
Current process state.
Definition at line 102 of file ecvTracePolylineTool.h.
Referenced by closePolyLine(), restart(), and updatePolyLineTip().
m_pickingHub
ccPickingHub* ccTracePolylineTool::m_pickingHub protected
Picking hub.
Definition at line 105 of file ecvTracePolylineTool.h.
Referenced by closePolyLine(), restart(), start(), and stop().
m_poly3D
ccPolyline* ccTracePolylineTool::m_poly3D protected
3D polyline
Definition at line 94 of file ecvTracePolylineTool.h.
Referenced by closePolyLine(), exportLine(), linkWith(), onItemPicked(), onWidthSizeChanged(), polylineOverSampling(), resetPoly3D(), restart(), start(), updatePoly3D(), and ~ccTracePolylineTool().
m_poly3DVertices
ccPointCloud* ccTracePolylineTool::m_poly3DVertices protected
3D polyline vertices
Definition at line 96 of file ecvTracePolylineTool.h.
Referenced by exportLine(), onItemPicked(), polylineOverSampling(), restart(), and updatePolyLineTip().
m_polyTip
ccPolyline* ccTracePolylineTool::m_polyTip protected
2D polyline (for the currently edited part)
Definition at line 89 of file ecvTracePolylineTool.h.
Referenced by ccTracePolylineTool(), closePolyLine(), linkWith(), onItemPicked(), onWidthSizeChanged(), resetTip(), restart(), start(), stop(), updatePolyLineTip(), updateTip(), and ~ccTracePolylineTool().
m_polyTipVertices
ccPointCloud* ccTracePolylineTool::m_polyTipVertices protected
2D polyline vertices
Definition at line 91 of file ecvTracePolylineTool.h.
Referenced by ccTracePolylineTool(), onItemPicked(), and updatePolyLineTip().
m_segmentParams
std::vector<SegmentGLParams> ccTracePolylineTool::m_segmentParams protected
Viewport parameters use to draw each segment of the polyline.
Definition at line 99 of file ecvTracePolylineTool.h.
Referenced by exportLine(), onItemPicked(), polylineOverSampling(), and restart().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvTracePolylineTool.h
/root/ACloudViewer/app/ecvTracePolylineTool.cpp