ACloudViewer: colmap::AffineTransformEstimator Class Reference
colmap::AffineTransformEstimator Class Reference
#include <affine_transform.h>
Public Types
typedef Eigen::Vector2d X_t
typedef Eigen::Vector2d Y_t
typedef Eigen::Matrix< double, 2, 3 > M_t
Static Public Member Functions
static std::vector< M_t > Estimate (const std::vector< X_t > &points1, const std::vector< Y_t > &points2)
static void Residuals (const std::vector< X_t > &points1, const std::vector< Y_t > &points2, const M_t &E, std::vector< double > *residuals)
Static Public Attributes
static const int kMinNumSamples = 3
Detailed Description
Definition at line 18 of file affine_transform.h.
Member Typedef Documentation
M_t
typedef Eigen::Matrix<double, 2, 3> colmap::AffineTransformEstimator::M_t
Definition at line 22 of file affine_transform.h.
X_t
typedef Eigen::Vector2d colmap::AffineTransformEstimator::X_t
Definition at line 20 of file affine_transform.h.
Y_t
typedef Eigen::Vector2d colmap::AffineTransformEstimator::Y_t
Definition at line 21 of file affine_transform.h.
Member Function Documentation
Estimate()
std::vector< AffineTransformEstimator::M_t > colmap::AffineTransformEstimator::Estimate (const std::vector< X_t > & points1, const std::vector< Y_t > & points2) static
Definition at line 40 of file affine_transform.cc.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::retrieval::VoteAndVerify().
Residuals()
void colmap::AffineTransformEstimator::Residuals (const std::vector< X_t > & points1, const std::vector< Y_t > & points2, const M_t & E, std::vector< double > * residuals) static
Definition at line 75 of file affine_transform.cc.
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
kMinNumSamples
const int colmap::AffineTransformEstimator::kMinNumSamples = 3 static
Definition at line 25 of file affine_transform.h.
Referenced by colmap::retrieval::VoteAndVerify().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/estimators/affine_transform.h
/root/ACloudViewer/libs/Reconstruction/src/estimators/affine_transform.cc