ACloudViewer: ccRenderToFileDlg Class Reference
ccRenderToFileDlg Class Reference
Dialog for screen to file rendering.
#include <ecvRenderToFileDlg.h>
Public Member Functions
ccRenderToFileDlg (unsigned baseWidth, unsigned baseHeight, QWidget *parent=0)
Default constructor.
~ccRenderToFileDlg () override
void hideOptions ()
Disable and hide the scale and overlay checkboxes.
float getZoom () const
On dialog acceptance, returns requested zoom.
QString getFilename () const
On dialog acceptance, returns requested output filename.
bool dontScalePoints () const
On dialog acceptance, returns whether points should be scaled or not.
bool renderOverlayItems () const
Whether overlay items should be rendered.
Protected Slots
void chooseFile ()
void updateInfo ()
void saveSettings ()
Protected Attributes
unsigned w
unsigned h
QString selectedFilter
QString currentPath
QString filters
Ui::RenderToFileDialog * m_ui
Detailed Description
Dialog for screen to file rendering.
Definition at line 19 of file ecvRenderToFileDlg.h.
Constructor & Destructor Documentation
ccRenderToFileDlg()
ccRenderToFileDlg::ccRenderToFileDlg (unsigned baseWidth, unsigned baseHeight, QWidget * parent = 0)
Default constructor.
Definition at line 28 of file ecvRenderToFileDlg.cpp.
References chooseFile(), currentPath, data, dontScalePoints(), CVLog::Error(), filters, m_ui, renderOverlayItems(), saveSettings(), selectedFilter, and updateInfo().
~ccRenderToFileDlg()
ccRenderToFileDlg::~ccRenderToFileDlg () override
Definition at line 119 of file ecvRenderToFileDlg.cpp.
References m_ui.
Member Function Documentation
chooseFile
void ccRenderToFileDlg::chooseFile () protected slot
Definition at line 108 of file ecvRenderToFileDlg.cpp.
References filters, m_ui, and selectedFilter.
Referenced by ccRenderToFileDlg().
dontScalePoints()
bool ccRenderToFileDlg::dontScalePoints () const
On dialog acceptance, returns whether points should be scaled or not.
Definition at line 136 of file ecvRenderToFileDlg.cpp.
References m_ui.
Referenced by ccRenderToFileDlg(), DistanceMapGenerationDlg::exportMapAsImage(), and saveSettings().
getFilename()
QString ccRenderToFileDlg::getFilename () const
On dialog acceptance, returns requested output filename.
Definition at line 132 of file ecvRenderToFileDlg.cpp.
References m_ui.
Referenced by DistanceMapGenerationDlg::exportMapAsImage().
getZoom()
float ccRenderToFileDlg::getZoom () const
On dialog acceptance, returns requested zoom.
Definition at line 128 of file ecvRenderToFileDlg.cpp.
References m_ui.
Referenced by DistanceMapGenerationDlg::exportMapAsImage(), and updateInfo().
hideOptions()
void ccRenderToFileDlg::hideOptions ()
Disable and hide the scale and overlay checkboxes.
Definition at line 121 of file ecvRenderToFileDlg.cpp.
References m_ui.
Referenced by DistanceMapGenerationDlg::exportMapAsImage().
renderOverlayItems()
bool ccRenderToFileDlg::renderOverlayItems () const
Whether overlay items should be rendered.
Definition at line 140 of file ecvRenderToFileDlg.cpp.
References m_ui.
Referenced by ccRenderToFileDlg(), DistanceMapGenerationDlg::exportMapAsImage(), and saveSettings().
saveSettings
void ccRenderToFileDlg::saveSettings () protected slot
Definition at line 90 of file ecvRenderToFileDlg.cpp.
References currentPath, dontScalePoints(), m_ui, renderOverlayItems(), and selectedFilter.
Referenced by ccRenderToFileDlg().
updateInfo
void ccRenderToFileDlg::updateInfo () protected slot
Definition at line 144 of file ecvRenderToFileDlg.cpp.
References getZoom(), h, m_ui, and w.
Referenced by ccRenderToFileDlg().
Member Data Documentation
currentPath
QString ccRenderToFileDlg::currentPath protected
Definition at line 53 of file ecvRenderToFileDlg.h.
Referenced by ccRenderToFileDlg(), and saveSettings().
filters
QString ccRenderToFileDlg::filters protected
Definition at line 54 of file ecvRenderToFileDlg.h.
Referenced by ccRenderToFileDlg(), and chooseFile().
h
unsigned ccRenderToFileDlg::h protected
Definition at line 50 of file ecvRenderToFileDlg.h.
Referenced by updateInfo().
m_ui
Ui::RenderToFileDialog* ccRenderToFileDlg::m_ui protected
Definition at line 56 of file ecvRenderToFileDlg.h.
Referenced by ccRenderToFileDlg(), chooseFile(), dontScalePoints(), getFilename(), getZoom(), hideOptions(), renderOverlayItems(), saveSettings(), updateInfo(), and ~ccRenderToFileDlg().
selectedFilter
QString ccRenderToFileDlg::selectedFilter protected
Definition at line 52 of file ecvRenderToFileDlg.h.
Referenced by ccRenderToFileDlg(), chooseFile(), and saveSettings().
w
unsigned ccRenderToFileDlg::w protected
Definition at line 49 of file ecvRenderToFileDlg.h.
Referenced by updateInfo().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVPluginAPI/include/ecvRenderToFileDlg.h
/root/ACloudViewer/libs/CVPluginAPI/src/ecvRenderToFileDlg.cpp