ACloudViewer: cloudViewer::utility::IJsonConvertible Class Reference
cloudViewer::utility::IJsonConvertible Class Reference abstract
#include <IJsonConvertible.h>
Public Member Functions
virtual ~IJsonConvertible ()
virtual bool ConvertToJsonValue (Json::Value &value) const =0
virtual bool ConvertFromJsonValue (const Json::Value &value)=0
virtual std::string ToString () const
Convert to a styled string representation of JSON data for display.
Static Public Member Functions
static bool EigenVector3dFromJsonArray (Eigen::Vector3d &vec, const Json::Value &value)
static bool EigenVector3dToJsonArray (const Eigen::Vector3d &vec, Json::Value &value)
static bool EigenVector4dFromJsonArray (Eigen::Vector4d &vec, const Json::Value &value)
static bool EigenVector4dToJsonArray (const Eigen::Vector4d &vec, Json::Value &value)
static bool EigenMatrix3dFromJsonArray (Eigen::Matrix3d &mat, const Json::Value &value)
static bool EigenMatrix3dToJsonArray (const Eigen::Matrix3d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d_u &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d_u &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d_u &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d_u &mat, Json::Value &value)
Detailed Description
Class IJsonConvertible defines the behavior of a class that can convert itself to/from a json::Value.
Definition at line 41 of file IJsonConvertible.h.
Constructor & Destructor Documentation
~IJsonConvertible()
virtual cloudViewer::utility::IJsonConvertible::~IJsonConvertible () inline virtual
Definition at line 43 of file IJsonConvertible.h.
Member Function Documentation
ConvertFromJsonValue()
virtual bool cloudViewer::utility::IJsonConvertible::ConvertFromJsonValue (const Json::Value & value) pure virtual
Implemented in cloudViewer::AlignmentSession, cloudViewer::geometry::Octree, cloudViewer::geometry::OctreePointColorLeafNode, cloudViewer::geometry::OctreeColorLeafNode, cloudViewer::camera::PinholeCameraTrajectory, cloudViewer::camera::PinholeCameraParameters, cloudViewer::camera::PinholeCameraIntrinsic, cloudViewer::visualization::ViewTrajectory, cloudViewer::visualization::ViewParameters, cloudViewer::visualization::RenderOptionWithEditing, cloudViewer::visualization::RenderOption, cloudViewer::visualization::SelectionPolygonVolume, cloudViewer::t::io::RGBDVideoMetadata, cloudViewer::t::io::RealSenseSensorConfig, cloudViewer::pipelines::registration::PoseGraph, cloudViewer::pipelines::registration::PoseGraphEdge, cloudViewer::pipelines::registration::PoseGraphNode, cloudViewer::pipelines::color_map::ImageWarpingField, cloudViewer::io::MKVMetadata, and cloudViewer::io::AzureKinectSensorConfig.
ConvertToJsonValue()
virtual bool cloudViewer::utility::IJsonConvertible::ConvertToJsonValue (Json::Value & value) const pure virtual
Implemented in cloudViewer::AlignmentSession, cloudViewer::geometry::Octree, cloudViewer::geometry::OctreePointColorLeafNode, cloudViewer::geometry::OctreeColorLeafNode, cloudViewer::camera::PinholeCameraTrajectory, cloudViewer::camera::PinholeCameraParameters, cloudViewer::camera::PinholeCameraIntrinsic, cloudViewer::visualization::ViewTrajectory, cloudViewer::visualization::ViewParameters, cloudViewer::visualization::RenderOptionWithEditing, cloudViewer::visualization::RenderOption, cloudViewer::visualization::SelectionPolygonVolume, cloudViewer::t::io::RGBDVideoMetadata, cloudViewer::t::io::RealSenseSensorConfig, cloudViewer::pipelines::registration::PoseGraph, cloudViewer::pipelines::registration::PoseGraphEdge, cloudViewer::pipelines::registration::PoseGraphNode, cloudViewer::pipelines::color_map::ImageWarpingField, cloudViewer::io::MKVMetadata, and cloudViewer::io::AzureKinectSensorConfig.
Referenced by ToString().
EigenMatrix3dFromJsonArray()
bool cloudViewer::utility::IJsonConvertible::EigenMatrix3dFromJsonArray (Eigen::Matrix3d & mat, const Json::Value & value) static
Definition at line 87 of file IJsonConvertible.cpp.
Referenced by cloudViewer::camera::PinholeCameraIntrinsic::ConvertFromJsonValue().
EigenMatrix3dToJsonArray()
bool cloudViewer::utility::IJsonConvertible::EigenMatrix3dToJsonArray (const Eigen::Matrix3d & mat, Json::Value & value) static
Definition at line 99 of file IJsonConvertible.cpp.
Referenced by cloudViewer::camera::PinholeCameraIntrinsic::ConvertToJsonValue().
EigenMatrix4dFromJsonArray() [1/2]
bool cloudViewer::utility::IJsonConvertible::EigenMatrix4dFromJsonArray (Eigen::Matrix4d & mat, const Json::Value & value) static
Definition at line 108 of file IJsonConvertible.cpp.
Referenced by cloudViewer::pipelines::registration::PoseGraphNode::ConvertFromJsonValue(), cloudViewer::pipelines::registration::PoseGraphEdge::ConvertFromJsonValue(), cloudViewer::AlignmentSession::ConvertFromJsonValue(), and cloudViewer::data::DemoDopplerICPSequence::GetCalibration().
EigenMatrix4dFromJsonArray() [2/2]
bool cloudViewer::utility::IJsonConvertible::EigenMatrix4dFromJsonArray (Eigen::Matrix4d_u & mat, const Json::Value & value) static
Definition at line 129 of file IJsonConvertible.cpp.
EigenMatrix4dToJsonArray() [1/2]
bool cloudViewer::utility::IJsonConvertible::EigenMatrix4dToJsonArray (const Eigen::Matrix4d & mat, Json::Value & value) static
Definition at line 120 of file IJsonConvertible.cpp.
Referenced by cloudViewer::pipelines::registration::PoseGraphNode::ConvertToJsonValue(), cloudViewer::pipelines::registration::PoseGraphEdge::ConvertToJsonValue(), and cloudViewer::AlignmentSession::ConvertToJsonValue().
EigenMatrix4dToJsonArray() [2/2]
bool cloudViewer::utility::IJsonConvertible::EigenMatrix4dToJsonArray (const Eigen::Matrix4d_u & mat, Json::Value & value) static
Definition at line 141 of file IJsonConvertible.cpp.
EigenMatrix6dFromJsonArray() [1/2]
bool cloudViewer::utility::IJsonConvertible::EigenMatrix6dFromJsonArray (Eigen::Matrix6d & mat, const Json::Value & value) static
Definition at line 150 of file IJsonConvertible.cpp.
Referenced by cloudViewer::pipelines::registration::PoseGraphEdge::ConvertFromJsonValue().
EigenMatrix6dFromJsonArray() [2/2]
bool cloudViewer::utility::IJsonConvertible::EigenMatrix6dFromJsonArray (Eigen::Matrix6d_u & mat, const Json::Value & value) static
Definition at line 171 of file IJsonConvertible.cpp.
EigenMatrix6dToJsonArray() [1/2]
bool cloudViewer::utility::IJsonConvertible::EigenMatrix6dToJsonArray (const Eigen::Matrix6d & mat, Json::Value & value) static
Definition at line 162 of file IJsonConvertible.cpp.
Referenced by cloudViewer::pipelines::registration::PoseGraphEdge::ConvertToJsonValue().
EigenMatrix6dToJsonArray() [2/2]
bool cloudViewer::utility::IJsonConvertible::EigenMatrix6dToJsonArray (const Eigen::Matrix6d_u & mat, Json::Value & value) static
Definition at line 183 of file IJsonConvertible.cpp.
EigenVector3dFromJsonArray()
bool cloudViewer::utility::IJsonConvertible::EigenVector3dFromJsonArray (Eigen::Vector3d & vec, const Json::Value & value) static
Definition at line 43 of file IJsonConvertible.cpp.
Referenced by cloudViewer::visualization::SelectionPolygonVolume::ConvertFromJsonValue(), cloudViewer::visualization::RenderOption::ConvertFromJsonValue(), cloudViewer::visualization::RenderOptionWithEditing::ConvertFromJsonValue(), cloudViewer::visualization::ViewParameters::ConvertFromJsonValue(), cloudViewer::geometry::OctreeColorLeafNode::ConvertFromJsonValue(), cloudViewer::geometry::OctreePointColorLeafNode::ConvertFromJsonValue(), and cloudViewer::geometry::Octree::ConvertFromJsonValue().
EigenVector3dToJsonArray()
bool cloudViewer::utility::IJsonConvertible::EigenVector3dToJsonArray (const Eigen::Vector3d & vec, Json::Value & value) static
Definition at line 55 of file IJsonConvertible.cpp.
Referenced by cloudViewer::visualization::SelectionPolygonVolume::ConvertToJsonValue(), cloudViewer::visualization::RenderOption::ConvertToJsonValue(), cloudViewer::visualization::RenderOptionWithEditing::ConvertToJsonValue(), cloudViewer::visualization::ViewParameters::ConvertToJsonValue(), cloudViewer::geometry::OctreeColorLeafNode::ConvertToJsonValue(), cloudViewer::geometry::OctreePointColorLeafNode::ConvertToJsonValue(), and cloudViewer::geometry::Octree::ConvertToJsonValue().
EigenVector4dFromJsonArray()
bool cloudViewer::utility::IJsonConvertible::EigenVector4dFromJsonArray (Eigen::Vector4d & vec, const Json::Value & value) static
Definition at line 64 of file IJsonConvertible.cpp.
EigenVector4dToJsonArray()
bool cloudViewer::utility::IJsonConvertible::EigenVector4dToJsonArray (const Eigen::Vector4d & vec, Json::Value & value) static
Definition at line 77 of file IJsonConvertible.cpp.
ToString()
std::string cloudViewer::utility::IJsonConvertible::ToString () const virtual
Convert to a styled string representation of JSON data for display.
Definition at line 37 of file IJsonConvertible.cpp.
References ConvertToJsonValue(), and Value.
The documentation for this class was generated from the following files:
/root/ACloudViewer/core/include/IJsonConvertible.h
/root/ACloudViewer/core/src/IJsonConvertible.cpp