ACloudViewer: cloudViewer::visualization::rendering::FilamentView Class Reference
cloudViewer::visualization::rendering::FilamentView Class Reference
#include <FilamentView.h>
Public Member Functions
FilamentView (filament::Engine &engine, FilamentResourceManager &resource_mgr)
FilamentView (filament::Engine &engine, FilamentScene &scene, FilamentResourceManager &resource_mgr)
~FilamentView () override
void SetDiscardBuffers (const TargetBuffers &buffers) override
Mode GetMode () const override
void SetMode (Mode mode) override
void SetWireframe (bool enable) override
void SetSampleCount (int n) override
int GetSampleCount () const override
void SetViewport (std::int32_t x, std::int32_t y, std::uint32_t w, std::uint32_t h) override
std::array< int, 4 > GetViewport () const override
void SetPostProcessing (bool enabled) override
void SetAmbientOcclusion (bool enabled, bool ssct_enabled=false) override
void SetBloom (bool enabled, float strength=0.5f, int spread=6) override
void SetAntiAliasing (bool enabled, bool temporal=false) override
void SetShadowing (bool enabled, ShadowType type) override
void SetColorGrading (const ColorGradingParams &color_grading) override
void ConfigureForColorPicking () override
void EnableViewCaching (bool enable) override
bool IsCached () const override
TextureHandle GetColorBuffer () override
Camera * GetCamera () const override
void CopySettingsFrom (const FilamentView &other)
void SetScene (FilamentScene &scene)
filament::View * GetNativeView () const
void PreRender ()
void PostRender ()
Public Member Functions inherited from cloudViewer::visualization::rendering::View
virtual ~View ()
Static Public Attributes
static constexpr std::uint8_t kAllLayersMask
static constexpr std::uint8_t kMainLayer = 1
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::rendering::View
enum class TargetBuffers : std::uint8_t {
None = 0u , Color = 1u , Depth = 2u , Stencil = 4u ,
ColorAndDepth = Color | Depth , ColorAndStencil = Color | Stencil , DepthAndStencil = Depth | Stencil , All = Color | Depth | Stencil
}
enum class Mode : std::uint8_t {
Color = 0u , Depth , Normals , ColorMapX ,
ColorMapY , ColorMapZ
}
enum class ShadowType : std::uint8_t { kPCF , kVSM }
Detailed Description
Definition at line 33 of file FilamentView.h.
Constructor & Destructor Documentation
FilamentView() [1/2]
cloudViewer::visualization::rendering::FilamentView::FilamentView (filament::Engine & engine, FilamentResourceManager & resource_mgr)
Definition at line 55 of file FilamentView.cpp.
References cloudViewer::visualization::rendering::View::All, cloudViewer::visualization::rendering::Camera::Horizontal, kAllLayersMask, cloudViewer::visualization::rendering::ColorGradingParams::kHigh, kMainLayer, cloudViewer::visualization::rendering::View::kPCF, cloudViewer::visualization::rendering::ColorGradingParams::kUchimura, SetAmbientOcclusion(), SetAntiAliasing(), SetColorGrading(), SetPostProcessing(), and SetShadowing().
FilamentView() [2/2]
cloudViewer::visualization::rendering::FilamentView::FilamentView (filament::Engine & engine, FilamentScene & scene, FilamentResourceManager & resource_mgr)
Definition at line 78 of file FilamentView.cpp.
References cloudViewer::visualization::rendering::FilamentScene::GetNativeScene().
~FilamentView()
cloudViewer::visualization::rendering::FilamentView::~FilamentView () override
Definition at line 87 of file FilamentView.cpp.
Member Function Documentation
ConfigureForColorPicking()
void cloudViewer::visualization::rendering::FilamentView::ConfigureForColorPicking () override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 286 of file FilamentView.cpp.
References cloudViewer::visualization::rendering::View::kPCF, SetAmbientOcclusion(), SetPostProcessing(), and SetShadowing().
Referenced by CopySettingsFrom().
CopySettingsFrom()
void cloudViewer::visualization::rendering::FilamentView::CopySettingsFrom (const FilamentView & other)
Definition at line 345 of file FilamentView.cpp.
References ConfigureForColorPicking(), SetMode(), and SetViewport().
EnableViewCaching()
void cloudViewer::visualization::rendering::FilamentView::EnableViewCaching (bool enable) override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 294 of file FilamentView.cpp.
References cloudViewer::visualization::rendering::FilamentResourceManager::CreateColorAttachmentTexture(), cloudViewer::visualization::rendering::FilamentResourceManager::CreateDepthAttachmentTexture(), cloudViewer::visualization::rendering::FilamentResourceManager::CreateRenderTarget(), and cloudViewer::visualization::rendering::FilamentResourceManager::Destroy().
GetCamera()
Camera * cloudViewer::visualization::rendering::FilamentView::GetCamera () const override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 343 of file FilamentView.cpp.
GetColorBuffer()
TextureHandle cloudViewer::visualization::rendering::FilamentView::GetColorBuffer () override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 325 of file FilamentView.cpp.
GetMode()
View::Mode cloudViewer::visualization::rendering::FilamentView::GetMode () const override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 96 of file FilamentView.cpp.
GetNativeView()
filament::View* cloudViewer::visualization::rendering::FilamentView::GetNativeView () const inline
Definition at line 81 of file FilamentView.h.
Referenced by cloudViewer::visualization::rendering::FilamentRenderToBuffer::Render().
GetSampleCount()
int cloudViewer::visualization::rendering::FilamentView::GetSampleCount () const override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 144 of file FilamentView.cpp.
GetViewport()
std::array< int, 4 > cloudViewer::visualization::rendering::FilamentView::GetViewport () const override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 153 of file FilamentView.cpp.
IsCached()
bool cloudViewer::visualization::rendering::FilamentView::IsCached () const override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 323 of file FilamentView.cpp.
PostRender()
void cloudViewer::visualization::rendering::FilamentView::PostRender ()
Definition at line 449 of file FilamentView.cpp.
PreRender()
void cloudViewer::visualization::rendering::FilamentView::PreRender ()
Definition at line 361 of file FilamentView.cpp.
References cloudViewer::visualization::rendering::View::ColorMapX, cloudViewer::visualization::rendering::View::ColorMapY, cloudViewer::visualization::rendering::View::ColorMapZ, cloudViewer::visualization::rendering::View::Depth, cloudViewer::visualization::rendering::MaterialModifier::Finish(), cloudViewer::visualization::rendering::FilamentResourceManager::GetMaterialInstance(), cloudViewer::visualization::rendering::FilamentResourceManager::kColorMapMaterial, cloudViewer::visualization::rendering::FilamentResourceManager::kDepthMaterial, cloudViewer::visualization::rendering::FilamentResourceManager::kNormalsMaterial, cloudViewer::visualization::rendering::View::Normals, cloudViewer::visualization::rendering::FilamentMaterialModifier::SetParameter(), and cloudViewer::visualization::rendering::MaterialModifier::SetParameter().
SetAmbientOcclusion()
void cloudViewer::visualization::rendering::FilamentView::SetAmbientOcclusion (bool enabled, bool ssct_enabled = false) override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 162 of file FilamentView.cpp.
Referenced by ConfigureForColorPicking(), and FilamentView().
SetAntiAliasing()
void cloudViewer::visualization::rendering::FilamentView::SetAntiAliasing (bool enabled, bool temporal = false) override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 181 of file FilamentView.cpp.
Referenced by FilamentView().
SetBloom()
void cloudViewer::visualization::rendering::FilamentView::SetBloom (bool enabled, float strength = 0.5f, int spread = 6) override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 170 of file FilamentView.cpp.
Referenced by SetWireframe().
SetColorGrading()
void cloudViewer::visualization::rendering::FilamentView::SetColorGrading (const ColorGradingParams & color_grading) override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 212 of file FilamentView.cpp.
References cloudViewer::visualization::rendering::eigen_to_float3(), cloudViewer::visualization::rendering::eigen_to_float4(), cloudViewer::visualization::rendering::ColorGradingParams::GetContrast(), cloudViewer::visualization::rendering::ColorGradingParams::GetHighlights(), cloudViewer::visualization::rendering::ColorGradingParams::GetHighlightScale(), cloudViewer::visualization::rendering::ColorGradingParams::GetMidpoint(), cloudViewer::visualization::rendering::ColorGradingParams::GetMidtones(), cloudViewer::visualization::rendering::ColorGradingParams::GetMixerBlue(), cloudViewer::visualization::rendering::ColorGradingParams::GetMixerGreen(), cloudViewer::visualization::rendering::ColorGradingParams::GetMixerRed(), cloudViewer::visualization::rendering::ColorGradingParams::GetOffset(), cloudViewer::visualization::rendering::ColorGradingParams::GetPower(), cloudViewer::visualization::rendering::ColorGradingParams::GetQuality(), cloudViewer::visualization::rendering::ColorGradingParams::GetRanges(), cloudViewer::visualization::rendering::ColorGradingParams::GetSaturation(), cloudViewer::visualization::rendering::ColorGradingParams::GetShadowGamma(), cloudViewer::visualization::rendering::ColorGradingParams::GetShadows(), cloudViewer::visualization::rendering::ColorGradingParams::GetSlope(), cloudViewer::visualization::rendering::ColorGradingParams::GetTemperature(), cloudViewer::visualization::rendering::ColorGradingParams::GetTint(), cloudViewer::visualization::rendering::ColorGradingParams::GetToneMapping(), cloudViewer::visualization::rendering::ColorGradingParams::GetVibrance(), cloudViewer::visualization::rendering::ColorGradingParams::kAces, cloudViewer::visualization::rendering::ColorGradingParams::kAcesLegacy, cloudViewer::visualization::rendering::ColorGradingParams::kDisplayRange, cloudViewer::visualization::rendering::ColorGradingParams::kFilmic, cloudViewer::visualization::rendering::ColorGradingParams::kHigh, cloudViewer::visualization::rendering::ColorGradingParams::kMedium, cloudViewer::visualization::rendering::ColorGradingParams::kReinhard, cloudViewer::visualization::rendering::ColorGradingParams::kUchimura, and cloudViewer::visualization::rendering::ColorGradingParams::kUltra.
Referenced by FilamentView().
SetDiscardBuffers()
void cloudViewer::visualization::rendering::FilamentView::SetDiscardBuffers (const TargetBuffers & buffers) override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 128 of file FilamentView.cpp.
SetMode()
void cloudViewer::visualization::rendering::FilamentView::SetMode (Mode mode) override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 98 of file FilamentView.cpp.
References cloudViewer::visualization::rendering::View::Color, cloudViewer::visualization::rendering::View::ColorMapX, cloudViewer::visualization::rendering::View::ColorMapY, cloudViewer::visualization::rendering::View::ColorMapZ, cloudViewer::visualization::rendering::View::Depth, kAllLayersMask, kMainLayer, and cloudViewer::visualization::rendering::View::Normals.
Referenced by CopySettingsFrom().
SetPostProcessing()
void cloudViewer::visualization::rendering::FilamentView::SetPostProcessing (bool enabled) override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 158 of file FilamentView.cpp.
Referenced by ConfigureForColorPicking(), and FilamentView().
SetSampleCount()
void cloudViewer::visualization::rendering::FilamentView::SetSampleCount (int n) override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 142 of file FilamentView.cpp.
SetScene()
void cloudViewer::visualization::rendering::FilamentView::SetScene (FilamentScene & scene)
Definition at line 356 of file FilamentView.cpp.
References cloudViewer::visualization::rendering::FilamentScene::GetNativeScene().
Referenced by cloudViewer::visualization::rendering::FilamentRenderToBuffer::Configure().
SetShadowing()
void cloudViewer::visualization::rendering::FilamentView::SetShadowing (bool enabled, ShadowType type) override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 192 of file FilamentView.cpp.
References cloudViewer::visualization::rendering::View::kPCF, and type.
Referenced by ConfigureForColorPicking(), and FilamentView().
SetViewport()
void cloudViewer::visualization::rendering::FilamentView::SetViewport (std::int32_t x, std::int32_t y, std::uint32_t w, std::uint32_t h) override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 146 of file FilamentView.cpp.
Referenced by CopySettingsFrom(), and cloudViewer::visualization::rendering::FilamentRenderToBuffer::SetDimensions().
SetWireframe()
void cloudViewer::visualization::rendering::FilamentView::SetWireframe (bool enable) override virtual
Implements cloudViewer::visualization::rendering::View.
Definition at line 133 of file FilamentView.cpp.
References SetBloom().
Member Data Documentation
kAllLayersMask
constexpr std::uint8_t cloudViewer::visualization::rendering::FilamentView::kAllLayersMask static constexpr
Initial value:
=
            std::numeric_limits<std::uint8_t>::max()
Definition at line 35 of file FilamentView.h.
Referenced by cloudViewer::visualization::rendering::FilamentScene::Copy(), FilamentView(), and SetMode().
kMainLayer
constexpr std::uint8_t cloudViewer::visualization::rendering::FilamentView::kMainLayer = 1 static constexpr
Definition at line 37 of file FilamentView.h.
Referenced by cloudViewer::visualization::rendering::FilamentScene::Copy(), FilamentView(), and SetMode().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentView.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentView.cpp