ACloudViewer: pba::SparseBundleCPU< Float > Class Template Reference
pba::SparseBundleCPU< Float > Class Template Reference
#include <SparseBundleCPU.h>
Public Types
typedef avec< Float > VectorF
typedef std::vector< int > VectorI
typedef float float_t
Public Types inherited from pba::ParallelBA
enum StatusT {
STATUS_SUCCESS = 0 , STATUS_CAMERA_MISSING = 1 , STATUS_POINT_MISSING , STATUS_PROJECTION_MISSING ,
STATUS_MEASURMENT_MISSING , STATUS_ALLOCATION_FAIL
}
enum DeviceT {
PBA_INVALID_DEVICE = -4 , PBA_CPU_DOUBLE = -3 , PBA_CPU_FLOAT = -2 , PBA_CUDA_DEVICE_DEFAULT = -1 ,
PBA_CUDA_DEVICE0 = 0
}
enum DistortionT { PBA_MEASUREMENT_DISTORTION = -1 , PBA_NO_DISTORTION = 0 , PBA_PROJECTION_DISTORTION = 1 }
enum BundleModeT { BUNDLE_FULL = 0 , BUNDLE_ONLY_MOTION = 1 , BUNDLE_ONLY_STRUCTURE = 2 }
Public Member Functions
SparseBundleCPU (const int num_threads)
virtual void AbortBundleAdjustment ()
virtual int GetCurrentIteration ()
virtual void SetNextTimeBudget (int seconds)
virtual void SetNextBundleMode (BundleModeT mode)
virtual void SetFixedIntrinsics (bool fixed)
virtual void EnableRadialDistortion (DistortionT type)
virtual void ParseParam (int narg, char **argv)
SparseBundleCPU ()
virtual void SetCameraData (size_t ncam, CameraT *cams)
virtual void SetPointData (size_t npoint, Point3D *pts)
virtual void SetProjection (size_t nproj, const Point2D *imgpts, const int *point_idx, const int *cam_idx)
virtual void SetFocalMask (const int *fmask, float weight)
virtual float GetMeanSquaredError ()
virtual int RunBundleAdjustment ()
Public Member Functions inherited from pba::ParallelBA
virtual void ReserveStorage (size_t ncam, size_t npt, size_t nproj)
void SetFocalLengthFixed (bool fixed)
void ResetBundleStorage ()
ParallelBA (DeviceT device=PBA_CUDA_DEVICE_DEFAULT, const int num_threads=-1)
void * operator new (size_t size)
virtual ~ParallelBA ()
Public Member Functions inherited from pba::ConfigBA
void ParseParam (int argc, char **argv)
const char * GetOutputParam ()
float GetInitialMSE ()
float GetFinalMSE ()
double GetBundleTiming (int timer=TIMER_OVERALL)
int GetIterationsLM ()
int GetIterationsCG ()
int GetCurrentDevice ()
int GetBundleReturnCode ()
int GetActiveDevice ()
Protected Member Functions
bool ProcessIndexCameraQ (std::vector< int > &qmap, std::vector< int > &qlist)
void ProcessWeightCameraQ (std::vector< int > &cpnum, std::vector< int > &qmap, Float *qmapw, Float *qlistw)
int ValidateInputData ()
int InitializeBundle ()
int GetParameterLength ()
void BundleAdjustment ()
void NormalizeData ()
void TransferDataToHost ()
void DenormalizeData ()
void NormalizeDataF ()
void NormalizeDataD ()
bool InitializeStorageForSFM ()
bool InitializeStorageForCG ()
void SaveBundleRecord (int iter, float res, float damping, float &g_norm, float &g_inf)
void PrepareJacobianNormalization ()
void EvaluateJacobians ()
void ComputeJtE (VectorF &E, VectorF &JtE, int mode=0)
void ComputeJX (VectorF &X, VectorF &JX, int mode=0)
void ComputeDiagonal (VectorF &JJI)
void ComputeBlockPC (float lambda, bool dampd)
void ApplyBlockPC (VectorF &v, VectorF &pv, int mode=0)
float UpdateCameraPoint (VectorF &dx, VectorF &cuImageTempProj)
float EvaluateProjection (VectorF &cam, VectorF &point, VectorF &proj)
float EvaluateProjectionX (VectorF &cam, VectorF &point, VectorF &proj)
float SaveUpdatedSystem (float residual_reduction, float dx_sqnorm, float damping)
float EvaluateDeltaNorm ()
int SolveNormalEquationPCGB (float lambda)
int SolveNormalEquationPCGX (float lambda)
int SolveNormalEquation (float lambda)
void NonlinearOptimizeLM ()
void AdjustBundleAdjsutmentMode ()
void RunProfileSteps ()
void RunTestIterationLM (bool reduced)
void DumpCooJacobian ()
Protected Member Functions inherited from pba::ConfigBA
ConfigBA ()
void ResetTemporarySetting ()
void ResetBundleStatistics ()
void PrintBundleStatistics ()
void SaveBundleStatistics (int ncam, int npt, int nproj)
void BundleTimerStart (int timer)
void BundleTimerSwitch (int timer)
float BundleTimerGet (int timer)
void BundleTimerSwap (int timer1, int timer2)
float BundleTimerGetNow (int timer=TIMER_OPTIMIZATION)
void SaveBundleRecord (int iter, float res, float damping, float gn, float gi)
bool IsTimeBudgetAvailable ()
double MyClock ()
Protected Attributes
int _num_camera
int _num_point
int _num_imgpt
CameraT * _camera_data
float * _point_data
const float * _imgpt_data
const int * _camera_idx
const int * _point_idx
const int * _focal_mask
float _projection_sse
VectorF _cuCameraData
VectorF _cuCameraDataEX
VectorF _cuPointData
VectorF _cuPointDataEX
VectorF _cuMeasurements
VectorF _cuImageProj
VectorF _cuJacobianCamera
VectorF _cuJacobianPoint
VectorF _cuJacobianCameraT
VectorI _cuProjectionMap
VectorI _cuPointMeasurementMap
VectorI _cuCameraMeasurementMap
VectorI _cuCameraMeasurementList
VectorI _cuCameraMeasurementListT
VectorF _cuBlockPC
VectorF _cuVectorSJ
VectorF _cuVectorJtE
LM normal equation.
VectorF _cuVectorJJ
VectorF _cuVectorJX
VectorF _cuVectorXK
VectorF _cuVectorPK
VectorF _cuVectorZK
VectorF _cuVectorRK
int _num_imgpt_q
float _weight_q
VectorI _cuCameraQList
VectorI _cuCameraQMap
VectorF _cuCameraQMapW
VectorF _cuCameraQListW
Protected Attributes inherited from pba::ConfigBA
bool __multiply_jx_usenoj
int __selected_device
int __cpu_data_precision
int __bundle_time_budget
int __bundle_mode_next
int __bundle_current_mode
float __initial_mse
float __final_mse
float __final_mse_x
float __focal_scaling
float __depth_scaling
int __current_device
int __current_iteration
int __num_cg_iteration
int __num_lm_success
int __num_lm_iteration
int __num_projection_eval
int __num_jacobian_eval
int __num_camera_modified
int __num_point_behind
int __pba_return_code
int __recent_cg_status
int __profile_pba
bool __cpu_thread_profile
bool __debug_pba
bool __warmup_device
size_t __memory_usage
bool __matlab_format_stat
char * __stat_filename
const char * __driver_output
std::vector< float > __bundle_records
double __timer_record [NUM_TIMER]
int __num_cpu_thread_all
int __num_cpu_thread [NUM_FUNC]
Additional Inherited Members
Public Attributes inherited from pba::ConfigBA
int __lm_max_iteration
int __cg_max_iteration
int __cg_min_iteration
int __cg_recalculate_freq
bool __accurate_gain_ratio
float __lm_delta_threshold
float __lm_gradient_threshold
float __lm_mse_threshold
float __lm_initial_damp
float __lm_minimum_damp
float __lm_maximum_damp
float __cg_norm_threshold
float __cg_norm_guard
int __pba_experimental
bool __cg_schur_complement
bool __lm_check_gradient
float __lm_damping_auto_switch
bool __lm_use_diagonal_damp
bool __fixed_intrinsics
int __use_radial_distortion
bool __reset_initial_distortion
int __verbose_level
bool __abort_flag
bool __verbose_cg_iteration
bool __verbose_function_time
bool __save_gradient_norm
bool __verbose_allocation
bool __verbose_sse
bool __jc_store_transpose
bool __no_jacobian_store
bool __jc_store_original
bool __jacobian_normalize
bool __focal_normalize
bool __depth_normalize
bool __depth_degeneracy_fix
float __data_normalize_median
float __depth_check_epsilon
Protected Types inherited from pba::ConfigBA
enum {
TIMER_OVERALL = 0 , TIMER_OPTIMIZATION , TIMER_GPU_ALLOCATION , TIMER_GPU_UPLOAD ,
TIMER_PREPROCESSING , TIMER_GPU_DOWNLOAD , TIMER_CG_ITERATION , TIMER_LM_ITERATION ,
TIMER_FUNCTION_JJ , TIMER_FUNCTION_PJ , TIMER_FUNCTION_DD , TIMER_FUNCTION_JX ,
TIMER_FUNCTION_JTE , TIMER_FUNCTION_BC , TIMER_FUNCTION_MP , TIMER_FUNCTION_UP ,
TIMER_PROFILE_STEP , NUM_TIMER , FUNC_JX = 0 , FUNC_JX_ ,
FUNC_JTEC_JCT , FUNC_JTEC_JCO , FUNC_JTEP , FUNC_JTE_ ,
FUNC_JJ_JCO_JCT_JP , FUNC_JJ_JCO_JP , FUNC_JJ_JCT_JP , FUNC_JJ_JP ,
FUNC_PJ , FUNC_BCC_JCT , FUNC_BCC_JCO , FUNC_BCP ,
FUNC_MPC , FUNC_MPP , FUNC_VS , FUNC_VV ,
NUM_FUNC
}
Detailed Description
template<class Float>
class pba::SparseBundleCPU< Float >
Definition at line 144 of file SparseBundleCPU.h.
Member Typedef Documentation
float_t
template<class Float > typedef float pba::SparseBundleCPU< Float >::float_t
Definition at line 150 of file SparseBundleCPU.h.
VectorF
template<class Float > typedef avec<Float> pba::SparseBundleCPU< Float >::VectorF
Definition at line 148 of file SparseBundleCPU.h.
VectorI
template<class Float > typedef std::vector<int> pba::SparseBundleCPU< Float >::VectorI
Definition at line 149 of file SparseBundleCPU.h.
Constructor & Destructor Documentation
SparseBundleCPU() [1/2]
template<class Float > pba::SparseBundleCPU< Float >::SparseBundleCPU (const int num_threads)
Definition at line 2550 of file SparseBundleCPU.cpp.
References pba::ConfigBA::__cpu_data_precision, pba::ConfigBA::__multiply_jx_usenoj, pba::ProgramCPU::__num_cpu_cores, pba::ConfigBA::__num_cpu_thread, pba::ConfigBA::__verbose_level, pba::ConfigBA::FUNC_BCC_JCO, pba::ConfigBA::FUNC_BCC_JCT, pba::ConfigBA::FUNC_BCP, pba::ConfigBA::FUNC_JJ_JCO_JCT_JP, pba::ConfigBA::FUNC_JJ_JCO_JP, pba::ConfigBA::FUNC_JJ_JCT_JP, pba::ConfigBA::FUNC_JJ_JP, pba::ConfigBA::FUNC_JTE_, pba::ConfigBA::FUNC_JTEC_JCO, pba::ConfigBA::FUNC_JTEC_JCT, pba::ConfigBA::FUNC_JTEP, pba::ConfigBA::FUNC_JX, pba::ConfigBA::FUNC_JX_, pba::ConfigBA::FUNC_MPC, pba::ConfigBA::FUNC_MPP, pba::ConfigBA::FUNC_PJ, pba::ConfigBA::FUNC_VS, and pba::ConfigBA::FUNC_VV.
SparseBundleCPU() [2/2]
template<class Float > pba::SparseBundleCPU< Float >::SparseBundleCPU ()
Member Function Documentation
AbortBundleAdjustment()
template<class Float > virtual void pba::SparseBundleCPU< Float >::AbortBundleAdjustment () inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 254 of file SparseBundleCPU.h.
References pba::ConfigBA::__abort_flag.
AdjustBundleAdjsutmentMode()
template<class Float > void pba::SparseBundleCPU< Float >::AdjustBundleAdjsutmentMode protected
Definition at line 3885 of file SparseBundleCPU.cpp.
ApplyBlockPC()
template<class Float > void pba::SparseBundleCPU< Float >::ApplyBlockPC (VectorF & v, VectorF & pv, int mode = 0) protected
Definition at line 3202 of file SparseBundleCPU.cpp.
References pba::avec< Float >::begin(), and pba::ProgramCPU::MultiplyBlockConditioner().
BundleAdjustment()
template<class Float > void pba::SparseBundleCPU< Float >::BundleAdjustment protected
Definition at line 2688 of file SparseBundleCPU.cpp.
ComputeBlockPC()
template<class Float > void pba::SparseBundleCPU< Float >::ComputeBlockPC (float lambda, bool dampd) protected
Definition at line 3171 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeDiagonalBlock(), and pba::ProgramCPU::ComputeDiagonalBlock_().
ComputeDiagonal()
template<class Float > void pba::SparseBundleCPU< Float >::ComputeDiagonal (VectorF & JJI) protected
Definition at line 3211 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeDiagonal().
ComputeJtE()
template<class Float > void pba::SparseBundleCPU< Float >::ComputeJtE (VectorF & E, VectorF & JtE, int mode = 0) protected
Definition at line 3047 of file SparseBundleCPU.cpp.
References pba::avec< Float >::begin(), pba::ProgramCPU::ComputeJQtEC(), pba::ProgramCPU::ComputeJtE(), pba::ProgramCPU::ComputeJtE_(), pba::ProgramCPU::ComputeVXY(), and POINT_ALIGN.
ComputeJX()
template<class Float > void pba::SparseBundleCPU< Float >::ComputeJX (VectorF & X, VectorF & JX, int mode = 0) protected
Definition at line 3147 of file SparseBundleCPU.cpp.
References pba::avec< Float >::begin(), pba::ProgramCPU::ComputeJQX(), pba::ProgramCPU::ComputeJX(), pba::ProgramCPU::ComputeJX_(), and X.
DenormalizeData()
template<class Float > void pba::SparseBundleCPU< Float >::DenormalizeData protected
Definition at line 3391 of file SparseBundleCPU.cpp.
DumpCooJacobian()
template<class Float > void pba::SparseBundleCPU< Float >::DumpCooJacobian protected
Definition at line 3720 of file SparseBundleCPU.cpp.
References width.
EnableRadialDistortion()
template<class Float > virtual void pba::SparseBundleCPU< Float >::EnableRadialDistortion (DistortionT type) inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 263 of file SparseBundleCPU.h.
References pba::ConfigBA::__use_radial_distortion, and type.
EvaluateDeltaNorm()
template<class Float > float pba::SparseBundleCPU< Float >::EvaluateDeltaNorm protected
Definition at line 3895 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeVectorNorm(), POINT_ALIGN, and pba::avec< Float >::set().
EvaluateJacobians()
template<class Float > void pba::SparseBundleCPU< Float >::EvaluateJacobians protected
Definition at line 3015 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeJacobian(), and NULL.
EvaluateProjection()
template<class Float > float pba::SparseBundleCPU< Float >::EvaluateProjection (VectorF & cam, VectorF & point, VectorF & proj) protected
Definition at line 3117 of file SparseBundleCPU.cpp.
References pba::avec< Float >::begin(), pba::ProgramCPU::ComputeProjection(), pba::ProgramCPU::ComputeProjectionQ(), and pba::ProgramCPU::ComputeVectorNorm().
EvaluateProjectionX()
template<class Float > float pba::SparseBundleCPU< Float >::EvaluateProjectionX (VectorF & cam, VectorF & point, VectorF & proj) protected
Definition at line 3132 of file SparseBundleCPU.cpp.
References pba::avec< Float >::begin(), pba::ProgramCPU::ComputeProjectionQ(), pba::ProgramCPU::ComputeProjectionX(), and pba::ProgramCPU::ComputeVectorNorm().
GetCurrentIteration()
template<class Float > virtual int pba::SparseBundleCPU< Float >::GetCurrentIteration () inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 255 of file SparseBundleCPU.h.
References pba::ConfigBA::__current_iteration.
GetMeanSquaredError()
template<class Float > float pba::SparseBundleCPU< Float >::GetMeanSquaredError virtual
Reimplemented from pba::ParallelBA.
Definition at line 2644 of file SparseBundleCPU.cpp.
GetParameterLength()
template<class Float > int pba::SparseBundleCPU< Float >::GetParameterLength protected
Definition at line 2683 of file SparseBundleCPU.cpp.
References POINT_ALIGN.
InitializeBundle()
template<class Float > int pba::SparseBundleCPU< Float >::InitializeBundle protected
Definition at line 2671 of file SparseBundleCPU.cpp.
InitializeStorageForCG()
template<class Float > bool pba::SparseBundleCPU< Float >::InitializeStorageForCG protected
Definition at line 2963 of file SparseBundleCPU.cpp.
References ALLOCATE_OPTIONAL_DATA, and ALLOCATE_REQUIRED_DATA.
InitializeStorageForSFM()
template<class Float > bool pba::SparseBundleCPU< Float >::InitializeStorageForSFM protected
Definition at line 2742 of file SparseBundleCPU.cpp.
References ALLOCATE_OPTIONAL_DATA, ALLOCATE_REQUIRED_DATA, copy, and POINT_ALIGN.
NonlinearOptimizeLM()
template<class Float > void pba::SparseBundleCPU< Float >::NonlinearOptimizeLM protected
Definition at line 3910 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeJtE(), cloudViewer::utility::floor(), max(), pba::avec< Float >::size(), and pba::ProgramCPU::UpdateCameraPoint().
NormalizeData()
template<class Float > void pba::SparseBundleCPU< Float >::NormalizeData protected
Definition at line 2710 of file SparseBundleCPU.cpp.
NormalizeDataD()
template<class Float > void pba::SparseBundleCPU< Float >::NormalizeDataD protected
Definition at line 3286 of file SparseBundleCPU.cpp.
References pba::CameraT_< FT >::f, fabs(), pba::CameraT_< FT >::m, max(), min(), and pba::CameraT_< FT >::t.
NormalizeDataF()
template<class Float > void pba::SparseBundleCPU< Float >::NormalizeDataF protected
Definition at line 3228 of file SparseBundleCPU.cpp.
References copy.
ParseParam()
template<class Float > virtual void pba::SparseBundleCPU< Float >::ParseParam (int narg, char ** argv) inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 266 of file SparseBundleCPU.h.
References pba::ConfigBA::ParseParam().
PrepareJacobianNormalization()
template<class Float > void pba::SparseBundleCPU< Float >::PrepareJacobianNormalization protected
Definition at line 2992 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeDiagonal(), pba::ProgramCPU::ComputeRSQRT(), pba::ProgramCPU::ComputeSQRT(), and pba::avec< Float >::swap().
ProcessIndexCameraQ()
template<class Float > bool pba::SparseBundleCPU< Float >::ProcessIndexCameraQ (std::vector< int > & qmap, std::vector< int > & qlist) protected
Definition at line 2848 of file SparseBundleCPU.cpp.
References error(), and NULL.
ProcessWeightCameraQ()
template<class Float > void pba::SparseBundleCPU< Float >::ProcessWeightCameraQ (std::vector< int > & cpnum, std::vector< int > & qmap, Float * qmapw, Float * qlistw) protected
Definition at line 2919 of file SparseBundleCPU.cpp.
RunBundleAdjustment()
template<class Float > int pba::SparseBundleCPU< Float >::RunBundleAdjustment virtual
Reimplemented from pba::ParallelBA.
Definition at line 2650 of file SparseBundleCPU.cpp.
RunProfileSteps()
template<class Float > void pba::SparseBundleCPU< Float >::RunProfileSteps protected
Definition at line 4193 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeDiagonal(), pba::ProgramCPU::ComputeJtE(), pba::ProgramCPU::ComputeJX(), pba::ProgramCPU::ComputeSAXPY(), pba::ProgramCPU::ComputeSXYPZ(), pba::ProgramCPU::ComputeVectorDot(), pba::ProgramCPU::ComputeVectorNorm(), pba::ProgramCPU::ComputeVectorNormW(), max(), PROFILE, PROTILE, PROTILE2, PROXILE, pba::ProgramCPU::SetVectorZero(), and pba::ProgramCPU::UpdateCameraPoint().
RunTestIterationLM()
template<class Float > void pba::SparseBundleCPU< Float >::RunTestIterationLM (bool reduced) protected
Definition at line 3781 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeJtE(), pba::ProgramCPU::ComputeJX(), pba::ProgramCPU::ComputeVectorDot(), pba::ProgramCPU::ComputeVectorNorm(), and pba::ProgramCPU::UpdateCameraPoint().
SaveBundleRecord()
template<class Float > void pba::SparseBundleCPU< Float >::SaveBundleRecord (int iter, float res, float damping, float & g_norm, float & g_inf) protected
Definition at line 3105 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeVectorMax(), pba::ProgramCPU::ComputeVectorNorm(), and pba::ConfigBA::SaveBundleRecord().
SaveUpdatedSystem()
template<class Float > float pba::SparseBundleCPU< Float >::SaveUpdatedSystem (float residual_reduction, float dx_sqnorm, float damping) protected
save the new motion/struture
Definition at line 3825 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeJX(), pba::ProgramCPU::ComputeVectorDot(), pba::ProgramCPU::ComputeVectorNorm(), pba::ProgramCPU::ComputeVectorNormW(), POINT_ALIGN, and pba::avec< Float >::set().
SetCameraData()
template<class Float > void pba::SparseBundleCPU< Float >::SetCameraData (size_t ncam, CameraT * cams) virtual
Reimplemented from pba::ParallelBA.
Definition at line 2614 of file SparseBundleCPU.cpp.
References NULL.
SetFixedIntrinsics()
template<class Float > virtual void pba::SparseBundleCPU< Float >::SetFixedIntrinsics (bool fixed) inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 262 of file SparseBundleCPU.h.
References pba::ConfigBA::__fixed_intrinsics.
SetFocalMask()
template<class Float > void pba::SparseBundleCPU< Float >::SetFocalMask (const int * fmask, float weight) virtual
Reimplemented from pba::ParallelBA.
Definition at line 2622 of file SparseBundleCPU.cpp.
SetNextBundleMode()
template<class Float > virtual void pba::SparseBundleCPU< Float >::SetNextBundleMode (BundleModeT mode) inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 259 of file SparseBundleCPU.h.
References pba::ConfigBA::__bundle_mode_next.
SetNextTimeBudget()
template<class Float > virtual void pba::SparseBundleCPU< Float >::SetNextTimeBudget (int seconds) inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 256 of file SparseBundleCPU.h.
References pba::ConfigBA::__bundle_time_budget, and seconds.
SetPointData()
template<class Float > void pba::SparseBundleCPU< Float >::SetPointData (size_t npoint, Point3D * pts) virtual
Reimplemented from pba::ParallelBA.
Definition at line 2628 of file SparseBundleCPU.cpp.
SetProjection()
template<class Float > void pba::SparseBundleCPU< Float >::SetProjection (size_t nproj, const Point2D * imgpts, const int * point_idx, const int * cam_idx) virtual
Reimplemented from pba::ParallelBA.
Definition at line 2634 of file SparseBundleCPU.cpp.
SolveNormalEquation()
template<class Float > int pba::SparseBundleCPU< Float >::SolveNormalEquation (float lambda) protected
Definition at line 3703 of file SparseBundleCPU.cpp.
SolveNormalEquationPCGB()
template<class Float > int pba::SparseBundleCPU< Float >::SolveNormalEquationPCGB (float lambda) protected
Definition at line 3576 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeJtE(), pba::ProgramCPU::ComputeJX(), pba::ProgramCPU::ComputeSAX(), pba::ProgramCPU::ComputeSAXPY(), pba::ProgramCPU::ComputeSXYPZ(), pba::ProgramCPU::ComputeVectorDot(), pba::ProgramCPU::ComputeVectorNorm(), pba::ProgramCPU::ComputeVectorNormW(), fabs(), and min().
SolveNormalEquationPCGX()
template<class Float > int pba::SparseBundleCPU< Float >::SolveNormalEquationPCGX (float lambda) protected
Definition at line 3423 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeJtE(), pba::ProgramCPU::ComputeJX(), pba::ProgramCPU::ComputeSAX(), pba::ProgramCPU::ComputeSAXPY(), pba::ProgramCPU::ComputeSXYPZ(), pba::ProgramCPU::ComputeVectorDot(), pba::ProgramCPU::ComputeVectorNorm(), pba::ProgramCPU::ComputeVectorNormW(), pba::avec< Float >::data(), fabs(), min(), and pba::avec< Float >::set().
TransferDataToHost()
template<class Float > void pba::SparseBundleCPU< Float >::TransferDataToHost protected
Definition at line 2717 of file SparseBundleCPU.cpp.
References copy.
UpdateCameraPoint()
template<class Float > float pba::SparseBundleCPU< Float >::UpdateCameraPoint (VectorF & dx, VectorF & cuImageTempProj) protected
Definition at line 3796 of file SparseBundleCPU.cpp.
References pba::ProgramCPU::ComputeVXY(), POINT_ALIGN, and pba::ProgramCPU::UpdateCameraPoint().
ValidateInputData()
template<class Float > int pba::SparseBundleCPU< Float >::ValidateInputData protected
Definition at line 2661 of file SparseBundleCPU.cpp.
References NULL.
Member Data Documentation
_camera_data
template<class Float > CameraT* pba::SparseBundleCPU< Float >::_camera_data protected
Definition at line 156 of file SparseBundleCPU.h.
_camera_idx
template<class Float > const int* pba::SparseBundleCPU< Float >::_camera_idx protected
Definition at line 161 of file SparseBundleCPU.h.
_cuBlockPC
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuBlockPC protected
Definition at line 185 of file SparseBundleCPU.h.
_cuCameraData
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuCameraData protected
Definition at line 169 of file SparseBundleCPU.h.
_cuCameraDataEX
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuCameraDataEX protected
Definition at line 170 of file SparseBundleCPU.h.
_cuCameraMeasurementList
template<class Float > VectorI pba::SparseBundleCPU< Float >::_cuCameraMeasurementList protected
Definition at line 181 of file SparseBundleCPU.h.
_cuCameraMeasurementListT
template<class Float > VectorI pba::SparseBundleCPU< Float >::_cuCameraMeasurementListT protected
Definition at line 182 of file SparseBundleCPU.h.
_cuCameraMeasurementMap
template<class Float > VectorI pba::SparseBundleCPU< Float >::_cuCameraMeasurementMap protected
Definition at line 180 of file SparseBundleCPU.h.
_cuCameraQList
template<class Float > VectorI pba::SparseBundleCPU< Float >::_cuCameraQList protected
Definition at line 201 of file SparseBundleCPU.h.
_cuCameraQListW
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuCameraQListW protected
Definition at line 204 of file SparseBundleCPU.h.
_cuCameraQMap
template<class Float > VectorI pba::SparseBundleCPU< Float >::_cuCameraQMap protected
Definition at line 202 of file SparseBundleCPU.h.
_cuCameraQMapW
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuCameraQMapW protected
Definition at line 203 of file SparseBundleCPU.h.
_cuImageProj
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuImageProj protected
Definition at line 174 of file SparseBundleCPU.h.
_cuJacobianCamera
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuJacobianCamera protected
Definition at line 175 of file SparseBundleCPU.h.
_cuJacobianCameraT
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuJacobianCameraT protected
Definition at line 177 of file SparseBundleCPU.h.
_cuJacobianPoint
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuJacobianPoint protected
Definition at line 176 of file SparseBundleCPU.h.
_cuMeasurements
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuMeasurements protected
Definition at line 173 of file SparseBundleCPU.h.
_cuPointData
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuPointData protected
Definition at line 171 of file SparseBundleCPU.h.
_cuPointDataEX
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuPointDataEX protected
Definition at line 172 of file SparseBundleCPU.h.
_cuPointMeasurementMap
template<class Float > VectorI pba::SparseBundleCPU< Float >::_cuPointMeasurementMap protected
Definition at line 179 of file SparseBundleCPU.h.
_cuProjectionMap
template<class Float > VectorI pba::SparseBundleCPU< Float >::_cuProjectionMap protected
Definition at line 178 of file SparseBundleCPU.h.
_cuVectorJJ
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuVectorJJ protected
Definition at line 190 of file SparseBundleCPU.h.
_cuVectorJtE
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuVectorJtE protected
LM normal equation.
Definition at line 189 of file SparseBundleCPU.h.
_cuVectorJX
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuVectorJX protected
Definition at line 191 of file SparseBundleCPU.h.
_cuVectorPK
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuVectorPK protected
Definition at line 193 of file SparseBundleCPU.h.
_cuVectorRK
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuVectorRK protected
Definition at line 195 of file SparseBundleCPU.h.
_cuVectorSJ
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuVectorSJ protected
Definition at line 186 of file SparseBundleCPU.h.
_cuVectorXK
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuVectorXK protected
Definition at line 192 of file SparseBundleCPU.h.
_cuVectorZK
template<class Float > VectorF pba::SparseBundleCPU< Float >::_cuVectorZK protected
Definition at line 194 of file SparseBundleCPU.h.
_focal_mask
template<class Float > const int* pba::SparseBundleCPU< Float >::_focal_mask protected
Definition at line 163 of file SparseBundleCPU.h.
_imgpt_data
template<class Float > const float* pba::SparseBundleCPU< Float >::_imgpt_data protected
Definition at line 160 of file SparseBundleCPU.h.
_num_camera
template<class Float > int pba::SparseBundleCPU< Float >::_num_camera protected
Definition at line 153 of file SparseBundleCPU.h.
_num_imgpt
template<class Float > int pba::SparseBundleCPU< Float >::_num_imgpt protected
Definition at line 155 of file SparseBundleCPU.h.
_num_imgpt_q
template<class Float > int pba::SparseBundleCPU< Float >::_num_imgpt_q protected
Definition at line 199 of file SparseBundleCPU.h.
_num_point
template<class Float > int pba::SparseBundleCPU< Float >::_num_point protected
Definition at line 154 of file SparseBundleCPU.h.
_point_data
template<class Float > float* pba::SparseBundleCPU< Float >::_point_data protected
Definition at line 157 of file SparseBundleCPU.h.
_point_idx
template<class Float > const int* pba::SparseBundleCPU< Float >::_point_idx protected
Definition at line 162 of file SparseBundleCPU.h.
_projection_sse
template<class Float > float pba::SparseBundleCPU< Float >::_projection_sse protected
Definition at line 166 of file SparseBundleCPU.h.
_weight_q
template<class Float > float pba::SparseBundleCPU< Float >::_weight_q protected
Definition at line 200 of file SparseBundleCPU.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/PBA/SparseBundleCPU.h
/root/ACloudViewer/libs/Reconstruction/lib/PBA/SparseBundleCPU.cpp