ACloudViewer: e57::ReaderImpl Class Reference
e57::ReaderImpl Class Reference
most of the functions follows Reader
#include <ReaderImpl.h>
Public Member Functions
ReaderImpl (const ustring &filePath)
~ReaderImpl ()
bool IsOpen () const
bool Close ()
bool GetE57Root (E57Root &fileHeader) const
int64_t GetImage2DCount () const
bool ReadImage2D (int64_t imageIndex, Image2D &Image2DHeader) const
bool GetImage2DSizes (int64_t imageIndex, Image2DProjection &imageProjection, Image2DType &imageType, int64_t &imageWidth, int64_t &imageHeight, int64_t &imageSize, Image2DType &imageMaskType, Image2DType &imageVisualType) const
int64_t ReadImage2DData (int64_t imageIndex, Image2DProjection imageProjection, Image2DType imageType, void *pBuffer, int64_t start, int64_t count) const
int64_t GetData3DCount () const
bool ReadData3D (int64_t dataIndex, Data3D &data3DHeader) const
bool GetData3DSizes (int64_t dataIndex, int64_t &rowMax, int64_t &columnMax, int64_t &pointsSize, int64_t &groupsSize, int64_t &countSize, bool &bColumnIndex) const
bool ReadData3DGroupsData (int64_t dataIndex, int64_t groupCount, int64_t *idElementValue, int64_t *startPointIndex, int64_t *pointCount) const
template<typename COORDTYPE >
CompressedVectorReader SetUpData3DPointsData (int64_t dataIndex, size_t pointCount, const Data3DPointsData_t< COORDTYPE > &buffers) const
StructureNode GetRawE57Root () const
VectorNode GetRawData3D () const
VectorNode GetRawImages2D () const
ImageFile GetRawIMF () const
Detailed Description
most of the functions follows Reader
Definition at line 36 of file ReaderImpl.h.
Constructor & Destructor Documentation
ReaderImpl()
e57::ReaderImpl::ReaderImpl (const ustring & filePath)
Definition at line 33 of file ReaderImpl.cpp.
~ReaderImpl()
e57::ReaderImpl::~ReaderImpl ()
Definition at line 39 of file ReaderImpl.cpp.
References Close(), and IsOpen().
Member Function Documentation
Close()
bool e57::ReaderImpl::Close ()
Definition at line 54 of file ReaderImpl.cpp.
References e57::ImageFile::close(), and IsOpen().
Referenced by ~ReaderImpl().
GetData3DCount()
int64_t e57::ReaderImpl::GetData3DCount () const
Definition at line 514 of file ReaderImpl.cpp.
References e57::VectorNode::childCount().
GetData3DSizes()
bool e57::ReaderImpl::GetData3DSizes (int64_t dataIndex, int64_t & rowMax, int64_t & columnMax, int64_t & pointsSize, int64_t & groupsSize, int64_t & countSize, bool & bColumnIndex) const
Definition at line 1106 of file ReaderImpl.cpp.
References e57::VectorNode::childCount(), e57::CompressedVectorNode::childCount(), e57::StructureNode::get(), e57::VectorNode::get(), e57::StructureNode::isDefined(), IsOpen(), e57::IntegerNode::maximum(), e57::IntegerNode::minimum(), points, e57::CompressedVectorNode::prototype(), e57::IntegerNode::value(), and e57::StringNode::value().
GetE57Root()
bool e57::ReaderImpl::GetE57Root (E57Root & fileHeader) const
Definition at line 66 of file ReaderImpl.cpp.
References e57::VectorNode::childCount(), e57::E57Root::coordinateMetadata, e57::E57Root::creationDateTime, e57::E57Root::data3DSize, e57::DateTime::dateTimeValue, e57::E57Root::e57LibraryVersion, e57::E57Root::formatName, e57::StructureNode::get(), e57::E57Root::guid, e57::E57Root::images2DSize, e57::DateTime::isAtomicClockReferenced, e57::StructureNode::isDefined(), IsOpen(), e57::FloatNode::value(), e57::StringNode::value(), e57::E57Root::versionMajor, and e57::E57Root::versionMinor.
GetImage2DCount()
int64_t e57::ReaderImpl::GetImage2DCount () const
Definition at line 103 of file ReaderImpl.cpp.
References e57::VectorNode::childCount().
GetImage2DSizes()
bool e57::ReaderImpl::GetImage2DSizes (int64_t imageIndex, Image2DProjection & imageProjection, Image2DType & imageType, int64_t & imageWidth, int64_t & imageHeight, int64_t & imageSize, Image2DType & imageMaskType, Image2DType & imageVisualType) const
Definition at line 411 of file ReaderImpl.cpp.
References e57::VectorNode::childCount(), e57::E57_CYLINDRICAL, e57::E57_NO_IMAGE, e57::E57_NO_PROJECTION, e57::E57_PINHOLE, e57::E57_SPHERICAL, e57::E57_VISUAL, e57::VectorNode::get(), and image.
GetRawData3D()
VectorNode e57::ReaderImpl::GetRawData3D () const
Definition at line 524 of file ReaderImpl.cpp.
GetRawE57Root()
StructureNode e57::ReaderImpl::GetRawE57Root () const
Definition at line 519 of file ReaderImpl.cpp.
GetRawImages2D()
VectorNode e57::ReaderImpl::GetRawImages2D () const
Definition at line 529 of file ReaderImpl.cpp.
GetRawIMF()
ImageFile e57::ReaderImpl::GetRawIMF () const
Definition at line 534 of file ReaderImpl.cpp.
IsOpen()
bool e57::ReaderImpl::IsOpen () const
Definition at line 48 of file ReaderImpl.cpp.
References e57::ImageFile::isOpen().
Referenced by Close(), GetData3DSizes(), GetE57Root(), ReadData3D(), ReadImage2D(), and ~ReaderImpl().
ReadData3D()
bool e57::ReaderImpl::ReadData3D (int64_t dataIndex, Data3D & data3DHeader) const
Definition at line 539 of file ReaderImpl.cpp.
References e57::Data3D::acquisitionEnd, e57::Data3D::acquisitionStart, e57::PointStandardizedFieldsAvailable::angleMaximum, e57::PointStandardizedFieldsAvailable::angleMinimum, e57::PointStandardizedFieldsAvailable::angleScaledInteger, e57::Data3D::atmosphericPressure, e57::SphericalBounds::azimuthEnd, e57::SphericalBounds::azimuthStart, e57::Data3D::cartesianBounds, e57::PointStandardizedFieldsAvailable::cartesianInvalidStateField, e57::PointStandardizedFieldsAvailable::cartesianXField, e57::PointStandardizedFieldsAvailable::cartesianYField, e57::PointStandardizedFieldsAvailable::cartesianZField, e57::VectorNode::childCount(), e57::CompressedVectorNode::childCount(), e57::PointStandardizedFieldsAvailable::colorBlueField, e57::ColorLimits::colorBlueMaximum, e57::ColorLimits::colorBlueMinimum, e57::PointStandardizedFieldsAvailable::colorGreenField, e57::ColorLimits::colorGreenMaximum, e57::ColorLimits::colorGreenMinimum, e57::Data3D::colorLimits, e57::PointStandardizedFieldsAvailable::colorRedField, e57::ColorLimits::colorRedMaximum, e57::ColorLimits::colorRedMinimum, e57::PointStandardizedFieldsAvailable::columnIndexField, e57::PointStandardizedFieldsAvailable::columnIndexMaximum, e57::IndexBounds::columnMaximum, e57::IndexBounds::columnMinimum, e57::DateTime::dateTimeValue, e57::Data3D::description, e57::E57_FLOAT, e57::E57_INTEGER, e57::E57_NOT_SCALED_USE_FLOAT, e57::E57_NOT_SCALED_USE_INTEGER, e57::E57_SCALED_INTEGER, e57::SphericalBounds::elevationMaximum, e57::SphericalBounds::elevationMinimum, e57::ImageFile::extensionsLookupPrefix(), e57::StructureNode::get(), e57::VectorNode::get(), e57::PointGroupingSchemes::groupingByLine, e57::GroupingByLine::groupsSize, e57::Data3D::guid, e57::GroupingByLine::idElementName, e57::Data3D::indexBounds, e57::PointStandardizedFieldsAvailable::intensityField, e57::Data3D::intensityLimits, e57::IntensityLimits::intensityMaximum, e57::IntensityLimits::intensityMinimum, e57::PointStandardizedFieldsAvailable::intensityScaledInteger, e57::DateTime::isAtomicClockReferenced, e57::PointStandardizedFieldsAvailable::isColorInvalidField, e57::StructureNode::isDefined(), e57::PointStandardizedFieldsAvailable::isIntensityInvalidField, IsOpen(), e57::PointStandardizedFieldsAvailable::isTimeStampInvalidField, e57::IntegerNode::maximum(), e57::ScaledIntegerNode::maximum(), e57::FloatNode::maximum(), e57::ScaledIntegerNode::minimum(), e57::FloatNode::minimum(), e57::Data3D::name, e57::PointStandardizedFieldsAvailable::normalX, e57::PointStandardizedFieldsAvailable::normalY, e57::PointStandardizedFieldsAvailable::normalZ, offset, e57::ScaledIntegerNode::offset(), e57::Data3D::originalGuids, e57::GroupingByLine::pointCountSize, e57::Data3D::pointFields, e57::Data3D::pointGroupingSchemes, e57::PointStandardizedFieldsAvailable::pointRangeMaximum, e57::PointStandardizedFieldsAvailable::pointRangeMinimum, e57::PointStandardizedFieldsAvailable::pointRangeScaledInteger, points, e57::Data3D::pointsSize, e57::Data3D::pose, e57::CompressedVectorNode::prototype(), e57::SphericalBounds::rangeMaximum, e57::SphericalBounds::rangeMinimum, e57::Data3D::relativeHumidity, e57::PointStandardizedFieldsAvailable::returnCountField, e57::PointStandardizedFieldsAvailable::returnIndexField, e57::IndexBounds::returnMaximum, e57::PointStandardizedFieldsAvailable::returnMaximum, e57::IndexBounds::returnMinimum, e57::RigidBodyTransform::rotation, e57::PointStandardizedFieldsAvailable::rowIndexField, e57::PointStandardizedFieldsAvailable::rowIndexMaximum, e57::IndexBounds::rowMaximum, e57::IndexBounds::rowMinimum, e57::ScaledIntegerNode::scale(), e57::Data3D::sensorFirmwareVersion, e57::Data3D::sensorHardwareVersion, e57::Data3D::sensorModel, e57::Data3D::sensorSerialNumber, e57::Data3D::sensorSoftwareVersion, e57::Data3D::sensorVendor, e57::PointStandardizedFieldsAvailable::sphericalAzimuthField, e57::Data3D::sphericalBounds, e57::PointStandardizedFieldsAvailable::sphericalElevationField, e57::PointStandardizedFieldsAvailable::sphericalInvalidStateField, e57::PointStandardizedFieldsAvailable::sphericalRangeField, e57::Data3D::temperature, e57::PointStandardizedFieldsAvailable::timeMaximum, e57::PointStandardizedFieldsAvailable::timeMinimum, e57::PointStandardizedFieldsAvailable::timeScaledInteger, e57::PointStandardizedFieldsAvailable::timeStampField, e57::RigidBodyTransform::translation, e57::Node::type(), e57::IntegerNode::value(), e57::FloatNode::value(), e57::StringNode::value(), e57::Quaternion::w, e57::Translation::x, e57::Quaternion::x, e57::CartesianBounds::xMaximum, e57::CartesianBounds::xMinimum, e57::Translation::y, e57::Quaternion::y, e57::CartesianBounds::yMaximum, e57::CartesianBounds::yMinimum, e57::Translation::z, e57::Quaternion::z, e57::CartesianBounds::zMaximum, and e57::CartesianBounds::zMinimum.
ReadData3DGroupsData()
bool e57::ReaderImpl::ReadData3DGroupsData (int64_t dataIndex, int64_t groupCount, int64_t * idElementValue, int64_t * startPointIndex, int64_t * pointCount) const
Definition at line 1222 of file ReaderImpl.cpp.
References e57::StructureNode::childCount(), e57::VectorNode::childCount(), e57::CompressedVectorReader::close(), e57::Node::elementName(), e57::StructureNode::get(), e57::VectorNode::get(), e57::StructureNode::isDefined(), name, e57::CompressedVectorNode::prototype(), e57::CompressedVectorReader::read(), and e57::CompressedVectorNode::reader().
ReadImage2D()
bool e57::ReaderImpl::ReadImage2D (int64_t imageIndex, Image2D & Image2DHeader) const
Definition at line 109 of file ReaderImpl.cpp.
References e57::Image2D::acquisitionDateTime, e57::Image2D::associatedData3DGuid, e57::BlobNode::byteCount(), e57::VectorNode::childCount(), e57::Image2D::cylindricalRepresentation, e57::DateTime::dateTimeValue, e57::Image2D::description, e57::PinholeRepresentation::focalLength, e57::StructureNode::get(), e57::VectorNode::get(), e57::Image2D::guid, image, e57::VisualReferenceRepresentation::imageHeight, e57::PinholeRepresentation::imageHeight, e57::SphericalRepresentation::imageHeight, e57::CylindricalRepresentation::imageHeight, e57::VisualReferenceRepresentation::imageMaskSize, e57::PinholeRepresentation::imageMaskSize, e57::SphericalRepresentation::imageMaskSize, e57::CylindricalRepresentation::imageMaskSize, e57::VisualReferenceRepresentation::imageWidth, e57::PinholeRepresentation::imageWidth, e57::SphericalRepresentation::imageWidth, e57::CylindricalRepresentation::imageWidth, e57::DateTime::isAtomicClockReferenced, e57::StructureNode::isDefined(), IsOpen(), e57::VisualReferenceRepresentation::jpegImageSize, e57::PinholeRepresentation::jpegImageSize, e57::SphericalRepresentation::jpegImageSize, e57::CylindricalRepresentation::jpegImageSize, e57::Image2D::name, e57::Image2D::pinholeRepresentation, e57::PinholeRepresentation::pixelHeight, e57::SphericalRepresentation::pixelHeight, e57::CylindricalRepresentation::pixelHeight, e57::PinholeRepresentation::pixelWidth, e57::SphericalRepresentation::pixelWidth, e57::CylindricalRepresentation::pixelWidth, e57::VisualReferenceRepresentation::pngImageSize, e57::PinholeRepresentation::pngImageSize, e57::SphericalRepresentation::pngImageSize, e57::CylindricalRepresentation::pngImageSize, e57::Image2D::pose, e57::PinholeRepresentation::principalPointX, e57::PinholeRepresentation::principalPointY, e57::CylindricalRepresentation::principalPointY, e57::CylindricalRepresentation::radius, e57::RigidBodyTransform::rotation, e57::Image2D::sensorModel, e57::Image2D::sensorSerialNumber, e57::Image2D::sensorVendor, e57::Image2D::sphericalRepresentation, e57::RigidBodyTransform::translation, e57::FloatNode::value(), e57::StringNode::value(), e57::Image2D::visualReferenceRepresentation, e57::Quaternion::w, e57::Translation::x, e57::Quaternion::x, e57::Translation::y, e57::Quaternion::y, e57::Translation::z, and e57::Quaternion::z.
ReadImage2DData()
int64_t e57::ReaderImpl::ReadImage2DData (int64_t imageIndex, Image2DProjection imageProjection, Image2DType imageType, void * pBuffer, int64_t start, int64_t count) const
Definition at line 463 of file ReaderImpl.cpp.
References e57::VectorNode::childCount(), count, e57::E57_CYLINDRICAL, e57::E57_NO_PROJECTION, e57::E57_PINHOLE, e57::E57_SPHERICAL, e57::E57_VISUAL, e57::VectorNode::get(), and image.
SetUpData3DPointsData()
template<typename COORDTYPE > template CompressedVectorReader e57::ReaderImpl::SetUpData3DPointsData (int64_t dataIndex, size_t pointCount, const Data3DPointsData_t< COORDTYPE > & buffers) const
Definition at line 1284 of file ReaderImpl.cpp.
References e57::Data3DPointsData_t< COORDTYPE >::cartesianInvalidState, e57::Data3DPointsData_t< COORDTYPE >::cartesianX, e57::Data3DPointsData_t< COORDTYPE >::cartesianY, e57::Data3DPointsData_t< COORDTYPE >::cartesianZ, e57::StructureNode::childCount(), e57::Data3DPointsData_t< COORDTYPE >::colorBlue, e57::Data3DPointsData_t< COORDTYPE >::colorGreen, e57::Data3DPointsData_t< COORDTYPE >::colorRed, e57::Data3DPointsData_t< COORDTYPE >::columnIndex, count, e57::E57_SCALED_INTEGER, e57::Node::elementName(), e57::ImageFile::extensionsLookupPrefix(), e57::StructureNode::get(), e57::VectorNode::get(), e57::Data3DPointsData_t< COORDTYPE >::intensity, e57::Data3DPointsData_t< COORDTYPE >::isColorInvalid, e57::StructureNode::isDefined(), e57::Data3DPointsData_t< COORDTYPE >::isIntensityInvalid, e57::Data3DPointsData_t< COORDTYPE >::isTimeStampInvalid, name, e57::Data3DPointsData_t< COORDTYPE >::normalX, e57::Data3DPointsData_t< COORDTYPE >::normalY, e57::Data3DPointsData_t< COORDTYPE >::normalZ, points, e57::Data3DPointsData_t< COORDTYPE >::returnCount, e57::Data3DPointsData_t< COORDTYPE >::returnIndex, e57::Data3DPointsData_t< COORDTYPE >::rowIndex, e57::Data3DPointsData_t< COORDTYPE >::sphericalAzimuth, e57::Data3DPointsData_t< COORDTYPE >::sphericalElevation, e57::Data3DPointsData_t< COORDTYPE >::sphericalInvalidState, e57::Data3DPointsData_t< COORDTYPE >::sphericalRange, e57::Data3DPointsData_t< COORDTYPE >::timeStamp, type, and e57::Node::type().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qE57IO/extern/libE57Format/src/ReaderImpl.h
/root/ACloudViewer/plugins/core/IO/qE57IO/extern/libE57Format/src/ReaderImpl.cpp