ACloudViewer: ProfileLoader Class Reference
ProfileLoader Class Reference
Loads a 2D profile form a custom (ASCII) file.
#include <profileLoader.h>
Static Public Member Functions
static ccPolyline * Load (QString filename, CCVector3 &origin, ecvMainAppInterface *app=0)
Loads a 2D profile from a file.
Detailed Description
Loads a 2D profile form a custom (ASCII) file.
Definition at line 20 of file profileLoader.h.
Member Function Documentation
Load()
ccPolyline * ProfileLoader::Load (QString filename, CCVector3 & origin, ecvMainAppInterface * app = 0) static
Loads a 2D profile from a file.
The file must have a particular organization (see the code for more details). Notably the profile is associated to a 3D origin. Only the X and Y coordinates of the polyline's vertices will be used: X = radius and Y = height (Z = 0).
Parameters
[in] filename filename
[out] origin profile origin
[in] app main application handle for displaying messages (optional)
Returns
loaded polyline (or 0 if an error occurred)
Definition at line 25 of file profileLoader.cpp.
References ccHObject::addChild(), cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::ReferenceCloud::addPointIndex(), count, error(), ecvColor::green(), points, qtCompatSplitRegex(), cloudViewer::ReferenceCloud::reserve(), ccPointCloud::reserve(), ccPolyline::set2DMode(), cloudViewer::Polyline::setClosed(), ccPolyline::setColor(), ccObject::setEnabled(), ccObject::setLocked(), ccObject::setName(), ccDrawableObject::showColors(), QtCompat::SkipEmptyParts, Vector2Tpl< Type >::x, Tuple3Tpl< Type >::x, Vector2Tpl< Type >::y, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by qSRA::loadProfile().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qSRA/include/profileLoader.h
/root/ACloudViewer/plugins/core/Standard/qSRA/src/profileLoader.cpp