ACloudViewer: PdmsTools::PdmsCommands::ElementCreation Class Reference
PdmsTools::PdmsCommands::ElementCreation Class Reference
#include <PdmsTools.h>
Public Member Functions
ElementCreation ()
virtual bool handle (const char *str)
virtual bool handle (Token t)
bool isValid () const
virtual bool execute (PdmsObjects::GenericItem *&item) const
Public Member Functions inherited from PdmsTools::PdmsCommands::Command
Command (Token t)
Command (const Command &com)
virtual ~Command ()
virtual bool handle (PointCoordinateType numvalue)
Static Public Member Functions
static const char * GetDefaultElementName (Token token)
Static Public Member Functions inherited from PdmsTools::PdmsCommands::Command
static Command * Create (Token t)
Factory.
Public Attributes
Token elementType
std::vector< std::string > path
Public Attributes inherited from PdmsTools::PdmsCommands::Command
Token command
Protected Member Functions
bool splitPath (const char *str)
Detailed Description
Definition at line 614 of file PdmsTools.h.
Constructor & Destructor Documentation
ElementCreation()
PdmsTools::PdmsCommands::ElementCreation::ElementCreation () inline
Definition at line 619 of file PdmsTools.h.
References elementType, and PdmsTools::PDMS_INVALID_TOKEN.
Member Function Documentation
execute()
bool ElementCreation::execute (PdmsObjects::GenericItem *& item) const virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 607 of file PdmsTools.cpp.
References PdmsTools::PdmsObjects::GenericItem::creator, PdmsTools::PdmsObjects::Stack::Destroy(), PdmsTools::PdmsObjects::GenericItem::getRoot(), memalert, name, PdmsTools::PdmsObjects::GenericItem::name, PdmsTools::PdmsObjects::GenericItem::owner, cloudViewer::t::geometry::path, PdmsTools::PDMS_BOX, PdmsTools::PDMS_CONE, PdmsTools::PDMS_CTORUS, PdmsTools::PDMS_DISH, PdmsTools::PDMS_EQUIPMENT, PdmsTools::PDMS_EXTRU, PdmsTools::PDMS_GROUP, PdmsTools::PDMS_LOOP, PdmsTools::PDMS_NBOX, PdmsTools::PDMS_NEXTRU, PdmsTools::PDMS_PYRAMID, PdmsTools::PDMS_RTORUS, PdmsTools::PDMS_SCYLINDER, PdmsTools::PDMS_SITE, PdmsTools::PDMS_SNOUT, PdmsTools::PDMS_STRUCTURE, PdmsTools::PDMS_SUBSTRUCTURE, PdmsTools::PDMS_VERTEX, PdmsTools::PDMS_WORLD, PdmsTools::PDMS_ZONE, PdmsTools::PdmsObjects::GenericItem::push(), s_elementsStack, and PdmsTools::PdmsObjects::GenericItem::scan().
GetDefaultElementName()
const char * ElementCreation::GetDefaultElementName (Token token) static
Definition at line 556 of file PdmsTools.cpp.
References PdmsTools::PDMS_BOX, PdmsTools::PDMS_CONE, PdmsTools::PDMS_CTORUS, PdmsTools::PDMS_DISH, PdmsTools::PDMS_EQUIPMENT, PdmsTools::PDMS_EXTRU, PdmsTools::PDMS_GROUP, PdmsTools::PDMS_LOOP, PdmsTools::PDMS_NBOX, PdmsTools::PDMS_NEXTRU, PdmsTools::PDMS_PYRAMID, PdmsTools::PDMS_RTORUS, PdmsTools::PDMS_SCYLINDER, PdmsTools::PDMS_SITE, PdmsTools::PDMS_SNOUT, PdmsTools::PDMS_STRUCTURE, PdmsTools::PDMS_SUBSTRUCTURE, PdmsTools::PDMS_VERTEX, PdmsTools::PDMS_WORLD, and PdmsTools::PDMS_ZONE.
handle() [1/2]
bool ElementCreation::handle (const char * str) virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 537 of file PdmsTools.cpp.
References cloudViewer::t::geometry::path.
handle() [2/2]
bool ElementCreation::handle (Token t) virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 543 of file PdmsTools.cpp.
References PdmsTools::PdmsToken::isElement().
isValid()
bool ElementCreation::isValid () const virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 552 of file PdmsTools.cpp.
References PdmsTools::PdmsToken::isElement().
splitPath()
bool ElementCreation::splitPath (const char * str) protected
Definition at line 755 of file PdmsTools.cpp.
References cloudViewer::t::geometry::path.
Member Data Documentation
elementType
Token PdmsTools::PdmsCommands::ElementCreation::elementType
Definition at line 616 of file PdmsTools.h.
Referenced by ElementCreation().
path
std::vector<std::string> PdmsTools::PdmsCommands::ElementCreation::path
Definition at line 617 of file PdmsTools.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsTools.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsTools.cpp