ACloudViewer: cloudViewer::visualization::webrtc_server::ImageCapturer Class Reference
cloudViewer::visualization::webrtc_server::ImageCapturer Class Reference
#include <ImageCapturer.h>
Public Member Functions
ImageCapturer (const std::string &url_, const std::map< std::string, std::string > &opts)
virtual ~ImageCapturer ()
ImageCapturer (const std::map< std::string, std::string > &opts)
virtual void AddOrUpdateSink (rtc::VideoSinkInterface< webrtc::VideoFrame > *sink, const rtc::VideoSinkWants &wants) override
virtual void RemoveSink (rtc::VideoSinkInterface< webrtc::VideoFrame > *sink) override
void OnCaptureResult (const std::shared_ptr< core::Tensor > &frame)
Static Public Member Functions
static ImageCapturer * Create (const std::string &url, const std::map< std::string, std::string > &opts)
Protected Attributes
int width_
int height_
rtc::VideoBroadcaster broadcaster_
Detailed Description
Definition at line 29 of file ImageCapturer.h.
Constructor & Destructor Documentation
ImageCapturer() [1/2]
cloudViewer::visualization::webrtc_server::ImageCapturer::ImageCapturer (const std::string & url_, const std::map< std::string, std::string > & opts)
Definition at line 25 of file ImageCapturer.cpp.
Referenced by Create().
~ImageCapturer()
cloudViewer::visualization::webrtc_server::ImageCapturer::~ImageCapturer () virtual
Definition at line 29 of file ImageCapturer.cpp.
ImageCapturer() [2/2]
cloudViewer::visualization::webrtc_server::ImageCapturer::ImageCapturer (const std::map< std::string, std::string > & opts)
Definition at line 38 of file ImageCapturer.cpp.
Member Function Documentation
AddOrUpdateSink()
void cloudViewer::visualization::webrtc_server::ImageCapturer::AddOrUpdateSink (rtc::VideoSinkInterface< webrtc::VideoFrame > * sink, const rtc::VideoSinkWants & wants) override virtual
Definition at line 97 of file ImageCapturer.cpp.
References broadcaster_.
Create()
ImageCapturer * cloudViewer::visualization::webrtc_server::ImageCapturer::Create (const std::string & url, const std::map< std::string, std::string > & opts) static
Definition at line 31 of file ImageCapturer.cpp.
References ImageCapturer().
Referenced by cloudViewer::visualization::webrtc_server::ImageTrackSource::Create().
OnCaptureResult()
void cloudViewer::visualization::webrtc_server::ImageCapturer::OnCaptureResult (const std::shared_ptr< core::Tensor > & frame)
Definition at line 48 of file ImageCapturer.cpp.
References broadcaster_, frame, height, height_, LogError, width, and width_.
RemoveSink()
void cloudViewer::visualization::webrtc_server::ImageCapturer::RemoveSink (rtc::VideoSinkInterface< webrtc::VideoFrame > * sink) override virtual
Definition at line 103 of file ImageCapturer.cpp.
References broadcaster_.
Member Data Documentation
broadcaster_
rtc::VideoBroadcaster cloudViewer::visualization::webrtc_server::ImageCapturer::broadcaster_ protected
Definition at line 53 of file ImageCapturer.h.
Referenced by AddOrUpdateSink(), OnCaptureResult(), and RemoveSink().
height_
int cloudViewer::visualization::webrtc_server::ImageCapturer::height_ protected
Definition at line 52 of file ImageCapturer.h.
Referenced by OnCaptureResult().
width_
int cloudViewer::visualization::webrtc_server::ImageCapturer::width_ protected
Definition at line 51 of file ImageCapturer.h.
Referenced by OnCaptureResult().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/webrtc_server/ImageCapturer.h
/root/ACloudViewer/libs/cloudViewer/visualization/webrtc_server/ImageCapturer.cpp