ACloudViewer: PythonPlugin Class Reference
PythonPlugin Class Reference final
"Entry point" of the plugin
#include <PythonPlugin.h>
Public Member Functions
PythonPlugin (QObject *parent=nullptr)
QList< QAction * > getActions () override
Get a list of actions for this plugin.
void registerCommands (ccCommandLineInterface *cmd) override
void setMainAppInterface (ecvMainAppInterface *app) override
Sets application entry point.
void stop () override
Stops the plugin.
PythonPlugin (const PythonPlugin &)=delete
PythonPlugin (PythonPlugin &&)=delete
PythonPlugin & operator= (const PythonPlugin &)=delete
PythonPlugin & operator= (PythonPlugin &&)=delete
~PythonPlugin () noexcept override
Public Member Functions inherited from ccStdPluginInterface
ccStdPluginInterface (const QString &resourcePath=QString())
Default constructor.
virtual ~ccStdPluginInterface () override=default
Destructor.
virtual CC_PLUGIN_TYPE getType () const override
Returns plugin type (standard or OpenGL filter)
virtual ecvMainAppInterface * getMainAppInterface ()
A callback pointer to the main app interface for use by plugins.
virtual void onNewSelection (const ccHObject::Container &selectedEntities)
virtual void dispToConsole (QString message, ecvMainAppInterface::ConsoleMessageLevel level=ecvMainAppInterface::STD_CONSOLE_MESSAGE)
Shortcut to ecvMainAppInterface::dispToConsole.
Public Member Functions inherited from ccDefaultPluginInterface
virtual ~ccDefaultPluginInterface ()
virtual bool isCore () const override
Is this plugin a core plugin?
virtual QString getName () const override
Returns (short) name (for menu entry, etc.)
virtual QString getDescription () const override
Returns long name/description (for tooltip, etc.)
virtual QIcon getIcon () const override
Returns icon.
virtual ReferenceList getReferences () const override
virtual ContactList getAuthors () const override
virtual ContactList getMaintainers () const override
Public Member Functions inherited from ccPluginInterface
virtual ~ccPluginInterface ()=default
Virtual destructor.
virtual bool start ()
Starts the plugin.
virtual ccExternalFactory * getCustomObjectsFactory () const
Returns the plugin's custom object factory (if any)
Additional Inherited Members
Public Types inherited from ccPluginInterface
typedef QList< Contact > ContactList
using ReferenceList = QList< Reference >
Protected Member Functions inherited from ccDefaultPluginInterface
ccDefaultPluginInterface (const QString &resourcePath=QString())
Protected Attributes inherited from ccStdPluginInterface
ecvMainAppInterface * m_app
Main application interface.
Detailed Description
"Entry point" of the plugin
Definition at line 28 of file PythonPlugin.h.
Constructor & Destructor Documentation
PythonPlugin() [1/3]
PythonPlugin::PythonPlugin (QObject * parent = nullptr) explicit
Definition at line 36 of file PythonPlugin.cpp.
References PythonInterpreter::executionFinished(), PythonInterpreter::executionStarted(), PythonConfig::fromContainingEnvironment(), PythonConfig::initBundled(), PythonInterpreter::initialize(), PythonRuntimeSettings::isDefaultPythonEnv(), PythonConfig::IsInsideEnvironment(), PYPLUGIN_ICON_PATH, PythonRuntimeSettings::pythonEnvConfig(), PythonConfig::type(), and PythonConfig::validateAndDisplayErrors().
PythonPlugin() [2/3]
PythonPlugin::PythonPlugin (const PythonPlugin &) delete
PythonPlugin() [3/3]
PythonPlugin::PythonPlugin (PythonPlugin &&) delete
~PythonPlugin()
PythonPlugin::~PythonPlugin () override noexcept
Definition at line 427 of file PythonPlugin.cpp.
References Runtime::unsetCmdLineInterfaceInstance(), and Runtime::unsetMainAppInterfaceInstance().
Member Function Documentation
getActions()
QList< QAction * > PythonPlugin::getActions () override virtual
Get a list of actions for this plugin.
Implements ccStdPluginInterface.
Definition at line 136 of file PythonPlugin.cpp.
References ABOUT_ICON_PATH, ACTION_LAUNCHER_ICON_PATH, ADD_PYSCRIPT_ICON_PATH, DOCUMENTATION_ICON_PATH, EDITOR_ICON_PATH, PythonInterpreter::IsInitialized(), LoadSettings(), PACKAGE_MANAGER_ICON_PATH, cloudViewer::t::geometry::path, PYSCRIPTS_REGISTER_ICON_PATH, REMOVE_PYSCRIPT_ICON_PATH, REPL_ICON_PATH, RUNNER_ICON_PATH, and SETTINGS_ICON_PATH.
operator=() [1/2]
PythonPlugin& PythonPlugin::operator= (const PythonPlugin &) delete
operator=() [2/2]
PythonPlugin& PythonPlugin::operator= (PythonPlugin &&) delete
registerCommands()
void PythonPlugin::registerCommands (ccCommandLineInterface * cmd) override virtual
Registers the -PYTHON_SCRIPT command to run Python scripts in ACloudViewer's commandline mode
Reimplemented from ccPluginInterface.
Definition at line 500 of file PythonPlugin.cpp.
References ccCommandLineInterface::registerCommand(), and Runtime::setCmdLineInterfaceInstance().
setMainAppInterface()
void PythonPlugin::setMainAppInterface (ecvMainAppInterface * app) override virtual
Sets application entry point.
Called just after plugin creation by qCC
Reimplemented from ccStdPluginInterface.
Definition at line 509 of file PythonPlugin.cpp.
References ecvMainAppInterface::getMainWindow(), PythonPluginManager::loadPluginsFrom(), PythonPluginManager::loadPluginsFromEntryPoints(), LogPythonHome(), LogPythonPath(), ccStdPluginInterface::m_app, PythonRuntimeSettings::pluginsPaths(), ccStdPluginInterface::setMainAppInterface(), Runtime::setMainAppInterfaceInstance(), and CVLog::Warning().
stop()
void PythonPlugin::stop () override virtual
Stops the plugin.
Should be reimplemented if necessary. Used to stop a plugin previously started (see ccPluginInterface::start).
Reimplemented from ccPluginInterface.
Definition at line 128 of file PythonPlugin.cpp.
References LoadSettings().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonPlugin.h
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonPlugin.cpp