ACloudViewer: flann::CountRadiusResultSet< DistanceType > Class Template Reference
flann::CountRadiusResultSet< DistanceType > Class Template Reference
#include <result_set.h>
Public Member Functions
CountRadiusResultSet (DistanceType radius_)
~CountRadiusResultSet ()
void clear ()
size_t size () const
bool full () const
void addPoint (DistanceType dist, size_t index)
DistanceType worstDist () const
Public Member Functions inherited from flann::ResultSet< DistanceType >
virtual ~ResultSet ()
Detailed Description
template<typename DistanceType>
class flann::CountRadiusResultSet< DistanceType >
This is a result set that only counts the neighbors within a radius.
Definition at line 652 of file result_set.h.
Constructor & Destructor Documentation
CountRadiusResultSet()
template<typename DistanceType > flann::CountRadiusResultSet< DistanceType >::CountRadiusResultSet (DistanceType radius_) inline
Definition at line 658 of file result_set.h.
References flann::CountRadiusResultSet< DistanceType >::clear().
~CountRadiusResultSet()
template<typename DistanceType > flann::CountRadiusResultSet< DistanceType >::~CountRadiusResultSet () inline
Definition at line 664 of file result_set.h.
Member Function Documentation
addPoint()
template<typename DistanceType > void flann::CountRadiusResultSet< DistanceType >::addPoint (DistanceType dist, size_t index) inline virtual
Implements flann::ResultSet< DistanceType >.
Definition at line 683 of file result_set.h.
References count, and dist().
clear()
template<typename DistanceType > void flann::CountRadiusResultSet< DistanceType >::clear () inline
Definition at line 668 of file result_set.h.
References count.
Referenced by flann::CountRadiusResultSet< DistanceType >::CountRadiusResultSet(), and flann::NNIndex< Distance >::radiusSearch().
full()
template<typename DistanceType > bool flann::CountRadiusResultSet< DistanceType >::full () const inline virtual
Implements flann::ResultSet< DistanceType >.
Definition at line 678 of file result_set.h.
size()
template<typename DistanceType > size_t flann::CountRadiusResultSet< DistanceType >::size () const inline
Definition at line 673 of file result_set.h.
References count.
Referenced by flann::NNIndex< Distance >::radiusSearch().
worstDist()
template<typename DistanceType > DistanceType flann::CountRadiusResultSet< DistanceType >::worstDist () const inline virtual
Implements flann::ResultSet< DistanceType >.
Definition at line 690 of file result_set.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/util/result_set.h