ACloudViewer: cloudViewer::ReconstructionWidget Class Reference
cloudViewer::ReconstructionWidget Class Reference
#include <ReconstructionWidget.h>
Public Member Functions
ReconstructionWidget (MainWindow *app)
void ImportReconstruction (const std::string &path)
void close ()
void release ()
void iniEnvironment ()
void showLog ()
void hideLog ()
QDockWidget * getLogWidget ()
std::vector< QMenu * > & getReconstructionMenus ()
std::vector< QToolBar * > & getReconstructionToolbars ()
QLabel * getTimerStatusBar ()
QLabel * getImageStatusBar ()
Detailed Description
Definition at line 45 of file ReconstructionWidget.h.
Constructor & Destructor Documentation
ReconstructionWidget()
cloudViewer::ReconstructionWidget::ReconstructionWidget (MainWindow * app) explicit
Definition at line 23 of file ReconstructionWidget.cpp.
References hideLog(), and iniEnvironment().
Member Function Documentation
close()
void cloudViewer::ReconstructionWidget::close ()
Definition at line 111 of file ReconstructionWidget.cpp.
References cloudViewer::ProjectWidget::IsValid().
Referenced by release().
getImageStatusBar()
QLabel* cloudViewer::ReconstructionWidget::getImageStatusBar () inline
Definition at line 67 of file ReconstructionWidget.h.
References cloudViewer::ModelViewerWidget::statusbar_status_label.
getLogWidget()
QDockWidget* cloudViewer::ReconstructionWidget::getLogWidget () inline
Definition at line 60 of file ReconstructionWidget.h.
getReconstructionMenus()
std::vector<QMenu*>& cloudViewer::ReconstructionWidget::getReconstructionMenus () inline
Definition at line 61 of file ReconstructionWidget.h.
getReconstructionToolbars()
std::vector<QToolBar*>& cloudViewer::ReconstructionWidget::getReconstructionToolbars () inline
Definition at line 62 of file ReconstructionWidget.h.
getTimerStatusBar()
QLabel* cloudViewer::ReconstructionWidget::getTimerStatusBar () inline
Definition at line 66 of file ReconstructionWidget.h.
hideLog()
void cloudViewer::ReconstructionWidget::hideLog ()
Definition at line 1309 of file ReconstructionWidget.cpp.
Referenced by ReconstructionWidget().
ImportReconstruction()
void cloudViewer::ReconstructionWidget::ImportReconstruction (const std::string & path)
Definition at line 104 of file ReconstructionWidget.cpp.
References cloudViewer::t::geometry::path, cloudViewer::ReconstructionManagerWidget::SelectReconstruction(), and cloudViewer::ReconstructionManagerWidget::Update().
iniEnvironment()
void cloudViewer::ReconstructionWidget::iniEnvironment ()
Definition at line 45 of file ReconstructionWidget.cpp.
References CVTools::FromQString(), cloudViewer::utility::filesystem::JoinPaths(), cloudViewer::ProjectWidget::SetDatabasePath(), and cloudViewer::ProjectWidget::SetImagePath().
Referenced by ReconstructionWidget().
release()
void cloudViewer::ReconstructionWidget::release ()
Definition at line 134 of file ReconstructionWidget.cpp.
References close(), and cloudViewer::ModelViewerWidget::Release().
showLog()
void cloudViewer::ReconstructionWidget::showLog ()
Definition at line 1302 of file ReconstructionWidget.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/reconstruction/ReconstructionWidget.h
/root/ACloudViewer/app/reconstruction/ReconstructionWidget.cpp