ACloudViewer: flann::IndexBase Class Reference
flann::IndexBase Class Reference abstract
#include <nn_index.h>
Public Member Functions
virtual ~IndexBase ()
virtual size_t veclen () const =0
virtual size_t size () const =0
virtual flann_algorithm_t getType () const =0
virtual int usedMemory () const =0
virtual IndexParams getParameters () const =0
virtual void loadIndex (FILE *stream)=0
virtual void saveIndex (FILE *stream)=0
Detailed Description
Definition at line 49 of file nn_index.h.
Constructor & Destructor Documentation
~IndexBase()
virtual flann::IndexBase::~IndexBase () inline virtual
Definition at line 52 of file nn_index.h.
Member Function Documentation
getParameters()
virtual IndexParams flann::IndexBase::getParameters () const pure virtual
Implemented in flann::NNIndex< Distance >, and flann::AutotunedIndex< Distance >.
getType()
virtual flann_algorithm_t flann::IndexBase::getType () const pure virtual
Implemented in flann::LshIndex< Distance >, flann::LinearIndex< Distance >, flann::KMeansIndex< Distance >, flann::KDTreeSingleIndex< Distance >, flann::KDTreeIndex< Distance >, flann::KDTreeCuda3dIndex< Distance >, flann::HierarchicalClusteringIndex< Distance >, flann::CompositeIndex< Distance >, and flann::AutotunedIndex< Distance >.
Referenced by flann::Index< Distance >::getType(), and flann::NNIndex< Distance >::serialize().
loadIndex()
virtual void flann::IndexBase::loadIndex (FILE * stream) pure virtual
Implemented in flann::LshIndex< Distance >, flann::LinearIndex< Distance >, flann::KMeansIndex< Distance >, flann::KDTreeSingleIndex< Distance >, flann::KDTreeIndex< Distance >, flann::KDTreeCuda3dIndex< Distance >, flann::HierarchicalClusteringIndex< Distance >, flann::CompositeIndex< Distance >, and flann::AutotunedIndex< Distance >.
saveIndex()
virtual void flann::IndexBase::saveIndex (FILE * stream) pure virtual
Implemented in flann::LshIndex< Distance >, flann::LinearIndex< Distance >, flann::KMeansIndex< Distance >, flann::KDTreeSingleIndex< Distance >, flann::KDTreeIndex< Distance >, flann::KDTreeCuda3dIndex< Distance >, flann::HierarchicalClusteringIndex< Distance >, flann::CompositeIndex< Distance >, and flann::AutotunedIndex< Distance >.
Referenced by flann::Index< Distance >::save().
size()
virtual size_t flann::IndexBase::size () const pure virtual
Implemented in flann::NNIndex< Distance >, flann::CompositeIndex< Distance >, and flann::AutotunedIndex< Distance >.
usedMemory()
virtual int flann::IndexBase::usedMemory () const pure virtual
Implemented in flann::LshIndex< Distance >, flann::LinearIndex< Distance >, flann::KMeansIndex< Distance >, flann::KDTreeSingleIndex< Distance >, flann::KDTreeIndex< Distance >, flann::KDTreeCuda3dIndex< Distance >, flann::HierarchicalClusteringIndex< Distance >, flann::CompositeIndex< Distance >, and flann::AutotunedIndex< Distance >.
Referenced by flann::Index< Distance >::usedMemory().
veclen()
virtual size_t flann::IndexBase::veclen () const pure virtual
Implemented in flann::NNIndex< Distance >, flann::KDTreeCuda3dIndex< Distance >, flann::CompositeIndex< Distance >, and flann::AutotunedIndex< Distance >.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/algorithms/nn_index.h