ACloudViewer: ccClippingBoxRepeatDlg Class Reference
ccClippingBoxRepeatDlg Class Reference
Dialog for managing clipping box based repeated processes.
#include <ecvClippingBoxRepeatDlg.h>
Public Member Functions
ccClippingBoxRepeatDlg (bool singleContourMode=false, QWidget *parent=0)
Default constructor.
void setFlatDim (unsigned char dim)
Sets flat dimension (single contour mode only!)
void setRepeatDim (unsigned char dim)
Sets repeat dimension (multiple contour mode only!)
Protected Slots
void onDimChecked (bool)
void onDimXChecked (bool)
void onDimYChecked (bool)
void onDimZChecked (bool)
Detailed Description
Dialog for managing clipping box based repeated processes.
Definition at line 16 of file ecvClippingBoxRepeatDlg.h.
Constructor & Destructor Documentation
ccClippingBoxRepeatDlg()
ccClippingBoxRepeatDlg::ccClippingBoxRepeatDlg (bool singleContourMode = false, QWidget * parent = 0)
Default constructor.
Definition at line 16 of file ecvClippingBoxRepeatDlg.cpp.
References onDimChecked(), onDimXChecked(), onDimYChecked(), onDimZChecked(), and setFlatDim().
Member Function Documentation
onDimChecked
void ccClippingBoxRepeatDlg::onDimChecked (bool) protected slot
Definition at line 86 of file ecvClippingBoxRepeatDlg.cpp.
Referenced by ccClippingBoxRepeatDlg().
onDimXChecked
void ccClippingBoxRepeatDlg::onDimXChecked (bool state) protected slot
Definition at line 59 of file ecvClippingBoxRepeatDlg.cpp.
References setFlatDim().
Referenced by ccClippingBoxRepeatDlg().
onDimYChecked
void ccClippingBoxRepeatDlg::onDimYChecked (bool state) protected slot
Definition at line 63 of file ecvClippingBoxRepeatDlg.cpp.
References setFlatDim().
Referenced by ccClippingBoxRepeatDlg().
onDimZChecked
void ccClippingBoxRepeatDlg::onDimZChecked (bool state) protected slot
Definition at line 67 of file ecvClippingBoxRepeatDlg.cpp.
References setFlatDim().
Referenced by ccClippingBoxRepeatDlg().
setFlatDim()
void ccClippingBoxRepeatDlg::setFlatDim (unsigned char dim)
Sets flat dimension (single contour mode only!)
Definition at line 72 of file ecvClippingBoxRepeatDlg.cpp.
Referenced by ccClippingBoxRepeatDlg(), onDimXChecked(), onDimYChecked(), and onDimZChecked().
setRepeatDim()
void ccClippingBoxRepeatDlg::setRepeatDim (unsigned char dim)
Sets repeat dimension (multiple contour mode only!)
Definition at line 50 of file ecvClippingBoxRepeatDlg.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvClippingBoxRepeatDlg.h
/root/ACloudViewer/app/ecvClippingBoxRepeatDlg.cpp