ACloudViewer: PlyOrientedVertex< Real > Class Template Reference
PlyOrientedVertex< Real > Class Template Reference
#include <Ply.h>
Public Types
typedef PlyOrientedVertex Wrapper
Public Member Functions
PlyOrientedVertex (void)
PlyOrientedVertex (Point3D< Real > p, Point3D< Real > n)
PlyOrientedVertex operator+ (PlyOrientedVertex p) const
PlyOrientedVertex operator- (PlyOrientedVertex p) const
template<class _Real >
PlyOrientedVertex operator* (_Real s) const
template<class _Real >
PlyOrientedVertex operator/ (_Real s) const
PlyOrientedVertex & operator+= (PlyOrientedVertex p)
PlyOrientedVertex & operator-= (PlyOrientedVertex p)
template<class _Real >
PlyOrientedVertex & operator*= (_Real s)
template<class _Real >
PlyOrientedVertex & operator/= (_Real s)
Public Attributes
Point3D< Real > point
Point3D< Real > normal
Static Public Attributes
static const int ReadComponents =6
static const int WriteComponents =6
static PlyProperty ReadProperties []
static PlyProperty WriteProperties []
Detailed Description
template<class Real>
class PlyOrientedVertex< Real >
Definition at line 328 of file Ply.h.
Member Typedef Documentation
Wrapper
template<class Real > typedef PlyOrientedVertex PlyOrientedVertex< Real >::Wrapper
Definition at line 331 of file Ply.h.
Constructor & Destructor Documentation
PlyOrientedVertex() [1/2]
template<class Real > PlyOrientedVertex< Real >::PlyOrientedVertex (void) inline
Definition at line 340 of file Ply.h.
Referenced by PlyOrientedVertex< Real >::operator*(), PlyOrientedVertex< Real >::operator+(), PlyOrientedVertex< Real >::operator-(), and PlyOrientedVertex< Real >::operator/().
PlyOrientedVertex() [2/2]
template<class Real > PlyOrientedVertex< Real >::PlyOrientedVertex (Point3D< Real > p, Point3D< Real > n) inline
Definition at line 341 of file Ply.h.
Member Function Documentation
operator*()
template<class Real > template<class _Real > PlyOrientedVertex PlyOrientedVertex< Real >::operator* (_Real s) const inline
Definition at line 344 of file Ply.h.
References PlyOrientedVertex< Real >::normal, and PlyOrientedVertex< Real >::PlyOrientedVertex().
operator*=()
template<class Real > template<class _Real > PlyOrientedVertex& PlyOrientedVertex< Real >::operator*= (_Real s) inline
Definition at line 348 of file Ply.h.
References PlyOrientedVertex< Real >::normal.
operator+()
template<class Real > PlyOrientedVertex PlyOrientedVertex< Real >::operator+ (PlyOrientedVertex< Real > p) const inline
Definition at line 342 of file Ply.h.
References PlyOrientedVertex< Real >::normal, PlyOrientedVertex< Real >::PlyOrientedVertex(), and PlyOrientedVertex< Real >::point.
operator+=()
template<class Real > PlyOrientedVertex& PlyOrientedVertex< Real >::operator+= (PlyOrientedVertex< Real > p) inline
Definition at line 346 of file Ply.h.
References PlyOrientedVertex< Real >::normal, and PlyOrientedVertex< Real >::point.
operator-()
template<class Real > PlyOrientedVertex PlyOrientedVertex< Real >::operator- (PlyOrientedVertex< Real > p) const inline
Definition at line 343 of file Ply.h.
References PlyOrientedVertex< Real >::normal, PlyOrientedVertex< Real >::PlyOrientedVertex(), and PlyOrientedVertex< Real >::point.
operator-=()
template<class Real > PlyOrientedVertex& PlyOrientedVertex< Real >::operator-= (PlyOrientedVertex< Real > p) inline
Definition at line 347 of file Ply.h.
References PlyOrientedVertex< Real >::normal, and PlyOrientedVertex< Real >::point.
operator/()
template<class Real > template<class _Real > PlyOrientedVertex PlyOrientedVertex< Real >::operator/ (_Real s) const inline
Definition at line 345 of file Ply.h.
References PlyOrientedVertex< Real >::normal, and PlyOrientedVertex< Real >::PlyOrientedVertex().
operator/=()
template<class Real > template<class _Real > PlyOrientedVertex& PlyOrientedVertex< Real >::operator/= (_Real s) inline
Definition at line 349 of file Ply.h.
References PlyOrientedVertex< Real >::normal.
Member Data Documentation
normal
template<class Real > Point3D<Real> PlyOrientedVertex< Real >::normal
Definition at line 338 of file Ply.h.
Referenced by PlyOrientedVertex< Real >::operator*(), operator*(), PlyOrientedVertex< Real >::operator*=(), PlyOrientedVertex< Real >::operator+(), PlyOrientedVertex< Real >::operator+=(), PlyOrientedVertex< Real >::operator-(), PlyOrientedVertex< Real >::operator-=(), PlyOrientedVertex< Real >::operator/(), and PlyOrientedVertex< Real >::operator/=().
point
template<class Real > Point3D<Real> PlyOrientedVertex< Real >::point
Definition at line 338 of file Ply.h.
Referenced by operator*(), PlyOrientedVertex< Real >::operator+(), PlyOrientedVertex< Real >::operator+=(), PlyOrientedVertex< Real >::operator-(), and PlyOrientedVertex< Real >::operator-=().
ReadComponents
template<class Real > const int PlyOrientedVertex< Real >::ReadComponents =6 static
Definition at line 333 of file Ply.h.
ReadProperties
template<class Real > PlyProperty PlyOrientedVertex< Real >::ReadProperties static
Initial value:
=
{
    {  strdup ( "x"  ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyOrientedVertex ,  point.coords[0] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "y"  ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyOrientedVertex ,  point.coords[1] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "z"  ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyOrientedVertex ,  point.coords[2] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "nx" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyOrientedVertex , normal.coords[0] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "ny" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyOrientedVertex , normal.coords[1] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "nz" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyOrientedVertex , normal.coords[2] ) ) , 0 , 0 , 0 , 0 }
}
Definition at line 335 of file Ply.h.
WriteComponents
template<class Real > const int PlyOrientedVertex< Real >::WriteComponents =6 static
Definition at line 334 of file Ply.h.
WriteProperties
template<class Real > PlyProperty PlyOrientedVertex< Real >::WriteProperties static
Initial value:
=
{
    {  strdup ( "x"  ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyOrientedVertex ,  point.coords[0] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "y"  ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyOrientedVertex ,  point.coords[1] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "z"  ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyOrientedVertex ,  point.coords[2] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "nx" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyOrientedVertex , normal.coords[0] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "ny" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyOrientedVertex , normal.coords[1] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "nz" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyOrientedVertex , normal.coords[2] ) ) , 0 , 0 , 0 , 0 }
}
Definition at line 336 of file Ply.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/Ply.h