ACloudViewer: ccApplyTransformationDlg Class Reference
ccApplyTransformationDlg Class Reference
Dialog to input a 4x4 matrix.
#include <ecvApplyTransformationDlg.h>
Public Member Functions
ccApplyTransformationDlg (QWidget *parent=0)
Default constructor.
ccGLMatrixd getTransformation () const
Returns input matrix.
Protected Slots
void checkMatrixValidityAndAccept ()
Checks matrix validity and 'accept' dialog if ok.
void onMatrixTextChange ()
void onRotAngleValueChanged (double)
Updates dialog when a component of the rotation axis/angle form changes.
void onEulerValueChanged (double)
Updates dialog when a component of the euleur form changes.
void loadFromASCIIFile ()
Loads matrix from ASCII file.
void loadFromClipboard ()
Loads matrix from clipboard ("paste")
void initFromDipAndDipDir ()
Inits matrix from dip / dip direction values.
void buttonClicked (QAbstractButton *)
Signal called when a button is clicked.
Protected Member Functions
void updateAll (const ccGLMatrix &mat, bool textForm=true, bool axisAngleForm=true, bool eulerForm=true)
Updates all forms with a given matrix.
Detailed Description
Dialog to input a 4x4 matrix.
Definition at line 16 of file ecvApplyTransformationDlg.h.
Constructor & Destructor Documentation
ccApplyTransformationDlg()
ccApplyTransformationDlg::ccApplyTransformationDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 51 of file ecvApplyTransformationDlg.cpp.
References buttonClicked(), checkMatrixValidityAndAccept(), initFromDipAndDipDir(), loadFromASCIIFile(), loadFromClipboard(), onEulerValueChanged(), onMatrixTextChange(), onRotAngleValueChanged(), s_currentFormIndex, s_inverseMatrix, and s_lastMatrix().
Member Function Documentation
buttonClicked
void ccApplyTransformationDlg::buttonClicked (QAbstractButton * button) protected slot
Signal called when a button is clicked.
Definition at line 377 of file ecvApplyTransformationDlg.cpp.
References updateAll().
Referenced by ccApplyTransformationDlg().
checkMatrixValidityAndAccept
void ccApplyTransformationDlg::checkMatrixValidityAndAccept () protected slot
Checks matrix validity and 'accept' dialog if ok.
Definition at line 274 of file ecvApplyTransformationDlg.cpp.
References ccGLMatrixTpl< float >::FromString(), s_currentFormIndex, s_inverseMatrix, and s_lastMatrix().
Referenced by ccApplyTransformationDlg().
getTransformation()
ccGLMatrixd ccApplyTransformationDlg::getTransformation () const
Returns input matrix.
Definition at line 259 of file ecvApplyTransformationDlg.cpp.
References ccGLMatrixTpl< double >::FromString(), and ccGLMatrixTpl< T >::invert().
initFromDipAndDipDir
void ccApplyTransformationDlg::initFromDipAndDipDir () protected slot
Inits matrix from dip / dip direction values.
Definition at line 331 of file ecvApplyTransformationDlg.cpp.
References ccNormalVectors::ConvertDipAndDipDirToNormal(), ccGLMatrixTpl< float >::FromToRotation(), ccHObject::getBB_recursive(), cloudViewer::BoundingBoxTpl< T >::getCenter(), MainWindow::getSelectedEntities(), cloudViewer::BoundingBoxTpl< T >::isValid(), ccGLMatrixTpl< T >::setTranslation(), MainWindow::TheInstance(), and updateAll().
Referenced by ccApplyTransformationDlg().
loadFromASCIIFile
void ccApplyTransformationDlg::loadFromASCIIFile () protected slot
Loads matrix from ASCII file.
Definition at line 295 of file ecvApplyTransformationDlg.cpp.
References ecvPS::CurrentPath(), ecvFileUtils::defaultDocPath(), CVLog::Error(), ccGLMatrixTpl< T >::fromAsciiFile(), ecvPS::LoadFile(), and ccGLMatrixTpl< T >::toString().
Referenced by ccApplyTransformationDlg().
loadFromClipboard
void ccApplyTransformationDlg::loadFromClipboard () protected slot
Loads matrix from clipboard ("paste")
Definition at line 320 of file ecvApplyTransformationDlg.cpp.
References CVLog::Warning().
Referenced by ccApplyTransformationDlg().
onEulerValueChanged
void ccApplyTransformationDlg::onEulerValueChanged (double) protected slot
Updates dialog when a component of the euleur form changes.
Definition at line 170 of file ecvApplyTransformationDlg.cpp.
References cloudViewer::DegreesToRadians(), ccGLMatrixTpl< T >::initFromParameters(), updateAll(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccApplyTransformationDlg().
onMatrixTextChange
void ccApplyTransformationDlg::onMatrixTextChange () protected slot
Automatically removes anything between square brackets, and update the other forms
Definition at line 132 of file ecvApplyTransformationDlg.cpp.
References ccGLMatrixTpl< float >::FromString(), and updateAll().
Referenced by ccApplyTransformationDlg().
onRotAngleValueChanged
void ccApplyTransformationDlg::onRotAngleValueChanged (double) protected slot
Updates dialog when a component of the rotation axis/angle form changes.
Definition at line 151 of file ecvApplyTransformationDlg.cpp.
References cloudViewer::DegreesToRadians(), ccGLMatrixTpl< T >::initFromParameters(), updateAll(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccApplyTransformationDlg().
updateAll()
void ccApplyTransformationDlg::updateAll (const ccGLMatrix & mat, bool textForm = true, bool axisAngleForm = true, bool eulerForm = true) protected
Updates all forms with a given matrix.
Definition at line 190 of file ecvApplyTransformationDlg.cpp.
References cloudViewer::DegreesToRadians(), ccGLMatrixTpl< T >::getParameters(), ccGLMatrixTpl< T >::toString(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by buttonClicked(), initFromDipAndDipDir(), onEulerValueChanged(), onMatrixTextChange(), and onRotAngleValueChanged().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvApplyTransformationDlg.h
/root/ACloudViewer/app/ecvApplyTransformationDlg.cpp