ACloudViewer: cloudViewer::ProjectWidget Class Reference
cloudViewer::ProjectWidget Class Reference
#include <ProjectWidget.h>
Public Member Functions
ProjectWidget (QWidget *parent, OptionManager *options)
bool IsValid () const
void Reset ()
void persistSave (const std::string &project_path, const std::string &database_path, const std::string &image_path)
std::string GetDatabasePath () const
std::string GetImagePath () const
void SetDatabasePath (const std::string &path)
void SetImagePath (const std::string &path)
Detailed Description
Definition at line 20 of file ProjectWidget.h.
Constructor & Destructor Documentation
ProjectWidget()
cloudViewer::ProjectWidget::ProjectWidget (QWidget * parent, OptionManager * options)
Definition at line 20 of file ProjectWidget.cpp.
Member Function Documentation
GetDatabasePath()
std::string cloudViewer::ProjectWidget::GetDatabasePath () const
Definition at line 83 of file ProjectWidget.cpp.
Referenced by IsValid().
GetImagePath()
std::string cloudViewer::ProjectWidget::GetImagePath () const
Definition at line 87 of file ProjectWidget.cpp.
Referenced by IsValid().
IsValid()
bool cloudViewer::ProjectWidget::IsValid () const
Definition at line 62 of file ProjectWidget.cpp.
References GetDatabasePath(), and GetImagePath().
Referenced by cloudViewer::ReconstructionWidget::close().
persistSave()
void cloudViewer::ProjectWidget::persistSave (const std::string & project_path, const std::string & database_path, const std::string & image_path)
Definition at line 72 of file ProjectWidget.cpp.
References CVTools::ToQString().
Reset()
void cloudViewer::ProjectWidget::Reset ()
Definition at line 67 of file ProjectWidget.cpp.
SetDatabasePath()
void cloudViewer::ProjectWidget::SetDatabasePath (const std::string & path)
Definition at line 91 of file ProjectWidget.cpp.
References cloudViewer::t::geometry::path.
Referenced by cloudViewer::ReconstructionWidget::iniEnvironment().
SetImagePath()
void cloudViewer::ProjectWidget::SetImagePath (const std::string & path)
Definition at line 95 of file ProjectWidget.cpp.
References cloudViewer::t::geometry::path.
Referenced by cloudViewer::ReconstructionWidget::iniEnvironment().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/reconstruction/ProjectWidget.h
/root/ACloudViewer/app/reconstruction/ProjectWidget.cpp