ACloudViewer: ccSerializationHelper Class Reference
ccSerializationHelper Class Reference
Serialization helpers.
#include <ecvSerializableObject.h>
Static Public Member Functions
static short GenericArrayToFileMinVersion ()
Returns the minimum file version to save/load a 'generic array'.
static void CoordsFromDataStream (QDataStream &stream, int flags, PointCoordinateType *out, unsigned count=1)
static void ScalarsFromDataStream (QDataStream &stream, int flags, ScalarType *out, unsigned count=1)
template<class Type , int N, class ComponentType >
static bool GenericArrayToFile (const std::vector< Type > &data, QFile &out)
Helper: saves a vector to file.
template<class Type , int N, class ComponentType >
static bool GenericArrayFromFile (std::vector< Type > &data, QFile &in, short dataVersion, const QString &verboseDescription)
Helper: loads a vector structure from file.
template<class Type , int N, class ComponentType , class FileComponentType >
static bool GenericArrayFromTypedFile (std::vector< Type > &data, QFile &in, short dataVersion, const QString &verboseDescription, FileComponentType *_autoOffset=nullptr)
Static Protected Member Functions
static bool ReadArrayHeader (QFile &in, short dataVersion, ::uint8_t &componentCount, ::uint32_t &elementCount)
Detailed Description
Serialization helpers.
Definition at line 120 of file ecvSerializableObject.h.
Member Function Documentation
CoordsFromDataStream()
static void ccSerializationHelper::CoordsFromDataStream (QDataStream & stream, int flags, PointCoordinateType * out, unsigned count = 1) inline static
Reads one or several 'PointCoordinateType' values from a QDataStream either in float or double format depending on the 'flag' value
Definition at line 127 of file ecvSerializableObject.h.
Referenced by define_ccSerializationHelper().
GenericArrayFromFile()
template<class Type , int N, class ComponentType > static bool ccSerializationHelper::GenericArrayFromFile (std::vector< Type > & data, QFile & in, short dataVersion, const QString & verboseDescription) inline static
Helper: loads a vector structure from file.
Parameters
data vector to load
in input file (must be already opened)
dataVersion version current data version
Returns
success
Definition at line 219 of file ecvSerializableObject.h.
GenericArrayFromTypedFile()
template<class Type , int N, class ComponentType , class FileComponentType > static bool ccSerializationHelper::GenericArrayFromTypedFile (std::vector< Type > & data, QFile & in, short dataVersion, const QString & verboseDescription, FileComponentType * _autoOffset = nullptr) inline static
Helper: loads a vector structure from a file stored with a different type
Parameters
data vector to load
in input file (must be already opened)
dataVersion version current data version
Returns
success
Definition at line 278 of file ecvSerializableObject.h.
GenericArrayToFile()
template<class Type , int N, class ComponentType > static bool ccSerializationHelper::GenericArrayToFile (const std::vector< Type > & data, QFile & out) inline static
Helper: saves a vector to file.
Parameters
data vector to save (must be allocated)
out output file (must be already opened)
Returns
success
Definition at line 173 of file ecvSerializableObject.h.
GenericArrayToFileMinVersion()
static short ccSerializationHelper::GenericArrayToFileMinVersion () inline static
Returns the minimum file version to save/load a 'generic array'.
Definition at line 123 of file ecvSerializableObject.h.
Referenced by ccArray< Type, N, ComponentType >::minimumFileVersion_MeOnly().
ReadArrayHeader()
static bool ccSerializationHelper::ReadArrayHeader (QFile & in, short dataVersion, ::uint8_t & componentCount, ::uint32_t & elementCount) inline static protected
Definition at line 358 of file ecvSerializableObject.h.
ScalarsFromDataStream()
static void ccSerializationHelper::ScalarsFromDataStream (QDataStream & stream, int flags, ScalarType * out, unsigned count = 1) inline static
Reads one or several 'ScalarType' values from a QDataStream either in float or double format depending on the 'flag' value
Definition at line 148 of file ecvSerializableObject.h.
Referenced by define_ccSerializationHelper().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvSerializableObject.h