ACloudViewer: colmap::BundleAdjustmentConfig Class Reference
colmap::BundleAdjustmentConfig Class Reference
#include <bundle_adjustment.h>
Public Member Functions
BundleAdjustmentConfig ()
size_t NumImages () const
size_t NumPoints () const
size_t NumConstantCameras () const
size_t NumConstantPoses () const
size_t NumConstantTvecs () const
size_t NumVariablePoints () const
size_t NumConstantPoints () const
size_t NumResiduals (const Reconstruction &reconstruction) const
void AddImage (const image_t image_id)
bool HasImage (const image_t image_id) const
void RemoveImage (const image_t image_id)
void SetConstantCamera (const camera_t camera_id)
void SetVariableCamera (const camera_t camera_id)
bool IsConstantCamera (const camera_t camera_id) const
void SetConstantPose (const image_t image_id)
void SetVariablePose (const image_t image_id)
bool HasConstantPose (const image_t image_id) const
void SetConstantTvec (const image_t image_id, const std::vector< int > &idxs)
void RemoveConstantTvec (const image_t image_id)
bool HasConstantTvec (const image_t image_id) const
void AddVariablePoint (const point3D_t point3D_id)
void AddConstantPoint (const point3D_t point3D_id)
bool HasPoint (const point3D_t point3D_id) const
bool HasVariablePoint (const point3D_t point3D_id) const
bool HasConstantPoint (const point3D_t point3D_id) const
void RemoveVariablePoint (const point3D_t point3D_id)
void RemoveConstantPoint (const point3D_t point3D_id)
const std::unordered_set< image_t > & Images () const
const std::unordered_set< point3D_t > & VariablePoints () const
const std::unordered_set< point3D_t > & ConstantPoints () const
const std::vector< int > & ConstantTvec (const image_t image_id) const
Detailed Description
Definition at line 27 of file bundle_adjustment.h.
Constructor & Destructor Documentation
BundleAdjustmentConfig()
colmap::BundleAdjustmentConfig::BundleAdjustmentConfig ()
Definition at line 55 of file bundle_adjustment.cc.
Member Function Documentation
AddConstantPoint()
void colmap::BundleAdjustmentConfig::AddConstantPoint (const point3D_t point3D_id)
Definition at line 197 of file bundle_adjustment.cc.
References HasVariablePoint().
Referenced by BOOST_AUTO_TEST_CASE().
AddImage()
void colmap::BundleAdjustmentConfig::AddImage (const image_t image_id)
Definition at line 116 of file bundle_adjustment.cc.
Referenced by colmap::IncrementalMapper::AdjustGlobalBundle(), colmap::IncrementalMapper::AdjustLocalBundle(), BOOST_AUTO_TEST_CASE(), colmap::RunPointTriangulator(), and colmap::RunRigBundleAdjuster().
AddVariablePoint()
void colmap::BundleAdjustmentConfig::AddVariablePoint (const point3D_t point3D_id)
Definition at line 192 of file bundle_adjustment.cc.
References HasConstantPoint().
Referenced by colmap::IncrementalMapper::AdjustLocalBundle(), and BOOST_AUTO_TEST_CASE().
ConstantPoints()
const std::unordered_set< point3D_t > & colmap::BundleAdjustmentConfig::ConstantPoints () const
Definition at line 182 of file bundle_adjustment.cc.
Referenced by colmap::BundleAdjuster::ParameterizePoints().
ConstantTvec()
const std::vector< int > & colmap::BundleAdjustmentConfig::ConstantTvec (const image_t image_id) const
Definition at line 187 of file bundle_adjustment.cc.
HasConstantPoint()
bool colmap::BundleAdjustmentConfig::HasConstantPoint (const point3D_t point3D_id) const
Definition at line 212 of file bundle_adjustment.cc.
Referenced by AddVariablePoint(), and HasPoint().
HasConstantPose()
bool colmap::BundleAdjustmentConfig::HasConstantPose (const image_t image_id) const
Definition at line 150 of file bundle_adjustment.cc.
Referenced by SetConstantTvec().
HasConstantTvec()
bool colmap::BundleAdjustmentConfig::HasConstantTvec (const image_t image_id) const
Definition at line 169 of file bundle_adjustment.cc.
Referenced by SetConstantPose().
HasImage()
bool colmap::BundleAdjustmentConfig::HasImage (const image_t image_id) const
Definition at line 120 of file bundle_adjustment.cc.
Referenced by SetConstantPose(), and SetConstantTvec().
HasPoint()
bool colmap::BundleAdjustmentConfig::HasPoint (const point3D_t point3D_id) const
Definition at line 202 of file bundle_adjustment.cc.
References HasConstantPoint(), and HasVariablePoint().
HasVariablePoint()
bool colmap::BundleAdjustmentConfig::HasVariablePoint (const point3D_t point3D_id) const
Definition at line 206 of file bundle_adjustment.cc.
Referenced by AddConstantPoint(), and HasPoint().
Images()
const std::unordered_set< image_t > & colmap::BundleAdjustmentConfig::Images () const
Definition at line 173 of file bundle_adjustment.cc.
Referenced by colmap::IncrementalMapper::AdjustLocalBundle().
IsConstantCamera()
bool colmap::BundleAdjustmentConfig::IsConstantCamera (const camera_t camera_id) const
Definition at line 136 of file bundle_adjustment.cc.
Referenced by colmap::BundleAdjuster::ParameterizeCameras().
NumConstantCameras()
size_t colmap::BundleAdjustmentConfig::NumConstantCameras () const
Definition at line 63 of file bundle_adjustment.cc.
NumConstantPoints()
size_t colmap::BundleAdjustmentConfig::NumConstantPoints () const
Definition at line 79 of file bundle_adjustment.cc.
NumConstantPoses()
size_t colmap::BundleAdjustmentConfig::NumConstantPoses () const
Definition at line 67 of file bundle_adjustment.cc.
NumConstantTvecs()
size_t colmap::BundleAdjustmentConfig::NumConstantTvecs () const
Definition at line 71 of file bundle_adjustment.cc.
NumImages()
size_t colmap::BundleAdjustmentConfig::NumImages () const
Definition at line 57 of file bundle_adjustment.cc.
Referenced by colmap::BundleAdjustmentOptions::CreateSolverOptions().
NumPoints()
size_t colmap::BundleAdjustmentConfig::NumPoints () const
Definition at line 59 of file bundle_adjustment.cc.
NumResiduals()
size_t colmap::BundleAdjustmentConfig::NumResiduals (const Reconstruction & reconstruction) const
Definition at line 83 of file bundle_adjustment.cc.
References colmap::Reconstruction::Image(), colmap::Image::NumPoints3D(), and colmap::Reconstruction::Point3D().
Referenced by BOOST_AUTO_TEST_CASE().
NumVariablePoints()
size_t colmap::BundleAdjustmentConfig::NumVariablePoints () const
Definition at line 75 of file bundle_adjustment.cc.
RemoveConstantPoint()
void colmap::BundleAdjustmentConfig::RemoveConstantPoint (const point3D_t point3D_id)
Definition at line 222 of file bundle_adjustment.cc.
RemoveConstantTvec()
void colmap::BundleAdjustmentConfig::RemoveConstantTvec (const image_t image_id)
Definition at line 165 of file bundle_adjustment.cc.
RemoveImage()
void colmap::BundleAdjustmentConfig::RemoveImage (const image_t image_id)
Definition at line 124 of file bundle_adjustment.cc.
RemoveVariablePoint()
void colmap::BundleAdjustmentConfig::RemoveVariablePoint (const point3D_t point3D_id)
Definition at line 218 of file bundle_adjustment.cc.
SetConstantCamera()
void colmap::BundleAdjustmentConfig::SetConstantCamera (const camera_t camera_id)
Definition at line 128 of file bundle_adjustment.cc.
Referenced by colmap::IncrementalMapper::AdjustLocalBundle(), and BOOST_AUTO_TEST_CASE().
SetConstantPose()
void colmap::BundleAdjustmentConfig::SetConstantPose (const image_t image_id)
Definition at line 140 of file bundle_adjustment.cc.
References HasConstantTvec(), and HasImage().
Referenced by colmap::IncrementalMapper::AdjustGlobalBundle(), colmap::IncrementalMapper::AdjustLocalBundle(), and BOOST_AUTO_TEST_CASE().
SetConstantTvec()
void colmap::BundleAdjustmentConfig::SetConstantTvec (const image_t image_id, const std::vector< int > & idxs)
Definition at line 154 of file bundle_adjustment.cc.
References HasConstantPose(), HasImage(), and colmap::VectorContainsDuplicateValues().
Referenced by colmap::IncrementalMapper::AdjustGlobalBundle(), colmap::IncrementalMapper::AdjustLocalBundle(), and BOOST_AUTO_TEST_CASE().
SetVariableCamera()
void colmap::BundleAdjustmentConfig::SetVariableCamera (const camera_t camera_id)
Definition at line 132 of file bundle_adjustment.cc.
SetVariablePose()
void colmap::BundleAdjustmentConfig::SetVariablePose (const image_t image_id)
Definition at line 146 of file bundle_adjustment.cc.
VariablePoints()
const std::unordered_set< point3D_t > & colmap::BundleAdjustmentConfig::VariablePoints () const
Definition at line 177 of file bundle_adjustment.cc.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/optim/bundle_adjustment.h
/root/ACloudViewer/libs/Reconstruction/src/optim/bundle_adjustment.cc