ACloudViewer: VtkUtils::PointsToModelConverter Class Reference
VtkUtils::PointsToModelConverter Class Reference
#include <pointstomodelconverter.h>
Public Member Functions
PointsToModelConverter (const QList< Point3F > &points, TableModel *model)
void run ()
Public Member Functions inherited from VtkUtils::SignalledRunnable
SignalledRunnable ()
Additional Inherited Members
Signals inherited from VtkUtils::SignalledRunnable
void finished ()
Detailed Description
Definition at line 21 of file pointstomodelconverter.h.
Constructor & Destructor Documentation
PointsToModelConverter()
VtkUtils::PointsToModelConverter::PointsToModelConverter (const QList< Point3F > & points, TableModel * model)
Definition at line 16 of file pointstomodelconverter.cpp.
Member Function Documentation
run()
void VtkUtils::PointsToModelConverter::run ()
Definition at line 20 of file pointstomodelconverter.cpp.
References VtkUtils::SignalledRunnable::finished(), VtkUtils::TableModel::resize(), and VtkUtils::TableModel::setData().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/pointstomodelconverter.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/pointstomodelconverter.cpp