ACloudViewer: Allocator< T > Class Template Reference
Allocator< T > Class Template Reference
#include <Allocator.h>
Public Member Functions
Allocator (void)
~Allocator (void)
void reset (void)
AllocatorState getState (void) const
void rollBack (void)
void rollBack (const AllocatorState &state)
void set (int blockSize)
T * newElements (int elements=1)
Detailed Description
template<class T>
class Allocator< T >
This templated class assists in memory allocation and is well suited for instances when it is known that the sequence of memory allocations is performed in a stack-based manner, so that memory allocated last is released first. It also preallocates memory in chunks so that multiple requests for small chunks of memory do not require separate system calls to the memory manager. The allocator is templated off of the class of objects that we would like it to allocate, ensuring that appropriate constructors and destructors are called as necessary.
Definition at line 46 of file Allocator.h.
Constructor & Destructor Documentation
Allocator()
template<class T > Allocator< T >::Allocator (void) inline
Definition at line 52 of file Allocator.h.
~Allocator()
template<class T > Allocator< T >::~Allocator (void) inline
Definition at line 53 of file Allocator.h.
References Allocator< T >::reset().
Member Function Documentation
getState()
template<class T > AllocatorState Allocator< T >::getState (void) const inline
This method returns the memory state of the allocator.
Definition at line 64 of file Allocator.h.
References AllocatorState::index, and AllocatorState::remains.
newElements()
template<class T > T* Allocator< T >::newElements (int elements = 1) inline
This method returns a pointer to an array of elements objects. If there is left over pre-allocated memory, this method simply returns a pointer to the next free piece of memory, otherwise it pre-allocates more memory. Note that if the number of objects requested is larger than the value blockSize with which the allocator was initialized, the request for memory will fail.
Definition at line 142 of file Allocator.h.
References NULL.
reset()
template<class T > void Allocator< T >::reset (void) inline
This method is the allocators destructor. It frees up any of the memory that it has allocated.
Definition at line 57 of file Allocator.h.
Referenced by Allocator< T >::set(), and Allocator< T >::~Allocator().
rollBack() [1/2]
template<class T > void Allocator< T >::rollBack (const AllocatorState & state) inline
This method rolls back the allocator to the previous memory state and makes all of the memory previously allocated available for re-allocation. Note that it does it not call the constructor again, so after this method has been called, assumptions about the state of the values in memory are no longer valid.
Definition at line 97 of file Allocator.h.
References AllocatorState::index, and AllocatorState::remains.
rollBack() [2/2]
template<class T > void Allocator< T >::rollBack (void) inline
This method rolls back the allocator so that it makes all of the memory previously allocated available for re-allocation. Note that it does it not call the constructor again, so after this method has been called, assumptions about the state of the values in memory are no longer valid.
Definition at line 77 of file Allocator.h.
set()
template<class T > void Allocator< T >::set (int blockSize) inline
This method initiallizes the constructor and the blockSize variable specifies the the number of objects that should be pre-allocated at a time.
Definition at line 129 of file Allocator.h.
References Allocator< T >::reset().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/Allocator.h