ACloudViewer: qPCV Class Reference
qPCV Class Reference
#include <qPCV.h>
Public Member Functions
qPCV (QObject *parent=nullptr)
Default constructor.
virtual ~qPCV ()=default
virtual void onNewSelection (const ccHObject::Container &selectedEntities) override
virtual QList< QAction * > getActions () override
Get a list of actions for this plugin.
virtual void registerCommands (ccCommandLineInterface *cmd) override
Optional: registers commands (for the command line mode)
Public Member Functions inherited from ccStdPluginInterface
ccStdPluginInterface (const QString &resourcePath=QString())
Default constructor.
virtual ~ccStdPluginInterface () override=default
Destructor.
virtual CC_PLUGIN_TYPE getType () const override
Returns plugin type (standard or OpenGL filter)
virtual void setMainAppInterface (ecvMainAppInterface *app)
Sets application entry point.
virtual ecvMainAppInterface * getMainAppInterface ()
A callback pointer to the main app interface for use by plugins.
virtual void dispToConsole (QString message, ecvMainAppInterface::ConsoleMessageLevel level=ecvMainAppInterface::STD_CONSOLE_MESSAGE)
Shortcut to ecvMainAppInterface::dispToConsole.
Public Member Functions inherited from ccDefaultPluginInterface
virtual ~ccDefaultPluginInterface ()
virtual bool isCore () const override
Is this plugin a core plugin?
virtual QString getName () const override
Returns (short) name (for menu entry, etc.)
virtual QString getDescription () const override
Returns long name/description (for tooltip, etc.)
virtual QIcon getIcon () const override
Returns icon.
virtual ReferenceList getReferences () const override
virtual ContactList getAuthors () const override
virtual ContactList getMaintainers () const override
Public Member Functions inherited from ccPluginInterface
virtual ~ccPluginInterface ()=default
Virtual destructor.
virtual bool start ()
Starts the plugin.
virtual void stop ()
Stops the plugin.
virtual ccExternalFactory * getCustomObjectsFactory () const
Returns the plugin's custom object factory (if any)
Protected Slots
void doAction ()
Slot called when associated ation is triggered.
Protected Attributes
QAction * m_action
Associated action.
Protected Attributes inherited from ccStdPluginInterface
ecvMainAppInterface * m_app
Main application interface.
Additional Inherited Members
Public Types inherited from ccPluginInterface
typedef QList< Contact > ContactList
using ReferenceList = QList< Reference >
Protected Member Functions inherited from ccDefaultPluginInterface
ccDefaultPluginInterface (const QString &resourcePath=QString())
Detailed Description
Wrapper to the ShadeVis algorithm for computing Ambient Occlusion on meshes and point clouds "Visibility based methods and assessment for detail-recovery", M. Tarini, P. Cignoni, R. Scopigno Proc. of Visualization 2003, October 19-24, Seattle, USA. http://vcg.sourceforge.net/index.php/ShadeVis
Definition at line 20 of file qPCV.h.
Constructor & Destructor Documentation
qPCV()
qPCV::qPCV (QObject * parent = nullptr) explicit
Default constructor.
Definition at line 37 of file qPCV.cpp.
~qPCV()
virtual qPCV::~qPCV () virtual default
Member Function Documentation
doAction
void qPCV::doAction () protected slot
Slot called when associated ation is triggered.
Definition at line 69 of file qPCV.cpp.
References ccPointCloud::addScalarField(), CC_PCV_FIELD_LABEL_NAME, ccScalarField::computeMinAndMax(), count, ecvMainAppInterface::dbRootObject(), ccPointCloud::deleteScalarField(), ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, ccHObject::filterChildren(), PCV::GenerateRays(), ccGenericMesh::getAssociatedCloud(), ccColorScalesManager::GetDefaultScale(), ecvMainAppInterface::getMainWindow(), ccObject::getName(), ccHObject::getParent(), ccGenericPointCloud::getPointNormal(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), ecvMainAppInterface::getSelectedEntities(), ccColorScalesManager::GREY, ccDrawableObject::hasNormals(), ccObject::isA(), ccObject::isKindOf(), PCV::Launch(), ccStdPluginInterface::m_app, CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, ecvMainAppInterface::refreshSelected(), s_closedMeshCheckBoxState, s_firstLaunch, s_mode180CheckBoxState, s_raysSpinBoxValue, s_resSpinBoxValue, ccScalarField::setColorScale(), ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentScalarField(), ccDrawableObject::showSF(), cloudViewer::GenericCloud::size(), ccHObjectCaster::ToGenericMesh(), ccHObjectCaster::ToGenericPointCloud(), ccHObjectCaster::ToPointCloud(), ecvMainAppInterface::updateUI(), and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by getActions().
getActions()
QList< QAction * > qPCV::getActions () override virtual
Get a list of actions for this plugin.
Implements ccStdPluginInterface.
Definition at line 56 of file qPCV.cpp.
References doAction(), ccDefaultPluginInterface::getDescription(), ccDefaultPluginInterface::getIcon(), ccDefaultPluginInterface::getName(), and m_action.
onNewSelection()
void qPCV::onNewSelection (const ccHObject::Container & selectedEntities) override virtual
This method is called by the main application whenever the entity selection changes Does nothing by default. Should be re-implemented by the plugin if necessary.
Parameters
selectedEntities currently selected entities
Reimplemented from ccStdPluginInterface.
Definition at line 42 of file qPCV.cpp.
References m_action, CV_TYPES::MESH, and CV_TYPES::POINT_CLOUD.
registerCommands()
void qPCV::registerCommands (ccCommandLineInterface * cmd) override virtual
Optional: registers commands (for the command line mode)
Does nothing by default.
Warning
: don't use keywords that are already used by the main application or other plugins! (use a unique prefix for all commands if possible)
Reimplemented from ccPluginInterface.
Definition at line 291 of file qPCV.cpp.
References ccCommandLineInterface::registerCommand().
Member Data Documentation
m_action
QAction* qPCV::m_action protected
Associated action.
Definition at line 44 of file qPCV.h.
Referenced by getActions(), and onNewSelection().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCV/include/qPCV.h
/root/ACloudViewer/plugins/core/Standard/qPCV/src/qPCV.cpp