ACloudViewer: Cube Class Reference
Cube Class Reference
#include <MarchingCubes.h>
Static Public Member Functions
static int CornerIndex (int x, int y, int z)
static void FactorCornerIndex (int idx, int &x, int &y, int &z)
static int EdgeIndex (int orientation, int i, int j)
static void FactorEdgeIndex (int idx, int &orientation, int &i, int &j)
static int FaceIndex (int dir, int offSet)
static int FaceIndex (int x, int y, int z)
static void FactorFaceIndex (int idx, int &x, int &y, int &z)
static void FactorFaceIndex (int idx, int &dir, int &offSet)
static int AntipodalCornerIndex (int idx)
static int FaceReflectCornerIndex (int idx, int faceIndex)
static int FaceReflectEdgeIndex (int idx, int faceIndex)
static int FaceReflectFaceIndex (int idx, int faceIndex)
static int EdgeReflectCornerIndex (int idx, int edgeIndex)
static int EdgeReflectEdgeIndex (int edgeIndex)
static int FaceAdjacentToEdges (int eIndex1, int eIndex2)
static void FacesAdjacentToEdge (int eIndex, int &f1Index, int &f2Index)
static void EdgeCorners (int idx, int &c1, int &c2)
static void FaceCorners (int idx, int &c1, int &c2, int &c3, int &c4)
static bool IsEdgeCorner (int cIndex, int e)
static bool IsFaceCorner (int cIndex, int f)
Static Public Attributes
static const unsigned int CORNERS =8
static const unsigned int EDGES =12
static const unsigned int FACES =6
Detailed Description
Definition at line 52 of file MarchingCubes.h.
Member Function Documentation
AntipodalCornerIndex()
int Cube::AntipodalCornerIndex (int idx) static
Definition at line 237 of file MarchingCubes.cpp.
References CornerIndex(), and FactorCornerIndex().
CornerIndex()
int Cube::CornerIndex (int x, int y, int z) static
Definition at line 103 of file MarchingCubes.cpp.
Referenced by AntipodalCornerIndex(), EdgeCorners(), EdgeReflectCornerIndex(), FaceCorners(), FaceReflectCornerIndex(), MarchingCubes::GetFaceIndex(), and MarchingCubes::GetIndex().
EdgeCorners()
void Cube::EdgeCorners (int idx, int & c1, int & c2) static
Definition at line 194 of file MarchingCubes.cpp.
References CornerIndex(), and FactorEdgeIndex().
Referenced by MarchingCubes::HasEdgeRoots().
EdgeIndex()
int Cube::EdgeIndex (int orientation, int i, int j) static
Definition at line 105 of file MarchingCubes.cpp.
Referenced by EdgeReflectEdgeIndex(), and FaceReflectEdgeIndex().
EdgeReflectCornerIndex()
int Cube::EdgeReflectCornerIndex (int idx, int edgeIndex) static
Definition at line 281 of file MarchingCubes.cpp.
References CornerIndex(), FactorCornerIndex(), and FactorEdgeIndex().
EdgeReflectEdgeIndex()
int Cube::EdgeReflectEdgeIndex (int edgeIndex) static
Definition at line 294 of file MarchingCubes.cpp.
References EdgeIndex(), and FactorEdgeIndex().
FaceAdjacentToEdges()
int Cube::FaceAdjacentToEdges (int eIndex1, int eIndex2) static
Definition at line 161 of file MarchingCubes.cpp.
References FacesAdjacentToEdge().
FaceCorners()
void Cube::FaceCorners (int idx, int & c1, int & c2, int & c3, int & c4) static
Definition at line 213 of file MarchingCubes.cpp.
References CornerIndex().
FaceIndex() [1/2]
int Cube::FaceIndex (int dir, int offSet) static
Definition at line 122 of file MarchingCubes.cpp.
Referenced by FacesAdjacentToEdge().
FaceIndex() [2/2]
int Cube::FaceIndex (int x, int y, int z) static
Definition at line 112 of file MarchingCubes.cpp.
FaceReflectCornerIndex()
int Cube::FaceReflectCornerIndex (int idx, int faceIndex) static
Definition at line 269 of file MarchingCubes.cpp.
References CornerIndex(), and FactorCornerIndex().
FaceReflectEdgeIndex()
int Cube::FaceReflectEdgeIndex (int idx, int faceIndex) static
Definition at line 252 of file MarchingCubes.cpp.
References EdgeIndex(), and FactorEdgeIndex().
FaceReflectFaceIndex()
int Cube::FaceReflectFaceIndex (int idx, int faceIndex) static
Definition at line 243 of file MarchingCubes.cpp.
FacesAdjacentToEdge()
void Cube::FacesAdjacentToEdge (int eIndex, int & f1Index, int & f2Index) static
Definition at line 171 of file MarchingCubes.cpp.
References FaceIndex(), and FactorEdgeIndex().
Referenced by FaceAdjacentToEdges().
FactorCornerIndex()
void Cube::FactorCornerIndex (int idx, int & x, int & y, int & z) static
Definition at line 104 of file MarchingCubes.cpp.
Referenced by AntipodalCornerIndex(), EdgeReflectCornerIndex(), and FaceReflectCornerIndex().
FactorEdgeIndex()
void Cube::FactorEdgeIndex (int idx, int & orientation, int & i, int & j) static
Definition at line 106 of file MarchingCubes.cpp.
Referenced by EdgeCorners(), EdgeReflectCornerIndex(), EdgeReflectEdgeIndex(), FaceReflectEdgeIndex(), FacesAdjacentToEdge(), and IsEdgeCorner().
FactorFaceIndex() [1/2]
void Cube::FactorFaceIndex (int idx, int & dir, int & offSet) static
Definition at line 137 of file MarchingCubes.cpp.
FactorFaceIndex() [2/2]
void Cube::FactorFaceIndex (int idx, int & x, int & y, int & z) static
Definition at line 124 of file MarchingCubes.cpp.
Referenced by MarchingCubes::GetFaceIndex(), and IsFaceCorner().
IsEdgeCorner()
bool Cube::IsEdgeCorner (int cIndex, int e) static
Definition at line 142 of file MarchingCubes.cpp.
References FactorEdgeIndex().
IsFaceCorner()
bool Cube::IsFaceCorner (int cIndex, int f) static
Definition at line 154 of file MarchingCubes.cpp.
References FactorFaceIndex().
Member Data Documentation
CORNERS
const unsigned int Cube::CORNERS =8 static
Definition at line 54 of file MarchingCubes.h.
EDGES
const unsigned int Cube::EDGES =12 static
Definition at line 54 of file MarchingCubes.h.
FACES
const unsigned int Cube::FACES =6 static
Definition at line 54 of file MarchingCubes.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/MarchingCubes.h
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/MarchingCubes.cpp