ACloudViewer: ccTranslationManager Class Reference
ccTranslationManager Class Reference
#include <ecvTranslationManager.h>
Public Member Functions
~ccTranslationManager () override=default
void registerTranslatorFile (const QString &prefix, const QString &path)
void loadTranslations ()
void loadTranslation (QString language)
void populateMenu (QMenu *menu, const QString &pathToTranslationFiles)
Static Public Member Functions
static ccTranslationManager & get ()
Protected Member Functions
ccTranslationManager ()=default
Detailed Description
Definition at line 16 of file ecvTranslationManager.h.
Constructor & Destructor Documentation
~ccTranslationManager()
ccTranslationManager::~ccTranslationManager () override default
ccTranslationManager()
ccTranslationManager::ccTranslationManager () explicit protected default
References cloudViewer::t::geometry::path.
Member Function Documentation
get()
static ccTranslationManager& ccTranslationManager::get () static
Referenced by main(), and MainWindow::MainWindow().
loadTranslation()
void ccTranslationManager::loadTranslation (QString language)
Using the translation file prefixes that were registered, load the actual translation by the 2-letter ISO 639 language code in lowercase.
Referenced by main().
loadTranslations()
void ccTranslationManager::loadTranslations ()
Using the translation file prefixes that were registered, load the actual translations
populateMenu()
void ccTranslationManager::populateMenu (QMenu * menu, const QString & pathToTranslationFiles)
Populate the menu with a list of languages found using files in 'pathToTranslationFiles'
Referenced by MainWindow::MainWindow().
registerTranslatorFile()
void ccTranslationManager::registerTranslatorFile (const QString & prefix, const QString & path)
Register a file prefix for translation files. The files should be named <prefix>_<lang>.ts where <lang> is the 2-letter ISO 639 language code in lowercase. e.g. ACloudViewer_fr.ts
Parameters
prefix The prefix of the file to register
path The path to look for the files in
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CVAppCommon/include/ecvTranslationManager.h