ACloudViewer: cloudViewer::TwoViewGeometriesTab Class Reference
cloudViewer::TwoViewGeometriesTab Class Reference
#include <DatabaseManagementWidget.h>
Public Member Functions
TwoViewGeometriesTab (QWidget *parent, OptionManager *options, colmap::Database *database)
void Reload (const std::vector< colmap::Image > &images, const colmap::image_t image_id)
Public Member Functions inherited from cloudViewer::TwoViewInfoTab
TwoViewInfoTab ()
TwoViewInfoTab (QWidget *parent, OptionManager *options, colmap::Database *database)
void Clear ()
Additional Inherited Members
Protected Member Functions inherited from cloudViewer::TwoViewInfoTab
void InitializeTable (const QStringList &table_header)
void ShowMatches ()
void FillTable ()
Protected Attributes inherited from cloudViewer::TwoViewInfoTab
OptionManager * options_
colmap::Database * database_
const colmap::Image * image_
std::vector< std::pair< const colmap::Image *, colmap::FeatureMatches > > matches_
std::vector< int > configs_
std::vector< size_t > sorted_matches_idxs_
QTableWidget * table_widget_
QLabel * info_label_
FeatureImageViewerWidget * matches_viewer_widget_
Detailed Description
Definition at line 69 of file DatabaseManagementWidget.h.
Constructor & Destructor Documentation
TwoViewGeometriesTab()
cloudViewer::TwoViewGeometriesTab::TwoViewGeometriesTab (QWidget * parent, OptionManager * options, colmap::Database * database)
Definition at line 166 of file DatabaseManagementWidget.cpp.
References cloudViewer::TwoViewInfoTab::InitializeTable().
Member Function Documentation
Reload()
void cloudViewer::TwoViewGeometriesTab::Reload (const std::vector< colmap::Image > & images, const colmap::image_t image_id)
Definition at line 177 of file DatabaseManagementWidget.cpp.
References cloudViewer::TwoViewInfoTab::configs_, cloudViewer::TwoViewInfoTab::database_, cloudViewer::TwoViewInfoTab::FillTable(), image, cloudViewer::TwoViewInfoTab::image_, and cloudViewer::TwoViewInfoTab::matches_.
Referenced by cloudViewer::OverlappingImagesWidget::ShowMatches().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/reconstruction/DatabaseManagementWidget.h
/root/ACloudViewer/app/reconstruction/DatabaseManagementWidget.cpp