ACloudViewer: QCPBars Class Reference
QCPBars Class Reference
A plottable representing a bar chart in a plot.
#include <qcustomplot.h>
Public Types
enum WidthType {
wtAbsolute , wtAxisRectRatio , wtPlotCoords , wtAbsolute ,
wtAxisRectRatio , wtPlotCoords
}
enum WidthType {
wtAbsolute , wtAxisRectRatio , wtPlotCoords , wtAbsolute ,
wtAxisRectRatio , wtPlotCoords
}
Public Member Functions
QCPBars (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPBars ()
double width () const
WidthType widthType () const
QCPBarsGroup * barsGroup () const
double baseValue () const
double stackingGap () const
QCPBars * barBelow () const
QCPBars * barAbove () const
QSharedPointer< QCPBarsDataContainer > data () const
void setData (QSharedPointer< QCPBarsDataContainer > data)
void setData (const QVector< double > &keys, const QVector< double > &values, bool alreadySorted=false)
void setWidth (double width)
void setWidthType (WidthType widthType)
void setBarsGroup (QCPBarsGroup *barsGroup)
void setBaseValue (double baseValue)
void setStackingGap (double pixels)
void addData (const QVector< double > &keys, const QVector< double > &values, bool alreadySorted=false)
void addData (double key, double value)
void moveBelow (QCPBars *bars)
void moveAbove (QCPBars *bars)
virtual QCPDataSelection selectTestRect (const QRectF &rect, bool onlySelectable) const
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
virtual QCPRange getKeyRange (bool &foundRange, QCP::SignDomain inSignDomain=QCP::sdBoth) const
virtual QCPRange getValueRange (bool &foundRange, QCP::SignDomain inSignDomain=QCP::sdBoth, const QCPRange &inKeyRange=QCPRange()) const
virtual QPointF dataPixelPosition (int index) const
QCPBars (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPBars ()
double width () const
WidthType widthType () const
QCPBarsGroup * barsGroup () const
double baseValue () const
QCPBars * barBelow () const
QCPBars * barAbove () const
QCPBarDataMap * data () const
void setWidth (double width)
void setWidthType (WidthType widthType)
void setBarsGroup (QCPBarsGroup *barsGroup)
void setBaseValue (double baseValue)
void setData (QCPBarDataMap *data, bool copy=false)
void setData (const QVector< double > &key, const QVector< double > &value)
void moveBelow (QCPBars *bars)
void moveAbove (QCPBars *bars)
void addData (const QCPBarDataMap &dataMap)
void addData (const QCPBarData &data)
void addData (double key, double value)
void addData (const QVector< double > &keys, const QVector< double > &values)
void removeDataBefore (double key)
void removeDataAfter (double key)
void removeData (double fromKey, double toKey)
void removeData (double key)
virtual void clearData ()
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractPlottable1D< QCPBarsData >
QCPAbstractPlottable1D (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPAbstractPlottable1D ()
virtual int dataCount () const
virtual double dataMainKey (int index) const
virtual double dataSortKey (int index) const
virtual double dataMainValue (int index) const
virtual QCPRange dataValueRange (int index) const
virtual bool sortKeyIsMainKey () const
virtual int findBegin (double sortKey, bool expandedRange=true) const
virtual int findEnd (double sortKey, bool expandedRange=true) const
virtual QCPPlottableInterface1D * interface1D ()
Public Member Functions inherited from QCPAbstractPlottable
QCPAbstractPlottable (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPAbstractPlottable ()
QString name () const
bool antialiasedFill () const
bool antialiasedScatters () const
QPen pen () const
QBrush brush () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
QCP::SelectionType selectable () const
bool selected () const
QCPDataSelection selection () const
QCPSelectionDecorator * selectionDecorator () const
void setName (const QString &name)
void setAntialiasedFill (bool enabled)
void setAntialiasedScatters (bool enabled)
void setPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setKeyAxis (QCPAxis *axis)
void setValueAxis (QCPAxis *axis)
Q_SLOT void setSelectable (QCP::SelectionType selectable)
Q_SLOT void setSelection (QCPDataSelection selection)
void setSelectionDecorator (QCPSelectionDecorator *decorator)
void coordsToPixels (double key, double value, double &x, double &y) const
const QPointF coordsToPixels (double key, double value) const
void pixelsToCoords (double x, double y, double &key, double &value) const
void pixelsToCoords (const QPointF &pixelPos, double &key, double &value) const
void rescaleAxes (bool onlyEnlarge=false) const
void rescaleKeyAxis (bool onlyEnlarge=false) const
void rescaleValueAxis (bool onlyEnlarge=false, bool inKeyRange=false) const
bool addToLegend (QCPLegend *legend)
bool addToLegend ()
bool removeFromLegend (QCPLegend *legend) const
bool removeFromLegend () const
QCPAbstractPlottable (QCPAxis *keyAxis, QCPAxis *valueAxis)
QString name () const
bool antialiasedFill () const
bool antialiasedScatters () const
bool antialiasedErrorBars () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
bool selectable () const
bool selected () const
void setName (const QString &name)
void setAntialiasedFill (bool enabled)
void setAntialiasedScatters (bool enabled)
void setAntialiasedErrorBars (bool enabled)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setKeyAxis (QCPAxis *axis)
void setValueAxis (QCPAxis *axis)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual bool addToLegend ()
virtual bool removeFromLegend () const
void rescaleAxes (bool onlyEnlarge=false) const
void rescaleKeyAxis (bool onlyEnlarge=false) const
void rescaleValueAxis (bool onlyEnlarge=false) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
virtual ~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Public Member Functions inherited from QCPPlottableInterface1D
virtual ~QCPPlottableInterface1D ()
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const
void getVisibleDataBounds (QCPBarsDataContainer::const_iterator &begin, QCPBarsDataContainer::const_iterator &end) const
QRectF getBarRect (double key, double value) const
void getPixelWidth (double key, double &lower, double &upper) const
double getStackedBaseValue (double key, bool positive) const
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
void getVisibleDataBounds (QCPBarDataMap::const_iterator &lower, QCPBarDataMap::const_iterator &upperEnd) const
QPolygonF getBarPolygon (double key, double value) const
void getPixelWidth (double key, double &lower, double &upper) const
double getStackedBaseValue (double key, bool positive) const
Protected Member Functions inherited from QCPAbstractPlottable1D< QCPBarsData >
void getDataSegments (QList< QCPDataRange > &selectedSegments, QList< QCPDataRange > &unselectedSegments) const
void drawPolyline (QCPPainter *painter, const QVector< QPointF > &lineData) const
Protected Member Functions inherited from QCPAbstractPlottable
virtual QRect clipRect () const
virtual QCP::Interaction selectionCategory () const
void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void applyFillAntialiasingHint (QCPPainter *painter) const
void applyScattersAntialiasingHint (QCPPainter *painter) const
virtual QRect clipRect () const
virtual QCP::Interaction selectionCategory () const
void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void coordsToPixels (double key, double value, double &x, double &y) const
const QPointF coordsToPixels (double key, double value) const
void pixelsToCoords (double x, double y, double &key, double &value) const
void pixelsToCoords (const QPointF &pixelPos, double &key, double &value) const
QPen mainPen () const
QBrush mainBrush () const
void applyFillAntialiasingHint (QCPPainter *painter) const
void applyScattersAntialiasingHint (QCPPainter *painter) const
void applyErrorBarsAntialiasingHint (QCPPainter *painter) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual void mousePressEvent (QMouseEvent *event, const QVariant &details)
virtual void mouseMoveEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseReleaseEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseDoubleClickEvent (QMouseEvent *event, const QVariant &details)
virtual void wheelEvent (QWheelEvent *event)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Static Protected Member Functions
static void connectBars (QCPBars *lower, QCPBars *upper)
static void connectBars (QCPBars *lower, QCPBars *upper)
Protected Attributes
double mWidth
WidthType mWidthType
QCPBarsGroup * mBarsGroup
double mBaseValue
double mStackingGap
QPointer< QCPBars > mBarBelow
QPointer< QCPBars > mBarAbove
QCPBarDataMap * mData
Protected Attributes inherited from QCPAbstractPlottable1D< QCPBarsData >
QSharedPointer< QCPDataContainer< QCPBarsData > > mDataContainer
Protected Attributes inherited from QCPAbstractPlottable
QString mName
bool mAntialiasedFill
bool mAntialiasedScatters
QPen mPen
QBrush mBrush
QPointer< QCPAxis > mKeyAxis
QPointer< QCPAxis > mValueAxis
QCP::SelectionType mSelectable
QCPDataSelection mSelection
QCPSelectionDecorator * mSelectionDecorator
bool mAntialiasedErrorBars
QPen mSelectedPen
QBrush mSelectedBrush
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractPlottable
void selectionChanged (bool selected)
void selectionChanged (const QCPDataSelection &selection)
void selectableChanged (QCP::SelectionType selectable)
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
void layerChanged (QCPLayer *newLayer)
Protected Types inherited from QCPAbstractPlottable
enum SignDomain { sdNegative , sdBoth , sdPositive }
Detailed Description
A plottable representing a bar chart in a plot.
To plot data, assign it with the setData or addData functions.
Changing the appearance
The appearance of the bars is determined by the pen and the brush (setPen, setBrush). The width of the individual bars can be controlled with setWidthType and setWidth.
Bar charts are stackable. This means, two QCPBars plottables can be placed on top of each other (see QCPBars::moveAbove). So when two bars are at the same key position, they will appear stacked.
If you would like to group multiple QCPBars plottables together so they appear side by side as shown below, use QCPBarsGroup.
Usage
Like all data representing objects in QCustomPlot, the QCPBars is a plottable (QCPAbstractPlottable). So the plottable-interface of QCustomPlot applies (QCustomPlot::plottable, QCustomPlot::removePlottable, etc.)
Usually, you first create an instance:
which registers it with the QCustomPlot instance of the passed axes. Note that this QCustomPlot instance takes ownership of the plottable, so do not delete it manually but use QCustomPlot::removePlottable() instead. The newly created plottable can be modified, e.g.:
To plot data, assign it with the setData or addData functions.
Changing the appearance
The appearance of the bars is determined by the pen and the brush (setPen, setBrush). The width of the individual bars can be controlled with setWidthType and setWidth.
Bar charts are stackable. This means, two QCPBars plottables can be placed on top of each other (see QCPBars::moveAbove). So when two bars are at the same key position, they will appear stacked.
If you would like to group multiple QCPBars plottables together so they appear side by side as shown below, use QCPBarsGroup.
Usage
Like all data representing objects in QCustomPlot, the QCPBars is a plottable (QCPAbstractPlottable). So the plottable-interface of QCustomPlot applies (QCustomPlot::plottable, QCustomPlot::addPlottable, QCustomPlot::removePlottable, etc.)
Usually, you first create an instance:
add it to the customPlot with QCustomPlot::addPlottable:
and then modify the properties of the newly created plottable, e.g.:
Definition at line 6449 of file qcustomplot.h.
Member Enumeration Documentation
WidthType [1/2]
enum QCPBars::WidthType
Defines the ways the width of the bar can be specified. Thus it defines what the number passed to setWidth actually means.
See also
setWidthType, setWidth
Enumerator
wtAbsolute
Bar width is in absolute pixels.
wtAxisRectRatio
Bar width is given by a fraction of the axis rect size
wtPlotCoords
Bar width is in key coordinates and thus scales with the key axis range
wtAbsolute
Bar width is in absolute pixels.
wtAxisRectRatio
Bar width is given by a fraction of the axis rect size
wtPlotCoords
Bar width is in key coordinates and thus scales with the key axis range
Definition at line 6467 of file qcustomplot.h.
WidthType [2/2]
enum QCPBars::WidthType
Defines the ways the width of the bar can be specified. Thus it defines what the number passed to setWidth actually means.
See also
setWidthType, setWidth
Enumerator
wtAbsolute
Bar width is in absolute pixels.
wtAxisRectRatio
Bar width is given by a fraction of the axis rect size
wtPlotCoords
Bar width is in key coordinates and thus scales with the key axis range
wtAbsolute
Bar width is in absolute pixels.
wtAxisRectRatio
Bar width is given by a fraction of the axis rect size
wtPlotCoords
Bar width is in key coordinates and thus scales with the key axis range
Definition at line 3434 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPBars() [1/2]
QCPBars::QCPBars (QCPAxis * keyAxis, QCPAxis * valueAxis) explicit
Constructs a bar chart which uses keyAxis as its key axis ("x") and valueAxis as its value axis ("y"). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
The created QCPBars is automatically registered with the QCustomPlot instance inferred from keyAxis. This QCustomPlot instance takes ownership of the QCPBars, so do not delete it manually but use QCustomPlot::removePlottable() instead.
Constructs a bar chart which uses keyAxis as its key axis ("x") and valueAxis as its value axis ("y"). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
The constructed QCPBars can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the bar chart.
Definition at line 25137 of file qcustomplot.cpp.
References ecvColor::blue(), QCPAbstractPlottable::mBrush, QCPAbstractPlottable::mPen, QCPAbstractPlottable::mSelectionDecorator, and QCPSelectionDecorator::setBrush().
~QCPBars() [1/2]
QCPBars::~QCPBars () virtual
Definition at line 25152 of file qcustomplot.cpp.
References connectBars(), mBarAbove, mBarBelow, and setBarsGroup().
QCPBars() [2/2]
QCPBars::QCPBars (QCPAxis * keyAxis, QCPAxis * valueAxis) explicit
~QCPBars() [2/2]
virtual QCPBars::~QCPBars () virtual
Member Function Documentation
addData() [1/6]
void QCPBars::addData (const QCPBarData & data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data.
See also
removeData
Definition at line 19709 of file qcustomplot.cpp.
References data(), mData, and qtCompatMapInsertMulti().
addData() [2/6]
void QCPBars::addData (const QCPBarDataMap & dataMap)
Adds the provided data points in dataMap to the current data.
See also
removeData
Definition at line 19701 of file qcustomplot.cpp.
References mData, and qtCompatMapUnite().
addData() [3/6]
void QCPBars::addData (const QVector< double > & keys, const QVector< double > & values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as key and value tuples to the current data.
See also
removeData
Definition at line 19728 of file qcustomplot.cpp.
References QCPBarData::key, mData, qtCompatMapInsertMulti(), and QCPBarData::value.
addData() [4/6]
void QCPBars::addData (const QVector< double > & keys, const QVector< double > & values, bool alreadySorted = false)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Adds the provided points in keys and values to the current data. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
If you can guarantee that the passed data points are sorted by keys in ascending order, you can set alreadySorted to true, to improve performance by saving a sorting run.
Alternatively, you can also access and modify the data directly via the data method, which returns a pointer to the internal data container.
Definition at line 25268 of file qcustomplot.cpp.
References QCPAbstractPlottable1D< QCPBarsData >::mDataContainer.
Referenced by QCPColoredBars::setData(), and setData().
addData() [5/6]
void QCPBars::addData (double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data point as key and value to the current data.
Alternatively, you can also access and modify the data directly via the data method, which returns a pointer to the internal data container.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as key and value tuple to the current data
See also
removeData
Definition at line 25297 of file qcustomplot.cpp.
References QCPAbstractPlottable1D< QCPBarsData >::mDataContainer.
addData() [6/6]
void QCPBars::addData (double key, double value)
barAbove() [1/2]
QCPBars * QCPBars::barAbove () const inline
Returns the bars plottable that is directly above this bars plottable. If there is no such plottable, returns 0.
See also
barBelow, moveBelow, moveAbove
Definition at line 6488 of file qcustomplot.h.
References data().
barAbove() [2/2]
QCPBars* QCPBars::barAbove () const inline
Definition at line 3454 of file qcustomplot.h.
References data().
barBelow() [1/2]
QCPBars * QCPBars::barBelow () const inline
Returns the bars plottable that is directly below this bars plottable. If there is no such plottable, returns 0.
See also
barAbove, moveBelow, moveAbove
Definition at line 6487 of file qcustomplot.h.
References data().
Referenced by QCPBarsGroup::keyPixelOffset().
barBelow() [2/2]
QCPBars* QCPBars::barBelow () const inline
Definition at line 3453 of file qcustomplot.h.
References data().
barsGroup() [1/2]
QCPBarsGroup* QCPBars::barsGroup () const inline
Definition at line 6484 of file qcustomplot.h.
Referenced by setBarsGroup().
barsGroup() [2/2]
QCPBarsGroup* QCPBars::barsGroup () const inline
Definition at line 3451 of file qcustomplot.h.
baseValue() [1/2]
double QCPBars::baseValue () const inline
Definition at line 6485 of file qcustomplot.h.
Referenced by setBaseValue().
baseValue() [2/2]
double QCPBars::baseValue () const inline
Definition at line 3452 of file qcustomplot.h.
clearData()
void QCPBars::clearData () virtual
Removes all data points.
See also
removeData, removeDataAfter, removeDataBefore
Implements QCPAbstractPlottable.
Reimplemented in QCPColoredBars.
Definition at line 19788 of file qcustomplot.cpp.
References mData.
connectBars() [1/2]
void QCPBars::connectBars (QCPBars * lower, QCPBars * upper) static protected
Definition at line 25829 of file qcustomplot.cpp.
References mBarAbove, and mBarBelow.
Referenced by moveAbove(), moveBelow(), and ~QCPBars().
connectBars() [2/2]
static void QCPBars::connectBars (QCPBars * lower, QCPBars * upper) static protected
data() [1/2]
QSharedPointer< QCPBarsDataContainer > QCPBars::data () const inline
Returns a shared pointer to the internal data storage of type QCPBarsDataContainer. You may use it to directly manipulate the data, which may be more convenient and faster than using the regular setData or addData methods.
Definition at line 6489 of file qcustomplot.h.
Referenced by addData(), barAbove(), barBelow(), QCPColoredBars::clearData(), AnglesCustomPlot::dataContainer(), QCPBarsWithText::draw(), QCPColoredBars::setData(), and setData().
data() [2/2]
QCPBarDataMap* QCPBars::data () const inline
Definition at line 3455 of file qcustomplot.h.
dataPixelPosition()
QPointF QCPBars::dataPixelPosition (int index) const virtual
const = 0
Returns the pixel position on the widget surface at which the data point at the given index appears.
Usually this corresponds to the point of dataMainKey/ dataMainValue, in pixel coordinates. However, depending on the plottable, this might be a different apparent position than just a coord-to-pixel transform of those values. For example, QCPBars apparent data values can be shifted depending on their stacking, bar grouping or configured base value.
Reimplemented from QCPAbstractPlottable1D< QCPBarsData >.
Definition at line 25517 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getStackedBaseValue(), QCPAbstractPlottable::keyAxis(), QCPBarsGroup::keyPixelOffset(), mBarsGroup, QCPAbstractPlottable1D< QCPBarsData >::mDataContainer, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), size, and QCPAbstractPlottable::valueAxis().
draw() [1/2]
void QCPBars::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractPlottable.
Reimplemented in QCPBarsWithText, QCPColoredBars, and QCPBarsWithText.
Definition at line 25544 of file qcustomplot.cpp.
References QCPSelectionDecorator::applyBrush(), QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPSelectionDecorator::applyPen(), QCPSelectionDecorator::drawDecoration(), getBarRect(), QCPAbstractPlottable1D< QCPBarsData >::getDataSegments(), getVisibleDataBounds(), QCP::isInvalidData(), QCPAbstractPlottable::mBrush, QCPAbstractPlottable1D< QCPBarsData >::mDataContainer, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mPen, QCPAbstractPlottable::mSelectionDecorator, QCPAbstractPlottable::mValueAxis, QCPAbstractPlottable::name(), QCPAbstractPlottable::selection(), and QCPPainter::setPen().
Referenced by QCPBarsWithText::draw(), and QCPColoredBars::draw().
draw() [2/2]
virtual void QCPBars::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractPlottable.
Reimplemented in QCPBarsWithText, QCPColoredBars, and QCPBarsWithText.
drawLegendIcon() [1/2]
void QCPBars::drawLegendIcon (QCPPainter * painter, const QRectF & rect) const protected virtual
Implements QCPAbstractPlottable.
Definition at line 25594 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::mBrush, QCPAbstractPlottable::mPen, and QCPPainter::setPen().
drawLegendIcon() [2/2]
virtual void QCPBars::drawLegendIcon (QCPPainter * painter, const QRectF & rect) const protected virtual
Implements QCPAbstractPlottable.
getBarPolygon()
QPolygonF QCPBars::getBarPolygon (double key, double value) const protected
Definition at line 19953 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getPixelWidth(), getStackedBaseValue(), QCPAbstractPlottable::keyAxis(), QCPBarsGroup::keyPixelOffset(), mBarsGroup, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), result, and QCPAbstractPlottable::valueAxis().
Referenced by getVisibleDataBounds().
getBarRect()
QRectF QCPBars::getBarRect (double key, double value) const protected
Definition at line 25694 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getPixelWidth(), getStackedBaseValue(), QCPAbstractPlottable::keyAxis(), QCPBarsGroup::keyPixelOffset(), mBarBelow, mBarsGroup, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mPen, mStackingGap, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), QCPAxis::pixelOrientation(), and QCPAbstractPlottable::valueAxis().
Referenced by QCPColoredBars::draw(), draw(), getVisibleDataBounds(), selectTest(), and selectTestRect().
getKeyRange() [1/2]
QCPRange QCPBars::getKeyRange (bool & foundRange, QCP::SignDomain inSignDomain = QCP::sdBoth) const virtual
Returns the coordinate range that all data in this plottable span in the key axis dimension. For logarithmic plots, one can set inSignDomain to either QCP::sdNegative or QCP::sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to QCP::sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to QCP::sdBoth (default). foundRange is an output parameter that indicates whether a range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
Note that foundRange is not the same as QCPRange::validRange, since the range returned by this function may have size zero (e.g. when there is only one data point). In this case foundRange would return true, but the returned range is not a valid range in terms of QCPRange::validRange.
See also
rescaleAxes, getValueRange
Implements QCPAbstractPlottable.
Definition at line 25432 of file qcustomplot.cpp.
References getPixelWidth(), QCPBarsGroup::keyPixelOffset(), QCPRange::lower, mBarsGroup, QCPAbstractPlottable1D< QCPBarsData >::mDataContainer, QCPAbstractPlottable::mKeyAxis, and QCPRange::upper.
getKeyRange() [2/2]
QCPRange QCPBars::getKeyRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const protected virtual
Implements QCPAbstractPlottable.
Definition at line 20115 of file qcustomplot.cpp.
References getPixelWidth(), QCPBarsGroup::keyPixelOffset(), QCPRange::lower, mBarsGroup, mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
getPixelWidth() [1/2]
void QCPBars::getPixelWidth (double key, double & lower, double & upper) const protected
Definition at line 25739 of file qcustomplot.cpp.
References QCPAbstractPlottable::mKeyAxis, mWidth, mWidthType, wtAbsolute, wtAxisRectRatio, and wtPlotCoords.
Referenced by getBarPolygon(), getBarRect(), and getKeyRange().
getPixelWidth() [2/2]
void QCPBars::getPixelWidth (double key, double & lower, double & upper) const protected
getStackedBaseValue() [1/2]
double QCPBars::getStackedBaseValue (double key, bool positive) const protected
Definition at line 25789 of file qcustomplot.cpp.
References e, mBarBelow, and mBaseValue.
Referenced by dataPixelPosition(), getBarPolygon(), getBarRect(), and getValueRange().
getStackedBaseValue() [2/2]
double QCPBars::getStackedBaseValue (double key, bool positive) const protected
getValueRange() [1/2]
QCPRange QCPBars::getValueRange (bool & foundRange, QCP::SignDomain inSignDomain = QCP::sdBoth, const QCPRange & inKeyRange = QCPRange()) const virtual
Returns the coordinate range that the data points in the specified key range (inKeyRange) span in the value axis dimension. For logarithmic plots, one can set inSignDomain to either QCP::sdNegative or QCP::sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to QCP::sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to QCP::sdBoth (default). foundRange is an output parameter that indicates whether a range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
If inKeyRange has both lower and upper bound set to zero (is equal to QCPRange()), all data points are considered, without any restriction on the keys.
Note that foundRange is not the same as QCPRange::validRange, since the range returned by this function may have size zero (e.g. when there is only one data point). In this case foundRange would return true, but the returned range is not a valid range in terms of QCPRange::validRange.
See also
rescaleAxes, getKeyRange
Implements QCPAbstractPlottable.
Definition at line 25475 of file qcustomplot.cpp.
References getStackedBaseValue(), QCPRange::lower, mBaseValue, QCPAbstractPlottable1D< QCPBarsData >::mDataContainer, QCP::sdBoth, QCP::sdNegative, QCP::sdPositive, and QCPRange::upper.
getValueRange() [2/2]
QCPRange QCPBars::getValueRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const protected virtual
called by rescaleAxes functions to get the full data value bounds. For logarithmic plots, one can set inSignDomain to either sdNegative or sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to sdBoth (default). foundRange is an output parameter that indicates whether a range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
Note that foundRange is not the same as QCPRange::validRange, since the range returned by this function may have size zero, which wouldn't count as a valid range.
See also
rescaleAxes, getKeyRange
Implements QCPAbstractPlottable.
Definition at line 20161 of file qcustomplot.cpp.
References getStackedBaseValue(), QCPRange::lower, mBaseValue, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
getVisibleDataBounds() [1/2]
void QCPBars::getVisibleDataBounds (QCPBarDataMap::const_iterator & lower, QCPBarDataMap::const_iterator & upperEnd) const protected
Definition at line 19879 of file qcustomplot.cpp.
References getBarPolygon(), mData, and QCPAbstractPlottable::mKeyAxis.
getVisibleDataBounds() [2/2]
void QCPBars::getVisibleDataBounds (QCPBarsDataContainer::const_iterator & begin, QCPBarsDataContainer::const_iterator & end) const protected
Definition at line 25620 of file qcustomplot.cpp.
References getBarRect(), QCPAbstractPlottable1D< QCPBarsData >::mDataContainer, and QCPAbstractPlottable::mKeyAxis.
Referenced by draw(), selectTest(), and selectTestRect().
moveAbove() [1/2]
void QCPBars::moveAbove (QCPBars * bars)
Moves this bars plottable above bars. In other words, the bars of this plottable will appear above the bars of bars. The move target bars must use the same key and value axis as this plottable.
Inserting into and removing from existing bar stacking is handled gracefully. If bars already has a bars object above itself, this bars object is inserted between the two. If this bars object is already between two other bars, the two other bars will be stacked on top of each other after the operation.
To remove this bars plottable from any stacking, set bars to 0.
See also
moveBelow, barBelow, barAbove
Moves this bars plottable above bars. In other words, the bars of this plottable will appear above the bars of bars. The move target bars must use the same key and value axis as this plottable.
Inserting into and removing from existing bar stacking is handled gracefully. If bars already has a bars object below itself, this bars object is inserted between the two. If this bars object is already between two other bars, the two other bars will be stacked on top of each other after the operation.
To remove this bars plottable from any stacking, set bars to 0.
See also
moveBelow, barBelow, barAbove
Definition at line 25350 of file qcustomplot.cpp.
References connectBars(), QCPAbstractPlottable::keyAxis(), mBarAbove, mBarBelow, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, and QCPAbstractPlottable::valueAxis().
moveAbove() [2/2]
void QCPBars::moveAbove (QCPBars * bars)
moveBelow() [1/2]
void QCPBars::moveBelow (QCPBars * bars)
Moves this bars plottable below bars. In other words, the bars of this plottable will appear below the bars of bars. The move target bars must use the same key and value axis as this plottable.
Inserting into and removing from existing bar stacking is handled gracefully. If bars already has a bars object below itself, this bars object is inserted between the two. If this bars object is already between two other bars, the two other bars will be stacked on top of each other after the operation.
To remove this bars plottable from any stacking, set bars to 0.
See also
moveBelow, barAbove, barBelow
Definition at line 25316 of file qcustomplot.cpp.
References connectBars(), QCPAbstractPlottable::keyAxis(), mBarAbove, mBarBelow, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, and QCPAbstractPlottable::valueAxis().
moveBelow() [2/2]
void QCPBars::moveBelow (QCPBars * bars)
removeData() [1/2]
void QCPBars::removeData (double fromKey, double toKey)
Removes all data points with key between fromKey and toKey. if fromKey is greater or equal to toKey, the function does nothing. To remove a single data point with known key, use removeData(double key).
See also
addData, clearData
Definition at line 19766 of file qcustomplot.cpp.
References mData.
removeData() [2/2]
void QCPBars::removeData (double key)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at key. If the position is not known with absolute precision, consider using removeData(double fromKey, double toKey) with a small fuzziness interval around the suspected position, depeding on the precision with which the key is known.
See also
addData, clearData
Definition at line 19782 of file qcustomplot.cpp.
References mData.
removeDataAfter()
void QCPBars::removeDataAfter (double key)
Removes all data points with key greater than key.
See also
addData, clearData
Definition at line 19753 of file qcustomplot.cpp.
References mData.
removeDataBefore()
void QCPBars::removeDataBefore (double key)
Removes all data points with key smaller than key.
See also
addData, clearData
Definition at line 19744 of file qcustomplot.cpp.
References mData.
selectTest() [1/2]
double QCPBars::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
Implements a selectTest specific to this plottable's point geometry.
If details is not 0, it will be set to a QCPDataSelection, describing the closest data point to pos.
\seebaseclassmethod QCPAbstractPlottable::selectTest
Implements QCPAbstractPlottable.
Definition at line 25403 of file qcustomplot.cpp.
References getBarRect(), getVisibleDataBounds(), QCPAbstractPlottable1D< QCPBarsData >::mDataContainer, QCPAbstractPlottable::mKeyAxis, QCPLayerable::mParentPlot, QCPAbstractPlottable::mSelectable, QCPAbstractPlottable::mValueAxis, QCustomPlot::selectionTolerance(), and QCP::stNone.
selectTest() [2/2]
virtual double QCPBars::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
selectTestRect()
QCPDataSelection QCPBars::selectTestRect (const QRectF & rect, bool onlySelectable) const virtual
Returns a data selection containing all the data points of this plottable which are contained (or hit by) rect. This is used mainly in the selection rect interaction for data selection (data selectionmechanism").
If onlySelectable is true, an empty QCPDataSelection is returned if this plottable is not selectable (i.e. if QCPAbstractPlottable::setSelectable is QCP::stNone).
Note
rect must be a normalized rect (positive or zero width and height). This is especially important when using the rect of QCPSelectionRect::accepted, which is not necessarily normalized. Use QRect::normalized() when passing a rect which might not be normalized.
Reimplemented from QCPAbstractPlottable1D< QCPBarsData >.
Definition at line 25372 of file qcustomplot.cpp.
References getBarRect(), getVisibleDataBounds(), QCPAbstractPlottable1D< QCPBarsData >::mDataContainer, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mSelectable, QCPAbstractPlottable::mValueAxis, result, and QCP::stNone.
setBarsGroup() [1/2]
void QCPBars::setBarsGroup (QCPBarsGroup * barsGroup)
Sets to which QCPBarsGroup this QCPBars instance belongs to. Alternatively, you can also use QCPBarsGroup::append.
To remove this QCPBars from any group, set barsGroup to 0.
Definition at line 25226 of file qcustomplot.cpp.
References barsGroup(), mBarsGroup, QCPBarsGroup::registerBars(), and QCPBarsGroup::unregisterBars().
Referenced by ~QCPBars().
setBarsGroup() [2/2]
void QCPBars::setBarsGroup (QCPBarsGroup * barsGroup)
setBaseValue() [1/2]
void QCPBars::setBaseValue (double baseValue)
Sets the base value of this bars plottable.
The base value defines where on the value coordinate the bars start. How far the bars extend from the base value is given by their individual value data. For example, if the base value is set to 1, a bar with data value 2 will have its lowest point at value coordinate 1 and highest point at 3.
For stacked bars, only the base value of the bottom-most QCPBars has meaning.
The default base value is 0.
Definition at line 25246 of file qcustomplot.cpp.
References baseValue(), and mBaseValue.
setBaseValue() [2/2]
void QCPBars::setBaseValue (double baseValue)
setData() [1/4]
void QCPBars::setData (const QVector< double > & key, const QVector< double > & value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in key and value tuples. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 19616 of file qcustomplot.cpp.
References QCPBarData::key, mData, qtCompatMapInsertMulti(), and QCPBarData::value.
setData() [2/4]
void QCPBars::setData (const QVector< double > & keys, const QVector< double > & values, bool alreadySorted = false)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in keys and values. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
If you can guarantee that the passed data points are sorted by keys in ascending order, you can set alreadySorted to true, to improve performance by saving a sorting run.
See also
addData
Definition at line 25192 of file qcustomplot.cpp.
References addData(), and QCPAbstractPlottable1D< QCPBarsData >::mDataContainer.
setData() [3/4]
void QCPBars::setData (QCPBarDataMap * data, bool copy = false)
Replaces the current data with the provided data.
If copy is set to true, data points in data will only be copied. if false, the plottable takes ownership of the passed data and replaces the internal data pointer with it. This is significantly faster than copying for large datasets.
Definition at line 19594 of file qcustomplot.cpp.
References copy, data(), and mData.
setData() [4/4]
void QCPBars::setData (QSharedPointer< QCPBarsDataContainer > data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data container with the provided data container.
Since a QSharedPointer is used, multiple QCPBars may share the same data container safely. Modifying the data in the container will then affect all bars that share the container. Sharing can be achieved by simply exchanging the data containers wrapped in shared pointers:
If you do not wish to share containers, but create a copy from an existing container, rather use the QCPDataContainer<DataType>::set method on the bar's data container directly:
See also
addData
Definition at line 25176 of file qcustomplot.cpp.
References data(), and QCPAbstractPlottable1D< QCPBarsData >::mDataContainer.
Referenced by AnglesCustomPlot::createQCPBars(), ccHistogramWindow::refresh(), ccWaveWidget::refresh(), and QCPColoredBars::setData().
setStackingGap()
void QCPBars::setStackingGap (double pixels)
If this bars plottable is stacked on top of another bars plottable (moveAbove), this method allows specifying a distance in pixels, by which the drawn bar rectangles will be separated by the bars below it.
Definition at line 25253 of file qcustomplot.cpp.
References mStackingGap.
setWidth() [1/2]
void QCPBars::setWidth (double width)
Sets the width of the bars.
How the number passed as width is interpreted (e.g. screen pixels, plot coordinates,...), depends on the currently set width type, see setWidthType and WidthType.
Definition at line 25206 of file qcustomplot.cpp.
References mWidth, and width().
Referenced by AnglesCustomPlot::createQCPBars(), ccHistogramWindow::refresh(), and ccWaveWidget::refresh().
setWidth() [2/2]
void QCPBars::setWidth (double width)
setWidthType() [1/2]
void QCPBars::setWidthType (QCPBars::WidthType widthType)
Sets how the width of the bars is defined. See the documentation of WidthType for an explanation of the possible values for widthType.
The default value is wtPlotCoords.
See also
setWidth
Definition at line 25216 of file qcustomplot.cpp.
References mWidthType, and widthType().
setWidthType() [2/2]
void QCPBars::setWidthType (WidthType widthType)
stackingGap()
double QCPBars::stackingGap () const inline
Definition at line 6486 of file qcustomplot.h.
width() [1/2]
double QCPBars::width () const inline
Definition at line 6482 of file qcustomplot.h.
Referenced by setWidth().
width() [2/2]
double QCPBars::width () const inline
Definition at line 3449 of file qcustomplot.h.
widthType() [1/2]
WidthType QCPBars::widthType () const inline
Definition at line 6483 of file qcustomplot.h.
Referenced by setWidthType().
widthType() [2/2]
WidthType QCPBars::widthType () const inline
Definition at line 3450 of file qcustomplot.h.
Member Data Documentation
mBarAbove
QPointer< QCPBars > QCPBars::mBarAbove protected
Definition at line 6532 of file qcustomplot.h.
Referenced by connectBars(), moveAbove(), moveBelow(), and ~QCPBars().
mBarBelow
QPointer< QCPBars > QCPBars::mBarBelow protected
Definition at line 6532 of file qcustomplot.h.
Referenced by connectBars(), getBarRect(), getStackedBaseValue(), moveAbove(), moveBelow(), and ~QCPBars().
mBarsGroup
QCPBarsGroup * QCPBars::mBarsGroup protected
Definition at line 6529 of file qcustomplot.h.
Referenced by dataPixelPosition(), getBarPolygon(), getBarRect(), getKeyRange(), and setBarsGroup().
mBaseValue
double QCPBars::mBaseValue protected
Definition at line 6530 of file qcustomplot.h.
Referenced by getStackedBaseValue(), getValueRange(), and setBaseValue().
mData
QCPBarDataMap* QCPBars::mData protected
Definition at line 3485 of file qcustomplot.h.
Referenced by addData(), clearData(), getKeyRange(), getValueRange(), getVisibleDataBounds(), removeData(), removeDataAfter(), removeDataBefore(), and setData().
mStackingGap
double QCPBars::mStackingGap protected
Definition at line 6531 of file qcustomplot.h.
Referenced by getBarRect(), and setStackingGap().
mWidth
double QCPBars::mWidth protected
Definition at line 6527 of file qcustomplot.h.
Referenced by QCPColoredBars::draw(), getPixelWidth(), and setWidth().
mWidthType
WidthType QCPBars::mWidthType protected
Definition at line 6528 of file qcustomplot.h.
Referenced by getPixelWidth(), and setWidthType().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp