ACloudViewer: ccPickOneElementDlg Class Reference
ccPickOneElementDlg Class Reference
Minimal dialog to pick one element in a list (combox box)
#include <ecvPickOneElementDlg.h>
Public Member Functions
ccPickOneElementDlg (const QString &label, const QString &windowTitle=QString(), QWidget *parent=nullptr)
Default constructor.
~ccPickOneElementDlg () override
Destructor.
void addElement (const QString &elementName)
Add an element to the combo box.
void setDefaultIndex (int index)
Sets the combo box default index.
int getSelectedIndex ()
Returns the combo box current index (after completion)
Protected Attributes
Ui_PickOneElementDialog * m_ui
Associated UI.
Detailed Description
Minimal dialog to pick one element in a list (combox box)
Definition at line 18 of file ecvPickOneElementDlg.h.
Constructor & Destructor Documentation
ccPickOneElementDlg()
ccPickOneElementDlg::ccPickOneElementDlg (const QString & label, const QString & windowTitle = QString(), QWidget * parent = nullptr)
Default constructor.
~ccPickOneElementDlg()
ccPickOneElementDlg::~ccPickOneElementDlg () override
Destructor.
Member Function Documentation
addElement()
void ccPickOneElementDlg::addElement (const QString & elementName)
Add an element to the combo box.
Referenced by ccEntityAction::computeStatParams(), ccEntityAction::enhanceRGBWithIntensities(), and ccEntityAction::statisticalTest().
getSelectedIndex()
int ccPickOneElementDlg::getSelectedIndex ()
Returns the combo box current index (after completion)
Referenced by ccEntityAction::computeStatParams(), ccEntityAction::enhanceRGBWithIntensities(), and ccEntityAction::statisticalTest().
setDefaultIndex()
void ccPickOneElementDlg::setDefaultIndex (int index)
Sets the combo box default index.
Referenced by ccEntityAction::computeStatParams(), ccEntityAction::enhanceRGBWithIntensities(), and ccEntityAction::statisticalTest().
Member Data Documentation
m_ui
Ui_PickOneElementDialog* ccPickOneElementDlg::m_ui protected
Associated UI.
Definition at line 39 of file ecvPickOneElementDlg.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CVAppCommon/include/ecvPickOneElementDlg.h