ACloudViewer: ccColorScalesManager Class Reference
ccColorScalesManager Class Reference
Color scales manager/container.
#include <ecvColorScalesManager.h>
Public Types
enum DEFAULT_SCALES {
BGYR = 0 , GREY = 1 , BWR = 2 , RY = 3 ,
RW = 4 , ABS_NORM_GREY = 5 , HSV_360_DEG = 6 , VERTEX_QUALITY = 7 ,
DIP_BRYW = 8 , DIP_DIR_REPEAT = 9 , VIRIDIS = 10 , BROWN_YELLOW = 11 ,
YELLOW_BROWN = 12 , TOPO_LANDSERF = 13 , HIGH_CONTRAST = 14 , CIVIDIS
}
Pre-defined color scales (all relative - i.e. expand to actual SF)
typedef QMap< QString, ccColorScale::Shared > ScalesMap
Color scales map type.
Public Member Functions
virtual ~ccColorScalesManager ()
Destructor.
ccColorScale::Shared getDefaultScale (DEFAULT_SCALES scale) const
Returns a pre-defined color scale.
ccColorScale::Shared getScale (QString UUID) const
Returns a color scale based on its UUID.
void addScale (ccColorScale::Shared scale)
Adds a new color scale.
void removeScale (QString UUID)
Removes a color scale.
ScalesMap & map ()
Access to the internal map.
const ScalesMap & map () const
Access to the internal map (const)
void fromPersistentSettings ()
Loads custom color scales from persistent settings.
void toPersistentSettings () const
Save custom color scales to persistent settings.
Static Public Member Functions
static ccColorScalesManager * GetUniqueInstance ()
Returns unique instance.
static void ReleaseUniqueInstance ()
Releases unique instance.
static QString GetDefaultScaleUUID (int scale)
Returns a pre-defined color scale UUID.
static ccColorScale::Shared GetDefaultScale (DEFAULT_SCALES scale=BGYR)
Returns a pre-defined color scale (static shortcut)
Protected Member Functions
ccColorScalesManager ()
Default constructor.
Static Protected Member Functions
static ccColorScale::Shared Create (DEFAULT_SCALES scaleType)
Creates a pre-defined color scale.
Protected Attributes
ScalesMap m_scales
Color scales.
Detailed Description
Color scales manager/container.
Definition at line 17 of file ecvColorScalesManager.h.
Member Typedef Documentation
ScalesMap
typedef QMap<QString, ccColorScale::Shared> ccColorScalesManager::ScalesMap
Color scales map type.
Definition at line 84 of file ecvColorScalesManager.h.
Member Enumeration Documentation
DEFAULT_SCALES
enum ccColorScalesManager::DEFAULT_SCALES
Pre-defined color scales (all relative - i.e. expand to actual SF)
Enumerator
BGYR
Blue-Green-Yellow-Red ramp (default for distances display)
GREY
Grey ramp (default for Global Illumination)
BWR
Blue-White-Red ramp (for signed SF)
RY
Red-Yellow ramp
RW
Red-White ramp
ABS_NORM_GREY
Absolute normalized grey ramp (intensities between 0 and 1)
HSV_360_DEG
HSV colors between 0 and 360 degrees
VERTEX_QUALITY
Mesh vertex quality (see cloudViewer::MeshSamplingTools::VertexFlags)
DIP_BRYW
Dip (0 - 90 degrees) (Brown-Red-Yellow-White)
DIP_DIR_REPEAT
Dip direction (0 - 360 degrees)
VIRIDIS
matplotlib library colorscale created by Stéfan van der Walt and Nathaniel Smith
BROWN_YELLOW
Brown-Yellow
YELLOW_BROWN
Yellow-Brown
TOPO_LANDSERF
Topo Landserf (quartile)
HIGH_CONTRAST
High contrast
CIVIDIS
matplotlib library colorscale - see https://arxiv.org/ftp/arxiv/papers/1712/1712.01662.pdf
Definition at line 29 of file ecvColorScalesManager.h.
Constructor & Destructor Documentation
~ccColorScalesManager()
virtual ccColorScalesManager::~ccColorScalesManager () virtual
Destructor.
ccColorScalesManager()
ccColorScalesManager::ccColorScalesManager () protected
Default constructor.
Member Function Documentation
addScale()
void ccColorScalesManager::addScale (ccColorScale::Shared scale)
Adds a new color scale.
Referenced by define_ccColorScalesManager().
Create()
static ccColorScale::Shared ccColorScalesManager::Create (DEFAULT_SCALES scaleType) static protected
Creates a pre-defined color scale.
fromPersistentSettings()
void ccColorScalesManager::fromPersistentSettings ()
Loads custom color scales from persistent settings.
Referenced by define_ccColorScalesManager().
getDefaultScale()
ccColorScale::Shared ccColorScalesManager::getDefaultScale (DEFAULT_SCALES scale) const inline
Returns a pre-defined color scale.
Definition at line 68 of file ecvColorScalesManager.h.
Referenced by define_ccColorScalesManager(), GetDefaultScale(), and StereogramDialog::StereogramDialog().
GetDefaultScale()
static ccColorScale::Shared ccColorScalesManager::GetDefaultScale (DEFAULT_SCALES scale = BGYR) inline static
Returns a pre-defined color scale (static shortcut)
Definition at line 61 of file ecvColorScalesManager.h.
References getDefaultScale().
Referenced by LasCloudChunk::addLasFieldsToCloud(), define_ccColorScalesManager(), DistanceMapGenerationDlg::DistanceMapGenerationDlg(), qPCV::doAction(), LASFWFFilter::loadFile(), LasIOFilter::loadFile(), LoadScan(), PCVCommand::Process(), StereogramDialog::StereogramDialog(), and DistanceMapGenerationDlg::update().
GetDefaultScaleUUID()
static QString ccColorScalesManager::GetDefaultScaleUUID (int scale) inline static
Returns a pre-defined color scale UUID.
Definition at line 56 of file ecvColorScalesManager.h.
Referenced by define_ccColorScalesManager().
getScale()
ccColorScale::Shared ccColorScalesManager::getScale (QString UUID) const
Returns a color scale based on its UUID.
Referenced by define_ccColorScalesManager().
GetUniqueInstance()
static ccColorScalesManager* ccColorScalesManager::GetUniqueInstance () static
Returns unique instance.
Referenced by define_ccColorScalesManager().
map() [1/2]
ScalesMap& ccColorScalesManager::map () inline
Access to the internal map.
Definition at line 87 of file ecvColorScalesManager.h.
map() [2/2]
const ScalesMap& ccColorScalesManager::map () const inline
Access to the internal map (const)
Definition at line 90 of file ecvColorScalesManager.h.
ReleaseUniqueInstance()
static void ccColorScalesManager::ReleaseUniqueInstance () static
Releases unique instance.
Referenced by define_ccColorScalesManager().
removeScale()
void ccColorScalesManager::removeScale (QString UUID)
Removes a color scale.
Warning: can't remove default scales!
Referenced by define_ccColorScalesManager().
toPersistentSettings()
void ccColorScalesManager::toPersistentSettings () const
Save custom color scales to persistent settings.
Referenced by define_ccColorScalesManager().
Member Data Documentation
m_scales
ScalesMap ccColorScalesManager::m_scales protected
Color scales.
Definition at line 106 of file ecvColorScalesManager.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvColorScalesManager.h