ACloudViewer: ecvGui Class Reference
ecvGui Class Reference
This class manages some persistent parameters (mostly for display)
#include <ecvGuiParameters.h>
Classes
struct ParamStruct
GUI parameters.
Static Public Member Functions
static const ParamStruct & Parameters ()
Returns the stored values of each parameter.
static void Set (const ParamStruct &params)
Sets GUI parameters.
static void UpdateParameters ()
static void ReleaseInstance ()
Release unique instance (if any)
Protected Attributes
ParamStruct params
Parameters set.
Detailed Description
This class manages some persistent parameters (mostly for display)
Values of persistent parameters are stored by the system (either in the registry or in a separate file depending on the OS).
Definition at line 25 of file ecvGuiParameters.h.
Member Function Documentation
Parameters()
const ecvGui::ParamStruct & ecvGui::Parameters () static
Returns the stored values of each parameter.
Definition at line 24 of file ecvGuiParameters.cpp.
References s_gui.
Referenced by ccDisplayOptionsDlg::ccDisplayOptionsDlg(), ccEntityAction::computeStatParams(), ccHObject::draw(), MatrixDisplayDlg::fillDialogWith(), ccPropertiesTreeDelegate::fillWithLabel(), ecvDisplayTools::GetDisplayParameters(), ccPointPropertiesDlg::processPickedPoint(), ccHistogramWindow::refresh(), ccWaveWidget::refresh(), cloudViewer::ModelViewerWidget::SetBackgroundColor(), ccPropertiesTreeDelegate::setEditorData(), and ecvDisplayTools::StartCPUBasedPointPicking().
ReleaseInstance()
void ecvGui::ReleaseInstance () static
Release unique instance (if any)
Definition at line 39 of file ecvGuiParameters.cpp.
References s_gui.
Set()
void ecvGui::Set (const ParamStruct & params) static
Sets GUI parameters.
Definition at line 41 of file ecvGuiParameters.cpp.
References params, and s_gui.
Referenced by ccDisplayOptionsDlg::apply(), ccDisplayOptionsDlg::doReject(), ecvDisplayTools::SetDisplayParameters(), and ecvDisplayTools::StartCPUBasedPointPicking().
UpdateParameters()
void ecvGui::UpdateParameters () static
Definition at line 33 of file ecvGuiParameters.cpp.
References s_gui.
Referenced by ecvDisplayTools::GetDisplayParameters().
Member Data Documentation
params
ParamStruct ecvGui::params protected
Parameters set.
Definition at line 145 of file ecvGuiParameters.h.
Referenced by Set().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/ecvGuiParameters.h
/root/ACloudViewer/libs/CV_db/src/ecvGuiParameters.cpp