ACloudViewer: cloudViewer::GenericDistribution Class Reference
cloudViewer::GenericDistribution Class Reference abstract
A generic class to handle a probability distribution.
#include <GenericDistribution.h>
Public Types
using ScalarContainer = std::vector< ScalarType >
Scalar values container.
Public Member Functions
GenericDistribution ()
Default constructor.
virtual ~GenericDistribution ()=default
Default destructor.
virtual const char * getName () const =0
Returns distribution name.
virtual bool isValid () const
Indicates if the distribution parameters are valid.
virtual bool computeParameters (const ScalarContainer &values)=0
Computes the distribution parameters from a set of values.
virtual double computeP (ScalarType x) const =0
Computes the probability of x.
virtual double computePfromZero (ScalarType x) const =0
Computes the cumulative probability between 0 and x.
virtual double computeP (ScalarType x1, ScalarType x2) const =0
Computes the cumulative probability between x1 and x2.
virtual double computeChi2Dist (const GenericCloud *Yk, unsigned numberOfClasses, int *histo=nullptr)=0
Computes the Chi2 distance (related to the Chi2 Test)
Protected Member Functions
void setValid (bool state)
Sets distribution current validity.
Protected Attributes
bool m_isValid
Whether the distribution is in a valid state or not.
Detailed Description
A generic class to handle a probability distribution.
Custom parametric distributions can be implemented through this interface and used for filtering data (see StatisticalTestingTools).
Definition at line 25 of file GenericDistribution.h.
Member Typedef Documentation
ScalarContainer
using cloudViewer::GenericDistribution::ScalarContainer = std::vector<ScalarType>
Scalar values container.
Definition at line 46 of file GenericDistribution.h.
Constructor & Destructor Documentation
GenericDistribution()
cloudViewer::GenericDistribution::GenericDistribution () inline
Default constructor.
Definition at line 28 of file GenericDistribution.h.
~GenericDistribution()
virtual cloudViewer::GenericDistribution::~GenericDistribution () virtual default
Default destructor.
Member Function Documentation
computeChi2Dist()
virtual double cloudViewer::GenericDistribution::computeChi2Dist (const GenericCloud * Yk, unsigned numberOfClasses, int * histo = nullptr) pure virtual
Computes the Chi2 distance (related to the Chi2 Test)
Computes the Chi2 distance from a group of point, accordingly to a certain number of classes (see Chi2 test theory for more information). The result of projecting each point (or more precisely each scalar value associated to each point) in the different classes can be stored in an array (of the same size as the number of classes). To do so, such an array (already allocated in memory) should be passed as an argument. Warning: be sure to activate an OUTPUT scalar field on the input cloud
Parameters
Yk a group of points
numberOfClasses the number of classes for the Chi2 Test
histo an array to store the values projection result (optional)
Returns
the Chi2 distance (or -1.0 if an error occurred)
Implemented in cloudViewer::NormalDistribution, and cloudViewer::WeibullDistribution.
Referenced by define_GenericDistribution().
computeP() [1/2]
virtual double cloudViewer::GenericDistribution::computeP (ScalarType x) const pure virtual
Computes the probability of x.
Parameters
x the variable
Returns
the probabilty
Implemented in cloudViewer::WeibullDistribution, and cloudViewer::NormalDistribution.
Referenced by define_GenericDistribution().
computeP() [2/2]
virtual double cloudViewer::GenericDistribution::computeP (ScalarType x1, ScalarType x2) const pure virtual
Computes the cumulative probability between x1 and x2.
x1 should be lower than x2
Parameters
x1 the lower boundary
x2 the upper boundary
Returns
the cumulative probabilty
Implemented in cloudViewer::WeibullDistribution, and cloudViewer::NormalDistribution.
computeParameters()
virtual bool cloudViewer::GenericDistribution::computeParameters (const ScalarContainer & values) pure virtual
Computes the distribution parameters from a set of values.
Parameters
values a set of scalar values
Returns
true (if the computation succeeded) or false (if not)
Implemented in cloudViewer::WeibullDistribution, and cloudViewer::NormalDistribution.
Referenced by define_GenericDistribution().
computePfromZero()
virtual double cloudViewer::GenericDistribution::computePfromZero (ScalarType x) const pure virtual
Computes the cumulative probability between 0 and x.
Parameters
x the upper boundary
Returns
the cumulative probabilty
Implemented in cloudViewer::WeibullDistribution, and cloudViewer::NormalDistribution.
Referenced by define_GenericDistribution().
getName()
virtual const char* cloudViewer::GenericDistribution::getName () const pure virtual
Returns distribution name.
Implemented in cloudViewer::WeibullDistribution, and cloudViewer::NormalDistribution.
Referenced by define_GenericDistribution().
isValid()
virtual bool cloudViewer::GenericDistribution::isValid () const inline virtual
Indicates if the distribution parameters are valid.
This function is related to 'computeParameters()'. If the parameters computation failed, then the parameters will be marked as 'invalid'. In this case, the dsitribution should'nt be used (most of the methods won't work anyway).
Returns
true (if the distribution parameters are valid) or false (if not)
Definition at line 43 of file GenericDistribution.h.
Referenced by define_GenericDistribution().
setValid()
void cloudViewer::GenericDistribution::setValid (bool state) inline protected
Sets distribution current validity.
Definition at line 93 of file GenericDistribution.h.
Member Data Documentation
m_isValid
bool cloudViewer::GenericDistribution::m_isValid protected
Whether the distribution is in a valid state or not.
Definition at line 96 of file GenericDistribution.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/GenericDistribution.h