ACloudViewer: ccStatisticalTestDlg Class Reference
ccStatisticalTestDlg Class Reference
Dialog for the Local Statistical Test tool.
#include <ecvStatisticalTestDlg.h>
Public Member Functions
ccStatisticalTestDlg (QString param1Label, QString param2Label, QString param3Label=QString(), QString windowTitle=QString(), QWidget *parent=0)
Default constructor (for distributions with up to 3 parameters)
double getParam1 () const
Returns 1st parameter value.
double getParam2 () const
Returns 2nd parameter value.
double getParam3 () const
Returns 3rd parameter value.
int getNeighborsNumber () const
Returns the number of neighbors.
double getProba () const
Returns the associated probability.
Detailed Description
Dialog for the Local Statistical Test tool.
Definition at line 13 of file ecvStatisticalTestDlg.h.
Constructor & Destructor Documentation
ccStatisticalTestDlg()
ccStatisticalTestDlg::ccStatisticalTestDlg (QString param1Label, QString param2Label, QString param3Label = QString(), QString windowTitle = QString(), QWidget * parent = 0)
Default constructor (for distributions with up to 3 parameters)
Definition at line 10 of file ecvStatisticalTestDlg.cpp.
Member Function Documentation
getNeighborsNumber()
int ccStatisticalTestDlg::getNeighborsNumber () const
Returns the number of neighbors.
Definition at line 44 of file ecvStatisticalTestDlg.cpp.
Referenced by ccEntityAction::statisticalTest().
getParam1()
double ccStatisticalTestDlg::getParam1 () const
Returns 1st parameter value.
Definition at line 32 of file ecvStatisticalTestDlg.cpp.
Referenced by ccEntityAction::statisticalTest().
getParam2()
double ccStatisticalTestDlg::getParam2 () const
Returns 2nd parameter value.
Definition at line 36 of file ecvStatisticalTestDlg.cpp.
Referenced by ccEntityAction::statisticalTest().
getParam3()
double ccStatisticalTestDlg::getParam3 () const
Returns 3rd parameter value.
Definition at line 40 of file ecvStatisticalTestDlg.cpp.
Referenced by ccEntityAction::statisticalTest().
getProba()
double ccStatisticalTestDlg::getProba () const
Returns the associated probability.
Definition at line 48 of file ecvStatisticalTestDlg.cpp.
Referenced by ccEntityAction::statisticalTest().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvStatisticalTestDlg.h
/root/ACloudViewer/app/ecvStatisticalTestDlg.cpp