ACloudViewer: ccColorLevelsDlg Class Reference
ccColorLevelsDlg Class Reference
Dialog to change the color levels.
#include <ecvColorLevelsDlg.h>
Public Member Functions
ccColorLevelsDlg (QWidget *parent, ccGenericPointCloud *pointCloud)
Default constructor.
Protected Types
enum CHANNELS { RGB = 0 , RED = 1 , GREEN = 2 , BLUE = 3 }
Channels.
Protected Slots
void onChannelChanged (int)
void onApply ()
Protected Member Functions
void updateHistogram ()
Updates histogram.
Protected Attributes
ccHistogramWindow * m_histogram
Associated histogram view.
ccGenericPointCloud * m_cloud
Associated point cloud (color source)
Detailed Description
Dialog to change the color levels.
Definition at line 19 of file ecvColorLevelsDlg.h.
Member Enumeration Documentation
CHANNELS
enum ccColorLevelsDlg::CHANNELS protected
Channels.
Enumerator
RGB
RED
GREEN
BLUE
Definition at line 33 of file ecvColorLevelsDlg.h.
Constructor & Destructor Documentation
ccColorLevelsDlg()
ccColorLevelsDlg::ccColorLevelsDlg (QWidget * parent, ccGenericPointCloud * pointCloud)
Default constructor.
Definition at line 31 of file ecvColorLevelsDlg.cpp.
References ecvColor::black(), m_histogram, onApply(), onChannelChanged(), s_inputLevels, s_outputLevels, s_outputLevelsEnabled, ccHistogramWindow::setColorScheme(), ccHistogramWindow::setSolidColor(), updateHistogram(), and ccHistogramWindow::USE_SOLID_COLOR.
Member Function Documentation
onApply
void ccColorLevelsDlg::onApply () protected slot
Definition at line 142 of file ecvColorLevelsDlg.cpp.
References BLUE, ccGenericPointCloud::getPointColor(), GREEN, m_cloud, ecvColor::MAX, onChannelChanged(), RED, ecvDisplayTools::RedrawDisplay(), RGB, ecvColor::RgbTpl< Type >::rgb, s_inputLevels, s_outputLevels, s_outputLevelsEnabled, ccPointCloud::setPointColor(), cloudViewer::GenericCloud::size(), and ccHObjectCaster::ToPointCloud().
Referenced by ccColorLevelsDlg().
onChannelChanged
void ccColorLevelsDlg::onChannelChanged (int channel) protected slot
Definition at line 140 of file ecvColorLevelsDlg.cpp.
References updateHistogram().
Referenced by ccColorLevelsDlg(), and onApply().
updateHistogram()
void ccColorLevelsDlg::updateHistogram () protected
Updates histogram.
Definition at line 67 of file ecvColorLevelsDlg.cpp.
References ecvColor::RgbTpl< Type >::b, ecvColor::black(), BLUE, ecvColor::blue(), ccHistogramWindow::clear(), ccHistogramWindow::fromBinArray(), ecvColor::RgbTpl< Type >::g, ccGenericPointCloud::getPointColor(), GREEN, ecvColor::green(), m_cloud, m_histogram, ecvColor::RgbTpl< Type >::r, RED, ecvColor::red(), ccHistogramWindow::refresh(), RGB, ccHistogramWindow::setAxisLabels(), ccHistogramWindow::setSolidColor(), and cloudViewer::GenericCloud::size().
Referenced by ccColorLevelsDlg(), and onChannelChanged().
Member Data Documentation
m_cloud
ccGenericPointCloud* ccColorLevelsDlg::m_cloud protected
Associated point cloud (color source)
Definition at line 42 of file ecvColorLevelsDlg.h.
Referenced by onApply(), and updateHistogram().
m_histogram
ccHistogramWindow* ccColorLevelsDlg::m_histogram protected
Associated histogram view.
Definition at line 39 of file ecvColorLevelsDlg.h.
Referenced by ccColorLevelsDlg(), and updateHistogram().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvColorLevelsDlg.h
/root/ACloudViewer/app/ecvColorLevelsDlg.cpp