ACloudViewer: LDATrainer Class Reference
LDATrainer Class Reference
#include <trainer.h>
Public Types
typedef dlib::matrix< float, 0, 1 > sample_type
typedef dlib::linear_kernel< sample_type > kernel_type
typedef dlib::decision_function< kernel_type > trained_function_type
Public Member Functions
trained_function_type train (const std::vector< sample_type > &samplesvec, const std::vector< float > &labels) const
void train (int nfolds, const std::vector< sample_type > &samples, const std::vector< float > &labels)
double predict (const sample_type &data) const
Public Attributes
std::vector< float > m_weights
Classifier weights.
Detailed Description
Definition at line 17 of file trainer.h.
Member Typedef Documentation
kernel_type
typedef dlib::linear_kernel<sample_type> LDATrainer::kernel_type
Definition at line 20 of file trainer.h.
sample_type
typedef dlib::matrix<float, 0, 1> LDATrainer::sample_type
Definition at line 19 of file trainer.h.
trained_function_type
typedef dlib::decision_function<kernel_type> LDATrainer::trained_function_type
Definition at line 21 of file trainer.h.
Member Function Documentation
predict()
double LDATrainer::predict (const sample_type & data) const inline
Definition at line 202 of file trainer.h.
References m_weights.
Referenced by DilateClassifier(), and qCanupoTools::TrainClassifier().
train() [1/2]
trained_function_type LDATrainer::train (const std::vector< sample_type > & samplesvec, const std::vector< float > & labels) const inline
Definition at line 24 of file trainer.h.
References dot().
Referenced by qCanupoTools::TrainClassifier().
train() [2/2]
void LDATrainer::train (int nfolds, const std::vector< sample_type > & samples, const std::vector< float > & labels) inline
Definition at line 177 of file trainer.h.
References m_weights.
Member Data Documentation
m_weights
std::vector<float> LDATrainer::m_weights
Classifier weights.
Definition at line 211 of file trainer.h.
Referenced by DilateClassifier(), predict(), train(), and qCanupoTools::TrainClassifier().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qCanupo/include/trainer.h