ACloudViewer: cloudViewer::CloudSamplingTools Class Reference
cloudViewer::CloudSamplingTools Class Reference
Several point cloud resampling algorithms (octree-based, random, etc.)
#include <CloudSamplingTools.h>
Classes
struct SFModulationParams
Parameters for the scalar-field based modulation of a parameter.
Public Types
enum RESAMPLING_CELL_METHOD { CELL_CENTER , CELL_GRAVITY_CENTER }
enum SUBSAMPLING_CELL_METHOD { RANDOM_POINT , NEAREST_POINT_TO_CELL_CENTER }
Static Public Member Functions
static PointCloud * resampleCloudWithOctreeAtLevel (GenericIndexedCloudPersist *cloud, unsigned char octreeLevel, RESAMPLING_CELL_METHOD resamplingMethod, GenericProgressCallback *progressCb=nullptr, DgmOctree *inputOctree=nullptr)
Resamples a point cloud (process based on the octree)
static GenericIndexedCloud * resampleCloudWithOctree (GenericIndexedCloudPersist *cloud, int newNumberOfPoints, RESAMPLING_CELL_METHOD resamplingMethod, GenericProgressCallback *progressCb=nullptr, DgmOctree *inputOctree=nullptr)
Resamples a point cloud (process based on the octree)
static ReferenceCloud * subsampleCloudWithOctreeAtLevel (GenericIndexedCloudPersist *cloud, unsigned char octreeLevel, SUBSAMPLING_CELL_METHOD subsamplingMethod, GenericProgressCallback *progressCb=nullptr, DgmOctree *inputOctree=nullptr)
Subsamples a point cloud (process based on the octree)
static ReferenceCloud * subsampleCloudWithOctree (GenericIndexedCloudPersist *cloud, int newNumberOfPoints, SUBSAMPLING_CELL_METHOD subsamplingMethod, GenericProgressCallback *progressCb=nullptr, DgmOctree *inputOctree=nullptr)
Subsamples a point cloud (process based on the octree)
static ReferenceCloud * subsampleCloudRandomly (GenericIndexedCloudPersist *cloud, unsigned newNumberOfPoints, GenericProgressCallback *progressCb=nullptr)
Subsamples a point cloud (process based on random selections)
static ReferenceCloud * UniformDownSample (GenericIndexedCloudPersist *cloud, unsigned every_k_points)
static ReferenceCloud * resampleCloudSpatially (GenericIndexedCloudPersist *cloud, PointCoordinateType minDistance, const SFModulationParams &modParams, DgmOctree *octree=nullptr, GenericProgressCallback *progressCb=nullptr)
Resamples a point cloud (process based on inter point distance)
static ReferenceCloud * sorFilter (GenericIndexedCloudPersist *cloud, int knn=6, double nSigma=1.0, DgmOctree *octree=nullptr, GenericProgressCallback *progressCb=nullptr)
Statistical Outliers Removal (SOR) filter.
static ReferenceCloud * noiseFilter (GenericIndexedCloudPersist *cloud, PointCoordinateType kernelRadius, double nSigma, bool removeIsolatedPoints=false, bool useKnn=false, int knn=6, bool useAbsoluteError=true, double absoluteError=0.0, DgmOctree *octree=nullptr, GenericProgressCallback *progressCb=nullptr)
Noise filter based on the distance to the approximate local surface.
Static Protected Member Functions
static bool resampleCellAtLevel (const DgmOctree::octreeCell &cell, void **additionalParameters, NormalizedProgress *nProgress=nullptr)
static bool subsampleCellAtLevel (const DgmOctree::octreeCell &cell, void **additionalParameters, NormalizedProgress *nProgress=nullptr)
"Cellular" function to select a unique point inside an octree cell
static bool applyNoiseFilterAtLevel (const DgmOctree::octreeCell &cell, void **additionalParameters, NormalizedProgress *nProgress=nullptr)
"Cellular" function to apply the noise filter inside an octree cell
static bool applySORFilterAtLevel (const DgmOctree::octreeCell &cell, void **additionalParameters, NormalizedProgress *nProgress=nullptr)
"Cellular" function to apply the SOR filter inside an octree cell
Detailed Description
Several point cloud resampling algorithms (octree-based, random, etc.)
Definition at line 25 of file CloudSamplingTools.h.
Member Enumeration Documentation
RESAMPLING_CELL_METHOD
enum cloudViewer::CloudSamplingTools::RESAMPLING_CELL_METHOD
Octree cell resampling methods (see CloudSamplingTools::resampleCloudWithOctree)
Enumerator
CELL_CENTER
CELL_GRAVITY_CENTER
Definition at line 29 of file CloudSamplingTools.h.
SUBSAMPLING_CELL_METHOD
enum cloudViewer::CloudSamplingTools::SUBSAMPLING_CELL_METHOD
Octree cell simplifying methods (see CloudSamplingTools::subsampleCloudWithOctree)
Enumerator
RANDOM_POINT
NEAREST_POINT_TO_CELL_CENTER
Definition at line 33 of file CloudSamplingTools.h.
Member Function Documentation
applyNoiseFilterAtLevel()
bool CloudSamplingTools::applyNoiseFilterAtLevel (const DgmOctree::octreeCell & cell, void ** additionalParameters, NormalizedProgress * nProgress = nullptr) static protected
"Cellular" function to apply the noise filter inside an octree cell
This function is meant to be applied to all cells of the octree (it is of the form DgmOctree::localFunctionPtr).
Parameters
cell structure describing the cell on which processing is applied
additionalParameters see method description
nProgress optional (normalized) progress notification (per-point)
Definition at line 710 of file CloudSamplingTools.cpp.
References cloudViewer::ReferenceCloud::addPointIndex(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::cellCenter, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::cellPos, cloudViewer::DgmOctree::computeCellCenter(), cloudViewer::DistanceComputationTools::computePoint2PlaneDistance(), cloudViewer::DgmOctree::findNearestNeighborsStartingFromCell(), cloudViewer::DgmOctree::findNeighborsInASphereStartingFromCell(), cloudViewer::DgmOctree::getCellPos(), cloudViewer::DgmOctree::getCellSize(), cloudViewer::Neighbourhood::getLSPlane(), cloudViewer::DgmOctreeReferenceCloud::getPoint(), cloudViewer::ReferenceCloud::getPoint(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::level, cloudViewer::DgmOctree::octreeCell::level, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::minNumberOfNeighbors, nProgress, cloudViewer::NormalizedProgress::oneStep(), cloudViewer::DgmOctree::octreeCell::parentOctree, cloudViewer::DgmOctree::octreeCell::points, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::pointsInNeighbourhood, cloudViewer::DgmOctree::NearestNeighboursSphericalSearchStruct::prepare(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::queryPoint, cloudViewer::ReferenceCloud::size(), stddev(), std::swap(), and cloudViewer::DgmOctree::octreeCell::truncatedCode.
Referenced by noiseFilter().
applySORFilterAtLevel()
bool CloudSamplingTools::applySORFilterAtLevel (const DgmOctree::octreeCell & cell, void ** additionalParameters, NormalizedProgress * nProgress = nullptr) static protected
"Cellular" function to apply the SOR filter inside an octree cell
This function is meant to be applied to all cells of the octree (it is of the form DgmOctree::localFunctionPtr).
Parameters
cell structure describing the cell on which processing is applied
additionalParameters see method description
nProgress optional (normalized) progress notification (per-point)
Definition at line 835 of file CloudSamplingTools.cpp.
References cloudViewer::DgmOctree::computeCellCenter(), count, cloudViewer::DgmOctree::findNearestNeighborsStartingFromCell(), cloudViewer::DgmOctree::getCellPos(), cloudViewer::ReferenceCloud::getPoint(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::level, cloudViewer::DgmOctree::octreeCell::level, nProgress, cloudViewer::NormalizedProgress::oneStep(), cloudViewer::DgmOctree::octreeCell::parentOctree, cloudViewer::DgmOctree::octreeCell::points, cloudViewer::ReferenceCloud::size(), and cloudViewer::DgmOctree::octreeCell::truncatedCode.
Referenced by sorFilter().
noiseFilter()
ReferenceCloud * CloudSamplingTools::noiseFilter (GenericIndexedCloudPersist * cloud, PointCoordinateType kernelRadius, double nSigma, bool removeIsolatedPoints = false, bool useKnn = false, int knn = 6, bool useAbsoluteError = true, double absoluteError = 0.0, DgmOctree * octree = nullptr, GenericProgressCallback * progressCb = nullptr) static
Noise filter based on the distance to the approximate local surface.
This filter removes points based on their distance relatively to the best fit plane computed on their neighbors.
Parameters
cloud the point cloud to resample
kernelRadius neighborhood radius
nSigma number of sigmas under which the points should be kept
removeIsolatedPoints whether to remove isolated points (i.e. with 3 points or less in the neighborhood)
useKnn whether to use a constant number of neighbors instead of a radius
knn number of neighbors (if useKnn is true)
useAbsoluteError whether to use an absolute error instead of 'n' sigmas
absoluteError absolute error (if useAbsoluteError is true)
octree associated octree if available
progressCb the client application can get some notification of the process progress through this callback mechanism (see GenericProgressCallback)
Returns
a reference cloud corresponding to the filtered cloud
Definition at line 563 of file CloudSamplingTools.cpp.
References applyNoiseFilterAtLevel(), cloudViewer::DgmOctree::build(), cloudViewer::DgmOctree::executeFunctionForAllCellsAtLevel(), cloudViewer::DgmOctree::findBestLevelForAGivenNeighbourhoodSizeExtraction(), cloudViewer::DgmOctree::findBestLevelForAGivenPopulationPerCell(), octree, octreeLevel, cloudViewer::ReferenceCloud::reserve(), cloudViewer::ReferenceCloud::resize(), cloudViewer::GenericCloud::size(), and cloudViewer::ReferenceCloud::size().
Referenced by define_CloudSamplingTools().
resampleCellAtLevel()
bool CloudSamplingTools::resampleCellAtLevel (const DgmOctree::octreeCell & cell, void ** additionalParameters, NormalizedProgress * nProgress = nullptr) static protected
"Cellular" function to replace one set of points (contained in an octree cell) by a unique point This function is meant to be applied to all cells of the octree (it is of the form DgmOctree::localFunctionPtr). It replaces all points in a cell by a unique one, according to different rules. Method parameters (defined in "additionalParameters") are :
(PointCloud*) point cloud to store new points
(RESAMPLING_CELL_METHOD*) resampling method
Parameters
cell structure describing the cell on which processing is applied
additionalParameters see method description
nProgress optional (normalized) progress notification (per-point)
Definition at line 638 of file CloudSamplingTools.cpp.
References cloudViewer::PointCloudTpl< T >::addPoint(), CELL_GRAVITY_CENTER, cloudViewer::DgmOctree::computeCellCenter(), cloudViewer::Neighbourhood::getGravityCenter(), cloudViewer::DgmOctree::octreeCell::level, nProgress, cloudViewer::DgmOctree::octreeCell::parentOctree, cloudViewer::DgmOctree::octreeCell::points, cloudViewer::ReferenceCloud::size(), cloudViewer::NormalizedProgress::steps(), and cloudViewer::DgmOctree::octreeCell::truncatedCode.
Referenced by resampleCloudWithOctreeAtLevel().
resampleCloudSpatially()
ReferenceCloud * CloudSamplingTools::resampleCloudSpatially (GenericIndexedCloudPersist * cloud, PointCoordinateType minDistance, const SFModulationParams & modParams, DgmOctree * octree = nullptr, GenericProgressCallback * progressCb = nullptr) static
Resamples a point cloud (process based on inter point distance)
The cloud is resampled so that there is no point nearer than a given distance to other points It works by picking a reference point, removing all points which are to close to this point, and repeating these two steps until the result is reached
Parameters
cloud the point cloud to resample
minDistance the distance under which a point in the resulting cloud cannot have any neighbour
modParams parameters of the subsampling behavior modulation with a scalar field (optional)
octree associated octree if available
progressCb the client application can get some notification of the process progress through this callback mechanism (see GenericProgressCallback)
Returns
a reference cloud corresponding to the resampling 'selection'
Definition at line 256 of file CloudSamplingTools.cpp.
References cloudViewer::CloudSamplingTools::SFModulationParams::a, cloudViewer::ReferenceCloud::addPointIndex(), cloudViewer::DgmOctree::associatedCloud(), cloudViewer::CloudSamplingTools::SFModulationParams::b, cloudViewer::DgmOctree::build(), cloudViewer::ReferenceCloud::capacity(), cloudViewer::ScalarFieldTools::computeScalarFieldExtremas(), cloudViewer::CloudSamplingTools::SFModulationParams::enabled, cloudViewer::DgmOctree::findBestLevelForAGivenNeighbourhoodSizeExtraction(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::GenericCloud::getPointScalarValue(), cloudViewer::DgmOctree::getPointsInSphericalNeighbourhood(), octree, octreeLevel, cloudViewer::NormalizedProgress::oneStep(), cloudViewer::ReferenceCloud::reserve(), cloudViewer::ReferenceCloud::resize(), cloudViewer::GenericProgressCallback::setInfo(), cloudViewer::GenericProgressCallback::setMethodTitle(), cloudViewer::GenericCloud::size(), cloudViewer::ReferenceCloud::size(), cloudViewer::GenericProgressCallback::start(), cloudViewer::GenericProgressCallback::stop(), cloudViewer::GenericProgressCallback::textCanBeEdited(), cloudViewer::GenericProgressCallback::update(), and cloudViewer::ScalarField::ValidValue().
Referenced by qM3C2Process::Compute(), define_CloudSamplingTools(), qCanupoPlugin::doClassifyAction(), getMortarMaps(), ccSubsamplingDlg::getSampledCloud(), ccAlignDlg::getSampledData(), ccAlignDlg::getSampledModel(), masc::CorePoints::prepare(), and CommandSubsample::process().
resampleCloudWithOctree()
GenericIndexedCloud * CloudSamplingTools::resampleCloudWithOctree (GenericIndexedCloudPersist * cloud, int newNumberOfPoints, RESAMPLING_CELL_METHOD resamplingMethod, GenericProgressCallback * progressCb = nullptr, DgmOctree * inputOctree = nullptr) static
Resamples a point cloud (process based on the octree)
Same as 'resampleCloudWithOctreeAtLevel' method, apart the fact that instead of giving a specific octree subdivision level as input parameter, one can specify an approximative number of points for the resulting cloud (algorithm will automatically determine the corresponding octree level).
Parameters
cloud the point cloud to resample
newNumberOfPoints desired number of points (approximative)
resamplingMethod resampling method (applied to each octree cell)
progressCb the client application can get some notification of the process progress through this callback mechanism (see GenericProgressCallback)
inputOctree if the octree has been already computed, it can be used by the process (avoid recomputation)
Returns
the resampled cloud (new cloud)
Definition at line 27 of file CloudSamplingTools.cpp.
References cloudViewer::DgmOctree::build(), cloudViewer::DgmOctree::findBestLevelForAGivenCellNumber(), octree, and resampleCloudWithOctreeAtLevel().
Referenced by define_CloudSamplingTools().
resampleCloudWithOctreeAtLevel()
PointCloud * CloudSamplingTools::resampleCloudWithOctreeAtLevel (GenericIndexedCloudPersist * cloud, unsigned char octreeLevel, RESAMPLING_CELL_METHOD resamplingMethod, GenericProgressCallback * progressCb = nullptr, DgmOctree * inputOctree = nullptr) static
Resamples a point cloud (process based on the octree)
A resampling algorithm is applied inside each cell of the octree. The different resampling methods are represented as an enumerator (see RESAMPLING_CELL_METHOD) and consist in simple processes such as replacing all the points lying in a cell by the cell center or by the points gravity center.
Parameters
cloud the point cloud to resample
octreeLevel the octree level at which to perform the resampling process
resamplingMethod resampling method (applied to each octree cell)
progressCb the client application can get some notification of the process progress through this callback mechanism (see GenericProgressCallback)
inputOctree if the octree has been already computed, it can be used by the process (avoid recomputation)
Returns
the resampled cloud (new cloud)
Definition at line 54 of file CloudSamplingTools.cpp.
References cloudViewer::DgmOctree::build(), cloudViewer::DgmOctree::executeFunctionForAllCellsAtLevel(), cloudViewer::DgmOctree::getCellNumber(), octree, octreeLevel, resampleCellAtLevel(), and cloudViewer::PointCloudTpl< T >::reserve().
Referenced by define_CloudSamplingTools(), and resampleCloudWithOctree().
sorFilter()
ReferenceCloud * CloudSamplingTools::sorFilter (GenericIndexedCloudPersist * cloud, int knn = 6, double nSigma = 1.0, DgmOctree * octree = nullptr, GenericProgressCallback * progressCb = nullptr) static
Statistical Outliers Removal (SOR) filter.
This filter removes points based on their mean distance to their distance (by comparing it to the average distance of all points to their neighbors). It is equivalent to PCL StatisticalOutlierRemoval filter (see http://pointclouds.org/documentation/tutorials/statistical_outlier.php)
Parameters
cloud the point cloud to resample
knn number of neighbors
nSigma number of sigmas under which the points should be kept
octree associated octree if available
progressCb the client application can get some notification of the process progress through this callback mechanism (see GenericProgressCallback)
Returns
a reference cloud corresponding to the filtered cloud
Definition at line 464 of file CloudSamplingTools.cpp.
References cloudViewer::ReferenceCloud::addPointIndex(), applySORFilterAtLevel(), cloudViewer::DgmOctree::build(), cloudViewer::DgmOctree::executeFunctionForAllCellsAtLevel(), cloudViewer::DgmOctree::findBestLevelForAGivenPopulationPerCell(), octree, octreeLevel, cloudViewer::ReferenceCloud::reserve(), cloudViewer::ReferenceCloud::resize(), cloudViewer::GenericCloud::size(), and cloudViewer::ReferenceCloud::size().
Referenced by define_CloudSamplingTools(), and CommandSORFilter::process().
subsampleCellAtLevel()
bool CloudSamplingTools::subsampleCellAtLevel (const DgmOctree::octreeCell & cell, void ** additionalParameters, NormalizedProgress * nProgress = nullptr) static protected
"Cellular" function to select a unique point inside an octree cell
This function is meant to be applied to all cells of the octree (it is of the form DgmOctree::localFunctionPtr). It chooses one point from the set of points inside a cell, according to different rules. Method parameters (defined in "additionalParameters") are :
(ReferenceCloud*) reference point cloud to store selected points
(SUBSAMPLING_CELL_METHOD*) subampling method
Parameters
cell structure describing the cell on which processing is applied
additionalParameters see method description
nProgress optional (normalized) progress notification (per-point)
Definition at line 665 of file CloudSamplingTools.cpp.
References cloudViewer::ReferenceCloud::addPointIndex(), cloudViewer::DgmOctree::computeCellCenter(), cloudViewer::ReferenceCloud::getPoint(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), cloudViewer::DgmOctree::octreeCell::level, nProgress, cloudViewer::NormalizedProgress::oneStep(), cloudViewer::DgmOctree::octreeCell::parentOctree, cloudViewer::DgmOctree::octreeCell::points, RANDOM_POINT, cloudViewer::ReferenceCloud::size(), cloudViewer::NormalizedProgress::steps(), and cloudViewer::DgmOctree::octreeCell::truncatedCode.
Referenced by subsampleCloudWithOctreeAtLevel().
subsampleCloudRandomly()
ReferenceCloud * CloudSamplingTools::subsampleCloudRandomly (GenericIndexedCloudPersist * cloud, unsigned newNumberOfPoints, GenericProgressCallback * progressCb = nullptr) static
Subsamples a point cloud (process based on random selections)
A very simple subsampling algorithm that simply consists in selecting "n" different points, in a random way.
Parameters
cloud point cloud to subsample
newNumberOfPoints desired number of points (exact)
progressCb the client application can get some notification of the process progress through this callback mechanism (see GenericProgressCallback)
Returns
a reference cloud corresponding to the subsampling 'selection'
Definition at line 202 of file CloudSamplingTools.cpp.
References cloudViewer::ReferenceCloud::addPointIndex(), cloudViewer::NormalizedProgress::oneStep(), cloudViewer::ReferenceCloud::resize(), cloudViewer::GenericProgressCallback::setInfo(), cloudViewer::GenericCloud::size(), cloudViewer::GenericProgressCallback::start(), cloudViewer::ReferenceCloud::swap(), cloudViewer::GenericProgressCallback::textCanBeEdited(), and cloudViewer::GenericProgressCallback::update().
Referenced by define_CloudSamplingTools(), qCanupoPlugin::doTrainAction(), ccSubsamplingDlg::getSampledCloud(), ccAlignDlg::getSampledData(), ccAlignDlg::getSampledModel(), masc::CorePoints::prepare(), CommandSubsample::process(), and cloudViewer::ICPRegistrationTools::Register().
subsampleCloudWithOctree()
ReferenceCloud * CloudSamplingTools::subsampleCloudWithOctree (GenericIndexedCloudPersist * cloud, int newNumberOfPoints, SUBSAMPLING_CELL_METHOD subsamplingMethod, GenericProgressCallback * progressCb = nullptr, DgmOctree * inputOctree = nullptr) static
Subsamples a point cloud (process based on the octree)
Same as 'subsampleCloudWithOctreeAtLevel' method, apart the fact that instead of giving a specific octree subdivision level as input parameter, one can specify an approximative number of points for the resulting cloud (algorithm will automatically determine the corresponding octree level).
Parameters
cloud point cloud to subsample
newNumberOfPoints desired number of points (approximative)
subsamplingMethod resampling method (applied to each octree cell)
progressCb the client application can get some notification of the process progress through this callback mechanism (see GenericProgressCallback)
inputOctree if the octree has been already computed, it can be used by the process (avoid recomputation)
Returns
a reference cloud corresponding to the subsampling 'selection'
Definition at line 99 of file CloudSamplingTools.cpp.
References cloudViewer::DgmOctree::build(), cloudViewer::DgmOctree::findBestLevelForAGivenCellNumber(), octree, and subsampleCloudWithOctreeAtLevel().
Referenced by define_CloudSamplingTools().
subsampleCloudWithOctreeAtLevel()
ReferenceCloud * CloudSamplingTools::subsampleCloudWithOctreeAtLevel (GenericIndexedCloudPersist * cloud, unsigned char octreeLevel, SUBSAMPLING_CELL_METHOD subsamplingMethod, GenericProgressCallback * progressCb = nullptr, DgmOctree * inputOctree = nullptr) static
Subsamples a point cloud (process based on the octree)
A subsampling algorithm is applied inside each cell of the octree. The different subsampling methods are represented as an enumerator (see SUBSAMPLING_CELL_METHOD) and consist in simple processes such as choosing a random point, or the one closest to the cell center.
Parameters
cloud point cloud to subsample
octreeLevel octree level at which to perform the subsampling process
subsamplingMethod subsampling method (applied to each octree cell)
progressCb the client application can get some notification of the process progress through this callback mechanism (see GenericProgressCallback)
inputOctree if the octree has been already computed, it can be used by the process (avoid recomputation)
Returns
a reference cloud corresponding to the subsampling 'selection'
Definition at line 126 of file CloudSamplingTools.cpp.
References cloudViewer::DgmOctree::build(), cloudViewer::DgmOctree::executeFunctionForAllCellsAtLevel(), cloudViewer::DgmOctree::getCellNumber(), octree, octreeLevel, cloudViewer::ReferenceCloud::reserve(), and subsampleCellAtLevel().
Referenced by define_CloudSamplingTools(), ccSubsamplingDlg::getSampledCloud(), ccAlignDlg::getSampledData(), ccAlignDlg::getSampledModel(), CommandSubsample::process(), and subsampleCloudWithOctree().
UniformDownSample()
ReferenceCloud * CloudSamplingTools::UniformDownSample (GenericIndexedCloudPersist * cloud, unsigned every_k_points) static
Definition at line 171 of file CloudSamplingTools.cpp.
References cloudViewer::ReferenceCloud::addPointIndex(), cloudViewer::ReferenceCloud::reserve(), cloudViewer::ReferenceCloud::resize(), and cloudViewer::GenericCloud::size().
The documentation for this class was generated from the following files:
/root/ACloudViewer/core/include/CloudSamplingTools.h
/root/ACloudViewer/core/src/CloudSamplingTools.cpp