ACloudViewer: TemplateAlignmentDialog Class Reference
TemplateAlignmentDialog Class Reference
CANUPO plugin's training dialog.
#include <TemplateAlignmentDialog.h>
Public Member Functions
TemplateAlignmentDialog (ecvMainAppInterface *app)
Default constructor.
ccPointCloud * getTemplate1Cloud ()
Get template #1 point cloud.
ccPointCloud * getTemplate2Cloud ()
Get template #2 point cloud.
ccPointCloud * getEvaluationCloud ()
Get evaluation point cloud.
void loadParamsFromPersistentSettings ()
Loads parameters from persistent settings.
void saveParamsToPersistentSettings ()
Saves parameters to persistent settings.
bool getScales (std::vector< float > &scales) const
Returns input scales.
int getMaxThreadCount () const
Returns the max number of threads to use.
int getMaxIterations () const
Returns the Maximum Iterations.
float getVoxelGridLeafSize () const
float getNormalRadius () const
Returns the Normal Radius.
float getFeatureRadius () const
Returns the Feature Radius.
float getMinSampleDistance () const
Returns the Minimum Sample Distance.
float getMaxCorrespondenceDistance () const
Returns the Maximum Correspondence Distance.
void refreshCloudComboBox ()
Protected Slots
void onCloudChanged (int)
Protected Member Functions
bool validParameters () const
QString getEntityName (ccHObject *obj)
ccPointCloud * getCloudFromCombo (QComboBox *comboBox, ccHObject *dbRoot)
Protected Attributes
ecvMainAppInterface * m_app
Gives access to the application (data-base, UI, etc.)
Detailed Description
CANUPO plugin's training dialog.
Definition at line 20 of file TemplateAlignmentDialog.h.
Constructor & Destructor Documentation
TemplateAlignmentDialog()
TemplateAlignmentDialog::TemplateAlignmentDialog (ecvMainAppInterface * app)
Default constructor.
Definition at line 28 of file TemplateAlignmentDialog.cpp.
References loadParamsFromPersistentSettings(), and onCloudChanged().
Member Function Documentation
getCloudFromCombo()
ccPointCloud * TemplateAlignmentDialog::getCloudFromCombo (QComboBox * comboBox, ccHObject * dbRoot) protected
Definition at line 278 of file TemplateAlignmentDialog.cpp.
References ccHObject::find(), ccObject::isA(), and CV_TYPES::POINT_CLOUD.
Referenced by getEvaluationCloud(), getTemplate1Cloud(), and getTemplate2Cloud().
getEntityName()
QString TemplateAlignmentDialog::getEntityName (ccHObject * obj) protected
Definition at line 265 of file TemplateAlignmentDialog.cpp.
References ccObject::getName(), ccObject::getUniqueID(), and name.
Referenced by refreshCloudComboBox().
getEvaluationCloud()
ccPointCloud * TemplateAlignmentDialog::getEvaluationCloud ()
Get evaluation point cloud.
Definition at line 204 of file TemplateAlignmentDialog.cpp.
References getCloudFromCombo(), and m_app.
Referenced by TemplateAlignment::getParametersFromDialog().
getFeatureRadius()
float TemplateAlignmentDialog::getFeatureRadius () const
Returns the Feature Radius.
Definition at line 117 of file TemplateAlignmentDialog.cpp.
Referenced by TemplateAlignment::getParametersFromDialog().
getMaxCorrespondenceDistance()
float TemplateAlignmentDialog::getMaxCorrespondenceDistance () const
Returns the Maximum Correspondence Distance.
Definition at line 125 of file TemplateAlignmentDialog.cpp.
Referenced by TemplateAlignment::getParametersFromDialog().
getMaxIterations()
int TemplateAlignmentDialog::getMaxIterations () const
Returns the Maximum Iterations.
Definition at line 130 of file TemplateAlignmentDialog.cpp.
Referenced by TemplateAlignment::getParametersFromDialog().
getMaxThreadCount()
int TemplateAlignmentDialog::getMaxThreadCount () const
Returns the max number of threads to use.
Definition at line 109 of file TemplateAlignmentDialog.cpp.
getMinSampleDistance()
float TemplateAlignmentDialog::getMinSampleDistance () const
Returns the Minimum Sample Distance.
Definition at line 121 of file TemplateAlignmentDialog.cpp.
Referenced by TemplateAlignment::getParametersFromDialog().
getNormalRadius()
float TemplateAlignmentDialog::getNormalRadius () const
Returns the Normal Radius.
Definition at line 113 of file TemplateAlignmentDialog.cpp.
Referenced by TemplateAlignment::getParametersFromDialog().
getScales()
bool TemplateAlignmentDialog::getScales (std::vector< float > & scales) const
Returns input scales.
Definition at line 142 of file TemplateAlignmentDialog.cpp.
References cloudViewer::utility::floor(), and QtCompat::SkipEmptyParts.
Referenced by TemplateAlignment::getParametersFromDialog().
getTemplate1Cloud()
ccPointCloud * TemplateAlignmentDialog::getTemplate1Cloud ()
Get template #1 point cloud.
Definition at line 186 of file TemplateAlignmentDialog.cpp.
References getCloudFromCombo(), and m_app.
Referenced by TemplateAlignment::compute(), and TemplateAlignment::getParametersFromDialog().
getTemplate2Cloud()
ccPointCloud * TemplateAlignmentDialog::getTemplate2Cloud ()
Get template #2 point cloud.
Definition at line 195 of file TemplateAlignmentDialog.cpp.
References getCloudFromCombo(), and m_app.
Referenced by TemplateAlignment::compute(), and TemplateAlignment::getParametersFromDialog().
getVoxelGridLeafSize()
float TemplateAlignmentDialog::getVoxelGridLeafSize () const
Definition at line 134 of file TemplateAlignmentDialog.cpp.
Referenced by TemplateAlignment::getParametersFromDialog().
loadParamsFromPersistentSettings()
void TemplateAlignmentDialog::loadParamsFromPersistentSettings ()
Loads parameters from persistent settings.
Definition at line 209 of file TemplateAlignmentDialog.cpp.
Referenced by TemplateAlignmentDialog().
onCloudChanged
void TemplateAlignmentDialog::onCloudChanged (int dummy) protected slot
Definition at line 182 of file TemplateAlignmentDialog.cpp.
References validParameters().
Referenced by TemplateAlignmentDialog().
refreshCloudComboBox()
void TemplateAlignmentDialog::refreshCloudComboBox ()
Definition at line 49 of file TemplateAlignmentDialog.cpp.
References getEntityName(), m_app, name, and CV_TYPES::POINT_CLOUD.
Referenced by TemplateAlignment::openInputDialog().
saveParamsToPersistentSettings()
void TemplateAlignmentDialog::saveParamsToPersistentSettings ()
Saves parameters to persistent settings.
Definition at line 248 of file TemplateAlignmentDialog.cpp.
Referenced by TemplateAlignment::openInputDialog().
validParameters()
bool TemplateAlignmentDialog::validParameters () const protected
Definition at line 88 of file TemplateAlignmentDialog.cpp.
Referenced by onCloudChanged().
Member Data Documentation
m_app
ecvMainAppInterface* TemplateAlignmentDialog::m_app protected
Gives access to the application (data-base, UI, etc.)
Definition at line 66 of file TemplateAlignmentDialog.h.
Referenced by getEvaluationCloud(), getTemplate1Cloud(), getTemplate2Cloud(), and refreshCloudComboBox().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Recognitions/dialogs/TemplateAlignmentDialog.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Recognitions/dialogs/TemplateAlignmentDialog.cpp