ACloudViewer: PlyValueVertex< Real > Class Template Reference
PlyValueVertex< Real > Class Template Reference
#include <Ply.h>
Public Types
typedef PlyValueVertex Wrapper
Public Member Functions
PlyValueVertex (void)
PlyValueVertex (Point3D< Real > p, Real v)
PlyValueVertex operator+ (PlyValueVertex p) const
PlyValueVertex operator- (PlyValueVertex p) const
template<class _Real >
PlyValueVertex operator* (_Real s) const
template<class _Real >
PlyValueVertex operator/ (_Real s) const
PlyValueVertex & operator+= (PlyValueVertex p)
PlyValueVertex & operator-= (PlyValueVertex p)
template<class _Real >
PlyValueVertex & operator*= (_Real s)
template<class _Real >
PlyValueVertex & operator/= (_Real s)
Public Attributes
Point3D< Real > point
Real value
Static Public Attributes
static const int ReadComponents =4
static const int WriteComponents =4
static PlyProperty ReadProperties []
static PlyProperty WriteProperties []
Detailed Description
template<class Real>
class PlyValueVertex< Real >
Definition at line 288 of file Ply.h.
Member Typedef Documentation
Wrapper
template<class Real > typedef PlyValueVertex PlyValueVertex< Real >::Wrapper
Definition at line 291 of file Ply.h.
Constructor & Destructor Documentation
PlyValueVertex() [1/2]
template<class Real > PlyValueVertex< Real >::PlyValueVertex (void) inline
Definition at line 301 of file Ply.h.
Referenced by PlyValueVertex< Real >::operator*(), PlyValueVertex< Real >::operator+(), PlyValueVertex< Real >::operator-(), and PlyValueVertex< Real >::operator/().
PlyValueVertex() [2/2]
template<class Real > PlyValueVertex< Real >::PlyValueVertex (Point3D< Real > p, Real v) inline
Definition at line 302 of file Ply.h.
Member Function Documentation
operator*()
template<class Real > template<class _Real > PlyValueVertex PlyValueVertex< Real >::operator* (_Real s) const inline
Definition at line 305 of file Ply.h.
References PlyValueVertex< Real >::PlyValueVertex(), and PlyValueVertex< Real >::value.
operator*=()
template<class Real > template<class _Real > PlyValueVertex& PlyValueVertex< Real >::operator*= (_Real s) inline
Definition at line 309 of file Ply.h.
References PlyValueVertex< Real >::value.
operator+()
template<class Real > PlyValueVertex PlyValueVertex< Real >::operator+ (PlyValueVertex< Real > p) const inline
Definition at line 303 of file Ply.h.
References PlyValueVertex< Real >::PlyValueVertex(), PlyValueVertex< Real >::point, and PlyValueVertex< Real >::value.
operator+=()
template<class Real > PlyValueVertex& PlyValueVertex< Real >::operator+= (PlyValueVertex< Real > p) inline
Definition at line 307 of file Ply.h.
References PlyValueVertex< Real >::point, and PlyValueVertex< Real >::value.
operator-()
template<class Real > PlyValueVertex PlyValueVertex< Real >::operator- (PlyValueVertex< Real > p) const inline
Definition at line 304 of file Ply.h.
References PlyValueVertex< Real >::PlyValueVertex(), and PlyValueVertex< Real >::value.
operator-=()
template<class Real > PlyValueVertex& PlyValueVertex< Real >::operator-= (PlyValueVertex< Real > p) inline
Definition at line 308 of file Ply.h.
References PlyValueVertex< Real >::point, and PlyValueVertex< Real >::value.
operator/()
template<class Real > template<class _Real > PlyValueVertex PlyValueVertex< Real >::operator/ (_Real s) const inline
Definition at line 306 of file Ply.h.
References PlyValueVertex< Real >::PlyValueVertex(), and PlyValueVertex< Real >::value.
operator/=()
template<class Real > template<class _Real > PlyValueVertex& PlyValueVertex< Real >::operator/= (_Real s) inline
Definition at line 310 of file Ply.h.
References PlyValueVertex< Real >::value.
Member Data Documentation
point
template<class Real > Point3D<Real> PlyValueVertex< Real >::point
Definition at line 298 of file Ply.h.
Referenced by operator*(), PlyValueVertex< Real >::operator+(), PlyValueVertex< Real >::operator+=(), and PlyValueVertex< Real >::operator-=().
ReadComponents
template<class Real > const int PlyValueVertex< Real >::ReadComponents =4 static
Definition at line 293 of file Ply.h.
ReadProperties
template<class Real > PlyProperty PlyValueVertex< Real >::ReadProperties static
Initial value:
=
{
    {  strdup ( "x"     ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyValueVertex , point.coords[0] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "y"     ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyValueVertex , point.coords[1] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "z"     ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyValueVertex , point.coords[2] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "value" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyValueVertex , value           ) ) , 0 , 0 , 0 , 0 }
}
Definition at line 295 of file Ply.h.
value
template<class Real > Real PlyValueVertex< Real >::value
Definition at line 299 of file Ply.h.
Referenced by PlyValueVertex< Real >::operator*(), operator*(), PlyValueVertex< Real >::operator*=(), PlyValueVertex< Real >::operator+(), PlyValueVertex< Real >::operator+=(), PlyValueVertex< Real >::operator-(), PlyValueVertex< Real >::operator-=(), PlyValueVertex< Real >::operator/(), and PlyValueVertex< Real >::operator/=().
WriteComponents
template<class Real > const int PlyValueVertex< Real >::WriteComponents =4 static
Definition at line 294 of file Ply.h.
WriteProperties
template<class Real > PlyProperty PlyValueVertex< Real >::WriteProperties static
Initial value:
=
{
    {  strdup ( "x"     ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyValueVertex , point.coords[0] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "y"     ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyValueVertex , point.coords[1] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "z"     ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyValueVertex , point.coords[2] ) ) , 0 , 0 , 0 , 0 },
    {  strdup ( "value" ) , PLYType< Real >() , PLYType< Real >() , int( offsetof( PlyValueVertex , value           ) ) , 0 , 0 , 0 , 0 }
}
Definition at line 296 of file Ply.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/Ply.h