ACloudViewer: qPCL Class Reference
qPCL Class Reference
PCL bridge plugin.
#include <qPCLBase.h>
Public Slots
void handleNewEntity (ccHObject *)
Handles new entity.
void handleEntityChange (ccHObject *)
Handles entity (visual) modification.
void handleErrorMessage (QString)
Handles new error message.
Public Member Functions
qPCL (QObject *parent=nullptr)
Default constructor.
virtual ~qPCL () override=default
Destructor.
virtual void onNewSelection (const ccHObject::Container &selectedEntities) override
virtual QVector< QList< QAction * > > getActions () override
Get a list of actions for this plugin.
virtual QVector< QString > getModuleNames () override
virtual void stop () override
Stops the plugin.
Public Member Functions inherited from ccPclPluginInterface
ccPclPluginInterface (const QString &resourcePath=QString())
Default constructor.
virtual ~ccPclPluginInterface ()=default
Destructor.
virtual CC_PLUGIN_TYPE getType () const override
Returns plugin type (standard or OpenGL filter)
virtual void setMainAppInterface (ecvMainAppInterface *app)
Sets application entry point.
virtual ecvMainAppInterface * getMainAppInterface ()
A callback pointer to the main app interface for use by plugins.
virtual void dispToConsole (QString message, ecvMainAppInterface::ConsoleMessageLevel level=ecvMainAppInterface::STD_CONSOLE_MESSAGE)
Shortcut to ecvMainAppInterface::dispToConsole.
Public Member Functions inherited from ccDefaultPluginInterface
virtual ~ccDefaultPluginInterface ()
virtual bool isCore () const override
Is this plugin a core plugin?
virtual QString getName () const override
Returns (short) name (for menu entry, etc.)
virtual QString getDescription () const override
Returns long name/description (for tooltip, etc.)
virtual QIcon getIcon () const override
Returns icon.
virtual ReferenceList getReferences () const override
virtual ContactList getAuthors () const override
virtual ContactList getMaintainers () const override
Public Member Functions inherited from ccPluginInterface
virtual ~ccPluginInterface ()=default
Virtual destructor.
virtual bool start ()
Starts the plugin.
virtual ccExternalFactory * getCustomObjectsFactory () const
Returns the plugin's custom object factory (if any)
virtual void registerCommands (ccCommandLineInterface *cmd)
Optional: registers commands (for the command line mode)
Protected Member Functions
int addPclModule (BasePclModule *module, QList< QAction * > &actions)
Adds a pcl module.
Protected Member Functions inherited from ccDefaultPluginInterface
ccDefaultPluginInterface (const QString &resourcePath=QString())
Protected Attributes
std::vector< BasePclModule * > m_modules
Loaded modules.
QVector< QString > m_moduleNames
Protected Attributes inherited from ccPclPluginInterface
ecvMainAppInterface * m_app
Main application interface.
Additional Inherited Members
Public Types inherited from ccPluginInterface
typedef QList< Contact > ContactList
using ReferenceList = QList< Reference >
Detailed Description
PCL bridge plugin.
Definition at line 19 of file qPCLBase.h.
Constructor & Destructor Documentation
qPCL()
qPCL::qPCL (QObject * parent = nullptr)
Default constructor.
Definition at line 48 of file qPCLBase.cpp.
~qPCL()
virtual qPCL::~qPCL () override virtual default
Destructor.
Member Function Documentation
addPclModule()
int qPCL::addPclModule (BasePclModule * module, QList< QAction * > & actions) protected
Adds a pcl module.
Definition at line 133 of file qPCLBase.cpp.
References BasePclModule::entityHasChanged(), BasePclModule::getAction(), handleEntityChange(), handleErrorMessage(), handleNewEntity(), ccPclPluginInterface::m_app, m_modules, BasePclModule::newEntity(), BasePclModule::newErrorMessage(), and BasePclModule::setMainAppInterface().
Referenced by getActions().
getActions()
QVector< QList< QAction * > > qPCL::getActions () override virtual
Get a list of actions for this plugin.
Implements ccPclPluginInterface.
Definition at line 75 of file qPCLBase.cpp.
References addPclModule(), m_moduleNames, and m_modules.
getModuleNames()
QVector< QString > qPCL::getModuleNames () override virtual
Implements ccPclPluginInterface.
Definition at line 131 of file qPCLBase.cpp.
References m_moduleNames.
handleEntityChange
void qPCL::handleEntityChange (ccHObject * entity) slot
Handles entity (visual) modification.
Definition at line 64 of file qPCLBase.cpp.
References ccPclPluginInterface::m_app, ecvMainAppInterface::refreshSelected(), and ecvMainAppInterface::updateUI().
Referenced by addPclModule().
handleErrorMessage
void qPCL::handleErrorMessage (QString message) slot
Handles new error message.
Definition at line 70 of file qPCLBase.cpp.
References ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, and ccPclPluginInterface::m_app.
Referenced by addPclModule().
handleNewEntity
void qPCL::handleNewEntity (ccHObject * entity) slot
Handles new entity.
Definition at line 58 of file qPCLBase.cpp.
References ecvMainAppInterface::addToDB(), ccPclPluginInterface::m_app, and ecvMainAppInterface::zoomOnEntities().
Referenced by addPclModule().
onNewSelection()
void qPCL::onNewSelection (const ccHObject::Container & selectedEntities) override virtual
This method is called by the main application whenever the entity selection changes Does nothing by default. Should be re-implemented by the plugin if necessary.
Parameters
selectedEntities currently selected entities
Reimplemented from ccPclPluginInterface.
Definition at line 158 of file qPCLBase.cpp.
References m_modules.
stop()
void qPCL::stop () override virtual
Stops the plugin.
Should be reimplemented if necessary. Used to stop a plugin previously started (see ccPluginInterface::start).
Reimplemented from ccPluginInterface.
Definition at line 51 of file qPCLBase.cpp.
References m_modules.
Member Data Documentation
m_moduleNames
QVector<QString> qPCL::m_moduleNames protected
Definition at line 54 of file qPCLBase.h.
Referenced by getActions(), and getModuleNames().
m_modules
std::vector<BasePclModule*> qPCL::m_modules protected
Loaded modules.
Definition at line 53 of file qPCLBase.h.
Referenced by addPclModule(), getActions(), onNewSelection(), and stop().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/include/qPCLBase.h
/root/ACloudViewer/plugins/core/Standard/qPCL/src/qPCLBase.cpp