ACloudViewer: ListWidgetConsole Class Reference
ListWidgetConsole Class Reference
Writes messages to the QListWidget given.
#include <Consoles.h>
Public Member Functions
ListWidgetConsole (QListWidget *view, const Qt::GlobalColor color)
ListWidgetConsole (QListWidget *view, const QColor &color)
ListWidgetConsole (QListWidget *view)
void write (const char *messagePart)
bool isatty () const
void flush () const
Detailed Description
Writes messages to the QListWidget given.
Definition at line 120 of file Consoles.h.
Constructor & Destructor Documentation
ListWidgetConsole() [1/3]
ListWidgetConsole::ListWidgetConsole (QListWidget * view, const Qt::GlobalColor color) inline
Definition at line 123 of file Consoles.h.
ListWidgetConsole() [2/3]
ListWidgetConsole::ListWidgetConsole (QListWidget * view, const QColor & color) inline
Definition at line 126 of file Consoles.h.
ListWidgetConsole() [3/3]
ListWidgetConsole::ListWidgetConsole (QListWidget * view) inline explicit
Definition at line 127 of file Consoles.h.
Member Function Documentation
flush()
void ListWidgetConsole::flush () const inline
Definition at line 145 of file Consoles.h.
References ConsoleWrapper::flush().
Referenced by PYBIND11_EMBEDDED_MODULE().
isatty()
bool ListWidgetConsole::isatty () const inline
Definition at line 140 of file Consoles.h.
Referenced by PYBIND11_EMBEDDED_MODULE().
write()
void ListWidgetConsole::write (const char * messagePart) inline
Definition at line 129 of file Consoles.h.
References CVLog::Warning(), and ConsoleWrapper::write().
Referenced by PYBIND11_EMBEDDED_MODULE().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/Runtime/Consoles.h