ACloudViewer: ccScalarField::Range Class Reference
ccScalarField::Range Class Reference
Scalar field range structure.
#include <ecvScalarField.h>
Public Member Functions
Range ()
Default constructor.
ScalarType min () const
ScalarType start () const
ScalarType stop () const
ScalarType max () const
ScalarType range () const
ScalarType maxRange () const
void setBounds (ScalarType minVal, ScalarType maxVal, bool resetStartStop=true)
void setStart (ScalarType value)
void setStop (ScalarType value)
ScalarType inbound (ScalarType val) const
Returns the nearest inbound value.
bool isInbound (ScalarType val) const
Returns whether a value is inbound or not.
bool isInRange (ScalarType val) const
Returns whether a value is inside range or not.
Protected Member Functions
void updateRange ()
Updates actual range.
Protected Attributes
ScalarType m_min
ScalarType m_start
ScalarType m_stop
ScalarType m_max
ScalarType m_range
Detailed Description
Scalar field range structure.
Definition at line 36 of file ecvScalarField.h.
Constructor & Destructor Documentation
Range()
ccScalarField::Range::Range () inline
Default constructor.
Definition at line 39 of file ecvScalarField.h.
Member Function Documentation
inbound()
ScalarType ccScalarField::Range::inbound (ScalarType val) const inline
Returns the nearest inbound value.
Definition at line 78 of file ecvScalarField.h.
Referenced by define_ccScalarField().
isInbound()
bool ccScalarField::Range::isInbound (ScalarType val) const inline
Returns whether a value is inbound or not.
Definition at line 82 of file ecvScalarField.h.
Referenced by define_ccScalarField().
isInRange()
bool ccScalarField::Range::isInRange (ScalarType val) const inline
Returns whether a value is inside range or not.
Definition at line 86 of file ecvScalarField.h.
Referenced by define_ccScalarField(), ccSNECloud::drawMeOnly(), ccScalarField::normalize(), and PclTools::UpdateScalarBar().
max()
ScalarType ccScalarField::Range::max () const inline
Definition at line 45 of file ecvScalarField.h.
Referenced by ccRasterizeTool::activeLayerChanged(), define_ccScalarField(), sfEditDlg::fillDialogWith(), GetSymmetricalNormalizedValue(), ccScalarField::mayHaveHiddenValues(), ccHistogramWindow::refresh(), PclTools::UpdateScalarBar(), and ccColorFromScalarDlg::~ccColorFromScalarDlg().
maxRange()
ScalarType ccScalarField::Range::maxRange () const inline
Definition at line 47 of file ecvScalarField.h.
Referenced by ccScalarField::computeMinAndMax(), define_ccScalarField(), and sfEditDlg::fillDialogWith().
min()
ScalarType ccScalarField::Range::min () const inline
Definition at line 42 of file ecvScalarField.h.
Referenced by ccRasterizeTool::activeLayerChanged(), ccScalarField::computeMinAndMax(), define_ccScalarField(), sfEditDlg::fillDialogWith(), ccScalarField::mayHaveHiddenValues(), ccHistogramWindow::refresh(), PclTools::UpdateScalarBar(), and ccColorFromScalarDlg::~ccColorFromScalarDlg().
range()
ScalarType ccScalarField::Range::range () const inline
Definition at line 46 of file ecvScalarField.h.
Referenced by ccRasterizeTool::activeLayerChanged(), define_ccScalarField(), GetNormalizedValue(), and ccScalarField::normalize().
setBounds()
void ccScalarField::Range::setBounds (ScalarType minVal, ScalarType maxVal, bool resetStartStop = true) inline
Definition at line 50 of file ecvScalarField.h.
Referenced by ccScalarField::computeMinAndMax(), define_ccScalarField(), and ccScalarField::updateSaturationBounds().
setStart()
void ccScalarField::Range::setStart (ScalarType value) inline
Definition at line 66 of file ecvScalarField.h.
Referenced by define_ccScalarField(), ccScalarField::setMinDisplayed(), and ccScalarField::setSaturationStart().
setStop()
void ccScalarField::Range::setStop (ScalarType value) inline
Definition at line 71 of file ecvScalarField.h.
Referenced by define_ccScalarField(), ccScalarField::setMaxDisplayed(), and ccScalarField::setSaturationStop().
start()
ScalarType ccScalarField::Range::start () const inline
Definition at line 43 of file ecvScalarField.h.
Referenced by define_ccScalarField(), sfEditDlg::fillDialogWith(), ccHistogramWindow::fromSF(), GetNormalizedValue(), GetSymmetricalNormalizedValue(), ccScalarField::importParametersFrom(), ccScalarField::mayHaveHiddenValues(), ccScalarField::normalize(), ccHistogramWindow::refresh(), ecvFilterByLabelDlg::setInputEntity(), and PclTools::UpdateScalarBar().
stop()
ScalarType ccScalarField::Range::stop () const inline
Definition at line 44 of file ecvScalarField.h.
Referenced by define_ccScalarField(), sfEditDlg::fillDialogWith(), ccHistogramWindow::fromSF(), ccScalarField::importParametersFrom(), ccScalarField::mayHaveHiddenValues(), ccScalarField::normalize(), ccHistogramWindow::refresh(), ecvFilterByLabelDlg::setInputEntity(), and PclTools::UpdateScalarBar().
updateRange()
void ccScalarField::Range::updateRange () inline protected
Updates actual range.
Definition at line 92 of file ecvScalarField.h.
References ZERO_TOLERANCE_SCALAR.
Member Data Documentation
m_max
ScalarType ccScalarField::Range::m_max protected
Minimum value
Definition at line 99 of file ecvScalarField.h.
m_min
ScalarType ccScalarField::Range::m_min protected
Minimum value
Definition at line 96 of file ecvScalarField.h.
m_range
ScalarType ccScalarField::Range::m_range protected
Actual range: start-stop (but can't be ZERO!)
Definition at line 101 of file ecvScalarField.h.
m_start
ScalarType ccScalarField::Range::m_start protected
Current start value (in [min,max])
Definition at line 97 of file ecvScalarField.h.
m_stop
ScalarType ccScalarField::Range::m_stop protected
Current stop value (in [min,max])
Definition at line 98 of file ecvScalarField.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvScalarField.h