ACloudViewer: vtkPVPostFilterExecutive Class Reference
vtkPVPostFilterExecutive Class Reference
#include <vtkPVPostFilterExecutive.h>
Public Member Functions
vtkTypeMacro (vtkPVPostFilterExecutive, vtkPVCompositeDataPipeline)
void PrintSelf (ostream &os, vtkIndent indent) override
vtkDataObject * GetCompositeInputData (int port, int index, vtkInformationVector **inInfoVec)
vtkInformation * GetPostArrayToProcessInformation (int idx)
void SetPostArrayToProcessInformation (int idx, vtkInformation *inInfo)
Public Member Functions inherited from vtkPVCompositeDataPipeline
vtkTypeMacro (vtkPVCompositeDataPipeline, vtkCompositeDataPipeline)
void PrintSelf (ostream &os, vtkIndent indent) override
Static Public Member Functions
static vtkPVPostFilterExecutive * New ()
static vtkInformationInformationVectorKey * POST_ARRAYS_TO_PROCESS ()
static vtkInformationStringVectorKey * POST_ARRAY_COMPONENT_KEY ()
Static Public Member Functions inherited from vtkPVCompositeDataPipeline
static vtkPVCompositeDataPipeline * New ()
Protected Member Functions
vtkPVPostFilterExecutive ()
~vtkPVPostFilterExecutive () override
int NeedToExecuteData (int outputPort, vtkInformationVector **inInfoVec, vtkInformationVector *outInfoVec) override
bool MatchingPropertyInformation (vtkInformation *inputArrayInfo, vtkInformation *postArrayInfo)
Protected Member Functions inherited from vtkPVCompositeDataPipeline
vtkPVCompositeDataPipeline ()
~vtkPVCompositeDataPipeline () override
void CopyDefaultInformation (vtkInformation *request, int direction, vtkInformationVector **inInfoVec, vtkInformationVector *outInfoVec) override
void ResetPipelineInformation (int port, vtkInformation *) override
Detailed Description
Definition at line 16 of file vtkPVPostFilterExecutive.h.
Constructor & Destructor Documentation
vtkPVPostFilterExecutive()
vtkPVPostFilterExecutive::vtkPVPostFilterExecutive () protected
Definition at line 32 of file vtkPVPostFilterExecutive.cxx.
~vtkPVPostFilterExecutive()
vtkPVPostFilterExecutive::~vtkPVPostFilterExecutive () override protected
Definition at line 37 of file vtkPVPostFilterExecutive.cxx.
Member Function Documentation
GetCompositeInputData()
vtkDataObject* vtkPVPostFilterExecutive::GetCompositeInputData (int port, int index, vtkInformationVector ** inInfoVec)
Returns the data object stored with the DATA_OBJECT() in the input port
GetPostArrayToProcessInformation()
vtkInformation * vtkPVPostFilterExecutive::GetPostArrayToProcessInformation (int idx)
Definition at line 53 of file vtkPVPostFilterExecutive.cxx.
References POST_ARRAYS_TO_PROCESS().
Referenced by SetPostArrayToProcessInformation().
MatchingPropertyInformation()
bool vtkPVPostFilterExecutive::MatchingPropertyInformation (vtkInformation * inputArrayInfo, vtkInformation * postArrayInfo) protected
Definition at line 86 of file vtkPVPostFilterExecutive.cxx.
Referenced by SetPostArrayToProcessInformation().
NeedToExecuteData()
int vtkPVPostFilterExecutive::NeedToExecuteData (int outputPort, vtkInformationVector ** inInfoVec, vtkInformationVector * outInfoVec) override protected
Definition at line 42 of file vtkPVPostFilterExecutive.cxx.
References POST_ARRAYS_TO_PROCESS().
New()
static vtkPVPostFilterExecutive* vtkPVPostFilterExecutive::New () static
Referenced by vtkPVPostFilter::CreateDefaultExecutive(), and vtkPVPostFilter::vtkPVPostFilter().
POST_ARRAY_COMPONENT_KEY()
static vtkInformationStringVectorKey* vtkPVPostFilterExecutive::POST_ARRAY_COMPONENT_KEY () static
Referenced by SetPostArrayToProcessInformation().
POST_ARRAYS_TO_PROCESS()
static vtkInformationInformationVectorKey* vtkPVPostFilterExecutive::POST_ARRAYS_TO_PROCESS () static
Referenced by vtkPVPostFilter::DoAnyNeededConversions(), GetPostArrayToProcessInformation(), NeedToExecuteData(), and vtkPVPostFilter::RequestData().
PrintSelf()
void vtkPVPostFilterExecutive::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 102 of file vtkPVPostFilterExecutive.cxx.
SetPostArrayToProcessInformation()
void vtkPVPostFilterExecutive::SetPostArrayToProcessInformation (int idx, vtkInformation * inInfo)
Definition at line 75 of file vtkPVPostFilterExecutive.cxx.
References GetPostArrayToProcessInformation(), MatchingPropertyInformation(), and POST_ARRAY_COMPONENT_KEY().
Referenced by vtkPVCompositeDataPipeline::CopyDefaultInformation().
vtkTypeMacro()
vtkPVPostFilterExecutive::vtkTypeMacro (vtkPVPostFilterExecutive , vtkPVCompositeDataPipeline)
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkPVPostFilterExecutive.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkPVPostFilterExecutive.cxx