ACloudViewer: e57::WriterImpl Class Reference
e57::WriterImpl Class Reference
most of the functions follows Writer
#include <WriterImpl.h>
Public Member Functions
WriterImpl (const ustring &filePath, const ustring &coordinateMetaData)
~WriterImpl ()
bool IsOpen () const
bool Close ()
int64_t NewImage2D (Image2D &image2DHeader)
int64_t WriteImage2DData (int64_t imageIndex, Image2DType imageType, Image2DProjection imageProjection, void *pBuffer, int64_t start, int64_t count)
int64_t NewData3D (Data3D &data3DHeader)
template<typename COORDTYPE >
CompressedVectorWriter SetUpData3DPointsData (int64_t dataIndex, size_t pointCount, const Data3DPointsData_t< COORDTYPE > &buffers)
bool WriteData3DGroupsData (int64_t dataIndex, int64_t groupCount, int64_t *idElementValue, int64_t *startPointIndex, int64_t *pointCount)
StructureNode GetRawE57Root ()
VectorNode GetRawData3D ()
VectorNode GetRawImages2D ()
ImageFile GetRawIMF ()
Detailed Description
most of the functions follows Writer
Definition at line 36 of file WriterImpl.h.
Constructor & Destructor Documentation
WriterImpl()
e57::WriterImpl::WriterImpl (const ustring & filePath, const ustring & coordinateMetaData)
Definition at line 36 of file WriterImpl.cpp.
References e57::E57_V1_0_URI, e57::ImageFile::extensionsAdd(), e57::generateRandomGUID(), e57::Utilities::getVersions(), and e57::StructureNode::set().
~WriterImpl()
e57::WriterImpl::~WriterImpl ()
Definition at line 81 of file WriterImpl.cpp.
References Close(), and IsOpen().
Member Function Documentation
Close()
bool e57::WriterImpl::Close ()
Definition at line 94 of file WriterImpl.cpp.
References e57::ImageFile::close(), and IsOpen().
Referenced by ~WriterImpl().
GetRawData3D()
VectorNode e57::WriterImpl::GetRawData3D ()
Definition at line 110 of file WriterImpl.cpp.
GetRawE57Root()
StructureNode e57::WriterImpl::GetRawE57Root ()
Definition at line 105 of file WriterImpl.cpp.
GetRawImages2D()
VectorNode e57::WriterImpl::GetRawImages2D ()
Definition at line 115 of file WriterImpl.cpp.
GetRawIMF()
ImageFile e57::WriterImpl::GetRawIMF ()
Definition at line 120 of file WriterImpl.cpp.
IsOpen()
bool e57::WriterImpl::IsOpen () const
Definition at line 89 of file WriterImpl.cpp.
References e57::ImageFile::isOpen().
Referenced by Close(), and ~WriterImpl().
NewData3D()
int64_t e57::WriterImpl::NewData3D (Data3D & data3DHeader)
Definition at line 416 of file WriterImpl.cpp.
References e57::VectorNode::append(), e57::Data3D::atmosphericPressure, e57::VectorNode::childCount(), e57::Data3D::description, e57::generateRandomGUID(), e57::StructureNode::get(), e57::Data3D::guid, e57::Data3D::indexBounds, e57::Data3D::name, e57::Data3D::originalGuids, e57::Data3D::relativeHumidity, e57::Data3D::sensorFirmwareVersion, e57::Data3D::sensorHardwareVersion, e57::Data3D::sensorModel, e57::Data3D::sensorSerialNumber, e57::Data3D::sensorSoftwareVersion, e57::Data3D::sensorVendor, e57::StructureNode::set(), and e57::Data3D::temperature.
NewImage2D()
int64_t e57::WriterImpl::NewImage2D (Image2D & image2DHeader)
Definition at line 125 of file WriterImpl.cpp.
References e57::Image2D::acquisitionDateTime, e57::VectorNode::append(), e57::Image2D::associatedData3DGuid, e57::VectorNode::childCount(), e57::Image2D::cylindricalRepresentation, e57::DateTime::dateTimeValue, e57::Image2D::description, e57::PinholeRepresentation::focalLength, e57::generateRandomGUID(), e57::Image2D::guid, image, e57::VisualReferenceRepresentation::imageHeight, e57::PinholeRepresentation::imageHeight, e57::SphericalRepresentation::imageHeight, e57::CylindricalRepresentation::imageHeight, e57::VisualReferenceRepresentation::imageMaskSize, e57::PinholeRepresentation::imageMaskSize, e57::SphericalRepresentation::imageMaskSize, e57::CylindricalRepresentation::imageMaskSize, e57::VisualReferenceRepresentation::imageWidth, e57::PinholeRepresentation::imageWidth, e57::SphericalRepresentation::imageWidth, e57::CylindricalRepresentation::imageWidth, e57::DateTime::isAtomicClockReferenced, e57::VisualReferenceRepresentation::jpegImageSize, e57::PinholeRepresentation::jpegImageSize, e57::SphericalRepresentation::jpegImageSize, e57::CylindricalRepresentation::jpegImageSize, e57::Image2D::name, e57::Image2D::pinholeRepresentation, e57::PinholeRepresentation::pixelHeight, e57::SphericalRepresentation::pixelHeight, e57::CylindricalRepresentation::pixelHeight, e57::PinholeRepresentation::pixelWidth, e57::SphericalRepresentation::pixelWidth, e57::CylindricalRepresentation::pixelWidth, e57::VisualReferenceRepresentation::pngImageSize, e57::PinholeRepresentation::pngImageSize, e57::SphericalRepresentation::pngImageSize, e57::CylindricalRepresentation::pngImageSize, e57::Image2D::pose, e57::PinholeRepresentation::principalPointX, e57::PinholeRepresentation::principalPointY, e57::CylindricalRepresentation::principalPointY, e57::CylindricalRepresentation::radius, e57::RigidBodyTransform::rotation, e57::Image2D::sensorModel, e57::Image2D::sensorSerialNumber, e57::Image2D::sensorVendor, e57::StructureNode::set(), e57::Image2D::sphericalRepresentation, e57::RigidBodyTransform::translation, e57::Image2D::visualReferenceRepresentation, e57::Quaternion::w, e57::Translation::x, e57::Quaternion::x, e57::Translation::y, e57::Quaternion::y, e57::Translation::z, and e57::Quaternion::z.
SetUpData3DPointsData()
template<typename COORDTYPE > template CompressedVectorWriter e57::WriterImpl::SetUpData3DPointsData (int64_t dataIndex, size_t pointCount, const Data3DPointsData_t< COORDTYPE > & buffers)
Definition at line 945 of file WriterImpl.cpp.
References e57::Data3DPointsData_t< COORDTYPE >::cartesianInvalidState, e57::Data3DPointsData_t< COORDTYPE >::cartesianX, e57::Data3DPointsData_t< COORDTYPE >::cartesianY, e57::Data3DPointsData_t< COORDTYPE >::cartesianZ, e57::Data3DPointsData_t< COORDTYPE >::colorBlue, e57::Data3DPointsData_t< COORDTYPE >::colorGreen, e57::Data3DPointsData_t< COORDTYPE >::colorRed, e57::Data3DPointsData_t< COORDTYPE >::columnIndex, count, e57::StructureNode::get(), e57::Data3DPointsData_t< COORDTYPE >::intensity, e57::Data3DPointsData_t< COORDTYPE >::isColorInvalid, e57::StructureNode::isDefined(), e57::Data3DPointsData_t< COORDTYPE >::isIntensityInvalid, e57::Data3DPointsData_t< COORDTYPE >::isTimeStampInvalid, e57::Data3DPointsData_t< COORDTYPE >::normalX, e57::Data3DPointsData_t< COORDTYPE >::normalY, e57::Data3DPointsData_t< COORDTYPE >::normalZ, points, e57::Data3DPointsData_t< COORDTYPE >::returnCount, e57::Data3DPointsData_t< COORDTYPE >::returnIndex, e57::Data3DPointsData_t< COORDTYPE >::rowIndex, e57::Data3DPointsData_t< COORDTYPE >::sphericalAzimuth, e57::Data3DPointsData_t< COORDTYPE >::sphericalElevation, e57::Data3DPointsData_t< COORDTYPE >::sphericalInvalidState, e57::Data3DPointsData_t< COORDTYPE >::sphericalRange, and e57::Data3DPointsData_t< COORDTYPE >::timeStamp.
WriteData3DGroupsData()
bool e57::WriterImpl::WriteData3DGroupsData (int64_t dataIndex, int64_t groupCount, int64_t * idElementValue, int64_t * startPointIndex, int64_t * pointCount)
Definition at line 1073 of file WriterImpl.cpp.
References e57::CompressedVectorWriter::close(), e57::StructureNode::get(), e57::StructureNode::isDefined(), e57::CompressedVectorWriter::write(), and e57::CompressedVectorNode::writer().
WriteImage2DData()
int64_t e57::WriterImpl::WriteImage2DData (int64_t imageIndex, Image2DType imageType, Image2DProjection imageProjection, void * pBuffer, int64_t start, int64_t count)
Definition at line 369 of file WriterImpl.cpp.
References e57::VectorNode::childCount(), count, e57::E57_CYLINDRICAL, e57::E57_NO_PROJECTION, e57::E57_PINHOLE, e57::E57_SPHERICAL, e57::E57_VISUAL, e57::VectorNode::get(), and image.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qE57IO/extern/libE57Format/src/WriterImpl.h
/root/ACloudViewer/plugins/core/IO/qE57IO/extern/libE57Format/src/WriterImpl.cpp