ACloudViewer: QCPItemEllipse Class Reference
QCPItemEllipse Class Reference
An ellipse.
#include <qcustomplot.h>
Public Member Functions
QCPItemEllipse (QCustomPlot *parentPlot)
virtual ~QCPItemEllipse ()
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
QCPItemEllipse (QCustomPlot *parentPlot)
virtual ~QCPItemEllipse ()
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractItem
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
virtual ~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Public Attributes
QCPItemPosition *const topLeft
QCPItemPosition *const bottomRight
QCPItemAnchor *const topLeftRim
QCPItemAnchor *const top
QCPItemAnchor *const topRightRim
QCPItemAnchor *const right
QCPItemAnchor *const bottomRightRim
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeftRim
QCPItemAnchor *const left
QCPItemAnchor *const center
Protected Types
enum AnchorIndex {
aiTopLeftRim , aiTop , aiTopRightRim , aiRight ,
aiBottomRightRim , aiBottom , aiBottomLeftRim , aiLeft ,
aiCenter , aiTopLeftRim , aiTop , aiTopRightRim ,
aiRight , aiBottomRightRim , aiBottom , aiBottomLeftRim ,
aiLeft , aiCenter
}
enum AnchorIndex {
aiTopLeftRim , aiTop , aiTopRightRim , aiRight ,
aiBottomRightRim , aiBottom , aiBottomLeftRim , aiLeft ,
aiCenter , aiTopLeftRim , aiTop , aiTopRightRim ,
aiRight , aiBottomRightRim , aiBottom , aiBottomLeftRim ,
aiLeft , aiCenter
}
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPosition (int anchorId) const
QPen mainPen () const
QBrush mainBrush () const
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPen mainPen () const
QBrush mainBrush () const
Protected Member Functions inherited from QCPAbstractItem
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double rectDistance (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual void mousePressEvent (QMouseEvent *event, const QVariant &details)
virtual void mouseMoveEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseReleaseEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseDoubleClickEvent (QMouseEvent *event, const QVariant &details)
virtual void wheelEvent (QWheelEvent *event)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
Protected Attributes inherited from QCPAbstractItem
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractItem
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
void layerChanged (QCPLayer *newLayer)
Detailed Description
An ellipse.
Ellipse example. Blue dotted circles are
anchors, solid blue discs are positions."
It has two positions, topLeft and bottomRight, which define the rect the ellipse will be drawn in.
Definition at line 7546 of file qcustomplot.h.
Member Enumeration Documentation
AnchorIndex [1/2]
enum QCPItemEllipse::AnchorIndex protected
Enumerator
aiTopLeftRim
aiTop
aiTopRightRim
aiRight
aiBottomRightRim
aiBottom
aiBottomLeftRim
aiLeft
aiCenter
aiTopLeftRim
aiTop
aiTopRightRim
aiRight
aiBottomRightRim
aiBottom
aiBottomLeftRim
aiLeft
aiCenter
Definition at line 7588 of file qcustomplot.h.
AnchorIndex [2/2]
enum QCPItemEllipse::AnchorIndex protected
Enumerator
aiTopLeftRim
aiTop
aiTopRightRim
aiRight
aiBottomRightRim
aiBottom
aiBottomLeftRim
aiLeft
aiCenter
aiTopLeftRim
aiTop
aiTopRightRim
aiRight
aiBottomRightRim
aiBottom
aiBottomLeftRim
aiLeft
aiCenter
Definition at line 4227 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemEllipse() [1/2]
QCPItemEllipse::QCPItemEllipse (QCustomPlot * parentPlot) explicit
Creates an ellipse item and sets default values.
The created item is automatically registered with parentPlot. This QCustomPlot instance takes ownership of the item, so do not delete it manually but use QCustomPlot::removeItem() instead.
Creates an ellipse item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 31036 of file qcustomplot.cpp.
References ecvColor::black(), ecvColor::blue(), bottomRight, setBrush(), QCPItemPosition::setCoords(), setPen(), setSelectedBrush(), setSelectedPen(), and topLeft.
~QCPItemEllipse() [1/2]
QCPItemEllipse::~QCPItemEllipse () virtual
Definition at line 31060 of file qcustomplot.cpp.
QCPItemEllipse() [2/2]
QCPItemEllipse::QCPItemEllipse (QCustomPlot * parentPlot)
~QCPItemEllipse() [2/2]
virtual QCPItemEllipse::~QCPItemEllipse () virtual
Member Function Documentation
anchorPixelPoint()
QPointF QCPItemEllipse::anchorPixelPoint (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 23883 of file qcustomplot.cpp.
References aiBottom, aiBottomLeftRim, aiBottomRightRim, aiCenter, aiLeft, aiRight, aiTop, aiTopLeftRim, aiTopRightRim, bottomRight, QCPItemPosition::pixelPoint(), and topLeft.
anchorPixelPosition()
QPointF QCPItemEllipse::anchorPixelPosition (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 31150 of file qcustomplot.cpp.
References aiBottom, aiBottomLeftRim, aiBottomRightRim, aiCenter, aiLeft, aiRight, aiTop, aiTopLeftRim, aiTopRightRim, bottomRight, QCPItemPosition::pixelPosition(), and topLeft.
brush() [1/2]
QBrush QCPItemEllipse::brush () const inline
Definition at line 7561 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
brush() [2/2]
QBrush QCPItemEllipse::brush () const inline
Definition at line 4200 of file qcustomplot.h.
draw() [1/2]
void QCPItemEllipse::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
Definition at line 31122 of file qcustomplot.cpp.
References bottomRight, QCPAbstractItem::clipRect(), mainBrush(), mainPen(), QCPItemPosition::pixelPosition(), QCPPainter::setPen(), QCPLayerable::setVisible(), and topLeft.
draw() [2/2]
virtual void QCPItemEllipse::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
mainBrush() [1/2]
QBrush QCPItemEllipse::mainBrush () const protected
Definition at line 31194 of file qcustomplot.cpp.
References mBrush, QCPAbstractItem::mSelected, and mSelectedBrush.
Referenced by draw().
mainBrush() [2/2]
QBrush QCPItemEllipse::mainBrush () const protected
mainPen() [1/2]
QPen QCPItemEllipse::mainPen () const protected
Definition at line 31187 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
mainPen() [2/2]
QPen QCPItemEllipse::mainPen () const protected
pen() [1/2]
QPen QCPItemEllipse::pen () const inline
Definition at line 7559 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
pen() [2/2]
QPen QCPItemEllipse::pen () const inline
Definition at line 4198 of file qcustomplot.h.
selectedBrush() [1/2]
QBrush QCPItemEllipse::selectedBrush () const inline
Definition at line 7562 of file qcustomplot.h.
selectedBrush() [2/2]
QBrush QCPItemEllipse::selectedBrush () const inline
Definition at line 4201 of file qcustomplot.h.
selectedPen() [1/2]
QPen QCPItemEllipse::selectedPen () const inline
Definition at line 7560 of file qcustomplot.h.
selectedPen() [2/2]
QPen QCPItemEllipse::selectedPen () const inline
Definition at line 4199 of file qcustomplot.h.
selectTest() [1/2]
double QCPItemEllipse::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 31095 of file qcustomplot.cpp.
References a, bottomRight, center, mBrush, QCPLayerable::mParentPlot, QCPAbstractItem::mSelectable, QCPItemPosition::pixelPosition(), result, QCustomPlot::selectionTolerance(), topLeft, x, and y.
selectTest() [2/2]
virtual double QCPItemEllipse::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
setBrush() [1/2]
void QCPItemEllipse::setBrush (const QBrush & brush)
Sets the brush that will be used to fill the ellipse. To disable filling, set brush to Qt::NoBrush.
See also
setSelectedBrush, setPen
Definition at line 31082 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPItemEllipse().
setBrush() [2/2]
void QCPItemEllipse::setBrush (const QBrush & brush)
setPen() [1/2]
void QCPItemEllipse::setPen (const QPen & pen)
Sets the pen that will be used to draw the line of the ellipse
See also
setSelectedPen, setBrush
Definition at line 31067 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemEllipse().
setPen() [2/2]
void QCPItemEllipse::setPen (const QPen & pen)
setSelectedBrush() [1/2]
void QCPItemEllipse::setSelectedBrush (const QBrush & brush)
Sets the brush that will be used to fill the ellipse when selected. To disable filling, set brush to Qt::NoBrush.
See also
setBrush
Definition at line 31090 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPItemEllipse().
setSelectedBrush() [2/2]
void QCPItemEllipse::setSelectedBrush (const QBrush & brush)
setSelectedPen() [1/2]
void QCPItemEllipse::setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw the line of the ellipse when selected
See also
setPen, setSelected
Definition at line 31074 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemEllipse().
setSelectedPen() [2/2]
void QCPItemEllipse::setSelectedPen (const QPen & pen)
Member Data Documentation
bottom
QCPItemAnchor *const QCPItemEllipse::bottom
Definition at line 7582 of file qcustomplot.h.
bottomLeftRim
QCPItemAnchor *const QCPItemEllipse::bottomLeftRim
Definition at line 7583 of file qcustomplot.h.
bottomRight
QCPItemPosition *const QCPItemEllipse::bottomRight
Definition at line 7576 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), QCPItemEllipse(), and selectTest().
bottomRightRim
QCPItemAnchor *const QCPItemEllipse::bottomRightRim
Definition at line 7581 of file qcustomplot.h.
center
QCPItemAnchor *const QCPItemEllipse::center
Definition at line 7585 of file qcustomplot.h.
Referenced by selectTest().
left
QCPItemAnchor *const QCPItemEllipse::left
Definition at line 7584 of file qcustomplot.h.
mBrush
QBrush QCPItemEllipse::mBrush protected
Definition at line 7602 of file qcustomplot.h.
Referenced by mainBrush(), selectTest(), and setBrush().
mPen
QPen QCPItemEllipse::mPen protected
Definition at line 7601 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
mSelectedBrush
QBrush QCPItemEllipse::mSelectedBrush protected
Definition at line 7602 of file qcustomplot.h.
Referenced by mainBrush(), and setSelectedBrush().
mSelectedPen
QPen QCPItemEllipse::mSelectedPen protected
Definition at line 7601 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
right
QCPItemAnchor *const QCPItemEllipse::right
Definition at line 7580 of file qcustomplot.h.
top
QCPItemAnchor *const QCPItemEllipse::top
Definition at line 7578 of file qcustomplot.h.
topLeft
QCPItemPosition *const QCPItemEllipse::topLeft
Definition at line 7575 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), QCPItemEllipse(), and selectTest().
topLeftRim
QCPItemAnchor *const QCPItemEllipse::topLeftRim
Definition at line 7577 of file qcustomplot.h.
topRightRim
QCPItemAnchor *const QCPItemEllipse::topRightRim
Definition at line 7579 of file qcustomplot.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp