ACloudViewer: cloudViewer::visualization::rendering::ModelInteractorLogic Class Reference
cloudViewer::visualization::rendering::ModelInteractorLogic Class Reference
#include <ModelInteractorLogic.h>
Public Member Functions
ModelInteractorLogic (CloudViewerScene *scene, Camera *camera, double min_far_plane)
virtual ~ModelInteractorLogic ()
void SetBoundingBox (const ccBBox &bounds) override
void SetModel (GeometryHandle axes, const std::vector< GeometryHandle > &objects)
void Rotate (int dx, int dy) override
void RotateZ (int dx, int dy) override
Rotates about the forward axis of the matrix.
void Dolly (float dy, DragType drag_type) override
void Pan (int dx, int dy) override
void StartMouseDrag () override
void UpdateMouseDragUI () override
void EndMouseDrag () override
Public Member Functions inherited from cloudViewer::visualization::rendering::RotationInteractorLogic
RotationInteractorLogic (Camera *camera, double min_far_plane)
~RotationInteractorLogic ()
virtual void SetCenterOfRotation (const Eigen::Vector3f &center)
Public Member Functions inherited from cloudViewer::visualization::rendering::MatrixInteractorLogic
virtual ~MatrixInteractorLogic ()
void SetViewSize (int width, int height)
int GetViewWidth () const
int GetViewHeight () const
const ccBBox & GetBoundingBox () const
Eigen::Vector3f GetCenterOfRotation () const
void SetMouseDownInfo (const Camera::Transform &matrix, const Eigen::Vector3f &center_of_rotation)
const Camera::Transform & GetMatrix () const
virtual void RotateWorld (int dx, int dy, const Eigen::Vector3f &x_axis, const Eigen::Vector3f &y_axis)
virtual void RotateZWorld (int dx, int dy, const Eigen::Vector3f &forward)
virtual void Dolly (float z_dist, Camera::Transform matrix)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::rendering::MatrixInteractorLogic
enum class DragType { MOUSE , WHEEL , TWO_FINGER }
Protected Member Functions inherited from cloudViewer::visualization::rendering::RotationInteractorLogic
Eigen::Vector3f CalcPanVectorWorld (int dx, int dy)
void UpdateCameraFarPlane ()
Protected Member Functions inherited from cloudViewer::visualization::rendering::MatrixInteractorLogic
void SetMatrix (const Camera::Transform &matrix)
float CalcRotateRadians (int dx, int dy)
float CalcRotateZRadians (int dx, int dy)
float CalcDollyDist (float dy, DragType drag_type, const Camera::Transform &matrix)
Protected Attributes inherited from cloudViewer::visualization::rendering::RotationInteractorLogic
double min_far_plane_
Camera * camera_
Protected Attributes inherited from cloudViewer::visualization::rendering::MatrixInteractorLogic
int view_width_ = 1
int view_height_ = 1
double model_size_ = 20.0
ccBBox model_bounds_
Eigen::Vector3f center_of_rotation_
Camera::Transform matrix_at_mouse_down_
Eigen::Vector3f center_of_rotation_at_mouse_down_
Detailed Description
Definition at line 21 of file ModelInteractorLogic.h.
Constructor & Destructor Documentation
ModelInteractorLogic()
cloudViewer::visualization::rendering::ModelInteractorLogic::ModelInteractorLogic (CloudViewerScene * scene, Camera * camera, double min_far_plane)
Definition at line 19 of file ModelInteractorLogic.cpp.
~ModelInteractorLogic()
cloudViewer::visualization::rendering::ModelInteractorLogic::~ModelInteractorLogic () virtual
Definition at line 24 of file ModelInteractorLogic.cpp.
Member Function Documentation
Dolly()
void cloudViewer::visualization::rendering::ModelInteractorLogic::Dolly (float dy, DragType drag_type) override virtual
Moves the matrix along the forward axis. (This is one type of zoom.)
Reimplemented from cloudViewer::visualization::rendering::MatrixInteractorLogic.
Definition at line 77 of file ModelInteractorLogic.cpp.
References cloudViewer::visualization::rendering::MatrixInteractorLogic::CalcDollyDist(), cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::Camera::GetForwardVector(), cloudViewer::visualization::rendering::Scene::GetGeometryTransform(), cloudViewer::visualization::rendering::CloudViewerScene::GetScene(), cloudViewer::visualization::rendering::MatrixInteractorLogic::matrix_at_mouse_down_, cloudViewer::visualization::rendering::MatrixInteractorLogic::MOUSE, cloudViewer::visualization::rendering::Scene::SetGeometryTransform(), and cloudViewer::visualization::rendering::RotationInteractorLogic::UpdateCameraFarPlane().
EndMouseDrag()
void cloudViewer::visualization::rendering::ModelInteractorLogic::EndMouseDrag () override virtual
Reimplemented from cloudViewer::visualization::rendering::RotationInteractorLogic.
Definition at line 152 of file ModelInteractorLogic.cpp.
References cloudViewer::visualization::rendering::CloudViewerScene::GetScene(), cloudViewer::visualization::rendering::kAxisObjectName(), and cloudViewer::visualization::rendering::Scene::ShowGeometry().
Pan()
void cloudViewer::visualization::rendering::ModelInteractorLogic::Pan (int dx, int dy) override virtual
Reimplemented from cloudViewer::visualization::rendering::RotationInteractorLogic.
Definition at line 101 of file ModelInteractorLogic.cpp.
References cloudViewer::visualization::rendering::RotationInteractorLogic::CalcPanVectorWorld(), cloudViewer::visualization::rendering::MatrixInteractorLogic::center_of_rotation_, cloudViewer::visualization::rendering::MatrixInteractorLogic::center_of_rotation_at_mouse_down_, cloudViewer::visualization::rendering::CloudViewerScene::GetScene(), and cloudViewer::visualization::rendering::Scene::SetGeometryTransform().
Rotate()
void cloudViewer::visualization::rendering::ModelInteractorLogic::Rotate (int dx, int dy) override virtual
Rotates about an axis defined by dx * matrixLeft, dy * matrixUp. dy is assumed to be in window-style coordinates, that is, going up produces a negative dy. The axis goes through the center of rotation.
Reimplemented from cloudViewer::visualization::rendering::MatrixInteractorLogic.
Definition at line 37 of file ModelInteractorLogic.cpp.
References cloudViewer::visualization::rendering::MatrixInteractorLogic::CalcRotateRadians(), cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::MatrixInteractorLogic::center_of_rotation_, cloudViewer::visualization::rendering::Camera::GetLeftVector(), cloudViewer::visualization::rendering::CloudViewerScene::GetScene(), cloudViewer::visualization::rendering::Camera::GetUpVector(), and cloudViewer::visualization::rendering::Scene::SetGeometryTransform().
RotateZ()
void cloudViewer::visualization::rendering::ModelInteractorLogic::RotateZ (int dx, int dy) override virtual
Rotates about the forward axis of the matrix.
Reimplemented from cloudViewer::visualization::rendering::MatrixInteractorLogic.
Definition at line 61 of file ModelInteractorLogic.cpp.
References cloudViewer::visualization::rendering::MatrixInteractorLogic::CalcRotateZRadians(), cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::MatrixInteractorLogic::center_of_rotation_, cloudViewer::visualization::rendering::Camera::GetForwardVector(), cloudViewer::visualization::rendering::CloudViewerScene::GetScene(), and cloudViewer::visualization::rendering::Scene::SetGeometryTransform().
SetBoundingBox()
void cloudViewer::visualization::rendering::ModelInteractorLogic::SetBoundingBox (const ccBBox & bounds) override virtual
Reimplemented from cloudViewer::visualization::rendering::MatrixInteractorLogic.
Definition at line 26 of file ModelInteractorLogic.cpp.
References ccBBox::GetCenter(), cloudViewer::visualization::rendering::MatrixInteractorLogic::SetBoundingBox(), and cloudViewer::visualization::rendering::MatrixInteractorLogic::SetMouseDownInfo().
SetModel()
void cloudViewer::visualization::rendering::ModelInteractorLogic::SetModel (GeometryHandle axes, const std::vector< GeometryHandle > & objects)
Definition at line 34 of file ModelInteractorLogic.cpp.
StartMouseDrag()
void cloudViewer::visualization::rendering::ModelInteractorLogic::StartMouseDrag () override virtual
Reimplemented from cloudViewer::visualization::rendering::RotationInteractorLogic.
Definition at line 130 of file ModelInteractorLogic.cpp.
References cloudViewer::visualization::rendering::MatrixInteractorLogic::center_of_rotation_, cloudViewer::visualization::rendering::Scene::GeometryIsVisible(), cloudViewer::visualization::rendering::CloudViewerScene::GetGeometries(), cloudViewer::visualization::rendering::CloudViewerScene::GetScene(), cloudViewer::visualization::rendering::kAxisObjectName(), cloudViewer::visualization::rendering::MatrixInteractorLogic::SetMouseDownInfo(), cloudViewer::visualization::rendering::Scene::ShowGeometry(), and cloudViewer::visualization::rendering::RotationInteractorLogic::UpdateCameraFarPlane().
UpdateMouseDragUI()
void cloudViewer::visualization::rendering::ModelInteractorLogic::UpdateMouseDragUI () override virtual
Reimplemented from cloudViewer::visualization::rendering::RotationInteractorLogic.
Definition at line 150 of file ModelInteractorLogic.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/ModelInteractorLogic.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/ModelInteractorLogic.cpp