ACloudViewer: ecvRecentFiles Class Reference
ecvRecentFiles Class Reference
#include <ecvRecentFiles.h>
Public Member Functions
ecvRecentFiles (QWidget *parent)
QMenu * menu ()
Returns a "most recently used file" menu.
void addFilePath (const QString &filePath)
Adds a file path to the recently used menu.
Detailed Description
Definition at line 17 of file ecvRecentFiles.h.
Constructor & Destructor Documentation
ecvRecentFiles()
ecvRecentFiles::ecvRecentFiles (QWidget * parent)
Definition at line 25 of file ecvRecentFiles.cpp.
References ecvPS::LoadFile(), and ecvSettingManager::removeKey().
Member Function Documentation
addFilePath()
void ecvRecentFiles::addFilePath (const QString & filePath)
Adds a file path to the recently used menu.
Definition at line 41 of file ecvRecentFiles.cpp.
References ecvSettingManager::getValue(), ecvPS::LoadFile(), and ecvSettingManager::setValue().
Referenced by MainWindow::addToDB().
menu()
QMenu * ecvRecentFiles::menu ()
Returns a "most recently used file" menu.
Definition at line 39 of file ecvRecentFiles.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvRecentFiles.h
/root/ACloudViewer/app/ecvRecentFiles.cpp