ACloudViewer: ecvPrimitiveDistanceDlg Class Reference
ecvPrimitiveDistanceDlg Class Reference
Dialog for cloud sphere or cloud plane comparison setting.
#include <ecvPrimitiveDistanceDlg.h>
Public Slots
void applyAndExit ()
void cancelAndExit ()
Public Member Functions
ecvPrimitiveDistanceDlg (QWidget *parent=nullptr)
Default constructor.
~ecvPrimitiveDistanceDlg ()=default
Default destructor.
bool signedDistances ()
bool flipNormals ()
bool treatPlanesAsBounded ()
Protected Slots
void toggleSigned (bool)
Detailed Description
Dialog for cloud sphere or cloud plane comparison setting.
Definition at line 22 of file ecvPrimitiveDistanceDlg.h.
Constructor & Destructor Documentation
ecvPrimitiveDistanceDlg()
ecvPrimitiveDistanceDlg::ecvPrimitiveDistanceDlg (QWidget * parent = nullptr)
Default constructor.
Definition at line 20 of file ecvPrimitiveDistanceDlg.cpp.
References applyAndExit(), cancelAndExit(), s_flipNormals, s_signedDist, s_treatAsBounded, and toggleSigned().
~ecvPrimitiveDistanceDlg()
ecvPrimitiveDistanceDlg::~ecvPrimitiveDistanceDlg () default
Default destructor.
Member Function Documentation
applyAndExit
void ecvPrimitiveDistanceDlg::applyAndExit () slot
Definition at line 37 of file ecvPrimitiveDistanceDlg.cpp.
References flipNormals(), s_flipNormals, s_signedDist, s_treatAsBounded, signedDistances(), and treatPlanesAsBounded().
Referenced by ecvPrimitiveDistanceDlg().
cancelAndExit
void ecvPrimitiveDistanceDlg::cancelAndExit () slot
Definition at line 44 of file ecvPrimitiveDistanceDlg.cpp.
Referenced by ecvPrimitiveDistanceDlg().
flipNormals()
bool ecvPrimitiveDistanceDlg::flipNormals () inline
Definition at line 34 of file ecvPrimitiveDistanceDlg.h.
Referenced by applyAndExit().
signedDistances()
bool ecvPrimitiveDistanceDlg::signedDistances () inline
Definition at line 33 of file ecvPrimitiveDistanceDlg.h.
Referenced by applyAndExit().
toggleSigned
void ecvPrimitiveDistanceDlg::toggleSigned (bool state) protected slot
Definition at line 46 of file ecvPrimitiveDistanceDlg.cpp.
Referenced by ecvPrimitiveDistanceDlg().
treatPlanesAsBounded()
bool ecvPrimitiveDistanceDlg::treatPlanesAsBounded () inline
Definition at line 35 of file ecvPrimitiveDistanceDlg.h.
Referenced by applyAndExit().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvPrimitiveDistanceDlg.h
/root/ACloudViewer/app/ecvPrimitiveDistanceDlg.cpp