ACloudViewer: QCPHiddenArea Class Reference
QCPHiddenArea Class Reference
QCustomPlot: greyed areas.
#include <ecvQCustomPlot.h>
Public Member Functions
QCPHiddenArea (bool leftSide, QCPAxis *keyAxis, QCPAxis *valueAxis)
Public Member Functions inherited from QCPSelectableCursor
QCPSelectableCursor (QCPAxis *keyAxis, QCPAxis *valueAxis)
Default constructor.
virtual bool isSelectable (QPoint click) const
double currentVal () const
double minVal () const
double maxVal () const
void range (double &minVal, double &maxVal) const
void setCurrentVal (double val)
void setRange (double minVal, double maxVal)
double pixelToKey (int pixX) const
Converts a pixel value (X) to the equivalent key.
double pixelToValue (int pixY) const
Converts a pixel value (Y) to the equivalent value.
virtual void clearData ()
double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const override
Protected Member Functions
virtual void draw (QCPPainter *painter)
Protected Member Functions inherited from QCPSelectableCursor
void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const override
QCPRange getKeyRange (bool &foundRange, QCP::SignDomain inSignDomain=QCP::sdBoth) const override
QCPRange getValueRange (bool &foundRange, QCP::SignDomain inSignDomain=QCP::sdBoth, const QCPRange &inKeyRange=QCPRange()) const override
Protected Attributes
bool mLeftSide
Whether the cursor is displayed on the left side or not.
Protected Attributes inherited from QCPSelectableCursor
double mCurrentVal
double mMinVal
double mMaxVal
QPoint mLastPos
int mLastRadius
Detailed Description
QCustomPlot: greyed areas.
Definition at line 255 of file ecvQCustomPlot.h.
Constructor & Destructor Documentation
QCPHiddenArea()
QCPHiddenArea::QCPHiddenArea (bool leftSide, QCPAxis * keyAxis, QCPAxis * valueAxis) inline explicit
Definition at line 259 of file ecvQCustomPlot.h.
References ecvColor::white().
Member Function Documentation
draw()
virtual void QCPHiddenArea::draw (QCPPainter * painter) inline protected virtual
Definition at line 271 of file ecvQCustomPlot.h.
References cloudViewer::utility::ceil(), color, cloudViewer::utility::floor(), QCPSelectableCursor::mCurrentVal, QCPSelectableCursor::mLastPos, QCPSelectableCursor::mLastRadius, mLeftSide, QCPSelectableCursor::mMaxVal, QCPSelectableCursor::mMinVal, rect::width, rect::x, and rect::y.
Member Data Documentation
mLeftSide
bool QCPHiddenArea::mLeftSide protected
Whether the cursor is displayed on the left side or not.
Definition at line 328 of file ecvQCustomPlot.h.
Referenced by draw().
The documentation for this class was generated from the following file:
/root/ACloudViewer/app/ecvQCustomPlot.h