ACloudViewer: ColorScheme Class Reference
ColorScheme Class Reference final
ColorScheme to be used by the PythonHighlighter & Editor.
#include <ColorScheme.h>
Public Types
using Vector = std::vector< ColorScheme >
Public Member Functions
const QString & name () const
The name of the color scheme.
QColor backgroundColor () const
Color to be used as the background for the displayed text.
QColor foregroundColor () const
Color to be used for regular text.
QColor currentLineHighlightColor () const
Color to be used if a highlight of the current line is shown.
const QTextCharFormat & operator[] (PythonHighlighter::CodeElement e) const
Returns the format to be used for the given code element.
Static Public Member Functions
static const Vector & AvailableColorSchemes ()
Returns the vector of available color schemes.
static const ColorScheme * ColorSchemeByName (const QString &name)
static ColorScheme Default ()
Default color scheme.
static ColorScheme Dracula ()
Detailed Description
ColorScheme to be used by the PythonHighlighter & Editor.
Definition at line 13 of file ColorScheme.h.
Member Typedef Documentation
Vector
using ColorScheme::Vector = std::vector<ColorScheme>
Definition at line 16 of file ColorScheme.h.
Member Function Documentation
AvailableColorSchemes()
const ColorScheme::Vector & ColorScheme::AvailableColorSchemes () static
Returns the vector of available color schemes.
Definition at line 113 of file ColorScheme.cpp.
References Default(), Dracula(), and s_AvailableColorSchemes.
Referenced by EditorSettings::setupUi().
backgroundColor()
QColor ColorScheme::backgroundColor () const
Color to be used as the background for the displayed text.
Definition at line 52 of file ColorScheme.cpp.
ColorSchemeByName()
const ColorScheme * ColorScheme::ColorSchemeByName (const QString & name) static
Returns a ColorScheme that matches the given name. returns nullptr if the color scheme does not exists;
Definition at line 123 of file ColorScheme.cpp.
References name(), and s_AvailableColorSchemes.
Referenced by EditorSettings::loadFromSettings(), and EditorSettings::saveChanges().
currentLineHighlightColor()
QColor ColorScheme::currentLineHighlightColor () const
Color to be used if a highlight of the current line is shown.
Definition at line 57 of file ColorScheme.cpp.
Default()
ColorScheme ColorScheme::Default () static
Default color scheme.
Definition at line 69 of file ColorScheme.cpp.
References ecvColor::black(), ecvColor::blue(), FormatHelper(), ecvColor::magenta(), ecvColor::red(), ecvColor::white(), and ecvColor::yellow().
Referenced by AvailableColorSchemes().
Dracula()
ColorScheme ColorScheme::Dracula () static
Dracula color scheme https://draculatheme.com/
Definition at line 88 of file ColorScheme.cpp.
References FormatHelper(), and ecvColor::red().
Referenced by AvailableColorSchemes().
foregroundColor()
QColor ColorScheme::foregroundColor () const
Color to be used for regular text.
Definition at line 47 of file ColorScheme.cpp.
name()
const QString & ColorScheme::name () const
The name of the color scheme.
Definition at line 107 of file ColorScheme.cpp.
Referenced by ColorSchemeByName(), EditorSettings::saveChanges(), EditorSettings::setFormValuesToCurrentValues(), and EditorSettings::setupUi().
operator[]()
const QTextCharFormat & ColorScheme::operator[] (PythonHighlighter::CodeElement e) const
Returns the format to be used for the given code element.
Definition at line 62 of file ColorScheme.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/ColorScheme.h
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/ColorScheme.cpp