ACloudViewer: cloudViewer::core::TensorIterator Class Reference
cloudViewer::core::TensorIterator Class Reference
#include <Indexer.h>
Public Member Functions
TensorIterator (const Tensor &tensor)
CLOUDVIEWER_HOST_DEVICE int64_t NumWorkloads () const
CLOUDVIEWER_HOST_DEVICE void * GetPtr (int64_t workload_idx) const
Protected Attributes
TensorRef input_
int64_t ndims_
Detailed Description
Indexer to one Tensor
Example usage:
// Create a float Tensor and set all elements to 100.
std::vector<float> vals{0, 1, 2, 3, 4};
Tensor a(vals, SizeVector{5}, core::Float32);
TensorIterator iter(a);
for (int64_t i = 0; i < iter.NumWorkloads(); ++i) {
    *static_cast<float*>(iter.GetPtr(i)) = 100.f;
}
Definition at line 222 of file Indexer.h.
Constructor & Destructor Documentation
TensorIterator()
cloudViewer::core::TensorIterator::TensorIterator (const Tensor & tensor) inline
Definition at line 224 of file Indexer.h.
Member Function Documentation
GetPtr()
CLOUDVIEWER_HOST_DEVICE void* cloudViewer::core::TensorIterator::GetPtr (int64_t workload_idx) const inline
Definition at line 235 of file Indexer.h.
References cloudViewer::core::TensorRef::byte_strides_, cloudViewer::core::TensorRef::data_ptr_, cloudViewer::core::TensorRef::dtype_byte_size_, input_, ndims_, NumWorkloads(), and offset.
Referenced by cloudViewer::benchmarks::Rand().
NumWorkloads()
CLOUDVIEWER_HOST_DEVICE int64_t cloudViewer::core::TensorIterator::NumWorkloads () const inline
Definition at line 227 of file Indexer.h.
References input_, ndims_, and cloudViewer::core::TensorRef::shape_.
Referenced by GetPtr().
Member Data Documentation
input_
TensorRef cloudViewer::core::TensorIterator::input_ protected
Definition at line 251 of file Indexer.h.
Referenced by GetPtr(), and NumWorkloads().
ndims_
int64_t cloudViewer::core::TensorIterator::ndims_ protected
Definition at line 252 of file Indexer.h.
Referenced by GetPtr(), and NumWorkloads().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/Indexer.h