ACloudViewer: ccGuiPythonInstance Class Reference
ccGuiPythonInstance Class Reference final
#include <ccGuiPythonInstance.h>
Public Member Functions
ccGuiPythonInstance (ecvMainAppInterface *app) noexcept(false)
QMainWindow * getMainWindow ()
bool haveSelection () const
bool haveOneSelection () const
const ccHObject::Container & getSelectedEntities () const
void setSelectedInDB (ccHObject *obj, bool selected)
ccHObject * dbRootObject ()
void addToDB (pybind11::object &obj, bool updateZoom=false, bool autoExpandDBTree=true, bool checkDimensions=false, bool autoRedraw=true)
void removeFromDB (pybind11::object &obj)
void redrawAll (bool only2D=false)
void refreshAll (bool only2D=false)
void enableAll ()
void disableAll ()
void updateUI ()
void freezeUI (bool state)
ccHObject * loadFile (const char *filename, FileIOFilter::LoadParameters &parameters)
ecvMainAppInterface * app ()
Detailed Description
This class provide methods that are made available Python scripts kind of like C++ plugins have access to a ecvMainAppInterface. Thus this class is mostly a ecvMainAppInterface with some accommodations to handle the fact that it is made to interact with python.
Definition at line 26 of file ccGuiPythonInstance.h.
Constructor & Destructor Documentation
ccGuiPythonInstance()
ccGuiPythonInstance::ccGuiPythonInstance (ecvMainAppInterface * app) explicit noexcept
Definition at line 76 of file ccGuiPythonInstance.cpp.
Member Function Documentation
addToDB()
void ccGuiPythonInstance::addToDB (pybind11::object & obj, bool updateZoom = false, bool autoExpandDBTree = true, bool checkDimensions = false, bool autoRedraw = true)
Definition at line 125 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
app()
ecvMainAppInterface * ccGuiPythonInstance::app ()
Definition at line 196 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
dbRootObject()
ccHObject * ccGuiPythonInstance::dbRootObject ()
Definition at line 162 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
disableAll()
void ccGuiPythonInstance::disableAll ()
Definition at line 182 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
enableAll()
void ccGuiPythonInstance::enableAll ()
Definition at line 177 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
freezeUI()
void ccGuiPythonInstance::freezeUI (bool state)
Definition at line 192 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
getMainWindow()
QMainWindow * ccGuiPythonInstance::getMainWindow ()
Definition at line 84 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
getSelectedEntities()
const ccHObject::Container & ccGuiPythonInstance::getSelectedEntities () const
Definition at line 99 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
haveOneSelection()
bool ccGuiPythonInstance::haveOneSelection () const
Definition at line 94 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
haveSelection()
bool ccGuiPythonInstance::haveSelection () const
Definition at line 89 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
loadFile()
ccHObject * ccGuiPythonInstance::loadFile (const char * filename, FileIOFilter::LoadParameters & parameters)
Definition at line 109 of file ccGuiPythonInstance.cpp.
References CC_FERR_NO_ERROR, filename, FileIOFilter::LoadFromFile(), result, and ThrowForFileError().
Referenced by define_ccGUIPythonInstance().
redrawAll()
void ccGuiPythonInstance::redrawAll (bool only2D = false)
Definition at line 167 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
refreshAll()
void ccGuiPythonInstance::refreshAll (bool only2D = false)
Definition at line 172 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
removeFromDB()
void ccGuiPythonInstance::removeFromDB (pybind11::object & obj)
Definition at line 143 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
setSelectedInDB()
void ccGuiPythonInstance::setSelectedInDB (ccHObject * obj, bool selected)
Definition at line 104 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
updateUI()
void ccGuiPythonInstance::updateUI ()
Definition at line 187 of file ccGuiPythonInstance.cpp.
Referenced by define_ccGUIPythonInstance().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/Runtime/ccGuiPythonInstance.h
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/Runtime/ccGuiPythonInstance.cpp