ACloudViewer: cloudViewer::utility::filesystem::CFile Class Reference
cloudViewer::utility::filesystem::CFile Class Reference
#include <FileSystem.h>
Public Member Functions
~CFile ()
The destructor closes the file automatically.
bool Open (const std::string &filename, const std::string &mode)
Open a file.
std::string GetError ()
Returns the last encountered error for this file.
void Close ()
Close the file.
int64_t CurPos ()
Returns current position in the file (ftell).
int64_t GetFileSize ()
Returns the file size in bytes.
int64_t GetNumLines ()
Returns the number of lines in the file.
const char * ReadLine ()
template<class T >
size_t ReadData (T *data, size_t num_elems)
size_t ReadData (void *data, size_t elem_size, size_t num_elems)
FILE * GetFILE ()
Returns the underlying C FILE pointer.
Detailed Description
RAII Wrapper for C FILE* Throws exceptions in situations where the caller is not usually going to have proper handling code:
using an unopened CFile
errors and ferror from underlying calls (fclose, ftell, fseek, fread, fwrite, fgetpos, fsetpos)
reading a line that is too long, caller is unlikely to have proper code to handle a partial next line If you would like to handle any of these issues by not having your code throw, use try/catch (const std::exception &e) { ... }
Definition at line 219 of file FileSystem.h.
Constructor & Destructor Documentation
~CFile()
cloudViewer::utility::filesystem::CFile::~CFile ()
The destructor closes the file automatically.
Member Function Documentation
Close()
void cloudViewer::utility::filesystem::CFile::Close ()
Close the file.
CurPos()
int64_t cloudViewer::utility::filesystem::CFile::CurPos ()
Returns current position in the file (ftell).
Referenced by cloudViewer::t::io::ReadPointCloudFromSPLAT(), cloudViewer::t::io::ReadPointCloudFromTXT(), cloudViewer::io::ReadPointCloudFromXYZ(), cloudViewer::t::io::ReadPointCloudFromXYZI(), cloudViewer::io::ReadPointCloudFromXYZN(), and cloudViewer::io::ReadPointCloudFromXYZRGB().
GetError()
std::string cloudViewer::utility::filesystem::CFile::GetError ()
Returns the last encountered error for this file.
Referenced by cloudViewer::t::io::ReadNpy(), cloudViewer::t::io::ReadNpz(), cloudViewer::t::io::NumpyArray::Save(), cloudViewer::t::io::WriteNpzEmpty(), and cloudViewer::t::io::WriteNpzOneTensor().
GetFILE()
FILE* cloudViewer::utility::filesystem::CFile::GetFILE () inline
Returns the underlying C FILE pointer.
Definition at line 264 of file FileSystem.h.
Referenced by cloudViewer::t::io::ReadNpy(), cloudViewer::t::io::ReadNpz(), cloudViewer::t::io::ReadPointCloudFromPTS(), cloudViewer::t::io::NumpyArray::Save(), cloudViewer::t::io::WriteNpzEmpty(), cloudViewer::t::io::WriteNpzOneTensor(), cloudViewer::io::WritePointCloudToPTS(), cloudViewer::t::io::WritePointCloudToPTS(), cloudViewer::t::io::WritePointCloudToTXT(), cloudViewer::io::WritePointCloudToXYZ(), cloudViewer::t::io::WritePointCloudToXYZI(), cloudViewer::io::WritePointCloudToXYZN(), and cloudViewer::io::WritePointCloudToXYZRGB().
GetFileSize()
int64_t cloudViewer::utility::filesystem::CFile::GetFileSize ()
Returns the file size in bytes.
Referenced by cloudViewer::t::io::ReadPointCloudFromSPLAT(), cloudViewer::t::io::ReadPointCloudFromTXT(), cloudViewer::io::ReadPointCloudFromXYZ(), cloudViewer::t::io::ReadPointCloudFromXYZI(), cloudViewer::io::ReadPointCloudFromXYZN(), and cloudViewer::io::ReadPointCloudFromXYZRGB().
GetNumLines()
int64_t cloudViewer::utility::filesystem::CFile::GetNumLines ()
Returns the number of lines in the file.
Referenced by cloudViewer::t::io::ReadPointCloudFromTXT(), and cloudViewer::t::io::ReadPointCloudFromXYZI().
Open()
bool cloudViewer::utility::filesystem::CFile::Open (const std::string & filename, const std::string & mode)
Open a file.
Referenced by cloudViewer::t::io::DepthNoiseSimulator::DepthNoiseSimulator(), cloudViewer::t::io::ReadNpy(), cloudViewer::t::io::ReadNpz(), cloudViewer::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromSPLAT(), cloudViewer::t::io::ReadPointCloudFromTXT(), cloudViewer::io::ReadPointCloudFromXYZ(), cloudViewer::t::io::ReadPointCloudFromXYZI(), cloudViewer::io::ReadPointCloudFromXYZN(), cloudViewer::io::ReadPointCloudFromXYZRGB(), cloudViewer::t::io::NumpyArray::Save(), cloudViewer::t::io::WriteNpzEmpty(), cloudViewer::t::io::WriteNpzOneTensor(), cloudViewer::io::WritePointCloudToPTS(), cloudViewer::t::io::WritePointCloudToPTS(), cloudViewer::t::io::WritePointCloudToTXT(), cloudViewer::io::WritePointCloudToXYZ(), cloudViewer::t::io::WritePointCloudToXYZI(), cloudViewer::io::WritePointCloudToXYZN(), and cloudViewer::io::WritePointCloudToXYZRGB().
ReadData() [1/2]
template<class T > size_t cloudViewer::utility::filesystem::CFile::ReadData (T * data, size_t num_elems) inline
Read data to a buffer.
Parameters
data The data buffer to be written into.
num_elements Number of elements to be read. The byte size of the element is determined by the size of buffer type.
Definition at line 253 of file FileSystem.h.
Referenced by cloudViewer::t::io::ReadPointCloudFromSPLAT().
ReadData() [2/2]
size_t cloudViewer::utility::filesystem::CFile::ReadData (void * data, size_t elem_size, size_t num_elems)
Read data to a buffer.
Parameters
data The data buffer to be written into.
elem_size Element size in bytes.
num_elems Number of elements to read.
ReadLine()
const char* cloudViewer::utility::filesystem::CFile::ReadLine ()
Throws if we hit buffer maximum. In most cases, calling code is only capable of processing a complete line, if it receives a partial line it will probably fail and it is very likely to fail/corrupt on the next call that receives the remainder of the line.
Referenced by cloudViewer::t::io::DepthNoiseSimulator::DepthNoiseSimulator(), cloudViewer::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromTXT(), cloudViewer::io::ReadPointCloudFromXYZ(), cloudViewer::t::io::ReadPointCloudFromXYZI(), cloudViewer::io::ReadPointCloudFromXYZN(), and cloudViewer::io::ReadPointCloudFromXYZRGB().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/FileSystem.h