ACloudViewer: VtkUtils::AbstractFileReader Class Reference
VtkUtils::AbstractFileReader Class Reference
#include <filereaderutils.h>
Signals
void finished ()
Public Member Functions
AbstractFileReader (QObject *parent=nullptr)
void setFileName (const QString &file)
QString fileName () const
void setTitle (const QString &title)
QString title () const
Protected Attributes
QString m_fileName
QString m_title
Detailed Description
Definition at line 47 of file filereaderutils.h.
Constructor & Destructor Documentation
AbstractFileReader()
VtkUtils::AbstractFileReader::AbstractFileReader (QObject * parent = nullptr) explicit
Definition at line 100 of file filereaderutils.cpp.
Member Function Documentation
fileName()
QString VtkUtils::AbstractFileReader::fileName () const
Definition at line 106 of file filereaderutils.cpp.
References m_fileName.
Referenced by VtkUtils::VtkFileReader::run(), VtkUtils::StlFileReader::run(), VtkUtils::ObjFileReader::run(), VtkUtils::DynaFileReader::run(), VtkUtils::NastranFileReader::run(), VtkUtils::FluentFileReader::run(), VtkUtils::AnsysFileReader::run(), VtkUtils::PlyFileReader::run(), and VtkUtils::PdbFileReader::run().
finished
void VtkUtils::AbstractFileReader::finished () signal
Referenced by VtkUtils::VtkFileReader::run(), VtkUtils::StlFileReader::run(), VtkUtils::ObjFileReader::run(), VtkUtils::DynaFileReader::run(), VtkUtils::NastranFileReader::run(), VtkUtils::FluentFileReader::run(), VtkUtils::AnsysFileReader::run(), VtkUtils::PlyFileReader::run(), and VtkUtils::PdbFileReader::run().
setFileName()
void VtkUtils::AbstractFileReader::setFileName (const QString & file)
Definition at line 102 of file filereaderutils.cpp.
References m_fileName.
setTitle()
void VtkUtils::AbstractFileReader::setTitle (const QString & title)
Definition at line 108 of file filereaderutils.cpp.
References m_title, and title().
title()
QString VtkUtils::AbstractFileReader::title () const
Definition at line 112 of file filereaderutils.cpp.
References m_title.
Referenced by setTitle().
Member Data Documentation
m_fileName
QString VtkUtils::AbstractFileReader::m_fileName protected
Definition at line 63 of file filereaderutils.h.
Referenced by fileName(), and setFileName().
m_title
QString VtkUtils::AbstractFileReader::m_title protected
Definition at line 64 of file filereaderutils.h.
Referenced by VtkUtils::NastranFileReader::run(), VtkUtils::AnsysFileReader::run(), setTitle(), and title().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/filereaderutils.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/filereaderutils.cpp