ACloudViewer: colmap::TransitiveMatchingTab Class Reference
colmap::TransitiveMatchingTab Class Reference
Public Member Functions
TransitiveMatchingTab (QWidget *parent, OptionManager *options)
void Run () override
Public Member Functions inherited from colmap::FeatureMatchingTab
FeatureMatchingTab (QWidget *parent, OptionManager *options)
Additional Inherited Members
Protected Member Functions inherited from colmap::FeatureMatchingTab
void CreateGeneralOptions ()
Protected Attributes inherited from colmap::FeatureMatchingTab
OptionManager * options_
OptionsWidget * options_widget_
QGridLayout * grid_layout_
ThreadControlWidget * thread_control_widget_
Detailed Description
Definition at line 79 of file feature_matching_widget.cc.
Constructor & Destructor Documentation
TransitiveMatchingTab()
colmap::TransitiveMatchingTab::TransitiveMatchingTab (QWidget * parent, OptionManager * options)
Definition at line 272 of file feature_matching_widget.cc.
References colmap::OptionsWidget::AddOptionInt(), colmap::FeatureMatchingTab::CreateGeneralOptions(), colmap::FeatureMatchingTab::options_widget_, and colmap::OptionManager::transitive_matching.
Member Function Documentation
Run()
void colmap::TransitiveMatchingTab::Run () override virtual
Implements colmap::FeatureMatchingTab.
Definition at line 283 of file feature_matching_widget.cc.
References colmap::OptionManager::database_path, colmap::FeatureMatchingTab::options_, colmap::FeatureMatchingTab::options_widget_, colmap::OptionManager::sift_matching, colmap::ThreadControlWidget::StartThread(), colmap::FeatureMatchingTab::thread_control_widget_, colmap::OptionManager::transitive_matching, and colmap::OptionsWidget::WriteOptions().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/ui/feature_matching_widget.cc