ACloudViewer: cloudViewer::visualization::gui::Label Class Reference
cloudViewer::visualization::gui::Label Class Reference
#include <Label.h>
Classes
struct Impl
Public Member Functions
Label (const char *text=nullptr)
Copies text.
~Label ()
const char * GetText () const
void SetText (const char *text)
Sets the text of the label (copies text)
Color GetTextColor () const
void SetTextColor (const Color &color)
FontId GetFontId () const
void SetFontId (const FontId font_id)
Size CalcPreferredSize (const LayoutContext &context, const Constraints &constraints) const override
DrawResult Draw (const DrawContext &context) override
Public Member Functions inherited from cloudViewer::visualization::gui::Widget
Widget ()
Widget (const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Widget ()
virtual void AddChild (std::shared_ptr< Widget > child)
virtual const std::vector< std::shared_ptr< Widget > > GetChildren () const
virtual const Rect & GetFrame () const
Returns the frame size in pixels.
virtual void SetFrame (const Rect &f)
virtual const Color & GetBackgroundColor () const
virtual bool IsDefaultBackgroundColor () const
virtual void SetBackgroundColor (const Color &color)
virtual bool IsVisible () const
virtual void SetVisible (bool vis)
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
virtual void SetTooltip (const char *text)
virtual const char * GetTooltip () const
virtual Size CalcMinimumSize (const LayoutContext &context) const
virtual void Layout (const LayoutContext &context)
virtual EventResult Mouse (const MouseEvent &e)
virtual EventResult Key (const KeyEvent &e)
virtual DrawResult Tick (const TickEvent &e)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::gui::Widget
enum class DrawResult { NONE , REDRAW , RELAYOUT }
enum class EventResult { IGNORED , CONSUMED , DISCARD }
Static Public Attributes inherited from cloudViewer::visualization::gui::Widget
static constexpr int DIM_GROW = 10000
Protected Member Functions inherited from cloudViewer::visualization::gui::Widget
void DrawImGuiPushEnabledState ()
void DrawImGuiPopEnabledState ()
void DrawImGuiTooltip ()
Detailed Description
Definition at line 16 of file Label.h.
Constructor & Destructor Documentation
Label()
cloudViewer::visualization::gui::Label::Label (const char * text = nullptr) explicit
Copies text.
Definition at line 42 of file Label.cpp.
References SetText().
~Label()
cloudViewer::visualization::gui::Label::~Label ()
Definition at line 48 of file Label.cpp.
Member Function Documentation
CalcPreferredSize()
Size cloudViewer::visualization::gui::Label::CalcPreferredSize (const LayoutContext & context, const Constraints & constraints) const override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 65 of file Label.cpp.
References cloudViewer::utility::ceil(), context, max(), min(), cloudViewer::visualization::gui::PREFERRED_WRAP_WIDTH_EM, size, and cloudViewer::visualization::gui::Widget::Constraints::width.
Draw()
Widget::DrawResult cloudViewer::visualization::gui::Label::Draw (const DrawContext & context) override virtual
Draws the widget. If this is a Dear ImGUI widget, this is where the actual event processing happens. Return NONE if no action needs to be taken, REDRAW if the widget needs to be redrawn (e.g. its value changed), and RELAYOUT if the widget wishes to change size.
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 115 of file Label.cpp.
References cloudViewer::visualization::gui::colorToImgui(), context, cloudViewer::visualization::gui::DEFAULT_COLOR, cloudViewer::visualization::gui::Widget::DrawImGuiTooltip(), frame, cloudViewer::visualization::gui::Widget::GetFrame(), and cloudViewer::visualization::gui::Widget::NONE.
GetFontId()
FontId cloudViewer::visualization::gui::Label::GetFontId () const
Definition at line 61 of file Label.cpp.
GetText()
const char * cloudViewer::visualization::gui::Label::GetText () const
Definition at line 50 of file Label.cpp.
GetTextColor()
Color cloudViewer::visualization::gui::Label::GetTextColor () const
Definition at line 57 of file Label.cpp.
SetFontId()
void cloudViewer::visualization::gui::Label::SetFontId (const FontId font_id)
Definition at line 63 of file Label.cpp.
SetText()
void cloudViewer::visualization::gui::Label::SetText (const char * text)
Sets the text of the label (copies text)
Definition at line 52 of file Label.cpp.
Referenced by Label().
SetTextColor()
void cloudViewer::visualization::gui::Label::SetTextColor (const Color & color)
Definition at line 59 of file Label.cpp.
References color.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Label.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Label.cpp