ACloudViewer: LasScalarFieldLoader Class Reference
LasScalarFieldLoader Class Reference
#include <LasScalarFieldLoader.h>
Public Member Functions
LasScalarFieldLoader (std::vector< LasScalarField > &standardScalarFields, std::vector< LasExtraScalarField > &extraScalarFields, ccPointCloud &pointCloud)
CC_FILE_ERROR handleScalarFields (ccPointCloud &pointCloud, const laszip_point &currentPoint)
CC_FILE_ERROR handleRGBValue (ccPointCloud &pointCloud, const laszip_point &currentPoint)
CC_FILE_ERROR handleExtraScalarFields (ccPointCloud &pointCloud, const laszip_point &currentPoint)
void setIgnoreFieldsWithDefaultValues (bool state)
void setForce8bitRgbMode (bool state)
void setManualTimeShift (double timeShift)
const std::vector< LasScalarField > & standardFields () const
const std::vector< LasExtraScalarField > & extraFields () const
Detailed Description
Class with the logic on how to load LAS dimensions values from the LAS file into a ccPointCloud's scalar field.
This also handles LAS extra scalar fields, as well as RGB.
Definition at line 45 of file LasScalarFieldLoader.h.
Constructor & Destructor Documentation
LasScalarFieldLoader()
LasScalarFieldLoader::LasScalarFieldLoader (std::vector< LasScalarField > & standardScalarFields, std::vector< LasExtraScalarField > & extraScalarFields, ccPointCloud & pointCloud)
Definition at line 16 of file LasScalarFieldLoader.cpp.
Member Function Documentation
extraFields()
const std::vector<LasExtraScalarField>& LasScalarFieldLoader::extraFields () const inline
Definition at line 82 of file LasScalarFieldLoader.h.
Referenced by LasIOFilter::loadFile().
handleExtraScalarFields()
CC_FILE_ERROR LasScalarFieldLoader::handleExtraScalarFields (ccPointCloud & pointCloud, const laszip_point & currentPoint)
Definition at line 148 of file LasScalarFieldLoader.cpp.
References CC_FERR_NO_ERROR, CC_FERR_READING, LasExtraScalarField::Floating, LasExtraScalarField::Signed, and LasExtraScalarField::Unsigned.
Referenced by LasIOFilter::loadFile().
handleRGBValue()
CC_FILE_ERROR LasScalarFieldLoader::handleRGBValue (ccPointCloud & pointCloud, const laszip_point & currentPoint)
In LAS files, the red, green and blue channels are normal LAS fields, however in ACloudViewer RGB is handled differently.
Definition at line 106 of file LasScalarFieldLoader.cpp.
References ccPointCloud::addRGBColor(), ecvColor::black(), ecvColor::blue(), CC_FERR_NO_ERROR, CC_FERR_NOT_ENOUGH_MEMORY, ecvColor::green(), ccPointCloud::hasColors(), ecvColor::red(), ccPointCloud::reserveTheRGBTable(), and cloudViewer::PointCloudTpl< T >::size().
Referenced by LasIOFilter::loadFile().
handleScalarFields()
CC_FILE_ERROR LasScalarFieldLoader::handleScalarFields (ccPointCloud & pointCloud, const laszip_point & currentPoint)
Definition at line 25 of file LasScalarFieldLoader.cpp.
References CC_FERR_NO_ERROR, LasScalarField::Classification, LasScalarField::EdgeOfFlightLine, error(), LasScalarField::ExtendedClassification, LasScalarField::ExtendedNumberOfReturns, LasScalarField::ExtendedReturnNumber, LasScalarField::ExtendedScanAngle, LasScalarField::ExtendedScannerChannel, LasScalarField::GpsTime, LasScalarField::Intensity, LasScalarField::KeypointFlag, LasScalarField::NearInfrared, LasScalarField::NumberOfReturns, LasDetails::OVERLAP_FLAG_BIT_MASK, LasScalarField::OverlapFlag, LasScalarField::PointSourceId, LasScalarField::ReturnNumber, SCAN_ANGLE_SCALE, LasScalarField::ScanAngleRank, LasScalarField::ScanDirectionFlag, LasScalarField::SyntheticFlag, LasScalarField::UserData, and LasScalarField::WithheldFlag.
Referenced by LasIOFilter::loadFile().
setForce8bitRgbMode()
void LasScalarFieldLoader::setForce8bitRgbMode (bool state) inline
Definition at line 65 of file LasScalarFieldLoader.h.
Referenced by LasIOFilter::loadFile().
setIgnoreFieldsWithDefaultValues()
void LasScalarFieldLoader::setIgnoreFieldsWithDefaultValues (bool state) inline
Definition at line 60 of file LasScalarFieldLoader.h.
Referenced by LasIOFilter::loadFile().
setManualTimeShift()
void LasScalarFieldLoader::setManualTimeShift (double timeShift) inline
If nan, this value will be ignored and the time shift will be taken using the first value encountered.
Definition at line 72 of file LasScalarFieldLoader.h.
Referenced by LasIOFilter::loadFile().
standardFields()
const std::vector<LasScalarField>& LasScalarFieldLoader::standardFields () const inline
Definition at line 77 of file LasScalarFieldLoader.h.
Referenced by LasIOFilter::loadFile().
Member Data Documentation
floatingValues
double LasScalarFieldLoader::floatingValues[LasExtraScalarField::MAX_DIM_SIZE]
Definition at line 133 of file LasScalarFieldLoader.h.
signedValues
int64_t LasScalarFieldLoader::signedValues[LasExtraScalarField::MAX_DIM_SIZE]
Definition at line 132 of file LasScalarFieldLoader.h.
unsignedValues
uint64_t LasScalarFieldLoader::unsignedValues[LasExtraScalarField::MAX_DIM_SIZE]
Definition at line 131 of file LasScalarFieldLoader.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qLASIO/include/LasScalarFieldLoader.h
/root/ACloudViewer/plugins/core/IO/qLASIO/src/LasScalarFieldLoader.cpp