ACloudViewer: FileIOFilter Class Reference
FileIOFilter Class Reference
Generic file I/O filter.
#include <FileIOFilter.h>
Classes
struct FilterInfo
struct LoadParameters
Generic loading parameters.
struct SaveParameters
Generic saving parameters.
Public Types
enum FilterFeature {
NoFeatures = 0x0000 , Import = 0x00001 , Export = 0x0002 , BuiltIn = 0x0004 ,
DynamicInfo = 0x0008
}
using Shared = QSharedPointer< FileIOFilter >
Shared type.
using FilterContainer = std::vector< FileIOFilter::Shared >
Type of a I/O filters container.
Public Member Functions
virtual ~FileIOFilter ()=default
bool importSupported () const
Returns whether this I/O filter can import files.
bool exportSupported () const
Returns whether this I/O filter can export files.
const QStringList & getFileFilters (bool onImport) const
Returns the file filter(s) for this I/O filter.
QString getDefaultExtension () const
Returns the default file extension.
virtual CC_FILE_ERROR loadFile (const QString &filename, ccHObject &container, LoadParameters &parameters)
Loads one or more entities from a file.
virtual CC_FILE_ERROR saveToFile (ccHObject *entity, const QString &filename, const SaveParameters &parameters)
Saves an entity (or a group of) to a file.
virtual bool canSave (CV_CLASS_ENUM type, bool &multiple, bool &exclusive) const
Returns whether this I/O filter can save the specified type of entity.
virtual void unregister ()
Called when the filter is unregistered.
Static Public Member Functions
static QStringList ImportFilterList ()
static ccHObject * LoadFromFile (const QString &filename, LoadParameters &parameters, Shared filter, CC_FILE_ERROR &result)
Loads one or more entities from a file with a known filter.
static ccHObject * LoadFromFile (const QString &filename, LoadParameters &parameters, CC_FILE_ERROR &result, const QString &fileFilter=QString())
Loads one or more entities from a file with known type.
static CC_FILE_ERROR SaveToFile (ccHObject *entities, const QString &filename, const SaveParameters &parameters, Shared filter)
static CC_FILE_ERROR SaveToFile (ccHObject *entities, const QString &filename, const SaveParameters &parameters, const QString &fileFilter)
static bool HandleGlobalShift (const CCVector3d &P, CCVector3d &Pshift, bool &preserveCoordinateShift, LoadParameters &loadParameters, bool useInputCoordinatesShiftIfPossible=false)
Shortcut to the ecvGlobalShiftManager mechanism specific for files.
static void DisplayErrorMessage (CC_FILE_ERROR err, const QString &action, const QString &filename)
Displays (to console) the message corresponding to a given error code.
static bool CheckForSpecialChars (const QString &filename)
Returns whether special characters are present in the input string.
static void ResetSesionCounter ()
static unsigned IncreaseSesionCounter ()
static void Register (Shared filter)
Registers a new filter.
static Shared GetFilter (const QString &fileFilter, bool onImport)
Returns the filter corresponding to the given 'file filter'.
static Shared FindBestFilterForExtension (const QString &ext)
Returns the best filter (presumably) to open a given file extension.
static const FilterContainer & GetFilters ()
Returns the set of all registered filters.
static void UnregisterAll ()
Unregisters all filters.
Protected Member Functions
FileIOFilter (const FilterInfo &info)
void setImportExtensions (const QStringList &extensions)
void setImportFileFilterStrings (const QStringList &filterStrings)
void setExportFileFilterStrings (const QStringList &filterStrings)
Static Protected Attributes
static constexpr float DEFAULT_PRIORITY = 25.0f
Detailed Description
Generic file I/O filter.
Gives static access to file loader. Must be implemented by any specific I/O filter.
Definition at line 46 of file FileIOFilter.h.
Member Typedef Documentation
FilterContainer
using FileIOFilter::FilterContainer = std::vector<FileIOFilter::Shared>
Type of a I/O filters container.
Definition at line 284 of file FileIOFilter.h.
Shared
using FileIOFilter::Shared = QSharedPointer<FileIOFilter>
Shared type.
Definition at line 97 of file FileIOFilter.h.
Member Enumeration Documentation
FilterFeature
enum FileIOFilter::FilterFeature
Enumerator
NoFeatures
Import
Export
BuiltIn
DynamicInfo
Definition at line 299 of file FileIOFilter.h.
Constructor & Destructor Documentation
~FileIOFilter()
virtual FileIOFilter::~FileIOFilter () virtual default
FileIOFilter()
FileIOFilter::FileIOFilter (const FilterInfo & info) explicit protected
Definition at line 52 of file FileIOFilter.cpp.
References DynamicInfo, and FileIOFilter::FilterInfo::features.
Member Function Documentation
canSave()
virtual bool FileIOFilter::canSave (CV_CLASS_ENUM type, bool & multiple, bool & exclusive) const inline virtual
Returns whether this I/O filter can save the specified type of entity.
Parameters
type entity type
multiple whether the filter can save multiple instances of this entity at once
exclusive whether the filter can only save this type of entity if selected or if it can be mixed with other types
Returns
whether the entity type can be saved
Reimplemented in RDBFilter, LASFilter, LasIOFilter, LASFWFFilter, FBXFilter, E57Filter, DRCFilter, SimpleBinFilter, MascaretFilter, MAFilter, HeightProfileFilter, SinusxFilter, SalomeHydroFilter, PVFilter, PovFilter, PNFilter, VTKFilter, STLFilter, PlyFilter, OFFFilter, ObjFilter, ImageFileFilter, DxfFilter, DepthMapFileFilter, BinFilter, AsciiFilter, PcdFilter, and IoAbstractLoader.
Definition at line 158 of file FileIOFilter.h.
References type.
CheckForSpecialChars()
bool FileIOFilter::CheckForSpecialChars (const QString & filename) static
Returns whether special characters are present in the input string.
Definition at line 505 of file FileIOFilter.cpp.
References filename.
Referenced by IcmFilter::LoadCalibratedImages(), DxfFilter::loadFile(), IcmFilter::loadFile(), FBXFilter::loadFile(), DxfFilter::saveToFile(), FBXFilter::saveToFile(), and DepthMapFileFilter::saveToFile().
DisplayErrorMessage()
void FileIOFilter::DisplayErrorMessage (CC_FILE_ERROR err, const QString & action, const QString & filename) static
Displays (to console) the message corresponding to a given error code.
Parameters
err error code
action "saving", "reading", etc.
filename corresponding file
Definition at line 425 of file FileIOFilter.cpp.
References CC_FERR_BAD_ARGUMENT, CC_FERR_BAD_ENTITY_TYPE, CC_FERR_BROKEN_DEPENDENCY_ERROR, CC_FERR_CANCELED_BY_USER, CC_FERR_CONSOLE_ERROR, CC_FERR_FILE_WAS_WRITTEN_BY_UNKNOWN_PLUGIN, CC_FERR_MALFORMED_FILE, CC_FERR_NO_ERROR, CC_FERR_NO_LOAD, CC_FERR_NO_SAVE, CC_FERR_NOT_ENOUGH_MEMORY, CC_FERR_NOT_IMPLEMENTED, CC_FERR_READING, CC_FERR_THIRD_PARTY_LIB_EXCEPTION, CC_FERR_THIRD_PARTY_LIB_FAILURE, CC_FERR_UNKNOWN_FILE, CC_FERR_WRITING, CC_FERR_WRONG_FILE_TYPE, CVLog::Error(), filename, and CVLog::Warning().
Referenced by cloudViewer::io::AutoReadEntity(), cloudViewer::io::AutoWriteEntity(), LoadFromFile(), and SaveToFile().
exportSupported()
bool FileIOFilter::exportSupported () const
Returns whether this I/O filter can export files.
Definition at line 65 of file FileIOFilter.cpp.
References Export, and FileIOFilter::FilterInfo::features.
FindBestFilterForExtension()
FileIOFilter::Shared FileIOFilter::FindBestFilterForExtension (const QString & ext) static
Returns the best filter (presumably) to open a given file extension.
Definition at line 228 of file FileIOFilter.cpp.
References s_ioFilters.
Referenced by cloudViewer::io::AutoReadEntity(), cloudViewer::io::AutoWriteEntity(), IcmFilter::loadFile(), PovFilter::loadFile(), and LoadFromFile().
getDefaultExtension()
QString FileIOFilter::getDefaultExtension () const
Returns the default file extension.
Definition at line 77 of file FileIOFilter.cpp.
References FileIOFilter::FilterInfo::defaultExtension.
getFileFilters()
const QStringList & FileIOFilter::getFileFilters (bool onImport) const
Returns the file filter(s) for this I/O filter.
E.g. 'ASCII file (*.asc)'
Parameters
onImport whether the requested filters are for import or export
Returns
list of filters
Definition at line 69 of file FileIOFilter.cpp.
References FileIOFilter::FilterInfo::exportFileFilterStrings, and FileIOFilter::FilterInfo::importFileFilterStrings.
GetFilter()
FileIOFilter::Shared FileIOFilter::GetFilter (const QString & fileFilter, bool onImport) static
Returns the filter corresponding to the given 'file filter'.
Definition at line 212 of file FileIOFilter.cpp.
References s_ioFilters.
Referenced by LoadFromFile(), CommandLoadLASFWF::process(), ccCommandLineParser::saveClouds(), ccCommandLineParser::saveMeshes(), and SaveToFile().
GetFilters()
const FileIOFilter::FilterContainer & FileIOFilter::GetFilters () static
Returns the set of all registered filters.
Definition at line 224 of file FileIOFilter.cpp.
References s_ioFilters.
Referenced by cloudViewer::io::AutoReadEntity(), cloudViewer::io::AutoWriteEntity(), define_qcc_io(), CommandChangeOutputFormat::getFileFormatFilter(), and cvSelectionExporter::saveObjectToFileWithDialog().
HandleGlobalShift()
bool FileIOFilter::HandleGlobalShift (const CCVector3d & P, CCVector3d & Pshift, bool & preserveCoordinateShift, LoadParameters & loadParameters, bool useInputCoordinatesShiftIfPossible = false) static
Shortcut to the ecvGlobalShiftManager mechanism specific for files.
Parameters
[in] P sample point (typically the first loaded)
[out] Pshift global shift
[out] preserveCoordinateShift whether shift sould be preserved on save
[in] loadParameters loading parameters
[in] useInputCoordinatesShiftIfPossible whether to use the input 'PShift' vector if possible
Returns
whether global shift has been defined/enabled
Definition at line 509 of file FileIOFilter.cpp.
References FileIOFilter::LoadParameters::coordinatesShift, FileIOFilter::LoadParameters::coordinatesShiftEnabled, ecvGlobalShiftManager::Handle(), FileIOFilter::LoadParameters::preserveShiftOnSave, and FileIOFilter::LoadParameters::shiftHandlingMode.
Referenced by FromFbxMesh(), GetGlobalShift(), STLFilter::loadASCIIFile(), STLFilter::loadBinaryFile(), LoadCloud(), AsciiFilter::loadCloudFromFormatedAsciiStream(), ObjFilter::loadFile(), OFFFilter::loadFile(), PTXFilter::loadFile(), VTKFilter::loadFile(), SalomeHydroFilter::loadFile(), SinusxFilter::loadFile(), SimpleBinFilter::loadFile(), LASFWFFilter::loadFile(), LASFilter::loadFile(), LoadScan(), and vertex_cb().
ImportFilterList()
QStringList FileIOFilter::ImportFilterList () static
Get a list of all the available importer filter strings for use in a drop down menu. Includes "All (*.)" as the first item in the list.
Definition at line 241 of file FileIOFilter.cpp.
References s_ioFilters.
importSupported()
bool FileIOFilter::importSupported () const
Returns whether this I/O filter can import files.
Definition at line 61 of file FileIOFilter.cpp.
References FileIOFilter::FilterInfo::features, and Import.
IncreaseSesionCounter()
unsigned FileIOFilter::IncreaseSesionCounter () static
Indicates to the I/O filters that a new loading/saving action has started
Returns
the updated session counter
Definition at line 142 of file FileIOFilter.cpp.
References s_sessionCounter.
Referenced by cloudViewer::io::AutoReadEntity(), and LoadFromFile().
loadFile()
virtual CC_FILE_ERROR FileIOFilter::loadFile (const QString & filename, ccHObject & container, LoadParameters & parameters) inline virtual
Loads one or more entities from a file.
This method must be implemented by children classes.
Parameters
filename file to load
container container to store loaded entities
parameters generic loading parameters
Returns
error
Reimplemented in IoAbstractLoader, STEPFilter, RDBFilter, LASFilter, LasIOFilter, LASFWFFilter, FBXFilter, E57Filter, DRCFilter, SimpleBinFilter, PDMSFilter, SoiFilter, SinusxFilter, SalomeHydroFilter, PVFilter, PovFilter, PNFilter, IcmFilter, BundlerFilter, VTKFilter, STLFilter, PTXFilter, PlyFilter, OFFFilter, ObjFilter, ImageFileFilter, DxfFilter, BinFilter, AsciiFilter, PcdFilter, PhotoScanFilter, and CSVMatrixFilter.
Definition at line 124 of file FileIOFilter.h.
References CC_FERR_NOT_IMPLEMENTED, and filename.
LoadFromFile() [1/2]
ccHObject * FileIOFilter::LoadFromFile (const QString & filename, LoadParameters & parameters, CC_FILE_ERROR & result, const QString & fileFilter = QString()) static
Loads one or more entities from a file with known type.
Shortcut to the other version of FileIOFilter::LoadFromFile
Parameters
filename filename
parameters generic loading parameters
[out] result file error code
fileFilter input filter 'file filter' (if empty, the best I/O filter will be guessed from the file extension)
Returns
loaded entities (or 0 if an error occurred)
Definition at line 334 of file FileIOFilter.cpp.
References CC_FERR_CONSOLE_ERROR, CVLog::Error(), filename, FindBestFilterForExtension(), GetFilter(), LoadFromFile(), and result.
LoadFromFile() [2/2]
ccHObject * FileIOFilter::LoadFromFile (const QString & filename, LoadParameters & parameters, Shared filter, CC_FILE_ERROR & result) static
Loads one or more entities from a file with a known filter.
Shortcut to FileIOFilter::loadFile
Parameters
filename filename
parameters generic loading parameters
filter input filter
[out] result file error code
Returns
loaded entities (or 0 if an error occurred)
Definition at line 253 of file FileIOFilter.cpp.
References CC_FERR_CONSOLE_ERROR, CC_FERR_NO_ERROR, DisplayErrorMessage(), e, CVLog::Error(), filename, ccHObject::getChild(), ccHObject::getChildrenNumber(), ccObject::getName(), IncreaseSesionCounter(), CVLog::Print(), ccHObject::removeAllChildren(), result, FileIOFilter::LoadParameters::sessionStart, ccObject::setBaseName(), ccObject::setFullPath(), ccObject::setName(), and CVLog::Warning().
Referenced by MainWindow::addToDB(), define_qcc_io(), JsonRPCPlugin::execute(), ccCommandLineParser::importFile(), ccGuiPythonInstance::loadFile(), PhotoScanFilter::loadFile(), IcmFilter::loadFile(), PovFilter::loadFile(), MainWindow::loadFile(), LoadFromFile(), and ReadCloud().
Register()
void FileIOFilter::Register (Shared filter) static
Registers a new filter.
Definition at line 167 of file FileIOFilter.cpp.
References s_ioFilters, and CVLog::Warning().
Referenced by ccPluginManager::loadPlugins().
ResetSesionCounter()
void FileIOFilter::ResetSesionCounter () static
Indicates to the I/O filters that a new loading/saving session has started (for "Apply all" buttons for instance)
Definition at line 140 of file FileIOFilter.cpp.
References s_sessionCounter.
Referenced by MainWindow::addToDB(), cloudViewer::io::AutoReadEntity(), cloudViewer::io::AutoWriteEntity(), and masc::Tools::LoadFile().
SaveToFile() [1/2]
CC_FILE_ERROR FileIOFilter::SaveToFile (ccHObject * entities, const QString & filename, const SaveParameters & parameters, const QString & fileFilter) static
Saves an entity (or a group of) to a specific file thanks to a given filter Shortcut to the other version of FileIOFilter::SaveToFile
Parameters
entities entity to save (can be a group of other entities)
filename filename
parameters saving parameters
fileFilter output filter 'file filter'
Returns
error type (if any)
Definition at line 408 of file FileIOFilter.cpp.
References CC_FERR_BAD_ARGUMENT, CC_FERR_UNKNOWN_FILE, CVLog::Error(), filename, GetFilter(), and SaveToFile().
SaveToFile() [2/2]
CC_FILE_ERROR FileIOFilter::SaveToFile (ccHObject * entities, const QString & filename, const SaveParameters & parameters, Shared filter) static
Saves an entity (or a group of) to a specific file thanks to a given filter Shortcut to FileIOFilter::saveFile
Parameters
entities entity to save (can be a group of other entities)
filename filename
parameters saving parameters
filter output filter
Returns
error type (if any)
Definition at line 377 of file FileIOFilter.cpp.
References CC_FERR_BAD_ARGUMENT, CC_FERR_CONSOLE_ERROR, CC_FERR_NO_ERROR, DisplayErrorMessage(), filename, CVLog::Print(), result, and CVLog::Warning().
Referenced by define_qcc_io(), ccCommandLineParser::exportEntity(), cvSelectionExporter::saveObjectToFileWithDialog(), SaveToFile(), and PovFilter::saveToFile().
saveToFile()
virtual CC_FILE_ERROR FileIOFilter::saveToFile (ccHObject * entity, const QString & filename, const SaveParameters & parameters) inline virtual
Saves an entity (or a group of) to a file.
This method must be implemented by children classes.
Parameters
entity entity (or group of) to save
filename filename
parameters generic saving parameters
Returns
error
Reimplemented in LASFilter, LasIOFilter, LASFWFFilter, FBXFilter, E57Filter, DRCFilter, SimpleBinFilter, MascaretFilter, MAFilter, HeightProfileFilter, SinusxFilter, SalomeHydroFilter, PVFilter, PovFilter, PNFilter, VTKFilter, STLFilter, PlyFilter, OFFFilter, ObjFilter, ImageFileFilter, DxfFilter, DepthMapFileFilter, BinFilter, AsciiFilter, and PcdFilter.
Definition at line 141 of file FileIOFilter.h.
References CC_FERR_NOT_IMPLEMENTED, and filename.
setExportFileFilterStrings()
void FileIOFilter::setExportFileFilterStrings (const QStringList & filterStrings) protected
Allow export filter strings to be set after construction (e.g. for ImageFileFilter & QImageReader::supportedImageFormats())
Definition at line 90 of file FileIOFilter.cpp.
References FileIOFilter::FilterInfo::exportFileFilterStrings.
setImportExtensions()
void FileIOFilter::setImportExtensions (const QStringList & extensions) protected
Allow import extensions to be set after construction (e.g. for ImageFileFilter & QImageReader::supportedImageFormats())
Definition at line 81 of file FileIOFilter.cpp.
References FileIOFilter::FilterInfo::importExtensions.
setImportFileFilterStrings()
void FileIOFilter::setImportFileFilterStrings (const QStringList & filterStrings) protected
Allow import filter strings to be set after construction (e.g. for ImageFileFilter & QImageReader::supportedImageFormats())
Definition at line 85 of file FileIOFilter.cpp.
References FileIOFilter::FilterInfo::importFileFilterStrings.
unregister()
virtual void FileIOFilter::unregister () inline virtual
Called when the filter is unregistered.
Does nothing by default
Definition at line 296 of file FileIOFilter.h.
UnregisterAll()
void FileIOFilter::UnregisterAll () static
Unregisters all filters.
Should be called at the end of the application
Definition at line 204 of file FileIOFilter.cpp.
References s_ioFilters.
Referenced by main().
Member Data Documentation
DEFAULT_PRIORITY
constexpr float FileIOFilter::DEFAULT_PRIORITY = 25.0f static constexpr protected
Definition at line 313 of file FileIOFilter.h.
Referenced by Assimp3DMax::Assimp3DMax(), AssimpBlender::AssimpBlender(), AssimpCollada::AssimpCollada(), AssimpCommonFilter::AssimpCommonFilter(), AssimpGltf::AssimpGltf(), AssimpIfc::AssimpIfc(), BundlerFilter::BundlerFilter(), CSVMatrixFilter::CSVMatrixFilter(), DepthMapFileFilter::DepthMapFileFilter(), IcmFilter::IcmFilter(), LASFilter::LASFilter(), MAFilter::MAFilter(), MascaretFilter::MascaretFilter(), PDMSFilter::PDMSFilter(), PNFilter::PNFilter(), PovFilter::PovFilter(), PVFilter::PVFilter(), RDBFilter::RDBFilter(), SalomeHydroFilter::SalomeHydroFilter(), SinusxFilter::SinusxFilter(), SoiFilter::SoiFilter(), and STEPFilter::STEPFilter().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_io/include/FileIOFilter.h
/root/ACloudViewer/libs/CV_io/src/FileIOFilter.cpp