ACloudViewer: cloudViewer::visualization::rendering::FilamentRenderToBuffer Class Reference
cloudViewer::visualization::rendering::FilamentRenderToBuffer Class Reference
#include <FilamentRenderToBuffer.h>
Public Member Functions
FilamentRenderToBuffer (filament::Engine &engine)
~FilamentRenderToBuffer () override
void Configure (const View *view, Scene *scene, int width, int height, int n_channels, bool depth_image, BufferReadyCallback cb) override
void SetDimensions (std::uint32_t width, std::uint32_t height) override
View & GetView () override
void Render () override
void RenderTick ()
Public Member Functions inherited from cloudViewer::visualization::rendering::RenderToBuffer
virtual ~RenderToBuffer ()=default
void SetCleanupCallback (std::function< void(RenderToBuffer *)> cb)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::rendering::RenderToBuffer
using BufferReadyCallback = std::function< void(const Buffer &)>
Protected Attributes inherited from cloudViewer::visualization::rendering::RenderToBuffer
std::function< void(RenderToBuffer *)> cleanup_callback_
Detailed Description
Definition at line 29 of file FilamentRenderToBuffer.h.
Constructor & Destructor Documentation
FilamentRenderToBuffer()
cloudViewer::visualization::rendering::FilamentRenderToBuffer::FilamentRenderToBuffer (filament::Engine & engine) explicit
Definition at line 46 of file FilamentRenderToBuffer.cpp.
~FilamentRenderToBuffer()
cloudViewer::visualization::rendering::FilamentRenderToBuffer::~FilamentRenderToBuffer () override
Definition at line 51 of file FilamentRenderToBuffer.cpp.
Member Function Documentation
Configure()
void cloudViewer::visualization::rendering::FilamentRenderToBuffer::Configure (const View * view, Scene * scene, int width, int height, int n_channels, bool depth_image, BufferReadyCallback cb) override virtual
Implements cloudViewer::visualization::rendering::RenderToBuffer.
Definition at line 65 of file FilamentRenderToBuffer.cpp.
References height, LogDebug, LogWarning, SetDimensions(), cloudViewer::visualization::rendering::FilamentView::SetScene(), and width.
GetView()
View & cloudViewer::visualization::rendering::FilamentRenderToBuffer::GetView () override virtual
Implements cloudViewer::visualization::rendering::RenderToBuffer.
Definition at line 155 of file FilamentRenderToBuffer.cpp.
Render()
void cloudViewer::visualization::rendering::FilamentRenderToBuffer::Render () override virtual
Implements cloudViewer::visualization::rendering::RenderToBuffer.
Definition at line 177 of file FilamentRenderToBuffer.cpp.
References format, cloudViewer::visualization::rendering::FilamentView::GetNativeView(), cloudViewer::visualization::rendering::FilamentScene::HideRefractedMaterials(), cloudViewer::visualization::rendering::ReadPixelsCallback(), and type.
RenderTick()
void cloudViewer::visualization::rendering::FilamentRenderToBuffer::RenderTick ()
Definition at line 208 of file FilamentRenderToBuffer.cpp.
SetDimensions()
void cloudViewer::visualization::rendering::FilamentRenderToBuffer::SetDimensions (std::uint32_t width, std::uint32_t height) override virtual
Implements cloudViewer::visualization::rendering::RenderToBuffer.
Definition at line 112 of file FilamentRenderToBuffer.cpp.
References height, cloudViewer::visualization::rendering::FilamentView::SetViewport(), and width.
Referenced by Configure().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentRenderToBuffer.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentRenderToBuffer.cpp