ACloudViewer: cloudViewer::GenericIndexedMesh Class Reference
cloudViewer::GenericIndexedMesh Class Reference abstract
A generic mesh with index-based vertex access.
#include <GenericIndexedMesh.h>
Public Member Functions
GenericIndexedMesh ()=default
~GenericIndexedMesh () override=default
Default destructor.
virtual GenericTriangle * _getTriangle (unsigned triangleIndex)=0
Returns the ith triangle.
virtual VerticesIndexes * getTriangleVertIndexes (unsigned triangleIndex)=0
Returns the indexes of the vertices of a given triangle.
virtual void getTriangleVertices (unsigned triangleIndex, CCVector3 &A, CCVector3 &B, CCVector3 &C) const =0
Returns the vertices of a given triangle.
virtual void getTriangleVertices (unsigned triangleIndex, double A[3], double B[3], double C[3]) const =0
virtual VerticesIndexes * getNextTriangleVertIndexes ()=0
virtual bool normalsAvailable () const
Returns whether normals are available.
virtual bool interpolateNormals (unsigned triIndex, const CCVector3 &P, CCVector3 &N)
Interpolates normal(s) inside a given triangle.
Public Member Functions inherited from cloudViewer::GenericMesh
GenericMesh ()=default
virtual ~GenericMesh ()=default
Default destructor.
virtual unsigned size () const =0
Returns the number of triangles.
virtual bool hasTriangles () const
virtual void forEach (genericTriangleAction action)=0
Fast iteration mechanism.
virtual void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax)=0
Returns the mesh bounding-box.
virtual void placeIteratorAtBeginning ()=0
Places the mesh iterator at the beginning.
virtual GenericTriangle * _getNextTriangle ()=0
Returns the next triangle (relatively to the global iterator position)
Additional Inherited Members
Public Types inherited from cloudViewer::GenericMesh
enum class SimplificationContraction { Average , Quadric }
Indicates the method that is used for mesh simplification if multiple vertices are combined to a single one.
enum class FilterScope { All , Color , Normal , Vertex }
Indicates the scope of filter operations.
enum class DeformAsRigidAsPossibleEnergy { Spokes , Smoothed }
using genericTriangleAction = std::function< void(GenericTriangle &)>
Generic function to apply to a triangle (used by foreach)
Detailed Description
A generic mesh with index-based vertex access.
Implements the GenericMehs interface.
Definition at line 37 of file GenericIndexedMesh.h.
Constructor & Destructor Documentation
GenericIndexedMesh()
cloudViewer::GenericIndexedMesh::GenericIndexedMesh () default
~GenericIndexedMesh()
cloudViewer::GenericIndexedMesh::~GenericIndexedMesh () override default
Default destructor.
Member Function Documentation
_getTriangle()
virtual GenericTriangle* cloudViewer::GenericIndexedMesh::_getTriangle (unsigned triangleIndex) pure virtual
Returns the ith triangle.
Virtual method to request a triangle with a specific index. The returned object can be temporary.
Parameters
triangleIndex of the requested triangle (between 0 and the mesh size-1)
Returns
the requested triangle, or 0 if index value is not valid
Implemented in ccMesh, cloudViewer::SimpleMesh, cloudViewer::Delaunay2dMesh, ccSubMesh, and ccMeshGroup.
Referenced by ccGenericMesh::computeInterpolationWeights(), and define_GenericIndexedMesh().
getNextTriangleVertIndexes()
virtual VerticesIndexes* cloudViewer::GenericIndexedMesh::getNextTriangleVertIndexes () pure virtual
Returns the indexes of the vertices of the next triangle (relatively to the global iterator position)
Returns
the triangle indexes (or 0 if the global iterator is out of bounds)
Implemented in ccSubMesh, ccMeshGroup, ccMesh, cloudViewer::SimpleMesh, and cloudViewer::Delaunay2dMesh.
Referenced by cloudViewer::MeshSamplingTools::buildMeshEdgeUsageMap(), ccMesh::ccMesh(), define_GenericIndexedMesh(), STLFilter::saveToASCIIFile(), STLFilter::saveToBINFile(), ObjFilter::saveToFile(), MAFilter::saveToFile(), and cloudViewer::ManualSegmentationTools::segmentMesh().
getTriangleVertices() [1/2]
virtual void cloudViewer::GenericIndexedMesh::getTriangleVertices (unsigned triangleIndex, CCVector3 & A, CCVector3 & B, CCVector3 & C) const pure virtual
Returns the vertices of a given triangle.
Parameters
[in] triangleIndex index of the triangle (between 0 and the size(mesh)-1)
[out] A first vertex
[out] B second vertex
[out] C third vertex
Implemented in ccSubMesh, ccMeshGroup, ccMesh, cloudViewer::SimpleMesh, and cloudViewer::Delaunay2dMesh.
Referenced by ComparePointsAndTriangles(), ccGenericMesh::computePointPosition(), and ccGenericMesh::trianglePicking().
getTriangleVertices() [2/2]
virtual void cloudViewer::GenericIndexedMesh::getTriangleVertices (unsigned triangleIndex, double A[3], double B[3], double C[3]) const pure virtual
Implemented in ccSubMesh, ccMeshGroup, ccMesh, cloudViewer::SimpleMesh, and cloudViewer::Delaunay2dMesh.
getTriangleVertIndexes()
virtual VerticesIndexes* cloudViewer::GenericIndexedMesh::getTriangleVertIndexes (unsigned triangleIndex) pure virtual
Returns the indexes of the vertices of a given triangle.
Parameters
triangleIndex index of the triangle (between 0 and size(mesh)-1)
Returns
the triangle indexes (or 0 if index value is not valid)
Implemented in ccSubMesh, ccMeshGroup, ccMesh, cloudViewer::SimpleMesh, and cloudViewer::Delaunay2dMesh.
Referenced by ccNormalVectors::ComputeNormalWithTri(), ccCropTool::Crop(), cc2smReader::getPclCloud2(), cc2smReader::getPclMesh(), cc2smReader::getPclTextureMesh(), cc2smReader::getVtkPolyDataFromMeshCloud(), cc2smReader::getVtkPolyDataWithTextures(), MergeOldTriangles(), ecvDisplayTools::ProcessPickingResult(), OFFFilter::saveToFile(), cloudViewer::ManualSegmentationTools::segmentMeshWithAABox(), cloudViewer::ManualSegmentationTools::segmentMeshWithAAPlane(), ToFbxMesh(), and VtkUtils::TableModel::updateData().
interpolateNormals()
virtual bool cloudViewer::GenericIndexedMesh::interpolateNormals (unsigned triIndex, const CCVector3 & P, CCVector3 & N) inline virtual
Interpolates normal(s) inside a given triangle.
This method should be ideally overriden by the child class if normals are supported
Parameters
[in] triIndex triangle index
[in] P point where to interpolate (should be inside the triangle!)
[out] N interpolated normal
Returns
success
Reimplemented in ccSubMesh, ccMeshGroup, ccMesh, and cloudViewer::SimpleMesh.
Definition at line 89 of file GenericIndexedMesh.h.
Referenced by ccGenericMesh::samplePoints().
normalsAvailable()
virtual bool cloudViewer::GenericIndexedMesh::normalsAvailable () const inline virtual
Returns whether normals are available.
Reimplemented in ccMesh, ccGenericMesh, and cloudViewer::SimpleMesh.
Definition at line 80 of file GenericIndexedMesh.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/GenericIndexedMesh.h