ACloudViewer: ccLineationTool Class Reference
ccLineationTool Class Reference
#include <ccLineationTool.h>
Public Member Functions
ccLineationTool ()
virtual ~ccLineationTool ()
void toolDisactivated () override
void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccPointCloud *cloud, const CCVector3 &P) override
void accept () override
void cancel () override
Public Member Functions inherited from ccTool
virtual ~ccTool ()
void initializeTool (ecvMainAppInterface *app)
virtual void toolActivated ()
virtual void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccHObject *pickedObject, const CCVector3 &P)
virtual void onNewSelection (const ccHObject::Container &selectedEntities)
virtual bool canUndo ()
virtual void undo ()
Protected Attributes
int m_lineation_id = -1
Protected Attributes inherited from ccTool
ecvMainAppInterface * m_app
QWidget * m_window
Additional Inherited Members
Protected Member Functions inherited from ccTool
ccTool ()
Detailed Description
Definition at line 16 of file ccLineationTool.h.
Constructor & Destructor Documentation
ccLineationTool()
ccLineationTool::ccLineationTool ()
Definition at line 12 of file ccLineationTool.cpp.
~ccLineationTool()
ccLineationTool::~ccLineationTool () virtual
Definition at line 14 of file ccLineationTool.cpp.
Member Function Documentation
accept()
void ccLineationTool::accept () override virtual
Reimplemented from ccTool.
Definition at line 63 of file ccLineationTool.cpp.
References cancel().
cancel()
void ccLineationTool::cancel () override virtual
Reimplemented from ccTool.
Definition at line 68 of file ccLineationTool.cpp.
References ccTool::m_app, m_lineation_id, and cloudViewer::ReferenceCloud::size().
Referenced by accept(), and toolDisactivated().
pointPicked()
void ccLineationTool::pointPicked (ccHObject * insertPoint, unsigned itemIdx, ccPointCloud * cloud, const CCVector3 & P) override virtual
Reimplemented from ccTool.
Definition at line 20 of file ccLineationTool.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), ccCompass::drawName, ccObject::getName(), ccObject::getUniqueID(), ccTool::m_app, m_lineation_id, ccObject::setName(), ccDrawableObject::setVisible(), ccDrawableObject::showNameIn3D(), cloudViewer::ReferenceCloud::size(), and ccLineation::updateMetadata().
toolDisactivated()
void ccLineationTool::toolDisactivated () override virtual
Reimplemented from ccTool.
Definition at line 17 of file ccLineationTool.cpp.
References cancel().
Member Data Documentation
m_lineation_id
int ccLineationTool::m_lineation_id = -1 protected
Definition at line 38 of file ccLineationTool.h.
Referenced by cancel(), and pointPicked().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCompass/include/ccLineationTool.h
/root/ACloudViewer/plugins/core/Standard/qCompass/src/ccLineationTool.cpp