ACloudViewer: cloudViewer::visualization::rendering::TPointCloudBuffersBuilder Class Reference
cloudViewer::visualization::rendering::TPointCloudBuffersBuilder Class Reference
#include <FilamentGeometryBuffersBuilder.h>
Public Member Functions
TPointCloudBuffersBuilder (const t::geometry::PointCloud &geometry)
filament::RenderableManager::PrimitiveType GetPrimitiveType () const override
Buffers ConstructBuffers () override
filament::Box ComputeAABB () override
Public Member Functions inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
virtual ~GeometryBuffersBuilder ()=default
virtual void SetDownsampleThreshold (size_t min_points)
virtual void SetWideLines ()
virtual void SetAdjustColorsForSRGBToneMapping (bool adjust)
Protected Attributes
t::geometry::PointCloud geometry_
Protected Attributes inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
size_t downsample_threshold_ = SIZE_MAX
bool wide_lines_ = false
bool adjust_colors_for_srgb_tonemapping_ = true
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
using Buffers = std::tuple< VertexBufferHandle, IndexBufferHandle, IndexBufferHandle >
using IndexType = std::uint32_t
Static Public Member Functions inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
static std::unique_ptr< GeometryBuffersBuilder > GetBuilder (const ccHObject &geometry)
static std::unique_ptr< GeometryBuffersBuilder > GetBuilder (const t::geometry::Geometry &geometry)
Static Protected Member Functions inherited from cloudViewer::visualization::rendering::GeometryBuffersBuilder
static void DeallocateBuffer (void *buffer, size_t size, void *user_ptr)
static IndexBufferHandle CreateIndexBuffer (size_t max_index, size_t n_subsamples=SIZE_MAX)
Detailed Description
Definition at line 168 of file FilamentGeometryBuffersBuilder.h.
Constructor & Destructor Documentation
TPointCloudBuffersBuilder()
cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::TPointCloudBuffersBuilder (const t::geometry::PointCloud & geometry) explicit
Definition at line 281 of file PointCloudBuffers.cpp.
References colors, cloudViewer::core::Float32, geometry_, cloudViewer::core::Tensor::GetDtype(), cloudViewer::t::geometry::PointCloud::GetPointColors(), cloudViewer::t::geometry::PointCloud::GetPointNormals(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointColors(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), LogWarning, normals, cloudViewer::t::geometry::PointCloud::To(), cloudViewer::core::Tensor::To(), and cloudViewer::core::UInt8.
Member Function Documentation
ComputeAABB()
filament::Box cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::ComputeAABB () override virtual
Implements cloudViewer::visualization::rendering::GeometryBuffersBuilder.
Definition at line 460 of file PointCloudBuffers.cpp.
References geometry_, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::t::geometry::PointCloud::GetMaxBound(), and cloudViewer::t::geometry::PointCloud::GetMinBound().
ConstructBuffers()
GeometryBuffersBuilder::Buffers cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::ConstructBuffers () override virtual
Implements cloudViewer::visualization::rendering::GeometryBuffersBuilder.
Reimplemented in cloudViewer::visualization::rendering::TGaussianSplatBuffersBuilder.
Definition at line 329 of file PointCloudBuffers.cpp.
References cloudViewer::t::geometry::TensorMap::Contiguous(), cloudViewer::visualization::rendering::GeometryBuffersBuilder::CreateIndexBuffer(), cloudViewer::visualization::rendering::GeometryBuffersBuilder::DeallocateBuffer(), cloudViewer::visualization::rendering::GeometryBuffersBuilder::downsample_threshold_, float, geometry_, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::visualization::rendering::EngineInstance::GetInstance(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointColors(), cloudViewer::t::geometry::PointCloud::GetPointNormals(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::visualization::rendering::EngineInstance::GetResourceManager(), cloudViewer::t::geometry::PointCloud::HasPointAttr(), cloudViewer::t::geometry::PointCloud::HasPointColors(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), normals, points, and cloudViewer::visualization::rendering::VertexBuffer.
GetPrimitiveType()
RenderableManager::PrimitiveType cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::GetPrimitiveType () const override virtual
Implements cloudViewer::visualization::rendering::GeometryBuffersBuilder.
Definition at line 324 of file PointCloudBuffers.cpp.
Member Data Documentation
geometry_
t::geometry::PointCloud cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::geometry_ protected
Definition at line 179 of file FilamentGeometryBuffersBuilder.h.
Referenced by ComputeAABB(), ConstructBuffers(), cloudViewer::visualization::rendering::TGaussianSplatBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TGaussianSplatBuffersBuilder::TGaussianSplatBuffersBuilder(), and TPointCloudBuffersBuilder().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentGeometryBuffersBuilder.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/PointCloudBuffers.cpp