ACloudViewer: CustomVtkCaptionWidget Class Reference
CustomVtkCaptionWidget Class Reference
#include <CustomVtkCaptionWidget.h>
Public Member Functions
vtkTypeMacro (CustomVtkCaptionWidget, vtkCaptionWidget)
void SetHandleEnabled (bool state)
void SetAssociatedLabel (cc2DLabel *label)
Set the associated cc2DLabel for selection notification.
cc2DLabel * GetAssociatedLabel () const
Get the associated cc2DLabel.
Static Public Member Functions
static CustomVtkCaptionWidget * New ()
Protected Member Functions
CustomVtkCaptionWidget ()
~CustomVtkCaptionWidget () override
Static Protected Member Functions
static void OnWidgetInteraction (vtkObject *caller, unsigned long eventId, void *clientData, void *callData)
Callback for widget interaction events.
Protected Attributes
cc2DLabel * m_associatedLabel
vtkSmartPointer< vtkCallbackCommand > m_interactionCallback
Detailed Description
Definition at line 25 of file CustomVtkCaptionWidget.h.
Constructor & Destructor Documentation
CustomVtkCaptionWidget()
CustomVtkCaptionWidget::CustomVtkCaptionWidget () protected
Definition at line 28 of file CustomVtkCaptionWidget.cpp.
References m_interactionCallback, and OnWidgetInteraction().
~CustomVtkCaptionWidget()
CustomVtkCaptionWidget::~CustomVtkCaptionWidget () override protected
Definition at line 43 of file CustomVtkCaptionWidget.cpp.
References m_associatedLabel, and m_interactionCallback.
Member Function Documentation
GetAssociatedLabel()
cc2DLabel* CustomVtkCaptionWidget::GetAssociatedLabel () const inline
Get the associated cc2DLabel.
Definition at line 37 of file CustomVtkCaptionWidget.h.
New()
static CustomVtkCaptionWidget* CustomVtkCaptionWidget::New () static
OnWidgetInteraction()
void CustomVtkCaptionWidget::OnWidgetInteraction (vtkObject * caller, unsigned long eventId, void * clientData, void * callData) static protected
Callback for widget interaction events.
Definition at line 61 of file CustomVtkCaptionWidget.cpp.
References ecvDisplayTools::m_deferredPickingTimer, ecvDisplayTools::m_widgetClicked, and ecvDisplayTools::TheInstance().
Referenced by CustomVtkCaptionWidget().
SetAssociatedLabel()
void CustomVtkCaptionWidget::SetAssociatedLabel (cc2DLabel * label)
Set the associated cc2DLabel for selection notification.
Definition at line 57 of file CustomVtkCaptionWidget.cpp.
References m_associatedLabel.
SetHandleEnabled()
void CustomVtkCaptionWidget::SetHandleEnabled (bool state)
Definition at line 51 of file CustomVtkCaptionWidget.cpp.
vtkTypeMacro()
CustomVtkCaptionWidget::vtkTypeMacro (CustomVtkCaptionWidget , vtkCaptionWidget)
Member Data Documentation
m_associatedLabel
cc2DLabel* CustomVtkCaptionWidget::m_associatedLabel protected
Definition at line 49 of file CustomVtkCaptionWidget.h.
Referenced by SetAssociatedLabel(), and ~CustomVtkCaptionWidget().
m_interactionCallback
vtkSmartPointer<vtkCallbackCommand> CustomVtkCaptionWidget::m_interactionCallback protected
Definition at line 50 of file CustomVtkCaptionWidget.h.
Referenced by CustomVtkCaptionWidget(), and ~CustomVtkCaptionWidget().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Widgets/CustomVtkCaptionWidget.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Widgets/CustomVtkCaptionWidget.cpp