ACloudViewer: cloudViewer::visualization::gui::StackedWidget Class Reference
cloudViewer::visualization::gui::StackedWidget Class Reference
#include <StackedWidget.h>
Classes
struct Impl
Public Member Functions
StackedWidget ()
virtual ~StackedWidget ()
void SetSelectedIndex (int index)
Sets the index of the child to draw.
int GetSelectedIndex () const
Returns the index of the selected child.
Size CalcPreferredSize (const LayoutContext &context, const Constraints &constraints) const override
void Layout (const LayoutContext &context) override
Widget::DrawResult Draw (const DrawContext &context) override
Public Member Functions inherited from cloudViewer::visualization::gui::Widget
Widget ()
Widget (const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Widget ()
virtual void AddChild (std::shared_ptr< Widget > child)
virtual const std::vector< std::shared_ptr< Widget > > GetChildren () const
virtual const Rect & GetFrame () const
Returns the frame size in pixels.
virtual void SetFrame (const Rect &f)
virtual const Color & GetBackgroundColor () const
virtual bool IsDefaultBackgroundColor () const
virtual void SetBackgroundColor (const Color &color)
virtual bool IsVisible () const
virtual void SetVisible (bool vis)
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
virtual void SetTooltip (const char *text)
virtual const char * GetTooltip () const
virtual Size CalcMinimumSize (const LayoutContext &context) const
virtual EventResult Mouse (const MouseEvent &e)
virtual EventResult Key (const KeyEvent &e)
virtual DrawResult Tick (const TickEvent &e)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::gui::Widget
enum class DrawResult { NONE , REDRAW , RELAYOUT }
enum class EventResult { IGNORED , CONSUMED , DISCARD }
Static Public Attributes inherited from cloudViewer::visualization::gui::Widget
static constexpr int DIM_GROW = 10000
Protected Member Functions inherited from cloudViewer::visualization::gui::Widget
void DrawImGuiPushEnabledState ()
void DrawImGuiPopEnabledState ()
void DrawImGuiTooltip ()
Detailed Description
Stacks its children on top of each other, with only the selected child showing. It is like a tab control without the tabs.
Definition at line 18 of file StackedWidget.h.
Constructor & Destructor Documentation
StackedWidget()
cloudViewer::visualization::gui::StackedWidget::StackedWidget ()
Definition at line 20 of file StackedWidget.cpp.
~StackedWidget()
cloudViewer::visualization::gui::StackedWidget::~StackedWidget () virtual
Definition at line 22 of file StackedWidget.cpp.
Member Function Documentation
CalcPreferredSize()
Size cloudViewer::visualization::gui::StackedWidget::CalcPreferredSize (const LayoutContext & context, const Constraints & constraints) const override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 30 of file StackedWidget.cpp.
References context, cloudViewer::visualization::gui::Widget::GetChildren(), max(), and size.
Draw()
Widget::DrawResult cloudViewer::visualization::gui::StackedWidget::Draw (const DrawContext & context) override virtual
Draws the widget. If this is a Dear ImGUI widget, this is where the actual event processing happens. Return NONE if no action needs to be taken, REDRAW if the widget needs to be redrawn (e.g. its value changed), and RELAYOUT if the widget wishes to change size.
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 50 of file StackedWidget.cpp.
References context, cloudViewer::visualization::gui::Widget::GetChildren(), cloudViewer::visualization::gui::Widget::NONE, and size.
GetSelectedIndex()
int cloudViewer::visualization::gui::StackedWidget::GetSelectedIndex () const
Returns the index of the selected child.
Definition at line 28 of file StackedWidget.cpp.
Layout()
void cloudViewer::visualization::gui::StackedWidget::Layout (const LayoutContext & context) override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 41 of file StackedWidget.cpp.
References context, frame, cloudViewer::visualization::gui::Widget::GetChildren(), cloudViewer::visualization::gui::Widget::GetFrame(), and cloudViewer::visualization::gui::Widget::Layout().
SetSelectedIndex()
void cloudViewer::visualization::gui::StackedWidget::SetSelectedIndex (int index)
Sets the index of the child to draw.
Definition at line 24 of file StackedWidget.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/StackedWidget.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/StackedWidget.cpp