ACloudViewer: cloudViewer::t::io::CharVector Class Reference
cloudViewer::t::io::CharVector Class Reference
Public Member Functions
CharVector ()
CharVector (size_t size)
CharVector (size_t size, const char value)
template<typename T >
CharVector & Append (const T &rhs)
CharVector & Append (const std::string &rhs)
CharVector & Append (const char *rhs)
template<typename InputIt >
CharVector & Append (InputIt first, InputIt last)
template<typename T >
CharVector & Append (size_t count, const T &value)
CharVector & Append (const CharVector &other)
std::vector< char >::iterator Begin ()
std::vector< char >::iterator End ()
size_t Size () const
void Resize (size_t count)
char * Data ()
const char * Data () const
char & operator[] (size_t index)
const char & operator[] (size_t index) const
Detailed Description
Definition at line 54 of file NumpyIO.cpp.
Constructor & Destructor Documentation
CharVector() [1/3]
cloudViewer::t::io::CharVector::CharVector () inline
Definition at line 56 of file NumpyIO.cpp.
CharVector() [2/3]
cloudViewer::t::io::CharVector::CharVector (size_t size) inline
Definition at line 57 of file NumpyIO.cpp.
CharVector() [3/3]
cloudViewer::t::io::CharVector::CharVector (size_t size, const char value) inline
Definition at line 58 of file NumpyIO.cpp.
Member Function Documentation
Append() [1/6]
CharVector& cloudViewer::t::io::CharVector::Append (const char * rhs) inline
Definition at line 77 of file NumpyIO.cpp.
Append() [2/6]
CharVector& cloudViewer::t::io::CharVector::Append (const CharVector & other) inline
Definition at line 101 of file NumpyIO.cpp.
Append() [3/6]
CharVector& cloudViewer::t::io::CharVector::Append (const std::string & rhs) inline
Definition at line 72 of file NumpyIO.cpp.
Append() [4/6]
template<typename T > CharVector& cloudViewer::t::io::CharVector::Append (const T & rhs) inline
Definition at line 61 of file NumpyIO.cpp.
Referenced by Append(), cloudViewer::t::io::CreateNumpyHeader(), cloudViewer::t::io::WriteNpzEmpty(), and cloudViewer::t::io::WriteNpzOneTensor().
Append() [5/6]
template<typename InputIt > CharVector& cloudViewer::t::io::CharVector::Append (InputIt first, InputIt last) inline
Definition at line 88 of file NumpyIO.cpp.
Append() [6/6]
template<typename T > CharVector& cloudViewer::t::io::CharVector::Append (size_t count, const T & value) inline
Definition at line 94 of file NumpyIO.cpp.
References Append(), and count.
Begin()
std::vector<char>::iterator cloudViewer::t::io::CharVector::Begin () inline
Definition at line 107 of file NumpyIO.cpp.
Referenced by cloudViewer::t::io::ReadNpz(), and cloudViewer::t::io::WriteNpzOneTensor().
Data() [1/2]
char* cloudViewer::t::io::CharVector::Data () inline
Definition at line 115 of file NumpyIO.cpp.
Referenced by cloudViewer::t::io::CreateNumpyArrayFromCompressedFile(), cloudViewer::t::io::ParseNpyHeaderFromFile(), cloudViewer::t::io::ParseZipFooter(), cloudViewer::t::io::ReadNpz(), cloudViewer::t::io::NumpyArray::Save(), cloudViewer::t::io::WriteNpzEmpty(), and cloudViewer::t::io::WriteNpzOneTensor().
Data() [2/2]
const char* cloudViewer::t::io::CharVector::Data () const inline
Definition at line 117 of file NumpyIO.cpp.
End()
std::vector<char>::iterator cloudViewer::t::io::CharVector::End () inline
Definition at line 109 of file NumpyIO.cpp.
Referenced by cloudViewer::t::io::ReadNpz().
operator[]() [1/2]
char& cloudViewer::t::io::CharVector::operator[] (size_t index) inline
Definition at line 119 of file NumpyIO.cpp.
operator[]() [2/2]
const char& cloudViewer::t::io::CharVector::operator[] (size_t index) const inline
Definition at line 121 of file NumpyIO.cpp.
Resize()
void cloudViewer::t::io::CharVector::Resize (size_t count) inline
Definition at line 113 of file NumpyIO.cpp.
References count.
Referenced by cloudViewer::t::io::WriteNpzOneTensor().
Size()
size_t cloudViewer::t::io::CharVector::Size () const inline
Definition at line 111 of file NumpyIO.cpp.
Referenced by cloudViewer::t::io::CreateNumpyHeader(), cloudViewer::t::io::NumpyArray::Save(), cloudViewer::t::io::WriteNpzEmpty(), and cloudViewer::t::io::WriteNpzOneTensor().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/t/io/NumpyIO.cpp