ACloudViewer: PointCloudWrapper< Real > Class Template Reference
PointCloudWrapper< Real > Class Template Reference
Public Member Functions
PointCloudWrapper (const ccPointCloud &cloud)
virtual size_t size () const
virtual bool hasNormals () const
virtual bool hasColors () const
virtual void getPoint (size_t index, Real *coords) const
virtual void getNormal (size_t index, Real *coords) const
virtual void getColor (size_t index, Real *rgb) const
Protected Attributes
const ccPointCloud & m_cloud
Detailed Description
template<typename Real>
class PointCloudWrapper< Real >
Definition at line 39 of file qPoissonRecon.cpp.
Constructor & Destructor Documentation
PointCloudWrapper()
template<typename Real > PointCloudWrapper< Real >::PointCloudWrapper (const ccPointCloud & cloud) inline explicit
Definition at line 41 of file qPoissonRecon.cpp.
Member Function Documentation
getColor()
template<typename Real > virtual void PointCloudWrapper< Real >::getColor (size_t index, Real * rgb) const inline virtual
Implements PoissonReconLib::ICloud< Real >.
Definition at line 71 of file qPoissonRecon.cpp.
References color, ccPointCloud::getPointColor(), ccPointCloud::hasColors(), PointCloudWrapper< Real >::m_cloud, rgb, and cloudViewer::PointCloudTpl< T >::size().
getNormal()
template<typename Real > virtual void PointCloudWrapper< Real >::getNormal (size_t index, Real * coords) const inline virtual
Implements PoissonReconLib::ICloud< Real >.
Definition at line 58 of file qPoissonRecon.cpp.
References ccPointCloud::getPointNormal(), ccPointCloud::hasNormals(), PointCloudWrapper< Real >::m_cloud, cloudViewer::PointCloudTpl< T >::size(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
getPoint()
template<typename Real > virtual void PointCloudWrapper< Real >::getPoint (size_t index, Real * coords) const inline virtual
Implements PoissonReconLib::ICloud< Real >.
Definition at line 46 of file qPoissonRecon.cpp.
References cloudViewer::PointCloudTpl< T >::getPoint(), PointCloudWrapper< Real >::m_cloud, cloudViewer::PointCloudTpl< T >::size(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
hasColors()
template<typename Real > virtual bool PointCloudWrapper< Real >::hasColors () const inline virtual
Implements PoissonReconLib::ICloud< Real >.
Definition at line 45 of file qPoissonRecon.cpp.
References ccPointCloud::hasColors(), and PointCloudWrapper< Real >::m_cloud.
hasNormals()
template<typename Real > virtual bool PointCloudWrapper< Real >::hasNormals () const inline virtual
Implements PoissonReconLib::ICloud< Real >.
Definition at line 44 of file qPoissonRecon.cpp.
References ccPointCloud::hasNormals(), and PointCloudWrapper< Real >::m_cloud.
size()
template<typename Real > virtual size_t PointCloudWrapper< Real >::size () const inline virtual
Implements PoissonReconLib::ICloud< Real >.
Definition at line 43 of file qPoissonRecon.cpp.
References PointCloudWrapper< Real >::m_cloud, and cloudViewer::PointCloudTpl< T >::size().
Member Data Documentation
m_cloud
template<typename Real > const ccPointCloud& PointCloudWrapper< Real >::m_cloud protected
Definition at line 85 of file qPoissonRecon.cpp.
Referenced by PointCloudWrapper< Real >::getColor(), PointCloudWrapper< Real >::getNormal(), PointCloudWrapper< Real >::getPoint(), PointCloudWrapper< Real >::hasColors(), PointCloudWrapper< Real >::hasNormals(), and PointCloudWrapper< Real >::size().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qPoissonRecon/src/qPoissonRecon.cpp