ACloudViewer: CurveFittingTool::CurveFitting Class Reference
CurveFittingTool::CurveFitting Class Reference
#include <CurveFitting.h>
Public Member Functions
CurveFitting ()
~CurveFitting ()
void setInputcloud (PointCloudT::Ptr input_cloud)
void grid_mean_xyz (double x_resolution, double y_resolution, std::vector< double > &x_mean, std::vector< double > &y_mean, std::vector< double > &z_mean, PointCloudT::Ptr &new_cloud)
void line_fitting (std::vector< double > x, std::vector< double > y, double &k, double &b)
void polynomial2D_fitting (std::vector< double > x, std::vector< double > y, double &a, double &b, double &c)
void polynomial3D_fitting (std::vector< double > x, std::vector< double > y, std::vector< double > z, double &a, double &b, double &c)
void getPolynomial3D (PointCloudT::Ptr outCurve, double step_=0.5)
Static Public Member Functions
static ccPolyline * BsplineFitting (const ccPointCloud &cloud)
Detailed Description
Definition at line 27 of file CurveFitting.h.
Constructor & Destructor Documentation
CurveFitting()
CurveFittingTool::CurveFitting::CurveFitting ()
Definition at line 34 of file CurveFitting.cpp.
~CurveFitting()
CurveFittingTool::CurveFitting::~CurveFitting ()
Definition at line 36 of file CurveFitting.cpp.
Member Function Documentation
BsplineFitting()
ccPolyline * CurveFittingTool::CurveFitting::BsplineFitting (const ccPointCloud & cloud) static
Definition at line 38 of file CurveFitting.cpp.
References vtk2cc::ConvertToPolyline(), cloudViewer::PointCloudTpl< T >::getPoints(), points, and result.
getPolynomial3D()
void CurveFittingTool::CurveFitting::getPolynomial3D (PointCloudT::Ptr outCurve, double step_ = 0.5)
Definition at line 204 of file CurveFitting.cpp.
References cloudViewer::utility::ceil().
grid_mean_xyz()
void CurveFittingTool::CurveFitting::grid_mean_xyz (double x_resolution, double y_resolution, std::vector< double > & x_mean, std::vector< double > & y_mean, std::vector< double > & z_mean, PointCloudT::Ptr & new_cloud)
Definition at line 75 of file CurveFitting.cpp.
References cloudViewer::utility::ceil().
line_fitting()
void CurveFittingTool::CurveFitting::line_fitting (std::vector< double > x, std::vector< double > y, double & k, double & b)
Definition at line 131 of file CurveFitting.cpp.
References A12, x, and y.
polynomial2D_fitting()
void CurveFittingTool::CurveFitting::polynomial2D_fitting (std::vector< double > x, std::vector< double > y, double & a, double & b, double & c)
Definition at line 151 of file CurveFitting.cpp.
References a, A12, x, and y.
polynomial3D_fitting()
void CurveFittingTool::CurveFitting::polynomial3D_fitting (std::vector< double > x, std::vector< double > y, std::vector< double > z, double & a, double & b, double & c)
Definition at line 173 of file CurveFitting.cpp.
References a, A12, x, y, and z.
setInputcloud()
void CurveFittingTool::CurveFitting::setInputcloud (PointCloudT::Ptr input_cloud)
Definition at line 70 of file CurveFitting.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/Common/CurveFitting.h
/root/ACloudViewer/libs/PCLEngine/Tools/Common/CurveFitting.cpp