ACloudViewer: ScaleParamsComputer Class Reference
ScaleParamsComputer Class Reference abstract
Generic parameters 'computer' class (at a given scale)
#include <ccPointDescriptor.h>
Public Member Functions
virtual ~ScaleParamsComputer ()=default
virtual unsigned getID () const =0
Returns the associated descriptor ID.
virtual QString getName () const =0
Returns the associated descriptor name.
virtual unsigned dimPerScale () const =0
Returns the number of dimensions per scale for this descriptor.
virtual bool needSF () const
Returns whether the computer requires a scalar field or not.
virtual void reset ()=0
Called once before computing parameters at first scale.
virtual bool computeScaleParams (cloudViewer::ReferenceCloud &neighbors, double radius, float params[], bool &invalidScale)=0
Computes the parameters at a given scale.
Static Public Member Functions
static ScaleParamsComputer * GetByID (unsigned descID)
Vault: returns the computer corresponding to the given ID.
static unsigned AvailableCount ()
Returns the number of available 'descriptors'.
static ScaleParamsComputer * GetByIndex (unsigned index)
Vault: returns the ith computer.
Detailed Description
Generic parameters 'computer' class (at a given scale)
Must be inherited by any custom computer.
Definition at line 43 of file ccPointDescriptor.h.
Constructor & Destructor Documentation
~ScaleParamsComputer()
virtual ScaleParamsComputer::~ScaleParamsComputer () virtual default
Member Function Documentation
AvailableCount()
unsigned ScaleParamsComputer::AvailableCount () static
Returns the number of available 'descriptors'.
Definition at line 428 of file ccPointDescriptor.cpp.
References ScaleParamsComputerVault::map, and s_vault.
Referenced by qCanupoTrainingDialog::qCanupoTrainingDialog().
computeScaleParams()
virtual bool ScaleParamsComputer::computeScaleParams (cloudViewer::ReferenceCloud & neighbors, double radius, float params[], bool & invalidScale) pure virtual
Computes the parameters at a given scale.
Scales are always called in decreasing order.
Parameters
[in] neighbors the set of neighbors at the current scale
[in] radius current radius (half scale) value
[out] params the computed parameters
[out] invalidScale whether this scale is 'invalid' (i.e. parameters couldn't be computed, default one have been returned instead)
Returns
false if an error occurred (e.g. not enough memory)
Implemented in DimensionalityScaleParamsComputer.
dimPerScale()
virtual unsigned ScaleParamsComputer::dimPerScale () const pure virtual
Returns the number of dimensions per scale for this descriptor.
Implemented in DimensionalityScaleParamsComputer.
GetByID()
ScaleParamsComputer * ScaleParamsComputer::GetByID (unsigned descID) static
Vault: returns the computer corresponding to the given ID.
Definition at line 432 of file ccPointDescriptor.cpp.
References ScaleParamsComputerVault::map, and s_vault.
Referenced by qCanupoClassifDialog::browseClassifierFile(), qCanupoProcess::Classify(), qCanupoTools::ComputeCorePointsDescriptors(), and qCanupoPlugin::doTrainAction().
GetByIndex()
ScaleParamsComputer * ScaleParamsComputer::GetByIndex (unsigned index) static
Vault: returns the ith computer.
Definition at line 442 of file ccPointDescriptor.cpp.
References ScaleParamsComputerVault::map, and s_vault.
Referenced by qCanupoTrainingDialog::qCanupoTrainingDialog().
getID()
virtual unsigned ScaleParamsComputer::getID () const pure virtual
Returns the associated descriptor ID.
Implemented in DimensionalityScaleParamsComputer.
Referenced by qCanupoTrainingDialog::qCanupoTrainingDialog().
getName()
virtual QString ScaleParamsComputer::getName () const pure virtual
Returns the associated descriptor name.
Implemented in DimensionalityScaleParamsComputer.
Referenced by qCanupoClassifDialog::browseClassifierFile(), and qCanupoTrainingDialog::qCanupoTrainingDialog().
needSF()
virtual bool ScaleParamsComputer::needSF () const inline virtual
Returns whether the computer requires a scalar field or not.
Definition at line 68 of file ccPointDescriptor.h.
Referenced by qCanupoProcess::Classify(), and qCanupoPlugin::doTrainAction().
reset()
virtual void ScaleParamsComputer::reset () pure virtual
Called once before computing parameters at first scale.
Implemented in DimensionalityScaleParamsComputer.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCanupo/include/ccPointDescriptor.h
/root/ACloudViewer/plugins/core/Standard/qCanupo/src/ccPointDescriptor.cpp