ACloudViewer: cloudViewer::visualization::gui::Label3D Class Reference
cloudViewer::visualization::gui::Label3D Class Reference
#include <Label3D.h>
Classes
struct Impl
Public Member Functions
Label3D (const Eigen::Vector3f &pos, const char *text=nullptr)
Copies text.
~Label3D ()
const char * GetText () const
void SetText (const char *text)
Sets the text of the label (copies text)
Eigen::Vector3f GetPosition () const
void SetPosition (const Eigen::Vector3f &pos)
Color GetTextColor () const
void SetTextColor (const Color &color)
Detailed Description
Definition at line 20 of file Label3D.h.
Constructor & Destructor Documentation
Label3D()
cloudViewer::visualization::gui::Label3D::Label3D (const Eigen::Vector3f & pos, const char * text = nullptr) explicit
Copies text.
Definition at line 24 of file Label3D.cpp.
References SetPosition(), and SetText().
~Label3D()
cloudViewer::visualization::gui::Label3D::~Label3D ()
Definition at line 32 of file Label3D.cpp.
Member Function Documentation
GetPosition()
Eigen::Vector3f cloudViewer::visualization::gui::Label3D::GetPosition () const
Definition at line 38 of file Label3D.cpp.
GetText()
const char * cloudViewer::visualization::gui::Label3D::GetText () const
Definition at line 34 of file Label3D.cpp.
GetTextColor()
Color cloudViewer::visualization::gui::Label3D::GetTextColor () const
Definition at line 44 of file Label3D.cpp.
SetPosition()
void cloudViewer::visualization::gui::Label3D::SetPosition (const Eigen::Vector3f & pos)
Definition at line 40 of file Label3D.cpp.
Referenced by Label3D().
SetText()
void cloudViewer::visualization::gui::Label3D::SetText (const char * text)
Sets the text of the label (copies text)
Definition at line 36 of file Label3D.cpp.
Referenced by Label3D().
SetTextColor()
void cloudViewer::visualization::gui::Label3D::SetTextColor (const Color & color)
Definition at line 46 of file Label3D.cpp.
References color.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Label3D.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Label3D.cpp