ACloudViewer: ccColorScaleEditorDialog Class Reference
ccColorScaleEditorDialog Class Reference
Dialog to edit/create color scales.
#include <ecvColorScaleEditorDlg.h>
Public Member Functions
ccColorScaleEditorDialog (ccColorScalesManager *manager, ecvMainAppInterface *mainApp, ccColorScale::Shared currentScale=ccColorScale::Shared(nullptr), QWidget *parent=nullptr)
Default constructor.
~ccColorScaleEditorDialog () override=default
Destructor.
void setAssociatedScalarField (ccScalarField *sf)
Sets associated scalar field (optional)
void setActiveScale (ccColorScale::Shared currentScale)
Sets active scale.
ccColorScale::Shared getActiveScale ()
Returns active scale.
Protected Slots
void colorScaleChanged (int)
void relativeModeChanged (int)
void onStepSelected (int)
void onStepModified (int)
void deletecSelectedStep ()
void changeSelectedStepColor ()
void changeSelectedStepValue (double)
void onCustomLabelsListChanged ()
void toggleCustomLabelsList (bool)
void copyCurrentScale ()
bool saveCurrentScale ()
void deleteCurrentScale ()
void renameCurrentScale ()
void exportCurrentScale ()
void importScale ()
void createNewScale ()
void onApply ()
void onClose ()
Protected Member Functions
void updateMainComboBox ()
Updates main combox box with color scales manager.
void setModified (bool state)
Sets modification flag state.
bool canChangeCurrentScale ()
If the current scale has been modified, ask the user what to do.
bool isRelativeMode () const
void setScaleModeToRelative (bool isRelative)
bool checkCustomLabelsList (bool showWarnings)
Checks the custom labels list.
bool exportCustomLabelsList (ccColorScale::LabelSet &labels)
Exports the custom labels list.
Protected Attributes
ccColorScalesManager * m_manager
Color scale manager.
ccColorScale::Shared m_colorScale
Current active color scale.
ccColorScaleEditorWidget * m_scaleWidget
Color scale editor widget.
ccScalarField * m_associatedSF
Associated scalar field.
bool m_modified
Modification flag.
double m_minAbsoluteVal
Current min boundary for absolute scales.
double m_maxAbsoluteVal
Current max boundary for absolute scales.
ecvMainAppInterface * m_mainApp
Associated application (interface)
Ui::ColorScaleEditorDlg * m_ui
Detailed Description
Dialog to edit/create color scales.
Definition at line 27 of file ecvColorScaleEditorDlg.h.
Constructor & Destructor Documentation
ccColorScaleEditorDialog()
ccColorScaleEditorDialog::ccColorScaleEditorDialog (ccColorScalesManager * manager, ecvMainAppInterface * mainApp, ccColorScale::Shared currentScale = ccColorScale::Shared(nullptr), QWidget * parent = nullptr)
Default constructor.
Definition at line 45 of file ecvColorScaleEditorDlg.cpp.
References ccColorScalesManager::BGYR, changeSelectedStepColor(), changeSelectedStepValue(), colorScaleChanged(), copyCurrentScale(), createNewScale(), deletecSelectedStep(), deleteCurrentScale(), exportCurrentScale(), ccColorScalesManager::getDefaultScale(), importScale(), m_colorScale, m_manager, m_scaleWidget, m_ui, onApply(), onClose(), onCustomLabelsListChanged(), onStepModified(), onStepSelected(), relativeModeChanged(), renameCurrentScale(), saveCurrentScale(), setActiveScale(), toggleCustomLabelsList(), and updateMainComboBox().
~ccColorScaleEditorDialog()
ccColorScaleEditorDialog::~ccColorScaleEditorDialog () override default
Destructor.
Member Function Documentation
canChangeCurrentScale()
bool ccColorScaleEditorDialog::canChangeCurrentScale () protected
If the current scale has been modified, ask the user what to do.
Returns
whether user allows the change or not
ask the user if we should save the current scale?
Definition at line 185 of file ecvColorScaleEditorDlg.cpp.
References m_colorScale, m_modified, and saveCurrentScale().
Referenced by onApply(), onClose(), and setActiveScale().
changeSelectedStepColor
void ccColorScaleEditorDialog::changeSelectedStepColor () protected slot
Definition at line 408 of file ecvColorScaleEditorDlg.cpp.
References ccColorScaleElement::getColor(), ccColorScaleEditorWidget::getSelectedStepIndex(), ccColorScaleEditorWidget::getStep(), m_scaleWidget, and ccColorScaleEditorWidget::setStepColor().
Referenced by ccColorScaleEditorDialog().
changeSelectedStepValue
void ccColorScaleEditorDialog::changeSelectedStepValue (double value) protected slot
Definition at line 424 of file ecvColorScaleEditorDlg.cpp.
References ccColorScaleElement::getColor(), ccColorScaleElement::getRelativePos(), ccColorScaleEditorWidget::getSelectedStepIndex(), ccColorScaleEditorWidget::getStep(), ccColorScaleEditorWidget::getStepCount(), isRelativeMode(), m_maxAbsoluteVal, m_minAbsoluteVal, m_scaleWidget, max(), setModified(), ccColorScaleEditorWidget::setSelectedStepIndex(), ccColorScaleEditorWidget::setSliders(), and ccColorScaleEditorWidget::setStepRelativePosition().
Referenced by ccColorScaleEditorDialog().
checkCustomLabelsList()
bool ccColorScaleEditorDialog::checkCustomLabelsList (bool showWarnings) protected
Checks the custom labels list.
Definition at line 527 of file ecvColorScaleEditorDlg.cpp.
References CVLog::Error(), m_ui, qtCompatSplitRegex(), and QtCompat::SkipEmptyParts.
Referenced by saveCurrentScale(), and toggleCustomLabelsList().
colorScaleChanged
void ccColorScaleEditorDialog::colorScaleChanged (int pos) protected slot
Definition at line 166 of file ecvColorScaleEditorDlg.cpp.
References ccColorScalesManager::getScale(), ccColorScalesManager::GetUniqueInstance(), m_ui, and setActiveScale().
Referenced by ccColorScaleEditorDialog().
copyCurrentScale
void ccColorScaleEditorDialog::copyCurrentScale () protected slot
Definition at line 575 of file ecvColorScaleEditorDlg.cpp.
References ccColorScalesManager::addScale(), ccColorScale::Create(), ccColorScaleEditorWidget::exportColorScale(), m_colorScale, m_manager, m_scaleWidget, setActiveScale(), and updateMainComboBox().
Referenced by ccColorScaleEditorDialog().
createNewScale
void ccColorScaleEditorDialog::createNewScale () protected slot
Definition at line 719 of file ecvColorScaleEditorDlg.cpp.
References ccColorScalesManager::addScale(), ecvColor::blue(), ccColorScale::Create(), m_manager, ecvColor::red(), setActiveScale(), and updateMainComboBox().
Referenced by ccColorScaleEditorDialog().
deletecSelectedStep
void ccColorScaleEditorDialog::deletecSelectedStep () protected slot
Definition at line 396 of file ecvColorScaleEditorDlg.cpp.
References ccColorScaleEditorWidget::deleteStep(), ccColorScaleEditorWidget::getSelectedStepIndex(), ccColorScaleEditorWidget::getStepCount(), m_scaleWidget, and setModified().
Referenced by ccColorScaleEditorDialog().
deleteCurrentScale
void ccColorScaleEditorDialog::deleteCurrentScale () protected slot
Definition at line 683 of file ecvColorScaleEditorDlg.cpp.
References ccColorScalesManager::getScale(), m_colorScale, m_manager, m_ui, ccColorScalesManager::removeScale(), setActiveScale(), setModified(), and updateMainComboBox().
Referenced by ccColorScaleEditorDialog().
exportCurrentScale
void ccColorScaleEditorDialog::exportCurrentScale () protected slot
Definition at line 747 of file ecvColorScaleEditorDlg.cpp.
References ecvPS::CurrentPath(), ecvFileUtils::defaultDocPath(), filename, m_colorScale, CVLog::Print(), and ecvPS::SaveFile().
Referenced by ccColorScaleEditorDialog().
exportCustomLabelsList()
bool ccColorScaleEditorDialog::exportCustomLabelsList (ccColorScale::LabelSet & labels) protected
Exports the custom labels list.
Definition at line 496 of file ecvColorScaleEditorDlg.cpp.
References CVLog::Error(), m_ui, qtCompatSplitRegex(), and QtCompat::SkipEmptyParts.
Referenced by saveCurrentScale().
getActiveScale()
ccColorScale::Shared ccColorScaleEditorDialog::getActiveScale () inline
Returns active scale.
Definition at line 48 of file ecvColorScaleEditorDlg.h.
Referenced by StereogramDialog::spawnColorScaleEditor(), and DistanceMapGenerationDlg::spawnColorScaleEditor().
importScale
void ccColorScaleEditorDialog::importScale () protected slot
Definition at line 780 of file ecvColorScaleEditorDlg.cpp.
References ccColorScalesManager::addScale(), ecvPS::CurrentPath(), ecvFileUtils::defaultDocPath(), filename, ccColorScalesManager::getScale(), ecvPS::LoadFile(), ccColorScale::LoadFromXML(), m_manager, CVLog::Print(), setActiveScale(), e57::toString(), updateMainComboBox(), and CVLog::Warning().
Referenced by ccColorScaleEditorDialog().
isRelativeMode()
bool ccColorScaleEditorDialog::isRelativeMode () const protected
Returns whether current edited scale is 'relative' (true) or 'absolute' (false) Warning: may not be the same state as the current scale (m_colorScale) If current modifications have not been saved yet!
Definition at line 209 of file ecvColorScaleEditorDlg.cpp.
References m_ui.
Referenced by changeSelectedStepValue(), onStepModified(), and saveCurrentScale().
onApply
void ccColorScaleEditorDialog::onApply () protected slot
Definition at line 734 of file ecvColorScaleEditorDlg.cpp.
References canChangeCurrentScale(), m_associatedSF, m_colorScale, m_mainApp, ecvMainAppInterface::refreshAll(), and ccScalarField::setColorScale().
Referenced by ccColorScaleEditorDialog().
onClose
void ccColorScaleEditorDialog::onClose () protected slot
Definition at line 741 of file ecvColorScaleEditorDlg.cpp.
References canChangeCurrentScale().
Referenced by ccColorScaleEditorDialog().
onCustomLabelsListChanged
void ccColorScaleEditorDialog::onCustomLabelsListChanged () protected slot
Definition at line 551 of file ecvColorScaleEditorDlg.cpp.
References setModified().
Referenced by ccColorScaleEditorDialog().
onStepModified
void ccColorScaleEditorDialog::onStepModified (int index) protected slot
Definition at line 347 of file ecvColorScaleEditorDlg.cpp.
References ccColorScaleElement::getColor(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), ccColorScaleElement::getRelativePos(), ccColorScaleEditorWidget::getStep(), ccColorScaleEditorWidget::getStepCount(), isRelativeMode(), m_associatedSF, m_colorScale, m_maxAbsoluteVal, m_minAbsoluteVal, m_scaleWidget, m_ui, ccQtHelpers::SetButtonColor(), and setModified().
Referenced by ccColorScaleEditorDialog(), onStepSelected(), and setScaleModeToRelative().
onStepSelected
void ccColorScaleEditorDialog::onStepSelected (int index) protected slot
Definition at line 325 of file ecvColorScaleEditorDlg.cpp.
References ccColorScaleEditorWidget::getStepCount(), m_modified, m_scaleWidget, m_ui, onStepModified(), ccQtHelpers::SetButtonColor(), and setModified().
Referenced by ccColorScaleEditorDialog(), and setActiveScale().
relativeModeChanged
void ccColorScaleEditorDialog::relativeModeChanged (int value) protected slot
Definition at line 174 of file ecvColorScaleEditorDlg.cpp.
References setModified(), and setScaleModeToRelative().
Referenced by ccColorScaleEditorDialog().
renameCurrentScale
void ccColorScaleEditorDialog::renameCurrentScale () protected slot
Definition at line 664 of file ecvColorScaleEditorDlg.cpp.
References m_colorScale, and m_ui.
Referenced by ccColorScaleEditorDialog().
saveCurrentScale
bool ccColorScaleEditorDialog::saveCurrentScale () protected slot
Definition at line 598 of file ecvColorScaleEditorDlg.cpp.
References checkCustomLabelsList(), ecvMainAppInterface::dbRootObject(), ccColorScaleEditorWidget::exportColorScale(), exportCustomLabelsList(), ccHObject::filterChildren(), ccScalarField::getColorScale(), ccPointCloud::getCurrentDisplayedScalarField(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), ccHObject::getParent(), cloudViewer::PointCloudTpl< T >::getScalarField(), ccObject::isKindOf(), isRelativeMode(), m_colorScale, m_mainApp, m_maxAbsoluteVal, m_minAbsoluteVal, m_scaleWidget, m_ui, CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, ecvMainAppInterface::refreshAll(), ccScalarField::setColorScale(), and setModified().
Referenced by canChangeCurrentScale(), and ccColorScaleEditorDialog().
setActiveScale()
void ccColorScaleEditorDialog::setActiveScale (ccColorScale::Shared currentScale)
Sets active scale.
Definition at line 213 of file ecvColorScaleEditorDlg.cpp.
References canChangeCurrentScale(), ccColorScaleEditorWidget::importColorScale(), m_colorScale, m_maxAbsoluteVal, m_minAbsoluteVal, m_scaleWidget, m_ui, onStepSelected(), s_defaultEmptyCustomListText, setModified(), and setScaleModeToRelative().
Referenced by ccColorScaleEditorDialog(), colorScaleChanged(), copyCurrentScale(), createNewScale(), deleteCurrentScale(), and importScale().
setAssociatedScalarField()
void ccColorScaleEditorDialog::setAssociatedScalarField (ccScalarField * sf)
Sets associated scalar field (optional)
Definition at line 126 of file ecvColorScaleEditorDlg.cpp.
References cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), m_associatedSF, m_colorScale, m_maxAbsoluteVal, and m_minAbsoluteVal.
setModified()
void ccColorScaleEditorDialog::setModified (bool state) protected
Sets modification flag state.
Definition at line 180 of file ecvColorScaleEditorDlg.cpp.
References m_modified, and m_ui.
Referenced by changeSelectedStepValue(), deletecSelectedStep(), deleteCurrentScale(), onCustomLabelsListChanged(), onStepModified(), onStepSelected(), relativeModeChanged(), saveCurrentScale(), setActiveScale(), and toggleCustomLabelsList().
setScaleModeToRelative()
void ccColorScaleEditorDialog::setScaleModeToRelative (bool isRelative) protected
Sets current mode for active scale between 'relative' (true) or 'absolute' (false) Warning: may not be the same state as the current scale (m_colorScale) If current modifications have not been saved yet!
Definition at line 309 of file ecvColorScaleEditorDlg.cpp.
References ccColorScaleEditorWidget::getSelectedStepIndex(), m_scaleWidget, m_ui, and onStepModified().
Referenced by relativeModeChanged(), and setActiveScale().
toggleCustomLabelsList
void ccColorScaleEditorDialog::toggleCustomLabelsList (bool state) protected slot
Definition at line 555 of file ecvColorScaleEditorDlg.cpp.
References checkCustomLabelsList(), m_ui, s_defaultEmptyCustomListText, and setModified().
Referenced by ccColorScaleEditorDialog().
updateMainComboBox()
void ccColorScaleEditorDialog::updateMainComboBox () protected
Updates main combox box with color scales manager.
Definition at line 138 of file ecvColorScaleEditorDlg.cpp.
References m_colorScale, m_manager, m_ui, and ccColorScalesManager::map().
Referenced by ccColorScaleEditorDialog(), copyCurrentScale(), createNewScale(), deleteCurrentScale(), and importScale().
Member Data Documentation
m_associatedSF
ccScalarField* ccColorScaleEditorDialog::m_associatedSF protected
Associated scalar field.
Definition at line 123 of file ecvColorScaleEditorDlg.h.
Referenced by onApply(), onStepModified(), and setAssociatedScalarField().
m_colorScale
ccColorScale::Shared ccColorScaleEditorDialog::m_colorScale protected
Current active color scale.
Definition at line 117 of file ecvColorScaleEditorDlg.h.
Referenced by canChangeCurrentScale(), ccColorScaleEditorDialog(), copyCurrentScale(), deleteCurrentScale(), exportCurrentScale(), onApply(), onStepModified(), renameCurrentScale(), saveCurrentScale(), setActiveScale(), setAssociatedScalarField(), and updateMainComboBox().
m_mainApp
ecvMainAppInterface* ccColorScaleEditorDialog::m_mainApp protected
Associated application (interface)
Definition at line 134 of file ecvColorScaleEditorDlg.h.
Referenced by onApply(), and saveCurrentScale().
m_manager
ccColorScalesManager* ccColorScaleEditorDialog::m_manager protected
Color scale manager.
Definition at line 114 of file ecvColorScaleEditorDlg.h.
Referenced by ccColorScaleEditorDialog(), copyCurrentScale(), createNewScale(), deleteCurrentScale(), importScale(), and updateMainComboBox().
m_maxAbsoluteVal
double ccColorScaleEditorDialog::m_maxAbsoluteVal protected
Current max boundary for absolute scales.
Definition at line 131 of file ecvColorScaleEditorDlg.h.
Referenced by changeSelectedStepValue(), onStepModified(), saveCurrentScale(), setActiveScale(), and setAssociatedScalarField().
m_minAbsoluteVal
double ccColorScaleEditorDialog::m_minAbsoluteVal protected
Current min boundary for absolute scales.
Definition at line 129 of file ecvColorScaleEditorDlg.h.
Referenced by changeSelectedStepValue(), onStepModified(), saveCurrentScale(), setActiveScale(), and setAssociatedScalarField().
m_modified
bool ccColorScaleEditorDialog::m_modified protected
Modification flag.
Definition at line 126 of file ecvColorScaleEditorDlg.h.
Referenced by canChangeCurrentScale(), onStepSelected(), and setModified().
m_scaleWidget
ccColorScaleEditorWidget* ccColorScaleEditorDialog::m_scaleWidget protected
Color scale editor widget.
Definition at line 120 of file ecvColorScaleEditorDlg.h.
Referenced by ccColorScaleEditorDialog(), changeSelectedStepColor(), changeSelectedStepValue(), copyCurrentScale(), deletecSelectedStep(), onStepModified(), onStepSelected(), saveCurrentScale(), setActiveScale(), and setScaleModeToRelative().
m_ui
Ui::ColorScaleEditorDlg* ccColorScaleEditorDialog::m_ui protected
Definition at line 136 of file ecvColorScaleEditorDlg.h.
Referenced by ccColorScaleEditorDialog(), checkCustomLabelsList(), colorScaleChanged(), deleteCurrentScale(), exportCustomLabelsList(), isRelativeMode(), onStepModified(), onStepSelected(), renameCurrentScale(), saveCurrentScale(), setActiveScale(), setModified(), setScaleModeToRelative(), toggleCustomLabelsList(), and updateMainComboBox().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVPluginAPI/include/ecvColorScaleEditorDlg.h
/root/ACloudViewer/libs/CVPluginAPI/src/ecvColorScaleEditorDlg.cpp