ACloudViewer: cloudViewer::core::Cacher Class Reference
cloudViewer::core::Cacher Class Reference
Public Member Functions
~Cacher ()
Cacher (const Cacher &)=delete
Cacher & operator= (Cacher &)=delete
void * Malloc (size_t byte_size, const Device &device, const std::shared_ptr< MemoryManagerDevice > &device_mm)
void Free (void *ptr, const Device &device)
void Clear (const Device &device)
void Clear ()
Static Public Member Functions
static Cacher & GetInstance ()
Detailed Description
Definition at line 344 of file MemoryManagerCached.cpp.
Constructor & Destructor Documentation
~Cacher()
cloudViewer::core::Cacher::~Cacher () inline
Definition at line 362 of file MemoryManagerCached.cpp.
References Clear(), and LogError.
Cacher()
cloudViewer::core::Cacher::Cacher (const Cacher &) delete
Member Function Documentation
Clear() [1/2]
void cloudViewer::core::Cacher::Clear () inline
Definition at line 439 of file MemoryManagerCached.cpp.
Referenced by ~Cacher().
Clear() [2/2]
void cloudViewer::core::Cacher::Clear (const Device & device) inline
Definition at line 426 of file MemoryManagerCached.cpp.
Referenced by cloudViewer::core::MemoryManagerCached::ReleaseCache().
Free()
void cloudViewer::core::Cacher::Free (void * ptr, const Device & device) inline
Definition at line 420 of file MemoryManagerCached.cpp.
Referenced by cloudViewer::core::MemoryManagerCached::Free().
GetInstance()
static Cacher& cloudViewer::core::Cacher::GetInstance () inline static
Definition at line 346 of file MemoryManagerCached.cpp.
References cloudViewer::utility::Logger::GetInstance(), and Runtime::GetInstance().
Referenced by cloudViewer::core::MemoryManagerCached::Free(), cloudViewer::core::MemoryManagerCached::Malloc(), and cloudViewer::core::MemoryManagerCached::ReleaseCache().
Malloc()
void* cloudViewer::core::Cacher::Malloc (size_t byte_size, const Device & device, const std::shared_ptr< MemoryManagerDevice > & device_mm) inline
Definition at line 380 of file MemoryManagerCached.cpp.
References cloudViewer::core::MemoryCache::AlignByteSize().
Referenced by cloudViewer::core::MemoryManagerCached::Malloc().
operator=()
Cacher& cloudViewer::core::Cacher::operator= (Cacher &) delete
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/MemoryManagerCached.cpp