ACloudViewer: ccGraphicalSegmentationTool Class Reference
ccGraphicalSegmentationTool Class Reference
Graphical segmentation mechanism (with polyline)
#include <ecvGraphicalSegmentationTool.h>
Public Member Functions
ccGraphicalSegmentationTool (QWidget *parent)
Default constructor.
virtual ~ccGraphicalSegmentationTool ()
Destructor.
bool addEntity (ccHObject *anObject, bool silent=false)
Adds an entity (and/or its children) to the 'to be segmented' pool.
unsigned getNumberOfValidEntities () const
ccPolyline * getPolyLine ()
Get a pointer to the polyline that has been segmented.
QSet< ccHObject * > & entities ()
Returns the active 'to be segmented' set.
const QSet< ccHObject * > & entities () const
Returns the active 'to be segmented' set (const version)
virtual bool linkWith (QWidget *win) override
Links the overlay dialog with a MDI window.
virtual bool start () override
Starts process.
virtual void stop (bool accepted) override
Stops process/dialog.
bool deleteHiddenParts () const
Returns whether hidden parts should be delete after segmentation.
void removeAllEntities ()
Remove entities from the 'to be segmented' pool.
bool applySegmentation (ecvMainAppInterface *app, ccHObject::Container &newEntities)
Apply segmentation and update the database (helper)
Public Member Functions inherited from ccOverlayDialog
ccOverlayDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::FramelessWindowHint|Qt::Tool)
Default constructor.
~ccOverlayDialog () override
Destructor.
void reject () override
void addOverridenShortcut (Qt::Key key)
bool started () const
Returns whether the tool is currently started or not.
Protected Types
enum ProcessStates {
POLYLINE = 1 , RECTANGLE = 2 , PAUSED = 32 , STARTED = 64 ,
RUNNING = 128
}
Process states.
Protected Slots
void segmentIn ()
void segmentOut ()
void segment (bool)
void reset ()
void apply ()
void applyAndDelete ()
void cancel ()
void addPointToPolyline (int x, int y)
void closePolyLine (int x=0, int y=0)
void updateSegmentation ()
void closeRectangle ()
void updatePolyLine (int x, int y, Qt::MouseButtons buttons)
void pauseSegmentationMode (bool state, bool only2D=true)
void pauseSegmentation (bool state)
void resetSegmentation ()
void doSetPolylineSelection ()
void doSetRectangularSelection ()
void doActionUseExistingPolyline ()
void doExportSegmentationPolyline ()
void onShortcutTriggered (int)
To capture overridden shortcuts (pause button, etc.)
void prepareEntityForRemoval (ccHObject *entity, bool unallocateVisibilityArrays)
Prepare entity before removal.
void allowPolylineExport (bool state)
Whether to allow or not to exort the current segmentation polyline.
Protected Slots inherited from ccOverlayDialog
virtual void onLinkedWindowDeletion (QObject *object=nullptr)
Slot called when the linked window is deleted (calls 'onClose')
Protected Member Functions
void setDrawFlag (bool state=true)
Protected Member Functions inherited from ccOverlayDialog
bool eventFilter (QObject *obj, QEvent *e) override
Protected Attributes
QSet< ccHObject * > m_toSegment
Set of entities to be segmented.
bool m_somethingHasChanged
Whether something has changed or not (for proper 'cancel')
unsigned m_state
Current process state.
ccPolyline * m_segmentationPoly
Segmentation polyline.
ccPointCloud * m_polyVertices
Segmentation polyline vertices.
bool m_rectangularSelection
Selection mode.
bool m_deleteHiddenParts
Whether to delete hidden parts after segmentation.
Protected Attributes inherited from ccOverlayDialog
QWidget * m_associatedWin
Associated (MDI) window.
bool m_processing
Running/processing state.
QList< int > m_overriddenKeys
Overridden keys.
Additional Inherited Members
Signals inherited from ccOverlayDialog
void processFinished (bool accepted)
Signal emitted when process is finished.
void shortcutTriggered (int key)
Signal emitted when an overridden key shortcut is pressed.
void shown ()
Signal emitted when a 'show' event is detected.
Detailed Description
Graphical segmentation mechanism (with polyline)
Definition at line 27 of file ecvGraphicalSegmentationTool.h.
Member Enumeration Documentation
ProcessStates
enum ccGraphicalSegmentationTool::ProcessStates protected
Process states.
Enumerator
POLYLINE
RECTANGLE
PAUSED
STARTED
RUNNING
Definition at line 118 of file ecvGraphicalSegmentationTool.h.
Constructor & Destructor Documentation
ccGraphicalSegmentationTool()
ccGraphicalSegmentationTool::ccGraphicalSegmentationTool (QWidget * parent) explicit
Default constructor.
Definition at line 54 of file ecvGraphicalSegmentationTool.cpp.
References ccOverlayDialog::addOverridenShortcut(), allowPolylineExport(), apply(), applyAndDelete(), cancel(), doActionUseExistingPolyline(), doExportSegmentationPolyline(), doSetPolylineSelection(), doSetRectangularSelection(), ecvColor::green(), m_polyVertices, m_segmentationPoly, onShortcutTriggered(), pauseSegmentation(), reset(), segmentIn(), segmentOut(), ccPolyline::set2DMode(), cloudViewer::Polyline::setClosed(), ccPolyline::setColor(), ccPolyline::setForeground(), ccOverlayDialog::shortcutTriggered(), and ccDrawableObject::showColors().
~ccGraphicalSegmentationTool()
ccGraphicalSegmentationTool::~ccGraphicalSegmentationTool () virtual
Destructor.
Definition at line 138 of file ecvGraphicalSegmentationTool.cpp.
References m_polyVertices, and m_segmentationPoly.
Member Function Documentation
addEntity()
bool ccGraphicalSegmentationTool::addEntity (ccHObject * anObject, bool silent = false)
Adds an entity (and/or its children) to the 'to be segmented' pool.
Warning: some entities may be rejected if they are locked, or can't be segmented this way.
Returns
whether entity has been added to the pool or not
Definition at line 325 of file ecvGraphicalSegmentationTool.cpp.
References cloudViewer::ReferenceCloud::getAssociatedCloud(), ccGenericMesh::getAssociatedCloud(), ccHObject::getChild(), ccHObject::getChildrenNumber(), ccObject::getName(), CV_TYPES::HIERARCHY_OBJECT, ccObject::isA(), ccGenericMesh::IsCloudVerticesOfMesh(), ccPolyline::IsCloudVerticesOfPolyline(), ccObject::isKindOf(), m_toSegment, CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, CV_TYPES::POLY_LINE, ccHObject::popDisplayState(), CV_TYPES::PRIMITIVE, ccHObject::pushDisplayState(), result, ccObject::setEnabled(), ccDrawableObject::setVisible(), CV_TYPES::SUB_MESH, ccHObjectCaster::ToGenericMesh(), ccHObjectCaster::ToGenericPointCloud(), ccHObjectCaster::ToPolyline(), and CVLog::Warning().
addPointToPolyline
void ccGraphicalSegmentationTool::addPointToPolyline (int x, int y) protected slot
Definition at line 511 of file ecvGraphicalSegmentationTool.cpp.
References cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::ReferenceCloud::addPointIndex(), allowPolylineExport(), ccPointCloud::clear(), cloudViewer::Polyline::clear(), CVLog::Error(), cloudViewer::PointCloudTpl< T >::getPointPersistentPtr(), m_polyVertices, m_rectangularSelection, m_segmentationPoly, m_state, POLYLINE, RECTANGLE, ccPointCloud::reserve(), RUNNING, cloudViewer::Polyline::setClosed(), cloudViewer::PointCloudTpl< T >::size(), STARTED, ecvDisplayTools::ToVtkCoordinates(), updateSegmentation(), Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
Referenced by linkWith().
allowPolylineExport
void ccGraphicalSegmentationTool::allowPolylineExport (bool state) protected slot
Whether to allow or not to exort the current segmentation polyline.
Definition at line 129 of file ecvGraphicalSegmentationTool.cpp.
Referenced by addPointToPolyline(), ccGraphicalSegmentationTool(), closePolyLine(), closeRectangle(), doActionUseExistingPolyline(), pauseSegmentationMode(), start(), and updatePolyLine().
apply
void ccGraphicalSegmentationTool::apply () protected slot
Definition at line 1065 of file ecvGraphicalSegmentationTool.cpp.
References m_deleteHiddenParts, and stop().
Referenced by ccGraphicalSegmentationTool().
applyAndDelete
void ccGraphicalSegmentationTool::applyAndDelete () protected slot
Definition at line 1070 of file ecvGraphicalSegmentationTool.cpp.
References m_deleteHiddenParts, and stop().
Referenced by ccGraphicalSegmentationTool().
applySegmentation()
bool ccGraphicalSegmentationTool::applySegmentation (ecvMainAppInterface * app, ccHObject::Container & newEntities)
Apply segmentation and update the database (helper)
Definition at line 1130 of file ecvGraphicalSegmentationTool.cpp.
References ccHObject::addChild(), ecvMainAppInterface::addToDB(), ccGBLSensor::clearDepthBuffer(), ccGenericPointCloud::createNewCloudFromVisibilitySelection(), ccMesh::createNewMeshFromSelection(), ccPolyline::createNewPolylinesFromSelection(), ecvMainAppInterface::dbRootObject(), cc2DLabel::PickedPoint::entity(), CVLog::Error(), ccHObject::filterChildren(), CV_TYPES::GBL_SENSOR, cloudViewer::ReferenceCloud::getAssociatedCloud(), ccGenericMesh::getAssociatedCloud(), ccObject::getName(), ccHObject::getParent(), cc2DLabel::getPickedPoint(), ccObject::isA(), ccHObject::isAncestorOf(), ccGenericMesh::IsCloudVerticesOfMesh(), ccPolyline::IsCloudVerticesOfPolyline(), ccObject::isKindOf(), ccObject::isLocked(), CV_TYPES::LABEL_2D, m_deleteHiddenParts, m_toSegment, CV_TYPES::MESH, ecvMainAppInterface::ccHObjectContext::parent, CV_TYPES::POINT_CLOUD, CV_TYPES::POLY_LINE, prepareEntityForRemoval(), ecvMainAppInterface::putObjectBackIntoDBTree(), removeAllEntities(), ccHObject::removeChild(), ecvMainAppInterface::removeObjectTemporarilyFromDBTree(), RemoveUnusedLabelsAndUpdateTheOthers(), ccObject::setName(), cc2DLabel::size(), cloudViewer::GenericCloud::size(), cloudViewer::GenericMesh::size(), cloudViewer::ReferenceCloud::size(), ccMesh::size(), ccHObjectCaster::ToGBLSensor(), ccHObjectCaster::ToGenericMesh(), ccHObjectCaster::ToGenericPointCloud(), ccHObjectCaster::ToMesh(), and CVLog::Warning().
cancel
void ccGraphicalSegmentationTool::cancel () protected slot
Definition at line 1075 of file ecvGraphicalSegmentationTool.cpp.
References m_deleteHiddenParts, reset(), and stop().
Referenced by ccGraphicalSegmentationTool().
closePolyLine
void ccGraphicalSegmentationTool::closePolyLine (int x = 0, int y = 0) protected slot
Definition at line 613 of file ecvGraphicalSegmentationTool.cpp.
References allowPolylineExport(), ccPointCloud::clear(), cloudViewer::Polyline::clear(), m_polyVertices, m_segmentationPoly, m_state, POLYLINE, cloudViewer::ReferenceCloud::resize(), RUNNING, cloudViewer::Polyline::setClosed(), cloudViewer::ReferenceCloud::size(), and updateSegmentation().
Referenced by linkWith().
closeRectangle
void ccGraphicalSegmentationTool::closeRectangle () protected slot
Definition at line 591 of file ecvGraphicalSegmentationTool.cpp.
References allowPolylineExport(), ccPointCloud::clear(), cloudViewer::Polyline::clear(), m_polyVertices, m_rectangularSelection, m_segmentationPoly, m_state, RECTANGLE, RUNNING, cloudViewer::ReferenceCloud::size(), and updateSegmentation().
Referenced by linkWith().
deleteHiddenParts()
bool ccGraphicalSegmentationTool::deleteHiddenParts () const inline
Returns whether hidden parts should be delete after segmentation.
Definition at line 62 of file ecvGraphicalSegmentationTool.h.
References m_deleteHiddenParts.
doActionUseExistingPolyline
void ccGraphicalSegmentationTool::doActionUseExistingPolyline () protected slot
Definition at line 836 of file ecvGraphicalSegmentationTool.cpp.
References cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::ReferenceCloud::addPointIndex(), allowPolylineExport(), ccPointCloud::clear(), cloudViewer::Polyline::clear(), MainWindow::dbRootObject(), doSetPolylineSelection(), CVLog::Error(), ccHObject::filterChildren(), cloudViewer::ReferenceCloud::getAssociatedCloud(), ecvDisplayTools::GetGLCameraParameters(), ecvDisplayTools::GetMainWindow(), cc2DViewportObject::getParameters(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), ccPolyline::is2DMode(), cloudViewer::Polyline::isClosed(), m_polyVertices, m_rectangularSelection, m_segmentationPoly, m_state, pauseSegmentationMode(), CV_TYPES::POLY_LINE, POLYLINE, ccGLCameraParameters::project(), ecvDisplayTools::RedrawDisplay(), cloudViewer::ReferenceCloud::reserve(), ccPointCloud::reserve(), RUNNING, ccItemSelectionDlg::SelectEntity(), cloudViewer::Polyline::setClosed(), ecvDisplayTools::SetRedrawRecursive(), ecvDisplayTools::SetViewportParameters(), cloudViewer::GenericCloud::size(), cloudViewer::ReferenceCloud::size(), MainWindow::TheInstance(), updateSegmentation(), CV_TYPES::VIEWPORT_2D_OBJECT, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccGraphicalSegmentationTool().
doExportSegmentationPolyline
void ccGraphicalSegmentationTool::doExportSegmentationPolyline () protected slot
Definition at line 946 of file ecvGraphicalSegmentationTool.cpp.
References ccHObject::addChild(), MainWindow::addToDB(), Vector3Tpl< PointCoordinateType >::fromArray(), cloudViewer::ReferenceCloud::getAssociatedCloud(), ecvDisplayTools::GetClick3DPos(), ecvDisplayTools::GetGLCameraParameters(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), cloudViewer::PointCloudTpl< T >::getPoint(), ecvDisplayTools::GetViewportParameters(), height, ccPointCloud::invalidateBoundingBox(), ccShiftedObject::isShifted(), m_segmentationPoly, m_toSegment, CVLog::Print(), s_polylineExportCount, ccPolyline::set2DMode(), cloudViewer::Polyline::setClosed(), ccPolyline::setColor(), ccObject::setEnabled(), ccPolyline::setGlobalScale(), ccPolyline::setGlobalShift(), ccObject::setName(), cc2DViewportObject::setParameters(), cloudViewer::GenericCloud::size(), cloudViewer::ReferenceCloud::size(), MainWindow::TheInstance(), ccHObjectCaster::ToShifted(), Tuple3Tpl< Type >::u, ccGLCameraParameters::viewport, CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and ecvColor::yellow().
Referenced by ccGraphicalSegmentationTool().
doSetPolylineSelection
void ccGraphicalSegmentationTool::doSetPolylineSelection () protected slot
Definition at line 784 of file ecvGraphicalSegmentationTool.cpp.
References ecvDisplayTools::DisplayNewMessage(), m_rectangularSelection, m_state, ecvDisplayTools::MANUAL_SEGMENTATION_MESSAGE, PAUSED, pauseSegmentationMode(), ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::SetRedrawRecursive(), and ecvDisplayTools::UPPER_CENTER_MESSAGE.
Referenced by ccGraphicalSegmentationTool(), doActionUseExistingPolyline(), and onShortcutTriggered().
doSetRectangularSelection
void ccGraphicalSegmentationTool::doSetRectangularSelection () protected slot
Definition at line 810 of file ecvGraphicalSegmentationTool.cpp.
References ecvDisplayTools::DisplayNewMessage(), m_rectangularSelection, m_state, ecvDisplayTools::MANUAL_SEGMENTATION_MESSAGE, PAUSED, pauseSegmentationMode(), ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::SetRedrawRecursive(), and ecvDisplayTools::UPPER_CENTER_MESSAGE.
Referenced by ccGraphicalSegmentationTool(), and onShortcutTriggered().
entities() [1/2]
QSet<ccHObject*>& ccGraphicalSegmentationTool::entities () inline
Returns the active 'to be segmented' set.
Definition at line 52 of file ecvGraphicalSegmentationTool.h.
References m_toSegment.
entities() [2/2]
const QSet<ccHObject*>& ccGraphicalSegmentationTool::entities () const inline
Returns the active 'to be segmented' set (const version)
Definition at line 54 of file ecvGraphicalSegmentationTool.h.
References m_toSegment.
getNumberOfValidEntities()
unsigned ccGraphicalSegmentationTool::getNumberOfValidEntities () const
Returns the number of entites currently in the the 'to be segmented' pool
Definition at line 454 of file ecvGraphicalSegmentationTool.cpp.
References m_toSegment.
getPolyLine()
ccPolyline* ccGraphicalSegmentationTool::getPolyLine () inline
Get a pointer to the polyline that has been segmented.
Definition at line 49 of file ecvGraphicalSegmentationTool.h.
References m_segmentationPoly.
linkWith()
bool ccGraphicalSegmentationTool::linkWith (QWidget * win) override virtual
Links the overlay dialog with a MDI window.
Warning: link can't be modified while dialog is displayed/process is running!
Returns
success
Reimplemented from ccOverlayDialog.
Definition at line 183 of file ecvGraphicalSegmentationTool.cpp.
References addPointToPolyline(), closePolyLine(), closeRectangle(), ccOverlayDialog::linkWith(), m_segmentationPoly, ecvDisplayTools::TheInstance(), and updatePolyLine().
onShortcutTriggered
void ccGraphicalSegmentationTool::onShortcutTriggered (int key) protected slot
To capture overridden shortcuts (pause button, etc.)
Definition at line 146 of file ecvGraphicalSegmentationTool.cpp.
References doSetPolylineSelection(), doSetRectangularSelection(), and m_rectangularSelection.
Referenced by ccGraphicalSegmentationTool().
pauseSegmentation
void ccGraphicalSegmentationTool::pauseSegmentation (bool state) inline protected slot
Definition at line 91 of file ecvGraphicalSegmentationTool.h.
References pauseSegmentationMode().
Referenced by ccGraphicalSegmentationTool().
pauseSegmentationMode
void ccGraphicalSegmentationTool::pauseSegmentationMode (bool state, bool only2D = true) protected slot
Definition at line 726 of file ecvGraphicalSegmentationTool.cpp.
References allowPolylineExport(), ccPointCloud::clear(), cloudViewer::Polyline::clear(), ecvDisplayTools::DisplayNewMessage(), ecvDisplayTools::GetCurrentScreen(), ecvDisplayTools::GetMainWindow(), ecvDisplayTools::INTERACT_SEND_ALL_SIGNALS, m_polyVertices, m_rectangularSelection, m_segmentationPoly, m_state, ecvDisplayTools::MANUAL_SEGMENTATION_MESSAGE, PAUSED, ecvDisplayTools::RedrawDisplay(), resetSegmentation(), ecvDisplayTools::SetInteractionMode(), ecvDisplayTools::SetRedrawRecursive(), cloudViewer::PointCloudTpl< T >::size(), STARTED, ecvDisplayTools::TRANSFORM_CAMERA(), and ecvDisplayTools::UPPER_CENTER_MESSAGE.
Referenced by doActionUseExistingPolyline(), doSetPolylineSelection(), doSetRectangularSelection(), pauseSegmentation(), segment(), and start().
prepareEntityForRemoval
void ccGraphicalSegmentationTool::prepareEntityForRemoval (ccHObject * entity, bool unallocateVisibilityArrays) protected slot
Prepare entity before removal.
Definition at line 225 of file ecvGraphicalSegmentationTool.cpp.
References ccGenericMesh::IsCloudVerticesOfMesh(), ccPolyline::IsCloudVerticesOfPolyline(), ccObject::isKindOf(), CV_TYPES::POINT_CLOUD, ccHObject::popDisplayState(), ccHObjectCaster::ToGenericPointCloud(), and ccGenericPointCloud::unallocateVisibilityArray().
Referenced by applySegmentation(), and removeAllEntities().
removeAllEntities()
void ccGraphicalSegmentationTool::removeAllEntities ()
Remove entities from the 'to be segmented' pool.
Warning
'unallocateVisibilityArray' will be called on all point clouds prior to be removed from the pool.
Definition at line 264 of file ecvGraphicalSegmentationTool.cpp.
References m_toSegment, prepareEntityForRemoval(), and setDrawFlag().
Referenced by applySegmentation().
reset
void ccGraphicalSegmentationTool::reset (void) protected slot
Definition at line 302 of file ecvGraphicalSegmentationTool.cpp.
References ecvDisplayTools::GetCurrentScreen(), m_somethingHasChanged, m_toSegment, ecvDisplayTools::RedrawDisplay(), resetSegmentation(), ccGenericPointCloud::resetVisibilityArray(), setDrawFlag(), ecvDisplayTools::SetRedrawRecursive(), and ccHObjectCaster::ToGenericPointCloud().
Referenced by cancel(), ccGraphicalSegmentationTool(), and start().
resetSegmentation
void ccGraphicalSegmentationTool::resetSegmentation () protected slot
Definition at line 648 of file ecvGraphicalSegmentationTool.cpp.
References ecvDisplayTools::GetCurrentScreen(), ccHObject::getViewId(), m_segmentationPoly, ecvDisplayTools::RemoveWidgets(), and WIDGET_POLYLINE_2D.
Referenced by pauseSegmentationMode(), reset(), stop(), and updateSegmentation().
segment
void ccGraphicalSegmentationTool::segment (bool keepPointsInside) protected slot
Definition at line 660 of file ecvGraphicalSegmentationTool.cpp.
References CVLog::Error(), ecvDisplayTools::GetCurrentScreen(), ecvDisplayTools::GetGLCameraParameters(), cloudViewer::GenericIndexedCloud::getPoint(), ccGenericPointCloud::getTheVisibilityArray(), cloudViewer::Polyline::isClosed(), cloudViewer::ManualSegmentationTools::isPointInsidePoly(), m_segmentationPoly, m_somethingHasChanged, m_toSegment, pauseSegmentationMode(), POINT_HIDDEN, POINT_VISIBLE, ccGLCameraParameters::project(), ecvDisplayTools::RedrawDisplay(), setDrawFlag(), ecvDisplayTools::SetRedrawRecursive(), cloudViewer::GenericCloud::size(), ccHObjectCaster::ToGenericPointCloud(), Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
Referenced by segmentIn(), and segmentOut().
segmentIn
void ccGraphicalSegmentationTool::segmentIn () protected slot
Definition at line 656 of file ecvGraphicalSegmentationTool.cpp.
References segment().
Referenced by ccGraphicalSegmentationTool().
segmentOut
void ccGraphicalSegmentationTool::segmentOut () protected slot
Definition at line 658 of file ecvGraphicalSegmentationTool.cpp.
References segment().
Referenced by ccGraphicalSegmentationTool().
setDrawFlag()
void ccGraphicalSegmentationTool::setDrawFlag (bool state = true) protected
Definition at line 295 of file ecvGraphicalSegmentationTool.cpp.
References m_toSegment.
Referenced by removeAllEntities(), reset(), and segment().
start()
bool ccGraphicalSegmentationTool::start () override virtual
Starts process.
Returns
success
Reimplemented from ccOverlayDialog.
Definition at line 207 of file ecvGraphicalSegmentationTool.cpp.
References allowPolylineExport(), ccPointCloud::clear(), cloudViewer::Polyline::clear(), m_polyVertices, m_segmentationPoly, m_somethingHasChanged, ecvDisplayTools::NO_PICKING, pauseSegmentationMode(), reset(), ecvDisplayTools::SetPickingMode(), and ccOverlayDialog::start().
stop()
void ccGraphicalSegmentationTool::stop (bool accepted) override virtual
Stops process/dialog.
Automatically emits the 'processFinished' signal (with input state as argument).
Parameters
accepted process/dialog result
Reimplemented from ccOverlayDialog.
Definition at line 276 of file ecvGraphicalSegmentationTool.cpp.
References ecvDisplayTools::DEFAULT_PICKING, ecvDisplayTools::DisplayNewMessage(), ecvDisplayTools::GetCurrentScreen(), m_segmentationPoly, ecvDisplayTools::MANUAL_SEGMENTATION_MESSAGE, ecvDisplayTools::RedrawDisplay(), resetSegmentation(), ecvDisplayTools::SetInteractionMode(), ecvDisplayTools::SetPickingMode(), ecvDisplayTools::SetRedrawRecursive(), ccOverlayDialog::stop(), ecvDisplayTools::TRANSFORM_CAMERA(), and ecvDisplayTools::UPPER_CENTER_MESSAGE.
Referenced by apply(), applyAndDelete(), and cancel().
updatePolyLine
void ccGraphicalSegmentationTool::updatePolyLine (int x, int y, Qt::MouseButtons buttons) protected slot
Definition at line 458 of file ecvGraphicalSegmentationTool.cpp.
References cloudViewer::ReferenceCloud::addPointIndex(), allowPolylineExport(), cloudViewer::Polyline::clear(), CVLog::Error(), cloudViewer::PointCloudTpl< T >::getPointPersistentPtr(), m_polyVertices, m_segmentationPoly, m_state, POLYLINE, RECTANGLE, ccPointCloud::resize(), RUNNING, cloudViewer::Polyline::setClosed(), cloudViewer::PointCloudTpl< T >::size(), ecvDisplayTools::ToVtkCoordinates(), updateSegmentation(), Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
Referenced by linkWith().
updateSegmentation
void ccGraphicalSegmentationTool::updateSegmentation () protected slot
Definition at line 638 of file ecvGraphicalSegmentationTool.cpp.
References ecvDisplayTools::DrawWidgets(), ecvDisplayTools::GetCurrentScreen(), m_segmentationPoly, WIDGETS_PARAMETER::opacity, resetSegmentation(), and WIDGET_POLYLINE_2D.
Referenced by addPointToPolyline(), closePolyLine(), closeRectangle(), doActionUseExistingPolyline(), and updatePolyLine().
Member Data Documentation
m_deleteHiddenParts
bool ccGraphicalSegmentationTool::m_deleteHiddenParts protected
Whether to delete hidden parts after segmentation.
Definition at line 141 of file ecvGraphicalSegmentationTool.h.
Referenced by apply(), applyAndDelete(), applySegmentation(), cancel(), and deleteHiddenParts().
m_polyVertices
ccPointCloud* ccGraphicalSegmentationTool::m_polyVertices protected
Segmentation polyline vertices.
Definition at line 135 of file ecvGraphicalSegmentationTool.h.
Referenced by addPointToPolyline(), ccGraphicalSegmentationTool(), closePolyLine(), closeRectangle(), doActionUseExistingPolyline(), pauseSegmentationMode(), start(), updatePolyLine(), and ~ccGraphicalSegmentationTool().
m_rectangularSelection
bool ccGraphicalSegmentationTool::m_rectangularSelection protected
Selection mode.
Definition at line 138 of file ecvGraphicalSegmentationTool.h.
Referenced by addPointToPolyline(), closeRectangle(), doActionUseExistingPolyline(), doSetPolylineSelection(), doSetRectangularSelection(), onShortcutTriggered(), and pauseSegmentationMode().
m_segmentationPoly
ccPolyline* ccGraphicalSegmentationTool::m_segmentationPoly protected
Segmentation polyline.
Definition at line 133 of file ecvGraphicalSegmentationTool.h.
Referenced by addPointToPolyline(), ccGraphicalSegmentationTool(), closePolyLine(), closeRectangle(), doActionUseExistingPolyline(), doExportSegmentationPolyline(), getPolyLine(), linkWith(), pauseSegmentationMode(), resetSegmentation(), segment(), start(), stop(), updatePolyLine(), updateSegmentation(), and ~ccGraphicalSegmentationTool().
m_somethingHasChanged
bool ccGraphicalSegmentationTool::m_somethingHasChanged protected
Whether something has changed or not (for proper 'cancel')
Definition at line 115 of file ecvGraphicalSegmentationTool.h.
Referenced by reset(), segment(), and start().
m_state
unsigned ccGraphicalSegmentationTool::m_state protected
Current process state.
Definition at line 130 of file ecvGraphicalSegmentationTool.h.
Referenced by addPointToPolyline(), closePolyLine(), closeRectangle(), doActionUseExistingPolyline(), doSetPolylineSelection(), doSetRectangularSelection(), pauseSegmentationMode(), and updatePolyLine().
m_toSegment
QSet<ccHObject*> ccGraphicalSegmentationTool::m_toSegment protected
Set of entities to be segmented.
Definition at line 112 of file ecvGraphicalSegmentationTool.h.
Referenced by addEntity(), applySegmentation(), doExportSegmentationPolyline(), entities(), getNumberOfValidEntities(), removeAllEntities(), reset(), segment(), and setDrawFlag().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvGraphicalSegmentationTool.h
/root/ACloudViewer/app/ecvGraphicalSegmentationTool.cpp