ACloudViewer: colmap::Timer Class Reference
colmap::Timer Class Reference
#include <timer.h>
Public Member Functions
Timer ()
void Start ()
void Restart ()
void Pause ()
void Resume ()
void Reset ()
double ElapsedMicroSeconds () const
double ElapsedSeconds () const
double ElapsedMinutes () const
double ElapsedHours () const
void PrintSeconds () const
void PrintMinutes () const
void PrintHours () const
Detailed Description
Definition at line 14 of file timer.h.
Constructor & Destructor Documentation
Timer()
colmap::Timer::Timer ()
Definition at line 41 of file timer.cc.
Member Function Documentation
ElapsedHours()
double colmap::Timer::ElapsedHours () const
Definition at line 86 of file timer.cc.
References ElapsedMinutes().
Referenced by BOOST_AUTO_TEST_CASE(), and PrintHours().
ElapsedMicroSeconds()
double colmap::Timer::ElapsedMicroSeconds () const
Definition at line 69 of file timer.cc.
Referenced by BOOST_AUTO_TEST_CASE(), and ElapsedSeconds().
ElapsedMinutes()
double colmap::Timer::ElapsedMinutes () const
Definition at line 84 of file timer.cc.
References ElapsedSeconds().
Referenced by BOOST_AUTO_TEST_CASE(), ElapsedHours(), and PrintMinutes().
ElapsedSeconds()
double colmap::Timer::ElapsedSeconds () const
Definition at line 82 of file timer.cc.
References ElapsedMicroSeconds().
Referenced by BOOST_AUTO_TEST_CASE(), ElapsedMinutes(), colmap::DatabaseCache::Load(), PrintSeconds(), and colmap::RunVocabTreeRetriever().
Pause()
void colmap::Timer::Pause ()
Definition at line 54 of file timer.cc.
Referenced by colmap::Thread::BlockIfPaused(), and BOOST_AUTO_TEST_CASE().
PrintHours()
void colmap::Timer::PrintHours () const
Definition at line 98 of file timer.cc.
References ElapsedHours(), QtCompat::endl(), and colmap::StringPrintf().
PrintMinutes()
void colmap::Timer::PrintMinutes () const
Definition at line 93 of file timer.cc.
References ElapsedMinutes(), QtCompat::endl(), and colmap::StringPrintf().
Referenced by colmap::mvs::Workspace::Load(), colmap::RunImageRegistrator(), colmap::RunModelCropper(), colmap::RunModelSplitter(), and colmap::RunPointTriangulator().
PrintSeconds()
void colmap::Timer::PrintSeconds () const
Definition at line 88 of file timer.cc.
References ElapsedSeconds(), QtCompat::endl(), and colmap::StringPrintf().
Reset()
void colmap::Timer::Reset ()
Definition at line 64 of file timer.cc.
Referenced by BOOST_AUTO_TEST_CASE().
Restart()
void colmap::Timer::Restart ()
Definition at line 49 of file timer.cc.
References Start().
Referenced by colmap::DatabaseCache::Load(), and colmap::Thread::Start().
Resume()
void colmap::Timer::Resume ()
Definition at line 59 of file timer.cc.
Referenced by colmap::Thread::BlockIfPaused(), and BOOST_AUTO_TEST_CASE().
Start()
void colmap::Timer::Start ()
Definition at line 43 of file timer.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::DatabaseCache::Load(), colmap::mvs::Workspace::Load(), Restart(), colmap::RunImageRegistrator(), colmap::RunModelCropper(), colmap::RunModelSplitter(), colmap::RunPointTriangulator(), and colmap::RunVocabTreeRetriever().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/util/timer.h
/root/ACloudViewer/libs/Reconstruction/src/util/timer.cc