ACloudViewer: colmap::SiftFeatureMatcher Class Reference
colmap::SiftFeatureMatcher Class Reference
#include <matching.h>
Public Member Functions
SiftFeatureMatcher (const SiftMatchingOptions &options, Database *database, FeatureMatcherCache *cache)
~SiftFeatureMatcher ()
bool Setup ()
void Match (const std::vector< std::pair< image_t, image_t >> &image_pairs)
Detailed Description
Definition at line 333 of file matching.h.
Constructor & Destructor Documentation
SiftFeatureMatcher()
colmap::SiftFeatureMatcher::SiftFeatureMatcher (const SiftMatchingOptions & options, Database * database, FeatureMatcherCache * cache)
Definition at line 724 of file matching.cc.
~SiftFeatureMatcher()
colmap::SiftFeatureMatcher::~SiftFeatureMatcher ()
Definition at line 797 of file matching.cc.
Member Function Documentation
Match()
void colmap::SiftFeatureMatcher::Match (const std::vector< std::pair< image_t, image_t >> & image_pairs)
Definition at line 869 of file matching.cc.
References data, colmap::FeatureMatcherCache::DeleteInlierMatches(), colmap::FeatureMatcherCache::DeleteMatches(), colmap::FeatureMatcherCache::ExistsInlierMatches(), colmap::FeatureMatcherCache::ExistsMatches(), colmap::FeatureMatcherCache::GetMatches(), colmap::Database::ImagePairToPairId(), colmap::SiftMatchingOptions::min_num_inliers, colmap::FeatureMatcherCache::WriteMatches(), and colmap::FeatureMatcherCache::WriteTwoViewGeometry().
Setup()
bool colmap::SiftFeatureMatcher::Setup ()
Definition at line 833 of file matching.cc.
References colmap::SiftMatchingOptions::max_num_matches.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/feature/matching.h
/root/ACloudViewer/libs/Reconstruction/src/feature/matching.cc