ACloudViewer: ecvPoissonReconDlg Class Reference
ecvPoissonReconDlg Class Reference
#include <ecvPoissonReconDlg.h>
Public Member Functions
ecvPoissonReconDlg (QWidget *parent=0)
bool start ()
bool addEntity (ccHObject *ent)
ccHObject::Container & getReconstructions ()
Protected Member Functions
bool showDialog ()
bool doComputation ()
void updateParams ()
void adjustParams (ccPointCloud *cloud)
Detailed Description
Definition at line 21 of file ecvPoissonReconDlg.h.
Constructor & Destructor Documentation
ecvPoissonReconDlg()
ecvPoissonReconDlg::ecvPoissonReconDlg (QWidget * parent = 0) explicit
Definition at line 174 of file ecvPoissonReconDlg.cpp.
Member Function Documentation
addEntity()
bool ecvPoissonReconDlg::addEntity (ccHObject * ent)
Definition at line 269 of file ecvPoissonReconDlg.cpp.
References ccObject::isA(), ccObject::isKindOf(), and CV_TYPES::POINT_CLOUD.
adjustParams()
void ecvPoissonReconDlg::adjustParams (ccPointCloud * cloud) protected
Definition at line 185 of file ecvPoissonReconDlg.cpp.
References Parameters::boundary, Parameters::COUNT, Parameters::density, Parameters::depth, Parameters::DIRICHLET, Parameters::FREE, cloudViewer::BoundingBoxTpl< T >::getDiagNormd(), ccGenericPointCloud::getOwnBB(), ccPointCloud::hasColors(), Parameters::linearFit, Parameters::NEUMANN, Parameters::pointWeight, s_defaultResolution, s_depthMode, s_params, Parameters::samplesPerNode, and Parameters::withColors.
Referenced by start().
doComputation()
bool ecvPoissonReconDlg::doComputation () protected
Definition at line 221 of file ecvPoissonReconDlg.cpp.
References Parameters::depth, doReconstruct(), Parameters::finestCellWidth, ccObject::getName(), result, s_cloud, s_depthMode, s_params, cloudViewer::utility::Sleep(), and Parameters::threads.
Referenced by start().
getReconstructions()
ccHObject::Container & ecvPoissonReconDlg::getReconstructions ()
Definition at line 281 of file ecvPoissonReconDlg.cpp.
showDialog()
bool ecvPoissonReconDlg::showDialog () protected
Definition at line 418 of file ecvPoissonReconDlg.cpp.
References updateParams().
Referenced by start().
start()
bool ecvPoissonReconDlg::start ()
Definition at line 285 of file ecvPoissonReconDlg.cpp.
References ccHObject::addChild(), adjustParams(), ccDrawableObject::colorsShown(), ccMesh::computeNormals(), ccEntityAction::computeNormals(), count, Parameters::density, Parameters::depth, doComputation(), CVLog::Error(), ccMesh::getAssociatedCloud(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccObject::getName(), ccHObject::getParent(), ccPointCloud::hasColors(), ccEntityAction::importToSF(), ccObject::isKindOf(), CV_TYPES::POINT_CLOUD, CVLog::Print(), s_cloud, s_density, s_mesh, s_params, ccObject::setEnabled(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccObject::setName(), ccDrawableObject::setVisible(), ccDrawableObject::showColors(), showDialog(), ccDrawableObject::showSF(), cloudViewer::PointCloudTpl< T >::size(), ccMesh::size(), ccHObjectCaster::ToPointCloud(), ccPointCloud::unallocateColors(), updateParams(), CVLog::Warning(), and Parameters::withColors.
updateParams()
void ecvPoissonReconDlg::updateParams () protected
Definition at line 429 of file ecvPoissonReconDlg.cpp.
References Parameters::boundary, Parameters::COUNT, Parameters::density, Parameters::depth, Parameters::DIRICHLET, Parameters::finestCellWidth, Parameters::FREE, Parameters::linearFit, Parameters::NEUMANN, Parameters::pointWeight, s_defaultResolution, s_depthMode, s_params, Parameters::samplesPerNode, and Parameters::withColors.
Referenced by showDialog(), and start().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvPoissonReconDlg.h
/root/ACloudViewer/app/ecvPoissonReconDlg.cpp