ACloudViewer: colmap::CombinationSampler Class Reference
colmap::CombinationSampler Class Reference
#include <combination_sampler.h>
Public Member Functions
CombinationSampler (const size_t num_samples)
void Initialize (const size_t total_num_samples) override
size_t MaxNumSamples () override
std::vector< size_t > Sample () override
Public Member Functions inherited from colmap::Sampler
Sampler ()
Sampler (const size_t num_samples)
template<typename X_t >
void SampleX (const X_t &X, X_t *X_rand)
template<typename X_t , typename Y_t >
void SampleXY (const X_t &X, const Y_t &Y, X_t *X_rand, Y_t *Y_rand)
Detailed Description
Definition at line 18 of file combination_sampler.h.
Constructor & Destructor Documentation
CombinationSampler()
colmap::CombinationSampler::CombinationSampler (const size_t num_samples) explicit
Definition at line 41 of file combination_sampler.cc.
Member Function Documentation
Initialize()
void colmap::CombinationSampler::Initialize (const size_t total_num_samples) override virtual
Implements colmap::Sampler.
Definition at line 44 of file combination_sampler.cc.
Referenced by BOOST_AUTO_TEST_CASE().
MaxNumSamples()
size_t colmap::CombinationSampler::MaxNumSamples () override virtual
Implements colmap::Sampler.
Definition at line 51 of file combination_sampler.cc.
References colmap::NChooseK().
Referenced by BOOST_AUTO_TEST_CASE().
Sample()
std::vector< size_t > colmap::CombinationSampler::Sample () override virtual
Implements colmap::Sampler.
Definition at line 55 of file combination_sampler.cc.
References colmap::NextCombination().
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/optim/combination_sampler.h
/root/ACloudViewer/libs/Reconstruction/src/optim/combination_sampler.cc