ACloudViewer: AnglesCustomPlot Class Reference
AnglesCustomPlot Class Reference
#include <AnglesCustomPlot.h>
Signals
void closeTab ()
Public Member Functions
AnglesCustomPlot (const QVector< double > &data, const QString &xLabel, int nbBins, QWidget *parent=nullptr)
~AnglesCustomPlot ()
bool computeHistogram (const QVector< double > &data)
void createQCPBars (const QString &xLabel)
void rescale ()
QSharedPointer< QCPBarsDataContainer > dataContainer ()
void emitCloseTab ()
void mouseDoubleClickEvent (QMouseEvent *event) override
void mousePressEvent (QMouseEvent *event) override
Detailed Description
Definition at line 18 of file AnglesCustomPlot.h.
Constructor & Destructor Documentation
AnglesCustomPlot()
AnglesCustomPlot::AnglesCustomPlot (const QVector< double > & data, const QString & xLabel, int nbBins, QWidget * parent = nullptr) explicit
Definition at line 15 of file AnglesCustomPlot.cpp.
References computeHistogram(), and createQCPBars().
~AnglesCustomPlot()
AnglesCustomPlot::~AnglesCustomPlot ()
Definition at line 36 of file AnglesCustomPlot.cpp.
Member Function Documentation
closeTab
void AnglesCustomPlot::closeTab () signal
Referenced by G3PointPlots::addToTabWidget(), and emitCloseTab().
computeHistogram()
bool AnglesCustomPlot::computeHistogram (const QVector< double > & data)
Definition at line 41 of file AnglesCustomPlot.cpp.
References cloudViewer::utility::ceil(), count, MAX_HISTOGRAM_SIZE, min(), cloudViewer::ScalarField::ValidValue(), and CVLog::Warning().
Referenced by AnglesCustomPlot().
createQCPBars()
void AnglesCustomPlot::createQCPBars (const QString & xLabel)
Definition at line 92 of file AnglesCustomPlot.cpp.
References ecvColor::lighter().
Referenced by AnglesCustomPlot().
dataContainer()
QSharedPointer<QCPBarsDataContainer> AnglesCustomPlot::dataContainer () inline
Definition at line 33 of file AnglesCustomPlot.h.
emitCloseTab()
void AnglesCustomPlot::emitCloseTab () inline
Definition at line 37 of file AnglesCustomPlot.h.
References closeTab().
Referenced by mousePressEvent().
mouseDoubleClickEvent()
void AnglesCustomPlot::mouseDoubleClickEvent (QMouseEvent * event) override
Definition at line 119 of file AnglesCustomPlot.cpp.
References event, and rescale().
mousePressEvent()
void AnglesCustomPlot::mousePressEvent (QMouseEvent * event) override
Definition at line 126 of file AnglesCustomPlot.cpp.
References emitCloseTab(), and event.
rescale()
void AnglesCustomPlot::rescale ()
Definition at line 111 of file AnglesCustomPlot.cpp.
Referenced by mouseDoubleClickEvent().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qG3Point/include/AnglesCustomPlot.h
/root/ACloudViewer/plugins/core/Standard/qG3Point/src/AnglesCustomPlot.cpp