ACloudViewer: ColorScalarFieldWrapper Class Reference
ColorScalarFieldWrapper Class Reference
#include <ScalarFieldWrappers.h>
Public Types
enum Band { Red = 0 , Green = 1 , Blue = 2 }
Public Types inherited from IScalarFieldWrapper
using Shared = QSharedPointer< IScalarFieldWrapper >
Public Member Functions
ColorScalarFieldWrapper (const ccPointCloud *cloud, Band band)
virtual double pointValue (unsigned index) const override
virtual bool isValid () const
virtual QString getName () const
virtual size_t size () const override
Public Member Functions inherited from IScalarFieldWrapper
virtual ~IScalarFieldWrapper ()
Protected Attributes
const ccPointCloud * m_cloud
Band m_band
Detailed Description
Definition at line 138 of file ScalarFieldWrappers.h.
Member Enumeration Documentation
Band
enum ColorScalarFieldWrapper::Band
Enumerator
Red
Green
Blue
Definition at line 140 of file ScalarFieldWrappers.h.
Constructor & Destructor Documentation
ColorScalarFieldWrapper()
ColorScalarFieldWrapper::ColorScalarFieldWrapper (const ccPointCloud * cloud, Band band) inline
Definition at line 142 of file ScalarFieldWrappers.h.
Member Function Documentation
getName()
virtual QString ColorScalarFieldWrapper::getName () const inline virtual
Implements IScalarFieldWrapper.
Definition at line 151 of file ScalarFieldWrappers.h.
References m_band.
isValid()
virtual bool ColorScalarFieldWrapper::isValid () const inline virtual
Implements IScalarFieldWrapper.
Definition at line 148 of file ScalarFieldWrappers.h.
References ccPointCloud::hasColors(), and m_cloud.
pointValue()
virtual double ColorScalarFieldWrapper::pointValue (unsigned index) const inline override virtual
Implements IScalarFieldWrapper.
Definition at line 145 of file ScalarFieldWrappers.h.
References ccPointCloud::getPointColor(), m_band, m_cloud, and ecvColor::RgbTpl< Type >::rgb.
size()
virtual size_t ColorScalarFieldWrapper::size () const inline override virtual
Implements IScalarFieldWrapper.
Definition at line 155 of file ScalarFieldWrappers.h.
References m_cloud, and cloudViewer::PointCloudTpl< T >::size().
Member Data Documentation
m_band
Band ColorScalarFieldWrapper::m_band protected
Definition at line 159 of file ScalarFieldWrappers.h.
Referenced by getName(), and pointValue().
m_cloud
const ccPointCloud* ColorScalarFieldWrapper::m_cloud protected
Definition at line 158 of file ScalarFieldWrappers.h.
Referenced by isValid(), pointValue(), and size().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/q3DMASC/ScalarFieldWrappers.h