ACloudViewer: cloudViewer::core::nns::NearestNeighborSearch Class Reference
cloudViewer::core::nns::NearestNeighborSearch Class Reference
A Class for nearest neighbor search.
#include <NearestNeighborSearch.h>
Public Member Functions
NearestNeighborSearch (const Tensor &dataset_points, const Dtype &index_dtype=core::Int32)
~NearestNeighborSearch ()
NearestNeighborSearch (const NearestNeighborSearch &)=delete
NearestNeighborSearch & operator= (const NearestNeighborSearch &)=delete
bool KnnIndex ()
bool MultiRadiusIndex ()
bool FixedRadiusIndex (utility::optional< double > radius={})
bool HybridIndex (utility::optional< double > radius={})
std::pair< Tensor, Tensor > KnnSearch (const Tensor &query_points, int knn)
std::tuple< Tensor, Tensor, Tensor > FixedRadiusSearch (const Tensor &query_points, double radius, bool sort=true)
std::tuple< Tensor, Tensor, Tensor > MultiRadiusSearch (const Tensor &query_points, const Tensor &radii)
std::tuple< Tensor, Tensor, Tensor > HybridSearch (const Tensor &query_points, const double radius, const int max_knn) const
Protected Attributes
std::unique_ptr< NanoFlannIndex > nanoflann_index_
std::unique_ptr< nns::FixedRadiusIndex > fixed_radius_index_
std::unique_ptr< nns::KnnIndex > knn_index_
const Tensor dataset_points_
const Dtype index_dtype_
Detailed Description
A Class for nearest neighbor search.
Definition at line 26 of file NearestNeighborSearch.h.
Constructor & Destructor Documentation
NearestNeighborSearch() [1/2]
cloudViewer::core::nns::NearestNeighborSearch::NearestNeighborSearch (const Tensor & dataset_points, const Dtype & index_dtype = core::Int32) inline
Constructor.
Parameters
dataset_points Dataset points for constructing search index. Must be 2D, with shape {n, d}. SYCL tensors are not yet supported.
Definition at line 34 of file NearestNeighborSearch.h.
References cloudViewer::core::AssertNotSYCL(), and dataset_points_.
~NearestNeighborSearch()
cloudViewer::core::nns::NearestNeighborSearch::~NearestNeighborSearch ()
Definition at line 16 of file NearestNeighborSearch.cpp.
NearestNeighborSearch() [2/2]
cloudViewer::core::nns::NearestNeighborSearch::NearestNeighborSearch (const NearestNeighborSearch &) delete
Member Function Documentation
FixedRadiusIndex()
bool cloudViewer::core::nns::NearestNeighborSearch::FixedRadiusIndex (utility::optional< double > radius = {})
Set index for fixed-radius search.
Parameters
radius optional radius parameter. required for gpu fixed radius index.
Returns
Returns true if building index success, otherwise false.
Definition at line 40 of file NearestNeighborSearch.cpp.
References dataset_points_, fixed_radius_index_, cloudViewer::utility::optional< T >::has_value(), index_dtype_, cloudViewer::core::IsDevice::IsCUDA(), LogError, and cloudViewer::utility::optional< T >::value().
Referenced by cloudViewer::t::pipelines::registration::ComputeFPFHFeature(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingRadiusSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingRadiusSearchCPU(), cloudViewer::ml::contrib::RadiusSearch(), and cloudViewer::t::geometry::PointCloud::RemoveRadiusOutliers().
FixedRadiusSearch()
std::tuple< Tensor, Tensor, Tensor > cloudViewer::core::nns::NearestNeighborSearch::FixedRadiusSearch (const Tensor & query_points, double radius, bool sort = true)
Perform fixed radius search. All query points share the same radius.
Parameters
query_points Data points for querying. Must be 2D, with shape {n, d}.
radius Radius.
sort Sort the results by distance. Default is True.
Returns
Tuple of Tensors, (indices, distances, num_neighbors):
indices: Tensor of shape {total_number_of_neighbors,}, with dtype same as index_dtype_.
distances: Tensor of shape {total_number_of_neighbors,}, same dtype with query_points. The distances are squared L2 distances.
num_neighbors: Tensor of shape {n+1,}, with dtype Int64. The Tensor is a prefix sum of the number of neighbors for each query point.
Definition at line 98 of file NearestNeighborSearch.cpp.
References AssertTensorDevice, dataset_points_, fixed_radius_index_, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::IsDevice::IsCUDA(), LogError, and nanoflann_index_.
Referenced by cloudViewer::t::pipelines::registration::ComputeFPFHFeature(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingRadiusSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingRadiusSearchCPU(), cloudViewer::ml::contrib::RadiusSearch(), and cloudViewer::t::geometry::PointCloud::RemoveRadiusOutliers().
HybridIndex()
bool cloudViewer::core::nns::NearestNeighborSearch::HybridIndex (utility::optional< double > radius = {})
Set index for hybrid search.
Returns
Returns true if building index success, otherwise false.
Definition at line 60 of file NearestNeighborSearch.cpp.
References dataset_points_, fixed_radius_index_, cloudViewer::utility::optional< T >::has_value(), index_dtype_, cloudViewer::core::IsDevice::IsCUDA(), LogError, and cloudViewer::utility::optional< T >::value().
Referenced by cloudViewer::t::geometry::PointCloud::ComputeBoundaryPoints(), cloudViewer::t::pipelines::registration::ComputeFPFHFeature(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingHybridSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingHybridSearchCPU(), cloudViewer::t::pipelines::registration::EvaluateRegistration(), cloudViewer::t::pipelines::slac::GetCorrespondenceSetForPointCloudPair(), cloudViewer::t::pipelines::registration::GetInformationMatrix(), and cloudViewer::t::pipelines::registration::MultiScaleICP().
HybridSearch()
std::tuple< Tensor, Tensor, Tensor > cloudViewer::core::nns::NearestNeighborSearch::HybridSearch (const Tensor & query_points, const double radius, const int max_knn) const
Perform hybrid search.
Parameters
query_points Data points for querying. Must be 2D, with shape {n, d}.
radius Radius.
max_knn Maximum number of neighbor to search per query.
Returns
Tuple of Tensors, (indices, distances, counts):
indices: Tensor of shape {n, knn}, with dtype same as index_dtype_.
distances: Tensor of shape {n, knn}, with same dtype with query_points. The distances are squared L2 distances.
counts: Counts of neighbour for each query points. [Tensor of shape {n}, with dtype same as index_dtype_].
Definition at line 130 of file NearestNeighborSearch.cpp.
References AssertTensorDevice, dataset_points_, fixed_radius_index_, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::IsDevice::IsCUDA(), LogError, and nanoflann_index_.
Referenced by cloudViewer::t::geometry::PointCloud::ComputeBoundaryPoints(), cloudViewer::t::pipelines::registration::ComputeFPFHFeature(), cloudViewer::t::pipelines::registration::ComputeRegistrationResult(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingHybridSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingHybridSearchCPU(), cloudViewer::t::pipelines::slac::GetCorrespondenceSetForPointCloudPair(), cloudViewer::t::pipelines::registration::GetInformationMatrix(), and cloudViewer::core::nns::pybind_core_nns().
KnnIndex()
bool cloudViewer::core::nns::NearestNeighborSearch::KnnIndex ()
Set index for knn search.
Returns
Returns true if building index success, otherwise false.
Definition at line 23 of file NearestNeighborSearch.cpp.
References dataset_points_, index_dtype_, cloudViewer::core::IsDevice::IsCUDA(), knn_index_, and LogError.
Referenced by cloudViewer::t::pipelines::registration::ComputeFPFHFeature(), cloudViewer::t::geometry::PointCloud::ComputeMetrics(), cloudViewer::t::pipelines::registration::CorrespondencesFromFeatures(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingKNNSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingKNNSearchCPU(), cloudViewer::ml::contrib::KnnSearch(), cloudViewer::core::nns::pybind_core_nns(), and cloudViewer::t::geometry::PointCloud::RemoveStatisticalOutliers().
KnnSearch()
std::pair< Tensor, Tensor > cloudViewer::core::nns::NearestNeighborSearch::KnnSearch (const Tensor & query_points, int knn)
Perform knn search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}.
knn Number of neighbors to search per query point.
Returns
Pair of Tensors, (indices, distances):
indices: Tensor of shape {n, knn}, with dtype same as index_dtype_.
distances: Tensor of shape {n, knn}, same dtype with query_points. The distances are squared L2 distances.
Definition at line 79 of file NearestNeighborSearch.cpp.
References AssertTensorDevice, dataset_points_, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::IsDevice::IsCUDA(), knn_index_, LogError, and nanoflann_index_.
Referenced by cloudViewer::t::pipelines::registration::ComputeFPFHFeature(), cloudViewer::t::geometry::PointCloud::ComputeMetrics(), cloudViewer::t::pipelines::registration::CorrespondencesFromFeatures(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingKNNSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingKNNSearchCPU(), cloudViewer::ml::contrib::KnnSearch(), cloudViewer::core::nns::pybind_core_nns(), and cloudViewer::t::geometry::PointCloud::RemoveStatisticalOutliers().
MultiRadiusIndex()
bool cloudViewer::core::nns::NearestNeighborSearch::MultiRadiusIndex ()
Set index for multi-radius search.
Returns
Returns true if building index success, otherwise false.
Definition at line 38 of file NearestNeighborSearch.cpp.
Referenced by cloudViewer::core::nns::pybind_core_nns().
MultiRadiusSearch()
std::tuple< Tensor, Tensor, Tensor > cloudViewer::core::nns::NearestNeighborSearch::MultiRadiusSearch (const Tensor & query_points, const Tensor & radii)
Perform multi-radius search. Each query point has an independent radius.
Parameters
query_points Query points. Must be 2D, with shape {n, d}.
radii Radii of query points. Each query point has one radius. Must be 1D, with shape {n,}.
Returns
Tuple of Tensors, (indices,distances, num_neighbors):
indices: Tensor of shape {total_number_of_neighbors,}, with dtype same as index_dtype_.
distances: Tensor of shape {total_number_of_neighbors,}, same dtype with query_points. The distances are squared L2 distances.
num_neighbors: Tensor of shape {n+1,}, with dtype Int64. The Tensor is a prefix sum of the number of neighbors for each query point.
Definition at line 118 of file NearestNeighborSearch.cpp.
References AssertTensorDtype, dataset_points_, cloudViewer::core::Tensor::GetDtype(), LogError, nanoflann_index_, and radii.
Referenced by cloudViewer::core::nns::pybind_core_nns().
operator=()
NearestNeighborSearch& cloudViewer::core::nns::NearestNeighborSearch::operator= (const NearestNeighborSearch &) delete
Member Data Documentation
dataset_points_
const Tensor cloudViewer::core::nns::NearestNeighborSearch::dataset_points_ protected
Definition at line 132 of file NearestNeighborSearch.h.
Referenced by FixedRadiusIndex(), FixedRadiusSearch(), HybridIndex(), HybridSearch(), KnnIndex(), KnnSearch(), MultiRadiusSearch(), and NearestNeighborSearch().
fixed_radius_index_
std::unique_ptr<nns::FixedRadiusIndex> cloudViewer::core::nns::NearestNeighborSearch::fixed_radius_index_ protected
Definition at line 130 of file NearestNeighborSearch.h.
Referenced by FixedRadiusIndex(), FixedRadiusSearch(), HybridIndex(), and HybridSearch().
index_dtype_
const Dtype cloudViewer::core::nns::NearestNeighborSearch::index_dtype_ protected
Definition at line 133 of file NearestNeighborSearch.h.
Referenced by FixedRadiusIndex(), HybridIndex(), and KnnIndex().
knn_index_
std::unique_ptr<nns::KnnIndex> cloudViewer::core::nns::NearestNeighborSearch::knn_index_ protected
Definition at line 131 of file NearestNeighborSearch.h.
Referenced by KnnIndex(), and KnnSearch().
nanoflann_index_
std::unique_ptr<NanoFlannIndex> cloudViewer::core::nns::NearestNeighborSearch::nanoflann_index_ protected
Definition at line 129 of file NearestNeighborSearch.h.
Referenced by FixedRadiusSearch(), HybridSearch(), KnnSearch(), and MultiRadiusSearch().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/core/nns/NearestNeighborSearch.h
/root/ACloudViewer/libs/cloudViewer/core/nns/NearestNeighborSearch.cpp