ACloudViewer: flann::KNNSimpleResultSet< DistanceType > Class Template Reference
flann::KNNSimpleResultSet< DistanceType > Class Template Reference
#include <result_set.h>
Public Types
typedef DistanceIndex< DistanceType > DistIndex
Public Member Functions
KNNSimpleResultSet (size_t capacity_)
~KNNSimpleResultSet ()
void clear ()
size_t size () const
bool full () const
void addPoint (DistanceType dist, size_t index)
void copy (size_t *indices, DistanceType *dists, size_t num_elements, bool sorted=true)
DistanceType worstDist () const
Public Member Functions inherited from flann::ResultSet< DistanceType >
virtual ~ResultSet ()
Detailed Description
template<typename DistanceType>
class flann::KNNSimpleResultSet< DistanceType >
KNNSimpleResultSet does not ensure that the element it holds are unique. Is used in those cases where the nearest neighbour algorithm used does not attempt to insert the same element multiple times.
Definition at line 101 of file result_set.h.
Member Typedef Documentation
DistIndex
template<typename DistanceType > typedef DistanceIndex<DistanceType> flann::KNNSimpleResultSet< DistanceType >::DistIndex
Definition at line 104 of file result_set.h.
Constructor & Destructor Documentation
KNNSimpleResultSet()
template<typename DistanceType > flann::KNNSimpleResultSet< DistanceType >::KNNSimpleResultSet (size_t capacity_) inline
Definition at line 106 of file result_set.h.
References flann::KNNSimpleResultSet< DistanceType >::clear(), and max().
~KNNSimpleResultSet()
template<typename DistanceType > flann::KNNSimpleResultSet< DistanceType >::~KNNSimpleResultSet () inline
Definition at line 114 of file result_set.h.
Member Function Documentation
addPoint()
template<typename DistanceType > void flann::KNNSimpleResultSet< DistanceType >::addPoint (DistanceType dist, size_t index) inline virtual
Add a point to result set
Parameters
dist distance to point
index index of point
Implements flann::ResultSet< DistanceType >.
Definition at line 151 of file result_set.h.
References dist().
clear()
template<typename DistanceType > void flann::KNNSimpleResultSet< DistanceType >::clear () inline
Clears the result set
Definition at line 121 of file result_set.h.
References max().
Referenced by flann::NNIndex< Distance >::knnSearch(), and flann::KNNSimpleResultSet< DistanceType >::KNNSimpleResultSet().
copy()
template<typename DistanceType > void flann::KNNSimpleResultSet< DistanceType >::copy (size_t * indices, DistanceType * dists, size_t num_elements, bool sorted = true) inline
Copy indices and distances to output buffers
Parameters
indices
dists
num_elements Number of elements to copy
sorted Indicates if results should be sorted
Definition at line 180 of file result_set.h.
References min().
Referenced by flann::NNIndex< Distance >::knnSearch().
full()
template<typename DistanceType > bool flann::KNNSimpleResultSet< DistanceType >::full () const inline virtual
Radius search result set always reports full
Returns
Implements flann::ResultSet< DistanceType >.
Definition at line 141 of file result_set.h.
size()
template<typename DistanceType > size_t flann::KNNSimpleResultSet< DistanceType >::size () const inline
Returns
Number of elements in the result set
Definition at line 132 of file result_set.h.
Referenced by flann::NNIndex< Distance >::knnSearch().
worstDist()
template<typename DistanceType > DistanceType flann::KNNSimpleResultSet< DistanceType >::worstDist () const inline virtual
Implements flann::ResultSet< DistanceType >.
Definition at line 189 of file result_set.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/util/result_set.h