ACloudViewer: ccPointPropertiesDlg Class Reference
ccPointPropertiesDlg Class Reference
Dialog for simple point picking (information, distance, etc.)
#include <ecvPointPropertiesDlg.h>
Signals
void newLabel (ccHObject *)
Signal emitted when a new label is created.
Signals inherited from ccOverlayDialog
void processFinished (bool accepted)
Signal emitted when process is finished.
void shortcutTriggered (int key)
Signal emitted when an overridden key shortcut is pressed.
void shown ()
Signal emitted when a 'show' event is detected.
Public Member Functions
ccPointPropertiesDlg (ccPickingHub *pickingHub, QWidget *parent)
Default constructor.
virtual ~ccPointPropertiesDlg ()
Default destructor.
virtual bool start () override
Starts process.
virtual void stop (bool state) override
Stops process/dialog.
virtual bool linkWith (QWidget *win) override
Links the overlay dialog with a MDI window.
Public Member Functions inherited from ccPointPickingGenericInterface
ccPointPickingGenericInterface (ccPickingHub *pickingHub, QWidget *parent=nullptr)
Default constructor.
~ccPointPickingGenericInterface () override=default
Destructor.
void onItemPicked (const PickedItem &pi) override
Inherited from ccPickingListener.
Public Member Functions inherited from ccOverlayDialog
ccOverlayDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::FramelessWindowHint|Qt::Tool)
Default constructor.
~ccOverlayDialog () override
Destructor.
void reject () override
void addOverridenShortcut (Qt::Key key)
bool started () const
Returns whether the tool is currently started or not.
Public Member Functions inherited from ccPickingListener
virtual ~ccPickingListener ()=default
Protected Types
enum Mode { POINT_INFO , POINT_POINT_DISTANCE , POINTS_ANGLE , RECT_ZONE }
Picking mode.
Protected Slots
void onClose ()
void activatePointPropertiesDisplay ()
void activateDistanceDisplay ()
void activateAngleDisplay ()
void activate2DZonePicking ()
void initializeState ()
void exportCurrentLabel ()
void update2DZone (int x, int y, Qt::MouseButtons buttons)
void processClickedPoint (int x, int y)
void close2DZone ()
Protected Slots inherited from ccOverlayDialog
virtual void onLinkedWindowDeletion (QObject *object=nullptr)
Slot called when the linked window is deleted (calls 'onClose')
Protected Member Functions
void processPickedPoint (ccPointCloud *cloud, unsigned pointIndex, int x, int y) override
Generic method to process picked points.
Protected Member Functions inherited from ccOverlayDialog
bool eventFilter (QObject *obj, QEvent *e) override
Protected Attributes
Mode m_pickingMode
Current picking mode.
cc2DLabel * m_label
Associated 3D label.
cc2DViewportLabel * m_rect2DLabel
Associated 2D label.
Protected Attributes inherited from ccPointPickingGenericInterface
ccPickingHub * m_pickingHub
Picking hub.
Protected Attributes inherited from ccOverlayDialog
QWidget * m_associatedWin
Associated (MDI) window.
bool m_processing
Running/processing state.
QList< int > m_overriddenKeys
Overridden keys.
Detailed Description
Dialog for simple point picking (information, distance, etc.)
Definition at line 20 of file ecvPointPropertiesDlg.h.
Member Enumeration Documentation
Mode
enum ccPointPropertiesDlg::Mode protected
Picking mode.
Enumerator
POINT_INFO
POINT_POINT_DISTANCE
POINTS_ANGLE
RECT_ZONE
Definition at line 55 of file ecvPointPropertiesDlg.h.
Constructor & Destructor Documentation
ccPointPropertiesDlg()
ccPointPropertiesDlg::ccPointPropertiesDlg (ccPickingHub * pickingHub, QWidget * parent) explicit
Default constructor.
Definition at line 30 of file ecvPointPropertiesDlg.cpp.
References activate2DZonePicking(), activateAngleDisplay(), activateDistanceDisplay(), activatePointPropertiesDisplay(), exportCurrentLabel(), initializeState(), m_label, m_rect2DLabel, onClose(), ccDrawableObject::setSelected(), and ccDrawableObject::setVisible().
~ccPointPropertiesDlg()
ccPointPropertiesDlg::~ccPointPropertiesDlg () virtual
Default destructor.
Definition at line 62 of file ecvPointPropertiesDlg.cpp.
References m_label, and m_rect2DLabel.
Member Function Documentation
activate2DZonePicking
void ccPointPropertiesDlg::activate2DZonePicking () protected slot
Definition at line 157 of file ecvPointPropertiesDlg.cpp.
References ecvDisplayTools::INTERACT_SEND_ALL_SIGNALS, m_label, m_pickingMode, RECT_ZONE, ecvDisplayTools::SetInteractionMode(), and ccDrawableObject::setVisible().
Referenced by ccPointPropertiesDlg().
activateAngleDisplay
void ccPointPropertiesDlg::activateAngleDisplay () protected slot
Definition at line 145 of file ecvPointPropertiesDlg.cpp.
References m_label, m_pickingMode, m_rect2DLabel, POINTS_ANGLE, ecvDisplayTools::SetInteractionMode(), ccDrawableObject::setVisible(), and ecvDisplayTools::TRANSFORM_CAMERA().
Referenced by ccPointPropertiesDlg().
activateDistanceDisplay
void ccPointPropertiesDlg::activateDistanceDisplay () protected slot
Definition at line 133 of file ecvPointPropertiesDlg.cpp.
References m_label, m_pickingMode, m_rect2DLabel, POINT_POINT_DISTANCE, ecvDisplayTools::SetInteractionMode(), ccDrawableObject::setVisible(), and ecvDisplayTools::TRANSFORM_CAMERA().
Referenced by ccPointPropertiesDlg().
activatePointPropertiesDisplay
void ccPointPropertiesDlg::activatePointPropertiesDisplay () protected slot
Definition at line 119 of file ecvPointPropertiesDlg.cpp.
References ecvDisplayTools::GetCurrentScreen(), m_label, m_pickingMode, m_rect2DLabel, POINT_INFO, ecvDisplayTools::SetInteractionMode(), ccDrawableObject::setVisible(), and ecvDisplayTools::TRANSFORM_CAMERA().
Referenced by ccPointPropertiesDlg(), and start().
close2DZone
void ccPointPropertiesDlg::close2DZone () protected slot
Definition at line 337 of file ecvPointPropertiesDlg.cpp.
References ecvDisplayTools::GetCurrentScreen(), ccDrawableObject::isSelected(), ccDrawableObject::isVisible(), m_pickingMode, m_rect2DLabel, RECT_ZONE, s_last2DLabelComment(), ccObject::setName(), ccDrawableObject::setSelected(), ccDrawableObject::setVisible(), and cc2DViewportLabel::updateLabel().
Referenced by linkWith().
exportCurrentLabel
void ccPointPropertiesDlg::exportCurrentLabel () protected slot
Definition at line 177 of file ecvPointPropertiesDlg.cpp.
References ccHObject::addChild(), ecvDisplayTools::AddToOwnDB(), cc2DLabel::PickedPoint::cloud, cc2DLabel::displayPointLegend(), ecvDisplayTools::GetCurrentScreen(), cc2DLabel::getPickedPoint(), ccDrawableObject::isSelected(), ccDrawableObject::isVisible(), m_label, m_pickingMode, m_rect2DLabel, newLabel(), RECT_ZONE, ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::RemoveFromOwnDB(), cc2DLabel::setDisplayedIn2D(), ccDrawableObject::setRedraw(), ecvDisplayTools::SetRedrawRecursive(), ccDrawableObject::setSelected(), ccDrawableObject::setVisible(), cc2DLabel::size(), and ecvDisplayTools::USE_2D.
Referenced by ccPointPropertiesDlg().
initializeState
void ccPointPropertiesDlg::initializeState () protected slot
Definition at line 170 of file ecvPointPropertiesDlg.cpp.
References cc2DLabel::clear(), m_label, m_rect2DLabel, ccDrawableObject::setSelected(), and ccDrawableObject::setVisible().
Referenced by ccPointPropertiesDlg(), and stop().
linkWith()
bool ccPointPropertiesDlg::linkWith (QWidget * win) override virtual
Links the overlay dialog with a MDI window.
Warning: link can't be modified while dialog is displayed/process is running!
Returns
success
Reimplemented from ccPointPickingGenericInterface.
Definition at line 70 of file ecvPointPropertiesDlg.cpp.
References ecvDisplayTools::AddToOwnDB(), ecvDisplayTools::buttonReleased(), cc2DLabel::clear(), close2DZone(), ecvDisplayTools::GetCurrentScreen(), ecvDisplayTools::leftButtonClicked(), ccPointPickingGenericInterface::linkWith(), m_label, m_rect2DLabel, ecvDisplayTools::mouseMoved(), processClickedPoint(), ecvDisplayTools::RemoveFromOwnDB(), ecvDisplayTools::SetInteractionMode(), ccDrawableObject::setSelected(), ccDrawableObject::setVisible(), ecvDisplayTools::TheInstance(), ecvDisplayTools::TRANSFORM_CAMERA(), and update2DZone().
newLabel
void ccPointPropertiesDlg::newLabel (ccHObject *) signal
Signal emitted when a new label is created.
Referenced by exportCurrentLabel().
onClose
void ccPointPropertiesDlg::onClose () protected slot
Definition at line 117 of file ecvPointPropertiesDlg.cpp.
References stop().
Referenced by ccPointPropertiesDlg().
processClickedPoint
void ccPointPropertiesDlg::processClickedPoint (int x, int y) protected slot
Definition at line 268 of file ecvPointPropertiesDlg.cpp.
References ecvDisplayTools::GetCurrentScreen(), ecvDisplayTools::GetViewportParameters(), ccDrawableObject::isSelected(), m_pickingMode, m_rect2DLabel, RECT_ZONE, cc2DViewportLabel::roi(), ccObject::setName(), cc2DViewportObject::setParameters(), cc2DViewportLabel::setRoi(), ccDrawableObject::setSelected(), ccDrawableObject::setVisible(), ecvDisplayTools::ToVtkCoordinates(), cc2DViewportLabel::updateLabel(), Tuple3Tpl< Type >::x, x, Tuple3Tpl< Type >::y, and y.
Referenced by linkWith().
processPickedPoint()
void ccPointPropertiesDlg::processPickedPoint (ccPointCloud * cloud, unsigned pointIndex, int x, int y) override protected virtual
Generic method to process picked points.
Parameters
cloud picked point cloud
pointIndex point index in cloud
x picked pixel X position
y picked pixel Y position
Implements ccPointPickingGenericInterface.
Definition at line 222 of file ecvPointPropertiesDlg.cpp.
References cc2DLabel::addPickedPoint(), cc2DLabel::clear(), cc2DLabel::displayPointLegend(), ecvDisplayTools::GetCurrentScreen(), cc2DLabel::getLabelContent(), cc2DLabel::getName(), ecvDisplayTools::GlWidth(), m_label, m_pickingMode, ecvGui::Parameters(), POINT_INFO, POINT_POINT_DISTANCE, POINTS_ANGLE, CVLog::Print(), RECT_ZONE, ccObject::setEnabled(), cc2DLabel::setPosition(), ccDrawableObject::setVisible(), cc2DLabel::size(), cc2DLabel::updateLabel(), x, and y.
start()
bool ccPointPropertiesDlg::start () override virtual
Starts process.
Returns
success
Reimplemented from ccPointPickingGenericInterface.
Definition at line 102 of file ecvPointPropertiesDlg.cpp.
References activatePointPropertiesDisplay(), and ccPointPickingGenericInterface::start().
stop()
void ccPointPropertiesDlg::stop (bool accepted) override virtual
Stops process/dialog.
Automatically emits the 'processFinished' signal (with input state as argument).
Parameters
accepted process/dialog result
Reimplemented from ccPointPickingGenericInterface.
Definition at line 107 of file ecvPointPropertiesDlg.cpp.
References ecvDisplayTools::GetCurrentScreen(), initializeState(), ecvDisplayTools::SetInteractionMode(), ccPointPickingGenericInterface::stop(), and ecvDisplayTools::TRANSFORM_CAMERA().
Referenced by onClose().
update2DZone
void ccPointPropertiesDlg::update2DZone (int x, int y, Qt::MouseButtons buttons) protected slot
Definition at line 308 of file ecvPointPropertiesDlg.cpp.
References ecvDisplayTools::GetCurrentScreen(), ccDrawableObject::isSelected(), m_pickingMode, m_rect2DLabel, RECT_ZONE, cc2DViewportLabel::roi(), cc2DViewportLabel::setRoi(), ccDrawableObject::setVisible(), ecvDisplayTools::ToVtkCoordinates(), cc2DViewportLabel::updateLabel(), Tuple3Tpl< Type >::x, x, Tuple3Tpl< Type >::y, and y.
Referenced by linkWith().
Member Data Documentation
m_label
cc2DLabel* ccPointPropertiesDlg::m_label protected
Associated 3D label.
Definition at line 67 of file ecvPointPropertiesDlg.h.
Referenced by activate2DZonePicking(), activateAngleDisplay(), activateDistanceDisplay(), activatePointPropertiesDisplay(), ccPointPropertiesDlg(), exportCurrentLabel(), initializeState(), linkWith(), processPickedPoint(), and ~ccPointPropertiesDlg().
m_pickingMode
Mode ccPointPropertiesDlg::m_pickingMode protected
Current picking mode.
Definition at line 64 of file ecvPointPropertiesDlg.h.
Referenced by activate2DZonePicking(), activateAngleDisplay(), activateDistanceDisplay(), activatePointPropertiesDisplay(), close2DZone(), exportCurrentLabel(), processClickedPoint(), processPickedPoint(), and update2DZone().
m_rect2DLabel
cc2DViewportLabel* ccPointPropertiesDlg::m_rect2DLabel protected
Associated 2D label.
Definition at line 70 of file ecvPointPropertiesDlg.h.
Referenced by activateAngleDisplay(), activateDistanceDisplay(), activatePointPropertiesDisplay(), ccPointPropertiesDlg(), close2DZone(), exportCurrentLabel(), initializeState(), linkWith(), processClickedPoint(), update2DZone(), and ~ccPointPropertiesDlg().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvPointPropertiesDlg.h
/root/ACloudViewer/app/ecvPointPropertiesDlg.cpp