ACloudViewer: MinimumCutSegmentation Class Reference
MinimumCutSegmentation Class Reference
Region Growing Segmentation.
#include <MinimumCutSegmentation.h>
Public Member Functions
MinimumCutSegmentation ()
virtual ~MinimumCutSegmentation ()
virtual int compute ()
Performs the actual filter job.
Public Member Functions inherited from BasePclModule
BasePclModule (PclModuleDescription desc=PclModuleDescription(), ccPluginInterface *parent_plugin=0)
Default constructor.
QAction * getAction ()
Get the action associated with the button used in menu and toolbar creation.
QString getStatusTip () const
Returns the status tip.
QString getModuleName () const
Returns the name of the filter.
QString getEntryName () const
Returns the entry name.
QIcon getIcon () const
Returns the icon associated with the button.
void setShowProgressBar (bool status)
Sets whether to show a progressbar while computing or not.
std::vector< std::string > getSelectedAvailableScalarFields ()
ccPointCloud * getSelectedEntityAsCCPointCloud () const
Returns the first selected entity as a ccPointCloud.
ccHObject * getSelectedEntityAsCCHObject () const
Returns the first selected entity as a ccHObject.
ccHObject::Container getSelectedThatHaveMetaData (const QString key) const
Get selected object that also have the provided metadata key.
void getAllEntitiesOfType (CV_CLASS_ENUM type, ccHObject::Container &entities)
Returns all the objects in db tree of type "type".
void getAllEntitiesThatHaveMetaData (QString key, ccHObject::Container &entities)
void getSelectedEntitiesThatAreCCPointCloud (ccHObject::Container &entities)
get all entities that are selected and that also are cc_point_cloud
void getSelectedEntitiesThatAre (CV_CLASS_ENUM kind, ccHObject::Container &entities)
int hasSelectedRGB ()
Returns 1 if the first selected entity has RGB info.
int hasSelectedScalarField ()
Returns 1 if the first selected entity has at least one scalar field.
int hasSelectedScalarField (std::string field_name)
int isFirstSelectedCcPointCloud ()
Returns 1 if the first selected object is a ccPointCloud.
virtual void updateSelectedEntities (const ccHObject::Container &selectedEntities)
Updates the internal copy of selected entities.
void setMainAppInterface (ecvMainAppInterface *app)
Sets associated CC application interface (to access DB)
ecvMainAppInterface * getMainAppInterface ()
ccPluginInterface * getParentPlugin () const
Returns the associated parent plugin interface.
Protected Member Functions
virtual int checkSelected ()
Checks if current selection is compliant with the filter.
virtual int openInputDialog ()
virtual void getParametersFromDialog ()
Collects parameters from the filter dialog (if openDialog is successful)
virtual int checkParameters ()
virtual QString getErrorMessage (int errorCode)
Returns the error message corresponding to a given error code.
Protected Member Functions inherited from BasePclModule
virtual int openOutputDialog ()
virtual int start ()
Starts computation.
virtual void initAction ()
Initializes the corresponding action.
void throwError (int errCode)
Protected Attributes
MinimumCutSegmentationDlg * m_dialog
bool m_colored
int m_neighboursNumber
float m_smoothSigma
float m_backWeightRadius
float m_foregroundWeight
float m_cx
float m_cy
float m_cz
Protected Attributes inherited from BasePclModule
QAction * m_action
Forces the Ui to be updated.
ccHObject::Container m_selected
Pointer to the main window.
PclModuleDescription m_desc
Associated dialog.
ecvMainAppInterface * m_app
Associated application interface.
ccPluginInterface * m_parent_plugin
associated parent plugin of the filter
bool m_show_progress
Do we want to show a progress bar when the filter works?
Additional Inherited Members
Signals inherited from BasePclModule
void entityHasChanged (ccHObject *)
Signal emitted when an entity is (visually) modified.
void newEntity (ccHObject *)
Signal emitted when a new entity is created by the filter.
void newErrorMessage (QString)
Signal emitted when a new error message is produced.
Protected Slots inherited from BasePclModule
int performAction ()
Returns is called when the dialog window is accepted.
Detailed Description
Region Growing Segmentation.
Definition at line 18 of file MinimumCutSegmentation.h.
Constructor & Destructor Documentation
MinimumCutSegmentation()
MinimumCutSegmentation::MinimumCutSegmentation ()
Definition at line 29 of file MinimumCutSegmentation.cpp.
~MinimumCutSegmentation()
MinimumCutSegmentation::~MinimumCutSegmentation () virtual
Definition at line 45 of file MinimumCutSegmentation.cpp.
References m_dialog.
Member Function Documentation
checkParameters()
int MinimumCutSegmentation::checkParameters () protected virtual
Checks that the parameters retrieved by getParametersFromDialog are valid Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Returns
1 if parameters are valid (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 90 of file MinimumCutSegmentation.cpp.
checkSelected()
int MinimumCutSegmentation::checkSelected () protected virtual
Checks if current selection is compliant with the filter.
If not, an error is returned and computation stops. By default, baseclass method simply checks that selection is composed of one and only one ccPointCloud. This method should be overridden if necessary.
Returns
1 if selection is compliant (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 50 of file MinimumCutSegmentation.cpp.
References BasePclModule::isFirstSelectedCcPointCloud().
compute()
int MinimumCutSegmentation::compute () virtual
Performs the actual filter job.
This method MUST be re-implemented by derived filter
Returns
1 if successful (error code otherwise)
Implements BasePclModule.
Definition at line 92 of file MinimumCutSegmentation.cpp.
References ccHObject::addChild(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccObject::getName(), ccHObject::getParent(), BasePclModule::getSelectedEntityAsCCPointCloud(), m_backWeightRadius, m_colored, m_cx, m_cy, m_cz, m_foregroundWeight, m_neighboursNumber, m_smoothSigma, BasePclModule::newEntity(), result, ccObject::setEnabled(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), and ccObject::setName().
getErrorMessage()
QString MinimumCutSegmentation::getErrorMessage (int errorCode) protected virtual
Returns the error message corresponding to a given error code.
Each filter have a set of possible error message to be used given bt getFilterErrorMessage() Baseclass implementation provides some generic messages.
Note
These messages can be replaced by re-implementing this method and handling the same codes BEFORE calling the baseclass method
Reimplemented from BasePclModule.
Definition at line 156 of file MinimumCutSegmentation.cpp.
References BasePclModule::getErrorMessage().
getParametersFromDialog()
void MinimumCutSegmentation::getParametersFromDialog () protected virtual
Collects parameters from the filter dialog (if openDialog is successful)
Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Reimplemented from BasePclModule.
Definition at line 75 of file MinimumCutSegmentation.cpp.
References m_backWeightRadius, m_cx, m_cy, m_cz, m_dialog, m_foregroundWeight, m_neighboursNumber, and m_smoothSigma.
openInputDialog()
int MinimumCutSegmentation::openInputDialog () protected virtual
Opens the input dialog window. Where the user can supply parameters for the computation Automatically called by performAction. Does nothing by default. Must be overridden if a dialog must be displayed.
Returns
1 if dialog has been successfully executed, 0 if canceled, negative error code otherwise
Reimplemented from BasePclModule.
Definition at line 58 of file MinimumCutSegmentation.cpp.
References BasePclModule::getSelectedEntityAsCCPointCloud(), ccPointCloud::hasColors(), ccPointCloud::hasScalarFields(), BasePclModule::m_app, m_colored, m_dialog, and MinimumCutSegmentationDlg::refreshLabelComboBox().
Member Data Documentation
m_backWeightRadius
float MinimumCutSegmentation::m_backWeightRadius protected
Definition at line 40 of file MinimumCutSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_colored
bool MinimumCutSegmentation::m_colored protected
Definition at line 36 of file MinimumCutSegmentation.h.
Referenced by compute(), and openInputDialog().
m_cx
float MinimumCutSegmentation::m_cx protected
Definition at line 43 of file MinimumCutSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_cy
float MinimumCutSegmentation::m_cy protected
Definition at line 44 of file MinimumCutSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_cz
float MinimumCutSegmentation::m_cz protected
Definition at line 45 of file MinimumCutSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_dialog
MinimumCutSegmentationDlg* MinimumCutSegmentation::m_dialog protected
Definition at line 34 of file MinimumCutSegmentation.h.
Referenced by getParametersFromDialog(), openInputDialog(), and ~MinimumCutSegmentation().
m_foregroundWeight
float MinimumCutSegmentation::m_foregroundWeight protected
Definition at line 41 of file MinimumCutSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_neighboursNumber
int MinimumCutSegmentation::m_neighboursNumber protected
Definition at line 38 of file MinimumCutSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_smoothSigma
float MinimumCutSegmentation::m_smoothSigma protected
Definition at line 39 of file MinimumCutSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Segmentations/MinimumCutSegmentation.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Segmentations/MinimumCutSegmentation.cpp