ACloudViewer: ccMPlaneDlg Class Reference
ccMPlaneDlg Class Reference
#include <ccMPlaneDlg.h>
Signals
void signalMeasureNameChanged (QTableWidgetItem *item)
void signalCloseButtonPressed ()
void signalFittingPointClicked (int index)
void signalTabChanged (int tab)
void signalMeasurementModeChanged ()
void signalFittingPointDelete (int index)
void signalShowNormalCheckBoxClicked (bool checked)
void signalSaveButtonClicked ()
Signals inherited from ccOverlayDialog
void processFinished (bool accepted)
Signal emitted when process is finished.
void shortcutTriggered (int key)
Signal emitted when an overridden key shortcut is pressed.
void shown ()
Signal emitted when a 'show' event is detected.
Public Member Functions
ccMPlaneDlg (QWidget *parent=0)
Default constructor.
void initializeFittingPointTable ()
void addFittingPoint (int rowIndex, const CCVector3 &point)
void selectFittingPoint (unsigned int rowIndex)
void clearFittingPoints ()
void addMeasurementPoint (const QString &name, float distance)
void renameMeasurement (const QString &name, unsigned int rowIndex)
void enableMeasurementTab (bool enable)
void clearMeasurementPoints ()
bool isSignedMeasurement () const
bool isNormalVectorChecked () const
Public Member Functions inherited from ccOverlayDialog
ccOverlayDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::FramelessWindowHint|Qt::Tool)
Default constructor.
~ccOverlayDialog () override
Destructor.
virtual bool linkWith (QWidget *win)
Links the overlay dialog with a MDI window.
virtual bool start ()
Starts process.
virtual void stop (bool accepted)
Stops process/dialog.
void reject () override
void addOverridenShortcut (Qt::Key key)
bool started () const
Returns whether the tool is currently started or not.
Protected Slots
void onMeasurementPointNameChanged (QTableWidgetItem *item)
void onCloseButtonPressed ()
void onTabChanged (int tab)
void onRadioButtonClicked ()
void onDeleteButtonClicked ()
void onShowNormalCheckBox (bool checked)
void onSaveButtonClicked ()
Protected Slots inherited from ccOverlayDialog
virtual void onLinkedWindowDeletion (QObject *object=nullptr)
Slot called when the linked window is deleted (calls 'onClose')
Additional Inherited Members
Protected Member Functions inherited from ccOverlayDialog
bool eventFilter (QObject *obj, QEvent *e) override
Protected Attributes inherited from ccOverlayDialog
QWidget * m_associatedWin
Associated (MDI) window.
bool m_processing
Running/processing state.
QList< int > m_overriddenKeys
Overridden keys.
Detailed Description
Definition at line 24 of file ccMPlaneDlg.h.
Constructor & Destructor Documentation
ccMPlaneDlg()
ccMPlaneDlg::ccMPlaneDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 19 of file ccMPlaneDlg.cpp.
References onCloseButtonPressed(), and onTabChanged().
Member Function Documentation
addFittingPoint()
void ccMPlaneDlg::addFittingPoint (int rowIndex, const CCVector3 & point)
Definition at line 194 of file ccMPlaneDlg.cpp.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
addMeasurementPoint()
void ccMPlaneDlg::addMeasurementPoint (const QString & name, float distance)
Definition at line 243 of file ccMPlaneDlg.cpp.
References Utils::distance(), and name.
clearFittingPoints()
void ccMPlaneDlg::clearFittingPoints ()
Definition at line 238 of file ccMPlaneDlg.cpp.
References initializeFittingPointTable().
Referenced by ccMPlaneDlgController::onCloseButtonPressed().
clearMeasurementPoints()
void ccMPlaneDlg::clearMeasurementPoints ()
Definition at line 276 of file ccMPlaneDlg.cpp.
Referenced by ccMPlaneDlgController::onCloseButtonPressed().
enableMeasurementTab()
void ccMPlaneDlg::enableMeasurementTab (bool enable)
Definition at line 272 of file ccMPlaneDlg.cpp.
initializeFittingPointTable()
void ccMPlaneDlg::initializeFittingPointTable ()
Definition at line 288 of file ccMPlaneDlg.cpp.
Referenced by clearFittingPoints().
isNormalVectorChecked()
bool ccMPlaneDlg::isNormalVectorChecked () const
Definition at line 284 of file ccMPlaneDlg.cpp.
isSignedMeasurement()
bool ccMPlaneDlg::isSignedMeasurement () const
Definition at line 280 of file ccMPlaneDlg.cpp.
Referenced by ccMPlaneDlgController::onMeasurementModeChanged().
onCloseButtonPressed
void ccMPlaneDlg::onCloseButtonPressed () protected slot
Definition at line 303 of file ccMPlaneDlg.cpp.
References signalCloseButtonPressed().
Referenced by ccMPlaneDlg().
onDeleteButtonClicked
void ccMPlaneDlg::onDeleteButtonClicked () protected slot
Definition at line 311 of file ccMPlaneDlg.cpp.
References signalFittingPointDelete().
onMeasurementPointNameChanged
void ccMPlaneDlg::onMeasurementPointNameChanged (QTableWidgetItem * item) protected slot
Definition at line 326 of file ccMPlaneDlg.cpp.
References signalMeasureNameChanged().
onRadioButtonClicked
void ccMPlaneDlg::onRadioButtonClicked () protected slot
Definition at line 307 of file ccMPlaneDlg.cpp.
References signalMeasurementModeChanged().
onSaveButtonClicked
void ccMPlaneDlg::onSaveButtonClicked () protected slot
Definition at line 324 of file ccMPlaneDlg.cpp.
References signalSaveButtonClicked().
onShowNormalCheckBox
void ccMPlaneDlg::onShowNormalCheckBox (bool checked) protected slot
Definition at line 320 of file ccMPlaneDlg.cpp.
References signalShowNormalCheckBoxClicked().
onTabChanged
void ccMPlaneDlg::onTabChanged (int tab) protected slot
Definition at line 305 of file ccMPlaneDlg.cpp.
References signalTabChanged().
Referenced by ccMPlaneDlg().
renameMeasurement()
void ccMPlaneDlg::renameMeasurement (const QString & name, unsigned int rowIndex)
Definition at line 265 of file ccMPlaneDlg.cpp.
References name.
Referenced by ccMPlaneDlgController::onMeasureNameChanged().
selectFittingPoint()
void ccMPlaneDlg::selectFittingPoint (unsigned int rowIndex)
Definition at line 234 of file ccMPlaneDlg.cpp.
Referenced by ccMPlaneDlgController::onFittingPointDelete(), and ccMPlaneDlgController::onItemPicked().
signalCloseButtonPressed
void ccMPlaneDlg::signalCloseButtonPressed () signal
Referenced by ccMPlaneDlgController::ccMPlaneDlgController(), and onCloseButtonPressed().
signalFittingPointClicked
void ccMPlaneDlg::signalFittingPointClicked (int index) signal
signalFittingPointDelete
void ccMPlaneDlg::signalFittingPointDelete (int index) signal
Referenced by ccMPlaneDlgController::ccMPlaneDlgController(), and onDeleteButtonClicked().
signalMeasurementModeChanged
void ccMPlaneDlg::signalMeasurementModeChanged () signal
Referenced by ccMPlaneDlgController::ccMPlaneDlgController(), and onRadioButtonClicked().
signalMeasureNameChanged
void ccMPlaneDlg::signalMeasureNameChanged (QTableWidgetItem * item) signal
Referenced by ccMPlaneDlgController::ccMPlaneDlgController(), and onMeasurementPointNameChanged().
signalSaveButtonClicked
void ccMPlaneDlg::signalSaveButtonClicked () signal
Referenced by ccMPlaneDlgController::ccMPlaneDlgController(), and onSaveButtonClicked().
signalShowNormalCheckBoxClicked
void ccMPlaneDlg::signalShowNormalCheckBoxClicked (bool checked) signal
Referenced by ccMPlaneDlgController::ccMPlaneDlgController(), and onShowNormalCheckBox().
signalTabChanged
void ccMPlaneDlg::signalTabChanged (int tab) signal
Referenced by ccMPlaneDlgController::ccMPlaneDlgController(), and onTabChanged().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qMPlane/src/ccMPlaneDlg.h
/root/ACloudViewer/plugins/core/Standard/qMPlane/src/ccMPlaneDlg.cpp