ACloudViewer: cloudViewer::visualization::gui::GLFWWindowSystem Class Reference
cloudViewer::visualization::gui::GLFWWindowSystem Class Reference
#include <GLFWWindowSystem.h>
Public Member Functions
GLFWWindowSystem ()
~GLFWWindowSystem ()
void Initialize () override
void Uninitialize () override
void WaitEventsTimeout (double timeout_secs) override
Size GetScreenSize (OSWindow w) override
OSWindow CreateOSWindow (Window *o3d_window, int width, int height, const char *title, int flags) override
void DestroyWindow (OSWindow w) override
void PostRedrawEvent (OSWindow w) override
bool GetWindowIsVisible (OSWindow w) const override
void ShowWindow (OSWindow w, bool show) override
void RaiseWindowToTop (OSWindow w) override
bool IsActiveWindow (OSWindow w) const override
Point GetWindowPos (OSWindow w) const override
void SetWindowPos (OSWindow w, int x, int y) override
Size GetWindowSize (OSWindow w) const override
void SetWindowSize (OSWindow w, int width, int height) override
Size GetWindowSizePixels (OSWindow w) const override
void SetWindowSizePixels (OSWindow w, const Size &size) override
float GetWindowScaleFactor (OSWindow w) const override
float GetUIScaleFactor (OSWindow w) const override
void SetWindowTitle (OSWindow w, const char *title) override
Point GetMousePosInWindow (OSWindow w) const override
int GetMouseButtons (OSWindow w) const override
void CancelUserClose (OSWindow w) override
void * GetNativeDrawable (OSWindow w) override
rendering::FilamentRenderer * CreateRenderer (OSWindow w) override
void ResizeRenderer (OSWindow w, rendering::FilamentRenderer *renderer) override
MenuBase * CreateOSMenu () override
Public Member Functions inherited from cloudViewer::visualization::gui::WindowSystem
virtual ~WindowSystem ()
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::gui::WindowSystem
using OSWindow = void *
Static Public Attributes inherited from cloudViewer::visualization::gui::WindowSystem
static constexpr int FLAG_VISIBLE = 0
static constexpr int FLAG_HIDDEN = (1 << 0)
static constexpr int FLAG_TOPMOST = (1 << 1)
Detailed Description
Definition at line 18 of file GLFWWindowSystem.h.
Constructor & Destructor Documentation
GLFWWindowSystem()
cloudViewer::visualization::gui::GLFWWindowSystem::GLFWWindowSystem ()
Definition at line 97 of file GLFWWindowSystem.cpp.
~GLFWWindowSystem()
cloudViewer::visualization::gui::GLFWWindowSystem::~GLFWWindowSystem ()
Definition at line 99 of file GLFWWindowSystem.cpp.
Member Function Documentation
CancelUserClose()
void cloudViewer::visualization::gui::GLFWWindowSystem::CancelUserClose (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 295 of file GLFWWindowSystem.cpp.
CreateOSMenu()
MenuBase * cloudViewer::visualization::gui::GLFWWindowSystem::CreateOSMenu () override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 535 of file GLFWWindowSystem.cpp.
CreateOSWindow()
GLFWWindowSystem::OSWindow cloudViewer::visualization::gui::GLFWWindowSystem::CreateOSWindow (Window * o3d_window, int width, int height, const char * title, int flags) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 148 of file GLFWWindowSystem.cpp.
References cloudViewer::visualization::gui::WindowSystem::FLAG_HIDDEN, cloudViewer::visualization::gui::WindowSystem::FLAG_TOPMOST, height, NULL, o3d_window, and width.
CreateRenderer()
rendering::FilamentRenderer * cloudViewer::visualization::gui::GLFWWindowSystem::CreateRenderer (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 519 of file GLFWWindowSystem.cpp.
References cloudViewer::visualization::rendering::EngineInstance::GetInstance(), GetNativeDrawable(), and cloudViewer::visualization::rendering::EngineInstance::GetResourceManager().
DestroyWindow()
void cloudViewer::visualization::gui::GLFWWindowSystem::DestroyWindow (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 189 of file GLFWWindowSystem.cpp.
GetMouseButtons()
int cloudViewer::visualization::gui::GLFWWindowSystem::GetMouseButtons (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 280 of file GLFWWindowSystem.cpp.
References cloudViewer::visualization::gui::LEFT, cloudViewer::visualization::gui::MIDDLE, and cloudViewer::visualization::gui::RIGHT.
GetMousePosInWindow()
Point cloudViewer::visualization::gui::GLFWWindowSystem::GetMousePosInWindow (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 273 of file GLFWWindowSystem.cpp.
References GetWindowScaleFactor(), and scaling.
GetNativeDrawable()
void * cloudViewer::visualization::gui::GLFWWindowSystem::GetNativeDrawable (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 515 of file GLFWWindowSystem.cpp.
References cloudViewer::visualization::gui::GetNativeDrawable().
Referenced by CreateRenderer().
GetScreenSize()
Size cloudViewer::visualization::gui::GLFWWindowSystem::GetScreenSize (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 125 of file GLFWWindowSystem.cpp.
GetUIScaleFactor()
float cloudViewer::visualization::gui::GLFWWindowSystem::GetUIScaleFactor (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 263 of file GLFWWindowSystem.cpp.
GetWindowIsVisible()
bool cloudViewer::visualization::gui::GLFWWindowSystem::GetWindowIsVisible (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 197 of file GLFWWindowSystem.cpp.
GetWindowPos()
Point cloudViewer::visualization::gui::GLFWWindowSystem::GetWindowPos (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 217 of file GLFWWindowSystem.cpp.
GetWindowScaleFactor()
float cloudViewer::visualization::gui::GLFWWindowSystem::GetWindowScaleFactor (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 248 of file GLFWWindowSystem.cpp.
Referenced by GetMousePosInWindow().
GetWindowSize()
Size cloudViewer::visualization::gui::GLFWWindowSystem::GetWindowSize (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 227 of file GLFWWindowSystem.cpp.
References height, and width.
GetWindowSizePixels()
Size cloudViewer::visualization::gui::GLFWWindowSystem::GetWindowSizePixels (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 237 of file GLFWWindowSystem.cpp.
References height, and width.
Initialize()
void cloudViewer::visualization::gui::GLFWWindowSystem::Initialize () override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 101 of file GLFWWindowSystem.cpp.
IsActiveWindow()
bool cloudViewer::visualization::gui::GLFWWindowSystem::IsActiveWindow (OSWindow w) const override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 213 of file GLFWWindowSystem.cpp.
PostRedrawEvent()
void cloudViewer::visualization::gui::GLFWWindowSystem::PostRedrawEvent (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 193 of file GLFWWindowSystem.cpp.
References cloudViewer::visualization::gui::PostNativeExposeEvent().
RaiseWindowToTop()
void cloudViewer::visualization::gui::GLFWWindowSystem::RaiseWindowToTop (OSWindow w) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 209 of file GLFWWindowSystem.cpp.
ResizeRenderer()
void cloudViewer::visualization::gui::GLFWWindowSystem::ResizeRenderer (OSWindow w, rendering::FilamentRenderer * renderer) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 525 of file GLFWWindowSystem.cpp.
References cloudViewer::visualization::rendering::FilamentRenderer::UpdateSwapChain().
SetWindowPos()
void cloudViewer::visualization::gui::GLFWWindowSystem::SetWindowPos (OSWindow w, int x, int y) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 223 of file GLFWWindowSystem.cpp.
SetWindowSize()
void cloudViewer::visualization::gui::GLFWWindowSystem::SetWindowSize (OSWindow w, int width, int height) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 233 of file GLFWWindowSystem.cpp.
References height, and width.
SetWindowSizePixels()
void cloudViewer::visualization::gui::GLFWWindowSystem::SetWindowSizePixels (OSWindow w, const Size & size) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 243 of file GLFWWindowSystem.cpp.
References QtCompat::endl().
SetWindowTitle()
void cloudViewer::visualization::gui::GLFWWindowSystem::SetWindowTitle (OSWindow w, const char * title) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 269 of file GLFWWindowSystem.cpp.
ShowWindow()
void cloudViewer::visualization::gui::GLFWWindowSystem::ShowWindow (OSWindow w, bool show) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 201 of file GLFWWindowSystem.cpp.
Uninitialize()
void cloudViewer::visualization::gui::GLFWWindowSystem::Uninitialize () override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 115 of file GLFWWindowSystem.cpp.
WaitEventsTimeout()
void cloudViewer::visualization::gui::GLFWWindowSystem::WaitEventsTimeout (double timeout_secs) override virtual
Implements cloudViewer::visualization::gui::WindowSystem.
Definition at line 117 of file GLFWWindowSystem.cpp.
References QtCompat::endl().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/GLFWWindowSystem.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/GLFWWindowSystem.cpp