ACloudViewer: ProgramGPU Class Reference
ProgramGPU Class Reference abstract
#include <ProgramGPU.h>
Public Member Functions
virtual int UseProgram ()=0
virtual void * GetProgramID ()=0
virtual ~ProgramGPU ()
Detailed Description
Definition at line 33 of file ProgramGPU.h.
Constructor & Destructor Documentation
~ProgramGPU()
virtual ProgramGPU::~ProgramGPU () inline virtual
Definition at line 40 of file ProgramGPU.h.
Member Function Documentation
GetProgramID()
virtual void* ProgramGPU::GetProgramID () pure virtual
Implemented in ProgramGLSL.
UseProgram()
virtual int ProgramGPU::UseProgram () pure virtual
Implemented in ProgramGLSL.
Referenced by ShaderMan::FilterImage(), SiftMatchGL::GetGuidedSiftMatch(), SiftMatchGL::GetSiftMatch(), ShaderMan::TextureDownSample(), ShaderMan::TextureUpSample(), ShaderMan::UseShaderCopyKeypoint(), ShaderMan::UseShaderDebug(), ShaderMan::UseShaderDescriptor(), ShaderMan::UseShaderDisplayDOG(), ShaderMan::UseShaderDisplayGaussian(), ShaderMan::UseShaderDisplayGrad(), ShaderMan::UseShaderDisplayKeypoints(), ShaderMan::UseShaderGenListEnd(), ShaderMan::UseShaderGenListHisto(), ShaderMan::UseShaderGenListInit(), ShaderMan::UseShaderGenListStart(), ShaderMan::UseShaderGenListStep(), ShaderMan::UseShaderGenVBO(), ShaderMan::UseShaderGradientPass(), ShaderMan::UseShaderKeypoint(), ShaderMan::UseShaderMarginCopy(), ShaderMan::UseShaderOrientation(), ShaderMan::UseShaderRGB2Gray(), ShaderMan::UseShaderSimpleOrientation(), and ShaderMan::UseShaderZeroPass().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/ProgramGPU.h