ACloudViewer: PythonPluginManager Class Reference
PythonPluginManager Class Reference final
#include <PythonPluginManager.h>
Public Member Functions
PythonPluginManager ()=default
const std::vector< Runtime::RegisteredPlugin > & plugins () const
Returns the currently loaded plugins.
void loadPluginsFromEntryPoints ()
void loadPluginsFrom (const QStringList &paths)
void unloadPlugins ()
This MUST be called before finalizing the interpreter.
Detailed Description
The Manager class (#OOP) for the plugins, responsible for loading and storing them
Definition at line 16 of file PythonPluginManager.h.
Constructor & Destructor Documentation
PythonPluginManager()
PythonPluginManager::PythonPluginManager () default
Member Function Documentation
loadPluginsFrom()
void PythonPluginManager::loadPluginsFrom (const QStringList & paths)
Loads the plugins from the given path.
A plugin is either a .py file or a directory.
Parameters
paths where we will look for plugins to load
Definition at line 117 of file PythonPluginManager.cpp.
References Runtime::RegisteredPlugin::InstanciatePlugin().
Referenced by PythonPlugin::setMainAppInterface().
loadPluginsFromEntryPoints()
void PythonPluginManager::loadPluginsFromEntryPoints ()
Autodiscover plugins based on the package metadata. it uses the entry point mechanism described
In PyPa docs: https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/
In SetupTools docs: https://setuptools.pypa.io/en/latest/userguide/entry_point.html The entry point group "cloudviewer.plugins" is searched among all packages included in the current site-package, then we try to load the plugin from the "entry.value" that must be formed in this fashion: "package_and_module:SubClassOfPythonPluginInterface". The name of the plugin is infered from the entry.name
Definition at line 21 of file PythonPluginManager.cpp.
References Runtime::RegisteredPlugin::InstanciatePlugin().
Referenced by PythonPlugin::setMainAppInterface().
plugins()
const std::vector< Runtime::RegisteredPlugin > & PythonPluginManager::plugins () const
Returns the currently loaded plugins.
Definition at line 16 of file PythonPluginManager.cpp.
Referenced by PythonActionLauncher::populateToolBox().
unloadPlugins()
void PythonPluginManager::unloadPlugins ()
This MUST be called before finalizing the interpreter.
Definition at line 187 of file PythonPluginManager.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonPluginManager.h
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonPluginManager.cpp