ACloudViewer: ccGamepadManager Class Reference
ccGamepadManager Class Reference
Gamepad manager.
#include <ccGamepadManager.h>
Public Member Functions
ccGamepadManager (ecvMainAppInterface *appInterface, QObject *parent)
~ccGamepadManager ()
QMenu * menu ()
Returns the menu associated with gamepads.
Protected Member Functions
void enableDevice (bool state, bool silent, int deviceID=-1)
void releaseDevice ()
void showMessage (QString message, bool asWarning)
void setupMenu ()
void setupGamepadInput ()
void onGamepadInput ()
Detailed Description
Gamepad manager.
Definition at line 39 of file ccGamepadManager.h.
Constructor & Destructor Documentation
ccGamepadManager()
ccGamepadManager::ccGamepadManager (ecvMainAppInterface * appInterface, QObject * parent)
Definition at line 20 of file ccGamepadManager.cpp.
References enableDevice(), setupGamepadInput(), and setupMenu().
~ccGamepadManager()
ccGamepadManager::~ccGamepadManager ()
Definition at line 35 of file ccGamepadManager.cpp.
References releaseDevice().
Member Function Documentation
enableDevice()
void ccGamepadManager::enableDevice (bool state, bool silent, int deviceID = -1) protected
Definition at line 51 of file ccGamepadManager.cpp.
References ccPickOneElementDlg::addElement(), ecvMainAppInterface::getMainWindow(), ccPickOneElementDlg::getSelectedIndex(), name, CVLog::Print(), setupGamepadInput(), showMessage(), GamepadInput::start(), GamepadInput::stop(), and CVLog::Warning().
Referenced by ccGamepadManager(), setupGamepadInput(), and setupMenu().
menu()
QMenu* ccGamepadManager::menu () inline
Returns the menu associated with gamepads.
Definition at line 47 of file ccGamepadManager.h.
onGamepadInput()
void ccGamepadManager::onGamepadInput () protected
Definition at line 233 of file ccGamepadManager.cpp.
References ecvMainAppInterface::getMainWindow(), and GamepadInput::update().
Referenced by setupGamepadInput().
releaseDevice()
void ccGamepadManager::releaseDevice () protected
Definition at line 140 of file ccGamepadManager.cpp.
References GamepadInput::stop().
Referenced by ~ccGamepadManager().
setupGamepadInput()
void ccGamepadManager::setupGamepadInput () protected
Definition at line 150 of file ccGamepadManager.cpp.
References ecvMainAppInterface::decreasePointSize(), enableDevice(), ecvMainAppInterface::increasePointSize(), onGamepadInput(), CVLog::Print(), ecvMainAppInterface::setGlobalZoom(), showMessage(), ecvMainAppInterface::toggleActiveWindowCenteredPerspective(), ecvMainAppInterface::toggleActiveWindowViewerBasedPerspective(), and GamepadInput::updated().
Referenced by ccGamepadManager(), and enableDevice().
setupMenu()
void ccGamepadManager::setupMenu () protected
Definition at line 216 of file ccGamepadManager.cpp.
References enableDevice().
Referenced by ccGamepadManager().
showMessage()
void ccGamepadManager::showMessage (QString message, bool asWarning) protected
Definition at line 43 of file ccGamepadManager.cpp.
References CVLog::Error(), and CVLog::Warning().
Referenced by enableDevice(), and setupGamepadInput().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVAppCommon/devices/gamepad/ccGamepadManager.h
/root/ACloudViewer/libs/CVAppCommon/devices/gamepad/ccGamepadManager.cpp