ACloudViewer: Widgets::GradientComboBox Class Reference
Widgets::GradientComboBox Class Reference
#include <gradientcombobox.h>
Signals
void colorsChanged (const QString &name, const QColor &clr1, const QColor &clr2)
Public Member Functions
GradientComboBox (QWidget *parent=nullptr)
~GradientComboBox ()
void setCurrentIndex (int index)
int currentIndex () const
QString currentName () const
QColor currentColor1 () const
QColor currentColor2 () const
void showPopup ()
void hidePopup ()
Static Public Member Functions
static QPair< QColor, QColor > colorPair (int index)
Protected Member Functions
void paintEvent (QPaintEvent *e)
void resizeEvent (QResizeEvent *e)
QSize minimumSizeHint () const
Detailed Description
Definition at line 18 of file gradientcombobox.h.
Constructor & Destructor Documentation
GradientComboBox()
Widgets::GradientComboBox::GradientComboBox (QWidget * parent = nullptr) explicit
Definition at line 424 of file gradientcombobox.cpp.
~GradientComboBox()
Widgets::GradientComboBox::~GradientComboBox ()
Definition at line 428 of file gradientcombobox.cpp.
Member Function Documentation
colorPair()
QPair< QColor, QColor > Widgets::GradientComboBox::colorPair (int index) static
Definition at line 463 of file gradientcombobox.cpp.
References ecvColor::LookUpTable::at(), and size.
colorsChanged
void Widgets::GradientComboBox::colorsChanged (const QString & name, const QColor & clr1, const QColor & clr2) signal
currentColor1()
QColor Widgets::GradientComboBox::currentColor1 () const
Definition at line 449 of file gradientcombobox.cpp.
Referenced by cvIsoSurfaceFilter::on_gradientCombo_activated().
currentColor2()
QColor Widgets::GradientComboBox::currentColor2 () const
Definition at line 456 of file gradientcombobox.cpp.
Referenced by cvIsoSurfaceFilter::on_gradientCombo_activated().
currentIndex()
int Widgets::GradientComboBox::currentIndex () const
Definition at line 438 of file gradientcombobox.cpp.
currentName()
QString Widgets::GradientComboBox::currentName () const
Definition at line 442 of file gradientcombobox.cpp.
hidePopup()
void Widgets::GradientComboBox::hidePopup ()
Definition at line 482 of file gradientcombobox.cpp.
minimumSizeHint()
QSize Widgets::GradientComboBox::minimumSizeHint () const protected
Definition at line 526 of file gradientcombobox.cpp.
paintEvent()
void Widgets::GradientComboBox::paintEvent (QPaintEvent * e) protected
Definition at line 489 of file gradientcombobox.cpp.
References color, Widgets::GradientWidgetItem::color1(), Widgets::GradientWidgetItem::color2(), e, height, and width.
resizeEvent()
void Widgets::GradientComboBox::resizeEvent (QResizeEvent * e) protected
Definition at line 517 of file gradientcombobox.cpp.
References e.
setCurrentIndex()
void Widgets::GradientComboBox::setCurrentIndex (int index)
Definition at line 430 of file gradientcombobox.cpp.
References Widgets::GradientWidgetItem::name().
showPopup()
void Widgets::GradientComboBox::showPopup ()
Definition at line 472 of file gradientcombobox.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/gradientcombobox.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/gradientcombobox.cpp