ACloudViewer: colmap::HomographyMatrixEstimator Class Reference
colmap::HomographyMatrixEstimator Class Reference
#include <homography_matrix.h>
Public Types
typedef Eigen::Vector2d X_t
typedef Eigen::Vector2d Y_t
typedef Eigen::Matrix3d M_t
Static Public Member Functions
static std::vector< M_t > Estimate (const std::vector< X_t > &points1, const std::vector< Y_t > &points2)
static void Residuals (const std::vector< X_t > &points1, const std::vector< Y_t > &points2, const M_t &H, std::vector< double > *residuals)
Static Public Attributes
static const int kMinNumSamples = 4
Detailed Description
Definition at line 21 of file homography_matrix.h.
Member Typedef Documentation
M_t
typedef Eigen::Matrix3d colmap::HomographyMatrixEstimator::M_t
Definition at line 25 of file homography_matrix.h.
X_t
typedef Eigen::Vector2d colmap::HomographyMatrixEstimator::X_t
Definition at line 23 of file homography_matrix.h.
Y_t
typedef Eigen::Vector2d colmap::HomographyMatrixEstimator::Y_t
Definition at line 24 of file homography_matrix.h.
Member Function Documentation
Estimate()
std::vector< HomographyMatrixEstimator::M_t > colmap::HomographyMatrixEstimator::Estimate (const std::vector< X_t > & points1, const std::vector< Y_t > & points2) static
Definition at line 44 of file homography_matrix.cc.
References colmap::CenterAndNormalizeImagePoints().
Referenced by BOOST_AUTO_TEST_CASE().
Residuals()
void colmap::HomographyMatrixEstimator::Residuals (const std::vector< X_t > & points1, const std::vector< Y_t > & points2, const M_t & H, std::vector< double > * residuals) static
Definition at line 94 of file homography_matrix.cc.
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
kMinNumSamples
const int colmap::HomographyMatrixEstimator::kMinNumSamples = 4 static
Definition at line 28 of file homography_matrix.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/estimators/homography_matrix.h
/root/ACloudViewer/libs/Reconstruction/src/estimators/homography_matrix.cc