ACloudViewer: ccFitPlaneTool Class Reference
ccFitPlaneTool Class Reference
#include <ccFitPlaneTool.h>
Public Member Functions
ccFitPlaneTool ()
virtual ~ccFitPlaneTool ()
void toolActivated () override
void toolDisactivated () override
void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccPointCloud *cloud, const CCVector3 &P) override
Public Member Functions inherited from ccTool
virtual ~ccTool ()
void initializeTool (ecvMainAppInterface *app)
virtual void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccHObject *pickedObject, const CCVector3 &P)
virtual void onNewSelection (const ccHObject::Container &selectedEntities)
virtual void accept ()
virtual void cancel ()
virtual bool canUndo ()
virtual void undo ()
Public Attributes
ccMouseCircle * m_mouseCircle = nullptr
Additional Inherited Members
Protected Member Functions inherited from ccTool
ccTool ()
Protected Attributes inherited from ccTool
ecvMainAppInterface * m_app
QWidget * m_window
Detailed Description
Definition at line 20 of file ccFitPlaneTool.h.
Constructor & Destructor Documentation
ccFitPlaneTool()
ccFitPlaneTool::ccFitPlaneTool ()
Definition at line 13 of file ccFitPlaneTool.cpp.
~ccFitPlaneTool()
ccFitPlaneTool::~ccFitPlaneTool () virtual
Definition at line 15 of file ccFitPlaneTool.cpp.
References m_mouseCircle, and ccMouseCircle::ownerIsDead().
Member Function Documentation
pointPicked()
void ccFitPlaneTool::pointPicked (ccHObject * insertPoint, unsigned itemIdx, ccPointCloud * cloud, const CCVector3 & P) override virtual
Reimplemented from ccTool.
Definition at line 43 of file ccFitPlaneTool.cpp.
References ccHObject::addChild(), ccGenericPointCloud::computeOctree(), ccFitPlane::Fit(), ccObject::getName(), ccGenericPointCloud::getOctree(), ccMouseCircle::getRadiusWorld(), ccTool::m_app, m_mouseCircle, ccHObject::SELECTION_IGNORED, ccHObject::setSelectionBehavior(), ccDrawableObject::setVisible(), and ccFitPlane::updateAttributes().
toolActivated()
void ccFitPlaneTool::toolActivated () override virtual
Reimplemented from ccTool.
Definition at line 25 of file ccFitPlaneTool.cpp.
References ecvDisplayTools::GetCurrentScreen(), m_mouseCircle, ecvDisplayTools::SetPerspectiveState(), and ccDrawableObject::setVisible().
toolDisactivated()
void ccFitPlaneTool::toolDisactivated () override virtual
Reimplemented from ccTool.
Definition at line 34 of file ccFitPlaneTool.cpp.
References m_mouseCircle, and ccDrawableObject::setVisible().
Member Data Documentation
m_mouseCircle
ccMouseCircle* ccFitPlaneTool::m_mouseCircle = nullptr
Definition at line 39 of file ccFitPlaneTool.h.
Referenced by pointPicked(), toolActivated(), toolDisactivated(), and ~ccFitPlaneTool().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCompass/include/ccFitPlaneTool.h
/root/ACloudViewer/plugins/core/Standard/qCompass/src/ccFitPlaneTool.cpp