ACloudViewer: cloudViewer::io::MKVReader Class Reference
cloudViewer::io::MKVReader Class Reference
#include <MKVReader.h>
Public Member Functions
MKVReader ()
Default Constructor.
virtual ~MKVReader ()
bool IsOpened ()
Check If the mkv file is opened.
bool IsEOF ()
Check if the mkv file is all read.
bool Open (const std::string &filename)
void Close ()
Close the opened mkv playback.
MKVMetadata & GetMetadata ()
Get metadata of the mkv playback.
bool SeekTimestamp (size_t timestamp)
Seek to the timestamp (in us).
std::shared_ptr< geometry::RGBDImage > NextFrame ()
Get next frame from the mkv playback and returns the RGBD object.
Detailed Description
AzureKinect mkv file reader.
Definition at line 26 of file MKVReader.h.
Constructor & Destructor Documentation
MKVReader()
cloudViewer::io::MKVReader::MKVReader ()
Default Constructor.
Definition at line 26 of file MKVReader.cpp.
~MKVReader()
virtual cloudViewer::io::MKVReader::~MKVReader () inline virtual
Definition at line 30 of file MKVReader.h.
Member Function Documentation
Close()
void cloudViewer::io::MKVReader::Close ()
Close the opened mkv playback.
Definition at line 62 of file MKVReader.cpp.
References cloudViewer::io::k4a_plugin::k4a_playback_close().
Referenced by Open().
GetMetadata()
MKVMetadata& cloudViewer::io::MKVReader::GetMetadata () inline
Get metadata of the mkv playback.
Definition at line 45 of file MKVReader.h.
IsEOF()
bool cloudViewer::io::MKVReader::IsEOF () inline
Check if the mkv file is all read.
Definition at line 35 of file MKVReader.h.
IsOpened()
bool cloudViewer::io::MKVReader::IsOpened ()
Check If the mkv file is opened.
Definition at line 28 of file MKVReader.cpp.
Referenced by NextFrame(), Open(), and SeekTimestamp().
NextFrame()
std::shared_ptr< geometry::RGBDImage > cloudViewer::io::MKVReader::NextFrame ()
Get next frame from the mkv playback and returns the RGBD object.
Definition at line 141 of file MKVReader.cpp.
References cloudViewer::io::AzureKinectSensor::DecompressCapture(), IsOpened(), cloudViewer::io::k4a_plugin::k4a_capture_release(), cloudViewer::io::k4a_plugin::k4a_playback_get_next_capture(), LogError, and LogInfo.
Open()
bool cloudViewer::io::MKVReader::Open (const std::string & filename)
Open an mkv playback.
Parameters
filename Path to the mkv file.
Definition at line 45 of file MKVReader.cpp.
References Close(), cloudViewer::io::MKVMetadata::ConvertFromJsonValue(), IsOpened(), cloudViewer::io::k4a_plugin::k4a_playback_open(), and LogWarning.
SeekTimestamp()
bool cloudViewer::io::MKVReader::SeekTimestamp (size_t timestamp)
Seek to the timestamp (in us).
Definition at line 120 of file MKVReader.cpp.
References IsOpened(), cloudViewer::io::k4a_plugin::k4a_playback_seek_timestamp(), LogWarning, and cloudViewer::io::MKVMetadata::stream_length_usec_.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/io/sensor/azure_kinect/MKVReader.h
/root/ACloudViewer/libs/cloudViewer/io/sensor/azure_kinect/MKVReader.cpp