ACloudViewer: ccTrace Class Reference
ccTrace Class Reference
#include <ccTrace.h>
Public Types
enum MODE {
RGB = 1 , LIGHT = 2 , DARK = 4 , CURVE = 8 ,
GRADIENT = 16 , DISTANCE = 32 , SCALAR = 64 , INV_SCALAR = 128
}
Public Types inherited from cloudViewer::GenericCloud
using genericPointAction = std::function< void(const CCVector3 &, ScalarType &)>
Generic function applied to a point (used by foreach)
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Public Member Functions
ccTrace (ccPointCloud *associatedCloud)
ccTrace (ccPolyline *obj)
virtual ~ccTrace ()
virtual CV_CLASS_ENUM getClassID () const override
Returns class ID.
void pushWaypoint (int pointId)
void deleteWaypoint (int pointId)
int getWaypoint (int n)
int insertWaypoint (int pointId)
CCVector3f getPointNormal (int pointIdx)
void undoLast ()
size_t waypoint_count () const
bool optimizePath (int maxIterations=1000000)
void finalizePath ()
void recalculatePath ()
ccFitPlane * fitPlane (int surface_effect_tolerance=10, float min_planarity=0.75f)
void bakePathToScalarField ()
int getSegmentCost (int p1, int p2)
void buildGradientCost (QWidget *parent)
void buildCurvatureCost (QWidget *parent)
bool isGradientPrecomputed ()
bool isCurvaturePrecomputed ()
Public Member Functions inherited from ccPolyline
ccPolyline (GenericIndexedCloudPersist *associatedCloud)
Default constructor.
ccPolyline (ccPointCloud &associatedCloud)
ccPolyline (const ccPolyline &poly)
Copy constructor.
virtual ~ccPolyline () override=default
Destructor.
virtual bool isSerializable () const override
Returns whether object is serializable of not.
virtual void applyGLTransformation (const ccGLMatrix &trans) override
Applies a GL transformation to the entity.
virtual unsigned getUniqueIDForDisplay () const override
Returns object unqiue ID used for display.
virtual bool hasColors () const override
Returns whether colors are enabled or not.
virtual void setGlobalShift (const CCVector3d &shift) override
Sets shift applied to original coordinates (information storage only)
virtual void setGlobalScale (double scale) override
void set2DMode (bool state)
Defines if the polyline is considered as 2D or 3D.
bool is2DMode () const
Returns whether the polyline is considered as 2D or 3D.
void setTransformFlag (bool state)
Defines if the polyline is considered as processed polyline.
bool needTransform () const
Returns whether the polyline is considered as 2D or 3D.
void setForeground (bool state)
Defines if the polyline is drawn in background or foreground.
void setColor (const ecvColor::Rgb &col)
Sets the polyline color.
void setWidth (PointCoordinateType width)
Sets the width of the line.
PointCoordinateType getWidth () const
Returns the width of the line.
const ecvColor::Rgb & getColor () const
Returns the polyline color.
virtual ccBBox getOwnBB (bool withGLFeatures=false) override
Returns the entity's own bounding-box.
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col) override
Draws the entity (and its children) bounding-box.
bool split (PointCoordinateType maxEdgeLength, std::vector< ccPolyline * > &parts)
Splits the polyline into several parts based on a maximum edge length.
bool add (const ccPointCloud &cloud)
Add another reference cloud.
PointCoordinateType computeLength () const
Computes the polyline length.
void showVertices (bool state)
Sets whether to display or hide the polyline vertices.
bool verticesShown () const
Whether the polyline vertices should be displayed or not.
bool arrowShown () const
unsigned getArrowIndex () const
PointCoordinateType getArrowLength () const
void setVertexMarkerWidth (int width)
Sets the width of vertex markers.
int getVertexMarkerWidth () const
Returns the width of vertex markers.
bool initWith (ccPointCloud *vertices, const ccPolyline &poly)
void importParametersFrom (const ccPolyline &poly)
Copy the parameters from another polyline.
void showArrow (bool state, unsigned vertIndex, PointCoordinateType length)
Shows an arrow in place of a given vertex.
unsigned segmentCount () const
Returns the number of segments.
ccPointCloud * samplePoints (bool densityBased, double samplingParameter, bool withRGB)
Samples points on the polyline.
ccPolyline * smoothChaikin (PointCoordinateType ratio, unsigned iterationCount) const
Smoothes the polyline (Chaikin algorithm)
bool createNewPolylinesFromSelection (std::vector< ccPolyline * > &output)
Creates a polyline mesh with the selected vertices only.
virtual bool IsEmpty () const override
virtual Eigen::Vector3d GetMinBound () const override
Returns min bounds for geometry coordinates.
virtual Eigen::Vector3d GetMaxBound () const override
Returns max bounds for geometry coordinates.
virtual Eigen::Vector3d GetCenter () const override
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const override
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const override
virtual ccPolyline & Transform (const Eigen::Matrix4d &transformation) override
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual ccPolyline & Translate (const Eigen::Vector3d &translation, bool relative=true) override
Apply translation to the geometry coordinates.
virtual ccPolyline & Scale (const double s, const Eigen::Vector3d &center) override
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual ccPolyline & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center) override
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
ccPolyline & operator+= (const ccPolyline &polyline)
ccPolyline & operator= (const ccPolyline &polyline)
ccPolyline operator+ (const ccPolyline &polyline) const
ccPolyline & PaintUniformColor (const Eigen::Vector3d &color)
Assigns each line in the LineSet the same color.
Public Member Functions inherited from cloudViewer::Polyline
Polyline (GenericIndexedCloudPersist *associatedCloud)
Polyline constructor.
bool isClosed () const
Returns whether the polyline is closed or not.
void setClosed (bool state)
Sets whether the polyline is closed or not.
void clear (bool unusedParam=true) override
Clears the cloud.
Public Member Functions inherited from cloudViewer::ReferenceCloud
ReferenceCloud (GenericIndexedCloudPersist *associatedCloud)
Default constructor.
ReferenceCloud (const ReferenceCloud &refCloud)
Copy constructor.
~ReferenceCloud () override=default
Destructor.
unsigned size () const override
Returns the number of points.
void forEach (genericPointAction action) override
Fast iteration mechanism.
void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax) override
Returns the cloud bounding box.
unsigned char testVisibility (const CCVector3 &P) const override
void placeIteratorAtBeginning () override
Sets the cloud iterator at the beginning.
const CCVector3 * getNextPoint () override
Returns the next point (relatively to the global iterator position)
bool enableScalarField () override
Enables the scalar field associated to the cloud.
bool isScalarFieldEnabled () const override
Returns true if the scalar field is enabled, false otherwise.
void setPointScalarValue (unsigned pointIndex, ScalarType value) override
Sets the ith point associated scalar value.
ScalarType getPointScalarValue (unsigned pointIndex) const override
Returns the ith point associated scalar value.
const CCVector3 * getPoint (unsigned index) const override
Returns the ith point.
void getPoint (unsigned index, CCVector3 &P) const override
Returns the ith point.
void getPoint (unsigned index, double P[3]) const override
const CCVector3 * getPointPersistentPtr (unsigned index) override
Returns the ith point as a persistent pointer.
virtual unsigned getPointGlobalIndex (unsigned localIndex) const
virtual const CCVector3 * getCurrentPointCoordinates () const
Returns the coordinates of the point pointed by the current element.
virtual unsigned getCurrentPointGlobalIndex () const
Returns the global index of the point pointed by the current element.
virtual ScalarType getCurrentPointScalarValue () const
Returns the current point associated scalar value.
virtual void setCurrentPointScalarValue (ScalarType value)
Sets the current point associated scalar value.
virtual void forwardIterator ()
Forwards the local element iterator.
virtual bool addPointIndex (unsigned globalIndex)
Point global index insertion mechanism.
virtual bool addPointIndex (unsigned firstIndex, unsigned lastIndex)
Point global index insertion mechanism (range)
virtual void setPointIndex (unsigned localIndex, unsigned globalIndex)
Sets global index for a given element.
virtual bool reserve (unsigned n)
Reserves some memory for hosting the point references.
virtual bool resize (unsigned n)
Presets the size of the vector used to store point references.
virtual unsigned capacity () const
Returns max capacity.
virtual void swap (unsigned i, unsigned j)
Swaps two point references.
virtual void removeCurrentPointGlobalIndex ()
Removes current element.
virtual void removePointGlobalIndex (unsigned localIndex)
Removes a given element.
virtual GenericIndexedCloudPersist * getAssociatedCloud ()
Returns the associated (source) cloud.
virtual const GenericIndexedCloudPersist * getAssociatedCloud () const
Returns the associated (source) cloud (const version)
virtual void setAssociatedCloud (GenericIndexedCloudPersist *cloud)
Sets the associated (source) cloud.
bool add (const ReferenceCloud &cloud)
Add another reference cloud.
void invalidateBoundingBox ()
Invalidates the bounding-box.
Public Member Functions inherited from cloudViewer::GenericIndexedCloudPersist
~GenericIndexedCloudPersist () override=default
Default destructor.
Public Member Functions inherited from cloudViewer::GenericIndexedCloud
~GenericIndexedCloud () override=default
Default destructor.
virtual bool normalsAvailable () const
Returns whether normals are available.
virtual const CCVector3 * getNormal (unsigned index) const
If per-point normals are available, returns the one at a specific index.
Public Member Functions inherited from cloudViewer::GenericCloud
GenericCloud ()=default
Default constructor.
virtual ~GenericCloud ()=default
Default destructor.
virtual bool hasPoints () const
Public Member Functions inherited from ccShiftedObject
ccShiftedObject (QString name=QString())
Default constructor.
ccShiftedObject (const ccShiftedObject &s)
Copy constructor.
void copyGlobalShiftAndScale (const ccShiftedObject &s)
Copies the Global Shift and Scale from another entity.
virtual void setGlobalShift (double x, double y, double z)
Sets shift applied to original coordinates (information storage only)
virtual const CCVector3d & getGlobalShift () const
Returns the shift applied to original coordinates.
virtual double getGlobalScale () const
Returns the scale applied to original coordinates.
bool isShifted () const
Returns whether the cloud is shifted or not.
template<typename T >
CCVector3d toGlobal3d (const Vector3Tpl< T > &Plocal) const
Returns the point back-projected into the original coordinates system.
template<typename T >
CCVector3d toLocal3d (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
template<typename T >
CCVector3 toLocal3pc (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner) override
GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false) override
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual Eigen::Vector2d GetMin2DBound () const
virtual Eigen::Vector2d GetMax2DBound () const
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual ccBBox getOwnFitBB (ccGLMatrix &trans)
Returns best-fit bounding-box (if available)
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
virtual void notifyGeometryUpdate ()
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual const ccGLMatrix & getGLTransformationHistory () const
Returns the transformation 'history' matrix.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual void getDrawingParameters (glDrawParams &params) const
Returns main OpenGL parameters for this entity.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual bool hasNormals () const
Returns whether normals are enabled or not.
virtual bool normalsShown () const
Returns whether normals are shown or not.
virtual void showNormals (bool state)
Sets normals visibility.
virtual void toggleNormals ()
Toggles normals display state.
virtual bool hasDisplayedScalarField () const
Returns whether an active scalar field is available or not.
virtual bool hasScalarFields () const
Returns whether one or more scalar fields are instantiated.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void toggleMaterials ()
Toggles material display state.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Public Member Functions inherited from ccMeasurement
ccMeasurement ()
virtual ~ccMeasurement ()
void setDefaultColor (const ecvColor::Rgb &col)
void setHighlightColor (const ecvColor::Rgb &col)
void setActiveColor (const ecvColor::Rgb &col)
void setAlternateColor (const ecvColor::Rgb &col)
ecvColor::Rgb getMeasurementColour () const
void setActive (bool isActive)
void setHighlight (bool isActive)
void setAlternate (bool isActive)
void setNormal ()
Static Public Member Functions
static bool isTrace (ccHObject *object)
Static Public Member Functions inherited from ccPolyline
static bool IsCloudVerticesOfPolyline (ccGenericPointCloud *cloud, ccPolyline **polyline=nullptr)
Helper to determine if the input cloud acts as vertices of a polyline.
static ccPolyline * Circle (const CCVector3 &center, PointCoordinateType radius, unsigned resolution=48)
Creates a circle as a polyline.
static QString MetaKeyUpDir ()
static QString MetaKeyConstAltitude ()
Meta data key: contour plot constant altitude (for contour plots, etc.)
static QString MetaKeyAbscissa ()
Meta data key: profile abscissa along generatrix.
static QString MetaKeyPrefixCenter ()
static QString MetaKeyPrefixDirection ()
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Static Public Attributes
static int COST_MODE = ccTrace::MODE::DARK
Protected Member Functions
virtual void drawMeOnly (CC_DRAW_CONTEXT &context) override
Draws the entity only (not its children)
int getClosestWaypoint (int pointID)
std::deque< int > optimizeSegment (int start, int end, int offset=0)
int getSegmentCostRGB (int p1, int p2)
int getSegmentCostDark (int p1, int p2)
int getSegmentCostLight (int p1, int p2)
int getSegmentCostCurve (int p1, int p2)
int getSegmentCostGrad (int p1, int p2, float search_r)
int getSegmentCostDist (int p1, int p2)
int getSegmentCostScalar (int p1, int p2)
int getSegmentCostScalarInv (int p1, int p2)
float calculateOptimumSearchRadius ()
Protected Member Functions inherited from ccPolyline
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
Protected Member Functions inherited from ccShiftedObject
bool saveShiftInfoToFile (QFile &out) const
Serialization helper (output)
bool loadShiftInfoFromFile (QFile &in)
Serialization helper (input)
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void drawNameIn3D ()
Draws the entity name in 3D.
virtual void onDeletionOf (const ccHObject *obj)
This method is called when another object is deleted.
virtual void onUpdateOf (ccHObject *obj)
This method is called when another object (geometry) is updated.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Protected Attributes
float m_relMarkerScale = 1.0f
ccPointCloud * m_cloud = 0
std::vector< std::deque< int > > m_trace
std::vector< int > m_waypoints
std::vector< int > m_previous
Protected Attributes inherited from ccPolyline
ecvColor::Rgb m_rgbColor
Unique RGB color.
PointCoordinateType m_width
Width of the line.
bool m_mode2D
Whether polyline should be considered as 2D (true) or 3D (false)
bool m_needTransform
Whether polyline should be considered as processed polyline.
bool m_foreground
bool m_showVertices
Whether vertices should be displayed or not.
int m_vertMarkWidth
Vertex marker width.
bool m_showArrow
Whether to show an arrow or not.
PointCoordinateType m_arrowLength
Arrow length.
unsigned m_arrowIndex
Arrow index.
Protected Attributes inherited from cloudViewer::Polyline
bool m_isClosed
Closing state.
Protected Attributes inherited from cloudViewer::ReferenceCloud
ReferencesContainer m_theIndexes
Indexes of (some of) the associated cloud points.
std::atomic< unsigned > m_globalIterator
Iterator on the point references container.
BoundingBox m_bbox
Bounding-box.
GenericIndexedCloudPersist * m_theAssociatedCloud
Associated cloud.
std::mutex m_mutex
For concurrent access.
Protected Attributes inherited from ccShiftedObject
CCVector3d m_globalShift
Global shift (typically applied at loading time)
double m_globalScale
Global scale (typically applied at loading time)
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Protected Attributes inherited from ccMeasurement
bool m_isActive = false
bool m_isHighlighted = false
bool m_isAlternate = false
ecvColor::Rgb m_active_colour = ecvColor::yellow
ecvColor::Rgb m_highlight_colour = ecvColor::green
ecvColor::Rgb m_alternate_colour = ecvColor::cyan
ecvColor::Rgb m_normal_colour = ecvColor::blue
Additional Inherited Members
Protected Types inherited from cloudViewer::ReferenceCloud
using ReferencesContainer = std::vector< unsigned int >
Container of 3D point indexes.
Detailed Description
Definition at line 57 of file ccTrace.h.
Member Enumeration Documentation
MODE
enum ccTrace::MODE
Enumerator
RGB
LIGHT
DARK
CURVE
GRADIENT
DISTANCE
SCALAR
INV_SCALAR
Definition at line 191 of file ccTrace.h.
Constructor & Destructor Documentation
ccTrace() [1/2]
ccTrace::ccTrace (ccPointCloud * associatedCloud)
Definition at line 15 of file ccTrace.cpp.
ccTrace() [2/2]
ccTrace::ccTrace (ccPolyline * obj)
Definition at line 19 of file ccTrace.cpp.
References cloudViewer::ReferenceCloud::addPointIndex(), COST_MODE, cloudViewer::ReferenceCloud::getAssociatedCloud(), ccObject::getMetaData(), ccObject::getName(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), ccObject::hasMetaData(), cloudViewer::ReferenceCloud::invalidateBoundingBox(), m_trace, m_waypoints, optimizePath(), ccObject::setMetaData(), ccObject::setName(), and cloudViewer::ReferenceCloud::size().
~ccTrace()
virtual ccTrace::~ccTrace () inline virtual
Definition at line 62 of file ccTrace.h.
Member Function Documentation
bakePathToScalarField()
void ccTrace::bakePathToScalarField ()
Definition at line 883 of file ccTrace.cpp.
References ccObject::getUniqueID(), m_cloud, m_trace, cloudViewer::PointCloudTpl< T >::setPointScalarValue(), and cloudViewer::PointCloudTpl< T >::size().
buildCurvatureCost()
void ccTrace::buildCurvatureCost (QWidget * parent)
Definition at line 754 of file ccTrace.cpp.
References ccPointCloud::addScalarField(), cloudViewer::GeometricalAnalysisTools::ComputeCharactersitic(), cloudViewer::ScalarField::computeMinAndMax(), ccGenericPointCloud::computeOctree(), cloudViewer::GeometricalAnalysisTools::Curvature, ccPointCloud::deleteScalarField(), cloudViewer::ScalarField::getMax(), ccGenericPointCloud::getOctree(), cloudViewer::PointCloudTpl< T >::getPointScalarValue(), cloudViewer::PointCloudTpl< T >::getScalarField(), isCurvaturePrecomputed(), m_cloud, cloudViewer::GeometricalAnalysisTools::NoError, octree, result, cloudViewer::PointCloudTpl< T >::setCurrentInScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentScalarField(), cloudViewer::PointCloudTpl< T >::setPointScalarValue(), cloudViewer::PointCloudTpl< T >::size(), and CVLog::Warning().
Referenced by ccTraceTool::pointPicked().
buildGradientCost()
void ccTrace::buildGradientCost (QWidget * parent)
Definition at line 680 of file ccTrace.cpp.
References ccPointCloud::addScalarField(), ecvColor::RgbTpl< Type >::b, cloudViewer::ScalarField::computeMinAndMax(), ccGenericPointCloud::computeOctree(), cloudViewer::ScalarFieldTools::computeScalarFieldGradient(), ccPointCloud::deleteScalarField(), CVLog::Error(), ecvColor::RgbTpl< Type >::g, cloudViewer::ScalarField::getMax(), ccGenericPointCloud::getOctree(), ccPointCloud::getPointColor(), cloudViewer::PointCloudTpl< T >::getPointScalarValue(), cloudViewer::PointCloudTpl< T >::getScalarField(), isGradientPrecomputed(), m_cloud, octree, ecvColor::RgbTpl< Type >::r, result, cloudViewer::PointCloudTpl< T >::setCurrentInScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentOutScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentScalarField(), cloudViewer::PointCloudTpl< T >::setPointScalarValue(), cloudViewer::PointCloudTpl< T >::size(), and CVLog::Warning().
Referenced by ccTraceTool::pointPicked().
calculateOptimumSearchRadius()
float ccTrace::calculateOptimumSearchRadius () protected
Definition at line 896 of file ccTrace.cpp.
References cloudViewer::ReferenceCloud::clear(), ccGenericPointCloud::computeOctree(), ccGenericPointCloud::getOctree(), cloudViewer::PointCloudTpl< T >::getPoint(), m_cloud, and cloudViewer::PointCloudTpl< T >::size().
deleteWaypoint()
void ccTrace::deleteWaypoint (int pointId) inline
Definition at line 84 of file ccTrace.h.
References m_waypoints.
drawMeOnly()
void ccTrace::drawMeOnly (CC_DRAW_CONTEXT & context) override protected virtual
Draws the entity only (not its children)
Reimplemented from ccPolyline.
Definition at line 939 of file ccTrace.cpp.
References c_unitPointMarker(), CC_ENTITY_PICKING, color, context, ccGLMatrixTpl< T >::data(), ccGLDrawContext::defaultLineWidth, ccGLDrawContext::defaultPointSize, ccGLDrawContext::drawingFlags, Vector3Tpl< double >::fromArray(), ecvDisplayTools::GetCurrentScreen(), ccDrawableObject::getDrawingParameters(), ecvDisplayTools::GetGLCameraParameters(), ccMeasurement::getMeasurementColour(), cloudViewer::PointCloudTpl< T >::getPoint(), ecvDisplayTools::GetViewportParameters(), m_cloud, ccMeasurement::m_isActive, m_relMarkerScale, m_trace, m_waypoints, ccPolyline::m_width, MACRO_Draw3D, MACRO_EntityPicking, MACRO_Foreground, ccGLCameraParameters::modelViewMat, ecvViewportParameters::perspectiveView, TransformInfo::setScale(), TransformInfo::setTranslationStart(), glDrawParams::showColors, glDrawParams::showNorms, ccGLDrawContext::transformInfo, Tuple3Tpl< Type >::u, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, Tuple3Tpl< Type >::z, and ecvViewportParameters::zFar.
finalizePath()
void ccTrace::finalizePath ()
Definition at line 237 of file ccTrace.cpp.
References cloudViewer::ReferenceCloud::addPointIndex(), cloudViewer::Polyline::clear(), cloudViewer::ReferenceCloud::invalidateBoundingBox(), and m_trace.
Referenced by ccTraceTool::finishCurrentTrace(), fitPlane(), and optimizePath().
fitPlane()
ccFitPlane * ccTrace::fitPlane (int surface_effect_tolerance = 10, float min_planarity = 0.75f)
Definition at line 817 of file ccTrace.cpp.
References cloudViewer::Neighbourhood::computeCovarianceMatrix(), Vector3Tpl< Type >::dot(), finalizePath(), ccFitPlane::Fit(), ccPlane::getNormal(), ccNormalVectors::GetNormal(), ccPointCloud::getPointNormalIndex(), ccPointCloud::hasNormals(), m_cloud, PC_ONE, cloudViewer::ReferenceCloud::size(), and ccFitPlane::updateAttributes().
Referenced by ccTraceTool::finishCurrentTrace(), and ccCompass::recalculateFitPlanes().
getClassID()
virtual CV_CLASS_ENUM ccTrace::getClassID () const inline override virtual
Returns class ID.
Reimplemented from ccPolyline.
Definition at line 65 of file ccTrace.h.
References CV_TYPES::POLY_LINE.
getClosestWaypoint()
int ccTrace::getClosestWaypoint (int pointID) protected
getPointNormal()
CCVector3f ccTrace::getPointNormal (int pointIdx) inline
Definition at line 110 of file ccTrace.h.
References cloudViewer::ReferenceCloud::getPointGlobalIndex(), ccPointCloud::getPointNormal(), ccPointCloud::hasNormals(), and m_cloud.
Referenced by ccCompass::estimateStructureNormals().
getSegmentCost()
int ccTrace::getSegmentCost (int p1, int p2)
Definition at line 450 of file ccTrace.cpp.
References COST_MODE, getSegmentCostCurve(), getSegmentCostDark(), getSegmentCostDist(), getSegmentCostGrad(), getSegmentCostLight(), getSegmentCostRGB(), getSegmentCostScalar(), getSegmentCostScalarInv(), ccPointCloud::hasColors(), ccPointCloud::hasDisplayedScalarField(), and m_cloud.
Referenced by optimizeSegment().
getSegmentCostCurve()
int ccTrace::getSegmentCostCurve (int p1, int p2) protected
Definition at line 540 of file ccTrace.cpp.
References cloudViewer::Neighbourhood::computeCurvature(), cloudViewer::ScalarField::getMax(), cloudViewer::DgmOctreeReferenceCloud::getPoint(), cloudViewer::PointCloudTpl< T >::getPointScalarValue(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), isCurvaturePrecomputed(), m_cloud, and cloudViewer::PointCloudTpl< T >::setCurrentScalarField().
Referenced by getSegmentCost().
getSegmentCostDark()
int ccTrace::getSegmentCostDark (int p1, int p2) protected
Definition at line 524 of file ccTrace.cpp.
References ecvColor::RgbTpl< Type >::b, ecvColor::RgbTpl< Type >::g, ccPointCloud::getPointColor(), m_cloud, and ecvColor::RgbTpl< Type >::r.
Referenced by getSegmentCost(), and getSegmentCostLight().
getSegmentCostDist()
int ccTrace::getSegmentCostDist (int p1, int p2) protected
Definition at line 659 of file ccTrace.cpp.
Referenced by getSegmentCost().
getSegmentCostGrad()
int ccTrace::getSegmentCostGrad (int p1, int p2, float search_r) protected
Definition at line 590 of file ccTrace.cpp.
References ecvColor::RgbTpl< Type >::b, ecvColor::RgbTpl< Type >::g, cloudViewer::ScalarField::getMax(), cloudViewer::PointCloudTpl< T >::getPoint(), ccPointCloud::getPointColor(), cloudViewer::PointCloudTpl< T >::getPointScalarValue(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), m_cloud, ecvColor::RgbTpl< Type >::r, and cloudViewer::PointCloudTpl< T >::setCurrentScalarField().
Referenced by getSegmentCost().
getSegmentCostLight()
int ccTrace::getSegmentCostLight (int p1, int p2) protected
Definition at line 535 of file ccTrace.cpp.
References getSegmentCostDark().
Referenced by getSegmentCost().
getSegmentCostRGB()
int ccTrace::getSegmentCostRGB (int p1, int p2) protected
Definition at line 477 of file ccTrace.cpp.
References ecvColor::RgbTpl< Type >::b, ecvColor::RgbTpl< Type >::g, ccPointCloud::getPointColor(), m_cloud, and ecvColor::RgbTpl< Type >::r.
Referenced by getSegmentCost().
getSegmentCostScalar()
int ccTrace::getSegmentCostScalar (int p1, int p2) protected
Definition at line 661 of file ccTrace.cpp.
References ccPointCloud::getCurrentDisplayedScalarField(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), cloudViewer::ScalarField::getValue(), and m_cloud.
Referenced by getSegmentCost().
getSegmentCostScalarInv()
int ccTrace::getSegmentCostScalarInv (int p1, int p2) protected
Definition at line 670 of file ccTrace.cpp.
References ccPointCloud::getCurrentDisplayedScalarField(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), cloudViewer::ScalarField::getValue(), and m_cloud.
Referenced by getSegmentCost().
getWaypoint()
int ccTrace::getWaypoint (int n) inline
Definition at line 93 of file ccTrace.h.
References m_waypoints.
insertWaypoint()
int ccTrace::insertWaypoint (int pointId)
Definition at line 92 of file ccTrace.cpp.
References cloudViewer::PointCloudTpl< T >::getPoint(), m_cloud, m_previous, m_waypoints, and Vector3Tpl< Type >::norm2().
Referenced by ccTraceTool::pointPicked().
isCurvaturePrecomputed()
bool ccTrace::isCurvaturePrecomputed ()
Definition at line 811 of file ccTrace.cpp.
References cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), and m_cloud.
Referenced by buildCurvatureCost(), getSegmentCostCurve(), and ccTraceTool::pointPicked().
isGradientPrecomputed()
bool ccTrace::isGradientPrecomputed ()
Definition at line 806 of file ccTrace.cpp.
References cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), and m_cloud.
Referenced by buildGradientCost(), and ccTraceTool::pointPicked().
isTrace()
bool ccTrace::isTrace (ccHObject * object) static
Definition at line 1102 of file ccTrace.cpp.
References ccObject::hasMetaData().
Referenced by ccCompass::estimateP21(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), ccCompass::fitPlaneToGeoObject(), ccCompass::recalculateFitPlanes(), ccCompass::recalculateSelectedTraces(), and ccCompass::tryLoading().
optimizePath()
bool ccTrace::optimizePath (int maxIterations = 1000000)
Definition at line 149 of file ccTrace.cpp.
References ccPointCloud::addScalarField(), cloudViewer::ScalarField::computeMinAndMax(), finalizePath(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), m_cloud, m_trace, m_waypoints, optimizeSegment(), cloudViewer::PointCloudTpl< T >::setCurrentScalarField(), ccObject::setMetaData(), and cloudViewer::ReferenceCloud::size().
Referenced by ccTrace(), ccTraceTool::pointPicked(), recalculatePath(), and ccTraceTool::undo().
optimizeSegment()
std::deque< int > ccTrace::optimizeSegment (int start, int end, int offset = 0) protected
Definition at line 258 of file ccTrace.cpp.
References ecvColor::RgbTpl< Type >::b, ccGenericPointCloud::computeOctree(), ecvColor::RgbTpl< Type >::g, ccGenericPointCloud::getOctree(), cloudViewer::PointCloudTpl< T >::getPoint(), ccPointCloud::getPointColor(), getSegmentCost(), ccPointCloud::hasColors(), m_cloud, cloudViewer::DgmOctree::PointDescriptor::point, cloudViewer::DgmOctree::PointDescriptor::pointIndex, ecvColor::RgbTpl< Type >::r, cloudViewer::PointCloudTpl< T >::setPointScalarValue(), cloudViewer::PointCloudTpl< T >::size(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by optimizePath().
pushWaypoint()
void ccTrace::pushWaypoint (int pointId) inline
Definition at line 75 of file ccTrace.h.
References m_waypoints.
recalculatePath()
void ccTrace::recalculatePath ()
Definition at line 252 of file ccTrace.cpp.
References m_trace, and optimizePath().
Referenced by ccCompass::recalculateSelectedTraces().
undoLast()
void ccTrace::undoLast () inline
Definition at line 121 of file ccTrace.h.
References m_previous, m_trace, and m_waypoints.
Referenced by ccTraceTool::pointPicked(), and ccTraceTool::undo().
waypoint_count()
size_t ccTrace::waypoint_count () const inline
Definition at line 130 of file ccTrace.h.
References m_waypoints.
Referenced by ccTraceTool::pointPicked().
Member Data Documentation
COST_MODE
int ccTrace::COST_MODE = ccTrace::MODE::DARK static
Definition at line 203 of file ccTrace.h.
Referenced by ccTrace(), ccCompass::eventFilter(), getSegmentCost(), ccTraceTool::pointPicked(), and ccCompass::recalculateSelectedTraces().
m_cloud
ccPointCloud* ccTrace::m_cloud = 0 protected
Definition at line 241 of file ccTrace.h.
Referenced by bakePathToScalarField(), buildCurvatureCost(), buildGradientCost(), calculateOptimumSearchRadius(), drawMeOnly(), fitPlane(), getPointNormal(), getSegmentCost(), getSegmentCostCurve(), getSegmentCostDark(), getSegmentCostGrad(), getSegmentCostRGB(), getSegmentCostScalar(), getSegmentCostScalarInv(), insertWaypoint(), isCurvaturePrecomputed(), isGradientPrecomputed(), optimizePath(), and optimizeSegment().
m_previous
std::vector<int> ccTrace::m_previous protected
Definition at line 250 of file ccTrace.h.
Referenced by insertWaypoint(), and undoLast().
m_relMarkerScale
float ccTrace::m_relMarkerScale = 1.0f protected
Definition at line 240 of file ccTrace.h.
Referenced by drawMeOnly().
m_trace
std::vector<std::deque<int> > ccTrace::m_trace protected
Definition at line 246 of file ccTrace.h.
Referenced by bakePathToScalarField(), ccTrace(), drawMeOnly(), finalizePath(), optimizePath(), recalculatePath(), and undoLast().
m_waypoints
std::vector<int> ccTrace::m_waypoints protected
Definition at line 249 of file ccTrace.h.
Referenced by ccTrace(), deleteWaypoint(), drawMeOnly(), getWaypoint(), insertWaypoint(), optimizePath(), pushWaypoint(), undoLast(), and waypoint_count().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCompass/include/ccTrace.h
/root/ACloudViewer/plugins/core/Standard/qCompass/src/ccTrace.cpp