ACloudViewer: PoissonReconLib::IMesh< Real > Class Template Reference
PoissonReconLib::IMesh< Real > Class Template Reference abstract
Output mesh interface.
#include <PoissonReconLib.h>
Public Member Functions
virtual void addVertex (const Real *coords)=0
virtual void addNormal (const Real *coords)=0
virtual void addColor (const Real *rgb)=0
virtual void addDensity (double d)=0
virtual void addTriangle (size_t i1, size_t i2, size_t i3)=0
Detailed Description
template<typename Real>
class PoissonReconLib::IMesh< Real >
Output mesh interface.
Definition at line 150 of file PoissonReconLib.h.
Member Function Documentation
addColor()
template<typename Real > virtual void PoissonReconLib::IMesh< Real >::addColor (const Real * rgb) pure virtual
Implemented in MeshWrapper< Real >.
Referenced by ExtractMesh().
addDensity()
template<typename Real > virtual void PoissonReconLib::IMesh< Real >::addDensity (double d) pure virtual
Implemented in MeshWrapper< Real >.
Referenced by ExtractMesh().
addNormal()
template<typename Real > virtual void PoissonReconLib::IMesh< Real >::addNormal (const Real * coords) pure virtual
Implemented in MeshWrapper< Real >.
addTriangle()
template<typename Real > virtual void PoissonReconLib::IMesh< Real >::addTriangle (size_t i1, size_t i2, size_t i3) pure virtual
Implemented in MeshWrapper< Real >.
Referenced by ExtractMesh().
addVertex()
template<typename Real > virtual void PoissonReconLib::IMesh< Real >::addVertex (const Real * coords) pure virtual
Implemented in MeshWrapper< Real >.
Referenced by ExtractMesh().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qPoissonRecon/extern/Src_CC_wrap/PoissonReconLib.h