ACloudViewer: cloudViewer::pipelines::registration::TransformationEstimation Class Reference
cloudViewer::pipelines::registration::TransformationEstimation Class Reference abstract
#include <TransformationEstimation.h>
Public Member Functions
TransformationEstimation ()
Default Constructor.
virtual ~TransformationEstimation ()
virtual TransformationEstimationType GetTransformationEstimationType () const =0
virtual double ComputeRMSE (const ccPointCloud &source, const ccPointCloud &target, const CorrespondenceSet &corres) const =0
virtual Eigen::Matrix4d ComputeTransformation (const ccPointCloud &source, const ccPointCloud &target, const CorrespondenceSet &corres) const =0
Detailed Description
Base class that estimates a transformation between two point clouds The virtual function ComputeTransformation() must be implemented in subclasses.
Definition at line 38 of file TransformationEstimation.h.
Constructor & Destructor Documentation
TransformationEstimation()
cloudViewer::pipelines::registration::TransformationEstimation::TransformationEstimation () inline
Default Constructor.
Definition at line 41 of file TransformationEstimation.h.
~TransformationEstimation()
virtual cloudViewer::pipelines::registration::TransformationEstimation::~TransformationEstimation () inline virtual
Definition at line 42 of file TransformationEstimation.h.
Member Function Documentation
ComputeRMSE()
virtual double cloudViewer::pipelines::registration::TransformationEstimation::ComputeRMSE (const ccPointCloud & source, const ccPointCloud & target, const CorrespondenceSet & corres) const pure virtual
Compute RMSE between source and target points cloud given correspondences.
Parameters
source Source point cloud.
target Target point cloud.
corres Correspondence set between source and target point cloud.
Implemented in cloudViewer::pipelines::registration::TransformationEstimationPointToPlane, cloudViewer::pipelines::registration::TransformationEstimationPointToPoint, cloudViewer::pipelines::registration::TransformationEstimationForGeneralizedICP, and cloudViewer::pipelines::registration::TransformationEstimationForColoredICP.
ComputeTransformation()
virtual Eigen::Matrix4d cloudViewer::pipelines::registration::TransformationEstimation::ComputeTransformation (const ccPointCloud & source, const ccPointCloud & target, const CorrespondenceSet & corres) const pure virtual
Compute transformation from source to target point cloud given correspondences.
Parameters
source Source point cloud.
target Target point cloud.
corres Correspondence set between source and target point cloud.
Implemented in cloudViewer::pipelines::registration::TransformationEstimationPointToPlane, cloudViewer::pipelines::registration::TransformationEstimationPointToPoint, cloudViewer::pipelines::registration::TransformationEstimationForGeneralizedICP, and cloudViewer::pipelines::registration::TransformationEstimationForColoredICP.
Referenced by cloudViewer::pipelines::registration::RegistrationICP(), and cloudViewer::pipelines::registration::RegistrationRANSACBasedOnCorrespondence().
GetTransformationEstimationType()
virtual TransformationEstimationType cloudViewer::pipelines::registration::TransformationEstimation::GetTransformationEstimationType () const pure virtual
Implemented in cloudViewer::pipelines::registration::TransformationEstimationPointToPlane, cloudViewer::pipelines::registration::TransformationEstimationPointToPoint, cloudViewer::pipelines::registration::TransformationEstimationForGeneralizedICP, and cloudViewer::pipelines::registration::TransformationEstimationForColoredICP.
Referenced by cloudViewer::pipelines::registration::RegistrationICP().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/pipelines/registration/TransformationEstimation.h