ACloudViewer: cloudViewer::core::SmallVectorTemplateBase< T, true > Class Template Reference
cloudViewer::core::SmallVectorTemplateBase< T, true > Class Template Reference
#include <SmallVector.h>
Public Member Functions
void push_back (ValueParamT Elt)
void pop_back ()
Public Member Functions inherited from cloudViewer::core::SmallVectorTemplateCommon< T, typename >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >
size_t size () const
size_t capacity () const
bool empty () const
Protected Types
using ValueParamT = typename std::conditional< TakesParamByValue, T, const T & >::type
Protected Member Functions
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
const T * reserveForParamAndGetAddress (const T &Elt, size_t N=1)
T * reserveForParamAndGetAddress (T &Elt, size_t N=1)
void growAndAssign (size_t NumElts, T Elt)
template<typename... ArgTypes>
T & growAndEmplaceBack (ArgTypes &&...Args)
Protected Member Functions inherited from cloudViewer::core::SmallVectorTemplateCommon< T, typename >
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSize, size_t TSize)
bool isSmall () const
void resetToSmall ()
Put this vector in a state of being small.
bool isReferenceToRange (const void *V, const void *First, const void *Last) const
Return true if V is an internal reference to the given range.
bool isReferenceToStorage (const void *V) const
Return true if V is an internal reference to this vector.
bool isRangeInStorage (const void *First, const void *Last) const
bool isSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
void assertSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Check whether Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToAdd (const void *Elt, size_t N=1)
void assertSafeToReferenceAfterClear (const T *From, const T *To)
Check whether any part of the range will be invalidated by clearing.
template<class ItTy , std::enable_if_t< !std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToReferenceAfterClear (ItTy, ItTy)
void assertSafeToAddRange (const T *From, const T *To)
Check whether any part of the range will be invalidated by growing.
template<class ItTy , std::enable_if_t< !std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToAddRange (ItTy, ItTy)
Protected Member Functions inherited from cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (size_t MinSize, size_t TSize, size_t &NewCapacity)
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
void set_size (size_t N)
Static Protected Member Functions
static void destroy_range (T *, T *)
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
template<typename T1 , typename T2 >
static void uninitialized_copy (T1 *I, T1 *E, T2 *Dest, std::enable_if_t< std::is_same< typename std::remove_const< T1 >::type, T2 >::value > *=nullptr)
static ValueParamT forward_value_param (ValueParamT V)
Copy V or return a reference, depending on ValueParamT.
Static Protected Member Functions inherited from cloudViewer::core::SmallVectorTemplateCommon< T, typename >
template<class U >
static const T * reserveForParamAndGetAddressImpl (U *This, const T &Elt, size_t N)
Static Protected Member Functions inherited from cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Static Protected Attributes
static constexpr bool TakesParamByValue = sizeof(T) <= 2 * sizeof(void *)
Additional Inherited Members
Public Types inherited from cloudViewer::core::SmallVectorTemplateCommon< T, typename >
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = std::reverse_iterator< iterator >
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Protected Attributes inherited from cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >
void * BeginX
SmallVectorSizeType< T > Size
SmallVectorSizeType< T > Capacity
Detailed Description
template<typename T>
class cloudViewer::core::SmallVectorTemplateBase< T, true >
SmallVectorTemplateBase<TriviallyCopyable = true> - This is where we put method implementations that are designed to work with trivially copyable T's. This allows using memcpy in place of copy/move construction and skipping destruction.
Definition at line 513 of file SmallVector.h.
Member Typedef Documentation
ValueParamT
template<typename T > using cloudViewer::core::SmallVectorTemplateBase< T, true >::ValueParamT = typename std::conditional<TakesParamByValue, T, const T &>::type protected
Either const T& or T, depending on whether it's cheap enough to take parameters by value.
Definition at line 523 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorTemplateBase()
template<typename T > cloudViewer::core::SmallVectorTemplateBase< T, true >::SmallVectorTemplateBase (size_t Size) inline protected
Definition at line 526 of file SmallVector.h.
Member Function Documentation
destroy_range()
template<typename T > static void cloudViewer::core::SmallVectorTemplateBase< T, true >::destroy_range (T * , T *) inline static protected
Definition at line 529 of file SmallVector.h.
forward_value_param()
template<typename T > static ValueParamT cloudViewer::core::SmallVectorTemplateBase< T, true >::forward_value_param (ValueParamT V) inline static protected
Copy V or return a reference, depending on ValueParamT.
Definition at line 582 of file SmallVector.h.
grow()
template<typename T > void cloudViewer::core::SmallVectorTemplateBase< T, true >::grow (size_t MinSize = 0) inline protected
Double the size of the allocated memory, guaranteeing space for at least one more element or MinSize if specified.
Definition at line 566 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::grow_pod().
growAndAssign()
template<typename T > void cloudViewer::core::SmallVectorTemplateBase< T, true >::growAndAssign (size_t NumElts, T Elt) inline protected
Definition at line 584 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::grow(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size().
growAndEmplaceBack()
template<typename T > template<typename... ArgTypes> T& cloudViewer::core::SmallVectorTemplateBase< T, true >::growAndEmplaceBack (ArgTypes &&... Args) inline protected
Definition at line 595 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::back(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::push_back().
pop_back()
template<typename T > void cloudViewer::core::SmallVectorTemplateBase< T, true >::pop_back () inline
Definition at line 610 of file SmallVector.h.
References cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size().
push_back()
template<typename T > void cloudViewer::core::SmallVectorTemplateBase< T, true >::push_back (ValueParamT Elt) inline
Definition at line 604 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size().
reserveForParamAndGetAddress() [1/2]
template<typename T > const T* cloudViewer::core::SmallVectorTemplateBase< T, true >::reserveForParamAndGetAddress (const T & Elt, size_t N = 1) inline protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 570 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::reserveForParamAndGetAddressImpl().
reserveForParamAndGetAddress() [2/2]
template<typename T > T* cloudViewer::core::SmallVectorTemplateBase< T, true >::reserveForParamAndGetAddress (T & Elt, size_t N = 1) inline protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 576 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::reserveForParamAndGetAddressImpl().
uninitialized_copy() [1/2]
template<typename T > template<typename It1 , typename It2 > static void cloudViewer::core::SmallVectorTemplateBase< T, true >::uninitialized_copy (It1 I, It1 E, It2 Dest) inline static protected
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Definition at line 542 of file SmallVector.h.
uninitialized_copy() [2/2]
template<typename T > template<typename T1 , typename T2 > static void cloudViewer::core::SmallVectorTemplateBase< T, true >::uninitialized_copy (T1 * I, T1 * E, T2 * Dest, std::enable_if_t< std::is_same< typename std::remove_const< T1 >::type, T2 >::value > * = nullptr) inline static protected
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Definition at line 550 of file SmallVector.h.
uninitialized_move()
template<typename T > template<typename It1 , typename It2 > static void cloudViewer::core::SmallVectorTemplateBase< T, true >::uninitialized_move (It1 I, It1 E, It2 Dest) inline static protected
Move the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Definition at line 534 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateBase< T, bool >::uninitialized_copy().
Member Data Documentation
TakesParamByValue
template<typename T > constexpr bool cloudViewer::core::SmallVectorTemplateBase< T, true >::TakesParamByValue = sizeof(T) <= 2 * sizeof(void *) static constexpr protected
True if it's cheap enough to take parameters by value. Doing so avoids overhead related to mitigations for reference invalidation.
Definition at line 519 of file SmallVector.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/SmallVector.h