ACloudViewer: ccTool Class Reference
ccTool Class Reference
#include <ccTool.h>
Public Member Functions
virtual ~ccTool ()
void initializeTool (ecvMainAppInterface *app)
virtual void toolActivated ()
virtual void toolDisactivated ()
virtual void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccHObject *pickedObject, const CCVector3 &P)
virtual void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccPointCloud *cloud, const CCVector3 &P)
virtual void onNewSelection (const ccHObject::Container &selectedEntities)
virtual void accept ()
virtual void cancel ()
virtual bool canUndo ()
virtual void undo ()
Protected Member Functions
ccTool ()
Protected Attributes
ecvMainAppInterface * m_app
QWidget * m_window
Detailed Description
Definition at line 18 of file ccTool.h.
Constructor & Destructor Documentation
~ccTool()
virtual ccTool::~ccTool () inline virtual
Definition at line 20 of file ccTool.h.
ccTool()
ccTool::ccTool () inline protected
Definition at line 64 of file ccTool.h.
Member Function Documentation
accept()
virtual void ccTool::accept () inline virtual
Reimplemented in ccTraceTool, ccTopologyTool, ccThicknessTool, and ccLineationTool.
Definition at line 52 of file ccTool.h.
Referenced by ccCompass::onAccept().
cancel()
virtual void ccTool::cancel () inline virtual
Reimplemented in ccTraceTool, ccTopologyTool, ccThicknessTool, and ccLineationTool.
Definition at line 55 of file ccTool.h.
Referenced by ccCompass::onClose(), and ccCompass::stopMeasuring().
canUndo()
virtual bool ccTool::canUndo () inline virtual
Reimplemented in ccTraceTool.
Definition at line 58 of file ccTool.h.
Referenced by ccCompass::addPinchNode(), ccCompass::setNote(), ccCompass::setPlane(), and ccCompass::setThickness().
initializeTool()
void ccTool::initializeTool (ecvMainAppInterface * app) inline
Definition at line 22 of file ccTool.h.
References ecvDisplayTools::GetCurrentScreen(), m_app, and m_window.
Referenced by ccCompass::doAction().
onNewSelection()
virtual void ccTool::onNewSelection (const ccHObject::Container & selectedEntities) inline virtual
Reimplemented in ccTraceTool, ccTopologyTool, and ccThicknessTool.
Definition at line 48 of file ccTool.h.
pointPicked() [1/2]
virtual void ccTool::pointPicked (ccHObject * insertPoint, unsigned itemIdx, ccHObject * pickedObject, const CCVector3 & P) inline virtual
Reimplemented in ccThicknessTool.
Definition at line 35 of file ccTool.h.
Referenced by ccCompass::pointPicked().
pointPicked() [2/2]
virtual void ccTool::pointPicked (ccHObject * insertPoint, unsigned itemIdx, ccPointCloud * cloud, const CCVector3 & P) inline virtual
Reimplemented in ccTraceTool, ccThicknessTool, ccPinchNodeTool, ccNoteTool, ccLineationTool, and ccFitPlaneTool.
Definition at line 42 of file ccTool.h.
toolActivated()
virtual void ccTool::toolActivated () inline virtual
Reimplemented in ccTraceTool, ccTopologyTool, ccThicknessTool, ccPinchNodeTool, ccNoteTool, and ccFitPlaneTool.
Definition at line 28 of file ccTool.h.
Referenced by ccCompass::addPinchNode(), ccCompass::setLineation(), ccCompass::setNote(), ccCompass::setPlane(), ccCompass::setThickness(), ccCompass::setTrace(), and ccCompass::startMeasuring().
toolDisactivated()
virtual void ccTool::toolDisactivated () inline virtual
Reimplemented in ccTraceTool, ccTopologyTool, ccThicknessTool, ccPinchNodeTool, ccNoteTool, ccLineationTool, and ccFitPlaneTool.
Definition at line 31 of file ccTool.h.
Referenced by ccCompass::cleanupBeforeToolChange(), and ccCompass::stopMeasuring().
undo()
virtual void ccTool::undo () inline virtual
Reimplemented in ccTraceTool.
Definition at line 61 of file ccTool.h.
Referenced by ccCompass::onUndo().
Member Data Documentation
m_app
ecvMainAppInterface* ccTool::m_app protected
Definition at line 67 of file ccTool.h.
Referenced by ccLineationTool::cancel(), ccTraceTool::cancel(), ccTraceTool::finishCurrentTrace(), initializeTool(), ccThicknessTool::onNewSelection(), ccTopologyTool::onNewSelection(), ccTraceTool::pickupTrace(), ccThicknessTool::pointPicked(), ccFitPlaneTool::pointPicked(), ccLineationTool::pointPicked(), ccNoteTool::pointPicked(), ccPinchNodeTool::pointPicked(), ccTraceTool::pointPicked(), ccThicknessTool::toolActivated(), ccTraceTool::toolActivated(), ccThicknessTool::toolDisactivated(), and ccTraceTool::undo().
m_window
QWidget* ccTool::m_window protected
Definition at line 70 of file ccTool.h.
Referenced by initializeTool().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qCompass/include/ccTool.h