ACloudViewer: PCLModules::TemplateMatching Class Reference
PCLModules::TemplateMatching Class Reference
#include <PCLModules.h>
Classes
struct Result
Public Member Functions
TemplateMatching ()
~TemplateMatching ()
void setminSampleDis (float minSampleDistance)
void setmaxCorrespondenceDis (float maxCorrespondenceDistance)
void setmaxIterations (int maxIterations)
void setTargetCloud (FeatureCloud &target_cloud)
void addTemplateCloud (FeatureCloud &template_cloud)
FeatureCloud * getTemplateCloud (int index)
void align (FeatureCloud &template_cloud, TemplateMatching::Result &result)
void alignAll (std::vector< TemplateMatching::Result, Eigen::aligned_allocator< Result >> &results)
int findBestAlignment (TemplateMatching::Result &result)
void clear ()
Detailed Description
Definition at line 1513 of file PCLModules.h.
Constructor & Destructor Documentation
TemplateMatching()
PCLModules::TemplateMatching::TemplateMatching ()
Definition at line 387 of file PCLModules.cpp.
~TemplateMatching()
PCLModules::TemplateMatching::~TemplateMatching () inline
Definition at line 1522 of file PCLModules.h.
Member Function Documentation
addTemplateCloud()
void PCLModules::TemplateMatching::addTemplateCloud (FeatureCloud & template_cloud) inline
Definition at line 1538 of file PCLModules.h.
Referenced by TemplateAlignment::compute().
align()
void PCLModules::TemplateMatching::align (FeatureCloud & template_cloud, TemplateMatching::Result & result)
Definition at line 406 of file PCLModules.cpp.
References float, PCLModules::FeatureCloud::getLocalFeatures(), PCLModules::FeatureCloud::getPointCloud(), and result.
Referenced by alignAll().
alignAll()
void PCLModules::TemplateMatching::alignAll (std::vector< TemplateMatching::Result, Eigen::aligned_allocator< Result >> & results)
Definition at line 421 of file PCLModules.cpp.
References align().
Referenced by findBestAlignment().
clear()
void PCLModules::TemplateMatching::clear () inline
Definition at line 1561 of file PCLModules.h.
Referenced by TemplateAlignment::getParametersFromDialog().
findBestAlignment()
int PCLModules::TemplateMatching::findBestAlignment (TemplateMatching::Result & result)
Definition at line 432 of file PCLModules.cpp.
References alignAll(), PCLModules::TemplateMatching::Result::fitness_score, and result.
Referenced by TemplateAlignment::compute().
getTemplateCloud()
FeatureCloud* PCLModules::TemplateMatching::getTemplateCloud (int index) inline
Definition at line 1543 of file PCLModules.h.
Referenced by TemplateAlignment::compute().
setmaxCorrespondenceDis()
void PCLModules::TemplateMatching::setmaxCorrespondenceDis (float maxCorrespondenceDistance) inline
Definition at line 1527 of file PCLModules.h.
Referenced by TemplateAlignment::getParametersFromDialog().
setmaxIterations()
void PCLModules::TemplateMatching::setmaxIterations (int maxIterations) inline
Definition at line 1530 of file PCLModules.h.
Referenced by TemplateAlignment::getParametersFromDialog().
setminSampleDis()
void PCLModules::TemplateMatching::setminSampleDis (float minSampleDistance) inline
Definition at line 1524 of file PCLModules.h.
Referenced by TemplateAlignment::getParametersFromDialog().
setTargetCloud()
void PCLModules::TemplateMatching::setTargetCloud (FeatureCloud & target_cloud)
Definition at line 399 of file PCLModules.cpp.
References PCLModules::FeatureCloud::getLocalFeatures(), and PCLModules::FeatureCloud::getPointCloud().
Referenced by TemplateAlignment::compute().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/PclUtils/PCLModules.h
/root/ACloudViewer/libs/PCLEngine/PclUtils/PCLModules.cpp