ACloudViewer: PythonRuntimeSettings Class Reference
PythonRuntimeSettings Class Reference final
#include <PythonRuntimeSettings.h>
Public Member Functions
PythonRuntimeSettings (QWidget *parent=nullptr)
QStringList pluginsPaths () const
PythonConfig pythonEnvConfig () const
bool isDefaultPythonEnv () const
Detailed Description
Definition at line 16 of file PythonRuntimeSettings.h.
Constructor & Destructor Documentation
PythonRuntimeSettings()
PythonRuntimeSettings::PythonRuntimeSettings (QWidget * parent = nullptr) explicit
Definition at line 133 of file PythonRuntimeSettings.cpp.
References SETTINGS_ICON_PATH.
Member Function Documentation
isDefaultPythonEnv()
bool PythonRuntimeSettings::isDefaultPythonEnv () const
Definition at line 276 of file PythonRuntimeSettings.cpp.
Referenced by PythonPlugin::PythonPlugin().
pluginsPaths()
QStringList PythonRuntimeSettings::pluginsPaths () const
Definition at line 244 of file PythonRuntimeSettings.cpp.
Referenced by PythonPlugin::setMainAppInterface().
pythonEnvConfig()
PythonConfig PythonRuntimeSettings::pythonEnvConfig () const
Definition at line 249 of file PythonRuntimeSettings.cpp.
References PythonConfig::initBundled(), PythonConfig::initDefault(), and PythonConfig::initFromLocation().
Referenced by PythonPlugin::PythonPlugin().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonRuntimeSettings.h
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonRuntimeSettings.cpp