ACloudViewer: colmap::VisibilityPyramid Class Reference
colmap::VisibilityPyramid Class Reference
#include <visibility_pyramid.h>
Public Member Functions
VisibilityPyramid ()
VisibilityPyramid (const size_t num_levels, const size_t width, const size_t height)
void SetPoint (const double x, const double y)
void ResetPoint (const double x, const double y)
size_t NumLevels () const
size_t Width () const
size_t Height () const
size_t Score () const
size_t MaxScore () const
Detailed Description
Definition at line 28 of file visibility_pyramid.h.
Constructor & Destructor Documentation
VisibilityPyramid() [1/2]
colmap::VisibilityPyramid::VisibilityPyramid ()
Definition at line 38 of file visibility_pyramid.cc.
VisibilityPyramid() [2/2]
colmap::VisibilityPyramid::VisibilityPyramid (const size_t num_levels, const size_t width, const size_t height)
Definition at line 40 of file visibility_pyramid.cc.
Member Function Documentation
Height()
size_t colmap::VisibilityPyramid::Height () const inline
Definition at line 73 of file visibility_pyramid.h.
Referenced by BOOST_AUTO_TEST_CASE().
MaxScore()
size_t colmap::VisibilityPyramid::MaxScore () const inline
Definition at line 77 of file visibility_pyramid.h.
Referenced by BOOST_AUTO_TEST_CASE().
NumLevels()
size_t colmap::VisibilityPyramid::NumLevels () const inline
Definition at line 69 of file visibility_pyramid.h.
Referenced by BOOST_AUTO_TEST_CASE().
ResetPoint()
void colmap::VisibilityPyramid::ResetPoint (const double x, const double y)
Definition at line 74 of file visibility_pyramid.cc.
References x, and y.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Image::DecrementCorrespondenceHasPoint3D().
Score()
size_t colmap::VisibilityPyramid::Score () const inline
Definition at line 75 of file visibility_pyramid.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Image::Point3DVisibilityScore().
SetPoint()
void colmap::VisibilityPyramid::SetPoint (const double x, const double y)
Definition at line 52 of file visibility_pyramid.cc.
References x, and y.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Image::IncrementCorrespondenceHasPoint3D().
Width()
size_t colmap::VisibilityPyramid::Width () const inline
Definition at line 71 of file visibility_pyramid.h.
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/visibility_pyramid.h
/root/ACloudViewer/libs/Reconstruction/src/base/visibility_pyramid.cc