ACloudViewer: cloudViewer::PointViewerWidget Class Reference
cloudViewer::PointViewerWidget Class Reference
#include <PointViewerWidget.h>
Public Member Functions
PointViewerWidget (QWidget *parent, ModelViewerWidget *model_viewer_widget, OptionManager *option)
void Show (const colmap::point3D_t point3D_id)
Detailed Description
Definition at line 21 of file PointViewerWidget.h.
Constructor & Destructor Documentation
PointViewerWidget()
cloudViewer::PointViewerWidget::PointViewerWidget (QWidget * parent, ModelViewerWidget * model_viewer_widget, OptionManager * option)
Definition at line 19 of file PointViewerWidget.cpp.
Member Function Documentation
Show()
void cloudViewer::PointViewerWidget::Show (const colmap::point3D_t point3D_id)
Definition at line 107 of file PointViewerWidget.cpp.
References colmap::BitmapToQImageRGB(), cloudViewer::ModelViewerWidget::cameras, QtCompat::endl(), ecvColor::green(), image, colmap::OptionManager::image_path, cloudViewer::ModelViewerWidget::images, cloudViewer::utility::filesystem::JoinPaths(), colmap::kInvalidPoint3DId, cloudViewer::t::geometry::path, cloudViewer::ModelViewerWidget::points3D, colmap::ProjectPointToImage(), colmap::Bitmap::Read(), ecvColor::red(), patch::to_string(), x, colmap::Point2D::X(), colmap::Point2D::XY(), y, and colmap::Point2D::Y().
Referenced by cloudViewer::ModelViewerWidget::ShowPointInfo().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/reconstruction/PointViewerWidget.h
/root/ACloudViewer/app/reconstruction/PointViewerWidget.cpp