ACloudViewer: PoissonReconLib Class Reference
PoissonReconLib Class Reference
Wrapper to use PoissonRecon (Kazhdan et. al) as a library.
#include <PoissonReconLib.h>
Classes
class ICloud
Input cloud interface.
class IMesh
Output mesh interface.
struct Parameters
Algorithm parameters.
Static Public Member Functions
static bool Reconstruct (const Parameters &params, const PoissonReconLib::ICloud< float > &inCloud, PoissonReconLib::IMesh< float > &ouMesh)
Reconstruct a mesh from a point cloud (float version)
static bool Reconstruct (const Parameters &params, const PoissonReconLib::ICloud< double > &inCloud, PoissonReconLib::IMesh< double > &ouMesh)
Reconstruct a mesh from a point cloud (double version)
Detailed Description
Wrapper to use PoissonRecon (Kazhdan et. al) as a library.
Definition at line 24 of file PoissonReconLib.h.
Member Function Documentation
Reconstruct() [1/2]
bool PoissonReconLib::Reconstruct (const Parameters & params, const PoissonReconLib::ICloud< double > & inCloud, PoissonReconLib::IMesh< double > & ouMesh) static
Reconstruct a mesh from a point cloud (double version)
Definition at line 757 of file PoissonReconLib.cpp.
References DIMENSION, PoissonReconLib::Parameters::DIRICHLET, PoissonReconLib::Parameters::FREE, PoissonReconLib::ICloud< Real >::hasNormals(), PoissonReconLib::Parameters::NEUMANN, and params.
Reconstruct() [2/2]
bool PoissonReconLib::Reconstruct (const Parameters & params, const PoissonReconLib::ICloud< float > & inCloud, PoissonReconLib::IMesh< float > & ouMesh) static
Reconstruct a mesh from a point cloud (float version)
Definition at line 702 of file PoissonReconLib.cpp.
References DIMENSION, PoissonReconLib::Parameters::DIRICHLET, PoissonReconLib::Parameters::FREE, PoissonReconLib::ICloud< Real >::hasNormals(), PoissonReconLib::Parameters::NEUMANN, and params.
Referenced by doReconstruct().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPoissonRecon/extern/Src_CC_wrap/PoissonReconLib.h
/root/ACloudViewer/plugins/core/Standard/qPoissonRecon/extern/Src_CC_wrap/PoissonReconLib.cpp