ACloudViewer: cloudViewer::ChamferDistanceTransform Class Reference
cloudViewer::ChamferDistanceTransform Class Reference
Class to compute a Chamfer distance field on a 3D grid.
#include <ChamferDistanceTransform.h>
Public Member Functions
bool init (const Tuple3ui &gridSize)
Initializes the grid.
int propagateDistance (CHAMFER_DISTANCE_TYPE type, GenericProgressCallback *progressCb=nullptr)
Computes the Chamfer distance on the whole grid.
Public Member Functions inherited from cloudViewer::Grid3D< unsigned short >
Grid3D ()
Default constructor.
const Tuple3ui & size () const
Returns the grid dimensions.
bool isInitialized () const
Returns whether the grid has been initialized or not.
void clear ()
Clears the grid.
bool init (unsigned di, unsigned dj, unsigned dk, unsigned margin, GridElement defaultCellValue=0)
Initializes the grid.
Tuple3i computeCellPos (const CCVector3 &P, const CCVector3 &gridMinCorner, PointCoordinateType cellSize) const
Computes the (grid) cell position that contains a given point.
bool intersectWith (GenericIndexedMesh *mesh, PointCoordinateType cellLength, const CCVector3 &gridMinCorner, GridElement intersectValue=0, GenericProgressCallback *progressCb=nullptr)
Intersects this grid with a mesh.
bool intersectWith (GenericIndexedMesh *mesh, PointCoordinateType cellLength, const CCVector3 &gridMinCorner, genericCellTriIntersectionAction action, GenericProgressCallback *progressCb=nullptr)
Intersects this grid with a mesh (generic form)
bool intersectWith (GenericCloud *cloud, PointCoordinateType cellLength, const CCVector3 &gridMinCorner, GridElement intersectValue=0, GenericProgressCallback *progressCb=nullptr)
Intersects this grid with a cloud.
void setValue (int i, int j, int k, GridElement value)
Sets the value of a given cell.
void setValue (const Tuple3i &cellPos, GridElement value)
Sets the value of a given cell.
const GridElement & getValue (int i, int j, int k) const
Returns the value of a given cell (const version)
GridElement & getValue (int i, int j, int k)
Returns the value of a given cell.
const GridElement & getValue (Tuple3i &cellPos) const
Returns the value of a given cell const version)
GridElement & getValue (Tuple3i &cellPos)
Returns the value of a given cell.
GridElement * data ()
Gives access to the internal grid data (with margin)
const GridElement * data () const
Gives access to the internal grid data (with margin) (const version)
uint64_t innerCellCount () const
Returns the number of cell count (whithout margin)
uint64_t totalCellCount () const
Returns the total number of cell count (with margin)
Static Public Attributes
static const unsigned short MAX_DIST = 0xFAFA
Max possible 'distance'.
Additional Inherited Members
Public Types inherited from cloudViewer::Grid3D< unsigned short >
using GridElement = unsigned short
Cell type.
using genericCellTriIntersectionAction = std::function< void(const Tuple3i &, unsigned)>
Protected Member Functions inherited from cloudViewer::Grid3D< unsigned short >
int64_t pos2index (int i, int j, int k) const
Converts a 3D position to an absolute index.
Protected Attributes inherited from cloudViewer::Grid3D< unsigned short >
std::vector< GridElement > m_grid
Grid data.
Tuple3ui m_innerSize
Dimensions of the grid (without margin)
int64_t m_margin
Margin.
int64_t m_rowSize
1D row size (with margin)
int64_t m_sliceSize
2D slice size (with margin)
uint64_t m_innerCellCount
3D grid size without margin
uint64_t m_totalCellCount
3D grid size with margin
int64_t m_marginShift
First index of real data (i.e. after marin)
Detailed Description
Class to compute a Chamfer distance field on a 3D grid.
Internally we use 'unsigned short' value to limit memory consumption. For computational reasons, the max computable 'distance' is 0xFAFA = 64250.
Definition at line 24 of file ChamferDistanceTransform.h.
Member Function Documentation
init()
bool cloudViewer::ChamferDistanceTransform::init (const Tuple3ui & gridSize) inline
Initializes the grid.
'Zero' cells must be initialized with setValue(0). The grid must be explicitelty initialized prior to any action.
Returns
true if the initialization succeeded
Definition at line 37 of file ChamferDistanceTransform.h.
References cloudViewer::Grid3D< Type >::init(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by define_ChamferDistanceTransform().
propagateDistance()
int ChamferDistanceTransform::propagateDistance (CHAMFER_DISTANCE_TYPE type, GenericProgressCallback * progressCb = nullptr)
Computes the Chamfer distance on the whole grid.
Propagates the distances on the whole grid. The 'zeros' should have already been initialized before calling this method (see ChamferDistanceTransform::setZero).
Parameters
type the Chamfer distance type
progressCb the client application can get some notification of the process progress through this callback mechanism (see GenericProgressCallback)
Returns
max distance (or -1 if an error occurred)
Definition at line 112 of file ChamferDistanceTransform.cpp.
References BackwardNeighbours111, BackwardNeighbours345, CHAMFER_111, CHAMFER_345, ForwardNeighbours111, ForwardNeighbours345, cloudViewer::Grid3D< unsigned short >::m_grid, cloudViewer::Grid3D< unsigned short >::m_innerSize, cloudViewer::Grid3D< unsigned short >::m_rowSize, cloudViewer::Grid3D< unsigned short >::m_sliceSize, min(), cloudViewer::NormalizedProgress::oneStep(), cloudViewer::Grid3D< unsigned short >::pos2index(), cloudViewer::GenericProgressCallback::setInfo(), cloudViewer::GenericProgressCallback::setMethodTitle(), cloudViewer::GenericProgressCallback::start(), cloudViewer::GenericProgressCallback::textCanBeEdited(), type, cloudViewer::GenericProgressCallback::update(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by define_ChamferDistanceTransform().
Member Data Documentation
MAX_DIST
const unsigned short cloudViewer::ChamferDistanceTransform::MAX_DIST = 0xFAFA static
Max possible 'distance'.
Warning
Never pass a 'constant initializer' by reference
Definition at line 30 of file ChamferDistanceTransform.h.
Referenced by define_ChamferDistanceTransform().
The documentation for this class was generated from the following files:
/root/ACloudViewer/core/include/ChamferDistanceTransform.h
/root/ACloudViewer/core/src/ChamferDistanceTransform.cpp