ACloudViewer: Chi2Helper Class Reference
Chi2Helper Class Reference
Package of methods to compute Chi2 related stuff.
#include <Chi2Helper.h>
Static Public Member Functions
static double poz (double z)
Probability of normal z value.
static double EXP_MAX_A_VALUE ()
Value above which exp(EXP_MAX_A_VALUE) diverges.
static double pochisq (double x, int df)
Probability of chi-square value.
static double critchi (double p, int df)
Compute critical chi-square value toproduce given p.
Detailed Description
Package of methods to compute Chi2 related stuff.
The following JavaScript functions for calculating normal and chi-square probabilities and critical values were adapted by John Walker from C implementations written by Gary Perlman of Wang Institute, Tyngsboro, MA 01879. Both the original C code and this JavaScript edition are in the public domain.
Definition at line 28 of file Chi2Helper.h.
Member Function Documentation
critchi()
static double Chi2Helper::critchi (double p, int df) inline static
Compute critical chi-square value toproduce given p.
We just do a bisection search for a value within CHI_EPSILON, relying on the monotonicity of pochisq().
Definition at line 148 of file Chi2Helper.h.
References pochisq().
Referenced by cloudViewer::StatisticalTestingTools::computeChi2Fractile().
EXP_MAX_A_VALUE()
static double Chi2Helper::EXP_MAX_A_VALUE () inline static
Value above which exp(EXP_MAX_A_VALUE) diverges.
Definition at line 99 of file Chi2Helper.h.
Referenced by pochisq().
pochisq()
static double Chi2Helper::pochisq (double x, int df) inline static
Probability of chi-square value.
Adapted from: Hill, I. D. and Pike, M. C. Algorithm 299 Collected Algorithms for the CACM 1967 p. 243 Updated for rounding errors based on remark in ACM TOMS June 1985, page 185
Definition at line 108 of file Chi2Helper.h.
References a, e, EXP_MAX_A_VALUE(), I_SQRT_PI, LOG_SQRT_PI, poz(), x, y, and z.
Referenced by cloudViewer::StatisticalTestingTools::computeChi2Probability(), and critchi().
poz()
static double Chi2Helper::poz (double z) inline static
Probability of normal z value.
Adapted from a polynomial approximation in: Ibbetson D, Algorithm 209 Collected Algorithms of the CACM 1963 p. 616 Note: This routine has six digit accuracy, so it is only useful for absolute z values < 6. For z values >= to 6.0, poz() returns 0.0.
Definition at line 38 of file Chi2Helper.h.
References x, y, and z.
Referenced by pochisq().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/Chi2Helper.h