ACloudViewer: ccHistogramWindowDlg Class Reference
ccHistogramWindowDlg Class Reference
Encapsulating dialog for ccHistogramWindow.
#include <ecvHistogramWindow.h>
Public Member Functions
ccHistogramWindowDlg (QWidget *parent=0)
Default constructor.
virtual ~ccHistogramWindowDlg ()
Destructor.
ccHistogramWindow * window ()
Returns encapsulated ccHistogramWindow.
bool exportToCSV (QString filename) const
Exports histogram to a CSV file.
Protected Member Functions
void onExportToCSV ()
When the export to CSV file button is pressed.
void onExportToImage ()
When the export to Image file button is pressed.
Protected Attributes
ccHistogramWindow * m_win
Ui_HistogramDialog * m_gui
Associated widgets.
Detailed Description
Encapsulating dialog for ccHistogramWindow.
Definition at line 249 of file ecvHistogramWindow.h.
Constructor & Destructor Documentation
ccHistogramWindowDlg()
ccHistogramWindowDlg::ccHistogramWindowDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 842 of file ecvHistogramWindow.cpp.
References m_gui, m_win, onExportToCSV(), and onExportToImage().
~ccHistogramWindowDlg()
ccHistogramWindowDlg::~ccHistogramWindowDlg () virtual
Destructor.
Definition at line 861 of file ecvHistogramWindow.cpp.
References m_gui.
Member Function Documentation
exportToCSV()
bool ccHistogramWindowDlg::exportToCSV (QString filename) const
Exports histogram to a CSV file.
Definition at line 866 of file ecvHistogramWindow.cpp.
References QtCompat::endl(), filename, ccHistogramWindow::histoValues(), m_win, ccHistogramWindow::maxVal(), ccHistogramWindow::minVal(), CVLog::Print(), s_csvSep(), and CVLog::Warning().
Referenced by onExportToCSV().
onExportToCSV()
void ccHistogramWindowDlg::onExportToCSV () protected
When the export to CSV file button is pressed.
Definition at line 915 of file ecvHistogramWindow.cpp.
References ecvPS::CurrentPath(), ecvFileUtils::defaultDocPath(), exportToCSV(), filename, m_win, and ecvPS::SaveFile().
Referenced by ccHistogramWindowDlg().
onExportToImage()
void ccHistogramWindowDlg::onExportToImage () protected
When the export to Image file button is pressed.
Definition at line 946 of file ecvHistogramWindow.cpp.
References ecvPS::CurrentPath(), ecvFileUtils::defaultDocPath(), CVLog::Error(), ImageFileFilter::GetSaveFilename(), image, m_win, CVLog::Print(), and ecvPS::SaveFile().
Referenced by ccHistogramWindowDlg().
window()
ccHistogramWindow* ccHistogramWindowDlg::window () inline
Returns encapsulated ccHistogramWindow.
Definition at line 259 of file ecvHistogramWindow.h.
References m_win.
Referenced by ccEntityAction::computeStatParams(), ccComparisonDlg::showHisto(), and MainWindow::spawnHistogramDialog().
Member Data Documentation
m_gui
Ui_HistogramDialog* ccHistogramWindowDlg::m_gui protected
Associated widgets.
Definition at line 276 of file ecvHistogramWindow.h.
Referenced by ccHistogramWindowDlg(), and ~ccHistogramWindowDlg().
m_win
ccHistogramWindow* ccHistogramWindowDlg::m_win protected
Definition at line 273 of file ecvHistogramWindow.h.
Referenced by ccHistogramWindowDlg(), exportToCSV(), onExportToCSV(), onExportToImage(), and window().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvHistogramWindow.h
/root/ACloudViewer/app/ecvHistogramWindow.cpp