ACloudViewer: cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP Class Reference
cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP Class Reference
#include <TransformationEstimation.h>
Public Member Functions
~TransformationEstimationForDopplerICP () override
TransformationEstimationForDopplerICP (const double period=0.1, const double lambda_doppler=0.01, const bool reject_dynamic_outliers=false, const double doppler_outlier_threshold=2.0, const std::size_t outlier_rejection_min_iteration=2, const std::size_t geometric_robust_loss_min_iteration=0, const std::size_t doppler_robust_loss_min_iteration=2, const RobustKernel &geometric_kernel=RobustKernel(RobustKernelMethod::L2Loss, 1.0, 1.0), const RobustKernel &doppler_kernel=RobustKernel(RobustKernelMethod::L2Loss, 1.0, 1.0), const core::Tensor &transform_vehicle_to_sensor=core::Tensor::Eye(4, core::Float64, core::Device("CPU:0")))
Constructor.
TransformationEstimationType GetTransformationEstimationType () const override
double ComputeRMSE (const geometry::PointCloud &source, const geometry::PointCloud &target, const core::Tensor &correspondences) const override
Computes RMSE (double) for DopplerICP method, between two pointclouds, given correspondences.
core::Tensor ComputeTransformation (const geometry::PointCloud &source, const geometry::PointCloud &target, const core::Tensor &correspondences, const core::Tensor &current_transform=core::Tensor::Eye(4, core::Float64, core::Device("CPU:0")), const std::size_t iteration=0) const override
Estimates the transformation matrix for DopplerICP method, a tensor of shape {4, 4}, and dtype Float64 on CPU device.
Public Member Functions inherited from cloudViewer::t::pipelines::registration::TransformationEstimation
TransformationEstimation ()
Default Constructor.
virtual ~TransformationEstimation ()
Public Attributes
double period_ {0.1}
Time period (in seconds) between the source and the target point clouds.
double lambda_doppler_ {0.01}
Factor that weighs the Doppler residual term in DICP objective.
bool reject_dynamic_outliers_ {false}
Whether or not to prune dynamic point outlier correspondences.
double doppler_outlier_threshold_ {2.0}
std::size_t outlier_rejection_min_iteration_ {2}
Number of iterations of ICP after which outlier rejection is enabled.
std::size_t geometric_robust_loss_min_iteration_ {0}
Number of iterations of ICP after which robust loss kicks in.
std::size_t doppler_robust_loss_min_iteration_ {2}
RobustKernel geometric_kernel_
RobustKernel for outlier rejection.
RobustKernel doppler_kernel_
core::Tensor transform_vehicle_to_sensor_
Detailed Description
This is the implementation of the following paper: B. Hexsel, H. Vhavle, Y. Chen, DICP: Doppler Iterative Closest Point Algorithm, RSS 2022.
Class to estimate a transformation matrix tensor of shape {4, 4}, dtype Float64, on CPU device for DopplerICP method.
Definition at line 309 of file TransformationEstimation.h.
Constructor & Destructor Documentation
~TransformationEstimationForDopplerICP()
cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::~TransformationEstimationForDopplerICP () inline override
Definition at line 311 of file TransformationEstimation.h.
TransformationEstimationForDopplerICP()
cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::TransformationEstimationForDopplerICP (const double period = 0.1, const double lambda_doppler = 0.01, const bool reject_dynamic_outliers = false, const double doppler_outlier_threshold = 2.0, const std::size_t outlier_rejection_min_iteration = 2, const std::size_t geometric_robust_loss_min_iteration = 0, const std::size_t doppler_robust_loss_min_iteration = 2, const RobustKernel & geometric_kernel = RobustKernel(RobustKernelMethod::L2Loss, 1.0, 1.0), const RobustKernel & doppler_kernel = RobustKernel(RobustKernelMethod::L2Loss, 1.0, 1.0), const core::Tensor & transform_vehicle_to_sensor = core::Tensor::Eye(4, core::Float64, core::Device("CPU:0"))) inline explicit
Constructor.
Parameters
period Time period (in seconds) between the source and the target point clouds. Default value: 0.1.
lambda_doppler λ ∈ [0, 1] in the overall energy (1−λ)EG + λED. Refer the documentation of DopplerICP for more information.
reject_dynamic_outliers Whether or not to reject dynamic point outlier correspondences.
doppler_outlier_threshold Correspondences with Doppler error greater than this threshold are rejected from optimization.
outlier_rejection_min_iteration Number of iterations of ICP after which outlier rejection is enabled.
geometric_robust_loss_min_iteration Number of iterations of ICP after which robust loss for geometric term kicks in.
doppler_robust_loss_min_iteration Number of iterations of ICP after which robust loss for Doppler term kicks in.
geometric_kernel (optional) Any of the implemented statistical robust kernel for outlier rejection for the geometric term.
doppler_kernel (optional) Any of the implemented statistical robust kernel for outlier rejection for the Doppler term.
transform_vehicle_to_sensor The 4x4 extrinsic transformation matrix between the vehicle and the sensor frames. Defaults to identity transform.
Definition at line 336 of file TransformationEstimation.h.
References AssertTensorShape, lambda_doppler_, and LogError.
Member Function Documentation
ComputeRMSE()
double cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::ComputeRMSE (const geometry::PointCloud & source, const geometry::PointCloud & target, const core::Tensor & correspondences) const override virtual
Computes RMSE (double) for DopplerICP method, between two pointclouds, given correspondences.
Parameters
source Source pointcloud. (Float32 or Float64 type).
target Target pointcloud. (Float32 or Float64 type). It must contain normals, directions, and Doppler of the same shape and dtype as the positions.
correspondences Tensor of type Int64 containing indices of corresponding target points, where the value is the target index and the index of the value itself is the source index. It contains -1 as value at index with no correspondence.
Implements cloudViewer::t::pipelines::registration::TransformationEstimation.
Definition at line 307 of file TransformationEstimation.cpp.
References AssertTensorDevice, AssertTensorDtype, cloudViewer::t::pipelines::registration::AssertValidCorrespondences(), cloudViewer::core::Float64, cloudViewer::t::geometry::PointCloud::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::PointCloud::GetPointNormals(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), cloudViewer::t::geometry::PointCloud::HasPointPositions(), cloudViewer::core::Tensor::IndexGet(), LogError, cloudViewer::core::Tensor::Mul_(), cloudViewer::core::Tensor::Ne(), cloudViewer::core::Tensor::Reshape(), cloudViewer::core::Tensor::Sum(), and cloudViewer::t::geometry::kernel::image::To().
ComputeTransformation()
core::Tensor cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::ComputeTransformation (const geometry::PointCloud & source, const geometry::PointCloud & target, const core::Tensor & correspondences, const core::Tensor & current_transform = core::Tensor::Eye(4, core::Float64, core::Device("CPU:0")), const std::size_t iteration = 0) const override virtual
Estimates the transformation matrix for DopplerICP method, a tensor of shape {4, 4}, and dtype Float64 on CPU device.
Parameters
source Source pointcloud. (Float32 or Float64 type).
target Target pointcloud. (Float32 or Float64 type). It must contain normals, directions, and Doppler of the same shape and dtype as the positions.
correspondences Tensor of type Int64 containing indices of corresponding target points, where the value is the target index and the index of the value itself is the source index. It contains -1 as value at index with no correspondence.
current_transform The current pose estimate of ICP.
iteration The current iteration number of the ICP algorithm.
Returns
transformation between source to target, a tensor of shape {4, 4}, type Float64 on CPU device.
Implements cloudViewer::t::pipelines::registration::TransformationEstimation.
Definition at line 342 of file TransformationEstimation.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, cloudViewer::t::pipelines::registration::AssertValidCorrespondences(), cloudViewer::t::pipelines::kernel::ComputePoseDopplerICP(), cloudViewer::t::geometry::PointCloud::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointNormals(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointAttr(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), cloudViewer::t::geometry::PointCloud::HasPointPositions(), LogError, and cloudViewer::t::pipelines::kernel::PoseToTransformation().
GetTransformationEstimationType()
TransformationEstimationType cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::GetTransformationEstimationType () const inline override virtual
Implements cloudViewer::t::pipelines::registration::TransformationEstimation.
Definition at line 372 of file TransformationEstimation.h.
Member Data Documentation
doppler_kernel_
RobustKernel cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::doppler_kernel_
Initial value:
=
            RobustKernel(RobustKernelMethod::L2Loss, 1.0, 1.0)
Definition at line 434 of file TransformationEstimation.h.
doppler_outlier_threshold_
double cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::doppler_outlier_threshold_ {2.0}
Correspondences with Doppler error greater than this threshold are rejected from optimization.
Definition at line 425 of file TransformationEstimation.h.
doppler_robust_loss_min_iteration_
std::size_t cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::doppler_robust_loss_min_iteration_ {2}
Definition at line 430 of file TransformationEstimation.h.
geometric_kernel_
RobustKernel cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::geometric_kernel_
Initial value:
=
            RobustKernel(RobustKernelMethod::L2Loss, 1.0, 1.0)
RobustKernel for outlier rejection.
Definition at line 432 of file TransformationEstimation.h.
geometric_robust_loss_min_iteration_
std::size_t cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::geometric_robust_loss_min_iteration_ {0}
Number of iterations of ICP after which robust loss kicks in.
Definition at line 429 of file TransformationEstimation.h.
lambda_doppler_
double cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::lambda_doppler_ {0.01}
Factor that weighs the Doppler residual term in DICP objective.
Definition at line 420 of file TransformationEstimation.h.
Referenced by TransformationEstimationForDopplerICP().
outlier_rejection_min_iteration_
std::size_t cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::outlier_rejection_min_iteration_ {2}
Number of iterations of ICP after which outlier rejection is enabled.
Definition at line 427 of file TransformationEstimation.h.
period_
double cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::period_ {0.1}
Time period (in seconds) between the source and the target point clouds.
Definition at line 418 of file TransformationEstimation.h.
Referenced by cloudViewer::t::pipelines::registration::BenchmarkDopplerICP().
reject_dynamic_outliers_
bool cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::reject_dynamic_outliers_ {false}
Whether or not to prune dynamic point outlier correspondences.
Definition at line 422 of file TransformationEstimation.h.
transform_vehicle_to_sensor_
core::Tensor cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::transform_vehicle_to_sensor_
Initial value:
=
            core::Tensor::Eye(4, core::Float64, core::Device("CPU:0"))
The 4x4 extrinsic transformation matrix between the vehicle and the sensor frames.
Definition at line 438 of file TransformationEstimation.h.
Referenced by cloudViewer::t::pipelines::registration::BenchmarkDopplerICP().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/t/pipelines/registration/TransformationEstimation.h
/root/ACloudViewer/libs/cloudViewer/t/pipelines/registration/TransformationEstimation.cpp