ACloudViewer: cloudViewer::visualization::rendering::FilamentRenderer Class Reference
cloudViewer::visualization::rendering::FilamentRenderer Class Reference
#include <FilamentRenderer.h>
Public Member Functions
FilamentRenderer (filament::Engine &engine, void *native_drawable, FilamentResourceManager &resource_mgr)
FilamentRenderer (filament::Engine &engine, int width, int height, FilamentResourceManager &resource_mgr)
~FilamentRenderer () override
SceneHandle CreateScene () override
Scene * GetScene (const SceneHandle &id) const override
void DestroyScene (const SceneHandle &id) override
virtual void SetClearColor (const Eigen::Vector4f &color) override
void UpdateSwapChain () override
void UpdateBitmapSwapChain (int width, int height) override
void BeginFrame () override
void Draw () override
void RequestReadPixels (int width, int height, std::function< void(std::shared_ptr< core::Tensor >)> callback) override
void EndFrame () override
void SetOnAfterDraw (std::function< void()> callback) override
MaterialHandle AddMaterial (const ResourceLoadRequest &request) override
MaterialInstanceHandle AddMaterialInstance (const MaterialHandle &material) override
MaterialModifier & ModifyMaterial (const MaterialHandle &id) override
MaterialModifier & ModifyMaterial (const MaterialInstanceHandle &id) override
void RemoveMaterialInstance (const MaterialInstanceHandle &id) override
TextureHandle AddTexture (const ResourceLoadRequest &request, bool srgb=false) override
TextureHandle AddTexture (const std::shared_ptr< geometry::Image > image, bool srgb=false) override
TextureHandle AddTexture (const t::geometry::Image &image, bool srgb=false) override
bool UpdateTexture (TextureHandle texture, const std::shared_ptr< geometry::Image > image, bool srgb) override
bool UpdateTexture (TextureHandle texture, const t::geometry::Image &image, bool srgb) override
void RemoveTexture (const TextureHandle &id) override
IndirectLightHandle AddIndirectLight (const ResourceLoadRequest &request) override
void RemoveIndirectLight (const IndirectLightHandle &id) override
SkyboxHandle AddSkybox (const ResourceLoadRequest &request) override
void RemoveSkybox (const SkyboxHandle &id) override
std::shared_ptr< visualization::rendering::RenderToBuffer > CreateBufferRenderer () override
void ConvertToGuiScene (const SceneHandle &id)
FilamentScene * GetGuiScene () const
filament::Renderer * GetNative ()
Public Member Functions inherited from cloudViewer::visualization::rendering::Renderer
virtual ~Renderer ()=default
void RenderToImage (View *view, Scene *scene, std::function< void(std::shared_ptr< geometry::Image >)> cb)
void RenderToDepthImage (View *view, Scene *scene, std::function< void(std::shared_ptr< geometry::Image >)> cb, bool z_in_view_space=false)
Detailed Description
Definition at line 36 of file FilamentRenderer.h.
Constructor & Destructor Documentation
FilamentRenderer() [1/2]
cloudViewer::visualization::rendering::FilamentRenderer::FilamentRenderer (filament::Engine & engine, void * native_drawable, FilamentResourceManager & resource_mgr)
Definition at line 51 of file FilamentRenderer.cpp.
FilamentRenderer() [2/2]
cloudViewer::visualization::rendering::FilamentRenderer::FilamentRenderer (filament::Engine & engine, int width, int height, FilamentResourceManager & resource_mgr) explicit
Definition at line 62 of file FilamentRenderer.cpp.
References height, and width.
~FilamentRenderer()
cloudViewer::visualization::rendering::FilamentRenderer::~FilamentRenderer () override
Definition at line 74 of file FilamentRenderer.cpp.
Member Function Documentation
AddIndirectLight()
IndirectLightHandle cloudViewer::visualization::rendering::FilamentRenderer::AddIndirectLight (const ResourceLoadRequest & request) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 298 of file FilamentRenderer.cpp.
References cloudViewer::visualization::rendering::ResourceLoadRequest::error_callback_, and cloudViewer::visualization::rendering::ResourceLoadRequest::path_.
AddMaterial()
MaterialHandle cloudViewer::visualization::rendering::FilamentRenderer::AddMaterial (const ResourceLoadRequest & request) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 220 of file FilamentRenderer.cpp.
AddMaterialInstance()
MaterialInstanceHandle cloudViewer::visualization::rendering::FilamentRenderer::AddMaterialInstance (const MaterialHandle & material) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 225 of file FilamentRenderer.cpp.
AddSkybox()
SkyboxHandle cloudViewer::visualization::rendering::FilamentRenderer::AddSkybox (const ResourceLoadRequest & request) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 313 of file FilamentRenderer.cpp.
References cloudViewer::visualization::rendering::ResourceLoadRequest::error_callback_, and cloudViewer::visualization::rendering::ResourceLoadRequest::path_.
AddTexture() [1/3]
TextureHandle cloudViewer::visualization::rendering::FilamentRenderer::AddTexture (const ResourceLoadRequest & request, bool srgb = false) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 270 of file FilamentRenderer.cpp.
References cloudViewer::visualization::rendering::ResourceLoadRequest::error_callback_, and cloudViewer::visualization::rendering::ResourceLoadRequest::path_.
AddTexture() [2/3]
TextureHandle cloudViewer::visualization::rendering::FilamentRenderer::AddTexture (const std::shared_ptr< geometry::Image > image, bool srgb = false) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 347 of file FilamentRenderer.cpp.
References image.
AddTexture() [3/3]
TextureHandle cloudViewer::visualization::rendering::FilamentRenderer::AddTexture (const t::geometry::Image & image, bool srgb = false) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 352 of file FilamentRenderer.cpp.
References image.
BeginFrame()
void cloudViewer::visualization::rendering::FilamentRenderer::BeginFrame () override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 129 of file FilamentRenderer.cpp.
ConvertToGuiScene()
void cloudViewer::visualization::rendering::FilamentRenderer::ConvertToGuiScene (const SceneHandle & id)
Definition at line 333 of file FilamentRenderer.cpp.
References LogWarning.
Referenced by cloudViewer::visualization::gui::ImguiFilamentBridge::ImguiFilamentBridge().
CreateBufferRenderer()
std::shared_ptr< RenderToBuffer > cloudViewer::visualization::rendering::FilamentRenderer::CreateBufferRenderer () override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 327 of file FilamentRenderer.cpp.
CreateScene()
SceneHandle cloudViewer::visualization::rendering::FilamentRenderer::CreateScene () override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 81 of file FilamentRenderer.cpp.
References cloudViewer::visualization::rendering::REHandle< EntityType::Scene >::Next().
Referenced by cloudViewer::visualization::gui::ImguiFilamentBridge::ImguiFilamentBridge().
DestroyScene()
void cloudViewer::visualization::rendering::FilamentRenderer::DestroyScene (const SceneHandle & id) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 98 of file FilamentRenderer.cpp.
Draw()
void cloudViewer::visualization::rendering::FilamentRenderer::Draw () override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 150 of file FilamentRenderer.cpp.
EndFrame()
void cloudViewer::visualization::rendering::FilamentRenderer::EndFrame () override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 170 of file FilamentRenderer.cpp.
GetGuiScene()
FilamentScene* cloudViewer::visualization::rendering::FilamentRenderer::GetGuiScene () const inline
Definition at line 100 of file FilamentRenderer.h.
Referenced by cloudViewer::visualization::gui::ImguiFilamentBridge::ImguiFilamentBridge().
GetNative()
filament::Renderer* cloudViewer::visualization::rendering::FilamentRenderer::GetNative () inline
Definition at line 102 of file FilamentRenderer.h.
GetScene()
Scene * cloudViewer::visualization::rendering::FilamentRenderer::GetScene (const SceneHandle & id) const override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 89 of file FilamentRenderer.cpp.
ModifyMaterial() [1/2]
MaterialModifier & cloudViewer::visualization::rendering::FilamentRenderer::ModifyMaterial (const MaterialHandle & id) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 230 of file FilamentRenderer.cpp.
References LogWarning.
ModifyMaterial() [2/2]
MaterialModifier & cloudViewer::visualization::rendering::FilamentRenderer::ModifyMaterial (const MaterialInstanceHandle & id) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 248 of file FilamentRenderer.cpp.
References LogWarning.
RemoveIndirectLight()
void cloudViewer::visualization::rendering::FilamentRenderer::RemoveIndirectLight (const IndirectLightHandle & id) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 309 of file FilamentRenderer.cpp.
RemoveMaterialInstance()
void cloudViewer::visualization::rendering::FilamentRenderer::RemoveMaterialInstance (const MaterialInstanceHandle & id) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 265 of file FilamentRenderer.cpp.
RemoveSkybox()
void cloudViewer::visualization::rendering::FilamentRenderer::RemoveSkybox (const SkyboxHandle & id) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 323 of file FilamentRenderer.cpp.
RemoveTexture()
void cloudViewer::visualization::rendering::FilamentRenderer::RemoveTexture (const TextureHandle & id) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 294 of file FilamentRenderer.cpp.
RequestReadPixels()
void cloudViewer::visualization::rendering::FilamentRenderer::RequestReadPixels (int width, int height, std::function< void(std::shared_ptr< core::Tensor >)> callback) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 199 of file FilamentRenderer.cpp.
References cloudViewer::core::Dtype::ByteSize(), callback, height, image, cloudViewer::visualization::rendering::ReadPixelsCallback(), cloudViewer::core::UInt8, LasNames::UserData, and width.
SetClearColor()
void cloudViewer::visualization::rendering::FilamentRenderer::SetClearColor (const Eigen::Vector4f & color) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 102 of file FilamentRenderer.cpp.
References color.
SetOnAfterDraw()
void cloudViewer::visualization::rendering::FilamentRenderer::SetOnAfterDraw (std::function< void()> callback) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 113 of file FilamentRenderer.cpp.
References callback.
UpdateBitmapSwapChain()
void cloudViewer::visualization::rendering::FilamentRenderer::UpdateBitmapSwapChain (int width, int height) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 123 of file FilamentRenderer.cpp.
References height, and width.
Referenced by cloudViewer::visualization::gui::BitmapWindowSystem::ResizeRenderer().
UpdateSwapChain()
void cloudViewer::visualization::rendering::FilamentRenderer::UpdateSwapChain () override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 117 of file FilamentRenderer.cpp.
Referenced by cloudViewer::visualization::gui::GLFWWindowSystem::ResizeRenderer().
UpdateTexture() [1/2]
bool cloudViewer::visualization::rendering::FilamentRenderer::UpdateTexture (TextureHandle texture, const std::shared_ptr< geometry::Image > image, bool srgb) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 281 of file FilamentRenderer.cpp.
References image.
UpdateTexture() [2/2]
bool cloudViewer::visualization::rendering::FilamentRenderer::UpdateTexture (TextureHandle texture, const t::geometry::Image & image, bool srgb) override virtual
Implements cloudViewer::visualization::rendering::Renderer.
Definition at line 288 of file FilamentRenderer.cpp.
References image.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentRenderer.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentRenderer.cpp