ACloudViewer: colmap::mvs::CudaArrayLayeredTexture< T > Class Template Reference
colmap::mvs::CudaArrayLayeredTexture< T > Class Template Reference
#include <cuda_texture.h>
Public Member Functions
cudaTextureObject_t GetObj () const
size_t GetWidth () const
size_t GetHeight () const
size_t GetDepth () const
CudaArrayLayeredTexture (const cudaTextureDesc &texture_desc, const size_t width, const size_t height, const size_t depth)
~CudaArrayLayeredTexture ()
Static Public Member Functions
static std::unique_ptr< CudaArrayLayeredTexture< T > > FromGpuMat (const cudaTextureDesc &texture_desc, const GpuMat< T > &mat)
static std::unique_ptr< CudaArrayLayeredTexture< T > > FromHostArray (const cudaTextureDesc &texture_desc, const size_t width, const size_t height, const size_t depth, const T *data)
Detailed Description
template<typename T>
class colmap::mvs::CudaArrayLayeredTexture< T >
Definition at line 22 of file cuda_texture.h.
Constructor & Destructor Documentation
CudaArrayLayeredTexture()
template<typename T > colmap::mvs::CudaArrayLayeredTexture< T >::CudaArrayLayeredTexture (const cudaTextureDesc & texture_desc, const size_t width, const size_t height, const size_t depth)
Definition at line 108 of file cuda_texture.h.
~CudaArrayLayeredTexture()
template<typename T > colmap::mvs::CudaArrayLayeredTexture< T >::~CudaArrayLayeredTexture
Definition at line 134 of file cuda_texture.h.
References CUDA_SAFE_CALL.
Member Function Documentation
FromGpuMat()
template<typename T > std::unique_ptr< CudaArrayLayeredTexture< T > > colmap::mvs::CudaArrayLayeredTexture< T >::FromGpuMat (const cudaTextureDesc & texture_desc, const GpuMat< T > & mat) static
Definition at line 67 of file cuda_texture.h.
References CUDA_SAFE_CALL, colmap::mvs::GpuMat< T >::GetDepth(), colmap::mvs::GpuMat< T >::GetHeight(), colmap::mvs::GpuMat< T >::GetPitch(), colmap::mvs::GpuMat< T >::GetPtr(), and colmap::mvs::GpuMat< T >::GetWidth().
FromHostArray()
template<typename T > std::unique_ptr< CudaArrayLayeredTexture< T > > colmap::mvs::CudaArrayLayeredTexture< T >::FromHostArray (const cudaTextureDesc & texture_desc, const size_t width, const size_t height, const size_t depth, const T * data) static
Definition at line 87 of file cuda_texture.h.
References CUDA_SAFE_CALL, data, height, and width.
GetDepth()
template<typename T > size_t colmap::mvs::CudaArrayLayeredTexture< T >::GetDepth
Definition at line 155 of file cuda_texture.h.
GetHeight()
template<typename T > size_t colmap::mvs::CudaArrayLayeredTexture< T >::GetHeight
Definition at line 150 of file cuda_texture.h.
GetObj()
template<typename T > cudaTextureObject_t colmap::mvs::CudaArrayLayeredTexture< T >::GetObj
Definition at line 140 of file cuda_texture.h.
GetWidth()
template<typename T > size_t colmap::mvs::CudaArrayLayeredTexture< T >::GetWidth
Definition at line 145 of file cuda_texture.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/mvs/cuda_texture.h