ACloudViewer: cvSelectionPropertiesWidget Class Reference
cvSelectionPropertiesWidget Class Reference
Comprehensive selection properties and management widget.
#include <cvSelectionPropertiesWidget.h>
Classes
struct SavedSelection
Saved selection entry for Selection Editor.
Signals
void highlightColorChanged (double r, double g, double b, int mode)
void highlightOpacityChanged (double opacity, int mode)
void expressionChanged (const QString &expression)
void activateCombinedSelectionsRequested ()
void selectionAdded (const cvSelectionData &selection)
void selectionRemoved (int index)
void allSelectionsRemoved ()
void freezeSelectionRequested ()
void extractSelectionRequested ()
void extractedObjectReady (ccHObject *obj)
void plotOverTimeRequested ()
void invertSelectionRequested ()
void findDataRequested (const QString &dataProducer, const QString &elementType, const QString &attribute, const QString &op, const QString &value)
void algebraOperationRequested (int operation)
void bookmarkRequested (const QString &name)
void annotationRequested (const QString &text)
Public Member Functions
cvSelectionPropertiesWidget (QWidget *parent=nullptr)
~cvSelectionPropertiesWidget () override
void setHighlighter (cvSelectionHighlighter *highlighter)
void setSelectionManager (cvViewSelectionManager *manager)
void syncUIWithHighlighter ()
bool updateSelection (const cvSelectionData &selectionData, vtkPolyData *polyData=nullptr)
void clearSelection ()
const cvSelectionData & selectionData () const
cvViewSelectionManager * selectionManager () const
void setDataProducerName (const QString &name)
Set the data producer name (source of selection)
void refreshDataProducers ()
Refresh the data producer combo box Call this when data sources change (e.g., after loading new data)
Public Member Functions inherited from cvSelectionBase
cvSelectionBase ()
virtual ~cvSelectionBase ()=default
virtual void setVisualizer (ecvGenericVisualizer3D *viewer)
Set the visualizer instance.
ecvGenericVisualizer3D * getVisualizer () const
Get the visualizer instance.
Protected Member Functions
bool eventFilter (QObject *obj, QEvent *event) override
void resizeEvent (QResizeEvent *event) override
Protected Member Functions inherited from cvSelectionBase
PclUtils::PCLVis * getPCLVis () const
Get PCLVis instance (for VTK-specific operations)
bool hasValidPCLVis () const
Check if visualizer is valid and is PCLVis.
vtkDataSet * getDataFromActor (vtkActor *actor)
Get data object from a specific actor (ParaView-style)
QList< vtkActor * > getDataActors () const
Get all visible data actors from visualizer.
std::vector< vtkPolyData * > getAllPolyDataFromVisualizer ()
Get all polyData from the visualizer.
virtual vtkPolyData * getPolyDataForSelection (const cvSelectionData *selectionData=nullptr)
Get polyData using ParaView-style priority (centralized method)
Additional Inherited Members
Protected Attributes inherited from cvSelectionBase
ecvGenericVisualizer3D * m_viewer
Visualizer instance (abstract interface)
Detailed Description
Comprehensive selection properties and management widget.
Based on ParaView's Find Data panel with:
pqFindDataSelectionDisplayFrame (Selection Display)
pqSelectionEditor (Selection Editor)
pqFindDataCurrentSelectionFrame (Selected Data spreadsheet)
Layout:
Selected Data header with action buttons
Selection Display (collapsible) - labels, colors, label properties
Selection Editor (collapsible) - data producer, expression, saved selections
Selected Data table (spreadsheet view with attributes)
Definition at line 71 of file cvSelectionPropertiesWidget.h.
Constructor & Destructor Documentation
cvSelectionPropertiesWidget()
cvSelectionPropertiesWidget::cvSelectionPropertiesWidget (QWidget * parent = nullptr) explicit
Definition at line 125 of file cvSelectionPropertiesWidget.cpp.
References CVLog::PrintVerbose().
~cvSelectionPropertiesWidget()
cvSelectionPropertiesWidget::~cvSelectionPropertiesWidget () override
Definition at line 211 of file cvSelectionPropertiesWidget.cpp.
Member Function Documentation
activateCombinedSelectionsRequested
void cvSelectionPropertiesWidget::activateCombinedSelectionsRequested () signal
algebraOperationRequested
void cvSelectionPropertiesWidget::algebraOperationRequested (int operation) signal
allSelectionsRemoved
void cvSelectionPropertiesWidget::allSelectionsRemoved () signal
annotationRequested
void cvSelectionPropertiesWidget::annotationRequested (const QString & text) signal
bookmarkRequested
void cvSelectionPropertiesWidget::bookmarkRequested (const QString & name) signal
clearSelection()
void cvSelectionPropertiesWidget::clearSelection ()
Definition at line 1717 of file cvSelectionPropertiesWidget.cpp.
References cvSelectionData::clear(), cvSelectionHighlighter::isCellLabelVisible(), cvSelectionHighlighter::isPointLabelVisible(), cvSelectionHighlighter::setCellLabelArray(), and cvSelectionHighlighter::setPointLabelArray().
Referenced by cvFindDataDockWidget::clearSelection(), and updateSelection().
eventFilter()
bool cvSelectionPropertiesWidget::eventFilter (QObject * obj, QEvent * event) override protected
Definition at line 240 of file cvSelectionPropertiesWidget.cpp.
References color, event, cvSelectionHighlighter::getHighlightQColor(), cvSelectionHighlighter::HOVER, cloudViewer::t::geometry::ipp::Resize(), and cvSelectionHighlighter::SELECTED.
expressionChanged
void cvSelectionPropertiesWidget::expressionChanged (const QString & expression) signal
extractedObjectReady
void cvSelectionPropertiesWidget::extractedObjectReady (ccHObject * obj) signal
extractSelectionRequested
void cvSelectionPropertiesWidget::extractSelectionRequested () signal
findDataRequested
void cvSelectionPropertiesWidget::findDataRequested (const QString & dataProducer, const QString & elementType, const QString & attribute, const QString & op, const QString & value) signal
freezeSelectionRequested
void cvSelectionPropertiesWidget::freezeSelectionRequested () signal
highlightColorChanged
void cvSelectionPropertiesWidget::highlightColorChanged (double r, double g, double b, int mode) signal
Referenced by setHighlighter().
highlightOpacityChanged
void cvSelectionPropertiesWidget::highlightOpacityChanged (double opacity, int mode) signal
Referenced by setHighlighter().
invertSelectionRequested
void cvSelectionPropertiesWidget::invertSelectionRequested () signal
plotOverTimeRequested
void cvSelectionPropertiesWidget::plotOverTimeRequested () signal
refreshDataProducers()
void cvSelectionPropertiesWidget::refreshDataProducers ()
Refresh the data producer combo box Call this when data sources change (e.g., after loading new data)
Definition at line 5438 of file cvSelectionPropertiesWidget.cpp.
Referenced by cvFindDataDockWidget::refreshDataProducers(), and cvFindDataDockWidget::showEvent().
resizeEvent()
void cvSelectionPropertiesWidget::resizeEvent (QResizeEvent * event) override protected
Definition at line 268 of file cvSelectionPropertiesWidget.cpp.
References event.
selectionAdded
void cvSelectionPropertiesWidget::selectionAdded (const cvSelectionData & selection) signal
selectionData()
const cvSelectionData& cvSelectionPropertiesWidget::selectionData () const inline
Definition at line 98 of file cvSelectionPropertiesWidget.h.
Referenced by updateSelection().
selectionManager()
cvViewSelectionManager* cvSelectionPropertiesWidget::selectionManager () const inline
Definition at line 99 of file cvSelectionPropertiesWidget.h.
selectionRemoved
void cvSelectionPropertiesWidget::selectionRemoved (int index) signal
setDataProducerName()
void cvSelectionPropertiesWidget::setDataProducerName (const QString & name)
Set the data producer name (source of selection)
Definition at line 5423 of file cvSelectionPropertiesWidget.cpp.
References name.
Referenced by updateSelection().
setHighlighter()
void cvSelectionPropertiesWidget::setHighlighter (cvSelectionHighlighter * highlighter)
Definition at line 279 of file cvSelectionPropertiesWidget.cpp.
References cvSelectionHighlighter::colorChanged(), cvSelectionBase::getPCLVis(), highlightColorChanged(), highlightOpacityChanged(), cvSelectionHighlighter::labelPropertiesChanged(), cvSelectionHighlighter::opacityChanged(), cvSelectionHighlighter::setHighlightColor(), cvSelectionHighlighter::setHighlightOpacity(), syncUIWithHighlighter(), and PclUtils::PCLVis::UpdateScreen().
Referenced by cvFindDataDockWidget::configure(), and setSelectionManager().
setSelectionManager()
void cvSelectionPropertiesWidget::setSelectionManager (cvViewSelectionManager * manager)
Definition at line 1483 of file cvSelectionPropertiesWidget.cpp.
References SelectionLabelProperties::cellLabelColor, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelColor, SelectionLabelProperties::cellLabelFontFamily, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelFontFamily, SelectionLabelProperties::cellLabelFontSize, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelFontSize, cvViewSelectionManager::getAnnotations(), cvViewSelectionManager::getHighlighter(), cvSelectionHighlighter::getLabelProperties(), SelectionLabelProperties::lineWidth, cvSelectionLabelPropertiesDialog::LabelProperties::lineWidth, SelectionLabelProperties::opacity, cvSelectionLabelPropertiesDialog::LabelProperties::opacity, SelectionLabelProperties::pointLabelColor, cvSelectionLabelPropertiesDialog::LabelProperties::pointLabelColor, SelectionLabelProperties::pointLabelFontFamily, cvSelectionLabelPropertiesDialog::LabelProperties::pointLabelFontFamily, SelectionLabelProperties::pointLabelFontSize, cvSelectionLabelPropertiesDialog::LabelProperties::pointLabelFontSize, SelectionLabelProperties::pointSize, cvSelectionLabelPropertiesDialog::LabelProperties::pointSize, cvSelectionAnnotationManager::setDefaultLabelProperties(), and setHighlighter().
Referenced by cvFindDataDockWidget::configure().
syncUIWithHighlighter()
void cvSelectionPropertiesWidget::syncUIWithHighlighter ()
Definition at line 563 of file cvSelectionPropertiesWidget.cpp.
References cvSelectionHighlighter::BOUNDARY, cvSelectionHighlighter::getHighlightOpacity(), cvSelectionHighlighter::getHighlightQColor(), cvSelectionHighlighter::HOVER, cvSelectionHighlighter::PRESELECTED, CVLog::PrintVerbose(), and cvSelectionHighlighter::SELECTED.
Referenced by setHighlighter().
updateSelection()
bool cvSelectionPropertiesWidget::updateSelection (const cvSelectionData & selectionData, vtkPolyData * polyData = nullptr)
Definition at line 1541 of file cvSelectionPropertiesWidget.cpp.
References cvSelectionData::CELLS, clearSelection(), cvSelectionData::fieldAssociation(), ccObject::getName(), cvViewSelectionManager::getPolyData(), cvSelectionBase::getPolyDataForSelection(), cvViewSelectionManager::getSourceObject(), cvSelectionData::ids(), cvViewSelectionManager::instance(), cvSelectionData::isEmpty(), cvSelectionData::POINTS, CVLog::PrintVerbose(), selectionData(), setDataProducerName(), and CVLog::Warning().
Referenced by cvFindDataDockWidget::updateSelection().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvSelectionPropertiesWidget.h
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvSelectionPropertiesWidget.cpp