ACloudViewer: ccFastMarchingForNormsDirection Class Reference
ccFastMarchingForNormsDirection Class Reference
Fast Marching algorithm for normals direction resolution.
#include <ecvFastMarchingForNormsDirection.h>
Classes
class DirectionCell
A Fast Marching grid cell for normals direction resolution.
Public Member Functions
ccFastMarchingForNormsDirection ()
Default constructor.
int init (ccGenericPointCloud *cloud, NormsIndexesTableType *theNorms, ccOctree *theOctree, unsigned char gridLevel)
Initializes the grid with a point cloud (and ist corresponding octree)
unsigned updateResolvedTable (ccGenericPointCloud *theCloud, std::vector< unsigned char > &resolved, NormsIndexesTableType *theNorms)
Updates a list of point flags, indicating the points already processed.
int propagate () override
Propagates the front.
Public Member Functions inherited from cloudViewer::FastMarching
FastMarching ()
Default constructor.
virtual ~FastMarching ()
Destructor.
virtual bool setSeedCell (const Tuple3i &pos)
Sets a given cell as "seed".
virtual void cleanLastPropagation ()
virtual float getTime (Tuple3i &pos, bool absoluteCoordinates=false) const
Returns the front arrival time at a given cell.
virtual void setExtendedConnectivity (bool state)
Sets extended connectivity mode.
Static Public Member Functions
static int OrientNormals (ccPointCloud *theCloud, unsigned char octreeLevel, ecvProgressDialog *progressCb=nullptr)
Static entry point (helper)
Protected Member Functions
float computeTCoefApprox (cloudViewer::FastMarching::Cell *currentCell, cloudViewer::FastMarching::Cell *neighbourCell) const override
Computes the front acceleration between two cells.
int step () override
Propagates the front (one step)
void initTrialCells () override
Initializes the TRIAL cells list.
bool instantiateGrid (unsigned size) override
Instantiates grid in memory.
float computePropagationConfidence (DirectionCell *originCell, DirectionCell *destCell) const
Computes relative 'confidence' between two cells (orientations)
void resolveCellOrientation (unsigned index)
Resolves the direction of a given cell (once and for all)
Protected Member Functions inherited from cloudViewer::FastMarching
unsigned pos2index (const Tuple3i &pos) const
virtual int initGridWithOctree (DgmOctree *octree, unsigned char gridLevel)
virtual int initGrid (float step, unsigned dim[3])
Intializes the grid with a given step and dimensions.
virtual int initOther ()
virtual float computeT (unsigned index)
Computes the front arrival time at a given cell.
template<class T >
bool instantiateGridTpl (unsigned size)
Grid instantiation helper.
virtual void addTrialCell (unsigned index)
Add a cell to the TRIAL cells list.
virtual void addActiveCell (unsigned index)
Add a cell to the ACTIVE cells list.
virtual void addIgnoredCell (unsigned index)
Add a cell to the IGNORED cells list.
virtual unsigned getNearestTrialCell ()
Returns the TRIAL cell with the smallest front arrival time.
void resetCells (std::vector< unsigned > &list)
Resets the state of cells in a given list.
Additional Inherited Members
Protected Attributes inherited from cloudViewer::FastMarching
std::vector< unsigned > m_activeCells
ACTIVE cells list.
std::vector< unsigned > m_trialCells
TRIAL cells list.
std::vector< unsigned > m_ignoredCells
IGNORED cells lits.
bool m_initialized
Specifiies whether structure is initialized or not.
unsigned m_dx
Grid size along the X dimension.
unsigned m_dy
Grid size along the Y dimension.
unsigned m_dz
Grid size along the Z dimension.
unsigned m_rowSize
Shift for cell access acceleration (Y dimension)
unsigned m_sliceSize
Shift for cell access acceleration (Z dimension)
unsigned m_indexShift
First index of innerbound grid.
unsigned m_gridSize
Grid size.
Cell ** m_theGrid
Grid used to process Fast Marching.
DgmOctree * m_octree
Associated octree.
unsigned char m_gridLevel
Equivalent octree subdivision level.
float m_cellSize
Octree cell size at equivalent subdivision level.
Tuple3i m_minFillIndexes
Octree min fill indexes at 'm_gridLevel'.
unsigned m_numberOfNeighbours
Current number of neighbours (6 or 26)
int m_neighboursIndexShift [26]
Neighbours coordinates shifts in grid.
float m_neighboursDistance [26]
Neighbours distance weight.
Detailed Description
Fast Marching algorithm for normals direction resolution.
Extends the FastMarching class.
Definition at line 28 of file ecvFastMarchingForNormsDirection.h.
Constructor & Destructor Documentation
ccFastMarchingForNormsDirection()
ccFastMarchingForNormsDirection::ccFastMarchingForNormsDirection ()
Default constructor.
Definition at line 24 of file ecvFastMarchingForNormsDirection.cpp.
Member Function Documentation
computePropagationConfidence()
float ccFastMarchingForNormsDirection::computePropagationConfidence (DirectionCell * originCell, DirectionCell * destCell) const protected
Computes relative 'confidence' between two cells (orientations)
Returns
confidence between 0 and 1
Definition at line 107 of file ecvFastMarchingForNormsDirection.cpp.
References ccFastMarchingForNormsDirection::DirectionCell::C, Vector3Tpl< Type >::dot(), ccFastMarchingForNormsDirection::DirectionCell::N, and Vector3Tpl< Type >::normalize().
Referenced by computeTCoefApprox(), and resolveCellOrientation().
computeTCoefApprox()
float ccFastMarchingForNormsDirection::computeTCoefApprox (cloudViewer::FastMarching::Cell * currentCell, cloudViewer::FastMarching::Cell * neighbourCell) const override protected virtual
Computes the front acceleration between two cells.
Parameters
currentCell the "central" cell
neighbourCell the other cell
Returns
the front acceleration
Implements cloudViewer::FastMarching.
Definition at line 239 of file ecvFastMarchingForNormsDirection.cpp.
References computePropagationConfidence(), and ccFastMarchingForNormsDirection::DirectionCell::signConfidence.
Referenced by initTrialCells().
init()
int ccFastMarchingForNormsDirection::init (ccGenericPointCloud * cloud, NormsIndexesTableType * theNorms, ccOctree * theOctree, unsigned char gridLevel)
Initializes the grid with a point cloud (and ist corresponding octree)
The points should be associated to an (active) scalar field. The Fast Marching grid will have the same dimensions as the input octree considered at a given level of subdivision.
Parameters
cloud the point cloud
theNorms the normals array
theOctree the associated octree
gridLevel the level of subdivision
Returns
a negative value if something went wrong
Definition at line 62 of file ecvFastMarchingForNormsDirection.cpp.
References cloudViewer::DgmOctree::associatedCloud(), ccFastMarchingForNormsDirection::DirectionCell::C, ccFastMarchingForNormsDirection::DirectionCell::cellCode, ComputeRobustAverageNorm(), cloudViewer::DgmOctree::getCellCodes(), cloudViewer::DgmOctree::getCellPos(), cloudViewer::Neighbourhood::getGravityCenter(), cloudViewer::DgmOctree::getPointsInCell(), cloudViewer::FastMarching::initGridWithOctree(), cloudViewer::FastMarching::m_initialized, cloudViewer::FastMarching::m_theGrid, ccFastMarchingForNormsDirection::DirectionCell::N, cloudViewer::FastMarching::pos2index(), and result.
Referenced by OrientNormals().
initTrialCells()
void ccFastMarchingForNormsDirection::initTrialCells () override protected virtual
Initializes the TRIAL cells list.
See the Fast Marching algorithm theory for more information
Reimplemented from cloudViewer::FastMarching.
Definition at line 306 of file ecvFastMarchingForNormsDirection.cpp.
References cloudViewer::FastMarching::addTrialCell(), computeTCoefApprox(), cloudViewer::FastMarching::Cell::FAR_CELL, cloudViewer::FastMarching::m_activeCells, cloudViewer::FastMarching::m_neighboursDistance, cloudViewer::FastMarching::m_neighboursIndexShift, cloudViewer::FastMarching::m_numberOfNeighbours, cloudViewer::FastMarching::m_theGrid, ccFastMarchingForNormsDirection::DirectionCell::signConfidence, cloudViewer::FastMarching::Cell::state, and cloudViewer::FastMarching::Cell::T.
Referenced by propagate().
instantiateGrid()
bool ccFastMarchingForNormsDirection::instantiateGrid (unsigned size) inline override protected virtual
Instantiates grid in memory.
Grid is also filled with zeros.
Parameters
size grid size
Returns
success
Implements cloudViewer::FastMarching.
Definition at line 103 of file ecvFastMarchingForNormsDirection.h.
References size.
OrientNormals()
int ccFastMarchingForNormsDirection::OrientNormals (ccPointCloud * theCloud, unsigned char octreeLevel, ecvProgressDialog * progressCb = nullptr) static
Static entry point (helper)
Definition at line 339 of file ecvFastMarchingForNormsDirection.cpp.
References ccPointCloud::addScalarField(), cloudViewer::FastMarching::cleanLastPropagation(), ccScalarField::computeMinAndMax(), ccGenericPointCloud::computeOctree(), count, ccPointCloud::deleteScalarField(), cloudViewer::PointCloudTpl< T >::enableScalarField(), CVLog::Error(), ccPointCloud::getCurrentDisplayedScalarField(), ccPointCloud::getCurrentDisplayedScalarFieldIndex(), ccObject::getName(), ccGenericPointCloud::getOctree(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::DgmOctree::getTheCellPosWhichIncludesThePoint(), init(), name, ccPointCloud::normals(), octree, octreeLevel, propagate(), result, ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentScalarField(), ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), cloudViewer::FastMarching::setSeedCell(), ccDrawableObject::sfShown(), ccDrawableObject::showNormals(), ccDrawableObject::showSF(), cloudViewer::PointCloudTpl< T >::size(), ecvProgressDialog::start(), ecvProgressDialog::stop(), cloudViewer::GenericProgressCallback::textCanBeEdited(), ecvProgressDialog::update(), updateResolvedTable(), CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccPointCloud::orientNormalsWithFM().
propagate()
int ccFastMarchingForNormsDirection::propagate () override virtual
Propagates the front.
The seeds should have already been initialized
Returns
propagation result (errors = negative values)
Implements cloudViewer::FastMarching.
Definition at line 250 of file ecvFastMarchingForNormsDirection.cpp.
References initTrialCells(), result, and step().
Referenced by OrientNormals().
resolveCellOrientation()
void ccFastMarchingForNormsDirection::resolveCellOrientation (unsigned index) protected
Resolves the direction of a given cell (once and for all)
Definition at line 125 of file ecvFastMarchingForNormsDirection.cpp.
References cloudViewer::FastMarching::Cell::ACTIVE_CELL, computePropagationConfidence(), Vector3Tpl< Type >::dot(), cloudViewer::FastMarching::m_neighboursIndexShift, cloudViewer::FastMarching::m_numberOfNeighbours, cloudViewer::FastMarching::m_theGrid, ccFastMarchingForNormsDirection::DirectionCell::N, ccFastMarchingForNormsDirection::DirectionCell::signConfidence, and cloudViewer::FastMarching::Cell::state.
Referenced by step().
step()
int ccFastMarchingForNormsDirection::step () override protected virtual
Propagates the front (one step)
Returns
a negative value if a problem occurred
Implements cloudViewer::FastMarching.
Definition at line 184 of file ecvFastMarchingForNormsDirection.cpp.
References cloudViewer::FastMarching::Cell::ACTIVE_CELL, cloudViewer::FastMarching::addActiveCell(), cloudViewer::FastMarching::addIgnoredCell(), cloudViewer::FastMarching::addTrialCell(), cloudViewer::FastMarching::computeT(), cloudViewer::FastMarching::Cell::FAR_CELL, cloudViewer::FastMarching::getNearestTrialCell(), cloudViewer::FastMarching::m_activeCells, cloudViewer::FastMarching::m_initialized, cloudViewer::FastMarching::m_neighboursIndexShift, cloudViewer::FastMarching::m_numberOfNeighbours, cloudViewer::FastMarching::m_theGrid, resolveCellOrientation(), scalar, cloudViewer::FastMarching::Cell::state, cloudViewer::FastMarching::Cell::T, cloudViewer::FastMarching::Cell::T_INF(), and cloudViewer::FastMarching::Cell::TRIAL_CELL.
Referenced by propagate().
updateResolvedTable()
unsigned ccFastMarchingForNormsDirection::updateResolvedTable (ccGenericPointCloud * theCloud, std::vector< unsigned char > & resolved, NormsIndexesTableType * theNorms)
Updates a list of point flags, indicating the points already processed.
Returns
the number of resolved points
Definition at line 262 of file ecvFastMarchingForNormsDirection.cpp.
References cloudViewer::DgmOctree::associatedCloud(), ccFastMarchingForNormsDirection::DirectionCell::cellCode, count, Vector3Tpl< Type >::dot(), ccNormalVectors::GetNormal(), ccNormalVectors::GetNormIndex(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), cloudViewer::DgmOctree::getPointsInCell(), ccArray< Type, N, ComponentType >::getValue(), cloudViewer::FastMarching::m_activeCells, cloudViewer::FastMarching::m_gridLevel, cloudViewer::FastMarching::m_initialized, cloudViewer::FastMarching::m_octree, cloudViewer::FastMarching::m_theGrid, cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, ccFastMarchingForNormsDirection::DirectionCell::N, cloudViewer::GenericCloud::setPointScalarValue(), ccArray< Type, N, ComponentType >::setValue(), cloudViewer::ReferenceCloud::size(), and cloudViewer::FastMarching::Cell::T.
Referenced by OrientNormals().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/ecvFastMarchingForNormsDirection.h
/root/ACloudViewer/libs/CV_db/src/ecvFastMarchingForNormsDirection.cpp