ACloudViewer: cvProbeFilter Class Reference
cvProbeFilter Class Reference
#include <cvProbeFilter.h>
Public Member Functions
cvProbeFilter (QWidget *parent=nullptr)
virtual void apply () override
virtual ccHObject * getOutput () override
virtual void clearAllActor () override
virtual void showInteractor (bool state) override
virtual void getInteractorBounds (ccBBox &bbox) override
virtual void getInteractorTransformation (ccGLMatrixd &trans) override
virtual void shift (const CCVector3d &v) override
Shifts the current interactor.
Public Member Functions inherited from cvGenericFilter
cvGenericFilter (QWidget *parent=nullptr)
virtual ~cvGenericFilter ()
virtual void start ()
virtual void update ()
virtual void reset ()
virtual void restoreOrigin ()
virtual void getOutput (std::vector< ccHObject * > &outputSlices, std::vector< ccPolyline * > &outputContours)
virtual bool initModel ()
virtual bool setInput (ccHObject *obj)
virtual void updateUi ()
virtual void getInteractorInfos (ccBBox &bbox, ccGLMatrixd &trans)
void setUpViewer (PclUtils::PCLVis *viewer)
void showOutline (bool show=true)
void setNegative (bool state)
void setInteractor (vtkRenderWindowInteractor *interactor)
vtkRenderWindowInteractor * getInteractor ()
Protected Types
enum WidgetType { WT_Line , WT_Sphere , WT_Box , WT_ImplicitPlane }
Protected Types inherited from cvGenericFilter
enum DisplayEffect { Opaque , Transparent , Points , Wireframe }
Protected Member Functions
virtual void modelReady () override
virtual void createUi () override
virtual void initFilter () override
virtual void dataChanged () override
Protected Member Functions inherited from cvGenericFilter
virtual void colorsChanged ()
void setDisplayEffect (DisplayEffect effect)
DisplayEffect displayEffect () const
void safeOff (vtk3DWidget *widget)
void updateSize ()
void UpdateScalarRange ()
void applyDisplayEffect ()
void setScalarBarColors (const QColor &clr1, const QColor &clr2)
QColor color1 () const
QColor color2 () const
void setScalarRange (double min, double max)
double scalarMin () const
double scalarMax () const
vtkSmartPointer< vtkDataArray > getActorScalars (vtkSmartPointer< vtkActor > actor)
int getDefaultScalarInterpolationForDataSet (vtkDataSet *data)
vtkSmartPointer< vtkLookupTable > createLookupTable (double min, double max)
template<class ConfigClass >
void setupConfigWidget (ConfigClass *cc)
template<class DataObject , class Mapper >
void createActorFromData (vtkDataObject *dataObj)
void showScalarBar (bool show=true)
void setOutlineColor (const QColor &clr)
bool isValidPolyData () const
bool isValidDataSet () const
void addActor (const vtkSmartPointer< vtkProp > actor)
void removeActor (const vtkSmartPointer< vtkProp > actor)
void setResultData (vtkSmartPointer< vtkDataObject > data)
vtkSmartPointer< vtkDataObject > resultData () const
Protected Attributes
Ui::cvProbeFilterDlg * m_configUi = nullptr
WidgetType m_widgetType = WT_Line
vtkSmartPointer< vtkLineWidget > m_lineWidget
vtkSmartPointer< vtkSphereWidget > m_sphereWidget
vtkSmartPointer< vtkBoxWidget > m_boxWidget
vtkSmartPointer< vtkImplicitPlaneWidget > m_implicitPlaneWidget
vtkSmartPointer< vtkProbeFilter > m_probe
QCustomPlot * m_plotWidget = nullptr
double m_linePoint1 [3]
double m_linePoint2 [3]
double m_sphereCenter [3]
double m_sphereRadius
double m_planeOrigin [3]
double m_planeNormal [3]
Protected Attributes inherited from cvGenericFilter
Ui::GenericFilterDlg * m_ui = nullptr
DisplayEffect m_displayEffect = Opaque
vtkDataObject * m_dataObject = nullptr
vtkSmartPointer< vtkDataObject > m_resultData
bool m_keepMode
bool m_negative
bool m_meshMode
bool m_preview
std::string m_id
ccHObject * m_entity = nullptr
PclUtils::PCLVis * m_viewer = nullptr
vtkRenderWindowInteractor * m_interactor = nullptr
vtkSmartPointer< vtkActor > m_modelActor
vtkSmartPointer< vtkLODActor > m_filterActor
vtkSmartPointer< vtkScalarBarActor > m_scalarBar
vtkSmartPointer< vtkActor > m_outlineActor
QColor m_color1 = Qt::blue
QColor m_color2 = Qt::red
double m_scalarMin = 0.0
double m_scalarMax = 1.0
Additional Inherited Members
Protected Slots inherited from cvGenericFilter
void onDoubleClick (int x, int y)
Static Protected Attributes inherited from cvGenericFilter
static const int MAX_PREVIEW_NUMBER = 20e4
Detailed Description
Definition at line 23 of file cvProbeFilter.h.
Member Enumeration Documentation
WidgetType
enum cvProbeFilter::WidgetType protected
Enumerator
WT_Line
WT_Sphere
WT_Box
WT_ImplicitPlane
Definition at line 60 of file cvProbeFilter.h.
Constructor & Destructor Documentation
cvProbeFilter()
cvProbeFilter::cvProbeFilter (QWidget * parent = nullptr) explicit
Definition at line 50 of file cvProbeFilter.cpp.
References createUi().
Member Function Documentation
apply()
void cvProbeFilter::apply () override virtual
Implements cvGenericFilter.
Definition at line 81 of file cvProbeFilter.cpp.
References QCustomPlot::addGraph(), QtCompatRegExpOption::CaseInsensitive, QCustomPlot::clearGraphs(), Utils::ColorSeries::Cool, QCustomPlot::graph(), cvGenericFilter::m_dataObject, m_linePoint1, m_linePoint2, m_planeNormal, m_planeOrigin, m_plotWidget, m_probe, m_sphereCenter, m_widgetType, Utils::ColorSeries::nextColor(), QCustomPlot::replot(), QCPGraph::rescaleAxes(), QCPGraph::setData(), QCPAbstractPlottable::setName(), QCPAbstractPlottable::setPen(), Utils::ColorSeries::setScheme(), cvGenericFilter::update(), VTK_CREATE, VtkUtils::vtkInitOnce(), WT_Box, WT_ImplicitPlane, WT_Line, WT_Sphere, x, and y.
Referenced by dataChanged(), and shift().
clearAllActor()
void cvProbeFilter::clearAllActor () override virtual
Reimplemented from cvGenericFilter.
Definition at line 299 of file cvProbeFilter.cpp.
References cvGenericFilter::clearAllActor(), m_boxWidget, m_configUi, m_implicitPlaneWidget, m_lineWidget, m_plotWidget, m_sphereWidget, and cvGenericFilter::safeOff().
createUi()
void cvProbeFilter::createUi () override protected virtual
Reimplemented from cvGenericFilter.
Definition at line 55 of file cvProbeFilter.cpp.
References QCustomPlot::clearGraphs(), cvGenericFilter::createUi(), QCP::iRangeDrag, QCP::iRangeZoom, QCP::iSelectPlottables, QCustomPlot::legend, m_configUi, m_plotWidget, QCPLegend::setFont(), QCustomPlot::setInteractions(), QCPAxis::setTickLabels(), cvGenericFilter::setupConfigWidget(), QCPLayerable::setVisible(), QCustomPlot::xAxis, QCustomPlot::xAxis2, QCustomPlot::yAxis, and QCustomPlot::yAxis2.
Referenced by cvProbeFilter().
dataChanged()
void cvProbeFilter::dataChanged () override protected virtual
Reimplemented from cvGenericFilter.
Definition at line 323 of file cvProbeFilter.cpp.
References apply().
getInteractorBounds()
void cvProbeFilter::getInteractorBounds (ccBBox & bbox) override virtual
Reimplemented from cvGenericFilter.
Definition at line 188 of file cvProbeFilter.cpp.
References m_boxWidget, m_implicitPlaneWidget, m_lineWidget, m_sphereWidget, m_widgetType, cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), and cloudViewer::BoundingBoxTpl< T >::setValidity().
getInteractorTransformation()
void cvProbeFilter::getInteractorTransformation (ccGLMatrixd & trans) override virtual
Reimplemented from cvGenericFilter.
Definition at line 232 of file cvProbeFilter.cpp.
References ccGLMatrixTpl< T >::data(), m_boxWidget, m_implicitPlaneWidget, m_lineWidget, m_sphereWidget, and m_widgetType.
getOutput()
ccHObject * cvProbeFilter::getOutput () override virtual
Reimplemented from cvGenericFilter.
Definition at line 325 of file cvProbeFilter.cpp.
References QtCompatRegExpOption::CaseInsensitive, ecvFileUtils::defaultDocPath(), ecvDisplayTools::GetCurrentScreen(), m_plotWidget, m_probe, CVLog::Print(), result, QCustomPlot::saveBmp(), QCustomPlot::savePdf(), QCustomPlot::savePng(), and CVLog::Warning().
initFilter()
void cvProbeFilter::initFilter () override protected virtual
Reimplemented from cvGenericFilter.
Definition at line 318 of file cvProbeFilter.cpp.
References cvGenericFilter::initFilter(), and cvGenericFilter::setDisplayEffect().
modelReady()
void cvProbeFilter::modelReady () override protected virtual
Reimplemented from cvGenericFilter.
Definition at line 480 of file cvProbeFilter.cpp.
References cvGenericFilter::modelReady().
shift()
void cvProbeFilter::shift (const CCVector3d & v) override virtual
Shifts the current interactor.
Reimplemented from cvGenericFilter.
Definition at line 259 of file cvProbeFilter.cpp.
References apply(), m_boxWidget, m_implicitPlaneWidget, m_linePoint1, m_linePoint2, m_lineWidget, m_sphereCenter, m_sphereWidget, m_widgetType, Tuple3Tpl< Type >::u, Vector3Tpl< double >::vadd(), and VTK_CREATE.
showInteractor()
void cvProbeFilter::showInteractor (bool state) override virtual
Reimplemented from cvGenericFilter.
Definition at line 160 of file cvProbeFilter.cpp.
References m_boxWidget, m_implicitPlaneWidget, m_lineWidget, m_sphereWidget, m_widgetType, and cvGenericFilter::safeOff().
Member Data Documentation
m_boxWidget
vtkSmartPointer<vtkBoxWidget> cvProbeFilter::m_boxWidget protected
Definition at line 67 of file cvProbeFilter.h.
Referenced by clearAllActor(), getInteractorBounds(), getInteractorTransformation(), shift(), and showInteractor().
m_configUi
Ui::cvProbeFilterDlg* cvProbeFilter::m_configUi = nullptr protected
Definition at line 62 of file cvProbeFilter.h.
Referenced by clearAllActor(), and createUi().
m_implicitPlaneWidget
vtkSmartPointer<vtkImplicitPlaneWidget> cvProbeFilter::m_implicitPlaneWidget protected
Definition at line 68 of file cvProbeFilter.h.
Referenced by clearAllActor(), getInteractorBounds(), getInteractorTransformation(), shift(), and showInteractor().
m_linePoint1
double cvProbeFilter::m_linePoint1[3] protected
Definition at line 74 of file cvProbeFilter.h.
Referenced by apply(), and shift().
m_linePoint2
double cvProbeFilter::m_linePoint2[3] protected
Definition at line 75 of file cvProbeFilter.h.
Referenced by apply(), and shift().
m_lineWidget
vtkSmartPointer<vtkLineWidget> cvProbeFilter::m_lineWidget protected
Definition at line 65 of file cvProbeFilter.h.
Referenced by clearAllActor(), getInteractorBounds(), getInteractorTransformation(), shift(), and showInteractor().
m_planeNormal
double cvProbeFilter::m_planeNormal[3] protected
Definition at line 81 of file cvProbeFilter.h.
Referenced by apply().
m_planeOrigin
double cvProbeFilter::m_planeOrigin[3] protected
Definition at line 80 of file cvProbeFilter.h.
Referenced by apply().
m_plotWidget
QCustomPlot* cvProbeFilter::m_plotWidget = nullptr protected
Definition at line 72 of file cvProbeFilter.h.
Referenced by apply(), clearAllActor(), createUi(), and getOutput().
m_probe
vtkSmartPointer<vtkProbeFilter> cvProbeFilter::m_probe protected
Definition at line 70 of file cvProbeFilter.h.
Referenced by apply(), and getOutput().
m_sphereCenter
double cvProbeFilter::m_sphereCenter[3] protected
Definition at line 77 of file cvProbeFilter.h.
Referenced by apply(), and shift().
m_sphereRadius
double cvProbeFilter::m_sphereRadius protected
Definition at line 78 of file cvProbeFilter.h.
m_sphereWidget
vtkSmartPointer<vtkSphereWidget> cvProbeFilter::m_sphereWidget protected
Definition at line 66 of file cvProbeFilter.h.
Referenced by clearAllActor(), getInteractorBounds(), getInteractorTransformation(), shift(), and showInteractor().
m_widgetType
WidgetType cvProbeFilter::m_widgetType = WT_Line protected
Definition at line 64 of file cvProbeFilter.h.
Referenced by apply(), getInteractorBounds(), getInteractorTransformation(), shift(), and showInteractor().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/cvProbeFilter.h
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/cvProbeFilter.cpp