ACloudViewer: cloudViewer::t::geometry::RGBDImage Class Reference
cloudViewer::t::geometry::RGBDImage Class Reference
RGBDImage A pair of color and depth images.
#include <RGBDImage.h>
Public Member Functions
RGBDImage ()
Default Comnstructor.
RGBDImage (const Image &color, const Image &depth, bool aligned=true)
Parameterized Constructor.
core::Device GetDevice () const override
Returns the device of the geometry.
~RGBDImage () override
RGBDImage & Clear () override
Clear stored data.
bool IsEmpty () const override
Is any data stored?
bool AreAligned () const
Are the depth and color images aligned (same viewpoint and resolution)?
core::Tensor GetMinBound () const
Compute min 2D coordinates for the data (always {0,0}).
core::Tensor GetMaxBound () const
Compute max 2D coordinates for the data.
RGBDImage To (const core::Device &device, bool copy=false) const
RGBDImage Clone () const
Returns copy of the RGBD image on the same device.
cloudViewer::geometry::RGBDImage ToLegacy () const
Convert to the legacy RGBDImage format.
std::string ToString () const
Text description.
Public Member Functions inherited from cloudViewer::t::geometry::Geometry
virtual ~Geometry ()
GeometryType GetGeometryType () const
Returns one of registered geometry types.
int Dimension () const
Returns whether the geometry is 2D or 3D.
std::string GetName () const
void SetName (const std::string &name)
Public Member Functions inherited from cloudViewer::core::IsDevice
IsDevice ()=default
virtual ~IsDevice ()=default
bool IsCPU () const
bool IsCUDA () const
bool IsSYCL () const
Public Attributes
Image color_
The color image.
Image depth_
The depth image.
bool aligned_ = true
Are the depth and color images aligned (same viewpoint and resolution)?
Additional Inherited Members
Public Types inherited from cloudViewer::t::geometry::Geometry
enum class GeometryType {
Unspecified = 0 , PointCloud = 1 , VoxelGrid = 2 , Octree = 3 ,
LineSet = 4 , MeshBase = 5 , TriangleMesh = 6 , HalfEdgeTriangleMesh = 7 ,
Image = 8 , RGBDImage = 9 , TetraMesh = 10 , OrientedBoundingBox = 11 ,
AxisAlignedBoundingBox = 12
}
Specifies possible geometry types.
Protected Member Functions inherited from cloudViewer::t::geometry::Geometry
Geometry (GeometryType type, int dimension)
Parameterized Constructor.
Detailed Description
RGBDImage A pair of color and depth images.
For most processing, the image pair should be aligned (same viewpoint and resolution).
Definition at line 21 of file RGBDImage.h.
Constructor & Destructor Documentation
RGBDImage() [1/2]
cloudViewer::t::geometry::RGBDImage::RGBDImage () inline
Default Comnstructor.
Definition at line 24 of file RGBDImage.h.
Referenced by To().
RGBDImage() [2/2]
cloudViewer::t::geometry::RGBDImage::RGBDImage (const Image & color, const Image & depth, bool aligned = true) inline
Parameterized Constructor.
Parameters
color The color image.
depth The depth image.
aligned Are the two images aligned (same viewpoint and resolution)?
Definition at line 32 of file RGBDImage.h.
References aligned_, color, cloudViewer::t::geometry::Image::GetCols(), cloudViewer::t::geometry::Image::GetRows(), and LogWarning.
~RGBDImage()
cloudViewer::t::geometry::RGBDImage::~RGBDImage () inline override
Definition at line 56 of file RGBDImage.h.
Member Function Documentation
AreAligned()
bool cloudViewer::t::geometry::RGBDImage::AreAligned () const inline
Are the depth and color images aligned (same viewpoint and resolution)?
Definition at line 65 of file RGBDImage.h.
References aligned_.
Referenced by ToString().
Clear()
RGBDImage & cloudViewer::t::geometry::RGBDImage::Clear () override virtual
Clear stored data.
Implements cloudViewer::t::geometry::Geometry.
Definition at line 14 of file RGBDImage.cpp.
References cloudViewer::t::geometry::Image::Clear(), color_, and depth_.
Clone()
RGBDImage cloudViewer::t::geometry::RGBDImage::Clone () const inline
Returns copy of the RGBD image on the same device.
Definition at line 91 of file RGBDImage.h.
References color_, cloudViewer::t::geometry::Image::GetDevice(), and To().
GetDevice()
core::Device cloudViewer::t::geometry::RGBDImage::GetDevice () const inline override virtual
Returns the device of the geometry.
Implements cloudViewer::t::geometry::Geometry.
Definition at line 45 of file RGBDImage.h.
References color_, depth_, cloudViewer::t::geometry::Image::GetDevice(), LogError, and cloudViewer::core::Device::ToString().
GetMaxBound()
core::Tensor cloudViewer::t::geometry::RGBDImage::GetMaxBound () const inline
Compute max 2D coordinates for the data.
Definition at line 73 of file RGBDImage.h.
References color_, depth_, cloudViewer::t::geometry::Image::GetCols(), cloudViewer::t::geometry::Image::GetRows(), and cloudViewer::core::Int64.
GetMinBound()
core::Tensor cloudViewer::t::geometry::RGBDImage::GetMinBound () const inline
Compute min 2D coordinates for the data (always {0,0}).
Definition at line 68 of file RGBDImage.h.
References cloudViewer::core::Int64, and cloudViewer::core::Tensor::Zeros().
IsEmpty()
bool cloudViewer::t::geometry::RGBDImage::IsEmpty () const override virtual
Is any data stored?
Implements cloudViewer::t::geometry::Geometry.
Definition at line 20 of file RGBDImage.cpp.
References color_, depth_, and cloudViewer::t::geometry::Image::IsEmpty().
To()
RGBDImage cloudViewer::t::geometry::RGBDImage::To (const core::Device & device, bool copy = false) const inline
Transfer the RGBD image to a specified device.
Parameters
device The targeted device to convert to.
copy If true, a new image is always created; if false, the copy is avoided when the original image is already on the target device.
Definition at line 85 of file RGBDImage.h.
References aligned_, color_, copy, depth_, RGBDImage(), and cloudViewer::t::geometry::Image::To().
Referenced by Clone().
ToLegacy()
cloudViewer::geometry::RGBDImage cloudViewer::t::geometry::RGBDImage::ToLegacy () const inline
Convert to the legacy RGBDImage format.
Definition at line 94 of file RGBDImage.h.
References color_, depth_, and cloudViewer::t::geometry::Image::ToLegacy().
ToString()
std::string cloudViewer::t::geometry::RGBDImage::ToString () const
Text description.
Definition at line 22 of file RGBDImage.cpp.
References AreAligned(), color_, depth_, format, cloudViewer::t::geometry::Image::GetChannels(), cloudViewer::t::geometry::Image::GetCols(), cloudViewer::t::geometry::Image::GetDevice(), cloudViewer::t::geometry::Image::GetDtype(), cloudViewer::t::geometry::Image::GetRows(), cloudViewer::core::Device::ToString(), and cloudViewer::core::Dtype::ToString().
Member Data Documentation
aligned_
bool cloudViewer::t::geometry::RGBDImage::aligned_ = true
Are the depth and color images aligned (same viewpoint and resolution)?
Definition at line 108 of file RGBDImage.h.
Referenced by AreAligned(), RGBDImage(), and To().
color_
Image cloudViewer::t::geometry::RGBDImage::color_
The color image.
Definition at line 104 of file RGBDImage.h.
Referenced by cloudViewer::t::io::RealSenseSensor::CaptureFrame(), Clear(), Clone(), cloudViewer::t::geometry::PointCloud::CreateFromRGBDImage(), cloudViewer::t::pipelines::slac::ControlGrid::Deform(), GetDevice(), GetMaxBound(), IsEmpty(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScale(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScaleHybrid(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScaleIntensity(), To(), ToLegacy(), and ToString().
depth_
Image cloudViewer::t::geometry::RGBDImage::depth_
The depth image.
Definition at line 106 of file RGBDImage.h.
Referenced by cloudViewer::t::io::RealSenseSensor::CaptureFrame(), Clear(), cloudViewer::t::geometry::PointCloud::CreateFromRGBDImage(), cloudViewer::t::pipelines::slac::ControlGrid::Deform(), GetDevice(), GetMaxBound(), IsEmpty(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScale(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScaleHybrid(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScaleIntensity(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScalePointToPlane(), To(), ToLegacy(), and ToString().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/t/geometry/RGBDImage.h
/root/ACloudViewer/libs/cloudViewer/t/geometry/RGBDImage.cpp