ACloudViewer: SFCollector Class Reference
SFCollector Class Reference
SF collector.
#include <ScalarFieldCollector.h>
Classes
struct SFDesc
Public Types
enum Behavior { ALWAYS_KEEP , CAN_REMOVE , ALWAYS_REMOVE }
using Map = QMap< cloudViewer::ScalarField *, SFDesc >
Public Member Functions
void push (ccPointCloud *cloud, cloudViewer::ScalarField *sf, Behavior behavior)
void releaseSFs (bool keepByDefault)
bool setBehavior (cloudViewer::ScalarField *sf, Behavior behavior)
Public Attributes
Map scalarFields
Detailed Description
SF collector.
For tracking the creation and removing a set of scalar fields
Definition at line 42 of file ScalarFieldCollector.h.
Member Typedef Documentation
Map
using SFCollector::Map = QMap<cloudViewer::ScalarField*, SFDesc>
Definition at line 60 of file ScalarFieldCollector.h.
Member Enumeration Documentation
Behavior
enum SFCollector::Behavior
Enumerator
ALWAYS_KEEP
CAN_REMOVE
ALWAYS_REMOVE
Definition at line 44 of file ScalarFieldCollector.h.
Member Function Documentation
push()
void SFCollector::push (ccPointCloud * cloud, cloudViewer::ScalarField * sf, Behavior behavior)
Definition at line 19 of file ScalarFieldCollector.cpp.
References SFCollector::SFDesc::behavior, SFCollector::SFDesc::cloud, and scalarFields.
Referenced by masc::PointFeature::prepare(), and masc::Feature::PrepareSF().
releaseSFs()
void SFCollector::releaseSFs (bool keepByDefault)
Definition at line 35 of file ScalarFieldCollector.cpp.
References ALWAYS_KEEP, SFCollector::SFDesc::behavior, CAN_REMOVE, SFCollector::SFDesc::cloud, ccPointCloud::deleteScalarField(), cloudViewer::ScalarField::getName(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), and scalarFields.
Referenced by q3DMASCPlugin::doClassifyAction(), q3DMASCPlugin::doTrainAction(), and Command3DMASCClassif::process().
setBehavior()
bool SFCollector::setBehavior (cloudViewer::ScalarField * sf, Behavior behavior)
Definition at line 64 of file ScalarFieldCollector.cpp.
References scalarFields.
Referenced by masc::NeighborhoodFeature::prepare(), and masc::PointFeature::prepare().
Member Data Documentation
scalarFields
Map SFCollector::scalarFields
Definition at line 61 of file ScalarFieldCollector.h.
Referenced by masc::NeighborhoodFeature::prepare(), masc::PointFeature::prepare(), push(), releaseSFs(), and setBehavior().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/q3DMASC/ScalarFieldCollector.h
/root/ACloudViewer/plugins/core/Standard/q3DMASC/ScalarFieldCollector.cpp