ACloudViewer: cvContourTool Class Reference
cvContourTool Class Reference
#include <cvContourTool.h>
Public Member Functions
cvContourTool (QWidget *parent=nullptr)
~cvContourTool () override
virtual void start () override
virtual void reset () override
virtual void showWidget (bool state) override
virtual ccHObject * getOutput () override
virtual void setColor (double r, double g, double b) override
Set measurement color (RGB values in range [0.0, 1.0])
virtual bool getColor (double &r, double &g, double &b) const override
virtual void lockInteraction () override
Lock tool interaction (disable VTK widget interaction and UI controls)
virtual void unlockInteraction () override
Unlock tool interaction (enable VTK widget interaction and UI controls)
virtual void setInstanceLabel (const QString &label) override
Set instance label suffix (e.g., "#1", "#2") for display in 3D view.
Public Member Functions inherited from cvGenericMeasurementTool
cvGenericMeasurementTool (QWidget *parent=nullptr)
virtual ~cvGenericMeasurementTool ()
virtual void update ()
virtual bool initModel ()
virtual bool setInput (ccHObject *obj)
virtual void clearAllActor ()
virtual double getMeasurementValue () const
Get measurement value (distance or angle)
virtual void getPoint1 (double pos[3]) const
Get point 1 coordinates.
virtual void getPoint2 (double pos[3]) const
Get point 2 coordinates.
virtual void getCenter (double pos[3]) const
Get center point coordinates (for angle/protractor)
virtual void setPoint1 (double pos[3])
Set point 1 coordinates.
virtual void setPoint2 (double pos[3])
Set point 2 coordinates.
virtual void setCenter (double pos[3])
Set center point coordinates (for angle/protractor)
virtual void setFontFamily (const QString &family)
virtual void setFontSize (int size)
Set font size for measurement labels.
virtual void setBold (bool bold)
Set font bold state for measurement labels.
virtual void setItalic (bool italic)
Set font italic state for measurement labels.
virtual void setShadow (bool shadow)
Set font shadow state for measurement labels.
virtual void setFontOpacity (double opacity)
Set font opacity for measurement labels (0.0 to 1.0)
virtual void setFontColor (double r, double g, double b)
Set font color for measurement labels (RGB values 0.0-1.0)
virtual void setHorizontalJustification (const QString &justification)
virtual void setVerticalJustification (const QString &justification)
QString getFontFamily () const
Get font properties (for UI synchronization)
int getFontSize () const
void getFontColor (double &r, double &g, double &b) const
bool getFontBold () const
bool getFontItalic () const
bool getFontShadow () const
double getFontOpacity () const
QString getHorizontalJustification () const
QString getVerticalJustification () const
void setUpViewer (PclUtils::PCLVis *viewer)
void setInteractor (vtkRenderWindowInteractor *interactor)
vtkRenderWindowInteractor * getInteractor ()
vtkRenderer * getRenderer ()
void setupShortcuts (QWidget *vtkWidget)
void disableShortcuts ()
Disable all keyboard shortcuts (call before tool destruction)
void clearPickingCache ()
Protected Member Functions
virtual void initTool () override
virtual void createUi () override
Protected Member Functions inherited from cvGenericMeasurementTool
virtual void modelReady ()
virtual void dataChanged ()
void safeOff (vtkAbstractWidget *widget)
virtual void setupPointPickingShortcuts (QWidget *vtkWidget)
void updatePickingHelpers ()
Update point picking helpers with current interactor/renderer.
void addActor (const vtkSmartPointer< vtkProp > actor)
void removeActor (const vtkSmartPointer< vtkProp > actor)
Additional Inherited Members
Signals inherited from cvGenericMeasurementTool
void measurementValueChanged ()
Signal sent when the measurement value changes.
void pointPickingRequested (int pointIndex)
void pointPickingCancelled ()
Signal sent when point picking is cancelled.
Protected Attributes inherited from cvGenericMeasurementTool
Ui::GenericMeasurementToolDlg * m_ui = nullptr
std::string m_id
ccHObject * m_entity = nullptr
PclUtils::PCLVis * m_viewer = nullptr
vtkRenderWindowInteractor * m_interactor = nullptr
vtkRenderer * m_renderer = nullptr
vtkSmartPointer< vtkActor > m_modelActor
QList< cvPointPickingHelper * > m_pickingHelpers
List of point picking helpers for keyboard shortcuts.
QWidget * m_vtkWidget = nullptr
VTK widget reference for creating shortcuts (saved from linkWith)
QString m_fontFamily = "Arial"
Font properties for measurement labels (shared by all tools)
int m_fontSize = 6
double m_fontColor [3] = {1.0, 1.0, 1.0}
bool m_fontBold = false
bool m_fontItalic = false
bool m_fontShadow = true
double m_fontOpacity = 1.0
QString m_horizontalJustification = "Left"
QString m_verticalJustification = "Bottom"
Detailed Description
Definition at line 18 of file cvContourTool.h.
Constructor & Destructor Documentation
cvContourTool()
cvContourTool::cvContourTool (QWidget * parent = nullptr) explicit
Definition at line 42 of file cvContourTool.cpp.
References cvGenericMeasurementTool::m_fontSize.
~cvContourTool()
cvContourTool::~cvContourTool () override
Definition at line 52 of file cvContourTool.cpp.
References cvGenericMeasurementTool::m_interactor.
Member Function Documentation
createUi()
void cvContourTool::createUi () override protected virtual
Reimplemented from cvGenericMeasurementTool.
Definition at line 138 of file cvContourTool.cpp.
References CVLog::Error(), cvGenericMeasurementTool::m_ui, and cloudViewer::core::Minimum().
getColor()
bool cvContourTool::getColor (double & r, double & g, double & b) const override virtual
Get measurement color (RGB values in range [0.0, 1.0]) Returns false if not implemented, true if color is retrieved
Reimplemented from cvGenericMeasurementTool.
Definition at line 273 of file cvContourTool.cpp.
getOutput()
ccHObject * cvContourTool::getOutput () override virtual
Reimplemented from cvGenericMeasurementTool.
Definition at line 510 of file cvContourTool.cpp.
References vtk2cc::ConvertToPolyline(), CVLog::Error(), cloudViewer::ReferenceCloud::getAssociatedCloud(), ccObject::getName(), cloudViewer::GenericIndexedCloud::getPoint(), ecvColor::green(), cloudViewer::LessThanEpsilon(), CVLog::Print(), ccPolyline::set2DMode(), cloudViewer::Polyline::setClosed(), ccPolyline::setColor(), ccObject::setName(), ccDrawableObject::setVisible(), ccPolyline::setWidth(), cloudViewer::GenericCloud::size(), CVLog::Warning(), and Tuple3Tpl< Type >::z.
initTool()
void cvContourTool::initTool () override protected virtual
Reimplemented from cvGenericMeasurementTool.
Definition at line 89 of file cvContourTool.cpp.
lockInteraction()
void cvContourTool::lockInteraction () override virtual
Lock tool interaction (disable VTK widget interaction and UI controls)
Reimplemented from cvGenericMeasurementTool.
Definition at line 280 of file cvContourTool.cpp.
References cvGenericMeasurementTool::disableShortcuts(), cvConstrainedContourRepresentation::GetLabelActor(), cvGenericMeasurementTool::m_interactor, CVLog::PrintDebug(), and cvGenericMeasurementTool::update().
reset()
void cvContourTool::reset (void) override virtual
Reimplemented from cvGenericMeasurementTool.
Definition at line 216 of file cvContourTool.cpp.
References cvGenericMeasurementTool::measurementValueChanged(), and cvGenericMeasurementTool::update().
setColor()
void cvContourTool::setColor (double r, double g, double b) override virtual
Set measurement color (RGB values in range [0.0, 1.0])
Reimplemented from cvGenericMeasurementTool.
Definition at line 241 of file cvContourTool.cpp.
References cvGenericMeasurementTool::update().
setInstanceLabel()
void cvContourTool::setInstanceLabel (const QString & label) override virtual
Set instance label suffix (e.g., "#1", "#2") for display in 3D view.
Reimplemented from cvGenericMeasurementTool.
Definition at line 478 of file cvContourTool.cpp.
References cvConstrainedContourRepresentation::BuildRepresentation(), cvConstrainedContourRepresentation::SetLabelSuffix(), and cvGenericMeasurementTool::update().
showWidget()
void cvContourTool::showWidget (bool state) override virtual
Reimplemented from cvGenericMeasurementTool.
Definition at line 228 of file cvContourTool.cpp.
References cvGenericMeasurementTool::update().
start()
void cvContourTool::start (void) override virtual
Reimplemented from cvGenericMeasurementTool.
Definition at line 214 of file cvContourTool.cpp.
References cvGenericMeasurementTool::start().
unlockInteraction()
void cvContourTool::unlockInteraction () override virtual
Unlock tool interaction (enable VTK widget interaction and UI controls)
Reimplemented from cvGenericMeasurementTool.
Definition at line 365 of file cvContourTool.cpp.
References cvConstrainedContourRepresentation::GetLabelActor(), cvGenericMeasurementTool::m_fontColor, cvGenericMeasurementTool::m_fontOpacity, cvGenericMeasurementTool::m_interactor, cvGenericMeasurementTool::m_pickingHelpers, cvGenericMeasurementTool::m_vtkWidget, CVLog::PrintDebug(), cvGenericMeasurementTool::setupShortcuts(), and cvGenericMeasurementTool::update().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/MeasurementTools/cvContourTool.h
/root/ACloudViewer/libs/PCLEngine/Tools/MeasurementTools/cvContourTool.cpp