ACloudViewer: qM3C2Tools Class Reference
qM3C2Tools Class Reference
M3C2 generic tools.
#include <qM3C2Tools.h>
Classes
struct GuessedParams
M3C2 parameters that can be guessed automatically by 'probing'.
Static Public Member Functions
static void ComputeStatistics (cloudViewer::DgmOctree::NeighboursSet &set, bool useMedian, double &meanOrMedian, double &stdDevOrIQR)
Computes statistics on a neighbors set.
static bool GuessBestParams (ccPointCloud *cloud1, ccPointCloud *cloud2, unsigned minPoints4Stats, GuessedParams &params, bool fastMode, ecvMainAppInterface *app=nullptr, unsigned probingCount=1000)
Tries to guess some M3C2 parameters by randomly 'probing' the cloud.
Detailed Description
M3C2 generic tools.
Definition at line 65 of file qM3C2Tools.h.
Member Function Documentation
ComputeStatistics()
void qM3C2Tools::ComputeStatistics (cloudViewer::DgmOctree::NeighboursSet & set, bool useMedian, double & meanOrMedian, double & stdDevOrIQR) static
Computes statistics on a neighbors set.
Either the mean distance and std. dev. (if useMedian is false) or the median and interquartile range (if useMedian is true). See http://en.wikipedia.org/wiki/Interquartile_range
Definition at line 487 of file qM3C2Tools.cpp.
References count, cloudViewer::DgmOctree::PointDescriptor::distComp(), Interquartile(), Median(), and NAN_VALUE.
Referenced by ComputeM3C2DistForPoint().
GuessBestParams()
bool qM3C2Tools::GuessBestParams (ccPointCloud * cloud1, ccPointCloud * cloud2, unsigned minPoints4Stats, qM3C2Tools::GuessedParams & params, bool fastMode, ecvMainAppInterface * app = nullptr, unsigned probingCount = 1000) static
Tries to guess some M3C2 parameters by randomly 'probing' the cloud.
Definition at line 529 of file qM3C2Tools.cpp.
References ecvMainAppInterface::addToDB(), cloudViewer::utility::ceil(), ccGenericPointCloud::computeOctree(), cloudViewer::DistanceComputationTools::computePoint2PlaneDistance(), ecvMainAppInterface::dispToConsole(), cloudViewer::utility::floor(), Vector3Tpl< double >::fromArray(), cloudViewer::BoundingBoxTpl< T >::getDiagNorm(), cloudViewer::BoundingBoxTpl< T >::getDiagNormd(), cloudViewer::Neighbourhood::getLSPlane(), ecvMainAppInterface::getMainWindow(), ccGenericPointCloud::getOctree(), ccGenericPointCloud::getOctreeProxy(), ccGenericPointCloud::getOwnBB(), ccHObject::getParent(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, Vector3Tpl< Type >::normalize(), qM3C2Tools::GuessedParams::normScale, qM3C2Tools::GuessedParams::preferredDimension, qM3C2Tools::GuessedParams::projDepth, qM3C2Tools::GuessedParams::projScale, cloudViewer::ReferenceCloud::resize(), cloudViewer::ReferenceCloud::setPointIndex(), cloudViewer::PointCloudTpl< T >::size(), Tuple3Tpl< Type >::u, ecvMainAppInterface::WRN_CONSOLE_MESSAGE, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by qM3C2Dialog::guessParams().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qM3C2/include/qM3C2Tools.h
/root/ACloudViewer/plugins/core/Standard/qM3C2/src/qM3C2Tools.cpp