ACloudViewer: cloudViewer::utility::CountingProgressReporter Class Reference
cloudViewer::utility::CountingProgressReporter Class Reference
#include <ProgressReporters.h>
Public Member Functions
CountingProgressReporter (std::function< bool(double)> f)
void SetTotal (int64_t total)
bool Update (int64_t count)
void Finish ()
void operator++ ()
Detailed Description
Progress reporting through update_progress(double percent) function. If you have a set number of items to process (or bytes to load), CountingProgressReporter will convert that to percentages (you still have to specify how many items you have, of course)
Definition at line 19 of file ProgressReporters.h.
Constructor & Destructor Documentation
CountingProgressReporter()
cloudViewer::utility::CountingProgressReporter::CountingProgressReporter (std::function< bool(double)> f) inline
Definition at line 21 of file ProgressReporters.h.
Member Function Documentation
Finish()
void cloudViewer::utility::CountingProgressReporter::Finish () inline
Definition at line 38 of file ProgressReporters.h.
Referenced by cloudViewer::t::io::ReadPCDData(), cloudViewer::io::ReadPointCloudFromPLY(), cloudViewer::t::io::ReadPointCloudFromPLY(), cloudViewer::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromSPLAT(), cloudViewer::t::io::ReadPointCloudFromTXT(), cloudViewer::io::ReadPointCloudFromXYZ(), cloudViewer::t::io::ReadPointCloudFromXYZI(), cloudViewer::io::ReadPointCloudFromXYZN(), cloudViewer::io::ReadPointCloudFromXYZRGB(), cloudViewer::io::ReadPointCloudInMemoryFromXYZ(), cloudViewer::io::WritePointCloudInMemoryToXYZ(), cloudViewer::io::WritePointCloudToPLY(), cloudViewer::io::WritePointCloudToPTS(), cloudViewer::t::io::WritePointCloudToPTS(), cloudViewer::t::io::WritePointCloudToSPLAT(), cloudViewer::t::io::WritePointCloudToTXT(), cloudViewer::io::WritePointCloudToXYZ(), cloudViewer::t::io::WritePointCloudToXYZI(), cloudViewer::io::WritePointCloudToXYZN(), and cloudViewer::io::WritePointCloudToXYZRGB().
operator++()
void cloudViewer::utility::CountingProgressReporter::operator++ () inline
Definition at line 40 of file ProgressReporters.h.
SetTotal()
void cloudViewer::utility::CountingProgressReporter::SetTotal (int64_t total) inline
Definition at line 24 of file ProgressReporters.h.
Referenced by cloudViewer::io::ReadModelUsingAssimp(), cloudViewer::t::io::ReadPCDData(), cloudViewer::io::ReadPointCloudFromPLY(), cloudViewer::t::io::ReadPointCloudFromPLY(), cloudViewer::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromSPLAT(), cloudViewer::t::io::ReadPointCloudFromTXT(), cloudViewer::io::ReadPointCloudFromXYZ(), cloudViewer::t::io::ReadPointCloudFromXYZI(), cloudViewer::io::ReadPointCloudFromXYZN(), cloudViewer::io::ReadPointCloudFromXYZRGB(), cloudViewer::io::ReadPointCloudInMemoryFromXYZ(), cloudViewer::io::ReadTriangleMeshFromPLY(), cloudViewer::t::io::WritePCDData(), cloudViewer::io::WritePointCloudInMemoryToXYZ(), cloudViewer::io::WritePointCloudToPLY(), cloudViewer::t::io::WritePointCloudToPLY(), cloudViewer::io::WritePointCloudToPTS(), cloudViewer::t::io::WritePointCloudToPTS(), cloudViewer::t::io::WritePointCloudToSPLAT(), cloudViewer::t::io::WritePointCloudToTXT(), cloudViewer::io::WritePointCloudToXYZ(), cloudViewer::t::io::WritePointCloudToXYZI(), cloudViewer::io::WritePointCloudToXYZN(), and cloudViewer::io::WritePointCloudToXYZRGB().
Update()
bool cloudViewer::utility::CountingProgressReporter::Update (int64_t count) inline
Definition at line 25 of file ProgressReporters.h.
References count.
Referenced by cloudViewer::io::ReadModelUsingAssimp(), cloudViewer::t::io::ReadPCDData(), cloudViewer::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromSPLAT(), cloudViewer::t::io::ReadPointCloudFromTXT(), cloudViewer::io::ReadPointCloudFromXYZ(), cloudViewer::t::io::ReadPointCloudFromXYZI(), cloudViewer::io::ReadPointCloudFromXYZN(), cloudViewer::io::ReadPointCloudFromXYZRGB(), cloudViewer::io::ReadPointCloudInMemoryFromXYZ(), cloudViewer::t::io::WritePCDData(), cloudViewer::io::WritePointCloudInMemoryToXYZ(), cloudViewer::io::WritePointCloudToPLY(), cloudViewer::t::io::WritePointCloudToPLY(), cloudViewer::io::WritePointCloudToPTS(), cloudViewer::t::io::WritePointCloudToPTS(), cloudViewer::t::io::WritePointCloudToSPLAT(), cloudViewer::t::io::WritePointCloudToTXT(), cloudViewer::io::WritePointCloudToXYZ(), cloudViewer::t::io::WritePointCloudToXYZI(), cloudViewer::io::WritePointCloudToXYZN(), and cloudViewer::io::WritePointCloudToXYZRGB().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/ProgressReporters.h