ACloudViewer: ccCamSensorProjectionDlg Class Reference
ccCamSensorProjectionDlg Class Reference
Camera sensor parameters dialog.
#include <ecvCamSensorProjectionDlg.h>
Public Member Functions
ccCamSensorProjectionDlg (QWidget *parent=0)
Default constructor.
void initWithCamSensor (const ccCameraSensor *sensor)
void updateCamSensor (ccCameraSensor *sensor)
Detailed Description
Camera sensor parameters dialog.
Definition at line 15 of file ecvCamSensorProjectionDlg.h.
Constructor & Destructor Documentation
ccCamSensorProjectionDlg()
ccCamSensorProjectionDlg::ccCamSensorProjectionDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 16 of file ecvCamSensorProjectionDlg.cpp.
Member Function Documentation
initWithCamSensor()
void ccCamSensorProjectionDlg::initWithCamSensor (const ccCameraSensor * sensor)
Definition at line 35 of file ecvCamSensorProjectionDlg.cpp.
References ccCameraSensor::IntrinsicParameters::arrayHeight, ccCameraSensor::IntrinsicParameters::arrayWidth, ccCameraSensor::BROWN_DISTORTION, ccGLMatrixTpl< T >::data(), ccCameraSensor::getDistortionParameters(), ccCameraSensor::getIntrinsicParameters(), ccSensor::getRigidTransformation(), ccGLMatrixTpl< T >::getTranslation(), ccCameraSensor::RadialDistortionParameters::k1, ccCameraSensor::RadialDistortionParameters::k2, ccCameraSensor::BrownDistortionParameters::K_BrownParams, ccCameraSensor::BrownDistortionParameters::linearDisparityParams, ccCameraSensor::BrownDistortionParameters::P_BrownParams, ccCameraSensor::IntrinsicParameters::pixelSize_mm, ccCameraSensor::IntrinsicParameters::principal_point, ccCameraSensor::BrownDistortionParameters::principalPointOffset, cloudViewer::RadiansToDegrees(), ccCameraSensor::SIMPLE_RADIAL_DISTORTION, ccCameraSensor::IntrinsicParameters::skew, ccCameraSensor::IntrinsicParameters::vertFocal_pix, ccCameraSensor::IntrinsicParameters::vFOV_rad, ccCameraSensor::IntrinsicParameters::zFar_mm, and ccCameraSensor::IntrinsicParameters::zNear_mm.
updateCamSensor()
void ccCamSensorProjectionDlg::updateCamSensor (ccCameraSensor * sensor)
Definition at line 132 of file ecvCamSensorProjectionDlg.cpp.
References ccCameraSensor::IntrinsicParameters::arrayHeight, ccCameraSensor::IntrinsicParameters::arrayWidth, ccGLMatrixTpl< T >::data(), cloudViewer::DegreesToRadians(), ccCameraSensor::IntrinsicParameters::pixelSize_mm, ccCameraSensor::IntrinsicParameters::principal_point, ccCameraSensor::setIntrinsicParameters(), ccSensor::setRigidTransformation(), ccGLMatrixTpl< T >::setTranslation(), ccCameraSensor::IntrinsicParameters::skew, ccCameraSensor::IntrinsicParameters::vertFocal_pix, ccCameraSensor::IntrinsicParameters::vFOV_rad, ccCameraSensor::IntrinsicParameters::zFar_mm, and ccCameraSensor::IntrinsicParameters::zNear_mm.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvCamSensorProjectionDlg.h
/root/ACloudViewer/app/ecvCamSensorProjectionDlg.cpp