ACloudViewer: cloudViewer::visualization::webrtc_server::RequestHandler Class Reference
cloudViewer::visualization::webrtc_server::RequestHandler Class Reference
Public Member Functions
RequestHandler (HttpServerRequestHandler::HttpFunction &func)
bool handle (CivetServer *server, struct mg_connection *conn)
bool handleGet (CivetServer *server, struct mg_connection *conn) override
bool handlePost (CivetServer *server, struct mg_connection *conn) override
Detailed Description
Definition at line 38 of file HttpServerRequestHandler.cpp.
Constructor & Destructor Documentation
RequestHandler()
cloudViewer::visualization::webrtc_server::RequestHandler::RequestHandler (HttpServerRequestHandler::HttpFunction & func) inline
Definition at line 40 of file HttpServerRequestHandler.cpp.
Member Function Documentation
handle()
bool cloudViewer::visualization::webrtc_server::RequestHandler::handle (CivetServer * server, struct mg_connection * conn) inline
Definition at line 43 of file HttpServerRequestHandler.cpp.
Referenced by handleGet(), and handlePost().
handleGet()
bool cloudViewer::visualization::webrtc_server::RequestHandler::handleGet (CivetServer * server, struct mg_connection * conn) inline override
Definition at line 75 of file HttpServerRequestHandler.cpp.
References handle().
handlePost()
bool cloudViewer::visualization::webrtc_server::RequestHandler::handlePost (CivetServer * server, struct mg_connection * conn) inline override
Definition at line 78 of file HttpServerRequestHandler.cpp.
References handle().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/webrtc_server/HttpServerRequestHandler.cpp