ACloudViewer: ccColorScale Class Reference
ccColorScale Class Reference
Color scale.
#include <ecvColorScale.h>
Classes
struct Label
Color scale label (value + optional text)
Public Types
typedef QSharedPointer< ccColorScale > Shared
Shared pointer type.
using LabelSet = std::set< Label >
Type of a list of custom labels.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Public Member Functions
ccColorScale (const QString &name, const QString &uuid=QString())
Default constructor.
virtual ~ccColorScale ()
Destructor.
ccColorScale::Shared copy (const QString &uuid=QString()) const
Creates a copy of this color scale (with a specified unique id)
const QString & getName () const
Returns name.
void setName (const QString &name)
Sets name.
QString getUuid () const
Returns unique ID.
void setUuid (QString uuid)
Sets unique ID.
void generateNewUuid ()
Generates a new unique ID.
bool isRelative () const
Returns whether scale is relative or absoute.
void setRelative ()
Sets scale as relative.
void setAbsolute (double minVal, double maxVal)
Sets scale as absolute.
void getAbsoluteBoundaries (double &minVal, double &maxVal) const
Get absolute scale boundaries.
bool isLocked () const
Returns whether scale is locked or not.
void setLocked (bool state)
Sets whether scale is locked or not.
LabelSet & customLabels ()
Returns the list of custom labels (if any)
const LabelSet & customLabels () const
Returns the list of custom labels (if any - const version)
void setCustomLabels (const LabelSet &labels)
Sets the list of custom labels (only if the scale is absolute)
int stepCount () const
Returns the current number of steps.
ccColorScaleElement & step (int index)
Access to a given step.
const ccColorScaleElement & step (int index) const
Access to a given step (const)
void insert (const ccColorScaleElement &step, bool autoUpdate=true)
Adds a step.
void remove (int index, bool autoUpdate=true)
Deletes a given step.
void clear ()
Clears all steps.
void update ()
Updates internal representation.
double getRelativePosition (double value) const
const ecvColor::Rgb * getColorByValue (double value, const ecvColor::Rgb *outOfRangeColor=nullptr) const
Returns color by value.
const ecvColor::Rgb * getColorByRelativePos (double relativePos, const ecvColor::Rgb *outOfRangeColor=nullptr) const
Returns color by relative position in scale.
const ecvColor::Rgb * getColorByRelativePos (double relativePos, unsigned steps, const ecvColor::Rgb *outOfRangeColor=nullptr) const
Returns color by relative position in scale with a given 'resolution'.
const ecvColor::Rgb & getColorByIndex (unsigned index) const
Returns color by index.
bool saveAsXML (QString filename) const
Saves this color scale as an XML file.
bool isSerializable () const override
Returns whether object is serializable of not.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Static Public Member Functions
static ccColorScale::Shared Create (const QString &name)
Creates a new color scale (with auto-generated unique id)
static Shared LoadFromXML (QString filename)
Loads a color scale from an XML file.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Static Public Attributes
static const unsigned MIN_STEPS = 2
Minimum number of steps.
static const unsigned DEFAULT_STEPS = 256
Default number of steps for display.
static const unsigned MAX_STEPS = 1024
Maximum number of steps (internal representation)
Protected Member Functions
void sort ()
Sort elements.
Protected Attributes
QString m_name
Name.
QString m_uuid
Unique ID.
QList< ccColorScaleElement > m_steps
Elements.
ecvColor::Rgb m_rgbaScale [MAX_STEPS]
Internal representation (RGB)
bool m_updated
Internal representation validity.
bool m_relative
Whether scale is relative or not.
bool m_locked
Whether scale is locked or not.
double m_absoluteMinValue
'Absolute' minimum value
double m_absoluteRange
'Absolute' range
LabelSet m_customLabels
List of custom labels.
Detailed Description
Color scale.
A color scale is defined by several 'steps' corresponding to given colors. The color between each step is linearly interpolated. A valid color scale must have at least 2 steps, one at relative position 0.0 (scale start) and one at relative position 1.0 (scale end). Steps can't be defined outside this interval.
For faster access, a array of interpolated colors is maintained internally. Be sure that the 'refresh' method has been called after any modification(s) of the scale steps (position or color).
Definition at line 71 of file ecvColorScale.h.
Member Typedef Documentation
LabelSet
using ccColorScale::LabelSet = std::set<Label>
Type of a list of custom labels.
Definition at line 160 of file ecvColorScale.h.
Shared
typedef QSharedPointer<ccColorScale> ccColorScale::Shared
Shared pointer type.
Definition at line 74 of file ecvColorScale.h.
Constructor & Destructor Documentation
ccColorScale()
ccColorScale::ccColorScale (const QString & name, const QString & uuid = QString())
Default constructor.
Parameters
name scale name
uuid UUID (automatically generated if none is provided) Scale are 'relative' by default (can be changed afterwards, see setAbsolute). On construction they already have the two extreme steps defined (at position 0.0 and 1.0).
~ccColorScale()
virtual ccColorScale::~ccColorScale () virtual
Destructor.
Member Function Documentation
clear()
void ccColorScale::clear ()
Clears all steps.
There should be at least 2 steps for the scale to be valid! Scale must not be locked.
Referenced by define_ccColorScale().
copy()
ccColorScale::Shared ccColorScale::copy (const QString & uuid = QString()) const
Creates a copy of this color scale (with a specified unique id)
Create()
static ccColorScale::Shared ccColorScale::Create (const QString & name) static
Creates a new color scale (with auto-generated unique id)
Warning: color scale is relative by default.
customLabels() [1/2]
LabelSet& ccColorScale::customLabels () inline
Returns the list of custom labels (if any)
Definition at line 163 of file ecvColorScale.h.
Referenced by define_ccColorScale().
customLabels() [2/2]
const LabelSet& ccColorScale::customLabels () const inline
Returns the list of custom labels (if any - const version)
Definition at line 165 of file ecvColorScale.h.
fromFile()
bool ccColorScale::fromFile (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override virtual
Loads data from binary stream.
Parameters
in input file (already opened)
dataVersion file version (for version-specific deserialization)
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Returns
success
Note: When implementing, use dataVersion checks to handle different
versions:
if (dataVersion >= X) { read new field } else { use default value } This ensures forward compatibility with older file formats.
Reimplemented from ccSerializableObject.
generateNewUuid()
void ccColorScale::generateNewUuid ()
Generates a new unique ID.
Referenced by define_ccColorScale().
getAbsoluteBoundaries()
void ccColorScale::getAbsoluteBoundaries (double & minVal, double & maxVal) const
Get absolute scale boundaries.
Warning: only valid with absolute scales!
getColorByIndex()
const ecvColor::Rgb& ccColorScale::getColorByIndex (unsigned index) const inline
Returns color by index.
Parameters
index color index in m_rgbaScale array (must be below MAX_STEPS)
Returns
corresponding color
Definition at line 278 of file ecvColorScale.h.
Referenced by define_ccColorScale().
getColorByRelativePos() [1/2]
const ecvColor::Rgb* ccColorScale::getColorByRelativePos (double relativePos, const ecvColor::Rgb * outOfRangeColor = nullptr) const inline
Returns color by relative position in scale.
Parameters
relativePos relative position (should be in [0;1])
outOfRangeColor default color to return if relativePos if out of [0;1]
Returns
corresponding color
Definition at line 241 of file ecvColorScale.h.
Referenced by define_ccColorScale().
getColorByRelativePos() [2/2]
const ecvColor::Rgb* ccColorScale::getColorByRelativePos (double relativePos, unsigned steps, const ecvColor::Rgb * outOfRangeColor = nullptr) const inline
Returns color by relative position in scale with a given 'resolution'.
Parameters
relativePos relative position (must be between 0 and 1!)
steps desired resolution (must be greater than 1 and smaller than MAX_STEPS)
outOfRangeColor default color to return if relativePos if out of [0;1]
Returns
corresponding color
Definition at line 258 of file ecvColorScale.h.
getColorByValue()
const ecvColor::Rgb* ccColorScale::getColorByValue (double value, const ecvColor::Rgb * outOfRangeColor = nullptr) const inline
Returns color by value.
Warning: only valid with absolute scales!
Parameters
value value
outOfRangeColor default color to return if relativePos if out of [0;1]
Returns
corresponding color
Definition at line 226 of file ecvColorScale.h.
Referenced by define_ccColorScale().
getName()
const QString& ccColorScale::getName () const inline
Returns name.
Definition at line 112 of file ecvColorScale.h.
Referenced by define_ccColorScale().
getRelativePosition()
double ccColorScale::getRelativePosition (double value) const inline
Returns relative position of a given value (wrt to scale absolute min and max) Warning: only valid with absolute scales! Use 'getColorByRelativePos' otherwise.
Definition at line 215 of file ecvColorScale.h.
Referenced by define_ccColorScale().
getUuid()
QString ccColorScale::getUuid () const inline
Returns unique ID.
Definition at line 117 of file ecvColorScale.h.
Referenced by define_ccColorScale().
insert()
void ccColorScale::insert (const ccColorScaleElement & step, bool autoUpdate = true)
Adds a step.
Scale must not be locked.
Referenced by define_ccColorScale().
isLocked()
bool ccColorScale::isLocked () const inline
Returns whether scale is locked or not.
Definition at line 140 of file ecvColorScale.h.
Referenced by define_ccColorScale().
isRelative()
bool ccColorScale::isRelative () const inline
Returns whether scale is relative or absoute.
Relative means that internal 'values' are percentage.
Definition at line 126 of file ecvColorScale.h.
Referenced by define_ccColorScale().
isSerializable()
bool ccColorScale::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccSerializableObject.
Definition at line 289 of file ecvColorScale.h.
LoadFromXML()
static Shared ccColorScale::LoadFromXML (QString filename) static
Loads a color scale from an XML file.
Referenced by define_ccColorScale().
minimumFileVersion()
short ccColorScale::minimumFileVersion () const override virtual
Returns the minimum file version required to save this instance.
To be overridden by subclasses to indicate their minimum required version. This enables the system to determine:
Forward compatibility: newer software can read older files (dataVersion check in fromFile)
Backward compatibility: determine minimum version needed to save current data
Returns
minimum file version required for this object
Implements ccSerializableObject.
remove()
void ccColorScale::remove (int index, bool autoUpdate = true)
Deletes a given step.
The first and last index shouldn't be deleted! Scale must not be locked.
Referenced by define_ccColorScale().
saveAsXML()
bool ccColorScale::saveAsXML (QString filename) const
Saves this color scale as an XML file.
Referenced by define_ccColorScale().
setAbsolute()
void ccColorScale::setAbsolute (double minVal, double maxVal)
Sets scale as absolute.
Referenced by define_ccColorScale().
setCustomLabels()
void ccColorScale::setCustomLabels (const LabelSet & labels) inline
Sets the list of custom labels (only if the scale is absolute)
Warning
May throw std::bad_alloc exception)
Definition at line 170 of file ecvColorScale.h.
Referenced by define_ccColorScale().
setLocked()
void ccColorScale::setLocked (bool state) inline
Sets whether scale is locked or not.
Definition at line 143 of file ecvColorScale.h.
Referenced by define_ccColorScale().
setName()
void ccColorScale::setName (const QString & name) inline
Sets name.
Definition at line 114 of file ecvColorScale.h.
References name.
Referenced by define_ccColorScale().
setRelative()
void ccColorScale::setRelative () inline
Sets scale as relative.
Definition at line 129 of file ecvColorScale.h.
Referenced by define_ccColorScale().
setUuid()
void ccColorScale::setUuid (QString uuid) inline
Sets unique ID.
Definition at line 119 of file ecvColorScale.h.
Referenced by define_ccColorScale().
sort()
void ccColorScale::sort () protected
Sort elements.
step() [1/2]
ccColorScaleElement& ccColorScale::step (int index) inline
Access to a given step.
Definition at line 180 of file ecvColorScale.h.
Referenced by define_ccColorScale().
step() [2/2]
const ccColorScaleElement& ccColorScale::step (int index) const inline
Access to a given step (const)
Definition at line 183 of file ecvColorScale.h.
stepCount()
int ccColorScale::stepCount () const inline
Returns the current number of steps.
A valid scale should always have at least 2 steps!
Definition at line 177 of file ecvColorScale.h.
Referenced by define_ccColorScale().
toFile()
bool ccColorScale::toFile (QFile & out, short dataVersion) const override virtual
Saves data to binary stream.
Parameters
out output file (already opened)
dataVersion target file version (for forward/backward compatibility)
Returns
success
Reimplemented from ccSerializableObject.
update()
void ccColorScale::update ()
Updates internal representation.
Must be called at least once after any modification (before using this scale).
Referenced by define_ccColorScale().
Member Data Documentation
DEFAULT_STEPS
const unsigned ccColorScale::DEFAULT_STEPS = 256 static
Default number of steps for display.
Warning
Never pass a 'constant initializer' by reference
Definition at line 104 of file ecvColorScale.h.
Referenced by define_ccColorScale().
m_absoluteMinValue
double ccColorScale::m_absoluteMinValue protected
'Absolute' minimum value
Only used if scale is 'absolute' (i.e. not relative). 'Absolute' should not be taken in its mathematical meaning!
Definition at line 326 of file ecvColorScale.h.
m_absoluteRange
double ccColorScale::m_absoluteRange protected
'Absolute' range
Only used if scale is 'absolute' (i.e. not relative). 'Absolute' should not be taken in its mathematical meaning!
Definition at line 332 of file ecvColorScale.h.
m_customLabels
LabelSet ccColorScale::m_customLabels protected
List of custom labels.
Definition at line 335 of file ecvColorScale.h.
m_locked
bool ccColorScale::m_locked protected
Whether scale is locked or not.
Definition at line 320 of file ecvColorScale.h.
m_name
QString ccColorScale::m_name protected
Name.
Definition at line 302 of file ecvColorScale.h.
m_relative
bool ccColorScale::m_relative protected
Whether scale is relative or not.
Definition at line 317 of file ecvColorScale.h.
m_rgbaScale
ecvColor::Rgb ccColorScale::m_rgbaScale[MAX_STEPS] protected
Internal representation (RGB)
Definition at line 311 of file ecvColorScale.h.
m_steps
QList<ccColorScaleElement> ccColorScale::m_steps protected
Elements.
Definition at line 308 of file ecvColorScale.h.
m_updated
bool ccColorScale::m_updated protected
Internal representation validity.
Definition at line 314 of file ecvColorScale.h.
m_uuid
QString ccColorScale::m_uuid protected
Unique ID.
Definition at line 305 of file ecvColorScale.h.
MAX_STEPS
const unsigned ccColorScale::MAX_STEPS = 1024 static
Maximum number of steps (internal representation)
Warning
Never pass a 'constant initializer' by reference
Definition at line 109 of file ecvColorScale.h.
Referenced by define_ccColorScale(), DistanceMapGenerationDlg::DistanceMapGenerationDlg(), and StereogramDialog::StereogramDialog().
MIN_STEPS
const unsigned ccColorScale::MIN_STEPS = 2 static
Minimum number of steps.
Warning
Never pass a 'constant initializer' by reference
Definition at line 99 of file ecvColorScale.h.
Referenced by define_ccColorScale(), DistanceMapGenerationDlg::DistanceMapGenerationDlg(), StereogramDialog::onDensityColorStepsChanged(), and StereogramDialog::StereogramDialog().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvColorScale.h