ACloudViewer: cloudViewer::VisualizerForAlignment Class Reference
cloudViewer::VisualizerForAlignment Class Reference
#include <VisualizerForAlignment.h>
Public Member Functions
VisualizerForAlignment (visualization::VisualizerWithEditing &source, visualization::VisualizerWithEditing &target, double voxel_size=-1.0, double max_correspondence_distance=-1.0, bool with_scaling=true, bool use_dialog=true, const std::string &polygon_filename="", const std::string &directory="")
~VisualizerForAlignment () override
void PrintVisualizerHelp () override
bool AddSourceAndTarget (std::shared_ptr< ccPointCloud > source, std::shared_ptr< ccPointCloud > target)
Public Member Functions inherited from cloudViewer::visualization::Visualizer
Visualizer ()
virtual ~Visualizer ()
Visualizer (Visualizer &&)=delete
Visualizer (const Visualizer &)=delete
Visualizer & operator= (const Visualizer &)=delete
bool CreateVisualizerWindow (const std::string &window_name="CloudViewer", const int width=640, const int height=480, const int left=50, const int top=50, const bool visible=true)
Function to create a window and initialize GLFW.
void DestroyVisualizerWindow ()
Function to destroy a window.
void RegisterAnimationCallback (std::function< bool(Visualizer *)> callback_func)
Function to register a callback function for animation.
void Run ()
Function to activate the window.
void Close ()
Function to to notify the window to be closed.
bool WaitEvents ()
Function to process the event queue and return if the window is closed.
bool PollEvents ()
virtual bool AddGeometry (std::shared_ptr< const ccHObject > geometry_ptr, bool reset_bounding_box=true)
Function to add geometry to the scene and create corresponding shaders.
virtual bool RemoveGeometry (std::shared_ptr< const ccHObject > geometry_ptr, bool reset_bounding_box=true)
Function to remove geometry from the scene.
virtual bool ClearGeometries ()
virtual bool UpdateGeometry (std::shared_ptr< const ccHObject > geometry_ptr=nullptr)
Function to update geometry.
virtual bool HasGeometry () const
virtual void UpdateRender ()
Function to inform render needed to be updated.
virtual void SetFullScreen (bool fullscreen)
Functions to change between fullscreen and windowed modes.
virtual void ToggleFullScreen ()
virtual bool IsFullScreen ()
virtual void UpdateWindowTitle ()
virtual void BuildUtilities ()
ViewControl & GetViewControl ()
Function to retrieve the associated ViewControl.
RenderOption & GetRenderOption ()
Function to retrieve the associated RenderOption.
std::shared_ptr< geometry::Image > CaptureScreenFloatBuffer (bool do_render=true)
Function to capture screen and store RGB in a float buffer.
void CaptureScreenImage (const std::string &filename="", bool do_render=true)
Function to capture and save a screen image.
std::shared_ptr< geometry::Image > CaptureDepthFloatBuffer (bool do_render=true)
void CaptureDepthImage (const std::string &filename="", bool do_render=true, double depth_scale=1000.0)
void CaptureDepthPointCloud (const std::string &filename="", bool do_render=true, bool convert_to_world_coordinate=false)
Function to capture and save local point cloud.
void CaptureRenderOption (const std::string &filename="")
void ResetViewPoint (bool reset_bounding_box=false)
Function to reset view point.
const std::string & GetWindowName () const
Protected Member Functions
void KeyPressCallback (GLFWwindow *window, int key, int scancode, int action, int mods) override
bool SaveSessionToFile (const std::string &filename)
bool LoadSessionFromFile (const std::string &filename)
bool AlignWithManualAnnotation ()
void PrintTransformation ()
void EvaluateAlignmentAndSave (const std::string &filename)
Protected Member Functions inherited from cloudViewer::visualization::Visualizer
virtual bool InitOpenGL ()
Function to initialize OpenGL.
virtual bool InitViewControl ()
Function to initialize ViewControl.
virtual bool InitRenderOption ()
Function to initialize RenderOption.
virtual void Render (bool render_screen=false)
void CopyViewStatusToClipboard ()
void CopyViewStatusFromClipboard ()
virtual void WindowRefreshCallback (GLFWwindow *window)
virtual void WindowResizeCallback (GLFWwindow *window, int w, int h)
virtual void MouseMoveCallback (GLFWwindow *window, double x, double y)
virtual void MouseScrollCallback (GLFWwindow *window, double x, double y)
virtual void MouseButtonCallback (GLFWwindow *window, int button, int action, int mods)
virtual void WindowCloseCallback (GLFWwindow *window)
Function to notify the window to be closed.
Protected Attributes
visualization::VisualizerWithEditing & source_visualizer_
visualization::VisualizerWithEditing & target_visualizer_
double voxel_size_ = -1.0
double max_correspondence_distance_ = -1.0
bool with_scaling_ = true
bool use_dialog_ = true
Eigen::Matrix4d transformation_ = Eigen::Matrix4d::Identity()
std::string polygon_filename_ = ""
std::shared_ptr< ccPointCloud > source_copy_ptr_
std::shared_ptr< ccPointCloud > target_copy_ptr_
AlignmentSession alignment_session_
std::string default_directory_
Protected Attributes inherited from cloudViewer::visualization::Visualizer
GLFWwindow * window_ = nullptr
std::string window_name_ = "CloudViewer"
std::shared_ptr< GLFWContext > glfw_context_ = nullptr
Shared GLFW context.
Eigen::Vector2i saved_window_size_ = Eigen::Vector2i::Zero()
Eigen::Vector2i saved_window_pos_ = Eigen::Vector2i::Zero()
std::function< bool(Visualizer *)> animation_callback_func_ = nullptr
std::function< bool(Visualizer *)> animation_callback_func_in_loop_
MouseControl mouse_control_
bool is_redraw_required_ = true
bool is_initialized_ = false
GLuint vao_id_ = 0
GLuint render_fbo_ = 0
GLuint render_rgb_tex_ = 0
GLuint render_depth_stencil_rbo_ = 0
std::unique_ptr< ViewControl > view_control_ptr_
std::unique_ptr< RenderOption > render_option_ptr_
std::unordered_set< std::shared_ptr< const ccHObject > > geometry_ptrs_
std::unordered_set< std::shared_ptr< glsl::GeometryRenderer > > geometry_renderer_ptrs_
std::vector< std::shared_ptr< const ccHObject > > utility_ptrs_
std::vector< std::shared_ptr< glsl::GeometryRenderer > > utility_renderer_ptrs_
std::unordered_map< std::shared_ptr< glsl::GeometryRenderer >, RenderOption > utility_renderer_opts_
std::shared_ptr< ccMesh > coordinate_frame_mesh_ptr_
std::shared_ptr< glsl::CoordinateFrameRenderer > coordinate_frame_mesh_renderer_ptr_
Detailed Description
Definition at line 27 of file VisualizerForAlignment.h.
Constructor & Destructor Documentation
VisualizerForAlignment()
cloudViewer::VisualizerForAlignment::VisualizerForAlignment (visualization::VisualizerWithEditing & source, visualization::VisualizerWithEditing & target, double voxel_size = -1.0, double max_correspondence_distance = -1.0, bool with_scaling = true, bool use_dialog = true, const std::string & polygon_filename = "", const std::string & directory = "") inline
Definition at line 29 of file VisualizerForAlignment.h.
~VisualizerForAlignment()
cloudViewer::VisualizerForAlignment::~VisualizerForAlignment () inline override
Definition at line 45 of file VisualizerForAlignment.h.
Member Function Documentation
AddSourceAndTarget()
bool cloudViewer::VisualizerForAlignment::AddSourceAndTarget (std::shared_ptr< ccPointCloud > source, std::shared_ptr< ccPointCloud > target)
Definition at line 31 of file VisualizerForAlignment.cpp.
References cloudViewer::visualization::Visualizer::AddGeometry(), alignment_session_, cloudViewer::visualization::Visualizer::GetRenderOption(), cloudViewer::visualization::RenderOption::point_size_, source_copy_ptr_, cloudViewer::AlignmentSession::source_ptr_, target_copy_ptr_, and cloudViewer::AlignmentSession::target_ptr_.
Referenced by main().
AlignWithManualAnnotation()
bool cloudViewer::VisualizerForAlignment::AlignWithManualAnnotation () protected
Definition at line 267 of file VisualizerForAlignment.cpp.
References alignment_session_, cloudViewer::pipelines::registration::TransformationEstimationPointToPoint::ComputeRMSE(), cloudViewer::pipelines::registration::TransformationEstimationPointToPoint::ComputeTransformation(), cloudViewer::visualization::VisualizerWithEditing::GetPickedPoints(), LogInfo, LogWarning, PrintTransformation(), source_copy_ptr_, cloudViewer::AlignmentSession::source_ptr_, source_visualizer_, cloudViewer::AlignmentSession::target_ptr_, target_visualizer_, transformation_, and with_scaling_.
Referenced by KeyPressCallback().
EvaluateAlignmentAndSave()
void cloudViewer::VisualizerForAlignment::EvaluateAlignmentAndSave (const std::string & filename) protected
Definition at line 315 of file VisualizerForAlignment.cpp.
References filename, cloudViewer::utility::filesystem::FOpen(), cloudViewer::utility::filesystem::GetFileNameWithoutExtension(), LogError, source_copy_ptr_, target_copy_ptr_, and cloudViewer::io::WritePointCloud().
Referenced by KeyPressCallback().
KeyPressCallback()
void cloudViewer::VisualizerForAlignment::KeyPressCallback (GLFWwindow * window, int key, int scancode, int action, int mods) override protected virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 44 of file VisualizerForAlignment.cpp.
References alignment_session_, AlignWithManualAnnotation(), default_directory_, e, EvaluateAlignmentAndSave(), cloudViewer::utility::filesystem::FileExists(), filename, format, cloudViewer::visualization::Visualizer::KeyPressCallback(), LoadSessionFromFile(), LogError, LogInfo, LogWarning, max_correspondence_distance_, polygon_filename_, PrintTransformation(), cloudViewer::io::ReadIJsonConvertible(), cloudViewer::pipelines::registration::RegistrationICP(), cloudViewer::visualization::Visualizer::ResetViewPoint(), result, SaveSessionToFile(), source_copy_ptr_, cloudViewer::AlignmentSession::source_ptr_, target_copy_ptr_, cloudViewer::AlignmentSession::target_ptr_, transformation_, cloudViewer::visualization::Visualizer::UpdateGeometry(), use_dialog_, and voxel_size_.
LoadSessionFromFile()
bool cloudViewer::VisualizerForAlignment::LoadSessionFromFile (const std::string & filename) protected
Definition at line 248 of file VisualizerForAlignment.cpp.
References alignment_session_, filename, cloudViewer::visualization::VisualizerWithEditing::GetPickedPoints(), cloudViewer::AlignmentSession::max_correspondence_distance_, max_correspondence_distance_, cloudViewer::io::ReadIJsonConvertible(), cloudViewer::visualization::Visualizer::ResetViewPoint(), source_copy_ptr_, cloudViewer::AlignmentSession::source_indices_, cloudViewer::AlignmentSession::source_ptr_, source_visualizer_, cloudViewer::AlignmentSession::target_indices_, target_visualizer_, cloudViewer::AlignmentSession::transformation_, transformation_, cloudViewer::visualization::Visualizer::UpdateGeometry(), cloudViewer::visualization::Visualizer::UpdateRender(), cloudViewer::AlignmentSession::voxel_size_, voxel_size_, cloudViewer::AlignmentSession::with_scaling_, and with_scaling_.
Referenced by KeyPressCallback().
PrintTransformation()
void cloudViewer::VisualizerForAlignment::PrintTransformation () protected
Definition at line 299 of file VisualizerForAlignment.cpp.
References LogInfo, and transformation_.
Referenced by AlignWithManualAnnotation(), and KeyPressCallback().
PrintVisualizerHelp()
void cloudViewer::VisualizerForAlignment::PrintVisualizerHelp () override virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 16 of file VisualizerForAlignment.cpp.
References LogInfo, and cloudViewer::visualization::Visualizer::PrintVisualizerHelp().
SaveSessionToFile()
bool cloudViewer::VisualizerForAlignment::SaveSessionToFile (const std::string & filename) protected
Definition at line 237 of file VisualizerForAlignment.cpp.
References alignment_session_, filename, cloudViewer::visualization::VisualizerWithEditing::GetPickedPoints(), cloudViewer::AlignmentSession::max_correspondence_distance_, max_correspondence_distance_, cloudViewer::AlignmentSession::source_indices_, source_visualizer_, cloudViewer::AlignmentSession::target_indices_, target_visualizer_, cloudViewer::AlignmentSession::transformation_, transformation_, cloudViewer::AlignmentSession::voxel_size_, voxel_size_, cloudViewer::AlignmentSession::with_scaling_, with_scaling_, and cloudViewer::io::WriteIJsonConvertible().
Referenced by KeyPressCallback().
Member Data Documentation
alignment_session_
AlignmentSession cloudViewer::VisualizerForAlignment::alignment_session_ protected
Definition at line 75 of file VisualizerForAlignment.h.
Referenced by AddSourceAndTarget(), AlignWithManualAnnotation(), KeyPressCallback(), LoadSessionFromFile(), and SaveSessionToFile().
default_directory_
std::string cloudViewer::VisualizerForAlignment::default_directory_ protected
Definition at line 76 of file VisualizerForAlignment.h.
Referenced by KeyPressCallback().
max_correspondence_distance_
double cloudViewer::VisualizerForAlignment::max_correspondence_distance_ = -1.0 protected
Definition at line 68 of file VisualizerForAlignment.h.
Referenced by KeyPressCallback(), LoadSessionFromFile(), and SaveSessionToFile().
polygon_filename_
std::string cloudViewer::VisualizerForAlignment::polygon_filename_ = "" protected
Definition at line 72 of file VisualizerForAlignment.h.
Referenced by KeyPressCallback().
source_copy_ptr_
std::shared_ptr<ccPointCloud> cloudViewer::VisualizerForAlignment::source_copy_ptr_ protected
Definition at line 73 of file VisualizerForAlignment.h.
Referenced by AddSourceAndTarget(), AlignWithManualAnnotation(), EvaluateAlignmentAndSave(), KeyPressCallback(), and LoadSessionFromFile().
source_visualizer_
visualization::VisualizerWithEditing& cloudViewer::VisualizerForAlignment::source_visualizer_ protected
Definition at line 65 of file VisualizerForAlignment.h.
Referenced by AlignWithManualAnnotation(), LoadSessionFromFile(), and SaveSessionToFile().
target_copy_ptr_
std::shared_ptr<ccPointCloud> cloudViewer::VisualizerForAlignment::target_copy_ptr_ protected
Definition at line 74 of file VisualizerForAlignment.h.
Referenced by AddSourceAndTarget(), EvaluateAlignmentAndSave(), and KeyPressCallback().
target_visualizer_
visualization::VisualizerWithEditing& cloudViewer::VisualizerForAlignment::target_visualizer_ protected
Definition at line 66 of file VisualizerForAlignment.h.
Referenced by AlignWithManualAnnotation(), LoadSessionFromFile(), and SaveSessionToFile().
transformation_
Eigen::Matrix4d cloudViewer::VisualizerForAlignment::transformation_ = Eigen::Matrix4d::Identity() protected
Definition at line 71 of file VisualizerForAlignment.h.
Referenced by AlignWithManualAnnotation(), KeyPressCallback(), LoadSessionFromFile(), PrintTransformation(), and SaveSessionToFile().
use_dialog_
bool cloudViewer::VisualizerForAlignment::use_dialog_ = true protected
Definition at line 70 of file VisualizerForAlignment.h.
Referenced by KeyPressCallback().
voxel_size_
double cloudViewer::VisualizerForAlignment::voxel_size_ = -1.0 protected
Definition at line 67 of file VisualizerForAlignment.h.
Referenced by KeyPressCallback(), LoadSessionFromFile(), and SaveSessionToFile().
with_scaling_
bool cloudViewer::VisualizerForAlignment::with_scaling_ = true protected
Definition at line 69 of file VisualizerForAlignment.h.
Referenced by AlignWithManualAnnotation(), LoadSessionFromFile(), and SaveSessionToFile().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVViewer/tools/ManuallyAlignPointCloud/VisualizerForAlignment.h
/root/ACloudViewer/libs/CVViewer/tools/ManuallyAlignPointCloud/VisualizerForAlignment.cpp