ACloudViewer: Classify3DMASCDialog Class Reference
Classify3DMASCDialog Class Reference
3DMASC plugin 'classify' dialog
#include <qClassify3DMASCDialog.h>
Public Member Functions
Classify3DMASCDialog (ecvMainAppInterface *app, bool trainMode=false)
Default constructor.
~Classify3DMASCDialog ()
void readSettings ()
read settings
void writeSettings ()
write settings
void setCloudRoles (const QList< QString > &roles, QString &corePointsLabel, const QMap< QString, QString > &rolesAndNames)
Sets the clouds roles.
void setComboBoxIndex (const QMap< QString, QString > &rolesAndNames, QLabel *label, const QMap< QString, QVariant > &namesAndUniqueIds, QComboBox *comboBox)
void getClouds (QMap< QString, ccPointCloud * > &clouds) const
Returns the selected point clouds.
Protected Slots
void onCloudChanged (int)
Protected Attributes
ecvMainAppInterface * m_app
Gives access to the application (data-base, UI, etc.)
Detailed Description
3DMASC plugin 'classify' dialog
Definition at line 36 of file qClassify3DMASCDialog.h.
Constructor & Destructor Documentation
Classify3DMASCDialog()
Classify3DMASCDialog::Classify3DMASCDialog (ecvMainAppInterface * app, bool trainMode = false)
Default constructor.
Definition at line 44 of file qClassify3DMASCDialog.cpp.
References m_app, name, onCloudChanged(), CV_TYPES::POINT_CLOUD, and readSettings().
~Classify3DMASCDialog()
Classify3DMASCDialog::~Classify3DMASCDialog ()
Definition at line 113 of file qClassify3DMASCDialog.cpp.
References writeSettings().
Member Function Documentation
getClouds()
void Classify3DMASCDialog::getClouds (QMap< QString, ccPointCloud * > & clouds) const
Returns the selected point clouds.
Definition at line 235 of file qClassify3DMASCDialog.cpp.
References GetCloudFromCombo(), and m_app.
Referenced by q3DMASCPlugin::doClassifyAction(), and q3DMASCPlugin::doTrainAction().
onCloudChanged
void Classify3DMASCDialog::onCloudChanged (int dummy) protected slot
Definition at line 268 of file qClassify3DMASCDialog.cpp.
Referenced by Classify3DMASCDialog().
readSettings()
void Classify3DMASCDialog::readSettings ()
read settings
Definition at line 115 of file qClassify3DMASCDialog.cpp.
Referenced by Classify3DMASCDialog().
setCloudRoles()
void Classify3DMASCDialog::setCloudRoles (const QList< QString > & roles, QString & corePointsLabel, const QMap< QString, QString > & rolesAndNames)
Sets the clouds roles.
Definition at line 147 of file qClassify3DMASCDialog.cpp.
References m_app, CV_TYPES::POINT_CLOUD, and setComboBoxIndex().
Referenced by q3DMASCPlugin::doClassifyAction(), and q3DMASCPlugin::doTrainAction().
setComboBoxIndex()
void Classify3DMASCDialog::setComboBoxIndex (const QMap< QString, QString > & rolesAndNames, QLabel * label, const QMap< QString, QVariant > & namesAndUniqueIds, QComboBox * comboBox)
Preset the combo boxes if possible with the names specified in the parameter file
Definition at line 128 of file qClassify3DMASCDialog.cpp.
References name.
Referenced by setCloudRoles().
writeSettings()
void Classify3DMASCDialog::writeSettings ()
write settings
Definition at line 122 of file qClassify3DMASCDialog.cpp.
Referenced by ~Classify3DMASCDialog().
Member Data Documentation
m_app
ecvMainAppInterface* Classify3DMASCDialog::m_app protected
Gives access to the application (data-base, UI, etc.)
Definition at line 70 of file qClassify3DMASCDialog.h.
Referenced by Classify3DMASCDialog(), getClouds(), and setCloudRoles().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/q3DMASC/qClassify3DMASCDialog.h
/root/ACloudViewer/plugins/core/Standard/q3DMASC/qClassify3DMASCDialog.cpp