ACloudViewer: MascaretFilter Class Reference
MascaretFilter Class Reference
Mascaret profile I/O filter.
#include <MascaretFilter.h>
Public Member Functions
MascaretFilter ()
virtual bool canSave (CV_CLASS_ENUM type, bool &multiple, bool &exclusive) const override
Returns whether this I/O filter can save the specified type of entity.
virtual CC_FILE_ERROR saveToFile (ccHObject *entity, const QString &filename, const SaveParameters &parameters) override
Saves an entity (or a group of) to a file.
Public Member Functions inherited from FileIOFilter
virtual ~FileIOFilter ()=default
bool importSupported () const
Returns whether this I/O filter can import files.
bool exportSupported () const
Returns whether this I/O filter can export files.
const QStringList & getFileFilters (bool onImport) const
Returns the file filter(s) for this I/O filter.
QString getDefaultExtension () const
Returns the default file extension.
virtual CC_FILE_ERROR loadFile (const QString &filename, ccHObject &container, LoadParameters &parameters)
Loads one or more entities from a file.
virtual void unregister ()
Called when the filter is unregistered.
Additional Inherited Members
Public Types inherited from FileIOFilter
enum FilterFeature {
NoFeatures = 0x0000 , Import = 0x00001 , Export = 0x0002 , BuiltIn = 0x0004 ,
DynamicInfo = 0x0008
}
using Shared = QSharedPointer< FileIOFilter >
Shared type.
using FilterContainer = std::vector< FileIOFilter::Shared >
Type of a I/O filters container.
Static Public Member Functions inherited from FileIOFilter
static QStringList ImportFilterList ()
static ccHObject * LoadFromFile (const QString &filename, LoadParameters &parameters, Shared filter, CC_FILE_ERROR &result)
Loads one or more entities from a file with a known filter.
static ccHObject * LoadFromFile (const QString &filename, LoadParameters &parameters, CC_FILE_ERROR &result, const QString &fileFilter=QString())
Loads one or more entities from a file with known type.
static CC_FILE_ERROR SaveToFile (ccHObject *entities, const QString &filename, const SaveParameters &parameters, Shared filter)
static CC_FILE_ERROR SaveToFile (ccHObject *entities, const QString &filename, const SaveParameters &parameters, const QString &fileFilter)
static bool HandleGlobalShift (const CCVector3d &P, CCVector3d &Pshift, bool &preserveCoordinateShift, LoadParameters &loadParameters, bool useInputCoordinatesShiftIfPossible=false)
Shortcut to the ecvGlobalShiftManager mechanism specific for files.
static void DisplayErrorMessage (CC_FILE_ERROR err, const QString &action, const QString &filename)
Displays (to console) the message corresponding to a given error code.
static bool CheckForSpecialChars (const QString &filename)
Returns whether special characters are present in the input string.
static void ResetSesionCounter ()
static unsigned IncreaseSesionCounter ()
static void Register (Shared filter)
Registers a new filter.
static Shared GetFilter (const QString &fileFilter, bool onImport)
Returns the filter corresponding to the given 'file filter'.
static Shared FindBestFilterForExtension (const QString &ext)
Returns the best filter (presumably) to open a given file extension.
static const FilterContainer & GetFilters ()
Returns the set of all registered filters.
static void UnregisterAll ()
Unregisters all filters.
Protected Member Functions inherited from FileIOFilter
FileIOFilter (const FilterInfo &info)
void setImportExtensions (const QStringList &extensions)
void setImportFileFilterStrings (const QStringList &filterStrings)
void setExportFileFilterStrings (const QStringList &filterStrings)
Static Protected Attributes inherited from FileIOFilter
static constexpr float DEFAULT_PRIORITY = 25.0f
Detailed Description
Mascaret profile I/O filter.
See http://www.opentelemac.org/
Definition at line 15 of file MascaretFilter.h.
Constructor & Destructor Documentation
MascaretFilter()
MascaretFilter::MascaretFilter ()
Definition at line 38 of file MascaretFilter.cpp.
References FileIOFilter::DEFAULT_PRIORITY, and FileIOFilter::Export.
Member Function Documentation
canSave()
bool MascaretFilter::canSave (CV_CLASS_ENUM type, bool & multiple, bool & exclusive) const override virtual
Returns whether this I/O filter can save the specified type of entity.
Parameters
type entity type
multiple whether the filter can save multiple instances of this entity at once
exclusive whether the filter can only save this type of entity if selected or if it can be mixed with other types
Returns
whether the entity type can be saved
Reimplemented from FileIOFilter.
Definition at line 45 of file MascaretFilter.cpp.
References CV_TYPES::POLY_LINE, and type.
saveToFile()
CC_FILE_ERROR MascaretFilter::saveToFile (ccHObject * entity, const QString & filename, const SaveParameters & parameters) override virtual
Saves an entity (or a group of) to a file.
This method must be implemented by children classes.
Parameters
entity entity (or group of) to save
filename filename
parameters generic saving parameters
Returns
error
Reimplemented from FileIOFilter.
Definition at line 75 of file MascaretFilter.cpp.
References CC_FERR_BAD_ARGUMENT, CC_FERR_CANCELED_BY_USER, CC_FERR_NO_ERROR, CC_FERR_NO_SAVE, CC_FERR_NOT_ENOUGH_MEMORY, CC_FERR_WRITING, QtCompat::endl(), Vector3Tpl< PointCoordinateType >::fromArray(), ccHObject::getChild(), ccHObject::getChildrenNumber(), ccObject::getMetaData(), ccObject::getName(), cloudViewer::ReferenceCloud::getPoint(), ccObject::hasMetaData(), CV_TYPES::HIERARCHY_OBJECT, ccObject::isA(), MakeMascaretName(), ccPolyline::MetaKeyAbscissa(), ccPolyline::MetaKeyPrefixCenter(), ccPolyline::MetaKeyPrefixDirection(), ccPolyline::MetaKeyUpDir(), Vector3Tpl< Type >::normalize(), CV_TYPES::POLY_LINE, result, cloudViewer::ReferenceCloud::size(), std::swap(), ccShiftedObject::toGlobal3d(), ToLocalAbscissa(), type, Tuple3Tpl< Type >::u, CVLog::Warning(), Vector2Tpl< Type >::x, Tuple3Tpl< Type >::x, Vector2Tpl< Type >::y, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/MascaretFilter.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/MascaretFilter.cpp