ACloudViewer: cloudViewer::visualization::gui::CheckableTextTreeCell Class Reference
cloudViewer::visualization::gui::CheckableTextTreeCell Class Reference
#include <TreeView.h>
Classes
struct Impl
Public Member Functions
CheckableTextTreeCell (const char *text, bool is_checked, std::function< void(bool)> on_toggled)
~CheckableTextTreeCell ()
std::shared_ptr< Checkbox > GetCheckbox ()
std::shared_ptr< Label > GetLabel ()
Size CalcPreferredSize (const LayoutContext &context, const Constraints &constraints) const override
void Layout (const LayoutContext &context) override
Public Member Functions inherited from cloudViewer::visualization::gui::Widget
Widget ()
Widget (const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Widget ()
virtual void AddChild (std::shared_ptr< Widget > child)
virtual const std::vector< std::shared_ptr< Widget > > GetChildren () const
virtual const Rect & GetFrame () const
Returns the frame size in pixels.
virtual void SetFrame (const Rect &f)
virtual const Color & GetBackgroundColor () const
virtual bool IsDefaultBackgroundColor () const
virtual void SetBackgroundColor (const Color &color)
virtual bool IsVisible () const
virtual void SetVisible (bool vis)
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
virtual void SetTooltip (const char *text)
virtual const char * GetTooltip () const
virtual Size CalcMinimumSize (const LayoutContext &context) const
virtual DrawResult Draw (const DrawContext &context)
virtual EventResult Mouse (const MouseEvent &e)
virtual EventResult Key (const KeyEvent &e)
virtual DrawResult Tick (const TickEvent &e)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::gui::Widget
enum class DrawResult { NONE , REDRAW , RELAYOUT }
enum class EventResult { IGNORED , CONSUMED , DISCARD }
Static Public Attributes inherited from cloudViewer::visualization::gui::Widget
static constexpr int DIM_GROW = 10000
Protected Member Functions inherited from cloudViewer::visualization::gui::Widget
void DrawImGuiPushEnabledState ()
void DrawImGuiPopEnabledState ()
void DrawImGuiTooltip ()
Detailed Description
The only difference between just putting in a Checkbox with TreeView::AddItem() is that with a Checkbox, clicking on the text will toggle on/off, whereas with this you must click on the checkbox; clicking on the text will open/close the children (if any, and if CanSelectItemsWithChildren is false).
Definition at line 28 of file TreeView.h.
Constructor & Destructor Documentation
CheckableTextTreeCell()
cloudViewer::visualization::gui::CheckableTextTreeCell::CheckableTextTreeCell (const char * text, bool is_checked, std::function< void(bool)> on_toggled)
Definition at line 33 of file TreeView.cpp.
References cloudViewer::visualization::gui::Widget::AddChild().
~CheckableTextTreeCell()
cloudViewer::visualization::gui::CheckableTextTreeCell::~CheckableTextTreeCell ()
Definition at line 47 of file TreeView.cpp.
Member Function Documentation
CalcPreferredSize()
Size cloudViewer::visualization::gui::CheckableTextTreeCell::CalcPreferredSize (const LayoutContext & context, const Constraints & constraints) const override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 57 of file TreeView.cpp.
References context, and max().
GetCheckbox()
std::shared_ptr< Checkbox > cloudViewer::visualization::gui::CheckableTextTreeCell::GetCheckbox ()
Definition at line 49 of file TreeView.cpp.
Referenced by cloudViewer::visualization::gui::pybind_gui_classes().
GetLabel()
std::shared_ptr< Label > cloudViewer::visualization::gui::CheckableTextTreeCell::GetLabel ()
Definition at line 53 of file TreeView.cpp.
Referenced by cloudViewer::visualization::gui::pybind_gui_classes().
Layout()
void cloudViewer::visualization::gui::CheckableTextTreeCell::Layout (const LayoutContext & context) override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 65 of file TreeView.cpp.
References context, frame, and cloudViewer::visualization::gui::Widget::GetFrame().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/TreeView.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/TreeView.cpp