ACloudViewer: qCanupoTrainingDialog Class Reference
qCanupoTrainingDialog Class Reference
CANUPO plugin's training dialog.
#include <qCanupoTrainingDialog.h>
Public Member Functions
qCanupoTrainingDialog (ecvMainAppInterface *app)
Default constructor.
ccPointCloud * getOriginPointCloud ()
Get origin point cloud.
ccPointCloud * getClass1Cloud ()
Get class #1 point cloud.
ccPointCloud * getClass2Cloud ()
Get class #2 point cloud.
ccPointCloud * getEvaluationCloud ()
Get evaluation point cloud.
void loadParamsFromPersistentSettings ()
Loads parameters from persistent settings.
void saveParamsToPersistentSettings ()
Saves parameters to persistent settings.
bool getScales (std::vector< float > &scales) const
Returns input scales.
int getMaxThreadCount () const
Returns the max number of threads to use.
unsigned getDescriptorID () const
Returns the selected descriptor ID.
Protected Slots
void onClassChanged (int)
void onCloudChanged (int)
Protected Member Functions
bool validParameters () const
Protected Attributes
ecvMainAppInterface * m_app
Gives access to the application (data-base, UI, etc.)
Detailed Description
CANUPO plugin's training dialog.
Definition at line 16 of file qCanupoTrainingDialog.h.
Constructor & Destructor Documentation
qCanupoTrainingDialog()
qCanupoTrainingDialog::qCanupoTrainingDialog (ecvMainAppInterface * app)
Default constructor.
Definition at line 32 of file qCanupoTrainingDialog.cpp.
References ScaleParamsComputer::AvailableCount(), count, ScaleParamsComputer::GetByIndex(), qCanupoTools::GetEntityName(), ScaleParamsComputer::getID(), ScaleParamsComputer::getName(), loadParamsFromPersistentSettings(), m_app, name, onClassChanged(), onCloudChanged(), and CV_TYPES::POINT_CLOUD.
Member Function Documentation
getClass1Cloud()
ccPointCloud * qCanupoTrainingDialog::getClass1Cloud ()
Get class #1 point cloud.
Definition at line 179 of file qCanupoTrainingDialog.cpp.
References qCanupoTools::GetCloudFromCombo(), and m_app.
Referenced by qCanupoPlugin::doTrainAction().
getClass2Cloud()
ccPointCloud * qCanupoTrainingDialog::getClass2Cloud ()
Get class #2 point cloud.
Definition at line 185 of file qCanupoTrainingDialog.cpp.
References qCanupoTools::GetCloudFromCombo(), and m_app.
Referenced by qCanupoPlugin::doTrainAction().
getDescriptorID()
unsigned qCanupoTrainingDialog::getDescriptorID () const
Returns the selected descriptor ID.
Definition at line 160 of file qCanupoTrainingDialog.cpp.
Referenced by qCanupoPlugin::doTrainAction().
getEvaluationCloud()
ccPointCloud * qCanupoTrainingDialog::getEvaluationCloud ()
Get evaluation point cloud.
Definition at line 199 of file qCanupoTrainingDialog.cpp.
References qCanupoTools::GetCloudFromCombo(), and m_app.
Referenced by qCanupoPlugin::doTrainAction().
getMaxThreadCount()
int qCanupoTrainingDialog::getMaxThreadCount () const
Returns the max number of threads to use.
Definition at line 116 of file qCanupoTrainingDialog.cpp.
Referenced by qCanupoPlugin::doTrainAction().
getOriginPointCloud()
ccPointCloud * qCanupoTrainingDialog::getOriginPointCloud ()
Get origin point cloud.
Definition at line 191 of file qCanupoTrainingDialog.cpp.
References qCanupoTools::GetCloudFromCombo(), and m_app.
Referenced by qCanupoPlugin::doTrainAction().
getScales()
bool qCanupoTrainingDialog::getScales (std::vector< float > & scales) const
Returns input scales.
Definition at line 120 of file qCanupoTrainingDialog.cpp.
References cloudViewer::utility::floor(), and QtCompat::SkipEmptyParts.
Referenced by qCanupoPlugin::doTrainAction().
loadParamsFromPersistentSettings()
void qCanupoTrainingDialog::loadParamsFromPersistentSettings ()
Loads parameters from persistent settings.
Definition at line 207 of file qCanupoTrainingDialog.cpp.
Referenced by qCanupoTrainingDialog().
onClassChanged
void qCanupoTrainingDialog::onClassChanged (int dummy) protected slot
Definition at line 171 of file qCanupoTrainingDialog.cpp.
References validParameters().
Referenced by qCanupoTrainingDialog().
onCloudChanged
void qCanupoTrainingDialog::onCloudChanged (int dummy) protected slot
Definition at line 175 of file qCanupoTrainingDialog.cpp.
References validParameters().
Referenced by qCanupoTrainingDialog().
saveParamsToPersistentSettings()
void qCanupoTrainingDialog::saveParamsToPersistentSettings ()
Saves parameters to persistent settings.
Definition at line 249 of file qCanupoTrainingDialog.cpp.
Referenced by qCanupoPlugin::doTrainAction().
validParameters()
bool qCanupoTrainingDialog::validParameters () const protected
Definition at line 104 of file qCanupoTrainingDialog.cpp.
Referenced by onClassChanged(), and onCloudChanged().
Member Data Documentation
m_app
ecvMainAppInterface* qCanupoTrainingDialog::m_app protected
Gives access to the application (data-base, UI, etc.)
Definition at line 52 of file qCanupoTrainingDialog.h.
Referenced by getClass1Cloud(), getClass2Cloud(), getEvaluationCloud(), getOriginPointCloud(), and qCanupoTrainingDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCanupo/include/qCanupoTrainingDialog.h
/root/ACloudViewer/plugins/core/Standard/qCanupo/src/qCanupoTrainingDialog.cpp