ACloudViewer: colmap::IncrementalTriangulator Class Reference
colmap::IncrementalTriangulator Class Reference
#include <incremental_triangulator.h>
Classes
struct CorrData
struct Options
Public Member Functions
IncrementalTriangulator (const CorrespondenceGraph *correspondence_graph, Reconstruction *reconstruction)
size_t TriangulateImage (const Options &options, const image_t image_id)
size_t CompleteImage (const Options &options, const image_t image_id)
size_t CompleteTracks (const Options &options, const std::unordered_set< point3D_t > &point3D_ids)
size_t CompleteAllTracks (const Options &options)
size_t MergeTracks (const Options &options, const std::unordered_set< point3D_t > &point3D_ids)
size_t MergeAllTracks (const Options &options)
size_t Retriangulate (const Options &options)
void AddModifiedPoint3D (const point3D_t point3D_id)
const std::unordered_set< point3D_t > & GetModifiedPoints3D ()
void ClearModifiedPoints3D ()
Detailed Description
Definition at line 18 of file incremental_triangulator.h.
Constructor & Destructor Documentation
IncrementalTriangulator()
colmap::IncrementalTriangulator::IncrementalTriangulator (const CorrespondenceGraph * correspondence_graph, Reconstruction * reconstruction)
Definition at line 55 of file incremental_triangulator.cc.
Member Function Documentation
AddModifiedPoint3D()
void colmap::IncrementalTriangulator::AddModifiedPoint3D (const point3D_t point3D_id)
Definition at line 418 of file incremental_triangulator.cc.
ClearModifiedPoints3D()
void colmap::IncrementalTriangulator::ClearModifiedPoints3D ()
Definition at line 436 of file incremental_triangulator.cc.
CompleteAllTracks()
size_t colmap::IncrementalTriangulator::CompleteAllTracks (const Options & options)
Definition at line 260 of file incremental_triangulator.cc.
References colmap::IncrementalTriangulator::Options::Check(), and colmap::Reconstruction::Point3DIds().
CompleteImage()
size_t colmap::IncrementalTriangulator::CompleteImage (const Options & options, const image_t image_id)
Definition at line 125 of file incremental_triangulator.cc.
References colmap::Track::AddElement(), colmap::Reconstruction::AddPoint3D(), colmap::Reconstruction::Camera(), colmap::IncrementalTriangulator::CorrData::camera, colmap::IncrementalTriangulator::Options::Check(), colmap::IncrementalTriangulator::Options::complete_max_reproj_error, colmap::RANSACOptions::confidence, colmap::DegToRad(), QtCompat::endl(), colmap::EstimateTriangulation(), colmap::Reconstruction::ExistsImage(), colmap::Point2D::HasPoint3D(), colmap::IncrementalTriangulator::Options::ignore_two_view_tracks, image, colmap::Reconstruction::Image(), colmap::IncrementalTriangulator::CorrData::image, colmap::IncrementalTriangulator::CorrData::image_id, colmap::Camera::ImageToWorld(), colmap::CorrespondenceGraph::IsTwoViewObservation(), colmap::RANSACOptions::max_error, colmap::RANSACOptions::max_num_trials, colmap::IncrementalTriangulator::Options::max_transitivity, colmap::IncrementalTriangulator::Options::min_angle, colmap::RANSACOptions::min_inlier_ratio, colmap::RANSACOptions::min_num_trials, colmap::EstimateTriangulationOptions::min_tri_angle, colmap::NChooseK(), colmap::IncrementalTriangulator::CorrData::point2D, colmap::IncrementalTriangulator::CorrData::point2D_idx, colmap::Point2D::Point3DId(), colmap::Image::ProjectionCenter(), colmap::Image::ProjectionMatrix(), colmap::EstimateTriangulationOptions::ransac_options, colmap::TriangulationEstimator::REPROJECTION_ERROR, colmap::Track::Reserve(), colmap::EstimateTriangulationOptions::residual_type, and colmap::Point2D::XY().
CompleteTracks()
size_t colmap::IncrementalTriangulator::CompleteTracks (const Options & options, const std::unordered_set< point3D_t > & point3D_ids)
Definition at line 244 of file incremental_triangulator.cc.
References colmap::IncrementalTriangulator::Options::Check().
GetModifiedPoints3D()
const std::unordered_set< point3D_t > & colmap::IncrementalTriangulator::GetModifiedPoints3D ()
Definition at line 423 of file incremental_triangulator.cc.
References colmap::Reconstruction::ExistsPoint3D().
MergeAllTracks()
size_t colmap::IncrementalTriangulator::MergeAllTracks (const Options & options)
Definition at line 290 of file incremental_triangulator.cc.
References colmap::IncrementalTriangulator::Options::Check(), and colmap::Reconstruction::Point3DIds().
MergeTracks()
size_t colmap::IncrementalTriangulator::MergeTracks (const Options & options, const std::unordered_set< point3D_t > & point3D_ids)
Definition at line 274 of file incremental_triangulator.cc.
References colmap::IncrementalTriangulator::Options::Check().
Retriangulate()
size_t colmap::IncrementalTriangulator::Retriangulate (const Options & options)
Definition at line 304 of file incremental_triangulator.cc.
References colmap::Reconstruction::Camera(), colmap::IncrementalTriangulator::CorrData::camera, colmap::Image::CameraId(), colmap::IncrementalTriangulator::Options::Check(), colmap::IncrementalTriangulator::Options::continue_max_angle_error, QtCompat::endl(), colmap::Reconstruction::ExistsImage(), colmap::CorrespondenceGraph::FindCorrespondencesBetweenImages(), colmap::Point2D::HasPoint3D(), colmap::Reconstruction::Image(), colmap::IncrementalTriangulator::CorrData::image, colmap::IncrementalTriangulator::CorrData::image_id, colmap::Reconstruction::ImagePairs(), colmap::Image::IsRegistered(), colmap::Database::PairIdToImagePair(), colmap::Image::Point2D(), colmap::IncrementalTriangulator::CorrData::point2D, colmap::IncrementalTriangulator::CorrData::point2D_idx, colmap::IncrementalTriangulator::Options::re_max_angle_error, colmap::IncrementalTriangulator::Options::re_max_trials, and colmap::IncrementalTriangulator::Options::re_min_ratio.
TriangulateImage()
size_t colmap::IncrementalTriangulator::TriangulateImage (const Options & options, const image_t image_id)
Definition at line 61 of file incremental_triangulator.cc.
References colmap::Reconstruction::Camera(), colmap::IncrementalTriangulator::CorrData::camera, colmap::IncrementalTriangulator::Options::Check(), QtCompat::endl(), colmap::Reconstruction::ExistsImage(), image, colmap::Reconstruction::Image(), colmap::IncrementalTriangulator::CorrData::image, colmap::IncrementalTriangulator::CorrData::image_id, colmap::IncrementalTriangulator::Options::max_transitivity, colmap::IncrementalTriangulator::CorrData::point2D, and colmap::IncrementalTriangulator::CorrData::point2D_idx.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/sfm/incremental_triangulator.h
/root/ACloudViewer/libs/Reconstruction/src/sfm/incremental_triangulator.cc