ACloudViewer: qVoxFallDialog Class Reference
qVoxFallDialog Class Reference
VOXFALL plugin's main dialog.
#include <qVoxFallDialog.h>
Public Member Functions
qVoxFallDialog (ccMesh *mesh1, ccMesh *mesh2, ecvMainAppInterface *app)
Default constructor.
ccMesh * getMesh1 () const
Returns mesh #1.
ccMesh * getMesh2 () const
Returns mesh #2.
double getVoxelSize () const
Returns voxel size.
double getAzimuth () const
Returns slope azimuth.
bool getExportMeshesActivation () const
Returns whether the blocks will be exported as meshes.
bool getLossGainActivation () const
Labels the blocks as loss or gain clusters.
int getMaxThreadCount () const
Returns the max number of threads to use.
void loadParamsFromPersistentSettings ()
void loadParamsFrom (const QSettings &settings)
void saveParamsToPersistentSettings ()
void saveParamsTo (QSettings &settings)
Protected Member Functions
void swapMeshes ()
void setMesh1Visibility (bool)
void setMesh2Visibility (bool)
void setMeshes (ccMesh *mesh1, ccMesh *mesh2)
Sets meshes.
Protected Attributes
ecvMainAppInterface * m_app
ccMesh * m_mesh1
ccMesh * m_mesh2
Detailed Description
VOXFALL plugin's main dialog.
Definition at line 19 of file qVoxFallDialog.h.
Constructor & Destructor Documentation
qVoxFallDialog()
qVoxFallDialog::qVoxFallDialog (ccMesh * mesh1, ccMesh * mesh2, ecvMainAppInterface * app)
Default constructor.
Definition at line 62 of file qVoxFallDialog.cpp.
References loadParamsFromPersistentSettings(), setMesh1Visibility(), setMesh2Visibility(), setMeshes(), and swapMeshes().
Member Function Documentation
getAzimuth()
double qVoxFallDialog::getAzimuth () const
Returns slope azimuth.
Definition at line 140 of file qVoxFallDialog.cpp.
Referenced by qVoxFallProcess::Compute().
getExportMeshesActivation()
bool qVoxFallDialog::getExportMeshesActivation () const
Returns whether the blocks will be exported as meshes.
Definition at line 145 of file qVoxFallDialog.cpp.
Referenced by qVoxFallProcess::Compute().
getLossGainActivation()
bool qVoxFallDialog::getLossGainActivation () const
Labels the blocks as loss or gain clusters.
Definition at line 149 of file qVoxFallDialog.cpp.
Referenced by qVoxFallProcess::Compute().
getMaxThreadCount()
int qVoxFallDialog::getMaxThreadCount () const
Returns the max number of threads to use.
Definition at line 153 of file qVoxFallDialog.cpp.
Referenced by qVoxFallProcess::Compute().
getMesh1()
ccMesh* qVoxFallDialog::getMesh1 () const inline
Returns mesh #1.
Definition at line 27 of file qVoxFallDialog.h.
References m_mesh1.
Referenced by qVoxFallProcess::Compute().
getMesh2()
ccMesh* qVoxFallDialog::getMesh2 () const inline
Returns mesh #2.
Definition at line 29 of file qVoxFallDialog.h.
References m_mesh2.
Referenced by qVoxFallProcess::Compute().
getVoxelSize()
double qVoxFallDialog::getVoxelSize () const
Returns voxel size.
Definition at line 135 of file qVoxFallDialog.cpp.
Referenced by qVoxFallProcess::Compute().
loadParamsFrom()
void qVoxFallDialog::loadParamsFrom (const QSettings & settings)
Definition at line 162 of file qVoxFallDialog.cpp.
Referenced by loadParamsFromPersistentSettings().
loadParamsFromPersistentSettings()
void qVoxFallDialog::loadParamsFromPersistentSettings ()
Definition at line 157 of file qVoxFallDialog.cpp.
References loadParamsFrom().
Referenced by qVoxFallDialog().
saveParamsTo()
void qVoxFallDialog::saveParamsTo (QSettings & settings)
Definition at line 188 of file qVoxFallDialog.cpp.
Referenced by saveParamsToPersistentSettings().
saveParamsToPersistentSettings()
void qVoxFallDialog::saveParamsToPersistentSettings ()
Definition at line 183 of file qVoxFallDialog.cpp.
References saveParamsTo().
setMesh1Visibility()
void qVoxFallDialog::setMesh1Visibility (bool state) protected
Definition at line 109 of file qVoxFallDialog.cpp.
References m_app, m_mesh1, ccDrawableObject::setRedraw(), ecvDisplayTools::SetRedrawRecursive(), and ccDrawableObject::setVisible().
Referenced by qVoxFallDialog().
setMesh2Visibility()
void qVoxFallDialog::setMesh2Visibility (bool state) protected
Definition at line 122 of file qVoxFallDialog.cpp.
References m_app, m_mesh2, ccDrawableObject::setRedraw(), ecvDisplayTools::SetRedrawRecursive(), and ccDrawableObject::setVisible().
Referenced by qVoxFallDialog().
setMeshes()
void qVoxFallDialog::setMeshes (ccMesh * mesh1, ccMesh * mesh2) protected
Sets meshes.
Definition at line 87 of file qVoxFallDialog.cpp.
References GetEntityName(), ccDrawableObject::isVisible(), m_mesh1, and m_mesh2.
Referenced by qVoxFallDialog(), and swapMeshes().
swapMeshes()
void qVoxFallDialog::swapMeshes () protected
Definition at line 85 of file qVoxFallDialog.cpp.
References m_mesh1, m_mesh2, and setMeshes().
Referenced by qVoxFallDialog().
Member Data Documentation
m_app
ecvMainAppInterface* qVoxFallDialog::m_app protected
Definition at line 58 of file qVoxFallDialog.h.
Referenced by setMesh1Visibility(), and setMesh2Visibility().
m_mesh1
ccMesh* qVoxFallDialog::m_mesh1 protected
Definition at line 60 of file qVoxFallDialog.h.
Referenced by getMesh1(), setMesh1Visibility(), setMeshes(), and swapMeshes().
m_mesh2
ccMesh* qVoxFallDialog::m_mesh2 protected
Definition at line 61 of file qVoxFallDialog.h.
Referenced by getMesh2(), setMesh2Visibility(), setMeshes(), and swapMeshes().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qVoxFall/include/qVoxFallDialog.h
/root/ACloudViewer/plugins/core/Standard/qVoxFall/src/qVoxFallDialog.cpp