ACloudViewer: FacetsClassifier Class Reference
FacetsClassifier Class Reference
#include <facetsClassifier.h>
Public Types
typedef std::vector< ccFacet * > FacetSet
Set of facets (pointers to)
Static Public Member Functions
static PointCoordinateType CommputeHDistBetweenFacets (const ccFacet *f1, const ccFacet *f2)
Computes minimal 'orthogonal' distance between two facets.
static void GenerateSubfamilyColor (ecvColor::Rgb &col, double dip, double dipDir, unsigned subFamilyIndex, unsigned subFamilyCount, ecvColor::Rgb *darkCol=0)
Generates a given sub-family color.
static void GetFamilyIndexes (ccFacet *facet, unsigned dSteps, unsigned ddSteps, double angularStep_deg, unsigned &iDip, unsigned &iDipDir)
static QString GetFamilyName (double dip, double dipDir, double angularStep_deg)
static QString GetSubFamilyName (int subFamilyIndex)
static bool ProcessFamiliy (ccHObject *parent, FacetSet &family, unsigned familyIndex, unsigned iDip, unsigned iDipDir, double angularStep_deg, double maxDist)
Subdivides a set of facets with similar orientation.
static bool ByOrientation (ccHObject *facetGroup, double angularStep_deg, double maxDist)
Classifies the facets based on their orientation.
Detailed Description
Definition at line 26 of file facetsClassifier.h.
Member Typedef Documentation
FacetSet
typedef std::vector<ccFacet*> FacetsClassifier::FacetSet
Set of facets (pointers to)
Definition at line 29 of file facetsClassifier.h.
Member Function Documentation
ByOrientation()
static bool FacetsClassifier::ByOrientation (ccHObject * facetGroup, double angularStep_deg, double maxDist) inline static
Classifies the facets based on their orientation.
Definition at line 320 of file facetsClassifier.h.
References ccHObject::addChild(), cloudViewer::utility::ceil(), error(), CV_TYPES::FACET, ccHObject::filterChildren(), GetFamilyIndexes(), ccHObject::getParent(), ProcessFamiliy(), ccHObject::removeAllChildren(), ccHObject::removeChild(), and ccHObject::removeDependencyWith().
Referenced by qFacets::classifyFacetsByAngle().
CommputeHDistBetweenFacets()
static PointCoordinateType FacetsClassifier::CommputeHDistBetweenFacets (const ccFacet * f1, const ccFacet * f2) inline static
Computes minimal 'orthogonal' distance between two facets.
Definition at line 32 of file facetsClassifier.h.
References Vector3Tpl< Type >::dot(), fabs(), ccFacet::getCenter(), ccFacet::getNormal(), and min().
Referenced by ProcessFamiliy().
GenerateSubfamilyColor()
static void FacetsClassifier::GenerateSubfamilyColor (ecvColor::Rgb & col, double dip, double dipDir, unsigned subFamilyIndex, unsigned subFamilyCount, ecvColor::Rgb * darkCol = 0) inline static
Generates a given sub-family color.
Definition at line 40 of file facetsClassifier.h.
References c_darkColorRatio, and ecvColor::Convert::hsl2rgb().
Referenced by qFacets::createFacets(), StereogramWidget::paintEvent(), and ProcessFamiliy().
GetFamilyIndexes()
static void FacetsClassifier::GetFamilyIndexes (ccFacet * facet, unsigned dSteps, unsigned ddSteps, double angularStep_deg, unsigned & iDip, unsigned & iDipDir) inline static
Definition at line 66 of file facetsClassifier.h.
References ccNormalVectors::ConvertNormalToDipAndDipDir(), cloudViewer::utility::floor(), and ccFacet::getNormal().
Referenced by ByOrientation().
GetFamilyName()
static QString FacetsClassifier::GetFamilyName (double dip, double dipDir, double angularStep_deg) inline static
Definition at line 84 of file facetsClassifier.h.
Referenced by ProcessFamiliy().
GetSubFamilyName()
static QString FacetsClassifier::GetSubFamilyName (int subFamilyIndex) inline static
Definition at line 92 of file facetsClassifier.h.
Referenced by ProcessFamiliy().
ProcessFamiliy()
static bool FacetsClassifier::ProcessFamiliy (ccHObject * parent, FacetSet & family, unsigned familyIndex, unsigned iDip, unsigned iDipDir, double angularStep_deg, double maxDist) inline static
Subdivides a set of facets with similar orientation.
Definition at line 97 of file facetsClassifier.h.
References ccHObject::addChild(), CommputeHDistBetweenFacets(), count, dist(), GenerateSubfamilyColor(), ccFacet::getContour(), GetFamilyName(), ccObject::getMetaData(), ccHObject::getParent(), GetSubFamilyName(), cloudViewer::SquareMatrixTpl< Scalar >::getValue(), cloudViewer::SquareMatrixTpl< Scalar >::isValid(), s_OriFamilyKey, s_OriFamilyNameKey, s_OriSubFamilyKey, ccPolyline::setColor(), ccFacet::setColor(), ccObject::setMetaData(), cloudViewer::SquareMatrixTpl< Scalar >::setValue(), and ccPolyline::setWidth().
Referenced by ByOrientation().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qFacets/include/facetsClassifier.h