ACloudViewer: PointCloudLODVisibilityFlagger Class Reference
PointCloudLODVisibilityFlagger Class Reference
Public Member Functions
PointCloudLODVisibilityFlagger (ccPointCloudLOD &lod, const Frustum &frustum, unsigned char maxLevel)
void setClipPlanes (const ccClipPlaneSet &clipPlanes)
void propagateFlag (ccPointCloudLOD::Node &node, uint8_t flag)
uint32_t flag (ccPointCloudLOD::Node &node)
Public Attributes
ccPointCloudLOD & m_lod
const Frustum & m_frustum
unsigned char m_maxLevel
ccClipPlaneSet m_clipPlanes
bool m_hasClipPlanes
Detailed Description
Definition at line 541 of file ecvPointCloudLOD.cpp.
Constructor & Destructor Documentation
PointCloudLODVisibilityFlagger()
PointCloudLODVisibilityFlagger::PointCloudLODVisibilityFlagger (ccPointCloudLOD & lod, const Frustum & frustum, unsigned char maxLevel) inline
Definition at line 543 of file ecvPointCloudLOD.cpp.
Member Function Documentation
flag()
uint32_t PointCloudLODVisibilityFlagger::flag (ccPointCloudLOD::Node & node) inline
Definition at line 575 of file ecvPointCloudLOD.cpp.
References ccPointCloudLOD::Node::center, ccPointCloudLOD::Node::childCount, ccPointCloudLOD::Node::childIndexes, Frustum::INSIDE, Frustum::INTERSECT, ccPointCloudLOD::Node::intersection, ccPointCloudLOD::Node::level, m_clipPlanes, m_frustum, m_hasClipPlanes, m_lod, m_maxLevel, ccPointCloudLOD::node(), Frustum::OUTSIDE, ccPointCloudLOD::Node::pointCount, propagateFlag(), ccPointCloudLOD::Node::radius, Frustum::sphereInFrustum(), Tuple4Tpl< Type >::w, Tuple3Tpl< Type >::x, Tuple4Tpl< Type >::x, Tuple3Tpl< Type >::y, Tuple4Tpl< Type >::y, Tuple3Tpl< Type >::z, and Tuple4Tpl< Type >::z.
Referenced by ccPointCloudLOD::flagVisibility(), and propagateFlag().
propagateFlag()
void PointCloudLODVisibilityFlagger::propagateFlag (ccPointCloudLOD::Node & node, uint8_t flag) inline
Definition at line 561 of file ecvPointCloudLOD.cpp.
References ccPointCloudLOD::Node::childCount, ccPointCloudLOD::Node::childIndexes, flag(), ccPointCloudLOD::Node::intersection, ccPointCloudLOD::Node::level, m_lod, and ccPointCloudLOD::node().
Referenced by flag().
setClipPlanes()
void PointCloudLODVisibilityFlagger::setClipPlanes (const ccClipPlaneSet & clipPlanes) inline
Definition at line 551 of file ecvPointCloudLOD.cpp.
References m_clipPlanes, and m_hasClipPlanes.
Referenced by ccPointCloudLOD::flagVisibility().
Member Data Documentation
m_clipPlanes
ccClipPlaneSet PointCloudLODVisibilityFlagger::m_clipPlanes
Definition at line 642 of file ecvPointCloudLOD.cpp.
Referenced by flag(), and setClipPlanes().
m_frustum
const Frustum& PointCloudLODVisibilityFlagger::m_frustum
Definition at line 640 of file ecvPointCloudLOD.cpp.
Referenced by flag().
m_hasClipPlanes
bool PointCloudLODVisibilityFlagger::m_hasClipPlanes
Definition at line 643 of file ecvPointCloudLOD.cpp.
Referenced by flag(), and setClipPlanes().
m_lod
ccPointCloudLOD& PointCloudLODVisibilityFlagger::m_lod
Definition at line 639 of file ecvPointCloudLOD.cpp.
Referenced by flag(), and propagateFlag().
m_maxLevel
unsigned char PointCloudLODVisibilityFlagger::m_maxLevel
Definition at line 641 of file ecvPointCloudLOD.cpp.
Referenced by flag().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/src/ecvPointCloudLOD.cpp