ACloudViewer: ecvGenericDisplayTools Class Reference
ecvGenericDisplayTools Class Reference
Generic display tools.
#include <ecvGenericDisplayTools.h>
Public Types
enum TextAlign {
ALIGN_HLEFT = 1 , ALIGN_HMIDDLE = 2 , ALIGN_HRIGHT = 4 , ALIGN_VTOP = 8 ,
ALIGN_VMIDDLE = 16 , ALIGN_VBOTTOM = 32 , ALIGN_DEFAULT = 1 | 8
}
Text alignment.
Public Member Functions
virtual ~ecvGenericDisplayTools ()
Default destructor.
virtual bool getPerspectiveState (int viewport=0) const
virtual void toWorldPoint (const CCVector3d &input2D, CCVector3d &output3D)
virtual void toWorldPoint (const CCVector3 &input2D, CCVector3d &output3D)
virtual void toDisplayPoint (const CCVector3d &input3D, CCVector3d &output2D)
virtual void toDisplayPoint (const CCVector3 &input3D, CCVector3d &output2D)
Static Public Member Functions
static ecvGenericDisplayTools * GetInstance ()
static void SetInstance (ecvGenericDisplayTools *tool)
static int FontSizeModifier (int fontSize, float zoomFactor)
static bool GetPerspectiveState ()
Returns perspective mode.
template<typename iType , typename oType >
static void ToWorldPoint (const Vector3Tpl< iType > &input2D, Vector3Tpl< oType > &output3D)
template<typename iType , typename oType >
static void ToDisplayPoint (const Vector3Tpl< iType > &input3D, Vector3Tpl< oType > &output2D)
static ccGLMatrixd Frustum (double left, double right, double bottom, double top, double znear, double zfar)
static ccGLMatrixd Perspective (double fovyInDegrees, double aspectRatio, double znear, double zfar)
static ccGLMatrixd Ortho (double left, double right, double bottom, double top, double nearVal, double farVal)
static ccGLMatrixd Ortho (double w, double h, double d)
template<typename iType , typename oType >
static bool Project (const Vector3Tpl< iType > &input3D, const oType *modelview, const oType *projection, const int *viewport, Vector3Tpl< oType > &output2D, bool *inFrustum=nullptr)
static double MAT (const double *m, int r, int c)
static float MAT (const float *m, int r, int c)
static double & MAT (double *m, int r, int c)
static float & MAT (float *m, int r, int c)
template<typename Type >
static bool InvertMatrix (const Type *m, Type *out)
template<typename iType , typename oType >
static bool Unproject (const Vector3Tpl< iType > &input2D, const oType *modelview, const oType *projection, const int *viewport, Vector3Tpl< oType > &output3D)
static void PickMatrix (double x, double y, double width, double height, int viewport[4], double m[16])
Protected Member Functions
ecvGenericDisplayTools ()
Default constructor.
Detailed Description
Generic display tools.
Definition at line 24 of file ecvGenericDisplayTools.h.
Member Enumeration Documentation
TextAlign
enum ecvGenericDisplayTools::TextAlign
Text alignment.
Enumerator
ALIGN_HLEFT
ALIGN_HMIDDLE
ALIGN_HRIGHT
ALIGN_VTOP
ALIGN_VMIDDLE
ALIGN_VBOTTOM
ALIGN_DEFAULT
Definition at line 78 of file ecvGenericDisplayTools.h.
Constructor & Destructor Documentation
~ecvGenericDisplayTools()
virtual ecvGenericDisplayTools::~ecvGenericDisplayTools () inline virtual
Default destructor.
Definition at line 27 of file ecvGenericDisplayTools.h.
ecvGenericDisplayTools()
ecvGenericDisplayTools::ecvGenericDisplayTools () protected
Default constructor.
Member Function Documentation
FontSizeModifier()
static int ecvGenericDisplayTools::FontSizeModifier (int fontSize, float zoomFactor) inline static
Definition at line 33 of file ecvGenericDisplayTools.h.
References cloudViewer::utility::floor().
Frustum()
static ccGLMatrixd ecvGenericDisplayTools::Frustum (double left, double right, double bottom, double top, double znear, double zfar) inline static
Definition at line 89 of file ecvGenericDisplayTools.h.
References ccGLMatrixTpl< T >::data().
GetInstance()
static ecvGenericDisplayTools* ecvGenericDisplayTools::GetInstance () static
GetPerspectiveState()
static bool ecvGenericDisplayTools::GetPerspectiveState () inline static
Returns perspective mode.
Definition at line 42 of file ecvGenericDisplayTools.h.
References Runtime::GetInstance().
Referenced by define_ccDisplayTools().
getPerspectiveState()
virtual bool ecvGenericDisplayTools::getPerspectiveState (int viewport = 0) const inline virtual
Reimplemented in ecvDisplayTools.
Definition at line 46 of file ecvGenericDisplayTools.h.
InvertMatrix()
template<typename Type > static bool ecvGenericDisplayTools::InvertMatrix (const Type * m, Type * out) inline static
Definition at line 326 of file ecvGenericDisplayTools.h.
MAT() [1/4]
static double ecvGenericDisplayTools::MAT (const double * m, int r, int c) inline static
Definition at line 315 of file ecvGenericDisplayTools.h.
MAT() [2/4]
static float ecvGenericDisplayTools::MAT (const float * m, int r, int c) inline static
Definition at line 318 of file ecvGenericDisplayTools.h.
MAT() [3/4]
static double& ecvGenericDisplayTools::MAT (double * m, int r, int c) inline static
Definition at line 322 of file ecvGenericDisplayTools.h.
MAT() [4/4]
static float& ecvGenericDisplayTools::MAT (float * m, int r, int c) inline static
Definition at line 323 of file ecvGenericDisplayTools.h.
Ortho() [1/2]
static ccGLMatrixd ecvGenericDisplayTools::Ortho (double left, double right, double bottom, double top, double nearVal, double farVal) inline static
Definition at line 174 of file ecvGenericDisplayTools.h.
References ccGLMatrixTpl< T >::data(), and ccGLMatrixTpl< T >::toIdentity().
Ortho() [2/2]
static ccGLMatrixd ecvGenericDisplayTools::Ortho (double w, double h, double d) inline static
Definition at line 214 of file ecvGenericDisplayTools.h.
References ccGLMatrixTpl< T >::data(), and ccGLMatrixTpl< T >::toIdentity().
Perspective()
static ccGLMatrixd ecvGenericDisplayTools::Perspective (double fovyInDegrees, double aspectRatio, double znear, double zfar) inline static
Definition at line 136 of file ecvGenericDisplayTools.h.
References ccGLMatrixTpl< T >::data(), and cloudViewer::DegreesToRadians().
PickMatrix()
static void ecvGenericDisplayTools::PickMatrix (double x, double y, double width, double height, int viewport[4], double m[16]) inline static
Definition at line 519 of file ecvGenericDisplayTools.h.
References height, and width.
Project()
template<typename iType , typename oType > static bool ecvGenericDisplayTools::Project (const Vector3Tpl< iType > & input3D, const oType * modelview, const oType * projection, const int * viewport, Vector3Tpl< oType > & output2D, bool * inFrustum = nullptr) inline static
Definition at line 245 of file ecvGenericDisplayTools.h.
References abs(), Runtime::GetInstance(), Tuple4Tpl< Type >::w, Tuple3Tpl< Type >::x, Tuple4Tpl< Type >::x, Tuple3Tpl< Type >::y, Tuple4Tpl< Type >::y, Tuple3Tpl< Type >::z, and Tuple4Tpl< Type >::z.
SetInstance()
static void ecvGenericDisplayTools::SetInstance (ecvGenericDisplayTools * tool) static
toDisplayPoint() [1/2]
virtual void ecvGenericDisplayTools::toDisplayPoint (const CCVector3 & input3D, CCVector3d & output2D) inline virtual
Definition at line 73 of file ecvGenericDisplayTools.h.
toDisplayPoint() [2/2]
virtual void ecvGenericDisplayTools::toDisplayPoint (const CCVector3d & input3D, CCVector3d & output2D) inline virtual
Definition at line 68 of file ecvGenericDisplayTools.h.
ToDisplayPoint()
template<typename iType , typename oType > static void ecvGenericDisplayTools::ToDisplayPoint (const Vector3Tpl< iType > & input3D, Vector3Tpl< oType > & output2D) inline static
Definition at line 64 of file ecvGenericDisplayTools.h.
References Runtime::GetInstance().
toWorldPoint() [1/2]
virtual void ecvGenericDisplayTools::toWorldPoint (const CCVector3 & input2D, CCVector3d & output3D) inline virtual
Definition at line 60 of file ecvGenericDisplayTools.h.
toWorldPoint() [2/2]
virtual void ecvGenericDisplayTools::toWorldPoint (const CCVector3d & input2D, CCVector3d & output3D) inline virtual
Definition at line 56 of file ecvGenericDisplayTools.h.
ToWorldPoint()
template<typename iType , typename oType > static void ecvGenericDisplayTools::ToWorldPoint (const Vector3Tpl< iType > & input2D, Vector3Tpl< oType > & output3D) inline static
Definition at line 51 of file ecvGenericDisplayTools.h.
References Runtime::GetInstance().
Unproject()
template<typename iType , typename oType > static bool ecvGenericDisplayTools::Unproject (const Vector3Tpl< iType > & input2D, const oType * modelview, const oType * projection, const int * viewport, Vector3Tpl< oType > & output3D) inline static
Definition at line 474 of file ecvGenericDisplayTools.h.
References ccGLMatrixTpl< T >::data(), and Runtime::GetInstance().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvGenericDisplayTools.h