ACloudViewer: ccGenericMesh Class Reference
ccGenericMesh Class Reference abstract
Generic mesh interface.
#include <ecvGenericMesh.h>
Public Member Functions
ccGenericMesh (QString name=QString())
Default constructor.
~ccGenericMesh () override=default
Destructor.
void showNormals (bool state) override
Sets normals visibility.
bool isSerializable () const override
Returns whether object is serializable of not.
virtual ccGenericPointCloud * getAssociatedCloud () const =0
Returns the vertices cloud.
virtual void refreshBB ()=0
Forces bounding-box update.
virtual unsigned capacity () const =0
Returns max capacity.
virtual bool hasMaterials () const =0
virtual const ccMaterialSet * getMaterialSet () const =0
virtual int getTriangleMtlIndex (unsigned triangleIndex) const =0
Returns a given triangle material indexes.
virtual bool hasTextures () const =0
Returns whether textures are available for this mesh.
virtual TextureCoordsContainer * getTexCoordinatesTable () const =0
Returns per-triangle texture coordinates array.
virtual void getTriangleTexCoordinates (unsigned triIndex, TexCoords2D *&tx1, TexCoords2D *&tx2, TexCoords2D *&tx3) const =0
Returns per-triangle texture coordinates (pointer to)
virtual void getTexCoordinates (unsigned index, TexCoords2D *&tx) const =0
virtual bool hasPerTriangleTexCoordIndexes () const =0
Returns whether this mesh as per-triangle triplets of tex coords indexes.
virtual void getTriangleTexCoordinatesIndexes (unsigned triangleIndex, int &i1, int &i2, int &i3) const =0
Returns the triplet of tex coords indexes for a given triangle.
virtual bool hasTriNormals () const =0
Returns whether the mesh has per-triangle normals.
virtual void getTriangleNormalIndexes (unsigned triangleIndex, int &i1, int &i2, int &i3) const =0
Returns a triplet of normal indexes for a given triangle (if any)
virtual bool getTriangleNormals (unsigned triangleIndex, CCVector3 &Na, CCVector3 &Nb, CCVector3 &Nc) const =0
Returns a given triangle normal.
virtual bool getTriangleNormals (unsigned triangleIndex, double Na[3], double Nb[3], double Nc[3]) const
virtual bool getTriangleNormals (unsigned triangleIndex, Eigen::Vector3d &Na, Eigen::Vector3d &Nb, Eigen::Vector3d &Nc) const
virtual NormsIndexesTableType * getTriNormsTable () const =0
Returns per-triangle normals shared array.
virtual void computeInterpolationWeights (unsigned triIndex, const CCVector3 &P, CCVector3d &weights) const
Returns the (barycentric) interpolation weights for a given triangle.
virtual bool interpolateNormalsBC (unsigned triIndex, const CCVector3d &w, CCVector3 &N)=0
Interpolates normal(s) inside a given triangle.
virtual bool interpolateColors (unsigned triIndex, const CCVector3 &P, ecvColor::Rgb &C)=0
Interpolates RGB colors inside a given triangle.
virtual bool getColorFromMaterial (unsigned triIndex, const CCVector3 &P, ecvColor::Rgb &C, bool interpolateColorIfNoTexture)=0
virtual bool getVertexColorFromMaterial (unsigned triIndex, unsigned char vertIndex, ecvColor::Rgb &C, bool returnColorIfNoTexture)=0
virtual bool isShownAsWire () const
Returns whether the mesh is displayed as wired or with plain facets.
virtual void showWired (bool state)
Sets whether mesh should be displayed as a wire or with plain facets.
virtual bool isShownAsPoints () const
Returns whether the mesh is displayed as wired or with plain facets.
virtual void showPoints (bool state)
virtual bool triNormsShown () const
Returns whether per-triangle normals are shown or not.
virtual void showTriNorms (bool state)
Sets whether to show or not per-triangle normals.
virtual bool materialsShown () const
Sets whether textures/material should be displayed or not.
virtual void showMaterials (bool state)
Sets whether textures should be displayed or not.
virtual bool stipplingEnabled () const
Returns whether polygon stippling is enabled or not.
void enableStippling (bool state)
Enables polygon stippling.
ccPointCloud * samplePoints (bool densityBased, double samplingParameter, bool withNormals, bool withRGB, bool withTexture, cloudViewer::GenericProgressCallback *pDlg=nullptr)
Samples points on a mesh.
void importParametersFrom (const ccGenericMesh *mesh)
Imports the parameters from another mesh.
virtual bool trianglePicking (const CCVector2d &clickPos, const ccGLCameraParameters &camera, int &nearestTriIndex, double &nearestSquareDist, CCVector3d &nearestPoint, CCVector3d *barycentricCoords=nullptr) const
Brute force triangle picking.
virtual bool trianglePicking (unsigned triIndex, const CCVector2d &clickPos, const ccGLCameraParameters &camera, CCVector3d &point, CCVector3d *barycentricCoords=nullptr) const
Triangle picking (single triangle)
bool computePointPosition (unsigned triIndex, const CCVector2d &uv, CCVector3 &P, bool warningIfOutside=true) const
void setGlobalShift (const CCVector3d &shift) override
Sets shift applied to original coordinates (information storage only)
void setGlobalScale (double scale) override
const CCVector3d & getGlobalShift () const override
Returns the shift applied to original coordinates.
double getGlobalScale () const override
Returns the scale applied to original coordinates.
bool normalsAvailable () const override
Returns whether normals are available.
bool updateTextures (const std::string &texture_file)
bool updateTextures (const std::vector< std::string > &texture_files)
Public Member Functions inherited from cloudViewer::GenericIndexedMesh
GenericIndexedMesh ()=default
~GenericIndexedMesh () override=default
Default destructor.
virtual GenericTriangle * _getTriangle (unsigned triangleIndex)=0
Returns the ith triangle.
virtual VerticesIndexes * getTriangleVertIndexes (unsigned triangleIndex)=0
Returns the indexes of the vertices of a given triangle.
virtual void getTriangleVertices (unsigned triangleIndex, CCVector3 &A, CCVector3 &B, CCVector3 &C) const =0
Returns the vertices of a given triangle.
virtual void getTriangleVertices (unsigned triangleIndex, double A[3], double B[3], double C[3]) const =0
virtual VerticesIndexes * getNextTriangleVertIndexes ()=0
virtual bool interpolateNormals (unsigned triIndex, const CCVector3 &P, CCVector3 &N)
Interpolates normal(s) inside a given triangle.
Public Member Functions inherited from cloudViewer::GenericMesh
GenericMesh ()=default
virtual ~GenericMesh ()=default
Default destructor.
virtual unsigned size () const =0
Returns the number of triangles.
virtual bool hasTriangles () const
virtual void forEach (genericTriangleAction action)=0
Fast iteration mechanism.
virtual void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax)=0
Returns the mesh bounding-box.
virtual void placeIteratorAtBeginning ()=0
Places the mesh iterator at the beginning.
virtual GenericTriangle * _getNextTriangle ()=0
Returns the next triangle (relatively to the global iterator position)
Public Member Functions inherited from ccShiftedObject
ccShiftedObject (QString name=QString())
Default constructor.
ccShiftedObject (const ccShiftedObject &s)
Copy constructor.
void copyGlobalShiftAndScale (const ccShiftedObject &s)
Copies the Global Shift and Scale from another entity.
virtual void setGlobalShift (double x, double y, double z)
Sets shift applied to original coordinates (information storage only)
bool isShifted () const
Returns whether the cloud is shifted or not.
template<typename T >
CCVector3d toGlobal3d (const Vector3Tpl< T > &Plocal) const
Returns the point back-projected into the original coordinates system.
template<typename T >
CCVector3d toLocal3d (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
template<typename T >
CCVector3 toLocal3pc (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner) override
GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false) override
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual bool IsEmpty () const
virtual Eigen::Vector3d GetMinBound () const
Returns min bounds for geometry coordinates.
virtual Eigen::Vector2d GetMin2DBound () const
virtual Eigen::Vector3d GetMaxBound () const
Returns max bounds for geometry coordinates.
virtual Eigen::Vector2d GetMax2DBound () const
virtual Eigen::Vector3d GetCenter () const
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const
virtual ccHObject & Transform (const Eigen::Matrix4d &transformation)
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual ccHObject & Translate (const Eigen::Vector3d &translation, bool relative=true)
Apply translation to the geometry coordinates.
virtual ccHObject & Scale (const double s, const Eigen::Vector3d &center)
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center)
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
CV_CLASS_ENUM getClassID () const override
Returns class ID.
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
virtual ccBBox getOwnBB (bool withGLFeatures=false)
Returns the entity's own bounding-box.
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual ccBBox getOwnFitBB (ccGLMatrix &trans)
Returns best-fit bounding-box (if available)
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col)
Draws the entity (and its children) bounding-box.
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
virtual void notifyGeometryUpdate ()
bool isSerializable () const override
Returns whether object is serializable of not.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual unsigned getUniqueIDForDisplay () const
Returns object unqiue ID used for display.
virtual const ccGLMatrix & getGLTransformationHistory () const
Returns the transformation 'history' matrix.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual void getDrawingParameters (glDrawParams &params) const
Returns main OpenGL parameters for this entity.
virtual bool hasColors () const
Returns whether colors are enabled or not.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual bool hasNormals () const
Returns whether normals are enabled or not.
virtual bool normalsShown () const
Returns whether normals are shown or not.
virtual void toggleNormals ()
Toggles normals display state.
virtual bool hasDisplayedScalarField () const
Returns whether an active scalar field is available or not.
virtual bool hasScalarFields () const
Returns whether one or more scalar fields are instantiated.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void toggleMaterials ()
Toggles material display state.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Static Public Member Functions
static bool IsCloudVerticesOfMesh (ccGenericPointCloud *cloud, ccGenericMesh **mesh=nullptr)
Helper to determine if the input cloud acts as vertices of a mesh.
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Protected Member Functions
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
virtual bool trianglePicking (unsigned triIndex, const CCVector2d &clickPos, const ccGLMatrix &trans, bool noGLTrans, const ccGenericPointCloud &vertices, const ccGLCameraParameters &camera, CCVector3d &point, CCVector3d *barycentricCoords=nullptr) const
Triangle picking (single triangle)
void drawMeOnly (CC_DRAW_CONTEXT &context) override
Enables (OpenGL) stipple mask.
void handleColorRamp (CC_DRAW_CONTEXT &context)
Handles the color ramp display.
Protected Member Functions inherited from ccShiftedObject
bool saveShiftInfoToFile (QFile &out) const
Serialization helper (output)
bool loadShiftInfoFromFile (QFile &in)
Serialization helper (input)
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void applyGLTransformation (const ccGLMatrix &trans)
Applies a GL transformation to the entity.
virtual void drawNameIn3D ()
Draws the entity name in 3D.
virtual void onDeletionOf (const ccHObject *obj)
This method is called when another object is deleted.
virtual void onUpdateOf (ccHObject *obj)
This method is called when another object (geometry) is updated.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Static Protected Member Functions
static CCVector3 * GetVertexBuffer ()
static CCVector3 * GetNormalsBuffer ()
static ecvColor::Rgb * GetColorsBuffer ()
static unsigned * GetWireVertexIndexes ()
Returns a pre-initialized array of vertex indexes for wired display.
Protected Attributes
bool m_triNormsShown
Per-triangle normals display flag.
bool m_materialsShown
Texture/material display flag.
bool m_showWired
Wireframe display mode.
bool m_showPoints
points display mode
bool m_stippling
Polygon stippling state.
Protected Attributes inherited from ccShiftedObject
CCVector3d m_globalShift
Global shift (typically applied at loading time)
double m_globalScale
Global scale (typically applied at loading time)
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Additional Inherited Members
Public Types inherited from cloudViewer::GenericMesh
enum class SimplificationContraction { Average , Quadric }
Indicates the method that is used for mesh simplification if multiple vertices are combined to a single one.
enum class FilterScope { All , Color , Normal , Vertex }
Indicates the scope of filter operations.
enum class DeformAsRigidAsPossibleEnergy { Spokes , Smoothed }
using genericTriangleAction = std::function< void(GenericTriangle &)>
Generic function to apply to a triangle (used by foreach)
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Detailed Description
Generic mesh interface.
Definition at line 28 of file ecvGenericMesh.h.
Constructor & Destructor Documentation
ccGenericMesh()
ccGenericMesh::ccGenericMesh (QString name = QString())
Default constructor.
Parameters
name object name
~ccGenericMesh()
ccGenericMesh::~ccGenericMesh () override default
Destructor.
Member Function Documentation
capacity()
virtual unsigned ccGenericMesh::capacity () const pure virtual
Returns max capacity.
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by define_ccGenericMesh(), cloudViewer::geometry::pybind_meshbase(), and ccMesh::shrinkToFit().
computeInterpolationWeights()
virtual void ccGenericMesh::computeInterpolationWeights (unsigned triIndex, const CCVector3 & P, CCVector3d & weights) const virtual
Returns the (barycentric) interpolation weights for a given triangle.
Reimplemented in ccMesh.
Referenced by ccCropTool::Crop().
computePointPosition()
bool ccGenericMesh::computePointPosition (unsigned triIndex, const CCVector2d & uv, CCVector3 & P, bool warningIfOutside = true) const
Computes the point that corresponds to the given uv (barycentric) coordinates
drawMeOnly()
void ccGenericMesh::drawMeOnly (CC_DRAW_CONTEXT & context) override protected virtual
Enables (OpenGL) stipple mask.
Reimplemented from ccHObject.
Reimplemented in ccPlane, ccMeshGroup, and ccMesh.
enableStippling()
void ccGenericMesh::enableStippling (bool state) inline
Enables polygon stippling.
Definition at line 207 of file ecvGenericMesh.h.
Referenced by ccFitPlane::ccFitPlane(), qFacets::createFacets(), cloudViewer::geometry::pybind_meshbase(), ccCompass::recurseStipple(), and qCanupo2DViewDialog::trainClassifier().
fromFile_MeOnly()
bool ccGenericMesh::fromFile_MeOnly (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override protected virtual
Loads own object data.
Called by 'fromFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
in input file
dataVersion file version
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Reimplemented from ccHObject.
Reimplemented in ccTorus, ccSubMesh, ccSphere, ccQuadric, ccPlane, ccMeshGroup, ccMesh, and ccGenericPrimitive.
getAssociatedCloud()
virtual ccGenericPointCloud* ccGenericMesh::getAssociatedCloud () const pure virtual
Returns the vertices cloud.
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by ccGraphicalSegmentationTool::addEntity(), ccGraphicalSegmentationTool::applySegmentation(), CanDetachCloud(), ccCropTool::Crop(), define_ccGenericMesh(), ccDBRoot::deleteSelectedEntities(), qPCV::doAction(), ccDBRoot::dropMimeData(), ccCommandLineParser::exportEntity(), ccPropertiesTreeDelegate::fillWithMesh(), ccRegistrationTools::ICP(), ccCommandLineParser::importFile(), ccComparisonDlg::prepareEntitiesForComparison(), CommandExtractVertices::process(), PCVCommand::Process(), MAFilter::saveToFile(), and ToFbxMesh().
getColorFromMaterial()
virtual bool ccGenericMesh::getColorFromMaterial (unsigned triIndex, const CCVector3 & P, ecvColor::Rgb & C, bool interpolateColorIfNoTexture) pure virtual
! Returns RGB color from a given triangle material/texture **
Parameters
triIndex triangle index
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
GetColorsBuffer()
static ecvColor::Rgb* ccGenericMesh::GetColorsBuffer () static protected
getGlobalScale()
double ccGenericMesh::getGlobalScale () const override virtual
Returns the scale applied to original coordinates.
Reimplemented from ccShiftedObject.
getGlobalShift()
const CCVector3d& ccGenericMesh::getGlobalShift () const override virtual
Returns the shift applied to original coordinates.
See ccGenericPointCloud::setOriginalShift
Reimplemented from ccShiftedObject.
getMaterialSet()
virtual const ccMaterialSet* ccGenericMesh::getMaterialSet () const pure virtual
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by ccCropTool::Crop(), define_ccGenericMesh(), and ccPropertiesTreeDelegate::setEditorData().
GetNormalsBuffer()
static CCVector3* ccGenericMesh::GetNormalsBuffer () static protected
getTexCoordinates()
virtual void ccGenericMesh::getTexCoordinates (unsigned index, TexCoords2D *& tx) const pure virtual
Implemented in ccSubMesh, ccMesh, and ccMeshGroup.
getTexCoordinatesTable()
virtual TextureCoordsContainer* ccGenericMesh::getTexCoordinatesTable () const pure virtual
Returns per-triangle texture coordinates array.
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by define_ccGenericMesh().
getTriangleMtlIndex()
virtual int ccGenericMesh::getTriangleMtlIndex (unsigned triangleIndex) const pure virtual
Returns a given triangle material indexes.
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by ccCropTool::Crop(), and define_ccGenericMesh().
getTriangleNormalIndexes()
virtual void ccGenericMesh::getTriangleNormalIndexes (unsigned triangleIndex, int & i1, int & i2, int & i3) const pure virtual
Returns a triplet of normal indexes for a given triangle (if any)
Parameters
[in] triangleIndex triangle index
[out] i1 first vertex normal index (or -1 if none)
[out] i2 second vertex normal index (or -1 if none)
[out] i3 third vertex normal index (or -1 if none)
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
getTriangleNormals() [1/3]
virtual bool ccGenericMesh::getTriangleNormals (unsigned triangleIndex, CCVector3 & Na, CCVector3 & Nb, CCVector3 & Nc) const pure virtual
Returns a given triangle normal.
Mesh must have triangle normals associated (see hasTriNormals)
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by ToFbxMesh().
getTriangleNormals() [2/3]
virtual bool ccGenericMesh::getTriangleNormals (unsigned triangleIndex, double Na[3], double Nb[3], double Nc[3]) const inline virtual
Reimplemented in ccMesh.
Definition at line 111 of file ecvGenericMesh.h.
getTriangleNormals() [3/3]
virtual bool ccGenericMesh::getTriangleNormals (unsigned triangleIndex, Eigen::Vector3d & Na, Eigen::Vector3d & Nb, Eigen::Vector3d & Nc) const inline virtual
Reimplemented in ccMesh.
Definition at line 117 of file ecvGenericMesh.h.
getTriangleTexCoordinates()
virtual void ccGenericMesh::getTriangleTexCoordinates (unsigned triIndex, TexCoords2D *& tx1, TexCoords2D *& tx2, TexCoords2D *& tx3) const pure virtual
Returns per-triangle texture coordinates (pointer to)
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by ccCropTool::Crop().
getTriangleTexCoordinatesIndexes()
virtual void ccGenericMesh::getTriangleTexCoordinatesIndexes (unsigned triangleIndex, int & i1, int & i2, int & i3) const pure virtual
Returns the triplet of tex coords indexes for a given triangle.
Parameters
triangleIndex triangle index
i1 first vertex tex coords index
i2 second vertex tex coords index
i3 third vertex tex coords index
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
getTriNormsTable()
virtual NormsIndexesTableType* ccGenericMesh::getTriNormsTable () const pure virtual
Returns per-triangle normals shared array.
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
GetVertexBuffer()
static CCVector3* ccGenericMesh::GetVertexBuffer () static protected
getVertexColorFromMaterial()
virtual bool ccGenericMesh::getVertexColorFromMaterial (unsigned triIndex, unsigned char vertIndex, ecvColor::Rgb & C, bool returnColorIfNoTexture) pure virtual
! Returns RGB color of a vertex from a given triangle material/texture **
Parameters
triIndex triangle index
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
GetWireVertexIndexes()
static unsigned* ccGenericMesh::GetWireVertexIndexes () static protected
Returns a pre-initialized array of vertex indexes for wired display.
Array size is MAX_NUMBER_OF_ELEMENTS_PER_CHUNK*6 by default
handleColorRamp()
void ccGenericMesh::handleColorRamp (CC_DRAW_CONTEXT & context) protected
Handles the color ramp display.
hasMaterials()
virtual bool ccGenericMesh::hasMaterials () const pure virtual
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by ccCropTool::Crop(), define_ccGenericMesh(), ccPropertiesTreeDelegate::fillWithMesh(), and cloudViewer::geometry::pybind_meshbase().
hasPerTriangleTexCoordIndexes()
virtual bool ccGenericMesh::hasPerTriangleTexCoordIndexes () const pure virtual
Returns whether this mesh as per-triangle triplets of tex coords indexes.
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by ccCropTool::Crop(), and define_ccGenericMesh().
hasTextures()
virtual bool ccGenericMesh::hasTextures () const pure virtual
Returns whether textures are available for this mesh.
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by define_ccGenericMesh(), and cloudViewer::geometry::pybind_meshbase().
hasTriNormals()
virtual bool ccGenericMesh::hasTriNormals () const pure virtual
Returns whether the mesh has per-triangle normals.
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by ccCropTool::Crop(), define_ccGenericMesh(), ccMesh::HasTriangleNormals(), cloudViewer::geometry::pybind_meshbase(), and ToFbxMesh().
importParametersFrom()
void ccGenericMesh::importParametersFrom (const ccGenericMesh * mesh)
Imports the parameters from another mesh.
Only the specific parameters are imported.
Referenced by ccCropTool::Crop().
interpolateColors()
virtual bool ccGenericMesh::interpolateColors (unsigned triIndex, const CCVector3 & P, ecvColor::Rgb & C) pure virtual
Interpolates RGB colors inside a given triangle.
Parameters
triIndex triangle index
P point where to interpolate (should be inside the triangle!)
[out] C interpolated color
Returns
success
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by ccCropTool::Crop().
interpolateNormalsBC()
virtual bool ccGenericMesh::interpolateNormalsBC (unsigned triIndex, const CCVector3d & w, CCVector3 & N) pure virtual
Interpolates normal(s) inside a given triangle.
Parameters
triIndex triangle index
w barycentric coordinates
[out] N interpolated normal
Returns
success
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
IsCloudVerticesOfMesh()
static bool ccGenericMesh::IsCloudVerticesOfMesh (ccGenericPointCloud * cloud, ccGenericMesh ** mesh = nullptr) static
Helper to determine if the input cloud acts as vertices of a mesh.
Referenced by ccGraphicalSegmentationTool::addEntity(), ccGraphicalSegmentationTool::applySegmentation(), and ccGraphicalSegmentationTool::prepareEntityForRemoval().
isSerializable()
bool ccGenericMesh::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccSerializableObject.
Reimplemented in ccSubMesh, ccMeshGroup, and ccMesh.
Definition at line 43 of file ecvGenericMesh.h.
isShownAsPoints()
virtual bool ccGenericMesh::isShownAsPoints () const inline virtual
Returns whether the mesh is displayed as wired or with plain facets.
Definition at line 185 of file ecvGenericMesh.h.
Referenced by ccPropertiesTreeDelegate::fillWithMesh(), and cloudViewer::geometry::pybind_meshbase().
isShownAsWire()
virtual bool ccGenericMesh::isShownAsWire () const inline virtual
Returns whether the mesh is displayed as wired or with plain facets.
Definition at line 179 of file ecvGenericMesh.h.
Referenced by ccPropertiesTreeDelegate::fillWithMesh(), and cloudViewer::geometry::pybind_meshbase().
materialsShown()
virtual bool ccGenericMesh::materialsShown () const inline virtual
Sets whether textures/material should be displayed or not.
Definition at line 198 of file ecvGenericMesh.h.
Referenced by ccCropTool::Crop(), ccPropertiesTreeDelegate::fillWithMesh(), cloudViewer::geometry::pybind_meshbase(), and ccMesh::toggleMaterials().
minimumFileVersion_MeOnly()
short ccGenericMesh::minimumFileVersion_MeOnly () const override protected virtual
Returns the minimum file version required to save this instance's own data To be overloaded (but still called ;) by subclass. Used internally by minimumFileVersion() to compute the overall minimum.
Reimplemented from ccHObject.
Reimplemented in ccTorus, ccSubMesh, ccSphere, ccQuadric, ccPlane, ccMeshGroup, ccMesh, and ccGenericPrimitive.
normalsAvailable()
bool ccGenericMesh::normalsAvailable () const inline override virtual
Returns whether normals are available.
Reimplemented from cloudViewer::GenericIndexedMesh.
Reimplemented in ccMesh.
Definition at line 256 of file ecvGenericMesh.h.
References ccDrawableObject::hasNormals().
refreshBB()
virtual void ccGenericMesh::refreshBB () pure virtual
Forces bounding-box update.
Implemented in ccSubMesh, ccMeshGroup, and ccMesh.
Referenced by define_ccGenericMesh(), and cloudViewer::geometry::pybind_meshbase().
samplePoints()
ccPointCloud* ccGenericMesh::samplePoints (bool densityBased, double samplingParameter, bool withNormals, bool withRGB, bool withTexture, cloudViewer::GenericProgressCallback * pDlg = nullptr)
Samples points on a mesh.
setGlobalScale()
void ccGenericMesh::setGlobalScale (double scale) override virtual
Sets the scale applied to original coordinates (information storage only)
Reimplemented from ccShiftedObject.
setGlobalShift()
void ccGenericMesh::setGlobalShift (const CCVector3d & shift) override virtual
Sets shift applied to original coordinates (information storage only)
Such a shift can typically be applied at loading time. Original coordinates are equal to '(P/scale - shift)'
Reimplemented from ccShiftedObject.
showMaterials()
virtual void ccGenericMesh::showMaterials (bool state) inline virtual
Sets whether textures should be displayed or not.
Definition at line 201 of file ecvGenericMesh.h.
Referenced by DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertProfileToMesh(), ccEntityAction::convertTextureToColor(), ccCropTool::Crop(), FromFbxMesh(), CSVMatrixFilter::loadFile(), DRCFilter::loadFile(), cloudViewer::geometry::pybind_meshbase(), ccMesh::toggleMaterials(), and GrainsAsEllipsoids::updateMeshAndLineSet().
showNormals()
void ccGenericMesh::showNormals (bool state) override virtual
Sets normals visibility.
Reimplemented from ccDrawableObject.
Referenced by ccEntityAction::clearProperty(), qFacets::createFacets(), ccCropTool::Crop(), qCork::doAction(), qCSF::doAction(), ccTraceTool::finishCurrentTrace(), FromFbxMesh(), STEPFilter::importStepFile(), ccEntityAction::invertNormals(), CSVMatrixFilter::loadFile(), DRCFilter::loadFile(), CommandRemoveNormals::process(), and DistanceMapGenerationDlg::update().
showPoints()
virtual void ccGenericMesh::showPoints (bool state) inline virtual
Sets whether mesh should be displayed as a point cloud or with plain facets
Definition at line 189 of file ecvGenericMesh.h.
Referenced by cloudViewer::geometry::pybind_meshbase().
showTriNorms()
virtual void ccGenericMesh::showTriNorms (bool state) inline virtual
Sets whether to show or not per-triangle normals.
Definition at line 195 of file ecvGenericMesh.h.
Referenced by cloudViewer::geometry::pybind_meshbase().
showWired()
virtual void ccGenericMesh::showWired (bool state) inline virtual
Sets whether mesh should be displayed as a wire or with plain facets.
Definition at line 182 of file ecvGenericMesh.h.
Referenced by ccCompass::estimateStrain(), and cloudViewer::geometry::pybind_meshbase().
stipplingEnabled()
virtual bool ccGenericMesh::stipplingEnabled () const inline virtual
Returns whether polygon stippling is enabled or not.
Definition at line 204 of file ecvGenericMesh.h.
Referenced by cloudViewer::geometry::pybind_meshbase().
toFile_MeOnly()
bool ccGenericMesh::toFile_MeOnly (QFile & out, short dataVersion) const override protected virtual
Save own object data.
Called by 'toFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
out output file
dataVersion target file version for compatibility control
Reimplemented from ccHObject.
Reimplemented in ccTorus, ccSubMesh, ccSphere, ccQuadric, ccPlane, ccMeshGroup, ccMesh, and ccGenericPrimitive.
trianglePicking() [1/3]
virtual bool ccGenericMesh::trianglePicking (const CCVector2d & clickPos, const ccGLCameraParameters & camera, int & nearestTriIndex, double & nearestSquareDist, CCVector3d & nearestPoint, CCVector3d * barycentricCoords = nullptr) const virtual
Brute force triangle picking.
Reimplemented in ccMeshGroup.
Referenced by ccTracePolylineTool::polylineOverSampling().
trianglePicking() [2/3]
virtual bool ccGenericMesh::trianglePicking (unsigned triIndex, const CCVector2d & clickPos, const ccGLCameraParameters & camera, CCVector3d & point, CCVector3d * barycentricCoords = nullptr) const virtual
Triangle picking (single triangle)
trianglePicking() [3/3]
virtual bool ccGenericMesh::trianglePicking (unsigned triIndex, const CCVector2d & clickPos, const ccGLMatrix & trans, bool noGLTrans, const ccGenericPointCloud & vertices, const ccGLCameraParameters & camera, CCVector3d & point, CCVector3d * barycentricCoords = nullptr) const protected virtual
Triangle picking (single triangle)
triNormsShown()
virtual bool ccGenericMesh::triNormsShown () const inline virtual
Returns whether per-triangle normals are shown or not.
Definition at line 192 of file ecvGenericMesh.h.
Referenced by cloudViewer::geometry::pybind_meshbase().
updateTextures() [1/2]
bool ccGenericMesh::updateTextures (const std::string & texture_file)
updateTextures() [2/2]
bool ccGenericMesh::updateTextures (const std::vector< std::string > & texture_files)
Member Data Documentation
m_materialsShown
bool ccGenericMesh::m_materialsShown protected
Texture/material display flag.
Definition at line 304 of file ecvGenericMesh.h.
m_showPoints
bool ccGenericMesh::m_showPoints protected
points display mode
Definition at line 310 of file ecvGenericMesh.h.
m_showWired
bool ccGenericMesh::m_showWired protected
Wireframe display mode.
Definition at line 307 of file ecvGenericMesh.h.
m_stippling
bool ccGenericMesh::m_stippling protected
Polygon stippling state.
Definition at line 313 of file ecvGenericMesh.h.
m_triNormsShown
bool ccGenericMesh::m_triNormsShown protected
Per-triangle normals display flag.
Definition at line 301 of file ecvGenericMesh.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvGenericMesh.h