ACloudViewer: LasScalarFieldSaver Class Reference
LasScalarFieldSaver Class Reference
#include <LasScalarFieldSaver.h>
Public Member Functions
LasScalarFieldSaver ()=default
LasScalarFieldSaver (std::vector< LasScalarField > &&standardFields, std::vector< LasExtraScalarField > &&extraFields)
void setStandarFields (std::vector< LasScalarField > &&standardFields)
void setExtraFields (std::vector< LasExtraScalarField > &&extraFields)
const std::vector< LasExtraScalarField > & extraFields () const
void handleScalarFields (size_t pointIndex, laszip_point &point)
Saves the scalar fields values for pointIndex into the given laszip_point.
void handleExtraFields (size_t pointIndex, laszip_point &point)
Saves the extra scalar fields values for pointIndex into the given laszip_point.
Detailed Description
Class with the logic to save a point clouds scalar field into a LAS file.
Definition at line 36 of file LasScalarFieldSaver.h.
Constructor & Destructor Documentation
LasScalarFieldSaver() [1/2]
LasScalarFieldSaver::LasScalarFieldSaver () default
LasScalarFieldSaver() [2/2]
LasScalarFieldSaver::LasScalarFieldSaver (std::vector< LasScalarField > && standardFields, std::vector< LasExtraScalarField > && extraFields)
Creates a new LasScalarFieldSaver that will save the given standard LAS fields and the LAS extra scalar fields
Definition at line 13 of file LasScalarFieldSaver.cpp.
Member Function Documentation
extraFields()
const std::vector<LasExtraScalarField>& LasScalarFieldSaver::extraFields () const inline
Definition at line 56 of file LasScalarFieldSaver.h.
Referenced by setExtraFields().
handleExtraFields()
void LasScalarFieldSaver::handleExtraFields (size_t pointIndex, laszip_point & point)
Saves the extra scalar fields values for pointIndex into the given laszip_point.
Definition at line 152 of file LasScalarFieldSaver.cpp.
References LasExtraScalarField::f32, LasExtraScalarField::f64, LasExtraScalarField::i16, LasExtraScalarField::i32, LasExtraScalarField::i64, LasExtraScalarField::i8, LasExtraScalarField::Invalid, LasExtraScalarField::MAX_DIM_SIZE, LasExtraScalarField::u16, LasExtraScalarField::u32, LasExtraScalarField::u64, LasExtraScalarField::u8, and LasExtraScalarField::Undocumented.
Referenced by LasSaver::saveNextPoint().
handleScalarFields()
void LasScalarFieldSaver::handleScalarFields (size_t pointIndex, laszip_point & point)
Saves the scalar fields values for pointIndex into the given laszip_point.
Definition at line 20 of file LasScalarFieldSaver.cpp.
References LasScalarField::Classification, LasScalarField::EdgeOfFlightLine, LasScalarField::ExtendedClassification, LasScalarField::ExtendedNumberOfReturns, LasScalarField::ExtendedReturnNumber, LasScalarField::ExtendedScanAngle, LasScalarField::ExtendedScannerChannel, LasScalarField::GpsTime, LasScalarField::Intensity, LasScalarField::KeypointFlag, max(), min(), LasScalarField::NearInfrared, LasScalarField::NumberOfReturns, LasDetails::OVERLAP_FLAG_BIT_MASK, LasScalarField::OverlapFlag, LasScalarField::PointSourceId, LasScalarField::ReturnNumber, SCAN_ANGLE_SCALE, LasScalarField::ScanAngleRank, LasScalarField::ScanDirectionFlag, LasScalarField::SyntheticFlag, LasScalarField::UserData, and LasScalarField::WithheldFlag.
Referenced by LasSaver::saveNextPoint().
setExtraFields()
void LasScalarFieldSaver::setExtraFields (std::vector< LasExtraScalarField > && extraFields) inline
Definition at line 51 of file LasScalarFieldSaver.h.
References extraFields().
Referenced by LasSaver::LasSaver().
setStandarFields()
void LasScalarFieldSaver::setStandarFields (std::vector< LasScalarField > && standardFields) inline
Definition at line 46 of file LasScalarFieldSaver.h.
Referenced by LasSaver::LasSaver().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qLASIO/include/LasScalarFieldSaver.h
/root/ACloudViewer/plugins/core/IO/qLASIO/src/LasScalarFieldSaver.cpp