ACloudViewer: Widgets::ColorPickerButton Class Reference
Widgets::ColorPickerButton Class Reference
Signals
void clicked ()
Public Member Functions
ColorPickerButton (QWidget *parent)
Protected Member Functions
void mousePressEvent (QMouseEvent *e)
void mouseMoveEvent (QMouseEvent *e)
void mouseReleaseEvent (QMouseEvent *e)
void keyPressEvent (QKeyEvent *e)
void keyReleaseEvent (QKeyEvent *e)
void paintEvent (QPaintEvent *e)
void focusInEvent (QFocusEvent *e)
void focusOutEvent (QFocusEvent *e)
Detailed Description
Definition at line 111 of file qtcolorpicker.cpp.
Constructor & Destructor Documentation
ColorPickerButton()
Widgets::ColorPickerButton::ColorPickerButton (QWidget * parent)
Definition at line 941 of file qtcolorpicker.cpp.
Member Function Documentation
clicked
void Widgets::ColorPickerButton::clicked () signal
Referenced by keyReleaseEvent(), and mouseReleaseEvent().
focusInEvent()
void Widgets::ColorPickerButton::focusInEvent (QFocusEvent * e) protected
Definition at line 1006 of file qtcolorpicker.cpp.
References e.
focusOutEvent()
void Widgets::ColorPickerButton::focusOutEvent (QFocusEvent * e) protected
Definition at line 1015 of file qtcolorpicker.cpp.
References e.
keyPressEvent()
void Widgets::ColorPickerButton::keyPressEvent (QKeyEvent * e) protected
Definition at line 973 of file qtcolorpicker.cpp.
References e.
keyReleaseEvent()
void Widgets::ColorPickerButton::keyReleaseEvent (QKeyEvent * e) protected
Definition at line 989 of file qtcolorpicker.cpp.
References clicked(), and e.
mouseMoveEvent()
void Widgets::ColorPickerButton::mouseMoveEvent (QMouseEvent * e) protected
Definition at line 956 of file qtcolorpicker.cpp.
mousePressEvent()
void Widgets::ColorPickerButton::mousePressEvent (QMouseEvent * e) protected
Definition at line 948 of file qtcolorpicker.cpp.
mouseReleaseEvent()
void Widgets::ColorPickerButton::mouseReleaseEvent (QMouseEvent * e) protected
Definition at line 964 of file qtcolorpicker.cpp.
References clicked().
paintEvent()
void Widgets::ColorPickerButton::paintEvent (QPaintEvent * e) protected
Definition at line 1024 of file qtcolorpicker.cpp.
References ecvColor::black(), e, height, offset, and width.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/qtcolorpicker.cpp