ACloudViewer: PdmsTools::PdmsObjects::Stack Class Reference
PdmsTools::PdmsObjects::Stack Class Reference
Item stack.
#include <PdmsTools.h>
Static Public Member Functions
static void Init ()
static void Clear ()
static void Destroy (GenericItem *&item)
Detailed Description
Item stack.
Definition at line 202 of file PdmsTools.h.
Member Function Documentation
Clear()
void PdmsObjects::Stack::Clear () static
Definition at line 53 of file PdmsTools.cpp.
References s_elementsStack.
Destroy()
void PdmsObjects::Stack::Destroy (GenericItem *& item) static
Definition at line 70 of file PdmsTools.cpp.
References s_elementsStack.
Referenced by PdmsTools::PdmsObjects::GroupElement::clear(), PdmsTools::PdmsCommands::ElementCreation::execute(), PdmsTools::PdmsObjects::DesignElement::~DesignElement(), PdmsTools::PdmsObjects::Extrusion::~Extrusion(), and PdmsTools::PdmsObjects::Loop::~Loop().
Init()
void PdmsObjects::Stack::Init () static
Definition at line 48 of file PdmsTools.cpp.
References s_elementsStack.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsTools.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsTools.cpp