ACloudViewer: CVLog Class Reference
CVLog Class Reference abstract
Main log interface.
#include <CVLog.h>
Public Types
enum MessageLevelFlags {
LOG_VERBOSE = 0 , LOG_STANDARD = 1 , LOG_IMPORTANT = 2 , LOG_WARNING = 3 ,
LOG_ERROR = 4 , DEBUG_FLAG = 8
}
Message level.
Public Member Functions
virtual ~CVLog ()
Destructor.
virtual void logMessage (const QString &message, int level)=0
Generic message logging method.
Static Public Member Functions
static CVLog * TheInstance ()
Returns the static and unique instance.
static void RegisterInstance (CVLog *logInstance)
Registers a unique instance.
static void EnableMessageBackup (bool state)
Enables the message backup system.
static int VerbosityLevel ()
Returns the current verbosity level.
static void SetVerbosityLevel (int level)
Sets the verbosity level.
static void LogMessage (const QString &message, int level)
Static shortcut to CVLog::logMessage.
static bool PrintVerbose (const char *format,...)
Prints out a verbose formatted message in console.
static bool PrintVerbose (const QString &message)
QString version of ccLog::PrintVerbose.
static bool Print (const char *format,...)
Prints out a formatted message in console.
static bool Print (const QString &message)
QString version of ccLog::Print.
static bool PrintHigh (const char *format,...)
Prints out an important formatted message in console.
static bool PrintHigh (const QString &message)
QString version of ccLog::PrintHigh.
static bool PrintDebug (const char *format,...)
Same as Print, but works only in Debug mode.
static bool PrintDebug (const QString &message)
QString version of ccLog::PrintDebug.
static bool Warning (const char *format,...)
Prints out a formatted warning message in console.
static bool Warning (const QString &message)
QString version of ccLog::Warning.
static bool WarningDebug (const char *format,...)
Same as Warning, but works only in Debug mode.
static bool WarningDebug (const QString &message)
QString version of ccLog::WarningDebug.
static bool Error (const char *format,...)
Display an error dialog with formatted message.
static bool Error (const QString &message)
QString version of 'Error'.
static bool ErrorDebug (const char *format,...)
Same as Error, but works only in Debug mode.
static bool ErrorDebug (const QString &message)
QString version of ccLog::ErrorDebug.
Detailed Description
Main log interface.
This interface is meant to be used as a unique (static) instance. It should be thread safe!
Definition at line 25 of file CVLog.h.
Member Enumeration Documentation
MessageLevelFlags
enum CVLog::MessageLevelFlags
Message level.
Enumerator
LOG_VERBOSE
Verbose message (Debug)
LOG_STANDARD
Standard message (Print)
LOG_IMPORTANT
Important messages (PrintHigh)
LOG_WARNING
Warning message (Warning)
LOG_ERROR
Error message (Error)
DEBUG_FLAG
Debug flag (reserved)
Definition at line 42 of file CVLog.h.
Constructor & Destructor Documentation
~CVLog()
virtual CVLog::~CVLog () inline virtual
Destructor.
Definition at line 28 of file CVLog.h.
Member Function Documentation
EnableMessageBackup()
void CVLog::EnableMessageBackup (bool state) static
Enables the message backup system.
Stores the messages until a valid logging instance is registered.
Definition at line 55 of file CVLog.cpp.
References s_backupEnabled.
Referenced by InitEnvironment().
Error() [1/2]
bool CVLog::Error (const char * format, ...) static
Display an error dialog with formatted message.
Works just like the 'printf' command.
Returns
always 'false'
Definition at line 143 of file CVLog.cpp.
References LOG_ARGS, and LOG_ERROR.
Referenced by ccPointPairRegistrationDlg::addAlignedPoint(), ecvAnnotationsTool::addAssociatedEntity(), ecvFilterTool::addAssociatedEntity(), ecvMeasurementTool::addAssociatedEntity(), ccHObject::addDependency(), PclUtils::PCLVis::addOrientedCube(), ccGraphicalSegmentationTool::addPointToPolyline(), ccPointPairRegistrationDlg::addReferencePoint(), ccColorScalesManager::addScale(), PclUtils::PCLVis::addTextureMesh(), PclUtils::PCLVis::addTextureMeshFromCCMesh(), ecvDisplayTools::AddToOwnDB(), G3Point::G3PointAction::angles(), ccPointCloud::append(), cvDecimateFilter::apply(), cvIsoSurfaceFilter::apply(), cvSmoothFilter::apply(), cvThresholdFilter::apply(), ccScalarFieldArithmeticsDlg::Apply(), PclUtils::renders::TextureRenderManager::Apply(), PclUtils::renders::PBRRenderer::Apply(), PclUtils::renders::MultiTextureRenderer::Apply(), ccLibAlgorithms::ApplyCCLibAlgorithm(), PclUtils::renders::MeshMaterialExtractor::ApplyMaterialFromMesh(), VtkUtils::VtkMultiTextureRenderer::ApplyPBRMaterial(), ccLibAlgorithms::ApplyScaleMatchingAlgorithm(), ccGraphicalSegmentationTool::applySegmentation(), PclUtils::renders::MeshTextureApplier::ApplyTexturesFromCCMesh(), ccNormalComputationDlg::autoEstimateRadius(), FastGlobalRegistrationDialog::autoEstimateRadius(), cvSelectionExporter::batchExportToFiles(), cvSelectionExporter::batchExportToMeshes(), cvSelectionExporter::batchExportToPointClouds(), ccTrace::buildGradientCost(), ccCone::buildUp(), ccDisc::buildUp(), ccDish::buildUp(), ccExtru::buildUp(), ccPlane::buildUp(), ccQuadric::buildUp(), ccSphere::buildUp(), ccTorus::buildUp(), ccPointPairRegistrationDlg::callHornRegistration(), ccCloudLayersHelper::ccCloudLayersHelper(), ccColorFromScalarDlg::ccColorFromScalarDlg(), ccDefaultPluginInterface::ccDefaultPluginInterface(), ccRenderToFileDlg::ccRenderToFileDlg(), ccEntityAction::changeColorLevels(), ccColorScaleEditorDialog::checkCustomLabelsList(), ccPolyline::Circle(), G3Point::G3PointAction::cleanLabels(), ccPointCloud::clone(), ccMesh::cloneMesh(), G3Point::G3PointAction::cluster(), G3Point::G3PointAction::clusterAndOrClean(), cvSelectionAlgebra::complementOf(), ccComparisonDlg::computeApproxDistances(), ccHistogramWindow::computeBinArrayFromSF(), cloudViewer::geometry::Qhull::ComputeDelaunayTetrahedralization(), ccComparisonDlg::computeDistances(), ccLibAlgorithms::ComputeGeomCharacteristic(), ccEntityAction::computeNormals(), ccPointCloud::computeNormalsWithOctree(), ccKdTree::convertCellIndexToSF(), ccVolumeCalcTool::convertGridToCloud(), ccEntityAction::convertNormalsTo(), ccRasterGrid::convertToCloud(), vtk2cc::ConvertToMultiPolylines(), vtk2cc::ConvertToPolyline(), ccSerializableObject::CorruptError(), ccFacet::Create(), ccColorScalesManager::Create(), cvGenericFilter::createActorFromData(), PclTools::CreateCube(), cloudViewer::geometry::TetraMesh::CreateFromPointCloud(), ecvMeasurementTool::createMeasurementTool(), ccPointCloud::createNewCloudFromVisibilitySelection(), ccSubMesh::createNewSubMeshFromSelection(), cvContourTool::createUi(), cvDistanceTool::createUi(), cvProtractorTool::createUi(), ccEntityAction::DBScanCluster(), define_ccLog(), ccComparisonDlg::determineBestOctreeLevel(), cvSelectionAlgebra::differenceOf(), FileIOFilter::DisplayErrorMessage(), ecvUtils::DisplayLockedVerticesWarning(), MainWindow::dispToConsole(), qCloudLayers::doAction(), qHoughNormals::doAction(), qRansacSD::doAction(), ccGraphicalSegmentationTool::doActionUseExistingPolyline(), qSRA::doProjectCloudDistsInGrid(), PclUtils::PCLVis::draw(), ccDBRoot::dropMimeData(), ecvShortcutDecorator::ecvShortcutDecorator(), ecvAnimationParamDlg::enableListener(), MainWindow::enablePickingOperation(), ccCommandLineParser::error(), errorCallback(), ccAlignDlg::estimateDelta(), PythonInterpreter::executeFunction(), PclUtils::PCLVis::expandBounds(), ecvAnnotationsTool::exportAnnotationToSF(), ccEntityAction::exportCoordToSF(), ccColorScaleEditorDialog::exportCustomLabelsList(), cvSelectionExporter::exportFromSourceCloud(), cvSelectionExporter::exportFromSourceMesh(), ccRasterizeTool::ExportGeoTiff(), ccDBRoot::exportImages(), ecvMeasurementTool::exportMeasurement(), ccEntityAction::exportNormalToSF(), GrainsAsEllipsoids::exportResultsAsCloud(), MatrixDisplayDlg::exportToASCII(), ccPointListPickingDlg::exportToASCII(), cvSelectionAnnotationManager::exportToFile(), cvSelectionExporter::exportToFile(), cvSelectionExporter::exportToMesh(), ccPointListPickingDlg::exportToNewCloud(), ccPointListPickingDlg::exportToNewPolyline(), cvSelectionExporter::exportToPointCloud(), ccContourExtractor::ExtractFlatContour(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), cvSelectionExporter::extractSelection(), LasSaveDialog::extraFieldsToSave(), CVTools::FileMappingReader(), CVTools::FileMappingWriter(), TreeIso::Final_seg_pcd(), ccPointCloud::From(), ccBoundingBoxEditorDlg::fromClipboardClicked(), masc::Classifier::fromFile(), PclUtils::renders::MaterialConverter::FromMaterialSet(), ccDBRoot::gatherRecursiveInformation(), ccRasterizeTool::generateCloud(), ccRasterizeTool::generateContours(), ccRasterizeTool::generateHillshade(), ccRasterizeTool::generateImage(), ccRasterizeTool::generateMesh(), ccRasterizeTool::generateRaster(), PclUtils::PCLVis::getActorById(), ccComparisonDlg::getBestOctreeLevel(), GetConeProfile(), cvContourTool::getOutput(), ccPointListPickingDlg::getPickedPoints(), PclUtils::PCLVis::getPropById(), G3Point::getRandomColors(), ccAlignDlg::getSampledData(), ccAlignDlg::getSampledModel(), ImageFileFilter::GetSaveFilename(), ecvFilterTool::getSlice(), cvTooltipFormatter::getTooltipInfo(), ccMesh::getVertexColorFromMaterial(), ccOctree::GuessBestRadiusAutoComputeOctree(), ccPointCloud::hidePointsByScalarValue(), cvSelectionHighlighter::highlightSelection(), ccRegistrationTools::ICP(), cvSelectionAnnotationManager::importFromFile(), ccInnerRect2DFinder::init(), ccWaveWidget::init(), ccPointPairRegistrationDlg::init(), TreeIso::Init_seg_pcd(), PclMeasurementTools::initialize(), PclFiltersTool::initialize(), cvGenericMeasurementTool::initModel(), TreeIso::Intermediate_seg_pcd(), ccEntityAction::interpolateColors(), ccPointCloudInterpolator::InterpolateScalarFieldsFrom(), ccEntityAction::interpolateSFs(), cvSelectionAlgebra::intersectionOf(), ccComparisonDlg::isValid(), G3Point::G3PointAction::keep(), cloudViewer::loadArrayFromFile(), cloudViewer::loadArrayFromFileIntoArray(), cloudViewer::loadArrayOfArraysFromFile(), IcmFilter::LoadCalibratedImages(), AsciiFilter::loadCloudFromFormatedAsciiStream(), ObjFilter::loadFile(), VTKFilter::loadFile(), IcmFilter::loadFile(), SimpleBinFilter::loadFile(), DRCFilter::loadFile(), LasIOFilter::loadFile(), LASFilter::loadFile(), PlyFilter::loadFile(), BundlerFilter::loadFileExtended(), ccApplyTransformationDlg::loadFromASCIIFile(), FileIOFilter::LoadFromFile(), ccColorScale::LoadFromXML(), LoadScan(), main(), ccColorFromScalarDlg::maxChanged(), ccSerializableObject::MemoryError(), G3Point::G3PointAction::merge(), ccColorFromScalarDlg::minChanged(), ccHistogramWindowDlg::onExportToImage(), G3PointPlots::onExportToImage(), ccTracePolylineTool::onItemPicked(), VTKExtensions::vtkCustomInteractorStyle::OnKeyDown(), ccWaveDialog::onPointPickingButtonToggled(), Train3DMASCDialog::openTraceFile(), ccGenericPrimitive::operator+=(), ccMesh::operator+=(), ccPointCloud::operator+=(), ccMinimumSpanningTreeForNormsDirection::OrientNormals(), ccFastMarchingForNormsDirection::OrientNormals(), ccEntityAction::orientNormalsFM(), ccEntityAction::orientNormalsMST(), ccPointCloud::partialClone(), ccMesh::partialClone(), cvSelectionAlgebra::performOperation(), HSVDialog::pickPoint(), RgbDialog::pickPoint_first(), ScalarDialog::pickPoint_first(), RgbDialog::pickPoint_second(), ScalarDialog::pickPoint_second(), ccPlaneEditDlg::pickPointAsCenter(), ecvCameraParamEditDlg::pickPointAsPivot(), ccComparisonDlg::prepareEntitiesForComparison(), masc::Tools::PrepareFeatures(), cvHardwareSelector::PrepareSelect(), qAnimationDlg::preview(), CommandMergeMeshes::process(), G3Point::G3PointAction::processNewStacks(), ccMesh::pushSubdivide(), CVTools::QMappingReader(), CVTools::QMappingWriter(), ccSerializableObject::ReadError(), ccPointPairRegistrationDlg::removeAlignedPoint(), ccPointPairRegistrationDlg::removeRefPoint(), ccPointCloud::removeVisiblePoints(), qAnimationDlg::render(), PclUtils::PCLVis::renderToImage(), PCLDisplayTools::renderToImage(), ccPointCloud::reserve(), ccPointCloud::reserveTheFWFTable(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveTheRGBTable(), cvCutFilter::resetBoxWidget(), cvCutFilter::resetPlaneWidget(), cvCutFilter::resetSphereWidget(), ccPointCloud::resize(), ccPointCloud::resizeTheFWFTable(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), ccTracePolylineTool::restart(), ecvLayoutManager::restoreCustomLayout(), ecvLayoutManager::restoreDefaultLayout(), ccEntityAction::rgbGaussianFilter(), ConfusionMatrix::save(), cloudViewer::saveArrayToFile(), ccColorScale::saveAsXML(), ccBoundingBoxEditorDlg::saveBoxAndAccept(), masc::Tools::SaveClassifier(), ecvLayoutManager::saveCustomLayout(), MainWindow::saveGUIElementsPos(), cvSelectionExporter::saveObjectToFileWithDialog(), SaveScan(), FileIOFilter::SaveToFile(), DepthMapFileFilter::saveToFile(), DxfFilter::saveToFile(), MAFilter::saveToFile(), LasIOFilter::saveToFile(), LASFilter::saveToFile(), G3Point::G3PointAction::segment(), ccGraphicalSegmentationTool::segment(), cvHardwareSelector::Select(), ccPointCloud::SelectByIndex(), SendError(), ecvCustomViewpointButtonDlg::setConfigurations(), ccPointCloud::setCoordFromSF(), cvViewSelectionManager::setCurrentSelection(), ccColorFromScalarDlg::setDefaultSatValuePerChannel(), cvGenericFilter::setInput(), ecvConsole::setLogFile(), ccPointCloud::setRGBColorByHeight(), ecvCustomViewpointButtonDlg::setToolTips(), ccEntityAction::sfArithmetic(), ccEntityAction::sfConvertToRandomRGB(), ccEntityAction::sfGaussianFilter(), ccGamepadManager::showMessage(), cvGenericFilter::showOutline(), sMetaDataValid(), qAnimationDlg::smoothTrajectory(), ccPolyline::split(), ecvPoissonReconDlg::start(), ecvAnnotationsTool::start(), ecvFilterByLabelDlg::start(), ccPointPairRegistrationDlg::start(), ccPointPickingGenericInterface::start(), ccEntityAction::statisticalTest(), ccMesh::subdivide(), cvSelectionAlgebra::symmetricDifferenceOf(), cvSelectionAlgebra::unionOf(), ccPointCloud::unroll(), PclUtils::renders::TextureRenderManager::Update(), GrainsAsEllipsoids::updateBBoxOnlyOne(), ccColorFromScalarDlg::updateChannel(), ccRasterizeTool::updateGrid(), ccRasterizeTool::updateGridAndDisplay(), ccVolumeCalcTool::updateGridAndDisplay(), ccColorFromScalarDlg::updateHistogram(), GrainsAsEllipsoids::updateMeshAndLineSet(), ccGraphicalSegmentationTool::updatePolyLine(), PclUtils::PCLVis::updateShadingMode(), qAnimationDlg::updateSmoothCameraTrajectory(), ccColorFromScalarDlg::updateSpinBoxLimits(), PclUtils::renders::TextureRendererBase::ValidateActor(), PclUtils::renders::TextureRendererBase::ValidateMaterials(), G3Point::G3PointAction::wolman(), Tiler::writeAll(), and ccSerializableObject::WriteError().
Error() [2/2]
bool CVLog::Error (const QString & message) static
QString version of 'Error'.
Definition at line 148 of file CVLog.cpp.
References LOG_ERROR, and LogMessage().
ErrorDebug() [1/2]
bool CVLog::ErrorDebug (const char * format, ...) static
Same as Error, but works only in Debug mode.
Works just like the 'printf' command.
Returns
always 'false'
Definition at line 181 of file CVLog.cpp.
References DEBUG_FLAG, LOG_ARGS, and LOG_ERROR.
Referenced by ccHObject::addChild(), and ccHObject::New().
ErrorDebug() [2/2]
bool CVLog::ErrorDebug (const QString & message) static
QString version of ccLog::ErrorDebug.
Definition at line 188 of file CVLog.cpp.
References DEBUG_FLAG, LOG_ERROR, and LogMessage().
LogMessage()
void CVLog::LogMessage (const QString & message, int level) static
Static shortcut to CVLog::logMessage.
Definition at line 64 of file CVLog.cpp.
References logMessage(), s_backupEnabled, s_backupMessages, s_instance, and s_verbosityLevel.
Referenced by cloudViewer::LogWidget::Append(), define_ccLog(), Error(), ErrorDebug(), ccLogger< level >::flush(), Print(), PrintDebug(), PrintHigh(), PrintVerbose(), Warning(), WarningDebug(), and cloudViewer::LogWidget::~LogWidget().
logMessage()
virtual void CVLog::logMessage (const QString & message, int level) pure virtual
Generic message logging method.
To be implemented by child class.
Warning
MUST BE THREAD SAFE!
Parameters
message message
level message severity (see MessageLevelFlags)
Implemented in PyPrintLogger, and ecvConsole.
Referenced by LogMessage(), and RegisterInstance().
Print() [1/2]
bool CVLog::Print (const char * format, ...) static
Prints out a formatted message in console.
Works just like the 'printf' command.
Returns
always 'true'
Definition at line 113 of file CVLog.cpp.
References LOG_ARGS, and LOG_STANDARD.
Referenced by cvSelectionAnnotationManager::addAnnotation(), cvSelectionAnnotationManager::addAnnotationAt(), ecvShortcutDecorator::addShortcut(), fgr::CApp::AdvancedMatching(), ccPointPairRegistrationDlg::align(), ccDBRoot::alignCameraWithEntity(), ccGraphicalTransformationTool::apply(), ccPointPairRegistrationDlg::apply(), ccDisplayOptionsDlg::apply(), PclUtils::renders::MultiTextureRenderer::Apply(), ccLibAlgorithms::ApplyCCLibAlgorithm(), PclUtils::renders::MeshMaterialExtractor::ApplyMaterialFromMesh(), VtkUtils::VtkMultiTextureRenderer::ApplyPBRMaterial(), PclUtils::renders::MeshTextureApplier::ApplyPBRTextures(), ccLibAlgorithms::ApplyScaleMatchingAlgorithm(), PclUtils::renders::MeshTextureApplier::ApplyTexturesFromCCMesh(), TemplateAlignment::applyTransformation(), cvSelectionExporter::batchExportToFiles(), cvSelectionExporter::batchExportToMeshes(), cvSelectionExporter::batchExportToPointClouds(), cvSelectionPipeline::captureBuffersForFastPreSelection(), ccWaveDialog::ccWaveDialog(), PclAnnotationTool::changeAnnotationType(), masc::Classifier::classify(), G3Point::G3PointAction::cleanLabels(), cvSelectionAnnotationManager::clearAll(), cvViewSelectionManager::clearCurrentSelection(), Train3DMASCDialog::closeTraceFile(), G3Point::G3PointAction::cluster(), cvSelectionAlgebra::complementOf(), ccPointCloud::compressFWFData(), CorrespondenceMatching::compute(), TemplateAlignment::compute(), ConvexConcaveHullReconstruction::compute(), GreedyTriangulation::compute(), MarchingCubeReconstruction::compute(), NurbsCurveFitting::compute(), NurbsSurfaceReconstruction::compute(), PoissonReconstruction::compute(), FastGlobalRegistrationFilter::compute(), ccComparisonDlg::computeApproxDistances(), ccComparisonDlg::computeDistances(), ComputeKmeansClustering(), ComputeMathOpWithNearestNeighbor(), ccPointCloud::computeNormalsWithOctree(), ccEntityAction::computeOctree(), ccEntityAction::computeStatParams(), ccVolumeCalcTool::ComputeVolume(), Mouse3DInput::connect(), cvSelectionPipeline::convertToCvSelectionData(), ccPointPairRegistrationDlg::convertToSphereCenter(), PclTools::CreateTexturingMesh(), ccEntityAction::DBScanCluster(), define_ccLog(), ccGriddedTools::DetectParameters(), cvSelectionAlgebra::differenceOf(), MainWindow::dispToConsole(), ccGraphicalSegmentationTool::doExportSegmentationPolyline(), QVTKWidgetCustom::dropEvent(), ecvKeySequences::dumpShortcuts(), ccGamepadManager::enableDevice(), masc::Classifier::evaluate(), QVTKWidgetCustom::event(), cvSelectionPipeline::executePolygonSelection(), cvSelectionPipeline::executeRectangleSelection(), cvViewSelectionManager::expandSelection(), PclAnnotationTool::exportAnnotations(), ecvAnnotationsTool::exportAnnotationToSF(), ccRasterizeTool::exportContourLines(), ccColorScaleEditorDialog::exportCurrentScale(), cvSelectionExporter::exportFromSourceMesh(), ccRasterizeTool::ExportGeoTiff(), ccVolumeCalcTool::exportGridAsCloud(), ccDBRoot::exportImages(), ecvMeasurementTool::exportMeasurement(), MatrixDisplayDlg::exportToASCII(), ccPointListPickingDlg::exportToASCII(), MatrixDisplayDlg::exportToClipboard(), ccHistogramWindowDlg::exportToCSV(), G3PointPlots::exportToCSV(), cvSelectionAnnotationManager::exportToFile(), cvSelectionExporter::exportToFile(), cvSelectionExporter::exportToMesh(), cvSelectionPipeline::extractSelectionIds(), ccPropertiesTreeDelegate::fillModel(), TreeIso::Final_seg_pcd(), PclUtils::renders::MaterialConverter::FromCCMaterial(), PclUtils::renders::MaterialConverter::FromPCLMaterial(), ccColorScalesManager::fromPersistentSettings(), ccRasterizeTool::generateASCIIMatrix(), ccRasterizeTool::generateCloud(), ccRasterizeTool::generateContours(), ccRasterizeTool::generateImage(), ccRasterizeTool::generateMesh(), PCLModules::GetConvexHullReconstruction(), G3Point::G3PointAction::GetG3PointAction(), cvProbeFilter::getOutput(), cvContourTool::getOutput(), cvProtractorTool::getOutput(), ccMouseCircle::getRadiusWorld(), PCLModules::GetRegionGrowing(), PCLModules::GetRegionGrowingRGB(), cvViewSelectionManager::getSourcePointCloud(), ccNormalVectors::GuessBestRadius(), ccOctree::GuessBestRadius(), ccRegistrationTools::ICP(), cvSelectionAnnotationManager::importFromFile(), ccColorScaleEditorDialog::importScale(), STEPFilter::importStepFile(), TreeIso::Init_seg_pcd(), InitEnvironment(), MainWindow::initPlugins(), TreeIso::Intermediate_seg_pcd(), cvSelectionAlgebra::intersectionOf(), G3Point::G3PointAction::keep(), PclAnnotationTool::keyboardEventProcess(), LasWaveformLoader::LasWaveformLoader(), Annotaions::loadAnnotations(), IcmFilter::LoadCalibratedImages(), CSVMatrixFilter::loadFile(), PcdFilter::loadFile(), BinFilter::loadFile(), ObjFilter::loadFile(), PTXFilter::loadFile(), STLFilter::loadFile(), VTKFilter::loadFile(), IcmFilter::loadFile(), PovFilter::loadFile(), SimpleBinFilter::loadFile(), DRCFilter::loadFile(), FBXFilter::loadFile(), LASFWFFilter::loadFile(), LasIOFilter::loadFile(), LASFilter::loadFile(), RDBFilter::loadFile(), PlyFilter::loadFile(), masc::Tools::LoadFile(), IoAbstractLoader::loadFile(), FileIOFilter::LoadFromFile(), ccColorScale::LoadFromXML(), LoadImage(), ccPluginManager::loadPlugins(), LoadScan(), LogPythonHome(), LogPythonPath(), main(), MainWindow::MainWindow(), G3Point::G3PointAction::merge(), ccMesh::mergeDuplicatedVertices(), IoUtils::newCCMeshFromAIMesh(), NodeToConsole(), ccHistogramWindowDlg::onExportToImage(), G3PointPlots::onExportToImage(), HSVDialog::onItemPicked(), RgbDialog::onItemPicked(), ScalarDialog::onItemPicked(), ecvMeasurementTool::onItemPicked(), VTKExtensions::vtkCustomInteractorStyle::OnKeyDown(), ecvPrimitiveFactoryDlg::onMatrixTextChange(), ecvDisplayTools::onPointPicking(), Train3DMASCDialog::openTraceFile(), LasExtraScalarField::ParseExtraScalarFields(), ccMesh::partialClone(), masc::ContextBasedFeature::prepare(), masc::Tools::PrepareFeatures(), ccCommandLineParser::print(), PrintSystemHardwareInfo(), ccPointPropertiesDlg::processPickedPoint(), cvSelectionPipeline::promptUser(), ccEntityAction::RansacSegmentation(), cvSelectionPipeline::refinePolygonSelection(), ccMaterial::releaseTexture(), cvSelectionAnnotationManager::removeAnnotation(), ccPointCloud::RemoveNonFinitePoints(), ecvDisplayTools::RenderToFile(), ResolveNormalsWithMST(), ccEntityAction::rgbGaussianFilter(), ccPointCloudLODThread::run(), Annotaions::saveAnnotations(), cvSelectionExporter::saveObjectToFileWithDialog(), SaveScan(), FileIOFilter::SaveToFile(), AsciiFilter::saveToFile(), SimpleBinFilter::saveToFile(), FBXFilter::saveToFile(), LASFWFFilter::saveToFile(), LasIOFilter::saveToFile(), ecvApplicationBase::setAppStyle(), cvSelectionPipeline::setEnableCaching(), PclAnnotationTool::setInputCloud(), ecvDisplayTools::SetLineWidth(), ecvConsole::setLogFile(), cvSelectionPipeline::setPointPickingRadius(), ecvDisplayTools::SetPointSize(), ccGamepadManager::setupGamepadInput(), ccEntityAction::sfFromColor(), ccEntityAction::sfGaussianFilter(), ShowDurationNow(), ecvPoissonReconDlg::start(), ccEntityAction::statisticalTest(), PclAnnotationTool::stop(), cvSelectionAlgebra::symmetricDifferenceOf(), TileLasReader(), ccWaveform::ToASCII(), ccBoundingBoxEditorDlg::toClipboardClicked(), masc::Classifier::toFile(), cvSelectionAlgebra::unionOf(), ccRasterizeTool::updateGrid(), ccNormalVectors::UpdateNormalOrientations(), ccPlaneEditDlg::updatePlane(), ccGenericMesh::updateTextures(), PCLModules::VoxelGridFilter(), and G3Point::G3PointAction::wolman().
Print() [2/2]
bool CVLog::Print (const QString & message) static
QString version of ccLog::Print.
Definition at line 118 of file CVLog.cpp.
References LOG_STANDARD, and LogMessage().
PrintDebug() [1/2]
bool CVLog::PrintDebug (const char * format, ...) static
Same as Print, but works only in Debug mode.
Works just like the 'printf' command.
Returns
always 'true'
Definition at line 153 of file CVLog.cpp.
References DEBUG_FLAG, LOG_ARGS, and LOG_STANDARD.
Referenced by ecvMeasurementTool::addInstance(), PclUtils::PCLVis::addScalarFieldToVTK(), PclUtils::PCLVis::addTextureMesh(), PclUtils::PCLVis::addTextureMeshFromCCMesh(), MainWindow::addToDB(), ccGraphicalTransformationTool::apply(), PclUtils::renders::TextureRenderManager::Apply(), PclUtils::renders::PBRRenderer::Apply(), PclUtils::renders::MultiTextureRenderer::Apply(), VtkUtils::VtkMultiTextureRenderer::ApplyPBRMaterial(), PclUtils::renders::MeshTextureApplier::ApplyTexturesFromMaterialSet(), ccCameraSensor::computeOrthoRectificationParams(), cc2smReader::ConVertToPCLMaterial(), PclUtils::renders::MaterialConverter::CountMapKd(), IoUtils::createMaterialSetForMesh(), cvPointPickingHelper::cvPointPickingHelper(), ccComparisonDlg::determineBestOctreeLevel(), cvGenericMeasurementTool::disableShortcuts(), QVTKWidgetCustom::event(), ccRasterizeTool::ExportGeoTiff(), ccMaterialSet::findMaterialByName(), ccMaterialSet::findMaterialByUniqueID(), PclUtils::renders::MaterialConverter::FromCCMaterial(), FromFbxMesh(), PclUtils::renders::MaterialConverter::FromMaterialSet(), PclUtils::renders::MaterialConverter::FromPCLMaterial(), CVTools::FromUnicode(), ccRasterizeTool::generateContours(), cc2smReader::getVtkPolyDataFromMeshCloud(), MainWindow::initPlugins(), ccMaterial::loadAndSetTextureMap(), cloudViewer::loadArrayFromFile(), cloudViewer::loadArrayFromFileIntoArray(), cloudViewer::loadArrayOfArraysFromFile(), AsciiFilter::loadCloudFromFormatedAsciiStream(), PhotoScanFilter::loadFile(), PovFilter::loadFile(), PlyFilter::loadFile(), cvContourTool::lockInteraction(), cvDistanceTool::lockInteraction(), myMessageOutput(), qAnimationDlg::onAutoStepsDurationToggled(), qAnimationDlg::onTotalTimeChanged(), cloudViewer::saveArrayOfArraysToFile(), cloudViewer::saveArrayToFile(), PclUtils::renders::TextureRenderManager::SelectRenderer(), PclUtils::PCLVis::setCurrentSourceObject(), PclUtils::PCLVis::setScalarFieldName(), ccMaterial::setTexture(), ecvLayoutManager::setupDefaultLayout(), cvGenericMeasurementTool::setupShortcuts(), PclUtils::PCLVis::syncAllScalarFieldsToVTK(), ToFbxMesh(), PclUtils::PCLVis::ToggleCameraOrientationWidget(), CVTools::ToUnicode(), cvContourTool::unlockInteraction(), cvDistanceTool::unlockInteraction(), cvProtractorTool::unlockInteraction(), PclUtils::renders::TextureRenderManager::Update(), PclUtils::PCLVis::updateShadingMode(), and PclUtils::PCLVis::updateTexture().
PrintDebug() [2/2]
bool CVLog::PrintDebug (const QString & message) static
QString version of ccLog::PrintDebug.
Definition at line 160 of file CVLog.cpp.
References DEBUG_FLAG, LOG_STANDARD, and LogMessage().
PrintHigh() [1/2]
bool CVLog::PrintHigh (const char * format, ...) static
Prints out an important formatted message in console.
Works just like the 'printf' command.
Returns
always 'true'
Definition at line 123 of file CVLog.cpp.
References LOG_ARGS, and LOG_IMPORTANT.
PrintHigh() [2/2]
bool CVLog::PrintHigh (const QString & message) static
QString version of ccLog::PrintHigh.
Definition at line 128 of file CVLog.cpp.
References LOG_IMPORTANT, and LogMessage().
PrintVerbose() [1/2]
bool CVLog::PrintVerbose (const char * format, ...) static
Prints out a verbose formatted message in console.
Works just like the 'printf' command.
Returns
always 'true'
Definition at line 103 of file CVLog.cpp.
References LOG_ARGS, and LOG_VERBOSE.
Referenced by cvSelectionAnnotationManager::addAnnotation(), ecvKeySequences::addModalShortcut(), PclUtils::PCLVis::addTextureMesh(), PclUtils::PCLVis::addTextureMeshFromCCMesh(), VtkUtils::VtkMultiTextureRenderer::ApplyPBRMaterial(), cvGenericSelectionTool::applySelectionModifierUnified(), PclUtils::ImageVis::changeOpacity(), cvSelectionFilter::combineAND(), cvSelectionFilter::combineOR(), cvSelectionPipeline::combineSelections(), cvSelectionToolController::connectHighlighter(), cvSelectionPipeline::convertToCvSelectionData(), cvGenericSelectionTool::createSelectionFromPick(), cvFindDataDockWidget::cvFindDataDockWidget(), cvSelectionAlgebra::cvSelectionAlgebra(), cvSelectionAnnotationManager::cvSelectionAnnotationManager(), cvSelectionFilter::cvSelectionFilter(), cvSelectionHighlighter::cvSelectionHighlighter(), cvSelectionPropertiesWidget::cvSelectionPropertiesWidget(), ecvKeySequences::disableSiblings(), ecvDisplayTools::doPicking(), ecvKeySequences::dumpShortcuts(), ecvKeySequences::ecvKeySequences(), ecvKeySequences::enableNextSibling(), cvRenderViewSelectionReaction::endSelection(), cvViewSelectionManager::expandSelection(), cvSelectionAlgebra::expandSelection(), cvSelectionExporter::exportFromSourceCloud(), cvSelectionExporter::exportFromSourceMesh(), cvSelectionExporter::exportToPointCloud(), cvSelectionAlgebra::extractBoundary(), cvSelectionPipeline::extractDataFromSelection(), cvSelectionExporter::extractSelection(), cvSelectionFilter::filterByArea(), cvSelectionFilter::filterByAttributeComparison(), cvSelectionFilter::filterByAttributeRange(), cvSelectionFilter::filterByBoundingBox(), cvSelectionFilter::filterByDistanceFromPoint(), cvSelectionFilter::filterByNeighborCount(), cvSelectionFilter::filterByNormalAngle(), cvSelectionBase::getAllPolyDataFromVisualizer(), cvSelectionBase::getDataActors(), cvSelectionBase::getDataFromActor(), cvProtractorTool::getOutput(), cvViewSelectionManager::getPolyData(), cvSelectionBase::getPolyDataForSelection(), cvGenericSelectionTool::getPolyDataForSelection(), cvSelectionPipeline::getPrimaryDataFromSelection(), cvRenderViewSelectionReaction::getSelectionModifier(), cvViewSelectionManager::getSourceMesh(), cvViewSelectionManager::getSourcePointCloud(), cvSelectionAlgebra::growPointSelection(), cvSelectionAlgebra::growSelection(), cvSelectionToolController::handleEscapeKey(), cvGenericSelectionTool::hardwareSelectInRegion(), cvFindDataDockWidget::hideEvent(), PclUtils::PCLVis::hidePclMarkerAxes(), cvSelectionHighlighter::highlightSelection(), cvSelectionToolController::initialize(), cvGenericSelectionTool::initializePickers(), cvSelectionToolController::invalidateCache(), cvSelectionFilter::invert(), ccMaterial::loadAndSetTextureMap(), ObjFilter::loadFile(), QVTKWidgetCustom::mouseReleaseEvent(), cvSelectionToolController::onModifierChanged(), cvSelectionToolController::onSelectionFinished(), cvGenericSelectionTool::pickAtPosition(), cvSelectionToolController::registerAction(), cvSelectionToolController::registerManipulationActions(), cvSelectionToolController::registerModifierActions(), ecvKeySequences::removeModalShortcut(), ecvKeySequences::reorder(), ecvLayoutManager::restoreCustomLayout(), ecvLayoutManager::restoreDefaultLayout(), ecvLayoutManager::restoreGUILayout(), ecvLayoutManager::saveCustomLayout(), ecvLayoutManager::saveGUILayout(), cvSelectionPipeline::selectCellsInPolygon(), cvSelectionPipeline::selectPointsInPolygon(), cvSelectionHighlighter::setCellLabelArray(), cvViewSelectionManager::setCurrentSelection(), PclUtils::PCLVis::SetDataAxesGridProperties(), cvSelectionAnnotationManager::setDefaultLabelProperties(), cvViewSelectionManager::setGrowSelectionRemoveIntermediateLayers(), cvSelectionHighlighter::setHighlightColor(), cvSelectionHighlighter::setHighlightOpacity(), cvSelectionHighlighter::setLabelProperties(), cvSelectionHighlighter::setLineWidth(), PclUtils::PCLVis::setMeshOpacity(), cvGenericSelectionTool::setPickerTolerance(), cvSelectionHighlighter::setPointLabelArray(), cvSelectionHighlighter::setPointSize(), cvSelectionToolController::setupActions(), ecvLayoutManager::setupDefaultLayout(), cvSelectionToolController::setVisualizer(), cvSelectionPipeline::setVisualizer(), cvFindDataDockWidget::showEvent(), PclUtils::PCLVis::showOrientationMarkerWidgetAxes(), PclUtils::PCLVis::showPclMarkerAxes(), cvSelectionAlgebra::shrinkPointSelection(), cvSelectionAlgebra::shrinkSelection(), cvRenderViewSelectionReaction::storeCurrentStyle(), cvSelectionPropertiesWidget::syncUIWithHighlighter(), PclUtils::PCLVis::ToggleCameraOrientationWidget(), cvSelectionPropertiesWidget::updateSelection(), cvFindDataDockWidget::~cvFindDataDockWidget(), and cvSelectionPipeline::~cvSelectionPipeline().
PrintVerbose() [2/2]
bool CVLog::PrintVerbose (const QString & message) static
QString version of ccLog::PrintVerbose.
Definition at line 108 of file CVLog.cpp.
References LOG_VERBOSE, and LogMessage().
RegisterInstance()
void CVLog::RegisterInstance (CVLog * logInstance) static
Registers a unique instance.
Definition at line 81 of file CVLog.cpp.
References logMessage(), s_backupMessages, and s_instance.
Referenced by define_pycc(), ecvConsole::Init(), ecvConsole::ReleaseInstance(), and ecvConsole::TheInstance().
SetVerbosityLevel()
void CVLog::SetVerbosityLevel (int level) static
Sets the verbosity level.
Messages below this level will be filtered out.
Definition at line 59 of file CVLog.cpp.
References LOG_ERROR, and s_verbosityLevel.
Referenced by ccDisplayOptionsDlg::apply().
TheInstance()
CVLog * CVLog::TheInstance () static
Returns the static and unique instance.
Definition at line 53 of file CVLog.cpp.
References s_instance.
Referenced by define_ccLog(), ccCommandLineParser::exportEntity(), and CommandLogFile::process().
VerbosityLevel()
int CVLog::VerbosityLevel () static
Returns the current verbosity level.
Definition at line 57 of file CVLog.cpp.
References s_verbosityLevel.
Referenced by ccDisplayOptionsDlg::apply().
Warning() [1/2]
bool CVLog::Warning (const char * format, ...) static
Prints out a formatted warning message in console.
Works just like the 'printf' command.
Returns
always 'false'
Definition at line 133 of file CVLog.cpp.
References LOG_ARGS, and LOG_WARNING.
Referenced by PlyOpenDlg::addAllStdPropsAsSF(), cvSelectionAnnotationManager::addAnnotation(), PclUtils::PCLVis::addCaption(), ccGraphicalTransformationTool::addEntity(), ccGraphicalSegmentationTool::addEntity(), ecvMeasurementTool::addInstance(), LasCloudChunk::addLasFieldsToCloud(), ccPickingHub::addListener(), ecvKeySequences::addModalShortcut(), PclUtils::PCLVis::addPolyline(), PclUtils::ImageVis::addRGBImage(), PclUtils::PCLVis::addScalarBar(), ccPointCloud::addScalarField(), PclUtils::PCLVis::addScalarFieldToVTK(), ecvShortcutDecorator::addShortcut(), PclUtils::PCLVis::addTextureMesh(), MainWindow::addToDB(), ccMesh::addTriangleNorm(), ccPointPairRegistrationDlg::align(), ccPointCloud::append(), ccMaterialSet::append(), ccPropertiesTreeDelegate::appendWideRow(), ecvFilterByLabelDlg::apply(), ccGraphicalTransformationTool::apply(), ccPointPairRegistrationDlg::apply(), ccScalarFieldArithmeticsDlg::Apply(), PclUtils::renders::MultiTextureRenderer::Apply(), ccComparisonDlg::applyAndExit(), ccLibAlgorithms::ApplyCCLibAlgorithm(), ecvCustomViewpointsToolbar::ApplyCustomViewpoint(), ccPointCloud::applyFilterToRGB(), PclUtils::renders::MeshMaterialExtractor::ApplyMaterialFromMesh(), VtkUtils::VtkMultiTextureRenderer::ApplyPBRMaterial(), ccLibAlgorithms::ApplyScaleMatchingAlgorithm(), ccGraphicalSegmentationTool::applySegmentation(), cvGenericSelectionTool::applySelectionModifierUnified(), PclUtils::renders::MeshTextureApplier::ApplyTexturesFromCCMesh(), PclUtils::renders::MeshTextureApplier::ApplyTexturesFromMaterialSet(), PclUtils::renders::MeshTextureApplier::ApplyTraditionalTextures(), ccSensor::applyViewport(), ccCameraSensor::applyViewport(), ccGBLSensor::applyViewport(), cvSelectionExporter::batchExportToFiles(), cvSelectionExporter::batchExportToMeshes(), cvSelectionExporter::batchExportToPointClouds(), cvRenderViewSelectionReaction::beginSelection(), ccOctreeFrustumIntersector::build(), ccTrace::buildCurvatureCost(), ccTrace::buildGradientCost(), G3PointFactory::buildObject(), ccExtru::buildUp(), cvSelectionPipeline::captureBuffersForFastPreSelection(), CatchGLErrors(), CCCloudToDraco(), ccComputeOctreeDlg::ccComputeOctreeDlg(), ccIndexedTransformationBuffer::ccIndexedTransformationBuffer(), CCMeshToDraco(), ccWaveDialog::ccWaveDialog(), PclAnnotationTool::changeAnnotationType(), ChildNodeToConsole(), ccPolyline::Circle(), masc::Classifier::classify(), ccColorScale::clear(), ccEntityAction::clearProperty(), ccMaterialSet::clone(), NormsIndexesTableType::clone(), NormsTableType::clone(), ColorsTableType::clone(), RGBAColorsTableType::clone(), TextureCoordsContainer::clone(), ccFacet::clone(), ccHObjectCaster::CloneChildren(), ccMesh::cloneMesh(), cvSelectionPipeline::combineSelections(), ccPointCloud::compressFWFData(), FastGlobalRegistrationFilter::compute(), ccComparisonDlg::computeApproxDistances(), ccHistogramWindow::computeBinArrayFromSF(), ccPointCloud::computeCPSet(), ccComparisonDlg::computeDistances(), ComputeFeatures(), ccCameraSensor::computeFrustumCorners(), ccLibAlgorithms::ComputeGeomCharacteristic(), ccRasterGrid::ComputeGridSize(), AnglesCustomPlot::computeHistogram(), ComputeKmeansClustering(), ccScalarField::computeMinAndMax(), ccPointCloud::computeNormalsWithGrids(), ccPointCloud::computeNormalsWithOctree(), ccEntityAction::computeOctree(), ccMesh::computePerTriangleNormals(), ccMesh::computePerVertexNormals(), ccGenericMesh::computePointPosition(), ccEntityAction::computeStatParams(), ccCameraSensor::computeUncertainty(), masc::NeighborhoodFeature::computeValue(), ccVolumeCalcTool::ComputeVolume(), cvFindDataDockWidget::configure(), Mouse3DInput::connect(), ConverFromTo(), ccPointCloud::convertCurrentScalarFieldToColors(), ccCameraSensor::ConvertFocalMMToPix(), ccCameraSensor::ConvertFocalPixToMM(), ccVolumeCalcTool::ConvertGridToCloud(), ccRasterizeTool::convertGridToCloud(), ccMesh::convertMaterialsToVertexColors(), ccEntityAction::convertNormalsTo(), ccPointCloud::convertNormalToDipDirSFs(), ccPointCloud::convertNormalToRGB(), ccEntityAction::convertTextureToColor(), ccRasterGrid::convertToCloud(), cvSelectionPipeline::convertToCvSelectionData(), vtk2cc::ConvertToMesh(), vtk2cc::ConvertToPointCloud(), vtk2cc::ConvertToPolyline(), ccPointPairRegistrationDlg::convertToSphereCenter(), ccEntityAction::ConvexHull(), ccArray< Type, N, ComponentType >::copy(), ccColorScale::copy(), pcl2cc::CopyScalarField(), pcl2cc::CopyXYZ(), CreateFeaturesFromCommand(), IoUtils::createMaterialSetForMesh(), ccPointCloud::createNewCloudFromVisibilitySelection(), ccMesh::createNewMeshFromSelection(), ccPolyline::createNewPolylinesFromSelection(), QueryExpressionUtils::createRegex(), CreateTempFile(), ccCropTool::Crop(), ccPointCloud::Crop(), ccPointCloud::crop(), ccPointCloud::crop2D(), cvPointPickingHelper::cvPointPickingHelper(), define_ccLog(), define_pycc(), ccDBRoot::deleteSelectedEntities(), ccGriddedTools::DetectParameters(), ccComparisonDlg::determineBestOctreeLevel(), DisplayCurrentNodeInfo(), FileIOFilter::DisplayErrorMessage(), ecvUtils::DisplayLockedVerticesWarning(), ecvDisplayTools::DisplayNewMessage(), PclUtils::PCLVis::displayText(), MainWindow::dispToConsole(), ccGraphicalSegmentationTool::doExportSegmentationPolyline(), qSRA::doProjectCloudDistsInGrid(), q3DMASCPlugin::doTrainAction(), PCLDisplayTools::draw(), PCLDisplayTools::drawWidgets(), ccDBRoot::editLabelScalarValue(), PclUtils::ImageVis::enable2Dviewer(), ccGamepadManager::enableDevice(), ccSubsamplingDlg::enableSFModulation(), ccEntityAction::enhanceRGBWithIntensities(), ccPointCloud::enhanceRGBWithIntensitySF(), VtkUtils::AngleWidgetObserver::Execute(), PythonInterpreter::executeFile(), cvSelectionPipeline::executePolygonSelection(), cvSelectionPipeline::executeRectangleSelection(), PclUtils::PCLVis::ExpandBounds(), cvViewSelectionManager::expandSelection(), cvSelectionAlgebra::expandSelection(), ecvAnnotationsTool::exportAnnotationToSF(), ccPointCloud::exportCoordToSF(), cvSelectionExporter::exportFromSourceCloud(), cvSelectionExporter::exportFromSourceMesh(), ccDBRoot::exportImages(), ecvMeasurementTool::exportMeasurement(), ccGraphicalTransformationTool::exportNewEntities(), ccPointCloud::exportNormalToSF(), ccEntityAction::exportNormalToSF(), ecvFilterTool::exportSlice(), ccHistogramWindowDlg::exportToCSV(), G3PointPlots::exportToCSV(), cvSelectionExporter::exportToMesh(), cvSelectionExporter::exportToPointCloud(), cvSelectionAlgebra::extractBoundary(), cvSelectionPipeline::extractDataFromSelection(), ccContourExtractor::ExtractFlatContour(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), cvSelectionExporter::extractSelection(), cvSelectionPipeline::extractSelectionIds(), masc::Feature::ExtractSources(), ExtraLasField::ExtraLasField(), CVTools::FileMappingReader(), CVTools::FileMappingWriter(), LasExtraScalarFieldCard::fillField(), ccRasterGrid::fillWith(), cvSelectionFilter::filterByArea(), cvSelectionFilter::filterByAttributeComparison(), cvSelectionFilter::filterByAttributeRange(), cvSelectionFilter::filterByNeighborCount(), cvSelectionFilter::filterByNormalAngle(), cvRenderViewSelectionReaction::finalizeSelection(), ccGenericPrimitive::finishCloneJob(), G3Point::G3PointAction::fit(), ccQuadric::Fit(), ccPlane::Fit(), ccPointCloud::From(), ccHistogramWindow::fromBinArray(), PclUtils::renders::MaterialConverter::FromCCMaterial(), FromFbxMesh(), masc::Classifier::fromFile(), pcl2cc::FromPCLMaterial(), ccColorScalesManager::fromPersistentSettings(), FromQByteArray(), ccKdTreeForFacetExtraction::FuseCells(), ccRasterizeTool::generateASCIIMatrix(), ccRasterizeTool::generateCloud(), ccSensor::getActiveAbsoluteTransformation(), cvSelectionBase::getAllPolyDataFromVisualizer(), cloudViewer::getArrayLengthFromFile(), cvSelectionBase::getDataActors(), G3Point::G3PointAction::GetG3PointAction(), LasField::GetLASFields(), ecvGlobalShiftManager::GetLast(), cvGenericFilter::getOutput(), cvIsoSurfaceFilter::getOutput(), cvProbeFilter::getOutput(), cvContourTool::getOutput(), cvDistanceTool::getOutput(), cvProtractorTool::getOutput(), cc2smReader::getPclCloud2(), cc2smReader::getPclMesh(), cc2smReader::getPclTextureMesh(), cvSelectionPipeline::getPixelSelectionInfo(), cvSelectionPipeline::getPrimaryDataFromSelection(), PclUtils::PCLVis::getReasonableClippingRange(), ccSubsamplingDlg::getSampledCloud(), GetScalarFieldIndex(), GetSource(), cvViewSelectionManager::getSourceMesh(), ccGenericPointCloud::getTheVisiblePoints(), ccMesh::getTriangleTexCoordinates(), cc2smReader::getVtkPolyDataFromMeshCloud(), cc2smReader::getVtkPolyDataWithTextures(), GrainsAsEllipsoids::GrainsAsEllipsoids(), cvSelectionAlgebra::growPointSelection(), cvSelectionAlgebra::growSelection(), ccNormalVectors::GuessBestRadius(), ccOctree::GuessBestRadius(), ecvGlobalShiftManager::Handle(), cvGenericSelectionTool::hardwareSelectInRegion(), PclUtils::PCLVis::hideOrientationMarkerWidgetAxes(), cvSelectionHighlighter::highlightElement(), cvSelectionHighlighter::highlightSelection(), ccRegistrationTools::ICP(), LasScalarField::IdFromName(), ccColorScaleEditorDialog::importScale(), STEPFilter::importStepFile(), ccEntityAction::importToSF(), ccNormalVectors::init(), ccPointCloud::VBO::init(), PclAnnotationTool::initAnnotationLabels(), ccCameraSensor::FrustumInformation::initFrustumHull(), MainWindow::initPlugins(), ccPolyline::initWith(), ccColorScale::insert(), ccPointCloud::interpolateColorsFrom(), ccPointCloudInterpolator::InterpolateScalarFieldsFrom(), ccOctree::intersectWithFrustum(), PclAnnotationTool::keyboardEventProcess(), LasWaveformLoader::LasWaveformLoader(), ccOverlayDialog::linkWith(), ccMaterial::loadAndSetTexture(), ccMaterial::loadAndSetTextureMap(), Annotaions::loadAnnotations(), STLFilter::loadASCIIFile(), STLFilter::loadBinaryFile(), IcmFilter::LoadCalibratedImages(), masc::Tools::LoadClassifierCloudLabels(), LoadCloud(), AsciiFilter::loadCloudFromFormatedAsciiStream(), CSVMatrixFilter::loadFile(), PhotoScanFilter::loadFile(), PcdFilter::loadFile(), DxfFilter::loadFile(), ImageFileFilter::loadFile(), ObjFilter::loadFile(), OFFFilter::loadFile(), PTXFilter::loadFile(), STLFilter::loadFile(), VTKFilter::loadFile(), IcmFilter::loadFile(), PovFilter::loadFile(), SalomeHydroFilter::loadFile(), SinusxFilter::loadFile(), SoiFilter::loadFile(), PDMSFilter::loadFile(), SimpleBinFilter::loadFile(), DRCFilter::loadFile(), E57Filter::loadFile(), FBXFilter::loadFile(), LASFWFFilter::loadFile(), LasIOFilter::loadFile(), LASFilter::loadFile(), PlyFilter::loadFile(), masc::Tools::LoadFile(), IoAbstractLoader::loadFile(), BundlerFilter::loadFileExtended(), PclUtils::renders::TextureLoader::LoadFromCCMaterial(), ccApplyTransformationDlg::loadFromClipboard(), FileIOFilter::LoadFromFile(), PclUtils::renders::TextureLoader::LoadFromPCLMaterial(), ccColorScale::LoadFromXML(), LasMetadata::LoadGlobalEncoding(), LoadImage(), ecvShiftAndScaleCloudDlg::loadInfoFromFile(), qM3C2Dialog::loadParamsFrom(), LasMetadata::LoadProjectUUID(), LoadScan(), masc::Feature::LoadSources(), LasWaveformLoader::loadWaveform(), MainWindow::MainWindow(), LasExtraScalarField::MatchExtraBytesToScalarFields(), ccMesh::merge(), ccMesh::mergeDuplicatedVertices(), QVTKWidgetCustom::mouseMoveEvent(), myMessageOutput(), ccHObject::New(), IoUtils::newCCMeshFromAIMesh(), ecvMeasurementTool::onItemPicked(), ccPointPairRegistrationDlg::onItemPicked(), ccPointPickingGenericInterface::onItemPicked(), MainWindow::onItemPicked(), cvRenderViewSelectionReaction::onLeftButtonRelease(), cvRenderViewSelectionReaction::onMouseMove(), ecvMeasurementTool::onPointPickingRequested(), LasSaver::open(), ccMinimumSpanningTreeForNormsDirection::OrientNormals(), ccFastMarchingForNormsDirection::OrientNormals(), ccEntityAction::orientNormalsFM(), ccEntityAction::orientNormalsMST(), ccPointCloud::orientNormalsTowardViewPoint(), ccPointCloud::orientNormalsWithGrids(), ccCameraSensor::orthoRectifyAsCloud(), ccCameraSensor::OrthoRectifyAsImages(), LasExtraScalarField::ParseExtraScalarFields(), ccMaterialSet::ParseMTL(), ParseWaveformDescriptorVlrs(), ccPointCloud::partialClone(), ccMesh::partialClone(), cvViewSelectionManager::performAlgebraOperation(), cvGenericSelectionTool::pickAtCursor(), cvGenericSelectionTool::pickAtPosition(), LasDetails::PointFormatsAvailableForVersion(), ccCompass::pointPicked(), ccGenericPointCloud::pointPicking(), ccTracePolylineTool::polylineOverSampling(), masc::CorePoints::prepare(), masc::ContextBasedFeature::prepare(), prepareCloud(), masc::Tools::PrepareFeatures(), PrepareLASField(), masc::Feature::PrepareSF(), qAnimationDlg::preview(), CommandRasterize::process(), CommandVolume25D::process(), cvConstrainedDistanceWidget::ProcessKeyEvents(), ccEntityAction::processMeshSF(), LasMetadata::ProjectionVLRToString(), ccDrawableObject::pushDisplayState(), ccHObject::pushDisplayState(), masc::Tools::RandomSubset(), ReadCloud(), ReadCorePoints(), ReadScales(), cvSelectionPipeline::refinePolygonSelection(), FileIOFilter::Register(), cvSelectionToolController::registerAction(), ccColorScale::remove(), cvSelectionAnnotationManager::removeAnnotation(), ccDBRoot::removeElement(), ccDBRoot::removeElements(), ecvMeasurementTool::removeInstance(), ccColorScalesManager::removeScale(), qAnimationDlg::render(), ecvLayoutManager::repositionUnifiedPluginToolbar(), ccPointCloud::reserveTheFWFTable(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveTheRGBTable(), ccGraphicalTransformationTool::reset(), ccArray< Type, N, ComponentType >::resizeSafe(), ccPointCloud::resizeTheFWFTable(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), ecvLayoutManager::restoreCustomLayout(), ccPointCloudLODThread::run(), ccGenericMesh::samplePoints(), ccPolyline::samplePoints(), Annotaions::saveAnnotations(), cloudViewer::saveArrayToFile(), masc::Tools::SaveClassifier(), LasSaver::saveNextPoint(), SaveScan(), SaveScene(), masc::Feature::SaveSources(), STLFilter::saveToBINFile(), FileIOFilter::SaveToFile(), PcdFilter::saveToFile(), AsciiFilter::saveToFile(), DxfFilter::saveToFile(), ImageFileFilter::saveToFile(), ObjFilter::saveToFile(), OFFFilter::saveToFile(), STLFilter::saveToFile(), VTKFilter::saveToFile(), PNFilter::saveToFile(), PovFilter::saveToFile(), PVFilter::saveToFile(), SalomeHydroFilter::saveToFile(), SinusxFilter::saveToFile(), HeightProfileFilter::saveToFile(), MascaretFilter::saveToFile(), SimpleBinFilter::saveToFile(), E57Filter::saveToFile(), FBXFilter::saveToFile(), LASFWFFilter::saveToFile(), LasIOFilter::saveToFile(), LASFilter::saveToFile(), DepthMapFileFilter::saveToFile(), ccPointCloud::SelectByIndex(), cvSelectionPipeline::selectCellsInPolygon(), cvRenderViewSelectionReaction::selectCellsOnSurface(), ccDBRoot::selectChildrenByTypeAndName(), ccDBRoot::selectEntities(), ccDBRoot::selectEntity(), PclAnnotationTool::selectExistedAnnotation(), cvRenderViewSelectionReaction::selectionChanged(), cloudViewer::ModelViewerWidget::SelectObject(), cvSelectionPipeline::selectPointsInPolygon(), cvRenderViewSelectionReaction::selectPointsOnSurface(), PclUtils::renders::TextureRenderManager::SelectRenderer(), SendError(), ecvApplicationBase::setAppStyle(), ecvDisplayTools::SetAspectRatio(), ccEntityAction::setColor(), ccHistogramWindow::setCurveValues(), PCLDisplayTools::setDataAxesGridProperties(), PclUtils::PCLVis::SetDataAxesGridProperties(), STEPFilter::SetDefaultLinearDeflection(), ecvDisplayTools::SetFocusToScreen(), ecvDisplayTools::SetFov(), ccShiftedObject::setGlobalScale(), ecvFilterByLabelDlg::setInputEntity(), PclUtils::PCLVis::setLightIntensity(), PCLDisplayTools::setLightIntensity(), ccScalarField::setLogScale(), PythonPlugin::setMainAppInterface(), PclUtils::PCLVis::setMeshOpacity(), PclUtils::PCLVis::setMeshRenderingMode(), PclUtils::PCLVis::setMeshShadingMode(), SetOrAdd(), ecvDisplayTools::SetPickingMode(), cvDistanceTool::setPoint1(), cvDistanceTool::setPoint2(), ccPlane::SetQuadTexture(), ccPointCloud::setRGBColorByBanding(), ccPointCloud::setRGBColorWithCurrentScalarField(), PclTransformTool::setRotationMode(), PclTransformTool::setScaleEnabled(), PclTransformTool::setShearEnabled(), ccMaterial::setTexture(), PclTransformTool::setTranlationMode(), cvGenericMeasurementTool::setupShortcuts(), PclMeasurementTools::setupShortcuts(), EditCameraTool::SetVisualizer(), PclFiltersTool::setVisualizer(), PclMeasurementTools::setVisualizer(), PclAnnotationTool::setVisualizer(), PclTransformTool::setVisualizer(), ecvDisplayTools::SetZNearCoef(), ccEntityAction::sfAddIdField(), ccEntityAction::sfFromColor(), ccEntityAction::sfGaussianFilter(), ccEntityAction::sfRename(), PclTransformTool::showInteractor(), ccGamepadManager::showMessage(), cvSelectionAlgebra::shrinkPointSelection(), cvSelectionAlgebra::shrinkSelection(), ccPolyline::smoothChaikin(), qAnimationDlg::smoothTrajectory(), sPluginIID(), ecvPoissonReconDlg::start(), ecvMeasurementTool::start(), ccTracePolylineTool::start(), ecvDisplayTools::StartCPUBasedPointPicking(), ecvDisplayTools::StartOpenGLPicking(), qAnimationDlg::textureAnimationPreview(), qAnimationDlg::textureAnimationRender(), ecvDisplayTools::TheInstance(), TileLasReader(), ccWaveform::toASCII(), ccWaveform::ToASCII(), ToFbxMesh(), masc::Classifier::toFile(), ecvAnnotationsTool::toggleBox(), PCLDisplayTools::ToggleCameraOrientationWidget(), PclUtils::PCLVis::ToggleCameraOrientationWidget(), PclUtils::PCLVis::toggleOrientationMarkerWidgetAxes(), ecvAnnotationsTool::toggleOrigin(), ccMesh::Triangulate(), ccPointCloud::triangulateGrid(), ccMesh::TriangulateTwoPolylines(), ccCameraSensor::undistort(), ccPointCloud::unroll(), ccColorScale::update(), PclUtils::renders::PBRRenderer::Update(), PclUtils::renders::MultiTextureRenderer::Update(), qAnimationDlg::updateCameraTrajectory(), ecvDisplayTools::UpdateConstellationCenterAndZoom(), GrainsAsEllipsoids::updateMeshAndLineSet(), PCLDisplayTools::updateMeshTextures(), ccNormalVectors::UpdateNormalOrientations(), qM3C2Normals::UpdateNormalOrientationsWithCloud(), cvSelectionPropertiesWidget::updateSelection(), PclUtils::PCLVis::updateTexture(), ccGenericMesh::updateTextures(), PclUtils::renders::TextureRendererBase::ValidateMaterials(), vertex_cb(), PCLModules::VoxelGridFilter(), ccCommandLineParser::warning(), ccConsoleOutput::write(), ListWidgetConsole::write(), MainWindow::zoomOnEntities(), and MainWindow::zoomOnSelectedEntities().
Warning() [2/2]
bool CVLog::Warning (const QString & message) static
QString version of ccLog::Warning.
Definition at line 138 of file CVLog.cpp.
References LOG_WARNING, and LogMessage().
WarningDebug() [1/2]
bool CVLog::WarningDebug (const char * format, ...) static
Same as Warning, but works only in Debug mode.
Works just like the 'printf' command.
Returns
always 'false'
Definition at line 167 of file CVLog.cpp.
References DEBUG_FLAG, LOG_ARGS, and LOG_WARNING.
Referenced by ccMaterialSet::append(), and PCLModules::ComputeCloudResolution().
WarningDebug() [2/2]
bool CVLog::WarningDebug (const QString & message) static
QString version of ccLog::WarningDebug.
Definition at line 174 of file CVLog.cpp.
References DEBUG_FLAG, LOG_WARNING, and LogMessage().
The documentation for this class was generated from the following files:
/root/ACloudViewer/core/include/CVLog.h
/root/ACloudViewer/core/src/CVLog.cpp