ACloudViewer: cloudViewer::t::geometry::DrawableGeometry Class Reference
cloudViewer::t::geometry::DrawableGeometry Class Reference
Mix-in class for geometry types that can be visualized.
#include <DrawableGeometry.h>
Public Member Functions
DrawableGeometry ()
~DrawableGeometry ()
bool HasMaterial () const
Check if a material has been applied to this Geometry with SetMaterial.
visualization::rendering::Material & GetMaterial ()
Get material associated with this Geometry.
const visualization::rendering::Material & GetMaterial () const
Get const reference to material associated with this Geometry.
void SetMaterial (const visualization::rendering::Material &material)
Set the material properties associate with this Geometry.
Detailed Description
Mix-in class for geometry types that can be visualized.
Definition at line 19 of file DrawableGeometry.h.
Constructor & Destructor Documentation
DrawableGeometry()
cloudViewer::t::geometry::DrawableGeometry::DrawableGeometry () inline
Definition at line 21 of file DrawableGeometry.h.
~DrawableGeometry()
cloudViewer::t::geometry::DrawableGeometry::~DrawableGeometry () inline
Definition at line 22 of file DrawableGeometry.h.
Member Function Documentation
GetMaterial() [1/2]
visualization::rendering::Material& cloudViewer::t::geometry::DrawableGeometry::GetMaterial () inline
Get material associated with this Geometry.
Definition at line 28 of file DrawableGeometry.h.
Referenced by cloudViewer::t::geometry::TriangleMesh::BakeVertexAttrTextures(), cloudViewer::t::geometry::TriangleMesh::FromLegacy(), cloudViewer::io::rpc::GeometryToMeshData(), cloudViewer::t::geometry::TriangleMesh::ProjectImagesToAlbedo(), cloudViewer::t::io::ReadTriangleMeshFromNPZ(), cloudViewer::t::geometry::TriangleMesh::SamplePointsUniformly(), cloudViewer::io::rpc::SetTriangleMesh(), cloudViewer::t::geometry::TriangleMesh::ToLegacy(), cloudViewer::t::io::WriteTriangleMeshToNPZ(), and cloudViewer::t::io::WriteTriangleMeshUsingASSIMP().
GetMaterial() [2/2]
const visualization::rendering::Material& cloudViewer::t::geometry::DrawableGeometry::GetMaterial () const inline
Get const reference to material associated with this Geometry.
Definition at line 31 of file DrawableGeometry.h.
HasMaterial()
bool cloudViewer::t::geometry::DrawableGeometry::HasMaterial () const inline
Check if a material has been applied to this Geometry with SetMaterial.
Definition at line 25 of file DrawableGeometry.h.
References cloudViewer::visualization::rendering::Material::IsValid().
Referenced by cloudViewer::t::geometry::TriangleMesh::ProjectImagesToAlbedo(), cloudViewer::io::rpc::SetTriangleMesh(), and cloudViewer::t::io::WriteTriangleMeshUsingASSIMP().
SetMaterial()
void cloudViewer::t::geometry::DrawableGeometry::SetMaterial (const visualization::rendering::Material & material) inline
Set the material properties associate with this Geometry.
Definition at line 36 of file DrawableGeometry.h.
Referenced by cloudViewer::t::geometry::TriangleMesh::ProjectImagesToAlbedo().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/t/geometry/DrawableGeometry.h