ACloudViewer: pba::SparseBundleCU Class Reference
pba::SparseBundleCU Class Reference
#include <SparseBundleCU.h>
Public Member Functions
virtual float GetMeanSquaredError ()
virtual void SetCameraData (size_t ncam, CameraT *cams)
virtual void SetPointData (size_t npoint, Point3D *pts)
virtual void SetProjection (size_t nproj, const Point2D *imgpts, const int *point_idx, const int *cam_idx)
virtual void SetFocalMask (const int *fmask, float weight)
virtual int RunBundleAdjustment ()
virtual void AbortBundleAdjustment ()
virtual int GetCurrentIteration ()
virtual void SetNextTimeBudget (int seconds)
virtual void SetNextBundleMode (BundleModeT mode)
virtual void SetFixedIntrinsics (bool fixed)
virtual void EnableRadialDistortion (DistortionT type)
virtual void ParseParam (int narg, char **argv)
SparseBundleCU (int device)
size_t GetMemCapacity ()
Public Member Functions inherited from pba::ParallelBA
void SetFocalLengthFixed (bool fixed)
void ResetBundleStorage ()
ParallelBA (DeviceT device=PBA_CUDA_DEVICE_DEFAULT, const int num_threads=-1)
void * operator new (size_t size)
virtual ~ParallelBA ()
Public Member Functions inherited from pba::ConfigBA
void ParseParam (int argc, char **argv)
const char * GetOutputParam ()
float GetInitialMSE ()
float GetFinalMSE ()
double GetBundleTiming (int timer=TIMER_OVERALL)
int GetIterationsLM ()
int GetIterationsCG ()
int GetCurrentDevice ()
int GetBundleReturnCode ()
int GetActiveDevice ()
Protected Member Functions
bool ProcessIndexCameraQ (std::vector< int > &qmap, std::vector< int > &qlist)
void ProcessWeightCameraQ (std::vector< int > &cpnum, std::vector< int > &qmap, std::vector< float > &qmapw, std::vector< float > &qlistw)
int GetParameterLength ()
int InitializeBundle ()
int ValidateInputData ()
void ReleaseAllocatedData ()
bool InitializeStorageForCG ()
bool InitializeBundleGPU ()
bool TransferDataToGPU ()
void TransferDataToHost ()
void DenormalizeData ()
void NormalizeData ()
void NormalizeDataF ()
void NormalizeDataD ()
void DebugProjections ()
void RunDebugSteps ()
bool CheckRequiredMem (int fresh=1)
bool CheckRequiredMemX ()
void ReserveStorage (size_t ncam, size_t npt, size_t nproj)
void ReserveStorageAuto ()
float EvaluateProjection (CuTexImage &cam, CuTexImage &point, CuTexImage &proj)
float EvaluateProjectionX (CuTexImage &cam, CuTexImage &point, CuTexImage &proj)
float UpdateCameraPoint (CuTexImage &dx, CuTexImage &cuImageTempProj)
float SaveUpdatedSystem (float residual_reduction, float dx_sqnorm, float damping)
float EvaluateDeltaNorm ()
void EvaluateJacobians (bool shuffle=true)
void PrepareJacobianNormalization ()
void ComputeJtE (CuTexImage &E, CuTexImage &JtE, int mode=0)
void ComputeJX (CuTexImage &X, CuTexImage &JX, int mode=0)
void ComputeDiagonal (CuTexImage &JJ, CuTexImage &JJI)
void ComputeBlockPC (float lambda, bool dampd=true)
void ApplyBlockPC (CuTexImage &v, CuTexImage &pv, int mode=0)
int SolveNormalEquationPCGB (float lambda)
int SolveNormalEquationPCGX (float lambda)
int SolveNormalEquation (float lambda)
void AdjustBundleAdjsutmentMode ()
void NonlinearOptimizeLM ()
void BundleAdjustment ()
void RunTestIterationLM (bool reduced)
void SaveBundleRecord (int iter, float res, float damping, float &g_norm, float &g_inf)
void SaveNormalEquation (float lambda)
void RunProfileSteps ()
void WarmupDevice ()
Protected Member Functions inherited from pba::ConfigBA
ConfigBA ()
void ResetTemporarySetting ()
void ResetBundleStatistics ()
void PrintBundleStatistics ()
void SaveBundleStatistics (int ncam, int npt, int nproj)
void BundleTimerStart (int timer)
void BundleTimerSwitch (int timer)
float BundleTimerGet (int timer)
void BundleTimerSwap (int timer1, int timer2)
float BundleTimerGetNow (int timer=TIMER_OPTIMIZATION)
void SaveBundleRecord (int iter, float res, float damping, float gn, float gi)
bool IsTimeBudgetAvailable ()
double MyClock ()
Protected Attributes
int _num_camera
int _num_point
int _num_imgpt
CameraT * _camera_data
float * _point_data
const float * _imgpt_data
const int * _camera_idx
const int * _point_idx
const int * _focal_mask
std::vector< float > _imgpt_datax
float _projection_sse
CuTexImage _cuCameraData
CuTexImage _cuCameraDataEX
CuTexImage _cuPointData
CuTexImage _cuPointDataEX
CuTexImage _cuMeasurements
CuTexImage _cuImageProj
CuTexImage _cuJacobianCamera
CuTexImage _cuJacobianPoint
CuTexImage _cuJacobianCameraT
CuTexImage _cuProjectionMap
CuTexImage _cuPointMeasurementMap
CuTexImage _cuCameraMeasurementMap
CuTexImage _cuCameraMeasurementList
CuTexImage _cuCameraMeasurementListT
CuTexImage _cuBufferData
CuTexImage _cuBlockPC
CuTexImage _cuVectorSJ
CuTexImage _cuVectorJtE
LM normal equation.
CuTexImage _cuVectorJJ
CuTexImage _cuVectorJX
CuTexImage _cuVectorXK
CuTexImage _cuVectorPK
CuTexImage _cuVectorZK
CuTexImage _cuVectorRK
int _num_imgpt_q
float _weight_q
CuTexImage _cuCameraQList
CuTexImage _cuCameraQMap
CuTexImage _cuCameraQMapW
CuTexImage _cuCameraQListW
Protected Attributes inherited from pba::ConfigBA
bool __multiply_jx_usenoj
int __selected_device
int __cpu_data_precision
int __bundle_time_budget
int __bundle_mode_next
int __bundle_current_mode
float __initial_mse
float __final_mse
float __final_mse_x
float __focal_scaling
float __depth_scaling
int __current_device
int __current_iteration
int __num_cg_iteration
int __num_lm_success
int __num_lm_iteration
int __num_projection_eval
int __num_jacobian_eval
int __num_camera_modified
int __num_point_behind
int __pba_return_code
int __recent_cg_status
int __profile_pba
bool __cpu_thread_profile
bool __debug_pba
bool __warmup_device
size_t __memory_usage
bool __matlab_format_stat
char * __stat_filename
const char * __driver_output
std::vector< float > __bundle_records
double __timer_record [NUM_TIMER]
int __num_cpu_thread_all
int __num_cpu_thread [NUM_FUNC]
Additional Inherited Members
Public Types inherited from pba::ParallelBA
enum StatusT {
STATUS_SUCCESS = 0 , STATUS_CAMERA_MISSING = 1 , STATUS_POINT_MISSING , STATUS_PROJECTION_MISSING ,
STATUS_MEASURMENT_MISSING , STATUS_ALLOCATION_FAIL
}
enum DeviceT {
PBA_INVALID_DEVICE = -4 , PBA_CPU_DOUBLE = -3 , PBA_CPU_FLOAT = -2 , PBA_CUDA_DEVICE_DEFAULT = -1 ,
PBA_CUDA_DEVICE0 = 0
}
enum DistortionT { PBA_MEASUREMENT_DISTORTION = -1 , PBA_NO_DISTORTION = 0 , PBA_PROJECTION_DISTORTION = 1 }
enum BundleModeT { BUNDLE_FULL = 0 , BUNDLE_ONLY_MOTION = 1 , BUNDLE_ONLY_STRUCTURE = 2 }
Public Attributes inherited from pba::ConfigBA
int __lm_max_iteration
int __cg_max_iteration
int __cg_min_iteration
int __cg_recalculate_freq
bool __accurate_gain_ratio
float __lm_delta_threshold
float __lm_gradient_threshold
float __lm_mse_threshold
float __lm_initial_damp
float __lm_minimum_damp
float __lm_maximum_damp
float __cg_norm_threshold
float __cg_norm_guard
int __pba_experimental
bool __cg_schur_complement
bool __lm_check_gradient
float __lm_damping_auto_switch
bool __lm_use_diagonal_damp
bool __fixed_intrinsics
int __use_radial_distortion
bool __reset_initial_distortion
int __verbose_level
bool __abort_flag
bool __verbose_cg_iteration
bool __verbose_function_time
bool __save_gradient_norm
bool __verbose_allocation
bool __verbose_sse
bool __jc_store_transpose
bool __no_jacobian_store
bool __jc_store_original
bool __jacobian_normalize
bool __focal_normalize
bool __depth_normalize
bool __depth_degeneracy_fix
float __data_normalize_median
float __depth_check_epsilon
Protected Types inherited from pba::ConfigBA
enum {
TIMER_OVERALL = 0 , TIMER_OPTIMIZATION , TIMER_GPU_ALLOCATION , TIMER_GPU_UPLOAD ,
TIMER_PREPROCESSING , TIMER_GPU_DOWNLOAD , TIMER_CG_ITERATION , TIMER_LM_ITERATION ,
TIMER_FUNCTION_JJ , TIMER_FUNCTION_PJ , TIMER_FUNCTION_DD , TIMER_FUNCTION_JX ,
TIMER_FUNCTION_JTE , TIMER_FUNCTION_BC , TIMER_FUNCTION_MP , TIMER_FUNCTION_UP ,
TIMER_PROFILE_STEP , NUM_TIMER , FUNC_JX = 0 , FUNC_JX_ ,
FUNC_JTEC_JCT , FUNC_JTEC_JCO , FUNC_JTEP , FUNC_JTE_ ,
FUNC_JJ_JCO_JCT_JP , FUNC_JJ_JCO_JP , FUNC_JJ_JCT_JP , FUNC_JJ_JP ,
FUNC_PJ , FUNC_BCC_JCT , FUNC_BCC_JCO , FUNC_BCP ,
FUNC_MPC , FUNC_MPP , FUNC_VS , FUNC_VV ,
NUM_FUNC
}
Detailed Description
Definition at line 31 of file SparseBundleCU.h.
Constructor & Destructor Documentation
SparseBundleCU()
pba::SparseBundleCU::SparseBundleCU (int device)
Definition at line 77 of file SparseBundleCU.cpp.
References pba::ConfigBA::__selected_device.
Member Function Documentation
AbortBundleAdjustment()
virtual void pba::SparseBundleCU::AbortBundleAdjustment () inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 152 of file SparseBundleCU.h.
References pba::ConfigBA::__abort_flag.
AdjustBundleAdjsutmentMode()
void pba::SparseBundleCU::AdjustBundleAdjsutmentMode () protected
Definition at line 1564 of file SparseBundleCU.cpp.
References pba::ConfigBA::__bundle_current_mode, _cuJacobianCamera, _cuJacobianCameraT, pba::ParallelBA::BUNDLE_ONLY_STRUCTURE, and pba::CuTexImage::InitTexture().
Referenced by BundleAdjustment().
ApplyBlockPC()
void pba::SparseBundleCU::ApplyBlockPC (CuTexImage & v, CuTexImage & pv, int mode = 0) protected
Definition at line 1134 of file SparseBundleCU.cpp.
References pba::ConfigBA::__use_radial_distortion, _cuBlockPC, _num_camera, _num_point, pba::ProgramCU::MultiplyBlockConditioner(), and pba::ConfigBA::TIMER_FUNCTION_MP.
Referenced by RunProfileSteps(), SolveNormalEquation(), SolveNormalEquationPCGB(), and SolveNormalEquationPCGX().
BundleAdjustment()
void pba::SparseBundleCU::BundleAdjustment () protected
Definition at line 130 of file SparseBundleCU.cpp.
References pba::ConfigBA::__profile_pba, AdjustBundleAdjsutmentMode(), DenormalizeData(), InitializeBundle(), NonlinearOptimizeLM(), NormalizeData(), RunProfileSteps(), pba::ParallelBA::STATUS_SUCCESS, pba::ConfigBA::TIMER_OVERALL, TransferDataToHost(), and ValidateInputData().
Referenced by RunBundleAdjustment().
CheckRequiredMem()
bool pba::SparseBundleCU::CheckRequiredMem (int fresh = 1) protected
Definition at line 249 of file SparseBundleCU.cpp.
References pba::ConfigBA::__jc_store_original, pba::ConfigBA::__jc_store_transpose, pba::ConfigBA::__no_jacobian_store, pba::ConfigBA::__use_radial_distortion, _cuCameraData, _cuMeasurements, _cuPointData, _num_camera, _num_imgpt, _num_imgpt_q, _num_point, pba::ProgramCU::GetCudaMemoryCap(), pba::CuTexImage::GetReservedWidth(), and max().
Referenced by CheckRequiredMemX().
CheckRequiredMemX()
bool pba::SparseBundleCU::CheckRequiredMemX () protected
Definition at line 229 of file SparseBundleCU.cpp.
References pba::ConfigBA::__jc_store_original, pba::ConfigBA::__jc_store_transpose, pba::ConfigBA::__no_jacobian_store, pba::ConfigBA::__verbose_level, and CheckRequiredMem().
Referenced by InitializeBundle(), and WarmupDevice().
ComputeBlockPC()
void pba::SparseBundleCU::ComputeBlockPC (float lambda, bool dampd = true) protected
Definition at line 1105 of file SparseBundleCU.cpp.
References pba::ConfigBA::__bundle_current_mode, pba::ConfigBA::__fixed_intrinsics, pba::ConfigBA::__jc_store_original, pba::ConfigBA::__jc_store_transpose, pba::ConfigBA::__no_jacobian_store, pba::ConfigBA::__use_radial_distortion, _cuBlockPC, _cuCameraData, _cuCameraMeasurementList, _cuCameraMeasurementMap, _cuCameraQListW, _cuJacobianCamera, _cuJacobianCameraT, _cuJacobianPoint, _cuMeasurements, _cuPointData, _cuPointMeasurementMap, _cuProjectionMap, _cuVectorJJ, _cuVectorSJ, pba::ProgramCU::ComputeDiagonalBlock(), pba::ProgramCU::ComputeDiagonalBlock_(), pba::ProgramCU::ComputeDiagonalQ(), pba::CuTexImage::IsValid(), and pba::ConfigBA::TIMER_FUNCTION_BC.
Referenced by PrepareJacobianNormalization(), RunProfileSteps(), SolveNormalEquation(), SolveNormalEquationPCGB(), and SolveNormalEquationPCGX().
ComputeDiagonal()
void pba::SparseBundleCU::ComputeDiagonal (CuTexImage & JJ, CuTexImage & JJI) protected
Definition at line 1140 of file SparseBundleCU.cpp.
References pba::ConfigBA::__jc_store_original, pba::ConfigBA::__jc_store_transpose, pba::ConfigBA::__no_jacobian_store, pba::ConfigBA::__use_radial_distortion, _cuCameraMeasurementList, _cuCameraMeasurementMap, _cuCameraQListW, _cuJacobianCamera, _cuJacobianCameraT, _cuJacobianPoint, _cuPointMeasurementMap, pba::ProgramCU::ComputeDiagonal(), pba::ProgramCU::ComputeDiagonalQ(), pba::CuTexImage::IsValid(), and pba::ConfigBA::TIMER_FUNCTION_DD.
Referenced by PrepareJacobianNormalization(), and RunProfileSteps().
ComputeJtE()
void pba::SparseBundleCU::ComputeJtE (CuTexImage & E, CuTexImage & JtE, int mode = 0) protected
Definition at line 1026 of file SparseBundleCU.cpp.
References pba::ConfigBA::__bundle_current_mode, pba::ConfigBA::__fixed_intrinsics, pba::ConfigBA::__jc_store_original, pba::ConfigBA::__jc_store_transpose, pba::ConfigBA::__no_jacobian_store, pba::ConfigBA::__use_radial_distortion, _cuCameraData, _cuCameraMeasurementList, _cuCameraMeasurementMap, _cuCameraQList, _cuCameraQListW, _cuJacobianCamera, _cuJacobianCameraT, _cuJacobianPoint, _cuMeasurements, _cuPointData, _cuPointMeasurementMap, _cuProjectionMap, _cuVectorSJ, _num_camera, _num_imgpt_q, _num_point, pba::ProgramCU::ComputeJQtEC(), pba::ProgramCU::ComputeJtE(), pba::ProgramCU::ComputeJtE_(), pba::ProgramCU::ComputeVXY(), pba::CuTexImage::IsValid(), and pba::ConfigBA::TIMER_FUNCTION_JTE.
Referenced by NonlinearOptimizeLM(), RunDebugSteps(), RunProfileSteps(), RunTestIterationLM(), SolveNormalEquationPCGB(), and SolveNormalEquationPCGX().
ComputeJX()
void pba::SparseBundleCU::ComputeJX (CuTexImage & X, CuTexImage & JX, int mode = 0) protected
Definition at line 1074 of file SparseBundleCU.cpp.
References pba::ConfigBA::__fixed_intrinsics, pba::ConfigBA::__jc_store_original, pba::ConfigBA::__multiply_jx_usenoj, pba::ConfigBA::__no_jacobian_store, pba::ConfigBA::__use_radial_distortion, _cuCameraData, _cuCameraQMap, _cuCameraQMapW, _cuJacobianCamera, _cuJacobianPoint, _cuMeasurements, _cuPointData, _cuProjectionMap, _cuVectorSJ, _cuVectorZK, _num_camera, _num_imgpt, _num_imgpt_q, _num_point, pba::ProgramCU::ComputeJQX(), pba::ProgramCU::ComputeJX(), pba::ProgramCU::ComputeJX_(), pba::ProgramCU::ComputeVXY(), pba::CuTexImage::IsValid(), pba::ConfigBA::TIMER_FUNCTION_JX, and X.
Referenced by RunDebugSteps(), RunProfileSteps(), RunTestIterationLM(), SaveUpdatedSystem(), SolveNormalEquationPCGB(), and SolveNormalEquationPCGX().
DebugProjections()
void pba::SparseBundleCU::DebugProjections () protected
Definition at line 900 of file SparseBundleCU.cpp.
References pba::ConfigBA::__focal_scaling, pba::ConfigBA::__use_radial_distortion, _camera_data, _camera_idx, _imgpt_data, _imgpt_datax, _num_imgpt, _point_data, and _point_idx.
DenormalizeData()
void pba::SparseBundleCU::DenormalizeData () protected
Definition at line 840 of file SparseBundleCU.cpp.
References pba::ConfigBA::__depth_normalize, pba::ConfigBA::__depth_scaling, pba::ConfigBA::__focal_normalize, pba::ConfigBA::__focal_scaling, pba::ConfigBA::__use_radial_distortion, _camera_data, _imgpt_datax, _num_camera, _num_point, _point_data, _projection_sse, pba::CameraT_< FT >::distortion_type, pba::CameraT_< FT >::f, pba::CameraT_< FT >::radial, and pba::CameraT_< FT >::t.
Referenced by BundleAdjustment().
EnableRadialDistortion()
virtual void pba::SparseBundleCU::EnableRadialDistortion (DistortionT type) inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 161 of file SparseBundleCU.h.
References pba::ConfigBA::__use_radial_distortion, and type.
EvaluateDeltaNorm()
float pba::SparseBundleCU::EvaluateDeltaNorm () protected
Definition at line 1571 of file SparseBundleCU.cpp.
References pba::ConfigBA::__bundle_current_mode, _cuBufferData, _cuVectorXK, _num_camera, _num_point, pba::ParallelBA::BUNDLE_ONLY_MOTION, pba::ParallelBA::BUNDLE_ONLY_STRUCTURE, pba::ProgramCU::ComputeVectorNorm(), pba::CuTexImage::data(), and pba::CuTexImage::SetTexture().
Referenced by NonlinearOptimizeLM().
EvaluateJacobians()
void pba::SparseBundleCU::EvaluateJacobians (bool shuffle = true) protected
Definition at line 1002 of file SparseBundleCU.cpp.
References pba::ConfigBA::__bundle_current_mode, pba::ConfigBA::__fixed_intrinsics, pba::ConfigBA::__jc_store_original, pba::ConfigBA::__jc_store_transpose, pba::ConfigBA::__no_jacobian_store, pba::ConfigBA::__num_jacobian_eval, pba::ConfigBA::__use_radial_distortion, _cuCameraData, _cuCameraMeasurementList, _cuCameraMeasurementListT, _cuJacobianCamera, _cuJacobianCameraT, _cuJacobianPoint, _cuMeasurements, _cuPointData, _cuProjectionMap, _cuVectorSJ, pba::ParallelBA::BUNDLE_ONLY_MOTION, pba::ProgramCU::ComputeJacobian(), pba::CuTexImage::IsValid(), pba::ProgramCU::ShuffleCameraJacobian(), and pba::ConfigBA::TIMER_FUNCTION_JJ.
Referenced by NonlinearOptimizeLM(), PrepareJacobianNormalization(), RunDebugSteps(), RunProfileSteps(), and RunTestIterationLM().
EvaluateProjection()
float pba::SparseBundleCU::EvaluateProjection (CuTexImage & cam, CuTexImage & point, CuTexImage & proj) protected
Definition at line 878 of file SparseBundleCU.cpp.
References pba::ConfigBA::__num_projection_eval, pba::ConfigBA::__use_radial_distortion, _cuBufferData, _cuCameraQMap, _cuCameraQMapW, _cuMeasurements, _cuProjectionMap, _num_imgpt, _num_imgpt_q, pba::ProgramCU::ComputeProjection(), pba::ProgramCU::ComputeProjectionQ(), pba::ProgramCU::ComputeVectorNorm(), and pba::ConfigBA::TIMER_FUNCTION_PJ.
Referenced by NonlinearOptimizeLM(), RunDebugSteps(), RunProfileSteps(), RunTestIterationLM(), and UpdateCameraPoint().
EvaluateProjectionX()
float pba::SparseBundleCU::EvaluateProjectionX (CuTexImage & cam, CuTexImage & point, CuTexImage & proj) protected
Definition at line 889 of file SparseBundleCU.cpp.
References pba::ConfigBA::__num_projection_eval, pba::ConfigBA::__use_radial_distortion, _cuBufferData, _cuCameraQMap, _cuCameraQMapW, _cuMeasurements, _cuProjectionMap, _num_imgpt, _num_imgpt_q, pba::ProgramCU::ComputeProjectionQ(), pba::ProgramCU::ComputeProjectionX(), pba::ProgramCU::ComputeVectorNorm(), and pba::ConfigBA::TIMER_FUNCTION_PJ.
Referenced by NonlinearOptimizeLM().
GetCurrentIteration()
virtual int pba::SparseBundleCU::GetCurrentIteration () inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 153 of file SparseBundleCU.h.
References pba::ConfigBA::__current_iteration.
GetMeanSquaredError()
float pba::SparseBundleCU::GetMeanSquaredError () virtual
Reimplemented from pba::ParallelBA.
Definition at line 125 of file SparseBundleCU.cpp.
References pba::ConfigBA::__focal_scaling, _num_imgpt, and _projection_sse.
GetMemCapacity()
size_t pba::SparseBundleCU::GetMemCapacity ()
Definition at line 92 of file SparseBundleCU.cpp.
References pba::ConfigBA::__current_device, pba::ConfigBA::__selected_device, pba::ProgramCU::GetCudaMemoryCap(), and pba::ProgramCU::SetCudaDevice().
Referenced by pba::ParallelBA::ParallelBA().
GetParameterLength()
int pba::SparseBundleCU::GetParameterLength () protected
Definition at line 225 of file SparseBundleCU.cpp.
References _num_camera, and _num_point.
Referenced by InitializeStorageForCG(), SaveNormalEquation(), SolveNormalEquationPCGB(), and SolveNormalEquationPCGX().
InitializeBundle()
int pba::SparseBundleCU::InitializeBundle () protected
Definition at line 215 of file SparseBundleCU.cpp.
References pba::ConfigBA::__current_device, pba::ConfigBA::__selected_device, CheckRequiredMemX(), InitializeBundleGPU(), ReserveStorageAuto(), pba::ProgramCU::SetCudaDevice(), pba::ParallelBA::STATUS_ALLOCATION_FAIL, pba::ParallelBA::STATUS_SUCCESS, and pba::ConfigBA::TIMER_GPU_ALLOCATION.
Referenced by BundleAdjustment().
InitializeBundleGPU()
bool pba::SparseBundleCU::InitializeBundleGPU () protected
Definition at line 164 of file SparseBundleCU.cpp.
References pba::ConfigBA::__jc_store_original, pba::ConfigBA::__jc_store_transpose, pba::ConfigBA::__memory_usage, pba::ConfigBA::__no_jacobian_store, pba::ConfigBA::__verbose_level, pba::ProgramCU::ClearPreviousError(), InitializeStorageForCG(), ReleaseAllocatedData(), and TransferDataToGPU().
Referenced by InitializeBundle(), ReserveStorage(), and WarmupDevice().
InitializeStorageForCG()
bool pba::SparseBundleCU::InitializeStorageForCG () protected
Definition at line 948 of file SparseBundleCU.cpp.
References pba::ConfigBA::__accurate_gain_ratio, pba::ConfigBA::__jacobian_normalize, pba::ConfigBA::__memory_usage, pba::ConfigBA::__use_radial_distortion, pba::ConfigBA::__verbose_level, _cuBlockPC, _cuImageProj, _cuVectorJJ, _cuVectorJtE, _cuVectorJX, _cuVectorPK, _cuVectorRK, _cuVectorSJ, _cuVectorXK, _cuVectorZK, _num_camera, _num_imgpt, _num_imgpt_q, _num_point, ALLOCATE_OPTIONAL_DATA, ALLOCATE_REQUIRED_DATA, pba::CuTexImage::data(), GetParameterLength(), and pba::CuTexImage::SetTexture().
Referenced by InitializeBundleGPU().
NonlinearOptimizeLM()
void pba::SparseBundleCU::NonlinearOptimizeLM () protected
Definition at line 1586 of file SparseBundleCU.cpp.
References pba::ConfigBA::__abort_flag, pba::ConfigBA::__current_iteration, pba::ConfigBA::__final_mse, pba::ConfigBA::__final_mse_x, pba::ConfigBA::__focal_scaling, pba::ConfigBA::__initial_mse, pba::ConfigBA::__jacobian_normalize, pba::ConfigBA::__lm_check_gradient, pba::ConfigBA::__lm_damping_auto_switch, pba::ConfigBA::__lm_delta_threshold, pba::ConfigBA::__lm_gradient_threshold, pba::ConfigBA::__lm_initial_damp, pba::ConfigBA::__lm_max_iteration, pba::ConfigBA::__lm_maximum_damp, pba::ConfigBA::__lm_minimum_damp, pba::ConfigBA::__lm_mse_threshold, pba::ConfigBA::__lm_use_diagonal_damp, pba::ConfigBA::__num_lm_iteration, pba::ConfigBA::__num_lm_success, pba::ConfigBA::__pba_return_code, pba::ConfigBA::__recent_cg_status, pba::ConfigBA::__save_gradient_norm, pba::ConfigBA::__use_radial_distortion, pba::ConfigBA::__verbose_level, pba::ConfigBA::__verbose_sse, _cuCameraData, _cuImageProj, _cuPointData, _cuVectorJtE, _cuVectorJX, _cuVectorSJ, _cuVectorXK, _cuVectorZK, _num_imgpt, _projection_sse, pba::ConfigBA::BundleTimerGetNow(), ComputeJtE(), EvaluateDeltaNorm(), EvaluateJacobians(), EvaluateProjection(), EvaluateProjectionX(), cloudViewer::utility::floor(), pba::ConfigBA::IsTimeBudgetAvailable(), pba::CuTexImage::IsValid(), max(), PrepareJacobianNormalization(), SaveBundleRecord(), SaveUpdatedSystem(), SolveNormalEquation(), pba::CuTexImage::SwapData(), pba::ConfigBA::TIMER_OPTIMIZATION, and UpdateCameraPoint().
Referenced by BundleAdjustment().
NormalizeData()
void pba::SparseBundleCU::NormalizeData () protected
Definition at line 834 of file SparseBundleCU.cpp.
References NormalizeDataD(), NormalizeDataF(), and pba::ConfigBA::TIMER_PREPROCESSING.
Referenced by BundleAdjustment().
NormalizeDataD()
void pba::SparseBundleCU::NormalizeDataD () protected
Definition at line 728 of file SparseBundleCU.cpp.
References pba::ConfigBA::__data_normalize_median, pba::ConfigBA::__depth_check_epsilon, pba::ConfigBA::__depth_degeneracy_fix, pba::ConfigBA::__depth_normalize, pba::ConfigBA::__depth_scaling, pba::ConfigBA::__focal_normalize, pba::ConfigBA::__num_camera_modified, pba::ConfigBA::__num_point_behind, pba::ConfigBA::__verbose_level, _camera_data, _camera_idx, _imgpt_data, _num_camera, _num_imgpt, _num_point, _point_data, _point_idx, pba::CameraT_< FT >::f, fabs(), pba::CameraT_< FT >::m, max(), min(), and pba::CameraT_< FT >::t.
Referenced by NormalizeData().
NormalizeDataF()
void pba::SparseBundleCU::NormalizeDataF () protected
Definition at line 674 of file SparseBundleCU.cpp.
References pba::ConfigBA::__data_normalize_median, pba::ConfigBA::__focal_normalize, pba::ConfigBA::__focal_scaling, pba::ConfigBA::__reset_initial_distortion, pba::ConfigBA::__use_radial_distortion, pba::ConfigBA::__verbose_level, _camera_data, _imgpt_data, _imgpt_datax, _num_camera, _num_imgpt, pba::CameraT_< FT >::f, and pba::CameraT_< FT >::radial.
Referenced by NormalizeData().
ParseParam()
virtual void pba::SparseBundleCU::ParseParam (int narg, char ** argv) inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 164 of file SparseBundleCU.h.
References pba::ConfigBA::ParseParam().
PrepareJacobianNormalization()
void pba::SparseBundleCU::PrepareJacobianNormalization () protected
Definition at line 980 of file SparseBundleCU.cpp.
References pba::ConfigBA::__bundle_current_mode, pba::ConfigBA::__jc_store_original, pba::ConfigBA::__jc_store_transpose, _cuJacobianPoint, _cuVectorJJ, _cuVectorSJ, ComputeBlockPC(), ComputeDiagonal(), pba::ProgramCU::ComputeRSQRT(), pba::ProgramCU::ComputeSQRT(), EvaluateJacobians(), pba::CuTexImage::IsValid(), and pba::CuTexImage::SwapData().
Referenced by NonlinearOptimizeLM(), and RunProfileSteps().
ProcessIndexCameraQ()
bool pba::SparseBundleCU::ProcessIndexCameraQ (std::vector< int > & qmap, std::vector< int > & qlist) protected
Definition at line 530 of file SparseBundleCU.cpp.
References _camera_idx, _focal_mask, _num_camera, _num_imgpt, _num_imgpt_q, _point_idx, _weight_q, error(), and NULL.
Referenced by TransferDataToGPU().
ProcessWeightCameraQ()
void pba::SparseBundleCU::ProcessWeightCameraQ (std::vector< int > & cpnum, std::vector< int > & qmap, std::vector< float > & qmapw, std::vector< float > & qlistw) protected
Definition at line 600 of file SparseBundleCU.cpp.
References pba::ConfigBA::__use_radial_distortion, _camera_data, _focal_mask, _num_camera, _num_imgpt_q, _weight_q, pba::CameraT_< FT >::f, and pba::CameraT_< FT >::radial.
Referenced by TransferDataToGPU().
ReleaseAllocatedData()
void pba::SparseBundleCU::ReleaseAllocatedData () protected
Definition at line 641 of file SparseBundleCU.cpp.
References _cuBlockPC, _cuBufferData, _cuCameraData, _cuCameraDataEX, _cuCameraMeasurementList, _cuCameraMeasurementListT, _cuCameraMeasurementMap, _cuCameraQList, _cuCameraQListW, _cuCameraQMap, _cuCameraQMapW, _cuImageProj, _cuJacobianCamera, _cuJacobianCameraT, _cuJacobianPoint, _cuMeasurements, _cuPointData, _cuPointDataEX, _cuPointMeasurementMap, _cuProjectionMap, _cuVectorJJ, _cuVectorJtE, _cuVectorJX, _cuVectorPK, _cuVectorRK, _cuVectorSJ, _cuVectorXK, _cuVectorZK, pba::ProgramCU::ClearTextureObjectCache(), pba::CuTexImage::ReleaseData(), and pba::ProgramCU::ResetCurrentDevice().
Referenced by InitializeBundleGPU(), and ReserveStorage().
ReserveStorage()
void pba::SparseBundleCU::ReserveStorage (size_t ncam, size_t npt, size_t nproj) protected virtual
Reimplemented from pba::ParallelBA.
Definition at line 307 of file SparseBundleCU.cpp.
References pba::ConfigBA::__jc_store_original, pba::ConfigBA::__jc_store_transpose, pba::ConfigBA::__no_jacobian_store, pba::ConfigBA::__verbose_level, _camera_idx, _cuCameraData, _cuMeasurements, _cuPointData, _num_camera, _num_imgpt, _num_point, _point_idx, pba::CuTexImage::GetReservedWidth(), InitializeBundleGPU(), max(), NULL, and ReleaseAllocatedData().
Referenced by ReserveStorageAuto().
ReserveStorageAuto()
void pba::SparseBundleCU::ReserveStorageAuto () protected
Definition at line 355 of file SparseBundleCU.cpp.
References _cuCameraData, _cuMeasurements, _cuPointData, _num_camera, _num_imgpt, _num_point, pba::CuTexImage::data(), NULL, ReserveStorage(), and pba::upgrade_dimension().
Referenced by InitializeBundle().
RunBundleAdjustment()
int pba::SparseBundleCU::RunBundleAdjustment () virtual
Reimplemented from pba::ParallelBA.
Definition at line 153 of file SparseBundleCU.cpp.
References pba::ConfigBA::__num_lm_success, pba::ConfigBA::__warmup_device, _num_camera, _num_imgpt, _num_point, BundleAdjustment(), pba::ConfigBA::PrintBundleStatistics(), pba::ConfigBA::ResetBundleStatistics(), pba::ConfigBA::ResetTemporarySetting(), pba::ConfigBA::SaveBundleStatistics(), and WarmupDevice().
RunDebugSteps()
void pba::SparseBundleCU::RunDebugSteps () protected
Definition at line 1941 of file SparseBundleCU.cpp.
References _cuCameraData, _cuImageProj, _cuPointData, _cuVectorJtE, _cuVectorJX, ComputeJtE(), ComputeJX(), DEBUG_FUNCN, EvaluateJacobians(), and EvaluateProjection().
RunProfileSteps()
void pba::SparseBundleCU::RunProfileSteps () protected
Definition at line 1792 of file SparseBundleCU.cpp.
References pba::ConfigBA::__cg_max_iteration, pba::ConfigBA::__cg_min_iteration, pba::ConfigBA::__jc_store_original, pba::ConfigBA::__jc_store_transpose, pba::ConfigBA::__lm_initial_damp, pba::ConfigBA::__multiply_jx_usenoj, pba::ConfigBA::__no_jacobian_store, pba::ConfigBA::__num_cg_iteration, pba::ConfigBA::__profile_pba, _cuBufferData, _cuCameraData, _cuCameraMeasurementList, _cuImageProj, _cuJacobianCamera, _cuJacobianCameraT, _cuJacobianPoint, _cuMeasurements, _cuPointData, _cuVectorJJ, _cuVectorJtE, _cuVectorJX, _cuVectorPK, _cuVectorRK, _cuVectorXK, _cuVectorZK, _imgpt_data, _imgpt_datax, _point_data, ApplyBlockPC(), ComputeBlockPC(), ComputeDiagonal(), ComputeJtE(), ComputeJX(), pba::ProgramCU::ComputeSAXPY(), pba::ProgramCU::ComputeSXYPZ(), pba::ProgramCU::ComputeVectorDot(), pba::ProgramCU::ComputeVectorNorm(), pba::ProgramCU::ComputeVectorNormW(), pba::CuTexImage::CopyFromHost(), pba::CuTexImage::CopyToHost(), EvaluateJacobians(), EvaluateProjection(), pba::ProgramCU::FinishWorkCUDA(), PrepareJacobianNormalization(), PROFILE, PROXILE, pba::CuTexImage::ReleaseData(), RunTestIterationLM(), pba::ProgramCU::ShuffleCameraJacobian(), SolveNormalEquationPCGB(), SolveNormalEquationPCGX(), and UpdateCameraPoint().
Referenced by BundleAdjustment().
RunTestIterationLM()
void pba::SparseBundleCU::RunTestIterationLM (bool reduced) protected
Definition at line 1460 of file SparseBundleCU.cpp.
References pba::ConfigBA::__lm_initial_damp, _cuBufferData, _cuCameraData, _cuImageProj, _cuPointData, _cuVectorJtE, _cuVectorJX, _cuVectorXK, _cuVectorZK, ComputeJtE(), ComputeJX(), pba::ProgramCU::ComputeVectorDot(), pba::ProgramCU::ComputeVectorNorm(), EvaluateJacobians(), EvaluateProjection(), SolveNormalEquationPCGB(), SolveNormalEquationPCGX(), and UpdateCameraPoint().
Referenced by RunProfileSteps().
SaveBundleRecord()
void pba::SparseBundleCU::SaveBundleRecord (int iter, float res, float damping, float & g_norm, float & g_inf) protected
Definition at line 1062 of file SparseBundleCU.cpp.
References pba::ConfigBA::__lm_check_gradient, pba::ConfigBA::__save_gradient_norm, _cuBufferData, _cuVectorJtE, pba::ProgramCU::ComputeVectorMax(), pba::ProgramCU::ComputeVectorNorm(), and pba::ConfigBA::SaveBundleRecord().
Referenced by NonlinearOptimizeLM().
SaveNormalEquation()
void pba::SparseBundleCU::SaveNormalEquation (float lambda) protected
Definition at line 1950 of file SparseBundleCU.cpp.
References _camera_idx, _cuImageProj, _cuJacobianCamera, _cuJacobianPoint, _cuVectorXK, _num_camera, _num_imgpt, _point_idx, pba::CuTexImage::CopyToHost(), and GetParameterLength().
SaveUpdatedSystem()
float pba::SparseBundleCU::SaveUpdatedSystem (float residual_reduction, float dx_sqnorm, float damping) protected
save the new motion/struture
Definition at line 1500 of file SparseBundleCU.cpp.
References pba::ConfigBA::__accurate_gain_ratio, pba::ConfigBA::__bundle_current_mode, pba::ConfigBA::__lm_use_diagonal_damp, _cuBufferData, _cuCameraData, _cuCameraDataEX, _cuPointData, _cuPointDataEX, _cuVectorJJ, _cuVectorJtE, _cuVectorJX, _cuVectorXK, _num_camera, _num_point, pba::ParallelBA::BUNDLE_ONLY_MOTION, pba::ParallelBA::BUNDLE_ONLY_STRUCTURE, ComputeJX(), pba::ProgramCU::ComputeVectorDot(), pba::ProgramCU::ComputeVectorNorm(), pba::ProgramCU::ComputeVectorNormW(), pba::CuTexImage::data(), pba::CuTexImage::SetTexture(), and pba::CuTexImage::SwapData().
Referenced by NonlinearOptimizeLM().
SetCameraData()
void pba::SparseBundleCU::SetCameraData (size_t ncam, CameraT * cams) virtual
Reimplemented from pba::ParallelBA.
Definition at line 99 of file SparseBundleCU.cpp.
References _camera_data, _focal_mask, _num_camera, and NULL.
SetFixedIntrinsics()
virtual void pba::SparseBundleCU::SetFixedIntrinsics (bool fixed) inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 160 of file SparseBundleCU.h.
References pba::ConfigBA::__fixed_intrinsics.
SetFocalMask()
void pba::SparseBundleCU::SetFocalMask (const int * fmask, float weight) virtual
Reimplemented from pba::ParallelBA.
Definition at line 106 of file SparseBundleCU.cpp.
References _focal_mask, and _weight_q.
SetNextBundleMode()
virtual void pba::SparseBundleCU::SetNextBundleMode (BundleModeT mode) inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 157 of file SparseBundleCU.h.
References pba::ConfigBA::__bundle_mode_next.
SetNextTimeBudget()
virtual void pba::SparseBundleCU::SetNextTimeBudget (int seconds) inline virtual
Reimplemented from pba::ParallelBA.
Definition at line 154 of file SparseBundleCU.h.
References pba::ConfigBA::__bundle_time_budget, and seconds.
SetPointData()
void pba::SparseBundleCU::SetPointData (size_t npoint, Point3D * pts) virtual
Reimplemented from pba::ParallelBA.
Definition at line 111 of file SparseBundleCU.cpp.
References _num_point, and _point_data.
SetProjection()
void pba::SparseBundleCU::SetProjection (size_t nproj, const Point2D * imgpts, const int * point_idx, const int * cam_idx) virtual
Reimplemented from pba::ParallelBA.
Definition at line 116 of file SparseBundleCU.cpp.
References _camera_idx, _imgpt_data, _imgpt_datax, _num_imgpt, and _point_idx.
SolveNormalEquation()
int pba::SparseBundleCU::SolveNormalEquation (float lambda) protected
Definition at line 1444 of file SparseBundleCU.cpp.
References pba::ConfigBA::__bundle_current_mode, pba::ConfigBA::__cg_schur_complement, pba::ConfigBA::__lm_use_diagonal_damp, _cuVectorJtE, _cuVectorXK, ApplyBlockPC(), pba::ParallelBA::BUNDLE_ONLY_MOTION, pba::ParallelBA::BUNDLE_ONLY_STRUCTURE, ComputeBlockPC(), SolveNormalEquationPCGB(), and SolveNormalEquationPCGX().
Referenced by NonlinearOptimizeLM().
SolveNormalEquationPCGB()
int pba::SparseBundleCU::SolveNormalEquationPCGB (float lambda) protected
Definition at line 1318 of file SparseBundleCU.cpp.
References pba::ConfigBA::__cg_max_iteration, pba::ConfigBA::__cg_min_iteration, pba::ConfigBA::__cg_norm_guard, pba::ConfigBA::__cg_norm_threshold, pba::ConfigBA::__cg_recalculate_freq, pba::ConfigBA::__lm_use_diagonal_damp, pba::ConfigBA::__num_cg_iteration, pba::ConfigBA::__recent_cg_status, pba::ConfigBA::__verbose_cg_iteration, _cuBufferData, _cuVectorJJ, _cuVectorJtE, _cuVectorJX, _cuVectorPK, _cuVectorRK, _cuVectorXK, _cuVectorZK, ApplyBlockPC(), pba::ConfigBA::BundleTimerGetNow(), ComputeBlockPC(), ComputeJtE(), ComputeJX(), pba::ProgramCU::ComputeSAX(), pba::ProgramCU::ComputeSAXPY(), pba::ProgramCU::ComputeSXYPZ(), pba::ProgramCU::ComputeVectorDot(), pba::ProgramCU::ComputeVectorNorm(), pba::ProgramCU::ComputeVectorNormW(), fabs(), GetParameterLength(), min(), and pba::ConfigBA::TIMER_CG_ITERATION.
Referenced by RunProfileSteps(), RunTestIterationLM(), and SolveNormalEquation().
SolveNormalEquationPCGX()
int pba::SparseBundleCU::SolveNormalEquationPCGX (float lambda) protected
Definition at line 1164 of file SparseBundleCU.cpp.
References pba::ConfigBA::__cg_max_iteration, pba::ConfigBA::__cg_min_iteration, pba::ConfigBA::__cg_norm_guard, pba::ConfigBA::__cg_norm_threshold, pba::ConfigBA::__lm_use_diagonal_damp, pba::ConfigBA::__num_cg_iteration, pba::ConfigBA::__recent_cg_status, pba::ConfigBA::__verbose_cg_iteration, _cuBufferData, _cuImageProj, _cuVectorJJ, _cuVectorJtE, _cuVectorJX, _cuVectorPK, _cuVectorRK, _cuVectorXK, _cuVectorZK, _num_camera, _num_point, ApplyBlockPC(), pba::ConfigBA::BundleTimerGetNow(), ComputeBlockPC(), ComputeJtE(), ComputeJX(), pba::ProgramCU::ComputeSAX(), pba::ProgramCU::ComputeSAXPY(), pba::ProgramCU::ComputeSXYPZ(), pba::ProgramCU::ComputeVectorDot(), pba::ProgramCU::ComputeVectorNorm(), pba::ProgramCU::ComputeVectorNormW(), pba::CuTexImage::data(), fabs(), GetParameterLength(), min(), pba::CuTexImage::SetTexture(), and pba::ConfigBA::TIMER_CG_ITERATION.
Referenced by RunProfileSteps(), RunTestIterationLM(), and SolveNormalEquation().
TransferDataToGPU()
bool pba::SparseBundleCU::TransferDataToGPU () protected
Definition at line 407 of file SparseBundleCU.cpp.
References pba::ConfigBA::__jc_store_original, pba::ConfigBA::__jc_store_transpose, pba::ConfigBA::__memory_usage, pba::ConfigBA::__no_jacobian_store, pba::ConfigBA::__profile_pba, pba::ConfigBA::__verbose_level, _camera_data, _camera_idx, _cuBufferData, _cuCameraData, _cuCameraDataEX, _cuCameraMeasurementList, _cuCameraMeasurementListT, _cuCameraMeasurementMap, _cuCameraQList, _cuCameraQListW, _cuCameraQMap, _cuCameraQMapW, _cuImageProj, _cuJacobianCamera, _cuJacobianCameraT, _cuJacobianPoint, _cuMeasurements, _cuPointData, _cuPointDataEX, _cuPointMeasurementMap, _cuProjectionMap, _imgpt_data, _imgpt_datax, _num_camera, _num_imgpt, _num_imgpt_q, _num_point, _point_data, _point_idx, ALLOCATE_OPTIONAL_DATA, ALLOCATE_REQUIRED_DATA, pba::ConfigBA::BundleTimerSwap(), pba::CuTexImage::CopyFromHost(), pba::CuTexImage::IsValid(), ProcessIndexCameraQ(), ProcessWeightCameraQ(), pba::CuTexImage::ReleaseData(), pba::ConfigBA::TIMER_GPU_ALLOCATION, pba::ConfigBA::TIMER_GPU_UPLOAD, and pba::ConfigBA::TIMER_PREPROCESSING.
Referenced by InitializeBundleGPU().
TransferDataToHost()
void pba::SparseBundleCU::TransferDataToHost () protected
Definition at line 872 of file SparseBundleCU.cpp.
References _camera_data, _cuCameraData, _cuPointData, _point_data, pba::CuTexImage::CopyToHost(), and pba::ConfigBA::TIMER_GPU_DOWNLOAD.
Referenced by BundleAdjustment().
UpdateCameraPoint()
float pba::SparseBundleCU::UpdateCameraPoint (CuTexImage & dx, CuTexImage & cuImageTempProj) protected
Definition at line 1474 of file SparseBundleCU.cpp.
References pba::ConfigBA::__bundle_current_mode, pba::ConfigBA::__jacobian_normalize, _cuCameraData, _cuCameraDataEX, _cuPointData, _cuPointDataEX, _cuVectorSJ, _cuVectorXK, _num_camera, _num_point, pba::ParallelBA::BUNDLE_ONLY_MOTION, pba::ParallelBA::BUNDLE_ONLY_STRUCTURE, pba::ProgramCU::ComputeVXY(), EvaluateProjection(), pba::ConfigBA::TIMER_FUNCTION_UP, and pba::ProgramCU::UpdateCameraPoint().
Referenced by NonlinearOptimizeLM(), RunProfileSteps(), and RunTestIterationLM().
ValidateInputData()
int pba::SparseBundleCU::ValidateInputData () protected
Definition at line 199 of file SparseBundleCU.cpp.
References _camera_data, _camera_idx, _imgpt_data, _point_data, _point_idx, NULL, pba::ParallelBA::STATUS_CAMERA_MISSING, pba::ParallelBA::STATUS_MEASURMENT_MISSING, pba::ParallelBA::STATUS_POINT_MISSING, pba::ParallelBA::STATUS_PROJECTION_MISSING, and pba::ParallelBA::STATUS_SUCCESS.
Referenced by BundleAdjustment().
WarmupDevice()
void pba::SparseBundleCU::WarmupDevice () protected
Definition at line 208 of file SparseBundleCU.cpp.
References pba::ConfigBA::__current_device, pba::ConfigBA::__selected_device, CheckRequiredMemX(), InitializeBundleGPU(), and pba::ProgramCU::SetCudaDevice().
Referenced by RunBundleAdjustment().
Member Data Documentation
_camera_data
CameraT* pba::SparseBundleCU::_camera_data protected
Definition at line 36 of file SparseBundleCU.h.
Referenced by DebugProjections(), DenormalizeData(), NormalizeDataD(), NormalizeDataF(), ProcessWeightCameraQ(), SetCameraData(), TransferDataToGPU(), TransferDataToHost(), and ValidateInputData().
_camera_idx
const int* pba::SparseBundleCU::_camera_idx protected
Definition at line 40 of file SparseBundleCU.h.
Referenced by DebugProjections(), NormalizeDataD(), ProcessIndexCameraQ(), ReserveStorage(), SaveNormalEquation(), SetProjection(), TransferDataToGPU(), and ValidateInputData().
_cuBlockPC
CuTexImage pba::SparseBundleCU::_cuBlockPC protected
Definition at line 65 of file SparseBundleCU.h.
Referenced by ApplyBlockPC(), ComputeBlockPC(), InitializeStorageForCG(), and ReleaseAllocatedData().
_cuBufferData
CuTexImage pba::SparseBundleCU::_cuBufferData protected
Definition at line 63 of file SparseBundleCU.h.
Referenced by EvaluateDeltaNorm(), EvaluateProjection(), EvaluateProjectionX(), ReleaseAllocatedData(), RunProfileSteps(), RunTestIterationLM(), SaveBundleRecord(), SaveUpdatedSystem(), SolveNormalEquationPCGB(), SolveNormalEquationPCGX(), and TransferDataToGPU().
_cuCameraData
CuTexImage pba::SparseBundleCU::_cuCameraData protected
Definition at line 47 of file SparseBundleCU.h.
Referenced by CheckRequiredMem(), ComputeBlockPC(), ComputeJtE(), ComputeJX(), EvaluateJacobians(), NonlinearOptimizeLM(), ReleaseAllocatedData(), ReserveStorage(), ReserveStorageAuto(), RunDebugSteps(), RunProfileSteps(), RunTestIterationLM(), SaveUpdatedSystem(), TransferDataToGPU(), TransferDataToHost(), and UpdateCameraPoint().
_cuCameraDataEX
CuTexImage pba::SparseBundleCU::_cuCameraDataEX protected
Definition at line 48 of file SparseBundleCU.h.
Referenced by ReleaseAllocatedData(), SaveUpdatedSystem(), TransferDataToGPU(), and UpdateCameraPoint().
_cuCameraMeasurementList
CuTexImage pba::SparseBundleCU::_cuCameraMeasurementList protected
Definition at line 59 of file SparseBundleCU.h.
Referenced by ComputeBlockPC(), ComputeDiagonal(), ComputeJtE(), EvaluateJacobians(), ReleaseAllocatedData(), RunProfileSteps(), and TransferDataToGPU().
_cuCameraMeasurementListT
CuTexImage pba::SparseBundleCU::_cuCameraMeasurementListT protected
Definition at line 60 of file SparseBundleCU.h.
Referenced by EvaluateJacobians(), ReleaseAllocatedData(), and TransferDataToGPU().
_cuCameraMeasurementMap
CuTexImage pba::SparseBundleCU::_cuCameraMeasurementMap protected
Definition at line 58 of file SparseBundleCU.h.
Referenced by ComputeBlockPC(), ComputeDiagonal(), ComputeJtE(), ReleaseAllocatedData(), and TransferDataToGPU().
_cuCameraQList
CuTexImage pba::SparseBundleCU::_cuCameraQList protected
Definition at line 81 of file SparseBundleCU.h.
Referenced by ComputeJtE(), ReleaseAllocatedData(), and TransferDataToGPU().
_cuCameraQListW
CuTexImage pba::SparseBundleCU::_cuCameraQListW protected
Definition at line 84 of file SparseBundleCU.h.
Referenced by ComputeBlockPC(), ComputeDiagonal(), ComputeJtE(), ReleaseAllocatedData(), and TransferDataToGPU().
_cuCameraQMap
CuTexImage pba::SparseBundleCU::_cuCameraQMap protected
Definition at line 82 of file SparseBundleCU.h.
Referenced by ComputeJX(), EvaluateProjection(), EvaluateProjectionX(), ReleaseAllocatedData(), and TransferDataToGPU().
_cuCameraQMapW
CuTexImage pba::SparseBundleCU::_cuCameraQMapW protected
Definition at line 83 of file SparseBundleCU.h.
Referenced by ComputeJX(), EvaluateProjection(), EvaluateProjectionX(), ReleaseAllocatedData(), and TransferDataToGPU().
_cuImageProj
CuTexImage pba::SparseBundleCU::_cuImageProj protected
Definition at line 52 of file SparseBundleCU.h.
Referenced by InitializeStorageForCG(), NonlinearOptimizeLM(), ReleaseAllocatedData(), RunDebugSteps(), RunProfileSteps(), RunTestIterationLM(), SaveNormalEquation(), SolveNormalEquationPCGX(), and TransferDataToGPU().
_cuJacobianCamera
CuTexImage pba::SparseBundleCU::_cuJacobianCamera protected
Definition at line 53 of file SparseBundleCU.h.
Referenced by AdjustBundleAdjsutmentMode(), ComputeBlockPC(), ComputeDiagonal(), ComputeJtE(), ComputeJX(), EvaluateJacobians(), ReleaseAllocatedData(), RunProfileSteps(), SaveNormalEquation(), and TransferDataToGPU().
_cuJacobianCameraT
CuTexImage pba::SparseBundleCU::_cuJacobianCameraT protected
Definition at line 55 of file SparseBundleCU.h.
Referenced by AdjustBundleAdjsutmentMode(), ComputeBlockPC(), ComputeDiagonal(), ComputeJtE(), EvaluateJacobians(), ReleaseAllocatedData(), RunProfileSteps(), and TransferDataToGPU().
_cuJacobianPoint
CuTexImage pba::SparseBundleCU::_cuJacobianPoint protected
Definition at line 54 of file SparseBundleCU.h.
Referenced by ComputeBlockPC(), ComputeDiagonal(), ComputeJtE(), ComputeJX(), EvaluateJacobians(), PrepareJacobianNormalization(), ReleaseAllocatedData(), RunProfileSteps(), SaveNormalEquation(), and TransferDataToGPU().
_cuMeasurements
CuTexImage pba::SparseBundleCU::_cuMeasurements protected
Definition at line 51 of file SparseBundleCU.h.
Referenced by CheckRequiredMem(), ComputeBlockPC(), ComputeJtE(), ComputeJX(), EvaluateJacobians(), EvaluateProjection(), EvaluateProjectionX(), ReleaseAllocatedData(), ReserveStorage(), ReserveStorageAuto(), RunProfileSteps(), and TransferDataToGPU().
_cuPointData
CuTexImage pba::SparseBundleCU::_cuPointData protected
Definition at line 49 of file SparseBundleCU.h.
Referenced by CheckRequiredMem(), ComputeBlockPC(), ComputeJtE(), ComputeJX(), EvaluateJacobians(), NonlinearOptimizeLM(), ReleaseAllocatedData(), ReserveStorage(), ReserveStorageAuto(), RunDebugSteps(), RunProfileSteps(), RunTestIterationLM(), SaveUpdatedSystem(), TransferDataToGPU(), TransferDataToHost(), and UpdateCameraPoint().
_cuPointDataEX
CuTexImage pba::SparseBundleCU::_cuPointDataEX protected
Definition at line 50 of file SparseBundleCU.h.
Referenced by ReleaseAllocatedData(), SaveUpdatedSystem(), TransferDataToGPU(), and UpdateCameraPoint().
_cuPointMeasurementMap
CuTexImage pba::SparseBundleCU::_cuPointMeasurementMap protected
Definition at line 57 of file SparseBundleCU.h.
Referenced by ComputeBlockPC(), ComputeDiagonal(), ComputeJtE(), ReleaseAllocatedData(), and TransferDataToGPU().
_cuProjectionMap
CuTexImage pba::SparseBundleCU::_cuProjectionMap protected
Definition at line 56 of file SparseBundleCU.h.
Referenced by ComputeBlockPC(), ComputeJtE(), ComputeJX(), EvaluateJacobians(), EvaluateProjection(), EvaluateProjectionX(), ReleaseAllocatedData(), and TransferDataToGPU().
_cuVectorJJ
CuTexImage pba::SparseBundleCU::_cuVectorJJ protected
Definition at line 70 of file SparseBundleCU.h.
Referenced by ComputeBlockPC(), InitializeStorageForCG(), PrepareJacobianNormalization(), ReleaseAllocatedData(), RunProfileSteps(), SaveUpdatedSystem(), SolveNormalEquationPCGB(), and SolveNormalEquationPCGX().
_cuVectorJtE
CuTexImage pba::SparseBundleCU::_cuVectorJtE protected
LM normal equation.
Definition at line 69 of file SparseBundleCU.h.
Referenced by InitializeStorageForCG(), NonlinearOptimizeLM(), ReleaseAllocatedData(), RunDebugSteps(), RunProfileSteps(), RunTestIterationLM(), SaveBundleRecord(), SaveUpdatedSystem(), SolveNormalEquation(), SolveNormalEquationPCGB(), and SolveNormalEquationPCGX().
_cuVectorJX
CuTexImage pba::SparseBundleCU::_cuVectorJX protected
Definition at line 71 of file SparseBundleCU.h.
Referenced by InitializeStorageForCG(), NonlinearOptimizeLM(), ReleaseAllocatedData(), RunDebugSteps(), RunProfileSteps(), RunTestIterationLM(), SaveUpdatedSystem(), SolveNormalEquationPCGB(), and SolveNormalEquationPCGX().
_cuVectorPK
CuTexImage pba::SparseBundleCU::_cuVectorPK protected
Definition at line 73 of file SparseBundleCU.h.
Referenced by InitializeStorageForCG(), ReleaseAllocatedData(), RunProfileSteps(), SolveNormalEquationPCGB(), and SolveNormalEquationPCGX().
_cuVectorRK
CuTexImage pba::SparseBundleCU::_cuVectorRK protected
Definition at line 75 of file SparseBundleCU.h.
Referenced by InitializeStorageForCG(), ReleaseAllocatedData(), RunProfileSteps(), SolveNormalEquationPCGB(), and SolveNormalEquationPCGX().
_cuVectorSJ
CuTexImage pba::SparseBundleCU::_cuVectorSJ protected
Definition at line 66 of file SparseBundleCU.h.
Referenced by ComputeBlockPC(), ComputeJtE(), ComputeJX(), EvaluateJacobians(), InitializeStorageForCG(), NonlinearOptimizeLM(), PrepareJacobianNormalization(), ReleaseAllocatedData(), and UpdateCameraPoint().
_cuVectorXK
CuTexImage pba::SparseBundleCU::_cuVectorXK protected
Definition at line 72 of file SparseBundleCU.h.
Referenced by EvaluateDeltaNorm(), InitializeStorageForCG(), NonlinearOptimizeLM(), ReleaseAllocatedData(), RunProfileSteps(), RunTestIterationLM(), SaveNormalEquation(), SaveUpdatedSystem(), SolveNormalEquation(), SolveNormalEquationPCGB(), SolveNormalEquationPCGX(), and UpdateCameraPoint().
_cuVectorZK
CuTexImage pba::SparseBundleCU::_cuVectorZK protected
Definition at line 74 of file SparseBundleCU.h.
Referenced by ComputeJX(), InitializeStorageForCG(), NonlinearOptimizeLM(), ReleaseAllocatedData(), RunProfileSteps(), RunTestIterationLM(), SolveNormalEquationPCGB(), and SolveNormalEquationPCGX().
_focal_mask
const int* pba::SparseBundleCU::_focal_mask protected
Definition at line 42 of file SparseBundleCU.h.
Referenced by ProcessIndexCameraQ(), ProcessWeightCameraQ(), SetCameraData(), and SetFocalMask().
_imgpt_data
const float* pba::SparseBundleCU::_imgpt_data protected
Definition at line 39 of file SparseBundleCU.h.
Referenced by DebugProjections(), NormalizeDataD(), NormalizeDataF(), RunProfileSteps(), SetProjection(), TransferDataToGPU(), and ValidateInputData().
_imgpt_datax
std::vector<float> pba::SparseBundleCU::_imgpt_datax protected
Definition at line 43 of file SparseBundleCU.h.
Referenced by DebugProjections(), DenormalizeData(), NormalizeDataF(), RunProfileSteps(), SetProjection(), and TransferDataToGPU().
_num_camera
int pba::SparseBundleCU::_num_camera protected
Definition at line 33 of file SparseBundleCU.h.
Referenced by ApplyBlockPC(), CheckRequiredMem(), ComputeJtE(), ComputeJX(), DenormalizeData(), EvaluateDeltaNorm(), GetParameterLength(), InitializeStorageForCG(), NormalizeDataD(), NormalizeDataF(), ProcessIndexCameraQ(), ProcessWeightCameraQ(), ReserveStorage(), ReserveStorageAuto(), RunBundleAdjustment(), SaveNormalEquation(), SaveUpdatedSystem(), SetCameraData(), SolveNormalEquationPCGX(), TransferDataToGPU(), and UpdateCameraPoint().
_num_imgpt
int pba::SparseBundleCU::_num_imgpt protected
Definition at line 35 of file SparseBundleCU.h.
Referenced by CheckRequiredMem(), ComputeJX(), DebugProjections(), EvaluateProjection(), EvaluateProjectionX(), GetMeanSquaredError(), InitializeStorageForCG(), NonlinearOptimizeLM(), NormalizeDataD(), NormalizeDataF(), ProcessIndexCameraQ(), ReserveStorage(), ReserveStorageAuto(), RunBundleAdjustment(), SaveNormalEquation(), SetProjection(), and TransferDataToGPU().
_num_imgpt_q
int pba::SparseBundleCU::_num_imgpt_q protected
Definition at line 79 of file SparseBundleCU.h.
Referenced by CheckRequiredMem(), ComputeJtE(), ComputeJX(), EvaluateProjection(), EvaluateProjectionX(), InitializeStorageForCG(), ProcessIndexCameraQ(), ProcessWeightCameraQ(), and TransferDataToGPU().
_num_point
int pba::SparseBundleCU::_num_point protected
Definition at line 34 of file SparseBundleCU.h.
Referenced by ApplyBlockPC(), CheckRequiredMem(), ComputeJtE(), ComputeJX(), DenormalizeData(), EvaluateDeltaNorm(), GetParameterLength(), InitializeStorageForCG(), NormalizeDataD(), ReserveStorage(), ReserveStorageAuto(), RunBundleAdjustment(), SaveUpdatedSystem(), SetPointData(), SolveNormalEquationPCGX(), TransferDataToGPU(), and UpdateCameraPoint().
_point_data
float* pba::SparseBundleCU::_point_data protected
Definition at line 37 of file SparseBundleCU.h.
Referenced by DebugProjections(), DenormalizeData(), NormalizeDataD(), RunProfileSteps(), SetPointData(), TransferDataToGPU(), TransferDataToHost(), and ValidateInputData().
_point_idx
const int* pba::SparseBundleCU::_point_idx protected
Definition at line 41 of file SparseBundleCU.h.
Referenced by DebugProjections(), NormalizeDataD(), ProcessIndexCameraQ(), ReserveStorage(), SaveNormalEquation(), SetProjection(), TransferDataToGPU(), and ValidateInputData().
_projection_sse
float pba::SparseBundleCU::_projection_sse protected
Definition at line 45 of file SparseBundleCU.h.
Referenced by DenormalizeData(), GetMeanSquaredError(), and NonlinearOptimizeLM().
_weight_q
float pba::SparseBundleCU::_weight_q protected
Definition at line 80 of file SparseBundleCU.h.
Referenced by ProcessIndexCameraQ(), ProcessWeightCameraQ(), and SetFocalMask().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/PBA/SparseBundleCU.h
/root/ACloudViewer/libs/Reconstruction/lib/PBA/SparseBundleCU.cpp