ACloudViewer: colmap::TwoViewInfoTab Class Reference
colmap::TwoViewInfoTab Class Reference
#include <database_management_widget.h>
Public Member Functions
TwoViewInfoTab ()
TwoViewInfoTab (QWidget *parent, OptionManager *options, Database *database)
void Clear ()
Protected Member Functions
void InitializeTable (const QStringList &table_header)
void ShowMatches ()
void FillTable ()
Protected Attributes
OptionManager * options_
Database * database_
const Image * image_
std::vector< std::pair< const Image *, FeatureMatches > > matches_
std::vector< int > configs_
std::vector< size_t > sorted_matches_idxs_
QTableWidget * table_widget_
QLabel * info_label_
FeatureImageViewerWidget * matches_viewer_widget_
Detailed Description
Definition at line 25 of file database_management_widget.h.
Constructor & Destructor Documentation
TwoViewInfoTab() [1/2]
colmap::TwoViewInfoTab::TwoViewInfoTab () inline
Definition at line 27 of file database_management_widget.h.
TwoViewInfoTab() [2/2]
colmap::TwoViewInfoTab::TwoViewInfoTab (QWidget * parent, OptionManager * options, Database * database)
Definition at line 38 of file database_management_widget.cc.
Member Function Documentation
Clear()
void colmap::TwoViewInfoTab::Clear ()
Definition at line 45 of file database_management_widget.cc.
References configs_, matches_, sorted_matches_idxs_, and table_widget_.
FillTable()
void colmap::TwoViewInfoTab::FillTable () protected
Definition at line 107 of file database_management_widget.cc.
References configs_, info_label_, matches_, sorted_matches_idxs_, and table_widget_.
InitializeTable()
void colmap::TwoViewInfoTab::InitializeTable (const QStringList & table_header) protected
Definition at line 52 of file database_management_widget.cc.
References info_label_, ShowMatches(), and table_widget_.
Referenced by colmap::MatchesTab::MatchesTab(), and colmap::TwoViewGeometriesTab::TwoViewGeometriesTab().
ShowMatches()
void colmap::TwoViewInfoTab::ShowMatches () protected
Definition at line 78 of file database_management_widget.cc.
References database_, image_, colmap::OptionManager::image_path, colmap::Image::ImageId(), colmap::JoinPaths(), matches_, matches_viewer_widget_, colmap::Image::Name(), options_, colmap::FeatureImageViewerWidget::ReadAndShowWithMatches(), colmap::Database::ReadKeypoints(), sorted_matches_idxs_, table_widget_, and patch::to_string().
Referenced by InitializeTable().
Member Data Documentation
configs_
std::vector<int> colmap::TwoViewInfoTab::configs_ protected
Definition at line 42 of file database_management_widget.h.
Referenced by Clear(), and FillTable().
database_
Database* colmap::TwoViewInfoTab::database_ protected
Definition at line 38 of file database_management_widget.h.
Referenced by ShowMatches().
image_
const Image* colmap::TwoViewInfoTab::image_ protected
Definition at line 40 of file database_management_widget.h.
Referenced by ShowMatches().
info_label_
QLabel* colmap::TwoViewInfoTab::info_label_ protected
Definition at line 46 of file database_management_widget.h.
Referenced by FillTable(), and InitializeTable().
matches_
std::vector<std::pair<const Image*, FeatureMatches> > colmap::TwoViewInfoTab::matches_ protected
Definition at line 41 of file database_management_widget.h.
Referenced by Clear(), FillTable(), and ShowMatches().
matches_viewer_widget_
FeatureImageViewerWidget* colmap::TwoViewInfoTab::matches_viewer_widget_ protected
Definition at line 47 of file database_management_widget.h.
Referenced by ShowMatches().
options_
OptionManager* colmap::TwoViewInfoTab::options_ protected
Definition at line 37 of file database_management_widget.h.
Referenced by ShowMatches().
sorted_matches_idxs_
std::vector<size_t> colmap::TwoViewInfoTab::sorted_matches_idxs_ protected
Definition at line 43 of file database_management_widget.h.
Referenced by Clear(), FillTable(), and ShowMatches().
table_widget_
QTableWidget* colmap::TwoViewInfoTab::table_widget_ protected
Definition at line 45 of file database_management_widget.h.
Referenced by Clear(), FillTable(), InitializeTable(), and ShowMatches().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/database_management_widget.h
/root/ACloudViewer/libs/Reconstruction/src/ui/database_management_widget.cc