ACloudViewer: flann::KNNResultSet2< DistanceType > Class Template Reference
flann::KNNResultSet2< DistanceType > Class Template Reference
#include <result_set.h>
Public Types
typedef DistanceIndex< DistanceType > DistIndex
Public Member Functions
KNNResultSet2 (size_t capacity_)
~KNNResultSet2 ()
void clear ()
size_t size () const
bool full () const
void addPoint (DistanceType dist, size_t index)
void copy (size_t *indices, DistanceType *dists, size_t num_elements, bool sorted=true)
DistanceType worstDist () const
Public Member Functions inherited from flann::ResultSet< DistanceType >
virtual ~ResultSet ()
Detailed Description
template<typename DistanceType>
class flann::KNNResultSet2< DistanceType >
Definition at line 304 of file result_set.h.
Member Typedef Documentation
DistIndex
template<typename DistanceType > typedef DistanceIndex<DistanceType> flann::KNNResultSet2< DistanceType >::DistIndex
Definition at line 307 of file result_set.h.
Constructor & Destructor Documentation
KNNResultSet2()
template<typename DistanceType > flann::KNNResultSet2< DistanceType >::KNNResultSet2 (size_t capacity_) inline
Definition at line 309 of file result_set.h.
References flann::KNNResultSet2< DistanceType >::clear().
~KNNResultSet2()
template<typename DistanceType > flann::KNNResultSet2< DistanceType >::~KNNResultSet2 () inline
Definition at line 317 of file result_set.h.
Member Function Documentation
addPoint()
template<typename DistanceType > void flann::KNNResultSet2< DistanceType >::addPoint (DistanceType dist, size_t index) inline virtual
Add another point to result set
Parameters
dist distance to point
index index of point Pre-conditions: capacity_>0
Implements flann::ResultSet< DistanceType >.
Definition at line 355 of file result_set.h.
References dist(), and flann::cuda::heap::make_heap().
clear()
template<typename DistanceType > void flann::KNNResultSet2< DistanceType >::clear () inline
Clears the result set
Definition at line 324 of file result_set.h.
References max().
Referenced by flann::KNNResultSet2< DistanceType >::KNNResultSet2(), and flann::NNIndex< Distance >::knnSearch().
copy()
template<typename DistanceType > void flann::KNNResultSet2< DistanceType >::copy (size_t * indices, DistanceType * dists, size_t num_elements, bool sorted = true) inline
Copy indices and distances to output buffers
Parameters
indices
dists
num_elements Number of elements to copy
sorted Indicates if results should be sorted
Definition at line 388 of file result_set.h.
References min(), and flann::KNNResultSet2< DistanceType >::size().
Referenced by flann::NNIndex< Distance >::knnSearch().
full()
template<typename DistanceType > bool flann::KNNResultSet2< DistanceType >::full () const inline virtual
Radius search result set always reports full
Returns
Implements flann::ResultSet< DistanceType >.
Definition at line 344 of file result_set.h.
size()
template<typename DistanceType > size_t flann::KNNResultSet2< DistanceType >::size () const inline
Returns
Number of elements in the result set
Definition at line 335 of file result_set.h.
Referenced by flann::KNNResultSet2< DistanceType >::copy(), and flann::NNIndex< Distance >::knnSearch().
worstDist()
template<typename DistanceType > DistanceType flann::KNNResultSet2< DistanceType >::worstDist () const inline virtual
Implements flann::ResultSet< DistanceType >.
Definition at line 408 of file result_set.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/util/result_set.h