ACloudViewer: QCPAbstractLegendItem Class Reference
QCPAbstractLegendItem Class Reference abstract
The abstract base class for all entries in a QCPLegend.
#include <qcustomplot.h>
Signals
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
void layerChanged (QCPLayer *newLayer)
Public Member Functions
QCPAbstractLegendItem (QCPLegend *parent)
QCPLegend * parentLegend () const
QFont font () const
QColor textColor () const
QFont selectedFont () const
QColor selectedTextColor () const
bool selectable () const
bool selected () const
void setFont (const QFont &font)
void setTextColor (const QColor &color)
void setSelectedFont (const QFont &font)
void setSelectedTextColor (const QColor &color)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
QCPAbstractLegendItem (QCPLegend *parent)
QCPLegend * parentLegend () const
QFont font () const
QColor textColor () const
QFont selectedFont () const
QColor selectedTextColor () const
bool selectable () const
bool selected () const
void setFont (const QFont &font)
void setTextColor (const QColor &color)
void setSelectedFont (const QFont &font)
void setSelectedTextColor (const QColor &color)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPLayoutElement
QCPLayoutElement (QCustomPlot *parentPlot=0)
virtual ~QCPLayoutElement ()
QCPLayout * layout () const
QRect rect () const
QRect outerRect () const
QMargins margins () const
QMargins minimumMargins () const
QCP::MarginSides autoMargins () const
QSize minimumSize () const
QSize maximumSize () const
SizeConstraintRect sizeConstraintRect () const
QCPMarginGroup * marginGroup (QCP::MarginSide side) const
QHash< QCP::MarginSide, QCPMarginGroup * > marginGroups () const
void setOuterRect (const QRect &rect)
void setMargins (const QMargins &margins)
void setMinimumMargins (const QMargins &margins)
void setAutoMargins (QCP::MarginSides sides)
void setMinimumSize (const QSize &size)
void setMinimumSize (int width, int height)
void setMaximumSize (const QSize &size)
void setMaximumSize (int width, int height)
void setSizeConstraintRect (SizeConstraintRect constraintRect)
void setMarginGroup (QCP::MarginSides sides, QCPMarginGroup *group)
virtual void update (UpdatePhase phase)
virtual QSize minimumOuterSizeHint () const
virtual QSize maximumOuterSizeHint () const
virtual QList< QCPLayoutElement * > elements (bool recursive) const
QCPLayoutElement (QCustomPlot *parentPlot=0)
virtual ~QCPLayoutElement ()
QCPLayout * layout () const
QRect rect () const
QRect outerRect () const
QMargins margins () const
QMargins minimumMargins () const
QCP::MarginSides autoMargins () const
QSize minimumSize () const
QSize maximumSize () const
QCPMarginGroup * marginGroup (QCP::MarginSide side) const
QHash< QCP::MarginSide, QCPMarginGroup * > marginGroups () const
void setOuterRect (const QRect &rect)
void setMargins (const QMargins &margins)
void setMinimumMargins (const QMargins &margins)
void setAutoMargins (QCP::MarginSides sides)
void setMinimumSize (const QSize &size)
void setMinimumSize (int width, int height)
void setMaximumSize (const QSize &size)
void setMaximumSize (int width, int height)
void setMarginGroup (QCP::MarginSides sides, QCPMarginGroup *group)
virtual void update (UpdatePhase phase)
virtual QSize minimumSizeHint () const
virtual QSize maximumSizeHint () const
virtual QList< QCPLayoutElement * > elements (bool recursive) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
virtual ~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Protected Member Functions
virtual QCP::Interaction selectionCategory () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual QRect clipRect () const
virtual void draw (QCPPainter *painter)=0
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual QCP::Interaction selectionCategory () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual QRect clipRect () const
virtual void draw (QCPPainter *painter)=0
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
Protected Member Functions inherited from QCPLayoutElement
virtual int calculateAutoMargin (QCP::MarginSide side)
virtual void layoutChanged ()
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual int calculateAutoMargin (QCP::MarginSide side)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
Protected Member Functions inherited from QCPLayerable
virtual void mousePressEvent (QMouseEvent *event, const QVariant &details)
virtual void mouseMoveEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseReleaseEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseDoubleClickEvent (QMouseEvent *event, const QVariant &details)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QCPLegend * mParentLegend
QFont mFont
QColor mTextColor
QFont mSelectedFont
QColor mSelectedTextColor
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayoutElement
QCPLayout * mParentLayout
QSize mMinimumSize
QSize mMaximumSize
SizeConstraintRect mSizeConstraintRect
QRect mRect
QRect mOuterRect
QMargins mMargins
QMargins mMinimumMargins
QCP::MarginSides mAutoMargins
QHash< QCP::MarginSide, QCPMarginGroup * > mMarginGroups
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Public Types inherited from QCPLayoutElement
enum UpdatePhase {
upPreparation , upMargins , upLayout , upPreparation ,
upMargins , upLayout
}
enum SizeConstraintRect { scrInnerRect , scrOuterRect }
enum UpdatePhase {
upPreparation , upMargins , upLayout , upPreparation ,
upMargins , upLayout
}
Detailed Description
The abstract base class for all entries in a QCPLegend.
It defines a very basic interface for entries in a QCPLegend. For representing plottables in the legend, the subclass QCPPlottableLegendItem is more suitable.
Only derive directly from this class when you need absolute freedom (e.g. a custom legend entry that's not even associated with a plottable).
You must implement the following pure virtual functions:
draw (from QCPLayerable)
You inherit the following members you may use:
QCPLegend *mParentLegend A pointer to the parent QCPLegend.
QFont mFont The generic font of the item. You should use this font for all or at least the most prominent text of the item.
Definition at line 5512 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPAbstractLegendItem() [1/2]
QCPAbstractLegendItem::QCPAbstractLegendItem (QCPLegend * parent) explicit
Constructs a QCPAbstractLegendItem and associates it with the QCPLegend parent. This does not cause the item to be added to parent, so QCPLegend::addItem must be called separately.
Definition at line 18715 of file qcustomplot.cpp.
References QCPLayerable::setLayer(), and QCPLayoutElement::setMargins().
QCPAbstractLegendItem() [2/2]
QCPAbstractLegendItem::QCPAbstractLegendItem (QCPLegend * parent) explicit
Member Function Documentation
applyDefaultAntialiasingHint() [1/2]
void QCPAbstractLegendItem::applyDefaultAntialiasingHint (QCPPainter * painter) const protected virtual
Reimplemented from QCPLayoutElement.
Definition at line 18809 of file qcustomplot.cpp.
References QCP::aeLegendItems, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
applyDefaultAntialiasingHint() [2/2]
virtual void QCPAbstractLegendItem::applyDefaultAntialiasingHint (QCPPainter * painter) const protected virtual
Reimplemented from QCPLayoutElement.
clipRect() [1/2]
QRect QCPAbstractLegendItem::clipRect () const protected virtual
Reimplemented from QCPLayerable.
Definition at line 18815 of file qcustomplot.cpp.
References QCPLayoutElement::mOuterRect.
clipRect() [2/2]
virtual QRect QCPAbstractLegendItem::clipRect () const protected virtual
Reimplemented from QCPLayerable.
deselectEvent() [1/2]
void QCPAbstractLegendItem::deselectEvent (bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 18834 of file qcustomplot.cpp.
References mParentLegend, mSelectable, mSelected, QCPLegend::selectableParts(), setSelected(), and QCPLegend::spItems.
deselectEvent() [2/2]
virtual void QCPAbstractLegendItem::deselectEvent (bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
draw() [1/2]
virtual void QCPAbstractLegendItem::draw (QCPPainter * painter) protected pure virtual
Reimplemented from QCPLayoutElement.
Implemented in QCPPlottableLegendItem, and QCPPlottableLegendItem.
draw() [2/2]
virtual void QCPAbstractLegendItem::draw (QCPPainter * painter) protected pure virtual
Reimplemented from QCPLayoutElement.
Implemented in QCPPlottableLegendItem, and QCPPlottableLegendItem.
font() [1/2]
QFont QCPAbstractLegendItem::font () const inline
Definition at line 5531 of file qcustomplot.h.
Referenced by setFont(), and setSelectedFont().
font() [2/2]
QFont QCPAbstractLegendItem::font () const inline
Definition at line 2562 of file qcustomplot.h.
parentLegend() [1/2]
QCPLegend* QCPAbstractLegendItem::parentLegend () const inline
Definition at line 5530 of file qcustomplot.h.
parentLegend() [2/2]
QCPLegend* QCPAbstractLegendItem::parentLegend () const inline
Definition at line 2561 of file qcustomplot.h.
selectable() [1/2]
bool QCPAbstractLegendItem::selectable () const inline
Definition at line 5535 of file qcustomplot.h.
Referenced by setSelectable().
selectable() [2/2]
bool QCPAbstractLegendItem::selectable () const inline
Definition at line 2566 of file qcustomplot.h.
selectableChanged [1/2]
void QCPAbstractLegendItem::selectableChanged (bool selectable) signal
Referenced by setSelectable().
selectableChanged [2/2]
void QCPAbstractLegendItem::selectableChanged (bool selectable) signal
selected() [1/2]
bool QCPAbstractLegendItem::selected () const inline
Definition at line 5536 of file qcustomplot.h.
Referenced by QCPLegend::selectedParts(), and setSelected().
selected() [2/2]
bool QCPAbstractLegendItem::selected () const inline
Definition at line 2567 of file qcustomplot.h.
selectedFont() [1/2]
QFont QCPAbstractLegendItem::selectedFont () const inline
Definition at line 5533 of file qcustomplot.h.
selectedFont() [2/2]
QFont QCPAbstractLegendItem::selectedFont () const inline
Definition at line 2564 of file qcustomplot.h.
selectedTextColor() [1/2]
QColor QCPAbstractLegendItem::selectedTextColor () const inline
Definition at line 5534 of file qcustomplot.h.
selectedTextColor() [2/2]
QColor QCPAbstractLegendItem::selectedTextColor () const inline
Definition at line 2565 of file qcustomplot.h.
selectEvent() [1/2]
void QCPAbstractLegendItem::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 18818 of file qcustomplot.cpp.
References event, mParentLegend, mSelectable, mSelected, QCPLegend::selectableParts(), setSelected(), and QCPLegend::spItems.
selectEvent() [2/2]
virtual void QCPAbstractLegendItem::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
selectionCategory() [1/2]
QCP::Interaction QCPAbstractLegendItem::selectionCategory () const protected virtual
Reimplemented from QCPLayerable.
Definition at line 19550 of file qcustomplot.cpp.
References QCP::iSelectLegend.
selectionCategory() [2/2]
virtual QCP::Interaction QCPAbstractLegendItem::selectionCategory () const protected virtual
Reimplemented from QCPLayerable.
selectionChanged [1/2]
void QCPAbstractLegendItem::selectionChanged (bool selected) signal
This signal is emitted when the selection state of this legend item has changed, either by user interaction or by a direct call to setSelected.
Referenced by setSelected().
selectionChanged [2/2]
void QCPAbstractLegendItem::selectionChanged (bool selected) signal
selectTest() [1/2]
double QCPAbstractLegendItem::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
Layout elements are sensitive to events inside their outer rect. If pos is within the outer rect, this method returns a value corresponding to 0.99 times the parent plot's selection tolerance. However, layout elements are not selectable by default. So if onlySelectable is true, -1.0 is returned.
See QCPLayerable::selectTest for a general explanation of this virtual method.
QCPLayoutElement subclasses may reimplement this method to provide more specific selection test behaviour.
Reimplemented from QCPLayoutElement.
Definition at line 18792 of file qcustomplot.cpp.
References mParentLegend, QCPLayerable::mParentPlot, QCPLayoutElement::mRect, mSelectable, QCPLegend::selectableParts(), QCustomPlot::selectionTolerance(), and QCPLegend::spItems.
selectTest() [2/2]
virtual double QCPAbstractLegendItem::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
Layout elements are sensitive to events inside their outer rect. If pos is within the outer rect, this method returns a value corresponding to 0.99 times the parent plot's selection tolerance. However, layout elements are not selectable by default. So if onlySelectable is true, -1.0 is returned.
See QCPLayerable::selectTest for a general explanation of this virtual method.
QCPLayoutElement subclasses may reimplement this method to provide more specific selection test behaviour.
Reimplemented from QCPLayoutElement.
setFont() [1/2]
void QCPAbstractLegendItem::setFont (const QFont & font)
Sets the default font of this specific legend item to font.
See also
setTextColor, QCPLegend::setFont
Definition at line 18733 of file qcustomplot.cpp.
References font(), and mFont.
Referenced by QCPLegend::setFont().
setFont() [2/2]
void QCPAbstractLegendItem::setFont (const QFont & font)
setSelectable() [1/2]
void QCPAbstractLegendItem::setSelectable (bool selectable)
Sets whether this specific legend item is selectable.
See also
setSelectedParts, QCustomPlot::setInteractions
Definition at line 18769 of file qcustomplot.cpp.
References mSelectable, selectable(), and selectableChanged().
setSelectable() [2/2]
Q_SLOT void QCPAbstractLegendItem::setSelectable (bool selectable)
setSelected() [1/2]
void QCPAbstractLegendItem::setSelected (bool selected)
Sets whether this specific legend item is selected.
It is possible to set the selection state of this item by calling this function directly, even if setSelectable is set to false.
See also
setSelectableParts, QCustomPlot::setInteractions
Definition at line 18784 of file qcustomplot.cpp.
References mSelected, selected(), and selectionChanged().
Referenced by deselectEvent(), selectEvent(), and QCPLegend::setSelectedParts().
setSelected() [2/2]
Q_SLOT void QCPAbstractLegendItem::setSelected (bool selected)
setSelectedFont() [1/2]
void QCPAbstractLegendItem::setSelectedFont (const QFont & font)
When this legend item is selected, font is used to draw generic text, instead of the normal font set with setFont.
See also
setFont, QCPLegend::setSelectedFont
Definition at line 18750 of file qcustomplot.cpp.
References font(), and mSelectedFont.
Referenced by QCPLegend::setSelectedFont().
setSelectedFont() [2/2]
void QCPAbstractLegendItem::setSelectedFont (const QFont & font)
setSelectedTextColor() [1/2]
void QCPAbstractLegendItem::setSelectedTextColor (const QColor & color)
When this legend item is selected, color is used to draw generic text, instead of the normal color set with setTextColor.
See also
setTextColor, QCPLegend::setSelectedTextColor
Definition at line 18760 of file qcustomplot.cpp.
References color, and mSelectedTextColor.
Referenced by QCPLegend::setSelectedTextColor().
setSelectedTextColor() [2/2]
void QCPAbstractLegendItem::setSelectedTextColor (const QColor & color)
setTextColor() [1/2]
void QCPAbstractLegendItem::setTextColor (const QColor & color)
Sets the default text color of this specific legend item to color.
See also
setFont, QCPLegend::setTextColor
Definition at line 18740 of file qcustomplot.cpp.
References color, and mTextColor.
Referenced by QCPLegend::setTextColor().
setTextColor() [2/2]
void QCPAbstractLegendItem::setTextColor (const QColor & color)
textColor() [1/2]
QColor QCPAbstractLegendItem::textColor () const inline
Definition at line 5532 of file qcustomplot.h.
textColor() [2/2]
QColor QCPAbstractLegendItem::textColor () const inline
Definition at line 2563 of file qcustomplot.h.
Member Data Documentation
mFont
QFont QCPAbstractLegendItem::mFont protected
Definition at line 5558 of file qcustomplot.h.
Referenced by QCPPlotTitle::font(), QCPPlottableLegendItem::getFont(), and setFont().
mParentLegend
QCPLegend * QCPAbstractLegendItem::mParentLegend protected
Definition at line 5557 of file qcustomplot.h.
Referenced by deselectEvent(), QCPPlottableLegendItem::draw(), QCPPlottableLegendItem::getIconBorderPen(), QCPPlottableLegendItem::minimumOuterSizeHint(), QCPPlottableLegendItem::minimumSizeHint(), selectEvent(), and selectTest().
mSelectable
bool QCPAbstractLegendItem::mSelectable protected
Definition at line 5562 of file qcustomplot.h.
Referenced by deselectEvent(), QCPPlotTitle::selectable(), selectEvent(), selectTest(), and setSelectable().
mSelected
bool QCPAbstractLegendItem::mSelected protected
Definition at line 5562 of file qcustomplot.h.
Referenced by deselectEvent(), QCPPlottableLegendItem::getFont(), QCPPlottableLegendItem::getIconBorderPen(), QCPPlottableLegendItem::getTextColor(), QCPPlotTitle::selected(), selectEvent(), and setSelected().
mSelectedFont
QFont QCPAbstractLegendItem::mSelectedFont protected
Definition at line 5560 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getFont(), QCPPlotTitle::selectedFont(), and setSelectedFont().
mSelectedTextColor
QColor QCPAbstractLegendItem::mSelectedTextColor protected
Definition at line 5561 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getTextColor(), QCPPlotTitle::selectedTextColor(), and setSelectedTextColor().
mTextColor
QColor QCPAbstractLegendItem::mTextColor protected
Definition at line 5559 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getTextColor(), setTextColor(), and QCPPlotTitle::textColor().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp