ACloudViewer: ecvAnnotationsTool Class Reference
ecvAnnotationsTool Class Reference
Dialog for managing a clipping box.
#include <ecvAnnotationsTool.h>
Public Slots
void toggleInteractors (bool state)
void toggleEditMode (bool state)
Public Member Functions
ecvAnnotationsTool (QWidget *parent)
Default constructor.
virtual ~ecvAnnotationsTool () override
Default destructor.
virtual bool start () override
Starts process.
virtual void stop (bool state) override
Stops process/dialog.
virtual bool linkWith (QWidget *win) override
Links the overlay dialog with a MDI window.
bool setAnnotationsTool (ecvGenericAnnotationTool *annotationTool)
bool addAssociatedEntity (ccHObject *anObject)
Adds an entity.
void releaseAssociatedEntities ()
unsigned getNumberOfAssociatedEntity () const
Returns the current number of associated entities.
Public Member Functions inherited from ccOverlayDialog
ccOverlayDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::FramelessWindowHint|Qt::Tool)
Default constructor.
~ccOverlayDialog () override
Destructor.
void reject () override
void addOverridenShortcut (Qt::Key key)
bool started () const
Returns whether the tool is currently started or not.
Protected Slots
void onShortcutTriggered (int)
To capture overridden shortcuts (pause button, etc.)
void importClassesFromFile ()
void toggleBox (bool)
void toggleOrigin (bool dummy)
void onNewMode ()
void onUnionMode ()
void onTrimMode ()
void onIntersectMode ()
void onLabelSelected ()
void onLabelChanged (int index)
void onItemPicked (bool isPicked)
void saveAnnotations ()
void reset ()
void closeDialog ()
void exportAnnotationToSF ()
void updateLabelsCombox (const std::vector< std::string > &labels)
void shiftXMinus ()
void shiftXPlus ()
void shiftYMinus ()
void shiftYPlus ()
void shiftZMinus ()
void shiftZPlus ()
void setFrontView ()
void setBottomView ()
void setTopView ()
void setBackView ()
void setLeftView ()
void setRightView ()
Protected Slots inherited from ccOverlayDialog
virtual void onLinkedWindowDeletion (QObject *object=nullptr)
Slot called when the linked window is deleted (calls 'onClose')
Protected Member Functions
void shiftBox (unsigned char dim, bool minus)
Shift box.
void setView (CC_VIEW_ORIENTATION orientation)
Sets predefined view.
ccBBox getSelectedEntityBbox ()
Protected Member Functions inherited from ccOverlayDialog
bool eventFilter (QObject *obj, QEvent *e) override
Protected Attributes
ecvGenericAnnotationTool * m_annotationTool
Annotation tool.
ccBBox m_box
bounding box
ccHObject m_entityContainer
Associated entities container.
bool m_disabledCombEvent
for solving dummy event trigger
bool m_editMode
Protected Attributes inherited from ccOverlayDialog
QWidget * m_associatedWin
Associated (MDI) window.
bool m_processing
Running/processing state.
QList< int > m_overriddenKeys
Overridden keys.
Additional Inherited Members
Signals inherited from ccOverlayDialog
void processFinished (bool accepted)
Signal emitted when process is finished.
void shortcutTriggered (int key)
Signal emitted when an overridden key shortcut is pressed.
void shown ()
Signal emitted when a 'show' event is detected.
Detailed Description
Dialog for managing a clipping box.
Definition at line 28 of file ecvAnnotationsTool.h.
Constructor & Destructor Documentation
ecvAnnotationsTool()
ecvAnnotationsTool::ecvAnnotationsTool (QWidget * parent) explicit
Default constructor.
Definition at line 31 of file ecvAnnotationsTool.cpp.
References ccOverlayDialog::addOverridenShortcut(), closeDialog(), exportAnnotationToSF(), importClassesFromFile(), m_disabledCombEvent, onIntersectMode(), onLabelChanged(), onLabelSelected(), onNewMode(), onShortcutTriggered(), onTrimMode(), onUnionMode(), reset(), saveAnnotations(), setBackView(), setBottomView(), setFrontView(), setLeftView(), setRightView(), setTopView(), shiftXMinus(), shiftXPlus(), shiftYMinus(), shiftYPlus(), shiftZMinus(), shiftZPlus(), ccOverlayDialog::shortcutTriggered(), toggleBox(), toggleEditMode(), toggleInteractors(), and toggleOrigin().
~ecvAnnotationsTool()
ecvAnnotationsTool::~ecvAnnotationsTool () override virtual
Default destructor.
Definition at line 124 of file ecvAnnotationsTool.cpp.
References releaseAssociatedEntities().
Member Function Documentation
addAssociatedEntity()
bool ecvAnnotationsTool::addAssociatedEntity (ccHObject * anObject)
Adds an entity.
Returns
success, if the entity is eligible for clipping
Definition at line 323 of file ecvAnnotationsTool.cpp.
References ccHObject::addChild(), ccHObject::DP_NONE, CVLog::Error(), ccHObject::getBB_recursive(), ccObject::isKindOf(), cloudViewer::BoundingBoxTpl< T >::isValid(), m_annotationTool, m_entityContainer, CV_TYPES::POINT_CLOUD, reset(), ccObject::setEnabled(), and ccDrawableObject::setVisible().
closeDialog
void ecvAnnotationsTool::closeDialog () protected slot
Definition at line 462 of file ecvAnnotationsTool.cpp.
References stop().
Referenced by ecvAnnotationsTool().
exportAnnotationToSF
void ecvAnnotationsTool::exportAnnotationToSF () protected slot
Definition at line 471 of file ecvAnnotationsTool.cpp.
References CVLog::Error(), ecvGenericAnnotationTool::getCurrentAnnotations(), ccHObject::getFirstChild(), ccEntityAction::importToSF(), m_annotationTool, m_entityContainer, CVLog::Print(), ccDrawableObject::showSF(), and CVLog::Warning().
Referenced by ecvAnnotationsTool().
getNumberOfAssociatedEntity()
unsigned ecvAnnotationsTool::getNumberOfAssociatedEntity () const
Returns the current number of associated entities.
Definition at line 351 of file ecvAnnotationsTool.cpp.
References ccHObject::getChildrenNumber(), and m_entityContainer.
Referenced by getSelectedEntityBbox().
getSelectedEntityBbox()
ccBBox ecvAnnotationsTool::getSelectedEntityBbox () protected
Definition at line 513 of file ecvAnnotationsTool.cpp.
References ccHObject::getDisplayBB_recursive(), getNumberOfAssociatedEntity(), and m_entityContainer.
importClassesFromFile
void ecvAnnotationsTool::importClassesFromFile () protected slot
Definition at line 254 of file ecvAnnotationsTool.cpp.
References ecvPS::CurrentPath(), ecvFileUtils::defaultDocPath(), CVTools::FromQString(), ecvGenericAnnotationTool::getAnnotationLabels(), ecvSettingManager::getValue(), ecvGenericAnnotationTool::loadClassesFromFile(), ecvPS::LoadFile(), m_annotationTool, ecvSettingManager::setValue(), and updateLabelsCombox().
Referenced by ecvAnnotationsTool().
linkWith()
bool ecvAnnotationsTool::linkWith (QWidget * win) override virtual
Links the overlay dialog with a MDI window.
Warning: link can't be modified while dialog is displayed/process is running!
Returns
success
Reimplemented from ccOverlayDialog.
Definition at line 357 of file ecvAnnotationsTool.cpp.
References ccOverlayDialog::linkWith().
onIntersectMode
void ecvAnnotationsTool::onIntersectMode () protected slot
Definition at line 198 of file ecvAnnotationsTool.cpp.
References ecvGenericAnnotationTool::intersectMode(), and m_annotationTool.
Referenced by ecvAnnotationsTool().
onItemPicked
void ecvAnnotationsTool::onItemPicked (bool isPicked) protected slot
Definition at line 239 of file ecvAnnotationsTool.cpp.
Referenced by setAnnotationsTool().
onLabelChanged
void ecvAnnotationsTool::onLabelChanged (int index) protected slot
Definition at line 206 of file ecvAnnotationsTool.cpp.
References ecvColor::LookUpTable::at(), ecvColor::RgbTpl< Type >::b, ecvGenericAnnotationTool::changeAnnotationType(), ecvColor::RgbTpl< Type >::g, m_annotationTool, m_disabledCombEvent, m_editMode, ecvColor::RgbTpl< Type >::r, ecvGenericAnnotationTool::selectExistedAnnotation(), and ecvColor::white().
Referenced by ecvAnnotationsTool(), and onLabelSelected().
onLabelSelected
void ecvAnnotationsTool::onLabelSelected () protected slot
Definition at line 204 of file ecvAnnotationsTool.cpp.
References onLabelChanged().
Referenced by ecvAnnotationsTool().
onNewMode
void ecvAnnotationsTool::onNewMode () protected slot
Definition at line 180 of file ecvAnnotationsTool.cpp.
References m_annotationTool, and ecvGenericAnnotationTool::resetMode().
Referenced by ecvAnnotationsTool().
onShortcutTriggered
void ecvAnnotationsTool::onShortcutTriggered (int key) protected slot
To capture overridden shortcuts (pause button, etc.)
Definition at line 137 of file ecvAnnotationsTool.cpp.
Referenced by ecvAnnotationsTool().
onTrimMode
void ecvAnnotationsTool::onTrimMode () protected slot
Definition at line 192 of file ecvAnnotationsTool.cpp.
References m_annotationTool, and ecvGenericAnnotationTool::trimMode().
Referenced by ecvAnnotationsTool().
onUnionMode
void ecvAnnotationsTool::onUnionMode () protected slot
Definition at line 186 of file ecvAnnotationsTool.cpp.
References m_annotationTool, and ecvGenericAnnotationTool::unionMode().
Referenced by ecvAnnotationsTool().
releaseAssociatedEntities()
void ecvAnnotationsTool::releaseAssociatedEntities ()
Definition at line 319 of file ecvAnnotationsTool.cpp.
References m_entityContainer, and ccHObject::removeAllChildren().
Referenced by stop(), and ~ecvAnnotationsTool().
reset
void ecvAnnotationsTool::reset (void) protected slot
Definition at line 452 of file ecvAnnotationsTool.cpp.
References cloudViewer::BoundingBoxTpl< T >::clear(), ccHObject::getBB_recursive(), ccHObject::getChildrenNumber(), m_annotationTool, m_box, m_entityContainer, and ecvGenericAnnotationTool::reset().
Referenced by addAssociatedEntity(), and ecvAnnotationsTool().
saveAnnotations
void ecvAnnotationsTool::saveAnnotations () protected slot
Definition at line 248 of file ecvAnnotationsTool.cpp.
References ecvGenericAnnotationTool::exportAnnotations(), and m_annotationTool.
Referenced by ecvAnnotationsTool().
setAnnotationsTool()
bool ecvAnnotationsTool::setAnnotationsTool (ecvGenericAnnotationTool * annotationTool)
Definition at line 126 of file ecvAnnotationsTool.cpp.
References m_annotationTool, ecvGenericAnnotationTool::objectPicked(), and onItemPicked().
setBackView
void ecvAnnotationsTool::setBackView () protected slot
Definition at line 507 of file ecvAnnotationsTool.cpp.
References CC_BACK_VIEW, and setView().
Referenced by ecvAnnotationsTool().
setBottomView
void ecvAnnotationsTool::setBottomView () protected slot
Definition at line 503 of file ecvAnnotationsTool.cpp.
References CC_BOTTOM_VIEW, and setView().
Referenced by ecvAnnotationsTool().
setFrontView
void ecvAnnotationsTool::setFrontView () protected slot
Definition at line 505 of file ecvAnnotationsTool.cpp.
References CC_FRONT_VIEW, and setView().
Referenced by ecvAnnotationsTool().
setLeftView
void ecvAnnotationsTool::setLeftView () protected slot
Definition at line 509 of file ecvAnnotationsTool.cpp.
References CC_LEFT_VIEW, and setView().
Referenced by ecvAnnotationsTool().
setRightView
void ecvAnnotationsTool::setRightView () protected slot
Definition at line 511 of file ecvAnnotationsTool.cpp.
References CC_RIGHT_VIEW, and setView().
Referenced by ecvAnnotationsTool().
setTopView
void ecvAnnotationsTool::setTopView () protected slot
Definition at line 501 of file ecvAnnotationsTool.cpp.
References CC_TOP_VIEW, and setView().
Referenced by ecvAnnotationsTool().
setView()
void ecvAnnotationsTool::setView (CC_VIEW_ORIENTATION orientation) protected
Sets predefined view.
Definition at line 521 of file ecvAnnotationsTool.cpp.
References ecvDisplayTools::SetView().
Referenced by setBackView(), setBottomView(), setFrontView(), setLeftView(), setRightView(), and setTopView().
shiftBox()
void ecvAnnotationsTool::shiftBox (unsigned char dim, bool minus) protected
Shift box.
Definition at line 447 of file ecvAnnotationsTool.cpp.
Referenced by shiftXMinus(), shiftXPlus(), shiftYMinus(), shiftYPlus(), shiftZMinus(), and shiftZPlus().
shiftXMinus
void ecvAnnotationsTool::shiftXMinus () inline protected slot
Definition at line 80 of file ecvAnnotationsTool.h.
References shiftBox().
Referenced by ecvAnnotationsTool().
shiftXPlus
void ecvAnnotationsTool::shiftXPlus () inline protected slot
Definition at line 81 of file ecvAnnotationsTool.h.
References shiftBox().
Referenced by ecvAnnotationsTool().
shiftYMinus
void ecvAnnotationsTool::shiftYMinus () inline protected slot
Definition at line 82 of file ecvAnnotationsTool.h.
References shiftBox().
Referenced by ecvAnnotationsTool().
shiftYPlus
void ecvAnnotationsTool::shiftYPlus () inline protected slot
Definition at line 83 of file ecvAnnotationsTool.h.
References shiftBox().
Referenced by ecvAnnotationsTool().
shiftZMinus
void ecvAnnotationsTool::shiftZMinus () inline protected slot
Definition at line 84 of file ecvAnnotationsTool.h.
References shiftBox().
Referenced by ecvAnnotationsTool().
shiftZPlus
void ecvAnnotationsTool::shiftZPlus () inline protected slot
Definition at line 85 of file ecvAnnotationsTool.h.
References shiftBox().
Referenced by ecvAnnotationsTool().
start()
bool ecvAnnotationsTool::start () override virtual
Starts process.
Returns
success
Reimplemented from ccOverlayDialog.
Definition at line 365 of file ecvAnnotationsTool.cpp.
References ecvGenericAnnotationTool::BOUNDINGBOX, CVLog::Error(), ecvGenericAnnotationTool::getAnnotationLabels(), ecvGenericAnnotationTool::getAnnotationMode(), ccHObject::getFirstChild(), m_annotationTool, m_entityContainer, ccOverlayDialog::m_processing, ecvGenericAnnotationTool::SEMANTICS, ecvGenericAnnotationTool::setInputCloud(), ccOverlayDialog::start(), ecvGenericAnnotationTool::start(), ccHObjectCaster::ToPointCloud(), and updateLabelsCombox().
stop()
void ecvAnnotationsTool::stop (bool accepted) override virtual
Stops process/dialog.
Automatically emits the 'processFinished' signal (with input state as argument).
Parameters
accepted process/dialog result
Reimplemented from ccOverlayDialog.
Definition at line 404 of file ecvAnnotationsTool.cpp.
References m_annotationTool, releaseAssociatedEntities(), ecvGenericAnnotationTool::stop(), and ccOverlayDialog::stop().
Referenced by closeDialog().
toggleBox
void ecvAnnotationsTool::toggleBox (bool state) protected slot
Definition at line 287 of file ecvAnnotationsTool.cpp.
References ecvGenericAnnotationTool::hideAnnotation(), m_annotationTool, ecvGenericAnnotationTool::showAnnotation(), ecvDisplayTools::UpdateScreen(), and CVLog::Warning().
Referenced by ecvAnnotationsTool().
toggleEditMode
void ecvAnnotationsTool::toggleEditMode (bool state) slot
Definition at line 355 of file ecvAnnotationsTool.cpp.
References m_editMode.
Referenced by ecvAnnotationsTool().
toggleInteractors
void ecvAnnotationsTool::toggleInteractors (bool state) slot
Definition at line 241 of file ecvAnnotationsTool.cpp.
References m_annotationTool, and ecvGenericAnnotationTool::toggleInteractor().
Referenced by ecvAnnotationsTool().
toggleOrigin
void ecvAnnotationsTool::toggleOrigin (bool dummy) protected slot
Definition at line 303 of file ecvAnnotationsTool.cpp.
References ecvGenericAnnotationTool::hideOrigin(), m_annotationTool, ecvGenericAnnotationTool::showOrigin(), ecvDisplayTools::UpdateScreen(), and CVLog::Warning().
Referenced by ecvAnnotationsTool().
updateLabelsCombox
void ecvAnnotationsTool::updateLabelsCombox (const std::vector< std::string > & labels) protected slot
Definition at line 422 of file ecvAnnotationsTool.cpp.
References ecvColor::LookUpTable::at(), ecvColor::RgbTpl< Type >::b, ecvColor::RgbTpl< Type >::g, m_disabledCombEvent, name, ecvColor::RgbTpl< Type >::r, CVTools::ToQString(), and ecvColor::white().
Referenced by importClassesFromFile(), and start().
Member Data Documentation
m_annotationTool
ecvGenericAnnotationTool* ecvAnnotationsTool::m_annotationTool protected
Annotation tool.
Definition at line 102 of file ecvAnnotationsTool.h.
Referenced by addAssociatedEntity(), exportAnnotationToSF(), importClassesFromFile(), onIntersectMode(), onLabelChanged(), onNewMode(), onTrimMode(), onUnionMode(), reset(), saveAnnotations(), setAnnotationsTool(), start(), stop(), toggleBox(), toggleInteractors(), and toggleOrigin().
m_box
ccBBox ecvAnnotationsTool::m_box protected
bounding box
Definition at line 107 of file ecvAnnotationsTool.h.
Referenced by reset().
m_disabledCombEvent
bool ecvAnnotationsTool::m_disabledCombEvent protected
for solving dummy event trigger
Definition at line 113 of file ecvAnnotationsTool.h.
Referenced by ecvAnnotationsTool(), onLabelChanged(), and updateLabelsCombox().
m_editMode
bool ecvAnnotationsTool::m_editMode protected
Definition at line 115 of file ecvAnnotationsTool.h.
Referenced by onLabelChanged(), and toggleEditMode().
m_entityContainer
ccHObject ecvAnnotationsTool::m_entityContainer protected
Associated entities container.
Definition at line 110 of file ecvAnnotationsTool.h.
Referenced by addAssociatedEntity(), exportAnnotationToSF(), getNumberOfAssociatedEntity(), getSelectedEntityBbox(), releaseAssociatedEntities(), reset(), and start().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvAnnotationsTool.h
/root/ACloudViewer/app/ecvAnnotationsTool.cpp