ACloudViewer: cloudViewer::visualization::rendering::IBLRotationInteractorLogic Class Reference
cloudViewer::visualization::rendering::IBLRotationInteractorLogic Class Reference
#include <IBLRotationInteractorLogic.h>
Public Member Functions
IBLRotationInteractorLogic (Scene *scene, Camera *camera)
void Rotate (int dx, int dy) override
void RotateZ (int dx, int dy) override
Rotates about the forward axis of the matrix.
void StartMouseDrag ()
void UpdateMouseDragUI ()
void EndMouseDrag ()
Camera::Transform GetCurrentRotation () const
Public Member Functions inherited from cloudViewer::visualization::rendering::MatrixInteractorLogic
virtual ~MatrixInteractorLogic ()
void SetViewSize (int width, int height)
int GetViewWidth () const
int GetViewHeight () const
const ccBBox & GetBoundingBox () const
virtual void SetBoundingBox (const ccBBox &bounds)
Eigen::Vector3f GetCenterOfRotation () const
void SetMouseDownInfo (const Camera::Transform &matrix, const Eigen::Vector3f &center_of_rotation)
const Camera::Transform & GetMatrix () const
virtual void RotateWorld (int dx, int dy, const Eigen::Vector3f &x_axis, const Eigen::Vector3f &y_axis)
virtual void RotateZWorld (int dx, int dy, const Eigen::Vector3f &forward)
virtual void Dolly (float dy, DragType drag_type)
virtual void Dolly (float z_dist, Camera::Transform matrix)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::rendering::MatrixInteractorLogic
enum class DragType { MOUSE , WHEEL , TWO_FINGER }
Protected Member Functions inherited from cloudViewer::visualization::rendering::MatrixInteractorLogic
void SetMatrix (const Camera::Transform &matrix)
float CalcRotateRadians (int dx, int dy)
float CalcRotateZRadians (int dx, int dy)
float CalcDollyDist (float dy, DragType drag_type, const Camera::Transform &matrix)
Protected Attributes inherited from cloudViewer::visualization::rendering::MatrixInteractorLogic
int view_width_ = 1
int view_height_ = 1
double model_size_ = 20.0
ccBBox model_bounds_
Eigen::Vector3f center_of_rotation_
Camera::Transform matrix_at_mouse_down_
Eigen::Vector3f center_of_rotation_at_mouse_down_
Detailed Description
Definition at line 19 of file IBLRotationInteractorLogic.h.
Constructor & Destructor Documentation
IBLRotationInteractorLogic()
cloudViewer::visualization::rendering::IBLRotationInteractorLogic::IBLRotationInteractorLogic (Scene * scene, Camera * camera)
Definition at line 17 of file IBLRotationInteractorLogic.cpp.
Member Function Documentation
EndMouseDrag()
void cloudViewer::visualization::rendering::IBLRotationInteractorLogic::EndMouseDrag ()
Definition at line 53 of file IBLRotationInteractorLogic.cpp.
References cloudViewer::visualization::rendering::Scene::ShowSkybox().
GetCurrentRotation()
Camera::Transform cloudViewer::visualization::rendering::IBLRotationInteractorLogic::GetCurrentRotation () const
Definition at line 62 of file IBLRotationInteractorLogic.cpp.
References cloudViewer::visualization::rendering::MatrixInteractorLogic::GetMatrix().
Referenced by Rotate(), and RotateZ().
Rotate()
void cloudViewer::visualization::rendering::IBLRotationInteractorLogic::Rotate (int dx, int dy) override virtual
Rotates about an axis defined by dx * matrixLeft, dy * matrixUp. dy is assumed to be in window-style coordinates, that is, going up produces a negative dy. The axis goes through the center of rotation.
Reimplemented from cloudViewer::visualization::rendering::MatrixInteractorLogic.
Definition at line 21 of file IBLRotationInteractorLogic.cpp.
References GetCurrentRotation(), cloudViewer::visualization::rendering::Camera::GetLeftVector(), cloudViewer::visualization::rendering::Camera::GetUpVector(), cloudViewer::visualization::rendering::MatrixInteractorLogic::RotateWorld(), cloudViewer::visualization::rendering::Scene::SetIndirectLightRotation(), and UpdateMouseDragUI().
RotateZ()
void cloudViewer::visualization::rendering::IBLRotationInteractorLogic::RotateZ (int dx, int dy) override virtual
Rotates about the forward axis of the matrix.
Reimplemented from cloudViewer::visualization::rendering::MatrixInteractorLogic.
Definition at line 29 of file IBLRotationInteractorLogic.cpp.
References GetCurrentRotation(), cloudViewer::visualization::rendering::Camera::GetForwardVector(), cloudViewer::visualization::rendering::MatrixInteractorLogic::RotateWorld(), cloudViewer::visualization::rendering::Scene::SetIndirectLightRotation(), and UpdateMouseDragUI().
StartMouseDrag()
void cloudViewer::visualization::rendering::IBLRotationInteractorLogic::StartMouseDrag ()
Definition at line 36 of file IBLRotationInteractorLogic.cpp.
References cloudViewer::visualization::rendering::Scene::GetIndirectLightRotation(), cloudViewer::visualization::rendering::Scene::GetSkyboxVisible(), cloudViewer::visualization::rendering::MatrixInteractorLogic::SetMouseDownInfo(), cloudViewer::visualization::rendering::Scene::ShowSkybox(), and UpdateMouseDragUI().
UpdateMouseDragUI()
void cloudViewer::visualization::rendering::IBLRotationInteractorLogic::UpdateMouseDragUI ()
Definition at line 51 of file IBLRotationInteractorLogic.cpp.
Referenced by Rotate(), RotateZ(), and StartMouseDrag().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/IBLRotationInteractorLogic.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/IBLRotationInteractorLogic.cpp