ACloudViewer: PclUtils::ImageVis Class Reference
PclUtils::ImageVis Class Reference
#include <ImageVis.h>
Public Member Functions
ImageVis (const std::string &viewerName, bool autoInit=false)
Default constructor.
void setupInteractor (vtkSmartPointer< vtkRenderWindowInteractor > interactor, vtkSmartPointer< vtkRenderWindow > win)
Set up our unique PCL interactor style for a given vtkRenderWindowInteractor object attached to a given vtkRenderWindow.
void setRenderWindow (vtkSmartPointer< vtkRenderWindow > win)
vtkSmartPointer< vtkRenderWindow > getRenderWindow ()
vtkSmartPointer< vtkRenderWindowInteractor > getRenderWindowInteractor ()
void setRenderWindowInteractor (vtkSmartPointer< vtkRenderWindowInteractor > interactor)
vtkSmartPointer< vtkRenderer > getRender ()
The renderer.
void setRender (vtkSmartPointer< vtkRenderer > render)
bool contains (const std::string &id) const
Check if the image with the given id was already added to this visualizer.
Layer * getLayer (const std::string &id)
void changeOpacity (double opacity, const std::string &viewID)
void hideShowActors (bool visibility, const std::string &viewID)
void removeLayer (const std::string &layer_id)
Remove a layer from the viewer.
LayerMap::iterator createLayer (const std::string &layer_id, int x, int y, int width, int height, double opacity=0.5, bool fill_box=true)
Add a new 2D rendering layer to the viewer.
void addRGBImage (const QImage &qimage, unsigned x, unsigned y, const std::string &layer_id, double opacity=1.0)
void addQImage (const QImage &qimage, const std::string &layer_id="image", double opacity=1.0)
Add a QImage directly (ParaView-style, using vtkQImageToImageSource).
bool addText (unsigned int x, unsigned int y, const std::string &text_string, double r, double g, double b, const std::string &layer_id="line", double opacity=1.0, int fontSize=10, bool bold=false)
void enable2Dviewer (bool state)
std::string pickItem (int x, int y)
Public Member Functions inherited from ecvGenericVisualizer2D
ecvGenericVisualizer2D ()=default
Default constructor.
virtual ~ecvGenericVisualizer2D ()=default
Destructor.
Public Member Functions inherited from ecvGenericVisualizer
ecvGenericVisualizer ()=default
Default constructor.
virtual ~ecvGenericVisualizer ()=default
Destructor.
Public Member Functions inherited from pcl::visualization::ImageViewer
ImageViewer (const std::string &window_title="")
Constructor.
virtual ~ImageViewer ()
Destructor.
void setInteractorStyle (vtkInteractorObserver *style)
Set up the interactor style. By default the interactor style is set to vtkInteractorStyleImage you can use this to set it to another type.
void showMonoImage (const unsigned char *data, unsigned width, unsigned height, const std::string &layer_id="mono_image", double opacity=1.0)
Show a monochrome 2D image on screen.
void addMonoImage (const unsigned char *data, unsigned width, unsigned height, const std::string &layer_id="mono_image", double opacity=1.0)
Add a monochrome 2D image layer, but do not render it (use spin/spinOnce to update).
void showMonoImage (const pcl::PointCloud< pcl::Intensity >::ConstPtr &cloud, const std::string &layer_id="mono_image", double opacity=1.0)
Show a monochrome 2D image on screen.
void addMonoImage (const pcl::PointCloud< pcl::Intensity >::ConstPtr &cloud, const std::string &layer_id="mono_image", double opacity=1.0)
Add a monochrome 2D image layer, but do not render it (use spin/spinOnce to update).
void showMonoImage (const pcl::PointCloud< pcl::Intensity > &cloud, const std::string &layer_id="mono_image", double opacity=1.0)
Show a monochrome 2D image on screen.
void addMonoImage (const pcl::PointCloud< pcl::Intensity > &cloud, const std::string &layer_id="mono_image", double opacity=1.0)
Add a monochrome 2D image layer, but do not render it (use spin/spinOnce to update).
void showMonoImage (const pcl::PointCloud< pcl::Intensity8u >::ConstPtr &cloud, const std::string &layer_id="mono_image", double opacity=1.0)
Show a monochrome 2D image on screen.
void addMonoImage (const pcl::PointCloud< pcl::Intensity8u >::ConstPtr &cloud, const std::string &layer_id="mono_image", double opacity=1.0)
Add a monochrome 2D image layer, but do not render it (use spin/spinOnce to update).
void showMonoImage (const pcl::PointCloud< pcl::Intensity8u > &cloud, const std::string &layer_id="mono_image", double opacity=1.0)
Show a monochrome 2D image on screen.
void addMonoImage (const pcl::PointCloud< pcl::Intensity8u > &cloud, const std::string &layer_id="mono_image", double opacity=1.0)
Add a monochrome 2D image layer, but do not render it (use spin/spinOnce to update).
void showRGBImage (const unsigned char *data, unsigned width, unsigned height, const std::string &layer_id="rgb_image", double opacity=1.0)
Show a 2D RGB image on screen.
void addRGBImage (const unsigned char *data, unsigned width, unsigned height, const std::string &layer_id="rgb_image", double opacity=1.0, bool autoresize=true)
Add an RGB 2D image layer, but do not render it (use spin/spinOnce to update).
template<typename T >
void showRGBImage (const typename pcl::PointCloud< T >::ConstPtr &cloud, const std::string &layer_id="rgb_image", double opacity=1.0)
Show a 2D image on screen, obtained from the RGB channel of a point cloud.
template<typename T >
void addRGBImage (const typename pcl::PointCloud< T >::ConstPtr &cloud, const std::string &layer_id="rgb_image", double opacity=1.0)
Add an RGB 2D image layer, but do not render it (use spin/spinOnce to update).
template<typename T >
void showRGBImage (const pcl::PointCloud< T > &cloud, const std::string &layer_id="rgb_image", double opacity=1.0)
Show a 2D image on screen, obtained from the RGB channel of a point cloud.
template<typename T >
void addRGBImage (const pcl::PointCloud< T > &cloud, const std::string &layer_id="rgb_image", double opacity=1.0)
Add an RGB 2D image layer, but do not render it (use spin/spinOnce to update).
void showFloatImage (const float *data, unsigned int width, unsigned int height, float min_value=std::numeric_limits< float >::min(), float max_value=std::numeric_limits< float >::max(), bool grayscale=false, const std::string &layer_id="float_image", double opacity=1.0)
Show a 2D image (float) on screen.
void addFloatImage (const float *data, unsigned int width, unsigned int height, float min_value=std::numeric_limits< float >::min(), float max_value=std::numeric_limits< float >::max(), bool grayscale=false, const std::string &layer_id="float_image", double opacity=1.0)
Add a float 2D image layer, but do not render it (use spin/spinOnce to update).
void showShortImage (const unsigned short *short_image, unsigned int width, unsigned int height, unsigned short min_value=std::numeric_limits< unsigned short >::min(), unsigned short max_value=std::numeric_limits< unsigned short >::max(), bool grayscale=false, const std::string &layer_id="short_image", double opacity=1.0)
Show a 2D image (unsigned short) on screen.
void addShortImage (const unsigned short *short_image, unsigned int width, unsigned int height, unsigned short min_value=std::numeric_limits< unsigned short >::min(), unsigned short max_value=std::numeric_limits< unsigned short >::max(), bool grayscale=false, const std::string &layer_id="short_image", double opacity=1.0)
Add a short 2D image layer, but do not render it (use spin/spinOnce to update).
void showAngleImage (const float *data, unsigned width, unsigned height, const std::string &layer_id="angle_image", double opacity=1.0)
Show a 2D image on screen representing angle data.
void addAngleImage (const float *data, unsigned width, unsigned height, const std::string &layer_id="angle_image", double opacity=1.0)
Add an angle 2D image layer, but do not render it (use spin/spinOnce to update).
void showHalfAngleImage (const float *data, unsigned width, unsigned height, const std::string &layer_id="half_angle_image", double opacity=1.0)
Show a 2D image on screen representing half angle data.
void addHalfAngleImage (const float *data, unsigned width, unsigned height, const std::string &layer_id="half_angle_image", double opacity=1.0)
Add a half angle 2D image layer, but do not render it (use spin/spinOnce to update).
void markPoint (std::size_t u, std::size_t v, Vector3ub fg_color, Vector3ub bg_color=red_color, double radius=3.0, const std::string &layer_id="points", double opacity=1.0)
Sets the pixel at coordinates(u,v) to color while setting the neighborhood to another.
void markPoints (const std::vector< int > &uv, Vector3ub fg_color, Vector3ub bg_color=red_color, double size=3.0, const std::string &layer_id="markers", double opacity=1.0)
Sets the pixel at coordinates(u,v) to color while setting the neighborhood to another.
void markPoints (const std::vector< float > &uv, Vector3ub fg_color, Vector3ub bg_color=red_color, double size=3.0, const std::string &layer_id="markers", double opacity=1.0)
Sets the pixel at coordinates(u,v) to color while setting the neighborhood to another (float coordinates version).
void setWindowTitle (const std::string &name)
Set the window title name.
void spin ()
Spin method. Calls the interactor and runs an internal loop.
void spinOnce (int time=1, bool force_redraw=true)
Spin once method. Calls the interactor and updates the screen once.
boost::signals2::connection registerKeyboardCallback (void(*callback)(const pcl::visualization::KeyboardEvent &, void *), void *cookie=nullptr)
Register a callback function for keyboard events.
template<typename T >
boost::signals2::connection registerKeyboardCallback (void(T::*callback)(const pcl::visualization::KeyboardEvent &, void *), T &instance, void *cookie=nullptr)
Register a callback function for keyboard events.
boost::signals2::connection registerKeyboardCallback (std::function< void(const pcl::visualization::KeyboardEvent &)> cb)
Register a callback std::function for keyboard events.
boost::signals2::connection registerMouseCallback (void(*callback)(const pcl::visualization::MouseEvent &, void *), void *cookie=nullptr)
Register a callback std::function for mouse events.
template<typename T >
boost::signals2::connection registerMouseCallback (void(T::*callback)(const pcl::visualization::MouseEvent &, void *), T &instance, void *cookie=nullptr)
Register a callback function for mouse events.
boost::signals2::connection registerMouseCallback (std::function< void(const pcl::visualization::MouseEvent &)> cb)
Register a callback function for mouse events.
void setPosition (int x, int y)
Set the position in screen coordinates.
void setSize (int xw, int yw)
Set the window size in screen coordinates.
int * getSize ()
Return the window size in pixels.
bool wasStopped () const
Returns true when the user tried to close the window.
void close ()
Stop the interaction and close the visualizaton window.
bool addCircle (unsigned int x, unsigned int y, double radius, const std::string &layer_id="circles", double opacity=1.0)
Add a circle shape from a point and a radius.
bool addCircle (unsigned int x, unsigned int y, double radius, double r, double g, double b, const std::string &layer_id="circles", double opacity=1.0)
Add a circle shape from a point and a radius.
bool addRectangle (const pcl::PointXY &min_pt, const pcl::PointXY &max_pt, const std::string &layer_id="rectangles", double opacity=1.0)
Add a 2D box and color its edges with a given color.
bool addRectangle (const pcl::PointXY &min_pt, const pcl::PointXY &max_pt, double r, double g, double b, const std::string &layer_id="rectangles", double opacity=1.0)
Add a 2D box and color its edges with a given color.
bool addRectangle (unsigned int x_min, unsigned int x_max, unsigned int y_min, unsigned int y_max, const std::string &layer_id="rectangles", double opacity=1.0)
Add a 2D box and color its edges with a given color.
bool addRectangle (unsigned int x_min, unsigned int x_max, unsigned int y_min, unsigned int y_max, double r, double g, double b, const std::string &layer_id="rectangles", double opacity=1.0)
Add a 2D box and color its edges with a given color.
template<typename T >
bool addRectangle (const typename pcl::PointCloud< T >::ConstPtr &image, const T &min_pt, const T &max_pt, const std::string &layer_id="rectangles", double opacity=1.0)
Add a 2D box and color its edges with a given color.
template<typename T >
bool addRectangle (const typename pcl::PointCloud< T >::ConstPtr &image, const T &min_pt, const T &max_pt, double r, double g, double b, const std::string &layer_id="rectangles", double opacity=1.0)
Add a 2D box and color its edges with a given color.
template<typename T >
bool addRectangle (const typename pcl::PointCloud< T >::ConstPtr &image, const pcl::PointCloud< T > &mask, double r, double g, double b, const std::string &layer_id="rectangles", double opacity=1.0)
Add a 2D box that contains a given image mask and color its edges.
template<typename T >
bool addRectangle (const typename pcl::PointCloud< T >::ConstPtr &image, const pcl::PointCloud< T > &mask, const std::string &layer_id="image_mask", double opacity=1.0)
Add a 2D box that contains a given image mask and color its edges in red.
bool addFilledRectangle (unsigned int x_min, unsigned int x_max, unsigned int y_min, unsigned int y_max, const std::string &layer_id="boxes", double opacity=0.5)
Add a 2D box and fill it in with a given color.
bool addFilledRectangle (unsigned int x_min, unsigned int x_max, unsigned int y_min, unsigned int y_max, double r, double g, double b, const std::string &layer_id="boxes", double opacity=0.5)
Add a 2D box and fill it in with a given color.
bool addLine (unsigned int x_min, unsigned int y_min, unsigned int x_max, unsigned int y_max, double r, double g, double b, const std::string &layer_id="line", double opacity=1.0)
Add a 2D line with a given color.
bool addLine (unsigned int x_min, unsigned int y_min, unsigned int x_max, unsigned int y_max, const std::string &layer_id="line", double opacity=1.0)
Add a 2D line with a given color.
bool addText (unsigned int x, unsigned int y, const std::string &text, double r, double g, double b, const std::string &layer_id="line", double opacity=1.0)
Add a 2D text with a given color.
bool addText (unsigned int x, unsigned int y, const std::string &text, const std::string &layer_id="line", double opacity=1.0)
Add a 2D text with a given color.
template<typename T >
bool addMask (const typename pcl::PointCloud< T >::ConstPtr &image, const pcl::PointCloud< T > &mask, double r, double g, double b, const std::string &layer_id="image_mask", double opacity=0.5)
Add a generic 2D mask to an image.
template<typename T >
bool addMask (const typename pcl::PointCloud< T >::ConstPtr &image, const pcl::PointCloud< T > &mask, const std::string &layer_id="image_mask", double opacity=0.5)
Add a generic 2D mask to an image (colored in red)
template<typename T >
bool addPlanarPolygon (const typename pcl::PointCloud< T >::ConstPtr &image, const pcl::PlanarPolygon< T > &polygon, double r, double g, double b, const std::string &layer_id="planar_polygon", double opacity=1.0)
Add a generic 2D planar polygon to an image.
template<typename T >
bool addPlanarPolygon (const typename pcl::PointCloud< T >::ConstPtr &image, const pcl::PlanarPolygon< T > &polygon, const std::string &layer_id="planar_polygon", double opacity=1.0)
Add a generic 2D planar polygon to an image.
bool addLayer (const std::string &layer_id, int width, int height, double opacity=0.5)
Add a new 2D rendering layer to the viewer.
void removeLayer (const std::string &layer_id)
Remove a 2D layer given by its ID.
template<typename PointT >
bool showCorrespondences (const pcl::PointCloud< PointT > &source_img, const pcl::PointCloud< PointT > &target_img, const pcl::Correspondences &correspondences, int nth=1, const std::string &layer_id="correspondences")
Add the specified correspondences to the display.
Additional Inherited Members
Public Types inherited from pcl::visualization::ImageViewer
using Ptr = shared_ptr< ImageViewer >
using ConstPtr = shared_ptr< const ImageViewer >
Protected Types inherited from pcl::visualization::ImageViewer
using LayerMap = std::vector< Layer >
Protected Member Functions inherited from pcl::visualization::ImageViewer
void render ()
Trigger a render call.
void convertIntensityCloudToUChar (const pcl::PointCloud< pcl::Intensity > &cloud, boost::shared_array< unsigned char > data)
Convert the Intensity information in a PointCloud<Intensity> to an unsigned char array.
void convertIntensityCloud8uToUChar (const pcl::PointCloud< pcl::Intensity8u > &cloud, boost::shared_array< unsigned char > data)
Convert the Intensity8u information in a PointCloud<Intensity8u> to an unsigned char array.
template<typename T >
void convertRGBCloudToUChar (const pcl::PointCloud< T > &cloud, boost::shared_array< unsigned char > &data)
Convert the RGB information in a PointCloud<T> to an unsigned char array.
void resetStoppedFlag ()
Set the stopped flag back to false.
void emitMouseEvent (unsigned long event_id)
Fire up a mouse event with a specified event ID.
void emitKeyboardEvent (unsigned long event_id)
Fire up a keyboard event with a specified event ID.
LayerMap::iterator createLayer (const std::string &layer_id, int width, int height, double opacity=0.5, bool fill_box=true)
Add a new 2D rendering layer to the viewer.
Static Protected Member Functions inherited from pcl::visualization::ImageViewer
static void MouseCallback (vtkObject *, unsigned long eid, void *clientdata, void *calldata)
static void KeyboardCallback (vtkObject *, unsigned long eid, void *clientdata, void *calldata)
Protected Attributes inherited from pcl::visualization::ImageViewer
boost::signals2::signal< void(const pcl::visualization::MouseEvent &)> mouse_signal_
boost::signals2::signal< void(const pcl::visualization::KeyboardEvent &)> keyboard_signal_
vtkSmartPointer< vtkRenderWindowInteractor > interactor_
vtkSmartPointer< vtkCallbackCommand > mouse_command_
vtkSmartPointer< vtkCallbackCommand > keyboard_command_
vtkSmartPointer< ExitMainLoopTimerCallback > exit_main_loop_timer_callback_
Callback object enabling us to leave the main loop, when a timer fires.
vtkSmartPointer< ExitCallback > exit_callback_
vtkSmartPointer< vtkImageViewer > image_viewer_
The ImageViewer widget.
vtkSmartPointer< vtkRenderWindow > win_
The render window.
vtkSmartPointer< vtkRenderer > ren_
The renderer.
vtkSmartPointer< vtkImageSlice > slice_
Global prop. This is the actual "actor".
vtkSmartPointer< ImageViewerInteractorStyle > interactor_style_
The interactor style.
boost::shared_array< unsigned char > data_
The data array representing the image. Used internally.
std::size_t data_size_
The data array (representing the image) size. Used internally.
bool stopped_
Set to false if the interaction loop is running.
int timer_id_
Global timer ID. Used in destructor only.
LayerMap layer_map_
Internal list with different 2D layers shapes.
vtkSmartPointer< vtkImageFlip > algo_
Image reslice, used for flipping the image.
std::vector< unsigned char * > image_data_
Internal data array. Used everytime add***Image is called. Cleared, everytime the render loop is executed.
Detailed Description
Definition at line 38 of file ImageVis.h.
Constructor & Destructor Documentation
ImageVis()
PclUtils::ImageVis::ImageVis (const std::string & viewerName, bool autoInit = false)
Default constructor.
Constructor is protected to avoid using this object as a non static class.
Definition at line 95 of file ImageVis.cpp.
Member Function Documentation
addQImage()
void PclUtils::ImageVis::addQImage (const QImage & qimage, const std::string & layer_id = "image", double opacity = 1.0)
Add a QImage directly (ParaView-style, using vtkQImageToImageSource).
Parameters
[in] qimage the QImage to add
[in] layer_id the name of the layer
[in] opacity the opacity of the layer (default: 1.0)
Definition at line 522 of file ImageVis.cpp.
References addRGBImage().
addRGBImage()
void PclUtils::ImageVis::addRGBImage (const QImage & qimage, unsigned x, unsigned y, const std::string & layer_id, double opacity = 1.0)
Definition at line 415 of file ImageVis.cpp.
References height, pcl::visualization::ImageViewer::ren_, pcl::visualization::ImageViewer::slice_, CVLog::Warning(), width, pcl::visualization::ImageViewer::win_, x, and y.
Referenced by addQImage().
addText()
bool PclUtils::ImageVis::addText (unsigned int x, unsigned int y, const std::string & text_string, double r, double g, double b, const std::string & layer_id = "line", double opacity = 1.0, int fontSize = 10, bool bold = false)
Definition at line 528 of file ImageVis.cpp.
References createLayer(), pcl::visualization::ImageViewer::getSize(), pcl::visualization::ImageViewer::interactor_style_, pcl::visualization::ImageViewer::layer_map_, pcl::visualization::ImageViewer::ren_, x, and y.
changeOpacity()
void PclUtils::ImageVis::changeOpacity (double opacity, const std::string & viewID)
Definition at line 301 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::Layer::actor, getLayer(), CVLog::PrintVerbose(), and pcl::visualization::ImageViewer::win_.
contains()
bool PclUtils::ImageVis::contains (const std::string & id) const
Check if the image with the given id was already added to this visualizer.
Parameters
[in] id the id of the image to check
Returns
true if a image with the specified id was found
Definition at line 246 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::layer_map_.
createLayer()
pcl::visualization::ImageViewer::LayerMap::iterator PclUtils::ImageVis::createLayer (const std::string & layer_id, int x, int y, int width, int height, double opacity = 0.5, bool fill_box = true)
Add a new 2D rendering layer to the viewer.
Parameters
[in] layer_id the name of the layer
[in] width the width of the layer
[in] height the height of the layer
[in] opacity the opacity of the layer: 0 for invisible, 1 for opaque. (default: 0.5)
[in] fill_box set to true to fill in the image with one black box before starting
Definition at line 381 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::Layer::actor, height, pcl::visualization::ImageViewer::image_viewer_, pcl::visualization::ImageViewer::layer_map_, pcl::visualization::ImageViewer::Layer::layer_name, pcl::visualization::ImageViewer::ren_, width, x, and y.
Referenced by addText().
enable2Dviewer()
void PclUtils::ImageVis::enable2Dviewer (bool state)
Definition at line 128 of file ImageVis.cpp.
References getRenderWindow(), getRenderWindowInteractor(), pcl::visualization::ImageViewer::registerMouseCallback(), setRenderWindowInteractor(), setupInteractor(), vtkRenderWindowInteractorFixNew(), and CVLog::Warning().
getLayer()
pcl::visualization::ImageViewer::Layer * PclUtils::ImageVis::getLayer (const std::string & id)
Definition at line 265 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::layer_map_.
Referenced by changeOpacity(), and hideShowActors().
getRender()
vtkSmartPointer< vtkRenderer > PclUtils::ImageVis::getRender ()
The renderer.
Definition at line 239 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::ren_.
getRenderWindow()
vtkSmartPointer< vtkRenderWindow > PclUtils::ImageVis::getRenderWindow ()
Definition at line 112 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::win_.
Referenced by enable2Dviewer(), and setupInteractor().
getRenderWindowInteractor()
vtkSmartPointer< vtkRenderWindowInteractor > PclUtils::ImageVis::getRenderWindowInteractor ()
Definition at line 208 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::interactor_.
Referenced by enable2Dviewer().
hideShowActors()
void PclUtils::ImageVis::hideShowActors (bool visibility, const std::string & viewID)
Definition at line 275 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::Layer::actor, and getLayer().
pickItem()
std::string PclUtils::ImageVis::pickItem (int x, int y)
Definition at line 170 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::Layer::actor, context, pcl::visualization::ImageViewer::layer_map_, pcl::visualization::ImageViewer::Layer::layer_name, x, and y.
removeLayer()
void PclUtils::ImageVis::removeLayer (const std::string & layer_id)
Remove a layer from the viewer.
Parameters
[in] layer_id the name of the layer to remove
Definition at line 335 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::interactor_, pcl::visualization::ImageViewer::removeLayer(), and pcl::visualization::ImageViewer::ren_.
setRender()
void PclUtils::ImageVis::setRender (vtkSmartPointer< vtkRenderer > render)
Definition at line 241 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::ren_, pcl::visualization::ImageViewer::render(), and pcl::visualization::ImageViewer::slice_.
setRenderWindow()
void PclUtils::ImageVis::setRenderWindow (vtkSmartPointer< vtkRenderWindow > win)
Definition at line 195 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::win_.
Referenced by setupInteractor().
setRenderWindowInteractor()
void PclUtils::ImageVis::setRenderWindowInteractor (vtkSmartPointer< vtkRenderWindowInteractor > interactor)
Definition at line 212 of file ImageVis.cpp.
References pcl::visualization::ImageViewer::exit_callback_, pcl::visualization::ImageViewer::exit_main_loop_timer_callback_, pcl::visualization::ImageViewer::interactor_, pcl::visualization::ImageViewer::resetStoppedFlag(), and pcl::visualization::ImageViewer::timer_id_.
Referenced by enable2Dviewer(), and setupInteractor().
setupInteractor()
void PclUtils::ImageVis::setupInteractor (vtkSmartPointer< vtkRenderWindowInteractor > interactor, vtkSmartPointer< vtkRenderWindow > win)
Set up our unique PCL interactor style for a given vtkRenderWindowInteractor object attached to a given vtkRenderWindow.
Parameters
[in,out] interactor the vtkRenderWindowInteractor object to set up
[in,out] win a vtkRenderWindow object that the interactor is attached to
Definition at line 116 of file ImageVis.cpp.
References getRenderWindow(), setRenderWindow(), and setRenderWindowInteractor().
Referenced by enable2Dviewer().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/PclUtils/ImageVis.h
/root/ACloudViewer/libs/PCLEngine/PclUtils/ImageVis.cpp