ACloudViewer: vtkPVTrackballRotate Class Reference
vtkPVTrackballRotate Class Reference
#include <vtkPVTrackballRotate.h>
Public Member Functions
vtkTypeMacro (vtkPVTrackballRotate, vtkCameraManipulator)
void PrintSelf (ostream &os, vtkIndent indent) override
void OnMouseMove (int x, int y, vtkRenderer *ren, vtkRenderWindowInteractor *rwi) override
void OnButtonDown (int x, int y, vtkRenderer *ren, vtkRenderWindowInteractor *rwi) override
void OnButtonUp (int x, int y, vtkRenderer *ren, vtkRenderWindowInteractor *rwi) override
void OnKeyUp (vtkRenderWindowInteractor *iren) override
void OnKeyDown (vtkRenderWindowInteractor *iren) override
vtkGetMacro (KeyCode, char)
Public Member Functions inherited from vtkCameraManipulator
vtkTypeMacro (vtkCameraManipulator, vtkObject)
void PrintSelf (ostream &os, vtkIndent indent) override
virtual void StartInteraction ()
virtual void EndInteraction ()
vtkSetMacro (Button, int)
vtkGetMacro (Button, int)
vtkSetMacro (Shift, int)
vtkGetMacro (Shift, int)
vtkBooleanMacro (Shift, int)
vtkSetMacro (Control, int)
vtkGetMacro (Control, int)
vtkBooleanMacro (Control, int)
vtkSetVector3Macro (Center, double)
vtkGetVector3Macro (Center, double)
vtkSetMacro (RotationFactor, double)
vtkGetMacro (RotationFactor, double)
vtkSetStringMacro (ManipulatorName)
vtkGetStringMacro (ManipulatorName)
void SetGUIHelper (vtkCameraManipulatorGUIHelper *)
vtkGetObjectMacro (GUIHelper, vtkCameraManipulatorGUIHelper)
Static Public Member Functions
static vtkPVTrackballRotate * New ()
Static Public Member Functions inherited from vtkCameraManipulator
static vtkCameraManipulator * New ()
Protected Member Functions
vtkPVTrackballRotate ()
~vtkPVTrackballRotate () override
vtkPVTrackballRotate (const vtkPVTrackballRotate &)=delete
void operator= (const vtkPVTrackballRotate &)=delete
Protected Member Functions inherited from vtkCameraManipulator
vtkCameraManipulator ()
~vtkCameraManipulator () override
void ComputeDisplayCenter (vtkRenderer *ren)
Protected Attributes
char KeyCode
Protected Attributes inherited from vtkCameraManipulator
char * ManipulatorName
int Button
int Shift
int Control
double Center [3]
double RotationFactor
double DisplayCenter [2]
vtkCameraManipulatorGUIHelper * GUIHelper
Detailed Description
Definition at line 13 of file vtkPVTrackballRotate.h.
Constructor & Destructor Documentation
vtkPVTrackballRotate() [1/2]
vtkPVTrackballRotate::vtkPVTrackballRotate () protected
Definition at line 30 of file vtkPVTrackballRotate.cxx.
References KeyCode.
~vtkPVTrackballRotate()
vtkPVTrackballRotate::~vtkPVTrackballRotate () override protected
Definition at line 36 of file vtkPVTrackballRotate.cxx.
vtkPVTrackballRotate() [2/2]
vtkPVTrackballRotate::vtkPVTrackballRotate (const vtkPVTrackballRotate &) protected delete
Member Function Documentation
New()
static vtkPVTrackballRotate* vtkPVTrackballRotate::New () static
Referenced by vtkPVTrackballMultiRotate::vtkPVTrackballMultiRotate().
OnButtonDown()
void vtkPVTrackballRotate::OnButtonDown (int x, int y, vtkRenderer * ren, vtkRenderWindowInteractor * rwi) override virtual
Reimplemented from vtkCameraManipulator.
Definition at line 41 of file vtkPVTrackballRotate.cxx.
References vtkCameraManipulator::ComputeDisplayCenter().
OnButtonUp()
void vtkPVTrackballRotate::OnButtonUp (int x, int y, vtkRenderer * ren, vtkRenderWindowInteractor * rwi) override virtual
Reimplemented from vtkCameraManipulator.
Definition at line 47 of file vtkPVTrackballRotate.cxx.
OnKeyDown()
void vtkPVTrackballRotate::OnKeyDown (vtkRenderWindowInteractor * iren) override virtual
Reimplemented from vtkCameraManipulator.
Definition at line 152 of file vtkPVTrackballRotate.cxx.
References KeyCode.
OnKeyUp()
void vtkPVTrackballRotate::OnKeyUp (vtkRenderWindowInteractor * iren) override virtual
These methods are called on all registered manipulators, not just the active one. Hence, these should just be used to record state and not perform any interactions. Overridden to capture if the x,y,z key is pressed.
Reimplemented from vtkCameraManipulator.
Definition at line 143 of file vtkPVTrackballRotate.cxx.
References KeyCode.
OnMouseMove()
void vtkPVTrackballRotate::OnMouseMove (int x, int y, vtkRenderer * ren, vtkRenderWindowInteractor * rwi) override virtual
Event bindings controlling the effects of pressing mouse buttons or moving the mouse.
Reimplemented from vtkCameraManipulator.
Definition at line 52 of file vtkPVTrackballRotate.cxx.
References vtkCameraManipulator::Center, cloudViewer::ml::contrib::Cross(), NULL, vtkCameraManipulator::RotationFactor, size, x, and y.
operator=()
void vtkPVTrackballRotate::operator= (const vtkPVTrackballRotate &) protected delete
PrintSelf()
void vtkPVTrackballRotate::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 161 of file vtkPVTrackballRotate.cxx.
References vtkCameraManipulator::Center, and QtCompat::endl().
vtkGetMacro()
vtkPVTrackballRotate::vtkGetMacro (KeyCode , char)
Returns the currently pressed key code.
vtkTypeMacro()
vtkPVTrackballRotate::vtkTypeMacro (vtkPVTrackballRotate , vtkCameraManipulator)
Member Data Documentation
KeyCode
char vtkPVTrackballRotate::KeyCode protected
Definition at line 58 of file vtkPVTrackballRotate.h.
Referenced by OnKeyDown(), OnKeyUp(), and vtkPVTrackballRotate().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/InteractionStyle/vtkPVTrackballRotate.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/InteractionStyle/vtkPVTrackballRotate.cxx