ACloudViewer: ccThicknessTool Class Reference
ccThicknessTool Class Reference
#include <ccThicknessTool.h>
Public Member Functions
ccThicknessTool ()
virtual ~ccThicknessTool ()
virtual void toolActivated () override
virtual void toolDisactivated () override
virtual void onNewSelection (const ccHObject::Container &selectedEntities) override
virtual void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccHObject *pickedObject, const CCVector3 &P) override
void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccPointCloud *cloud, const CCVector3 &P) override
void accept () override
void cancel () override
Public Member Functions inherited from ccTool
virtual ~ccTool ()
void initializeTool (ecvMainAppInterface *app)
virtual bool canUndo ()
virtual void undo ()
Static Public Attributes
static ecvColor::Rgb ACTIVE_COLOR = ecvColor::red
static bool TWO_POINT_MODE = false
Protected Attributes
ccPlane * m_referencePlane = nullptr
CCVector3 * m_startPoint = nullptr
std::vector< int > m_hiddenObjects
int m_graphic_id
Protected Attributes inherited from ccTool
ecvMainAppInterface * m_app
QWidget * m_window
Additional Inherited Members
Protected Member Functions inherited from ccTool
ccTool ()
Detailed Description
Definition at line 20 of file ccThicknessTool.h.
Constructor & Destructor Documentation
ccThicknessTool()
ccThicknessTool::ccThicknessTool ()
Definition at line 16 of file ccThicknessTool.cpp.
~ccThicknessTool()
ccThicknessTool::~ccThicknessTool () virtual
Definition at line 18 of file ccThicknessTool.cpp.
Member Function Documentation
accept()
void ccThicknessTool::accept () override virtual
Reimplemented from ccTool.
Definition at line 270 of file ccThicknessTool.cpp.
References toolActivated(), and toolDisactivated().
cancel()
void ccThicknessTool::cancel () override virtual
Reimplemented from ccTool.
Definition at line 279 of file ccThicknessTool.cpp.
References toolDisactivated().
onNewSelection()
void ccThicknessTool::onNewSelection (const ccHObject::Container & selectedEntities) override virtual
Reimplemented from ccTool.
Definition at line 21 of file ccThicknessTool.cpp.
References ACTIVE_COLOR, ecvMainAppInterface::dbRootObject(), ecvDisplayTools::DisplayNewMessage(), ccDrawableObject::enableTempColor(), ccHObject::find(), ccHObject::isDisplayed(), ecvDisplayTools::LOWER_LEFT_MESSAGE, ccTool::m_app, m_hiddenObjects, m_referencePlane, ecvDisplayTools::RedrawDisplay(), ccDrawableObject::setTempColor(), and ccDrawableObject::setVisible().
Referenced by pointPicked().
pointPicked() [1/2]
void ccThicknessTool::pointPicked (ccHObject * insertPoint, unsigned itemIdx, ccHObject * pickedObject, const CCVector3 & P) override virtual
Reimplemented from ccTool.
Definition at line 69 of file ccThicknessTool.cpp.
References ecvMainAppInterface::getSelectedEntities(), ccObject::isA(), ccTool::m_app, onNewSelection(), CV_TYPES::PLANE, and ecvMainAppInterface::setSelectedInDB().
pointPicked() [2/2]
void ccThicknessTool::pointPicked (ccHObject * insertPoint, unsigned itemIdx, ccPointCloud * cloud, const CCVector3 & P) override virtual
Reimplemented from ccTool.
Definition at line 85 of file ccThicknessTool.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), ecvMainAppInterface::addToDB(), ecvMainAppInterface::dbRootObject(), ecvDisplayTools::DisplayNewMessage(), ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, ccHObject::find(), ccObject::getUniqueID(), ecvDisplayTools::LOWER_LEFT_MESSAGE, ccTool::m_app, m_graphic_id, m_referencePlane, m_startPoint, ecvMainAppInterface::removeFromDB(), ccObject::setName(), ccDrawableObject::showNameIn3D(), and TWO_POINT_MODE.
toolActivated()
void ccThicknessTool::toolActivated () override virtual
Reimplemented from ccTool.
Definition at line 204 of file ccThicknessTool.cpp.
References ecvMainAppInterface::dbRootObject(), ecvDisplayTools::DisplayNewMessage(), ecvDisplayTools::LOWER_LEFT_MESSAGE, ccTool::m_app, and ecvDisplayTools::RedrawDisplay().
Referenced by accept().
toolDisactivated()
void ccThicknessTool::toolDisactivated () override virtual
Reimplemented from ccTool.
Definition at line 218 of file ccThicknessTool.cpp.
References ecvMainAppInterface::dbRootObject(), ccDrawableObject::enableTempColor(), ccHObject::find(), ccTool::m_app, m_hiddenObjects, m_referencePlane, m_startPoint, ecvDisplayTools::RedrawDisplay(), and ccDrawableObject::setVisible().
Referenced by accept(), and cancel().
Member Data Documentation
ACTIVE_COLOR
ecvColor::Rgb ccThicknessTool::ACTIVE_COLOR = ecvColor::red static
Definition at line 77 of file ccThicknessTool.h.
Referenced by onNewSelection().
m_graphic_id
int ccThicknessTool::m_graphic_id protected
Initial value:
=
            -1
Definition at line 61 of file ccThicknessTool.h.
Referenced by pointPicked().
m_hiddenObjects
std::vector<int> ccThicknessTool::m_hiddenObjects protected
Definition at line 59 of file ccThicknessTool.h.
Referenced by onNewSelection(), and toolDisactivated().
m_referencePlane
ccPlane* ccThicknessTool::m_referencePlane = nullptr protected
Definition at line 56 of file ccThicknessTool.h.
Referenced by onNewSelection(), pointPicked(), and toolDisactivated().
m_startPoint
CCVector3* ccThicknessTool::m_startPoint = nullptr protected
Definition at line 57 of file ccThicknessTool.h.
Referenced by pointPicked(), and toolDisactivated().
TWO_POINT_MODE
bool ccThicknessTool::TWO_POINT_MODE = false static
Definition at line 78 of file ccThicknessTool.h.
Referenced by pointPicked(), ccCompass::setThickness(), and ccCompass::setThickness2().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCompass/include/ccThicknessTool.h
/root/ACloudViewer/plugins/core/Standard/qCompass/src/ccThicknessTool.cpp