ACloudViewer: PythonEditor Class Reference
PythonEditor Class Reference final
#include <PythonEditor.h>
Signals
void executionCalled (const std::string &evalStatement, QListWidget *output)
Public Member Functions
PythonEditor (PythonInterpreter *interpreter)
void changeEvent (QEvent *e) override
bool openFile (const QString &fileName)
Static Public Member Functions
static QString SettingsApplicationName ()
Protected Slots
void newFile ()
void promptForFileToOpen ()
void promptForFolderToOpen ()
void save ()
void saveAs ()
void updateRecentFileActions ()
void openRecentFile ()
bool eventFilter (QObject *obj, QEvent *e) override
void projectTreeDoubleClicked (const QModelIndex &index)
void cut ()
void copy ()
void paste ()
void comment ()
void uncomment ()
void indentMore ()
void indentLess ()
void updateWindowMenu ()
void executionStarted ()
void executionFinished ()
CodeEditor * createChildCodeEditor ()
Protected Member Functions
void closeEvent (QCloseEvent *event) override
Detailed Description
Definition at line 50 of file PythonEditor.h.
Constructor & Destructor Documentation
PythonEditor()
PythonEditor::PythonEditor (PythonInterpreter * interpreter) explicit
Definition at line 28 of file PythonEditor.cpp.
References PythonInterpreter::executeCode(), executionCalled(), executionFinished(), PythonInterpreter::executionFinished(), executionStarted(), and PythonInterpreter::executionStarted().
Member Function Documentation
changeEvent()
void PythonEditor::changeEvent (QEvent * e) override
Definition at line 89 of file PythonEditor.cpp.
closeEvent()
void PythonEditor::closeEvent (QCloseEvent * event) override protected
Definition at line 45 of file PythonEditor.cpp.
comment
void PythonEditor::comment () protected slot
Definition at line 296 of file PythonEditor.cpp.
References CodeEditor::comment().
copy
void PythonEditor::copy () protected slot
Definition at line 279 of file PythonEditor.cpp.
createChildCodeEditor
CodeEditor * PythonEditor::createChildCodeEditor () protected slot
Definition at line 523 of file PythonEditor.cpp.
Referenced by newFile().
cut
void PythonEditor::cut () protected slot
Definition at line 271 of file PythonEditor.cpp.
eventFilter
bool PythonEditor::eventFilter (QObject * obj, QEvent * e) override protected slot
Definition at line 226 of file PythonEditor.cpp.
executionCalled
void PythonEditor::executionCalled (const std::string & evalStatement, QListWidget * output) signal
Referenced by PythonEditor().
executionFinished
void PythonEditor::executionFinished () protected slot
Definition at line 334 of file PythonEditor.cpp.
Referenced by PythonEditor().
executionStarted
void PythonEditor::executionStarted () protected slot
Definition at line 325 of file PythonEditor.cpp.
Referenced by PythonEditor().
indentLess
void PythonEditor::indentLess () protected slot
Definition at line 317 of file PythonEditor.cpp.
References CodeEditor::indentLess().
indentMore
void PythonEditor::indentMore () protected slot
Definition at line 310 of file PythonEditor.cpp.
References CodeEditor::indentMore().
newFile
void PythonEditor::newFile () protected slot
Definition at line 61 of file PythonEditor.cpp.
References createChildCodeEditor(), and CodeEditor::newFile().
openFile()
bool PythonEditor::openFile (const QString & fileName)
Opens a file
If the fileName points to an already opened file, then its window takes focus
Parameters
fileName the file to open
Returns
true of success
Definition at line 102 of file PythonEditor.cpp.
Referenced by openRecentFile(), projectTreeDoubleClicked(), and promptForFileToOpen().
openRecentFile
void PythonEditor::openRecentFile () protected slot
Definition at line 218 of file PythonEditor.cpp.
References openFile().
paste
void PythonEditor::paste () protected slot
Definition at line 287 of file PythonEditor.cpp.
projectTreeDoubleClicked
void PythonEditor::projectTreeDoubleClicked (const QModelIndex & index) protected slot
Definition at line 117 of file PythonEditor.cpp.
References openFile().
promptForFileToOpen
void PythonEditor::promptForFileToOpen () protected slot
Definition at line 69 of file PythonEditor.cpp.
References openFile().
promptForFolderToOpen
void PythonEditor::promptForFolderToOpen () protected slot
Definition at line 79 of file PythonEditor.cpp.
save
void PythonEditor::save () protected slot
Definition at line 252 of file PythonEditor.cpp.
saveAs
void PythonEditor::saveAs () protected slot
Definition at line 260 of file PythonEditor.cpp.
References CodeEditor::currentFile(), and CodeEditor::saveAs().
SettingsApplicationName()
QString PythonEditor::SettingsApplicationName () static
Definition at line 587 of file PythonEditor.cpp.
Referenced by updateRecentFileActions().
uncomment
void PythonEditor::uncomment () protected slot
Definition at line 303 of file PythonEditor.cpp.
References CodeEditor::uncomment().
updateRecentFileActions
void PythonEditor::updateRecentFileActions () protected slot
Definition at line 198 of file PythonEditor.cpp.
References count, MAX_RECENT_FILES, readRecentFiles(), and SettingsApplicationName().
updateWindowMenu
void PythonEditor::updateWindowMenu () protected slot
Definition at line 483 of file PythonEditor.cpp.
References CodeEditor::userFriendlyCurrentFile().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/CodeEditor/PythonEditor.h
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/CodeEditor/PythonEditor.cpp