ACloudViewer: RDBFilter Class Reference
RDBFilter Class Reference
#include <RDBFilter.h>
Public Member Functions
RDBFilter ()
CC_FILE_ERROR loadFile (const QString &fileName, ccHObject &container, LoadParameters &parameters) override
Loads one or more entities from a file.
bool canSave (CV_CLASS_ENUM type, bool &multiple, bool &exclusive) const override
Returns whether this I/O filter can save the specified type of entity.
Public Member Functions inherited from FileIOFilter
virtual ~FileIOFilter ()=default
bool importSupported () const
Returns whether this I/O filter can import files.
bool exportSupported () const
Returns whether this I/O filter can export files.
const QStringList & getFileFilters (bool onImport) const
Returns the file filter(s) for this I/O filter.
QString getDefaultExtension () const
Returns the default file extension.
virtual CC_FILE_ERROR saveToFile (ccHObject *entity, const QString &filename, const SaveParameters &parameters)
Saves an entity (or a group of) to a file.
virtual void unregister ()
Called when the filter is unregistered.
Additional Inherited Members
Public Types inherited from FileIOFilter
enum FilterFeature {
NoFeatures = 0x0000 , Import = 0x00001 , Export = 0x0002 , BuiltIn = 0x0004 ,
DynamicInfo = 0x0008
}
using Shared = QSharedPointer< FileIOFilter >
Shared type.
using FilterContainer = std::vector< FileIOFilter::Shared >
Type of a I/O filters container.
Static Public Member Functions inherited from FileIOFilter
static QStringList ImportFilterList ()
static ccHObject * LoadFromFile (const QString &filename, LoadParameters &parameters, Shared filter, CC_FILE_ERROR &result)
Loads one or more entities from a file with a known filter.
static ccHObject * LoadFromFile (const QString &filename, LoadParameters &parameters, CC_FILE_ERROR &result, const QString &fileFilter=QString())
Loads one or more entities from a file with known type.
static CC_FILE_ERROR SaveToFile (ccHObject *entities, const QString &filename, const SaveParameters &parameters, Shared filter)
static CC_FILE_ERROR SaveToFile (ccHObject *entities, const QString &filename, const SaveParameters &parameters, const QString &fileFilter)
static bool HandleGlobalShift (const CCVector3d &P, CCVector3d &Pshift, bool &preserveCoordinateShift, LoadParameters &loadParameters, bool useInputCoordinatesShiftIfPossible=false)
Shortcut to the ecvGlobalShiftManager mechanism specific for files.
static void DisplayErrorMessage (CC_FILE_ERROR err, const QString &action, const QString &filename)
Displays (to console) the message corresponding to a given error code.
static bool CheckForSpecialChars (const QString &filename)
Returns whether special characters are present in the input string.
static void ResetSesionCounter ()
static unsigned IncreaseSesionCounter ()
static void Register (Shared filter)
Registers a new filter.
static Shared GetFilter (const QString &fileFilter, bool onImport)
Returns the filter corresponding to the given 'file filter'.
static Shared FindBestFilterForExtension (const QString &ext)
Returns the best filter (presumably) to open a given file extension.
static const FilterContainer & GetFilters ()
Returns the set of all registered filters.
static void UnregisterAll ()
Unregisters all filters.
Protected Member Functions inherited from FileIOFilter
FileIOFilter (const FilterInfo &info)
void setImportExtensions (const QStringList &extensions)
void setImportFileFilterStrings (const QStringList &filterStrings)
void setExportFileFilterStrings (const QStringList &filterStrings)
Static Protected Attributes inherited from FileIOFilter
static constexpr float DEFAULT_PRIORITY = 25.0f
Detailed Description
Definition at line 29 of file RDBFilter.h.
Constructor & Destructor Documentation
RDBFilter()
RDBFilter::RDBFilter ()
Definition at line 44 of file RDBFilter.cpp.
References FileIOFilter::DEFAULT_PRIORITY, and FileIOFilter::Import.
Member Function Documentation
canSave()
bool RDBFilter::canSave (CV_CLASS_ENUM type, bool & multiple, bool & exclusive) const override virtual
Returns whether this I/O filter can save the specified type of entity.
Parameters
type entity type
multiple whether the filter can save multiple instances of this entity at once
exclusive whether the filter can only save this type of entity if selected or if it can be mixed with other types
Returns
whether the entity type can be saved
Reimplemented from FileIOFilter.
Definition at line 562 of file RDBFilter.cpp.
References type.
loadFile()
CC_FILE_ERROR RDBFilter::loadFile (const QString & filename, ccHObject & container, LoadParameters & parameters) override virtual
Loads one or more entities from a file.
This method must be implemented by children classes.
Parameters
filename file to load
container container to store loaded entities
parameters generic loading parameters
Returns
error
Reimplemented from FileIOFilter.
Definition at line 220 of file RDBFilter.cpp.
References ccHObject::addChild(), ccPointCloud::addNorm(), cloudViewer::PointCloudTpl< T >::addPoint(), ccPointCloud::addRGBColor(), ccPointCloud::addScalarField(), ecvColor::RgbTpl< Type >::b, CC_FERR_CANCELED_BY_USER, CC_FERR_NO_ERROR, CC_FERR_NOT_ENOUGH_MEMORY, context, count, Vector3Tpl< Type >::cross(), data, filename, Vector3Tpl< PointCoordinateType >::fromArray(), ecvColor::RgbTpl< Type >::g, cloudViewer::NormalizedProgress::oneStep(), FileIOFilter::LoadParameters::parentWidget, CVLog::Print(), ecvColor::RgbTpl< Type >::r, RDB_OPEN_DLG_Scalar, RDB_OPEN_DLG_TYPES_NAMES, ccPointCloud::reserve(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveTheRGBTable(), result, ccGenericPrimitive::setColor(), ccPointCloud::setCurrentDisplayedScalarField(), ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), ccObject::setName(), ccDrawableObject::setVisible(), ccDrawableObject::showColors(), ccDrawableObject::showNormals(), ccPlanarEntityInterface::showNormalVector(), ccDrawableObject::showSF(), cloudViewer::PointCloudTpl< T >::size(), ecvProgressDialog::start(), and X.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qRDBIO/include/RDBFilter.h
/root/ACloudViewer/plugins/core/IO/qRDBIO/src/RDBFilter.cpp