ACloudViewer: QCPItemBracket Class Reference
QCPItemBracket Class Reference
A bracket for referencing/highlighting certain parts in the plot.
#include <qcustomplot.h>
Public Types
enum BracketStyle {
bsSquare , bsRound , bsCurly , bsCalligraphic ,
bsSquare , bsRound , bsCurly , bsCalligraphic
}
enum BracketStyle {
bsSquare , bsRound , bsCurly , bsCalligraphic ,
bsSquare , bsRound , bsCurly , bsCalligraphic
}
Public Member Functions
QCPItemBracket (QCustomPlot *parentPlot)
virtual ~QCPItemBracket ()
QPen pen () const
QPen selectedPen () const
double length () const
BracketStyle style () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setLength (double length)
void setStyle (BracketStyle style)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
QCPItemBracket (QCustomPlot *parentPlot)
virtual ~QCPItemBracket ()
QPen pen () const
QPen selectedPen () const
double length () const
BracketStyle style () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setLength (double length)
void setStyle (BracketStyle style)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractItem
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
virtual ~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Public Attributes
QCPItemPosition *const left
QCPItemPosition *const right
QCPItemAnchor *const center
Protected Types
enum AnchorIndex { aiCenter , aiCenter }
enum AnchorIndex { aiCenter , aiCenter }
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPosition (int anchorId) const
QPen mainPen () const
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPen mainPen () const
Protected Member Functions inherited from QCPAbstractItem
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double rectDistance (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual void mousePressEvent (QMouseEvent *event, const QVariant &details)
virtual void mouseMoveEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseReleaseEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseDoubleClickEvent (QMouseEvent *event, const QVariant &details)
virtual void wheelEvent (QWheelEvent *event)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QPen mPen
QPen mSelectedPen
double mLength
BracketStyle mStyle
Protected Attributes inherited from QCPAbstractItem
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractItem
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
void layerChanged (QCPLayer *newLayer)
Detailed Description
A bracket for referencing/highlighting certain parts in the plot.
Bracket example. Blue dotted circles are
anchors, solid blue discs are positions."
It has two positions, left and right, which define the span of the bracket. If left is actually farther to the left than right, the bracket is opened to the bottom, as shown in the example image.
The bracket supports multiple styles via setStyle. The length, i.e. how far the bracket stretches away from the embraced span, can be controlled with setLength.
Demonstrating the effect of different values for setLength, for styles bsCalligraphic and bsSquare. Anchors and positions are displayed for reference.
It provides an anchor center, to allow connection of other items, e.g. an arrow (QCPItemLine or QCPItemCurve) or a text label (QCPItemText), to the bracket.
Definition at line 7795 of file qcustomplot.h.
Member Enumeration Documentation
AnchorIndex [1/2]
enum QCPItemBracket::AnchorIndex protected
Enumerator
aiCenter
aiCenter
Definition at line 7848 of file qcustomplot.h.
AnchorIndex [2/2]
enum QCPItemBracket::AnchorIndex protected
Enumerator
aiCenter
aiCenter
Definition at line 4463 of file qcustomplot.h.
BracketStyle [1/2]
enum QCPItemBracket::BracketStyle
Defines the various visual shapes of the bracket item. The appearance can be further modified by setLength and setPen.
See also
setStyle
Enumerator
bsSquare
A brace with angled edges.
bsRound
A brace with round edges.
bsCurly
A curly brace.
bsCalligraphic
A curly brace with varying stroke width giving a calligraphic impression
bsSquare
A brace with angled edges.
bsRound
A brace with round edges.
bsCurly
A curly brace.
bsCalligraphic
A curly brace with varying stroke width giving a calligraphic impression
Definition at line 7810 of file qcustomplot.h.
BracketStyle [2/2]
enum QCPItemBracket::BracketStyle
Enumerator
bsSquare
A brace with angled edges.
bsRound
A brace with round edges.
bsCurly
A curly brace.
bsCalligraphic
A curly brace with varying stroke width giving a calligraphic impression
bsSquare
A brace with angled edges.
bsRound
A brace with round edges.
bsCurly
A curly brace.
bsCalligraphic
A curly brace with varying stroke width giving a calligraphic impression
Definition at line 4426 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemBracket() [1/2]
QCPItemBracket::QCPItemBracket (QCustomPlot * parentPlot) explicit
Creates a bracket item and sets default values.
The created item is automatically registered with parentPlot. This QCustomPlot instance takes ownership of the item, so do not delete it manually but use QCustomPlot::removeItem() instead.
Creates a bracket item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 31866 of file qcustomplot.cpp.
References ecvColor::black(), ecvColor::blue(), left, right, QCPItemPosition::setCoords(), setPen(), and setSelectedPen().
~QCPItemBracket() [1/2]
QCPItemBracket::~QCPItemBracket () virtual
Definition at line 31880 of file qcustomplot.cpp.
QCPItemBracket() [2/2]
QCPItemBracket::QCPItemBracket (QCustomPlot * parentPlot)
~QCPItemBracket() [2/2]
virtual QCPItemBracket::~QCPItemBracket () virtual
Member Function Documentation
anchorPixelPoint()
QPointF QCPItemBracket::anchorPixelPoint (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 24749 of file qcustomplot.cpp.
References aiCenter, left, mLength, QCPItemPosition::pixelPoint(), and right.
anchorPixelPosition()
QPointF QCPItemBracket::anchorPixelPosition (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 32063 of file qcustomplot.cpp.
References aiCenter, left, mLength, QCPVector2D::normalized(), QCPVector2D::perpendicular(), QCPItemPosition::pixelPosition(), right, QCPVector2D::toPoint(), and QCPVector2D::toPointF().
draw() [1/2]
void QCPItemBracket::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
Definition at line 31970 of file qcustomplot.cpp.
References bsCalligraphic, bsCurly, bsRound, bsSquare, QCPAbstractItem::clipRect(), color, QCPPainter::drawLine(), left, mainPen(), mLength, mStyle, QCPVector2D::normalized(), cloudViewer::t::geometry::path, QCPVector2D::perpendicular(), QCPItemPosition::pixelPosition(), right, QCPPainter::setPen(), QCPVector2D::toPoint(), and QCPVector2D::toPointF().
draw() [2/2]
virtual void QCPItemBracket::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
length() [1/2]
double QCPItemBracket::length () const inline
Definition at line 7828 of file qcustomplot.h.
Referenced by setLength().
length() [2/2]
double QCPItemBracket::length () const inline
Definition at line 4443 of file qcustomplot.h.
mainPen() [1/2]
QPen QCPItemBracket::mainPen () const protected
Definition at line 32085 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
mainPen() [2/2]
QPen QCPItemBracket::mainPen () const protected
pen() [1/2]
QPen QCPItemBracket::pen () const inline
Definition at line 7826 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
pen() [2/2]
QPen QCPItemBracket::pen () const inline
Definition at line 4441 of file qcustomplot.h.
selectedPen() [1/2]
QPen QCPItemBracket::selectedPen () const inline
Definition at line 7827 of file qcustomplot.h.
selectedPen() [2/2]
QPen QCPItemBracket::selectedPen () const inline
Definition at line 4442 of file qcustomplot.h.
selectTest() [1/2]
double QCPItemBracket::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 31923 of file qcustomplot.cpp.
References a, bsCalligraphic, bsCurly, bsRound, bsSquare, QCPVector2D::distanceSquaredToLine(), left, mLength, QCPAbstractItem::mSelectable, mStyle, QCPVector2D::normalized(), QCPVector2D::perpendicular(), QCPItemPosition::pixelPosition(), right, and QCPVector2D::toPoint().
selectTest() [2/2]
virtual double QCPItemBracket::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
setLength() [1/2]
void QCPItemBracket::setLength (double length)
Sets the length in pixels how far the bracket extends in the direction towards the embraced span of the bracket (i.e. perpendicular to the left-right-direction)
Demonstrating the effect of different values for setLength, for styles bsCalligraphic and bsSquare. Anchors and positions are displayed for reference.
Definition at line 31911 of file qcustomplot.cpp.
References length(), and mLength.
setLength() [2/2]
void QCPItemBracket::setLength (double length)
setPen() [1/2]
void QCPItemBracket::setPen (const QPen & pen)
Sets the pen that will be used to draw the bracket.
Note that when the style is bsCalligraphic, only the color will be taken from the pen, the stroke and width are ignored. To change the apparent stroke width of a calligraphic bracket, use setLength, which has a similar effect.
See also
setSelectedPen
Definition at line 31892 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemBracket().
setPen() [2/2]
void QCPItemBracket::setPen (const QPen & pen)
setSelectedPen() [1/2]
void QCPItemBracket::setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw the bracket when selected
See also
setPen, setSelected
Definition at line 31899 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemBracket().
setSelectedPen() [2/2]
void QCPItemBracket::setSelectedPen (const QPen & pen)
setStyle() [1/2]
void QCPItemBracket::setStyle (QCPItemBracket::BracketStyle style)
Sets the style of the bracket, i.e. the shape/visual appearance.
See also
setPen
Definition at line 31918 of file qcustomplot.cpp.
References mStyle, and style().
setStyle() [2/2]
void QCPItemBracket::setStyle (BracketStyle style)
style() [1/2]
BracketStyle QCPItemBracket::style () const inline
Definition at line 7829 of file qcustomplot.h.
Referenced by setStyle().
style() [2/2]
BracketStyle QCPItemBracket::style () const inline
Definition at line 4444 of file qcustomplot.h.
Member Data Documentation
center
QCPItemAnchor *const QCPItemBracket::center
Definition at line 7844 of file qcustomplot.h.
left
QCPItemPosition *const QCPItemBracket::left
Definition at line 7842 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), QCPItemBracket(), and selectTest().
mLength
double QCPItemBracket::mLength protected
Definition at line 7850 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), selectTest(), and setLength().
mPen
QPen QCPItemBracket::mPen protected
Definition at line 7849 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
mSelectedPen
QPen QCPItemBracket::mSelectedPen protected
Definition at line 7849 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
mStyle
BracketStyle QCPItemBracket::mStyle protected
Definition at line 7851 of file qcustomplot.h.
Referenced by draw(), selectTest(), and setStyle().
right
QCPItemPosition *const QCPItemBracket::right
Definition at line 7843 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), QCPItemBracket(), and selectTest().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp