ACloudViewer: PdmsTools::PdmsCommands::NumericalValue Class Reference
PdmsTools::PdmsCommands::NumericalValue Class Reference
#include <PdmsTools.h>
Public Member Functions
NumericalValue (Token t)
virtual bool handle (PointCoordinateType numvalue)
virtual bool isValid () const
virtual PointCoordinateType getValue () const
virtual bool execute (PdmsObjects::GenericItem *&item) const
Public Member Functions inherited from PdmsTools::PdmsCommands::Command
Command (Token t)
Command (const Command &com)
virtual ~Command ()
virtual bool handle (const char *str)
virtual bool handle (Token t)
Public Attributes
PointCoordinateType value
int valueChanges
Public Attributes inherited from PdmsTools::PdmsCommands::Command
Token command
Additional Inherited Members
Static Public Member Functions inherited from PdmsTools::PdmsCommands::Command
static Command * Create (Token t)
Factory.
Detailed Description
Definition at line 496 of file PdmsTools.h.
Constructor & Destructor Documentation
NumericalValue()
PdmsTools::PdmsCommands::NumericalValue::NumericalValue (Token t) inline explicit
Definition at line 501 of file PdmsTools.h.
Member Function Documentation
execute()
bool NumericalValue::execute (PdmsObjects::GenericItem *& item) const virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Reimplemented in PdmsTools::PdmsCommands::DistanceValue.
Definition at line 103 of file PdmsTools.cpp.
References PdmsTools::PdmsObjects::GenericItem::setValue().
getValue()
PointCoordinateType NumericalValue::getValue () const virtual
Definition at line 90 of file PdmsTools.cpp.
References cloudViewer::DegreesToRadians(), PdmsTools::PDMS_ANGLE, PdmsTools::PDMS_X_BOTTOM_SHEAR, PdmsTools::PDMS_X_TOP_SHEAR, PdmsTools::PDMS_Y_BOTTOM_SHEAR, and PdmsTools::PDMS_Y_TOP_SHEAR.
handle()
bool NumericalValue::handle (PointCoordinateType numvalue) virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Reimplemented in PdmsTools::PdmsCommands::DistanceValue.
Definition at line 82 of file PdmsTools.cpp.
Referenced by PdmsTools::PdmsCommands::DistanceValue::handle().
isValid()
bool NumericalValue::isValid () const virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 88 of file PdmsTools.cpp.
Member Data Documentation
value
PointCoordinateType PdmsTools::PdmsCommands::NumericalValue::value
Definition at line 498 of file PdmsTools.h.
valueChanges
int PdmsTools::PdmsCommands::NumericalValue::valueChanges
Definition at line 499 of file PdmsTools.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsTools.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsTools.cpp