ACloudViewer: PdmsParser Class Reference
PdmsParser Class Reference
#include <PdmsParser.h>
Public Member Functions
PdmsParser ()
Default constructor.
~PdmsParser ()
void reset ()
void linkWithSession (PdmsLexer *s)
bool parseSessionContent ()
PdmsObjects::GenericItem * getLoadedObject (bool forgetIt=true)
Protected Member Functions
bool processCurrentToken ()
Protected Attributes
PdmsLexer * session
PdmsCommands::Command * currentCommand
PdmsObjects::GenericItem * currentItem
PdmsObjects::GenericItem * root
Detailed Description
Use this parser the following way: 1- create any Pdms session 2- link parser with the session 3- parse the current session content. if the session content changes, you can parse it as many times as you wish (the loaded object is overwritten each time) 4- get the result (either in session or in parser)
Definition at line 93 of file PdmsParser.h.
Constructor & Destructor Documentation
PdmsParser()
PdmsParser::PdmsParser ()
Default constructor.
Definition at line 450 of file PdmsParser.cpp.
~PdmsParser()
PdmsParser::~PdmsParser ()
Definition at line 456 of file PdmsParser.cpp.
References currentCommand, currentItem, and PdmsTools::PdmsObjects::GenericItem::getRoot().
Member Function Documentation
getLoadedObject()
PdmsObjects::GenericItem * PdmsParser::getLoadedObject (bool forgetIt = true)
Definition at line 593 of file PdmsParser.cpp.
References currentItem, PdmsLexer::getLoadedObject(), result, root, and session.
Referenced by PDMSFilter::loadFile().
linkWithSession()
void PdmsParser::linkWithSession (PdmsLexer * s)
Definition at line 470 of file PdmsParser.cpp.
References currentCommand, currentItem, PdmsTools::PDMS_MILLIMETRE, root, and session.
Referenced by PDMSFilter::loadFile().
parseSessionContent()
bool PdmsParser::parseSessionContent ()
Definition at line 568 of file PdmsParser.cpp.
References PdmsLexer::closeSession(), PdmsTools::PdmsObjects::GenericItem::convertCoordinateSystem(), currentItem, PdmsTools::PdmsObjects::GenericItem::getRoot(), PdmsLexer::gotoNextToken(), PdmsLexer::initializeSession(), PdmsLexer::printWarning(), processCurrentToken(), root, session, and PdmsLexer::setLoadedObject().
Referenced by PDMSFilter::loadFile().
processCurrentToken()
bool PdmsParser::processCurrentToken () protected
Definition at line 478 of file PdmsParser.cpp.
References currentCommand, currentItem, PdmsTools::PdmsCommands::Command::execute(), PdmsLexer::finish(), PdmsLexer::getCurrentToken(), PdmsTools::PdmsObjects::GenericItem::getRoot(), PdmsTools::PdmsCommands::Command::handle(), PdmsLexer::nameFromBuffer(), PdmsTools::PDMS_EOS, PdmsTools::PDMS_NAME_STR, PdmsTools::PDMS_NUM_VALUE, PdmsTools::PDMS_RETURN, PdmsTools::PDMS_UNKNOWN, PdmsTools::PDMS_UNUSED, PdmsLexer::printWarning(), root, session, and PdmsLexer::valueFromBuffer().
Referenced by parseSessionContent().
reset()
void PdmsParser::reset ()
Member Data Documentation
currentCommand
PdmsCommands::Command* PdmsParser::currentCommand protected
Definition at line 108 of file PdmsParser.h.
Referenced by linkWithSession(), processCurrentToken(), and ~PdmsParser().
currentItem
PdmsObjects::GenericItem* PdmsParser::currentItem protected
Definition at line 109 of file PdmsParser.h.
Referenced by getLoadedObject(), linkWithSession(), parseSessionContent(), processCurrentToken(), and ~PdmsParser().
root
PdmsObjects::GenericItem* PdmsParser::root protected
Definition at line 110 of file PdmsParser.h.
Referenced by getLoadedObject(), linkWithSession(), parseSessionContent(), and processCurrentToken().
session
PdmsLexer* PdmsParser::session protected
Definition at line 107 of file PdmsParser.h.
Referenced by getLoadedObject(), linkWithSession(), parseSessionContent(), and processCurrentToken().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsParser.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsParser.cpp