ACloudViewer: VtkUtils::ModelToPointsConverter Class Reference
VtkUtils::ModelToPointsConverter Class Reference
#include <modeltopointsconverter.h>
Public Member Functions
ModelToPointsConverter (TableModel *model)
QList< Point3F > points () const
QVector< Tuple3ui > vertices () const
void run ()
Public Member Functions inherited from VtkUtils::SignalledRunnable
SignalledRunnable ()
Additional Inherited Members
Signals inherited from VtkUtils::SignalledRunnable
void finished ()
Detailed Description
Definition at line 20 of file modeltopointsconverter.h.
Constructor & Destructor Documentation
ModelToPointsConverter()
VtkUtils::ModelToPointsConverter::ModelToPointsConverter (TableModel * model) explicit
Definition at line 14 of file modeltopointsconverter.cpp.
Member Function Documentation
points()
QList< Point3F > VtkUtils::ModelToPointsConverter::points () const
Definition at line 17 of file modeltopointsconverter.cpp.
run()
void VtkUtils::ModelToPointsConverter::run ()
Definition at line 23 of file modeltopointsconverter.cpp.
References VtkUtils::TableModel::columnCount(), VtkUtils::TableModel::data(), VtkUtils::SignalledRunnable::finished(), and VtkUtils::TableModel::rowCount().
vertices()
QVector< Tuple3ui > VtkUtils::ModelToPointsConverter::vertices () const
Definition at line 19 of file modeltopointsconverter.cpp.
References VtkUtils::TableModel::verticesData().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/modeltopointsconverter.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/modeltopointsconverter.cpp