ACloudViewer: q3DMASCPlugin Class Reference
q3DMASCPlugin Class Reference
3DMASC plugin
#include <q3DMASC.h>
Public Member Functions
q3DMASCPlugin (QObject *parent=nullptr)
Default constructor.
void onNewSelection (const ccHObject::Container &selectedEntities) override
QList< QAction * > getActions () override
Get a list of actions for this plugin.
void registerCommands (ccCommandLineInterface *cmd) override
Optional: registers commands (for the command line mode)
Public Member Functions inherited from ccStdPluginInterface
ccStdPluginInterface (const QString &resourcePath=QString())
Default constructor.
virtual ~ccStdPluginInterface () override=default
Destructor.
virtual CC_PLUGIN_TYPE getType () const override
Returns plugin type (standard or OpenGL filter)
virtual void setMainAppInterface (ecvMainAppInterface *app)
Sets application entry point.
virtual ecvMainAppInterface * getMainAppInterface ()
A callback pointer to the main app interface for use by plugins.
virtual void dispToConsole (QString message, ecvMainAppInterface::ConsoleMessageLevel level=ecvMainAppInterface::STD_CONSOLE_MESSAGE)
Shortcut to ecvMainAppInterface::dispToConsole.
Public Member Functions inherited from ccDefaultPluginInterface
virtual ~ccDefaultPluginInterface ()
virtual bool isCore () const override
Is this plugin a core plugin?
virtual QString getName () const override
Returns (short) name (for menu entry, etc.)
virtual QString getDescription () const override
Returns long name/description (for tooltip, etc.)
virtual QIcon getIcon () const override
Returns icon.
virtual ReferenceList getReferences () const override
virtual ContactList getAuthors () const override
virtual ContactList getMaintainers () const override
Public Member Functions inherited from ccPluginInterface
virtual ~ccPluginInterface ()=default
Virtual destructor.
virtual bool start ()
Starts the plugin.
virtual void stop ()
Stops the plugin.
virtual ccExternalFactory * getCustomObjectsFactory () const
Returns the plugin's custom object factory (if any)
Protected Slots
void doClassifyAction ()
void saveTrainParameters (const masc::TrainParameters &params)
void loadTrainParameters (masc::TrainParameters &params)
void doTrainAction ()
Protected Attributes
QAction * m_classifyAction
Calssify action.
QAction * m_trainAction
Train action.
ccHObject::Container m_selectedEntities
Currently selected entities.
Protected Attributes inherited from ccStdPluginInterface
ecvMainAppInterface * m_app
Main application interface.
Additional Inherited Members
Public Types inherited from ccPluginInterface
typedef QList< Contact > ContactList
using ReferenceList = QList< Reference >
Protected Member Functions inherited from ccDefaultPluginInterface
ccDefaultPluginInterface (const QString &resourcePath=QString())
Detailed Description
3DMASC plugin
3D Multi-cloud, multi-Attribute, multi-Scale, multi-Class classification
Definition at line 18 of file q3DMASC.h.
Constructor & Destructor Documentation
q3DMASCPlugin()
q3DMASCPlugin::q3DMASCPlugin (QObject * parent = nullptr) explicit
Default constructor.
Definition at line 31 of file q3DMASC.cpp.
Member Function Documentation
doClassifyAction
void q3DMASCPlugin::doClassifyAction () protected slot
Definition at line 83 of file q3DMASC.cpp.
References masc::Classifier::classify(), corePoints, ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, masc::Feature::ExtractSources(), Classify3DMASCDialog::getClouds(), ecvMainAppInterface::getMainWindow(), masc::Classifier::isValid(), masc::Tools::LoadClassifier(), masc::Tools::LoadClassifierCloudLabels(), ccStdPluginInterface::m_app, masc::Tools::PrepareFeatures(), SFCollector::releaseSFs(), Classify3DMASCDialog::setCloudRoles(), and ShowClassifyDisclaimer().
Referenced by getActions().
doTrainAction
void q3DMASCPlugin::doTrainAction () protected slot
Definition at line 241 of file q3DMASC.cpp.
References ccHObject::addChild(), Train3DMASCDialog::addFeature(), Train3DMASCDialog::addScale(), ecvMainAppInterface::addToDB(), masc::CorePoints::cloud, Train3DMASCDialog::connectScaleSelectionToFeatureSelection(), corePoints, ecvMainAppInterface::dispToConsole(), QtCompat::endl(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, masc::Classifier::evaluate(), masc::Feature::ExtractSources(), filename, ccHObject::getChildrenNumber(), masc::Tools::GetClassificationSF(), Classify3DMASCDialog::getClouds(), ecvMainAppInterface::getMainWindow(), Train3DMASCDialog::getRun(), Train3DMASCDialog::getSaveTrace(), Train3DMASCDialog::getTracePath(), masc::Classifier::getVarImportance(), masc::Classifier::AccuracyMetrics::goodGuess, Train3DMASCDialog::isFeatureSelected(), masc::Tools::LoadClassifierCloudLabels(), masc::Tools::LoadTrainingFile(), loadTrainParameters(), ccStdPluginInterface::m_app, masc::CorePoints::NONE, masc::CorePoints::origin, masc::Tools::PrepareFeatures(), masc::CorePoints::RANDOM, masc::Tools::RandomSubset(), masc::Classifier::AccuracyMetrics::ratio, ecvMainAppInterface::redrawAll(), SFCollector::releaseSFs(), masc::CorePoints::role, s_params, masc::Classifier::AccuracyMetrics::sampleCount, masc::Tools::SaveClassifier(), saveTrainParameters(), Train3DMASCDialog::setClassifierSaved(), Classify3DMASCDialog::setCloudRoles(), ccObject::setEnabled(), Train3DMASCDialog::setFeatureImportance(), Train3DMASCDialog::setFirstRunDone(), Train3DMASCDialog::setInputFilePath(), Train3DMASCDialog::setResultText(), Train3DMASCDialog::shouldSaveClassifier(), ShowTrainDisclaimer(), Train3DMASCDialog::sortByFeatureImportance(), masc::CorePoints::SPATIAL, ecvMainAppInterface::STD_CONSOLE_MESSAGE, masc::Classifier::train(), CVLog::Warning(), and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by getActions().
getActions()
QList< QAction * > q3DMASCPlugin::getActions () override virtual
Get a list of actions for this plugin.
Implements ccStdPluginInterface.
Definition at line 57 of file q3DMASC.cpp.
References doClassifyAction(), doTrainAction(), m_classifyAction, and m_trainAction.
loadTrainParameters
void q3DMASCPlugin::loadTrainParameters (masc::TrainParameters & params) protected slot
Definition at line 230 of file q3DMASC.cpp.
References masc::RandomTreesParams::activeVarCount, masc::RandomTreesParams::maxDepth, masc::RandomTreesParams::maxTreeCount, masc::RandomTreesParams::minSampleCount, and masc::TrainParameters::rt.
Referenced by doTrainAction().
onNewSelection()
void q3DMASCPlugin::onNewSelection (const ccHObject::Container & selectedEntities) override virtual
This method is called by the main application whenever the entity selection changes Does nothing by default. Should be re-implemented by the plugin if necessary.
Parameters
selectedEntities currently selected entities
Reimplemented from ccStdPluginInterface.
Definition at line 37 of file q3DMASC.cpp.
References ecvMainAppInterface::dbRootObject(), ccHObject::getChildrenNumber(), ccStdPluginInterface::m_app, m_classifyAction, m_selectedEntities, and m_trainAction.
registerCommands()
void q3DMASCPlugin::registerCommands (ccCommandLineInterface * cmd) override virtual
Optional: registers commands (for the command line mode)
Does nothing by default.
Warning
: don't use keywords that are already used by the main application or other plugins! (use a unique prefix for all commands if possible)
Reimplemented from ccPluginInterface.
Definition at line 833 of file q3DMASC.cpp.
References ccCommandLineInterface::registerCommand().
saveTrainParameters
void q3DMASCPlugin::saveTrainParameters (const masc::TrainParameters & params) protected slot
Definition at line 220 of file q3DMASC.cpp.
References masc::RandomTreesParams::activeVarCount, masc::RandomTreesParams::maxDepth, masc::RandomTreesParams::maxTreeCount, masc::RandomTreesParams::minSampleCount, and masc::TrainParameters::rt.
Referenced by doTrainAction().
Member Data Documentation
m_classifyAction
QAction* q3DMASCPlugin::m_classifyAction protected
Calssify action.
Definition at line 42 of file q3DMASC.h.
Referenced by getActions(), and onNewSelection().
m_selectedEntities
ccHObject::Container q3DMASCPlugin::m_selectedEntities protected
Currently selected entities.
Definition at line 47 of file q3DMASC.h.
Referenced by onNewSelection().
m_trainAction
QAction* q3DMASCPlugin::m_trainAction protected
Train action.
Definition at line 44 of file q3DMASC.h.
Referenced by getActions(), and onNewSelection().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/q3DMASC/q3DMASC.h
/root/ACloudViewer/plugins/core/Standard/q3DMASC/q3DMASC.cpp