ACloudViewer: qVoxFallTools Class Reference
qVoxFallTools Class Reference
#include <qVoxFallTools.h>
Static Public Member Functions
static std::vector< Tuple3i > FindAdjacents (Tuple3i V, CCVector3 steps, bool facetsOnly)
static int Grid2Index (Tuple3i n, CCVector3 steps)
static Tuple3i Index2Grid (unsigned index, CCVector3 steps)
Detailed Description
Definition at line 55 of file qVoxFallTools.h.
Member Function Documentation
FindAdjacents()
std::vector< Tuple3i > qVoxFallTools::FindAdjacents (Tuple3i V, CCVector3 steps, bool facetsOnly = false) static
Definition at line 64 of file qVoxFallTools.cpp.
References Tuple3Tpl< Type >::x, x, Tuple3Tpl< Type >::y, y, Tuple3Tpl< Type >::z, and z.
Referenced by ClusterEmptySpace().
Grid2Index()
int qVoxFallTools::Grid2Index (Tuple3i n, CCVector3 steps) static
Definition at line 101 of file qVoxFallTools.cpp.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ClusterEmptySpace(), GetVoxelOccupancy(), and GetVoxelOccupancyBefore().
Index2Grid()
Tuple3i qVoxFallTools::Index2Grid (unsigned index, CCVector3 steps) static
Definition at line 110 of file qVoxFallTools.cpp.
References cloudViewer::utility::floor(), Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
Referenced by ClusterEmptySpace(), ComputeClusterVolume(), and InitializeOutputCloud().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qVoxFall/include/qVoxFallTools.h
/root/ACloudViewer/plugins/core/Standard/qVoxFall/src/qVoxFallTools.cpp