ACloudViewer: ccPinchNodeTool Class Reference
ccPinchNodeTool Class Reference
#include <ccPinchNodeTool.h>
Public Member Functions
ccPinchNodeTool ()
virtual ~ccPinchNodeTool ()
virtual void toolActivated () override
virtual void toolDisactivated () override
void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccPointCloud *cloud, const CCVector3 &P) override
Public Member Functions inherited from ccTool
virtual ~ccTool ()
void initializeTool (ecvMainAppInterface *app)
virtual void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccHObject *pickedObject, const CCVector3 &P)
virtual void onNewSelection (const ccHObject::Container &selectedEntities)
virtual void accept ()
virtual void cancel ()
virtual bool canUndo ()
virtual void undo ()
Additional Inherited Members
Protected Member Functions inherited from ccTool
ccTool ()
Protected Attributes inherited from ccTool
ecvMainAppInterface * m_app
QWidget * m_window
Detailed Description
Definition at line 20 of file ccPinchNodeTool.h.
Constructor & Destructor Documentation
ccPinchNodeTool()
ccPinchNodeTool::ccPinchNodeTool ()
Definition at line 10 of file ccPinchNodeTool.cpp.
~ccPinchNodeTool()
ccPinchNodeTool::~ccPinchNodeTool () virtual
Definition at line 12 of file ccPinchNodeTool.cpp.
Member Function Documentation
pointPicked()
void ccPinchNodeTool::pointPicked (ccHObject * insertPoint, unsigned itemIdx, ccPointCloud * cloud, const CCVector3 & P) override virtual
Reimplemented from ccTool.
Definition at line 15 of file ccPinchNodeTool.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), ccGeoObject::getGeoObjectParent(), ccGeoObject::getRegion(), ccGeoObject::INTERIOR, ccTool::m_app, ccObject::setName(), and ccDrawableObject::showNameIn3D().
toolActivated()
void ccPinchNodeTool::toolActivated () override virtual
Reimplemented from ccTool.
Definition at line 47 of file ccPinchNodeTool.cpp.
toolDisactivated()
void ccPinchNodeTool::toolDisactivated () override virtual
Reimplemented from ccTool.
Definition at line 52 of file ccPinchNodeTool.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCompass/include/ccPinchNodeTool.h
/root/ACloudViewer/plugins/core/Standard/qCompass/src/ccPinchNodeTool.cpp