ACloudViewer: colmap::JetColormap Class Reference
colmap::JetColormap Class Reference
#include <bitmap.h>
Static Public Member Functions
static float Red (const float gray)
static float Green (const float gray)
static float Blue (const float gray)
Detailed Description
Definition at line 178 of file bitmap.h.
Member Function Documentation
Blue()
float colmap::JetColormap::Blue (const float gray) static
Definition at line 659 of file bitmap.cc.
Referenced by colmap::PointColormapError::ComputeColor(), colmap::PointColormapTrackLen::ComputeColor(), colmap::PointColormapGroundResolution::ComputeColor(), cloudViewer::MatchMatrixWidget::Show(), colmap::MatchMatrixWidget::Show(), and colmap::mvs::DepthMap::ToBitmap().
Green()
float colmap::JetColormap::Green (const float gray) static
Definition at line 657 of file bitmap.cc.
Referenced by colmap::PointColormapError::ComputeColor(), colmap::PointColormapTrackLen::ComputeColor(), colmap::PointColormapGroundResolution::ComputeColor(), cloudViewer::MatchMatrixWidget::Show(), colmap::MatchMatrixWidget::Show(), and colmap::mvs::DepthMap::ToBitmap().
Red()
float colmap::JetColormap::Red (const float gray) static
Definition at line 655 of file bitmap.cc.
Referenced by colmap::PointColormapError::ComputeColor(), colmap::PointColormapTrackLen::ComputeColor(), colmap::PointColormapGroundResolution::ComputeColor(), cloudViewer::MatchMatrixWidget::Show(), colmap::MatchMatrixWidget::Show(), and colmap::mvs::DepthMap::ToBitmap().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/util/bitmap.h
/root/ACloudViewer/libs/Reconstruction/src/util/bitmap.cc