ACloudViewer: cloudViewer::core::SmallVectorTemplateBase< T, bool > Class Template Reference
cloudViewer::core::SmallVectorTemplateBase< T, bool > Class Template Reference
#include <SmallVector.h>
Public Member Functions
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
Public Member Functions inherited from cloudViewer::core::SmallVectorTemplateCommon< T, typename >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >
size_t size () const
size_t capacity () const
bool empty () const
Protected Types
using ValueParamT = const T &
Protected Member Functions
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
T * mallocForGrow (size_t MinSize, size_t &NewCapacity)
void moveElementsForGrow (T *NewElts)
void takeAllocationForGrow (T *NewElts, size_t NewCapacity)
Transfer ownership of the allocation, finishing up grow().
const T * reserveForParamAndGetAddress (const T &Elt, size_t N=1)
T * reserveForParamAndGetAddress (T &Elt, size_t N=1)
void growAndAssign (size_t NumElts, const T &Elt)
template<typename... ArgTypes>
T & growAndEmplaceBack (ArgTypes &&...Args)
Protected Member Functions inherited from cloudViewer::core::SmallVectorTemplateCommon< T, typename >
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSize, size_t TSize)
bool isSmall () const
void resetToSmall ()
Put this vector in a state of being small.
bool isReferenceToRange (const void *V, const void *First, const void *Last) const
Return true if V is an internal reference to the given range.
bool isReferenceToStorage (const void *V) const
Return true if V is an internal reference to this vector.
bool isRangeInStorage (const void *First, const void *Last) const
bool isSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
void assertSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Check whether Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToAdd (const void *Elt, size_t N=1)
void assertSafeToReferenceAfterClear (const T *From, const T *To)
Check whether any part of the range will be invalidated by clearing.
template<class ItTy , std::enable_if_t< !std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToReferenceAfterClear (ItTy, ItTy)
void assertSafeToAddRange (const T *From, const T *To)
Check whether any part of the range will be invalidated by growing.
template<class ItTy , std::enable_if_t< !std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToAddRange (ItTy, ItTy)
Protected Member Functions inherited from cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (size_t MinSize, size_t TSize, size_t &NewCapacity)
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
void set_size (size_t N)
Static Protected Member Functions
static void destroy_range (T *S, T *E)
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
static T && forward_value_param (T &&V)
static const T & forward_value_param (const T &V)
Static Protected Member Functions inherited from cloudViewer::core::SmallVectorTemplateCommon< T, typename >
template<class U >
static const T * reserveForParamAndGetAddressImpl (U *This, const T &Elt, size_t N)
Static Protected Member Functions inherited from cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Static Protected Attributes
static constexpr bool TakesParamByValue = false
Additional Inherited Members
Public Types inherited from cloudViewer::core::SmallVectorTemplateCommon< T, typename >
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = std::reverse_iterator< iterator >
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Protected Attributes inherited from cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >
void * BeginX
SmallVectorSizeType< T > Size
SmallVectorSizeType< T > Capacity
Detailed Description
template<typename T, bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value>
class cloudViewer::core::SmallVectorTemplateBase< T, bool >
SmallVectorTemplateBase<TriviallyCopyable = false> - This is where we put method implementations that are designed to work with non-trivial T's.
We approximate is_trivially_copyable with trivial move/copy construction and trivial destruction. While the standard doesn't specify that you're allowed copy these types with memcpy, there is no way for the type to observe this. This catches the important case of std::pair<POD, POD>, which is not trivially assignable.
Definition at line 368 of file SmallVector.h.
Member Typedef Documentation
ValueParamT
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> using cloudViewer::core::SmallVectorTemplateBase< T, bool >::ValueParamT = const T & protected
Definition at line 373 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorTemplateBase()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> cloudViewer::core::SmallVectorTemplateBase< T, bool >::SmallVectorTemplateBase (size_t Size) inline protected
Definition at line 375 of file SmallVector.h.
Member Function Documentation
destroy_range()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> static void cloudViewer::core::SmallVectorTemplateBase< T, bool >::destroy_range (T * S, T * E) inline static protected
Definition at line 377 of file SmallVector.h.
Referenced by cloudViewer::core::SmallVectorImpl< T >::assign(), cloudViewer::core::SmallVectorImpl< T >::assignRemote(), cloudViewer::core::SmallVectorImpl< T >::clear(), cloudViewer::core::SmallVectorImpl< T >::erase(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::growAndAssign(), cloudViewer::core::SmallVectorImpl< T >::operator=(), cloudViewer::core::SmallVector< T, N >::operator=(), cloudViewer::core::SmallVectorImpl< T >::swap(), cloudViewer::core::SmallVectorImpl< T >::truncate(), and cloudViewer::core::SmallVector< T, N >::~SmallVector().
forward_value_param() [1/2]
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> static const T& cloudViewer::core::SmallVectorTemplateBase< T, bool >::forward_value_param (const T & V) inline static protected
Definition at line 433 of file SmallVector.h.
forward_value_param() [2/2]
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> static T&& cloudViewer::core::SmallVectorTemplateBase< T, bool >::forward_value_param (T && V) inline static protected
Definition at line 432 of file SmallVector.h.
Referenced by cloudViewer::core::SmallVectorImpl< T >::insert().
grow()
template<typename T , bool TriviallyCopyable> void cloudViewer::core::SmallVectorTemplateBase< T, TriviallyCopyable >::grow (size_t MinSize = 0) protected
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory. Guarantees space for at least one more element, or MinSize more elements if specified.
Definition at line 479 of file SmallVector.h.
Referenced by cloudViewer::core::SmallVectorTemplateBase< T, true >::growAndAssign(), cloudViewer::core::SmallVectorImpl< T >::operator=(), and cloudViewer::core::SmallVectorImpl< T >::reserve().
growAndAssign()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> void cloudViewer::core::SmallVectorTemplateBase< T, bool >::growAndAssign (size_t NumElts, const T & Elt) inline protected
Definition at line 435 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::destroy_range(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::mallocForGrow(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::takeAllocationForGrow().
Referenced by cloudViewer::core::SmallVectorImpl< T >::assign().
growAndEmplaceBack()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> template<typename... ArgTypes> T& cloudViewer::core::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack (ArgTypes &&... Args) inline protected
Definition at line 446 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::back(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::mallocForGrow(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::moveElementsForGrow(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::takeAllocationForGrow().
Referenced by cloudViewer::core::SmallVectorImpl< T >::emplace_back().
mallocForGrow()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> T* cloudViewer::core::SmallVectorTemplateBase< T, bool >::mallocForGrow (size_t MinSize, size_t & NewCapacity) inline protected
Create a new allocation big enough for MinSize and pass back its size in NewCapacity. This is the first section of grow().
Definition at line 406 of file SmallVector.h.
Referenced by cloudViewer::core::SmallVectorTemplateBase< T, bool >::growAndAssign(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack().
moveElementsForGrow()
template<typename T , bool TriviallyCopyable> void cloudViewer::core::SmallVectorTemplateBase< T, TriviallyCopyable >::moveElementsForGrow (T * NewElts) protected
Move existing elements over to the new allocation NewElts, the middle section of grow().
Definition at line 488 of file SmallVector.h.
Referenced by cloudViewer::core::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack().
pop_back()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> void cloudViewer::core::SmallVectorTemplateBase< T, bool >::pop_back () inline
Definition at line 471 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size().
Referenced by cloudViewer::t::geometry::RaycastingScene::CastRays(), cloudViewer::t::geometry::RaycastingScene::ComputeClosestPoints(), cloudViewer::t::geometry::RaycastingScene::ComputeDistance(), cloudViewer::t::geometry::RaycastingScene::ComputeSignedDistance(), cloudViewer::t::geometry::RaycastingScene::CountIntersections(), cloudViewer::core::SmallVectorImpl< T >::erase(), cloudViewer::t::geometry::RaycastingScene::ListIntersections(), cloudViewer::core::SmallVectorImpl< T >::pop_back_val(), and cloudViewer::t::geometry::RaycastingScene::TestOcclusions().
push_back() [1/2]
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> void cloudViewer::core::SmallVectorTemplateBase< T, bool >::push_back (const T & Elt) inline
Definition at line 459 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size().
Referenced by cloudViewer::core::ConcatenateImpl(), cloudViewer::core::Tensor::Flatten(), cloudViewer::core::SmallVectorTemplateBase< T, true >::growAndEmplaceBack(), cloudViewer::core::kernel::IndexAdd_(), cloudViewer::t::io::ParsePropertyDict(), and cloudViewer::core::AdvancedIndexPreprocessor::RunPreprocess().
push_back() [2/2]
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> void cloudViewer::core::SmallVectorTemplateBase< T, bool >::push_back (T && Elt) inline
Definition at line 465 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and cloudViewer::core::SmallVectorBase< SmallVectorSizeType< T > >::size().
reserveForParamAndGetAddress() [1/2]
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> const T* cloudViewer::core::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress (const T & Elt, size_t N = 1) inline protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 421 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::reserveForParamAndGetAddressImpl().
Referenced by cloudViewer::core::SmallVectorImpl< T >::append(), cloudViewer::core::SmallVectorImpl< T >::insert(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::push_back(), and cloudViewer::core::SmallVectorTemplateBase< T, true >::push_back().
reserveForParamAndGetAddress() [2/2]
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> T* cloudViewer::core::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress (T & Elt, size_t N = 1) inline protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 427 of file SmallVector.h.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::reserveForParamAndGetAddressImpl().
takeAllocationForGrow()
template<typename T , bool TriviallyCopyable> void cloudViewer::core::SmallVectorTemplateBase< T, TriviallyCopyable >::takeAllocationForGrow (T * NewElts, size_t NewCapacity) protected
Transfer ownership of the allocation, finishing up grow().
Definition at line 499 of file SmallVector.h.
Referenced by cloudViewer::core::SmallVectorTemplateBase< T, bool >::growAndAssign(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack().
uninitialized_copy()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> template<typename It1 , typename It2 > static void cloudViewer::core::SmallVectorTemplateBase< T, bool >::uninitialized_copy (It1 I, It1 E, It2 Dest) inline static protected
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
Definition at line 395 of file SmallVector.h.
Referenced by cloudViewer::core::SmallVectorImpl< T >::append(), cloudViewer::core::SmallVectorImpl< T >::insert(), cloudViewer::core::SmallVectorImpl< T >::operator=(), cloudViewer::core::SmallVectorImpl< T >::swap(), and cloudViewer::core::SmallVectorTemplateBase< T, true >::uninitialized_move().
uninitialized_move()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> template<typename It1 , typename It2 > static void cloudViewer::core::SmallVectorTemplateBase< T, bool >::uninitialized_move (It1 I, It1 E, It2 Dest) inline static protected
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
Definition at line 387 of file SmallVector.h.
Referenced by cloudViewer::core::SmallVectorImpl< T >::insert(), and cloudViewer::core::SmallVectorImpl< T >::operator=().
Member Data Documentation
TakesParamByValue
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> constexpr bool cloudViewer::core::SmallVectorTemplateBase< T, bool >::TakesParamByValue = false static constexpr protected
Definition at line 372 of file SmallVector.h.
Referenced by cloudViewer::core::SmallVectorImpl< T >::insert().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/SmallVector.h