ACloudViewer: cloudViewer::data::DemoDopplerICPSequence Class Reference
cloudViewer::data::DemoDopplerICPSequence Class Reference
Data class for DemoDopplerICPSequence contains an example sequence of 100 point clouds with Doppler velocity channel and corresponding ground truth poses. The sequence was generated using the CARLA simulator.
#include <Dataset.h>
Public Member Functions
DemoDopplerICPSequence (const std::string &data_root="")
std::vector< std::string > GetPaths () const
Returns the list of the point cloud paths in the sequence.
std::string GetPath (std::size_t index) const
Path to the point cloud at index.
std::string GetCalibrationPath () const
Path to the calibration metadata file, containing transformation between the vehicle and sensor frames and the time period.
std::string GetTrajectoryPath () const
Path to the ground truth poses for the entire sequence.
bool GetCalibration (Eigen::Matrix4d &calibration, double &period) const
Returns the vehicle to sensor calibration transformation and the time period (in secs) between sequential point cloud scans.
std::vector< std::pair< double, Eigen::Matrix4d > > GetTrajectory () const
Returns a list of (timestamp, pose) representing the ground truth trajectory of the sequence.
Public Member Functions inherited from cloudViewer::data::DownloadDataset
DownloadDataset (const std::string &prefix, const DataDescriptor &data_descriptor, const std::string &data_root="")
DownloadDataset (const std::string &prefix, const std::vector< DataDescriptor > &data_descriptors, const std::string &data_root="")
virtual ~DownloadDataset ()
Public Member Functions inherited from cloudViewer::data::Dataset
Dataset (const std::string &prefix, const std::string &data_root="")
Parameterized Constructor.
virtual ~Dataset ()
const std::string GetDataRoot () const
Get data root directory. The data root is set at construction time or automatically determined.
const std::string GetPrefix () const
Get prefix for the dataset.
const std::string GetDownloadDir () const
Get absolute path to download directory. i.e. ${data_root}/download/${prefix}.
const std::string GetExtractDir () const
Get absolute path to extract directory. i.e. ${data_root}/extract/${prefix}.
Additional Inherited Members
Protected Member Functions inherited from cloudViewer::data::DownloadDataset
bool HasDownloaded (const DataDescriptor &data_descriptor) const
Check if all files are downloaded and MD5 checksums are valid.
Protected Member Functions inherited from cloudViewer::data::Dataset
void CheckPathsExist (const std::vector< std::string > &paths) const
Check if the paths exists after extraction.
Protected Attributes inherited from cloudViewer::data::DownloadDataset
std::vector< DataDescriptor > data_descriptors_
Protected Attributes inherited from cloudViewer::data::Dataset
std::string data_root_
CloudViewer data root.
std::string prefix_
Dataset prefix.
Detailed Description
Data class for DemoDopplerICPSequence contains an example sequence of 100 point clouds with Doppler velocity channel and corresponding ground truth poses. The sequence was generated using the CARLA simulator.
Definition at line 355 of file Dataset.h.
Constructor & Destructor Documentation
DemoDopplerICPSequence()
cloudViewer::data::DemoDopplerICPSequence::DemoDopplerICPSequence (const std::string & data_root = "")
Definition at line 78 of file DemoDopplerICPSequence.cpp.
References cloudViewer::data::Dataset::GetExtractDir().
Member Function Documentation
GetCalibration()
bool cloudViewer::data::DemoDopplerICPSequence::GetCalibration (Eigen::Matrix4d & calibration, double & period) const
Returns the vehicle to sensor calibration transformation and the time period (in secs) between sequential point cloud scans.
Definition at line 100 of file DemoDopplerICPSequence.cpp.
References cloudViewer::utility::IJsonConvertible::EigenMatrix4dFromJsonArray(), and Value.
Referenced by cloudViewer::t::pipelines::registration::BenchmarkDopplerICP().
GetCalibrationPath()
std::string cloudViewer::data::DemoDopplerICPSequence::GetCalibrationPath () const inline
Path to the calibration metadata file, containing transformation between the vehicle and sensor frames and the time period.
Definition at line 365 of file Dataset.h.
GetPath()
std::string cloudViewer::data::DemoDopplerICPSequence::GetPath (std::size_t index) const
Path to the point cloud at index.
Definition at line 91 of file DemoDopplerICPSequence.cpp.
References LogError.
Referenced by cloudViewer::t::pipelines::registration::BenchmarkDopplerICP().
GetPaths()
std::vector<std::string> cloudViewer::data::DemoDopplerICPSequence::GetPaths () const inline
Returns the list of the point cloud paths in the sequence.
Definition at line 360 of file Dataset.h.
GetTrajectory()
std::vector< std::pair< double, Eigen::Matrix4d > > cloudViewer::data::DemoDopplerICPSequence::GetTrajectory () const
Returns a list of (timestamp, pose) representing the ground truth trajectory of the sequence.
Definition at line 116 of file DemoDopplerICPSequence.cpp.
GetTrajectoryPath()
std::string cloudViewer::data::DemoDopplerICPSequence::GetTrajectoryPath () const inline
Path to the ground truth poses for the entire sequence.
Definition at line 367 of file Dataset.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/data/Dataset.h
/root/ACloudViewer/libs/cloudViewer/data/dataset/DemoDopplerICPSequence.cpp