ACloudViewer: FBXFilter Class Reference
FBXFilter Class Reference
Autodesk FBX format I/O filter.
#include <FBXFilter.h>
Public Member Functions
FBXFilter ()
CC_FILE_ERROR loadFile (const QString &filename, ccHObject &container, LoadParameters &parameters) override
Loads one or more entities from a file.
bool canSave (CV_CLASS_ENUM type, bool &multiple, bool &exclusive) const override
Returns whether this I/O filter can save the specified type of entity.
CC_FILE_ERROR saveToFile (ccHObject *entity, const QString &filename, const SaveParameters &parameters) override
Saves an entity (or a group of) to a file.
Public Member Functions inherited from FileIOFilter
virtual ~FileIOFilter ()=default
bool importSupported () const
Returns whether this I/O filter can import files.
bool exportSupported () const
Returns whether this I/O filter can export files.
const QStringList & getFileFilters (bool onImport) const
Returns the file filter(s) for this I/O filter.
QString getDefaultExtension () const
Returns the default file extension.
virtual void unregister ()
Called when the filter is unregistered.
Static Public Member Functions
static void SetDefaultOutputFormat (QString format)
Static Public Member Functions inherited from FileIOFilter
static QStringList ImportFilterList ()
static ccHObject * LoadFromFile (const QString &filename, LoadParameters &parameters, Shared filter, CC_FILE_ERROR &result)
Loads one or more entities from a file with a known filter.
static ccHObject * LoadFromFile (const QString &filename, LoadParameters &parameters, CC_FILE_ERROR &result, const QString &fileFilter=QString())
Loads one or more entities from a file with known type.
static CC_FILE_ERROR SaveToFile (ccHObject *entities, const QString &filename, const SaveParameters &parameters, Shared filter)
static CC_FILE_ERROR SaveToFile (ccHObject *entities, const QString &filename, const SaveParameters &parameters, const QString &fileFilter)
static bool HandleGlobalShift (const CCVector3d &P, CCVector3d &Pshift, bool &preserveCoordinateShift, LoadParameters &loadParameters, bool useInputCoordinatesShiftIfPossible=false)
Shortcut to the ecvGlobalShiftManager mechanism specific for files.
static void DisplayErrorMessage (CC_FILE_ERROR err, const QString &action, const QString &filename)
Displays (to console) the message corresponding to a given error code.
static bool CheckForSpecialChars (const QString &filename)
Returns whether special characters are present in the input string.
static void ResetSesionCounter ()
static unsigned IncreaseSesionCounter ()
static void Register (Shared filter)
Registers a new filter.
static Shared GetFilter (const QString &fileFilter, bool onImport)
Returns the filter corresponding to the given 'file filter'.
static Shared FindBestFilterForExtension (const QString &ext)
Returns the best filter (presumably) to open a given file extension.
static const FilterContainer & GetFilters ()
Returns the set of all registered filters.
static void UnregisterAll ()
Unregisters all filters.
Additional Inherited Members
Public Types inherited from FileIOFilter
enum FilterFeature {
NoFeatures = 0x0000 , Import = 0x00001 , Export = 0x0002 , BuiltIn = 0x0004 ,
DynamicInfo = 0x0008
}
using Shared = QSharedPointer< FileIOFilter >
Shared type.
using FilterContainer = std::vector< FileIOFilter::Shared >
Type of a I/O filters container.
Protected Member Functions inherited from FileIOFilter
FileIOFilter (const FilterInfo &info)
void setImportExtensions (const QStringList &extensions)
void setImportFileFilterStrings (const QStringList &filterStrings)
void setExportFileFilterStrings (const QStringList &filterStrings)
Static Protected Attributes inherited from FileIOFilter
static constexpr float DEFAULT_PRIORITY = 25.0f
Detailed Description
Autodesk FBX format I/O filter.
http://www.autodesk.com/products/fbx/overview
Definition at line 15 of file FBXFilter.h.
Constructor & Destructor Documentation
FBXFilter()
FBXFilter::FBXFilter ()
Definition at line 33 of file FBXFilter.cpp.
References FileIOFilter::Export, and FileIOFilter::Import.
Member Function Documentation
canSave()
bool FBXFilter::canSave (CV_CLASS_ENUM type, bool & multiple, bool & exclusive) const override virtual
Returns whether this I/O filter can save the specified type of entity.
Parameters
type entity type
multiple whether the filter can save multiple instances of this entity at once
exclusive whether the filter can only save this type of entity if selected or if it can be mixed with other types
Returns
whether the entity type can be saved
Reimplemented from FileIOFilter.
Definition at line 39 of file FBXFilter.cpp.
References CV_TYPES::MESH, and type.
loadFile()
CC_FILE_ERROR FBXFilter::loadFile (const QString & filename, ccHObject & container, LoadParameters & parameters) override virtual
Loads one or more entities from a file.
This method must be implemented by children classes.
Parameters
filename file to load
container container to store loaded entities
parameters generic loading parameters
Returns
error
Reimplemented from FileIOFilter.
Definition at line 1349 of file FBXFilter.cpp.
References ccHObject::addChild(), ccHObject::applyGLTransformation_recursive(), CC_FERR_CONSOLE_ERROR, CC_FERR_NO_ERROR, CC_FERR_NO_LOAD, CC_FERR_THIRD_PARTY_LIB_EXCEPTION, FileIOFilter::CheckForSpecialChars(), ccGLMatrixTpl< T >::data(), data, FBX_SCALE_METADATA_KEY, filename, FromFbxMesh(), GetAttributeTypeName(), ccHObject::getChildrenNumber(), ccObject::getName(), CVLog::Print(), ccHObject::resetGLTransformationHistory_recursive(), result, ccObject::setMetaData(), ccObject::setName(), type, and CVLog::Warning().
saveToFile()
CC_FILE_ERROR FBXFilter::saveToFile (ccHObject * entity, const QString & filename, const SaveParameters & parameters) override virtual
Saves an entity (or a group of) to a file.
This method must be implemented by children classes.
Parameters
entity entity (or group of) to save
filename filename
parameters generic saving parameters
Returns
error
Reimplemented from FileIOFilter.
Definition at line 469 of file FBXFilter.cpp.
References CC_FERR_BAD_ARGUMENT, CC_FERR_CONSOLE_ERROR, CC_FERR_NO_ERROR, CC_FERR_NO_SAVE, CC_FERR_THIRD_PARTY_LIB_EXCEPTION, FileIOFilter::CheckForSpecialChars(), FBX_SCALE_METADATA_KEY, filename, ccHObject::getChild(), ccHObject::getChildrenNumber(), ccObject::getMetaData(), ccObject::hasMetaData(), CV_TYPES::HIERARCHY_OBJECT, ccObject::isA(), ccObject::isKindOf(), CV_TYPES::MESH, CVLog::Print(), s_defaultOutputFormat, SanitizeFBXFormatString(), SaveScene(), ToFbxMesh(), and CVLog::Warning().
SetDefaultOutputFormat()
void FBXFilter::SetDefaultOutputFormat (QString format) static
Sets default output format (will prevent the dialog to appear when saving FBX files)
Definition at line 457 of file FBXFilter.cpp.
References format, and s_defaultOutputFormat.
Referenced by FBXCommand::process().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qFBXIO/include/FBXFilter.h
/root/ACloudViewer/plugins/core/IO/qFBXIO/src/FBXFilter.cpp