ACloudViewer: CSF Class Reference
CSF Class Reference
#include <CSF.h>
Classes
struct Parameters
Public Member Functions
CSF (wl::PointCloud &cloud)
virtual ~CSF ()
bool readPointsFromFile (std::string filename)
void saveGroundPoints (const std::vector< int > &grp, std::string path="")
void saveOffGroundPoints (const std::vector< int > &grp, std::string path="")
bool do_filtering (std::vector< int > &groundIndexes, std::vector< int > &offGroundIndexes, bool exportClothMesh, ccMesh *&clothMesh, ecvMainAppInterface *app=0, QWidget *parent=0)
Public Attributes
Parameters params
Detailed Description
Definition at line 21 of file CSF.h.
Constructor & Destructor Documentation
CSF()
CSF::CSF (wl::PointCloud & cloud)
Definition at line 30 of file CSF.cpp.
References CSF::Parameters::bSloopSmooth, CSF::Parameters::class_threshold, CSF::Parameters::cloth_resolution, CSF::Parameters::iterations, CSF::Parameters::k_nearest_points, params, CSF::Parameters::rigidness, and CSF::Parameters::time_step.
~CSF()
CSF::~CSF () virtual
Definition at line 40 of file CSF.cpp.
Member Function Documentation
do_filtering()
bool CSF::do_filtering (std::vector< int > & groundIndexes, std::vector< int > & offGroundIndexes, bool exportClothMesh, ccMesh *& clothMesh, ecvMainAppInterface * app = 0, QWidget * parent = 0)
Definition at line 73 of file CSF.cpp.
References Cloth::addForce(), CSF::Parameters::bSloopSmooth, CSF::Parameters::class_threshold, CSF::Parameters::cloth_resolution, Cloud2CloudDist::Compute(), wl::PointCloud::computeBoundingBox(), ecvMainAppInterface::dispToConsole(), cloudViewer::utility::floor(), Cloth::getHeightvals(), CSF::Parameters::iterations, CSF::Parameters::k_nearest_points, Cloth::movableFilter(), Cloth::num_particles_height, Cloth::num_particles_width, params, Rasterization::RasterTerrain(), result, CSF::Parameters::rigidness, Cloth::terrainCollision(), CSF::Parameters::time_step, Cloth::timeStep(), Cloth::toMesh(), wl::Point::x, wl::Point::y, and wl::Point::z.
Referenced by qCSF::doAction(), and CommandCSF::process().
readPointsFromFile()
bool CSF::readPointsFromFile (std::string filename)
Definition at line 42 of file CSF.cpp.
References filename.
saveGroundPoints()
void CSF::saveGroundPoints (const std::vector< int > & grp, std::string path = "")
Definition at line 211 of file CSF.cpp.
References cloudViewer::t::geometry::path.
saveOffGroundPoints()
void CSF::saveOffGroundPoints (const std::vector< int > & grp, std::string path = "")
Definition at line 228 of file CSF.cpp.
References cloudViewer::t::geometry::path.
Member Data Documentation
params
Parameters CSF::params
Definition at line 63 of file CSF.h.
Referenced by CSF(), do_filtering(), qCSF::doAction(), and CommandCSF::process().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCSF/include/CSF.h
/root/ACloudViewer/plugins/core/Standard/qCSF/src/CSF.cpp