ACloudViewer: cloudViewer::visualization::gui::Horiz Class Reference
cloudViewer::visualization::gui::Horiz Class Reference
Lays out widgets horizontally.
#include <Layout.h>
Public Member Functions
Horiz ()
Horiz (int spacing, const Margins &margins=Margins())
Horiz (int spacing, const Margins &margins, const std::vector< std::shared_ptr< Widget >> &children)
~Horiz ()
int GetPreferredHeight () const
void SetPreferredHeight (int h)
Public Member Functions inherited from cloudViewer::visualization::gui::Layout1D
Layout1D (Dir dir, int spacing, const Margins &margins, const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Layout1D ()
int GetSpacing () const
const Margins & GetMargins () const
void SetSpacing (int spacing)
void SetMargins (const Margins &margins)
Size CalcPreferredSize (const LayoutContext &context, const Constraints &constraints) const override
void Layout (const LayoutContext &context) override
void AddFixed (int size)
Adds a fixed number of pixels after the previously added widget.
void AddStretch ()
Public Member Functions inherited from cloudViewer::visualization::gui::Widget
Widget ()
Widget (const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Widget ()
virtual void AddChild (std::shared_ptr< Widget > child)
virtual const std::vector< std::shared_ptr< Widget > > GetChildren () const
virtual const Rect & GetFrame () const
Returns the frame size in pixels.
virtual void SetFrame (const Rect &f)
virtual const Color & GetBackgroundColor () const
virtual bool IsDefaultBackgroundColor () const
virtual void SetBackgroundColor (const Color &color)
virtual bool IsVisible () const
virtual void SetVisible (bool vis)
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
virtual void SetTooltip (const char *text)
virtual const char * GetTooltip () const
virtual Size CalcMinimumSize (const LayoutContext &context) const
virtual DrawResult Draw (const DrawContext &context)
virtual EventResult Mouse (const MouseEvent &e)
virtual EventResult Key (const KeyEvent &e)
virtual DrawResult Tick (const TickEvent &e)
Static Public Member Functions
static std::shared_ptr< Layout1D::Fixed > MakeFixed (int size)
static std::shared_ptr< Layout1D::Stretch > MakeStretch ()
static std::shared_ptr< Horiz > MakeCentered (std::shared_ptr< Widget > w)
Static Public Member Functions inherited from cloudViewer::visualization::gui::Layout1D
static void debug_PrintPreferredSizes (Layout1D *layout, const LayoutContext &context, const Constraints &constraints, int depth=0)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::gui::Layout1D
enum Dir { VERT , HORIZ }
Public Types inherited from cloudViewer::visualization::gui::Widget
enum class DrawResult { NONE , REDRAW , RELAYOUT }
enum class EventResult { IGNORED , CONSUMED , DISCARD }
Static Public Attributes inherited from cloudViewer::visualization::gui::Widget
static constexpr int DIM_GROW = 10000
Protected Member Functions inherited from cloudViewer::visualization::gui::Layout1D
int GetMinorAxisPreferredSize () const
void SetMinorAxisPreferredSize (int size)
Margins & GetMutableMargins ()
Protected Member Functions inherited from cloudViewer::visualization::gui::Widget
void DrawImGuiPushEnabledState ()
void DrawImGuiPopEnabledState ()
void DrawImGuiTooltip ()
Detailed Description
Lays out widgets horizontally.
Definition at line 188 of file Layout.h.
Constructor & Destructor Documentation
Horiz() [1/3]
cloudViewer::visualization::gui::Horiz::Horiz ()
Definition at line 538 of file Layout.cpp.
Horiz() [2/3]
cloudViewer::visualization::gui::Horiz::Horiz (int spacing, const Margins & margins = Margins())
Spacing is in pixels; see the comment in Margin(). 1em is typically a good value for spacing.
Definition at line 540 of file Layout.cpp.
Horiz() [3/3]
cloudViewer::visualization::gui::Horiz::Horiz (int spacing, const Margins & margins, const std::vector< std::shared_ptr< Widget >> & children)
Definition at line 543 of file Layout.cpp.
~Horiz()
cloudViewer::visualization::gui::Horiz::~Horiz ()
Definition at line 548 of file Layout.cpp.
Member Function Documentation
GetPreferredHeight()
int cloudViewer::visualization::gui::Horiz::GetPreferredHeight () const
Definition at line 550 of file Layout.cpp.
References cloudViewer::visualization::gui::Layout1D::GetMinorAxisPreferredSize().
MakeCentered()
std::shared_ptr< Horiz > cloudViewer::visualization::gui::Horiz::MakeCentered (std::shared_ptr< Widget > w) static
Definition at line 531 of file Layout.cpp.
References MakeStretch().
Referenced by cloudViewer::visualization::gui::FileDialog::FileDialog(), cloudViewer::visualization::gui::Application::ShowMessageBox(), and cloudViewer::visualization::gui::Window::ShowMessageBox().
MakeFixed()
std::shared_ptr< Layout1D::Fixed > cloudViewer::visualization::gui::Horiz::MakeFixed (int size) static
Definition at line 523 of file Layout.cpp.
References cloudViewer::visualization::gui::Layout1D::HORIZ, and size.
MakeStretch()
std::shared_ptr< Layout1D::Stretch > cloudViewer::visualization::gui::Horiz::MakeStretch () static
Definition at line 527 of file Layout.cpp.
Referenced by MakeCentered().
SetPreferredHeight()
void cloudViewer::visualization::gui::Horiz::SetPreferredHeight (int h)
Definition at line 551 of file Layout.cpp.
References cloudViewer::visualization::gui::Layout1D::SetMinorAxisPreferredSize().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Layout.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Layout.cpp