ACloudViewer: QCPItemPixmap Class Reference
QCPItemPixmap Class Reference
An arbitrary pixmap.
#include <qcustomplot.h>
Public Member Functions
QCPItemPixmap (QCustomPlot *parentPlot)
virtual ~QCPItemPixmap ()
QPixmap pixmap () const
bool scaled () const
Qt::AspectRatioMode aspectRatioMode () const
Qt::TransformationMode transformationMode () const
QPen pen () const
QPen selectedPen () const
void setPixmap (const QPixmap &pixmap)
void setScaled (bool scaled, Qt::AspectRatioMode aspectRatioMode=Qt::KeepAspectRatio, Qt::TransformationMode transformationMode=Qt::SmoothTransformation)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
QCPItemPixmap (QCustomPlot *parentPlot)
virtual ~QCPItemPixmap ()
QPixmap pixmap () const
bool scaled () const
Qt::AspectRatioMode aspectRatioMode () const
Qt::TransformationMode transformationMode () const
QPen pen () const
QPen selectedPen () const
void setPixmap (const QPixmap &pixmap)
void setScaled (bool scaled, Qt::AspectRatioMode aspectRatioMode=Qt::KeepAspectRatio, Qt::TransformationMode transformationMode=Qt::SmoothTransformation)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractItem
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
virtual ~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Public Attributes
QCPItemPosition *const topLeft
QCPItemPosition *const bottomRight
QCPItemAnchor *const top
QCPItemAnchor *const topRight
QCPItemAnchor *const right
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeft
QCPItemAnchor *const left
Protected Types
enum AnchorIndex {
aiTop , aiTopRight , aiRight , aiBottom ,
aiBottomLeft , aiLeft , aiTop , aiTopRight ,
aiRight , aiBottom , aiBottomLeft , aiLeft
}
enum AnchorIndex {
aiTop , aiTopRight , aiRight , aiBottom ,
aiBottomLeft , aiLeft , aiTop , aiTopRight ,
aiRight , aiBottom , aiBottomLeft , aiLeft
}
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPosition (int anchorId) const
void updateScaledPixmap (QRect finalRect=QRect(), bool flipHorz=false, bool flipVert=false)
QRect getFinalRect (bool *flippedHorz=0, bool *flippedVert=0) const
QPen mainPen () const
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
void updateScaledPixmap (QRect finalRect=QRect(), bool flipHorz=false, bool flipVert=false)
QRect getFinalRect (bool *flippedHorz=0, bool *flippedVert=0) const
QPen mainPen () const
Protected Member Functions inherited from QCPAbstractItem
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double rectDistance (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual void mousePressEvent (QMouseEvent *event, const QVariant &details)
virtual void mouseMoveEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseReleaseEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseDoubleClickEvent (QMouseEvent *event, const QVariant &details)
virtual void wheelEvent (QWheelEvent *event)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QPixmap mPixmap
QPixmap mScaledPixmap
bool mScaled
bool mScaledPixmapInvalidated
Qt::AspectRatioMode mAspectRatioMode
Qt::TransformationMode mTransformationMode
QPen mPen
QPen mSelectedPen
Protected Attributes inherited from QCPAbstractItem
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractItem
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
void layerChanged (QCPLayer *newLayer)
Detailed Description
An arbitrary pixmap.
Pixmap example. Blue dotted circles are
anchors, solid blue discs are positions."
It has two positions, topLeft and bottomRight, which define the rectangle the pixmap will be drawn in. Depending on the scale setting (setScaled), the pixmap will be either scaled to fit the rectangle or be drawn aligned to the topLeft position.
If scaling is enabled and topLeft is further to the bottom/right than bottomRight (as shown on the right side of the example image), the pixmap will be flipped in the respective orientations.
Definition at line 7618 of file qcustomplot.h.
Member Enumeration Documentation
AnchorIndex [1/2]
enum QCPItemPixmap::AnchorIndex protected
Enumerator
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 7667 of file qcustomplot.h.
AnchorIndex [2/2]
enum QCPItemPixmap::AnchorIndex protected
Enumerator
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 4301 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemPixmap() [1/2]
QCPItemPixmap::QCPItemPixmap (QCustomPlot * parentPlot) explicit
Creates a rectangle item and sets default values.
The created item is automatically registered with parentPlot. This QCustomPlot instance takes ownership of the item, so do not delete it manually but use QCustomPlot::removeItem() instead.
Creates a rectangle item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 31229 of file qcustomplot.cpp.
References ecvColor::blue(), bottomRight, QCPItemPosition::setCoords(), setPen(), setSelectedPen(), and topLeft.
~QCPItemPixmap() [1/2]
QCPItemPixmap::~QCPItemPixmap () virtual
Definition at line 31250 of file qcustomplot.cpp.
QCPItemPixmap() [2/2]
QCPItemPixmap::QCPItemPixmap (QCustomPlot * parentPlot)
~QCPItemPixmap() [2/2]
virtual QCPItemPixmap::~QCPItemPixmap () virtual
Member Function Documentation
anchorPixelPoint()
QPointF QCPItemPixmap::anchorPixelPoint (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 24041 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiLeft, aiRight, aiTop, aiTopRight, and getFinalRect().
anchorPixelPosition()
QPointF QCPItemPixmap::anchorPixelPosition (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 31319 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiLeft, aiRight, aiTop, aiTopRight, and getFinalRect().
aspectRatioMode() [1/2]
Qt::AspectRatioMode QCPItemPixmap::aspectRatioMode () const inline
Definition at line 7636 of file qcustomplot.h.
Referenced by setScaled().
aspectRatioMode() [2/2]
Qt::AspectRatioMode QCPItemPixmap::aspectRatioMode () const inline
Definition at line 4270 of file qcustomplot.h.
draw() [1/2]
void QCPItemPixmap::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
Definition at line 31300 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), getFinalRect(), mainPen(), mPixmap, mScaled, mScaledPixmap, pen(), QCPPainter::setPen(), and updateScaledPixmap().
draw() [2/2]
virtual void QCPItemPixmap::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
getFinalRect() [1/2]
QRect QCPItemPixmap::getFinalRect (bool * flippedHorz = 0, bool * flippedVert = 0) const protected
Definition at line 31406 of file qcustomplot.cpp.
References bottomRight, mAspectRatioMode, mPixmap, mScaled, QCPItemPosition::pixelPosition(), result, and topLeft.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), selectTest(), and updateScaledPixmap().
getFinalRect() [2/2]
QRect QCPItemPixmap::getFinalRect (bool * flippedHorz = 0, bool * flippedVert = 0) const protected
mainPen() [1/2]
QPen QCPItemPixmap::mainPen () const protected
Definition at line 31452 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
mainPen() [2/2]
QPen QCPItemPixmap::mainPen () const protected
pen() [1/2]
QPen QCPItemPixmap::pen () const inline
Definition at line 7640 of file qcustomplot.h.
Referenced by draw(), setPen(), and setSelectedPen().
pen() [2/2]
QPen QCPItemPixmap::pen () const inline
Definition at line 4274 of file qcustomplot.h.
pixmap() [1/2]
QPixmap QCPItemPixmap::pixmap () const inline
Definition at line 7634 of file qcustomplot.h.
Referenced by setPixmap().
pixmap() [2/2]
QPixmap QCPItemPixmap::pixmap () const inline
Definition at line 4268 of file qcustomplot.h.
scaled() [1/2]
bool QCPItemPixmap::scaled () const inline
Definition at line 7635 of file qcustomplot.h.
Referenced by setScaled().
scaled() [2/2]
bool QCPItemPixmap::scaled () const inline
Definition at line 4269 of file qcustomplot.h.
selectedPen() [1/2]
QPen QCPItemPixmap::selectedPen () const inline
Definition at line 7641 of file qcustomplot.h.
selectedPen() [2/2]
QPen QCPItemPixmap::selectedPen () const inline
Definition at line 4275 of file qcustomplot.h.
selectTest() [1/2]
double QCPItemPixmap::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 31290 of file qcustomplot.cpp.
References getFinalRect(), QCPAbstractItem::mSelectable, and QCPAbstractItem::rectDistance().
selectTest() [2/2]
virtual double QCPItemPixmap::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
setPen() [1/2]
void QCPItemPixmap::setPen (const QPen & pen)
Sets the pen that will be used to draw a border around the pixmap.
See also
setSelectedPen, setBrush
Definition at line 31279 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemPixmap().
setPen() [2/2]
void QCPItemPixmap::setPen (const QPen & pen)
setPixmap() [1/2]
void QCPItemPixmap::setPixmap (const QPixmap & pixmap)
Sets the pixmap that will be displayed.
Definition at line 31255 of file qcustomplot.cpp.
References mPixmap, mScaledPixmapInvalidated, and pixmap().
setPixmap() [2/2]
void QCPItemPixmap::setPixmap (const QPixmap & pixmap)
setScaled() [1/2]
void QCPItemPixmap::setScaled (bool scaled, Qt::AspectRatioMode aspectRatioMode = Qt::KeepAspectRatio, Qt::TransformationMode transformationMode = Qt::SmoothTransformation)
Sets whether the pixmap will be scaled to fit the rectangle defined by the topLeft and bottomRight positions.
Definition at line 31265 of file qcustomplot.cpp.
References aspectRatioMode(), mAspectRatioMode, mScaled, mScaledPixmapInvalidated, mTransformationMode, scaled(), and transformationMode().
setScaled() [2/2]
void QCPItemPixmap::setScaled (bool scaled, Qt::AspectRatioMode aspectRatioMode = Qt::KeepAspectRatio, Qt::TransformationMode transformationMode = Qt::SmoothTransformation)
setSelectedPen() [1/2]
void QCPItemPixmap::setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw a border around the pixmap when selected
See also
setPen, setSelected
Definition at line 31287 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemPixmap().
setSelectedPen() [2/2]
void QCPItemPixmap::setSelectedPen (const QPen & pen)
transformationMode() [1/2]
Qt::TransformationMode QCPItemPixmap::transformationMode () const inline
Definition at line 7637 of file qcustomplot.h.
Referenced by setScaled().
transformationMode() [2/2]
Qt::TransformationMode QCPItemPixmap::transformationMode () const inline
Definition at line 4271 of file qcustomplot.h.
updateScaledPixmap() [1/2]
void QCPItemPixmap::updateScaledPixmap (QRect finalRect = QRect(), bool flipHorz = false, bool flipVert = false) protected
Definition at line 31361 of file qcustomplot.cpp.
References getFinalRect(), mAspectRatioMode, mPixmap, mScaled, mScaledPixmap, mScaledPixmapInvalidated, and mTransformationMode.
Referenced by draw().
updateScaledPixmap() [2/2]
void QCPItemPixmap::updateScaledPixmap (QRect finalRect = QRect(), bool flipHorz = false, bool flipVert = false) protected
Member Data Documentation
bottom
QCPItemAnchor *const QCPItemPixmap::bottom
Definition at line 7662 of file qcustomplot.h.
bottomLeft
QCPItemAnchor *const QCPItemPixmap::bottomLeft
Definition at line 7663 of file qcustomplot.h.
bottomRight
QCPItemPosition *const QCPItemPixmap::bottomRight
Definition at line 7658 of file qcustomplot.h.
Referenced by getFinalRect(), and QCPItemPixmap().
left
QCPItemAnchor *const QCPItemPixmap::left
Definition at line 7664 of file qcustomplot.h.
mAspectRatioMode
Qt::AspectRatioMode QCPItemPixmap::mAspectRatioMode protected
Definition at line 7681 of file qcustomplot.h.
Referenced by getFinalRect(), setScaled(), and updateScaledPixmap().
mPen
QPen QCPItemPixmap::mPen protected
Definition at line 7683 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
mPixmap
QPixmap QCPItemPixmap::mPixmap protected
Definition at line 7677 of file qcustomplot.h.
Referenced by draw(), getFinalRect(), setPixmap(), and updateScaledPixmap().
mScaled
bool QCPItemPixmap::mScaled protected
Definition at line 7679 of file qcustomplot.h.
Referenced by draw(), getFinalRect(), setScaled(), and updateScaledPixmap().
mScaledPixmap
QPixmap QCPItemPixmap::mScaledPixmap protected
Definition at line 7678 of file qcustomplot.h.
Referenced by draw(), and updateScaledPixmap().
mScaledPixmapInvalidated
bool QCPItemPixmap::mScaledPixmapInvalidated protected
Definition at line 7680 of file qcustomplot.h.
Referenced by setPixmap(), setScaled(), and updateScaledPixmap().
mSelectedPen
QPen QCPItemPixmap::mSelectedPen protected
Definition at line 7683 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
mTransformationMode
Qt::TransformationMode QCPItemPixmap::mTransformationMode protected
Definition at line 7682 of file qcustomplot.h.
Referenced by setScaled(), and updateScaledPixmap().
right
QCPItemAnchor *const QCPItemPixmap::right
Definition at line 7661 of file qcustomplot.h.
top
QCPItemAnchor *const QCPItemPixmap::top
Definition at line 7659 of file qcustomplot.h.
topLeft
QCPItemPosition *const QCPItemPixmap::topLeft
Definition at line 7657 of file qcustomplot.h.
Referenced by getFinalRect(), and QCPItemPixmap().
topRight
QCPItemAnchor *const QCPItemPixmap::topRight
Definition at line 7660 of file qcustomplot.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp