ACloudViewer: colmap::BundleAdjuster Class Reference
colmap::BundleAdjuster Class Reference
#include <bundle_adjustment.h>
Public Member Functions
BundleAdjuster (const BundleAdjustmentOptions &options, const BundleAdjustmentConfig &config)
bool Solve (Reconstruction *reconstruction)
const ceres::Solver::Summary & Summary () const
Protected Member Functions
void ParameterizeCameras (Reconstruction *reconstruction)
void ParameterizePoints (Reconstruction *reconstruction)
Protected Attributes
const BundleAdjustmentOptions options_
BundleAdjustmentConfig config_
std::unique_ptr< ceres::Problem > problem_
ceres::Solver::Summary summary_
std::unordered_set< camera_t > camera_ids_
std::unordered_map< point3D_t, size_t > point3D_num_observations_
Detailed Description
Definition at line 172 of file bundle_adjustment.h.
Constructor & Destructor Documentation
BundleAdjuster()
colmap::BundleAdjuster::BundleAdjuster (const BundleAdjustmentOptions & options, const BundleAdjustmentConfig & config)
Definition at line 366 of file bundle_adjustment.cc.
Member Function Documentation
ParameterizeCameras()
void colmap::BundleAdjuster::ParameterizeCameras (Reconstruction * reconstruction) protected
Definition at line 572 of file bundle_adjustment.cc.
References colmap::Reconstruction::Camera(), camera_ids_, config_, colmap::Camera::ExtraParamsIdxs(), colmap::Camera::FocalLengthIdxs(), colmap::BundleAdjustmentConfig::IsConstantCamera(), colmap::Camera::NumParams(), options_, colmap::Camera::ParamsData(), colmap::Camera::PrincipalPointIdxs(), problem_, colmap::BundleAdjustmentOptions::refine_extra_params, colmap::BundleAdjustmentOptions::refine_focal_length, colmap::BundleAdjustmentOptions::refine_principal_point, and colmap::SetSubsetManifold().
ParameterizePoints()
void colmap::BundleAdjuster::ParameterizePoints (Reconstruction * reconstruction) protected
Definition at line 623 of file bundle_adjustment.cc.
References config_, colmap::BundleAdjustmentConfig::ConstantPoints(), colmap::Track::Length(), colmap::Reconstruction::Point3D(), point3D_num_observations_, problem_, colmap::Point3D::Track(), and colmap::Point3D::XYZ().
Solve()
bool colmap::BundleAdjuster::Solve (Reconstruction * reconstruction)
Definition at line 372 of file bundle_adjustment.cc.
References config_, colmap::BundleAdjustmentOptions::CreateLossFunction(), colmap::BundleAdjustmentOptions::CreateSolverOptions(), QtCompat::endl(), options_, colmap::BundleAdjustmentOptions::print_summary, colmap::PrintHeading2(), colmap::PrintSolverSummary(), problem_, cloudViewer::core::Solve(), and summary_.
Referenced by colmap::IncrementalMapper::AdjustGlobalBundle(), colmap::IncrementalMapper::AdjustLocalBundle(), BOOST_AUTO_TEST_CASE(), and colmap::RunPointTriangulator().
Summary()
const ceres::Solver::Summary & colmap::BundleAdjuster::Summary () const
Definition at line 404 of file bundle_adjustment.cc.
References summary_.
Referenced by colmap::IncrementalMapper::AdjustLocalBundle(), and BOOST_AUTO_TEST_CASE().
Member Data Documentation
camera_ids_
std::unordered_set<camera_t> colmap::BundleAdjuster::camera_ids_ protected
Definition at line 203 of file bundle_adjustment.h.
Referenced by ParameterizeCameras().
config_
BundleAdjustmentConfig colmap::BundleAdjuster::config_ protected
Definition at line 200 of file bundle_adjustment.h.
Referenced by ParameterizeCameras(), ParameterizePoints(), Solve(), and colmap::RigBundleAdjuster::Solve().
options_
const BundleAdjustmentOptions colmap::BundleAdjuster::options_ protected
Definition at line 199 of file bundle_adjustment.h.
Referenced by ParameterizeCameras(), Solve(), and colmap::RigBundleAdjuster::Solve().
point3D_num_observations_
std::unordered_map<point3D_t, size_t> colmap::BundleAdjuster::point3D_num_observations_ protected
Definition at line 204 of file bundle_adjustment.h.
Referenced by ParameterizePoints().
problem_
std::unique_ptr<ceres::Problem> colmap::BundleAdjuster::problem_ protected
Definition at line 201 of file bundle_adjustment.h.
Referenced by ParameterizeCameras(), ParameterizePoints(), Solve(), and colmap::RigBundleAdjuster::Solve().
summary_
ceres::Solver::Summary colmap::BundleAdjuster::summary_ protected
Definition at line 202 of file bundle_adjustment.h.
Referenced by Solve(), colmap::RigBundleAdjuster::Solve(), and Summary().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/optim/bundle_adjustment.h
/root/ACloudViewer/libs/Reconstruction/src/optim/bundle_adjustment.cc