ACloudViewer: ccLogger< level > Class Template Reference
ccLogger< level > Class Template Reference
#include <Utilities.h>
Public Member Functions
ccLogger ()
virtual ~ccLogger ()
ccLogger & operator<< (const QString &message)
ccLogger & operator<< (const char *message)
ccLogger & operator<< (int value)
ccLogger & operator<< (const qsizetype value)
void flush ()
Protected Attributes
QString m_message
Detailed Description
template<enum CVLog::MessageLevelFlags level>
class ccLogger< level >
Wrapper around CVLog to have a std::cout like API
Example
ccPrint() << "Message";
Definition at line 23 of file Utilities.h.
Constructor & Destructor Documentation
ccLogger()
template<enum CVLog::MessageLevelFlags level> ccLogger< level >::ccLogger () inline
Definition at line 26 of file Utilities.h.
References ccLogger< level >::m_message.
~ccLogger()
template<enum CVLog::MessageLevelFlags level> virtual ccLogger< level >::~ccLogger () inline virtual
Definition at line 31 of file Utilities.h.
References ccLogger< level >::flush().
Member Function Documentation
flush()
template<enum CVLog::MessageLevelFlags level> void ccLogger< level >::flush () inline
Definition at line 60 of file Utilities.h.
References CVLog::LogMessage(), and ccLogger< level >::m_message.
Referenced by ccLogger< level >::~ccLogger().
operator<<() [1/4]
template<enum CVLog::MessageLevelFlags level> ccLogger& ccLogger< level >::operator<< (const char * message) inline
Definition at line 42 of file Utilities.h.
References ccLogger< level >::m_message.
operator<<() [2/4]
template<enum CVLog::MessageLevelFlags level> ccLogger& ccLogger< level >::operator<< (const qsizetype value) inline
Definition at line 54 of file Utilities.h.
References ccLogger< level >::m_message.
operator<<() [3/4]
template<enum CVLog::MessageLevelFlags level> ccLogger& ccLogger< level >::operator<< (const QString & message) inline
Definition at line 36 of file Utilities.h.
References ccLogger< level >::m_message.
operator<<() [4/4]
template<enum CVLog::MessageLevelFlags level> ccLogger& ccLogger< level >::operator<< (int value) inline
Definition at line 48 of file Utilities.h.
References ccLogger< level >::m_message.
Member Data Documentation
m_message
template<enum CVLog::MessageLevelFlags level> QString ccLogger< level >::m_message protected
Definition at line 67 of file Utilities.h.
Referenced by ccLogger< level >::ccLogger(), ccLogger< level >::flush(), ccLogger< level >::operator<<(), and PluginLogger< level >::PluginLogger().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/Utilities.h