ACloudViewer: ccWaveWidget Class Reference
ccWaveWidget Class Reference
Waveform widget.
#include <ecvWaveformDialog.h>
Public Member Functions
ccWaveWidget (QWidget *parent=nullptr)
Default constructor.
~ccWaveWidget () override
Destructor.
void setTitle (const QString &str)
Sets title.
void setAxisLabels (const QString &xLabel, const QString &yLabel)
Sets axis labels.
void init (ccPointCloud *cloud, unsigned pointIndex, bool logScale, double maxValue=0.0)
Computes the wave (curve) from a given point waveform.
void clear ()
Clears the display.
void refresh ()
Updates the display.
Protected Member Functions
void mousePressEvent (QMouseEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void resizeEvent (QResizeEvent *event) override
void updateCurveWidth (int w, int h)
Updates overlay curve width depending on the widget display size.
Protected Attributes
QString m_titleStr
QCPTextElement * m_titlePlot
QCPGraph * m_curve
Wave curve.
std::vector< double > m_curveValues
double m_dt
double m_minA
double m_maxA
double m_echoPos
QCPBarsWithText * m_vertBar
bool m_drawVerticalIndicator
double m_verticalIndicatorPositionPercent
QCPBarsWithText * m_peakBar
QFont m_renderingFont
Rendering font.
QPoint m_lastMouseClick
Last mouse click.
Detailed Description
Waveform widget.
Definition at line 30 of file ecvWaveformDialog.h.
Constructor & Destructor Documentation
ccWaveWidget()
ccWaveWidget::ccWaveWidget (QWidget * parent = nullptr) explicit
Default constructor.
Definition at line 35 of file ecvWaveformDialog.cpp.
References m_renderingFont.
~ccWaveWidget()
ccWaveWidget::~ccWaveWidget () override
Destructor.
Definition at line 68 of file ecvWaveformDialog.cpp.
Member Function Documentation
clear()
void ccWaveWidget::clear (void)
Clears the display.
Definition at line 70 of file ecvWaveformDialog.cpp.
References refresh().
init()
void ccWaveWidget::init (ccPointCloud * cloud, unsigned pointIndex, bool logScale, double maxValue = 0.0)
Computes the wave (curve) from a given point waveform.
Definition at line 103 of file ecvWaveformDialog.cpp.
References AbsLog(), ccWaveformProxy::descriptor(), ccWaveformProxy::echoTime_ps(), CVLog::Error(), ccWaveformProxy::getSample(), ccPointCloud::hasFWF(), ccWaveformProxy::isValid(), m_curveValues, m_dt, m_echoPos, m_maxA, m_minA, max(), min(), ccWaveformProxy::numberOfSamples(), WaveformDescriptor::samplingRate_ps, and ccPointCloud::waveformProxy().
Referenced by ccWaveDialog::onPointIndexChanged().
mouseMoveEvent()
void ccWaveWidget::mouseMoveEvent (QMouseEvent * event) override protected
Definition at line 292 of file ecvWaveformDialog.cpp.
References event, m_curve, m_curveValues, m_drawVerticalIndicator, m_verticalIndicatorPositionPercent, and refresh().
Referenced by mousePressEvent().
mousePressEvent()
void ccWaveWidget::mousePressEvent (QMouseEvent * event) override protected
Definition at line 286 of file ecvWaveformDialog.cpp.
References event, m_lastMouseClick, and mouseMoveEvent().
refresh()
void ccWaveWidget::refresh ()
Updates the display.
Definition at line 154 of file ecvWaveformDialog.cpp.
References QCPBarsWithText::appendText(), ecvColor::blue(), height, m_curve, m_curveValues, m_drawVerticalIndicator, m_dt, m_echoPos, m_maxA, m_minA, m_peakBar, m_renderingFont, m_titlePlot, m_titleStr, m_vertBar, m_verticalIndicatorPositionPercent, ecvGui::Parameters(), ecvColor::red(), QCPBarsWithText::setText(), QCPBarsWithText::setTextAlignment(), updateCurveWidth(), and width.
Referenced by clear(), mouseMoveEvent(), ccWaveDialog::onPointIndexChanged(), and resizeEvent().
resizeEvent()
void ccWaveWidget::resizeEvent (QResizeEvent * event) override protected
Definition at line 278 of file ecvWaveformDialog.cpp.
References event, refresh(), and updateCurveWidth().
setAxisLabels()
void ccWaveWidget::setAxisLabels (const QString & xLabel, const QString & yLabel)
Sets axis labels.
Definition at line 83 of file ecvWaveformDialog.cpp.
setTitle()
void ccWaveWidget::setTitle (const QString & str)
Sets title.
Definition at line 81 of file ecvWaveformDialog.cpp.
References m_titleStr.
updateCurveWidth()
void ccWaveWidget::updateCurveWidth (int w, int h) protected
Updates overlay curve width depending on the widget display size.
Definition at line 267 of file ecvWaveformDialog.cpp.
References m_curve, and max().
Referenced by refresh(), and resizeEvent().
Member Data Documentation
m_curve
QCPGraph* ccWaveWidget::m_curve protected
Wave curve.
Definition at line 74 of file ecvWaveformDialog.h.
Referenced by mouseMoveEvent(), refresh(), and updateCurveWidth().
m_curveValues
std::vector<double> ccWaveWidget::m_curveValues protected
Definition at line 75 of file ecvWaveformDialog.h.
Referenced by init(), mouseMoveEvent(), and refresh().
m_drawVerticalIndicator
bool ccWaveWidget::m_drawVerticalIndicator protected
Definition at line 82 of file ecvWaveformDialog.h.
Referenced by mouseMoveEvent(), and refresh().
m_dt
double ccWaveWidget::m_dt protected
Definition at line 76 of file ecvWaveformDialog.h.
Referenced by init(), and refresh().
m_echoPos
double ccWaveWidget::m_echoPos protected
Definition at line 78 of file ecvWaveformDialog.h.
Referenced by init(), and refresh().
m_lastMouseClick
QPoint ccWaveWidget::m_lastMouseClick protected
Last mouse click.
Definition at line 92 of file ecvWaveformDialog.h.
Referenced by mousePressEvent().
m_maxA
double ccWaveWidget::m_maxA protected
Definition at line 77 of file ecvWaveformDialog.h.
Referenced by init(), and refresh().
m_minA
double ccWaveWidget::m_minA protected
Definition at line 77 of file ecvWaveformDialog.h.
Referenced by init(), and refresh().
m_peakBar
QCPBarsWithText* ccWaveWidget::m_peakBar protected
Definition at line 86 of file ecvWaveformDialog.h.
Referenced by refresh().
m_renderingFont
QFont ccWaveWidget::m_renderingFont protected
Rendering font.
Definition at line 89 of file ecvWaveformDialog.h.
Referenced by ccWaveWidget(), and refresh().
m_titlePlot
QCPTextElement* ccWaveWidget::m_titlePlot protected
Definition at line 71 of file ecvWaveformDialog.h.
Referenced by refresh().
m_titleStr
QString ccWaveWidget::m_titleStr protected
Definition at line 70 of file ecvWaveformDialog.h.
Referenced by refresh(), and setTitle().
m_vertBar
QCPBarsWithText* ccWaveWidget::m_vertBar protected
Definition at line 81 of file ecvWaveformDialog.h.
Referenced by refresh().
m_verticalIndicatorPositionPercent
double ccWaveWidget::m_verticalIndicatorPositionPercent protected
Definition at line 83 of file ecvWaveformDialog.h.
Referenced by mouseMoveEvent(), and refresh().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvWaveformDialog.h
/root/ACloudViewer/app/ecvWaveformDialog.cpp