ACloudViewer: colmap::CameraTab Class Reference
colmap::CameraTab Class Reference
#include <database_management_widget.h>
Public Member Functions
CameraTab (QWidget *parent, Database *database)
void Reload ()
void Clear ()
Detailed Description
Definition at line 90 of file database_management_widget.h.
Constructor & Destructor Documentation
CameraTab()
colmap::CameraTab::CameraTab (QWidget * parent, Database * database)
Definition at line 262 of file database_management_widget.cc.
Member Function Documentation
Clear()
void colmap::CameraTab::Clear ()
Definition at line 350 of file database_management_widget.cc.
Reload()
void colmap::CameraTab::Reload ()
Definition at line 303 of file database_management_widget.cc.
References colmap::Camera::CameraId(), colmap::Camera::HasPriorFocalLength(), colmap::Camera::Height(), colmap::Camera::ModelName(), colmap::Database::NumCameras(), colmap::Camera::Params(), colmap::Database::ReadAllCameras(), colmap::VectorToCSV(), and colmap::Camera::Width().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/database_management_widget.h
/root/ACloudViewer/libs/Reconstruction/src/ui/database_management_widget.cc