ACloudViewer: ecvMainAppInterface Class Reference
ecvMainAppInterface Class Reference abstract
Main application interface (for plugins)
#include <ecvMainAppInterface.h>
Classes
struct ccHObjectContext
Backup "context" for an object.
Public Types
enum ConsoleMessageLevel { STD_CONSOLE_MESSAGE = 0 , WRN_CONSOLE_MESSAGE = 1 , ERR_CONSOLE_MESSAGE = 2 }
Console message level (see dispToConsole)
Public Member Functions
virtual ~ecvMainAppInterface ()=default
virtual QMainWindow * getMainWindow ()=0
Returns main window.
virtual void registerOverlayDialog (ccOverlayDialog *dlg, Qt::Corner pos)=0
Registers a MDI area 'overlay' dialog.
virtual void unregisterOverlayDialog (ccOverlayDialog *dlg)=0
Unregisters a MDI area 'overlay' dialog.
virtual void updateOverlayDialogsPlacement ()=0
Forces the update of all registered MDI 'overlay' dialogs.
virtual ccUniqueIDGenerator::Shared getUniqueIDGenerator ()=0
Returns the unique ID generator.
virtual ccHObject * loadFile (QString filename, bool silent)=0
Attempts to load a file.
virtual void addToDB (ccHObject *obj, bool updateZoom=false, bool autoExpandDBTree=true, bool checkDimensions=false, bool autoRedraw=true)=0
virtual void removeFromDB (ccHObject *obj, bool autoDelete=true)=0
Removes an entity from main db tree.
virtual ccHObjectContext removeObjectTemporarilyFromDBTree (ccHObject *obj)=0
Removes object temporarily from DB tree.
virtual void putObjectBackIntoDBTree (ccHObject *obj, const ccHObjectContext &context)=0
Adds back object to DB tree.
virtual void setSelectedInDB (ccHObject *obj, bool selected)=0
Selects or unselects an entity (in db tree)
virtual const ccHObject::Container & getSelectedEntities () const =0
Returns currently selected entities ("read only")
bool haveSelection () const
Checks if we have any selections.
bool haveOneSelection () const
Checks if we have exactly one selection.
virtual void dispToConsole (QString message, ConsoleMessageLevel level=STD_CONSOLE_MESSAGE)=0
virtual void forceConsoleDisplay ()=0
Forces display of console widget.
virtual ccHObject * dbRootObject ()=0
Returns DB root (as a ccHObject)
virtual void refreshAll (bool only2D=false, bool forceRedraw=true)=0
Redraws all GL windows that have the 'refresh' flag on.
virtual void redrawAll (bool only2D=false, bool forceRedraw=true)
virtual void enableAll ()=0
Enables all windows.
virtual void disableAll ()=0
Disables all windows.
virtual void refreshSelected (bool only2D=false, bool forceRedraw=true)=0
virtual void refreshObject (ccHObject *obj, bool only2D=false, bool forceRedraw=true)=0
virtual void refreshObjects (ccHObject::Container objs, bool only2D=false, bool forceRedraw=true)=0
virtual void resetSelectedBBox ()=0
virtual void updateUI ()=0
virtual void freezeUI (bool state)=0
Freezes/unfreezes UI.
virtual ccColorScalesManager * getColorScalesManager ()=0
Returns color scale manager (unique instance)
virtual void spawnHistogramDialog (const std::vector< unsigned > &histoValues, double minVal, double maxVal, QString title, QString xAxisLabel)=0
virtual ccPickingHub * pickingHub ()
virtual void setView (CC_VIEW_ORIENTATION view)=0
virtual void toggleActiveWindowCenteredPerspective ()=0
virtual void toggleActiveWindowViewerBasedPerspective ()=0
virtual void zoomOnSelectedEntities ()=0
virtual void zoomOnEntities (ccHObject *obj)=0
virtual void setGlobalZoom ()=0
virtual void increasePointSize ()=0
virtual void decreasePointSize ()=0
virtual void addWidgetToQMdiArea (QWidget *viewWidget)=0
virtual QWidget * getActiveWindow ()=0
virtual void toggleExclusiveFullScreen (bool state)=0
virtual void toggle3DView (bool state)=0
Detailed Description
Main application interface (for plugins)
Definition at line 24 of file ecvMainAppInterface.h.
Member Enumeration Documentation
ConsoleMessageLevel
enum ecvMainAppInterface::ConsoleMessageLevel
Console message level (see dispToConsole)
Enumerator
STD_CONSOLE_MESSAGE
WRN_CONSOLE_MESSAGE
ERR_CONSOLE_MESSAGE
Definition at line 116 of file ecvMainAppInterface.h.
Constructor & Destructor Documentation
~ecvMainAppInterface()
virtual ecvMainAppInterface::~ecvMainAppInterface () virtual default
Member Function Documentation
addToDB()
virtual void ecvMainAppInterface::addToDB (ccHObject * obj, bool updateZoom = false, bool autoExpandDBTree = true, bool checkDimensions = false, bool autoRedraw = true) pure virtual
Implemented in MainWindow.
Referenced by ccMeasurementRecorder::addFittingPoint(), ccCompass::addGeoObject(), ccMeasurementRecorder::addMeasurementPoint(), ccGraphicalSegmentationTool::applySegmentation(), qCanupoProcess::Classify(), qFacets::classifyFacetsByAngle(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), qSRA::computeCloud2ProfileRadialDist(), ccCompass::convertToPointCloud(), ccCompass::distributeSelection(), qCork::doAction(), qCSF::doAction(), qPoissonRecon::doAction(), qRansacSD::doAction(), qCanupoPlugin::doClassifyAction(), q3DMASCPlugin::doTrainAction(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), JsonRPCPlugin::execute(), StereogramDialog::exportCurrentSelection(), DistanceMapGenerationDlg::exportMapAsCloud(), DistanceMapGenerationDlg::exportMapAsMesh(), GrainsAsEllipsoids::exportResultsAsCloud(), qFacets::extractFacets(), CC_ITEM_TREE::findOrCreateContainer(), ccTraceTool::finishCurrentTrace(), G3Point::G3PointAction::fit(), ccCompass::fitPlaneToGeoObject(), G3Point::G3PointAction::getBorders(), GetDefaultContainer(), ccCompass::getInsertPoint(), qM3C2Tools::GuessBestParams(), qPCL::handleNewEntity(), ccCompass::importFoliations(), ccCompassImport::importFoliations(), ccCompass::importLineations(), ccCompassImport::importLineations(), qSRA::loadProfile(), ccTraceTool::pickupTrace(), ccFitPlaneTool::pointPicked(), ccLineationTool::pointPicked(), ccNoteTool::pointPicked(), ccPinchNodeTool::pointPicked(), ccThicknessTool::pointPicked(), ccTraceTool::pointPicked(), ccCompass::recalculateFitPlanes(), ccMeasurementRecorder::setPlane(), and ccCompass::tryLoading().
addWidgetToQMdiArea()
virtual void ecvMainAppInterface::addWidgetToQMdiArea (QWidget * viewWidget) pure virtual
Implemented in MainWindow.
dbRootObject()
virtual ccHObject* ecvMainAppInterface::dbRootObject () pure virtual
Returns DB root (as a ccHObject)
Implemented in MainWindow.
Referenced by ccCompass::addGeoObject(), ccGraphicalSegmentationTool::applySegmentation(), ccLineationTool::cancel(), ccTraceTool::cancel(), Classify3DMASCDialog::Classify3DMASCDialog(), ccCompass::cleanupBeforeToolChange(), ccCompass::convertToPointCloud(), ccCompass::distributeSelection(), qPCV::doAction(), ccCompass::estimateStrain(), JsonRPCPlugin::execute(), StereogramDialog::exportCurrentSelection(), ccCompass::exportToSVG(), ccTraceTool::finishCurrentTrace(), ccCompass::fitPlaneToGeoObject(), BasePclModule::getAllEntitiesOfType(), qCanupoTrainingDialog::getClass1Cloud(), qCanupoTrainingDialog::getClass2Cloud(), Classify3DMASCDialog::getClouds(), qCanupoClassifDialog::getCorePointsCloud(), qM3C2Dialog::getCorePointsCloud(), GetDefaultContainer(), qCanupoTrainingDialog::getEvaluationCloud(), CorrespondenceMatchingDialog::getEvaluationCloud(), TemplateAlignmentDialog::getEvaluationCloud(), ccCompass::getInsertPoint(), CorrespondenceMatchingDialog::getModel1Cloud(), CorrespondenceMatchingDialog::getModel2Cloud(), qM3C2Dialog::getNormalsOrientationCloud(), qCanupoTrainingDialog::getOriginPointCloud(), GeneralFiltersDlg::getPolyline(), ccGeoObject::getRegion(), TemplateAlignmentDialog::getTemplate1Cloud(), TemplateAlignmentDialog::getTemplate2Cloud(), q3DMASCPlugin::onNewSelection(), ccThicknessTool::onNewSelection(), ccTopologyTool::onNewSelection(), ccCompass::onSave(), ccLineationTool::pointPicked(), ccNoteTool::pointPicked(), ccThicknessTool::pointPicked(), ccTraceTool::pointPicked(), qCanupoClassifDialog::qCanupoClassifDialog(), qCanupoTrainingDialog::qCanupoTrainingDialog(), qM3C2Dialog::qM3C2Dialog(), ccCompass::recalculateFitPlanes(), CorrespondenceMatchingDialog::refreshCloudComboBox(), TemplateAlignmentDialog::refreshCloudComboBox(), MinimumCutSegmentationDlg::refreshLabelComboBox(), GeneralFiltersDlg::refreshPolylineComboBox(), ccCompassExport::saveCSV(), ccColorScaleEditorDialog::saveCurrentScale(), ccCompassExport::saveSVG(), ccCompassExport::saveXML(), Classify3DMASCDialog::setCloudRoles(), ccCompass::setPick(), ccCompass::setYoungerThan(), ccCompass::toggleLabels(), ccCompass::toggleNormals(), ccCompass::toggleStipple(), ccThicknessTool::toolActivated(), ccThicknessTool::toolDisactivated(), ccCompass::tryLoading(), ccTraceTool::undo(), StereogramDialog::updateFacetsFilter(), MinimumCutSegmentationDlg::updateForeGroundPoint(), qM3C2Dialog::updateNormalComboBox(), and ccCompass::writeToXML().
decreasePointSize()
virtual void ecvMainAppInterface::decreasePointSize () pure virtual
Implemented in MainWindow.
Referenced by ccGamepadManager::setupGamepadInput().
disableAll()
virtual void ecvMainAppInterface::disableAll () pure virtual
Disables all windows.
Implemented in MainWindow.
dispToConsole()
virtual void ecvMainAppInterface::dispToConsole (QString message, ConsoleMessageLevel level = STD_CONSOLE_MESSAGE) pure virtual
! Prints a message to console **
Parameters
message message
Implemented in MainWindow.
Referenced by qCanupoProcess::Classify(), Classify3DMASCDialog::Classify3DMASCDialog(), qFacets::classifyFacetsByAngle(), DONSegmentation::compute(), EuclideanClusterSegmentation::compute(), SACSegmentation::compute(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), qSRA::computeCloud2ProfileRadialDist(), DistanceMapGenerationTool::ComputeRadialDist(), ccCompass::convertToPointCloud(), G3Point::G3PointAction::createAction(), DistanceMapGenerationTool::CreateMap(), ccPclPluginInterface::dispToConsole(), ccStdPluginInterface::dispToConsole(), DistanceMapGenerationDlg::DistanceMapGenerationDlg(), ccCompass::distributeSelection(), CSF::do_filtering(), qCloudLayers::doAction(), ccCompass::doAction(), qCork::doAction(), qCSF::doAction(), qPCV::doAction(), qPoissonRecon::doAction(), q3DMASCPlugin::doClassifyAction(), qCanupoPlugin::doClassifyAction(), qSRA::doComputeRadialDists(), doPerformBooleanOp(), q3DMASCPlugin::doTrainAction(), qCanupoPlugin::doTrainAction(), ccCompass::estimateP21(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), qFacets::exportFacets(), qFacets::exportFacetsInfo(), DistanceMapGenerationDlg::exportMapAsCloud(), DistanceMapGenerationDlg::exportMapAsGrid(), DistanceMapGenerationDlg::exportMapAsMesh(), DistanceMapGenerationDlg::exportProfilesAsDXF(), ccCompass::exportToSVG(), qFacets::extractFacets(), extractRecursive(), TreeIso::Final_seg(), ccTraceTool::finishCurrentTrace(), ccCompass::fitPlaneToGeoObject(), ccCompass::getInsertPoint(), CorrespondenceMatching::getParametersFromDialog(), TemplateAlignment::getParametersFromDialog(), qM3C2Tools::GuessBestParams(), qPCL::handleErrorMessage(), ccCompass::importFoliations(), ccCompassImport::importFoliations(), ccCompass::importLineations(), ccCompassImport::importLineations(), TreeIso::Init_seg(), qTreeIso::init_segs(), TreeIso::Intermediate_seg(), ProfileLoader::Load(), DistanceMapGenerationDlg::loadOverlaySymbols(), qSRA::loadProfile(), ccCompass::mergeGeoObjects(), ccMPlaneDlgController::onItemPicked(), ccMPlaneDlgController::onMeasureNameChanged(), ccTopologyTool::onNewSelection(), ccCompass::onSave(), ccFitPlaneTool::pointPicked(), ccLineationTool::pointPicked(), ccPinchNodeTool::pointPicked(), ccThicknessTool::pointPicked(), ccTraceTool::pointPicked(), PCVCommand::Process(), qCanupoTrainingDialog::qCanupoTrainingDialog(), CorrespondenceMatchingDialog::refreshCloudComboBox(), TemplateAlignmentDialog::refreshCloudComboBox(), qCanupo2DViewDialog::saveClassifier(), ccCompassExport::saveCSV(), DxfProfilesExporter::SaveHorizontalProfiles(), DistanceMapGenerationTool::SaveMapAsCSVMatrix(), ccCompassExport::saveSVG(), DxfProfilesExporter::SaveVerticalProfiles(), ccCompassExport::saveXML(), G3Point::G3PointAction::segment(), qFacets::showStereogram(), ccCompass::startMeasuring(), ccCompass::startPicking(), DistanceMapGenerationDlg::toggleOverlayGrid(), masc::Classifier::train(), qCanupoTools::TrainClassifier(), DistanceMapGenerationDlg::update(), StereogramDialog::updateFacetsFilter(), DistanceMapGenerationDlg::updateMapTexture(), and ccCompass::writeToXML().
enableAll()
virtual void ecvMainAppInterface::enableAll () pure virtual
Enables all windows.
Implemented in MainWindow.
forceConsoleDisplay()
virtual void ecvMainAppInterface::forceConsoleDisplay () pure virtual
Forces display of console widget.
Implemented in MainWindow.
freezeUI()
virtual void ecvMainAppInterface::freezeUI (bool state) pure virtual
Freezes/unfreezes UI.
Parameters
state freeze state
Implemented in MainWindow.
Referenced by ccMPlaneDlgController::onCloseButtonPressed(), ccMPlaneDlgController::openDialog(), ccCloudLayersDlg::start(), and ccCloudLayersDlg::stop().
getActiveWindow()
virtual QWidget* ecvMainAppInterface::getActiveWindow () pure virtual
Implemented in MainWindow.
Referenced by ccCloudLayersDlg::ccCloudLayersDlg(), ccMPlaneDlgController::ccMPlaneDlgController(), qCloudLayers::doAction(), ccCompass::doAction(), qRansacSD::doAction(), qCanupoPlugin::doClassifyAction(), qCanupoPlugin::doTrainAction(), JsonRPCPlugin::execute(), qFacets::extractFacets(), ExtractSIFT::openInputDialog(), NormalEstimation::openInputDialog(), ProjectionFilter::openInputDialog(), DONSegmentation::openInputDialog(), EuclideanClusterSegmentation::openInputDialog(), RegionGrowingSegmentation::openInputDialog(), SACSegmentation::openInputDialog(), ConvexConcaveHullReconstruction::openInputDialog(), GreedyTriangulation::openInputDialog(), MarchingCubeReconstruction::openInputDialog(), NurbsCurveFitting::openInputDialog(), NurbsSurfaceReconstruction::openInputDialog(), PoissonReconstruction::openInputDialog(), ccCompass::startMeasuring(), ccCompass::stopMeasuring(), and ccPluginUIManager::updateMenus().
getColorScalesManager()
virtual ccColorScalesManager* ecvMainAppInterface::getColorScalesManager () pure virtual
Returns color scale manager (unique instance)
Implemented in MainWindow.
Referenced by DistanceMapGenerationDlg::DistanceMapGenerationDlg(), StereogramDialog::spawnColorScaleEditor(), DistanceMapGenerationDlg::spawnColorScaleEditor(), and StereogramDialog::StereogramDialog().
getMainWindow()
virtual QMainWindow* ecvMainAppInterface::getMainWindow () pure virtual
Returns main window.
Implemented in MainWindow.
Referenced by ccCompass::addGeoObject(), ccMPlaneDlgController::ccMPlaneDlgController(), qFacets::classifyFacetsByAngle(), qSRA::computeCloud2ProfileRadialDist(), DistanceMapGenerationTool::ComputeRadialDist(), qFacets::createFacets(), qCloudLayers::doAction(), ccCompass::doAction(), qCork::doAction(), qCSF::doAction(), qHoughNormals::doAction(), qPCV::doAction(), qPoissonRecon::doAction(), qTreeIso::doAction(), q3DMASCPlugin::doClassifyAction(), qSRA::doProjectCloudDistsInGrid(), q3DMASCPlugin::doTrainAction(), ccGamepadManager::enableDevice(), ccCompass::estimateP21(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), qFacets::exportFacets(), qFacets::exportFacetsInfo(), DistanceMapGenerationDlg::exportMapAsImage(), qFacets::extractFacets(), FastGlobalRegistrationFilter::getParametersFromDialog(), qM3C2Tools::GuessBestParams(), ccCompass::importFoliations(), ccCompassImport::importFoliations(), ccCompass::importLineations(), ccCompassImport::importLineations(), ccEntityAction::interpolateSFs(), qSRA::loadProfile(), ccGamepadManager::onGamepadInput(), MLSSmoothingUpsampling::openInputDialog(), StatisticalOutliersRemover::openInputDialog(), ccNoteTool::pointPicked(), ccTraceTool::pointPicked(), PythonPlugin::setMainAppInterface(), G3PointDisclaimer::show(), DisclaimerDialog::show(), ShowClassifyDisclaimer(), ShowDisclaimer(), ccCompass::showHelp(), qFacets::showStereogram(), ShowTrainDisclaimer(), StereogramDialog::spawnColorScaleEditor(), DistanceMapGenerationDlg::spawnColorScaleEditor(), qCanupoTools::TrainClassifier(), ccCompass::tryLoading(), and G3Point::G3PointAction::wolman().
getSelectedEntities()
virtual const ccHObject::Container& ecvMainAppInterface::getSelectedEntities () const pure virtual
Returns currently selected entities ("read only")
Implemented in MainWindow.
Referenced by qFacets::classifyFacetsByAngle(), qSRA::computeCloud2ProfileRadialDist(), ccCompass::convertToPointCloud(), G3Point::G3PointAction::createAction(), ccCompass::distributeSelection(), qCloudLayers::doAction(), qCork::doAction(), qCSF::doAction(), qHoughNormals::doAction(), qPCV::doAction(), qPoissonRecon::doAction(), qRansacSD::doAction(), ccCompass::estimateP21(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), qFacets::extractFacets(), TreeIso::Final_seg(), qFacets::getFacetsInCurrentSelection(), ccPluginUIManager::handleSelectionChanged(), haveOneSelection(), haveSelection(), ccCompass::importFoliations(), ccCompassImport::importFoliations(), ccCompass::importLineations(), ccCompassImport::importLineations(), ccPluginUIManager::init(), TreeIso::Init_seg(), TreeIso::Intermediate_seg(), ccCompass::mergeGeoObjects(), ccThicknessTool::pointPicked(), qSRA::projectCloudDistsInGrid(), ccCompass::recalculateSelectedTraces(), ccCompass::setLineation(), ccCompass::setPlane(), ccCompass::setThickness(), ccCompass::setTrace(), qFacets::showStereogram(), and ccTraceTool::toolActivated().
getUniqueIDGenerator()
virtual ccUniqueIDGenerator::Shared ecvMainAppInterface::getUniqueIDGenerator () pure virtual
Returns the unique ID generator.
Implemented in MainWindow.
Referenced by ccPclPluginInterface::setMainAppInterface(), and ccStdPluginInterface::setMainAppInterface().
haveOneSelection()
bool ecvMainAppInterface::haveOneSelection () const inline
Checks if we have exactly one selection.
Definition at line 113 of file ecvMainAppInterface.h.
References getSelectedEntities().
Referenced by qFacets::classifyFacetsByAngle(), G3Point::G3PointAction::createAction(), qCloudLayers::doAction(), qCSF::doAction(), qPoissonRecon::doAction(), qFacets::extractFacets(), MainWindow::onItemPicked(), and qFacets::showStereogram().
haveSelection()
bool ecvMainAppInterface::haveSelection () const inline
Checks if we have any selections.
Definition at line 110 of file ecvMainAppInterface.h.
References getSelectedEntities().
Referenced by qHoughNormals::doAction().
increasePointSize()
virtual void ecvMainAppInterface::increasePointSize () pure virtual
Implemented in MainWindow.
Referenced by ccGamepadManager::setupGamepadInput().
loadFile()
virtual ccHObject* ecvMainAppInterface::loadFile (QString filename, bool silent) pure virtual
Attempts to load a file.
Implemented in MainWindow.
pickingHub()
virtual ccPickingHub* ecvMainAppInterface::pickingHub () inline virtual
Reimplemented in MainWindow.
Definition at line 201 of file ecvMainAppInterface.h.
Referenced by ccCompass::startPicking(), and ccCompass::stopPicking().
putObjectBackIntoDBTree()
virtual void ecvMainAppInterface::putObjectBackIntoDBTree (ccHObject * obj, const ccHObjectContext & context) pure virtual
Adds back object to DB tree.
This method should be called once modifications to the db tree are finished (see removeObjectTemporarilyFromDBTree).
Implemented in MainWindow.
Referenced by ccGraphicalSegmentationTool::applySegmentation(), BasePclModule::performAction(), RemoveUnusedLabelsAndUpdateTheOthers(), ccPointPairRegistrationDlg::transformAlignedEntity(), and GrainsAsEllipsoids::updateMeshAndLineSet().
redrawAll()
virtual void ecvMainAppInterface::redrawAll (bool only2D = false, bool forceRedraw = true) inline virtual
Definition at line 148 of file ecvMainAppInterface.h.
References refreshAll().
Referenced by q3DMASCPlugin::doTrainAction().
refreshAll()
virtual void ecvMainAppInterface::refreshAll (bool only2D = false, bool forceRedraw = true) pure virtual
Redraws all GL windows that have the 'refresh' flag on.
! Forces redraw of all GL windows **
Parameters
only2D whether to redraw everything (false) or only the 2D layer (true) See ccDrawableObject::prepareDisplayForRefresh.
only2D whether to redraw everything (false) or only the 2D layer (true)
Implemented in MainWindow.
Referenced by qM3C2Process::Compute(), qVoxFallProcess::Compute(), ccCompass::distributeSelection(), qPoissonRecon::doAction(), qTreeIso::doAction(), qCanupoPlugin::doClassifyAction(), qSRA::doComputeRadialDists(), ccCompass::estimateStructureNormals(), qTreeIso::final_segs(), qTreeIso::init_segs(), qTreeIso::intermediate_segs(), ccCompass::mergeGeoObjects(), ccColorScaleEditorDialog::onApply(), ccMPlaneDlgController::onFittingPointDelete(), redrawAll(), ccColorScaleEditorDialog::saveCurrentScale(), qM3C2Dialog::setCloud1Visibility(), qM3C2Dialog::setCloud2Visibility(), ccOrderChoiceDlg::setColorsAndLabels(), qVoxFallDialog::setMesh1Visibility(), qVoxFallDialog::setMesh2Visibility(), ccCompass::stopMeasuring(), StereogramDialog::updateFacetsFilter(), and ccOrderChoiceDlg::~ccOrderChoiceDlg().
refreshObject()
virtual void ecvMainAppInterface::refreshObject (ccHObject * obj, bool only2D = false, bool forceRedraw = true) pure virtual
Implemented in MainWindow.
refreshObjects()
virtual void ecvMainAppInterface::refreshObjects (ccHObject::Container objs, bool only2D = false, bool forceRedraw = true) pure virtual
Implemented in MainWindow.
refreshSelected()
virtual void ecvMainAppInterface::refreshSelected (bool only2D = false, bool forceRedraw = true) pure virtual
Implemented in MainWindow.
Referenced by qHoughNormals::doAction(), qPCV::doAction(), qPCL::handleEntityChange(), and ccMPlaneDlgController::onCloseButtonPressed().
registerOverlayDialog()
virtual void ecvMainAppInterface::registerOverlayDialog (ccOverlayDialog * dlg, Qt::Corner pos) pure virtual
Registers a MDI area 'overlay' dialog.
Overlay dialogs are displayed in the central MDI area, above the 3D views. The position (pos) is defined relatively to the MDI area (as one of its 4 corners). And it is automatically updated when the main window is moved or resized. Registered dialogs are automatically released when CLOUDVIEWER stops.
Notes:
it may be necessary to call 'updateOverlayDialogsPlacement' after calling this method
it's a good idea to freeez the UI when the tool starts to avoid other overlay dialogs to appear (don't forget to unfreeze the UI afterwards)
Implemented in MainWindow.
Referenced by qCloudLayers::doAction(), ccCompass::enableMapMode(), and ccCompass::startMeasuring().
removeFromDB()
virtual void ecvMainAppInterface::removeFromDB (ccHObject * obj, bool autoDelete = true) pure virtual
Removes an entity from main db tree.
Object is automatically detached from its parent.
Parameters
obj entity
autoDelete automatically deletes object
Implemented in MainWindow.
Referenced by ccLineationTool::cancel(), ccTraceTool::cancel(), qFacets::classifyFacetsByAngle(), ccMeasurementRecorder::deleteFittingPoint(), ccMeasurementRecorder::deletePlane(), ccCompass::distributeSelection(), JsonRPCPlugin::execute(), ccCompass::mergeGeoObjects(), ccTraceTool::pickupTrace(), ccThicknessTool::pointPicked(), ccTraceTool::pointPicked(), and ccCompass::tryLoading().
removeObjectTemporarilyFromDBTree()
virtual ccHObjectContext ecvMainAppInterface::removeObjectTemporarilyFromDBTree (ccHObject * obj) pure virtual
Removes object temporarily from DB tree.
This method must be called before any modification to the db tree
Warning
May change the set of currently selected entities
Implemented in MainWindow.
Referenced by ccGraphicalSegmentationTool::applySegmentation(), BasePclModule::performAction(), RemoveUnusedLabelsAndUpdateTheOthers(), ccPointPairRegistrationDlg::transformAlignedEntity(), and GrainsAsEllipsoids::updateMeshAndLineSet().
resetSelectedBBox()
virtual void ecvMainAppInterface::resetSelectedBBox () pure virtual
Implemented in MainWindow.
setGlobalZoom()
virtual void ecvMainAppInterface::setGlobalZoom () pure virtual
Implemented in MainWindow.
Referenced by ccGamepadManager::setupGamepadInput().
setSelectedInDB()
virtual void ecvMainAppInterface::setSelectedInDB (ccHObject * obj, bool selected) pure virtual
Selects or unselects an entity (in db tree)
Parameters
obj entity
selected whether entity should be selected or not
Implemented in MainWindow.
Referenced by ccCompass::addGeoObject(), qPoissonRecon::doAction(), ccTraceTool::finishCurrentTrace(), ccCompass::mergeGeoObjects(), ccCompass::pointPicked(), ccThicknessTool::pointPicked(), and ccTraceTool::pointPicked().
setView()
virtual void ecvMainAppInterface::setView (CC_VIEW_ORIENTATION view) pure virtual
Implemented in MainWindow.
spawnHistogramDialog()
virtual void ecvMainAppInterface::spawnHistogramDialog (const std::vector< unsigned > & histoValues, double minVal, double maxVal, QString title, QString xAxisLabel) pure virtual
Implemented in MainWindow.
toggle3DView()
virtual void ecvMainAppInterface::toggle3DView (bool state) pure virtual
Implemented in MainWindow.
toggleActiveWindowCenteredPerspective()
virtual void ecvMainAppInterface::toggleActiveWindowCenteredPerspective () pure virtual
Referenced by ccGamepadManager::setupGamepadInput().
toggleActiveWindowViewerBasedPerspective()
virtual void ecvMainAppInterface::toggleActiveWindowViewerBasedPerspective () pure virtual
Referenced by ccGamepadManager::setupGamepadInput().
toggleExclusiveFullScreen()
virtual void ecvMainAppInterface::toggleExclusiveFullScreen (bool state) pure virtual
Implemented in MainWindow.
unregisterOverlayDialog()
virtual void ecvMainAppInterface::unregisterOverlayDialog (ccOverlayDialog * dlg) pure virtual
Unregisters a MDI area 'overlay' dialog.
Warning
Original overlay dialog object will be deleted (see QObject::deleteLater)
Implemented in MainWindow.
Referenced by ccCompass::enableMeasureMode(), ccMPlaneDlgController::onCloseButtonPressed(), and ccCompass::stopMeasuring().
updateOverlayDialogsPlacement()
virtual void ecvMainAppInterface::updateOverlayDialogsPlacement () pure virtual
Forces the update of all registered MDI 'overlay' dialogs.
Implemented in MainWindow.
Referenced by qCloudLayers::doAction(), ccCompass::enableMapMode(), ccCompass::enableMeasureMode(), and ccMPlaneDlgController::onCloseButtonPressed().
updateUI()
virtual void ecvMainAppInterface::updateUI () pure virtual
Updates UI (menu and properties browser) to reflect current selection state This method should be called whenever a change is made to any selected entity
Implemented in MainWindow.
Referenced by ccCompass::distributeSelection(), qCloudLayers::doAction(), qHoughNormals::doAction(), qPCV::doAction(), qPoissonRecon::doAction(), qCanupoPlugin::doClassifyAction(), qSRA::doComputeRadialDists(), qTreeIso::final_segs(), G3Point::G3PointAction::fit(), qPCL::handleEntityChange(), qTreeIso::init_segs(), qTreeIso::intermediate_segs(), ccMPlaneDlgController::onFittingPointDelete(), ccCompass::pointPicked(), qM3C2Dialog::setCloud1Visibility(), qM3C2Dialog::setCloud2Visibility(), qVoxFallDialog::setMesh1Visibility(), and qVoxFallDialog::setMesh2Visibility().
zoomOnEntities()
virtual void ecvMainAppInterface::zoomOnEntities (ccHObject * obj) pure virtual
Implemented in MainWindow.
Referenced by qPCL::handleNewEntity().
zoomOnSelectedEntities()
virtual void ecvMainAppInterface::zoomOnSelectedEntities () pure virtual
Implemented in MainWindow.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CVPluginAPI/include/ecvMainAppInterface.h