ACloudViewer: cloudViewer::data::SampleSUNRGBDImage Class Reference
cloudViewer::data::SampleSUNRGBDImage Class Reference
Data class for SampleSUNRGBDImage contains a color image SUN_color.jpg and a depth image SUN_depth.png sample from SUN RGBD dataset.
#include <Dataset.h>
Public Member Functions
SampleSUNRGBDImage (const std::string &data_root="")
std::string GetColorPath () const
Path to color image sample.
std::string GetDepthPath () const
Path to depth image sample.
Public Member Functions inherited from cloudViewer::data::DownloadDataset
DownloadDataset (const std::string &prefix, const DataDescriptor &data_descriptor, const std::string &data_root="")
DownloadDataset (const std::string &prefix, const std::vector< DataDescriptor > &data_descriptors, const std::string &data_root="")
virtual ~DownloadDataset ()
Public Member Functions inherited from cloudViewer::data::Dataset
Dataset (const std::string &prefix, const std::string &data_root="")
Parameterized Constructor.
virtual ~Dataset ()
const std::string GetDataRoot () const
Get data root directory. The data root is set at construction time or automatically determined.
const std::string GetPrefix () const
Get prefix for the dataset.
const std::string GetDownloadDir () const
Get absolute path to download directory. i.e. ${data_root}/download/${prefix}.
const std::string GetExtractDir () const
Get absolute path to extract directory. i.e. ${data_root}/extract/${prefix}.
Additional Inherited Members
Protected Member Functions inherited from cloudViewer::data::DownloadDataset
bool HasDownloaded (const DataDescriptor &data_descriptor) const
Check if all files are downloaded and MD5 checksums are valid.
Protected Member Functions inherited from cloudViewer::data::Dataset
void CheckPathsExist (const std::vector< std::string > &paths) const
Check if the paths exists after extraction.
Protected Attributes inherited from cloudViewer::data::DownloadDataset
std::vector< DataDescriptor > data_descriptors_
Protected Attributes inherited from cloudViewer::data::Dataset
std::string data_root_
CloudViewer data root.
std::string prefix_
Dataset prefix.
Detailed Description
Data class for SampleSUNRGBDImage contains a color image SUN_color.jpg and a depth image SUN_depth.png sample from SUN RGBD dataset.
Definition at line 1091 of file Dataset.h.
Constructor & Destructor Documentation
SampleSUNRGBDImage()
cloudViewer::data::SampleSUNRGBDImage::SampleSUNRGBDImage (const std::string & data_root = "")
Definition at line 22 of file SampleSUNRGBDImage.cpp.
References cloudViewer::data::Dataset::GetExtractDir().
Member Function Documentation
GetColorPath()
std::string cloudViewer::data::SampleSUNRGBDImage::GetColorPath () const inline
Path to color image sample.
Definition at line 1096 of file Dataset.h.
Referenced by cloudViewer::data::pybind_sample_sun_rgbd_image().
GetDepthPath()
std::string cloudViewer::data::SampleSUNRGBDImage::GetDepthPath () const inline
Path to depth image sample.
Definition at line 1098 of file Dataset.h.
Referenced by cloudViewer::data::pybind_sample_sun_rgbd_image().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/data/Dataset.h
/root/ACloudViewer/libs/cloudViewer/data/dataset/SampleSUNRGBDImage.cpp