ACloudViewer: ccSerializableObject Class Reference
ccSerializableObject Class Reference abstract
Serializable object interface.
#include <ecvSerializableObject.h>
Public Types
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Public Member Functions
virtual ~ccSerializableObject ()=default
Destructor.
virtual bool isSerializable () const
Returns whether object is serializable of not.
virtual bool toFile (QFile &out, short dataVersion) const
Saves data to binary stream.
virtual short minimumFileVersion () const =0
Returns the minimum file version required to save this instance.
virtual bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Loads data from binary stream.
Static Public Member Functions
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Detailed Description
Serializable object interface.
Definition at line 25 of file ecvSerializableObject.h.
Member Typedef Documentation
LoadedIDMap
typedef QMultiMap<unsigned, unsigned> ccSerializableObject::LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Definition at line 61 of file ecvSerializableObject.h.
Member Enumeration Documentation
DeserializationFlags
enum ccSerializableObject::DeserializationFlags
Deserialization flags (bit-field)
Enumerator
DF_POINT_COORDS_64_BITS
Point coordinates are stored as 64 bits double (otherwise 32 bits floats)
DF_SCALAR_VAL_32_BITS
Scalar values are stored as 32 bits floats (otherwise 64 bits double)
Definition at line 51 of file ecvSerializableObject.h.
Constructor & Destructor Documentation
~ccSerializableObject()
virtual ccSerializableObject::~ccSerializableObject () virtual default
Destructor.
Member Function Documentation
CorruptError()
static bool ccSerializableObject::CorruptError () inline static
Sends a custom error message (corrupted file) and returns 'false'.
Shortcut for returning a standardized error message in the fromFile method.
Returns
always false
Definition at line 113 of file ecvSerializableObject.h.
References CVLog::Error().
Referenced by define_ccSerializableObject().
fromFile()
virtual bool ccSerializableObject::fromFile (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) inline virtual
Loads data from binary stream.
Parameters
in input file (already opened)
dataVersion file version (for version-specific deserialization)
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Returns
success
Note: When implementing, use dataVersion checks to handle different
versions:
if (dataVersion >= X) { read new field } else { use default value } This ensures forward compatibility with older file formats.
Reimplemented in ccWaveform, WaveformDescriptor, ecvViewportParameters, ccScalarField, ccPointCloud::Grid, ccObject, ccMaterial, ccIndexedTransformation, ccHObject, ccGLMatrixTpl< T >, ccGLMatrixTpl< double >, ccGLMatrixTpl< float >, and ccColorScale.
Definition at line 75 of file ecvSerializableObject.h.
Referenced by define_ccSerializableObject().
isSerializable()
virtual bool ccSerializableObject::isSerializable () const inline virtual
Returns whether object is serializable of not.
Reimplemented in cloudViewer::geometry::VoxelGrid, cloudViewer::geometry::RGBDImage, cloudViewer::geometry::Octree, cloudViewer::geometry::LineSet, cloudViewer::geometry::Image, cloudViewer::geometry::HalfEdgeTriangleMesh, ccWaveform, WaveformDescriptor, ecvViewportParameters, cloudViewer::geometry::TetraMesh, ccSubMesh, ccSensor, ccScalarField, ccPolyline, ccPointCloud::Grid, ecvOrientedBBox, ccMeshGroup, cloudViewer::geometry::ecvMeshBase, ccMesh, ccMaterialSet, ccMaterial, ccIndexedTransformationBuffer, ccIndexedTransformation, ccImage, ccHObject, ccGLMatrixTpl< T >, ccGLMatrixTpl< double >, ccGLMatrixTpl< float >, ccGenericPointCloud, ccGenericMesh, ccGBLSensor, ccFacet, ccCustomHObject, ccColorScale, ccCameraSensor, ccBBox, ccArray< Type, N, ComponentType >, ccArray< CompressedNormType, 1, CompressedNormType >, ccArray< TexCoords2D, 2, float >, ccArray< ecvColor::Rgba, 4, ColorCompType >, ccArray< CCVector3, 3, PointCoordinateType >, ccArray< ecvColor::Rgb, 3, ColorCompType >, cc2DViewportObject, cc2DViewportLabel, cc2DLabel, cloudViewer::visualization::SelectionPolygon, and cloudViewer::visualization::PointCloudPicker.
Definition at line 31 of file ecvSerializableObject.h.
Referenced by define_ccSerializableObject().
MemoryError()
static bool ccSerializableObject::MemoryError () inline static
Sends a custom error message (not enough memory) and returns 'false'.
Shortcut for returning a standardized error message in the fromFile method.
Returns
always false
Definition at line 104 of file ecvSerializableObject.h.
References CVLog::Error().
Referenced by define_ccSerializableObject().
minimumFileVersion()
virtual short ccSerializableObject::minimumFileVersion () const pure virtual
Returns the minimum file version required to save this instance.
To be overridden by subclasses to indicate their minimum required version. This enables the system to determine:
Forward compatibility: newer software can read older files (dataVersion check in fromFile)
Backward compatibility: determine minimum version needed to save current data
Returns
minimum file version required for this object
Implemented in ccWaveform, WaveformDescriptor, ecvViewportParameters, ccScalarField, ccPointCloud::Grid, ccObject, ccMaterial, ccIndexedTransformation, ccHObject, ccGLMatrixTpl< T >, ccGLMatrixTpl< double >, ccGLMatrixTpl< float >, and ccColorScale.
Referenced by define_ccSerializableObject().
ReadError()
static bool ccSerializableObject::ReadError () inline static
Sends a custom error message (read error) and returns 'false'.
Shortcut for returning a standardized error message in the fromFile method.
Returns
always false
Definition at line 95 of file ecvSerializableObject.h.
References CVLog::Error().
Referenced by define_ccSerializableObject().
toFile()
virtual bool ccSerializableObject::toFile (QFile & out, short dataVersion) const inline virtual
Saves data to binary stream.
Parameters
out output file (already opened)
dataVersion target file version (for forward/backward compatibility)
Returns
success
Reimplemented in ccWaveform, WaveformDescriptor, ecvViewportParameters, ccScalarField, ccPointCloud::Grid, ccObject, ccMaterial, ccIndexedTransformation, ccHObject, ccGLMatrixTpl< T >, ccGLMatrixTpl< double >, ccGLMatrixTpl< float >, and ccColorScale.
Definition at line 38 of file ecvSerializableObject.h.
Referenced by define_ccSerializableObject().
WriteError()
static bool ccSerializableObject::WriteError () inline static
Sends a custom error message (write error) and returns 'false'.
Shortcut for returning a standardized error message in the toFile method.
Returns
always false
Definition at line 86 of file ecvSerializableObject.h.
References CVLog::Error().
Referenced by define_ccSerializableObject().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvSerializableObject.h