ACloudViewer: cloudViewer::DatabaseImageViewerWidget Class Reference
cloudViewer::DatabaseImageViewerWidget Class Reference
#include <ImageViewerWidget.h>
Public Member Functions
DatabaseImageViewerWidget (QWidget *parent, ModelViewerWidget *ModelViewerWidget, OptionManager *options)
void ShowImageWithId (const colmap::image_t image_id)
Public Member Functions inherited from cloudViewer::FeatureImageViewerWidget
FeatureImageViewerWidget (QWidget *parent, const std::string &switch_text)
void ReadAndShowWithKeypoints (const std::string &path, const colmap::FeatureKeypoints &keypoints, const std::vector< char > &tri_mask)
void ReadAndShowWithMatches (const std::string &path1, const std::string &path2, const colmap::FeatureKeypoints &keypoints1, const colmap::FeatureKeypoints &keypoints2, const colmap::FeatureMatches &matches)
Public Member Functions inherited from cloudViewer::ImageViewerWidget
ImageViewerWidget (QWidget *parent)
void ShowBitmap (const colmap::Bitmap &bitmap)
void ShowPixmap (const QPixmap &pixmap)
void ReadAndShow (const std::string &path)
Additional Inherited Members
Protected Member Functions inherited from cloudViewer::FeatureImageViewerWidget
void ShowOrHide ()
Protected Member Functions inherited from cloudViewer::ImageViewerWidget
void resizeEvent (QResizeEvent *event)
void closeEvent (QCloseEvent *event)
void ZoomIn ()
void ZoomOut ()
void Save ()
Protected Attributes inherited from cloudViewer::FeatureImageViewerWidget
QPixmap image1_
QPixmap image2_
bool switch_state_
QPushButton * switch_button_
const std::string switch_text_
Protected Attributes inherited from cloudViewer::ImageViewerWidget
QGridLayout * grid_layout_
QHBoxLayout * button_layout_
Detailed Description
Definition at line 85 of file ImageViewerWidget.h.
Constructor & Destructor Documentation
DatabaseImageViewerWidget()
cloudViewer::DatabaseImageViewerWidget::DatabaseImageViewerWidget (QWidget * parent, ModelViewerWidget * ModelViewerWidget, OptionManager * options)
Definition at line 232 of file ImageViewerWidget.cpp.
Member Function Documentation
ShowImageWithId()
void cloudViewer::DatabaseImageViewerWidget::ShowImageWithId (const colmap::image_t image_id)
Definition at line 330 of file ImageViewerWidget.cpp.
References cloudViewer::ModelViewerWidget::cameras, image, cloudViewer::ModelViewerWidget::images, cloudViewer::utility::filesystem::JoinPaths(), cloudViewer::t::geometry::path, and cloudViewer::FeatureImageViewerWidget::ReadAndShowWithKeypoints().
Referenced by cloudViewer::ModelViewerWidget::ShowImageInfo().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/reconstruction/ImageViewerWidget.h
/root/ACloudViewer/app/reconstruction/ImageViewerWidget.cpp