ACloudViewer: cloudViewer::Grid3D< Type > Class Template Reference
cloudViewer::Grid3D< Type > Class Template Reference
Simple 3D grid structure.
#include <Grid3D.h>
Classes
struct CellToTest
Public Types
using GridElement = Type
Cell type.
using genericCellTriIntersectionAction = std::function< void(const Tuple3i &, unsigned)>
Public Member Functions
Grid3D ()
Default constructor.
const Tuple3ui & size () const
Returns the grid dimensions.
bool isInitialized () const
Returns whether the grid has been initialized or not.
void clear ()
Clears the grid.
bool init (unsigned di, unsigned dj, unsigned dk, unsigned margin, GridElement defaultCellValue=0)
Initializes the grid.
Tuple3i computeCellPos (const CCVector3 &P, const CCVector3 &gridMinCorner, PointCoordinateType cellSize) const
Computes the (grid) cell position that contains a given point.
bool intersectWith (GenericIndexedMesh *mesh, PointCoordinateType cellLength, const CCVector3 &gridMinCorner, GridElement intersectValue=0, GenericProgressCallback *progressCb=nullptr)
Intersects this grid with a mesh.
bool intersectWith (GenericIndexedMesh *mesh, PointCoordinateType cellLength, const CCVector3 &gridMinCorner, genericCellTriIntersectionAction action, GenericProgressCallback *progressCb=nullptr)
Intersects this grid with a mesh (generic form)
bool intersectWith (GenericCloud *cloud, PointCoordinateType cellLength, const CCVector3 &gridMinCorner, GridElement intersectValue=0, GenericProgressCallback *progressCb=nullptr)
Intersects this grid with a cloud.
void setValue (int i, int j, int k, GridElement value)
Sets the value of a given cell.
void setValue (const Tuple3i &cellPos, GridElement value)
Sets the value of a given cell.
const GridElement & getValue (int i, int j, int k) const
Returns the value of a given cell (const version)
GridElement & getValue (int i, int j, int k)
Returns the value of a given cell.
const GridElement & getValue (Tuple3i &cellPos) const
Returns the value of a given cell const version)
GridElement & getValue (Tuple3i &cellPos)
Returns the value of a given cell.
GridElement * data ()
Gives access to the internal grid data (with margin)
const GridElement * data () const
Gives access to the internal grid data (with margin) (const version)
uint64_t innerCellCount () const
Returns the number of cell count (whithout margin)
uint64_t totalCellCount () const
Returns the total number of cell count (with margin)
Protected Member Functions
int64_t pos2index (int i, int j, int k) const
Converts a 3D position to an absolute index.
Protected Attributes
std::vector< GridElement > m_grid
Grid data.
Tuple3ui m_innerSize
Dimensions of the grid (without margin)
int64_t m_margin
Margin.
int64_t m_rowSize
1D row size (with margin)
int64_t m_sliceSize
2D slice size (with margin)
uint64_t m_innerCellCount
3D grid size without margin
uint64_t m_totalCellCount
3D grid size with margin
int64_t m_marginShift
First index of real data (i.e. after marin)
Detailed Description
template<class Type>
class cloudViewer::Grid3D< Type >
Simple 3D grid structure.
The grid data is contiguous in memory.
Definition at line 32 of file Grid3D.h.
Member Typedef Documentation
genericCellTriIntersectionAction
template<class Type > using cloudViewer::Grid3D< Type >::genericCellTriIntersectionAction = std::function<void(const Tuple3i&, unsigned)>
Generic function applied to a cell intersected by a triangle (used by the generic form of intersectWith)
Definition at line 151 of file Grid3D.h.
GridElement
template<class Type > using cloudViewer::Grid3D< Type >::GridElement = Type
Cell type.
Definition at line 35 of file Grid3D.h.
Constructor & Destructor Documentation
Grid3D()
template<class Type > cloudViewer::Grid3D< Type >::Grid3D () inline
Default constructor.
Definition at line 38 of file Grid3D.h.
Member Function Documentation
clear()
template<class Type > void cloudViewer::Grid3D< Type >::clear () inline
Clears the grid.
Warning
If Type is a pointer type, memory should be released first
Definition at line 56 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_grid, cloudViewer::Grid3D< Type >::m_innerCellCount, cloudViewer::Grid3D< Type >::m_innerSize, cloudViewer::Grid3D< Type >::m_margin, cloudViewer::Grid3D< Type >::m_marginShift, cloudViewer::Grid3D< Type >::m_rowSize, cloudViewer::Grid3D< Type >::m_sliceSize, and cloudViewer::Grid3D< Type >::m_totalCellCount.
computeCellPos()
template<class Type > Tuple3i cloudViewer::Grid3D< Type >::computeCellPos (const CCVector3 & P, const CCVector3 & gridMinCorner, PointCoordinateType cellSize) const inline
Computes the (grid) cell position that contains a given point.
Definition at line 111 of file Grid3D.h.
References Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by cloudViewer::Grid3D< Type >::intersectWith().
data() [1/2]
template<class Type > GridElement* cloudViewer::Grid3D< Type >::data () inline
Gives access to the internal grid data (with margin)
Definition at line 527 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_grid.
data() [2/2]
template<class Type > const GridElement* cloudViewer::Grid3D< Type >::data () const inline
Gives access to the internal grid data (with margin) (const version)
Definition at line 529 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_grid.
getValue() [1/4]
template<class Type > GridElement& cloudViewer::Grid3D< Type >::getValue (int i, int j, int k) inline
Returns the value of a given cell.
Parameters
i the cell coordinate along the X dimension
j the cell coordinate along the Y dimension
k the cell coordinate along the Z dimension
Returns
the cell value
Definition at line 507 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_grid, and cloudViewer::Grid3D< Type >::pos2index().
getValue() [2/4]
template<class Type > const GridElement& cloudViewer::Grid3D< Type >::getValue (int i, int j, int k) const inline
Returns the value of a given cell (const version)
Parameters
i the cell coordinate along the X dimension
j the cell coordinate along the Y dimension
k the cell coordinate along the Z dimension
Returns
the cell value
Definition at line 498 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_grid, and cloudViewer::Grid3D< Type >::pos2index().
getValue() [3/4]
template<class Type > GridElement& cloudViewer::Grid3D< Type >::getValue (Tuple3i & cellPos) inline
Returns the value of a given cell.
Parameters
cellPos the cell position
Returns
the cell value
Definition at line 522 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_grid, cloudViewer::Grid3D< Type >::pos2index(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
getValue() [4/4]
template<class Type > const GridElement& cloudViewer::Grid3D< Type >::getValue (Tuple3i & cellPos) const inline
Returns the value of a given cell const version)
Parameters
cellPos the cell position
Returns
the cell value
Definition at line 515 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_grid, cloudViewer::Grid3D< Type >::pos2index(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
init()
template<class Type > bool cloudViewer::Grid3D< Type >::init (unsigned di, unsigned dj, unsigned dk, unsigned margin, GridElement defaultCellValue = 0) inline
Initializes the grid.
The grid must be explicitelty initialized prior to any action.
Parameters
di grid size along the X dimension
dj grid size along the Y dimension
dk grid size along the Z dimension
margin grid margin
defaultCellValue default cell value
Returns
true if the initialization succeeded
Definition at line 77 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_grid, cloudViewer::Grid3D< Type >::m_innerCellCount, cloudViewer::Grid3D< Type >::m_innerSize, cloudViewer::Grid3D< Type >::m_margin, cloudViewer::Grid3D< Type >::m_marginShift, cloudViewer::Grid3D< Type >::m_rowSize, cloudViewer::Grid3D< Type >::m_sliceSize, cloudViewer::Grid3D< Type >::m_totalCellCount, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by cloudViewer::ChamferDistanceTransform::init(), and cloudViewer::SaitoSquaredDistanceTransform::initGrid().
innerCellCount()
template<class Type > uint64_t cloudViewer::Grid3D< Type >::innerCellCount () const inline
Returns the number of cell count (whithout margin)
Definition at line 532 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_innerCellCount.
intersectWith() [1/3]
template<class Type > bool cloudViewer::Grid3D< Type >::intersectWith (GenericCloud * cloud, PointCoordinateType cellLength, const CCVector3 & gridMinCorner, GridElement intersectValue = 0, GenericProgressCallback * progressCb = nullptr) inline
Intersects this grid with a cloud.
Definition at line 423 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::computeCellPos(), cloudViewer::GenericCloud::getNextPoint(), cloudViewer::Grid3D< Type >::isInitialized(), nProgress, cloudViewer::NormalizedProgress::oneStep(), cloudViewer::GenericCloud::placeIteratorAtBeginning(), cloudViewer::Grid3D< Type >::setValue(), cloudViewer::Grid3D< Type >::size(), cloudViewer::GenericCloud::size(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
intersectWith() [2/3]
template<class Type > bool cloudViewer::Grid3D< Type >::intersectWith (GenericIndexedMesh * mesh, PointCoordinateType cellLength, const CCVector3 & gridMinCorner, genericCellTriIntersectionAction action, GenericProgressCallback * progressCb = nullptr) inline
Intersects this grid with a mesh (generic form)
Definition at line 155 of file Grid3D.h.
References cloudViewer::GenericTriangle::_getA(), cloudViewer::GenericTriangle::_getB(), cloudViewer::GenericTriangle::_getC(), cloudViewer::GenericMesh::_getNextTriangle(), cloudViewer::utility::ceil(), cloudViewer::Grid3D< Type >::CellToTest::cellSize, cloudViewer::Grid3D< Type >::computeCellPos(), Vector3Tpl< Type >::cross(), Vector3Tpl< Type >::dot(), Vector3Tpl< PointCoordinateType >::fromArray(), cloudViewer::GreaterThanSquareEpsilon(), cloudViewer::Grid3D< Type >::isInitialized(), max(), min(), Vector3Tpl< Type >::norm2(), nProgress, cloudViewer::GenericMesh::placeIteratorAtBeginning(), cloudViewer::Grid3D< Type >::CellToTest::pos, cloudViewer::Grid3D< Type >::size(), cloudViewer::GenericMesh::size(), cloudViewer::CCMiscTools::TriBoxOverlap(), Tuple3Tpl< Type >::u, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
intersectWith() [3/3]
template<class Type > bool cloudViewer::Grid3D< Type >::intersectWith (GenericIndexedMesh * mesh, PointCoordinateType cellLength, const CCVector3 & gridMinCorner, GridElement intersectValue = 0, GenericProgressCallback * progressCb = nullptr) inline
Intersects this grid with a mesh.
Definition at line 135 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::setValue().
isInitialized()
template<class Type > bool cloudViewer::Grid3D< Type >::isInitialized () const inline
Returns whether the grid has been initialized or not.
Definition at line 51 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_totalCellCount.
Referenced by cloudViewer::Grid3D< Type >::intersectWith().
pos2index()
template<class Type > int64_t cloudViewer::Grid3D< Type >::pos2index (int i, int j, int k) const inline protected
Converts a 3D position to an absolute index.
Definition at line 538 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_marginShift, cloudViewer::Grid3D< Type >::m_rowSize, and cloudViewer::Grid3D< Type >::m_sliceSize.
Referenced by cloudViewer::Grid3D< Type >::getValue(), and cloudViewer::Grid3D< Type >::setValue().
setValue() [1/2]
template<class Type > void cloudViewer::Grid3D< Type >::setValue (const Tuple3i & cellPos, GridElement value) inline
Sets the value of a given cell.
Parameters
cellPos the cell position
value new cell value
Definition at line 488 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_grid, cloudViewer::Grid3D< Type >::pos2index(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
setValue() [2/2]
template<class Type > void cloudViewer::Grid3D< Type >::setValue (int i, int j, int k, GridElement value) inline
Sets the value of a given cell.
Parameters
i the cell coordinate along the X dimension
j the cell coordinate along the Y dimension
k the cell coordinate along the Z dimension
value new cell value
Definition at line 480 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_grid, and cloudViewer::Grid3D< Type >::pos2index().
Referenced by cloudViewer::Grid3D< Type >::intersectWith().
size()
template<class Type > const Tuple3ui& cloudViewer::Grid3D< Type >::size () const inline
Returns the grid dimensions.
Definition at line 48 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_innerSize.
Referenced by cloudViewer::Grid3D< Type >::intersectWith().
totalCellCount()
template<class Type > uint64_t cloudViewer::Grid3D< Type >::totalCellCount () const inline
Returns the total number of cell count (with margin)
Definition at line 534 of file Grid3D.h.
References cloudViewer::Grid3D< Type >::m_totalCellCount.
Member Data Documentation
m_grid
template<class Type > std::vector<GridElement> cloudViewer::Grid3D< Type >::m_grid protected
Grid data.
Definition at line 544 of file Grid3D.h.
Referenced by cloudViewer::Grid3D< Type >::clear(), cloudViewer::Grid3D< Type >::data(), cloudViewer::Grid3D< Type >::getValue(), cloudViewer::Grid3D< Type >::init(), and cloudViewer::Grid3D< Type >::setValue().
m_innerCellCount
template<class Type > uint64_t cloudViewer::Grid3D< Type >::m_innerCellCount protected
3D grid size without margin
Definition at line 555 of file Grid3D.h.
Referenced by cloudViewer::Grid3D< Type >::clear(), cloudViewer::Grid3D< Type >::init(), and cloudViewer::Grid3D< Type >::innerCellCount().
m_innerSize
template<class Type > Tuple3ui cloudViewer::Grid3D< Type >::m_innerSize protected
Dimensions of the grid (without margin)
Definition at line 547 of file Grid3D.h.
Referenced by cloudViewer::Grid3D< Type >::clear(), cloudViewer::Grid3D< Type >::init(), and cloudViewer::Grid3D< Type >::size().
m_margin
template<class Type > int64_t cloudViewer::Grid3D< Type >::m_margin protected
Margin.
Definition at line 549 of file Grid3D.h.
Referenced by cloudViewer::Grid3D< Type >::clear(), and cloudViewer::Grid3D< Type >::init().
m_marginShift
template<class Type > int64_t cloudViewer::Grid3D< Type >::m_marginShift protected
First index of real data (i.e. after marin)
Definition at line 559 of file Grid3D.h.
Referenced by cloudViewer::Grid3D< Type >::clear(), cloudViewer::Grid3D< Type >::init(), and cloudViewer::Grid3D< Type >::pos2index().
m_rowSize
template<class Type > int64_t cloudViewer::Grid3D< Type >::m_rowSize protected
1D row size (with margin)
Definition at line 551 of file Grid3D.h.
Referenced by cloudViewer::Grid3D< Type >::clear(), cloudViewer::Grid3D< Type >::init(), and cloudViewer::Grid3D< Type >::pos2index().
m_sliceSize
template<class Type > int64_t cloudViewer::Grid3D< Type >::m_sliceSize protected
2D slice size (with margin)
Definition at line 553 of file Grid3D.h.
Referenced by cloudViewer::Grid3D< Type >::clear(), cloudViewer::Grid3D< Type >::init(), and cloudViewer::Grid3D< Type >::pos2index().
m_totalCellCount
template<class Type > uint64_t cloudViewer::Grid3D< Type >::m_totalCellCount protected
3D grid size with margin
Definition at line 557 of file Grid3D.h.
Referenced by cloudViewer::Grid3D< Type >::clear(), cloudViewer::Grid3D< Type >::init(), cloudViewer::Grid3D< Type >::isInitialized(), and cloudViewer::Grid3D< Type >::totalCellCount().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/Grid3D.h