ACloudViewer: vtkPVImageInteractorStyle Class Reference
vtkPVImageInteractorStyle Class Reference
ParaView-style interactor for 2D image viewing.
#include <vtkPVImageInteractorStyle.h>
Public Member Functions
vtkTypeMacro (vtkPVImageInteractorStyle, vtkInteractorStyleImage)
void PrintSelf (ostream &os, vtkIndent indent) override
void OnLeftButtonDown () override
void OnLeftButtonUp () override
void OnMiddleButtonDown () override
void OnMiddleButtonUp () override
void OnMouseMove () override
void Pan () override
void Rotate () override
Static Public Member Functions
static vtkPVImageInteractorStyle * New ()
Protected Member Functions
vtkPVImageInteractorStyle ()
~vtkPVImageInteractorStyle () override
Protected Attributes
double RotationFactor
Detailed Description
ParaView-style interactor for 2D image viewing.
Provides ParaView-like interaction for images:
Left button: Pan (translate)
Middle button: Rotate around Z-axis (perpendicular to image plane)
Wheel: Zoom
Definition at line 23 of file vtkPVImageInteractorStyle.h.
Constructor & Destructor Documentation
vtkPVImageInteractorStyle()
vtkPVImageInteractorStyle::vtkPVImageInteractorStyle () protected
Definition at line 27 of file vtkPVImageInteractorStyle.cxx.
References RotationFactor.
~vtkPVImageInteractorStyle()
vtkPVImageInteractorStyle::~vtkPVImageInteractorStyle () override protected default
Member Function Documentation
New()
static vtkPVImageInteractorStyle* vtkPVImageInteractorStyle::New () static
OnLeftButtonDown()
void vtkPVImageInteractorStyle::OnLeftButtonDown () override
Event bindings controlling the effects of pressing mouse buttons or moving the mouse.
Definition at line 41 of file vtkPVImageInteractorStyle.cxx.
References x, and y.
OnLeftButtonUp()
void vtkPVImageInteractorStyle::OnLeftButtonUp () override
Definition at line 57 of file vtkPVImageInteractorStyle.cxx.
OnMiddleButtonDown()
void vtkPVImageInteractorStyle::OnMiddleButtonDown () override
Definition at line 68 of file vtkPVImageInteractorStyle.cxx.
References x, and y.
OnMiddleButtonUp()
void vtkPVImageInteractorStyle::OnMiddleButtonUp () override
Definition at line 84 of file vtkPVImageInteractorStyle.cxx.
OnMouseMove()
void vtkPVImageInteractorStyle::OnMouseMove () override
Definition at line 95 of file vtkPVImageInteractorStyle.cxx.
References Pan(), and Rotate().
Pan()
void vtkPVImageInteractorStyle::Pan () override
Override Pan and Rotate methods for custom behavior
Definition at line 219 of file vtkPVImageInteractorStyle.cxx.
References cloudViewer::ml::contrib::Cross(), size, and z.
Referenced by OnMouseMove().
PrintSelf()
void vtkPVImageInteractorStyle::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 35 of file vtkPVImageInteractorStyle.cxx.
References RotationFactor.
Rotate()
void vtkPVImageInteractorStyle::Rotate () override
Definition at line 110 of file vtkPVImageInteractorStyle.cxx.
References RotationFactor, and size.
Referenced by OnMouseMove().
vtkTypeMacro()
vtkPVImageInteractorStyle::vtkTypeMacro (vtkPVImageInteractorStyle , vtkInteractorStyleImage)
Member Data Documentation
RotationFactor
double vtkPVImageInteractorStyle::RotationFactor protected
Definition at line 54 of file vtkPVImageInteractorStyle.h.
Referenced by PrintSelf(), Rotate(), and vtkPVImageInteractorStyle().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/InteractionStyle/vtkPVImageInteractorStyle.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/InteractionStyle/vtkPVImageInteractorStyle.cxx