ACloudViewer: ccGBLSensor Class Reference
ccGBLSensor Class Reference
Ground-based Laser sensor.
#include <ecvGBLSensor.h>
Public Types
enum ROTATION_ORDER { YAW_THEN_PITCH = 0 , PITCH_THEN_YAW = 1 }
The order of inner-rotations of the sensor (body/mirrors)
using NormalGrid = std::vector< CCVector3 >
2D grid of normals
using ColorGrid = std::vector< ecvColor::Rgb >
2D grid of colors
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Public Member Functions
ccGBLSensor (ROTATION_ORDER rotOrder=YAW_THEN_PITCH)
Default constructor.
ccGBLSensor (const ccGBLSensor &sensor)
Copy constructor.
~ccGBLSensor () override=default
Destructor.
CV_CLASS_ENUM getClassID () const override
Returns class ID.
bool isSerializable () const override
Returns whether object is serializable of not.
ccBBox getOwnBB (bool withGLFeatures=false) override
Returns the entity's own bounding-box.
ccBBox getOwnFitBB (ccGLMatrix &trans) override
Returns best-fit bounding-box (if available)
virtual void clearDrawings () override
virtual void hideShowDrawings (CC_DRAW_CONTEXT &context) override
bool applyViewport () override
Apply sensor 'viewport' to a 3D view.
unsigned char checkVisibility (const CCVector3 &P) const override
bool computeAutoParameters (cloudViewer::GenericCloud *theCloud)
Computes angular parameters automatically (all but the angular steps!)
void setPitchRange (PointCoordinateType minPhi, PointCoordinateType maxPhi)
Sets the pitch scanning limits.
PointCoordinateType getMinPitch () const
Returns the minimal pitch limit (in radians)
PointCoordinateType getMaxPitch () const
Returns the maximal pitch limit (in radians)
void setPitchStep (PointCoordinateType dPhi)
Sets the pitch step.
PointCoordinateType getPitchStep () const
Returns the lateral pitch step (in radians)
bool pitchIsShifted () const
void setYawRange (PointCoordinateType minTheta, PointCoordinateType maxTheta)
Sets the yaw scanning limits.
PointCoordinateType getMinYaw () const
Returns the minimal yaw limit (in radians)
PointCoordinateType getMaxYaw () const
Returns the maximal yaw limit (in radians)
void setYawStep (PointCoordinateType dTheta)
Sets the yaw step.
PointCoordinateType getYawStep () const
Returns the yaw step (in radians)
bool yawIsShifted () const
PointCoordinateType getSensorRange () const
Returns the sensor max. range.
void setSensorRange (PointCoordinateType range)
Sets the sensor max. range.
PointCoordinateType getUncertainty () const
Returns the Z-buffer uncertainty on depth values.
void setUncertainty (PointCoordinateType u)
Sets the Z-buffer uncertainty on depth values.
ROTATION_ORDER getRotationOrder () const
Returns the sensor internal rotations order.
void setRotationOrder (ROTATION_ORDER rotOrder)
Sets the sensor internal rotations order.
void projectPoint (const CCVector3 &sourcePoint, CCVector2 &destPoint, PointCoordinateType &depth, double posIndex=0) const
Projects a point in the sensor world.
NormalGrid * projectNormals (cloudViewer::GenericCloud *cloud, const NormalGrid &norms, double posIndex=0) const
Projects a set of point cloud normals in the sensor world.
ColorGrid * projectColors (cloudViewer::GenericCloud *cloud, const ColorGrid &rgbColors) const
bool computeDepthBuffer (cloudViewer::GenericCloud *cloud, int &errorCode, ccPointCloud *projectedCloud=nullptr)
const ccDepthBuffer & getDepthBuffer () const
Returns the associated depth buffer.
void clearDepthBuffer ()
Removes the associated depth buffer.
const cloudViewer::geometry::LineSet & getSensorLegLines () const
const cloudViewer::geometry::LineSet & getSensorAxis () const
const ecvOrientedBBox & getSensorHead () const
Public Member Functions inherited from ccSensor
ccSensor (QString name)
Default constructor.
ccSensor (const ccSensor &sensor)
Copy constructor.
virtual CC_SENSOR_TYPE getType () const
Returns the sensor type.
ccIndexedTransformationBuffer * getPositions ()
Returns associated positions.
void setPositions (ccIndexedTransformationBuffer *positions)
Sets associated positions.
bool addPosition (ccGLMatrix &trans, double index)
Adds a new position (shortcut)
bool getAbsoluteTransformation (ccIndexedTransformation &trans, double index) const
bool getActiveAbsoluteTransformation (ccIndexedTransformation &trans) const
Gets currently active absolute transformation.
bool getActiveAbsoluteCenter (CCVector3 &vec) const
Gets currently active absolute position.
bool getActiveAbsoluteRotation (ccGLMatrix &rotation) const
Gets currently active rotation matrix (without translation)
virtual void setRigidTransformation (const ccGLMatrix &mat)
virtual ccGLMatrix & getRigidTransformation ()
virtual const ccGLMatrix & getRigidTransformation () const
void getIndexBounds (double &minIndex, double &maxIndex) const
Gets index boundaries (shortcut)
double getActiveIndex () const
Sets currently active index (displayed position, etc.)
void setActiveIndex (double index)
Sets currently active index (displayed position, etc.)
void setGraphicScale (PointCoordinateType scale)
Sets the sensor graphic representation scale.
PointCoordinateType getGraphicScale () const
Returns the sensor graphic representation scale.
void setFrameColor (ecvColor::Rgb color)
const ecvColor::Rgb & getFrameColor () const
virtual void applyGLTransformation (const ccGLMatrix &trans) override
Applies a GL transformation to the entity.
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual bool IsEmpty () const
virtual Eigen::Vector3d GetMinBound () const
Returns min bounds for geometry coordinates.
virtual Eigen::Vector2d GetMin2DBound () const
virtual Eigen::Vector3d GetMaxBound () const
Returns max bounds for geometry coordinates.
virtual Eigen::Vector2d GetMax2DBound () const
virtual Eigen::Vector3d GetCenter () const
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const
virtual ccHObject & Transform (const Eigen::Matrix4d &transformation)
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual ccHObject & Translate (const Eigen::Vector3d &translation, bool relative=true)
Apply translation to the geometry coordinates.
virtual ccHObject & Scale (const double s, const Eigen::Vector3d &center)
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center)
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false)
virtual bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner)
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col)
Draws the entity (and its children) bounding-box.
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
virtual void notifyGeometryUpdate ()
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual unsigned getUniqueIDForDisplay () const
Returns object unqiue ID used for display.
virtual const ccGLMatrix & getGLTransformationHistory () const
Returns the transformation 'history' matrix.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual void getDrawingParameters (glDrawParams &params) const
Returns main OpenGL parameters for this entity.
virtual bool hasColors () const
Returns whether colors are enabled or not.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual bool hasNormals () const
Returns whether normals are enabled or not.
virtual bool normalsShown () const
Returns whether normals are shown or not.
virtual void showNormals (bool state)
Sets normals visibility.
virtual void toggleNormals ()
Toggles normals display state.
virtual bool hasDisplayedScalarField () const
Returns whether an active scalar field is available or not.
virtual bool hasScalarFields () const
Returns whether one or more scalar fields are instantiated.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void toggleMaterials ()
Toggles material display state.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Static Public Member Functions
static QString GetErrorString (int errorCode)
Returns the error string corresponding to an error code.
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Protected Member Functions
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
void drawMeOnly (CC_DRAW_CONTEXT &context) override
Draws the entity only (not its children)
bool convertToDepthMapCoords (PointCoordinateType yaw, PointCoordinateType pitch, unsigned &i, unsigned &j) const
Protected Member Functions inherited from ccSensor
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void drawNameIn3D ()
Draws the entity name in 3D.
virtual void onDeletionOf (const ccHObject *obj)
This method is called when another object is deleted.
virtual void onUpdateOf (ccHObject *obj)
This method is called when another object (geometry) is updated.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Protected Attributes
PointCoordinateType m_phiMin
Minimal pitch limit (in radians)
PointCoordinateType m_phiMax
Maximal pitch limit (in radians)
PointCoordinateType m_deltaPhi
Pitch step (in radians)
bool m_pitchAnglesAreShifted
PointCoordinateType m_thetaMin
Minimal yaw limit (in radians)
PointCoordinateType m_thetaMax
Maximal yaw limit (in radians)
PointCoordinateType m_deltaTheta
Yaw step (in radians)
bool m_yawAnglesAreShifted
ROTATION_ORDER m_rotationOrder
Mirrors rotation order.
PointCoordinateType m_sensorRange
Sensor max range.
PointCoordinateType m_uncertainty
Z-buffer uncertainty.
ccDepthBuffer m_depthBuffer
Associated Z-buffer.
ecvOrientedBBox m_obbHead
cloudViewer::geometry::LineSet m_leg
cloudViewer::geometry::LineSet m_axis
Protected Attributes inherited from ccSensor
ccIndexedTransformationBuffer * m_posBuffer
Positions buffer (optional)
ccGLMatrix m_rigidTransformation
Rigid transformation between this sensor and its associated positions.
double m_activeIndex
Active index (for displayed position, etc.)
ecvColor::Rgb m_color
Color of the sensor.
PointCoordinateType m_scale
Sensor graphic representation scale.
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Detailed Description
Ground-based Laser sensor.
An implementation of the ccSensor interface that can be used to represent a depth sensor relying on 2 rotations relatively to two perpendicular axes, such as ground based laser scanners typically.
Definition at line 26 of file ecvGBLSensor.h.
Member Typedef Documentation
ColorGrid
using ccGBLSensor::ColorGrid = std::vector<ecvColor::Rgb>
2D grid of colors
Definition at line 195 of file ecvGBLSensor.h.
NormalGrid
using ccGBLSensor::NormalGrid = std::vector<CCVector3>
2D grid of normals
Definition at line 180 of file ecvGBLSensor.h.
Member Enumeration Documentation
ROTATION_ORDER
enum ccGBLSensor::ROTATION_ORDER
The order of inner-rotations of the sensor (body/mirrors)
Either the first rotation is made around the Z axis (yaw) then around the lateral axis (pitch) as most scanners do today (Leica, Riegl, Faro, etc.). Othewise the opposite order is used (as the very old Mensi Soisic).
Enumerator
YAW_THEN_PITCH
PITCH_THEN_YAW
Definition at line 33 of file ecvGBLSensor.h.
Constructor & Destructor Documentation
ccGBLSensor() [1/2]
ccGBLSensor::ccGBLSensor (ROTATION_ORDER rotOrder = YAW_THEN_PITCH) explicit
Default constructor.
Parameters
rotOrder inner rotations order
ccGBLSensor() [2/2]
ccGBLSensor::ccGBLSensor (const ccGBLSensor & sensor)
Copy constructor.
Warning
The depth buffer is not copied!
Parameters
sensor sensor structure to copy
~ccGBLSensor()
ccGBLSensor::~ccGBLSensor () override default
Destructor.
Member Function Documentation
applyViewport()
bool ccGBLSensor::applyViewport () override virtual
Apply sensor 'viewport' to a 3D view.
Parameters
win 3D view to which to apply the sensor viewport (or the associated 'display' if 0)
Returns
success
Reimplemented from ccSensor.
checkVisibility()
unsigned char ccGBLSensor::checkVisibility (const CCVector3 & P) const override virtual
Determines a 3D point "visibility" relatively to the sensor field of view Relies on the sensor associated depth map (see ccGBLSensor::computeDepthBuffer). The depth map is used to determine the "visiblity" of a 3D point relatively to the laser scanner field of view. This can be useful for filtering out points that shouldn't be compared while computing the distances between two point clouds for instance (for more information on this particular topic, refer to Daniel Girardeau-Montaut's PhD manuscript - Chapter 2, section 2.3.3).
Parameters
P the point to test
Returns
the point's visibility (POINT_VISIBLE, POINT_HIDDEN, POINT_OUT_OF_RANGE or POINT_OUT_OF_FOV)
Reimplemented from ccSensor.
clearDepthBuffer()
void ccGBLSensor::clearDepthBuffer ()
Removes the associated depth buffer.
clearDrawings()
virtual void ccGBLSensor::clearDrawings () override virtual
Reimplemented from ccSensor.
computeAutoParameters()
bool ccGBLSensor::computeAutoParameters (cloudViewer::GenericCloud * theCloud)
Computes angular parameters automatically (all but the angular steps!)
WARNING: this method uses the cloud global iterator.
Referenced by define_ccGBLSensor(), PcdFilter::loadFile(), and PovFilter::loadFile().
computeDepthBuffer()
bool ccGBLSensor::computeDepthBuffer (cloudViewer::GenericCloud * cloud, int & errorCode, ccPointCloud * projectedCloud = nullptr)
Projects a point cloud along the sensor point of view defined by this instance WARNING: this method uses the cloud global iterator
Parameters
cloud a point cloud
errorCode error code in case the returned cloud is 0
projectedCloud optional (empty) cloud to store the projected points
Returns
whether the depth buffer was successfully created or not
convertToDepthMapCoords()
bool ccGBLSensor::convertToDepthMapCoords (PointCoordinateType yaw, PointCoordinateType pitch, unsigned & i, unsigned & j) const protected
Converts 2D angular coordinates (yaw,pitch) in integer depth buffer coordinates
drawMeOnly()
void ccGBLSensor::drawMeOnly (CC_DRAW_CONTEXT & context) override protected virtual
Draws the entity only (not its children)
Reimplemented from ccHObject.
fromFile_MeOnly()
bool ccGBLSensor::fromFile_MeOnly (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override protected virtual
Loads own object data.
Called by 'fromFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
in input file
dataVersion file version
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Reimplemented from ccHObject.
getClassID()
CV_CLASS_ENUM ccGBLSensor::getClassID () const inline override virtual
Returns class ID.
Returns
class unique ID
Reimplemented from ccSensor.
Definition at line 50 of file ecvGBLSensor.h.
References CV_TYPES::GBL_SENSOR.
getDepthBuffer()
const ccDepthBuffer& ccGBLSensor::getDepthBuffer () const inline
Returns the associated depth buffer.
Call ccGBLSensor::computeDepthBuffer first otherwise the returned buffer will be 0.
Definition at line 225 of file ecvGBLSensor.h.
GetErrorString()
static QString ccGBLSensor::GetErrorString (int errorCode) static
Returns the error string corresponding to an error code.
Errors codes are returned by ccGBLSensor::computeDepthBuffer or ccDepthBuffer::fillHoles for instance.
Referenced by define_ccGBLSensor().
getMaxPitch()
PointCoordinateType ccGBLSensor::getMaxPitch () const inline
Returns the maximal pitch limit (in radians)
Definition at line 97 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor().
getMaxYaw()
PointCoordinateType ccGBLSensor::getMaxYaw () const inline
Returns the maximal yaw limit (in radians)
Definition at line 122 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor().
getMinPitch()
PointCoordinateType ccGBLSensor::getMinPitch () const inline
Returns the minimal pitch limit (in radians)
Definition at line 94 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor().
getMinYaw()
PointCoordinateType ccGBLSensor::getMinYaw () const inline
Returns the minimal yaw limit (in radians)
Definition at line 119 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor().
getOwnBB()
ccBBox ccGBLSensor::getOwnBB (bool withGLFeatures = false) override virtual
Returns the entity's own bounding-box.
Children bboxes are ignored.
Parameters
withGLFeatures whether to take into account display-only elements (if any)
Returns
bounding-box
Reimplemented from ccHObject.
getOwnFitBB()
ccBBox ccGBLSensor::getOwnFitBB (ccGLMatrix & trans) override virtual
Returns best-fit bounding-box (if available)
Warning
Only suitable for leaf objects (i.e. without children) Therefore children bboxes are always ignored.
This method is not supported by all entities! (returns the axis-aligned bounding-box by default).
Parameters
[out] trans associated transformation (so that the bounding-box can be displayed in the right position!)
Returns
fit bounding-box
Reimplemented from ccHObject.
getPitchStep()
PointCoordinateType ccGBLSensor::getPitchStep () const inline
Returns the lateral pitch step (in radians)
Definition at line 105 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor(), and PovFilter::saveToFile().
getRotationOrder()
ROTATION_ORDER ccGBLSensor::getRotationOrder () const inline
Returns the sensor internal rotations order.
Definition at line 156 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor(), and PovFilter::saveToFile().
getSensorAxis()
const cloudViewer::geometry::LineSet& ccGBLSensor::getSensorAxis () const inline
Definition at line 233 of file ecvGBLSensor.h.
getSensorHead()
const ecvOrientedBBox& ccGBLSensor::getSensorHead () const inline
Definition at line 236 of file ecvGBLSensor.h.
getSensorLegLines()
const cloudViewer::geometry::LineSet& ccGBLSensor::getSensorLegLines () const inline
Definition at line 230 of file ecvGBLSensor.h.
getSensorRange()
PointCoordinateType ccGBLSensor::getSensorRange () const inline
Returns the sensor max. range.
Definition at line 137 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor().
getUncertainty()
PointCoordinateType ccGBLSensor::getUncertainty () const inline
Returns the Z-buffer uncertainty on depth values.
Definition at line 147 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor().
getYawStep()
PointCoordinateType ccGBLSensor::getYawStep () const inline
Returns the yaw step (in radians)
Definition at line 130 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor(), and PovFilter::saveToFile().
hideShowDrawings()
virtual void ccGBLSensor::hideShowDrawings (CC_DRAW_CONTEXT & context) override virtual
Reimplemented from ccSensor.
isSerializable()
bool ccGBLSensor::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccSensor.
Definition at line 51 of file ecvGBLSensor.h.
minimumFileVersion_MeOnly()
short ccGBLSensor::minimumFileVersion_MeOnly () const override protected virtual
Returns the minimum file version required to save this instance's own data To be overloaded (but still called ;) by subclass. Used internally by minimumFileVersion() to compute the overall minimum.
Reimplemented from ccHObject.
pitchIsShifted()
bool ccGBLSensor::pitchIsShifted () const inline
Returns whether the pitch angles are shifted (i.e. between [0 ; 2pi] instead of [-pi ; pi])
Definition at line 109 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor().
projectColors()
ColorGrid* ccGBLSensor::projectColors (cloudViewer::GenericCloud * cloud, const ColorGrid & rgbColors) const
Projects a set of point cloud colors in the sensor frame defined by this instance WARNING: this method uses the cloud global iterator
Parameters
cloud a point cloud
rgbColors the RGB colors (should have the same size and order as the point cloud)
Returns
a set of RGB colors organized as a bidimensional grid (same size as the depth buffer)
projectNormals()
NormalGrid* ccGBLSensor::projectNormals (cloudViewer::GenericCloud * cloud, const NormalGrid & norms, double posIndex = 0) const
Projects a set of point cloud normals in the sensor world.
WARNING: this method uses the cloud global iterator
Parameters
cloud a point cloud
norms the normals vectors (should have the same size and order as the point cloud)
posIndex (optional) sensor position index (see ccIndexedTransformationBuffer)
Returns
a bidimensional array of 3D vectors (same size as the depth buffer)
projectPoint()
void ccGBLSensor::projectPoint (const CCVector3 & sourcePoint, CCVector2 & destPoint, PointCoordinateType & depth, double posIndex = 0) const
Projects a point in the sensor world.
Parameters
[in] sourcePoint 3D point to project
[out] destPoint projected point in polar coordinates: (theta,phi) = (yaw,pitch) (angles between [-pi,+pi] or [0 ; 2pi] if the corresponding angle is 'shifted')
[out] depth distance between the sensor optical center and the 3D point
[in] posIndex (optional) sensor position index (see ccIndexedTransformationBuffer)
setPitchRange()
void ccGBLSensor::setPitchRange (PointCoordinateType minPhi, PointCoordinateType maxPhi)
Sets the pitch scanning limits.
Parameters
minPhi min pitch angle (in radians)
maxPhi max pitch angle (in radians)
Referenced by define_ccGBLSensor().
setPitchStep()
void ccGBLSensor::setPitchStep (PointCoordinateType dPhi)
Sets the pitch step.
Parameters
dPhi pitch step (in radians)
Referenced by define_ccGBLSensor(), PcdFilter::loadFile(), and PovFilter::loadFile().
setRotationOrder()
void ccGBLSensor::setRotationOrder (ROTATION_ORDER rotOrder) inline
Sets the sensor internal rotations order.
Parameters
rotOrder internal rotations order
Definition at line 161 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor().
setSensorRange()
void ccGBLSensor::setSensorRange (PointCoordinateType range) inline
Sets the sensor max. range.
Parameters
range max. range of the sensor
Definition at line 142 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor().
setUncertainty()
void ccGBLSensor::setUncertainty (PointCoordinateType u) inline
Sets the Z-buffer uncertainty on depth values.
The uncertainty is used to handle numerical inaccuracies
Parameters
u the Z-buffer uncertainty
Definition at line 153 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor(), and PcdFilter::loadFile().
setYawRange()
void ccGBLSensor::setYawRange (PointCoordinateType minTheta, PointCoordinateType maxTheta)
Sets the yaw scanning limits.
Parameters
minTheta min yaw angle (in radians)
maxTheta max yaw angle (in radians)
Referenced by define_ccGBLSensor().
setYawStep()
void ccGBLSensor::setYawStep (PointCoordinateType dTheta)
Sets the yaw step.
Parameters
dTheta yaw step (in radians)
Referenced by define_ccGBLSensor(), PcdFilter::loadFile(), and PovFilter::loadFile().
toFile_MeOnly()
bool ccGBLSensor::toFile_MeOnly (QFile & out, short dataVersion) const override protected virtual
Save own object data.
Called by 'toFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
out output file
dataVersion target file version for compatibility control
Reimplemented from ccHObject.
yawIsShifted()
bool ccGBLSensor::yawIsShifted () const inline
Returns whether the yaw angles are shifted (i.e. between [0 ; 2pi] instead of [-pi ; pi])
Definition at line 134 of file ecvGBLSensor.h.
Referenced by define_ccGBLSensor().
Member Data Documentation
m_axis
cloudViewer::geometry::LineSet ccGBLSensor::m_axis protected
Definition at line 292 of file ecvGBLSensor.h.
m_deltaPhi
PointCoordinateType ccGBLSensor::m_deltaPhi protected
Pitch step (in radians)
Definition at line 262 of file ecvGBLSensor.h.
m_deltaTheta
PointCoordinateType ccGBLSensor::m_deltaTheta protected
Yaw step (in radians)
Definition at line 274 of file ecvGBLSensor.h.
m_depthBuffer
ccDepthBuffer ccGBLSensor::m_depthBuffer protected
Associated Z-buffer.
Definition at line 288 of file ecvGBLSensor.h.
m_leg
cloudViewer::geometry::LineSet ccGBLSensor::m_leg protected
Definition at line 291 of file ecvGBLSensor.h.
m_obbHead
ecvOrientedBBox ccGBLSensor::m_obbHead protected
Definition at line 290 of file ecvGBLSensor.h.
m_phiMax
PointCoordinateType ccGBLSensor::m_phiMax protected
Maximal pitch limit (in radians)
Phi = 0 corresponds to the scanner vertical direction (upward)
Definition at line 260 of file ecvGBLSensor.h.
m_phiMin
PointCoordinateType ccGBLSensor::m_phiMin protected
Minimal pitch limit (in radians)
Phi = 0 corresponds to the scanner vertical direction (upward)
Definition at line 257 of file ecvGBLSensor.h.
m_pitchAnglesAreShifted
bool ccGBLSensor::m_pitchAnglesAreShifted protected
Whether the pitch angular range is shifted (i.e in [0 ; 2pi] instead of [-pi ; pi])
Definition at line 265 of file ecvGBLSensor.h.
m_rotationOrder
ROTATION_ORDER ccGBLSensor::m_rotationOrder protected
Mirrors rotation order.
Definition at line 280 of file ecvGBLSensor.h.
m_sensorRange
PointCoordinateType ccGBLSensor::m_sensorRange protected
Sensor max range.
Definition at line 283 of file ecvGBLSensor.h.
m_thetaMax
PointCoordinateType ccGBLSensor::m_thetaMax protected
Maximal yaw limit (in radians)
Theta = 0 corresponds to the scanner X direction
Definition at line 272 of file ecvGBLSensor.h.
m_thetaMin
PointCoordinateType ccGBLSensor::m_thetaMin protected
Minimal yaw limit (in radians)
Theta = 0 corresponds to the scanner X direction
Definition at line 269 of file ecvGBLSensor.h.
m_uncertainty
PointCoordinateType ccGBLSensor::m_uncertainty protected
Z-buffer uncertainty.
Definition at line 285 of file ecvGBLSensor.h.
m_yawAnglesAreShifted
bool ccGBLSensor::m_yawAnglesAreShifted protected
Whether the yaw range is shifted (i.e in [0 ; 2pi] instead of [-pi ; pi]))
Definition at line 277 of file ecvGBLSensor.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvGBLSensor.h