ACloudViewer: cloudViewer::visualization::gui::Dialog Class Reference
cloudViewer::visualization::gui::Dialog Class Reference
Base class for dialogs.
#include <Dialog.h>
Classes
struct Impl
Public Member Functions
Dialog (const char *title)
virtual ~Dialog ()
Size CalcPreferredSize (const LayoutContext &context, const Constraints &constraints) const override
void Layout (const LayoutContext &context) override
DrawResult Draw (const DrawContext &context) override
virtual void OnWillShow ()
Public Member Functions inherited from cloudViewer::visualization::gui::Widget
Widget ()
Widget (const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Widget ()
virtual void AddChild (std::shared_ptr< Widget > child)
virtual const std::vector< std::shared_ptr< Widget > > GetChildren () const
virtual const Rect & GetFrame () const
Returns the frame size in pixels.
virtual void SetFrame (const Rect &f)
virtual const Color & GetBackgroundColor () const
virtual bool IsDefaultBackgroundColor () const
virtual void SetBackgroundColor (const Color &color)
virtual bool IsVisible () const
virtual void SetVisible (bool vis)
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
virtual void SetTooltip (const char *text)
virtual const char * GetTooltip () const
virtual Size CalcMinimumSize (const LayoutContext &context) const
virtual EventResult Mouse (const MouseEvent &e)
virtual EventResult Key (const KeyEvent &e)
virtual DrawResult Tick (const TickEvent &e)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::gui::Widget
enum class DrawResult { NONE , REDRAW , RELAYOUT }
enum class EventResult { IGNORED , CONSUMED , DISCARD }
Static Public Attributes inherited from cloudViewer::visualization::gui::Widget
static constexpr int DIM_GROW = 10000
Protected Member Functions inherited from cloudViewer::visualization::gui::Widget
void DrawImGuiPushEnabledState ()
void DrawImGuiPopEnabledState ()
void DrawImGuiTooltip ()
Detailed Description
Base class for dialogs.
Definition at line 19 of file Dialog.h.
Constructor & Destructor Documentation
Dialog()
cloudViewer::visualization::gui::Dialog::Dialog (const char * title) explicit
Definition at line 23 of file Dialog.cpp.
~Dialog()
cloudViewer::visualization::gui::Dialog::~Dialog () virtual
Definition at line 25 of file Dialog.cpp.
Member Function Documentation
CalcPreferredSize()
Size cloudViewer::visualization::gui::Dialog::CalcPreferredSize (const LayoutContext & context, const Constraints & constraints) const override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Reimplemented in cloudViewer::visualization::gui::FileDialog.
Definition at line 27 of file Dialog.cpp.
References cloudViewer::visualization::gui::Widget::CalcPreferredSize(), context, cloudViewer::visualization::gui::Widget::GetChildren(), and size.
Draw()
Widget::DrawResult cloudViewer::visualization::gui::Dialog::Draw (const DrawContext & context) override virtual
Draws the widget. If this is a Dear ImGUI widget, this is where the actual event processing happens. Return NONE if no action needs to be taken, REDRAW if the widget needs to be redrawn (e.g. its value changed), and RELAYOUT if the widget wishes to change size.
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 49 of file Dialog.cpp.
References context, and cloudViewer::visualization::gui::Widget::Draw().
Layout()
void cloudViewer::visualization::gui::Dialog::Layout (const LayoutContext & context) override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 37 of file Dialog.cpp.
References context, cloudViewer::visualization::gui::Widget::GetChildren(), cloudViewer::visualization::gui::Widget::GetFrame(), cloudViewer::visualization::gui::Widget::Layout(), and size.
OnWillShow()
void cloudViewer::visualization::gui::Dialog::OnWillShow () virtual
Reimplemented in cloudViewer::visualization::gui::FileDialog.
Definition at line 47 of file Dialog.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Dialog.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Dialog.cpp