ACloudViewer: ccDefaultPluginInterface Class Reference
ccDefaultPluginInterface Class Reference
#include <ecvDefaultPluginInterface.h>
Public Member Functions
virtual ~ccDefaultPluginInterface ()
virtual bool isCore () const override
Is this plugin a core plugin?
virtual QString getName () const override
Returns (short) name (for menu entry, etc.)
virtual QString getDescription () const override
Returns long name/description (for tooltip, etc.)
virtual QIcon getIcon () const override
Returns icon.
virtual ReferenceList getReferences () const override
virtual ContactList getAuthors () const override
virtual ContactList getMaintainers () const override
Public Member Functions inherited from ccPluginInterface
virtual ~ccPluginInterface ()=default
Virtual destructor.
virtual CC_PLUGIN_TYPE getType () const =0
Returns plugin type (standard or OpenGL filter)
virtual bool start ()
Starts the plugin.
virtual void stop ()
Stops the plugin.
virtual ccExternalFactory * getCustomObjectsFactory () const
Returns the plugin's custom object factory (if any)
virtual void registerCommands (ccCommandLineInterface *cmd)
Optional: registers commands (for the command line mode)
Protected Member Functions
ccDefaultPluginInterface (const QString &resourcePath=QString())
Additional Inherited Members
Public Types inherited from ccPluginInterface
typedef QList< Contact > ContactList
using ReferenceList = QList< Reference >
Detailed Description
Definition at line 16 of file ecvDefaultPluginInterface.h.
Constructor & Destructor Documentation
~ccDefaultPluginInterface()
ccDefaultPluginInterface::~ccDefaultPluginInterface () virtual
Definition at line 88 of file ecvDefaultPluginInterface.cpp.
ccDefaultPluginInterface()
ccDefaultPluginInterface::ccDefaultPluginInterface (const QString & resourcePath = QString()) protected
Definition at line 59 of file ecvDefaultPluginInterface.cpp.
References ccDefaultPluginData::doc, and CVLog::Error().
Member Function Documentation
getAuthors()
ccPluginInterface::ContactList ccDefaultPluginInterface::getAuthors () const override virtual
Returns a list of the authors' names and email addresses This is optional. See qDummyPlugin for a real example. Added in v3.1 of the plugin interface.
Reimplemented from ccPluginInterface.
Definition at line 117 of file ecvDefaultPluginInterface.cpp.
References ccDefaultPluginData::contacts().
getDescription()
QString ccDefaultPluginInterface::getDescription () const override virtual
Returns long name/description (for tooltip, etc.)
Implements ccPluginInterface.
Definition at line 104 of file ecvDefaultPluginInterface.cpp.
References ccDefaultPluginData::field().
Referenced by qCSF::getActions(), qMPlane::getActions(), qPCV::getActions(), and ccPluginUIManager::init().
getIcon()
QIcon ccDefaultPluginInterface::getIcon () const override virtual
Returns icon.
Should be reimplemented if necessary
Reimplemented from ccPluginInterface.
Definition at line 108 of file ecvDefaultPluginInterface.cpp.
References ccDefaultPluginData::field().
Referenced by qCSF::getActions(), qMPlane::getActions(), qPCV::getActions(), and ccPluginUIManager::init().
getMaintainers()
ccPluginInterface::ContactList ccDefaultPluginInterface::getMaintainers () const override virtual
Returns a list of the maintainers' names and email addresses This is optional. See qDummyPlugin for a real example. Added in v3.1 of the plugin interface.
Reimplemented from ccPluginInterface.
Definition at line 121 of file ecvDefaultPluginInterface.cpp.
References ccDefaultPluginData::contacts().
getName()
QString ccDefaultPluginInterface::getName () const override virtual
Returns (short) name (for menu entry, etc.)
Implements ccPluginInterface.
Definition at line 100 of file ecvDefaultPluginInterface.cpp.
References ccDefaultPluginData::field().
Referenced by qCSF::getActions(), qMPlane::getActions(), and qPCV::getActions().
getReferences()
ccPluginInterface::ReferenceList ccDefaultPluginInterface::getReferences () const override virtual
Returns a list of references (articles and websites) for the plugin This is optional. See qDummyPlugin for a real example. Added in v3.1 of the plugin interface.
Reimplemented from ccPluginInterface.
Definition at line 112 of file ecvDefaultPluginInterface.cpp.
References ccDefaultPluginData::references().
isCore()
bool ccDefaultPluginInterface::isCore () const override virtual
Is this plugin a core plugin?
Implements ccPluginInterface.
Definition at line 96 of file ecvDefaultPluginInterface.cpp.
References ccDefaultPluginData::doc.
Referenced by ccPluginUIManager::init().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVPluginStub/include/ecvDefaultPluginInterface.h
/root/ACloudViewer/libs/CVPluginStub/src/ecvDefaultPluginInterface.cpp