ACloudViewer: BSplineData< Degree > Class Template Reference
BSplineData< Degree > Class Template Reference
#include <BSplineData.h>
Public Member Functions
BSplineData (void)
void set (int maxDepth, bool dirichlet=false)
Static Public Member Functions
static int Centers (int depth)
static int Corners (int depth)
static int Dimension (int depth)
static int FunctionIndex (int depth, int offset)
static void FactorFunctionIndex (int idx, int &depth, int &offset)
static int TotalFunctionCount (int depth)
static int TotalSampleCount (int depth)
static void FunctionSpan (int depth, int &fStart, int &fEnd)
static void SampleSpan (int depth, int &sStart, int &sEnd)
static int RemapOffset (int depth, int idx, bool &reflect)
Public Attributes
int depth
size_t functionCount
size_t sampleCount
BSplineEvaluationData< Degree >::BSplineComponents * baseBSplines
Detailed Description
template<int Degree>
class BSplineData< Degree >
Definition at line 349 of file BSplineData.h.
Constructor & Destructor Documentation
BSplineData()
template<int Degree> BSplineData< Degree >::BSplineData (void)
Member Function Documentation
Centers()
template<int Degree> static int BSplineData< Degree >::Centers (int depth) inline static
Definition at line 354 of file BSplineData.h.
References BSplineData< Degree >::depth.
Corners()
template<int Degree> static int BSplineData< Degree >::Corners (int depth) inline static
Definition at line 355 of file BSplineData.h.
References BSplineData< Degree >::depth.
Dimension()
template<int Degree> static int BSplineData< Degree >::Dimension (int depth) inline static
Definition at line 356 of file BSplineData.h.
References BSplineData< Degree >::depth.
Referenced by Octree< Real >::_Dimension().
FactorFunctionIndex()
template<int Degree> static void BSplineData< Degree >::FactorFunctionIndex (int idx, int & depth, int & offset) inline static
Definition at line 358 of file BSplineData.h.
References BinaryNode::CenterDepthAndOffset(), BinaryNode::CornerDepthAndOffset(), BSplineData< Degree >::depth, and offset.
FunctionIndex()
template<int Degree> static int BSplineData< Degree >::FunctionIndex (int depth, int offset) inline static
Definition at line 357 of file BSplineData.h.
References BinaryNode::CenterIndex(), BinaryNode::CornerIndex(), BSplineData< Degree >::depth, and offset.
FunctionSpan()
template<int Degree> static void BSplineData< Degree >::FunctionSpan (int depth, int & fStart, int & fEnd) inline static
Definition at line 361 of file BSplineData.h.
References BSplineData< Degree >::depth, and BSplineData< Degree >::TotalFunctionCount().
RemapOffset()
template<int Degree> static int BSplineData< Degree >::RemapOffset (int depth, int idx, bool & reflect) inline static
SampleSpan()
template<int Degree> static void BSplineData< Degree >::SampleSpan (int depth, int & sStart, int & sEnd) inline static
Definition at line 362 of file BSplineData.h.
References BSplineData< Degree >::depth, and BSplineData< Degree >::TotalSampleCount().
set()
template<int Degree> void BSplineData< Degree >::set (int maxDepth, bool dirichlet = false)
TotalFunctionCount()
template<int Degree> static int BSplineData< Degree >::TotalFunctionCount (int depth) inline static
Definition at line 359 of file BSplineData.h.
References BinaryNode::CumulativeCenterCount(), BinaryNode::CumulativeCornerCount(), and BSplineData< Degree >::depth.
Referenced by BSplineData< Degree >::FunctionSpan().
TotalSampleCount()
template<int Degree> static int BSplineData< Degree >::TotalSampleCount (int depth) inline static
Definition at line 360 of file BSplineData.h.
References BinaryNode::CenterCount(), BinaryNode::CornerCount(), and BSplineData< Degree >::depth.
Referenced by BSplineData< Degree >::SampleSpan().
Member Data Documentation
baseBSplines
template<int Degree> BSplineEvaluationData< Degree >::BSplineComponents* BSplineData< Degree >::baseBSplines
Definition at line 368 of file BSplineData.h.
depth
template<int Degree> int BSplineData< Degree >::depth
Definition at line 366 of file BSplineData.h.
Referenced by BSplineData< Degree >::Centers(), BSplineData< Degree >::Corners(), BSplineData< Degree >::Dimension(), BSplineData< Degree >::FactorFunctionIndex(), BSplineData< Degree >::FunctionIndex(), BSplineData< Degree >::FunctionSpan(), BSplineData< Degree >::SampleSpan(), BSplineData< Degree >::TotalFunctionCount(), and BSplineData< Degree >::TotalSampleCount().
functionCount
template<int Degree> size_t BSplineData< Degree >::functionCount
Definition at line 367 of file BSplineData.h.
sampleCount
template<int Degree> size_t BSplineData< Degree >::sampleCount
Definition at line 367 of file BSplineData.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/BSplineData.h