ACloudViewer: cloudViewer::utility::Logger Class Reference
cloudViewer::utility::Logger Class Reference
Logger class should be used as a global singleton object (GetInstance()).
#include <Logging.h>
Classes
struct Impl
Public Member Functions
Logger (Logger const &)=delete
void operator= (Logger const &)=delete
void SetPrintFunction (std::function< void(const std::string &)> print_fcn)
void ResetPrintFunction ()
Reset the print function to the default one (print to console).
const std::function< void(const std::string &)> GetPrintFunction ()
Get the print function used by the Logger.
void SetVerbosityLevel (VerbosityLevel verbosity_level)
VerbosityLevel GetVerbosityLevel () const
Get global verbosity level of CloudViewer.
Static Public Member Functions
static Logger & GetInstance ()
Get Logger global singleton instance.
template<typename... Args>
static void LogError_ (const char *file, int line, const char *function, const char *format, Args &&...args)
template<typename... Args>
static void LogWarning_ (const char *file, int line, const char *function, const char *format, Args &&...args)
template<typename... Args>
static void LogInfo_ (const char *file, int line, const char *function, const char *format, Args &&...args)
template<typename... Args>
static void LogDebug_ (const char *file, int line, const char *function, const char *format, Args &&...args)
Detailed Description
Logger class should be used as a global singleton object (GetInstance()).
Definition at line 129 of file Logging.h.
Constructor & Destructor Documentation
Logger()
cloudViewer::utility::Logger::Logger (Logger const &) delete
Member Function Documentation
GetInstance()
static Logger& cloudViewer::utility::Logger::GetInstance () static
Get Logger global singleton instance.
Referenced by cloudViewer::utility::VerbosityContextManager::Enter(), cloudViewer::utility::VerbosityContextManager::Exit(), cloudViewer::core::Cacher::GetInstance(), cloudViewer::core::MemoryManagerStatistic::GetInstance(), LogDebug_(), LogError_(), LogInfo_(), LogWarning_(), cloudViewer::visualization::app::RunViewer(), and cloudViewer::core::MemoryManagerStatistic::~MemoryManagerStatistic().
GetPrintFunction()
const std::function<void(const std::string &)> cloudViewer::utility::Logger::GetPrintFunction ()
Get the print function used by the Logger.
Referenced by cloudViewer::visualization::app::RunViewer().
GetVerbosityLevel()
VerbosityLevel cloudViewer::utility::Logger::GetVerbosityLevel () const
Get global verbosity level of CloudViewer.
Referenced by cloudViewer::utility::VerbosityContextManager::Enter().
LogDebug_()
template<typename... Args> static void cloudViewer::utility::Logger::LogDebug_ (const char * file, int line, const char * function, const char * format, Args &&... args) inline static
Definition at line 239 of file Logging.h.
References cloudViewer::utility::Debug, format, GetInstance(), and cloudViewer::utility::GetVerbosityLevel().
LogError_()
template<typename... Args> static void cloudViewer::utility::Logger::LogError_ (const char * file, int line, const char * function, const char * format, Args &&... args) inline static
Definition at line 189 of file Logging.h.
References format, and GetInstance().
Referenced by cloudViewer::core::tensor_check::AssertTensorDevice_(), cloudViewer::core::tensor_check::AssertTensorDtype_(), cloudViewer::core::tensor_check::AssertTensorDtypes_(), and cloudViewer::core::tensor_check::AssertTensorShape_().
LogInfo_()
template<typename... Args> static void cloudViewer::utility::Logger::LogInfo_ (const char * file, int line, const char * function, const char * format, Args &&... args) inline static
Definition at line 222 of file Logging.h.
References format, GetInstance(), cloudViewer::utility::GetVerbosityLevel(), and cloudViewer::utility::Info.
LogWarning_()
template<typename... Args> static void cloudViewer::utility::Logger::LogWarning_ (const char * file, int line, const char * function, const char * format, Args &&... args) inline static
Definition at line 204 of file Logging.h.
References format, GetInstance(), cloudViewer::utility::GetVerbosityLevel(), and cloudViewer::utility::Warning.
operator=()
void cloudViewer::utility::Logger::operator= (Logger const &) delete
ResetPrintFunction()
void cloudViewer::utility::Logger::ResetPrintFunction ()
Reset the print function to the default one (print to console).
Referenced by cloudViewer::visualization::app::RunViewer(), and cloudViewer::core::MemoryManagerStatistic::~MemoryManagerStatistic().
SetPrintFunction()
void cloudViewer::utility::Logger::SetPrintFunction (std::function< void(const std::string &)> print_fcn)
Overwrite the default print function, this is useful when you want to redirect prints rather than printing to stdout. For example, in Open3D's python binding, the default print function is replaced with py::print().
Parameters
print_fcn The function for printing. It should take a string input and returns nothing.
Referenced by cloudViewer::visualization::app::RunViewer().
SetVerbosityLevel()
void cloudViewer::utility::Logger::SetVerbosityLevel (VerbosityLevel verbosity_level)
Set global verbosity level of CloudViewer.
Parameters
verbosity_level Messages with equal or less than verbosity_level verbosity will be printed.
Referenced by cloudViewer::utility::VerbosityContextManager::Enter(), and cloudViewer::utility::VerbosityContextManager::Exit().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/Logging.h