ACloudViewer: cloudViewer::core::kernel::CPUReductionEngine Class Reference
cloudViewer::core::kernel::CPUReductionEngine Class Reference
Public Member Functions
CPUReductionEngine (const CPUReductionEngine &)=delete
CPUReductionEngine & operator= (const CPUReductionEngine &)=delete
CPUReductionEngine (const Indexer &indexer)
template<typename func_t , typename scalar_t >
void Run (const func_t &reduce_func, scalar_t identity)
Detailed Description
Definition at line 70 of file ReductionCPU.cpp.
Constructor & Destructor Documentation
CPUReductionEngine() [1/2]
cloudViewer::core::kernel::CPUReductionEngine::CPUReductionEngine (const CPUReductionEngine &) delete
CPUReductionEngine() [2/2]
cloudViewer::core::kernel::CPUReductionEngine::CPUReductionEngine (const Indexer & indexer) inline
Definition at line 74 of file ReductionCPU.cpp.
Member Function Documentation
operator=()
CPUReductionEngine& cloudViewer::core::kernel::CPUReductionEngine::operator= (const CPUReductionEngine &) delete
Run()
template<typename func_t , typename scalar_t > void cloudViewer::core::kernel::CPUReductionEngine::Run (const func_t & reduce_func, scalar_t identity) inline
Definition at line 77 of file ReductionCPU.cpp.
References cloudViewer::utility::EstimateMaxThreads(), cloudViewer::utility::InParallel(), and cloudViewer::core::Indexer::NumOutputElements().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/kernel/ReductionCPU.cpp