ACloudViewer: cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex > Class Template Reference
cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex > Class Template Reference
#include <NeighborSearchAllocator.h>
Public Member Functions
NeighborSearchAllocator (Device device)
void AllocIndices (TIndex **ptr, size_t num)
void AllocIndices (TIndex **ptr, size_t num, TIndex value)
void AllocDistances (T **ptr, size_t num)
void AllocDistances (T **ptr, size_t num, T value)
void AllocCounts (TIndex **ptr, size_t num)
void AllocCounts (TIndex **ptr, size_t num, TIndex value)
const TIndex * IndicesPtr () const
const T * DistancesPtr () const
const TIndex * CountsPtr () const
const Tensor & NeighborsIndex () const
Tensor & NeighborsIndex_ ()
const Tensor & NeighborsDistance () const
Tensor & NeighborsDistance_ ()
const Tensor & NeighborsCount () const
Detailed Description
template<class T, class TIndex = int32_t>
class cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >
Definition at line 19 of file NeighborSearchAllocator.h.
Constructor & Destructor Documentation
NeighborSearchAllocator()
template<class T , class TIndex = int32_t> cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborSearchAllocator (Device device) inline
Definition at line 21 of file NeighborSearchAllocator.h.
Member Function Documentation
AllocCounts() [1/2]
template<class T , class TIndex = int32_t> void cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::AllocCounts (TIndex ** ptr, size_t num) inline
Definition at line 47 of file NeighborSearchAllocator.h.
References cloudViewer::core::Tensor::Empty(), and cloudViewer::core::Tensor::GetDataPtr().
AllocCounts() [2/2]
template<class T , class TIndex = int32_t> void cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::AllocCounts (TIndex ** ptr, size_t num, TIndex value) inline
Definition at line 53 of file NeighborSearchAllocator.h.
References cloudViewer::core::Tensor::Full(), and cloudViewer::core::Tensor::GetDataPtr().
AllocDistances() [1/2]
template<class T , class TIndex = int32_t> void cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::AllocDistances (T ** ptr, size_t num) inline
Definition at line 35 of file NeighborSearchAllocator.h.
References cloudViewer::core::Tensor::Empty(), and cloudViewer::core::Tensor::GetDataPtr().
AllocDistances() [2/2]
template<class T , class TIndex = int32_t> void cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::AllocDistances (T ** ptr, size_t num, T value) inline
Definition at line 41 of file NeighborSearchAllocator.h.
References cloudViewer::core::Tensor::Full(), and cloudViewer::core::Tensor::GetDataPtr().
AllocIndices() [1/2]
template<class T , class TIndex = int32_t> void cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::AllocIndices (TIndex ** ptr, size_t num) inline
Definition at line 23 of file NeighborSearchAllocator.h.
References cloudViewer::core::Tensor::Empty(), and cloudViewer::core::Tensor::GetDataPtr().
AllocIndices() [2/2]
template<class T , class TIndex = int32_t> void cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::AllocIndices (TIndex ** ptr, size_t num, TIndex value) inline
Definition at line 29 of file NeighborSearchAllocator.h.
References cloudViewer::core::Tensor::Full(), and cloudViewer::core::Tensor::GetDataPtr().
CountsPtr()
template<class T , class TIndex = int32_t> const TIndex* cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::CountsPtr () const inline
Definition at line 63 of file NeighborSearchAllocator.h.
References cloudViewer::core::Tensor::GetDataPtr().
DistancesPtr()
template<class T , class TIndex = int32_t> const T* cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::DistancesPtr () const inline
Definition at line 61 of file NeighborSearchAllocator.h.
References cloudViewer::core::Tensor::GetDataPtr().
IndicesPtr()
template<class T , class TIndex = int32_t> const TIndex* cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::IndicesPtr () const inline
Definition at line 59 of file NeighborSearchAllocator.h.
References cloudViewer::core::Tensor::GetDataPtr().
NeighborsCount()
template<class T , class TIndex = int32_t> const Tensor& cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborsCount () const inline
Definition at line 69 of file NeighborSearchAllocator.h.
Referenced by cloudViewer::core::nns::NanoFlannIndex::SearchHybrid().
NeighborsDistance()
template<class T , class TIndex = int32_t> const Tensor& cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborsDistance () const inline
Definition at line 67 of file NeighborSearchAllocator.h.
Referenced by cloudViewer::core::nns::FixedRadiusSearchCPU(), cloudViewer::core::nns::NanoFlannIndex::SearchHybrid(), cloudViewer::core::nns::NanoFlannIndex::SearchKnn(), and cloudViewer::core::nns::NanoFlannIndex::SearchRadius().
NeighborsDistance_()
template<class T , class TIndex = int32_t> Tensor& cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborsDistance_ () inline
Definition at line 68 of file NeighborSearchAllocator.h.
NeighborsIndex()
template<class T , class TIndex = int32_t> const Tensor& cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborsIndex () const inline
Definition at line 65 of file NeighborSearchAllocator.h.
Referenced by cloudViewer::core::nns::FixedRadiusSearchCPU(), cloudViewer::core::nns::NanoFlannIndex::SearchHybrid(), cloudViewer::core::nns::NanoFlannIndex::SearchKnn(), and cloudViewer::core::nns::NanoFlannIndex::SearchRadius().
NeighborsIndex_()
template<class T , class TIndex = int32_t> Tensor& cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborsIndex_ () inline
Definition at line 66 of file NeighborSearchAllocator.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/nns/NeighborSearchAllocator.h