ACloudViewer: G3PointDialog Class Reference
G3PointDialog Class Reference
#include <G3PointDialog.h>
Signals
void kNNEditingFinished ()
void segment ()
void clusterAndOrClean ()
void getBorders ()
void fit ()
void exportResults ()
void wolman ()
void angles ()
void allClicked (bool state)
void onlyOneClicked (bool state)
void onlyOneChanged (int idx)
void transparencyChanged (double transparency)
void drawSurfaces (bool state)
void drawLines (bool state)
void drawPoints (bool state)
void glPointSize (int size)
Public Member Functions
G3PointDialog (QString cloudName, QWidget *parent=nullptr)
~G3PointDialog ()
void readSettings ()
void writeSettings ()
void emitKNNChanged ()
void emitSegment ()
void emitClusterAndOrClean ()
void emitGetBorders ()
void emitAllClicked (bool state)
void emitOnlyOneClicked (bool state)
void emitOnlyOneChanged (int idx)
void emitFit ()
void emitExportResults ()
void emitWolman ()
void emitAngles ()
void emitTransparencyChanged (double transparency)
void emitDrawSurfaces (bool state)
void emitDrawLines (bool state)
void emitDrawPoints (bool state)
void emitGLPointSizeChanged (int size)
void emitSignals ()
double getMaxAngle1 ()
double getMaxAngle2 ()
double getMinFlatness ()
int getNMin ()
int getkNN ()
int getWolmanNbIter ()
int getAnglesNbBins ()
double getRadiusFactor ()
bool isSteepestSlope ()
void enableClusterAndOrClean (bool state)
bool clusterIsChecked ()
bool cleanIsChecked ()
void setOnlyOneMax (int idx)
void enableDrawPointsForOnlyOneGrain (bool state)
Detailed Description
Definition at line 16 of file G3PointDialog.h.
Constructor & Destructor Documentation
G3PointDialog()
G3PointDialog::G3PointDialog (QString cloudName, QWidget * parent = nullptr) explicit
Definition at line 14 of file G3PointDialog.cpp.
References emitAllClicked(), emitAngles(), emitClusterAndOrClean(), emitDrawLines(), emitDrawPoints(), emitDrawSurfaces(), emitExportResults(), emitFit(), emitGetBorders(), emitGLPointSizeChanged(), emitKNNChanged(), emitOnlyOneChanged(), emitOnlyOneClicked(), emitSegment(), emitWolman(), and enableDrawPointsForOnlyOneGrain().
~G3PointDialog()
G3PointDialog::~G3PointDialog ()
Definition at line 61 of file G3PointDialog.cpp.
Member Function Documentation
allClicked
void G3PointDialog::allClicked (bool state) signal
Referenced by emitAllClicked(), emitSignals(), and G3Point::G3PointAction::fit().
angles
void G3PointDialog::angles () signal
Referenced by emitAngles().
cleanIsChecked()
bool G3PointDialog::cleanIsChecked ()
Definition at line 144 of file G3PointDialog.cpp.
Referenced by G3Point::G3PointAction::clusterAndOrClean().
clusterAndOrClean
void G3PointDialog::clusterAndOrClean () signal
Referenced by emitClusterAndOrClean().
clusterIsChecked()
bool G3PointDialog::clusterIsChecked ()
Definition at line 140 of file G3PointDialog.cpp.
Referenced by G3Point::G3PointAction::clusterAndOrClean().
drawLines
void G3PointDialog::drawLines (bool state) signal
Referenced by emitDrawLines(), and G3Point::G3PointAction::fit().
drawPoints
void G3PointDialog::drawPoints (bool state) signal
Referenced by emitDrawPoints(), and G3Point::G3PointAction::fit().
drawSurfaces
void G3PointDialog::drawSurfaces (bool state) signal
Referenced by emitDrawSurfaces(), and G3Point::G3PointAction::fit().
emitAllClicked()
void G3PointDialog::emitAllClicked (bool state) inline
Definition at line 31 of file G3PointDialog.h.
References allClicked().
Referenced by G3PointDialog().
emitAngles()
void G3PointDialog::emitAngles () inline
Definition at line 37 of file G3PointDialog.h.
References angles().
Referenced by G3PointDialog().
emitClusterAndOrClean()
void G3PointDialog::emitClusterAndOrClean () inline
Definition at line 28 of file G3PointDialog.h.
References clusterAndOrClean().
Referenced by G3PointDialog().
emitDrawLines()
void G3PointDialog::emitDrawLines (bool state) inline
Definition at line 42 of file G3PointDialog.h.
References drawLines().
Referenced by G3PointDialog().
emitDrawPoints()
void G3PointDialog::emitDrawPoints (bool state) inline
Definition at line 43 of file G3PointDialog.h.
References drawPoints().
Referenced by G3PointDialog().
emitDrawSurfaces()
void G3PointDialog::emitDrawSurfaces (bool state) inline
Definition at line 41 of file G3PointDialog.h.
References drawSurfaces().
Referenced by G3PointDialog().
emitExportResults()
void G3PointDialog::emitExportResults () inline
Definition at line 35 of file G3PointDialog.h.
References exportResults().
Referenced by G3PointDialog().
emitFit()
void G3PointDialog::emitFit () inline
Definition at line 34 of file G3PointDialog.h.
References fit().
Referenced by G3PointDialog().
emitGetBorders()
void G3PointDialog::emitGetBorders () inline
Definition at line 29 of file G3PointDialog.h.
References getBorders().
Referenced by G3PointDialog().
emitGLPointSizeChanged()
void G3PointDialog::emitGLPointSizeChanged (int size) inline
Definition at line 44 of file G3PointDialog.h.
References glPointSize(), and size.
Referenced by G3PointDialog().
emitKNNChanged()
void G3PointDialog::emitKNNChanged () inline
Definition at line 26 of file G3PointDialog.h.
References kNNEditingFinished().
Referenced by G3PointDialog().
emitOnlyOneChanged()
void G3PointDialog::emitOnlyOneChanged (int idx) inline
Definition at line 33 of file G3PointDialog.h.
References onlyOneChanged().
Referenced by G3PointDialog().
emitOnlyOneClicked()
void G3PointDialog::emitOnlyOneClicked (bool state) inline
Definition at line 32 of file G3PointDialog.h.
References onlyOneClicked().
Referenced by G3PointDialog().
emitSegment()
void G3PointDialog::emitSegment () inline
Definition at line 27 of file G3PointDialog.h.
References segment().
Referenced by G3PointDialog().
emitSignals()
void G3PointDialog::emitSignals ()
Definition at line 148 of file G3PointDialog.cpp.
References allClicked(), and onlyOneChanged().
Referenced by G3Point::G3PointAction::fit().
emitTransparencyChanged()
void G3PointDialog::emitTransparencyChanged (double transparency) inline
Definition at line 38 of file G3PointDialog.h.
References transparencyChanged().
emitWolman()
void G3PointDialog::emitWolman () inline
Definition at line 36 of file G3PointDialog.h.
References wolman().
Referenced by G3PointDialog().
enableClusterAndOrClean()
void G3PointDialog::enableClusterAndOrClean (bool state)
Definition at line 136 of file G3PointDialog.cpp.
Referenced by G3Point::G3PointAction::segment().
enableDrawPointsForOnlyOneGrain()
void G3PointDialog::enableDrawPointsForOnlyOneGrain (bool state)
Definition at line 157 of file G3PointDialog.cpp.
Referenced by G3PointDialog().
exportResults
void G3PointDialog::exportResults () signal
Referenced by emitExportResults().
fit
void G3PointDialog::fit () signal
Referenced by emitFit().
getAnglesNbBins()
int G3PointDialog::getAnglesNbBins ()
Definition at line 120 of file G3PointDialog.cpp.
Referenced by G3Point::G3PointAction::angles().
getBorders
void G3PointDialog::getBorders () signal
Referenced by emitGetBorders().
getkNN()
int G3PointDialog::getkNN ()
Definition at line 114 of file G3PointDialog.cpp.
getMaxAngle1()
double G3PointDialog::getMaxAngle1 ()
Definition at line 100 of file G3PointDialog.cpp.
Referenced by G3Point::G3PointAction::cluster().
getMaxAngle2()
double G3PointDialog::getMaxAngle2 ()
Definition at line 104 of file G3PointDialog.cpp.
Referenced by G3Point::G3PointAction::cleanLabels().
getMinFlatness()
double G3PointDialog::getMinFlatness ()
Definition at line 108 of file G3PointDialog.cpp.
Referenced by G3Point::G3PointAction::cleanLabels().
getNMin()
int G3PointDialog::getNMin ()
Definition at line 112 of file G3PointDialog.cpp.
Referenced by G3Point::G3PointAction::cleanLabels().
getRadiusFactor()
double G3PointDialog::getRadiusFactor ()
Definition at line 128 of file G3PointDialog.cpp.
Referenced by G3Point::G3PointAction::cluster().
getWolmanNbIter()
int G3PointDialog::getWolmanNbIter ()
Definition at line 116 of file G3PointDialog.cpp.
Referenced by G3Point::G3PointAction::wolman().
glPointSize
void G3PointDialog::glPointSize (int size) signal
Referenced by emitGLPointSizeChanged(), and G3Point::G3PointAction::fit().
isSteepestSlope()
bool G3PointDialog::isSteepestSlope ()
Definition at line 132 of file G3PointDialog.cpp.
kNNEditingFinished
void G3PointDialog::kNNEditingFinished () signal
Referenced by emitKNNChanged().
onlyOneChanged
void G3PointDialog::onlyOneChanged (int idx) signal
Referenced by emitOnlyOneChanged(), emitSignals(), and G3Point::G3PointAction::fit().
onlyOneClicked
void G3PointDialog::onlyOneClicked (bool state) signal
Referenced by emitOnlyOneClicked(), and G3Point::G3PointAction::fit().
readSettings()
void G3PointDialog::readSettings ()
Definition at line 63 of file G3PointDialog.cpp.
segment
void G3PointDialog::segment () signal
Referenced by emitSegment().
setOnlyOneMax()
void G3PointDialog::setOnlyOneMax (int idx)
Definition at line 153 of file G3PointDialog.cpp.
References max().
Referenced by G3Point::G3PointAction::fit().
transparencyChanged
void G3PointDialog::transparencyChanged (double transparency) signal
Referenced by emitTransparencyChanged(), and G3Point::G3PointAction::fit().
wolman
void G3PointDialog::wolman () signal
Referenced by emitWolman().
writeSettings()
void G3PointDialog::writeSettings ()
Definition at line 84 of file G3PointDialog.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qG3Point/include/G3PointDialog.h
/root/ACloudViewer/plugins/core/Standard/qG3Point/src/G3PointDialog.cpp