ACloudViewer: Tiler Class Reference
Tiler Class Reference
Class describing the current tiling process.
Public Member Functions
Tiler ()
~Tiler ()=default
size_t tileCount () const
bool init (unsigned width, unsigned height, unsigned Zdim, const QString &absoluteBaseFilename, const CCVector3d &bbMin, const CCVector3d &bbMax, PointTableRef table, const LasHeader &header)
void addPoint (const PointViewPtr &buffer, unsigned pointIndex)
void writeAll ()
Protected Member Functions
unsigned index (unsigned i, unsigned j) const
Protected Attributes
unsigned w
unsigned h
unsigned X
unsigned Y
unsigned Z
CCVector3d bbMinCorner
CCVector3d tileDiag
std::vector< PointViewPtr > tilePointViews
std::vector< QString > fileNames
Detailed Description
Class describing the current tiling process.
Definition at line 731 of file LASFilter.cpp.
Constructor & Destructor Documentation
Tiler()
Tiler::Tiler () inline
Definition at line 733 of file LASFilter.cpp.
~Tiler()
Tiler::~Tiler () default
Member Function Documentation
addPoint()
void Tiler::addPoint (const PointViewPtr & buffer, unsigned pointIndex) inline
Definition at line 789 of file LASFilter.cpp.
References bbMinCorner, cloudViewer::utility::floor(), h, index(), max(), min(), tileDiag, tilePointViews, Tuple3Tpl< Type >::u, w, X, X, and Y.
Referenced by LASFilter::loadFile().
index()
unsigned Tiler::index (unsigned i, unsigned j) const inline protected
Definition at line 826 of file LASFilter.cpp.
References w.
Referenced by addPoint(), and init().
init()
bool Tiler::init (unsigned width, unsigned height, unsigned Zdim, const QString & absoluteBaseFilename, const CCVector3d & bbMin, const CCVector3d & bbMax, PointTableRef table, const LasHeader & header) inline
Definition at line 739 of file LASFilter.cpp.
References bbMinCorner, count, fileNames, h, height, index(), tileDiag, tilePointViews, Tuple3Tpl< Type >::u, w, width, X, Y, and Z.
Referenced by LASFilter::loadFile().
tileCount()
size_t Tiler::tileCount () const inline
Definition at line 737 of file LASFilter.cpp.
References tilePointViews.
writeAll()
void Tiler::writeAll () inline
Definition at line 804 of file LASFilter.cpp.
References CVLog::Error(), fileNames, and tilePointViews.
Referenced by LASFilter::loadFile().
Member Data Documentation
bbMinCorner
CCVector3d Tiler::bbMinCorner protected
Definition at line 830 of file LASFilter.cpp.
Referenced by addPoint(), and init().
fileNames
std::vector<QString> Tiler::fileNames protected
Definition at line 832 of file LASFilter.cpp.
Referenced by init(), and writeAll().
h
unsigned Tiler::h protected
Definition at line 828 of file LASFilter.cpp.
Referenced by addPoint(), and init().
tileDiag
CCVector3d Tiler::tileDiag protected
Definition at line 830 of file LASFilter.cpp.
Referenced by addPoint(), and init().
tilePointViews
std::vector<PointViewPtr> Tiler::tilePointViews protected
Definition at line 831 of file LASFilter.cpp.
Referenced by addPoint(), init(), tileCount(), and writeAll().
w
unsigned Tiler::w protected
Definition at line 828 of file LASFilter.cpp.
Referenced by addPoint(), index(), and init().
X
unsigned Tiler::X protected
Definition at line 829 of file LASFilter.cpp.
Referenced by addPoint(), and init().
Y
unsigned Tiler::Y protected
Definition at line 829 of file LASFilter.cpp.
Referenced by addPoint(), and init().
Z
unsigned Tiler::Z protected
Definition at line 829 of file LASFilter.cpp.
Referenced by init().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/IO/qPDALIO/src/LASFilter.cpp