ACloudViewer: cloudViewer::t::pipelines::slam::Frame Class Reference
cloudViewer::t::pipelines::slam::Frame Class Reference
Frame is a container class storing an intrinsic matrix and several 2D tensors, from depth map, vertex map, to color map, in a customized way.
#include <Frame.h>
Public Member Functions
Frame (int height, int width, const core::Tensor &intrinsics, const core::Device &device)
int GetHeight () const
int GetWidth () const
void SetIntrinsics (const core::Tensor &intrinsics)
core::Tensor GetIntrinsics () const
void SetData (const std::string &name, const core::Tensor &data)
core::Tensor GetData (const std::string &name) const
void SetDataFromImage (const std::string &name, const t::geometry::Image &data)
t::geometry::Image GetDataAsImage (const std::string &name) const
Detailed Description
Frame is a container class storing an intrinsic matrix and several 2D tensors, from depth map, vertex map, to color map, in a customized way.
Definition at line 21 of file Frame.h.
Constructor & Destructor Documentation
Frame()
cloudViewer::t::pipelines::slam::Frame::Frame (int height, int width, const core::Tensor & intrinsics, const core::Device & device) inline
Definition at line 23 of file Frame.h.
Member Function Documentation
GetData()
core::Tensor cloudViewer::t::pipelines::slam::Frame::GetData (const std::string & name) const inline
Definition at line 43 of file Frame.h.
References LogWarning, and name.
Referenced by GetDataAsImage(), and cloudViewer::t::pipelines::slam::Model::SynthesizeModelFrame().
GetDataAsImage()
t::geometry::Image cloudViewer::t::pipelines::slam::Frame::GetDataAsImage (const std::string & name) const inline
Definition at line 58 of file Frame.h.
References GetData(), and name.
Referenced by cloudViewer::t::pipelines::slam::Model::Integrate(), and cloudViewer::t::pipelines::slam::Model::TrackFrameToModel().
GetHeight()
int cloudViewer::t::pipelines::slam::Frame::GetHeight () const inline
Definition at line 32 of file Frame.h.
Referenced by cloudViewer::t::pipelines::slam::Model::SynthesizeModelFrame().
GetIntrinsics()
core::Tensor cloudViewer::t::pipelines::slam::Frame::GetIntrinsics () const inline
Definition at line 38 of file Frame.h.
Referenced by cloudViewer::t::pipelines::slam::Model::Integrate(), cloudViewer::t::pipelines::slam::Model::SynthesizeModelFrame(), and cloudViewer::t::pipelines::slam::Model::TrackFrameToModel().
GetWidth()
int cloudViewer::t::pipelines::slam::Frame::GetWidth () const inline
Definition at line 33 of file Frame.h.
Referenced by cloudViewer::t::pipelines::slam::Model::SynthesizeModelFrame().
SetData()
void cloudViewer::t::pipelines::slam::Frame::SetData (const std::string & name, const core::Tensor & data) inline
Definition at line 40 of file Frame.h.
References name, and cloudViewer::core::Tensor::To().
Referenced by SetDataFromImage(), and cloudViewer::t::pipelines::slam::Model::SynthesizeModelFrame().
SetDataFromImage()
void cloudViewer::t::pipelines::slam::Frame::SetDataFromImage (const std::string & name, const t::geometry::Image & data) inline
Definition at line 53 of file Frame.h.
References cloudViewer::t::geometry::Image::AsTensor(), name, and SetData().
SetIntrinsics()
void cloudViewer::t::pipelines::slam::Frame::SetIntrinsics (const core::Tensor & intrinsics) inline
Definition at line 35 of file Frame.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/t/pipelines/slam/Frame.h