ACloudViewer: cloudViewer::geometry::OctreePointColorLeafNode Class Reference
cloudViewer::geometry::OctreePointColorLeafNode Class Reference
OctreePointColorLeafNode class is an OctreeColorLeafNode containing a list of indices corresponding to the point cloud points contained in this leaf node.
#include <Octree.h>
Public Member Functions
bool operator== (const OctreeLeafNode &other) const override
std::shared_ptr< OctreeLeafNode > Clone () const override
Clone this OctreeLeafNode.
bool ConvertToJsonValue (Json::Value &value) const override
bool ConvertFromJsonValue (const Json::Value &value) override
Public Member Functions inherited from cloudViewer::geometry::OctreeNode
OctreeNode ()
Default Constructor.
virtual ~OctreeNode ()
Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
virtual ~IJsonConvertible ()
virtual std::string ToString () const
Convert to a styled string representation of JSON data for display.
Static Public Member Functions
static std::function< std::shared_ptr< OctreeLeafNode >)> GetInitFunction ()
Get lambda function for initializing OctreeLeafNode.
static std::function< void(std::shared_ptr< OctreeLeafNode >)> GetUpdateFunction (size_t index, const Eigen::Vector3d &color)
Get lambda function for updating OctreeLeafNode.
Static Public Member Functions inherited from cloudViewer::geometry::OctreeColorLeafNode
static std::function< std::shared_ptr< OctreeLeafNode >)> GetInitFunction ()
Get lambda function for initializing OctreeLeafNode.
static std::function< void(std::shared_ptr< OctreeLeafNode >)> GetUpdateFunction (const Eigen::Vector3d &color)
Get lambda function for updating OctreeLeafNode.
Static Public Member Functions inherited from cloudViewer::geometry::OctreeNode
static std::shared_ptr< OctreeNode > ConstructFromJsonValue (const Json::Value &value)
Factory function to construct an OctreeNode by parsing the json value.
Static Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
static bool EigenVector3dFromJsonArray (Eigen::Vector3d &vec, const Json::Value &value)
static bool EigenVector3dToJsonArray (const Eigen::Vector3d &vec, Json::Value &value)
static bool EigenVector4dFromJsonArray (Eigen::Vector4d &vec, const Json::Value &value)
static bool EigenVector4dToJsonArray (const Eigen::Vector4d &vec, Json::Value &value)
static bool EigenMatrix3dFromJsonArray (Eigen::Matrix3d &mat, const Json::Value &value)
static bool EigenMatrix3dToJsonArray (const Eigen::Matrix3d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d_u &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d_u &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d_u &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d_u &mat, Json::Value &value)
Public Attributes
std::vector< size_t > indices_
Associated point indices with this node.
Public Attributes inherited from cloudViewer::geometry::OctreeColorLeafNode
Eigen::Vector3d color_ = Eigen::Vector3d(0, 0, 0)
Detailed Description
OctreePointColorLeafNode class is an OctreeColorLeafNode containing a list of indices corresponding to the point cloud points contained in this leaf node.
Definition at line 217 of file Octree.h.
Member Function Documentation
Clone()
std::shared_ptr< OctreeLeafNode > cloudViewer::geometry::OctreePointColorLeafNode::Clone () const override virtual
Clone this OctreeLeafNode.
Reimplemented from cloudViewer::geometry::OctreeColorLeafNode.
Definition at line 280 of file Octree.cpp.
References cloudViewer::geometry::OctreeColorLeafNode::color_, and indices_.
ConvertFromJsonValue()
bool cloudViewer::geometry::OctreePointColorLeafNode::ConvertFromJsonValue (const Json::Value & value) override virtual
Reimplemented from cloudViewer::geometry::OctreeColorLeafNode.
Definition at line 310 of file Octree.cpp.
References cloudViewer::geometry::OctreeColorLeafNode::color_, cloudViewer::utility::IJsonConvertible::EigenVector3dFromJsonArray(), indices_, LogWarning, and size.
ConvertToJsonValue()
bool cloudViewer::geometry::OctreePointColorLeafNode::ConvertToJsonValue (Json::Value & value) const override virtual
Reimplemented from cloudViewer::geometry::OctreeColorLeafNode.
Definition at line 300 of file Octree.cpp.
References cloudViewer::geometry::OctreeColorLeafNode::color_, cloudViewer::utility::IJsonConvertible::EigenVector3dToJsonArray(), and indices_.
GetInitFunction()
std::function< std::shared_ptr< OctreeLeafNode >)> cloudViewer::geometry::OctreePointColorLeafNode::GetInitFunction () static
Get lambda function for initializing OctreeLeafNode.
When the init function is called, an empty OctreePointColorLeafNode is created.
Definition at line 254 of file Octree.cpp.
Referenced by cloudViewer::geometry::Octree::ConvertFromPointCloud().
GetUpdateFunction()
std::function< void(std::shared_ptr< OctreeLeafNode >)> cloudViewer::geometry::OctreePointColorLeafNode::GetUpdateFunction (size_t index, const Eigen::Vector3d & color) static
Get lambda function for updating OctreeLeafNode.
When called, the update function adds the point cloud point index to the corresponding node index list.
Parameters
idx Point cloud point index associated with node.
color Color of the node.
Definition at line 261 of file Octree.cpp.
References color, cloudViewer::geometry::OctreeColorLeafNode::GetUpdateFunction(), and LogError.
Referenced by cloudViewer::geometry::Octree::ConvertFromPointCloud().
operator==()
bool cloudViewer::geometry::OctreePointColorLeafNode::operator== (const OctreeLeafNode & other) const override virtual
Reimplemented from cloudViewer::geometry::OctreeColorLeafNode.
Definition at line 287 of file Octree.cpp.
References cloudViewer::geometry::OctreeColorLeafNode::color_, and indices_.
Member Data Documentation
indices_
std::vector<size_t> cloudViewer::geometry::OctreePointColorLeafNode::indices_
Associated point indices with this node.
Definition at line 243 of file Octree.h.
Referenced by Clone(), ConvertFromJsonValue(), ConvertToJsonValue(), and operator==().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/Octree.h
/root/ACloudViewer/libs/CV_db/src/Octree.cpp