ACloudViewer: ecvTextureFileSelector Class Reference
ecvTextureFileSelector Class Reference
Advanced editor for color scales.
#include <ecvTextureFileSelector.h>
Signals
void textureFileSelected (int)
Signal emitted when a texture file item is selected.
void textureFileEditorSummoned ()
Public Member Functions
ecvTextureFileSelector (QWidget *parent, QString defaultButtonIconPath=QString())
Default constructor.
void init (const QMap< QString, QString > &texturePathMap)
Inits selector with the Empty texture file path.
bool isEmpty () const
void addItem (const QString &textureFilename, const QString &textureFilepath)
void setSelectedTexturefile (QString textureFilepath)
Sets selected combo box item (scale) by UUID.
QString getTexturefilePath (int index) const
Protected Attributes
QComboBox * m_comboBox
Color scales combo-box.
QToolButton * m_button
Spawn color scale editor button.
Detailed Description
Advanced editor for color scales.
Combo-box + shortcut to color scale editor
Definition at line 16 of file ecvTextureFileSelector.h.
Constructor & Destructor Documentation
ecvTextureFileSelector()
ecvTextureFileSelector::ecvTextureFileSelector (QWidget * parent, QString defaultButtonIconPath = QString())
Default constructor.
Definition at line 15 of file ecvTextureFileSelector.cpp.
References m_button, m_comboBox, and cloudViewer::core::Maximum().
Member Function Documentation
addItem()
void ecvTextureFileSelector::addItem (const QString & textureFilename, const QString & textureFilepath)
Definition at line 63 of file ecvTextureFileSelector.cpp.
References m_comboBox.
Referenced by ccPropertiesTreeDelegate::setEditorData().
getTexturefilePath()
QString ecvTextureFileSelector::getTexturefilePath (int index) const
Definition at line 70 of file ecvTextureFileSelector.cpp.
References m_comboBox.
init()
void ecvTextureFileSelector::init (const QMap< QString, QString > & texturePathMap)
Inits selector with the Empty texture file path.
Definition at line 38 of file ecvTextureFileSelector.cpp.
References m_button, m_comboBox, cloudViewer::t::geometry::path, textureFileEditorSummoned(), and textureFileSelected().
Referenced by ccPropertiesTreeDelegate::createEditor(), and ccPropertiesTreeDelegate::setEditorData().
isEmpty()
bool ecvTextureFileSelector::isEmpty () const
Definition at line 34 of file ecvTextureFileSelector.cpp.
References m_comboBox.
setSelectedTexturefile()
void ecvTextureFileSelector::setSelectedTexturefile (QString textureFilepath)
Sets selected combo box item (scale) by UUID.
Definition at line 78 of file ecvTextureFileSelector.cpp.
References m_comboBox, and textureFileSelected().
Referenced by ccPropertiesTreeDelegate::setEditorData().
textureFileEditorSummoned
void ecvTextureFileSelector::textureFileEditorSummoned () signal
Signal emitted when the user clicks on the 'Texture file loading editor' button
Referenced by ccPropertiesTreeDelegate::createEditor(), and init().
textureFileSelected
void ecvTextureFileSelector::textureFileSelected (int) signal
Signal emitted when a texture file item is selected.
Referenced by ccPropertiesTreeDelegate::createEditor(), init(), and setSelectedTexturefile().
Member Data Documentation
m_button
QToolButton* ecvTextureFileSelector::m_button protected
Spawn color scale editor button.
Definition at line 51 of file ecvTextureFileSelector.h.
Referenced by ecvTextureFileSelector(), and init().
m_comboBox
QComboBox* ecvTextureFileSelector::m_comboBox protected
Color scales combo-box.
Definition at line 48 of file ecvTextureFileSelector.h.
Referenced by addItem(), ecvTextureFileSelector(), getTexturefilePath(), init(), isEmpty(), and setSelectedTexturefile().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvTextureFileSelector.h
/root/ACloudViewer/app/ecvTextureFileSelector.cpp