ACloudViewer: Widgets::GradientWidgetItem Class Reference
Widgets::GradientWidgetItem Class Reference
Public Member Functions
GradientWidgetItem (const GradientData &gradient, QWidget *parent=nullptr)
QString name () const
QColor color1 () const
QColor color2 () const
Detailed Description
Definition at line 55 of file gradientcombobox.cpp.
Constructor & Destructor Documentation
GradientWidgetItem()
Widgets::GradientWidgetItem::GradientWidgetItem (const GradientData & gradient, QWidget * parent = nullptr)
Definition at line 67 of file gradientcombobox.cpp.
References Widgets::GradientData::color1, Widgets::GradientData::color2, cloudViewer::core::Minimum(), and Widgets::GradientLabel::setColors().
Member Function Documentation
color1()
QColor Widgets::GradientWidgetItem::color1 () const inline
Definition at line 60 of file gradientcombobox.cpp.
References Widgets::GradientData::color1.
Referenced by Widgets::GradientComboBox::paintEvent().
color2()
QColor Widgets::GradientWidgetItem::color2 () const inline
Definition at line 61 of file gradientcombobox.cpp.
References Widgets::GradientData::color2.
Referenced by Widgets::GradientComboBox::paintEvent().
name()
QString Widgets::GradientWidgetItem::name () const inline
Definition at line 59 of file gradientcombobox.cpp.
References Widgets::GradientData::name.
Referenced by Widgets::GradientComboBox::setCurrentIndex().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/gradientcombobox.cpp