ACloudViewer: ccFilterByValueDlg Class Reference
ccFilterByValueDlg Class Reference
#include <ecvFilterByValueDlg.h>
Public Types
enum Mode { EXPORT , SPLIT , CANCEL }
Mode.
Public Member Functions
ccFilterByValueDlg (double minRange, double maxRange, double minVal=-1.0e9, double maxVal=1.0e9, QWidget *parent=0)
Default constructor.
Mode mode () const
Returns the selected mode.
Protected Slots
void onExport ()
void onSplit ()
Protected Attributes
Mode m_mode
Detailed Description
Dialog to sepcify a range of SF values and how the corresponding points should be extracted
Definition at line 17 of file ecvFilterByValueDlg.h.
Member Enumeration Documentation
Mode
enum ccFilterByValueDlg::Mode
Mode.
Enumerator
EXPORT
SPLIT
CANCEL
Definition at line 29 of file ecvFilterByValueDlg.h.
Constructor & Destructor Documentation
ccFilterByValueDlg()
ccFilterByValueDlg::ccFilterByValueDlg (double minRange, double maxRange, double minVal = -1.0e9, double maxVal = 1.0e9, QWidget * parent = 0)
Default constructor.
Definition at line 10 of file ecvFilterByValueDlg.cpp.
References onExport(), and onSplit().
Member Function Documentation
mode()
Mode ccFilterByValueDlg::mode () const inline
Returns the selected mode.
Definition at line 32 of file ecvFilterByValueDlg.h.
References m_mode.
onExport
void ccFilterByValueDlg::onExport () inline protected slot
Definition at line 36 of file ecvFilterByValueDlg.h.
References EXPORT, and m_mode.
Referenced by ccFilterByValueDlg().
onSplit
void ccFilterByValueDlg::onSplit () inline protected slot
Definition at line 40 of file ecvFilterByValueDlg.h.
References m_mode, and SPLIT.
Referenced by ccFilterByValueDlg().
Member Data Documentation
m_mode
Mode ccFilterByValueDlg::m_mode protected
Definition at line 46 of file ecvFilterByValueDlg.h.
Referenced by mode(), onExport(), and onSplit().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvFilterByValueDlg.h
/root/ACloudViewer/app/ecvFilterByValueDlg.cpp