ACloudViewer: qMPlane Class Reference
qMPlane Class Reference
#include <qMPlane.h>
Public Member Functions
qMPlane (QObject *parent=nullptr)
~qMPlane () override=default
void onNewSelection (const ccHObject::Container &selectedEntities) override
QList< QAction * > getActions () override
Protected Slots
void doAction ()
Detailed Description
Definition at line 26 of file qMPlane.h.
Constructor & Destructor Documentation
qMPlane()
qMPlane::qMPlane (QObject * parent = nullptr) explicit
Definition at line 21 of file qMPlane.cpp.
~qMPlane()
qMPlane::~qMPlane () override default
Member Function Documentation
doAction
void qMPlane::doAction () protected slot
Definition at line 53 of file qMPlane.cpp.
Referenced by getActions().
getActions()
QList< QAction * > qMPlane::getActions () override
Definition at line 26 of file qMPlane.cpp.
References doAction().
onNewSelection()
void qMPlane::onNewSelection (const ccHObject::Container & selectedEntities) override
Definition at line 37 of file qMPlane.cpp.
References ccObject::isKindOf(), and CV_TYPES::POINT_CLOUD.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qMPlane/qMPlane.h
/root/ACloudViewer/plugins/core/Standard/qMPlane/qMPlane.cpp