ACloudViewer: FileIO Class Reference
FileIO Class Reference
#include <FileIO.h>
Static Public Member Functions
static void setWriterInfo (const QString &applicationName, const QString &version)
static QString writerInfo ()
static QString applicationName ()
static QString version ()
static QString createdBy ()
static QString createdDateTime ()
Detailed Description
Definition at line 15 of file FileIO.h.
Member Function Documentation
applicationName()
QString FileIO::applicationName () static
Definition at line 34 of file FileIO.cpp.
Referenced by MAFilter::saveToFile(), and setWriterInfo().
createdBy()
QString FileIO::createdBy () static
Definition at line 38 of file FileIO.cpp.
References writerInfo().
Referenced by SaveScan(), DxfFilter::saveToFile(), ObjFilter::saveToFile(), and DepthMapFileFilter::saveToFile().
createdDateTime()
QString FileIO::createdDateTime () static
Definition at line 42 of file FileIO.cpp.
References e57::toString().
Referenced by DxfFilter::saveToFile(), ObjFilter::saveToFile(), and DepthMapFileFilter::saveToFile().
setWriterInfo()
void FileIO::setWriterInfo (const QString & applicationName, const QString & version) static
Definition at line 17 of file FileIO.cpp.
References applicationName(), and version().
Referenced by ecvApplication::ecvApplication().
version()
QString FileIO::version () static
Definition at line 36 of file FileIO.cpp.
Referenced by MAFilter::saveToFile(), and setWriterInfo().
writerInfo()
QString FileIO::writerInfo () static
Definition at line 24 of file FileIO.cpp.
Referenced by createdBy(), ImageFileFilter::saveToFile(), and MAFilter::saveToFile().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_io/include/FileIO.h
/root/ACloudViewer/libs/CV_io/src/FileIO.cpp