ACloudViewer: VtkUtils::VtkMultiTextureRenderer Class Reference
VtkUtils::VtkMultiTextureRenderer Class Reference
Multi-texture renderer - Efficient and robust multi-texture mesh rendering support.
#include <VtkMultiTextureRenderer.h>
Classes
struct Impl
struct PBRMaterial
Generic PBR material structure (supports multi-texture)
Public Member Functions
VtkMultiTextureRenderer ()
~VtkMultiTextureRenderer ()
bool ApplyPBRMaterial (vtkSmartPointer< vtkActor > actor, const PBRMaterial &material, vtkSmartPointer< vtkPolyData > polydata, vtkRenderer *renderer=nullptr)
Apply PBR material to actor (Filament style)
Detailed Description
Multi-texture renderer - Efficient and robust multi-texture mesh rendering support.
Features:
Support PBR material rendering with multiple textures
Automatic texture caching and management
Support VTK 9.0+ PBR rendering pipeline
Thread-safe texture loading
Definition at line 37 of file VtkMultiTextureRenderer.h.
Constructor & Destructor Documentation
VtkMultiTextureRenderer()
VtkUtils::VtkMultiTextureRenderer::VtkMultiTextureRenderer ()
Definition at line 91 of file VtkMultiTextureRenderer.cpp.
~VtkMultiTextureRenderer()
VtkUtils::VtkMultiTextureRenderer::~VtkMultiTextureRenderer ()
Definition at line 100 of file VtkMultiTextureRenderer.cpp.
Member Function Documentation
ApplyPBRMaterial()
bool VtkUtils::VtkMultiTextureRenderer::ApplyPBRMaterial (vtkSmartPointer< vtkActor > actor, const PBRMaterial & material, vtkSmartPointer< vtkPolyData > polydata, vtkRenderer * renderer = nullptr)
Apply PBR material to actor (Filament style)
Parameters
actor VTK actor object
material PBR material structure
polydata Polygon data (for texture coordinates)
renderer VTK renderer (for IBL configuration)
Returns
Returns true on success
Definition at line 228 of file VtkMultiTextureRenderer.cpp.
References VtkUtils::VtkMultiTextureRenderer::PBRMaterial::ao, CVLog::Error(), VtkUtils::VtkMultiTextureRenderer::PBRMaterial::metallic, VtkUtils::VtkMultiTextureRenderer::PBRMaterial::opacity, CVLog::Print(), CVLog::PrintDebug(), CVLog::PrintVerbose(), result, VtkUtils::VtkMultiTextureRenderer::PBRMaterial::roughness, and CVLog::Warning().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/PclUtils/renders/pbr/VtkMultiTextureRenderer.h
/root/ACloudViewer/libs/PCLEngine/PclUtils/renders/pbr/VtkMultiTextureRenderer.cpp