ACloudViewer: DisclaimerDialog Class Reference
DisclaimerDialog Class Reference
Dialog for displaying the BRGM disclaimer.
#include <disclaimerDialog.h>
Public Member Functions
DisclaimerDialog (QWidget *parent=0)
Default constructor.
DisclaimerDialog (QWidget *parent=nullptr)
Default constructor.
~DisclaimerDialog ()
DisclaimerDialog (QWidget *parent=nullptr)
~DisclaimerDialog ()
Static Public Member Functions
static bool show (ecvMainAppInterface *app)
static bool show (ecvMainAppInterface *app)
Detailed Description
Dialog for displaying the BRGM disclaimer.
Dialog for displaying the VoxFall disclaimer.
Dialog for displaying the M3C2/UEB disclaimer.
Definition at line 19 of file disclaimerDialog.h.
Constructor & Destructor Documentation
DisclaimerDialog() [1/3]
DisclaimerDialog::DisclaimerDialog (QWidget * parent = 0) inline
Default constructor.
Definition at line 22 of file disclaimerDialog.h.
Referenced by show().
DisclaimerDialog() [2/3]
DisclaimerDialog::DisclaimerDialog (QWidget * parent = nullptr)
Default constructor.
~DisclaimerDialog() [1/2]
DisclaimerDialog::~DisclaimerDialog ()
Definition at line 25 of file qM3C2DisclaimerDialog.cpp.
DisclaimerDialog() [3/3]
DisclaimerDialog::DisclaimerDialog (QWidget * parent = nullptr)
~DisclaimerDialog() [2/2]
DisclaimerDialog::~DisclaimerDialog ()
Member Function Documentation
show() [1/2]
bool DisclaimerDialog::show (ecvMainAppInterface * app) static
Definition at line 27 of file qM3C2DisclaimerDialog.cpp.
References DisclaimerDialog(), and ecvMainAppInterface::getMainWindow().
show() [2/2]
static bool DisclaimerDialog::show (ecvMainAppInterface * app) static
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qFacets/include/disclaimerDialog.h
/root/ACloudViewer/plugins/core/Standard/qM3C2/include/qM3C2DisclaimerDialog.h
/root/ACloudViewer/plugins/core/Standard/qVoxFall/include/qVoxFallDisclaimerDialog.h
/root/ACloudViewer/plugins/core/Standard/qM3C2/src/qM3C2DisclaimerDialog.cpp
/root/ACloudViewer/plugins/core/Standard/qVoxFall/src/qVoxFallDisclaimerDialog.cpp