ACloudViewer: cloudViewer::BoundingBoxTpl< T > Class Template Reference
cloudViewer::BoundingBoxTpl< T > Class Template Reference
Bounding box structure.
#include <BoundingBox.h>
Public Member Functions
BoundingBoxTpl ()
Default constructor.
BoundingBoxTpl (const Vector3Tpl< T > &minCorner, const Vector3Tpl< T > &maxCorner)
Constructor from two vectors (lower min. and upper max. corners)
BoundingBoxTpl< T > operator+ (const BoundingBoxTpl< T > &bbox) const
Returns the 'sum' of this bounding-box and another one.
const BoundingBoxTpl< T > & operator+= (const BoundingBoxTpl< T > &bbox)
In place 'sum' of this bounding-box with another one.
virtual const BoundingBoxTpl< T > & operator+= (const Vector3Tpl< T > &V)
Shifts the bounding box with a vector.
virtual const BoundingBoxTpl< T > & operator-= (const Vector3Tpl< T > &V)
Shifts the bounding box with a vector.
virtual const BoundingBoxTpl< T > & operator*= (T scaleFactor)
Scales the bounding box.
virtual const BoundingBoxTpl< T > & operator*= (const SquareMatrixTpl< T > &mat)
Rotates the bounding box.
void clear ()
Resets the bounding box.
void add (const Vector3Tpl< T > &P)
'Enlarges' the bounding box with a point
const Vector3Tpl< T > & minCorner () const
Returns min corner (const)
const Vector3Tpl< T > & maxCorner () const
Returns max corner (const)
Vector3Tpl< T > & minCorner ()
Returns min corner.
Vector3Tpl< T > & maxCorner ()
Returns max corner.
Vector3Tpl< T > getCenter () const
Returns center.
Vector3Tpl< T > getDiagVec () const
Returns diagonal vector.
T getDiagNorm () const
Returns diagonal length.
double getDiagNormd () const
Returns diagonal length (double precision)
T getMinBoxDim () const
Returns minimal box dimension.
T getMaxBoxDim () const
Returns maximal box dimension.
double computeVolume () const
Returns the bounding-box volume.
void setValidity (bool state)
Sets bonding box validity.
bool isValid () const
Returns whether bounding box is valid or not.
T minDistTo (const BoundingBoxTpl< T > &bbox) const
bool contains (const Vector3Tpl< T > &P) const
Returns whether a points is inside the box or not.
bool containsEigen (const Eigen::Vector3d &point) const
std::vector< std::size_t > GetPointIndicesWithinBoundingBox (const std::vector< Eigen::Vector3d > &points) const
std::vector< std::size_t > GetPointIndicesWithinBoundingBox (const std::vector< Vector3Tpl< T >> &points) const
void addEigen (const Eigen::Vector3d &point)
double volume () const
void SetColor (const Eigen::Vector3d &color)
Sets the bounding box color.
Eigen::Vector3d GetColor () const
Gets the bounding box color.
double getXPercentage (double x) const
double getYPercentage (double y) const
double getZPercentage (double z) const
void getBounds (double bounds[6]) const
Protected Attributes
Vector3Tpl< T > m_bbMin
Lower min. corner.
Vector3Tpl< T > m_bbMax
Upper max. corner.
CCVector3d color_
The color of the bounding box in RGB.
bool m_valid
Validity.
Detailed Description
template<typename T>
class cloudViewer::BoundingBoxTpl< T >
Bounding box structure.
Definition at line 25 of file BoundingBox.h.
Constructor & Destructor Documentation
BoundingBoxTpl() [1/2]
template<typename T > cloudViewer::BoundingBoxTpl< T >::BoundingBoxTpl () inline
Default constructor.
Definition at line 28 of file BoundingBox.h.
BoundingBoxTpl() [2/2]
template<typename T > cloudViewer::BoundingBoxTpl< T >::BoundingBoxTpl (const Vector3Tpl< T > & minCorner, const Vector3Tpl< T > & maxCorner) inline
Constructor from two vectors (lower min. and upper max. corners)
Definition at line 32 of file BoundingBox.h.
Member Function Documentation
add()
template<typename T > void cloudViewer::BoundingBoxTpl< T >::add (const Vector3Tpl< T > & P) inline
'Enlarges' the bounding box with a point
Definition at line 131 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, cloudViewer::BoundingBoxTpl< T >::m_valid, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by cloudViewer::BoundingBoxTpl< T >::addEigen(), ComputeFacetExtensions(), ccPointPairRegistrationDlg::convertToSphereCenter(), ccBBox::CreateFromPoints(), ccPointCloudLODThread::fillNode(), cloudViewer::PointCloudTpl< T >::getBoundingBox(), cloudViewer::ReferenceCloud::getBoundingBox(), ccIndexedTransformationBuffer::getOwnBB(), GrainsAsEllipsoids::GrainsAsEllipsoids(), ccBBox::operator*(), cloudViewer::BoundingBoxTpl< T >::operator*=(), cloudViewer::BoundingBoxTpl< T >::operator+=(), ccMesh::refreshBB(), ccSubMesh::refreshBB(), and GrainsAsEllipsoids::updateBBoxOnlyOne().
addEigen()
template<typename T > void cloudViewer::BoundingBoxTpl< T >::addEigen (const Eigen::Vector3d & point) inline
Definition at line 260 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::add().
clear()
template<typename T > void cloudViewer::BoundingBoxTpl< T >::clear () inline
Resets the bounding box.
(0,0,0) --> (0,0,0)
Definition at line 125 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, and cloudViewer::BoundingBoxTpl< T >::m_valid.
Referenced by ccPointPairRegistrationDlg::convertToSphereCenter(), cloudViewer::PointCloudTpl< T >::getBoundingBox(), cloudViewer::ReferenceCloud::getBoundingBox(), GrainsAsEllipsoids::GrainsAsEllipsoids(), cloudViewer::BoundingBoxTpl< T >::operator*=(), ccMesh::refreshBB(), ccSubMesh::refreshBB(), ecvAnnotationsTool::reset(), ccClipBox::reset(), cloudViewer::visualization::ViewControl::ResetBoundingBox(), cloudViewer::ModelViewerWidget::StartRender(), and GrainsAsEllipsoids::updateBBoxOnlyOne().
computeVolume()
template<typename T > double cloudViewer::BoundingBoxTpl< T >::computeVolume () const inline
Returns the bounding-box volume.
Definition at line 192 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::getDiagVec(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccLibAlgorithms::ApplyScaleMatchingAlgorithm().
contains()
template<typename T > bool cloudViewer::BoundingBoxTpl< T >::contains (const Vector3Tpl< T > & P) const inline
Returns whether a points is inside the box or not.
Warning: box should be valid!
Definition at line 231 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccBoundingBoxEditorDlg::checkBaseInclusion(), ccPointCloud::crop(), ccClipBox::flagPointsInside(), and cloudViewer::BoundingBoxTpl< T >::GetPointIndicesWithinBoundingBox().
containsEigen()
template<typename T > bool cloudViewer::BoundingBoxTpl< T >::containsEigen (const Eigen::Vector3d & point) const inline
Definition at line 236 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
getBounds()
template<typename T > void cloudViewer::BoundingBoxTpl< T >::getBounds (double bounds[6]) const inline
Definition at line 283 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by PclUtils::PCLVis::resetCamera().
getCenter()
template<typename T > Vector3Tpl<T> cloudViewer::BoundingBoxTpl< T >::getCenter () const inline
Returns center.
Definition at line 164 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax, and cloudViewer::BoundingBoxTpl< T >::m_bbMin.
Referenced by MainWindow::addToDB(), ccDBRoot::alignCameraWithEntity(), ccLibAlgorithms::ApplyScaleMatchingAlgorithm(), ecvDisplayTools::ComputeProjectionMatrix(), ccTopologyRelation::constructGraphic(), cloudViewer::OrientedBoundingBox::CreateFromAxisAlignedBoundingBox(), ccHObject::draw(), ccClipBox::drawMeOnly(), ccSphere::drawNameIn3D(), ccPointCloudLODThread::fillNode(), ccPropertiesTreeDelegate::fillWithHObject(), ccBoundingBoxEditorDlg::fromClipboardClicked(), ccPolyline::GetCenter(), ecvDisplayTools::GetRealCameraCenter(), ccApplyTransformationDlg::initFromDipAndDipDir(), cvDistanceTool::initTool(), cvProtractorTool::initTool(), ccPointCloud::interpolateColorsFrom(), ccPointCloudInterpolator::InterpolateScalarFieldsFrom(), MakeSquare(), ccClipBox::move2D(), ccClipBox::move3D(), CommandCrossSection::process(), CommandMatchBBCenters::process(), ccInnerRect2DFinder::process(), ccBoundingBoxEditorDlg::reflectChanges(), cvDistanceTool::reset(), cvProtractorTool::reset(), ccBoundingBoxEditorDlg::toClipboardClicked(), ccClipBox::update(), cc2Point5DimEditor::update2DDisplayZoom(), ecvDisplayTools::UpdateConstellationCenterAndZoom(), ccHObject::updateNameIn3DRecursive(), DistanceMapGenerationDlg::updateZoom(), and ccContourExtractorDlg::zoomOn().
GetColor()
template<typename T > Eigen::Vector3d cloudViewer::BoundingBoxTpl< T >::GetColor () const inline
Gets the bounding box color.
Definition at line 267 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::color_, and Vector3Tpl< double >::fromArray().
Referenced by cloudViewer::geometry::LineSet::CreateFromAxisAlignedBoundingBox(), and cloudViewer::t::geometry::AxisAlignedBoundingBox::FromLegacy().
getDiagNorm()
template<typename T > T cloudViewer::BoundingBoxTpl< T >::getDiagNorm () const inline
Returns diagonal length.
Definition at line 172 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::getDiagVec(), and Vector3Tpl< Type >::norm().
Referenced by MainWindow::addToDB(), ccComparisonDlg::ccComparisonDlg(), ccClipBox::computeArrowsScale(), qM3C2Tools::GuessBestParams(), IcmFilter::LoadCalibratedImages(), PcdFilter::loadFile(), LoadScan(), ccClipBox::move3D(), NormalEstimation::openInputDialog(), GreedyTriangulation::openInputDialog(), MarchingCubeReconstruction::openInputDialog(), PoissonReconstruction::openInputDialog(), ecvDisplayTools::UpdateConstellationCenterAndZoom(), and DistanceMapGenerationDlg::updateZoom().
getDiagNormd()
template<typename T > double cloudViewer::BoundingBoxTpl< T >::getDiagNormd () const inline
Returns diagonal length (double precision)
Definition at line 175 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::getDiagVec(), and Vector3Tpl< Type >::normd().
Referenced by ecvPoissonReconDlg::adjustParams(), ecvDisplayTools::ComputeProjectionMatrix(), qPoissonRecon::doAction(), ccPointCloudLODThread::fillNode(), qM3C2Tools::GuessBestParams(), and ccEntityAction::interpolateSFs().
getDiagVec()
template<typename T > Vector3Tpl<T> cloudViewer::BoundingBoxTpl< T >::getDiagVec () const inline
Returns diagonal vector.
Definition at line 169 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax, and cloudViewer::BoundingBoxTpl< T >::m_bbMin.
Referenced by ComputeFacetExtensions(), cloudViewer::BoundingBoxTpl< T >::computeVolume(), cloudViewer::OrientedBoundingBox::CreateFromAxisAlignedBoundingBox(), ccPropertiesTreeDelegate::fillWithHObject(), ccLibAlgorithms::GetDefaultCloudKernelSize(), cloudViewer::BoundingBoxTpl< T >::getDiagNorm(), cloudViewer::BoundingBoxTpl< T >::getDiagNormd(), cloudViewer::BoundingBoxTpl< T >::getMaxBoxDim(), cloudViewer::BoundingBoxTpl< T >::getMinBoxDim(), cvDistanceTool::initTool(), cvProtractorTool::initTool(), ccPointCloud::interpolateColorsFrom(), ccPointCloudInterpolator::InterpolateScalarFieldsFrom(), MakeSquare(), ccInnerRect2DFinder::process(), ccBoundingBoxEditorDlg::reflectChanges(), cvDistanceTool::reset(), cvProtractorTool::reset(), DxfFilter::saveToFile(), ccPointCloud::setRGBColorByHeight(), qCanupoTools::TrainClassifier(), ccClipBox::update(), DistanceMapGenerationDlg::updateZoom(), cloudViewer::BoundingBoxTpl< T >::volume(), and ccContourExtractorDlg::zoomOn().
getMaxBoxDim()
template<typename T > T cloudViewer::BoundingBoxTpl< T >::getMaxBoxDim () const inline
Returns maximal box dimension.
Definition at line 185 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::getDiagVec(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccLibAlgorithms::ApplyScaleMatchingAlgorithm(), ccNormalVectors::GuessNaiveRadius(), ccOctree::GuessNaiveRadius(), ccOctreeSpinBox::setCloud(), qCanupo2DViewDialog::trainClassifier(), and qCanupoTools::TrainClassifier().
getMinBoxDim()
template<typename T > T cloudViewer::BoundingBoxTpl< T >::getMinBoxDim () const inline
Returns minimal box dimension.
Definition at line 178 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::getDiagVec(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by qFacets::extractFacets().
GetPointIndicesWithinBoundingBox() [1/2]
template<typename T > std::vector<std::size_t> cloudViewer::BoundingBoxTpl< T >::GetPointIndicesWithinBoundingBox (const std::vector< Eigen::Vector3d > & points) const inline
Definition at line 242 of file BoundingBox.h.
References Vector3Tpl< PointCoordinateType >::fromArrayContainer(), and points.
Referenced by ccMesh::Crop(), and ccPointCloud::Crop().
GetPointIndicesWithinBoundingBox() [2/2]
template<typename T > std::vector<std::size_t> cloudViewer::BoundingBoxTpl< T >::GetPointIndicesWithinBoundingBox (const std::vector< Vector3Tpl< T >> & points) const inline
Definition at line 248 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::contains(), and points.
getXPercentage()
template<typename T > double cloudViewer::BoundingBoxTpl< T >::getXPercentage (double x) const inline
Definition at line 271 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, and x.
getYPercentage()
template<typename T > double cloudViewer::BoundingBoxTpl< T >::getYPercentage (double y) const inline
Definition at line 275 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, and y.
getZPercentage()
template<typename T > double cloudViewer::BoundingBoxTpl< T >::getZPercentage (double z) const inline
Definition at line 279 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, and z.
isValid()
template<typename T > bool cloudViewer::BoundingBoxTpl< T >::isValid () const inline
Returns whether bounding box is valid or not.
Definition at line 203 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_valid.
Referenced by ecvAnnotationsTool::addAssociatedEntity(), ccClipBox::addAssociatedEntity(), ccLibAlgorithms::ApplyScaleMatchingAlgorithm(), ccBoundingBoxEditorDlg::ccBoundingBoxEditorDlg(), ccComputeOctreeDlg::ccComputeOctreeDlg(), ccVolumeCalcTool::ccVolumeCalcTool(), ccBoundingBoxEditorDlg::checkBaseInclusion(), ccRasterGrid::ComputeGridSize(), ccEntityAction::computeOctree(), ecvDisplayTools::ComputeProjectionMatrix(), ccVolumeCalcTool::ComputeVolume(), ccVolumeCalcTool::ConvertGridToCloud(), cc2Point5DimEditor::convertGridToCloud(), ccRasterGrid::convertToCloud(), ccMesh::Crop(), ccPointCloud::Crop(), ccPointCloud::crop(), DistanceMapGenerationDlg::DistanceMapGenerationDlg(), ccHObject::draw(), ccHObject::drawBB(), ccClipBox::drawMeOnly(), ccSphere::drawNameIn3D(), cloudViewer::ModelViewerWidget::EndRender(), ccRasterizeTool::ExportGeoTiff(), ccPropertiesTreeDelegate::fillWithHObject(), ccPropertiesTreeDelegate::fillWithViewProperties(), ccRasterizeTool::generateContours(), cloudViewer::PointCloudTpl< T >::getBoundingBox(), cloudViewer::ReferenceCloud::getBoundingBox(), ccSubMesh::getBoundingBox(), ccHObject::getDisplayBB_recursive(), ccKdTree::getNeighborLeaves(), ccIndexedTransformationBuffer::getOwnBB(), ccSubMesh::getOwnBB(), ccHObject::getOwnGlobalBB(), ccShiftedObject::getOwnGlobalBB(), ecvDisplayTools::GetRealCameraCenter(), ecvDisplayTools::GetVisibleObjectsBB(), ccInnerRect2DFinder::init(), ccApplyTransformationDlg::initFromDipAndDipDir(), cvDistanceTool::initTool(), cvProtractorTool::initTool(), cloudViewer::BoundingBoxTpl< T >::minDistTo(), ccClipBox::move2D(), ccClipBox::move3D(), NormalEstimation::openInputDialog(), GreedyTriangulation::openInputDialog(), MarchingCubeReconstruction::openInputDialog(), PoissonReconstruction::openInputDialog(), cloudViewer::BoundingBoxTpl< T >::operator+(), cloudViewer::BoundingBoxTpl< T >::operator+=(), CommandCrossSection::process(), ccInnerRect2DFinder::process(), ccMesh::refreshBB(), cvDistanceTool::reset(), cvProtractorTool::reset(), ccBoundingBoxEditorDlg::setBaseBBox(), PclUtils::PCLVis::SetDataAxesGridProperties(), ecvFilterTool::shiftBox(), ecvDisplayTools::UpdateConstellationCenterAndZoom(), ccBoundingBoxEditorDlg::updateCurrentBBox(), ccVolumeCalcTool::updateGrid(), ccRasterizeTool::updateGrid(), ccHObject::updateNameIn3DRecursive(), ccBoundingBoxEditorDlg::updateXWidth(), ccBoundingBoxEditorDlg::updateYWidth(), DistanceMapGenerationDlg::updateZoom(), ccBoundingBoxEditorDlg::updateZWidth(), ccPointPairRegistrationDlg::zoomGlobalOnRegistrationEntities(), MainWindow::zoomOnEntities(), and MainWindow::zoomOnSelectedEntities().
maxCorner() [1/2]
template<typename T > Vector3Tpl<T>& cloudViewer::BoundingBoxTpl< T >::maxCorner () inline
Returns max corner.
Definition at line 161 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax.
maxCorner() [2/2]
template<typename T > const Vector3Tpl<T>& cloudViewer::BoundingBoxTpl< T >::maxCorner () const inline
Returns max corner (const)
Definition at line 156 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax.
Referenced by ccBoundingBoxEditorDlg::checkBaseInclusion(), PCLDisplayTools::checkEntityNeedUpdate(), ccRasterGrid::ComputeGridSize(), ccEntityAction::computeOctree(), cloudViewer::visualization::ViewControl::ConvertFromViewParameters(), ccBBox::CreateFromPoints(), ccCropTool::Crop(), DistanceMapGenerationDlg::DistanceMapGenerationDlg(), PCLDisplayTools::drawBBox(), ccClipBox::drawMeOnly(), ccRasterizeTool::ExportGeoTiff(), ccQuadric::Fit(), cloudViewer::t::geometry::AxisAlignedBoundingBox::FromLegacy(), cloudViewer::geometry::Octree::GetAxisAlignedBoundingBox(), cloudViewer::geometry::VoxelGrid::GetAxisAlignedBoundingBox(), cloudViewer::PointCloudTpl< T >::getBoundingBox(), cloudViewer::ReferenceCloud::getBoundingBox(), ccMesh::getBoundingBox(), ccSubMesh::getBoundingBox(), cloudViewer::BoundingBoxTpl< T >::getBounds(), ccKdTree::getCellBBox(), GetCellBBoxVisitor::GetCellBBoxVisitor(), cvCutFilter::getInteractorBounds(), cvProbeFilter::getInteractorBounds(), cvStreamlineFilter::getInteractorBounds(), ccPolyline::GetMaxBound(), ccClipBox::getOwnBB(), ccGenericPointCloud::getOwnBB(), ccIndexedTransformationBuffer::getOwnBB(), ccPolyline::getOwnBB(), ccHObject::getOwnGlobalBB(), ccShiftedObject::getOwnGlobalBB(), MakeSquare(), ccClipBox::move3D(), cloudViewer::BoundingBoxTpl< T >::operator+=(), ccBBox::operator+=(), CommandCrossSection::process(), ccBoundingBoxEditorDlg::reflectChanges(), DxfFilter::saveToFile(), ccOctreeSpinBox::setCloud(), PclUtils::PCLVis::SetDataAxesGridProperties(), ccClipBox::shift(), ecvFilterTool::shiftBox(), cloudViewer::geometry::Line3D::SlabAABBBase(), cloudViewer::t::geometry::AxisAlignedBoundingBox::ToLegacy(), DistanceMapGenerationDlg::updateZoom(), DrawMeOnlyVisitor::visit(), GetCellBBoxVisitor::visit(), and GetNeighborLeavesVisitor::visit().
minCorner() [1/2]
template<typename T > Vector3Tpl<T>& cloudViewer::BoundingBoxTpl< T >::minCorner () inline
Returns min corner.
Definition at line 159 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMin.
minCorner() [2/2]
template<typename T > const Vector3Tpl<T>& cloudViewer::BoundingBoxTpl< T >::minCorner () const inline
Returns min corner (const)
Definition at line 154 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMin.
Referenced by ccBoundingBoxEditorDlg::checkBaseInclusion(), PCLDisplayTools::checkEntityNeedUpdate(), ccRasterGrid::ComputeGridSize(), ccEntityAction::computeOctree(), ccVolumeCalcTool::ComputeVolume(), cloudViewer::visualization::ViewControl::ConvertFromViewParameters(), ccRasterGrid::convertToCloud(), ccBBox::CreateFromPoints(), ccCropTool::Crop(), DistanceMapGenerationDlg::DistanceMapGenerationDlg(), PCLDisplayTools::drawBBox(), ccClipBox::drawMeOnly(), ccRasterizeTool::ExportGeoTiff(), ccQuadric::Fit(), cloudViewer::t::geometry::AxisAlignedBoundingBox::FromLegacy(), ccRasterizeTool::generateContours(), cloudViewer::geometry::Octree::GetAxisAlignedBoundingBox(), cloudViewer::geometry::VoxelGrid::GetAxisAlignedBoundingBox(), cloudViewer::PointCloudTpl< T >::getBoundingBox(), cloudViewer::ReferenceCloud::getBoundingBox(), ccMesh::getBoundingBox(), ccSubMesh::getBoundingBox(), cloudViewer::BoundingBoxTpl< T >::getBounds(), ccKdTree::getCellBBox(), GetCellBBoxVisitor::GetCellBBoxVisitor(), cvCutFilter::getInteractorBounds(), cvProbeFilter::getInteractorBounds(), cvStreamlineFilter::getInteractorBounds(), ccPolyline::GetMinBound(), ccClipBox::getOwnBB(), ccGenericPointCloud::getOwnBB(), ccIndexedTransformationBuffer::getOwnBB(), ccPolyline::getOwnBB(), ccHObject::getOwnGlobalBB(), ccShiftedObject::getOwnGlobalBB(), MakeSquare(), ccClipBox::move3D(), cloudViewer::BoundingBoxTpl< T >::operator+=(), ccBBox::operator+=(), CommandCrossSection::process(), CommandRasterize::process(), ccBoundingBoxEditorDlg::reflectChanges(), DxfFilter::saveToFile(), ccOctreeSpinBox::setCloud(), PclUtils::PCLVis::SetDataAxesGridProperties(), ccPointCloud::setRGBColorByHeight(), ccClipBox::shift(), ecvFilterTool::shiftBox(), cloudViewer::geometry::Line3D::SlabAABBBase(), cloudViewer::t::geometry::AxisAlignedBoundingBox::ToLegacy(), ccRasterizeTool::updateGrid(), DistanceMapGenerationDlg::updateZoom(), DrawMeOnlyVisitor::visit(), GetCellBBoxVisitor::visit(), and GetNeighborLeavesVisitor::visit().
minDistTo()
template<typename T > T cloudViewer::BoundingBoxTpl< T >::minDistTo (const BoundingBoxTpl< T > & bbox) const inline
Computes min gap (absolute distance) between this bounding-box and another one
Returns
min gap (>=0) or -1 if at least one of the box is not valid
Definition at line 209 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::isValid(), cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, cloudViewer::BoundingBoxTpl< T >::m_valid, Vector3Tpl< Type >::norm(), and Tuple3Tpl< Type >::u.
Referenced by GetNeighborLeavesVisitor::visit().
operator*=() [1/2]
template<typename T > virtual const BoundingBoxTpl<T>& cloudViewer::BoundingBoxTpl< T >::operator*= (const SquareMatrixTpl< T > & mat) inline virtual
Rotates the bounding box.
Definition at line 99 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::add(), cloudViewer::BoundingBoxTpl< T >::clear(), cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, cloudViewer::BoundingBoxTpl< T >::m_valid, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator*=() [2/2]
template<typename T > virtual const BoundingBoxTpl<T>& cloudViewer::BoundingBoxTpl< T >::operator*= (T scaleFactor) inline virtual
Scales the bounding box.
Reimplemented in ccBBox.
Definition at line 89 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, and cloudViewer::BoundingBoxTpl< T >::m_valid.
operator+()
template<typename T > BoundingBoxTpl<T> cloudViewer::BoundingBoxTpl< T >::operator+ (const BoundingBoxTpl< T > & bbox) const inline
Returns the 'sum' of this bounding-box and another one.
Definition at line 40 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::isValid(), cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, cloudViewer::BoundingBoxTpl< T >::m_valid, cloudViewer::BoundingBoxTpl< T >::setValidity(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
operator+=() [1/2]
template<typename T > const BoundingBoxTpl<T>& cloudViewer::BoundingBoxTpl< T >::operator+= (const BoundingBoxTpl< T > & bbox) inline
In place 'sum' of this bounding-box with another one.
Definition at line 59 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::add(), cloudViewer::BoundingBoxTpl< T >::isValid(), cloudViewer::BoundingBoxTpl< T >::maxCorner(), and cloudViewer::BoundingBoxTpl< T >::minCorner().
operator+=() [2/2]
template<typename T > virtual const BoundingBoxTpl<T>& cloudViewer::BoundingBoxTpl< T >::operator+= (const Vector3Tpl< T > & V) inline virtual
Shifts the bounding box with a vector.
Definition at line 69 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, and cloudViewer::BoundingBoxTpl< T >::m_valid.
operator-=()
template<typename T > virtual const BoundingBoxTpl<T>& cloudViewer::BoundingBoxTpl< T >::operator-= (const Vector3Tpl< T > & V) inline virtual
Shifts the bounding box with a vector.
Definition at line 79 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_bbMax, cloudViewer::BoundingBoxTpl< T >::m_bbMin, and cloudViewer::BoundingBoxTpl< T >::m_valid.
SetColor()
template<typename T > void cloudViewer::BoundingBoxTpl< T >::SetColor (const Eigen::Vector3d & color) inline
Sets the bounding box color.
Definition at line 265 of file BoundingBox.h.
References color, and cloudViewer::BoundingBoxTpl< T >::color_.
Referenced by cloudViewer::t::geometry::AxisAlignedBoundingBox::ToLegacy().
setValidity()
template<typename T > void cloudViewer::BoundingBoxTpl< T >::setValidity (bool state) inline
Sets bonding box validity.
Definition at line 200 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::m_valid.
Referenced by cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::SimpleMesh::addTriangle(), ccSubMesh::addTriangleIndex(), ccSubMesh::clear(), cloudViewer::visualization::ViewControl::ConvertFromViewParameters(), ccBBox::CreateFromPoints(), ccSubMesh::createNewSubMeshFromSelection(), cloudViewer::geometry::Octree::GetAxisAlignedBoundingBox(), cloudViewer::geometry::VoxelGrid::GetAxisAlignedBoundingBox(), ccKdTree::getCellBBox(), cvCutFilter::getInteractorBounds(), cvProbeFilter::getInteractorBounds(), cvStreamlineFilter::getInteractorBounds(), ccGenericPointCloud::getOwnBB(), ccPolyline::getOwnBB(), GrainsAsEllipsoids::GrainsAsEllipsoids(), cloudViewer::PointCloudTpl< T >::invalidateBoundingBox(), ccIndexedTransformationBuffer::invalidateBoundingBox(), ccMesh::onUpdateOf(), ccSubMesh::onUpdateOf(), cloudViewer::BoundingBoxTpl< T >::operator+(), ccMesh::resize(), ccMesh::setAssociatedCloud(), ccSubMesh::setTriangleIndex(), and GrainsAsEllipsoids::updateBBoxOnlyOne().
volume()
template<typename T > double cloudViewer::BoundingBoxTpl< T >::volume () const inline
Definition at line 262 of file BoundingBox.h.
References cloudViewer::BoundingBoxTpl< T >::getDiagVec(), and Vector3Tpl< Type >::prod().
Member Data Documentation
color_
template<typename T > CCVector3d cloudViewer::BoundingBoxTpl< T >::color_ protected
The color of the bounding box in RGB.
Definition at line 298 of file BoundingBox.h.
Referenced by cloudViewer::BoundingBoxTpl< T >::GetColor(), and cloudViewer::BoundingBoxTpl< T >::SetColor().
m_bbMax
template<typename T > Vector3Tpl<T> cloudViewer::BoundingBoxTpl< T >::m_bbMax protected
Upper max. corner.
Definition at line 296 of file BoundingBox.h.
Referenced by cloudViewer::BoundingBoxTpl< T >::add(), cloudViewer::BoundingBoxTpl< T >::clear(), cloudViewer::BoundingBoxTpl< T >::contains(), cloudViewer::BoundingBoxTpl< T >::containsEigen(), cloudViewer::BoundingBoxTpl< T >::getCenter(), cloudViewer::BoundingBoxTpl< T >::getDiagVec(), cloudViewer::BoundingBoxTpl< T >::getXPercentage(), cloudViewer::BoundingBoxTpl< T >::getYPercentage(), cloudViewer::BoundingBoxTpl< T >::getZPercentage(), cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minDistTo(), cloudViewer::BoundingBoxTpl< T >::operator*=(), cloudViewer::BoundingBoxTpl< T >::operator+(), cloudViewer::BoundingBoxTpl< T >::operator+=(), and cloudViewer::BoundingBoxTpl< T >::operator-=().
m_bbMin
template<typename T > Vector3Tpl<T> cloudViewer::BoundingBoxTpl< T >::m_bbMin protected
Lower min. corner.
Definition at line 294 of file BoundingBox.h.
Referenced by cloudViewer::BoundingBoxTpl< T >::add(), cloudViewer::BoundingBoxTpl< T >::clear(), cloudViewer::BoundingBoxTpl< T >::contains(), cloudViewer::BoundingBoxTpl< T >::containsEigen(), cloudViewer::BoundingBoxTpl< T >::getCenter(), cloudViewer::BoundingBoxTpl< T >::getDiagVec(), cloudViewer::BoundingBoxTpl< T >::getXPercentage(), cloudViewer::BoundingBoxTpl< T >::getYPercentage(), cloudViewer::BoundingBoxTpl< T >::getZPercentage(), cloudViewer::BoundingBoxTpl< T >::minCorner(), cloudViewer::BoundingBoxTpl< T >::minDistTo(), cloudViewer::BoundingBoxTpl< T >::operator*=(), cloudViewer::BoundingBoxTpl< T >::operator+(), cloudViewer::BoundingBoxTpl< T >::operator+=(), and cloudViewer::BoundingBoxTpl< T >::operator-=().
m_valid
template<typename T > bool cloudViewer::BoundingBoxTpl< T >::m_valid protected
Validity.
Definition at line 300 of file BoundingBox.h.
Referenced by cloudViewer::BoundingBoxTpl< T >::add(), cloudViewer::BoundingBoxTpl< T >::clear(), cloudViewer::BoundingBoxTpl< T >::isValid(), cloudViewer::BoundingBoxTpl< T >::minDistTo(), cloudViewer::BoundingBoxTpl< T >::operator*=(), cloudViewer::BoundingBoxTpl< T >::operator+(), cloudViewer::BoundingBoxTpl< T >::operator+=(), cloudViewer::BoundingBoxTpl< T >::operator-=(), and cloudViewer::BoundingBoxTpl< T >::setValidity().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/BoundingBox.h