ACloudViewer: DxfProfilesExporter Class Reference
DxfProfilesExporter Class Reference
DXF profiles (of a surface of revolution) exporter.
#include <dxfProfilesExporter.h>
Classes
struct Parameters
Static Public Member Functions
static bool IsEnabled ()
Returns whether DXF support is enabled or not.
static bool SaveVerticalProfiles (const QSharedPointer< DistanceMapGenerationTool::Map > &map, ccPolyline *profile, QString filename, unsigned angularStepCount, double heightStep, double heightShift, const Parameters &params, ecvMainAppInterface *app=0)
static bool SaveHorizontalProfiles (const QSharedPointer< DistanceMapGenerationTool::Map > &map, ccPolyline *profile, QString filename, unsigned heightStepCount, double heightShift, double angularStep_rad, double radToUnitConvFactor, QString angleUnit, const Parameters &params, ecvMainAppInterface *app=0)
Detailed Description
DXF profiles (of a surface of revolution) exporter.
Requires DXF lib support!
Definition at line 23 of file dxfProfilesExporter.h.
Member Function Documentation
IsEnabled()
bool DxfProfilesExporter::IsEnabled () static
Returns whether DXF support is enabled or not.
Definition at line 21 of file dxfProfilesExporter.cpp.
Referenced by DistanceMapGenerationDlg::DistanceMapGenerationDlg().
SaveHorizontalProfiles()
bool DxfProfilesExporter::SaveHorizontalProfiles (const QSharedPointer< DistanceMapGenerationTool::Map > & map, ccPolyline * profile, QString filename, unsigned heightStepCount, double heightShift, double angularStep_rad, double radToUnitConvFactor, QString angleUnit, const Parameters & params, ecvMainAppInterface * app = 0) static
Exports horizontal profiles (of a surface of revolution's map) as a DXF file
Definition at line 607 of file dxfProfilesExporter.cpp.
References HorizStepData::angle_rad, DL_Codes::black, DL_Codes::bylayer, c_margin, c_pageHeight_mm, c_pageMargin_mm, c_pageWidth_mm, c_profileMargin_mm, c_textHeight_mm, c_textMargin_mm, DL_WriterA::close(), DistanceMapGenerationTool::MapCell::count, HorizStepData::deviation, DxfProfilesExporter::Parameters::devLabelMultCoef, DxfProfilesExporter::Parameters::devMagnifyCoef, ecvMainAppInterface::dispToConsole(), DL_VERSION_R12, DL_Writer::dxfEOF(), DL_WriterA::dxfInt(), DL_WriterA::dxfReal(), DL_WriterA::dxfString(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, filename, DL_Codes::green, height, HORIZ_PROFILE_LAYER, DL_Codes::l_gray, LEGEND_LAYER, DxfProfilesExporter::Parameters::legendRealProfileTitle, DxfProfilesExporter::Parameters::legendTheoProfileTitle, M_PI, DL_Dxf::out(), DxfProfilesExporter::Parameters::precision, profile, DxfProfilesExporter::Parameters::profileTitles, DL_Codes::red, s_lineWidth, DxfProfilesExporter::Parameters::scaledDevUnits, DL_Writer::sectionBlocks(), DL_Writer::sectionEnd(), DL_Writer::sectionEntities(), DL_Writer::sectionTables(), DL_Writer::tableAppid(), DL_Writer::tableAppidEntry(), DL_Writer::tableEnd(), DL_Writer::tableLayers(), DL_Writer::tableLinetypes(), DL_Writer::tableStyle(), DistanceMapGenerationTool::MapCell::value, DL_Dxf::writeBlock(), DL_Dxf::writeBlockRecord(), DL_Dxf::writeCircle(), DL_Dxf::writeDimStyle(), DL_Dxf::writeEndBlock(), DL_Dxf::writeHeader(), DL_Dxf::writeLayer(), DL_Dxf::writeLine(), DL_Dxf::writeLinetype(), DL_Dxf::writeObjects(), DL_Dxf::writeObjectsEnd(), DL_Dxf::writePolyline(), DL_Dxf::writePolylineEnd(), DL_Dxf::writeStyle(), DL_Dxf::writeText(), DL_Dxf::writeUcs(), DL_Dxf::writeVertex(), DL_Dxf::writeView(), DL_Dxf::writeVPort(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by DistanceMapGenerationDlg::exportProfilesAsDXF().
SaveVerticalProfiles()
bool DxfProfilesExporter::SaveVerticalProfiles (const QSharedPointer< DistanceMapGenerationTool::Map > & map, ccPolyline * profile, QString filename, unsigned angularStepCount, double heightStep, double heightShift, const Parameters & params, ecvMainAppInterface * app = 0) static
Exports vertical profiles (of a surface of revolution's map) as a DXF file
Definition at line 49 of file dxfProfilesExporter.cpp.
References DL_Codes::black, DL_Codes::bylayer, c_pageHeight_mm, c_pageMargin_mm, c_pageWidth_mm, c_profileMargin_mm, c_textHeight_mm, c_textMargin_mm, DL_WriterA::close(), DistanceMapGenerationTool::MapCell::count, VertStepData::deviation, DxfProfilesExporter::Parameters::devLabelMultCoef, DxfProfilesExporter::Parameters::devMagnifyCoef, ecvMainAppInterface::dispToConsole(), DL_VERSION_R12, DL_Writer::dxfEOF(), DL_WriterA::dxfInt(), DL_WriterA::dxfReal(), DL_WriterA::dxfString(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, filename, DL_Codes::green, height, VertStepData::height, DL_Codes::l_gray, LEGEND_LAYER, DxfProfilesExporter::Parameters::legendRealProfileTitle, DxfProfilesExporter::Parameters::legendTheoProfileTitle, DL_Dxf::out(), DxfProfilesExporter::Parameters::precision, profile, PROFILE_LAYER, DxfProfilesExporter::Parameters::profileTitles, VertStepData::radius_th, DL_Codes::red, s_lineWidth, DxfProfilesExporter::Parameters::scaledDevUnits, DL_Writer::sectionBlocks(), DL_Writer::sectionEnd(), DL_Writer::sectionEntities(), DL_Writer::sectionTables(), DL_Writer::tableAppid(), DL_Writer::tableAppidEntry(), DL_Writer::tableEnd(), DL_Writer::tableLayers(), DL_Writer::tableLinetypes(), DL_Writer::tableStyle(), DistanceMapGenerationTool::MapCell::value, VERT_PROFILE_LAYER, DL_Dxf::writeBlock(), DL_Dxf::writeBlockRecord(), DL_Dxf::writeDimStyle(), DL_Dxf::writeEndBlock(), DL_Dxf::writeHeader(), DL_Dxf::writeLayer(), DL_Dxf::writeLine(), DL_Dxf::writeLinetype(), DL_Dxf::writeObjects(), DL_Dxf::writeObjectsEnd(), DL_Dxf::writePolyline(), DL_Dxf::writePolylineEnd(), DL_Dxf::writeStyle(), DL_Dxf::writeText(), DL_Dxf::writeUcs(), DL_Dxf::writeVertex(), DL_Dxf::writeView(), DL_Dxf::writeVPort(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by DistanceMapGenerationDlg::exportProfilesAsDXF().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qSRA/include/dxfProfilesExporter.h
/root/ACloudViewer/plugins/core/Standard/qSRA/src/dxfProfilesExporter.cpp