ACloudViewer: cvSelectionFilter Class Reference
cvSelectionFilter Class Reference
Advanced selection filtering system.
#include <cvSelectionAlgebra.h>
Public Types
enum FilterType {
ATTRIBUTE_RANGE , GEOMETRIC_AREA , GEOMETRIC_ANGLE , SPATIAL_BBOX ,
SPATIAL_DISTANCE , TOPOLOGY_NEIGHBORS
}
Filter types.
enum ComparisonOp {
EQUAL , NOT_EQUAL , LESS_THAN , LESS_EQUAL ,
GREATER_THAN , GREATER_EQUAL , BETWEEN , OUTSIDE
}
Comparison operators.
Signals
void progressChanged (int percentage)
Emitted when filtering progress changes.
void filteringComplete (const cvSelectionData &result)
Emitted when filtering is complete.
Public Member Functions
cvSelectionFilter (QObject *parent=nullptr)
~cvSelectionFilter () override
cvSelectionData filterByAttributeRange (vtkPolyData *polyData, const cvSelectionData &input, const QString &attributeName, double minValue, double maxValue)
Filter by attribute value range.
cvSelectionData filterByAttributeComparison (vtkPolyData *polyData, const cvSelectionData &input, const QString &attributeName, ComparisonOp op, double value)
Filter by attribute comparison.
cvSelectionData filterByArea (vtkPolyData *polyData, const cvSelectionData &input, double minArea, double maxArea)
Filter cells by area.
cvSelectionData filterByNormalAngle (vtkPolyData *polyData, const cvSelectionData &input, double refX, double refY, double refZ, double minAngleDeg, double maxAngleDeg)
Filter by normal angle relative to reference direction.
cvSelectionData filterByBoundingBox (vtkPolyData *polyData, const cvSelectionData &input, const double bounds[6])
Filter by bounding box.
cvSelectionData filterByDistanceFromPoint (vtkPolyData *polyData, const cvSelectionData &input, double x, double y, double z, double minDistance, double maxDistance)
Filter by distance from point.
cvSelectionData filterByNeighborCount (vtkPolyData *polyData, const cvSelectionData &input, int minNeighbors, int maxNeighbors)
Filter by neighbor count (topology)
Static Public Member Functions
static cvSelectionData combineAND (const cvSelectionData &a, const cvSelectionData &b)
Combine two selections with AND operation.
static cvSelectionData combineOR (const cvSelectionData &a, const cvSelectionData &b)
Combine two selections with OR operation.
static cvSelectionData invert (vtkPolyData *polyData, const cvSelectionData &input)
Invert selection (NOT operation)
static QStringList getAttributeNames (vtkPolyData *polyData, bool pointData=true)
Get attribute names available in polyData.
Detailed Description
Advanced selection filtering system.
Provides various filters to refine selections:
Attribute-based filtering (scalar values, colors, etc.)
Geometric filtering (area, angle, distance)
Spatial filtering (bounding box, distance from point)
Combinatorial filtering (AND, OR, NOT operations)
Based on ParaView's selection filter functionality.
Definition at line 271 of file cvSelectionAlgebra.h.
Member Enumeration Documentation
ComparisonOp
enum cvSelectionFilter::ComparisonOp
Comparison operators.
Enumerator
EQUAL
NOT_EQUAL
LESS_THAN
LESS_EQUAL
GREATER_THAN
GREATER_EQUAL
BETWEEN
OUTSIDE
Definition at line 290 of file cvSelectionAlgebra.h.
FilterType
enum cvSelectionFilter::FilterType
Filter types.
Enumerator
ATTRIBUTE_RANGE
Filter by attribute value range.
GEOMETRIC_AREA
Filter by cell area.
GEOMETRIC_ANGLE
Filter by normal angle.
SPATIAL_BBOX
Filter by bounding box.
SPATIAL_DISTANCE
Filter by distance from point.
TOPOLOGY_NEIGHBORS
Filter by neighbor count.
Definition at line 278 of file cvSelectionAlgebra.h.
Constructor & Destructor Documentation
cvSelectionFilter()
cvSelectionFilter::cvSelectionFilter (QObject * parent = nullptr) explicit
Definition at line 1043 of file cvSelectionAlgebra.cpp.
References CVLog::PrintVerbose().
~cvSelectionFilter()
cvSelectionFilter::~cvSelectionFilter () override
Definition at line 1048 of file cvSelectionAlgebra.cpp.
Member Function Documentation
combineAND()
cvSelectionData cvSelectionFilter::combineAND (const cvSelectionData & a, const cvSelectionData & b) static
Combine two selections with AND operation.
Definition at line 1438 of file cvSelectionAlgebra.cpp.
References a, cvSelectionData::count(), cvSelectionData::fieldAssociation(), cvSelectionData::ids(), cvSelectionData::isEmpty(), CVLog::PrintVerbose(), qSetFromVector(), qVectorFromSet(), and result.
combineOR()
cvSelectionData cvSelectionFilter::combineOR (const cvSelectionData & a, const cvSelectionData & b) static
Combine two selections with OR operation.
Definition at line 1463 of file cvSelectionAlgebra.cpp.
References a, cvSelectionData::count(), cvSelectionData::fieldAssociation(), cvSelectionData::ids(), cvSelectionData::isEmpty(), CVLog::PrintVerbose(), qSetFromVector(), qVectorFromSet(), and result.
filterByArea()
cvSelectionData cvSelectionFilter::filterByArea (vtkPolyData * polyData, const cvSelectionData & input, double minArea, double maxArea)
Filter cells by area.
Definition at line 1175 of file cvSelectionAlgebra.cpp.
References cvSelectionData::CELLS, cvSelectionData::fieldAssociation(), cvSelectionData::ids(), cvSelectionData::isEmpty(), CVLog::PrintVerbose(), and CVLog::Warning().
filterByAttributeComparison()
cvSelectionData cvSelectionFilter::filterByAttributeComparison (vtkPolyData * polyData, const cvSelectionData & input, const QString & attributeName, ComparisonOp op, double value)
Filter by attribute comparison.
Definition at line 1101 of file cvSelectionAlgebra.cpp.
References e, EQUAL, cvSelectionData::fieldAssociation(), GREATER_EQUAL, GREATER_THAN, cvSelectionData::ids(), cvSelectionData::isEmpty(), LESS_EQUAL, LESS_THAN, NOT_EQUAL, cvSelectionData::POINTS, CVLog::PrintVerbose(), and CVLog::Warning().
filterByAttributeRange()
cvSelectionData cvSelectionFilter::filterByAttributeRange (vtkPolyData * polyData, const cvSelectionData & input, const QString & attributeName, double minValue, double maxValue)
Filter by attribute value range.
Definition at line 1051 of file cvSelectionAlgebra.cpp.
References cvSelectionData::fieldAssociation(), cvSelectionData::ids(), cvSelectionData::isEmpty(), cvSelectionData::POINTS, CVLog::PrintVerbose(), and CVLog::Warning().
filterByBoundingBox()
cvSelectionData cvSelectionFilter::filterByBoundingBox (vtkPolyData * polyData, const cvSelectionData & input, const double bounds[6])
Filter by bounding box.
Definition at line 1266 of file cvSelectionAlgebra.cpp.
References cvSelectionData::fieldAssociation(), cvSelectionData::ids(), cvSelectionData::isEmpty(), cvSelectionData::POINTS, and CVLog::PrintVerbose().
filterByDistanceFromPoint()
cvSelectionData cvSelectionFilter::filterByDistanceFromPoint (vtkPolyData * polyData, const cvSelectionData & input, double x, double y, double z, double minDistance, double maxDistance)
Filter by distance from point.
Definition at line 1329 of file cvSelectionAlgebra.cpp.
References cvSelectionData::fieldAssociation(), cvSelectionData::ids(), cvSelectionData::isEmpty(), cvSelectionData::POINTS, CVLog::PrintVerbose(), x, y, and z.
filterByNeighborCount()
cvSelectionData cvSelectionFilter::filterByNeighborCount (vtkPolyData * polyData, const cvSelectionData & input, int minNeighbors, int maxNeighbors)
Filter by neighbor count (topology)
Definition at line 1399 of file cvSelectionAlgebra.cpp.
References cvSelectionData::CELLS, cvSelectionData::fieldAssociation(), cvSelectionData::ids(), cvSelectionData::isEmpty(), CVLog::PrintVerbose(), and CVLog::Warning().
filterByNormalAngle()
cvSelectionData cvSelectionFilter::filterByNormalAngle (vtkPolyData * polyData, const cvSelectionData & input, double refX, double refY, double refZ, double minAngleDeg, double maxAngleDeg)
Filter by normal angle relative to reference direction.
Definition at line 1213 of file cvSelectionAlgebra.cpp.
References cvSelectionData::CELLS, cvSelectionData::fieldAssociation(), cvSelectionData::ids(), cvSelectionData::isEmpty(), normal, normals, CVLog::PrintVerbose(), and CVLog::Warning().
filteringComplete
void cvSelectionFilter::filteringComplete (const cvSelectionData & result) signal
Emitted when filtering is complete.
getAttributeNames()
QStringList cvSelectionFilter::getAttributeNames (vtkPolyData * polyData, bool pointData = true) static
Get attribute names available in polyData.
Definition at line 1514 of file cvSelectionAlgebra.cpp.
References data.
invert()
cvSelectionData cvSelectionFilter::invert (vtkPolyData * polyData, const cvSelectionData & input) static
Invert selection (NOT operation)
Definition at line 1487 of file cvSelectionAlgebra.cpp.
References cvSelectionData::count(), cvSelectionData::fieldAssociation(), cvSelectionData::ids(), cvSelectionData::isEmpty(), cvSelectionData::POINTS, CVLog::PrintVerbose(), and qSetFromVector().
progressChanged
void cvSelectionFilter::progressChanged (int percentage) signal
Emitted when filtering progress changes.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvSelectionAlgebra.h
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvSelectionAlgebra.cpp