ACloudViewer: ecvColor::Convert Class Reference
ecvColor::Convert Class Reference
Color space conversion.
#include <ecvColorTypes.h>
Static Public Member Functions
static Rgb hsl2rgb (float H, float S, float L)
Converts a HSL color to RGB color space.
static Rgb hsv2rgb (float H, float S, float V)
Converts a HSV color to RGB color space.
Static Protected Member Functions
static float hue2rgb (float m1, float m2, float hue)
Method used by hsl2rgb.
Detailed Description
Color space conversion.
Definition at line 258 of file ecvColorTypes.h.
Member Function Documentation
hsl2rgb()
static Rgb ecvColor::Convert::hsl2rgb (float H, float S, float L) inline static
Converts a HSL color to RGB color space.
Parameters
H [out] hue [0;360[
S [out] saturation [0;1]
L [out] light [0;1]
Returns
RGB color (unsigned byte)
Definition at line 266 of file ecvColorTypes.h.
References hue2rgb(), and ecvColor::MAX.
Referenced by FacetsClassifier::GenerateSubfamilyColor().
hsv2rgb()
static Rgb ecvColor::Convert::hsv2rgb (float H, float S, float V) inline static
Converts a HSV color to RGB color space.
Parameters
H [out] hue [0;360[
S [out] saturation [0;1]
V [out] value [0;1]
Returns
RGB color (unsigned byte)
Definition at line 286 of file ecvColorTypes.h.
References ecvColor::RgbTpl< Type >::b, ecvColor::RgbTpl< Type >::g, ecvColor::MAX, and ecvColor::RgbTpl< Type >::r.
hue2rgb()
static float ecvColor::Convert::hue2rgb (float m1, float m2, float hue) inline static protected
Method used by hsl2rgb.
Definition at line 336 of file ecvColorTypes.h.
Referenced by hsl2rgb().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/eCV_db/include/ecvColorTypes.h