ACloudViewer: ccPclPluginInterface Class Reference
ccPclPluginInterface Class Reference abstract
Pcl ECV plugin interface.
#include <ecvPclPluginInterface.h>
Public Member Functions
ccPclPluginInterface (const QString &resourcePath=QString())
Default constructor.
virtual ~ccPclPluginInterface ()=default
Destructor.
virtual CC_PLUGIN_TYPE getType () const override
Returns plugin type (standard or OpenGL filter)
virtual void setMainAppInterface (ecvMainAppInterface *app)
Sets application entry point.
virtual ecvMainAppInterface * getMainAppInterface ()
A callback pointer to the main app interface for use by plugins.
virtual QVector< QList< QAction * > > getActions ()=0
Get a list of actions for this plugin.
virtual QVector< QString > getModuleNames ()=0
virtual void onNewSelection (const ccHObject::Container &selectedEntities)
virtual void dispToConsole (QString message, ecvMainAppInterface::ConsoleMessageLevel level=ecvMainAppInterface::STD_CONSOLE_MESSAGE)
Shortcut to ecvMainAppInterface::dispToConsole.
Public Member Functions inherited from ccDefaultPluginInterface
virtual ~ccDefaultPluginInterface ()
virtual bool isCore () const override
Is this plugin a core plugin?
virtual QString getName () const override
Returns (short) name (for menu entry, etc.)
virtual QString getDescription () const override
Returns long name/description (for tooltip, etc.)
virtual QIcon getIcon () const override
Returns icon.
virtual ReferenceList getReferences () const override
virtual ContactList getAuthors () const override
virtual ContactList getMaintainers () const override
Public Member Functions inherited from ccPluginInterface
virtual ~ccPluginInterface ()=default
Virtual destructor.
virtual bool start ()
Starts the plugin.
virtual void stop ()
Stops the plugin.
virtual ccExternalFactory * getCustomObjectsFactory () const
Returns the plugin's custom object factory (if any)
virtual void registerCommands (ccCommandLineInterface *cmd)
Optional: registers commands (for the command line mode)
Protected Attributes
ecvMainAppInterface * m_app
Main application interface.
Additional Inherited Members
Public Types inherited from ccPluginInterface
typedef QList< Contact > ContactList
using ReferenceList = QList< Reference >
Protected Member Functions inherited from ccDefaultPluginInterface
ccDefaultPluginInterface (const QString &resourcePath=QString())
Detailed Description
Pcl ECV plugin interface.
Version 1.4 The plugin is now responsible for its own actions (QAction ;) and the associated ecvMainAppInterface member should give it access to everything it needs in the main application.
Definition at line 27 of file ecvPclPluginInterface.h.
Constructor & Destructor Documentation
ccPclPluginInterface()
ccPclPluginInterface::ccPclPluginInterface (const QString & resourcePath = QString()) inline
Default constructor.
Definition at line 30 of file ecvPclPluginInterface.h.
~ccPclPluginInterface()
virtual ccPclPluginInterface::~ccPclPluginInterface () virtual default
Destructor.
Member Function Documentation
dispToConsole()
virtual void ccPclPluginInterface::dispToConsole (QString message, ecvMainAppInterface::ConsoleMessageLevel level = ecvMainAppInterface::STD_CONSOLE_MESSAGE) inline virtual
Shortcut to ecvMainAppInterface::dispToConsole.
Definition at line 74 of file ecvPclPluginInterface.h.
References ecvMainAppInterface::dispToConsole(), and m_app.
getActions()
virtual QVector<QList<QAction*> > ccPclPluginInterface::getActions () pure virtual
Get a list of actions for this plugin.
Implemented in qPCL.
getMainAppInterface()
virtual ecvMainAppInterface* ccPclPluginInterface::getMainAppInterface () inline virtual
A callback pointer to the main app interface for use by plugins.
Any plugin (and its tools) may need to access methods of this interface
Definition at line 57 of file ecvPclPluginInterface.h.
References m_app.
getModuleNames()
virtual QVector<QString> ccPclPluginInterface::getModuleNames () pure virtual
Implemented in qPCL.
getType()
virtual CC_PLUGIN_TYPE ccPclPluginInterface::getType () const inline override virtual
Returns plugin type (standard or OpenGL filter)
Implements ccPluginInterface.
Definition at line 37 of file ecvPclPluginInterface.h.
References ECV_PCL_ALGORITHM_PLUGIN.
onNewSelection()
virtual void ccPclPluginInterface::onNewSelection (const ccHObject::Container & selectedEntities) inline virtual
This method is called by the main application whenever the entity selection changes Does nothing by default. Should be re-implemented by the plugin if necessary.
Parameters
selectedEntities currently selected entities
Reimplemented in qPCL.
Definition at line 69 of file ecvPclPluginInterface.h.
Referenced by ccPluginUIManager::handleSelectionChanged().
setMainAppInterface()
virtual void ccPclPluginInterface::setMainAppInterface (ecvMainAppInterface * app) inline virtual
Sets application entry point.
Called just after plugin creation by qCC
Definition at line 44 of file ecvPclPluginInterface.h.
References ecvMainAppInterface::getUniqueIDGenerator(), m_app, and ccObject::SetUniqueIDGenerator().
Referenced by ccPluginUIManager::init().
Member Data Documentation
m_app
ecvMainAppInterface* ccPclPluginInterface::m_app protected
Main application interface.
Definition at line 85 of file ecvPclPluginInterface.h.
Referenced by qPCL::addPclModule(), dispToConsole(), getMainAppInterface(), qPCL::handleEntityChange(), qPCL::handleErrorMessage(), qPCL::handleNewEntity(), and setMainAppInterface().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CVPluginStub/include/ecvPclPluginInterface.h