ACloudViewer: ecvFilterTool Class Reference
ecvFilterTool Class Reference
Dialog for managing a clipping box.
#include <ecvFilterTool.h>
Public Member Functions
ecvFilterTool (QWidget *parent)
Default constructor.
virtual ~ecvFilterTool ()
Default destructor.
virtual bool linkWith (QWidget *win) override
Links the overlay dialog with a MDI window.
virtual bool start () override
Starts process.
virtual void stop (bool state) override
Stops process/dialog.
void setFilter (ecvGenericFiltersTool *filter)
ecvGenericFiltersTool * getFilter () const
bool addAssociatedEntity (ccHObject *anObject)
Adds an entity.
unsigned getNumberOfAssociatedEntity () const
Returns the current number of associated entities.
ccHObject::Container getOutputs () const
Public Member Functions inherited from ccOverlayDialog
ccOverlayDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::FramelessWindowHint|Qt::Tool)
Default constructor.
~ccOverlayDialog () override
Destructor.
void reject () override
void addOverridenShortcut (Qt::Key key)
bool started () const
Returns whether the tool is currently started or not.
Protected Slots
void toggleInteractors (bool)
void toggleBox (bool)
void reset ()
void restoreOrigin ()
void closeDialog ()
void exportSlice ()
void shiftXMinus ()
void shiftXPlus ()
void shiftYMinus ()
void shiftYPlus ()
void shiftZMinus ()
void shiftZPlus ()
void setTopView ()
void setBottomView ()
void setFrontView ()
void setBackView ()
void setLeftView ()
void setRightView ()
ccBBox getSelectedEntityBbox ()
Protected Slots inherited from ccOverlayDialog
virtual void onLinkedWindowDeletion (QObject *object=nullptr)
Slot called when the linked window is deleted (calls 'onClose')
Protected Member Functions
void releaseAssociatedEntities ()
Releases all associated entities.
ccHObject * getSlice (bool silent)
void shiftBox (unsigned char dim, bool minus)
Shift box.
void setView (CC_VIEW_ORIENTATION orientation)
Sets predefined view.
Protected Member Functions inherited from ccOverlayDialog
bool eventFilter (QObject *obj, QEvent *e) override
Protected Attributes
ecvGenericFiltersTool * m_filter
filter tool
ecvGenericFiltersTool::FilterType m_filterType
ccHObject m_entityContainer
Associated entities container.
ccHObject::Container m_out_entities
Protected Attributes inherited from ccOverlayDialog
QWidget * m_associatedWin
Associated (MDI) window.
bool m_processing
Running/processing state.
QList< int > m_overriddenKeys
Overridden keys.
Additional Inherited Members
Signals inherited from ccOverlayDialog
void processFinished (bool accepted)
Signal emitted when process is finished.
void shortcutTriggered (int key)
Signal emitted when an overridden key shortcut is pressed.
void shown ()
Signal emitted when a 'show' event is detected.
Detailed Description
Dialog for managing a clipping box.
Definition at line 29 of file ecvFilterTool.h.
Constructor & Destructor Documentation
ecvFilterTool()
ecvFilterTool::ecvFilterTool (QWidget * parent) explicit
Default constructor.
Definition at line 38 of file ecvFilterTool.cpp.
References closeDialog(), exportSlice(), reset(), restoreOrigin(), s_maxEdgeLength, setBackView(), setBottomView(), setFrontView(), setLeftView(), setRightView(), setTopView(), shiftXMinus(), shiftXPlus(), shiftYMinus(), shiftYPlus(), shiftZMinus(), shiftZPlus(), toggleBox(), and toggleInteractors().
~ecvFilterTool()
ecvFilterTool::~ecvFilterTool () virtual
Default destructor.
Definition at line 85 of file ecvFilterTool.cpp.
Member Function Documentation
addAssociatedEntity()
bool ecvFilterTool::addAssociatedEntity (ccHObject * anObject)
Adds an entity.
Returns
success, if the entity is eligible for clipping
Definition at line 95 of file ecvFilterTool.cpp.
References ccHObject::addChild(), ccHObject::DP_NONE, CVLog::Error(), ccHObject::getChild(), ccHObject::getChildrenNumber(), ccHObject::isGroup(), m_entityContainer, m_filter, ccObject::setEnabled(), and ccDrawableObject::setVisible().
closeDialog
void ecvFilterTool::closeDialog () protected slot
Definition at line 260 of file ecvFilterTool.cpp.
References stop().
Referenced by ecvFilterTool().
exportSlice
void ecvFilterTool::exportSlice () protected slot
Definition at line 198 of file ecvFilterTool.cpp.
References ccHObject::addChild(), MainWindow::addToDB(), ccHObject::getChild(), ccObject::getName(), getNumberOfAssociatedEntity(), ccHObject::getParent(), getSlice(), ecvGenericFiltersTool::GLYPH_FILTER, m_entityContainer, m_filter, m_filterType, m_out_entities, ecvGenericFiltersTool::PROBE_FILTER, reset(), result, MainWindow::TheInstance(), and CVLog::Warning().
Referenced by ecvFilterTool().
getFilter()
ecvGenericFiltersTool* ecvFilterTool::getFilter () const inline
Definition at line 44 of file ecvFilterTool.h.
References m_filter.
getNumberOfAssociatedEntity()
unsigned ecvFilterTool::getNumberOfAssociatedEntity () const
Returns the current number of associated entities.
Definition at line 130 of file ecvFilterTool.cpp.
References ccHObject::getChildrenNumber(), and m_entityContainer.
Referenced by exportSlice(), getSelectedEntityBbox(), and stop().
getOutputs()
ccHObject::Container ecvFilterTool::getOutputs () const inline
Definition at line 54 of file ecvFilterTool.h.
References m_out_entities.
getSelectedEntityBbox
ccBBox ecvFilterTool::getSelectedEntityBbox () protected slot
Definition at line 262 of file ecvFilterTool.cpp.
References ccHObject::getDisplayBB_recursive(), getNumberOfAssociatedEntity(), and m_entityContainer.
getSlice()
ccHObject * ecvFilterTool::getSlice (bool silent) protected
Definition at line 187 of file ecvFilterTool.cpp.
References CVLog::Error(), ecvGenericFiltersTool::getOutput(), and m_filter.
Referenced by exportSlice().
linkWith()
bool ecvFilterTool::linkWith (QWidget * win) override virtual
Links the overlay dialog with a MDI window.
Warning: link can't be modified while dialog is displayed/process is running!
Returns
success
Reimplemented from ccOverlayDialog.
Definition at line 134 of file ecvFilterTool.cpp.
References ccOverlayDialog::linkWith().
releaseAssociatedEntities()
void ecvFilterTool::releaseAssociatedEntities () protected
Releases all associated entities.
Warning: resets the current clipping box
Definition at line 233 of file ecvFilterTool.cpp.
References m_entityContainer, and ccHObject::removeAllChildren().
Referenced by stop().
reset
void ecvFilterTool::reset () protected slot
Definition at line 250 of file ecvFilterTool.cpp.
References m_filter, and ecvGenericFiltersTool::reset().
Referenced by ecvFilterTool(), and exportSlice().
restoreOrigin
void ecvFilterTool::restoreOrigin () protected slot
Definition at line 254 of file ecvFilterTool.cpp.
References m_filter, and ecvGenericFiltersTool::restore().
Referenced by ecvFilterTool().
setBackView
void ecvFilterTool::setBackView () inline protected slot
Definition at line 76 of file ecvFilterTool.h.
References CC_BACK_VIEW, and setView().
Referenced by ecvFilterTool().
setBottomView
void ecvFilterTool::setBottomView () inline protected slot
Definition at line 74 of file ecvFilterTool.h.
References CC_BOTTOM_VIEW, and setView().
Referenced by ecvFilterTool().
setFilter()
void ecvFilterTool::setFilter (ecvGenericFiltersTool * filter)
Definition at line 180 of file ecvFilterTool.cpp.
References ecvGenericFiltersTool::getFilterType(), ecvGenericFiltersTool::getFilterWidget(), m_filter, and m_filterType.
setFrontView
void ecvFilterTool::setFrontView () inline protected slot
Definition at line 75 of file ecvFilterTool.h.
References CC_FRONT_VIEW, and setView().
Referenced by ecvFilterTool().
setLeftView
void ecvFilterTool::setLeftView () inline protected slot
Definition at line 77 of file ecvFilterTool.h.
References CC_LEFT_VIEW, and setView().
Referenced by ecvFilterTool().
setRightView
void ecvFilterTool::setRightView () inline protected slot
Definition at line 78 of file ecvFilterTool.h.
References CC_RIGHT_VIEW, and setView().
Referenced by ecvFilterTool().
setTopView
void ecvFilterTool::setTopView () inline protected slot
Definition at line 73 of file ecvFilterTool.h.
References CC_TOP_VIEW, and setView().
Referenced by ecvFilterTool().
setView()
void ecvFilterTool::setView (CC_VIEW_ORIENTATION orientation) protected
Sets predefined view.
Definition at line 270 of file ecvFilterTool.cpp.
References ecvDisplayTools::SetView().
Referenced by setBackView(), setBottomView(), setFrontView(), setLeftView(), setRightView(), and setTopView().
shiftBox()
void ecvFilterTool::shiftBox (unsigned char dim, bool minus) protected
Shift box.
Definition at line 237 of file ecvFilterTool.cpp.
References ecvGenericFiltersTool::getBox(), cloudViewer::BoundingBoxTpl< T >::isValid(), m_filter, cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), ecvGenericFiltersTool::shift(), Tuple3Tpl< Type >::u, and width.
Referenced by shiftXMinus(), shiftXPlus(), shiftYMinus(), shiftYPlus(), shiftZMinus(), and shiftZPlus().
shiftXMinus
void ecvFilterTool::shiftXMinus () inline protected slot
Definition at line 66 of file ecvFilterTool.h.
References shiftBox().
Referenced by ecvFilterTool().
shiftXPlus
void ecvFilterTool::shiftXPlus () inline protected slot
Definition at line 67 of file ecvFilterTool.h.
References shiftBox().
Referenced by ecvFilterTool().
shiftYMinus
void ecvFilterTool::shiftYMinus () inline protected slot
Definition at line 68 of file ecvFilterTool.h.
References shiftBox().
Referenced by ecvFilterTool().
shiftYPlus
void ecvFilterTool::shiftYPlus () inline protected slot
Definition at line 69 of file ecvFilterTool.h.
References shiftBox().
Referenced by ecvFilterTool().
shiftZMinus
void ecvFilterTool::shiftZMinus () inline protected slot
Definition at line 70 of file ecvFilterTool.h.
References shiftBox().
Referenced by ecvFilterTool().
shiftZPlus
void ecvFilterTool::shiftZPlus () inline protected slot
Definition at line 71 of file ecvFilterTool.h.
References shiftBox().
Referenced by ecvFilterTool().
start()
bool ecvFilterTool::start () override virtual
Starts process.
Returns
success
Reimplemented from ccOverlayDialog.
Definition at line 142 of file ecvFilterTool.cpp.
References ccHObject::getFirstChild(), m_entityContainer, m_filter, m_out_entities, ccOverlayDialog::m_processing, ecvGenericFiltersTool::setInputData(), ecvGenericFiltersTool::showOutline(), ccOverlayDialog::start(), and ecvGenericFiltersTool::start().
stop()
void ecvFilterTool::stop (bool accepted) override virtual
Stops process/dialog.
Automatically emits the 'processFinished' signal (with input state as argument).
Parameters
accepted process/dialog result
Reimplemented from ccOverlayDialog.
Definition at line 154 of file ecvFilterTool.cpp.
References ccClipBoxParams::box, ecvGenericFiltersTool::get(), ccHObject::getChild(), ecvGenericFiltersTool::getFilterWidget(), getNumberOfAssociatedEntity(), ccObject::getUniqueID(), m_entityContainer, m_filter, releaseAssociatedEntities(), s_lastBoxParams, ccOverlayDialog::stop(), ccClipBoxParams::trans, and ecvGenericFiltersTool::unregisterFilter().
Referenced by closeDialog().
toggleBox
void ecvFilterTool::toggleBox (bool state) protected slot
Definition at line 91 of file ecvFilterTool.cpp.
References m_filter, and ecvGenericFiltersTool::showOutline().
Referenced by ecvFilterTool().
toggleInteractors
void ecvFilterTool::toggleInteractors (bool state) protected slot
Definition at line 87 of file ecvFilterTool.cpp.
References m_filter, and ecvGenericFiltersTool::showInteractor().
Referenced by ecvFilterTool().
Member Data Documentation
m_entityContainer
ccHObject ecvFilterTool::m_entityContainer protected
Associated entities container.
Definition at line 102 of file ecvFilterTool.h.
Referenced by addAssociatedEntity(), exportSlice(), getNumberOfAssociatedEntity(), getSelectedEntityBbox(), releaseAssociatedEntities(), start(), and stop().
m_filter
ecvGenericFiltersTool* ecvFilterTool::m_filter protected
filter tool
Definition at line 97 of file ecvFilterTool.h.
Referenced by addAssociatedEntity(), exportSlice(), getFilter(), getSlice(), reset(), restoreOrigin(), setFilter(), shiftBox(), start(), stop(), toggleBox(), and toggleInteractors().
m_filterType
ecvGenericFiltersTool::FilterType ecvFilterTool::m_filterType protected
Definition at line 99 of file ecvFilterTool.h.
Referenced by exportSlice(), and setFilter().
m_out_entities
ccHObject::Container ecvFilterTool::m_out_entities protected
Definition at line 104 of file ecvFilterTool.h.
Referenced by exportSlice(), getOutputs(), and start().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvFilterTool.h
/root/ACloudViewer/app/ecvFilterTool.cpp