ACloudViewer: pqCustomViewpointButtonDialogUI Class Reference
pqCustomViewpointButtonDialogUI Class Reference
Public Member Functions
pqCustomViewpointButtonDialogUI (::ecvCustomViewpointButtonDlg *parent)
~pqCustomViewpointButtonDialogUI ()
void setNumberOfRows (int rows)
int rowCount () const
void setToolTips (const QStringList &txts)
QStringList toolTips () const
void setToolTip (int index, const QString &txt)
QString toolTip (int index) const
void deleteRow (int index)
Detailed Description
Definition at line 38 of file ecvCustomViewpointButtonDlg.cpp.
Constructor & Destructor Documentation
pqCustomViewpointButtonDialogUI()
pqCustomViewpointButtonDialogUI::pqCustomViewpointButtonDialogUI (::ecvCustomViewpointButtonDlg * parent) inline
Definition at line 50 of file ecvCustomViewpointButtonDlg.cpp.
~pqCustomViewpointButtonDialogUI()
pqCustomViewpointButtonDialogUI::~pqCustomViewpointButtonDialogUI () inline
Definition at line 52 of file ecvCustomViewpointButtonDlg.cpp.
References setNumberOfRows().
Member Function Documentation
deleteRow()
void pqCustomViewpointButtonDialogUI::deleteRow (int index) inline
Definition at line 145 of file ecvCustomViewpointButtonDlg.cpp.
References ecvCustomViewpointButtonDlg::MAXIMUM_NUMBER_OF_ITEMS.
Referenced by setNumberOfRows().
rowCount()
int pqCustomViewpointButtonDialogUI::rowCount () const inline
Definition at line 116 of file ecvCustomViewpointButtonDlg.cpp.
setNumberOfRows()
void pqCustomViewpointButtonDialogUI::setNumberOfRows (int rows) inline
Definition at line 54 of file ecvCustomViewpointButtonDlg.cpp.
References ecvCustomViewpointButtonDlg::DEFAULT_TOOLTIP, deleteRow(), ecvCustomViewpointButtonDlg::MAXIMUM_NUMBER_OF_ITEMS, and ecvCustomViewpointButtonDlg::MINIMUM_NUMBER_OF_ITEMS.
Referenced by ecvCustomViewpointButtonDlg::setToolTipsAndConfigurations(), and ~pqCustomViewpointButtonDialogUI().
setToolTip()
void pqCustomViewpointButtonDialogUI::setToolTip (int index, const QString & txt) inline
Definition at line 133 of file ecvCustomViewpointButtonDlg.cpp.
setToolTips()
void pqCustomViewpointButtonDialogUI::setToolTips (const QStringList & txts) inline
Definition at line 118 of file ecvCustomViewpointButtonDlg.cpp.
Referenced by ecvCustomViewpointButtonDlg::setToolTips(), and ecvCustomViewpointButtonDlg::setToolTipsAndConfigurations().
toolTip()
QString pqCustomViewpointButtonDialogUI::toolTip (int index) const inline
Definition at line 140 of file ecvCustomViewpointButtonDlg.cpp.
toolTips()
QStringList pqCustomViewpointButtonDialogUI::toolTips () const inline
Definition at line 125 of file ecvCustomViewpointButtonDlg.cpp.
Referenced by ecvCustomViewpointButtonDlg::getToolTips().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CVAppCommon/src/ecvCustomViewpointButtonDlg.cpp