ACloudViewer: VtkUtils::Contour Class Reference
VtkUtils::Contour Class Reference
#include <contour.h>
Public Member Functions
Contour (QWidget *parent=nullptr)
~Contour ()
void setVectors (const QList< Vector4F > &vectors)
void setNumberOfContours (int num)
int numberOfContours () const
void setPlaneVisible (bool visible=true)
bool planeVisible () const
void setPlaneDistance (qreal distance)
bool planeDistance () const
Public Member Functions inherited from VtkUtils::Surface
Surface (QWidget *parent=nullptr)
virtual ~Surface ()
void setPoints (const QList< Point3F > &points)
Public Member Functions inherited from VtkUtils::VtkWidget
VtkWidget (QWidget *parent=nullptr)
virtual ~VtkWidget ()
void setMultiViewports (bool multi=true)
bool multiViewports () const
void createActorFromVTKDataSet (const vtkSmartPointer< vtkDataSet > &data, vtkSmartPointer< vtkLODActor > &actor, bool use_scalars=true)
void addActor (vtkProp *actor, const QColor &clr=Qt::black)
void addViewProp (vtkProp *prop)
QList< vtkProp * > actors () const
void setActorsVisible (bool visible)
void setActorVisible (vtkProp *actor, bool visible)
bool actorVisible (vtkProp *actor)
void setBackgroundColor (const QColor &clr)
void setBackgroundColor ()
QColor backgroundColor () const
vtkRenderer * defaultRenderer ()
bool defaultRendererTaken () const
void showOrientationMarker (bool show=true)
vtkRenderWindow * GetRenderWindow ()
QVTKInteractor * GetInteractor ()
Protected Member Functions
void renderSurface ()
Protected Member Functions inherited from VtkUtils::Surface
vtkActor * surfaceActor () const
Protected Member Functions inherited from VtkUtils::VtkWidget
void setBounds (double *bounds)
double xMin () const
double xMax () const
double yMin () const
double yMax () const
double zMin () const
double zMax () const
Detailed Description
Definition at line 15 of file contour.h.
Constructor & Destructor Documentation
Contour()
VtkUtils::Contour::Contour (QWidget * parent = nullptr) explicit
Definition at line 32 of file contour.cpp.
~Contour()
VtkUtils::Contour::~Contour ()
Definition at line 36 of file contour.cpp.
Member Function Documentation
numberOfContours()
int VtkUtils::Contour::numberOfContours () const
Definition at line 55 of file contour.cpp.
planeDistance()
bool VtkUtils::Contour::planeDistance () const
Definition at line 63 of file contour.cpp.
planeVisible()
bool VtkUtils::Contour::planeVisible () const
Definition at line 59 of file contour.cpp.
renderSurface()
void VtkUtils::Contour::renderSurface () protected virtual
Reimplemented from VtkUtils::Surface.
Definition at line 65 of file contour.cpp.
References VtkUtils::VtkWidget::defaultRenderer(), VtkUtils::VtkWidget::setBounds(), VtkUtils::Surface::surfaceActor(), VTK_CREATE, VtkUtils::Vector4F::x, VtkUtils::Vector4F::y, and VtkUtils::Vector4F::z.
Referenced by setVectors().
setNumberOfContours()
void VtkUtils::Contour::setNumberOfContours (int num)
Definition at line 45 of file contour.cpp.
References VtkUtils::VtkWidget::zMax(), and VtkUtils::VtkWidget::zMin().
setPlaneDistance()
void VtkUtils::Contour::setPlaneDistance (qreal distance)
Definition at line 61 of file contour.cpp.
setPlaneVisible()
void VtkUtils::Contour::setPlaneVisible (bool visible = true)
Definition at line 57 of file contour.cpp.
setVectors()
void VtkUtils::Contour::setVectors (const QList< Vector4F > & vectors)
Definition at line 38 of file contour.cpp.
References renderSurface().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/contour.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/contour.cpp