ACloudViewer: colmap::OptionManager Class Reference
colmap::OptionManager Class Reference
#include <option_manager.h>
Public Member Functions
OptionManager (bool add_project_options=true)
void ModifyForIndividualData ()
void ModifyForVideoData ()
void ModifyForInternetData ()
void ModifyForLowQuality ()
void ModifyForMediumQuality ()
void ModifyForHighQuality ()
void ModifyForExtremeQuality ()
void AddAllOptions ()
void AddLogOptions ()
void AddRandomOptions ()
void AddDatabaseOptions ()
void AddImageOptions ()
void AddExtractionOptions ()
void AddMatchingOptions ()
void AddExhaustiveMatchingOptions ()
void AddSequentialMatchingOptions ()
void AddVocabTreeMatchingOptions ()
void AddSpatialMatchingOptions ()
void AddTransitiveMatchingOptions ()
void AddImagePairsMatchingOptions ()
void AddBundleAdjustmentOptions ()
void AddMapperOptions ()
void AddPatchMatchStereoOptions ()
void AddStereoFusionOptions ()
void AddPoissonMeshingOptions ()
void AddDelaunayMeshingOptions ()
void AddTexturingOptions ()
void AddRenderOptions ()
template<typename T >
void AddRequiredOption (const std::string &name, T *option, const std::string &help_text="")
template<typename T >
void AddDefaultOption (const std::string &name, T *option, const std::string &help_text="")
void Reset ()
void ResetOptions (const bool reset_paths)
bool Check ()
void Parse (const int argc, char **argv)
bool Read (const std::string &path)
bool ReRead (const std::string &path)
void Write (const std::string &path) const
Public Attributes
std::shared_ptr< std::string > project_path
std::shared_ptr< std::string > database_path
std::shared_ptr< std::string > image_path
std::shared_ptr< ImageReaderOptions > image_reader
std::shared_ptr< SiftExtractionOptions > sift_extraction
std::shared_ptr< SiftMatchingOptions > sift_matching
std::shared_ptr< ExhaustiveMatchingOptions > exhaustive_matching
std::shared_ptr< SequentialMatchingOptions > sequential_matching
std::shared_ptr< VocabTreeMatchingOptions > vocab_tree_matching
std::shared_ptr< SpatialMatchingOptions > spatial_matching
std::shared_ptr< TransitiveMatchingOptions > transitive_matching
std::shared_ptr< ImagePairsMatchingOptions > image_pairs_matching
std::shared_ptr< BundleAdjustmentOptions > bundle_adjustment
std::shared_ptr< IncrementalMapperOptions > mapper
std::shared_ptr< mvs::PatchMatchOptions > patch_match_stereo
std::shared_ptr< mvs::StereoFusionOptions > stereo_fusion
std::shared_ptr< mvs::PoissonMeshingOptions > poisson_meshing
std::shared_ptr< mvs::DelaunayMeshingOptions > delaunay_meshing
std::shared_ptr< TexturingOptions > texturing
std::shared_ptr< RenderOptions > render
Detailed Description
Definition at line 38 of file option_manager.h.
Constructor & Destructor Documentation
OptionManager()
colmap::OptionManager::OptionManager (bool add_project_options = true)
Definition at line 56 of file option_manager.cc.
References AddLogOptions(), AddRandomOptions(), bundle_adjustment, database_path, delaunay_meshing, exhaustive_matching, image_pairs_matching, image_path, image_reader, mapper, patch_match_stereo, poisson_meshing, project_path, render, Reset(), sequential_matching, sift_extraction, sift_matching, spatial_matching, stereo_fusion, texturing, transitive_matching, and vocab_tree_matching.
Member Function Documentation
AddAllOptions()
void colmap::OptionManager::AddAllOptions ()
Definition at line 178 of file option_manager.cc.
References AddBundleAdjustmentOptions(), AddDatabaseOptions(), AddDelaunayMeshingOptions(), AddExhaustiveMatchingOptions(), AddExtractionOptions(), AddImageOptions(), AddImagePairsMatchingOptions(), AddLogOptions(), AddMapperOptions(), AddMatchingOptions(), AddPatchMatchStereoOptions(), AddPoissonMeshingOptions(), AddRandomOptions(), AddRenderOptions(), AddSequentialMatchingOptions(), AddSpatialMatchingOptions(), AddStereoFusionOptions(), AddTransitiveMatchingOptions(), and AddVocabTreeMatchingOptions().
Referenced by cloudViewer::ReconstructionWidget::ReconstructionWidget(), ReRead(), colmap::RunGraphicalUserInterface(), and colmap::RunProjectGenerator().
AddBundleAdjustmentOptions()
void colmap::OptionManager::AddBundleAdjustmentOptions ()
Definition at line 450 of file option_manager.cc.
References bundle_adjustment.
Referenced by AddAllOptions(), colmap::RunBundleAdjuster(), and colmap::RunRigBundleAdjuster().
AddDatabaseOptions()
void colmap::OptionManager::AddDatabaseOptions ()
Definition at line 219 of file option_manager.cc.
References database_path.
Referenced by AddAllOptions(), colmap::RunDatabaseCleaner(), colmap::RunDatabaseCreator(), colmap::RunExhaustiveMatcher(), colmap::RunFeatureExtractor(), colmap::RunFeatureImporter(), colmap::RunImageRegistrator(), colmap::RunMapper(), colmap::RunMatchesImporter(), colmap::RunPointTriangulator(), colmap::RunSequentialMatcher(), colmap::RunSpatialMatcher(), colmap::RunTransitiveMatcher(), colmap::RunVocabTreeBuilder(), colmap::RunVocabTreeMatcher(), and colmap::RunVocabTreeRetriever().
AddDefaultOption()
template<typename T > void colmap::OptionManager::AddDefaultOption (const std::string & name, T * option, const std::string & help_text = "")
Definition at line 180 of file option_manager.h.
References name.
Referenced by colmap::RunAutomaticReconstructor(), colmap::RunColorExtractor(), colmap::RunDelaunayMesher(), colmap::RunFeatureExtractor(), colmap::RunFeatureImporter(), colmap::RunGraphicalUserInterface(), colmap::RunHierarchicalMapper(), colmap::RunImageDeleter(), colmap::RunImageFilterer(), colmap::RunImageRectifier(), colmap::RunImageUndistorter(), colmap::RunImageUndistorterStandalone(), colmap::RunMapper(), colmap::RunMatchesImporter(), colmap::RunModelAligner(), colmap::RunModelComparer(), colmap::RunModelConverter(), colmap::RunModelCropper(), colmap::RunModelMerger(), colmap::RunModelOrientationAligner(), colmap::RunModelSplitter(), colmap::RunModelTransformer(), colmap::RunPatchMatchStereo(), colmap::RunPointFiltering(), colmap::RunPointTriangulator(), colmap::RunProjectGenerator(), colmap::RunRigBundleAdjuster(), colmap::RunStereoFuser(), colmap::RunVocabTreeBuilder(), and colmap::RunVocabTreeRetriever().
AddDelaunayMeshingOptions()
void colmap::OptionManager::AddDelaunayMeshingOptions ()
Definition at line 746 of file option_manager.cc.
References delaunay_meshing.
Referenced by AddAllOptions(), and colmap::RunDelaunayMesher().
AddExhaustiveMatchingOptions()
void colmap::OptionManager::AddExhaustiveMatchingOptions ()
Definition at line 334 of file option_manager.cc.
References AddMatchingOptions(), and exhaustive_matching.
Referenced by AddAllOptions(), and colmap::RunExhaustiveMatcher().
AddExtractionOptions()
void colmap::OptionManager::AddExtractionOptions ()
Definition at line 237 of file option_manager.cc.
References image_reader, and sift_extraction.
Referenced by AddAllOptions(), colmap::RunFeatureExtractor(), and colmap::RunFeatureImporter().
AddImageOptions()
void colmap::OptionManager::AddImageOptions ()
Definition at line 228 of file option_manager.cc.
References image_path.
Referenced by AddAllOptions(), colmap::RunColorExtractor(), colmap::RunFeatureExtractor(), colmap::RunFeatureImporter(), colmap::RunImageRectifier(), colmap::RunImageUndistorter(), colmap::RunImageUndistorterStandalone(), colmap::RunMapper(), colmap::RunModelOrientationAligner(), and colmap::RunPointTriangulator().
AddImagePairsMatchingOptions()
void colmap::OptionManager::AddImagePairsMatchingOptions ()
Definition at line 438 of file option_manager.cc.
References AddMatchingOptions(), and image_pairs_matching.
Referenced by AddAllOptions().
AddLogOptions()
void colmap::OptionManager::AddLogOptions ()
Definition at line 200 of file option_manager.cc.
Referenced by AddAllOptions(), and OptionManager().
AddMapperOptions()
void colmap::OptionManager::AddMapperOptions ()
Definition at line 502 of file option_manager.cc.
References mapper.
Referenced by AddAllOptions(), colmap::RunHierarchicalMapper(), colmap::RunImageRegistrator(), colmap::RunMapper(), and colmap::RunPointTriangulator().
AddMatchingOptions()
void colmap::OptionManager::AddMatchingOptions ()
Definition at line 298 of file option_manager.cc.
References sift_matching.
Referenced by AddAllOptions(), AddExhaustiveMatchingOptions(), AddImagePairsMatchingOptions(), AddSequentialMatchingOptions(), AddSpatialMatchingOptions(), AddTransitiveMatchingOptions(), AddVocabTreeMatchingOptions(), and colmap::RunMatchesImporter().
AddPatchMatchStereoOptions()
void colmap::OptionManager::AddPatchMatchStereoOptions ()
Definition at line 638 of file option_manager.cc.
References patch_match_stereo.
Referenced by AddAllOptions(), and colmap::RunPatchMatchStereo().
AddPoissonMeshingOptions()
void colmap::OptionManager::AddPoissonMeshingOptions ()
Definition at line 729 of file option_manager.cc.
References poisson_meshing.
Referenced by AddAllOptions(), and colmap::RunPoissonMesher().
AddRandomOptions()
void colmap::OptionManager::AddRandomOptions ()
Definition at line 210 of file option_manager.cc.
References colmap::kDefaultPRNGSeed.
Referenced by AddAllOptions(), and OptionManager().
AddRenderOptions()
void colmap::OptionManager::AddRenderOptions ()
Definition at line 770 of file option_manager.cc.
References render.
Referenced by AddAllOptions().
AddRequiredOption()
template<typename T > void colmap::OptionManager::AddRequiredOption (const std::string & name, T * option, const std::string & help_text = "")
Definition at line 171 of file option_manager.h.
References name.
Referenced by main(), colmap::RunAutomaticReconstructor(), colmap::RunBundleAdjuster(), colmap::RunColorExtractor(), colmap::RunDatabaseCleaner(), colmap::RunDatabaseMerger(), colmap::RunDelaunayMesher(), colmap::RunFeatureImporter(), colmap::RunHierarchicalMapper(), colmap::RunImageDeleter(), colmap::RunImageFilterer(), colmap::RunImageRectifier(), colmap::RunImageRegistrator(), colmap::RunImageTexturer(), colmap::RunImageUndistorter(), colmap::RunImageUndistorterStandalone(), colmap::RunMapper(), colmap::RunMatchesImporter(), colmap::RunModelAligner(), colmap::RunModelAnalyzer(), colmap::RunModelComparer(), colmap::RunModelConverter(), colmap::RunModelCropper(), colmap::RunModelMerger(), colmap::RunModelOrientationAligner(), colmap::RunModelSplitter(), colmap::RunModelTransformer(), colmap::RunPatchMatchStereo(), colmap::RunPointFiltering(), colmap::RunPointTriangulator(), colmap::RunPoissonMesher(), colmap::RunProjectGenerator(), colmap::RunRigBundleAdjuster(), colmap::RunStereoFuser(), colmap::RunVocabTreeBuilder(), and colmap::RunVocabTreeRetriever().
AddSequentialMatchingOptions()
void colmap::OptionManager::AddSequentialMatchingOptions ()
Definition at line 346 of file option_manager.cc.
References AddMatchingOptions(), and sequential_matching.
Referenced by AddAllOptions(), and colmap::RunSequentialMatcher().
AddSpatialMatchingOptions()
void colmap::OptionManager::AddSpatialMatchingOptions ()
Definition at line 406 of file option_manager.cc.
References AddMatchingOptions(), and spatial_matching.
Referenced by AddAllOptions(), and colmap::RunSpatialMatcher().
AddStereoFusionOptions()
void colmap::OptionManager::AddStereoFusionOptions ()
Definition at line 697 of file option_manager.cc.
References stereo_fusion.
Referenced by AddAllOptions(), and colmap::RunStereoFuser().
AddTexturingOptions()
void colmap::OptionManager::AddTexturingOptions ()
Definition at line 1025 of file option_manager.cc.
References texturing.
Referenced by colmap::RunImageTexturer().
AddTransitiveMatchingOptions()
void colmap::OptionManager::AddTransitiveMatchingOptions ()
Definition at line 424 of file option_manager.cc.
References AddMatchingOptions(), and transitive_matching.
Referenced by AddAllOptions(), and colmap::RunTransitiveMatcher().
AddVocabTreeMatchingOptions()
void colmap::OptionManager::AddVocabTreeMatchingOptions ()
Definition at line 381 of file option_manager.cc.
References AddMatchingOptions(), and vocab_tree_matching.
Referenced by AddAllOptions(), and colmap::RunVocabTreeMatcher().
Check()
bool colmap::OptionManager::Check ()
Definition at line 848 of file option_manager.cc.
References bundle_adjustment, CHECK_OPTION_IMPL, database_path, delaunay_meshing, exhaustive_matching, colmap::ExistsDir(), colmap::GetParentDir(), image_pairs_matching, image_path, image_reader, mapper, patch_match_stereo, poisson_meshing, render, sequential_matching, sift_extraction, sift_matching, spatial_matching, stereo_fusion, transitive_matching, and vocab_tree_matching.
Referenced by Parse(), and Read().
ModifyForExtremeQuality()
void colmap::OptionManager::ModifyForExtremeQuality ()
Definition at line 168 of file option_manager.cc.
References mapper, sift_extraction, and sift_matching.
Referenced by colmap::RunProjectGenerator().
ModifyForHighQuality()
void colmap::OptionManager::ModifyForHighQuality ()
Definition at line 155 of file option_manager.cc.
References mapper, patch_match_stereo, sift_extraction, sift_matching, stereo_fusion, and vocab_tree_matching.
Referenced by colmap::RunProjectGenerator().
ModifyForIndividualData()
void colmap::OptionManager::ModifyForIndividualData ()
Definition at line 91 of file option_manager.cc.
References mapper.
ModifyForInternetData()
void colmap::OptionManager::ModifyForInternetData ()
Definition at line 109 of file option_manager.cc.
References stereo_fusion.
ModifyForLowQuality()
void colmap::OptionManager::ModifyForLowQuality ()
Definition at line 113 of file option_manager.cc.
References mapper, patch_match_stereo, sequential_matching, sift_extraction, stereo_fusion, and vocab_tree_matching.
Referenced by colmap::RunProjectGenerator().
ModifyForMediumQuality()
void colmap::OptionManager::ModifyForMediumQuality ()
Definition at line 134 of file option_manager.cc.
References mapper, patch_match_stereo, sequential_matching, sift_extraction, stereo_fusion, and vocab_tree_matching.
Referenced by colmap::RunProjectGenerator().
ModifyForVideoData()
void colmap::OptionManager::ModifyForVideoData ()
Definition at line 97 of file option_manager.cc.
References mapper, ResetOptions(), and stereo_fusion.
Parse()
void colmap::OptionManager::Parse (const int argc, char ** argv)
Definition at line 888 of file option_manager.cc.
References Check(), QtCompat::endl(), colmap::GetBuildInfo(), colmap::GetVersionInfo(), project_path, Read(), and colmap::StringPrintf().
Referenced by main(), colmap::RunAutomaticReconstructor(), colmap::RunBundleAdjuster(), colmap::RunColorExtractor(), colmap::RunDatabaseCleaner(), colmap::RunDatabaseCreator(), colmap::RunDatabaseMerger(), colmap::RunDelaunayMesher(), colmap::RunExhaustiveMatcher(), colmap::RunFeatureExtractor(), colmap::RunFeatureImporter(), colmap::RunGraphicalUserInterface(), colmap::RunHierarchicalMapper(), colmap::RunImageDeleter(), colmap::RunImageFilterer(), colmap::RunImageRectifier(), colmap::RunImageRegistrator(), colmap::RunImageTexturer(), colmap::RunImageUndistorter(), colmap::RunImageUndistorterStandalone(), colmap::RunMapper(), colmap::RunMatchesImporter(), colmap::RunModelAligner(), colmap::RunModelAnalyzer(), colmap::RunModelComparer(), colmap::RunModelConverter(), colmap::RunModelCropper(), colmap::RunModelMerger(), colmap::RunModelOrientationAligner(), colmap::RunModelSplitter(), colmap::RunModelTransformer(), colmap::RunPatchMatchStereo(), colmap::RunPointFiltering(), colmap::RunPointTriangulator(), colmap::RunPoissonMesher(), colmap::RunProjectGenerator(), colmap::RunRigBundleAdjuster(), colmap::RunSequentialMatcher(), colmap::RunSpatialMatcher(), colmap::RunStereoFuser(), colmap::RunTransitiveMatcher(), colmap::RunVocabTreeBuilder(), colmap::RunVocabTreeMatcher(), and colmap::RunVocabTreeRetriever().
Read()
bool colmap::OptionManager::Read (const std::string & path)
Definition at line 934 of file option_manager.cc.
References Check(), e, QtCompat::endl(), colmap::ExistsFile(), and cloudViewer::t::geometry::path.
Referenced by Parse(), and ReRead().
ReRead()
bool colmap::OptionManager::ReRead (const std::string & path)
Definition at line 960 of file option_manager.cc.
References AddAllOptions(), cloudViewer::t::geometry::path, Read(), and Reset().
Referenced by cloudViewer::ReconstructionWidget::iniEnvironment().
Reset()
void colmap::OptionManager::Reset ()
Definition at line 787 of file option_manager.cc.
References ResetOptions().
Referenced by OptionManager(), and ReRead().
ResetOptions()
void colmap::OptionManager::ResetOptions (const bool reset_paths)
Definition at line 823 of file option_manager.cc.
References bundle_adjustment, database_path, delaunay_meshing, exhaustive_matching, image_pairs_matching, image_path, image_reader, mapper, patch_match_stereo, poisson_meshing, project_path, render, sequential_matching, sift_extraction, sift_matching, spatial_matching, stereo_fusion, texturing, transitive_matching, and vocab_tree_matching.
Referenced by ModifyForVideoData(), and Reset().
Write()
void colmap::OptionManager::Write (const std::string & path) const
Definition at line 966 of file option_manager.cc.
References cloudViewer::t::geometry::path, and colmap::StringContains().
Referenced by colmap::RunProjectGenerator(), and colmap::ReconstructionManager::Write().
Member Data Documentation
bundle_adjustment
std::shared_ptr<BundleAdjustmentOptions> colmap::OptionManager::bundle_adjustment
Definition at line 113 of file option_manager.h.
Referenced by AddBundleAdjustmentOptions(), Check(), OptionManager(), ResetOptions(), and colmap::RunRigBundleAdjuster().
database_path
std::shared_ptr<std::string> colmap::OptionManager::database_path
Definition at line 99 of file option_manager.h.
Referenced by AddDatabaseOptions(), Check(), cloudViewer::ReconstructionWidget::iniEnvironment(), OptionManager(), ResetOptions(), cloudViewer::SIFTExtractionWidget::Run(), cloudViewer::ImportFeaturesWidget::Run(), cloudViewer::ExhaustiveMatchingTab::Run(), cloudViewer::SequentialMatchingTab::Run(), cloudViewer::VocabTreeMatchingTab::Run(), cloudViewer::SpatialMatchingTab::Run(), cloudViewer::TransitiveMatchingTab::Run(), cloudViewer::CustomMatchingTab::Run(), colmap::SIFTExtractionWidget::Run(), colmap::ImportFeaturesWidget::Run(), colmap::ExhaustiveMatchingTab::Run(), colmap::SequentialMatchingTab::Run(), colmap::VocabTreeMatchingTab::Run(), colmap::SpatialMatchingTab::Run(), colmap::TransitiveMatchingTab::Run(), colmap::CustomMatchingTab::Run(), colmap::RunDatabaseCleaner(), colmap::RunDatabaseCreator(), colmap::RunExhaustiveMatcher(), colmap::RunFeatureExtractor(), colmap::RunFeatureImporter(), colmap::RunImageRegistrator(), colmap::RunMapper(), colmap::RunMatchesImporter(), colmap::RunPointTriangulator(), colmap::RunSequentialMatcher(), colmap::RunSpatialMatcher(), colmap::RunTransitiveMatcher(), colmap::RunVocabTreeBuilder(), colmap::RunVocabTreeMatcher(), colmap::RunVocabTreeRetriever(), cloudViewer::MatchMatrixWidget::Show(), and colmap::MatchMatrixWidget::Show().
delaunay_meshing
std::shared_ptr<mvs::DelaunayMeshingOptions> colmap::OptionManager::delaunay_meshing
Definition at line 119 of file option_manager.h.
Referenced by AddDelaunayMeshingOptions(), Check(), OptionManager(), ResetOptions(), colmap::RunDelaunayMesher(), and colmap::AutomaticReconstructionController::RunDenseMapper().
exhaustive_matching
std::shared_ptr<ExhaustiveMatchingOptions> colmap::OptionManager::exhaustive_matching
Definition at line 106 of file option_manager.h.
Referenced by AddExhaustiveMatchingOptions(), Check(), cloudViewer::ExhaustiveMatchingTab::ExhaustiveMatchingTab(), colmap::ExhaustiveMatchingTab::ExhaustiveMatchingTab(), OptionManager(), ResetOptions(), cloudViewer::ExhaustiveMatchingTab::Run(), colmap::ExhaustiveMatchingTab::Run(), and colmap::RunExhaustiveMatcher().
image_pairs_matching
std::shared_ptr<ImagePairsMatchingOptions> colmap::OptionManager::image_pairs_matching
Definition at line 111 of file option_manager.h.
Referenced by AddImagePairsMatchingOptions(), Check(), cloudViewer::CustomMatchingTab::CustomMatchingTab(), colmap::CustomMatchingTab::CustomMatchingTab(), OptionManager(), and ResetOptions().
image_path
std::shared_ptr<std::string> colmap::OptionManager::image_path
Definition at line 100 of file option_manager.h.
Referenced by AddImageOptions(), Check(), cloudViewer::ReconstructionWidget::iniEnvironment(), OptionManager(), ResetOptions(), cloudViewer::SIFTExtractionWidget::Run(), cloudViewer::ImportFeaturesWidget::Run(), colmap::SIFTExtractionWidget::Run(), colmap::ImportFeaturesWidget::Run(), colmap::RunColorExtractor(), colmap::AutomaticReconstructionController::RunDenseMapper(), colmap::RunFeatureExtractor(), colmap::RunFeatureImporter(), colmap::RunImageRectifier(), colmap::RunImageTexturer(), colmap::RunImageUndistorter(), colmap::RunImageUndistorterStandalone(), colmap::RunMapper(), colmap::RunModelOrientationAligner(), colmap::RunPointTriangulator(), cloudViewer::PointViewerWidget::Show(), colmap::PointViewerWidget::Show(), cloudViewer::DatabaseImageViewerWidget::ShowImageWithId(), colmap::DatabaseImageViewerWidget::ShowImageWithId(), cloudViewer::TwoViewInfoTab::ShowMatches(), and colmap::TwoViewInfoTab::ShowMatches().
image_reader
std::shared_ptr<ImageReaderOptions> colmap::OptionManager::image_reader
Definition at line 102 of file option_manager.h.
Referenced by AddExtractionOptions(), Check(), OptionManager(), ResetOptions(), cloudViewer::SIFTExtractionWidget::Run(), cloudViewer::ImportFeaturesWidget::Run(), colmap::SIFTExtractionWidget::Run(), colmap::ImportFeaturesWidget::Run(), colmap::RunFeatureExtractor(), colmap::RunFeatureImporter(), cloudViewer::SIFTExtractionWidget::SIFTExtractionWidget(), and colmap::SIFTExtractionWidget::SIFTExtractionWidget().
mapper
std::shared_ptr<IncrementalMapperOptions> colmap::OptionManager::mapper
Definition at line 114 of file option_manager.h.
Referenced by AddMapperOptions(), Check(), cloudViewer::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget(), colmap::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget(), cloudViewer::MapperFilteringOptionsWidget::MapperFilteringOptionsWidget(), colmap::MapperFilteringOptionsWidget::MapperFilteringOptionsWidget(), cloudViewer::MapperGeneralOptionsWidget::MapperGeneralOptionsWidget(), colmap::MapperGeneralOptionsWidget::MapperGeneralOptionsWidget(), cloudViewer::MapperInitializationOptionsWidget::MapperInitializationOptionsWidget(), colmap::MapperInitializationOptionsWidget::MapperInitializationOptionsWidget(), cloudViewer::MapperRegistrationOptionsWidget::MapperRegistrationOptionsWidget(), colmap::MapperRegistrationOptionsWidget::MapperRegistrationOptionsWidget(), cloudViewer::MapperTriangulationOptionsWidget::MapperTriangulationOptionsWidget(), colmap::MapperTriangulationOptionsWidget::MapperTriangulationOptionsWidget(), ModifyForExtremeQuality(), ModifyForHighQuality(), ModifyForIndividualData(), ModifyForLowQuality(), ModifyForMediumQuality(), ModifyForVideoData(), OptionManager(), ResetOptions(), colmap::RunHierarchicalMapper(), colmap::RunImageRegistrator(), colmap::RunMapper(), and colmap::RunPointTriangulator().
patch_match_stereo
std::shared_ptr<mvs::PatchMatchOptions> colmap::OptionManager::patch_match_stereo
Definition at line 116 of file option_manager.h.
Referenced by AddPatchMatchStereoOptions(), Check(), ModifyForHighQuality(), ModifyForLowQuality(), ModifyForMediumQuality(), OptionManager(), ResetOptions(), colmap::AutomaticReconstructionController::RunDenseMapper(), and colmap::RunPatchMatchStereo().
poisson_meshing
std::shared_ptr<mvs::PoissonMeshingOptions> colmap::OptionManager::poisson_meshing
Definition at line 118 of file option_manager.h.
Referenced by AddPoissonMeshingOptions(), Check(), OptionManager(), ResetOptions(), colmap::AutomaticReconstructionController::RunDenseMapper(), and colmap::RunPoissonMesher().
project_path
std::shared_ptr<std::string> colmap::OptionManager::project_path
Definition at line 98 of file option_manager.h.
Referenced by cloudViewer::ReconstructionWidget::close(), colmap::MainWindow::closeEvent(), cloudViewer::ReconstructionWidget::iniEnvironment(), OptionManager(), Parse(), and ResetOptions().
render
std::shared_ptr<RenderOptions> colmap::OptionManager::render
Definition at line 122 of file option_manager.h.
Referenced by AddRenderOptions(), Check(), cloudViewer::ModelViewerWidget::GetProjectionType(), colmap::ModelViewerWidget::GetProjectionType(), OptionManager(), cloudViewer::ReconstructionWidget::ReconstructionWidget(), ResetOptions(), and colmap::ModelViewerWidget::TranslateView().
sequential_matching
std::shared_ptr<SequentialMatchingOptions> colmap::OptionManager::sequential_matching
Definition at line 107 of file option_manager.h.
Referenced by AddSequentialMatchingOptions(), Check(), ModifyForLowQuality(), ModifyForMediumQuality(), OptionManager(), ResetOptions(), cloudViewer::SequentialMatchingTab::Run(), colmap::SequentialMatchingTab::Run(), colmap::RunSequentialMatcher(), cloudViewer::SequentialMatchingTab::SequentialMatchingTab(), and colmap::SequentialMatchingTab::SequentialMatchingTab().
sift_extraction
std::shared_ptr<SiftExtractionOptions> colmap::OptionManager::sift_extraction
Definition at line 103 of file option_manager.h.
Referenced by AddExtractionOptions(), Check(), ModifyForExtremeQuality(), ModifyForHighQuality(), ModifyForLowQuality(), ModifyForMediumQuality(), OptionManager(), ResetOptions(), cloudViewer::SIFTExtractionWidget::Run(), colmap::SIFTExtractionWidget::Run(), colmap::RunFeatureExtractor(), cloudViewer::SIFTExtractionWidget::SIFTExtractionWidget(), and colmap::SIFTExtractionWidget::SIFTExtractionWidget().
sift_matching
std::shared_ptr<SiftMatchingOptions> colmap::OptionManager::sift_matching
Definition at line 105 of file option_manager.h.
Referenced by AddMatchingOptions(), Check(), cloudViewer::FeatureMatchingTab::CreateGeneralOptions(), colmap::FeatureMatchingTab::CreateGeneralOptions(), ModifyForExtremeQuality(), ModifyForHighQuality(), OptionManager(), ResetOptions(), cloudViewer::ExhaustiveMatchingTab::Run(), cloudViewer::SequentialMatchingTab::Run(), cloudViewer::VocabTreeMatchingTab::Run(), cloudViewer::SpatialMatchingTab::Run(), cloudViewer::TransitiveMatchingTab::Run(), cloudViewer::CustomMatchingTab::Run(), colmap::ExhaustiveMatchingTab::Run(), colmap::SequentialMatchingTab::Run(), colmap::VocabTreeMatchingTab::Run(), colmap::SpatialMatchingTab::Run(), colmap::TransitiveMatchingTab::Run(), colmap::CustomMatchingTab::Run(), colmap::RunExhaustiveMatcher(), colmap::RunMatchesImporter(), colmap::RunSequentialMatcher(), colmap::RunSpatialMatcher(), colmap::RunTransitiveMatcher(), and colmap::RunVocabTreeMatcher().
spatial_matching
std::shared_ptr<SpatialMatchingOptions> colmap::OptionManager::spatial_matching
Definition at line 109 of file option_manager.h.
Referenced by AddSpatialMatchingOptions(), Check(), OptionManager(), ResetOptions(), cloudViewer::SpatialMatchingTab::Run(), colmap::SpatialMatchingTab::Run(), colmap::RunSpatialMatcher(), cloudViewer::SpatialMatchingTab::SpatialMatchingTab(), and colmap::SpatialMatchingTab::SpatialMatchingTab().
stereo_fusion
std::shared_ptr<mvs::StereoFusionOptions> colmap::OptionManager::stereo_fusion
Definition at line 117 of file option_manager.h.
Referenced by AddStereoFusionOptions(), Check(), ModifyForHighQuality(), ModifyForInternetData(), ModifyForLowQuality(), ModifyForMediumQuality(), ModifyForVideoData(), OptionManager(), ResetOptions(), colmap::AutomaticReconstructionController::RunDenseMapper(), and colmap::RunStereoFuser().
texturing
std::shared_ptr<TexturingOptions> colmap::OptionManager::texturing
Definition at line 120 of file option_manager.h.
Referenced by AddTexturingOptions(), OptionManager(), ResetOptions(), colmap::AutomaticReconstructionController::RunDenseMapper(), and colmap::RunImageTexturer().
transitive_matching
std::shared_ptr<TransitiveMatchingOptions> colmap::OptionManager::transitive_matching
Definition at line 110 of file option_manager.h.
Referenced by AddTransitiveMatchingOptions(), Check(), OptionManager(), ResetOptions(), cloudViewer::TransitiveMatchingTab::Run(), colmap::TransitiveMatchingTab::Run(), colmap::RunTransitiveMatcher(), cloudViewer::TransitiveMatchingTab::TransitiveMatchingTab(), and colmap::TransitiveMatchingTab::TransitiveMatchingTab().
vocab_tree_matching
std::shared_ptr<VocabTreeMatchingOptions> colmap::OptionManager::vocab_tree_matching
Definition at line 108 of file option_manager.h.
Referenced by AddVocabTreeMatchingOptions(), Check(), ModifyForHighQuality(), ModifyForLowQuality(), ModifyForMediumQuality(), OptionManager(), ResetOptions(), cloudViewer::VocabTreeMatchingTab::Run(), colmap::VocabTreeMatchingTab::Run(), colmap::RunVocabTreeMatcher(), cloudViewer::VocabTreeMatchingTab::VocabTreeMatchingTab(), and colmap::VocabTreeMatchingTab::VocabTreeMatchingTab().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/util/option_manager.h
/root/ACloudViewer/libs/Reconstruction/src/util/option_manager.cc