ACloudViewer: PdmsTools::PdmsCommands::Reference Class Reference
PdmsTools::PdmsCommands::Reference Class Reference
#include <PdmsTools.h>
Public Member Functions
Reference (Token t=PDMS_INVALID_TOKEN)
Reference (const Reference &ref)
Reference & operator= (const Reference &ref)
virtual bool handle (Token t)
virtual bool handle (const char *str)
virtual bool isValid () const
virtual bool isNameReference () const
virtual bool isTokenReference () const
virtual bool execute (PdmsObjects::GenericItem *&item) const
Public Member Functions inherited from PdmsTools::PdmsCommands::Command
Command (Token t)
Command (const Command &com)
virtual ~Command ()
virtual bool handle (PointCoordinateType numvalue)
Public Attributes
Token token
char refname [c_max_str_length]
Public Attributes inherited from PdmsTools::PdmsCommands::Command
Token command
Protected Member Functions
int isSet () const
Additional Inherited Members
Static Public Member Functions inherited from PdmsTools::PdmsCommands::Command
static Command * Create (Token t)
Factory.
Detailed Description
Definition at line 524 of file PdmsTools.h.
Constructor & Destructor Documentation
Reference() [1/2]
PdmsTools::PdmsCommands::Reference::Reference (Token t = PDMS_INVALID_TOKEN) inline explicit
Definition at line 529 of file PdmsTools.h.
References PdmsTools::c_max_str_length, and refname.
Reference() [2/2]
PdmsTools::PdmsCommands::Reference::Reference (const Reference & ref) inline
Definition at line 533 of file PdmsTools.h.
References refname.
Member Function Documentation
execute()
bool Reference::execute (PdmsObjects::GenericItem *& item) const virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 166 of file PdmsTools.cpp.
References defaultWorld, PdmsTools::PdmsCommands::ElementEnding::execute(), PdmsTools::PdmsObjects::GenericItem::getRoot(), PdmsTools::PdmsToken::isDesignElement(), PdmsTools::PdmsToken::isGroupElement(), PdmsTools::PdmsObjects::GenericItem::owner, PdmsTools::PDMS_LAST, PdmsTools::PDMS_OWNER, result, s_elementsStack, and PdmsTools::PdmsObjects::GenericItem::scan().
handle() [1/2]
bool Reference::handle (const char * str) virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 144 of file PdmsTools.cpp.
handle() [2/2]
bool Reference::handle (Token t) virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 135 of file PdmsTools.cpp.
References PdmsTools::PdmsToken::isElement().
Referenced by PdmsTools::PdmsCommands::ElementEnding::handle().
isNameReference()
bool Reference::isNameReference () const virtual
Definition at line 155 of file PdmsTools.cpp.
isSet()
int Reference::isSet () const protected
Definition at line 159 of file PdmsTools.cpp.
References PdmsTools::PDMS_INVALID_TOKEN.
isTokenReference()
bool Reference::isTokenReference () const virtual
Definition at line 157 of file PdmsTools.cpp.
References PdmsTools::PDMS_INVALID_TOKEN.
isValid()
bool Reference::isValid () const virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 151 of file PdmsTools.cpp.
References PdmsTools::PDMS_LAST.
Referenced by PdmsTools::PdmsCommands::ElementEnding::isValid().
operator=()
Reference & Reference::operator= (const Reference & ref)
Definition at line 127 of file PdmsTools.cpp.
References PdmsTools::PdmsCommands::Command::command, refname, and token.
Member Data Documentation
refname
char PdmsTools::PdmsCommands::Reference::refname[c_max_str_length]
Definition at line 527 of file PdmsTools.h.
Referenced by operator=(), and Reference().
token
Token PdmsTools::PdmsCommands::Reference::token
Definition at line 526 of file PdmsTools.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsTools.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsTools.cpp