ACloudViewer: colmap::OptionsWidget Class Reference
colmap::OptionsWidget Class Reference
#include <options_widget.h>
Public Member Functions
OptionsWidget (QWidget *parent)
void AddOptionRow (const std::string &label_text, QWidget *widget, void *option)
void AddWidgetRow (const std::string &label_text, QWidget *widget)
void AddLayoutRow (const std::string &label_text, QLayout *layout)
QSpinBox * AddOptionInt (int *option, const std::string &label_text, const int min=0, const int max=static_cast< int >(1e7))
QDoubleSpinBox * AddOptionDouble (double *option, const std::string &label_text, const double min=0, const double max=1e7, const double step=0.01, const int decimals=2)
QDoubleSpinBox * AddOptionDoubleLog (double *option, const std::string &label_text, const double min=0, const double max=1e7, const double step=0.01, const int decimals=2)
QCheckBox * AddOptionBool (bool *option, const std::string &label_text)
QLineEdit * AddOptionText (std::string *option, const std::string &label_text)
QLineEdit * AddOptionFilePath (std::string *option, const std::string &label_text)
QLineEdit * AddOptionDirPath (std::string *option, const std::string &label_text)
void AddSpacer ()
void AddSection (const std::string &title)
void ReadOptions ()
void WriteOptions ()
Protected Member Functions
void showEvent (QShowEvent *event)
void closeEvent (QCloseEvent *event)
void hideEvent (QHideEvent *event)
void ShowOption (void *option)
void HideOption (void *option)
void ShowWidget (QWidget *option)
void HideWidget (QWidget *option)
void ShowLayout (QLayout *option)
void HideLayout (QLayout *option)
Protected Attributes
QGridLayout * grid_layout_
std::unordered_map< void *, std::pair< QLabel *, QWidget * > > option_rows_
std::unordered_map< QWidget *, std::pair< QLabel *, QWidget * > > widget_rows_
std::unordered_map< QLayout *, std::pair< QLabel *, QWidget * > > layout_rows_
std::vector< std::pair< QSpinBox *, int * > > options_int_
std::vector< std::pair< QDoubleSpinBox *, double * > > options_double_
std::vector< std::pair< QDoubleSpinBox *, double * > > options_double_log_
std::vector< std::pair< QCheckBox *, bool * > > options_bool_
std::vector< std::pair< QLineEdit *, std::string * > > options_text_
std::vector< std::pair< QLineEdit *, std::string * > > options_path_
Detailed Description
Definition at line 16 of file options_widget.h.
Constructor & Destructor Documentation
OptionsWidget()
colmap::OptionsWidget::OptionsWidget (QWidget * parent) explicit
Definition at line 36 of file options_widget.cc.
References grid_layout_.
Member Function Documentation
AddLayoutRow()
void colmap::OptionsWidget::AddLayoutRow (const std::string & label_text, QLayout * layout)
Definition at line 77 of file options_widget.cc.
References grid_layout_, layout_rows_, and cloudViewer::core::make_pair().
AddOptionBool()
QCheckBox * colmap::OptionsWidget::AddOptionBool (bool * option, const std::string & label_text)
Definition at line 139 of file options_widget.cc.
References AddOptionRow(), and options_bool_.
Referenced by colmap::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::FeatureMatchingTab::CreateGeneralOptions(), colmap::FeatureMatchingTab::CreateGeneralOptions(), cloudViewer::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget(), colmap::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget(), cloudViewer::MapperGeneralOptionsWidget::MapperGeneralOptionsWidget(), colmap::MapperGeneralOptionsWidget::MapperGeneralOptionsWidget(), cloudViewer::MapperTriangulationOptionsWidget::MapperTriangulationOptionsWidget(), colmap::MapperTriangulationOptionsWidget::MapperTriangulationOptionsWidget(), cloudViewer::SequentialMatchingTab::SequentialMatchingTab(), colmap::SequentialMatchingTab::SequentialMatchingTab(), cloudViewer::SIFTExtractionWidget::SIFTExtractionWidget(), colmap::SIFTExtractionWidget::SIFTExtractionWidget(), cloudViewer::SpatialMatchingTab::SpatialMatchingTab(), and colmap::SpatialMatchingTab::SpatialMatchingTab().
AddOptionDirPath()
QLineEdit * colmap::OptionsWidget::AddOptionDirPath (std::string * option, const std::string & label_text)
Definition at line 181 of file options_widget.cc.
References AddOptionRow(), grid_layout_, and options_path_.
Referenced by colmap::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::ImportFeaturesWidget::ImportFeaturesWidget(), colmap::ImportFeaturesWidget::ImportFeaturesWidget(), cloudViewer::MapperGeneralOptionsWidget::MapperGeneralOptionsWidget(), colmap::MapperGeneralOptionsWidget::MapperGeneralOptionsWidget(), cloudViewer::SIFTExtractionWidget::SIFTExtractionWidget(), and colmap::SIFTExtractionWidget::SIFTExtractionWidget().
AddOptionDouble()
QDoubleSpinBox * colmap::OptionsWidget::AddOptionDouble (double * option, const std::string & label_text, const double min = 0, const double max = 1e7, const double step = 0.01, const int decimals = 2)
Definition at line 107 of file options_widget.cc.
References AddOptionRow(), and options_double_.
Referenced by cloudViewer::FeatureMatchingTab::CreateGeneralOptions(), colmap::FeatureMatchingTab::CreateGeneralOptions(), cloudViewer::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget(), colmap::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget(), cloudViewer::MapperFilteringOptionsWidget::MapperFilteringOptionsWidget(), colmap::MapperFilteringOptionsWidget::MapperFilteringOptionsWidget(), cloudViewer::MapperInitializationOptionsWidget::MapperInitializationOptionsWidget(), colmap::MapperInitializationOptionsWidget::MapperInitializationOptionsWidget(), cloudViewer::MapperRegistrationOptionsWidget::MapperRegistrationOptionsWidget(), colmap::MapperRegistrationOptionsWidget::MapperRegistrationOptionsWidget(), cloudViewer::MapperTriangulationOptionsWidget::MapperTriangulationOptionsWidget(), colmap::MapperTriangulationOptionsWidget::MapperTriangulationOptionsWidget(), cloudViewer::SIFTExtractionWidget::SIFTExtractionWidget(), colmap::SIFTExtractionWidget::SIFTExtractionWidget(), cloudViewer::SpatialMatchingTab::SpatialMatchingTab(), and colmap::SpatialMatchingTab::SpatialMatchingTab().
AddOptionDoubleLog()
QDoubleSpinBox * colmap::OptionsWidget::AddOptionDoubleLog (double * option, const std::string & label_text, const double min = 0, const double max = 1e7, const double step = 0.01, const int decimals = 2)
Definition at line 123 of file options_widget.cc.
References AddOptionRow(), and options_double_log_.
AddOptionFilePath()
QLineEdit * colmap::OptionsWidget::AddOptionFilePath (std::string * option, const std::string & label_text)
Definition at line 161 of file options_widget.cc.
References AddOptionRow(), grid_layout_, and options_path_.
Referenced by colmap::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::CustomMatchingTab::CustomMatchingTab(), colmap::CustomMatchingTab::CustomMatchingTab(), cloudViewer::SequentialMatchingTab::SequentialMatchingTab(), colmap::SequentialMatchingTab::SequentialMatchingTab(), cloudViewer::SIFTExtractionWidget::SIFTExtractionWidget(), colmap::SIFTExtractionWidget::SIFTExtractionWidget(), cloudViewer::VocabTreeMatchingTab::VocabTreeMatchingTab(), and colmap::VocabTreeMatchingTab::VocabTreeMatchingTab().
AddOptionInt()
QSpinBox * colmap::OptionsWidget::AddOptionInt (int * option, const std::string & label_text, const int min = 0, const int max = static_cast<int>(1e7))
Definition at line 93 of file options_widget.cc.
References AddOptionRow(), and options_int_.
Referenced by colmap::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::FeatureMatchingTab::CreateGeneralOptions(), colmap::FeatureMatchingTab::CreateGeneralOptions(), cloudViewer::CustomMatchingTab::CustomMatchingTab(), colmap::CustomMatchingTab::CustomMatchingTab(), cloudViewer::ExhaustiveMatchingTab::ExhaustiveMatchingTab(), colmap::ExhaustiveMatchingTab::ExhaustiveMatchingTab(), cloudViewer::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget(), colmap::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget(), cloudViewer::MapperGeneralOptionsWidget::MapperGeneralOptionsWidget(), colmap::MapperGeneralOptionsWidget::MapperGeneralOptionsWidget(), cloudViewer::MapperInitializationOptionsWidget::MapperInitializationOptionsWidget(), colmap::MapperInitializationOptionsWidget::MapperInitializationOptionsWidget(), cloudViewer::MapperRegistrationOptionsWidget::MapperRegistrationOptionsWidget(), colmap::MapperRegistrationOptionsWidget::MapperRegistrationOptionsWidget(), cloudViewer::MapperTriangulationOptionsWidget::MapperTriangulationOptionsWidget(), colmap::MapperTriangulationOptionsWidget::MapperTriangulationOptionsWidget(), cloudViewer::SequentialMatchingTab::SequentialMatchingTab(), colmap::SequentialMatchingTab::SequentialMatchingTab(), cloudViewer::SIFTExtractionWidget::SIFTExtractionWidget(), colmap::SIFTExtractionWidget::SIFTExtractionWidget(), cloudViewer::SpatialMatchingTab::SpatialMatchingTab(), colmap::SpatialMatchingTab::SpatialMatchingTab(), cloudViewer::TransitiveMatchingTab::TransitiveMatchingTab(), colmap::TransitiveMatchingTab::TransitiveMatchingTab(), cloudViewer::VocabTreeMatchingTab::VocabTreeMatchingTab(), and colmap::VocabTreeMatchingTab::VocabTreeMatchingTab().
AddOptionRow()
void colmap::OptionsWidget::AddOptionRow (const std::string & label_text, QWidget * widget, void * option)
Definition at line 50 of file options_widget.cc.
References grid_layout_, cloudViewer::core::make_pair(), option_rows_, and widget_rows_.
Referenced by AddOptionBool(), AddOptionDirPath(), AddOptionDouble(), AddOptionDoubleLog(), AddOptionFilePath(), AddOptionInt(), AddOptionText(), cloudViewer::CustomMatchingTab::CustomMatchingTab(), and colmap::CustomMatchingTab::CustomMatchingTab().
AddOptionText()
QLineEdit * colmap::OptionsWidget::AddOptionText (std::string * option, const std::string & label_text)
Definition at line 150 of file options_widget.cc.
References AddOptionRow(), and options_text_.
Referenced by colmap::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::FeatureMatchingTab::CreateGeneralOptions(), colmap::FeatureMatchingTab::CreateGeneralOptions(), cloudViewer::SIFTExtractionWidget::SIFTExtractionWidget(), and colmap::SIFTExtractionWidget::SIFTExtractionWidget().
AddSection()
void colmap::OptionsWidget::AddSection (const std::string & title)
Definition at line 208 of file options_widget.cc.
References grid_layout_.
Referenced by cloudViewer::FeatureMatchingTab::CreateGeneralOptions(), colmap::FeatureMatchingTab::CreateGeneralOptions(), cloudViewer::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget(), and colmap::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget().
AddSpacer()
void colmap::OptionsWidget::AddSpacer ()
Definition at line 202 of file options_widget.cc.
References grid_layout_.
Referenced by colmap::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::FeatureMatchingTab::CreateGeneralOptions(), colmap::FeatureMatchingTab::CreateGeneralOptions(), cloudViewer::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget(), and colmap::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget().
AddWidgetRow()
void colmap::OptionsWidget::AddWidgetRow (const std::string & label_text, QWidget * widget)
Definition at line 64 of file options_widget.cc.
References grid_layout_, cloudViewer::core::make_pair(), and widget_rows_.
closeEvent()
void colmap::OptionsWidget::closeEvent (QCloseEvent * event) protected
Definition at line 270 of file options_widget.cc.
References WriteOptions().
hideEvent()
void colmap::OptionsWidget::hideEvent (QHideEvent * event) protected
Definition at line 272 of file options_widget.cc.
References WriteOptions().
HideLayout()
void colmap::OptionsWidget::HideLayout (QLayout * option) protected
Definition at line 304 of file options_widget.cc.
References layout_rows_.
HideOption()
void colmap::OptionsWidget::HideOption (void * option) protected
Definition at line 280 of file options_widget.cc.
References option_rows_.
HideWidget()
void colmap::OptionsWidget::HideWidget (QWidget * option) protected
Definition at line 292 of file options_widget.cc.
References widget_rows_.
ReadOptions()
void colmap::OptionsWidget::ReadOptions ()
Definition at line 216 of file options_widget.cc.
References options_bool_, options_double_, options_double_log_, options_int_, options_path_, and options_text_.
Referenced by showEvent().
showEvent()
void colmap::OptionsWidget::showEvent (QShowEvent * event) protected
Definition at line 268 of file options_widget.cc.
References ReadOptions().
Referenced by cloudViewer::AutomaticReconstructionWidget::showEvent().
ShowLayout()
void colmap::OptionsWidget::ShowLayout (QLayout * option) protected
Definition at line 298 of file options_widget.cc.
References layout_rows_.
ShowOption()
void colmap::OptionsWidget::ShowOption (void * option) protected
Definition at line 274 of file options_widget.cc.
References option_rows_.
ShowWidget()
void colmap::OptionsWidget::ShowWidget (QWidget * option) protected
Definition at line 286 of file options_widget.cc.
References widget_rows_.
WriteOptions()
void colmap::OptionsWidget::WriteOptions ()
Definition at line 242 of file options_widget.cc.
References options_bool_, options_double_, options_double_log_, options_int_, options_path_, and options_text_.
Referenced by closeEvent(), hideEvent(), cloudViewer::AutomaticReconstructionWidget::Run(), colmap::AutomaticReconstructionWidget::Run(), cloudViewer::SIFTExtractionWidget::Run(), cloudViewer::ImportFeaturesWidget::Run(), cloudViewer::ExhaustiveMatchingTab::Run(), cloudViewer::SequentialMatchingTab::Run(), cloudViewer::VocabTreeMatchingTab::Run(), cloudViewer::SpatialMatchingTab::Run(), cloudViewer::TransitiveMatchingTab::Run(), cloudViewer::CustomMatchingTab::Run(), colmap::SIFTExtractionWidget::Run(), colmap::ImportFeaturesWidget::Run(), colmap::ExhaustiveMatchingTab::Run(), colmap::SequentialMatchingTab::Run(), colmap::VocabTreeMatchingTab::Run(), colmap::SpatialMatchingTab::Run(), colmap::TransitiveMatchingTab::Run(), and colmap::CustomMatchingTab::Run().
Member Data Documentation
grid_layout_
QGridLayout* colmap::OptionsWidget::grid_layout_ protected
Definition at line 70 of file options_widget.h.
Referenced by AddLayoutRow(), AddOptionDirPath(), AddOptionFilePath(), AddOptionRow(), AddSection(), AddSpacer(), AddWidgetRow(), colmap::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), cloudViewer::AutomaticReconstructionWidget::AutomaticReconstructionWidget(), and OptionsWidget().
layout_rows_
std::unordered_map<QLayout*, std::pair<QLabel*, QWidget*> > colmap::OptionsWidget::layout_rows_ protected
Definition at line 74 of file options_widget.h.
Referenced by AddLayoutRow(), HideLayout(), and ShowLayout().
option_rows_
std::unordered_map<void*, std::pair<QLabel*, QWidget*> > colmap::OptionsWidget::option_rows_ protected
Definition at line 72 of file options_widget.h.
Referenced by AddOptionRow(), HideOption(), and ShowOption().
options_bool_
std::vector<std::pair<QCheckBox*, bool*> > colmap::OptionsWidget::options_bool_ protected
Definition at line 79 of file options_widget.h.
Referenced by AddOptionBool(), ReadOptions(), and WriteOptions().
options_double_
std::vector<std::pair<QDoubleSpinBox*, double*> > colmap::OptionsWidget::options_double_ protected
Definition at line 77 of file options_widget.h.
Referenced by AddOptionDouble(), ReadOptions(), and WriteOptions().
options_double_log_
std::vector<std::pair<QDoubleSpinBox*, double*> > colmap::OptionsWidget::options_double_log_ protected
Definition at line 78 of file options_widget.h.
Referenced by AddOptionDoubleLog(), ReadOptions(), and WriteOptions().
options_int_
std::vector<std::pair<QSpinBox*, int*> > colmap::OptionsWidget::options_int_ protected
Definition at line 76 of file options_widget.h.
Referenced by AddOptionInt(), ReadOptions(), and WriteOptions().
options_path_
std::vector<std::pair<QLineEdit*, std::string*> > colmap::OptionsWidget::options_path_ protected
Definition at line 81 of file options_widget.h.
Referenced by AddOptionDirPath(), AddOptionFilePath(), ReadOptions(), cloudViewer::AutomaticReconstructionWidget::showEvent(), and WriteOptions().
options_text_
std::vector<std::pair<QLineEdit*, std::string*> > colmap::OptionsWidget::options_text_ protected
Definition at line 80 of file options_widget.h.
Referenced by AddOptionText(), ReadOptions(), and WriteOptions().
widget_rows_
std::unordered_map<QWidget*, std::pair<QLabel*, QWidget*> > colmap::OptionsWidget::widget_rows_ protected
Definition at line 73 of file options_widget.h.
Referenced by AddOptionRow(), AddWidgetRow(), HideWidget(), and ShowWidget().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/options_widget.h
/root/ACloudViewer/libs/Reconstruction/src/ui/options_widget.cc