ACloudViewer: QUIConfig Class Reference
QUIConfig Class Reference
#include <ecvUIManager.h>
Static Public Member Functions
static void ReadConfig ()
static void WriteConfig ()
static void NewConfig ()
static bool CheckConfig ()
Static Public Attributes
static QChar IconMain = QChar(0xf072)
static QChar IconMenu = QChar(0xf0d7)
static QChar IconMin = QChar(0xf068)
static QChar IconMax = QChar(0xf2d2)
static QChar IconNormal = QChar(0xf2d0)
static QChar IconClose = QChar(0xf00d)
static QString FontName = "Microsoft Yahei"
static int FontSize = 9
static QString ConfigFile = "config.ini"
static QString TextColor = "#F0F0F0"
static QString PanelColor = "#F0F0F0"
static QString BorderColor = "#F0F0F0"
static QString NormalColorStart = "#F0F0F0"
static QString NormalColorEnd = "#F0F0F0"
static QString DarkColorStart = "#F0F0F0"
static QString DarkColorEnd = "#F0F0F0"
static QString HighColor = "#F0F0F0"
Detailed Description
Definition at line 626 of file ecvUIManager.h.
Member Function Documentation
CheckConfig()
bool QUIConfig::CheckConfig () static
Definition at line 2627 of file ecvUIManager.cpp.
References ConfigFile, and NewConfig().
Referenced by ReadConfig().
NewConfig()
void QUIConfig::NewConfig () static
Definition at line 2621 of file ecvUIManager.cpp.
References WriteConfig().
Referenced by CheckConfig().
ReadConfig()
void QUIConfig::ReadConfig () static
Definition at line 2603 of file ecvUIManager.cpp.
References CheckConfig(), and ConfigFile.
WriteConfig()
void QUIConfig::WriteConfig () static
Definition at line 2614 of file ecvUIManager.cpp.
References ConfigFile.
Referenced by NewConfig().
Member Data Documentation
BorderColor
QString QUIConfig::BorderColor = "#F0F0F0" static
Definition at line 643 of file ecvUIManager.h.
ConfigFile
QString QUIConfig::ConfigFile = "config.ini" static
Definition at line 638 of file ecvUIManager.h.
Referenced by CheckConfig(), ReadConfig(), and WriteConfig().
DarkColorEnd
QString QUIConfig::DarkColorEnd = "#F0F0F0" static
Definition at line 647 of file ecvUIManager.h.
DarkColorStart
QString QUIConfig::DarkColorStart = "#F0F0F0" static
Definition at line 646 of file ecvUIManager.h.
FontName
QString QUIConfig::FontName = "Microsoft Yahei" static
Definition at line 636 of file ecvUIManager.h.
FontSize
int QUIConfig::FontSize = 9 static
Definition at line 637 of file ecvUIManager.h.
HighColor
QString QUIConfig::HighColor = "#F0F0F0" static
Definition at line 648 of file ecvUIManager.h.
IconClose
QChar QUIConfig::IconClose = QChar(0xf00d) static
Definition at line 634 of file ecvUIManager.h.
Referenced by QUIWidget::setIcon().
IconMain
QChar QUIConfig::IconMain = QChar(0xf072) static
Definition at line 629 of file ecvUIManager.h.
Referenced by QUIWidget::setIconMain().
IconMax
QChar QUIConfig::IconMax = QChar(0xf2d2) static
Definition at line 632 of file ecvUIManager.h.
Referenced by QUIWidget::setIcon().
IconMenu
QChar QUIConfig::IconMenu = QChar(0xf0d7) static
Definition at line 630 of file ecvUIManager.h.
Referenced by QUIWidget::setIcon().
IconMin
QChar QUIConfig::IconMin = QChar(0xf068) static
Definition at line 631 of file ecvUIManager.h.
Referenced by QUIWidget::setIcon().
IconNormal
QChar QUIConfig::IconNormal = QChar(0xf2d0) static
Definition at line 633 of file ecvUIManager.h.
Referenced by QUIWidget::setIcon().
NormalColorEnd
QString QUIConfig::NormalColorEnd = "#F0F0F0" static
Definition at line 645 of file ecvUIManager.h.
NormalColorStart
QString QUIConfig::NormalColorStart = "#F0F0F0" static
Definition at line 644 of file ecvUIManager.h.
PanelColor
QString QUIConfig::PanelColor = "#F0F0F0" static
Definition at line 642 of file ecvUIManager.h.
TextColor
QString QUIConfig::TextColor = "#F0F0F0" static
Definition at line 641 of file ecvUIManager.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvUIManager.h
/root/ACloudViewer/app/ecvUIManager.cpp