ACloudViewer: ccCorkDlg Class Reference
ccCorkDlg Class Reference
Dialog for qCork plugin.
#include <ccCorkDlg.h>
Public Types
enum CSG_OPERATION { UNION , INTERSECT , DIFF , SYM_DIFF }
Supported CSG operations.
Public Member Functions
ccCorkDlg (QWidget *parent=0)
Default constructor.
void setNames (QString A, QString B)
Set meshes names.
CSG_OPERATION getSelectedOperation () const
Returns the selected operation.
bool isSwapped () const
Returns whether mesh order has been swappped or not.
Protected Slots
void unionSelected ()
void intersectSelected ()
void diffSelected ()
void symDiffSelected ()
void swap ()
Protected Attributes
CSG_OPERATION m_selectedOperation
bool m_isSwapped
Detailed Description
Dialog for qCork plugin.
Definition at line 13 of file ccCorkDlg.h.
Member Enumeration Documentation
CSG_OPERATION
enum ccCorkDlg::CSG_OPERATION
Supported CSG operations.
Enumerator
UNION
INTERSECT
DIFF
SYM_DIFF
Definition at line 21 of file ccCorkDlg.h.
Constructor & Destructor Documentation
ccCorkDlg()
ccCorkDlg::ccCorkDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 10 of file ccCorkDlg.cpp.
References diffSelected(), intersectSelected(), swap(), symDiffSelected(), and unionSelected().
Member Function Documentation
diffSelected
void ccCorkDlg::diffSelected () protected slot
Definition at line 41 of file ccCorkDlg.cpp.
References DIFF, and m_selectedOperation.
Referenced by ccCorkDlg().
getSelectedOperation()
CSG_OPERATION ccCorkDlg::getSelectedOperation () const inline
Returns the selected operation.
Definition at line 27 of file ccCorkDlg.h.
References m_selectedOperation.
Referenced by qCork::doAction().
intersectSelected
void ccCorkDlg::intersectSelected () protected slot
Definition at line 36 of file ccCorkDlg.cpp.
References INTERSECT, and m_selectedOperation.
Referenced by ccCorkDlg().
isSwapped()
bool ccCorkDlg::isSwapped () const inline
Returns whether mesh order has been swappped or not.
Definition at line 30 of file ccCorkDlg.h.
References m_isSwapped.
Referenced by qCork::doAction().
setNames()
void ccCorkDlg::setNames (QString A, QString B)
Set meshes names.
Definition at line 26 of file ccCorkDlg.cpp.
Referenced by qCork::doAction(), and swap().
swap
void ccCorkDlg::swap () protected slot
Definition at line 51 of file ccCorkDlg.cpp.
References m_isSwapped, and setNames().
Referenced by ccCorkDlg().
symDiffSelected
void ccCorkDlg::symDiffSelected () protected slot
Definition at line 46 of file ccCorkDlg.cpp.
References m_selectedOperation, and SYM_DIFF.
Referenced by ccCorkDlg().
unionSelected
void ccCorkDlg::unionSelected () protected slot
Definition at line 31 of file ccCorkDlg.cpp.
References m_selectedOperation, and UNION.
Referenced by ccCorkDlg().
Member Data Documentation
m_isSwapped
bool ccCorkDlg::m_isSwapped protected
Definition at line 42 of file ccCorkDlg.h.
Referenced by isSwapped(), and swap().
m_selectedOperation
CSG_OPERATION ccCorkDlg::m_selectedOperation protected
Definition at line 41 of file ccCorkDlg.h.
Referenced by diffSelected(), getSelectedOperation(), intersectSelected(), symDiffSelected(), and unionSelected().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCork/include/ccCorkDlg.h
/root/ACloudViewer/plugins/core/Standard/qCork/src/ccCorkDlg.cpp