ACloudViewer: qM3C2Normals Class Reference
qM3C2Normals Class Reference
M3C2 normals computation related tools.
#include <qM3C2Tools.h>
Public Types
enum ComputationMode {
DEFAULT_MODE = 0 , USE_CLOUD1_NORMALS = 1 , MULTI_SCALE_MODE = 2 , VERT_MODE = 3 ,
HORIZ_MODE = 4 , USE_CORE_POINTS_NORMALS = 5
}
Normals computation mode.
Static Public Member Functions
static bool ComputeCorePointsNormals (cloudViewer::GenericIndexedCloud *corePoints, NormsIndexesTableType *corePointsNormals, ccGenericPointCloud *sourceCloud, const std::vector< PointCoordinateType > &sortedRadii, bool &invalidNormals, int maxThreadCount=0, ccScalarField *normalScale=nullptr, cloudViewer::GenericProgressCallback *progressCb=nullptr, cloudViewer::DgmOctree *inputOctree=nullptr)
Computes normals on core points only.
static bool UpdateNormalOrientationsWithCloud (cloudViewer::GenericIndexedCloud *normCloud, NormsIndexesTableType &normsCodes, cloudViewer::GenericIndexedCloud *orientationCloud, int maxThreadCount=0, cloudViewer::GenericProgressCallback *progressCb=nullptr)
static void MakeNormalsHorizontal (NormsIndexesTableType &normsCodes)
Makes all normals horizontal.
Detailed Description
M3C2 normals computation related tools.
Definition at line 22 of file qM3C2Tools.h.
Member Enumeration Documentation
ComputationMode
enum qM3C2Normals::ComputationMode
Normals computation mode.
Warning
Don't change the associated values! (for parameter files)
Enumerator
DEFAULT_MODE
USE_CLOUD1_NORMALS
MULTI_SCALE_MODE
VERT_MODE
HORIZ_MODE
USE_CORE_POINTS_NORMALS
Definition at line 27 of file qM3C2Tools.h.
Member Function Documentation
ComputeCorePointsNormals()
bool qM3C2Normals::ComputeCorePointsNormals (cloudViewer::GenericIndexedCloud * corePoints, NormsIndexesTableType * corePointsNormals, ccGenericPointCloud * sourceCloud, const std::vector< PointCoordinateType > & sortedRadii, bool & invalidNormals, int maxThreadCount = 0, ccScalarField * normalScale = nullptr, cloudViewer::GenericProgressCallback * progressCb = nullptr, cloudViewer::DgmOctree * inputOctree = nullptr) static
Computes normals on core points only.
See qCC's ccNormalVectors::ComputeCloudNormals.
Warning
normals orientation is not resolved!
Definition at line 179 of file qM3C2Tools.cpp.
References cloudViewer::DgmOctree::build(), ComputeCorePointNormal(), corePoints, cloudViewer::ScalarField::currentSize(), ccArray< Type, N, ComponentType >::currentSize(), cloudViewer::ScalarField::fill(), cloudViewer::DgmOctree::findBestLevelForAGivenNeighbourhoodSizeExtraction(), invalidNormals, ccArray< Type, N, ComponentType >::isAllocated(), NAN_VALUE, normalScale, nProgress, octreeLevel, ccArray< Type, N, ComponentType >::resizeSafe(), cloudViewer::ScalarField::resizeSafe(), s_corePointsNormalsParams, cloudViewer::GenericProgressCallback::setInfo(), cloudViewer::GenericProgressCallback::setMethodTitle(), cloudViewer::GenericCloud::size(), sourceCloud, cloudViewer::GenericProgressCallback::start(), cloudViewer::GenericProgressCallback::stop(), and cloudViewer::GenericProgressCallback::textCanBeEdited().
Referenced by qM3C2Process::Compute().
MakeNormalsHorizontal()
void qM3C2Normals::MakeNormalsHorizontal (NormsIndexesTableType & normsCodes) static
Makes all normals horizontal.
Definition at line 429 of file qM3C2Tools.cpp.
References count, ccArray< Type, N, ComponentType >::currentSize(), ccNormalVectors::GetNormal(), ccNormalVectors::GetNormIndex(), ccArray< Type, N, ComponentType >::getValue(), Vector3Tpl< Type >::normalize(), normsCodes, ccArray< Type, N, ComponentType >::setValue(), Tuple3Tpl< Type >::u, and Tuple3Tpl< Type >::z.
Referenced by qM3C2Process::Compute().
UpdateNormalOrientationsWithCloud()
bool qM3C2Normals::UpdateNormalOrientationsWithCloud (cloudViewer::GenericIndexedCloud * normCloud, NormsIndexesTableType & normsCodes, cloudViewer::GenericIndexedCloud * orientationCloud, int maxThreadCount = 0, cloudViewer::GenericProgressCallback * progressCb = nullptr) static
Re-orients normal vectors so that they all 'look' towards the nearest point of another cloud
Definition at line 346 of file qM3C2Tools.cpp.
References count, ccArray< Type, N, ComponentType >::currentSize(), normCloud, normsCodes, nProgress, orientationCloud, OrientPointNormalWithCloud(), s_normOriWithCloud, cloudViewer::GenericProgressCallback::setInfo(), cloudViewer::GenericProgressCallback::setMethodTitle(), cloudViewer::GenericCloud::size(), cloudViewer::GenericProgressCallback::start(), cloudViewer::GenericProgressCallback::stop(), cloudViewer::GenericProgressCallback::textCanBeEdited(), and CVLog::Warning().
Referenced by qM3C2Process::Compute().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qM3C2/include/qM3C2Tools.h
/root/ACloudViewer/plugins/core/Standard/qM3C2/src/qM3C2Tools.cpp