ACloudViewer: ccCloudLayersHelper Class Reference
ccCloudLayersHelper Class Reference
#include <ccCloudLayersHelper.h>
Classes
struct Parameters
Public Member Functions
ccCloudLayersHelper (ecvMainAppInterface *app, ccPointCloud *cloud)
~ccCloudLayersHelper ()
QStringList getScalarFields ()
void setScalarFieldIndex (int index)
void setVisible (bool value)
void apply (QList< ccAsprsModel::AsprsItem > &items)
int apply (ccAsprsModel::AsprsItem &item, bool redrawDisplay=false)
void changeCode (const ccAsprsModel::AsprsItem &item, ScalarType oldCode)
int moveItem (const ccAsprsModel::AsprsItem &from, const ccAsprsModel::AsprsItem *to, bool redrawDisplay=false)
void saveState ()
void restoreState ()
void mouseMove (const CCVector2 &center, float squareDist, std::map< ScalarType, int > &affected)
void projectCloud (const ccGLCameraParameters &camera)
bool hasChanges () const
Parameters & getParameters ()
ccPointCloud * cloud ()
void keepCurrentSFVisible ()
Detailed Description
Definition at line 46 of file ccCloudLayersHelper.h.
Constructor & Destructor Documentation
ccCloudLayersHelper()
ccCloudLayersHelper::ccCloudLayersHelper (ecvMainAppInterface * app, ccPointCloud * cloud)
Definition at line 23 of file ccCloudLayersHelper.cpp.
References ColorsTableType::clone(), cloud(), ccDrawableObject::colorsShown(), CVLog::Error(), ccPointCloud::hasColors(), ccPointCloud::resizeTheRGBTable(), ccPointCloud::rgbColors(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), and cloudViewer::PointCloudTpl< T >::size().
~ccCloudLayersHelper()
ccCloudLayersHelper::~ccCloudLayersHelper ()
Definition at line 58 of file ccCloudLayersHelper.cpp.
References ccArray< Type, N, ComponentType >::copy(), ccHObject::redrawDisplay(), ccPointCloud::rgbColors(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), and ccPointCloud::unallocateColors().
Member Function Documentation
apply() [1/2]
int ccCloudLayersHelper::apply (ccAsprsModel::AsprsItem & item, bool redrawDisplay = false)
Definition at line 121 of file ccCloudLayersHelper.cpp.
References ccAsprsModel::AsprsItem::code, ccAsprsModel::AsprsItem::color, ecvColor::FromQColora(), cloudViewer::PointCloudTpl< T >::getScalarField(), ecvColor::MAX, ccHObject::redrawDisplay(), ccPointCloud::setPointColor(), and ccAsprsModel::AsprsItem::visible.
apply() [2/2]
void ccCloudLayersHelper::apply (QList< ccAsprsModel::AsprsItem > & items)
Definition at line 109 of file ccCloudLayersHelper.cpp.
References ecvColor::black(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), ccHObject::redrawDisplay(), and ccPointCloud::setRGBColor().
changeCode()
void ccCloudLayersHelper::changeCode (const ccAsprsModel::AsprsItem & item, ScalarType oldCode)
Definition at line 143 of file ccCloudLayersHelper.cpp.
References ccAsprsModel::AsprsItem::code, cloudViewer::PointCloudTpl< T >::getScalarField(), and cloudViewer::ScalarField::setValue().
cloud()
ccPointCloud* ccCloudLayersHelper::cloud () inline
Definition at line 92 of file ccCloudLayersHelper.h.
Referenced by ccCloudLayersHelper().
getParameters()
ccCloudLayersHelper::Parameters & ccCloudLayersHelper::getParameters ()
Definition at line 333 of file ccCloudLayersHelper.cpp.
getScalarFields()
QStringList ccCloudLayersHelper::getScalarFields ()
Definition at line 79 of file ccCloudLayersHelper.cpp.
References cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudViewer::PointCloudTpl< T >::getScalarFieldName(), and ccPointCloud::hasScalarFields().
Referenced by ccCloudLayersDlg::setPointCloud().
hasChanges()
bool ccCloudLayersHelper::hasChanges () const inline
Definition at line 81 of file ccCloudLayersHelper.h.
Referenced by projectCloud().
keepCurrentSFVisible()
void ccCloudLayersHelper::keepCurrentSFVisible ()
Definition at line 94 of file ccCloudLayersHelper.cpp.
References ccPointCloud::setCurrentDisplayedScalarField().
Referenced by ccCloudLayersDlg::stop().
mouseMove()
void ccCloudLayersHelper::mouseMove (const CCVector2 & center, float squareDist, std::map< ScalarType, int > & affected)
Definition at line 239 of file ccCloudLayersHelper.cpp.
References ccCloudLayersHelper::Parameters::anyPoints, ccAsprsModel::AsprsItem::code, color, ccAsprsModel::AsprsItem::color, ecvColor::FromQColor(), ccPointCloud::getPointColor(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::ScalarField::getValue(), ccCloudLayersHelper::Parameters::input, ccDrawableObject::isVisible(), ecvColor::MAX, ccCloudLayersHelper::Parameters::output, ccHObject::redrawDisplay(), ccPointCloud::setPointColor(), cloudViewer::ScalarField::setValue(), cloudViewer::PointCloudTpl< T >::size(), ccAsprsModel::AsprsItem::visible, and ccCloudLayersHelper::Parameters::visiblePoints.
moveItem()
int ccCloudLayersHelper::moveItem (const ccAsprsModel::AsprsItem & from, const ccAsprsModel::AsprsItem * to, bool redrawDisplay = false)
Definition at line 157 of file ccCloudLayersHelper.cpp.
References ecvColor::black(), ccAsprsModel::AsprsItem::code, color, ccAsprsModel::AsprsItem::color, ecvColor::FromQColor(), cloudViewer::PointCloudTpl< T >::getScalarField(), ccHObject::redrawDisplay(), ccPointCloud::setPointColor(), and cloudViewer::ScalarField::setValue().
projectCloud()
void ccCloudLayersHelper::projectCloud (const ccGLCameraParameters & camera)
Definition at line 295 of file ccCloudLayersHelper.cpp.
References abs(), ccGLMatrixTpl< T >::data(), hasChanges(), ccGLCameraParameters::modelViewMat, OPENGL_MATRIX_SIZE, and cloudViewer::PointCloudTpl< T >::size().
restoreState()
void ccCloudLayersHelper::restoreState ()
Definition at line 195 of file ccCloudLayersHelper.cpp.
References cloudViewer::PointCloudTpl< T >::getScalarField(), ccPointCloud::setPointColor(), cloudViewer::ScalarField::setValue(), and cloudViewer::PointCloudTpl< T >::size().
saveState()
void ccCloudLayersHelper::saveState ()
Definition at line 184 of file ccCloudLayersHelper.cpp.
References ccPointCloud::getPointColor(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::ScalarField::getValue(), and cloudViewer::PointCloudTpl< T >::size().
setScalarFieldIndex()
void ccCloudLayersHelper::setScalarFieldIndex (int index)
Definition at line 90 of file ccCloudLayersHelper.cpp.
setVisible()
void ccCloudLayersHelper::setVisible (bool value)
Definition at line 99 of file ccCloudLayersHelper.cpp.
References color, ccPointCloud::getPointColor(), ccHObject::redrawDisplay(), ccPointCloud::setPointColor(), ccDrawableObject::setVisible(), and cloudViewer::PointCloudTpl< T >::size().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCloudLayers/include/ccCloudLayersHelper.h
/root/ACloudViewer/plugins/core/Standard/qCloudLayers/src/ccCloudLayersHelper.cpp