ACloudViewer: cloudViewer::visualization::gui::VectorEdit Class Reference
cloudViewer::visualization::gui::VectorEdit Class Reference
#include <VectorEdit.h>
Classes
struct Impl
Public Member Functions
VectorEdit ()
~VectorEdit ()
Eigen::Vector3f GetValue () const
void SetValue (const Eigen::Vector3f &val)
Sets the value of the widget. Does not call onValueChanged.
void SetOnValueChanged (std::function< void(const Eigen::Vector3f &)> on_changed)
Size CalcPreferredSize (const LayoutContext &context, const Constraints &constraints) const override
Widget::DrawResult Draw (const DrawContext &context) override
Public Member Functions inherited from cloudViewer::visualization::gui::Widget
Widget ()
Widget (const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Widget ()
virtual void AddChild (std::shared_ptr< Widget > child)
virtual const std::vector< std::shared_ptr< Widget > > GetChildren () const
virtual const Rect & GetFrame () const
Returns the frame size in pixels.
virtual void SetFrame (const Rect &f)
virtual const Color & GetBackgroundColor () const
virtual bool IsDefaultBackgroundColor () const
virtual void SetBackgroundColor (const Color &color)
virtual bool IsVisible () const
virtual void SetVisible (bool vis)
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
virtual void SetTooltip (const char *text)
virtual const char * GetTooltip () const
virtual Size CalcMinimumSize (const LayoutContext &context) const
virtual void Layout (const LayoutContext &context)
virtual EventResult Mouse (const MouseEvent &e)
virtual EventResult Key (const KeyEvent &e)
virtual DrawResult Tick (const TickEvent &e)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::gui::Widget
enum class DrawResult { NONE , REDRAW , RELAYOUT }
enum class EventResult { IGNORED , CONSUMED , DISCARD }
Static Public Attributes inherited from cloudViewer::visualization::gui::Widget
static constexpr int DIM_GROW = 10000
Protected Member Functions inherited from cloudViewer::visualization::gui::Widget
void DrawImGuiPushEnabledState ()
void DrawImGuiPopEnabledState ()
void DrawImGuiTooltip ()
Detailed Description
Definition at line 18 of file VectorEdit.h.
Constructor & Destructor Documentation
VectorEdit()
cloudViewer::visualization::gui::VectorEdit::VectorEdit ()
Definition at line 30 of file VectorEdit.cpp.
References patch::to_string().
~VectorEdit()
cloudViewer::visualization::gui::VectorEdit::~VectorEdit ()
Definition at line 34 of file VectorEdit.cpp.
Member Function Documentation
CalcPreferredSize()
Size cloudViewer::visualization::gui::VectorEdit::CalcPreferredSize (const LayoutContext & context, const Constraints & constraints) const override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 51 of file VectorEdit.cpp.
References cloudViewer::utility::ceil(), and cloudViewer::visualization::gui::Widget::DIM_GROW.
Draw()
Widget::DrawResult cloudViewer::visualization::gui::VectorEdit::Draw (const DrawContext & context) override virtual
Draws the widget. If this is a Dear ImGUI widget, this is where the actual event processing happens. Return NONE if no action needs to be taken, REDRAW if the widget needs to be redrawn (e.g. its value changed), and RELAYOUT if the widget wishes to change size.
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 58 of file VectorEdit.cpp.
References cloudViewer::visualization::gui::colorToImgui(), context, cloudViewer::visualization::gui::Widget::DrawImGuiPopEnabledState(), cloudViewer::visualization::gui::Widget::DrawImGuiPushEnabledState(), cloudViewer::visualization::gui::Widget::DrawImGuiTooltip(), frame, cloudViewer::visualization::gui::Widget::GetFrame(), cloudViewer::visualization::gui::Widget::NONE, cloudViewer::visualization::gui::Widget::REDRAW, result, and width.
GetValue()
Eigen::Vector3f cloudViewer::visualization::gui::VectorEdit::GetValue () const
Definition at line 36 of file VectorEdit.cpp.
SetOnValueChanged()
void cloudViewer::visualization::gui::VectorEdit::SetOnValueChanged (std::function< void(const Eigen::Vector3f &)> on_changed)
Sets the function that is called whenever the value in the widget changes because of user behavior
Definition at line 46 of file VectorEdit.cpp.
SetValue()
void cloudViewer::visualization::gui::VectorEdit::SetValue (const Eigen::Vector3f & val)
Sets the value of the widget. Does not call onValueChanged.
Definition at line 38 of file VectorEdit.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/VectorEdit.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/VectorEdit.cpp