ACloudViewer: ccDrawableObject Class Reference
ccDrawableObject Class Reference abstract
Generic interface for (3D) drawable entities.
#include <ecvDrawableObject.h>
Classes
struct DisplayState
Display state.
Public Member Functions
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual void draw (CC_DRAW_CONTEXT &context)=0
Draws entity and its children.
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual void getDrawingParameters (glDrawParams &params) const
Returns main OpenGL parameters for this entity.
virtual bool hasColors () const
Returns whether colors are enabled or not.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual bool hasNormals () const
Returns whether normals are enabled or not.
virtual bool normalsShown () const
Returns whether normals are shown or not.
virtual void showNormals (bool state)
Sets normals visibility.
virtual void toggleNormals ()
Toggles normals display state.
virtual bool hasDisplayedScalarField () const
Returns whether an active scalar field is available or not.
virtual bool hasScalarFields () const
Returns whether one or more scalar fields are instantiated.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void toggleMaterials ()
Toggles material display state.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual bool pushDisplayState ()
Pushes the current display state.
virtual void popDisplayState (bool apply=true)
Pops the last pushed display state.
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Protected Attributes
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Detailed Description
Generic interface for (3D) drawable entities.
Definition at line 24 of file ecvDrawableObject.h.
Constructor & Destructor Documentation
ccDrawableObject() [1/2]
ccDrawableObject::ccDrawableObject ()
Default constructor.
ccDrawableObject() [2/2]
ccDrawableObject::ccDrawableObject (const ccDrawableObject & object)
Copy constructor.
~ccDrawableObject()
virtual ccDrawableObject::~ccDrawableObject () virtual default
Member Function Documentation
addClipPlanes()
virtual bool ccDrawableObject::addClipPlanes (const ccClipPlane & plane) virtual
Registers a new clipping plane.
Returns
false if the planes couldn't be added (not enough memory)
Referenced by define_ccDrawableObject().
applyDisplayState()
virtual void ccDrawableObject::applyDisplayState (const DisplayState & state) virtual
Applies a display state.
colorsShown()
virtual bool ccDrawableObject::colorsShown () const inline virtual
Returns whether colors are shown or not.
Definition at line 82 of file ecvDrawableObject.h.
Referenced by ccCloudLayersHelper::ccCloudLayersHelper(), define_ccDrawableObject(), and qPoissonRecon::doAction().
draw()
virtual void ccDrawableObject::draw (CC_DRAW_CONTEXT & context) pure virtual
Draws entity and its children.
Implemented in GrainsAsEllipsoids, ccMouseCircle, ccMouseCircle, ecvOrientedBBox, ccHObject, and ccBBox.
Referenced by define_ccDrawableObject().
enableGLTransformation()
virtual void ccDrawableObject::enableGLTransformation (bool state) virtual
Enables/disables associated GL transformation.
See ccDrawableObject::setGLTransformation.
Referenced by define_ccDrawableObject().
enableTempColor()
virtual void ccDrawableObject::enableTempColor (bool state) inline virtual
Set temporary color activation state.
Definition at line 155 of file ecvDrawableObject.h.
Referenced by ccThicknessTool::onNewSelection(), ccPolyline::setColor(), and ccThicknessTool::toolDisactivated().
getDrawingParameters()
virtual void ccDrawableObject::getDrawingParameters (glDrawParams & params) const virtual
Returns main OpenGL parameters for this entity.
These parameters are deduced from the visibility states of its different features (points, normals, etc.).
Parameters
params a glDrawParams structure
Reimplemented in ccPointCloud.
Referenced by ccTrace::drawMeOnly().
getGLTransformation()
virtual const ccGLMatrix& ccDrawableObject::getGLTransformation () const inline virtual
Returns associated GL transformation.
See ccDrawableObject::setGLTransformation.
Definition at line 191 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
getOpacity()
virtual float ccDrawableObject::getOpacity () const inline virtual
Definition at line 160 of file ecvDrawableObject.h.
getTempColor()
virtual const ecvColor::Rgb& ccDrawableObject::getTempColor () const inline virtual
Returns current temporary (unique) color.
Definition at line 143 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
hasColors()
virtual bool ccDrawableObject::hasColors () const inline virtual
Returns whether colors are enabled or not.
Reimplemented in ccSubMesh, ccPolyline, ccPointCloud, and ccMesh.
Definition at line 80 of file ecvDrawableObject.h.
Referenced by CCCloudToDraco(), define_ccDrawableObject(), RgbDialog::onItemPicked(), LASFilter::saveToFile(), and ToFbxMesh().
hasDisplayedScalarField()
virtual bool ccDrawableObject::hasDisplayedScalarField () const inline virtual
Returns whether an active scalar field is available or not.
Reimplemented in ccSubMesh, ccPointCloud, and ccMesh.
Definition at line 99 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
hasNormals()
virtual bool ccDrawableObject::hasNormals () const inline virtual
Returns whether normals are enabled or not.
Reimplemented in ccSubMesh, ccPointCloud, and ccMesh.
Definition at line 89 of file ecvDrawableObject.h.
Referenced by CCCloudToDraco(), define_ccDrawableObject(), qPCV::doAction(), ccGenericMesh::normalsAvailable(), ccMesh::normalsAvailable(), and ToFbxMesh().
hasScalarFields()
virtual bool ccDrawableObject::hasScalarFields () const inline virtual
Returns whether one or more scalar fields are instantiated.
WARNING: doesn't mean a scalar field is currently displayed (see ccDrawableObject::hasDisplayedScalarField).
Reimplemented in ccSubMesh, ccPointCloud, and ccMesh.
Definition at line 105 of file ecvDrawableObject.h.
Referenced by CCCloudToDraco(), define_ccDrawableObject(), and ScalarDialog::onItemPicked().
isColorOverridden()
virtual bool ccDrawableObject::isColorOverridden () const inline virtual
Returns whether colors are currently overridden by a temporary (unique) color See ccDrawableObject::setTempColor.
Definition at line 138 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject(), and ccSymbolCloud::drawMeOnly().
isFixedId()
virtual bool ccDrawableObject::isFixedId () inline virtual
Definition at line 53 of file ecvDrawableObject.h.
isGLTransEnabled()
virtual bool ccDrawableObject::isGLTransEnabled () const inline virtual
Returns whether a GL transformation is enabled or not.
Definition at line 186 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
isRedraw()
virtual bool ccDrawableObject::isRedraw () const inline virtual
Returns whether entity is to be redraw.
Definition at line 46 of file ecvDrawableObject.h.
isSelected()
virtual bool ccDrawableObject::isSelected () const inline virtual
Returns whether entity is selected or not.
Definition at line 68 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
isVisibilityLocked()
virtual bool ccDrawableObject::isVisibilityLocked () const inline virtual
Returns whether visibility is locked or not.
Definition at line 56 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
isVisible()
virtual bool ccDrawableObject::isVisible () const inline virtual
Returns whether entity is visible or not.
Definition at line 38 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject(), ccMouseCircle::draw(), ccCompass::exportToSVG(), ccCompass::hideAllPointClouds(), ccCloudLayersHelper::mouseMove(), qM3C2Dialog::setClouds(), qVoxFallDialog::setMeshes(), ccCloudLayersDlg::stop(), DistanceMapGenerationDlg::toggleOverlayGrid(), ccCompass::tryLoading(), GrainsAsEllipsoids::updateMeshAndLineSet(), and DistanceMapGenerationDlg::updateZoom().
lockVisibility()
virtual void ccDrawableObject::lockVisibility (bool state) inline virtual
Locks/unlocks visibility.
If visibility is locked, the user won't be able to modify it (via the properties tree for instance).
Definition at line 63 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject(), and GrainsAsEllipsoids::GrainsAsEllipsoids().
nameShownIn3D()
virtual bool ccDrawableObject::nameShownIn3D () const inline virtual
Returns whether name is displayed in 3D or not.
Definition at line 128 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
normalsShown()
virtual bool ccDrawableObject::normalsShown () const inline virtual
Returns whether normals are shown or not.
Reimplemented in ccSubMesh, and ccMesh.
Definition at line 91 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
popDisplayState()
virtual void ccDrawableObject::popDisplayState (bool apply = true) virtual
Pops the last pushed display state.
Reimplemented in ccHObject.
pushDisplayState()
virtual bool ccDrawableObject::pushDisplayState () virtual
Pushes the current display state.
Reimplemented in ccHObject.
removeAllClipPlanes()
virtual void ccDrawableObject::removeAllClipPlanes () inline virtual
Removes all clipping planes (if any)
Definition at line 218 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
resetGLTransformation()
virtual void ccDrawableObject::resetGLTransformation () virtual
Resets associated GL transformation.
GL transformation is reset to identity. Note: GL transformation is automatically disabled. See ccDrawableObject::setGLTransformation.
Referenced by define_ccDrawableObject().
rotateGL()
virtual void ccDrawableObject::rotateGL (const ccGLMatrix & rotMat) virtual
Multiplies (left) current GL transformation by a rotation matrix.
'GLtrans = M * GLtrans' Note: GL transformation is automatically enabled. See ccDrawableObject::setGLTransformation.
Referenced by define_ccDrawableObject().
setFixedId()
virtual void ccDrawableObject::setFixedId (bool state) inline virtual
Definition at line 52 of file ecvDrawableObject.h.
setForceRedraw()
virtual void ccDrawableObject::setForceRedraw (bool state) inline virtual
Sets force redraw.
Definition at line 50 of file ecvDrawableObject.h.
Referenced by FastGlobalRegistrationDialog::updateGUI().
setGLTransformation()
virtual void ccDrawableObject::setGLTransformation (const ccGLMatrix & trans) virtual
Associates entity with a GL transformation (rotation + translation)
Warning
FOR DISPLAY PURPOSE ONLY (i.e. should only be temporary) If the associated GL transformation is enabled (see ccDrawableObject::enableGLTransformation), it will be applied before displaying this entity. However it will not be taken into account by any cloudViewer algorithm (distance computation, etc.) for instance. Note: GL transformation is automatically enabled.
Referenced by CorrespondenceMatching::applyTransformation(), TemplateAlignment::applyTransformation(), define_ccDrawableObject(), JsonRPCPlugin::execute(), GetConeProfile(), PDMSFilter::loadFile(), and qSRA::loadProfile().
setOpacity()
virtual void ccDrawableObject::setOpacity (float opacity) inline virtual
Set opacity activation state.
Definition at line 163 of file ecvDrawableObject.h.
setRedraw()
virtual void ccDrawableObject::setRedraw (bool state) inline virtual
Sets entity redraw mode.
Definition at line 48 of file ecvDrawableObject.h.
Referenced by qCanupoPlugin::doClassifyAction(), qSRA::doComputeRadialDists(), masc::Classifier::evaluate(), qVoxFallDialog::setMesh1Visibility(), qVoxFallDialog::setMesh2Visibility(), and StereogramDialog::updateFacetsFilter().
setSelected()
virtual void ccDrawableObject::setSelected (bool state) inline virtual
Selects/Unselects entity.
Definition at line 70 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
setTempColor()
virtual void ccDrawableObject::setTempColor (const ecvColor::Rgb & col, bool autoActivate = true) virtual
Sets current temporary (unique)
Parameters
col rgb color
autoActivate auto activates temporary color
Referenced by define_ccDrawableObject(), DistanceMapGenerationDlg::loadOverlaySymbols(), ccThicknessTool::onNewSelection(), DistanceMapGenerationDlg::overlayGridColorChanged(), DistanceMapGenerationDlg::overlaySymbolsColorChanged(), DistanceMapGenerationDlg::toggleOverlayGrid(), and FastGlobalRegistrationDialog::updateGUI().
setVisible()
virtual void ccDrawableObject::setVisible (bool state) inline virtual
Sets entity visibility.
Definition at line 40 of file ecvDrawableObject.h.
Referenced by qCanupo2DViewDialog::addObject(), ccCloudLayersDlg::ccCloudLayersDlg(), ccMouseCircle::ccMouseCircle(), ccCompass::cleanupBeforeToolChange(), DistanceMapGenerationDlg::clearView(), CorrespondenceMatching::compute(), NurbsCurveFitting::compute(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), qSRA::computeCloud2ProfileRadialDist(), ccTopologyRelation::constructGraphic(), contourPoly(), contourPoly2(), DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertProfileToMesh(), qFacets::createFacets(), CC_ITEM_TREE::createPointLabel2D(), define_ccDrawableObject(), qCSF::doAction(), qPoissonRecon::doAction(), ccCompass::exportToSVG(), ccTraceTool::finishCurrentTrace(), GrainsAsEllipsoids::GrainsAsEllipsoids(), ccCompass::hideAllPointClouds(), IcmFilter::LoadCalibratedImages(), CSVMatrixFilter::loadFile(), PhotoScanFilter::loadFile(), PcdFilter::loadFile(), PovFilter::loadFile(), SinusxFilter::loadFile(), PDMSFilter::loadFile(), DRCFilter::loadFile(), RDBFilter::loadFile(), LoadImage(), DistanceMapGenerationDlg::loadOverlaySymbols(), LoadScan(), ccThicknessTool::onNewSelection(), ccTraceTool::pickupTrace(), ccFitPlaneTool::pointPicked(), ccLineationTool::pointPicked(), ccTraceTool::pointPicked(), qM3C2Dialog::setCloud1Visibility(), qM3C2Dialog::setCloud2Visibility(), qVoxFallDialog::setMesh1Visibility(), qVoxFallDialog::setMesh2Visibility(), ccCloudLayersHelper::setVisible(), DistanceMapGenerationDlg::toggleOverlayGrid(), ccFitPlaneTool::toolActivated(), ccFitPlaneTool::toolDisactivated(), ccThicknessTool::toolDisactivated(), ccCompass::tryLoading(), DistanceMapGenerationDlg::update(), StereogramDialog::updateFacetsFilter(), and FastGlobalRegistrationDialog::updateGUI().
sfShown()
virtual bool ccDrawableObject::sfShown () const inline virtual
Returns whether active scalar field is visible.
Definition at line 117 of file ecvDrawableObject.h.
Referenced by ccCloudLayersHelper::ccCloudLayersHelper(), and define_ccDrawableObject().
showColors()
virtual void ccDrawableObject::showColors (bool state) inline virtual
Sets colors visibility.
Definition at line 84 of file ecvDrawableObject.h.
Referenced by ccCloudLayersHelper::ccCloudLayersHelper(), ExtractSIFT::compute(), GeneralFilters::compute(), ProjectionFilter::compute(), CorrespondenceMatching::compute(), TemplateAlignment::compute(), qSRA::computeCloud2ProfileRadialDist(), contourPoly(), contourPoly2(), define_ccDrawableObject(), qPoissonRecon::doAction(), ccCompass::estimateStrain(), GrainsAsEllipsoids::exportResultsAsCloud(), FromFbxMesh(), ProfileLoader::Load(), LoadCloud(), CSVMatrixFilter::loadFile(), SoiFilter::loadFile(), DRCFilter::loadFile(), LASFWFFilter::loadFile(), LASFilter::loadFile(), RDBFilter::loadFile(), LoadScan(), cloudViewer::io::ReadTriangleMeshFromOBJ(), qCanupo2DViewDialog::resetBoundary(), DistanceMapGenerationDlg::toggleOverlayGrid(), qCanupo2DViewDialog::trainClassifier(), qCanupoTools::TrainClassifier(), GrainsAsEllipsoids::updateMeshAndLineSet(), and ccCloudLayersHelper::~ccCloudLayersHelper().
showNameIn3D()
virtual void ccDrawableObject::showNameIn3D (bool state) inline virtual
Sets whether name should be displayed in 3D.
Definition at line 125 of file ecvDrawableObject.h.
Referenced by ccFitPlane::ccFitPlane(), ccTopologyRelation::constructGraphic(), define_ccDrawableObject(), ccCompass::importFoliations(), ccCompassImport::importFoliations(), ccLineationTool::pointPicked(), ccPinchNodeTool::pointPicked(), ccThicknessTool::pointPicked(), ccNote::updateMetadata(), and ccTopologyRelation::updateMetadata().
showNormals()
virtual void ccDrawableObject::showNormals (bool state) inline virtual
Sets normals visibility.
Reimplemented in ccGenericMesh.
Definition at line 93 of file ecvDrawableObject.h.
Referenced by qM3C2Process::Compute(), define_ccDrawableObject(), qHoughNormals::doAction(), FromFbxMesh(), LoadCloud(), RDBFilter::loadFile(), and LoadScan().
showSF()
virtual void ccDrawableObject::showSF (bool state) inline virtual
Sets active scalarfield visibility.
Definition at line 108 of file ecvDrawableObject.h.
Referenced by LasCloudChunk::addLasFieldsToCloud(), ccCloudLayersHelper::ccCloudLayersHelper(), masc::Classifier::classify(), qCanupoProcess::Classify(), ExtractSIFT::compute(), GeneralFilters::compute(), ProjectionFilter::compute(), CorrespondenceMatching::compute(), TemplateAlignment::compute(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), DistanceMapGenerationTool::ComputeRadialDist(), DistanceMapGenerationTool::ConvertMapToCloud(), ccMeasurementDevice::createScalarFieldForCloud(), define_ccDrawableObject(), qPCV::doAction(), qPoissonRecon::doAction(), ccCompass::estimateStructureNormals(), masc::Classifier::evaluate(), qFacets::extractFacets(), TreeIso::Final_seg_pcd(), getMortarMaps(), TreeIso::Init_seg_pcd(), TreeIso::Intermediate_seg_pcd(), LoadCloud(), LASFWFFilter::loadFile(), RDBFilter::loadFile(), LoadScan(), PCVCommand::Process(), and ccCloudLayersHelper::~ccCloudLayersHelper().
toggleClipPlanes()
virtual void ccDrawableObject::toggleClipPlanes (CC_DRAW_CONTEXT & context, bool enable) virtual
Enables or disables clipping planes (OpenGL)
Warning
If enabling the clipping planes, be sure to call this method AFTER the model view matrix has been set.
Referenced by define_ccDrawableObject().
toggleColors()
virtual void ccDrawableObject::toggleColors () inline virtual
Toggles colors display state.
Definition at line 86 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
toggleMaterials()
virtual void ccDrawableObject::toggleMaterials () inline virtual
Toggles material display state.
Reimplemented in ccMesh.
Definition at line 121 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
toggleNormals()
virtual void ccDrawableObject::toggleNormals () inline virtual
Toggles normals display state.
Definition at line 95 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
toggleSF()
virtual void ccDrawableObject::toggleSF () inline virtual
Toggles SF display state.
Definition at line 114 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
toggleShowName()
virtual void ccDrawableObject::toggleShowName () inline virtual
Toggles name in 3D display state.
Definition at line 131 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
toggleVisibility()
virtual void ccDrawableObject::toggleVisibility () inline virtual
Toggles visibility.
Definition at line 43 of file ecvDrawableObject.h.
Referenced by define_ccDrawableObject().
translateGL()
virtual void ccDrawableObject::translateGL (const CCVector3 & trans) virtual
Translates current GL transformation by a rotation matrix.
'GLtrans = GLtrans + T' Note: GL transformation is automatically enabled. See ccDrawableObject::setGLTransformation.
Referenced by define_ccDrawableObject().
Member Data Documentation
m_clipPlanes
ccClipPlaneSet ccDrawableObject::m_clipPlanes protected
Active clipping planes (used for display only)
Definition at line 300 of file ecvDrawableObject.h.
m_colorIsOverridden
bool ccDrawableObject::m_colorIsOverridden protected
Temporary (unique) color activation state.
Definition at line 283 of file ecvDrawableObject.h.
m_colorsDisplayed
bool ccDrawableObject::m_colorsDisplayed protected
Specifies whether colors should be displayed.
Definition at line 274 of file ecvDrawableObject.h.
m_displayStateStack
std::vector<DisplayState::Shared> ccDrawableObject::m_displayStateStack protected
The stack of pushed display states.
Definition at line 303 of file ecvDrawableObject.h.
m_fixedId
bool ccDrawableObject::m_fixedId protected
Definition at line 257 of file ecvDrawableObject.h.
m_forceRedraw
bool ccDrawableObject::m_forceRedraw protected
Definition at line 259 of file ecvDrawableObject.h.
m_glTrans
ccGLMatrix ccDrawableObject::m_glTrans protected
Current GL transformation.
See ccDrawableObject::setGLTransformation.
Definition at line 288 of file ecvDrawableObject.h.
m_glTransEnabled
bool ccDrawableObject::m_glTransEnabled protected
Current GL transformation activation state.
See ccDrawableObject::setGLTransformation.
Definition at line 292 of file ecvDrawableObject.h.
m_lockedVisibility
bool ccDrawableObject::m_lockedVisibility protected
Specifies whether the visibility can be changed by user or not.
Definition at line 271 of file ecvDrawableObject.h.
m_modelRedraw
bool ccDrawableObject::m_modelRedraw protected
Definition at line 258 of file ecvDrawableObject.h.
m_nameIn3DPos
CCVector3d ccDrawableObject::m_nameIn3DPos protected
Last 2D position of the '3D' name.
Definition at line 297 of file ecvDrawableObject.h.
m_normalsDisplayed
bool ccDrawableObject::m_normalsDisplayed protected
Specifies whether normals should be displayed.
Definition at line 276 of file ecvDrawableObject.h.
m_opacity
float ccDrawableObject::m_opacity protected
Definition at line 260 of file ecvDrawableObject.h.
m_selected
bool ccDrawableObject::m_selected protected
Specifies whether the object is selected or not.
Definition at line 268 of file ecvDrawableObject.h.
m_sfDisplayed
bool ccDrawableObject::m_sfDisplayed protected
Specifies whether scalar field should be displayed.
Definition at line 278 of file ecvDrawableObject.h.
m_showNameIn3D
bool ccDrawableObject::m_showNameIn3D protected
Whether name is displayed in 3D or not.
Definition at line 295 of file ecvDrawableObject.h.
m_tempColor
ecvColor::Rgb ccDrawableObject::m_tempColor protected
Temporary (unique) color.
Definition at line 281 of file ecvDrawableObject.h.
Referenced by ccSymbolCloud::drawMeOnly().
m_visible
bool ccDrawableObject::m_visible protected
Specifies whether the object is visible or not.
Note: this does not influence the children visibility
Definition at line 265 of file ecvDrawableObject.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvDrawableObject.h