ACloudViewer: cloudViewer::visualization::rendering::MaterialModifier Class Reference
cloudViewer::visualization::rendering::MaterialModifier Class Reference abstract
#include <MaterialModifier.h>
Public Member Functions
virtual ~MaterialModifier ()=default
virtual MaterialModifier & SetParameter (const char *parameter, int value)=0
virtual MaterialModifier & SetParameter (const char *parameter, float value)=0
virtual MaterialModifier & SetParameter (const char *parameter, const Eigen::Vector3f &value)=0
virtual MaterialModifier & SetColor (const char *parameter, const Eigen::Vector3f &value, bool srgb)=0
virtual MaterialModifier & SetColor (const char *parameter, const Eigen::Vector4f &value, bool srgb)=0
virtual MaterialModifier & SetTexture (const char *parameter, const TextureHandle &texture, const TextureSamplerParameters &sampler)=0
virtual MaterialModifier & SetDoubleSided (bool doubleSided)=0
virtual MaterialInstanceHandle Finish ()=0
Detailed Description
Definition at line 107 of file MaterialModifier.h.
Constructor & Destructor Documentation
~MaterialModifier()
virtual cloudViewer::visualization::rendering::MaterialModifier::~MaterialModifier () virtual default
Member Function Documentation
Finish()
virtual MaterialInstanceHandle cloudViewer::visualization::rendering::MaterialModifier::Finish () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentMaterialModifier.
Referenced by cloudViewer::visualization::rendering::FilamentView::PreRender().
SetColor() [1/2]
virtual MaterialModifier& cloudViewer::visualization::rendering::MaterialModifier::SetColor (const char * parameter, const Eigen::Vector3f & value, bool srgb) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentMaterialModifier.
SetColor() [2/2]
virtual MaterialModifier& cloudViewer::visualization::rendering::MaterialModifier::SetColor (const char * parameter, const Eigen::Vector4f & value, bool srgb) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentMaterialModifier.
SetDoubleSided()
virtual MaterialModifier& cloudViewer::visualization::rendering::MaterialModifier::SetDoubleSided (bool doubleSided) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentMaterialModifier.
SetParameter() [1/3]
virtual MaterialModifier& cloudViewer::visualization::rendering::MaterialModifier::SetParameter (const char * parameter, const Eigen::Vector3f & value) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentMaterialModifier.
SetParameter() [2/3]
virtual MaterialModifier& cloudViewer::visualization::rendering::MaterialModifier::SetParameter (const char * parameter, float value) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentMaterialModifier.
SetParameter() [3/3]
virtual MaterialModifier& cloudViewer::visualization::rendering::MaterialModifier::SetParameter (const char * parameter, int value) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentMaterialModifier.
Referenced by cloudViewer::visualization::rendering::FilamentView::PreRender(), and cloudViewer::visualization::rendering::FilamentScene::SetBackground().
SetTexture()
virtual MaterialModifier& cloudViewer::visualization::rendering::MaterialModifier::SetTexture (const char * parameter, const TextureHandle & texture, const TextureSamplerParameters & sampler) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentMaterialModifier.
Referenced by cloudViewer::visualization::rendering::FilamentScene::SetBackground().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/MaterialModifier.h