ACloudViewer: colmap::Point3D Class Reference
colmap::Point3D Class Reference
#include <point3d.h>
Public Member Functions
Point3D ()
const Eigen::Vector3d & XYZ () const
Eigen::Vector3d & XYZ ()
double XYZ (const size_t idx) const
double & XYZ (const size_t idx)
double X () const
double Y () const
double Z () const
void SetXYZ (const Eigen::Vector3d &xyz)
const Eigen::Vector3ub & Color () const
Eigen::Vector3ub & Color ()
uint8_t Color (const size_t idx) const
uint8_t & Color (const size_t idx)
void SetColor (const Eigen::Vector3ub &color)
double Error () const
bool HasError () const
void SetError (const double error)
const class Track & Track () const
class Track & Track ()
void SetTrack (const class Track &track)
bool operator== (const Point3D &other) const
bool operator!= (const Point3D &other) const
Detailed Description
Definition at line 23 of file point3d.h.
Constructor & Destructor Documentation
Point3D()
Point3D< T >::Point3D ()
Definition at line 36 of file point3d.cc.
Member Function Documentation
Color() [1/4]
Eigen::Vector3ub & Point3D< T >::Color () inline
Definition at line 92 of file point3d.h.
Color() [2/4]
const Eigen::Vector3ub & Point3D< T >::Color () const inline
Definition at line 90 of file point3d.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::PointColormapPhotometric::ComputeColor(), colmap::Reconstruction::ExtractColorsForImage(), colmap::Reconstruction::MergePoints3D(), and operator==().
Color() [3/4]
uint8_t & Point3D< T >::Color (const size_t idx) inline
Definition at line 96 of file point3d.h.
Color() [4/4]
uint8_t Point3D< T >::Color (const size_t idx) const inline
Definition at line 94 of file point3d.h.
Error()
double Point3D< T >::Error () const inline
Definition at line 100 of file point3d.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::PointColormapError::ComputeColor(), and operator==().
HasError()
bool Point3D< T >::HasError () const inline
Definition at line 102 of file point3d.h.
Referenced by colmap::IncrementalMapper::AdjustLocalBundle(), and BOOST_AUTO_TEST_CASE().
operator!=()
bool Point3D< T >::operator!= (const Point3D & other) const inline
Definition at line 117 of file point3d.h.
operator==()
bool Point3D< T >::operator== (const Point3D & other) const inline
Definition at line 112 of file point3d.h.
References Color(), Error(), Track(), and XYZ().
SetColor()
void Point3D< T >::SetColor (const Eigen::Vector3ub & color) inline
Definition at line 98 of file point3d.h.
References color.
Referenced by colmap::Reconstruction::AddPoint3D(), BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::ExtractColorsForImage().
SetError()
void Point3D< T >::SetError (const double error) inline
Definition at line 104 of file point3d.h.
Referenced by BOOST_AUTO_TEST_CASE().
SetTrack()
void Point3D< T >::SetTrack (const class Track & track) inline
Definition at line 110 of file point3d.h.
Referenced by colmap::Reconstruction::AddPoint3D(), and BOOST_AUTO_TEST_CASE().
SetXYZ()
void Point3D< T >::SetXYZ (const Eigen::Vector3d & xyz) inline
Definition at line 88 of file point3d.h.
Referenced by colmap::Reconstruction::AddPoint3D(), and BOOST_AUTO_TEST_CASE().
Track() [1/2]
class Track & Point3D< T >::Track () inline
Definition at line 108 of file point3d.h.
Track() [2/2]
const class Track & Point3D< T >::Track () const inline
Definition at line 106 of file point3d.h.
Referenced by colmap::Reconstruction::AddObservation(), colmap::IncrementalMapper::AdjustLocalBundle(), BOOST_AUTO_TEST_CASE(), colmap::PointColormapTrackLen::ComputeColor(), colmap::Reconstruction::DeleteObservation(), colmap::Reconstruction::DeletePoint3D(), colmap::Reconstruction::MergePoints3D(), operator==(), colmap::BundleAdjuster::ParameterizePoints(), and colmap::RunPointFiltering().
X()
double Point3D< T >::X () const inline
Definition at line 82 of file point3d.h.
Referenced by BOOST_AUTO_TEST_CASE().
XYZ() [1/4]
Eigen::Vector3d & Point3D< T >::XYZ () inline
Definition at line 76 of file point3d.h.
XYZ() [2/4]
const Eigen::Vector3d & Point3D< T >::XYZ () const inline
Definition at line 74 of file point3d.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Reconstruction::FilterObservationsWithNegativeDepth(), colmap::Reconstruction::MergePoints3D(), operator==(), colmap::BundleAdjuster::ParameterizePoints(), and colmap::IncrementalMapper::RegisterNextImage().
XYZ() [3/4]
double & Point3D< T >::XYZ (const size_t idx) inline
Definition at line 80 of file point3d.h.
XYZ() [4/4]
double Point3D< T >::XYZ (const size_t idx) const inline
Definition at line 78 of file point3d.h.
Y()
double Point3D< T >::Y () const inline
Definition at line 84 of file point3d.h.
Referenced by BOOST_AUTO_TEST_CASE().
Z()
double Point3D< T >::Z () const inline
Definition at line 86 of file point3d.h.
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/point3d.h
/root/ACloudViewer/libs/Reconstruction/src/base/point3d.cc