ACloudViewer: ccSubMesh Class Reference
ccSubMesh Class Reference
A sub-mesh.
#include <ecvSubMesh.h>
Public Types
using IndexMap = std::vector< unsigned int >
Indexes map for createNewSubMeshFromSelection.
Public Types inherited from cloudViewer::GenericMesh
enum class SimplificationContraction { Average , Quadric }
Indicates the method that is used for mesh simplification if multiple vertices are combined to a single one.
enum class FilterScope { All , Color , Normal , Vertex }
Indicates the scope of filter operations.
enum class DeformAsRigidAsPossibleEnergy { Spokes , Smoothed }
using genericTriangleAction = std::function< void(GenericTriangle &)>
Generic function to apply to a triangle (used by foreach)
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Public Member Functions
ccSubMesh (ccMesh *parentMesh)
Default constructor.
~ccSubMesh () override=default
Destructor.
CV_CLASS_ENUM getClassID () const override
Returns class ID.
ccBBox getOwnBB (bool withGLFeatures=false) override
Returns the entity's own bounding-box.
bool isSerializable () const override
Returns whether object is serializable of not.
ccGenericPointCloud * getAssociatedCloud () const override
Returns the vertices cloud.
void refreshBB () override
Forces bounding-box update.
bool interpolateNormalsBC (unsigned triIndex, const CCVector3d &w, CCVector3 &N) override
Interpolates normal(s) inside a given triangle.
bool interpolateColors (unsigned triIndex, const CCVector3 &P, ecvColor::Rgb &rgb) override
Interpolates RGB colors inside a given triangle.
bool getColorFromMaterial (unsigned triIndex, const CCVector3 &P, ecvColor::Rgb &rgb, bool interpolateColorIfNoTexture) override
bool getVertexColorFromMaterial (unsigned triIndex, unsigned char vertIndex, ecvColor::Rgb &rgb, bool returnColorIfNoTexture) override
bool hasMaterials () const override
const ccMaterialSet * getMaterialSet () const override
int getTriangleMtlIndex (unsigned triangleIndex) const override
Returns a given triangle material indexes.
bool hasTextures () const override
Returns whether textures are available for this mesh.
TextureCoordsContainer * getTexCoordinatesTable () const override
Returns per-triangle texture coordinates array.
void getTexCoordinates (unsigned index, TexCoords2D *&tx) const override
void getTriangleTexCoordinates (unsigned triIndex, TexCoords2D *&tx1, TexCoords2D *&tx2, TexCoords2D *&tx3) const override
Returns per-triangle texture coordinates (pointer to)
bool hasPerTriangleTexCoordIndexes () const override
Returns whether this mesh as per-triangle triplets of tex coords indexes.
void getTriangleTexCoordinatesIndexes (unsigned triangleIndex, int &i1, int &i2, int &i3) const override
Returns the triplet of tex coords indexes for a given triangle.
bool hasTriNormals () const override
Returns whether the mesh has per-triangle normals.
void getTriangleNormalIndexes (unsigned triangleIndex, int &i1, int &i2, int &i3) const override
Returns a triplet of normal indexes for a given triangle (if any)
bool getTriangleNormals (unsigned triangleIndex, CCVector3 &Na, CCVector3 &Nb, CCVector3 &Nc) const override
Returns a given triangle normal.
NormsIndexesTableType * getTriNormsTable () const override
Returns per-triangle normals shared array.
unsigned capacity () const override
Returns max capacity.
bool hasColors () const override
Returns whether colors are enabled or not.
bool hasNormals () const override
Returns whether normals are enabled or not.
bool hasScalarFields () const override
Returns whether one or more scalar fields are instantiated.
bool hasDisplayedScalarField () const override
Returns whether an active scalar field is available or not.
bool normalsShown () const override
Returns whether normals are shown or not.
unsigned size () const override
Returns the number of triangles.
void forEach (genericTriangleAction action) override
Fast iteration mechanism.
void placeIteratorAtBeginning () override
Places the mesh iterator at the beginning.
cloudViewer::GenericTriangle * _getNextTriangle () override
Returns the next triangle (relatively to the global iterator position)
cloudViewer::GenericTriangle * _getTriangle (unsigned index) override
Returns the ith triangle.
cloudViewer::VerticesIndexes * getNextTriangleVertIndexes () override
cloudViewer::VerticesIndexes * getTriangleVertIndexes (unsigned triangleIndex) override
Returns the indexes of the vertices of a given triangle.
virtual void getTriangleVertices (unsigned triangleIndex, CCVector3 &A, CCVector3 &B, CCVector3 &C) const override
Returns the vertices of a given triangle.
virtual void getTriangleVertices (unsigned triangleIndex, double A[3], double B[3], double C[3]) const override
void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax) override
Returns the mesh bounding-box.
bool interpolateNormals (unsigned triIndex, const CCVector3 &P, CCVector3 &N) override
Interpolates normal(s) inside a given triangle.
unsigned getTriGlobalIndex (unsigned localIndex) const
unsigned getCurrentTriGlobalIndex () const
Returns the global index of the triangle pointed by the current element.
void forwardIterator ()
Forwards the local element iterator.
void clear (bool releaseMemory)
Clears the mesh.
bool addTriangleIndex (unsigned globalIndex)
Triangle global index insertion mechanism.
bool addTriangleIndex (unsigned firstIndex, unsigned lastIndex)
Triangle global index insertion mechanism (range)
void setTriangleIndex (unsigned localIndex, unsigned globalIndex)
Sets global index for a given element.
bool reserve (size_t n)
Reserves some memory for hosting the triangle references.
bool resize (size_t n)
Presets the size of the vector used to store triangle references.
ccMesh * getAssociatedMesh ()
Returns the associated mesh.
const ccMesh * getAssociatedMesh () const
Returns the associated mesh (const version)
void setAssociatedMesh (ccMesh *mesh, bool unlinkPreviousOne=true)
Sets the associated mesh.
ccSubMesh * createNewSubMeshFromSelection (bool removeSelectedTriangles, const std::vector< int > &selectedTriangleIndexes, IndexMap *newRemainingTriangleIndexes=nullptr)
Creates a new sub mesh with the visible vertices only.
ccSubMesh * createNewSubMeshFromSelection (bool removeSelectedFaces, IndexMap *indexMap=nullptr)
Creates a new sub mesh with the selected vertices only.
Public Member Functions inherited from ccGenericMesh
ccGenericMesh (QString name=QString())
Default constructor.
~ccGenericMesh () override=default
Destructor.
void showNormals (bool state) override
Sets normals visibility.
virtual bool getTriangleNormals (unsigned triangleIndex, double Na[3], double Nb[3], double Nc[3]) const
virtual bool getTriangleNormals (unsigned triangleIndex, Eigen::Vector3d &Na, Eigen::Vector3d &Nb, Eigen::Vector3d &Nc) const
virtual void computeInterpolationWeights (unsigned triIndex, const CCVector3 &P, CCVector3d &weights) const
Returns the (barycentric) interpolation weights for a given triangle.
virtual bool isShownAsWire () const
Returns whether the mesh is displayed as wired or with plain facets.
virtual void showWired (bool state)
Sets whether mesh should be displayed as a wire or with plain facets.
virtual bool isShownAsPoints () const
Returns whether the mesh is displayed as wired or with plain facets.
virtual void showPoints (bool state)
virtual bool triNormsShown () const
Returns whether per-triangle normals are shown or not.
virtual void showTriNorms (bool state)
Sets whether to show or not per-triangle normals.
virtual bool materialsShown () const
Sets whether textures/material should be displayed or not.
virtual void showMaterials (bool state)
Sets whether textures should be displayed or not.
virtual bool stipplingEnabled () const
Returns whether polygon stippling is enabled or not.
void enableStippling (bool state)
Enables polygon stippling.
ccPointCloud * samplePoints (bool densityBased, double samplingParameter, bool withNormals, bool withRGB, bool withTexture, cloudViewer::GenericProgressCallback *pDlg=nullptr)
Samples points on a mesh.
void importParametersFrom (const ccGenericMesh *mesh)
Imports the parameters from another mesh.
virtual bool trianglePicking (const CCVector2d &clickPos, const ccGLCameraParameters &camera, int &nearestTriIndex, double &nearestSquareDist, CCVector3d &nearestPoint, CCVector3d *barycentricCoords=nullptr) const
Brute force triangle picking.
virtual bool trianglePicking (unsigned triIndex, const CCVector2d &clickPos, const ccGLCameraParameters &camera, CCVector3d &point, CCVector3d *barycentricCoords=nullptr) const
Triangle picking (single triangle)
bool computePointPosition (unsigned triIndex, const CCVector2d &uv, CCVector3 &P, bool warningIfOutside=true) const
void setGlobalShift (const CCVector3d &shift) override
Sets shift applied to original coordinates (information storage only)
void setGlobalScale (double scale) override
const CCVector3d & getGlobalShift () const override
Returns the shift applied to original coordinates.
double getGlobalScale () const override
Returns the scale applied to original coordinates.
bool normalsAvailable () const override
Returns whether normals are available.
bool updateTextures (const std::string &texture_file)
bool updateTextures (const std::vector< std::string > &texture_files)
Public Member Functions inherited from cloudViewer::GenericIndexedMesh
GenericIndexedMesh ()=default
~GenericIndexedMesh () override=default
Default destructor.
Public Member Functions inherited from cloudViewer::GenericMesh
GenericMesh ()=default
virtual ~GenericMesh ()=default
Default destructor.
virtual bool hasTriangles () const
Public Member Functions inherited from ccShiftedObject
ccShiftedObject (QString name=QString())
Default constructor.
ccShiftedObject (const ccShiftedObject &s)
Copy constructor.
void copyGlobalShiftAndScale (const ccShiftedObject &s)
Copies the Global Shift and Scale from another entity.
virtual void setGlobalShift (double x, double y, double z)
Sets shift applied to original coordinates (information storage only)
bool isShifted () const
Returns whether the cloud is shifted or not.
template<typename T >
CCVector3d toGlobal3d (const Vector3Tpl< T > &Plocal) const
Returns the point back-projected into the original coordinates system.
template<typename T >
CCVector3d toLocal3d (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
template<typename T >
CCVector3 toLocal3pc (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner) override
GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false) override
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual bool IsEmpty () const
virtual Eigen::Vector3d GetMinBound () const
Returns min bounds for geometry coordinates.
virtual Eigen::Vector2d GetMin2DBound () const
virtual Eigen::Vector3d GetMaxBound () const
Returns max bounds for geometry coordinates.
virtual Eigen::Vector2d GetMax2DBound () const
virtual Eigen::Vector3d GetCenter () const
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const
virtual ccHObject & Transform (const Eigen::Matrix4d &transformation)
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual ccHObject & Translate (const Eigen::Vector3d &translation, bool relative=true)
Apply translation to the geometry coordinates.
virtual ccHObject & Scale (const double s, const Eigen::Vector3d &center)
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center)
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual ccBBox getOwnFitBB (ccGLMatrix &trans)
Returns best-fit bounding-box (if available)
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col)
Draws the entity (and its children) bounding-box.
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
virtual void notifyGeometryUpdate ()
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual unsigned getUniqueIDForDisplay () const
Returns object unqiue ID used for display.
virtual const ccGLMatrix & getGLTransformationHistory () const
Returns the transformation 'history' matrix.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual void getDrawingParameters (glDrawParams &params) const
Returns main OpenGL parameters for this entity.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual void toggleNormals ()
Toggles normals display state.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void toggleMaterials ()
Toggles material display state.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Protected Types
using ReferencesContainer = std::vector< unsigned int >
Container of 3D triangles indexes.
Protected Member Functions
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
void onUpdateOf (ccHObject *obj) override
This method is called when another object (geometry) is updated.
Protected Member Functions inherited from ccGenericMesh
virtual bool trianglePicking (unsigned triIndex, const CCVector2d &clickPos, const ccGLMatrix &trans, bool noGLTrans, const ccGenericPointCloud &vertices, const ccGLCameraParameters &camera, CCVector3d &point, CCVector3d *barycentricCoords=nullptr) const
Triangle picking (single triangle)
void drawMeOnly (CC_DRAW_CONTEXT &context) override
Enables (OpenGL) stipple mask.
void handleColorRamp (CC_DRAW_CONTEXT &context)
Handles the color ramp display.
Protected Member Functions inherited from ccShiftedObject
bool saveShiftInfoToFile (QFile &out) const
Serialization helper (output)
bool loadShiftInfoFromFile (QFile &in)
Serialization helper (input)
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void applyGLTransformation (const ccGLMatrix &trans)
Applies a GL transformation to the entity.
virtual void drawNameIn3D ()
Draws the entity name in 3D.
virtual void onDeletionOf (const ccHObject *obj)
This method is called when another object is deleted.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Protected Attributes
ccMesh * m_associatedMesh
Associated mesh.
ReferencesContainer m_triIndexes
Indexes of (some of) the associated mesh triangles.
unsigned m_globalIterator
Iterator on the triangles references container.
ccBBox m_bBox
Bounding-box.
Protected Attributes inherited from ccGenericMesh
bool m_triNormsShown
Per-triangle normals display flag.
bool m_materialsShown
Texture/material display flag.
bool m_showWired
Wireframe display mode.
bool m_showPoints
points display mode
bool m_stippling
Polygon stippling state.
Protected Attributes inherited from ccShiftedObject
CCVector3d m_globalShift
Global shift (typically applied at loading time)
double m_globalScale
Global scale (typically applied at loading time)
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Additional Inherited Members
Static Public Member Functions inherited from ccGenericMesh
static bool IsCloudVerticesOfMesh (ccGenericPointCloud *cloud, ccGenericMesh **mesh=nullptr)
Helper to determine if the input cloud acts as vertices of a mesh.
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Static Protected Member Functions inherited from ccGenericMesh
static CCVector3 * GetVertexBuffer ()
static CCVector3 * GetNormalsBuffer ()
static ecvColor::Rgb * GetColorsBuffer ()
static unsigned * GetWireVertexIndexes ()
Returns a pre-initialized array of vertex indexes for wired display.
Detailed Description
A sub-mesh.
Equivalent to a cloudViewer::ReferenceCloud for a mesh
Definition at line 19 of file ecvSubMesh.h.
Member Typedef Documentation
IndexMap
using ccSubMesh::IndexMap = std::vector<unsigned int>
Indexes map for createNewSubMeshFromSelection.
Definition at line 175 of file ecvSubMesh.h.
ReferencesContainer
using ccSubMesh::ReferencesContainer = std::vector<unsigned int> protected
Container of 3D triangles indexes.
Definition at line 220 of file ecvSubMesh.h.
Constructor & Destructor Documentation
ccSubMesh()
ccSubMesh::ccSubMesh (ccMesh * parentMesh) explicit
Default constructor.
Definition at line 24 of file ecvSubMesh.cpp.
References ccDrawableObject::colorsShown(), ccMesh::normalsShown(), setAssociatedMesh(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccGenericMesh::showNormals(), and ccDrawableObject::showSF().
Referenced by createNewSubMeshFromSelection().
~ccSubMesh()
ccSubMesh::~ccSubMesh () override default
Destructor.
Member Function Documentation
_getNextTriangle()
cloudViewer::GenericTriangle * ccSubMesh::_getNextTriangle () override virtual
Returns the next triangle (relatively to the global iterator position)
Virtual method to handle the mesh global iterator. Global iterator position should be increased each time this method is called. The returned object can be temporary.
Returns
a triangle
Implements cloudViewer::GenericMesh.
Definition at line 67 of file ecvSubMesh.cpp.
References ccMesh::_getTriangle(), m_associatedMesh, m_globalIterator, m_triIndexes, and size().
_getTriangle()
cloudViewer::GenericTriangle * ccSubMesh::_getTriangle (unsigned triangleIndex) override virtual
Returns the ith triangle.
Virtual method to request a triangle with a specific index. The returned object can be temporary.
Parameters
triangleIndex of the requested triangle (between 0 and the mesh size-1)
Returns
the requested triangle, or 0 if index value is not valid
Implements cloudViewer::GenericIndexedMesh.
Definition at line 146 of file ecvSubMesh.cpp.
References ccMesh::_getTriangle(), getTriGlobalIndex(), m_associatedMesh, and size().
addTriangleIndex() [1/2]
bool ccSubMesh::addTriangleIndex (unsigned firstIndex, unsigned lastIndex)
Triangle global index insertion mechanism (range)
Parameters
firstIndex first triangle global index of range
lastIndex last triangle global index of range (excluded)
Returns
false if not enough memory
Definition at line 512 of file ecvSubMesh.cpp.
References m_bBox, m_triIndexes, and cloudViewer::BoundingBoxTpl< T >::setValidity().
addTriangleIndex() [2/2]
bool ccSubMesh::addTriangleIndex (unsigned globalIndex)
Triangle global index insertion mechanism.
Parameters
globalIndex a triangle global index
Returns
false if not enough memory
Definition at line 499 of file ecvSubMesh.cpp.
References m_bBox, m_triIndexes, and cloudViewer::BoundingBoxTpl< T >::setValidity().
Referenced by createNewSubMeshFromSelection(), define_ccSubMesh(), ObjFilter::loadFile(), and ccMesh::merge().
capacity()
unsigned ccSubMesh::capacity () const override virtual
Returns max capacity.
Implements ccGenericMesh.
Definition at line 562 of file ecvSubMesh.cpp.
References m_triIndexes.
clear()
void ccSubMesh::clear (bool releaseMemory)
Clears the mesh.
Definition at line 491 of file ecvSubMesh.cpp.
References m_bBox, m_triIndexes, and cloudViewer::BoundingBoxTpl< T >::setValidity().
Referenced by define_ccSubMesh().
createNewSubMeshFromSelection() [1/2]
ccSubMesh * ccSubMesh::createNewSubMeshFromSelection (bool removeSelectedFaces, IndexMap * indexMap = nullptr)
Creates a new sub mesh with the selected vertices only.
This method is called after a graphical segmentation or by ccMesh::createNewMeshFromSelection. It creates a new sub-mesh structure with the vertices that are tagged as "visible" (see ccGenericPointCloud::visibilityArray). This method will also update this sub-mesh if removeSelectedFaces is true. In this case, all "selected" triangles will be removed from this sub-mesh's instance.
    \param removeSelectedFaces specifies if the faces composed only of
'selected' vertices should be removed or not
Parameters
indexMap if an index map is provided, it will be used to 'translate' global indexes
Definition at line 194 of file ecvSubMesh.cpp.
References addTriangleIndex(), ccSubMesh(), ccDrawableObject::colorsShown(), ccGenericMesh::enableStippling(), CVLog::Error(), getAssociatedCloud(), ccObject::getName(), ccGenericPointCloud::getTheVisibilityArray(), ccMesh::getTriangleVertIndexes(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, ccGenericMesh::isShownAsWire(), m_associatedMesh, m_bBox, m_triIndexes, ccGenericMesh::materialsShown(), normalsShown(), ccHObject::notifyGeometryUpdate(), POINT_VISIBLE, reserve(), resize(), ccObject::setName(), cloudViewer::BoundingBoxTpl< T >::setValidity(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccGenericMesh::showMaterials(), ccGenericMesh::showNormals(), ccDrawableObject::showSF(), ccGenericMesh::showWired(), cloudViewer::GenericCloud::size(), size(), and ccGenericMesh::stipplingEnabled().
createNewSubMeshFromSelection() [2/2]
ccSubMesh * ccSubMesh::createNewSubMeshFromSelection (bool removeSelectedTriangles, const std::vector< int > & selectedTriangleIndexes, IndexMap * newRemainingTriangleIndexes = nullptr)
Creates a new sub mesh with the visible vertices only.
Parameters
removeSelectedTriangles specifies if the faces composed only of 'selected' vertices should be removed or not
selectedTriangleIndexes a map of the triangles indexes that will be used in the new sub msh (or -1 if they are discarded)
newRemainingTriangleIndexes if an index map is provided, it will be used to 'translate' global indexes of triangles remaining in the source sub-mesh
Returns
the new sub-mesh if successful
Definition at line 298 of file ecvSubMesh.cpp.
References addTriangleIndex(), ccSubMesh(), ccDrawableObject::colorsShown(), ccGenericMesh::enableStippling(), CVLog::Error(), ccObject::getName(), ccMesh::getTriangleVertIndexes(), ccGenericMesh::isShownAsWire(), m_associatedMesh, m_bBox, m_triIndexes, ccGenericMesh::materialsShown(), normalsShown(), ccHObject::notifyGeometryUpdate(), reserve(), resize(), ccObject::setName(), cloudViewer::BoundingBoxTpl< T >::setValidity(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccGenericMesh::showMaterials(), ccGenericMesh::showNormals(), ccDrawableObject::showSF(), ccGenericMesh::showWired(), ccMesh::size(), size(), and ccGenericMesh::stipplingEnabled().
Referenced by ecvFilterByLabelDlg::apply(), and ccMesh::createNewMeshFromSelection().
forEach()
void ccSubMesh::forEach (genericTriangleAction action) override virtual
Fast iteration mechanism.
Virtual method to apply a function to the whole mesh
Parameters
action function to apply (see GenericMesh::genericTriangleAction)
Implements cloudViewer::GenericMesh.
Definition at line 53 of file ecvSubMesh.cpp.
References ccMesh::_getTriangle(), m_associatedMesh, and m_triIndexes.
forwardIterator()
void ccSubMesh::forwardIterator () inline
Forwards the local element iterator.
Definition at line 127 of file ecvSubMesh.h.
Referenced by define_ccSubMesh().
fromFile_MeOnly()
bool ccSubMesh::fromFile_MeOnly (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override protected virtual
Loads own object data.
Called by 'fromFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
in input file
dataVersion file version
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Reimplemented from ccGenericMesh.
Definition at line 635 of file ecvSubMesh.cpp.
getAssociatedCloud()
ccGenericPointCloud * ccSubMesh::getAssociatedCloud () const override virtual
Returns the vertices cloud.
Implements ccGenericMesh.
Definition at line 63 of file ecvSubMesh.cpp.
References ccMesh::getAssociatedCloud(), and m_associatedMesh.
Referenced by createNewSubMeshFromSelection().
getAssociatedMesh() [1/2]
ccMesh* ccSubMesh::getAssociatedMesh () inline
Returns the associated mesh.
Definition at line 162 of file ecvSubMesh.h.
Referenced by define_ccSubMesh(), and ecvDisplayTools::StartCPUBasedPointPicking().
getAssociatedMesh() [2/2]
const ccMesh* ccSubMesh::getAssociatedMesh () const inline
Returns the associated mesh (const version)
Definition at line 165 of file ecvSubMesh.h.
getBoundingBox()
void ccSubMesh::getBoundingBox (CCVector3 & bbMin, CCVector3 & bbMax) override virtual
Returns the mesh bounding-box.
Virtual method to request the mesh bounding-box limits. It is equivalent to the bounding-box of the cloud composed of the mesh vertexes.
Parameters
bbMin lower bounding-box limits (Xmin,Ymin,Zmin)
bbMax higher bounding-box limits (Xmax,Ymax,Zmax)
Implements cloudViewer::GenericMesh.
Definition at line 591 of file ecvSubMesh.cpp.
References cloudViewer::BoundingBoxTpl< T >::isValid(), m_bBox, cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), refreshBB(), and size().
getClassID()
CV_CLASS_ENUM ccSubMesh::getClassID () const inline override virtual
Returns class ID.
Reimplemented from ccHObject.
Definition at line 27 of file ecvSubMesh.h.
References CV_TYPES::SUB_MESH.
getColorFromMaterial()
bool ccSubMesh::getColorFromMaterial (unsigned triIndex, const CCVector3 & P, ecvColor::Rgb & C, bool interpolateColorIfNoTexture) override virtual
! Returns RGB color from a given triangle material/texture **
Parameters
triIndex triangle index
Implements ccGenericMesh.
Definition at line 118 of file ecvSubMesh.cpp.
References ccMesh::getColorFromMaterial(), getTriGlobalIndex(), m_associatedMesh, rgb, and size().
getCurrentTriGlobalIndex()
unsigned ccSubMesh::getCurrentTriGlobalIndex () const inline
Returns the global index of the triangle pointed by the current element.
Definition at line 121 of file ecvSubMesh.h.
References cloudViewer::GenericMesh::size().
Referenced by define_ccSubMesh().
getMaterialSet()
const ccMaterialSet * ccSubMesh::getMaterialSet () const override virtual
Implements ccGenericMesh.
Definition at line 413 of file ecvSubMesh.cpp.
References ccMesh::getMaterialSet(), and m_associatedMesh.
getNextTriangleVertIndexes()
cloudViewer::VerticesIndexes * ccSubMesh::getNextTriangleVertIndexes () override virtual
Returns the indexes of the vertices of the next triangle (relatively to the global iterator position)
Returns
the triangle indexes (or 0 if the global iterator is out of bounds)
Implements cloudViewer::GenericIndexedMesh.
Definition at line 75 of file ecvSubMesh.cpp.
References ccMesh::getTriangleVertIndexes(), m_associatedMesh, m_globalIterator, m_triIndexes, and size().
getOwnBB()
ccBBox ccSubMesh::getOwnBB (bool withGLFeatures = false) override virtual
Returns the entity's own bounding-box.
Children bboxes are ignored.
Parameters
withGLFeatures whether to take into account display-only elements (if any)
Returns
bounding-box
Reimplemented from ccHObject.
Definition at line 582 of file ecvSubMesh.cpp.
References cloudViewer::BoundingBoxTpl< T >::isValid(), m_bBox, refreshBB(), and size().
getTexCoordinates()
void ccSubMesh::getTexCoordinates (unsigned index, TexCoords2D *& tx) const override virtual
Implements ccGenericMesh.
Definition at line 428 of file ecvSubMesh.cpp.
References ccMesh::getTexCoordinates(), and m_associatedMesh.
getTexCoordinatesTable()
TextureCoordsContainer * ccSubMesh::getTexCoordinatesTable () const override virtual
Returns per-triangle texture coordinates array.
Implements ccGenericMesh.
Definition at line 423 of file ecvSubMesh.cpp.
References ccMesh::getTexCoordinatesTable(), and m_associatedMesh.
getTriangleMtlIndex()
int ccSubMesh::getTriangleMtlIndex (unsigned triangleIndex) const override virtual
Returns a given triangle material indexes.
Implements ccGenericMesh.
Definition at line 417 of file ecvSubMesh.cpp.
References ccMesh::getTriangleMtlIndex(), getTriGlobalIndex(), and m_associatedMesh.
getTriangleNormalIndexes()
void ccSubMesh::getTriangleNormalIndexes (unsigned triangleIndex, int & i1, int & i2, int & i3) const override virtual
Returns a triplet of normal indexes for a given triangle (if any)
Parameters
[in] triangleIndex triangle index
[out] i1 first vertex normal index (or -1 if none)
[out] i2 second vertex normal index (or -1 if none)
[out] i3 third vertex normal index (or -1 if none)
Implements ccGenericMesh.
Definition at line 465 of file ecvSubMesh.cpp.
References ccMesh::getTriangleNormalIndexes(), getTriGlobalIndex(), m_associatedMesh, and size().
getTriangleNormals()
bool ccSubMesh::getTriangleNormals (unsigned triangleIndex, CCVector3 & Na, CCVector3 & Nb, CCVector3 & Nc) const override virtual
Returns a given triangle normal.
Mesh must have triangle normals associated (see hasTriNormals)
Implements ccGenericMesh.
Definition at line 477 of file ecvSubMesh.cpp.
References ccMesh::getTriangleNormals(), getTriGlobalIndex(), m_associatedMesh, and size().
getTriangleTexCoordinates()
void ccSubMesh::getTriangleTexCoordinates (unsigned triIndex, TexCoords2D *& tx1, TexCoords2D *& tx2, TexCoords2D *& tx3) const override virtual
Returns per-triangle texture coordinates (pointer to)
Implements ccGenericMesh.
Definition at line 434 of file ecvSubMesh.cpp.
References ccMesh::getTriangleTexCoordinates(), getTriGlobalIndex(), m_associatedMesh, and size().
getTriangleTexCoordinatesIndexes()
void ccSubMesh::getTriangleTexCoordinatesIndexes (unsigned triangleIndex, int & i1, int & i2, int & i3) const override virtual
Returns the triplet of tex coords indexes for a given triangle.
Parameters
triangleIndex triangle index
i1 first vertex tex coords index
i2 second vertex tex coords index
i3 third vertex tex coords index
Implements ccGenericMesh.
Definition at line 453 of file ecvSubMesh.cpp.
References ccMesh::getTriangleTexCoordinatesIndexes(), getTriGlobalIndex(), m_associatedMesh, and size().
getTriangleVertices() [1/2]
void ccSubMesh::getTriangleVertices (unsigned triangleIndex, CCVector3 & A, CCVector3 & B, CCVector3 & C) const override virtual
Returns the vertices of a given triangle.
Parameters
[in] triangleIndex index of the triangle (between 0 and the size(mesh)-1)
[out] A first vertex
[out] B second vertex
[out] C third vertex
Implements cloudViewer::GenericIndexedMesh.
Definition at line 157 of file ecvSubMesh.cpp.
References ccMesh::getTriangleVertices(), getTriGlobalIndex(), m_associatedMesh, and size().
getTriangleVertices() [2/2]
void ccSubMesh::getTriangleVertices (unsigned triangleIndex, double A[3], double B[3], double C[3]) const override virtual
Implements cloudViewer::GenericIndexedMesh.
Definition at line 170 of file ecvSubMesh.cpp.
References ccMesh::getTriangleVertices(), getTriGlobalIndex(), m_associatedMesh, and size().
getTriangleVertIndexes()
cloudViewer::VerticesIndexes * ccSubMesh::getTriangleVertIndexes (unsigned triangleIndex) override virtual
Returns the indexes of the vertices of a given triangle.
Parameters
triangleIndex index of the triangle (between 0 and size(mesh)-1)
Returns
the triangle indexes (or 0 if index value is not valid)
Implements cloudViewer::GenericIndexedMesh.
Definition at line 183 of file ecvSubMesh.cpp.
References ccMesh::getTriangleVertIndexes(), getTriGlobalIndex(), m_associatedMesh, and size().
getTriGlobalIndex()
unsigned ccSubMesh::getTriGlobalIndex (unsigned localIndex) const inline
Returns global index (i.e. relative to the associated mesh) of a given element
Parameters
localIndex local index (i.e. relative to the internal index container)
Definition at line 116 of file ecvSubMesh.h.
Referenced by _getTriangle(), define_ccSubMesh(), getColorFromMaterial(), getTriangleMtlIndex(), getTriangleNormalIndexes(), getTriangleNormals(), getTriangleTexCoordinates(), getTriangleTexCoordinatesIndexes(), getTriangleVertices(), getTriangleVertIndexes(), getVertexColorFromMaterial(), interpolateColors(), interpolateNormals(), and interpolateNormalsBC().
getTriNormsTable()
NormsIndexesTableType * ccSubMesh::getTriNormsTable () const override virtual
Returns per-triangle normals shared array.
Implements ccGenericMesh.
Definition at line 487 of file ecvSubMesh.cpp.
References ccMesh::getTriNormsTable(), and m_associatedMesh.
getVertexColorFromMaterial()
bool ccSubMesh::getVertexColorFromMaterial (unsigned triIndex, unsigned char vertIndex, ecvColor::Rgb & C, bool returnColorIfNoTexture) override virtual
! Returns RGB color of a vertex from a given triangle material/texture **
Parameters
triIndex triangle index
Implements ccGenericMesh.
Definition at line 132 of file ecvSubMesh.cpp.
References getTriGlobalIndex(), ccMesh::getVertexColorFromMaterial(), m_associatedMesh, rgb, and size().
hasColors()
bool ccSubMesh::hasColors () const override virtual
Returns whether colors are enabled or not.
Reimplemented from ccDrawableObject.
Definition at line 405 of file ecvSubMesh.cpp.
hasDisplayedScalarField()
bool ccSubMesh::hasDisplayedScalarField () const override virtual
Returns whether an active scalar field is available or not.
Reimplemented from ccDrawableObject.
Definition at line 408 of file ecvSubMesh.cpp.
hasMaterials()
bool ccSubMesh::hasMaterials () const override virtual
Implements ccGenericMesh.
Definition at line 409 of file ecvSubMesh.cpp.
hasNormals()
bool ccSubMesh::hasNormals () const override virtual
Returns whether normals are enabled or not.
Reimplemented from ccDrawableObject.
Definition at line 406 of file ecvSubMesh.cpp.
hasPerTriangleTexCoordIndexes()
bool ccSubMesh::hasPerTriangleTexCoordIndexes () const override virtual
Returns whether this mesh as per-triangle triplets of tex coords indexes.
Implements ccGenericMesh.
Definition at line 448 of file ecvSubMesh.cpp.
References ccMesh::hasPerTriangleTexCoordIndexes(), and m_associatedMesh.
hasScalarFields()
bool ccSubMesh::hasScalarFields () const override virtual
Returns whether one or more scalar fields are instantiated.
WARNING: doesn't mean a scalar field is currently displayed (see ccDrawableObject::hasDisplayedScalarField).
Reimplemented from ccDrawableObject.
Definition at line 407 of file ecvSubMesh.cpp.
hasTextures()
bool ccSubMesh::hasTextures () const override virtual
Returns whether textures are available for this mesh.
Implements ccGenericMesh.
Definition at line 410 of file ecvSubMesh.cpp.
hasTriNormals()
bool ccSubMesh::hasTriNormals () const override virtual
Returns whether the mesh has per-triangle normals.
Implements ccGenericMesh.
Definition at line 411 of file ecvSubMesh.cpp.
interpolateColors()
bool ccSubMesh::interpolateColors (unsigned triIndex, const CCVector3 & P, ecvColor::Rgb & C) override virtual
Interpolates RGB colors inside a given triangle.
Parameters
triIndex triangle index
P point where to interpolate (should be inside the triangle!)
[out] C interpolated color
Returns
success
Implements ccGenericMesh.
Definition at line 106 of file ecvSubMesh.cpp.
References getTriGlobalIndex(), ccMesh::interpolateColors(), m_associatedMesh, rgb, and size().
interpolateNormals()
bool ccSubMesh::interpolateNormals (unsigned triIndex, const CCVector3 & P, CCVector3 & N) override virtual
Interpolates normal(s) inside a given triangle.
This method should be ideally overriden by the child class if normals are supported
Parameters
[in] triIndex triangle index
[in] P point where to interpolate (should be inside the triangle!)
[out] N interpolated normal
Returns
success
Reimplemented from cloudViewer::GenericIndexedMesh.
Definition at line 82 of file ecvSubMesh.cpp.
References getTriGlobalIndex(), ccMesh::interpolateNormals(), m_associatedMesh, and size().
interpolateNormalsBC()
bool ccSubMesh::interpolateNormalsBC (unsigned triIndex, const CCVector3d & w, CCVector3 & N) override virtual
Interpolates normal(s) inside a given triangle.
Parameters
triIndex triangle index
w barycentric coordinates
[out] N interpolated normal
Returns
success
Implements ccGenericMesh.
Definition at line 94 of file ecvSubMesh.cpp.
References getTriGlobalIndex(), ccMesh::interpolateNormalsBC(), m_associatedMesh, and size().
isSerializable()
bool ccSubMesh::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccGenericMesh.
Definition at line 31 of file ecvSubMesh.h.
minimumFileVersion_MeOnly()
short ccSubMesh::minimumFileVersion_MeOnly () const override protected virtual
Returns the minimum file version required to save this instance's own data To be overloaded (but still called ;) by subclass. Used internally by minimumFileVersion() to compute the overall minimum.
Reimplemented from ccGenericMesh.
Definition at line 628 of file ecvSubMesh.cpp.
References ccSerializationHelper::GenericArrayToFileMinVersion(), and ccGenericMesh::minimumFileVersion_MeOnly().
normalsShown()
bool ccSubMesh::normalsShown () const override virtual
Returns whether normals are shown or not.
Reimplemented from ccDrawableObject.
Definition at line 396 of file ecvSubMesh.cpp.
References ccDrawableObject::normalsShown(), and ccGenericMesh::triNormsShown().
Referenced by createNewSubMeshFromSelection().
onUpdateOf()
void ccSubMesh::onUpdateOf (ccHObject * obj) override protected virtual
This method is called when another object (geometry) is updated.
For internal use.
Reimplemented from ccHObject.
Definition at line 49 of file ecvSubMesh.cpp.
References m_associatedMesh, m_bBox, and cloudViewer::BoundingBoxTpl< T >::setValidity().
placeIteratorAtBeginning()
void ccSubMesh::placeIteratorAtBeginning () inline override virtual
Places the mesh iterator at the beginning.
Virtual method to handle the mesh global iterator
Implements cloudViewer::GenericMesh.
Definition at line 89 of file ecvSubMesh.h.
refreshBB()
void ccSubMesh::refreshBB () override virtual
Forces bounding-box update.
Implements ccGenericMesh.
Definition at line 566 of file ecvSubMesh.cpp.
References cloudViewer::GenericTriangle::_getA(), cloudViewer::GenericTriangle::_getB(), cloudViewer::GenericTriangle::_getC(), ccMesh::_getTriangle(), cloudViewer::BoundingBoxTpl< T >::add(), cloudViewer::BoundingBoxTpl< T >::clear(), m_associatedMesh, m_bBox, m_triIndexes, and ccHObject::notifyGeometryUpdate().
Referenced by getBoundingBox(), and getOwnBB().
reserve()
bool ccSubMesh::reserve (size_t n)
Reserves some memory for hosting the triangle references.
Parameters
n the number of triangles (references)
Definition at line 542 of file ecvSubMesh.cpp.
References m_triIndexes.
Referenced by createNewSubMeshFromSelection(), define_ccSubMesh(), ObjFilter::loadFile(), and ccMesh::merge().
resize()
bool ccSubMesh::resize (size_t n)
Presets the size of the vector used to store triangle references.
Parameters
n the number of triangles (references)
Definition at line 552 of file ecvSubMesh.cpp.
References m_triIndexes.
Referenced by createNewSubMeshFromSelection(), and define_ccSubMesh().
setAssociatedMesh()
void ccSubMesh::setAssociatedMesh (ccMesh * mesh, bool unlinkPreviousOne = true)
Sets the associated mesh.
Parameters
mesh parent mesh
unlinkPreviousOne whether to remove any dependency with the previous parent mesh (if any)
Definition at line 36 of file ecvSubMesh.cpp.
References ccHObject::addDependency(), ccHObject::DP_NOTIFY_OTHER_ON_UPDATE, m_associatedMesh, and ccHObject::removeDependencyWith().
Referenced by ccSubMesh(), ccMesh::createNewMeshFromSelection(), and define_ccSubMesh().
setTriangleIndex()
void ccSubMesh::setTriangleIndex (unsigned localIndex, unsigned globalIndex)
Sets global index for a given element.
Parameters
localIndex local index
globalIndex global index
Definition at line 536 of file ecvSubMesh.cpp.
References m_bBox, m_triIndexes, cloudViewer::BoundingBoxTpl< T >::setValidity(), and size().
Referenced by define_ccSubMesh().
size()
unsigned ccSubMesh::size () const inline override virtual
Returns the number of triangles.
Virtual method to request the mesh size
Returns
the mesh size
Implements cloudViewer::GenericMesh.
Definition at line 85 of file ecvSubMesh.h.
Referenced by _getNextTriangle(), _getTriangle(), ccMesh::createNewMeshFromSelection(), createNewSubMeshFromSelection(), getBoundingBox(), getColorFromMaterial(), getNextTriangleVertIndexes(), getOwnBB(), getTriangleNormalIndexes(), getTriangleNormals(), getTriangleTexCoordinates(), getTriangleTexCoordinatesIndexes(), getTriangleVertices(), getTriangleVertIndexes(), getVertexColorFromMaterial(), interpolateColors(), interpolateNormals(), interpolateNormalsBC(), ObjFilter::saveToFile(), and setTriangleIndex().
toFile_MeOnly()
bool ccSubMesh::toFile_MeOnly (QFile & out, short dataVersion) const override protected virtual
Save own object data.
Called by 'toFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
out output file
dataVersion target file version for compatibility control
Reimplemented from ccGenericMesh.
Definition at line 601 of file ecvSubMesh.cpp.
Member Data Documentation
m_associatedMesh
ccMesh* ccSubMesh::m_associatedMesh protected
Associated mesh.
Definition at line 217 of file ecvSubMesh.h.
Referenced by _getNextTriangle(), _getTriangle(), createNewSubMeshFromSelection(), forEach(), getAssociatedCloud(), getColorFromMaterial(), getMaterialSet(), getNextTriangleVertIndexes(), getTexCoordinates(), getTexCoordinatesTable(), getTriangleMtlIndex(), getTriangleNormalIndexes(), getTriangleNormals(), getTriangleTexCoordinates(), getTriangleTexCoordinatesIndexes(), getTriangleVertices(), getTriangleVertIndexes(), getTriNormsTable(), getVertexColorFromMaterial(), hasPerTriangleTexCoordIndexes(), interpolateColors(), interpolateNormals(), interpolateNormalsBC(), onUpdateOf(), refreshBB(), and setAssociatedMesh().
m_bBox
ccBBox ccSubMesh::m_bBox protected
Bounding-box.
Definition at line 229 of file ecvSubMesh.h.
Referenced by addTriangleIndex(), clear(), createNewSubMeshFromSelection(), getBoundingBox(), getOwnBB(), onUpdateOf(), refreshBB(), and setTriangleIndex().
m_globalIterator
unsigned ccSubMesh::m_globalIterator protected
Iterator on the triangles references container.
Definition at line 226 of file ecvSubMesh.h.
Referenced by _getNextTriangle(), and getNextTriangleVertIndexes().
m_triIndexes
ReferencesContainer ccSubMesh::m_triIndexes protected
Indexes of (some of) the associated mesh triangles.
Definition at line 223 of file ecvSubMesh.h.
Referenced by _getNextTriangle(), addTriangleIndex(), capacity(), clear(), createNewSubMeshFromSelection(), forEach(), getNextTriangleVertIndexes(), refreshBB(), reserve(), resize(), and setTriangleIndex().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/ecvSubMesh.h
/root/ACloudViewer/libs/CV_db/src/ecvSubMesh.cpp