ACloudViewer: flann::Matrix< T > Class Template Reference
flann::Matrix< T > Class Template Reference
#include <matrix.h>
Public Types
typedef T type
Public Member Functions
Matrix ()
Matrix (T *data_, size_t rows_, size_t cols_, size_t stride_=0)
T * operator[] (size_t index) const
T * ptr () const
Public Member Functions inherited from flann::Matrix_
Matrix_ ()
Matrix_ (void *data_, size_t rows_, size_t cols_, flann_datatype_t type_, size_t stride_=0)
void * operator[] (size_t index) const
void * ptr () const
Additional Inherited Members
Public Attributes inherited from flann::Matrix_
size_t rows
size_t cols
size_t stride
flann_datatype_t type
Protected Member Functions inherited from flann::Matrix_
template<typename Archive >
void serialize (Archive &ar)
Protected Attributes inherited from flann::Matrix_
uchar * data
Detailed Description
template<typename T>
class flann::Matrix< T >
Class that implements a simple rectangular matrix stored in a memory buffer and provides convenient matrix-like access using the [] operators.
This class has the same memory structure as the un-templated class flann::Matrix_ and it's directly convertible from it.
Definition at line 103 of file matrix.h.
Member Typedef Documentation
type
template<typename T > typedef T flann::Matrix< T >::type
Definition at line 106 of file matrix.h.
Constructor & Destructor Documentation
Matrix() [1/2]
template<typename T > flann::Matrix< T >::Matrix () inline
Definition at line 108 of file matrix.h.
Matrix() [2/2]
template<typename T > flann::Matrix< T >::Matrix (T * data_, size_t rows_, size_t cols_, size_t stride_ = 0) inline
Definition at line 112 of file matrix.h.
References flann::Matrix_::cols, and flann::Matrix_::stride.
Member Function Documentation
operator[]()
template<typename T > T* flann::Matrix< T >::operator[] (size_t index) const inline
Operator that returns a (pointer to a) row of the data.
Definition at line 121 of file matrix.h.
References flann::Matrix_::data, and flann::Matrix_::stride.
ptr()
template<typename T > T* flann::Matrix< T >::ptr () const inline
Definition at line 127 of file matrix.h.
References flann::Matrix_::data.
Referenced by flann::KDTreeCuda3dIndex< Distance >::buildIndex(), flann::mpi::Index< Distance >::knnSearch(), flann::NNIndex< Distance >::knnSearch(), flann::KDTreeCuda3dIndex< Distance >::knnSearchGpu(), flann::mpi::ResultsMerger< DistanceType >::operator()(), flann::mpi::Index< Distance >::radiusSearch(), flann::NNIndex< Distance >::radiusSearch(), flann::save_to_file(), flann::mpi::SearchResults< DistanceType >::serialize(), boost::serialization::serialize(), and flann::KDTreeCuda3dIndex< Distance >::~KDTreeCuda3dIndex().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/util/matrix.h