ACloudViewer: pba::avec< Float > Class Template Reference
pba::avec< Float > Class Template Reference
#include <SparseBundleCPU.h>
Public Member Functions
avec ()
avec (size_t count)
~avec ()
void resize (size_t newcount)
void set (Float *data, size_t count)
void swap (avec< Float > &next)
operator Float * ()
operator Float *const () const
Float * begin ()
Float * data ()
Float * end ()
const Float * begin () const
const Float * end () const
size_t size () const
size_t IsValid () const
void SaveToFile (const char *name)
Static Public Member Functions
static Float * allocate (size_t count)
static void deallocate (void *p)
Detailed Description
template<class Float>
class pba::avec< Float >
Definition at line 36 of file SparseBundleCPU.h.
Constructor & Destructor Documentation
avec() [1/2]
template<class Float > pba::avec< Float >::avec () inline
Definition at line 71 of file SparseBundleCPU.h.
References NULL.
avec() [2/2]
template<class Float > pba::avec< Float >::avec (size_t count) inline
Definition at line 76 of file SparseBundleCPU.h.
References pba::avec< Float >::allocate(), and count.
~avec()
template<class Float > pba::avec< Float >::~avec () inline
Definition at line 82 of file SparseBundleCPU.h.
References pba::avec< Float >::deallocate().
Member Function Documentation
allocate()
template<class Float > static Float* pba::avec< Float >::allocate (size_t count) inline static
Definition at line 44 of file SparseBundleCPU.h.
References ALIGN_PTR, count, NULL, pba::avec< Float >::size(), and VECTOR_ALIGNMENT.
Referenced by pba::avec< Float >::avec(), and pba::avec< Float >::resize().
begin() [1/2]
template<class Float > Float* pba::avec< Float >::begin () inline
Definition at line 133 of file SparseBundleCPU.h.
References NULL.
Referenced by pba::SparseBundleCPU< Float >::ApplyBlockPC(), pba::ProgramCPU::ComputeDiagonal(), pba::ProgramCPU::ComputeDiagonalBlock_(), pba::SparseBundleCPU< Float >::ComputeJtE(), pba::SparseBundleCPU< Float >::ComputeJX(), pba::ProgramCPU::ComputeRSQRT(), pba::ProgramCPU::ComputeSAX(), pba::ProgramCPU::ComputeSQRT(), pba::ProgramCPU::ComputeSXYPZ(), pba::ProgramCPU::ComputeVectorMax(), pba::ProgramCPU::ComputeVXY(), pba::SparseBundleCPU< Float >::EvaluateProjection(), pba::SparseBundleCPU< Float >::EvaluateProjectionX(), pba::ProgramCPU::SetVectorZero(), and pba::ProgramCPU::UpdateCameraPoint().
begin() [2/2]
template<class Float > const Float* pba::avec< Float >::begin () const inline
Definition at line 136 of file SparseBundleCPU.h.
References NULL.
data()
template<class Float > Float* pba::avec< Float >::data () inline
Definition at line 134 of file SparseBundleCPU.h.
References NULL.
Referenced by pba::avec< Float >::set(), and pba::SparseBundleCPU< Float >::SolveNormalEquationPCGX().
deallocate()
template<class Float > static void pba::avec< Float >::deallocate (void * p) inline static
Definition at line 61 of file SparseBundleCPU.h.
Referenced by pba::avec< Float >::resize(), pba::avec< Float >::set(), and pba::avec< Float >::~avec().
end() [1/2]
template<class Float > Float* pba::avec< Float >::end () inline
Definition at line 135 of file SparseBundleCPU.h.
Referenced by pba::ProgramCPU::ComputeDiagonal(), pba::ProgramCPU::ComputeRSQRT(), pba::ProgramCPU::ComputeSAX(), pba::ProgramCPU::ComputeSQRT(), pba::ProgramCPU::ComputeVectorMax(), pba::ProgramCPU::ComputeVXY(), and pba::ProgramCPU::SetVectorZero().
end() [2/2]
template<class Float > const Float* pba::avec< Float >::end () const inline
Definition at line 137 of file SparseBundleCPU.h.
IsValid()
template<class Float > size_t pba::avec< Float >::IsValid () const inline
Definition at line 139 of file SparseBundleCPU.h.
operator Float *()
template<class Float > pba::avec< Float >::operator Float * () inline
Definition at line 131 of file SparseBundleCPU.h.
References NULL.
operator Float *const()
template<class Float > pba::avec< Float >::operator Float *const () const inline
Definition at line 132 of file SparseBundleCPU.h.
resize()
template<class Float > void pba::avec< Float >::resize (size_t newcount) inline
Definition at line 86 of file SparseBundleCPU.h.
References pba::avec< Float >::allocate(), pba::avec< Float >::deallocate(), and NULL.
SaveToFile()
template<class Float > void pba::avec< Float >::SaveToFile (const char * name)
Definition at line 98 of file SparseBundleCPU.cpp.
set()
template<class Float > void pba::avec< Float >::set (Float * data, size_t count) inline
Definition at line 103 of file SparseBundleCPU.h.
References count, pba::avec< Float >::data(), and pba::avec< Float >::deallocate().
Referenced by pba::SparseBundleCPU< Float >::EvaluateDeltaNorm(), pba::SparseBundleCPU< Float >::SaveUpdatedSystem(), pba::SparseBundleCPU< Float >::SolveNormalEquationPCGX(), and pba::ProgramCPU::UpdateCameraPoint().
size()
template<class Float > size_t pba::avec< Float >::size () const inline
Definition at line 138 of file SparseBundleCPU.h.
Referenced by pba::avec< Float >::allocate(), pba::ProgramCPU::ComputeDiagonal(), pba::ProgramCPU::ComputeDiagonalBlock_(), and pba::SparseBundleCPU< Float >::NonlinearOptimizeLM().
swap()
template<class Float > void pba::avec< Float >::swap (avec< Float > & next) inline
Definition at line 111 of file SparseBundleCPU.h.
References next.
Referenced by pba::SparseBundleCPU< Float >::PrepareJacobianNormalization().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/PBA/SparseBundleCPU.h
/root/ACloudViewer/libs/Reconstruction/lib/PBA/SparseBundleCPU.cpp