ACloudViewer: colmap::MatchesTab Class Reference
colmap::MatchesTab Class Reference
#include <database_management_widget.h>
Public Member Functions
MatchesTab (QWidget *parent, OptionManager *options, Database *database)
void Reload (const std::vector< Image > &images, const image_t image_id)
Public Member Functions inherited from colmap::TwoViewInfoTab
TwoViewInfoTab ()
TwoViewInfoTab (QWidget *parent, OptionManager *options, Database *database)
void Clear ()
Additional Inherited Members
Protected Member Functions inherited from colmap::TwoViewInfoTab
void InitializeTable (const QStringList &table_header)
void ShowMatches ()
void FillTable ()
Protected Attributes inherited from colmap::TwoViewInfoTab
OptionManager * options_
Database * database_
const Image * image_
std::vector< std::pair< const Image *, FeatureMatches > > matches_
std::vector< int > configs_
std::vector< size_t > sorted_matches_idxs_
QTableWidget * table_widget_
QLabel * info_label_
FeatureImageViewerWidget * matches_viewer_widget_
Detailed Description
Definition at line 50 of file database_management_widget.h.
Constructor & Destructor Documentation
MatchesTab()
colmap::MatchesTab::MatchesTab (QWidget * parent, OptionManager * options, Database * database)
Definition at line 147 of file database_management_widget.cc.
References colmap::TwoViewInfoTab::InitializeTable().
Member Function Documentation
Reload()
void colmap::MatchesTab::Reload (const std::vector< Image > & images, const image_t image_id)
Definition at line 141 of file DatabaseManagementWidget.cpp.
References cloudViewer::TwoViewInfoTab::database_, colmap::Database::ExistsMatches(), cloudViewer::TwoViewInfoTab::FillTable(), image, cloudViewer::TwoViewInfoTab::image_, cloudViewer::TwoViewInfoTab::matches_, and colmap::Database::ReadMatches().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/database_management_widget.h
/root/ACloudViewer/app/reconstruction/DatabaseManagementWidget.cpp
/root/ACloudViewer/libs/Reconstruction/src/ui/database_management_widget.cc