ACloudViewer: flann::NNIndex< Distance > Class Template Reference
flann::NNIndex< Distance > Class Template Reference abstract
#include <nn_index.h>
Public Types
typedef Distance::ElementType ElementType
typedef Distance::ResultType DistanceType
Public Member Functions
NNIndex (Distance d)
NNIndex (const IndexParams &params, Distance d)
NNIndex (const NNIndex &other)
virtual ~NNIndex ()
virtual NNIndex * clone () const =0
virtual void buildIndex ()
virtual void buildIndex (const Matrix< ElementType > &dataset)
virtual void addPoints (const Matrix< ElementType > &points, float rebuild_threshold=2)
Incrementally add points to the index.
virtual void removePoint (size_t id)
virtual ElementType * getPoint (size_t id)
size_t size () const
size_t veclen () const
IndexParams getParameters () const
template<typename Archive >
void serialize (Archive &ar)
virtual int knnSearch (const Matrix< ElementType > &queries, Matrix< size_t > &indices, Matrix< DistanceType > &dists, size_t knn, const SearchParams &params) const
Perform k-nearest neighbor search.
int knnSearch (const Matrix< ElementType > &queries, Matrix< int > &indices, Matrix< DistanceType > &dists, size_t knn, const SearchParams &params) const
int knnSearch (const Matrix< ElementType > &queries, std::vector< std::vector< size_t > > &indices, std::vector< std::vector< DistanceType > > &dists, size_t knn, const SearchParams &params) const
Perform k-nearest neighbor search.
int knnSearch (const Matrix< ElementType > &queries, std::vector< std::vector< int > > &indices, std::vector< std::vector< DistanceType > > &dists, size_t knn, const SearchParams &params) const
int radiusSearch (const Matrix< ElementType > &queries, Matrix< size_t > &indices, Matrix< DistanceType > &dists, float radius, const SearchParams &params) const
Perform radius search.
int radiusSearch (const Matrix< ElementType > &queries, Matrix< int > &indices, Matrix< DistanceType > &dists, float radius, const SearchParams &params) const
int radiusSearch (const Matrix< ElementType > &queries, std::vector< std::vector< size_t > > &indices, std::vector< std::vector< DistanceType > > &dists, float radius, const SearchParams &params) const
Perform radius search.
int radiusSearch (const Matrix< ElementType > &queries, std::vector< std::vector< int > > &indices, std::vector< std::vector< DistanceType > > &dists, float radius, const SearchParams &params) const
virtual void findNeighbors (ResultSet< DistanceType > &result, const ElementType *vec, const SearchParams &searchParams) const =0
Public Member Functions inherited from flann::IndexBase
virtual ~IndexBase ()
virtual flann_algorithm_t getType () const =0
virtual int usedMemory () const =0
virtual void loadIndex (FILE *stream)=0
virtual void saveIndex (FILE *stream)=0
Protected Member Functions
virtual void freeIndex ()=0
virtual void buildIndexImpl ()=0
size_t id_to_index (size_t id)
void indices_to_ids (const size_t *in, size_t *out, size_t size) const
void setDataset (const Matrix< ElementType > &dataset)
void extendDataset (const Matrix< ElementType > &new_points)
void cleanRemovedPoints ()
void swap (NNIndex &other)
Protected Attributes
Distance distance_
size_t last_id_
size_t size_
size_t size_at_build_
size_t veclen_
IndexParams index_params_
bool removed_
DynamicBitset removed_points_
size_t removed_count_
std::vector< size_t > ids_
std::vector< ElementType * > points_
ElementType * data_ptr_
Detailed Description
template<typename Distance>
class flann::NNIndex< Distance >
Nearest-neighbour index base class
Definition at line 73 of file nn_index.h.
Member Typedef Documentation
DistanceType
template<typename Distance > typedef Distance::ResultType flann::NNIndex< Distance >::DistanceType
Definition at line 77 of file nn_index.h.
ElementType
template<typename Distance > typedef Distance::ElementType flann::NNIndex< Distance >::ElementType
Definition at line 76 of file nn_index.h.
Constructor & Destructor Documentation
NNIndex() [1/3]
template<typename Distance > flann::NNIndex< Distance >::NNIndex (Distance d) inline
Definition at line 79 of file nn_index.h.
NNIndex() [2/3]
template<typename Distance > flann::NNIndex< Distance >::NNIndex (const IndexParams & params, Distance d) inline
Definition at line 84 of file nn_index.h.
NNIndex() [3/3]
template<typename Distance > flann::NNIndex< Distance >::NNIndex (const NNIndex< Distance > & other) inline
Definition at line 89 of file nn_index.h.
References copy, flann::NNIndex< Distance >::data_ptr_, flann::NNIndex< Distance >::points_, flann::NNIndex< Distance >::size_, and flann::NNIndex< Distance >::veclen_.
~NNIndex()
template<typename Distance > virtual flann::NNIndex< Distance >::~NNIndex () inline virtual
Definition at line 112 of file nn_index.h.
References flann::NNIndex< Distance >::data_ptr_.
Member Function Documentation
addPoints()
template<typename Distance > virtual void flann::NNIndex< Distance >::addPoints (const Matrix< ElementType > & points, float rebuild_threshold = 2) inline virtual
Incrementally add points to the index.
Parameters
points Matrix with points to be added
rebuild_threshold
Reimplemented in flann::LshIndex< Distance >, flann::LinearIndex< Distance >, flann::KMeansIndex< Distance >, flann::KDTreeSingleIndex< Distance >, flann::KDTreeIndex< Distance >, flann::HierarchicalClusteringIndex< Distance >, flann::CompositeIndex< Distance >, and flann::AutotunedIndex< Distance >.
Definition at line 152 of file nn_index.h.
Referenced by flann::Index< Distance >::addPoints().
buildIndex() [1/2]
template<typename Distance > virtual void flann::NNIndex< Distance >::buildIndex () inline virtual
Builds the index
Reimplemented in flann::LshIndex< Distance >, flann::KMeansIndex< Distance >, flann::KDTreeSingleIndex< Distance >, flann::KDTreeIndex< Distance >, flann::HierarchicalClusteringIndex< Distance >, flann::LshIndex< Distance >, flann::KMeansIndex< Distance >, flann::KDTreeSingleIndex< Distance >, flann::KDTreeIndex< Distance >, flann::KDTreeCuda3dIndex< Distance >, flann::HierarchicalClusteringIndex< Distance >, flann::CompositeIndex< Distance >, and flann::AutotunedIndex< Distance >.
Definition at line 125 of file nn_index.h.
References flann::NNIndex< Distance >::buildIndexImpl(), flann::NNIndex< Distance >::cleanRemovedPoints(), flann::NNIndex< Distance >::freeIndex(), flann::NNIndex< Distance >::size_, and flann::NNIndex< Distance >::size_at_build_.
Referenced by flann::Index< Distance >::buildIndex(), and flann::NNIndex< Distance >::buildIndex().
buildIndex() [2/2]
template<typename Distance > virtual void flann::NNIndex< Distance >::buildIndex (const Matrix< ElementType > & dataset) inline virtual
Builds the index using the specified dataset
Parameters
dataset the dataset to use
Reimplemented in flann::AutotunedIndex< Distance >.
Definition at line 141 of file nn_index.h.
References flann::NNIndex< Distance >::buildIndex(), and flann::NNIndex< Distance >::setDataset().
buildIndexImpl()
template<typename Distance > virtual void flann::NNIndex< Distance >::buildIndexImpl () protected pure virtual
Implemented in flann::LshIndex< Distance >, flann::LinearIndex< Distance >, flann::KMeansIndex< Distance >, flann::KDTreeSingleIndex< Distance >, flann::KDTreeIndex< Distance >, flann::KDTreeCuda3dIndex< Distance >, flann::HierarchicalClusteringIndex< Distance >, flann::CompositeIndex< Distance >, and flann::AutotunedIndex< Distance >.
Referenced by flann::NNIndex< Distance >::buildIndex().
cleanRemovedPoints()
template<typename Distance > void flann::NNIndex< Distance >::cleanRemovedPoints () inline protected
Definition at line 782 of file nn_index.h.
References flann::NNIndex< Distance >::ids_, flann::NNIndex< Distance >::points_, flann::NNIndex< Distance >::removed_, flann::NNIndex< Distance >::removed_count_, flann::NNIndex< Distance >::removed_points_, flann::DynamicBitset::reset(), flann::DynamicBitset::resize(), flann::NNIndex< Distance >::size_, and flann::DynamicBitset::test().
Referenced by flann::NNIndex< Distance >::buildIndex().
clone()
template<typename Distance > virtual NNIndex* flann::NNIndex< Distance >::clone () const pure virtual
Implemented in flann::LshIndex< Distance >, flann::LinearIndex< Distance >, flann::KMeansIndex< Distance >, flann::KDTreeSingleIndex< Distance >, flann::KDTreeIndex< Distance >, flann::KDTreeCuda3dIndex< Distance >, flann::HierarchicalClusteringIndex< Distance >, flann::CompositeIndex< Distance >, and flann::AutotunedIndex< Distance >.
Referenced by flann::Index< Distance >::Index().
extendDataset()
template<typename Distance > void flann::NNIndex< Distance >::extendDataset (const Matrix< ElementType > & new_points) inline protected
Definition at line 763 of file nn_index.h.
References flann::NNIndex< Distance >::ids_, flann::NNIndex< Distance >::last_id_, flann::NNIndex< Distance >::points_, flann::NNIndex< Distance >::removed_, flann::NNIndex< Distance >::removed_points_, flann::DynamicBitset::reset(), flann::DynamicBitset::resize(), flann::Matrix_::rows, and flann::NNIndex< Distance >::size_.
Referenced by flann::HierarchicalClusteringIndex< Distance >::addPoints(), flann::KDTreeIndex< Distance >::addPoints(), flann::KDTreeSingleIndex< Distance >::addPoints(), flann::KMeansIndex< Distance >::addPoints(), flann::LinearIndex< Distance >::addPoints(), and flann::LshIndex< Distance >::addPoints().
findNeighbors()
template<typename Distance > virtual void flann::NNIndex< Distance >::findNeighbors (ResultSet< DistanceType > & result, const ElementType * vec, const SearchParams & searchParams) const pure virtual
Implemented in flann::LinearIndex< Distance >, flann::KMeansIndex< Distance >, flann::KDTreeSingleIndex< Distance >, flann::KDTreeIndex< Distance >, flann::KDTreeCuda3dIndex< Distance >, flann::HierarchicalClusteringIndex< Distance >, flann::CompositeIndex< Distance >, flann::AutotunedIndex< Distance >, and flann::LshIndex< Distance >.
Referenced by flann::NNIndex< Distance >::knnSearch(), and flann::NNIndex< Distance >::radiusSearch().
freeIndex()
template<typename Distance > virtual void flann::NNIndex< Distance >::freeIndex () protected pure virtual
Implemented in flann::LshIndex< Distance >, flann::LinearIndex< Distance >, flann::KDTreeIndex< Distance >, flann::KDTreeCuda3dIndex< Distance >, flann::CompositeIndex< Distance >, and flann::AutotunedIndex< Distance >.
Referenced by flann::NNIndex< Distance >::buildIndex().
getParameters()
template<typename Distance > IndexParams flann::NNIndex< Distance >::getParameters () const inline virtual
Returns the parameters used by the index.
Returns
The index parameters
Implements flann::IndexBase.
Definition at line 219 of file nn_index.h.
References flann::NNIndex< Distance >::index_params_.
Referenced by flann::Index< Distance >::getParameters().
getPoint()
template<typename Distance > virtual ElementType* flann::NNIndex< Distance >::getPoint (size_t id) inline virtual
Get point with specific id
Parameters
id
Returns
Reimplemented in flann::KDTreeCuda3dIndex< Distance >.
Definition at line 187 of file nn_index.h.
References flann::NNIndex< Distance >::id_to_index(), NULL, and flann::NNIndex< Distance >::points_.
Referenced by flann::Index< Distance >::getPoint().
id_to_index()
template<typename Distance > size_t flann::NNIndex< Distance >::id_to_index (size_t id) inline protected
Definition at line 705 of file nn_index.h.
References flann::NNIndex< Distance >::ids_.
Referenced by flann::NNIndex< Distance >::getPoint(), and flann::NNIndex< Distance >::removePoint().
indices_to_ids()
template<typename Distance > void flann::NNIndex< Distance >::indices_to_ids (const size_t * in, size_t * out, size_t size) const inline protected
Definition at line 737 of file nn_index.h.
Referenced by flann::LshIndex< Distance >::knnSearch(), flann::NNIndex< Distance >::knnSearch(), and flann::NNIndex< Distance >::radiusSearch().
knnSearch() [1/4]
template<typename Distance > int flann::NNIndex< Distance >::knnSearch (const Matrix< ElementType > & queries, Matrix< int > & indices, Matrix< DistanceType > & dists, size_t knn, const SearchParams & params) const inline
Parameters
queries
indices
dists
knn
params
Returns
Definition at line 368 of file nn_index.h.
References flann::Matrix_::cols, flann::NNIndex< Distance >::knnSearch(), params, flann::Matrix< T >::ptr(), result, and flann::Matrix_::rows.
knnSearch() [2/4]
template<typename Distance > virtual int flann::NNIndex< Distance >::knnSearch (const Matrix< ElementType > & queries, Matrix< size_t > & indices, Matrix< DistanceType > & dists, size_t knn, const SearchParams & params) const inline virtual
Perform k-nearest neighbor search.
Parameters
[in] queries The query points for which to find the nearest neighbors
[out] indices The indices of the nearest neighbors found
[out] dists Distances to the nearest neighbors found
[in] knn Number of nearest neighbors to return
[in] params Search parameters
Reimplemented in flann::LshIndex< Distance >, and flann::AutotunedIndex< Distance >.
Definition at line 305 of file nn_index.h.
References flann::KNNSimpleResultSet< DistanceType >::clear(), flann::KNNResultSet2< DistanceType >::clear(), flann::Matrix_::cols, flann::KNNSimpleResultSet< DistanceType >::copy(), flann::KNNResultSet2< DistanceType >::copy(), count, flann::NNIndex< Distance >::findNeighbors(), flann::FLANN_True, flann::FLANN_Undefined, flann::NNIndex< Distance >::indices_to_ids(), KNN_HEAP_THRESHOLD, min(), params, flann::Matrix_::rows, flann::KNNSimpleResultSet< DistanceType >::size(), flann::KNNResultSet2< DistanceType >::size(), and flann::NNIndex< Distance >::veclen().
Referenced by flann::NNIndex< Distance >::knnSearch(), and flann::Index< Distance >::knnSearch().
knnSearch() [3/4]
template<typename Distance > int flann::NNIndex< Distance >::knnSearch (const Matrix< ElementType > & queries, std::vector< std::vector< int > > & indices, std::vector< std::vector< DistanceType > > & dists, size_t knn, const SearchParams & params) const inline
Parameters
queries
indices
dists
knn
params
Returns
Definition at line 466 of file nn_index.h.
References flann::NNIndex< Distance >::knnSearch(), params, and result.
knnSearch() [4/4]
template<typename Distance > int flann::NNIndex< Distance >::knnSearch (const Matrix< ElementType > & queries, std::vector< std::vector< size_t > > & indices, std::vector< std::vector< DistanceType > > & dists, size_t knn, const SearchParams & params) const inline
Perform k-nearest neighbor search.
Parameters
[in] queries The query points for which to find the nearest neighbors
[out] indices The indices of the nearest neighbors found
[out] dists Distances to the nearest neighbors found
[in] knn Number of nearest neighbors to return
[in] params Search parameters
Definition at line 395 of file nn_index.h.
References flann::KNNSimpleResultSet< DistanceType >::clear(), flann::KNNResultSet2< DistanceType >::clear(), flann::Matrix_::cols, flann::KNNSimpleResultSet< DistanceType >::copy(), flann::KNNResultSet2< DistanceType >::copy(), count, flann::NNIndex< Distance >::findNeighbors(), flann::FLANN_True, flann::FLANN_Undefined, flann::NNIndex< Distance >::indices_to_ids(), KNN_HEAP_THRESHOLD, min(), params, flann::Matrix_::rows, flann::KNNSimpleResultSet< DistanceType >::size(), flann::KNNResultSet2< DistanceType >::size(), and flann::NNIndex< Distance >::veclen().
radiusSearch() [1/4]
template<typename Distance > int flann::NNIndex< Distance >::radiusSearch (const Matrix< ElementType > & queries, Matrix< int > & indices, Matrix< DistanceType > & dists, float radius, const SearchParams & params) const inline
Parameters
queries
indices
dists
radius
params
Returns
Definition at line 574 of file nn_index.h.
References flann::Matrix_::cols, params, flann::Matrix< T >::ptr(), flann::NNIndex< Distance >::radiusSearch(), result, and flann::Matrix_::rows.
radiusSearch() [2/4]
template<typename Distance > int flann::NNIndex< Distance >::radiusSearch (const Matrix< ElementType > & queries, Matrix< size_t > & indices, Matrix< DistanceType > & dists, float radius, const SearchParams & params) const inline
Perform radius search.
Parameters
[in] query The query point
[out] indices The indices of the neighbors found within the given radius
[out] dists The distances to the nearest neighbors found
[in] radius The radius used for search
[in] params Search parameters
Returns
Number of neighbors found
Definition at line 491 of file nn_index.h.
References flann::RadiusResultSet< DistanceType >::clear(), flann::KNNRadiusResultSet< DistanceType >::clear(), flann::CountRadiusResultSet< DistanceType >::clear(), flann::Matrix_::cols, flann::RadiusResultSet< DistanceType >::copy(), flann::KNNRadiusResultSet< DistanceType >::copy(), count, flann::NNIndex< Distance >::findNeighbors(), flann::NNIndex< Distance >::indices_to_ids(), infinity(), min(), params, flann::Matrix_::rows, flann::NNIndex< Distance >::size(), flann::RadiusResultSet< DistanceType >::size(), flann::KNNRadiusResultSet< DistanceType >::size(), flann::CountRadiusResultSet< DistanceType >::size(), and flann::NNIndex< Distance >::veclen().
Referenced by flann::NNIndex< Distance >::radiusSearch(), and flann::Index< Distance >::radiusSearch().
radiusSearch() [3/4]
template<typename Distance > int flann::NNIndex< Distance >::radiusSearch (const Matrix< ElementType > & queries, std::vector< std::vector< int > > & indices, std::vector< std::vector< DistanceType > > & dists, float radius, const SearchParams & params) const inline
Parameters
queries
indices
dists
radius
params
Returns
Definition at line 680 of file nn_index.h.
References params, flann::NNIndex< Distance >::radiusSearch(), and result.
radiusSearch() [4/4]
template<typename Distance > int flann::NNIndex< Distance >::radiusSearch (const Matrix< ElementType > & queries, std::vector< std::vector< size_t > > & indices, std::vector< std::vector< DistanceType > > & dists, float radius, const SearchParams & params) const inline
Perform radius search.
Parameters
[in] query The query point
[out] indices The indices of the neighbors found within the given radius
[out] dists The distances to the nearest neighbors found
[in] radius The radius used for search
[in] params Search parameters
Returns
Number of neighbors found
Definition at line 601 of file nn_index.h.
References flann::RadiusResultSet< DistanceType >::clear(), flann::KNNRadiusResultSet< DistanceType >::clear(), flann::CountRadiusResultSet< DistanceType >::clear(), flann::Matrix_::cols, flann::RadiusResultSet< DistanceType >::copy(), flann::KNNRadiusResultSet< DistanceType >::copy(), count, flann::NNIndex< Distance >::findNeighbors(), flann::NNIndex< Distance >::indices_to_ids(), params, flann::Matrix_::rows, flann::RadiusResultSet< DistanceType >::size(), flann::KNNRadiusResultSet< DistanceType >::size(), flann::CountRadiusResultSet< DistanceType >::size(), and flann::NNIndex< Distance >::veclen().
removePoint()
template<typename Distance > virtual void flann::NNIndex< Distance >::removePoint (size_t id) inline virtual
Remove point from the index
Parameters
index Index of point to be removed
Reimplemented in flann::KDTreeCuda3dIndex< Distance >, flann::CompositeIndex< Distance >, and flann::AutotunedIndex< Distance >.
Definition at line 161 of file nn_index.h.
References flann::NNIndex< Distance >::id_to_index(), flann::NNIndex< Distance >::ids_, flann::NNIndex< Distance >::last_id_, flann::NNIndex< Distance >::removed_, flann::NNIndex< Distance >::removed_count_, flann::NNIndex< Distance >::removed_points_, flann::DynamicBitset::reset(), flann::DynamicBitset::resize(), flann::DynamicBitset::set(), flann::NNIndex< Distance >::size_, and flann::DynamicBitset::test().
Referenced by flann::Index< Distance >::removePoint().
serialize()
template<typename Distance > template<typename Archive > void flann::NNIndex< Distance >::serialize (Archive & ar) inline
Definition at line 226 of file nn_index.h.
References flann::IndexHeaderStruct::cols, flann::NNIndex< Distance >::data_ptr_, flann::IndexHeaderStruct::data_type, FLANN_SIGNATURE_, flann::get_param(), flann::IndexBase::getType(), flann::IndexHeader::h, flann::NNIndex< Distance >::ids_, flann::NNIndex< Distance >::index_params_, flann::IndexHeaderStruct::index_type, flann::NNIndex< Distance >::last_id_, flann::serialization::make_binary_object(), flann::NNIndex< Distance >::points_, flann::NNIndex< Distance >::removed_, flann::NNIndex< Distance >::removed_count_, flann::NNIndex< Distance >::removed_points_, flann::IndexHeaderStruct::rows, flann::IndexHeaderStruct::signature, flann::NNIndex< Distance >::size_, flann::NNIndex< Distance >::size_at_build_, and flann::NNIndex< Distance >::veclen_.
setDataset()
template<typename Distance > void flann::NNIndex< Distance >::setDataset (const Matrix< ElementType > & dataset) inline protected
Definition at line 746 of file nn_index.h.
References flann::DynamicBitset::clear(), flann::Matrix_::cols, flann::NNIndex< Distance >::ids_, flann::NNIndex< Distance >::last_id_, flann::NNIndex< Distance >::points_, flann::NNIndex< Distance >::removed_, flann::NNIndex< Distance >::removed_count_, flann::NNIndex< Distance >::removed_points_, flann::Matrix_::rows, flann::NNIndex< Distance >::size_, and flann::NNIndex< Distance >::veclen_.
Referenced by flann::NNIndex< Distance >::buildIndex(), flann::HierarchicalClusteringIndex< Distance >::HierarchicalClusteringIndex(), flann::KDTreeIndex< Distance >::KDTreeIndex(), flann::KDTreeSingleIndex< Distance >::KDTreeSingleIndex(), flann::KMeansIndex< Distance >::KMeansIndex(), flann::LinearIndex< Distance >::LinearIndex(), and flann::LshIndex< Distance >::LshIndex().
size()
template<typename Distance > size_t flann::NNIndex< Distance >::size () const inline virtual
Returns
number of features in this index.
Implements flann::IndexBase.
Definition at line 201 of file nn_index.h.
References flann::NNIndex< Distance >::removed_count_, and flann::NNIndex< Distance >::size_.
Referenced by flann::NNIndex< Distance >::radiusSearch(), and flann::Index< Distance >::size().
swap()
template<typename Distance > void flann::NNIndex< Distance >::swap (NNIndex< Distance > & other) inline protected
Definition at line 802 of file nn_index.h.
References flann::NNIndex< Distance >::data_ptr_, flann::NNIndex< Distance >::distance_, flann::NNIndex< Distance >::ids_, flann::NNIndex< Distance >::index_params_, flann::NNIndex< Distance >::last_id_, flann::NNIndex< Distance >::points_, flann::NNIndex< Distance >::removed_, flann::NNIndex< Distance >::removed_count_, flann::NNIndex< Distance >::removed_points_, flann::NNIndex< Distance >::size_, flann::NNIndex< Distance >::size_at_build_, std::swap(), and flann::NNIndex< Distance >::veclen_.
Referenced by flann::LinearIndex< Distance >::operator=().
veclen()
template<typename Distance > size_t flann::NNIndex< Distance >::veclen () const inline virtual
Returns
The dimensionality of the features in this index.
Implements flann::IndexBase.
Definition at line 209 of file nn_index.h.
References flann::NNIndex< Distance >::veclen_.
Referenced by flann::NNIndex< Distance >::knnSearch(), flann::NNIndex< Distance >::radiusSearch(), and flann::Index< Distance >::veclen().
Member Data Documentation
data_ptr_
template<typename Distance > ElementType* flann::NNIndex< Distance >::data_ptr_ protected
Pointer to dataset memory if allocated by this index, otherwise NULL
Definition at line 881 of file nn_index.h.
Referenced by flann::NNIndex< Distance >::NNIndex(), flann::NNIndex< Distance >::serialize(), flann::NNIndex< Distance >::swap(), and flann::NNIndex< Distance >::~NNIndex().
distance_
template<typename Distance > Distance flann::NNIndex< Distance >::distance_ protected
The distance functor
Definition at line 823 of file nn_index.h.
Referenced by flann::KMeansIndex< Distance >::addPoints(), flann::AutotunedIndex< Distance >::buildIndex(), flann::LinearIndex< Distance >::findNeighbors(), flann::HierarchicalClusteringIndex< Distance >::initCenterChooser(), flann::KMeansIndex< Distance >::initCenterChooser(), flann::AutotunedIndex< Distance >::loadIndex(), and flann::NNIndex< Distance >::swap().
ids_
template<typename Distance > std::vector<size_t> flann::NNIndex< Distance >::ids_ protected
Array of point IDs, returned by nearest-neighbour operations
Definition at line 871 of file nn_index.h.
Referenced by flann::NNIndex< Distance >::cleanRemovedPoints(), flann::NNIndex< Distance >::extendDataset(), flann::NNIndex< Distance >::id_to_index(), flann::NNIndex< Distance >::removePoint(), flann::NNIndex< Distance >::serialize(), flann::NNIndex< Distance >::setDataset(), and flann::NNIndex< Distance >::swap().
index_params_
template<typename Distance > IndexParams flann::NNIndex< Distance >::index_params_ protected
Parameters of the index.
Definition at line 851 of file nn_index.h.
Referenced by flann::NNIndex< Distance >::getParameters(), flann::HierarchicalClusteringIndex< Distance >::HierarchicalClusteringIndex(), flann::KDTreeIndex< Distance >::KDTreeIndex(), flann::LshIndex< Distance >::LshIndex(), flann::AutotunedIndex< Distance >::serialize(), flann::HierarchicalClusteringIndex< Distance >::serialize(), flann::KDTreeIndex< Distance >::serialize(), flann::KDTreeSingleIndex< Distance >::serialize(), flann::KMeansIndex< Distance >::serialize(), flann::LinearIndex< Distance >::serialize(), flann::LshIndex< Distance >::serialize(), flann::NNIndex< Distance >::serialize(), and flann::NNIndex< Distance >::swap().
last_id_
template<typename Distance > size_t flann::NNIndex< Distance >::last_id_ protected
Each index point has an associated ID. IDs are assigned sequentially in increasing order. This indicates the ID assigned to the last point added to the index.
Definition at line 831 of file nn_index.h.
Referenced by flann::NNIndex< Distance >::extendDataset(), flann::NNIndex< Distance >::removePoint(), flann::NNIndex< Distance >::serialize(), flann::NNIndex< Distance >::setDataset(), and flann::NNIndex< Distance >::swap().
points_
template<typename Distance > std::vector<ElementType*> flann::NNIndex< Distance >::points_ protected
Point data
Definition at line 876 of file nn_index.h.
Referenced by flann::LshIndex< Distance >::addPoints(), flann::KDTreeSingleIndex< Distance >::buildIndexImpl(), flann::LshIndex< Distance >::buildIndexImpl(), flann::NNIndex< Distance >::cleanRemovedPoints(), flann::NNIndex< Distance >::extendDataset(), flann::LinearIndex< Distance >::findNeighbors(), flann::NNIndex< Distance >::getPoint(), flann::HierarchicalClusteringIndex< Distance >::initCenterChooser(), flann::KMeansIndex< Distance >::initCenterChooser(), flann::NNIndex< Distance >::NNIndex(), flann::NNIndex< Distance >::serialize(), flann::NNIndex< Distance >::setDataset(), and flann::NNIndex< Distance >::swap().
removed_
template<typename Distance > bool flann::NNIndex< Distance >::removed_ protected
Flag indicating if at least a point was removed from the index
Definition at line 856 of file nn_index.h.
Referenced by flann::NNIndex< Distance >::cleanRemovedPoints(), flann::NNIndex< Distance >::extendDataset(), flann::HierarchicalClusteringIndex< Distance >::findNeighbors(), flann::KDTreeIndex< Distance >::findNeighbors(), flann::KDTreeSingleIndex< Distance >::findNeighbors(), flann::KMeansIndex< Distance >::findNeighbors(), flann::LinearIndex< Distance >::findNeighbors(), flann::NNIndex< Distance >::removePoint(), flann::NNIndex< Distance >::serialize(), flann::NNIndex< Distance >::setDataset(), and flann::NNIndex< Distance >::swap().
removed_count_
template<typename Distance > size_t flann::NNIndex< Distance >::removed_count_ protected
Number of points removed from the index
Definition at line 866 of file nn_index.h.
Referenced by flann::NNIndex< Distance >::cleanRemovedPoints(), flann::NNIndex< Distance >::removePoint(), flann::NNIndex< Distance >::serialize(), flann::NNIndex< Distance >::setDataset(), flann::NNIndex< Distance >::size(), and flann::NNIndex< Distance >::swap().
removed_points_
template<typename Distance > DynamicBitset flann::NNIndex< Distance >::removed_points_ protected
Array used to mark points removed from the index
Definition at line 861 of file nn_index.h.
Referenced by flann::NNIndex< Distance >::cleanRemovedPoints(), flann::NNIndex< Distance >::extendDataset(), flann::LinearIndex< Distance >::findNeighbors(), flann::NNIndex< Distance >::removePoint(), flann::NNIndex< Distance >::serialize(), flann::NNIndex< Distance >::setDataset(), and flann::NNIndex< Distance >::swap().
size_
template<typename Distance > size_t flann::NNIndex< Distance >::size_ protected
Number of points in the index (and database)
Definition at line 836 of file nn_index.h.
Referenced by flann::HierarchicalClusteringIndex< Distance >::addPoints(), flann::KDTreeIndex< Distance >::addPoints(), flann::KMeansIndex< Distance >::addPoints(), flann::LshIndex< Distance >::addPoints(), flann::KDTreeCuda3dIndex< Distance >::buildIndex(), flann::NNIndex< Distance >::buildIndex(), flann::HierarchicalClusteringIndex< Distance >::buildIndexImpl(), flann::KDTreeIndex< Distance >::buildIndexImpl(), flann::KDTreeSingleIndex< Distance >::buildIndexImpl(), flann::KMeansIndex< Distance >::buildIndexImpl(), flann::NNIndex< Distance >::cleanRemovedPoints(), flann::NNIndex< Distance >::extendDataset(), flann::KDTreeCuda3dIndex< Distance >::KDTreeCuda3dIndex(), flann::KDTreeSingleIndex< Distance >::KDTreeSingleIndex(), flann::NNIndex< Distance >::NNIndex(), flann::NNIndex< Distance >::removePoint(), flann::NNIndex< Distance >::serialize(), flann::NNIndex< Distance >::setDataset(), flann::NNIndex< Distance >::size(), flann::NNIndex< Distance >::swap(), flann::KDTreeIndex< Distance >::usedMemory(), flann::KDTreeSingleIndex< Distance >::usedMemory(), and flann::LshIndex< Distance >::usedMemory().
size_at_build_
template<typename Distance > size_t flann::NNIndex< Distance >::size_at_build_ protected
Number of features in the dataset when the index was last built.
Definition at line 841 of file nn_index.h.
Referenced by flann::HierarchicalClusteringIndex< Distance >::addPoints(), flann::KDTreeIndex< Distance >::addPoints(), flann::KMeansIndex< Distance >::addPoints(), flann::LshIndex< Distance >::addPoints(), flann::NNIndex< Distance >::buildIndex(), flann::NNIndex< Distance >::serialize(), and flann::NNIndex< Distance >::swap().
veclen_
template<typename Distance > size_t flann::NNIndex< Distance >::veclen_ protected
Size of one point in the index (and database)
Definition at line 846 of file nn_index.h.
Referenced by flann::HierarchicalClusteringIndex< Distance >::addPoints(), flann::KDTreeIndex< Distance >::addPoints(), flann::KDTreeSingleIndex< Distance >::addPoints(), flann::KMeansIndex< Distance >::addPoints(), flann::LinearIndex< Distance >::addPoints(), flann::LshIndex< Distance >::addPoints(), flann::HierarchicalClusteringIndex< Distance >::buildIndexImpl(), flann::KDTreeIndex< Distance >::buildIndexImpl(), flann::KDTreeSingleIndex< Distance >::buildIndexImpl(), flann::KMeansIndex< Distance >::buildIndexImpl(), flann::LshIndex< Distance >::buildIndexImpl(), flann::KDTreeSingleIndex< Distance >::findNeighbors(), flann::LinearIndex< Distance >::findNeighbors(), flann::KMeansIndex< Distance >::getClusterCenters(), flann::HierarchicalClusteringIndex< Distance >::HierarchicalClusteringIndex(), flann::KDTreeSingleIndex< Distance >::KDTreeSingleIndex(), flann::LshIndex< Distance >::knnSearch(), flann::NNIndex< Distance >::NNIndex(), flann::NNIndex< Distance >::serialize(), flann::NNIndex< Distance >::setDataset(), flann::NNIndex< Distance >::swap(), and flann::NNIndex< Distance >::veclen().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/algorithms/nn_index.h