ACloudViewer: cloudViewer::io::AzureKinectRecorder Class Reference
cloudViewer::io::AzureKinectRecorder Class Reference
#include <AzureKinectRecorder.h>
Public Member Functions
AzureKinectRecorder (const AzureKinectSensorConfig &sensor_config, size_t sensor_index)
~AzureKinectRecorder () override
bool InitSensor () override
Initialize sensor.
bool OpenRecord (const std::string &filename) override
bool CloseRecord () override
Close the recorded mkv file.
std::shared_ptr< geometry::RGBDImage > RecordFrame (bool write, bool enable_align_depth_to_color) override
bool IsRecordCreated ()
Check if the mkv file is created.
Public Member Functions inherited from cloudViewer::io::RGBDRecorder
RGBDRecorder ()
virtual ~RGBDRecorder ()
Protected Attributes
AzureKinectSensor sensor_
_k4a_record_t * recording_
size_t device_index_
bool is_record_created_ = false
Detailed Description
AzureKinect recorder.
Definition at line 32 of file AzureKinectRecorder.h.
Constructor & Destructor Documentation
AzureKinectRecorder()
cloudViewer::io::AzureKinectRecorder::AzureKinectRecorder (const AzureKinectSensorConfig & sensor_config, size_t sensor_index)
Definition at line 35 of file AzureKinectRecorder.cpp.
~AzureKinectRecorder()
cloudViewer::io::AzureKinectRecorder::~AzureKinectRecorder () override
Definition at line 41 of file AzureKinectRecorder.cpp.
References CloseRecord().
Member Function Documentation
CloseRecord()
bool cloudViewer::io::AzureKinectRecorder::CloseRecord () override virtual
Close the recorded mkv file.
Implements cloudViewer::io::RGBDRecorder.
Definition at line 68 of file AzureKinectRecorder.cpp.
References is_record_created_, cloudViewer::io::k4a_plugin::k4a_record_close(), cloudViewer::io::k4a_plugin::k4a_record_flush(), LogInfo, LogWarning, and recording_.
Referenced by ~AzureKinectRecorder().
InitSensor()
bool cloudViewer::io::AzureKinectRecorder::InitSensor () override virtual
Initialize sensor.
Implements cloudViewer::io::RGBDRecorder.
Definition at line 43 of file AzureKinectRecorder.cpp.
References cloudViewer::io::AzureKinectSensor::Connect(), device_index_, and sensor_.
IsRecordCreated()
bool cloudViewer::io::AzureKinectRecorder::IsRecordCreated () inline
Check if the mkv file is created.
Definition at line 55 of file AzureKinectRecorder.h.
References is_record_created_.
OpenRecord()
bool cloudViewer::io::AzureKinectRecorder::OpenRecord (const std::string & filename) override virtual
Attempt to create and open an mkv file.
Parameters
filename Path to the mkv file.
Implements cloudViewer::io::RGBDRecorder.
Definition at line 47 of file AzureKinectRecorder.cpp.
References cloudViewer::io::AzureKinectSensorConfig::ConvertToNativeConfig(), cloudViewer::io::AzureKinectSensor::device_, is_record_created_, cloudViewer::io::k4a_plugin::k4a_record_create(), cloudViewer::io::k4a_plugin::k4a_record_write_header(), LogInfo, LogWarning, recording_, sensor_, and cloudViewer::io::AzureKinectSensor::sensor_config_.
RecordFrame()
std::shared_ptr< geometry::RGBDImage > cloudViewer::io::AzureKinectRecorder::RecordFrame (bool write, bool enable_align_depth_to_color) override virtual
Record a frame to mkv if flag is on and return an RGBD object.
Parameters
write Enable recording to mkv file.
enable_align_depth_to_color Enable aligning WFOV depth image to the color image in visualizer.
Implements cloudViewer::io::RGBDRecorder.
Definition at line 83 of file AzureKinectRecorder.cpp.
References cloudViewer::io::AzureKinectSensor::CaptureRawFrame(), cloudViewer::io::AzureKinectSensor::DecompressCapture(), is_record_created_, cloudViewer::io::k4a_plugin::k4a_capture_release(), cloudViewer::io::k4a_plugin::k4a_record_write_capture(), LogError, LogInfo, recording_, sensor_, and cloudViewer::io::AzureKinectSensor::transform_depth_to_color_.
Member Data Documentation
device_index_
size_t cloudViewer::io::AzureKinectRecorder::device_index_ protected
Definition at line 60 of file AzureKinectRecorder.h.
Referenced by InitSensor().
is_record_created_
bool cloudViewer::io::AzureKinectRecorder::is_record_created_ = false protected
Definition at line 62 of file AzureKinectRecorder.h.
Referenced by CloseRecord(), IsRecordCreated(), OpenRecord(), and RecordFrame().
recording_
_k4a_record_t* cloudViewer::io::AzureKinectRecorder::recording_ protected
Definition at line 59 of file AzureKinectRecorder.h.
Referenced by CloseRecord(), OpenRecord(), and RecordFrame().
sensor_
AzureKinectSensor cloudViewer::io::AzureKinectRecorder::sensor_ protected
Definition at line 58 of file AzureKinectRecorder.h.
Referenced by InitSensor(), OpenRecord(), and RecordFrame().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/io/sensor/azure_kinect/AzureKinectRecorder.h
/root/ACloudViewer/libs/cloudViewer/io/sensor/azure_kinect/AzureKinectRecorder.cpp