ACloudViewer: colmap::GPSTransform Class Reference
colmap::GPSTransform Class Reference
#include <gps.h>
Public Types
enum ELLIPSOID { GRS80 , WGS84 }
Public Member Functions
GPSTransform (const int ellipsoid=GRS80)
std::vector< Eigen::Vector3d > EllToXYZ (const std::vector< Eigen::Vector3d > &ell) const
std::vector< Eigen::Vector3d > XYZToEll (const std::vector< Eigen::Vector3d > &xyz) const
Detailed Description
Definition at line 20 of file gps.h.
Member Enumeration Documentation
ELLIPSOID
enum colmap::GPSTransform::ELLIPSOID
Enumerator
GRS80
WGS84
Definition at line 22 of file gps.h.
Constructor & Destructor Documentation
GPSTransform()
colmap::GPSTransform::GPSTransform (const int ellipsoid = GRS80) explicit
Definition at line 38 of file gps.cc.
References GRS80, and WGS84.
Member Function Documentation
EllToXYZ()
std::vector< Eigen::Vector3d > colmap::GPSTransform::EllToXYZ (const std::vector< Eigen::Vector3d > & ell) const
Definition at line 57 of file gps.cc.
References colmap::DegToRad().
Referenced by BOOST_AUTO_TEST_CASE().
XYZToEll()
std::vector< Eigen::Vector3d > colmap::GPSTransform::XYZToEll (const std::vector< Eigen::Vector3d > & xyz) const
Definition at line 82 of file gps.cc.
References e, colmap::RadToDeg(), x, y, and z.
Referenced by colmap::AlignToENUPlane(), and BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/gps.h
/root/ACloudViewer/libs/Reconstruction/src/base/gps.cc