ACloudViewer: PdmsTools::PdmsObjects::GroupElement Class Reference
PdmsTools::PdmsObjects::GroupElement Class Reference
Group of elements.
#include <PdmsTools.h>
Public Member Functions
GroupElement (Token l)
virtual ~GroupElement ()
virtual void clear (bool del=false)
virtual bool push (GenericItem *i)
virtual void remove (GenericItem *i)
virtual bool isGroupElement ()
virtual bool convertCoordinateSystem ()
virtual GenericItem * scan (const char *str)
virtual bool scan (Token t, std::vector< GenericItem * > &array)
virtual Token getType () const
virtual std::pair< int, int > write (std::ostream &output, int nbtabs=0) const
Public Member Functions inherited from PdmsTools::PdmsObjects::GenericItem
GenericItem ()
Default constructor.
virtual ~GenericItem ()
Destructor.
virtual bool setPosition (const CCVector3 &p)
virtual bool setOrientation (const CCVector3 &x, const CCVector3 &y, const CCVector3 &z)
virtual GenericItem * getRoot ()
virtual bool isDesignElement ()
virtual bool setValue (Token t, PointCoordinateType value)
Public Attributes
Token level
std::list< DesignElement * > elements
std::list< GroupElement * > subhierarchy
Public Attributes inherited from PdmsTools::PdmsObjects::GenericItem
GenericItem * owner
Parent imte.
GenericItem * creator
Creator item.
CCVector3 position
Object position.
CCVector3 orientation [3]
Object orientation (X,Y and Z)
bool isCoordinateSystemUpToDate
Coordinate system update flag.
GenericItem * positionReference
Reference object (position)
GenericItem * orientationReferences [3]
Reference(s) object(s) (orientation)
char name [c_max_str_length]
Name.
Additional Inherited Members
Protected Member Functions inherited from PdmsTools::PdmsObjects::GenericItem
bool isOrientationValid (unsigned i) const
bool completeOrientation ()
Detailed Description
Group of elements.
Definition at line 228 of file PdmsTools.h.
Constructor & Destructor Documentation
GroupElement()
GroupElement::GroupElement (Token l) explicit
Definition at line 1080 of file PdmsTools.cpp.
References PdmsTools::c_max_str_length, elements, level, PdmsTools::PdmsObjects::GenericItem::name, and subhierarchy.
~GroupElement()
GroupElement::~GroupElement () virtual
Definition at line 1087 of file PdmsTools.cpp.
References clear().
Member Function Documentation
clear()
void GroupElement::clear (bool del = false) virtual
Definition at line 1089 of file PdmsTools.cpp.
References PdmsTools::PdmsObjects::Stack::Destroy(), elements, and subhierarchy.
Referenced by ~GroupElement().
convertCoordinateSystem()
bool GroupElement::convertCoordinateSystem () virtual
Reimplemented from PdmsTools::PdmsObjects::GenericItem.
Definition at line 1166 of file PdmsTools.cpp.
References PdmsTools::PdmsObjects::GenericItem::convertCoordinateSystem(), elements, PdmsTools::PdmsObjects::GenericItem::isCoordinateSystemUpToDate, and subhierarchy.
getType()
virtual Token PdmsTools::PdmsObjects::GroupElement::getType () const inline virtual
Reimplemented from PdmsTools::PdmsObjects::GenericItem.
Definition at line 249 of file PdmsTools.h.
References level.
isGroupElement()
virtual bool PdmsTools::PdmsObjects::GroupElement::isGroupElement () inline virtual
Reimplemented from PdmsTools::PdmsObjects::GenericItem.
Definition at line 245 of file PdmsTools.h.
push()
bool GroupElement::push (GenericItem * i) virtual
Implements PdmsTools::PdmsObjects::GenericItem.
Definition at line 1106 of file PdmsTools.cpp.
References elements, PdmsTools::PdmsObjects::GenericItem::getType(), PdmsTools::PdmsToken::isDesignElement(), PdmsTools::PdmsToken::isGroupElement(), level, memalert, PdmsTools::PdmsObjects::GenericItem::owner, PdmsTools::PDMS_GROUP, PdmsTools::PdmsObjects::GenericItem::push(), PdmsTools::PdmsObjects::GenericItem::remove(), and subhierarchy.
remove()
void GroupElement::remove (GenericItem * i) virtual
Reimplemented from PdmsTools::PdmsObjects::GenericItem.
Definition at line 1148 of file PdmsTools.cpp.
References elements, and subhierarchy.
scan() [1/2]
GenericItem * GroupElement::scan (const char * str) virtual
Reimplemented from PdmsTools::PdmsObjects::GenericItem.
Definition at line 1181 of file PdmsTools.cpp.
References elements, PdmsTools::PdmsObjects::GenericItem::scan(), and subhierarchy.
scan() [2/2]
bool GroupElement::scan (Token t, std::vector< GenericItem * > & array) virtual
Reimplemented from PdmsTools::PdmsObjects::GenericItem.
Definition at line 1194 of file PdmsTools.cpp.
References elements, PdmsTools::PdmsObjects::GenericItem::scan(), size, and subhierarchy.
write()
std::pair< int, int > GroupElement::write (std::ostream & output, int nbtabs = 0) const virtual
Implements PdmsTools::PdmsObjects::GenericItem.
Definition at line 1206 of file PdmsTools.cpp.
References elements, QtCompat::endl(), level, PdmsTools::PdmsObjects::GenericItem::name, PdmsTools::PDMS_EQUIPMENT, PdmsTools::PDMS_GROUP, PdmsTools::PDMS_SITE, PdmsTools::PDMS_STRUCTURE, PdmsTools::PDMS_SUBSTRUCTURE, PdmsTools::PDMS_WORLD, PdmsTools::PDMS_ZONE, and subhierarchy.
Member Data Documentation
elements
std::list<DesignElement *> PdmsTools::PdmsObjects::GroupElement::elements
Definition at line 231 of file PdmsTools.h.
Referenced by clear(), convertCoordinateSystem(), GroupElement(), PDMSFilter::loadFile(), push(), remove(), scan(), and write().
level
Token PdmsTools::PdmsObjects::GroupElement::level
Definition at line 230 of file PdmsTools.h.
Referenced by getType(), GroupElement(), push(), and write().
subhierarchy
std::list<GroupElement *> PdmsTools::PdmsObjects::GroupElement::subhierarchy
Definition at line 232 of file PdmsTools.h.
Referenced by clear(), convertCoordinateSystem(), GroupElement(), PDMSFilter::loadFile(), push(), remove(), scan(), and write().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsTools.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsTools.cpp