ACloudViewer: JlCompress Class Reference
JlCompress Class Reference
Utility class for typical operations.
#include <JlCompress.h>
Static Public Member Functions
static bool compressFile (QString fileCompressed, QString file)
Compress a single file.
static bool compressFiles (QString fileCompressed, QStringList files)
Compress a list of files.
static bool compressDir (QString fileCompressed, QString dir=QString(), bool recursive=true)
Compress a whole directory.
static bool compressDir (QString fileCompressed, QString dir, bool recursive, QDir::Filters filters)
Compress a whole directory.
static QString extractFile (QString fileCompressed, QString fileName, QString fileDest=QString())
Extract a single file.
static QStringList extractFiles (QString fileCompressed, QStringList files, QString dir=QString())
Extract a list of files.
static QStringList extractDir (QString fileCompressed, QString dir=QString())
Extract a whole archive.
static QStringList getFileList (QString fileCompressed)
Get the file list.
static QString extractFile (QIODevice *ioDevice, QString fileName, QString fileDest=QString())
Extract a single file.
static QStringList extractFiles (QIODevice *ioDevice, QStringList files, QString dir=QString())
Extract a list of files.
static QStringList extractDir (QIODevice *ioDevice, QString dir=QString())
Extract a whole archive.
static QStringList getFileList (QIODevice *ioDevice)
Get the file list.
Detailed Description
Utility class for typical operations.
This class contains a number of useful static functions to perform simple operations, such as mass ZIP packing or extraction.
Definition at line 43 of file JlCompress.h.
Member Function Documentation
compressDir() [1/2]
bool JlCompress::compressDir (QString fileCompressed, QString dir, bool recursive, QDir::Filters filters) static
Compress a whole directory.
Unless filters are specified explicitly, packs only regular non-hidden files (and subdirs, if recursive is true). If filters are specified, they are OR-combined with QDir::AllDirs|QDir::NoDotAndDotDot when searching for dirs and with QDir::Files when searching for files.
Parameters
fileCompressed path to the resulting archive
dir path to the directory being compressed
recursive if true, then the subdirectories are packed as well
filters what to pack, filters are applied both when searching for subdirs (if packing recursively) and when looking for files to pack
Returns
true on success, false otherwise
Definition at line 277 of file JlCompress.cpp.
References QuaZip::close(), QuaZip::getZipError(), QuaZip::mdCreate, and QuaZip::open().
compressDir() [2/2]
bool JlCompress::compressDir (QString fileCompressed, QString dir = QString(), bool recursive = true) static
Compress a whole directory.
Does not compress hidden files. See compressDir(QString, QString, bool, QDir::Filters).
Parameters
fileCompressed The name of the archive.
dir The directory to compress.
recursive Whether to pack the subdirectories as well, or just regular files.
Returns
true if success, false otherwise.
Definition at line 267 of file JlCompress.cpp.
compressFile()
bool JlCompress::compressFile (QString fileCompressed, QString file) static
Compress a single file.
Parameters
fileCompressed The name of the archive.
file The file to compress.
Returns
true if success, false otherwise.
Definition at line 213 of file JlCompress.cpp.
References QuaZip::close(), QuaZip::getZipError(), QuaZip::mdCreate, and QuaZip::open().
compressFiles()
bool JlCompress::compressFiles (QString fileCompressed, QStringList files) static
Compress a list of files.
Parameters
fileCompressed The name of the archive.
files The file list to compress.
Returns
true if success, false otherwise.
Definition at line 238 of file JlCompress.cpp.
References QuaZip::close(), QuaZip::getZipError(), QuaZip::mdCreate, and QuaZip::open().
extractDir() [1/2]
QStringList JlCompress::extractDir (QIODevice * ioDevice, QString dir = QString()) static
Extract a whole archive.
Parameters
ioDevice pointer to device with compressed data.
dir The directory to extract to, the current directory if left empty.
Returns
The list of the full paths of the files extracted, empty on failure.
Definition at line 441 of file JlCompress.cpp.
extractDir() [2/2]
QStringList JlCompress::extractDir (QString fileCompressed, QString dir = QString()) static
Extract a whole archive.
Parameters
fileCompressed The name of the archive.
dir The directory to extract to, the current directory if left empty.
Returns
The list of the full paths of the files extracted, empty on failure.
Definition at line 371 of file JlCompress.cpp.
extractFile() [1/2]
QString JlCompress::extractFile (QIODevice * ioDevice, QString fileName, QString fileDest = QString()) static
Extract a single file.
Parameters
ioDevice pointer to device with compressed data.
fileName The file to extract.
fileDest The destination file, assumed to be identical to file if left empty.
Returns
The list of the full paths of the files extracted, empty on failure.
Definition at line 451 of file JlCompress.cpp.
extractFile() [2/2]
QString JlCompress::extractFile (QString fileCompressed, QString fileName, QString fileDest = QString()) static
Extract a single file.
Parameters
fileCompressed The name of the archive.
fileName The file to extract.
fileDest The destination file, assumed to be identical to file if left empty.
Returns
The list of the full paths of the files extracted, empty on failure.
Definition at line 305 of file JlCompress.cpp.
extractFiles() [1/2]
QStringList JlCompress::extractFiles (QIODevice * ioDevice, QStringList files, QString dir = QString()) static
Extract a list of files.
Parameters
ioDevice pointer to device with compressed data.
files The file list to extract.
dir The directory to put the files to, the current directory if left empty.
Returns
The list of the full paths of the files extracted, empty on failure.
Definition at line 458 of file JlCompress.cpp.
extractFiles() [2/2]
QStringList JlCompress::extractFiles (QString fileCompressed, QStringList files, QString dir = QString()) static
Extract a list of files.
Parameters
fileCompressed The name of the archive.
files The file list to extract.
dir The directory to put the files to, the current directory if left empty.
Returns
The list of the full paths of the files extracted, empty on failure.
Definition at line 335 of file JlCompress.cpp.
getFileList() [1/2]
QStringList JlCompress::getFileList (QIODevice * ioDevice) static
Get the file list.
Returns
The list of the files in the archive, or, more precisely, the list of the entries, including both files and directories if they are present separately.
Definition at line 446 of file JlCompress.cpp.
getFileList() [2/2]
QStringList JlCompress::getFileList (QString fileCompressed) static
Get the file list.
Returns
The list of the files in the archive, or, more precisely, the list of the entries, including both files and directories if they are present separately.
Definition at line 407 of file JlCompress.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qPhotoscanIO/extern/quazip/quazip/quazip/JlCompress.h
/root/ACloudViewer/plugins/core/IO/qPhotoscanIO/extern/quazip/quazip/quazip/JlCompress.cpp