ACloudViewer: PclTransformTool Class Reference
PclTransformTool Class Reference
#include <PclTransformTool.h>
Public Member Functions
PclTransformTool (ecvGenericVisualizer3D *viewer)
~PclTransformTool ()
virtual void setVisualizer (ecvGenericVisualizer3D *viewer=nullptr) override
initialize
virtual bool setInputData (ccHObject *entity, int viewport=0) override
void addActors ()
virtual void showInteractor (bool state) override
virtual bool start () override
virtual void stop () override
virtual void reset () override
virtual void clear () override
virtual void setTranlationMode (TranslationMOde mode)
virtual void setRotationMode (RotationMode mode)
virtual void setScaleEnabled (bool state)
virtual void setShearEnabled (bool state)
virtual const ccGLMatrixd getFinalTransformation () override
virtual void getOutput (std::vector< ccHObject * > &out) override
Public Member Functions inherited from ecvGenericTransformTool
ecvGenericTransformTool ()
virtual ~ecvGenericTransformTool ()=default
ccHObject * getAssociatedEntity ()
Additional Inherited Members
Public Types inherited from ecvGenericTransformTool
enum RotationMode { R_XYZ , R_X , R_Y , R_Z }
Default constructor.
enum TranslationMOde {
T_X , T_Y , T_Z , T_XY ,
T_XZ , T_ZY , T_XYZ , T_NONE
}
Signals inherited from ecvGenericTransformTool
void tranformMatrix (const ccGLMatrixd &transMatrix)
Protected Attributes inherited from ecvGenericTransformTool
ccHObject * m_associatedEntity
Detailed Description
Definition at line 28 of file PclTransformTool.h.
Constructor & Destructor Documentation
PclTransformTool()
PclTransformTool::PclTransformTool (ecvGenericVisualizer3D * viewer) explicit
Definition at line 41 of file PclTransformTool.cpp.
References setVisualizer().
~PclTransformTool()
PclTransformTool::~PclTransformTool ()
Definition at line 49 of file PclTransformTool.cpp.
Member Function Documentation
addActors()
void PclTransformTool::addActors ()
Definition at line 78 of file PclTransformTool.cpp.
References CVTools::FromQString(), PclUtils::PCLVis::getActorById(), ecvGenericTransformTool::getAssociatedEntity(), ccHObject::getChild(), ccHObject::getChildrenNumber(), and ccHObject::getViewId().
Referenced by setInputData().
clear()
void PclTransformTool::clear () override virtual
Implements ecvGenericTransformTool.
Definition at line 171 of file PclTransformTool.cpp.
getFinalTransformation()
const ccGLMatrixd PclTransformTool::getFinalTransformation () override virtual
Implements ecvGenericTransformTool.
Definition at line 284 of file PclTransformTool.cpp.
getOutput()
void PclTransformTool::getOutput (std::vector< ccHObject * > & out) override virtual
Implements ecvGenericTransformTool.
Definition at line 298 of file PclTransformTool.cpp.
reset()
void PclTransformTool::reset (void) override virtual
Implements ecvGenericTransformTool.
Definition at line 158 of file PclTransformTool.cpp.
References ecvDisplayTools::UpdateScreen().
Referenced by stop().
setInputData()
bool PclTransformTool::setInputData (ccHObject * entity, int viewport = 0) override virtual
Reimplemented from ecvGenericTransformTool.
Definition at line 62 of file PclTransformTool.cpp.
References addActors(), ecvGenericTransformTool::getAssociatedEntity(), and ecvGenericTransformTool::setInputData().
setRotationMode()
void PclTransformTool::setRotationMode (RotationMode mode) virtual
Implements ecvGenericTransformTool.
Definition at line 227 of file PclTransformTool.cpp.
References ecvGenericTransformTool::R_X, ecvGenericTransformTool::R_XYZ, ecvGenericTransformTool::R_Y, ecvGenericTransformTool::R_Z, and CVLog::Warning().
setScaleEnabled()
void PclTransformTool::setScaleEnabled (bool state) virtual
Implements ecvGenericTransformTool.
Definition at line 261 of file PclTransformTool.cpp.
References CVLog::Warning().
setShearEnabled()
void PclTransformTool::setShearEnabled (bool state) virtual
Implements ecvGenericTransformTool.
Definition at line 272 of file PclTransformTool.cpp.
References CVLog::Warning().
setTranlationMode()
void PclTransformTool::setTranlationMode (TranslationMOde mode) virtual
Implements ecvGenericTransformTool.
Definition at line 173 of file PclTransformTool.cpp.
References ecvGenericTransformTool::T_NONE, ecvGenericTransformTool::T_X, ecvGenericTransformTool::T_XY, ecvGenericTransformTool::T_XYZ, ecvGenericTransformTool::T_XZ, ecvGenericTransformTool::T_Y, ecvGenericTransformTool::T_Z, ecvGenericTransformTool::T_ZY, and CVLog::Warning().
setVisualizer()
void PclTransformTool::setVisualizer (ecvGenericVisualizer3D * viewer = nullptr) override virtual
initialize
Implements ecvGenericTransformTool.
Definition at line 51 of file PclTransformTool.cpp.
References CVLog::Warning().
Referenced by PclTransformTool().
showInteractor()
void PclTransformTool::showInteractor (bool state) override virtual
Implements ecvGenericTransformTool.
Definition at line 100 of file PclTransformTool.cpp.
References CVLog::Warning().
start()
bool PclTransformTool::start (void) override virtual
Implements ecvGenericTransformTool.
Definition at line 115 of file PclTransformTool.cpp.
References PclUtils::PCLVis::getRenderWindowInteractor(), VTK_CREATE, and VtkUtils::vtkInitOnce().
stop()
void PclTransformTool::stop () override virtual
Implements ecvGenericTransformTool.
Definition at line 146 of file PclTransformTool.cpp.
References reset().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/TransformTools/PclTransformTool.h
/root/ACloudViewer/libs/PCLEngine/Tools/TransformTools/PclTransformTool.cpp