ACloudViewer: cloudViewer::visualization::ColorMap Class Reference
cloudViewer::visualization::ColorMap Class Reference abstract
#include <ColorMap.h>
Public Types
enum class ColorMapOption {
Gray = 0 , Jet = 1 , Summer = 2 , Winter = 3 ,
Hot = 4
}
Public Member Functions
ColorMap ()
virtual ~ColorMap ()
virtual Eigen::Vector3d GetColor (double value) const =0
Function to get a color from a value in [0..1].
Protected Member Functions
double Interpolate (double value, double y0, double x0, double y1, double x1) const
Eigen::Vector3d Interpolate (double value, const Eigen::Vector3d &y0, double x0, const Eigen::Vector3d &y1, double x1) const
Detailed Description
Definition at line 16 of file ColorMap.h.
Member Enumeration Documentation
ColorMapOption
enum cloudViewer::visualization::ColorMap::ColorMapOption strong
Enumerator
Gray
Jet
Summer
Winter
Hot
Definition at line 18 of file ColorMap.h.
Constructor & Destructor Documentation
ColorMap()
cloudViewer::visualization::ColorMap::ColorMap () inline
Definition at line 27 of file ColorMap.h.
~ColorMap()
virtual cloudViewer::visualization::ColorMap::~ColorMap () inline virtual
Definition at line 28 of file ColorMap.h.
Member Function Documentation
GetColor()
virtual Eigen::Vector3d cloudViewer::visualization::ColorMap::GetColor (double value) const pure virtual
Function to get a color from a value in [0..1].
Implemented in cloudViewer::visualization::ColorMapHot, cloudViewer::visualization::ColorMapWinter, cloudViewer::visualization::ColorMapSummer, cloudViewer::visualization::ColorMapJet, and cloudViewer::visualization::ColorMapGray.
Interpolate() [1/2]
Eigen::Vector3d cloudViewer::visualization::ColorMap::Interpolate (double value, const Eigen::Vector3d & y0, double x0, const Eigen::Vector3d & y1, double x1) const inline protected
Definition at line 41 of file ColorMap.h.
Interpolate() [2/2]
double cloudViewer::visualization::ColorMap::Interpolate (double value, double y0, double x0, double y1, double x1) const inline protected
Definition at line 35 of file ColorMap.h.
Referenced by cloudViewer::visualization::ColorMapSummer::GetColor(), cloudViewer::visualization::ColorMapWinter::GetColor(), cloudViewer::visualization::ColorMapHot::GetColor(), and cloudViewer::visualization::ColorMapJet::JetBase().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/utility/ColorMap.h