ACloudViewer: cloudViewer::geometry::Qhull Class Reference
cloudViewer::geometry::Qhull Class Reference
#include <ecvQhull.h>
Static Public Member Functions
static std::tuple< std::shared_ptr< ccMesh >, std::vector< size_t > > ComputeConvexHull (const std::vector< Eigen::Vector3d > &points)
static std::tuple< std::shared_ptr< ccMesh >, std::vector< size_t > > ComputeConvexHull (const std::vector< CCVector3 > &points)
static std::tuple< std::shared_ptr< TetraMesh >, std::vector< size_t > > ComputeDelaunayTetrahedralization (const std::vector< Eigen::Vector3d > &points)
static std::tuple< std::shared_ptr< TetraMesh >, std::vector< size_t > > ComputeDelaunayTetrahedralization (const std::vector< CCVector3 > &points)
Detailed Description
Definition at line 21 of file ecvQhull.h.
Member Function Documentation
ComputeConvexHull() [1/2]
std::tuple< std::shared_ptr< ccMesh >, std::vector< size_t > > cloudViewer::geometry::Qhull::ComputeConvexHull (const std::vector< CCVector3 > & points) static
Definition at line 39 of file ecvQhull.cpp.
References cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, normals, points, ccObject::setEnabled(), ccObject::setLocked(), ccPointCloud::shrinkToFit(), and cloudViewer::PointCloudTpl< T >::size().
ComputeConvexHull() [2/2]
std::tuple< std::shared_ptr< ccMesh >, std::vector< size_t > > cloudViewer::geometry::Qhull::ComputeConvexHull (const std::vector< Eigen::Vector3d > & points) static
Definition at line 34 of file ecvQhull.cpp.
References Vector3Tpl< PointCoordinateType >::fromArrayContainer(), and points.
Referenced by ccMesh::ComputeConvexHull(), cloudViewer::geometry::ecvMeshBase::ComputeConvexHull(), ccPointCloud::ComputeConvexHull(), ecvOrientedBBox::CreateFromPoints(), and ccPointCloud::HiddenPointRemoval().
ComputeDelaunayTetrahedralization() [1/2]
std::tuple< std::shared_ptr< TetraMesh >, std::vector< size_t > > cloudViewer::geometry::Qhull::ComputeDelaunayTetrahedralization (const std::vector< CCVector3 > & points) static
Definition at line 127 of file ecvQhull.cpp.
References ComputeDelaunayTetrahedralization(), Vector3Tpl< PointCoordinateType >::fromArrayContainer(), and points.
ComputeDelaunayTetrahedralization() [2/2]
std::tuple< std::shared_ptr< TetraMesh >, std::vector< size_t > > cloudViewer::geometry::Qhull::ComputeDelaunayTetrahedralization (const std::vector< Eigen::Vector3d > & points) static
Definition at line 133 of file ecvQhull.cpp.
References CVLog::Error(), points, and cloudViewer::geometry::TetraMesh::tetras_.
Referenced by ComputeDelaunayTetrahedralization(), cloudViewer::geometry::TetraMesh::CreateFromPointCloud(), and ccMesh::CreateFromPointCloudAlphaShape().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/ecvQhull.h
/root/ACloudViewer/libs/CV_db/src/ecvQhull.cpp