ACloudViewer: colmap::mvs::Workspace Class Reference
colmap::mvs::Workspace Class Reference
#include <workspace.h>
Classes
struct Options
Public Member Functions
Workspace (const Options &options)
virtual void Load (const std::vector< std::string > &image_names)
const Options & GetOptions () const
const Model & GetModel () const
virtual const Bitmap & GetBitmap (const int image_idx)
virtual const DepthMap & GetDepthMap (const int image_idx)
virtual const NormalMap & GetNormalMap (const int image_idx)
std::string GetBitmapPath (const int image_idx) const
std::string GetDepthMapPath (const int image_idx) const
std::string GetNormalMapPath (const int image_idx) const
bool HasBitmap (const int image_idx) const
bool HasDepthMap (const int image_idx) const
bool HasNormalMap (const int image_idx) const
Protected Member Functions
std::string GetFileName (const int image_idx) const
Protected Attributes
Options options_
Model model_
Detailed Description
Definition at line 21 of file workspace.h.
Constructor & Destructor Documentation
Workspace()
colmap::mvs::Workspace::Workspace (const Options & options)
Definition at line 41 of file workspace.cc.
Member Function Documentation
GetBitmap()
const Bitmap & colmap::mvs::Workspace::GetBitmap (const int image_idx) virtual
Reimplemented in colmap::mvs::CachedWorkspace.
Definition at line 119 of file workspace.cc.
GetBitmapPath()
std::string colmap::mvs::Workspace::GetBitmapPath (const int image_idx) const
Definition at line 131 of file workspace.cc.
References colmap::mvs::Model::images, and model_.
Referenced by colmap::mvs::CachedWorkspace::GetBitmap(), HasBitmap(), and Load().
GetDepthMap()
const DepthMap & colmap::mvs::Workspace::GetDepthMap (const int image_idx) virtual
Reimplemented in colmap::mvs::CachedWorkspace.
Definition at line 123 of file workspace.cc.
GetDepthMapPath()
std::string colmap::mvs::Workspace::GetDepthMapPath (const int image_idx) const
Definition at line 135 of file workspace.cc.
References GetFileName().
Referenced by colmap::mvs::CachedWorkspace::GetDepthMap(), HasDepthMap(), and Load().
GetFileName()
std::string colmap::mvs::Workspace::GetFileName (const int image_idx) const protected
Definition at line 57 of file workspace.cc.
References colmap::mvs::Model::GetImageName(), colmap::mvs::Workspace::Options::input_type, model_, options_, and colmap::StringPrintf().
Referenced by GetDepthMapPath(), and GetNormalMapPath().
GetModel()
const Model& colmap::mvs::Workspace::GetModel () const inline
Definition at line 50 of file workspace.h.
References model_.
Referenced by colmap::mvs::ImportPMVSWorkspace().
GetNormalMap()
const NormalMap & colmap::mvs::Workspace::GetNormalMap (const int image_idx) virtual
Reimplemented in colmap::mvs::CachedWorkspace.
Definition at line 127 of file workspace.cc.
GetNormalMapPath()
std::string colmap::mvs::Workspace::GetNormalMapPath (const int image_idx) const
Definition at line 139 of file workspace.cc.
References GetFileName().
Referenced by colmap::mvs::CachedWorkspace::GetNormalMap(), HasNormalMap(), and Load().
GetOptions()
const Options& colmap::mvs::Workspace::GetOptions () const inline
Definition at line 48 of file workspace.h.
References options_.
Referenced by colmap::mvs::ImportPMVSWorkspace().
HasBitmap()
bool colmap::mvs::Workspace::HasBitmap (const int image_idx) const
Definition at line 143 of file workspace.cc.
References colmap::ExistsFile(), and GetBitmapPath().
Referenced by Load().
HasDepthMap()
bool colmap::mvs::Workspace::HasDepthMap (const int image_idx) const
Definition at line 147 of file workspace.cc.
References colmap::ExistsFile(), and GetDepthMapPath().
Referenced by Load().
HasNormalMap()
bool colmap::mvs::Workspace::HasNormalMap (const int image_idx) const
Definition at line 151 of file workspace.cc.
References colmap::ExistsFile(), and GetNormalMapPath().
Load()
void colmap::mvs::Workspace::Load (const std::vector< std::string > & image_names) virtual
Reimplemented in colmap::mvs::CachedWorkspace.
Definition at line 63 of file workspace.cc.
References colmap::ThreadPool::AddTask(), QtCompat::endl(), GetBitmapPath(), GetDepthMapPath(), colmap::GetEffectiveNumThreads(), colmap::mvs::Model::GetImageIdx(), GetNormalMapPath(), HasBitmap(), HasDepthMap(), height, colmap::mvs::Workspace::Options::image_as_rgb, colmap::mvs::Model::images, colmap::mvs::Workspace::Options::max_image_size, model_, colmap::mvs::Workspace::Options::num_threads, options_, colmap::Timer::PrintMinutes(), colmap::Timer::Start(), colmap::StringPrintf(), colmap::ThreadPool::Wait(), and width.
Member Data Documentation
model_
Model colmap::mvs::Workspace::model_ protected
Definition at line 71 of file workspace.h.
Referenced by colmap::mvs::CachedWorkspace::GetBitmap(), GetBitmapPath(), colmap::mvs::CachedWorkspace::GetDepthMap(), GetFileName(), GetModel(), colmap::mvs::CachedWorkspace::GetNormalMap(), and Load().
options_
Options colmap::mvs::Workspace::options_ protected
Definition at line 70 of file workspace.h.
Referenced by colmap::mvs::CachedWorkspace::GetBitmap(), colmap::mvs::CachedWorkspace::GetDepthMap(), GetFileName(), colmap::mvs::CachedWorkspace::GetNormalMap(), GetOptions(), and Load().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/mvs/workspace.h
/root/ACloudViewer/libs/Reconstruction/src/mvs/workspace.cc