ACloudViewer: ecvAxesGridDialog Class Reference
ecvAxesGridDialog Class Reference
ParaView-style Axes Grid Properties Dialog.
#include <ecvAxesGridDialog.h>
Signals
void propertiesChanged ()
void applyRequested ()
Public Member Functions
ecvAxesGridDialog (const QString &title, QWidget *parent=nullptr)
~ecvAxesGridDialog () override
QString getXTitle () const
void setXTitle (const QString &title)
QString getYTitle () const
void setYTitle (const QString &title)
QString getZTitle () const
void setZTitle (const QString &title)
QColor getGridColor () const
void setGridColor (const QColor &color)
bool getShowGrid () const
void setShowGrid (bool show)
bool getXAxisUseCustomLabels () const
void setXAxisUseCustomLabels (bool use)
QList< QPair< double, QString > > getXAxisCustomLabels () const
void setXAxisCustomLabels (const QList< QPair< double, QString >> &labels)
bool getYAxisUseCustomLabels () const
void setYAxisUseCustomLabels (bool use)
QList< QPair< double, QString > > getYAxisCustomLabels () const
void setYAxisCustomLabels (const QList< QPair< double, QString >> &labels)
bool getZAxisUseCustomLabels () const
void setZAxisUseCustomLabels (bool use)
QList< QPair< double, QString > > getZAxisCustomLabels () const
void setZAxisCustomLabels (const QList< QPair< double, QString >> &labels)
bool getUseCustomBounds () const
void setUseCustomBounds (bool use)
double getXMin () const
void setXMin (double value)
double getXMax () const
void setXMax (double value)
double getYMin () const
void setYMin (double value)
double getYMax () const
void setYMax (double value)
double getZMin () const
void setZMin (double value)
double getZMax () const
void setZMax (double value)
QColor getColor () const
void setColor (const QColor &color)
double getLineWidth () const
void setLineWidth (double)
double getOpacity () const
void setOpacity (double)
bool getShowLabels () const
void setShowLabels (bool)
Detailed Description
ParaView-style Axes Grid Properties Dialog.
Complete implementation matching ParaView's GridAxes3DActor properties panel. Features:
Title Texts (X/Y/Z)
Face Properties (Grid Color, Show Grid)
X/Y/Z Axis Label Properties with Custom Labels support
Bounds (Use Custom Bounds)
Real-time preview via Apply button
Non-modal dialog
Definition at line 37 of file ecvAxesGridDialog.h.
Constructor & Destructor Documentation
ecvAxesGridDialog()
ecvAxesGridDialog::ecvAxesGridDialog (const QString & title, QWidget * parent = nullptr) explicit
Definition at line 24 of file ecvAxesGridDialog.cpp.
~ecvAxesGridDialog()
ecvAxesGridDialog::~ecvAxesGridDialog () override default
Member Function Documentation
applyRequested
void ecvAxesGridDialog::applyRequested () signal
getColor()
QColor ecvAxesGridDialog::getColor () const inline
Definition at line 108 of file ecvAxesGridDialog.h.
References getGridColor().
getGridColor()
QColor ecvAxesGridDialog::getGridColor () const
Definition at line 315 of file ecvAxesGridDialog.cpp.
Referenced by getColor().
getLineWidth()
double ecvAxesGridDialog::getLineWidth () const inline
Definition at line 110 of file ecvAxesGridDialog.h.
getOpacity()
double ecvAxesGridDialog::getOpacity () const inline
Definition at line 112 of file ecvAxesGridDialog.h.
getShowGrid()
bool ecvAxesGridDialog::getShowGrid () const
Definition at line 320 of file ecvAxesGridDialog.cpp.
getShowLabels()
bool ecvAxesGridDialog::getShowLabels () const inline
Definition at line 114 of file ecvAxesGridDialog.h.
getUseCustomBounds()
bool ecvAxesGridDialog::getUseCustomBounds () const
Definition at line 369 of file ecvAxesGridDialog.cpp.
getXAxisCustomLabels()
QList< QPair< double, QString > > ecvAxesGridDialog::getXAxisCustomLabels () const
Definition at line 333 of file ecvAxesGridDialog.cpp.
References ecvCustomLabelsWidget::getLabels().
getXAxisUseCustomLabels()
bool ecvAxesGridDialog::getXAxisUseCustomLabels () const
Definition at line 327 of file ecvAxesGridDialog.cpp.
getXMax()
double ecvAxesGridDialog::getXMax () const
Definition at line 385 of file ecvAxesGridDialog.cpp.
getXMin()
double ecvAxesGridDialog::getXMin () const
Definition at line 381 of file ecvAxesGridDialog.cpp.
getXTitle()
QString ecvAxesGridDialog::getXTitle () const
Definition at line 302 of file ecvAxesGridDialog.cpp.
getYAxisCustomLabels()
QList< QPair< double, QString > > ecvAxesGridDialog::getYAxisCustomLabels () const
Definition at line 347 of file ecvAxesGridDialog.cpp.
References ecvCustomLabelsWidget::getLabels().
getYAxisUseCustomLabels()
bool ecvAxesGridDialog::getYAxisUseCustomLabels () const
Definition at line 341 of file ecvAxesGridDialog.cpp.
getYMax()
double ecvAxesGridDialog::getYMax () const
Definition at line 393 of file ecvAxesGridDialog.cpp.
getYMin()
double ecvAxesGridDialog::getYMin () const
Definition at line 389 of file ecvAxesGridDialog.cpp.
getYTitle()
QString ecvAxesGridDialog::getYTitle () const
Definition at line 306 of file ecvAxesGridDialog.cpp.
getZAxisCustomLabels()
QList< QPair< double, QString > > ecvAxesGridDialog::getZAxisCustomLabels () const
Definition at line 361 of file ecvAxesGridDialog.cpp.
References ecvCustomLabelsWidget::getLabels().
getZAxisUseCustomLabels()
bool ecvAxesGridDialog::getZAxisUseCustomLabels () const
Definition at line 355 of file ecvAxesGridDialog.cpp.
getZMax()
double ecvAxesGridDialog::getZMax () const
Definition at line 401 of file ecvAxesGridDialog.cpp.
getZMin()
double ecvAxesGridDialog::getZMin () const
Definition at line 397 of file ecvAxesGridDialog.cpp.
getZTitle()
QString ecvAxesGridDialog::getZTitle () const
Definition at line 310 of file ecvAxesGridDialog.cpp.
propertiesChanged
void ecvAxesGridDialog::propertiesChanged () signal
setColor()
void ecvAxesGridDialog::setColor (const QColor & color) inline
Definition at line 109 of file ecvAxesGridDialog.h.
References color, and setGridColor().
setGridColor()
void ecvAxesGridDialog::setGridColor (const QColor & color)
Definition at line 316 of file ecvAxesGridDialog.cpp.
References color.
Referenced by setColor().
setLineWidth()
void ecvAxesGridDialog::setLineWidth (double) inline
Definition at line 111 of file ecvAxesGridDialog.h.
setOpacity()
void ecvAxesGridDialog::setOpacity (double) inline
Definition at line 113 of file ecvAxesGridDialog.h.
setShowGrid()
void ecvAxesGridDialog::setShowGrid (bool show)
Definition at line 323 of file ecvAxesGridDialog.cpp.
setShowLabels()
void ecvAxesGridDialog::setShowLabels (bool) inline
Definition at line 115 of file ecvAxesGridDialog.h.
setUseCustomBounds()
void ecvAxesGridDialog::setUseCustomBounds (bool use)
Definition at line 372 of file ecvAxesGridDialog.cpp.
setXAxisCustomLabels()
void ecvAxesGridDialog::setXAxisCustomLabels (const QList< QPair< double, QString >> & labels)
Definition at line 336 of file ecvAxesGridDialog.cpp.
References ecvCustomLabelsWidget::setLabels().
setXAxisUseCustomLabels()
void ecvAxesGridDialog::setXAxisUseCustomLabels (bool use)
Definition at line 330 of file ecvAxesGridDialog.cpp.
setXMax()
void ecvAxesGridDialog::setXMax (double value)
Definition at line 386 of file ecvAxesGridDialog.cpp.
setXMin()
void ecvAxesGridDialog::setXMin (double value)
Definition at line 382 of file ecvAxesGridDialog.cpp.
setXTitle()
void ecvAxesGridDialog::setXTitle (const QString & title)
Definition at line 303 of file ecvAxesGridDialog.cpp.
setYAxisCustomLabels()
void ecvAxesGridDialog::setYAxisCustomLabels (const QList< QPair< double, QString >> & labels)
Definition at line 350 of file ecvAxesGridDialog.cpp.
References ecvCustomLabelsWidget::setLabels().
setYAxisUseCustomLabels()
void ecvAxesGridDialog::setYAxisUseCustomLabels (bool use)
Definition at line 344 of file ecvAxesGridDialog.cpp.
setYMax()
void ecvAxesGridDialog::setYMax (double value)
Definition at line 394 of file ecvAxesGridDialog.cpp.
setYMin()
void ecvAxesGridDialog::setYMin (double value)
Definition at line 390 of file ecvAxesGridDialog.cpp.
setYTitle()
void ecvAxesGridDialog::setYTitle (const QString & title)
Definition at line 307 of file ecvAxesGridDialog.cpp.
setZAxisCustomLabels()
void ecvAxesGridDialog::setZAxisCustomLabels (const QList< QPair< double, QString >> & labels)
Definition at line 364 of file ecvAxesGridDialog.cpp.
References ecvCustomLabelsWidget::setLabels().
setZAxisUseCustomLabels()
void ecvAxesGridDialog::setZAxisUseCustomLabels (bool use)
Definition at line 358 of file ecvAxesGridDialog.cpp.
setZMax()
void ecvAxesGridDialog::setZMax (double value)
Definition at line 402 of file ecvAxesGridDialog.cpp.
setZMin()
void ecvAxesGridDialog::setZMin (double value)
Definition at line 398 of file ecvAxesGridDialog.cpp.
setZTitle()
void ecvAxesGridDialog::setZTitle (const QString & title)
Definition at line 311 of file ecvAxesGridDialog.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/db_tree/ecvAxesGridDialog.h
/root/ACloudViewer/app/db_tree/ecvAxesGridDialog.cpp