ACloudViewer: PclUtils::renders::TextureLoader Class Reference
PclUtils::renders::TextureLoader Class Reference
Utility class for loading textures from various sources.
#include <TextureLoader.h>
Static Public Member Functions
static int LoadFromPCLMaterial (const pcl::TexMaterial &tex_mat, vtkTexture *vtk_tex)
Load texture from pcl::TexMaterial.
static int LoadFromCCMaterial (ccMaterial::CShared material, vtkTexture *vtk_tex)
Load texture from ccMaterial.
Detailed Description
Utility class for loading textures from various sources.
Definition at line 24 of file TextureLoader.h.
Member Function Documentation
LoadFromCCMaterial()
int PclUtils::renders::TextureLoader::LoadFromCCMaterial (ccMaterial::CShared material, vtkTexture * vtk_tex) static
Load texture from ccMaterial.
Parameters
material ccMaterial object
vtk_tex VTK texture object to load into
Returns
1 on success, -1 on failure
Definition at line 155 of file TextureLoader.cpp.
References cloudViewer::utility::filesystem::DirectoryExists(), cloudViewer::utility::filesystem::FileExists(), CVTools::FromQString(), cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), cloudViewer::utility::filesystem::GetFileParentDirectory(), ccMaterial::GetTexture(), cloudViewer::utility::filesystem::IsDirectory(), cloudViewer::utility::filesystem::IsFile(), cloudViewer::utility::filesystem::ListFilesInDirectory(), cloudViewer::t::geometry::path, cloudViewer::utility::ToUpper(), and CVLog::Warning().
LoadFromPCLMaterial()
int PclUtils::renders::TextureLoader::LoadFromPCLMaterial (const pcl::TexMaterial & tex_mat, vtkTexture * vtk_tex) static
Load texture from pcl::TexMaterial.
Parameters
tex_mat PCL texture material
vtk_tex VTK texture object to load into
Returns
1 on success, -1 on failure
Definition at line 32 of file TextureLoader.cpp.
References cloudViewer::utility::filesystem::DirectoryExists(), cloudViewer::utility::filesystem::FileExists(), cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), cloudViewer::utility::filesystem::GetFileParentDirectory(), ccMaterial::GetTexture(), cloudViewer::utility::filesystem::IsDirectory(), cloudViewer::utility::filesystem::IsFile(), cloudViewer::utility::filesystem::ListFilesInDirectory(), cloudViewer::t::geometry::path, cloudViewer::utility::ToUpper(), and CVLog::Warning().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/PclUtils/renders/utils/TextureLoader.h
/root/ACloudViewer/libs/PCLEngine/PclUtils/renders/utils/TextureLoader.cpp