ACloudViewer: ccPointPickingGenericInterface Class Reference
ccPointPickingGenericInterface Class Reference abstract
#include <ecvPointPickingGenericInterface.h>
Public Member Functions
ccPointPickingGenericInterface (ccPickingHub *pickingHub, QWidget *parent=nullptr)
Default constructor.
~ccPointPickingGenericInterface () override=default
Destructor.
bool linkWith (QWidget *win) override
Links the overlay dialog with a MDI window.
bool start () override
Starts process.
void stop (bool state) override
Stops process/dialog.
void onItemPicked (const PickedItem &pi) override
Inherited from ccPickingListener.
Public Member Functions inherited from ccOverlayDialog
ccOverlayDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::FramelessWindowHint|Qt::Tool)
Default constructor.
~ccOverlayDialog () override
Destructor.
void reject () override
void addOverridenShortcut (Qt::Key key)
bool started () const
Returns whether the tool is currently started or not.
Public Member Functions inherited from ccPickingListener
virtual ~ccPickingListener ()=default
Protected Member Functions
virtual void processPickedPoint (ccPointCloud *cloud, unsigned pointIndex, int x, int y)=0
Generic method to process picked points.
Protected Member Functions inherited from ccOverlayDialog
bool eventFilter (QObject *obj, QEvent *e) override
Protected Attributes
ccPickingHub * m_pickingHub
Picking hub.
Protected Attributes inherited from ccOverlayDialog
QWidget * m_associatedWin
Associated (MDI) window.
bool m_processing
Running/processing state.
QList< int > m_overriddenKeys
Overridden keys.
Additional Inherited Members
Signals inherited from ccOverlayDialog
void processFinished (bool accepted)
Signal emitted when process is finished.
void shortcutTriggered (int key)
Signal emitted when an overridden key shortcut is pressed.
void shown ()
Signal emitted when a 'show' event is detected.
Protected Slots inherited from ccOverlayDialog
virtual void onLinkedWindowDeletion (QObject *object=nullptr)
Slot called when the linked window is deleted (calls 'onClose')
Detailed Description
Generic interface for any dialog/graphical interactor that relies on point picking.
Definition at line 28 of file ecvPointPickingGenericInterface.h.
Constructor & Destructor Documentation
ccPointPickingGenericInterface()
ccPointPickingGenericInterface::ccPointPickingGenericInterface (ccPickingHub * pickingHub, QWidget * parent = nullptr) explicit
Default constructor.
Definition at line 24 of file ecvPointPickingGenericInterface.cpp.
References m_pickingHub.
~ccPointPickingGenericInterface()
ccPointPickingGenericInterface::~ccPointPickingGenericInterface () override default
Destructor.
Member Function Documentation
linkWith()
bool ccPointPickingGenericInterface::linkWith (QWidget * win) override virtual
Links the overlay dialog with a MDI window.
Warning: link can't be modified while dialog is displayed/process is running!
Returns
success
Reimplemented from ccOverlayDialog.
Reimplemented in ccPointPropertiesDlg.
Definition at line 30 of file ecvPointPickingGenericInterface.cpp.
References ccOverlayDialog::linkWith(), m_pickingHub, and ccPickingHub::removeListener().
Referenced by ccPointPropertiesDlg::linkWith().
onItemPicked()
void ccPointPickingGenericInterface::onItemPicked (const PickedItem & pi) override virtual
Inherited from ccPickingListener.
Implements ccPickingListener.
Definition at line 73 of file ecvPointPickingGenericInterface.cpp.
References ccPickingListener::PickedItem::clickPoint, ccPickingListener::PickedItem::entity, ccObject::isKindOf(), ccPickingListener::PickedItem::itemIndex, ccOverlayDialog::m_processing, CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, processPickedPoint(), and CVLog::Warning().
processPickedPoint()
virtual void ccPointPickingGenericInterface::processPickedPoint (ccPointCloud * cloud, unsigned pointIndex, int x, int y) protected pure virtual
Generic method to process picked points.
Parameters
cloud picked point cloud
pointIndex point index in cloud
x picked pixel X position
y picked pixel Y position
Implemented in ccPointPropertiesDlg, and ccPointListPickingDlg.
Referenced by onItemPicked().
start()
bool ccPointPickingGenericInterface::start () override virtual
Starts process.
Returns
success
Reimplemented from ccOverlayDialog.
Reimplemented in ccPointPropertiesDlg.
Definition at line 45 of file ecvPointPickingGenericInterface.cpp.
References ccPickingHub::addListener(), CVLog::Error(), m_pickingHub, ecvDisplayTools::POINT_PICKING, and ccOverlayDialog::start().
Referenced by ccPointPropertiesDlg::start().
stop()
void ccPointPickingGenericInterface::stop (bool accepted) override virtual
Stops process/dialog.
Automatically emits the 'processFinished' signal (with input state as argument).
Parameters
accepted process/dialog result
Reimplemented from ccOverlayDialog.
Reimplemented in ccPointPropertiesDlg.
Definition at line 64 of file ecvPointPickingGenericInterface.cpp.
References m_pickingHub, ccPickingHub::removeListener(), and ccOverlayDialog::stop().
Referenced by ccPointListPickingDlg::applyAndExit(), ccPointListPickingDlg::cancelAndExit(), and ccPointPropertiesDlg::stop().
Member Data Documentation
m_pickingHub
ccPickingHub* ccPointPickingGenericInterface::m_pickingHub protected
Picking hub.
Definition at line 60 of file ecvPointPickingGenericInterface.h.
Referenced by ccPointPickingGenericInterface(), linkWith(), start(), and stop().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvPointPickingGenericInterface.h
/root/ACloudViewer/app/ecvPointPickingGenericInterface.cpp