ACloudViewer: sfEditDlg Class Reference
sfEditDlg Class Reference
GUI scalar field interactor for properties list dialog.
#include <sfEditDlg.h>
Signals
void entitySFHasChanged ()
Signal emitted when the SF display parameters have changed.
Public Member Functions
sfEditDlg (QWidget *parent=0)
Default constructor.
~sfEditDlg ()
void fillDialogWith (ccScalarField *sf)
Updates dialog with a given scalar field.
void minValSBChanged (double)
void maxValSBChanged (double)
void minSatSBChanged (double)
void maxSatSBChanged (double)
void minValHistoChanged (double)
void maxValHistoChanged (double)
void minSatHistoChanged (double)
void maxSatHistoChanged (double)
void nanInGrayChanged (bool)
void alwaysShow0Changed (bool)
void symmetricalScaleChanged (bool)
void logScaleChanged (bool)
Protected Member Functions
double dispSpin2slider (double val) const
double satSpin2slider (double val) const
double dispSlider2spin (int pos) const
double satSlider2spin (int pos) const
Protected Attributes
ccScalarField * m_associatedSF
Associated scalar field.
ccHistogramWindow * m_associatedSFHisto
Associated scalar field histogram.
Ui::SFEditDlg * m_ui
Detailed Description
GUI scalar field interactor for properties list dialog.
Definition at line 21 of file sfEditDlg.h.
Constructor & Destructor Documentation
sfEditDlg()
sfEditDlg::sfEditDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 29 of file sfEditDlg.cpp.
References ccHistogramWindow::All, alwaysShow0Changed(), logScaleChanged(), m_associatedSFHisto, m_ui, maxSatHistoChanged(), maxSatSBChanged(), maxValHistoChanged(), maxValSBChanged(), minSatHistoChanged(), minSatSBChanged(), minValHistoChanged(), minValSBChanged(), nanInGrayChanged(), ccHistogramWindow::setSFInteractionMode(), QCPAxis::setTickLabels(), ccHistogramWindow::sfMaxDispValChanged(), ccHistogramWindow::sfMaxSatValChanged(), ccHistogramWindow::sfMinDispValChanged(), ccHistogramWindow::sfMinSatValChanged(), symmetricalScaleChanged(), QCPAxis::ticker(), QCustomPlot::xAxis, and QCustomPlot::yAxis.
~sfEditDlg()
sfEditDlg::~sfEditDlg ()
Definition at line 89 of file sfEditDlg.cpp.
References m_ui.
Member Function Documentation
alwaysShow0Changed()
void sfEditDlg::alwaysShow0Changed (bool state)
Definition at line 305 of file sfEditDlg.cpp.
References ccScalarField::alwaysShowZero(), entitySFHasChanged(), ccScalarField::isZeroAlwaysShown(), and m_associatedSF.
Referenced by sfEditDlg().
dispSlider2spin()
double sfEditDlg::dispSlider2spin (int pos) const protected
dispSpin2slider()
double sfEditDlg::dispSpin2slider (double val) const protected
entitySFHasChanged
void sfEditDlg::entitySFHasChanged () signal
Signal emitted when the SF display parameters have changed.
Referenced by alwaysShow0Changed(), ccPropertiesTreeDelegate::createEditor(), logScaleChanged(), maxSatHistoChanged(), maxSatSBChanged(), maxValHistoChanged(), maxValSBChanged(), minSatHistoChanged(), minSatSBChanged(), minValHistoChanged(), minValSBChanged(), nanInGrayChanged(), and symmetricalScaleChanged().
fillDialogWith()
void sfEditDlg::fillDialogWith (ccScalarField * sf)
Updates dialog with a given scalar field.
Definition at line 91 of file sfEditDlg.cpp.
References ccScalarField::areNaNValuesShownInGrey(), ccScalarField::displayRange(), ccHistogramWindow::fromSF(), ccScalarField::getColorScale(), ccScalarField::getHistogram(), ccScalarField::isZeroAlwaysShown(), ccScalarField::logScale(), m_associatedSF, m_associatedSFHisto, m_ui, ccScalarField::Range::max(), ccScalarField::Range::maxRange(), ccScalarField::Range::min(), ccScalarField::saturationRange(), SPIN_BOX_STEPS, ccScalarField::Range::start(), ccScalarField::Range::stop(), and ccScalarField::symmetricalScale().
Referenced by logScaleChanged(), ccPropertiesTreeDelegate::setEditorData(), and symmetricalScaleChanged().
logScaleChanged()
void sfEditDlg::logScaleChanged (bool state)
Definition at line 331 of file sfEditDlg.cpp.
References entitySFHasChanged(), fillDialogWith(), ccScalarField::logScale(), m_associatedSF, m_associatedSFHisto, ccHistogramWindow::refresh(), and ccScalarField::setLogScale().
Referenced by sfEditDlg().
maxSatHistoChanged()
void sfEditDlg::maxSatHistoChanged (double val)
Definition at line 282 of file sfEditDlg.cpp.
References entitySFHasChanged(), m_associatedSF, and m_ui.
Referenced by sfEditDlg().
maxSatSBChanged()
void sfEditDlg::maxSatSBChanged (double val)
Definition at line 236 of file sfEditDlg.cpp.
References entitySFHasChanged(), m_associatedSF, m_associatedSFHisto, and ccHistogramWindow::setMaxSatValue().
Referenced by sfEditDlg().
maxValHistoChanged()
void sfEditDlg::maxValHistoChanged (double val)
Definition at line 258 of file sfEditDlg.cpp.
References entitySFHasChanged(), m_associatedSF, and m_ui.
Referenced by sfEditDlg().
maxValSBChanged()
void sfEditDlg::maxValSBChanged (double val)
Definition at line 216 of file sfEditDlg.cpp.
References entitySFHasChanged(), m_associatedSF, m_associatedSFHisto, and ccHistogramWindow::setMaxDispValue().
Referenced by sfEditDlg().
minSatHistoChanged()
void sfEditDlg::minSatHistoChanged (double val)
Definition at line 270 of file sfEditDlg.cpp.
References entitySFHasChanged(), m_associatedSF, and m_ui.
Referenced by sfEditDlg().
minSatSBChanged()
void sfEditDlg::minSatSBChanged (double val)
Definition at line 226 of file sfEditDlg.cpp.
References entitySFHasChanged(), m_associatedSF, m_associatedSFHisto, and ccHistogramWindow::setMinSatValue().
Referenced by sfEditDlg().
minValHistoChanged()
void sfEditDlg::minValHistoChanged (double val)
Definition at line 246 of file sfEditDlg.cpp.
References entitySFHasChanged(), m_associatedSF, and m_ui.
Referenced by sfEditDlg().
minValSBChanged()
void sfEditDlg::minValSBChanged (double val)
Definition at line 206 of file sfEditDlg.cpp.
References entitySFHasChanged(), m_associatedSF, m_associatedSFHisto, and ccHistogramWindow::setMinDispValue().
Referenced by sfEditDlg().
nanInGrayChanged()
void sfEditDlg::nanInGrayChanged (bool state)
Definition at line 294 of file sfEditDlg.cpp.
References ccScalarField::areNaNValuesShownInGrey(), entitySFHasChanged(), m_associatedSF, and ccScalarField::showNaNValuesInGrey().
Referenced by sfEditDlg().
satSlider2spin()
double sfEditDlg::satSlider2spin (int pos) const protected
satSpin2slider()
double sfEditDlg::satSpin2slider (double val) const protected
symmetricalScaleChanged()
void sfEditDlg::symmetricalScaleChanged (bool state)
Definition at line 316 of file sfEditDlg.cpp.
References entitySFHasChanged(), fillDialogWith(), m_associatedSF, m_associatedSFHisto, ccHistogramWindow::refresh(), ccScalarField::setSymmetricalScale(), and ccScalarField::symmetricalScale().
Referenced by sfEditDlg().
Member Data Documentation
m_associatedSF
ccScalarField* sfEditDlg::m_associatedSF protected
Associated scalar field.
Definition at line 62 of file sfEditDlg.h.
Referenced by alwaysShow0Changed(), fillDialogWith(), logScaleChanged(), maxSatHistoChanged(), maxSatSBChanged(), maxValHistoChanged(), maxValSBChanged(), minSatHistoChanged(), minSatSBChanged(), minValHistoChanged(), minValSBChanged(), nanInGrayChanged(), and symmetricalScaleChanged().
m_associatedSFHisto
ccHistogramWindow* sfEditDlg::m_associatedSFHisto protected
Associated scalar field histogram.
Definition at line 64 of file sfEditDlg.h.
Referenced by fillDialogWith(), logScaleChanged(), maxSatSBChanged(), maxValSBChanged(), minSatSBChanged(), minValSBChanged(), sfEditDlg(), and symmetricalScaleChanged().
m_ui
Ui::SFEditDlg* sfEditDlg::m_ui protected
Definition at line 66 of file sfEditDlg.h.
Referenced by fillDialogWith(), maxSatHistoChanged(), maxValHistoChanged(), minSatHistoChanged(), minValHistoChanged(), sfEditDlg(), and ~sfEditDlg().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/db_tree/sfEditDlg.h
/root/ACloudViewer/app/db_tree/sfEditDlg.cpp