ACloudViewer: cvSelectionAnnotationManager Class Reference
cvSelectionAnnotationManager Class Reference
Selection annotation manager.
#include <cvSelectionAnnotation.h>
Signals
void annotationsChanged ()
Emitted when annotations change.
void annotationAdded (const QString &id)
Emitted when annotation is added.
void annotationRemoved (const QString &id)
Emitted when annotation is removed.
void annotationUpdated (const QString &id)
Emitted when annotation is updated.
Public Member Functions
cvSelectionAnnotationManager (QObject *parent=nullptr)
~cvSelectionAnnotationManager () override
void setVisualizer (PclUtils::PCLVis *viewer)
Set the visualizer.
QString addAnnotation (const cvSelectionData &selection, const QString &text, bool autoPosition=true)
Add annotation for a selection.
QString addAnnotationAt (const QString &text, const double position[3], const QString &id=QString())
Add annotation at specific position.
bool removeAnnotation (const QString &id)
Remove annotation.
bool updateAnnotationText (const QString &id, const QString &text)
Update annotation text.
bool updateAnnotationPosition (const QString &id, const double position[3])
Update annotation position.
bool setAnnotationVisible (const QString &id, bool visible)
Set annotation visibility.
bool setAnnotationColor (const QString &id, const QColor &color)
Set annotation color.
bool setAnnotationFontSize (const QString &id, int fontSize)
Set annotation font size.
void applyLabelProperties (const cvSelectionLabelPropertiesDialog::LabelProperties &props, bool isCellLabel)
Apply label properties to all annotations (for cell or point labels)
void setDefaultLabelProperties (const cvSelectionLabelPropertiesDialog::LabelProperties &props, bool isCellLabel)
Set default label properties for new annotations.
cvAnnotation getAnnotation (const QString &id) const
Get annotation.
QList< cvAnnotation > allAnnotations () const
Get all annotations.
QStringList annotationIds () const
Get annotation IDs.
int count () const
Get annotation count.
void clearAll ()
Clear all annotations.
void showAll ()
Show all annotations.
void hideAll ()
Hide all annotations.
bool exportToFile (const QString &filename) const
Export annotations to JSON file.
bool importFromFile (const QString &filename, bool merge=true)
Import annotations from JSON file.
Detailed Description
Selection annotation manager.
Manages text annotations for selections:
Add/remove annotations
Show/hide annotations
Update annotation text and style
Export/import annotations
Auto-position at selection center
Based on ParaView's annotation functionality.
Definition at line 112 of file cvSelectionAnnotation.h.
Constructor & Destructor Documentation
cvSelectionAnnotationManager()
cvSelectionAnnotationManager::cvSelectionAnnotationManager (QObject * parent = nullptr) explicit
Definition at line 37 of file cvSelectionAnnotation.cpp.
References CVLog::PrintVerbose().
~cvSelectionAnnotationManager()
cvSelectionAnnotationManager::~cvSelectionAnnotationManager () override
Definition at line 43 of file cvSelectionAnnotation.cpp.
References clearAll().
Member Function Documentation
addAnnotation()
QString cvSelectionAnnotationManager::addAnnotation (const cvSelectionData & selection, const QString & text, bool autoPosition = true)
Add annotation for a selection.
Parameters
selection Selection data
text Annotation text
autoPosition If true, position at selection center
Returns
Annotation ID
Definition at line 51 of file cvSelectionAnnotation.cpp.
References annotationAdded(), annotationsChanged(), cvAnnotation::bold, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelBold, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelColor, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelFontFamily, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelFontSize, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelHorizontalJustification, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelItalic, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelOpacity, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelShadow, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelVerticalJustification, cvAnnotation::color, cvAnnotation::followSelection, cvAnnotation::fontFamily, cvAnnotation::fontSize, cvAnnotation::horizontalJustification, cvAnnotation::id, cvSelectionData::isEmpty(), cvAnnotation::italic, cvAnnotation::opacity, cvAnnotation::position, CVLog::Print(), CVLog::PrintVerbose(), cvAnnotation::shadow, cvAnnotation::text, cvAnnotation::verticalJustification, and CVLog::Warning().
addAnnotationAt()
QString cvSelectionAnnotationManager::addAnnotationAt (const QString & text, const double position[3], const QString & id = QString())
Add annotation at specific position.
Parameters
text Annotation text
position 3D position
id Optional custom ID
Returns
Annotation ID
Definition at line 126 of file cvSelectionAnnotation.cpp.
References annotationAdded(), annotationsChanged(), cvAnnotation::bold, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelBold, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelColor, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelFontFamily, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelFontSize, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelHorizontalJustification, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelItalic, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelOpacity, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelShadow, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelVerticalJustification, cvAnnotation::color, cvAnnotation::fontFamily, cvAnnotation::fontSize, cvAnnotation::horizontalJustification, cvAnnotation::italic, cvAnnotation::opacity, position, CVLog::Print(), cvAnnotation::shadow, and cvAnnotation::verticalJustification.
allAnnotations()
QList< cvAnnotation > cvSelectionAnnotationManager::allAnnotations () const
Get all annotations.
Definition at line 332 of file cvSelectionAnnotation.cpp.
annotationAdded
void cvSelectionAnnotationManager::annotationAdded (const QString & id) signal
Emitted when annotation is added.
Referenced by addAnnotation(), and addAnnotationAt().
annotationIds()
QStringList cvSelectionAnnotationManager::annotationIds () const
Get annotation IDs.
Definition at line 337 of file cvSelectionAnnotation.cpp.
annotationRemoved
void cvSelectionAnnotationManager::annotationRemoved (const QString & id) signal
Emitted when annotation is removed.
Referenced by removeAnnotation().
annotationsChanged
void cvSelectionAnnotationManager::annotationsChanged () signal
Emitted when annotations change.
Referenced by addAnnotation(), addAnnotationAt(), applyLabelProperties(), clearAll(), hideAll(), importFromFile(), removeAnnotation(), showAll(), and updateAnnotationText().
annotationUpdated
void cvSelectionAnnotationManager::annotationUpdated (const QString & id) signal
Emitted when annotation is updated.
Referenced by setAnnotationColor(), setAnnotationFontSize(), setAnnotationVisible(), updateAnnotationPosition(), and updateAnnotationText().
applyLabelProperties()
void cvSelectionAnnotationManager::applyLabelProperties (const cvSelectionLabelPropertiesDialog::LabelProperties & props, bool isCellLabel)
Apply label properties to all annotations (for cell or point labels)
Parameters
props Label properties from dialog
isCellLabel If true, apply cell label properties; if false, apply point label properties
Definition at line 266 of file cvSelectionAnnotation.cpp.
References annotationsChanged(), cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelBold, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelColor, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelFontFamily, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelFontSize, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelHorizontalJustification, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelItalic, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelOpacity, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelShadow, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelVerticalJustification, cvSelectionLabelPropertiesDialog::LabelProperties::pointLabelBold, cvSelectionLabelPropertiesDialog::LabelProperties::pointLabelColor, cvSelectionLabelPropertiesDialog::LabelProperties::pointLabelFontFamily, cvSelectionLabelPropertiesDialog::LabelProperties::pointLabelFontSize, cvSelectionLabelPropertiesDialog::LabelProperties::pointLabelHorizontalJustification, cvSelectionLabelPropertiesDialog::LabelProperties::pointLabelItalic, cvSelectionLabelPropertiesDialog::LabelProperties::pointLabelOpacity, cvSelectionLabelPropertiesDialog::LabelProperties::pointLabelShadow, and cvSelectionLabelPropertiesDialog::LabelProperties::pointLabelVerticalJustification.
clearAll()
void cvSelectionAnnotationManager::clearAll ()
Clear all annotations.
Definition at line 342 of file cvSelectionAnnotation.cpp.
References annotationsChanged(), and CVLog::Print().
Referenced by importFromFile(), and ~cvSelectionAnnotationManager().
count()
int cvSelectionAnnotationManager::count () const inline
Get annotation count.
Definition at line 234 of file cvSelectionAnnotation.h.
exportToFile()
bool cvSelectionAnnotationManager::exportToFile (const QString & filename) const
Export annotations to JSON file.
Parameters
filename Output filename
Returns
True on success
Definition at line 377 of file cvSelectionAnnotation.cpp.
References CVLog::Error(), filename, and CVLog::Print().
getAnnotation()
cvAnnotation cvSelectionAnnotationManager::getAnnotation (const QString & id) const
Get annotation.
Parameters
id Annotation ID
Returns
Annotation data
Definition at line 326 of file cvSelectionAnnotation.cpp.
hideAll()
void cvSelectionAnnotationManager::hideAll ()
Hide all annotations.
Definition at line 367 of file cvSelectionAnnotation.cpp.
References annotationsChanged().
importFromFile()
bool cvSelectionAnnotationManager::importFromFile (const QString & filename, bool merge = true)
Import annotations from JSON file.
Parameters
filename Input filename
merge If true, merge; if false, replace
Returns
True on success
Definition at line 439 of file cvSelectionAnnotation.cpp.
References annotationsChanged(), cvAnnotation::bold, clearAll(), cvAnnotation::color, data, CVLog::Error(), filename, cvAnnotation::followSelection, cvAnnotation::fontFamily, cvAnnotation::fontSize, cvAnnotation::horizontalJustification, cvAnnotation::italic, cvAnnotation::opacity, position, CVLog::Print(), cvAnnotation::shadow, cvAnnotation::timestamp, cvAnnotation::verticalJustification, and cvAnnotation::visible.
removeAnnotation()
bool cvSelectionAnnotationManager::removeAnnotation (const QString & id)
Remove annotation.
Parameters
id Annotation ID
Returns
True if removed
Definition at line 166 of file cvSelectionAnnotation.cpp.
References annotationRemoved(), annotationsChanged(), CVLog::Print(), and CVLog::Warning().
setAnnotationColor()
bool cvSelectionAnnotationManager::setAnnotationColor (const QString & id, const QColor & color)
Set annotation color.
Parameters
id Annotation ID
color Text color
Returns
True if updated
Definition at line 236 of file cvSelectionAnnotation.cpp.
References annotationUpdated(), and color.
setAnnotationFontSize()
bool cvSelectionAnnotationManager::setAnnotationFontSize (const QString & id, int fontSize)
Set annotation font size.
Parameters
id Annotation ID
fontSize Font size in points
Returns
True if updated
Definition at line 251 of file cvSelectionAnnotation.cpp.
References annotationUpdated().
setAnnotationVisible()
bool cvSelectionAnnotationManager::setAnnotationVisible (const QString & id, bool visible)
Set annotation visibility.
Parameters
id Annotation ID
visible Visibility flag
Returns
True if updated
Definition at line 221 of file cvSelectionAnnotation.cpp.
References annotationUpdated().
setDefaultLabelProperties()
void cvSelectionAnnotationManager::setDefaultLabelProperties (const cvSelectionLabelPropertiesDialog::LabelProperties & props, bool isCellLabel)
Set default label properties for new annotations.
Parameters
props Label properties from dialog
isCellLabel If true, use cell label properties; if false, use point label properties
Definition at line 305 of file cvSelectionAnnotation.cpp.
References cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelColor, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelFontFamily, cvSelectionLabelPropertiesDialog::LabelProperties::cellLabelFontSize, and CVLog::PrintVerbose().
Referenced by cvSelectionPropertiesWidget::setSelectionManager().
setVisualizer()
void cvSelectionAnnotationManager::setVisualizer (PclUtils::PCLVis * viewer)
Set the visualizer.
Definition at line 46 of file cvSelectionAnnotation.cpp.
Referenced by cvViewSelectionManager::setVisualizer().
showAll()
void cvSelectionAnnotationManager::showAll ()
Show all annotations.
Definition at line 357 of file cvSelectionAnnotation.cpp.
References annotationsChanged().
updateAnnotationPosition()
bool cvSelectionAnnotationManager::updateAnnotationPosition (const QString & id, const double position[3])
Update annotation position.
Parameters
id Annotation ID
position New position
Returns
True if updated
Definition at line 204 of file cvSelectionAnnotation.cpp.
References annotationUpdated(), and position.
updateAnnotationText()
bool cvSelectionAnnotationManager::updateAnnotationText (const QString & id, const QString & text)
Update annotation text.
Parameters
id Annotation ID
text New text
Returns
True if updated
Definition at line 188 of file cvSelectionAnnotation.cpp.
References annotationsChanged(), and annotationUpdated().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvSelectionAnnotation.h
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvSelectionAnnotation.cpp