ACloudViewer: QCPItemCurve Class Reference
QCPItemCurve Class Reference
A curved line from one point to another.
#include <qcustomplot.h>
Public Member Functions
QCPItemCurve (QCustomPlot *parentPlot)
virtual ~QCPItemCurve ()
QPen pen () const
QPen selectedPen () const
QCPLineEnding head () const
QCPLineEnding tail () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setHead (const QCPLineEnding &head)
void setTail (const QCPLineEnding &tail)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
QCPItemCurve (QCustomPlot *parentPlot)
virtual ~QCPItemCurve ()
QPen pen () const
QPen selectedPen () const
QCPLineEnding head () const
QCPLineEnding tail () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setHead (const QCPLineEnding &head)
void setTail (const QCPLineEnding &tail)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractItem
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
virtual ~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Public Attributes
QCPItemPosition *const start
QCPItemPosition *const startDir
QCPItemPosition *const endDir
QCPItemPosition *const end
Protected Member Functions
virtual void draw (QCPPainter *painter)
QPen mainPen () const
virtual void draw (QCPPainter *painter)
QPen mainPen () const
Protected Member Functions inherited from QCPAbstractItem
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual QPointF anchorPixelPosition (int anchorId) const
double rectDistance (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual QPointF anchorPixelPoint (int anchorId) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual void mousePressEvent (QMouseEvent *event, const QVariant &details)
virtual void mouseMoveEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseReleaseEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseDoubleClickEvent (QMouseEvent *event, const QVariant &details)
virtual void wheelEvent (QWheelEvent *event)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QPen mPen
QPen mSelectedPen
QCPLineEnding mHead
QCPLineEnding mTail
Protected Attributes inherited from QCPAbstractItem
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractItem
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
void layerChanged (QCPLayer *newLayer)
Detailed Description
A curved line from one point to another.
Curve example. Blue dotted circles are anchors,
solid blue discs are positions."
It has four positions, start and end, which define the end points of the line, and two control points which define the direction the line exits from the start and the direction from which it approaches the end: startDir and endDir.
With setHead and setTail you may set different line ending styles, e.g. to create an arrow.
Often it is desirable for the control points to stay at fixed relative positions to the start/end point. This can be achieved by setting the parent anchor e.g. of startDir simply to start, and then specify the desired pixel offset with QCPItemPosition::setCoords on startDir.
Definition at line 7319 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemCurve() [1/2]
QCPItemCurve::QCPItemCurve (QCustomPlot * parentPlot) explicit
Creates a curve item and sets default values.
The created item is automatically registered with parentPlot. This QCustomPlot instance takes ownership of the item, so do not delete it manually but use QCustomPlot::removeItem() instead.
Creates a curve item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 30403 of file qcustomplot.cpp.
References ecvColor::black(), ecvColor::blue(), end, endDir, QCPItemPosition::setCoords(), setPen(), setSelectedPen(), start, and startDir.
~QCPItemCurve() [1/2]
QCPItemCurve::~QCPItemCurve () virtual
Definition at line 30418 of file qcustomplot.cpp.
QCPItemCurve() [2/2]
QCPItemCurve::QCPItemCurve (QCustomPlot * parentPlot)
~QCPItemCurve() [2/2]
virtual QCPItemCurve::~QCPItemCurve () virtual
Member Function Documentation
draw() [1/2]
void QCPItemCurve::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
Definition at line 30487 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), QCPLineEnding::draw(), end, endDir, QCPLineEnding::esNone, M_PI, mainPen(), mHead, mTail, QCPItemPosition::pixelPosition(), QCPPainter::setPen(), start, startDir, QCPLineEnding::style(), and QCPVector2D::toPointF().
draw() [2/2]
virtual void QCPItemCurve::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
head() [1/2]
QCPLineEnding QCPItemCurve::head () const inline
Definition at line 7334 of file qcustomplot.h.
Referenced by setHead().
head() [2/2]
QCPLineEnding QCPItemCurve::head () const inline
Definition at line 3988 of file qcustomplot.h.
mainPen() [1/2]
QPen QCPItemCurve::mainPen () const protected
Definition at line 30524 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
mainPen() [2/2]
QPen QCPItemCurve::mainPen () const protected
pen() [1/2]
QPen QCPItemCurve::pen () const inline
Definition at line 7332 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
pen() [2/2]
QPen QCPItemCurve::pen () const inline
Definition at line 3986 of file qcustomplot.h.
selectedPen() [1/2]
QPen QCPItemCurve::selectedPen () const inline
Definition at line 7333 of file qcustomplot.h.
selectedPen() [2/2]
QPen QCPItemCurve::selectedPen () const inline
Definition at line 3987 of file qcustomplot.h.
selectTest() [1/2]
double QCPItemCurve::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 30459 of file qcustomplot.cpp.
References QCPVector2D::distanceSquaredToLine(), end, endDir, QCPAbstractItem::mSelectable, QCPItemPosition::pixelPosition(), start, and startDir.
selectTest() [2/2]
virtual double QCPItemCurve::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
setHead() [1/2]
void QCPItemCurve::setHead (const QCPLineEnding & head)
Sets the line ending style of the head. The head corresponds to the end position.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle here, e.g.
setHead(QCPLineEnding::esSpikeArrow)
See also
setTail
Definition at line 30444 of file qcustomplot.cpp.
References head(), and mHead.
setHead() [2/2]
void QCPItemCurve::setHead (const QCPLineEnding & head)
setPen() [1/2]
void QCPItemCurve::setPen (const QPen & pen)
Sets the pen that will be used to draw the line
See also
setSelectedPen
Definition at line 30425 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemCurve().
setPen() [2/2]
void QCPItemCurve::setPen (const QPen & pen)
setSelectedPen() [1/2]
void QCPItemCurve::setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw the line when selected
See also
setPen, setSelected
Definition at line 30432 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemCurve().
setSelectedPen() [2/2]
void QCPItemCurve::setSelectedPen (const QPen & pen)
setTail() [1/2]
void QCPItemCurve::setTail (const QCPLineEnding & tail)
Sets the line ending style of the tail. The tail corresponds to the start position.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle here, e.g.
setTail(QCPLineEnding::esSpikeArrow)
See also
setHead
Definition at line 30456 of file qcustomplot.cpp.
References mTail, and tail().
setTail() [2/2]
void QCPItemCurve::setTail (const QCPLineEnding & tail)
tail() [1/2]
QCPLineEnding QCPItemCurve::tail () const inline
Definition at line 7335 of file qcustomplot.h.
Referenced by setTail().
tail() [2/2]
QCPLineEnding QCPItemCurve::tail () const inline
Definition at line 3989 of file qcustomplot.h.
Member Data Documentation
end
QCPItemPosition *const QCPItemCurve::end
Definition at line 7351 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), and selectTest().
endDir
QCPItemPosition *const QCPItemCurve::endDir
Definition at line 7350 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), and selectTest().
mHead
QCPLineEnding QCPItemCurve::mHead protected
Definition at line 7356 of file qcustomplot.h.
Referenced by draw(), and setHead().
mPen
QPen QCPItemCurve::mPen protected
Definition at line 7355 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
mSelectedPen
QPen QCPItemCurve::mSelectedPen protected
Definition at line 7355 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
mTail
QCPLineEnding QCPItemCurve::mTail protected
Definition at line 7356 of file qcustomplot.h.
Referenced by draw(), and setTail().
start
QCPItemPosition *const QCPItemCurve::start
Definition at line 7348 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), and selectTest().
startDir
QCPItemPosition *const QCPItemCurve::startDir
Definition at line 7349 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), and selectTest().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp