ACloudViewer: Widgets::ColorPickerPopup Class Reference
Widgets::ColorPickerPopup Class Reference
Public Slots
void getColorFromDialog ()
Signals
void selected (const QColor &)
void hid ()
Public Member Functions
ColorPickerPopup (int width, bool withColorDialog, QWidget *parent=0)
~ColorPickerPopup ()
void insertColor (const QColor &col, const QString &text, int index)
void exec ()
void setExecFlag ()
QColor lastSelected () const
ColorPickerItem * find (const QColor &col) const
QColor color (int index) const
Protected Slots
void updateSelected ()
Protected Member Functions
void keyPressEvent (QKeyEvent *e)
void showEvent (QShowEvent *e)
void hideEvent (QHideEvent *e)
void mouseReleaseEvent (QMouseEvent *e)
void regenerateGrid ()
Detailed Description
Definition at line 171 of file qtcolorpicker.cpp.
Constructor & Destructor Documentation
ColorPickerPopup()
Widgets::ColorPickerPopup::ColorPickerPopup (int width, bool withColorDialog, QWidget * parent = 0)
Definition at line 478 of file qtcolorpicker.cpp.
References getColorFromDialog(), cloudViewer::core::Minimum(), regenerateGrid(), and width.
~ColorPickerPopup()
Widgets::ColorPickerPopup::~ColorPickerPopup ()
Definition at line 508 of file qtcolorpicker.cpp.
Member Function Documentation
color()
QColor Widgets::ColorPickerPopup::color (int index) const
Definition at line 569 of file qtcolorpicker.cpp.
Referenced by Widgets::QtColorPicker::color().
exec()
void Widgets::ColorPickerPopup::exec ()
Definition at line 579 of file qtcolorpicker.cpp.
References e.
Referenced by Widgets::QtColorPicker::GetColor().
find()
ColorPickerItem * Widgets::ColorPickerPopup::find (const QColor & col) const
Definition at line 517 of file qtcolorpicker.cpp.
Referenced by insertColor(), and Widgets::QtColorPicker::setCurrentColor().
getColorFromDialog
void Widgets::ColorPickerPopup::getColorFromDialog () slot
Definition at line 827 of file qtcolorpicker.cpp.
References insertColor(), rgb, and selected().
Referenced by ColorPickerPopup().
hid
void Widgets::ColorPickerPopup::hid () signal
Referenced by hideEvent().
hideEvent()
void Widgets::ColorPickerPopup::hideEvent (QHideEvent * e) protected
Definition at line 739 of file qtcolorpicker.cpp.
References e, and hid().
insertColor()
void Widgets::ColorPickerPopup::insertColor (const QColor & col, const QString & text, int index)
Definition at line 530 of file qtcolorpicker.cpp.
References find(), lastSelected(), regenerateGrid(), selected(), Widgets::ColorPickerItem::setSelected(), and updateSelected().
Referenced by Widgets::QtColorPicker::GetColor(), getColorFromDialog(), and Widgets::QtColorPicker::insertColor().
keyPressEvent()
void Widgets::ColorPickerPopup::keyPressEvent (QKeyEvent * e) protected
Definition at line 624 of file qtcolorpicker.cpp.
References Widgets::ColorPickerItem::color(), columnCount(), e, selected(), and Widgets::ColorPickerItem::setSelected().
lastSelected()
QColor Widgets::ColorPickerPopup::lastSelected () const
Definition at line 753 of file qtcolorpicker.cpp.
Referenced by Widgets::QtColorPicker::GetColor(), and insertColor().
mouseReleaseEvent()
void Widgets::ColorPickerPopup::mouseReleaseEvent (QMouseEvent * e) protected
Definition at line 616 of file qtcolorpicker.cpp.
References e.
regenerateGrid()
void Widgets::ColorPickerPopup::regenerateGrid () protected
Definition at line 786 of file qtcolorpicker.cpp.
References cloudViewer::utility::ceil().
Referenced by ColorPickerPopup(), and insertColor().
selected
void Widgets::ColorPickerPopup::selected (const QColor &) signal
Referenced by getColorFromDialog(), insertColor(), keyPressEvent(), and updateSelected().
setExecFlag()
void Widgets::ColorPickerPopup::setExecFlag ()
showEvent()
void Widgets::ColorPickerPopup::showEvent (QShowEvent * e) protected
Definition at line 760 of file qtcolorpicker.cpp.
updateSelected
void Widgets::ColorPickerPopup::updateSelected () protected slot
Definition at line 591 of file qtcolorpicker.cpp.
References Widgets::ColorPickerItem::color(), selected(), and Widgets::ColorPickerItem::setSelected().
Referenced by insertColor().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/qtcolorpicker.cpp