ACloudViewer: colmap::SceneClustering Class Reference
colmap::SceneClustering Class Reference
#include <scene_clustering.h>
Classes
struct Cluster
struct Options
Public Member Functions
SceneClustering (const Options &options)
void Partition (const std::vector< std::pair< image_t, image_t >> &image_pairs, const std::vector< int > &num_inliers)
const Cluster * GetRootCluster () const
std::vector< const Cluster * > GetLeafClusters () const
Static Public Member Functions
static SceneClustering Create (const Options &options, const Database &database)
Detailed Description
Definition at line 21 of file scene_clustering.h.
Constructor & Destructor Documentation
SceneClustering()
colmap::SceneClustering::SceneClustering (const Options & options)
Definition at line 47 of file scene_clustering.cc.
References colmap::SceneClustering::Options::Check().
Member Function Documentation
Create()
SceneClustering colmap::SceneClustering::Create (const Options & options, const Database & database) static
Definition at line 286 of file scene_clustering.cc.
References QtCompat::endl(), Partition(), and colmap::Database::ReadTwoViewGeometryNumInliers().
GetLeafClusters()
std::vector< const SceneClustering::Cluster * > colmap::SceneClustering::GetLeafClusters () const
Definition at line 254 of file scene_clustering.cc.
Referenced by BOOST_AUTO_TEST_CASE().
GetRootCluster()
const SceneClustering::Cluster * colmap::SceneClustering::GetRootCluster () const
Definition at line 250 of file scene_clustering.cc.
Referenced by BOOST_AUTO_TEST_CASE().
Partition()
void colmap::SceneClustering::Partition (const std::vector< std::pair< image_t, image_t >> & image_pairs, const std::vector< int > & num_inliers)
Definition at line 51 of file scene_clustering.cc.
References colmap::SceneClustering::Options::is_hierarchical.
Referenced by BOOST_AUTO_TEST_CASE(), and Create().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/scene_clustering.h
/root/ACloudViewer/libs/Reconstruction/src/base/scene_clustering.cc