ACloudViewer: ccImage Class Reference
ccImage Class Reference
Generic image.
#include <ecvImage.h>
Public Member Functions
ccImage ()
Default constructor.
ccImage (const QImage &image, const QString &name=QString("unknown"))
Constructor from QImage.
virtual bool isSerializable () const override
Returns whether object is serializable of not.
virtual CV_CLASS_ENUM getClassID () const override
Returns unique class ID.
bool load (const QString &filename, QString &error)
Loads image from file.
QImage & data ()
Returns image data.
const QImage & data () const
Returns image data (const version)
void setData (const QImage &image)
Sets image data.
unsigned getW () const
Returns image width.
unsigned getH () const
Returns image height.
void setAlpha (float value)
Sets image texture transparency.
float getAlpha () const
Returns image texture transparency.
void setAspectRatio (float ar)
Manually sets aspect ratio.
float getAspectRatio () const
Returns aspect ratio.
void setAssociatedSensor (ccCameraSensor *sensor)
Sets associated sensor.
ccCameraSensor * getAssociatedSensor ()
Returns associated sensor.
const ccCameraSensor * getAssociatedSensor () const
Returns associated sensor (const version)
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual bool IsEmpty () const
virtual Eigen::Vector3d GetMinBound () const
Returns min bounds for geometry coordinates.
virtual Eigen::Vector2d GetMin2DBound () const
virtual Eigen::Vector3d GetMaxBound () const
Returns max bounds for geometry coordinates.
virtual Eigen::Vector2d GetMax2DBound () const
virtual Eigen::Vector3d GetCenter () const
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const
virtual ccHObject & Transform (const Eigen::Matrix4d &transformation)
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual ccHObject & Translate (const Eigen::Vector3d &translation, bool relative=true)
Apply translation to the geometry coordinates.
virtual ccHObject & Scale (const double s, const Eigen::Vector3d &center)
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center)
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
virtual ccBBox getOwnBB (bool withGLFeatures=false)
Returns the entity's own bounding-box.
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false)
virtual bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner)
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual ccBBox getOwnFitBB (ccGLMatrix &trans)
Returns best-fit bounding-box (if available)
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col)
Draws the entity (and its children) bounding-box.
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
virtual void notifyGeometryUpdate ()
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual unsigned getUniqueIDForDisplay () const
Returns object unqiue ID used for display.
virtual const ccGLMatrix & getGLTransformationHistory () const
Returns the transformation 'history' matrix.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual void getDrawingParameters (glDrawParams &params) const
Returns main OpenGL parameters for this entity.
virtual bool hasColors () const
Returns whether colors are enabled or not.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual bool hasNormals () const
Returns whether normals are enabled or not.
virtual bool normalsShown () const
Returns whether normals are shown or not.
virtual void showNormals (bool state)
Sets normals visibility.
virtual void toggleNormals ()
Toggles normals display state.
virtual bool hasDisplayedScalarField () const
Returns whether an active scalar field is available or not.
virtual bool hasScalarFields () const
Returns whether one or more scalar fields are instantiated.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void toggleMaterials ()
Toggles material display state.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Protected Member Functions
virtual void drawMeOnly (CC_DRAW_CONTEXT &context) override
Draws the entity only (not its children)
virtual void onDeletionOf (const ccHObject *obj) override
This method is called when another object is deleted.
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
void updateAspectRatio ()
Updates aspect ratio.
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void applyGLTransformation (const ccGLMatrix &trans)
Applies a GL transformation to the entity.
virtual void drawNameIn3D ()
Draws the entity name in 3D.
virtual void onUpdateOf (ccHObject *obj)
This method is called when another object (geometry) is updated.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Protected Attributes
unsigned m_width
Image width (in pixels)
unsigned m_height
Image height (in pixels)
float m_aspectRatio
Aspect ratio w/h.
float m_texAlpha
Texture transparency.
QImage m_image
Image data.
ccCameraSensor * m_associatedSensor
Associated sensor.
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Additional Inherited Members
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Detailed Description
Generic image.
Definition at line 19 of file ecvImage.h.
Constructor & Destructor Documentation
ccImage() [1/2]
ccImage::ccImage ()
Default constructor.
ccImage() [2/2]
ccImage::ccImage (const QImage & image, const QString & name = QString("unknown"))
Constructor from QImage.
Member Function Documentation
data() [1/2]
QImage& ccImage::data () inline
Returns image data.
Definition at line 43 of file ecvImage.h.
data() [2/2]
const QImage& ccImage::data () const inline
Returns image data (const version)
Definition at line 45 of file ecvImage.h.
drawMeOnly()
virtual void ccImage::drawMeOnly (CC_DRAW_CONTEXT & context) override protected virtual
Draws the entity only (not its children)
Reimplemented from ccHObject.
fromFile_MeOnly()
bool ccImage::fromFile_MeOnly (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override protected virtual
Loads own object data.
Called by 'fromFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
in input file
dataVersion file version
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Reimplemented from ccHObject.
getAlpha()
float ccImage::getAlpha () const inline
Returns image texture transparency.
Definition at line 60 of file ecvImage.h.
getAspectRatio()
float ccImage::getAspectRatio () const inline
Returns aspect ratio.
Definition at line 66 of file ecvImage.h.
Referenced by LoadImage().
getAssociatedSensor() [1/2]
ccCameraSensor* ccImage::getAssociatedSensor () inline
Returns associated sensor.
Definition at line 72 of file ecvImage.h.
getAssociatedSensor() [2/2]
const ccCameraSensor* ccImage::getAssociatedSensor () const inline
Returns associated sensor (const version)
Definition at line 75 of file ecvImage.h.
getClassID()
virtual CV_CLASS_ENUM ccImage::getClassID () const inline override virtual
Returns unique class ID.
Reimplemented from ccHObject.
Definition at line 31 of file ecvImage.h.
References CV_TYPES::IMAGE.
getH()
unsigned ccImage::getH () const inline
Returns image height.
Definition at line 54 of file ecvImage.h.
Referenced by IcmFilter::LoadCalibratedImages().
getW()
unsigned ccImage::getW () const inline
Returns image width.
Definition at line 51 of file ecvImage.h.
Referenced by IcmFilter::LoadCalibratedImages().
isSerializable()
virtual bool ccImage::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccHObject.
Definition at line 28 of file ecvImage.h.
load()
bool ccImage::load (const QString & filename, QString & error)
Loads image from file.
Parameters
filename image filename
error a human readable description of what went wrong (if method fails)
Returns
success
Referenced by IcmFilter::LoadCalibratedImages().
minimumFileVersion_MeOnly()
short ccImage::minimumFileVersion_MeOnly () const override protected virtual
Returns the minimum file version required to save this instance's own data To be overloaded (but still called ;) by subclass. Used internally by minimumFileVersion() to compute the overall minimum.
Reimplemented from ccHObject.
onDeletionOf()
virtual void ccImage::onDeletionOf (const ccHObject * obj) override protected virtual
This method is called when another object is deleted.
For internal use.
Reimplemented from ccHObject.
setAlpha()
void ccImage::setAlpha (float value)
Sets image texture transparency.
setAspectRatio()
void ccImage::setAspectRatio (float ar) inline
Manually sets aspect ratio.
Definition at line 63 of file ecvImage.h.
Referenced by LoadImage().
setAssociatedSensor()
void ccImage::setAssociatedSensor (ccCameraSensor * sensor)
Sets associated sensor.
Referenced by IcmFilter::LoadCalibratedImages(), and LoadImage().
setData()
void ccImage::setData (const QImage & image)
Sets image data.
Referenced by LoadImage().
toFile_MeOnly()
bool ccImage::toFile_MeOnly (QFile & out, short dataVersion) const override protected virtual
Save own object data.
Called by 'toFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
out output file
dataVersion target file version for compatibility control
Reimplemented from ccHObject.
updateAspectRatio()
void ccImage::updateAspectRatio () protected
Updates aspect ratio.
Member Data Documentation
m_aspectRatio
float ccImage::m_aspectRatio protected
Aspect ratio w/h.
Default is m_width/m_height. Should be changed if pixels are not square.
Definition at line 102 of file ecvImage.h.
m_associatedSensor
ccCameraSensor* ccImage::m_associatedSensor protected
Associated sensor.
Definition at line 111 of file ecvImage.h.
m_height
unsigned ccImage::m_height protected
Image height (in pixels)
Definition at line 96 of file ecvImage.h.
m_image
QImage ccImage::m_image protected
Image data.
Definition at line 108 of file ecvImage.h.
m_texAlpha
float ccImage::m_texAlpha protected
Texture transparency.
Definition at line 105 of file ecvImage.h.
m_width
unsigned ccImage::m_width protected
Image width (in pixels)
Definition at line 94 of file ecvImage.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvImage.h