ACloudViewer: ccMeasurement Class Reference
ccMeasurement Class Reference
#include <ccMeasurement.h>
Public Member Functions
ccMeasurement ()
virtual ~ccMeasurement ()
void setDefaultColor (const ecvColor::Rgb &col)
void setHighlightColor (const ecvColor::Rgb &col)
void setActiveColor (const ecvColor::Rgb &col)
void setAlternateColor (const ecvColor::Rgb &col)
ecvColor::Rgb getMeasurementColour () const
void setActive (bool isActive)
void setHighlight (bool isActive)
void setAlternate (bool isActive)
void setNormal ()
Protected Attributes
bool m_isActive = false
bool m_isHighlighted = false
bool m_isAlternate = false
ecvColor::Rgb m_active_colour = ecvColor::yellow
ecvColor::Rgb m_highlight_colour = ecvColor::green
ecvColor::Rgb m_alternate_colour = ecvColor::cyan
ecvColor::Rgb m_normal_colour = ecvColor::blue
Detailed Description
Definition at line 18 of file ccMeasurement.h.
Constructor & Destructor Documentation
ccMeasurement()
ccMeasurement::ccMeasurement () inline
Definition at line 20 of file ccMeasurement.h.
~ccMeasurement()
virtual ccMeasurement::~ccMeasurement () inline virtual
Definition at line 22 of file ccMeasurement.h.
Member Function Documentation
getMeasurementColour()
ecvColor::Rgb ccMeasurement::getMeasurementColour () const inline
Definition at line 36 of file ccMeasurement.h.
References m_active_colour, m_alternate_colour, m_highlight_colour, m_isActive, m_isAlternate, m_isHighlighted, and m_normal_colour.
Referenced by ccPointPair::drawMeOnly(), and ccTrace::drawMeOnly().
setActive()
void ccMeasurement::setActive (bool isActive) inline
Definition at line 48 of file ccMeasurement.h.
References m_isActive.
Referenced by ccTraceTool::cancel(), ccTraceTool::finishCurrentTrace(), ccTraceTool::pickupTrace(), and ccTraceTool::pointPicked().
setActiveColor()
void ccMeasurement::setActiveColor (const ecvColor::Rgb & col) inline
Definition at line 29 of file ccMeasurement.h.
References m_active_colour.
Referenced by ccNote::updateMetadata(), and ccPinchNode::updateMetadata().
setAlternate()
void ccMeasurement::setAlternate (bool isActive) inline
Definition at line 50 of file ccMeasurement.h.
References m_isAlternate.
setAlternateColor()
void ccMeasurement::setAlternateColor (const ecvColor::Rgb & col) inline
Definition at line 30 of file ccMeasurement.h.
References m_alternate_colour.
Referenced by ccPinchNode::updateMetadata().
setDefaultColor()
void ccMeasurement::setDefaultColor (const ecvColor::Rgb & col) inline
Definition at line 25 of file ccMeasurement.h.
References m_normal_colour.
Referenced by ccNote::updateMetadata(), and ccPinchNode::updateMetadata().
setHighlight()
void ccMeasurement::setHighlight (bool isActive) inline
Definition at line 49 of file ccMeasurement.h.
References m_isHighlighted.
setHighlightColor()
void ccMeasurement::setHighlightColor (const ecvColor::Rgb & col) inline
Definition at line 26 of file ccMeasurement.h.
References m_highlight_colour.
Referenced by ccPinchNode::updateMetadata().
setNormal()
void ccMeasurement::setNormal () inline
Definition at line 51 of file ccMeasurement.h.
References m_isActive, m_isAlternate, and m_isHighlighted.
Member Data Documentation
m_active_colour
ecvColor::Rgb ccMeasurement::m_active_colour = ecvColor::yellow protected
Definition at line 62 of file ccMeasurement.h.
Referenced by getMeasurementColour(), and setActiveColor().
m_alternate_colour
ecvColor::Rgb ccMeasurement::m_alternate_colour = ecvColor::cyan protected
Definition at line 64 of file ccMeasurement.h.
Referenced by getMeasurementColour(), and setAlternateColor().
m_highlight_colour
ecvColor::Rgb ccMeasurement::m_highlight_colour = ecvColor::green protected
Definition at line 63 of file ccMeasurement.h.
Referenced by getMeasurementColour(), and setHighlightColor().
m_isActive
bool ccMeasurement::m_isActive = false protected
Definition at line 59 of file ccMeasurement.h.
Referenced by ccTrace::drawMeOnly(), getMeasurementColour(), setActive(), and setNormal().
m_isAlternate
bool ccMeasurement::m_isAlternate = false protected
Definition at line 61 of file ccMeasurement.h.
Referenced by getMeasurementColour(), setAlternate(), and setNormal().
m_isHighlighted
bool ccMeasurement::m_isHighlighted = false protected
Definition at line 60 of file ccMeasurement.h.
Referenced by getMeasurementColour(), setHighlight(), and setNormal().
m_normal_colour
ecvColor::Rgb ccMeasurement::m_normal_colour = ecvColor::blue protected
Definition at line 65 of file ccMeasurement.h.
Referenced by getMeasurementColour(), and setDefaultColor().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qCompass/include/ccMeasurement.h