ACloudViewer: ecvPrimitiveFactoryDlg Class Reference
ecvPrimitiveFactoryDlg Class Reference
Primitive factory.
#include <ecvPrimitiveFactoryDlg.h>
Public Member Functions
ecvPrimitiveFactoryDlg (MainWindow *win)
Default constructor.
Protected Slots
void createPrimitive ()
Creates currently defined primitive.
Protected Member Functions
void setSpherePositionFromClipboard ()
Set sphere position from clipboard.
void setSpherePositionToOrigin ()
Set sphere position to origin.
void setCoordinateSystemBasedOnSelectedObject ()
void onMatrixTextChange ()
void setCSMatrixToIdentity ()
ccGLMatrix getCSMatrix (bool &valid)
Protected Attributes
MainWindow * m_win
Associated main window.
Detailed Description
Primitive factory.
Definition at line 19 of file ecvPrimitiveFactoryDlg.h.
Constructor & Destructor Documentation
ecvPrimitiveFactoryDlg()
ecvPrimitiveFactoryDlg::ecvPrimitiveFactoryDlg (MainWindow * win) explicit
Default constructor.
Definition at line 35 of file ecvPrimitiveFactoryDlg.cpp.
References createPrimitive(), m_win, onMatrixTextChange(), setCoordinateSystemBasedOnSelectedObject(), setCSMatrixToIdentity(), setSpherePositionFromClipboard(), and setSpherePositionToOrigin().
Member Function Documentation
createPrimitive
void ecvPrimitiveFactoryDlg::createPrimitive () protected slot
Creates currently defined primitive.
Definition at line 57 of file ecvPrimitiveFactoryDlg.cpp.
References MainWindow::addToDB(), cloudViewer::DegreesToRadians(), getCSMatrix(), m_win, ecvDisplayTools::ResetCameraClippingRange(), ccGLMatrixTpl< T >::setTranslation(), and ccGLMatrixTpl< T >::toIdentity().
Referenced by ecvPrimitiveFactoryDlg().
getCSMatrix()
ccGLMatrix ecvPrimitiveFactoryDlg::getCSMatrix (bool & valid) protected
Definition at line 222 of file ecvPrimitiveFactoryDlg.cpp.
References ccGLMatrixTpl< float >::FromString().
Referenced by createPrimitive(), and onMatrixTextChange().
onMatrixTextChange()
void ecvPrimitiveFactoryDlg::onMatrixTextChange () protected
Definition at line 204 of file ecvPrimitiveFactoryDlg.cpp.
References getCSMatrix(), and CVLog::Print().
Referenced by ecvPrimitiveFactoryDlg().
setCoordinateSystemBasedOnSelectedObject()
void ecvPrimitiveFactoryDlg::setCoordinateSystemBasedOnSelectedObject () protected
Definition at line 196 of file ecvPrimitiveFactoryDlg.cpp.
References MainWindow::getSelectedEntities(), and m_win.
Referenced by ecvPrimitiveFactoryDlg().
setCSMatrixToIdentity()
void ecvPrimitiveFactoryDlg::setCSMatrixToIdentity () protected
Definition at line 212 of file ecvPrimitiveFactoryDlg.cpp.
Referenced by ecvPrimitiveFactoryDlg().
setSpherePositionFromClipboard()
void ecvPrimitiveFactoryDlg::setSpherePositionFromClipboard () protected
Set sphere position from clipboard.
Definition at line 168 of file ecvPrimitiveFactoryDlg.cpp.
References qtCompatSplitRegex(), QtCompat::SkipEmptyParts, Vector3Tpl< Type >::toDouble(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ecvPrimitiveFactoryDlg().
setSpherePositionToOrigin()
void ecvPrimitiveFactoryDlg::setSpherePositionToOrigin () protected
Set sphere position to origin.
Definition at line 190 of file ecvPrimitiveFactoryDlg.cpp.
Referenced by ecvPrimitiveFactoryDlg().
Member Data Documentation
m_win
MainWindow* ecvPrimitiveFactoryDlg::m_win protected
Associated main window.
Definition at line 48 of file ecvPrimitiveFactoryDlg.h.
Referenced by createPrimitive(), ecvPrimitiveFactoryDlg(), and setCoordinateSystemBasedOnSelectedObject().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvPrimitiveFactoryDlg.h
/root/ACloudViewer/app/ecvPrimitiveFactoryDlg.cpp