ACloudViewer: cloudViewer::visualization::gui::Layout1D Class Reference
cloudViewer::visualization::gui::Layout1D Class Reference
#include <Layout.h>
Classes
class Fixed
struct Impl
class Stretch
Public Types
enum Dir { VERT , HORIZ }
Public Types inherited from cloudViewer::visualization::gui::Widget
enum class DrawResult { NONE , REDRAW , RELAYOUT }
enum class EventResult { IGNORED , CONSUMED , DISCARD }
Public Member Functions
Layout1D (Dir dir, int spacing, const Margins &margins, const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Layout1D ()
int GetSpacing () const
const Margins & GetMargins () const
void SetSpacing (int spacing)
void SetMargins (const Margins &margins)
Size CalcPreferredSize (const LayoutContext &context, const Constraints &constraints) const override
void Layout (const LayoutContext &context) override
void AddFixed (int size)
Adds a fixed number of pixels after the previously added widget.
void AddStretch ()
Public Member Functions inherited from cloudViewer::visualization::gui::Widget
Widget ()
Widget (const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Widget ()
virtual void AddChild (std::shared_ptr< Widget > child)
virtual const std::vector< std::shared_ptr< Widget > > GetChildren () const
virtual const Rect & GetFrame () const
Returns the frame size in pixels.
virtual void SetFrame (const Rect &f)
virtual const Color & GetBackgroundColor () const
virtual bool IsDefaultBackgroundColor () const
virtual void SetBackgroundColor (const Color &color)
virtual bool IsVisible () const
virtual void SetVisible (bool vis)
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
virtual void SetTooltip (const char *text)
virtual const char * GetTooltip () const
virtual Size CalcMinimumSize (const LayoutContext &context) const
virtual DrawResult Draw (const DrawContext &context)
virtual EventResult Mouse (const MouseEvent &e)
virtual EventResult Key (const KeyEvent &e)
virtual DrawResult Tick (const TickEvent &e)
Static Public Member Functions
static void debug_PrintPreferredSizes (Layout1D *layout, const LayoutContext &context, const Constraints &constraints, int depth=0)
Protected Member Functions
int GetMinorAxisPreferredSize () const
void SetMinorAxisPreferredSize (int size)
Margins & GetMutableMargins ()
Protected Member Functions inherited from cloudViewer::visualization::gui::Widget
void DrawImGuiPushEnabledState ()
void DrawImGuiPopEnabledState ()
void DrawImGuiTooltip ()
Additional Inherited Members
Static Public Attributes inherited from cloudViewer::visualization::gui::Widget
static constexpr int DIM_GROW = 10000
Detailed Description
Lays out widgets either horizontally or vertically. Base class for Vert and Horiz.
Definition at line 43 of file Layout.h.
Member Enumeration Documentation
Dir
enum cloudViewer::visualization::gui::Layout1D::Dir
Enumerator
VERT
HORIZ
Definition at line 47 of file Layout.h.
Constructor & Destructor Documentation
Layout1D()
cloudViewer::visualization::gui::Layout1D::Layout1D (Dir dir, int spacing, const Margins & margins, const std::vector< std::shared_ptr< Widget >> & children)
Spacing is in pixels; see the comment in Margin(). 1em is typically a good value for spacing.
Definition at line 193 of file Layout.cpp.
~Layout1D()
cloudViewer::visualization::gui::Layout1D::~Layout1D () virtual
Definition at line 203 of file Layout.cpp.
Member Function Documentation
AddFixed()
void cloudViewer::visualization::gui::Layout1D::AddFixed (int size)
Adds a fixed number of pixels after the previously added widget.
Definition at line 212 of file Layout.cpp.
References cloudViewer::visualization::gui::Widget::AddChild(), and size.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
AddStretch()
void cloudViewer::visualization::gui::Layout1D::AddStretch ()
Adds a virtual widget that takes up as much space as possible. This is useful for centering widgets: { stretch, w1, w2, stretch } or for aligning widgets to one side or the other: { stretch, ok, cancel }.
Definition at line 224 of file Layout.cpp.
References cloudViewer::visualization::gui::Widget::AddChild().
CalcPreferredSize()
Size cloudViewer::visualization::gui::Layout1D::CalcPreferredSize (const LayoutContext & context, const Constraints & constraints) const override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Reimplemented in cloudViewer::visualization::gui::CollapsableVert.
Definition at line 226 of file Layout.cpp.
References context, cloudViewer::visualization::gui::Widget::DIM_GROW, cloudViewer::visualization::gui::Widget::GetChildren(), size, and VERT.
Referenced by cloudViewer::visualization::gui::CollapsableVert::CalcPreferredSize(), and debug_PrintPreferredSizes().
debug_PrintPreferredSizes()
void cloudViewer::visualization::gui::Layout1D::debug_PrintPreferredSizes (Layout1D * layout, const LayoutContext & context, const Constraints & constraints, int depth = 0) static
Definition at line 130 of file Layout.cpp.
References cloudViewer::visualization::gui::Margins::bottom, CalcPreferredSize(), context, e, QtCompat::endl(), for(), cloudViewer::visualization::gui::Widget::GetChildren(), cloudViewer::visualization::gui::VGrid::GetMargins(), cloudViewer::visualization::gui::VGrid::GetSpacing(), cloudViewer::visualization::gui::Margins::left, cloudViewer::visualization::gui::Margins::right, size, cloudViewer::visualization::gui::Margins::top, VERT, and cloudViewer::visualization::gui::Size::width.
GetMargins()
const Margins & cloudViewer::visualization::gui::Layout1D::GetMargins () const
Definition at line 206 of file Layout.cpp.
Referenced by cloudViewer::visualization::gui::CollapsableVert::CalcPreferredSize().
GetMinorAxisPreferredSize()
int cloudViewer::visualization::gui::Layout1D::GetMinorAxisPreferredSize () const protected
Definition at line 216 of file Layout.cpp.
Referenced by cloudViewer::visualization::gui::Horiz::GetPreferredHeight(), and cloudViewer::visualization::gui::Vert::GetPreferredWidth().
GetMutableMargins()
Margins & cloudViewer::visualization::gui::Layout1D::GetMutableMargins () protected
Definition at line 207 of file Layout.cpp.
Referenced by cloudViewer::visualization::gui::CollapsableVert::Layout().
GetSpacing()
int cloudViewer::visualization::gui::Layout1D::GetSpacing () const
Definition at line 205 of file Layout.cpp.
Layout()
void cloudViewer::visualization::gui::Layout1D::Layout (const LayoutContext & context) override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Reimplemented in cloudViewer::visualization::gui::CollapsableVert.
Definition at line 250 of file Layout.cpp.
References cloudViewer::visualization::gui::Widget::CalcMinimumSize(), context, cloudViewer::visualization::gui::Widget::DIM_GROW, frame, cloudViewer::visualization::gui::Widget::GetChildren(), cloudViewer::visualization::gui::Widget::GetFrame(), height, cloudViewer::visualization::gui::Widget::Constraints::height, cloudViewer::visualization::gui::Widget::Layout(), VERT, cloudViewer::visualization::gui::Widget::Constraints::width, x, and y.
Referenced by cloudViewer::visualization::gui::CollapsableVert::Layout().
SetMargins()
void cloudViewer::visualization::gui::Layout1D::SetMargins (const Margins & margins)
Sets margins. Need to signal a relayout after calling (unless it is before a layout that will happen, such as before adding as a child).
Definition at line 210 of file Layout.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetMinorAxisPreferredSize()
void cloudViewer::visualization::gui::Layout1D::SetMinorAxisPreferredSize (int size) protected
Definition at line 220 of file Layout.cpp.
References size.
Referenced by cloudViewer::visualization::gui::Horiz::SetPreferredHeight(), and cloudViewer::visualization::gui::Vert::SetPreferredWidth().
SetSpacing()
void cloudViewer::visualization::gui::Layout1D::SetSpacing (int spacing)
Sets spacing. Need to signal a relayout after calling (unless it is before a layout that will happen, such as before adding as a child).
Definition at line 209 of file Layout.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Layout.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Layout.cpp