ACloudViewer: colmap::mvs::PatchMatch Class Reference
colmap::mvs::PatchMatch Class Reference
#include <patch_match.h>
Classes
struct Problem
Public Member Functions
PatchMatch (const PatchMatchOptions &options, const Problem &problem)
~PatchMatch ()
void Check () const
void Run ()
DepthMap GetDepthMap () const
NormalMap GetNormalMap () const
ConsistencyGraph GetConsistencyGraph () const
Mat< float > GetSelProbMap () const
Detailed Description
Definition at line 153 of file patch_match.h.
Constructor & Destructor Documentation
PatchMatch()
colmap::mvs::PatchMatch::PatchMatch (const PatchMatchOptions & options, const Problem & problem)
Definition at line 48 of file patch_match.cc.
~PatchMatch()
colmap::mvs::PatchMatch::~PatchMatch ()
Definition at line 51 of file patch_match.cc.
Member Function Documentation
Check()
void colmap::mvs::PatchMatch::Check () const
Definition at line 96 of file patch_match.cc.
References colmap::mvs::PatchMatchOptions::Check(), colmap::mvs::PatchMatch::Problem::depth_maps, colmap::mvs::PatchMatchOptions::geom_consistency, colmap::mvs::Image::GetHeight(), colmap::mvs::Mat< T >::GetHeight(), colmap::mvs::Image::GetWidth(), colmap::mvs::Mat< T >::GetWidth(), colmap::mvs::PatchMatchOptions::gpu_index, image, colmap::mvs::PatchMatch::Problem::images, colmap::mvs::PatchMatch::Problem::normal_maps, colmap::mvs::PatchMatch::Problem::ref_image_idx, and colmap::mvs::PatchMatch::Problem::src_image_idxs.
Referenced by Run().
GetConsistencyGraph()
ConsistencyGraph colmap::mvs::PatchMatch::GetConsistencyGraph () const
Definition at line 178 of file patch_match.cc.
References colmap::mvs::PatchMatch::Problem::images, and colmap::mvs::PatchMatch::Problem::ref_image_idx.
GetDepthMap()
DepthMap colmap::mvs::PatchMatch::GetDepthMap () const
Definition at line 166 of file patch_match.cc.
GetNormalMap()
NormalMap colmap::mvs::PatchMatch::GetNormalMap () const
Definition at line 170 of file patch_match.cc.
GetSelProbMap()
Mat< float > colmap::mvs::PatchMatch::GetSelProbMap () const
Definition at line 174 of file patch_match.cc.
Run()
void colmap::mvs::PatchMatch::Run ()
Definition at line 157 of file patch_match.cc.
References Check(), and colmap::PrintHeading2().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/mvs/patch_match.h
/root/ACloudViewer/libs/Reconstruction/src/mvs/patch_match.cc