ACloudViewer: cvQueryValueWidget Class Reference
cvQueryValueWidget Class Reference
cvQueryValueWidget - Dynamic value input widget
#include <cvQueryWidgets.h>
Public Types
enum ValueType {
NO_VALUE , SINGLE_VALUE , COMMA_SEPARATED_VALUES , RANGE_PAIR ,
LOCATION_WITH_TOLERANCE , LOCATION
}
Signals
void valueChanged ()
Public Member Functions
cvQueryValueWidget (QWidget *parent=nullptr)
~cvQueryValueWidget () override=default
void setType (ValueType type)
QMap< QString, QString > values () const
void setValues (const QMap< QString, QString > &values)
void clear ()
Detailed Description
cvQueryValueWidget - Dynamic value input widget
Based on ParaView's pqValueWidget, this widget dynamically creates different UI components based on the ValueType. It supports:
NO_VALUE: No input (for operators like "is min", "is max")
SINGLE_VALUE: Single text input
COMMA_SEPARATED_VALUES: Single text input for comma-separated values
RANGE_PAIR: Two inputs for min/max range
LOCATION: Three inputs for X/Y/Z coordinates
LOCATION_WITH_TOLERANCE: X/Y/Z coordinates + tolerance value
Definition at line 34 of file cvQueryWidgets.h.
Member Enumeration Documentation
ValueType
enum cvQueryValueWidget::ValueType
Enumerator
NO_VALUE
SINGLE_VALUE
COMMA_SEPARATED_VALUES
RANGE_PAIR
LOCATION_WITH_TOLERANCE
LOCATION
Definition at line 38 of file cvQueryWidgets.h.
Constructor & Destructor Documentation
cvQueryValueWidget()
cvQueryValueWidget::cvQueryValueWidget (QWidget * parent = nullptr) explicit
Definition at line 16 of file cvQueryWidgets.cpp.
~cvQueryValueWidget()
cvQueryValueWidget::~cvQueryValueWidget () override default
Member Function Documentation
clear()
void cvQueryValueWidget::clear ()
Clear all input fields
Definition at line 45 of file cvQueryWidgets.cpp.
Referenced by cvQueryConditionWidget::clear(), and cvQueryConditionWidget::setExpression().
setType()
void cvQueryValueWidget::setType (ValueType type)
Set the type of value widget. This rebuilds the UI with appropriate input components.
Definition at line 21 of file cvQueryWidgets.cpp.
References type.
setValues()
void cvQueryValueWidget::setValues (const QMap< QString, QString > & values)
Set values from a map (used when parsing existing expressions)
Definition at line 37 of file cvQueryWidgets.cpp.
References values().
Referenced by cvQueryConditionWidget::setExpression().
valueChanged
void cvQueryValueWidget::valueChanged () signal
Referenced by cvQueryConditionWidget::cvQueryConditionWidget().
values()
QMap< QString, QString > cvQueryValueWidget::values () const
Get current values as a map (key -> value). Keys are: "value", "value_min", "value_max", "value_x", "value_y", "value_z", "value_tolerance"
Definition at line 28 of file cvQueryWidgets.cpp.
References result.
Referenced by cvQueryConditionWidget::expression(), and setValues().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvQueryWidgets.h
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvQueryWidgets.cpp