ACloudViewer: cloudViewer::ml::op_util::DimX< TLeft, TRight, TOp > Class Template Reference
cloudViewer::ml::op_util::DimX< TLeft, TRight, TOp > Class Template Reference
Dim expression class.
#include <ShapeChecking.h>
Public Member Functions
int64_t value ()
bool & constant ()
bool assign (int64_t a)
assigns a value to the expression
std::string ToString (bool show_value=true)
Static Public Member Functions
static DimX< TLeft, TRight, TOp > Create (TLeft left, TRight right)
Detailed Description
template<class TLeft, class TRight, class TOp>
class cloudViewer::ml::op_util::DimX< TLeft, TRight, TOp >
Dim expression class.
Definition at line 207 of file ShapeChecking.h.
Member Function Documentation
assign()
template<class TLeft , class TRight , class TOp > bool cloudViewer::ml::op_util::DimX< TLeft, TRight, TOp >::assign (int64_t a) inline
assigns a value to the expression
Definition at line 223 of file ShapeChecking.h.
References cloudViewer::ml::op_util::DimX< TLeft, TRight, TOp >::value().
constant()
template<class TLeft , class TRight , class TOp > bool& cloudViewer::ml::op_util::DimX< TLeft, TRight, TOp >::constant () inline
Definition at line 220 of file ShapeChecking.h.
Referenced by cloudViewer::ml::op_util::GetValue().
Create()
template<class TLeft , class TRight , class TOp > static DimX<TLeft, TRight, TOp> cloudViewer::ml::op_util::DimX< TLeft, TRight, TOp >::Create (TLeft left, TRight right) inline static
Definition at line 209 of file ShapeChecking.h.
ToString()
template<class TLeft , class TRight , class TOp > std::string cloudViewer::ml::op_util::DimX< TLeft, TRight, TOp >::ToString (bool show_value = true) inline
Definition at line 231 of file ShapeChecking.h.
Referenced by cloudViewer::ml::op_util::GetString().
value()
template<class TLeft , class TRight , class TOp > int64_t cloudViewer::ml::op_util::DimX< TLeft, TRight, TOp >::value () inline
Definition at line 213 of file ShapeChecking.h.
Referenced by cloudViewer::ml::op_util::DimX< TLeft, TRight, TOp >::assign(), and cloudViewer::ml::op_util::GetValue().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/ml/ShapeChecking.h