ACloudViewer: e57::PacketLock Class Reference
e57::PacketLock Class Reference
#include <Packet.h>
Public Member Functions
~PacketLock ()
Protected Member Functions
PacketLock (PacketReadCache *cache, unsigned cacheIndex)
Only PacketReadCache can construct.
Protected Attributes
PacketReadCache * cache_ = nullptr
unsigned int cacheIndex_ = 0
Detailed Description
Definition at line 84 of file Packet.h.
Constructor & Destructor Documentation
~PacketLock()
PacketLock::~PacketLock ()
Note cache must live longer than lock, this is reasonable assumption.
Definition at line 311 of file Packet.cpp.
References cache_, cacheIndex_, QtCompat::endl(), and e57::PacketReadCache::unlock().
PacketLock()
PacketLock::PacketLock (PacketReadCache * cache, unsigned cacheIndex) protected
Only PacketReadCache can construct.
Definition at line 304 of file Packet.cpp.
References QtCompat::endl().
Member Data Documentation
cache_
PacketReadCache* e57::PacketLock::cache_ = nullptr protected
Definition at line 99 of file Packet.h.
Referenced by ~PacketLock().
cacheIndex_
unsigned int e57::PacketLock::cacheIndex_ = 0 protected
Definition at line 100 of file Packet.h.
Referenced by ~PacketLock().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qE57IO/extern/libE57Format/src/Packet.h
/root/ACloudViewer/plugins/core/IO/qE57IO/extern/libE57Format/src/Packet.cpp