ACloudViewer: QUIInputBox Class Reference
QUIInputBox Class Reference
#include <ecvUIManager.h>
Public Slots
void setIconMain (QChar str, quint32 size=9)
void setParameter (const QString &title, int type=0, int closeSec=0, QString defaultValue=QString(), bool pwd=false)
Public Member Functions
QUIInputBox (QWidget *parent=0)
~QUIInputBox ()
QString getValue () const
Static Public Member Functions
static QUIInputBox * Instance ()
Protected Member Functions
void closeEvent (QCloseEvent *)
bool eventFilter (QObject *obj, QEvent *evt)
Detailed Description
Definition at line 471 of file ecvUIManager.h.
Constructor & Destructor Documentation
QUIInputBox()
QUIInputBox::QUIInputBox (QWidget * parent = 0) explicit
Definition at line 2012 of file ecvUIManager.cpp.
Referenced by Instance().
~QUIInputBox()
QUIInputBox::~QUIInputBox ()
Definition at line 2017 of file ecvUIManager.cpp.
Member Function Documentation
closeEvent()
void QUIInputBox::closeEvent (QCloseEvent *) protected
Definition at line 2254 of file ecvUIManager.cpp.
eventFilter()
bool QUIInputBox::eventFilter (QObject * obj, QEvent * evt) protected
Definition at line 2259 of file ecvUIManager.cpp.
References event.
getValue()
QString QUIInputBox::getValue () const
Definition at line 2252 of file ecvUIManager.cpp.
Referenced by QUIWidget::showInputBox().
Instance()
static QUIInputBox* QUIInputBox::Instance () inline static
Definition at line 478 of file ecvUIManager.h.
References QUIInputBox().
Referenced by QUIWidget::setIconMain().
setIconMain
void QUIInputBox::setIconMain (QChar str, quint32 size = 9) slot
Definition at line 2299 of file ecvUIManager.cpp.
References IconHelper::Instance(), IconHelper::setIcon(), and size.
Referenced by QUIWidget::setIconMain().
setParameter
void QUIInputBox::setParameter (const QString & title, int type = 0, int closeSec = 0, QString defaultValue = QString(), bool pwd = false) slot
Definition at line 2227 of file ecvUIManager.cpp.
References type.
Referenced by QUIWidget::showInputBox().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvUIManager.h
/root/ACloudViewer/app/ecvUIManager.cpp