ACloudViewer: IScalarFieldWrapper Class Reference
IScalarFieldWrapper Class Reference abstract
#include <ScalarFieldWrappers.h>
Public Types
using Shared = QSharedPointer< IScalarFieldWrapper >
Public Member Functions
virtual ~IScalarFieldWrapper ()
virtual double pointValue (unsigned index) const =0
virtual bool isValid () const =0
virtual QString getName () const =0
virtual size_t size () const =0
Detailed Description
Definition at line 35 of file ScalarFieldWrappers.h.
Member Typedef Documentation
Shared
using IScalarFieldWrapper::Shared = QSharedPointer<IScalarFieldWrapper>
Definition at line 38 of file ScalarFieldWrappers.h.
Constructor & Destructor Documentation
~IScalarFieldWrapper()
virtual IScalarFieldWrapper::~IScalarFieldWrapper () inline virtual
Definition at line 37 of file ScalarFieldWrappers.h.
Member Function Documentation
getName()
virtual QString IScalarFieldWrapper::getName () const pure virtual
Implemented in ColorScalarFieldWrapper, DimScalarFieldWrapper, NormDipAndDipDirFieldWrapper, ScalarFieldRatioWrapper, and ScalarFieldWrapper.
isValid()
virtual bool IScalarFieldWrapper::isValid () const pure virtual
Implemented in ColorScalarFieldWrapper, DimScalarFieldWrapper, NormDipAndDipDirFieldWrapper, ScalarFieldRatioWrapper, and ScalarFieldWrapper.
pointValue()
virtual double IScalarFieldWrapper::pointValue (unsigned index) const pure virtual
Implemented in ColorScalarFieldWrapper, DimScalarFieldWrapper, NormDipAndDipDirFieldWrapper, ScalarFieldRatioWrapper, and ScalarFieldWrapper.
Referenced by ComputeMathOpWithNearestNeighbor(), and masc::Feature::PerformMathOp().
size()
virtual size_t IScalarFieldWrapper::size () const pure virtual
Implemented in ColorScalarFieldWrapper, DimScalarFieldWrapper, NormDipAndDipDirFieldWrapper, ScalarFieldRatioWrapper, and ScalarFieldWrapper.
Referenced by masc::Feature::PerformMathOp().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/q3DMASC/ScalarFieldWrappers.h