ACloudViewer: TemplateAlignment Class Reference
TemplateAlignment Class Reference
Template Alignment.
#include <TemplateAlignment.h>
Public Member Functions
TemplateAlignment ()
virtual ~TemplateAlignment ()
virtual int compute ()
Performs the actual filter job.
Public Member Functions inherited from BasePclModule
BasePclModule (PclModuleDescription desc=PclModuleDescription(), ccPluginInterface *parent_plugin=0)
Default constructor.
QAction * getAction ()
Get the action associated with the button used in menu and toolbar creation.
QString getStatusTip () const
Returns the status tip.
QString getModuleName () const
Returns the name of the filter.
QString getEntryName () const
Returns the entry name.
QIcon getIcon () const
Returns the icon associated with the button.
void setShowProgressBar (bool status)
Sets whether to show a progressbar while computing or not.
std::vector< std::string > getSelectedAvailableScalarFields ()
ccPointCloud * getSelectedEntityAsCCPointCloud () const
Returns the first selected entity as a ccPointCloud.
ccHObject * getSelectedEntityAsCCHObject () const
Returns the first selected entity as a ccHObject.
ccHObject::Container getSelectedThatHaveMetaData (const QString key) const
Get selected object that also have the provided metadata key.
void getAllEntitiesOfType (CV_CLASS_ENUM type, ccHObject::Container &entities)
Returns all the objects in db tree of type "type".
void getAllEntitiesThatHaveMetaData (QString key, ccHObject::Container &entities)
void getSelectedEntitiesThatAreCCPointCloud (ccHObject::Container &entities)
get all entities that are selected and that also are cc_point_cloud
void getSelectedEntitiesThatAre (CV_CLASS_ENUM kind, ccHObject::Container &entities)
int hasSelectedRGB ()
Returns 1 if the first selected entity has RGB info.
int hasSelectedScalarField ()
Returns 1 if the first selected entity has at least one scalar field.
int hasSelectedScalarField (std::string field_name)
int isFirstSelectedCcPointCloud ()
Returns 1 if the first selected object is a ccPointCloud.
virtual void updateSelectedEntities (const ccHObject::Container &selectedEntities)
Updates the internal copy of selected entities.
void setMainAppInterface (ecvMainAppInterface *app)
Sets associated CC application interface (to access DB)
ecvMainAppInterface * getMainAppInterface ()
ccPluginInterface * getParentPlugin () const
Returns the associated parent plugin interface.
Protected Member Functions
virtual int checkSelected ()
Checks if current selection is compliant with the filter.
virtual int openInputDialog ()
virtual void getParametersFromDialog ()
Collects parameters from the filter dialog (if openDialog is successful)
virtual int checkParameters ()
virtual QString getErrorMessage (int errorCode)
Returns the error message corresponding to a given error code.
void applyTransformation (ccHObject *entity, const ccGLMatrixd &mat)
Protected Member Functions inherited from BasePclModule
virtual int openOutputDialog ()
virtual int start ()
Starts computation.
virtual void initAction ()
Initializes the corresponding action.
void throwError (int errCode)
Protected Attributes
ccPointCloud * m_targetCloud
TemplateAlignmentDialog * m_dialog
PCLModules::TemplateMatching * m_templateMatch
float m_leafSize
bool m_useVoxelGrid
int m_maxThreadCount
float m_normalRadius
float m_featureRadius
int m_maxIterations
float m_minSampleDistance
float m_maxCorrespondenceDistance
std::vector< float > m_scales
std::vector< ccPointCloud * > m_templateClouds
Protected Attributes inherited from BasePclModule
QAction * m_action
Forces the Ui to be updated.
ccHObject::Container m_selected
Pointer to the main window.
PclModuleDescription m_desc
Associated dialog.
ecvMainAppInterface * m_app
Associated application interface.
ccPluginInterface * m_parent_plugin
associated parent plugin of the filter
bool m_show_progress
Do we want to show a progress bar when the filter works?
Additional Inherited Members
Signals inherited from BasePclModule
void entityHasChanged (ccHObject *)
Signal emitted when an entity is (visually) modified.
void newEntity (ccHObject *)
Signal emitted when a new entity is created by the filter.
void newErrorMessage (QString)
Signal emitted when a new error message is produced.
Protected Slots inherited from BasePclModule
int performAction ()
Returns is called when the dialog window is accepted.
Detailed Description
Template Alignment.
Definition at line 22 of file TemplateAlignment.h.
Constructor & Destructor Documentation
TemplateAlignment()
TemplateAlignment::TemplateAlignment ()
Definition at line 29 of file TemplateAlignment.cpp.
~TemplateAlignment()
TemplateAlignment::~TemplateAlignment () virtual
Definition at line 47 of file TemplateAlignment.cpp.
References m_dialog, and m_templateMatch.
Member Function Documentation
applyTransformation()
void TemplateAlignment::applyTransformation (ccHObject * entity, const ccGLMatrixd & mat) protected
Definition at line 251 of file TemplateAlignment.cpp.
References ccHObject::applyGLTransformation_recursive(), ccGLMatrixTpl< T >::data(), CVLog::Print(), ccDrawableObject::setGLTransformation(), and ccGLMatrixTpl< T >::toString().
Referenced by compute().
checkParameters()
int TemplateAlignment::checkParameters () protected virtual
Checks that the parameters retrieved by getParametersFromDialog are valid Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Returns
1 if parameters are valid (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 132 of file TemplateAlignment.cpp.
References m_featureRadius, m_normalRadius, m_targetCloud, and m_templateClouds.
checkSelected()
int TemplateAlignment::checkSelected () protected virtual
Checks if current selection is compliant with the filter.
If not, an error is returned and computation stops. By default, baseclass method simply checks that selection is composed of one and only one ccPointCloud. This method should be overridden if necessary.
Returns
1 if selection is compliant (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 55 of file TemplateAlignment.cpp.
References BasePclModule::isFirstSelectedCcPointCloud().
compute()
int TemplateAlignment::compute () virtual
Performs the actual filter job.
This method MUST be re-implemented by derived filter
Returns
1 if successful (error code otherwise)
Implements BasePclModule.
Definition at line 143 of file TemplateAlignment.cpp.
References ccHObject::addChild(), applyTransformation(), ecvColor::darkBlue(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccObject::getName(), ccHObject::getParent(), TemplateAlignmentDialog::getTemplate1Cloud(), TemplateAlignmentDialog::getTemplate2Cloud(), m_dialog, m_featureRadius, m_leafSize, m_maxThreadCount, m_normalRadius, m_targetCloud, m_templateClouds, m_templateMatch, m_useVoxelGrid, BasePclModule::newEntity(), CVLog::Print(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccObject::setName(), ccPointCloud::setRGBColor(), ccDrawableObject::showColors(), and ccDrawableObject::showSF().
getErrorMessage()
QString TemplateAlignment::getErrorMessage (int errorCode) protected virtual
Returns the error message corresponding to a given error code.
Each filter have a set of possible error message to be used given bt getFilterErrorMessage() Baseclass implementation provides some generic messages.
Note
These messages can be replaced by re-implementing this method and handling the same codes BEFORE calling the baseclass method
Reimplemented from BasePclModule.
Definition at line 264 of file TemplateAlignment.cpp.
References BasePclModule::getErrorMessage().
getParametersFromDialog()
void TemplateAlignment::getParametersFromDialog () protected virtual
Collects parameters from the filter dialog (if openDialog is successful)
Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Reimplemented from BasePclModule.
Definition at line 75 of file TemplateAlignment.cpp.
References ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, TemplateAlignmentDialog::getEvaluationCloud(), TemplateAlignmentDialog::getFeatureRadius(), TemplateAlignmentDialog::getMaxCorrespondenceDistance(), TemplateAlignmentDialog::getMaxIterations(), TemplateAlignmentDialog::getMinSampleDistance(), TemplateAlignmentDialog::getNormalRadius(), TemplateAlignmentDialog::getScales(), TemplateAlignmentDialog::getTemplate1Cloud(), TemplateAlignmentDialog::getTemplate2Cloud(), TemplateAlignmentDialog::getVoxelGridLeafSize(), BasePclModule::m_app, m_dialog, m_featureRadius, m_leafSize, m_maxCorrespondenceDistance, m_maxIterations, m_maxThreadCount, m_minSampleDistance, m_normalRadius, m_scales, m_targetCloud, m_templateClouds, m_templateMatch, and m_useVoxelGrid.
openInputDialog()
int TemplateAlignment::openInputDialog () protected virtual
Opens the input dialog window. Where the user can supply parameters for the computation Automatically called by performAction. Does nothing by default. Must be overridden if a dialog must be displayed.
Returns
1 if dialog has been successfully executed, 0 if canceled, negative error code otherwise
Reimplemented from BasePclModule.
Definition at line 63 of file TemplateAlignment.cpp.
References BasePclModule::m_app, m_dialog, TemplateAlignmentDialog::refreshCloudComboBox(), and TemplateAlignmentDialog::saveParamsToPersistentSettings().
Member Data Documentation
m_dialog
TemplateAlignmentDialog* TemplateAlignment::m_dialog protected
Definition at line 41 of file TemplateAlignment.h.
Referenced by compute(), getParametersFromDialog(), openInputDialog(), and ~TemplateAlignment().
m_featureRadius
float TemplateAlignment::m_featureRadius protected
Definition at line 50 of file TemplateAlignment.h.
Referenced by checkParameters(), compute(), and getParametersFromDialog().
m_leafSize
float TemplateAlignment::m_leafSize protected
Definition at line 44 of file TemplateAlignment.h.
Referenced by compute(), and getParametersFromDialog().
m_maxCorrespondenceDistance
float TemplateAlignment::m_maxCorrespondenceDistance protected
Definition at line 55 of file TemplateAlignment.h.
Referenced by getParametersFromDialog().
m_maxIterations
int TemplateAlignment::m_maxIterations protected
Definition at line 53 of file TemplateAlignment.h.
Referenced by getParametersFromDialog().
m_maxThreadCount
int TemplateAlignment::m_maxThreadCount protected
Definition at line 48 of file TemplateAlignment.h.
Referenced by compute(), and getParametersFromDialog().
m_minSampleDistance
float TemplateAlignment::m_minSampleDistance protected
Definition at line 54 of file TemplateAlignment.h.
Referenced by getParametersFromDialog().
m_normalRadius
float TemplateAlignment::m_normalRadius protected
Definition at line 49 of file TemplateAlignment.h.
Referenced by checkParameters(), compute(), and getParametersFromDialog().
m_scales
std::vector<float> TemplateAlignment::m_scales protected
Definition at line 57 of file TemplateAlignment.h.
Referenced by getParametersFromDialog().
m_targetCloud
ccPointCloud* TemplateAlignment::m_targetCloud protected
Definition at line 40 of file TemplateAlignment.h.
Referenced by checkParameters(), compute(), and getParametersFromDialog().
m_templateClouds
std::vector<ccPointCloud*> TemplateAlignment::m_templateClouds protected
Definition at line 58 of file TemplateAlignment.h.
Referenced by checkParameters(), compute(), and getParametersFromDialog().
m_templateMatch
PCLModules::TemplateMatching* TemplateAlignment::m_templateMatch protected
Definition at line 42 of file TemplateAlignment.h.
Referenced by compute(), getParametersFromDialog(), and ~TemplateAlignment().
m_useVoxelGrid
bool TemplateAlignment::m_useVoxelGrid protected
Definition at line 45 of file TemplateAlignment.h.
Referenced by compute(), and getParametersFromDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Recognitions/TemplateAlignment.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Recognitions/TemplateAlignment.cpp