ACloudViewer: flann::KNNUniqueResultSet< DistanceType > Class Template Reference
flann::KNNUniqueResultSet< DistanceType > Class Template Reference
#include <result_set.h>
Public Member Functions
KNNUniqueResultSet (unsigned int capacity)
void addPoint (DistanceType dist, size_t index)
void clear ()
Public Member Functions inherited from flann::UniqueResultSet< DistanceType >
UniqueResultSet ()
bool full () const
void copy (size_t *indices, DistanceType *dist, int n_neighbors, bool sorted=true)
size_t size () const
DistanceType worstDist () const
Public Member Functions inherited from flann::ResultSet< DistanceType >
virtual ~ResultSet ()
Protected Types
typedef UniqueResultSet< DistanceType >::DistIndex DistIndex
Protected Attributes
unsigned int capacity_
Protected Attributes inherited from flann::UniqueResultSet< DistanceType >
bool is_full_
DistanceType worst_distance_
std::set< DistIndex > dist_indices_
Detailed Description
template<typename DistanceType>
class flann::KNNUniqueResultSet< DistanceType >
Class that holds the k NN neighbors Faster than KNNResultSet as it uses a binary heap and does not maintain two arrays
Definition at line 785 of file result_set.h.
Member Typedef Documentation
DistIndex
template<typename DistanceType > typedef UniqueResultSet<DistanceType>::DistIndex flann::KNNUniqueResultSet< DistanceType >::DistIndex protected
Definition at line 829 of file result_set.h.
Constructor & Destructor Documentation
KNNUniqueResultSet()
template<typename DistanceType > flann::KNNUniqueResultSet< DistanceType >::KNNUniqueResultSet (unsigned int capacity) inline
Constructor
Parameters
capacity the number of neighbors to store at max
Definition at line 791 of file result_set.h.
References flann::KNNUniqueResultSet< DistanceType >::clear(), and flann::UniqueResultSet< DistanceType >::is_full_.
Member Function Documentation
addPoint()
template<typename DistanceType > void flann::KNNUniqueResultSet< DistanceType >::addPoint (DistanceType dist, size_t index) inline virtual
Add a possible candidate to the best neighbors
Parameters
dist distance for that neighbor
index index of that neighbor
Implements flann::ResultSet< DistanceType >.
Definition at line 801 of file result_set.h.
References flann::KNNUniqueResultSet< DistanceType >::capacity_, dist(), flann::UniqueResultSet< DistanceType >::dist_indices_, flann::UniqueResultSet< DistanceType >::is_full_, and flann::UniqueResultSet< DistanceType >::worst_distance_.
clear()
template<typename DistanceType > void flann::KNNUniqueResultSet< DistanceType >::clear () inline
Remove all elements in the set
Definition at line 821 of file result_set.h.
References flann::UniqueResultSet< DistanceType >::dist_indices_, flann::UniqueResultSet< DistanceType >::is_full_, max(), and flann::UniqueResultSet< DistanceType >::worst_distance_.
Referenced by flann::LshIndex< Distance >::knnSearch(), and flann::KNNUniqueResultSet< DistanceType >::KNNUniqueResultSet().
Member Data Documentation
capacity_
template<typename DistanceType > unsigned int flann::KNNUniqueResultSet< DistanceType >::capacity_ protected
The number of neighbors to keep
Definition at line 835 of file result_set.h.
Referenced by flann::KNNUniqueResultSet< DistanceType >::addPoint().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/util/result_set.h