ACloudViewer: WolmanCustomPlot Class Reference
WolmanCustomPlot Class Reference
#include <WolmanCustomPlot.h>
Signals
void closeTab ()
Signals inherited from QCustomPlot
void mouseDoubleClick (QMouseEvent *event)
void mousePress (QMouseEvent *event)
void mouseMove (QMouseEvent *event)
void mouseRelease (QMouseEvent *event)
void mouseWheel (QWheelEvent *event)
void plottableClick (QCPAbstractPlottable *plottable, int dataIndex, QMouseEvent *event)
void plottableDoubleClick (QCPAbstractPlottable *plottable, int dataIndex, QMouseEvent *event)
void itemClick (QCPAbstractItem *item, QMouseEvent *event)
void itemDoubleClick (QCPAbstractItem *item, QMouseEvent *event)
void axisClick (QCPAxis *axis, QCPAxis::SelectablePart part, QMouseEvent *event)
void axisDoubleClick (QCPAxis *axis, QCPAxis::SelectablePart part, QMouseEvent *event)
void legendClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
void legendDoubleClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
void selectionChangedByUser ()
void beforeReplot ()
void afterReplot ()
void mouseDoubleClick (QMouseEvent *event)
void mousePress (QMouseEvent *event)
void mouseMove (QMouseEvent *event)
void mouseRelease (QMouseEvent *event)
void mouseWheel (QWheelEvent *event)
void plottableClick (QCPAbstractPlottable *plottable, QMouseEvent *event)
void plottableDoubleClick (QCPAbstractPlottable *plottable, QMouseEvent *event)
void itemClick (QCPAbstractItem *item, QMouseEvent *event)
void itemDoubleClick (QCPAbstractItem *item, QMouseEvent *event)
void axisClick (QCPAxis *axis, QCPAxis::SelectablePart part, QMouseEvent *event)
void axisDoubleClick (QCPAxis *axis, QCPAxis::SelectablePart part, QMouseEvent *event)
void legendClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
void legendDoubleClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
void titleClick (QMouseEvent *event, QCPPlotTitle *title)
void titleDoubleClick (QMouseEvent *event, QCPPlotTitle *title)
void selectionChangedByUser ()
void beforeReplot ()
void afterReplot ()
Public Member Functions
WolmanCustomPlot (const Eigen::ArrayXf &d_sample, const Eigen::Array3d &dq_final, const Eigen::Array3d &edq)
QSharedPointer< QCPGraphDataContainer > dataContainer ()
void rescale ()
void emitCloseTab ()
void mouseDoubleClickEvent (QMouseEvent *event) override
void mousePressEvent (QMouseEvent *event) override
Public Member Functions inherited from QCustomPlot
QCustomPlot (QWidget *parent=0)
virtual ~QCustomPlot ()
QRect viewport () const
double bufferDevicePixelRatio () const
QPixmap background () const
bool backgroundScaled () const
Qt::AspectRatioMode backgroundScaledMode () const
QCPLayoutGrid * plotLayout () const
QCP::AntialiasedElements antialiasedElements () const
QCP::AntialiasedElements notAntialiasedElements () const
bool autoAddPlottableToLegend () const
const QCP::Interactions interactions () const
int selectionTolerance () const
bool noAntialiasingOnDrag () const
QCP::PlottingHints plottingHints () const
Qt::KeyboardModifier multiSelectModifier () const
QCP::SelectionRectMode selectionRectMode () const
QCPSelectionRect * selectionRect () const
bool openGl () const
void setViewport (const QRect &rect)
void setBufferDevicePixelRatio (double ratio)
void setBackground (const QPixmap &pm)
void setBackground (const QPixmap &pm, bool scaled, Qt::AspectRatioMode mode=Qt::KeepAspectRatioByExpanding)
void setBackground (const QBrush &brush)
void setBackgroundScaled (bool scaled)
void setBackgroundScaledMode (Qt::AspectRatioMode mode)
void setAntialiasedElements (const QCP::AntialiasedElements &antialiasedElements)
void setAntialiasedElement (QCP::AntialiasedElement antialiasedElement, bool enabled=true)
void setNotAntialiasedElements (const QCP::AntialiasedElements &notAntialiasedElements)
void setNotAntialiasedElement (QCP::AntialiasedElement notAntialiasedElement, bool enabled=true)
void setAutoAddPlottableToLegend (bool on)
void setInteractions (const QCP::Interactions &interactions)
void setInteraction (const QCP::Interaction &interaction, bool enabled=true)
void setSelectionTolerance (int pixels)
void setNoAntialiasingOnDrag (bool enabled)
void setPlottingHints (const QCP::PlottingHints &hints)
void setPlottingHint (QCP::PlottingHint hint, bool enabled=true)
void setMultiSelectModifier (Qt::KeyboardModifier modifier)
void setSelectionRectMode (QCP::SelectionRectMode mode)
void setSelectionRect (QCPSelectionRect *selectionRect)
void setOpenGl (bool enabled, int multisampling=16)
QCPAbstractPlottable * plottable (int index)
QCPAbstractPlottable * plottable ()
bool removePlottable (QCPAbstractPlottable *plottable)
bool removePlottable (int index)
int clearPlottables ()
int plottableCount () const
QList< QCPAbstractPlottable * > selectedPlottables () const
QCPAbstractPlottable * plottableAt (const QPointF &pos, bool onlySelectable=false) const
bool hasPlottable (QCPAbstractPlottable *plottable) const
QCPGraph * graph (int index) const
QCPGraph * graph () const
QCPGraph * addGraph (QCPAxis *keyAxis=0, QCPAxis *valueAxis=0)
bool removeGraph (QCPGraph *graph)
bool removeGraph (int index)
int clearGraphs ()
int graphCount () const
QList< QCPGraph * > selectedGraphs () const
QCPAbstractItem * item (int index) const
QCPAbstractItem * item () const
bool removeItem (QCPAbstractItem *item)
bool removeItem (int index)
int clearItems ()
int itemCount () const
QList< QCPAbstractItem * > selectedItems () const
QCPAbstractItem * itemAt (const QPointF &pos, bool onlySelectable=false) const
bool hasItem (QCPAbstractItem *item) const
QCPLayer * layer (const QString &name) const
QCPLayer * layer (int index) const
QCPLayer * currentLayer () const
bool setCurrentLayer (const QString &name)
bool setCurrentLayer (QCPLayer *layer)
int layerCount () const
bool addLayer (const QString &name, QCPLayer *otherLayer=0, LayerInsertMode insertMode=limAbove)
bool removeLayer (QCPLayer *layer)
bool moveLayer (QCPLayer *layer, QCPLayer *otherLayer, LayerInsertMode insertMode=limAbove)
int axisRectCount () const
QCPAxisRect * axisRect (int index=0) const
QList< QCPAxisRect * > axisRects () const
QCPLayoutElement * layoutElementAt (const QPointF &pos) const
QCPAxisRect * axisRectAt (const QPointF &pos) const
Q_SLOT void rescaleAxes (bool onlyVisiblePlottables=false)
QList< QCPAxis * > selectedAxes () const
QList< QCPLegend * > selectedLegends () const
Q_SLOT void deselectAll ()
bool savePdf (const QString &fileName, int width=0, int height=0, QCP::ExportPen exportPen=QCP::epAllowCosmetic, const QString &pdfCreator=QString(), const QString &pdfTitle=QString())
bool savePng (const QString &fileName, int width=0, int height=0, double scale=1.0, int quality=-1, int resolution=96, QCP::ResolutionUnit resolutionUnit=QCP::ruDotsPerInch)
bool saveJpg (const QString &fileName, int width=0, int height=0, double scale=1.0, int quality=-1, int resolution=96, QCP::ResolutionUnit resolutionUnit=QCP::ruDotsPerInch)
bool saveBmp (const QString &fileName, int width=0, int height=0, double scale=1.0, int resolution=96, QCP::ResolutionUnit resolutionUnit=QCP::ruDotsPerInch)
bool saveRastered (const QString &fileName, int width, int height, double scale, const char *format, int quality=-1, int resolution=96, QCP::ResolutionUnit resolutionUnit=QCP::ruDotsPerInch)
QPixmap toPixmap (int width=0, int height=0, double scale=1.0)
void toPainter (QCPPainter *painter, int width=0, int height=0)
Q_SLOT void replot (QCustomPlot::RefreshPriority refreshPriority=QCustomPlot::rpRefreshHint)
QCustomPlot (QWidget *parent=0)
virtual ~QCustomPlot ()
QRect viewport () const
QPixmap background () const
bool backgroundScaled () const
Qt::AspectRatioMode backgroundScaledMode () const
QCPLayoutGrid * plotLayout () const
QCP::AntialiasedElements antialiasedElements () const
QCP::AntialiasedElements notAntialiasedElements () const
bool autoAddPlottableToLegend () const
const QCP::Interactions interactions () const
int selectionTolerance () const
bool noAntialiasingOnDrag () const
QCP::PlottingHints plottingHints () const
Qt::KeyboardModifier multiSelectModifier () const
void setViewport (const QRect &rect)
void setBackground (const QPixmap &pm)
void setBackground (const QPixmap &pm, bool scaled, Qt::AspectRatioMode mode=Qt::KeepAspectRatioByExpanding)
void setBackground (const QBrush &brush)
void setBackgroundScaled (bool scaled)
void setBackgroundScaledMode (Qt::AspectRatioMode mode)
void setAntialiasedElements (const QCP::AntialiasedElements &antialiasedElements)
void setAntialiasedElement (QCP::AntialiasedElement antialiasedElement, bool enabled=true)
void setNotAntialiasedElements (const QCP::AntialiasedElements &notAntialiasedElements)
void setNotAntialiasedElement (QCP::AntialiasedElement notAntialiasedElement, bool enabled=true)
void setAutoAddPlottableToLegend (bool on)
void setInteractions (const QCP::Interactions &interactions)
void setInteraction (const QCP::Interaction &interaction, bool enabled=true)
void setSelectionTolerance (int pixels)
void setNoAntialiasingOnDrag (bool enabled)
void setPlottingHints (const QCP::PlottingHints &hints)
void setPlottingHint (QCP::PlottingHint hint, bool enabled=true)
void setMultiSelectModifier (Qt::KeyboardModifier modifier)
QCPAbstractPlottable * plottable (int index)
QCPAbstractPlottable * plottable ()
bool addPlottable (QCPAbstractPlottable *plottable)
bool removePlottable (QCPAbstractPlottable *plottable)
bool removePlottable (int index)
int clearPlottables ()
int plottableCount () const
QList< QCPAbstractPlottable * > selectedPlottables () const
QCPAbstractPlottable * plottableAt (const QPointF &pos, bool onlySelectable=false) const
bool hasPlottable (QCPAbstractPlottable *plottable) const
QCPGraph * graph (int index) const
QCPGraph * graph () const
QCPGraph * addGraph (QCPAxis *keyAxis=0, QCPAxis *valueAxis=0)
bool removeGraph (QCPGraph *graph)
bool removeGraph (int index)
int clearGraphs ()
int graphCount () const
QList< QCPGraph * > selectedGraphs () const
QCPAbstractItem * item (int index) const
QCPAbstractItem * item () const
bool addItem (QCPAbstractItem *item)
bool removeItem (QCPAbstractItem *item)
bool removeItem (int index)
int clearItems ()
int itemCount () const
QList< QCPAbstractItem * > selectedItems () const
QCPAbstractItem * itemAt (const QPointF &pos, bool onlySelectable=false) const
bool hasItem (QCPAbstractItem *item) const
QCPLayer * layer (const QString &name) const
QCPLayer * layer (int index) const
QCPLayer * currentLayer () const
bool setCurrentLayer (const QString &name)
bool setCurrentLayer (QCPLayer *layer)
int layerCount () const
bool addLayer (const QString &name, QCPLayer *otherLayer=0, LayerInsertMode insertMode=limAbove)
bool removeLayer (QCPLayer *layer)
bool moveLayer (QCPLayer *layer, QCPLayer *otherLayer, LayerInsertMode insertMode=limAbove)
int axisRectCount () const
QCPAxisRect * axisRect (int index=0) const
QList< QCPAxisRect * > axisRects () const
QCPLayoutElement * layoutElementAt (const QPointF &pos) const
Q_SLOT void rescaleAxes (bool onlyVisiblePlottables=false)
QList< QCPAxis * > selectedAxes () const
QList< QCPLegend * > selectedLegends () const
Q_SLOT void deselectAll ()
bool savePdf (const QString &fileName, bool noCosmeticPen=false, int width=0, int height=0, const QString &pdfCreator=QString(), const QString &pdfTitle=QString())
bool savePng (const QString &fileName, int width=0, int height=0, double scale=1.0, int quality=-1)
bool saveJpg (const QString &fileName, int width=0, int height=0, double scale=1.0, int quality=-1)
bool saveBmp (const QString &fileName, int width=0, int height=0, double scale=1.0)
bool saveRastered (const QString &fileName, int width, int height, double scale, const char *format, int quality=-1)
QPixmap toPixmap (int width=0, int height=0, double scale=1.0)
void toPainter (QCPPainter *painter, int width=0, int height=0)
Q_SLOT void replot (QCustomPlot::RefreshPriority refreshPriority=QCustomPlot::rpHint)
Public Attributes
Eigen::Array3d m_dq_final
Eigen::Array3d m_edq
QCPGraph * m_graph
Public Attributes inherited from QCustomPlot
QCPAxis * xAxis
QCPAxis * yAxis
QCPAxis * xAxis2
QCPAxis * yAxis2
QCPLegend * legend
Additional Inherited Members
Public Types inherited from QCustomPlot
enum LayerInsertMode { limBelow , limAbove , limBelow , limAbove }
enum RefreshPriority {
rpImmediateRefresh , rpQueuedRefresh , rpRefreshHint , rpQueuedReplot ,
rpImmediate , rpQueued , rpHint
}
enum LayerInsertMode { limBelow , limAbove , limBelow , limAbove }
enum RefreshPriority {
rpImmediateRefresh , rpQueuedRefresh , rpRefreshHint , rpQueuedReplot ,
rpImmediate , rpQueued , rpHint
}
Protected Member Functions inherited from QCustomPlot
virtual QSize minimumSizeHint () const
virtual QSize sizeHint () const
virtual void paintEvent (QPaintEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void draw (QCPPainter *painter)
virtual void updateLayout ()
virtual void axisRemoved (QCPAxis *axis)
virtual void legendRemoved (QCPLegend *legend)
virtual Q_SLOT void processRectSelection (QRect rect, QMouseEvent *event)
virtual Q_SLOT void processRectZoom (QRect rect, QMouseEvent *event)
virtual Q_SLOT void processPointSelection (QMouseEvent *event)
bool registerPlottable (QCPAbstractPlottable *plottable)
bool registerGraph (QCPGraph *graph)
bool registerItem (QCPAbstractItem *item)
void updateLayerIndices () const
QCPLayerable * layerableAt (const QPointF &pos, bool onlySelectable, QVariant *selectionDetails=0) const
QList< QCPLayerable * > layerableListAt (const QPointF &pos, bool onlySelectable, QList< QVariant > *selectionDetails=0) const
void drawBackground (QCPPainter *painter)
void setupPaintBuffers ()
QCPAbstractPaintBuffer * createPaintBuffer ()
bool hasInvalidatedPaintBuffers ()
bool setupOpenGl ()
void freeOpenGl ()
virtual QSize minimumSizeHint () const
virtual QSize sizeHint () const
virtual void paintEvent (QPaintEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void draw (QCPPainter *painter)
virtual void axisRemoved (QCPAxis *axis)
virtual void legendRemoved (QCPLegend *legend)
void updateLayerIndices () const
QCPLayerable * layerableAt (const QPointF &pos, bool onlySelectable, QVariant *selectionDetails=0) const
void drawBackground (QCPPainter *painter)
Protected Attributes inherited from QCustomPlot
QRect mViewport
double mBufferDevicePixelRatio
QCPLayoutGrid * mPlotLayout
bool mAutoAddPlottableToLegend
QList< QCPAbstractPlottable * > mPlottables
QList< QCPGraph * > mGraphs
QList< QCPAbstractItem * > mItems
QList< QCPLayer * > mLayers
QCP::AntialiasedElements mAntialiasedElements
QCP::AntialiasedElements mNotAntialiasedElements
QCP::Interactions mInteractions
int mSelectionTolerance
bool mNoAntialiasingOnDrag
QBrush mBackgroundBrush
QPixmap mBackgroundPixmap
QPixmap mScaledBackgroundPixmap
bool mBackgroundScaled
Qt::AspectRatioMode mBackgroundScaledMode
QCPLayer * mCurrentLayer
QCP::PlottingHints mPlottingHints
Qt::KeyboardModifier mMultiSelectModifier
QCP::SelectionRectMode mSelectionRectMode
QCPSelectionRect * mSelectionRect
bool mOpenGl
QList< QSharedPointer< QCPAbstractPaintBuffer > > mPaintBuffers
QPoint mMousePressPos
bool mMouseHasMoved
QPointer< QCPLayerable > mMouseEventLayerable
QPointer< QCPLayerable > mMouseSignalLayerable
QVariant mMouseEventLayerableDetails
QVariant mMouseSignalLayerableDetails
bool mReplotting
bool mReplotQueued
int mOpenGlMultisamples
QCP::AntialiasedElements mOpenGlAntialiasedElementsBackup
bool mOpenGlCacheLabelsBackup
QPixmap mPaintBuffer
QPointer< QCPLayoutElement > mMouseEventElement
Detailed Description
Definition at line 74 of file WolmanCustomPlot.h.
Constructor & Destructor Documentation
WolmanCustomPlot()
WolmanCustomPlot::WolmanCustomPlot (const Eigen::ArrayXf & d_sample, const Eigen::Array3d & dq_final, const Eigen::Array3d & edq)
Definition at line 14 of file WolmanCustomPlot.cpp.
References QCustomPlot::addGraph(), QtCompat::endl(), QCPErrorBars::etKeyError, QCP::iRangeDrag, QCP::iRangeZoom, QCPGraph::lsNone, m_graph, ecvColor::red(), QCPAbstractPlottable::removeFromLegend(), QCPGraph::rescaleAxes(), QCPAbstractPlottable::rescaleAxes(), QCPLayerable::setAntialiased(), QCPErrorBars::setData(), QCPGraph::setData(), QCPErrorBars::setDataPlottable(), QCPErrorBars::setErrorType(), QCustomPlot::setInteractions(), QCPAxis::setLabel(), QCPGraph::setLineStyle(), QCPAbstractPlottable::setPen(), QCPAxis::setScaleType(), QCPGraph::setScatterStyle(), QCPScatterStyle::ssCircle, QCPAxis::stLogarithmic, QCustomPlot::xAxis, and QCustomPlot::yAxis.
Member Function Documentation
closeTab
void WolmanCustomPlot::closeTab () signal
Referenced by G3PointPlots::addToTabWidget(), and emitCloseTab().
dataContainer()
QSharedPointer<QCPGraphDataContainer> WolmanCustomPlot::dataContainer () inline
Definition at line 81 of file WolmanCustomPlot.h.
References QCPGraph::data(), and m_graph.
Referenced by G3PointPlots::onExportToCSV().
emitCloseTab()
void WolmanCustomPlot::emitCloseTab () inline
Definition at line 93 of file WolmanCustomPlot.h.
References closeTab().
Referenced by mousePressEvent().
mouseDoubleClickEvent()
void WolmanCustomPlot::mouseDoubleClickEvent (QMouseEvent * event) override virtual
Reimplemented from QCustomPlot.
Definition at line 88 of file WolmanCustomPlot.cpp.
References event, QCustomPlot::mouseDoubleClickEvent(), and rescale().
mousePressEvent()
void WolmanCustomPlot::mousePressEvent (QMouseEvent * event) override virtual
Reimplemented from QCustomPlot.
Definition at line 95 of file WolmanCustomPlot.cpp.
References emitCloseTab(), event, and QCustomPlot::mousePressEvent().
rescale()
void WolmanCustomPlot::rescale ()
Definition at line 80 of file WolmanCustomPlot.cpp.
References m_graph, QCustomPlot::replot(), and QCPGraph::rescaleAxes().
Referenced by mouseDoubleClickEvent().
Member Data Documentation
m_dq_final
Eigen::Array3d WolmanCustomPlot::m_dq_final
Definition at line 85 of file WolmanCustomPlot.h.
Referenced by G3PointPlots::onExportToCSV().
m_edq
Eigen::Array3d WolmanCustomPlot::m_edq
Definition at line 87 of file WolmanCustomPlot.h.
Referenced by G3PointPlots::onExportToCSV().
m_graph
QCPGraph* WolmanCustomPlot::m_graph
Definition at line 89 of file WolmanCustomPlot.h.
Referenced by dataContainer(), rescale(), and WolmanCustomPlot().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qG3Point/include/WolmanCustomPlot.h
/root/ACloudViewer/plugins/core/Standard/qG3Point/src/WolmanCustomPlot.cpp