ACloudViewer: cvCutFilter Class Reference
cvCutFilter Class Reference
#include <cvCutFilter.h>
Public Member Functions
virtual void showInteractor (bool state) override
virtual void getInteractorBounds (ccBBox &bbox) override
virtual void getInteractorTransformation (ccGLMatrixd &trans) override
virtual void shift (const CCVector3d &v) override
Shifts the current interactor.
Public Member Functions inherited from cvGenericFilter
cvGenericFilter (QWidget *parent=nullptr)
virtual ~cvGenericFilter ()
virtual void apply ()=0
virtual void start ()
virtual void update ()
virtual void reset ()
virtual void restoreOrigin ()
virtual ccHObject * getOutput ()
virtual void getOutput (std::vector< ccHObject * > &outputSlices, std::vector< ccPolyline * > &outputContours)
virtual bool initModel ()
virtual bool setInput (ccHObject *obj)
virtual void getInteractorInfos (ccBBox &bbox, ccGLMatrixd &trans)
void setUpViewer (PclUtils::PCLVis *viewer)
void showOutline (bool show=true)
void setNegative (bool state)
void setInteractor (vtkRenderWindowInteractor *interactor)
vtkRenderWindowInteractor * getInteractor ()
Protected Types
enum CutType { Box , Plane , Sphere }
Protected Types inherited from cvGenericFilter
enum DisplayEffect { Opaque , Transparent , Points , Wireframe }
Protected Slots
void onOriginChanged (double *orgin)
void onNormalChanged (double *normal)
void onCenterChanged (double *center)
void onRadiusChanged (double radius)
void onPlanesChanged (vtkPlanes *planes)
void showContourLines (bool show=true)
void onPreview (bool dummy)
Protected Slots inherited from cvGenericFilter
void onDoubleClick (int x, int y)
Protected Member Functions
cvCutFilter (QWidget *parent=nullptr)
void setNormal (double normal[3])
void setOrigin (double origin[3])
void setRadius (double radius)
void updateCutWidget ()
virtual void initFilter () override
void setCutType (CutType type)
CutType cutType () const
virtual void clearAllActor () override
virtual void modelReady () override
virtual void dataChanged () override
virtual void updateUi () override
void createUi ()
void resetPlaneWidget ()
void resetSphereWidget ()
void resetBoxWidget ()
Protected Member Functions inherited from cvGenericFilter
virtual void colorsChanged ()
void setDisplayEffect (DisplayEffect effect)
DisplayEffect displayEffect () const
void safeOff (vtk3DWidget *widget)
void updateSize ()
void UpdateScalarRange ()
void applyDisplayEffect ()
void setScalarBarColors (const QColor &clr1, const QColor &clr2)
QColor color1 () const
QColor color2 () const
void setScalarRange (double min, double max)
double scalarMin () const
double scalarMax () const
vtkSmartPointer< vtkDataArray > getActorScalars (vtkSmartPointer< vtkActor > actor)
int getDefaultScalarInterpolationForDataSet (vtkDataSet *data)
vtkSmartPointer< vtkLookupTable > createLookupTable (double min, double max)
template<class ConfigClass >
void setupConfigWidget (ConfigClass *cc)
template<class DataObject , class Mapper >
void createActorFromData (vtkDataObject *dataObj)
void showScalarBar (bool show=true)
void setOutlineColor (const QColor &clr)
bool isValidPolyData () const
bool isValidDataSet () const
void addActor (const vtkSmartPointer< vtkProp > actor)
void removeActor (const vtkSmartPointer< vtkProp > actor)
void setResultData (vtkSmartPointer< vtkDataObject > data)
vtkSmartPointer< vtkDataObject > resultData () const
Protected Attributes
double m_normal [3]
double m_origin [3]
double m_center [3]
double m_radius
vtkSmartPointer< vtkBoxWidget > m_boxWidget
vtkSmartPointer< vtkSphereWidget > m_sphereWidget
vtkSmartPointer< vtkImplicitPlaneWidget > m_planeWidget
Ui::CutFilterDlg * m_configUi = nullptr
CutType m_cutType = CutType::Box
vtkSmartPointer< vtkPlanes > m_planes
vtkSmartPointer< vtkActor > m_contourLinesActor
Protected Attributes inherited from cvGenericFilter
Ui::GenericFilterDlg * m_ui = nullptr
DisplayEffect m_displayEffect = Opaque
vtkDataObject * m_dataObject = nullptr
vtkSmartPointer< vtkDataObject > m_resultData
bool m_keepMode
bool m_negative
bool m_meshMode
bool m_preview
std::string m_id
ccHObject * m_entity = nullptr
PclUtils::PCLVis * m_viewer = nullptr
vtkRenderWindowInteractor * m_interactor = nullptr
vtkSmartPointer< vtkActor > m_modelActor
vtkSmartPointer< vtkLODActor > m_filterActor
vtkSmartPointer< vtkScalarBarActor > m_scalarBar
vtkSmartPointer< vtkActor > m_outlineActor
QColor m_color1 = Qt::blue
QColor m_color2 = Qt::red
double m_scalarMin = 0.0
double m_scalarMax = 1.0
Additional Inherited Members
Static Protected Attributes inherited from cvGenericFilter
static const int MAX_PREVIEW_NUMBER = 20e4
Detailed Description
Definition at line 25 of file cvCutFilter.h.
Member Enumeration Documentation
CutType
enum cvCutFilter::CutType protected
Enumerator
Box
Plane
Sphere
Definition at line 28 of file cvCutFilter.h.
Constructor & Destructor Documentation
cvCutFilter()
cvCutFilter::cvCutFilter (QWidget * parent = nullptr) explicit protected
Definition at line 45 of file cvCutFilter.cpp.
References createUi().
Member Function Documentation
clearAllActor()
void cvCutFilter::clearAllActor () override protected virtual
Reimplemented from cvGenericFilter.
Reimplemented in cvSliceFilter, and cvClipFilter.
Definition at line 50 of file cvCutFilter.cpp.
References cvGenericFilter::clearAllActor(), m_boxWidget, m_contourLinesActor, m_planeWidget, m_sphereWidget, cvGenericFilter::removeActor(), and cvGenericFilter::safeOff().
Referenced by cvClipFilter::clearAllActor(), and cvSliceFilter::clearAllActor().
createUi()
void cvCutFilter::createUi () protected virtual
Reimplemented from cvGenericFilter.
Definition at line 70 of file cvCutFilter.cpp.
References cvGenericFilter::createUi(), m_configUi, cvGenericFilter::m_preview, onPreview(), cvGenericFilter::setNegative(), and cvGenericFilter::setupConfigWidget().
Referenced by cvCutFilter().
cutType()
cvCutFilter::CutType cvCutFilter::cutType () const protected
Definition at line 325 of file cvCutFilter.cpp.
References m_cutType.
Referenced by cvSliceFilter::apply(), and cvClipFilter::apply().
dataChanged()
void cvCutFilter::dataChanged () override protected virtual
Reimplemented from cvGenericFilter.
Definition at line 582 of file cvCutFilter.cpp.
References cvGenericFilter::apply(), Box, m_center, m_cutType, m_normal, m_origin, m_planeWidget, m_radius, m_sphereWidget, Plane, resetBoxWidget(), resetPlaneWidget(), resetSphereWidget(), and Sphere.
getInteractorBounds()
void cvCutFilter::getInteractorBounds (ccBBox & bbox) override virtual
Reimplemented from cvGenericFilter.
Definition at line 113 of file cvCutFilter.cpp.
References Box, m_boxWidget, m_cutType, m_planeWidget, m_sphereWidget, cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), Plane, cloudViewer::BoundingBoxTpl< T >::setValidity(), and Sphere.
getInteractorTransformation()
void cvCutFilter::getInteractorTransformation (ccGLMatrixd & trans) override virtual
Reimplemented from cvGenericFilter.
Definition at line 150 of file cvCutFilter.cpp.
References Box, ccGLMatrixTpl< T >::data(), m_boxWidget, m_cutType, m_planeWidget, m_sphereWidget, Plane, and Sphere.
initFilter()
void cvCutFilter::initFilter () override protected virtual
Reimplemented from cvGenericFilter.
Definition at line 327 of file cvCutFilter.cpp.
References cvGenericFilter::initFilter(), m_configUi, cvGenericFilter::m_meshMode, and cvGenericFilter::m_preview.
modelReady()
void cvCutFilter::modelReady () override protected virtual
Reimplemented from cvGenericFilter.
Definition at line 525 of file cvCutFilter.cpp.
References VtkUtils::SignalBlocker::addObject(), cvGenericFilter::isValidDataSet(), cvGenericFilter::isValidPolyData(), m_center, m_configUi, cvGenericFilter::m_dataObject, cvGenericFilter::m_meshMode, m_normal, m_origin, m_radius, cvGenericFilter::modelReady(), setRadius(), cvGenericFilter::setScalarRange(), cvGenericFilter::showScalarBar(), and updateCutWidget().
onCenterChanged
void cvCutFilter::onCenterChanged (double * center) protected slot
Definition at line 370 of file cvCutFilter.cpp.
References VtkUtils::SignalBlocker::addObject(), cvGenericFilter::apply(), m_center, and m_configUi.
Referenced by shift(), and updateCutWidget().
onNormalChanged
void cvCutFilter::onNormalChanged (double * normal) protected slot
Definition at line 354 of file cvCutFilter.cpp.
References VtkUtils::SignalBlocker::addObject(), cvGenericFilter::apply(), m_configUi, m_normal, and normal.
Referenced by updateCutWidget().
onOriginChanged
void cvCutFilter::onOriginChanged (double * orgin) protected slot
Definition at line 338 of file cvCutFilter.cpp.
References VtkUtils::SignalBlocker::addObject(), cvGenericFilter::apply(), m_configUi, m_origin, and origin.
Referenced by updateCutWidget().
onPlanesChanged
void cvCutFilter::onPlanesChanged (vtkPlanes * planes) protected slot
Definition at line 397 of file cvCutFilter.cpp.
References cvGenericFilter::apply(), and m_planes.
Referenced by resetBoxWidget(), and updateCutWidget().
onPreview
void cvCutFilter::onPreview (bool dummy) protected slot
Definition at line 520 of file cvCutFilter.cpp.
References cvGenericFilter::apply(), m_configUi, and cvGenericFilter::m_preview.
Referenced by createUi().
onRadiusChanged
void cvCutFilter::onRadiusChanged (double radius) protected slot
Definition at line 386 of file cvCutFilter.cpp.
References cvGenericFilter::apply(), m_configUi, m_radius, and setRadius().
Referenced by updateCutWidget().
resetBoxWidget()
void cvCutFilter::resetBoxWidget () protected
Definition at line 666 of file cvCutFilter.cpp.
References CVLog::Error(), cvGenericFilter::isValidDataSet(), cvGenericFilter::isValidPolyData(), m_boxWidget, cvGenericFilter::m_dataObject, m_planes, onPlanesChanged(), and cvGenericFilter::UpdateScalarRange().
Referenced by dataChanged().
resetPlaneWidget()
void cvCutFilter::resetPlaneWidget () protected
Definition at line 611 of file cvCutFilter.cpp.
References CVLog::Error(), cvGenericFilter::isValidDataSet(), cvGenericFilter::isValidPolyData(), cvGenericFilter::m_dataObject, m_origin, m_planeWidget, origin, and cvGenericFilter::UpdateScalarRange().
Referenced by dataChanged(), and updateCutWidget().
resetSphereWidget()
void cvCutFilter::resetSphereWidget () protected
Definition at line 636 of file cvCutFilter.cpp.
References CVLog::Error(), cvGenericFilter::isValidDataSet(), cvGenericFilter::isValidPolyData(), m_center, cvGenericFilter::m_dataObject, m_sphereWidget, and setRadius().
Referenced by dataChanged(), and updateCutWidget().
setCutType()
void cvCutFilter::setCutType (CutType type) protected
Definition at line 318 of file cvCutFilter.cpp.
References m_cutType, type, and updateCutWidget().
setNormal()
void cvCutFilter::setNormal (double normal[3]) protected
Definition at line 302 of file cvCutFilter.cpp.
References cvGenericFilter::apply(), m_normal, and normal.
setOrigin()
void cvCutFilter::setOrigin (double origin[3]) protected
Definition at line 309 of file cvCutFilter.cpp.
References cvGenericFilter::apply(), m_normal, and origin.
setRadius()
void cvCutFilter::setRadius (double radius) protected
Definition at line 316 of file cvCutFilter.cpp.
References m_radius.
Referenced by modelReady(), onRadiusChanged(), and resetSphereWidget().
shift()
void cvCutFilter::shift (const CCVector3d & v) override virtual
Shifts the current interactor.
Reimplemented from cvGenericFilter.
Definition at line 172 of file cvCutFilter.cpp.
References cvGenericFilter::apply(), Box, m_boxWidget, m_center, m_cutType, m_planeWidget, m_sphereWidget, onCenterChanged(), Plane, Sphere, Tuple3Tpl< Type >::u, Vector3Tpl< double >::vadd(), and VTK_CREATE.
showContourLines
void cvCutFilter::showContourLines (bool show = true) protected slot
START
Definition at line 402 of file cvCutFilter.cpp.
References cvGenericFilter::addActor(), m_contourLinesActor, cvGenericFilter::m_dataObject, cvGenericFilter::m_meshMode, cvGenericFilter::setResultData(), cvGenericFilter::update(), and VTK_CREATE.
Referenced by cvSliceFilter::apply().
showInteractor()
void cvCutFilter::showInteractor (bool state) override virtual
Reimplemented from cvGenericFilter.
Definition at line 91 of file cvCutFilter.cpp.
References Box, m_boxWidget, m_cutType, m_planeWidget, m_sphereWidget, Plane, cvGenericFilter::safeOff(), and Sphere.
updateCutWidget()
void cvCutFilter::updateCutWidget () protected
Definition at line 200 of file cvCutFilter.cpp.
References VtkUtils::AbstractWidgetObserver::attach(), Box, cvGenericFilter::getInteractor(), cvGenericFilter::isValidDataSet(), cvGenericFilter::isValidPolyData(), m_boxWidget, m_center, m_configUi, m_cutType, cvGenericFilter::m_dataObject, cvGenericFilter::m_modelActor, m_normal, m_origin, m_planeWidget, m_radius, m_sphereWidget, onCenterChanged(), onNormalChanged(), onOriginChanged(), onPlanesChanged(), onRadiusChanged(), Plane, resetPlaneWidget(), resetSphereWidget(), cvGenericFilter::safeOff(), Sphere, cvGenericFilter::updateSize(), and VtkUtils::vtkInitOnce().
Referenced by modelReady(), and setCutType().
updateUi()
void cvCutFilter::updateUi () override protected virtual
Reimplemented from cvGenericFilter.
Definition at line 83 of file cvCutFilter.cpp.
References m_configUi, and cvGenericFilter::m_preview.
Member Data Documentation
m_boxWidget
vtkSmartPointer<vtkBoxWidget> cvCutFilter::m_boxWidget protected
Definition at line 92 of file cvCutFilter.h.
Referenced by clearAllActor(), getInteractorBounds(), getInteractorTransformation(), resetBoxWidget(), shift(), showInteractor(), and updateCutWidget().
m_center
double cvCutFilter::m_center[3] protected
Definition at line 89 of file cvCutFilter.h.
Referenced by cvSliceFilter::apply(), cvClipFilter::apply(), dataChanged(), modelReady(), onCenterChanged(), resetSphereWidget(), shift(), and updateCutWidget().
m_configUi
Ui::CutFilterDlg* cvCutFilter::m_configUi = nullptr protected
Definition at line 96 of file cvCutFilter.h.
Referenced by createUi(), initFilter(), modelReady(), onCenterChanged(), onNormalChanged(), onOriginChanged(), onPreview(), onRadiusChanged(), updateCutWidget(), and updateUi().
m_contourLinesActor
vtkSmartPointer<vtkActor> cvCutFilter::m_contourLinesActor protected
Definition at line 100 of file cvCutFilter.h.
Referenced by cvSliceFilter::apply(), clearAllActor(), and showContourLines().
m_cutType
CutType cvCutFilter::m_cutType = CutType::Box protected
Definition at line 98 of file cvCutFilter.h.
Referenced by cutType(), dataChanged(), getInteractorBounds(), getInteractorTransformation(), setCutType(), shift(), showInteractor(), and updateCutWidget().
m_normal
double cvCutFilter::m_normal[3] protected
Definition at line 87 of file cvCutFilter.h.
Referenced by cvSliceFilter::apply(), cvClipFilter::apply(), dataChanged(), modelReady(), onNormalChanged(), setNormal(), setOrigin(), and updateCutWidget().
m_origin
double cvCutFilter::m_origin[3] protected
Definition at line 88 of file cvCutFilter.h.
Referenced by cvSliceFilter::apply(), cvClipFilter::apply(), dataChanged(), modelReady(), onOriginChanged(), resetPlaneWidget(), and updateCutWidget().
m_planes
vtkSmartPointer<vtkPlanes> cvCutFilter::m_planes protected
Definition at line 99 of file cvCutFilter.h.
Referenced by cvSliceFilter::apply(), cvClipFilter::apply(), onPlanesChanged(), and resetBoxWidget().
m_planeWidget
vtkSmartPointer<vtkImplicitPlaneWidget> cvCutFilter::m_planeWidget protected
Definition at line 94 of file cvCutFilter.h.
Referenced by clearAllActor(), dataChanged(), getInteractorBounds(), getInteractorTransformation(), resetPlaneWidget(), shift(), showInteractor(), and updateCutWidget().
m_radius
double cvCutFilter::m_radius protected
Definition at line 90 of file cvCutFilter.h.
Referenced by cvSliceFilter::apply(), cvClipFilter::apply(), dataChanged(), modelReady(), onRadiusChanged(), setRadius(), and updateCutWidget().
m_sphereWidget
vtkSmartPointer<vtkSphereWidget> cvCutFilter::m_sphereWidget protected
Definition at line 93 of file cvCutFilter.h.
Referenced by clearAllActor(), dataChanged(), getInteractorBounds(), getInteractorTransformation(), resetSphereWidget(), shift(), showInteractor(), and updateCutWidget().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/cvCutFilter.h
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/cvCutFilter.cpp