ACloudViewer: colmap::ReconstructionManagerWidget Class Reference
colmap::ReconstructionManagerWidget Class Reference
#include <reconstruction_manager_widget.h>
Public Member Functions
ReconstructionManagerWidget (QWidget *parent, const ReconstructionManager *reconstruction_manager)
void Update ()
size_t SelectedReconstructionIdx () const
void SelectReconstruction (const size_t idx)
Static Public Attributes
static const size_t kNewestReconstructionIdx
Detailed Description
Definition at line 16 of file reconstruction_manager_widget.h.
Constructor & Destructor Documentation
ReconstructionManagerWidget()
colmap::ReconstructionManagerWidget::ReconstructionManagerWidget (QWidget * parent, const ReconstructionManager * reconstruction_manager)
Definition at line 42 of file reconstruction_manager_widget.cc.
Member Function Documentation
SelectedReconstructionIdx()
size_t colmap::ReconstructionManagerWidget::SelectedReconstructionIdx () const
Definition at line 92 of file reconstruction_manager_widget.cc.
References kNewestReconstructionIdx, and colmap::ReconstructionManager::Size().
SelectReconstruction()
void colmap::ReconstructionManagerWidget::SelectReconstruction (const size_t idx)
Definition at line 104 of file reconstruction_manager_widget.cc.
References colmap::ReconstructionManager::Size().
Referenced by colmap::MainWindow::ImportReconstruction().
Update()
void colmap::ReconstructionManagerWidget::Update ()
Definition at line 50 of file reconstruction_manager_widget.cc.
References colmap::ReconstructionManager::Get(), colmap::Reconstruction::NumPoints3D(), colmap::Reconstruction::NumRegImages(), QTCOMPAT_FONTMETRICS_WIDTH, and colmap::ReconstructionManager::Size().
Referenced by colmap::MainWindow::ImportReconstruction(), and colmap::AutomaticReconstructionWidget::Run().
Member Data Documentation
kNewestReconstructionIdx
const size_t colmap::ReconstructionManagerWidget::kNewestReconstructionIdx static
Initial value:
=
    std::numeric_limits<size_t>::max()
Definition at line 18 of file reconstruction_manager_widget.h.
Referenced by SelectedReconstructionIdx().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/reconstruction_manager_widget.h
/root/ACloudViewer/libs/Reconstruction/src/ui/reconstruction_manager_widget.cc