ACloudViewer: cloudViewer::visualization::ViewControlWithCustomAnimation Class Reference
cloudViewer::visualization::ViewControlWithCustomAnimation Class Reference
#include <ViewControlWithCustomAnimation.h>
Public Types
enum AnimationMode { FreeMode = 0 , PreviewMode = 1 , PlayMode = 2 }
Public Types inherited from cloudViewer::visualization::ViewControl
enum ProjectionType { Perspective = 0 , Orthogonal = 1 }
Public Member Functions
virtual ~ViewControlWithCustomAnimation ()
void Reset () override
void ChangeFieldOfView (double step) override
void Scale (double scale) override
void Rotate (double x, double y, double xo, double yo) override
Function to process rotation.
void Translate (double x, double y, double xo, double yo) override
Function to process translation.
void SetAnimationMode (AnimationMode mode)
void AddKeyFrame ()
void UpdateKeyFrame ()
void DeleteKeyFrame ()
void AddSpinKeyFrames (int num_of_key_frames=20)
void ClearAllKeyFrames ()
size_t NumOfKeyFrames () const
size_t NumOfFrames () const
void ToggleTrajectoryLoop ()
void ChangeTrajectoryInterval (int change)
int GetTrajectoryInterval () const
std::string GetStatusString () const
void Step (double change)
void GoToFirst ()
void GoToLast ()
bool CaptureTrajectory (const std::string &filename="")
bool LoadTrajectoryFromJsonFile (const std::string &filename)
bool LoadTrajectoryFromCameraTrajectory (const camera::PinholeCameraTrajectory &camera_trajectory)
bool IsPreviewing ()
bool IsPlaying ()
bool IsPlayingEnd (size_t num)
bool IsValidPinholeCameraTrajectory () const
Public Member Functions inherited from cloudViewer::visualization::ViewControl
virtual ~ViewControl ()
void SetViewMatrices (const Eigen::Matrix4d &model_matrix=Eigen::Matrix4d::Identity())
bool ConvertToViewParameters (ViewParameters &status) const
Function to get equivalent view parameters (support orthogonal)
bool ConvertFromViewParameters (const ViewParameters &status)
void SetZoom (const double zoom)
void SetUp (const Eigen::Vector3d &up)
void SetFront (const Eigen::Vector3d &front)
void SetLookat (const Eigen::Vector3d &lookat)
bool ConvertToPinholeCameraParameters (camera::PinholeCameraParameters &parameters)
bool ConvertFromPinholeCameraParameters (const camera::PinholeCameraParameters &parameters, bool allow_arbitrary=false)
ProjectionType GetProjectionType () const
void SetProjectionParameters ()
virtual void ChangeWindowSize (int width, int height)
virtual void CameraLocalTranslate (double forward, double right, double up)
virtual void CameraLocalRotate (double x, double y, double xo=0.0, double yo=0.0)
virtual void ResetCameraLocalRotate ()
virtual void Roll (double x)
const ccBBox & GetBoundingBox () const
void ResetBoundingBox ()
void FitInGeometry (const ccHObject &geometry)
double GetFieldOfView () const
Function to get field of view.
gl_util::GLMatrix4f GetMVPMatrix () const
gl_util::GLMatrix4f GetProjectionMatrix () const
gl_util::GLMatrix4f GetViewMatrix () const
gl_util::GLMatrix4f GetModelMatrix () const
gl_util::GLVector3f GetEye () const
gl_util::GLVector3f GetLookat () const
gl_util::GLVector3f GetUp () const
gl_util::GLVector3f GetFront () const
gl_util::GLVector3f GetRight () const
int GetWindowWidth () const
int GetWindowHeight () const
double GetZNear () const
double GetZFar () const
void SetConstantZNear (double z_near)
void SetConstantZFar (double z_far)
void UnsetConstantZNear ()
void UnsetConstantZFar ()
Protected Member Functions
size_t CurrentFrame () const
size_t CurrentKeyframe () const
double RegularizeFrameIndex (double current_frame, size_t num_of_frames, bool is_loop)
void SetViewControlFromTrajectory ()
Protected Attributes
AnimationMode animation_mode_ = AnimationMode::FreeMode
ViewTrajectory view_trajectory_
double current_frame_ = 0.0
double current_keyframe_ = 0.0
Protected Attributes inherited from cloudViewer::visualization::ViewControl
int window_width_ = 0
int window_height_ = 0
ccBBox bounding_box_
Eigen::Vector3d eye_
Eigen::Vector3d lookat_
Eigen::Vector3d up_
Eigen::Vector3d front_
Eigen::Vector3d right_
double distance_
double field_of_view_
double zoom_
double view_ratio_
double aspect_
double z_near_
double z_far_
double constant_z_near_ = -1
double constant_z_far_ = -1
gl_util::GLMatrix4f projection_matrix_
gl_util::GLMatrix4f view_matrix_
gl_util::GLMatrix4f model_matrix_
gl_util::GLMatrix4f MVP_matrix_
Eigen::Vector3d start_local_rotate_up_
Eigen::Vector3d start_local_rotate_right_
Eigen::Vector3d start_local_rotate_front_
Eigen::Vector3d start_local_rotate_eye_
Eigen::Vector3d start_local_rotate_lookat_
double local_rotate_up_accum_
double local_rotate_right_accum_
Additional Inherited Members
Static Public Attributes inherited from cloudViewer::visualization::ViewControl
static const double FIELD_OF_VIEW_MAX = 90.0
static const double FIELD_OF_VIEW_MIN = 5.0
static const double FIELD_OF_VIEW_DEFAULT = 60.0
static const double FIELD_OF_VIEW_STEP = 5.0
static const double ZOOM_DEFAULT = 0.7
static const double ZOOM_MIN = 0.02
static const double ZOOM_MAX = 2.0
static const double ZOOM_STEP = 0.02
static const double ROTATION_RADIAN_PER_PIXEL = 0.003
Detailed Description
Definition at line 17 of file ViewControlWithCustomAnimation.h.
Member Enumeration Documentation
AnimationMode
enum cloudViewer::visualization::ViewControlWithCustomAnimation::AnimationMode
Enumerator
FreeMode
PreviewMode
PlayMode
Definition at line 19 of file ViewControlWithCustomAnimation.h.
Constructor & Destructor Documentation
~ViewControlWithCustomAnimation()
virtual cloudViewer::visualization::ViewControlWithCustomAnimation::~ViewControlWithCustomAnimation () inline virtual
Definition at line 26 of file ViewControlWithCustomAnimation.h.
Member Function Documentation
AddKeyFrame()
void cloudViewer::visualization::ViewControlWithCustomAnimation::AddKeyFrame ()
Definition at line 87 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, cloudViewer::visualization::ViewControl::ConvertToViewParameters(), current_keyframe_, CurrentKeyframe(), cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
Referenced by AddSpinKeyFrames().
AddSpinKeyFrames()
void cloudViewer::visualization::ViewControlWithCustomAnimation::AddSpinKeyFrames (int num_of_key_frames = 20)
Definition at line 125 of file ViewControlWithCustomAnimation.cpp.
References AddKeyFrame(), animation_mode_, M_PI, cloudViewer::visualization::ViewControl::Rotate(), and cloudViewer::visualization::ViewControl::ROTATION_RADIAN_PER_PIXEL.
CaptureTrajectory()
bool cloudViewer::visualization::ViewControlWithCustomAnimation::CaptureTrajectory (const std::string & filename = "")
Definition at line 215 of file ViewControlWithCustomAnimation.cpp.
References cloudViewer::utility::GetCurrentTimeStamp(), LogDebug, cloudViewer::visualization::ViewTrajectory::view_status_, view_trajectory_, and cloudViewer::io::WriteIJsonConvertible().
ChangeFieldOfView()
void cloudViewer::visualization::ViewControlWithCustomAnimation::ChangeFieldOfView (double step) override virtual
Function to change field of view.
Parameters
step The step to change field of view.
Reimplemented from cloudViewer::visualization::ViewControl.
Definition at line 23 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, cloudViewer::visualization::ViewControl::ChangeFieldOfView(), cloudViewer::visualization::ViewControl::field_of_view_, cloudViewer::visualization::ViewControl::GetProjectionType(), cloudViewer::visualization::gl_util::Perspective(), cloudViewer::visualization::ViewControl::SetProjectionParameters(), cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
ChangeTrajectoryInterval()
void cloudViewer::visualization::ViewControlWithCustomAnimation::ChangeTrajectoryInterval (int change) inline
Definition at line 49 of file ViewControlWithCustomAnimation.h.
References animation_mode_, cloudViewer::visualization::ViewTrajectory::ChangeInterval(), and view_trajectory_.
ClearAllKeyFrames()
void cloudViewer::visualization::ViewControlWithCustomAnimation::ClearAllKeyFrames () inline
Definition at line 39 of file ViewControlWithCustomAnimation.h.
References cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
CurrentFrame()
size_t cloudViewer::visualization::ViewControlWithCustomAnimation::CurrentFrame () const inline protected
Definition at line 73 of file ViewControlWithCustomAnimation.h.
References current_frame_.
Referenced by GetStatusString(), and SetViewControlFromTrajectory().
CurrentKeyframe()
size_t cloudViewer::visualization::ViewControlWithCustomAnimation::CurrentKeyframe () const inline protected
Definition at line 74 of file ViewControlWithCustomAnimation.h.
References current_keyframe_.
Referenced by AddKeyFrame(), DeleteKeyFrame(), GetStatusString(), SetViewControlFromTrajectory(), and UpdateKeyFrame().
DeleteKeyFrame()
void cloudViewer::visualization::ViewControlWithCustomAnimation::DeleteKeyFrame ()
Definition at line 112 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, current_keyframe_, CurrentKeyframe(), cloudViewer::visualization::ViewTrajectory::is_loop_, RegularizeFrameIndex(), SetViewControlFromTrajectory(), cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
GetStatusString()
std::string cloudViewer::visualization::ViewControlWithCustomAnimation::GetStatusString () const
Definition at line 136 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, CurrentFrame(), CurrentKeyframe(), format, cloudViewer::visualization::ViewTrajectory::is_loop_, cloudViewer::visualization::ViewTrajectory::NumOfFrames(), cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
GetTrajectoryInterval()
int cloudViewer::visualization::ViewControlWithCustomAnimation::GetTrajectoryInterval () const inline
Definition at line 54 of file ViewControlWithCustomAnimation.h.
References cloudViewer::visualization::ViewTrajectory::interval_, and view_trajectory_.
GoToFirst()
void cloudViewer::visualization::ViewControlWithCustomAnimation::GoToFirst ()
Definition at line 191 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, current_frame_, current_keyframe_, SetViewControlFromTrajectory(), cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
Referenced by SetAnimationMode().
GoToLast()
void cloudViewer::visualization::ViewControlWithCustomAnimation::GoToLast ()
Definition at line 203 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, current_frame_, current_keyframe_, cloudViewer::visualization::ViewTrajectory::NumOfFrames(), SetViewControlFromTrajectory(), cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
IsPlaying()
bool cloudViewer::visualization::ViewControlWithCustomAnimation::IsPlaying () inline
Definition at line 66 of file ViewControlWithCustomAnimation.h.
References animation_mode_.
Referenced by IsPlayingEnd().
IsPlayingEnd()
bool cloudViewer::visualization::ViewControlWithCustomAnimation::IsPlayingEnd (size_t num) inline
Definition at line 67 of file ViewControlWithCustomAnimation.h.
References IsPlaying(), cloudViewer::visualization::ViewTrajectory::NumOfFrames(), and view_trajectory_.
IsPreviewing()
bool cloudViewer::visualization::ViewControlWithCustomAnimation::IsPreviewing () inline
Definition at line 63 of file ViewControlWithCustomAnimation.h.
References animation_mode_.
IsValidPinholeCameraTrajectory()
bool cloudViewer::visualization::ViewControlWithCustomAnimation::IsValidPinholeCameraTrajectory () const
Definition at line 270 of file ViewControlWithCustomAnimation.cpp.
References cloudViewer::visualization::ViewControl::FIELD_OF_VIEW_MIN, cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
LoadTrajectoryFromCameraTrajectory()
bool cloudViewer::visualization::ViewControlWithCustomAnimation::LoadTrajectoryFromCameraTrajectory (const camera::PinholeCameraTrajectory & camera_trajectory)
Definition at line 242 of file ViewControlWithCustomAnimation.cpp.
References cloudViewer::visualization::ViewControl::ConvertFromPinholeCameraParameters(), cloudViewer::visualization::ViewControl::ConvertToViewParameters(), current_frame_, current_keyframe_, cloudViewer::visualization::ViewTrajectory::interval_, cloudViewer::visualization::ViewTrajectory::INTERVAL_MIN, cloudViewer::visualization::ViewTrajectory::is_loop_, cloudViewer::camera::PinholeCameraTrajectory::parameters_, cloudViewer::visualization::ViewTrajectory::Reset(), SetViewControlFromTrajectory(), cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
LoadTrajectoryFromJsonFile()
bool cloudViewer::visualization::ViewControlWithCustomAnimation::LoadTrajectoryFromJsonFile (const std::string & filename)
Definition at line 230 of file ViewControlWithCustomAnimation.cpp.
References current_frame_, current_keyframe_, cloudViewer::io::ReadIJsonConvertible(), cloudViewer::visualization::ViewTrajectory::Reset(), SetViewControlFromTrajectory(), and view_trajectory_.
NumOfFrames()
size_t cloudViewer::visualization::ViewControlWithCustomAnimation::NumOfFrames () const inline
Definition at line 43 of file ViewControlWithCustomAnimation.h.
References cloudViewer::visualization::ViewTrajectory::NumOfFrames(), and view_trajectory_.
NumOfKeyFrames()
size_t cloudViewer::visualization::ViewControlWithCustomAnimation::NumOfKeyFrames () const inline
Definition at line 40 of file ViewControlWithCustomAnimation.h.
References cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
RegularizeFrameIndex()
double cloudViewer::visualization::ViewControlWithCustomAnimation::RegularizeFrameIndex (double current_frame, size_t num_of_frames, bool is_loop) protected
Definition at line 286 of file ViewControlWithCustomAnimation.cpp.
Referenced by DeleteKeyFrame(), and Step().
Reset()
void cloudViewer::visualization::ViewControlWithCustomAnimation::Reset () override virtual
Reimplemented from cloudViewer::visualization::ViewControl.
Definition at line 17 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, and cloudViewer::visualization::ViewControl::Reset().
Rotate()
void cloudViewer::visualization::ViewControlWithCustomAnimation::Rotate (double x, double y, double xo, double yo) override virtual
Function to process rotation.
Coordinates are measured in screen coordinates relative to the top-left corner of the window client area.
Parameters
x The distance the mouse cursor has moved in x-axis.
y The distance the mouse cursor has moved in y-axis.
xo Original point coordinate of the mouse in x-axis.
yo Original point coordinate of the mouse in y-axis.
Reimplemented from cloudViewer::visualization::ViewControl.
Definition at line 51 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, and cloudViewer::visualization::ViewControl::Rotate().
Scale()
void cloudViewer::visualization::ViewControlWithCustomAnimation::Scale (double scale) override virtual
Function to process scaling
Parameters
scale is the scale ratio.
Reimplemented from cloudViewer::visualization::ViewControl.
Definition at line 45 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, and cloudViewer::visualization::ViewControl::Scale().
SetAnimationMode()
void cloudViewer::visualization::ViewControlWithCustomAnimation::SetAnimationMode (AnimationMode mode)
Definition at line 69 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, cloudViewer::visualization::ViewTrajectory::ComputeInterpolationCoefficients(), GoToFirst(), cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
SetViewControlFromTrajectory()
void cloudViewer::visualization::ViewControlWithCustomAnimation::SetViewControlFromTrajectory () protected
Definition at line 310 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, cloudViewer::visualization::ViewControl::ConvertFromViewParameters(), CurrentFrame(), CurrentKeyframe(), cloudViewer::visualization::ViewTrajectory::GetInterpolatedFrame(), cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
Referenced by DeleteKeyFrame(), GoToFirst(), GoToLast(), LoadTrajectoryFromCameraTrajectory(), LoadTrajectoryFromJsonFile(), and Step().
Step()
void cloudViewer::visualization::ViewControlWithCustomAnimation::Step (double change)
Definition at line 173 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, current_frame_, current_keyframe_, cloudViewer::visualization::ViewTrajectory::is_loop_, cloudViewer::visualization::ViewTrajectory::NumOfFrames(), RegularizeFrameIndex(), SetViewControlFromTrajectory(), cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
ToggleTrajectoryLoop()
void cloudViewer::visualization::ViewControlWithCustomAnimation::ToggleTrajectoryLoop () inline
Definition at line 44 of file ViewControlWithCustomAnimation.h.
References animation_mode_, cloudViewer::visualization::ViewTrajectory::is_loop_, and view_trajectory_.
Translate()
void cloudViewer::visualization::ViewControlWithCustomAnimation::Translate (double x, double y, double xo, double yo) override virtual
Function to process translation.
Coordinates are measured in screen coordinates relative to the top-left corner of the window client area.
Parameters
x Distance the mouse cursor has moved in x-axis.
y Distance the mouse cursor has moved in y-axis.
xo Original point coordinate of the mouse in x-axis.
yo Original point coordinate of the mouse in y-axis.
Reimplemented from cloudViewer::visualization::ViewControl.
Definition at line 60 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, and cloudViewer::visualization::ViewControl::Translate().
UpdateKeyFrame()
void cloudViewer::visualization::ViewControlWithCustomAnimation::UpdateKeyFrame ()
Definition at line 104 of file ViewControlWithCustomAnimation.cpp.
References animation_mode_, cloudViewer::visualization::ViewControl::ConvertToViewParameters(), CurrentKeyframe(), cloudViewer::visualization::ViewTrajectory::view_status_, and view_trajectory_.
Member Data Documentation
animation_mode_
AnimationMode cloudViewer::visualization::ViewControlWithCustomAnimation::animation_mode_ = AnimationMode::FreeMode protected
Definition at line 81 of file ViewControlWithCustomAnimation.h.
Referenced by AddKeyFrame(), AddSpinKeyFrames(), ChangeFieldOfView(), ChangeTrajectoryInterval(), DeleteKeyFrame(), GetStatusString(), GoToFirst(), GoToLast(), IsPlaying(), IsPreviewing(), Reset(), Rotate(), Scale(), SetAnimationMode(), SetViewControlFromTrajectory(), Step(), ToggleTrajectoryLoop(), Translate(), and UpdateKeyFrame().
current_frame_
double cloudViewer::visualization::ViewControlWithCustomAnimation::current_frame_ = 0.0 protected
Definition at line 83 of file ViewControlWithCustomAnimation.h.
Referenced by CurrentFrame(), GoToFirst(), GoToLast(), LoadTrajectoryFromCameraTrajectory(), LoadTrajectoryFromJsonFile(), and Step().
current_keyframe_
double cloudViewer::visualization::ViewControlWithCustomAnimation::current_keyframe_ = 0.0 protected
Definition at line 84 of file ViewControlWithCustomAnimation.h.
Referenced by AddKeyFrame(), CurrentKeyframe(), DeleteKeyFrame(), GoToFirst(), GoToLast(), LoadTrajectoryFromCameraTrajectory(), LoadTrajectoryFromJsonFile(), and Step().
view_trajectory_
ViewTrajectory cloudViewer::visualization::ViewControlWithCustomAnimation::view_trajectory_ protected
Definition at line 82 of file ViewControlWithCustomAnimation.h.
Referenced by AddKeyFrame(), CaptureTrajectory(), ChangeFieldOfView(), ChangeTrajectoryInterval(), ClearAllKeyFrames(), DeleteKeyFrame(), GetStatusString(), GetTrajectoryInterval(), GoToFirst(), GoToLast(), IsPlayingEnd(), IsValidPinholeCameraTrajectory(), LoadTrajectoryFromCameraTrajectory(), LoadTrajectoryFromJsonFile(), NumOfFrames(), NumOfKeyFrames(), SetAnimationMode(), SetViewControlFromTrajectory(), Step(), ToggleTrajectoryLoop(), and UpdateKeyFrame().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/ViewControlWithCustomAnimation.h
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/ViewControlWithCustomAnimation.cpp