ACloudViewer: MeshWrapper< Real > Class Template Reference
MeshWrapper< Real > Class Template Reference
Public Member Functions
MeshWrapper (ccMesh &mesh, ccPointCloud &vertices, cloudViewer::ScalarField *densitySF=nullptr)
bool checkMeshCapacity ()
bool checkVertexCapacity ()
virtual void addVertex (const Real *coords) override
virtual void addNormal (const Real *coords) override
virtual void addColor (const Real *rgb) override
virtual void addDensity (double d) override
void addTriangle (size_t i1, size_t i2, size_t i3) override
bool isInErrorState () const
Protected Attributes
ccMesh & m_mesh
ccPointCloud & m_vertices
bool m_error
cloudViewer::ScalarField * m_densitySF
Detailed Description
template<typename Real>
class MeshWrapper< Real >
Definition at line 89 of file qPoissonRecon.cpp.
Constructor & Destructor Documentation
MeshWrapper()
template<typename Real > MeshWrapper< Real >::MeshWrapper (ccMesh & mesh, ccPointCloud & vertices, cloudViewer::ScalarField * densitySF = nullptr) inline explicit
Definition at line 91 of file qPoissonRecon.cpp.
Member Function Documentation
addColor()
template<typename Real > virtual void MeshWrapper< Real >::addColor (const Real * rgb) inline override virtual
Implements PoissonReconLib::IMesh< Real >.
Definition at line 145 of file qPoissonRecon.cpp.
References ccPointCloud::addRGBColor(), MeshWrapper< Real >::checkVertexCapacity(), ccPointCloud::hasColors(), MeshWrapper< Real >::m_error, MeshWrapper< Real >::m_vertices, max(), min(), and ccPointCloud::reserveTheRGBTable().
addDensity()
template<typename Real > virtual void MeshWrapper< Real >::addDensity (double d) inline override virtual
Implements PoissonReconLib::IMesh< Real >.
Definition at line 163 of file qPoissonRecon.cpp.
References cloudViewer::ScalarField::addElement(), MeshWrapper< Real >::m_densitySF, MeshWrapper< Real >::m_error, and cloudViewer::ScalarField::reserveSafe().
addNormal()
template<typename Real > virtual void MeshWrapper< Real >::addNormal (const Real * coords) inline override virtual
Implements PoissonReconLib::IMesh< Real >.
Definition at line 133 of file qPoissonRecon.cpp.
References ccPointCloud::addNorm(), MeshWrapper< Real >::checkVertexCapacity(), Vector3Tpl< PointCoordinateType >::fromArray(), ccPointCloud::hasNormals(), MeshWrapper< Real >::m_error, MeshWrapper< Real >::m_vertices, and ccPointCloud::reserveTheNormsTable().
addTriangle()
template<typename Real > void MeshWrapper< Real >::addTriangle (size_t i1, size_t i2, size_t i3) inline override virtual
Implements PoissonReconLib::IMesh< Real >.
Definition at line 175 of file qPoissonRecon.cpp.
References ccMesh::addTriangle(), MeshWrapper< Real >::checkMeshCapacity(), and MeshWrapper< Real >::m_mesh.
addVertex()
template<typename Real > virtual void MeshWrapper< Real >::addVertex (const Real * coords) inline override virtual
Implements PoissonReconLib::IMesh< Real >.
Definition at line 125 of file qPoissonRecon.cpp.
References cloudViewer::PointCloudTpl< T >::addPoint(), MeshWrapper< Real >::checkVertexCapacity(), Vector3Tpl< PointCoordinateType >::fromArray(), and MeshWrapper< Real >::m_vertices.
checkMeshCapacity()
template<typename Real > bool MeshWrapper< Real >::checkMeshCapacity () inline
Definition at line 99 of file qPoissonRecon.cpp.
References ccMesh::capacity(), MeshWrapper< Real >::m_error, MeshWrapper< Real >::m_mesh, ccMesh::reserve(), and ccMesh::size().
Referenced by MeshWrapper< Real >::addTriangle().
checkVertexCapacity()
template<typename Real > bool MeshWrapper< Real >::checkVertexCapacity () inline
Definition at line 112 of file qPoissonRecon.cpp.
References cloudViewer::PointCloudTpl< T >::capacity(), MeshWrapper< Real >::m_error, MeshWrapper< Real >::m_vertices, ccPointCloud::reserve(), and cloudViewer::PointCloudTpl< T >::size().
Referenced by MeshWrapper< Real >::addColor(), MeshWrapper< Real >::addNormal(), and MeshWrapper< Real >::addVertex().
isInErrorState()
template<typename Real > bool MeshWrapper< Real >::isInErrorState () const inline
Definition at line 183 of file qPoissonRecon.cpp.
References MeshWrapper< Real >::m_error.
Referenced by doReconstruct().
Member Data Documentation
m_densitySF
template<typename Real > cloudViewer::ScalarField* MeshWrapper< Real >::m_densitySF protected
Definition at line 189 of file qPoissonRecon.cpp.
Referenced by MeshWrapper< Real >::addDensity().
m_error
template<typename Real > bool MeshWrapper< Real >::m_error protected
Definition at line 188 of file qPoissonRecon.cpp.
Referenced by MeshWrapper< Real >::addColor(), MeshWrapper< Real >::addDensity(), MeshWrapper< Real >::addNormal(), MeshWrapper< Real >::checkMeshCapacity(), MeshWrapper< Real >::checkVertexCapacity(), and MeshWrapper< Real >::isInErrorState().
m_mesh
template<typename Real > ccMesh& MeshWrapper< Real >::m_mesh protected
Definition at line 186 of file qPoissonRecon.cpp.
Referenced by MeshWrapper< Real >::addTriangle(), and MeshWrapper< Real >::checkMeshCapacity().
m_vertices
template<typename Real > ccPointCloud& MeshWrapper< Real >::m_vertices protected
Definition at line 187 of file qPoissonRecon.cpp.
Referenced by MeshWrapper< Real >::addColor(), MeshWrapper< Real >::addNormal(), MeshWrapper< Real >::addVertex(), and MeshWrapper< Real >::checkVertexCapacity().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qPoissonRecon/src/qPoissonRecon.cpp