ACloudViewer: colmap::DatabaseCache Class Reference
colmap::DatabaseCache Class Reference
#include <database_cache.h>
Public Member Functions
DatabaseCache ()
size_t NumCameras () const
size_t NumImages () const
class Camera & Camera (const camera_t camera_id)
const class Camera & Camera (const camera_t camera_id) const
class Image & Image (const image_t image_id)
const class Image & Image (const image_t image_id) const
const std::unordered_map< camera_t, class Camera > & Cameras () const
const std::unordered_map< image_t, class Image > & Images () const
bool ExistsCamera (const camera_t camera_id) const
bool ExistsImage (const image_t image_id) const
const class CorrespondenceGraph & CorrespondenceGraph () const
void AddCamera (const class Camera &camera)
void AddImage (const class Image &image)
void Load (const Database &database, const size_t min_num_matches, const bool ignore_watermarks, const std::unordered_set< std::string > &image_names)
const class Image * FindImageWithName (const std::string &name) const
Detailed Description
Definition at line 28 of file database_cache.h.
Constructor & Destructor Documentation
DatabaseCache()
colmap::DatabaseCache::DatabaseCache ()
Definition at line 42 of file database_cache.cc.
Member Function Documentation
AddCamera()
void colmap::DatabaseCache::AddCamera (const class Camera & camera)
Definition at line 44 of file database_cache.cc.
References colmap::Camera::CameraId(), and ExistsCamera().
Referenced by BOOST_AUTO_TEST_CASE().
AddImage()
void colmap::DatabaseCache::AddImage (const class Image & image)
Definition at line 49 of file database_cache.cc.
References colmap::CorrespondenceGraph::AddImage(), ExistsImage(), and image.
Referenced by BOOST_AUTO_TEST_CASE().
Camera() [1/2]
class Camera & colmap::DatabaseCache::Camera (const camera_t camera_id) inline
Definition at line 88 of file database_cache.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::IncrementalMapper::RegisterNextImage().
Camera() [2/2]
const class Camera & colmap::DatabaseCache::Camera (const camera_t camera_id) const inline
Definition at line 92 of file database_cache.h.
Cameras()
const std::unordered_map< camera_t, class Camera > & colmap::DatabaseCache::Cameras () const inline
Definition at line 104 of file database_cache.h.
Referenced by colmap::Reconstruction::Load().
CorrespondenceGraph()
const class CorrespondenceGraph & colmap::DatabaseCache::CorrespondenceGraph () const inline
Definition at line 121 of file database_cache.h.
Referenced by colmap::IncrementalMapper::BeginReconstruction(), BOOST_AUTO_TEST_CASE(), colmap::Reconstruction::Load(), colmap::IncrementalMapper::RegisterInitialImagePair(), and colmap::IncrementalMapper::RegisterNextImage().
ExistsCamera()
bool colmap::DatabaseCache::ExistsCamera (const camera_t camera_id) const inline
Definition at line 113 of file database_cache.h.
Referenced by AddCamera(), and BOOST_AUTO_TEST_CASE().
ExistsImage()
bool colmap::DatabaseCache::ExistsImage (const image_t image_id) const inline
Definition at line 117 of file database_cache.h.
Referenced by AddImage(), BOOST_AUTO_TEST_CASE(), and colmap::IncrementalMapper::FindInitialImagePair().
FindImageWithName()
const class Image * colmap::DatabaseCache::FindImageWithName (const std::string & name) const
Definition at line 206 of file database_cache.cc.
References image, and name.
Image() [1/2]
class Image & colmap::DatabaseCache::Image (const image_t image_id) inline
Definition at line 96 of file database_cache.h.
Referenced by BOOST_AUTO_TEST_CASE().
Image() [2/2]
const class Image & colmap::DatabaseCache::Image (const image_t image_id) const inline
Definition at line 100 of file database_cache.h.
Images()
const std::unordered_map< image_t, class Image > & colmap::DatabaseCache::Images () const inline
Definition at line 109 of file database_cache.h.
Referenced by colmap::Reconstruction::Load().
Load()
void colmap::DatabaseCache::Load (const Database & database, const size_t min_num_matches, const bool ignore_watermarks, const std::unordered_set< std::string > & image_names)
Definition at line 55 of file database_cache.cc.
References colmap::CorrespondenceGraph::AddCorrespondences(), colmap::CorrespondenceGraph::AddImage(), colmap::Timer::ElapsedSeconds(), QtCompat::endl(), colmap::FeatureKeypointsToPointsVector(), colmap::CorrespondenceGraph::Finalize(), image, colmap::CorrespondenceGraph::NumCorrespondencesForImage(), colmap::CorrespondenceGraph::NumObservationsForImage(), colmap::Database::PairIdToImagePair(), points, colmap::Database::ReadAllCameras(), colmap::Database::ReadAllImages(), colmap::Database::ReadKeypoints(), colmap::Database::ReadTwoViewGeometries(), colmap::Timer::Restart(), colmap::Timer::Start(), colmap::StringPrintf(), and colmap::TwoViewGeometry::WATERMARK.
Referenced by colmap::RunImageRegistrator(), and colmap::RunPointTriangulator().
NumCameras()
size_t colmap::DatabaseCache::NumCameras () const inline
Definition at line 85 of file database_cache.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::Load().
NumImages()
size_t colmap::DatabaseCache::NumImages () const inline
Definition at line 86 of file database_cache.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::Load().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/database_cache.h
/root/ACloudViewer/libs/Reconstruction/src/base/database_cache.cc