ACloudViewer: cloudViewer::visualization::gui::Color Class Reference
cloudViewer::visualization::gui::Color Class Reference
#include <Color.h>
Public Member Functions
Color ()
Color (float r, float g, float b, float a=1.0)
Color (const Eigen::Vector3f &rgb)
float GetRed () const
float GetGreen () const
float GetBlue () const
float GetAlpha () const
void SetColor (float r, float g, float b, float a=1.0)
const float * GetPointer () const
float * GetMutablePointer ()
Color Lightened (float amount)
unsigned int ToABGR32 () const
bool operator== (const Color &rhs) const
bool operator!= (const Color &rhs) const
Detailed Description
Definition at line 16 of file Color.h.
Constructor & Destructor Documentation
Color() [1/3]
cloudViewer::visualization::gui::Color::Color ()
Definition at line 17 of file Color.cpp.
Referenced by Lightened().
Color() [2/3]
cloudViewer::visualization::gui::Color::Color (float r, float g, float b, float a = 1.0)
Definition at line 19 of file Color.cpp.
Color() [3/3]
cloudViewer::visualization::gui::Color::Color (const Eigen::Vector3f & rgb)
Definition at line 22 of file Color.cpp.
Member Function Documentation
GetAlpha()
float cloudViewer::visualization::gui::Color::GetAlpha () const
Definition at line 37 of file Color.cpp.
Referenced by Lightened(), and ToABGR32().
GetBlue()
float cloudViewer::visualization::gui::Color::GetBlue () const
Definition at line 36 of file Color.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView(), Lightened(), and ToABGR32().
GetGreen()
float cloudViewer::visualization::gui::Color::GetGreen () const
Definition at line 35 of file Color.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView(), Lightened(), and ToABGR32().
GetMutablePointer()
float * cloudViewer::visualization::gui::Color::GetMutablePointer ()
Definition at line 50 of file Color.cpp.
GetPointer()
const float * cloudViewer::visualization::gui::Color::GetPointer () const
Definition at line 49 of file Color.cpp.
GetRed()
float cloudViewer::visualization::gui::Color::GetRed () const
Definition at line 34 of file Color.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView(), Lightened(), and ToABGR32().
Lightened()
Color cloudViewer::visualization::gui::Color::Lightened (float amount)
Returns a lighter color.
Parameters
amount is between 0 and 1, with 0 being the same color and 1 being white.
Definition at line 52 of file Color.cpp.
References Color(), GetAlpha(), GetBlue(), GetGreen(), GetRed(), max(), and min().
operator!=()
bool cloudViewer::visualization::gui::Color::operator!= (const Color & rhs) const
Definition at line 30 of file Color.cpp.
References operator==().
operator==()
bool cloudViewer::visualization::gui::Color::operator== (const Color & rhs) const
Definition at line 25 of file Color.cpp.
Referenced by operator!=().
SetColor()
void cloudViewer::visualization::gui::Color::SetColor (float r, float g, float b, float a = 1.0)
Definition at line 39 of file Color.cpp.
ToABGR32()
unsigned int cloudViewer::visualization::gui::Color::ToABGR32 () const
Definition at line 59 of file Color.cpp.
References GetAlpha(), GetBlue(), GetGreen(), and GetRed().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Color.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Color.cpp