ACloudViewer: ecvApplicationBase Class Reference
ecvApplicationBase Class Reference
#include <ecvApplicationBase.h>
Public Member Functions
ecvApplicationBase (int &argc, char **argv, bool isCommandLine, const QString &version)
bool isCommandLine () const
QString versionStr () const
QString versionLongStr (bool includeOS) const
const QString & translationPath () const
bool setAppStyle (const QString &styleKey)
Set the application style.
Public Member Functions inherited from QApplication
QApplication (int argc, char **argv)
Static Public Member Functions
static void InitOpenGL ()
Detailed Description
Definition at line 35 of file ecvApplicationBase.h.
Constructor & Destructor Documentation
ecvApplicationBase()
ecvApplicationBase::ecvApplicationBase (int & argc, char ** argv, bool isCommandLine, const QString & version)
Definition at line 88 of file ecvApplicationBase.cpp.
References ecvPS::AppStyle(), ccPluginManager::get(), ccTranslationManager::get(), ccTranslationManager::loadTranslations(), ccTranslationManager::registerTranslatorFile(), ccMaterial::ReleaseTextures(), and ccPluginManager::setPaths().
Member Function Documentation
InitOpenGL()
void ecvApplicationBase::InitOpenGL () static
This must be called before instantiating the application class so it can setup OpenGL first.
Calling QSurfaceFormat::setDefaultFormat() before constructing the QApplication instance is mandatory on some platforms (for example, OS X) when an OpenGL core profile context is requested. This is to ensure that resource sharing between contexts stays functional as all internal contexts are created using the correct version and profile.
Definition at line 40 of file ecvApplicationBase.cpp.
References format.
Referenced by main().
isCommandLine()
bool ecvApplicationBase::isCommandLine () const inline
Definition at line 46 of file ecvApplicationBase.h.
setAppStyle()
bool ecvApplicationBase::setAppStyle (const QString & styleKey)
Set the application style.
Parameters
styleKey Style name (from QStyleFactory::keys() or custom like "QDarkStyleSheet::Dark")
Returns
true if successful, false otherwise
Supported style keys:
Any Qt native style (e.g., "Fusion", "Windows", "macOS", "macintosh")
"QDarkStyleSheet::Dark" - Dark theme (if available)
"QDarkStyleSheet::Light" - Light theme (if available)
On macOS, the native "macintosh" or "macOS" style is used by default if available, providing native macOS appearance.
Definition at line 302 of file ecvApplicationBase.cpp.
References ecvPS::AppStyle(), CVLog::Print(), ecvSettingManager::setValue(), and CVLog::Warning().
translationPath()
const QString & ecvApplicationBase::translationPath () const
Definition at line 205 of file ecvApplicationBase.cpp.
versionLongStr()
QString ecvApplicationBase::versionLongStr (bool includeOS) const
Definition at line 172 of file ecvApplicationBase.cpp.
versionStr()
QString ecvApplicationBase::versionStr () const
Definition at line 170 of file ecvApplicationBase.cpp.
Referenced by ecvApplication::ecvApplication().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVAppCommon/include/ecvApplicationBase.h
/root/ACloudViewer/libs/CVAppCommon/src/ecvApplicationBase.cpp