ACloudViewer: VtkUtils::VtkFileReader Class Reference
VtkUtils::VtkFileReader Class Reference
#include <filereaderutils.h>
Public Member Functions
VtkFileReader (QObject *parent=nullptr)
void run ()
Public Member Functions inherited from VtkUtils::AbstractFileReader
AbstractFileReader (QObject *parent=nullptr)
void setFileName (const QString &file)
QString fileName () const
void setTitle (const QString &title)
QString title () const
Public Member Functions inherited from VtkUtils::ReaderTempl< vtkGenericDataObjectReader >
virtual vtkDataObject * dataObject () const
vtkGenericDataObjectReader * reader () const
Additional Inherited Members
Signals inherited from VtkUtils::AbstractFileReader
void finished ()
Protected Attributes inherited from VtkUtils::AbstractFileReader
QString m_fileName
QString m_title
Protected Attributes inherited from VtkUtils::ReaderTempl< vtkGenericDataObjectReader >
vtkGenericDataObjectReader * m_reader
vtkDataObject * m_dataObject
Detailed Description
Definition at line 67 of file filereaderutils.h.
Constructor & Destructor Documentation
VtkFileReader()
VtkUtils::VtkFileReader::VtkFileReader (QObject * parent = nullptr) explicit
Definition at line 114 of file filereaderutils.cpp.
Member Function Documentation
run()
void VtkUtils::VtkFileReader::run ()
Definition at line 116 of file filereaderutils.cpp.
References VtkUtils::AbstractFileReader::fileName(), VtkUtils::AbstractFileReader::finished(), VtkUtils::ReaderTempl< vtkGenericDataObjectReader >::m_reader, and VtkUtils::vtkInitOnce().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/filereaderutils.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/filereaderutils.cpp