ACloudViewer: GetCellBBoxVisitor Class Reference
GetCellBBoxVisitor Class Reference
Recursive visitor for ccKdTree::getCellBBox.
Public Member Functions
GetCellBBoxVisitor ()
void visit (ccKdTree::BaseNode *node)
Public Attributes
ccBBox m_UpdatedBox
Detailed Description
Recursive visitor for ccKdTree::getCellBBox.
Definition at line 211 of file ecvKdTree.cpp.
Constructor & Destructor Documentation
GetCellBBoxVisitor()
GetCellBBoxVisitor::GetCellBBoxVisitor () inline
Definition at line 215 of file ecvKdTree.cpp.
References m_UpdatedBox, cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), and PC_NAN.
Member Function Documentation
visit()
void GetCellBBoxVisitor::visit (ccKdTree::BaseNode * node) inline
Definition at line 221 of file ecvKdTree.cpp.
References cloudViewer::TrueKdTree::BaseNode::isNode(), cloudViewer::TrueKdTree::Node::leftChild, m_UpdatedBox, cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), cloudViewer::TrueKdTree::BaseNode::parent, cloudViewer::TrueKdTree::Node::splitDim, cloudViewer::TrueKdTree::Node::splitValue, and Tuple3Tpl< Type >::u.
Referenced by ccKdTree::getCellBBox().
Member Data Documentation
m_UpdatedBox
ccBBox GetCellBBoxVisitor::m_UpdatedBox
Definition at line 213 of file ecvKdTree.cpp.
Referenced by ccKdTree::getCellBBox(), GetCellBBoxVisitor(), and visit().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/src/ecvKdTree.cpp