ACloudViewer: PythonActionLauncher Class Reference
PythonActionLauncher Class Reference
#include <PythonActionLauncher.h>
Public Member Functions
PythonActionLauncher (const PythonPluginManager *pluginManager, PythonInterpreter *interpreter, QWidget *parent=nullptr)
Protected Member Functions
void showEvent (QShowEvent *event) override
void populateToolBox ()
void clearToolBox ()
void disable ()
void enable ()
Detailed Description
Definition at line 18 of file PythonActionLauncher.h.
Constructor & Destructor Documentation
PythonActionLauncher()
PythonActionLauncher::PythonActionLauncher (const PythonPluginManager * pluginManager, PythonInterpreter * interpreter, QWidget * parent = nullptr) explicit
Definition at line 64 of file PythonActionLauncher.cpp.
References ACTION_LAUNCHER_ICON_PATH, disable(), enable(), PythonInterpreter::executionFinished(), and PythonInterpreter::executionStarted().
Member Function Documentation
clearToolBox()
void PythonActionLauncher::clearToolBox () protected
Definition at line 98 of file PythonActionLauncher.cpp.
Referenced by showEvent().
disable()
void PythonActionLauncher::disable () protected
Definition at line 89 of file PythonActionLauncher.cpp.
Referenced by PythonActionLauncher().
enable()
void PythonActionLauncher::enable () protected
Definition at line 93 of file PythonActionLauncher.cpp.
Referenced by PythonActionLauncher().
populateToolBox()
void PythonActionLauncher::populateToolBox () protected
Definition at line 109 of file PythonActionLauncher.cpp.
References PluginListModel::handleDoubleClick(), and PythonPluginManager::plugins().
Referenced by showEvent().
showEvent()
void PythonActionLauncher::showEvent (QShowEvent * event) override protected
Definition at line 82 of file PythonActionLauncher.cpp.
References clearToolBox(), event, and populateToolBox().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonActionLauncher.h
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonActionLauncher.cpp