ACloudViewer: ShaderMan Class Reference
ShaderMan Class Reference
#include <ShaderMan.h>
Static Public Member Functions
static void SelectInitialSmoothingFilter (int octave_min, SiftParam &param)
static void UseShaderMarginCopy (int xmax, int ymax)
static void UseShaderOrientation (int gtex, int width, int height, float sigma, int auxtex, float step, int keypoint_list)
static void UseShaderDescriptor (int gtex, int otex, int dwidth, int fwidth, int width, int height, float sigma)
static void UseShaderSimpleOrientation (int oTex, float sigma, float sigma_step)
static void UseShaderCopyKeypoint ()
static void UseShaderGenVBO (float width, float fwidth, float size)
static void UseShaderDebug ()
static void UseShaderZeroPass ()
static void UseShaderGenListStart (float fw, int tex0)
static void UseShaderGenListStep (int tex, int tex0)
static void UseShaderGenListEnd (int ktex)
static void UseShaderGenListHisto ()
static void UseShaderGenListInit (int w, int h, int tight=1)
static void UseShaderKeypoint (int texU, int texD)
static void UseShaderGradientPass (int texP=0)
static void UseShaderDisplayKeypoints ()
static void UseShaderDisplayGrad ()
static void UseShaderRGB2Gray ()
static void UseShaderDisplayDOG ()
static void UseShaderDisplayGaussian ()
static void FilterInitialImage (GLTexImage *tex, GLTexImage *buf)
static void FilterSampledImage (GLTexImage *tex, GLTexImage *buf)
static void FilterImage (FilterProgram *filter, GLTexImage *dst, GLTexImage *src, GLTexImage *tmp)
static void TextureCopy (GLTexImage *dst, GLTexImage *src)
static void TextureDownSample (GLTexImage *dst, GLTexImage *src, int scale=2)
static void TextureUpSample (GLTexImage *dst, GLTexImage *src, int scale)
static void InitShaderMan (SiftParam &param)
static void DestroyShaders ()
static int HaveShaderMan ()
static void UnloadProgram ()
Static Public Attributes
static ShaderBag * s_bag = NULL
Detailed Description
Definition at line 40 of file ShaderMan.h.
Member Function Documentation
DestroyShaders()
void ShaderMan::DestroyShaders () static
Definition at line 65 of file ShaderMan.cpp.
References NULL, and s_bag.
Referenced by PyramidGL::~PyramidGL().
FilterImage()
void ShaderMan::FilterImage (FilterProgram * filter, GLTexImage * dst, GLTexImage * src, GLTexImage * tmp) static
Definition at line 76 of file ShaderMan.cpp.
References FilterProgram::_size, GLTexImage::AttachToFBO(), GLTexImage::BindTex(), GLTexImage::DetachFBO(), GLTexImage::DrawQuad(), GLTexImage::FillMargin(), GLTexImage::FitTexViewPort(), NULL, FilterProgram::s_shader_h, FilterProgram::s_shader_v, GLTexImage::UnbindTex(), UnloadProgram(), and ProgramGPU::UseProgram().
Referenced by PyramidNaive::BuildPyramid(), PyramidPacked::BuildPyramid(), FilterInitialImage(), and FilterSampledImage().
FilterInitialImage()
void ShaderMan::FilterInitialImage (GLTexImage * tex, GLTexImage * buf) static
Definition at line 129 of file ShaderMan.cpp.
References ShaderBag::f_gaussian_skip0, FilterImage(), and s_bag.
Referenced by PyramidNaive::BuildPyramid(), and PyramidPacked::BuildPyramid().
FilterSampledImage()
void ShaderMan::FilterSampledImage (GLTexImage * tex, GLTexImage * buf) static
Definition at line 134 of file ShaderMan.cpp.
References ShaderBag::f_gaussian_skip1, FilterImage(), and s_bag.
Referenced by PyramidNaive::BuildPyramid(), and PyramidPacked::BuildPyramid().
HaveShaderMan()
static int ShaderMan::HaveShaderMan () inline static
Definition at line 76 of file ShaderMan.h.
References NULL, and s_bag.
Referenced by GLTexInput::SetImageData().
InitShaderMan()
void ShaderMan::InitShaderMan (SiftParam & param) static
Definition at line 48 of file ShaderMan.cpp.
References GlobalParam::_usePackedTex, GlobalParam::_UseSiftGPUEX, GlobalUtil::CheckErrorsGL(), ShaderBag::LoadDisplayShaders(), ShaderBag::LoadDynamicShaders(), ShaderBag::LoadFixedShaders(), s_bag, GlobalUtil::StartTimer(), and GlobalUtil::StopTimer().
Referenced by PyramidGL::InitializeContext().
SelectInitialSmoothingFilter()
void ShaderMan::SelectInitialSmoothingFilter (int octave_min, SiftParam & param) static
Definition at line 346 of file ShaderMan.cpp.
References s_bag, and ShaderBag::SelectInitialSmoothingFilter().
Referenced by PyramidNaive::InitPyramid(), and PyramidPacked::InitPyramid().
TextureCopy()
void ShaderMan::TextureCopy (GLTexImage * dst, GLTexImage * src) static
Definition at line 139 of file ShaderMan.cpp.
References GLTexImage::AttachToFBO(), GLTexImage::BindTex(), GLTexImage::DetachFBO(), GLTexImage::DrawQuad(), GLTexImage::FitTexViewPort(), and GLTexImage::UnbindTex().
TextureDownSample()
void ShaderMan::TextureDownSample (GLTexImage * dst, GLTexImage * src, int scale = 2) static
Definition at line 155 of file ShaderMan.cpp.
References GLTexImage::AttachToFBO(), GLTexImage::BindTex(), GLTexImage::DetachFBO(), GLTexImage::DrawQuadDS(), GLTexImage::FitTexViewPort(), s_bag, ShaderBag::s_sampling, GLTexImage::UnbindTex(), UnloadProgram(), and ProgramGPU::UseProgram().
Referenced by PyramidNaive::BuildPyramid(), and PyramidPacked::BuildPyramid().
TextureUpSample()
void ShaderMan::TextureUpSample (GLTexImage * dst, GLTexImage * src, int scale) static
Definition at line 177 of file ShaderMan.cpp.
References GlobalParam::_usePackedTex, GLTexImage::AttachToFBO(), GLTexImage::BindTex(), GLTexImage::DetachFBO(), GLTexImage::DrawQuadUS(), GLTexImage::FitTexViewPort(), s_bag, ShaderBag::s_sampling, GlobalUtil::SetTextureParameter(), GlobalUtil::SetTextureParameterUS(), GLTexImage::UnbindTex(), UnloadProgram(), and ProgramGPU::UseProgram().
Referenced by PyramidNaive::BuildPyramid(), and PyramidPacked::BuildPyramid().
UnloadProgram()
void ShaderMan::UnloadProgram (void) static
Definition at line 71 of file ShaderMan.cpp.
References s_bag, and ShaderBag::UnloadProgram().
Referenced by PyramidNaive::BuildPyramid(), PyramidPacked::BuildPyramid(), PyramidGL::CleanUpAfterSIFT(), PyramidNaive::ComputeGradient(), PyramidPacked::ComputeGradient(), PyramidNaive::DetectKeypointsEX(), PyramidPacked::DetectKeypointsEX(), FilterImage(), PyramidGL::GetFeatureDescriptors(), GLTexImage::TexConvertRGB(), GLTexPacked::TexConvertRGB(), TextureDownSample(), and TextureUpSample().
UseShaderCopyKeypoint()
void ShaderMan::UseShaderCopyKeypoint () static
Definition at line 314 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_copy_key, and ProgramGPU::UseProgram().
Referenced by PyramidGL::GenerateFeatureDisplayVBO().
UseShaderDebug()
void ShaderMan::UseShaderDebug () static
Definition at line 293 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_debug, and ProgramGPU::UseProgram().
UseShaderDescriptor()
void ShaderMan::UseShaderDescriptor (int gtex, int otex, int dwidth, int fwidth, int width, int height, float sigma) static
Definition at line 340 of file ShaderMan.cpp.
References height, s_bag, ShaderBag::s_descriptor_fp, ShaderBag::SetFeatureDescirptorParam(), ProgramGPU::UseProgram(), and width.
Referenced by PyramidGL::GetFeatureDescriptors().
UseShaderDisplayDOG()
void ShaderMan::UseShaderDisplayDOG () static
Definition at line 211 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_display_dog, and ProgramGPU::UseProgram().
Referenced by SiftGPUEX::DisplaySIFT().
UseShaderDisplayGaussian()
void ShaderMan::UseShaderDisplayGaussian () static
Definition at line 206 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_display_gaussian, and ProgramGPU::UseProgram().
Referenced by SiftGPUEX::DisplaySIFT().
UseShaderDisplayGrad()
void ShaderMan::UseShaderDisplayGrad () static
Definition at line 224 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_display_grad, and ProgramGPU::UseProgram().
Referenced by SiftGPUEX::DisplaySIFT().
UseShaderDisplayKeypoints()
void ShaderMan::UseShaderDisplayKeypoints () static
Definition at line 230 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_display_keys, and ProgramGPU::UseProgram().
Referenced by SiftGPUEX::DisplaySIFT().
UseShaderGenListEnd()
void ShaderMan::UseShaderGenListEnd (int ktex) static
Definition at line 287 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_genlist_end, ShaderBag::SetGenListEndParam(), and ProgramGPU::UseProgram().
UseShaderGenListHisto()
void ShaderMan::UseShaderGenListHisto () static
Definition at line 266 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_genlist_histo, and ProgramGPU::UseProgram().
UseShaderGenListInit()
void ShaderMan::UseShaderGenListInit (int w, int h, int tight = 1) static
Definition at line 254 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_genlist_init_ex, ShaderBag::s_genlist_init_tight, ShaderBag::SetGenListInitParam(), and ProgramGPU::UseProgram().
UseShaderGenListStart()
void ShaderMan::UseShaderGenListStart (float fw, int tex0) static
Definition at line 275 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_genlist_start, ShaderBag::SetGenListStartParam(), and ProgramGPU::UseProgram().
UseShaderGenListStep()
void ShaderMan::UseShaderGenListStep (int tex, int tex0) static
Definition at line 281 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_genlist_step, ShaderBag::SetGenListStepParam(), and ProgramGPU::UseProgram().
UseShaderGenVBO()
void ShaderMan::UseShaderGenVBO (float width, float fwidth, float size) static
Definition at line 303 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_vertex_list, ShaderBag::SetGenVBOParam(), size, ProgramGPU::UseProgram(), and width.
Referenced by PyramidGL::GenerateFeatureDisplayVBO().
UseShaderGradientPass()
void ShaderMan::UseShaderGradientPass (int texP = 0) static
Definition at line 239 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_grad_pass, ShaderBag::SetGradPassParam(), and ProgramGPU::UseProgram().
Referenced by PyramidNaive::ComputeGradient(), PyramidPacked::ComputeGradient(), PyramidNaive::DetectKeypointsEX(), and PyramidPacked::DetectKeypointsEX().
UseShaderKeypoint()
void ShaderMan::UseShaderKeypoint (int texU, int texD) static
Definition at line 246 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_keypoint, ShaderBag::SetDogTexParam(), and ProgramGPU::UseProgram().
Referenced by PyramidNaive::DetectKeypointsEX(), and PyramidPacked::DetectKeypointsEX().
UseShaderMarginCopy()
void ShaderMan::UseShaderMarginCopy (int xmax, int ymax) static
Definition at line 308 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_margin_copy, ShaderBag::SetMarginCopyParam(), and ProgramGPU::UseProgram().
Referenced by GLTexImage::FillMargin(), and GLTexPacked::FillMargin().
UseShaderOrientation()
void ShaderMan::UseShaderOrientation (int gtex, int width, int height, float sigma, int auxtex, float step, int keypoint_list) static
Definition at line 327 of file ShaderMan.cpp.
References GlobalParam::_FixedOrientation, height, s_bag, ShaderBag::s_orientation, ShaderBag::SetFeatureOrientationParam(), ProgramGPU::UseProgram(), and width.
Referenced by PyramidNaive::GetFeatureOrientations(), and PyramidPacked::GetFeatureOrientations().
UseShaderRGB2Gray()
void ShaderMan::UseShaderRGB2Gray () static
Definition at line 218 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_gray, and ProgramGPU::UseProgram().
Referenced by GLTexImage::TexConvertRGB(), and GLTexPacked::TexConvertRGB().
UseShaderSimpleOrientation()
void ShaderMan::UseShaderSimpleOrientation (int oTex, float sigma, float sigma_step) static
Definition at line 319 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_orientation, ShaderBag::SetSimpleOrientationInput(), and ProgramGPU::UseProgram().
Referenced by PyramidNaive::GetSimplifiedOrientation(), and PyramidPacked::GetSimplifiedOrientation().
UseShaderZeroPass()
void ShaderMan::UseShaderZeroPass () static
Definition at line 298 of file ShaderMan.cpp.
References s_bag, ShaderBag::s_zero_pass, and ProgramGPU::UseProgram().
Referenced by GLTexPacked::ZeroHistoMargin(), and GLTexImage::ZeroHistoMargin().
Member Data Documentation
s_bag
ShaderBag * ShaderMan::s_bag = NULL static
Definition at line 43 of file ShaderMan.h.
Referenced by PyramidNaive::BuildPyramid(), PyramidPacked::BuildPyramid(), DestroyShaders(), FilterInitialImage(), FilterSampledImage(), HaveShaderMan(), InitShaderMan(), SelectInitialSmoothingFilter(), TextureDownSample(), TextureUpSample(), UnloadProgram(), UseShaderCopyKeypoint(), UseShaderDebug(), UseShaderDescriptor(), UseShaderDisplayDOG(), UseShaderDisplayGaussian(), UseShaderDisplayGrad(), UseShaderDisplayKeypoints(), UseShaderGenListEnd(), UseShaderGenListHisto(), UseShaderGenListInit(), UseShaderGenListStart(), UseShaderGenListStep(), UseShaderGenVBO(), UseShaderGradientPass(), UseShaderKeypoint(), UseShaderMarginCopy(), UseShaderOrientation(), UseShaderRGB2Gray(), UseShaderSimpleOrientation(), and UseShaderZeroPass().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/ShaderMan.h
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/ShaderMan.cpp