ACloudViewer: cloudViewer::core::nns::KnnIndex Class Reference
cloudViewer::core::nns::KnnIndex Class Reference
#include <KnnIndex.h>
Public Member Functions
KnnIndex ()
KnnIndex (const Tensor &dataset_points)
Parameterized Constructor.
KnnIndex (const Tensor &dataset_points, const Dtype &index_dtype)
~KnnIndex ()
KnnIndex (const KnnIndex &)=delete
KnnIndex & operator= (const KnnIndex &)=delete
bool SetTensorData (const Tensor &dataset_points, const Dtype &index_dtype=core::Int64) override
bool SetTensorData (const Tensor &dataset_points, const Tensor &points_row_splits, const Dtype &index_dtype=core::Int64)
bool SetTensorData (const Tensor &dataset_points, double radius, const Dtype &index_dtype=core::Int64) override
std::pair< Tensor, Tensor > SearchKnn (const Tensor &query_points, int knn) const override
std::pair< Tensor, Tensor > SearchKnn (const Tensor &query_points, const Tensor &queries_row_splits, int knn) const
std::tuple< Tensor, Tensor, Tensor > SearchRadius (const Tensor &query_points, const Tensor &radii, bool sort) const override
std::tuple< Tensor, Tensor, Tensor > SearchRadius (const Tensor &query_points, const double radius, bool sort) const override
std::tuple< Tensor, Tensor, Tensor > SearchHybrid (const Tensor &query_points, const double radius, const int max_knn) const override
Public Member Functions inherited from cloudViewer::core::nns::NNSIndex
NNSIndex ()
Default Constructor.
virtual ~NNSIndex ()
NNSIndex (const NNSIndex &)=delete
NNSIndex & operator= (const NNSIndex &)=delete
int GetDimension () const
size_t GetDatasetSize () const
Dtype GetDtype () const
Device GetDevice () const
Dtype GetIndexDtype () const
Protected Attributes
Tensor points_row_splits_
Protected Attributes inherited from cloudViewer::core::nns::NNSIndex
Tensor dataset_points_
Dtype index_dtype_
Detailed Description
Definition at line 33 of file KnnIndex.h.
Constructor & Destructor Documentation
KnnIndex() [1/4]
cloudViewer::core::nns::KnnIndex::KnnIndex ()
Definition at line 20 of file KnnIndex.cpp.
KnnIndex() [2/4]
cloudViewer::core::nns::KnnIndex::KnnIndex (const Tensor & dataset_points)
Parameterized Constructor.
Parameters
dataset_points Provides a set of data points as Tensor for KDTree construction.
Definition at line 22 of file KnnIndex.cpp.
References SetTensorData().
KnnIndex() [3/4]
cloudViewer::core::nns::KnnIndex::KnnIndex (const Tensor & dataset_points, const Dtype & index_dtype)
Definition at line 26 of file KnnIndex.cpp.
References SetTensorData().
~KnnIndex()
cloudViewer::core::nns::KnnIndex::~KnnIndex ()
Definition at line 30 of file KnnIndex.cpp.
KnnIndex() [4/4]
cloudViewer::core::nns::KnnIndex::KnnIndex (const KnnIndex &) delete
Member Function Documentation
operator=()
KnnIndex& cloudViewer::core::nns::KnnIndex::operator= (const KnnIndex &) delete
SearchHybrid()
std::tuple<Tensor, Tensor, Tensor> cloudViewer::core::nns::KnnIndex::SearchHybrid (const Tensor & query_points, const double radius, const int max_knn) const inline override virtual
Perform hybrid search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}.
radius Radius.
max_knn Maximum number of neighbor to search per query point.
Returns
Tuple of Tensors, (indices, distances, counts):
indices: Tensor of shape {n, knn}, with dtype Int32.
distances: Tensor of shape {n, knn}, with dtype Float32.
counts: Tensor of shape {n, 1}, with dtype Int32.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 79 of file KnnIndex.h.
References LogError.
SearchKnn() [1/2]
std::pair< Tensor, Tensor > cloudViewer::core::nns::KnnIndex::SearchKnn (const Tensor & query_points, const Tensor & queries_row_splits, int knn) const
Definition at line 87 of file KnnIndex.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorShape, cloudViewer::core::Tensor::Contiguous(), DISPATCH_FLOAT_INT_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::Empty(), cloudViewer::core::nns::NNSIndex::GetDevice(), cloudViewer::core::nns::NNSIndex::GetDimension(), cloudViewer::core::nns::NNSIndex::GetDtype(), cloudViewer::core::nns::NNSIndex::GetIndexDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Int64, cloudViewer::core::Device::IsCUDA(), cloudViewer::core::Tensor::Item(), KNN_PARAMETERS, LogError, cloudViewer::core::make_pair(), and cloudViewer::utility::nullopt.
SearchKnn() [2/2]
std::pair< Tensor, Tensor > cloudViewer::core::nns::KnnIndex::SearchKnn (const Tensor & query_points, int knn) const override virtual
Perform K nearest neighbor search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}, same dtype with dataset_points.
knn Number of nearest neighbor to search.
Returns
Pair of Tensors: (indices, distances):
indices: Tensor of shape {n, knn}, with dtype Int32.
distances: Tensor of shape {n, knn}, same dtype with dataset_points.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 80 of file KnnIndex.cpp.
References cloudViewer::core::Tensor::GetShape().
SearchRadius() [1/2]
std::tuple<Tensor, Tensor, Tensor> cloudViewer::core::nns::KnnIndex::SearchRadius (const Tensor & query_points, const double radius, bool sort) const inline override virtual
Perform radius search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}, same dtype with dataset_points.
radius Radius.
Returns
Tuple of Tensors, (indices, distances, num_neighbors):
indices: Tensor of shape {total_num_neighbors,}, dtype Int32.
distances: Tensor of shape {total_num_neighbors,}, same dtype with dataset_points.
num_neighbors: Tensor of shape {n}, dtype Int32.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 73 of file KnnIndex.h.
References LogError.
SearchRadius() [2/2]
std::tuple<Tensor, Tensor, Tensor> cloudViewer::core::nns::KnnIndex::SearchRadius (const Tensor & query_points, const Tensor & radii, bool sort) const inline override virtual
Perform radius search with multiple radii.
Parameters
query_points Query points. Must be 2D, with shape {n, d}, same dtype with dataset_points.
radii list of radius. Must be 1D, with shape {n, }.
Returns
Tuple of Tensors: (indices, distances, num_neighbors):
indices: Tensor of shape {total_num_neighbors,}, dtype Int32.
distances: Tensor of shape {total_num_neighbors,}, same dtype with dataset_points.
num_neighbors: Tensor of shape {n,}, dtype Int32.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 67 of file KnnIndex.h.
References LogError.
SetTensorData() [1/3]
bool cloudViewer::core::nns::KnnIndex::SetTensorData (const Tensor & dataset_points, const Dtype & index_dtype = core::Int64) override virtual
Set the data for the nearest neighbor search.
Parameters
dataset_points Dataset points for KDTree construction. Must be 2D, with shape {n, d}.
Returns
Returns true if the construction success, otherwise false.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 32 of file KnnIndex.cpp.
References cloudViewer::core::Tensor::GetShape().
Referenced by KnnIndex().
SetTensorData() [2/3]
bool cloudViewer::core::nns::KnnIndex::SetTensorData (const Tensor & dataset_points, const Tensor & points_row_splits, const Dtype & index_dtype = core::Int64)
Definition at line 39 of file KnnIndex.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::nns::NNSIndex::dataset_points_, cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetShape(), cloudViewer::core::nns::NNSIndex::index_dtype_, cloudViewer::core::Int32, cloudViewer::core::Int64, cloudViewer::core::IsDevice::IsCUDA(), cloudViewer::core::Tensor::Item(), LogError, cloudViewer::core::Tensor::NumDims(), and points_row_splits_.
SetTensorData() [3/3]
bool cloudViewer::core::nns::KnnIndex::SetTensorData (const Tensor & dataset_points, double radius, const Dtype & index_dtype = core::Int64) inline override virtual
Set the data for the nearest neighbor search.
Parameters
dataset_points Dataset points for KDTree construction. Must be 2D, with shape {n, d}.
Returns
Returns true if the construction success, otherwise false.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 53 of file KnnIndex.h.
References LogError.
Member Data Documentation
points_row_splits_
Tensor cloudViewer::core::nns::KnnIndex::points_row_splits_ protected
Definition at line 87 of file KnnIndex.h.
Referenced by SetTensorData().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/core/nns/KnnIndex.h
/root/ACloudViewer/libs/cloudViewer/core/nns/KnnIndex.cpp