ACloudViewer: CodeEditor Class Reference
CodeEditor Class Reference final
#include <CodeEditor.h>
Public Member Functions
CodeEditor (EditorSettings *settings, QWidget *parent=nullptr)
void lineNumberAreaPaintEvent (QPaintEvent *event)
bool eventFilter (QObject *target, QEvent *event) override
int lineNumberAreaWidth ()
void newFile ()
bool loadFile (const QString &fileName)
bool save ()
bool saveAs ()
bool saveFile (const QString &fileName)
QString userFriendlyCurrentFile ()
QString currentFile () const
void comment ()
void uncomment ()
void indentMore ()
void indentLess ()
Protected Member Functions
void resizeEvent (QResizeEvent *event) override
void closeEvent (QCloseEvent *event) override
void keyPressEvent (QKeyEvent *e) override
Detailed Description
Definition at line 23 of file CodeEditor.h.
Constructor & Destructor Documentation
CodeEditor()
CodeEditor::CodeEditor (EditorSettings * settings, QWidget * parent = nullptr) explicit
Definition at line 17 of file CodeEditor.cpp.
References EditorSettings::settingsChanged().
Member Function Documentation
closeEvent()
void CodeEditor::closeEvent (QCloseEvent * event) override protected
Definition at line 252 of file CodeEditor.cpp.
comment()
void CodeEditor::comment ()
Definition at line 325 of file CodeEditor.cpp.
References PYTHON_COMMENT_STR.
Referenced by PythonEditor::comment().
currentFile()
QString CodeEditor::currentFile () const inline
Definition at line 40 of file CodeEditor.h.
Referenced by PythonEditor::saveAs().
eventFilter()
bool CodeEditor::eventFilter (QObject * target, QEvent * event) override
Definition at line 33 of file CodeEditor.cpp.
References event.
indentLess()
void CodeEditor::indentLess ()
Definition at line 372 of file CodeEditor.cpp.
References INDENT_STRING.
Referenced by PythonEditor::indentLess(), and keyPressEvent().
indentMore()
void CodeEditor::indentMore ()
Definition at line 358 of file CodeEditor.cpp.
References INDENT_STRING.
Referenced by PythonEditor::indentMore(), and keyPressEvent().
keyPressEvent()
void CodeEditor::keyPressEvent (QKeyEvent * e) override protected
Definition at line 417 of file CodeEditor.cpp.
References indentLess(), and indentMore().
lineNumberAreaPaintEvent()
void CodeEditor::lineNumberAreaPaintEvent (QPaintEvent * event)
Definition at line 145 of file CodeEditor.cpp.
References ecvColor::black(), event, and height.
Referenced by LineNumberArea::paintEvent().
lineNumberAreaWidth()
int CodeEditor::lineNumberAreaWidth ()
Definition at line 83 of file CodeEditor.cpp.
References max(), and e57::space().
Referenced by resizeEvent(), and LineNumberArea::sizeHint().
loadFile()
bool CodeEditor::loadFile (const QString & fileName)
Definition at line 183 of file CodeEditor.cpp.
newFile()
void CodeEditor::newFile ()
Definition at line 172 of file CodeEditor.cpp.
Referenced by PythonEditor::newFile().
resizeEvent()
void CodeEditor::resizeEvent (QResizeEvent * event) override protected
Definition at line 114 of file CodeEditor.cpp.
References lineNumberAreaWidth().
save()
bool CodeEditor::save ()
Definition at line 205 of file CodeEditor.cpp.
References saveAs(), and saveFile().
saveAs()
bool CodeEditor::saveAs ()
Definition at line 217 of file CodeEditor.cpp.
References saveFile().
Referenced by save(), and PythonEditor::saveAs().
saveFile()
bool CodeEditor::saveFile (const QString & fileName)
Definition at line 226 of file CodeEditor.cpp.
Referenced by save(), and saveAs().
uncomment()
void CodeEditor::uncomment ()
Definition at line 339 of file CodeEditor.cpp.
References PYTHON_COMMENT_STR.
Referenced by PythonEditor::uncomment().
userFriendlyCurrentFile()
QString CodeEditor::userFriendlyCurrentFile ()
Definition at line 247 of file CodeEditor.cpp.
Referenced by PythonEditor::updateWindowMenu().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/CodeEditor/CodeEditor.h
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/CodeEditor/CodeEditor.cpp