ACloudViewer: ViewInterpolate Class Reference
ViewInterpolate Class Reference
The ViewInterpolate class.
#include <ViewInterpolate.h>
Public Member Functions
ViewInterpolate (const ecvViewportParameters &view1, const ecvViewportParameters &view2, unsigned int stepCount=0)
Constructor from two viewports and a number of steps.
void setSmoothTrajectory (ccPolyline *smoothTrajectory, ccPolyline *smoothTrajectoryReversed, unsigned i1, unsigned i2, PointCoordinateType length)
Sets the smooth trajectory (optional)
const ecvViewportParameters & view1 () const
Returns the first viewport object.
const ecvViewportParameters & view2 () const
bool interpolate (ecvViewportParameters &a_returned_viewport, double ratio) const
Interpolates the 2 viewports at a given (relative) position.
bool nextView (ecvViewportParameters &a_returned_viewport)
Returns the next viewport.
unsigned int currentStep ()
Returns the current step.
void setCurrentStep (unsigned int step)
Sets the current step.
unsigned int maxStep ()
Returns the max number of steps.
void setMaxStep (unsigned int stepCount)
Sets the max number of steps.
void reset ()
Resets the interpolator.
Detailed Description
The ViewInterpolate class.
This class takes pointers to two viewport objects, and returns intermediate viewports between over a set number of steps.
Definition at line 20 of file ViewInterpolate.h.
Constructor & Destructor Documentation
ViewInterpolate()
ViewInterpolate::ViewInterpolate (const ecvViewportParameters & view1, const ecvViewportParameters & view2, unsigned int stepCount = 0)
Constructor from two viewports and a number of steps.
Definition at line 13 of file ViewInterpolate.cpp.
Member Function Documentation
currentStep()
unsigned int ViewInterpolate::currentStep () inline
Returns the current step.
Definition at line 47 of file ViewInterpolate.h.
interpolate()
bool ViewInterpolate::interpolate (ecvViewportParameters & a_returned_viewport, double ratio) const
Interpolates the 2 viewports at a given (relative) position.
Definition at line 50 of file ViewInterpolate.cpp.
References ecvViewportParameters::cameraAspectRatio, ecvViewportParameters::defaultLineWidth, ecvViewportParameters::defaultPointSize, ecvViewportParameters::fov_deg, ecvViewportParameters::getCameraCenter(), ecvViewportParameters::getFocalDistance(), ecvViewportParameters::getPivotPoint(), ccGLMatrixTpl< double >::Interpolate(), InterpolateNumber(), ecvViewportParameters::setCameraCenter(), ecvViewportParameters::setFocalDistance(), ecvViewportParameters::setPivotPoint(), ecvViewportParameters::viewMat, ecvViewportParameters::zFar, ecvViewportParameters::zNear, and ecvViewportParameters::zNearCoef.
Referenced by nextView(), qAnimationDlg::preview(), qAnimationDlg::render(), and qAnimationDlg::smoothTrajectory().
maxStep()
unsigned int ViewInterpolate::maxStep () inline
Returns the max number of steps.
Definition at line 52 of file ViewInterpolate.h.
nextView()
bool ViewInterpolate::nextView (ecvViewportParameters & a_returned_viewport)
Returns the next viewport.
Definition at line 95 of file ViewInterpolate.cpp.
References interpolate().
reset()
void ViewInterpolate::reset (void) inline
Resets the interpolator.
Definition at line 57 of file ViewInterpolate.h.
setCurrentStep()
void ViewInterpolate::setCurrentStep (unsigned int step) inline
Sets the current step.
Definition at line 49 of file ViewInterpolate.h.
setMaxStep()
void ViewInterpolate::setMaxStep (unsigned int stepCount) inline
Sets the max number of steps.
Definition at line 54 of file ViewInterpolate.h.
setSmoothTrajectory()
void ViewInterpolate::setSmoothTrajectory (ccPolyline * smoothTrajectory, ccPolyline * smoothTrajectoryReversed, unsigned i1, unsigned i2, PointCoordinateType length)
Sets the smooth trajectory (optional)
Definition at line 28 of file ViewInterpolate.cpp.
References length().
view1()
const ecvViewportParameters& ViewInterpolate::view1 () const inline
Returns the first viewport object.
Definition at line 35 of file ViewInterpolate.h.
view2()
const ecvViewportParameters& ViewInterpolate::view2 () const inline
Definition at line 37 of file ViewInterpolate.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qAnimation/include/ViewInterpolate.h
/root/ACloudViewer/plugins/core/Standard/qAnimation/src/ViewInterpolate.cpp