ACloudViewer: colmap::PointViewerWidget Class Reference
colmap::PointViewerWidget Class Reference
#include <point_viewer_widget.h>
Public Member Functions
PointViewerWidget (QWidget *parent, ModelViewerWidget *model_viewer_widget, OptionManager *option)
void Show (const point3D_t point3D_id)
Detailed Description
Definition at line 20 of file point_viewer_widget.h.
Constructor & Destructor Documentation
PointViewerWidget()
colmap::PointViewerWidget::PointViewerWidget (QWidget * parent, ModelViewerWidget * model_viewer_widget, OptionManager * option)
Definition at line 39 of file point_viewer_widget.cc.
Member Function Documentation
Show()
void colmap::PointViewerWidget::Show (const point3D_t point3D_id)
Definition at line 127 of file point_viewer_widget.cc.
References colmap::BitmapToQImageRGB(), colmap::ModelViewerWidget::cameras, QtCompat::endl(), ecvColor::green(), image, colmap::OptionManager::image_path, colmap::ModelViewerWidget::images, colmap::JoinPaths(), colmap::kInvalidPoint3DId, cloudViewer::t::geometry::path, colmap::ModelViewerWidget::points3D, colmap::ProjectPointToImage(), colmap::Bitmap::Read(), ecvColor::red(), patch::to_string(), x, colmap::Point2D::X(), colmap::Point2D::XY(), y, and colmap::Point2D::Y().
Referenced by colmap::ModelViewerWidget::ShowPointInfo().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/point_viewer_widget.h
/root/ACloudViewer/libs/Reconstruction/src/ui/point_viewer_widget.cc