ACloudViewer: Train3DMASCDialog Class Reference
Train3DMASCDialog Class Reference
3DMASC plugin 'train' dialog
#include <qTrain3DMASCDialog.h>
Public Member Functions
Train3DMASCDialog (QWidget *parent=nullptr)
Default constructor.
~Train3DMASCDialog ()
void readSettings ()
void writeSettings ()
void clearResults ()
int addFeature (QString name, float importance, bool isChecked=true)
Adds a feature (entry) to the results table.
int addScale (double scale, bool isChecked=true)
void scaleStateChanged (QTableWidgetItem *item)
void connectScaleSelectionToFeatureSelection ()
void setResultText (QString text)
void setFirstRunDone ()
void setClassifierSaved ()
bool isFeatureSelected (QString featureName) const
void setFeatureImportance (QString featureName, float importance)
void sortByFeatureImportance ()
bool shouldSaveClassifier () const
void addConfusionMatrixAndSaveTraces (ConfusionMatrix *ptr)
void setInputFilePath (QString filename)
void setCheckBoxSaveTrace (bool state)
bool openTraceFile ()
bool closeTraceFile ()
void saveTraces (ConfusionMatrix *confusionMatrix)
bool getSaveTrace ()
QString getTracePath ()
int getRun ()
Protected Slots
void onClose ()
void onSave ()
void onExportResults (QString filePath="")
Protected Attributes
bool classifierSaved
bool saveRequested
std::vector< ConfusionMatrix * > toDeleteLater
bool traceFileConfigured
QFile * m_traceFile
QString m_tracePath
QTextStream m_traceStream
QString m_parameterFilePath
QString m_baseName
uint run
Detailed Description
3DMASC plugin 'train' dialog
Definition at line 39 of file qTrain3DMASCDialog.h.
Constructor & Destructor Documentation
Train3DMASCDialog()
Train3DMASCDialog::Train3DMASCDialog (QWidget * parent = nullptr)
Default constructor.
Definition at line 28 of file qTrain3DMASCDialog.cpp.
References m_baseName, onClose(), onExportResults(), onSave(), and readSettings().
~Train3DMASCDialog()
Train3DMASCDialog::~Train3DMASCDialog ()
Definition at line 49 of file qTrain3DMASCDialog.cpp.
References closeTraceFile(), toDeleteLater, and writeSettings().
Member Function Documentation
addConfusionMatrixAndSaveTraces()
void Train3DMASCDialog::addConfusionMatrixAndSaveTraces (ConfusionMatrix * ptr)
Definition at line 214 of file qTrain3DMASCDialog.cpp.
References saveTraces(), and toDeleteLater.
Referenced by masc::Classifier::evaluate().
addFeature()
int Train3DMASCDialog::addFeature (QString name, float importance, bool isChecked = true)
Adds a feature (entry) to the results table.
Returns
the row index
Definition at line 78 of file qTrain3DMASCDialog.cpp.
References name.
Referenced by q3DMASCPlugin::doTrainAction().
addScale()
int Train3DMASCDialog::addScale (double scale, bool isChecked = true)
Definition at line 95 of file qTrain3DMASCDialog.cpp.
Referenced by q3DMASCPlugin::doTrainAction().
clearResults()
void Train3DMASCDialog::clearResults ()
Definition at line 73 of file qTrain3DMASCDialog.cpp.
closeTraceFile()
bool Train3DMASCDialog::closeTraceFile ()
Definition at line 295 of file qTrain3DMASCDialog.cpp.
References m_traceFile, and CVLog::Print().
Referenced by ~Train3DMASCDialog().
connectScaleSelectionToFeatureSelection()
void Train3DMASCDialog::connectScaleSelectionToFeatureSelection ()
Definition at line 117 of file qTrain3DMASCDialog.cpp.
References scaleStateChanged().
Referenced by q3DMASCPlugin::doTrainAction().
getRun()
int Train3DMASCDialog::getRun ()
Definition at line 341 of file qTrain3DMASCDialog.cpp.
References run.
Referenced by q3DMASCPlugin::doTrainAction().
getSaveTrace()
bool Train3DMASCDialog::getSaveTrace ()
Definition at line 326 of file qTrain3DMASCDialog.cpp.
Referenced by q3DMASCPlugin::doTrainAction().
getTracePath()
QString Train3DMASCDialog::getTracePath ()
Definition at line 330 of file qTrain3DMASCDialog.cpp.
References m_traceFile, openTraceFile(), and traceFileConfigured.
Referenced by q3DMASCPlugin::doTrainAction().
isFeatureSelected()
bool Train3DMASCDialog::isFeatureSelected (QString featureName) const
Definition at line 131 of file qTrain3DMASCDialog.cpp.
Referenced by q3DMASCPlugin::doTrainAction().
onClose
void Train3DMASCDialog::onClose () protected slot
Definition at line 163 of file qTrain3DMASCDialog.cpp.
References classifierSaved.
Referenced by Train3DMASCDialog().
onExportResults
void Train3DMASCDialog::onExportResults (QString filePath = "") protected slot
Definition at line 180 of file qTrain3DMASCDialog.cpp.
References QtCompat::endl(), and FeatureImportanceColumn.
Referenced by Train3DMASCDialog().
onSave
void Train3DMASCDialog::onSave () protected slot
Definition at line 175 of file qTrain3DMASCDialog.cpp.
References saveRequested.
Referenced by Train3DMASCDialog().
openTraceFile()
bool Train3DMASCDialog::openTraceFile ()
Definition at line 228 of file qTrain3DMASCDialog.cpp.
References ecvColor::LookUpTable::at(), CVLog::Error(), m_baseName, m_parameterFilePath, m_traceFile, m_tracePath, m_traceStream, CVLog::Print(), and traceFileConfigured.
Referenced by getTracePath(), and saveTraces().
readSettings()
void Train3DMASCDialog::readSettings ()
Definition at line 57 of file qTrain3DMASCDialog.cpp.
References setCheckBoxSaveTrace().
Referenced by Train3DMASCDialog().
saveTraces()
void Train3DMASCDialog::saveTraces (ConfusionMatrix * confusionMatrix)
Definition at line 306 of file qTrain3DMASCDialog.cpp.
References QtCompat::endl(), ConfusionMatrix::getOverallAccuracy(), m_baseName, m_tracePath, m_traceStream, openTraceFile(), run, ConfusionMatrix::save(), ConfusionMatrix::setSessionRun(), and traceFileConfigured.
Referenced by addConfusionMatrixAndSaveTraces().
scaleStateChanged()
void Train3DMASCDialog::scaleStateChanged (QTableWidgetItem * item)
Definition at line 106 of file qTrain3DMASCDialog.cpp.
References name.
Referenced by connectScaleSelectionToFeatureSelection().
setCheckBoxSaveTrace()
void Train3DMASCDialog::setCheckBoxSaveTrace (bool state)
Definition at line 224 of file qTrain3DMASCDialog.cpp.
Referenced by readSettings().
setClassifierSaved()
void Train3DMASCDialog::setClassifierSaved () inline
Definition at line 61 of file qTrain3DMASCDialog.h.
References classifierSaved, and saveRequested.
Referenced by q3DMASCPlugin::doTrainAction().
setFeatureImportance()
void Train3DMASCDialog::setFeatureImportance (QString featureName, float importance)
Definition at line 147 of file qTrain3DMASCDialog.cpp.
References FeatureImportanceColumn.
Referenced by q3DMASCPlugin::doTrainAction().
setFirstRunDone()
void Train3DMASCDialog::setFirstRunDone ()
Definition at line 126 of file qTrain3DMASCDialog.cpp.
Referenced by q3DMASCPlugin::doTrainAction().
setInputFilePath()
void Train3DMASCDialog::setInputFilePath (QString filename)
Definition at line 220 of file qTrain3DMASCDialog.cpp.
References m_parameterFilePath.
Referenced by q3DMASCPlugin::doTrainAction().
setResultText()
void Train3DMASCDialog::setResultText (QString text)
Definition at line 122 of file qTrain3DMASCDialog.cpp.
Referenced by q3DMASCPlugin::doTrainAction().
shouldSaveClassifier()
bool Train3DMASCDialog::shouldSaveClassifier () const inline
Definition at line 70 of file qTrain3DMASCDialog.h.
References saveRequested.
Referenced by q3DMASCPlugin::doTrainAction().
sortByFeatureImportance()
void Train3DMASCDialog::sortByFeatureImportance ()
Definition at line 143 of file qTrain3DMASCDialog.cpp.
References FeatureImportanceColumn.
Referenced by q3DMASCPlugin::doTrainAction().
writeSettings()
void Train3DMASCDialog::writeSettings ()
Definition at line 66 of file qTrain3DMASCDialog.cpp.
Referenced by ~Train3DMASCDialog().
Member Data Documentation
classifierSaved
bool Train3DMASCDialog::classifierSaved protected
Definition at line 89 of file qTrain3DMASCDialog.h.
Referenced by onClose(), and setClassifierSaved().
m_baseName
QString Train3DMASCDialog::m_baseName protected
Definition at line 97 of file qTrain3DMASCDialog.h.
Referenced by openTraceFile(), saveTraces(), and Train3DMASCDialog().
m_parameterFilePath
QString Train3DMASCDialog::m_parameterFilePath protected
Definition at line 96 of file qTrain3DMASCDialog.h.
Referenced by openTraceFile(), and setInputFilePath().
m_traceFile
QFile* Train3DMASCDialog::m_traceFile protected
Definition at line 93 of file qTrain3DMASCDialog.h.
Referenced by closeTraceFile(), getTracePath(), and openTraceFile().
m_tracePath
QString Train3DMASCDialog::m_tracePath protected
Definition at line 94 of file qTrain3DMASCDialog.h.
Referenced by openTraceFile(), and saveTraces().
m_traceStream
QTextStream Train3DMASCDialog::m_traceStream protected
Definition at line 95 of file qTrain3DMASCDialog.h.
Referenced by openTraceFile(), and saveTraces().
run
uint Train3DMASCDialog::run protected
Definition at line 98 of file qTrain3DMASCDialog.h.
Referenced by getRun(), and saveTraces().
saveRequested
bool Train3DMASCDialog::saveRequested protected
Definition at line 90 of file qTrain3DMASCDialog.h.
Referenced by onSave(), setClassifierSaved(), and shouldSaveClassifier().
toDeleteLater
std::vector<ConfusionMatrix*> Train3DMASCDialog::toDeleteLater protected
Definition at line 91 of file qTrain3DMASCDialog.h.
Referenced by addConfusionMatrixAndSaveTraces(), and ~Train3DMASCDialog().
traceFileConfigured
bool Train3DMASCDialog::traceFileConfigured protected
Definition at line 92 of file qTrain3DMASCDialog.h.
Referenced by getTracePath(), openTraceFile(), and saveTraces().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/q3DMASC/qTrain3DMASCDialog.h
/root/ACloudViewer/plugins/core/Standard/q3DMASC/qTrain3DMASCDialog.cpp