ACloudViewer: cloudViewer::core::nns::NanoFlannIndex Class Reference
cloudViewer::core::nns::NanoFlannIndex Class Reference
#include <NanoFlannIndex.h>
Public Member Functions
NanoFlannIndex ()
Default Constructor.
NanoFlannIndex (const Tensor &dataset_points)
Parameterized Constructor.
NanoFlannIndex (const Tensor &dataset_points, const Dtype &index_dtype)
~NanoFlannIndex ()
NanoFlannIndex (const NanoFlannIndex &)=delete
NanoFlannIndex & operator= (const NanoFlannIndex &)=delete
bool SetTensorData (const Tensor &dataset_points, const Dtype &index_dtype=core::Int64) override
bool SetTensorData (const Tensor &dataset_points, double radius, const Dtype &index_dtype=core::Int64) override
std::pair< Tensor, Tensor > SearchKnn (const Tensor &query_points, int knn) const override
std::tuple< Tensor, Tensor, Tensor > SearchRadius (const Tensor &query_points, const Tensor &radii, bool sort=true) const override
std::tuple< Tensor, Tensor, Tensor > SearchRadius (const Tensor &query_points, double radius, bool sort=true) const override
std::tuple< Tensor, Tensor, Tensor > SearchHybrid (const Tensor &query_points, double radius, int max_knn) const override
Public Member Functions inherited from cloudViewer::core::nns::NNSIndex
NNSIndex ()
Default Constructor.
virtual ~NNSIndex ()
NNSIndex (const NNSIndex &)=delete
NNSIndex & operator= (const NNSIndex &)=delete
int GetDimension () const
size_t GetDatasetSize () const
Dtype GetDtype () const
Device GetDevice () const
Dtype GetIndexDtype () const
Protected Attributes
std::unique_ptr< NanoFlannIndexHolderBase > holder_
Protected Attributes inherited from cloudViewer::core::nns::NNSIndex
Tensor dataset_points_
Dtype index_dtype_
Detailed Description
Definition at line 25 of file NanoFlannIndex.h.
Constructor & Destructor Documentation
NanoFlannIndex() [1/4]
cloudViewer::core::nns::NanoFlannIndex::NanoFlannIndex ()
Default Constructor.
Definition at line 23 of file NanoFlannIndex.cpp.
NanoFlannIndex() [2/4]
cloudViewer::core::nns::NanoFlannIndex::NanoFlannIndex (const Tensor & dataset_points)
Parameterized Constructor.
Parameters
dataset_points Provides a set of data points as Tensor for KDTree construction.
Definition at line 25 of file NanoFlannIndex.cpp.
References SetTensorData().
NanoFlannIndex() [3/4]
cloudViewer::core::nns::NanoFlannIndex::NanoFlannIndex (const Tensor & dataset_points, const Dtype & index_dtype)
Definition at line 29 of file NanoFlannIndex.cpp.
References SetTensorData().
~NanoFlannIndex()
cloudViewer::core::nns::NanoFlannIndex::~NanoFlannIndex ()
Definition at line 34 of file NanoFlannIndex.cpp.
NanoFlannIndex() [4/4]
cloudViewer::core::nns::NanoFlannIndex::NanoFlannIndex (const NanoFlannIndex &) delete
Member Function Documentation
operator=()
NanoFlannIndex& cloudViewer::core::nns::NanoFlannIndex::operator= (const NanoFlannIndex &) delete
SearchHybrid()
std::tuple< Tensor, Tensor, Tensor > cloudViewer::core::nns::NanoFlannIndex::SearchHybrid (const Tensor & query_points, double radius, int max_knn) const override virtual
Perform hybrid search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}.
radius Radius.
max_knn Maximum number of neighbor to search per query point.
Returns
Tuple of Tensors, (indices, distances, counts):
indices: Tensor of shape {n, knn}, with dtype Int32.
distances: Tensor of shape {n, knn}, with dtype Float32.
counts: Counts of neighbour for each query points. [Tensor of shape {n}, with dtype Int32].
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 158 of file NanoFlannIndex.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorShape, cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::nns::NNSIndex::dataset_points_, DISPATCH_FLOAT_INT_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::nns::NNSIndex::GetDevice(), cloudViewer::core::nns::NNSIndex::GetDimension(), cloudViewer::core::nns::NNSIndex::GetDtype(), cloudViewer::core::nns::NNSIndex::GetIndexDtype(), cloudViewer::core::Tensor::GetShape(), holder_, cloudViewer::core::nns::L2, LogError, cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborsCount(), cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborsDistance(), cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborsIndex(), cloudViewer::utility::nullopt, and cloudViewer::core::Tensor::View().
SearchKnn()
std::pair< Tensor, Tensor > cloudViewer::core::nns::NanoFlannIndex::SearchKnn (const Tensor & query_points, int knn) const override virtual
Perform K nearest neighbor search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}, same dtype with dataset_points.
knn Number of nearest neighbor to search.
Returns
Pair of Tensors: (indices, distances):
indices: Tensor of shape {n, knn}, with dtype Int32.
distances: Tensor of shape {n, knn}, same dtype with dataset_points.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 58 of file NanoFlannIndex.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorShape, cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::nns::NNSIndex::dataset_points_, DISPATCH_FLOAT_INT_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::nns::NNSIndex::GetDatasetSize(), cloudViewer::core::nns::NNSIndex::GetDevice(), cloudViewer::core::nns::NNSIndex::GetDimension(), cloudViewer::core::nns::NNSIndex::GetDtype(), cloudViewer::core::nns::NNSIndex::GetIndexDtype(), cloudViewer::core::Tensor::GetShape(), holder_, cloudViewer::core::Int64, cloudViewer::core::nns::L2, LogError, cloudViewer::core::make_pair(), min(), cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborsDistance(), cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborsIndex(), cloudViewer::utility::nullopt, and cloudViewer::core::Tensor::View().
SearchRadius() [1/2]
std::tuple< Tensor, Tensor, Tensor > cloudViewer::core::nns::NanoFlannIndex::SearchRadius (const Tensor & query_points, const Tensor & radii, bool sort = true) const override virtual
Perform radius search with multiple radii.
Parameters
query_points Query points. Must be 2D, with shape {n, d}, same dtype with dataset_points.
radii list of radius. Must be 1D, with shape {n, }.
Returns
Tuple of Tensors: (indices, distances, counts):
indices: Tensor of shape {total_num_neighbors,}, dtype Int32.
distances: Tensor of shape {total_num_neighbors,}, same dtype with dataset_points.
counts: Tensor of shape {n,}, dtype Int64.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 99 of file NanoFlannIndex.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorShape, cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::nns::NNSIndex::dataset_points_, DISPATCH_FLOAT_INT_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::nns::NNSIndex::GetDevice(), cloudViewer::core::nns::NNSIndex::GetDimension(), cloudViewer::core::nns::NNSIndex::GetDtype(), cloudViewer::core::nns::NNSIndex::GetIndexDtype(), cloudViewer::core::Tensor::GetShape(), holder_, cloudViewer::core::nns::NNSIndex::index_dtype_, cloudViewer::core::Int64, cloudViewer::core::nns::L2, LogError, cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborsDistance(), cloudViewer::core::nns::NeighborSearchAllocator< T, TIndex >::NeighborsIndex(), cloudViewer::utility::nullopt, radii, and cloudViewer::core::Tensor::To().
Referenced by SearchRadius().
SearchRadius() [2/2]
std::tuple< Tensor, Tensor, Tensor > cloudViewer::core::nns::NanoFlannIndex::SearchRadius (const Tensor & query_points, double radius, bool sort = true) const override virtual
Perform radius search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}, same dtype with dataset_points.
radius Radius.
Returns
Tuple of Tensors, (indices, distances, counts):
indices: Tensor of shape {total_num_neighbors,}, dtype Int32.
distances: Tensor of shape {total_num_neighbors,}, same dtype with dataset_points.
counts: Tensor of shape {n}, dtype Int64.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 145 of file NanoFlannIndex.cpp.
References DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, cloudViewer::core::nns::NNSIndex::GetDtype(), cloudViewer::core::Tensor::GetShape(), radii, result, and SearchRadius().
SetTensorData() [1/2]
bool cloudViewer::core::nns::NanoFlannIndex::SetTensorData (const Tensor & dataset_points, const Dtype & index_dtype = core::Int64) override virtual
Set the data for the nearest neighbor search.
Parameters
dataset_points Dataset points for KDTree construction. Must be 2D, with shape {n, d}.
Returns
Returns true if the construction success, otherwise false.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 36 of file NanoFlannIndex.cpp.
References AssertTensorDtypes, cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::nns::NNSIndex::dataset_points_, DISPATCH_FLOAT_INT_DTYPE_TO_TEMPLATE, cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::nns::NNSIndex::GetDtype(), cloudViewer::core::nns::NNSIndex::GetIndexDtype(), cloudViewer::core::Tensor::GetShape(), holder_, cloudViewer::core::nns::NNSIndex::index_dtype_, cloudViewer::core::Int32, cloudViewer::core::Int64, cloudViewer::core::nns::L2, LogError, and cloudViewer::core::Tensor::NumDims().
Referenced by NanoFlannIndex().
SetTensorData() [2/2]
bool cloudViewer::core::nns::NanoFlannIndex::SetTensorData (const Tensor & dataset_points, double radius, const Dtype & index_dtype = core::Int64) inline override virtual
Set the data for the nearest neighbor search.
Parameters
dataset_points Dataset points for KDTree construction. Must be 2D, with shape {n, d}.
Returns
Returns true if the construction success, otherwise false.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 44 of file NanoFlannIndex.h.
References LogError.
Member Data Documentation
holder_
std::unique_ptr<NanoFlannIndexHolderBase> cloudViewer::core::nns::NanoFlannIndex::holder_ protected
Definition at line 109 of file NanoFlannIndex.h.
Referenced by SearchHybrid(), SearchKnn(), SearchRadius(), and SetTensorData().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/core/nns/NanoFlannIndex.h
/root/ACloudViewer/libs/cloudViewer/core/nns/NanoFlannIndex.cpp