ACloudViewer: QVTKWidgetCustom Class Reference
QVTKWidgetCustom Class Reference
Container widget for vtk.
#include <QVTKWidgetCustom.h>
Public Member Functions
QVTKWidgetCustom (QMainWindow *parentWindow, ecvDisplayTools *tools, bool stereoMode=false)
virtual ~QVTKWidgetCustom ()
vtkRenderer * getVtkRender ()
vtkRenderWindowInteractor * getVtkInteractor ()
void initVtk (vtkSmartPointer< vtkRenderWindowInteractor > interactor, bool useVBO=false)
void setMultiViewports (bool multi=true)
bool multiViewports () const
void addActor (vtkProp *actor, const QColor &clr=Qt::black)
void addViewProp (vtkProp *prop)
QList< vtkProp * > actors () const
void setActorsVisible (bool visible)
void setActorVisible (vtkProp *actor, bool visible)
bool actorVisible (vtkProp *actor)
void setBackgroundColor (const QColor &clr)
QColor backgroundColor () const
vtkRenderer * defaultRenderer ()
bool defaultRendererTaken () const
void transformCameraView (const double *viewMat)
void transformCameraProjection (const double *projMat)
void updateScene ()
vtkRenderWindow * GetRenderWindow ()
void SetRenderWindow (vtkRenderWindow *win)
QVTKInteractor * GetInteractor ()
void toWorldPoint (const CCVector3d &input2D, CCVector3d &output3D)
void toWorldPoint (const CCVector3 &input2D, CCVector3d &output3D)
void toDisplayPoint (const CCVector3d &worldPos, CCVector3d &displayPos)
void toDisplayPoint (const CCVector3 &worldPos, CCVector3d &displayPos)
void setCameraPosition (const CCVector3d &pos)
void setCameraFocalPoint (const CCVector3d &pos)
void setCameraViewUp (const CCVector3d &pos)
void setBackgroundColor (const ecvColor::Rgbf &bkg1, const ecvColor::Rgbf &bkg2, bool gradient)
vtkSmartPointer< vtkLookupTable > createLookupTable (double min, double max)
QMainWindow * getWin ()
void setScaleBarVisible (bool visible)
Protected Member Functions
void setBounds (double *bounds)
double xMin () const
double xMax () const
double yMin () const
double yMax () const
double zMin () const
double zMax () const
virtual bool event (QEvent *evt) override
virtual void wheelEvent (QWheelEvent *event) override
virtual void keyPressEvent (QKeyEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseDoubleClickEvent (QMouseEvent *event) override
virtual void dragEnterEvent (QDragEnterEvent *event) override
virtual void dropEvent (QDropEvent *event) override
virtual void updateActivateditems (int x, int y, int dx, int dy, bool updatePosition=false)
Protected Attributes
bool m_unclosable = true
bool m_useVBO = false
vtkRenderer * m_render
QMainWindow * m_win
ecvDisplayTools * m_tools
vtkDataObject * m_dataObject
vtkActor * m_modelActor = nullptr
vtkLODActor * m_filterActor = nullptr
QColor m_color1 = Qt::blue
QColor m_color2 = Qt::red
vtkSmartPointer< vtkPlanes > m_planes
vtkSmartPointer< vtkCamera > m_camera
vtkSmartPointer< vtkRendererCollection > m_renders
vtkSmartPointer< vtkRenderWindowInteractor > m_interactor
vtkSmartPointer< vtkLogoWidget > m_logoWidget
Internal pointer to widget which contains a logo_Widget_.
vtkSmartPointer< vtkScalarBarWidget > m_scalarbarWidget
Internal pointer to widget which contains a scalarbar_Widget_.
vtkSmartPointer< vtkOrientationMarkerWidget > m_axesWidget
Internal pointer to widget which contains a set of axes.
ScaleBarWidget * m_scaleBar = nullptr
VtkWidgetPrivate * d_ptr
QTimer * m_wheelZoomUpdateTimer = nullptr
Detailed Description
Container widget for vtk.
Definition at line 62 of file QVTKWidgetCustom.h.
Constructor & Destructor Documentation
QVTKWidgetCustom()
QVTKWidgetCustom::QVTKWidgetCustom (QMainWindow * parentWindow, ecvDisplayTools * tools, bool stereoMode = false) explicit
Definition at line 177 of file QVTKWidgetCustom.cpp.
References d_ptr, m_tools, m_wheelZoomUpdateTimer, and ecvDisplayTools::Update2DLabel().
~QVTKWidgetCustom()
QVTKWidgetCustom::~QVTKWidgetCustom () virtual
Definition at line 220 of file QVTKWidgetCustom.cpp.
References d_ptr, m_scaleBar, and m_wheelZoomUpdateTimer.
Member Function Documentation
actors()
QList< vtkProp * > QVTKWidgetCustom::actors () const
Definition at line 435 of file QVTKWidgetCustom.cpp.
References d_ptr.
actorVisible()
bool QVTKWidgetCustom::actorVisible (vtkProp * actor)
Definition at line 445 of file QVTKWidgetCustom.cpp.
addActor()
void QVTKWidgetCustom::addActor (vtkProp * actor, const QColor & clr = Qt::black)
Definition at line 366 of file QVTKWidgetCustom.cpp.
References d_ptr, defaultRenderer(), defaultRendererTaken(), GetRenderWindow(), and Utils::vtkColor().
addViewProp()
void QVTKWidgetCustom::addViewProp (vtkProp * prop)
Definition at line 404 of file QVTKWidgetCustom.cpp.
References d_ptr, defaultRenderer(), defaultRendererTaken(), and GetRenderWindow().
backgroundColor()
QColor QVTKWidgetCustom::backgroundColor () const
Definition at line 467 of file QVTKWidgetCustom.cpp.
References d_ptr.
createLookupTable()
vtkSmartPointer< vtkLookupTable > QVTKWidgetCustom::createLookupTable (double min, double max)
Definition at line 233 of file QVTKWidgetCustom.cpp.
References m_color1, m_color2, Utils::qColor2HSV(), and VTK_CREATE.
defaultRenderer()
vtkRenderer * QVTKWidgetCustom::defaultRenderer ()
Definition at line 471 of file QVTKWidgetCustom.cpp.
References d_ptr, GetRenderWindow(), and VtkUtils::vtkInitOnce().
Referenced by addActor(), and addViewProp().
defaultRendererTaken()
bool QVTKWidgetCustom::defaultRendererTaken () const
Definition at line 479 of file QVTKWidgetCustom.cpp.
References d_ptr.
Referenced by addActor(), and addViewProp().
dragEnterEvent()
void QVTKWidgetCustom::dragEnterEvent (QDragEnterEvent * event) override protected virtual
Definition at line 1323 of file QVTKWidgetCustom.cpp.
References event().
Referenced by event().
dropEvent()
void QVTKWidgetCustom::dropEvent (QDropEvent * event) override protected virtual
Definition at line 1330 of file QVTKWidgetCustom.cpp.
References event(), ecvDisplayTools::filesDropped(), m_tools, and CVLog::Print().
Referenced by event().
event()
bool QVTKWidgetCustom::event (QEvent * evt) override protected virtual
Definition at line 1354 of file QVTKWidgetCustom.cpp.
References dragEnterEvent(), dropEvent(), event, ecvDisplayTools::exclusiveFullScreenToggled(), m_interactor, m_render, m_scaleBar, m_tools, ecvDisplayTools::m_touchBaseDist, ecvDisplayTools::m_touchInProgress, m_unclosable, ecvDisplayTools::m_viewportParams, m_win, ecvViewportParameters::perspectiveView, CVLog::Print(), CVLog::PrintDebug(), cloudViewer::t::geometry::ipp::Resize(), ecvDisplayTools::ResizeGL(), size, ScaleBarWidget::update(), and ecvDisplayTools::UpdateZoom().
Referenced by dragEnterEvent(), dropEvent(), keyPressEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and wheelEvent().
GetInteractor()
QVTKInteractor* QVTKWidgetCustom::GetInteractor () inline
Definition at line 103 of file QVTKWidgetCustom.h.
GetRenderWindow()
vtkRenderWindow* QVTKWidgetCustom::GetRenderWindow () inline
Definition at line 99 of file QVTKWidgetCustom.h.
Referenced by addActor(), addViewProp(), defaultRenderer(), initVtk(), setBackgroundColor(), and updateScene().
getVtkInteractor()
vtkRenderWindowInteractor* QVTKWidgetCustom::getVtkInteractor () inline
Definition at line 72 of file QVTKWidgetCustom.h.
getVtkRender()
vtkRenderer* QVTKWidgetCustom::getVtkRender () inline
Definition at line 71 of file QVTKWidgetCustom.h.
getWin()
QMainWindow* QVTKWidgetCustom::getWin () inline
Definition at line 130 of file QVTKWidgetCustom.h.
initVtk()
void QVTKWidgetCustom::initVtk (vtkSmartPointer< vtkRenderWindowInteractor > interactor, bool useVBO = false)
Definition at line 250 of file QVTKWidgetCustom.cpp.
References GetRenderWindow(), m_camera, m_interactor, m_render, m_renders, m_scaleBar, and m_useVBO.
Referenced by PCLDisplayTools::registerVisualizer().
keyPressEvent()
void QVTKWidgetCustom::keyPressEvent (QKeyEvent * event) override protected virtual
Definition at line 1450 of file QVTKWidgetCustom.cpp.
References event().
mouseDoubleClickEvent()
void QVTKWidgetCustom::mouseDoubleClickEvent (QMouseEvent * event) override protected virtual
Definition at line 554 of file QVTKWidgetCustom.cpp.
References ecvDisplayTools::doubleButtonClicked(), event(), ecvDisplayTools::GetClick3DPos(), ecvDisplayTools::m_deferredPickingTimer, ecvDisplayTools::m_ignoreMouseReleaseEvent, m_tools, ecvDisplayTools::SetPivotPoint(), x, and y.
mouseMoveEvent()
void QVTKWidgetCustom::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 657 of file QVTKWidgetCustom.cpp.
References a, ccHObject::addChild(), cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::ReferenceCloud::addPointIndex(), ecvDisplayTools::AddToOwnDB(), ccGLMatrixTpl< T >::applyRotation(), ecvViewportParameters::cameraAspectRatio, ecvDisplayTools::cameraParamChanged(), ecvDisplayTools::ComputeActualPixelSize(), ecvDisplayTools::ConvertMousePositionToOrientation(), cloudViewer::DegreesToRadians(), ecvDisplayTools::Deprecate3DLayer(), ecvDisplayTools::DisplayNewMessage(), Vector3Tpl< Type >::dot(), ecvDisplayTools::ENTITY_PICKING, ecvDisplayTools::ENTITY_RECT_PICKING, event(), ecvDisplayTools::ExclusiveFullScreen(), ccGLMatrixTpl< double >::FromToRotation(), cloudViewer::ReferenceCloud::getAssociatedCloud(), ecvDisplayTools::GetClick3DPos(), ccGLMatrixTpl< T >::getColumnAsVec3D(), ecvDisplayTools::GetDevicePixelRatio(), ecvDisplayTools::GetGLCameraParameters(), ecvViewportParameters::getPivotPoint(), cloudViewer::GenericIndexedCloudPersist::getPointPersistentPtr(), ecvColor::green(), height, ccGLMatrixTpl< T >::initFromParameters(), ecvDisplayTools::INTERACT_2D_ITEMS, ecvDisplayTools::INTERACT_CLICKABLE_ITEMS, ecvDisplayTools::INTERACT_PAN, ecvDisplayTools::INTERACT_ROTATE, ecvDisplayTools::INTERACT_SIG_MOUSE_MOVED, ecvDisplayTools::INTERACT_TRANSFORM_ENTITIES, ecvDisplayTools::InvalidateViewport(), ecvDisplayTools::labelmove2D(), ecvDisplayTools::LOWER_LEFT_MESSAGE, ecvDisplayTools::m_activeItems, ecvDisplayTools::m_allowRectangularEntityPicking, ecvDisplayTools::m_bubbleViewFov_deg, ecvDisplayTools::m_bubbleViewModeEnabled, ecvDisplayTools::m_clickableItemsVisible, ecvDisplayTools::m_customLightEnabled, ecvDisplayTools::m_customLightPos, ecvDisplayTools::m_hotZone, ecvDisplayTools::m_interactionFlags, m_interactor, ecvDisplayTools::m_lastMouseMovePos, ecvDisplayTools::m_lastMousePos, ecvDisplayTools::m_lockedRotationAxis, ecvDisplayTools::m_mouseMoved, M_PI, ecvDisplayTools::m_pickingMode, ecvDisplayTools::m_rectPickingPoly, m_render, ecvDisplayTools::m_rotationAxisLocked, m_scaleBar, ecvDisplayTools::m_showCursorCoordinates, m_tools, ecvDisplayTools::m_viewportParams, ccGLCameraParameters::modelViewMat, ecvDisplayTools::mouseMoved(), ecvDisplayTools::mousePosChanged(), ecvDisplayTools::MoveCamera(), ecvDisplayTools::NO_PICKING, Vector3Tpl< Type >::norm(), Vector3Tpl< Type >::normalize(), ecvViewportParameters::objectCenteredView, ecvViewportParameters::perspectiveView, ccGLCameraParameters::project(), cloudViewer::RadiansToDegrees(), ecvDisplayTools::HotZone::rect(), ecvDisplayTools::RedrawDisplay(), ccPointCloud::reserve(), ecvDisplayTools::RotateWithAxis(), ecvDisplayTools::rotation(), ecvDisplayTools::scheduleFullRedraw(), ecvDisplayTools::SCREEN_SIZE_MESSAGE, ccPolyline::set2DMode(), cloudViewer::Polyline::setClosed(), ccPolyline::setColor(), ccPolyline::setForeground(), ccDrawableObject::setVisible(), ccDrawableObject::showColors(), ecvDisplayTools::ShowPivotSymbol(), ecvDisplayTools::HotZone::topCorner, ecvDisplayTools::ToVtkCoordinates(), ecvDisplayTools::TRANSFORM_CAMERA(), ecvDisplayTools::translation(), ccGLMatrixTpl< T >::transposed(), ScaleBarWidget::update(), updateActivateditems(), ecvDisplayTools::UpdateActiveItemsList(), ecvDisplayTools::UpdateDisplayParameters(), ecvDisplayTools::UpdateNamePoseRecursive(), ecvDisplayTools::USE_2D, ecvViewportParameters::viewMat, ecvDisplayTools::viewMatRotated(), CVLog::Warning(), width, Tuple3Tpl< Type >::x, x, Tuple3Tpl< Type >::y, y, Tuple3Tpl< Type >::z, and ecvViewportParameters::zFar.
mousePressEvent()
void QVTKWidgetCustom::mousePressEvent (QMouseEvent * event) override protected virtual
Definition at line 502 of file QVTKWidgetCustom.cpp.
References event(), ecvDisplayTools::GetClick3DPos(), ecvDisplayTools::INTERACT_CTRL_PAN, ecvDisplayTools::INTERACT_PAN, ecvDisplayTools::INTERACT_ROTATE, ecvDisplayTools::INTERACT_SIG_LB_CLICKED, ecvDisplayTools::INTERACT_SIG_RB_CLICKED, ecvDisplayTools::leftButtonClicked(), ecvDisplayTools::m_autoPickPivotAtCenter, ecvDisplayTools::m_ignoreMouseReleaseEvent, ecvDisplayTools::m_interactionFlags, ecvDisplayTools::m_last_picked_id, ecvDisplayTools::m_last_point_index, ecvDisplayTools::m_lastClickTime_ticks, ecvDisplayTools::m_lastMousePos, ecvDisplayTools::m_mouseButtonPressed, ecvDisplayTools::m_mouseMoved, ecvDisplayTools::m_timer, m_tools, ecvDisplayTools::rightButtonClicked(), ecvDisplayTools::SetPivotPoint(), and ecvDisplayTools::USE_VTK_PICK.
mouseReleaseEvent()
void QVTKWidgetCustom::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Definition at line 1195 of file QVTKWidgetCustom.cpp.
References ccInteractor::acceptClick(), ecvDisplayTools::buttonReleased(), CC_MAX_PICKING_CLICK_DURATION_MS, ecvDisplayTools::ENTITY_RECT_PICKING, event(), cloudViewer::ReferenceCloud::getAssociatedCloud(), cloudViewer::GenericIndexedCloudPersist::getPointPersistentPtr(), height, ecvDisplayTools::Height(), ecvDisplayTools::INTERACT_2D_ITEMS, ecvDisplayTools::INTERACT_SIG_BUTTON_RELEASED, ecvDisplayTools::m_activeItems, ecvDisplayTools::m_deferredPickingTimer, ecvDisplayTools::m_ignoreMouseReleaseEvent, ecvDisplayTools::m_interactionFlags, ecvDisplayTools::m_lastClickTime_ticks, ecvDisplayTools::m_lastMousePos, ecvDisplayTools::m_mouseButtonPressed, ecvDisplayTools::m_mouseMoved, ecvDisplayTools::m_pivotSymbolShown, ecvDisplayTools::m_pivotVisibility, ecvDisplayTools::m_rectPickingPoly, ecvDisplayTools::m_timer, m_tools, ecvDisplayTools::m_widgetClicked, ecvDisplayTools::PIVOT_ALWAYS_SHOW, ecvDisplayTools::PIVOT_SHOW_ON_MOVE, CVLog::PrintVerbose(), ecvDisplayTools::ProcessClickableItems(), ecvDisplayTools::RefreshDisplay(), ecvDisplayTools::RemoveFromOwnDB(), ecvDisplayTools::ShowPivotSymbol(), ecvDisplayTools::StartPicking(), ecvDisplayTools::ToBeRefreshed(), ecvDisplayTools::TRANSFORM_CAMERA(), ecvDisplayTools::Update2DLabel(), ecvDisplayTools::UpdateActiveItemsList(), ecvDisplayTools::Width(), Tuple3Tpl< Type >::x, x, Tuple3Tpl< Type >::y, and y.
multiViewports()
bool QVTKWidgetCustom::multiViewports () const
Definition at line 364 of file QVTKWidgetCustom.cpp.
References d_ptr.
setActorsVisible()
void QVTKWidgetCustom::setActorsVisible (bool visible)
Definition at line 437 of file QVTKWidgetCustom.cpp.
References d_ptr.
setActorVisible()
void QVTKWidgetCustom::setActorVisible (vtkProp * actor, bool visible)
Definition at line 441 of file QVTKWidgetCustom.cpp.
setBackgroundColor() [1/2]
void QVTKWidgetCustom::setBackgroundColor (const ecvColor::Rgbf & bkg1, const ecvColor::Rgbf & bkg2, bool gradient)
Definition at line 350 of file QVTKWidgetCustom.cpp.
References ecvColor::RgbTpl< Type >::b, ecvColor::RgbTpl< Type >::g, m_render, and ecvColor::RgbTpl< Type >::r.
setBackgroundColor() [2/2]
void QVTKWidgetCustom::setBackgroundColor (const QColor & clr)
Definition at line 449 of file QVTKWidgetCustom.cpp.
References d_ptr, and GetRenderWindow().
setBounds()
void QVTKWidgetCustom::setBounds (double * bounds) protected
Definition at line 484 of file QVTKWidgetCustom.cpp.
References d_ptr.
setCameraFocalPoint()
void QVTKWidgetCustom::setCameraFocalPoint (const CCVector3d & pos)
Definition at line 336 of file QVTKWidgetCustom.cpp.
References m_render, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
setCameraPosition()
void QVTKWidgetCustom::setCameraPosition (const CCVector3d & pos)
Definition at line 329 of file QVTKWidgetCustom.cpp.
References m_render, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
setCameraViewUp()
void QVTKWidgetCustom::setCameraViewUp (const CCVector3d & pos)
Definition at line 343 of file QVTKWidgetCustom.cpp.
References m_render, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
setMultiViewports()
void QVTKWidgetCustom::setMultiViewports (bool multi = true)
Definition at line 358 of file QVTKWidgetCustom.cpp.
References d_ptr.
SetRenderWindow()
void QVTKWidgetCustom::SetRenderWindow (vtkRenderWindow * win) inline
Definition at line 100 of file QVTKWidgetCustom.h.
Referenced by PCLDisplayTools::registerVisualizer().
setScaleBarVisible()
void QVTKWidgetCustom::setScaleBarVisible (bool visible) inline
Definition at line 132 of file QVTKWidgetCustom.h.
toDisplayPoint() [1/2]
void QVTKWidgetCustom::toDisplayPoint (const CCVector3 & worldPos, CCVector3d & displayPos)
Definition at line 324 of file QVTKWidgetCustom.cpp.
References Vector3Tpl< double >::fromArray(), toDisplayPoint(), and Tuple3Tpl< Type >::u.
toDisplayPoint() [2/2]
void QVTKWidgetCustom::toDisplayPoint (const CCVector3d & worldPos, CCVector3d & displayPos)
Definition at line 315 of file QVTKWidgetCustom.cpp.
References m_render, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by toDisplayPoint().
toWorldPoint() [1/2]
void QVTKWidgetCustom::toWorldPoint (const CCVector3 & input2D, CCVector3d & output3D)
Definition at line 310 of file QVTKWidgetCustom.cpp.
References Vector3Tpl< double >::fromArray(), toWorldPoint(), and Tuple3Tpl< Type >::u.
toWorldPoint() [2/2]
void QVTKWidgetCustom::toWorldPoint (const CCVector3d & input2D, CCVector3d & output3D)
Definition at line 296 of file QVTKWidgetCustom.cpp.
References m_render, Tuple3Tpl< Type >::u, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by toWorldPoint().
transformCameraProjection()
void QVTKWidgetCustom::transformCameraProjection (const double * projMat)
Definition at line 274 of file QVTKWidgetCustom.cpp.
References m_camera.
Referenced by PCLDisplayTools::transformCameraProjection().
transformCameraView()
void QVTKWidgetCustom::transformCameraView (const double * viewMat)
Definition at line 264 of file QVTKWidgetCustom.cpp.
References m_render.
Referenced by PCLDisplayTools::transformCameraView().
updateActivateditems()
void QVTKWidgetCustom::updateActivateditems (int x, int y, int dx, int dy, bool updatePosition = false) protected virtual
Definition at line 1168 of file QVTKWidgetCustom.cpp.
References ccGLMatrixTpl< T >::applyRotation(), ecvDisplayTools::ComputeActualPixelSize(), ecvDisplayTools::Deprecate3DLayer(), ecvDisplayTools::GetDevicePixelRatio(), ecvDisplayTools::GlHeight(), ecvDisplayTools::GlWidth(), ecvDisplayTools::InvalidateViewport(), ecvDisplayTools::m_activeItems, m_tools, ecvDisplayTools::m_viewportParams, ecvDisplayTools::Redraw2DLabel(), ccGLMatrixTpl< T >::transposed(), ecvViewportParameters::viewMat, x, and y.
Referenced by mouseMoveEvent().
updateScene()
void QVTKWidgetCustom::updateScene ()
Definition at line 285 of file QVTKWidgetCustom.cpp.
References GetRenderWindow(), IsCalledFromMainThread(), m_interactor, m_render, m_scaleBar, and ScaleBarWidget::update().
wheelEvent()
void QVTKWidgetCustom::wheelEvent (QWheelEvent * event) override protected virtual
Definition at line 572 of file QVTKWidgetCustom.cpp.
References ecvDisplayTools::cameraParamChanged(), ecvViewportParameters::defaultPointSize, event(), ecvViewportParameters::fov_deg, ecvViewportParameters::IncrementToZNearCoef(), ecvDisplayTools::INTERACT_ZOOM_CAMERA, ecvDisplayTools::labelmove2D(), ecvDisplayTools::m_interactionFlags, m_tools, ecvDisplayTools::m_viewportParams, m_wheelZoomUpdateTimer, ecvDisplayTools::mouseWheelChanged(), ecvDisplayTools::mouseWheelRotated(), ecvDisplayTools::onWheelEvent(), ecvViewportParameters::perspectiveView, qtCompatWheelEventDelta(), ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::SetFov(), ecvDisplayTools::SetPointSize(), ecvDisplayTools::SetRedrawRecursive(), ecvDisplayTools::SetZNearCoef(), ecvDisplayTools::Update(), ecvDisplayTools::UpdateNamePoseRecursive(), ecvViewportParameters::zNearCoef, and ecvViewportParameters::ZNearCoefToIncrement().
xMax()
double QVTKWidgetCustom::xMax () const protected
Definition at line 491 of file QVTKWidgetCustom.cpp.
References d_ptr.
xMin()
double QVTKWidgetCustom::xMin () const protected
Definition at line 489 of file QVTKWidgetCustom.cpp.
References d_ptr.
yMax()
double QVTKWidgetCustom::yMax () const protected
Definition at line 495 of file QVTKWidgetCustom.cpp.
References d_ptr.
yMin()
double QVTKWidgetCustom::yMin () const protected
Definition at line 493 of file QVTKWidgetCustom.cpp.
References d_ptr.
zMax()
double QVTKWidgetCustom::zMax () const protected
Definition at line 499 of file QVTKWidgetCustom.cpp.
References d_ptr.
zMin()
double QVTKWidgetCustom::zMin () const protected
Definition at line 497 of file QVTKWidgetCustom.cpp.
References d_ptr.
Member Data Documentation
d_ptr
VtkWidgetPrivate* QVTKWidgetCustom::d_ptr protected
Definition at line 184 of file QVTKWidgetCustom.h.
Referenced by actors(), addActor(), addViewProp(), backgroundColor(), defaultRenderer(), defaultRendererTaken(), multiViewports(), QVTKWidgetCustom(), setActorsVisible(), setBackgroundColor(), setBounds(), setMultiViewports(), xMax(), xMin(), yMax(), yMin(), zMax(), zMin(), and ~QVTKWidgetCustom().
m_axesWidget
vtkSmartPointer<vtkOrientationMarkerWidget> QVTKWidgetCustom::m_axesWidget protected
Internal pointer to widget which contains a set of axes.
Definition at line 180 of file QVTKWidgetCustom.h.
m_camera
vtkSmartPointer<vtkCamera> QVTKWidgetCustom::m_camera protected
Definition at line 167 of file QVTKWidgetCustom.h.
Referenced by initVtk(), and transformCameraProjection().
m_color1
QColor QVTKWidgetCustom::m_color1 = Qt::blue protected
Definition at line 162 of file QVTKWidgetCustom.h.
Referenced by createLookupTable().
m_color2
QColor QVTKWidgetCustom::m_color2 = Qt::red protected
Definition at line 163 of file QVTKWidgetCustom.h.
Referenced by createLookupTable().
m_dataObject
vtkDataObject* QVTKWidgetCustom::m_dataObject protected
Definition at line 158 of file QVTKWidgetCustom.h.
m_filterActor
vtkLODActor* QVTKWidgetCustom::m_filterActor = nullptr protected
Definition at line 160 of file QVTKWidgetCustom.h.
m_interactor
vtkSmartPointer<vtkRenderWindowInteractor> QVTKWidgetCustom::m_interactor protected
Definition at line 171 of file QVTKWidgetCustom.h.
Referenced by event(), initVtk(), mouseMoveEvent(), and updateScene().
m_logoWidget
vtkSmartPointer<vtkLogoWidget> QVTKWidgetCustom::m_logoWidget protected
Internal pointer to widget which contains a logo_Widget_.
Definition at line 174 of file QVTKWidgetCustom.h.
m_modelActor
vtkActor* QVTKWidgetCustom::m_modelActor = nullptr protected
Definition at line 159 of file QVTKWidgetCustom.h.
m_planes
vtkSmartPointer<vtkPlanes> QVTKWidgetCustom::m_planes protected
Definition at line 165 of file QVTKWidgetCustom.h.
m_render
vtkRenderer* QVTKWidgetCustom::m_render protected
Definition at line 154 of file QVTKWidgetCustom.h.
Referenced by event(), initVtk(), mouseMoveEvent(), setBackgroundColor(), setCameraFocalPoint(), setCameraPosition(), setCameraViewUp(), toDisplayPoint(), toWorldPoint(), transformCameraView(), and updateScene().
m_renders
vtkSmartPointer<vtkRendererCollection> QVTKWidgetCustom::m_renders protected
Definition at line 169 of file QVTKWidgetCustom.h.
Referenced by initVtk().
m_scalarbarWidget
vtkSmartPointer<vtkScalarBarWidget> QVTKWidgetCustom::m_scalarbarWidget protected
Internal pointer to widget which contains a scalarbar_Widget_.
Definition at line 177 of file QVTKWidgetCustom.h.
m_scaleBar
ScaleBarWidget* QVTKWidgetCustom::m_scaleBar = nullptr protected
Definition at line 182 of file QVTKWidgetCustom.h.
Referenced by event(), initVtk(), mouseMoveEvent(), updateScene(), and ~QVTKWidgetCustom().
m_tools
ecvDisplayTools* QVTKWidgetCustom::m_tools protected
Definition at line 156 of file QVTKWidgetCustom.h.
Referenced by dropEvent(), event(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), QVTKWidgetCustom(), updateActivateditems(), and wheelEvent().
m_unclosable
bool QVTKWidgetCustom::m_unclosable = true protected
Definition at line 152 of file QVTKWidgetCustom.h.
Referenced by event().
m_useVBO
bool QVTKWidgetCustom::m_useVBO = false protected
Definition at line 153 of file QVTKWidgetCustom.h.
Referenced by initVtk().
m_wheelZoomUpdateTimer
QTimer* QVTKWidgetCustom::m_wheelZoomUpdateTimer = nullptr protected
Definition at line 187 of file QVTKWidgetCustom.h.
Referenced by QVTKWidgetCustom(), wheelEvent(), and ~QVTKWidgetCustom().
m_win
QMainWindow* QVTKWidgetCustom::m_win protected
Definition at line 155 of file QVTKWidgetCustom.h.
Referenced by event().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Widgets/QVTKWidgetCustom.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Widgets/QVTKWidgetCustom.cpp