ACloudViewer: flann::mpi::Client Class Reference
flann::mpi::Client Class Reference
#include <client.h>
Public Member Functions
Client (const std::string &host, const std::string &service)
template<typename ElementType , typename DistanceType >
void knnSearch (const flann::Matrix< ElementType > &queries, flann::Matrix< int > &indices, flann::Matrix< DistanceType > &dists, int knn, const SearchParams &params)
Detailed Description
Definition at line 43 of file client.h.
Constructor & Destructor Documentation
Client()
flann::mpi::Client::Client (const std::string & host, const std::string & service) inline
Definition at line 46 of file client.h.
Member Function Documentation
knnSearch()
template<typename ElementType , typename DistanceType > void flann::mpi::Client::knnSearch (const flann::Matrix< ElementType > & queries, flann::Matrix< int > & indices, flann::Matrix< DistanceType > & dists, int knn, const SearchParams & params) inline
Definition at line 55 of file client.h.
References flann::Request< T >::checks, flann::Matrix_::cols, flann::Response< T >::dists, flann::Response< T >::indices, flann::Request< T >::nn, params, flann::Request< T >::queries, flann::read_object(), flann::Matrix_::rows, and flann::write_object().
Referenced by main().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/mpi/client.h