ACloudViewer: cvThresholdFilter Class Reference
cvThresholdFilter Class Reference
#include <cvThresholdFilter.h>
Public Member Functions
cvThresholdFilter (QWidget *parent=nullptr)
~cvThresholdFilter ()
virtual void apply () override
virtual ccHObject * getOutput () override
virtual void clearAllActor () override
virtual void initFilter () override
Public Member Functions inherited from cvIsoSurfaceFilter
cvIsoSurfaceFilter (QWidget *parent=0)
~cvIsoSurfaceFilter ()
Public Member Functions inherited from cvGenericFilter
cvGenericFilter (QWidget *parent=nullptr)
virtual ~cvGenericFilter ()
virtual void start ()
virtual void update ()
virtual void reset ()
virtual void restoreOrigin ()
virtual void getOutput (std::vector< ccHObject * > &outputSlices, std::vector< ccPolyline * > &outputContours)
virtual bool initModel ()
virtual bool setInput (ccHObject *obj)
virtual void shift (const CCVector3d &v)
Shifts the current interactor.
virtual void updateUi ()
virtual void showInteractor (bool state)
virtual void getInteractorInfos (ccBBox &bbox, ccGLMatrixd &trans)
virtual void getInteractorTransformation (ccGLMatrixd &trans)
virtual void getInteractorBounds (ccBBox &bbox)
void setUpViewer (PclUtils::PCLVis *viewer)
void showOutline (bool show=true)
void setNegative (bool state)
void setInteractor (vtkRenderWindowInteractor *interactor)
vtkRenderWindowInteractor * getInteractor ()
Protected Attributes
vtkSmartPointer< vtkDataSetSurfaceFilter > m_dssFilter
Protected Attributes inherited from cvIsoSurfaceFilter
Ui::cvIsoSurfaceFilterDlg * m_configUi = nullptr
double m_minScalar = .0
double m_maxScalar = .0
int m_numOfContours = 10
QString m_currentScalarName
vtkSmartPointer< vtkContourFilter > m_contourFilter
Protected Attributes inherited from cvGenericFilter
Ui::GenericFilterDlg * m_ui = nullptr
DisplayEffect m_displayEffect = Opaque
vtkDataObject * m_dataObject = nullptr
vtkSmartPointer< vtkDataObject > m_resultData
bool m_keepMode
bool m_negative
bool m_meshMode
bool m_preview
std::string m_id
ccHObject * m_entity = nullptr
PclUtils::PCLVis * m_viewer = nullptr
vtkRenderWindowInteractor * m_interactor = nullptr
vtkSmartPointer< vtkActor > m_modelActor
vtkSmartPointer< vtkLODActor > m_filterActor
vtkSmartPointer< vtkScalarBarActor > m_scalarBar
vtkSmartPointer< vtkActor > m_outlineActor
QColor m_color1 = Qt::blue
QColor m_color2 = Qt::red
double m_scalarMin = 0.0
double m_scalarMax = 1.0
Additional Inherited Members
Protected Types inherited from cvGenericFilter
enum DisplayEffect { Opaque , Transparent , Points , Wireframe }
Protected Slots inherited from cvIsoSurfaceFilter
void onDoubleSpinBoxValueChanged (double value)
void onSpinBoxValueChanged (int value)
void onComboBoxIndexChanged (int index)
void on_gradientCombo_activated (int index)
Protected Slots inherited from cvGenericFilter
void onDoubleClick (int x, int y)
Protected Member Functions inherited from cvIsoSurfaceFilter
virtual void createUi () override
virtual void modelReady () override
virtual void colorsChanged () override
virtual void dataChanged () override
Protected Member Functions inherited from cvGenericFilter
void setDisplayEffect (DisplayEffect effect)
DisplayEffect displayEffect () const
void safeOff (vtk3DWidget *widget)
void updateSize ()
void UpdateScalarRange ()
void applyDisplayEffect ()
void setScalarBarColors (const QColor &clr1, const QColor &clr2)
QColor color1 () const
QColor color2 () const
void setScalarRange (double min, double max)
double scalarMin () const
double scalarMax () const
vtkSmartPointer< vtkDataArray > getActorScalars (vtkSmartPointer< vtkActor > actor)
int getDefaultScalarInterpolationForDataSet (vtkDataSet *data)
vtkSmartPointer< vtkLookupTable > createLookupTable (double min, double max)
template<class ConfigClass >
void setupConfigWidget (ConfigClass *cc)
template<class DataObject , class Mapper >
void createActorFromData (vtkDataObject *dataObj)
void showScalarBar (bool show=true)
void setOutlineColor (const QColor &clr)
bool isValidPolyData () const
bool isValidDataSet () const
void addActor (const vtkSmartPointer< vtkProp > actor)
void removeActor (const vtkSmartPointer< vtkProp > actor)
void setResultData (vtkSmartPointer< vtkDataObject > data)
vtkSmartPointer< vtkDataObject > resultData () const
Static Protected Attributes inherited from cvGenericFilter
static const int MAX_PREVIEW_NUMBER = 20e4
Detailed Description
Definition at line 13 of file cvThresholdFilter.h.
Constructor & Destructor Documentation
cvThresholdFilter()
cvThresholdFilter::cvThresholdFilter (QWidget * parent = nullptr) explicit
Definition at line 23 of file cvThresholdFilter.cpp.
~cvThresholdFilter()
cvThresholdFilter::~cvThresholdFilter ()
Definition at line 28 of file cvThresholdFilter.cpp.
Member Function Documentation
apply()
void cvThresholdFilter::apply () override virtual
Reimplemented from cvIsoSurfaceFilter.
Definition at line 30 of file cvThresholdFilter.cpp.
References cvGenericFilter::addActor(), cvGenericFilter::applyDisplayEffect(), cvGenericFilter::createLookupTable(), CVLog::Error(), cvGenericFilter::m_dataObject, m_dssFilter, cvGenericFilter::m_filterActor, cvIsoSurfaceFilter::m_maxScalar, cvIsoSurfaceFilter::m_minScalar, cvIsoSurfaceFilter::m_numOfContours, cvGenericFilter::m_scalarBar, VTK_CREATE, and VtkUtils::vtkInitOnce().
clearAllActor()
void cvThresholdFilter::clearAllActor () override virtual
Reimplemented from cvIsoSurfaceFilter.
Definition at line 78 of file cvThresholdFilter.cpp.
References cvIsoSurfaceFilter::clearAllActor().
getOutput()
ccHObject * cvThresholdFilter::getOutput () override virtual
Reimplemented from cvIsoSurfaceFilter.
Definition at line 70 of file cvThresholdFilter.cpp.
References cvGenericFilter::getOutput(), m_dssFilter, and cvGenericFilter::setResultData().
initFilter()
void cvThresholdFilter::initFilter () override virtual
Reimplemented from cvIsoSurfaceFilter.
Definition at line 80 of file cvThresholdFilter.cpp.
References cvIsoSurfaceFilter::initFilter(), and cvIsoSurfaceFilter::m_configUi.
Member Data Documentation
m_dssFilter
vtkSmartPointer<vtkDataSetSurfaceFilter> cvThresholdFilter::m_dssFilter protected
Definition at line 28 of file cvThresholdFilter.h.
Referenced by apply(), and getOutput().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/cvThresholdFilter.h
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/cvThresholdFilter.cpp