ACloudViewer: flann::KNNRadiusResultSet< DistanceType > Class Template Reference
flann::KNNRadiusResultSet< DistanceType > Class Template Reference
#include <result_set.h>
Public Types
typedef DistanceIndex< DistanceType > DistIndex
Public Member Functions
KNNRadiusResultSet (DistanceType radius_, size_t capacity_)
~KNNRadiusResultSet ()
void clear ()
size_t size () const
bool full () const
void addPoint (DistanceType dist, size_t index)
void copy (size_t *indices, DistanceType *dists, size_t num_elements, bool sorted=true)
DistanceType worstDist () const
Public Member Functions inherited from flann::ResultSet< DistanceType >
virtual ~ResultSet ()
Detailed Description
template<typename DistanceType>
class flann::KNNRadiusResultSet< DistanceType >
Bounded radius result set. It limits the number of elements it can hold to a preset capacity.
Definition at line 527 of file result_set.h.
Member Typedef Documentation
DistIndex
template<typename DistanceType > typedef DistanceIndex<DistanceType> flann::KNNRadiusResultSet< DistanceType >::DistIndex
Definition at line 530 of file result_set.h.
Constructor & Destructor Documentation
KNNRadiusResultSet()
template<typename DistanceType > flann::KNNRadiusResultSet< DistanceType >::KNNRadiusResultSet (DistanceType radius_, size_t capacity_) inline
Definition at line 532 of file result_set.h.
References flann::KNNRadiusResultSet< DistanceType >::clear().
~KNNRadiusResultSet()
template<typename DistanceType > flann::KNNRadiusResultSet< DistanceType >::~KNNRadiusResultSet () inline
Definition at line 540 of file result_set.h.
Member Function Documentation
addPoint()
template<typename DistanceType > void flann::KNNRadiusResultSet< DistanceType >::addPoint (DistanceType dist, size_t index) inline virtual
Add another point to result set
Parameters
dist distance to point
index index of point Pre-conditions: capacity_>0
Implements flann::ResultSet< DistanceType >.
Definition at line 578 of file result_set.h.
References dist(), and flann::cuda::heap::make_heap().
clear()
template<typename DistanceType > void flann::KNNRadiusResultSet< DistanceType >::clear () inline
Clears the result set
Definition at line 547 of file result_set.h.
Referenced by flann::KNNRadiusResultSet< DistanceType >::KNNRadiusResultSet(), and flann::NNIndex< Distance >::radiusSearch().
copy()
template<typename DistanceType > void flann::KNNRadiusResultSet< DistanceType >::copy (size_t * indices, DistanceType * dists, size_t num_elements, bool sorted = true) inline
Copy indices and distances to output buffers
Parameters
indices
dists
num_elements Number of elements to copy
sorted Indicates if results should be sorted
Definition at line 612 of file result_set.h.
References min(), and flann::KNNRadiusResultSet< DistanceType >::size().
Referenced by flann::NNIndex< Distance >::radiusSearch().
full()
template<typename DistanceType > bool flann::KNNRadiusResultSet< DistanceType >::full () const inline virtual
Radius search result set always reports full
Returns
Implements flann::ResultSet< DistanceType >.
Definition at line 567 of file result_set.h.
size()
template<typename DistanceType > size_t flann::KNNRadiusResultSet< DistanceType >::size () const inline
Returns
Number of elements in the result set
Definition at line 558 of file result_set.h.
Referenced by flann::KNNRadiusResultSet< DistanceType >::copy(), and flann::NNIndex< Distance >::radiusSearch().
worstDist()
template<typename DistanceType > DistanceType flann::KNNRadiusResultSet< DistanceType >::worstDist () const inline virtual
Implements flann::ResultSet< DistanceType >.
Definition at line 632 of file result_set.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/util/result_set.h