ACloudViewer: qCanupoClassifDialog Class Reference
qCanupoClassifDialog Class Reference
CANUPO plugin's classification dialog.
#include <qCanupoClassifDialog.h>
Public Types
enum CORE_CLOUD_SOURCES { ORIGINAL , OTHER , SUBSAMPLED , MSC_FILE }
"Sources" of core points
Public Member Functions
qCanupoClassifDialog (ccPointCloud *cloud, ecvMainAppInterface *app)
Default constructor.
CORE_CLOUD_SOURCES getCorePointsCloudSource () const
Returns the selected source for core points.
ccPointCloud * getCorePointsCloud ()
Get core points cloud (if any)
QString getMscFilename () const
Returns MSC file name (if source == MSC_FILE)
double getConfidenceTrehshold () const
Returns the confidence threshold.
bool useSF () const
int getMaxThreadCount () const
Returns the max number of threads to use.
void loadParamsFromPersistentSettings ()
Loads parameters from persistent settings.
void saveParamsToPersistentSettings ()
Saves parameters to persistent settings.
Protected Slots
void browseClassifierFile ()
void browseMscFile ()
Protected Attributes
ecvMainAppInterface * m_app
Gives access to the application (data-base, UI, etc.)
ccPointCloud * m_cloud
Associated cloud.
Detailed Description
CANUPO plugin's classification dialog.
Definition at line 16 of file qCanupoClassifDialog.h.
Member Enumeration Documentation
CORE_CLOUD_SOURCES
enum qCanupoClassifDialog::CORE_CLOUD_SOURCES
"Sources" of core points
Enumerator
ORIGINAL
OTHER
SUBSAMPLED
MSC_FILE
Definition at line 24 of file qCanupoClassifDialog.h.
Constructor & Destructor Documentation
qCanupoClassifDialog()
qCanupoClassifDialog::qCanupoClassifDialog (ccPointCloud * cloud, ecvMainAppInterface * app)
Default constructor.
Definition at line 28 of file qCanupoClassifDialog.cpp.
References browseClassifierFile(), browseMscFile(), ccPointCloud::getCurrentDisplayedScalarField(), qCanupoTools::GetEntityName(), loadParamsFromPersistentSettings(), m_app, and CV_TYPES::POINT_CLOUD.
Member Function Documentation
browseClassifierFile
void qCanupoClassifDialog::browseClassifierFile () protected slot
Definition at line 230 of file qCanupoClassifDialog.cpp.
References Classifier::FileHeader::classifierCount, computer, Classifier::FileHeader::descID, Classifier::FileHeader::dimPerScale, error(), ScaleParamsComputer::GetByID(), ScaleParamsComputer::getName(), and Classifier::Load().
Referenced by qCanupoClassifDialog().
browseMscFile
void qCanupoClassifDialog::browseMscFile () protected slot
Definition at line 212 of file qCanupoClassifDialog.cpp.
Referenced by qCanupoClassifDialog().
getConfidenceTrehshold()
double qCanupoClassifDialog::getConfidenceTrehshold () const
Returns the confidence threshold.
Definition at line 75 of file qCanupoClassifDialog.cpp.
Referenced by qCanupoPlugin::doClassifyAction().
getCorePointsCloud()
ccPointCloud * qCanupoClassifDialog::getCorePointsCloud ()
Get core points cloud (if any)
Returns either the input cloud (ORIGINAL) or the other cloud specified in the dedicated combo box (OTHER). It can also return a null pointer if the user has requested sub-sampling (SUBSAMPLED) or MSC file (MSC_FILE).
Definition at line 111 of file qCanupoClassifDialog.cpp.
References qCanupoTools::GetCloudFromCombo(), m_app, and m_cloud.
Referenced by qCanupoPlugin::doClassifyAction().
getCorePointsCloudSource()
qCanupoClassifDialog::CORE_CLOUD_SOURCES qCanupoClassifDialog::getCorePointsCloudSource () const
Returns the selected source for core points.
Definition at line 92 of file qCanupoClassifDialog.cpp.
References MSC_FILE, ORIGINAL, OTHER, and SUBSAMPLED.
Referenced by qCanupoPlugin::doClassifyAction().
getMaxThreadCount()
int qCanupoClassifDialog::getMaxThreadCount () const
Returns the max number of threads to use.
Definition at line 87 of file qCanupoClassifDialog.cpp.
Referenced by qCanupoPlugin::doClassifyAction().
getMscFilename()
QString qCanupoClassifDialog::getMscFilename () const
Returns MSC file name (if source == MSC_FILE)
Definition at line 107 of file qCanupoClassifDialog.cpp.
Referenced by qCanupoPlugin::doClassifyAction().
loadParamsFromPersistentSettings()
void qCanupoClassifDialog::loadParamsFromPersistentSettings ()
Loads parameters from persistent settings.
Definition at line 123 of file qCanupoClassifDialog.cpp.
References useSF().
Referenced by qCanupoClassifDialog().
saveParamsToPersistentSettings()
void qCanupoClassifDialog::saveParamsToPersistentSettings ()
Saves parameters to persistent settings.
Definition at line 186 of file qCanupoClassifDialog.cpp.
Referenced by qCanupoPlugin::doClassifyAction().
useSF()
bool qCanupoClassifDialog::useSF () const
Returns whether a SF should be used to classify points with low confidence
Definition at line 83 of file qCanupoClassifDialog.cpp.
Referenced by qCanupoPlugin::doClassifyAction(), and loadParamsFromPersistentSettings().
Member Data Documentation
m_app
ecvMainAppInterface* qCanupoClassifDialog::m_app protected
Gives access to the application (data-base, UI, etc.)
Definition at line 60 of file qCanupoClassifDialog.h.
Referenced by getCorePointsCloud(), and qCanupoClassifDialog().
m_cloud
ccPointCloud* qCanupoClassifDialog::m_cloud protected
Associated cloud.
Definition at line 63 of file qCanupoClassifDialog.h.
Referenced by getCorePointsCloud().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCanupo/include/qCanupoClassifDialog.h
/root/ACloudViewer/plugins/core/Standard/qCanupo/src/qCanupoClassifDialog.cpp