ACloudViewer: ccMesh Class Reference
ccMesh Class Reference
Triangular mesh.
#include <ecvMesh.h>
Classes
struct Material
Public Types
enum MESH_SCALAR_FIELD_PROCESS { SMOOTH_MESH_SF , ENHANCE_MESH_SF }
Mesh scalar field processes.
using triangleIndexesContainer = ccArray< cloudViewer::VerticesIndexes, 3, unsigned >
Container of per-triangle vertices indexes (3)
using triangleMaterialIndexesSet = ccArray< int, 1, int >
Container of per-triangle material descriptors.
Public Types inherited from cloudViewer::GenericMesh
enum class SimplificationContraction { Average , Quadric }
Indicates the method that is used for mesh simplification if multiple vertices are combined to a single one.
enum class FilterScope { All , Color , Normal , Vertex }
Indicates the scope of filter operations.
enum class DeformAsRigidAsPossibleEnergy { Spokes , Smoothed }
using genericTriangleAction = std::function< void(GenericTriangle &)>
Generic function to apply to a triangle (used by foreach)
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Public Member Functions
ccMesh (ccGenericPointCloud *vertices=nullptr)
Default ccMesh constructor.
ccMesh (const ccMesh &mesh)
ccMesh (const std::vector< Eigen::Vector3d > &vertices, const std::vector< Eigen::Vector3i > &triangles)
Parameterized Constructor.
ccMesh (cloudViewer::GenericIndexedMesh *giMesh, ccGenericPointCloud *giVertices)
ccMesh constructor (from a cloudViewer::GenericIndexedMesh)
~ccMesh () override
Default destructor.
CV_CLASS_ENUM getClassID () const override
Returns class ID.
void setAssociatedCloud (ccGenericPointCloud *cloud)
Sets the associated vertices cloud (warning)
ccMesh * cloneMesh (ccGenericPointCloud *vertices=nullptr, ccMaterialSet *clonedMaterials=nullptr, NormsIndexesTableType *clonedNormsTable=nullptr, TextureCoordsContainer *cloneTexCoords=nullptr)
Clones this entity.
ccMesh * partialClone (const std::vector< unsigned > &triangleIndices, int *warnings=nullptr) const
Creates a new mesh from a selection of triangles (partial clone)
bool merge (const ccMesh *mesh, bool createSubMesh)
Merges another mesh into this one.
ccMesh & operator= (const ccMesh &mesh)
ccMesh & operator+= (const ccMesh &mesh)
ccMesh operator+ (const ccMesh &mesh) const
void clear ()
unsigned getUniqueIDForDisplay () const override
Returns object unqiue ID used for display.
ccBBox getOwnBB (bool withGLFeatures=false) override
Returns the entity's own bounding-box.
bool isSerializable () const override
Returns whether object is serializable of not.
const ccGLMatrix & getGLTransformationHistory () const override
Returns the transformation 'history' matrix.
ccGenericPointCloud * getAssociatedCloud () const override
Returns the vertices cloud.
void refreshBB () override
Forces bounding-box update.
bool interpolateNormalsBC (unsigned triIndex, const CCVector3d &w, CCVector3 &N) override
Interpolates normal(s) inside a given triangle.
bool interpolateColors (unsigned triIndex, const CCVector3 &P, ecvColor::Rgb &C) override
Interpolates RGB colors inside a given triangle.
void computeInterpolationWeights (unsigned triIndex, const CCVector3 &P, CCVector3d &weights) const override
Returns the (barycentric) interpolation weights for a given triangle.
bool getColorFromMaterial (unsigned triIndex, const CCVector3 &P, ecvColor::Rgb &C, bool interpolateColorIfNoTexture) override
bool getVertexColorFromMaterial (unsigned triIndex, unsigned char vertIndex, ecvColor::Rgb &C, bool returnColorIfNoTexture) override
unsigned capacity () const override
Returns max capacity.
void forEach (genericTriangleAction action) override
Fast iteration mechanism.
void placeIteratorAtBeginning () override
Places the mesh iterator at the beginning.
cloudViewer::GenericTriangle * _getNextTriangle () override
Returns the next triangle (relatively to the global iterator position)
cloudViewer::GenericTriangle * _getTriangle (unsigned triangleIndex) override
Returns the ith triangle.
cloudViewer::VerticesIndexes * getNextTriangleVertIndexes () override
cloudViewer::VerticesIndexes * getTriangleVertIndexes (unsigned triangleIndex) override
Returns the indexes of the vertices of a given triangle.
virtual void getTriangleVertices (unsigned triangleIndex, CCVector3 &A, CCVector3 &B, CCVector3 &C) const override
Returns the vertices of a given triangle.
virtual void getTriangleVertices (unsigned triangleIndex, double A[3], double B[3], double C[3]) const override
unsigned int getVerticeSize () const
Eigen::Vector3d getVertice (size_t index) const
void setVertice (size_t index, const Eigen::Vector3d &vertice)
void addVertice (const Eigen::Vector3d &vertice)
std::vector< Eigen::Vector3d > getEigenVertices () const
void addEigenVertices (const std::vector< Eigen::Vector3d > &vertices)
void setEigenVertices (const std::vector< Eigen::Vector3d > &vertices)
Eigen::Vector3d getVertexNormal (size_t index) const
void setVertexNormal (size_t index, const Eigen::Vector3d &normal)
void addVertexNormal (const Eigen::Vector3d &normal)
std::vector< Eigen::Vector3d > getVertexNormals () const
void addVertexNormals (const std::vector< Eigen::Vector3d > &normals)
void setVertexNormals (const std::vector< Eigen::Vector3d > &normals)
Eigen::Vector3d getVertexColor (size_t index) const
void setVertexColor (size_t index, const Eigen::Vector3d &color)
void addVertexColor (const Eigen::Vector3d &color)
std::vector< Eigen::Vector3d > getVertexColors () const
ColorsTableType * getVertexColorsPtr ()
void addVertexColors (const std::vector< Eigen::Vector3d > &colors)
void setVertexColors (const std::vector< Eigen::Vector3d > &colors)
bool HasVertices () const
std::vector< CCVector3 > & getVerticesPtr ()
const std::vector< CCVector3 > & getVertices () const
virtual unsigned size () const override
Returns the number of triangles.
void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax) override
Returns the mesh bounding-box.
bool normalsAvailable () const override
Returns whether normals are available.
bool interpolateNormals (unsigned triIndex, const CCVector3 &P, CCVector3 &N) override
Interpolates normal(s) inside a given triangle.
void getTriangleVertIndexes (size_t triangleIndex, Eigen::Vector3i &vertIndx) const
virtual const cloudViewer::VerticesIndexes * getTriangleVertIndexes (unsigned triangleIndex) const
bool hasColors () const override
Returns whether colors are enabled or not.
bool hasNormals () const override
Returns whether normals are enabled or not.
bool HasVertexNormals () const
bool hasScalarFields () const override
Returns whether one or more scalar fields are instantiated.
bool hasDisplayedScalarField () const override
Returns whether an active scalar field is available or not.
bool normalsShown () const override
Returns whether normals are shown or not.
void toggleMaterials () override
Toggles material display state.
void invertNormals ()
Inverts normals (if any)
void shiftTriangleIndexes (unsigned shift)
Shifts all triangles indexes.
void flipTriangles ()
Flips the triangle.
void addTriangle (unsigned i1, unsigned i2, unsigned i3)
Adds a triangle to the mesh.
void addTriangle (const cloudViewer::VerticesIndexes &triangle)
void addTriangle (const Eigen::Vector3i &index)
void addTriangles (const std::vector< Eigen::Vector3i > &triangles)
void setTriangle (size_t index, const Eigen::Vector3i &triangle)
void setTriangles (const std::vector< Eigen::Vector3i > &triangles)
Eigen::Vector3i getTriangle (size_t index) const
std::vector< Eigen::Vector3i > getTriangles () const
triangleIndexesContainer * getTrianglesPtr () const
bool reserve (std::size_t n)
Reserves the memory to store the vertex indexes (3 per triangle)
bool reserveAssociatedCloud (std::size_t n, bool init_color=false, bool init_normal=false)
bool resize (size_t n)
Resizes the array of vertex indexes (3 per triangle)
bool resizeAssociatedCloud (std::size_t n)
void shrinkToFit ()
Removes unused capacity.
void shrinkVertexToFit ()
bool hasTriNormals () const override
Returns whether the mesh has per-triangle normals.
bool HasTriangleNormals () const
void getTriangleNormalIndexes (unsigned triangleIndex, int &i1, int &i2, int &i3) const override
Returns a triplet of normal indexes for a given triangle (if any)
bool getTriangleNormals (unsigned triangleIndex, CCVector3 &Na, CCVector3 &Nb, CCVector3 &Nc) const override
Returns a given triangle normal.
bool getTriangleNormals (unsigned triangleIndex, double Na[3], double Nb[3], double Nc[3]) const override
bool getTriangleNormals (unsigned triangleIndex, Eigen::Vector3d &Na, Eigen::Vector3d &Nb, Eigen::Vector3d &Nc) const override
std::vector< Eigen::Vector3d > getTriangleNormals () const
std::vector< CCVector3 * > getTriangleNormalsPtr () const
Eigen::Vector3d getTriangleNorm (size_t index) const
bool setTriangleNorm (size_t index, const Eigen::Vector3d &triangle_normal)
bool setTriangleNormalIndexes (size_t triangleIndex, CompressedNormType value)
CompressedNormType getTriangleNormalIndexes (size_t triangleIndex)
bool addTriangleNorm (const CCVector3 &N)
bool addTriangleNorm (const Eigen::Vector3d &N)
std::vector< Eigen::Vector3d > getTriangleNorms () const
bool setTriangleNorms (const std::vector< Eigen::Vector3d > &triangle_normals)
bool addTriangleNorms (const std::vector< Eigen::Vector3d > &triangle_normals)
NormsIndexesTableType * getTriNormsTable () const override
Returns per-triangle normals shared array.
void setTriNormsTable (NormsIndexesTableType *triNormsTable, bool autoReleaseOldTable=true)
Sets per-triangle normals array (may be shared)
void clearTriNormals ()
Removes per-triangle normals.
bool arePerTriangleNormalsEnabled () const
Returns whether per triangle normals are enabled.
bool reservePerTriangleNormalIndexes ()
Reserves memory to store per-triangle triplets of normal indexes.
void addTriangleNormalIndexes (int i1, int i2, int i3)
Adds a triplet of normal indexes for next triangle.
void setTriangleNormalIndexes (unsigned triangleIndex, int i1, int i2, int i3)
Sets a triplet of normal indexes for a given triangle.
void removePerTriangleNormalIndexes ()
Removes any per-triangle triplets of normal indexes.
void invertPerTriangleNormals ()
Invert per-triangle normals.
bool hasMaterials () const override
const ccMaterialSet * getMaterialSet () const override
int getTriangleMtlIndex (unsigned triangleIndex) const override
Returns a given triangle material indexes.
bool convertMaterialsToVertexColors ()
Converts materials to vertex colors.
bool hasPerTriangleMtlIndexes () const
Returns whether this mesh as per-triangle material index.
bool reservePerTriangleMtlIndexes ()
Reserves memory to store per-triangle material index.
void removePerTriangleMtlIndexes ()
Removes any per-triangle material indexes.
void addTriangleMtlIndex (int mtlIndex)
Adds triangle material index for next triangle.
void setTriangleMtlIndexesTable (triangleMaterialIndexesSet *matIndexesTable, bool autoReleaseOldTable=true)
Sets per-triangle material indexes array.
const triangleMaterialIndexesSet * getTriangleMtlIndexesTable () const
Returns the per-triangle material indexes array.
void setTriangleMtlIndex (unsigned triangleIndex, int mtlIndex)
Sets triangle material indexes.
void setMaterialSet (ccMaterialSet *materialSet, bool autoReleaseOldMaterialSet=true)
Sets associated material set (may be shared)
bool hasTextures () const override
Returns whether textures are available for this mesh.
TextureCoordsContainer * getTexCoordinatesTable () const override
Returns per-triangle texture coordinates array.
void getTriangleTexCoordinates (unsigned triIndex, TexCoords2D *&tx1, TexCoords2D *&tx2, TexCoords2D *&tx3) const override
Returns per-triangle texture coordinates (pointer to)
void getTexCoordinates (unsigned index, TexCoords2D *&tx) const override
bool hasPerTriangleTexCoordIndexes () const override
Returns whether this mesh as per-triangle triplets of tex coords indexes.
void getTriangleTexCoordinatesIndexes (unsigned triangleIndex, int &i1, int &i2, int &i3) const override
Returns the triplet of tex coords indexes for a given triangle.
void setTexCoordinatesTable (TextureCoordsContainer *texCoordsTable, bool autoReleaseOldTable=true)
Sets per-triangle texture coordinates array (may be shared)
bool reservePerTriangleTexCoordIndexes ()
Reserves memory to store per-triangle triplets of tex coords indexes.
void removePerTriangleTexCoordIndexes ()
Remove per-triangle tex coords indexes.
void addTriangleTexCoordIndexes (int i1, int i2, int i3)
Adds a triplet of tex coords indexes for next triangle.
void setTriangleTexCoordIndexes (unsigned triangleIndex, int i1, int i2, int i3)
Sets a triplet of tex coords indexes for a given triangle.
bool computeNormals (bool perVertex)
Computes normals.
bool computePerVertexNormals ()
Computes per-vertex normals.
bool computePerTriangleNormals ()
Computes per-triangle normals.
bool laplacianSmooth (unsigned nbIteration=100, PointCoordinateType factor=static_cast< PointCoordinateType >(0.01), ecvProgressDialog *progressCb=nullptr)
Laplacian smoothing.
bool processScalarField (MESH_SCALAR_FIELD_PROCESS process)
ccMesh * subdivide (PointCoordinateType maxArea) const
ccMesh * createNewMeshFromSelection (bool removeSelectedTriangles, std::vector< int > *newIndexesOfRemainingTriangles=nullptr, bool withChildEntities=false)
Creates a new mesh with the selected vertices only.
void swapTriangles (unsigned index1, unsigned index2)
Swaps two triangles.
void removeTriangles (size_t index)
void transformTriNormals (const ccGLMatrix &trans)
Transforms the mesh per-triangle normals.
bool mergeDuplicatedVertices (unsigned char octreeLevel=DefaultMergeDulicateVerticesLevel, QWidget *parentWidget=nullptr)
Merges duplicated vertices.
bool hasAdjacencyList () const
Returns true if the mesh contains adjacency normals.
bool hasTriangleUvs () const
bool hasTriangleMaterialIds () const
bool hasEigenTextures () const
Returns true if the mesh has texture.
virtual bool IsEmpty () const override
virtual Eigen::Vector3d GetMinBound () const override
Returns min bounds for geometry coordinates.
virtual Eigen::Vector3d GetMaxBound () const override
Returns max bounds for geometry coordinates.
virtual Eigen::Vector3d GetCenter () const override
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const override
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const override
virtual ccMesh & Transform (const Eigen::Matrix4d &transformation) override
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual ccMesh & Translate (const Eigen::Vector3d &translation, bool relative=true) override
Apply translation to the geometry coordinates.
virtual ccMesh & Scale (const double s, const Eigen::Vector3d &center) override
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual ccMesh & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center) override
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
ccMesh & PaintUniformColor (const Eigen::Vector3d &color)
Assigns each vertex in the ccMesh the same color.
std::tuple< std::shared_ptr< ccMesh >, std::vector< size_t > > ComputeConvexHull () const
std::unordered_map< Eigen::Vector2i, double, cloudViewer::utility::hash_eigen< Eigen::Vector2i > > ComputeEdgeWeightsCot (const std::unordered_map< Eigen::Vector2i, std::vector< int >, cloudViewer::utility::hash_eigen< Eigen::Vector2i >> &edges_to_vertices, double min_weight=std::numeric_limits< double >::lowest()) const
Function that computes for each edge in the triangle mesh and passed as parameter edges_to_vertices the cot weight.
ccMesh & ComputeTriangleNormals (bool normalized=true)
Function to compute triangle normals, usually called before rendering.
ccMesh & ComputeVertexNormals (bool normalized=true)
Function to compute vertex normals, usually called before rendering.
ccMesh & NormalizeNormals ()
ccMesh & ComputeAdjacencyList ()
Function to compute adjacency list, call before adjacency list is.
ccMesh & RemoveDuplicatedVertices ()
Function that removes duplicated verties, i.e., vertices that have identical coordinates.
ccMesh & RemoveDuplicatedTriangles ()
Function that removes duplicated triangles, i.e., removes triangles that reference the same three vertices, independent of their order.
ccMesh & RemoveUnreferencedVertices ()
This function removes vertices from the triangle mesh that are not referenced in any triangle of the mesh.
ccMesh & RemoveDegenerateTriangles ()
Function that removes degenerate triangles, i.e., triangles that reference a single vertex multiple times in a single triangle.
ccMesh & RemoveNonManifoldEdges ()
Function that removes all non-manifold edges, by successively deleting triangles with the smallest surface area adjacent to the non-manifold edge until the number of adjacent triangles to the edge is <= 2.
ccMesh & MergeCloseVertices (double eps)
Function that will merge close by vertices to a single one. The vertex position, normal and color will be the average of the vertices.
std::shared_ptr< ccMesh > FilterSharpen (int number_of_iterations, double strength, FilterScope scope=FilterScope::All) const
Function to sharpen triangle mesh.
std::shared_ptr< ccMesh > FilterSmoothSimple (int number_of_iterations, FilterScope scope=FilterScope::All) const
Function to smooth triangle mesh with simple neighbour average.
std::shared_ptr< ccMesh > FilterSmoothLaplacian (int number_of_iterations, double lambda, FilterScope scope=FilterScope::All) const
Function to smooth triangle mesh using Laplacian.
std::shared_ptr< ccMesh > FilterSmoothTaubin (int number_of_iterations, double lambda=0.5, double mu=-0.53, FilterScope scope=FilterScope::All) const
Function to smooth triangle mesh using method of Taubin, "Curve and Surface Smoothing Without Shrinkage", 1995. Applies in each iteration two times FilterSmoothLaplacian, first with lambda and second with mu as smoothing parameter. This method avoids shrinkage of the triangle mesh.
int EulerPoincareCharacteristic () const
std::vector< Eigen::Vector2i > GetNonManifoldEdges (bool allow_boundary_edges=true) const
bool IsEdgeManifold (bool allow_boundary_edges=true) const
std::vector< int > GetNonManifoldVertices () const
bool IsVertexManifold () const
std::vector< Eigen::Vector2i > GetSelfIntersectingTriangles () const
bool IsSelfIntersecting () const
bool IsBoundingBoxIntersecting (const ccMesh &other) const
bool IsIntersecting (const ccMesh &other) const
bool IsOrientable () const
bool IsWatertight () const
bool OrientTriangles ()
std::unordered_map< Eigen::Vector2i, std::vector< int >, cloudViewer::utility::hash_eigen< Eigen::Vector2i > > GetEdgeToTrianglesMap () const
std::unordered_map< Eigen::Vector2i, std::vector< int >, cloudViewer::utility::hash_eigen< Eigen::Vector2i > > GetEdgeToVerticesMap () const
double GetTriangleArea (size_t triangle_idx) const
double GetSurfaceArea () const
double GetSurfaceArea (std::vector< double > &triangle_areas) const
double GetVolume () const
Eigen::Vector4d GetTrianglePlane (size_t triangle_idx) const
std::shared_ptr< ccPointCloud > SamplePointsUniformlyImpl (size_t number_of_points, std::vector< double > &triangle_areas, double surface_area, bool use_triangle_normal, int seed)
std::shared_ptr< ccPointCloud > SamplePointsUniformly (size_t number_of_points, bool use_triangle_normal=false, int seed=-1)
std::shared_ptr< ccPointCloud > SamplePointsPoissonDisk (size_t number_of_points, double init_factor=5, const std::shared_ptr< ccPointCloud > pcl_init=nullptr, bool use_triangle_normal=false, int seed=-1)
std::shared_ptr< ccMesh > SubdivideMidpoint (int number_of_iterations) const
std::shared_ptr< ccMesh > SubdivideLoop (int number_of_iterations) const
std::shared_ptr< ccMesh > SimplifyVertexClustering (double voxel_size, SimplificationContraction contraction=SimplificationContraction::Average) const
std::shared_ptr< ccMesh > SimplifyQuadricDecimation (int target_number_of_triangles, double maximum_error=std::numeric_limits< double >::infinity(), double boundary_weight=1.0) const
std::shared_ptr< ccMesh > SelectByIndex (const std::vector< size_t > &indices, bool cleanup=true) const
std::shared_ptr< ccMesh > Crop (const ccBBox &bbox) const
std::shared_ptr< ccMesh > Crop (const ecvOrientedBBox &bbox) const
std::tuple< std::vector< int >, std::vector< size_t >, std::vector< double > > ClusterConnectedTriangles () const
Function that clusters connected triangles, i.e., triangles that are connected via edges are assigned the same cluster index.
void RemoveTrianglesByIndex (const std::vector< size_t > &triangle_indices)
This function removes the triangles with index in triangle_indices. Call RemoveUnreferencedVertices to clean up vertices afterwards.
void RemoveTrianglesByMask (const std::vector< bool > &triangle_mask)
This function removes the triangles that are masked in triangle_mask. Call RemoveUnreferencedVertices to clean up vertices afterwards.
void RemoveVerticesByIndex (const std::vector< size_t > &vertex_indices)
This function removes the vertices with index in vertex_indices. Note that also all triangles associated with the vertices are removeds.
void RemoveVerticesByMask (const std::vector< bool > &vertex_mask)
This function removes the vertices that are masked in vertex_mask. Note that also all triangles associated with the vertices are removed..
std::shared_ptr< ccMesh > DeformAsRigidAsPossible (const std::vector< int > &constraint_vertex_indices, const std::vector< Eigen::Vector3d > &constraint_vertex_positions, size_t max_iter, DeformAsRigidAsPossibleEnergy energy=DeformAsRigidAsPossibleEnergy::Spokes, double smoothed_alpha=0.01) const
This function deforms the mesh using the method by Sorkine and Alexa, "As-Rigid-As-Possible Surface Modeling", 2007.
Public Member Functions inherited from ccGenericMesh
ccGenericMesh (QString name=QString())
Default constructor.
~ccGenericMesh () override=default
Destructor.
void showNormals (bool state) override
Sets normals visibility.
virtual bool isShownAsWire () const
Returns whether the mesh is displayed as wired or with plain facets.
virtual void showWired (bool state)
Sets whether mesh should be displayed as a wire or with plain facets.
virtual bool isShownAsPoints () const
Returns whether the mesh is displayed as wired or with plain facets.
virtual void showPoints (bool state)
virtual bool triNormsShown () const
Returns whether per-triangle normals are shown or not.
virtual void showTriNorms (bool state)
Sets whether to show or not per-triangle normals.
virtual bool materialsShown () const
Sets whether textures/material should be displayed or not.
virtual void showMaterials (bool state)
Sets whether textures should be displayed or not.
virtual bool stipplingEnabled () const
Returns whether polygon stippling is enabled or not.
void enableStippling (bool state)
Enables polygon stippling.
ccPointCloud * samplePoints (bool densityBased, double samplingParameter, bool withNormals, bool withRGB, bool withTexture, cloudViewer::GenericProgressCallback *pDlg=nullptr)
Samples points on a mesh.
void importParametersFrom (const ccGenericMesh *mesh)
Imports the parameters from another mesh.
virtual bool trianglePicking (const CCVector2d &clickPos, const ccGLCameraParameters &camera, int &nearestTriIndex, double &nearestSquareDist, CCVector3d &nearestPoint, CCVector3d *barycentricCoords=nullptr) const
Brute force triangle picking.
virtual bool trianglePicking (unsigned triIndex, const CCVector2d &clickPos, const ccGLCameraParameters &camera, CCVector3d &point, CCVector3d *barycentricCoords=nullptr) const
Triangle picking (single triangle)
bool computePointPosition (unsigned triIndex, const CCVector2d &uv, CCVector3 &P, bool warningIfOutside=true) const
void setGlobalShift (const CCVector3d &shift) override
Sets shift applied to original coordinates (information storage only)
void setGlobalScale (double scale) override
const CCVector3d & getGlobalShift () const override
Returns the shift applied to original coordinates.
double getGlobalScale () const override
Returns the scale applied to original coordinates.
bool updateTextures (const std::string &texture_file)
bool updateTextures (const std::vector< std::string > &texture_files)
Public Member Functions inherited from cloudViewer::GenericIndexedMesh
GenericIndexedMesh ()=default
~GenericIndexedMesh () override=default
Default destructor.
Public Member Functions inherited from cloudViewer::GenericMesh
GenericMesh ()=default
virtual ~GenericMesh ()=default
Default destructor.
virtual bool hasTriangles () const
Public Member Functions inherited from ccShiftedObject
ccShiftedObject (QString name=QString())
Default constructor.
ccShiftedObject (const ccShiftedObject &s)
Copy constructor.
void copyGlobalShiftAndScale (const ccShiftedObject &s)
Copies the Global Shift and Scale from another entity.
virtual void setGlobalShift (double x, double y, double z)
Sets shift applied to original coordinates (information storage only)
bool isShifted () const
Returns whether the cloud is shifted or not.
template<typename T >
CCVector3d toGlobal3d (const Vector3Tpl< T > &Plocal) const
Returns the point back-projected into the original coordinates system.
template<typename T >
CCVector3d toLocal3d (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
template<typename T >
CCVector3 toLocal3pc (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner) override
GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false) override
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual Eigen::Vector2d GetMin2DBound () const
virtual Eigen::Vector2d GetMax2DBound () const
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual ccBBox getOwnFitBB (ccGLMatrix &trans)
Returns best-fit bounding-box (if available)
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col)
Draws the entity (and its children) bounding-box.
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
virtual void notifyGeometryUpdate ()
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual void getDrawingParameters (glDrawParams &params) const
Returns main OpenGL parameters for this entity.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual void toggleNormals ()
Toggles normals display state.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Static Public Member Functions
static cloudViewer::VerticesIndexes GetOrderedTriangle (int vidx0, int vidx1, int vidx2)
static ccMesh * Triangulate (ccGenericPointCloud *cloud, cloudViewer::TRIANGULATION_TYPES type, bool updateNormals=false, PointCoordinateType maxEdgeLength=0, unsigned char dim=2)
Creates a Delaunay 2.5D mesh from a point cloud.
static ccMesh * TriangulateTwoPolylines (ccPolyline *p1, ccPolyline *p2, CCVector3 *projectionDir=nullptr)
Creates a Delaunay 2.5D mesh from two polylines.
static double ComputeTriangleArea (const Eigen::Vector3d &p0, const Eigen::Vector3d &p1, const Eigen::Vector3d &p2)
Function that computes the area of a mesh triangle.
static Eigen::Vector3i GetEigneOrderedTriangle (int vidx0, int vidx1, int vidx2)
static Eigen::Vector4d ComputeTrianglePlane (const Eigen::Vector3d &p0, const Eigen::Vector3d &p1, const Eigen::Vector3d &p2)
static Eigen::Vector2i GetOrderedEdge (int vidx0, int vidx1)
Helper function to get an edge with ordered vertex indices.
static std::shared_ptr< ccMesh > CreateFromPointCloudAlphaShape (const ccPointCloud &pcd, double alpha, std::shared_ptr< cloudViewer::geometry::TetraMesh > tetra_mesh=nullptr, std::vector< size_t > *pt_map=nullptr)
Alpha shapes are a generalization of the convex hull. With decreasing alpha value the shape schrinks and creates cavities. See Edelsbrunner and Muecke, "Three-Dimensional Alpha Shapes", 1994.
static std::shared_ptr< ccMesh > CreateFromPointCloudBallPivoting (const ccPointCloud &pcd, const std::vector< double > &radii)
static std::tuple< std::shared_ptr< ccMesh >, std::vector< double > > CreateFromPointCloudPoisson (const ccPointCloud &pcd, size_t depth=8, size_t width=0, float scale=1.1f, bool linear_fit=false, float point_weight=2.f, float samples_per_node=1.5f, int boundary_type=2, int n_threads=-1)
Function that computes a triangle mesh from a oriented PointCloud pcd. This implements the Screened Poisson Reconstruction proposed in Kazhdan and Hoppe, "Screened Poisson Surface Reconstruction", 2013. This function uses the original implementation by Kazhdan. See https://github.com/mkazhdan/PoissonRecon.
static std::shared_ptr< ccMesh > CreateTetrahedron (double radius=1.0, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreateOctahedron (double radius=1.0, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreateIcosahedron (double radius=1.0, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreatePlane (double width=1.0, double height=1.0, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreateBox (double width=1.0, double height=1.0, double depth=1.0, bool create_uv_map=false, bool map_texture_to_each_face=false)
static std::shared_ptr< ccMesh > CreateSphere (double radius=1.0, int resolution=20, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreateCylinder (double radius=1.0, double height=2.0, int resolution=20, int split=4, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreateCone (double radius=1.0, double height=2.0, int resolution=20, int split=1, bool create_uv_map=false)
static std::shared_ptr< ccMesh > CreateTorus (double torus_radius=1.0, double tube_radius=0.5, int radial_resolution=30, int tubular_resolution=20)
static std::shared_ptr< ccMesh > CreateArrow (double cylinder_radius=1.0, double cone_radius=1.5, double cylinder_height=5.0, double cone_height=4.0, int resolution=20, int cylinder_split=4, int cone_split=1)
static std::shared_ptr< ccMesh > CreateCoordinateFrame (double size=1.0, const Eigen::Vector3d &origin=Eigen::Vector3d(0.0, 0.0, 0.0))
static std::shared_ptr< ccMesh > CreateMobius (int length_split=70, int width_split=15, int twists=1, double radius=1, double flatness=1, double width=1, double scale=1)
Static Public Member Functions inherited from ccGenericMesh
static bool IsCloudVerticesOfMesh (ccGenericPointCloud *cloud, ccGenericMesh **mesh=nullptr)
Helper to determine if the input cloud acts as vertices of a mesh.
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Public Attributes
std::vector< std::unordered_set< int > > adjacency_list_
std::vector< Eigen::Vector2d > triangle_uvs_
List of uv coordinates per triangle.
std::vector< std::pair< std::string, Material > > materials_
std::vector< int > triangle_material_ids_
List of material ids.
std::vector< cloudViewer::geometry::Image > textures_
Textures of the image.
Static Public Attributes
static const unsigned char DefaultMergeDulicateVerticesLevel = 10
Default octree level for the 'mergeDuplicatedVertices' algorithm.
Protected Types
using triangleTexCoordIndexesSet = ccArray< Tuple3i, 3, int >
Set of triplets of indexes referring to mesh texture coordinates.
using triangleNormalsIndexesSet = ccArray< Tuple3i, 3, int >
Set of triplets of indexes referring to mesh normals.
Protected Member Functions
void FilterSmoothLaplacianHelper (std::shared_ptr< ccMesh > &mesh, const std::vector< CCVector3 > &prev_vertices, const std::vector< CCVector3 > &prev_vertex_normals, const ColorsTableType &prev_vertex_colors, const std::vector< std::unordered_set< int >> &adjacency_list, double lambda, bool filter_vertex, bool filter_normal, bool filter_color) const
void drawMeOnly (CC_DRAW_CONTEXT &context) override
Enables (OpenGL) stipple mask.
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
void applyGLTransformation (const ccGLMatrix &trans) override
Applies a GL transformation to the entity.
void onUpdateOf (ccHObject *obj) override
This method is called when another object (geometry) is updated.
void onDeletionOf (const ccHObject *obj) override
This method is called when another object is deleted.
void computeInterpolationWeights (const cloudViewer::VerticesIndexes &vertIndexes, const CCVector3 &P, CCVector3d &weights) const
bool interpolateNormals (const cloudViewer::VerticesIndexes &vertIndexes, const CCVector3d &w, CCVector3 &N, const Tuple3i *triNormIndexes=nullptr)
bool interpolateColors (const cloudViewer::VerticesIndexes &vertIndexes, const CCVector3 &P, ecvColor::Rgb &C)
bool pushSubdivide (unsigned indexA, unsigned indexB, unsigned indexC)
Used internally by 'subdivide'.
virtual void showNormals_extended (bool p)
Protected Member Functions inherited from ccGenericMesh
virtual bool trianglePicking (unsigned triIndex, const CCVector2d &clickPos, const ccGLMatrix &trans, bool noGLTrans, const ccGenericPointCloud &vertices, const ccGLCameraParameters &camera, CCVector3d &point, CCVector3d *barycentricCoords=nullptr) const
Triangle picking (single triangle)
void handleColorRamp (CC_DRAW_CONTEXT &context)
Handles the color ramp display.
Protected Member Functions inherited from ccShiftedObject
bool saveShiftInfoToFile (QFile &out) const
Serialization helper (output)
bool loadShiftInfoFromFile (QFile &in)
Serialization helper (input)
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void drawNameIn3D ()
Draws the entity name in 3D.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Protected Attributes
ccGenericPointCloud * m_associatedCloud
associated cloud (vertices)
NormsIndexesTableType * m_triNormals
Per-triangle normals.
TextureCoordsContainer * m_texCoords
Texture coordinates.
ccMaterialSet * m_materials
Materials.
triangleIndexesContainer * m_triVertIndexes
Triangles' vertices indexes (3 per triangle)
unsigned m_globalIterator
Iterator on the list of triangles.
cloudViewer::SimpleRefTriangle m_currentTriangle
Dump triangle structure to transmit temporary data.
ccBBox m_bBox
Bounding-box.
triangleMaterialIndexesSet * m_triMtlIndexes
Per-triangle material indexes.
triangleTexCoordIndexesSet * m_texCoordIndexes
Mesh tex coords indexes (per-triangle)
triangleNormalsIndexesSet * m_triNormalIndexes
Mesh normals indexes (per-triangle)
Protected Attributes inherited from ccGenericMesh
bool m_triNormsShown
Per-triangle normals display flag.
bool m_materialsShown
Texture/material display flag.
bool m_showWired
Wireframe display mode.
bool m_showPoints
points display mode
bool m_stippling
Polygon stippling state.
Protected Attributes inherited from ccShiftedObject
CCVector3d m_globalShift
Global shift (typically applied at loading time)
double m_globalScale
Global scale (typically applied at loading time)
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Additional Inherited Members
Static Protected Member Functions inherited from ccGenericMesh
static CCVector3 * GetVertexBuffer ()
static CCVector3 * GetNormalsBuffer ()
static ecvColor::Rgb * GetColorsBuffer ()
static unsigned * GetWireVertexIndexes ()
Returns a pre-initialized array of vertex indexes for wired display.
Detailed Description
Triangular mesh.
Definition at line 35 of file ecvMesh.h.
Member Typedef Documentation
triangleIndexesContainer
using ccMesh::triangleIndexesContainer = ccArray<cloudViewer::VerticesIndexes, 3, unsigned>
Container of per-triangle vertices indexes (3)
Definition at line 277 of file ecvMesh.h.
triangleMaterialIndexesSet
using ccMesh::triangleMaterialIndexesSet = ccArray<int, 1, int>
Container of per-triangle material descriptors.
Definition at line 447 of file ecvMesh.h.
triangleNormalsIndexesSet
using ccMesh::triangleNormalsIndexesSet = ccArray<Tuple3i, 3, int> protected
Set of triplets of indexes referring to mesh normals.
Definition at line 1521 of file ecvMesh.h.
triangleTexCoordIndexesSet
using ccMesh::triangleTexCoordIndexesSet = ccArray<Tuple3i, 3, int> protected
Set of triplets of indexes referring to mesh texture coordinates.
Definition at line 1516 of file ecvMesh.h.
Member Enumeration Documentation
MESH_SCALAR_FIELD_PROCESS
enum ccMesh::MESH_SCALAR_FIELD_PROCESS
Mesh scalar field processes.
Enumerator
SMOOTH_MESH_SF
Smooth
ENHANCE_MESH_SF
Enhance
Definition at line 554 of file ecvMesh.h.
Constructor & Destructor Documentation
ccMesh() [1/4]
ccMesh::ccMesh (ccGenericPointCloud * vertices = nullptr) explicit
Default ccMesh constructor.
Parameters
vertices the vertices cloud
Definition at line 42 of file ecvMesh.cpp.
References CCShareable::link(), m_triVertIndexes, and setAssociatedCloud().
Referenced by cloneMesh(), createNewMeshFromSelection(), operator+(), partialClone(), subdivide(), Triangulate(), and TriangulateTwoPolylines().
ccMesh() [2/4]
ccMesh::ccMesh (const ccMesh & mesh)
Definition at line 59 of file ecvMesh.cpp.
References ccHObject::addChild(), ccHObject::getChildrenNumber(), m_associatedCloud, ccObject::setEnabled(), and ccObject::setLocked().
ccMesh() [3/4]
ccMesh::ccMesh (const std::vector< Eigen::Vector3d > & vertices, const std::vector< Eigen::Vector3i > & triangles) explicit
Parameterized Constructor.
Parameters
vertices list of vertices.
triangles list of triangles.
Definition at line 70 of file ecvMesh.cpp.
References ccHObject::addChild(), m_associatedCloud, ccPointCloud::resize(), setEigenVertices(), ccObject::setEnabled(), ccObject::setLocked(), setTriangles(), and ccHObjectCaster::ToPointCloud().
ccMesh() [4/4]
ccMesh::ccMesh (cloudViewer::GenericIndexedMesh * giMesh, ccGenericPointCloud * giVertices) explicit
ccMesh constructor (from a cloudViewer::GenericIndexedMesh)
The GenericIndexedMesh should refer to a known ccGenericPointCloud.
Parameters
giMesh the GenericIndexedMesh
giVertices giMesh vertices
Definition at line 86 of file ecvMesh.cpp.
References addTriangle(), ccDrawableObject::colorsShown(), cloudViewer::GenericIndexedMesh::getNextTriangleVertIndexes(), ccDrawableObject::hasColors(), ccDrawableObject::hasDisplayedScalarField(), ccDrawableObject::hasNormals(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, CCShareable::link(), m_triVertIndexes, cloudViewer::GenericMesh::placeIteratorAtBeginning(), reserve(), setAssociatedCloud(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccGenericMesh::showNormals(), ccDrawableObject::showSF(), and cloudViewer::GenericMesh::size().
~ccMesh()
ccMesh::~ccMesh () override
Default destructor.
Definition at line 122 of file ecvMesh.cpp.
References clearTriNormals(), m_texCoordIndexes, m_triMtlIndexes, m_triNormalIndexes, m_triVertIndexes, CCShareable::release(), setMaterialSet(), and setTexCoordinatesTable().
Member Function Documentation
_getNextTriangle()
cloudViewer::GenericTriangle * ccMesh::_getNextTriangle () override virtual
Returns the next triangle (relatively to the global iterator position)
Virtual method to handle the mesh global iterator. Global iterator position should be increased each time this method is called. The returned object can be temporary.
Returns
a triangle
Implements cloudViewer::GenericMesh.
Definition at line 2165 of file ecvMesh.cpp.
References _getTriangle(), m_globalIterator, and size().
Referenced by qVoxFallProcess::Compute().
_getTriangle()
cloudViewer::GenericTriangle * ccMesh::_getTriangle (unsigned triangleIndex) override virtual
Returns the ith triangle.
Virtual method to request a triangle with a specific index. The returned object can be temporary.
Parameters
triangleIndex of the requested triangle (between 0 and the mesh size-1)
Returns
the requested triangle, or 0 if index value is not valid
Implements cloudViewer::GenericIndexedMesh.
Definition at line 2173 of file ecvMesh.cpp.
References cloudViewer::SimpleRefTriangle::A, cloudViewer::SimpleRefTriangle::B, cloudViewer::SimpleRefTriangle::C, cloudViewer::GenericIndexedCloud::getPoint(), ccArray< Type, N, ComponentType >::getValue(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, m_associatedCloud, m_currentTriangle, m_triVertIndexes, and size().
Referenced by _getNextTriangle(), ccSubMesh::_getNextTriangle(), ccSubMesh::_getTriangle(), ccSubMesh::forEach(), and ccSubMesh::refreshBB().
addEigenVertices()
void ccMesh::addEigenVertices (const std::vector< Eigen::Vector3d > & vertices)
Definition at line 2377 of file ecvMesh.cpp.
References cloudViewer::PointCloudTpl< T >::addPoints(), m_associatedCloud, ccPointCloud::reserveThePointsTable(), cloudViewer::PointCloudTpl< T >::size(), and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::t::geometry::TriangleMesh::ToLegacy().
addTriangle() [1/3]
void ccMesh::addTriangle (const cloudViewer::VerticesIndexes & triangle)
Definition at line 2432 of file ecvMesh.cpp.
References m_triVertIndexes.
addTriangle() [2/3]
void ccMesh::addTriangle (const Eigen::Vector3i & index) inline
Definition at line 260 of file ecvMesh.h.
addTriangle() [3/3]
void ccMesh::addTriangle (unsigned i1, unsigned i2, unsigned i3)
Adds a triangle to the mesh.
Warning
Bounding-box validity is broken after a call to this method. However, for the sake of performance, no call to notifyGeometryUpdate is made automatically. Make sure to do so when all modifications are done!
Parameters
i1 first vertex index (relatively to the vertex cloud)
i2 second vertex index (relatively to the vertex cloud)
i3 third vertex index (relatively to the vertex cloud)
Definition at line 2428 of file ecvMesh.cpp.
References m_triVertIndexes.
Referenced by MeshWrapper< Real >::addTriangle(), cloudViewer::io::AddTrianglesByEarClipping(), ccCone::buildUp(), ccDisc::buildUp(), ccDish::buildUp(), ccExtru::buildUp(), ccPlane::buildUp(), ccQuadric::buildUp(), ccSphere::buildUp(), ccTorus::buildUp(), ccMesh(), cloneMesh(), pcl2cc::Convert(), DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertProfileToMesh(), vtk2cc::ConvertToMesh(), define_ccMesh(), face_cb(), FromFbxMesh(), STEPFilter::importStepFile(), STLFilter::loadASCIIFile(), STLFilter::loadBinaryFile(), CSVMatrixFilter::loadFile(), ObjFilter::loadFile(), OFFFilter::loadFile(), VTKFilter::loadFile(), DRCFilter::loadFile(), merge(), ccGenericPrimitive::operator+=(), partialClone(), pushSubdivide(), cloudViewer::io::ReadTriangleMeshFromGLTF(), cloudViewer::io::ReadTriangleMeshFromOBJ(), cloudViewer::io::ReadTriangleMeshUsingASSIMP(), cloudViewer::t::geometry::TriangleMesh::ToLegacy(), Cloth::toMesh(), ccPointCloud::triangulateGrid(), and GrainsAsEllipsoids::updateMeshAndLineSet().
addTriangleMtlIndex()
void ccMesh::addTriangleMtlIndex (int mtlIndex)
Adds triangle material index for next triangle.
Cf. ccMesh::reservePerTriangleMtlIndexes.
Parameters
mtlIndex triangle material index
Definition at line 3751 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::isAllocated(), and m_triMtlIndexes.
Referenced by DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertProfileToMesh(), createNewMeshFromSelection(), ccCropTool::Crop(), FromFbxMesh(), CSVMatrixFilter::loadFile(), ObjFilter::loadFile(), PlyFilter::loadFile(), partialClone(), and ccPlane::SetQuadTexture().
addTriangleNorm() [1/2]
bool ccMesh::addTriangleNorm (const CCVector3 & N)
Definition at line 3513 of file ecvMesh.cpp.
References addTriangleNormalIndexes(), arePerTriangleNormalsEnabled(), ccNormalVectors::GetNormIndex(), m_triNormals, CCShareable::release(), reservePerTriangleNormalIndexes(), setTriNormsTable(), Tuple3Tpl< Type >::u, and CVLog::Warning().
Referenced by addTriangleNorm(), and addTriangleNorms().
addTriangleNorm() [2/2]
bool ccMesh::addTriangleNorm (const Eigen::Vector3d & N)
Definition at line 3531 of file ecvMesh.cpp.
References addTriangleNorm(), and Vector3Tpl< PointCoordinateType >::fromArray().
addTriangleNormalIndexes()
void ccMesh::addTriangleNormalIndexes (int i1, int i2, int i3)
Adds a triplet of normal indexes for next triangle.
Make sure per-triangle normal indexes array is allocated (see reservePerTriangleNormalIndexes)
Parameters
i1 first vertex normal index
i2 second vertex normal index
i3 third vertex normal index
Definition at line 3340 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::isAllocated(), and m_triNormalIndexes.
Referenced by addTriangleNorm(), ccCone::buildUp(), ccDisc::buildUp(), ccExtru::buildUp(), ccPlane::buildUp(), ccTorus::buildUp(), computePerTriangleNormals(), createNewMeshFromSelection(), FromFbxMesh(), STLFilter::loadASCIIFile(), STLFilter::loadBinaryFile(), ObjFilter::loadFile(), VTKFilter::loadFile(), ccGenericPrimitive::operator+=(), and partialClone().
addTriangleNorms()
bool ccMesh::addTriangleNorms (const std::vector< Eigen::Vector3d > & triangle_normals)
Definition at line 3571 of file ecvMesh.cpp.
References addTriangleNorm(), LogWarning, normal, reserve(), and size().
addTriangles()
void ccMesh::addTriangles (const std::vector< Eigen::Vector3i > & triangles) inline
Definition at line 265 of file ecvMesh.h.
Referenced by define_ccMesh().
addTriangleTexCoordIndexes()
void ccMesh::addTriangleTexCoordIndexes (int i1, int i2, int i3)
Adds a triplet of tex coords indexes for next triangle.
Make sure per-triangle tex coords indexes array is allocated (see reservePerTriangleTexCoordIndexes)
Parameters
i1 first vertex tex coords index
i2 second vertex tex coords index
i3 third vertex tex coords index
Definition at line 3678 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::isAllocated(), and m_texCoordIndexes.
Referenced by DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertProfileToMesh(), createNewMeshFromSelection(), ccCropTool::Crop(), FromFbxMesh(), CSVMatrixFilter::loadFile(), ObjFilter::loadFile(), PlyFilter::loadFile(), partialClone(), and ccPlane::SetQuadTexture().
addVertexColor()
void ccMesh::addVertexColor (const Eigen::Vector3d & color)
Definition at line 2289 of file ecvMesh.cpp.
References ccPointCloud::addEigenColor(), color, m_associatedCloud, and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::io::ReadTriangleMeshUsingASSIMP().
addVertexColors()
void ccMesh::addVertexColors (const std::vector< Eigen::Vector3d > & colors)
Definition at line 2327 of file ecvMesh.cpp.
References ccPointCloud::addEigenColors(), colors, m_associatedCloud, ccPointCloud::reserveTheRGBTable(), and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::t::geometry::TriangleMesh::ToLegacy().
addVertexNormal()
void ccMesh::addVertexNormal (const Eigen::Vector3d & normal)
Definition at line 2244 of file ecvMesh.cpp.
References ccPointCloud::addEigenNorm(), m_associatedCloud, normal, and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::io::ReadTriangleMeshUsingASSIMP().
addVertexNormals()
void ccMesh::addVertexNormals (const std::vector< Eigen::Vector3d > & normals)
Definition at line 2273 of file ecvMesh.cpp.
References ccPointCloud::addEigenNorms(), m_associatedCloud, normals, ccPointCloud::reserveTheNormsTable(), and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::t::geometry::TriangleMesh::ToLegacy().
addVertice()
void ccMesh::addVertice (const Eigen::Vector3d & vertice)
Definition at line 2230 of file ecvMesh.cpp.
References cloudViewer::PointCloudTpl< T >::addEigenPoint(), getAssociatedCloud(), and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::io::ReadTriangleMeshUsingASSIMP().
applyGLTransformation()
void ccMesh::applyGLTransformation (const ccGLMatrix & trans) override protected virtual
Applies a GL transformation to the entity.
this = rotMat*(this-rotCenter)+(rotCenter+trans)
Parameters
trans a ccGLMatrix structure
Reimplemented from ccHObject.
Definition at line 514 of file ecvMesh.cpp.
References ccHObject::applyGLTransformation(), and transformTriNormals().
Referenced by ccGenericPrimitive::applyGLTransformation().
arePerTriangleNormalsEnabled()
bool ccMesh::arePerTriangleNormalsEnabled () const
Returns whether per triangle normals are enabled.
To enable per triangle normals, you should:
first, reserve memory for triangles (this is always the first thing to do)
associate this mesh to a triangle normals array (see ccMesh::setTriNormsTable)
reserve memory to store per-triangle normal indexes with ccMesh::reservePerTriangleNormalIndexes
add for each triangle a triplet of indexes (referring to stored normals)
Definition at line 3319 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::isAllocated(), and m_triNormalIndexes.
Referenced by addTriangleNorm().
capacity()
unsigned ccMesh::capacity () const override virtual
Returns max capacity.
Implements ccGenericMesh.
Definition at line 2147 of file ecvMesh.cpp.
References m_triVertIndexes.
Referenced by MeshWrapper< Real >::checkMeshCapacity(), face_cb(), STEPFilter::importStepFile(), STLFilter::loadASCIIFile(), ObjFilter::loadFile(), OFFFilter::loadFile(), VTKFilter::loadFile(), and pushSubdivide().
clear()
void ccMesh::clear ()
Definition at line 2126 of file ecvMesh.cpp.
References adjacency_list_, ccPointCloud::clear(), clearTriNormals(), getAssociatedCloud(), cloudViewer::GenericCloud::hasPoints(), materials_, resize(), textures_, ccHObjectCaster::ToPointCloud(), triangle_material_ids_, and triangle_uvs_.
Referenced by ComputeAdjacencyList(), cloudViewer::io::ReadTriangleMeshFromGLTF(), cloudViewer::io::ReadTriangleMeshFromOBJ(), cloudViewer::io::ReadTriangleMeshFromPLY(), and cloudViewer::io::ReadTriangleMeshUsingASSIMP().
clearTriNormals()
void ccMesh::clearTriNormals () inline
Removes per-triangle normals.
Definition at line 353 of file ecvMesh.h.
Referenced by clear(), ccEntityAction::clearProperty(), CommandClearNormals::process(), and ~ccMesh().
cloneMesh()
ccMesh * ccMesh::cloneMesh (ccGenericPointCloud * vertices = nullptr, ccMaterialSet * clonedMaterials = nullptr, NormsIndexesTableType * clonedNormsTable = nullptr, TextureCoordsContainer * cloneTexCoords = nullptr)
Clones this entity.
All the main features of the entity are cloned, except from the octree
Parameters
vertices vertices set to use (will be automatically - AND OPTIMALLY - cloned if 0)
clonedMaterials for internal use
clonedNormsTable for internal use
cloneTexCoords for internal use
Returns
a copy of this entity
Definition at line 1109 of file ecvMesh.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), addTriangle(), ccMesh(), ccMaterialSet::clone(), NormsIndexesTableType::clone(), TextureCoordsContainer::clone(), ccGenericPointCloud::clone(), ccDrawableObject::colorsShown(), computeNormals(), ccArray< Type, N, ComponentType >::copy(), CVLog::Error(), getMaterialSet(), ccObject::getName(), getNextTriangleVertIndexes(), hasNormals(), hasTriNormals(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, ccGenericMesh::importParametersFrom(), ccObject::isA(), ccObject::isEnabled(), ccDrawableObject::isVisible(), m_associatedCloud, m_materials, m_texCoordIndexes, m_texCoords, m_triMtlIndexes, m_triNormalIndexes, m_triNormals, ccGenericMesh::materialsShown(), normalsShown(), partialClone(), placeIteratorAtBeginning(), CV_TYPES::POINT_CLOUD, removePerTriangleMtlIndexes(), removePerTriangleNormalIndexes(), removePerTriangleTexCoordIndexes(), reserve(), cloudViewer::ReferenceCloud::reserve(), reservePerTriangleMtlIndexes(), reservePerTriangleNormalIndexes(), reservePerTriangleTexCoordIndexes(), ccObject::setEnabled(), setMaterialSet(), ccObject::setName(), setTexCoordinatesTable(), setTriNormsTable(), ccDrawableObject::setVisible(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccGenericMesh::showMaterials(), ccGenericMesh::showNormals(), ccDrawableObject::showSF(), cloudViewer::GenericCloud::size(), cloudViewer::ReferenceCloud::size(), size(), and CVLog::Warning().
Referenced by ccPointCloud::append(), ccFacet::clone(), and qVoxFallProcess::Compute().
ClusterConnectedTriangles()
std::tuple< std::vector< int >, std::vector< size_t >, std::vector< double > > ccMesh::ClusterConnectedTriangles () const
Function that clusters connected triangles, i.e., triangles that are connected via edges are assigned the same cluster index.
Returns
A vector that contains the cluster index per triangle, a second vector contains the number of triangles per cluster, and a third vector contains the surface area per cluster.
Definition at line 1175 of file TriangleMeshFactory.cpp.
References cloudViewer::t::geometry::GetEdgeToTrianglesMap(), cloudViewer::t::geometry::GetOrderedEdge(), LogDebug, and size.
ComputeAdjacencyList()
ccMesh & ccMesh::ComputeAdjacencyList ()
Function to compute adjacency list, call before adjacency list is.
Definition at line 1416 of file TriangleMeshFactory.cpp.
References clear(), and size.
ComputeConvexHull()
std::tuple< std::shared_ptr< ccMesh >, std::vector< size_t > > ccMesh::ComputeConvexHull () const
Definition at line 409 of file TriangleMeshFactory.cpp.
References cloudViewer::geometry::Qhull::ComputeConvexHull().
ComputeEdgeWeightsCot()
std::unordered_map< Eigen::Vector2i, double, utility::hash_eigen< Eigen::Vector2i > > ccMesh::ComputeEdgeWeightsCot (const std::unordered_map< Eigen::Vector2i, std::vector< int >, cloudViewer::utility::hash_eigen< Eigen::Vector2i >> & edges_to_vertices, double min_weight = std::numeric_limits<double>::lowest()) const
Function that computes for each edge in the triangle mesh and passed as parameter edges_to_vertices the cot weight.
Parameters
edges_to_vertices map from edge to vector of neighbouring vertices.
min_weight minimum weight returned. Weights smaller than this get clamped.
Returns
cot weight per edge.
Definition at line 1346 of file TriangleMeshFactory.cpp.
References a.
computeInterpolationWeights() [1/2]
void ccMesh::computeInterpolationWeights (const cloudViewer::VerticesIndexes & vertIndexes, const CCVector3 & P, CCVector3d & weights) const protected
Same as other 'computeInterpolationWeights' method with a set of 3 vertices indexes
Definition at line 4032 of file ecvMesh.cpp.
References cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, m_associatedCloud, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
computeInterpolationWeights() [2/2]
void ccMesh::computeInterpolationWeights (unsigned triIndex, const CCVector3 & P, CCVector3d & weights) const override virtual
Returns the (barycentric) interpolation weights for a given triangle.
Reimplemented from ccGenericMesh.
Definition at line 4023 of file ecvMesh.cpp.
References m_triVertIndexes, and size().
Referenced by getColorFromMaterial(), and interpolateColors().
computeNormals()
bool ccMesh::computeNormals (bool perVertex)
Computes normals.
Parameters
perVertex whether normals should be computed per-vertex or per-triangle
Returns
success
Definition at line 242 of file ecvMesh.cpp.
References computePerTriangleNormals(), and computePerVertexNormals().
Referenced by ccQuadric::buildUp(), cloneMesh(), qPoissonRecon::doAction(), laplacianSmooth(), partialClone(), ecvPoissonReconDlg::start(), subdivide(), and Triangulate().
computePerTriangleNormals()
bool ccMesh::computePerTriangleNormals ()
Computes per-triangle normals.
Definition at line 331 of file ecvMesh.cpp.
References addTriangleNormalIndexes(), ccNormalVectors::GetNormIndex(), cloudViewer::GenericIndexedCloud::getPoint(), ccArray< Type, N, ComponentType >::getValue(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, m_associatedCloud, m_triNormalIndexes, m_triVertIndexes, CCShareable::release(), removePerTriangleNormalIndexes(), reservePerTriangleNormalIndexes(), ccArray< Type, N, ComponentType >::reserveSafe(), setTriNormsTable(), showNormals_extended(), size(), Tuple3Tpl< Type >::u, and CVLog::Warning().
Referenced by computeNormals(), qVoxFallTransform::CreateVoxelMesh(), ccCropTool::Crop(), and STEPFilter::importStepFile().
computePerVertexNormals()
bool ccMesh::computePerVertexNormals ()
Computes per-vertex normals.
normalsWereAllocated &&
Definition at line 246 of file ecvMesh.cpp.
References getNextTriangleVertIndexes(), cloudViewer::PointCloudTpl< T >::getPoint(), ccPointCloud::hasNormals(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, ccObject::isA(), m_associatedCloud, Vector3Tpl< Type >::normalize(), placeIteratorAtBeginning(), CV_TYPES::POINT_CLOUD, ccPointCloud::resize(), s_blankNorm, ccPointCloud::setPointNormal(), ccDrawableObject::showNormals(), showNormals_extended(), cloudViewer::GenericCloud::size(), size(), and CVLog::Warning().
Referenced by computeNormals(), ccCropTool::Crop(), qCSF::doAction(), and CSVMatrixFilter::loadFile().
ComputeTriangleArea()
double ccMesh::ComputeTriangleArea (const Eigen::Vector3d & p0, const Eigen::Vector3d & p1, const Eigen::Vector3d & p2) static
Function that computes the area of a mesh triangle.
Definition at line 1628 of file TriangleMeshFactory.cpp.
References x, and y.
ComputeTriangleNormals()
ccMesh & ccMesh::ComputeTriangleNormals (bool normalized = true)
Function to compute triangle normals, usually called before rendering.
Definition at line 1380 of file TriangleMeshFactory.cpp.
ComputeTrianglePlane()
Eigen::Vector4d ccMesh::ComputeTrianglePlane (const Eigen::Vector3d & p0, const Eigen::Vector3d & p1, const Eigen::Vector3d & p2) static
Function that computes the plane equation from the three points. If the three points are co-linear, then this function returns the invalid plane (0, 0, 0, 0).
Definition at line 1697 of file TriangleMeshFactory.cpp.
Referenced by ccPointCloud::SegmentPlane().
ComputeVertexNormals()
ccMesh & ccMesh::ComputeVertexNormals (bool normalized = true)
Function to compute vertex normals, usually called before rendering.
Definition at line 1388 of file TriangleMeshFactory.cpp.
Referenced by main(), and colmap::mvs::MvsTexturing::TextureMesh().
convertMaterialsToVertexColors()
bool ccMesh::convertMaterialsToVertexColors ()
Converts materials to vertex colors.
Warning: this method will overwrite colors (if any)
Definition at line 4718 of file ecvMesh.cpp.
References getNextTriangleVertIndexes(), getVertexColorFromMaterial(), hasMaterials(), cloudViewer::VerticesIndexes::i, ccObject::isA(), m_associatedCloud, placeIteratorAtBeginning(), CV_TYPES::POINT_CLOUD, ccPointCloud::resizeTheRGBTable(), ccPointCloud::setPointColor(), size(), and CVLog::Warning().
Referenced by ccEntityAction::convertTextureToColor().
CreateArrow()
std::shared_ptr< ccMesh > ccMesh::CreateArrow (double cylinder_radius = 1.0, double cone_radius = 1.5, double cylinder_height = 5.0, double cone_height = 4.0, int resolution = 20, int cylinder_split = 4, int cone_split = 1) static
Factory function to create an arrow mesh (TriangleMeshFactory.cpp) The axis of the cone with cone_radius will be along the z-axis. The cylinder with cylinder_radius is from (0, 0, 0) to (0, 0, cylinder_height), and the cone is from (0, 0, cylinder_height) to (0, 0, cylinder_height + cone_height). The cone will be split into resolution segments. The cylinder_height will be split into cylinder_split segments. The cone_height will be split into cone_split segments.
Parameters
cylinder_radius defines the radius of the cylinder.
cone_radius defines the radius of the cone.
cylinder_height defines the height of the cylinder. The cylinder is from (0, 0, 0) to (0, 0, cylinder_height)
cone_height defines the height of the cone. The axis of the cone will be from (0, 0, cylinder_height) to (0, 0, cylinder_height + cone_height).
resolution defines the cone will be split into resolution segments.
cylinder_split defines the cylinder_height will be split into cylinder_split segments.
cone_split defines the cone_height will be split into cone_split segments.
Definition at line 2766 of file TriangleMeshFactory.cpp.
References LogError.
Referenced by cloudViewer::t::geometry::TriangleMesh::CreateArrow(), and ccFacet::getNormalVectorMesh().
CreateBox()
std::shared_ptr< ccMesh > ccMesh::CreateBox (double width = 1.0, double height = 1.0, double depth = 1.0, bool create_uv_map = false, bool map_texture_to_each_face = false) static
Factory function to create a box mesh (TriangleMeshFactory.cpp) The left bottom corner on the front will be placed at (0, 0, 0).
Parameters
width is x-directional length.
height is y-directional length.
depth is z-directional length.
create_uv_map add default UV map to the shape.
map_texture_to_each_face if true, maps the entire texture image to each face. If false, sets the default uv map to the mesh.
Definition at line 2091 of file TriangleMeshFactory.cpp.
References cloudViewer::PointCloudTpl< T >::getPointPtr(), height, LogError, normals, ccPointCloud::resize(), ccObject::setEnabled(), ccObject::setLocked(), ccPointCloud::shrinkToFit(), and width.
CreateCone()
std::shared_ptr< ccMesh > ccMesh::CreateCone (double radius = 1.0, double height = 2.0, int resolution = 20, int split = 1, bool create_uv_map = false) static
Factory function to create a cone mesh (TriangleMeshFactory.cpp) The axis of the cone will be from (0, 0, 0) to (0, 0, height). The circle with radius will be split into resolution segments. The height will be split into split segments.
Parameters
radius defines the radius of the cone.
height defines the height of the cone.
resolution defines that the circle will be split into resolution segments
split defines that the height will be split into split segments.
create_uv_map add default UV map to the mesh.
Definition at line 2544 of file TriangleMeshFactory.cpp.
References cloudViewer::PointCloudTpl< T >::getPointPtr(), height, LogError, M_PI, cloudViewer::core::make_pair(), normals, ccPointCloud::resize(), cloudViewer::PointCloudTpl< T >::setEigenPoint(), ccObject::setEnabled(), ccObject::setLocked(), and ccPointCloud::shrinkToFit().
Referenced by cloudViewer::t::geometry::TriangleMesh::CreateCone().
CreateCoordinateFrame()
std::shared_ptr< ccMesh > ccMesh::CreateCoordinateFrame (double size = 1.0, const Eigen::Vector3d & origin = Eigen::Vector3d(0.0, 0.0, 0.0)) static
Factory function to create a coordinate frame mesh (TriangleMeshFactory.cpp). arrows respectively.
Parameters
size is the length of the axes.
size defines the size of the coordinate frame.
origin defines the origin of the cooridnate frame.
Definition at line 2808 of file TriangleMeshFactory.cpp.
References LogError, origin, and size.
Referenced by cloudViewer::visualization::Visualizer::BuildUtilities(), cloudViewer::t::geometry::TriangleMesh::CreateCoordinateFrame(), and cloudViewer::visualization::Visualizer::ResetViewPoint().
CreateCylinder()
std::shared_ptr< ccMesh > ccMesh::CreateCylinder (double radius = 1.0, double height = 2.0, int resolution = 20, int split = 4, bool create_uv_map = false) static
Factory function to create a cylinder mesh (TriangleMeshFactory.cpp) The axis of the cylinder will be from (0, 0, -height/2) to (0, 0, height/2). The circle with radius will be split into resolution segments. The height will be split into split segments.
Parameters
radius defines the radius of the cylinder.
height defines the height of the cylinder.
resolution defines that the circle will be split into resolution segments
split defines that the height will be split into split segments.
create_uv_map add default UV map to the mesh.
Definition at line 2368 of file TriangleMeshFactory.cpp.
References cloudViewer::PointCloudTpl< T >::getPointPtr(), height, LogError, M_PI, cloudViewer::core::make_pair(), normals, ccPointCloud::resize(), cloudViewer::PointCloudTpl< T >::setEigenPoint(), ccObject::setEnabled(), ccObject::setLocked(), and ccPointCloud::shrinkToFit().
Referenced by cloudViewer::t::geometry::TriangleMesh::CreateCylinder().
CreateFromPointCloudAlphaShape()
std::shared_ptr< ccMesh > ccMesh::CreateFromPointCloudAlphaShape (const ccPointCloud & pcd, double alpha, std::shared_ptr< cloudViewer::geometry::TetraMesh > tetra_mesh = nullptr, std::vector< size_t > * pt_map = nullptr) static
Alpha shapes are a generalization of the convex hull. With decreasing alpha value the shape schrinks and creates cavities. See Edelsbrunner and Muecke, "Three-Dimensional Alpha Shapes", 1994.
Parameters
pcd PointCloud for what the alpha shape should be computed.
alpha parameter to controll the shape. A very big value will give a shape close to the convex hull.
tetra_mesh If not a nullptr, than uses this to construct the alpha shape. Otherwise, ComputeDelaunayTetrahedralization is called.
pt_map Optional map from tetra_mesh vertex indices to pcd points.
Returns
ccMesh of the alpha shape.
Definition at line 20 of file SurfaceReconstructionAlphaShape.cpp.
References a, cloudViewer::PointCloudTpl< T >::addPoints(), cloudViewer::geometry::Qhull::ComputeDelaunayTetrahedralization(), GetOrderedTriangle(), ccPointCloud::getPointColor(), ccPointCloud::getPointNormal(), cloudViewer::PointCloudTpl< T >::getPoints(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), LogDebug, LogError, normals, ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), ccObject::setEnabled(), ccObject::setLocked(), ccPointCloud::setPointColor(), ccPointCloud::setPointNormal(), and ccPointCloud::shrinkToFit().
CreateFromPointCloudBallPivoting()
std::shared_ptr< ccMesh > ccMesh::CreateFromPointCloudBallPivoting (const ccPointCloud & pcd, const std::vector< double > & radii) static
Function that computes a triangle mesh from a oriented PointCloud
Parameters
pcd. This implements the Ball Pivoting algorithm proposed in F. Bernardini et al., "The ball-pivoting algorithm for surface reconstruction", 1999. The implementation is also based on the algorithms outlined in Digne, "An Analysis and Implementation of a Parallel Ball Pivoting Algorithm", 2014. The surface reconstruction is done by rolling a ball with a given radius (cf.
radii) over the point cloud, whenever the ball touches three points a triangle is created.
pcd defines the PointCloud from which the ccMesh surface is reconstructed. Has to contain normals.
radii defines the radii of the ball that are used for the surface reconstruction.
Definition at line 770 of file SurfaceReconstructionBallPivoting.cpp.
References radii, and BallPivoting::Run().
Referenced by cloudViewer::pipelines::registration::BenchmarkCreateFromPointCloudBallPivoting().
CreateFromPointCloudPoisson()
std::tuple< std::shared_ptr< ccMesh >, std::vector< double > > ccMesh::CreateFromPointCloudPoisson (const ccPointCloud & pcd, size_t depth = 8, size_t width = 0, float scale = 1.1f, bool linear_fit = false, float point_weight = 2.f, float samples_per_node = 1.5f, int boundary_type = 2, int n_threads = -1) static
Function that computes a triangle mesh from a oriented PointCloud pcd. This implements the Screened Poisson Reconstruction proposed in Kazhdan and Hoppe, "Screened Poisson Surface Reconstruction", 2013. This function uses the original implementation by Kazhdan. See https://github.com/mkazhdan/PoissonRecon.
Parameters
pcd PointCloud with normals and optionally colors.
depth Maximum depth of the tree that will be used for surface reconstruction. Running at depth d corresponds to solving on a grid whose resolution is no larger than 2^d x 2^d x 2^d. Note that since the reconstructor adapts the octree to the sampling density, the specified reconstruction depth is only an upper bound.
width Specifies the target width of the finest level octree cells. This parameter is ignored if depth is specified.
scale Specifies the ratio between the diameter of the cube used for reconstruction and the diameter of the samples' bounding cube.
linear_fit If true, the reconstructor use linear interpolation to estimate the positions of iso-vertices.
point_weight The importance that interpolation of the point samples is given in the formulation of the screened Poisson equation. The results of the original (unscreened) Poisson Reconstruction can be obtained by setting this value to 0
samples_per_node The minimum number of sample points that should fall within an octree node as the octree construction is adapted to sampling density. This parameter specifies the minimum number of points that should fall within an octree node. For noise-free samples, small values in the range [1.0 - 5.0] can be used. For more noisy samples, larger values in the range [15.0 - 20.0] may be needed to provide a smoother, noise-reduced, reconstruction.
boundary_type Boundary type for the finite elements
n_threads Number of threads used for reconstruction. Set to -1 to automatically determine it.
Returns
The estimated ccMesh, and per vertex densitie values that can be used to to trim the mesh.
Definition at line 768 of file SurfaceReconstructionPoisson.cpp.
References poisson::DEFAULT_FEM_DEGREE, poisson::DIMENSION, ccPointCloud::hasNormals(), LogError, and width.
Referenced by doReconstruct().
CreateIcosahedron()
std::shared_ptr< ccMesh > ccMesh::CreateIcosahedron (double radius = 1.0, bool create_uv_map = false) static
Factory function to create an icosahedron mesh (trianglemeshfactory.cpp). The mesh centroid will be at (0,0,0) and
Parameters
radius defines the distance from the center to the mesh vertices.
create_uv_map add default UV map to the mesh.
Definition at line 1959 of file TriangleMeshFactory.cpp.
References cloudViewer::PointCloudTpl< T >::addEigenPoint(), LogError, normals, ccObject::setEnabled(), ccObject::setLocked(), and ccPointCloud::shrinkToFit().
Referenced by cloudViewer::t::geometry::TriangleMesh::CreateIcosahedron().
CreateMobius()
std::shared_ptr< ccMesh > ccMesh::CreateMobius (int length_split = 70, int width_split = 15, int twists = 1, double radius = 1, double flatness = 1, double width = 1, double scale = 1) static
Factory function to create a Mobius strip.
Parameters
length_split defines the number of segments along the Mobius strip.
width_split defines the number of segments along the width of the Mobius strip.
twists defines the number of twists of the strip.
radius defines the radius of the Mobius strip.
flatness controls the height of the strip.
width controls the width of the Mobius strip.
scale is used to scale the entire Mobius strip.
Definition at line 2850 of file TriangleMeshFactory.cpp.
References cloudViewer::PointCloudTpl< T >::getPointPtr(), LogError, M_PI, normals, ccPointCloud::resize(), ccObject::setEnabled(), ccObject::setLocked(), ccPointCloud::shrinkToFit(), width, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by cloudViewer::t::geometry::TriangleMesh::CreateMobius().
createNewMeshFromSelection()
ccMesh * ccMesh::createNewMeshFromSelection (bool removeSelectedTriangles, std::vector< int > * newIndexesOfRemainingTriangles = nullptr, bool withChildEntities = false)
Creates a new mesh with the selected vertices only.
This method is called after a graphical segmentation. It creates a new mesh structure with the vertices that are tagged as "visible" (see ccGenericPointCloud::visibilityArray). This method will also update this mesh if removeSelectedFaces is true. In this case, all "selected" triangles will be removed from this mesh's instance.
    \param  removeSelectedTriangles         specifies if the
faces composed only of 'selected' vertices should be removed or not. If true, the visibility array will be automatically unallocated on completion
Parameters
newIndexesOfRemainingTriangles the new indexes of the remaining triangles (if removeSelectedTriangles is true - optional). Must be initially empty or have the same size as the original mesh.
withChildEntities whether child entities should be transferred as well (see ccHObjectCaster::CloneChildren)
Returns
the new mesh (if successful) or itself if all vertices were visible/selected
Definition at line 2747 of file ecvMesh.cpp.
References ccHObject::addChild(), addTriangleMtlIndex(), addTriangleNormalIndexes(), addTriangleTexCoordIndexes(), ccMesh(), ccHObjectCaster::CloneChildren(), ccDrawableObject::colorsShown(), ccGenericPointCloud::createNewCloudFromVisibilitySelection(), ccSubMesh::createNewSubMeshFromSelection(), ccHObject::filterChildren(), ccObject::getName(), ccGenericPointCloud::getTheVisibilityArray(), ccArray< Type, N, ComponentType >::getValue(), cloudViewer::VerticesIndexes::i, ccGenericMesh::importParametersFrom(), ccObject::isEnabled(), ccDrawableObject::isVisible(), CCShareable::link(), m_associatedCloud, m_materials, m_texCoordIndexes, m_texCoords, m_triMtlIndexes, m_triNormalIndexes, m_triNormals, m_triVertIndexes, ccGenericMesh::materialsShown(), normalsShown(), ccHObject::notifyGeometryUpdate(), POINT_HIDDEN, CCShareable::release(), ccHObject::removeChild(), removePerTriangleMtlIndexes(), removePerTriangleNormalIndexes(), removePerTriangleTexCoordIndexes(), ccGenericPointCloud::removeVisiblePoints(), reservePerTriangleMtlIndexes(), reservePerTriangleNormalIndexes(), reservePerTriangleTexCoordIndexes(), ccArray< Type, N, ComponentType >::reserveSafe(), resize(), cloudViewer::ManualSegmentationTools::segmentMesh(), ccSubMesh::setAssociatedMesh(), ccObject::setEnabled(), setMaterialSet(), ccObject::setName(), setTexCoordinatesTable(), setTriNormsTable(), ccArray< Type, N, ComponentType >::setValue(), ccDrawableObject::setVisible(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccGenericMesh::showMaterials(), ccGenericMesh::showNormals(), ccDrawableObject::showSF(), cloudViewer::GenericCloud::size(), cloudViewer::ReferenceCloud::size(), size(), ccSubMesh::size(), CV_TYPES::SUB_MESH, Tuple3Tpl< Type >::u, ccGenericPointCloud::unallocateVisibilityArray(), and CVLog::Warning().
Referenced by ecvFilterByLabelDlg::apply(), and ccGraphicalSegmentationTool::applySegmentation().
CreateOctahedron()
std::shared_ptr< ccMesh > ccMesh::CreateOctahedron (double radius = 1.0, bool create_uv_map = false) static
Factory function to create an octahedron mesh (trianglemeshfactory.cpp). the mesh centroid will be at (0,0,0) and radius defines the distance from the center to the mesh vertices.
Parameters
radius defines the distance from centroid to mesh vetices.
create_uv_map add default UV map to the mesh.
Definition at line 1902 of file TriangleMeshFactory.cpp.
References cloudViewer::PointCloudTpl< T >::addEigenPoint(), LogError, normals, ccObject::setEnabled(), ccObject::setLocked(), and ccPointCloud::shrinkToFit().
Referenced by cloudViewer::t::geometry::TriangleMesh::CreateOctahedron().
CreatePlane()
std::shared_ptr< ccMesh > ccMesh::CreatePlane (double width = 1.0, double height = 1.0, bool create_uv_map = false) static
Factory function to create a plane mesh (TriangleMeshFactory.cpp) The left bottom corner on the front will be placed at (0, 0, 0).
Parameters
width is x-directional length.
height is y-directional length.
create_uv_map add default UV map to the shape.
Definition at line 2047 of file TriangleMeshFactory.cpp.
References cloudViewer::PointCloudTpl< T >::getPointPtr(), height, LogError, normals, ccPointCloud::resize(), ccObject::setEnabled(), ccObject::setLocked(), ccPointCloud::shrinkToFit(), and width.
CreateSphere()
std::shared_ptr< ccMesh > ccMesh::CreateSphere (double radius = 1.0, int resolution = 20, bool create_uv_map = false) static
Factory function to create a sphere mesh (TriangleMeshFactory.cpp) The sphere with radius will be centered at (0, 0, 0). Its axis is aligned with z-axis.
Parameters
radius defines radius of the sphere.
resolution defines the resolution of the sphere. The longitudes will be split into resolution segments (i.e. there are resolution + 1 latitude lines including the north and south pole). The latitudes will be split into `2 * resolution segments (i.e. there are 2 * resolution longitude lines.)
create_uv_map add default UV map to the mesh.
Definition at line 2180 of file TriangleMeshFactory.cpp.
References cloudViewer::PointCloudTpl< T >::getPointPtr(), LogError, M_PI, cloudViewer::core::make_pair(), normals, ccPointCloud::resize(), cloudViewer::PointCloudTpl< T >::setEigenPoint(), ccObject::setEnabled(), ccObject::setLocked(), ccPointCloud::shrinkToFit(), and width.
Referenced by cloudViewer::t::geometry::TriangleMesh::CreateSphere(), and cloudViewer::visualization::rendering::LightDirectionInteractorLogic::StartMouseDrag().
CreateTetrahedron()
std::shared_ptr< ccMesh > ccMesh::CreateTetrahedron (double radius = 1.0, bool create_uv_map = false) static
Factory function to create a tetrahedron mesh (trianglemeshfactory.cpp). the mesh centroid will be at (0,0,0) and radius defines the distance from the center to the mesh vertices.
Parameters
radius defines the distance from centroid to mesh vetices.
create_uv_map add default UV map to the mesh.
Definition at line 1851 of file TriangleMeshFactory.cpp.
References cloudViewer::PointCloudTpl< T >::addEigenPoint(), LogError, normals, ccObject::setEnabled(), ccObject::setLocked(), and ccPointCloud::shrinkToFit().
Referenced by cloudViewer::t::geometry::TriangleMesh::CreateTetrahedron().
CreateTorus()
std::shared_ptr< ccMesh > ccMesh::CreateTorus (double torus_radius = 1.0, double tube_radius = 0.5, int radial_resolution = 30, int tubular_resolution = 20) static
Factory function to create a torus mesh (TriangleMeshFactory.cpp) The torus will be centered at (0, 0, 0) and a radius of torus_radius. The tube of the torus will have a radius of tube_radius. The number of segments in radial and tubular direction are radial_resolution and tubular_resolution respectively.
Parameters
torus_radius defines the radius from the center of the torus to the center of the tube.
tube_radius defines the radius of the torus tube.
radial_resolution defines the he number of segments along the radial direction.
tubular_resolution defines the number of segments along the tubular direction.
Definition at line 2689 of file TriangleMeshFactory.cpp.
References cloudViewer::PointCloudTpl< T >::getPointPtr(), LogError, M_PI, normals, ccPointCloud::resize(), ccObject::setEnabled(), ccObject::setLocked(), and ccPointCloud::shrinkToFit().
Referenced by cloudViewer::t::geometry::TriangleMesh::CreateTorus().
Crop() [1/2]
std::shared_ptr< ccMesh > ccMesh::Crop (const ccBBox & bbox) const
Function to crop pointcloud into output pointcloud All points with coordinates outside the bounding box
Parameters
bbox are clipped.
bbox defines the input Axis Aligned Bounding Box.
Definition at line 992 of file ecvMesh.cpp.
References cloudViewer::BoundingBoxTpl< T >::GetPointIndicesWithinBoundingBox(), getVertices(), cloudViewer::BoundingBoxTpl< T >::isValid(), LogError, and SelectByIndex().
Crop() [2/2]
std::shared_ptr< ccMesh > ccMesh::Crop (const ecvOrientedBBox & bbox) const
Function to crop pointcloud into output pointcloud All points with coordinates outside the bounding box
Parameters
bbox are clipped.
bbox defines the input Oriented Bounding Box.
Definition at line 1002 of file ecvMesh.cpp.
References cloudViewer::OrientedBoundingBox::GetPointIndicesWithinBoundingBox(), cloudViewer::PointCloudTpl< T >::getPoints(), ecvOrientedBBox::IsEmpty(), LogError, m_associatedCloud, SelectByIndex(), and ccHObjectCaster::ToPointCloud().
DeformAsRigidAsPossible()
std::shared_ptr< ccMesh > ccMesh::DeformAsRigidAsPossible (const std::vector< int > & constraint_vertex_indices, const std::vector< Eigen::Vector3d > & constraint_vertex_positions, size_t max_iter, DeformAsRigidAsPossibleEnergy energy = DeformAsRigidAsPossibleEnergy::Spokes, double smoothed_alpha = 0.01) const
This function deforms the mesh using the method by Sorkine and Alexa, "As-Rigid-As-Possible Surface Modeling", 2007.
Parameters
constraint_vertex_indices Indices of the triangle vertices that should be constrained by the vertex positions in constraint_vertex_positions.
constraint_vertex_positions Vertex positions used for the constraints.
max_iter maximum number of iterations to minimize energy functional.
energy energy model that should be optimized
smoothed_alpha alpha parameter of the smoothed ARAP model
Returns
The deformed ccMesh
Definition at line 21 of file TriangleMeshDeformation.cpp.
References cloudViewer::PointCloudTpl< T >::addPoints(), cloudViewer::t::geometry::GetOrderedEdge(), cloudViewer::PointCloudTpl< T >::getPointPtr(), LogDebug, LogError, normals, ccObject::setEnabled(), ccObject::setLocked(), ccPointCloud::shrinkToFit(), and std::swap().
drawMeOnly()
void ccMesh::drawMeOnly (CC_DRAW_CONTEXT & context) override protected virtual
Enables (OpenGL) stipple mask.
Reimplemented from ccGenericMesh.
Reimplemented in ccPlane.
Definition at line 2635 of file ecvMesh.cpp.
References ccScalarField::areNaNValuesShownInGrey(), cloudViewer::utility::ceil(), context, ecvDisplayTools::Draw(), ECV_POINTS_MODE, ECV_SURFACE_MODE, ECV_WIREFRAME_MODE, ccPointCloud::getCurrentDisplayedScalarField(), ccDrawableObject::getDrawingParameters(), ecvDisplayTools::GetMainWindow(), ccGenericPointCloud::getTheVisibilityArray(), ccGenericMesh::handleColorRamp(), hasMaterials(), ccDrawableObject::hasNormals(), hasTextures(), hasTriNormals(), ccObject::isA(), ccDrawableObject::isColorOverridden(), ccGenericMesh::isShownAsPoints(), ccGenericMesh::isShownAsWire(), ecvColor::lightGrey(), m_associatedCloud, ccDrawableObject::m_normalsDisplayed, ccDrawableObject::m_tempColor, m_triVertIndexes, MACRO_Draw3D, MACRO_EntityPicking, MACRO_FastEntityPicking, MACRO_LightIsEnabled, MACRO_LODActivated, ccGenericMesh::materialsShown(), CV_TYPES::POINT_CLOUD, glDrawParams::showColors, glDrawParams::showNorms, glDrawParams::showSF, ccGenericMesh::showWired(), cloudViewer::GenericCloud::size(), and ccGenericMesh::triNormsShown().
Referenced by ccCoordinateSystem::drawMeOnly(), and ccPlane::drawMeOnly().
EulerPoincareCharacteristic()
int ccMesh::EulerPoincareCharacteristic () const
Function that computes the Euler-Poincaré characteristic, i.e., V + F - E, where V is the number of vertices, F is the number of triangles, and E is the number of edges.
Definition at line 879 of file TriangleMeshFactory.cpp.
References cloudViewer::t::geometry::GetOrderedEdge(), and size.
FilterSharpen()
std::shared_ptr< ccMesh > ccMesh::FilterSharpen (int number_of_iterations, double strength, FilterScope scope = FilterScope::All) const
Function to sharpen triangle mesh.
The output value ($v_o$) is the input value ($v_i$) plus strength times the input value minus the sum of he adjacent values. $v_o = v_i x strength (v_i * |N| - \sum_{n \in N} v_n)$.
Parameters
number_of_iterations defines the number of repetitions of this operation.
strength - The strength of the filter.
Definition at line 413 of file TriangleMeshFactory.cpp.
References ccPointCloud::getPointNormals(), cloudViewer::PointCloudTpl< T >::getPoints(), ccArray< Type, N, ComponentType >::getValue(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), normals, ccPointCloud::resize(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), ccPointCloud::rgbColors(), ccObject::setEnabled(), ccObject::setLocked(), cloudViewer::PointCloudTpl< T >::setPoint(), ccPointCloud::setPointColor(), ccPointCloud::setPointNormal(), ccPointCloud::shrinkToFit(), cloudViewer::PointCloudTpl< T >::size(), std::swap(), ecvColor::RgbTpl< Type >::ToEigen(), and ccHObjectCaster::ToPointCloud().
FilterSmoothLaplacian()
std::shared_ptr< ccMesh > ccMesh::FilterSmoothLaplacian (int number_of_iterations, double lambda, FilterScope scope = FilterScope::All) const
Function to smooth triangle mesh using Laplacian.
$v_o = v_i \cdot \lambda (sum_{n \in N} w_n v_n - v_i)$, with $v_i$ being the input value, $v_o$ the output value, $N$ is the set of adjacent neighbours, $w_n$ is the weighting of the neighbour based on the inverse distance (closer neighbours have higher weight),
Parameters
number_of_iterations defines the number of repetitions of this operation.
lambda is the smoothing parameter.
Definition at line 706 of file TriangleMeshFactory.cpp.
References ccPointCloud::getPointNormals(), cloudViewer::PointCloudTpl< T >::getPoints(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), normals, ccPointCloud::resize(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), ccPointCloud::rgbColors(), ccObject::setEnabled(), ccObject::setLocked(), ccPointCloud::shrinkToFit(), cloudViewer::PointCloudTpl< T >::size(), std::swap(), and ccHObjectCaster::ToPointCloud().
FilterSmoothLaplacianHelper()
void ccMesh::FilterSmoothLaplacianHelper (std::shared_ptr< ccMesh > & mesh, const std::vector< CCVector3 > & prev_vertices, const std::vector< CCVector3 > & prev_vertex_normals, const ColorsTableType & prev_vertex_colors, const std::vector< std::unordered_set< int >> & adjacency_list, double lambda, bool filter_vertex, bool filter_normal, bool filter_color) const protected
Definition at line 645 of file TriangleMeshFactory.cpp.
References e, cloudViewer::PointCloudTpl< T >::setPoint(), ccPointCloud::setPointColor(), ccPointCloud::setPointNormal(), cloudViewer::PointCloudTpl< T >::size(), ecvColor::RgbTpl< Type >::ToEigen(), and ccHObjectCaster::ToPointCloud().
FilterSmoothSimple()
std::shared_ptr< ccMesh > ccMesh::FilterSmoothSimple (int number_of_iterations, FilterScope scope = FilterScope::All) const
Function to smooth triangle mesh with simple neighbour average.
$v_o = \frac{v_i + \sum_{n \in N} v_n)}{|N| + 1}$, with $v_i$ being the input value, $v_o$ the output value, and $N$ is the set of adjacent neighbours.
Parameters
number_of_iterations defines the number of repetitions of this operation.
Definition at line 535 of file TriangleMeshFactory.cpp.
References ccPointCloud::getPointNormals(), cloudViewer::PointCloudTpl< T >::getPoints(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), normals, ccPointCloud::resize(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), ccPointCloud::rgbColors(), ccObject::setEnabled(), ccObject::setLocked(), cloudViewer::PointCloudTpl< T >::setPoint(), ccPointCloud::setPointColor(), ccPointCloud::setPointNormal(), ccPointCloud::shrinkToFit(), cloudViewer::PointCloudTpl< T >::size(), std::swap(), ecvColor::RgbTpl< Type >::ToEigen(), and ccHObjectCaster::ToPointCloud().
FilterSmoothTaubin()
std::shared_ptr< ccMesh > ccMesh::FilterSmoothTaubin (int number_of_iterations, double lambda = 0.5, double mu = -0.53, FilterScope scope = FilterScope::All) const
Function to smooth triangle mesh using method of Taubin, "Curve and Surface Smoothing Without Shrinkage", 1995. Applies in each iteration two times FilterSmoothLaplacian, first with lambda and second with mu as smoothing parameter. This method avoids shrinkage of the triangle mesh.
Parameters
number_of_iterations defines the number of repetitions of this operation.
lambda is the filter parameter
mu is the filter parameter
Definition at line 785 of file TriangleMeshFactory.cpp.
References ccPointCloud::getPointNormals(), cloudViewer::PointCloudTpl< T >::getPoints(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), normals, ccPointCloud::resize(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), ccPointCloud::rgbColors(), ccObject::setEnabled(), ccObject::setLocked(), ccPointCloud::shrinkToFit(), cloudViewer::PointCloudTpl< T >::size(), std::swap(), and ccHObjectCaster::ToPointCloud().
flipTriangles()
void ccMesh::flipTriangles ()
Flips the triangle.
Swaps the second and third vertices indexes
Definition at line 3309 of file ecvMesh.cpp.
References m_triVertIndexes, and std::swap().
forEach()
void ccMesh::forEach (genericTriangleAction action) override virtual
Fast iteration mechanism.
Virtual method to apply a function to the whole mesh
Parameters
action function to apply (see GenericMesh::genericTriangleAction)
Implements cloudViewer::GenericMesh.
Definition at line 2151 of file ecvMesh.cpp.
References cloudViewer::SimpleRefTriangle::A, cloudViewer::SimpleRefTriangle::B, cloudViewer::SimpleRefTriangle::C, cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, m_associatedCloud, m_currentTriangle, and m_triVertIndexes.
fromFile_MeOnly()
bool ccMesh::fromFile_MeOnly (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override protected virtual
Loads own object data.
Called by 'fromFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
in input file
dataVersion file version
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Reimplemented from ccGenericMesh.
Reimplemented in ccTorus, ccSphere, ccQuadric, and ccPlane.
Definition at line 3877 of file ecvMesh.cpp.
getAssociatedCloud()
ccGenericPointCloud* ccMesh::getAssociatedCloud () const inline override virtual
Returns the vertices cloud.
Implements ccGenericMesh.
Definition at line 143 of file ecvMesh.h.
Referenced by addVertice(), ccPointCloud::append(), cloudViewer::io::AutoReadEntity(), CCMeshToDraco(), clear(), ccEntityAction::clearProperty(), ConvexConcaveHullReconstruction::compute(), GreedyTriangulation::compute(), MarchingCubeReconstruction::compute(), NurbsSurfaceReconstruction::compute(), PoissonReconstruction::compute(), cloudViewer::visualization::SelectionPolygonVolume::CropTriangleMesh(), cloudViewer::visualization::SelectionPolygon::CropTriangleMesh(), ccSubMesh::getAssociatedCloud(), GetCenter(), getEigenVertices(), GetMaxBound(), GetMinBound(), cvIsoSurfaceFilter::getOutput(), cvSliceFilter::getOutput(), getVertice(), getVertices(), getVerticeSize(), getVerticesPtr(), STLFilter::loadFile(), merge(), ccGenericPrimitive::operator+=(), operator=(), CommandClearNormals::process(), CommandDelaunayTri::process(), ccEntityAction::processMeshSF(), pushSubdivide(), cloudViewer::io::ReadTriangleMesh(), cloudViewer::io::ReadTriangleMeshFromOBJ(), cloudViewer::io::ReadTriangleMeshFromPLY(), cloudViewer::io::ReadTriangleMeshUsingASSIMP(), VTKFilter::saveToFile(), SelectByIndex(), ccEntityAction::setColor(), cloudViewer::pipelines::color_map::SetGeometryColorAverage(), ccPlane::SetQuadTexture(), cloudViewer::io::rpc::SetTriangleMesh(), setVertice(), ecvPoissonReconDlg::start(), subdivide(), colmap::mvs::MvsTexturing::TextureMesh(), and Triangulate().
GetAxisAlignedBoundingBox()
ccBBox ccMesh::GetAxisAlignedBoundingBox () const override virtual
Returns an axis-aligned bounding box of the geometry.
Reimplemented from ccHObject.
Definition at line 844 of file ecvMesh.cpp.
References ccBBox::CreateFromPoints(), and getVertices().
Referenced by cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::ComputeAABB(), and ccFacet::GetAxisAlignedBoundingBox().
getBoundingBox()
void ccMesh::getBoundingBox (CCVector3 & bbMin, CCVector3 & bbMax) override virtual
Returns the mesh bounding-box.
Virtual method to request the mesh bounding-box limits. It is equivalent to the bounding-box of the cloud composed of the mesh vertexes.
Parameters
bbMin lower bounding-box limits (Xmin,Ymin,Zmin)
bbMax higher bounding-box limits (Xmax,Ymax,Zmax)
Implements cloudViewer::GenericMesh.
Definition at line 2406 of file ecvMesh.cpp.
References m_bBox, cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), and refreshBB().
GetCenter()
Eigen::Vector3d ccMesh::GetCenter () const override virtual
Returns the center of the geometry coordinates.
Reimplemented from ccHObject.
Definition at line 836 of file ecvMesh.cpp.
References ccHObject::ComputeCenter(), getAssociatedCloud(), cloudViewer::PointCloudTpl< T >::getEigenPoints(), and ccHObjectCaster::ToPointCloud().
Referenced by ccFacet::GetCenter().
getClassID()
CV_CLASS_ENUM ccMesh::getClassID () const inline override virtual
Returns class ID.
Reimplemented from ccHObject.
Reimplemented in ccTorus, ccSphere, ccQuadric, and ccPlane.
Definition at line 63 of file ecvMesh.h.
References CV_TYPES::MESH.
getColorFromMaterial()
bool ccMesh::getColorFromMaterial (unsigned triIndex, const CCVector3 & P, ecvColor::Rgb & C, bool interpolateColorIfNoTexture) override virtual
! Returns RGB color from a given triangle material/texture **
Parameters
triIndex triangle index
Implements ccGenericMesh.
Definition at line 4228 of file ecvMesh.cpp.
References ecvColor::RgbaTpl< Type >::b, computeInterpolationWeights(), cloudViewer::utility::floor(), ecvColor::RgbaTpl< Type >::g, ccArray< Type, N, ComponentType >::getValue(), hasMaterials(), interpolateColors(), m_materials, m_texCoordIndexes, m_texCoords, m_triMtlIndexes, ecvColor::MAX, ecvColor::RgbaTpl< Type >::r, rgb, size(), TexCoords2D::tx, TexCoords2D::ty, Tuple3Tpl< Type >::u, x, y, and ZERO_TOLERANCE_D.
Referenced by ccSubMesh::getColorFromMaterial().
GetEdgeToTrianglesMap()
std::unordered_map< Eigen::Vector2i, std::vector< int >, utility::hash_eigen< Eigen::Vector2i > > ccMesh::GetEdgeToTrianglesMap () const
Function that returns a map from edges (vertex0, vertex1) to the triangle indices the given edge belongs to.
Definition at line 1589 of file TriangleMeshFactory.cpp.
References cloudViewer::t::geometry::GetOrderedEdge(), and size.
GetEdgeToVerticesMap()
std::unordered_map< Eigen::Vector2i, std::vector< int >, utility::hash_eigen< Eigen::Vector2i > > ccMesh::GetEdgeToVerticesMap () const
Function that returns a map from edges (vertex0, vertex1) to the vertex (vertex2) indices the given edge belongs to.
Definition at line 1610 of file TriangleMeshFactory.cpp.
References cloudViewer::t::geometry::GetOrderedEdge(), and size.
getEigenVertices()
std::vector< Eigen::Vector3d > ccMesh::getEigenVertices () const
Definition at line 2368 of file ecvMesh.cpp.
References getAssociatedCloud(), cloudViewer::PointCloudTpl< T >::getEigenPoints(), and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::geometry::LineSet::CreateFromTriangleMesh(), cloudViewer::pipelines::color_map::CreateVertexAndImageVisibility(), and cloudViewer::t::geometry::TriangleMesh::FromLegacy().
GetEigneOrderedTriangle()
static Eigen::Vector3i ccMesh::GetEigneOrderedTriangle (int vidx0, int vidx1, int vidx2) inline static
Definition at line 965 of file ecvMesh.h.
References std::swap().
getGLTransformationHistory()
const ccGLMatrix & ccMesh::getGLTransformationHistory () const override virtual
Returns the transformation 'history' matrix.
Reimplemented from ccHObject.
Definition at line 2419 of file ecvMesh.cpp.
References ccHObject::getGLTransformationHistory(), m_associatedCloud, and ccHObject::m_glTransHistory.
getMaterialSet()
const ccMaterialSet* ccMesh::getMaterialSet () const inline override virtual
Implements ccGenericMesh.
Definition at line 412 of file ecvMesh.h.
Referenced by cloneMesh(), ccSubMesh::getMaterialSet(), partialClone(), ccPlane::SetQuadTexture(), and ToFbxMesh().
GetMaxBound()
Eigen::Vector3d ccMesh::GetMaxBound () const override virtual
Returns max bounds for geometry coordinates.
Reimplemented from ccHObject.
Definition at line 828 of file ecvMesh.cpp.
References ccHObject::ComputeMaxBound(), getAssociatedCloud(), cloudViewer::PointCloudTpl< T >::getEigenPoints(), and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::geometry::VoxelGrid::CreateFromTriangleMesh(), ccFacet::GetMaxBound(), and IsBoundingBoxIntersecting().
GetMinBound()
Eigen::Vector3d ccMesh::GetMinBound () const override virtual
Returns min bounds for geometry coordinates.
Reimplemented from ccHObject.
Definition at line 820 of file ecvMesh.cpp.
References ccHObject::ComputeMinBound(), getAssociatedCloud(), cloudViewer::PointCloudTpl< T >::getEigenPoints(), and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::geometry::VoxelGrid::CreateFromTriangleMesh(), ccFacet::GetMinBound(), and IsBoundingBoxIntersecting().
getNextTriangleVertIndexes()
cloudViewer::VerticesIndexes * ccMesh::getNextTriangleVertIndexes () override virtual
Returns the indexes of the vertices of the next triangle (relatively to the global iterator position)
Returns
the triangle indexes (or 0 if the global iterator is out of bounds)
Implements cloudViewer::GenericIndexedMesh.
Definition at line 2618 of file ecvMesh.cpp.
References getTriangleVertIndexes(), m_globalIterator, and size().
Referenced by cloneMesh(), computePerVertexNormals(), convertMaterialsToVertexColors(), laplacianSmooth(), processScalarField(), and VTKFilter::saveToFile().
GetNonManifoldEdges()
std::vector< Eigen::Vector2i > ccMesh::GetNonManifoldEdges (bool allow_boundary_edges = true) const
Function that returns the non-manifold edges of the triangle mesh. If
Parameters
allow_boundary_edges is set to false, than also boundary edges are returned
Definition at line 895 of file TriangleMeshFactory.cpp.
References cloudViewer::t::geometry::GetEdgeToTrianglesMap().
GetNonManifoldVertices()
std::vector< int > ccMesh::GetNonManifoldVertices () const
Function that returns a list of non-manifold vertex indices. A vertex is manifold if its star is edge‐manifold and edge‐connected. (Two or more faces connected only by a vertex and not by an edge.)
Definition at line 921 of file TriangleMeshFactory.cpp.
References next, and size.
GetOrderedEdge()
static Eigen::Vector2i ccMesh::GetOrderedEdge (int vidx0, int vidx1) inline static
Helper function to get an edge with ordered vertex indices.
Definition at line 1005 of file ecvMesh.h.
Referenced by OrientTriangleHelper().
GetOrderedTriangle()
static cloudViewer::VerticesIndexes ccMesh::GetOrderedTriangle (int vidx0, int vidx1, int vidx2) inline static
Definition at line 92 of file ecvMesh.h.
References std::swap().
Referenced by CreateFromPointCloudAlphaShape().
GetOrientedBoundingBox()
ecvOrientedBBox ccMesh::GetOrientedBoundingBox () const override virtual
Reimplemented from ccHObject.
Definition at line 848 of file ecvMesh.cpp.
References ecvOrientedBBox::CreateFromPoints(), and getVertices().
Referenced by ccFacet::GetOrientedBoundingBox().
getOwnBB()
ccBBox ccMesh::getOwnBB (bool withGLFeatures = false) override virtual
Returns the entity's own bounding-box.
Children bboxes are ignored.
Parameters
withGLFeatures whether to take into account display-only elements (if any)
Returns
bounding-box
Reimplemented from ccHObject.
Definition at line 2413 of file ecvMesh.cpp.
References m_bBox, and refreshBB().
Referenced by ccDBRoot::alignCameraWithEntity(), and ccSphere::drawNameIn3D().
GetSelfIntersectingTriangles()
std::vector< Eigen::Vector2i > ccMesh::GetSelfIntersectingTriangles () const
Function that returns a list of triangles that are intersecting the mesh.
Definition at line 981 of file TriangleMeshFactory.cpp.
References size, and cloudViewer::utility::IntersectionTest::TriangleTriangle3d().
GetSurfaceArea() [1/2]
double ccMesh::GetSurfaceArea () const
Function that computes the surface area of the mesh, i.e. the sum of the individual triangle surfaces.
Definition at line 1644 of file TriangleMeshFactory.cpp.
References size.
GetSurfaceArea() [2/2]
double ccMesh::GetSurfaceArea (std::vector< double > & triangle_areas) const
Function that computes the surface area of the mesh, i.e. the sum of the individual triangle surfaces.
Definition at line 1653 of file TriangleMeshFactory.cpp.
References size.
getTexCoordinates()
void ccMesh::getTexCoordinates (unsigned index, TexCoords2D *& tx) const override virtual
Implements ccGenericMesh.
Definition at line 3653 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::getValue(), and m_texCoords.
Referenced by ccSubMesh::getTexCoordinates().
getTexCoordinatesTable()
TextureCoordsContainer* ccMesh::getTexCoordinatesTable () const inline override virtual
Returns per-triangle texture coordinates array.
Implements ccGenericMesh.
Definition at line 476 of file ecvMesh.h.
Referenced by CCMeshToDraco(), ccSubMesh::getTexCoordinatesTable(), ccPlane::SetQuadTexture(), and ToFbxMesh().
getTriangle()
Eigen::Vector3i ccMesh::getTriangle (size_t index) const
Definition at line 2448 of file ecvMesh.cpp.
References getTriangleVertIndexes(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, and cloudViewer::VerticesIndexes::i3.
Referenced by getTriangles(), and IsIntersecting().
GetTriangleArea()
double ccMesh::GetTriangleArea (size_t triangle_idx) const
Function that computes the area of a mesh triangle identified by the triangle index
Definition at line 1637 of file TriangleMeshFactory.cpp.
getTriangleMtlIndex()
int ccMesh::getTriangleMtlIndex (unsigned triangleIndex) const override virtual
Returns a given triangle material indexes.
Implements ccGenericMesh.
Definition at line 3761 of file ecvMesh.cpp.
References m_triMtlIndexes.
Referenced by ccCropTool::Crop(), ccSubMesh::getTriangleMtlIndex(), partialClone(), and ToFbxMesh().
getTriangleMtlIndexesTable()
const triangleMaterialIndexesSet* ccMesh::getTriangleMtlIndexesTable () const inline
Returns the per-triangle material indexes array.
Definition at line 454 of file ecvMesh.h.
Referenced by PlyFilter::loadFile().
getTriangleNorm()
Eigen::Vector3d ccMesh::getTriangleNorm (size_t index) const
Definition at line 3474 of file ecvMesh.cpp.
References ccNormalVectors::getNormal(), ccNormalVectors::GetUniqueInstance(), ccArray< Type, N, ComponentType >::getValue(), m_triNormals, and Tuple3Tpl< Type >::u.
Referenced by getTriangleNormals(), getTriangleNorms(), and SelectByIndex().
getTriangleNormalIndexes() [1/2]
CompressedNormType ccMesh::getTriangleNormalIndexes (size_t triangleIndex)
Definition at line 3505 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::getValue(), hasTriNormals(), and m_triNormals.
getTriangleNormalIndexes() [2/2]
void ccMesh::getTriangleNormalIndexes (unsigned triangleIndex, int & i1, int & i2, int & i3) const override virtual
Returns a triplet of normal indexes for a given triangle (if any)
Parameters
[in] triangleIndex triangle index
[out] i1 first vertex normal index (or -1 if none)
[out] i2 second vertex normal index (or -1 if none)
[out] i3 third vertex normal index (or -1 if none)
Implements ccGenericMesh.
Definition at line 3353 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::getValue(), m_triNormalIndexes, and Tuple3Tpl< Type >::u.
Referenced by ccSubMesh::getTriangleNormalIndexes(), partialClone(), VTKFilter::saveToFile(), and ToFbxMesh().
getTriangleNormals() [1/4]
std::vector< Eigen::Vector3d > ccMesh::getTriangleNormals () const
Definition at line 3456 of file ecvMesh.cpp.
References getTriangleNorm(), and size().
Referenced by getTriangleNormals().
getTriangleNormals() [2/4]
bool ccMesh::getTriangleNormals (unsigned triangleIndex, CCVector3 & Na, CCVector3 & Nb, CCVector3 & Nc) const override virtual
Returns a given triangle normal.
Mesh must have triangle normals associated (see hasTriNormals)
Implements ccGenericMesh.
Definition at line 3367 of file ecvMesh.cpp.
References ccNormalVectors::getNormal(), ccNormalVectors::GetUniqueInstance(), ccArray< Type, N, ComponentType >::getValue(), m_triNormalIndexes, m_triNormals, and Tuple3Tpl< Type >::u.
Referenced by ccSubMesh::getTriangleNormals().
getTriangleNormals() [3/4]
bool ccMesh::getTriangleNormals (unsigned triangleIndex, double Na[3], double Nb[3], double Nc[3]) const override virtual
Reimplemented from ccGenericMesh.
Definition at line 3396 of file ecvMesh.cpp.
References ccNormalVectors::getNormal(), ccNormalVectors::GetUniqueInstance(), ccArray< Type, N, ComponentType >::getValue(), m_triNormalIndexes, m_triNormals, and Tuple3Tpl< Type >::u.
getTriangleNormals() [4/4]
bool ccMesh::getTriangleNormals (unsigned triangleIndex, Eigen::Vector3d & Na, Eigen::Vector3d & Nb, Eigen::Vector3d & Nc) const override virtual
Reimplemented from ccGenericMesh.
Definition at line 3449 of file ecvMesh.cpp.
References getTriangleNormals().
getTriangleNormalsPtr()
std::vector< CCVector3 * > ccMesh::getTriangleNormalsPtr () const
Definition at line 3465 of file ecvMesh.cpp.
References ccNormalVectors::getNormal(), ccNormalVectors::GetUniqueInstance(), ccArray< Type, N, ComponentType >::getValue(), m_triNormals, and size().
Referenced by cloudViewer::io::rpc::SetTriangleMesh().
getTriangleNorms()
std::vector< Eigen::Vector3d > ccMesh::getTriangleNorms () const
Definition at line 3535 of file ecvMesh.cpp.
References getTriangleNorm(), hasTriNormals(), LogWarning, and m_triNormals.
GetTrianglePlane()
Eigen::Vector4d ccMesh::GetTrianglePlane (size_t triangle_idx) const
Function that computes the plane equation of a mesh triangle identified by the triangle index.
Definition at line 1713 of file TriangleMeshFactory.cpp.
getTriangles()
std::vector< Eigen::Vector3i > ccMesh::getTriangles () const
Definition at line 2462 of file ecvMesh.cpp.
References getTriangle(), cloudViewer::GenericMesh::hasTriangles(), LogWarning, and size().
getTrianglesPtr()
triangleIndexesContainer* ccMesh::getTrianglesPtr () const inline
Definition at line 279 of file ecvMesh.h.
Referenced by cloudViewer::io::rpc::SetTriangleMesh().
getTriangleTexCoordinates()
void ccMesh::getTriangleTexCoordinates (unsigned triIndex, TexCoords2D *& tx1, TexCoords2D *& tx2, TexCoords2D *& tx3) const override virtual
Returns per-triangle texture coordinates (pointer to)
Implements ccGenericMesh.
Definition at line 3620 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::getValue(), m_texCoordIndexes, m_texCoords, Tuple3Tpl< Type >::u, and CVLog::Warning().
Referenced by ccSubMesh::getTriangleTexCoordinates().
getTriangleTexCoordinatesIndexes()
void ccMesh::getTriangleTexCoordinatesIndexes (unsigned triangleIndex, int & i1, int & i2, int & i3) const override virtual
Returns the triplet of tex coords indexes for a given triangle.
Parameters
triangleIndex triangle index
i1 first vertex tex coords index
i2 second vertex tex coords index
i3 third vertex tex coords index
Implements ccGenericMesh.
Definition at line 3691 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::getValue(), m_texCoordIndexes, and Tuple3Tpl< Type >::u.
Referenced by ccSubMesh::getTriangleTexCoordinatesIndexes(), partialClone(), and ToFbxMesh().
getTriangleVertices() [1/2]
void ccMesh::getTriangleVertices (unsigned triangleIndex, CCVector3 & A, CCVector3 & B, CCVector3 & C) const override virtual
Returns the vertices of a given triangle.
Parameters
[in] triangleIndex index of the triangle (between 0 and the size(mesh)-1)
[out] A first vertex
[out] B second vertex
[out] C third vertex
Implements cloudViewer::GenericIndexedMesh.
Definition at line 2187 of file ecvMesh.cpp.
References cloudViewer::GenericIndexedCloud::getPoint(), ccArray< Type, N, ComponentType >::getValue(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, m_associatedCloud, m_triVertIndexes, and size().
Referenced by cloudViewer::geometry::VoxelGrid::CreateFromTriangleMeshWithinBounds(), and ccSubMesh::getTriangleVertices().
getTriangleVertices() [2/2]
void ccMesh::getTriangleVertices (unsigned triangleIndex, double A[3], double B[3], double C[3]) const override virtual
Implements cloudViewer::GenericIndexedMesh.
Definition at line 2200 of file ecvMesh.cpp.
References cloudViewer::GenericIndexedCloud::getPoint(), ccArray< Type, N, ComponentType >::getValue(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, m_associatedCloud, m_triVertIndexes, and size().
getTriangleVertIndexes() [1/3]
void ccMesh::getTriangleVertIndexes (size_t triangleIndex, Eigen::Vector3i & vertIndx) const
Definition at line 2609 of file ecvMesh.cpp.
References getTriangleVertIndexes(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, and cloudViewer::VerticesIndexes::i3.
getTriangleVertIndexes() [2/3]
const cloudViewer::VerticesIndexes * ccMesh::getTriangleVertIndexes (unsigned triangleIndex) const virtual
Definition at line 2604 of file ecvMesh.cpp.
References m_triVertIndexes.
getTriangleVertIndexes() [3/3]
cloudViewer::VerticesIndexes * ccMesh::getTriangleVertIndexes (unsigned triangleIndex) override virtual
Returns the indexes of the vertices of a given triangle.
Parameters
triangleIndex index of the triangle (between 0 and size(mesh)-1)
Returns
the triangle indexes (or 0 if index value is not valid)
Implements cloudViewer::GenericIndexedMesh.
Definition at line 2599 of file ecvMesh.cpp.
References m_triVertIndexes.
Referenced by CCMeshToDraco(), cloudViewer::geometry::LineSet::CreateFromTriangleMesh(), ccSubMesh::createNewSubMeshFromSelection(), ccCropTool::Crop(), cloudViewer::t::geometry::TriangleMesh::FromLegacy(), colmap::mvs::GenerateCandidate(), getNextTriangleVertIndexes(), ccSubMesh::getNextTriangleVertIndexes(), getTriangle(), getTriangleVertIndexes(), ccSubMesh::getTriangleVertIndexes(), CSVMatrixFilter::loadFile(), PlyFilter::loadFile(), merge(), mergeDuplicatedVertices(), ccGenericPrimitive::operator+=(), partialClone(), and SelectByIndex().
getTriNormsTable()
NormsIndexesTableType* ccMesh::getTriNormsTable () const inline override virtual
Returns per-triangle normals shared array.
Implements ccGenericMesh.
Definition at line 344 of file ecvMesh.h.
Referenced by pcl2cc::Convert(), vtk2cc::ConvertToMesh(), ccOctree::DrawCellAsAPrimitive(), ccSubMesh::getTriNormsTable(), STLFilter::loadASCIIFile(), STLFilter::loadBinaryFile(), STLFilter::loadFile(), main(), ccGenericPrimitive::operator+=(), VTKFilter::saveToFile(), and ToFbxMesh().
getUniqueIDForDisplay()
unsigned ccMesh::getUniqueIDForDisplay () const override virtual
Returns object unqiue ID used for display.
Reimplemented from ccHObject.
Definition at line 2626 of file ecvMesh.cpp.
References CV_TYPES::FACET, ccHObject::getParent(), ccObject::getUniqueID(), ccObject::isA(), and ccHObject::m_parent.
getVertexColor()
Eigen::Vector3d ccMesh::getVertexColor (size_t index) const
Definition at line 2295 of file ecvMesh.cpp.
References ccPointCloud::getEigenColor(), m_associatedCloud, and ccHObjectCaster::ToPointCloud().
getVertexColorFromMaterial()
bool ccMesh::getVertexColorFromMaterial (unsigned triIndex, unsigned char vertIndex, ecvColor::Rgb & C, bool returnColorIfNoTexture) override virtual
! Returns RGB color of a vertex from a given triangle material/texture **
Parameters
triIndex triangle index
Implements ccGenericMesh.
Definition at line 4154 of file ecvMesh.cpp.
References CVLog::Error(), cloudViewer::utility::floor(), ecvColor::FromQRgb(), ecvColor::FromRgbafToRgb(), ccGenericPointCloud::getPointColor(), ccArray< Type, N, ComponentType >::getValue(), hasColors(), hasMaterials(), cloudViewer::VerticesIndexes::i, m_associatedCloud, m_materials, m_texCoordIndexes, m_texCoords, m_triMtlIndexes, m_triVertIndexes, rgb, size(), TexCoords2D::tx, TexCoords2D::ty, and Tuple3Tpl< Type >::u.
Referenced by convertMaterialsToVertexColors(), and ccSubMesh::getVertexColorFromMaterial().
getVertexColors()
std::vector< Eigen::Vector3d > ccMesh::getVertexColors () const
Definition at line 2311 of file ecvMesh.cpp.
References ccPointCloud::getEigenColors(), m_associatedCloud, and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::t::geometry::TriangleMesh::FromLegacy().
getVertexColorsPtr()
ColorsTableType * ccMesh::getVertexColorsPtr ()
Definition at line 2319 of file ecvMesh.cpp.
References m_associatedCloud, ccPointCloud::rgbColors(), and ccHObjectCaster::ToPointCloud().
getVertexNormal()
Eigen::Vector3d ccMesh::getVertexNormal (size_t index) const
Definition at line 2251 of file ecvMesh.cpp.
References ccPointCloud::getEigenNormal(), m_associatedCloud, and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::ConstructBuffers().
getVertexNormals()
std::vector< Eigen::Vector3d > ccMesh::getVertexNormals () const
Definition at line 2266 of file ecvMesh.cpp.
References ccPointCloud::getEigenNormals(), m_associatedCloud, and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::t::geometry::TriangleMesh::FromLegacy().
getVertice()
Eigen::Vector3d ccMesh::getVertice (size_t index) const
Definition at line 2213 of file ecvMesh.cpp.
References getAssociatedCloud(), cloudViewer::PointCloudTpl< T >::getEigenPoint(), and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::io::AddTrianglesByEarClipping(), cloudViewer::pipelines::color_map::ComputeJacobianAndResidualNonRigid(), cloudViewer::pipelines::color_map::ComputeJacobianAndResidualRigid(), and IsIntersecting().
getVertices()
const std::vector< CCVector3 > & ccMesh::getVertices () const
Definition at line 2352 of file ecvMesh.cpp.
References getAssociatedCloud(), cloudViewer::PointCloudTpl< T >::getPoints(), LogError, and ccHObjectCaster::ToPointCloud().
Referenced by Crop(), GetAxisAlignedBoundingBox(), and GetOrientedBoundingBox().
getVerticeSize()
unsigned int ccMesh::getVerticeSize () const
Definition at line 2336 of file ecvMesh.cpp.
References getAssociatedCloud(), and cloudViewer::GenericCloud::size().
Referenced by cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::ConstructBuffers(), cloudViewer::pipelines::color_map::CreateVertexAndImageVisibility(), cloudViewer::io::ReadTriangleMesh(), cloudViewer::pipelines::color_map::RunNonRigidOptimizer(), SelectByIndex(), cloudViewer::pipelines::color_map::SetGeometryColorAverage(), and cloudViewer::pipelines::color_map::SetProxyIntensityForVertex().
getVerticesPtr()
std::vector< CCVector3 > & ccMesh::getVerticesPtr ()
Definition at line 2344 of file ecvMesh.cpp.
References getAssociatedCloud(), cloudViewer::PointCloudTpl< T >::getPoints(), LogError, and ccHObjectCaster::ToPointCloud().
GetVolume()
double ccMesh::GetVolume () const
Function that computes the volume of the mesh, under the condition that it is watertight and orientable. See Zhang and Chen, "Efficient feature extraction for 2D/3D objects in mesh representation", 2001.
Definition at line 1664 of file TriangleMeshFactory.cpp.
References LogError, and size.
hasAdjacencyList()
bool ccMesh::hasAdjacencyList () const inline
Returns true if the mesh contains adjacency normals.
Definition at line 712 of file ecvMesh.h.
hasColors()
bool ccMesh::hasColors () const override virtual
Returns whether colors are enabled or not.
Reimplemented from ccDrawableObject.
Definition at line 221 of file ecvMesh.cpp.
References ccDrawableObject::hasColors(), and m_associatedCloud.
Referenced by ccEntityAction::convertTextureToColor(), getVertexColorFromMaterial(), interpolateColors(), SelectByIndex(), cloudViewer::io::rpc::SetTriangleMesh(), and subdivide().
hasDisplayedScalarField()
bool ccMesh::hasDisplayedScalarField () const override virtual
Returns whether an active scalar field is available or not.
Reimplemented from ccDrawableObject.
Definition at line 233 of file ecvMesh.cpp.
References ccDrawableObject::hasDisplayedScalarField(), and m_associatedCloud.
hasEigenTextures()
bool ccMesh::hasEigenTextures () const inline
Returns true if the mesh has texture.
Definition at line 726 of file ecvMesh.h.
References a.
hasMaterials()
bool ccMesh::hasMaterials () const override virtual
Implements ccGenericMesh.
Definition at line 3713 of file ecvMesh.cpp.
References m_materials, m_triMtlIndexes, and m_triVertIndexes.
Referenced by convertMaterialsToVertexColors(), ccEntityAction::convertTextureToColor(), drawMeOnly(), getColorFromMaterial(), getVertexColorFromMaterial(), hasTextures(), PlyFilter::loadFile(), merge(), and ToFbxMesh().
hasNormals()
bool ccMesh::hasNormals () const override virtual
Returns whether normals are enabled or not.
Reimplemented from ccDrawableObject.
Definition at line 225 of file ecvMesh.cpp.
References hasTriNormals(), and HasVertexNormals().
Referenced by ccEntityAction::clearProperty(), cloneMesh(), cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::ConstructBuffers(), qCork::doAction(), interpolateNormals(), interpolateNormalsBC(), ccEntityAction::invertNormals(), laplacianSmooth(), VTKFilter::loadFile(), partialClone(), CommandInvertNormal::process(), SelectByIndex(), cloudViewer::io::rpc::SetTriangleMesh(), and subdivide().
hasPerTriangleMtlIndexes()
bool ccMesh::hasPerTriangleMtlIndexes () const inline
Returns whether this mesh as per-triangle material index.
Definition at line 421 of file ecvMesh.h.
Referenced by FromFbxMesh(), and ccPlane::SetQuadTexture().
hasPerTriangleTexCoordIndexes()
bool ccMesh::hasPerTriangleTexCoordIndexes () const inline override virtual
Returns whether this mesh as per-triangle triplets of tex coords indexes.
Implements ccGenericMesh.
Definition at line 484 of file ecvMesh.h.
Referenced by ccSubMesh::hasPerTriangleTexCoordIndexes(), ccPlane::SetQuadTexture(), and ToFbxMesh().
hasScalarFields()
bool ccMesh::hasScalarFields () const override virtual
Returns whether one or more scalar fields are instantiated.
WARNING: doesn't mean a scalar field is currently displayed (see ccDrawableObject::hasDisplayedScalarField).
Reimplemented from ccDrawableObject.
Definition at line 238 of file ecvMesh.cpp.
References ccDrawableObject::hasScalarFields(), and m_associatedCloud.
hasTextures()
bool ccMesh::hasTextures () const override virtual
Returns whether textures are available for this mesh.
Implements ccGenericMesh.
Definition at line 3703 of file ecvMesh.cpp.
References hasMaterials(), ccArray< Type, N, ComponentType >::isAllocated(), m_texCoordIndexes, m_texCoords, and m_triVertIndexes.
Referenced by drawMeOnly(), cloudViewer::io::rpc::SetTriangleMesh(), and ToFbxMesh().
hasTriangleMaterialIds()
bool ccMesh::hasTriangleMaterialIds () const inline
Definition at line 721 of file ecvMesh.h.
References cloudViewer::GenericMesh::hasTriangles(), and cloudViewer::GenericMesh::size().
HasTriangleNormals()
bool ccMesh::HasTriangleNormals () const inline
Definition at line 314 of file ecvMesh.h.
References ccGenericMesh::hasTriNormals().
Referenced by merge().
hasTriangleUvs()
bool ccMesh::hasTriangleUvs () const inline
Definition at line 717 of file ecvMesh.h.
References cloudViewer::GenericMesh::hasTriangles(), and cloudViewer::GenericMesh::size().
Referenced by cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::ConstructBuffers(), cloudViewer::t::geometry::TriangleMesh::FromLegacy(), SelectByIndex(), and cloudViewer::io::rpc::SetTriangleMesh().
hasTriNormals()
bool ccMesh::hasTriNormals () const override virtual
Returns whether the mesh has per-triangle normals.
Implements ccGenericMesh.
Definition at line 3589 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::isAllocated(), m_triNormalIndexes, m_triNormals, and m_triVertIndexes.
Referenced by ccGraphicalTransformationTool::apply(), ccEntityAction::clearProperty(), cloneMesh(), qCork::doAction(), drawMeOnly(), ccDBRoot::gatherRecursiveInformation(), getTriangleNormalIndexes(), getTriangleNorms(), hasNormals(), interpolateNormals(), interpolateNormalsBC(), laplacianSmooth(), VTKFilter::loadFile(), ccGenericPrimitive::operator+=(), partialClone(), VTKFilter::saveToFile(), SelectByIndex(), cloudViewer::io::rpc::SetTriangleMesh(), setTriangleNorm(), setTriangleNormalIndexes(), and subdivide().
HasVertexNormals()
bool ccMesh::HasVertexNormals () const
Definition at line 229 of file ecvMesh.cpp.
References ccDrawableObject::hasNormals(), and m_associatedCloud.
Referenced by hasNormals().
HasVertices()
bool ccMesh::HasVertices () const inline
Definition at line 208 of file ecvMesh.h.
Referenced by cloudViewer::t::geometry::TriangleMesh::FromLegacy(), and cloudViewer::io::ReadTriangleMesh().
interpolateColors() [1/2]
bool ccMesh::interpolateColors (const cloudViewer::VerticesIndexes & vertIndexes, const CCVector3 & P, ecvColor::Rgb & C) protected
Same as other 'interpolateColors' method with a set of 3 vertices indexes
Definition at line 4133 of file ecvMesh.cpp.
References ecvColor::RgbTpl< Type >::b, computeInterpolationWeights(), cloudViewer::utility::floor(), ecvColor::RgbTpl< Type >::g, ccGenericPointCloud::getPointColor(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, m_associatedCloud, ecvColor::RgbTpl< Type >::r, rgb, and Tuple3Tpl< Type >::u.
interpolateColors() [2/2]
bool ccMesh::interpolateColors (unsigned triIndex, const CCVector3 & P, ecvColor::Rgb & C) override virtual
Interpolates RGB colors inside a given triangle.
Parameters
triIndex triangle index
P point where to interpolate (should be inside the triangle!)
[out] C interpolated color
Returns
success
Implements ccGenericMesh.
Definition at line 4120 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::getValue(), hasColors(), m_triVertIndexes, and size().
Referenced by getColorFromMaterial(), ccSubMesh::interpolateColors(), and pushSubdivide().
interpolateNormals() [1/2]
bool ccMesh::interpolateNormals (const cloudViewer::VerticesIndexes & vertIndexes, const CCVector3d & w, CCVector3 & N, const Tuple3i * triNormIndexes = nullptr) protected
Same as other 'interpolateNormals' method with a set of 3 vertices indexes
Definition at line 4065 of file ecvMesh.cpp.
References ccNormalVectors::GetNormal(), ccGenericPointCloud::getPointNormal(), ccArray< Type, N, ComponentType >::getValue(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, m_associatedCloud, m_triNormals, Vector3Tpl< Type >::normalize(), Vector3Tpl< Type >::toDouble(), Vector3Tpl< Type >::toPC(), and Tuple3Tpl< Type >::u.
interpolateNormals() [2/2]
bool ccMesh::interpolateNormals (unsigned triIndex, const CCVector3 & P, CCVector3 & N) override virtual
Interpolates normal(s) inside a given triangle.
This method should be ideally overriden by the child class if normals are supported
Parameters
[in] triIndex triangle index
[in] P point where to interpolate (should be inside the triangle!)
[out] N interpolated normal
Returns
success
Reimplemented from cloudViewer::GenericIndexedMesh.
Definition at line 4050 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::getValue(), hasNormals(), hasTriNormals(), m_triNormalIndexes, m_triVertIndexes, and size().
Referenced by ccSubMesh::interpolateNormals(), and interpolateNormalsBC().
interpolateNormalsBC()
bool ccMesh::interpolateNormalsBC (unsigned triIndex, const CCVector3d & w, CCVector3 & N) override virtual
Interpolates normal(s) inside a given triangle.
Parameters
triIndex triangle index
w barycentric coordinates
[out] N interpolated normal
Returns
success
Implements ccGenericMesh.
Definition at line 4105 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::getValue(), hasNormals(), hasTriNormals(), interpolateNormals(), m_triNormalIndexes, m_triVertIndexes, and size().
Referenced by ccSubMesh::interpolateNormalsBC().
invertNormals()
void ccMesh::invertNormals ()
Inverts normals (if any)
Either the per-triangle normals, or the per-vertex ones
Definition at line 3288 of file ecvMesh.cpp.
References ccPointCloud::hasNormals(), ccPointCloud::invertNormals(), invertPerTriangleNormals(), m_associatedCloud, and m_triNormals.
Referenced by ccEntityAction::invertNormals(), and CommandInvertNormal::process().
invertPerTriangleNormals()
void ccMesh::invertPerTriangleNormals ()
Invert per-triangle normals.
Definition at line 3301 of file ecvMesh.cpp.
References ccNormalCompressor::InvertNormal(), and m_triNormals.
Referenced by invertNormals().
IsBoundingBoxIntersecting()
bool ccMesh::IsBoundingBoxIntersecting (const ccMesh & other) const
Function that tests if the bounding boxes of the triangle meshes are intersecting.
Definition at line 1020 of file TriangleMeshFactory.cpp.
References cloudViewer::utility::IntersectionTest::AABBAABB(), GetMaxBound(), and GetMinBound().
IsEdgeManifold()
bool ccMesh::IsEdgeManifold (bool allow_boundary_edges = true) const
Function that checks if the given triangle mesh is edge-manifold. A mesh is edge­-manifold if each edge is bounding either one or two triangles. If allow_boundary_edges is set to false, then this function returns false if there exists boundary edges.
Definition at line 909 of file TriangleMeshFactory.cpp.
References cloudViewer::t::geometry::GetEdgeToTrianglesMap().
IsEmpty()
virtual bool ccMesh::IsEmpty () const inline override virtual
Reimplemented from ccHObject.
Definition at line 735 of file ecvMesh.h.
References cloudViewer::GenericMesh::hasTriangles().
Referenced by cloudViewer::io::AutoReadEntity(), doReconstruct(), and main().
IsIntersecting()
bool ccMesh::IsIntersecting (const ccMesh & other) const
Function that tests if the triangle mesh intersects another triangle mesh. Tests each triangle against each other triangle.
Definition at line 1026 of file TriangleMeshFactory.cpp.
References getTriangle(), getVertice(), size, size(), and cloudViewer::utility::IntersectionTest::TriangleTriangle3d().
IsOrientable()
bool ccMesh::IsOrientable () const
Function that tests if the given triangle mesh is orientable, i.e. the triangles can oriented in such a way that all normals point towards the outside.
Definition at line 1157 of file TriangleMeshFactory.cpp.
References OrientTriangleHelper().
IsSelfIntersecting()
bool ccMesh::IsSelfIntersecting () const
Function that tests if the triangle mesh is self-intersecting. Tests each triangle pair for intersection.
Definition at line 1016 of file TriangleMeshFactory.cpp.
isSerializable()
bool ccMesh::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccGenericMesh.
Definition at line 139 of file ecvMesh.h.
IsVertexManifold()
bool ccMesh::IsVertexManifold () const
Function that checks if all vertices in the triangle mesh are manifold. A vertex is manifold if its star is edge‐manifold and edge‐connected. (Two or more faces connected only by a vertex and not by an edge.)
Definition at line 977 of file TriangleMeshFactory.cpp.
IsWatertight()
bool ccMesh::IsWatertight () const
Function that tests if the given triangle mesh is watertight by checking if it is vertex manifold and edge-manifold with no boundary edges, but not self-intersecting.
Definition at line 1162 of file TriangleMeshFactory.cpp.
laplacianSmooth()
bool ccMesh::laplacianSmooth (unsigned nbIteration = 100, PointCoordinateType factor = static_cast<PointCoordinateType>(0.01), ecvProgressDialog * progressCb = nullptr)
Laplacian smoothing.
Parameters
nbIteration smoothing iterations
factor smoothing 'force'
progressCb progress dialog callback
Definition at line 1013 of file ecvMesh.cpp.
References computeNormals(), getNextTriangleVertIndexes(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::GenericIndexedCloudPersist::getPointPersistentPtr(), hasNormals(), hasTriNormals(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, m_associatedCloud, ccHObject::notifyGeometryUpdate(), nProgress, cloudViewer::NormalizedProgress::oneStep(), placeIteratorAtBeginning(), ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), cloudViewer::GenericCloud::size(), size(), and ecvProgressDialog::start().
merge()
bool ccMesh::merge (const ccMesh * mesh, bool createSubMesh)
Merges another mesh into this one.
Parameters
mesh mesh to be merged in this one
createSubMesh whether to create a submesh entity corresponding to the added mesh
Returns
success
Definition at line 1788 of file ecvMesh.cpp.
References ccHObject::addChild(), ccMaterialSet::addMaterial(), addTriangle(), ccSubMesh::addTriangleIndex(), adjacency_list_, ccDrawableObject::colorsShown(), ccGenericMesh::enableStippling(), getAssociatedCloud(), ccObject::getName(), getTriangleVertIndexes(), ccArray< Type, N, ComponentType >::getValue(), hasMaterials(), HasTriangleNormals(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, ccObject::isA(), ccObject::isEnabled(), ccGenericMesh::isShownAsPoints(), ccGenericMesh::isShownAsWire(), ccDrawableObject::isVisible(), m_associatedCloud, m_materials, m_texCoordIndexes, m_texCoords, m_triMtlIndexes, m_triNormalIndexes, m_triNormals, ccGenericMesh::materialsShown(), normalsShown(), CV_TYPES::POINT_CLOUD, ccSubMesh::reserve(), reserve(), reservePerTriangleMtlIndexes(), reservePerTriangleNormalIndexes(), reservePerTriangleTexCoordIndexes(), ccArray< Type, N, ComponentType >::reserveSafe(), resize(), ccObject::setEnabled(), setMaterialSet(), ccObject::setName(), setTexCoordinatesTable(), setTriNormsTable(), ccDrawableObject::setVisible(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccGenericMesh::showMaterials(), ccGenericMesh::showNormals(), ccGenericMesh::showPoints(), ccDrawableObject::showSF(), ccGenericMesh::showTriNorms(), ccGenericMesh::showWired(), cloudViewer::GenericCloud::size(), size(), ccGenericMesh::stipplingEnabled(), textures_, triangle_material_ids_, triangle_uvs_, ccGenericMesh::triNormsShown(), Tuple3Tpl< Type >::u, and CVLog::Warning().
Referenced by cloudViewer::io::AutoReadEntity(), qVoxFallProcess::Compute(), operator+=(), and operator=().
MergeCloseVertices()
ccMesh & ccMesh::MergeCloseVertices (double eps)
Function that will merge close by vertices to a single one. The vertex position, normal and color will be the average of the vertices.
Parameters
eps defines the maximum distance of close by vertices. This function might help to close triangle soups.
Definition at line 309 of file TriangleMeshFactory.cpp.
References color, ecvColor::RgbTpl< Type >::FromEigen(), cloudViewer::PointCloudTpl< T >::getPoints(), LogDebug, normal, ccPointCloud::rgbColors(), cloudViewer::geometry::KDTreeFlann::SearchRadius(), ccPointCloud::setPointNormals(), std::swap(), and ccHObjectCaster::ToPointCloud().
mergeDuplicatedVertices()
bool ccMesh::mergeDuplicatedVertices (unsigned char octreeLevel = DefaultMergeDulicateVerticesLevel, QWidget * parentWidget = nullptr)
Merges duplicated vertices.
Definition at line 661 of file ecvMesh.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), cloudViewer::DgmOctree::build(), cloudViewer::DgmOctree::executeFunctionForAllCellsAtLevel(), ccPointCloud::From(), ccHObject::getChildIndex(), getTriangleVertIndexes(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, ccObject::isKindOf(), m_associatedCloud, octree, partialClone(), CV_TYPES::POINT_CLOUD, CVLog::Print(), ccHObject::removeChild(), cloudViewer::ReferenceCloud::reserve(), resize(), result, setAssociatedCloud(), cloudViewer::GenericCloud::size(), size(), swapTriangles(), TagDuplicatedVertices(), and CVLog::Warning().
Referenced by STEPFilter::importStepFile(), and STLFilter::loadFile().
minimumFileVersion_MeOnly()
short ccMesh::minimumFileVersion_MeOnly () const override protected virtual
Returns the minimum file version required to save this instance's own data To be overloaded (but still called ;) by subclass. Used internally by minimumFileVersion() to compute the overall minimum.
Reimplemented from ccGenericMesh.
Reimplemented in ccTorus, ccSphere, ccQuadric, and ccPlane.
Definition at line 3870 of file ecvMesh.cpp.
References ccSerializationHelper::GenericArrayToFileMinVersion(), and ccGenericMesh::minimumFileVersion_MeOnly().
Referenced by ccGenericPrimitive::minimumFileVersion_MeOnly().
NormalizeNormals()
ccMesh & ccMesh::NormalizeNormals ()
Normalize both triangle normals and vertex normals to length 1. Normalize point normals to length 1.
Definition at line 1400 of file TriangleMeshFactory.cpp.
References ccNormalVectors::GetNormalPtr(), ccPointCloud::hasNormals(), Vector3Tpl< Type >::normalize(), ccPointCloud::NormalizeNormals(), and ccHObjectCaster::ToPointCloud().
normalsAvailable()
bool ccMesh::normalsAvailable () const inline override virtual
Returns whether normals are available.
Reimplemented from ccGenericMesh.
Definition at line 215 of file ecvMesh.h.
References ccDrawableObject::hasNormals().
normalsShown()
bool ccMesh::normalsShown () const override virtual
Returns whether normals are shown or not.
Reimplemented from ccDrawableObject.
Definition at line 388 of file ecvMesh.cpp.
References ccDrawableObject::normalsShown(), and ccGenericMesh::triNormsShown().
Referenced by ccSubMesh::ccSubMesh(), cloneMesh(), createNewMeshFromSelection(), qCork::doAction(), cvSelectionExporter::exportFromSourceMesh(), ccGenericPrimitive::finishCloneJob(), ObjFilter::loadFile(), merge(), partialClone(), and subdivide().
onDeletionOf()
void ccMesh::onDeletionOf (const ccHObject * obj) override protected virtual
This method is called when another object is deleted.
For internal use.
Reimplemented from ccHObject.
Definition at line 215 of file ecvMesh.cpp.
References m_associatedCloud, ccHObject::onDeletionOf(), and setAssociatedCloud().
onUpdateOf()
void ccMesh::onUpdateOf (ccHObject * obj) override protected virtual
This method is called when another object (geometry) is updated.
For internal use.
Reimplemented from ccHObject.
Definition at line 206 of file ecvMesh.cpp.
References m_associatedCloud, m_bBox, ccHObject::notifyGeometryUpdate(), ccHObject::onUpdateOf(), and cloudViewer::BoundingBoxTpl< T >::setValidity().
operator+()
ccMesh ccMesh::operator+ (const ccMesh & mesh) const
Definition at line 165 of file ecvMesh.cpp.
References ccMesh().
operator+=()
ccMesh & ccMesh::operator+= (const ccMesh & mesh)
Definition at line 155 of file ecvMesh.cpp.
References adjacency_list_, CVLog::Error(), and merge().
operator=()
ccMesh & ccMesh::operator= (const ccMesh & mesh)
Definition at line 133 of file ecvMesh.cpp.
References ccHObject::addChild(), adjacency_list_, ccPointCloud::clear(), getAssociatedCloud(), merge(), resize(), setAssociatedCloud(), ccObject::setEnabled(), ccObject::setLocked(), ccObject::setName(), and ccHObjectCaster::ToPointCloud().
OrientTriangles()
bool ccMesh::OrientTriangles ()
If the mesh is orientable then this function rearranges the triangles such that all normals point towards the outside/inside.
Definition at line 1166 of file TriangleMeshFactory.cpp.
References OrientTriangleHelper(), and std::swap().
PaintUniformColor()
ccMesh & ccMesh::PaintUniformColor (const Eigen::Vector3d & color)
Assigns each vertex in the ccMesh the same color.
Parameters
color RGB colors of vertices.
Definition at line 398 of file TriangleMeshFactory.cpp.
References color, ccPointCloud::PaintUniformColor(), CV_TYPES::POINT_CLOUD, and ccHObjectCaster::ToPointCloud().
partialClone()
ccMesh * ccMesh::partialClone (const std::vector< unsigned > & triangleIndices, int * warnings = nullptr) const
Creates a new mesh from a selection of triangles (partial clone)
Similar to ccPointCloud::partialClone but for meshes.
Parameters
triangleIndices Indices of triangles to include in the partial clone
warnings [optional] to store warnings
Returns
a partial clone of this mesh (or nullptr if an error occurred)
Definition at line 1347 of file ecvMesh.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), addTriangle(), addTriangleMtlIndex(), addTriangleNormalIndexes(), addTriangleTexCoordIndexes(), ccMesh(), ccMaterialSet::clone(), NormsIndexesTableType::clone(), TextureCoordsContainer::clone(), ccGenericPointCloud::clone(), ccDrawableObject::colorsShown(), computeNormals(), CVLog::Error(), getMaterialSet(), ccObject::getName(), getTriangleMtlIndex(), getTriangleNormalIndexes(), getTriangleTexCoordinatesIndexes(), getTriangleVertIndexes(), hasNormals(), hasTriNormals(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, ccGenericMesh::importParametersFrom(), ccObject::isA(), ccObject::isEnabled(), ccDrawableObject::isVisible(), m_associatedCloud, m_materials, m_texCoordIndexes, m_texCoords, m_triMtlIndexes, m_triNormalIndexes, m_triNormals, ccGenericMesh::materialsShown(), normalsShown(), CV_TYPES::POINT_CLOUD, CVLog::Print(), removePerTriangleMtlIndexes(), removePerTriangleNormalIndexes(), removePerTriangleTexCoordIndexes(), reserve(), cloudViewer::ReferenceCloud::reserve(), reservePerTriangleMtlIndexes(), reservePerTriangleNormalIndexes(), reservePerTriangleTexCoordIndexes(), ccObject::setEnabled(), setMaterialSet(), ccObject::setName(), setTexCoordinatesTable(), setTriNormsTable(), ccDrawableObject::setVisible(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccGenericMesh::showMaterials(), ccGenericMesh::showNormals(), ccDrawableObject::showSF(), size(), and CVLog::Warning().
Referenced by cloneMesh(), cvSelectionExporter::exportFromSourceMesh(), and mergeDuplicatedVertices().
placeIteratorAtBeginning()
void ccMesh::placeIteratorAtBeginning () override virtual
Places the mesh iterator at the beginning.
Virtual method to handle the mesh global iterator
Implements cloudViewer::GenericMesh.
Definition at line 2163 of file ecvMesh.cpp.
References m_globalIterator.
Referenced by cloneMesh(), qVoxFallProcess::Compute(), computePerVertexNormals(), convertMaterialsToVertexColors(), laplacianSmooth(), processScalarField(), and VTKFilter::saveToFile().
processScalarField()
bool ccMesh::processScalarField (MESH_SCALAR_FIELD_PROCESS process)
Applies process to the mesh scalar field (the one associated to its vertices in fact) A very simple smoothing/enhancement algorithm based on each vertex direct neighbours. Prior to calling this method, one should check first that the vertices are associated to a scalar field. Warning: the processed scalar field must be enabled for both INPUT & OUTPUT! (see ccGenericCloud::setCurrentScalarField)
Parameters
process either 'smooth' or 'enhance'
Definition at line 392 of file ecvMesh.cpp.
References count, ENHANCE_MESH_SF, getNextTriangleVertIndexes(), cloudViewer::GenericCloud::getPointScalarValue(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, cloudViewer::GenericCloud::isScalarFieldEnabled(), m_associatedCloud, placeIteratorAtBeginning(), cloudViewer::GenericCloud::setPointScalarValue(), cloudViewer::GenericCloud::size(), size(), and SMOOTH_MESH_SF.
Referenced by ccEntityAction::processMeshSF().
pushSubdivide()
bool ccMesh::pushSubdivide (unsigned indexA, unsigned indexB, unsigned indexC) protected
Used internally by 'subdivide'.
Definition at line 4343 of file ecvMesh.cpp.
References cloudViewer::PointCloudTpl< T >::addPoint(), ccPointCloud::addRGBColor(), addTriangle(), cloudViewer::PointCloudTpl< T >::capacity(), capacity(), CVLog::Error(), GenerateKey(), getAssociatedCloud(), cloudViewer::PointCloudTpl< T >::getPoint(), ccPointCloud::hasColors(), interpolateColors(), ccObject::isA(), CV_TYPES::POINT_CLOUD, reserve(), ccPointCloud::reserve(), s_alreadyCreatedVertices, s_defaultSubdivideGrowRate, s_maxSubdivideArea, cloudViewer::PointCloudTpl< T >::size(), size(), and ZERO_TOLERANCE_F.
Referenced by subdivide().
refreshBB()
void ccMesh::refreshBB () override virtual
Forces bounding-box update.
Implements ccGenericMesh.
Definition at line 2387 of file ecvMesh.cpp.
References cloudViewer::BoundingBoxTpl< T >::add(), cloudViewer::BoundingBoxTpl< T >::clear(), count, cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, cloudViewer::BoundingBoxTpl< T >::isValid(), m_associatedCloud, m_bBox, m_triVertIndexes, ccHObject::notifyGeometryUpdate(), and cloudViewer::GenericCloud::size().
Referenced by getBoundingBox(), and getOwnBB().
RemoveDegenerateTriangles()
ccMesh & ccMesh::RemoveDegenerateTriangles ()
Function that removes degenerate triangles, i.e., triangles that reference a single vertex multiple times in a single triangle.
They are usually the product of removing duplicated vertices.
Definition at line 193 of file TriangleMeshFactory.cpp.
References LogDebug, LogWarning, and size.
Referenced by cloudViewer::geometry::HalfEdgeTriangleMesh::CreateFromTriangleMesh().
RemoveDuplicatedTriangles()
ccMesh & ccMesh::RemoveDuplicatedTriangles ()
Function that removes duplicated triangles, i.e., removes triangles that reference the same three vertices, independent of their order.
Definition at line 84 of file TriangleMeshFactory.cpp.
References LogDebug, LogWarning, and size.
Referenced by cloudViewer::geometry::HalfEdgeTriangleMesh::CreateFromTriangleMesh().
RemoveDuplicatedVertices()
ccMesh & ccMesh::RemoveDuplicatedVertices ()
Function that removes duplicated verties, i.e., vertices that have identical coordinates.
Definition at line 31 of file TriangleMeshFactory.cpp.
References LogDebug, ccPointCloud::resize(), and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::geometry::HalfEdgeTriangleMesh::CreateFromTriangleMesh().
RemoveNonManifoldEdges()
ccMesh & ccMesh::RemoveNonManifoldEdges ()
Function that removes all non-manifold edges, by successively deleting triangles with the smallest surface area adjacent to the non-manifold edge until the number of adjacent triangles to the edge is <= 2.
Definition at line 225 of file TriangleMeshFactory.cpp.
References cloudViewer::t::geometry::GetEdgeToTrianglesMap(), LogWarning, and size.
removePerTriangleMtlIndexes()
void ccMesh::removePerTriangleMtlIndexes ()
Removes any per-triangle material indexes.
Definition at line 3746 of file ecvMesh.cpp.
References m_triMtlIndexes, and CCShareable::release().
Referenced by cloneMesh(), createNewMeshFromSelection(), PlyFilter::loadFile(), partialClone(), setMaterialSet(), and ccPlane::SetQuadTexture().
removePerTriangleNormalIndexes()
void ccMesh::removePerTriangleNormalIndexes ()
Removes any per-triangle triplets of normal indexes.
Definition at line 3323 of file ecvMesh.cpp.
References m_triNormalIndexes, and CCShareable::release().
Referenced by ccBox::buildUp(), ccCoordinateSystem::buildUp(), cloneMesh(), computePerTriangleNormals(), createNewMeshFromSelection(), ccGenericPrimitive::init(), STLFilter::loadASCIIFile(), STLFilter::loadBinaryFile(), partialClone(), and setTriNormsTable().
removePerTriangleTexCoordIndexes()
void ccMesh::removePerTriangleTexCoordIndexes ()
Remove per-triangle tex coords indexes.
Definition at line 3671 of file ecvMesh.cpp.
References m_texCoordIndexes, and CCShareable::release().
Referenced by cloneMesh(), DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertProfileToMesh(), createNewMeshFromSelection(), PlyFilter::loadFile(), partialClone(), ccPlane::SetQuadTexture(), and setTexCoordinatesTable().
removeTriangles()
void ccMesh::removeTriangles (size_t index)
Definition at line 2583 of file ecvMesh.cpp.
References LogWarning, m_texCoordIndexes, m_triMtlIndexes, m_triNormalIndexes, m_triVertIndexes, and size().
RemoveTrianglesByIndex()
void ccMesh::RemoveTrianglesByIndex (const std::vector< size_t > & triangle_indices)
This function removes the triangles with index in triangle_indices. Call RemoveUnreferencedVertices to clean up vertices afterwards.
Parameters
triangle_indices Indices of the triangles that should be removed.
Definition at line 1243 of file TriangleMeshFactory.cpp.
References LogWarning, and size.
RemoveTrianglesByMask()
void ccMesh::RemoveTrianglesByMask (const std::vector< bool > & triangle_mask)
This function removes the triangles that are masked in triangle_mask. Call RemoveUnreferencedVertices to clean up vertices afterwards.
Parameters
triangle_mask Mask of triangles that should be removed. Should have same size as triangles_.
Definition at line 1260 of file TriangleMeshFactory.cpp.
References LogError, and size.
RemoveUnreferencedVertices()
ccMesh & ccMesh::RemoveUnreferencedVertices ()
This function removes vertices from the triangle mesh that are not referenced in any triangle of the mesh.
Definition at line 139 of file TriangleMeshFactory.cpp.
References LogDebug, ccPointCloud::resize(), and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::geometry::HalfEdgeTriangleMesh::CreateFromTriangleMesh().
RemoveVerticesByIndex()
void ccMesh::RemoveVerticesByIndex (const std::vector< size_t > & vertex_indices)
This function removes the vertices with index in vertex_indices. Note that also all triangles associated with the vertices are removeds.
Parameters
triangle_indices Indices of the triangles that should be removed.
Definition at line 1283 of file TriangleMeshFactory.cpp.
References LogWarning.
RemoveVerticesByMask()
void ccMesh::RemoveVerticesByMask (const std::vector< bool > & vertex_mask)
This function removes the vertices that are masked in vertex_mask. Note that also all triangles associated with the vertices are removed..
Parameters
vertex_mask Mask of vertices that should be removed. Should have same size as vertices_.
Definition at line 1299 of file TriangleMeshFactory.cpp.
References cloudViewer::PointCloudTpl< T >::getPoint(), ccPointCloud::getPointColor(), ccPointCloud::getPointNormal(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), cloudViewer::VerticesIndexes::i, LogError, ccPointCloud::resize(), cloudViewer::PointCloudTpl< T >::setPoint(), ccPointCloud::setPointColor(), ccPointCloud::setPointNormal(), cloudViewer::PointCloudTpl< T >::size(), size, and ccHObjectCaster::ToPointCloud().
reserve()
bool ccMesh::reserve (std::size_t n)
Reserves the memory to store the vertex indexes (3 per triangle)
Parameters
n the number of triangles to reserve
Returns
true if the method succeeds, false otherwise
Definition at line 2475 of file ecvMesh.cpp.
References m_texCoordIndexes, m_triMtlIndexes, m_triNormalIndexes, m_triVertIndexes, and ccArray< Type, N, ComponentType >::reserveSafe().
Referenced by addTriangleNorms(), ccMesh(), MeshWrapper< Real >::checkMeshCapacity(), cloneMesh(), pcl2cc::Convert(), DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertProfileToMesh(), vtk2cc::ConvertToMesh(), face_cb(), FromFbxMesh(), STEPFilter::importStepFile(), ccGenericPrimitive::init(), STLFilter::loadASCIIFile(), STLFilter::loadBinaryFile(), CSVMatrixFilter::loadFile(), ObjFilter::loadFile(), OFFFilter::loadFile(), VTKFilter::loadFile(), DRCFilter::loadFile(), PlyFilter::loadFile(), merge(), ccGenericPrimitive::operator+=(), partialClone(), pushSubdivide(), subdivide(), Cloth::toMesh(), and ccPointCloud::triangulateGrid().
reserveAssociatedCloud()
bool ccMesh::reserveAssociatedCloud (std::size_t n, bool init_color = false, bool init_normal = false)
Definition at line 2539 of file ecvMesh.cpp.
References LogError, LogWarning, m_associatedCloud, ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveThePointsTable(), ccPointCloud::reserveTheRGBTable(), and ccHObjectCaster::ToPointCloud().
Referenced by cloudViewer::io::ReadTriangleMeshUsingASSIMP().
reservePerTriangleMtlIndexes()
bool ccMesh::reservePerTriangleMtlIndexes ()
Reserves memory to store per-triangle material index.
Before adding per-triangle material index to the mesh (with ccMesh::addTriangleMtlIndex()) be sure to reserve the necessary amount of memory with this method. This method reserves memory for as many material descriptors as the number of triangles in the mesh (effictively stored or reserved - a call to ccMesh::reserve prior to this one is mandatory).
Returns
true if ok, false if there's not enough memory
Definition at line 3734 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::isAllocated(), CCShareable::link(), m_triMtlIndexes, m_triVertIndexes, and ccArray< Type, N, ComponentType >::reserveSafe().
Referenced by cloneMesh(), DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertProfileToMesh(), createNewMeshFromSelection(), ccCropTool::Crop(), FromFbxMesh(), CSVMatrixFilter::loadFile(), ObjFilter::loadFile(), PlyFilter::loadFile(), merge(), partialClone(), and ccPlane::SetQuadTexture().
reservePerTriangleNormalIndexes()
bool ccMesh::reservePerTriangleNormalIndexes ()
Reserves memory to store per-triangle triplets of normal indexes.
Before adding per-triangle normal indexes triplets to the mesh (with ccMesh::addTriangleNormalsIndexes()) be sure to reserve the necessary amount of memory with this method. This method reserves memory for as many normals indexes triplets as the number of triangles in the mesh (effictively stored or reserved - a call to ccMesh::reserve prior to this one is mandatory).
Returns
true if ok, false if there's not enough memory
Definition at line 3328 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::isAllocated(), CCShareable::link(), m_triNormalIndexes, m_triVertIndexes, and ccArray< Type, N, ComponentType >::reserveSafe().
Referenced by addTriangleNorm(), cloneMesh(), computePerTriangleNormals(), createNewMeshFromSelection(), FromFbxMesh(), ccGenericPrimitive::init(), STLFilter::loadASCIIFile(), STLFilter::loadBinaryFile(), ObjFilter::loadFile(), VTKFilter::loadFile(), merge(), ccGenericPrimitive::operator+=(), and partialClone().
reservePerTriangleTexCoordIndexes()
bool ccMesh::reservePerTriangleTexCoordIndexes ()
Reserves memory to store per-triangle triplets of tex coords indexes.
Before adding per-triangle tex coords indexes triplets to the mesh (with ccMesh::addTriangleTexCoordIndexes()) be sure to reserve the necessary amount of memory with this method. This method reserves memory for as many tex coords indexes triplets as the number of triangles in the mesh (effictively stored or reserved - a call to ccMesh::reserve prior to this one is mandatory).
Returns
true if ok, false if there's not enough memory
Definition at line 3659 of file ecvMesh.cpp.
References ccArray< Type, N, ComponentType >::isAllocated(), CCShareable::link(), m_texCoordIndexes, m_triVertIndexes, and ccArray< Type, N, ComponentType >::reserveSafe().
Referenced by cloneMesh(), DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertProfileToMesh(), createNewMeshFromSelection(), FromFbxMesh(), CSVMatrixFilter::loadFile(), ObjFilter::loadFile(), PlyFilter::loadFile(), merge(), partialClone(), and ccPlane::SetQuadTexture().
resize()
bool ccMesh::resize (size_t n)
Resizes the array of vertex indexes (3 per triangle)
If the new number of elements is smaller than the actual size, the overflooding elements will be deleted.
Parameters
n the new number of triangles
Returns
true if the method succeeds, false otherwise
Definition at line 2488 of file ecvMesh.cpp.
References m_bBox, m_texCoordIndexes, m_triMtlIndexes, m_triNormalIndexes, m_triVertIndexes, ccHObject::notifyGeometryUpdate(), ccArray< Type, N, ComponentType >::resizeSafe(), and cloudViewer::BoundingBoxTpl< T >::setValidity().
Referenced by clear(), createNewMeshFromSelection(), PlyFilter::loadFile(), merge(), mergeDuplicatedVertices(), operator=(), setTriangleNorms(), and setTriangles().
resizeAssociatedCloud()
bool ccMesh::resizeAssociatedCloud (std::size_t n)
Definition at line 2513 of file ecvMesh.cpp.
References ccPointCloud::hasColors(), ccPointCloud::hasNormals(), LogError, LogWarning, m_associatedCloud, ccPointCloud::resize(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), and ccHObjectCaster::ToPointCloud().
Rotate()
ccMesh & ccMesh::Rotate (const Eigen::Matrix3d & R, const Eigen::Vector3d & center) override virtual
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
Parameters
R A 3x3 rotation matrix
center Rotation center that is used for the rotation.
Reimplemented from ccHObject.
Definition at line 882 of file ecvMesh.cpp.
References ccPointCloud::applyRigidTransformation(), m_associatedCloud, ccGLMatrixTpl< T >::setRotation(), ccGLMatrixTpl< T >::shiftRotationCenter(), ccHObjectCaster::ToPointCloud(), and transformTriNormals().
Referenced by ccFacet::Rotate().
SamplePointsPoissonDisk()
std::shared_ptr< ccPointCloud > ccMesh::SamplePointsPoissonDisk (size_t number_of_points, double init_factor = 5, const std::shared_ptr< ccPointCloud > pcl_init = nullptr, bool use_triangle_normal = false, int seed = -1)
Function to sample number_of_points points (blue noise). Based on the method presented in Yuksel, "Sample Elimination for Generating Poisson Disk Sample Sets", EUROGRAPHICS, 2015 The PointCloud pcl_init is used for sample elimination if given, otherwise a PointCloud is first uniformly sampled with init_number_of_points x number_of_points number of points. use_triangle_normal Set to true to assign the triangle normals to the returned points instead of the interpolated vertex normals. The triangle normals will be computed and added to the mesh if necessary. seed Sets the seed value used in the random generator, set to -1 to use a random seed value with each function call.
Definition at line 1431 of file TriangleMeshFactory.cpp.
References a, LogError, cloudViewer::geometry::KDTreeFlann::SearchRadius(), and size.
SamplePointsUniformly()
std::shared_ptr< ccPointCloud > ccMesh::SamplePointsUniformly (size_t number_of_points, bool use_triangle_normal = false, int seed = -1)
Function to sample
Parameters
number_of_points points uniformly from the mesh.
use_triangle_normal Set to true to assign the triangle normals to the returned points instead of the interpolated vertex normals. The triangle normals will be computed and added to the mesh if necessary.
seed Sets the seed value used in the random generator, set to -1 to use a random seed value with each function call.
Definition at line 1831 of file TriangleMeshFactory.cpp.
References LogError, and size.
SamplePointsUniformlyImpl()
std::shared_ptr< ccPointCloud > ccMesh::SamplePointsUniformlyImpl (size_t number_of_points, std::vector< double > & triangle_areas, double surface_area, bool use_triangle_normal, int seed)
Function to sample
Parameters
number_of_points points uniformly from the mesh.
Definition at line 1720 of file TriangleMeshFactory.cpp.
References a, ccEntityAction::computeNormals(), ccPointCloud::getEigenColor(), ccPointCloud::getEigenNormal(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, size, and uv.
Scale()
ccMesh & ccMesh::Scale (const double s, const Eigen::Vector3d & center) override virtual
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
Parameters
scale The scale parameter that is multiplied to the points/vertices of the geometry.
center Scale center that is used to resize the geometry.
Reimplemented from ccHObject.
Definition at line 872 of file ecvMesh.cpp.
References m_associatedCloud, ccPointCloud::Scale(), and ccHObjectCaster::ToPointCloud().
Referenced by ccFacet::Scale().
SelectByIndex()
std::shared_ptr< ccMesh > ccMesh::SelectByIndex (const std::vector< size_t > & indices, bool cleanup = true) const
Function to select points from input ccMesh into output ccMesh Vertices with indices in indices are selected.
Parameters
indices defines Indices of vertices to be selected.
cleanup If true it automatically calls ccMesh::RemoveDuplicatedVertices, ccMesh::RemoveDuplicatedTriangles, ccMesh::RemoveUnreferencedVertices, and ccMesh::RemoveDegenerateTriangles
Definition at line 898 of file ecvMesh.cpp.
References ccPointCloud::addNorm(), cloudViewer::PointCloudTpl< T >::addPoint(), ccPointCloud::addRGBColor(), getAssociatedCloud(), getTriangleNorm(), getTriangleVertIndexes(), getVerticeSize(), hasColors(), ccPointCloud::hasColors(), hasNormals(), ccPointCloud::hasNormals(), hasTriangleUvs(), hasTriNormals(), LogDebug, LogWarning, normals, ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveTheRGBTable(), ccObject::setEnabled(), ccObject::setLocked(), ccPointCloud::shrinkToFit(), and size().
Referenced by Crop().
setAssociatedCloud()
void ccMesh::setAssociatedCloud (ccGenericPointCloud * cloud)
Sets the associated vertices cloud (warning)
Definition at line 169 of file ecvMesh.cpp.
References ccHObject::addDependency(), ccHObject::DP_NOTIFY_OTHER_ON_DELETE, ccHObject::DP_NOTIFY_OTHER_ON_UPDATE, m_associatedCloud, m_bBox, and cloudViewer::BoundingBoxTpl< T >::setValidity().
Referenced by ccMesh(), define_ccMesh(), mergeDuplicatedVertices(), onDeletionOf(), and operator=().
setEigenVertices()
void ccMesh::setEigenVertices (const std::vector< Eigen::Vector3d > & vertices)
Definition at line 2361 of file ecvMesh.cpp.
References m_associatedCloud, cloudViewer::PointCloudTpl< T >::setEigenPoints(), cloudViewer::GenericCloud::size(), and ccHObjectCaster::ToPointCloud().
Referenced by ccMesh().
setMaterialSet()
void ccMesh::setMaterialSet (ccMaterialSet * materialSet, bool autoReleaseOldMaterialSet = true)
Sets associated material set (may be shared)
Definition at line 492 of file ecvMesh.cpp.
References ccHObject::addChild(), ccHObject::getChildIndex(), CCShareable::link(), m_materials, CCShareable::release(), ccHObject::removeChild(), and removePerTriangleMtlIndexes().
Referenced by cloneMesh(), DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertProfileToMesh(), createNewMeshFromSelection(), ccCropTool::Crop(), FromFbxMesh(), ObjFilter::loadFile(), DRCFilter::loadFile(), PlyFilter::loadFile(), merge(), partialClone(), ccPlane::SetQuadTexture(), GrainsAsEllipsoids::updateMeshAndLineSet(), and ~ccMesh().
setTexCoordinatesTable()
void ccMesh::setTexCoordinatesTable (TextureCoordsContainer * texCoordsTable, bool autoReleaseOldTable = true)
Sets per-triangle texture coordinates array (may be shared)
Definition at line 3598 of file ecvMesh.cpp.
References ccHObject::addChild(), ccHObject::getChildIndex(), CCShareable::link(), m_texCoords, CCShareable::release(), ccHObject::removeChild(), and removePerTriangleTexCoordIndexes().
Referenced by cloneMesh(), DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertProfileToMesh(), createNewMeshFromSelection(), ccCropTool::Crop(), FromFbxMesh(), CSVMatrixFilter::loadFile(), ObjFilter::loadFile(), DRCFilter::loadFile(), PlyFilter::loadFile(), merge(), partialClone(), ccPlane::SetQuadTexture(), and ~ccMesh().
setTriangle()
void ccMesh::setTriangle (size_t index, const Eigen::Vector3i & triangle)
Definition at line 2436 of file ecvMesh.cpp.
References LogWarning, and m_triVertIndexes.
Referenced by setTriangles().
setTriangleMtlIndex()
void ccMesh::setTriangleMtlIndex (unsigned triangleIndex, int mtlIndex)
Sets triangle material indexes.
Cf. ccMesh::reservePerTriangleMtlIndexes.
Parameters
triangleIndex triangle index
mtlIndex triangle material index
Definition at line 3756 of file ecvMesh.cpp.
References m_triMtlIndexes, and ccArray< Type, N, ComponentType >::setValue().
Referenced by ccCropTool::Crop().
setTriangleMtlIndexesTable()
void ccMesh::setTriangleMtlIndexesTable (triangleMaterialIndexesSet * matIndexesTable, bool autoReleaseOldTable = true)
Sets per-triangle material indexes array.
Definition at line 3718 of file ecvMesh.cpp.
References CCShareable::link(), m_triMtlIndexes, and CCShareable::release().
Referenced by PlyFilter::loadFile().
setTriangleNorm()
bool ccMesh::setTriangleNorm (size_t index, const Eigen::Vector3d & triangle_normal)
Definition at line 3483 of file ecvMesh.cpp.
References Vector3Tpl< PointCoordinateType >::fromArray(), ccNormalVectors::GetNormIndex(), hasTriNormals(), m_triNormals, and setTriangleNormalIndexes().
Referenced by setTriangleNorms().
setTriangleNormalIndexes() [1/2]
bool ccMesh::setTriangleNormalIndexes (size_t triangleIndex, CompressedNormType value)
Definition at line 3495 of file ecvMesh.cpp.
References hasTriNormals(), m_triNormals, and ccArray< Type, N, ComponentType >::setValue().
Referenced by setTriangleNorm().
setTriangleNormalIndexes() [2/2]
void ccMesh::setTriangleNormalIndexes (unsigned triangleIndex, int i1, int i2, int i3)
Sets a triplet of normal indexes for a given triangle.
Parameters
triangleIndex triangle index
i1 first vertex normal index
i2 second vertex normal index
i3 third vertex normal index
Definition at line 3345 of file ecvMesh.cpp.
References m_triNormalIndexes, and ccArray< Type, N, ComponentType >::setValue().
setTriangleNorms()
bool ccMesh::setTriangleNorms (const std::vector< Eigen::Vector3d > & triangle_normals)
Definition at line 3550 of file ecvMesh.cpp.
References LogWarning, m_triNormals, resize(), ccArray< Type, N, ComponentType >::resizeSafe(), and setTriangleNorm().
setTriangles()
void ccMesh::setTriangles (const std::vector< Eigen::Vector3i > & triangles)
Definition at line 2455 of file ecvMesh.cpp.
References resize(), setTriangle(), and size().
Referenced by ccMesh().
setTriangleTexCoordIndexes()
void ccMesh::setTriangleTexCoordIndexes (unsigned triangleIndex, int i1, int i2, int i3)
Sets a triplet of tex coords indexes for a given triangle.
Parameters
triangleIndex triangle index
i1 first vertex tex coords index
i2 second vertex tex coords index
i3 third vertex tex coords index
Definition at line 3683 of file ecvMesh.cpp.
References m_texCoordIndexes, and ccArray< Type, N, ComponentType >::setValue().
setTriNormsTable()
void ccMesh::setTriNormsTable (NormsIndexesTableType * triNormsTable, bool autoReleaseOldTable = true)
Sets per-triangle normals array (may be shared)
Definition at line 470 of file ecvMesh.cpp.
References ccHObject::addChild(), ccHObject::getChildIndex(), CCShareable::link(), m_triNormals, CCShareable::release(), ccHObject::removeChild(), and removePerTriangleNormalIndexes().
Referenced by addTriangleNorm(), cloneMesh(), computePerTriangleNormals(), createNewMeshFromSelection(), FromFbxMesh(), ccGenericPrimitive::init(), STLFilter::loadASCIIFile(), STLFilter::loadBinaryFile(), ObjFilter::loadFile(), STLFilter::loadFile(), VTKFilter::loadFile(), merge(), ccGenericPrimitive::operator+=(), and partialClone().
setVertexColor()
void ccMesh::setVertexColor (size_t index, const Eigen::Vector3d & color)
Definition at line 2282 of file ecvMesh.cpp.
References color, m_associatedCloud, ccPointCloud::setPointColor(), and ccHObjectCaster::ToPointCloud().
setVertexColors()
void ccMesh::setVertexColors (const std::vector< Eigen::Vector3d > & colors)
Definition at line 2304 of file ecvMesh.cpp.
References colors, m_associatedCloud, ccPointCloud::setEigenColors(), cloudViewer::GenericCloud::size(), and ccHObjectCaster::ToPointCloud().
setVertexNormal()
void ccMesh::setVertexNormal (size_t index, const Eigen::Vector3d & normal)
Definition at line 2237 of file ecvMesh.cpp.
References m_associatedCloud, normal, ccPointCloud::setPointNormal(), and ccHObjectCaster::ToPointCloud().
setVertexNormals()
void ccMesh::setVertexNormals (const std::vector< Eigen::Vector3d > & normals)
Definition at line 2259 of file ecvMesh.cpp.
References m_associatedCloud, normals, ccPointCloud::setEigenNormals(), cloudViewer::GenericCloud::size(), and ccHObjectCaster::ToPointCloud().
setVertice()
void ccMesh::setVertice (size_t index, const Eigen::Vector3d & vertice)
Definition at line 2222 of file ecvMesh.cpp.
References getAssociatedCloud(), cloudViewer::PointCloudTpl< T >::setEigenPoint(), and ccHObjectCaster::ToPointCloud().
shiftTriangleIndexes()
void ccMesh::shiftTriangleIndexes (unsigned shift)
Shifts all triangles indexes.
Parameters
shift index shift (positive)
Definition at line 3279 of file ecvMesh.cpp.
References cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, and m_triVertIndexes.
Referenced by ccPointCloud::append().
showNormals_extended()
virtual void ccMesh::showNormals_extended (bool p) inline protected virtual
Definition at line 1487 of file ecvMesh.h.
Referenced by computePerTriangleNormals(), and computePerVertexNormals().
shrinkToFit()
void ccMesh::shrinkToFit () inline
Removes unused capacity.
Definition at line 302 of file ecvMesh.h.
References ccGenericMesh::capacity(), and cloudViewer::GenericMesh::size().
Referenced by pcl2cc::Convert(), vtk2cc::ConvertToMesh(), STEPFilter::importStepFile(), ObjFilter::loadFile(), OFFFilter::loadFile(), STLFilter::loadFile(), VTKFilter::loadFile(), DRCFilter::loadFile(), PlyFilter::loadFile(), main(), subdivide(), and ccPointCloud::triangulateGrid().
shrinkVertexToFit()
void ccMesh::shrinkVertexToFit ()
Definition at line 2568 of file ecvMesh.cpp.
References m_associatedCloud, ccPointCloud::shrinkToFit(), and ccHObjectCaster::ToPointCloud().
SimplifyQuadricDecimation()
std::shared_ptr< ccMesh > ccMesh::SimplifyQuadricDecimation (int target_number_of_triangles, double maximum_error = std::numeric_limits<double>::infinity(), double boundary_weight = 1.0) const
Function to simplify mesh using Quadric Error Metric Decimation by Garland and Heckbert.
Parameters
target_number_of_triangles defines the number of triangles that the simplified mesh should have. It is not guaranteed that this number will be reached.
maximum_error defines the maximum error where a vertex is allowed to be merged
boundary_weight a weight applied to edge vertices used to preserve boundaries
Definition at line 272 of file TriangleMeshSimplification.cpp.
References a, Quadric::Eval(), cloudViewer::t::geometry::GetEdgeToTrianglesMap(), ccPointCloud::getEigenColor(), ccPointCloud::getEigenNormal(), cloudViewer::PointCloudTpl< T >::getEigenPoint(), cloudViewer::PointCloudTpl< T >::getPoint(), ccPointCloud::getPointColor(), ccPointCloud::getPointNormal(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), cloudViewer::VerticesIndexes::i, cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, Quadric::IsInvertible(), LogError, LogWarning, Quadric::Minimum(), ccPointCloud::resize(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), ccPointCloud::setEigenColor(), ccPointCloud::setEigenNormal(), ccObject::setEnabled(), ccObject::setLocked(), cloudViewer::PointCloudTpl< T >::setPoint(), ccPointCloud::setPointColor(), ccPointCloud::setPointNormal(), cloudViewer::PointCloudTpl< T >::size(), size, and ccHObjectCaster::ToPointCloud().
SimplifyVertexClustering()
std::shared_ptr< ccMesh > ccMesh::SimplifyVertexClustering (double voxel_size, SimplificationContraction contraction = SimplificationContraction::Average) const
Function to simplify mesh using Vertex Clustering. The result can be a non-manifold mesh.
Parameters
voxel_size - The size of the voxel within vertices are pooled.
contraction - Method to aggregate vertex information. Average computes a simple average, Quadric minimizes the distance to the adjacent planes.
Definition at line 75 of file TriangleMeshSimplification.cpp.
References cloudViewer::utility::floor(), ccPointCloud::getEigenColor(), ccPointCloud::getEigenNormal(), cloudViewer::PointCloudTpl< T >::getEigenPoint(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, Quadric::IsInvertible(), LogError, LogWarning, Quadric::Minimum(), ccPointCloud::resize(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), ccObject::setEnabled(), ccObject::setLocked(), cloudViewer::PointCloudTpl< T >::setPoint(), ccPointCloud::setPointColor(), ccPointCloud::setPointNormal(), ccDrawableObject::showColors(), ccDrawableObject::showNormals(), cloudViewer::PointCloudTpl< T >::size(), size, ccHObjectCaster::ToPointCloud(), and voxel_size.
size()
unsigned ccMesh::size () const override virtual
Returns the number of triangles.
Virtual method to request the mesh size
Returns
the mesh size
Implements cloudViewer::GenericMesh.
Definition at line 2143 of file ecvMesh.cpp.
References m_triVertIndexes.
Referenced by _getNextTriangle(), _getTriangle(), addTriangleNorms(), ccGraphicalSegmentationTool::applySegmentation(), ccBox::buildUp(), ccCoordinateSystem::buildUp(), CCMeshToDraco(), MeshWrapper< Real >::checkMeshCapacity(), cloneMesh(), ConvexConcaveHullReconstruction::compute(), GreedyTriangulation::compute(), MarchingCubeReconstruction::compute(), NurbsSurfaceReconstruction::compute(), PoissonReconstruction::compute(), qVoxFallProcess::Compute(), computeInterpolationWeights(), computePerTriangleNormals(), computePerVertexNormals(), convertMaterialsToVertexColors(), cloudViewer::geometry::LineSet::CreateFromTriangleMesh(), cloudViewer::geometry::VoxelGrid::CreateFromTriangleMeshWithinBounds(), createNewMeshFromSelection(), ccSubMesh::createNewSubMeshFromSelection(), ccCropTool::Crop(), cloudViewer::visualization::SelectionPolygonVolume::CropTriangleMesh(), cloudViewer::visualization::SelectionPolygon::CropTriangleMesh(), qPoissonRecon::doAction(), cvSelectionExporter::exportFromSourceMesh(), cvSelectionExporter::exportToMesh(), face_cb(), FromFbxMesh(), cloudViewer::t::geometry::TriangleMesh::FromLegacy(), ccDBRoot::gatherRecursiveInformation(), getColorFromMaterial(), getNextTriangleVertIndexes(), cvViewSelectionManager::getSourceMesh(), getTriangleNormals(), getTriangleNormalsPtr(), getTriangles(), getTriangleVertices(), getVertexColorFromMaterial(), interpolateColors(), interpolateNormals(), interpolateNormalsBC(), ccFacet::IsEmpty(), IsIntersecting(), laplacianSmooth(), CSVMatrixFilter::loadFile(), ObjFilter::loadFile(), OFFFilter::loadFile(), STLFilter::loadFile(), VTKFilter::loadFile(), DRCFilter::loadFile(), PlyFilter::loadFile(), merge(), mergeDuplicatedVertices(), ccGenericPrimitive::operator+=(), partialClone(), CommandCrossSection::process(), CommandDelaunayTri::process(), processScalarField(), pushSubdivide(), cloudViewer::io::ReadTriangleMesh(), cloudViewer::io::ReadTriangleMeshFromOBJ(), removeTriangles(), VTKFilter::saveToFile(), SelectByIndex(), ccPlane::SetQuadTexture(), setTriangles(), ecvPoissonReconDlg::start(), subdivide(), swapTriangles(), colmap::mvs::MvsTexturing::TextureMesh(), ToFbxMesh(), ccPointCloud::triangulateGrid(), and TriangulateTwoPolylines().
subdivide()
ccMesh * ccMesh::subdivide (PointCoordinateType maxArea) const
Subdivides mesh (so as to ensure that all triangles are falls below 'maxArea')
Returns
subdivided mesh (if successful)
Definition at line 4502 of file ecvMesh.cpp.
References ccHObject::addChild(), ccMesh(), ccDrawableObject::colorsShown(), computeNormals(), CVLog::Error(), ccPointCloud::From(), GenerateKey(), getAssociatedCloud(), ccArray< Type, N, ComponentType >::getValue(), hasColors(), hasNormals(), hasTriNormals(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, ccObject::isA(), ccDrawableObject::isVisible(), cloudViewer::LessThanEpsilon(), m_triVertIndexes, normalsShown(), CV_TYPES::POINT_CLOUD, pushSubdivide(), reserve(), s_alreadyCreatedVertices, s_maxSubdivideArea, ccDrawableObject::setVisible(), ccDrawableObject::showColors(), ccGenericMesh::showNormals(), shrinkToFit(), ccPointCloud::shrinkToFit(), cloudViewer::GenericCloud::size(), and size().
SubdivideLoop()
std::shared_ptr< ccMesh > ccMesh::SubdivideLoop (int number_of_iterations) const
Function to subdivide triangle mesh using Loop's scheme. Cf. Charles T. Loop, "Smooth subdivision surfaces based on triangles",
Each triangle is subdivided into four triangles per iteration.
Parameters
number_of_iterations defines a single iteration splits each triangle into four triangles that cover the same surface.
Definition at line 113 of file TriangleMeshSubdivide.cpp.
References e2, ccPointCloud::getEigenColor(), ccPointCloud::getEigenNormal(), cloudViewer::PointCloudTpl< T >::getEigenPoint(), cloudViewer::t::geometry::GetOrderedEdge(), cloudViewer::PointCloudTpl< T >::getPoint(), ccPointCloud::getPointNormal(), cloudViewer::PointCloudTpl< T >::getPointPtr(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), LogError, LogWarning, ccPointCloud::resize(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::resizeTheRGBTable(), ccPointCloud::setEigenColor(), ccPointCloud::setEigenNormal(), ccObject::setEnabled(), ccObject::setLocked(), cloudViewer::PointCloudTpl< T >::setPoint(), ccPointCloud::setPointNormal(), cloudViewer::PointCloudTpl< T >::size(), size, and ccHObjectCaster::ToPointCloud().
SubdivideMidpoint()
std::shared_ptr< ccMesh > ccMesh::SubdivideMidpoint (int number_of_iterations) const
Function to subdivide triangle mesh using the simple midpoint algorithm. Each triangle is subdivided into four triangles per iteration and the new vertices lie on the midpoint of the triangle edges.
Parameters
number_of_iterations defines a single iteration splits each triangle into four triangles that cover the same surface.
Definition at line 21 of file TriangleMeshSubdivide.cpp.
References ccPointCloud::addEigenColor(), ccPointCloud::addEigenNorm(), cloudViewer::PointCloudTpl< T >::addEigenPoint(), ccPointCloud::getEigenColor(), ccPointCloud::getEigenNormal(), cloudViewer::PointCloudTpl< T >::getEigenPoint(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), LogError, LogWarning, ccObject::setEnabled(), ccObject::setLocked(), cloudViewer::PointCloudTpl< T >::size(), and ccHObjectCaster::ToPointCloud().
swapTriangles()
void ccMesh::swapTriangles (unsigned index1, unsigned index2)
Swaps two triangles.
Automatically updates internal structures (i.e. lookup tables for material, normals, etc.).
Definition at line 2574 of file ecvMesh.cpp.
References m_texCoordIndexes, m_triMtlIndexes, m_triNormalIndexes, m_triVertIndexes, size(), and ccArray< Type, N, ComponentType >::swap().
Referenced by mergeDuplicatedVertices().
toFile_MeOnly()
bool ccMesh::toFile_MeOnly (QFile & out, short dataVersion) const override protected virtual
Save own object data.
Called by 'toFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
out output file
dataVersion target file version for compatibility control
Reimplemented from ccGenericMesh.
Reimplemented in ccTorus, ccSphere, ccQuadric, and ccPlane.
Definition at line 3766 of file ecvMesh.cpp.
toggleMaterials()
void ccMesh::toggleMaterials () inline override virtual
Toggles material display state.
Reimplemented from ccDrawableObject.
Definition at line 233 of file ecvMesh.h.
References ccGenericMesh::materialsShown(), and ccGenericMesh::showMaterials().
Transform()
ccMesh & ccMesh::Transform (const Eigen::Matrix4d & transformation) override virtual
Apply transformation (4x4 matrix) to the geometry coordinates.
Reimplemented from ccHObject.
Definition at line 852 of file ecvMesh.cpp.
References ccPointCloud::applyRigidTransformation(), ccGLMatrixTpl< float >::FromEigenMatrix(), m_associatedCloud, ccHObjectCaster::ToPointCloud(), and transformTriNormals().
Referenced by cloudViewer::io::ReadTriangleMeshFromGLTF(), and ccFacet::Transform().
transformTriNormals()
void ccMesh::transformTriNormals (const ccGLMatrix & trans)
Transforms the mesh per-triangle normals.
Definition at line 524 of file ecvMesh.cpp.
References ccGLMatrixTpl< T >::applyRotation(), ccArray< Type, N, ComponentType >::clear(), ccNormalVectors::GetNormal(), ccNormalVectors::GetNormIndex(), ccNormalVectors::GetNumberOfVectors(), ccHObject::getParent(), ccArray< Type, N, ComponentType >::getValue(), ccObject::isKindOf(), m_triNormals, CV_TYPES::MESH, CCShareable::release(), ccArray< Type, N, ComponentType >::setValue(), and Tuple3Tpl< Type >::u.
Referenced by ccGraphicalTransformationTool::apply(), applyGLTransformation(), Rotate(), and Transform().
Translate()
ccMesh & ccMesh::Translate (const Eigen::Vector3d & translation, bool relative = true) override virtual
Apply translation to the geometry coordinates.
Parameters
translation A 3D vector to transform the geometry.
relative If true, the translation is directly applied to the geometry. Otherwise, the geometry center is moved to the translation.
Reimplemented from ccHObject.
Definition at line 863 of file ecvMesh.cpp.
References m_associatedCloud, ccHObjectCaster::ToPointCloud(), and ccPointCloud::Translate().
Referenced by cloudViewer::io::ReadTriangleMeshFromGLTF(), and ccFacet::Translate().
Triangulate()
ccMesh * ccMesh::Triangulate (ccGenericPointCloud * cloud, cloudViewer::TRIANGULATION_TYPES type, bool updateNormals = false, PointCoordinateType maxEdgeLength = 0, unsigned char dim = 2) static
Creates a Delaunay 2.5D mesh from a point cloud.
See cloudViewer::PointProjectionTools::computeTriangulation.
Definition at line 1732 of file ecvMesh.cpp.
References ccMesh(), computeNormals(), cloudViewer::PointProjectionTools::computeTriangulation(), getAssociatedCloud(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccObject::getName(), ccDrawableObject::hasColors(), ccDrawableObject::hasNormals(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccObject::setName(), ccGenericMesh::showNormals(), cloudViewer::GenericCloud::size(), type, and CVLog::Warning().
Referenced by CommandDelaunayTri::process().
TriangulateTwoPolylines()
ccMesh * ccMesh::TriangulateTwoPolylines (ccPolyline * p1, ccPolyline * p2, CCVector3 * projectionDir = nullptr) static
Creates a Delaunay 2.5D mesh from two polylines.
Definition at line 1538 of file ecvMesh.cpp.
References ccHObject::addChild(), cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::Delaunay2dMesh::buildMesh(), ccMesh(), Vector3Tpl< Type >::cross(), Vector3Tpl< Type >::dot(), cloudViewer::PointProjectionTools::extractConvexHull2D(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), cloudViewer::Neighbourhood::getGravityCenter(), cloudViewer::Neighbourhood::getLSPlane(), cloudViewer::Neighbourhood::getLSPlaneX(), cloudViewer::Neighbourhood::getLSPlaneY(), cloudViewer::ReferenceCloud::getPoint(), cloudViewer::Polyline::isClosed(), cloudViewer::Delaunay2dMesh::linkMeshWith(), Vector3Tpl< Type >::orthogonal(), cloudViewer::Delaunay2dMesh::removeOuterTriangles(), ccPointCloud::reserve(), ccPolyline::segmentCount(), ccObject::setEnabled(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccDrawableObject::setVisible(), cloudViewer::Delaunay2dMesh::size(), cloudViewer::PointCloudTpl< T >::size(), cloudViewer::ReferenceCloud::size(), size(), CVLog::Warning(), and X.
Member Data Documentation
adjacency_list_
std::vector<std::unordered_set<int> > ccMesh::adjacency_list_
The set adjacency_list[i] contains the indices of adjacent vertices of vertex i.
Definition at line 622 of file ecvMesh.h.
Referenced by clear(), merge(), operator+=(), and operator=().
DefaultMergeDulicateVerticesLevel
const unsigned char ccMesh::DefaultMergeDulicateVerticesLevel = 10 static
Default octree level for the 'mergeDuplicatedVertices' algorithm.
Definition at line 612 of file ecvMesh.h.
Referenced by STEPFilter::importStepFile(), and STLFilter::loadFile().
m_associatedCloud
ccGenericPointCloud* ccMesh::m_associatedCloud protected
associated cloud (vertices)
Definition at line 1490 of file ecvMesh.h.
Referenced by _getTriangle(), addEigenVertices(), addVertexColor(), addVertexColors(), addVertexNormal(), addVertexNormals(), ccMesh(), cloneMesh(), computeInterpolationWeights(), computePerTriangleNormals(), computePerVertexNormals(), convertMaterialsToVertexColors(), createNewMeshFromSelection(), Crop(), drawMeOnly(), ccGenericPrimitive::finishCloneJob(), forEach(), getGLTransformationHistory(), getTriangleVertices(), getVertexColor(), getVertexColorFromMaterial(), getVertexColors(), getVertexColorsPtr(), getVertexNormal(), getVertexNormals(), hasColors(), hasDisplayedScalarField(), hasScalarFields(), HasVertexNormals(), interpolateColors(), interpolateNormals(), invertNormals(), laplacianSmooth(), merge(), mergeDuplicatedVertices(), onDeletionOf(), onUpdateOf(), partialClone(), processScalarField(), refreshBB(), reserveAssociatedCloud(), resizeAssociatedCloud(), Rotate(), Scale(), setAssociatedCloud(), ccGenericPrimitive::setColor(), setEigenVertices(), setVertexColor(), setVertexColors(), setVertexNormal(), setVertexNormals(), shrinkVertexToFit(), Transform(), Translate(), and ccGenericPrimitive::vertices().
m_bBox
ccBBox ccMesh::m_bBox protected
Bounding-box.
Definition at line 1510 of file ecvMesh.h.
Referenced by getBoundingBox(), getOwnBB(), onUpdateOf(), refreshBB(), resize(), and setAssociatedCloud().
m_currentTriangle
cloudViewer::SimpleRefTriangle ccMesh::m_currentTriangle protected
Dump triangle structure to transmit temporary data.
Definition at line 1507 of file ecvMesh.h.
Referenced by _getTriangle(), and forEach().
m_globalIterator
unsigned ccMesh::m_globalIterator protected
Iterator on the list of triangles.
Definition at line 1505 of file ecvMesh.h.
Referenced by _getNextTriangle(), getNextTriangleVertIndexes(), and placeIteratorAtBeginning().
m_materials
ccMaterialSet* ccMesh::m_materials protected
Materials.
Definition at line 1499 of file ecvMesh.h.
Referenced by cloneMesh(), createNewMeshFromSelection(), getColorFromMaterial(), getVertexColorFromMaterial(), hasMaterials(), merge(), partialClone(), and setMaterialSet().
m_texCoordIndexes
triangleTexCoordIndexesSet* ccMesh::m_texCoordIndexes protected
Mesh tex coords indexes (per-triangle)
Definition at line 1518 of file ecvMesh.h.
Referenced by addTriangleTexCoordIndexes(), cloneMesh(), createNewMeshFromSelection(), getColorFromMaterial(), getTriangleTexCoordinates(), getTriangleTexCoordinatesIndexes(), getVertexColorFromMaterial(), hasTextures(), merge(), partialClone(), removePerTriangleTexCoordIndexes(), removeTriangles(), reserve(), reservePerTriangleTexCoordIndexes(), resize(), setTriangleTexCoordIndexes(), swapTriangles(), and ~ccMesh().
m_texCoords
TextureCoordsContainer* ccMesh::m_texCoords protected
Texture coordinates.
Definition at line 1496 of file ecvMesh.h.
Referenced by cloneMesh(), createNewMeshFromSelection(), getColorFromMaterial(), getTexCoordinates(), getTriangleTexCoordinates(), getVertexColorFromMaterial(), hasTextures(), merge(), partialClone(), and setTexCoordinatesTable().
m_triMtlIndexes
triangleMaterialIndexesSet* ccMesh::m_triMtlIndexes protected
Per-triangle material indexes.
Definition at line 1513 of file ecvMesh.h.
Referenced by addTriangleMtlIndex(), cloneMesh(), createNewMeshFromSelection(), getColorFromMaterial(), getTriangleMtlIndex(), getVertexColorFromMaterial(), hasMaterials(), merge(), partialClone(), removePerTriangleMtlIndexes(), removeTriangles(), reserve(), reservePerTriangleMtlIndexes(), resize(), setTriangleMtlIndex(), setTriangleMtlIndexesTable(), swapTriangles(), and ~ccMesh().
m_triNormalIndexes
triangleNormalsIndexesSet* ccMesh::m_triNormalIndexes protected
Mesh normals indexes (per-triangle)
Definition at line 1523 of file ecvMesh.h.
Referenced by addTriangleNormalIndexes(), arePerTriangleNormalsEnabled(), cloneMesh(), computePerTriangleNormals(), createNewMeshFromSelection(), getTriangleNormalIndexes(), getTriangleNormals(), hasTriNormals(), interpolateNormals(), interpolateNormalsBC(), merge(), ccGenericPrimitive::operator+=(), partialClone(), removePerTriangleNormalIndexes(), removeTriangles(), reserve(), reservePerTriangleNormalIndexes(), resize(), setTriangleNormalIndexes(), swapTriangles(), and ~ccMesh().
m_triNormals
NormsIndexesTableType* ccMesh::m_triNormals protected
Per-triangle normals.
Definition at line 1493 of file ecvMesh.h.
Referenced by addTriangleNorm(), ccBox::buildUp(), ccCone::buildUp(), ccCoordinateSystem::buildUp(), ccDisc::buildUp(), ccExtru::buildUp(), ccPlane::buildUp(), ccTorus::buildUp(), cloneMesh(), createNewMeshFromSelection(), getTriangleNorm(), getTriangleNormalIndexes(), getTriangleNormals(), getTriangleNormalsPtr(), getTriangleNorms(), hasTriNormals(), ccGenericPrimitive::init(), interpolateNormals(), invertNormals(), invertPerTriangleNormals(), merge(), ccGenericPrimitive::operator+=(), partialClone(), setTriangleNorm(), setTriangleNormalIndexes(), setTriangleNorms(), setTriNormsTable(), and transformTriNormals().
m_triVertIndexes
triangleIndexesContainer* ccMesh::m_triVertIndexes protected
Triangles' vertices indexes (3 per triangle)
Definition at line 1502 of file ecvMesh.h.
Referenced by _getTriangle(), addTriangle(), ccBox::buildUp(), ccCone::buildUp(), ccCoordinateSystem::buildUp(), ccDisc::buildUp(), ccSphere::buildUp(), ccTorus::buildUp(), capacity(), ccMesh(), computeInterpolationWeights(), computePerTriangleNormals(), createNewMeshFromSelection(), drawMeOnly(), flipTriangles(), forEach(), getTriangleVertices(), getTriangleVertIndexes(), getVertexColorFromMaterial(), hasMaterials(), hasTextures(), hasTriNormals(), ccGenericPrimitive::init(), interpolateColors(), interpolateNormals(), interpolateNormalsBC(), refreshBB(), removeTriangles(), reserve(), reservePerTriangleMtlIndexes(), reservePerTriangleNormalIndexes(), reservePerTriangleTexCoordIndexes(), resize(), setTriangle(), shiftTriangleIndexes(), size(), subdivide(), swapTriangles(), and ~ccMesh().
materials_
std::vector<std::pair<std::string, Material> > ccMesh::materials_
Definition at line 704 of file ecvMesh.h.
Referenced by clear(), cloudViewer::t::geometry::TriangleMesh::FromLegacy(), cloudViewer::io::ReadTriangleMeshFromOBJ(), cloudViewer::io::ReadTriangleMeshUsingASSIMP(), and cloudViewer::t::geometry::TriangleMesh::ToLegacy().
textures_
std::vector<cloudViewer::geometry::Image> ccMesh::textures_
Textures of the image.
Definition at line 709 of file ecvMesh.h.
Referenced by clear(), merge(), cloudViewer::io::ReadTriangleMeshFromOBJ(), cloudViewer::io::ReadTriangleMeshUsingASSIMP(), and cloudViewer::io::rpc::SetTriangleMesh().
triangle_material_ids_
std::vector<int> ccMesh::triangle_material_ids_
List of material ids.
Definition at line 707 of file ecvMesh.h.
Referenced by clear(), merge(), cloudViewer::io::ReadTriangleMeshFromOBJ(), and cloudViewer::io::ReadTriangleMeshUsingASSIMP().
triangle_uvs_
std::vector<Eigen::Vector2d> ccMesh::triangle_uvs_
List of uv coordinates per triangle.
Definition at line 625 of file ecvMesh.h.
Referenced by clear(), cloudViewer::t::geometry::TriangleMesh::FromLegacy(), merge(), cloudViewer::io::ReadTriangleMeshFromOBJ(), cloudViewer::io::ReadTriangleMeshUsingASSIMP(), cloudViewer::io::rpc::SetTriangleMesh(), and cloudViewer::t::geometry::TriangleMesh::ToLegacy().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/ecvMesh.h
/root/ACloudViewer/libs/CV_db/src/ecvMesh.cpp
/root/ACloudViewer/libs/CV_db/src/SurfaceReconstructionAlphaShape.cpp
/root/ACloudViewer/libs/CV_db/src/SurfaceReconstructionBallPivoting.cpp
/root/ACloudViewer/libs/CV_db/src/SurfaceReconstructionPoisson.cpp
/root/ACloudViewer/libs/CV_db/src/TriangleMeshDeformation.cpp
/root/ACloudViewer/libs/CV_db/src/TriangleMeshFactory.cpp
/root/ACloudViewer/libs/CV_db/src/TriangleMeshSimplification.cpp
/root/ACloudViewer/libs/CV_db/src/TriangleMeshSubdivide.cpp