ACloudViewer: IconHelper Class Reference
IconHelper Class Reference
#include <ecvUIManager.h>
Public Member Functions
IconHelper (QObject *parent=0)
void setIcon (QLabel *lab, QChar c, quint32 size=9)
void setIcon (QAbstractButton *btn, QChar c, quint32 size=9)
QPixmap getPixmap (const QString &color, QChar c, quint32 size=9, quint32 pixWidth=10, quint32 pixHeight=10)
QPixmap getPixmap (QToolButton *btn, bool normal)
void setStyle (QWidget *widget, QList< QToolButton * > btns, QList< int > pixChar, quint32 iconSize=9, quint32 iconWidth=10, quint32 iconHeight=10, const QString &type="left", int borderWidth=3, const QString &borderColor="#029FEA", const QString &normalBgColor="#292F38", const QString &darkBgColor="#1D2025", const QString &normalTextColor="#54626F", const QString &darkTextColor="#FDFDFD")
void setStyle (QFrame *frame, QList< QToolButton * > btns, QList< int > pixChar, quint32 iconSize=9, quint32 iconWidth=10, quint32 iconHeight=10, const QString &normalBgColor="#2FC5A2", const QString &darkBgColor="#3EA7E9", const QString &normalTextColor="#EEEEEE", const QString &darkTextColor="#FFFFFF")
Static Public Member Functions
static IconHelper * Instance ()
static void setStyle (QWidget *widget, const QString &type="left", int borderWidth=3, const QString &borderColor="#029FEA", const QString &normalBgColor="#292F38", const QString &darkBgColor="#1D2025", const QString &normalTextColor="#54626F", const QString &darkTextColor="#FDFDFD")
Protected Member Functions
bool eventFilter (QObject *watched, QEvent *event)
Detailed Description
Definition at line 547 of file ecvUIManager.h.
Constructor & Destructor Documentation
IconHelper()
IconHelper::IconHelper (QObject * parent = 0) explicit
Definition at line 2304 of file ecvUIManager.cpp.
Referenced by Instance().
Member Function Documentation
eventFilter()
bool IconHelper::eventFilter (QObject * watched, QEvent * event) protected
Definition at line 2558 of file ecvUIManager.cpp.
References event.
getPixmap() [1/2]
QPixmap IconHelper::getPixmap (const QString & color, QChar c, quint32 size = 9, quint32 pixWidth = 10, quint32 pixHeight = 10)
Definition at line 2328 of file ecvUIManager.cpp.
References color, and size.
Referenced by setStyle().
getPixmap() [2/2]
QPixmap IconHelper::getPixmap (QToolButton * btn, bool normal)
Definition at line 2350 of file ecvUIManager.cpp.
References normal.
Instance()
static IconHelper* IconHelper::Instance () inline static
Definition at line 552 of file ecvUIManager.h.
References IconHelper().
Referenced by QUIWidget::setIcon(), QUIWidget::setIconMain(), QUIMessageBox::setIconMain(), and QUIInputBox::setIconMain().
setIcon() [1/2]
void IconHelper::setIcon (QAbstractButton * btn, QChar c, quint32 size = 9)
Definition at line 2322 of file ecvUIManager.cpp.
References size.
setIcon() [2/2]
void IconHelper::setIcon (QLabel * lab, QChar c, quint32 size = 9)
Definition at line 2316 of file ecvUIManager.cpp.
References size.
Referenced by QUIWidget::setIcon(), QUIWidget::setIconMain(), QUIMessageBox::setIconMain(), and QUIInputBox::setIconMain().
setStyle() [1/3]
void IconHelper::setStyle (QFrame * frame, QList< QToolButton * > btns, QList< int > pixChar, quint32 iconSize = 9, quint32 iconWidth = 10, quint32 iconHeight = 10, const QString & normalBgColor = "#2FC5A2", const QString & darkBgColor = "#3EA7E9", const QString & normalTextColor = "#EEEEEE", const QString & darkTextColor = "#FFFFFF")
Definition at line 2512 of file ecvUIManager.cpp.
References frame, and getPixmap().
setStyle() [2/3]
void IconHelper::setStyle (QWidget * widget, const QString & type = "left", int borderWidth = 3, const QString & borderColor = "#029FEA", const QString & normalBgColor = "#292F38", const QString & darkBgColor = "#1D2025", const QString & normalTextColor = "#54626F", const QString & darkTextColor = "#FDFDFD") static
Definition at line 2365 of file ecvUIManager.cpp.
References type.
setStyle() [3/3]
void IconHelper::setStyle (QWidget * widget, QList< QToolButton * > btns, QList< int > pixChar, quint32 iconSize = 9, quint32 iconWidth = 10, quint32 iconHeight = 10, const QString & type = "left", int borderWidth = 3, const QString & borderColor = "#029FEA", const QString & normalBgColor = "#292F38", const QString & darkBgColor = "#1D2025", const QString & normalTextColor = "#54626F", const QString & darkTextColor = "#FDFDFD")
Definition at line 2418 of file ecvUIManager.cpp.
References getPixmap(), and type.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvUIManager.h
/root/ACloudViewer/app/ecvUIManager.cpp