ACloudViewer: cloudViewer::geometry::Octree Class Reference
cloudViewer::geometry::Octree Class Reference
Octree datastructure.
#include <Octree.h>
Public Member Functions
Octree (const char *name="Octree2")
Default Constructor.
Octree (const size_t &max_depth, const char *name="Octree2")
Parameterized Constructor.
Octree (const size_t &max_depth, const Eigen::Vector3d &origin, const double &size, const char *name="Octree2")
Parameterized Constructor.
Octree (const Octree &src_octree, const char *name="Octree2")
~Octree () override
virtual bool isSerializable () const override
Returns whether object is serializable of not.
virtual CV_CLASS_ENUM getClassID () const override
Returns unique class ID.
virtual ccBBox getOwnBB (bool withGLFeatures=false) override
Returns the entity's own bounding-box.
Octree & Clear ()
virtual bool IsEmpty () const override
virtual Eigen::Vector3d GetMinBound () const override
Returns min bounds for geometry coordinates.
virtual Eigen::Vector3d GetMaxBound () const override
Returns max bounds for geometry coordinates.
virtual Eigen::Vector3d GetCenter () const override
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const override
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const override
virtual Octree & Transform (const Eigen::Matrix4d &transformation) override
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual Octree & Translate (const Eigen::Vector3d &translation, bool relative=true) override
Apply translation to the geometry coordinates.
virtual Octree & Scale (const double s, const Eigen::Vector3d &center) override
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual Octree & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center) override
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
bool ConvertToJsonValue (Json::Value &value) const override
bool ConvertFromJsonValue (const Json::Value &value) override
void ConvertFromPointCloud (const ccPointCloud &point_cloud, double size_expand=0.01)
Convert octree from point cloud.
void InsertPoint (const Eigen::Vector3d &point, const std::function< std::shared_ptr< OctreeLeafNode >()> &fl_init, const std::function< void(std::shared_ptr< OctreeLeafNode >)> &fl_update, const std::function< std::shared_ptr< OctreeInternalNode >()> &fi_init=nullptr, const std::function< void(std::shared_ptr< OctreeInternalNode >)> &fi_update=nullptr)
Insert a point to the octree.
void Traverse (const std::function< bool(const std::shared_ptr< OctreeNode > &, const std::shared_ptr< OctreeNodeInfo > &)> &f)
DFS traversal of Octree from the root, with callback function called for each node.
void Traverse (const std::function< bool(const std::shared_ptr< OctreeNode > &, const std::shared_ptr< OctreeNodeInfo > &)> &f) const
Const version of Traverse. DFS traversal of Octree from the root, with callback function called for each node.
std::pair< std::shared_ptr< OctreeLeafNode >, std::shared_ptr< OctreeNodeInfo > > LocateLeafNode (const Eigen::Vector3d &point) const
Returns leaf OctreeNode and OctreeNodeInfo where the querypoint should reside.
bool operator== (const Octree &other) const
Returns true if the Octree is completely the same, used for testing.
std::shared_ptr< geometry::VoxelGrid > ToVoxelGrid () const
Convert to VoxelGrid.
void CreateFromVoxelGrid (const geometry::VoxelGrid &voxel_grid)
Convert from voxel grid.
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual Eigen::Vector2d GetMin2DBound () const
virtual Eigen::Vector2d GetMax2DBound () const
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false)
virtual bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner)
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual ccBBox getOwnFitBB (ccGLMatrix &trans)
Returns best-fit bounding-box (if available)
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col)
Draws the entity (and its children) bounding-box.
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
virtual void notifyGeometryUpdate ()
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual unsigned getUniqueIDForDisplay () const
Returns object unqiue ID used for display.
virtual const ccGLMatrix & getGLTransformationHistory () const
Returns the transformation 'history' matrix.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual void getDrawingParameters (glDrawParams &params) const
Returns main OpenGL parameters for this entity.
virtual bool hasColors () const
Returns whether colors are enabled or not.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual bool hasNormals () const
Returns whether normals are enabled or not.
virtual bool normalsShown () const
Returns whether normals are shown or not.
virtual void showNormals (bool state)
Sets normals visibility.
virtual void toggleNormals ()
Toggles normals display state.
virtual bool hasDisplayedScalarField () const
Returns whether an active scalar field is available or not.
virtual bool hasScalarFields () const
Returns whether one or more scalar fields are instantiated.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void toggleMaterials ()
Toggles material display state.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
virtual ~IJsonConvertible ()
virtual std::string ToString () const
Convert to a styled string representation of JSON data for display.
Static Public Member Functions
static bool IsPointInBound (const Eigen::Vector3d &point, const Eigen::Vector3d &origin, const double &size)
Return true if point within bound, that is, origin <= point < origin + size.
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Static Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
static bool EigenVector3dFromJsonArray (Eigen::Vector3d &vec, const Json::Value &value)
static bool EigenVector3dToJsonArray (const Eigen::Vector3d &vec, Json::Value &value)
static bool EigenVector4dFromJsonArray (Eigen::Vector4d &vec, const Json::Value &value)
static bool EigenVector4dToJsonArray (const Eigen::Vector4d &vec, Json::Value &value)
static bool EigenMatrix3dFromJsonArray (Eigen::Matrix3d &mat, const Json::Value &value)
static bool EigenMatrix3dToJsonArray (const Eigen::Matrix3d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d_u &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d_u &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d_u &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d_u &mat, Json::Value &value)
Public Attributes
std::shared_ptr< OctreeNode > root_node_ = nullptr
Root of the octree.
Eigen::Vector3d origin_
double size_
size_t max_depth_
Additional Inherited Members
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void drawMeOnly (CC_DRAW_CONTEXT &context)
Draws the entity only (not its children)
virtual void applyGLTransformation (const ccGLMatrix &trans)
Applies a GL transformation to the entity.
virtual bool toFile_MeOnly (QFile &out, short dataVersion) const
Save own object data.
virtual bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Loads own object data.
virtual short minimumFileVersion_MeOnly () const
virtual void drawNameIn3D ()
Draws the entity name in 3D.
virtual void onDeletionOf (const ccHObject *obj)
This method is called when another object is deleted.
virtual void onUpdateOf (ccHObject *obj)
This method is called when another object (geometry) is updated.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Detailed Description
Octree datastructure.
Definition at line 249 of file Octree.h.
Constructor & Destructor Documentation
Octree() [1/4]
cloudViewer::geometry::Octree::Octree (const char * name = "Octree2") inline
Default Constructor.
Definition at line 253 of file Octree.h.
Octree() [2/4]
cloudViewer::geometry::Octree::Octree (const size_t & max_depth, const char * name = "Octree2") inline
Parameterized Constructor.
Parameters
max_depth Sets the value of the max depth of the Octree.
Definition at line 258 of file Octree.h.
Octree() [3/4]
cloudViewer::geometry::Octree::Octree (const size_t & max_depth, const Eigen::Vector3d & origin, const double & size, const char * name = "Octree2") inline
Parameterized Constructor.
Parameters
max_depth Sets the value of the max depth of the Octree.
origin Sets the global min bound of the Octree.
size Sets the outer bounding box edge size for the whole octree.
Definition at line 265 of file Octree.h.
Octree() [4/4]
cloudViewer::geometry::Octree::Octree (const Octree & src_octree, const char * name = "Octree2")
Definition at line 328 of file Octree.cpp.
References LogError, root_node_, and Traverse().
~Octree()
cloudViewer::geometry::Octree::~Octree () inline override
Definition at line 274 of file Octree.h.
Member Function Documentation
Clear()
Octree & cloudViewer::geometry::Octree::Clear ()
Definition at line 483 of file Octree.cpp.
References origin_, root_node_, and size_.
Referenced by ConvertFromPointCloud().
ConvertFromJsonValue()
bool cloudViewer::geometry::Octree::ConvertFromJsonValue (const Json::Value & value) override virtual
Implements cloudViewer::utility::IJsonConvertible.
Definition at line 770 of file Octree.cpp.
References cloudViewer::geometry::OctreeNode::ConstructFromJsonValue(), cloudViewer::utility::IJsonConvertible::EigenVector3dFromJsonArray(), LogWarning, max_depth_, origin_, root_node_, and size_.
ConvertFromPointCloud()
void cloudViewer::geometry::Octree::ConvertFromPointCloud (const ccPointCloud & point_cloud, double size_expand = 0.01)
Convert octree from point cloud.
Parameters
point_cloud Input point cloud.
size_expand A small expansion size such that the octree is slightly bigger than the original point cloud bounds to accomodate all points.
Definition at line 545 of file Octree.cpp.
References Clear(), color, ccPointCloud::getEigenColor(), cloudViewer::PointCloudTpl< T >::getEigenPoint(), cloudViewer::geometry::OctreePointColorLeafNode::GetInitFunction(), ccPointCloud::GetMaxBound(), ccPointCloud::GetMinBound(), cloudViewer::geometry::OctreePointColorLeafNode::GetUpdateFunction(), has_colors, ccPointCloud::hasColors(), InsertPoint(), LogError, origin_, cloudViewer::PointCloudTpl< T >::size(), and size_.
ConvertToJsonValue()
bool cloudViewer::geometry::Octree::ConvertToJsonValue (Json::Value & value) const override virtual
Implements cloudViewer::utility::IJsonConvertible.
Definition at line 756 of file Octree.cpp.
References cloudViewer::utility::IJsonConvertible::EigenVector3dToJsonArray(), cloudViewer::core::Int64, max_depth_, origin_, root_node_, and size_.
CreateFromVoxelGrid()
void cloudViewer::geometry::Octree::CreateFromVoxelGrid (const geometry::VoxelGrid & voxel_grid)
Convert from voxel grid.
Definition at line 791 of file Octree.cpp.
References cloudViewer::geometry::Voxel::color_, cloudViewer::geometry::OctreeColorLeafNode::GetInitFunction(), cloudViewer::geometry::VoxelGrid::GetMaxBound(), cloudViewer::geometry::OctreeColorLeafNode::GetUpdateFunction(), cloudViewer::geometry::Voxel::grid_index_, InsertPoint(), origin_, cloudViewer::geometry::VoxelGrid::origin_, size_, cloudViewer::geometry::VoxelGrid::voxel_size_, and cloudViewer::geometry::VoxelGrid::voxels_.
GetAxisAlignedBoundingBox()
ccBBox cloudViewer::geometry::Octree::GetAxisAlignedBoundingBox () const override virtual
Returns an axis-aligned bounding box of the geometry.
Reimplemented from ccHObject.
Definition at line 511 of file Octree.cpp.
References GetMaxBound(), GetMinBound(), ccBBox::IsEmpty(), cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), and cloudViewer::BoundingBoxTpl< T >::setValidity().
Referenced by GetOrientedBoundingBox(), and getOwnBB().
GetCenter()
Eigen::Vector3d cloudViewer::geometry::Octree::GetCenter () const override virtual
Returns the center of the geometry coordinates.
Reimplemented from ccHObject.
Definition at line 507 of file Octree.cpp.
References origin_, and size_.
getClassID()
virtual CV_CLASS_ENUM cloudViewer::geometry::Octree::getClassID () const inline override virtual
Returns unique class ID.
Reimplemented from ccHObject.
Definition at line 280 of file Octree.h.
References CV_TYPES::POINT_OCTREE2.
GetMaxBound()
Eigen::Vector3d cloudViewer::geometry::Octree::GetMaxBound () const override virtual
Returns max bounds for geometry coordinates.
Reimplemented from ccHObject.
Definition at line 499 of file Octree.cpp.
References IsEmpty(), origin_, and size_.
Referenced by GetAxisAlignedBoundingBox().
GetMinBound()
Eigen::Vector3d cloudViewer::geometry::Octree::GetMinBound () const override virtual
Returns min bounds for geometry coordinates.
Reimplemented from ccHObject.
Definition at line 491 of file Octree.cpp.
References IsEmpty(), and origin_.
Referenced by GetAxisAlignedBoundingBox().
GetOrientedBoundingBox()
ecvOrientedBBox cloudViewer::geometry::Octree::GetOrientedBoundingBox () const override virtual
Reimplemented from ccHObject.
Definition at line 519 of file Octree.cpp.
References ecvOrientedBBox::CreateFromAxisAlignedBoundingBox(), and GetAxisAlignedBoundingBox().
getOwnBB()
ccBBox cloudViewer::geometry::Octree::getOwnBB (bool withGLFeatures = false) override virtual
Returns the entity's own bounding-box.
Children bboxes are ignored.
Parameters
withGLFeatures whether to take into account display-only elements (if any)
Returns
bounding-box
Reimplemented from ccHObject.
Definition at line 479 of file Octree.cpp.
References GetAxisAlignedBoundingBox().
InsertPoint()
void cloudViewer::geometry::Octree::InsertPoint (const Eigen::Vector3d & point, const std::function< std::shared_ptr< OctreeLeafNode >()> & fl_init, const std::function< void(std::shared_ptr< OctreeLeafNode >)> & fl_update, const std::function< std::shared_ptr< OctreeInternalNode >()> & fi_init = nullptr, const std::function< void(std::shared_ptr< OctreeInternalNode >)> & fi_update = nullptr)
Insert a point to the octree.
Parameters
point Coordinates of the point.
fl_init Initialization fcn used to create new leaf node (if needed) associated with the point.
fl_update Update fcn used to update the leaf node associated with the point.
fi_init Initialize fcn used to create a new internal node (if needed) which is an ancestor of the point's leaf node. If omitted, the default OctreeInternalNode function is used.
fi_update Update fcn used to update the internal node which is an ancestor of the point's leaf node. If omitted, the default OctreeInternalNode function is used.
Definition at line 579 of file Octree.cpp.
References max_depth_, origin_, root_node_, and size_.
Referenced by ConvertFromPointCloud(), and CreateFromVoxelGrid().
IsEmpty()
virtual bool cloudViewer::geometry::Octree::IsEmpty () const inline override virtual
Reimplemented from ccHObject.
Definition at line 288 of file Octree.h.
Referenced by GetMaxBound(), and GetMinBound().
IsPointInBound()
bool cloudViewer::geometry::Octree::IsPointInBound (const Eigen::Vector3d & point, const Eigen::Vector3d & origin, const double & size) static
Return true if point within bound, that is, origin <= point < origin + size.
Parameters
point Coordinates of the point.
origin Origin coordinates.
size Size of the Octree.
Definition at line 663 of file Octree.cpp.
References origin, and size.
Referenced by LocateLeafNode().
isSerializable()
virtual bool cloudViewer::geometry::Octree::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccHObject.
Definition at line 277 of file Octree.h.
LocateLeafNode()
std::pair< std::shared_ptr< OctreeLeafNode >, std::shared_ptr< OctreeNodeInfo > > cloudViewer::geometry::Octree::LocateLeafNode (const Eigen::Vector3d & point) const
Returns leaf OctreeNode and OctreeNodeInfo where the querypoint should reside.
Parameters
point Coordinates of the point.
Definition at line 727 of file Octree.cpp.
References IsPointInBound(), cloudViewer::core::make_pair(), and Traverse().
operator==()
bool cloudViewer::geometry::Octree::operator== (const Octree & other) const
Returns true if the Octree is completely the same, used for testing.
Definition at line 384 of file Octree.cpp.
References max_depth_, origin_, size_, and Traverse().
Rotate()
Octree & cloudViewer::geometry::Octree::Rotate (const Eigen::Matrix3d & R, const Eigen::Vector3d & center) override virtual
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
Parameters
R A 3x3 rotation matrix
center Rotation center that is used for the rotation.
Reimplemented from ccHObject.
Definition at line 539 of file Octree.cpp.
References LogError.
Scale()
Octree & cloudViewer::geometry::Octree::Scale (const double s, const Eigen::Vector3d & center) override virtual
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
Parameters
scale The scale parameter that is multiplied to the points/vertices of the geometry.
center Scale center that is used to resize the geometry.
Reimplemented from ccHObject.
Definition at line 534 of file Octree.cpp.
References LogError.
ToVoxelGrid()
std::shared_ptr< geometry::VoxelGrid > cloudViewer::geometry::Octree::ToVoxelGrid () const
Convert to VoxelGrid.
Definition at line 750 of file Octree.cpp.
Transform()
Octree & cloudViewer::geometry::Octree::Transform (const Eigen::Matrix4d & transformation) override virtual
Apply transformation (4x4 matrix) to the geometry coordinates.
Reimplemented from ccHObject.
Definition at line 524 of file Octree.cpp.
References LogError.
Translate()
Octree & cloudViewer::geometry::Octree::Translate (const Eigen::Vector3d & translation, bool relative = true) override virtual
Apply translation to the geometry coordinates.
Parameters
translation A 3D vector to transform the geometry.
relative If true, the translation is directly applied to the geometry. Otherwise, the geometry center is moved to the translation.
Reimplemented from ccHObject.
Definition at line 529 of file Octree.cpp.
References LogError.
Traverse() [1/2]
void cloudViewer::geometry::Octree::Traverse (const std::function< bool(const std::shared_ptr< OctreeNode > &, const std::shared_ptr< OctreeNodeInfo > &)> & f)
DFS traversal of Octree from the root, with callback function called for each node.
Parameters
f Callback which fires with each traversed internal/leaf node. Arguments supply information about the node being traversed and other node-specific data. A Boolean return value is used for early-stopping. If f returns true, children of this node will not be traversed.
Definition at line 671 of file Octree.cpp.
References origin_, root_node_, and size_.
Referenced by LocateLeafNode(), Octree(), and operator==().
Traverse() [2/2]
void cloudViewer::geometry::Octree::Traverse (const std::function< bool(const std::shared_ptr< OctreeNode > &, const std::shared_ptr< OctreeNodeInfo > &)> & f) const
Const version of Traverse. DFS traversal of Octree from the root, with callback function called for each node.
Parameters
f Callback which fires with each traversed internal/leaf node. Arguments supply information about the node being traversed and other node-specific data. A Boolean return value is used for early-stopping. If f returns true, children of this node will not be traversed.
Definition at line 679 of file Octree.cpp.
References origin_, root_node_, and size_.
Member Data Documentation
max_depth_
size_t cloudViewer::geometry::Octree::max_depth_
Max depth of octree. The depth is defined as the distance from the deepest leaf node to root. A tree with only the root node has depth 0.
Definition at line 329 of file Octree.h.
Referenced by ConvertFromJsonValue(), ConvertToJsonValue(), InsertPoint(), and operator==().
origin_
Eigen::Vector3d cloudViewer::geometry::Octree::origin_
Global min bound (include). A point is within bound iff origin_ <= point < origin_ + size_.
Definition at line 321 of file Octree.h.
Referenced by Clear(), ConvertFromJsonValue(), ConvertFromPointCloud(), ConvertToJsonValue(), CreateFromVoxelGrid(), GetCenter(), GetMaxBound(), GetMinBound(), InsertPoint(), operator==(), and Traverse().
root_node_
std::shared_ptr<OctreeNode> cloudViewer::geometry::Octree::root_node_ = nullptr
Root of the octree.
Definition at line 317 of file Octree.h.
Referenced by Clear(), ConvertFromJsonValue(), ConvertToJsonValue(), InsertPoint(), Octree(), and Traverse().
size_
double cloudViewer::geometry::Octree::size_
Outer bounding box edge size for the whole octree. A point is within bound iff origin_ <= point < origin_ + size_.
Definition at line 325 of file Octree.h.
Referenced by Clear(), ConvertFromJsonValue(), ConvertFromPointCloud(), ConvertToJsonValue(), CreateFromVoxelGrid(), GetCenter(), GetMaxBound(), InsertPoint(), operator==(), and Traverse().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/Octree.h
/root/ACloudViewer/libs/CV_db/src/Octree.cpp