ACloudViewer: cloudViewer::visualization::visualizer::O3DVisualizerSelections Class Reference
cloudViewer::visualization::visualizer::O3DVisualizerSelections Class Reference
#include <O3DVisualizerSelections.h>
Classes
struct SelectedIndex
Public Types
using SelectionSet = std::map< std::string, std::set< SelectedIndex > >
Public Member Functions
O3DVisualizerSelections (gui::SceneWidget &widget3d)
~O3DVisualizerSelections ()
void NewSet ()
void RemoveSet (int index)
void SelectSet (int index)
size_t GetNumberOfSets () const
void SelectIndices (const std::map< std::string, std::vector< std::pair< size_t, Eigen::Vector3d >>> &indices)
void UnselectIndices (const std::map< std::string, std::vector< std::pair< size_t, Eigen::Vector3d >>> &indices)
std::vector< SelectionSet > GetSets ()
void SetPointSize (double radius_world)
void MakeActive ()
void MakeInactive ()
bool IsActive () const
void SetSelectableGeometry (const std::vector< gui::SceneWidget::PickableGeometry > &geometry)
Detailed Description
Internal class that acts as a selections model + controller for O3DVisualizer
Definition at line 31 of file O3DVisualizerSelections.h.
Member Typedef Documentation
SelectionSet
using cloudViewer::visualization::visualizer::O3DVisualizerSelections::SelectionSet = std::map<std::string, std::set<SelectedIndex> >
Definition at line 46 of file O3DVisualizerSelections.h.
Constructor & Destructor Documentation
O3DVisualizerSelections()
cloudViewer::visualization::visualizer::O3DVisualizerSelections::O3DVisualizerSelections (gui::SceneWidget & widget3d)
Definition at line 33 of file O3DVisualizerSelections.cpp.
~O3DVisualizerSelections()
cloudViewer::visualization::visualizer::O3DVisualizerSelections::~O3DVisualizerSelections ()
Definition at line 36 of file O3DVisualizerSelections.cpp.
Member Function Documentation
GetNumberOfSets()
size_t cloudViewer::visualization::visualizer::O3DVisualizerSelections::GetNumberOfSets () const
Definition at line 72 of file O3DVisualizerSelections.cpp.
GetSets()
std::vector< O3DVisualizerSelections::SelectionSet > cloudViewer::visualization::visualizer::O3DVisualizerSelections::GetSets ()
Definition at line 144 of file O3DVisualizerSelections.cpp.
IsActive()
bool cloudViewer::visualization::visualizer::O3DVisualizerSelections::IsActive () const
Definition at line 182 of file O3DVisualizerSelections.cpp.
Referenced by SetPointSize().
MakeActive()
void cloudViewer::visualization::visualizer::O3DVisualizerSelections::MakeActive ()
Definition at line 162 of file O3DVisualizerSelections.cpp.
References cloudViewer::visualization::gui::SceneWidget::GetScene(), LogError, and cloudViewer::visualization::gui::SceneWidget::SetViewControls().
MakeInactive()
void cloudViewer::visualization::visualizer::O3DVisualizerSelections::MakeInactive ()
Definition at line 184 of file O3DVisualizerSelections.cpp.
References cloudViewer::visualization::gui::SceneWidget::GetScene().
NewSet()
void cloudViewer::visualization::visualizer::O3DVisualizerSelections::NewSet ()
Definition at line 38 of file O3DVisualizerSelections.cpp.
References name, and patch::to_string().
RemoveSet()
void cloudViewer::visualization::visualizer::O3DVisualizerSelections::RemoveSet (int index)
Definition at line 46 of file O3DVisualizerSelections.cpp.
References cloudViewer::visualization::gui::SceneWidget::GetScene(), min(), and name.
SelectIndices()
void cloudViewer::visualization::visualizer::O3DVisualizerSelections::SelectIndices (const std::map< std::string, std::vector< std::pair< size_t, Eigen::Vector3d >>> & indices)
Definition at line 74 of file O3DVisualizerSelections.cpp.
References name.
SelectSet()
void cloudViewer::visualization::visualizer::O3DVisualizerSelections::SelectSet (int index)
Definition at line 59 of file O3DVisualizerSelections.cpp.
References cloudViewer::visualization::gui::SceneWidget::GetScene(), and name.
SetPointSize()
void cloudViewer::visualization::visualizer::O3DVisualizerSelections::SetPointSize (double radius_world)
Definition at line 153 of file O3DVisualizerSelections.cpp.
References IsActive().
SetSelectableGeometry()
void cloudViewer::visualization::visualizer::O3DVisualizerSelections::SetSelectableGeometry (const std::vector< gui::SceneWidget::PickableGeometry > & geometry)
Definition at line 195 of file O3DVisualizerSelections.cpp.
References cloudViewer::visualization::gui::SceneWidget::SetPickableGeometry().
UnselectIndices()
void cloudViewer::visualization::visualizer::O3DVisualizerSelections::UnselectIndices (const std::map< std::string, std::vector< std::pair< size_t, Eigen::Vector3d >>> & indices)
Definition at line 94 of file O3DVisualizerSelections.cpp.
References name.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/O3DVisualizerSelections.h
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/O3DVisualizerSelections.cpp