ACloudViewer: LASOpenDlg Class Reference
LASOpenDlg Class Reference
Dialog to choose the LAS fields to load.
#include <LASOpenDlg.h>
Public Member Functions
LASOpenDlg (QWidget *parent=nullptr)
Default constructor.
void setDimensions (const std::vector< std::string > &dimensions)
Sets available dimensions.
bool doLoad (LAS_FIELDS field) const
Whether to load a given field.
void clearEVLRs ()
Clears the 'extra bytes' record.
void setInfos (QString filename, unsigned pointCount, const CCVector3d &bbMin, const CCVector3d &bbMax)
Sets the information about the file.
void addEVLR (QString description)
Adds an 'extra bytes' record entry.
bool doLoadEVLR (size_t index) const
Returns whether an EVLR is selected for laoding or not.
bool autoSkipMode () const
Auto-skip mode (to use the same parameters for ALL files afterwards)
bool forced8bitRgbMode () const
Whether 8-bit RGB mode is forced or not.
void resetApplyAll ()
Resets the "apply all" flag (if set)
bool getTimeShift (double &timeShift) const
Returns the timeshift (if any)
Protected Member Functions
void onApplyAll ()
void onBrowse ()
Protected Attributes
bool m_autoSkip
Detailed Description
Dialog to choose the LAS fields to load.
Definition at line 25 of file LASOpenDlg.h.
Constructor & Destructor Documentation
LASOpenDlg()
LASOpenDlg::LASOpenDlg (QWidget * parent = nullptr) explicit
Default constructor.
Definition at line 19 of file LASOpenDlg.cpp.
References clearEVLRs(), onApplyAll(), and onBrowse().
Member Function Documentation
addEVLR()
void LASOpenDlg::addEVLR (QString description)
Adds an 'extra bytes' record entry.
Definition at line 207 of file LASOpenDlg.cpp.
autoSkipMode()
bool LASOpenDlg::autoSkipMode () const inline
Auto-skip mode (to use the same parameters for ALL files afterwards)
Definition at line 54 of file LASOpenDlg.h.
References m_autoSkip.
clearEVLRs()
void LASOpenDlg::clearEVLRs ()
Clears the 'extra bytes' record.
Definition at line 180 of file LASOpenDlg.cpp.
Referenced by LASOpenDlg().
doLoad()
bool LASOpenDlg::doLoad (LAS_FIELDS field) const
Whether to load a given field.
Definition at line 101 of file LASOpenDlg.cpp.
References LAS_BLUE, LAS_CLASSIF_KEYPOINT, LAS_CLASSIF_OVERLAP, LAS_CLASSIF_SYNTHETIC, LAS_CLASSIF_VALUE, LAS_CLASSIF_WITHHELD, LAS_CLASSIFICATION, LAS_EXTRA, LAS_FLIGHT_LINE_EDGE, LAS_GREEN, LAS_INTENSITY, LAS_INVALID, LAS_NUMBER_OF_RETURNS, LAS_POINT_SOURCE_ID, LAS_RED, LAS_RETURN_NUMBER, LAS_SCAN_ANGLE_RANK, LAS_SCAN_DIRECTION, LAS_TIME, LAS_USER_DATA, LAS_X, LAS_Y, and LAS_Z.
doLoadEVLR()
bool LASOpenDlg::doLoadEVLR (size_t index) const
Returns whether an EVLR is selected for laoding or not.
Definition at line 217 of file LASOpenDlg.cpp.
forced8bitRgbMode()
bool LASOpenDlg::forced8bitRgbMode () const
Whether 8-bit RGB mode is forced or not.
Definition at line 224 of file LASOpenDlg.cpp.
getTimeShift()
bool LASOpenDlg::getTimeShift (double & timeShift) const
Returns the timeshift (if any)
Definition at line 228 of file LASOpenDlg.cpp.
onApplyAll()
void LASOpenDlg::onApplyAll () protected
Definition at line 42 of file LASOpenDlg.cpp.
References m_autoSkip.
Referenced by LASOpenDlg().
onBrowse()
void LASOpenDlg::onBrowse () protected
Definition at line 47 of file LASOpenDlg.cpp.
Referenced by LASOpenDlg().
resetApplyAll()
void LASOpenDlg::resetApplyAll ()
Resets the "apply all" flag (if set)
Definition at line 40 of file LASOpenDlg.cpp.
References m_autoSkip.
setDimensions()
void LASOpenDlg::setDimensions (const std::vector< std::string > & dimensions)
Sets available dimensions.
Definition at line 69 of file LASOpenDlg.cpp.
References FieldIsPresent(), LAS_BLUE, LAS_CLASSIFICATION, LAS_FLIGHT_LINE_EDGE, LAS_GREEN, LAS_INTENSITY, LAS_NUMBER_OF_RETURNS, LAS_POINT_SOURCE_ID, LAS_RED, LAS_RETURN_NUMBER, LAS_SCAN_ANGLE_RANK, LAS_SCAN_DIRECTION, LAS_TIME, and LAS_USER_DATA.
setInfos()
void LASOpenDlg::setInfos (QString filename, unsigned pointCount, const CCVector3d & bbMin, const CCVector3d & bbMax)
Sets the information about the file.
Definition at line 186 of file LASOpenDlg.cpp.
References e57::toString(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Member Data Documentation
m_autoSkip
bool LASOpenDlg::m_autoSkip protected
Definition at line 70 of file LASOpenDlg.h.
Referenced by autoSkipMode(), onApplyAll(), and resetApplyAll().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qPDALIO/include/LASOpenDlg.h
/root/ACloudViewer/plugins/core/IO/qPDALIO/src/LASOpenDlg.cpp