ACloudViewer: VtkUtils::VtkPlotWidget Class Reference
VtkUtils::VtkPlotWidget Class Reference abstract
#include <vtkplotwidget.h>
Public Member Functions
VtkPlotWidget (QWidget *parent=nullptr)
virtual ~VtkPlotWidget ()
virtual vtkContextItem * chart () const =0
vtkContextView * contextView () const
vtkRenderWindow * GetRenderWindow ()
Protected Member Functions
void init ()
Detailed Description
Definition at line 35 of file vtkplotwidget.h.
Constructor & Destructor Documentation
VtkPlotWidget()
VtkUtils::VtkPlotWidget::VtkPlotWidget (QWidget * parent = nullptr) explicit
Definition at line 39 of file vtkplotwidget.cpp.
References init().
~VtkPlotWidget()
VtkUtils::VtkPlotWidget::~VtkPlotWidget () virtual
Definition at line 45 of file vtkplotwidget.cpp.
Member Function Documentation
chart()
virtual vtkContextItem* VtkUtils::VtkPlotWidget::chart () const pure virtual
Implemented in VtkUtils::VtkPlotPieWidget, VtkUtils::VtkPlot3DWidget, and VtkUtils::VtkPlot2DWidget.
contextView()
vtkContextView * VtkUtils::VtkPlotWidget::contextView () const
Definition at line 54 of file vtkplotwidget.cpp.
Referenced by VtkUtils::VtkPlot2DWidget::chart(), VtkUtils::VtkPlot3DWidget::chart(), and VtkUtils::VtkPlotPieWidget::chart().
GetRenderWindow()
vtkRenderWindow* VtkUtils::VtkPlotWidget::GetRenderWindow () inline
Definition at line 44 of file vtkplotwidget.h.
Referenced by init().
init()
void VtkUtils::VtkPlotWidget::init () protected
Definition at line 47 of file vtkplotwidget.cpp.
References GetRenderWindow().
Referenced by VtkPlotWidget().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/vtkplotwidget.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/vtkplotwidget.cpp