ACloudViewer: qVoxFallProcess Class Reference
qVoxFallProcess Class Reference
VoxFall process.
#include <qVoxFallProcess.h>
Static Public Member Functions
static bool Compute (const qVoxFallDialog &dlg, QString &errorMessage, bool allowDialogs, QWidget *parentWidget=nullptr, ecvMainAppInterface *app=nullptr)
Detailed Description
VoxFall process.
See "VoxFall: Non-Parametric Volumetric Change Detection for Rockfalls", Farmakis, I., Guccione, D.E., Thoeni, K. and Giacomini, A., 2024, Computers and Geosciences
Definition at line 23 of file qVoxFallProcess.h.
Member Function Documentation
Compute()
bool qVoxFallProcess::Compute (const qVoxFallDialog & dlg, QString & errorMessage, bool allowDialogs, QWidget * parentWidget = nullptr, ecvMainAppInterface * app = nullptr) static
Definition at line 347 of file qVoxFallProcess.cpp.
References cloudViewer::GenericTriangle::_getA(), cloudViewer::GenericTriangle::_getB(), cloudViewer::GenericTriangle::_getC(), ccMesh::_getNextTriangle(), ccHObject::addChild(), ccPointCloud::addScalarField(), ccHObject::applyGLTransformation_recursive(), VoxFallParams::bbDims, VoxFallParams::centroid, CHANGE_TYPE_SF_NAME, VoxFallParams::changeType, VoxFallParams::changeTypeSF, ccMesh::cloneMesh(), CLUSTER_SF_NAME, ClusterEmptySpace(), VoxFallParams::clusterIndices, VoxFallParams::clusterLabel, VoxFallParams::clusterOutterVoxelCount, VoxFallParams::clusters, VoxFallParams::clusterSF, ComputeClusterVolume(), ccScalarField::computeMinAndMax(), count, qVoxFallTransform::CreateVoxelMesh(), VoxFallParams::currentLabel, VoxFallParams::emptyVoxelCount, VoxFallParams::exportBlocksAsMeshes, VoxFallParams::exportLossGain, VoxFallParams::extent, qVoxFallDialog::getAzimuth(), qVoxFallDialog::getExportMeshesActivation(), qVoxFallDialog::getLossGainActivation(), qVoxFallDialog::getMaxThreadCount(), qVoxFallDialog::getMesh1(), qVoxFallDialog::getMesh2(), ccObject::getName(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::ScalarField::getValue(), GetVoxelOccupancy(), GetVoxelOccupancyBefore(), qVoxFallDialog::getVoxelSize(), InitializeOutputCloud(), VoxFallParams::isEmpty, VoxFallParams::isEmptyBefore, CCShareable::link(), VoxFallParams::maxBound, ccMesh::merge(), VoxFallParams::minBound, NAN_VALUE, VoxFallParams::nbs, VoxFallParams::nonEmptyVoxelsVisited, nProgress, VoxFallParams::nProgress, cloudViewer::NormalizedProgress::oneStep(), ccMesh::placeIteratorAtBeginning(), ccPointCloud::reserve(), cloudViewer::ScalarField::resizeSafe(), s_VoxFallParams, ccPointCloud::setCurrentDisplayedScalarField(), ccObject::setEnabled(), ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), cloudViewer::ScalarField::setValue(), ccDrawableObject::setVisible(), ccDrawableObject::showSF(), ccMesh::size(), ecvProgressDialog::start(), VoxFallParams::steps, cloudViewer::CCMiscTools::TriBoxOverlap(), UNCERTAINTY_SF_NAME, VoxFallParams::uncertaintySF, ecvProgressDialog::update(), VOLUME_SF_NAME, VoxFallParams::volumes, VoxFallParams::volumeSF, VoxFallParams::voxelSize, VoxFallParams::voxfall, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qVoxFall/include/qVoxFallProcess.h
/root/ACloudViewer/plugins/core/Standard/qVoxFall/src/qVoxFallProcess.cpp