ACloudViewer: ccPointCloud Class Reference
ccPointCloud Class Reference
A 3D cloud and its associated features (color, normals, scalar fields, etc.)
#include <ecvPointCloud.h>
Classes
struct Grid
Grid structure.
struct RgbFilterOptions
RGB filter options.
struct UnrollBaseParams
struct UnrollConeParams
struct UnrollCylinderParams
class VBO
struct vboSet
VBO set.
Public Types
enum CLONE_WARNINGS { WRN_OUT_OF_MEM_FOR_COLORS = 1 , WRN_OUT_OF_MEM_FOR_NORMALS = 2 , WRN_OUT_OF_MEM_FOR_SFS = 4 , WRN_OUT_OF_MEM_FOR_FWF = 8 }
Warnings for the partialClone method (bit flags)
enum RGB_FILTER_TYPES {
NONE , BILATERAL , GAUSSIAN , MEAN ,
MEDIAN
}
RGB filter types.
enum UnrollMode { CYLINDER = 0 , CONE = 1 , STRAIGHTENED_CONE = 2 , STRAIGHTENED_CONE2 = 3 }
using BaseClass = cloudViewer::PointCloudTpl< ccGenericPointCloud >
Base class (shortcut)
using FWFDescriptorSet = QMap< uint8_t, WaveformDescriptor >
Waveform descriptors set.
using FWFDataContainer = std::vector< uint8_t >
Waveform data container.
using SharedFWFDataContainer = QSharedPointer< const FWFDataContainer >
Public Types inherited from ccGenericPointCloud
using VisibilityTableType = std::vector< unsigned char >
Array of "visibility" information for each point.
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Public Types inherited from cloudViewer::GenericCloud
using genericPointAction = std::function< void(const CCVector3 &, ScalarType &)>
Generic function applied to a point (used by foreach)
Public Member Functions
ccPointCloud (QString name=QString()) throw ()
Default constructor.
ccPointCloud (const ccPointCloud &cloud)
ccPointCloud (const std::vector< Eigen::Vector3d > &points, const std::string &name="cloud")
~ccPointCloud () override
Default destructor.
CV_CLASS_ENUM getClassID () const override
Returns class ID.
ccPointCloud * partialClone (const cloudViewer::ReferenceCloud *selection, int *warnings=nullptr, bool withChildEntities=true) const
Creates a new point cloud object from a ReferenceCloud (selection)
ccPointCloud * cloneThis (ccPointCloud *destCloud=nullptr, bool ignoreChildren=false)
Clones this entity.
ccGenericPointCloud * clone (ccGenericPointCloud *destCloud=nullptr, bool ignoreChildren=false) override
Clones this entity.
ccPointCloud & operator= (const ccPointCloud &cloud)
Fuses another 3D entity with this one.
const ccPointCloud & operator+= (const ccPointCloud &cloud)
const ccPointCloud & operator+= (ccPointCloud *)
ccPointCloud operator+ (const ccPointCloud &cloud) const
void clear () override
Clears the entity from all its points and features.
void unalloactePoints ()
Erases the cloud points.
void unallocateColors ()
Erases the cloud colors.
void unallocateNorms ()
Erases the cloud normals.
void colorsHaveChanged ()
void normalsHaveChanged ()
Notify a modification of normals display parameters or contents.
void pointsHaveChanged ()
Notify a modification of points display parameters or contents.
bool reserve (unsigned numberOfPoints) override
Reserves memory for all the active features.
bool reserveThePointsTable (unsigned _numberOfPoints)
Reserves memory to store the points coordinates.
bool reserveTheRGBTable ()
Reserves memory to store the RGB colors.
bool reserveTheNormsTable ()
Reserves memory to store the compressed normals.
bool resize (unsigned numberOfPoints) override
Resizes all the active features arrays.
bool resizeTheRGBTable (bool fillWithWhite=false)
Resizes the RGB colors array.
bool resizeTheNormsTable ()
Resizes the compressed normals array.
void shrinkToFit ()
Removes unused capacity.
ccScalarField * getCurrentDisplayedScalarField () const
Returns the currently displayed scalar (or 0 if none)
int getCurrentDisplayedScalarFieldIndex () const
Returns the currently displayed scalar field index (or -1 if none)
void setCurrentDisplayedScalarField (int index)
Sets the currently displayed scalar field.
void deleteScalarField (int index) override
Deletes a specific scalar field.
void deleteAllScalarFields () override
Deletes all scalar fields associated to this cloud.
int addScalarField (const char *uniqueName) override
Creates a new scalar field and registers it.
bool sfColorScaleShown () const
Returns whether color scale should be displayed or not.
void showSFColorsScale (bool state)
Sets whether color scale should be displayed or not.
size_t gridCount () const
Returns the number of associated grids.
Grid::Shared & grid (size_t gridIndex)
Returns an associated grid.
const Grid::Shared & grid (size_t gridIndex) const
Returns an associated grid (const verson)
bool addGrid (Grid::Shared grid)
Adds an associated grid.
void removeGrids ()
Remove all associated grids.
ccMesh * triangulateGrid (const Grid &grid, double minTriangleAngle_deg=0.0) const
Meshes a scan grid.
bool computeNormalsWithGrids (double minTriangleAngle_deg=1.0, ecvProgressDialog *pDlg=nullptr)
Compute the normals with the associated grid structure(s)
bool orientNormalsWithGrids (ecvProgressDialog *pDlg=nullptr)
Orient the normals with the associated grid structure(s)
bool orientNormalsTowardViewPoint (CCVector3 &VP, ecvProgressDialog *pDlg=nullptr)
Normals are forced to point to O.
bool computeNormalsWithOctree (CV_LOCAL_MODEL_TYPES model, ccNormalVectors::Orientation preferredOrientation, PointCoordinateType defaultRadius, ecvProgressDialog *pDlg=nullptr)
Compute the normals by approximating the local surface around each point.
bool orientNormalsWithMST (unsigned kNN=6, ecvProgressDialog *pDlg=nullptr)
Orient the normals with a Minimum Spanning Tree.
bool orientNormalsWithFM (unsigned char level, ecvProgressDialog *pDlg=nullptr)
Orient normals with Fast Marching.
bool hasFWF () const
Returns whether the cloud has associated Full WaveForm data.
ccWaveformProxy waveformProxy (unsigned index) const
Returns a proxy on a given waveform.
FWFDescriptorSet & fwfDescriptors ()
Gives access to the FWF descriptors.
const FWFDescriptorSet & fwfDescriptors () const
Gives access to the FWF descriptors (const version)
std::vector< ccWaveform > & waveforms ()
Gives access to the associated FWF data.
const std::vector< ccWaveform > & waveforms () const
Gives access to the associated FWF data (const version)
bool reserveTheFWFTable ()
Reserves the FWF table.
bool resizeTheFWFTable ()
Resizes the FWF table.
SharedFWFDataContainer & fwfData ()
Gives access to the associated FWF data container.
const SharedFWFDataContainer & fwfData () const
Gives access to the associated FWF data container (const version)
bool compressFWFData ()
Compresses the associated FWF data container.
bool computeFWFAmplitude (double &minVal, double &maxVal, ecvProgressDialog *pDlg=nullptr) const
Computes the maximum amplitude of all associated waveforms.
void clearFWFData ()
Clears all associated FWF data.
CCVector3 computeGravityCenter ()
Returns the cloud gravity center.
void invalidateBoundingBox () override
Invalidates bounding box.
void getDrawingParameters (glDrawParams &params) const override
Returns main OpenGL parameters for this entity.
unsigned getUniqueIDForDisplay () const override
Returns object unqiue ID used for display.
bool hasColors () const override
Returns whether colors are enabled or not.
bool hasNormals () const override
Returns whether normals are enabled or not.
bool hasScalarFields () const override
Returns whether one or more scalar fields are instantiated.
bool hasDisplayedScalarField () const override
Returns whether an active scalar field is available or not.
unsigned char testVisibility (const CCVector3 &P) const override
bool normalsAvailable () const override
Returns whether normals are available.
const CCVector3 * getNormal (unsigned pointIndex) const override
If per-point normals are available, returns the one at a specific index.
const ecvColor::Rgb * getScalarValueColor (ScalarType d) const override
Returns color corresponding to a given scalar value.
const ecvColor::Rgb * getPointScalarValueColor (unsigned pointIndex) const override
Returns color corresponding to a given point associated scalar value.
ScalarType getPointDisplayedDistance (unsigned pointIndex) const override
Returns scalar value associated to a given point.
const ecvColor::Rgb & getPointColor (unsigned pointIndex) const override
Returns color corresponding to a given point.
const ColorsTableType & getPointColors () const
ecvColor::Rgb & getPointColorPtr (size_t pointIndex)
Eigen::Vector3d getEigenColor (size_t index) const
std::vector< Eigen::Vector3d > getEigenColors () const
void setEigenColors (const std::vector< Eigen::Vector3d > &colors)
const CompressedNormType & getPointNormalIndex (unsigned pointIndex) const override
Returns compressed normal corresponding to a given point.
const CCVector3 & getPointNormal (unsigned pointIndex) const override
Returns normal corresponding to a given point.
CCVector3 & getPointNormalPtr (size_t pointIndex) const
std::vector< CCVector3 > getPointNormals () const
std::vector< CCVector3 * > getPointNormalsPtr () const
void setPointNormals (const std::vector< CCVector3 > &normals)
Eigen::Vector3d getEigenNormal (size_t index) const
std::vector< Eigen::Vector3d > getEigenNormals () const
void setEigenNormals (const std::vector< Eigen::Vector3d > &normals)
cloudViewer::ReferenceCloud * crop (const ccBBox &box, bool inside=true) override
Crops the cloud inside (or outside) a bounding box.
cloudViewer::ReferenceCloud * crop (const ecvOrientedBBox &bbox) override
virtual void applyRigidTransformation (const ccGLMatrix &trans) override
Applies a rigid transformation (rotation + translation)
virtual void scale (PointCoordinateType fx, PointCoordinateType fy, PointCoordinateType fz, CCVector3 center=CCVector3(0, 0, 0)) override
Multiplies all coordinates by constant factors (one per dimension)
void refreshBB () override
Forces bounding-box update.
ccGenericPointCloud * createNewCloudFromVisibilitySelection (bool removeSelectedPoints=false, VisibilityTableType *visTable=nullptr, std::vector< int > *newIndexesOfRemainingPoints=nullptr, bool silent=false, cloudViewer::ReferenceCloud *selection=nullptr) override
bool removeVisiblePoints (VisibilityTableType *visTable=nullptr, std::vector< int > *newIndexes=nullptr) override
Removes all the 'visible' points (as defined by the visibility array)
void enableVisibilityCheck (bool state)
bool hasSensor () const
Returns whether the mesh as an associated sensor or not.
QSharedPointer< cloudViewer::ReferenceCloud > computeCPSet (ccGenericPointCloud &otherCloud, cloudViewer::GenericProgressCallback *progressCb=nullptr, unsigned char octreeLevel=0)
Computes the closest point of this cloud relatively to another cloud.
bool interpolateColorsFrom (ccGenericPointCloud *cloud, cloudViewer::GenericProgressCallback *progressCb=nullptr, unsigned char octreeLevel=0)
Interpolate colors from another cloud (nearest neighbor only)
void setPointColor (size_t pointIndex, const ecvColor::Rgb &col)
Sets a particular point color.
void setPointColor (size_t pointIndex, const ecvColor::Rgba &col)
void setPointColor (size_t pointIndex, const Eigen::Vector3d &col)
void setEigenColor (size_t index, const Eigen::Vector3d &color)
void setPointNormalIndex (size_t pointIndex, CompressedNormType norm)
Sets a particular point compressed normal.
void setPointNormal (size_t pointIndex, const CCVector3 &N)
Sets a particular point normal (shortcut)
void setEigenNormal (size_t index, const Eigen::Vector3d &normal)
void addNormIndex (CompressedNormType index)
Pushes a compressed normal vector.
void addNorm (const CCVector3 &N)
Pushes a normal vector on stack (shortcut)
void addEigenNorm (const Eigen::Vector3d &N)
void addEigenNorms (const std::vector< Eigen::Vector3d > &normals)
void addNorms (const std::vector< CCVector3 > &Ns)
void addNorms (const std::vector< CompressedNormType > &idxes)
std::vector< CompressedNormType > getNorms () const
void getNorms (std::vector< CompressedNormType > &idxes) const
void addNormAtIndex (const PointCoordinateType *N, unsigned index)
Adds a normal vector to the one at a specific index.
void setNormsTable (NormsIndexesTableType *norms)
Sets the (compressed) normals table.
bool convertNormalToRGB ()
Converts normals to RGB colors.
bool convertNormalToDipDirSFs (ccScalarField *dipSF, ccScalarField *dipDirSF)
Converts normals to two scalar fields: 'dip' and 'dip direction'.
void addRGBColor (const ecvColor::Rgb &C)
Pushes an RGB color on stack.
void addRGBColors (const std::vector< ecvColor::Rgb > &colors)
void addEigenColor (const Eigen::Vector3d &color)
void addEigenColors (const std::vector< Eigen::Vector3d > &colors)
void addRGBColor (ColorCompType r, ColorCompType g, ColorCompType b)
Pushes an RGB color on stack (shortcut)
void addGreyColor (ColorCompType g)
Pushes a grey color on stack (shortcut)
bool convertRGBToGreyScale ()
Converts RGB to grey scale colors.
bool colorize (float r, float g, float b)
Multiplies all color components of all points by coefficients.
bool setRGBColorByHeight (unsigned char heightDim, ccColorScale::Shared colorScale)
Assigns color to points proportionnaly to their 'height'.
bool setRGBColorByBanding (unsigned char dim, double freq)
Assigns color to points by 'banding'.
bool convertCurrentScalarFieldToColors (bool mixWithExistingColor=false)
bool setRGBColorWithCurrentScalarField (bool mixWithExistingColor=false)
Sets RGB colors with current scalar field (values & parameters)
bool setRGBColor (ColorCompType r, ColorCompType g, ColorCompType b)
Set a unique color for the whole cloud (shortcut)
bool setRGBColor (const ecvColor::Rgb &col)
Set a unique color for the whole cloud.
bool applyFilterToRGB (PointCoordinateType sigma, PointCoordinateType sigmaSF, RgbFilterOptions filterParams, cloudViewer::GenericProgressCallback *progressCb=nullptr)
Applies a spatial Gaussian filter on RGB colors.
void invertNormals ()
Inverts normals (if any)
ccPointCloud * filterPointsByScalarValue (ScalarType minVal, ScalarType maxVal, bool outside=false)
Filters out points whose scalar values falls into an interval.
ccPointCloud * filterPointsByScalarValue (std::vector< ScalarType > values, bool outside=false)
Filters out points whose scalar values falls into an interval.
void hidePointsByScalarValue (ScalarType minVal, ScalarType maxVal)
Hides points whose scalar values falls into an interval.
void hidePointsByScalarValue (std::vector< ScalarType > values)
Hides points whose scalar values falls into an interval.
ccPointCloud * unroll (UnrollMode mode, UnrollBaseParams *params, bool exportDeviationSF=false, double startAngle_deg=0.0, double stopAngle_deg=360.0, cloudViewer::GenericProgressCallback *progressCb=nullptr) const
Unrolls the cloud and its normals on a cylinder or a cone.
void addColorRampInfo (CC_DRAW_CONTEXT &context)
Adds associated SF color ramp info to current GL context.
int addScalarField (ccScalarField *sf)
Adds an existing scalar field to this cloud.
ColorsTableType * rgbColors () const
Returns pointer on RGB colors table.
NormsIndexesTableType * normals () const
Returns pointer on compressed normals indexes table.
cloudViewer::ReferenceCloud * crop2D (const ccPolyline *poly, unsigned char orthoDim, bool inside=true)
Crops the cloud inside (or outside) a 2D polyline.
const ccPointCloud & append (ccPointCloud *cloud, unsigned pointCountBefore, bool ignoreChildren=false)
Appends a cloud to this one.
bool enhanceRGBWithIntensitySF (int sfIdx, bool useCustomIntensityRange=false, double minI=0.0, double maxI=1.0)
bool exportCoordToSF (bool exportDims[3])
Exports the specified coordinate dimension(s) to scalar field(s)
bool setCoordFromSF (bool importDims[3], cloudViewer::ScalarField *sf, PointCoordinateType defaultValueForNaN)
Sets coordinate(s) from a scalar field.
bool exportNormalToSF (bool exportDims[3])
Exports the specified normal dimension(s) to scalar field(s)
virtual bool IsEmpty () const override
virtual Eigen::Vector3d GetMinBound () const override
Returns min bounds for geometry coordinates.
virtual Eigen::Vector3d GetMaxBound () const override
Returns max bounds for geometry coordinates.
virtual Eigen::Vector3d GetCenter () const override
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const override
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const override
virtual ccPointCloud & Transform (const Eigen::Matrix4d &trans) override
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual ccPointCloud & Translate (const Eigen::Vector3d &translation, bool relative=true) override
Apply translation to the geometry coordinates.
ccPointCloud & Translate (const CCVector3 &T)
virtual ccPointCloud & Scale (const double s, const Eigen::Vector3d &center) override
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual ccPointCloud & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center) override
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
bool HasCovariances () const
Returns 'true' if the point cloud contains per-point covariance matrix.
ccPointCloud & NormalizeNormals ()
Normalize point normals to length 1.`.
std::shared_ptr< ccPointCloud > SelectByIndex (const std::vector< size_t > &indices, bool invert=false) const
Function to select points from input ccPointCloud into output ccPointCloud.
ccPointCloud & RemoveNonFinitePoints (bool remove_nan=true, bool remove_infinite=true)
Remove all points fromt he point cloud that have a nan entry, or infinite entries.
std::shared_ptr< ccPointCloud > VoxelDownSample (double voxel_size)
Function to downsample input ccPointCloud into output ccPointCloud with a voxel.
std::tuple< std::shared_ptr< ccPointCloud >, Eigen::MatrixXi, std::vector< std::vector< int > > > VoxelDownSampleAndTrace (double voxel_size, const Eigen::Vector3d &min_bound, const Eigen::Vector3d &max_bound, bool approximate_class=false) const
Function to downsample using geometry.ccPointCloud.VoxelDownSample.
std::shared_ptr< ccPointCloud > UniformDownSample (size_t every_k_points) const
Function to downsample input ccPointCloud into output ccPointCloud uniformly.
std::shared_ptr< ccPointCloud > RandomDownSample (double sampling_ratio) const
Function to downsample input pointcloud into output pointcloud randomly.
std::shared_ptr< ccPointCloud > FarthestPointDownSample (const size_t num_samples, const size_t start_index=0) const
Function to downsample input pointcloud into output pointcloud with a set of points has farthest distance.
std::shared_ptr< ccPointCloud > Crop (const ccBBox &bbox) const
Function to crop ccPointCloud into output ccPointCloud.
std::shared_ptr< ccPointCloud > Crop (const ecvOrientedBBox &bbox) const
Function to crop ccPointCloud into output ccPointCloud.
std::tuple< std::shared_ptr< ccPointCloud >, std::vector< size_t > > RemoveRadiusOutliers (size_t nb_points, double search_radius) const
Function to remove points that have less than nb_points in a sphere of a given radius.
std::tuple< std::shared_ptr< ccPointCloud >, std::vector< size_t > > RemoveStatisticalOutliers (size_t nb_neighbors, double std_ratio) const
Function to remove points that are further away from their nb_neighbor neighbors in average.
bool EstimateNormals (const cloudViewer::geometry::KDTreeSearchParam &search_param=cloudViewer::geometry::KDTreeSearchParamKNN(), bool fast_normal_computation=true)
Function to compute the normals of a point cloud.
bool OrientNormalsToAlignWithDirection (const Eigen::Vector3d &orientation_reference=Eigen::Vector3d(0.0, 0.0, 1.0))
Function to orient the normals of a point cloud.
bool OrientNormalsTowardsCameraLocation (const Eigen::Vector3d &camera_location=Eigen::Vector3d::Zero())
Function to orient the normals of a point cloud.
void OrientNormalsConsistentTangentPlane (size_t k)
Function to consistently orient estimated normals based on consistent tangent planes as described in Hoppe et al., "Surface Reconstruction from Unorganized Points", 1992.
std::vector< double > ComputePointCloudDistance (const ccPointCloud &target)
Function to compute the point to point distances between point clouds.
void EstimateCovariances (const cloudViewer::geometry::KDTreeSearchParam &search_param=cloudViewer::geometry::KDTreeSearchParamKNN())
Function to compute the covariance matrix for each point of a point cloud.
std::vector< double > ComputeMahalanobisDistance () const
Function to compute the Mahalanobis distance for points in an input point cloud.
std::vector< double > ComputeNearestNeighborDistance () const
double ComputeResolution () const
std::tuple< std::shared_ptr< ccMesh >, std::vector< size_t > > ComputeConvexHull () const
Function that computes the convex hull of the point cloud using qhull.
std::tuple< std::shared_ptr< ccMesh >, std::vector< size_t > > HiddenPointRemoval (const Eigen::Vector3d &camera_location, const double radius) const
This is an implementation of the Hidden Point Removal operator described in Katz et. al. 'Direct Visibility of Point Sets', 2007.
std::vector< int > ClusterDBSCAN (double eps, size_t min_points, bool print_progress=false) const
Cluster ccPointCloud using the DBSCAN algorithm Ester et al., "A Density-Based Algorithm for Discovering Clusters in Large Spatial Databases with Noise", 1996.
std::tuple< Eigen::Vector4d, std::vector< size_t > > SegmentPlane (const double distance_threshold=0.01, const int ransac_n=3, const int num_iterations=100) const
Segment ccPointCloud plane using the RANSAC algorithm.
std::shared_ptr< ccPointCloud > CreateFromVoxelGrid (const cloudViewer::geometry::VoxelGrid &voxel_grid)
Function to create a PointCloud from a VoxelGrid.
ccPointCloud & PaintUniformColor (const Eigen::Vector3d &color)
Assigns each vertex in the ccMesh the same color.
bool initLOD ()
Intializes the LOD structure.
void clearLOD ()
Clears the LOD structure.
Public Member Functions inherited from cloudViewer::PointCloudTpl< ccGenericPointCloud >
PointCloudTpl ()
Default constructor.
virtual ~PointCloudTpl ()
Default destructor.
unsigned size () const override
void forEach (GenericCloud::genericPointAction action) override
void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax) override
void placeIteratorAtBeginning () override
const CCVector3 * getNextPoint () override
bool enableScalarField () override
bool isScalarFieldEnabled () const override
void setPointScalarValue (unsigned pointIndex, ScalarType value) override
ScalarType getPointScalarValue (unsigned pointIndex) const override
const CCVector3 * getPoint (unsigned index) const override
void getPoint (unsigned index, CCVector3 &P) const override
void getPoint (unsigned index, double P[3]) const override
CCVector3 * getPointPtr (size_t index)
std::vector< CCVector3 > & getPoints ()
const std::vector< CCVector3 > & getPoints () const
const CCVector3 * getPointPersistentPtr (unsigned index) override
const CCVector3 * getPointPersistentPtr (unsigned index) const
void reset ()
Clears the cloud database.
void addPoint (const CCVector3 &P)
Adds a 3D point to the database.
void addPoint (double x, double y, double z)
void addPoint (double xyz[3])
void setPoint (size_t index, const CCVector3 &P)
void setEigenPoint (size_t index, const Eigen::Vector3d &point)
void addEigenPoint (const Eigen::Vector3d &point)
void addPoints (const std::vector< CCVector3 > &points)
void addPoints (const std::vector< Eigen::Vector3d > &points)
Eigen::Vector3d getEigenPoint (size_t index) const
std::vector< Eigen::Vector3d > getEigenPoints () const
void setEigenPoints (const std::vector< Eigen::Vector3d > &points)
unsigned getNumberOfScalarFields () const
Returns the number of associated (and active) scalar fields.
ScalarField * getScalarField (int index) const
Returns a pointer to a specific scalar field.
const char * getScalarFieldName (int index) const
Returns the name of a specific scalar field.
int getScalarFieldIndexByName (const char *name) const
Returns the index of a scalar field represented by its name.
ScalarField * getCurrentInScalarField () const
Returns the scalar field currently associated to the cloud input.
ScalarField * getCurrentOutScalarField () const
Returns the scalar field currently associated to the cloud output.
void setCurrentInScalarField (int index)
Sets the INPUT scalar field.
int getCurrentInScalarFieldIndex ()
Returns current INPUT scalar field index (or -1 if none)
void setCurrentOutScalarField (int index)
Sets the OUTPUT scalar field.
int getCurrentOutScalarFieldIndex ()
Returns current OUTPUT scalar field index (or -1 if none)
void setCurrentScalarField (int index)
Sets both the INPUT & OUTPUT scalar field.
bool renameScalarField (int index, const char *newName)
Renames a specific scalar field.
unsigned capacity () const
Returns cloud capacity (i.e. reserved size)
Public Member Functions inherited from ccGenericPointCloud
ccGenericPointCloud (QString name=QString())
Default constructor.
ccGenericPointCloud (const ccGenericPointCloud &cloud)
Copy constructor.
~ccGenericPointCloud () override
Default destructor.
virtual ccOctree::Shared computeOctree (cloudViewer::GenericProgressCallback *progressCb=nullptr, bool autoAddChild=true)
Computes the cloud octree.
virtual ccOctree::Shared getOctree () const
Returns the associated octree (if any)
virtual void setOctree (ccOctree::Shared octree, bool autoAddChild=true)
Sets the associated octree.
virtual ccOctreeProxy * getOctreeProxy () const
Returns the associated octree proxy (if any)
virtual void deleteOctree ()
Erases the octree.
virtual VisibilityTableType & getTheVisibilityArray ()
Returns associated visibility array.
virtual const VisibilityTableType & getTheVisibilityArray () const
Returns associated visibility array (const version)
virtual cloudViewer::ReferenceCloud * getTheVisiblePoints (const VisibilityTableType *visTable=nullptr, bool silent=false, cloudViewer::ReferenceCloud *selection=nullptr) const
Returns a ReferenceCloud equivalent to the visibility array.
virtual bool isVisibilityTableInstantiated () const
Returns whether the visibility array is allocated or not.
virtual bool resetVisibilityArray ()
Resets the associated visibility array.
virtual void invertVisibilityArray ()
Inverts the visibility array.
virtual void unallocateVisibilityArray ()
Erases the points visibility information.
ccBBox getOwnBB (bool withGLFeatures=false) override
Returns the entity's own bounding-box.
bool isSerializable () const override
Returns whether object is serializable of not.
void setPointSize (unsigned size=0)
Sets point size.
unsigned char getPointSize () const
Returns current point size.
void importParametersFrom (const ccGenericPointCloud *cloud)
Imports the parameters from another cloud.
bool pointPicking (const CCVector2d &clickPos, const ccGLCameraParameters &camera, int &nearestPointIndex, double &nearestSquareDist, double pickWidth=2.0, double pickHeight=2.0, bool autoComputeOctree=false)
Point picking (brute force or octree-driven)
std::tuple< Eigen::Vector3d, Eigen::Matrix3d > computeMeanAndCovariance () const
cloudViewer::SquareMatrixd computeCovariance () const
Public Member Functions inherited from ccShiftedObject
ccShiftedObject (QString name=QString())
Default constructor.
ccShiftedObject (const ccShiftedObject &s)
Copy constructor.
void copyGlobalShiftAndScale (const ccShiftedObject &s)
Copies the Global Shift and Scale from another entity.
virtual void setGlobalShift (double x, double y, double z)
Sets shift applied to original coordinates (information storage only)
virtual void setGlobalShift (const CCVector3d &shift)
Sets shift applied to original coordinates (information storage only)
virtual const CCVector3d & getGlobalShift () const
Returns the shift applied to original coordinates.
virtual void setGlobalScale (double scale)
virtual double getGlobalScale () const
Returns the scale applied to original coordinates.
bool isShifted () const
Returns whether the cloud is shifted or not.
template<typename T >
CCVector3d toGlobal3d (const Vector3Tpl< T > &Plocal) const
Returns the point back-projected into the original coordinates system.
template<typename T >
CCVector3d toLocal3d (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
template<typename T >
CCVector3 toLocal3pc (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner) override
GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false) override
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual Eigen::Vector2d GetMin2DBound () const
virtual Eigen::Vector2d GetMax2DBound () const
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual ccBBox getOwnFitBB (ccGLMatrix &trans)
Returns best-fit bounding-box (if available)
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col)
Draws the entity (and its children) bounding-box.
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
bool isSerializable () const override
Returns whether object is serializable of not.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual const ccGLMatrix & getGLTransformationHistory () const
Returns the transformation 'history' matrix.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual bool normalsShown () const
Returns whether normals are shown or not.
virtual void showNormals (bool state)
Sets normals visibility.
virtual void toggleNormals ()
Toggles normals display state.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void toggleMaterials ()
Toggles material display state.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Public Member Functions inherited from cloudViewer::GenericIndexedCloudPersist
~GenericIndexedCloudPersist () override=default
Default destructor.
Public Member Functions inherited from cloudViewer::GenericIndexedCloud
~GenericIndexedCloud () override=default
Default destructor.
Public Member Functions inherited from cloudViewer::GenericCloud
GenericCloud ()=default
Default constructor.
virtual ~GenericCloud ()=default
Default destructor.
virtual bool hasPoints () const
Static Public Member Functions
static ccPointCloud * From (const cloudViewer::GenericIndexedCloud *cloud, const ccGenericPointCloud *sourceCloud=nullptr)
Creates a new point cloud object from a GenericIndexedCloud.
static ccPointCloud * From (cloudViewer::GenericCloud *cloud, const ccGenericPointCloud *sourceCloud=nullptr)
Creates a new point cloud object from a GenericCloud.
static ccPointCloud * From (const ccPointCloud *sourceCloud, const std::vector< size_t > &indices, bool invert=false)
Function to select points from input ccPointCloud into output ccPointCloud.
static std::vector< Eigen::Matrix3d > EstimatePerPointCovariances (const ccPointCloud &input, const cloudViewer::geometry::KDTreeSearchParam &search_param=cloudViewer::geometry::KDTreeSearchParamKNN())
Static function to compute the covariance matrix for each point of a point cloud. Doesn't change the input PointCloud, just outputs the covariance matrices.
static std::shared_ptr< ccPointCloud > CreateFromDepthImage (const cloudViewer::geometry::Image &depth, const cloudViewer::camera::PinholeCameraIntrinsic &intrinsic, const Eigen::Matrix4d &extrinsic=Eigen::Matrix4d::Identity(), double depth_scale=1000.0, double depth_trunc=1000.0, int stride=1, bool project_valid_depth_only=true)
Factory function to create a pointcloud from a depth image and a camera model.
static std::shared_ptr< ccPointCloud > CreateFromRGBDImage (const cloudViewer::geometry::RGBDImage &image, const cloudViewer::camera::PinholeCameraIntrinsic &intrinsic, const Eigen::Matrix4d &extrinsic=Eigen::Matrix4d::Identity(), bool project_valid_depth_only=true)
Factory function to create a pointcloud from an RGB-D image and a camera model.
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Public Attributes
std::vector< Eigen::Matrix3d > covariances_
Covariance Matrix for each point.
Protected Member Functions
void drawMeOnly (CC_DRAW_CONTEXT &context) override
Draws the entity only (not its children)
void applyGLTransformation (const ccGLMatrix &trans) override
Applies a GL transformation to the entity.
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
void notifyGeometryUpdate () override
void swapPoints (unsigned firstIndex, unsigned secondIndex) override
virtual void removePoints (size_t index) override
void releaseVBOs ()
Release VBOs.
Protected Member Functions inherited from cloudViewer::PointCloudTpl< ccGenericPointCloud >
CCVector3 * point (unsigned index)
Returns non const access to a given point.
const CCVector3 * point (unsigned index) const
Returns const access to a given point.
Protected Member Functions inherited from ccShiftedObject
bool saveShiftInfoToFile (QFile &out) const
Serialization helper (output)
bool loadShiftInfoFromFile (QFile &in)
Serialization helper (input)
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void drawNameIn3D ()
Draws the entity name in 3D.
virtual void onDeletionOf (const ccHObject *obj)
This method is called when another object is deleted.
virtual void onUpdateOf (ccHObject *obj)
This method is called when another object (geometry) is updated.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Protected Attributes
ColorsTableType * m_rgbColors
Colors.
NormsIndexesTableType * m_normals
Normals (compressed)
bool m_sfColorScaleDisplayed
ccScalarField * m_currentDisplayedScalarField
Currently displayed scalar field.
int m_currentDisplayedScalarFieldIndex
Currently displayed scalar field index.
std::vector< Grid::Shared > m_grids
Associated grid structure.
bool m_visibilityCheckEnabled
Whether visibility check is available or not (during comparison)
vboSet m_vboManager
Set of VBOs attached to this cloud.
ccPointCloudLOD * m_lod
L.O.D. structure.
FWFDescriptorSet m_fwfDescriptors
General waveform descriptors.
std::vector< ccWaveform > m_fwfWaveforms
Per-point waveform accessors.
SharedFWFDataContainer m_fwfData
Waveforms raw data storage.
Protected Attributes inherited from cloudViewer::PointCloudTpl< ccGenericPointCloud >
std::vector< CCVector3 > m_points
3D Points database
BoundingBox m_bbox
Bounding-box.
unsigned m_currentPointIndex
'Iterator' on the points db
std::vector< ScalarField * > m_scalarFields
Associated scalar fields.
int m_currentInScalarFieldIndex
Index of current scalar field used for input.
int m_currentOutScalarFieldIndex
Index of current scalar field used for output.
Protected Attributes inherited from ccGenericPointCloud
VisibilityTableType m_pointsVisibility
Per-point visibility table.
unsigned char m_pointSize
Point size (won't be applied if 0)
Protected Attributes inherited from ccShiftedObject
CCVector3d m_globalShift
Global shift (typically applied at loading time)
double m_globalScale
Global scale (typically applied at loading time)
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Detailed Description
A 3D cloud and its associated features (color, normals, scalar fields, etc.)
A point cloud can have multiple features:
colors (RGB)
normals (compressed)
scalar fields
an octree strucutre
per-point visibility information (to hide/display subsets of points)
other children objects (meshes, calibrated pictures, etc.)
Definition at line 146 of file ecvPointCloud.h.
Member Typedef Documentation
BaseClass
using ccPointCloud::BaseClass = cloudViewer::PointCloudTpl<ccGenericPointCloud>
Base class (shortcut)
Definition at line 150 of file ecvPointCloud.h.
FWFDataContainer
using ccPointCloud::FWFDataContainer = std::vector<uint8_t>
Waveform data container.
Definition at line 506 of file ecvPointCloud.h.
FWFDescriptorSet
using ccPointCloud::FWFDescriptorSet = QMap<uint8_t, WaveformDescriptor>
Waveform descriptors set.
Definition at line 503 of file ecvPointCloud.h.
SharedFWFDataContainer
using ccPointCloud::SharedFWFDataContainer = QSharedPointer<const FWFDataContainer>
Definition at line 507 of file ecvPointCloud.h.
Member Enumeration Documentation
CLONE_WARNINGS
enum ccPointCloud::CLONE_WARNINGS
Warnings for the partialClone method (bit flags)
Enumerator
WRN_OUT_OF_MEM_FOR_COLORS
WRN_OUT_OF_MEM_FOR_NORMALS
WRN_OUT_OF_MEM_FOR_SFS
WRN_OUT_OF_MEM_FOR_FWF
Definition at line 208 of file ecvPointCloud.h.
RGB_FILTER_TYPES
enum ccPointCloud::RGB_FILTER_TYPES
RGB filter types.
Enumerator
NONE
BILATERAL
GAUSSIAN
MEAN
MEDIAN
Definition at line 790 of file ecvPointCloud.h.
UnrollMode
enum ccPointCloud::UnrollMode
Enumerator
CYLINDER
CONE
STRAIGHTENED_CONE
STRAIGHTENED_CONE2
Definition at line 864 of file ecvPointCloud.h.
Constructor & Destructor Documentation
ccPointCloud() [1/3]
ccPointCloud::ccPointCloud (QString name = QString()) throw ()
Default constructor.
Creates an empty cloud without any feature. Each of them shoud be specifically instantiated/created (once the points have been added to this cloud, at least partially).
Parameters
name cloud name (optional)
ccPointCloud() [2/3]
ccPointCloud::ccPointCloud (const ccPointCloud & cloud)
ccPointCloud() [3/3]
ccPointCloud::ccPointCloud (const std::vector< Eigen::Vector3d > & points, const std::string & name = "cloud")
~ccPointCloud()
ccPointCloud::~ccPointCloud () override
Default destructor.
Member Function Documentation
addColorRampInfo()
void ccPointCloud::addColorRampInfo (CC_DRAW_CONTEXT & context)
Adds associated SF color ramp info to current GL context.
addEigenColor()
void ccPointCloud::addEigenColor (const Eigen::Vector3d & color)
Referenced by cloudViewer::pipelines::integration::ScalableTSDFVolume::ExtractTriangleMesh(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractTriangleMesh(), cloudViewer::io::ReadModelUsingAssimp(), cloudViewer::io::ReadPointCloudFromXYZRGB(), and cloudViewer::io::ReadTriangleMeshFromOBJ().
addEigenColors()
void ccPointCloud::addEigenColors (const std::vector< Eigen::Vector3d > & colors)
Referenced by cloudViewer::geometry::pybind_pointcloud(), and cloudViewer::t::geometry::PointCloud::ToLegacy().
addEigenNorm()
void ccPointCloud::addEigenNorm (const Eigen::Vector3d & N)
Referenced by cloudViewer::io::ReadModelUsingAssimp(), cloudViewer::io::ReadPointCloudFromXYZN(), and cloudViewer::io::ReadTriangleMeshFromGLTF().
addEigenNorms()
void ccPointCloud::addEigenNorms (const std::vector< Eigen::Vector3d > & normals)
Referenced by cloudViewer::geometry::pybind_pointcloud(), and cloudViewer::t::geometry::PointCloud::ToLegacy().
addGreyColor()
void ccPointCloud::addGreyColor (ColorCompType g) inline
Pushes a grey color on stack (shortcut)
Shortcut: color is converted to RGB(g, g, g)
Parameters
g grey component
Definition at line 722 of file ecvPointCloud.h.
Referenced by SoiFilter::loadFile(), and cloudViewer::geometry::pybind_pointcloud().
addGrid()
bool ccPointCloud::addGrid (Grid::Shared grid) inline
Adds an associated grid.
Definition at line 449 of file ecvPointCloud.h.
addNorm()
void ccPointCloud::addNorm (const CCVector3 & N)
Pushes a normal vector on stack (shortcut)
Parameters
N normal vector
Referenced by MeshWrapper< Real >::addNormal(), define_ccPointCloud(), ccCompass::estimateStructureNormals(), FromFbxMesh(), LoadCloud(), RDBFilter::loadFile(), LoadScan(), and cloudViewer::visualization::MessageProcessor::ProcessMessage().
addNormAtIndex()
void ccPointCloud::addNormAtIndex (const PointCoordinateType * N, unsigned index)
Adds a normal vector to the one at a specific index.
The resulting sum is automatically normalized and compressed.
Parameters
N normal vector to add (size: 3)
index normal index to modify
addNormIndex()
void ccPointCloud::addNormIndex (CompressedNormType index)
Pushes a compressed normal vector.
Parameters
index compressed normal vector
addNorms() [1/2]
void ccPointCloud::addNorms (const std::vector< CCVector3 > & Ns)
addNorms() [2/2]
void ccPointCloud::addNorms (const std::vector< CompressedNormType > & idxes)
addRGBColor() [1/2]
void ccPointCloud::addRGBColor (ColorCompType r, ColorCompType g, ColorCompType b) inline
Pushes an RGB color on stack (shortcut)
Parameters
r red component
g green component
b blue component
Definition at line 714 of file ecvPointCloud.h.
addRGBColor() [2/2]
void ccPointCloud::addRGBColor (const ecvColor::Rgb & C)
Pushes an RGB color on stack.
Parameters
C RGB color
Referenced by MeshWrapper< Real >::addColor(), contourPoly(), contourPoly2(), FromFbxMesh(), getMortarMaps(), LasScalarFieldLoader::handleRGBValue(), LoadCloud(), CSVMatrixFilter::loadFile(), LASFWFFilter::loadFile(), LASFilter::loadFile(), RDBFilter::loadFile(), LoadScan(), cloudViewer::io::ReadTriangleMeshFromGLTF(), rotY(), and qCanupoTools::TrainClassifier().
addRGBColors()
void ccPointCloud::addRGBColors (const std::vector< ecvColor::Rgb > & colors)
addScalarField() [1/2]
int ccPointCloud::addScalarField (ccScalarField * sf)
Adds an existing scalar field to this cloud.
Warning: the cloud takes ownership of it!
Parameters
sf existing scalar field
Returns
index of added scalar field (or -1 if an error occurred)
addScalarField() [2/2]
int ccPointCloud::addScalarField (const char * uniqueName) override virtual
Creates a new scalar field and registers it.
Warnings:
the name must be unique (the method will fail if a SF with the same name already exists)
this method DOES resize the scalar field to match the current cloud size
Parameters
uniqueName scalar field name (must be unique)
Returns
index of this new scalar field (or -1 if an error occurred)
Reimplemented from cloudViewer::PointCloudTpl< ccGenericPointCloud >.
Referenced by LasCloudChunk::addLasFieldsToCloud(), ccScalarFieldArithmeticsDlg::Apply(), ccLibAlgorithms::ApplyCCLibAlgorithm(), ccTrace::buildCurvatureCost(), ccTrace::buildGradientCost(), masc::Classifier::classify(), qCanupoProcess::Classify(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), ccComparisonDlg::computeApproxDistances(), ccComparisonDlg::computeDistances(), ccLibAlgorithms::ComputeGeomCharacteristic(), DistanceMapGenerationTool::ComputeRadialDist(), ccRasterizeTool::convertGridToCloud(), DistanceMapGenerationTool::ConvertMapToCloud(), ccEntityAction::convertNormalsTo(), ccCropTool::Crop(), qPCV::doAction(), qPoissonRecon::doAction(), ccCompass::estimateP21(), masc::Classifier::evaluate(), GrainsAsEllipsoids::exportResultsAsCloud(), qFacets::extractFacets(), TreeIso::Final_seg_pcd(), ccRasterizeTool::generateHillshade(), getMortarMaps(), ccRegistrationTools::ICP(), ccEntityAction::importToSF(), TreeIso::Init_seg_pcd(), TreeIso::Intermediate_seg_pcd(), LoadCloud(), LASFWFFilter::loadFile(), RDBFilter::loadFile(), LoadScan(), ccTrace::optimizePath(), masc::Feature::PrepareSF(), CommandExtractCCs::process(), CommandStatTest::process(), PCVCommand::Process(), cloudViewer::geometry::pybind_pointcloud(), ccEntityAction::rgbGaussianFilter(), ccEntityAction::sfAddIdField(), ccEntityAction::sfGaussianFilter(), and ccEntityAction::statisticalTest().
append()
const ccPointCloud& ccPointCloud::append (ccPointCloud * cloud, unsigned pointCountBefore, bool ignoreChildren = false)
Appends a cloud to this one.
Same as the += operator with pointCountBefore == size()
Parameters
cloud cloud to be added
pointCountBefore the number of points previously contained in this cloud
ignoreChildren whether to copy input cloud's children or not
Returns
the resulting point cloud
Referenced by cloudViewer::geometry::pybind_pointcloud().
applyFilterToRGB()
bool ccPointCloud::applyFilterToRGB (PointCoordinateType sigma, PointCoordinateType sigmaSF, RgbFilterOptions filterParams, cloudViewer::GenericProgressCallback * progressCb = nullptr)
Applies a spatial Gaussian filter on RGB colors.
The "amplitude" of the Gaussian filter must be specified (sigma). As 99% of the Gaussian distribution is between -3*sigma and +3*sigma around the mean value, this filter will only look for neighbors within a sphere of radius 3*sigma. One can also use the filter as a Bilateral filter. In this case the weights are computed considering the difference of the neighbors SF values with the current point SF value (also following a Gaussian distribution). Warning: this method assumes the output scalar field is set.
Parameters
sigma filter variance
sigmaSF if strictly positive, the variance for the Bilateral filter
filterParams filter options
progressCb the client application can get some notification of the process progress through this callback mechanism (see GenericProgressCallback)
Returns
success
Referenced by ccEntityAction::rgbGaussianFilter().
applyGLTransformation()
void ccPointCloud::applyGLTransformation (const ccGLMatrix & trans) override protected virtual
Applies a GL transformation to the entity.
this = rotMat*(this-rotCenter)+(rotCenter+trans)
Parameters
trans a ccGLMatrix structure
Reimplemented from ccHObject.
applyRigidTransformation()
virtual void ccPointCloud::applyRigidTransformation (const ccGLMatrix & trans) override virtual
Applies a rigid transformation (rotation + translation)
Implements ccGenericPointCloud.
clear()
void ccPointCloud::clear () override virtual
Clears the entity from all its points and features.
Display parameters are also reseted to their default values.
Reimplemented from ccGenericPointCloud.
Reimplemented in ccSymbolCloud.
Referenced by ccGraphicalSegmentationTool::addPointToPolyline(), ccSymbolCloud::clear(), ccGraphicalSegmentationTool::closePolyLine(), ccGraphicalSegmentationTool::closeRectangle(), ccTopologyRelation::constructGraphic(), ccGraphicalSegmentationTool::doActionUseExistingPolyline(), ccCompass::estimateP21(), ccContourExtractor::ExtractConcaveHull2D(), ccGraphicalSegmentationTool::pauseSegmentationMode(), cloudViewer::io::ReadPointCloudFromPLY(), cloudViewer::io::ReadPointCloudFromPTS(), cloudViewer::io::ReadPointCloudFromXYZ(), cloudViewer::io::ReadPointCloudFromXYZN(), cloudViewer::io::ReadPointCloudFromXYZRGB(), cloudViewer::io::ReadPointCloudInMemoryFromXYZ(), qCanupo2DViewDialog::resetBoundary(), cloudViewer::benchmarks::TestKDTreeLine0::setup(), ccGraphicalSegmentationTool::start(), and qCanupoTools::TrainClassifier().
clearFWFData()
void ccPointCloud::clearFWFData ()
Clears all associated FWF data.
clearLOD()
void ccPointCloud::clearLOD ()
Clears the LOD structure.
clone()
ccGenericPointCloud* ccPointCloud::clone (ccGenericPointCloud * destCloud = nullptr, bool ignoreChildren = false) override virtual
Clones this entity.
All the main features of the entity are cloned, except from the octree and the points visibility information.
Parameters
destCloud destination cloud can be provided here (must be of the exact same type as the cloned cloud!)
ignoreChildren [optional] whether to ignore the cloud's children or not (in which case they will be cloned as well)
Returns
a copy of this entity
Implements ccGenericPointCloud.
cloneThis()
ccPointCloud* ccPointCloud::cloneThis (ccPointCloud * destCloud = nullptr, bool ignoreChildren = false)
Clones this entity.
All the main features of the entity are cloned, except from the octree and the points visibility information.
Parameters
destCloud [optional] the destination cloud can be provided here
ignoreChildren [optional] whether to ignore the cloud's children or not (in which case they will be cloned as well)
Returns
a copy of this entity
Referenced by ComputeKmeansClustering(), cloudViewer::geometry::pybind_pointcloud(), and cloudViewer::geometry::pybind_trianglemesh().
ClusterDBSCAN()
std::vector<int> ccPointCloud::ClusterDBSCAN (double eps, size_t min_points, bool print_progress = false) const
Cluster ccPointCloud using the DBSCAN algorithm Ester et al., "A Density-Based Algorithm for Discovering Clusters in Large Spatial Databases with Noise", 1996.
Returns a list of point labels, -1 indicates noise according to the algorithm.
Parameters
eps Density parameter that is used to find neighbouring points.
min_points Minimum number of points to form a cluster.
print_progress If true the progress is visualized in the console.
Referenced by ccEntityAction::DBScanCluster(), and cloudViewer::geometry::pybind_pointcloud().
colorize()
bool ccPointCloud::colorize (float r, float g, float b)
Multiplies all color components of all points by coefficients.
If the cloud has no color, all points are considered white and the color array is automatically allocated.
Parameters
r red component
g green component
b blue component
Returns
success
Referenced by define_ccPointCloud(), cloudViewer::geometry::pybind_pointcloud(), and ccEntityAction::setColor().
colorsHaveChanged()
void ccPointCloud::colorsHaveChanged () inline
Notify a modification of color / scalar field display parameters or contents
Definition at line 276 of file ecvPointCloud.h.
Referenced by TreeIso::Final_seg_pcd(), TreeIso::Init_seg_pcd(), TreeIso::Intermediate_seg_pcd(), ccColorFromScalarDlg::onApply(), and cloudViewer::geometry::pybind_pointcloud().
compressFWFData()
bool ccPointCloud::compressFWFData ()
Compresses the associated FWF data container.
As the container is shared, the compressed version will be potentially added to the memory resulting in a decrease of the available memory...
Referenced by LASFWFFilter::saveToFile().
ComputeConvexHull()
std::tuple<std::shared_ptr<ccMesh>, std::vector<size_t> > ccPointCloud::ComputeConvexHull () const
Function that computes the convex hull of the point cloud using qhull.
Referenced by ccEntityAction::ConvexHull(), and cloudViewer::geometry::pybind_pointcloud().
computeCPSet()
QSharedPointer<cloudViewer::ReferenceCloud> ccPointCloud::computeCPSet (ccGenericPointCloud & otherCloud, cloudViewer::GenericProgressCallback * progressCb = nullptr, unsigned char octreeLevel = 0)
Computes the closest point of this cloud relatively to another cloud.
The output (reference) clouds will have as many points as this cloud (with the indexes pointing on the closest point in the other cloud)
Referenced by cloudViewer::geometry::pybind_pointcloud().
computeFWFAmplitude()
bool ccPointCloud::computeFWFAmplitude (double & minVal, double & maxVal, ecvProgressDialog * pDlg = nullptr) const
Computes the maximum amplitude of all associated waveforms.
Referenced by ccWaveDialog::ccWaveDialog().
computeGravityCenter()
CCVector3 ccPointCloud::computeGravityCenter ()
Returns the cloud gravity center.
Returns
gravity center
Referenced by ccPointPairRegistrationDlg::callHornRegistration(), and cloudViewer::geometry::pybind_pointcloud().
ComputeMahalanobisDistance()
std::vector<double> ccPointCloud::ComputeMahalanobisDistance () const
Function to compute the Mahalanobis distance for points in an input point cloud.
See: https://en.wikipedia.org/wiki/Mahalanobis_distance
Referenced by convert(), and cloudViewer::geometry::pybind_pointcloud().
ComputeNearestNeighborDistance()
std::vector<double> ccPointCloud::ComputeNearestNeighborDistance () const
Function to compute the distance from a point to its nearest neighbor in the input point cloud
Referenced by cloudViewer::geometry::pybind_pointcloud().
computeNormalsWithGrids()
bool ccPointCloud::computeNormalsWithGrids (double minTriangleAngle_deg = 1.0, ecvProgressDialog * pDlg = nullptr)
Compute the normals with the associated grid structure(s)
Can also orient the normals in the same run.
Referenced by define_ccPointCloud().
computeNormalsWithOctree()
bool ccPointCloud::computeNormalsWithOctree (CV_LOCAL_MODEL_TYPES model, ccNormalVectors::Orientation preferredOrientation, PointCoordinateType defaultRadius, ecvProgressDialog * pDlg = nullptr)
Compute the normals by approximating the local surface around each point.
Referenced by define_ccPointCloud(), and CommandOctreeNormal::process().
ComputePointCloudDistance()
std::vector<double> ccPointCloud::ComputePointCloudDistance (const ccPointCloud & target)
Function to compute the point to point distances between point clouds.
For each point in the source point cloud, compute the distance to the target point cloud.
Parameters
target The target point cloud.
Referenced by cloudViewer::geometry::pybind_pointcloud().
ComputeResolution()
double ccPointCloud::ComputeResolution () const
Referenced by ccEntityAction::DBScanCluster(), cloudViewer::geometry::pybind_pointcloud(), and ccEntityAction::VoxelSampling().
convertCurrentScalarFieldToColors()
bool ccPointCloud::convertCurrentScalarFieldToColors (bool mixWithExistingColor = false)
Converts current scalar field (values & display parameters) to RGB colors
Returns
success
Referenced by CommandSFConvertToRGB::process(), CommandVolume25D::process(), and cloudViewer::geometry::pybind_pointcloud().
convertNormalToDipDirSFs()
bool ccPointCloud::convertNormalToDipDirSFs (ccScalarField * dipSF, ccScalarField * dipDirSF)
Converts normals to two scalar fields: 'dip' and 'dip direction'.
One input scalar field may be empty if the corresponding value is not required
Parameters
[out] dipSF dip values
[out] dipDirSF dip direction values
Returns
success
Referenced by ccEntityAction::convertNormalsTo(), and cloudViewer::geometry::pybind_pointcloud().
convertNormalToRGB()
bool ccPointCloud::convertNormalToRGB ()
Converts normals to RGB colors.
See ccNormalVectors::ConvertNormalToRGB
Returns
success
Referenced by ccEntityAction::convertNormalsTo(), and cloudViewer::geometry::pybind_pointcloud().
convertRGBToGreyScale()
bool ccPointCloud::convertRGBToGreyScale ()
Converts RGB to grey scale colors.
Returns
success
Referenced by cloudViewer::geometry::pybind_pointcloud(), and ccEntityAction::rgbToGreyScale().
CreateFromDepthImage()
static std::shared_ptr<ccPointCloud> ccPointCloud::CreateFromDepthImage (const cloudViewer::geometry::Image & depth, const cloudViewer::camera::PinholeCameraIntrinsic & intrinsic, const Eigen::Matrix4d & extrinsic = Eigen::Matrix4d::Identity(), double depth_scale = 1000.0, double depth_trunc = 1000.0, int stride = 1, bool project_valid_depth_only = true) static
Factory function to create a pointcloud from a depth image and a camera model.
Given depth value d at (u, v) image coordinate, the corresponding 3d point is: z = d / depth_scale
x = (u - cx) * z / fx
y = (v - cy) * z / fy
Parameters
depth The input depth image can be either a float image, or a uint16_t image.
intrinsic Intrinsic parameters of the camera.
extrinsic Extrinsic parameters of the camera.
depth_scale The depth is scaled by 1 / depth_scale.
depth_trunc Truncated at depth_trunc distance.
stride Sampling factor to support coarse point cloud extraction.
\Return An empty pointcloud if the conversion fails. If
Parameters
project_valid_depth_only is true, return point cloud, which doesn't have nan point. If the value is false, return point cloud, which has a point for each pixel, whereas invalid depth results in NaN points.
Referenced by cloudViewer::pipelines::integration::ScalableTSDFVolume::Integrate(), main(), and cloudViewer::geometry::pybind_pointcloud().
CreateFromRGBDImage()
static std::shared_ptr<ccPointCloud> ccPointCloud::CreateFromRGBDImage (const cloudViewer::geometry::RGBDImage & image, const cloudViewer::camera::PinholeCameraIntrinsic & intrinsic, const Eigen::Matrix4d & extrinsic = Eigen::Matrix4d::Identity(), bool project_valid_depth_only = true) static
Factory function to create a pointcloud from an RGB-D image and a camera model.
Given depth value d at (u, v) image coordinate, the corresponding 3d point is: z = d / depth_scale
x = (u - cx) * z / fx
y = (v - cy) * z / fy
Parameters
image The input image.
intrinsic Intrinsic parameters of the camera.
extrinsic Extrinsic parameters of the camera.
\Return An empty pointcloud if the conversion fails. If
Parameters
project_valid_depth_only is true, return point cloud, which doesn't have nan point. If the value is false, return point cloud, which has a point for each pixel, whereas invalid depth results in NaN points.
Referenced by cloudViewer::geometry::pybind_pointcloud().
CreateFromVoxelGrid()
std::shared_ptr<ccPointCloud> ccPointCloud::CreateFromVoxelGrid (const cloudViewer::geometry::VoxelGrid & voxel_grid)
Function to create a PointCloud from a VoxelGrid.
It transforms the voxel centers to 3D points using the original point cloud coordinate (with respect to the center of the voxel grid).
Parameters
voxel_grid The input VoxelGrid.
createNewCloudFromVisibilitySelection()
ccGenericPointCloud* ccPointCloud::createNewCloudFromVisibilitySelection (bool removeSelectedPoints = false, VisibilityTableType * visTable = nullptr, std::vector< int > * newIndexesOfRemainingPoints = nullptr, bool silent = false, cloudViewer::ReferenceCloud * selection = nullptr) override virtual
Warning
if removeSelectedPoints is true, any attached octree will be deleted, as well as the visibility table.
Implements ccGenericPointCloud.
Referenced by StereogramDialog::exportCurrentSelection().
Crop() [1/2]
std::shared_ptr<ccPointCloud> ccPointCloud::Crop (const ccBBox & bbox) const
Function to crop ccPointCloud into output ccPointCloud.
All points with coordinates outside the bounding box bbox are clipped.
Parameters
bbox ccBBox to crop points.
Referenced by convert(), cloudViewer::t::geometry::LegacyCropByAxisAlignedBox(), cloudViewer::t::geometry::LegacyCropByOrientedBox(), and cloudViewer::geometry::pybind_pointcloud().
crop() [1/2]
cloudViewer::ReferenceCloud* ccPointCloud::crop (const ccBBox & box, bool inside = true) override virtual
Crops the cloud inside (or outside) a bounding box.
Warning
Always returns a selection (potentially empty) if successful.
Parameters
box cropping box
inside whether selected points are inside or outside the box
Returns
points falling inside (or outside) as a selection
Implements ccGenericPointCloud.
Referenced by ccCropTool::Crop().
Crop() [2/2]
std::shared_ptr<ccPointCloud> ccPointCloud::Crop (const ecvOrientedBBox & bbox) const
Function to crop ccPointCloud into output ccPointCloud.
All points with coordinates outside the bounding box bbox are clipped.
Parameters
bbox OrientedBoundingBox to crop points.
crop() [2/2]
cloudViewer::ReferenceCloud* ccPointCloud::crop (const ecvOrientedBBox & bbox) override virtual
Implements ccGenericPointCloud.
crop2D()
cloudViewer::ReferenceCloud* ccPointCloud::crop2D (const ccPolyline * poly, unsigned char orthoDim, bool inside = true)
Crops the cloud inside (or outside) a 2D polyline.
Warning
Always returns a selection (potentially empty) if successful.
Parameters
poly croping polyline
orthoDim dimension orthogonal to the plane in which the segmentation should occur (X=0, Y=1, Z=2)
inside whether selected points are inside or outside the polyline
Returns
points falling inside (or outside) as a selection
Referenced by define_ccPointCloud(), and cloudViewer::geometry::pybind_pointcloud().
deleteAllScalarFields()
void ccPointCloud::deleteAllScalarFields () override virtual
Deletes all scalar fields associated to this cloud.
Reimplemented from cloudViewer::PointCloudTpl< ccGenericPointCloud >.
Referenced by ccCropTool::Crop(), and cloudViewer::geometry::pybind_pointcloud().
deleteScalarField()
void ccPointCloud::deleteScalarField (int index) override virtual
Deletes a specific scalar field.
WARNING: this operation may modify the scalar fields order (especially if the deleted SF is not the last one). However current IN & OUT scalar fields will stay up-to-date (while their index may change).
Parameters
index index of scalar field to be deleted
Reimplemented from cloudViewer::PointCloudTpl< ccGenericPointCloud >.
Referenced by ccScalarFieldArithmeticsDlg::Apply(), ccComparisonDlg::applyAndExit(), ccLibAlgorithms::ApplyCCLibAlgorithm(), ccTrace::buildCurvatureCost(), ccTrace::buildGradientCost(), ccComparisonDlg::cancelAndExit(), masc::Classifier::classify(), qCanupoProcess::Classify(), ccComparisonDlg::computeApproxDistances(), ccComparisonDlg::computeDistances(), ccLibAlgorithms::ComputeGeomCharacteristic(), ccEntityAction::convertNormalsTo(), ccMeasurementDevice::deleteScalarFieldFromCloud(), qPCV::doAction(), masc::Classifier::evaluate(), qFacets::extractFacets(), ccRegistrationTools::ICP(), CommandExtractCCs::process(), PCVCommand::Process(), cloudViewer::geometry::pybind_pointcloud(), SFCollector::releaseSFs(), RemoveScalarField(), and CommandRemoveSF::removeSF().
drawMeOnly()
void ccPointCloud::drawMeOnly (CC_DRAW_CONTEXT & context) override protected virtual
Draws the entity only (not its children)
Reimplemented from ccHObject.
Reimplemented in ccSymbolCloud, and ccSNECloud.
Referenced by ccSNECloud::drawMeOnly().
enableVisibilityCheck()
void ccPointCloud::enableVisibilityCheck (bool state) inline
Sets whether visibility check is enabled or not (e.g. during distances computation) See ccPointCloud::testVisibility.
Definition at line 618 of file ecvPointCloud.h.
Referenced by ccComparisonDlg::computeDistances().
enhanceRGBWithIntensitySF()
bool ccPointCloud::enhanceRGBWithIntensitySF (int sfIdx, bool useCustomIntensityRange = false, double minI = 0.0, double maxI = 1.0)
Enhances the RGB colors with the current scalar field (assuming it's intensities)
Referenced by ccEntityAction::enhanceRGBWithIntensities(), and cloudViewer::geometry::pybind_pointcloud().
EstimateCovariances()
void ccPointCloud::EstimateCovariances (const cloudViewer::geometry::KDTreeSearchParam & search_param = cloudViewer::geometry::KDTreeSearchParamKNN())
Function to compute the covariance matrix for each point of a point cloud.
Parameters
search_param The KDTree search parameters for neighborhood search.
Referenced by cloudViewer::geometry::pybind_pointcloud().
EstimateNormals()
bool ccPointCloud::EstimateNormals (const cloudViewer::geometry::KDTreeSearchParam & search_param = cloudViewer::geometry::KDTreeSearchParamKNN(), bool fast_normal_computation = true)
Function to compute the normals of a point cloud.
Normals are oriented with respect to the input point cloud if normals exist.
Parameters
search_param The KDTree search parameters for neighborhood search.
fast_normal_computation If true, the normal estiamtion uses a non-iterative method to extract the eigenvector from the covariance matrix. This is faster, but is not as numerical stable.
Referenced by convert(), and cloudViewer::geometry::pybind_pointcloud().
EstimatePerPointCovariances()
static std::vector<Eigen::Matrix3d> ccPointCloud::EstimatePerPointCovariances (const ccPointCloud & input, const cloudViewer::geometry::KDTreeSearchParam & search_param = cloudViewer::geometry::KDTreeSearchParamKNN()) static
Static function to compute the covariance matrix for each point of a point cloud. Doesn't change the input PointCloud, just outputs the covariance matrices.
Parameters
input PointCloud to use for covariance computation
search_param The KDTree search parameters for neighborhood search.
Referenced by cloudViewer::geometry::pybind_pointcloud().
exportCoordToSF()
bool ccPointCloud::exportCoordToSF (bool exportDims[3])
Exports the specified coordinate dimension(s) to scalar field(s)
Referenced by ccEntityAction::exportCoordToSF(), CommandCoordToSF::process(), and cloudViewer::geometry::pybind_pointcloud().
exportNormalToSF()
bool ccPointCloud::exportNormalToSF (bool exportDims[3])
Exports the specified normal dimension(s) to scalar field(s)
Referenced by ccEntityAction::exportNormalToSF().
FarthestPointDownSample()
std::shared_ptr<ccPointCloud> ccPointCloud::FarthestPointDownSample (const size_t num_samples, const size_t start_index = 0) const
Function to downsample input pointcloud into output pointcloud with a set of points has farthest distance.
The sample is performed by selecting the farthest point from previous selected points iteratively, starting from start_index.
Parameters
num_samples Number of points to be sampled.
start_index Index to start downsampling from.
Referenced by cloudViewer::geometry::pybind_pointcloud().
filterPointsByScalarValue() [1/2]
ccPointCloud* ccPointCloud::filterPointsByScalarValue (ScalarType minVal, ScalarType maxVal, bool outside = false)
Filters out points whose scalar values falls into an interval.
Threshold values should be expressed relatively to the current displayed scalar field.
Parameters
minVal minimum value
maxVal maximum value
outside whether to select the points inside or outside of the specified interval
Returns
resulting cloud (remaining points)
Referenced by ecvFilterByLabelDlg::apply(), and cloudViewer::geometry::pybind_pointcloud().
filterPointsByScalarValue() [2/2]
ccPointCloud* ccPointCloud::filterPointsByScalarValue (std::vector< ScalarType > values, bool outside = false)
Filters out points whose scalar values falls into an interval.
Threshold values should be expressed relatively to the current displayed scalar field.
Parameters
values filter scalar values
outside whether to select the points inside or outside of the specified interval
Returns
resulting cloud (remaining points)
From() [1/3]
static ccPointCloud* ccPointCloud::From (cloudViewer::GenericCloud * cloud, const ccGenericPointCloud * sourceCloud = nullptr) static
Creates a new point cloud object from a GenericCloud.
"GenericCloud" is a very simple and light interface from cloudViewer. It is meant to give access to points coordinates of any cloud (on the condition it implements the GenericCloud interface of course). See cloudViewer documentation for more information about GenericClouds. As the GenericCloud interface is very simple, only points are imported. Note: throws an 'int' exception in case of error (see CTOR_ERRORS)
Parameters
cloud a GenericCloud structure
sourceCloud cloud from which main parameters will be imported (optional)
From() [2/3]
static ccPointCloud* ccPointCloud::From (const ccPointCloud * sourceCloud, const std::vector< size_t > & indices, bool invert = false) static
Function to select points from input ccPointCloud into output ccPointCloud.
Points with indices in
Parameters
indices are selected.
sourceCloud.
indices Indices of points to be selected.
invert Set to True to invert the selection of indices.
From() [3/3]
static ccPointCloud* ccPointCloud::From (const cloudViewer::GenericIndexedCloud * cloud, const ccGenericPointCloud * sourceCloud = nullptr) static
Creates a new point cloud object from a GenericIndexedCloud.
"GenericIndexedCloud" is an extension of GenericCloud (from cloudViewer) which provides a const random accessor to points. See cloudViewer documentation for more information about GenericIndexedCloud. As the GenericIndexedCloud interface is very simple, only points are imported. Note: throws an 'int' exception in case of error (see CTOR_ERRORS)
Parameters
cloud a GenericIndexedCloud structure
sourceCloud cloud from which main parameters will be imported (optional)
Referenced by ccCropTool::Crop(), cloudViewer::geometry::pybind_pointcloud(), and ccEntityAction::RansacSegmentation().
fromFile_MeOnly()
bool ccPointCloud::fromFile_MeOnly (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override protected virtual
Loads own object data.
Called by 'fromFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
in input file
dataVersion file version
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Reimplemented from ccGenericPointCloud.
fwfData() [1/2]
SharedFWFDataContainer& ccPointCloud::fwfData () inline
Gives access to the associated FWF data container.
Definition at line 525 of file ecvPointCloud.h.
Referenced by ccPropertiesTreeDelegate::fillWithPointCloud(), LasWaveformLoader::LasWaveformLoader(), LASFWFFilter::loadFile(), and LASFWFFilter::saveToFile().
fwfData() [2/2]
const SharedFWFDataContainer& ccPointCloud::fwfData () const inline
Gives access to the associated FWF data container (const version)
Definition at line 527 of file ecvPointCloud.h.
fwfDescriptors() [1/2]
FWFDescriptorSet& ccPointCloud::fwfDescriptors () inline
Gives access to the FWF descriptors.
Definition at line 510 of file ecvPointCloud.h.
Referenced by ccPropertiesTreeDelegate::fillWithPointCloud(), LASFWFFilter::loadFile(), LasWaveformLoader::loadWaveform(), and LASFWFFilter::saveToFile().
fwfDescriptors() [2/2]
const FWFDescriptorSet& ccPointCloud::fwfDescriptors () const inline
Gives access to the FWF descriptors (const version)
Definition at line 512 of file ecvPointCloud.h.
GetAxisAlignedBoundingBox()
virtual ccBBox ccPointCloud::GetAxisAlignedBoundingBox () const override virtual
Returns an axis-aligned bounding box of the geometry.
Reimplemented from ccHObject.
Referenced by cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ComputeAABB().
GetCenter()
virtual Eigen::Vector3d ccPointCloud::GetCenter () const inline override virtual
Returns the center of the geometry coordinates.
Reimplemented from ccHObject.
Definition at line 970 of file ecvPointCloud.h.
References Vector3Tpl< PointCoordinateType >::fromArrayContainer().
getClassID()
CV_CLASS_ENUM ccPointCloud::getClassID () const inline override virtual
Returns class ID.
Reimplemented from ccHObject.
Definition at line 167 of file ecvPointCloud.h.
References CV_TYPES::POINT_CLOUD.
getCurrentDisplayedScalarField()
ccScalarField* ccPointCloud::getCurrentDisplayedScalarField () const
Returns the currently displayed scalar (or 0 if none)
Referenced by ccRasterizeTool::activeLayerChanged(), ccRasterizeTool::addNewContour(), ccColorFromScalarDlg::ccColorFromScalarDlg(), qCanupoProcess::Classify(), MLSSmoothingUpsampling::compute(), ccEntityAction::computeStatParams(), define_ccPointCloud(), qSRA::doProjectCloudDistsInGrid(), qCanupoPlugin::doTrainAction(), ccDBRoot::editLabelScalarValue(), DistanceMapGenerationDlg::exportMapAsCloud(), ccPropertiesTreeDelegate::fillSFWithPointCloud(), ccRasterizeTool::generateContours(), ccRasterizeTool::generateImage(), ccTrace::getSegmentCostScalar(), ccTrace::getSegmentCostScalarInv(), ccRegistrationTools::ICP(), E57Filter::loadFile(), cloudViewer::geometry::pybind_pointcloud(), qCanupoClassifDialog::qCanupoClassifDialog(), RefinePointClassif(), ccEntityAction::rgbGaussianFilter(), ccColorScaleEditorDialog::saveCurrentScale(), ccPropertiesTreeDelegate::setEditorData(), ecvFilterByLabelDlg::setInputEntity(), ccEntityAction::sfConvertToRandomRGB(), ccEntityAction::sfConvertToRGB(), ccEntityAction::sfGaussianFilter(), ccEntityAction::sfRename(), ccEntityAction::sfSetAsCoord(), ccComparisonDlg::showHisto(), ecvFilterByLabelDlg::start(), ccEntityAction::statisticalTest(), and ccColorFromScalarDlg::~ccColorFromScalarDlg().
getCurrentDisplayedScalarFieldIndex()
int ccPointCloud::getCurrentDisplayedScalarFieldIndex () const
Returns the currently displayed scalar field index (or -1 if none)
Referenced by ecvFilterByLabelDlg::apply(), ccLibAlgorithms::ApplyCCLibAlgorithm(), ccColorFromScalarDlg::ccColorFromScalarDlg(), define_ccPointCloud(), ccComparisonDlg::prepareEntitiesForComparison(), CommandSFConvertToRGB::process(), CommandCanupoClassif::process(), ccEntityAction::processMeshSF(), cloudViewer::geometry::pybind_pointcloud(), CommandRemoveSF::removeSF(), ccEntityAction::rgbGaussianFilter(), SaveScan(), ccPropertiesTreeDelegate::setEditorData(), ccEntityAction::sfGaussianFilter(), and ccEntityAction::statisticalTest().
getDrawingParameters()
void ccPointCloud::getDrawingParameters (glDrawParams & params) const override virtual
Returns main OpenGL parameters for this entity.
These parameters are deduced from the visibility states of its different features (points, normals, etc.).
Parameters
params a glDrawParams structure
Reimplemented from ccDrawableObject.
Referenced by ccSymbolCloud::drawMeOnly().
getEigenColor()
Eigen::Vector3d ccPointCloud::getEigenColor (size_t index) const
Referenced by cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ConstructBuffers(), cloudViewer::geometry::pybind_pointcloud(), cloudViewer::io::WritePointCloudToPLY(), cloudViewer::io::WritePointCloudToPTS(), and cloudViewer::io::WritePointCloudToXYZRGB().
getEigenColors()
std::vector<Eigen::Vector3d> ccPointCloud::getEigenColors () const
Referenced by cloudViewer::t::geometry::PointCloud::FromLegacy(), and cloudViewer::geometry::pybind_pointcloud().
getEigenNormal()
Eigen::Vector3d ccPointCloud::getEigenNormal (size_t index) const
Referenced by cloudViewer::pipelines::registration::CorrespondenceCheckerBasedOnNormal::Check(), cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::ComputeRMSE(), cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::ComputeRMSE(), cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::ComputeTransformation(), cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::ComputeTransformation(), cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ConstructBuffers(), cloudViewer::geometry::pybind_pointcloud(), cloudViewer::io::WritePointCloudToPLY(), and cloudViewer::io::WritePointCloudToXYZN().
getEigenNormals()
std::vector<Eigen::Vector3d> ccPointCloud::getEigenNormals () const
Referenced by cloudViewer::t::geometry::PointCloud::FromLegacy(), and cloudViewer::geometry::pybind_pointcloud().
GetMaxBound()
virtual Eigen::Vector3d ccPointCloud::GetMaxBound () const inline override virtual
Returns max bounds for geometry coordinates.
Reimplemented from ccHObject.
Definition at line 967 of file ecvPointCloud.h.
References Vector3Tpl< PointCoordinateType >::fromArrayContainer().
GetMinBound()
virtual Eigen::Vector3d ccPointCloud::GetMinBound () const inline override virtual
Returns min bounds for geometry coordinates.
Reimplemented from ccHObject.
Definition at line 963 of file ecvPointCloud.h.
References Vector3Tpl< PointCoordinateType >::fromArrayContainer().
getNormal()
const CCVector3* ccPointCloud::getNormal (unsigned index) const override virtual
If per-point normals are available, returns the one at a specific index.
Warning
If overriden, this method should return a valid normal for all points
Reimplemented from cloudViewer::GenericIndexedCloud.
getNorms() [1/2]
std::vector<CompressedNormType> ccPointCloud::getNorms () const
getNorms() [2/2]
void ccPointCloud::getNorms (std::vector< CompressedNormType > & idxes) const
GetOrientedBoundingBox()
virtual ecvOrientedBBox ccPointCloud::GetOrientedBoundingBox () const override virtual
Reimplemented from ccHObject.
getPointColor()
const ecvColor::Rgb& ccPointCloud::getPointColor (unsigned pointIndex) const override virtual
Returns color corresponding to a given point.
WARNING: color array must be enabled! (see ccDrawableObject::hasColors)
Implements ccGenericPointCloud.
Referenced by ccTrace::buildGradientCost(), ComputeAverageColor(), ComputeKmeansClustering(), cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::ComputeRMSE(), cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::ComputeTransformation(), contourPoly(), contourPoly2(), ccSymbolCloud::drawMeOnly(), PointCloudWrapper< Real >::getColor(), GetKeyCluster(), getMortarMaps(), ccTrace::getSegmentCostDark(), ccTrace::getSegmentCostGrad(), ccTrace::getSegmentCostRGB(), ccCloudLayersHelper::mouseMove(), ccTrace::optimizeSegment(), ColorScalarFieldWrapper::pointValue(), rotY(), LasSaver::saveNextPoint(), SaveScan(), ccCloudLayersHelper::saveState(), MAFilter::saveToFile(), LASFWFFilter::saveToFile(), and ccCloudLayersHelper::setVisible().
getPointColorPtr()
ecvColor::Rgb& ccPointCloud::getPointColorPtr (size_t pointIndex)
Referenced by cloudViewer::ModelViewerWidget::SelectObject().
getPointColors()
const ColorsTableType& ccPointCloud::getPointColors () const inline
Definition at line 577 of file ecvPointCloud.h.
Referenced by cloudViewer::io::rpc::SetPointCloud(), and cloudViewer::io::rpc::SetTriangleMesh().
getPointDisplayedDistance()
ScalarType ccPointCloud::getPointDisplayedDistance (unsigned pointIndex) const override virtual
Returns scalar value associated to a given point.
The returned value is taken from the current displayed scalar field WARNING: scalar field must be enabled! (see ccDrawableObject::hasDisplayedScalarField)
Implements ccGenericPointCloud.
getPointNormal()
const CCVector3& ccPointCloud::getPointNormal (unsigned pointIndex) const override virtual
Returns normal corresponding to a given point.
WARNING: normals array must be enabled! (see ccDrawableObject::hasNormals)
Implements ccGenericPointCloud.
Referenced by ccSNECloud::drawMeOnly(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), PointCloudWrapper< Real >::getNormal(), ccTrace::getPointNormal(), StereogramWidget::init(), NormDipAndDipDirFieldWrapper::pointValue(), SaveScan(), and StereogramDialog::updateFacetsFilter().
getPointNormalIndex()
const CompressedNormType& ccPointCloud::getPointNormalIndex (unsigned pointIndex) const override virtual
Returns compressed normal corresponding to a given point.
WARNING: normals array must be enabled! (see ccDrawableObject::hasNormals)
Implements ccGenericPointCloud.
Referenced by ccTrace::fitPlane().
getPointNormalPtr()
CCVector3& ccPointCloud::getPointNormalPtr (size_t pointIndex) const
getPointNormals()
std::vector<CCVector3> ccPointCloud::getPointNormals () const
getPointNormalsPtr()
std::vector<CCVector3*> ccPointCloud::getPointNormalsPtr () const
Referenced by cloudViewer::io::rpc::SetPointCloud(), and cloudViewer::io::rpc::SetTriangleMesh().
getPointScalarValueColor()
const ecvColor::Rgb* ccPointCloud::getPointScalarValueColor (unsigned pointIndex) const override virtual
Returns color corresponding to a given point associated scalar value.
The returned value depends on the current scalar field display parameters. It may even be 0 if the value shouldn't be displayed. WARNING: scalar field must be enabled! (see ccDrawableObject::hasDisplayedScalarField)
Implements ccGenericPointCloud.
getScalarValueColor()
const ecvColor::Rgb* ccPointCloud::getScalarValueColor (ScalarType d) const override virtual
Returns color corresponding to a given scalar value.
The returned value depends on the current scalar field display parameters. It may even be 0 if the value shouldn't be displayed. WARNING: scalar field must be enabled! (see ccDrawableObject::hasDisplayedScalarField)
Implements ccGenericPointCloud.
getUniqueIDForDisplay()
unsigned ccPointCloud::getUniqueIDForDisplay () const override virtual
Returns object unqiue ID used for display.
Reimplemented from ccHObject.
grid() [1/2]
Grid::Shared& ccPointCloud::grid (size_t gridIndex) inline
Returns an associated grid.
Definition at line 443 of file ecvPointCloud.h.
Referenced by ccPropertiesTreeDelegate::fillWithPointCloud().
grid() [2/2]
const Grid::Shared& ccPointCloud::grid (size_t gridIndex) const inline
Returns an associated grid (const verson)
Definition at line 445 of file ecvPointCloud.h.
gridCount()
size_t ccPointCloud::gridCount () const inline
Returns the number of associated grids.
Definition at line 441 of file ecvPointCloud.h.
Referenced by ccEntityAction::computeNormals(), ccPropertiesTreeDelegate::fillWithPointCloud(), and ccDBRoot::getSelectedEntities().
hasColors()
bool ccPointCloud::hasColors () const override virtual
Returns whether colors are enabled or not.
Reimplemented from ccDrawableObject.
Referenced by ccRasterizeTool::activeLayerChanged(), MeshWrapper< Real >::addColor(), LasCloudChunk::addLasFieldsToCloud(), ecvPoissonReconDlg::adjustParams(), ccCloudLayersHelper::ccCloudLayersHelper(), ccEntityAction::changeColorLevels(), masc::PointFeature::checkValidity(), GeneralFilters::compute(), cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::ComputeTransformation(), cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ConstructBuffers(), qPoissonRecon::doAction(), ccEntityAction::enhanceRGBWithIntensities(), cloudViewer::pipelines::integration::ScalableTSDFVolume::ExtractTriangleMesh(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractTriangleMesh(), cloudViewer::t::geometry::PointCloud::FromLegacy(), ccDBRoot::gatherRecursiveInformation(), PointCloudWrapper< Real >::getColor(), ccTrace::getSegmentCost(), LasScalarFieldLoader::handleRGBValue(), LasSaveDialog::handleSelectedPointFormatChange(), LasCloudChunk::hasColors(), PointCloudWrapper< Real >::hasColors(), BasePclModule::hasSelectedRGB(), ColorScalarFieldWrapper::isValid(), LasSaver::LasSaver(), DRCFilter::loadFile(), LASFilter::loadFile(), ccColorFromScalarDlg::onApply(), MinimumCutSegmentation::openInputDialog(), RegionGrowingSegmentation::openInputDialog(), ccTrace::optimizeSegment(), cloudViewer::pipelines::registration::RegistrationColoredICP(), ccEntityAction::rgbGaussianFilter(), ccEntityAction::rgbToGreyScale(), LasSaver::saveNextPoint(), SaveScan(), PcdFilter::saveToFile(), LASFWFFilter::saveToFile(), LasDetails::SelectBestVersion(), cloudViewer::io::rpc::SetPointCloud(), ccEntityAction::sfFromColor(), ecvPoissonReconDlg::start(), cloudViewer::io::WritePointCloudToPLY(), cloudViewer::io::WritePointCloudToPTS(), and cloudViewer::io::WritePointCloudToXYZRGB().
HasCovariances()
bool ccPointCloud::HasCovariances () const inline
Returns 'true' if the point cloud contains per-point covariance matrix.
Definition at line 988 of file ecvPointCloud.h.
Referenced by cloudViewer::pipelines::registration::TransformationEstimationForGeneralizedICP::ComputeTransformation(), and cloudViewer::geometry::pybind_pointcloud().
hasDisplayedScalarField()
bool ccPointCloud::hasDisplayedScalarField () const override virtual
Returns whether an active scalar field is available or not.
Reimplemented from ccDrawableObject.
Referenced by LasCloudChunk::addLasFieldsToCloud(), ccTrace::getSegmentCost(), and ccEntityAction::rgbGaussianFilter().
hasFWF()
bool ccPointCloud::hasFWF () const
Returns whether the cloud has associated Full WaveForm data.
Referenced by ccPropertiesTreeDelegate::fillWithPointCloud(), LasSaveDialog::handleSelectedPointFormatChange(), ccWaveWidget::init(), LasSaver::LasSaver(), LASFWFFilter::saveToFile(), and LasDetails::SelectBestVersion().
hasNormals()
bool ccPointCloud::hasNormals () const override virtual
Returns whether normals are enabled or not.
Reimplemented from ccDrawableObject.
Referenced by MeshWrapper< Real >::addNormal(), cloudViewer::pipelines::registration::CorrespondenceCheckerBasedOnNormal::Check(), masc::PointFeature::checkValidity(), NormalEstimation::compute(), ProjectionFilter::compute(), GreedyTriangulation::compute(), MarchingCubeReconstruction::compute(), PoissonReconstruction::compute(), FastGlobalRegistrationFilter::compute(), qM3C2Process::Compute(), cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::ComputeRMSE(), cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::ComputeTransformation(), cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::ComputeTransformation(), cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ConstructBuffers(), convert(), ccEntityAction::convertNormalsTo(), qFacets::createFacets(), qPoissonRecon::doAction(), ccEntityAction::exportNormalToSF(), qFacets::extractFacets(), ccTrace::fitPlane(), cloudViewer::t::geometry::PointCloud::FromLegacy(), ccDBRoot::gatherRecursiveInformation(), PointCloudWrapper< Real >::getNormal(), qM3C2Dialog::getNormalsComputationMode(), FastGlobalRegistrationFilter::getParametersFromDialog(), ccTrace::getPointNormal(), PointCloudWrapper< Real >::hasNormals(), StereogramWidget::init(), ccEntityAction::invertNormals(), NormDipAndDipDirFieldWrapper::isValid(), DRCFilter::loadFile(), ccEntityAction::orientNormalsFM(), ccEntityAction::orientNormalsMST(), CommandOctreeNormal::process(), CommandInvertNormal::process(), CommandConvertNormalsToDipAndDipDir::process(), CommandConvertNormalsToSFs::process(), CommandOrientNormalsMST::process(), cloudViewer::visualization::MessageProcessor::ProcessMessage(), cloudViewer::pipelines::registration::RegistrationColoredICP(), cloudViewer::pipelines::registration::RegistrationICP(), masc::PointFeature::retrieveField(), SaveScan(), PcdFilter::saveToFile(), cloudViewer::io::rpc::SetPointCloud(), StereogramDialog::updateFacetsFilter(), qM3C2Dialog::updateNormalComboBox(), cloudViewer::io::WritePointCloudToPLY(), and cloudViewer::io::WritePointCloudToXYZN().
hasScalarFields()
bool ccPointCloud::hasScalarFields () const override virtual
Returns whether one or more scalar fields are instantiated.
WARNING: doesn't mean a scalar field is currently displayed (see ccDrawableObject::hasDisplayedScalarField).
Reimplemented from ccDrawableObject.
Referenced by ccScalarFieldArithmeticsDlg::Apply(), GeneralFilters::compute(), ccVolumeCalcTool::convertGridToCloud(), ccVolumeCalcTool::ConvertGridToCloud(), qCloudLayers::doAction(), ccEntityAction::enhanceRGBWithIntensities(), GetScalarFieldIndex(), ccCloudLayersHelper::getScalarFields(), BasePclModule::hasSelectedScalarField(), ccEntityAction::interpolateSFs(), MinimumCutSegmentation::openInputDialog(), RegionGrowingSegmentation::openInputDialog(), CommandRasterize::process(), CommandVolume25D::process(), SimpleBinFilter::saveToFile(), and qM3C2Dialog::setupPrecisionMapsTab().
hasSensor()
bool ccPointCloud::hasSensor () const
Returns whether the mesh as an associated sensor or not.
Referenced by ccComparisonDlg::ccComparisonDlg(), ccEntityAction::computeNormals(), and cloudViewer::geometry::pybind_pointcloud().
HiddenPointRemoval()
std::tuple<std::shared_ptr<ccMesh>, std::vector<size_t> > ccPointCloud::HiddenPointRemoval (const Eigen::Vector3d & camera_location, const double radius) const
This is an implementation of the Hidden Point Removal operator described in Katz et. al. 'Direct Visibility of Point Sets', 2007.
Additional information about the choice of radius for noisy point clouds can be found in Mehra et. al. 'Visibility of Noisy Point Cloud Data', 2010.
Parameters
camera_location All points not visible from that location will be removed.
radius The radius of the sperical projection.
Referenced by cloudViewer::geometry::pybind_pointcloud().
hidePointsByScalarValue() [1/2]
void ccPointCloud::hidePointsByScalarValue (ScalarType minVal, ScalarType maxVal)
Hides points whose scalar values falls into an interval.
Values are taken from the current OUTPUT scalar field.
Parameters
minVal minimum value (below, points are hidden)
maxVal maximum value (above, points are hidden)
Referenced by ecvFilterByLabelDlg::apply(), and cloudViewer::geometry::pybind_pointcloud().
hidePointsByScalarValue() [2/2]
void ccPointCloud::hidePointsByScalarValue (std::vector< ScalarType > values)
Hides points whose scalar values falls into an interval.
Values are taken from the current OUTPUT scalar field.
Parameters
values scalar values (equal, points are hidden)
initLOD()
bool ccPointCloud::initLOD ()
Intializes the LOD structure.
Returns
success
interpolateColorsFrom()
bool ccPointCloud::interpolateColorsFrom (ccGenericPointCloud * cloud, cloudViewer::GenericProgressCallback * progressCb = nullptr, unsigned char octreeLevel = 0)
Interpolate colors from another cloud (nearest neighbor only)
Referenced by cloudViewer::geometry::pybind_pointcloud().
invalidateBoundingBox()
void ccPointCloud::invalidateBoundingBox () override virtual
Invalidates bounding box.
Bounding box will be recomputed next time a request is made to 'getBoundingBox'.
Reimplemented from cloudViewer::PointCloudTpl< ccGenericPointCloud >.
Referenced by qM3C2Process::Compute(), ccGraphicalSegmentationTool::doExportSegmentationPolyline(), ccRasterizeTool::exportContourLines(), cloudViewer::geometry::pybind_pointcloud(), ccPointPairRegistrationDlg::removeAlignedPoint(), ccPointPairRegistrationDlg::removeRefPoint(), and ccEntityAction::sfSetAsCoord().
invertNormals()
void ccPointCloud::invertNormals ()
Inverts normals (if any)
Referenced by ccEntityAction::invertNormals(), CommandInvertNormal::process(), and cloudViewer::geometry::pybind_pointcloud().
IsEmpty()
virtual bool ccPointCloud::IsEmpty () const inline override virtual
Reimplemented from ccHObject.
Definition at line 961 of file ecvPointCloud.h.
Referenced by cloudViewer::geometry::pybind_pointcloud(), and cloudViewer::io::WritePointCloudToPLY().
minimumFileVersion_MeOnly()
short ccPointCloud::minimumFileVersion_MeOnly () const override protected virtual
Returns the minimum file version required to save this instance's own data To be overloaded (but still called ;) by subclass. Used internally by minimumFileVersion() to compute the overall minimum.
Reimplemented from ccGenericPointCloud.
NormalizeNormals()
ccPointCloud& ccPointCloud::NormalizeNormals ()
Normalize point normals to length 1.`.
Referenced by cloudViewer::geometry::pybind_pointcloud().
normals()
NormsIndexesTableType* ccPointCloud::normals () const inline
Returns pointer on compressed normals indexes table.
Definition at line 917 of file ecvPointCloud.h.
Referenced by qM3C2Process::Compute().
normalsAvailable()
bool ccPointCloud::normalsAvailable () const inline override virtual
Returns whether normals are available.
Reimplemented from cloudViewer::GenericIndexedCloud.
Definition at line 566 of file ecvPointCloud.h.
normalsHaveChanged()
void ccPointCloud::normalsHaveChanged () inline
Notify a modification of normals display parameters or contents.
Definition at line 280 of file ecvPointCloud.h.
Referenced by ccCompass::estimateStructureNormals(), and cloudViewer::geometry::pybind_pointcloud().
notifyGeometryUpdate()
void ccPointCloud::notifyGeometryUpdate () override protected virtual
Notifies all dependent entities that the geometry of this entity has changed
Reimplemented from ccHObject.
operator+()
ccPointCloud ccPointCloud::operator+ (const ccPointCloud & cloud) const inline
Definition at line 252 of file ecvPointCloud.h.
operator+=() [1/2]
const ccPointCloud& ccPointCloud::operator+= (ccPointCloud *)
operator+=() [2/2]
const ccPointCloud& ccPointCloud::operator+= (const ccPointCloud & cloud)
operator=()
ccPointCloud& ccPointCloud::operator= (const ccPointCloud & cloud)
Fuses another 3D entity with this one.
All the main features of the given entity are added, except from the octree and the points visibility information. Those features are deleted on this cloud.
OrientNormalsConsistentTangentPlane()
void ccPointCloud::OrientNormalsConsistentTangentPlane (size_t k)
Function to consistently orient estimated normals based on consistent tangent planes as described in Hoppe et al., "Surface Reconstruction from Unorganized Points", 1992.
Parameters
k k nearest neighbour for graph reconstruction for normal propagation.
Referenced by cloudViewer::geometry::pybind_pointcloud().
OrientNormalsToAlignWithDirection()
bool ccPointCloud::OrientNormalsToAlignWithDirection (const Eigen::Vector3d & orientation_reference = Eigen::Vector3d(0.0, 0.0, 1.0))
Function to orient the normals of a point cloud.
Parameters
orientation_reference Normals are oriented with respect to orientation_reference.
Referenced by convert(), and cloudViewer::geometry::pybind_pointcloud().
OrientNormalsTowardsCameraLocation()
bool ccPointCloud::OrientNormalsTowardsCameraLocation (const Eigen::Vector3d & camera_location = Eigen::Vector3d::Zero())
Function to orient the normals of a point cloud.
Parameters
camera_location Normals are oriented with towards the camera_location.
Referenced by convert(), and cloudViewer::geometry::pybind_pointcloud().
orientNormalsTowardViewPoint()
bool ccPointCloud::orientNormalsTowardViewPoint (CCVector3 & VP, ecvProgressDialog * pDlg = nullptr)
Normals are forced to point to O.
Referenced by define_ccPointCloud().
orientNormalsWithFM()
bool ccPointCloud::orientNormalsWithFM (unsigned char level, ecvProgressDialog * pDlg = nullptr)
Orient normals with Fast Marching.
Referenced by define_ccPointCloud(), and ccEntityAction::orientNormalsFM().
orientNormalsWithGrids()
bool ccPointCloud::orientNormalsWithGrids (ecvProgressDialog * pDlg = nullptr)
Orient the normals with the associated grid structure(s)
orientNormalsWithMST()
bool ccPointCloud::orientNormalsWithMST (unsigned kNN = 6, ecvProgressDialog * pDlg = nullptr)
Orient the normals with a Minimum Spanning Tree.
Referenced by define_ccPointCloud(), ccEntityAction::orientNormalsMST(), and CommandOrientNormalsMST::process().
PaintUniformColor()
ccPointCloud& ccPointCloud::PaintUniformColor (const Eigen::Vector3d & color)
Assigns each vertex in the ccMesh the same color.
Parameters
color RGB colors of vertices.
Referenced by cloudViewer::geometry::pybind_pointcloud().
partialClone()
ccPointCloud* ccPointCloud::partialClone (const cloudViewer::ReferenceCloud * selection, int * warnings = nullptr, bool withChildEntities = true) const
Creates a new point cloud object from a ReferenceCloud (selection)
"Reference clouds" are a set of indexes referring to a real point cloud. See CClib documentation for more information about ReferenceClouds. Warning: the ReferenceCloud structure must refer to this cloud.
Parameters
[in] selection a ReferenceCloud structure (pointing to source)
[out] warnings [optional] to determine if warnings (CTOR_ERRORS) occurred during the duplication process
[in] withChildEntities whether child entities should be transferred as well (see ccHObjectCaster::CloneChildren)
Referenced by qFacets::createFacets(), ccCropTool::Crop(), qCSF::doAction(), qCanupoPlugin::doClassifyAction(), GrainsAsEllipsoids::fitEllipsoidToGrain(), G3Point::G3PointAction::getBorders(), getMortarMaps(), KNNRegions(), masc::CorePoints::prepare(), CommandSubsample::process(), CommandExtractCCs::process(), CommandSORFilter::process(), CommandCPS::process(), CommandCSF::process(), cloudViewer::geometry::pybind_pointcloud(), and GrainsAsEllipsoids::updateMeshAndLineSet().
pointsHaveChanged()
void ccPointCloud::pointsHaveChanged () inline
Notify a modification of points display parameters or contents.
Definition at line 284 of file ecvPointCloud.h.
Referenced by cloudViewer::geometry::pybind_pointcloud().
RandomDownSample()
std::shared_ptr<ccPointCloud> ccPointCloud::RandomDownSample (double sampling_ratio) const
Function to downsample input pointcloud into output pointcloud randomly.
The sample is performed by randomly selecting the index of the points in the pointcloud.
Parameters
sampling_ratio Sampling ratio, the ratio of sample to total number of points in the pointcloud.
Referenced by cloudViewer::geometry::pybind_pointcloud().
refreshBB()
void ccPointCloud::refreshBB () inline override virtual
Forces bounding-box update.
Implements ccGenericPointCloud.
Definition at line 603 of file ecvPointCloud.h.
Referenced by DistanceMapGenerationTool::ConvertCloudToConical(), and DistanceMapGenerationTool::ConvertCloudToCylindrical().
releaseVBOs()
void ccPointCloud::releaseVBOs () protected
Release VBOs.
removeGrids()
void ccPointCloud::removeGrids () inline
Remove all associated grids.
Definition at line 458 of file ecvPointCloud.h.
RemoveNonFinitePoints()
ccPointCloud& ccPointCloud::RemoveNonFinitePoints (bool remove_nan = true, bool remove_infinite = true)
Remove all points fromt he point cloud that have a nan entry, or infinite entries.
Also removes the corresponding normals and color entries.
Parameters
remove_nan Remove NaN values from the ccPointCloud.
remove_infinite Remove infinite values from the ccPointCloud.
Referenced by cloudViewer::geometry::pybind_pointcloud(), and cloudViewer::io::ReadPointCloud().
removePoints()
virtual void ccPointCloud::removePoints (size_t index) override protected virtual
Implements ccGenericPointCloud.
RemoveRadiusOutliers()
std::tuple<std::shared_ptr<ccPointCloud>, std::vector<size_t> > ccPointCloud::RemoveRadiusOutliers (size_t nb_points, double search_radius) const
Function to remove points that have less than nb_points in a sphere of a given radius.
Parameters
nb_points Number of points within the radius.
search_radius Radius of the sphere.
Referenced by cloudViewer::geometry::pybind_pointcloud().
RemoveStatisticalOutliers()
std::tuple<std::shared_ptr<ccPointCloud>, std::vector<size_t> > ccPointCloud::RemoveStatisticalOutliers (size_t nb_neighbors, double std_ratio) const
Function to remove points that are further away from their nb_neighbor neighbors in average.
Parameters
nb_neighbors Number of neighbors around the target point.
std_ratio Standard deviation ratio.
Referenced by cloudViewer::geometry::pybind_pointcloud().
removeVisiblePoints()
bool ccPointCloud::removeVisiblePoints (VisibilityTableType * visTable = nullptr, std::vector< int > * newIndexes = nullptr) override virtual
Removes all the 'visible' points (as defined by the visibility array)
Parameters
visTable visibility table (optional, otherwise the cloud's default one will be used)
newIndexes optional: stores the new indexes of the points (either an index >= 0 if kept, or -1 if not). Must be initially empty or have the same size as the original cloud.
Returns
success
Implements ccGenericPointCloud.
reserve()
bool ccPointCloud::reserve (unsigned numberOfPoints) override virtual
Reserves memory for all the active features.
This method is meant to be called before increasing the cloud population. Only the already allocated features will be re-reserved.
Returns
true if ok, false if there's not enough memory
Reimplemented from cloudViewer::PointCloudTpl< ccGenericPointCloud >.
Reimplemented in ccSymbolCloud.
Referenced by ccPointPairRegistrationDlg::addAlignedPoint(), qCanupo2DViewDialog::addOrSelectPoint(), ccGraphicalSegmentationTool::addPointToPolyline(), ccPointPairRegistrationDlg::addReferencePoint(), ccTracePolylineTool::ccTracePolylineTool(), MeshWrapper< Real >::checkVertexCapacity(), qVoxFallProcess::Compute(), ccEntityAction::computeNormals(), ccTopologyRelation::constructGraphic(), DistanceMapGenerationTool::ConvertConicalMapToMesh(), DistanceMapGenerationTool::ConvertMapToCloud(), DistanceMapGenerationTool::ConvertProfileToMesh(), ccGraphicalSegmentationTool::doActionUseExistingPolyline(), ccCompass::estimateP21(), ccCompass::estimateStructureNormals(), ccPointListPickingDlg::exportToNewCloud(), ccPointListPickingDlg::exportToNewPolyline(), ccContourExtractor::ExtractConcaveHull2D(), ccContourExtractor::ExtractFlatContour(), FromFbxMesh(), ccRasterizeTool::generateContours(), GetConeProfile(), FastGlobalRegistrationFilter::getParametersFromDialog(), STEPFilter::importStepFile(), ProfileLoader::Load(), LoadCloud(), CSVMatrixFilter::loadFile(), SalomeHydroFilter::loadFile(), SinusxFilter::loadFile(), LASFWFFilter::loadFile(), RDBFilter::loadFile(), LoadScan(), ccTracePolylineTool::onItemPicked(), masc::ContextBasedFeature::prepare(), CommandCrop2D::process(), cloudViewer::geometry::pybind_pointcloud(), ccSymbolCloud::reserve(), qCanupo2DViewDialog::resetBoundary(), DistanceMapGenerationDlg::toggleOverlayGrid(), Cloth::toMesh(), qCanupoTools::TrainClassifier(), and GrainsAsEllipsoids::updateMeshAndLineSet().
reserveTheFWFTable()
bool ccPointCloud::reserveTheFWFTable ()
Reserves the FWF table.
reserveTheNormsTable()
bool ccPointCloud::reserveTheNormsTable ()
Reserves memory to store the compressed normals.
Before adding normals to the cloud (with addNorm()) be sure to reserve the necessary amount of memory with this method. This method reserves memory for as many normals as the number of points in the cloud (effectively stored or reserved).
Returns
true if ok, false if there's not enough memory
Referenced by MeshWrapper< Real >::addNormal(), define_ccPointCloud(), ccCompass::estimateStructureNormals(), FromFbxMesh(), LoadCloud(), RDBFilter::loadFile(), LoadScan(), cloudViewer::visualization::MessageProcessor::ProcessMessage(), cloudViewer::geometry::pybind_pointcloud(), cloudViewer::io::ReadModelUsingAssimp(), cloudViewer::io::ReadPointCloudFromPLY(), and cloudViewer::t::geometry::PointCloud::ToLegacy().
reserveThePointsTable()
bool ccPointCloud::reserveThePointsTable (unsigned _numberOfPoints)
Reserves memory to store the points coordinates.
Before adding points to the cloud (with addPoint()) be sure to reserve the necessary amount of memory with this method. If the number of new elements is smaller than the actual one, nothing will happen.
Parameters
_numberOfPoints number of points to reserve the memory for
Returns
true if ok, false if there's not enough memory
Referenced by contourPoly(), contourPoly2(), define_ccPointCloud(), ccMeasurementDevice::fitPlaneToPoints(), cloudViewer::t::geometry::FromLegacyPointCloud(), getDensity(), getMortarMaps(), SoiFilter::loadFile(), DistanceMapGenerationDlg::loadOverlaySymbols(), cloudViewer::visualization::MessageProcessor::ProcessMessage(), cloudViewer::geometry::pybind_pointcloud(), cloudViewer::io::ReadModelUsingAssimp(), cloudViewer::io::ReadTriangleMeshFromOBJ(), LasCloudChunk::reserveSize(), rotY(), and cloudViewer::t::geometry::PointCloud::ToLegacy().
reserveTheRGBTable()
bool ccPointCloud::reserveTheRGBTable ()
Reserves memory to store the RGB colors.
Before adding colors to the cloud (with addRGBColor()) be sure to reserve the necessary amount of memory with this method. This method reserves memory for as many colors as the number of points in the cloud (effectively stored or reserved).
Returns
true if ok, false if there's not enough memory
Referenced by MeshWrapper< Real >::addColor(), contourPoly(), contourPoly2(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractTriangleMesh(), FromFbxMesh(), cloudViewer::t::geometry::FromLegacyPointCloud(), getMortarMaps(), LasScalarFieldLoader::handleRGBValue(), LoadCloud(), CSVMatrixFilter::loadFile(), SoiFilter::loadFile(), LASFWFFilter::loadFile(), LASFilter::loadFile(), RDBFilter::loadFile(), LoadScan(), cloudViewer::geometry::pybind_pointcloud(), cloudViewer::io::ReadModelUsingAssimp(), cloudViewer::io::ReadTriangleMeshFromOBJ(), rotY(), cloudViewer::t::geometry::PointCloud::ToLegacy(), and qCanupoTools::TrainClassifier().
resize()
bool ccPointCloud::resize (unsigned numberOfPoints) override virtual
Resizes all the active features arrays.
This method is meant to be called after having increased the cloud population (if the final number of inserted point is lower than the reserved size). Otherwise, it fills all new elements with blank values.
Returns
true if ok, false if there's not enough memory
Reimplemented from cloudViewer::PointCloudTpl< ccGenericPointCloud >.
Reimplemented in ccSymbolCloud.
Referenced by ccPointPairRegistrationDlg::clear(), qM3C2Process::Compute(), ComputeKmeansClustering(), DistanceMapGenerationTool::ConvertMapToCloud(), cloudViewer::t::geometry::FromLegacyPointCloud(), SinusxFilter::loadFile(), LASFilter::loadFile(), LoadScan(), cloudViewer::geometry::pybind_pointcloud(), cloudViewer::io::ReadPointCloudFromPLY(), cloudViewer::io::ReadPointCloudFromPTS(), cloudViewer::io::ReadTriangleMeshFromPLY(), ccPointPairRegistrationDlg::removeAlignedPoint(), ccPointPairRegistrationDlg::removeRefPoint(), ccSymbolCloud::resize(), ccPointPairRegistrationDlg::unstackAligned(), ccPointPairRegistrationDlg::unstackRef(), GrainsAsEllipsoids::updateMeshAndLineSet(), and ccGraphicalSegmentationTool::updatePolyLine().
resizeTheFWFTable()
bool ccPointCloud::resizeTheFWFTable ()
Resizes the FWF table.
resizeTheNormsTable()
bool ccPointCloud::resizeTheNormsTable ()
Resizes the compressed normals array.
If possible, the normals array is resized to fit exactly the number of points in the cloud (effictively stored or reserved). If the new size is inferior to the actual one, the last elements will be deleted. Otherwise, the array is filled with blank elements. WARNING: don't try to "add" any element on a resized array...
Returns
true if ok, false if there's not enough memory
Referenced by qM3C2Process::Compute(), define_ccPointCloud(), qHoughNormals::doAction(), cloudViewer::io::ReadTriangleMeshFromOBJ(), and cloudViewer::io::ReadTriangleMeshFromPLY().
resizeTheRGBTable()
bool ccPointCloud::resizeTheRGBTable (bool fillWithWhite = false)
Resizes the RGB colors array.
If possible, the colors array is resized to fit exactly the number of points in the cloud (effectively stored or reserved). If the new size is inferior to the actual one, the last elements will be deleted. Otherwise, the array is filled with zeros (default behavior) or "white" colors (is fillWithWhite). WARNING: don't try to "add" any element on a resized array...
Parameters
fillWithWhite whether to fill new array elements with zeros (false) or white color (true)
Returns
true if ok, false if there's not enough memory
Referenced by ccCloudLayersHelper::ccCloudLayersHelper(), ccCropTool::Crop(), GrainsAsEllipsoids::exportResultsAsCloud(), ccColorFromScalarDlg::onApply(), cloudViewer::geometry::pybind_pointcloud(), cloudViewer::io::ReadPointCloudFromPLY(), cloudViewer::io::ReadPointCloudFromPTS(), cloudViewer::io::ReadTriangleMeshFromPLY(), cloudViewer::pipelines::color_map::SetGeometryColorAverage(), ccEntityAction::sfConvertToRandomRGB(), and GrainsAsEllipsoids::updateMeshAndLineSet().
rgbColors()
ColorsTableType* ccPointCloud::rgbColors () const inline
Returns pointer on RGB colors table.
Definition at line 914 of file ecvPointCloud.h.
Referenced by ccCloudLayersHelper::ccCloudLayersHelper(), and ccCloudLayersHelper::~ccCloudLayersHelper().
Rotate()
virtual ccPointCloud& ccPointCloud::Rotate (const Eigen::Matrix3d & R, const Eigen::Vector3d & center) override virtual
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
Parameters
R A 3x3 rotation matrix
center Rotation center that is used for the rotation.
Reimplemented from ccHObject.
Scale()
virtual ccPointCloud& ccPointCloud::Scale (const double s, const Eigen::Vector3d & center) override virtual
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
Parameters
scale The scale parameter that is multiplied to the points/vertices of the geometry.
center Scale center that is used to resize the geometry.
Reimplemented from ccHObject.
scale()
virtual void ccPointCloud::scale (PointCoordinateType fx, PointCoordinateType fy, PointCoordinateType fz, CCVector3 center = CCVector3(0, 0, 0)) override virtual
Multiplies all coordinates by constant factors (one per dimension)
WARNING: attached octree may be deleted.
Parameters
fx multiplication factor along the X dimension
fy multiplication factor along the Y dimension
fz multiplication factor along the Z dimension
center scaling center (0,0,0) by default
Implements ccGenericPointCloud.
Referenced by getMortarMaps().
SegmentPlane()
std::tuple<Eigen::Vector4d, std::vector<size_t> > ccPointCloud::SegmentPlane (const double distance_threshold = 0.01, const int ransac_n = 3, const int num_iterations = 100) const
Segment ccPointCloud plane using the RANSAC algorithm.
Parameters
distance_threshold Max distance a point can be from the plane model, and still be considered an inlier.
ransac_n Number of initial points to be considered inliers in each iteration.
num_iterations Number of iterations.
Returns
Returns the plane model ax + by + cz + d = 0 and the indices of the plane inliers.
Referenced by cloudViewer::geometry::pybind_pointcloud(), and ccEntityAction::RansacSegmentation().
SelectByIndex()
std::shared_ptr<ccPointCloud> ccPointCloud::SelectByIndex (const std::vector< size_t > & indices, bool invert = false) const
Function to select points from input ccPointCloud into output ccPointCloud.
Points with indices in
Parameters
indices are selected.
indices Indices of points to be selected.
invert Set to True to invert the selection of indices.
Referenced by convert(), cloudViewer::t::geometry::LegacySelectByIndex(), and cloudViewer::geometry::pybind_pointcloud().
setCoordFromSF()
bool ccPointCloud::setCoordFromSF (bool importDims[3], cloudViewer::ScalarField * sf, PointCoordinateType defaultValueForNaN)
Sets coordinate(s) from a scalar field.
Referenced by ccEntityAction::sfSetAsCoord().
setCurrentDisplayedScalarField()
void ccPointCloud::setCurrentDisplayedScalarField (int index)
Sets the currently displayed scalar field.
Warning: this scalar field will automatically be set as the OUTPUT one!
Referenced by ccRasterizeTool::activeLayerChanged(), LasCloudChunk::addLasFieldsToCloud(), ccScalarFieldArithmeticsDlg::Apply(), ccComparisonDlg::applyAndExit(), ccLibAlgorithms::ApplyCCLibAlgorithm(), ccComparisonDlg::cancelAndExit(), ccColorFromScalarDlg::ccColorFromScalarDlg(), masc::Classifier::classify(), qCanupoProcess::Classify(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), ccComparisonDlg::computeApproxDistances(), ccComparisonDlg::computeDistances(), ccLibAlgorithms::ComputeGeomCharacteristic(), DistanceMapGenerationTool::ComputeRadialDist(), ccVolumeCalcTool::convertGridToCloud(), ccVolumeCalcTool::ConvertGridToCloud(), ccRasterizeTool::convertGridToCloud(), DistanceMapGenerationTool::ConvertMapToCloud(), ccEntityAction::convertNormalsTo(), ccMeasurementDevice::createScalarFieldForCloud(), ccCropTool::Crop(), define_ccPointCloud(), qPCV::doAction(), qPoissonRecon::doAction(), ccCompass::estimateStructureNormals(), masc::Classifier::evaluate(), qFacets::extractFacets(), TreeIso::Final_seg_pcd(), ccRasterizeTool::generateHillshade(), getMortarMaps(), ccEntityAction::importToSF(), TreeIso::Init_seg_pcd(), TreeIso::Intermediate_seg_pcd(), ccEntityAction::interpolateSFs(), ccCloudLayersHelper::keepCurrentSFVisible(), LoadCloud(), LASFWFFilter::loadFile(), RDBFilter::loadFile(), LoadScan(), CommandSFConvertToRGB::process(), CommandStatTest::process(), CommandICP::process(), CommandRasterize::process(), PCVCommand::Process(), cloudViewer::geometry::pybind_pointcloud(), CommandRemoveSF::removeSF(), ccEntityAction::rgbGaussianFilter(), ccEntityAction::sfAddIdField(), ccEntityAction::sfGaussianFilter(), and ccEntityAction::statisticalTest().
setEigenColor()
void ccPointCloud::setEigenColor (size_t index, const Eigen::Vector3d & color)
Referenced by cloudViewer::geometry::pybind_pointcloud().
setEigenColors()
void ccPointCloud::setEigenColors (const std::vector< Eigen::Vector3d > & colors)
setEigenNormal()
void ccPointCloud::setEigenNormal (size_t index, const Eigen::Vector3d & normal)
Referenced by cloudViewer::geometry::pybind_pointcloud().
setEigenNormals()
void ccPointCloud::setEigenNormals (const std::vector< Eigen::Vector3d > & normals)
setNormsTable()
void ccPointCloud::setNormsTable (NormsIndexesTableType * norms)
Sets the (compressed) normals table.
Referenced by qM3C2Process::Compute().
setPointColor() [1/3]
void ccPointCloud::setPointColor (size_t pointIndex, const ecvColor::Rgb & col)
Sets a particular point color.
WARNING: colors must be enabled.
Referenced by ccCloudLayersHelper::apply(), ComputeKmeansClustering(), ccCropTool::Crop(), GrainsAsEllipsoids::exportResultsAsCloud(), LASFWFFilter::loadFile(), LASFilter::loadFile(), ccCloudLayersHelper::mouseMove(), ccCloudLayersHelper::moveItem(), ccColorFromScalarDlg::onApply(), ccColorLevelsDlg::onApply(), cloudViewer::io::ReadPointCloudFromPTS(), ccCloudLayersHelper::restoreState(), ccCloudLayersHelper::setVisible(), ccEntityAction::sfConvertToRandomRGB(), and GrainsAsEllipsoids::updateMeshAndLineSet().
setPointColor() [2/3]
void ccPointCloud::setPointColor (size_t pointIndex, const ecvColor::Rgba & col)
setPointColor() [3/3]
void ccPointCloud::setPointColor (size_t pointIndex, const Eigen::Vector3d & col)
setPointNormal()
void ccPointCloud::setPointNormal (size_t pointIndex, const CCVector3 & N)
Sets a particular point normal (shortcut)
WARNING: normals must be enabled. Normal is automatically compressed before storage.
Referenced by ComputeM3C2DistForPoint(), define_ccPointCloud(), qHoughNormals::doAction(), ccCompass::estimateStructureNormals(), and cloudViewer::io::ReadTriangleMeshFromOBJ().
setPointNormalIndex()
void ccPointCloud::setPointNormalIndex (size_t pointIndex, CompressedNormType norm)
Sets a particular point compressed normal.
WARNING: normals must be enabled.
Referenced by qM3C2Process::Compute().
setPointNormals()
void ccPointCloud::setPointNormals (const std::vector< CCVector3 > & normals)
setRGBColor() [1/2]
bool ccPointCloud::setRGBColor (ColorCompType r, ColorCompType g, ColorCompType b) inline
Set a unique color for the whole cloud (shortcut)
Color array is automatically allocated if necessary.
Parameters
r red component
g green component
b blue component
Returns
success
Definition at line 778 of file ecvPointCloud.h.
Referenced by ccCloudLayersHelper::apply(), ExtractSIFT::compute(), GeneralFilters::compute(), ProjectionFilter::compute(), CorrespondenceMatching::compute(), TemplateAlignment::compute(), and ccEntityAction::setColor().
setRGBColor() [2/2]
bool ccPointCloud::setRGBColor (const ecvColor::Rgb & col)
Set a unique color for the whole cloud.
Color array is automatically allocated if necessary.
Parameters
col RGB color (size: 3)
Returns
success
setRGBColorByBanding()
bool ccPointCloud::setRGBColorByBanding (unsigned char dim, double freq)
Assigns color to points by 'banding'.
Banding is performed along the specified dimension Color array is automatically allocated if necessary.
Parameters
dim banding dimension (0:X, 1:Y, 2:Z)
freq banding frequency
Returns
success
Referenced by CommandColorBanding::process(), cloudViewer::geometry::pybind_pointcloud(), and ccEntityAction::setColorGradient().
setRGBColorByHeight()
bool ccPointCloud::setRGBColorByHeight (unsigned char heightDim, ccColorScale::Shared colorScale)
Assigns color to points proportionnaly to their 'height'.
Height is defined wrt to the specified dimension (heightDim). Color array is automatically allocated if necessary.
Parameters
heightDim ramp dimension (0:X, 1:Y, 2:Z)
colorScale color scale to use
Returns
success
Referenced by ccEntityAction::setColorGradient().
setRGBColorWithCurrentScalarField()
bool ccPointCloud::setRGBColorWithCurrentScalarField (bool mixWithExistingColor = false)
Sets RGB colors with current scalar field (values & parameters)
Returns
success
Referenced by cloudViewer::geometry::pybind_pointcloud(), and ccEntityAction::sfConvertToRGB().
sfColorScaleShown()
bool ccPointCloud::sfColorScaleShown () const
Returns whether color scale should be displayed or not.
Referenced by define_ccPointCloud(), ccPropertiesTreeDelegate::fillSFWithPointCloud(), and cloudViewer::geometry::pybind_pointcloud().
showSFColorsScale()
void ccPointCloud::showSFColorsScale (bool state)
Sets whether color scale should be displayed or not.
Referenced by ccVolumeCalcTool::convertGridToCloud(), ccVolumeCalcTool::ConvertGridToCloud(), ccMeasurementDevice::createScalarFieldForCloud(), define_ccPointCloud(), and cloudViewer::geometry::pybind_pointcloud().
shrinkToFit()
void ccPointCloud::shrinkToFit () inline
Removes unused capacity.
Definition at line 357 of file ecvPointCloud.h.
References size.
Referenced by define_ccPointCloud(), ccCompass::estimateStructureNormals(), cloudViewer::pipelines::integration::ScalableTSDFVolume::ExtractTriangleMesh(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractTriangleMesh(), STEPFilter::importStepFile(), SalomeHydroFilter::loadFile(), DRCFilter::loadFile(), DistanceMapGenerationDlg::loadOverlaySymbols(), main(), cloudViewer::geometry::pybind_pointcloud(), and cloudViewer::io::ReadModelUsingAssimp().
swapPoints()
void ccPointCloud::swapPoints (unsigned firstIndex, unsigned secondIndex) override protected virtual
Warning
Doesn't handle scan grids!
Reimplemented from cloudViewer::PointCloudTpl< ccGenericPointCloud >.
testVisibility()
unsigned char ccPointCloud::testVisibility (const CCVector3 & P) const override virtual
Returns a given point visibility state (relatively to a sensor for instance) Generic method to request a point visibility (should be overloaded if this functionality is required). The point visibility is such as defined in Daniel Girardeau-Montaut's PhD manuscript (see Chapter 2, section 2-3-3). In this case, a ground based laser sensor model should be used to determine it. This method is called before performing any point-to-cloud comparison. If the result is not POINT_VISIBLE, then the comparison won't be performed and the scalar field value associated to this point will be this visibility value.
Parameters
P the 3D point to test
Returns
visibility (default: POINT_VISIBLE)
Reimplemented from cloudViewer::GenericCloud.
toFile_MeOnly()
bool ccPointCloud::toFile_MeOnly (QFile & out, short dataVersion) const override protected virtual
Save own object data.
Called by 'toFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
out output file
dataVersion target file version for compatibility control
Reimplemented from ccGenericPointCloud.
Transform()
virtual ccPointCloud& ccPointCloud::Transform (const Eigen::Matrix4d & transformation) override virtual
Apply transformation (4x4 matrix) to the geometry coordinates.
Reimplemented from ccHObject.
Referenced by cloudViewer::pipelines::registration::EvaluateRegistration(), cloudViewer::pipelines::registration::GetInformationMatrixFromPointClouds(), cloudViewer::t::geometry::LegacyTransform(), cloudViewer::pipelines::registration::OptimizePairwiseRegistration(), cloudViewer::pipelines::registration::RegistrationICP(), and cloudViewer::pipelines::registration::RegistrationRANSACBasedOnCorrespondence().
Translate() [1/2]
ccPointCloud& ccPointCloud::Translate (const CCVector3 & T) inline
Definition at line 979 of file ecvPointCloud.h.
References Vector3Tpl< double >::fromArray().
Translate() [2/2]
virtual ccPointCloud& ccPointCloud::Translate (const Eigen::Vector3d & translation, bool relative = true) override virtual
Apply translation to the geometry coordinates.
Parameters
translation A 3D vector to transform the geometry.
relative If true, the translation is directly applied to the geometry. Otherwise, the geometry center is moved to the translation.
Reimplemented from ccHObject.
Referenced by getMortarMaps().
triangulateGrid()
ccMesh* ccPointCloud::triangulateGrid (const Grid & grid, double minTriangleAngle_deg = 0.0) const
Meshes a scan grid.
Warning
The mesh vertices will be this cloud instance!
unalloactePoints()
void ccPointCloud::unalloactePoints ()
Erases the cloud points.
Prefer ccPointCloud::clear by default.
Warning
DANGEROUS
Referenced by cloudViewer::geometry::pybind_pointcloud().
unallocateColors()
void ccPointCloud::unallocateColors ()
Erases the cloud colors.
Referenced by ccCropTool::Crop(), qPoissonRecon::doAction(), cloudViewer::geometry::pybind_pointcloud(), cloudViewer::pipelines::color_map::SetGeometryColorAverage(), ecvPoissonReconDlg::start(), and ccCloudLayersHelper::~ccCloudLayersHelper().
unallocateNorms()
void ccPointCloud::unallocateNorms ()
Erases the cloud normals.
Referenced by NormalEstimation::compute(), CommandClearNormals::process(), cloudViewer::geometry::pybind_pointcloud(), and cloudViewer::io::ReadTriangleMeshFromOBJ().
UniformDownSample()
std::shared_ptr<ccPointCloud> ccPointCloud::UniformDownSample (size_t every_k_points) const
Function to downsample input ccPointCloud into output ccPointCloud uniformly.
The sample is performed in the order of the points with the 0-th point always chosen, not at random.
Parameters
every_k_points Sample rate, the selected point indices are [0, k, 2k].
Referenced by convert(), and cloudViewer::geometry::pybind_pointcloud().
unroll()
ccPointCloud* ccPointCloud::unroll (UnrollMode mode, UnrollBaseParams * params, bool exportDeviationSF = false, double startAngle_deg = 0.0, double stopAngle_deg = 360.0, cloudViewer::GenericProgressCallback * progressCb = nullptr) const
Unrolls the cloud and its normals on a cylinder or a cone.
This method is redundant with the "developCloudOnCylinder" method of CCLib, apart that it can also handle the cloud normals.
Parameters
mode unrolling mode
params unrolling parameters (must match the unrolling mode)
exportDeviationSF to export the deviation fro the ideal cone as a scalar field
startAngle_deg start angle (in degrees) - 0 corresponds to +X (east)
stopAngle_deg stop angle (in degrees)
progressCb for progress notification
Returns
the unrolled point cloud
VoxelDownSample()
std::shared_ptr<ccPointCloud> ccPointCloud::VoxelDownSample (double voxel_size)
Function to downsample input ccPointCloud into output ccPointCloud with a voxel.
Normals and colors are averaged if they exist.
Parameters
voxel_size Defines the resolution of the voxel grid, smaller value leads to denser output point cloud.
Referenced by convert(), cloudViewer::visualization::VisualizerWithEditing::KeyPressCallback(), cloudViewer::t::geometry::LegacyEstimateNormals(), cloudViewer::t::geometry::LegacyRemoveRadiusOutliers(), cloudViewer::t::geometry::LegacyRemoveStatisticalOutliers(), cloudViewer::pipelines::registration::LoadPointCloud(), and cloudViewer::geometry::pybind_pointcloud().
VoxelDownSampleAndTrace()
std::tuple<std::shared_ptr<ccPointCloud>, Eigen::MatrixXi, std::vector<std::vector<int> > > ccPointCloud::VoxelDownSampleAndTrace (double voxel_size, const Eigen::Vector3d & min_bound, const Eigen::Vector3d & max_bound, bool approximate_class = false) const
Function to downsample using geometry.ccPointCloud.VoxelDownSample.
Also records point cloud index before downsampling.
Parameters
voxel_size Voxel size to downsample into.
min_bound Minimum coordinate of voxel boundaries
max_bound Maximum coordinate of voxel boundaries
approximate_class Whether to approximate.
Referenced by cloudViewer::geometry::pybind_pointcloud().
waveformProxy()
ccWaveformProxy ccPointCloud::waveformProxy (unsigned index) const
Returns a proxy on a given waveform.
Referenced by ccWaveWidget::init(), ccWaveDialog::onExportWaveAsCSV(), and LASFWFFilter::saveToFile().
waveforms() [1/2]
std::vector<ccWaveform>& ccPointCloud::waveforms () inline
Gives access to the associated FWF data.
Definition at line 515 of file ecvPointCloud.h.
Referenced by ccPropertiesTreeDelegate::fillWithPointCloud(), LasWaveformSaver::handlePoint(), LasWaveformLoader::LasWaveformLoader(), LASFWFFilter::loadFile(), LasWaveformLoader::loadWaveform(), and ccWaveDialog::onExportWaveAsCSV().
waveforms() [2/2]
const std::vector<ccWaveform>& ccPointCloud::waveforms () const inline
Gives access to the associated FWF data (const version)
Definition at line 517 of file ecvPointCloud.h.
Member Data Documentation
covariances_
std::vector<Eigen::Matrix3d> ccPointCloud::covariances_
Covariance Matrix for each point.
Definition at line 1316 of file ecvPointCloud.h.
Referenced by cloudViewer::pipelines::registration::TransformationEstimationForGeneralizedICP::ComputeRMSE(), cloudViewer::pipelines::registration::TransformationEstimationForGeneralizedICP::ComputeTransformation(), and cloudViewer::geometry::pybind_pointcloud().
m_currentDisplayedScalarField
ccScalarField* ccPointCloud::m_currentDisplayedScalarField protected
Currently displayed scalar field.
Definition at line 1348 of file ecvPointCloud.h.
Referenced by ccSNECloud::drawMeOnly().
m_currentDisplayedScalarFieldIndex
int ccPointCloud::m_currentDisplayedScalarFieldIndex protected
Currently displayed scalar field index.
Definition at line 1350 of file ecvPointCloud.h.
m_fwfData
SharedFWFDataContainer ccPointCloud::m_fwfData protected
Waveforms raw data storage.
Definition at line 1439 of file ecvPointCloud.h.
m_fwfDescriptors
FWFDescriptorSet ccPointCloud::m_fwfDescriptors protected
General waveform descriptors.
Definition at line 1433 of file ecvPointCloud.h.
m_fwfWaveforms
std::vector<ccWaveform> ccPointCloud::m_fwfWaveforms protected
Per-point waveform accessors.
Definition at line 1436 of file ecvPointCloud.h.
m_grids
std::vector<Grid::Shared> ccPointCloud::m_grids protected
Associated grid structure.
Definition at line 1353 of file ecvPointCloud.h.
m_lod
ccPointCloudLOD* ccPointCloud::m_lod protected
L.O.D. structure.
Definition at line 1429 of file ecvPointCloud.h.
m_normals
NormsIndexesTableType* ccPointCloud::m_normals protected
Normals (compressed)
Definition at line 1341 of file ecvPointCloud.h.
m_rgbColors
ColorsTableType* ccPointCloud::m_rgbColors protected
Colors.
Definition at line 1338 of file ecvPointCloud.h.
m_sfColorScaleDisplayed
bool ccPointCloud::m_sfColorScaleDisplayed protected
Specifies whether current scalar field color scale should be displayed or not
Definition at line 1345 of file ecvPointCloud.h.
m_vboManager
vboSet ccPointCloud::m_vboManager protected
Set of VBOs attached to this cloud.
Definition at line 1416 of file ecvPointCloud.h.
m_visibilityCheckEnabled
bool ccPointCloud::m_visibilityCheckEnabled protected
Whether visibility check is available or not (during comparison)
See ccPointCloud::testVisibility
Definition at line 1358 of file ecvPointCloud.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvPointCloud.h