ACloudViewer: STEPFilter Class Reference
STEPFilter Class Reference
#include <STEPFilter.h>
Public Member Functions
STEPFilter ()
CC_FILE_ERROR loadFile (const QString &fullFilename, ccHObject &container, LoadParameters &parameters) override
Loads one or more entities from a file.
CC_FILE_ERROR importStepFile (ccHObject &container, const QString &fullFilename, double linearDeflection, LoadParameters &parameters)
Specific loading method.
Public Member Functions inherited from FileIOFilter
virtual ~FileIOFilter ()=default
bool importSupported () const
Returns whether this I/O filter can import files.
bool exportSupported () const
Returns whether this I/O filter can export files.
const QStringList & getFileFilters (bool onImport) const
Returns the file filter(s) for this I/O filter.
QString getDefaultExtension () const
Returns the default file extension.
virtual CC_FILE_ERROR saveToFile (ccHObject *entity, const QString &filename, const SaveParameters &parameters)
Saves an entity (or a group of) to a file.
virtual bool canSave (CV_CLASS_ENUM type, bool &multiple, bool &exclusive) const
Returns whether this I/O filter can save the specified type of entity.
virtual void unregister ()
Called when the filter is unregistered.
Static Public Member Functions
static void SetDefaultLinearDeflection (double value)
Sets the default linear deflection.
Static Public Member Functions inherited from FileIOFilter
static QStringList ImportFilterList ()
static ccHObject * LoadFromFile (const QString &filename, LoadParameters &parameters, Shared filter, CC_FILE_ERROR &result)
Loads one or more entities from a file with a known filter.
static ccHObject * LoadFromFile (const QString &filename, LoadParameters &parameters, CC_FILE_ERROR &result, const QString &fileFilter=QString())
Loads one or more entities from a file with known type.
static CC_FILE_ERROR SaveToFile (ccHObject *entities, const QString &filename, const SaveParameters &parameters, Shared filter)
static CC_FILE_ERROR SaveToFile (ccHObject *entities, const QString &filename, const SaveParameters &parameters, const QString &fileFilter)
static bool HandleGlobalShift (const CCVector3d &P, CCVector3d &Pshift, bool &preserveCoordinateShift, LoadParameters &loadParameters, bool useInputCoordinatesShiftIfPossible=false)
Shortcut to the ecvGlobalShiftManager mechanism specific for files.
static void DisplayErrorMessage (CC_FILE_ERROR err, const QString &action, const QString &filename)
Displays (to console) the message corresponding to a given error code.
static bool CheckForSpecialChars (const QString &filename)
Returns whether special characters are present in the input string.
static void ResetSesionCounter ()
static unsigned IncreaseSesionCounter ()
static void Register (Shared filter)
Registers a new filter.
static Shared GetFilter (const QString &fileFilter, bool onImport)
Returns the filter corresponding to the given 'file filter'.
static Shared FindBestFilterForExtension (const QString &ext)
Returns the best filter (presumably) to open a given file extension.
static const FilterContainer & GetFilters ()
Returns the set of all registered filters.
static void UnregisterAll ()
Unregisters all filters.
Additional Inherited Members
Public Types inherited from FileIOFilter
enum FilterFeature {
NoFeatures = 0x0000 , Import = 0x00001 , Export = 0x0002 , BuiltIn = 0x0004 ,
DynamicInfo = 0x0008
}
using Shared = QSharedPointer< FileIOFilter >
Shared type.
using FilterContainer = std::vector< FileIOFilter::Shared >
Type of a I/O filters container.
Protected Member Functions inherited from FileIOFilter
FileIOFilter (const FilterInfo &info)
void setImportExtensions (const QStringList &extensions)
void setImportFileFilterStrings (const QStringList &filterStrings)
void setExportFileFilterStrings (const QStringList &filterStrings)
Static Protected Attributes inherited from FileIOFilter
static constexpr float DEFAULT_PRIORITY = 25.0f
Detailed Description
Definition at line 29 of file STEPFilter.h.
Constructor & Destructor Documentation
STEPFilter()
STEPFilter::STEPFilter ()
Definition at line 61 of file STEPFilter.cpp.
References FileIOFilter::DEFAULT_PRIORITY, and FileIOFilter::Import.
Member Function Documentation
importStepFile()
CC_FILE_ERROR STEPFilter::importStepFile (ccHObject & container, const QString & fullFilename, double linearDeflection, LoadParameters & parameters)
Specific loading method.
Definition at line 114 of file STEPFilter.cpp.
References ccHObject::addChild(), cloudViewer::PointCloudTpl< T >::addPoint(), ccMesh::addTriangle(), cloudViewer::PointCloudTpl< T >::capacity(), ccMesh::capacity(), CC_FERR_NO_ERROR, CC_FERR_NO_LOAD, CC_FERR_NOT_ENOUGH_MEMORY, CC_FERR_THIRD_PARTY_LIB_FAILURE, ccMesh::computePerTriangleNormals(), ccMesh::DefaultMergeDulicateVerticesLevel, face, ccMesh::mergeDuplicatedVertices(), FileIOFilter::LoadParameters::parentWidget, CVLog::Print(), ccMesh::reserve(), ccPointCloud::reserve(), ccObject::setEnabled(), ccObject::setName(), ShapeTypes, ccGenericMesh::showNormals(), ccMesh::shrinkToFit(), ccPointCloud::shrinkToFit(), cloudViewer::PointCloudTpl< T >::size(), and CVLog::Warning().
Referenced by loadFile().
loadFile()
CC_FILE_ERROR STEPFilter::loadFile (const QString & filename, ccHObject & container, LoadParameters & parameters) override virtual
Loads one or more entities from a file.
This method must be implemented by children classes.
Parameters
filename file to load
container container to store loaded entities
parameters generic loading parameters
Returns
error
Reimplemented from FileIOFilter.
Definition at line 82 of file STEPFilter.cpp.
References CC_FERR_CANCELED_BY_USER, CC_FERR_THIRD_PARTY_LIB_EXCEPTION, CC_FERR_UNKNOWN_FILE, error(), importStepFile(), FileIOFilter::LoadParameters::parentWidget, and s_defaultLinearDeflection.
SetDefaultLinearDeflection()
void STEPFilter::SetDefaultLinearDeflection (double value) static
Sets the default linear deflection.
Parameters
value linear deflection (in [1e-2, 1e-6]) The smaller this value is, the smaller the triangles will be. In some cases, if this linear deflection is too big, the tesselation may crash (precisely the instruction BRep_Tool::Triangulation(face, location)). But we don't know how to anticipate this.
Definition at line 70 of file STEPFilter.cpp.
References s_defaultLinearDeflection, and CVLog::Warning().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qStepCADImport/include/STEPFilter.h
/root/ACloudViewer/plugins/core/IO/qStepCADImport/src/STEPFilter.cpp