ACloudViewer: TreeIso Class Reference
TreeIso Class Reference
#include <TreeIso.h>
Static Public Member Functions
static bool Init_seg (const unsigned min_nn1, const float regStrength1, const float PR_DECIMATE_RES1, ecvMainAppInterface *app, QProgressDialog *progressDlg)
static bool Intermediate_seg (const unsigned PR_MIN_NN2, const float PR_REG_STRENGTH2, const float PR_DECIMATE_RES2, const float PR_MAX_GAP, ecvMainAppInterface *app, QProgressDialog *progressDlg)
static bool Final_seg (const unsigned PR_MIN_NN3, const float PR_REL_HEIGHT_LENGTH_RATIO, const float PR_VERTICAL_WEIGHT, ecvMainAppInterface *app, QProgressDialog *progressDlg)
static bool Init_seg_pcd (ccPointCloud *pc, const unsigned min_nn1, const float regStrength1, const float PR_DECIMATE_RES1, QProgressDialog *progressDlg=nullptr)
static bool Intermediate_seg_pcd (ccPointCloud *pc, const unsigned PR_MIN_NN2, const float PR_REG_STRENGTH2, const float PR_DECIMATE_RES2, const float PR_MAX_GAP, QProgressDialog *progressDlg=nullptr)
static bool Final_seg_pcd (ccPointCloud *pc, const unsigned PR_MIN_NN3, const float PR_REL_HEIGHT_LENGTH_RATIO, const float PR_VERTICAL_WEIGHT, QProgressDialog *progressDlg=nullptr)
Detailed Description
Definition at line 40 of file TreeIso.h.
Member Function Documentation
Final_seg()
bool TreeIso::Final_seg (const unsigned PR_MIN_NN3, const float PR_REL_HEIGHT_LENGTH_RATIO, const float PR_VERTICAL_WEIGHT, ecvMainAppInterface * app, QProgressDialog * progressDlg) static
Definition at line 911 of file TreeIso.cpp.
References ccObject::isA(), CV_TYPES::POINT_CLOUD, and ccHObject::redrawDisplay().
Referenced by qTreeIso::final_segs().
Final_seg_pcd()
bool TreeIso::Final_seg_pcd (ccPointCloud * pc, const unsigned PR_MIN_NN3, const float PR_REL_HEIGHT_LENGTH_RATIO, const float PR_VERTICAL_WEIGHT, QProgressDialog * progressDlg = nullptr) static
Definition at line 413 of file TreeIso.cpp.
References abs(), ccPointCloud::addScalarField(), arg_max_col(), arg_min_col(), ccPointCloud::colorsHaveChanged(), cloudViewer::ScalarField::computeMinAndMax(), CVLog::Error(), cloudViewer::ScalarField::fill(), FinalSegsSFName, get_subset(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::ScalarField::getValue(), InitSegsSFName, IntermedSegsSFName, knn_cpp_build(), knn_cpp_nearest_neighbors(), knn_cpp_query(), max_col(), mean_col(), median_col(), min_col(), mode_col(), NAN_VALUE, CVLog::Print(), ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::ScalarField::setValue(), ccDrawableObject::showSF(), Since(), cloudViewer::PointCloudTpl< T >::size(), toTranslatedVector(), and unique_group().
Referenced by CommandTreeIso::process().
Init_seg()
bool TreeIso::Init_seg (const unsigned min_nn1, const float regStrength1, const float PR_DECIMATE_RES1, ecvMainAppInterface * app, QProgressDialog * progressDlg) static
Definition at line 835 of file TreeIso.cpp.
References ccObject::isA(), CV_TYPES::POINT_CLOUD, and ccHObject::redrawDisplay().
Referenced by qTreeIso::init_segs().
Init_seg_pcd()
bool TreeIso::Init_seg_pcd (ccPointCloud * pc, const unsigned min_nn1, const float regStrength1, const float PR_DECIMATE_RES1, QProgressDialog * progressDlg = nullptr) static
Definition at line 58 of file TreeIso.cpp.
References ccPointCloud::addScalarField(), ccPointCloud::colorsHaveChanged(), cloudViewer::ScalarField::computeMinAndMax(), decimate_vec(), CVLog::Error(), cloudViewer::ScalarField::fill(), get_subset(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), InitSegsSFName, NAN_VALUE, perform_cut_pursuit(), CVLog::Print(), ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::ScalarField::setValue(), ccDrawableObject::showSF(), Since(), cloudViewer::PointCloudTpl< T >::size(), toTranslatedVector(), and unique_index_by_rows().
Referenced by CommandTreeIso::process().
Intermediate_seg()
bool TreeIso::Intermediate_seg (const unsigned PR_MIN_NN2, const float PR_REG_STRENGTH2, const float PR_DECIMATE_RES2, const float PR_MAX_GAP, ecvMainAppInterface * app, QProgressDialog * progressDlg) static
Definition at line 871 of file TreeIso.cpp.
References ccObject::isA(), CV_TYPES::POINT_CLOUD, and ccHObject::redrawDisplay().
Referenced by qTreeIso::intermediate_segs().
Intermediate_seg_pcd()
bool TreeIso::Intermediate_seg_pcd (ccPointCloud * pc, const unsigned PR_MIN_NN2, const float PR_REG_STRENGTH2, const float PR_DECIMATE_RES2, const float PR_MAX_GAP, QProgressDialog * progressDlg = nullptr) static
Definition at line 143 of file TreeIso.cpp.
References ccPointCloud::addScalarField(), ccPointCloud::colorsHaveChanged(), cloudViewer::ScalarField::computeMinAndMax(), decimate_vec(), CVLog::Error(), cloudViewer::ScalarField::fill(), get_subset(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::ScalarField::getValue(), InitSegsSFName, IntermedSegsSFName, knn_cpp_build(), knn_cpp_nearest_neighbors(), knn_cpp_query_min_d(), mean_col(), NAN_VALUE, perform_cut_pursuit2d(), CVLog::Print(), ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::ScalarField::setValue(), ccDrawableObject::showSF(), Since(), cloudViewer::PointCloudTpl< T >::size(), size, sort_indexes(), toTranslatedVector(), unique_group(), and unique_index_by_rows().
Referenced by CommandTreeIso::process().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qTreeIso/include/TreeIso.h
/root/ACloudViewer/plugins/core/Standard/qTreeIso/src/TreeIso.cpp