ACloudViewer: cloudViewer::visualization::GuiSettingsModel Class Reference
cloudViewer::visualization::GuiSettingsModel Class Reference
#include <GuiSettingsModel.h>
Classes
struct LightingProfile
struct LitMaterial
struct Materials
struct UnlitMaterial
Public Types
enum MaterialType { LIT = 0 , UNLIT , NORMAL_MAP , DEPTH }
Public Member Functions
GuiSettingsModel ()
bool GetShowSkybox () const
void SetShowSkybox (bool show)
bool GetShowAxes () const
void SetShowAxes (bool show)
bool GetShowGround () const
void SetShowGround (bool show)
bool GetSunFollowsCamera () const
void SetSunFollowsCamera (bool follow)
const Eigen::Vector3f & GetBackgroundColor () const
void SetBackgroundColor (const Eigen::Vector3f &color)
const LightingProfile & GetLighting () const
void SetLightingProfile (const LightingProfile &profile)
void SetCustomLighting (const LightingProfile &profile)
MaterialType GetMaterialType () const
void SetMaterialType (MaterialType type)
const Materials & GetCurrentMaterials () const
Materials & GetCurrentMaterials ()
void SetLitMaterial (const LitMaterial &material, const std::string &name)
void SetCurrentMaterials (const Materials &materials, const std::string &name)
void SetCurrentMaterials (const std::string &name)
void SetMaterialsToDefault ()
const Eigen::Vector3f & GetCurrentMaterialColor () const
void SetCurrentMaterialColor (const Eigen::Vector3f &color)
void ResetColors ()
void SetCustomDefaultColor (const Eigen::Vector3f color)
void UnsetCustomDefaultColor ()
int GetPointSize () const
void SetPointSize (int size)
bool GetBasicMode () const
void SetBasicMode (bool enable)
bool GetWireframeMode () const
void SetWireframeMode (bool enable)
bool GetUserWantsEstimateNormals ()
void EstimateNormalsClicked ()
bool GetDisplayingPointClouds () const
void SetDisplayingPointClouds (bool displaying)
If true, enables point size.
bool GetUserHasChangedLightingProfile () const
bool GetUserHasCustomizedLighting () const
bool GetUserHasChangedColor () const
void SetOnChanged (std::function< void(bool)> on_changed)
Static Public Member Functions
static const LightingProfile & GetDefaultLightingProfile ()
static const LightingProfile & GetDefaultPointCloudLightingProfile ()
static const LitMaterial & GetDefaultLitMaterial ()
Static Public Attributes
static constexpr const char * DEFAULT_IBL = "default"
static constexpr const char * CUSTOM_IBL = "Custom KTX file..."
static constexpr const char * DEFAULT_MATERIAL_NAME = "Polished ceramic"
static constexpr const char * MATERIAL_FROM_FILE_NAME
static constexpr const char * POINT_CLOUD_PROFILE_NAME
static const std::vector< LightingProfile > lighting_profiles_
static const std::map< std::string, const LitMaterial > prefab_materials_
Detailed Description
Definition at line 17 of file GuiSettingsModel.h.
Member Enumeration Documentation
MaterialType
enum cloudViewer::visualization::GuiSettingsModel::MaterialType
Enumerator
LIT
UNLIT
NORMAL_MAP
DEPTH
Definition at line 40 of file GuiSettingsModel.h.
Constructor & Destructor Documentation
GuiSettingsModel()
cloudViewer::visualization::GuiSettingsModel::GuiSettingsModel ()
Definition at line 177 of file GuiSettingsModel.cpp.
References DEFAULT_MATERIAL_NAME, GetDefaultLightingProfile(), GetDefaultLitMaterial(), cloudViewer::visualization::GuiSettingsModel::Materials::lit, and cloudViewer::visualization::GuiSettingsModel::Materials::lit_name.
Member Function Documentation
EstimateNormalsClicked()
void cloudViewer::visualization::GuiSettingsModel::EstimateNormalsClicked ()
Definition at line 365 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
GetBackgroundColor()
const Eigen::Vector3f & cloudViewer::visualization::GuiSettingsModel::GetBackgroundColor () const
Definition at line 221 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::Update(), and cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().
GetBasicMode()
bool cloudViewer::visualization::GuiSettingsModel::GetBasicMode () const
Definition at line 207 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().
GetCurrentMaterialColor()
const Eigen::Vector3f & cloudViewer::visualization::GuiSettingsModel::GetCurrentMaterialColor () const
Definition at line 297 of file GuiSettingsModel.cpp.
References cloudViewer::visualization::GuiSettingsModel::LitMaterial::base_color, cloudViewer::visualization::GuiSettingsModel::UnlitMaterial::base_color, LIT, cloudViewer::visualization::GuiSettingsModel::Materials::lit, UNLIT, cloudViewer::visualization::GuiSettingsModel::Materials::unlit, and ecvColor::white().
GetCurrentMaterials() [1/2]
GuiSettingsModel::Materials & cloudViewer::visualization::GuiSettingsModel::GetCurrentMaterials ()
Definition at line 258 of file GuiSettingsModel.cpp.
GetCurrentMaterials() [2/2]
const GuiSettingsModel::Materials & cloudViewer::visualization::GuiSettingsModel::GetCurrentMaterials () const
Definition at line 253 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView(), cloudViewer::visualization::GuiVisualizer::Impl::InitializeMaterials(), cloudViewer::visualization::GuiSettingsView::Update(), and cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().
GetDefaultLightingProfile()
const GuiSettingsModel::LightingProfile & cloudViewer::visualization::GuiSettingsModel::GetDefaultLightingProfile () static
Definition at line 154 of file GuiSettingsModel.cpp.
References lighting_profiles_.
Referenced by GuiSettingsModel().
GetDefaultLitMaterial()
const GuiSettingsModel::LitMaterial & cloudViewer::visualization::GuiSettingsModel::GetDefaultLitMaterial () static
Definition at line 164 of file GuiSettingsModel.cpp.
References DEFAULT_MATERIAL_NAME, LogError, and prefab_materials_.
Referenced by GuiSettingsModel().
GetDefaultPointCloudLightingProfile()
const GuiSettingsModel::LightingProfile & cloudViewer::visualization::GuiSettingsModel::GetDefaultPointCloudLightingProfile () static
Definition at line 159 of file GuiSettingsModel.cpp.
References lighting_profiles_.
Referenced by cloudViewer::visualization::GuiVisualizer::SetGeometry().
GetDisplayingPointClouds()
bool cloudViewer::visualization::GuiSettingsModel::GetDisplayingPointClouds () const
Definition at line 370 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::Update().
GetLighting()
const GuiSettingsModel::LightingProfile & cloudViewer::visualization::GuiSettingsModel::GetLighting () const
Definition at line 229 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView(), cloudViewer::visualization::GuiSettingsView::Update(), and cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().
GetMaterialType()
GuiSettingsModel::MaterialType cloudViewer::visualization::GuiSettingsModel::GetMaterialType () const
Definition at line 245 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::Update(), and cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().
GetPointSize()
int cloudViewer::visualization::GuiSettingsModel::GetPointSize () const
Definition at line 347 of file GuiSettingsModel.cpp.
References cloudViewer::visualization::GuiSettingsModel::Materials::point_size.
GetShowAxes()
bool cloudViewer::visualization::GuiSettingsModel::GetShowAxes () const
Definition at line 189 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::Update(), and cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().
GetShowGround()
bool cloudViewer::visualization::GuiSettingsModel::GetShowGround () const
Definition at line 195 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().
GetShowSkybox()
bool cloudViewer::visualization::GuiSettingsModel::GetShowSkybox () const
Definition at line 183 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::Update(), and cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().
GetSunFollowsCamera()
bool cloudViewer::visualization::GuiSettingsModel::GetSunFollowsCamera () const
Definition at line 201 of file GuiSettingsModel.cpp.
GetUserHasChangedColor()
bool cloudViewer::visualization::GuiSettingsModel::GetUserHasChangedColor () const
Definition at line 386 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::Update().
GetUserHasChangedLightingProfile()
bool cloudViewer::visualization::GuiSettingsModel::GetUserHasChangedLightingProfile () const
Definition at line 378 of file GuiSettingsModel.cpp.
GetUserHasCustomizedLighting()
bool cloudViewer::visualization::GuiSettingsModel::GetUserHasCustomizedLighting () const
Definition at line 382 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::Update().
GetUserWantsEstimateNormals()
bool cloudViewer::visualization::GuiSettingsModel::GetUserWantsEstimateNormals ()
Definition at line 356 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().
GetWireframeMode()
bool cloudViewer::visualization::GuiSettingsModel::GetWireframeMode () const
Definition at line 213 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().
ResetColors()
void cloudViewer::visualization::GuiSettingsModel::ResetColors ()
Definition at line 326 of file GuiSettingsModel.cpp.
References cloudViewer::visualization::GuiSettingsModel::LitMaterial::base_color, cloudViewer::visualization::GuiSettingsModel::UnlitMaterial::base_color, cloudViewer::visualization::GuiSettingsModel::Materials::lit, and cloudViewer::visualization::GuiSettingsModel::Materials::unlit.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetBackgroundColor()
void cloudViewer::visualization::GuiSettingsModel::SetBackgroundColor (const Eigen::Vector3f & color)
Definition at line 224 of file GuiSettingsModel.cpp.
References color.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetBasicMode()
void cloudViewer::visualization::GuiSettingsModel::SetBasicMode (bool enable)
Definition at line 208 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetCurrentMaterialColor()
void cloudViewer::visualization::GuiSettingsModel::SetCurrentMaterialColor (const Eigen::Vector3f & color)
Definition at line 312 of file GuiSettingsModel.cpp.
References cloudViewer::visualization::GuiSettingsModel::LitMaterial::base_color, cloudViewer::visualization::GuiSettingsModel::UnlitMaterial::base_color, color, LIT, cloudViewer::visualization::GuiSettingsModel::Materials::lit, UNLIT, and cloudViewer::visualization::GuiSettingsModel::Materials::unlit.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetCurrentMaterials() [1/2]
void cloudViewer::visualization::GuiSettingsModel::SetCurrentMaterials (const Materials & materials, const std::string & name)
Definition at line 273 of file GuiSettingsModel.cpp.
References cloudViewer::visualization::GuiSettingsModel::Materials::lit_name, and name.
SetCurrentMaterials() [2/2]
void cloudViewer::visualization::GuiSettingsModel::SetCurrentMaterials (const std::string & name)
Definition at line 280 of file GuiSettingsModel.cpp.
References cloudViewer::visualization::GuiSettingsModel::Materials::lit_name, and name.
SetCustomDefaultColor()
void cloudViewer::visualization::GuiSettingsModel::SetCustomDefaultColor (const Eigen::Vector3f color)
Definition at line 339 of file GuiSettingsModel.cpp.
References color.
SetCustomLighting()
void cloudViewer::visualization::GuiSettingsModel::SetCustomLighting (const LightingProfile & profile)
Definition at line 239 of file GuiSettingsModel.cpp.
References profile.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetDisplayingPointClouds()
void cloudViewer::visualization::GuiSettingsModel::SetDisplayingPointClouds (bool displaying)
If true, enables point size.
Definition at line 373 of file GuiSettingsModel.cpp.
SetLightingProfile()
void cloudViewer::visualization::GuiSettingsModel::SetLightingProfile (const LightingProfile & profile)
Definition at line 233 of file GuiSettingsModel.cpp.
References profile.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetLitMaterial()
void cloudViewer::visualization::GuiSettingsModel::SetLitMaterial (const LitMaterial & material, const std::string & name)
Definition at line 262 of file GuiSettingsModel.cpp.
References cloudViewer::visualization::GuiSettingsModel::LitMaterial::base_color, color, cloudViewer::visualization::GuiSettingsModel::Materials::lit, cloudViewer::visualization::GuiSettingsModel::Materials::lit_name, and name.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetMaterialsToDefault()
void cloudViewer::visualization::GuiSettingsModel::SetMaterialsToDefault ()
Definition at line 285 of file GuiSettingsModel.cpp.
References cloudViewer::visualization::GuiSettingsModel::LitMaterial::base_color, cloudViewer::visualization::GuiSettingsModel::UnlitMaterial::base_color, DEFAULT_MATERIAL_NAME, cloudViewer::visualization::GuiSettingsModel::Materials::lit, cloudViewer::visualization::GuiSettingsModel::Materials::lit_name, and cloudViewer::visualization::GuiSettingsModel::Materials::unlit.
Referenced by cloudViewer::visualization::GuiVisualizer::Impl::SetMaterialsToDefault().
SetMaterialType()
void cloudViewer::visualization::GuiSettingsModel::SetMaterialType (MaterialType type)
Definition at line 248 of file GuiSettingsModel.cpp.
References type.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetOnChanged()
void cloudViewer::visualization::GuiSettingsModel::SetOnChanged (std::function< void(bool)> on_changed)
Definition at line 390 of file GuiSettingsModel.cpp.
SetPointSize()
void cloudViewer::visualization::GuiSettingsModel::SetPointSize (int size)
Definition at line 351 of file GuiSettingsModel.cpp.
References cloudViewer::visualization::GuiSettingsModel::Materials::point_size, and size.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetShowAxes()
void cloudViewer::visualization::GuiSettingsModel::SetShowAxes (bool show)
Definition at line 190 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetShowGround()
void cloudViewer::visualization::GuiSettingsModel::SetShowGround (bool show)
Definition at line 196 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetShowSkybox()
void cloudViewer::visualization::GuiSettingsModel::SetShowSkybox (bool show)
Definition at line 184 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetSunFollowsCamera()
void cloudViewer::visualization::GuiSettingsModel::SetSunFollowsCamera (bool follow)
Definition at line 202 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
SetWireframeMode()
void cloudViewer::visualization::GuiSettingsModel::SetWireframeMode (bool enable)
Definition at line 216 of file GuiSettingsModel.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
UnsetCustomDefaultColor()
void cloudViewer::visualization::GuiSettingsModel::UnsetCustomDefaultColor ()
Definition at line 343 of file GuiSettingsModel.cpp.
Member Data Documentation
CUSTOM_IBL
constexpr const char * cloudViewer::visualization::GuiSettingsModel::CUSTOM_IBL = "Custom KTX file..." static constexpr
Definition at line 20 of file GuiSettingsModel.h.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
DEFAULT_IBL
constexpr const char * cloudViewer::visualization::GuiSettingsModel::DEFAULT_IBL = "default" static constexpr
Definition at line 19 of file GuiSettingsModel.h.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView(), and cloudViewer::visualization::GuiVisualizer::Impl::SetIBL().
DEFAULT_MATERIAL_NAME
constexpr const char * cloudViewer::visualization::GuiSettingsModel::DEFAULT_MATERIAL_NAME = "Polished ceramic" static constexpr
Definition at line 21 of file GuiSettingsModel.h.
Referenced by GetDefaultLitMaterial(), GuiSettingsModel(), SetMaterialsToDefault(), cloudViewer::visualization::GuiSettingsView::ShowFileMaterialEntry(), and cloudViewer::visualization::GuiSettingsView::Update().
lighting_profiles_
const std::vector< GuiSettingsModel::LightingProfile > cloudViewer::visualization::GuiSettingsModel::lighting_profiles_ static
Definition at line 72 of file GuiSettingsModel.h.
Referenced by GetDefaultLightingProfile(), GetDefaultPointCloudLightingProfile(), and cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
MATERIAL_FROM_FILE_NAME
constexpr const char * cloudViewer::visualization::GuiSettingsModel::MATERIAL_FROM_FILE_NAME static constexpr
Initial value:
=
            "Material from file [default]"
Definition at line 22 of file GuiSettingsModel.h.
Referenced by cloudViewer::visualization::GuiVisualizer::SetGeometry(), cloudViewer::visualization::GuiSettingsView::ShowFileMaterialEntry(), and cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().
POINT_CLOUD_PROFILE_NAME
constexpr const char * cloudViewer::visualization::GuiSettingsModel::POINT_CLOUD_PROFILE_NAME static constexpr
Initial value:
=
            "Cloudy day (no direct sun)"
Definition at line 24 of file GuiSettingsModel.h.
prefab_materials_
const std::map< std::string, const GuiSettingsModel::LitMaterial > cloudViewer::visualization::GuiSettingsModel::prefab_materials_ static
Initial value:
= {
                {DEFAULT_MATERIAL_NAME, {}},
                {"Metal (rougher)",
                 {{1.0f, 1.0f, 1.0f}, 1.0f, 0.5f, 0.5f, 0.0f, 0.0f, 0.0f}},
                {"Metal (smoother)",
                 {{1.0f, 1.0f, 1.0f}, 1.0f, 0.2f, 0.5f, 0.0f, 0.0f, 0.0f}},
                {"Plastic",
                 {{1.0f, 1.0f, 1.0f}, 0.0f, 0.5f, 0.5f, 0.5f, 0.8f, 0.0f}},
                {"Glazed ceramic",
                 {{1.0f, 1.0f, 1.0f}, 0.0f, 0.5f, 0.5f, 1.0f, 0.2f, 0.0f}},
                {"Clay",
                 {{0.7725f, 0.7725f, 0.7725f},
                  0.0f,
                  1.0f,
                  0.35f,
                  0.0f,
                  0.0f,
                  0.0f}},
}
Definition at line 73 of file GuiSettingsModel.h.
Referenced by GetDefaultLitMaterial(), and cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/GuiSettingsModel.h
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/GuiSettingsModel.cpp