ACloudViewer: cloudViewer::camera::PinholeCameraIntrinsic Class Reference
cloudViewer::camera::PinholeCameraIntrinsic Class Reference
Contains the pinhole camera intrinsic parameters.
#include <PinholeCameraIntrinsic.h>
Public Member Functions
PinholeCameraIntrinsic ()
Default Constructor.
PinholeCameraIntrinsic (int width, int height, const Eigen::Matrix3d &intrinsic_matrix)
Parameterized Constructor.
PinholeCameraIntrinsic (PinholeCameraIntrinsicParameters)
Parameterized Constructor.
PinholeCameraIntrinsic (int width, int height, double fx, double fy, double cx, double cy)
Parameterized Constructor.
virtual ~PinholeCameraIntrinsic () override
void SetIntrinsics (int width, int height, double fx, double fy, double cx, double cy)
Set camera intrinsic parameters.
std::pair< double, double > GetFocalLength () const
Returns the focal length in a tuple of X-axis and Y-axis focal lengths.
std::pair< double, double > GetPrincipalPoint () const
double GetSkew () const
Returns the skew.
bool IsValid () const
Returns true iff both the width and height are greater than 0.
bool ConvertToJsonValue (Json::Value &value) const override
bool ConvertFromJsonValue (const Json::Value &value) override
Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
virtual ~IJsonConvertible ()
virtual std::string ToString () const
Convert to a styled string representation of JSON data for display.
Public Attributes
int width_ = -1
Width of the image.
int height_ = -1
Height of the image.
Eigen::Matrix3d intrinsic_matrix_
Additional Inherited Members
Static Public Member Functions inherited from cloudViewer::utility::IJsonConvertible
static bool EigenVector3dFromJsonArray (Eigen::Vector3d &vec, const Json::Value &value)
static bool EigenVector3dToJsonArray (const Eigen::Vector3d &vec, Json::Value &value)
static bool EigenVector4dFromJsonArray (Eigen::Vector4d &vec, const Json::Value &value)
static bool EigenVector4dToJsonArray (const Eigen::Vector4d &vec, Json::Value &value)
static bool EigenMatrix3dFromJsonArray (Eigen::Matrix3d &mat, const Json::Value &value)
static bool EigenMatrix3dToJsonArray (const Eigen::Matrix3d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d &mat, Json::Value &value)
static bool EigenMatrix4dFromJsonArray (Eigen::Matrix4d_u &mat, const Json::Value &value)
static bool EigenMatrix4dToJsonArray (const Eigen::Matrix4d_u &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d &mat, Json::Value &value)
static bool EigenMatrix6dFromJsonArray (Eigen::Matrix6d_u &mat, const Json::Value &value)
static bool EigenMatrix6dToJsonArray (const Eigen::Matrix6d_u &mat, Json::Value &value)
Detailed Description
Contains the pinhole camera intrinsic parameters.
Definition at line 34 of file PinholeCameraIntrinsic.h.
Constructor & Destructor Documentation
PinholeCameraIntrinsic() [1/4]
cloudViewer::camera::PinholeCameraIntrinsic::PinholeCameraIntrinsic ()
Default Constructor.
PinholeCameraIntrinsic() [2/4]
cloudViewer::camera::PinholeCameraIntrinsic::PinholeCameraIntrinsic (int width, int height, const Eigen::Matrix3d & intrinsic_matrix)
Parameterized Constructor.
Parameters
width width of the image. (Default: -1).
height height of the image. (Default: -1).
intrinsic_matrix 3x3 intrinsic matrix. (Default: Identity).
PinholeCameraIntrinsic() [3/4]
cloudViewer::camera::PinholeCameraIntrinsic::PinholeCameraIntrinsic (PinholeCameraIntrinsicParameters)
Parameterized Constructor.
Parameters
PinholeCameraIntrinsicParameters - Sets the camera parameters to the default settings of one of the sensors.
PinholeCameraIntrinsic() [4/4]
cloudViewer::camera::PinholeCameraIntrinsic::PinholeCameraIntrinsic (int width, int height, double fx, double fy, double cx, double cy)
Parameterized Constructor.
Parameters
width width of the image.
height height of the image.
fx focal length along the X-axis.
fy focal length along the Y-axis.
cx principal point of the X-axis.
cy principal point of the Y-axis.
~PinholeCameraIntrinsic()
virtual cloudViewer::camera::PinholeCameraIntrinsic::~PinholeCameraIntrinsic () override virtual
Member Function Documentation
ConvertFromJsonValue()
bool cloudViewer::camera::PinholeCameraIntrinsic::ConvertFromJsonValue (const Json::Value & value) override virtual
Implements cloudViewer::utility::IJsonConvertible.
Referenced by cloudViewer::io::MKVMetadata::ConvertFromJsonValue(), and cloudViewer::t::io::RGBDVideoMetadata::ConvertFromJsonValue().
ConvertToJsonValue()
bool cloudViewer::camera::PinholeCameraIntrinsic::ConvertToJsonValue (Json::Value & value) const override virtual
Implements cloudViewer::utility::IJsonConvertible.
Referenced by cloudViewer::io::MKVMetadata::ConvertToJsonValue(), cloudViewer::t::io::RGBDVideoMetadata::ConvertToJsonValue(), and cloudViewer::t::io::RealSenseSensorConfig::GetMetadataJson().
GetFocalLength()
std::pair<double, double> cloudViewer::camera::PinholeCameraIntrinsic::GetFocalLength () const inline
Returns the focal length in a tuple of X-axis and Y-axis focal lengths.
Definition at line 87 of file PinholeCameraIntrinsic.h.
References cloudViewer::core::make_pair().
Referenced by cloudViewer::pipelines::integration::UniformTSDFVolume::IntegrateWithDepthToCameraDistanceMultiplier(), and cloudViewer::pipelines::color_map::Project3DPointAndGetUVDepth().
GetPrincipalPoint()
std::pair<double, double> cloudViewer::camera::PinholeCameraIntrinsic::GetPrincipalPoint () const inline
Returns the principle point in a tuple of X-axis and Y-axis principle point.
Definition at line 93 of file PinholeCameraIntrinsic.h.
References cloudViewer::core::make_pair().
Referenced by cloudViewer::pipelines::integration::UniformTSDFVolume::IntegrateWithDepthToCameraDistanceMultiplier(), and cloudViewer::pipelines::color_map::Project3DPointAndGetUVDepth().
GetSkew()
double cloudViewer::camera::PinholeCameraIntrinsic::GetSkew () const inline
Returns the skew.
Definition at line 98 of file PinholeCameraIntrinsic.h.
Referenced by cloudViewer::io::rpc::SetLegacyCamera().
IsValid()
bool cloudViewer::camera::PinholeCameraIntrinsic::IsValid () const inline
Returns true iff both the width and height are greater than 0.
Definition at line 101 of file PinholeCameraIntrinsic.h.
Referenced by cloudViewer::io::rpc::SetLegacyCamera().
SetIntrinsics()
void cloudViewer::camera::PinholeCameraIntrinsic::SetIntrinsics (int width, int height, double fx, double fy, double cx, double cy) inline
Set camera intrinsic parameters.
Parameters
width - width of the image.
height - height of the image.
fx - focal length along the X-axis.
fy - focal length along the Y-axis.
cx - principal point of the X-axis.
cy - principal point of the Y-axis.
Definition at line 75 of file PinholeCameraIntrinsic.h.
Referenced by cloudViewer::t::io::RealSenseSensorConfig::GetMetadataJson().
Member Data Documentation
height_
int cloudViewer::camera::PinholeCameraIntrinsic::height_ = -1
Height of the image.
Definition at line 110 of file PinholeCameraIntrinsic.h.
Referenced by cloudViewer::pipelines::integration::ScalableTSDFVolume::Integrate(), cloudViewer::pipelines::integration::UniformTSDFVolume::Integrate(), cloudViewer::pipelines::integration::UniformTSDFVolume::IntegrateWithDepthToCameraDistanceMultiplier(), cloudViewer::io::rpc::SetLegacyCamera(), and cloudViewer::visualization::gui::SceneWidget::SetupCamera().
intrinsic_matrix_
Eigen::Matrix3d cloudViewer::camera::PinholeCameraIntrinsic::intrinsic_matrix_
3x3 matrix.
Intrinsic camera matrix:
[[fx, 0, cx],
[0, fy, cy],
[0, 0, 1]]
Definition at line 116 of file PinholeCameraIntrinsic.h.
Referenced by cloudViewer::pipelines::odometry::CreateCameraMatrixPyramid(), cloudViewer::pipelines::odometry::CreateInformationMatrix(), cloudViewer::pipelines::odometry::InitializeRGBDOdometry(), cloudViewer::io::rpc::SetLegacyCamera(), and cloudViewer::visualization::gui::SceneWidget::SetupCamera().
width_
int cloudViewer::camera::PinholeCameraIntrinsic::width_ = -1
Width of the image.
Definition at line 108 of file PinholeCameraIntrinsic.h.
Referenced by cloudViewer::pipelines::integration::ScalableTSDFVolume::Integrate(), cloudViewer::pipelines::integration::UniformTSDFVolume::Integrate(), cloudViewer::pipelines::integration::UniformTSDFVolume::IntegrateWithDepthToCameraDistanceMultiplier(), cloudViewer::io::rpc::SetLegacyCamera(), and cloudViewer::visualization::gui::SceneWidget::SetupCamera().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/camera/PinholeCameraIntrinsic.h