ACloudViewer: cloudViewer::visualization::gui::VGrid Class Reference
cloudViewer::visualization::gui::VGrid Class Reference
#include <Layout.h>
Classes
struct Impl
Public Member Functions
VGrid (int num_cols, int spacing=0, const Margins &margins=Margins())
virtual ~VGrid ()
int GetSpacing () const
const Margins & GetMargins () const
int GetPreferredWidth () const
void SetPreferredWidth (int w)
Size CalcPreferredSize (const LayoutContext &context, const Constraints &constraints) const override
void Layout (const LayoutContext &context) override
Public Member Functions inherited from cloudViewer::visualization::gui::Widget
Widget ()
Widget (const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Widget ()
virtual void AddChild (std::shared_ptr< Widget > child)
virtual const std::vector< std::shared_ptr< Widget > > GetChildren () const
virtual const Rect & GetFrame () const
Returns the frame size in pixels.
virtual void SetFrame (const Rect &f)
virtual const Color & GetBackgroundColor () const
virtual bool IsDefaultBackgroundColor () const
virtual void SetBackgroundColor (const Color &color)
virtual bool IsVisible () const
virtual void SetVisible (bool vis)
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
virtual void SetTooltip (const char *text)
virtual const char * GetTooltip () const
virtual Size CalcMinimumSize (const LayoutContext &context) const
virtual DrawResult Draw (const DrawContext &context)
virtual EventResult Mouse (const MouseEvent &e)
virtual EventResult Key (const KeyEvent &e)
virtual DrawResult Tick (const TickEvent &e)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::gui::Widget
enum class DrawResult { NONE , REDRAW , RELAYOUT }
enum class EventResult { IGNORED , CONSUMED , DISCARD }
Static Public Attributes inherited from cloudViewer::visualization::gui::Widget
static constexpr int DIM_GROW = 10000
Protected Member Functions inherited from cloudViewer::visualization::gui::Widget
void DrawImGuiPushEnabledState ()
void DrawImGuiPopEnabledState ()
void DrawImGuiTooltip ()
Detailed Description
Lays out widgets in a grid. The widgets are assigned to the next horizontal column, and when all the columns in a row are used, a new row will be created.
Definition at line 210 of file Layout.h.
Constructor & Destructor Documentation
VGrid()
cloudViewer::visualization::gui::VGrid::VGrid (int num_cols, int spacing = 0, const Margins & margins = Margins())
Definition at line 561 of file Layout.cpp.
~VGrid()
cloudViewer::visualization::gui::VGrid::~VGrid () virtual
Definition at line 570 of file Layout.cpp.
Member Function Documentation
CalcPreferredSize()
Size cloudViewer::visualization::gui::VGrid::CalcPreferredSize (const LayoutContext & context, const Constraints & constraints) const override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 578 of file Layout.cpp.
References context, cloudViewer::visualization::gui::Widget::DIM_GROW, cloudViewer::visualization::gui::Widget::GetChildren(), height, max(), size, and width.
GetMargins()
const Margins & cloudViewer::visualization::gui::VGrid::GetMargins () const
Definition at line 573 of file Layout.cpp.
Referenced by cloudViewer::visualization::gui::Layout1D::debug_PrintPreferredSizes().
GetPreferredWidth()
int cloudViewer::visualization::gui::VGrid::GetPreferredWidth () const
Definition at line 575 of file Layout.cpp.
GetSpacing()
int cloudViewer::visualization::gui::VGrid::GetSpacing () const
Definition at line 572 of file Layout.cpp.
Referenced by cloudViewer::visualization::gui::Layout1D::debug_PrintPreferredSizes().
Layout()
void cloudViewer::visualization::gui::VGrid::Layout (const LayoutContext & context) override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 603 of file Layout.cpp.
References cloudViewer::utility::ceil(), context, cloudViewer::utility::floor(), frame, cloudViewer::visualization::gui::Widget::GetChildren(), cloudViewer::visualization::gui::Widget::GetFrame(), cloudViewer::visualization::gui::Widget::Layout(), width, and cloudViewer::visualization::gui::Widget::Constraints::width.
SetPreferredWidth()
void cloudViewer::visualization::gui::VGrid::SetPreferredWidth (int w)
Definition at line 576 of file Layout.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Layout.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Layout.cpp