ACloudViewer: Eigen_Normal_Estimator Class Reference
Eigen_Normal_Estimator Class Reference
#include <Normals.h>
Public Types
typedef nanoflann::KDTreeEigenMatrixAdaptor< Eigen::MatrixX3d > kd_tree
Public Member Functions
const Eigen::MatrixX3d & get_points () const
Eigen::MatrixX3d & get_normals ()
int & get_T ()
int & get_n_phi ()
int & get_n_rot ()
size_t & get_K ()
bool & density_sensitive ()
double & get_tol_angle_rad ()
size_t & get_K_density ()
const Eigen::MatrixX3d & get_normals () const
const int & get_T () const
const int & get_n_phi () const
const int & get_n_rot () const
const size_t & get_K () const
const bool & density_sensitive () const
const double & get_tol_angle_rad () const
const size_t & get_K_density () const
Eigen_Normal_Estimator (const Eigen::MatrixX3d &points, Eigen::MatrixX3d &normals)
void setProgressCallback (std::function< void(int)> callback)
int maxProgressCounter () const
void estimate_normals ()
Detailed Description
Definition at line 56 of file Normals.h.
Member Typedef Documentation
kd_tree
typedef nanoflann::KDTreeEigenMatrixAdaptor<Eigen::MatrixX3d> Eigen_Normal_Estimator::kd_tree
Definition at line 98 of file Normals.h.
Constructor & Destructor Documentation
Eigen_Normal_Estimator()
Eigen_Normal_Estimator::Eigen_Normal_Estimator (const Eigen::MatrixX3d & points, Eigen::MatrixX3d & normals) inline
Definition at line 101 of file Normals.h.
Member Function Documentation
density_sensitive() [1/2]
bool& Eigen_Normal_Estimator::density_sensitive () inline
Definition at line 82 of file Normals.h.
Referenced by qHoughNormals::doAction(), and main().
density_sensitive() [2/2]
const bool& Eigen_Normal_Estimator::density_sensitive () const inline
Definition at line 91 of file Normals.h.
estimate_normals()
void Eigen_Normal_Estimator::estimate_normals () inline
Definition at line 119 of file Normals.h.
References max(), NULL, points, and std::swap().
Referenced by qHoughNormals::doAction(), and main().
get_K() [1/2]
size_t& Eigen_Normal_Estimator::get_K () inline
Definition at line 81 of file Normals.h.
Referenced by qHoughNormals::doAction(), and main().
get_K() [2/2]
const size_t& Eigen_Normal_Estimator::get_K () const inline
Definition at line 90 of file Normals.h.
get_K_density() [1/2]
size_t& Eigen_Normal_Estimator::get_K_density () inline
Definition at line 84 of file Normals.h.
Referenced by qHoughNormals::doAction(), and main().
get_K_density() [2/2]
const size_t& Eigen_Normal_Estimator::get_K_density () const inline
Definition at line 93 of file Normals.h.
get_n_phi() [1/2]
int& Eigen_Normal_Estimator::get_n_phi () inline
Definition at line 79 of file Normals.h.
Referenced by qHoughNormals::doAction(), and main().
get_n_phi() [2/2]
const int& Eigen_Normal_Estimator::get_n_phi () const inline
Definition at line 88 of file Normals.h.
get_n_rot() [1/2]
int& Eigen_Normal_Estimator::get_n_rot () inline
Definition at line 80 of file Normals.h.
Referenced by qHoughNormals::doAction(), and main().
get_n_rot() [2/2]
const int& Eigen_Normal_Estimator::get_n_rot () const inline
Definition at line 89 of file Normals.h.
get_normals() [1/2]
Eigen::MatrixX3d& Eigen_Normal_Estimator::get_normals () inline
Definition at line 77 of file Normals.h.
get_normals() [2/2]
const Eigen::MatrixX3d& Eigen_Normal_Estimator::get_normals () const inline
Definition at line 86 of file Normals.h.
get_points()
const Eigen::MatrixX3d& Eigen_Normal_Estimator::get_points () const inline
Definition at line 75 of file Normals.h.
get_T() [1/2]
int& Eigen_Normal_Estimator::get_T () inline
Definition at line 78 of file Normals.h.
Referenced by qHoughNormals::doAction(), and main().
get_T() [2/2]
const int& Eigen_Normal_Estimator::get_T () const inline
Definition at line 87 of file Normals.h.
get_tol_angle_rad() [1/2]
double& Eigen_Normal_Estimator::get_tol_angle_rad () inline
Definition at line 83 of file Normals.h.
Referenced by qHoughNormals::doAction(), and main().
get_tol_angle_rad() [2/2]
const double& Eigen_Normal_Estimator::get_tol_angle_rad () const inline
Definition at line 92 of file Normals.h.
maxProgressCounter()
int Eigen_Normal_Estimator::maxProgressCounter () const inline
Definition at line 117 of file Normals.h.
Referenced by qHoughNormals::doAction().
setProgressCallback()
void Eigen_Normal_Estimator::setProgressCallback (std::function< void(int)> callback) inline
Definition at line 113 of file Normals.h.
References callback.
Referenced by qHoughNormals::doAction().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qHoughNormals/extern/normals_Hough/normals_Hough/Normals.h