ACloudViewer: colmap::ModelViewerWidget Class Reference
colmap::ModelViewerWidget Class Reference
#include <model_viewer_widget.h>
Public Member Functions
ModelViewerWidget (QWidget *parent, OptionManager *options)
void ReloadReconstruction ()
void ClearReconstruction ()
int GetProjectionType () const
void SetPointColormap (PointColormapBase *colormap)
void SetImageColormap (ImageColormapBase *colormap)
void UpdateMovieGrabber ()
void EnableCoordinateGrid ()
void DisableCoordinateGrid ()
void ChangeFocusDistance (const float delta)
void ChangeNearPlane (const float delta)
void ChangePointSize (const float delta)
void ChangeCameraSize (const float delta)
void RotateView (const float x, const float y, const float prev_x, const float prev_y)
void TranslateView (const float x, const float y, const float prev_x, const float prev_y)
void ResetView ()
QMatrix4x4 ModelViewMatrix () const
void SetModelViewMatrix (const QMatrix4x4 &matrix)
void SelectObject (const int x, const int y)
void SelectMoviewGrabberView (const size_t view_idx)
QImage GrabImage ()
void GrabMovie ()
void ShowPointInfo (const point3D_t point3D_id)
void ShowImageInfo (const image_t image_id)
float PointSize () const
float ImageSize () const
void SetPointSize (const float point_size)
void SetImageSize (const float image_size)
void SetBackgroundColor (const float r, const float g, const float b)
Public Attributes
const float kInitNearPlane = 1.0f
const float kMinNearPlane = 1e-3f
const float kMaxNearPlane = 1e5f
const float kNearPlaneScaleSpeed = 0.02f
const float kFarPlane = 1e5f
const float kInitFocusDistance = 100.0f
const float kMinFocusDistance = 1e-5f
const float kMaxFocusDistance = 1e8f
const float kFieldOfView = 25.0f
const float kFocusSpeed = 2.0f
const float kInitPointSize = 1.0f
const float kMinPointSize = 0.5f
const float kMaxPointSize = 100.0f
const float kPointScaleSpeed = 0.1f
const float kInitImageSize = 0.2f
const float kMinImageSize = 1e-6f
const float kMaxImageSize = 1e3f
const float kImageScaleSpeed = 0.1f
const int kDoubleClickInterval = 250
Reconstruction * reconstruction = nullptr
std::unordered_map< camera_t, Camera > cameras
std::unordered_map< image_t, Image > images
std::unordered_map< point3D_t, Point3D > points3D
std::vector< image_t > reg_image_ids
QLabel * statusbar_status_label
Protected Member Functions
void initializeGL () override
void resizeGL (int width, int height) override
void paintGL () override
Detailed Description
Definition at line 33 of file model_viewer_widget.h.
Constructor & Destructor Documentation
ModelViewerWidget()
colmap::ModelViewerWidget::ModelViewerWidget (QWidget * parent, OptionManager * options)
Definition at line 182 of file model_viewer_widget.cc.
Member Function Documentation
ChangeCameraSize()
void colmap::ModelViewerWidget::ChangeCameraSize (const float delta)
Definition at line 438 of file model_viewer_widget.cc.
References kImageScaleSpeed, kMaxImageSize, and kMinImageSize.
ChangeFocusDistance()
void colmap::ModelViewerWidget::ChangeFocusDistance (const float delta)
Definition at line 335 of file model_viewer_widget.cc.
References kFocusSpeed, kMaxFocusDistance, kMinFocusDistance, and colmap::QMatrixToEigen().
ChangeNearPlane()
void colmap::ModelViewerWidget::ChangeNearPlane (const float delta)
Definition at line 358 of file model_viewer_widget.cc.
References kMaxNearPlane, kMinNearPlane, and kNearPlaneScaleSpeed.
ChangePointSize()
void colmap::ModelViewerWidget::ChangePointSize (const float delta)
Definition at line 369 of file model_viewer_widget.cc.
References kMaxPointSize, kMinPointSize, and kPointScaleSpeed.
ClearReconstruction()
void colmap::ModelViewerWidget::ClearReconstruction ()
Definition at line 299 of file model_viewer_widget.cc.
References cameras, images, points3D, reconstruction, and reg_image_ids.
DisableCoordinateGrid()
void colmap::ModelViewerWidget::DisableCoordinateGrid ()
Definition at line 330 of file model_viewer_widget.cc.
Referenced by GrabImage().
EnableCoordinateGrid()
void colmap::ModelViewerWidget::EnableCoordinateGrid ()
Definition at line 325 of file model_viewer_widget.cc.
Referenced by GrabImage().
GetProjectionType()
int colmap::ModelViewerWidget::GetProjectionType () const
Definition at line 308 of file model_viewer_widget.cc.
References colmap::OptionManager::render.
GrabImage()
QImage colmap::ModelViewerWidget::GrabImage ()
Definition at line 540 of file model_viewer_widget.cc.
References DisableCoordinateGrid(), EnableCoordinateGrid(), height, image, paintGL(), and width.
GrabMovie()
void colmap::ModelViewerWidget::GrabMovie ()
Definition at line 571 of file model_viewer_widget.cc.
ImageSize()
float colmap::ModelViewerWidget::ImageSize () const
Definition at line 583 of file model_viewer_widget.cc.
initializeGL()
void colmap::ModelViewerWidget::initializeGL () override protected
Definition at line 218 of file model_viewer_widget.cc.
ModelViewMatrix()
QMatrix4x4 colmap::ModelViewerWidget::ModelViewMatrix () const
Definition at line 454 of file model_viewer_widget.cc.
paintGL()
void colmap::ModelViewerWidget::paintGL () override protected
Definition at line 228 of file model_viewer_widget.cc.
References height, colmap::QMatrixToEigen(), colmap::TrianglePainter::Render(), colmap::PointPainter::Render(), colmap::LinePainter::Render(), and width.
Referenced by GrabImage().
PointSize()
float colmap::ModelViewerWidget::PointSize () const
Definition at line 581 of file model_viewer_widget.cc.
ReloadReconstruction()
void colmap::ModelViewerWidget::ReloadReconstruction ()
Definition at line 272 of file model_viewer_widget.cc.
References colmap::Reconstruction::Cameras(), cameras, colmap::Reconstruction::Image(), images, colmap::Reconstruction::Points3D(), points3D, reconstruction, reg_image_ids, colmap::Reconstruction::RegImageIds(), and statusbar_status_label.
ResetView()
void colmap::ModelViewerWidget::ResetView ()
Definition at line 449 of file model_viewer_widget.cc.
resizeGL()
void colmap::ModelViewerWidget::resizeGL (int width, int height) override protected
Definition at line 266 of file model_viewer_widget.cc.
References height, and width.
RotateView()
void colmap::ModelViewerWidget::RotateView (const float x, const float y, const float prev_x, const float prev_y)
Definition at line 378 of file model_viewer_widget.cc.
References colmap::QMatrixToEigen(), colmap::RadToDeg(), x, and y.
SelectMoviewGrabberView()
void colmap::ModelViewerWidget::SelectMoviewGrabberView (const size_t view_idx)
Definition at line 534 of file model_viewer_widget.cc.
SelectObject()
void colmap::ModelViewerWidget::SelectObject (const int x, const int y)
Definition at line 463 of file model_viewer_widget.cc.
References color, height, colmap::kInvalidImageId, colmap::kInvalidPoint3DId, colmap::TrianglePainter::Render(), colmap::PointPainter::Render(), SELECTION_BUFFER_IMAGE_IDX, SELECTION_BUFFER_POINT_IDX, ShowImageInfo(), ShowPointInfo(), x, and y.
SetBackgroundColor()
void colmap::ModelViewerWidget::SetBackgroundColor (const float r, const float g, const float b)
Definition at line 594 of file model_viewer_widget.cc.
SetImageColormap()
void colmap::ModelViewerWidget::SetImageColormap (ImageColormapBase * colormap)
Definition at line 316 of file model_viewer_widget.cc.
SetImageSize()
void colmap::ModelViewerWidget::SetImageSize (const float image_size)
Definition at line 589 of file model_viewer_widget.cc.
SetModelViewMatrix()
void colmap::ModelViewerWidget::SetModelViewMatrix (const QMatrix4x4 & matrix)
Definition at line 458 of file model_viewer_widget.cc.
SetPointColormap()
void colmap::ModelViewerWidget::SetPointColormap (PointColormapBase * colormap)
Definition at line 312 of file model_viewer_widget.cc.
SetPointSize()
void colmap::ModelViewerWidget::SetPointSize (const float point_size)
Definition at line 585 of file model_viewer_widget.cc.
ShowImageInfo()
void colmap::ModelViewerWidget::ShowImageInfo (const image_t image_id)
Definition at line 577 of file model_viewer_widget.cc.
References colmap::DatabaseImageViewerWidget::ShowImageWithId().
Referenced by SelectObject().
ShowPointInfo()
void colmap::ModelViewerWidget::ShowPointInfo (const point3D_t point3D_id)
Definition at line 573 of file model_viewer_widget.cc.
References colmap::PointViewerWidget::Show().
Referenced by SelectObject().
TranslateView()
void colmap::ModelViewerWidget::TranslateView (const float x, const float y, const float prev_x, const float prev_y)
Definition at line 414 of file model_viewer_widget.cc.
References height, colmap::QMatrixToEigen(), colmap::OptionManager::render, x, and y.
UpdateMovieGrabber()
void colmap::ModelViewerWidget::UpdateMovieGrabber ()
Definition at line 320 of file model_viewer_widget.cc.
Member Data Documentation
cameras
std::unordered_map<camera_t, Camera> colmap::ModelViewerWidget::cameras
Definition at line 109 of file model_viewer_widget.h.
Referenced by ClearReconstruction(), ReloadReconstruction(), colmap::PointViewerWidget::Show(), and colmap::DatabaseImageViewerWidget::ShowImageWithId().
images
std::unordered_map<image_t, Image> colmap::ModelViewerWidget::images
Definition at line 110 of file model_viewer_widget.h.
Referenced by ClearReconstruction(), ReloadReconstruction(), colmap::PointViewerWidget::Show(), and colmap::DatabaseImageViewerWidget::ShowImageWithId().
kDoubleClickInterval
const int colmap::ModelViewerWidget::kDoubleClickInterval = 250
Definition at line 54 of file model_viewer_widget.h.
kFarPlane
const float colmap::ModelViewerWidget::kFarPlane = 1e5f
Definition at line 40 of file model_viewer_widget.h.
kFieldOfView
const float colmap::ModelViewerWidget::kFieldOfView = 25.0f
Definition at line 44 of file model_viewer_widget.h.
kFocusSpeed
const float colmap::ModelViewerWidget::kFocusSpeed = 2.0f
Definition at line 45 of file model_viewer_widget.h.
Referenced by ChangeFocusDistance().
kImageScaleSpeed
const float colmap::ModelViewerWidget::kImageScaleSpeed = 0.1f
Definition at line 53 of file model_viewer_widget.h.
Referenced by ChangeCameraSize().
kInitFocusDistance
const float colmap::ModelViewerWidget::kInitFocusDistance = 100.0f
Definition at line 41 of file model_viewer_widget.h.
kInitImageSize
const float colmap::ModelViewerWidget::kInitImageSize = 0.2f
Definition at line 50 of file model_viewer_widget.h.
kInitNearPlane
const float colmap::ModelViewerWidget::kInitNearPlane = 1.0f
Definition at line 36 of file model_viewer_widget.h.
kInitPointSize
const float colmap::ModelViewerWidget::kInitPointSize = 1.0f
Definition at line 46 of file model_viewer_widget.h.
kMaxFocusDistance
const float colmap::ModelViewerWidget::kMaxFocusDistance = 1e8f
Definition at line 43 of file model_viewer_widget.h.
Referenced by ChangeFocusDistance().
kMaxImageSize
const float colmap::ModelViewerWidget::kMaxImageSize = 1e3f
Definition at line 52 of file model_viewer_widget.h.
Referenced by ChangeCameraSize().
kMaxNearPlane
const float colmap::ModelViewerWidget::kMaxNearPlane = 1e5f
Definition at line 38 of file model_viewer_widget.h.
Referenced by ChangeNearPlane().
kMaxPointSize
const float colmap::ModelViewerWidget::kMaxPointSize = 100.0f
Definition at line 48 of file model_viewer_widget.h.
Referenced by ChangePointSize().
kMinFocusDistance
const float colmap::ModelViewerWidget::kMinFocusDistance = 1e-5f
Definition at line 42 of file model_viewer_widget.h.
Referenced by ChangeFocusDistance().
kMinImageSize
const float colmap::ModelViewerWidget::kMinImageSize = 1e-6f
Definition at line 51 of file model_viewer_widget.h.
Referenced by ChangeCameraSize().
kMinNearPlane
const float colmap::ModelViewerWidget::kMinNearPlane = 1e-3f
Definition at line 37 of file model_viewer_widget.h.
Referenced by ChangeNearPlane().
kMinPointSize
const float colmap::ModelViewerWidget::kMinPointSize = 0.5f
Definition at line 47 of file model_viewer_widget.h.
Referenced by ChangePointSize().
kNearPlaneScaleSpeed
const float colmap::ModelViewerWidget::kNearPlaneScaleSpeed = 0.02f
Definition at line 39 of file model_viewer_widget.h.
Referenced by ChangeNearPlane().
kPointScaleSpeed
const float colmap::ModelViewerWidget::kPointScaleSpeed = 0.1f
Definition at line 49 of file model_viewer_widget.h.
Referenced by ChangePointSize().
points3D
std::unordered_map<point3D_t, Point3D> colmap::ModelViewerWidget::points3D
Definition at line 111 of file model_viewer_widget.h.
Referenced by ClearReconstruction(), ReloadReconstruction(), and colmap::PointViewerWidget::Show().
reconstruction
Reconstruction* colmap::ModelViewerWidget::reconstruction = nullptr
Definition at line 108 of file model_viewer_widget.h.
Referenced by ClearReconstruction(), and ReloadReconstruction().
reg_image_ids
std::vector<image_t> colmap::ModelViewerWidget::reg_image_ids
Definition at line 112 of file model_viewer_widget.h.
Referenced by ClearReconstruction(), and ReloadReconstruction().
statusbar_status_label
QLabel* colmap::ModelViewerWidget::statusbar_status_label
Definition at line 114 of file model_viewer_widget.h.
Referenced by ReloadReconstruction().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/model_viewer_widget.h
/root/ACloudViewer/libs/Reconstruction/src/ui/model_viewer_widget.cc