ACloudViewer: qAnimationDlg Class Reference
qAnimationDlg Class Reference
Dialog for qAnimation plugin.
#include <qAnimationDlg.h>
Classes
struct Step
Simple step (viewport + time)
Public Member Functions
qAnimationDlg (QWidget *view3d, QWidget *parent=nullptr)
Default constructor.
virtual ~qAnimationDlg ()
Destrcuctor.
bool init (const std::vector< cc2DViewportObject * > &viewports, const std::vector< ccMesh * > &meshes)
Initialize the dialog with a set of viewports.
ccPolyline * getTrajectory ()
bool exportTrajectoryOnExit ()
bool updateTextures () const
Protected Types
typedef std::vector< Step > Trajectory
typedef std::vector< ccMesh * > MeshList
Protected Member Functions
void onFPSChanged (int)
void onTotalTimeChanged (double)
void onStepTimeChanged (double)
void onLoopToggled (bool)
void onCurrentStepChanged (int)
void onBrowseButtonClicked ()
void onBrowseTexturesButtonClicked ()
void onAutoStepsDurationToggled (bool)
void onSmoothTrajectoryToggled (bool)
void onSmoothRatioChanged (double)
void preview ()
void renderAnimation ()
void renderFrames ()
void onAccept ()
void onReject ()
void onItemChanged (QListWidgetItem *)
int getCurrentStepIndex ()
size_t countEnabledSteps () const
bool smoothModeEnabled () const
int countFrames (size_t startIndex=0)
void applyViewport (const ecvViewportParameters &viewportParameters)
double computeTotalTime ()
void updateCurrentStepDuration ()
void updateTotalDuration ()
bool updateCameraTrajectory ()
bool updateSmoothCameraTrajectory ()
bool getNextSegment (size_t &vp1, size_t &vp2) const
void render (bool asSeparateFrames)
bool smoothTrajectory (double ratio, unsigned iterationCount)
bool getCompressedTrajectory (Trajectory &compressedTrajectory) const
void updateSmoothTrajectoryDurations ()
void textureAnimationPreview (const QStringList &texture_files, QProgressDialog &progressDialog)
bool textureAnimationRender (const QStringList &texture_files, QProgressDialog &progressDialog, bool asSeparateFrames)
Protected Attributes
Trajectory m_videoSteps
Animation.
Trajectory m_smoothVideoSteps
Smoothed animation.
MeshList m_mesh_list
QWidget * m_view3d
Associated 3D view.
Detailed Description
Dialog for qAnimation plugin.
Definition at line 48 of file qAnimationDlg.h.
Member Typedef Documentation
MeshList
typedef std::vector<ccMesh*> qAnimationDlg::MeshList protected
Definition at line 121 of file qAnimationDlg.h.
Trajectory
typedef std::vector<Step> qAnimationDlg::Trajectory protected
Definition at line 120 of file qAnimationDlg.h.
Constructor & Destructor Documentation
qAnimationDlg()
qAnimationDlg::qAnimationDlg (QWidget * view3d, QWidget * parent = nullptr)
Default constructor.
Definition at line 82 of file qAnimationDlg.cpp.
References getImageList(), QVideoEncoder::GetSupportedOutputFormats(), onAccept(), onAutoStepsDurationToggled(), onBrowseButtonClicked(), onBrowseTexturesButtonClicked(), onFPSChanged(), onLoopToggled(), onReject(), onSmoothRatioChanged(), onSmoothTrajectoryToggled(), onStepTimeChanged(), onTotalTimeChanged(), preview(), renderAnimation(), renderFrames(), size, smoothTrajectory(), and updateTextures().
~qAnimationDlg()
qAnimationDlg::~qAnimationDlg () virtual
Destrcuctor.
Definition at line 236 of file qAnimationDlg.cpp.
Member Function Documentation
applyViewport()
void qAnimationDlg::applyViewport (const ecvViewportParameters & viewportParameters) protected
Definition at line 754 of file qAnimationDlg.cpp.
References m_view3d, ecvDisplayTools::SetViewportParameters(), and ecvDisplayTools::UpdateScreen().
Referenced by onCurrentStepChanged(), preview(), and render().
computeTotalTime()
double qAnimationDlg::computeTotalTime () protected
Definition at line 734 of file qAnimationDlg.cpp.
References count, getNextSegment(), and m_videoSteps.
Referenced by onTotalTimeChanged(), and updateTotalDuration().
countEnabledSteps()
size_t qAnimationDlg::countEnabledSteps () const protected
Definition at line 898 of file qAnimationDlg.cpp.
References count, and m_videoSteps.
Referenced by getCompressedTrajectory(), smoothTrajectory(), and updateSmoothCameraTrajectory().
countFrames()
int qAnimationDlg::countFrames (size_t startIndex = 0) protected
Definition at line 961 of file qAnimationDlg.cpp.
References qAnimationDlg::Step::duration_sec, getNextSegment(), and m_videoSteps.
exportTrajectoryOnExit()
bool qAnimationDlg::exportTrajectoryOnExit ()
Definition at line 730 of file qAnimationDlg.cpp.
getCompressedTrajectory()
bool qAnimationDlg::getCompressedTrajectory (Trajectory & compressedTrajectory) const protected
Definition at line 987 of file qAnimationDlg.cpp.
References countEnabledSteps(), and m_videoSteps.
Referenced by preview(), render(), and smoothTrajectory().
getCurrentStepIndex()
int qAnimationDlg::getCurrentStepIndex () protected
Definition at line 750 of file qAnimationDlg.cpp.
Referenced by init(), onAutoStepsDurationToggled(), onStepTimeChanged(), preview(), and updateCurrentStepDuration().
getNextSegment()
bool qAnimationDlg::getNextSegment (size_t & vp1, size_t & vp2) const protected
Definition at line 910 of file qAnimationDlg.cpp.
References m_videoSteps.
Referenced by computeTotalTime(), countFrames(), onAutoStepsDurationToggled(), onTotalTimeChanged(), updateCameraTrajectory(), and updateSmoothTrajectoryDurations().
getTrajectory()
ccPolyline * qAnimationDlg::getTrajectory ()
Definition at line 725 of file qAnimationDlg.cpp.
init()
bool qAnimationDlg::init (const std::vector< cc2DViewportObject * > & viewports, const std::vector< ccMesh * > & meshes)
Initialize the dialog with a set of viewports.
Definition at line 246 of file qAnimationDlg.cpp.
References ecvViewportParameters::computeViewMatrix(), getCurrentStepIndex(), ccObject::getMetaData(), ccObject::getName(), cc2DViewportObject::getParameters(), ccGLMatrixTpl< T >::getTranslationAsVec3D(), ecvDisplayTools::GetVisibleObjectsBB(), ccObject::hasMetaData(), ccGLMatrixTpl< T >::inverse(), m_mesh_list, m_videoSteps, onCurrentStepChanged(), onItemChanged(), s_stepDurationKey(), s_stepEnabledKey(), and updateCameraTrajectory().
onAccept()
void qAnimationDlg::onAccept () protected
Definition at line 325 of file qAnimationDlg.cpp.
References m_videoSteps, s_stepDurationKey(), s_stepEnabledKey(), and ccObject::setMetaData().
Referenced by qAnimationDlg().
onAutoStepsDurationToggled()
void qAnimationDlg::onAutoStepsDurationToggled (bool state) protected
Definition at line 621 of file qAnimationDlg.cpp.
References count, qAnimationDlg::Step::duration_sec, getCurrentStepIndex(), getNextSegment(), qAnimationDlg::Step::indexInSmoothTrajectory, length(), qAnimationDlg::Step::length, cloudViewer::LessThanEpsilon(), m_smoothVideoSteps, m_videoSteps, onCurrentStepChanged(), CVLog::PrintDebug(), and smoothModeEnabled().
Referenced by onSmoothTrajectoryToggled(), onTotalTimeChanged(), qAnimationDlg(), and updateCameraTrajectory().
onBrowseButtonClicked()
void qAnimationDlg::onBrowseButtonClicked () protected
Definition at line 864 of file qAnimationDlg.cpp.
Referenced by qAnimationDlg().
onBrowseTexturesButtonClicked()
void qAnimationDlg::onBrowseTexturesButtonClicked () protected
Definition at line 882 of file qAnimationDlg.cpp.
References getImageList(), and size.
Referenced by qAnimationDlg().
onCurrentStepChanged()
void qAnimationDlg::onCurrentStepChanged (int index) protected
Definition at line 1667 of file qAnimationDlg.cpp.
References applyViewport(), m_smoothVideoSteps, m_videoSteps, smoothModeEnabled(), and updateCurrentStepDuration().
Referenced by init(), onAutoStepsDurationToggled(), onItemChanged(), onLoopToggled(), and preview().
onFPSChanged()
void qAnimationDlg::onFPSChanged (int fps) protected
Definition at line 762 of file qAnimationDlg.cpp.
Referenced by qAnimationDlg().
onItemChanged()
void qAnimationDlg::onItemChanged (QListWidgetItem *) protected
Definition at line 1661 of file qAnimationDlg.cpp.
References onCurrentStepChanged(), and updateCameraTrajectory().
Referenced by init().
onLoopToggled()
void qAnimationDlg::onLoopToggled (bool enabled) protected
Definition at line 1693 of file qAnimationDlg.cpp.
References onCurrentStepChanged(), and updateCameraTrajectory().
Referenced by qAnimationDlg().
onReject()
void qAnimationDlg::onReject () protected
Definition at line 323 of file qAnimationDlg.cpp.
Referenced by qAnimationDlg().
onSmoothRatioChanged()
void qAnimationDlg::onSmoothRatioChanged (double ratio) protected
Definition at line 719 of file qAnimationDlg.cpp.
References onSmoothTrajectoryToggled().
Referenced by qAnimationDlg().
onSmoothTrajectoryToggled()
void qAnimationDlg::onSmoothTrajectoryToggled (bool state) protected
Definition at line 711 of file qAnimationDlg.cpp.
References onAutoStepsDurationToggled(), and updateSmoothCameraTrajectory().
Referenced by onSmoothRatioChanged(), and qAnimationDlg().
onStepTimeChanged()
void qAnimationDlg::onStepTimeChanged (double time_sec) protected
Definition at line 849 of file qAnimationDlg.cpp.
References getCurrentStepIndex(), m_videoSteps, updateCurrentStepDuration(), updateSmoothTrajectoryDurations(), and updateTotalDuration().
Referenced by qAnimationDlg().
onTotalTimeChanged()
void qAnimationDlg::onTotalTimeChanged (double newTime_sec) protected
Definition at line 766 of file qAnimationDlg.cpp.
References computeTotalTime(), count, qAnimationDlg::Step::duration_sec, getNextSegment(), qAnimationDlg::Step::indexInSmoothTrajectory, length(), qAnimationDlg::Step::length, cloudViewer::LessThanEpsilon(), m_smoothVideoSteps, m_videoSteps, onAutoStepsDurationToggled(), CVLog::PrintDebug(), smoothModeEnabled(), and updateCurrentStepDuration().
Referenced by qAnimationDlg().
preview()
void qAnimationDlg::preview () protected
Definition at line 1011 of file qAnimationDlg.cpp.
References applyViewport(), qAnimationDlg::Step::duration_sec, CVLog::Error(), CVTools::FromQString(), getCompressedTrajectory(), getCurrentStepIndex(), getImageList(), ViewInterpolate::interpolate(), m_mesh_list, m_smoothVideoSteps, m_videoSteps, max(), onCurrentStepChanged(), cloudViewer::utility::Sleep(), smoothModeEnabled(), textureAnimationPreview(), updateTextures(), qAnimationDlg::Step::viewportParams, and CVLog::Warning().
Referenced by qAnimationDlg().
render()
void qAnimationDlg::render (bool asSeparateFrames) protected
Definition at line 1358 of file qAnimationDlg.cpp.
References applyViewport(), qAnimationDlg::Step::duration_sec, CVLog::Error(), CVTools::FromQString(), getCompressedTrajectory(), getImageList(), ecvDisplayTools::GetScreenSize(), ecvDisplayTools::GlHeight(), ecvDisplayTools::GlWidth(), image, ViewInterpolate::interpolate(), m_mesh_list, m_smoothVideoSteps, m_videoSteps, m_view3d, ecvDisplayTools::RenderToImage(), smoothModeEnabled(), textureAnimationRender(), updateTextures(), qAnimationDlg::Step::viewportParams, and CVLog::Warning().
Referenced by renderAnimation(), and renderFrames().
renderAnimation()
void qAnimationDlg::renderAnimation () inline protected
Definition at line 79 of file qAnimationDlg.h.
References render().
Referenced by qAnimationDlg().
renderFrames()
void qAnimationDlg::renderFrames () inline protected
Definition at line 80 of file qAnimationDlg.h.
References render().
Referenced by qAnimationDlg().
smoothModeEnabled()
bool qAnimationDlg::smoothModeEnabled () const protected
Definition at line 238 of file qAnimationDlg.cpp.
References m_smoothVideoSteps.
Referenced by onAutoStepsDurationToggled(), onCurrentStepChanged(), onTotalTimeChanged(), preview(), render(), and updateSmoothTrajectoryDurations().
smoothTrajectory()
bool qAnimationDlg::smoothTrajectory (double ratio, unsigned iterationCount) protected
Definition at line 459 of file qAnimationDlg.cpp.
References qAnimationDlg::Step::cameraCenter, countEnabledSteps(), qAnimationDlg::Step::duration_sec, CVLog::Error(), getCompressedTrajectory(), qAnimationDlg::Step::indexInOriginalTrajectory, ViewInterpolate::interpolate(), m_smoothVideoSteps, m_videoSteps, Vector3Tpl< Type >::norm(), PC_ONE, updateSmoothTrajectoryDurations(), qAnimationDlg::Step::viewportParams, and CVLog::Warning().
Referenced by qAnimationDlg(), and updateSmoothCameraTrajectory().
textureAnimationPreview()
void qAnimationDlg::textureAnimationPreview (const QStringList & texture_files, QProgressDialog & progressDialog) protected
Definition at line 1203 of file qAnimationDlg.cpp.
References CVTools::FromQString(), m_mesh_list, cloudViewer::utility::Sleep(), ecvDisplayTools::UpdateScreen(), and CVLog::Warning().
Referenced by preview().
textureAnimationRender()
bool qAnimationDlg::textureAnimationRender (const QStringList & texture_files, QProgressDialog & progressDialog, bool asSeparateFrames) protected
Definition at line 1258 of file qAnimationDlg.cpp.
References CVTools::FromQString(), image, m_mesh_list, ecvDisplayTools::RenderToImage(), ecvDisplayTools::UpdateScreen(), and CVLog::Warning().
Referenced by render().
updateCameraTrajectory()
bool qAnimationDlg::updateCameraTrajectory () protected
Definition at line 367 of file qAnimationDlg.cpp.
References count, getNextSegment(), qAnimationDlg::Step::length, m_smoothVideoSteps, m_videoSteps, onAutoStepsDurationToggled(), result, updateSmoothCameraTrajectory(), updateTotalDuration(), and CVLog::Warning().
Referenced by init(), onItemChanged(), and onLoopToggled().
updateCurrentStepDuration()
void qAnimationDlg::updateCurrentStepDuration () protected
Definition at line 1652 of file qAnimationDlg.cpp.
References getCurrentStepIndex(), and m_videoSteps.
Referenced by onCurrentStepChanged(), onStepTimeChanged(), and onTotalTimeChanged().
updateSmoothCameraTrajectory()
bool qAnimationDlg::updateSmoothCameraTrajectory () protected
Definition at line 590 of file qAnimationDlg.cpp.
References countEnabledSteps(), CVLog::Error(), m_smoothVideoSteps, m_videoSteps, and smoothTrajectory().
Referenced by onSmoothTrajectoryToggled(), and updateCameraTrajectory().
updateSmoothTrajectoryDurations()
void qAnimationDlg::updateSmoothTrajectoryDurations () protected
Definition at line 412 of file qAnimationDlg.cpp.
References count, qAnimationDlg::Step::duration_sec, getNextSegment(), cloudViewer::GreaterThanEpsilon(), qAnimationDlg::Step::indexInSmoothTrajectory, length(), qAnimationDlg::Step::length, m_smoothVideoSteps, m_videoSteps, and smoothModeEnabled().
Referenced by onStepTimeChanged(), and smoothTrajectory().
updateTextures()
bool qAnimationDlg::updateTextures () const
Definition at line 242 of file qAnimationDlg.cpp.
References m_mesh_list.
Referenced by preview(), qAnimationDlg(), and render().
updateTotalDuration()
void qAnimationDlg::updateTotalDuration () protected
Definition at line 1644 of file qAnimationDlg.cpp.
References computeTotalTime().
Referenced by onStepTimeChanged(), and updateCameraTrajectory().
Member Data Documentation
m_mesh_list
MeshList qAnimationDlg::m_mesh_list protected
Definition at line 132 of file qAnimationDlg.h.
Referenced by init(), preview(), render(), textureAnimationPreview(), textureAnimationRender(), and updateTextures().
m_smoothVideoSteps
Trajectory qAnimationDlg::m_smoothVideoSteps protected
Smoothed animation.
Definition at line 131 of file qAnimationDlg.h.
Referenced by onAutoStepsDurationToggled(), onCurrentStepChanged(), onTotalTimeChanged(), preview(), render(), smoothModeEnabled(), smoothTrajectory(), updateCameraTrajectory(), updateSmoothCameraTrajectory(), and updateSmoothTrajectoryDurations().
m_videoSteps
Trajectory qAnimationDlg::m_videoSteps protected
Animation.
Definition at line 129 of file qAnimationDlg.h.
Referenced by computeTotalTime(), countEnabledSteps(), countFrames(), getCompressedTrajectory(), getNextSegment(), init(), onAccept(), onAutoStepsDurationToggled(), onCurrentStepChanged(), onStepTimeChanged(), onTotalTimeChanged(), preview(), render(), smoothTrajectory(), updateCameraTrajectory(), updateCurrentStepDuration(), updateSmoothCameraTrajectory(), and updateSmoothTrajectoryDurations().
m_view3d
QWidget* qAnimationDlg::m_view3d protected
Associated 3D view.
Definition at line 135 of file qAnimationDlg.h.
Referenced by applyViewport(), and render().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qAnimation/include/qAnimationDlg.h
/root/ACloudViewer/plugins/core/Standard/qAnimation/src/qAnimationDlg.cpp