ACloudViewer: cloudViewer::core::TensorList Class Reference
cloudViewer::core::TensorList Class Reference
#include <TensorList.h>
Public Member Functions
TensorList ()
Useful to support operator[] in a map.
TensorList (const SizeVector &element_shape, Dtype dtype, const Device &device=Device("CPU:0"))
TensorList (const std::vector< Tensor > &tensors)
TensorList (int64_t size, const SizeVector &element_shape, Dtype dtype, const Device &device=Device("CPU:0"))
TensorList (const std::initializer_list< Tensor > &tensors)
template<class InputIterator >
TensorList (InputIterator begin, InputIterator end)
TensorList (const TensorList &other)=default
TensorList (TensorList &&other)=default
TensorList & operator= (const TensorList &other) &=default
TensorList & operator= (TensorList &&other) &=default
void CopyFrom (const TensorList &other)
TensorList Clone () const
Tensor AsTensor () const
Return the reference of the contained valid tensors with shared memory.
void Resize (int64_t new_size)
void PushBack (const Tensor &tensor)
void Extend (const TensorList &other)
TensorList operator+ (const TensorList &other) const
Concatenate two tensorlists.
TensorList & operator+= (const TensorList &other)
Tensor operator[] (int64_t index) const
void Clear ()
std::string ToString () const
SizeVector GetElementShape () const
void AssertElementShape (const SizeVector &expected_element_shape) const
void AssertDevice (const Device &expected_device) const
Device GetDevice () const
Dtype GetDtype () const
int64_t GetSize () const
int64_t GetReservedSize () const
bool IsResizable () const
Static Public Member Functions
static TensorList FromTensor (const Tensor &tensor, bool inplace=false)
static TensorList Concatenate (const TensorList &a, const TensorList &b)
Protected Member Functions
TensorList (const SizeVector element_shape, int64_t size, int64_t reserved_size, const Tensor &internal_tensor, bool is_resizable)
Fully specified constructor.
void ResizeWithExpand (int64_t new_size)
Static Protected Member Functions
static int64_t ComputeReserveSize (int64_t size)
Protected Attributes
SizeVector element_shape_
The shape for each element tensor in the tensorlist.
int64_t size_ = 0
int64_t reserved_size_ = 0
Tensor internal_tensor_
The internal tensor for data storage.
bool is_resizable_ = true
Detailed Description
A tensorlist is a list of Tensors of the same shape, similar to std::vector<Tensor>. Internally, a tensorlist stores the Tensors in one bigger internal tensor, where the begin dimension of the internal tensor is extendable.
Examples:
A 3D point cloud with N points:
element_shape : (3,)
reserved_size : M, where M >= N
internal_tensor.shape: (M, 3)
Sparse voxel grid of N voxels:
element_shape : (8, 8, 8)
reserved_size : M, where M >= N
internal_tensor.shape: (M, 8, 8, 8)
Definition at line 39 of file TensorList.h.
Constructor & Destructor Documentation
TensorList() [1/9]
cloudViewer::core::TensorList::TensorList () inline
Useful to support operator[] in a map.
Definition at line 42 of file TensorList.h.
Referenced by Clear(), and FromTensor().
TensorList() [2/9]
cloudViewer::core::TensorList::TensorList (const SizeVector & element_shape, Dtype dtype, const Device & device = Device("CPU:0")) inline
Constructs an empty tensorlist.
Parameters
element_shape Shape of the contained tensors, e.g. {3,}. 0-sized and scalar element_shape are allowed.
dtype Data type of the contained tensors. e.g. core::Float32.
device Device of the contained tensors. e.g. Device("CPU:0").
Definition at line 50 of file TensorList.h.
References reserved_size_.
TensorList() [3/9]
cloudViewer::core::TensorList::TensorList (const std::vector< Tensor > & tensors) inline
Constructs a tensorlist from a vector of Tensors. The tensors must have the same shape, dtype and device. Values will be copied.
Parameters
tensors A vector of tensors. The tensors must have common shape, dtype and device.
Definition at line 65 of file TensorList.h.
TensorList() [4/9]
cloudViewer::core::TensorList::TensorList (int64_t size, const SizeVector & element_shape, Dtype dtype, const Device & device = Device("CPU:0")) inline
Constructs a tensorlist with specified size.
Parameters
size Size of the tensorlist.
element_shape Shape of the contained tensors, e.g. {3,}. 0-sized and scalar element_shape are allowed.
dtype Data type of the contained tensors. e.g. core::Float32.
device Device of the contained tensors. e.g. Device("CPU:0").
Definition at line 75 of file TensorList.h.
References reserved_size_.
TensorList() [5/9]
cloudViewer::core::TensorList::TensorList (const std::initializer_list< Tensor > & tensors) inline
Constructs a tensorlist from a list of Tensors. The tensors must have the same shape, dtype and device. Values will be copied.
Parameters
tensors A list of tensors. The tensors must have common shape, dtype and device.
Definition at line 91 of file TensorList.h.
TensorList() [6/9]
template<class InputIterator > cloudViewer::core::TensorList::TensorList (InputIterator begin, InputIterator end) inline
Constructs a tensorlist from Tensor iterator. The tensors must have the same shape, dtype and device. Values will be copied.
Parameters
begin Begin iterator.
end End iterator.
Definition at line 100 of file TensorList.h.
References ComputeReserveSize(), cloudViewer::core::shape_util::Concat(), element_shape_, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), internal_tensor_, LogError, reserved_size_, size, and size_.
TensorList() [7/9]
cloudViewer::core::TensorList::TensorList (const TensorList & other) default
Copy constructor for tensorlist. The internal tensor will share the same memory as the input. Also see: the copy constructor for Tensor.
TensorList() [8/9]
cloudViewer::core::TensorList::TensorList (TensorList && other) default
Move constructor for tensorlist. The internal tensor will share the same memory as the input. Also see: the move constructor for Tensor.
TensorList() [9/9]
cloudViewer::core::TensorList::TensorList (const SizeVector element_shape, int64_t size, int64_t reserved_size, const Tensor & internal_tensor, bool is_resizable) inline protected
Fully specified constructor.
Definition at line 274 of file TensorList.h.
Member Function Documentation
AssertDevice()
void cloudViewer::core::TensorList::AssertDevice (const Device & expected_device) const inline
Definition at line 252 of file TensorList.h.
References GetDevice(), LogError, cloudViewer::core::Device::ToString(), and ToString().
AssertElementShape()
void cloudViewer::core::TensorList::AssertElementShape (const SizeVector & expected_element_shape) const inline
Definition at line 243 of file TensorList.h.
References element_shape_, and LogError.
AsTensor()
Tensor cloudViewer::core::TensorList::AsTensor () const
Return the reference of the contained valid tensors with shared memory.
Definition at line 70 of file TensorList.cpp.
References internal_tensor_, size_, and cloudViewer::core::Tensor::Slice().
Referenced by Extend().
Clear()
void cloudViewer::core::TensorList::Clear ()
Clear the tensorlist by disgarding the internal tensor and resetting the size to 0. This operation is only valid for resizable tensorlist.
Definition at line 134 of file TensorList.cpp.
References cloudViewer::core::AssertIsResizable(), element_shape_, GetDevice(), GetDtype(), and TensorList().
Clone()
TensorList cloudViewer::core::TensorList::Clone () const
Duplicate the current tensorlist. Values will be copied. The returned tensor will always be resizable.
Definition at line 56 of file TensorList.cpp.
References CopyFrom().
Referenced by Concatenate().
ComputeReserveSize()
int64_t cloudViewer::core::TensorList::ComputeReserveSize (int64_t size) static protected
Compute the reserved size for the desired number of tensors with reserved_size_ = (1 << (ceil(log2(size_)) + 1)).
Definition at line 156 of file TensorList.cpp.
References LogError.
Referenced by FromTensor(), ResizeWithExpand(), and TensorList().
Concatenate()
TensorList cloudViewer::core::TensorList::Concatenate (const TensorList & a, const TensorList & b) static
Concatenate two tensorlists. Return a new tensorlists with data copied. Two tensorlists must have the same element_shape, type, and device.
Definition at line 121 of file TensorList.cpp.
References Clone(), and result.
Referenced by operator+().
CopyFrom()
void cloudViewer::core::TensorList::CopyFrom (const TensorList & other)
Performs actual copy from another tensorlist. The internal tensor will be explicitly copied. All attributes will be copied and replaced. The returned tensor will always be resizable.
Definition at line 62 of file TensorList.cpp.
References cloudViewer::core::Tensor::Clone(), internal_tensor_, and is_resizable_.
Referenced by Clone().
Extend()
void cloudViewer::core::TensorList::Extend (const TensorList & other)
Extend the current tensorlist with another tensorlist appended to the end. The data is copied. The two tensorlists must have the same element_shape, dtype, and device. This operation is only valid for resizable tensorlist.
Definition at line 94 of file TensorList.cpp.
References cloudViewer::core::AssertIsResizable(), AsTensor(), element_shape_, GetDevice(), GetDtype(), GetElementShape(), GetSize(), internal_tensor_, LogError, ResizeWithExpand(), size_, cloudViewer::core::Tensor::Slice(), cloudViewer::core::Device::ToString(), cloudViewer::core::Dtype::ToString(), and ToString().
Referenced by operator+=().
FromTensor()
TensorList cloudViewer::core::TensorList::FromTensor (const Tensor & tensor, bool inplace = false) static
Factory function to create tensorlist from a Tensor.
Parameters
tensor The input tensor. The tensor must have at least one dimension (tensor.NumDims() >= 1). The first dimension of the tensor will be used as the "size" dimension of the tensorlist, while the remaining dimensions will be used as the element shape of the tensor list. For example, if the input tensor has shape (2, 3, 4), the resulting tensorlist will have size 2 and element shape (3, 4).
inplace If inplace == true, the tensorlist shares the same memory with the input tensor. The input tensor must be contiguous. The resulting tensorlist cannot be extended. If inplace == false, the tensor values will be copied when creating the tensorlist.
Definition at line 28 of file TensorList.cpp.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), ComputeReserveSize(), cloudViewer::core::shape_util::Concat(), cloudViewer::core::Tensor::Empty(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::IsContiguous(), LogError, next, cloudViewer::core::SmallVectorBase< Size_T >::size(), size, cloudViewer::core::Tensor::Slice(), and TensorList().
GetDevice()
Device cloudViewer::core::TensorList::GetDevice () const inline
Definition at line 260 of file TensorList.h.
References cloudViewer::core::Tensor::GetDevice(), and internal_tensor_.
Referenced by AssertDevice(), Clear(), Extend(), PushBack(), ResizeWithExpand(), and ToString().
GetDtype()
Dtype cloudViewer::core::TensorList::GetDtype () const inline
Definition at line 262 of file TensorList.h.
References cloudViewer::core::Tensor::GetDtype(), and internal_tensor_.
Referenced by Clear(), Extend(), PushBack(), ResizeWithExpand(), and ToString().
GetElementShape()
SizeVector cloudViewer::core::TensorList::GetElementShape () const inline
Definition at line 241 of file TensorList.h.
References element_shape_.
Referenced by Extend().
GetReservedSize()
int64_t cloudViewer::core::TensorList::GetReservedSize () const inline
Definition at line 266 of file TensorList.h.
References reserved_size_.
GetSize()
int64_t cloudViewer::core::TensorList::GetSize () const inline
Definition at line 264 of file TensorList.h.
References size_.
Referenced by Extend().
IsResizable()
bool cloudViewer::core::TensorList::IsResizable () const inline
Definition at line 270 of file TensorList.h.
References is_resizable_.
Referenced by cloudViewer::core::AssertIsResizable().
operator+()
TensorList cloudViewer::core::TensorList::operator+ (const TensorList & other) const inline
Concatenate two tensorlists.
Definition at line 220 of file TensorList.h.
References Concatenate().
operator+=()
TensorList& cloudViewer::core::TensorList::operator+= (const TensorList & other) inline
Inplace concatenate with another tensorlist. This operation is only valid for resizable tensorlist.
Definition at line 226 of file TensorList.h.
References Extend().
operator=() [1/2]
TensorList& cloudViewer::core::TensorList::operator= (const TensorList & other) & default
Copy assignment operator. The internal tensor will share the same memory as the input.
operator=() [2/2]
TensorList& cloudViewer::core::TensorList::operator= (TensorList && other) & default
Move assignment operator. The internal tensor will share the same memory as the input.
operator[]()
Tensor cloudViewer::core::TensorList::operator[] (int64_t index) const
Extract the i-th Tensor along the begin axis, returning a new view. For advanced indexing like Slice, use tensorlist.AsTensor().Slice().
Definition at line 128 of file TensorList.cpp.
References internal_tensor_, size_, and cloudViewer::core::shape_util::WrapDim().
PushBack()
void cloudViewer::core::TensorList::PushBack (const Tensor & tensor)
Push back a tensor to the tensorlist. The values will be copied. This operation is only valid for resizable tensorlist.
Parameters
tensor The tensor to to be copied to the end of the tensorlist. The tensor must be of the same shape, dtype and device as the tensot list.
Definition at line 83 of file TensorList.cpp.
References cloudViewer::core::AssertIsResizable(), AssertTensorDevice, AssertTensorDtype, AssertTensorShape, element_shape_, GetDevice(), GetDtype(), internal_tensor_, ResizeWithExpand(), and size_.
Resize()
void cloudViewer::core::TensorList::Resize (int64_t new_size)
Resize tensorlist. If the size increases, the increased part will be initialized with 0. If the size decreases, the reserved_size_ remain unchanged. This operation is only valid for resizable tensorlist.
Definition at line 74 of file TensorList.cpp.
References cloudViewer::core::AssertIsResizable(), cloudViewer::core::Tensor::Fill(), internal_tensor_, ResizeWithExpand(), size_, and cloudViewer::core::Tensor::Slice().
ResizeWithExpand()
void cloudViewer::core::TensorList::ResizeWithExpand (int64_t new_size) protected
Expand internal tensor to be larger or equal to the requested size. If the current reserved size is smaller than the requested size, the reserved size will be increased, a new internal tensor will be allocated and the original data will be copied. If the current reserved size is larger than or equal to the requested size, no operation will be performed.
Parameters
new_size The requested size.
Definition at line 140 of file TensorList.cpp.
References ComputeReserveSize(), cloudViewer::core::shape_util::Concat(), element_shape_, GetDevice(), GetDtype(), internal_tensor_, reserved_size_, size_, and cloudViewer::core::Tensor::Slice().
Referenced by Extend(), PushBack(), and Resize().
ToString()
std::string cloudViewer::core::TensorList::ToString () const
Definition at line 185 of file TensorList.cpp.
References element_shape_, format, GetDevice(), GetDtype(), size_, and cloudViewer::core::SizeVector::ToString().
Referenced by AssertDevice(), and Extend().
Member Data Documentation
element_shape_
SizeVector cloudViewer::core::TensorList::element_shape_ protected
The shape for each element tensor in the tensorlist.
Definition at line 301 of file TensorList.h.
Referenced by AssertElementShape(), Clear(), Extend(), GetElementShape(), PushBack(), ResizeWithExpand(), TensorList(), and ToString().
internal_tensor_
Tensor cloudViewer::core::TensorList::internal_tensor_ protected
The internal tensor for data storage.
Definition at line 320 of file TensorList.h.
Referenced by AsTensor(), CopyFrom(), Extend(), GetDevice(), GetDtype(), operator[](), PushBack(), Resize(), ResizeWithExpand(), and TensorList().
is_resizable_
bool cloudViewer::core::TensorList::is_resizable_ = true protected
Whether the tensorlist is resizable. Typically, if the tensorlist is created with pre-allocated shared buffer, the tensorlist is not resizable.
Definition at line 325 of file TensorList.h.
Referenced by CopyFrom(), and IsResizable().
reserved_size_
int64_t cloudViewer::core::TensorList::reserved_size_ = 0 protected
Maximum number of elements in tensorlist.
The internal_tensor_'s shape is (reserved_size_, *element_shape_). In general, reserved_size_ >= (1 << (ceil(log2(size_)) + 1)) as conventionally done in std::vector.
Examples: size_ = 3, reserved_size_ = 8 size_ = 4, reserved_size_ = 8 size_ = 5, reserved_size_ = 16
Definition at line 317 of file TensorList.h.
Referenced by GetReservedSize(), ResizeWithExpand(), and TensorList().
size_
int64_t cloudViewer::core::TensorList::size_ = 0 protected
Number of active (valid) elements in tensorlist. The internal_tensor_ has shape (reserved_size_, *shape_), but only the front (size_, *shape_) is active.
Definition at line 306 of file TensorList.h.
Referenced by AsTensor(), Extend(), GetSize(), operator[](), PushBack(), Resize(), ResizeWithExpand(), TensorList(), and ToString().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/core/TensorList.h
/root/ACloudViewer/libs/cloudViewer/core/TensorList.cpp