ACloudViewer: QCPColoredBars Class Reference
QCPColoredBars Class Reference
QCustomPlot: colored histogram.
#include <ecvQCustomPlot.h>
Classes
class QCPColoredBarData
Public Types
typedef QMultiMap< double, QCPColoredBarData > QCPColoredBarDataMap
Public Types inherited from QCPBars
enum WidthType {
wtAbsolute , wtAxisRectRatio , wtPlotCoords , wtAbsolute ,
wtAxisRectRatio , wtPlotCoords
}
enum WidthType {
wtAbsolute , wtAxisRectRatio , wtPlotCoords , wtAbsolute ,
wtAxisRectRatio , wtPlotCoords
}
Public Member Functions
QCPColoredBars (QCPAxis *keyAxis, QCPAxis *valueAxis)
void setData (const QVector< double > &key, const QVector< double > &value)
void setData (const QVector< double > &key, const QVector< double > &value, const QVector< QColor > &colors)
QRect rect () const
virtual void clearData ()
Public Member Functions inherited from QCPBars
QCPBars (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPBars ()
double width () const
WidthType widthType () const
QCPBarsGroup * barsGroup () const
double baseValue () const
double stackingGap () const
QCPBars * barBelow () const
QCPBars * barAbove () const
QSharedPointer< QCPBarsDataContainer > data () const
void setData (QSharedPointer< QCPBarsDataContainer > data)
void setData (const QVector< double > &keys, const QVector< double > &values, bool alreadySorted=false)
void setWidth (double width)
void setWidthType (WidthType widthType)
void setBarsGroup (QCPBarsGroup *barsGroup)
void setBaseValue (double baseValue)
void setStackingGap (double pixels)
void addData (const QVector< double > &keys, const QVector< double > &values, bool alreadySorted=false)
void addData (double key, double value)
void moveBelow (QCPBars *bars)
void moveAbove (QCPBars *bars)
virtual QCPDataSelection selectTestRect (const QRectF &rect, bool onlySelectable) const
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
virtual QCPRange getKeyRange (bool &foundRange, QCP::SignDomain inSignDomain=QCP::sdBoth) const
virtual QCPRange getValueRange (bool &foundRange, QCP::SignDomain inSignDomain=QCP::sdBoth, const QCPRange &inKeyRange=QCPRange()) const
virtual QPointF dataPixelPosition (int index) const
QCPBars (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPBars ()
double width () const
WidthType widthType () const
QCPBarsGroup * barsGroup () const
double baseValue () const
QCPBars * barBelow () const
QCPBars * barAbove () const
QCPBarDataMap * data () const
void setWidth (double width)
void setWidthType (WidthType widthType)
void setBarsGroup (QCPBarsGroup *barsGroup)
void setBaseValue (double baseValue)
void setData (QCPBarDataMap *data, bool copy=false)
void setData (const QVector< double > &key, const QVector< double > &value)
void moveBelow (QCPBars *bars)
void moveAbove (QCPBars *bars)
void addData (const QCPBarDataMap &dataMap)
void addData (const QCPBarData &data)
void addData (double key, double value)
void addData (const QVector< double > &keys, const QVector< double > &values)
void removeDataBefore (double key)
void removeDataAfter (double key)
void removeData (double fromKey, double toKey)
void removeData (double key)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractPlottable1D< QCPBarsData >
QCPAbstractPlottable1D (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPAbstractPlottable1D ()
virtual int dataCount () const
virtual double dataMainKey (int index) const
virtual double dataSortKey (int index) const
virtual double dataMainValue (int index) const
virtual QCPRange dataValueRange (int index) const
virtual bool sortKeyIsMainKey () const
virtual int findBegin (double sortKey, bool expandedRange=true) const
virtual int findEnd (double sortKey, bool expandedRange=true) const
virtual QCPPlottableInterface1D * interface1D ()
Public Member Functions inherited from QCPAbstractPlottable
QCPAbstractPlottable (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPAbstractPlottable ()
QString name () const
bool antialiasedFill () const
bool antialiasedScatters () const
QPen pen () const
QBrush brush () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
QCP::SelectionType selectable () const
bool selected () const
QCPDataSelection selection () const
QCPSelectionDecorator * selectionDecorator () const
void setName (const QString &name)
void setAntialiasedFill (bool enabled)
void setAntialiasedScatters (bool enabled)
void setPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setKeyAxis (QCPAxis *axis)
void setValueAxis (QCPAxis *axis)
Q_SLOT void setSelectable (QCP::SelectionType selectable)
Q_SLOT void setSelection (QCPDataSelection selection)
void setSelectionDecorator (QCPSelectionDecorator *decorator)
void coordsToPixels (double key, double value, double &x, double &y) const
const QPointF coordsToPixels (double key, double value) const
void pixelsToCoords (double x, double y, double &key, double &value) const
void pixelsToCoords (const QPointF &pixelPos, double &key, double &value) const
void rescaleAxes (bool onlyEnlarge=false) const
void rescaleKeyAxis (bool onlyEnlarge=false) const
void rescaleValueAxis (bool onlyEnlarge=false, bool inKeyRange=false) const
bool addToLegend (QCPLegend *legend)
bool addToLegend ()
bool removeFromLegend (QCPLegend *legend) const
bool removeFromLegend () const
QCPAbstractPlottable (QCPAxis *keyAxis, QCPAxis *valueAxis)
QString name () const
bool antialiasedFill () const
bool antialiasedScatters () const
bool antialiasedErrorBars () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
bool selectable () const
bool selected () const
void setName (const QString &name)
void setAntialiasedFill (bool enabled)
void setAntialiasedScatters (bool enabled)
void setAntialiasedErrorBars (bool enabled)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setKeyAxis (QCPAxis *axis)
void setValueAxis (QCPAxis *axis)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual bool addToLegend ()
virtual bool removeFromLegend () const
void rescaleAxes (bool onlyEnlarge=false) const
void rescaleKeyAxis (bool onlyEnlarge=false) const
void rescaleValueAxis (bool onlyEnlarge=false) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
virtual ~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Public Member Functions inherited from QCPPlottableInterface1D
virtual ~QCPPlottableInterface1D ()
Protected Member Functions
virtual void draw (QCPPainter *painter)
Protected Member Functions inherited from QCPBars
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const
void getVisibleDataBounds (QCPBarsDataContainer::const_iterator &begin, QCPBarsDataContainer::const_iterator &end) const
QRectF getBarRect (double key, double value) const
void getPixelWidth (double key, double &lower, double &upper) const
double getStackedBaseValue (double key, bool positive) const
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
void getVisibleDataBounds (QCPBarDataMap::const_iterator &lower, QCPBarDataMap::const_iterator &upperEnd) const
QPolygonF getBarPolygon (double key, double value) const
void getPixelWidth (double key, double &lower, double &upper) const
double getStackedBaseValue (double key, bool positive) const
Protected Member Functions inherited from QCPAbstractPlottable1D< QCPBarsData >
void getDataSegments (QList< QCPDataRange > &selectedSegments, QList< QCPDataRange > &unselectedSegments) const
void drawPolyline (QCPPainter *painter, const QVector< QPointF > &lineData) const
Protected Member Functions inherited from QCPAbstractPlottable
virtual QRect clipRect () const
virtual QCP::Interaction selectionCategory () const
void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void applyFillAntialiasingHint (QCPPainter *painter) const
void applyScattersAntialiasingHint (QCPPainter *painter) const
virtual QRect clipRect () const
virtual QCP::Interaction selectionCategory () const
void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void coordsToPixels (double key, double value, double &x, double &y) const
const QPointF coordsToPixels (double key, double value) const
void pixelsToCoords (double x, double y, double &key, double &value) const
void pixelsToCoords (const QPointF &pixelPos, double &key, double &value) const
QPen mainPen () const
QBrush mainBrush () const
void applyFillAntialiasingHint (QCPPainter *painter) const
void applyScattersAntialiasingHint (QCPPainter *painter) const
void applyErrorBarsAntialiasingHint (QCPPainter *painter) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual void mousePressEvent (QMouseEvent *event, const QVariant &details)
virtual void mouseMoveEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseReleaseEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseDoubleClickEvent (QMouseEvent *event, const QVariant &details)
virtual void wheelEvent (QWheelEvent *event)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QCPColoredBarDataMap m_coloredData
Protected Attributes inherited from QCPBars
double mWidth
WidthType mWidthType
QCPBarsGroup * mBarsGroup
double mBaseValue
double mStackingGap
QPointer< QCPBars > mBarBelow
QPointer< QCPBars > mBarAbove
QCPBarDataMap * mData
Protected Attributes inherited from QCPAbstractPlottable1D< QCPBarsData >
QSharedPointer< QCPDataContainer< QCPBarsData > > mDataContainer
Protected Attributes inherited from QCPAbstractPlottable
QString mName
bool mAntialiasedFill
bool mAntialiasedScatters
QPen mPen
QBrush mBrush
QPointer< QCPAxis > mKeyAxis
QPointer< QCPAxis > mValueAxis
QCP::SelectionType mSelectable
QCPDataSelection mSelection
QCPSelectionDecorator * mSelectionDecorator
bool mAntialiasedErrorBars
QPen mSelectedPen
QBrush mSelectedBrush
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractPlottable
void selectionChanged (bool selected)
void selectionChanged (const QCPDataSelection &selection)
void selectableChanged (QCP::SelectionType selectable)
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
void layerChanged (QCPLayer *newLayer)
Protected Types inherited from QCPAbstractPlottable
enum SignDomain { sdNegative , sdBoth , sdPositive }
Static Protected Member Functions inherited from QCPBars
static void connectBars (QCPBars *lower, QCPBars *upper)
static void connectBars (QCPBars *lower, QCPBars *upper)
Detailed Description
QCustomPlot: colored histogram.
Definition at line 73 of file ecvQCustomPlot.h.
Member Typedef Documentation
QCPColoredBarDataMap
typedef QMultiMap<double, QCPColoredBarData> QCPColoredBars::QCPColoredBarDataMap
Definition at line 83 of file ecvQCustomPlot.h.
Constructor & Destructor Documentation
QCPColoredBars()
QCPColoredBars::QCPColoredBars (QCPAxis * keyAxis, QCPAxis * valueAxis) inline
Definition at line 85 of file ecvQCustomPlot.h.
Member Function Documentation
clearData()
virtual void QCPColoredBars::clearData () inline virtual
Removes all data points.
See also
removeData, removeDataAfter, removeDataBefore
Reimplemented from QCPBars.
Definition at line 117 of file ecvQCustomPlot.h.
References QCPBars::data(), and m_coloredData.
Referenced by ccHistogramWindow::refreshBars().
draw()
virtual void QCPColoredBars::draw (QCPPainter * painter) inline protected virtual
Reimplemented from QCPBars.
Definition at line 124 of file ecvQCustomPlot.h.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), QCPAbstractPlottable::brush(), color, QCPBars::draw(), QCPBars::getBarRect(), m_coloredData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPBars::mWidth, QCPAbstractPlottable::pen(), and QCPPainter::setPen().
rect()
QRect QCPColoredBars::rect () const inline
Definition at line 114 of file ecvQCustomPlot.h.
References QCPAbstractPlottable::clipRect().
Referenced by ccHistogramWindow::mouseMoveEvent().
setData() [1/2]
void QCPColoredBars::setData (const QVector< double > & key, const QVector< double > & value) inline
Definition at line 88 of file ecvQCustomPlot.h.
References m_coloredData, and QCPBars::setData().
Referenced by ccHistogramWindow::refresh(), and ccHistogramWindow::refreshBars().
setData() [2/2]
void QCPColoredBars::setData (const QVector< double > & key, const QVector< double > & value, const QVector< QColor > & colors) inline
Definition at line 94 of file ecvQCustomPlot.h.
References QCPBars::addData(), QCPColoredBars::QCPColoredBarData::color, colors, QCPBars::data(), QCPBarsData::key, m_coloredData, and QCPBarsData::value.
Member Data Documentation
m_coloredData
QCPColoredBarDataMap QCPColoredBars::m_coloredData protected
Definition at line 169 of file ecvQCustomPlot.h.
Referenced by clearData(), draw(), and setData().
The documentation for this class was generated from the following file:
/root/ACloudViewer/app/ecvQCustomPlot.h