ACloudViewer: PclUtils::renders::MeshMaterialExtractor Class Reference
PclUtils::renders::MeshMaterialExtractor Class Reference
Utility class for extracting and applying materials from mesh.
#include <MeshMaterialExtractor.h>
Static Public Member Functions
static bool ApplyMaterialFromMesh (vtkLODActor *actor, const ccGenericMesh *mesh, vtkPolyData *polydata, TextureRenderManager *render_manager, class vtkRenderer *renderer=nullptr)
Extract and apply material from ccMesh to actor.
Detailed Description
Utility class for extracting and applying materials from mesh.
Handles material extraction from ccGenericMesh and application to VTK actors.
Definition at line 24 of file MeshMaterialExtractor.h.
Member Function Documentation
ApplyMaterialFromMesh()
bool PclUtils::renders::MeshMaterialExtractor::ApplyMaterialFromMesh (vtkLODActor * actor, const ccGenericMesh * mesh, vtkPolyData * polydata, TextureRenderManager * render_manager, class vtkRenderer * renderer = nullptr) static
Extract and apply material from ccMesh to actor.
Parameters
actor VTK actor to apply material to
mesh ccMesh object containing materials
polydata Polygon data (for texture coordinates)
render_manager Texture render manager for applying materials
renderer VTK renderer (optional)
Returns
true on success
Definition at line 26 of file MeshMaterialExtractor.cpp.
References ccMaterialSet::addMaterial(), PclUtils::renders::TextureRenderManager::Apply(), CVLog::Error(), ccDrawableObject::hasColors(), CVLog::Print(), and CVLog::Warning().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/PclUtils/renders/utils/MeshMaterialExtractor.h
/root/ACloudViewer/libs/PCLEngine/PclUtils/renders/utils/MeshMaterialExtractor.cpp