ACloudViewer: cloudViewer::GenericTriangle Class Reference
cloudViewer::GenericTriangle Class Reference abstract
A generic triangle interface.
#include <GenericTriangle.h>
Public Member Functions
virtual ~GenericTriangle ()=default
Default destructor.
virtual const CCVector3 * _getA () const =0
Returns the first vertex (A)
virtual const CCVector3 * _getB () const =0
Returns the second vertex (B)
virtual const CCVector3 * _getC () const =0
Returns the third vertex (C)
Detailed Description
A generic triangle interface.
Returns (temporary) references to each vertex.
Definition at line 18 of file GenericTriangle.h.
Constructor & Destructor Documentation
~GenericTriangle()
virtual cloudViewer::GenericTriangle::~GenericTriangle () virtual default
Default destructor.
Member Function Documentation
_getA()
virtual const CCVector3* cloudViewer::GenericTriangle::_getA () const pure virtual
Returns the first vertex (A)
Implemented in cloudViewer::SimpleTriangle, and cloudViewer::SimpleRefTriangle.
Referenced by qVoxFallProcess::Compute(), define_GenericTriangle(), and cloudViewer::Grid3D< Type >::intersectWith().
_getB()
virtual const CCVector3* cloudViewer::GenericTriangle::_getB () const pure virtual
Returns the second vertex (B)
Implemented in cloudViewer::SimpleTriangle, and cloudViewer::SimpleRefTriangle.
Referenced by qVoxFallProcess::Compute(), define_GenericTriangle(), and cloudViewer::Grid3D< Type >::intersectWith().
_getC()
virtual const CCVector3* cloudViewer::GenericTriangle::_getC () const pure virtual
Returns the third vertex (C)
Implemented in cloudViewer::SimpleTriangle, and cloudViewer::SimpleRefTriangle.
Referenced by qVoxFallProcess::Compute(), define_GenericTriangle(), and cloudViewer::Grid3D< Type >::intersectWith().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/GenericTriangle.h