ACloudViewer: cloudViewer::GenericProgressCallback Class Reference
cloudViewer::GenericProgressCallback Class Reference abstract
#include <GenericProgressCallback.h>
Public Member Functions
virtual ~GenericProgressCallback ()=default
Default destructor.
virtual void update (float percent)=0
Notifies the algorithm progress.
virtual void setMethodTitle (const char *methodTitle)=0
Notifies the algorithm title.
virtual void setInfo (const char *infoStr)=0
Notifies some information about the ongoing process.
virtual void start ()=0
virtual void stop ()=0
Notifies the fact that the process has ended.
virtual bool isCancelRequested ()=0
Checks if the process should be canceled.
virtual bool textCanBeEdited () const
Returns whether the dialog title and info can be updated or not.
Detailed Description
A generic progress indicator interface to notify algorithms progress to the client application
Definition at line 20 of file GenericProgressCallback.h.
Constructor & Destructor Documentation
~GenericProgressCallback()
virtual cloudViewer::GenericProgressCallback::~GenericProgressCallback () virtual default
Default destructor.
Member Function Documentation
isCancelRequested()
virtual bool cloudViewer::GenericProgressCallback::isCancelRequested () pure virtual
Checks if the process should be canceled.
This method is called by some process from time to time to know if it should halt before its normal ending. This is a way for the client application to cancel an ongoing process (but it won't work with all algorithms). Process results may be incomplete/void. The cancel requirement mechanism must be implemented (typically a simple "cancel()" method that will be called by the client application).
Implemented in ecvProgressDialog.
Referenced by define_GenericProgressCallback(), and FastMarchingForFacetExtraction::propagate().
setInfo()
virtual void cloudViewer::GenericProgressCallback::setInfo (const char * infoStr) pure virtual
Notifies some information about the ongoing process.
The notification is sent by the ongoing algorithm (on the library side).
Parameters
infoStr some textual information about the ongoing process
Implemented in ecvProgressDialog.
Referenced by qCanupoTools::ComputeCorePointsDescriptors(), qM3C2Normals::ComputeCorePointsNormals(), define_GenericProgressCallback(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), ccKdTreeForFacetExtraction::FuseCells(), FastMarchingForFacetExtraction::init(), masc::ContextBasedFeature::prepare(), masc::Tools::PrepareFeatures(), ecvProgressDialog::setInfo(), and qM3C2Normals::UpdateNormalOrientationsWithCloud().
setMethodTitle()
virtual void cloudViewer::GenericProgressCallback::setMethodTitle (const char * methodTitle) pure virtual
Notifies the algorithm title.
The notification is sent by the ongoing algorithm (on the library side).
Parameters
methodTitle the algorithm title
Implemented in ecvProgressDialog.
Referenced by qCanupoTools::ComputeCorePointsDescriptors(), qM3C2Normals::ComputeCorePointsNormals(), define_GenericProgressCallback(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), ccKdTreeForFacetExtraction::FuseCells(), FastMarchingForFacetExtraction::init(), masc::ContextBasedFeature::prepare(), masc::Tools::PrepareFeatures(), ecvProgressDialog::setMethodTitle(), and qM3C2Normals::UpdateNormalOrientationsWithCloud().
start()
virtual void cloudViewer::GenericProgressCallback::start () pure virtual
Notifies the fact that every information has been sent and that the process begins Once start() is called, the progress bar and other informations could be displayed (for example).
Implemented in ecvProgressDialog.
Referenced by qCanupoTools::ComputeCorePointsDescriptors(), qM3C2Normals::ComputeCorePointsNormals(), define_GenericProgressCallback(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), ccKdTreeForFacetExtraction::FuseCells(), FastMarchingForFacetExtraction::init(), masc::Tools::PrepareFeatures(), and qM3C2Normals::UpdateNormalOrientationsWithCloud().
stop()
virtual void cloudViewer::GenericProgressCallback::stop () pure virtual
Notifies the fact that the process has ended.
Once end() is called, the progress bar and other informations could be hidden (for example).
Implemented in ecvProgressDialog.
Referenced by qCanupoTools::ComputeCorePointsDescriptors(), qM3C2Normals::ComputeCorePointsNormals(), define_GenericProgressCallback(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), FastMarchingForFacetExtraction::init(), masc::ContextBasedFeature::prepare(), and qM3C2Normals::UpdateNormalOrientationsWithCloud().
textCanBeEdited()
virtual bool cloudViewer::GenericProgressCallback::textCanBeEdited () const inline virtual
Returns whether the dialog title and info can be updated or not.
Definition at line 70 of file GenericProgressCallback.h.
Referenced by qCanupoTools::ComputeCorePointsDescriptors(), qM3C2Normals::ComputeCorePointsNormals(), define_GenericProgressCallback(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), ccKdTreeForFacetExtraction::FuseCells(), FastMarchingForFacetExtraction::init(), and qM3C2Normals::UpdateNormalOrientationsWithCloud().
update()
virtual void cloudViewer::GenericProgressCallback::update (float percent) pure virtual
Notifies the algorithm progress.
The notification is sent by the running algorithm (on the library side). This virtual method shouldn't be called too often, as the real process behind it is unspecified and may be time consuming. Ideally it shouldn't be called more than a few hundreds time.
Parameters
percent current progress, between 0.0 and 100.0
Implemented in ecvProgressDialog.
Referenced by define_GenericProgressCallback(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), ccKdTreeForFacetExtraction::FuseCells(), FastMarchingForFacetExtraction::init(), and FastMarchingForFacetExtraction::step().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/GenericProgressCallback.h