ACloudViewer: Widgets::PenStyleBox Class Reference
Widgets::PenStyleBox Class Reference
#include <penstylebox.h>
Public Member Functions
PenStyleBox (QWidget *parent=0)
construct PenStyleBox.
void setStyle (const Qt::PenStyle &style)
set style.
Qt::PenStyle style () const
obtain selected style.
Static Public Member Functions
static int styleIndex (const Qt::PenStyle &style)
get the index of style.
static Qt::PenStyle penStyle (int index)
get style.
Detailed Description
Definition at line 16 of file penstylebox.h.
Constructor & Destructor Documentation
PenStyleBox()
Widgets::PenStyleBox::PenStyleBox (QWidget * parent = 0)
construct PenStyleBox.
Parameters
parent,window.
Definition at line 22 of file penstylebox.cpp.
Member Function Documentation
penStyle()
Qt::PenStyle Widgets::PenStyleBox::penStyle (int index) static
get style.
Parameters
index,the index of style.
Returns
style, default: SolidLine.
Definition at line 49 of file penstylebox.cpp.
setStyle()
void Widgets::PenStyleBox::setStyle (const Qt::PenStyle & style)
set style.
Parameters
style.
Definition at line 35 of file penstylebox.cpp.
References style().
style()
Qt::PenStyle Widgets::PenStyleBox::style () const
obtain selected style.
Returns
style, default: SolidLine.
Definition at line 60 of file penstylebox.cpp.
Referenced by setStyle(), and styleIndex().
styleIndex()
int Widgets::PenStyleBox::styleIndex (const Qt::PenStyle & style) static
get the index of style.
Parameters
style.
Returns
the index of style.
Definition at line 73 of file penstylebox.cpp.
References style().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/penstylebox.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/penstylebox.cpp