ACloudViewer: ecvShortcutDialog Class Reference
ecvShortcutDialog Class Reference final
#include <ecvShortcutDialog.h>
Public Member Functions
ecvShortcutDialog (const QList< QAction * > &actions, QWidget *parent=nullptr)
~ecvShortcutDialog () override
void restoreShortcutsFromQSettings () const
Detailed Description
Shortcut edit dialog
List shortcuts for known actions, and allows to edit them Saves to QSettings on each edit
Definition at line 37 of file ecvShortcutDialog.h.
Constructor & Destructor Documentation
ecvShortcutDialog()
ecvShortcutDialog::ecvShortcutDialog (const QList< QAction * > & actions, QWidget * parent = nullptr) explicit
Definition at line 182 of file ecvShortcutDialog.cpp.
References ACTION_NAME_COLUMN, getMenuPath(), and KEY_SEQUENCE_COLUMN.
~ecvShortcutDialog()
ecvShortcutDialog::~ecvShortcutDialog () override
Definition at line 274 of file ecvShortcutDialog.cpp.
Member Function Documentation
restoreShortcutsFromQSettings()
void ecvShortcutDialog::restoreShortcutsFromQSettings () const
Definition at line 279 of file ecvShortcutDialog.cpp.
References KEY_SEQUENCE_COLUMN, and ecvPS::Shortcuts().
Referenced by MainWindow::MainWindow().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvShortcutDialog.h
/root/ACloudViewer/app/ecvShortcutDialog.cpp