ACloudViewer: ColorScaleElementSlider Class Reference
ColorScaleElementSlider Class Reference
Color scale element as a widget.
#include <ecvColorScaleEditorWidget.h>
Public Member Functions
ColorScaleElementSlider (double relativePos=0.0, QColor color=Qt::black, QWidget *parent=nullptr, Qt::Orientation orientation=Qt::Horizontal)
Default constructor.
void setSelected (bool state)
Sets selection state.
bool isSelected () const
Returns selection state.
Public Member Functions inherited from ccColorScaleElement
ccColorScaleElement ()
Default constructor.
ccColorScaleElement (double relativePos, QColor color)
Constructor from a (relative) position and a color.
void setRelativePos (double pos)
Sets associated value (relative to scale boundaries)
double getRelativePos () const
Returns step position (relative to scale boundaries)
void setColor (QColor color)
Sets color.
const QColor & getColor () const
Returns color.
Static Public Member Functions
static bool IsSmaller (const ColorScaleElementSlider *e1, const ColorScaleElementSlider *e2)
Comparison operator between two (pointers on) color scale elements.
Static Public Member Functions inherited from ccColorScaleElement
static bool IsSmaller (const ccColorScaleElement &e1, const ccColorScaleElement &e2)
Comparison operator between two color scale elements.
Protected Member Functions
void paintEvent (QPaintEvent *e) override
Protected Attributes
bool m_selected
Selection state.
Qt::Orientation m_orientation
Widget orientation.
Protected Attributes inherited from ccColorScaleElement
double m_relativePos
Step (relative) position.
QColor m_color
Color.
Detailed Description
Color scale element as a widget.
Definition at line 23 of file ecvColorScaleEditorWidget.h.
Constructor & Destructor Documentation
ColorScaleElementSlider()
ColorScaleElementSlider::ColorScaleElementSlider (double relativePos = 0.0, QColor color = Qt::black, QWidget * parent = nullptr, Qt::Orientation orientation = Qt::Horizontal)
Default constructor.
Definition at line 29 of file ecvColorScaleEditorWidget.cpp.
References DEFAULT_SLIDER_SYMBOL_SIZE, and m_orientation.
Member Function Documentation
isSelected()
bool ColorScaleElementSlider::isSelected () const inline
Returns selection state.
Definition at line 38 of file ecvColorScaleEditorWidget.h.
Referenced by SlidersWidget::mouseDoubleClickEvent(), and SlidersWidget::mouseMoveEvent().
IsSmaller()
static bool ColorScaleElementSlider::IsSmaller (const ColorScaleElementSlider * e1, const ColorScaleElementSlider * e2) inline static
Comparison operator between two (pointers on) color scale elements.
Definition at line 41 of file ecvColorScaleEditorWidget.h.
References e2, and ccColorScaleElement::getRelativePos().
Referenced by ColorScaleElementSliders::sort().
paintEvent()
void ColorScaleElementSlider::paintEvent (QPaintEvent * e) override protected
Definition at line 46 of file ecvColorScaleEditorWidget.cpp.
References ecvColor::black(), DEFAULT_SLIDER_SYMBOL_SIZE, ccColorScaleElement::m_color, m_orientation, m_selected, and ecvColor::red().
setSelected()
void ColorScaleElementSlider::setSelected (bool state) inline
Sets selection state.
Definition at line 35 of file ecvColorScaleEditorWidget.h.
Member Data Documentation
m_orientation
Qt::Orientation ColorScaleElementSlider::m_orientation protected
Widget orientation.
Definition at line 54 of file ecvColorScaleEditorWidget.h.
Referenced by ColorScaleElementSlider(), and paintEvent().
m_selected
bool ColorScaleElementSlider::m_selected protected
Selection state.
Definition at line 51 of file ecvColorScaleEditorWidget.h.
Referenced by paintEvent().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVPluginAPI/include/ecvColorScaleEditorWidget.h
/root/ACloudViewer/libs/CVPluginAPI/src/ecvColorScaleEditorWidget.cpp