ACloudViewer: ccSubsamplingDlg Class Reference
ccSubsamplingDlg Class Reference
Subsampling cloud dialog.
#include <ecvSubsamplingDlg.h>
Public Types
enum CC_SUBSAMPLING_METHOD { RANDOM = 0 , SPACE = 1 , OCTREE = 2 }
Sub-sampling method.
Public Member Functions
ccSubsamplingDlg (unsigned maxPointCount, double maxCloudRadius, QWidget *parent=0)
Default constructor.
cloudViewer::ReferenceCloud * getSampledCloud (ccGenericPointCloud *cloud, cloudViewer::GenericProgressCallback *progressCb=0)
Returns subsampled version of a cloud according to current parameters.
void enableSFModulation (ScalarType sfMin, ScalarType sfMax)
Enables the SF modulation option (SPATIAL method)
Protected Slots
void sliderMoved (int sliderPos)
void samplingRateChanged (double value)
void changeSamplingMethod (int index)
Protected Member Functions
void updateLabels ()
Updates the dialog labels depending on the active mode.
Protected Attributes
unsigned m_maxPointCount
Max point count (for RANDOM method)
double m_maxRadius
Max radius (for SPACE method)
bool m_sfModEnabled
Scalar modulation.
ScalarType m_sfMin
Scalar modulation (min SF value)
ScalarType m_sfMax
Scalar modulation (max SF value)
Detailed Description
Subsampling cloud dialog.
Definition at line 23 of file ecvSubsamplingDlg.h.
Member Enumeration Documentation
CC_SUBSAMPLING_METHOD
enum ccSubsamplingDlg::CC_SUBSAMPLING_METHOD
Sub-sampling method.
Enumerator
RANDOM
SPACE
OCTREE
Definition at line 28 of file ecvSubsamplingDlg.h.
Constructor & Destructor Documentation
ccSubsamplingDlg()
ccSubsamplingDlg::ccSubsamplingDlg (unsigned maxPointCount, double maxCloudRadius, QWidget * parent = 0)
Default constructor.
Definition at line 25 of file ecvSubsamplingDlg.cpp.
References changeSamplingMethod(), samplingRateChanged(), and sliderMoved().
Member Function Documentation
changeSamplingMethod
void ccSubsamplingDlg::changeSamplingMethod (int index) protected slot
Definition at line 197 of file ecvSubsamplingDlg.cpp.
References m_maxPointCount, m_maxRadius, m_sfModEnabled, cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, OCTREE, RANDOM, sliderMoved(), SPACE, and updateLabels().
Referenced by ccSubsamplingDlg().
enableSFModulation()
void ccSubsamplingDlg::enableSFModulation (ScalarType sfMin, ScalarType sfMax)
Enables the SF modulation option (SPATIAL method)
Definition at line 243 of file ecvSubsamplingDlg.cpp.
References m_sfMax, m_sfMin, m_sfModEnabled, SPACE, cloudViewer::ScalarField::ValidValue(), and CVLog::Warning().
getSampledCloud()
cloudViewer::ReferenceCloud * ccSubsamplingDlg::getSampledCloud (ccGenericPointCloud * cloud, cloudViewer::GenericProgressCallback * progressCb = 0)
Returns subsampled version of a cloud according to current parameters.
Should be called only once the dialog has been validated.
Definition at line 56 of file ecvSubsamplingDlg.cpp.
References cloudViewer::CloudSamplingTools::SFModulationParams::a, cloudViewer::CloudSamplingTools::SFModulationParams::b, ccGenericPointCloud::computeOctree(), count, cloudViewer::CloudSamplingTools::SFModulationParams::enabled, ccObject::getName(), ccGenericPointCloud::getOctree(), cloudViewer::GreaterThanEpsilon(), m_sfMax, m_sfMin, OCTREE, octree, RANDOM, cloudViewer::CloudSamplingTools::resampleCloudSpatially(), cloudViewer::GenericCloud::size(), SPACE, cloudViewer::CloudSamplingTools::subsampleCloudRandomly(), cloudViewer::CloudSamplingTools::subsampleCloudWithOctreeAtLevel(), and CVLog::Warning().
samplingRateChanged
void ccSubsamplingDlg::samplingRateChanged (double value) protected slot
Definition at line 171 of file ecvSubsamplingDlg.cpp.
References m_sfModEnabled, SPACE, and SPACE_RANGE_EXPONENT.
Referenced by ccSubsamplingDlg().
sliderMoved
void ccSubsamplingDlg::sliderMoved (int sliderPos) protected slot
Definition at line 157 of file ecvSubsamplingDlg.cpp.
References SPACE, and SPACE_RANGE_EXPONENT.
Referenced by ccSubsamplingDlg(), and changeSamplingMethod().
updateLabels()
void ccSubsamplingDlg::updateLabels () protected
Updates the dialog labels depending on the active mode.
Definition at line 135 of file ecvSubsamplingDlg.cpp.
References OCTREE, RANDOM, and SPACE.
Referenced by changeSamplingMethod().
Member Data Documentation
m_maxPointCount
unsigned ccSubsamplingDlg::m_maxPointCount protected
Max point count (for RANDOM method)
Definition at line 61 of file ecvSubsamplingDlg.h.
Referenced by changeSamplingMethod().
m_maxRadius
double ccSubsamplingDlg::m_maxRadius protected
Max radius (for SPACE method)
Definition at line 64 of file ecvSubsamplingDlg.h.
Referenced by changeSamplingMethod().
m_sfMax
ScalarType ccSubsamplingDlg::m_sfMax protected
Scalar modulation (max SF value)
Definition at line 71 of file ecvSubsamplingDlg.h.
Referenced by enableSFModulation(), and getSampledCloud().
m_sfMin
ScalarType ccSubsamplingDlg::m_sfMin protected
Scalar modulation (min SF value)
Definition at line 69 of file ecvSubsamplingDlg.h.
Referenced by enableSFModulation(), and getSampledCloud().
m_sfModEnabled
bool ccSubsamplingDlg::m_sfModEnabled protected
Scalar modulation.
Definition at line 67 of file ecvSubsamplingDlg.h.
Referenced by changeSamplingMethod(), enableSFModulation(), and samplingRateChanged().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvSubsamplingDlg.h
/root/ACloudViewer/app/ecvSubsamplingDlg.cpp