ACloudViewer: cloudViewer::ErrorFunction Class Reference
cloudViewer::ErrorFunction Class Reference
A class to compute the Error function (erf)
#include <ErrorFunction.h>
Static Public Member Functions
static double erfc (double x)
Computes erfc(x)
static double erf (double x)
Computes erf(x)
Detailed Description
A class to compute the Error function (erf)
See for example http://mathworld.wolfram.com/Erf.html. Most of the code comes from "erf.cpp" by Steve Strand (29-Jan-04).
Definition at line 28 of file ErrorFunction.h.
Member Function Documentation
erf()
double ErrorFunction::erf (double x) static
Computes erf(x)
erf(x) = 2/sqrt(pi)*integral(exp(-t^2),t,0,x) = 2/sqrt(pi)*[x - x^3/3 + x^5/5*2! - x^7/7*3! + ...] = 1-erfc(x)
Parameters
x a real variable
Returns
erf(x)
Definition at line 22 of file ErrorFunction.cpp.
References abs(), and erfc().
Referenced by cloudViewer::NormalDistribution::computeP(), cloudViewer::NormalDistribution::computePfromZero(), and define_ErrorFunction().
erfc()
double ErrorFunction::erfc (double x) static
Computes erfc(x)
erfc(x) = 2/sqrt(pi)*integral(exp(-t^2),t,x,inf) = exp(-x^2)/sqrt(pi) * [1/x+ (1/2)/x+ (2/2)/x+ (3/2)/x+ (4/2)/x+ ...] = 1-erf(x) (expression inside [] is a continued fraction so '+' means add to denominator only).
Parameters
x a real variable
Returns
erfc(x)
Definition at line 49 of file ErrorFunction.cpp.
References abs(), cloudViewer::c_erfRelativeError, and one_sqrtpi.
Referenced by define_ErrorFunction(), and erf().
The documentation for this class was generated from the following files:
/root/ACloudViewer/core/include/ErrorFunction.h
/root/ACloudViewer/core/src/ErrorFunction.cpp