ACloudViewer: cloudViewer::visualization::VisualizerWithCustomAnimation Class Reference
cloudViewer::visualization::VisualizerWithCustomAnimation Class Reference
#include <VisualizerWithCustomAnimation.h>
Public Member Functions
VisualizerWithCustomAnimation ()
~VisualizerWithCustomAnimation () override
VisualizerWithCustomAnimation (const VisualizerWithCustomAnimation &)=delete
VisualizerWithCustomAnimation & operator= (const VisualizerWithCustomAnimation &)=delete
void PrintVisualizerHelp () override
void UpdateWindowTitle () override
void Play (bool recording=false, bool recording_depth=false, bool close_window_when_animation_ends=false)
void RegisterRecordingImageFormat (const std::string &basedir, const std::string &format, const std::string &trajectory)
void RegisterRecordingDepthFormat (const std::string &basedir, const std::string &format, const std::string &trajectory)
Public Member Functions inherited from cloudViewer::visualization::Visualizer
Visualizer ()
virtual ~Visualizer ()
Visualizer (Visualizer &&)=delete
Visualizer (const Visualizer &)=delete
Visualizer & operator= (const Visualizer &)=delete
bool CreateVisualizerWindow (const std::string &window_name="CloudViewer", const int width=640, const int height=480, const int left=50, const int top=50, const bool visible=true)
Function to create a window and initialize GLFW.
void DestroyVisualizerWindow ()
Function to destroy a window.
void RegisterAnimationCallback (std::function< bool(Visualizer *)> callback_func)
Function to register a callback function for animation.
void Run ()
Function to activate the window.
void Close ()
Function to to notify the window to be closed.
bool WaitEvents ()
Function to process the event queue and return if the window is closed.
bool PollEvents ()
virtual bool AddGeometry (std::shared_ptr< const ccHObject > geometry_ptr, bool reset_bounding_box=true)
Function to add geometry to the scene and create corresponding shaders.
virtual bool RemoveGeometry (std::shared_ptr< const ccHObject > geometry_ptr, bool reset_bounding_box=true)
Function to remove geometry from the scene.
virtual bool ClearGeometries ()
virtual bool UpdateGeometry (std::shared_ptr< const ccHObject > geometry_ptr=nullptr)
Function to update geometry.
virtual bool HasGeometry () const
virtual void UpdateRender ()
Function to inform render needed to be updated.
virtual void SetFullScreen (bool fullscreen)
Functions to change between fullscreen and windowed modes.
virtual void ToggleFullScreen ()
virtual bool IsFullScreen ()
virtual void BuildUtilities ()
ViewControl & GetViewControl ()
Function to retrieve the associated ViewControl.
RenderOption & GetRenderOption ()
Function to retrieve the associated RenderOption.
std::shared_ptr< geometry::Image > CaptureScreenFloatBuffer (bool do_render=true)
Function to capture screen and store RGB in a float buffer.
void CaptureScreenImage (const std::string &filename="", bool do_render=true)
Function to capture and save a screen image.
std::shared_ptr< geometry::Image > CaptureDepthFloatBuffer (bool do_render=true)
void CaptureDepthImage (const std::string &filename="", bool do_render=true, double depth_scale=1000.0)
void CaptureDepthPointCloud (const std::string &filename="", bool do_render=true, bool convert_to_world_coordinate=false)
Function to capture and save local point cloud.
void CaptureRenderOption (const std::string &filename="")
void ResetViewPoint (bool reset_bounding_box=false)
Function to reset view point.
const std::string & GetWindowName () const
Protected Member Functions
bool InitViewControl () override
Function to initialize ViewControl.
void MouseMoveCallback (GLFWwindow *window, double x, double y) override
void MouseScrollCallback (GLFWwindow *window, double x, double y) override
void MouseButtonCallback (GLFWwindow *window, int button, int action, int mods) override
void KeyPressCallback (GLFWwindow *window, int key, int scancode, int action, int mods) override
Protected Member Functions inherited from cloudViewer::visualization::Visualizer
virtual bool InitOpenGL ()
Function to initialize OpenGL.
virtual bool InitRenderOption ()
Function to initialize RenderOption.
virtual void Render (bool render_screen=false)
void CopyViewStatusToClipboard ()
void CopyViewStatusFromClipboard ()
virtual void WindowRefreshCallback (GLFWwindow *window)
virtual void WindowResizeCallback (GLFWwindow *window, int w, int h)
virtual void WindowCloseCallback (GLFWwindow *window)
Function to notify the window to be closed.
Protected Attributes
std::string recording_image_basedir_ = "image/"
std::string recording_image_filename_format_ = "image_{:06d}.png"
std::string recording_image_trajectory_filename_ = "image_trajectory.json"
std::string recording_depth_basedir_ = "depth/"
std::string recording_depth_filename_format_ = "depth_{:06d}.png"
std::string recording_depth_trajectory_filename_ = "depth_trajectory.json"
size_t recording_file_index_ = 0
Protected Attributes inherited from cloudViewer::visualization::Visualizer
GLFWwindow * window_ = nullptr
std::string window_name_ = "CloudViewer"
std::shared_ptr< GLFWContext > glfw_context_ = nullptr
Shared GLFW context.
Eigen::Vector2i saved_window_size_ = Eigen::Vector2i::Zero()
Eigen::Vector2i saved_window_pos_ = Eigen::Vector2i::Zero()
std::function< bool(Visualizer *)> animation_callback_func_ = nullptr
std::function< bool(Visualizer *)> animation_callback_func_in_loop_
MouseControl mouse_control_
bool is_redraw_required_ = true
bool is_initialized_ = false
GLuint vao_id_ = 0
GLuint render_fbo_ = 0
GLuint render_rgb_tex_ = 0
GLuint render_depth_stencil_rbo_ = 0
std::unique_ptr< ViewControl > view_control_ptr_
std::unique_ptr< RenderOption > render_option_ptr_
std::unordered_set< std::shared_ptr< const ccHObject > > geometry_ptrs_
std::unordered_set< std::shared_ptr< glsl::GeometryRenderer > > geometry_renderer_ptrs_
std::vector< std::shared_ptr< const ccHObject > > utility_ptrs_
std::vector< std::shared_ptr< glsl::GeometryRenderer > > utility_renderer_ptrs_
std::unordered_map< std::shared_ptr< glsl::GeometryRenderer >, RenderOption > utility_renderer_opts_
std::shared_ptr< ccMesh > coordinate_frame_mesh_ptr_
std::shared_ptr< glsl::CoordinateFrameRenderer > coordinate_frame_mesh_renderer_ptr_
Detailed Description
Definition at line 15 of file VisualizerWithCustomAnimation.h.
Constructor & Destructor Documentation
VisualizerWithCustomAnimation() [1/2]
cloudViewer::visualization::VisualizerWithCustomAnimation::VisualizerWithCustomAnimation ()
Definition at line 22 of file VisualizerWithCustomAnimation.cpp.
~VisualizerWithCustomAnimation()
cloudViewer::visualization::VisualizerWithCustomAnimation::~VisualizerWithCustomAnimation () override
Definition at line 24 of file VisualizerWithCustomAnimation.cpp.
VisualizerWithCustomAnimation() [2/2]
cloudViewer::visualization::VisualizerWithCustomAnimation::VisualizerWithCustomAnimation (const VisualizerWithCustomAnimation &) delete
Member Function Documentation
InitViewControl()
bool cloudViewer::visualization::VisualizerWithCustomAnimation::InitViewControl () override protected virtual
Function to initialize ViewControl.
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 151 of file VisualizerWithCustomAnimation.cpp.
References cloudViewer::visualization::Visualizer::ResetViewPoint(), and cloudViewer::visualization::Visualizer::view_control_ptr_.
KeyPressCallback()
void cloudViewer::visualization::VisualizerWithCustomAnimation::KeyPressCallback (GLFWwindow * window, int key, int scancode, int action, int mods) override protected virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 158 of file VisualizerWithCustomAnimation.cpp.
References cloudViewer::visualization::Visualizer::is_redraw_required_, cloudViewer::visualization::Visualizer::KeyPressCallback(), LogDebug, Play(), UpdateWindowTitle(), and cloudViewer::visualization::Visualizer::view_control_ptr_.
MouseButtonCallback()
void cloudViewer::visualization::VisualizerWithCustomAnimation::MouseButtonCallback (GLFWwindow * window, int button, int action, int mods) override protected virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 286 of file VisualizerWithCustomAnimation.cpp.
References cloudViewer::visualization::Visualizer::MouseButtonCallback(), and cloudViewer::visualization::Visualizer::view_control_ptr_.
MouseMoveCallback()
void cloudViewer::visualization::VisualizerWithCustomAnimation::MouseMoveCallback (GLFWwindow * window, double x, double y) override protected virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 258 of file VisualizerWithCustomAnimation.cpp.
References cloudViewer::visualization::Visualizer::MouseMoveCallback(), cloudViewer::visualization::Visualizer::view_control_ptr_, x, and y.
MouseScrollCallback()
void cloudViewer::visualization::VisualizerWithCustomAnimation::MouseScrollCallback (GLFWwindow * window, double x, double y) override protected virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 269 of file VisualizerWithCustomAnimation.cpp.
References cloudViewer::visualization::Visualizer::is_redraw_required_, cloudViewer::visualization::Visualizer::MouseScrollCallback(), UpdateWindowTitle(), cloudViewer::visualization::Visualizer::view_control_ptr_, x, and y.
operator=()
VisualizerWithCustomAnimation& cloudViewer::visualization::VisualizerWithCustomAnimation::operator= (const VisualizerWithCustomAnimation &) delete
Play()
void cloudViewer::visualization::VisualizerWithCustomAnimation::Play (bool recording = false, bool recording_depth = false, bool close_window_when_animation_ends = false)
Definition at line 67 of file VisualizerWithCustomAnimation.cpp.
References cloudViewer::visualization::Visualizer::CaptureDepthImage(), cloudViewer::visualization::Visualizer::CaptureScreenImage(), cloudViewer::visualization::Visualizer::Close(), format, cloudViewer::visualization::Visualizer::is_redraw_required_, LogWarning, cloudViewer::utility::filesystem::MakeDirectoryHierarchy(), progress_bar, recording_depth_basedir_, recording_depth_filename_format_, recording_depth_trajectory_filename_, recording_file_index_, recording_image_basedir_, recording_image_filename_format_, recording_image_trajectory_filename_, cloudViewer::visualization::Visualizer::RegisterAnimationCallback(), UpdateWindowTitle(), cloudViewer::visualization::Visualizer::view_control_ptr_, and cloudViewer::io::WriteIJsonConvertible().
Referenced by KeyPressCallback(), and main().
PrintVisualizerHelp()
void cloudViewer::visualization::VisualizerWithCustomAnimation::PrintVisualizerHelp () override virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 26 of file VisualizerWithCustomAnimation.cpp.
References LogInfo, and cloudViewer::visualization::Visualizer::PrintVisualizerHelp().
RegisterRecordingDepthFormat()
void cloudViewer::visualization::VisualizerWithCustomAnimation::RegisterRecordingDepthFormat (const std::string & basedir, const std::string & format, const std::string & trajectory) inline
Definition at line 37 of file VisualizerWithCustomAnimation.h.
References format, recording_depth_basedir_, recording_depth_filename_format_, and recording_depth_trajectory_filename_.
RegisterRecordingImageFormat()
void cloudViewer::visualization::VisualizerWithCustomAnimation::RegisterRecordingImageFormat (const std::string & basedir, const std::string & format, const std::string & trajectory) inline
Definition at line 30 of file VisualizerWithCustomAnimation.h.
References format, recording_image_basedir_, recording_image_filename_format_, and recording_image_trajectory_filename_.
UpdateWindowTitle()
void cloudViewer::visualization::VisualizerWithCustomAnimation::UpdateWindowTitle () override virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 57 of file VisualizerWithCustomAnimation.cpp.
References cloudViewer::visualization::Visualizer::view_control_ptr_, cloudViewer::visualization::Visualizer::window_, and cloudViewer::visualization::Visualizer::window_name_.
Referenced by cloudViewer::visualization::DrawGeometriesWithCustomAnimation(), KeyPressCallback(), MouseScrollCallback(), and Play().
Member Data Documentation
recording_depth_basedir_
std::string cloudViewer::visualization::VisualizerWithCustomAnimation::recording_depth_basedir_ = "depth/" protected
Definition at line 63 of file VisualizerWithCustomAnimation.h.
Referenced by Play(), and RegisterRecordingDepthFormat().
recording_depth_filename_format_
std::string cloudViewer::visualization::VisualizerWithCustomAnimation::recording_depth_filename_format_ = "depth_{:06d}.png" protected
Definition at line 64 of file VisualizerWithCustomAnimation.h.
Referenced by Play(), and RegisterRecordingDepthFormat().
recording_depth_trajectory_filename_
std::string cloudViewer::visualization::VisualizerWithCustomAnimation::recording_depth_trajectory_filename_ = "depth_trajectory.json" protected
Definition at line 65 of file VisualizerWithCustomAnimation.h.
Referenced by Play(), and RegisterRecordingDepthFormat().
recording_file_index_
size_t cloudViewer::visualization::VisualizerWithCustomAnimation::recording_file_index_ = 0 protected
Definition at line 66 of file VisualizerWithCustomAnimation.h.
Referenced by Play().
recording_image_basedir_
std::string cloudViewer::visualization::VisualizerWithCustomAnimation::recording_image_basedir_ = "image/" protected
Definition at line 60 of file VisualizerWithCustomAnimation.h.
Referenced by Play(), and RegisterRecordingImageFormat().
recording_image_filename_format_
std::string cloudViewer::visualization::VisualizerWithCustomAnimation::recording_image_filename_format_ = "image_{:06d}.png" protected
Definition at line 61 of file VisualizerWithCustomAnimation.h.
Referenced by Play(), and RegisterRecordingImageFormat().
recording_image_trajectory_filename_
std::string cloudViewer::visualization::VisualizerWithCustomAnimation::recording_image_trajectory_filename_ = "image_trajectory.json" protected
Definition at line 62 of file VisualizerWithCustomAnimation.h.
Referenced by Play(), and RegisterRecordingImageFormat().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/VisualizerWithCustomAnimation.h
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/VisualizerWithCustomAnimation.cpp