ACloudViewer: ccOctree Class Reference
ccOctree Class Reference
Octree structure.
#include <ecvOctree.h>
Classes
struct BestRadiusParams
Parameters for the GuessBestRadius method.
Public Types
enum DisplayMode { WIRE = 0 , MEAN_POINTS , MEAN_CUBES = 2 }
Octree displaying methods.
typedef QSharedPointer< ccOctree > Shared
Shared pointer.
Public Types inherited from cloudViewer::DgmOctree
enum RayCastProcess { RC_NEAREST_POINT , RC_CLOSE_POINTS }
Ray casting processes.
using CellCode = unsigned
Type of the code of an octree cell.
using cellCodesContainer = std::vector< CellCode >
Octree cell codes container.
using cellIndexesContainer = std::vector< unsigned int >
Octree cell indexes container.
using NeighboursSet = std::vector< PointDescriptor >
A set of neighbours.
using NeighbourCellsSet = std::vector< CellDescriptor >
A set of neighbour cells descriptors.
using cellsContainer = std::vector< IndexAndCode >
Container of 'IndexAndCode' structures.
using octreeCellFunc = bool(*)(const octreeCell &, void **, NormalizedProgress *)
Signals
void updated ()
Signal sent when the octree organization is modified (cleared, etc.)
Public Member Functions
ccOctree (ccGenericPointCloud *cloud)
Default constructor.
virtual ~ccOctree ()
Destructor.
void multiplyBoundingBox (const PointCoordinateType multFactor)
Multiplies the bounding-box of the octree.
void translateBoundingBox (const CCVector3 &T)
Translates the bounding-box of the octree.
ccBBox getSquareBB () const
Returns the octree (square) bounding-box.
ccBBox getPointsBB () const
Returns the points bounding-box.
virtual void clear () override
Clears the octree.
int getDisplayedLevel () const
Returns the currently displayed octree level.
void setDisplayedLevel (int level)
Sets the currently displayed octree level.
bool isVisible () const
Returns whether octree is visible or not.
void setVisible (bool state)
Sets octree visibility.
DisplayMode getDisplayMode () const
Returns the currently display mode.
void setDisplayMode (DisplayMode mode)
Sets the currently display mode.
void draw (CC_DRAW_CONTEXT &context)
Draws the octree.
bool intersectWithFrustum (ccCameraSensor *sensor, std::vector< unsigned > &inCameraFrustum)
Intersects octree with a camera sensor.
bool pointPicking (const CCVector2d &clickPos, const ccGLCameraParameters &camera, PointDescriptor &output, double pickWidth_pix=3.0) const
Octree-driven point picking algorithm.
Public Member Functions inherited from cloudViewer::DgmOctree
DgmOctree (GenericIndexedCloudPersist *cloud)
DgmOctree constructor.
~DgmOctree () override=default
DgmOctree destructor.
int build (GenericProgressCallback *progressCb=nullptr)
Builds the structure.
int build (const CCVector3 &octreeMin, const CCVector3 &octreeMax, const CCVector3 *pointsMinFilter=nullptr, const CCVector3 *pointsMaxFilter=nullptr, GenericProgressCallback *progressCb=nullptr)
Builds the structure with constraints.
unsigned getNumberOfProjectedPoints () const
Returns the number of points projected into the octree.
const CCVector3 & getOctreeMins () const
Returns the lower boundaries of the octree.
const CCVector3 & getOctreeMaxs () const
Returns the higher boundaries of the octree.
void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax) const
Returns the octree bounding box.
const int * getMinFillIndexes (unsigned char level) const
const int * getMaxFillIndexes (unsigned char level) const
const PointCoordinateType & getCellSize (unsigned char level) const
Returns the octree cells length for a given level of subdivision.
void getCellDistanceFromBorders (const Tuple3i &cellPos, unsigned char level, int *cellDists) const
void getCellDistanceFromBorders (const Tuple3i &cellPos, unsigned char level, int neighbourhoodLength, int *cellDists) const
bool getPointsInCellByCellIndex (ReferenceCloud *cloud, unsigned cellIndex, unsigned char level, bool clearOutputCloud=true) const
Returns the points lying in a specific cell.
bool getPointsInCell (CellCode cellCode, unsigned char level, ReferenceCloud *subset, bool isCodeTruncated=false, bool clearOutputCloud=true) const
Returns the points lying in a specific cell.
ReferenceCloud * getPointsInCellsWithSortedCellCodes (cellCodesContainer &cellCodes, unsigned char level, ReferenceCloud *subset, bool areCodesTruncated=false) const
Returns the points lying in multiple cells.
unsigned findPointNeighbourhood (const CCVector3 *_queryPoint, ReferenceCloud *Yk, unsigned maxNumberOfNeighbors, unsigned char level, double &maxSquareDist, double maxSearchDist=0, int *finalNeighbourhoodSize=nullptr) const
Finds the nearest neighbours around a query point.
double findTheNearestNeighborStartingFromCell (NearestNeighboursSearchStruct &nNSS) const
unsigned findNearestNeighborsStartingFromCell (NearestNeighboursSearchStruct &nNSS, bool getOnlyPointsWithValidScalar=false) const
int findNeighborsInASphereStartingFromCell (NearestNeighboursSearchStruct &nNSS, double radius, bool sortValues=true) const
Advanced form of the nearest neighbours search algorithm (in a sphere)
int getPointsInSphericalNeighbourhood (const CCVector3 &sphereCenter, PointCoordinateType radius, NeighboursSet &neighbours, unsigned char level) const
Returns the points falling inside a sphere.
std::size_t getPointsInCylindricalNeighbourhood (CylindricalNeighbourhood &params) const
Returns the points falling inside a cylinder.
std::size_t getPointsInCylindricalNeighbourhoodProgressive (ProgressiveCylindricalNeighbourhood &params) const
Same as getPointsInCylindricalNeighbourhood with progressive approach.
std::size_t getPointsInBoxNeighbourhood (BoxNeighbourhood &params) const
Returns the points falling inside a box.
void getTheCellPosWhichIncludesThePoint (const CCVector3 *thePoint, Tuple3i &cellPos) const
void getTheCellPosWhichIncludesThePoint (const CCVector3 *thePoint, Tuple3i &cellPos, unsigned char level) const
void getTheCellPosWhichIncludesThePoint (const CCVector3 *thePoint, Tuple3i &cellPos, unsigned char level, bool &inBounds) const
void getCellPos (CellCode code, unsigned char level, Tuple3i &cellPos, bool isCodeTruncated) const
void computeCellCenter (CellCode code, unsigned char level, CCVector3 &center, bool isCodeTruncated=false) const
void computeCellCenter (const Tuple3i &cellPos, unsigned char level, CCVector3 &center) const
void computeCellCenter (const Tuple3s &cellPos, unsigned char level, CCVector3 &center) const
Short version of computeCellCenter.
void computeCellLimits (CellCode code, unsigned char level, CCVector3 &cellMin, CCVector3 &cellMax, bool isCodeTruncated=false) const
Returns the spatial limits of a given cell.
unsigned char findBestLevelForAGivenNeighbourhoodSizeExtraction (PointCoordinateType radius) const
unsigned char findBestLevelForComparisonWithOctree (const DgmOctree *theOtherOctree) const
unsigned char findBestLevelForAGivenPopulationPerCell (unsigned indicativeNumberOfPointsPerCell) const
unsigned char findBestLevelForAGivenCellNumber (unsigned indicativeNumberOfCells) const
const CellCode & getCellCode (unsigned index) const
Returns the ith cell code.
bool getCellCodes (unsigned char level, cellCodesContainer &vec, bool truncatedCodes=false) const
bool getCellIndexes (unsigned char level, cellIndexesContainer &vec) const
bool getCellCodesAndIndexes (unsigned char level, cellsContainer &vec, bool truncatedCodes=false) const
void diff (const cellCodesContainer &codesA, const cellCodesContainer &codesB, cellCodesContainer &diffA, cellCodesContainer &diffB) const
bool diff (unsigned char octreeLevel, const cellsContainer &codesA, const cellsContainer &codesB, int &diffA, int &diffB, int &cellsA, int &cellsB) const
const unsigned & getCellNumber (unsigned char level) const
Returns the number of cells for a given level of subdivision.
double computeMeanOctreeDensity (unsigned char level) const
int extractCCs (const cellCodesContainer &cellCodes, unsigned char level, bool sixConnexity, GenericProgressCallback *progressCb=nullptr) const
int extractCCs (unsigned char level, bool sixConnexity, GenericProgressCallback *progressCb=nullptr) const
unsigned executeFunctionForAllCellsStartingAtLevel (unsigned char startingLevel, octreeCellFunc func, void **additionalParameters, unsigned minNumberOfPointsPerCell, unsigned maxNumberOfPointsPerCell, bool multiThread=true, GenericProgressCallback *progressCb=nullptr, const char *functionTitle=nullptr, int maxThreadCount=0)
unsigned executeFunctionForAllCellsAtLevel (unsigned char level, octreeCellFunc func, void **additionalParameters, bool multiThread=false, GenericProgressCallback *progressCb=nullptr, const char *functionTitle=nullptr, int maxThreadCount=0)
bool rayCast (const CCVector3 &rayAxis, const CCVector3 &rayOrigin, double maxRadiusOrFov, bool isFOV, RayCastProcess process, std::vector< PointDescriptor > &output) const
Ray casting algorithm.
GenericIndexedCloudPersist * associatedCloud () const
Returns the associated cloud.
const cellsContainer & pointsAndTheirCellCodes () const
Returns the octree 'structure'.
Public Member Functions inherited from cloudViewer::GenericOctree
virtual ~GenericOctree ()=default
Default destructor.
Static Public Member Functions
static void ComputeAverageColor (cloudViewer::ReferenceCloud *subset, ccGenericPointCloud *sourceCloud, ColorCompType meanCol[])
Computes the average color of a set of points.
static CCVector3 ComputeAverageNorm (cloudViewer::ReferenceCloud *subset, ccGenericPointCloud *sourceCloud)
Computes the average normal of a set of points.
static PointCoordinateType GuessNaiveRadius (ccGenericPointCloud *cloud)
Tries to guess a very naive 'local radius' for octree-based computation.
static PointCoordinateType GuessBestRadius (ccGenericPointCloud *cloud, const BestRadiusParams &params, cloudViewer::DgmOctree *cloudOctree=nullptr, cloudViewer::GenericProgressCallback *progressCb=nullptr)
Tries to guess the best 'local radius' for octree-based computation.
static PointCoordinateType GuessBestRadiusAutoComputeOctree (ccGenericPointCloud *cloud, const BestRadiusParams &params, QWidget *parentWidget=nullptr)
Static Public Member Functions inherited from cloudViewer::DgmOctree
static unsigned char GET_BIT_SHIFT (unsigned char level)
Returns the binary shift for a given level of subdivision.
static int OCTREE_LENGTH (int level)
static CellCode GenerateTruncatedCellCode (const Tuple3i &cellPos, unsigned char level)
static CellCode GenerateTruncatedCellCode (const Tuple3s &pos, unsigned char level)
Short version of GenerateTruncatedCellCode.
static PointCoordinateType ComputeMinDistanceToCellBorder (const CCVector3 &queryPoint, PointCoordinateType cs, const CCVector3 &cellCenter)
static bool MultiThreadSupport ()
Static Protected Member Functions
static bool DrawCellAsABox (const cloudViewer::DgmOctree::octreeCell &cell, void **additionalParameters, cloudViewer::NormalizedProgress *nProgress=0)
static bool DrawCellAsAPoint (const cloudViewer::DgmOctree::octreeCell &cell, void **additionalParameters, cloudViewer::NormalizedProgress *nProgress=0)
static bool DrawCellAsAPrimitive (const cloudViewer::DgmOctree::octreeCell &cell, void **additionalParameters, cloudViewer::NormalizedProgress *nProgress=0)
Protected Attributes
ccGenericPointCloud * m_theAssociatedCloudAsGPC
Associated cloud (as a ccGenericPointCloud)
int m_displayedLevel
Displayed level.
DisplayMode m_displayMode
Display mode.
ccOctreeFrustumIntersector * m_frustumIntersector
For frustum intersection.
bool m_visible
For Octree Display.
Protected Attributes inherited from cloudViewer::DgmOctree
cellsContainer m_thePointsAndTheirCellCodes
The coded octree structure.
GenericIndexedCloudPersist * m_theAssociatedCloud
Associated cloud.
unsigned m_numberOfProjectedPoints
Number of points projected in the octree.
unsigned m_nearestPow2
CCVector3 m_dimMin
Min coordinates of the octree bounding-box.
CCVector3 m_dimMax
Max coordinates of the octree bounding-box.
CCVector3 m_pointsMin
CCVector3 m_pointsMax
PointCoordinateType m_cellSize [MAX_OCTREE_LEVEL+2]
Cell dimensions for all subdivision levels.
int m_fillIndexes [(MAX_OCTREE_LEVEL+1) *6]
unsigned m_cellCount [MAX_OCTREE_LEVEL+1]
Number of cells per level of subdivision.
unsigned m_maxCellPopulation [MAX_OCTREE_LEVEL+1]
Max cell population per level of subdivision.
double m_averageCellPopulation [MAX_OCTREE_LEVEL+1]
Average cell population per level of subdivision.
double m_stdDevCellPopulation [MAX_OCTREE_LEVEL+1]
Std. dev. of cell population per level of subdivision.
Additional Inherited Members
Static Public Attributes inherited from cloudViewer::DgmOctree
static const int MAX_OCTREE_LEVEL = 10
Max octree subdivision level.
static const int MAX_OCTREE_LENGTH = (1 << MAX_OCTREE_LEVEL)
Max octree length at last level of subdivision (number of cells)
static const CellCode INVALID_CELL_CODE = (~static_cast<CellCode>(0))
Invalid cell code.
Protected Member Functions inherited from cloudViewer::DgmOctree
int genericBuild (GenericProgressCallback *progressCb=nullptr)
Generic method to build the octree structure.
void updateMinAndMaxTables ()
Updates the tables containing octree limits and boundaries.
void updateCellSizeTable ()
void updateCellCountTable ()
void computeCellsStatistics (unsigned char level)
Computes statistics about cells for a given level of subdivision.
void getNeighborCellsAround (const Tuple3i &cellPos, cellIndexesContainer &neighborCellsIndexes, int neighbourhoodLength, unsigned char level) const
void getPointsInNeighbourCellsAround (NearestNeighboursSearchStruct &nNSS, int neighbourhoodLength, bool getOnlyPointsWithValidScalar=false) const
Gets point in the neighbourhing cells of a specific cell.
unsigned getCellIndex (CellCode truncatedCellCode, unsigned char bitDec) const
Returns the index of a given cell represented by its code.
unsigned getCellIndex (CellCode truncatedCellCode, unsigned char bitDec, unsigned begin, unsigned end) const
Returns the index of a given cell represented by its code.
Detailed Description
Octree structure.
Extends the cloudViewer::DgmOctree class.
Definition at line 27 of file ecvOctree.h.
Member Typedef Documentation
Shared
typedef QSharedPointer<ccOctree> ccOctree::Shared
Shared pointer.
Definition at line 32 of file ecvOctree.h.
Member Enumeration Documentation
DisplayMode
enum ccOctree::DisplayMode
Octree displaying methods.
Enumerator
WIRE
The octree is displayed as wired boxes (one box per cell)
MEAN_POINTS
The octree is displayed as points (one point per cell = the center of gravity of the points lying in it)
MEAN_CUBES
The octree is displayed as plain 3D cubes (one cube per cell)
Definition at line 77 of file ecvOctree.h.
Constructor & Destructor Documentation
ccOctree()
ccOctree::ccOctree (ccGenericPointCloud * cloud) explicit
Default constructor.
Parameters
cloud a point cloud
Definition at line 23 of file ecvOctree.cpp.
~ccOctree()
ccOctree::~ccOctree () virtual
Destructor.
Definition at line 31 of file ecvOctree.cpp.
References m_frustumIntersector.
Member Function Documentation
clear()
void ccOctree::clear () override virtual
Clears the octree.
Reimplemented from cloudViewer::DgmOctree.
Definition at line 88 of file ecvOctree.cpp.
References updated().
ComputeAverageColor()
void ccOctree::ComputeAverageColor (cloudViewer::ReferenceCloud * subset, ccGenericPointCloud * sourceCloud, ColorCompType meanCol[]) static
Computes the average color of a set of points.
Definition at line 274 of file ecvOctree.cpp.
References cloudViewer::ReferenceCloud::getAssociatedCloud(), ccDrawableObject::hasColors(), cloudViewer::ReferenceCloud::size(), and sourceCloud.
Referenced by DrawCellAsAPoint(), and DrawCellAsAPrimitive().
ComputeAverageNorm()
CCVector3 ccOctree::ComputeAverageNorm (cloudViewer::ReferenceCloud * subset, ccGenericPointCloud * sourceCloud) static
Computes the average normal of a set of points.
Definition at line 299 of file ecvOctree.cpp.
References cloudViewer::ReferenceCloud::getAssociatedCloud(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), ccGenericPointCloud::getPointNormal(), ccDrawableObject::hasNormals(), Vector3Tpl< Type >::normalize(), cloudViewer::ReferenceCloud::size(), and sourceCloud.
Referenced by qFacets::createFacets(), DrawCellAsAPoint(), and DrawCellAsAPrimitive().
draw()
void ccOctree::draw (CC_DRAW_CONTEXT & context)
Draws the octree.
Definition at line 119 of file ecvOctree.cpp.
References DrawCellAsABox(), cloudViewer::DgmOctree::executeFunctionForAllCellsAtLevel(), ecvDisplayTools::GetCurrentScreen(), ccDrawableObject::getDrawingParameters(), m_displayedLevel, m_displayMode, m_frustumIntersector, m_theAssociatedCloudAsGPC, cloudViewer::DgmOctree::m_thePointsAndTheirCellCodes, m_visible, and WIRE.
DrawCellAsABox()
bool ccOctree::DrawCellAsABox (const cloudViewer::DgmOctree::octreeCell & cell, void ** additionalParameters, cloudViewer::NormalizedProgress * nProgress = 0) static protected
Definition at line 141 of file ecvOctree.cpp.
References ecvColor::blue(), ccOctreeFrustumIntersector::CELL_INSIDE_FRUSTUM, ccOctreeFrustumIntersector::CELL_OUTSIDE_FRUSTUM, cloudViewer::DgmOctree::computeCellLimits(), context, ecvDisplayTools::DrawBBox(), ECV_SHAPE, ECV_WIREFRAME_MODE, ecvColor::green(), cloudViewer::DgmOctree::octreeCell::level, ecvColor::magenta(), cloudViewer::DgmOctree::octreeCell::parentOctree, ccOctreeFrustumIntersector::positionFromFrustum(), ecvDisplayTools::RemoveEntities(), and cloudViewer::DgmOctree::octreeCell::truncatedCode.
Referenced by draw().
DrawCellAsAPoint()
bool ccOctree::DrawCellAsAPoint (const cloudViewer::DgmOctree::octreeCell & cell, void ** additionalParameters, cloudViewer::NormalizedProgress * nProgress = 0) static protected
Definition at line 185 of file ecvOctree.cpp.
References ComputeAverageColor(), ComputeAverageNorm(), cloudViewer::ScalarFieldTools::computeMeanScalarValue(), cloudViewer::Neighbourhood::getGravityCenter(), ccGenericPointCloud::getScalarValueColor(), cloudViewer::DgmOctree::octreeCell::points, glDrawParams::showColors, glDrawParams::showNorms, and glDrawParams::showSF.
DrawCellAsAPrimitive()
bool ccOctree::DrawCellAsAPrimitive (const cloudViewer::DgmOctree::octreeCell & cell, void ** additionalParameters, cloudViewer::NormalizedProgress * nProgress = 0) static protected
Definition at line 221 of file ecvOctree.cpp.
References ComputeAverageColor(), ComputeAverageNorm(), cloudViewer::DgmOctree::computeCellCenter(), cloudViewer::ScalarFieldTools::computeMeanScalarValue(), context, ccHObject::draw(), ccNormalVectors::GetNormIndex(), ccGenericPointCloud::getScalarValueColor(), ccMesh::getTriNormsTable(), cloudViewer::DgmOctree::octreeCell::level, cloudViewer::DgmOctree::octreeCell::parentOctree, cloudViewer::DgmOctree::octreeCell::points, ecvColor::RgbTpl< Type >::rgb, rgb, ccGenericPrimitive::setColor(), ccArray< Type, N, ComponentType >::setValue(), glDrawParams::showColors, glDrawParams::showNorms, glDrawParams::showSF, cloudViewer::DgmOctree::octreeCell::truncatedCode, and Tuple3Tpl< Type >::u.
getDisplayedLevel()
int ccOctree::getDisplayedLevel () const inline
Returns the currently displayed octree level.
Definition at line 67 of file ecvOctree.h.
Referenced by ccPropertiesTreeDelegate::fillWithPointOctree().
getDisplayMode()
DisplayMode ccOctree::getDisplayMode () const inline
Returns the currently display mode.
Definition at line 87 of file ecvOctree.h.
getPointsBB()
ccBBox ccOctree::getPointsBB () const
Returns the points bounding-box.
Definition at line 97 of file ecvOctree.cpp.
References cloudViewer::DgmOctree::m_pointsMax, and cloudViewer::DgmOctree::m_pointsMin.
getSquareBB()
ccBBox ccOctree::getSquareBB () const
Returns the octree (square) bounding-box.
Definition at line 95 of file ecvOctree.cpp.
References cloudViewer::DgmOctree::m_dimMax, and cloudViewer::DgmOctree::m_dimMin.
GuessBestRadius()
PointCoordinateType ccOctree::GuessBestRadius (ccGenericPointCloud * cloud, const BestRadiusParams & params, cloudViewer::DgmOctree * cloudOctree = nullptr, cloudViewer::GenericProgressCallback * progressCb = nullptr) static
Tries to guess the best 'local radius' for octree-based computation.
The ideal radius is determined by randomly sampling up to 200 points and looking at their neighborhood.
Parameters
cloud point cloud on which to process the normals.
params parameters
cloudOctree input cloud octree (optional)
progressCb progress notification (optional)
Returns
the best radius (strictly positive value) or 0 if an error occurred
Definition at line 566 of file ecvOctree.cpp.
References ccOctree::BestRadiusParams::aimedPopulationPerCell, ccOctree::BestRadiusParams::aimedPopulationRange, cloudViewer::DgmOctree::build(), cloudViewer::DgmOctree::findBestLevelForAGivenNeighbourhoodSizeExtraction(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::DgmOctree::getPointsInSphericalNeighbourhood(), GuessNaiveRadius(), ccOctree::BestRadiusParams::minAboveMinRatio, ccOctree::BestRadiusParams::minCellPopulation, octree, octreeLevel, CVLog::Print(), cloudViewer::GenericCloud::size(), size, and CVLog::Warning().
Referenced by GuessBestRadiusAutoComputeOctree().
GuessBestRadiusAutoComputeOctree()
PointCoordinateType ccOctree::GuessBestRadiusAutoComputeOctree (ccGenericPointCloud * cloud, const BestRadiusParams & params, QWidget * parentWidget = nullptr) static
Tries to guess the best 'local radius' for octree-based computation (auto-computes the octree if necessary) The ideal radius is determined by randomly sampling up to 200 points and looking at their neighborhood.
Parameters
cloud point cloud on which to process the normals.
params parameters
parentWidget parent widget (for the progress dialog, if any has to be shown)
Returns
the best radius (strictly positive value) or 0 if an error occurred
Definition at line 545 of file ecvOctree.cpp.
References ccGenericPointCloud::computeOctree(), CVLog::Error(), ccObject::getName(), ccGenericPointCloud::getOctree(), and GuessBestRadius().
Referenced by FastGlobalRegistrationDialog::autoEstimateRadius().
GuessNaiveRadius()
PointCoordinateType ccOctree::GuessNaiveRadius (ccGenericPointCloud * cloud) static
Tries to guess a very naive 'local radius' for octree-based computation.
Parameters
cloud point cloud on which to process the normals.
Returns
naive radius (one percent of the cloud largest dimension by default, unless the cloud have very few points)
Definition at line 533 of file ecvOctree.cpp.
References cloudViewer::BoundingBoxTpl< T >::getMaxBoxDim(), ccGenericPointCloud::getOwnBB(), and cloudViewer::GenericCloud::size().
Referenced by FastGlobalRegistrationDialog::FastGlobalRegistrationDialog(), and GuessBestRadius().
intersectWithFrustum()
bool ccOctree::intersectWithFrustum (ccCameraSensor * sensor, std::vector< unsigned > & inCameraFrustum)
Intersects octree with a camera sensor.
Definition at line 38 of file ecvOctree.cpp.
References ccOctreeFrustumIntersector::build(), ccOctreeFrustumIntersector::computeFrustumIntersectionWithOctree(), ccCameraSensor::computeGlobalPlaneCoefficients(), ccCameraSensor::isGlobalCoordInFrustum(), m_frustumIntersector, and CVLog::Warning().
isVisible()
bool ccOctree::isVisible () const inline
Returns whether octree is visible or not.
Definition at line 72 of file ecvOctree.h.
multiplyBoundingBox()
void ccOctree::multiplyBoundingBox (const PointCoordinateType multFactor)
Multiplies the bounding-box of the octree.
If the cloud coordinates are simply multiplied by the same factor, there is no use in recomputing the octree structure. It's sufficient to update its bounding-box.
Parameters
multFactor multiplication factor
Definition at line 101 of file ecvOctree.cpp.
References cloudViewer::DgmOctree::m_cellSize, cloudViewer::DgmOctree::m_dimMax, cloudViewer::DgmOctree::m_dimMin, cloudViewer::DgmOctree::m_pointsMax, cloudViewer::DgmOctree::m_pointsMin, and cloudViewer::DgmOctree::MAX_OCTREE_LEVEL.
pointPicking()
bool ccOctree::pointPicking (const CCVector2d & clickPos, const ccGLCameraParameters & camera, PointDescriptor & output, double pickWidth_pix = 3.0) const
Octree-driven point picking algorithm.
Definition at line 320 of file ecvOctree.cpp.
References ccGLMatrixTpl< T >::apply(), ccGLMatrixTpl< T >::applyRotation(), cloudViewer::GenericCloud::enableScalarField(), cloudViewer::DgmOctree::findBestLevelForAGivenPopulationPerCell(), Vector3Tpl< PointCoordinateType >::fromArray(), cloudViewer::DgmOctree::GET_BIT_SHIFT(), ccHObject::getAbsoluteGLTransformation(), cloudViewer::DgmOctree::getCellPos(), cloudViewer::DgmOctree::getCellSize(), ccScalarField::getColor(), ccScalarField::getColorScale(), ccPointCloud::getCurrentDisplayedScalarField(), cloudViewer::GenericIndexedCloud::getPoint(), ccGenericPointCloud::getTheVisibilityArray(), cloudViewer::ScalarField::getValue(), AABB< T >::intersects(), cloudViewer::DgmOctree::INVALID_CELL_CODE, ccGLMatrixTpl< T >::inverse(), ccObject::isA(), ccGenericPointCloud::isVisibilityTableInstantiated(), cloudViewer::DgmOctree::m_dimMax, cloudViewer::DgmOctree::m_dimMin, cloudViewer::DgmOctree::m_theAssociatedCloud, m_theAssociatedCloudAsGPC, cloudViewer::DgmOctree::m_thePointsAndTheirCellCodes, ccScalarField::mayHaveHiddenValues(), Vector3Tpl< Type >::norm2d(), Vector3Tpl< Type >::normalize(), ccGLCameraParameters::perspective, ccGLCameraParameters::pixelSize, cloudViewer::DgmOctree::PointDescriptor::point, CV_TYPES::POINT_CLOUD, POINT_VISIBLE, cloudViewer::DgmOctree::PointDescriptor::pointIndex, ccGLCameraParameters::project(), cloudViewer::GenericCloud::setPointScalarValue(), ccDrawableObject::sfShown(), SQRT_3, Ray< T >::squareDistances(), cloudViewer::DgmOctree::PointDescriptor::squareDistd, ccGLCameraParameters::unproject(), Vector2Tpl< Type >::x, Tuple3Tpl< Type >::x, X, Vector2Tpl< Type >::y, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
setDisplayedLevel()
void ccOctree::setDisplayedLevel (int level)
Sets the currently displayed octree level.
Definition at line 74 of file ecvOctree.cpp.
References m_displayedLevel.
setDisplayMode()
void ccOctree::setDisplayMode (DisplayMode mode)
Sets the currently display mode.
Definition at line 81 of file ecvOctree.cpp.
References m_displayMode.
setVisible()
void ccOctree::setVisible (bool state) inline
Sets octree visibility.
Definition at line 74 of file ecvOctree.h.
translateBoundingBox()
void ccOctree::translateBoundingBox (const CCVector3 & T)
Translates the bounding-box of the octree.
If the cloud has been simply translated, there is no use to recompute the octree structure. It's sufficient to update its bounding-box.
Parameters
T translation vector
Definition at line 110 of file ecvOctree.cpp.
References cloudViewer::DgmOctree::m_dimMax, cloudViewer::DgmOctree::m_dimMin, cloudViewer::DgmOctree::m_pointsMax, and cloudViewer::DgmOctree::m_pointsMin.
updated
void ccOctree::updated () signal
Signal sent when the octree organization is modified (cleared, etc.)
Referenced by clear(), and ccPointCloudLODThread::run().
Member Data Documentation
m_displayedLevel
int ccOctree::m_displayedLevel protected
Displayed level.
Definition at line 183 of file ecvOctree.h.
Referenced by draw(), and setDisplayedLevel().
m_displayMode
DisplayMode ccOctree::m_displayMode protected
Display mode.
Definition at line 186 of file ecvOctree.h.
Referenced by draw(), and setDisplayMode().
m_frustumIntersector
ccOctreeFrustumIntersector* ccOctree::m_frustumIntersector protected
For frustum intersection.
Definition at line 189 of file ecvOctree.h.
Referenced by draw(), intersectWithFrustum(), and ~ccOctree().
m_theAssociatedCloudAsGPC
ccGenericPointCloud* ccOctree::m_theAssociatedCloudAsGPC protected
Associated cloud (as a ccGenericPointCloud)
Definition at line 180 of file ecvOctree.h.
Referenced by draw(), and pointPicking().
m_visible
bool ccOctree::m_visible protected
For Octree Display.
Definition at line 192 of file ecvOctree.h.
Referenced by draw().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/ecvOctree.h
/root/ACloudViewer/libs/CV_db/src/ecvOctree.cpp