ACloudViewer: ccGenericPointCloud Class Reference
ccGenericPointCloud Class Reference abstract
A 3D cloud interface with associated features (color, normals, octree, etc.)
#include <ecvGenericPointCloud.h>
Public Types
using VisibilityTableType = std::vector< unsigned char >
Array of "visibility" information for each point.
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Public Types inherited from cloudViewer::GenericCloud
using genericPointAction = std::function< void(const CCVector3 &, ScalarType &)>
Generic function applied to a point (used by foreach)
Public Member Functions
ccGenericPointCloud (QString name=QString())
Default constructor.
ccGenericPointCloud (const ccGenericPointCloud &cloud)
Copy constructor.
~ccGenericPointCloud () override
Default destructor.
virtual ccGenericPointCloud * clone (ccGenericPointCloud *destCloud=nullptr, bool ignoreChildren=false)=0
Clones this entity.
virtual void clear ()
Clears the entity from all its points and features.
virtual ccOctree::Shared computeOctree (cloudViewer::GenericProgressCallback *progressCb=nullptr, bool autoAddChild=true)
Computes the cloud octree.
virtual ccOctree::Shared getOctree () const
Returns the associated octree (if any)
virtual void setOctree (ccOctree::Shared octree, bool autoAddChild=true)
Sets the associated octree.
virtual ccOctreeProxy * getOctreeProxy () const
Returns the associated octree proxy (if any)
virtual void deleteOctree ()
Erases the octree.
virtual const ecvColor::Rgb * getScalarValueColor (ScalarType d) const =0
Returns color corresponding to a given scalar value.
virtual const ecvColor::Rgb * getPointScalarValueColor (unsigned pointIndex) const =0
Returns color corresponding to a given point associated scalar value.
virtual ScalarType getPointDisplayedDistance (unsigned pointIndex) const =0
Returns scalar value associated to a given point.
virtual const ecvColor::Rgb & getPointColor (unsigned pointIndex) const =0
Returns color corresponding to a given point.
virtual const CompressedNormType & getPointNormalIndex (unsigned pointIndex) const =0
Returns compressed normal corresponding to a given point.
virtual const CCVector3 & getPointNormal (unsigned pointIndex) const =0
Returns normal corresponding to a given point.
virtual VisibilityTableType & getTheVisibilityArray ()
Returns associated visibility array.
virtual const VisibilityTableType & getTheVisibilityArray () const
Returns associated visibility array (const version)
virtual cloudViewer::ReferenceCloud * getTheVisiblePoints (const VisibilityTableType *visTable=nullptr, bool silent=false, cloudViewer::ReferenceCloud *selection=nullptr) const
Returns a ReferenceCloud equivalent to the visibility array.
virtual bool isVisibilityTableInstantiated () const
Returns whether the visibility array is allocated or not.
virtual bool resetVisibilityArray ()
Resets the associated visibility array.
virtual void invertVisibilityArray ()
Inverts the visibility array.
virtual void unallocateVisibilityArray ()
Erases the points visibility information.
ccBBox getOwnBB (bool withGLFeatures=false) override
Returns the entity's own bounding-box.
virtual void refreshBB ()=0
Forces bounding-box update.
virtual ccGenericPointCloud * createNewCloudFromVisibilitySelection (bool removeSelectedPoints=false, VisibilityTableType *visTable=nullptr, std::vector< int > *newIndexesOfRemainingPoints=nullptr, bool silent=false, cloudViewer::ReferenceCloud *selection=nullptr)=0
virtual bool removeVisiblePoints (VisibilityTableType *visTable=nullptr, std::vector< int > *newIndexes=nullptr)=0
Removes all the 'visible' points (as defined by the visibility array)
virtual void applyRigidTransformation (const ccGLMatrix &trans)=0
Applies a rigid transformation (rotation + translation)
virtual cloudViewer::ReferenceCloud * crop (const ccBBox &box, bool inside=true)=0
Crops the cloud inside (or outside) a bounding box.
virtual cloudViewer::ReferenceCloud * crop (const ecvOrientedBBox &box)=0
virtual void removePoints (size_t index)=0
virtual void scale (PointCoordinateType fx, PointCoordinateType fy, PointCoordinateType fz, CCVector3 center=CCVector3(0, 0, 0))=0
Multiplies all coordinates by constant factors (one per dimension)
bool isSerializable () const override
Returns whether object is serializable of not.
void setPointSize (unsigned size=0)
Sets point size.
unsigned char getPointSize () const
Returns current point size.
void importParametersFrom (const ccGenericPointCloud *cloud)
Imports the parameters from another cloud.
bool pointPicking (const CCVector2d &clickPos, const ccGLCameraParameters &camera, int &nearestPointIndex, double &nearestSquareDist, double pickWidth=2.0, double pickHeight=2.0, bool autoComputeOctree=false)
Point picking (brute force or octree-driven)
std::tuple< Eigen::Vector3d, Eigen::Matrix3d > computeMeanAndCovariance () const
cloudViewer::SquareMatrixd computeCovariance () const
Public Member Functions inherited from ccShiftedObject
ccShiftedObject (QString name=QString())
Default constructor.
ccShiftedObject (const ccShiftedObject &s)
Copy constructor.
void copyGlobalShiftAndScale (const ccShiftedObject &s)
Copies the Global Shift and Scale from another entity.
virtual void setGlobalShift (double x, double y, double z)
Sets shift applied to original coordinates (information storage only)
virtual void setGlobalShift (const CCVector3d &shift)
Sets shift applied to original coordinates (information storage only)
virtual const CCVector3d & getGlobalShift () const
Returns the shift applied to original coordinates.
virtual void setGlobalScale (double scale)
virtual double getGlobalScale () const
Returns the scale applied to original coordinates.
bool isShifted () const
Returns whether the cloud is shifted or not.
template<typename T >
CCVector3d toGlobal3d (const Vector3Tpl< T > &Plocal) const
Returns the point back-projected into the original coordinates system.
template<typename T >
CCVector3d toLocal3d (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
template<typename T >
CCVector3 toLocal3pc (const Vector3Tpl< T > &Pglobal) const
Returns the point projected into the local (shifted) coordinates system.
bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner) override
GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false) override
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual bool IsEmpty () const
virtual Eigen::Vector3d GetMinBound () const
Returns min bounds for geometry coordinates.
virtual Eigen::Vector2d GetMin2DBound () const
virtual Eigen::Vector3d GetMaxBound () const
Returns max bounds for geometry coordinates.
virtual Eigen::Vector2d GetMax2DBound () const
virtual Eigen::Vector3d GetCenter () const
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const
virtual ccHObject & Transform (const Eigen::Matrix4d &transformation)
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual ccHObject & Translate (const Eigen::Vector3d &translation, bool relative=true)
Apply translation to the geometry coordinates.
virtual ccHObject & Scale (const double s, const Eigen::Vector3d &center)
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center)
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
CV_CLASS_ENUM getClassID () const override
Returns class ID.
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual ccBBox getOwnFitBB (ccGLMatrix &trans)
Returns best-fit bounding-box (if available)
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col)
Draws the entity (and its children) bounding-box.
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
virtual void notifyGeometryUpdate ()
bool isSerializable () const override
Returns whether object is serializable of not.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual unsigned getUniqueIDForDisplay () const
Returns object unqiue ID used for display.
virtual const ccGLMatrix & getGLTransformationHistory () const
Returns the transformation 'history' matrix.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual void getDrawingParameters (glDrawParams &params) const
Returns main OpenGL parameters for this entity.
virtual bool hasColors () const
Returns whether colors are enabled or not.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual bool hasNormals () const
Returns whether normals are enabled or not.
virtual bool normalsShown () const
Returns whether normals are shown or not.
virtual void showNormals (bool state)
Sets normals visibility.
virtual void toggleNormals ()
Toggles normals display state.
virtual bool hasDisplayedScalarField () const
Returns whether an active scalar field is available or not.
virtual bool hasScalarFields () const
Returns whether one or more scalar fields are instantiated.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void toggleMaterials ()
Toggles material display state.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Public Member Functions inherited from cloudViewer::GenericIndexedCloudPersist
~GenericIndexedCloudPersist () override=default
Default destructor.
virtual const CCVector3 * getPointPersistentPtr (unsigned index)=0
Returns the ith point as a persistent pointer.
Public Member Functions inherited from cloudViewer::GenericIndexedCloud
~GenericIndexedCloud () override=default
Default destructor.
virtual const CCVector3 * getPoint (unsigned index) const =0
Returns the ith point.
virtual void getPoint (unsigned index, CCVector3 &P) const =0
Returns the ith point.
virtual void getPoint (unsigned index, double P[3]) const
virtual bool normalsAvailable () const
Returns whether normals are available.
virtual const CCVector3 * getNormal (unsigned index) const
If per-point normals are available, returns the one at a specific index.
Public Member Functions inherited from cloudViewer::GenericCloud
GenericCloud ()=default
Default constructor.
virtual ~GenericCloud ()=default
Default destructor.
virtual unsigned size () const =0
Returns the number of points.
virtual bool hasPoints () const
virtual void forEach (genericPointAction action)=0
Fast iteration mechanism.
virtual void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax)=0
Returns the cloud bounding box.
virtual unsigned char testVisibility (const CCVector3 &P) const
virtual void placeIteratorAtBeginning ()=0
Sets the cloud iterator at the beginning.
virtual const CCVector3 * getNextPoint ()=0
Returns the next point (relatively to the global iterator position)
virtual bool enableScalarField ()=0
Enables the scalar field associated to the cloud.
virtual bool isScalarFieldEnabled () const =0
Returns true if the scalar field is enabled, false otherwise.
virtual void setPointScalarValue (unsigned pointIndex, ScalarType value)=0
Sets the ith point associated scalar value.
virtual ScalarType getPointScalarValue (unsigned pointIndex) const =0
Returns the ith point associated scalar value.
Protected Member Functions
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
Protected Member Functions inherited from ccShiftedObject
bool saveShiftInfoToFile (QFile &out) const
Serialization helper (output)
bool loadShiftInfoFromFile (QFile &in)
Serialization helper (input)
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void drawMeOnly (CC_DRAW_CONTEXT &context)
Draws the entity only (not its children)
virtual void applyGLTransformation (const ccGLMatrix &trans)
Applies a GL transformation to the entity.
virtual void drawNameIn3D ()
Draws the entity name in 3D.
virtual void onDeletionOf (const ccHObject *obj)
This method is called when another object is deleted.
virtual void onUpdateOf (ccHObject *obj)
This method is called when another object (geometry) is updated.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Protected Attributes
VisibilityTableType m_pointsVisibility
Per-point visibility table.
unsigned char m_pointSize
Point size (won't be applied if 0)
Protected Attributes inherited from ccShiftedObject
CCVector3d m_globalShift
Global shift (typically applied at loading time)
double m_globalScale
Global scale (typically applied at loading time)
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Additional Inherited Members
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Detailed Description
A 3D cloud interface with associated features (color, normals, octree, etc.)
A generic point cloud can have multiples features:
colors (RGB)
normals (compressed)
an octree strucutre
visibility information per point (to hide/display subsets of points)
Definition at line 45 of file ecvGenericPointCloud.h.
Member Typedef Documentation
VisibilityTableType
using ccGenericPointCloud::VisibilityTableType = std::vector<unsigned char>
Array of "visibility" information for each point.
See <CCConst.h>
Definition at line 165 of file ecvGenericPointCloud.h.
Constructor & Destructor Documentation
ccGenericPointCloud() [1/2]
ccGenericPointCloud::ccGenericPointCloud (QString name = QString())
Default constructor.
ccGenericPointCloud() [2/2]
ccGenericPointCloud::ccGenericPointCloud (const ccGenericPointCloud & cloud)
Copy constructor.
~ccGenericPointCloud()
ccGenericPointCloud::~ccGenericPointCloud () override
Default destructor.
Member Function Documentation
applyRigidTransformation()
virtual void ccGenericPointCloud::applyRigidTransformation (const ccGLMatrix & trans) pure virtual
Applies a rigid transformation (rotation + translation)
Implemented in ccPointCloud.
clear()
virtual void ccGenericPointCloud::clear () virtual
Clears the entity from all its points and features.
Display parameters are also reseted to their default values.
Reimplemented in ccSymbolCloud, and ccPointCloud.
Referenced by define_ccGenericPointCloud().
clone()
virtual ccGenericPointCloud* ccGenericPointCloud::clone (ccGenericPointCloud * destCloud = nullptr, bool ignoreChildren = false) pure virtual
Clones this entity.
All the main features of the entity are cloned, except from the octree and the points visibility information.
Parameters
destCloud destination cloud can be provided here (must be of the exact same type as the cloned cloud!)
ignoreChildren [optional] whether to ignore the cloud's children or not (in which case they will be cloned as well)
Returns
a copy of this entity
Implemented in ccPointCloud.
Referenced by define_ccGenericPointCloud().
computeCovariance()
cloudViewer::SquareMatrixd ccGenericPointCloud::computeCovariance () const
computeMeanAndCovariance()
std::tuple<Eigen::Vector3d, Eigen::Matrix3d> ccGenericPointCloud::computeMeanAndCovariance () const
computeOctree()
virtual ccOctree::Shared ccGenericPointCloud::computeOctree (cloudViewer::GenericProgressCallback * progressCb = nullptr, bool autoAddChild = true) virtual
Computes the cloud octree.
The octree bounding-box is automatically defined as the smallest 3D cube that totally encloses the cloud. WARNING: any previously attached octree will be deleted, even if the new octree computation failed.
Parameters
progressCb the caller can get some notification of the process progress through this callback mechanism (see cloudViewer documentation)
autoAddChild whether to automatically add the computed octree as child of this cloud or not
Returns
the computed octree
Referenced by ccTrace::buildCurvatureCost(), ccTrace::buildGradientCost(), ccTrace::calculateOptimumSearchRadius(), qCanupoProcess::Classify(), qM3C2Process::Compute(), ComputeMathOpWithNearestNeighbor(), ccCompass::estimateP21(), qM3C2Tools::GuessBestParams(), ccTrace::optimizeSegment(), ccFitPlaneTool::pointPicked(), masc::CorePoints::prepare(), masc::ContextBasedFeature::prepare(), masc::Tools::PrepareFeatures(), and qCanupoTools::TrainClassifier().
createNewCloudFromVisibilitySelection()
virtual ccGenericPointCloud* ccGenericPointCloud::createNewCloudFromVisibilitySelection (bool removeSelectedPoints = false, VisibilityTableType * visTable = nullptr, std::vector< int > * newIndexesOfRemainingPoints = nullptr, bool silent = false, cloudViewer::ReferenceCloud * selection = nullptr) pure virtual
Creates a new point cloud with only the 'visible' points (as defined by the visibility array)
Parameters
[in] removeSelectedPoints if true, 'visible' points are also removed from the current point cloud
[in] visTable visibility table (optional, otherwise the cloud's default one will be used)
[out] newIndexesOfRemainingPoints the new indexes of the remaining points (if removeSelectedPoints is true - optional). Must be initially empty or have the same size as the original cloud.
[in] silent don't issue a warning message if there's no point to keep
[out] selection the corresponding point selection
Returns
new point cloud with the 'visible' points (or the same cloud if all points are visible)
Implemented in ccPointCloud.
crop() [1/2]
virtual cloudViewer::ReferenceCloud* ccGenericPointCloud::crop (const ccBBox & box, bool inside = true) pure virtual
Crops the cloud inside (or outside) a bounding box.
Warning
Always returns a selection (potentially empty) if successful.
Parameters
box cropping box
inside whether selected points are inside or outside the box
Returns
points falling inside (or outside) as a selection
Implemented in ccPointCloud.
crop() [2/2]
virtual cloudViewer::ReferenceCloud* ccGenericPointCloud::crop (const ecvOrientedBBox & box) pure virtual
Implemented in ccPointCloud.
deleteOctree()
virtual void ccGenericPointCloud::deleteOctree () virtual
Erases the octree.
Referenced by DistanceMapGenerationTool::ConvertCloudToConical(), and DistanceMapGenerationTool::ConvertCloudToCylindrical().
fromFile_MeOnly()
bool ccGenericPointCloud::fromFile_MeOnly (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override protected virtual
Loads own object data.
Called by 'fromFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
in input file
dataVersion file version
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Reimplemented from ccHObject.
Reimplemented in ccPointCloud.
getOctree()
virtual ccOctree::Shared ccGenericPointCloud::getOctree () const virtual
Returns the associated octree (if any)
Referenced by ccTrace::buildCurvatureCost(), ccTrace::buildGradientCost(), ccTrace::calculateOptimumSearchRadius(), qCanupoProcess::Classify(), qM3C2Process::Compute(), ComputeMathOpWithNearestNeighbor(), DistanceMapGenerationTool::ConvertCloudToConical(), DistanceMapGenerationTool::ConvertCloudToCylindrical(), qFacets::extractFacets(), qM3C2Tools::GuessBestParams(), ccTrace::optimizeSegment(), ccFitPlaneTool::pointPicked(), masc::CorePoints::prepare(), masc::Tools::PrepareFeatures(), and qCanupoTools::TrainClassifier().
getOctreeProxy()
virtual ccOctreeProxy* ccGenericPointCloud::getOctreeProxy () const virtual
Returns the associated octree proxy (if any)
Referenced by qCanupoProcess::Classify(), qM3C2Process::Compute(), and qM3C2Tools::GuessBestParams().
getOwnBB()
ccBBox ccGenericPointCloud::getOwnBB (bool withGLFeatures = false) override virtual
Returns the entity's own bounding-box.
Children bboxes are ignored.
Parameters
withGLFeatures whether to take into account display-only elements (if any)
Returns
bounding-box
Reimplemented from ccHObject.
Referenced by DistanceMapGenerationDlg::DistanceMapGenerationDlg(), qPoissonRecon::doAction(), qFacets::extractFacets(), qM3C2Tools::GuessBestParams(), PcdFilter::loadFile(), LoadScan(), NormalEstimation::openInputDialog(), GreedyTriangulation::openInputDialog(), MarchingCubeReconstruction::openInputDialog(), PoissonReconstruction::openInputDialog(), qCanupo2DViewDialog::trainClassifier(), and qCanupoTools::TrainClassifier().
getPointColor()
virtual const ecvColor::Rgb& ccGenericPointCloud::getPointColor (unsigned pointIndex) const pure virtual
Returns color corresponding to a given point.
WARNING: color array must be enabled! (see ccDrawableObject::hasColors)
Implemented in ccPointCloud.
Referenced by CCCloudToDraco(), HSVDialog::onItemPicked(), RgbDialog::onItemPicked(), LASFilter::saveToFile(), and ToFbxMesh().
getPointDisplayedDistance()
virtual ScalarType ccGenericPointCloud::getPointDisplayedDistance (unsigned pointIndex) const pure virtual
Returns scalar value associated to a given point.
The returned value is taken from the current displayed scalar field WARNING: scalar field must be enabled! (see ccDrawableObject::hasDisplayedScalarField)
Implemented in ccPointCloud.
getPointNormal()
virtual const CCVector3& ccGenericPointCloud::getPointNormal (unsigned pointIndex) const pure virtual
Returns normal corresponding to a given point.
WARNING: normals array must be enabled! (see ccDrawableObject::hasNormals)
Implemented in ccPointCloud.
Referenced by CCCloudToDraco(), qPCV::doAction(), and ToFbxMesh().
getPointNormalIndex()
virtual const CompressedNormType& ccGenericPointCloud::getPointNormalIndex (unsigned pointIndex) const pure virtual
Returns compressed normal corresponding to a given point.
WARNING: normals array must be enabled! (see ccDrawableObject::hasNormals)
Implemented in ccPointCloud.
getPointScalarValueColor()
virtual const ecvColor::Rgb* ccGenericPointCloud::getPointScalarValueColor (unsigned pointIndex) const pure virtual
Returns color corresponding to a given point associated scalar value.
The returned value depends on the current scalar field display parameters. It may even be 0 if the value shouldn't be displayed. WARNING: scalar field must be enabled! (see ccDrawableObject::hasDisplayedScalarField)
Implemented in ccPointCloud.
getPointSize()
unsigned char ccGenericPointCloud::getPointSize () const inline
Returns current point size.
0 means that the cloud will use current OpenGL value (see glPointSize).
Definition at line 283 of file ecvGenericPointCloud.h.
getScalarValueColor()
virtual const ecvColor::Rgb* ccGenericPointCloud::getScalarValueColor (ScalarType d) const pure virtual
Returns color corresponding to a given scalar value.
The returned value depends on the current scalar field display parameters. It may even be 0 if the value shouldn't be displayed. WARNING: scalar field must be enabled! (see ccDrawableObject::hasDisplayedScalarField)
Implemented in ccPointCloud.
getTheVisibilityArray() [1/2]
virtual VisibilityTableType& ccGenericPointCloud::getTheVisibilityArray () inline virtual
Returns associated visibility array.
Definition at line 168 of file ecvGenericPointCloud.h.
Referenced by StereogramDialog::updateFacetsFilter().
getTheVisibilityArray() [2/2]
virtual const VisibilityTableType& ccGenericPointCloud::getTheVisibilityArray () const inline virtual
Returns associated visibility array (const version)
Definition at line 173 of file ecvGenericPointCloud.h.
getTheVisiblePoints()
virtual cloudViewer::ReferenceCloud* ccGenericPointCloud::getTheVisiblePoints (const VisibilityTableType * visTable = nullptr, bool silent = false, cloudViewer::ReferenceCloud * selection = nullptr) const virtual
Returns a ReferenceCloud equivalent to the visibility array.
Parameters
visTable visibility table (optional, otherwise the cloud's default one will be used)
silent don't issue warnings if no visible point is present
selection input reference cloud to be used (optional)
Returns
the visible points as a ReferenceCloud
importParametersFrom()
void ccGenericPointCloud::importParametersFrom (const ccGenericPointCloud * cloud)
Imports the parameters from another cloud.
Only the specific parameters are imported.
Referenced by qM3C2Process::Compute().
invertVisibilityArray()
virtual void ccGenericPointCloud::invertVisibilityArray () virtual
Inverts the visibility array.
isSerializable()
bool ccGenericPointCloud::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccSerializableObject.
Definition at line 269 of file ecvGenericPointCloud.h.
isVisibilityTableInstantiated()
virtual bool ccGenericPointCloud::isVisibilityTableInstantiated () const virtual
Returns whether the visibility array is allocated or not.
Referenced by ccSNECloud::drawMeOnly(), and StereogramDialog::exportCurrentSelection().
minimumFileVersion_MeOnly()
short ccGenericPointCloud::minimumFileVersion_MeOnly () const override protected virtual
Returns the minimum file version required to save this instance's own data To be overloaded (but still called ;) by subclass. Used internally by minimumFileVersion() to compute the overall minimum.
Reimplemented from ccHObject.
Reimplemented in ccPointCloud.
pointPicking()
bool ccGenericPointCloud::pointPicking (const CCVector2d & clickPos, const ccGLCameraParameters & camera, int & nearestPointIndex, double & nearestSquareDist, double pickWidth = 2.0, double pickHeight = 2.0, bool autoComputeOctree = false)
Point picking (brute force or octree-driven)
Warning
the octree-driven method only works if pickWidth == pickHeight
refreshBB()
virtual void ccGenericPointCloud::refreshBB () pure virtual
Forces bounding-box update.
Implemented in ccPointCloud.
removePoints()
virtual void ccGenericPointCloud::removePoints (size_t index) pure virtual
Implemented in ccPointCloud.
removeVisiblePoints()
virtual bool ccGenericPointCloud::removeVisiblePoints (VisibilityTableType * visTable = nullptr, std::vector< int > * newIndexes = nullptr) pure virtual
Removes all the 'visible' points (as defined by the visibility array)
Parameters
visTable visibility table (optional, otherwise the cloud's default one will be used)
newIndexes optional: stores the new indexes of the points (either an index >= 0 if kept, or -1 if not). Must be initially empty or have the same size as the original cloud.
Returns
success
Implemented in ccPointCloud.
resetVisibilityArray()
virtual bool ccGenericPointCloud::resetVisibilityArray () virtual
Resets the associated visibility array.
Warning: allocates the array if it was not done yet!
Referenced by StereogramDialog::updateFacetsFilter().
scale()
virtual void ccGenericPointCloud::scale (PointCoordinateType fx, PointCoordinateType fy, PointCoordinateType fz, CCVector3 center = CCVector3(0, 0, 0)) pure virtual
Multiplies all coordinates by constant factors (one per dimension)
WARNING: attached octree may be deleted.
Parameters
fx multiplication factor along the X dimension
fy multiplication factor along the Y dimension
fz multiplication factor along the Z dimension
center scaling center (0,0,0) by default
Implemented in ccPointCloud.
setOctree()
virtual void ccGenericPointCloud::setOctree (ccOctree::Shared octree, bool autoAddChild = true) virtual
Sets the associated octree.
setPointSize()
void ccGenericPointCloud::setPointSize (unsigned size = 0) inline
Sets point size.
Overrides default value one if superior than 0 (see glPointSize).
Definition at line 275 of file ecvGenericPointCloud.h.
References size.
Referenced by ExtractSIFT::compute(), define_ccPointCloud(), GrainsAsEllipsoids::exportResultsAsCloud(), and getMortarMaps().
toFile_MeOnly()
bool ccGenericPointCloud::toFile_MeOnly (QFile & out, short dataVersion) const override protected virtual
Save own object data.
Called by 'toFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
out output file
dataVersion target file version for compatibility control
Reimplemented from ccHObject.
Reimplemented in ccPointCloud.
unallocateVisibilityArray()
virtual void ccGenericPointCloud::unallocateVisibilityArray () virtual
Erases the points visibility information.
Referenced by StereogramDialog::updateFacetsFilter().
Member Data Documentation
m_pointSize
unsigned char ccGenericPointCloud::m_pointSize protected
Point size (won't be applied if 0)
Definition at line 321 of file ecvGenericPointCloud.h.
m_pointsVisibility
VisibilityTableType ccGenericPointCloud::m_pointsVisibility protected
Per-point visibility table.
If this table is allocated, only values set to POINT_VISIBLE will be considered as visible/selected.
Definition at line 318 of file ecvGenericPointCloud.h.
Referenced by ccSNECloud::drawMeOnly().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvGenericPointCloud.h