ACloudViewer: G3PointDisclaimer Class Reference
G3PointDisclaimer Class Reference
#include <G3PointDisclaimer.h>
Public Member Functions
G3PointDisclaimer (QWidget *parent=nullptr)
~G3PointDisclaimer ()
Static Public Member Functions
static bool show (ecvMainAppInterface *app)
Detailed Description
Definition at line 18 of file G3PointDisclaimer.h.
Constructor & Destructor Documentation
G3PointDisclaimer()
G3PointDisclaimer::G3PointDisclaimer (QWidget * parent = nullptr) explicit
Definition at line 20 of file G3PointDisclaimer.cpp.
Referenced by show().
~G3PointDisclaimer()
G3PointDisclaimer::~G3PointDisclaimer ()
Definition at line 43 of file G3PointDisclaimer.cpp.
Member Function Documentation
show()
bool G3PointDisclaimer::show (ecvMainAppInterface * app) static
Definition at line 45 of file G3PointDisclaimer.cpp.
References G3PointDisclaimer(), and ecvMainAppInterface::getMainWindow().
Referenced by G3Point::G3PointAction::GetG3PointAction().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qG3Point/include/G3PointDisclaimer.h
/root/ACloudViewer/plugins/core/Standard/qG3Point/src/G3PointDisclaimer.cpp