ACloudViewer: RgbDialog Class Reference
RgbDialog Class Reference
#include <RgbDialog.h>
Public Slots
void pickPoint_first (bool)
void pickPoint_second (bool)
Public Member Functions
RgbDialog (ccPickingHub *pickingHub, QWidget *parent=nullptr)
virtual void onItemPicked (const PickedItem &pi)
Inherited from ccPickingListener.
Public Member Functions inherited from ccPickingListener
virtual ~ccPickingListener ()=default
Protected Attributes
QWidget * m_pickingWin
Picking window (if any)
ccPickingHub * m_pickingHub
Picking hub.
Detailed Description
Definition at line 37 of file RgbDialog.h.
Constructor & Destructor Documentation
RgbDialog()
RgbDialog::RgbDialog (ccPickingHub * pickingHub, QWidget * parent = nullptr) explicit
Definition at line 20 of file RgbDialog.cpp.
References pickPoint_first(), and pickPoint_second().
Member Function Documentation
onItemPicked()
void RgbDialog::onItemPicked (const PickedItem & pi) virtual
Inherited from ccPickingListener.
Implements ccPickingListener.
Definition at line 92 of file RgbDialog.cpp.
References ccPickingHub::activeWindow(), ecvColor::RgbTpl< Type >::b, ccPickingListener::PickedItem::entity, ecvColor::RgbTpl< Type >::g, ccGenericPointCloud::getPointColor(), ccDrawableObject::hasColors(), ccObject::isKindOf(), ccPickingListener::PickedItem::itemIndex, m_pickingHub, m_pickingWin, CV_TYPES::POINT_CLOUD, CVLog::Print(), and ecvColor::RgbTpl< Type >::r.
pickPoint_first
void RgbDialog::pickPoint_first (bool state) slot
Definition at line 48 of file RgbDialog.cpp.
References ccPickingHub::addListener(), CVLog::Error(), m_pickingHub, and ccPickingHub::removeListener().
Referenced by RgbDialog().
pickPoint_second
void RgbDialog::pickPoint_second (bool state) slot
Definition at line 70 of file RgbDialog.cpp.
References ccPickingHub::addListener(), CVLog::Error(), m_pickingHub, and ccPickingHub::removeListener().
Referenced by RgbDialog().
Member Data Documentation
m_pickingHub
ccPickingHub* RgbDialog::m_pickingHub protected
Picking hub.
Definition at line 56 of file RgbDialog.h.
Referenced by onItemPicked(), pickPoint_first(), and pickPoint_second().
m_pickingWin
QWidget* RgbDialog::m_pickingWin protected
Picking window (if any)
Definition at line 53 of file RgbDialog.h.
Referenced by onItemPicked().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qColorimetricSegmenter/RgbDialog.h
/root/ACloudViewer/plugins/core/Standard/qColorimetricSegmenter/RgbDialog.cpp