ACloudViewer: colmap::ThreadControlWidget Class Reference
colmap::ThreadControlWidget Class Reference
#include <thread_control_widget.h>
Public Member Functions
ThreadControlWidget (QWidget *parent)
void StartThread (const QString &progress_text, const bool stoppable, Thread *thread)
void StartFunction (const QString &progress_text, const std::function< void()> &func)
Detailed Description
Definition at line 17 of file thread_control_widget.h.
Constructor & Destructor Documentation
ThreadControlWidget()
colmap::ThreadControlWidget::ThreadControlWidget (QWidget * parent) explicit
Definition at line 36 of file thread_control_widget.cc.
Member Function Documentation
StartFunction()
void colmap::ThreadControlWidget::StartFunction (const QString & progress_text, const std::function< void()> & func)
Definition at line 97 of file thread_control_widget.cc.
References Run(), and StartThread().
StartThread()
void colmap::ThreadControlWidget::StartThread (const QString & progress_text, const bool stoppable, Thread * thread)
Definition at line 53 of file thread_control_widget.cc.
References ecvColor::LookUpTable::at(), and colmap::Thread::FINISHED_CALLBACK.
Referenced by colmap::AutomaticReconstructionWidget::Run(), colmap::SIFTExtractionWidget::Run(), colmap::ImportFeaturesWidget::Run(), colmap::ExhaustiveMatchingTab::Run(), colmap::SequentialMatchingTab::Run(), colmap::VocabTreeMatchingTab::Run(), colmap::SpatialMatchingTab::Run(), colmap::TransitiveMatchingTab::Run(), colmap::CustomMatchingTab::Run(), and StartFunction().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/thread_control_widget.h
/root/ACloudViewer/libs/Reconstruction/src/ui/thread_control_widget.cc