ACloudViewer: cloudViewer::t::geometry::kernel::TransformIndexer Class Reference
cloudViewer::t::geometry::kernel::TransformIndexer Class Reference
Helper class for converting coordinates/indices between 3D/3D, 3D/2D, 2D/3D.
#include <GeometryIndexer.h>
Public Member Functions
TransformIndexer (const core::Tensor &intrinsics, const core::Tensor &extrinsics, float scale=1.0f)
CLOUDVIEWER_HOST_DEVICE void RigidTransform (float x_in, float y_in, float z_in, float *x_out, float *y_out, float *z_out) const
Transform a 3D coordinate in camera coordinate to world coordinate.
CLOUDVIEWER_HOST_DEVICE void Rotate (float x_in, float y_in, float z_in, float *x_out, float *y_out, float *z_out) const
Transform a 3D coordinate in camera coordinate to world coordinate.
CLOUDVIEWER_HOST_DEVICE void Project (float x_in, float y_in, float z_in, float *u_out, float *v_out) const
Project a 3D coordinate in camera coordinate to a 2D uv coordinate.
CLOUDVIEWER_HOST_DEVICE void Unproject (float u_in, float v_in, float d_in, float *x_out, float *y_out, float *z_out) const
Unproject a 2D uv coordinate with depth to 3D in camera coordinate.
CLOUDVIEWER_HOST_DEVICE void GetFocalLength (float *fx, float *fy) const
CLOUDVIEWER_HOST_DEVICE void GetCameraPosition (float *x, float *y, float *z) const
Detailed Description
Helper class for converting coordinates/indices between 3D/3D, 3D/2D, 2D/3D.
Definition at line 26 of file GeometryIndexer.h.
Constructor & Destructor Documentation
TransformIndexer()
cloudViewer::t::geometry::kernel::TransformIndexer::TransformIndexer (const core::Tensor & intrinsics, const core::Tensor & extrinsics, float scale = 1.0f) inline
intrinsic: simple pinhole camera matrix, stored in fx, fy, cx, cy extrinsic: world to camera transform, stored in a 3x4 matrix
Definition at line 30 of file GeometryIndexer.h.
References AssertTensorDevice, AssertTensorDtype, AssertTensorShape, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::IsContiguous(), and LogError.
Member Function Documentation
GetCameraPosition()
CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::TransformIndexer::GetCameraPosition (float * x, float * y, float * z) const inline
Definition at line 128 of file GeometryIndexer.h.
References x, y, and z.
GetFocalLength()
CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::TransformIndexer::GetFocalLength (float * fx, float * fy) const inline
Definition at line 123 of file GeometryIndexer.h.
Referenced by cloudViewer::t::pipelines::kernel::odometry::GetJacobianHybrid(), and cloudViewer::t::pipelines::kernel::odometry::GetJacobianIntensity().
Project()
CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::TransformIndexer::Project (float x_in, float y_in, float z_in, float * u_out, float * v_out) const inline
Project a 3D coordinate in camera coordinate to a 2D uv coordinate.
Definition at line 101 of file GeometryIndexer.h.
Referenced by cloudViewer::t::geometry::kernel::voxel_grid::EstimateRangeCPU(), cloudViewer::t::pipelines::kernel::odometry::GetJacobianHybrid(), cloudViewer::t::pipelines::kernel::odometry::GetJacobianIntensity(), cloudViewer::t::pipelines::kernel::odometry::GetJacobianPointToPlane(), cloudViewer::t::pipelines::kernel::odometry::GetJacobianPointToPoint(), and cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU().
RigidTransform()
CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::TransformIndexer::RigidTransform (float x_in, float y_in, float z_in, float * x_out, float * y_out, float * z_out) const inline
Transform a 3D coordinate in camera coordinate to world coordinate.
Definition at line 63 of file GeometryIndexer.h.
Referenced by cloudViewer::t::geometry::kernel::voxel_grid::EstimateRangeCPU(), cloudViewer::t::pipelines::kernel::odometry::GetJacobianHybrid(), cloudViewer::t::pipelines::kernel::odometry::GetJacobianIntensity(), cloudViewer::t::pipelines::kernel::odometry::GetJacobianPointToPlane(), cloudViewer::t::pipelines::kernel::odometry::GetJacobianPointToPoint(), cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU(), and cloudViewer::t::geometry::kernel::voxel_grid::RayCastCPU().
Rotate()
CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::TransformIndexer::Rotate (float x_in, float y_in, float z_in, float * x_out, float * y_out, float * z_out) const inline
Transform a 3D coordinate in camera coordinate to world coordinate.
Definition at line 82 of file GeometryIndexer.h.
Referenced by cloudViewer::t::geometry::kernel::voxel_grid::RayCastCPU().
Unproject()
CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::TransformIndexer::Unproject (float u_in, float v_in, float d_in, float * x_out, float * y_out, float * z_out) const inline
Unproject a 2D uv coordinate with depth to 3D in camera coordinate.
Definition at line 112 of file GeometryIndexer.h.
Referenced by cloudViewer::t::geometry::kernel::image::CreateVertexMapCPU(), cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU(), and cloudViewer::t::geometry::kernel::voxel_grid::RayCastCPU().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/t/geometry/kernel/GeometryIndexer.h