ACloudViewer: ccGBLSensorProjectionDlg Class Reference
ccGBLSensorProjectionDlg Class Reference
Ground-based (lidar) sensor parameters dialog.
#include <ecvGBLSensorProjectionDlg.h>
Public Member Functions
ccGBLSensorProjectionDlg (QWidget *parent=0)
Default constructor.
void initWithGBLSensor (const ccGBLSensor *sensor)
void updateGBLSensor (ccGBLSensor *sensor)
Detailed Description
Ground-based (lidar) sensor parameters dialog.
Definition at line 15 of file ecvGBLSensorProjectionDlg.h.
Constructor & Destructor Documentation
ccGBLSensorProjectionDlg()
ccGBLSensorProjectionDlg::ccGBLSensorProjectionDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 16 of file ecvGBLSensorProjectionDlg.cpp.
Member Function Documentation
initWithGBLSensor()
void ccGBLSensorProjectionDlg::initWithGBLSensor (const ccGBLSensor * sensor)
Definition at line 35 of file ecvGBLSensorProjectionDlg.cpp.
References ccGLMatrixTpl< T >::data(), ccGBLSensor::getPitchStep(), ccSensor::getRigidTransformation(), ccGBLSensor::getRotationOrder(), ccGBLSensor::getSensorRange(), ccGLMatrixTpl< T >::getTranslation(), ccGBLSensor::getUncertainty(), ccGBLSensor::getYawStep(), ccGBLSensor::PITCH_THEN_YAW, cloudViewer::RadiansToDegrees(), and ccGBLSensor::YAW_THEN_PITCH.
updateGBLSensor()
void ccGBLSensorProjectionDlg::updateGBLSensor (ccGBLSensor * sensor)
Definition at line 93 of file ecvGBLSensorProjectionDlg.cpp.
References ccGLMatrixTpl< T >::data(), cloudViewer::DegreesToRadians(), ccGBLSensor::PITCH_THEN_YAW, ccGBLSensor::setPitchStep(), ccSensor::setRigidTransformation(), ccGBLSensor::setRotationOrder(), ccGBLSensor::setSensorRange(), ccGLMatrixTpl< T >::setTranslation(), ccGBLSensor::setUncertainty(), ccGBLSensor::setYawStep(), and ccGBLSensor::YAW_THEN_PITCH.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvGBLSensorProjectionDlg.h
/root/ACloudViewer/app/ecvGBLSensorProjectionDlg.cpp