ACloudViewer: Vertex< _Real > Class Template Reference
Vertex< _Real > Class Template Reference
Public Types
typedef _Real Real
Public Member Functions
Vertex (const Point< Real, 3 > &point)
Vertex (const Point< Real, 3 > &point, const PointData< Real > &data, double _w=0.0)
Vertex ()
Vertex & operator*= (Real s)
Vertex & operator/= (Real s)
Vertex & operator+= (const Vertex &p)
Public Member Functions inherited from PointData< _Real >
PointData (Point3D< _Real > p=Point3D< _Real >(), _Real w=0)
PointData ()
PointData (const _Real _normal[3], const _Real _color[3], _Real scale=1.0)
PointData operator* (_Real s) const
PointData operator/ (_Real s) const
PointData & operator+= (const PointData &d)
PointData & operator*= (_Real s)
Public Attributes
Point< Real, 3 > point
double w
Public Attributes inherited from PointData< _Real >
Point3D< _Real > position
_Real weightedCoarserDValue
_Real weight
_Real normal [3]
_Real color [3]
Detailed Description
template<typename _Real>
class Vertex< _Real >
Definition at line 55 of file PoissonReconLib.cpp.
Member Typedef Documentation
Real
template<typename _Real > typedef _Real Vertex< _Real >::Real
Definition at line 57 of file PoissonReconLib.cpp.
Constructor & Destructor Documentation
Vertex() [1/3]
template<typename _Real > Vertex< _Real >::Vertex (const Point< Real, 3 > & point) inline
Definition at line 59 of file PoissonReconLib.cpp.
Vertex() [2/3]
template<typename _Real > Vertex< _Real >::Vertex (const Point< Real, 3 > & point, const PointData< Real > & data, double _w = 0.0) inline
Definition at line 62 of file PoissonReconLib.cpp.
Vertex() [3/3]
template<typename _Real > Vertex< _Real >::Vertex () inline
Definition at line 67 of file PoissonReconLib.cpp.
Member Function Documentation
operator*=()
template<typename _Real > Vertex& Vertex< _Real >::operator*= (Real s) inline
Definition at line 69 of file PoissonReconLib.cpp.
References PointData< Real >::operator*=().
operator+=()
template<typename _Real > Vertex& Vertex< _Real >::operator+= (const Vertex< _Real > & p) inline
Definition at line 84 of file PoissonReconLib.cpp.
References PointData< Real >::operator+=(), Vertex< _Real >::point, and Vertex< _Real >::w.
operator/=()
template<typename _Real > Vertex& Vertex< _Real >::operator/= (Real s) inline
Definition at line 77 of file PoissonReconLib.cpp.
References PointData< Real >::operator*=().
Member Data Documentation
point
template<typename _Real > Point<Real, 3> Vertex< _Real >::point
Definition at line 93 of file PoissonReconLib.cpp.
Referenced by ExtractMesh(), and Vertex< _Real >::operator+=().
w
template<typename _Real > double Vertex< _Real >::w
Definition at line 94 of file PoissonReconLib.cpp.
Referenced by ExtractMesh(), and Vertex< _Real >::operator+=().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qPoissonRecon/extern/Src_CC_wrap/PoissonReconLib.cpp