ACloudViewer: cvSliceFilter Class Reference
cvSliceFilter Class Reference
#include <cvSliceFilter.h>
Public Member Functions
cvSliceFilter (QWidget *parent=nullptr)
void apply ()
virtual ccHObject * getOutput () override
virtual void clearAllActor () override
Public Member Functions inherited from cvCutFilter
virtual void showInteractor (bool state) override
virtual void getInteractorBounds (ccBBox &bbox) override
virtual void getInteractorTransformation (ccGLMatrixd &trans) override
virtual void shift (const CCVector3d &v) override
Shifts the current interactor.
Public Member Functions inherited from cvGenericFilter
cvGenericFilter (QWidget *parent=nullptr)
virtual ~cvGenericFilter ()
virtual void start ()
virtual void update ()
virtual void reset ()
virtual void restoreOrigin ()
virtual void getOutput (std::vector< ccHObject * > &outputSlices, std::vector< ccPolyline * > &outputContours)
virtual bool initModel ()
virtual bool setInput (ccHObject *obj)
virtual void getInteractorInfos (ccBBox &bbox, ccGLMatrixd &trans)
void setUpViewer (PclUtils::PCLVis *viewer)
void showOutline (bool show=true)
void setNegative (bool state)
void setInteractor (vtkRenderWindowInteractor *interactor)
vtkRenderWindowInteractor * getInteractor ()
Additional Inherited Members
Protected Types inherited from cvCutFilter
enum CutType { Box , Plane , Sphere }
Protected Types inherited from cvGenericFilter
enum DisplayEffect { Opaque , Transparent , Points , Wireframe }
Protected Slots inherited from cvCutFilter
void onOriginChanged (double *orgin)
void onNormalChanged (double *normal)
void onCenterChanged (double *center)
void onRadiusChanged (double radius)
void onPlanesChanged (vtkPlanes *planes)
void showContourLines (bool show=true)
void onPreview (bool dummy)
Protected Slots inherited from cvGenericFilter
void onDoubleClick (int x, int y)
Protected Member Functions inherited from cvCutFilter
cvCutFilter (QWidget *parent=nullptr)
void setNormal (double normal[3])
void setOrigin (double origin[3])
void setRadius (double radius)
void updateCutWidget ()
virtual void initFilter () override
void setCutType (CutType type)
CutType cutType () const
virtual void modelReady () override
virtual void dataChanged () override
virtual void updateUi () override
void createUi ()
void resetPlaneWidget ()
void resetSphereWidget ()
void resetBoxWidget ()
Protected Member Functions inherited from cvGenericFilter
virtual void colorsChanged ()
void setDisplayEffect (DisplayEffect effect)
DisplayEffect displayEffect () const
void safeOff (vtk3DWidget *widget)
void updateSize ()
void UpdateScalarRange ()
void applyDisplayEffect ()
void setScalarBarColors (const QColor &clr1, const QColor &clr2)
QColor color1 () const
QColor color2 () const
void setScalarRange (double min, double max)
double scalarMin () const
double scalarMax () const
vtkSmartPointer< vtkDataArray > getActorScalars (vtkSmartPointer< vtkActor > actor)
int getDefaultScalarInterpolationForDataSet (vtkDataSet *data)
vtkSmartPointer< vtkLookupTable > createLookupTable (double min, double max)
template<class ConfigClass >
void setupConfigWidget (ConfigClass *cc)
template<class DataObject , class Mapper >
void createActorFromData (vtkDataObject *dataObj)
void showScalarBar (bool show=true)
void setOutlineColor (const QColor &clr)
bool isValidPolyData () const
bool isValidDataSet () const
void addActor (const vtkSmartPointer< vtkProp > actor)
void removeActor (const vtkSmartPointer< vtkProp > actor)
void setResultData (vtkSmartPointer< vtkDataObject > data)
vtkSmartPointer< vtkDataObject > resultData () const
Protected Attributes inherited from cvCutFilter
double m_normal [3]
double m_origin [3]
double m_center [3]
double m_radius
vtkSmartPointer< vtkBoxWidget > m_boxWidget
vtkSmartPointer< vtkSphereWidget > m_sphereWidget
vtkSmartPointer< vtkImplicitPlaneWidget > m_planeWidget
Ui::CutFilterDlg * m_configUi = nullptr
CutType m_cutType = CutType::Box
vtkSmartPointer< vtkPlanes > m_planes
vtkSmartPointer< vtkActor > m_contourLinesActor
Protected Attributes inherited from cvGenericFilter
Ui::GenericFilterDlg * m_ui = nullptr
DisplayEffect m_displayEffect = Opaque
vtkDataObject * m_dataObject = nullptr
vtkSmartPointer< vtkDataObject > m_resultData
bool m_keepMode
bool m_negative
bool m_meshMode
bool m_preview
std::string m_id
ccHObject * m_entity = nullptr
PclUtils::PCLVis * m_viewer = nullptr
vtkRenderWindowInteractor * m_interactor = nullptr
vtkSmartPointer< vtkActor > m_modelActor
vtkSmartPointer< vtkLODActor > m_filterActor
vtkSmartPointer< vtkScalarBarActor > m_scalarBar
vtkSmartPointer< vtkActor > m_outlineActor
QColor m_color1 = Qt::blue
QColor m_color2 = Qt::red
double m_scalarMin = 0.0
double m_scalarMax = 1.0
Static Protected Attributes inherited from cvGenericFilter
static const int MAX_PREVIEW_NUMBER = 20e4
Detailed Description
Definition at line 14 of file cvSliceFilter.h.
Constructor & Destructor Documentation
cvSliceFilter()
cvSliceFilter::cvSliceFilter (QWidget * parent = nullptr) explicit
Definition at line 38 of file cvSliceFilter.cpp.
Member Function Documentation
apply()
void cvSliceFilter::apply () virtual
Implements cvGenericFilter.
Definition at line 44 of file cvSliceFilter.cpp.
References cvGenericFilter::addActor(), cvGenericFilter::applyDisplayEffect(), cvCutFilter::Box, cvGenericFilter::createLookupTable(), cvCutFilter::cutType(), cvCutFilter::m_center, cvCutFilter::m_contourLinesActor, cvGenericFilter::m_dataObject, cvGenericFilter::m_filterActor, cvGenericFilter::m_keepMode, cvCutFilter::m_normal, cvCutFilter::m_origin, cvCutFilter::m_planes, cvCutFilter::m_radius, cvCutFilter::Plane, cvGenericFilter::scalarMax(), cvGenericFilter::scalarMin(), cvCutFilter::showContourLines(), cvCutFilter::Sphere, VTK_CREATE, and VtkUtils::vtkInitOnce().
clearAllActor()
void cvSliceFilter::clearAllActor () override virtual
Reimplemented from cvCutFilter.
Definition at line 42 of file cvSliceFilter.cpp.
References cvCutFilter::clearAllActor().
getOutput()
ccHObject * cvSliceFilter::getOutput () override virtual
Reimplemented from cvGenericFilter.
Definition at line 88 of file cvSliceFilter.cpp.
References vtk2cc::ConvertToMultiPolylines(), ccMesh::getAssociatedCloud(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccObject::getName(), ecvColor::green(), ccObject::isKindOf(), cvGenericFilter::m_entity, CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, result, ccPolyline::setGlobalScale(), ccPolyline::setGlobalShift(), ccObject::setName(), ccHObjectCaster::ToMesh(), ccHObjectCaster::ToPointCloud(), ccHObjectCaster::ToPolyline(), and VtkUtils::vtkInitOnce().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/cvSliceFilter.h
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/cvSliceFilter.cpp