ACloudViewer: E57FileInputStream Class Reference
E57FileInputStream Class Reference
Public Member Functions
E57FileInputStream (CheckedFile *cf, uint64_t logicalStart, uint64_t logicalLength)
~E57FileInputStream () override=default
E57FileInputStream (const E57FileInputStream &)=delete
E57FileInputStream & operator= (const E57FileInputStream &)=delete
XMLFilePos curPos () const override
XMLSize_t readBytes (XMLByte *const toFill, const XMLSize_t maxToRead) override
const XMLCh * getContentType () const override
Detailed Description
Definition at line 88 of file E57XmlParser.cpp.
Constructor & Destructor Documentation
E57FileInputStream() [1/2]
E57FileInputStream::E57FileInputStream (CheckedFile * cf, uint64_t logicalStart, uint64_t logicalLength)
Definition at line 115 of file E57XmlParser.cpp.
~E57FileInputStream()
E57FileInputStream::~E57FileInputStream () override default
E57FileInputStream() [2/2]
E57FileInputStream::E57FileInputStream (const E57FileInputStream &) delete
Member Function Documentation
curPos()
XMLFilePos E57FileInputStream::curPos () const inline override
Definition at line 97 of file E57XmlParser.cpp.
getContentType()
const XMLCh* E57FileInputStream::getContentType () const inline override
Definition at line 102 of file E57XmlParser.cpp.
operator=()
E57FileInputStream& E57FileInputStream::operator= (const E57FileInputStream &) delete
readBytes()
XMLSize_t E57FileInputStream::readBytes (XMLByte *const toFill, const XMLSize_t maxToRead) override
size_t and XMLSize_t should be compatible, should get compiler warning here if not
Be careful if size_t is smaller than int64_t
size_t is at least as big as int64_t
size_t is smaller than int64_t, Calc max that size_t can hold
read smaller of size_max, available ??? redo
Definition at line 120 of file E57XmlParser.cpp.
References max(), min(), e57::CheckedFile::read(), and e57::CheckedFile::seek().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/IO/qE57IO/extern/libE57Format/src/E57XmlParser.cpp