ACloudViewer: colmap::PointColormapBase Class Reference
colmap::PointColormapBase Class Reference abstract
#include <colormaps.h>
Public Member Functions
PointColormapBase ()
virtual ~PointColormapBase ()=default
virtual void Prepare (std::unordered_map< camera_t, Camera > &cameras, std::unordered_map< image_t, Image > &images, std::unordered_map< point3D_t, Point3D > &points3D, std::vector< image_t > &reg_image_ids)=0
virtual Eigen::Vector4f ComputeColor (const point3D_t point3D_id, const Point3D &point3D)=0
void UpdateScale (std::vector< float > *values)
float AdjustScale (const float gray)
Public Attributes
float scale
float min
float max
float range
float min_q
float max_q
Detailed Description
Definition at line 19 of file colormaps.h.
Constructor & Destructor Documentation
PointColormapBase()
colmap::PointColormapBase::PointColormapBase ()
Definition at line 38 of file colormaps.cc.
~PointColormapBase()
virtual colmap::PointColormapBase::~PointColormapBase () virtual default
Member Function Documentation
AdjustScale()
float colmap::PointColormapBase::AdjustScale (const float gray)
Definition at line 59 of file colormaps.cc.
References max, min, range, and scale.
Referenced by colmap::PointColormapError::ComputeColor(), colmap::PointColormapTrackLen::ComputeColor(), and colmap::PointColormapGroundResolution::ComputeColor().
ComputeColor()
virtual Eigen::Vector4f colmap::PointColormapBase::ComputeColor (const point3D_t point3D_id, const Point3D & point3D) pure virtual
Implemented in colmap::PointColormapGroundResolution, colmap::PointColormapTrackLen, colmap::PointColormapError, and colmap::PointColormapPhotometric.
Prepare()
virtual void colmap::PointColormapBase::Prepare (std::unordered_map< camera_t, Camera > & cameras, std::unordered_map< image_t, Image > & images, std::unordered_map< point3D_t, Point3D > & points3D, std::vector< image_t > & reg_image_ids) pure virtual
Implemented in colmap::PointColormapGroundResolution, colmap::PointColormapTrackLen, colmap::PointColormapError, and colmap::PointColormapPhotometric.
UpdateScale()
void colmap::PointColormapBase::UpdateScale (std::vector< float > * values)
Definition at line 46 of file colormaps.cc.
References max, max_q, min, min_q, and range.
Referenced by colmap::PointColormapError::Prepare(), colmap::PointColormapTrackLen::Prepare(), and colmap::PointColormapGroundResolution::Prepare().
Member Data Documentation
max
float colmap::PointColormapBase::max
Definition at line 37 of file colormaps.h.
Referenced by AdjustScale(), and UpdateScale().
max_q
float colmap::PointColormapBase::max_q
Definition at line 40 of file colormaps.h.
Referenced by UpdateScale().
min
float colmap::PointColormapBase::min
Definition at line 36 of file colormaps.h.
Referenced by AdjustScale(), and UpdateScale().
min_q
float colmap::PointColormapBase::min_q
Definition at line 39 of file colormaps.h.
Referenced by UpdateScale().
range
float colmap::PointColormapBase::range
Definition at line 38 of file colormaps.h.
Referenced by AdjustScale(), and UpdateScale().
scale
float colmap::PointColormapBase::scale
Definition at line 35 of file colormaps.h.
Referenced by AdjustScale().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/colormaps.h
/root/ACloudViewer/libs/Reconstruction/src/ui/colormaps.cc