ACloudViewer: colmap::Image Class Reference
colmap::Image Class Reference
#include <image.h>
Public Member Functions
Image ()
void SetUp (const Camera &camera)
void TearDown ()
image_t ImageId () const
void SetImageId (const image_t image_id)
const std::string & Name () const
std::string & Name ()
void SetName (const std::string &name)
camera_t CameraId () const
void SetCameraId (const camera_t camera_id)
bool HasCamera () const
bool IsRegistered () const
void SetRegistered (const bool registered)
point2D_t NumPoints2D () const
point2D_t NumPoints3D () const
point2D_t NumObservations () const
void SetNumObservations (const point2D_t num_observations)
point2D_t NumCorrespondences () const
void SetNumCorrespondences (const point2D_t num_observations)
point2D_t NumVisiblePoints3D () const
size_t Point3DVisibilityScore () const
const std::vector< point2D_t > & NumCorrespondencesHavePoint3D () const
std::vector< point2D_t > & NumCorrespondencesHavePoint3D ()
const VisibilityPyramid & Point3DVisibilityPyramid () const
VisibilityPyramid & Point3DVisibilityPyramid ()
const Eigen::Vector4d & Qvec () const
Eigen::Vector4d & Qvec ()
double Qvec (const size_t idx) const
double & Qvec (const size_t idx)
void SetQvec (const Eigen::Vector4d &qvec)
const Eigen::Vector4d & QvecPrior () const
Eigen::Vector4d & QvecPrior ()
double QvecPrior (const size_t idx) const
double & QvecPrior (const size_t idx)
bool HasQvecPrior () const
void SetQvecPrior (const Eigen::Vector4d &qvec)
const Eigen::Vector3d & Tvec () const
Eigen::Vector3d & Tvec ()
double Tvec (const size_t idx) const
double & Tvec (const size_t idx)
void SetTvec (const Eigen::Vector3d &tvec)
const Eigen::Vector3d & TvecPrior () const
Eigen::Vector3d & TvecPrior ()
double TvecPrior (const size_t idx) const
double & TvecPrior (const size_t idx)
bool HasTvecPrior () const
void SetTvecPrior (const Eigen::Vector3d &tvec)
const class Point2D & Point2D (const point2D_t point2D_idx) const
class Point2D & Point2D (const point2D_t point2D_idx)
const std::vector< class Point2D > & Points2D () const
void SetPoints2D (const std::vector< Eigen::Vector2d > &points)
void SetPoints2D (const std::vector< class Point2D > &points)
void SetPoint3DForPoint2D (const point2D_t point2D_idx, const point3D_t point3D_id)
void ResetPoint3DForPoint2D (const point2D_t point2D_idx)
bool IsPoint3DVisible (const point2D_t point2D_idx) const
bool HasPoint3D (const point3D_t point3D_id) const
void IncrementCorrespondenceHasPoint3D (const point2D_t point2D_idx)
void DecrementCorrespondenceHasPoint3D (const point2D_t point2D_idx)
void NormalizeQvec ()
Eigen::Matrix3x4d ProjectionMatrix () const
Eigen::Matrix3x4d InverseProjectionMatrix () const
Eigen::Matrix3d RotationMatrix () const
Eigen::Vector3d ProjectionCenter () const
Eigen::Vector3d ViewingDirection () const
Static Public Attributes
static const int kNumPoint3DVisibilityPyramidLevels = 6
Detailed Description
Definition at line 29 of file image.h.
Constructor & Destructor Documentation
Image()
colmap::Image::Image ()
Definition at line 46 of file image.cc.
Referenced by BOOST_AUTO_TEST_CASE().
Member Function Documentation
CameraId()
camera_t colmap::Image::CameraId () const inline
Definition at line 248 of file image.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::IncrementalMapper::RegisterInitialImagePair(), colmap::IncrementalMapper::RegisterNextImage(), and colmap::IncrementalTriangulator::Retriangulate().
DecrementCorrespondenceHasPoint3D()
void colmap::Image::DecrementCorrespondenceHasPoint3D (const point2D_t point2D_idx)
Definition at line 125 of file image.cc.
References colmap::VisibilityPyramid::ResetPoint(), colmap::Point2D::X(), and colmap::Point2D::Y().
HasCamera()
bool colmap::Image::HasCamera () const inline
Definition at line 255 of file image.h.
References colmap::kInvalidCameraId.
HasPoint3D()
bool colmap::Image::HasPoint3D (const point3D_t point3D_id) const
Definition at line 105 of file image.cc.
HasQvecPrior()
bool colmap::Image::HasQvecPrior () const inline
Definition at line 321 of file image.h.
References colmap::IsNaN().
HasTvecPrior()
bool colmap::Image::HasTvecPrior () const inline
Definition at line 345 of file image.h.
References colmap::IsNaN().
ImageId()
image_t colmap::Image::ImageId () const inline
Definition at line 238 of file image.h.
Referenced by BOOST_AUTO_TEST_CASE(), cloudViewer::TwoViewInfoTab::ShowMatches(), and colmap::TwoViewInfoTab::ShowMatches().
IncrementCorrespondenceHasPoint3D()
void colmap::Image::IncrementCorrespondenceHasPoint3D (const point2D_t point2D_idx)
Definition at line 112 of file image.cc.
References colmap::VisibilityPyramid::SetPoint(), colmap::Point2D::X(), and colmap::Point2D::Y().
InverseProjectionMatrix()
Eigen::Matrix3x4d colmap::Image::InverseProjectionMatrix () const
Definition at line 144 of file image.cc.
References colmap::ComposeProjectionMatrix(), and colmap::InvertProjectionMatrix().
IsPoint3DVisible()
bool colmap::Image::IsPoint3DVisible (const point2D_t point2D_idx) const inline
Definition at line 359 of file image.h.
IsRegistered()
bool colmap::Image::IsRegistered () const inline
Definition at line 257 of file image.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Reconstruction::IsImageRegistered(), colmap::IncrementalMapper::RegisterNextImage(), and colmap::IncrementalTriangulator::Retriangulate().
Name() [1/2]
std::string & colmap::Image::Name () inline
Definition at line 244 of file image.h.
References name_.
Name() [2/2]
const std::string & colmap::Image::Name () const inline
Definition at line 242 of file image.h.
References name_.
Referenced by colmap::Reconstruction::FindCommonRegImageIds(), colmap::Reconstruction::Load(), cloudViewer::TwoViewInfoTab::ShowMatches(), and colmap::TwoViewInfoTab::ShowMatches().
NormalizeQvec()
void colmap::Image::NormalizeQvec ()
Definition at line 138 of file image.cc.
References colmap::NormalizeQuaternion().
NumCorrespondences()
point2D_t colmap::Image::NumCorrespondences () const inline
Definition at line 273 of file image.h.
NumCorrespondencesHavePoint3D() [1/2]
std::vector< point2D_t > & colmap::Image::NumCorrespondencesHavePoint3D () inline
Definition at line 289 of file image.h.
NumCorrespondencesHavePoint3D() [2/2]
const std::vector< point2D_t > & colmap::Image::NumCorrespondencesHavePoint3D () const inline
Definition at line 285 of file image.h.
NumObservations()
point2D_t colmap::Image::NumObservations () const inline
Definition at line 267 of file image.h.
NumPoints2D()
point2D_t colmap::Image::NumPoints2D () const inline
Definition at line 261 of file image.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::Load().
NumPoints3D()
point2D_t colmap::Image::NumPoints3D () const inline
Definition at line 265 of file image.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Reconstruction::ComputeNumObservations(), and colmap::BundleAdjustmentConfig::NumResiduals().
NumVisiblePoints3D()
point2D_t colmap::Image::NumVisiblePoints3D () const inline
Definition at line 279 of file image.h.
Point2D() [1/2]
class Point2D & colmap::Image::Point2D (const point2D_t point2D_idx) inline
Definition at line 353 of file image.h.
Point2D() [2/2]
const class Point2D & colmap::Image::Point2D (const point2D_t point2D_idx) const inline
Definition at line 349 of file image.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Reconstruction::Merge(), colmap::IncrementalMapper::RegisterInitialImagePair(), colmap::IncrementalMapper::RegisterNextImage(), and colmap::IncrementalTriangulator::Retriangulate().
Point3DVisibilityPyramid() [1/2]
VisibilityPyramid & colmap::Image::Point3DVisibilityPyramid () inline
Definition at line 297 of file image.h.
Point3DVisibilityPyramid() [2/2]
const VisibilityPyramid & colmap::Image::Point3DVisibilityPyramid () const inline
Definition at line 293 of file image.h.
Point3DVisibilityScore()
size_t colmap::Image::Point3DVisibilityScore () const inline
Definition at line 281 of file image.h.
References colmap::VisibilityPyramid::Score().
Points2D()
const std::vector< class Point2D > & colmap::Image::Points2D () const inline
Definition at line 357 of file image.h.
ProjectionCenter()
Eigen::Vector3d colmap::Image::ProjectionCenter () const
Definition at line 152 of file image.cc.
References colmap::ProjectionCenterFromPose().
Referenced by colmap::AlignToPrincipalPlane(), BOOST_AUTO_TEST_CASE(), colmap::IncrementalTriangulator::CompleteImage(), colmap::IncrementalMapper::RegisterInitialImagePair(), and colmap::RunModelComparer().
ProjectionMatrix()
Eigen::Matrix3x4d colmap::Image::ProjectionMatrix () const
Definition at line 140 of file image.cc.
References colmap::ComposeProjectionMatrix().
Referenced by colmap::IncrementalTriangulator::CompleteImage(), and colmap::IncrementalMapper::RegisterInitialImagePair().
Qvec() [1/4]
Eigen::Vector4d & colmap::Image::Qvec () inline
Definition at line 303 of file image.h.
Qvec() [2/4]
const Eigen::Vector4d & colmap::Image::Qvec () const inline
Definition at line 301 of file image.h.
Referenced by colmap::AlignToPrincipalPlane(), colmap::CameraRig::ComputeRelativePoses(), colmap::IncrementalMapper::RegisterInitialImagePair(), and colmap::RunModelComparer().
Qvec() [3/4]
double & colmap::Image::Qvec (const size_t idx) inline
Definition at line 307 of file image.h.
Qvec() [4/4]
double colmap::Image::Qvec (const size_t idx) const inline
Definition at line 305 of file image.h.
QvecPrior() [1/4]
Eigen::Vector4d & colmap::Image::QvecPrior () inline
Definition at line 313 of file image.h.
QvecPrior() [2/4]
const Eigen::Vector4d & colmap::Image::QvecPrior () const inline
Definition at line 311 of file image.h.
Referenced by BOOST_AUTO_TEST_CASE().
QvecPrior() [3/4]
double & colmap::Image::QvecPrior (const size_t idx) inline
Definition at line 319 of file image.h.
QvecPrior() [4/4]
double colmap::Image::QvecPrior (const size_t idx) const inline
Definition at line 315 of file image.h.
ResetPoint3DForPoint2D()
void colmap::Image::ResetPoint3DForPoint2D (const point2D_t point2D_idx)
Definition at line 97 of file image.cc.
References colmap::Point2D::HasPoint3D(), colmap::kInvalidPoint3DId, and colmap::Point2D::SetPoint3DId().
Referenced by colmap::Reconstruction::Merge().
RotationMatrix()
Eigen::Matrix3d colmap::Image::RotationMatrix () const
Definition at line 148 of file image.cc.
References colmap::QuaternionToRotationMatrix().
Referenced by ViewingDirection().
SetCameraId()
void colmap::Image::SetCameraId (const camera_t camera_id) inline
Definition at line 250 of file image.h.
References colmap::kInvalidCameraId.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::DeleteAllPoints2DAndPoints3D().
SetImageId()
void colmap::Image::SetImageId (const image_t image_id) inline
Definition at line 240 of file image.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::DeleteAllPoints2DAndPoints3D().
SetName()
void colmap::Image::SetName (const std::string & name) inline
Definition at line 246 of file image.h.
References name, and name_.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::DeleteAllPoints2DAndPoints3D().
SetNumCorrespondences()
void colmap::Image::SetNumCorrespondences (const point2D_t num_observations) inline
Definition at line 275 of file image.h.
Referenced by colmap::Reconstruction::DeleteAllPoints2DAndPoints3D(), and colmap::Reconstruction::Load().
SetNumObservations()
void colmap::Image::SetNumObservations (const point2D_t num_observations) inline
Definition at line 269 of file image.h.
Referenced by colmap::Reconstruction::Load().
SetPoint3DForPoint2D()
void colmap::Image::SetPoint3DForPoint2D (const point2D_t point2D_idx, const point3D_t point3D_id)
Definition at line 87 of file image.cc.
References colmap::Point2D::HasPoint3D(), colmap::kInvalidPoint3DId, and colmap::Point2D::SetPoint3DId().
SetPoints2D() [1/2]
void colmap::Image::SetPoints2D (const std::vector< class Point2D > & points)
Definition at line 81 of file image.cc.
References points.
SetPoints2D() [2/2]
void colmap::Image::SetPoints2D (const std::vector< Eigen::Vector2d > & points)
Definition at line 71 of file image.cc.
References points.
Referenced by GenerateReconstruction(), and colmap::Reconstruction::Load().
SetQvec()
void colmap::Image::SetQvec (const Eigen::Vector4d & qvec) inline
Definition at line 309 of file image.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::DeleteAllPoints2DAndPoints3D().
SetQvecPrior()
void colmap::Image::SetQvecPrior (const Eigen::Vector4d & qvec) inline
Definition at line 323 of file image.h.
Referenced by colmap::Reconstruction::DeleteAllPoints2DAndPoints3D().
SetRegistered()
void colmap::Image::SetRegistered (const bool registered) inline
Definition at line 259 of file image.h.
Referenced by colmap::Reconstruction::DeleteAllPoints2DAndPoints3D(), and colmap::Reconstruction::Merge().
SetTvec()
void colmap::Image::SetTvec (const Eigen::Vector3d & tvec) inline
Definition at line 333 of file image.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::DeleteAllPoints2DAndPoints3D().
SetTvecPrior()
void colmap::Image::SetTvecPrior (const Eigen::Vector3d & tvec) inline
Definition at line 347 of file image.h.
Referenced by colmap::Reconstruction::DeleteAllPoints2DAndPoints3D().
SetUp()
void colmap::Image::SetUp (const Camera & camera)
Definition at line 60 of file image.cc.
References colmap::Camera::CameraId(), colmap::Camera::Height(), kNumPoint3DVisibilityPyramidLevels, and colmap::Camera::Width().
TearDown()
void colmap::Image::TearDown ()
Definition at line 67 of file image.cc.
Tvec() [1/4]
Eigen::Vector3d & colmap::Image::Tvec () inline
Definition at line 327 of file image.h.
Tvec() [2/4]
const Eigen::Vector3d & colmap::Image::Tvec () const inline
Definition at line 325 of file image.h.
Referenced by colmap::AlignToPrincipalPlane(), BOOST_AUTO_TEST_CASE(), colmap::CameraRig::ComputeRelativePoses(), colmap::IncrementalMapper::RegisterInitialImagePair(), and colmap::RunModelComparer().
Tvec() [3/4]
double & colmap::Image::Tvec (const size_t idx) inline
Definition at line 331 of file image.h.
Tvec() [4/4]
double colmap::Image::Tvec (const size_t idx) const inline
Definition at line 329 of file image.h.
TvecPrior() [1/4]
Eigen::Vector3d & colmap::Image::TvecPrior () inline
Definition at line 337 of file image.h.
TvecPrior() [2/4]
const Eigen::Vector3d & colmap::Image::TvecPrior () const inline
Definition at line 335 of file image.h.
Referenced by BOOST_AUTO_TEST_CASE().
TvecPrior() [3/4]
double & colmap::Image::TvecPrior (const size_t idx) inline
Definition at line 343 of file image.h.
TvecPrior() [4/4]
double colmap::Image::TvecPrior (const size_t idx) const inline
Definition at line 339 of file image.h.
ViewingDirection()
Eigen::Vector3d colmap::Image::ViewingDirection () const
Definition at line 156 of file image.cc.
References RotationMatrix().
Member Data Documentation
kNumPoint3DVisibilityPyramidLevels
const int colmap::Image::kNumPoint3DVisibilityPyramidLevels = 6 static
Definition at line 182 of file image.h.
Referenced by SetUp().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/image.h
/root/ACloudViewer/libs/Reconstruction/src/base/image.cc