ACloudViewer: ccUnrollDlg Class Reference
ccUnrollDlg Class Reference
Dialog: unroll clould on a cylinder or a cone.
#include <ecvUnrollDlg.h>
Public Member Functions
ccUnrollDlg (QWidget *parent=0)
Default constructor.
ccPointCloud::UnrollMode getType () const
int getAxisDimension () const
bool isAxisPositionAuto () const
CCVector3 getAxisPosition () const
void getAngleRange (double &start_deg, double &stop_deg) const
double getRadius () const
double getConeHalfAngle () const
bool exportDeviationSF () const
void toPersistentSettings () const
void fromPersistentSettings ()
Protected Slots
void shapeTypeChanged (int index)
void axisDimensionChanged (int index)
void axisAutoStateChanged (int checkState)
Protected Attributes
bool coneMode
Detailed Description
Dialog: unroll clould on a cylinder or a cone.
Definition at line 19 of file ecvUnrollDlg.h.
Constructor & Destructor Documentation
ccUnrollDlg()
ccUnrollDlg::ccUnrollDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 13 of file ecvUnrollDlg.cpp.
References axisAutoStateChanged(), axisDimensionChanged(), and shapeTypeChanged().
Member Function Documentation
axisAutoStateChanged
void ccUnrollDlg::axisAutoStateChanged (int checkState) protected slot
Definition at line 110 of file ecvUnrollDlg.cpp.
References axisDimensionChanged().
Referenced by ccUnrollDlg(), and shapeTypeChanged().
axisDimensionChanged
void ccUnrollDlg::axisDimensionChanged (int index) protected slot
Definition at line 119 of file ecvUnrollDlg.cpp.
Referenced by axisAutoStateChanged(), and ccUnrollDlg().
exportDeviationSF()
bool ccUnrollDlg::exportDeviationSF () const
Definition at line 65 of file ecvUnrollDlg.cpp.
Referenced by fromPersistentSettings().
fromPersistentSettings()
void ccUnrollDlg::fromPersistentSettings ()
Definition at line 160 of file ecvUnrollDlg.cpp.
References exportDeviationSF(), s_axisCenter, s_startAngle_deg, s_stopAngle_deg, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
getAngleRange()
void ccUnrollDlg::getAngleRange (double & start_deg, double & stop_deg) const
Definition at line 47 of file ecvUnrollDlg.cpp.
Referenced by toPersistentSettings().
getAxisDimension()
int ccUnrollDlg::getAxisDimension () const
Definition at line 39 of file ecvUnrollDlg.cpp.
getAxisPosition()
CCVector3 ccUnrollDlg::getAxisPosition () const
Definition at line 52 of file ecvUnrollDlg.cpp.
getConeHalfAngle()
double ccUnrollDlg::getConeHalfAngle () const
Definition at line 61 of file ecvUnrollDlg.cpp.
getRadius()
double ccUnrollDlg::getRadius () const
Definition at line 59 of file ecvUnrollDlg.cpp.
getType()
ccPointCloud::UnrollMode ccUnrollDlg::getType () const
Definition at line 34 of file ecvUnrollDlg.cpp.
isAxisPositionAuto()
bool ccUnrollDlg::isAxisPositionAuto () const
Definition at line 43 of file ecvUnrollDlg.cpp.
shapeTypeChanged
void ccUnrollDlg::shapeTypeChanged (int index) protected slot
Definition at line 69 of file ecvUnrollDlg.cpp.
References axisAutoStateChanged(), ccPointCloud::CONE, ccPointCloud::CYLINDER, ccPointCloud::STRAIGHTENED_CONE, and ccPointCloud::STRAIGHTENED_CONE2.
Referenced by ccUnrollDlg().
toPersistentSettings()
void ccUnrollDlg::toPersistentSettings () const
Definition at line 137 of file ecvUnrollDlg.cpp.
References getAngleRange(), s_axisCenter, s_startAngle_deg, s_stopAngle_deg, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Member Data Documentation
coneMode
bool ccUnrollDlg::coneMode protected
Definition at line 44 of file ecvUnrollDlg.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvUnrollDlg.h
/root/ACloudViewer/app/ecvUnrollDlg.cpp