ACloudViewer: cloudViewer::t::io::NumpyArray Class Reference
cloudViewer::t::io::NumpyArray Class Reference
Public Member Functions
NumpyArray (const core::Tensor &t)
NumpyArray (const core::SizeVector &shape, char type, int64_t word_size, bool fortran_order)
template<typename T >
T * GetDataPtr ()
template<typename T >
const T * GetDataPtr () const
core::Dtype GetDtype () const
core::SizeVector GetShape () const
bool IsFortranOrder () const
int64_t NumBytes () const
int64_t NumElements () const
core::Tensor ToTensor () const
void Save (std::string file_name) const
Detailed Description
Definition at line 495 of file NumpyIO.cpp.
Constructor & Destructor Documentation
NumpyArray() [1/2]
cloudViewer::t::io::NumpyArray::NumpyArray (const core::Tensor & t) inline
Definition at line 497 of file NumpyIO.cpp.
References cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Tensor::GetBlob(), and cloudViewer::core::Tensor::To().
NumpyArray() [2/2]
cloudViewer::t::io::NumpyArray::NumpyArray (const core::SizeVector & shape, char type, int64_t word_size, bool fortran_order) inline
Definition at line 505 of file NumpyIO.cpp.
References NumBytes().
Member Function Documentation
GetDataPtr() [1/2]
template<typename T > T* cloudViewer::t::io::NumpyArray::GetDataPtr () inline
Definition at line 517 of file NumpyIO.cpp.
Referenced by cloudViewer::t::io::CreateNumpyArrayFromCompressedFile(), and cloudViewer::t::io::CreateNumpyArrayFromFile().
GetDataPtr() [2/2]
template<typename T > const T* cloudViewer::t::io::NumpyArray::GetDataPtr () const inline
Definition at line 522 of file NumpyIO.cpp.
GetDtype()
core::Dtype cloudViewer::t::io::NumpyArray::GetDtype () const inline
Definition at line 526 of file NumpyIO.cpp.
References cloudViewer::core::Bool, cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Int16, cloudViewer::core::Int32, cloudViewer::core::Int64, cloudViewer::core::Int8, cloudViewer::core::UInt16, cloudViewer::core::UInt32, cloudViewer::core::UInt64, cloudViewer::core::UInt8, and cloudViewer::core::Undefined.
Referenced by Save(), and ToTensor().
GetShape()
core::SizeVector cloudViewer::t::io::NumpyArray::GetShape () const inline
Definition at line 542 of file NumpyIO.cpp.
IsFortranOrder()
bool cloudViewer::t::io::NumpyArray::IsFortranOrder () const inline
Definition at line 544 of file NumpyIO.cpp.
NumBytes()
int64_t cloudViewer::t::io::NumpyArray::NumBytes () const inline
Definition at line 546 of file NumpyIO.cpp.
References NumElements().
Referenced by cloudViewer::t::io::CreateNumpyArrayFromCompressedFile(), cloudViewer::t::io::CreateNumpyArrayFromFile(), and NumpyArray().
NumElements()
int64_t cloudViewer::t::io::NumpyArray::NumElements () const inline
Definition at line 548 of file NumpyIO.cpp.
References cloudViewer::core::SizeVector::NumElements().
Referenced by NumBytes().
Save()
void cloudViewer::t::io::NumpyArray::Save (std::string file_name) const inline
Definition at line 567 of file NumpyIO.cpp.
References cloudViewer::t::io::CreateNumpyHeader(), cloudViewer::t::io::CharVector::Data(), GetDtype(), cloudViewer::utility::filesystem::CFile::GetError(), cloudViewer::utility::filesystem::CFile::GetFILE(), LogError, cloudViewer::core::SizeVector::NumElements(), cloudViewer::utility::filesystem::CFile::Open(), SEEK_END, SEEK_SET, and cloudViewer::t::io::CharVector::Size().
Referenced by cloudViewer::t::io::WriteNpy().
ToTensor()
core::Tensor cloudViewer::t::io::NumpyArray::ToTensor () const inline
Definition at line 550 of file NumpyIO.cpp.
References cloudViewer::core::shape_util::DefaultStrides(), GetDtype(), cloudViewer::core::Dtype::GetDtypeCode(), LogError, and cloudViewer::core::Dtype::Undefined.
Referenced by cloudViewer::t::io::ReadNpy(), and cloudViewer::t::io::ReadNpz().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/t/io/NumpyIO.cpp