ACloudViewer: colmap::SimilarityTransform3 Class Reference
colmap::SimilarityTransform3 Class Reference
#include <similarity_transform.h>
Public Member Functions
SimilarityTransform3 ()
SimilarityTransform3 (const Eigen::Matrix3x4d &matrix)
SimilarityTransform3 (const Eigen::Transform< double, 3, Eigen::Affine > &transform)
SimilarityTransform3 (const double scale, const Eigen::Vector4d &qvec, const Eigen::Vector3d &tvec)
void Write (const std::string &path)
template<bool kEstimateScale = true>
bool Estimate (const std::vector< Eigen::Vector3d > &src, const std::vector< Eigen::Vector3d > &dst)
SimilarityTransform3 Inverse () const
void TransformPoint (Eigen::Vector3d *xyz) const
void TransformPose (Eigen::Vector4d *qvec, Eigen::Vector3d *tvec) const
Eigen::Matrix4d Matrix () const
double Scale () const
Eigen::Vector4d Rotation () const
Eigen::Vector3d Translation () const
Static Public Member Functions
static SimilarityTransform3 FromFile (const std::string &path)
Detailed Description
Definition at line 24 of file similarity_transform.h.
Constructor & Destructor Documentation
SimilarityTransform3() [1/4]
colmap::SimilarityTransform3::SimilarityTransform3 ()
Definition at line 178 of file similarity_transform.cc.
Referenced by Inverse().
SimilarityTransform3() [2/4]
colmap::SimilarityTransform3::SimilarityTransform3 (const Eigen::Matrix3x4d & matrix) explicit
Definition at line 182 of file similarity_transform.cc.
SimilarityTransform3() [3/4]
colmap::SimilarityTransform3::SimilarityTransform3 (const Eigen::Transform< double, 3, Eigen::Affine > & transform) explicit
Definition at line 186 of file similarity_transform.cc.
SimilarityTransform3() [4/4]
colmap::SimilarityTransform3::SimilarityTransform3 (const double scale, const Eigen::Vector4d & qvec, const Eigen::Vector3d & tvec)
Definition at line 190 of file similarity_transform.cc.
References colmap::ComposeProjectionMatrix().
Member Function Documentation
Estimate()
template<bool kEstimateScale> bool colmap::SimilarityTransform3::Estimate (const std::vector< Eigen::Vector3d > & src, const std::vector< Eigen::Vector3d > & dst)
Definition at line 77 of file similarity_transform.h.
References colmap::SimilarityTransformEstimator< kDim, kEstimateScale >::Estimate().
Referenced by colmap::Reconstruction::Align(), and TestEstimationWithNumCoords().
FromFile()
SimilarityTransform3 colmap::SimilarityTransform3::FromFile (const std::string & path) static
Definition at line 257 of file similarity_transform.cc.
References cloudViewer::t::geometry::path.
Referenced by colmap::RunModelCropper(), colmap::RunModelSplitter(), and colmap::RunModelTransformer().
Inverse()
SimilarityTransform3 colmap::SimilarityTransform3::Inverse () const
Definition at line 207 of file similarity_transform.cc.
References SimilarityTransform3().
Referenced by colmap::RunModelCropper(), colmap::RunModelSplitter(), and colmap::RunModelTransformer().
Matrix()
Eigen::Matrix4d colmap::SimilarityTransform3::Matrix () const
Definition at line 241 of file similarity_transform.cc.
Referenced by BOOST_AUTO_TEST_CASE(), Rotation(), colmap::RunModelComparer(), Scale(), TestEstimationWithNumCoords(), and Translation().
Rotation()
Eigen::Vector4d colmap::SimilarityTransform3::Rotation () const
Definition at line 249 of file similarity_transform.cc.
References Matrix(), colmap::RotationMatrixToQuaternion(), and Scale().
Referenced by BOOST_AUTO_TEST_CASE().
Scale()
double colmap::SimilarityTransform3::Scale () const
Definition at line 245 of file similarity_transform.cc.
References Matrix().
Referenced by colmap::AlignToENUPlane(), BOOST_AUTO_TEST_CASE(), Rotation(), colmap::RunModelSplitter(), and TransformPose().
TransformPoint()
void colmap::SimilarityTransform3::TransformPoint (Eigen::Vector3d * xyz) const
Definition at line 211 of file similarity_transform.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Reconstruction::Merge(), TestEstimationWithNumCoords(), and colmap::Reconstruction::Transform().
TransformPose()
void colmap::SimilarityTransform3::TransformPose (Eigen::Vector4d * qvec, Eigen::Vector3d * tvec) const
Definition at line 215 of file similarity_transform.cc.
References colmap::ComposeProjectionMatrix(), colmap::RotationMatrixToQuaternion(), and Scale().
Referenced by colmap::AlignToPrincipalPlane(), colmap::Reconstruction::Merge(), colmap::RunModelComparer(), and colmap::Reconstruction::Transform().
Translation()
Eigen::Vector3d colmap::SimilarityTransform3::Translation () const
Definition at line 253 of file similarity_transform.cc.
References Matrix().
Referenced by BOOST_AUTO_TEST_CASE().
Write()
void colmap::SimilarityTransform3::Write (const std::string & path)
Definition at line 199 of file similarity_transform.cc.
References QtCompat::endl(), and cloudViewer::t::geometry::path.
Referenced by colmap::RunModelAligner().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/similarity_transform.h
/root/ACloudViewer/libs/Reconstruction/src/base/similarity_transform.cc