ACloudViewer: MLSDialog Class Reference
MLSDialog Class Reference
#include <MLSDialog.h>
Public Member Functions
MLSDialog (QWidget *parent=nullptr)
Protected Slots
void activateMenu (QString name)
void toggleMethods (bool status)
void updateSquaredGaussian (double radius)
Protected Member Functions
void updateCombo ()
void deactivateAllMethods ()
Detailed Description
Definition at line 15 of file MLSDialog.h.
Constructor & Destructor Documentation
MLSDialog()
MLSDialog::MLSDialog (QWidget * parent = nullptr) explicit
Definition at line 20 of file MLSDialog.cpp.
References activateMenu(), deactivateAllMethods(), updateCombo(), and updateSquaredGaussian().
Member Function Documentation
activateMenu
void MLSDialog::activateMenu (QString name) protected slot
Definition at line 47 of file MLSDialog.cpp.
References deactivateAllMethods(), and name.
Referenced by MLSDialog().
deactivateAllMethods()
void MLSDialog::deactivateAllMethods () protected
Definition at line 61 of file MLSDialog.cpp.
Referenced by activateMenu(), MLSDialog(), and toggleMethods().
toggleMethods
void MLSDialog::toggleMethods (bool status) protected slot
Definition at line 67 of file MLSDialog.cpp.
References deactivateAllMethods().
updateCombo()
void MLSDialog::updateCombo () protected
Definition at line 33 of file MLSDialog.cpp.
Referenced by MLSDialog().
updateSquaredGaussian
void MLSDialog::updateSquaredGaussian (double radius) protected slot
Definition at line 71 of file MLSDialog.cpp.
Referenced by MLSDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/dialogs/MLSDialog.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/dialogs/MLSDialog.cpp