ACloudViewer: cloudViewer::utility::random::NormalGenerator< T > Class Template Reference
cloudViewer::utility::random::NormalGenerator< T > Class Template Reference
#include <Random.h>
Public Member Functions
NormalGenerator (const T mean=0.0, const T stddev=1.0)
T operator() ()
Call this to generate a normally distributed floating point value.
Protected Attributes
std::normal_distribution< T > distribution_
Detailed Description
template<typename T>
class cloudViewer::utility::random::NormalGenerator< T >
Generate normally distributed floating point values with mean and std. This class is globally seeded by utility::random::Seed(). This class is a wrapper around std::normal_distribution.
Example:
#include "cloudViewer/utility/Random.h"
// Globally seed cloudViewer. This will affect all random functions.
utility::random::Seed(0);
// Generate a random double with mean 0 and std 1.
utility::random::NormalGenerator<double> gen(0, 1);
for (size_t i = 0; i < 10; i++) {
    std::cout << gen() << std::endl;
}
Definition at line 154 of file Random.h.
Constructor & Destructor Documentation
NormalGenerator()
template<typename T > cloudViewer::utility::random::NormalGenerator< T >::NormalGenerator (const T mean = 0.0, const T stddev = 1.0) inline
Generate normally distributed floating point value with mean and std.
Parameters
mean The mean of the distribution.
stddev The standard deviation of the distribution.
Definition at line 160 of file Random.h.
References LogError, and stddev().
Member Function Documentation
operator()()
template<typename T > T cloudViewer::utility::random::NormalGenerator< T >::operator() () inline
Call this to generate a normally distributed floating point value.
Definition at line 168 of file Random.h.
References cloudViewer::utility::random::NormalGenerator< T >::distribution_, cloudViewer::utility::random::GetEngine(), and cloudViewer::utility::random::GetMutex().
Member Data Documentation
distribution_
template<typename T > std::normal_distribution<T> cloudViewer::utility::random::NormalGenerator< T >::distribution_ protected
Definition at line 174 of file Random.h.
Referenced by cloudViewer::utility::random::NormalGenerator< T >::operator()().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/utility/Random.h