ACloudViewer: QCPAxisTickerTime Class Reference
QCPAxisTickerTime Class Reference
Specialized axis ticker for time spans in units of milliseconds to days.
#include <qcustomplot.h>
Public Types
enum TimeUnit {
tuMilliseconds , tuSeconds , tuMinutes , tuHours ,
tuDays
}
Public Types inherited from QCPAxisTicker
enum TickStepStrategy { tssReadability , tssMeetTickCount }
Public Member Functions
QCPAxisTickerTime ()
QString timeFormat () const
int fieldWidth (TimeUnit unit) const
void setTimeFormat (const QString &format)
void setFieldWidth (TimeUnit unit, int width)
Public Member Functions inherited from QCPAxisTicker
QCPAxisTicker ()
virtual ~QCPAxisTicker ()
TickStepStrategy tickStepStrategy () const
int tickCount () const
double tickOrigin () const
void setTickStepStrategy (TickStepStrategy strategy)
void setTickCount (int count)
void setTickOrigin (double origin)
virtual void generate (const QCPRange &range, const QLocale &locale, QChar formatChar, int precision, QVector< double > &ticks, QVector< double > *subTicks, QVector< QString > *tickLabels)
Protected Member Functions
virtual double getTickStep (const QCPRange &range)
virtual int getSubTickCount (double tickStep)
virtual QString getTickLabel (double tick, const QLocale &locale, QChar formatChar, int precision)
void replaceUnit (QString &text, TimeUnit unit, int value) const
Protected Member Functions inherited from QCPAxisTicker
virtual QVector< double > createTickVector (double tickStep, const QCPRange &range)
virtual QVector< double > createSubTickVector (int subTickCount, const QVector< double > &ticks)
virtual QVector< QString > createLabelVector (const QVector< double > &ticks, const QLocale &locale, QChar formatChar, int precision)
void trimTicks (const QCPRange &range, QVector< double > &ticks, bool keepOneOutlier) const
double pickClosest (double target, const QVector< double > &candidates) const
double getMantissa (double input, double *magnitude=0) const
double cleanMantissa (double input) const
Protected Attributes
QString mTimeFormat
QHash< TimeUnit, int > mFieldWidth
TimeUnit mSmallestUnit
TimeUnit mBiggestUnit
QHash< TimeUnit, QString > mFormatPattern
Protected Attributes inherited from QCPAxisTicker
TickStepStrategy mTickStepStrategy
int mTickCount
double mTickOrigin
Detailed Description
Specialized axis ticker for time spans in units of milliseconds to days.
This QCPAxisTicker subclass generates ticks that corresponds to time intervals.
The format of the time display in the tick labels is controlled with setTimeFormat and setFieldWidth. The time coordinate is in the unit of seconds with respect to the time coordinate zero. Unlike with QCPAxisTickerDateTime, the ticks don't correspond to a specific calendar date and time.
The time can be displayed in milliseconds, seconds, minutes, hours and days. Depending on the largest available unit in the format specified with setTimeFormat, any time spans above will be carried in that largest unit. So for example if the format string is "%m:%s" and a tick at coordinate value 7815 (being 2 hours, 10 minutes and 15 seconds) is created, the resulting tick label will show "130:15" (130 minutes, 15 seconds). If the format string is "%h:%m:%s", the hour unit will be used and the label will thus be "02:10:15". Negative times with respect to the axis zero will carry a leading minus sign.
The ticker can be created and assigned to an axis like this:
axistickertime-creation
Here is an example of a time axis providing time information in days, hours and minutes. Due to the axis range spanning a few days and the wanted tick count (setTickCount), the ticker decided to use tick steps of 12 hours:
The format string for this example is
axistickertime-creation-2
Note
If you rather wish to display calendar dates and times, have a look at QCPAxisTickerDateTime instead.
Definition at line 1953 of file qcustomplot.h.
Member Enumeration Documentation
TimeUnit
enum QCPAxisTickerTime::TimeUnit
Defines the logical units in which fractions of time spans can be expressed.
See also
setFieldWidth, setTimeFormat
Enumerator
tuMilliseconds
Milliseconds, one thousandth of a second (%z in setTimeFormat)
tuSeconds
Seconds (%s in setTimeFormat)
tuMinutes
Minutes (%m in setTimeFormat)
tuHours
Hours (%h in setTimeFormat)
tuDays
Days (%d in setTimeFormat)
Definition at line 1962 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPAxisTickerTime()
QCPAxisTickerTime::QCPAxisTickerTime ()
Constructs the ticker and sets reasonable default values. Axis tickers are commonly created managed by a QSharedPointer, which then can be passed to QCPAxis::setTicker.
Definition at line 6288 of file qcustomplot.cpp.
References mFieldWidth, mFormatPattern, QCPAxisTicker::setTickCount(), tuDays, tuHours, tuMilliseconds, tuMinutes, and tuSeconds.
Member Function Documentation
fieldWidth()
int QCPAxisTickerTime::fieldWidth (TimeUnit unit) const inline
Definition at line 1980 of file qcustomplot.h.
getSubTickCount()
int QCPAxisTickerTime::getSubTickCount (double tickStep) protected virtual
Reimplemented from QCPAxisTicker.
Definition at line 6431 of file qcustomplot.cpp.
References QCPAxisTicker::getSubTickCount(), and result.
getTickLabel()
QString QCPAxisTickerTime::getTickLabel (double tick, const QLocale & locale, QChar formatChar, int precision) protected virtual
Reimplemented from QCPAxisTicker.
Definition at line 6478 of file qcustomplot.cpp.
References mBiggestUnit, mSmallestUnit, mTimeFormat, replaceUnit(), result, tuDays, tuHours, tuMilliseconds, tuMinutes, and tuSeconds.
getTickStep()
double QCPAxisTickerTime::getTickStep (const QCPRange & range) protected virtual
Reimplemented from QCPAxisTicker.
Definition at line 6370 of file qcustomplot.cpp.
References QCPAxisTicker::cleanMantissa(), e, mSmallestUnit, QCPAxisTicker::mTickCount, QCPAxisTicker::pickClosest(), result, QCPRange::size(), tuHours, tuMilliseconds, tuMinutes, and tuSeconds.
replaceUnit()
void QCPAxisTickerTime::replaceUnit (QString & text, QCPAxisTickerTime::TimeUnit unit, int value) const protected
Definition at line 6522 of file qcustomplot.cpp.
References mFieldWidth, and mFormatPattern.
Referenced by getTickLabel().
setFieldWidth()
void QCPAxisTickerTime::setFieldWidth (QCPAxisTickerTime::TimeUnit unit, int width)
Sets the field widh of the specified unit to be width digits, when displayed in the tick label. If the number for the specific unit is shorter than width, it will be padded with an according number of zeros to the left in order to reach the field width.
See also
setTimeFormat
Definition at line 6355 of file qcustomplot.cpp.
References mFieldWidth, and width.
setTimeFormat()
void QCPAxisTickerTime::setTimeFormat (const QString & format)
Sets the format that will be used to display time in the tick labels.
The available patterns are:
%z for milliseconds
%s for seconds
%m for minutes
%h for hours
%d for days
The field width (zero padding) can be controlled for each unit with setFieldWidth.
The largest unit that appears in format will carry all the remaining time of a certain tick coordinate, even if it overflows the natural limit of the unit. For example, if %m is the largest unit it might become larger than 59 in order to consume larger time values. If on the other hand %h is available, the minutes will wrap around to zero after 59 and the time will carry to the hour digit.
Definition at line 6326 of file qcustomplot.cpp.
References format, mBiggestUnit, mFormatPattern, mSmallestUnit, mTimeFormat, tuDays, and tuMilliseconds.
timeFormat()
QString QCPAxisTickerTime::timeFormat () const inline
Definition at line 1979 of file qcustomplot.h.
Member Data Documentation
mBiggestUnit
TimeUnit QCPAxisTickerTime::mBiggestUnit protected
Definition at line 1992 of file qcustomplot.h.
Referenced by getTickLabel(), and setTimeFormat().
mFieldWidth
QHash<TimeUnit, int> QCPAxisTickerTime::mFieldWidth protected
Definition at line 1989 of file qcustomplot.h.
Referenced by QCPAxisTickerTime(), replaceUnit(), and setFieldWidth().
mFormatPattern
QHash<TimeUnit, QString> QCPAxisTickerTime::mFormatPattern protected
Definition at line 1993 of file qcustomplot.h.
Referenced by QCPAxisTickerTime(), replaceUnit(), and setTimeFormat().
mSmallestUnit
TimeUnit QCPAxisTickerTime::mSmallestUnit protected
Definition at line 1992 of file qcustomplot.h.
Referenced by getTickLabel(), getTickStep(), and setTimeFormat().
mTimeFormat
QString QCPAxisTickerTime::mTimeFormat protected
Definition at line 1988 of file qcustomplot.h.
Referenced by getTickLabel(), and setTimeFormat().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp