ACloudViewer: PdmsFileSession Class Reference
PdmsFileSession Class Reference
#include <PdmsParser.h>
Public Member Functions
PdmsFileSession (const std::string &filename)
virtual ~PdmsFileSession ()
virtual bool initializeSession () override
virtual void closeSession (bool destroyLoadedObject=false) override
virtual void printWarning (const char *str) override
Public Member Functions inherited from PdmsLexer
PdmsLexer ()
virtual ~PdmsLexer ()
bool gotoNextToken ()
void finish ()
PointCoordinateType valueFromBuffer ()
const char * nameFromBuffer () const
Token getCurrentToken () const
PdmsObjects::GenericItem * getLoadedObject () const
const char * getBufferContent () const
void setLoadedObject (PdmsObjects::GenericItem *o)
Protected Member Functions
virtual void parseCurrentToken () override
virtual bool moveForward () override
virtual void skipComment () override
virtual void skipHandleCommand () override
Protected Member Functions inherited from PdmsLexer
void pushIntoDictionary (const char *str, Token token, int minSize=0)
Protected Attributes
std::string m_filename
int m_currentLine
bool m_eol
bool m_eof
FILE * m_file
Protected Attributes inherited from PdmsLexer
PdmsObjects::GenericItem * loadedObject
Token currentToken
char tokenBuffer [c_max_buff_size]
char nextBuffer [c_max_buff_size]
std::map< std::string, Token > dictionary
bool stop
char metaGroupMask
Additional Inherited Members
Static Protected Attributes inherited from PdmsLexer
static const int c_max_buff_size = 2048
Detailed Description
Definition at line 63 of file PdmsParser.h.
Constructor & Destructor Documentation
PdmsFileSession()
PdmsFileSession::PdmsFileSession (const std::string & filename)
Definition at line 261 of file PdmsParser.cpp.
~PdmsFileSession()
virtual PdmsFileSession::~PdmsFileSession () inline virtual
Definition at line 73 of file PdmsParser.h.
Member Function Documentation
closeSession()
void PdmsFileSession::closeSession (bool destroyLoadedObject = false) override virtual
Reimplemented from PdmsLexer.
Definition at line 280 of file PdmsParser.cpp.
References PdmsLexer::closeSession(), and m_file.
initializeSession()
bool PdmsFileSession::initializeSession () override virtual
Reimplemented from PdmsLexer.
Definition at line 268 of file PdmsParser.cpp.
References PdmsLexer::initializeSession(), m_currentLine, m_eof, m_eol, m_file, and m_filename.
moveForward()
bool PdmsFileSession::moveForward () override protected virtual
Reimplemented from PdmsLexer.
Definition at line 296 of file PdmsParser.cpp.
References PdmsLexer::c_max_buff_size, m_currentLine, m_eof, m_eol, m_file, PdmsLexer::moveForward(), printWarning(), PdmsLexer::tokenBuffer, and upperStr().
parseCurrentToken()
void PdmsFileSession::parseCurrentToken () override protected virtual
Reimplemented from PdmsLexer.
Definition at line 289 of file PdmsParser.cpp.
References PdmsLexer::currentToken, m_eof, PdmsLexer::parseCurrentToken(), PdmsTools::PDMS_EOS, and PdmsLexer::tokenBuffer.
printWarning()
void PdmsFileSession::printWarning (const char * str) override virtual
Implements PdmsLexer.
Definition at line 438 of file PdmsParser.cpp.
References PdmsLexer::currentToken, QtCompat::endl(), m_currentLine, m_filename, PdmsTools::PDMS_EOS, and PdmsLexer::tokenBuffer.
Referenced by moveForward().
skipComment()
void PdmsFileSession::skipComment () override protected virtual
Implements PdmsLexer.
Definition at line 335 of file PdmsParser.cpp.
References PdmsLexer::c_max_buff_size, PdmsLexer::currentToken, m_currentLine, m_eol, m_file, PdmsLexer::metaGroupMask, PdmsTools::PDMS_COMMENT_BLOCK, PdmsTools::PDMS_COMMENT_LINE, PdmsTools::PDMS_ENTER_METAGROUP, PdmsTools::PDMS_LEAVE_METAGROUP, PdmsLexer::tokenBuffer, and upperStr().
skipHandleCommand()
void PdmsFileSession::skipHandleCommand () override protected virtual
Implements PdmsLexer.
Definition at line 414 of file PdmsParser.cpp.
References PdmsTools::c_max_str_length, m_file, and PdmsLexer::tokenBuffer.
Member Data Documentation
m_currentLine
int PdmsFileSession::m_currentLine protected
Definition at line 66 of file PdmsParser.h.
Referenced by initializeSession(), moveForward(), printWarning(), and skipComment().
m_eof
bool PdmsFileSession::m_eof protected
Definition at line 68 of file PdmsParser.h.
Referenced by initializeSession(), moveForward(), and parseCurrentToken().
m_eol
bool PdmsFileSession::m_eol protected
Definition at line 67 of file PdmsParser.h.
Referenced by initializeSession(), moveForward(), and skipComment().
m_file
FILE* PdmsFileSession::m_file protected
Definition at line 69 of file PdmsParser.h.
Referenced by closeSession(), initializeSession(), moveForward(), skipComment(), and skipHandleCommand().
m_filename
std::string PdmsFileSession::m_filename protected
Definition at line 65 of file PdmsParser.h.
Referenced by initializeSession(), and printWarning().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsParser.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsParser.cpp