ACloudViewer: cloudViewer::t::pipelines::registration::TransformationEstimationPointToPoint Class Reference
cloudViewer::t::pipelines::registration::TransformationEstimationPointToPoint Class Reference
#include <TransformationEstimation.h>
Public Member Functions
TransformationEstimationPointToPoint ()
~TransformationEstimationPointToPoint () override
TransformationEstimationType GetTransformationEstimationType () const override
double ComputeRMSE (const geometry::PointCloud &source, const geometry::PointCloud &target, const core::Tensor &correspondences) const override
Computes RMSE (double) for PointToPoint method, between two pointclouds, given correspondences.
core::Tensor ComputeTransformation (const geometry::PointCloud &source, const geometry::PointCloud &target, const core::Tensor &correspondences, const core::Tensor &current_transform=core::Tensor::Eye(4, core::Float64, core::Device("CPU:0")), const std::size_t iteration=0) const override
Estimates the transformation matrix for PointToPoint method, a tensor of shape {4, 4}, and dtype Float64 on CPU device.
Public Member Functions inherited from cloudViewer::t::pipelines::registration::TransformationEstimation
TransformationEstimation ()
Default Constructor.
virtual ~TransformationEstimation ()
Detailed Description
Class to estimate a transformation matrix tensor of shape {4, 4}, dtype Float64, on CPU device for point to point distance.
Definition at line 101 of file TransformationEstimation.h.
Constructor & Destructor Documentation
TransformationEstimationPointToPoint()
cloudViewer::t::pipelines::registration::TransformationEstimationPointToPoint::TransformationEstimationPointToPoint () inline
Definition at line 104 of file TransformationEstimation.h.
~TransformationEstimationPointToPoint()
cloudViewer::t::pipelines::registration::TransformationEstimationPointToPoint::~TransformationEstimationPointToPoint () inline override
Definition at line 105 of file TransformationEstimation.h.
Member Function Documentation
ComputeRMSE()
double cloudViewer::t::pipelines::registration::TransformationEstimationPointToPoint::ComputeRMSE (const geometry::PointCloud & source, const geometry::PointCloud & target, const core::Tensor & correspondences) const override virtual
Computes RMSE (double) for PointToPoint method, between two pointclouds, given correspondences.
Parameters
source Source pointcloud. (Float32 or Float64 type).
target Target pointcloud. (Float32 or Float64 type).
correspondences Tensor of type Int64 containing indices of corresponding target points, where the value is the target index and the index of the value itself is the source index. It contains -1 as value at index with no correspondence.
Implements cloudViewer::t::pipelines::registration::TransformationEstimation.
Definition at line 39 of file TransformationEstimation.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, cloudViewer::t::pipelines::registration::AssertValidCorrespondences(), error(), cloudViewer::core::Float64, cloudViewer::t::geometry::PointCloud::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointPositions(), cloudViewer::core::Tensor::IndexGet(), LogError, cloudViewer::core::Tensor::Mul_(), cloudViewer::core::Tensor::Ne(), cloudViewer::core::Tensor::Reshape(), cloudViewer::core::Tensor::Sum(), and cloudViewer::t::geometry::kernel::image::To().
ComputeTransformation()
core::Tensor cloudViewer::t::pipelines::registration::TransformationEstimationPointToPoint::ComputeTransformation (const geometry::PointCloud & source, const geometry::PointCloud & target, const core::Tensor & correspondences, const core::Tensor & current_transform = core::Tensor::Eye(4, core::Float64, core::Device("CPU:0")), const std::size_t iteration = 0) const override virtual
Estimates the transformation matrix for PointToPoint method, a tensor of shape {4, 4}, and dtype Float64 on CPU device.
Parameters
source Source pointcloud. (Float32 or Float64 type).
target Target pointcloud. (Float32 or Float64 type).
correspondences Tensor of type Int64 containing indices of corresponding target points, where the value is the target index and the index of the value itself is the source index. It contains -1 as value at index with no correspondence.
current_transform The current pose estimate of ICP.
iteration The current iteration number of the ICP algorithm.
Returns
transformation between source to target, a tensor of shape {4, 4}, type Float64 on CPU device.
Implements cloudViewer::t::pipelines::registration::TransformationEstimation.
Definition at line 70 of file TransformationEstimation.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, cloudViewer::t::pipelines::registration::AssertValidCorrespondences(), cloudViewer::t::pipelines::kernel::ComputeRtPointToPoint(), cloudViewer::t::geometry::PointCloud::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointPositions(), LogError, and cloudViewer::t::pipelines::kernel::RtToTransformation().
GetTransformationEstimationType()
TransformationEstimationType cloudViewer::t::pipelines::registration::TransformationEstimationPointToPoint::GetTransformationEstimationType () const inline override virtual
Implements cloudViewer::t::pipelines::registration::TransformationEstimation.
Definition at line 108 of file TransformationEstimation.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/t/pipelines/registration/TransformationEstimation.h
/root/ACloudViewer/libs/cloudViewer/t/pipelines/registration/TransformationEstimation.cpp