ACloudViewer: ScalarDialog Class Reference
ScalarDialog Class Reference
#include <ScalarDialog.h>
Public Slots
void pickPoint_first (bool)
void pickPoint_second (bool)
Public Member Functions
ScalarDialog (ccPickingHub *pickingHub, QWidget *parent=nullptr)
virtual void onItemPicked (const PickedItem &pi)
Inherited from ccPickingListener.
Public Member Functions inherited from ccPickingListener
virtual ~ccPickingListener ()=default
Protected Attributes
QWidget * m_pickingWin
Picking window (if any)
ccPickingHub * m_pickingHub
Picking hub.
Detailed Description
Definition at line 38 of file ScalarDialog.h.
Constructor & Destructor Documentation
ScalarDialog()
ScalarDialog::ScalarDialog (ccPickingHub * pickingHub, QWidget * parent = nullptr) explicit
Definition at line 20 of file ScalarDialog.cpp.
References pickPoint_first(), and pickPoint_second().
Member Function Documentation
onItemPicked()
void ScalarDialog::onItemPicked (const PickedItem & pi) virtual
Inherited from ccPickingListener.
Implements ccPickingListener.
Definition at line 92 of file ScalarDialog.cpp.
References ccPickingHub::activeWindow(), ccPickingListener::PickedItem::entity, cloudViewer::GenericCloud::getPointScalarValue(), ccDrawableObject::hasScalarFields(), ccObject::isKindOf(), ccPickingListener::PickedItem::itemIndex, m_pickingHub, m_pickingWin, CV_TYPES::POINT_CLOUD, and CVLog::Print().
pickPoint_first
void ScalarDialog::pickPoint_first (bool state) slot
Definition at line 48 of file ScalarDialog.cpp.
References ccPickingHub::addListener(), CVLog::Error(), m_pickingHub, and ccPickingHub::removeListener().
Referenced by ScalarDialog().
pickPoint_second
void ScalarDialog::pickPoint_second (bool state) slot
Definition at line 70 of file ScalarDialog.cpp.
References ccPickingHub::addListener(), CVLog::Error(), m_pickingHub, and ccPickingHub::removeListener().
Referenced by ScalarDialog().
Member Data Documentation
m_pickingHub
ccPickingHub* ScalarDialog::m_pickingHub protected
Picking hub.
Definition at line 57 of file ScalarDialog.h.
Referenced by onItemPicked(), pickPoint_first(), and pickPoint_second().
m_pickingWin
QWidget* ScalarDialog::m_pickingWin protected
Picking window (if any)
Definition at line 54 of file ScalarDialog.h.
Referenced by onItemPicked().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qColorimetricSegmenter/ScalarDialog.h
/root/ACloudViewer/plugins/core/Standard/qColorimetricSegmenter/ScalarDialog.cpp