ACloudViewer: ccInnerRect2DFinder Class Reference
ccInnerRect2DFinder Class Reference
Finds a the biggets enclosed rectangle in a point cloud (2D)
#include <ecvInnerRect2DFinder.h>
Classes
struct Rect
2D rectangle
Public Member Functions
ccInnerRect2DFinder ()
Default constructor.
ccBox * process (ccGenericPointCloud *cloud, unsigned char zDim=2)
Finds the biggest enclosed rectangle.
Protected Member Functions
bool init (ccGenericPointCloud *cloud, unsigned char zDim)
Initializes internal structures.
void findBiggestRect (const Rect &rect, unsigned startIndex)
Internal processs.
Protected Attributes
Rect m_boundingRect
Global rectangle.
Rect m_maxRect
Inner rectangle.
double m_maxArea
Inner rectangle max area.
ccGenericPointCloud * m_cloud
Associated cloud.
unsigned char m_X
X dimension.
unsigned char m_Y
Y dimension.
Detailed Description
Finds a the biggets enclosed rectangle in a point cloud (2D)
Definition at line 15 of file ecvInnerRect2DFinder.h.
Constructor & Destructor Documentation
ccInnerRect2DFinder()
ccInnerRect2DFinder::ccInnerRect2DFinder ()
Default constructor.
Definition at line 16 of file ecvInnerRect2DFinder.cpp.
Member Function Documentation
findBiggestRect()
void ccInnerRect2DFinder::findBiggestRect (const Rect & rect, unsigned startIndex) protected
Internal processs.
Definition at line 100 of file ecvInnerRect2DFinder.cpp.
References ccInnerRect2DFinder::Rect::area(), cloudViewer::GenericIndexedCloud::getPoint(), m_cloud, m_maxArea, m_maxRect, m_X, m_Y, cloudViewer::GenericCloud::size(), Tuple3Tpl< Type >::u, rect::x1, and rect::y1.
Referenced by process().
init()
bool ccInnerRect2DFinder::init (ccGenericPointCloud * cloud, unsigned char zDim) protected
Initializes internal structures.
Definition at line 52 of file ecvInnerRect2DFinder.cpp.
References CVLog::Error(), ccGenericPointCloud::getOwnBB(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::BoundingBoxTpl< T >::isValid(), m_boundingRect, m_cloud, m_X, m_Y, cloudViewer::GenericCloud::size(), Tuple3Tpl< Type >::u, X, ccInnerRect2DFinder::Rect::x0, ccInnerRect2DFinder::Rect::x1, ccInnerRect2DFinder::Rect::y0, and ccInnerRect2DFinder::Rect::y1.
Referenced by process().
process()
ccBox * ccInnerRect2DFinder::process (ccGenericPointCloud * cloud, unsigned char zDim = 2)
Finds the biggest enclosed rectangle.
Definition at line 19 of file ecvInnerRect2DFinder.cpp.
References findBiggestRect(), cloudViewer::BoundingBoxTpl< T >::getCenter(), cloudViewer::BoundingBoxTpl< T >::getDiagVec(), ccGenericPointCloud::getOwnBB(), ccInnerRect2DFinder::Rect::height(), init(), cloudViewer::BoundingBoxTpl< T >::isValid(), m_boundingRect, m_maxArea, m_maxRect, m_X, m_Y, ccGLMatrixTpl< T >::setTranslation(), Tuple3Tpl< Type >::u, ccInnerRect2DFinder::Rect::width(), ccInnerRect2DFinder::Rect::x0, ccInnerRect2DFinder::Rect::x1, ccInnerRect2DFinder::Rect::y0, and ccInnerRect2DFinder::Rect::y1.
Member Data Documentation
m_boundingRect
Rect ccInnerRect2DFinder::m_boundingRect protected
Global rectangle.
Definition at line 44 of file ecvInnerRect2DFinder.h.
Referenced by init(), and process().
m_cloud
ccGenericPointCloud* ccInnerRect2DFinder::m_cloud protected
Associated cloud.
Definition at line 52 of file ecvInnerRect2DFinder.h.
Referenced by findBiggestRect(), and init().
m_maxArea
double ccInnerRect2DFinder::m_maxArea protected
Inner rectangle max area.
Definition at line 49 of file ecvInnerRect2DFinder.h.
Referenced by findBiggestRect(), and process().
m_maxRect
Rect ccInnerRect2DFinder::m_maxRect protected
Inner rectangle.
Definition at line 47 of file ecvInnerRect2DFinder.h.
Referenced by findBiggestRect(), and process().
m_X
unsigned char ccInnerRect2DFinder::m_X protected
X dimension.
Definition at line 55 of file ecvInnerRect2DFinder.h.
Referenced by findBiggestRect(), init(), and process().
m_Y
unsigned char ccInnerRect2DFinder::m_Y protected
Y dimension.
Definition at line 57 of file ecvInnerRect2DFinder.h.
Referenced by findBiggestRect(), init(), and process().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvInnerRect2DFinder.h
/root/ACloudViewer/app/ecvInnerRect2DFinder.cpp