ACloudViewer: vtkUndoSet Class Reference
vtkUndoSet Class Reference
#include <vtkUndoSet.h>
Public Member Functions
vtkTypeMacro (vtkUndoSet, vtkObject)
void PrintSelf (ostream &os, vtkIndent indent) override
virtual int Undo ()
virtual int Redo ()
int AddElement (vtkUndoElement *elem)
void RemoveElement (int index)
vtkUndoElement * GetElement (int index)
void RemoveAllElements ()
int GetNumberOfElements ()
Static Public Member Functions
static vtkUndoSet * New ()
Protected Member Functions
vtkUndoSet ()
~vtkUndoSet () override
Protected Attributes
vtkCollection * Collection
vtkCollection * TmpWorkingCollection
Detailed Description
Definition at line 17 of file vtkUndoSet.h.
Constructor & Destructor Documentation
vtkUndoSet()
vtkUndoSet::vtkUndoSet () protected
Definition at line 25 of file vtkUndoSet.cxx.
References Collection, and TmpWorkingCollection.
~vtkUndoSet()
vtkUndoSet::~vtkUndoSet () override protected
Definition at line 32 of file vtkUndoSet.cxx.
References Collection, and TmpWorkingCollection.
Member Function Documentation
AddElement()
int vtkUndoSet::AddElement (vtkUndoElement * elem)
Add an element to this set. If the newly added element, elem, and the most recently added element are both Mergeable, then an attempt is made to merge the new element with the previous one. On successful merging, the new element is discarded, otherwise it is appended to the set.
Returns
the index at which the element got added/merged.
Definition at line 39 of file vtkUndoSet.cxx.
References Collection, and vtkUndoElement::Merge().
GetElement()
vtkUndoElement * vtkUndoSet::GetElement (int index)
Get an element at a particular index
Definition at line 67 of file vtkUndoSet.cxx.
References Collection.
GetNumberOfElements()
int vtkUndoSet::GetNumberOfElements ()
Get number of elements in the set.
Definition at line 79 of file vtkUndoSet.cxx.
References Collection.
New()
static vtkUndoSet* vtkUndoSet::New () static
PrintSelf()
void vtkUndoSet::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 149 of file vtkUndoSet.cxx.
Redo()
int vtkUndoSet::Redo () virtual
Perform a Redo.
Definition at line 85 of file vtkUndoSet.cxx.
References Collection, vtkUndoElement::Redo(), vtkUndoElement::SetUndoSetWorkingContext(), TmpWorkingCollection, and vtkUndoElement::Undo().
RemoveAllElements()
void vtkUndoSet::RemoveAllElements ()
Remove all elemments.
Definition at line 73 of file vtkUndoSet.cxx.
References Collection.
RemoveElement()
void vtkUndoSet::RemoveElement (int index)
Remove an element at a particular index.
Definition at line 61 of file vtkUndoSet.cxx.
References Collection.
Undo()
int vtkUndoSet::Undo () virtual
Perform an Undo.
Definition at line 117 of file vtkUndoSet.cxx.
References Collection, vtkUndoElement::Redo(), vtkUndoElement::SetUndoSetWorkingContext(), TmpWorkingCollection, and vtkUndoElement::Undo().
vtkTypeMacro()
vtkUndoSet::vtkTypeMacro (vtkUndoSet , vtkObject)
Member Data Documentation
Collection
vtkCollection* vtkUndoSet::Collection protected
Definition at line 67 of file vtkUndoSet.h.
Referenced by AddElement(), GetElement(), GetNumberOfElements(), Redo(), RemoveAllElements(), RemoveElement(), Undo(), vtkUndoSet(), and ~vtkUndoSet().
TmpWorkingCollection
vtkCollection* vtkUndoSet::TmpWorkingCollection protected
Definition at line 68 of file vtkUndoSet.h.
Referenced by Redo(), Undo(), vtkUndoSet(), and ~vtkUndoSet().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkUndoSet.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkUndoSet.cxx