ACloudViewer: cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP Class Reference
cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP Class Reference
#include <TransformationEstimation.h>
Public Member Functions
~TransformationEstimationForColoredICP () override
TransformationEstimationForColoredICP (double lambda_geometric=0.968, const RobustKernel &kernel=RobustKernel(RobustKernelMethod::L2Loss, 1.0, 1.0))
Constructor.
TransformationEstimationType GetTransformationEstimationType () const override
double ComputeRMSE (const geometry::PointCloud &source, const geometry::PointCloud &target, const core::Tensor &correspondences) const override
Computes RMSE (double) for ColoredICP method, between two pointclouds, given correspondences.
core::Tensor ComputeTransformation (const geometry::PointCloud &source, const geometry::PointCloud &target, const core::Tensor &correspondences, const core::Tensor &current_transform=core::Tensor::Eye(4, core::Float64, core::Device("CPU:0")), const std::size_t iteration=0) const override
Estimates the transformation matrix for ColoredICP method, a tensor of shape {4, 4}, and dtype Float64 on CPU device.
Public Member Functions inherited from cloudViewer::t::pipelines::registration::TransformationEstimation
TransformationEstimation ()
Default Constructor.
virtual ~TransformationEstimation ()
Public Attributes
double lambda_geometric_ = 0.968
RobustKernel kernel_ = RobustKernel(RobustKernelMethod::L2Loss, 1.0, 1.0)
RobustKernel for outlier rejection.
Detailed Description
This is implementation of following paper J. Park, Q.-Y. Zhou, V. Koltun, Colored Point Cloud Registration Revisited, ICCV 2017.
Class to estimate a transformation matrix tensor of shape {4, 4}, dtype Float64, on CPU device for colored-icp method.
Definition at line 227 of file TransformationEstimation.h.
Constructor & Destructor Documentation
~TransformationEstimationForColoredICP()
cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP::~TransformationEstimationForColoredICP () inline override
Definition at line 229 of file TransformationEstimation.h.
TransformationEstimationForColoredICP()
cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP::TransformationEstimationForColoredICP (double lambda_geometric = 0.968, const RobustKernel & kernel = RobustKernel(RobustKernelMethod::L2Loss, 1.0, 1.0)) inline explicit
Constructor.
Parameters
lamda_geometric λ ∈ [0,1] in the overall energy λEG + (1−λ)EC. Refer the documentation of Colored-ICP for more information.
kernel (optional) Any of the implemented statistical robust kernel for outlier rejection.
Definition at line 237 of file TransformationEstimation.h.
References lambda_geometric_.
Member Function Documentation
ComputeRMSE()
double cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP::ComputeRMSE (const geometry::PointCloud & source, const geometry::PointCloud & target, const core::Tensor & correspondences) const override virtual
Computes RMSE (double) for ColoredICP method, between two pointclouds, given correspondences.
Parameters
source Source pointcloud. (Float32 or Float64 type).
target Target pointcloud. (Float32 or Float64 type). It must contain normals, colors and color_gradients of the same shape and dtype as the positions.
correspondences Tensor of type Int64 containing indices of corresponding target points, where the value is the target index and the index of the value itself is the source index. It contains -1 as value at index with no correspondence.
Implements cloudViewer::t::pipelines::registration::TransformationEstimation.
Definition at line 167 of file TransformationEstimation.cpp.
References Add(), cloudViewer::core::Tensor::Add_(), AssertTensorDevice, AssertTensorDtype, AssertTensorShape, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointColors(), cloudViewer::t::geometry::PointCloud::GetPointNormals(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointAttr(), cloudViewer::t::geometry::PointCloud::HasPointColors(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), cloudViewer::t::geometry::PointCloud::HasPointPositions(), cloudViewer::core::Tensor::IndexGet(), cloudViewer::core::Int64, lambda_geometric_, LogError, cloudViewer::core::Tensor::Mean(), cloudViewer::core::Tensor::Mul(), cloudViewer::core::Tensor::Ne(), cloudViewer::core::Tensor::Reshape(), cloudViewer::core::Tensor::Sum(), and cloudViewer::t::geometry::kernel::image::To().
ComputeTransformation()
core::Tensor cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP::ComputeTransformation (const geometry::PointCloud & source, const geometry::PointCloud & target, const core::Tensor & correspondences, const core::Tensor & current_transform = core::Tensor::Eye(4, core::Float64, core::Device("CPU:0")), const std::size_t iteration = 0) const override virtual
Estimates the transformation matrix for ColoredICP method, a tensor of shape {4, 4}, and dtype Float64 on CPU device.
Parameters
source Source pointcloud. (Float32 or Float64 type).
target Target pointcloud. (Float32 or Float64 type). It must contain normals, colors and color_gradients of the same shape and dtype as the positions.
correspondences Tensor of type Int64 containing indices of corresponding target points, where the value is the target index and the index of the value itself is the source index. It contains -1 as value at index with no correspondence.
current_transform The current pose estimate of ICP.
iteration The current iteration number of the ICP algorithm.
Returns
transformation between source to target, a tensor of shape {4, 4}, type Float64 on CPU device.
Implements cloudViewer::t::pipelines::registration::TransformationEstimation.
Definition at line 255 of file TransformationEstimation.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, cloudViewer::t::pipelines::registration::AssertValidCorrespondences(), cloudViewer::t::pipelines::kernel::ComputePoseColoredICP(), cloudViewer::t::geometry::PointCloud::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointColors(), cloudViewer::t::geometry::PointCloud::GetPointNormals(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointAttr(), cloudViewer::t::geometry::PointCloud::HasPointColors(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), cloudViewer::t::geometry::PointCloud::HasPointPositions(), LogError, and cloudViewer::t::pipelines::kernel::PoseToTransformation().
GetTransformationEstimationType()
TransformationEstimationType cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP::GetTransformationEstimationType () const inline override virtual
Implements cloudViewer::t::pipelines::registration::TransformationEstimation.
Definition at line 247 of file TransformationEstimation.h.
Member Data Documentation
kernel_
RobustKernel cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP::kernel_ = RobustKernel(RobustKernelMethod::L2Loss, 1.0, 1.0)
RobustKernel for outlier rejection.
Definition at line 294 of file TransformationEstimation.h.
lambda_geometric_
double cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP::lambda_geometric_ = 0.968
Definition at line 292 of file TransformationEstimation.h.
Referenced by ComputeRMSE(), and TransformationEstimationForColoredICP().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/t/pipelines/registration/TransformationEstimation.h
/root/ACloudViewer/libs/cloudViewer/t/pipelines/registration/TransformationEstimation.cpp