ACloudViewer: ccDBRoot Class Reference
ccDBRoot Class Reference
GUI database tree root.
#include <ecvDBRoot.h>
Public Slots
void changeSelection (const QItemSelection &selected, const QItemSelection &deselected)
void reflectObjectPropChange (ccHObject *obj)
void redrawCCObject (ccHObject *object, bool forceRedraw=true)
void redrawCCObjectAndChildren (ccHObject *object, bool forceRedraw=true)
void updateCCObject (ccHObject *object)
void deleteSelectedEntities ()
void selectEntity (ccHObject *obj, bool forceAdditiveSelection=false)
Selects a given entity.
void selectEntities (std::unordered_set< int > entIDs)
Selects multiple entities at once (shortcut to the other version)
void selectEntities (const ccHObject::Container &entities, bool incremental=false)
Selects multiple entities at once.
Signals
void selectionChanged ()
void dbIsEmpty ()
void dbIsNotEmptyAnymore ()
Public Member Functions
ccDBRoot (ccCustomQTreeView *dbTreeWidget, QTreeView *propertiesTreeWidget, QObject *parent=nullptr)
Default constructor.
virtual ~ccDBRoot () override
Destructor.
void hide ()
void show ()
ccHObject * getRootEntity ()
Returns associated root object.
void hidePropertiesView ()
Hides properties view.
void updatePropertiesView ()
Updates properties view.
ccPropertiesTreeDelegate * getPropertiesDelegate ()
Get properties tree delegate.
void addElement (ccHObject *object, bool autoExpand=true)
Adds an element to the DB tree.
void removeElement (ccHObject *object)
Removes an element from the DB tree.
void removeElements (ccHObject::Container &objects)
Removes several elements at once from the DB tree.
ccHObject * find (int uniqueID) const
Finds an element in DB.
int countSelectedEntities (CV_CLASS_ENUM filter=CV_TYPES::OBJECT)
size_t getSelectedEntities (ccHObject::Container &selectedEntities, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, dbTreeSelectionInfo *info=nullptr)
void expandElement (ccHObject *object, bool state)
Expands tree at a given node.
void unselectEntity (ccHObject *obj)
Unselects a given entity.
void unselectAllEntities ()
Unselects all entities.
void unloadAll ()
Unloads all entities.
virtual QVariant data (const QModelIndex &index, int role) const override
virtual QModelIndex index (int row, int column, const QModelIndex &parentIndex=QModelIndex()) const override
QModelIndex index (ccHObject *object)
virtual QModelIndex parent (const QModelIndex &index) const override
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const override
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const override
virtual Qt::ItemFlags flags (const QModelIndex &index) const override
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
virtual Qt::DropActions supportedDropActions () const override
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) override
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const override
virtual Qt::DropActions supportedDragActions () const override
Protected Types
enum TOGGLE_PROPERTY {
TG_ENABLE , TG_VISIBLE , TG_COLOR , TG_SF ,
TG_NORMAL , TG_MATERIAL , TG_3D_NAME
}
Entity property that can be toggled.
enum SortRules { SORT_A2Z , SORT_Z2A , SORT_BY_TYPE }
Entities sorting schemes.
Protected Slots
void showContextMenu (const QPoint &)
void expandBranch ()
void collapseBranch ()
void gatherRecursiveInformation ()
void sortChildrenAZ ()
void sortChildrenZA ()
void sortChildrenType ()
void selectByTypeAndName ()
void exportImages ()
void toggleSelectedEntities ()
void toggleSelectedEntitiesVisibility ()
void toggleSelectedEntitiesColor ()
void toggleSelectedEntitiesNormals ()
void toggleSelectedEntitiesSF ()
void toggleSelectedEntitiesMat ()
void toggleSelectedEntities3DName ()
void addEmptyGroup ()
void alignCameraWithEntityDirect ()
void alignCameraWithEntityIndirect ()
void enableBubbleViewMode ()
void editLabelScalarValue ()
Protected Member Functions
void toggleSelectedEntitiesProperty (TOGGLE_PROPERTY prop)
void alignCameraWithEntity (bool reverse)
Aligns the camera with the currently selected entity.
void showPropertiesView (ccHObject *obj)
Shows properties view for a given element.
void sortSelectedEntitiesChildren (SortRules rule)
Sorts selected entities children.
void expandOrCollapseHoveredBranch (bool expand)
Expands or collapses hovered item.
void selectChildrenByTypeAndName (CV_CLASS_ENUM type, bool typeIsExclusive=true, QString name=QString(), bool nameIsRegex=false)
Selects objects by type and/or name.
Protected Attributes
ccHObject * m_treeRoot
Associated DB root.
QTreeView * m_dbTreeWidget
Associated widget for DB tree.
QTreeView * m_propertiesTreeWidget
Associated widget for selected entity's properties tree.
QStandardItemModel * m_propertiesModel
Selected entity's properties data model.
ccPropertiesTreeDelegate * m_ccPropDelegate
Selected entity's properties delegate.
QAction * m_expandBranch
Context menu action: expand tree branch.
QAction * m_collapseBranch
Context menu action: collapse tree branch.
QAction * m_gatherInformation
Context menu action: gather (recursive) information on selected entities.
QAction * m_sortChildrenAZ
Context menu action: sort children in alphabetical order.
QAction * m_sortChildrenZA
Context menu action: sort children in reverse alphabetical order.
QAction * m_sortChildrenType
Context menu action: sort children by type.
QAction * m_selectByTypeAndName
Context menu action: select object by type and/or by name.
QAction * m_exportImages
Context menu action: export images.
QAction * m_deleteSelectedEntities
Context menu action: delete selected entities.
QAction * m_toggleSelectedEntities
Context menu action: enabled/disable selected entities.
QAction * m_toggleSelectedEntitiesVisibility
Context menu action: hide/show selected entities.
QAction * m_toggleSelectedEntitiesColor
Context menu action: hide/show selected entities color.
QAction * m_toggleSelectedEntitiesNormals
Context menu action: hide/show selected entities normals.
QAction * m_toggleSelectedEntitiesMat
Context menu action: hide/show selected entities materials/textures.
QAction * m_toggleSelectedEntitiesSF
Context menu action: hide/show selected entities SF.
QAction * m_toggleSelectedEntities3DName
Context menu action: hide/show selected entities 3D name.
QAction * m_addEmptyGroup
Context menu action: add empty group.
QAction * m_alignCameraWithEntity
Context menu action: use 3-points labels or planes to orient camera.
QAction * m_alignCameraWithEntityReverse
Context menu action: reverse of m_alignCameraWithEntity.
QAction * m_enableBubbleViewMode
Context menu action: enable bubble-view (on a sensor)
QAction * m_editLabelScalarValue
Context menu action: change current scalar value (via a 2D label)
QPoint m_contextMenuPos
Last context menu pos.
Detailed Description
GUI database tree root.
Definition at line 65 of file ecvDBRoot.h.
Member Enumeration Documentation
SortRules
enum ccDBRoot::SortRules protected
Entities sorting schemes.
Enumerator
SORT_A2Z
SORT_Z2A
SORT_BY_TYPE
Definition at line 268 of file ecvDBRoot.h.
TOGGLE_PROPERTY
enum ccDBRoot::TOGGLE_PROPERTY protected
Entity property that can be toggled.
Enumerator
TG_ENABLE
TG_VISIBLE
TG_COLOR
TG_SF
TG_NORMAL
TG_MATERIAL
TG_3D_NAME
Definition at line 198 of file ecvDBRoot.h.
Constructor & Destructor Documentation
ccDBRoot()
ccDBRoot::ccDBRoot (ccCustomQTreeView * dbTreeWidget, QTreeView * propertiesTreeWidget, QObject * parent = nullptr)
Default constructor.
Parameters
dbTreeWidget widget for DB tree display
propertiesTreeWidget widget for selected entity's properties tree display
parent widget QObject parent
Definition at line 262 of file ecvDBRoot.cpp.
References addEmptyGroup(), alignCameraWithEntityDirect(), alignCameraWithEntityIndirect(), ccPropertiesTreeDelegate::ccObjectAndChildrenAppearanceChanged(), ccPropertiesTreeDelegate::ccObjectAppearanceChanged(), ccPropertiesTreeDelegate::ccObjectPropertiesChanged(), changeSelection(), collapseBranch(), deleteSelectedEntities(), editLabelScalarValue(), enableBubbleViewMode(), expandBranch(), exportImages(), gatherRecursiveInformation(), redrawCCObject(), redrawCCObjectAndChildren(), selectByTypeAndName(), showContextMenu(), sortChildrenAZ(), sortChildrenType(), sortChildrenZA(), toggleSelectedEntities(), toggleSelectedEntities3DName(), toggleSelectedEntitiesColor(), toggleSelectedEntitiesMat(), toggleSelectedEntitiesNormals(), toggleSelectedEntitiesSF(), toggleSelectedEntitiesVisibility(), and updateCCObject().
~ccDBRoot()
ccDBRoot::~ccDBRoot () override virtual
Destructor.
Definition at line 382 of file ecvDBRoot.cpp.
References m_ccPropDelegate, m_propertiesModel, and m_treeRoot.
Member Function Documentation
addElement()
void ccDBRoot::addElement (ccHObject * object, bool autoExpand = true)
Adds an element to the DB tree.
Definition at line 423 of file ecvDBRoot.cpp.
References ccHObject::addChild(), dbIsNotEmptyAnymore(), ccHObject::getChildIndex(), ccHObject::getChildrenNumber(), ccHObject::getParent(), index(), m_dbTreeWidget, and m_treeRoot.
Referenced by addEmptyGroup(), MainWindow::addToDB(), dropMimeData(), and MainWindow::putObjectBackIntoDBTree().
addEmptyGroup
void ccDBRoot::addEmptyGroup () protected slot
Definition at line 2074 of file ecvDBRoot.cpp.
References addElement(), index(), m_contextMenuPos, m_dbTreeWidget, and parent().
Referenced by ccDBRoot().
alignCameraWithEntity()
void ccDBRoot::alignCameraWithEntity (bool reverse) protected
Aligns the camera with the currently selected entity.
Parameters
reverse whether to use the entity's normal (false) or its inverse (true)
Definition at line 1628 of file ecvDBRoot.cpp.
References cc2DLabel::PickedPoint::cloud, cloudViewer::CCMiscTools::ComputeBaseVectors(), cross(), CV_TYPES::FACET, Vector3Tpl< double >::fromArray(), ccHObject::getBB_recursive(), cloudViewer::BoundingBoxTpl< T >::getCenter(), ccGLMatrixTpl< T >::getColumnAsVec3D(), ccFacet::getNormal(), ccPlane::getNormal(), ccMesh::getOwnBB(), cc2DLabel::getPickedPoint(), cloudViewer::GenericIndexedCloud::getPoint(), ccGenericPrimitive::getTransformation(), cc2DLabel::PickedPoint::index, ccObject::isA(), CV_TYPES::LABEL_2D, m_dbTreeWidget, CV_TYPES::PLANE, CVLog::Print(), ccGLMatrixTpl< T >::setTranslation(), cc2DLabel::size(), and Tuple3Tpl< Type >::u.
Referenced by alignCameraWithEntityDirect(), and alignCameraWithEntityIndirect().
alignCameraWithEntityDirect
void ccDBRoot::alignCameraWithEntityDirect () inline protected slot
Definition at line 247 of file ecvDBRoot.h.
References alignCameraWithEntity().
Referenced by ccDBRoot().
alignCameraWithEntityIndirect
void ccDBRoot::alignCameraWithEntityIndirect () inline protected slot
Definition at line 248 of file ecvDBRoot.h.
References alignCameraWithEntity().
Referenced by ccDBRoot().
changeSelection
void ccDBRoot::changeSelection (const QItemSelection & selected, const QItemSelection & deselected) slot
Definition at line 999 of file ecvDBRoot.cpp.
References MainWindow::refreshAll(), selectionChanged(), ecvDisplayTools::SetRedrawRecursive(), ccDrawableObject::setSelected(), MainWindow::TheInstance(), and updatePropertiesView().
Referenced by ccDBRoot().
collapseBranch
void ccDBRoot::collapseBranch () protected slot
Definition at line 1588 of file ecvDBRoot.cpp.
References expandOrCollapseHoveredBranch().
Referenced by ccDBRoot().
columnCount()
int ccDBRoot::columnCount (const QModelIndex & parent = QModelIndex()) const override virtual
Definition at line 994 of file ecvDBRoot.cpp.
References parent().
countSelectedEntities()
int ccDBRoot::countSelectedEntities (CV_CLASS_ENUM filter = CV_TYPES::OBJECT)
Returns the number of selected entities in DB tree (optionally with a given type)
Definition at line 1256 of file ecvDBRoot.cpp.
References ccObject::isKindOf(), m_dbTreeWidget, and CV_TYPES::OBJECT.
data()
QVariant ccDBRoot::data (const QModelIndex & index, int role) const override virtual
Definition at line 690 of file ecvDBRoot.cpp.
References count, ccHObject::filterChildren(), ccHObject::getChildCountRecursive(), ccHObject::getChildrenNumber(), ccHObject::getClassID(), ccHObject::getIcon(), ccObject::getName(), CV_TYPES::HIERARCHY_OBJECT, index(), ccObject::isA(), ccObject::isEnabled(), ccObject::isLocked(), CV_TYPES::LABEL_2D, and CV_TYPES::VIEWPORT_2D_LABEL.
Referenced by dropMimeData().
dbIsEmpty
void ccDBRoot::dbIsEmpty () signal
Referenced by deleteSelectedEntities(), removeElement(), removeElements(), and unloadAll().
dbIsNotEmptyAnymore
void ccDBRoot::dbIsNotEmptyAnymore () signal
Referenced by addElement().
deleteSelectedEntities
void ccDBRoot::deleteSelectedEntities () slot
Definition at line 593 of file ecvDBRoot.cpp.
References CanDetachCloud(), dbIsEmpty(), ccGenericMesh::getAssociatedCloud(), ccHObject::getChildrenNumber(), ccObject::getName(), ccHObject::getParent(), hidePropertiesView(), index(), ccHObject::isAncestorOf(), ccObject::isKindOf(), ccObject::isLocked(), m_dbTreeWidget, m_treeRoot, CV_TYPES::MESH, parent(), CV_TYPES::POINT_CLOUD, MainWindow::refreshAll(), ecvDisplayTools::SetRedrawRecursive(), ecvDisplayTools::SetRemoveViewIDs(), MainWindow::TheInstance(), ccHObjectCaster::ToGenericMesh(), updatePropertiesView(), and CVLog::Warning().
Referenced by ccDBRoot().
dropMimeData()
bool ccDBRoot::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) override virtual
Definition at line 1401 of file ecvDBRoot.cpp.
References ccHObject::addChild(), ccHObject::addDependency(), addElement(), data(), ccHObject::DP_PARENT_OF_OTHER, CVLog::Error(), ccHObject::find(), ccGenericMesh::getAssociatedCloud(), ccHObject::getChildIndex(), ccHObject::getChildrenNumber(), ccHObject::getDependencyFlagsWith(), ccHObject::getParent(), CV_TYPES::IMAGE, ccObject::isA(), ccObject::isKindOf(), ccObject::isLeaf(), m_treeRoot, CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, MainWindow::refreshAll(), ccHObject::removeDependencyFlag(), removeElement(), CV_TYPES::SUB_MESH, MainWindow::TheInstance(), and ccHObjectCaster::ToGenericMesh().
editLabelScalarValue
void ccDBRoot::editLabelScalarValue () protected slot
Definition at line 2106 of file ecvDBRoot.cpp.
References cc2DLabel::PickedPoint::cloud, ccScalarField::computeMinAndMax(), ccPointCloud::getCurrentDisplayedScalarField(), cloudViewer::ScalarField::getName(), cc2DLabel::getPickedPoint(), cloudViewer::ScalarField::getValue(), ccDrawableObject::hasScalarFields(), cc2DLabel::PickedPoint::index, ccObject::isA(), m_dbTreeWidget, CV_TYPES::POINT_CLOUD, ccHObject::redrawDisplay(), cloudViewer::ScalarField::setValue(), cc2DLabel::size(), MainWindow::TheInstance(), ccHObjectCaster::To2DLabel(), and CVLog::Warning().
Referenced by ccDBRoot().
enableBubbleViewMode
void ccDBRoot::enableBubbleViewMode () protected slot
Definition at line 2088 of file ecvDBRoot.cpp.
References CV_TYPES::GBL_SENSOR, ccObject::isA(), m_dbTreeWidget, MainWindow::refreshAll(), and MainWindow::TheInstance().
Referenced by ccDBRoot().
expandBranch
void ccDBRoot::expandBranch () protected slot
Definition at line 1586 of file ecvDBRoot.cpp.
References expandOrCollapseHoveredBranch().
Referenced by ccDBRoot().
expandElement()
void ccDBRoot::expandElement (ccHObject * object, bool state)
Expands tree at a given node.
Definition at line 477 of file ecvDBRoot.cpp.
References ccHObject::getChild(), ccHObject::getChildrenNumber(), index(), and m_dbTreeWidget.
Referenced by cloudViewer::ModelViewerWidget::SelectObject().
expandOrCollapseHoveredBranch()
void ccDBRoot::expandOrCollapseHoveredBranch (bool expand) protected
Expands or collapses hovered item.
Definition at line 1590 of file ecvDBRoot.cpp.
References ccHObject::getChild(), ccHObject::getChildrenNumber(), index(), m_contextMenuPos, and m_dbTreeWidget.
Referenced by collapseBranch(), and expandBranch().
exportImages
void ccDBRoot::exportImages () protected slot
Definition at line 2159 of file ecvDBRoot.cpp.
References CVLog::Error(), filename, ccHObject::filterChildren(), CV_TYPES::IMAGE, image, ecvProgressDialog::isCancelRequested(), ccObject::isKindOf(), m_dbTreeWidget, CVLog::Print(), ecvProgressDialog::start(), ecvProgressDialog::stop(), MainWindow::TheInstance(), ccHObjectCaster::ToImage(), and CVLog::Warning().
Referenced by ccDBRoot().
find()
ccHObject * ccDBRoot::find (int uniqueID) const
Finds an element in DB.
Definition at line 1197 of file ecvDBRoot.cpp.
References ccHObject::find(), and m_treeRoot.
Referenced by selectEntities().
flags()
Qt::ItemFlags ccDBRoot::flags (const QModelIndex & index) const override virtual
Definition at line 1342 of file ecvDBRoot.cpp.
References CV_TYPES::CAMERA_SENSOR, CanDetachCloud(), CV_TYPES::CUSTOM_H_OBJECT, CV_TYPES::FACET, cloudViewer::ReferenceCloud::getAssociatedCloud(), ccHObject::getParent(), CV_TYPES::HIERARCHY_OBJECT, CV_TYPES::IMAGE, index(), ccObject::isA(), ccObject::isKindOf(), ccObject::isLocked(), CV_TYPES::LABEL_2D, CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, CV_TYPES::POLY_LINE, CV_TYPES::PRIMITIVE, CV_TYPES::SUB_MESH, and CV_TYPES::VIEWPORT_2D_OBJECT.
gatherRecursiveInformation
void ccDBRoot::gatherRecursiveInformation () protected slot
Definition at line 1699 of file ecvDBRoot.cpp.
References CVLog::Error(), ccHObject::getChild(), ccHObject::getChildrenNumber(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), ccPointCloud::hasColors(), ccPointCloud::hasNormals(), ccMesh::hasTriNormals(), CV_TYPES::IMAGE, ccObject::isA(), ccObject::isKindOf(), CV_TYPES::LABEL_2D, m_dbTreeWidget, CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, CV_TYPES::POINT_OCTREE, CV_TYPES::SENSOR, cloudViewer::PointCloudTpl< T >::size(), ccMesh::size(), and MainWindow::TheInstance().
Referenced by ccDBRoot().
getPropertiesDelegate()
ccPropertiesTreeDelegate* ccDBRoot::getPropertiesDelegate () inline
Get properties tree delegate.
Definition at line 93 of file ecvDBRoot.h.
References m_ccPropDelegate.
getRootEntity()
ccHObject * ccDBRoot::getRootEntity ()
Returns associated root object.
Definition at line 421 of file ecvDBRoot.cpp.
References m_treeRoot.
Referenced by MainWindow::addToDB(), and MainWindow::dbRootObject().
getSelectedEntities()
size_t ccDBRoot::getSelectedEntities (ccHObject::Container & selectedEntities, CV_CLASS_ENUM filter = CV_TYPES::OBJECT, dbTreeSelectionInfo * info = nullptr)
Returns selected entities in DB tree (optionally with a given type and additional information)
Definition at line 1273 of file ecvDBRoot.cpp.
References CV_TYPES::CAMERA_SENSOR, dbTreeSelectionInfo::cameraSensorCount, CV_TYPES::CIRCLE, dbTreeSelectionInfo::circleCount, dbTreeSelectionInfo::cloudCount, dbTreeSelectionInfo::colorCount, CV_TYPES::GBL_SENSOR, dbTreeSelectionInfo::gblSensorCount, ccGenericPointCloud::getOctree(), dbTreeSelectionInfo::gridCound, ccPointCloud::gridCount(), dbTreeSelectionInfo::groupCount, ccDrawableObject::hasColors(), ccDrawableObject::hasNormals(), ccDrawableObject::hasScalarFields(), CV_TYPES::HIERARCHY_OBJECT, ccObject::isA(), ccObject::isKindOf(), dbTreeSelectionInfo::kdTreeCount, m_dbTreeWidget, CV_TYPES::MESH, dbTreeSelectionInfo::meshCount, dbTreeSelectionInfo::normalsCount, dbTreeSelectionInfo::octreeCount, CV_TYPES::PLANE, dbTreeSelectionInfo::planeCount, CV_TYPES::POINT_CLOUD, CV_TYPES::POINT_KDTREE, CV_TYPES::POLY_LINE, dbTreeSelectionInfo::polylineCount, dbTreeSelectionInfo::reset(), dbTreeSelectionInfo::selCount, CV_TYPES::SENSOR, dbTreeSelectionInfo::sensorCount, dbTreeSelectionInfo::sfCount, ccHObjectCaster::ToGenericPointCloud(), and ccHObjectCaster::ToPointCloud().
hide()
void ccDBRoot::hide ()
Definition at line 388 of file ecvDBRoot.cpp.
References m_dbTreeWidget, and m_propertiesTreeWidget.
hidePropertiesView()
void ccDBRoot::hidePropertiesView ()
Hides properties view.
Definition at line 1210 of file ecvDBRoot.cpp.
References m_ccPropDelegate, m_propertiesModel, m_propertiesTreeWidget, and ccPropertiesTreeDelegate::unbind().
Referenced by deleteSelectedEntities(), removeElement(), removeElements(), toggleSelectedEntitiesProperty(), and updatePropertiesView().
index() [1/2]
QModelIndex ccDBRoot::index (ccHObject * object)
Definition at line 941 of file ecvDBRoot.cpp.
References m_treeRoot, and parent().
index() [2/2]
QModelIndex ccDBRoot::index (int row, int column, const QModelIndex & parentIndex = QModelIndex()) const override virtual
Definition at line 921 of file ecvDBRoot.cpp.
References m_treeRoot, and parent().
Referenced by addElement(), addEmptyGroup(), data(), deleteSelectedEntities(), expandElement(), expandOrCollapseHoveredBranch(), flags(), itemData(), parent(), removeElement(), removeElements(), selectEntities(), selectEntity(), setData(), showContextMenu(), unloadAll(), unselectEntity(), and updateCCObject().
itemData()
QMap< int, QVariant > ccDBRoot::itemData (const QModelIndex & index) const override virtual
Definition at line 1389 of file ecvDBRoot.cpp.
References ccObject::getUniqueID(), and index().
parent()
QModelIndex ccDBRoot::parent (const QModelIndex & index) const override virtual
Definition at line 963 of file ecvDBRoot.cpp.
References ccHObject::getIndex(), ccHObject::getParent(), index(), and m_treeRoot.
Referenced by addEmptyGroup(), columnCount(), deleteSelectedEntities(), index(), removeElement(), removeElements(), rowCount(), and unloadAll().
redrawCCObject
void ccDBRoot::redrawCCObject (ccHObject * object, bool forceRedraw = true) slot
Definition at line 1245 of file ecvDBRoot.cpp.
Referenced by ccDBRoot().
redrawCCObjectAndChildren
void ccDBRoot::redrawCCObjectAndChildren (ccHObject * object, bool forceRedraw = true) slot
Definition at line 1250 of file ecvDBRoot.cpp.
Referenced by ccDBRoot(), and setData().
reflectObjectPropChange
void ccDBRoot::reflectObjectPropChange (ccHObject * obj) slot
Definition at line 1216 of file ecvDBRoot.cpp.
References ccPropertiesTreeDelegate::getCurrentObject(), m_ccPropDelegate, m_propertiesTreeWidget, and showPropertiesView().
Referenced by setData().
removeElement()
void ccDBRoot::removeElement (ccHObject * object)
Removes an element from the DB tree.
Automatically calls prepareDisplayForRefresh on the object.
Definition at line 554 of file ecvDBRoot.cpp.
References dbIsEmpty(), ccHObject::getChildrenNumber(), hidePropertiesView(), index(), m_treeRoot, parent(), updatePropertiesView(), and CVLog::Warning().
Referenced by ccPointListPickingDlg::cancelAndExit(), ccPointListPickingDlg::clearLastLabel(), dropMimeData(), MainWindow::removeFromDB(), and MainWindow::removeObjectTemporarilyFromDBTree().
removeElements()
void ccDBRoot::removeElements (ccHObject::Container & objects)
Removes several elements at once from the DB tree.
Faster than multiple calls to removeElement. Automatically calls prepareDisplayForRefresh on the objects.
Warning
The input container will be cleared.
Definition at line 513 of file ecvDBRoot.cpp.
References dbIsEmpty(), ccHObject::getChildrenNumber(), hidePropertiesView(), index(), m_treeRoot, parent(), updatePropertiesView(), and CVLog::Warning().
Referenced by ccPointListPickingDlg::applyAndExit(), and ccPointListPickingDlg::cancelAndExit().
rowCount()
int ccDBRoot::rowCount (const QModelIndex & parent = QModelIndex()) const override virtual
Definition at line 983 of file ecvDBRoot.cpp.
References ccHObject::getChildrenNumber(), m_treeRoot, and parent().
selectByTypeAndName
void ccDBRoot::selectByTypeAndName () protected slot
Definition at line 1900 of file ecvDBRoot.cpp.
References ccSelectChildrenDlg::addType(), CV_TYPES::BOX, CV_TYPES::CAMERA_SENSOR, CV_TYPES::CONE, CV_TYPES::CUSTOM_H_OBJECT, CV_TYPES::CYLINDER, CV_TYPES::DISC, CV_TYPES::DISH, CV_TYPES::EXTRU, CV_TYPES::FACET, CV_TYPES::GBL_SENSOR, ccSelectChildrenDlg::getNameIsRegex(), ccSelectChildrenDlg::getNameMatchIsUsed(), ccSelectChildrenDlg::getSelectedName(), ccSelectChildrenDlg::getSelectedType(), ccSelectChildrenDlg::getStrictMatchState(), ccSelectChildrenDlg::getTypeIsUsed(), CV_TYPES::HIERARCHY_OBJECT, CV_TYPES::IMAGE, CV_TYPES::LABEL_2D, CV_TYPES::MESH, name, CV_TYPES::OBJECT, CV_TYPES::PLANE, CV_TYPES::POINT_CLOUD, CV_TYPES::POINT_KDTREE, CV_TYPES::POINT_OCTREE, CV_TYPES::POLY_LINE, CV_TYPES::PRIMITIVE, selectChildrenByTypeAndName(), CV_TYPES::SENSOR, CV_TYPES::SPHERE, CV_TYPES::SUB_MESH, MainWindow::TheInstance(), CV_TYPES::TORUS, type, CV_TYPES::VIEWPORT_2D_LABEL, and CV_TYPES::VIEWPORT_2D_OBJECT.
Referenced by ccDBRoot().
selectChildrenByTypeAndName()
void ccDBRoot::selectChildrenByTypeAndName (CV_CLASS_ENUM type, bool typeIsExclusive = true, QString name = QString(), bool nameIsRegex = false) protected
Selects objects by type and/or name.
Definition at line 1971 of file ecvDBRoot.cpp.
References ccHObject::filterChildren(), ccHObject::getChildrenNumber(), ccObject::getName(), m_contextMenuPos, m_dbTreeWidget, name, selectEntities(), type, and CVLog::Warning().
Referenced by selectByTypeAndName().
selectEntities [1/2]
void ccDBRoot::selectEntities (const ccHObject::Container & entities, bool incremental = false) slot
Selects multiple entities at once.
Parameters
entities set of the entities to 'select'
incremental whether to 'add' the input set to the selected entities set or to use it as replacement
Definition at line 1132 of file ecvDBRoot.cpp.
References index(), ccObject::isA(), ccDrawableObject::isSelected(), CV_TYPES::LABEL_2D, and m_dbTreeWidget.
selectEntities [2/2]
void ccDBRoot::selectEntities (std::unordered_set< int > entIDs) slot
Selects multiple entities at once (shortcut to the other version)
Parameters
entIDs list of the IDs of the entities to select
Definition at line 1109 of file ecvDBRoot.cpp.
References find(), and CVLog::Warning().
Referenced by ecvFilterByLabelDlg::apply(), and selectChildrenByTypeAndName().
selectEntity
void ccDBRoot::selectEntity (ccHObject * obj, bool forceAdditiveSelection = false) slot
Selects a given entity.
If ctrl is pressed by the user at the same time, previous selection will be simply updated accordingly.
Parameters
obj entity to select
forceAdditiveSelection whether to force additive selection (just as if CTRL key is pressed) or not
Definition at line 1054 of file ecvDBRoot.cpp.
References index(), ccObject::isA(), ccDrawableObject::isSelected(), CV_TYPES::LABEL_2D, m_dbTreeWidget, ccDrawableObject::setSelected(), and CVLog::Warning().
Referenced by cloudViewer::ModelViewerWidget::SelectObject(), and MainWindow::setSelectedInDB().
selectionChanged
void ccDBRoot::selectionChanged () signal
Referenced by changeSelection().
setData()
bool ccDBRoot::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override virtual
Definition at line 777 of file ecvDBRoot.cpp.
References context, ecvDisplayTools::getDataAxesGridProperties(), ccObject::getName(), ccHObject::getViewId(), ccHObject::hideBB(), ccGenericPrimitive::hideShowDrawings(), ccSensor::hideShowDrawings(), index(), ccObject::isA(), ccObject::isEnabled(), ccObject::isKindOf(), ccDrawableObject::isSelected(), ccDrawableObject::isVisible(), CV_TYPES::LABEL_2D, ccDrawableObject::nameShownIn3D(), CV_TYPES::POINT_KDTREE, CV_TYPES::POINT_OCTREE, CV_TYPES::PRIMITIVE, redrawCCObjectAndChildren(), reflectObjectPropChange(), MainWindow::refreshAll(), ecvDisplayTools::RemoveWidgets(), CV_TYPES::SENSOR, ccObject::setEnabled(), ccHObject::setForceRedrawRecursive(), ccObject::setName(), ccHObject::setRedrawFlagRecursive(), ecvDisplayTools::SetRedrawRecursive(), ccHObject::showBB(), MainWindow::TheInstance(), ecvDisplayTools::TheInstance(), ccHObjectCaster::To2DLabel(), ccHObjectCaster::To2DViewportLabel(), ccHObjectCaster::ToPrimitive(), ccHObjectCaster::ToSensor(), cc2DLabel::updateLabel(), cc2DViewportLabel::updateLabel(), updatePropertiesView(), ecvDisplayTools::UpdateScreen(), CV_TYPES::VIEWPORT_2D_LABEL, AxesGridProperties::visible, WIDGET_RECTANGLE_2D, and WIDGET_T2D.
show()
void ccDBRoot::show ()
Definition at line 393 of file ecvDBRoot.cpp.
References m_dbTreeWidget, and m_propertiesTreeWidget.
showContextMenu
void ccDBRoot::showContextMenu (const QPoint & menuPos) protected slot
Definition at line 2284 of file ecvDBRoot.cpp.
References cc2DLabel::PickedPoint::cloud, CV_TYPES::FACET, ccHObject::filterChildren(), CV_TYPES::GBL_SENSOR, ccHObject::getChildrenNumber(), cc2DLabel::getPickedPoint(), ccDrawableObject::hasScalarFields(), CV_TYPES::HIERARCHY_OBJECT, CV_TYPES::IMAGE, index(), ccObject::isA(), ccObject::isKindOf(), ccObject::isLeaf(), CV_TYPES::LABEL_2D, m_addEmptyGroup, m_alignCameraWithEntity, m_alignCameraWithEntityReverse, m_collapseBranch, m_contextMenuPos, m_dbTreeWidget, m_deleteSelectedEntities, m_editLabelScalarValue, m_enableBubbleViewMode, m_expandBranch, m_exportImages, m_gatherInformation, m_selectByTypeAndName, m_sortChildrenAZ, m_sortChildrenType, m_sortChildrenZA, m_toggleSelectedEntities, m_toggleSelectedEntities3DName, m_toggleSelectedEntitiesColor, m_toggleSelectedEntitiesMat, m_toggleSelectedEntitiesNormals, m_toggleSelectedEntitiesSF, m_toggleSelectedEntitiesVisibility, CV_TYPES::MESH, CV_TYPES::PLANE, CV_TYPES::POINT_CLOUD, size, cc2DLabel::size(), and ccHObjectCaster::To2DLabel().
Referenced by ccDBRoot().
showPropertiesView()
void ccDBRoot::showPropertiesView (ccHObject * obj) protected
Shows properties view for a given element.
Definition at line 1201 of file ecvDBRoot.cpp.
References c_propViewLeftColumnWidth, ccPropertiesTreeDelegate::fillModel(), m_ccPropDelegate, and m_propertiesTreeWidget.
Referenced by reflectObjectPropChange(), and updatePropertiesView().
sortChildrenAZ
void ccDBRoot::sortChildrenAZ () protected slot
Definition at line 1828 of file ecvDBRoot.cpp.
References SORT_A2Z, and sortSelectedEntitiesChildren().
Referenced by ccDBRoot().
sortChildrenType
void ccDBRoot::sortChildrenType () protected slot
Definition at line 1832 of file ecvDBRoot.cpp.
References SORT_BY_TYPE, and sortSelectedEntitiesChildren().
Referenced by ccDBRoot().
sortChildrenZA
void ccDBRoot::sortChildrenZA () protected slot
Definition at line 1830 of file ecvDBRoot.cpp.
References SORT_Z2A, and sortSelectedEntitiesChildren().
Referenced by ccDBRoot().
sortSelectedEntitiesChildren()
void ccDBRoot::sortSelectedEntitiesChildren (SortRules rule) protected
Sorts selected entities children.
Definition at line 1836 of file ecvDBRoot.cpp.
References ccHObject::getChild(), ccHObject::getChildrenNumber(), ccHObject::getClassID(), ccObject::getName(), m_dbTreeWidget, SORT_A2Z, SORT_BY_TYPE, SORT_Z2A, cloudViewer::utility::swap(), and ccHObject::swapChildren().
Referenced by sortChildrenAZ(), sortChildrenType(), and sortChildrenZA().
supportedDragActions()
virtual Qt::DropActions ccDBRoot::supportedDragActions () const inline override virtual
Definition at line 161 of file ecvDBRoot.h.
supportedDropActions()
Qt::DropActions ccDBRoot::supportedDropActions () const override virtual
Definition at line 1338 of file ecvDBRoot.cpp.
toggleSelectedEntities
void ccDBRoot::toggleSelectedEntities () inline protected slot
Definition at line 224 of file ecvDBRoot.h.
References TG_ENABLE, and toggleSelectedEntitiesProperty().
Referenced by ccDBRoot().
toggleSelectedEntities3DName
void ccDBRoot::toggleSelectedEntities3DName () inline protected slot
Definition at line 242 of file ecvDBRoot.h.
References TG_3D_NAME, and toggleSelectedEntitiesProperty().
Referenced by ccDBRoot().
toggleSelectedEntitiesColor
void ccDBRoot::toggleSelectedEntitiesColor () inline protected slot
Definition at line 230 of file ecvDBRoot.h.
References TG_COLOR, and toggleSelectedEntitiesProperty().
Referenced by ccDBRoot().
toggleSelectedEntitiesMat
void ccDBRoot::toggleSelectedEntitiesMat () inline protected slot
Definition at line 239 of file ecvDBRoot.h.
References TG_MATERIAL, and toggleSelectedEntitiesProperty().
Referenced by ccDBRoot().
toggleSelectedEntitiesNormals
void ccDBRoot::toggleSelectedEntitiesNormals () inline protected slot
Definition at line 233 of file ecvDBRoot.h.
References TG_NORMAL, and toggleSelectedEntitiesProperty().
Referenced by ccDBRoot().
toggleSelectedEntitiesProperty()
void ccDBRoot::toggleSelectedEntitiesProperty (TOGGLE_PROPERTY prop) protected
Toggles a given property (enable state, visibility, normal, color, SF, etc.) on selected entities
Definition at line 2023 of file ecvDBRoot.cpp.
References hidePropertiesView(), ccObject::isEnabled(), m_dbTreeWidget, MainWindow::refreshAll(), ccObject::setEnabled(), ccHObject::setForceRedrawRecursive(), TG_3D_NAME, TG_COLOR, TG_ENABLE, TG_NORMAL, TG_SF, TG_VISIBLE, MainWindow::TheInstance(), ccDrawableObject::toggleColors(), ccDrawableObject::toggleNormals(), ccDrawableObject::toggleSF(), ccDrawableObject::toggleShowName(), ccDrawableObject::toggleVisibility(), and updatePropertiesView().
Referenced by toggleSelectedEntities(), toggleSelectedEntities3DName(), toggleSelectedEntitiesColor(), toggleSelectedEntitiesMat(), toggleSelectedEntitiesNormals(), toggleSelectedEntitiesSF(), and toggleSelectedEntitiesVisibility().
toggleSelectedEntitiesSF
void ccDBRoot::toggleSelectedEntitiesSF () inline protected slot
Definition at line 236 of file ecvDBRoot.h.
References TG_SF, and toggleSelectedEntitiesProperty().
Referenced by ccDBRoot().
toggleSelectedEntitiesVisibility
void ccDBRoot::toggleSelectedEntitiesVisibility () inline protected slot
Definition at line 227 of file ecvDBRoot.h.
References TG_VISIBLE, and toggleSelectedEntitiesProperty().
Referenced by ccDBRoot().
unloadAll()
void ccDBRoot::unloadAll ()
Unloads all entities.
Definition at line 398 of file ecvDBRoot.cpp.
References dbIsEmpty(), ccHObject::getChild(), ccHObject::getChildrenNumber(), index(), m_treeRoot, parent(), MainWindow::refreshAll(), ccHObject::removeChild(), ecvDisplayTools::SetRemoveAllFlag(), MainWindow::TheInstance(), and updatePropertiesView().
Referenced by MainWindow::~MainWindow().
unselectAllEntities()
void ccDBRoot::unselectAllEntities ()
Unselects all entities.
Definition at line 1047 of file ecvDBRoot.cpp.
References m_dbTreeWidget.
unselectEntity()
void ccDBRoot::unselectEntity (ccHObject * obj)
Unselects a given entity.
Definition at line 1035 of file ecvDBRoot.cpp.
References index(), ccDrawableObject::isSelected(), and m_dbTreeWidget.
Referenced by cloudViewer::ModelViewerWidget::SelectObject(), and MainWindow::setSelectedInDB().
updateCCObject
void ccDBRoot::updateCCObject (ccHObject * object) slot
Definition at line 1237 of file ecvDBRoot.cpp.
References index().
Referenced by ccDBRoot().
updatePropertiesView()
void ccDBRoot::updatePropertiesView ()
Updates properties view.
Definition at line 1225 of file ecvDBRoot.cpp.
References hidePropertiesView(), m_dbTreeWidget, and showPropertiesView().
Referenced by changeSelection(), deleteSelectedEntities(), removeElement(), removeElements(), setData(), toggleSelectedEntitiesProperty(), unloadAll(), and MainWindow::updatePropertiesView().
Member Data Documentation
m_addEmptyGroup
QAction* ccDBRoot::m_addEmptyGroup protected
Context menu action: add empty group.
Definition at line 329 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_alignCameraWithEntity
QAction* ccDBRoot::m_alignCameraWithEntity protected
Context menu action: use 3-points labels or planes to orient camera.
Definition at line 331 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_alignCameraWithEntityReverse
QAction* ccDBRoot::m_alignCameraWithEntityReverse protected
Context menu action: reverse of m_alignCameraWithEntity.
Definition at line 333 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_ccPropDelegate
ccPropertiesTreeDelegate* ccDBRoot::m_ccPropDelegate protected
Selected entity's properties delegate.
Definition at line 294 of file ecvDBRoot.h.
Referenced by getPropertiesDelegate(), hidePropertiesView(), reflectObjectPropChange(), showPropertiesView(), and ~ccDBRoot().
m_collapseBranch
QAction* ccDBRoot::m_collapseBranch protected
Context menu action: collapse tree branch.
Definition at line 299 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_contextMenuPos
QPoint ccDBRoot::m_contextMenuPos protected
Last context menu pos.
Definition at line 340 of file ecvDBRoot.h.
Referenced by addEmptyGroup(), expandOrCollapseHoveredBranch(), selectChildrenByTypeAndName(), and showContextMenu().
m_dbTreeWidget
QTreeView* ccDBRoot::m_dbTreeWidget protected
Associated widget for DB tree.
Definition at line 286 of file ecvDBRoot.h.
Referenced by addElement(), addEmptyGroup(), alignCameraWithEntity(), countSelectedEntities(), deleteSelectedEntities(), editLabelScalarValue(), enableBubbleViewMode(), expandElement(), expandOrCollapseHoveredBranch(), exportImages(), gatherRecursiveInformation(), getSelectedEntities(), hide(), selectChildrenByTypeAndName(), selectEntities(), selectEntity(), show(), showContextMenu(), sortSelectedEntitiesChildren(), toggleSelectedEntitiesProperty(), unselectAllEntities(), unselectEntity(), and updatePropertiesView().
m_deleteSelectedEntities
QAction* ccDBRoot::m_deleteSelectedEntities protected
Context menu action: delete selected entities.
Definition at line 313 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_editLabelScalarValue
QAction* ccDBRoot::m_editLabelScalarValue protected
Context menu action: change current scalar value (via a 2D label)
Definition at line 337 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_enableBubbleViewMode
QAction* ccDBRoot::m_enableBubbleViewMode protected
Context menu action: enable bubble-view (on a sensor)
Definition at line 335 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_expandBranch
QAction* ccDBRoot::m_expandBranch protected
Context menu action: expand tree branch.
Definition at line 297 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_exportImages
QAction* ccDBRoot::m_exportImages protected
Context menu action: export images.
Definition at line 311 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_gatherInformation
QAction* ccDBRoot::m_gatherInformation protected
Context menu action: gather (recursive) information on selected entities.
Definition at line 301 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_propertiesModel
QStandardItemModel* ccDBRoot::m_propertiesModel protected
Selected entity's properties data model.
Definition at line 292 of file ecvDBRoot.h.
Referenced by hidePropertiesView(), and ~ccDBRoot().
m_propertiesTreeWidget
QTreeView* ccDBRoot::m_propertiesTreeWidget protected
Associated widget for selected entity's properties tree.
Definition at line 289 of file ecvDBRoot.h.
Referenced by hide(), hidePropertiesView(), reflectObjectPropChange(), show(), and showPropertiesView().
m_selectByTypeAndName
QAction* ccDBRoot::m_selectByTypeAndName protected
Context menu action: select object by type and/or by name.
Definition at line 309 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_sortChildrenAZ
QAction* ccDBRoot::m_sortChildrenAZ protected
Context menu action: sort children in alphabetical order.
Definition at line 303 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_sortChildrenType
QAction* ccDBRoot::m_sortChildrenType protected
Context menu action: sort children by type.
Definition at line 307 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_sortChildrenZA
QAction* ccDBRoot::m_sortChildrenZA protected
Context menu action: sort children in reverse alphabetical order.
Definition at line 305 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_toggleSelectedEntities
QAction* ccDBRoot::m_toggleSelectedEntities protected
Context menu action: enabled/disable selected entities.
Definition at line 315 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_toggleSelectedEntities3DName
QAction* ccDBRoot::m_toggleSelectedEntities3DName protected
Context menu action: hide/show selected entities 3D name.
Definition at line 327 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_toggleSelectedEntitiesColor
QAction* ccDBRoot::m_toggleSelectedEntitiesColor protected
Context menu action: hide/show selected entities color.
Definition at line 319 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_toggleSelectedEntitiesMat
QAction* ccDBRoot::m_toggleSelectedEntitiesMat protected
Context menu action: hide/show selected entities materials/textures.
Definition at line 323 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_toggleSelectedEntitiesNormals
QAction* ccDBRoot::m_toggleSelectedEntitiesNormals protected
Context menu action: hide/show selected entities normals.
Definition at line 321 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_toggleSelectedEntitiesSF
QAction* ccDBRoot::m_toggleSelectedEntitiesSF protected
Context menu action: hide/show selected entities SF.
Definition at line 325 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_toggleSelectedEntitiesVisibility
QAction* ccDBRoot::m_toggleSelectedEntitiesVisibility protected
Context menu action: hide/show selected entities.
Definition at line 317 of file ecvDBRoot.h.
Referenced by showContextMenu().
m_treeRoot
ccHObject* ccDBRoot::m_treeRoot protected
Associated DB root.
Definition at line 283 of file ecvDBRoot.h.
Referenced by addElement(), deleteSelectedEntities(), dropMimeData(), find(), getRootEntity(), index(), parent(), removeElement(), removeElements(), rowCount(), unloadAll(), and ~ccDBRoot().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/db_tree/ecvDBRoot.h
/root/ACloudViewer/app/db_tree/ecvDBRoot.cpp