ACloudViewer: cloudViewer::GenericMesh Class Reference
cloudViewer::GenericMesh Class Reference abstract
#include <GenericMesh.h>
Public Types
enum class SimplificationContraction { Average , Quadric }
Indicates the method that is used for mesh simplification if multiple vertices are combined to a single one.
enum class FilterScope { All , Color , Normal , Vertex }
Indicates the scope of filter operations.
enum class DeformAsRigidAsPossibleEnergy { Spokes , Smoothed }
using genericTriangleAction = std::function< void(GenericTriangle &)>
Generic function to apply to a triangle (used by foreach)
Public Member Functions
GenericMesh ()=default
virtual ~GenericMesh ()=default
Default destructor.
virtual unsigned size () const =0
Returns the number of triangles.
virtual bool hasTriangles () const
virtual void forEach (genericTriangleAction action)=0
Fast iteration mechanism.
virtual void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax)=0
Returns the mesh bounding-box.
virtual void placeIteratorAtBeginning ()=0
Places the mesh iterator at the beginning.
virtual GenericTriangle * _getNextTriangle ()=0
Returns the next triangle (relatively to the global iterator position)
Detailed Description
A generic mesh interface for data communication between library and client applications
Definition at line 21 of file GenericMesh.h.
Member Typedef Documentation
genericTriangleAction
using cloudViewer::GenericMesh::genericTriangleAction = std::function<void(GenericTriangle&)>
Generic function to apply to a triangle (used by foreach)
Definition at line 53 of file GenericMesh.h.
Member Enumeration Documentation
DeformAsRigidAsPossibleEnergy
enum cloudViewer::GenericMesh::DeformAsRigidAsPossibleEnergy strong
Energy model that is minimized in the DeformAsRigidAsPossible method.
Parameters
Spokes is the original energy as formulated in Sorkine and Alexa, "As-Rigid-As-Possible Surface Modeling", 2007.
Smoothed adds a rotation smoothing term to the rotations.
Enumerator
Spokes
Smoothed
Definition at line 50 of file GenericMesh.h.
FilterScope
enum cloudViewer::GenericMesh::FilterScope strong
Indicates the scope of filter operations.
Parameters
All indicates that all properties (color, normal, vertex position) are filtered.
Color indicates that only the colors are filtered.
Normal indicates that only the normals are filtered.
Vertex indicates that only the vertex positions are filtered.
Enumerator
All
Color
Normal
Vertex
Definition at line 44 of file GenericMesh.h.
SimplificationContraction
enum cloudViewer::GenericMesh::SimplificationContraction strong
Indicates the method that is used for mesh simplification if multiple vertices are combined to a single one.
Parameters
Average indicates that the average position is computed as output.
Quadric indicates that the distance to the adjacent triangle planes is minimized. Cf. "Simplifying Surfaces with Color and Texture using Quadric Error Metrics" by Garland and Heckbert.
Enumerator
Average
Quadric
Definition at line 35 of file GenericMesh.h.
Constructor & Destructor Documentation
GenericMesh()
cloudViewer::GenericMesh::GenericMesh () default
~GenericMesh()
virtual cloudViewer::GenericMesh::~GenericMesh () virtual default
Default destructor.
Member Function Documentation
_getNextTriangle()
virtual GenericTriangle* cloudViewer::GenericMesh::_getNextTriangle () pure virtual
Returns the next triangle (relatively to the global iterator position)
Virtual method to handle the mesh global iterator. Global iterator position should be increased each time this method is called. The returned object can be temporary.
Returns
a triangle
Implemented in ccSubMesh, ccMeshGroup, cloudViewer::geometry::ecvMeshBase, ccMesh, cloudViewer::SimpleMesh, and cloudViewer::Delaunay2dMesh.
Referenced by define_GenericMesh(), and cloudViewer::Grid3D< Type >::intersectWith().
forEach()
virtual void cloudViewer::GenericMesh::forEach (genericTriangleAction action) pure virtual
Fast iteration mechanism.
Virtual method to apply a function to the whole mesh
Parameters
action function to apply (see GenericMesh::genericTriangleAction)
Implemented in ccSubMesh, ccMeshGroup, cloudViewer::geometry::ecvMeshBase, ccMesh, cloudViewer::SimpleMesh, and cloudViewer::Delaunay2dMesh.
Referenced by define_GenericMesh().
getBoundingBox()
virtual void cloudViewer::GenericMesh::getBoundingBox (CCVector3 & bbMin, CCVector3 & bbMax) pure virtual
Returns the mesh bounding-box.
Virtual method to request the mesh bounding-box limits. It is equivalent to the bounding-box of the cloud composed of the mesh vertexes.
Parameters
bbMin lower bounding-box limits (Xmin,Ymin,Zmin)
bbMax higher bounding-box limits (Xmax,Ymax,Zmax)
Implemented in ccSubMesh, ccMeshGroup, cloudViewer::geometry::ecvMeshBase, ccMesh, cloudViewer::SimpleMesh, and cloudViewer::Delaunay2dMesh.
Referenced by define_GenericMesh().
hasTriangles()
virtual bool cloudViewer::GenericMesh::hasTriangles () const inline virtual
Reimplemented in cloudViewer::geometry::HalfEdgeTriangleMesh.
Definition at line 60 of file GenericMesh.h.
References size.
Referenced by ccMesh::hasTriangleMaterialIds(), ccMesh::hasTriangleUvs(), ccMesh::IsEmpty(), cloudViewer::io::ReadTriangleMesh(), and cloudViewer::io::rpc::SetTriangleMesh().
placeIteratorAtBeginning()
virtual void cloudViewer::GenericMesh::placeIteratorAtBeginning () pure virtual
Places the mesh iterator at the beginning.
Virtual method to handle the mesh global iterator
Implemented in ccSubMesh, ccMeshGroup, cloudViewer::geometry::ecvMeshBase, ccMesh, cloudViewer::SimpleMesh, and cloudViewer::Delaunay2dMesh.
Referenced by define_GenericMesh(), cloudViewer::Grid3D< Type >::intersectWith(), and MAFilter::saveToFile().
size()
virtual unsigned cloudViewer::GenericMesh::size () const pure virtual
Returns the number of triangles.
Virtual method to request the mesh size
Returns
the mesh size
Implemented in ccSubMesh, ccMeshGroup, cloudViewer::geometry::ecvMeshBase, ccMesh, cloudViewer::SimpleMesh, and cloudViewer::Delaunay2dMesh.
Referenced by define_GenericMesh(), ccSubMesh::getCurrentTriGlobalIndex(), ccMesh::hasTriangleMaterialIds(), ccMesh::hasTriangleUvs(), cloudViewer::Grid3D< Type >::intersectWith(), MAFilter::saveToFile(), ccMesh::shrinkToFit(), and ToFbxMesh().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/GenericMesh.h