ACloudViewer: flann::Logger Class Reference
flann::Logger Class Reference
#include <logger.h>
Static Public Member Functions
static void setLevel (int level)
static int getLevel ()
static void setDestination (const char *name)
static int log (int level, const char *fmt,...)
static int fatal (const char *fmt,...)
static int error (const char *fmt,...)
static int warn (const char *fmt,...)
static int info (const char *fmt,...)
static int debug (const char *fmt,...)
Detailed Description
Definition at line 43 of file logger.h.
Member Function Documentation
debug()
static int flann::Logger::debug (const char * fmt, ...) inline static
Definition at line 128 of file logger.h.
error()
static int flann::Logger::error (const char * fmt, ...) inline static
Definition at line 125 of file logger.h.
Referenced by __flann_add_points(), __flann_build_index(), __flann_compute_cluster_centers(), __flann_find_nearest_neighbors(), __flann_find_nearest_neighbors_index(), __flann_free_index(), __flann_get_point(), __flann_load_index(), __flann_radius_search(), __flann_remove_point(), __flann_save_index(), __flann_size(), __flann_used_memory(), __flann_veclen(), _flann_add_points(), _flann_build_index(), _flann_compute_cluster_centers(), _flann_find_nearest_neighbors(), _flann_find_nearest_neighbors_index(), _flann_free_index(), _flann_get_point(), _flann_load_index(), _flann_radius_search(), _flann_remove_point(), _flann_save_index(), _flann_size(), _flann_used_memory(), and _flann_veclen().
fatal()
static int flann::Logger::fatal (const char * fmt, ...) inline static
Definition at line 124 of file logger.h.
getLevel()
static int flann::Logger::getLevel () inline static
Returns the currently set logging level.
Returns
current logging level
Definition at line 91 of file logger.h.
Referenced by flann::AutotunedIndex< Distance >::buildIndex().
info()
static int flann::Logger::info (const char * fmt, ...) inline static
Definition at line 127 of file logger.h.
Referenced by flann::AutotunedIndex< Distance >::buildIndex(), flann::CompositeIndex< Distance >::buildIndex(), flann::KMeansIndex< Distance >::getClusterCenters(), flann::optimizeSimplexDownhill(), flann::search_with_ground_truth(), flann::test_index_checks(), flann::test_index_precision(), and flann::test_index_precisions().
log()
static int flann::Logger::log (int level, const char * fmt, ...) inline static
Print log message
Parameters
level Log level
fmt Message format
Returns
Definition at line 105 of file logger.h.
setDestination()
static void flann::Logger::setDestination (const char * name) inline static
Sets the logging destination
Parameters
name Filename or NULL for console
Definition at line 97 of file logger.h.
References name.
setLevel()
static void flann::Logger::setLevel (int level) inline static
Sets the logging level. All messages with lower priority will be ignored.
Parameters
level Logging level
Definition at line 85 of file logger.h.
Referenced by flann::log_verbosity().
warn()
static int flann::Logger::warn (const char * fmt, ...) inline static
Definition at line 126 of file logger.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/util/logger.h