ACloudViewer: cloudViewer::visualization::VisualizerWithVertexSelection Class Reference
cloudViewer::visualization::VisualizerWithVertexSelection Class Reference
#include <VisualizerWithVertexSelection.h>
Classes
struct PickedPoint
Public Types
enum class SelectionMode { None = 0 , Point = 1 , Rectangle = 2 , Moving = 3 }
Public Member Functions
VisualizerWithVertexSelection ()
~VisualizerWithVertexSelection () override
VisualizerWithVertexSelection (const VisualizerWithVertexSelection &)=delete
VisualizerWithVertexSelection & operator= (const VisualizerWithVertexSelection &)=delete
bool AddGeometry (std::shared_ptr< const ccHObject > geometry_ptr, bool reset_bounding_box=true) override
Function to add geometry to the scene and create corresponding shaders.
bool UpdateGeometry (std::shared_ptr< const ccHObject > geometry_ptr=nullptr) override
Function to update geometry.
void PrintVisualizerHelp () override
void UpdateWindowTitle () override
void BuildUtilities () override
void SetPointSize (double size)
std::vector< int > PickPoints (double x, double y, double w, double h)
std::vector< PickedPoint > GetPickedPoints () const
void ClearPickedPoints ()
void AddPickedPoints (const std::vector< int > indices)
void RemovePickedPoints (const std::vector< int > indices)
void RegisterSelectionChangedCallback (std::function< void()> f)
void RegisterSelectionMovingCallback (std::function< void()> f)
void RegisterSelectionMovedCallback (std::function< void()> f)
Public Member Functions inherited from cloudViewer::visualization::Visualizer
Visualizer ()
virtual ~Visualizer ()
Visualizer (Visualizer &&)=delete
Visualizer (const Visualizer &)=delete
Visualizer & operator= (const Visualizer &)=delete
bool CreateVisualizerWindow (const std::string &window_name="CloudViewer", const int width=640, const int height=480, const int left=50, const int top=50, const bool visible=true)
Function to create a window and initialize GLFW.
void DestroyVisualizerWindow ()
Function to destroy a window.
void RegisterAnimationCallback (std::function< bool(Visualizer *)> callback_func)
Function to register a callback function for animation.
void Run ()
Function to activate the window.
void Close ()
Function to to notify the window to be closed.
bool WaitEvents ()
Function to process the event queue and return if the window is closed.
bool PollEvents ()
virtual bool RemoveGeometry (std::shared_ptr< const ccHObject > geometry_ptr, bool reset_bounding_box=true)
Function to remove geometry from the scene.
virtual bool ClearGeometries ()
virtual bool HasGeometry () const
virtual void UpdateRender ()
Function to inform render needed to be updated.
virtual void SetFullScreen (bool fullscreen)
Functions to change between fullscreen and windowed modes.
virtual void ToggleFullScreen ()
virtual bool IsFullScreen ()
ViewControl & GetViewControl ()
Function to retrieve the associated ViewControl.
RenderOption & GetRenderOption ()
Function to retrieve the associated RenderOption.
std::shared_ptr< geometry::Image > CaptureScreenFloatBuffer (bool do_render=true)
Function to capture screen and store RGB in a float buffer.
void CaptureScreenImage (const std::string &filename="", bool do_render=true)
Function to capture and save a screen image.
std::shared_ptr< geometry::Image > CaptureDepthFloatBuffer (bool do_render=true)
void CaptureDepthImage (const std::string &filename="", bool do_render=true, double depth_scale=1000.0)
void CaptureDepthPointCloud (const std::string &filename="", bool do_render=true, bool convert_to_world_coordinate=false)
Function to capture and save local point cloud.
void CaptureRenderOption (const std::string &filename="")
void ResetViewPoint (bool reset_bounding_box=false)
Function to reset view point.
const std::string & GetWindowName () const
Protected Types
enum DragType { DRAG_MOVING , DRAG_END }
Protected Member Functions
bool InitViewControl () override
Function to initialize ViewControl.
bool InitRenderOption () override
Function to initialize RenderOption.
void WindowResizeCallback (GLFWwindow *window, int w, int h) override
void MouseMoveCallback (GLFWwindow *window, double x, double y) override
void MouseScrollCallback (GLFWwindow *window, double x, double y) override
void MouseButtonCallback (GLFWwindow *window, int button, int action, int mods) override
void KeyPressCallback (GLFWwindow *window, int key, int scancode, int action, int mods) override
void InvalidateSelectionPolygon ()
void InvalidatePicking ()
float GetDepth (int winX, int winY)
Eigen::Vector3d CalcDragDelta (double winX, double winY)
void DragSelectedPoints (const Eigen::Vector3d &delta, DragType type)
const std::vector< CCVector3 > * GetGeometryPoints (std::shared_ptr< const ccHObject > geometry)
const std::vector< Eigen::Vector3d > * GetGeometryEigenPoints (std::shared_ptr< const ccHObject > geometry)
Protected Member Functions inherited from cloudViewer::visualization::Visualizer
virtual bool InitOpenGL ()
Function to initialize OpenGL.
virtual void Render (bool render_screen=false)
void CopyViewStatusToClipboard ()
void CopyViewStatusFromClipboard ()
virtual void WindowRefreshCallback (GLFWwindow *window)
virtual void WindowCloseCallback (GLFWwindow *window)
Function to notify the window to be closed.
Protected Attributes
std::shared_ptr< SelectionPolygon > selection_polygon_ptr_
std::shared_ptr< glsl::SelectionPolygonRenderer > selection_polygon_renderer_ptr_
SelectionMode selection_mode_ = SelectionMode::None
Eigen::Vector2d mouse_down_pos_
std::vector< int > points_in_rect_
float drag_depth_ = 0.0f
std::shared_ptr< PointCloudPicker > pointcloud_picker_ptr_
std::shared_ptr< glsl::PointCloudPickerRenderer > pointcloud_picker_renderer_ptr_
std::shared_ptr< const ccHObject > geometry_ptr_
std::shared_ptr< glsl::GeometryRenderer > geometry_renderer_ptr_
RenderOption pick_point_opts_
std::shared_ptr< ccPointCloud > ui_points_geometry_ptr_
std::shared_ptr< glsl::GeometryRenderer > ui_points_renderer_ptr_
std::unordered_map< int, Eigen::Vector3d > selected_points_
std::unordered_map< int, Eigen::Vector3d > selected_points_before_drag_
std::shared_ptr< ccPointCloud > ui_selected_points_geometry_ptr_
std::shared_ptr< glsl::GeometryRenderer > ui_selected_points_renderer_ptr_
std::function< void()> on_selection_changed_
std::function< void()> on_selection_moving_
std::function< void()> on_selection_moved_
Protected Attributes inherited from cloudViewer::visualization::Visualizer
GLFWwindow * window_ = nullptr
std::string window_name_ = "CloudViewer"
std::shared_ptr< GLFWContext > glfw_context_ = nullptr
Shared GLFW context.
Eigen::Vector2i saved_window_size_ = Eigen::Vector2i::Zero()
Eigen::Vector2i saved_window_pos_ = Eigen::Vector2i::Zero()
std::function< bool(Visualizer *)> animation_callback_func_ = nullptr
std::function< bool(Visualizer *)> animation_callback_func_in_loop_
MouseControl mouse_control_
bool is_redraw_required_ = true
bool is_initialized_ = false
GLuint vao_id_ = 0
GLuint render_fbo_ = 0
GLuint render_rgb_tex_ = 0
GLuint render_depth_stencil_rbo_ = 0
std::unique_ptr< ViewControl > view_control_ptr_
std::unique_ptr< RenderOption > render_option_ptr_
std::unordered_set< std::shared_ptr< const ccHObject > > geometry_ptrs_
std::unordered_set< std::shared_ptr< glsl::GeometryRenderer > > geometry_renderer_ptrs_
std::vector< std::shared_ptr< const ccHObject > > utility_ptrs_
std::vector< std::shared_ptr< glsl::GeometryRenderer > > utility_renderer_ptrs_
std::unordered_map< std::shared_ptr< glsl::GeometryRenderer >, RenderOption > utility_renderer_opts_
std::shared_ptr< ccMesh > coordinate_frame_mesh_ptr_
std::shared_ptr< glsl::CoordinateFrameRenderer > coordinate_frame_mesh_renderer_ptr_
Detailed Description
Definition at line 22 of file VisualizerWithVertexSelection.h.
Member Enumeration Documentation
DragType
enum cloudViewer::visualization::VisualizerWithVertexSelection::DragType protected
Enumerator
DRAG_MOVING
DRAG_END
Definition at line 79 of file VisualizerWithVertexSelection.h.
SelectionMode
enum cloudViewer::visualization::VisualizerWithVertexSelection::SelectionMode strong
Enumerator
None
Point
Rectangle
Moving
Definition at line 24 of file VisualizerWithVertexSelection.h.
Constructor & Destructor Documentation
VisualizerWithVertexSelection() [1/2]
cloudViewer::visualization::VisualizerWithVertexSelection::VisualizerWithVertexSelection () inline
Definition at line 27 of file VisualizerWithVertexSelection.h.
~VisualizerWithVertexSelection()
cloudViewer::visualization::VisualizerWithVertexSelection::~VisualizerWithVertexSelection () inline override
Definition at line 28 of file VisualizerWithVertexSelection.h.
VisualizerWithVertexSelection() [2/2]
cloudViewer::visualization::VisualizerWithVertexSelection::VisualizerWithVertexSelection (const VisualizerWithVertexSelection &) delete
Member Function Documentation
AddGeometry()
bool cloudViewer::visualization::VisualizerWithVertexSelection::AddGeometry (std::shared_ptr< const ccHObject > geometry_ptr, bool reset_bounding_box = true) override virtual
Function to add geometry to the scene and create corresponding shaders.
After calling this function, the Visualizer owns the geometry object.
This function MUST be called after CreateVisualizerWindow().
This function returns FALSE when the geometry is of an unsupported type.
If an added geometry is changed, the behavior of Visualizer is undefined. Programmers are responsible for calling Geometry() to notify the Visualizer that the geometry has been changed and the Visualizer should be updated accordingly.
Parameters
geometry_ptr The Geometry object.
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 82 of file VisualizerWithVertexSelection.cpp.
References CV_TYPES::BBOX, CV_TYPES::CUSTOM_H_OBJECT, geometry_ptr_, cloudViewer::visualization::Visualizer::geometry_ptrs_, geometry_renderer_ptr_, cloudViewer::visualization::Visualizer::geometry_renderer_ptrs_, CV_TYPES::HALF_EDGE_MESH, CV_TYPES::HIERARCHY_OBJECT, CV_TYPES::IMAGE2, cloudViewer::visualization::Visualizer::is_initialized_, cloudViewer::visualization::RenderOption::LEqual, cloudViewer::visualization::RenderOption::Less, CV_TYPES::LINESET, LogDebug, LogInfo, CV_TYPES::MESH, CV_TYPES::MESH_BASE, CV_TYPES::ORIENTED_BBOX, CV_TYPES::POINT_CLOUD, CV_TYPES::POINT_OCTREE2, cloudViewer::visualization::Visualizer::ResetViewPoint(), CV_TYPES::RGBD_IMAGE, SetPointSize(), CV_TYPES::TETRA_MESH, ui_points_geometry_ptr_, ui_points_renderer_ptr_, ui_selected_points_geometry_ptr_, ui_selected_points_renderer_ptr_, UpdateGeometry(), cloudViewer::visualization::Visualizer::utility_renderer_opts_, cloudViewer::visualization::Visualizer::utility_renderer_ptrs_, cloudViewer::visualization::Visualizer::view_control_ptr_, CV_TYPES::VOXEL_GRID, and cloudViewer::visualization::Visualizer::window_.
Referenced by cloudViewer::visualization::DrawGeometriesWithVertexSelection().
AddPickedPoints()
void cloudViewer::visualization::VisualizerWithVertexSelection::AddPickedPoints (const std::vector< int > indices)
Definition at line 709 of file VisualizerWithVertexSelection.cpp.
References Vector3Tpl< double >::fromArray(), geometry_ptr_, GetGeometryEigenPoints(), GetGeometryPoints(), LogInfo, CV_TYPES::MESH, on_selection_changed_, CV_TYPES::POINT_CLOUD, points, selected_points_, ui_selected_points_geometry_ptr_, and ui_selected_points_renderer_ptr_.
Referenced by MouseButtonCallback(), and cloudViewer::visualization::pybind_visualizer().
BuildUtilities()
void cloudViewer::visualization::VisualizerWithVertexSelection::BuildUtilities () override virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 278 of file VisualizerWithVertexSelection.cpp.
References cloudViewer::visualization::Visualizer::BuildUtilities(), geometry_ptr_, cloudViewer::visualization::Visualizer::geometry_ptrs_, pointcloud_picker_ptr_, pointcloud_picker_renderer_ptr_, selection_polygon_ptr_, selection_polygon_renderer_ptr_, cloudViewer::visualization::Visualizer::utility_ptrs_, and cloudViewer::visualization::Visualizer::utility_renderer_ptrs_.
CalcDragDelta()
Eigen::Vector3d cloudViewer::visualization::VisualizerWithVertexSelection::CalcDragDelta (double winX, double winY) protected
Definition at line 848 of file VisualizerWithVertexSelection.cpp.
References drag_depth_, mouse_down_pos_, cloudViewer::visualization::gl_util::Unproject(), and cloudViewer::visualization::Visualizer::view_control_ptr_.
Referenced by MouseButtonCallback(), and MouseMoveCallback().
ClearPickedPoints()
void cloudViewer::visualization::VisualizerWithVertexSelection::ClearPickedPoints ()
Definition at line 698 of file VisualizerWithVertexSelection.cpp.
References LogInfo, None, selected_points_, selected_points_before_drag_, selection_mode_, ui_selected_points_geometry_ptr_, and ui_selected_points_renderer_ptr_.
Referenced by cloudViewer::visualization::pybind_visualizer(), and UpdateGeometry().
DragSelectedPoints()
void cloudViewer::visualization::VisualizerWithVertexSelection::DragSelectedPoints (const Eigen::Vector3d & delta, DragType type) protected
Definition at line 770 of file VisualizerWithVertexSelection.cpp.
References DRAG_END, DRAG_MOVING, on_selection_moved_, on_selection_moving_, selected_points_, selected_points_before_drag_, type, ui_selected_points_geometry_ptr_, and ui_selected_points_renderer_ptr_.
Referenced by MouseButtonCallback(), and MouseMoveCallback().
GetDepth()
float cloudViewer::visualization::VisualizerWithVertexSelection::GetDepth (int winX, int winY) protected
Definition at line 313 of file VisualizerWithVertexSelection.cpp.
References cloudViewer::visualization::Visualizer::geometry_renderer_ptrs_, cloudViewer::visualization::Visualizer::GetRenderOption(), cloudViewer::visualization::Visualizer::GetViewControl(), height, cloudViewer::visualization::Visualizer::view_control_ptr_, and width.
Referenced by MouseButtonCallback().
GetGeometryEigenPoints()
const std::vector< Eigen::Vector3d > * cloudViewer::visualization::VisualizerWithVertexSelection::GetGeometryEigenPoints (std::shared_ptr< const ccHObject > geometry) protected
Definition at line 790 of file VisualizerWithVertexSelection.cpp.
References CV_TYPES::BBOX, CV_TYPES::CUSTOM_H_OBJECT, CV_TYPES::HALF_EDGE_MESH, CV_TYPES::IMAGE2, CV_TYPES::LINESET, CV_TYPES::ORIENTED_BBOX, CV_TYPES::POINT_OCTREE2, points, CV_TYPES::RGBD_IMAGE, CV_TYPES::TETRA_MESH, and CV_TYPES::VOXEL_GRID.
Referenced by AddPickedPoints(), and UpdateGeometry().
GetGeometryPoints()
const std::vector< CCVector3 > * cloudViewer::visualization::VisualizerWithVertexSelection::GetGeometryPoints (std::shared_ptr< const ccHObject > geometry) protected
Definition at line 820 of file VisualizerWithVertexSelection.cpp.
References CV_TYPES::BBOX, CV_TYPES::CUSTOM_H_OBJECT, CV_TYPES::IMAGE2, CV_TYPES::MESH, CV_TYPES::ORIENTED_BBOX, CV_TYPES::POINT_CLOUD, CV_TYPES::POINT_OCTREE2, points, CV_TYPES::PRIMITIVE, CV_TYPES::RGBD_IMAGE, and CV_TYPES::VOXEL_GRID.
Referenced by AddPickedPoints(), and UpdateGeometry().
GetPickedPoints()
std::vector< VisualizerWithVertexSelection::PickedPoint > cloudViewer::visualization::VisualizerWithVertexSelection::GetPickedPoints () const
Definition at line 426 of file VisualizerWithVertexSelection.cpp.
References points, and selected_points_.
Referenced by cloudViewer::visualization::pybind_visualizer().
InitRenderOption()
bool cloudViewer::visualization::VisualizerWithVertexSelection::InitRenderOption () override protected virtual
Function to initialize RenderOption.
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 442 of file VisualizerWithVertexSelection.cpp.
References cloudViewer::visualization::Visualizer::render_option_ptr_.
InitViewControl()
bool cloudViewer::visualization::VisualizerWithVertexSelection::InitViewControl () override protected virtual
Function to initialize ViewControl.
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 435 of file VisualizerWithVertexSelection.cpp.
References cloudViewer::visualization::Visualizer::ResetViewPoint(), and cloudViewer::visualization::Visualizer::view_control_ptr_.
InvalidatePicking()
void cloudViewer::visualization::VisualizerWithVertexSelection::InvalidatePicking () protected
Definition at line 691 of file VisualizerWithVertexSelection.cpp.
References pointcloud_picker_ptr_, and pointcloud_picker_renderer_ptr_.
InvalidateSelectionPolygon()
void cloudViewer::visualization::VisualizerWithVertexSelection::InvalidateSelectionPolygon () protected
Definition at line 682 of file VisualizerWithVertexSelection.cpp.
References None, points_in_rect_, selection_mode_, selection_polygon_ptr_, and selection_polygon_renderer_ptr_.
Referenced by KeyPressCallback(), MouseButtonCallback(), MouseMoveCallback(), and WindowResizeCallback().
KeyPressCallback()
void cloudViewer::visualization::VisualizerWithVertexSelection::KeyPressCallback (GLFWwindow * window, int key, int scancode, int action, int mods) override protected virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 470 of file VisualizerWithVertexSelection.cpp.
References InvalidateSelectionPolygon(), cloudViewer::visualization::Visualizer::is_redraw_required_, cloudViewer::visualization::Visualizer::KeyPressCallback(), LogDebug, pick_point_opts_, cloudViewer::visualization::RenderOption::point_size_, points_in_rect_, RemovePickedPoints(), SetPointSize(), ui_points_renderer_ptr_, ui_selected_points_geometry_ptr_, ui_selected_points_renderer_ptr_, UpdateWindowTitle(), cloudViewer::visualization::Visualizer::utility_renderer_ptrs_, and cloudViewer::visualization::Visualizer::view_control_ptr_.
MouseButtonCallback()
void cloudViewer::visualization::VisualizerWithVertexSelection::MouseButtonCallback (GLFWwindow * window, int button, int action, int mods) override protected virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 594 of file VisualizerWithVertexSelection.cpp.
References AddPickedPoints(), CalcDragDelta(), drag_depth_, DRAG_END, DragSelectedPoints(), GetDepth(), InvalidateSelectionPolygon(), cloudViewer::visualization::Visualizer::is_redraw_required_, LogInfo, mouse_down_pos_, cloudViewer::visualization::Visualizer::MouseButtonCallback(), Moving, None, PickPoints(), Point, Rectangle, RemovePickedPoints(), selected_points_, selected_points_before_drag_, selection_mode_, selection_polygon_ptr_, and cloudViewer::visualization::Visualizer::view_control_ptr_.
MouseMoveCallback()
void cloudViewer::visualization::VisualizerWithVertexSelection::MouseMoveCallback (GLFWwindow * window, double x, double y) override protected virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 551 of file VisualizerWithVertexSelection.cpp.
References abs(), CalcDragDelta(), DRAG_MOVING, DragSelectedPoints(), InvalidateSelectionPolygon(), cloudViewer::visualization::Visualizer::is_redraw_required_, mouse_down_pos_, cloudViewer::visualization::Visualizer::MouseMoveCallback(), Moving, None, Point, Rectangle, selection_mode_, selection_polygon_ptr_, selection_polygon_renderer_ptr_, and cloudViewer::visualization::Visualizer::view_control_ptr_.
MouseScrollCallback()
void cloudViewer::visualization::VisualizerWithVertexSelection::MouseScrollCallback (GLFWwindow * window, double x, double y) override protected virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 588 of file VisualizerWithVertexSelection.cpp.
References cloudViewer::visualization::Visualizer::MouseScrollCallback().
operator=()
VisualizerWithVertexSelection& cloudViewer::visualization::VisualizerWithVertexSelection::operator= (const VisualizerWithVertexSelection &) delete
PickPoints()
std::vector< int > cloudViewer::visualization::VisualizerWithVertexSelection::PickPoints (double x, double y, double w, double h)
Definition at line 353 of file VisualizerWithVertexSelection.cpp.
References cloudViewer::utility::ceil(), cloudViewer::visualization::gl_util::ColorCodeToPickIndex(), cloudViewer::visualization::Visualizer::geometry_renderer_ptrs_, cloudViewer::visualization::Visualizer::GetRenderOption(), cloudViewer::visualization::Visualizer::GetViewControl(), height, CV_TYPES::MESH, pick_point_opts_, points_in_rect_, ui_points_geometry_ptr_, cloudViewer::visualization::Visualizer::view_control_ptr_, and width.
Referenced by MouseButtonCallback(), and cloudViewer::visualization::pybind_visualizer().
PrintVisualizerHelp()
void cloudViewer::visualization::VisualizerWithVertexSelection::PrintVisualizerHelp () override virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 250 of file VisualizerWithVertexSelection.cpp.
References LogInfo, and cloudViewer::visualization::Visualizer::PrintVisualizerHelp().
RegisterSelectionChangedCallback()
void cloudViewer::visualization::VisualizerWithVertexSelection::RegisterSelectionChangedCallback (std::function< void()> f)
Definition at line 448 of file VisualizerWithVertexSelection.cpp.
References on_selection_changed_.
RegisterSelectionMovedCallback()
void cloudViewer::visualization::VisualizerWithVertexSelection::RegisterSelectionMovedCallback (std::function< void()> f)
Definition at line 458 of file VisualizerWithVertexSelection.cpp.
References on_selection_moved_.
Referenced by cloudViewer::visualization::pybind_visualizer().
RegisterSelectionMovingCallback()
void cloudViewer::visualization::VisualizerWithVertexSelection::RegisterSelectionMovingCallback (std::function< void()> f)
Do not change the number of vertices in geometry, but can change the vertex values and call UpdateGeometry().
Definition at line 453 of file VisualizerWithVertexSelection.cpp.
References on_selection_moving_.
RemovePickedPoints()
void cloudViewer::visualization::VisualizerWithVertexSelection::RemovePickedPoints (const std::vector< int > indices)
Definition at line 752 of file VisualizerWithVertexSelection.cpp.
References LogInfo, on_selection_changed_, selected_points_, ui_selected_points_geometry_ptr_, and ui_selected_points_renderer_ptr_.
Referenced by KeyPressCallback(), MouseButtonCallback(), and cloudViewer::visualization::pybind_visualizer().
SetPointSize()
void cloudViewer::visualization::VisualizerWithVertexSelection::SetPointSize (double size)
Definition at line 862 of file VisualizerWithVertexSelection.cpp.
References max(), pick_point_opts_, cloudViewer::visualization::RenderOption::SetPointSize(), size, ui_points_renderer_ptr_, ui_selected_points_renderer_ptr_, and cloudViewer::visualization::Visualizer::utility_renderer_opts_.
Referenced by AddGeometry(), and KeyPressCallback().
UpdateGeometry()
bool cloudViewer::visualization::VisualizerWithVertexSelection::UpdateGeometry (std::shared_ptr< const ccHObject > geometry_ptr = nullptr) override virtual
Function to update geometry.
This function must be called when geometry has been changed. Otherwise the behavior of Visualizer is undefined. If called without an argument, updates all geometries, otherwise only updates the geometry specified.
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 162 of file VisualizerWithVertexSelection.cpp.
References CV_TYPES::BBOX, ClearPickedPoints(), CV_TYPES::CUSTOM_H_OBJECT, geometry_ptr_, geometry_renderer_ptr_, GetGeometryEigenPoints(), GetGeometryPoints(), CV_TYPES::HALF_EDGE_MESH, CV_TYPES::IMAGE2, CV_TYPES::LINESET, LogDebug, CV_TYPES::MESH, CV_TYPES::ORIENTED_BBOX, CV_TYPES::POINT_CLOUD, CV_TYPES::POINT_OCTREE2, result, CV_TYPES::RGBD_IMAGE, cloudViewer::PointCloudTpl< T >::size(), size, CV_TYPES::TETRA_MESH, ccHObjectCaster::ToPointCloud(), ui_points_geometry_ptr_, ui_points_renderer_ptr_, cloudViewer::visualization::Visualizer::UpdateGeometry(), and CV_TYPES::VOXEL_GRID.
Referenced by AddGeometry().
UpdateWindowTitle()
void cloudViewer::visualization::VisualizerWithVertexSelection::UpdateWindowTitle () override virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 270 of file VisualizerWithVertexSelection.cpp.
References cloudViewer::visualization::Visualizer::view_control_ptr_, cloudViewer::visualization::Visualizer::window_, and cloudViewer::visualization::Visualizer::window_name_.
Referenced by KeyPressCallback().
WindowResizeCallback()
void cloudViewer::visualization::VisualizerWithVertexSelection::WindowResizeCallback (GLFWwindow * window, int w, int h) override protected virtual
Reimplemented from cloudViewer::visualization::Visualizer.
Definition at line 463 of file VisualizerWithVertexSelection.cpp.
References InvalidateSelectionPolygon(), and cloudViewer::visualization::Visualizer::WindowResizeCallback().
Member Data Documentation
drag_depth_
float cloudViewer::visualization::VisualizerWithVertexSelection::drag_depth_ = 0.0f protected
Definition at line 95 of file VisualizerWithVertexSelection.h.
Referenced by CalcDragDelta(), and MouseButtonCallback().
geometry_ptr_
std::shared_ptr<const ccHObject> cloudViewer::visualization::VisualizerWithVertexSelection::geometry_ptr_ protected
Definition at line 101 of file VisualizerWithVertexSelection.h.
Referenced by AddGeometry(), AddPickedPoints(), BuildUtilities(), and UpdateGeometry().
geometry_renderer_ptr_
std::shared_ptr<glsl::GeometryRenderer> cloudViewer::visualization::VisualizerWithVertexSelection::geometry_renderer_ptr_ protected
Definition at line 102 of file VisualizerWithVertexSelection.h.
Referenced by AddGeometry(), and UpdateGeometry().
mouse_down_pos_
Eigen::Vector2d cloudViewer::visualization::VisualizerWithVertexSelection::mouse_down_pos_ protected
Definition at line 93 of file VisualizerWithVertexSelection.h.
Referenced by CalcDragDelta(), MouseButtonCallback(), and MouseMoveCallback().
on_selection_changed_
std::function<void()> cloudViewer::visualization::VisualizerWithVertexSelection::on_selection_changed_ protected
Definition at line 114 of file VisualizerWithVertexSelection.h.
Referenced by AddPickedPoints(), RegisterSelectionChangedCallback(), and RemovePickedPoints().
on_selection_moved_
std::function<void()> cloudViewer::visualization::VisualizerWithVertexSelection::on_selection_moved_ protected
Definition at line 116 of file VisualizerWithVertexSelection.h.
Referenced by DragSelectedPoints(), and RegisterSelectionMovedCallback().
on_selection_moving_
std::function<void()> cloudViewer::visualization::VisualizerWithVertexSelection::on_selection_moving_ protected
Definition at line 115 of file VisualizerWithVertexSelection.h.
Referenced by DragSelectedPoints(), and RegisterSelectionMovingCallback().
pick_point_opts_
RenderOption cloudViewer::visualization::VisualizerWithVertexSelection::pick_point_opts_ protected
Definition at line 104 of file VisualizerWithVertexSelection.h.
Referenced by KeyPressCallback(), PickPoints(), and SetPointSize().
pointcloud_picker_ptr_
std::shared_ptr<PointCloudPicker> cloudViewer::visualization::VisualizerWithVertexSelection::pointcloud_picker_ptr_ protected
Definition at line 97 of file VisualizerWithVertexSelection.h.
Referenced by BuildUtilities(), and InvalidatePicking().
pointcloud_picker_renderer_ptr_
std::shared_ptr<glsl::PointCloudPickerRenderer> cloudViewer::visualization::VisualizerWithVertexSelection::pointcloud_picker_renderer_ptr_ protected
Definition at line 99 of file VisualizerWithVertexSelection.h.
Referenced by BuildUtilities(), and InvalidatePicking().
points_in_rect_
std::vector<int> cloudViewer::visualization::VisualizerWithVertexSelection::points_in_rect_ protected
Definition at line 94 of file VisualizerWithVertexSelection.h.
Referenced by InvalidateSelectionPolygon(), KeyPressCallback(), and PickPoints().
selected_points_
std::unordered_map<int, Eigen::Vector3d> cloudViewer::visualization::VisualizerWithVertexSelection::selected_points_ protected
Definition at line 109 of file VisualizerWithVertexSelection.h.
Referenced by AddPickedPoints(), ClearPickedPoints(), DragSelectedPoints(), GetPickedPoints(), MouseButtonCallback(), and RemovePickedPoints().
selected_points_before_drag_
std::unordered_map<int, Eigen::Vector3d> cloudViewer::visualization::VisualizerWithVertexSelection::selected_points_before_drag_ protected
Definition at line 110 of file VisualizerWithVertexSelection.h.
Referenced by ClearPickedPoints(), DragSelectedPoints(), and MouseButtonCallback().
selection_mode_
SelectionMode cloudViewer::visualization::VisualizerWithVertexSelection::selection_mode_ = SelectionMode::None protected
Definition at line 92 of file VisualizerWithVertexSelection.h.
Referenced by ClearPickedPoints(), InvalidateSelectionPolygon(), MouseButtonCallback(), and MouseMoveCallback().
selection_polygon_ptr_
std::shared_ptr<SelectionPolygon> cloudViewer::visualization::VisualizerWithVertexSelection::selection_polygon_ptr_ protected
Definition at line 89 of file VisualizerWithVertexSelection.h.
Referenced by BuildUtilities(), InvalidateSelectionPolygon(), MouseButtonCallback(), and MouseMoveCallback().
selection_polygon_renderer_ptr_
std::shared_ptr<glsl::SelectionPolygonRenderer> cloudViewer::visualization::VisualizerWithVertexSelection::selection_polygon_renderer_ptr_ protected
Definition at line 91 of file VisualizerWithVertexSelection.h.
Referenced by BuildUtilities(), InvalidateSelectionPolygon(), and MouseMoveCallback().
ui_points_geometry_ptr_
std::shared_ptr<ccPointCloud> cloudViewer::visualization::VisualizerWithVertexSelection::ui_points_geometry_ptr_ protected
Definition at line 106 of file VisualizerWithVertexSelection.h.
Referenced by AddGeometry(), PickPoints(), and UpdateGeometry().
ui_points_renderer_ptr_
std::shared_ptr<glsl::GeometryRenderer> cloudViewer::visualization::VisualizerWithVertexSelection::ui_points_renderer_ptr_ protected
Definition at line 107 of file VisualizerWithVertexSelection.h.
Referenced by AddGeometry(), KeyPressCallback(), SetPointSize(), and UpdateGeometry().
ui_selected_points_geometry_ptr_
std::shared_ptr<ccPointCloud> cloudViewer::visualization::VisualizerWithVertexSelection::ui_selected_points_geometry_ptr_ protected
Definition at line 111 of file VisualizerWithVertexSelection.h.
Referenced by AddGeometry(), AddPickedPoints(), ClearPickedPoints(), DragSelectedPoints(), KeyPressCallback(), and RemovePickedPoints().
ui_selected_points_renderer_ptr_
std::shared_ptr<glsl::GeometryRenderer> cloudViewer::visualization::VisualizerWithVertexSelection::ui_selected_points_renderer_ptr_ protected
Definition at line 112 of file VisualizerWithVertexSelection.h.
Referenced by AddGeometry(), AddPickedPoints(), ClearPickedPoints(), DragSelectedPoints(), KeyPressCallback(), RemovePickedPoints(), and SetPointSize().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/VisualizerWithVertexSelection.h
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/VisualizerWithVertexSelection.cpp