ACloudViewer: GetNeighborLeavesVisitor Class Reference
GetNeighborLeavesVisitor Class Reference
Recursive visitor for ccKdTree::getNeighborLeaves.
Public Member Functions
GetNeighborLeavesVisitor (ccKdTree::BaseNode *cell, ccKdTree::LeafSet &neighbors, const ccBBox &cellBox, const ccBBox &treeBox)
void setUserDataFilter (int value)
void visit (ccKdTree::BaseNode *node)
Protected Attributes
ccKdTree::BaseNode * m_targetCell
ccBBox m_targetCellBox
ccBBox m_currentCellBox
ccKdTree::LeafSet * m_neighbors
bool m_userDataFilterEnabled
int m_userDataFilterValue
Detailed Description
Recursive visitor for ccKdTree::getNeighborLeaves.
Definition at line 269 of file ecvKdTree.cpp.
Constructor & Destructor Documentation
GetNeighborLeavesVisitor()
GetNeighborLeavesVisitor::GetNeighborLeavesVisitor (ccKdTree::BaseNode * cell, ccKdTree::LeafSet & neighbors, const ccBBox & cellBox, const ccBBox & treeBox) inline
Definition at line 271 of file ecvKdTree.cpp.
Member Function Documentation
setUserDataFilter()
void GetNeighborLeavesVisitor::setUserDataFilter (int value) inline
Definition at line 282 of file ecvKdTree.cpp.
References m_userDataFilterEnabled, and m_userDataFilterValue.
Referenced by ccKdTree::getNeighborLeaves().
visit()
void GetNeighborLeavesVisitor::visit (ccKdTree::BaseNode * node) inline
Definition at line 287 of file ecvKdTree.cpp.
References cloudViewer::TrueKdTree::BaseNode::isNode(), cloudViewer::TrueKdTree::Node::leftChild, m_currentCellBox, m_neighbors, m_targetCell, m_targetCellBox, m_userDataFilterEnabled, m_userDataFilterValue, cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), cloudViewer::BoundingBoxTpl< T >::minDistTo(), cloudViewer::TrueKdTree::Node::rightChild, cloudViewer::TrueKdTree::Node::splitDim, cloudViewer::TrueKdTree::Node::splitValue, Tuple3Tpl< Type >::u, and cloudViewer::TrueKdTree::Leaf::userData.
Referenced by ccKdTree::getNeighborLeaves().
Member Data Documentation
m_currentCellBox
ccBBox GetNeighborLeavesVisitor::m_currentCellBox protected
Definition at line 329 of file ecvKdTree.cpp.
Referenced by visit().
m_neighbors
ccKdTree::LeafSet* GetNeighborLeavesVisitor::m_neighbors protected
Definition at line 330 of file ecvKdTree.cpp.
Referenced by visit().
m_targetCell
ccKdTree::BaseNode* GetNeighborLeavesVisitor::m_targetCell protected
Definition at line 327 of file ecvKdTree.cpp.
Referenced by visit().
m_targetCellBox
ccBBox GetNeighborLeavesVisitor::m_targetCellBox protected
Definition at line 328 of file ecvKdTree.cpp.
Referenced by visit().
m_userDataFilterEnabled
bool GetNeighborLeavesVisitor::m_userDataFilterEnabled protected
Definition at line 331 of file ecvKdTree.cpp.
Referenced by setUserDataFilter(), and visit().
m_userDataFilterValue
int GetNeighborLeavesVisitor::m_userDataFilterValue protected
Definition at line 332 of file ecvKdTree.cpp.
Referenced by setUserDataFilter(), and visit().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/src/ecvKdTree.cpp