ACloudViewer: cloudViewer::core::MemoryManagerCached Class Reference
cloudViewer::core::MemoryManagerCached Class Reference
#include <MemoryManager.h>
Public Member Functions
MemoryManagerCached (const std::shared_ptr< MemoryManagerDevice > &device_mm)
void * Malloc (size_t byte_size, const Device &device) override
void Free (void *ptr, const Device &device) override
Frees previously allocated memory at address ptr on device device.
void Memcpy (void *dst_ptr, const Device &dst_device, const void *src_ptr, const Device &src_device, size_t num_bytes) override
Public Member Functions inherited from cloudViewer::core::MemoryManagerDevice
virtual ~MemoryManagerDevice ()=default
Static Public Member Functions
static void ReleaseCache (const Device &device)
Frees all releasable memory blocks on device device.
static void ReleaseCache ()
Protected Attributes
std::shared_ptr< MemoryManagerDevice > device_mm_
Detailed Description
Generic cached memory manager. This class can be used to speed-up memory allocations and deallocations from arbitrary direct memory managers.
Successful queries, i.e. cache hits, will result in constant-time allocations, but small direct allocations might still be faster.
Failed queries, i.e. cache misses, will result in direct allocations.
Direct frees will be delayed until either the end of the program or a cache release is triggered.
(Partial) cache releases will be triggered either manually by calling ReleaseCache or automatically if a direct allocation fails after observing a cache miss.
Definition at line 105 of file MemoryManager.h.
Constructor & Destructor Documentation
MemoryManagerCached()
cloudViewer::core::MemoryManagerCached::MemoryManagerCached (const std::shared_ptr< MemoryManagerDevice > & device_mm) explicit
Constructs a cached memory manager instance that wraps the existing direct memory manager device_mm.
Definition at line 474 of file MemoryManagerCached.cpp.
References device_mm_, and LogError.
Member Function Documentation
Free()
void cloudViewer::core::MemoryManagerCached::Free (void * ptr, const Device & device) override virtual
Frees previously allocated memory at address ptr on device device.
Implements cloudViewer::core::MemoryManagerDevice.
Definition at line 492 of file MemoryManagerCached.cpp.
References cloudViewer::core::Cacher::Free(), and cloudViewer::core::Cacher::GetInstance().
Malloc()
void * cloudViewer::core::MemoryManagerCached::Malloc (size_t byte_size, const Device & device) override virtual
Allocates memory of byte_size bytes on device device and returns a pointer to the beginning of the allocated memory block.
Implements cloudViewer::core::MemoryManagerDevice.
Definition at line 484 of file MemoryManagerCached.cpp.
References device_mm_, cloudViewer::core::Cacher::GetInstance(), and cloudViewer::core::Cacher::Malloc().
Memcpy()
void cloudViewer::core::MemoryManagerCached::Memcpy (void * dst_ptr, const Device & dst_device, const void * src_ptr, const Device & src_device, size_t num_bytes) override virtual
Copies num_bytes bytes of memory at address src_ptr on device src_device to address dst_ptr on device dst_device.
Implements cloudViewer::core::MemoryManagerDevice.
Definition at line 500 of file MemoryManagerCached.cpp.
References device_mm_.
ReleaseCache() [1/2]
void cloudViewer::core::MemoryManagerCached::ReleaseCache () static
Frees all releasable memory blocks on all known devices. Note that this may also affect other instances of MemoryManagerCached.
Definition at line 512 of file MemoryManagerCached.cpp.
References cloudViewer::core::Cacher::Clear(), and cloudViewer::core::Cacher::GetInstance().
Referenced by cloudViewer::core::Free(), cloudViewer::core::Malloc(), and cloudViewer::core::cuda::ReleaseCache().
ReleaseCache() [2/2]
void cloudViewer::core::MemoryManagerCached::ReleaseCache (const Device & device) static
Frees all releasable memory blocks on device device.
Definition at line 508 of file MemoryManagerCached.cpp.
References cloudViewer::core::Cacher::Clear(), and cloudViewer::core::Cacher::GetInstance().
Member Data Documentation
device_mm_
std::shared_ptr<MemoryManagerDevice> cloudViewer::core::MemoryManagerCached::device_mm_ protected
Definition at line 136 of file MemoryManager.h.
Referenced by Malloc(), Memcpy(), and MemoryManagerCached().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/core/MemoryManager.h
/root/ACloudViewer/libs/cloudViewer/core/MemoryManagerCached.cpp