ACloudViewer: StereogramDialog Class Reference
StereogramDialog Class Reference
Dialog for displaying the angular repartition of facets (qFacets plugin)
#include <stereogramDlg.h>
Public Member Functions
StereogramDialog (ecvMainAppInterface *app)
Default constructor.
bool init (double angularStep_deg, ccHObject *facetGroup, double resolution_deg=2.0)
Inits dialog.
StereogramWidget * stereogram ()
Returns associated widget.
Protected Slots
void colorScaleChanged (int)
void spawnColorScaleEditor ()
void onTicksFreqChanged (int)
void onHSVColorsToggled (bool)
void onDensityColorStepsChanged (int)
void onFilterEnabled (bool)
void onPointClicked (double, double)
void onFilterSizeChanged (double)
void onFilterCenterChanged (double)
void exportCurrentSelection ()
Protected Member Functions
void closeEvent (QCloseEvent *e)
void updateFacetsFilter (bool enable)
Protected Attributes
StereogramWidget * m_classifWidget
Associated widget.
ccColorScaleSelector * m_colorScaleSelector
Color scale selector/editor.
ecvMainAppInterface * m_app
Main application interface.
int m_facetGroupUniqueID
Associated set of facets (unique ID)
Detailed Description
Dialog for displaying the angular repartition of facets (qFacets plugin)
Definition at line 147 of file stereogramDlg.h.
Constructor & Destructor Documentation
StereogramDialog()
StereogramDialog::StereogramDialog (ecvMainAppInterface * app)
Default constructor.
Definition at line 596 of file stereogramDlg.cpp.
References ccColorScalesManager::BGYR, colorScaleChanged(), exportCurrentSelection(), frame, ccColorScalesManager::getDefaultScale(), ccColorScalesManager::GetDefaultScale(), m_app, m_classifWidget, m_colorScaleSelector, ccColorScale::MAX_STEPS, ccColorScale::MIN_STEPS, cloudViewer::core::Minimum(), onDensityColorStepsChanged(), onFilterCenterChanged(), onFilterEnabled(), onFilterSizeChanged(), onHSVColorsToggled(), onPointClicked(), onTicksFreqChanged(), StereogramWidget::setDensityColorScale(), StereogramWidget::setTicksFreq(), and spawnColorScaleEditor().
Member Function Documentation
closeEvent()
void StereogramDialog::closeEvent (QCloseEvent * e) protected
Definition at line 697 of file stereogramDlg.cpp.
References updateFacetsFilter().
colorScaleChanged
void StereogramDialog::colorScaleChanged (int) protected slot
Definition at line 958 of file stereogramDlg.cpp.
References m_classifWidget, m_colorScaleSelector, StereogramWidget::setDensityColorScale(), and StereogramWidget::setDensityColorScaleSteps().
Referenced by StereogramDialog().
exportCurrentSelection
void StereogramDialog::exportCurrentSelection () protected slot
Definition at line 853 of file stereogramDlg.cpp.
References ccHObject::addChild(), ccFacet::clone(), ccNormalVectors::ConvertNormalToDipAndDipDir(), ccPointCloud::createNewCloudFromVisibilitySelection(), fabs(), CV_TYPES::FACET, ccHObject::filterChildren(), ccHObject::find(), ccHObject::getChildrenNumber(), ccObject::getName(), ccFacet::getNormal(), CV_TYPES::HIERARCHY_OBJECT, ccObject::isA(), ccGenericPointCloud::isVisibilityTableInstantiated(), m_app, m_facetGroupUniqueID, CV_TYPES::POINT_CLOUD, ccObject::setName(), and cloudViewer::GenericCloud::size().
Referenced by StereogramDialog().
init()
bool StereogramDialog::init (double angularStep_deg, ccHObject * facetGroup, double resolution_deg = 2.0)
Inits dialog.
Warning: input 'facetGroup' should not be deleted before this dialog is closed!
Definition at line 667 of file stereogramDlg.cpp.
References ccNormalVectors::ConvertDipAndDipDirToString(), StereogramWidget::getMeanDir(), ccObject::getUniqueID(), StereogramWidget::init(), m_classifWidget, m_facetGroupUniqueID, and updateFacetsFilter().
Referenced by qFacets::showStereogram().
onDensityColorStepsChanged
void StereogramDialog::onDensityColorStepsChanged (int value) protected slot
Definition at line 936 of file stereogramDlg.cpp.
References m_classifWidget, ccColorScale::MIN_STEPS, and StereogramWidget::setDensityColorScaleSteps().
Referenced by StereogramDialog().
onFilterCenterChanged
void StereogramDialog::onFilterCenterChanged (double) protected slot
Definition at line 725 of file stereogramDlg.cpp.
References m_classifWidget, StereogramWidget::setTrackedCenter(), and updateFacetsFilter().
Referenced by StereogramDialog().
onFilterEnabled
void StereogramDialog::onFilterEnabled (bool state) protected slot
Definition at line 704 of file stereogramDlg.cpp.
References StereogramWidget::enableMouseTracking(), m_classifWidget, and updateFacetsFilter().
Referenced by StereogramDialog().
onFilterSizeChanged
void StereogramDialog::onFilterSizeChanged (double) protected slot
Definition at line 715 of file stereogramDlg.cpp.
References StereogramWidget::enableMouseTracking(), m_classifWidget, and updateFacetsFilter().
Referenced by StereogramDialog().
onHSVColorsToggled
void StereogramDialog::onHSVColorsToggled (bool state) protected slot
Definition at line 951 of file stereogramDlg.cpp.
References m_classifWidget, and StereogramWidget::showHSVRing().
Referenced by StereogramDialog().
onPointClicked
void StereogramDialog::onPointClicked (double dip_deg, double dipDir_deg) protected slot
Definition at line 735 of file stereogramDlg.cpp.
References m_classifWidget, and updateFacetsFilter().
Referenced by StereogramDialog().
onTicksFreqChanged
void StereogramDialog::onTicksFreqChanged (int value) protected slot
Definition at line 944 of file stereogramDlg.cpp.
References m_classifWidget, and StereogramWidget::setTicksFreq().
Referenced by StereogramDialog().
spawnColorScaleEditor
void StereogramDialog::spawnColorScaleEditor () protected slot
Definition at line 969 of file stereogramDlg.cpp.
References ccColorScalesManager::BGYR, m_app, and m_colorScaleSelector.
Referenced by StereogramDialog().
stereogram()
StereogramWidget* StereogramDialog::stereogram () inline
Returns associated widget.
Definition at line 163 of file stereogramDlg.h.
References m_classifWidget.
updateFacetsFilter()
void StereogramDialog::updateFacetsFilter (bool enable) protected
Changes the associated facets visibility based on the current filter parameters
Definition at line 753 of file stereogramDlg.cpp.
References ccNormalVectors::ConvertNormalToDipAndDipDir(), count, fabs(), CV_TYPES::FACET, ccHObject::filterChildren(), ccHObject::find(), ccFacet::getContour(), ccFacet::getNormal(), ccPointCloud::getPointNormal(), ccFacet::getPolygon(), ccGenericPointCloud::getTheVisibilityArray(), ccPointCloud::hasNormals(), CV_TYPES::HIERARCHY_OBJECT, ccObject::isA(), m_app, m_facetGroupUniqueID, CV_TYPES::POINT_CLOUD, POINT_HIDDEN, POINT_VISIBLE, ccGenericPointCloud::resetVisibilityArray(), ccDrawableObject::setRedraw(), ecvDisplayTools::SetRedrawRecursive(), ccDrawableObject::setVisible(), ccPolyline::setWidth(), cloudViewer::PointCloudTpl< T >::size(), and ccGenericPointCloud::unallocateVisibilityArray().
Referenced by closeEvent(), init(), onFilterCenterChanged(), onFilterEnabled(), onFilterSizeChanged(), and onPointClicked().
Member Data Documentation
m_app
ecvMainAppInterface* StereogramDialog::m_app protected
Main application interface.
Definition at line 193 of file stereogramDlg.h.
Referenced by exportCurrentSelection(), spawnColorScaleEditor(), StereogramDialog(), and updateFacetsFilter().
m_classifWidget
StereogramWidget* StereogramDialog::m_classifWidget protected
Associated widget.
Definition at line 187 of file stereogramDlg.h.
Referenced by colorScaleChanged(), init(), onDensityColorStepsChanged(), onFilterCenterChanged(), onFilterEnabled(), onFilterSizeChanged(), onHSVColorsToggled(), onPointClicked(), onTicksFreqChanged(), stereogram(), and StereogramDialog().
m_colorScaleSelector
ccColorScaleSelector* StereogramDialog::m_colorScaleSelector protected
Color scale selector/editor.
Definition at line 190 of file stereogramDlg.h.
Referenced by colorScaleChanged(), spawnColorScaleEditor(), and StereogramDialog().
m_facetGroupUniqueID
int StereogramDialog::m_facetGroupUniqueID protected
Associated set of facets (unique ID)
Definition at line 196 of file stereogramDlg.h.
Referenced by exportCurrentSelection(), init(), and updateFacetsFilter().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qFacets/include/stereogramDlg.h
/root/ACloudViewer/plugins/core/Standard/qFacets/src/stereogramDlg.cpp