ACloudViewer: cvProtractorTool Class Reference
cvProtractorTool Class Reference
#include <cvProtractorTool.h>
Public Member Functions
cvProtractorTool (QWidget *parent=nullptr)
~cvProtractorTool () override
virtual void start () override
virtual void reset () override
virtual void showWidget (bool state) override
virtual ccHObject * getOutput () override
virtual double getMeasurementValue () const override
Get measurement value (distance or angle)
virtual void getPoint1 (double pos[3]) const override
Get point 1 coordinates.
virtual void getPoint2 (double pos[3]) const override
Get point 2 coordinates.
virtual void getCenter (double pos[3]) const override
Get center point coordinates (for angle/protractor)
virtual void setPoint1 (double pos[3]) override
Set point 1 coordinates.
virtual void setPoint2 (double pos[3]) override
Set point 2 coordinates.
virtual void setCenter (double pos[3]) override
Set center point coordinates (for angle/protractor)
virtual void setColor (double r, double g, double b) override
Set measurement color (RGB values in range [0.0, 1.0])
virtual bool getColor (double &r, double &g, double &b) const override
virtual void lockInteraction () override
Lock tool interaction (disable VTK widget interaction and UI controls)
virtual void unlockInteraction () override
Unlock tool interaction (enable VTK widget interaction and UI controls)
virtual void setInstanceLabel (const QString &label) override
Set instance label suffix (e.g., "#1", "#2") for display in 3D view.
Public Member Functions inherited from cvGenericMeasurementTool
cvGenericMeasurementTool (QWidget *parent=nullptr)
virtual ~cvGenericMeasurementTool ()
virtual void update ()
virtual bool initModel ()
virtual bool setInput (ccHObject *obj)
virtual void clearAllActor ()
virtual void setFontFamily (const QString &family)
virtual void setFontSize (int size)
Set font size for measurement labels.
virtual void setBold (bool bold)
Set font bold state for measurement labels.
virtual void setItalic (bool italic)
Set font italic state for measurement labels.
virtual void setShadow (bool shadow)
Set font shadow state for measurement labels.
virtual void setFontOpacity (double opacity)
Set font opacity for measurement labels (0.0 to 1.0)
virtual void setFontColor (double r, double g, double b)
Set font color for measurement labels (RGB values 0.0-1.0)
virtual void setHorizontalJustification (const QString &justification)
virtual void setVerticalJustification (const QString &justification)
QString getFontFamily () const
Get font properties (for UI synchronization)
int getFontSize () const
void getFontColor (double &r, double &g, double &b) const
bool getFontBold () const
bool getFontItalic () const
bool getFontShadow () const
double getFontOpacity () const
QString getHorizontalJustification () const
QString getVerticalJustification () const
void setUpViewer (PclUtils::PCLVis *viewer)
void setInteractor (vtkRenderWindowInteractor *interactor)
vtkRenderWindowInteractor * getInteractor ()
vtkRenderer * getRenderer ()
void setupShortcuts (QWidget *vtkWidget)
void disableShortcuts ()
Disable all keyboard shortcuts (call before tool destruction)
void clearPickingCache ()
Protected Member Functions
virtual void initTool () override
virtual void createUi () override
virtual void setupPointPickingShortcuts (QWidget *vtkWidget) override
Protected Member Functions inherited from cvGenericMeasurementTool
virtual void modelReady ()
virtual void dataChanged ()
void safeOff (vtkAbstractWidget *widget)
void updatePickingHelpers ()
Update point picking helpers with current interactor/renderer.
void addActor (const vtkSmartPointer< vtkProp > actor)
void removeActor (const vtkSmartPointer< vtkProp > actor)
Additional Inherited Members
Signals inherited from cvGenericMeasurementTool
void measurementValueChanged ()
Signal sent when the measurement value changes.
void pointPickingRequested (int pointIndex)
void pointPickingCancelled ()
Signal sent when point picking is cancelled.
Protected Attributes inherited from cvGenericMeasurementTool
Ui::GenericMeasurementToolDlg * m_ui = nullptr
std::string m_id
ccHObject * m_entity = nullptr
PclUtils::PCLVis * m_viewer = nullptr
vtkRenderWindowInteractor * m_interactor = nullptr
vtkRenderer * m_renderer = nullptr
vtkSmartPointer< vtkActor > m_modelActor
QList< cvPointPickingHelper * > m_pickingHelpers
List of point picking helpers for keyboard shortcuts.
QWidget * m_vtkWidget = nullptr
VTK widget reference for creating shortcuts (saved from linkWith)
QString m_fontFamily = "Arial"
Font properties for measurement labels (shared by all tools)
int m_fontSize = 6
double m_fontColor [3] = {1.0, 1.0, 1.0}
bool m_fontBold = false
bool m_fontItalic = false
bool m_fontShadow = true
double m_fontOpacity = 1.0
QString m_horizontalJustification = "Left"
QString m_verticalJustification = "Bottom"
Detailed Description
Definition at line 20 of file cvProtractorTool.h.
Constructor & Destructor Documentation
cvProtractorTool()
cvProtractorTool::cvProtractorTool (QWidget * parent = nullptr) explicit
Definition at line 102 of file cvProtractorTool.cpp.
References cvGenericMeasurementTool::m_fontSize.
~cvProtractorTool()
cvProtractorTool::~cvProtractorTool () override
Definition at line 111 of file cvProtractorTool.cpp.
References cvGenericMeasurementTool::m_interactor.
Member Function Documentation
createUi()
void cvProtractorTool::createUi () override protected virtual
Reimplemented from cvGenericMeasurementTool.
Definition at line 254 of file cvProtractorTool.cpp.
References CVLog::Error(), cvGenericMeasurementTool::m_ui, and cloudViewer::core::Minimum().
getCenter()
void cvProtractorTool::getCenter (double pos[3]) const override virtual
Get center point coordinates (for angle/protractor)
Reimplemented from cvGenericMeasurementTool.
Definition at line 813 of file cvProtractorTool.cpp.
Referenced by getOutput().
getColor()
bool cvProtractorTool::getColor (double & r, double & g, double & b) const override virtual
Get measurement color (RGB values in range [0.0, 1.0]) Returns false if not implemented, true if color is retrieved
Reimplemented from cvGenericMeasurementTool.
Definition at line 948 of file cvProtractorTool.cpp.
getMeasurementValue()
double cvProtractorTool::getMeasurementValue () const override virtual
Get measurement value (distance or angle)
Reimplemented from cvGenericMeasurementTool.
Definition at line 786 of file cvProtractorTool.cpp.
Referenced by getOutput().
getOutput()
ccHObject * cvProtractorTool::getOutput () override virtual
Reimplemented from cvGenericMeasurementTool.
Definition at line 571 of file cvProtractorTool.cpp.
References cc2DLabel::addPickedPoint(), cloudViewer::PointCloudTpl< T >::addPoint(), cc2DLabel::displayPointLegend(), ccGenericMesh::getAssociatedCloud(), getCenter(), getMeasurementValue(), cloudViewer::GenericIndexedCloud::getPoint(), getPoint1(), getPoint2(), ccObject::isKindOf(), cvGenericMeasurementTool::m_entity, cvGenericMeasurementTool::m_interactor, cvGenericMeasurementTool::m_renderer, CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, CVLog::Print(), CVLog::PrintVerbose(), ccPointCloud::reserve(), cc2DLabel::setCollapsed(), cc2DLabel::setDisplayedIn2D(), ccObject::setEnabled(), cc2DLabel::setPosition(), ccDrawableObject::setVisible(), cloudViewer::GenericCloud::size(), cloudViewer::PointCloudTpl< T >::size(), ccHObjectCaster::ToPointCloud(), and CVLog::Warning().
getPoint1()
void cvProtractorTool::getPoint1 (double pos[3]) const override virtual
Get point 1 coordinates.
Reimplemented from cvGenericMeasurementTool.
Definition at line 793 of file cvProtractorTool.cpp.
Referenced by getOutput().
getPoint2()
void cvProtractorTool::getPoint2 (double pos[3]) const override virtual
Get point 2 coordinates.
Reimplemented from cvGenericMeasurementTool.
Definition at line 803 of file cvProtractorTool.cpp.
Referenced by getOutput().
initTool()
void cvProtractorTool::initTool () override protected virtual
Reimplemented from cvGenericMeasurementTool.
Definition at line 141 of file cvProtractorTool.cpp.
References ccHObject::getBB_recursive(), cloudViewer::BoundingBoxTpl< T >::getCenter(), cloudViewer::BoundingBoxTpl< T >::getDiagVec(), cloudViewer::BoundingBoxTpl< T >::isValid(), cvGenericMeasurementTool::m_entity, cvGenericMeasurementTool::m_interactor, cvGenericMeasurementTool::m_renderer, Vector3Tpl< Type >::norm(), offset, VtkUtils::vtkInitOnce(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
lockInteraction()
void cvProtractorTool::lockInteraction () override virtual
Lock tool interaction (disable VTK widget interaction and UI controls)
Reimplemented from cvGenericMeasurementTool.
Definition at line 955 of file cvProtractorTool.cpp.
References cvGenericMeasurementTool::disableShortcuts(), and cvGenericMeasurementTool::m_interactor.
reset()
void cvProtractorTool::reset (void) override virtual
Reimplemented from cvGenericMeasurementTool.
Definition at line 399 of file cvProtractorTool.cpp.
References ccHObject::getBB_recursive(), cloudViewer::BoundingBoxTpl< T >::getCenter(), cloudViewer::BoundingBoxTpl< T >::getDiagVec(), cloudViewer::BoundingBoxTpl< T >::isValid(), cvGenericMeasurementTool::m_entity, cvGenericMeasurementTool::measurementValueChanged(), Vector3Tpl< Type >::norm(), offset, cvGenericMeasurementTool::update(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
setCenter()
void cvProtractorTool::setCenter (double pos[3]) override virtual
Set center point coordinates (for angle/protractor)
Reimplemented from cvGenericMeasurementTool.
Definition at line 889 of file cvProtractorTool.cpp.
References cvGenericMeasurementTool::update().
setColor()
void cvProtractorTool::setColor (double r, double g, double b) override virtual
Set measurement color (RGB values in range [0.0, 1.0])
Reimplemented from cvGenericMeasurementTool.
Definition at line 922 of file cvProtractorTool.cpp.
References cvGenericMeasurementTool::update().
setInstanceLabel()
void cvProtractorTool::setInstanceLabel (const QString & label) override virtual
Set instance label suffix (e.g., "#1", "#2") for display in 3D view.
Reimplemented from cvGenericMeasurementTool.
Definition at line 1191 of file cvProtractorTool.cpp.
setPoint1()
void cvProtractorTool::setPoint1 (double pos[3]) override virtual
Set point 1 coordinates.
Reimplemented from cvGenericMeasurementTool.
Definition at line 823 of file cvProtractorTool.cpp.
References cvGenericMeasurementTool::update().
setPoint2()
void cvProtractorTool::setPoint2 (double pos[3]) override virtual
Set point 2 coordinates.
Reimplemented from cvGenericMeasurementTool.
Definition at line 856 of file cvProtractorTool.cpp.
References cvGenericMeasurementTool::update().
setupPointPickingShortcuts()
void cvProtractorTool::setupPointPickingShortcuts (QWidget * vtkWidget) override protected virtual
Setup keyboard shortcuts for point picking Override in derived classes to add specific shortcuts
Parameters
vtkWidget The VTK render window widget to bind shortcuts to
Reimplemented from cvGenericMeasurementTool.
Definition at line 478 of file cvProtractorTool.cpp.
References cvGenericMeasurementTool::m_interactor, cvGenericMeasurementTool::m_pickingHelpers, cvGenericMeasurementTool::m_renderer, cvPointPickingHelper::pick(), cvPointPickingHelper::setContextWidget(), cvPointPickingHelper::setInteractor(), and cvPointPickingHelper::setRenderer().
showWidget()
void cvProtractorTool::showWidget (bool state) override virtual
Reimplemented from cvGenericMeasurementTool.
Definition at line 542 of file cvProtractorTool.cpp.
References cvGenericMeasurementTool::update().
start()
void cvProtractorTool::start (void) override virtual
Reimplemented from cvGenericMeasurementTool.
Definition at line 392 of file cvProtractorTool.cpp.
References cvGenericMeasurementTool::start().
unlockInteraction()
void cvProtractorTool::unlockInteraction () override virtual
Unlock tool interaction (enable VTK widget interaction and UI controls)
Reimplemented from cvGenericMeasurementTool.
Definition at line 1048 of file cvProtractorTool.cpp.
References cvGenericMeasurementTool::m_fontColor, cvGenericMeasurementTool::m_fontOpacity, cvGenericMeasurementTool::m_interactor, cvGenericMeasurementTool::m_pickingHelpers, cvGenericMeasurementTool::m_vtkWidget, CVLog::PrintDebug(), cvGenericMeasurementTool::setupShortcuts(), and cvGenericMeasurementTool::updatePickingHelpers().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/MeasurementTools/cvProtractorTool.h
/root/ACloudViewer/libs/PCLEngine/Tools/MeasurementTools/cvProtractorTool.cpp