ACloudViewer: GamepadInput Class Reference
GamepadInput Class Reference
Gaempad handler.
#include <GamepadInput.h>
Signals
void updated ()
Public Member Functions
GamepadInput (QObject *parent=nullptr)
Default constructor.
virtual ~GamepadInput ()
Destructor.
void start ()
void stop ()
void update (QMainWindow *win)
Updates a window with the current gamepad state.
Detailed Description
Gaempad handler.
Definition at line 41 of file GamepadInput.h.
Constructor & Destructor Documentation
GamepadInput()
GamepadInput::GamepadInput (QObject * parent = nullptr) explicit
Default constructor.
Definition at line 19 of file GamepadInput.cpp.
~GamepadInput()
GamepadInput::~GamepadInput () virtual
Destructor.
Definition at line 28 of file GamepadInput.cpp.
Member Function Documentation
start()
void GamepadInput::start (void)
Definition at line 30 of file GamepadInput.cpp.
Referenced by ccGamepadManager::enableDevice().
stop()
void GamepadInput::stop ()
Definition at line 32 of file GamepadInput.cpp.
Referenced by ccGamepadManager::enableDevice(), and ccGamepadManager::releaseDevice().
update()
void GamepadInput::update (QMainWindow * win)
Updates a window with the current gamepad state.
Definition at line 34 of file GamepadInput.cpp.
References ecvViewportParameters::computeDistanceToHalfWidthRatio(), ecvViewportParameters::computeWidthAtFocalDist(), ecvDisplayTools::GetViewportParameters(), cloudViewer::GreaterThanEpsilon(), ecvDisplayTools::MoveCamera(), ecvViewportParameters::objectCenteredView, ecvViewportParameters::perspectiveView, ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::RotateBaseViewMat(), Tuple3Tpl< Type >::x, X, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccGamepadManager::onGamepadInput().
updated
void GamepadInput::updated () signal
Referenced by ccGamepadManager::setupGamepadInput().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVAppCommon/devices/gamepad/GamepadInput.h
/root/ACloudViewer/libs/CVAppCommon/devices/gamepad/GamepadInput.cpp