ACloudViewer: EditorSettings Class Reference
EditorSettings Class Reference final
#include <EditorSettings.h>
Signals
void settingsChanged ()
Public Member Functions
EditorSettings ()
int fontSize () const
bool shouldHighlightCurrentLine () const
const ColorScheme & colorScheme () const
Protected Member Functions
void connectSignals () const
void saveChanges ()
void saveChangesAndClose ()
void cancel ()
void setFormValuesToCurrentValues () const
void loadFromSettings ()
void setupUi ()
Detailed Description
Definition at line 14 of file EditorSettings.h.
Constructor & Destructor Documentation
EditorSettings()
EditorSettings::EditorSettings ()
Definition at line 21 of file EditorSettings.cpp.
References connectSignals(), loadFromSettings(), and setupUi().
Member Function Documentation
cancel()
void EditorSettings::cancel () protected
Definition at line 72 of file EditorSettings.cpp.
References setFormValuesToCurrentValues().
Referenced by connectSignals().
colorScheme()
const ColorScheme & EditorSettings::colorScheme () const
Definition at line 47 of file EditorSettings.cpp.
Referenced by loadFromSettings(), saveChanges(), and setupUi().
connectSignals()
void EditorSettings::connectSignals () const protected
Definition at line 103 of file EditorSettings.cpp.
References cancel(), saveChanges(), and saveChangesAndClose().
Referenced by EditorSettings().
fontSize()
int EditorSettings::fontSize () const
Definition at line 37 of file EditorSettings.cpp.
loadFromSettings()
void EditorSettings::loadFromSettings () protected
Definition at line 84 of file EditorSettings.cpp.
References COLOR_SCHEME_SETTINGS_KEY, colorScheme(), ColorScheme::ColorSchemeByName(), setFormValuesToCurrentValues(), SettingsScopeName(), and SHOULD_HIGHLIGHT_SETTINGS_KEY.
Referenced by EditorSettings().
saveChanges()
void EditorSettings::saveChanges () protected
Definition at line 52 of file EditorSettings.cpp.
References COLOR_SCHEME_SETTINGS_KEY, colorScheme(), ColorScheme::ColorSchemeByName(), ColorScheme::name(), settingsChanged(), SettingsScopeName(), and SHOULD_HIGHLIGHT_SETTINGS_KEY.
Referenced by connectSignals(), and saveChangesAndClose().
saveChangesAndClose()
void EditorSettings::saveChangesAndClose () protected
Definition at line 66 of file EditorSettings.cpp.
References saveChanges().
Referenced by connectSignals().
setFormValuesToCurrentValues()
void EditorSettings::setFormValuesToCurrentValues () const protected
Definition at line 78 of file EditorSettings.cpp.
References ColorScheme::name().
Referenced by cancel(), and loadFromSettings().
settingsChanged
void EditorSettings::settingsChanged () signal
Referenced by CodeEditor::CodeEditor(), and saveChanges().
setupUi()
void EditorSettings::setupUi () protected
Definition at line 28 of file EditorSettings.cpp.
References ColorScheme::AvailableColorSchemes(), colorScheme(), and ColorScheme::name().
Referenced by EditorSettings().
shouldHighlightCurrentLine()
bool EditorSettings::shouldHighlightCurrentLine () const
Definition at line 42 of file EditorSettings.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/CodeEditor/EditorSettings.h
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/CodeEditor/EditorSettings.cpp