ACloudViewer: ccObject Class Reference
ccObject Class Reference abstract
Generic "CLOUDVIEWER Object" template.
#include <ecvObject.h>
Public Member Functions
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual CV_CLASS_ENUM getClassID () const =0
Returns class ID.
virtual QString getName () const
Returns object name.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
virtual bool isSerializable () const
Returns whether object is serializable of not.
Static Public Member Functions
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Protected Member Functions
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Protected Attributes
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Additional Inherited Members
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Detailed Description
Generic "CLOUDVIEWER Object" template.
Definition at line 49 of file ecvObject.h.
Constructor & Destructor Documentation
ccObject() [1/2]
ccObject::ccObject (QString name = QString())
Default constructor.
Parameters
name object name (optional)
uniqueID unique ID (handle with care! Will be auto generated if equal to ccUniqueIDGenerator::InvalidUniqueID)
ccObject() [2/2]
ccObject::ccObject (const ccObject & object)
Copy constructor.
Member Function Documentation
fromFile()
bool ccObject::fromFile (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override protected virtual
Reimplemented from ccSerializableObject::fromFile.
Be sure to call ccObject::ReadClassIDFromFile (once) before calling this method, as the classID is voluntarily skipped (in order to let the user instantiate the object first)
Reimplemented from ccSerializableObject.
getBaseName()
QString ccObject::getBaseName () const inline
Definition at line 187 of file ecvObject.h.
getClassID()
virtual CV_CLASS_ENUM ccObject::getClassID () const pure virtual
Returns class ID.
Implemented in ccTrace, PyObjectBase< ObjectBase >, PyObjectBase< ccHObject >, cloudViewer::geometry::VoxelGrid, cloudViewer::geometry::RGBDImage, cloudViewer::geometry::Octree, cloudViewer::geometry::LineSet, cloudViewer::geometry::Image, cloudViewer::geometry::HalfEdgeTriangleMesh, ccTorus, cloudViewer::geometry::TetraMesh, ccSubMesh, ccSphere, ccSensor, ccQuadric, ccPolyline, ccPointCloud, ccPlane, ecvOrientedBBox, ccOctreeProxy, ccMeshGroup, cloudViewer::geometry::ecvMeshBase, ccMesh, ccMaterialSet, ccKdTree, ccIndexedTransformationBuffer, ccImage, ccHObject, ccGenericPrimitive, ccGBLSensor, ccFacet, ccExtru, ccDish, ccDisc, ccCylinder, ccCustomLeafObject, ccCustomHObject, ccCoordinateSystem, ccCone, ccClipBox, ccCircle, ccCameraSensor, ccBox, ccBBox, ccArray< Type, N, ComponentType >, ccArray< CompressedNormType, 1, CompressedNormType >, ccArray< TexCoords2D, 2, float >, ccArray< ecvColor::Rgba, 4, ColorCompType >, ccArray< CCVector3, 3, PointCoordinateType >, ccArray< ecvColor::Rgb, 3, ColorCompType >, TextureCoordsContainer, RGBAColorsTableType, ColorsTableType, NormsTableType, NormsIndexesTableType, cc2DViewportObject, cc2DViewportLabel, cc2DLabel, cloudViewer::visualization::SelectionPolygon, and cloudViewer::visualization::PointCloudPicker.
Referenced by ccHObject::isGroup().
GetCurrentDBVersion()
static unsigned ccObject::GetCurrentDBVersion () static
Returns current database version.
getFlagState()
virtual bool ccObject::getFlagState (CV_OBJECT_FLAG flag) const inline protected virtual
Returns flag state.
Definition at line 194 of file ecvObject.h.
getFullPath()
QString ccObject::getFullPath () const inline
Definition at line 190 of file ecvObject.h.
GetLastUniqueID()
static unsigned ccObject::GetLastUniqueID () static
Returns last assigned unique ID.
Unique IDs are handled with persistent settings in order to assure consistency between main app and plugins!
getMetaData()
QVariant ccObject::getMetaData (const QString & key) const
Returns a given associated meta data.
Parameters
key meta data unique identifier (case sensitive)
Returns
meta data (if any) or an invalid QVariant
Referenced by ccFitPlane::ccFitPlane(), ccGeoObject::ccGeoObject(), ccTopologyRelation::ccTopologyRelation(), ccTrace::ccTrace(), qCanupoProcess::Classify(), define_ccObject(), ccRasterizeTool::generateContours(), GetFacetMetaData(), DistanceMapGenerationTool::GetPolylineHeightShift(), GetPolylineMetaVector(), DistanceMapGenerationTool::GetPoylineRevolDim(), qAnimationDlg::init(), LasMetadata::LoadGlobalEncoding(), LasMetadata::LoadLasVersionFrom(), LasMetadata::LoadOffsetFrom(), LasMetadata::LoadProjectUUID(), LasMetadata::LoadScaleFrom(), LasMetadata::LoadVlrs(), FacetsClassifier::ProcessFamiliy(), SaveScan(), SinusxFilter::saveToFile(), MascaretFilter::saveToFile(), SimpleBinFilter::saveToFile(), FBXFilter::saveToFile(), LASFWFFilter::saveToFile(), and LASFilter::saveToFile().
getName()
virtual QString ccObject::getName () const inline virtual
Returns object name.
Reimplemented in cc2DLabel.
Definition at line 72 of file ecvObject.h.
Referenced by ccGraphicalTransformationTool::addEntity(), ccGraphicalSegmentationTool::addEntity(), ccCompass::addGeoObject(), MainWindow::addToDB(), G3Point::G3PointAction::angles(), ecvFilterByLabelDlg::apply(), ccPointPairRegistrationDlg::apply(), ccLibAlgorithms::ApplyCCLibAlgorithm(), ccLibAlgorithms::ApplyScaleMatchingAlgorithm(), ccGraphicalSegmentationTool::applySegmentation(), ccNormalComputationDlg::autoEstimateRadius(), ccComparisonDlg::ccComparisonDlg(), ccPointPair::ccPointPair(), ccRasterizeTool::ccRasterizeTool(), ccSNECloud::ccSNECloud(), ccTrace::ccTrace(), ccVolumeCalcTool::ccVolumeCalcTool(), ccWaveDialog::ccWaveDialog(), ccEntityAction::changeColorLevels(), masc::PointFeature::checkValidity(), ccArray< Type, N, ComponentType >::clone(), NormsIndexesTableType::clone(), NormsTableType::clone(), ColorsTableType::clone(), RGBAColorsTableType::clone(), TextureCoordsContainer::clone(), compareObjects(), GeneralFilters::compute(), MLSSmoothingUpsampling::compute(), ProjectionFilter::compute(), StatisticalOutliersRemover::compute(), CorrespondenceMatching::compute(), TemplateAlignment::compute(), DONSegmentation::compute(), EuclideanClusterSegmentation::compute(), MinimumCutSegmentation::compute(), SACSegmentation::compute(), NurbsCurveFitting::compute(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), ccLibAlgorithms::ComputeGeomCharacteristic(), ComputeMathOpWithNearestNeighbor(), ccEntityAction::computeStatParams(), ccTopologyRelation::constructGraphic(), contourPoly(), ccEntityAction::convertNormalsTo(), ccEntityAction::convertTextureToColor(), ccEntityAction::ConvexHull(), qFacets::createFacets(), ccCropTool::Crop(), ccDBRoot::data(), ccEntityAction::DBScanCluster(), define_ccObject(), ccDBRoot::deleteSelectedEntities(), ccCompass::distributeSelection(), qCork::doAction(), qCSF::doAction(), qPCV::doAction(), qPoissonRecon::doAction(), qCanupoPlugin::doClassifyAction(), ecvPoissonReconDlg::doComputation(), qCanupoPlugin::doTrainAction(), ccRasterizeTool::exportContourLines(), StereogramDialog::exportCurrentSelection(), ccCommandLineParser::exportEntity(), qFacets::exportFacets(), ccVolumeCalcTool::exportGridAsCloud(), DistanceMapGenerationDlg::exportMapAsCloud(), DistanceMapGenerationDlg::exportMapAsMesh(), ecvMeasurementTool::exportMeasurement(), ccGraphicalTransformationTool::exportNewEntities(), ccEntityAction::exportNormalToSF(), ecvFilterTool::exportSlice(), qFacets::extractFacets(), ccPropertiesTreeDelegate::fillWithCCArray(), ccPropertiesTreeDelegate::fillWithHObject(), ccPropertiesTreeDelegate::fillWithViewportObject(), ccTraceTool::finishCurrentTrace(), ccRasterizeTool::generateCloud(), ccRasterizeTool::generateMesh(), G3Point::G3PointAction::getBorders(), qCanupoTools::GetEntityName(), GetEntityName(), CorrespondenceMatchingDialog::getEntityName(), TemplateAlignmentDialog::getEntityName(), MinimumCutSegmentationDlg::getEntityName(), GetFacetMetaData(), G3Point::G3PointAction::GetG3PointAction(), ccCompass::getInsertPoint(), ccSubsamplingDlg::getSampledCloud(), GetScalarFieldIndex(), ccCommandLineParser::importFile(), ccEntityAction::importToSF(), qAnimationDlg::init(), PovFilter::loadFile(), E57Filter::loadFile(), FBXFilter::loadFile(), ccCompass::mergeGeoObjects(), ccPointPairRegistrationDlg::onItemPicked(), ccEntityAction::orientNormalsFM(), ccEntityAction::orientNormalsMST(), ccFitPlaneTool::pointPicked(), ccLineationTool::pointPicked(), ccNoteTool::pointPicked(), ccTracePolylineTool::polylineOverSampling(), masc::Tools::PrepareFeatures(), CommandCrossSection::process(), CommandOctreeNormal::process(), CommandInvertNormal::process(), CommandConvertNormalsToDipAndDipDir::process(), CommandConvertNormalsToSFs::process(), CommandSubsample::process(), CommandExtractCCs::process(), CommandSFConvertToRGB::process(), CommandMatchBBCenters::process(), CommandMatchBestFitPlane::process(), CommandOrientNormalsMST::process(), CommandSORFilter::process(), CommandStatTest::process(), CommandDelaunayTri::process(), CommandSFArithmetic::process(), CommandSFOperation::process(), CommandSFRename::process(), CommandICP::process(), CommandRasterize::process(), CommandVolume25D::process(), CommandRANSAC::process(), PCVCommand::Process(), ccEntityAction::processMeshSF(), cloudViewer::geometry::pybind_geometry_classes(), ccEntityAction::RansacSegmentation(), ccEntityAction::rgbGaussianFilter(), SaveScan(), SalomeHydroFilter::saveToFile(), SinusxFilter::saveToFile(), HeightProfileFilter::saveToFile(), MascaretFilter::saveToFile(), ccDBRoot::selectChildrenByTypeAndName(), ccEntityAction::setColor(), ccAlignDlg::setColorsAndLabels(), ccOrderChoiceDlg::setColorsAndLabels(), ccDBRoot::setData(), ccPropertiesTreeDelegate::setEditorData(), ecvFilterByLabelDlg::setInputEntity(), ccEntityAction::sfArithmetic(), ccEntityAction::sfGaussianFilter(), ccEntityAction::sfRename(), ccComparisonDlg::showHisto(), G3Point::G3PointAction::showWolman(), ccDBRoot::sortSelectedEntitiesChildren(), ecvPoissonReconDlg::start(), ccEntityAction::statisticalTest(), ToFbxMesh(), ccRegistrationDlg::updateGUI(), FastGlobalRegistrationDialog::updateGUI(), and MainWindow::zoomOnEntities().
GetNextUniqueID()
static unsigned ccObject::GetNextUniqueID () static
Returns a new unassigned unique ID.
Unique IDs are handled with persistent settings in order to assure consistency between main app and plugins!
getRemoveFlag()
virtual bool ccObject::getRemoveFlag () inline virtual
Returns removeFlag.
Definition at line 83 of file ecvObject.h.
getUniqueID()
virtual unsigned ccObject::getUniqueID () const inline virtual
Returns object unique ID.
Definition at line 86 of file ecvObject.h.
Referenced by ccTrace::bakePathToScalarField(), define_ccObject(), qPoissonRecon::doAction(), ccGraphicalTransformationTool::exportNewEntities(), ccPropertiesTreeDelegate::fillWithHObject(), ccGeoObject::generateInterior(), ccGeoObject::generateLower(), ccGeoObject::generateUpper(), qCanupoTools::GetEntityName(), GetEntityName(), CorrespondenceMatchingDialog::getEntityName(), TemplateAlignmentDialog::getEntityName(), MinimumCutSegmentationDlg::getEntityName(), ccHObject::getUniqueIDForDisplay(), ccHObject::getViewId(), ccCompass::hideAllPointClouds(), ccCommandLineParser::importFile(), StereogramDialog::init(), ccDBRoot::itemData(), ccTopologyTool::onNewSelection(), ccTraceTool::pickupTrace(), ccLineationTool::pointPicked(), ccThicknessTool::pointPicked(), ccTraceTool::pointPicked(), cloudViewer::geometry::pybind_geometry_classes(), ccPointListPickingDlg::removeLastEntry(), cloudViewer::ModelViewerWidget::SelectObject(), ecvFilterTool::stop(), ccCompass::tryLoading(), and FastGlobalRegistrationDialog::updateGUI().
GetUniqueIDGenerator()
static ccUniqueIDGenerator::Shared ccObject::GetUniqueIDGenerator () static
Returns the unique ID generator.
Referenced by MainWindow::getUniqueIDGenerator().
hasMetaData()
bool ccObject::hasMetaData (const QString & key) const
Returns whether a meta-data element with the given key exists or not.
Parameters
key meta-data unique identifier (case sensitive)
Returns
whether the element exists or not
Referenced by ccFitPlane::ccFitPlane(), ccTopologyRelation::ccTopologyRelation(), ccTrace::ccTrace(), define_ccObject(), BasePclModule::getSelectedThatHaveMetaData(), qAnimationDlg::init(), ccFitPlane::isFitPlane(), ccGeoObject::isGeoObject(), ccGeoObject::isGeoObjectInterior(), ccGeoObject::isGeoObjectLower(), ccGeoObject::isGeoObjectUpper(), ccLineation::isLineation(), ccNote::isNote(), ccPinchNode::isPinchNode(), ccPointPair::isPointPair(), ccGeoObject::isSingleSurfaceGeoObject(), ccSNECloud::isSNECloud(), ccThickness::isThickness(), ccTopologyRelation::isTopologyRelation(), ccTrace::isTrace(), LasMetadata::LoadProjectUUID(), LasMetadata::LoadVlrs(), SinusxFilter::saveToFile(), MascaretFilter::saveToFile(), SimpleBinFilter::saveToFile(), FBXFilter::saveToFile(), LASFWFFilter::saveToFile(), and LASFilter::saveToFile().
isA()
bool ccObject::isA (CV_CLASS_ENUM type) const inline
Definition at line 131 of file ecvObject.h.
References type.
Referenced by ccGraphicalTransformationTool::addEntity(), ccGraphicalSegmentationTool::addEntity(), ecvPoissonReconDlg::addEntity(), ccDBRoot::alignCameraWithEntity(), ecvFilterByLabelDlg::apply(), ccGraphicalTransformationTool::apply(), ccLibAlgorithms::ApplyCCLibAlgorithm(), ccGraphicalSegmentationTool::applySegmentation(), CCCloudToDraco(), ccComparisonDlg::ccComparisonDlg(), ccRasterizeTool::ccRasterizeTool(), qFacets::classifyFacetsByAngle(), ccEntityAction::clearProperty(), ccComparisonDlg::computeDistances(), ccLibAlgorithms::ComputeGeomCharacteristic(), ccEntityAction::convertNormalsTo(), ccCompass::convertToPointCloud(), G3Point::G3PointAction::createAction(), ccCropTool::Crop(), ccDBRoot::data(), qCSF::doAction(), qPCV::doAction(), qPoissonRecon::doAction(), qRansacSD::doAction(), ccDBRoot::dropMimeData(), ccDBRoot::editLabelScalarValue(), ccDBRoot::enableBubbleViewMode(), StereogramDialog::exportCurrentSelection(), ccCommandLineParser::exportEntity(), ccCompass::exportToSVG(), ccPropertiesTreeDelegate::fillModel(), ccPropertiesTreeDelegate::fillWithMesh(), ccPropertiesTreeDelegate::fillWithPointCloud(), ccPropertiesTreeDelegate::fillWithPolyline(), ccPropertiesTreeDelegate::fillWithPrimitive(), ccPropertiesTreeDelegate::fillWithViewProperties(), TreeIso::Final_seg(), ccDBRoot::flags(), ccKdTreeForFacetExtraction::FuseCells(), ccDBRoot::gatherRecursiveInformation(), ccRasterizeTool::generateRaster(), MinimumCutSegmentationDlg::get2DLabelFromCombo(), GetCloudFromCombo(), qCanupoTools::GetCloudFromCombo(), CorrespondenceMatchingDialog::getCloudFromCombo(), TemplateAlignmentDialog::getCloudFromCombo(), GetMeshFromCombo(), ccDBRoot::getSelectedEntities(), BasePclModule::getSelectedEntitiesThatAre(), BasePclModule::getSelectedEntitiesThatAreCCPointCloud(), BasePclModule::getSelectedEntityAsCCPointCloud(), ccRegistrationTools::ICP(), StereogramWidget::init(), TreeIso::Init_seg(), TreeIso::Intermediate_seg(), ccEntityAction::interpolateColors(), DistanceMapGenerationDlg::labelFontSizeChanged(), E57Filter::loadFile(), DistanceMapGenerationDlg::overlayGridColorChanged(), DistanceMapGenerationDlg::overlaySymbolsColorChanged(), DistanceMapGenerationDlg::overlaySymbolsSizeChanged(), ccThicknessTool::pointPicked(), ccComparisonDlg::prepareEntitiesForComparison(), CommandClearNormals::process(), CommandRemoveAllSFs::process(), CommandRemoveSF::process(), CommandRemoveRGB::process(), CommandRemoveNormals::process(), CommandRemoveScanGrids::process(), CommandCrop::process(), ccEntityAction::processMeshSF(), cloudViewer::geometry::pybind_geometry_classes(), ccEntityAction::rgbToGreyScale(), SalomeHydroFilter::saveToFile(), SinusxFilter::saveToFile(), HeightProfileFilter::saveToFile(), MAFilter::saveToFile(), MascaretFilter::saveToFile(), SimpleBinFilter::saveToFile(), E57Filter::saveToFile(), FBXFilter::saveToFile(), LasIOFilter::saveToFile(), LASFilter::saveToFile(), ccDBRoot::selectEntities(), ccDBRoot::selectEntity(), ccCustomQTreeView::selectionCommand(), ccEntityAction::setColor(), ccEntityAction::setColorGradient(), ccDBRoot::setData(), ccEntityAction::sfSetAsCoord(), ccDBRoot::showContextMenu(), ToFbxMesh(), ccPointPairRegistrationDlg::updateAllMarkers(), StereogramDialog::updateFacetsFilter(), and ccPointPairRegistrationDlg::updateSphereMarks().
isCustom()
bool ccObject::isCustom () const inline
Definition at line 123 of file ecvObject.h.
References CC_CUSTOM_BIT.
Referenced by define_ccObject(), and cloudViewer::geometry::pybind_geometry_classes().
isEnabled()
virtual bool ccObject::isEnabled () const inline virtual
Returns whether the object is enabled or not.
Shortcut to access flag CC_ENABLED
Definition at line 97 of file ecvObject.h.
References CC_ENABLED.
Referenced by ccComparisonDlg::computeDistances(), ccDBRoot::data(), define_ccObject(), ccCompass::estimateStrain(), ccRasterizeTool::generateCloud(), ccTracePolylineTool::polylineOverSampling(), ccDBRoot::setData(), ccDBRoot::toggleSelectedEntitiesProperty(), ccCompass::tryLoading(), and ccTracePolylineTool::updatePolyLineTip().
isHierarchy()
bool ccObject::isHierarchy () const inline
Definition at line 124 of file ecvObject.h.
References CC_HIERARCH_BIT.
Referenced by define_ccObject(), ccPropertiesTreeDelegate::fillModel(), and cloudViewer::geometry::pybind_geometry_classes().
isKindOf()
bool ccObject::isKindOf (CV_CLASS_ENUM type) const inline
Definition at line 128 of file ecvObject.h.
References type.
Referenced by ecvAnnotationsTool::addAssociatedEntity(), ccGraphicalTransformationTool::addEntity(), ccGraphicalSegmentationTool::addEntity(), ecvPoissonReconDlg::addEntity(), MainWindow::addToDB(), ccPointPairRegistrationDlg::align(), ecvFilterByLabelDlg::apply(), ccGraphicalTransformationTool::apply(), ccLibAlgorithms::ApplyScaleMatchingAlgorithm(), ccGraphicalSegmentationTool::applySegmentation(), CanDetachCloud(), ccPointPairRegistrationDlg::clear(), compareObjects(), ccEntityAction::computeNormals(), ccPointPairRegistrationDlg::convertToSphereCenter(), ccDBRoot::countSelectedEntities(), ccCropTool::Crop(), ccDBRoot::deleteSelectedEntities(), qPCV::doAction(), ccDBRoot::dropMimeData(), ccCommandLineParser::exportEntity(), ccDBRoot::exportImages(), ccPropertiesTreeDelegate::fillModel(), ccPropertiesTreeDelegate::fillWithPrimitive(), ccPropertiesTreeDelegate::fillWithViewProperties(), cloudViewer::visualization::ViewControl::FitInGeometry(), ccDBRoot::flags(), ccDBRoot::gatherRecursiveInformation(), ccDBRoot::getSelectedEntities(), ccCompass::hideAllPointClouds(), ccRegistrationTools::ICP(), ccPointPairRegistrationDlg::label2DMove(), PovFilter::loadFile(), ccMPlaneDlgController::onItemPicked(), HSVDialog::onItemPicked(), RgbDialog::onItemPicked(), ScalarDialog::onItemPicked(), ccPointPickingGenericInterface::onItemPicked(), qMPlane::onNewSelection(), ccCompass::pointPicked(), ccComparisonDlg::prepareEntitiesForComparison(), ccGraphicalSegmentationTool::prepareEntityForRemoval(), cloudViewer::geometry::pybind_geometry_classes(), ccPointPairRegistrationDlg::removeAlignedPoint(), ccPointPairRegistrationDlg::removeRefPoint(), ccPointPairRegistrationDlg::reset(), ccColorScaleEditorDialog::saveCurrentScale(), DRCFilter::saveToFile(), FBXFilter::saveToFile(), cloudViewer::ModelViewerWidget::SelectObject(), ccEntityAction::setColor(), ccDBRoot::setData(), ecvFilterByLabelDlg::setInputEntity(), ccPointPairRegistrationDlg::showAlignedEntities(), ccDBRoot::showContextMenu(), ccPointPairRegistrationDlg::showReferenceEntities(), ecvPoissonReconDlg::start(), ccPointPairRegistrationDlg::updateAlignedMarkers(), ccRegistrationDlg::updateGUI(), and ccPointPairRegistrationDlg::updateRefMarkers().
isLeaf()
bool ccObject::isLeaf () const inline
Definition at line 122 of file ecvObject.h.
References CC_LEAF_BIT.
Referenced by define_ccObject(), ccDBRoot::dropMimeData(), cloudViewer::geometry::pybind_geometry_classes(), and ccDBRoot::showContextMenu().
isLocked()
virtual bool ccObject::isLocked () const inline virtual
Returns whether the object is locked or not.
Shortcut to access flag CC_LOCKED
Definition at line 112 of file ecvObject.h.
References CC_LOCKED.
Referenced by ccGraphicalTransformationTool::addEntity(), ccGraphicalSegmentationTool::applySegmentation(), ccDBRoot::data(), define_ccObject(), ccDBRoot::deleteSelectedEntities(), ccPropertiesTreeDelegate::fillWithHObject(), ccPropertiesTreeDelegate::fillWithMesh(), ccDBRoot::flags(), and ccEntityAction::setColor().
metaData()
const QVariantMap& ccObject::metaData () const inline
Returns meta-data map (const only)
Definition at line 184 of file ecvObject.h.
Referenced by ccPropertiesTreeDelegate::fillWithMetaData().
minimumFileVersion()
short ccObject::minimumFileVersion () const override protected virtual
Returns the minimum file version required to save this instance.
To be overridden by subclasses to indicate their minimum required version. This enables the system to determine:
Forward compatibility: newer software can read older files (dataVersion check in fromFile)
Backward compatibility: determine minimum version needed to save current data
Returns
minimum file version required for this object
Implements ccSerializableObject.
ReadClassIDFromFile()
static CV_CLASS_ENUM ccObject::ReadClassIDFromFile (QFile & in, short dataVersion) static
Helper: reads out class ID from a binary stream.
Must be called before 'fromFile'!
removeMetaData()
bool ccObject::removeMetaData (const QString & key)
Removes a given associated meta-data.
Parameters
key meta-data unique identifier (case sensitive)
Returns
success
Referenced by define_ccObject().
setBaseName()
void ccObject::setBaseName (const QString & baseName) inline
Definition at line 186 of file ecvObject.h.
setEnabled()
virtual void ccObject::setEnabled (bool state) inline virtual
Sets the "enabled" property.
Shortcut to modify flag CC_ENABLED
Definition at line 102 of file ecvObject.h.
References CC_ENABLED.
Referenced by ecvAnnotationsTool::addAssociatedEntity(), ecvFilterTool::addAssociatedEntity(), ecvMeasurementTool::addAssociatedEntity(), ccGraphicalSegmentationTool::addEntity(), ecvFilterByLabelDlg::apply(), ccPointListPickingDlg::cancelAndExit(), ccComparisonDlg::ccComparisonDlg(), ccMouseCircle::ccMouseCircle(), ccPointPairRegistrationDlg::ccPointPairRegistrationDlg(), ccRasterizeTool::ccRasterizeTool(), ccTracePolylineTool::ccTracePolylineTool(), ccTracePolylineTool::closePolyLine(), GeneralFilters::compute(), MLSSmoothingUpsampling::compute(), StatisticalOutliersRemover::compute(), DONSegmentation::compute(), EuclideanClusterSegmentation::compute(), MinimumCutSegmentation::compute(), RegionGrowingSegmentation::compute(), SACSegmentation::compute(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), ccTopologyRelation::constructGraphic(), CreateLabel(), ccCropTool::Crop(), define_ccObject(), qCork::doAction(), qCSF::doAction(), qPoissonRecon::doAction(), ccGraphicalSegmentationTool::doExportSegmentationPolyline(), q3DMASCPlugin::doTrainAction(), ecvMeasurementTool::exportMeasurement(), ccGraphicalTransformationTool::exportNewEntities(), ccPointListPickingDlg::exportToNewPolyline(), ccContourExtractor::ExtractConcaveHull2D(), ccContourExtractor::ExtractFlatContour(), cloudViewer::pipelines::integration::ScalableTSDFVolume::ExtractTriangleMesh(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractTriangleMesh(), FromFbxMesh(), ccRasterizeTool::generateCloud(), ccRasterizeTool::generateContours(), ccRasterizeTool::generateMesh(), STEPFilter::importStepFile(), ProfileLoader::Load(), IcmFilter::LoadCalibratedImages(), CSVMatrixFilter::loadFile(), PhotoScanFilter::loadFile(), PcdFilter::loadFile(), PovFilter::loadFile(), SalomeHydroFilter::loadFile(), SinusxFilter::loadFile(), LoadImage(), LoadScan(), main(), ccTracePolylineTool::onItemPicked(), ccCompass::pointPicked(), CommandMergeMeshes::process(), CommandDelaunayTri::process(), CommandRasterize::process(), CommandVolume25D::process(), cloudViewer::visualization::MessageProcessor::ProcessMessage(), ccPointPropertiesDlg::processPickedPoint(), ccEntityAction::RansacSegmentation(), cloudViewer::io::ReadModelUsingAssimp(), cloudViewer::io::ReadTriangleMeshFromGLTF(), ccPointListPickingDlg::removeEntity(), ccTracePolylineTool::restart(), ccOrderChoiceDlg::setColorsAndLabels(), ccDBRoot::setData(), SetEnabled_recursive(), ccPointPairRegistrationDlg::showAlignedEntities(), ccPointPairRegistrationDlg::showReferenceEntities(), ecvPoissonReconDlg::start(), DistanceMapGenerationDlg::toggleOverlayGrid(), ccDBRoot::toggleSelectedEntitiesProperty(), Cloth::toMesh(), ccCompass::tryLoading(), ccPointPairRegistrationDlg::updateAllMarkers(), ccComparisonDlg::updateDisplay(), GrainsAsEllipsoids::updateMeshAndLineSet(), and ccTracePolylineTool::updatePolyLineTip().
setFlagState()
virtual void ccObject::setFlagState (CV_OBJECT_FLAG flag, bool state) protected virtual
Sets flag state.
Parameters
flag object flag to set
state flag state
Referenced by ccArray< Type, N, ComponentType >::ccArray().
setFullPath()
void ccObject::setFullPath (const QString & fullPaht) inline
Definition at line 189 of file ecvObject.h.
setLocked()
virtual void ccObject::setLocked (bool state) inline virtual
Sets the "enabled" property.
Shortcut to modify flag CC_LOCKED
Definition at line 117 of file ecvObject.h.
References CC_LOCKED.
Referenced by define_ccObject(), cloudViewer::pipelines::integration::ScalableTSDFVolume::ExtractTriangleMesh(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractTriangleMesh(), ProfileLoader::Load(), main(), cloudViewer::visualization::MessageProcessor::ProcessMessage(), cloudViewer::io::ReadModelUsingAssimp(), and GrainsAsEllipsoids::updateMeshAndLineSet().
setMetaData() [1/2]
void ccObject::setMetaData (const QString & key, const QVariant & data)
Sets a meta-data element.
Parameters
key meta-data unique identifier (case sensitive)
data data
Referenced by ccFitPlane::ccFitPlane(), ccTrace::ccTrace(), qCanupoProcess::Classify(), define_ccObject(), ccCompass::estimateStrain(), ccCompass::fitPlaneToGeoObject(), ccRasterizeTool::generateContours(), ccGeoObject::generateInterior(), ccGeoObject::generateLower(), ccGeoObject::generateUpper(), GrainsAsEllipsoids::GrainsAsEllipsoids(), SinusxFilter::loadFile(), FBXFilter::loadFile(), LASFWFFilter::loadFile(), LASFilter::loadFile(), LoadScan(), qAnimationDlg::onAccept(), ccTrace::optimizePath(), FacetsClassifier::ProcessFamiliy(), LasMetadata::SaveMetadataInto(), DistanceMapGenerationTool::SetPolylineHeightShift(), SetPoylineMetaVector(), DistanceMapGenerationTool::SetPoylineRevolDim(), ccFitPlane::updateAttributes(), ccSNECloud::updateMetadata(), ccLineation::updateMetadata(), ccNote::updateMetadata(), ccPinchNode::updateMetadata(), ccThickness::updateMetadata(), and ccTopologyRelation::updateMetadata().
setMetaData() [2/2]
void ccObject::setMetaData (const QVariantMap & dataset, bool overwrite = false)
Sets several meta-data elements at a time.
Parameters
dataset meta-data set
overwrite whether existing meta-data elements should be replaced by the input ones (with the same key) or not
setName()
virtual void ccObject::setName (const QString & name) inline virtual
Sets object name.
Definition at line 75 of file ecvObject.h.
References name.
Referenced by ccRasterizeTool::addNewContour(), ecvFilterByLabelDlg::apply(), ccGraphicalSegmentationTool::applySegmentation(), ccFitPlane::ccFitPlane(), ccPointPair::ccPointPair(), ccSNECloud::ccSNECloud(), ccTrace::ccTrace(), NormsIndexesTableType::clone(), NormsTableType::clone(), ColorsTableType::clone(), RGBAColorsTableType::clone(), TextureCoordsContainer::clone(), ccPointPropertiesDlg::close2DZone(), ExtractSIFT::compute(), GeneralFilters::compute(), MLSSmoothingUpsampling::compute(), ProjectionFilter::compute(), StatisticalOutliersRemover::compute(), CorrespondenceMatching::compute(), TemplateAlignment::compute(), DONSegmentation::compute(), EuclideanClusterSegmentation::compute(), MinimumCutSegmentation::compute(), RegionGrowingSegmentation::compute(), SACSegmentation::compute(), ConvexConcaveHullReconstruction::compute(), GreedyTriangulation::compute(), MarchingCubeReconstruction::compute(), NurbsCurveFitting::compute(), NurbsSurfaceReconstruction::compute(), PoissonReconstruction::compute(), qM3C2Process::Compute(), ComputeKmeansClustering(), ccTopologyRelation::constructGraphic(), contourPoly(), contourPoly2(), ccEntityAction::ConvexHull(), qFacets::createFacets(), CreateLabel(), CC_ITEM_TREE::createPointLabel2D(), DecodeSensor(), define_ccObject(), qCSF::doAction(), qPoissonRecon::doAction(), qCanupoPlugin::doClassifyAction(), ccGraphicalSegmentationTool::doExportSegmentationPolyline(), ccCompass::estimateStructureNormals(), StereogramDialog::exportCurrentSelection(), ccCommandLineParser::exportEntity(), ccVolumeCalcTool::exportGridAsCloud(), DistanceMapGenerationDlg::exportMapAsCloud(), DistanceMapGenerationDlg::exportMapAsMesh(), ecvMeasurementTool::exportMeasurement(), ccPointListPickingDlg::exportToNewCloud(), qFacets::extractFacets(), ccContourExtractor::ExtractFlatContour(), G3Point::G3PointAction::fit(), FromFbxMesh(), ccRasterizeTool::generateMesh(), G3Point::G3PointAction::getBorders(), getMortarMaps(), ccCompass::importLineations(), ccCompassImport::importLineations(), STEPFilter::importStepFile(), ProfileLoader::Load(), IcmFilter::LoadCalibratedImages(), CSVMatrixFilter::loadFile(), PhotoScanFilter::loadFile(), PcdFilter::loadFile(), SalomeHydroFilter::loadFile(), SinusxFilter::loadFile(), E57Filter::loadFile(), FBXFilter::loadFile(), LASFilter::loadFile(), RDBFilter::loadFile(), LoadImage(), LoadScan(), NodeStructureToTree(), MainWindow::onItemPicked(), ccLineationTool::pointPicked(), ccNoteTool::pointPicked(), ccPinchNodeTool::pointPicked(), ccThicknessTool::pointPicked(), ccTraceTool::pointPicked(), CommandOctreeNormal::process(), CommandExtractCCs::process(), CommandSORFilter::process(), CommandCrop2D::process(), CommandRasterize::process(), CommandVolume25D::process(), ccPointPropertiesDlg::processClickedPoint(), cloudViewer::geometry::pybind_geometry_classes(), ccEntityAction::RansacSegmentation(), ReadCloud(), ccPointPairRegistrationDlg::removeAlignedPoint(), ccPointPairRegistrationDlg::removeRefPoint(), ccDBRoot::setData(), ccMPlanePoint::setName(), ecvPoissonReconDlg::start(), GrainsAsEllipsoids::updateMeshAndLineSet(), ccLineation::updateMetadata(), and ccThickness::updateMetadata().
setRemoveFlag()
virtual void ccObject::setRemoveFlag (bool removeFlag) inline virtual
Sets removeFlag.
Definition at line 78 of file ecvObject.h.
setUniqueID()
virtual void ccObject::setUniqueID (unsigned ID) virtual
Changes unique ID.
WARNING: HANDLE WITH CARE! Updates persistent settings (last unique ID) if necessary.
Referenced by cloudViewer::geometry::pybind_geometry_classes().
SetUniqueIDGenerator()
static void ccObject::SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator) static
Sets the unique ID generator.
Referenced by ccPclPluginInterface::setMainAppInterface(), and ccStdPluginInterface::setMainAppInterface().
toFile()
bool ccObject::toFile (QFile & out, short dataVersion) const override protected virtual
Saves data to binary stream.
Parameters
out output file (already opened)
dataVersion target file version (for forward/backward compatibility)
Returns
success
Reimplemented from ccSerializableObject.
toggleActivation()
virtual void ccObject::toggleActivation () inline virtual
Toggles the "enabled" property.
Definition at line 107 of file ecvObject.h.
Referenced by define_ccObject(), and ccEntityAction::toggleProperty().
Member Data Documentation
m_baseName
QString ccObject::m_baseName protected
Definition at line 221 of file ecvObject.h.
m_filePath
QString ccObject::m_filePath protected
Definition at line 222 of file ecvObject.h.
m_flags
unsigned ccObject::m_flags protected
Object flags.
Definition at line 227 of file ecvObject.h.
m_metaData
QVariantMap ccObject::m_metaData protected
Associated meta-data.
Definition at line 230 of file ecvObject.h.
m_name
QString ccObject::m_name protected
Object name.
Definition at line 219 of file ecvObject.h.
Referenced by cc2DLabel::getRawName().
m_removeFlag
bool ccObject::m_removeFlag protected
Definition at line 224 of file ecvObject.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvObject.h