ACloudViewer: colmap::Track Class Reference
colmap::Track Class Reference
#include <track.h>
Public Member Functions
Track ()
size_t Length () const
const std::vector< TrackElement > & Elements () const
std::vector< TrackElement > & Elements ()
void SetElements (const std::vector< TrackElement > &elements)
const TrackElement & Element (const size_t idx) const
TrackElement & Element (const size_t idx)
void SetElement (const size_t idx, const TrackElement &element)
void AddElement (const TrackElement &element)
void AddElement (const image_t image_id, const point2D_t point2D_idx)
void AddElements (const std::vector< TrackElement > &elements)
void DeleteElement (const size_t idx)
void DeleteElement (const image_t image_id, const point2D_t point2D_idx)
void Reserve (const size_t num_elements)
void Compress ()
bool operator== (const Track &other) const
bool operator!= (const Track &other) const
Detailed Description
Definition at line 30 of file track.h.
Constructor & Destructor Documentation
Track()
colmap::Track::Track ()
Definition at line 36 of file track.cc.
Member Function Documentation
AddElement() [1/2]
void colmap::Track::AddElement (const image_t image_id, const point2D_t point2D_idx) inline
Definition at line 107 of file track.h.
AddElement() [2/2]
void colmap::Track::AddElement (const TrackElement & element) inline
Definition at line 103 of file track.h.
Referenced by colmap::Reconstruction::AddObservation(), BOOST_AUTO_TEST_CASE(), colmap::IncrementalTriangulator::CompleteImage(), colmap::Reconstruction::Merge(), and colmap::IncrementalMapper::RegisterInitialImagePair().
AddElements()
void colmap::Track::AddElements (const std::vector< TrackElement > & elements) inline
Definition at line 111 of file track.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::MergePoints3D().
Compress()
void colmap::Track::Compress () inline
Definition at line 124 of file track.h.
Referenced by BOOST_AUTO_TEST_CASE().
DeleteElement() [1/2]
void colmap::Track::DeleteElement (const image_t image_id, const point2D_t point2D_idx)
Definition at line 44 of file track.cc.
DeleteElement() [2/2]
void colmap::Track::DeleteElement (const size_t idx) inline
Definition at line 115 of file track.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::DeleteObservation().
Element() [1/2]
TrackElement & colmap::Track::Element (const size_t idx) inline
Definition at line 97 of file track.h.
Element() [2/2]
const TrackElement & colmap::Track::Element (const size_t idx) const inline
Definition at line 93 of file track.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::IncrementalMapper::RegisterInitialImagePair().
Elements() [1/2]
std::vector< TrackElement > & colmap::Track::Elements () inline
Definition at line 86 of file track.h.
Elements() [2/2]
const std::vector< TrackElement > & colmap::Track::Elements () const inline
Definition at line 84 of file track.h.
Referenced by colmap::Reconstruction::AddPoint3D(), BOOST_AUTO_TEST_CASE(), colmap::Reconstruction::DeletePoint3D(), and colmap::Reconstruction::MergePoints3D().
Length()
size_t colmap::Track::Length () const inline
Definition at line 82 of file track.h.
Referenced by colmap::IncrementalMapper::AdjustLocalBundle(), BOOST_AUTO_TEST_CASE(), colmap::PointColormapTrackLen::ComputeColor(), colmap::Reconstruction::DeleteObservation(), colmap::Reconstruction::Merge(), colmap::Reconstruction::MergePoints3D(), colmap::BundleAdjuster::ParameterizePoints(), and colmap::RunPointFiltering().
operator!=()
bool colmap::Track::operator!= (const Track & other) const inline
Definition at line 130 of file track.h.
operator==()
bool colmap::Track::operator== (const Track & other) const inline
Definition at line 126 of file track.h.
Reserve()
void colmap::Track::Reserve (const size_t num_elements) inline
Definition at line 120 of file track.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::IncrementalTriangulator::CompleteImage(), colmap::Reconstruction::MergePoints3D(), and colmap::IncrementalMapper::RegisterInitialImagePair().
SetElement()
void colmap::Track::SetElement (const size_t idx, const TrackElement & element) inline
Definition at line 99 of file track.h.
SetElements()
void colmap::Track::SetElements (const std::vector< TrackElement > & elements) inline
Definition at line 88 of file track.h.
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/track.h
/root/ACloudViewer/libs/Reconstruction/src/base/track.cc