ACloudViewer: PdmsTools::PdmsCommands::ElementEnding Class Reference
PdmsTools::PdmsCommands::ElementEnding Class Reference
#include <PdmsTools.h>
Public Member Functions
ElementEnding (Token t=PDMS_END)
virtual bool handle (Token t)
virtual bool handle (const char *str)
virtual bool isValid () const
virtual bool execute (PdmsObjects::GenericItem *&item) const
Public Member Functions inherited from PdmsTools::PdmsCommands::Command
Command (Token t)
Command (const Command &com)
virtual ~Command ()
virtual bool handle (PointCoordinateType numvalue)
Public Attributes
Reference end
Public Attributes inherited from PdmsTools::PdmsCommands::Command
Token command
Additional Inherited Members
Static Public Member Functions inherited from PdmsTools::PdmsCommands::Command
static Command * Create (Token t)
Factory.
Detailed Description
Definition at line 633 of file PdmsTools.h.
Constructor & Destructor Documentation
ElementEnding()
PdmsTools::PdmsCommands::ElementEnding::ElementEnding (Token t = PDMS_END) inline explicit
Definition at line 637 of file PdmsTools.h.
Member Function Documentation
execute()
bool ElementEnding::execute (PdmsObjects::GenericItem *& item) const virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 721 of file PdmsTools.cpp.
References PdmsTools::PdmsObjects::GenericItem::owner, PdmsTools::PDMS_END, PdmsTools::PDMS_EXTRU, PdmsTools::PDMS_LAST, PdmsTools::PDMS_NEXTRU, PdmsTools::PDMS_OWNER, and result.
Referenced by PdmsTools::PdmsCommands::Reference::execute().
handle() [1/2]
virtual bool PdmsTools::PdmsCommands::ElementEnding::handle (const char * str) inline virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 642 of file PdmsTools.h.
References PdmsTools::PdmsCommands::Command::command, end, and PdmsTools::PdmsCommands::Reference::handle().
handle() [2/2]
virtual bool PdmsTools::PdmsCommands::ElementEnding::handle (Token t) inline virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 638 of file PdmsTools.h.
References PdmsTools::PdmsCommands::Command::command, end, and PdmsTools::PdmsCommands::Reference::handle().
isValid()
virtual bool PdmsTools::PdmsCommands::ElementEnding::isValid () const inline virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 646 of file PdmsTools.h.
References PdmsTools::PdmsCommands::Command::command, end, and PdmsTools::PdmsCommands::Reference::isValid().
Member Data Documentation
end
Reference PdmsTools::PdmsCommands::ElementEnding::end
Definition at line 635 of file PdmsTools.h.
Referenced by handle(), and isValid().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsTools.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsTools.cpp