ACloudViewer: colmap::ImageTab Class Reference
colmap::ImageTab Class Reference
#include <database_management_widget.h>
Public Member Functions
ImageTab (QWidget *parent, CameraTab *camera_tab, OptionManager *options, Database *database)
void Reload ()
void Clear ()
Detailed Description
Definition at line 110 of file database_management_widget.h.
Constructor & Destructor Documentation
ImageTab()
colmap::ImageTab::ImageTab (QWidget * parent, CameraTab * camera_tab, OptionManager * options, Database * database)
Definition at line 456 of file database_management_widget.cc.
Member Function Documentation
Clear()
void colmap::ImageTab::Clear ()
Definition at line 567 of file database_management_widget.cc.
Reload()
void colmap::ImageTab::Reload ()
Definition at line 522 of file database_management_widget.cc.
References image, colmap::Database::NumImages(), colmap::Database::NumKeypoints(), and colmap::Database::ReadAllImages().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/database_management_widget.h
/root/ACloudViewer/libs/Reconstruction/src/ui/database_management_widget.cc