ACloudViewer: ScalarFieldView Class Reference
ScalarFieldView Class Reference
Public Member Functions
ScalarFieldView (cloudViewer::ScalarField &field)
ScalarFieldView (const ScalarFieldView view, const py::slice &slice)
ScalarFieldView (cloudViewer::ScalarField &field, const py::slice &slice)
py::object get_item (const py::object &index)
void set_item (const py::object &index, const py::object &value)
size_t len () const
void applySlicing (const py::slice &slice)
Detailed Description
Definition at line 19 of file ScalarField.cpp.
Constructor & Destructor Documentation
ScalarFieldView() [1/3]
ScalarFieldView::ScalarFieldView (cloudViewer::ScalarField & field) inline explicit
Definition at line 22 of file ScalarField.cpp.
ScalarFieldView() [2/3]
ScalarFieldView::ScalarFieldView (const ScalarFieldView view, const py::slice & slice) inline explicit
Definition at line 27 of file ScalarField.cpp.
ScalarFieldView() [3/3]
ScalarFieldView::ScalarFieldView (cloudViewer::ScalarField & field, const py::slice & slice) inline explicit
Definition at line 32 of file ScalarField.cpp.
Member Function Documentation
applySlicing()
void ScalarFieldView::applySlicing (const py::slice & slice) inline
Definition at line 133 of file ScalarField.cpp.
get_item()
py::object ScalarFieldView::get_item (const py::object & index) inline
Definition at line 37 of file ScalarField.cpp.
References result.
Referenced by define_ScalarField().
len()
size_t ScalarFieldView::len () const inline
Definition at line 128 of file ScalarField.cpp.
Referenced by define_ScalarField().
set_item()
void ScalarFieldView::set_item (const py::object & index, const py::object & value) inline
Definition at line 65 of file ScalarField.cpp.
Referenced by define_ScalarField().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/ScalarField.cpp