ACloudViewer: cloudViewer::TwoViewInfoTab Class Reference
cloudViewer::TwoViewInfoTab Class Reference
#include <DatabaseManagementWidget.h>
Public Member Functions
TwoViewInfoTab ()
TwoViewInfoTab (QWidget *parent, OptionManager *options, colmap::Database *database)
void Clear ()
Protected Member Functions
void InitializeTable (const QStringList &table_header)
void ShowMatches ()
void FillTable ()
Protected Attributes
OptionManager * options_
colmap::Database * database_
const colmap::Image * image_
std::vector< std::pair< const colmap::Image *, colmap::FeatureMatches > > matches_
std::vector< int > configs_
std::vector< size_t > sorted_matches_idxs_
QTableWidget * table_widget_
QLabel * info_label_
FeatureImageViewerWidget * matches_viewer_widget_
Detailed Description
Definition at line 31 of file DatabaseManagementWidget.h.
Constructor & Destructor Documentation
TwoViewInfoTab() [1/2]
cloudViewer::TwoViewInfoTab::TwoViewInfoTab () inline
Definition at line 33 of file DatabaseManagementWidget.h.
TwoViewInfoTab() [2/2]
cloudViewer::TwoViewInfoTab::TwoViewInfoTab (QWidget * parent, OptionManager * options, colmap::Database * database)
Member Function Documentation
Clear()
void cloudViewer::TwoViewInfoTab::Clear ()
Definition at line 26 of file DatabaseManagementWidget.cpp.
FillTable()
void cloudViewer::TwoViewInfoTab::FillTable () protected
Definition at line 90 of file DatabaseManagementWidget.cpp.
Referenced by cloudViewer::MatchesTab::Reload(), and cloudViewer::TwoViewGeometriesTab::Reload().
InitializeTable()
void cloudViewer::TwoViewInfoTab::InitializeTable (const QStringList & table_header) protected
Definition at line 33 of file DatabaseManagementWidget.cpp.
Referenced by cloudViewer::MatchesTab::MatchesTab(), and cloudViewer::TwoViewGeometriesTab::TwoViewGeometriesTab().
ShowMatches()
void cloudViewer::TwoViewInfoTab::ShowMatches () protected
Definition at line 59 of file DatabaseManagementWidget.cpp.
References cloudViewer::utility::filesystem::JoinPaths().
Member Data Documentation
configs_
std::vector<int> cloudViewer::TwoViewInfoTab::configs_ protected
Definition at line 51 of file DatabaseManagementWidget.h.
Referenced by cloudViewer::TwoViewGeometriesTab::Reload().
database_
colmap::Database* cloudViewer::TwoViewInfoTab::database_ protected
Definition at line 46 of file DatabaseManagementWidget.h.
Referenced by cloudViewer::MatchesTab::Reload(), and cloudViewer::TwoViewGeometriesTab::Reload().
image_
const colmap::Image* cloudViewer::TwoViewInfoTab::image_ protected
Definition at line 48 of file DatabaseManagementWidget.h.
Referenced by cloudViewer::MatchesTab::Reload(), and cloudViewer::TwoViewGeometriesTab::Reload().
info_label_
QLabel* cloudViewer::TwoViewInfoTab::info_label_ protected
Definition at line 55 of file DatabaseManagementWidget.h.
matches_
std::vector<std::pair<const colmap::Image*, colmap::FeatureMatches> > cloudViewer::TwoViewInfoTab::matches_ protected
Definition at line 50 of file DatabaseManagementWidget.h.
Referenced by cloudViewer::MatchesTab::Reload(), and cloudViewer::TwoViewGeometriesTab::Reload().
matches_viewer_widget_
FeatureImageViewerWidget* cloudViewer::TwoViewInfoTab::matches_viewer_widget_ protected
Definition at line 56 of file DatabaseManagementWidget.h.
options_
OptionManager* cloudViewer::TwoViewInfoTab::options_ protected
Definition at line 45 of file DatabaseManagementWidget.h.
sorted_matches_idxs_
std::vector<size_t> cloudViewer::TwoViewInfoTab::sorted_matches_idxs_ protected
Definition at line 52 of file DatabaseManagementWidget.h.
table_widget_
QTableWidget* cloudViewer::TwoViewInfoTab::table_widget_ protected
Definition at line 54 of file DatabaseManagementWidget.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/reconstruction/DatabaseManagementWidget.h
/root/ACloudViewer/app/reconstruction/DatabaseManagementWidget.cpp