ACloudViewer: DimensionalityScaleParamsComputer Class Reference
DimensionalityScaleParamsComputer Class Reference
Public Member Functions
DimensionalityScaleParamsComputer ()
Default constructor.
virtual unsigned getID () const
Returns the associated descriptor ID.
virtual QString getName () const
Returns the associated descriptor name.
virtual unsigned dimPerScale () const
Returns the number of dimensions per scale for this descriptor.
virtual void reset ()
Called once before computing parameters at first scale.
virtual bool computeScaleParams (cloudViewer::ReferenceCloud &neighbors, double radius, float params[], bool &invalidScale)
Computes the parameters at a given scale.
Public Member Functions inherited from ScaleParamsComputer
virtual ~ScaleParamsComputer ()=default
virtual bool needSF () const
Returns whether the computer requires a scalar field or not.
Protected Attributes
float m_defaultParams [2]
Default parameters (or last computed scale's ones!)
bool m_firstScale
First scale flag.
Additional Inherited Members
Static Public Member Functions inherited from ScaleParamsComputer
static ScaleParamsComputer * GetByID (unsigned descID)
Vault: returns the computer corresponding to the given ID.
static unsigned AvailableCount ()
Returns the number of available 'descriptors'.
static ScaleParamsComputer * GetByIndex (unsigned index)
Vault: returns the ith computer.
Detailed Description
Per-scale "dimensionality" parameters computer (i.e. same as the original CANUPO suite)
Definition at line 37 of file ccPointDescriptor.cpp.
Constructor & Destructor Documentation
DimensionalityScaleParamsComputer()
DimensionalityScaleParamsComputer::DimensionalityScaleParamsComputer () inline
Default constructor.
Definition at line 40 of file ccPointDescriptor.cpp.
Member Function Documentation
computeScaleParams()
virtual bool DimensionalityScaleParamsComputer::computeScaleParams (cloudViewer::ReferenceCloud & neighbors, double radius, float params[], bool & invalidScale) inline virtual
Computes the parameters at a given scale.
Scales are always called in decreasing order.
Parameters
[in] neighbors the set of neighbors at the current scale
[in] radius current radius (half scale) value
[out] params the computed parameters
[out] invalidScale whether this scale is 'invalid' (i.e. parameters couldn't be computed, default one have been returned instead)
Returns
false if an error occurred (e.g. not enough memory)
Implements ScaleParamsComputer.
Definition at line 65 of file ccPointDescriptor.cpp.
References cloudViewer::Neighbourhood::computeCovarianceMatrix(), m_defaultParams, m_firstScale, params, cloudViewer::ReferenceCloud::size(), Jacobi< Scalar >::SortEigenValuesAndVectors(), SQRT_3_DIV_2, Tuple3Tpl< Type >::u, Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
dimPerScale()
virtual unsigned DimensionalityScaleParamsComputer::dimPerScale () const inline virtual
Returns the number of dimensions per scale for this descriptor.
Implements ScaleParamsComputer.
Definition at line 49 of file ccPointDescriptor.cpp.
getID()
virtual unsigned DimensionalityScaleParamsComputer::getID () const inline virtual
Returns the associated descriptor ID.
Implements ScaleParamsComputer.
Definition at line 43 of file ccPointDescriptor.cpp.
References DESC_DIMENSIONALITY.
getName()
virtual QString DimensionalityScaleParamsComputer::getName () const inline virtual
Returns the associated descriptor name.
Implements ScaleParamsComputer.
Definition at line 46 of file ccPointDescriptor.cpp.
reset()
virtual void DimensionalityScaleParamsComputer::reset () inline virtual
Called once before computing parameters at first scale.
Implements ScaleParamsComputer.
Definition at line 52 of file ccPointDescriptor.cpp.
References m_defaultParams, m_firstScale, and SQRT_3_DIV_2.
Member Data Documentation
m_defaultParams
float DimensionalityScaleParamsComputer::m_defaultParams[2] protected
Default parameters (or last computed scale's ones!)
Definition at line 131 of file ccPointDescriptor.cpp.
Referenced by computeScaleParams(), and reset().
m_firstScale
bool DimensionalityScaleParamsComputer::m_firstScale protected
First scale flag.
Definition at line 133 of file ccPointDescriptor.cpp.
Referenced by computeScaleParams(), and reset().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qCanupo/src/ccPointDescriptor.cpp