ACloudViewer: ccPluginInfoDlg Class Reference
ccPluginInfoDlg Class Reference
#include <ecvPluginInfoDlg.h>
Public Member Functions
ccPluginInfoDlg (QWidget *parent=nullptr)
~ccPluginInfoDlg ()
void setPluginPaths (const QStringList &pluginPaths)
void setPluginList (const QList< ccPluginInterface * > &pluginList)
Detailed Description
Definition at line 24 of file ecvPluginInfoDlg.h.
Constructor & Destructor Documentation
ccPluginInfoDlg()
ccPluginInfoDlg::ccPluginInfoDlg (QWidget * parent = nullptr) explicit
Definition at line 94 of file ecvPluginInfoDlg.cpp.
References QtCompatRegExpOption::CaseInsensitive.
~ccPluginInfoDlg()
ccPluginInfoDlg::~ccPluginInfoDlg ()
Definition at line 127 of file ecvPluginInfoDlg.cpp.
Member Function Documentation
setPluginList()
void ccPluginInfoDlg::setPluginList (const QList< ccPluginInterface * > & pluginList)
Definition at line 140 of file ecvPluginInfoDlg.cpp.
References ccPluginManager::get(), and name.
Referenced by ccPluginUIManager::showAboutDialog().
setPluginPaths()
void ccPluginInfoDlg::setPluginPaths (const QStringList & pluginPaths)
Definition at line 129 of file ecvPluginInfoDlg.cpp.
References cloudViewer::t::geometry::path.
Referenced by ccPluginUIManager::showAboutDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/pluginManager/ecvPluginInfoDlg.h
/root/ACloudViewer/app/pluginManager/ecvPluginInfoDlg.cpp