ACloudViewer: cloudViewer::visualization::gui::RotationInteractor Class Reference
cloudViewer::visualization::gui::RotationInteractor Class Reference
Public Member Functions
rendering::MatrixInteractorLogic & GetMatrixInteractor () override
Eigen::Vector3f GetCenterOfRotation () const
void SetCenterOfRotation (const Eigen::Vector3f &center)
void Mouse (const MouseEvent &e) override
void Key (const KeyEvent &e) override
Public Member Functions inherited from cloudViewer::visualization::gui::SceneWidget::MouseInteractor
virtual ~MouseInteractor ()=default
virtual bool Tick (const TickEvent &e)
Protected Types
enum class State {
NONE , PAN , DOLLY , ROTATE_XY ,
ROTATE_Z
}
Protected Member Functions
void SetInteractor (rendering::RotationInteractorLogic *r)
Protected Attributes
rendering::RotationInteractorLogic * interactor_ = nullptr
int mouse_down_x_ = 0
int mouse_down_y_ = 0
State state_ = State::NONE
Detailed Description
Definition at line 281 of file SceneWidget.cpp.
Member Enumeration Documentation
State
enum cloudViewer::visualization::gui::RotationInteractor::State strong protected
Enumerator
NONE
PAN
DOLLY
ROTATE_XY
ROTATE_Z
Definition at line 377 of file SceneWidget.cpp.
Member Function Documentation
GetCenterOfRotation()
Eigen::Vector3f cloudViewer::visualization::gui::RotationInteractor::GetCenterOfRotation () const inline
Definition at line 292 of file SceneWidget.cpp.
References cloudViewer::visualization::rendering::MatrixInteractorLogic::GetCenterOfRotation(), and interactor_.
GetMatrixInteractor()
rendering::MatrixInteractorLogic& cloudViewer::visualization::gui::RotationInteractor::GetMatrixInteractor () inline override virtual
Implements cloudViewer::visualization::gui::SceneWidget::MouseInteractor.
Definition at line 288 of file SceneWidget.cpp.
References interactor_.
Referenced by cloudViewer::visualization::gui::PickInteractor::SetViewSize().
Key()
void cloudViewer::visualization::gui::RotationInteractor::Key (const KeyEvent & e) inline override virtual
Implements cloudViewer::visualization::gui::SceneWidget::MouseInteractor.
Reimplemented in cloudViewer::visualization::gui::PickInteractor.
Definition at line 370 of file SceneWidget.cpp.
Mouse()
void cloudViewer::visualization::gui::RotationInteractor::Mouse (const MouseEvent & e) inline override virtual
Implements cloudViewer::visualization::gui::SceneWidget::MouseInteractor.
Reimplemented in cloudViewer::visualization::gui::PickInteractor, cloudViewer::visualization::gui::RotateCameraInteractor, and cloudViewer::visualization::gui::RotateModelInteractor.
Definition at line 300 of file SceneWidget.cpp.
References cloudViewer::visualization::gui::ALT, cloudViewer::visualization::gui::MouseEvent::button, cloudViewer::visualization::gui::MouseEvent::BUTTON_DOWN, cloudViewer::visualization::gui::MouseEvent::BUTTON_UP, cloudViewer::visualization::gui::CTRL, DOLLY, cloudViewer::visualization::rendering::MatrixInteractorLogic::Dolly(), cloudViewer::visualization::gui::MouseEvent::DRAG, cloudViewer::visualization::rendering::RotationInteractorLogic::EndMouseDrag(), interactor_, cloudViewer::visualization::gui::LEFT, cloudViewer::visualization::gui::META, cloudViewer::visualization::gui::MouseEvent::modifiers, mouse_down_x_, mouse_down_y_, NONE, PAN, cloudViewer::visualization::rendering::RotationInteractorLogic::Pan(), cloudViewer::visualization::gui::RIGHT, cloudViewer::visualization::rendering::MatrixInteractorLogic::Rotate(), ROTATE_XY, ROTATE_Z, cloudViewer::visualization::rendering::MatrixInteractorLogic::RotateZ(), cloudViewer::visualization::gui::SHIFT, cloudViewer::visualization::rendering::RotationInteractorLogic::StartMouseDrag(), state_, cloudViewer::visualization::gui::MouseEvent::type, cloudViewer::visualization::rendering::RotationInteractorLogic::UpdateMouseDragUI(), cloudViewer::visualization::gui::MouseEvent::WHEEL, cloudViewer::visualization::gui::MouseEvent::wheel, cloudViewer::visualization::gui::MouseEvent::x, and cloudViewer::visualization::gui::MouseEvent::y.
SetCenterOfRotation()
void cloudViewer::visualization::gui::RotationInteractor::SetCenterOfRotation (const Eigen::Vector3f & center) inline
Definition at line 296 of file SceneWidget.cpp.
References interactor_, and cloudViewer::visualization::rendering::RotationInteractorLogic::SetCenterOfRotation().
SetInteractor()
void cloudViewer::visualization::gui::RotationInteractor::SetInteractor (rendering::RotationInteractorLogic * r) inline protected
Definition at line 283 of file SceneWidget.cpp.
References interactor_.
Referenced by cloudViewer::visualization::gui::RotateCameraInteractor::RotateCameraInteractor(), cloudViewer::visualization::gui::RotateCameraSphereInteractor::RotateCameraSphereInteractor(), and cloudViewer::visualization::gui::RotateModelInteractor::RotateModelInteractor().
Member Data Documentation
interactor_
rendering::RotationInteractorLogic* cloudViewer::visualization::gui::RotationInteractor::interactor_ = nullptr protected
Definition at line 373 of file SceneWidget.cpp.
Referenced by GetCenterOfRotation(), GetMatrixInteractor(), Mouse(), SetCenterOfRotation(), and SetInteractor().
mouse_down_x_
int cloudViewer::visualization::gui::RotationInteractor::mouse_down_x_ = 0 protected
Definition at line 374 of file SceneWidget.cpp.
Referenced by Mouse().
mouse_down_y_
int cloudViewer::visualization::gui::RotationInteractor::mouse_down_y_ = 0 protected
Definition at line 375 of file SceneWidget.cpp.
Referenced by Mouse().
state_
State cloudViewer::visualization::gui::RotationInteractor::state_ = State::NONE protected
Definition at line 378 of file SceneWidget.cpp.
Referenced by Mouse().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/SceneWidget.cpp