ACloudViewer: ccVolumeCalcTool Class Reference
ccVolumeCalcTool Class Reference
Volume calculation tool (dialog)
#include <ecvVolumeCalcTool.h>
Classes
struct ReportInfo
Report info.
Public Member Functions
ccVolumeCalcTool (ccGenericPointCloud *cloud1, ccGenericPointCloud *cloud2, QWidget *parent=0)
Default constructor.
~ccVolumeCalcTool ()
Destructor.
virtual double getGridStep () const override
Returns projection grid step.
virtual unsigned char getProjectionDimension () const override
Returns projection dimension.
virtual ccRasterGrid::ProjectionType getTypeOfProjection () const override
Returns type of projection.
Public Member Functions inherited from cc2Point5DimEditor
cc2Point5DimEditor ()
Default constructor.
virtual ~cc2Point5DimEditor ()
Destructor.
Static Public Member Functions
static bool ComputeVolume (ccRasterGrid &grid, ccGenericPointCloud *ground, ccGenericPointCloud *ceil, const ccBBox &gridBox, unsigned char vertDim, double gridStep, unsigned gridWidth, unsigned gridHeight, ccRasterGrid::ProjectionType projectionType, ccRasterGrid::EmptyCellFillOption groundEmptyCellFillStrategy, ccRasterGrid::EmptyCellFillOption ceilEmptyCellFillStrategy, ccVolumeCalcTool::ReportInfo &reportInfo, double groundHeight, double ceilHeight, QWidget *parentWidget=0)
Static accessor.
static ccPointCloud * ConvertGridToCloud (ccRasterGrid &grid, const ccBBox &gridBox, unsigned char vertDim, bool exportToOriginalCS)
Converts a (volume) grid to a point cloud.
Protected Slots
void saveSettingsAndAccept ()
Accepts the dialog and save settings.
void saveSettings ()
Save persistent settings and 'accept' dialog.
void projectionDirChanged (int)
Called when the projection direction changes.
void sfProjectionTypeChanged (int)
Called when the SF projection type changes.
virtual bool showGridBoxEditor () override
void groundFillEmptyCellStrategyChanged (int)
Called when the (ground) empty cell filling strategy changes.
void ceilFillEmptyCellStrategyChanged (int)
Called when the (ceil) empty cell filling strategy changes.
void gridOptionChanged ()
Called when the an option of the grid generation has changed.
void updateGridInfo ()
Updates the gid info.
void updateGridAndDisplay ()
Update the grid and the 2D display.
void swapRoles ()
Swap roles.
void groundSourceChanged (int)
Ground source changed.
void ceilSourceChanged (int)
Ceil source changed.
void exportToClipboard () const
Exports info to clipboard.
void exportGridAsCloud () const
Exports the grid as a point cloud.
void setDisplayedNumberPrecision (int)
Sets the displayed number precision.
Protected Member Functions
virtual void gridIsUpToDate (bool state) override
Declares whether the grid is up-to-date or not.
void loadSettings ()
Load persistent settings.
bool updateGrid ()
Updates the grid.
ccPointCloud * convertGridToCloud (bool exportToOriginalCS) const
Converts the grid to a point cloud.
void outputReport (const ReportInfo &info)
Outputs the report.
Protected Member Functions inherited from cc2Point5DimEditor
virtual ccBBox getCustomBBox () const
Returns custom bbox.
virtual void update2DDisplayZoom (ccBBox &box)
Updates the 2D display zoom.
virtual bool showGridBoxEditor ()
Show grid box editor and update.
virtual QString getGridSizeAsString () const
Returns the grid size as a string.
virtual bool getGridSize (unsigned &width, unsigned &height) const
Returns the grid size.
void createBoundingBoxEditor (const ccBBox &gridBBox, QWidget *parent)
Creates the bounding-box editor.
void create2DView (QFrame *parentFrame)
Creates the 2D view.
ccRasterGrid::EmptyCellFillOption getFillEmptyCellsStrategy (QComboBox *comboBox) const
Returns the empty cell strategy (for a given combo-box)
ccPointCloud * convertGridToCloud (const std::vector< ccRasterGrid::ExportableFields > &exportedFields, bool interpolateSF, bool interpolateColors, bool resampleInputCloudXY, bool resampleInputCloudZ, ccGenericPointCloud *inputCloud, bool fillEmptyCells, double emptyCellsHeight, bool exportToOriginalCS) const
Shortcut to ccRasterGrid::convertToCloud.
Protected Attributes
ccGenericPointCloud * m_cloud1
First associated cloud.
ccGenericPointCloud * m_cloud2
Second associated cloud.
ReportInfo m_lastReport
Last report.
Protected Attributes inherited from cc2Point5DimEditor
ccRasterGrid m_grid
Raster grid.
ccBoundingBoxEditorDlg * m_bbEditorDlg
Associated dialog.
ccPointCloud * m_rasterCloud
'Raster' cloud
Detailed Description
Volume calculation tool (dialog)
Definition at line 24 of file ecvVolumeCalcTool.h.
Constructor & Destructor Documentation
ccVolumeCalcTool()
ccVolumeCalcTool::ccVolumeCalcTool (ccGenericPointCloud * cloud1, ccGenericPointCloud * cloud2, QWidget * parent = 0)
Default constructor.
Definition at line 42 of file ecvVolumeCalcTool.cpp.
References ceilFillEmptyCellStrategyChanged(), ceilSourceChanged(), cc2Point5DimEditor::create2DView(), cc2Point5DimEditor::createBoundingBoxEditor(), exportGridAsCloud(), exportToClipboard(), ecvDisplayTools::GetDisplayParameters(), ecvDisplayTools::GetMainWindow(), ccObject::getName(), ccGenericPointCloud::getOwnBB(), gridIsUpToDate(), gridOptionChanged(), groundFillEmptyCellStrategyChanged(), groundSourceChanged(), cloudViewer::BoundingBoxTpl< T >::isValid(), loadSettings(), m_cloud1, m_cloud2, params, projectionDirChanged(), saveSettingsAndAccept(), setDisplayedNumberPrecision(), ecvDisplayTools::SetDisplayParameters(), showGridBoxEditor(), std::swap(), swapRoles(), updateGridAndDisplay(), and updateGridInfo().
~ccVolumeCalcTool()
ccVolumeCalcTool::~ccVolumeCalcTool ()
Destructor.
Definition at line 157 of file ecvVolumeCalcTool.cpp.
Member Function Documentation
ceilFillEmptyCellStrategyChanged
void ccVolumeCalcTool::ceilFillEmptyCellStrategyChanged (int) protected slot
Called when the (ceil) empty cell filling strategy changes.
Definition at line 246 of file ecvVolumeCalcTool.cpp.
References ccRasterGrid::FILL_CUSTOM_HEIGHT, cc2Point5DimEditor::getFillEmptyCellsStrategy(), and gridIsUpToDate().
Referenced by ccVolumeCalcTool(), and ceilSourceChanged().
ceilSourceChanged
void ccVolumeCalcTool::ceilSourceChanged (int) protected slot
Ceil source changed.
Definition at line 180 of file ecvVolumeCalcTool.cpp.
References ceilFillEmptyCellStrategyChanged().
Referenced by ccVolumeCalcTool().
ComputeVolume()
bool ccVolumeCalcTool::ComputeVolume (ccRasterGrid & grid, ccGenericPointCloud * ground, ccGenericPointCloud * ceil, const ccBBox & gridBox, unsigned char vertDim, double gridStep, unsigned gridWidth, unsigned gridHeight, ccRasterGrid::ProjectionType projectionType, ccRasterGrid::EmptyCellFillOption groundEmptyCellFillStrategy, ccRasterGrid::EmptyCellFillOption ceilEmptyCellFillStrategy, ccVolumeCalcTool::ReportInfo & reportInfo, double groundHeight = std::numeric_limits<double>::quiet_NaN(), double ceilHeight = std::numeric_limits<double>::quiet_NaN(), QWidget * parentWidget = 0) static
Static accessor.
Definition at line 499 of file ecvVolumeCalcTool.cpp.
References ccVolumeCalcTool::ReportInfo::addedVolume, ccVolumeCalcTool::ReportInfo::averageNeighborsPerCell, ccRasterCell::avgHeight, cloudViewer::utility::ceil(), ccVolumeCalcTool::ReportInfo::ceilNonMatchingPercent, count, ccRasterGrid::fillEmptyCells(), ccRasterGrid::fillWith(), Vector3Tpl< double >::fromArray(), ccRasterGrid::gridStep, ccVolumeCalcTool::ReportInfo::groundNonMatchingPercent, ccRasterCell::h, ccRasterGrid::height, ccRasterGrid::init(), ccRasterGrid::INTERPOLATE_DELAUNAY, ccRasterGrid::INVALID_PROJECTION_TYPE, cloudViewer::BoundingBoxTpl< T >::isValid(), ccVolumeCalcTool::ReportInfo::matchingPrecent, ccRasterCell::maxHeight, ccRasterGrid::maxHeight, cloudViewer::BoundingBoxTpl< T >::minCorner(), ccRasterCell::minHeight, ccRasterGrid::minHeight, ccRasterCell::nbPoints, ccRasterGrid::nonEmptyCellCount, nProgress, cloudViewer::NormalizedProgress::oneStep(), CVLog::Print(), ccVolumeCalcTool::ReportInfo::removedVolume, ccRasterGrid::rows, SendError(), ccRasterGrid::setValid(), ccRasterCell::stdDevHeight, ccVolumeCalcTool::ReportInfo::surface, Tuple3Tpl< Type >::u, ccRasterGrid::validCellCount, ccVolumeCalcTool::ReportInfo::volume, CVLog::Warning(), and ccRasterGrid::width.
Referenced by CommandVolume25D::process(), and updateGrid().
convertGridToCloud()
ccPointCloud * ccVolumeCalcTool::convertGridToCloud (bool exportToOriginalCS) const protected
Converts the grid to a point cloud.
Definition at line 395 of file ecvVolumeCalcTool.cpp.
References cc2Point5DimEditor::convertGridToCloud(), CVLog::Error(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), cloudViewer::PointCloudTpl< T >::getScalarField(), ccPointCloud::hasScalarFields(), ccRasterGrid::PER_CELL_VALUE, ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::ScalarField::setName(), ccScalarField::setSymmetricalScale(), ccDrawableObject::showSF(), and ccPointCloud::showSFColorsScale().
Referenced by exportGridAsCloud(), and updateGridAndDisplay().
ConvertGridToCloud()
ccPointCloud * ccVolumeCalcTool::ConvertGridToCloud (ccRasterGrid & grid, const ccBBox & gridBox, unsigned char vertDim, bool exportToOriginalCS) static
Converts a (volume) grid to a point cloud.
Definition at line 356 of file ecvVolumeCalcTool.cpp.
References ccRasterGrid::convertToCloud(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), cloudViewer::PointCloudTpl< T >::getScalarField(), ccPointCloud::hasScalarFields(), cloudViewer::BoundingBoxTpl< T >::isValid(), ccRasterGrid::PER_CELL_VALUE, ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::ScalarField::setName(), ccScalarField::setSymmetricalScale(), ccDrawableObject::showSF(), ccPointCloud::showSFColorsScale(), and CVLog::Warning().
Referenced by CommandVolume25D::process().
exportGridAsCloud
void ccVolumeCalcTool::exportGridAsCloud () const protected slot
Exports the grid as a point cloud.
Definition at line 817 of file ecvVolumeCalcTool.cpp.
References ccHObject::addChild(), MainWindow::addToDB(), convertGridToCloud(), ccObject::getName(), ccHObject::getParent(), ccRasterGrid::isValid(), m_cloud1, m_cloud2, cc2Point5DimEditor::m_grid, CVLog::Print(), ccObject::setName(), and MainWindow::TheInstance().
Referenced by ccVolumeCalcTool().
exportToClipboard
void ccVolumeCalcTool::exportToClipboard () const protected slot
Exports info to clipboard.
Definition at line 810 of file ecvVolumeCalcTool.cpp.
Referenced by ccVolumeCalcTool().
getGridStep()
double ccVolumeCalcTool::getGridStep () const override virtual
Returns projection grid step.
Implements cc2Point5DimEditor.
Definition at line 216 of file ecvVolumeCalcTool.cpp.
Referenced by updateGrid().
getProjectionDimension()
unsigned char ccVolumeCalcTool::getProjectionDimension () const override virtual
Returns projection dimension.
Returns
dimension as int (0: X, 1: Y, 2:Z)
Implements cc2Point5DimEditor.
Definition at line 220 of file ecvVolumeCalcTool.cpp.
Referenced by updateGrid().
getTypeOfProjection()
ccRasterGrid::ProjectionType ccVolumeCalcTool::getTypeOfProjection () const override virtual
Returns type of projection.
Implements cc2Point5DimEditor.
Definition at line 258 of file ecvVolumeCalcTool.cpp.
References ccRasterGrid::INVALID_PROJECTION_TYPE, ccRasterGrid::PROJ_AVERAGE_VALUE, ccRasterGrid::PROJ_MAXIMUM_VALUE, and ccRasterGrid::PROJ_MINIMUM_VALUE.
Referenced by updateGrid().
gridIsUpToDate()
void ccVolumeCalcTool::gridIsUpToDate (bool state) override protected virtual
Declares whether the grid is up-to-date or not.
Implements cc2Point5DimEditor.
Definition at line 339 of file ecvVolumeCalcTool.cpp.
Referenced by ccVolumeCalcTool(), ceilFillEmptyCellStrategyChanged(), gridOptionChanged(), groundFillEmptyCellStrategyChanged(), projectionDirChanged(), sfProjectionTypeChanged(), swapRoles(), and updateGridAndDisplay().
gridOptionChanged
void ccVolumeCalcTool::gridOptionChanged () protected slot
Called when the an option of the grid generation has changed.
Definition at line 256 of file ecvVolumeCalcTool.cpp.
References gridIsUpToDate().
Referenced by ccVolumeCalcTool().
groundFillEmptyCellStrategyChanged
void ccVolumeCalcTool::groundFillEmptyCellStrategyChanged (int) protected slot
Called when the (ground) empty cell filling strategy changes.
Definition at line 236 of file ecvVolumeCalcTool.cpp.
References ccRasterGrid::FILL_CUSTOM_HEIGHT, cc2Point5DimEditor::getFillEmptyCellsStrategy(), and gridIsUpToDate().
Referenced by ccVolumeCalcTool(), and groundSourceChanged().
groundSourceChanged
void ccVolumeCalcTool::groundSourceChanged (int) protected slot
Ground source changed.
Definition at line 174 of file ecvVolumeCalcTool.cpp.
References groundFillEmptyCellStrategyChanged().
Referenced by ccVolumeCalcTool().
loadSettings()
void ccVolumeCalcTool::loadSettings () protected
Load persistent settings.
Definition at line 274 of file ecvVolumeCalcTool.cpp.
References ecvPS::VolumeCalculation().
Referenced by ccVolumeCalcTool().
outputReport()
void ccVolumeCalcTool::outputReport (const ReportInfo & info) protected
Outputs the report.
Definition at line 478 of file ecvVolumeCalcTool.cpp.
References ccVolumeCalcTool::ReportInfo::averageNeighborsPerCell, m_lastReport, and ccVolumeCalcTool::ReportInfo::toText().
Referenced by setDisplayedNumberPrecision(), and updateGrid().
projectionDirChanged
void ccVolumeCalcTool::projectionDirChanged (int dir) protected slot
Called when the projection direction changes.
Definition at line 231 of file ecvVolumeCalcTool.cpp.
References gridIsUpToDate(), and updateGridInfo().
Referenced by ccVolumeCalcTool().
saveSettings
void ccVolumeCalcTool::saveSettings () protected slot
Save persistent settings and 'accept' dialog.
Definition at line 320 of file ecvVolumeCalcTool.cpp.
References ecvPS::VolumeCalculation().
Referenced by saveSettingsAndAccept().
saveSettingsAndAccept
void ccVolumeCalcTool::saveSettingsAndAccept () protected slot
Accepts the dialog and save settings.
Definition at line 315 of file ecvVolumeCalcTool.cpp.
References saveSettings().
Referenced by ccVolumeCalcTool().
setDisplayedNumberPrecision
void ccVolumeCalcTool::setDisplayedNumberPrecision (int precision) protected slot
Sets the displayed number precision.
Definition at line 159 of file ecvVolumeCalcTool.cpp.
References ecvDisplayTools::GetDisplayParameters(), ecvDisplayTools::GetMainWindow(), m_lastReport, outputReport(), params, ecvDisplayTools::RedrawDisplay(), and ecvDisplayTools::SetDisplayParameters().
Referenced by ccVolumeCalcTool().
sfProjectionTypeChanged
void ccVolumeCalcTool::sfProjectionTypeChanged (int index) protected slot
Called when the SF projection type changes.
Definition at line 227 of file ecvVolumeCalcTool.cpp.
References gridIsUpToDate().
showGridBoxEditor
bool ccVolumeCalcTool::showGridBoxEditor () override protected virtual slot
Definition at line 203 of file ecvVolumeCalcTool.cpp.
References cc2Point5DimEditor::showGridBoxEditor(), and updateGridInfo().
Referenced by ccVolumeCalcTool().
swapRoles
void ccVolumeCalcTool::swapRoles () protected slot
Swap roles.
Definition at line 185 of file ecvVolumeCalcTool.cpp.
References gridIsUpToDate().
Referenced by ccVolumeCalcTool().
updateGrid()
bool ccVolumeCalcTool::updateGrid () protected
Updates the grid.
Definition at line 738 of file ecvVolumeCalcTool.cpp.
References ComputeVolume(), cc2Point5DimEditor::getCustomBBox(), cc2Point5DimEditor::getFillEmptyCellsStrategy(), cc2Point5DimEditor::getGridSize(), getGridStep(), getProjectionDimension(), getTypeOfProjection(), cloudViewer::BoundingBoxTpl< T >::isValid(), m_cloud1, m_cloud2, cc2Point5DimEditor::m_grid, and outputReport().
Referenced by updateGridAndDisplay().
updateGridAndDisplay
void ccVolumeCalcTool::updateGridAndDisplay () protected slot
Update the grid and the 2D display.
Definition at line 427 of file ecvVolumeCalcTool.cpp.
References ecvDisplayTools::AddToOwnDB(), convertGridToCloud(), CVLog::Error(), ccHObject::getDisplayBB_recursive(), ecvDisplayTools::GetMainWindow(), gridIsUpToDate(), cc2Point5DimEditor::m_rasterCloud, ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::RemoveFromOwnDB(), cc2Point5DimEditor::update2DDisplayZoom(), and updateGrid().
Referenced by ccVolumeCalcTool().
updateGridInfo
void ccVolumeCalcTool::updateGridInfo () protected slot
Updates the gid info.
Definition at line 212 of file ecvVolumeCalcTool.cpp.
References cc2Point5DimEditor::getGridSizeAsString().
Referenced by ccVolumeCalcTool(), projectionDirChanged(), and showGridBoxEditor().
Member Data Documentation
m_cloud1
ccGenericPointCloud* ccVolumeCalcTool::m_cloud1 protected
First associated cloud.
Definition at line 157 of file ecvVolumeCalcTool.h.
Referenced by ccVolumeCalcTool(), exportGridAsCloud(), and updateGrid().
m_cloud2
ccGenericPointCloud* ccVolumeCalcTool::m_cloud2 protected
Second associated cloud.
Definition at line 159 of file ecvVolumeCalcTool.h.
Referenced by ccVolumeCalcTool(), exportGridAsCloud(), and updateGrid().
m_lastReport
ReportInfo ccVolumeCalcTool::m_lastReport protected
Last report.
Only valid if clipboardPushButton is enabled
Definition at line 164 of file ecvVolumeCalcTool.h.
Referenced by outputReport(), and setDisplayedNumberPrecision().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvVolumeCalcTool.h
/root/ACloudViewer/app/ecvVolumeCalcTool.cpp