ACloudViewer: GlobalUtil Class Reference
GlobalUtil Class Reference
#include <GlobalUtil.h>
Static Public Member Functions
static double CLOCK ()
static void StopTimer ()
static void StartTimer (const char *event)
static float GetElapsedTime ()
static void FitViewPort (int width, int height)
static void SetTextureParameter ()
static void SetTextureParameterUS ()
static void CheckErrorsGL (const char *location=NULL)
static bool CheckFramebufferStatus ()
static void SelectDisplay ()
static void InitGLParam (int NotTargetGL=0)
static void SetGLParam ()
static int CreateWindowEZ ()
static void CleanupOpenGL ()
static void SetDeviceParam (int argc, char **argv)
static int CreateWindowEZ (LiteWindow *window)
Additional Inherited Members
Static Public Attributes inherited from GlobalParam
static GLuint _texTarget = GL_TEXTURE_RECTANGLE_ARB
static GLuint _iTexFormat =GL_RGBA32F_ARB
static int _texMaxDim = 3200
static int _texMaxDimGL = 4096
static int _texMinDim = 16
static int _MemCapGPU = 0
static int _FitMemoryCap = 0
static int _verbose = 1
static int _timingS = 1
static int _timingO = 0
static int _timingL = 0
static int _usePackedTex = 1
static int _IsNvidia = 0
static int _KeepShaderLoop = 0
static int _UseCUDA = 0
static int _UseOpenCL = 0
static int _UseDynamicIndexing = 0
static int _debug = 0
static int _MaxFilterWidth = -1
static float _FilterWidthFactor = 4.0f
static float _OrientationWindowFactor = 2.0f
static float _DescriptorWindowFactor = 3.0f
static int _MaxOrientation = 2
static int _OrientationPack2 = 0
static int _ListGenGPU = 1
static int _ListGenSkipGPU = 6
static int _SupportNVFloat = 0
static int _SupportTextureRG = 0
static int _FullSupported = 1
static float _MaxFeaturePercent = 0.005f
static int _MaxLevelFeatureNum = 4096
static int _DescriptorPPR = 8
static int _DescriptorPPT = 16
static int _FeatureTexBlock = 4
static int _NarrowFeatureTex = 0
static int _SubpixelLocalization = 1
static int _ProcessOBO = 0
static int _TruncateMethod = 0
static int _PreciseBorder = 1
static int _UseSiftGPUEX = 0
static int _ForceTightPyramid = 0
static int _octave_min_default =0
static int _octave_num_default =-1
static int _InitPyramidWidth =0
static int _InitPyramidHeight =0
static int _PreProcessOnCPU = 1
static int _GoodOpenGL = -1
static int _FixedOrientation = 0
static int _LoweOrigin = 0
static int _ExitAfterSIFT = 0
static int _NormalizedSIFT = 1
static int _BinarySIFT = 0
static int _KeepExtremumSign = 0
static int _FeatureCountThreshold = -1
static int _KeyPointListForceLevel0 = 0
static int _DarknessAdaption = 0
static float _OrientationExtraFactor
static float _OrientationGaussianFactor = 1.5f
static float _MulitiOrientationThreshold = 0.8f
static int _WindowInitX = -1
static int _WindowInitY = -1
static const char * _WindowDisplay = NULL
static int _DeviceIndex = 0
Detailed Description
Definition at line 122 of file GlobalUtil.h.
Member Function Documentation
CheckErrorsGL()
static void GlobalUtil::CheckErrorsGL (const char * location = NULL) inline static
Definition at line 137 of file GlobalUtil.h.
Referenced by GLTexImage::CopyFromPBO(), PyramidPacked::DetectKeypointsEX(), and ShaderMan::InitShaderMan().
CheckFramebufferStatus()
bool GlobalUtil::CheckFramebufferStatus () static
Definition at line 250 of file GlobalUtil.cpp.
Referenced by PyramidPacked::GetFeatureOrientations().
CleanupOpenGL()
void GlobalUtil::CleanupOpenGL () static
Definition at line 156 of file GlobalUtil.cpp.
Referenced by PyramidGL::CleanUpAfterSIFT().
CLOCK()
static double GlobalUtil::CLOCK () inline static
Definition at line 126 of file GlobalUtil.h.
References ClockTimer::CLOCK().
Referenced by PyramidNaive::ComputeGradient(), PyramidPacked::ComputeGradient(), PyramidNaive::DetectKeypointsEX(), PyramidPacked::DetectKeypointsEX(), PyramidNaive::GenerateFeatureList(), and PyramidPacked::GenerateFeatureList().
CreateWindowEZ() [1/2]
int GlobalUtil::CreateWindowEZ () static
Definition at line 458 of file GlobalUtil.cpp.
Referenced by SiftMatchGPU::_CreateContextGL(), SiftGPU::CreateContextGL(), and CreateLiteWindow().
CreateWindowEZ() [2/2]
int GlobalUtil::CreateWindowEZ (LiteWindow * window) static
Definition at line 441 of file GlobalUtil.cpp.
References GlobalParam::_WindowDisplay, GlobalParam::_WindowInitX, GlobalParam::_WindowInitY, LiteWindow::Create(), LiteWindow::IsValid(), LiteWindow::MakeCurrent(), and NULL.
FitViewPort()
void GlobalUtil::FitViewPort (int width, int height) static
Definition at line 234 of file GlobalUtil.cpp.
References height, and width.
Referenced by GLTexImage::FillMargin(), GLTexPacked::FillMargin(), GLTexImage::FitRealTexViewPort(), GLTexImage::FitTexViewPort(), PyramidGL::GenerateFeatureDisplayVBO(), PyramidGL::GetFeatureDescriptors(), SiftGPU::RunSIFT(), GLTexInput::SetImageData(), GLTexPacked::ZeroHistoMargin(), and GLTexImage::ZeroHistoMargin().
GetElapsedTime()
static float GlobalUtil::GetElapsedTime () inline static
Definition at line 129 of file GlobalUtil.h.
References ClockTimer::GetElapsedTime().
Referenced by SiftPyramid::RunSIFT(), and SiftGPU::RunSIFT().
InitGLParam()
void GlobalUtil::InitGLParam (int NotTargetGL = 0) static
Definition at line 319 of file GlobalUtil.cpp.
References GlobalParam::_GoodOpenGL, GlobalParam::_IsNvidia, GlobalParam::_KeepShaderLoop, GlobalParam::_MemCapGPU, GlobalParam::_SupportNVFloat, GlobalParam::_SupportTextureRG, GlobalParam::_texMaxDim, GlobalParam::_texMaxDimGL, GlobalParam::_texTarget, GlobalParam::_UseCUDA, GlobalParam::_UseSiftGPUEX, GlobalParam::_verbose, NULL, and SetTextureParameter().
Referenced by SiftMatchGPU::_VerifyContextGL(), PyramidGL::InitializeContext(), and SiftMatchGL::InitSiftMatch().
SelectDisplay()
void GlobalUtil::SelectDisplay () static
Definition at line 417 of file GlobalUtil.cpp.
References GlobalParam::_WindowDisplay, and NULL.
Referenced by SiftGPU::ParseParam().
SetDeviceParam()
void GlobalUtil::SetDeviceParam (int argc, char ** argv) static
Definition at line 161 of file GlobalUtil.cpp.
References GlobalParam::_DeviceIndex, GlobalParam::_GoodOpenGL, GlobalParam::_WindowDisplay, GlobalParam::_WindowInitX, GlobalParam::_WindowInitY, NULL, and STRING_TO_INT.
Referenced by SiftMatchGPU::SetDeviceParam().
SetGLParam()
void GlobalUtil::SetGLParam () static
Definition at line 311 of file GlobalUtil.cpp.
References GlobalParam::_texTarget, GlobalParam::_UseCUDA, and GlobalParam::_UseOpenCL.
Referenced by SiftGPU::RunSIFT().
SetTextureParameter()
void GlobalUtil::SetTextureParameter () static
Definition at line 211 of file GlobalUtil.cpp.
References GlobalParam::_texTarget.
Referenced by InitGLParam(), and ShaderMan::TextureUpSample().
SetTextureParameterUS()
void GlobalUtil::SetTextureParameterUS () static
Definition at line 223 of file GlobalUtil.cpp.
References GlobalParam::_texTarget.
Referenced by ShaderMan::TextureUpSample().
StartTimer()
static void GlobalUtil::StartTimer (const char * event) inline static
Definition at line 128 of file GlobalUtil.h.
References GlobalParam::_timingO, event, and ClockTimer::StartTimer().
Referenced by ShaderMan::InitShaderMan(), SiftGPU::InitSiftGPU(), SiftPyramid::RunSIFT(), and SiftGPU::RunSIFT().
StopTimer()
static void GlobalUtil::StopTimer () inline static
Definition at line 127 of file GlobalUtil.h.
References GlobalParam::_timingS, and ClockTimer::StopTimer().
Referenced by ShaderMan::InitShaderMan(), SiftGPU::InitSiftGPU(), SiftPyramid::RunSIFT(), and SiftGPU::RunSIFT().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/GlobalUtil.h
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/GlobalUtil.cpp