ACloudViewer: colmap::Point2D Class Reference
colmap::Point2D Class Reference
#include <point2d.h>
Public Member Functions
Point2D ()
const Eigen::Vector2d & XY () const
Eigen::Vector2d & XY ()
double X () const
double Y () const
void SetXY (const Eigen::Vector2d &xy)
point3D_t Point3DId () const
bool HasPoint3D () const
void SetPoint3DId (const point3D_t point3D_id)
bool operator== (const Point2D &other) const
bool operator!= (const Point2D &other) const
Detailed Description
Definition at line 20 of file point2d.h.
Constructor & Destructor Documentation
Point2D()
colmap::Point2D::Point2D ()
Definition at line 36 of file point2d.cc.
Member Function Documentation
HasPoint3D()
bool colmap::Point2D::HasPoint3D () const inline
Definition at line 65 of file point2d.h.
References colmap::kInvalidPoint3DId.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::IncrementalTriangulator::CompleteImage(), colmap::Reconstruction::FilterObservationsWithNegativeDepth(), colmap::IncrementalMapper::RegisterNextImage(), colmap::Image::ResetPoint3DForPoint2D(), colmap::IncrementalTriangulator::Retriangulate(), and colmap::Image::SetPoint3DForPoint2D().
operator!=()
bool colmap::Point2D::operator!= (const Point2D & other) const inline
Definition at line 75 of file point2d.h.
operator==()
bool colmap::Point2D::operator== (const Point2D & other) const inline
Definition at line 71 of file point2d.h.
References Point3DId(), and XY().
Point3DId()
point3D_t colmap::Point2D::Point3DId () const inline
Definition at line 63 of file point2d.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::IncrementalTriangulator::CompleteImage(), colmap::Reconstruction::FilterObservationsWithNegativeDepth(), operator==(), and colmap::IncrementalMapper::RegisterNextImage().
SetPoint3DId()
void colmap::Point2D::SetPoint3DId (const point3D_t point3D_id) inline
Definition at line 67 of file point2d.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Image::ResetPoint3DForPoint2D(), and colmap::Image::SetPoint3DForPoint2D().
SetXY()
void colmap::Point2D::SetXY (const Eigen::Vector2d & xy) inline
Definition at line 61 of file point2d.h.
Referenced by BOOST_AUTO_TEST_CASE().
X()
double colmap::Point2D::X () const inline
Definition at line 57 of file point2d.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Image::DecrementCorrespondenceHasPoint3D(), colmap::Reconstruction::ExportBundler(), colmap::Reconstruction::ExportNVM(), colmap::Reconstruction::ExportRecon3D(), colmap::Image::IncrementCorrespondenceHasPoint3D(), cloudViewer::PointViewerWidget::Show(), and colmap::PointViewerWidget::Show().
XY() [1/2]
Eigen::Vector2d & colmap::Point2D::XY () inline
Definition at line 55 of file point2d.h.
XY() [2/2]
const Eigen::Vector2d & colmap::Point2D::XY () const inline
Definition at line 53 of file point2d.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::IncrementalTriangulator::CompleteImage(), operator==(), colmap::IncrementalMapper::RegisterInitialImagePair(), colmap::IncrementalMapper::RegisterNextImage(), cloudViewer::PointViewerWidget::Show(), and colmap::PointViewerWidget::Show().
Y()
double colmap::Point2D::Y () const inline
Definition at line 59 of file point2d.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Image::DecrementCorrespondenceHasPoint3D(), colmap::Reconstruction::ExportBundler(), colmap::Reconstruction::ExportNVM(), colmap::Reconstruction::ExportRecon3D(), colmap::Image::IncrementCorrespondenceHasPoint3D(), cloudViewer::PointViewerWidget::Show(), and colmap::PointViewerWidget::Show().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/point2d.h
/root/ACloudViewer/libs/Reconstruction/src/base/point2d.cc