ACloudViewer: colmap::FeatureMatcherCache Class Reference
colmap::FeatureMatcherCache Class Reference
#include <matching.h>
Public Member Functions
FeatureMatcherCache (const size_t cache_size, const Database *database)
void Setup ()
const Camera & GetCamera (const camera_t camera_id)
const Image & GetImage (const image_t image_id)
std::shared_ptr< FeatureKeypoints > GetKeypoints (const image_t image_id)
std::shared_ptr< FeatureDescriptors > GetDescriptors (const image_t image_id)
FeatureMatches GetMatches (const image_t image_id1, const image_t image_id2)
std::vector< image_t > GetImageIds ()
bool ExistsKeypoints (const image_t image_id)
bool ExistsDescriptors (const image_t image_id)
bool ExistsMatches (const image_t image_id1, const image_t image_id2)
bool ExistsInlierMatches (const image_t image_id1, const image_t image_id2)
void WriteMatches (const image_t image_id1, const image_t image_id2, const FeatureMatches &matches)
void WriteTwoViewGeometry (const image_t image_id1, const image_t image_id2, const TwoViewGeometry &two_view_geometry)
void DeleteMatches (const image_t image_id1, const image_t image_id2)
void DeleteInlierMatches (const image_t image_id1, const image_t image_id2)
Detailed Description
Definition at line 159 of file matching.h.
Constructor & Destructor Documentation
FeatureMatcherCache()
colmap::FeatureMatcherCache::FeatureMatcherCache (const size_t cache_size, const Database * database)
Definition at line 216 of file matching.cc.
Member Function Documentation
DeleteInlierMatches()
void colmap::FeatureMatcherCache::DeleteInlierMatches (const image_t image_id1, const image_t image_id2)
Definition at line 360 of file matching.cc.
References colmap::Database::DeleteInlierMatches().
Referenced by colmap::SiftFeatureMatcher::Match().
DeleteMatches()
void colmap::FeatureMatcherCache::DeleteMatches (const image_t image_id1, const image_t image_id2)
Definition at line 354 of file matching.cc.
References colmap::Database::DeleteMatches().
Referenced by colmap::SiftFeatureMatcher::Match().
ExistsDescriptors()
bool colmap::FeatureMatcherCache::ExistsDescriptors (const image_t image_id)
Definition at line 324 of file matching.cc.
Referenced by colmap::SiftCPUFeatureMatcher::Run(), and colmap::SiftGPUFeatureMatcher::Run().
ExistsInlierMatches()
bool colmap::FeatureMatcherCache::ExistsInlierMatches (const image_t image_id1, const image_t image_id2)
Definition at line 334 of file matching.cc.
References colmap::Database::ExistsInlierMatches().
Referenced by colmap::SiftFeatureMatcher::Match().
ExistsKeypoints()
bool colmap::FeatureMatcherCache::ExistsKeypoints (const image_t image_id)
Definition at line 320 of file matching.cc.
ExistsMatches()
bool colmap::FeatureMatcherCache::ExistsMatches (const image_t image_id1, const image_t image_id2)
Definition at line 328 of file matching.cc.
References colmap::Database::ExistsMatches().
Referenced by colmap::SiftFeatureMatcher::Match().
GetCamera()
const Camera & colmap::FeatureMatcherCache::GetCamera (const camera_t camera_id)
Definition at line 282 of file matching.cc.
Referenced by colmap::TwoViewGeometryVerifier::Run().
GetDescriptors()
std::shared_ptr< FeatureDescriptors > colmap::FeatureMatcherCache::GetDescriptors (const image_t image_id)
Definition at line 297 of file matching.cc.
Referenced by colmap::SiftGPUFeatureMatcher::GetDescriptorData(), and colmap::SiftCPUFeatureMatcher::Run().
GetImage()
const Image & colmap::FeatureMatcherCache::GetImage (const image_t image_id)
Definition at line 287 of file matching.cc.
Referenced by colmap::TwoViewGeometryVerifier::Run().
GetImageIds()
std::vector< image_t > colmap::FeatureMatcherCache::GetImageIds ()
Definition at line 308 of file matching.cc.
References image.
GetKeypoints()
std::shared_ptr< FeatureKeypoints > colmap::FeatureMatcherCache::GetKeypoints (const image_t image_id)
Definition at line 292 of file matching.cc.
Referenced by colmap::TwoViewGeometryVerifier::Run().
GetMatches()
FeatureMatches colmap::FeatureMatcherCache::GetMatches (const image_t image_id1, const image_t image_id2)
Definition at line 302 of file matching.cc.
References colmap::Database::ReadMatches().
Referenced by colmap::SiftFeatureMatcher::Match().
Setup()
void colmap::FeatureMatcherCache::Setup ()
Definition at line 250 of file matching.cc.
References colmap::Database::ExistsDescriptors(), colmap::Database::ExistsKeypoints(), colmap::Database::ReadDescriptors(), and colmap::Database::ReadKeypoints().
WriteMatches()
void colmap::FeatureMatcherCache::WriteMatches (const image_t image_id1, const image_t image_id2, const FeatureMatches & matches)
Definition at line 340 of file matching.cc.
References colmap::Database::WriteMatches().
Referenced by colmap::SiftFeatureMatcher::Match().
WriteTwoViewGeometry()
void colmap::FeatureMatcherCache::WriteTwoViewGeometry (const image_t image_id1, const image_t image_id2, const TwoViewGeometry & two_view_geometry)
Definition at line 347 of file matching.cc.
References colmap::Database::WriteTwoViewGeometry().
Referenced by colmap::SiftFeatureMatcher::Match().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/feature/matching.h
/root/ACloudViewer/libs/Reconstruction/src/feature/matching.cc