ACloudViewer: cloudViewer::benchmarks::TestKDTreeLine0 Class Reference
cloudViewer::benchmarks::TestKDTreeLine0 Class Reference
Public Member Functions
void setup (int size)
void search (int radiusInSteps)
Detailed Description
Definition at line 17 of file KDTreeFlann.cpp.
Member Function Documentation
search()
void cloudViewer::benchmarks::TestKDTreeLine0::search (int radiusInSteps) inline
Definition at line 40 of file KDTreeFlann.cpp.
References LogError, result, cloudViewer::geometry::KDTreeFlann::SearchRadius(), and size_.
Referenced by cloudViewer::benchmarks::BM_TestKDTreeLine0().
setup()
void cloudViewer::benchmarks::TestKDTreeLine0::setup (int size) inline
Definition at line 26 of file KDTreeFlann.cpp.
References cloudViewer::PointCloudTpl< T >::addEigenPoint(), ccPointCloud::clear(), LogInfo, cloudViewer::geometry::KDTreeFlann::SetGeometry(), and size.
Referenced by cloudViewer::benchmarks::BM_TestKDTreeLine0().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CVViewer/benchmarks/geometry/KDTreeFlann.cpp