ACloudViewer: qM3C2Process Class Reference
qM3C2Process Class Reference
M3C2 process.
#include <qM3C2Process.h>
Static Public Member Functions
static bool Compute (const qM3C2Dialog &dlg, QString &errorMessage, ccPointCloud *&outputCloud, bool allowDialogs, QWidget *parentWidget=nullptr, ecvMainAppInterface *app=nullptr)
Detailed Description
M3C2 process.
See "Accurate 3D comparison of complex topography with terrestrial laser scanner: application to the Rangitikei canyon (N-Z)", Lague, D., Brodu, N. and Leroux, J., 2013, ISPRS journal of Photogrammmetry and Remote Sensing
Definition at line 20 of file qM3C2Process.h.
Member Function Documentation
Compute()
bool qM3C2Process::Compute (const qM3C2Dialog & dlg, QString & errorMessage, ccPointCloud *& outputCloud, bool allowDialogs, QWidget * parentWidget = nullptr, ecvMainAppInterface * app = nullptr) static
Definition at line 428 of file qM3C2Process.cpp.
References ccPointCloud::addScalarField(), M3C2Params::cloud1Octree, M3C2Params::cloud1PM, M3C2Params::cloud2Octree, M3C2Params::cloud2PM, M3C2Params::computeConfidence, qM3C2Normals::ComputeCorePointsNormals(), ComputeM3C2DistForPoint(), ccScalarField::computeMinAndMax(), ccGenericPointCloud::computeOctree(), M3C2Params::coreNormals, M3C2Params::corePoints, ccArray< Type, N, ComponentType >::currentSize(), qM3C2Normals::DEFAULT_MODE, DENSITY_CLOUD1_SF_NAME, DENSITY_CLOUD2_SF_NAME, M3C2Params::densityCloud1SF, M3C2Params::densityCloud2SF, DIST_UNCERTAINTY_SF_NAME, M3C2Params::distUncertaintySF, error(), M3C2Params::exportNormal, M3C2Params::exportOption, qM3C2Dialog::getCloud1(), qM3C2Dialog::getCloud2(), qM3C2Dialog::getCorePointsCloud(), qM3C2Dialog::getExportOption(), qM3C2Dialog::getMaxThreadCount(), qM3C2Dialog::getMinPointsForStats(), cloudViewer::ScalarField::getName(), ccObject::getName(), qM3C2Dialog::getNormalsComputationMode(), qM3C2Dialog::getNormalsOrientationCloud(), ccGenericPointCloud::getOctree(), ccGenericPointCloud::getOctreeProxy(), ccHObject::getParent(), cloudViewer::PointCloudTpl< T >::getScalarField(), ccArray< Type, N, ComponentType >::getValue(), ccPointCloud::hasNormals(), qM3C2Normals::HORIZ_MODE, ccGenericPointCloud::importParametersFrom(), ccPointCloud::invalidateBoundingBox(), invalidNormals, qM3C2Dialog::keepOriginalCloud(), M3C2Params::keepOriginalCloud, M3C2Params::level1, M3C2Params::level2, CCShareable::link(), M3C2_DIST_SF_NAME, M3C2Params::m3c2DistSF, qM3C2Normals::MakeNormalsHorizontal(), max(), M3C2Params::minPoints4Stats, ccNormalVectors::MINUS_SENSOR_ORIGIN, qM3C2Normals::MULTI_SCALE_MODE, NAN_VALUE, NORMAL_SCALE_SF_NAME, ccPointCloud::normals(), normalScale, nProgress, M3C2Params::nProgress, M3C2Params::onlyPositiveSearch, orientationCloud, M3C2Params::outputCloud, ccNormalVectors::PLUS_X, M3C2Params::processCanceled, M3C2Params::progressiveSearch, M3C2Params::projectionDepth, M3C2Params::projectionRadius, radii, M3C2Params::registrationRms, CCShareable::release(), RemoveScalarField(), cloudViewer::CloudSamplingTools::resampleCloudSpatially(), ccPointCloud::resize(), cloudViewer::ScalarField::resizeSafe(), ccPointCloud::resizeTheNormsTable(), s_M3C2Params, SCALAR_ONE, SCALAR_ZERO, PrecisionMaps::scale, ccPointCloud::setCurrentDisplayedScalarField(), ccObject::setEnabled(), ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), ccScalarField::setMinDisplayed(), ccObject::setName(), ccPointCloud::setNormsTable(), ccPointCloud::setPointNormalIndex(), ccScalarField::setSymmetricalScale(), ccDrawableObject::setVisible(), ccDrawableObject::showNormals(), ccDrawableObject::showSF(), SIG_CHANGE_SF_NAME, M3C2Params::sigChangeSF, cloudViewer::GenericCloud::size(), cloudViewer::PointCloudTpl< T >::size(), sourceCloud, ecvProgressDialog::start(), STD_DEV_CLOUD1_SF_NAME, STD_DEV_CLOUD2_SF_NAME, M3C2Params::stdDevCloud1SF, M3C2Params::stdDevCloud2SF, PrecisionMaps::sX, PrecisionMaps::sY, PrecisionMaps::sZ, M3C2Params::updateNormal, ccNormalVectors::UpdateNormalOrientations(), qM3C2Normals::UpdateNormalOrientationsWithCloud(), qM3C2Normals::USE_CLOUD1_NORMALS, qM3C2Normals::USE_CORE_POINTS_NORMALS, M3C2Params::useMedian, M3C2Params::usePrecisionMaps, PrecisionMaps::valid(), and qM3C2Normals::VERT_MODE.
Referenced by ComputeWrapper(), and CommandM3C2::process().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qM3C2/include/qM3C2Process.h
/root/ACloudViewer/plugins/core/Standard/qM3C2/src/qM3C2Process.cpp