ACloudViewer: StatisticalOutliersRemover Class Reference
StatisticalOutliersRemover Class Reference
#include <StatisticalOutliersRemover.h>
Public Member Functions
StatisticalOutliersRemover ()
virtual ~StatisticalOutliersRemover ()
Public Member Functions inherited from BasePclModule
BasePclModule (PclModuleDescription desc=PclModuleDescription(), ccPluginInterface *parent_plugin=0)
Default constructor.
QAction * getAction ()
Get the action associated with the button used in menu and toolbar creation.
virtual QString getErrorMessage (int errorCode)
Returns the error message corresponding to a given error code.
QString getStatusTip () const
Returns the status tip.
QString getModuleName () const
Returns the name of the filter.
QString getEntryName () const
Returns the entry name.
QIcon getIcon () const
Returns the icon associated with the button.
void setShowProgressBar (bool status)
Sets whether to show a progressbar while computing or not.
std::vector< std::string > getSelectedAvailableScalarFields ()
ccPointCloud * getSelectedEntityAsCCPointCloud () const
Returns the first selected entity as a ccPointCloud.
ccHObject * getSelectedEntityAsCCHObject () const
Returns the first selected entity as a ccHObject.
ccHObject::Container getSelectedThatHaveMetaData (const QString key) const
Get selected object that also have the provided metadata key.
void getAllEntitiesOfType (CV_CLASS_ENUM type, ccHObject::Container &entities)
Returns all the objects in db tree of type "type".
void getAllEntitiesThatHaveMetaData (QString key, ccHObject::Container &entities)
void getSelectedEntitiesThatAreCCPointCloud (ccHObject::Container &entities)
get all entities that are selected and that also are cc_point_cloud
void getSelectedEntitiesThatAre (CV_CLASS_ENUM kind, ccHObject::Container &entities)
int hasSelectedRGB ()
Returns 1 if the first selected entity has RGB info.
int hasSelectedScalarField ()
Returns 1 if the first selected entity has at least one scalar field.
int hasSelectedScalarField (std::string field_name)
int isFirstSelectedCcPointCloud ()
Returns 1 if the first selected object is a ccPointCloud.
virtual void updateSelectedEntities (const ccHObject::Container &selectedEntities)
Updates the internal copy of selected entities.
void setMainAppInterface (ecvMainAppInterface *app)
Sets associated CC application interface (to access DB)
ecvMainAppInterface * getMainAppInterface ()
ccPluginInterface * getParentPlugin () const
Returns the associated parent plugin interface.
Protected Member Functions
int compute ()
Performs the actual filter job.
int openInputDialog ()
void getParametersFromDialog ()
Collects parameters from the filter dialog (if openDialog is successful)
Protected Member Functions inherited from BasePclModule
virtual int checkSelected ()
Checks if current selection is compliant with the filter.
virtual int openOutputDialog ()
virtual int checkParameters ()
virtual int start ()
Starts computation.
virtual void initAction ()
Initializes the corresponding action.
void throwError (int errCode)
Protected Attributes
SORDialog * m_dialog
int m_k
float m_std
Protected Attributes inherited from BasePclModule
QAction * m_action
Forces the Ui to be updated.
ccHObject::Container m_selected
Pointer to the main window.
PclModuleDescription m_desc
Associated dialog.
ecvMainAppInterface * m_app
Associated application interface.
ccPluginInterface * m_parent_plugin
associated parent plugin of the filter
bool m_show_progress
Do we want to show a progress bar when the filter works?
Additional Inherited Members
Signals inherited from BasePclModule
void entityHasChanged (ccHObject *)
Signal emitted when an entity is (visually) modified.
void newEntity (ccHObject *)
Signal emitted when a new entity is created by the filter.
void newErrorMessage (QString)
Signal emitted when a new error message is produced.
Protected Slots inherited from BasePclModule
int performAction ()
Returns is called when the dialog window is accepted.
Detailed Description
Definition at line 14 of file StatisticalOutliersRemover.h.
Constructor & Destructor Documentation
StatisticalOutliersRemover()
StatisticalOutliersRemover::StatisticalOutliersRemover ()
Definition at line 26 of file StatisticalOutliersRemover.cpp.
~StatisticalOutliersRemover()
StatisticalOutliersRemover::~StatisticalOutliersRemover () virtual
Definition at line 37 of file StatisticalOutliersRemover.cpp.
References m_dialog.
Member Function Documentation
compute()
int StatisticalOutliersRemover::compute () protected virtual
Performs the actual filter job.
This method MUST be re-implemented by derived filter
Returns
1 if successful (error code otherwise)
Implements BasePclModule.
Definition at line 58 of file StatisticalOutliersRemover.cpp.
References ccHObject::addChild(), pcl2cc::Convert(), cc2smReader::getAsSM(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccObject::getName(), ccHObject::getParent(), BasePclModule::getSelectedEntityAsCCPointCloud(), m_k, m_std, BasePclModule::newEntity(), PCLModules::RemoveOutliersStatistical< PCLCloud >(), result, ccObject::setEnabled(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), and ccObject::setName().
getParametersFromDialog()
void StatisticalOutliersRemover::getParametersFromDialog () protected virtual
Collects parameters from the filter dialog (if openDialog is successful)
Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Reimplemented from BasePclModule.
Definition at line 50 of file StatisticalOutliersRemover.cpp.
References m_dialog, m_k, and m_std.
openInputDialog()
int StatisticalOutliersRemover::openInputDialog () protected virtual
Opens the input dialog window. Where the user can supply parameters for the computation Automatically called by performAction. Does nothing by default. Must be overridden if a dialog must be displayed.
Returns
1 if dialog has been successfully executed, 0 if canceled, negative error code otherwise
Reimplemented from BasePclModule.
Definition at line 42 of file StatisticalOutliersRemover.cpp.
References ecvMainAppInterface::getMainWindow(), BasePclModule::m_app, and m_dialog.
Member Data Documentation
m_dialog
SORDialog* StatisticalOutliersRemover::m_dialog protected
Definition at line 24 of file StatisticalOutliersRemover.h.
Referenced by getParametersFromDialog(), openInputDialog(), and ~StatisticalOutliersRemover().
m_k
int StatisticalOutliersRemover::m_k protected
Definition at line 25 of file StatisticalOutliersRemover.h.
Referenced by compute(), and getParametersFromDialog().
m_std
float StatisticalOutliersRemover::m_std protected
Definition at line 26 of file StatisticalOutliersRemover.h.
Referenced by compute(), and getParametersFromDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/StatisticalOutliersRemover.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/StatisticalOutliersRemover.cpp