ACloudViewer: ClockTimer Class Reference
ClockTimer Class Reference
#include <GlobalUtil.h>
Public Member Functions
void StopTimer (int verb=1)
void StartTimer (const char *event, int verb=0)
float GetElapsedTime ()
Static Public Member Functions
static int ClockMS ()
static double CLOCK ()
static void InitHighResolution ()
Detailed Description
Definition at line 107 of file GlobalUtil.h.
Member Function Documentation
CLOCK()
double ClockTimer::CLOCK () static
Definition at line 287 of file GlobalUtil.cpp.
Referenced by GlobalUtil::CLOCK().
ClockMS()
int ClockTimer::ClockMS () static
Definition at line 282 of file GlobalUtil.cpp.
GetElapsedTime()
float ClockTimer::GetElapsedTime ()
Definition at line 306 of file GlobalUtil.cpp.
Referenced by GlobalUtil::GetElapsedTime().
InitHighResolution()
void ClockTimer::InitHighResolution () static
Definition at line 292 of file GlobalUtil.cpp.
Referenced by SiftGPU::InitSiftGPU().
StartTimer()
void ClockTimer::StartTimer (const char * event, int verb = 0)
Definition at line 296 of file GlobalUtil.cpp.
Referenced by GlobalUtil::StartTimer().
StopTimer()
void ClockTimer::StopTimer (int verb = 1)
Definition at line 301 of file GlobalUtil.cpp.
Referenced by GlobalUtil::StopTimer().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/GlobalUtil.h
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/GlobalUtil.cpp