ACloudViewer: ccItemSelectionDlg Class Reference
ccItemSelectionDlg Class Reference
Dialog to select one or multiple items.
#include <ecvItemSelectionDlg.h>
Public Member Functions
ccItemSelectionDlg (bool multiSelectionEnabled, QWidget *parent=0, QString itemName="entities", QString label=QString())
Default constructor.
void setItems (const QStringList &items, int defaultSelectedIndex=0)
Sets the list of items.
int getSelectedIndex () const
Returns selected index (unique selection mode)
void getSelectedIndexes (std::vector< int > &indexes) const
Returns selected indexes (multi-selection mode)
Static Public Member Functions
static int SelectEntity (const ccHObject::Container &entities, int defaultSelectedIndex=0, QWidget *parent=0, QString label=QString())
Static shortcut: unique selection mode.
static bool SelectEntities (const ccHObject::Container &entities, std::vector< int > &indexes, QWidget *parent=0, QString label=QString())
Static shortcut: multi-selection mode.
Detailed Description
Dialog to select one or multiple items.
Definition at line 16 of file ecvItemSelectionDlg.h.
Constructor & Destructor Documentation
ccItemSelectionDlg()
ccItemSelectionDlg::ccItemSelectionDlg (bool multiSelectionEnabled, QWidget * parent = 0, QString itemName = "entities", QString label = QString())
Default constructor.
Definition at line 14 of file ecvItemSelectionDlg.cpp.
Member Function Documentation
getSelectedIndex()
int ccItemSelectionDlg::getSelectedIndex () const
Returns selected index (unique selection mode)
Definition at line 52 of file ecvItemSelectionDlg.cpp.
Referenced by SelectEntity().
getSelectedIndexes()
void ccItemSelectionDlg::getSelectedIndexes (std::vector< int > & indexes) const
Returns selected indexes (multi-selection mode)
Definition at line 58 of file ecvItemSelectionDlg.cpp.
Referenced by ccEntityAction::interpolateSFs(), and SelectEntities().
SelectEntities()
bool ccItemSelectionDlg::SelectEntities (const ccHObject::Container & entities, std::vector< int > & indexes, QWidget * parent = 0, QString label = QString()) static
Static shortcut: multi-selection mode.
Definition at line 97 of file ecvItemSelectionDlg.cpp.
References getSelectedIndexes(), and setItems().
SelectEntity()
int ccItemSelectionDlg::SelectEntity (const ccHObject::Container & entities, int defaultSelectedIndex = 0, QWidget * parent = 0, QString label = QString()) static
Static shortcut: unique selection mode.
Definition at line 74 of file ecvItemSelectionDlg.cpp.
References getSelectedIndex(), and setItems().
Referenced by ccGraphicalSegmentationTool::doActionUseExistingPolyline().
setItems()
void ccItemSelectionDlg::setItems (const QStringList & items, int defaultSelectedIndex = 0)
Sets the list of items.
Definition at line 36 of file ecvItemSelectionDlg.cpp.
Referenced by ccEntityAction::interpolateSFs(), SelectEntities(), and SelectEntity().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvItemSelectionDlg.h
/root/ACloudViewer/app/ecvItemSelectionDlg.cpp