ACloudViewer: NurbsCurveFitting Class Reference
NurbsCurveFitting Class Reference
Greedy Triangulation.
#include <NurbsCurveFitting.h>
Public Member Functions
NurbsCurveFitting ()
virtual ~NurbsCurveFitting ()
virtual int compute ()
Performs the actual filter job.
Public Member Functions inherited from BasePclModule
BasePclModule (PclModuleDescription desc=PclModuleDescription(), ccPluginInterface *parent_plugin=0)
Default constructor.
QAction * getAction ()
Get the action associated with the button used in menu and toolbar creation.
QString getStatusTip () const
Returns the status tip.
QString getModuleName () const
Returns the name of the filter.
QString getEntryName () const
Returns the entry name.
QIcon getIcon () const
Returns the icon associated with the button.
void setShowProgressBar (bool status)
Sets whether to show a progressbar while computing or not.
std::vector< std::string > getSelectedAvailableScalarFields ()
ccPointCloud * getSelectedEntityAsCCPointCloud () const
Returns the first selected entity as a ccPointCloud.
ccHObject * getSelectedEntityAsCCHObject () const
Returns the first selected entity as a ccHObject.
ccHObject::Container getSelectedThatHaveMetaData (const QString key) const
Get selected object that also have the provided metadata key.
void getAllEntitiesOfType (CV_CLASS_ENUM type, ccHObject::Container &entities)
Returns all the objects in db tree of type "type".
void getAllEntitiesThatHaveMetaData (QString key, ccHObject::Container &entities)
void getSelectedEntitiesThatAreCCPointCloud (ccHObject::Container &entities)
get all entities that are selected and that also are cc_point_cloud
void getSelectedEntitiesThatAre (CV_CLASS_ENUM kind, ccHObject::Container &entities)
int hasSelectedRGB ()
Returns 1 if the first selected entity has RGB info.
int hasSelectedScalarField ()
Returns 1 if the first selected entity has at least one scalar field.
int hasSelectedScalarField (std::string field_name)
int isFirstSelectedCcPointCloud ()
Returns 1 if the first selected object is a ccPointCloud.
virtual void updateSelectedEntities (const ccHObject::Container &selectedEntities)
Updates the internal copy of selected entities.
void setMainAppInterface (ecvMainAppInterface *app)
Sets associated CC application interface (to access DB)
ecvMainAppInterface * getMainAppInterface ()
ccPluginInterface * getParentPlugin () const
Returns the associated parent plugin interface.
Protected Member Functions
virtual int checkSelected ()
Checks if current selection is compliant with the filter.
virtual int openInputDialog ()
virtual void getParametersFromDialog ()
Collects parameters from the filter dialog (if openDialog is successful)
virtual int checkParameters ()
virtual QString getErrorMessage (int errorCode)
Returns the error message corresponding to a given error code.
Protected Member Functions inherited from BasePclModule
virtual int openOutputDialog ()
virtual int start ()
Starts computation.
virtual void initAction ()
Initializes the corresponding action.
void throwError (int errCode)
Protected Attributes
NurbsCurveFittingDlg * m_dialog
bool m_exportProjectedCloud
bool m_useVoxelGrid
int m_minimizationType
bool m_curveFitting3D
bool m_closed
int m_order
int m_curveResolution
int m_controlPoints
float m_curveSmoothness
float m_curveRscale
Protected Attributes inherited from BasePclModule
QAction * m_action
Forces the Ui to be updated.
ccHObject::Container m_selected
Pointer to the main window.
PclModuleDescription m_desc
Associated dialog.
ecvMainAppInterface * m_app
Associated application interface.
ccPluginInterface * m_parent_plugin
associated parent plugin of the filter
bool m_show_progress
Do we want to show a progress bar when the filter works?
Additional Inherited Members
Signals inherited from BasePclModule
void entityHasChanged (ccHObject *)
Signal emitted when an entity is (visually) modified.
void newEntity (ccHObject *)
Signal emitted when a new entity is created by the filter.
void newErrorMessage (QString)
Signal emitted when a new error message is produced.
Protected Slots inherited from BasePclModule
int performAction ()
Returns is called when the dialog window is accepted.
Detailed Description
Greedy Triangulation.
Definition at line 18 of file NurbsCurveFitting.h.
Constructor & Destructor Documentation
NurbsCurveFitting()
NurbsCurveFitting::NurbsCurveFitting ()
Definition at line 32 of file NurbsCurveFitting.cpp.
~NurbsCurveFitting()
NurbsCurveFitting::~NurbsCurveFitting () virtual
Definition at line 50 of file NurbsCurveFitting.cpp.
References m_dialog.
Member Function Documentation
checkParameters()
int NurbsCurveFitting::checkParameters () protected virtual
Checks that the parameters retrieved by getParametersFromDialog are valid Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Returns
1 if parameters are valid (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 94 of file NurbsCurveFitting.cpp.
checkSelected()
int NurbsCurveFitting::checkSelected () protected virtual
Checks if current selection is compliant with the filter.
If not, an error is returned and computation stops. By default, baseclass method simply checks that selection is composed of one and only one ccPointCloud. This method should be overridden if necessary.
Returns
1 if selection is compliant (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 55 of file NurbsCurveFitting.cpp.
References BasePclModule::isFirstSelectedCcPointCloud().
compute()
int NurbsCurveFitting::compute () virtual
Performs the actual filter job.
This method MUST be re-implemented by derived filter
Returns
1 if successful (error code otherwise)
Implements BasePclModule.
Definition at line 96 of file NurbsCurveFitting.cpp.
References a, ccHObject::addChild(), pcl2cc::Convert(), ccGLMatrixTpl< T >::data(), ccPlane::Fit(), ccGLMatrixTpl< float >::FromToRotation(), ccHObject::getChildrenNumber(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccObject::getName(), ccPlane::getNormal(), ccHObject::getParent(), ecvTools::GetPolylines(), BasePclModule::getSelectedEntityAsCCPointCloud(), cc2smReader::getXYZ2(), ccGLMatrixTpl< T >::inverse(), m_closed, m_controlPoints, m_curveFitting3D, m_curveResolution, m_curveRscale, m_curveSmoothness, m_exportProjectedCloud, m_minimizationType, m_order, m_useVoxelGrid, BasePclModule::newEntity(), PC_ONE, CVLog::Print(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccObject::setName(), ccDrawableObject::setVisible(), cloudViewer::ReferenceCloud::size(), TO_PCL_CLOUD, and PCLModules::VoxelGridFilter< PointT >().
getErrorMessage()
QString NurbsCurveFitting::getErrorMessage (int errorCode) protected virtual
Returns the error message corresponding to a given error code.
Each filter have a set of possible error message to be used given bt getFilterErrorMessage() Baseclass implementation provides some generic messages.
Note
These messages can be replaced by re-implementing this method and handling the same codes BEFORE calling the baseclass method
Reimplemented from BasePclModule.
Definition at line 262 of file NurbsCurveFitting.cpp.
References BasePclModule::getErrorMessage().
getParametersFromDialog()
void NurbsCurveFitting::getParametersFromDialog () protected virtual
Collects parameters from the filter dialog (if openDialog is successful)
Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Reimplemented from BasePclModule.
Definition at line 74 of file NurbsCurveFitting.cpp.
References m_closed, m_controlPoints, m_curveFitting3D, m_curveResolution, m_curveRscale, m_curveSmoothness, m_dialog, m_exportProjectedCloud, m_minimizationType, m_order, and m_useVoxelGrid.
openInputDialog()
int NurbsCurveFitting::openInputDialog () protected virtual
Opens the input dialog window. Where the user can supply parameters for the computation Automatically called by performAction. Does nothing by default. Must be overridden if a dialog must be displayed.
Returns
1 if dialog has been successfully executed, 0 if canceled, negative error code otherwise
Reimplemented from BasePclModule.
Definition at line 63 of file NurbsCurveFitting.cpp.
References ecvMainAppInterface::getActiveWindow(), BasePclModule::m_app, and m_dialog.
Member Data Documentation
m_closed
bool NurbsCurveFitting::m_closed protected
Definition at line 40 of file NurbsCurveFitting.h.
Referenced by compute(), and getParametersFromDialog().
m_controlPoints
int NurbsCurveFitting::m_controlPoints protected
Definition at line 44 of file NurbsCurveFitting.h.
Referenced by compute(), and getParametersFromDialog().
m_curveFitting3D
bool NurbsCurveFitting::m_curveFitting3D protected
Definition at line 39 of file NurbsCurveFitting.h.
Referenced by compute(), and getParametersFromDialog().
m_curveResolution
int NurbsCurveFitting::m_curveResolution protected
Definition at line 43 of file NurbsCurveFitting.h.
Referenced by compute(), and getParametersFromDialog().
m_curveRscale
float NurbsCurveFitting::m_curveRscale protected
Definition at line 46 of file NurbsCurveFitting.h.
Referenced by compute(), and getParametersFromDialog().
m_curveSmoothness
float NurbsCurveFitting::m_curveSmoothness protected
Definition at line 45 of file NurbsCurveFitting.h.
Referenced by compute(), and getParametersFromDialog().
m_dialog
NurbsCurveFittingDlg* NurbsCurveFitting::m_dialog protected
Definition at line 34 of file NurbsCurveFitting.h.
Referenced by getParametersFromDialog(), openInputDialog(), and ~NurbsCurveFitting().
m_exportProjectedCloud
bool NurbsCurveFitting::m_exportProjectedCloud protected
Definition at line 35 of file NurbsCurveFitting.h.
Referenced by compute(), and getParametersFromDialog().
m_minimizationType
int NurbsCurveFitting::m_minimizationType protected
Definition at line 37 of file NurbsCurveFitting.h.
Referenced by compute(), and getParametersFromDialog().
m_order
int NurbsCurveFitting::m_order protected
Definition at line 42 of file NurbsCurveFitting.h.
Referenced by compute(), and getParametersFromDialog().
m_useVoxelGrid
bool NurbsCurveFitting::m_useVoxelGrid protected
Definition at line 36 of file NurbsCurveFitting.h.
Referenced by compute(), and getParametersFromDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Surfaces/NurbsCurveFitting.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Surfaces/NurbsCurveFitting.cpp