ACloudViewer: ProfileImportDlg Class Reference
ProfileImportDlg Class Reference
Dialog for importing a 2D revolution profile (qSRA plugin)
#include <profileImportDlg.h>
Public Member Functions
ProfileImportDlg (QWidget *parent=0)
Default constructor.
ProfileImportDlg (QWidget *parent=0)
Default constructor.
int getAxisDimension () const
void setDefaultFilename (QString filename)
Sets default filename.
QString getFilename () const
Returns input filename (on completion)
bool absoluteHeightValues () const
ProfileImportDlg (QWidget *parent=0)
Default constructor.
int getAxisDimension () const
Returns revolution axis dimension index.
void setDefaultFilename (QString filename)
Sets default filename.
QString getFilename () const
Returns input filename (on completion)
bool absoluteHeightValues () const
Protected Slots
void saveSettings ()
Save settings.
void browseFile ()
Called when the 'browse' tool button is pressed.
void browseFile ()
Called when the 'browse' tool button is pressed.
Detailed Description
Dialog for importing a 2D revolution profile (qSRA plugin)
Dialog for setting the input parameters required for the automatic segmentation of masonry walls
Definition at line 14 of file profileImportDlg.h.
Constructor & Destructor Documentation
ProfileImportDlg() [1/3]
ProfileImportDlg::ProfileImportDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 21 of file profileImportDlg.cpp.
References s_horizontal, s_joints, s_vertical, and saveSettings().
ProfileImportDlg() [2/3]
ProfileImportDlg::ProfileImportDlg (QWidget * parent = 0) explicit
Default constructor.
ProfileImportDlg() [3/3]
ProfileImportDlg::ProfileImportDlg (QWidget * parent = 0) explicit
Default constructor.
Member Function Documentation
absoluteHeightValues() [1/2]
bool ProfileImportDlg::absoluteHeightValues () const
Returns whether the profile heights are absolute or not (i.e. relative to the center)
Definition at line 53 of file profileImportDlg.cpp.
Referenced by qSRA::loadProfile().
absoluteHeightValues() [2/2]
bool ProfileImportDlg::absoluteHeightValues () const
Returns whether the profile heights are absolute or not (i.e. relative to the center)
browseFile [1/2]
void ProfileImportDlg::browseFile () protected slot
Called when the 'browse' tool button is pressed.
Definition at line 28 of file profileImportDlg.cpp.
References filename, getFilename(), and setDefaultFilename().
browseFile [2/2]
void ProfileImportDlg::browseFile () protected slot
Called when the 'browse' tool button is pressed.
getAxisDimension() [1/2]
int ProfileImportDlg::getAxisDimension () const
Definition at line 24 of file profileImportDlg.cpp.
Referenced by qSRA::loadProfile().
getAxisDimension() [2/2]
int ProfileImportDlg::getAxisDimension () const
Returns revolution axis dimension index.
Returns
0(X), 1(Y) or 2(Z).
getFilename() [1/2]
QString ProfileImportDlg::getFilename () const
Returns input filename (on completion)
Definition at line 49 of file profileImportDlg.cpp.
Referenced by browseFile(), and qSRA::loadProfile().
getFilename() [2/2]
QString ProfileImportDlg::getFilename () const
Returns input filename (on completion)
saveSettings
void ProfileImportDlg::saveSettings () protected slot
Save settings.
Definition at line 34 of file profileImportDlg.cpp.
References s_horizontal, s_joints, and s_vertical.
Referenced by ProfileImportDlg().
setDefaultFilename() [1/2]
void ProfileImportDlg::setDefaultFilename (QString filename)
Sets default filename.
Definition at line 45 of file profileImportDlg.cpp.
References filename.
Referenced by browseFile(), and qSRA::loadProfile().
setDefaultFilename() [2/2]
void ProfileImportDlg::setDefaultFilename (QString filename)
Sets default filename.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qMasonry/qAutoSeg/profileImportDlg.h
/root/ACloudViewer/plugins/core/Standard/qMasonry/qAutoSeg/profileImportDlg.cpp