ACloudViewer: qTreeIso Class Reference
qTreeIso Class Reference
TreeIso plugin.
#include <qTreeIso.h>
Protected Member Functions
void doAction ()
Slot called when associated ation is triggered.
void init_segs (const Parameters &parameters, QWidget *parent=nullptr)
void intermediate_segs (const Parameters &parameters, QWidget *parent=nullptr)
void final_segs (const Parameters &parameters, QWidget *parent=nullptr)
Protected Attributes
QAction * m_action
Associated action.
Detailed Description
TreeIso plugin.
Definition at line 41 of file qTreeIso.h.
Member Function Documentation
doAction()
void qTreeIso::doAction () protected
Slot called when associated ation is triggered.
Definition at line 70 of file qTreeIso.cpp.
final_segs()
void qTreeIso::final_segs (const Parameters & parameters, QWidget * parent = nullptr) protected
Definition at line 163 of file qTreeIso.cpp.
References TreeIso::Final_seg().
init_segs()
void qTreeIso::init_segs (const Parameters & parameters, QWidget * parent = nullptr) protected
Definition at line 112 of file qTreeIso.cpp.
References TreeIso::Init_seg().
intermediate_segs()
void qTreeIso::intermediate_segs (const Parameters & parameters, QWidget * parent = nullptr) protected
Definition at line 136 of file qTreeIso.cpp.
References TreeIso::Intermediate_seg().
Member Data Documentation
m_action
QAction* qTreeIso::m_action protected
Associated action.
Definition at line 85 of file qTreeIso.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qTreeIso/include/qTreeIso.h
/root/ACloudViewer/plugins/core/Standard/qTreeIso/src/qTreeIso.cpp