ACloudViewer: MainWindow Class Reference
MainWindow Class Reference
#include <MainWindow.h>
Public Slots
void enablePickingOperation (QString message)
void cancelPreviousPickingOperation (bool aborted)
void doActionPerspectiveProjection ()
void doActionOrthogonalProjection ()
Signals
void exclusiveFullScreenToggled (bool exclusive)
Signal emitted when the exclusive full screen is toggled.
void translation (const CCVector3d &t)
Signal emitted when the selected object is translated by the user.
void rotation (const ccGLMatrixd &rotMat)
Signal emitted when the selected object is rotated by the user.
Public Member Functions
void setUiManager (QUIWidget *uiManager)
void saveGUIElementsPos ()
Saves position and state of all GUI elements.
void setAutoPickPivot (bool state)
void setOrthoView ()
void setPerspectiveView ()
void updateViewModePopUpMenu ()
ccBBox getSelectedEntityBbox ()
void updateFullScreenMenu (bool state)
void addToDBAuto (const QStringList &filenames, bool displayDialog=true)
void addToDB (const QStringList &filenames, QString fileFilter=QString(), bool displayDialog=true)
void initPlugins ()
Sets up the UI (menus and toolbars) based on loaded plugins.
void updatePropertiesView ()
Updates the 'Properties' view.
void doActionSaveViewportAsCamera ()
void onItemPicked (const PickedItem &pi) override
Inherited from ccPickingListener.
ccDBRoot * db ()
Returns real 'dbRoot' object.
int getRenderWindowCount () const
Returns the number of 3D views.
QMdiSubWindow * getMDISubWindow (QWidget *win)
Returns MDI area subwindow corresponding to a given 3D view.
QWidget * getActiveWindow () override
QWidget * getWindow (int index) const
void update3DViewsMenu ()
void spawnHistogramDialog (const std::vector< unsigned > &histoValues, double minVal, double maxVal, QString title, QString xAxisLabel) override
ccPickingHub * pickingHub () override
void toggleExclusiveFullScreen (bool state) override
void toggle3DView (bool state) override
void forceConsoleDisplay () override
Forces display of console widget.
ccHObject * dbRootObject () override
Returns DB root (as a ccHObject)
void refreshAll (bool only2D=false, bool forceRedraw=true) override
Redraws all GL windows that have the 'refresh' flag on.
void enableAll () override
Enables all windows.
void disableAll () override
Disables all windows.
void refreshSelected (bool only2D=false, bool forceRedraw=true) override
void refreshObject (ccHObject *obj, bool only2D=false, bool forceRedraw=true) override
void refreshObjects (ccHObject::Container objs, bool only2D=false, bool forceRedraw=true) override
void resetSelectedBBox () override
void removeFromDB (ccHObject *obj, bool autoDelete=true) override
Removes an entity from main db tree.
void setSelectedInDB (ccHObject *obj, bool selected) override
Selects or unselects an entity (in db tree)
void putObjectBackIntoDBTree (ccHObject *obj, const ccHObjectContext &context) override
Adds back object to DB tree.
QMainWindow * getMainWindow () override
Returns main window.
const ccHObject::Container & getSelectedEntities () const override
Returns currently selected entities ("read only")
ccHObjectContext removeObjectTemporarilyFromDBTree (ccHObject *obj) override
Removes object temporarily from DB tree.
ccColorScalesManager * getColorScalesManager () override
Returns color scale manager (unique instance)
void addToDB (ccHObject *obj, bool updateZoom=false, bool autoExpandDBTree=true, bool checkDimensions=false, bool autoRedraw=true) override
void registerOverlayDialog (ccOverlayDialog *dlg, Qt::Corner pos) override
Registers a MDI area 'overlay' dialog.
void unregisterOverlayDialog (ccOverlayDialog *dlg) override
Unregisters a MDI area 'overlay' dialog.
void updateOverlayDialogsPlacement () override
Forces the update of all registered MDI 'overlay' dialogs.
ccHObject * loadFile (QString filename, bool silent) override
Attempts to load a file.
void setView (CC_VIEW_ORIENTATION view) override
void dispToConsole (QString message, ConsoleMessageLevel level=STD_CONSOLE_MESSAGE) override
ccUniqueIDGenerator::Shared getUniqueIDGenerator () override
Returns the unique ID generator.
void addWidgetToQMdiArea (QWidget *widget) override
void increasePointSize () override
void decreasePointSize () override
void updateUI () override
void freezeUI (bool state) override
Freezes/unfreezes UI.
void zoomOnSelectedEntities () override
void zoomOnEntities (ccHObject *obj) override
void setGlobalZoom () override
Public Member Functions inherited from ecvMainAppInterface
virtual ~ecvMainAppInterface ()=default
bool haveSelection () const
Checks if we have any selections.
bool haveOneSelection () const
Checks if we have exactly one selection.
virtual void redrawAll (bool only2D=false, bool forceRedraw=true)
Public Member Functions inherited from ccPickingListener
virtual ~ccPickingListener ()=default
Static Public Member Functions
static void UpdateUI ()
Static shortcut to MainWindow::updateUI.
static MainWindow * TheInstance ()
Returns the unique instance of this object.
static QWidget * GetActiveRenderWindow ()
Static shortcut to MainWindow::getActiveWindow.
static QWidget * GetRenderWindow (const QString &title)
Returns a given GL sub-window (determined by its title)
static void GetRenderWindows (std::vector< QWidget * > &windows)
Returns all GL sub-windows.
static void DestroyInstance ()
Deletes current main window instance.
static void ChangeStyle (const QString &qssFile)
Public Attributes
bool m_FirstShow
Flag: first time the window is made visible.
Static Public Attributes
static bool s_autoSaveGuiElementPos = true
Protected Member Functions
MainWindow ()
~MainWindow () override
QMenu * createPopupMenu () override
Override to add custom actions to right-click menu on toolbars.
Additional Inherited Members
Public Types inherited from ecvMainAppInterface
enum ConsoleMessageLevel { STD_CONSOLE_MESSAGE = 0 , WRN_CONSOLE_MESSAGE = 1 , ERR_CONSOLE_MESSAGE = 2 }
Console message level (see dispToConsole)
Detailed Description
Definition at line 117 of file MainWindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow () protected
Definition at line 275 of file MainWindow.cpp.
References a, addToDB(), ecvPS::AutoPickRotationCenter(), ecvPS::AutoShowCenter(), ecvPS::DoNotRestoreWindowGeometry(), ecvApp, cvFindDataDockWidget::extractedObjectReady(), freezeUI(), ccTranslationManager::get(), ecvDisplayTools::GetCurrentScreen(), ccTranslationManager::populateMenu(), CVLog::Print(), refreshAll(), ecvLayoutManager::registerBottomDockWidget(), ecvLayoutManager::registerLeftSideToolBar(), ecvLayoutManager::registerRightSideDockWidget(), ecvShortcutDialog::restoreShortcutsFromQSettings(), ecvDisplayTools::ToggleCameraOrientationWidget(), updateUI(), and CVLog::Warning().
Referenced by TheInstance().
~MainWindow()
MainWindow::~MainWindow () override protected
Definition at line 545 of file MainWindow.cpp.
References cancelPreviousPickingOperation(), GetRenderWindows(), ecvDisplayTools::ReleaseInstance(), ecvConsole::ReleaseInstance(), ecvDisplayTools::SetSceneDB(), and ccDBRoot::unloadAll().
Member Function Documentation
addToDB() [1/2]
void MainWindow::addToDB (ccHObject * obj, bool updateZoom = false, bool autoExpandDBTree = true, bool checkDimensions = false, bool autoRedraw = true) override virtual
Implements ecvMainAppInterface.
Definition at line 2210 of file MainWindow.cpp.
References ccDBRoot::addElement(), ccHObject::applyGLTransformation_recursive(), ccGLMatrixTpl< T >::data(), ecvGlobalShiftManager::DIALOG_IF_NECESSARY, ccHObject::filterChildren(), Vector3Tpl< double >::fromArray(), ccHObject::getBB_recursive(), cloudViewer::BoundingBoxTpl< T >::getCenter(), ccHObject::getChild(), ccHObject::getChildrenNumber(), cloudViewer::BoundingBoxTpl< T >::getDiagNorm(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccObject::getName(), ccDBRoot::getRootEntity(), ecvGlobalShiftManager::Handle(), CV_TYPES::IMAGE, ccObject::isKindOf(), Vector3Tpl< Type >::norm2(), CV_TYPES::POINT_CLOUD, CVLog::PrintDebug(), refreshObject(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ecvDisplayTools::SetRedrawRecursive(), ccGLMatrixTpl< T >::setTranslation(), ccHObjectCaster::ToGenericPointCloud(), ccGLMatrixTpl< T >::toIdentity(), Tuple3Tpl< Type >::u, CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, Tuple3Tpl< Type >::z, and ecvDisplayTools::ZoomGlobal().
addToDB() [2/2]
void MainWindow::addToDB (const QStringList & filenames, QString fileFilter = QString(), bool displayDialog = true)
Definition at line 2152 of file MainWindow.cpp.
References ecvRecentFiles::addFilePath(), FileIOFilter::LoadParameters::alwaysDisplayLoadDialog, CC_FERR_CANCELED_BY_USER, CC_FERR_NO_ERROR, FileIOFilter::LoadParameters::coordinatesShift, FileIOFilter::LoadParameters::coordinatesShiftEnabled, ecvGlobalShiftManager::DIALOG_IF_NECESSARY, filename, ccHObject::filterChildren(), ecvOptions::Instance(), FileIOFilter::LoadFromFile(), ecvOptions::normalsDisplayedByDefault, FileIOFilter::LoadParameters::parentWidget, CV_TYPES::POINT_CLOUD, FileIOFilter::ResetSesionCounter(), result, and FileIOFilter::LoadParameters::shiftHandlingMode.
Referenced by addToDBAuto(), ecvFilterByLabelDlg::apply(), ecvPrimitiveFactoryDlg::createPrimitive(), doActionSaveViewportAsCamera(), ccGraphicalSegmentationTool::doExportSegmentationPolyline(), ecvApplication::event(), ccRasterizeTool::exportContourLines(), ccVolumeCalcTool::exportGridAsCloud(), ccTracePolylineTool::exportLine(), ecvMeasurementTool::exportMeasurement(), ccGraphicalTransformationTool::exportNewEntities(), ecvFilterTool::exportSlice(), ccPointListPickingDlg::exportToNewCloud(), ccPointListPickingDlg::exportToNewPolyline(), ccRasterizeTool::generateCloud(), ccRasterizeTool::generateMesh(), main(), MainWindow(), ccPointListPickingDlg::processPickedPoint(), and ccPlaneEditDlg::saveParamsAndAccept().
addToDBAuto()
void MainWindow::addToDBAuto (const QStringList & filenames, bool displayDialog = true)
Definition at line 2147 of file MainWindow.cpp.
References addToDB().
addWidgetToQMdiArea()
void MainWindow::addWidgetToQMdiArea (QWidget * widget) override virtual
Implements ecvMainAppInterface.
Definition at line 1911 of file MainWindow.cpp.
References getMDISubWindow(), and GetRenderWindow().
cancelPreviousPickingOperation
void MainWindow::cancelPreviousPickingOperation (bool aborted) slot
Definition at line 5013 of file MainWindow.cpp.
References ecvDisplayTools::DisplayNewMessage(), freezeUI(), ecvDisplayTools::LOWER_LEFT_MESSAGE, NO_PICKING_OPERATION, ccPointPairRegistrationDlg::pause(), PICKING_LEVEL_POINTS, PICKING_ROTATION_CENTER, ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::RemoveFromOwnDB(), ccPickingHub::removeListener(), s_currentPickingOperation, s_levelMarkersCloud, and ecvDisplayTools::SetRedrawRecursive().
Referenced by onItemPicked(), and ~MainWindow().
ChangeStyle()
void MainWindow::ChangeStyle (const QString & qssFile) static
Definition at line 1982 of file MainWindow.cpp.
References ecvApp.
Referenced by main().
createPopupMenu()
QMenu * MainWindow::createPopupMenu () override protected
Override to add custom actions to right-click menu on toolbars.
Definition at line 628 of file MainWindow.cpp.
db()
ccDBRoot* MainWindow::db () inline
Returns real 'dbRoot' object.
Definition at line 193 of file MainWindow.h.
Referenced by ecvFilterByLabelDlg::apply(), ccPointListPickingDlg::applyAndExit(), ccPointListPickingDlg::cancelAndExit(), and ccPointListPickingDlg::clearLastLabel().
dbRootObject()
ccHObject * MainWindow::dbRootObject () override virtual
Returns DB root (as a ccHObject)
Implements ecvMainAppInterface.
Definition at line 2027 of file MainWindow.cpp.
References ccDBRoot::getRootEntity().
Referenced by ccGraphicalSegmentationTool::doActionUseExistingPolyline().
decreasePointSize()
void MainWindow::decreasePointSize () override virtual
Implements ecvMainAppInterface.
Definition at line 4918 of file MainWindow.cpp.
References ecvDisplayTools::GetViewportParameters(), refreshAll(), and ecvDisplayTools::SetPointSize().
DestroyInstance()
void MainWindow::DestroyInstance () static
Deletes current main window instance.
Definition at line 2042 of file MainWindow.cpp.
References s_instance.
Referenced by main().
disableAll()
void MainWindow::disableAll () override virtual
Disables all windows.
Implements ecvMainAppInterface.
Definition at line 3319 of file MainWindow.cpp.
dispToConsole()
void MainWindow::dispToConsole (QString message, ConsoleMessageLevel level = STD_CONSOLE_MESSAGE) override virtual
! Prints a message to console **
Parameters
message message
Implements ecvMainAppInterface.
Definition at line 2062 of file MainWindow.cpp.
References ecvMainAppInterface::ERR_CONSOLE_MESSAGE, CVLog::Error(), CVLog::Print(), ecvMainAppInterface::STD_CONSOLE_MESSAGE, CVLog::Warning(), and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
doActionOrthogonalProjection
void MainWindow::doActionOrthogonalProjection () slot
Definition at line 4972 of file MainWindow.cpp.
References ecvDisplayTools::GetCurrentScreen(), ecvDisplayTools::SetOrthoProjection(), setOrthoView(), and updateViewModePopUpMenu().
doActionPerspectiveProjection
void MainWindow::doActionPerspectiveProjection () slot
Definition at line 4962 of file MainWindow.cpp.
References ecvDisplayTools::GetCurrentScreen(), ecvDisplayTools::SetPerspectiveProjection(), setPerspectiveView(), and updateViewModePopUpMenu().
doActionSaveViewportAsCamera()
void MainWindow::doActionSaveViewportAsCamera ()
Definition at line 2367 of file MainWindow.cpp.
References addToDB(), getActiveWindow(), ecvDisplayTools::GetViewportParameters(), s_viewportIndex, and cc2DViewportObject::setParameters().
Referenced by ecvAnimationParamDlg::startAnimation().
enableAll()
void MainWindow::enableAll () override virtual
Enables all windows.
Implements ecvMainAppInterface.
Definition at line 3313 of file MainWindow.cpp.
enablePickingOperation
void MainWindow::enablePickingOperation (QString message) slot
Definition at line 4994 of file MainWindow.cpp.
References ccPickingHub::addListener(), ecvDisplayTools::DisplayNewMessage(), CVLog::Error(), freezeUI(), ecvDisplayTools::LOWER_LEFT_MESSAGE, and ecvDisplayTools::RedrawDisplay().
exclusiveFullScreenToggled
void MainWindow::exclusiveFullScreenToggled (bool exclusive) signal
Signal emitted when the exclusive full screen is toggled.
forceConsoleDisplay()
void MainWindow::forceConsoleDisplay () override virtual
Forces display of console widget.
Implements ecvMainAppInterface.
Definition at line 2019 of file MainWindow.cpp.
Referenced by ecvConsole::refresh().
freezeUI()
void MainWindow::freezeUI (bool state) override virtual
Freezes/unfreezes UI.
Parameters
state freeze state
Implements ecvMainAppInterface.
Definition at line 4624 of file MainWindow.cpp.
References ccPluginUIManager::additionalPluginToolbars(), and ccPluginUIManager::mainPluginToolbar().
Referenced by cancelPreviousPickingOperation(), enablePickingOperation(), and MainWindow().
GetActiveRenderWindow()
QWidget * MainWindow::GetActiveRenderWindow () static
Static shortcut to MainWindow::getActiveWindow.
Definition at line 1920 of file MainWindow.cpp.
References getActiveWindow(), and TheInstance().
getActiveWindow()
QWidget * MainWindow::getActiveWindow () override virtual
Implements ecvMainAppInterface.
Definition at line 1964 of file MainWindow.cpp.
Referenced by doActionSaveViewportAsCamera(), GetActiveRenderWindow(), and toggleExclusiveFullScreen().
getColorScalesManager()
ccColorScalesManager * MainWindow::getColorScalesManager () override virtual
Returns color scale manager (unique instance)
Implements ecvMainAppInterface.
Definition at line 3801 of file MainWindow.cpp.
References ccColorScalesManager::GetUniqueInstance().
getMainWindow()
QMainWindow* MainWindow::getMainWindow () inline override virtual
Returns main window.
Implements ecvMainAppInterface.
Definition at line 237 of file MainWindow.h.
getMDISubWindow()
QMdiSubWindow * MainWindow::getMDISubWindow (QWidget * win)
Returns MDI area subwindow corresponding to a given 3D view.
Definition at line 1857 of file MainWindow.cpp.
Referenced by addWidgetToQMdiArea().
GetRenderWindow()
QWidget * MainWindow::GetRenderWindow (const QString & title) static
Returns a given GL sub-window (determined by its title)
Parameters
title window title
Definition at line 1938 of file MainWindow.cpp.
References TheInstance().
Referenced by addWidgetToQMdiArea().
getRenderWindowCount()
int MainWindow::getRenderWindowCount () const
Returns the number of 3D views.
Definition at line 1853 of file MainWindow.cpp.
GetRenderWindows()
void MainWindow::GetRenderWindows (std::vector< QWidget * > & windows) static
Returns all GL sub-windows.
Parameters
[in,out] glWindows vector to store all sub-windows
Definition at line 1924 of file MainWindow.cpp.
References TheInstance().
Referenced by ~MainWindow().
getSelectedEntities()
const ccHObject::Container& MainWindow::getSelectedEntities () const inline override virtual
Returns currently selected entities ("read only")
Implements ecvMainAppInterface.
Definition at line 238 of file MainWindow.h.
Referenced by ccApplyTransformationDlg::initFromDipAndDipDir(), refreshSelected(), resetSelectedBBox(), ecvPrimitiveFactoryDlg::setCoordinateSystemBasedOnSelectedObject(), and ccPropertiesTreeDelegate::setEditorData().
getSelectedEntityBbox()
ccBBox MainWindow::getSelectedEntityBbox ()
Definition at line 3693 of file MainWindow.cpp.
References ccHObject::addChild(), ccHObject::DP_NONE, ccHObject::getChildrenNumber(), and ccHObject::getDisplayBB_recursive().
Referenced by zoomOnSelectedEntities().
getUniqueIDGenerator()
ccUniqueIDGenerator::Shared MainWindow::getUniqueIDGenerator () override virtual
Returns the unique ID generator.
Implements ecvMainAppInterface.
Definition at line 2077 of file MainWindow.cpp.
References ccObject::GetUniqueIDGenerator().
getWindow()
QWidget * MainWindow::getWindow (int index) const
Definition at line 1952 of file MainWindow.cpp.
increasePointSize()
void MainWindow::increasePointSize () override virtual
Implements ecvMainAppInterface.
Definition at line 4912 of file MainWindow.cpp.
References ecvDisplayTools::GetViewportParameters(), refreshAll(), and ecvDisplayTools::SetPointSize().
initPlugins()
void MainWindow::initPlugins ()
Sets up the UI (menus and toolbars) based on loaded plugins.
Definition at line 1545 of file MainWindow.cpp.
References ccPluginUIManager::actionShowMainPluginToolbar(), ccPluginUIManager::actionShowPCLAlgorithmToolbar(), ccPluginUIManager::additionalPluginToolbars(), ccPluginUIManager::glPclToolbar(), ccPluginUIManager::init(), ccPluginUIManager::isPythonPluginToolbar(), ccPluginUIManager::mainPluginToolbar(), ccPluginUIManager::pclAlgorithmMenu(), ccPluginUIManager::pluginMenu(), CVLog::Print(), CVLog::PrintDebug(), ecvLayoutManager::registerRightSideToolBar(), and CVLog::Warning().
Referenced by main().
loadFile()
ccHObject * MainWindow::loadFile (QString filename, bool silent) override virtual
Attempts to load a file.
Implements ecvMainAppInterface.
Definition at line 4124 of file MainWindow.cpp.
References FileIOFilter::LoadParameters::alwaysDisplayLoadDialog, CC_FERR_NO_ERROR, filename, FileIOFilter::LoadFromFile(), ecvGlobalShiftManager::NO_DIALOG_AUTO_SHIFT, FileIOFilter::LoadParameters::parentWidget, result, and FileIOFilter::LoadParameters::shiftHandlingMode.
onItemPicked()
void MainWindow::onItemPicked (const PickedItem & pi) override virtual
Inherited from ccPickingListener.
Implements ccPickingListener.
Definition at line 5051 of file MainWindow.cpp.
References ccHObject::addChild(), cc2DLabel::addPickedPoint(), cloudViewer::PointCloudTpl< T >::addPoint(), ccGLMatrixTpl< T >::apply(), cancelPreviousPickingOperation(), CC_TOP_VIEW, Vector3Tpl< Type >::cross(), ccGLMatrixTpl< T >::data(), ecvGui::ParamStruct::displayedNumPrecision, ecvDisplayTools::DisplayNewMessage(), Vector3Tpl< Type >::dot(), ccPickingListener::PickedItem::entity, Vector3Tpl< double >::fromArray(), ecvDisplayTools::GetCurrentViewDir(), ecvDisplayTools::GetDisplayParameters(), ccDrawableObject::getGLTransformation(), cloudViewer::PointCloudTpl< T >::getPoint(), ecvDisplayTools::GetViewportParameters(), ecvMainAppInterface::haveOneSelection(), ecvDisplayTools::LOWER_LEFT_MESSAGE, Vector3Tpl< Type >::normalize(), ecvViewportParameters::objectCenteredView, ccPickingListener::PickedItem::P3D, ecvViewportParameters::perspectiveView, PICKING_LEVEL_POINTS, PICKING_ROTATION_CENTER, refreshSelected(), s_currentPickingOperation, s_levelEntity, s_levelMarkersCloud, cc2DLabel::setDisplayedIn2D(), ccObject::setName(), ecvDisplayTools::SetPivotPoint(), ccHObject::setRedrawFlagRecursive(), ccGraphicalTransformationTool::setRotationCenter(), ccGLMatrixTpl< T >::setTranslation(), ecvDisplayTools::SetView(), ccDrawableObject::setVisible(), cloudViewer::PointCloudTpl< T >::size(), ccOverlayDialog::started(), Tuple3Tpl< Type >::u, CVLog::Warning(), Tuple3Tpl< Type >::x, X, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
pickingHub()
ccPickingHub* MainWindow::pickingHub () inline override virtual
Reimplemented from ecvMainAppInterface.
Definition at line 215 of file MainWindow.h.
Referenced by ecvMeasurementTool::ecvMeasurementTool(), ecvMeasurementTool::onPointPickingRequested(), and ecvMeasurementTool::start().
putObjectBackIntoDBTree()
void MainWindow::putObjectBackIntoDBTree (ccHObject * obj, const ccHObjectContext & context) override virtual
Adds back object to DB tree.
This method should be called once modifications to the db tree are finished (see removeObjectTemporarilyFromDBTree).
Implements ecvMainAppInterface.
Definition at line 3758 of file MainWindow.cpp.
References ccHObject::addDependency(), ccDBRoot::addElement(), context, and ccHObject::notifyGeometryUpdate().
Referenced by ccGraphicalTransformationTool::apply(), ccLibAlgorithms::ApplyScaleMatchingAlgorithm(), ccEntityAction::clearProperty(), ccEntityAction::computeNormals(), and ccEntityAction::computeOctree().
refreshAll()
void MainWindow::refreshAll (bool only2D = false, bool forceRedraw = true) override virtual
Redraws all GL windows that have the 'refresh' flag on.
! Forces redraw of all GL windows **
Parameters
only2D whether to redraw everything (false) or only the 2D layer (true) See ccDrawableObject::prepareDisplayForRefresh.
only2D whether to redraw everything (false) or only the 2D layer (true)
Implements ecvMainAppInterface.
Definition at line 4391 of file MainWindow.cpp.
References ecvDisplayTools::RedrawDisplay().
Referenced by ccDBRoot::changeSelection(), decreasePointSize(), ccDBRoot::deleteSelectedEntities(), ccDBRoot::dropMimeData(), ccDBRoot::enableBubbleViewMode(), increasePointSize(), MainWindow(), ccDBRoot::setData(), ccDBRoot::toggleSelectedEntitiesProperty(), and ccDBRoot::unloadAll().
refreshObject()
void MainWindow::refreshObject (ccHObject * obj, bool only2D = false, bool forceRedraw = true) override virtual
Implements ecvMainAppInterface.
Definition at line 4407 of file MainWindow.cpp.
References ecvDisplayTools::RedrawDisplay(), ccHObject::setRedrawFlagRecursive(), and ecvDisplayTools::SetRedrawRecursive().
Referenced by addToDB().
refreshObjects()
void MainWindow::refreshObjects (ccHObject::Container objs, bool only2D = false, bool forceRedraw = true) override virtual
Implements ecvMainAppInterface.
Definition at line 4417 of file MainWindow.cpp.
References ecvDisplayTools::RedrawDisplay(), ccHObject::setRedrawFlagRecursive(), and ecvDisplayTools::SetRedrawRecursive().
refreshSelected()
void MainWindow::refreshSelected (bool only2D = false, bool forceRedraw = true) override virtual
Implements ecvMainAppInterface.
Definition at line 4396 of file MainWindow.cpp.
References getSelectedEntities(), ecvDisplayTools::RedrawDisplay(), ccHObject::setRedrawFlagRecursive(), and ecvDisplayTools::SetRedrawRecursive().
Referenced by onItemPicked().
registerOverlayDialog()
void MainWindow::registerOverlayDialog (ccOverlayDialog * dlg, Qt::Corner pos) override virtual
Registers a MDI area 'overlay' dialog.
Overlay dialogs are displayed in the central MDI area, above the 3D views. The position (pos) is defined relatively to the MDI area (as one of its 4 corners). And it is automatically updated when the main window is moved or resized. Registered dialogs are automatically released when CLOUDVIEWER stops.
Notes:
it may be necessary to call 'updateOverlayDialogsPlacement' after calling this method
it's a good idea to freeez the UI when the tool starts to avoid other overlay dialogs to appear (don't forget to unfreeze the UI afterwards)
Implements ecvMainAppInterface.
Definition at line 4080 of file MainWindow.cpp.
References ccOverlayDialog::shown().
removeFromDB()
void MainWindow::removeFromDB (ccHObject * obj, bool autoDelete = true) override virtual
Removes an entity from main db tree.
Object is automatically detached from its parent.
Parameters
obj entity
autoDelete automatically deletes object
Implements ecvMainAppInterface.
Definition at line 4602 of file MainWindow.cpp.
References ccHObject::getParent(), ccHObject::removeDependencyWith(), ccDBRoot::removeElement(), and ccHObject::removeFromRenderScreen().
removeObjectTemporarilyFromDBTree()
MainWindow::ccHObjectContext MainWindow::removeObjectTemporarilyFromDBTree (ccHObject * obj) override virtual
Removes object temporarily from DB tree.
This method must be called before any modification to the db tree
Warning
May change the set of currently selected entities
Implements ecvMainAppInterface.
Definition at line 3776 of file MainWindow.cpp.
References context, ccHObject::getDependencyFlagsWith(), ccHObject::getParent(), ccHObject::removeDependencyWith(), and ccDBRoot::removeElement().
Referenced by ccGraphicalTransformationTool::apply(), ccLibAlgorithms::ApplyScaleMatchingAlgorithm(), ccEntityAction::clearProperty(), ccEntityAction::computeNormals(), and ccEntityAction::computeOctree().
resetSelectedBBox()
void MainWindow::resetSelectedBBox () override virtual
Implements ecvMainAppInterface.
Definition at line 4429 of file MainWindow.cpp.
References getSelectedEntities(), ccHObject::getViewId(), and ecvDisplayTools::RemoveBB().
rotation
void MainWindow::rotation (const ccGLMatrixd & rotMat) signal
Signal emitted when the selected object is rotated by the user.
Parameters
rotMat rotation applied to current viewport (4x4 OpenGL matrix)
saveGUIElementsPos()
void MainWindow::saveGUIElementsPos ()
Saves position and state of all GUI elements.
Definition at line 5287 of file MainWindow.cpp.
References CVLog::Error(), and ecvLayoutManager::saveGUILayout().
setAutoPickPivot()
void MainWindow::setAutoPickPivot (bool state)
Definition at line 1824 of file MainWindow.cpp.
setGlobalZoom()
void MainWindow::setGlobalZoom () override virtual
Implements ecvMainAppInterface.
Definition at line 4667 of file MainWindow.cpp.
References ecvDisplayTools::GetCurrentScreen(), ecvDisplayTools::SetRedrawRecursive(), and ecvDisplayTools::ZoomGlobal().
setOrthoView()
void MainWindow::setOrthoView ()
Definition at line 1831 of file MainWindow.cpp.
References ecvDisplayTools::GetCurrentScreen(), and ecvDisplayTools::SetPerspectiveState().
Referenced by doActionOrthogonalProjection().
setPerspectiveView()
void MainWindow::setPerspectiveView ()
Definition at line 1842 of file MainWindow.cpp.
References ecvDisplayTools::GetCurrentScreen(), and ecvDisplayTools::SetPerspectiveState().
Referenced by doActionPerspectiveProjection().
setSelectedInDB()
void MainWindow::setSelectedInDB (ccHObject * obj, bool selected) override virtual
Selects or unselects an entity (in db tree)
Parameters
obj entity
selected whether entity should be selected or not
Implements ecvMainAppInterface.
Definition at line 4615 of file MainWindow.cpp.
References ccDBRoot::selectEntity(), and ccDBRoot::unselectEntity().
setUiManager()
void MainWindow::setUiManager (QUIWidget * uiManager)
Definition at line 2008 of file MainWindow.cpp.
Referenced by main().
setView()
void MainWindow::setView (CC_VIEW_ORIENTATION view) override virtual
Implements ecvMainAppInterface.
Definition at line 3719 of file MainWindow.cpp.
References ecvDisplayTools::SetView().
spawnHistogramDialog()
void MainWindow::spawnHistogramDialog (const std::vector< unsigned > & histoValues, double minVal, double maxVal, QString title, QString xAxisLabel) override virtual
Implements ecvMainAppInterface.
Definition at line 9358 of file MainWindow.cpp.
References ccHistogramWindow::fromBinArray(), ccHistogramWindow::refresh(), ccHistogramWindow::setAxisLabels(), ccHistogramWindow::setTitle(), and ccHistogramWindowDlg::window().
TheInstance()
MainWindow * MainWindow::TheInstance () static
Returns the unique instance of this object.
Definition at line 2037 of file MainWindow.cpp.
References MainWindow(), and s_instance.
Referenced by ecvFilterByLabelDlg::apply(), ccGraphicalTransformationTool::apply(), ccPointListPickingDlg::applyAndExit(), ccPointListPickingDlg::cancelAndExit(), ccDBRoot::changeSelection(), ccPointListPickingDlg::clearLastLabel(), ccDBRoot::deleteSelectedEntities(), ccGraphicalSegmentationTool::doActionUseExistingPolyline(), ccGraphicalSegmentationTool::doExportSegmentationPolyline(), ccDBRoot::dropMimeData(), ecvMeasurementTool::ecvMeasurementTool(), ccDBRoot::editLabelScalarValue(), ccDBRoot::enableBubbleViewMode(), ecvApplication::event(), ccRasterizeTool::exportContourLines(), ccVolumeCalcTool::exportGridAsCloud(), ccDBRoot::exportImages(), ccTracePolylineTool::exportLine(), ecvMeasurementTool::exportMeasurement(), ccGraphicalTransformationTool::exportNewEntities(), ecvFilterTool::exportSlice(), ccPointListPickingDlg::exportToNewCloud(), ccPointListPickingDlg::exportToNewPolyline(), ccDBRoot::gatherRecursiveInformation(), ccRasterizeTool::generateCloud(), ccRasterizeTool::generateMesh(), GetActiveRenderWindow(), GetRenderWindow(), GetRenderWindows(), ccApplyTransformationDlg::initFromDipAndDipDir(), main(), ecvMeasurementTool::onPointPickingRequested(), ccPointListPickingDlg::processPickedPoint(), ccPlaneEditDlg::saveParamsAndAccept(), ccDBRoot::selectByTypeAndName(), ccDBRoot::setData(), ccPropertiesTreeDelegate::setEditorData(), ecvMeasurementTool::start(), ccDBRoot::toggleSelectedEntitiesProperty(), ccDBRoot::unloadAll(), and UpdateUI().
toggle3DView()
void MainWindow::toggle3DView (bool state) override virtual
Implements ecvMainAppInterface.
Definition at line 3943 of file MainWindow.cpp.
References ecvDisplayTools::GetCurrentScreen(), and ecvDisplayTools::Toggle2Dviewer().
toggleExclusiveFullScreen()
void MainWindow::toggleExclusiveFullScreen (bool state) override virtual
Implements ecvMainAppInterface.
Definition at line 3881 of file MainWindow.cpp.
References ecvDisplayTools::DisplayNewMessage(), ecvDisplayTools::FULL_SCREEN_MESSAGE, getActiveWindow(), ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::SetRedrawRecursive(), and ecvDisplayTools::UPPER_CENTER_MESSAGE.
translation
void MainWindow::translation (const CCVector3d & t) signal
Signal emitted when the selected object is translated by the user.
unregisterOverlayDialog()
void MainWindow::unregisterOverlayDialog (ccOverlayDialog * dlg) override virtual
Unregisters a MDI area 'overlay' dialog.
Warning
Original overlay dialog object will be deleted (see QObject::deleteLater)
Implements ecvMainAppInterface.
Definition at line 4108 of file MainWindow.cpp.
update3DViewsMenu()
void MainWindow::update3DViewsMenu ()
Definition at line 1867 of file MainWindow.cpp.
updateFullScreenMenu()
void MainWindow::updateFullScreenMenu (bool state)
Definition at line 3959 of file MainWindow.cpp.
updateOverlayDialogsPlacement()
void MainWindow::updateOverlayDialogsPlacement () override virtual
Forces the update of all registered MDI 'overlay' dialogs.
Implements ecvMainAppInterface.
Definition at line 4118 of file MainWindow.cpp.
updatePropertiesView()
void MainWindow::updatePropertiesView ()
Updates the 'Properties' view.
Definition at line 4988 of file MainWindow.cpp.
References ccDBRoot::updatePropertiesView().
Referenced by ccPlaneEditDlg::saveParamsAndAccept(), and updateUI().
UpdateUI()
void MainWindow::UpdateUI () static
Static shortcut to MainWindow::updateUI.
Definition at line 5192 of file MainWindow.cpp.
References TheInstance(), and updateUI().
Referenced by ccComparisonDlg::updateDisplay().
updateUI()
void MainWindow::updateUI () override virtual
Updates UI (menu and properties browser) to reflect current selection state This method should be called whenever a change is made to any selected entity
Implements ecvMainAppInterface.
Definition at line 4982 of file MainWindow.cpp.
References updatePropertiesView().
Referenced by MainWindow(), and UpdateUI().
updateViewModePopUpMenu()
void MainWindow::updateViewModePopUpMenu ()
Definition at line 1888 of file MainWindow.cpp.
References ecvDisplayTools::GetCurrentScreen(), and ecvGenericDisplayTools::GetPerspectiveState().
Referenced by doActionOrthogonalProjection(), and doActionPerspectiveProjection().
zoomOnEntities()
void MainWindow::zoomOnEntities (ccHObject * obj) override virtual
Implements ecvMainAppInterface.
Definition at line 4655 of file MainWindow.cpp.
References ccHObject::getDisplayBB_recursive(), ccObject::getName(), cloudViewer::BoundingBoxTpl< T >::isValid(), ecvDisplayTools::UpdateConstellationCenterAndZoom(), and CVLog::Warning().
zoomOnSelectedEntities()
void MainWindow::zoomOnSelectedEntities () override virtual
Implements ecvMainAppInterface.
Definition at line 4646 of file MainWindow.cpp.
References getSelectedEntityBbox(), cloudViewer::BoundingBoxTpl< T >::isValid(), ecvDisplayTools::UpdateConstellationCenterAndZoom(), and CVLog::Warning().
Member Data Documentation
m_FirstShow
bool MainWindow::m_FirstShow
Flag: first time the window is made visible.
Definition at line 206 of file MainWindow.h.
s_autoSaveGuiElementPos
bool MainWindow::s_autoSaveGuiElementPos = true static
Definition at line 207 of file MainWindow.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/MainWindow.h
/root/ACloudViewer/app/MainWindow.cpp