ACloudViewer: cloudViewer::ReferenceCloud Class Reference
cloudViewer::ReferenceCloud Class Reference
A very simple point cloud (no point duplication)
#include <ReferenceCloud.h>
Public Member Functions
ReferenceCloud (GenericIndexedCloudPersist *associatedCloud)
Default constructor.
ReferenceCloud (const ReferenceCloud &refCloud)
Copy constructor.
~ReferenceCloud () override=default
Destructor.
unsigned size () const override
Returns the number of points.
void forEach (genericPointAction action) override
Fast iteration mechanism.
void getBoundingBox (CCVector3 &bbMin, CCVector3 &bbMax) override
Returns the cloud bounding box.
unsigned char testVisibility (const CCVector3 &P) const override
void placeIteratorAtBeginning () override
Sets the cloud iterator at the beginning.
const CCVector3 * getNextPoint () override
Returns the next point (relatively to the global iterator position)
bool enableScalarField () override
Enables the scalar field associated to the cloud.
bool isScalarFieldEnabled () const override
Returns true if the scalar field is enabled, false otherwise.
void setPointScalarValue (unsigned pointIndex, ScalarType value) override
Sets the ith point associated scalar value.
ScalarType getPointScalarValue (unsigned pointIndex) const override
Returns the ith point associated scalar value.
const CCVector3 * getPoint (unsigned index) const override
Returns the ith point.
void getPoint (unsigned index, CCVector3 &P) const override
Returns the ith point.
void getPoint (unsigned index, double P[3]) const override
const CCVector3 * getPointPersistentPtr (unsigned index) override
Returns the ith point as a persistent pointer.
virtual unsigned getPointGlobalIndex (unsigned localIndex) const
virtual const CCVector3 * getCurrentPointCoordinates () const
Returns the coordinates of the point pointed by the current element.
virtual unsigned getCurrentPointGlobalIndex () const
Returns the global index of the point pointed by the current element.
virtual ScalarType getCurrentPointScalarValue () const
Returns the current point associated scalar value.
virtual void setCurrentPointScalarValue (ScalarType value)
Sets the current point associated scalar value.
virtual void forwardIterator ()
Forwards the local element iterator.
virtual void clear (bool releaseMemory=false)
Clears the cloud.
virtual bool addPointIndex (unsigned globalIndex)
Point global index insertion mechanism.
virtual bool addPointIndex (unsigned firstIndex, unsigned lastIndex)
Point global index insertion mechanism (range)
virtual void setPointIndex (unsigned localIndex, unsigned globalIndex)
Sets global index for a given element.
virtual bool reserve (unsigned n)
Reserves some memory for hosting the point references.
virtual bool resize (unsigned n)
Presets the size of the vector used to store point references.
virtual unsigned capacity () const
Returns max capacity.
virtual void swap (unsigned i, unsigned j)
Swaps two point references.
virtual void removeCurrentPointGlobalIndex ()
Removes current element.
virtual void removePointGlobalIndex (unsigned localIndex)
Removes a given element.
virtual GenericIndexedCloudPersist * getAssociatedCloud ()
Returns the associated (source) cloud.
virtual const GenericIndexedCloudPersist * getAssociatedCloud () const
Returns the associated (source) cloud (const version)
virtual void setAssociatedCloud (GenericIndexedCloudPersist *cloud)
Sets the associated (source) cloud.
bool add (const ReferenceCloud &cloud)
Add another reference cloud.
void invalidateBoundingBox ()
Invalidates the bounding-box.
Public Member Functions inherited from cloudViewer::GenericIndexedCloudPersist
~GenericIndexedCloudPersist () override=default
Default destructor.
Public Member Functions inherited from cloudViewer::GenericIndexedCloud
~GenericIndexedCloud () override=default
Default destructor.
virtual bool normalsAvailable () const
Returns whether normals are available.
virtual const CCVector3 * getNormal (unsigned index) const
If per-point normals are available, returns the one at a specific index.
Public Member Functions inherited from cloudViewer::GenericCloud
GenericCloud ()=default
Default constructor.
virtual ~GenericCloud ()=default
Default destructor.
virtual bool hasPoints () const
Protected Types
using ReferencesContainer = std::vector< unsigned int >
Container of 3D point indexes.
Protected Attributes
ReferencesContainer m_theIndexes
Indexes of (some of) the associated cloud points.
std::atomic< unsigned > m_globalIterator
Iterator on the point references container.
BoundingBox m_bbox
Bounding-box.
GenericIndexedCloudPersist * m_theAssociatedCloud
Associated cloud.
std::mutex m_mutex
For concurrent access.
Additional Inherited Members
Public Types inherited from cloudViewer::GenericCloud
using genericPointAction = std::function< void(const CCVector3 &, ScalarType &)>
Generic function applied to a point (used by foreach)
Detailed Description
A very simple point cloud (no point duplication)
Implements the GenericIndexedCloudPersist interface. A simple point cloud that stores references to Generic3dPoint instances in a vector.
Partial thread safety for all methods that can change the size of the cloud or that change or rely on point ordering.
Definition at line 29 of file ReferenceCloud.h.
Member Typedef Documentation
ReferencesContainer
using cloudViewer::ReferenceCloud::ReferencesContainer = std::vector<unsigned int> protected
Container of 3D point indexes.
Definition at line 231 of file ReferenceCloud.h.
Constructor & Destructor Documentation
ReferenceCloud() [1/2]
ReferenceCloud::ReferenceCloud (GenericIndexedCloudPersist * associatedCloud) explicit
Default constructor.
Definition at line 15 of file ReferenceCloud.cpp.
ReferenceCloud() [2/2]
ReferenceCloud::ReferenceCloud (const ReferenceCloud & refCloud)
Copy constructor.
Definition at line 18 of file ReferenceCloud.cpp.
~ReferenceCloud()
cloudViewer::ReferenceCloud::~ReferenceCloud () override default
Destructor.
Member Function Documentation
add()
bool ReferenceCloud::add (const ReferenceCloud & cloud)
Add another reference cloud.
Warning
Both clouds should have the same reference cloud!
No verification for duplicates! Thread safe.
Definition at line 166 of file ReferenceCloud.cpp.
References invalidateBoundingBox(), m_mutex, m_theAssociatedCloud, m_theIndexes, and size().
Referenced by FastMarchingForFacetExtraction::addCellToCurrentFacet(), ccKdTreeForFacetExtraction::FuseCells(), and ccPolyline::operator+=().
addPointIndex() [1/2]
bool ReferenceCloud::addPointIndex (unsigned firstIndex, unsigned lastIndex) virtual
Point global index insertion mechanism (range)
Parameters
firstIndex first point global index of range
lastIndex last point global index of range (excluded)
Returns
false if not enough memory Thread safe.
Definition at line 98 of file ReferenceCloud.cpp.
References invalidateBoundingBox(), m_mutex, m_theIndexes, and size().
addPointIndex() [2/2]
bool ReferenceCloud::addPointIndex (unsigned globalIndex) virtual
Point global index insertion mechanism.
Parameters
globalIndex a point global index
Returns
false if not enough memory Thread safe.
Definition at line 84 of file ReferenceCloud.cpp.
References invalidateBoundingBox(), m_mutex, and m_theIndexes.
Referenced by ccPolyline::add(), qCanupo2DViewDialog::addOrSelectPoint(), ccGraphicalSegmentationTool::addPointToPolyline(), cloudViewer::CloudSamplingTools::applyNoiseFilterAtLevel(), cloudViewer::TrueKdTree::build(), ccPointPair::ccPointPair(), ccPolyline::ccPolyline(), ccTrace::ccTrace(), ccTracePolylineTool::ccTracePolylineTool(), ccPolyline::Circle(), ccMesh::cloneMesh(), ComputeCorePointDescriptor(), ComputeCorePointNormal(), cloudViewer::StatisticalTestingTools::computeLocalChi2DistAtLevel(), cloudViewer::DistanceComputationTools::computePoint2MeshDistancesWithOctree(), ccTopologyRelation::constructGraphic(), contourPoly(), contourPoly2(), ccRasterGrid::convertToCloud(), vtk2cc::ConvertToPolyline(), ccPolyline::createNewPolylinesFromSelection(), ccPointCloud::crop(), ccPointCloud::crop2D(), cloudViewer::GeometricalAnalysisTools::DetectSphereRobust(), qCSF::doAction(), ccGraphicalSegmentationTool::doActionUseExistingPolyline(), cloudViewer::DgmOctree::executeFunctionForAllCellsAtLevel(), cloudViewer::DgmOctree::executeFunctionForAllCellsStartingAtLevel(), cvSelectionExporter::exportFromSourceCloud(), ccPointListPickingDlg::exportToNewPolyline(), ccContourExtractor::ExtractConcaveHull2D(), ccContourExtractor::ExtractFlatContour(), ccTrace::finalizePath(), cloudViewer::DgmOctree::findPointNeighbourhood(), GrainsAsEllipsoids::fitEllipsoidToGrain(), ccRasterizeTool::generateContours(), G3Point::G3PointAction::getBorders(), GetConeProfile(), cloudViewer::DgmOctree::getPointsInCellByCellIndex(), cloudViewer::DgmOctree::getPointsInCellsWithSortedCellCodes(), ecvTools::GetPolylines(), ccAlignDlg::getSampledData(), ccAlignDlg::getSampledModel(), ccGenericPointCloud::getTheVisiblePoints(), ccRegistrationTools::ICP(), ccCompass::importLineations(), ccCompassImport::importLineations(), ccPolyline::initWith(), ProfileLoader::Load(), ObjFilter::loadFile(), SalomeHydroFilter::loadFile(), SinusxFilter::loadFile(), ccMesh::mergeDuplicatedVertices(), QVTKWidgetCustom::mouseMoveEvent(), ccTracePolylineTool::onItemPicked(), ccMesh::partialClone(), ccLineationTool::pointPicked(), ccNoteTool::pointPicked(), ccPinchNodeTool::pointPicked(), ccThicknessTool::pointPicked(), ccTracePolylineTool::polylineOverSampling(), CommandCrop2D::process(), CommandCSF::process(), masc::Tools::RandomSubset(), cloudViewer::ICPRegistrationTools::Register(), cloudViewer::CloudSamplingTools::resampleCloudSpatially(), qCanupo2DViewDialog::resetBoundary(), cloudViewer::ManualSegmentationTools::segment(), ccPolyline::smoothChaikin(), cloudViewer::CloudSamplingTools::sorFilter(), ccPolyline::split(), cloudViewer::TrueKdTree::split(), cloudViewer::CloudSamplingTools::subsampleCellAtLevel(), cloudViewer::CloudSamplingTools::subsampleCloudRandomly(), DistanceMapGenerationDlg::toggleOverlayGrid(), cloudViewer::CloudSamplingTools::UniformDownSample(), ccPointCloud::unroll(), GrainsAsEllipsoids::updateMeshAndLineSet(), and ccGraphicalSegmentationTool::updatePolyLine().
capacity()
virtual unsigned cloudViewer::ReferenceCloud::capacity () const inline virtual
Returns max capacity.
Definition at line 174 of file ReferenceCloud.h.
Referenced by ccPolyline::createNewPolylinesFromSelection(), ccRegistrationTools::ICP(), cloudViewer::CloudSamplingTools::resampleCloudSpatially(), and ccPointCloud::unroll().
clear()
void ReferenceCloud::clear (bool releaseMemory = false) virtual
Clears the cloud.
Thread safe.
Reimplemented in cloudViewer::Polyline.
Definition at line 26 of file ReferenceCloud.cpp.
References invalidateBoundingBox(), m_mutex, and m_theIndexes.
Referenced by ccTrace::calculateOptimumSearchRadius(), qCanupoProcess::Classify(), cloudViewer::Polyline::clear(), ComputeCorePointNormal(), cloudViewer::StatisticalTestingTools::computeLocalChi2DistAtLevel(), ccPointCloud::crop(), ccPointCloud::crop2D(), ccCompass::estimateStructureNormals(), cloudViewer::DgmOctree::executeFunctionForAllCellsStartingAtLevel(), cloudViewer::DgmOctree::getPointsInCell(), cloudViewer::DgmOctree::getPointsInCellByCellIndex(), cloudViewer::DgmOctree::getPointsInCellsWithSortedCellCodes(), ccGenericPointCloud::getTheVisiblePoints(), CommandExtractCCs::process(), masc::Tools::RandomSubset(), and FastMarchingForFacetExtraction::updateFlagsTable().
enableScalarField()
bool cloudViewer::ReferenceCloud::enableScalarField () inline override virtual
Enables the scalar field associated to the cloud.
If the scalar field structure is not yet initialized/allocated, this method gives the signal for its creation. Otherwise, if possible the structure size should be pre-reserved with the same number of elements as the point cloud.
Implements cloudViewer::GenericCloud.
Definition at line 58 of file ReferenceCloud.h.
forEach()
void ReferenceCloud::forEach (genericPointAction action) override virtual
Fast iteration mechanism.
Virtual method to apply a function to the whole cloud
Parameters
action the function to apply (see GenericCloud::genericPointAction)
Implements cloudViewer::GenericCloud.
Definition at line 133 of file ReferenceCloud.cpp.
References count, cloudViewer::GenericIndexedCloudPersist::getPointPersistentPtr(), cloudViewer::GenericCloud::getPointScalarValue(), m_theAssociatedCloud, m_theIndexes, cloudViewer::GenericCloud::setPointScalarValue(), and size().
forwardIterator()
virtual void cloudViewer::ReferenceCloud::forwardIterator () inline virtual
Forwards the local element iterator.
Definition at line 133 of file ReferenceCloud.h.
Referenced by ComparePointsAndTriangles(), cloudViewer::DgmOctree::extractCCs(), and cloudViewer::FastMarchingForPropagation::setPropagationTimingsAsDistances().
getAssociatedCloud() [1/2]
virtual GenericIndexedCloudPersist* cloudViewer::ReferenceCloud::getAssociatedCloud () inline virtual
Returns the associated (source) cloud.
Definition at line 206 of file ReferenceCloud.h.
Referenced by ccPolyline::add(), ccGraphicalSegmentationTool::addEntity(), qCanupo2DViewDialog::addOrSelectPoint(), ccGraphicalSegmentationTool::applySegmentation(), CanDetachCloud(), ccPolyline::ccPolyline(), ccTrace::ccTrace(), ccFacet::clone(), ccOctree::ComputeAverageColor(), ccOctree::ComputeAverageNorm(), ComputeCellGaussianFilter(), cloudViewer::ScalarFieldTools::computeCellGaussianFilter(), ComputeFacetExtensions(), cloudViewer::StatisticalTestingTools::computeLocalChi2DistAtLevel(), cloudViewer::ScalarFieldTools::computeMeanGradientOnPatch(), ComputeRobustAverageNorm(), ccTopologyRelation::constructGraphic(), ccPolyline::createNewPolylinesFromSelection(), ccGraphicalSegmentationTool::doActionUseExistingPolyline(), ccGraphicalSegmentationTool::doExportSegmentationPolyline(), masc::Classifier::evaluate(), ccRasterizeTool::exportContourLines(), qFacets::exportFacets(), cloudViewer::GeometricalAnalysisTools::FlagDuplicatePointsInACellAtLevel(), ccDBRoot::flags(), ccKdTreeForFacetExtraction::FuseCells(), ccRasterizeTool::generateContours(), cvContourTool::getOutput(), cloudViewer::DgmOctree::getPointsInCellByCellIndex(), ccGenericPointCloud::getTheVisiblePoints(), ccPolyline::IsCloudVerticesOfPolyline(), QVTKWidgetCustom::mouseMoveEvent(), QVTKWidgetCustom::mouseReleaseEvent(), ccPolyline::operator+=(), ccPointCloud::partialClone(), masc::Tools::RandomSubset(), ccPolyline::Rotate(), ccPolyline::Scale(), cloudViewer::ManualSegmentationTools::segmentMesh(), cloudViewer::TrueKdTree::split(), FastMarchingForFacetExtraction::step(), masc::Classifier::train(), ccPolyline::Transform(), and ccPolyline::Translate().
getAssociatedCloud() [2/2]
virtual const GenericIndexedCloudPersist* cloudViewer::ReferenceCloud::getAssociatedCloud () const inline virtual
Returns the associated (source) cloud (const version)
Definition at line 211 of file ReferenceCloud.h.
getBoundingBox()
void ReferenceCloud::getBoundingBox (CCVector3 & bbMin, CCVector3 & bbMax) override virtual
Returns the cloud bounding box.
Virtual method to request the cloud bounding box limits
Parameters
bbMin lower bounding-box limits (Xmin,Ymin,Zmin)
bbMax higher bounding-box limits (Xmax,Ymax,Zmax)
Implements cloudViewer::GenericCloud.
Definition at line 37 of file ReferenceCloud.cpp.
References cloudViewer::BoundingBoxTpl< T >::add(), cloudViewer::BoundingBoxTpl< T >::clear(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::BoundingBoxTpl< T >::isValid(), m_bbox, m_mutex, m_theAssociatedCloud, m_theIndexes, cloudViewer::BoundingBoxTpl< T >::maxCorner(), and cloudViewer::BoundingBoxTpl< T >::minCorner().
Referenced by ccPolyline::getOwnBB(), and cloudViewer::TrueKdTree::split().
getCurrentPointCoordinates()
const CCVector3 * ReferenceCloud::getCurrentPointCoordinates () const virtual
Returns the coordinates of the point pointed by the current element.
Returns a persistent pointer.
Definition at line 77 of file ReferenceCloud.cpp.
References cloudViewer::GenericIndexedCloudPersist::getPointPersistentPtr(), m_globalIterator, m_theAssociatedCloud, m_theIndexes, cloudViewer::GenericCloud::size(), and size().
getCurrentPointGlobalIndex()
virtual unsigned cloudViewer::ReferenceCloud::getCurrentPointGlobalIndex () const inline virtual
Returns the global index of the point pointed by the current element.
Definition at line 113 of file ReferenceCloud.h.
References size.
getCurrentPointScalarValue()
virtual ScalarType cloudViewer::ReferenceCloud::getCurrentPointScalarValue () const inline virtual
Returns the current point associated scalar value.
Definition at line 119 of file ReferenceCloud.h.
References size.
Referenced by ComparePointsAndTriangles().
getNextPoint()
const CCVector3* cloudViewer::ReferenceCloud::getNextPoint () inline override virtual
Returns the next point (relatively to the global iterator position)
Virtual method to handle the cloud global iterator. Global iterator position should be increased by one each time this method is called. Warning:
the returned object may not be persistent!
THIS METHOD MAY NOT BE COMPATIBLE WITH PARALLEL STRATEGIES (see the DgmOctree::executeFunctionForAllCellsAtLevel_MT and DgmOctree::executeFunctionForAllCellsAtStartingLevel_MT methods).
Returns
pointer on next point (or 0 if no more)
Implements cloudViewer::GenericCloud.
Definition at line 51 of file ReferenceCloud.h.
References size.
getPoint() [1/3]
const CCVector3* cloudViewer::ReferenceCloud::getPoint (unsigned index) const inline override virtual
Returns the ith point.
Virtual method to request a point with a specific index. WARNINGS:
the returned object may not be persistent!
THIS METHOD MAY NOT BE COMPATIBLE WITH PARALLEL STRATEGIES (see the DgmOctree::executeFunctionForAllCellsAtLevel_MT and DgmOctree::executeFunctionForAllCellsAtStartingLevel_MT methods). Consider the other version of getPoint instead or the GenericIndexedCloudPersist class.
Parameters
index of the requested point (between 0 and the cloud size minus 1)
Returns
the requested point (undefined behavior if index is invalid)
Implements cloudViewer::GenericIndexedCloud.
Definition at line 79 of file ReferenceCloud.h.
References size.
Referenced by qCanupo2DViewDialog::addOrSelectPoint(), cloudViewer::CloudSamplingTools::applyNoiseFilterAtLevel(), cloudViewer::CloudSamplingTools::applySORFilterAtLevel(), ccPolyline::ccPolyline(), cellSFInterpolator(), ComparePointsAndTriangles(), GeneralFilters::compute(), cloudViewer::GeometricalAnalysisTools::ComputeApproxPointsDensityInACellAtLevel(), ComputeCellGaussianFilter(), cloudViewer::ScalarFieldTools::computeCellGaussianFilter(), cloudViewer::DistanceComputationTools::computeCellHausdorffDistance(), cloudViewer::DistanceComputationTools::computeCellHausdorffDistanceWithLocalModel(), cloudViewer::DistanceComputationTools::computeCloud2PolylineEquation(), ccOctreeFrustumIntersector::computeFrustumIntersectionWithOctree(), cloudViewer::GeometricalAnalysisTools::ComputeGeomCharacteristicAtLevel(), ccPolyline::computeLength(), cloudViewer::StatisticalTestingTools::computeLocalChi2DistAtLevel(), cloudViewer::ScalarFieldTools::computeMeanGradientOnPatch(), ComputeMSTGraphAtLevel(), ccNormalVectors::ComputeNormsAtLevelWithLS(), ccNormalVectors::ComputeNormsAtLevelWithQuadric(), ccNormalVectors::ComputeNormsAtLevelWithTri(), ccCompass::convertToPointCloud(), ccPolyline::drawMeOnly(), ccPointPair::drawMeOnly(), PCLDisplayTools::drawWidgets(), ccAlignDlg::estimateDelta(), ccCompass::estimateStructureNormals(), ccCompass::fitPlaneToGeoObject(), cloudViewer::GeometricalAnalysisTools::FlagDuplicatePointsInACellAtLevel(), ccKdTreeForFacetExtraction::FuseCells(), qCanupo2DViewDialog::getClosestVertex(), ccPointPair::getDirection(), cc2smReader::getPclPolygon(), qCanupo2DViewDialog::moveSelectedPoint(), masc::ContextBasedFeature::prepare(), qCanupo2DViewDialog::removePoint(), ccPolyline::samplePoints(), DxfFilter::saveToFile(), SalomeHydroFilter::saveToFile(), SinusxFilter::saveToFile(), HeightProfileFilter::saveToFile(), MascaretFilter::saveToFile(), ccPolyline::split(), cloudViewer::TrueKdTree::split(), cloudViewer::CloudSamplingTools::subsampleCellAtLevel(), TagDuplicatedVertices(), ccMesh::TriangulateTwoPolylines(), qCanupo2DViewDialog::updateClassifierPath(), ccLineation::updateMetadata(), ccThickness::updateMetadata(), and DistanceMapGenerationDlg::updateMinAndMaxLimits().
getPoint() [2/3]
void cloudViewer::ReferenceCloud::getPoint (unsigned index, CCVector3 & P) const inline override virtual
Returns the ith point.
Virtual method to request a point with a specific index. Index must be valid (undefined behavior if index is invalid)
Parameters
index of the requested point (between 0 and the cloud size minus 1)
P output point
Implements cloudViewer::GenericIndexedCloud.
Definition at line 83 of file ReferenceCloud.h.
References size.
getPoint() [3/3]
void cloudViewer::ReferenceCloud::getPoint (unsigned index, double P[3]) const inline override virtual
Reimplemented from cloudViewer::GenericIndexedCloud.
Definition at line 87 of file ReferenceCloud.h.
References size.
getPointGlobalIndex()
virtual unsigned cloudViewer::ReferenceCloud::getPointGlobalIndex (unsigned localIndex) const inline virtual
Returns global index (i.e. relative to the associated cloud) of a given element
Parameters
localIndex local index (i.e. relative to the internal index container)
Definition at line 103 of file ReferenceCloud.h.
Referenced by qCanupo2DViewDialog::addOrSelectPoint(), cloudViewer::CloudSamplingTools::applyNoiseFilterAtLevel(), cloudViewer::CloudSamplingTools::applySORFilterAtLevel(), ccPointPair::ccPointPair(), ccTrace::ccTrace(), cellSFInterpolator(), qCanupoProcess::Classify(), ComparePointsAndTriangles(), ComputeAverageColor(), ccOctree::ComputeAverageNorm(), ComputeCellGaussianFilter(), cloudViewer::ScalarFieldTools::computeCellGaussianFilter(), cloudViewer::DistanceComputationTools::computeCellHausdorffDistance(), cloudViewer::DistanceComputationTools::computeCellHausdorffDistanceWithLocalModel(), ComputeCorePointDescriptor(), ccOctreeFrustumIntersector::computeFrustumIntersectionWithOctree(), cloudViewer::GeometricalAnalysisTools::ComputeGeomCharacteristicAtLevel(), cloudViewer::StatisticalTestingTools::computeLocalChi2DistAtLevel(), ComputeMathOpWithNearestNeighbor(), cloudViewer::ScalarFieldTools::computeMeanGradientOnPatch(), ComputeMSTGraphAtLevel(), ccNormalVectors::ComputeNormsAtLevelWithLS(), ccNormalVectors::ComputeNormsAtLevelWithQuadric(), ccNormalVectors::ComputeNormsAtLevelWithTri(), ComputeRobustAverageNorm(), ccKdTree::convertCellIndexToRandomColor(), ccPolyline::createNewPolylinesFromSelection(), ccGraphicalSegmentationTool::doActionUseExistingPolyline(), ccCompass::estimateStructureNormals(), masc::Classifier::evaluate(), cloudViewer::GeometricalAnalysisTools::FlagDuplicatePointsInACellAtLevel(), ccTrace::getPointNormal(), ccPointCloud::partialClone(), RefinePointClassif(), cloudViewer::ICPRegistrationTools::Register(), qCanupo2DViewDialog::removePoint(), cloudViewer::ManualSegmentationTools::segmentMesh(), cloudViewer::TrueKdTree::split(), cloudViewer::CloudSamplingTools::subsampleCellAtLevel(), TagDuplicatedVertices(), masc::Classifier::train(), ccPointCloud::unroll(), FastMarchingForFacetExtraction::updateFlagsTable(), and ccFastMarchingForNormsDirection::updateResolvedTable().
getPointPersistentPtr()
const CCVector3* cloudViewer::ReferenceCloud::getPointPersistentPtr (unsigned index) inline override virtual
Returns the ith point as a persistent pointer.
Virtual method to request a point with a specific index. WARNING: the returned object MUST be persistent in order to be compatible with parallel strategies!
Parameters
index of the requested point (between 0 and the cloud size minus 1)
Returns
the requested point (or 0 if index is invalid)
Implements cloudViewer::GenericIndexedCloudPersist.
Definition at line 93 of file ReferenceCloud.h.
References size.
Referenced by ComputeCellGaussianFilter(), cloudViewer::ScalarFieldTools::computeCellGaussianFilter(), cloudViewer::DistanceComputationTools::computeCloud2MeshDistanceWithOctree(), cloudViewer::GeometricalAnalysisTools::ComputeGeomCharacteristicAtLevel(), cloudViewer::StatisticalTestingTools::computeLocalChi2DistAtLevel(), cloudViewer::ScalarFieldTools::computeMeanGradientOnPatch(), ComputeMSTGraphAtLevel(), ComputeNeighborhood2MeshDistancesWithOctree(), ccNormalVectors::ComputeNormsAtLevelWithLS(), ccNormalVectors::ComputeNormsAtLevelWithQuadric(), ccNormalVectors::ComputeNormsAtLevelWithTri(), and TagDuplicatedVertices().
getPointScalarValue()
ScalarType cloudViewer::ReferenceCloud::getPointScalarValue (unsigned pointIndex) const inline override virtual
Returns the ith point associated scalar value.
Implements cloudViewer::GenericCloud.
Definition at line 72 of file ReferenceCloud.h.
References size.
Referenced by ComparePointsAndTriangles(), ComputeCellGaussianFilter(), cloudViewer::ScalarFieldTools::computeCellGaussianFilter(), cloudViewer::StatisticalTestingTools::computeLocalChi2DistAtLevel(), cloudViewer::ScalarFieldTools::computeMeanGradientOnPatch(), cloudViewer::DistanceComputationTools::diff(), and cloudViewer::GeometricalAnalysisTools::FlagDuplicatePointsInACellAtLevel().
invalidateBoundingBox()
void cloudViewer::ReferenceCloud::invalidateBoundingBox () inline
Invalidates the bounding-box.
Definition at line 227 of file ReferenceCloud.h.
Referenced by add(), addPointIndex(), ccCircle::applyGLTransformation(), ccPolyline::applyGLTransformation(), ccTrace::ccTrace(), clear(), ccRasterizeTool::exportContourLines(), ccTrace::finalizePath(), setAssociatedCloud(), and setPointIndex().
isScalarFieldEnabled()
bool cloudViewer::ReferenceCloud::isScalarFieldEnabled () const inline override virtual
Returns true if the scalar field is enabled, false otherwise.
Implements cloudViewer::GenericCloud.
Definition at line 62 of file ReferenceCloud.h.
placeIteratorAtBeginning()
void cloudViewer::ReferenceCloud::placeIteratorAtBeginning () inline override virtual
Sets the cloud iterator at the beginning.
Virtual method to handle the cloud global iterator
Implements cloudViewer::GenericCloud.
Definition at line 50 of file ReferenceCloud.h.
Referenced by ComparePointsAndTriangles(), cloudViewer::DgmOctree::extractCCs(), and cloudViewer::FastMarchingForPropagation::setPropagationTimingsAsDistances().
removeCurrentPointGlobalIndex()
virtual void cloudViewer::ReferenceCloud::removeCurrentPointGlobalIndex () inline virtual
Removes current element.
WARNING: this method changes the cloud size! Thread safe.
Definition at line 195 of file ReferenceCloud.h.
Referenced by ComparePointsAndTriangles().
removePointGlobalIndex()
void ReferenceCloud::removePointGlobalIndex (unsigned localIndex) virtual
Removes a given element.
WARNING: this method changes the cloud size! Thread safe.
Definition at line 146 of file ReferenceCloud.cpp.
References m_mutex, m_theIndexes, and size().
reserve()
bool ReferenceCloud::reserve (unsigned n) virtual
Reserves some memory for hosting the point references.
Parameters
n the number of points (references) Thread safe.
Definition at line 51 of file ReferenceCloud.cpp.
References m_mutex, and m_theIndexes.
Referenced by qCanupo2DViewDialog::addOrSelectPoint(), ccPolyline::ccPolyline(), ccTracePolylineTool::ccTracePolylineTool(), ccPolyline::Circle(), ccMesh::cloneMesh(), ComputeCorePointDescriptor(), cloudViewer::StatisticalTestingTools::computeLocalChi2DistAtLevel(), cloudViewer::DistanceComputationTools::computePoint2MeshDistancesWithOctree(), contourPoly(), contourPoly2(), ccRasterGrid::convertToCloud(), vtk2cc::ConvertToPolyline(), ccPolyline::createNewPolylinesFromSelection(), ccPointCloud::crop(), ccPointCloud::crop2D(), cloudViewer::GeometricalAnalysisTools::DetectSphereRobust(), qCSF::doAction(), ccGraphicalSegmentationTool::doActionUseExistingPolyline(), cloudViewer::DgmOctree::executeFunctionForAllCellsAtLevel(), cloudViewer::DgmOctree::executeFunctionForAllCellsStartingAtLevel(), cvSelectionExporter::exportFromSourceCloud(), ccPointListPickingDlg::exportToNewPolyline(), ccContourExtractor::ExtractConcaveHull2D(), ccContourExtractor::ExtractFlatContour(), ccRasterizeTool::generateContours(), GetConeProfile(), ecvTools::GetPolylines(), ccGenericPointCloud::getTheVisiblePoints(), ccRegistrationTools::ICP(), ProfileLoader::Load(), ObjFilter::loadFile(), SalomeHydroFilter::loadFile(), ccMesh::mergeDuplicatedVertices(), cloudViewer::CloudSamplingTools::noiseFilter(), ccTracePolylineTool::onItemPicked(), ccMesh::partialClone(), ccTracePolylineTool::polylineOverSampling(), CommandCSF::process(), masc::Tools::RandomSubset(), cloudViewer::ICPRegistrationTools::Register(), cloudViewer::CloudSamplingTools::resampleCloudSpatially(), qCanupo2DViewDialog::resetBoundary(), ccPolyline::smoothChaikin(), cloudViewer::CloudSamplingTools::sorFilter(), ccPolyline::split(), cloudViewer::TrueKdTree::split(), cloudViewer::CloudSamplingTools::subsampleCloudWithOctreeAtLevel(), cloudViewer::CloudSamplingTools::UniformDownSample(), and ccPointCloud::unroll().
resize()
bool ReferenceCloud::resize (unsigned n) virtual
Presets the size of the vector used to store point references.
Parameters
n the number of points (references) Thread safe.
Definition at line 64 of file ReferenceCloud.cpp.
References m_mutex, and m_theIndexes.
Referenced by ccGraphicalSegmentationTool::closePolyLine(), cloudViewer::DistanceComputationTools::computeCloud2CloudDistances(), ComputeCorePointDescriptor(), ccPolyline::createNewPolylinesFromSelection(), ccPointCloud::crop(), ccPointCloud::crop2D(), cloudViewer::GeometricalAnalysisTools::DetectSphereRobust(), qM3C2Tools::GuessBestParams(), ccRegistrationTools::ICP(), cloudViewer::CloudSamplingTools::noiseFilter(), cloudViewer::ICPRegistrationTools::Register(), qCanupo2DViewDialog::removePoint(), cloudViewer::CloudSamplingTools::resampleCloudSpatially(), cloudViewer::CloudSamplingTools::sorFilter(), FastMarchingForFacetExtraction::step(), cloudViewer::CloudSamplingTools::subsampleCloudRandomly(), and cloudViewer::CloudSamplingTools::UniformDownSample().
setAssociatedCloud()
void ReferenceCloud::setAssociatedCloud (GenericIndexedCloudPersist * cloud) virtual
Sets the associated (source) cloud.
Definition at line 161 of file ReferenceCloud.cpp.
References invalidateBoundingBox(), and m_theAssociatedCloud.
Referenced by ccPolyline::initWith().
setCurrentPointScalarValue()
virtual void cloudViewer::ReferenceCloud::setCurrentPointScalarValue (ScalarType value) inline virtual
Sets the current point associated scalar value.
Definition at line 126 of file ReferenceCloud.h.
References size.
Referenced by cloudViewer::DgmOctree::extractCCs(), and cloudViewer::FastMarchingForPropagation::setPropagationTimingsAsDistances().
setPointIndex()
void ReferenceCloud::setPointIndex (unsigned localIndex, unsigned globalIndex) virtual
Sets global index for a given element.
Parameters
localIndex local index
globalIndex global index
Definition at line 127 of file ReferenceCloud.cpp.
References invalidateBoundingBox(), m_theIndexes, and size().
Referenced by qCanupo2DViewDialog::addOrSelectPoint(), cloudViewer::DistanceComputationTools::computeCellHausdorffDistance(), cloudViewer::DistanceComputationTools::computeCellHausdorffDistanceWithLocalModel(), qM3C2Tools::GuessBestParams(), and qCanupo2DViewDialog::removePoint().
setPointScalarValue()
void cloudViewer::ReferenceCloud::setPointScalarValue (unsigned pointIndex, ScalarType value) inline override virtual
Sets the ith point associated scalar value.
Implements cloudViewer::GenericCloud.
Definition at line 66 of file ReferenceCloud.h.
References size.
Referenced by ComparePointsAndTriangles(), cloudViewer::DistanceComputationTools::computeApproxCloud2CloudDistance(), cloudViewer::GeometricalAnalysisTools::ComputeApproxPointsDensityInACellAtLevel(), cloudViewer::ScalarFieldTools::computeCellGaussianFilter(), cloudViewer::DistanceComputationTools::computeCellHausdorffDistance(), cloudViewer::DistanceComputationTools::computeCellHausdorffDistanceWithLocalModel(), cloudViewer::DistanceComputationTools::computeCloud2MeshDistancesWithOctree(), cloudViewer::DistanceComputationTools::computeCloud2MeshDistanceWithOctree(), cloudViewer::GeometricalAnalysisTools::ComputeGeomCharacteristicAtLevel(), cloudViewer::StatisticalTestingTools::computeLocalChi2DistAtLevel(), ComputeNeighborhood2MeshDistancesWithOctree(), ccKdTree::convertCellIndexToSF(), and ccKdTreeForFacetExtraction::FuseCells().
size()
unsigned cloudViewer::ReferenceCloud::size () const inline override virtual
Returns the number of points.
Virtual method to request the cloud size
Returns
the cloud size
Implements cloudViewer::GenericCloud.
Definition at line 41 of file ReferenceCloud.h.
Referenced by add(), ccRasterizeTool::addNewContour(), qCanupo2DViewDialog::addOrSelectPoint(), addPointIndex(), cloudViewer::CloudSamplingTools::applyNoiseFilterAtLevel(), ccGraphicalSegmentationTool::applySegmentation(), cloudViewer::CloudSamplingTools::applySORFilterAtLevel(), ccLineationTool::cancel(), ccPointPair::ccPointPair(), ccTrace::ccTrace(), cellSFInterpolator(), ccMesh::cloneMesh(), ccGraphicalSegmentationTool::closePolyLine(), ccTracePolylineTool::closePolyLine(), ccGraphicalSegmentationTool::closeRectangle(), ComparePointsAndTriangles(), GeneralFilters::compute(), NurbsCurveFitting::compute(), cloudViewer::DistanceComputationTools::computeApproxCloud2CloudDistance(), cloudViewer::GeometricalAnalysisTools::ComputeApproxPointsDensityInACellAtLevel(), ccOctree::ComputeAverageColor(), ComputeAverageColor(), ccOctree::ComputeAverageNorm(), ComputeCellGaussianFilter(), cloudViewer::ScalarFieldTools::computeCellGaussianFilter(), cloudViewer::DistanceComputationTools::computeCellHausdorffDistance(), cloudViewer::DistanceComputationTools::computeCellHausdorffDistanceWithLocalModel(), ComputeCellStats(), cloudViewer::DistanceComputationTools::computeCloud2MeshDistancesWithOctree(), cloudViewer::DistanceComputationTools::computeCloud2MeshDistanceWithOctree(), cloudViewer::DistanceComputationTools::computeCloud2PolylineEquation(), ComputeCorePointDescriptor(), ComputeCorePointNormal(), ccOctreeFrustumIntersector::computeFrustumIntersectionWithOctree(), cloudViewer::GeometricalAnalysisTools::ComputeGeomCharacteristicAtLevel(), ccPolyline::computeLength(), cloudViewer::StatisticalTestingTools::computeLocalChi2DistAtLevel(), cloudViewer::ScalarFieldTools::computeMeanGradientOnPatch(), ComputeMSTGraphAtLevel(), ComputeNeighborhood2MeshDistancesWithOctree(), ccNormalVectors::ComputeNormsAtLevelWithLS(), ccNormalVectors::ComputeNormsAtLevelWithQuadric(), ccNormalVectors::ComputeNormsAtLevelWithTri(), ComputeRobustAverageNorm(), DimensionalityScaleParamsComputer::computeScaleParams(), ccKdTree::convertCellIndexToRandomColor(), ccKdTree::convertCellIndexToSF(), ccRasterGrid::convertToCloud(), vtk2cc::ConvertToMultiPolylines(), ccCompass::convertToPointCloud(), ccPointPairRegistrationDlg::convertToSphereCenter(), qFacets::createFacets(), ccMesh::createNewMeshFromSelection(), ccPolyline::createNewPolylinesFromSelection(), ccCropTool::Crop(), ccPointCloud::crop(), ccPointCloud::crop2D(), ccAlignDlg::dataSamplingRateChanged(), DescendingLeafSizeComparison(), cloudViewer::GeometricalAnalysisTools::DetectSphereRobust(), ccGraphicalSegmentationTool::doActionUseExistingPolyline(), ccGraphicalSegmentationTool::doExportSegmentationPolyline(), ccPolyline::drawMeOnly(), ccPointPair::drawMeOnly(), PCLDisplayTools::drawWidgets(), ccAlignDlg::estimateDelta(), ccCompass::estimateStructureNormals(), masc::Classifier::evaluate(), cloudViewer::DgmOctree::extractCCs(), ccPropertiesTreeDelegate::fillWithPolyline(), ccPropertiesTreeDelegate::fillWithViewProperties(), ccTrace::fitPlane(), ccCompass::fitPlaneToGeoObject(), cloudViewer::GeometricalAnalysisTools::FlagDuplicatePointsInACellAtLevel(), forEach(), cloudViewer::AutoSegmentationTools::frontPropagationBasedSegmentation(), ccKdTreeForFacetExtraction::FuseCells(), ccRasterizeTool::generateContours(), qCanupo2DViewDialog::getClosestVertex(), getCurrentPointCoordinates(), ccPointPair::getDirection(), ccPolyline::getOwnBB(), cc2smReader::getPclPolygon(), ccGenericPointCloud::getTheVisiblePoints(), ccRegistrationTools::ICP(), ccFacet::IsEmpty(), ccAlignDlg::modelSamplingRateChanged(), qCanupo2DViewDialog::moveSelectedPoint(), cloudViewer::CloudSamplingTools::noiseFilter(), ccTrace::optimizePath(), ccPointCloud::partialClone(), ccLineationTool::pointPicked(), ccTraceTool::pointPicked(), ccTracePolylineTool::polylineOverSampling(), CommandSubsample::process(), CommandExtractCCs::process(), CommandCrop2D::process(), masc::Tools::RandomSubset(), cloudViewer::ICPRegistrationTools::Register(), qCanupo2DViewDialog::removePoint(), removePointGlobalIndex(), cloudViewer::CloudSamplingTools::resampleCellAtLevel(), cloudViewer::CloudSamplingTools::resampleCloudSpatially(), ccPolyline::samplePoints(), DxfFilter::saveToFile(), SalomeHydroFilter::saveToFile(), SinusxFilter::saveToFile(), HeightProfileFilter::saveToFile(), MascaretFilter::saveToFile(), ccPolyline::segmentCount(), cloudViewer::ManualSegmentationTools::segmentMesh(), setPointIndex(), cloudViewer::FastMarchingForPropagation::setPropagationTimingsAsDistances(), FastMarchingForFacetExtraction::setSeedCell(), ccPolyline::smoothChaikin(), cloudViewer::CloudSamplingTools::sorFilter(), ccPolyline::split(), cloudViewer::TrueKdTree::split(), FastMarchingForFacetExtraction::step(), cloudViewer::CloudSamplingTools::subsampleCellAtLevel(), TagDuplicatedVertices(), masc::Classifier::train(), ccMesh::TriangulateTwoPolylines(), ccPointCloud::unroll(), qCanupo2DViewDialog::updateClassifierPath(), FastMarchingForFacetExtraction::updateFlagsTable(), ccLineation::updateMetadata(), ccThickness::updateMetadata(), DistanceMapGenerationDlg::updateMinAndMaxLimits(), and ccFastMarchingForNormsDirection::updateResolvedTable().
swap()
virtual void cloudViewer::ReferenceCloud::swap (unsigned i, unsigned j) inline virtual
Swaps two point references.
the point references indexes should be smaller than the total number of "reserved" points (see ReferenceCloud::reserve).
Parameters
i the first point index
j the second point index Thread safe.
Definition at line 185 of file ReferenceCloud.h.
References std::swap().
Referenced by ComputeCorePointDescriptor(), and cloudViewer::CloudSamplingTools::subsampleCloudRandomly().
testVisibility()
unsigned char cloudViewer::ReferenceCloud::testVisibility (const CCVector3 & P) const inline override virtual
Returns a given point visibility state (relatively to a sensor for instance) Generic method to request a point visibility (should be overloaded if this functionality is required). The point visibility is such as defined in Daniel Girardeau-Montaut's PhD manuscript (see Chapter 2, section 2-3-3). In this case, a ground based laser sensor model should be used to determine it. This method is called before performing any point-to-cloud comparison. If the result is not POINT_VISIBLE, then the comparison won't be performed and the scalar field value associated to this point will be this visibility value.
Parameters
P the 3D point to test
Returns
visibility (default: POINT_VISIBLE)
Reimplemented from cloudViewer::GenericCloud.
Definition at line 46 of file ReferenceCloud.h.
Member Data Documentation
m_bbox
BoundingBox cloudViewer::ReferenceCloud::m_bbox protected
Bounding-box.
Definition at line 240 of file ReferenceCloud.h.
Referenced by getBoundingBox(), ccPolyline::GetCenter(), ccPolyline::GetMaxBound(), and ccPolyline::GetMinBound().
m_globalIterator
std::atomic<unsigned> cloudViewer::ReferenceCloud::m_globalIterator protected
Iterator on the point references container.
Definition at line 237 of file ReferenceCloud.h.
Referenced by getCurrentPointCoordinates().
m_mutex
std::mutex cloudViewer::ReferenceCloud::m_mutex protected
For concurrent access.
Definition at line 250 of file ReferenceCloud.h.
Referenced by add(), addPointIndex(), clear(), getBoundingBox(), removePointGlobalIndex(), reserve(), and resize().
m_theAssociatedCloud
GenericIndexedCloudPersist* cloudViewer::ReferenceCloud::m_theAssociatedCloud protected
Associated cloud.
The cloud from which references are referring to. WARNING: do not use the inner iterator as it is used to 'implement' the ReferenceCloud one.
Definition at line 247 of file ReferenceCloud.h.
Referenced by ccPolyline::add(), add(), ccCircle::ccCircle(), ccPolyline::computeLength(), ccPolyline::createNewPolylinesFromSelection(), forEach(), ccPolyline::GetAxisAlignedBoundingBox(), getBoundingBox(), getCurrentPointCoordinates(), ccPolyline::GetOrientedBoundingBox(), ccPolyline::initWith(), ccPolyline::operator+=(), setAssociatedCloud(), ccPolyline::setGlobalScale(), ccPolyline::setGlobalShift(), and ccPolyline::split().
m_theIndexes
ReferencesContainer cloudViewer::ReferenceCloud::m_theIndexes protected
Indexes of (some of) the associated cloud points.
Definition at line 234 of file ReferenceCloud.h.
Referenced by add(), addPointIndex(), clear(), forEach(), ccPolyline::GetAxisAlignedBoundingBox(), getBoundingBox(), getCurrentPointCoordinates(), ccPolyline::GetOrientedBoundingBox(), removePointGlobalIndex(), reserve(), resize(), and setPointIndex().
The documentation for this class was generated from the following files:
/root/ACloudViewer/core/include/ReferenceCloud.h
/root/ACloudViewer/core/src/ReferenceCloud.cpp