ACloudViewer: cvFindDataDockWidget Class Reference
cvFindDataDockWidget Class Reference
Dock widget for Find Data / Selection Properties panel.
#include <cvFindDataDockWidget.h>
Signals
void extractedObjectReady (ccHObject *obj)
Emitted when an extracted object is ready to be added to the scene.
void visibilityChanged (bool visible)
Emitted when the dock visibility changes.
Public Member Functions
cvFindDataDockWidget (QWidget *parent=nullptr)
~cvFindDataDockWidget () override
cvSelectionPropertiesWidget * selectionPropertiesWidget () const
Get the selection properties widget contained in this dock.
void configure (cvSelectionHighlighter *highlighter, cvViewSelectionManager *manager, ecvGenericVisualizer3D *visualizer)
Configure the dock with necessary components.
void updateSelection (const cvSelectionData &selectionData)
Update the selection display with new data.
void clearSelection ()
Clear the current selection display.
void refreshDataProducers ()
Refresh the data producer list. Call this when data sources change (e.g., after loading new data)
Protected Member Functions
void showEvent (QShowEvent *event) override
void hideEvent (QHideEvent *event) override
Detailed Description
Dock widget for Find Data / Selection Properties panel.
This widget provides a standalone dock panel for selection properties, similar to ParaView's Find Data panel. It can be shown/hidden independently of the selection tools state.
Layout follows ParaView's pattern:
Docked on the right side of the application
Contains cvSelectionPropertiesWidget with collapsible sections
Can be tabified with other dock widgets
Definition at line 36 of file cvFindDataDockWidget.h.
Constructor & Destructor Documentation
cvFindDataDockWidget()
cvFindDataDockWidget::cvFindDataDockWidget (QWidget * parent = nullptr) explicit
Definition at line 21 of file cvFindDataDockWidget.cpp.
References CVLog::PrintVerbose().
~cvFindDataDockWidget()
cvFindDataDockWidget::~cvFindDataDockWidget () override
Definition at line 39 of file cvFindDataDockWidget.cpp.
References CVLog::PrintVerbose().
Member Function Documentation
clearSelection()
void cvFindDataDockWidget::clearSelection ()
Clear the current selection display.
Definition at line 119 of file cvFindDataDockWidget.cpp.
References cvSelectionPropertiesWidget::clearSelection().
configure()
void cvFindDataDockWidget::configure (cvSelectionHighlighter * highlighter, cvViewSelectionManager * manager, ecvGenericVisualizer3D * visualizer)
Configure the dock with necessary components.
Parameters
highlighter The selection highlighter for visual feedback
manager The selection manager for coordinating selections
visualizer The 3D visualizer for rendering
Definition at line 77 of file cvFindDataDockWidget.cpp.
References cvSelectionPropertiesWidget::setHighlighter(), cvSelectionPropertiesWidget::setSelectionManager(), cvSelectionBase::setVisualizer(), and CVLog::Warning().
extractedObjectReady
void cvFindDataDockWidget::extractedObjectReady (ccHObject * obj) signal
Emitted when an extracted object is ready to be added to the scene.
Referenced by MainWindow::MainWindow().
hideEvent()
void cvFindDataDockWidget::hideEvent (QHideEvent * event) override protected
Definition at line 147 of file cvFindDataDockWidget.cpp.
References event, CVLog::PrintVerbose(), and visibilityChanged().
refreshDataProducers()
void cvFindDataDockWidget::refreshDataProducers ()
Refresh the data producer list. Call this when data sources change (e.g., after loading new data)
Definition at line 126 of file cvFindDataDockWidget.cpp.
References cvSelectionPropertiesWidget::refreshDataProducers().
selectionPropertiesWidget()
cvSelectionPropertiesWidget* cvFindDataDockWidget::selectionPropertiesWidget () const inline
Get the selection properties widget contained in this dock.
Definition at line 46 of file cvFindDataDockWidget.h.
showEvent()
void cvFindDataDockWidget::showEvent (QShowEvent * event) override protected
Definition at line 133 of file cvFindDataDockWidget.cpp.
References event, CVLog::PrintVerbose(), cvSelectionPropertiesWidget::refreshDataProducers(), and visibilityChanged().
updateSelection()
void cvFindDataDockWidget::updateSelection (const cvSelectionData & selectionData)
Update the selection display with new data.
Parameters
selectionData The new selection data to display
Definition at line 111 of file cvFindDataDockWidget.cpp.
References cvSelectionPropertiesWidget::updateSelection().
visibilityChanged
void cvFindDataDockWidget::visibilityChanged (bool visible) signal
Emitted when the dock visibility changes.
Referenced by hideEvent(), and showEvent().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvFindDataDockWidget.h
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvFindDataDockWidget.cpp