ACloudViewer: GLTexImage Class Reference
GLTexImage Class Reference
#include <GLTexImage.h>
Public Member Functions
virtual void DrawQuadUS (int scale)
virtual void DrawQuadDS (int scale)
virtual void DrawImage ()
virtual void TexConvertRGB ()
virtual void ZeroHistoMargin ()
virtual void SetImageSize (int width, int height)
virtual void InitTexture (int width, int height, int clamp_to_edge=1)
void InitTexture (int width, int height, int clamp_to_edge, GLuint format)
virtual void FillMargin (int marginx, int marginy)
void DrawScaledQuad (float scale)
int CopyToPBO (GLuint pbo, int width, int height, GLenum format=GL_RGBA)
void CopyFromPBO (GLuint pbo, int width, int height, GLenum format=GL_RGBA)
void FitRealTexViewPort ()
void DrawQuadMT8 ()
void DrawQuadMT4 ()
void DrawQuadReduction ()
void DrawQuadReduction (int w, int h)
void DrawMargin (int right, int bottom)
void DrawQuad ()
void FitTexViewPort ()
void ZeroHistoMargin (int hw, int hh)
int CheckTexture ()
void SaveToASCII (const char *path)
void AttachToFBO (int i)
void BindTex ()
operator GLuint ()
GLuint GetTexID ()
int GetImgPixelCount ()
int GetTexPixelCount ()
int GetImgWidth ()
int GetImgHeight ()
int GetTexWidth ()
int GetTexHeight ()
int GetDrawWidth ()
int GetDrawHeight ()
int IsTexPacked ()
GLTexImage ()
virtual ~GLTexImage ()
Static Public Member Functions
static void DetachFBO (int i)
static void UnbindTex ()
static void UnbindMultiTex (int n)
static void DrawQuad (float x1, float x2, float y1, float y2)
Static Public Member Functions inherited from GlobalUtil
static double CLOCK ()
static void StopTimer ()
static void StartTimer (const char *event)
static float GetElapsedTime ()
static void FitViewPort (int width, int height)
static void SetTextureParameter ()
static void SetTextureParameterUS ()
static void CheckErrorsGL (const char *location=NULL)
static bool CheckFramebufferStatus ()
static void SelectDisplay ()
static void InitGLParam (int NotTargetGL=0)
static void SetGLParam ()
static int CreateWindowEZ ()
static void CleanupOpenGL ()
static void SetDeviceParam (int argc, char **argv)
static int CreateWindowEZ (LiteWindow *window)
Protected Attributes
GLuint _texID
int _imgWidth
int _imgHeight
int _texWidth
int _texHeight
int _drawWidth
int _drawHeight
Additional Inherited Members
Static Public Attributes inherited from GlobalParam
static GLuint _texTarget = GL_TEXTURE_RECTANGLE_ARB
static GLuint _iTexFormat =GL_RGBA32F_ARB
static int _texMaxDim = 3200
static int _texMaxDimGL = 4096
static int _texMinDim = 16
static int _MemCapGPU = 0
static int _FitMemoryCap = 0
static int _verbose = 1
static int _timingS = 1
static int _timingO = 0
static int _timingL = 0
static int _usePackedTex = 1
static int _IsNvidia = 0
static int _KeepShaderLoop = 0
static int _UseCUDA = 0
static int _UseOpenCL = 0
static int _UseDynamicIndexing = 0
static int _debug = 0
static int _MaxFilterWidth = -1
static float _FilterWidthFactor = 4.0f
static float _OrientationWindowFactor = 2.0f
static float _DescriptorWindowFactor = 3.0f
static int _MaxOrientation = 2
static int _OrientationPack2 = 0
static int _ListGenGPU = 1
static int _ListGenSkipGPU = 6
static int _SupportNVFloat = 0
static int _SupportTextureRG = 0
static int _FullSupported = 1
static float _MaxFeaturePercent = 0.005f
static int _MaxLevelFeatureNum = 4096
static int _DescriptorPPR = 8
static int _DescriptorPPT = 16
static int _FeatureTexBlock = 4
static int _NarrowFeatureTex = 0
static int _SubpixelLocalization = 1
static int _ProcessOBO = 0
static int _TruncateMethod = 0
static int _PreciseBorder = 1
static int _UseSiftGPUEX = 0
static int _ForceTightPyramid = 0
static int _octave_min_default =0
static int _octave_num_default =-1
static int _InitPyramidWidth =0
static int _InitPyramidHeight =0
static int _PreProcessOnCPU = 1
static int _GoodOpenGL = -1
static int _FixedOrientation = 0
static int _LoweOrigin = 0
static int _ExitAfterSIFT = 0
static int _NormalizedSIFT = 1
static int _BinarySIFT = 0
static int _KeepExtremumSign = 0
static int _FeatureCountThreshold = -1
static int _KeyPointListForceLevel0 = 0
static int _DarknessAdaption = 0
static float _OrientationExtraFactor
static float _OrientationGaussianFactor = 1.5f
static float _MulitiOrientationThreshold = 0.8f
static int _WindowInitX = -1
static int _WindowInitY = -1
static const char * _WindowDisplay = NULL
static int _DeviceIndex = 0
Detailed Description
Definition at line 31 of file GLTexImage.h.
Constructor & Destructor Documentation
GLTexImage()
GLTexImage::GLTexImage ()
Definition at line 56 of file GLTexImage.cpp.
~GLTexImage()
GLTexImage::~GLTexImage () virtual
Definition at line 65 of file GLTexImage.cpp.
Member Function Documentation
AttachToFBO()
void GLTexImage::AttachToFBO (int i)
Definition at line 363 of file GLTexImage.cpp.
Referenced by PyramidNaive::ComputeGradient(), PyramidPacked::ComputeGradient(), PyramidNaive::DetectKeypointsEX(), PyramidPacked::DetectKeypointsEX(), PyramidGL::DownloadKeypoints(), ShaderMan::FilterImage(), PyramidGL::GenerateFeatureDisplayVBO(), PyramidNaive::GenerateFeatureListCPU(), PyramidPacked::GenerateFeatureListCPU(), PyramidGL::GenerateFeatureListTex(), PyramidPacked::GetFeatureOrientations(), SiftMatchGL::GetGuidedSiftMatch(), SiftMatchGL::GetSiftMatch(), PyramidGL::ReshapeFeatureListCPU(), PyramidGL::ResizeFeatureStorage(), ShaderMan::TextureCopy(), ShaderMan::TextureDownSample(), and ShaderMan::TextureUpSample().
BindTex()
void GLTexImage::BindTex ()
Definition at line 159 of file GLTexImage.cpp.
Referenced by PyramidNaive::ComputeGradient(), PyramidPacked::ComputeGradient(), PyramidNaive::DetectKeypointsEX(), PyramidPacked::DetectKeypointsEX(), ShaderMan::FilterImage(), PyramidGL::GenerateFeatureDisplayVBO(), PyramidNaive::GenerateFeatureListCPU(), PyramidPacked::GenerateFeatureListCPU(), PyramidGL::GenerateFeatureListTex(), PyramidGL::GetFeatureDescriptors(), PyramidNaive::GetFeatureOrientations(), SiftMatchGL::GetGuidedSiftMatch(), SiftMatchGL::GetSiftMatch(), PyramidNaive::GetSimplifiedOrientation(), PyramidPacked::GetSimplifiedOrientation(), PyramidGL::ReshapeFeatureListCPU(), SiftMatchGL::SetDescriptors(), SiftMatchGL::SetFeautreLocation(), ShaderMan::TextureCopy(), ShaderMan::TextureDownSample(), and ShaderMan::TextureUpSample().
CheckTexture()
int GLTexImage::CheckTexture ()
Definition at line 70 of file GLTexImage.cpp.
CopyFromPBO()
void GLTexImage::CopyFromPBO (GLuint pbo, int width, int height, GLenum format = GL_RGBA)
Definition at line 1245 of file GLTexImage.cpp.
References GlobalParam::_texTarget, GlobalUtil::CheckErrorsGL(), format, height, max(), and width.
CopyToPBO()
int GLTexImage::CopyToPBO (GLuint pbo, int width, int height, GLenum format = GL_RGBA)
Definition at line 1187 of file GLTexImage.cpp.
References format, height, NULL, and width.
DetachFBO()
void GLTexImage::DetachFBO (int i) static
Definition at line 368 of file GLTexImage.cpp.
Referenced by PyramidPacked::ComputeGradient(), PyramidNaive::DetectKeypointsEX(), PyramidPacked::DetectKeypointsEX(), ShaderMan::FilterImage(), PyramidGL::ReshapeFeatureListCPU(), ShaderMan::TextureCopy(), ShaderMan::TextureDownSample(), and ShaderMan::TextureUpSample().
DrawImage()
void GLTexImage::DrawImage () virtual
Reimplemented in GLTexPacked.
Definition at line 346 of file GLTexImage.cpp.
DrawMargin()
void GLTexImage::DrawMargin (int right, int bottom)
Definition at line 233 of file GLTexImage.cpp.
DrawQuad() [1/2]
void GLTexImage::DrawQuad ()
Definition at line 170 of file GLTexImage.cpp.
Referenced by PyramidGL::GenerateFeatureDisplayVBO(), and PyramidGL::GetFeatureDescriptors().
DrawQuad() [2/2]
void GLTexImage::DrawQuad (float x1, float x2, float y1, float y2) static
Definition at line 374 of file GLTexImage.cpp.
Referenced by ShaderMan::FilterImage(), PyramidGL::GenerateFeatureDisplayVBO(), SiftMatchGL::GetGuidedSiftMatch(), SiftMatchGL::GetSiftMatch(), and ShaderMan::TextureCopy().
DrawQuadDS()
void GLTexImage::DrawQuadDS (int scale) virtual
Reimplemented in GLTexPacked.
Definition at line 401 of file GLTexImage.cpp.
Referenced by ShaderMan::TextureDownSample().
DrawQuadMT4()
void GLTexImage::DrawQuadMT4 ()
Definition at line 257 of file GLTexImage.cpp.
Referenced by PyramidNaive::ComputeGradient(), PyramidPacked::ComputeGradient(), PyramidNaive::DetectKeypointsEX(), and PyramidPacked::DetectKeypointsEX().
DrawQuadMT8()
void GLTexImage::DrawQuadMT8 ()
Definition at line 294 of file GLTexImage.cpp.
Referenced by PyramidNaive::DetectKeypointsEX(), and PyramidPacked::DetectKeypointsEX().
DrawQuadReduction() [1/2]
void GLTexImage::DrawQuadReduction ()
Definition at line 464 of file GLTexImage.cpp.
DrawQuadReduction() [2/2]
void GLTexImage::DrawQuadReduction (int w, int h)
Definition at line 428 of file GLTexImage.cpp.
DrawQuadUS()
void GLTexImage::DrawQuadUS (int scale) virtual
Reimplemented in GLTexPacked.
Definition at line 406 of file GLTexImage.cpp.
Referenced by ShaderMan::TextureUpSample().
DrawScaledQuad()
void GLTexImage::DrawScaledQuad (float scale)
Definition at line 411 of file GLTexImage.cpp.
FillMargin()
void GLTexImage::FillMargin (int marginx, int marginy) virtual
Reimplemented in GLTexPacked.
Definition at line 181 of file GLTexImage.cpp.
References GlobalUtil::FitViewPort(), min(), and ShaderMan::UseShaderMarginCopy().
Referenced by ShaderMan::FilterImage().
FitRealTexViewPort()
void GLTexImage::FitRealTexViewPort ()
Definition at line 358 of file GLTexImage.cpp.
References GlobalUtil::FitViewPort().
Referenced by PyramidGL::DownloadKeypoints().
FitTexViewPort()
void GLTexImage::FitTexViewPort ()
Definition at line 353 of file GLTexImage.cpp.
References GlobalUtil::FitViewPort().
Referenced by PyramidNaive::BuildPyramid(), PyramidPacked::BuildPyramid(), PyramidNaive::ComputeGradient(), PyramidPacked::ComputeGradient(), PyramidNaive::DetectKeypointsEX(), PyramidPacked::DetectKeypointsEX(), ShaderMan::FilterImage(), PyramidGL::GenerateFeatureDisplayVBO(), SiftMatchGL::GetGuidedSiftMatch(), SiftMatchGL::GetSiftMatch(), PyramidGL::ReshapeFeatureListCPU(), ShaderMan::TextureCopy(), ShaderMan::TextureDownSample(), and ShaderMan::TextureUpSample().
GetDrawHeight()
int GLTexImage::GetDrawHeight () inline
Definition at line 84 of file GLTexImage.h.
References _drawHeight.
Referenced by PyramidPacked::GenerateFeatureListCPU(), and PyramidGL::ResizeFeatureStorage().
GetDrawWidth()
int GLTexImage::GetDrawWidth () inline
Definition at line 83 of file GLTexImage.h.
References _drawWidth.
Referenced by PyramidPacked::GenerateFeatureListCPU(), and PyramidGL::ResizeFeatureStorage().
GetImgHeight()
int GLTexImage::GetImgHeight () inline
Definition at line 80 of file GLTexImage.h.
References _imgHeight.
Referenced by PyramidGL::DownloadKeypoints(), PyramidNaive::FitHistogramPyramid(), PyramidPacked::FitHistogramPyramid(), PyramidGL::GenerateFeatureDisplayVBO(), PyramidNaive::GenerateFeatureListCPU(), PyramidPacked::GenerateFeatureListCPU(), PyramidGL::GenerateFeatureListTex(), PyramidGL::ReshapeFeatureListCPU(), and PyramidGL::ResizeFeatureStorage().
GetImgPixelCount()
int GLTexImage::GetImgPixelCount () inline
Definition at line 77 of file GLTexImage.h.
References _imgHeight, and _imgWidth.
GetImgWidth()
int GLTexImage::GetImgWidth () inline
Definition at line 79 of file GLTexImage.h.
References _imgWidth.
Referenced by PyramidGL::DownloadKeypoints(), PyramidNaive::FitHistogramPyramid(), PyramidPacked::FitHistogramPyramid(), PyramidGL::GenerateFeatureDisplayVBO(), PyramidNaive::GenerateFeatureListCPU(), PyramidPacked::GenerateFeatureListCPU(), PyramidGL::GenerateFeatureListTex(), PyramidGL::ReshapeFeatureListCPU(), and PyramidGL::ResizeFeatureStorage().
GetTexHeight()
int GLTexImage::GetTexHeight () inline
Definition at line 82 of file GLTexImage.h.
References _texHeight.
Referenced by PyramidNaive::GenerateFeatureListCPU(), PyramidPacked::GenerateFeatureListCPU(), PyramidGL::GetFeatureDescriptors(), PyramidGL::ResizeFeatureStorage(), and PyramidGL::SetLevelFeatureNum().
GetTexID()
GLuint GLTexImage::GetTexID () inline
Definition at line 76 of file GLTexImage.h.
References _texID.
Referenced by PyramidGL::GetFeatureDescriptors(), PyramidNaive::GetSimplifiedOrientation(), and PyramidPacked::GetSimplifiedOrientation().
GetTexPixelCount()
int GLTexImage::GetTexPixelCount () inline
Definition at line 78 of file GLTexImage.h.
References _texHeight, and _texWidth.
GetTexWidth()
int GLTexImage::GetTexWidth () inline
Definition at line 81 of file GLTexImage.h.
References _texWidth.
Referenced by PyramidNaive::GenerateFeatureListCPU(), PyramidPacked::GenerateFeatureListCPU(), PyramidGL::ResizeFeatureStorage(), and PyramidGL::SetLevelFeatureNum().
InitTexture() [1/2]
void GLTexImage::InitTexture (int width, int height, int clamp_to_edge, GLuint format)
Definition at line 129 of file GLTexImage.cpp.
References format, height, NULL, and width.
InitTexture() [2/2]
void GLTexImage::InitTexture (int width, int height, int clamp_to_edge = 1) virtual
Reimplemented in GLTexPacked.
Definition at line 94 of file GLTexImage.cpp.
References height, NULL, and width.
Referenced by PyramidGL::ResizeFeatureStorage(), PyramidNaive::ResizePyramid(), PyramidPacked::ResizePyramid(), and PyramidGL::SetLevelFeatureNum().
IsTexPacked()
int GLTexImage::IsTexPacked () inline
Definition at line 86 of file GLTexImage.h.
References _drawWidth, and _imgWidth.
operator GLuint()
GLTexImage::operator GLuint () inline
Definition at line 75 of file GLTexImage.h.
References _texID.
SaveToASCII()
void GLTexImage::SaveToASCII (const char * path)
Definition at line 1212 of file GLTexImage.cpp.
SetImageSize()
void GLTexImage::SetImageSize (int width, int height) virtual
Reimplemented in GLTexPacked.
Definition at line 88 of file GLTexImage.cpp.
References height, and width.
Referenced by PyramidNaive::FitHistogramPyramid(), PyramidPacked::FitHistogramPyramid(), PyramidNaive::FitPyramid(), PyramidPacked::FitPyramid(), SiftMatchGL::GetGuidedSiftMatch(), SiftMatchGL::GetSiftMatch(), SiftMatchGL::SetDescriptors(), SiftMatchGL::SetFeautreLocation(), and PyramidGL::SetLevelFeatureNum().
TexConvertRGB()
void GLTexImage::TexConvertRGB () virtual
Reimplemented in GLTexPacked.
Definition at line 386 of file GLTexImage.cpp.
References ShaderMan::UnloadProgram(), and ShaderMan::UseShaderRGB2Gray().
UnbindMultiTex()
void GLTexImage::UnbindMultiTex (int n) static
Definition at line 724 of file GLTexImage.cpp.
Referenced by PyramidGL::CleanUpAfterSIFT(), PyramidNaive::ComputeGradient(), PyramidPacked::ComputeGradient(), PyramidNaive::DetectKeypointsEX(), PyramidPacked::DetectKeypointsEX(), PyramidGL::GetFeatureDescriptors(), PyramidNaive::GetFeatureOrientations(), PyramidPacked::GetFeatureOrientations(), SiftMatchGL::GetGuidedSiftMatch(), PyramidNaive::GetSimplifiedOrientation(), and PyramidPacked::GetSimplifiedOrientation().
UnbindTex()
void GLTexImage::UnbindTex () static
Definition at line 164 of file GLTexImage.cpp.
Referenced by ShaderMan::FilterImage(), PyramidNaive::GenerateFeatureListCPU(), PyramidPacked::GenerateFeatureListCPU(), PyramidGL::GenerateFeatureListTex(), PyramidGL::ReshapeFeatureListCPU(), SiftMatchGL::SetDescriptors(), SiftMatchGL::SetFeautreLocation(), ShaderMan::TextureCopy(), ShaderMan::TextureDownSample(), and ShaderMan::TextureUpSample().
ZeroHistoMargin() [1/2]
void GLTexImage::ZeroHistoMargin () virtual
Reimplemented in GLTexPacked.
Definition at line 196 of file GLTexImage.cpp.
Referenced by PyramidNaive::FitHistogramPyramid(), and PyramidPacked::FitHistogramPyramid().
ZeroHistoMargin() [2/2]
void GLTexImage::ZeroHistoMargin (int hw, int hh)
Definition at line 201 of file GLTexImage.cpp.
References GlobalUtil::FitViewPort(), height, ShaderMan::UseShaderZeroPass(), and width.
Member Data Documentation
_drawHeight
int GLTexImage::_drawHeight protected
Definition at line 40 of file GLTexImage.h.
Referenced by GetDrawHeight().
_drawWidth
int GLTexImage::_drawWidth protected
Definition at line 39 of file GLTexImage.h.
Referenced by GetDrawWidth(), and IsTexPacked().
_imgHeight
int GLTexImage::_imgHeight protected
Definition at line 36 of file GLTexImage.h.
Referenced by GetImgHeight(), and GetImgPixelCount().
_imgWidth
int GLTexImage::_imgWidth protected
Definition at line 35 of file GLTexImage.h.
Referenced by GetImgPixelCount(), GetImgWidth(), and IsTexPacked().
_texHeight
int GLTexImage::_texHeight protected
Definition at line 38 of file GLTexImage.h.
Referenced by GetTexHeight(), and GetTexPixelCount().
_texID
GLuint GLTexImage::_texID protected
Definition at line 34 of file GLTexImage.h.
Referenced by GetTexID(), and operator GLuint().
_texWidth
int GLTexImage::_texWidth protected
Definition at line 37 of file GLTexImage.h.
Referenced by GetTexPixelCount(), and GetTexWidth().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/GLTexImage.h
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/GLTexImage.cpp