ACloudViewer: PclAnnotationTool Class Reference
PclAnnotationTool Class Reference
#include <PclAnnotationTool.h>
Public Member Functions
PclAnnotationTool (AnnotationMode mode=AnnotationMode::BOUNDINGBOX)
PclAnnotationTool (ecvGenericVisualizer3D *viewer, AnnotationMode mode=AnnotationMode::BOUNDINGBOX)
virtual ~PclAnnotationTool () override
virtual void setVisualizer (ecvGenericVisualizer3D *viewer=nullptr) override
virtual bool loadClassesFromFile (const std::string &file) override
virtual void getAnnotationLabels (std::vector< std::string > &labelList) override
virtual bool getCurrentAnnotations (std::vector< int > &annos) const override
virtual void initAnnotationLabels (const std::vector< std::string > &labelList) override
virtual void toggleInteractor () override
virtual bool setInputCloud (ccPointCloud *pointCloud, int viewport=0) override
virtual void start () override
virtual void stop () override
virtual void intersectMode () override
virtual void unionMode () override
virtual void trimMode () override
virtual void resetMode () override
virtual void reset () override
clear state before load new cloud and annotation
virtual void clear () override
virtual void exportAnnotations () override
export annotations
virtual void changeAnnotationType (const std::string &type) override
virtual void selectExistedAnnotation (const std::string &type) override
virtual void updateCloud () override
virtual void showAnnotation () override
virtual void hideAnnotation () override
virtual void showOrigin () override
virtual void hideOrigin () override
virtual void removeAnnotation () override
Public Member Functions inherited from ecvGenericAnnotationTool
ecvGenericAnnotationTool (AnnotationMode mode=AnnotationMode::BOUNDINGBOX)
virtual ~ecvGenericAnnotationTool ()=default
AnnotationMode getAnnotationMode ()
Protected Slots
void pointPickingProcess (int index)
void areaPickingEventProcess (const std::vector< int > &new_selected_slice)
void pickedEventProcess (vtkActor *actor)
void keyboardEventProcess (const std::string &symKey)
Protected Member Functions
virtual void initialize (ecvGenericVisualizer3D *viewer) override
Protected Member Functions inherited from ecvGenericAnnotationTool
virtual bool buildUp ()
Builds primitive.
ccPointCloud * vertices ()
Returns vertices.
Additional Inherited Members
Public Types inherited from ecvGenericAnnotationTool
enum AnnotationMode { SEMANTICS , BOUNDINGBOX }
Default constructor.
Signals inherited from ecvGenericAnnotationTool
void objectPicked (bool isPicked)
Protected Attributes inherited from ecvGenericAnnotationTool
AnnotationMode m_annotationMode
ccPointCloud * m_associatedCloud
Detailed Description
Definition at line 32 of file PclAnnotationTool.h.
Constructor & Destructor Documentation
PclAnnotationTool() [1/2]
PclAnnotationTool::PclAnnotationTool (AnnotationMode mode = AnnotationMode::BOUNDINGBOX) explicit
Definition at line 47 of file PclAnnotationTool.cpp.
PclAnnotationTool() [2/2]
PclAnnotationTool::PclAnnotationTool (ecvGenericVisualizer3D * viewer, AnnotationMode mode = AnnotationMode::BOUNDINGBOX) explicit
Definition at line 50 of file PclAnnotationTool.cpp.
References initialize().
~PclAnnotationTool()
PclAnnotationTool::~PclAnnotationTool () override virtual
Definition at line 56 of file PclAnnotationTool.cpp.
Member Function Documentation
areaPickingEventProcess
void PclAnnotationTool::areaPickingEventProcess (const std::vector< int > & new_selected_slice) protected slot
Definition at line 325 of file PclAnnotationTool.cpp.
References a, ecvTools::DiffVector(), PclUtils::PCLVis::getRenderWindowInteractor(), ecvTools::IntersectionVector(), ecvTools::UnionVector(), and updateCloud().
Referenced by start(), and stop().
changeAnnotationType()
void PclAnnotationTool::changeAnnotationType (const std::string & type) override virtual
Implements ecvGenericAnnotationTool.
Definition at line 445 of file PclAnnotationTool.cpp.
References Annotation::getType(), ecvGenericAnnotationTool::m_annotationMode, CVLog::Print(), type, and CVLog::Warning().
clear()
void PclAnnotationTool::clear () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 661 of file PclAnnotationTool.cpp.
References PclUtils::PCLVis::getActorById(), and reset().
Referenced by stop().
exportAnnotations()
void PclAnnotationTool::exportAnnotations () override virtual
export annotations
Implements ecvGenericAnnotationTool.
Definition at line 520 of file PclAnnotationTool.cpp.
References ecvGenericAnnotationTool::m_annotationMode, CVLog::Print(), and CVTools::ToQString().
getAnnotationLabels()
void PclAnnotationTool::getAnnotationLabels (std::vector< std::string > & labelList) override virtual
Implements ecvGenericAnnotationTool.
Definition at line 149 of file PclAnnotationTool.cpp.
References Annotation::GetTypes().
getCurrentAnnotations()
bool PclAnnotationTool::getCurrentAnnotations (std::vector< int > & annos) const override virtual
Implements ecvGenericAnnotationTool.
Definition at line 161 of file PclAnnotationTool.cpp.
hideAnnotation()
void PclAnnotationTool::hideAnnotation () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 623 of file PclAnnotationTool.cpp.
Referenced by removeAnnotation().
hideOrigin()
void PclAnnotationTool::hideOrigin () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 643 of file PclAnnotationTool.cpp.
References PclUtils::PCLVis::getActorById().
initAnnotationLabels()
void PclAnnotationTool::initAnnotationLabels (const std::vector< std::string > & labelList) override virtual
Reimplemented from ecvGenericAnnotationTool.
Definition at line 97 of file PclAnnotationTool.cpp.
References ecvColor::LookUpTable::at(), Annotation::GetTypeIndex(), Annotation::GetTypes(), removeAnnotation(), size, updateCloud(), and CVLog::Warning().
initialize()
void PclAnnotationTool::initialize (ecvGenericVisualizer3D * viewer) override protected virtual
Implements ecvGenericAnnotationTool.
Definition at line 59 of file PclAnnotationTool.cpp.
References PclUtils::PCLVis::getRenderWindowInteractor(), ecvGenericAnnotationTool::m_annotationMode, resetMode(), and setVisualizer().
Referenced by PclAnnotationTool().
intersectMode()
void PclAnnotationTool::intersectMode () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 298 of file PclAnnotationTool.cpp.
keyboardEventProcess
void PclAnnotationTool::keyboardEventProcess (const std::string & symKey) protected slot
Definition at line 380 of file PclAnnotationTool.cpp.
References Annotation::getSlice(), Annotation::getType(), ecvGenericAnnotationTool::m_annotationMode, CVLog::Print(), removeAnnotation(), updateCloud(), and CVLog::Warning().
Referenced by start(), and stop().
loadClassesFromFile()
bool PclAnnotationTool::loadClassesFromFile (const std::string & file) override virtual
Implements ecvGenericAnnotationTool.
Definition at line 78 of file PclAnnotationTool.cpp.
Referenced by setInputCloud().
pickedEventProcess
void PclAnnotationTool::pickedEventProcess (vtkActor * actor) protected slot
Definition at line 360 of file PclAnnotationTool.cpp.
References PclUtils::PCLVis::getRenderWindowInteractor(), ecvGenericAnnotationTool::objectPicked(), Annotation::picked(), and Annotation::unpicked().
Referenced by start(), and stop().
pointPickingProcess
void PclAnnotationTool::pointPickingProcess (int index) protected slot
Definition at line 323 of file PclAnnotationTool.cpp.
removeAnnotation()
void PclAnnotationTool::removeAnnotation () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 690 of file PclAnnotationTool.cpp.
References hideAnnotation(), and updateCloud().
Referenced by initAnnotationLabels(), keyboardEventProcess(), and reset().
reset()
void PclAnnotationTool::reset (void) override virtual
clear state before load new cloud and annotation
Implements ecvGenericAnnotationTool.
Definition at line 655 of file PclAnnotationTool.cpp.
References removeAnnotation().
Referenced by clear().
resetMode()
void PclAnnotationTool::resetMode () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 316 of file PclAnnotationTool.cpp.
Referenced by initialize(), and stop().
selectExistedAnnotation()
void PclAnnotationTool::selectExistedAnnotation (const std::string & type) override virtual
Implements ecvGenericAnnotationTool.
Definition at line 480 of file PclAnnotationTool.cpp.
References ecvGenericAnnotationTool::m_annotationMode, type, updateCloud(), and CVLog::Warning().
setInputCloud()
bool PclAnnotationTool::setInputCloud (ccPointCloud * pointCloud, int viewport = 0) override virtual
Implements ecvGenericAnnotationTool.
Definition at line 165 of file PclAnnotationTool.cpp.
References FROM_PCL_CLOUD, CVTools::FromQString(), PclUtils::PCLVis::getActorById(), cc2smReader::getAsSM(), ccObject::getFullPath(), ccHObject::getViewId(), loadClassesFromFile(), ecvGenericAnnotationTool::m_annotationMode, CVLog::Print(), and CVTools::ToQString().
setVisualizer()
void PclAnnotationTool::setVisualizer (ecvGenericVisualizer3D * viewer = nullptr) override virtual
Implements ecvGenericAnnotationTool.
Definition at line 284 of file PclAnnotationTool.cpp.
References CVLog::Warning().
Referenced by initialize().
showAnnotation()
void PclAnnotationTool::showAnnotation () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 617 of file PclAnnotationTool.cpp.
showOrigin()
void PclAnnotationTool::showOrigin () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 629 of file PclAnnotationTool.cpp.
References PclUtils::PCLVis::getActorById().
start()
void PclAnnotationTool::start (void) override virtual
Implements ecvGenericAnnotationTool.
Definition at line 244 of file PclAnnotationTool.cpp.
References areaPickingEventProcess(), keyboardEventProcess(), ecvGenericAnnotationTool::m_annotationMode, pickedEventProcess(), PclUtils::PCLVis::setActorPickingEnabled(), PclUtils::PCLVis::setAreaPickingEnabled(), and PclUtils::PCLVis::setPointPickingEnabled().
stop()
void PclAnnotationTool::stop () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 262 of file PclAnnotationTool.cpp.
References areaPickingEventProcess(), clear(), keyboardEventProcess(), ecvGenericAnnotationTool::m_annotationMode, pickedEventProcess(), CVLog::Print(), resetMode(), PclUtils::PCLVis::setActorPickingEnabled(), PclUtils::PCLVis::setAreaPickingEnabled(), and PclUtils::PCLVis::setPointPickingEnabled().
toggleInteractor()
void PclAnnotationTool::toggleInteractor () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 143 of file PclAnnotationTool.cpp.
References PclUtils::PCLVis::toggleAreaPicking().
trimMode()
void PclAnnotationTool::trimMode () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 310 of file PclAnnotationTool.cpp.
unionMode()
void PclAnnotationTool::unionMode () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 304 of file PclAnnotationTool.cpp.
updateCloud()
void PclAnnotationTool::updateCloud () override virtual
Implements ecvGenericAnnotationTool.
Definition at line 603 of file PclAnnotationTool.cpp.
References ecvDisplayTools::UpdateScreen().
Referenced by areaPickingEventProcess(), initAnnotationLabels(), keyboardEventProcess(), removeAnnotation(), and selectExistedAnnotation().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/AnnotationTools/PclAnnotationTool.h
/root/ACloudViewer/libs/PCLEngine/Tools/AnnotationTools/PclAnnotationTool.cpp