ACloudViewer: DxfProfilesExportDlg Class Reference
DxfProfilesExportDlg Class Reference
Dialog for export multiple 2D profiles in a single DXF file (qSRA plugin)
#include <dxfProfilesExportDlg.h>
Public Member Functions
DxfProfilesExportDlg (QWidget *parent=0)
Default constructor.
QString getVertFilename () const
Returns vert. profiles output filename (on completion)
QString getHorizFilename () const
Returns horiz. profiles output filename (on completion)
Protected Slots
void browseVertFile ()
Called when the vert. 'browse' tool button is pressed.
void browseHorizFile ()
Called when the horiz. 'browse' tool button is pressed.
void acceptAndSaveSettings ()
Saves dialog state to persistent settings.
Protected Member Functions
void initFromPersistentSettings ()
Inits dialog state from persistent settings.
Detailed Description
Dialog for export multiple 2D profiles in a single DXF file (qSRA plugin)
Definition at line 13 of file dxfProfilesExportDlg.h.
Constructor & Destructor Documentation
DxfProfilesExportDlg()
DxfProfilesExportDlg::DxfProfilesExportDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 20 of file dxfProfilesExportDlg.cpp.
References acceptAndSaveSettings(), browseHorizFile(), browseVertFile(), and initFromPersistentSettings().
Member Function Documentation
acceptAndSaveSettings
void DxfProfilesExportDlg::acceptAndSaveSettings () protected slot
Saves dialog state to persistent settings.
Definition at line 95 of file dxfProfilesExportDlg.cpp.
Referenced by DxfProfilesExportDlg().
browseHorizFile
void DxfProfilesExportDlg::browseHorizFile () protected slot
Called when the horiz. 'browse' tool button is pressed.
Definition at line 137 of file dxfProfilesExportDlg.cpp.
References filename.
Referenced by DxfProfilesExportDlg().
browseVertFile
void DxfProfilesExportDlg::browseVertFile () protected slot
Called when the vert. 'browse' tool button is pressed.
Definition at line 120 of file dxfProfilesExportDlg.cpp.
References filename.
Referenced by DxfProfilesExportDlg().
getHorizFilename()
QString DxfProfilesExportDlg::getHorizFilename () const
Returns horiz. profiles output filename (on completion)
Definition at line 149 of file dxfProfilesExportDlg.cpp.
Referenced by DistanceMapGenerationDlg::exportProfilesAsDXF().
getVertFilename()
QString DxfProfilesExportDlg::getVertFilename () const
Returns vert. profiles output filename (on completion)
Definition at line 132 of file dxfProfilesExportDlg.cpp.
Referenced by DistanceMapGenerationDlg::exportProfilesAsDXF().
initFromPersistentSettings()
void DxfProfilesExportDlg::initFromPersistentSettings () protected
Inits dialog state from persistent settings.
Definition at line 34 of file dxfProfilesExportDlg.cpp.
References ecvFileUtils::defaultDocPath().
Referenced by DxfProfilesExportDlg().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qSRA/include/dxfProfilesExportDlg.h
/root/ACloudViewer/plugins/core/Standard/qSRA/src/dxfProfilesExportDlg.cpp