ACloudViewer: DistanceMapGenerationTool Class Reference
DistanceMapGenerationTool Class Reference
Distance map generation tool (surface of revolution)
#include <distanceMapGenerationTool.h>
Classes
class Map
"Distance" map
struct MapCell
"Distance" map cell
struct Measures
struct ProfileMetaData
Public Types
enum FillStrategyType { FILL_STRAT_MIN_DIST = 0 , FILL_STRAT_AVG_DIST = 1 , FILL_STRAT_MAX_DIST = 2 , INVALID_STRATEGY_TYPE = 255 }
Grid filling strategy.
enum EmptyCellFillOption { LEAVE_EMPTY = 0 , FILL_WITH_ZERO = 1 , FILL_INTERPOLATE = 2 }
Option for handling empty cells.
Static Public Member Functions
static bool GetPoylineMetaData (const ccPolyline *polyline, ProfileMetaData &data)
static void SetPoylineOrigin (ccPolyline *polyline, const CCVector3 &origin)
Sets the origin of a given polyline/profile.
static bool GetPoylineOrigin (const ccPolyline *polyline, CCVector3 &origin)
Returns the origin associated to a given polyline/profile.
static void SetPoylineRevolDim (ccPolyline *polyline, int revolDim)
Sets the revolution dimension of a given polyline.
static int GetPoylineRevolDim (const ccPolyline *polyline)
static void SetPoylineAxis (ccPolyline *polyline, const CCVector3 &axis)
Sets the revolution axis of a given polyline.
static bool GetPoylineAxis (const ccPolyline *polyline, CCVector3 &axis)
Returns the revolution axis associated to a given profile (polyline)
static void SetPolylineHeightShift (ccPolyline *polyline, PointCoordinateType heightShift)
Sets the profile 'height shift' (i.e. along the revolution axis)
static bool GetPolylineHeightShift (const ccPolyline *polyline, PointCoordinateType &heightShift)
Returns the profile 'height shift' (i.e. along the revolution axis)
static bool ComputeRadialDist (ccPointCloud *cloud, ccPolyline *profile, bool storeRadiiAsSF=false, ecvMainAppInterface *app=0)
Computes radial distance between cloud and a profile.
static QSharedPointer< Map > CreateMap (ccPointCloud *cloud, ccScalarField *sf, const ccGLMatrix &cloudToSurface, unsigned char revolutionAxisDim, double angStep_rad, double yStep, double yMin, double yMax, bool conical, bool counterclockwise, FillStrategyType fillStrategy, EmptyCellFillOption emptyCellfillOption, ecvMainAppInterface *app=0)
static ccMesh * ConvertConicalMapToMesh (const QSharedPointer< Map > &map, bool counterclockwise, QImage mapTexture=QImage())
Creates a conical projection (textured) mesh.
static double ConicalProjectN (double phi1, double phi2)
static double ConicalProject (double phi, double phi1, double n)
static bool ConvertCloudToCylindrical (ccPointCloud *cloud, const ccGLMatrix &cloudToSurface, unsigned char revolutionAxisDim, bool counterclockwise=false)
Converts a point cloud coordinates to "cylindrical" ones (in place)
static bool ConvertCloudToConical (ccPointCloud *cloud, const ccGLMatrix &cloudToSurface, unsigned char revolutionAxisDim, double latMin_rad, double latMax_rad, double conicalSpanRatio=1.0, bool counterclockwise=false)
Converts a point cloud coordinates to "conical" ones (in place)
static CCVector3 ProjectPointOnCone (double lon_rad, double lat_rad, double latMin_rad, double nProj, bool counterclockwise)
Projects a (longitude,r) couple to a 2D map.
static bool ComputeMinAndMaxLatitude_rad (ccPointCloud *cloud, double &minLat_rad, double &maxLat_rad, const ccGLMatrix &cloudToSurfaceOrigin, unsigned char revolutionAxisDim)
static bool SaveMapAsCSVMatrix (const QSharedPointer< Map > &map, QString filename, QString xUnit, QString yUnit, double xConversionFactor=1.0, double yConversionFactor=1.0, ecvMainAppInterface *app=0)
Saves a map as a CSV matrix.
static QImage ConvertMapToImage (const QSharedPointer< Map > &map, ccColorScale::Shared colorScale, unsigned colorScaleSteps=ccColorScale::MAX_STEPS)
Converts map to a QImage.
static ccPointCloud * ConvertMapToCloud (const QSharedPointer< Map > &map, ccPolyline *profile, double baseRadius=1.0, bool keepNaNPoints=true)
Converts map to a point cloud.
static ccMesh * ConvertProfileToMesh (ccPolyline *profile, const ccGLMatrix &cloudToProfile, bool counterclockwise, unsigned angularSteps=36, QImage mapTexture=QImage())
Converts profile to a (textured) mesh.
static bool ComputeSurfacesAndVolumes (const QSharedPointer< Map > &map, ccPolyline *profile, Measures &surfaces, Measures &volumes)
Detailed Description
Distance map generation tool (surface of revolution)
Definition at line 36 of file distanceMapGenerationTool.h.
Member Enumeration Documentation
EmptyCellFillOption
enum DistanceMapGenerationTool::EmptyCellFillOption
Option for handling empty cells.
Enumerator
LEAVE_EMPTY
FILL_WITH_ZERO
FILL_INTERPOLATE
Definition at line 185 of file distanceMapGenerationTool.h.
FillStrategyType
enum DistanceMapGenerationTool::FillStrategyType
Grid filling strategy.
Enumerator
FILL_STRAT_MIN_DIST
FILL_STRAT_AVG_DIST
FILL_STRAT_MAX_DIST
INVALID_STRATEGY_TYPE
Definition at line 177 of file distanceMapGenerationTool.h.
Member Function Documentation
ComputeMinAndMaxLatitude_rad()
bool DistanceMapGenerationTool::ComputeMinAndMaxLatitude_rad (ccPointCloud * cloud, double & minLat_rad, double & maxLat_rad, const ccGLMatrix & cloudToSurfaceOrigin, unsigned char revolutionAxisDim) static
Computes min and max latitudes of a point cloud (relatively to an axis and an 'origin')
Definition at line 380 of file distanceMapGenerationTool.cpp.
References ComputeLatitude_rad(), count, cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::PointCloudTpl< T >::size(), Tuple3Tpl< Type >::u, and X.
Referenced by DistanceMapGenerationDlg::updateMinAndMaxLimits().
ComputeRadialDist()
bool DistanceMapGenerationTool::ComputeRadialDist (ccPointCloud * cloud, ccPolyline * profile, bool storeRadiiAsSF = false, ecvMainAppInterface * app = 0) static
Computes radial distance between cloud and a profile.
Definition at line 219 of file distanceMapGenerationTool.cpp.
References ccPointCloud::addScalarField(), DistanceMapGenerationTool::ProfileMetaData::computeCloudToProfileOriginTrans(), ccScalarField::computeMinAndMax(), dist(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::PointCloudTpl< T >::getPoint(), GetPoylineMetaData(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), height, NAN_VALUE, nProgress, cloudViewer::NormalizedProgress::oneStep(), profile, RADIAL_DIST_SF_NAME, RADII_SF_NAME, DistanceMapGenerationTool::ProfileMetaData::revolDim, ccPointCloud::setCurrentDisplayedScalarField(), ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), cloudViewer::ScalarField::setValue(), ccDrawableObject::showSF(), cloudViewer::GenericCloud::size(), cloudViewer::PointCloudTpl< T >::size(), ecvProgressDialog::start(), Tuple3Tpl< Type >::u, cloudViewer::ScalarField::ValidValue(), Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
Referenced by qSRA::doComputeRadialDists().
ComputeSurfacesAndVolumes()
bool DistanceMapGenerationTool::ComputeSurfacesAndVolumes (const QSharedPointer< Map > & map, ccPolyline * profile, Measures & surfaces, Measures & volumes) static
Computes various surfaces and volumes (see Surfaces & Volumes structures) Warning: the 'positive' resp. 'negative' volumes coorespond to differences of volumes (i.e the volume that is exterior resp. interori to the theoretical profile). However, the 'positive' resp. 'negative' surfaces correspond to the surface of all the elements that have a positive resp. negative deviation.
Definition at line 977 of file distanceMapGenerationTool.cpp.
References DistanceMapGenerationTool::MapCell::count, fabs(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::PointCloudTpl< T >::getPoint(), GetPoylineRevolDim(), M_PI, DistanceMapGenerationTool::Measures::negative, DistanceMapGenerationTool::Measures::positive, profile, cloudViewer::GenericCloud::size(), cloudViewer::PointCloudTpl< T >::size(), std::swap(), DistanceMapGenerationTool::Measures::theoretical, DistanceMapGenerationTool::Measures::total, DistanceMapGenerationTool::MapCell::value, Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
Referenced by DistanceMapGenerationDlg::updateVolumes().
ConicalProject()
double DistanceMapGenerationTool::ConicalProject (double phi, double phi1, double n) static
Projects a given latitude with a Lambert conform conical projection with two intersecting parallels
Definition at line 435 of file distanceMapGenerationTool.cpp.
References M_PI_DIV_2, and M_PI_DIV_4.
Referenced by ConvertConicalMapToMesh(), and ProjectPointOnCone().
ConicalProjectN()
double DistanceMapGenerationTool::ConicalProjectN (double phi1, double phi2) static
Returns the constant 'n' factor of a Lambert conform conical projection with two intersecting parallels
Definition at line 423 of file distanceMapGenerationTool.cpp.
References fabs(), M_PI_DIV_2, and M_PI_DIV_4.
Referenced by ConvertCloudToConical(), ConvertConicalMapToMesh(), and DistanceMapGenerationDlg::toggleOverlayGrid().
ConvertCloudToConical()
bool DistanceMapGenerationTool::ConvertCloudToConical (ccPointCloud * cloud, const ccGLMatrix & cloudToSurface, unsigned char revolutionAxisDim, double latMin_rad, double latMax_rad, double conicalSpanRatio = 1.0, bool counterclockwise = false) static
Converts a point cloud coordinates to "conical" ones (in place)
See ProjectPointOnCone.
Definition at line 1203 of file distanceMapGenerationTool.cpp.
References ComputeLatitude_rad(), ConicalProjectN(), ccGenericPointCloud::deleteOctree(), ccGenericPointCloud::getOctree(), cloudViewer::PointCloudTpl< T >::getPoint(), M_PI, PC_ONE, ProjectPointOnCone(), ccPointCloud::refreshBB(), cloudViewer::PointCloudTpl< T >::size(), Tuple3Tpl< Type >::u, and X.
Referenced by DistanceMapGenerationDlg::loadOverlaySymbols().
ConvertCloudToCylindrical()
bool DistanceMapGenerationTool::ConvertCloudToCylindrical (ccPointCloud * cloud, const ccGLMatrix & cloudToSurface, unsigned char revolutionAxisDim, bool counterclockwise = false) static
Converts a point cloud coordinates to "cylindrical" ones (in place)
Definition at line 1156 of file distanceMapGenerationTool.cpp.
References ccGenericPointCloud::deleteOctree(), ccGenericPointCloud::getOctree(), cloudViewer::PointCloudTpl< T >::getPoint(), height, M_PI, PC_ONE, ccPointCloud::refreshBB(), cloudViewer::PointCloudTpl< T >::size(), Tuple3Tpl< Type >::u, Tuple3Tpl< Type >::x, X, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by DistanceMapGenerationDlg::loadOverlaySymbols().
ConvertConicalMapToMesh()
ccMesh * DistanceMapGenerationTool::ConvertConicalMapToMesh (const QSharedPointer< Map > & map, bool counterclockwise, QImage mapTexture = QImage()) static
Creates a conical projection (textured) mesh.
mapTexture.isNull()
Definition at line 838 of file distanceMapGenerationTool.cpp.
References ccHObject::addChild(), ccArray< Type, N, ComponentType >::addElement(), ccMaterialSet::addMaterial(), cloudViewer::PointCloudTpl< T >::addPoint(), ccMesh::addTriangle(), ccMesh::addTriangleMtlIndex(), ccMesh::addTriangleTexCoordIndexes(), ConicalProject(), ConicalProjectN(), M_PI, ccMesh::removePerTriangleTexCoordIndexes(), ccMesh::reserve(), ccPointCloud::reserve(), ccMesh::reservePerTriangleMtlIndexes(), ccMesh::reservePerTriangleTexCoordIndexes(), ccArray< Type, N, ComponentType >::reserveSafe(), ccMesh::setMaterialSet(), ccMesh::setTexCoordinatesTable(), ccDrawableObject::setVisible(), ccGenericMesh::showMaterials(), and TexCoords2D::ty.
Referenced by DistanceMapGenerationDlg::update().
ConvertMapToCloud()
ccPointCloud * DistanceMapGenerationTool::ConvertMapToCloud (const QSharedPointer< Map > & map, ccPolyline * profile, double baseRadius = 1.0, bool keepNaNPoints = true) static
Converts map to a point cloud.
Definition at line 1503 of file distanceMapGenerationTool.cpp.
References cloudViewer::ScalarField::addElement(), cloudViewer::PointCloudTpl< T >::addPoint(), ccPointCloud::addScalarField(), ccScalarField::computeMinAndMax(), count, DistanceMapGenerationTool::MapCell::count, cloudViewer::GenericIndexedCloud::getPoint(), GetPoylineMetaData(), DistanceMapGenerationTool::ProfileMetaData::heightShift, M_PI, NAN_VALUE, DistanceMapGenerationTool::ProfileMetaData::origin, profile, CCShareable::release(), ccPointCloud::reserve(), cloudViewer::ScalarField::reserveSafe(), ccPointCloud::resize(), DistanceMapGenerationTool::ProfileMetaData::revolDim, ccPointCloud::setCurrentDisplayedScalarField(), ccDrawableObject::showSF(), cloudViewer::GenericCloud::size(), cloudViewer::PointCloudTpl< T >::size(), Tuple3Tpl< Type >::u, DistanceMapGenerationTool::MapCell::value, Tuple3Tpl< Type >::x, X, and Tuple3Tpl< Type >::y.
Referenced by DistanceMapGenerationDlg::exportMapAsCloud().
ConvertMapToImage()
QImage DistanceMapGenerationTool::ConvertMapToImage (const QSharedPointer< Map > & map, ccColorScale::Shared colorScale, unsigned colorScaleSteps = ccColorScale::MAX_STEPS) static
Converts map to a QImage.
Definition at line 1596 of file distanceMapGenerationTool.cpp.
References ecvColor::RgbTpl< Type >::b, DistanceMapGenerationTool::MapCell::count, ecvColor::RgbTpl< Type >::g, image, ecvColor::lightGrey(), ecvColor::RgbTpl< Type >::r, and DistanceMapGenerationTool::MapCell::value.
Referenced by DistanceMapGenerationDlg::exportMapAsMesh(), and DistanceMapGenerationDlg::updateMapTexture().
ConvertProfileToMesh()
ccMesh * DistanceMapGenerationTool::ConvertProfileToMesh (ccPolyline * profile, const ccGLMatrix & cloudToProfile, bool counterclockwise, unsigned angularSteps = 36, QImage mapTexture = QImage()) static
Converts profile to a (textured) mesh.
Definition at line 1326 of file distanceMapGenerationTool.cpp.
References ccHObject::addChild(), ccArray< Type, N, ComponentType >::addElement(), ccMaterialSet::addMaterial(), cloudViewer::PointCloudTpl< T >::addPoint(), ccMesh::addTriangle(), ccMesh::addTriangleMtlIndex(), ccMesh::addTriangleTexCoordIndexes(), ccGLMatrixTpl< T >::apply(), cloudViewer::GenericIndexedCloud::getPoint(), GetPoylineMetaData(), ccGLMatrixTpl< T >::inverse(), M_PI, profile, ccHObject::removeChild(), ccMesh::removePerTriangleTexCoordIndexes(), ccMesh::reserve(), ccPointCloud::reserve(), ccMesh::reservePerTriangleMtlIndexes(), ccMesh::reservePerTriangleTexCoordIndexes(), ccArray< Type, N, ComponentType >::reserveSafe(), DistanceMapGenerationTool::ProfileMetaData::revolDim, ccMesh::setMaterialSet(), ccMesh::setTexCoordinatesTable(), ccDrawableObject::setVisible(), ccGenericMesh::showMaterials(), cloudViewer::GenericCloud::size(), TexCoords2D::ty, Tuple3Tpl< Type >::u, Tuple3Tpl< Type >::x, X, and Tuple3Tpl< Type >::y.
Referenced by DistanceMapGenerationDlg::exportMapAsMesh().
CreateMap()
QSharedPointer< DistanceMapGenerationTool::Map > DistanceMapGenerationTool::CreateMap (ccPointCloud * cloud, ccScalarField * sf, const ccGLMatrix & cloudToSurface, unsigned char revolutionAxisDim, double angStep_rad, double yStep, double yMin, double yMax, bool conical, bool counterclockwise, FillStrategyType fillStrategy, EmptyCellFillOption emptyCellfillOption, ecvMainAppInterface * app = 0) static
Projects a cloud (scalar field) on a revolution surface to generate a 2D map Projection can be either cylindrical or spherical. Warning: for cylindrical projection, the 2D map 'height' will be expressed relatively to the 'revolutionOrigin' and not the cloud's (implicit) origin.
Definition at line 447 of file distanceMapGenerationTool.cpp.
References cloudViewer::Delaunay2dMesh::buildMesh(), cloudViewer::utility::ceil(), ComputeLatitude_rad(), count, DistanceMapGenerationTool::MapCell::count, FILL_INTERPOLATE, FILL_STRAT_AVG_DIST, FILL_STRAT_MAX_DIST, FILL_STRAT_MIN_DIST, FILL_WITH_ZERO, cloudViewer::Delaunay2dMesh::getNextTriangleVertIndexes(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::ScalarField::getValue(), cloudViewer::VerticesIndexes::i, M_PI, max(), min(), cloudViewer::Delaunay2dMesh::placeIteratorAtBeginning(), cloudViewer::Delaunay2dMesh::size(), cloudViewer::PointCloudTpl< T >::size(), Tuple3Tpl< Type >::u, cloudViewer::Delaunay2dMesh::USE_ALL_POINTS, cloudViewer::ScalarField::ValidValue(), DistanceMapGenerationTool::MapCell::value, Vector2Tpl< Type >::x, X, and Vector2Tpl< Type >::y.
Referenced by DistanceMapGenerationDlg::updateMap().
GetPolylineHeightShift()
bool DistanceMapGenerationTool::GetPolylineHeightShift (const ccPolyline * polyline, PointCoordinateType & heightShift) static
Returns the profile 'height shift' (i.e. along the revolution axis)
Requires the right meta-data to be set (see SetPolylineHeightShift).
Returns
whether a height shift is defined or not
Definition at line 178 of file distanceMapGenerationTool.cpp.
References ccObject::getMetaData(), and PROFILE_HEIGHT_SHIFT_KEY.
Referenced by DistanceMapGenerationDlg::exportProfilesAsDXF(), and GetPoylineMetaData().
GetPoylineAxis()
bool DistanceMapGenerationTool::GetPoylineAxis (const ccPolyline * polyline, CCVector3 & axis) static
Returns the revolution axis associated to a given profile (polyline)
Requires the right meta-data to be set (see SetPoylineAxis).
Returns
whether an axis is defined or not
Definition at line 163 of file distanceMapGenerationTool.cpp.
References GetPolylineMetaVector(), and REVOLUTION_AXIS_KEY.
Referenced by GetPoylineMetaData().
GetPoylineMetaData()
bool DistanceMapGenerationTool::GetPoylineMetaData (const ccPolyline * polyline, ProfileMetaData & data) static
Returns the whole set of meta-data associated to a given polyline/profile
Returns
whether the profile is valid or not
Definition at line 194 of file distanceMapGenerationTool.cpp.
References DistanceMapGenerationTool::ProfileMetaData::axis, GetPolylineHeightShift(), GetPoylineAxis(), GetPoylineOrigin(), GetPoylineRevolDim(), DistanceMapGenerationTool::ProfileMetaData::hasAxis, DistanceMapGenerationTool::ProfileMetaData::heightShift, DistanceMapGenerationTool::ProfileMetaData::origin, and DistanceMapGenerationTool::ProfileMetaData::revolDim.
Referenced by ComputeRadialDist(), ConvertMapToCloud(), ConvertProfileToMesh(), DistanceMapGenerationDlg::DistanceMapGenerationDlg(), DistanceMapGenerationDlg::exportMapAsMesh(), DistanceMapGenerationDlg::loadOverlaySymbols(), DistanceMapGenerationDlg::updateMap(), DistanceMapGenerationDlg::updateMinAndMaxLimits(), and DistanceMapGenerationDlg::updateProfileOrigin().
GetPoylineOrigin()
bool DistanceMapGenerationTool::GetPoylineOrigin (const ccPolyline * polyline, CCVector3 & origin) static
Returns the origin associated to a given polyline/profile.
Requires the right meta-data to be set (see SetPoylineOrigin).
Returns
whether an origin is defined or not
Definition at line 152 of file distanceMapGenerationTool.cpp.
References GetPolylineMetaVector(), and PROFILE_ORIGIN_KEY.
Referenced by GetPoylineMetaData().
GetPoylineRevolDim()
int DistanceMapGenerationTool::GetPoylineRevolDim (const ccPolyline * polyline) static
Returns the revolution 'dimension' associated to a given profile (polyline) Requires the right meta-data to be set (see SetPoylineRevolDim).
Returns
0 (X), 1 (Y), 2 (Z) or -1 if no revolution dimension is defined
Definition at line 132 of file distanceMapGenerationTool.cpp.
References ccObject::getMetaData(), and REVOLUTION_AXIS_KEY.
Referenced by ComputeSurfacesAndVolumes(), and GetPoylineMetaData().
ProjectPointOnCone()
CCVector3 DistanceMapGenerationTool::ProjectPointOnCone (double lon_rad, double lat_rad, double latMin_rad, double nProj, bool counterclockwise) static
Projects a (longitude,r) couple to a 2D map.
For computing 'nProj' see ConicalProjectN.
Definition at line 823 of file distanceMapGenerationTool.cpp.
References ConicalProject(), and M_PI.
Referenced by ConvertCloudToConical(), and DistanceMapGenerationDlg::toggleOverlayGrid().
SaveMapAsCSVMatrix()
bool DistanceMapGenerationTool::SaveMapAsCSVMatrix (const QSharedPointer< Map > & map, QString filename, QString xUnit, QString yUnit, double xConversionFactor = 1.0, double yConversionFactor = 1.0, ecvMainAppInterface * app = 0) static
Saves a map as a CSV matrix.
Definition at line 1255 of file distanceMapGenerationTool.cpp.
References QtCompat::endl().
Referenced by DistanceMapGenerationDlg::exportMapAsGrid().
SetPolylineHeightShift()
void DistanceMapGenerationTool::SetPolylineHeightShift (ccPolyline * polyline, PointCoordinateType heightShift) static
Sets the profile 'height shift' (i.e. along the revolution axis)
This information is associated to a specific meta-data.
Definition at line 169 of file distanceMapGenerationTool.cpp.
References PROFILE_HEIGHT_SHIFT_KEY, and ccObject::setMetaData().
Referenced by GetConeProfile(), qSRA::loadProfile(), and DistanceMapGenerationDlg::updateProfileOrigin().
SetPoylineAxis()
void DistanceMapGenerationTool::SetPoylineAxis (ccPolyline * polyline, const CCVector3 & axis) static
Sets the revolution axis of a given polyline.
The revolution axis is associated to a specific meta-data.
Definition at line 158 of file distanceMapGenerationTool.cpp.
References REVOLUTION_AXIS_KEY, and SetPoylineMetaVector().
Referenced by GetConeProfile().
SetPoylineOrigin()
void DistanceMapGenerationTool::SetPoylineOrigin (ccPolyline * polyline, const CCVector3 & origin) static
Sets the origin of a given polyline/profile.
The revolution axis is associated to a specific meta-data.
Definition at line 147 of file distanceMapGenerationTool.cpp.
References PROFILE_ORIGIN_KEY, and SetPoylineMetaVector().
Referenced by GetConeProfile(), qSRA::loadProfile(), and DistanceMapGenerationDlg::updateProfileOrigin().
SetPoylineRevolDim()
void DistanceMapGenerationTool::SetPoylineRevolDim (ccPolyline * polyline, int revolDim) static
Sets the revolution dimension of a given polyline.
The revolution dimension is associated to a specific meta-data.
Definition at line 122 of file distanceMapGenerationTool.cpp.
References REVOLUTION_AXIS_KEY, and ccObject::setMetaData().
Referenced by GetConeProfile(), qSRA::loadProfile(), and DistanceMapGenerationDlg::updateProfileRevolDim().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qSRA/include/distanceMapGenerationTool.h
/root/ACloudViewer/plugins/core/Standard/qSRA/src/distanceMapGenerationTool.cpp