ACloudViewer: cloudViewer::visualization::rendering::CameraInteractorLogic Class Reference
cloudViewer::visualization::rendering::CameraInteractorLogic Class Reference
#include <CameraInteractorLogic.h>
Public Member Functions
CameraInteractorLogic (Camera *c, double min_far_plane)
void SetBoundingBox (const ccBBox &bounds) override
void Rotate (int dx, int dy) override
void RotateZ (int dx, int dy) override
Rotates about the forward axis of the matrix.
void Dolly (float dy, DragType type) override
void Dolly (float z_dist, Camera::Transform matrix_in) override
void Pan (int dx, int dy) override
void Zoom (int dy, DragType drag_type)
Sets camera field of view.
void RotateLocal (float angle_rad, const Eigen::Vector3f &axis)
void MoveLocal (const Eigen::Vector3f &v)
void RotateFly (int dx, int dy)
void StartMouseDrag () override
void ResetMouseDrag ()
void UpdateMouseDragUI () override
void EndMouseDrag () override
Public Member Functions inherited from cloudViewer::visualization::rendering::RotationInteractorLogic
RotationInteractorLogic (Camera *camera, double min_far_plane)
~RotationInteractorLogic ()
virtual void SetCenterOfRotation (const Eigen::Vector3f &center)
Public Member Functions inherited from cloudViewer::visualization::rendering::MatrixInteractorLogic
virtual ~MatrixInteractorLogic ()
void SetViewSize (int width, int height)
int GetViewWidth () const
int GetViewHeight () const
const ccBBox & GetBoundingBox () const
Eigen::Vector3f GetCenterOfRotation () const
void SetMouseDownInfo (const Camera::Transform &matrix, const Eigen::Vector3f &center_of_rotation)
const Camera::Transform & GetMatrix () const
virtual void RotateWorld (int dx, int dy, const Eigen::Vector3f &x_axis, const Eigen::Vector3f &y_axis)
virtual void RotateZWorld (int dx, int dy, const Eigen::Vector3f &forward)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::rendering::MatrixInteractorLogic
enum class DragType { MOUSE , WHEEL , TWO_FINGER }
Protected Member Functions inherited from cloudViewer::visualization::rendering::RotationInteractorLogic
Eigen::Vector3f CalcPanVectorWorld (int dx, int dy)
void UpdateCameraFarPlane ()
Protected Member Functions inherited from cloudViewer::visualization::rendering::MatrixInteractorLogic
void SetMatrix (const Camera::Transform &matrix)
float CalcRotateRadians (int dx, int dy)
float CalcRotateZRadians (int dx, int dy)
float CalcDollyDist (float dy, DragType drag_type, const Camera::Transform &matrix)
Protected Attributes inherited from cloudViewer::visualization::rendering::RotationInteractorLogic
double min_far_plane_
Camera * camera_
Protected Attributes inherited from cloudViewer::visualization::rendering::MatrixInteractorLogic
int view_width_ = 1
int view_height_ = 1
double model_size_ = 20.0
ccBBox model_bounds_
Eigen::Vector3f center_of_rotation_
Camera::Transform matrix_at_mouse_down_
Eigen::Vector3f center_of_rotation_at_mouse_down_
Detailed Description
Definition at line 16 of file CameraInteractorLogic.h.
Constructor & Destructor Documentation
CameraInteractorLogic()
cloudViewer::visualization::rendering::CameraInteractorLogic::CameraInteractorLogic (Camera * c, double min_far_plane)
Definition at line 14 of file CameraInteractorLogic.cpp.
Member Function Documentation
Dolly() [1/2]
void cloudViewer::visualization::rendering::CameraInteractorLogic::Dolly (float dy, DragType drag_type) override virtual
Moves the matrix along the forward axis. (This is one type of zoom.)
Reimplemented from cloudViewer::visualization::rendering::MatrixInteractorLogic.
Definition at line 44 of file CameraInteractorLogic.cpp.
References cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::MatrixInteractorLogic::center_of_rotation_, cloudViewer::visualization::rendering::MatrixInteractorLogic::Dolly(), cloudViewer::visualization::rendering::Camera::GetModelMatrix(), cloudViewer::visualization::rendering::MatrixInteractorLogic::MOUSE, cloudViewer::visualization::rendering::MatrixInteractorLogic::SetMouseDownInfo(), and type.
Referenced by Zoom().
Dolly() [2/2]
void cloudViewer::visualization::rendering::CameraInteractorLogic::Dolly (float z_dist, Camera::Transform matrix_in) override virtual
Reimplemented from cloudViewer::visualization::rendering::MatrixInteractorLogic.
Definition at line 52 of file CameraInteractorLogic.cpp.
References cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::MatrixInteractorLogic::Dolly(), cloudViewer::visualization::rendering::MatrixInteractorLogic::GetMatrix(), cloudViewer::visualization::rendering::Camera::SetModelMatrix(), and cloudViewer::visualization::rendering::RotationInteractorLogic::UpdateCameraFarPlane().
EndMouseDrag()
void cloudViewer::visualization::rendering::CameraInteractorLogic::EndMouseDrag () override virtual
Reimplemented from cloudViewer::visualization::rendering::RotationInteractorLogic.
Definition at line 143 of file CameraInteractorLogic.cpp.
MoveLocal()
void cloudViewer::visualization::rendering::CameraInteractorLogic::MoveLocal (const Eigen::Vector3f & v)
Definition at line 72 of file CameraInteractorLogic.cpp.
References cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::Camera::GetModelMatrix(), and cloudViewer::visualization::rendering::Camera::SetModelMatrix().
Pan()
void cloudViewer::visualization::rendering::CameraInteractorLogic::Pan (int dx, int dy) override virtual
Reimplemented from cloudViewer::visualization::rendering::RotationInteractorLogic.
Definition at line 60 of file CameraInteractorLogic.cpp.
References cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::MatrixInteractorLogic::GetMatrix(), cloudViewer::visualization::rendering::RotationInteractorLogic::Pan(), and cloudViewer::visualization::rendering::Camera::SetModelMatrix().
ResetMouseDrag()
void cloudViewer::visualization::rendering::CameraInteractorLogic::ResetMouseDrag ()
Definition at line 139 of file CameraInteractorLogic.cpp.
References StartMouseDrag().
Rotate()
void cloudViewer::visualization::rendering::CameraInteractorLogic::Rotate (int dx, int dy) override virtual
Rotates about an axis defined by dx * matrixLeft, dy * matrixUp. dy is assumed to be in window-style coordinates, that is, going up produces a negative dy. The axis goes through the center of rotation.
Reimplemented from cloudViewer::visualization::rendering::MatrixInteractorLogic.
Reimplemented in cloudViewer::visualization::rendering::CameraSphereInteractorLogic.
Definition at line 25 of file CameraInteractorLogic.cpp.
References cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::MatrixInteractorLogic::GetMatrix(), cloudViewer::visualization::rendering::MatrixInteractorLogic::Rotate(), and cloudViewer::visualization::rendering::Camera::SetModelMatrix().
RotateFly()
void cloudViewer::visualization::rendering::CameraInteractorLogic::RotateFly (int dx, int dy)
Definition at line 35 of file CameraInteractorLogic.cpp.
References cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::MatrixInteractorLogic::GetMatrix(), cloudViewer::visualization::rendering::Camera::GetModelMatrix(), cloudViewer::visualization::rendering::Camera::GetPosition(), cloudViewer::visualization::rendering::MatrixInteractorLogic::Rotate(), cloudViewer::visualization::rendering::Camera::SetModelMatrix(), and cloudViewer::visualization::rendering::MatrixInteractorLogic::SetMouseDownInfo().
RotateLocal()
void cloudViewer::visualization::rendering::CameraInteractorLogic::RotateLocal (float angle_rad, const Eigen::Vector3f & axis)
Definition at line 65 of file CameraInteractorLogic.cpp.
References cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::Camera::GetModelMatrix(), and cloudViewer::visualization::rendering::Camera::SetModelMatrix().
RotateZ()
void cloudViewer::visualization::rendering::CameraInteractorLogic::RotateZ (int dx, int dy) override virtual
Rotates about the forward axis of the matrix.
Reimplemented from cloudViewer::visualization::rendering::MatrixInteractorLogic.
Definition at line 30 of file CameraInteractorLogic.cpp.
References cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::MatrixInteractorLogic::GetMatrix(), cloudViewer::visualization::rendering::MatrixInteractorLogic::RotateZ(), and cloudViewer::visualization::rendering::Camera::SetModelMatrix().
SetBoundingBox()
void cloudViewer::visualization::rendering::CameraInteractorLogic::SetBoundingBox (const ccBBox & bounds) override virtual
Reimplemented from cloudViewer::visualization::rendering::MatrixInteractorLogic.
Definition at line 17 of file CameraInteractorLogic.cpp.
References cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, ccBBox::GetCenter(), cloudViewer::visualization::rendering::Camera::GetModelMatrix(), cloudViewer::visualization::rendering::MatrixInteractorLogic::SetBoundingBox(), and cloudViewer::visualization::rendering::MatrixInteractorLogic::SetMouseDownInfo().
StartMouseDrag()
void cloudViewer::visualization::rendering::CameraInteractorLogic::StartMouseDrag () override virtual
Reimplemented from cloudViewer::visualization::rendering::RotationInteractorLogic.
Reimplemented in cloudViewer::visualization::rendering::CameraSphereInteractorLogic.
Definition at line 134 of file CameraInteractorLogic.cpp.
References cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::MatrixInteractorLogic::center_of_rotation_, cloudViewer::visualization::rendering::Camera::GetFieldOfView(), cloudViewer::visualization::rendering::Camera::GetModelMatrix(), and cloudViewer::visualization::rendering::MatrixInteractorLogic::SetMouseDownInfo().
Referenced by ResetMouseDrag(), and cloudViewer::visualization::rendering::CameraSphereInteractorLogic::StartMouseDrag().
UpdateMouseDragUI()
void cloudViewer::visualization::rendering::CameraInteractorLogic::UpdateMouseDragUI () override virtual
Reimplemented from cloudViewer::visualization::rendering::RotationInteractorLogic.
Definition at line 141 of file CameraInteractorLogic.cpp.
Zoom()
void cloudViewer::visualization::rendering::CameraInteractorLogic::Zoom (int dy, DragType drag_type)
Sets camera field of view.
Definition at line 78 of file CameraInteractorLogic.cpp.
References cloudViewer::visualization::rendering::RotationInteractorLogic::camera_, cloudViewer::visualization::rendering::MatrixInteractorLogic::center_of_rotation_, cloudViewer::visualization::rendering::MatrixInteractorLogic::center_of_rotation_at_mouse_down_, Dolly(), cloudViewer::visualization::rendering::Camera::GetFar(), cloudViewer::visualization::rendering::Camera::GetFieldOfView(), cloudViewer::visualization::rendering::Camera::GetFieldOfViewType(), cloudViewer::visualization::rendering::Camera::GetModelMatrix(), cloudViewer::visualization::rendering::Camera::GetNear(), cloudViewer::visualization::rendering::Camera::GetPosition(), M_PI, cloudViewer::visualization::rendering::MatrixInteractorLogic::matrix_at_mouse_down_, max(), min(), cloudViewer::visualization::rendering::MatrixInteractorLogic::MOUSE, cloudViewer::visualization::rendering::Camera::SetProjection(), cloudViewer::visualization::rendering::MatrixInteractorLogic::TWO_FINGER, cloudViewer::visualization::rendering::MatrixInteractorLogic::view_height_, cloudViewer::visualization::rendering::MatrixInteractorLogic::view_width_, and cloudViewer::visualization::rendering::MatrixInteractorLogic::WHEEL.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/CameraInteractorLogic.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/CameraInteractorLogic.cpp