ACloudViewer: ccScalarField Class Reference
ccScalarField Class Reference
A scalar field associated to display-related parameters.
#include <ecvScalarField.h>
Classes
struct Histogram
Simple histogram structure.
class Range
Scalar field range structure.
Public Member Functions
ccScalarField (const char *name=nullptr)
Default constructor.
ccScalarField (const ccScalarField &sf)
Copy constructor.
const Range & displayRange () const
Access to the range of displayed values.
const Range & saturationRange () const
Access to the range of saturation values.
const Range & logSaturationRange () const
Access to the range of log scale saturation values.
void setMinDisplayed (ScalarType val)
Sets the minimum displayed value.
void setMaxDisplayed (ScalarType val)
Sets the maximum displayed value.
void setSaturationStart (ScalarType val)
Sets the value at which to start color gradient.
void setSaturationStop (ScalarType val)
Sets the value at which to stop color gradient.
const ecvColor::Rgb * getColor (ScalarType value) const
const ecvColor::Rgb * getValueColor (unsigned index) const
Shortcut to getColor.
void showNaNValuesInGrey (bool state)
bool areNaNValuesShownInGrey () const
Returns whether NaN values are displayed in gray or hidden.
void alwaysShowZero (bool state)
Sets whether 0 should always appear in associated color ramp or not.
bool isZeroAlwaysShown () const
Returns whether 0 should always appear in associated color ramp or not.
void setSymmetricalScale (bool state)
Sets whether the color scale should be symmetrical or not.
bool symmetricalScale () const
Returns whether the color scale s symmetrical or not.
void setLogScale (bool state)
Sets whether scale is logarithmic or not.
bool logScale () const
Returns whether scalar field is logarithmic or not.
void computeMinAndMax () override
Determines the min and max values.
const ccColorScale::Shared & getColorScale () const
Returns associated color scale.
void setColorScale (ccColorScale::Shared scale)
Sets associated color scale.
unsigned getColorRampSteps () const
Returns number of color ramp steps.
void setColorRampSteps (unsigned steps)
Sets number of color ramp steps used for display.
const Histogram & getHistogram () const
Returns associated histogram values (for display)
bool mayHaveHiddenValues () const
void setModificationFlag (bool state)
Sets modification flag state.
bool getModificationFlag () const
Returns modification flag state.
void importParametersFrom (const ccScalarField *sf)
Imports the parameters from another scalar field.
bool isSerializable () const override
Returns whether object is serializable of not.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
double getGlobalShift () const
Returns the global shift (if any)
void setGlobalShift (double shift)
Sets the global shift.
Public Member Functions inherited from cloudViewer::ScalarField
ScalarField (const char *name=nullptr)
Default constructor.
ScalarField (const ScalarField &sf)
Copy constructor.
void setName (const char *name)
Sets scalar field name.
const char * getName () const
Returns scalar field name.
void computeMeanAndVariance (ScalarType &mean, ScalarType *variance=nullptr) const
void flagValueAsInvalid (std::size_t index)
Sets the value as 'invalid' (i.e. NAN_VALUE)
std::size_t countValidValues () const
Returns the number of valid values in this scalar field.
ScalarType getMin () const
Returns the minimum value.
ScalarType getMax () const
Returns the maximum value.
void fill (ScalarType fillValue=0)
Fills the array with a particular value.
bool reserveSafe (std::size_t count)
Reserves memory (no exception thrown)
bool resizeSafe (std::size_t count, bool initNewElements=false, ScalarType valueForNewElements=0)
Resizes memory (no exception thrown)
ScalarType & getValue (std::size_t index)
const ScalarType & getValue (std::size_t index) const
void setValue (std::size_t index, ScalarType value)
void addElement (ScalarType value)
unsigned currentSize () const
void swap (std::size_t i1, std::size_t i2)
~ScalarField () override=default
Default destructor.
Public Member Functions inherited from CCShareable
CCShareable ()
Default constructor.
virtual void link ()
Increase counter.
virtual void release ()
Decrease counter and deletes object when 0.
virtual unsigned getLinkCount () const
Returns the current link count.
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Protected Member Functions
~ccScalarField () override=default
Default destructor.
void updateSaturationBounds ()
Updates saturation values.
ScalarType normalize (ScalarType val) const
Normalizes a scalar value between 0 and 1 (wrt to current parameters)
Protected Member Functions inherited from CCShareable
virtual ~CCShareable ()
Destructor.
Protected Attributes
Range m_displayRange
Displayed values range.
Range m_saturationRange
Saturation values range.
Range m_logSaturationRange
saturation values range (log scale mode)
bool m_showNaNValuesInGrey
Whether NaN values are shown in grey or are hidden.
bool m_symmetricalScale
Whether color scale is symmetrical or not.
bool m_logScale
Whether scale is logarithmic or not.
bool m_alwaysShowZero
Whether 0 should always appear in associated color ramp.
ccColorScale::Shared m_colorScale
Active color ramp (for display)
unsigned m_colorRampSteps
Number of color ramps steps (for display)
Histogram m_histogram
Associated histogram values (for display)
bool m_modified
Modification flag.
double m_globalShift
Global shift.
Protected Attributes inherited from cloudViewer::ScalarField
char m_name [256]
Scalar field name.
ScalarType m_minVal
Minimum value.
ScalarType m_maxVal
Maximum value.
Protected Attributes inherited from CCShareable
unsigned m_linkCount
Links counter.
Additional Inherited Members
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Static Public Member Functions inherited from cloudViewer::ScalarField
static ScalarType NaN ()
Returns the specific NaN value.
static bool ValidValue (ScalarType value)
Returns whether a scalar value is valid or not.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Detailed Description
A scalar field associated to display-related parameters.
Extends the cloudViewer::ScalarField object.
Definition at line 19 of file ecvScalarField.h.
Constructor & Destructor Documentation
ccScalarField() [1/2]
ccScalarField::ccScalarField (const char * name = nullptr) explicit
Default constructor.
Parameters
name scalar field name
ccScalarField() [2/2]
ccScalarField::ccScalarField (const ccScalarField & sf)
Copy constructor.
Parameters
sf scalar field to copy
Warning
May throw a std::bad_alloc exception
~ccScalarField()
ccScalarField::~ccScalarField () override protected default
Default destructor.
Call release instead
Member Function Documentation
alwaysShowZero()
void ccScalarField::alwaysShowZero (bool state)
Sets whether 0 should always appear in associated color ramp or not.
Referenced by define_ccScalarField().
areNaNValuesShownInGrey()
bool ccScalarField::areNaNValuesShownInGrey () const inline
Returns whether NaN values are displayed in gray or hidden.
Definition at line 156 of file ecvScalarField.h.
Referenced by define_ccScalarField(), and ccSNECloud::drawMeOnly().
computeMinAndMax()
void ccScalarField::computeMinAndMax () override virtual
Determines the min and max values.
Reimplemented from cloudViewer::ScalarField.
Referenced by masc::Classifier::classify(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), DistanceMapGenerationTool::ComputeRadialDist(), DistanceMapGenerationTool::ConvertMapToCloud(), ccMeasurementDevice::createScalarFieldForCloud(), qPCV::doAction(), qPoissonRecon::doAction(), ccCompass::estimateStrain(), masc::Classifier::evaluate(), LoadCloud(), LoadScan(), PCVCommand::Process(), and DistanceMapGenerationDlg::update().
displayRange()
const Range& ccScalarField::displayRange () const inline
Access to the range of displayed values.
Values outside of the [start;stop] intervale will either be grey or invisible (see showNaNValuesInGrey).
Definition at line 108 of file ecvScalarField.h.
Referenced by define_ccScalarField(), and ccSNECloud::drawMeOnly().
fromFile()
bool ccScalarField::fromFile (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override virtual
Loads data from binary stream.
Parameters
in input file (already opened)
dataVersion file version (for version-specific deserialization)
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Returns
success
Note: When implementing, use dataVersion checks to handle different
versions:
if (dataVersion >= X) { read new field } else { use default value } This ensures forward compatibility with older file formats.
Reimplemented from ccSerializableObject.
getColor()
const ecvColor::Rgb* ccScalarField::getColor (ScalarType value) const inline
Returns the color corresponding to a given value (wrt to the current display parameters) Warning: must no be called if the SF is not associated to a color scale!
Definition at line 139 of file ecvScalarField.h.
References ecvColor::lightGrey(), and normalize().
Referenced by define_ccScalarField(), and ccSNECloud::drawMeOnly().
getColorRampSteps()
unsigned ccScalarField::getColorRampSteps () const inline
Returns number of color ramp steps.
Definition at line 194 of file ecvScalarField.h.
Referenced by define_ccScalarField().
getColorScale()
const ccColorScale::Shared& ccScalarField::getColorScale () const inline
Returns associated color scale.
Definition at line 186 of file ecvScalarField.h.
Referenced by define_ccScalarField(), and DistanceMapGenerationDlg::DistanceMapGenerationDlg().
getGlobalShift()
double ccScalarField::getGlobalShift () const inline
Returns the global shift (if any)
Definition at line 234 of file ecvScalarField.h.
Referenced by define_ccScalarField(), ExtraLasField::ExtraLasField(), LasField::GetLASFields(), and SimpleBinFilter::saveToFile().
getHistogram()
const Histogram& ccScalarField::getHistogram () const inline
Returns associated histogram values (for display)
Definition at line 206 of file ecvScalarField.h.
Referenced by define_ccScalarField().
getModificationFlag()
bool ccScalarField::getModificationFlag () const inline
Returns modification flag state.
Definition at line 219 of file ecvScalarField.h.
Referenced by define_ccScalarField().
getValueColor()
const ecvColor::Rgb* ccScalarField::getValueColor (unsigned index) const inline
Shortcut to getColor.
Definition at line 147 of file ecvScalarField.h.
References cloudViewer::ScalarField::getValue().
Referenced by define_ccScalarField().
importParametersFrom()
void ccScalarField::importParametersFrom (const ccScalarField * sf)
Imports the parameters from another scalar field.
Referenced by define_ccScalarField().
isSerializable()
bool ccScalarField::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccSerializableObject.
Definition at line 225 of file ecvScalarField.h.
isZeroAlwaysShown()
bool ccScalarField::isZeroAlwaysShown () const inline
Returns whether 0 should always appear in associated color ramp or not.
Definition at line 164 of file ecvScalarField.h.
Referenced by define_ccScalarField().
logSaturationRange()
const Range& ccScalarField::logSaturationRange () const inline
Access to the range of log scale saturation values.
Relative color scales will only be applied to values inside the [start;stop] intervale.
Definition at line 122 of file ecvScalarField.h.
Referenced by define_ccScalarField().
logScale()
bool ccScalarField::logScale () const inline
Returns whether scalar field is logarithmic or not.
Definition at line 180 of file ecvScalarField.h.
Referenced by define_ccScalarField().
mayHaveHiddenValues()
bool ccScalarField::mayHaveHiddenValues () const
Returns whether the scalar field in its current configuration MAY have 'hidden' values or not 'Hidden' values are typically NaN values or values outside of the 'displayed' intervale while those values are not displayed in grey (see ccScalarField::showNaNValuesInGrey).
Referenced by define_ccScalarField().
minimumFileVersion()
short ccScalarField::minimumFileVersion () const override virtual
Returns the minimum file version required to save this instance.
To be overridden by subclasses to indicate their minimum required version. This enables the system to determine:
Forward compatibility: newer software can read older files (dataVersion check in fromFile)
Backward compatibility: determine minimum version needed to save current data
Returns
minimum file version required for this object
Implements ccSerializableObject.
normalize()
ScalarType ccScalarField::normalize (ScalarType val) const protected
Normalizes a scalar value between 0 and 1 (wrt to current parameters)
Parameters
val scalar value
Returns
a number between 0 and 1 if inside displayed range or -1 otherwise
saturationRange()
const Range& ccScalarField::saturationRange () const inline
Access to the range of saturation values.
Relative color scales will only be applied to values inside the [start;stop] intervale.
Definition at line 114 of file ecvScalarField.h.
Referenced by define_ccScalarField().
setColorRampSteps()
void ccScalarField::setColorRampSteps (unsigned steps)
Sets number of color ramp steps used for display.
Referenced by DistanceMapGenerationDlg::colorScaleChanged(), define_ccScalarField(), and DistanceMapGenerationDlg::update().
setColorScale()
void ccScalarField::setColorScale (ccColorScale::Shared scale)
Sets associated color scale.
Referenced by DistanceMapGenerationDlg::colorScaleChanged(), define_ccScalarField(), qPCV::doAction(), DistanceMapGenerationDlg::exportMapAsCloud(), LoadScan(), PCVCommand::Process(), and DistanceMapGenerationDlg::update().
setGlobalShift()
void ccScalarField::setGlobalShift (double shift) inline
Sets the global shift.
Definition at line 236 of file ecvScalarField.h.
Referenced by define_ccScalarField(), and SimpleBinFilter::loadFile().
setLogScale()
void ccScalarField::setLogScale (bool state)
Sets whether scale is logarithmic or not.
Referenced by define_ccScalarField().
setMaxDisplayed()
void ccScalarField::setMaxDisplayed (ScalarType val)
Sets the maximum displayed value.
Referenced by define_ccScalarField().
setMinDisplayed()
void ccScalarField::setMinDisplayed (ScalarType val)
Sets the minimum displayed value.
Referenced by qM3C2Process::Compute(), and define_ccScalarField().
setModificationFlag()
void ccScalarField::setModificationFlag (bool state) inline
Sets modification flag state.
Definition at line 217 of file ecvScalarField.h.
Referenced by define_ccScalarField().
setSaturationStart()
void ccScalarField::setSaturationStart (ScalarType val)
Sets the value at which to start color gradient.
Referenced by define_ccScalarField(), and E57Filter::loadFile().
setSaturationStop()
void ccScalarField::setSaturationStop (ScalarType val)
Sets the value at which to stop color gradient.
Referenced by define_ccScalarField(), and E57Filter::loadFile().
setSymmetricalScale()
void ccScalarField::setSymmetricalScale (bool state)
Sets whether the color scale should be symmetrical or not.
For relative color scales only.
Referenced by qM3C2Process::Compute(), and define_ccScalarField().
showNaNValuesInGrey()
void ccScalarField::showNaNValuesInGrey (bool state)
Sets whether NaN/out of displayed range values should be displayed in gray or hidden
Referenced by define_ccScalarField(), and qPoissonRecon::doAction().
symmetricalScale()
bool ccScalarField::symmetricalScale () const inline
Returns whether the color scale s symmetrical or not.
For relative color scales only.
Definition at line 174 of file ecvScalarField.h.
Referenced by define_ccScalarField().
toFile()
bool ccScalarField::toFile (QFile & out, short dataVersion) const override virtual
Saves data to binary stream.
Parameters
out output file (already opened)
dataVersion target file version (for forward/backward compatibility)
Returns
success
Reimplemented from ccSerializableObject.
updateSaturationBounds()
void ccScalarField::updateSaturationBounds () protected
Updates saturation values.
Member Data Documentation
m_alwaysShowZero
bool ccScalarField::m_alwaysShowZero protected
Whether 0 should always appear in associated color ramp.
Definition at line 280 of file ecvScalarField.h.
m_colorRampSteps
unsigned ccScalarField::m_colorRampSteps protected
Number of color ramps steps (for display)
Definition at line 286 of file ecvScalarField.h.
m_colorScale
ccColorScale::Shared ccScalarField::m_colorScale protected
Active color ramp (for display)
Definition at line 283 of file ecvScalarField.h.
m_displayRange
Range ccScalarField::m_displayRange protected
Displayed values range.
Definition at line 256 of file ecvScalarField.h.
m_globalShift
double ccScalarField::m_globalShift protected
Global shift.
Definition at line 298 of file ecvScalarField.h.
m_histogram
Histogram ccScalarField::m_histogram protected
Associated histogram values (for display)
Definition at line 289 of file ecvScalarField.h.
m_logSaturationRange
Range ccScalarField::m_logSaturationRange protected
saturation values range (log scale mode)
For log scale color mapping with relative scales.
Definition at line 266 of file ecvScalarField.h.
m_logScale
bool ccScalarField::m_logScale protected
Whether scale is logarithmic or not.
Definition at line 277 of file ecvScalarField.h.
m_modified
bool ccScalarField::m_modified protected
Modification flag.
Any modification to the scalar field values or parameters will turn this flag on.
Definition at line 295 of file ecvScalarField.h.
m_saturationRange
Range ccScalarField::m_saturationRange protected
Saturation values range.
For color mapping with relative scales.
Definition at line 261 of file ecvScalarField.h.
m_showNaNValuesInGrey
bool ccScalarField::m_showNaNValuesInGrey protected
Whether NaN values are shown in grey or are hidden.
Definition at line 269 of file ecvScalarField.h.
m_symmetricalScale
bool ccScalarField::m_symmetricalScale protected
Whether color scale is symmetrical or not.
For relative color scales only.
Definition at line 274 of file ecvScalarField.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvScalarField.h