ACloudViewer: ccPointCloudLODThread Class Reference
ccPointCloudLODThread Class Reference
Thread for background computation.
Public Member Functions
ccPointCloudLODThread (ccPointCloud &cloud, ccPointCloudLOD &lod, uint32_t maxCountPerCell)
Default constructor.
virtual ~ccPointCloudLODThread ()
Destructor.
Protected Member Functions
uint8_t fillNode (ccPointCloudLOD::Node &node) const
Fills a node (and returns its relative position) + recursive.
uint8_t fillNode_flat (ccPointCloudLOD::Node &node) const
Fills a node (and returns its relative position)
virtual void run ()
Protected Attributes
ccPointCloud & m_cloud
ccPointCloudLOD & m_lod
ccOctree::Shared m_octree
uint32_t m_maxCountPerCell
uint8_t m_maxLevel
Detailed Description
Thread for background computation.
Definition at line 19 of file ecvPointCloudLOD.cpp.
Constructor & Destructor Documentation
ccPointCloudLODThread()
ccPointCloudLODThread::ccPointCloudLODThread (ccPointCloud & cloud, ccPointCloudLOD & lod, uint32_t maxCountPerCell) inline
Default constructor.
Definition at line 24 of file ecvPointCloudLOD.cpp.
~ccPointCloudLODThread()
virtual ccPointCloudLODThread::~ccPointCloudLODThread () inline virtual
Destructor.
Definition at line 35 of file ecvPointCloudLOD.cpp.
Member Function Documentation
fillNode()
uint8_t ccPointCloudLODThread::fillNode (ccPointCloudLOD::Node & node) const inline protected
Fills a node (and returns its relative position) + recursive.
Definition at line 39 of file ecvPointCloudLOD.cpp.
References cloudViewer::BoundingBoxTpl< T >::add(), ccPointCloudLOD::Node::center, ccPointCloudLOD::Node::childCount, ccPointCloudLOD::Node::childIndexes, ccPointCloudLOD::Node::firstCodeIndex, Vector3Tpl< float >::fromArray(), Vector3Tpl< double >::fromArray(), cloudViewer::DgmOctree::GET_BIT_SHIFT(), cloudViewer::BoundingBoxTpl< T >::getCenter(), cloudViewer::BoundingBoxTpl< T >::getDiagNormd(), cloudViewer::PointCloudTpl< T >::getPoint(), ccPointCloudLOD::Node::level, m_cloud, m_lod, m_maxCountPerCell, m_maxLevel, m_octree, ccPointCloudLOD::newCell(), ccPointCloudLOD::node(), ccPointCloudLOD::Node::pointCount, ccPointCloudLOD::Node::radius, and Tuple3Tpl< Type >::u.
Referenced by run().
fillNode_flat()
uint8_t ccPointCloudLODThread::fillNode_flat (ccPointCloudLOD::Node & node) const inline protected
Fills a node (and returns its relative position)
Definition at line 117 of file ecvPointCloudLOD.cpp.
References ccPointCloudLOD::Node::center, ccPointCloudLOD::Node::firstCodeIndex, Vector3Tpl< double >::fromArray(), Vector3Tpl< float >::fromArray(), cloudViewer::DgmOctree::GET_BIT_SHIFT(), cloudViewer::PointCloudTpl< T >::getPoint(), ccPointCloudLOD::Node::level, m_cloud, m_octree, ccPointCloudLOD::Node::pointCount, ccPointCloudLOD::Node::radius, and Tuple3Tpl< Type >::u.
Referenced by run().
run()
virtual void ccPointCloudLODThread::run () inline protected virtual
Definition at line 165 of file ecvPointCloudLOD.cpp.
References ccPointCloudLOD::BROKEN, ccPointCloudLOD::Node::childCount, ccPointCloudLOD::Node::childIndexes, ccPointCloudLOD::clearData(), ccPointCloudLOD::Level::data, fillNode(), fillNode_flat(), ccPointCloudLOD::Node::firstCodeIndex, ccObject::getName(), ccGenericPointCloud::getOctree(), ccPointCloudLOD::INITIALIZED, ccPointCloudLOD::Node::level, m_cloud, ccPointCloudLOD::m_levels, m_lod, m_maxCountPerCell, m_maxLevel, m_octree, cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, ccPointCloudLOD::memory(), ccPointCloudLOD::newCell(), ccPointCloudLOD::node(), ccPointCloudLOD::Node::pointCount, CVLog::Print(), ccPointCloudLOD::root(), ccGenericPointCloud::setOctree(), ccPointCloudLOD::setState(), ccPointCloudLOD::shrink_to_fit(), cloudViewer::PointCloudTpl< T >::size(), ccPointCloudLOD::UNDER_CONSTRUCTION, ccOctree::updated(), and CVLog::Warning().
Member Data Documentation
m_cloud
ccPointCloud& ccPointCloudLODThread::m_cloud protected
Definition at line 374 of file ecvPointCloudLOD.cpp.
Referenced by fillNode(), fillNode_flat(), and run().
m_lod
ccPointCloudLOD& ccPointCloudLODThread::m_lod protected
Definition at line 375 of file ecvPointCloudLOD.cpp.
Referenced by fillNode(), and run().
m_maxCountPerCell
uint32_t ccPointCloudLODThread::m_maxCountPerCell protected
Definition at line 377 of file ecvPointCloudLOD.cpp.
Referenced by fillNode(), and run().
m_maxLevel
uint8_t ccPointCloudLODThread::m_maxLevel protected
Definition at line 378 of file ecvPointCloudLOD.cpp.
Referenced by fillNode(), and run().
m_octree
ccOctree::Shared ccPointCloudLODThread::m_octree protected
Definition at line 376 of file ecvPointCloudLOD.cpp.
Referenced by fillNode(), fillNode_flat(), and run().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/src/ecvPointCloudLOD.cpp