ACloudViewer: SliderLabelWidget Class Reference
SliderLabelWidget Class Reference
All sliders labels widget.
#include <ecvColorScaleEditorWidget.h>
Public Member Functions
SliderLabelWidget (SharedColorScaleElementSliders sliders, QWidget *parent=nullptr, Qt::Orientation orientation=Qt::Horizontal)
Default constructor.
void setTextColor (QColor color)
Sets text color.
void setPrecision (int precision)
Sets displayed numbers precision.
Public Member Functions inherited from ColorScaleEditorBaseWidget
ColorScaleEditorBaseWidget (SharedColorScaleElementSliders sliders, Qt::Orientation orientation, int margin, QWidget *parent=nullptr)
Defautl constructor.
int length () const
Returns useful length.
virtual void setSliders (SharedColorScaleElementSliders sliders)
Sets associated sliders set.
Qt::Orientation getOrientation () const
Returns orientation.
int getMargin () const
Returns margin.
Protected Member Functions
void paintEvent (QPaintEvent *e) override
Protected Attributes
QColor m_textColor
Text color.
int m_precision
Precision.
Protected Attributes inherited from ColorScaleEditorBaseWidget
SharedColorScaleElementSliders m_sliders
Associated sliders.
Qt::Orientation m_orientation
Orientation.
int m_margin
Margin.
Detailed Description
All sliders labels widget.
Definition at line 197 of file ecvColorScaleEditorWidget.h.
Constructor & Destructor Documentation
SliderLabelWidget()
SliderLabelWidget::SliderLabelWidget (SharedColorScaleElementSliders sliders, QWidget * parent = nullptr, Qt::Orientation orientation = Qt::Horizontal)
Default constructor.
Definition at line 417 of file ecvColorScaleEditorWidget.cpp.
Member Function Documentation
paintEvent()
void SliderLabelWidget::paintEvent (QPaintEvent * e) override protected
Definition at line 427 of file ecvColorScaleEditorWidget.cpp.
References DEFAULT_TEXT_MARGIN, ColorScaleEditorBaseWidget::m_orientation, m_precision, ColorScaleEditorBaseWidget::m_sliders, m_textColor, max(), and width.
setPrecision()
void SliderLabelWidget::setPrecision (int precision) inline
Sets displayed numbers precision.
Definition at line 210 of file ecvColorScaleEditorWidget.h.
Referenced by ccColorScaleEditorWidget::setLabelPrecision().
setTextColor()
void SliderLabelWidget::setTextColor (QColor color) inline
Sets text color.
Definition at line 207 of file ecvColorScaleEditorWidget.h.
References color.
Referenced by ccColorScaleEditorWidget::setLabelColor().
Member Data Documentation
m_precision
int SliderLabelWidget::m_precision protected
Precision.
Definition at line 220 of file ecvColorScaleEditorWidget.h.
Referenced by paintEvent().
m_textColor
QColor SliderLabelWidget::m_textColor protected
Text color.
Definition at line 217 of file ecvColorScaleEditorWidget.h.
Referenced by paintEvent().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVPluginAPI/include/ecvColorScaleEditorWidget.h
/root/ACloudViewer/libs/CVPluginAPI/src/ecvColorScaleEditorWidget.cpp