ACloudViewer: cvQueryConditionWidget Class Reference
cvQueryConditionWidget Class Reference
cvQueryConditionWidget - Single query condition widget
#include <cvQueryWidgets.h>
Public Types
enum TermType { ARRAY , POINT_NEAREST_TO , CELL_CONTAINING_POINT }
Signals
void conditionChanged ()
Public Member Functions
cvQueryConditionWidget (QWidget *parent=nullptr)
~cvQueryConditionWidget () override=default
void updateTerms (const QStringList &arrayNames, const QMap< QString, int > &arrayComponents, bool isPointData)
QString expression () const
void setExpression (const QString &expr)
void clear ()
Detailed Description
cvQueryConditionWidget - Single query condition widget
Based on ParaView's pqQueryWidget, represents one query condition row: [Term Combo] [Operator Combo] [Value Widget]
The widget automatically updates the operator list and value widget based on the selected term type.
Definition at line 92 of file cvQueryWidgets.h.
Member Enumeration Documentation
TermType
enum cvQueryConditionWidget::TermType
Enumerator
ARRAY
POINT_NEAREST_TO
CELL_CONTAINING_POINT
Definition at line 96 of file cvQueryWidgets.h.
Constructor & Destructor Documentation
cvQueryConditionWidget()
cvQueryConditionWidget::cvQueryConditionWidget (QWidget * parent = nullptr) explicit
Definition at line 164 of file cvQueryWidgets.cpp.
References conditionChanged(), and cvQueryValueWidget::valueChanged().
~cvQueryConditionWidget()
cvQueryConditionWidget::~cvQueryConditionWidget () override default
Member Function Documentation
clear()
void cvQueryConditionWidget::clear ()
Clear all selections
Definition at line 300 of file cvQueryWidgets.cpp.
References cvQueryValueWidget::clear().
conditionChanged
void cvQueryConditionWidget::conditionChanged () signal
Referenced by cvQueryConditionWidget().
expression()
QString cvQueryConditionWidget::expression () const
Get the generated query expression (e.g., "NormalX >= 0.5")
Definition at line 246 of file cvQueryWidgets.cpp.
References QueryExpressionUtils::formatExpression(), and cvQueryValueWidget::values().
setExpression()
void cvQueryConditionWidget::setExpression (const QString & expr)
Set expression and parse it to update UI
Definition at line 258 of file cvQueryWidgets.cpp.
References CELL_CONTAINING_POINT, cvQueryValueWidget::clear(), and cvQueryValueWidget::setValues().
updateTerms()
void cvQueryConditionWidget::updateTerms (const QStringList & arrayNames, const QMap< QString, int > & arrayComponents, bool isPointData)
Update the widget with available terms from data
Definition at line 188 of file cvQueryWidgets.cpp.
References ARRAY, CELL_CONTAINING_POINT, and POINT_NEAREST_TO.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvQueryWidgets.h
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvQueryWidgets.cpp