ACloudViewer: cloudViewer::pipelines::registration::GlobalOptimizationGaussNewton Class Reference
cloudViewer::pipelines::registration::GlobalOptimizationGaussNewton Class Reference
Global optimization with Gauss-Newton algorithm.
#include <GlobalOptimizationMethod.h>
Public Member Functions
GlobalOptimizationGaussNewton ()
Default Constructor.
~GlobalOptimizationGaussNewton () override
void OptimizePoseGraph (PoseGraph &pose_graph, const GlobalOptimizationConvergenceCriteria &criteria, const GlobalOptimizationOption &option) const override
Run pose graph optimization method.
Public Member Functions inherited from cloudViewer::pipelines::registration::GlobalOptimizationMethod
GlobalOptimizationMethod ()
Default Constructor.
virtual ~GlobalOptimizationMethod ()
Detailed Description
Global optimization with Gauss-Newton algorithm.
Definition at line 47 of file GlobalOptimizationMethod.h.
Constructor & Destructor Documentation
GlobalOptimizationGaussNewton()
cloudViewer::pipelines::registration::GlobalOptimizationGaussNewton::GlobalOptimizationGaussNewton () inline
Default Constructor.
Definition at line 50 of file GlobalOptimizationMethod.h.
~GlobalOptimizationGaussNewton()
cloudViewer::pipelines::registration::GlobalOptimizationGaussNewton::~GlobalOptimizationGaussNewton () inline override
Definition at line 51 of file GlobalOptimizationMethod.h.
Member Function Documentation
OptimizePoseGraph()
void cloudViewer::pipelines::registration::GlobalOptimizationGaussNewton::OptimizePoseGraph (PoseGraph & pose_graph, const GlobalOptimizationConvergenceCriteria & criteria, const GlobalOptimizationOption & option) const override virtual
Run pose graph optimization method.
Parameters
pose_graph The pose graph to be optimized (in-place).
criteria Convergence criteria.
option Global optimization options.
Implements cloudViewer::pipelines::registration::GlobalOptimizationMethod.
Definition at line 468 of file GlobalOptimization.cpp.
References cloudViewer::pipelines::registration::CheckMaxIteration(), cloudViewer::pipelines::registration::CheckRelativeIncrement(), cloudViewer::pipelines::registration::CheckRelativeResidualIncrement(), cloudViewer::pipelines::registration::CheckResidual(), cloudViewer::pipelines::registration::CheckRightTerm(), cloudViewer::pipelines::registration::ComputeLinearSystem(), cloudViewer::pipelines::registration::ComputeLineProcessWeight(), cloudViewer::pipelines::registration::ComputeResidual(), cloudViewer::pipelines::registration::ComputeZeta(), cloudViewer::pipelines::registration::PoseGraph::edges_, cloudViewer::utility::Timer::GetDurationInMillisecond(), LogDebug, cloudViewer::pipelines::registration::PoseGraph::nodes_, cloudViewer::utility::SolveLinearSystemPSD(), cloudViewer::utility::Timer::Start(), cloudViewer::utility::Timer::Stop(), cloudViewer::pipelines::registration::UpdateConfidence(), cloudViewer::pipelines::registration::UpdatePoseGraph(), and cloudViewer::pipelines::registration::UpdatePoseVector().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/pipelines/registration/GlobalOptimizationMethod.h
/root/ACloudViewer/libs/cloudViewer/pipelines/registration/GlobalOptimization.cpp