ACloudViewer: ccDefaultPluginData Class Reference
ccDefaultPluginData Class Reference
Public Member Functions
QString field (const QString &fieldName)
ccPluginInterface::ReferenceList references (const QString &fieldName)
ccPluginInterface::ContactList contacts (const QString &fieldName)
Public Attributes
QString m_IID
QJsonDocument doc
Detailed Description
Definition at line 19 of file ecvDefaultPluginInterface.cpp.
Member Function Documentation
contacts()
ccPluginInterface::ContactList ccDefaultPluginData::contacts (const QString & fieldName) inline
Definition at line 40 of file ecvDefaultPluginInterface.cpp.
References doc.
Referenced by ccDefaultPluginInterface::getAuthors(), and ccDefaultPluginInterface::getMaintainers().
field()
QString ccDefaultPluginData::field (const QString & fieldName) inline
Definition at line 21 of file ecvDefaultPluginInterface.cpp.
References doc.
Referenced by ccDefaultPluginInterface::getDescription(), ccDefaultPluginInterface::getIcon(), and ccDefaultPluginInterface::getName().
references()
ccPluginInterface::ReferenceList ccDefaultPluginData::references (const QString & fieldName) inline
Definition at line 25 of file ecvDefaultPluginInterface.cpp.
References doc.
Referenced by ccDefaultPluginInterface::getReferences().
Member Data Documentation
doc
QJsonDocument ccDefaultPluginData::doc
Definition at line 56 of file ecvDefaultPluginInterface.cpp.
Referenced by ccDefaultPluginInterface::ccDefaultPluginInterface(), contacts(), field(), ccDefaultPluginInterface::isCore(), and references().
m_IID
QString ccDefaultPluginData::m_IID
Definition at line 55 of file ecvDefaultPluginInterface.cpp.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CVPluginStub/src/ecvDefaultPluginInterface.cpp