ACloudViewer: ccScaleDlg Class Reference
ccScaleDlg Class Reference
Scale / multiply dialog.
#include <ecvScaleDlg.h>
Public Member Functions
ccScaleDlg (QWidget *parent=0)
Default constructor.
CCVector3d getScales () const
Returns scales.
bool keepInPlace () const
Whether the entity should be 'kept in place' or not.
bool rescaleGlobalShift () const
Whether the Global shift should be rescaled as well.
void saveState ()
Saves state.
Protected Slots
void allDimsAtOnceToggled (bool)
void fxUpdated (double)
Detailed Description
Scale / multiply dialog.
Definition at line 19 of file ecvScaleDlg.h.
Constructor & Destructor Documentation
ccScaleDlg()
ccScaleDlg::ccScaleDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 16 of file ecvScaleDlg.cpp.
References allDimsAtOnceToggled(), fxUpdated(), s_allAtOnce, s_keepInPlace, s_lastScales, s_rescaleGlobalShift, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Member Function Documentation
allDimsAtOnceToggled
void ccScaleDlg::allDimsAtOnceToggled (bool state) protected slot
Definition at line 64 of file ecvScaleDlg.cpp.
Referenced by ccScaleDlg().
fxUpdated
void ccScaleDlg::fxUpdated (double val) protected slot
Definition at line 44 of file ecvScaleDlg.cpp.
Referenced by ccScaleDlg().
getScales()
CCVector3d ccScaleDlg::getScales () const
Returns scales.
Definition at line 51 of file ecvScaleDlg.cpp.
Referenced by saveState().
keepInPlace()
bool ccScaleDlg::keepInPlace () const
Whether the entity should be 'kept in place' or not.
Definition at line 56 of file ecvScaleDlg.cpp.
Referenced by saveState().
rescaleGlobalShift()
bool ccScaleDlg::rescaleGlobalShift () const
Whether the Global shift should be rescaled as well.
Definition at line 60 of file ecvScaleDlg.cpp.
Referenced by saveState().
saveState()
void ccScaleDlg::saveState ()
Saves state.
Definition at line 37 of file ecvScaleDlg.cpp.
References getScales(), keepInPlace(), rescaleGlobalShift(), s_allAtOnce, s_keepInPlace, s_lastScales, and s_rescaleGlobalShift.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvScaleDlg.h
/root/ACloudViewer/app/ecvScaleDlg.cpp