ACloudViewer: ccInterpolationDlg Class Reference
ccInterpolationDlg Class Reference
Dialog for generic interpolation algorithms.
#include <ecvInterpolationDlg.h>
Public Member Functions
ccInterpolationDlg (QWidget *parent=0)
Default constructor.
ccPointCloudInterpolator::Parameters::Method getInterpolationMethod () const
void setInterpolationMethod (ccPointCloudInterpolator::Parameters::Method method)
ccPointCloudInterpolator::Parameters::Algo getInterpolationAlgorithm () const
void setInterpolationAlgorithm (ccPointCloudInterpolator::Parameters::Algo algo)
Protected Slots
void onRadiusUpdated (double)
Detailed Description
Dialog for generic interpolation algorithms.
Definition at line 16 of file ecvInterpolationDlg.h.
Constructor & Destructor Documentation
ccInterpolationDlg()
ccInterpolationDlg::ccInterpolationDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 13 of file ecvInterpolationDlg.cpp.
References onRadiusUpdated().
Member Function Documentation
getInterpolationAlgorithm()
ccPointCloudInterpolator::Parameters::Algo ccInterpolationDlg::getInterpolationAlgorithm () const
Definition at line 54 of file ecvInterpolationDlg.cpp.
References ccPointCloudInterpolator::Parameters::AVERAGE, ccPointCloudInterpolator::Parameters::MEDIAN, and ccPointCloudInterpolator::Parameters::NORMAL_DIST.
Referenced by ccEntityAction::interpolateSFs().
getInterpolationMethod()
ccPointCloudInterpolator::Parameters::Method ccInterpolationDlg::getInterpolationMethod () const
Definition at line 24 of file ecvInterpolationDlg.cpp.
References ccPointCloudInterpolator::Parameters::K_NEAREST_NEIGHBORS, ccPointCloudInterpolator::Parameters::NEAREST_NEIGHBOR, and ccPointCloudInterpolator::Parameters::RADIUS.
Referenced by ccEntityAction::interpolateSFs().
onRadiusUpdated
void ccInterpolationDlg::onRadiusUpdated (double radius) protected slot
Definition at line 83 of file ecvInterpolationDlg.cpp.
Referenced by ccInterpolationDlg().
setInterpolationAlgorithm()
void ccInterpolationDlg::setInterpolationAlgorithm (ccPointCloudInterpolator::Parameters::Algo algo)
Definition at line 66 of file ecvInterpolationDlg.cpp.
References ccPointCloudInterpolator::Parameters::AVERAGE, ccPointCloudInterpolator::Parameters::MEDIAN, and ccPointCloudInterpolator::Parameters::NORMAL_DIST.
Referenced by ccEntityAction::interpolateSFs().
setInterpolationMethod()
void ccInterpolationDlg::setInterpolationMethod (ccPointCloudInterpolator::Parameters::Method method)
Definition at line 36 of file ecvInterpolationDlg.cpp.
References ccPointCloudInterpolator::Parameters::K_NEAREST_NEIGHBORS, ccPointCloudInterpolator::Parameters::NEAREST_NEIGHBOR, and ccPointCloudInterpolator::Parameters::RADIUS.
Referenced by ccEntityAction::interpolateSFs().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvInterpolationDlg.h
/root/ACloudViewer/app/ecvInterpolationDlg.cpp