ACloudViewer: qFacets Class Reference
qFacets Class Reference
Facet detection plugin (BRGM)
#include <qFacets.h>
Protected Types
typedef std::unordered_set< ccFacet * > FacetSet
Set of facets (pointers)
Protected Slots
void fuseKdTreeCells ()
Fuses the cells of a kd-tree to produces planar facets.
void extractFacetsWithFM ()
Uses Fast Marching to detect planar facets.
void exportFacets ()
Exports facets (as shapefiles)
void exportFacetsInfo ()
Exports statistics on a set of facets.
void classifyFacetsByAngle ()
Classifies facets by orientation.
void showStereogram ()
Displays the selected entity stereogram.
Protected Member Functions
void extractFacets (CellsFusionDlg::Algorithm algo)
Uses the given algorithm to detect planar facets.
ccHObject * createFacets (ccPointCloud *cloud, cloudViewer::ReferenceCloudContainer &components, unsigned minPointsPerComponent, double maxEdgeLength, bool randomColors, bool &error)
Creates facets from components.
void getFacetsInCurrentSelection (FacetSet &facets) const
Returns all the facets in the current selection.
void classifyFacetsByAngle (ccHObject *group, double angleStep_deg, double maxDist)
Classifies facets by orientation.
Protected Attributes
QAction * m_doFuseKdTreeCells
Associated action.
QAction * m_fastMarchingExtraction
Associated action.
QAction * m_doExportFacets
Associated action.
QAction * m_doExportFacetsInfo
Associated action.
QAction * m_doClassifyFacetsByAngle
Associated action.
QAction * m_doShowStereogram
Associated action.
Detailed Description
Facet detection plugin (BRGM)
BRGM: BUREAU DE RECHERCHES GEOLOGIQUES ET MINIERES - http://www.brgm.fr/
Definition at line 35 of file qFacets.h.
Member Typedef Documentation
FacetSet
typedef std::unordered_set<ccFacet*> qFacets::FacetSet protected
Set of facets (pointers)
Definition at line 86 of file qFacets.h.
Member Function Documentation
classifyFacetsByAngle [1/2]
void qFacets::classifyFacetsByAngle () protected slot
Classifies facets by orientation.
Definition at line 976 of file qFacets.cpp.
References CV_TYPES::HIERARCHY_OBJECT, s_classifAngleStep, s_classifMaxDist, s_stereogramAngleStep, and ShowDisclaimer().
classifyFacetsByAngle() [2/2]
void qFacets::classifyFacetsByAngle (ccHObject * group, double angleStep_deg, double maxDist) protected
Classifies facets by orientation.
Definition at line 1006 of file qFacets.cpp.
References FacetsClassifier::ByOrientation(), ccHObject::getParent(), CV_TYPES::HIERARCHY_OBJECT, and ccObject::isA().
createFacets()
ccHObject * qFacets::createFacets (ccPointCloud * cloud, cloudViewer::ReferenceCloudContainer & components, unsigned minPointsPerComponent, double maxEdgeLength, bool randomColors, bool & error) protected
Creates facets from components.
Definition at line 435 of file qFacets.cpp.
References ccHObject::addChild(), ecvColor::RgbTpl< Type >::b, c_darkColorRatio, ccOctree::ComputeAverageNorm(), ccNormalVectors::ConvertNormalToDipAndDipDir(), ccFacet::Create(), Vector3Tpl< Type >::dot(), ccGenericMesh::enableStippling(), error(), ecvColor::RgbTpl< Type >::g, FacetsClassifier::GenerateSubfamilyColor(), ccHObject::getChildrenNumber(), ccFacet::getContour(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccObject::getName(), ccFacet::getNormal(), ccFacet::getPolygon(), ccFacet::getRMS(), ccPointCloud::hasNormals(), ccFacet::invertNormal(), ccPointCloud::partialClone(), ecvColor::RgbTpl< Type >::r, ecvColor::Generator::Random(), ccPolyline::setColor(), ccFacet::setColor(), ccPolyline::setGlobalScale(), ccPolyline::setGlobalShift(), ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), ccObject::setName(), ccDrawableObject::setVisible(), ccPolyline::setWidth(), ccGenericMesh::showNormals(), ccPlanarEntityInterface::showNormalVector(), and cloudViewer::ReferenceCloud::size().
Referenced by extractFacets().
exportFacets
void qFacets::exportFacets () protected slot
Exports facets (as shapefiles)
Definition at line 682 of file qFacets.cpp.
References ccHObject::addChild(), ccHObject::applyGLTransformation_recursive(), CC_FERR_NO_ERROR, FacetMetaData::center, ComputeFacetExtensions(), Vector3Tpl< Type >::cross(), ecvFileUtils::defaultDocPath(), FacetMetaData::dip_deg, FacetMetaData::dipDir_deg, ccHObject::DP_NONE, ccHObject::DP_PARENT_OF_OTHER, FacetMetaData::facetIndex, FacetMetaData::familyIndex, fields, cloudViewer::ReferenceCloud::getAssociatedCloud(), ccHObject::getChildrenNumber(), ccGLMatrixTpl< T >::getColumn(), ccFacet::getContour(), GetFacetMetaData(), getFacetsInCurrentSelection(), ccObject::getName(), ccGLMatrixTpl< T >::getTranslationAsVec3D(), cloudViewer::GreaterThanEpsilon(), ccGLMatrixTpl< T >::invert(), Vector3Tpl< Type >::norm2(), FacetMetaData::normal, Vector3Tpl< Type >::normalize(), params, FacetMetaData::rms, ccPolyline::set2DMode(), ccGLMatrixTpl< T >::setTranslation(), FacetsExportDlg::SHAPE_FILE_IO, ShowDisclaimer(), cloudViewer::GenericCloud::size(), FacetMetaData::subfamilyIndex, FacetMetaData::surface, ccGLMatrixTpl< T >::toIdentity(), Tuple3Tpl< Type >::x, X, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
exportFacetsInfo
void qFacets::exportFacetsInfo () protected slot
Exports statistics on a set of facets.
Definition at line 1034 of file qFacets.cpp.
References FacetsExportDlg::ASCII_FILE_IO, FacetMetaData::center, ComputeFacetExtensions(), ecvFileUtils::defaultDocPath(), FacetMetaData::dip_deg, FacetMetaData::dipDir_deg, FacetMetaData::facetIndex, FacetMetaData::familyIndex, ccFacet::getContour(), GetFacetMetaData(), getFacetsInCurrentSelection(), FacetMetaData::normal, FacetMetaData::rms, ShowDisclaimer(), FacetMetaData::subfamilyIndex, FacetMetaData::surface, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
extractFacets()
void qFacets::extractFacets (CellsFusionDlg::Algorithm algo) protected
Uses the given algorithm to detect planar facets.
Definition at line 202 of file qFacets.cpp.
References ccPointCloud::addScalarField(), CellsFusionDlg::ALGO_FAST_MARCHING, CellsFusionDlg::ALGO_KD_TREE, cloudViewer::TrueKdTree::build(), cloudViewer::ScalarField::computeMinAndMax(), count, createFacets(), ccPointCloud::deleteScalarField(), error(), cloudViewer::AutoSegmentationTools::extractConnectedComponents(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), ccKdTreeForFacetExtraction::FuseCells(), ccHObject::getChildrenNumber(), cloudViewer::BoundingBoxTpl< T >::getMinBoxDim(), ccObject::getName(), ccGenericPointCloud::getOctree(), ccGenericPointCloud::getOwnBB(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), ccPointCloud::hasNormals(), CCShareable::link(), cloudViewer::DistanceComputationTools::MAX_DIST, cloudViewer::DistanceComputationTools::MAX_DIST_68_PERCENT, cloudViewer::DistanceComputationTools::MAX_DIST_95_PERCENT, cloudViewer::DistanceComputationTools::MAX_DIST_99_PERCENT, result, cloudViewer::DistanceComputationTools::RMS, s_errorMaxPerFacet, s_errorMeasureType, s_fmUseRetroProjectionError, s_kdTreeFusionMaxAngle_deg, s_kdTreeFusionMaxRelativeDistance, s_lastCloud, s_maxEdgeLength, s_minPointsPerFacet, s_octreeLevel, ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentScalarField(), ccObject::setName(), ShowDisclaimer(), ccDrawableObject::showSF(), cloudViewer::PointCloudTpl< T >::size(), and ccHObjectCaster::ToPointCloud().
Referenced by extractFacetsWithFM(), and fuseKdTreeCells().
extractFacetsWithFM
void qFacets::extractFacetsWithFM () protected slot
Uses Fast Marching to detect planar facets.
Definition at line 196 of file qFacets.cpp.
References CellsFusionDlg::ALGO_FAST_MARCHING, and extractFacets().
fuseKdTreeCells
void qFacets::fuseKdTreeCells () protected slot
Fuses the cells of a kd-tree to produces planar facets.
Definition at line 200 of file qFacets.cpp.
References CellsFusionDlg::ALGO_KD_TREE, and extractFacets().
getFacetsInCurrentSelection()
void qFacets::getFacetsInCurrentSelection (FacetSet & facets) const protected
Returns all the facets in the current selection.
Definition at line 557 of file qFacets.cpp.
References CV_TYPES::FACET, ccHObject::filterChildren(), and ccFacet::getContour().
Referenced by exportFacets(), and exportFacetsInfo().
showStereogram
void qFacets::showStereogram () protected slot
Displays the selected entity stereogram.
Definition at line 942 of file qFacets.cpp.
References CV_TYPES::HIERARCHY_OBJECT, StereogramDialog::init(), CV_TYPES::POINT_CLOUD, s_fcDlg, s_stereogramAngleStep, s_stereogramResolution_deg, and ShowDisclaimer().
Member Data Documentation
m_doClassifyFacetsByAngle
QAction* qFacets::m_doClassifyFacetsByAngle protected
Associated action.
Definition at line 105 of file qFacets.h.
m_doExportFacets
QAction* qFacets::m_doExportFacets protected
Associated action.
Definition at line 101 of file qFacets.h.
m_doExportFacetsInfo
QAction* qFacets::m_doExportFacetsInfo protected
Associated action.
Definition at line 103 of file qFacets.h.
m_doFuseKdTreeCells
QAction* qFacets::m_doFuseKdTreeCells protected
Associated action.
Definition at line 97 of file qFacets.h.
m_doShowStereogram
QAction* qFacets::m_doShowStereogram protected
Associated action.
Definition at line 107 of file qFacets.h.
m_fastMarchingExtraction
QAction* qFacets::m_fastMarchingExtraction protected
Associated action.
Definition at line 99 of file qFacets.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qFacets/include/qFacets.h
/root/ACloudViewer/plugins/core/Standard/qFacets/src/qFacets.cpp