ACloudViewer: QUIWidget Class Reference
QUIWidget Class Reference
#include <ecvUIManager.h>
Public Types
enum Widget {
Lab_Ico = 0 , BtnMenu = 1 , BtnMenu_Min = 2 , BtnMenu_Max = 3 ,
BtnMenu_Normal = 4 , BtnMenu_Close = 5
}
enum Style {
Style_Silvery = 0 , Style_Blue = 1 , Style_LightBlue = 2 , Style_DarkBlue = 3 ,
Style_Gray = 4 , Style_LightGray = 5 , Style_DarkGray = 6 , Style_Black = 7 ,
Style_LightBlack = 8 , Style_DarkBlack = 9 , Style_PSBlack = 10 , Style_FlatBlack = 11 ,
Style_FlatWhite = 12
}
Public Slots
void toggleFullScreen (bool state)
toggles full screen
void setIcon (QUIWidget::Widget widget, QChar str, quint32 size=9)
void setIconMain (QChar str, quint32 size=9)
void setPixmap (QUIWidget::Widget widget, const QString &file, const QSize &size=QSize(32, 32))
void setWindowLogo (const QString &icon)
void setVisible (QUIWidget::Widget widget, bool visible=true)
void setOnlyCloseBtn ()
void setTitleHeight (int height)
void setBtnWidth (int width)
void setTitle (const QString &title)
void setAlignment (Qt::Alignment alignment)
void setMinHide (bool minHide)
void setMainWidget (MainWindow *mainWidget)
Signals
void changeStyle (const QString &qssFile)
void closing ()
Public Member Functions
QUIWidget (QWidget *parent=0)
~QUIWidget ()
void createTrayMenu ()
QLabel * getLabIco () const
QLabel * getLabTitle () const
QToolButton * getBtnMenu () const
QPushButton * getBtnMenuMin () const
QPushButton * getBtnMenuMax () const
QPushButton * getBtnMenuMClose () const
Style getStyle () const
QString getTitle () const
Qt::Alignment getAlignment () const
QSize sizeHint () const
QSize minimumSizeHint () const
Static Public Member Functions
static int deskWidth ()
static int deskHeight ()
static QString appName ()
static QString appPath ()
static void newDir (const QString &dirName)
static void writeInfo (const QString &info, const QString &filePath="log")
static void setStyle (QUIWidget::Style style)
static void setStyle (QString &qssFile)
static void setStyle (const QString &qssFile, QString &paletteColor, QString &textColor)
static void setStyle (const QString &qssFile, QString &textColor, QString &panelColor, QString &borderColor, QString &normalColorStart, QString &normalColorEnd, QString &darkColorStart, QString &darkColorEnd, QString &highColor)
static void getQssColor (const QString &qss, QString &textColor, QString &panelColor, QString &borderColor, QString &normalColorStart, QString &normalColorEnd, QString &darkColorStart, QString &darkColorEnd, QString &highColor)
static void setFormInCenter (QWidget *frm)
static void setTranslator (const QString &qmFile=":/image/qt_zh_CN.qm")
static void setCode ()
static void sleep (int sec)
static void setSystemDateTime (const QString &year, const QString &month, const QString &day, const QString &hour, const QString &min, const QString &sec)
static void runWithSystem (const QString &strName, const QString &strPath, bool autoRun=true)
static bool isIP (const QString &ip)
static bool isMac (const QString &mac)
static bool isTel (const QString &tel)
static bool isEmail (const QString &email)
static int strHexToDecimal (const QString &strHex)
static int strDecimalToDecimal (const QString &strDecimal)
static int strBinToDecimal (const QString &strBin)
static QString strHexToStrBin (const QString &strHex)
static QString decimalToStrBin1 (int decimal)
static QString decimalToStrBin2 (int decimal)
static QString decimalToStrHex (int decimal)
static QByteArray intToByte (int i)
static int byteToInt (const QByteArray &data)
static QByteArray ushortToByte (ushort i)
static int byteToUShort (const QByteArray &data)
static QString getXorEncryptDecrypt (const QString &str, char key)
static uchar getOrCode (const QByteArray &data)
static uchar getCheckCode (const QByteArray &data)
static QString byteArrayToAsciiStr (const QByteArray &data)
static QByteArray hexStrToByteArray (const QString &str)
static char convertHexChar (char ch)
static QByteArray asciiStrToByteArray (const QString &str)
static QString byteArrayToHexStr (const QByteArray &data)
static QString getFileName (const QString &filter, QString defaultDir=QCoreApplication::applicationDirPath())
static QStringList getFileNames (const QString &filter, QString defaultDir=QCoreApplication::applicationDirPath())
static QString getFolderName ()
static QString getFileNameWithExtension (const QString &strFilePath)
static QStringList getFolderFileNames (const QStringList &filter)
static bool folderIsExist (const QString &strFolder)
static bool fileIsExist (const QString &strFile)
static bool copyFile (const QString &sourceFile, const QString &targetFile)
static void deleteDirectory (const QString &path)
static bool ipLive (const QString &ip, int port, int timeout=1000)
static QString getHtml (const QString &url)
static QString getNetIP (const QString &webCode)
static QString getLocalIP ()
static QString urlToIP (const QString &url)
static bool isWebOk ()
static void showMessageBoxInfo (const QString &info, int closeSec=0)
static void showMessageBoxError (const QString &info, int closeSec=0)
static int showMessageBoxQuestion (const QString &info)
static QString showInputBox (bool &ok, const QString &title, int type=0, int closeSec=0, QString defaultValue=QString(), bool pwd=false)
Properties
QString title
Qt::Alignment alignment
Detailed Description
Definition at line 48 of file ecvUIManager.h.
Member Enumeration Documentation
Style
enum QUIWidget::Style
Enumerator
Style_Silvery
Style_Blue
Style_LightBlue
Style_DarkBlue
Style_Gray
Style_LightGray
Style_DarkGray
Style_Black
Style_LightBlack
Style_DarkBlack
Style_PSBlack
Style_FlatBlack
Style_FlatWhite
Definition at line 69 of file ecvUIManager.h.
Widget
enum QUIWidget::Widget
Enumerator
Lab_Ico
BtnMenu
BtnMenu_Min
BtnMenu_Max
BtnMenu_Normal
BtnMenu_Close
Definition at line 59 of file ecvUIManager.h.
Constructor & Destructor Documentation
QUIWidget()
QUIWidget::QUIWidget (QWidget * parent = 0) explicit
Definition at line 1110 of file ecvUIManager.cpp.
~QUIWidget()
QUIWidget::~QUIWidget ()
Definition at line 1115 of file ecvUIManager.cpp.
Member Function Documentation
appName()
QString QUIWidget::appName () static
Definition at line 30 of file ecvUIManager.cpp.
References name.
Referenced by writeInfo().
appPath()
QString QUIWidget::appPath () static
Definition at line 37 of file ecvUIManager.cpp.
Referenced by newDir(), and writeInfo().
asciiStrToByteArray()
QByteArray QUIWidget::asciiStrToByteArray (const QString & str) static
Definition at line 659 of file ecvUIManager.cpp.
References strHexToDecimal().
byteArrayToAsciiStr()
QString QUIWidget::byteArrayToAsciiStr (const QByteArray & data) static
Definition at line 520 of file ecvUIManager.cpp.
References data, and decimalToStrHex().
byteArrayToHexStr()
QString QUIWidget::byteArrayToHexStr (const QByteArray & data) static
Definition at line 938 of file ecvUIManager.cpp.
References data.
byteToInt()
int QUIWidget::byteToInt (const QByteArray & data) static
Definition at line 465 of file ecvUIManager.cpp.
References data.
byteToUShort()
int QUIWidget::byteToUShort (const QByteArray & data) static
Definition at line 481 of file ecvUIManager.cpp.
References data.
changeStyle
void QUIWidget::changeStyle (const QString & qssFile) signal
closing
void QUIWidget::closing () signal
convertHexChar()
char QUIWidget::convertHexChar (char ch) static
Definition at line 647 of file ecvUIManager.cpp.
Referenced by hexStrToByteArray().
copyFile()
bool QUIWidget::copyFile (const QString & sourceFile, const QString & targetFile) static
Definition at line 994 of file ecvUIManager.cpp.
References copy.
createTrayMenu()
void QUIWidget::createTrayMenu ()
Definition at line 1317 of file ecvUIManager.cpp.
References Settings::APP_LOGO, and Settings::TITLE.
Referenced by main().
decimalToStrBin1()
QString QUIWidget::decimalToStrBin1 (int decimal) static
Definition at line 419 of file ecvUIManager.cpp.
decimalToStrBin2()
QString QUIWidget::decimalToStrBin2 (int decimal) static
Definition at line 432 of file ecvUIManager.cpp.
decimalToStrHex()
QString QUIWidget::decimalToStrHex (int decimal) static
Definition at line 445 of file ecvUIManager.cpp.
Referenced by byteArrayToAsciiStr().
deleteDirectory()
void QUIWidget::deleteDirectory (const QString & path) static
Definition at line 1002 of file ecvUIManager.cpp.
References cloudViewer::t::geometry::path.
deskHeight()
int QUIWidget::deskHeight () static
Definition at line 25 of file ecvUIManager.cpp.
Referenced by setFormInCenter().
deskWidth()
int QUIWidget::deskWidth () static
Definition at line 20 of file ecvUIManager.cpp.
Referenced by setFormInCenter().
fileIsExist()
bool QUIWidget::fileIsExist (const QString & strFile) static
Definition at line 989 of file ecvUIManager.cpp.
folderIsExist()
bool QUIWidget::folderIsExist (const QString & strFolder) static
Definition at line 984 of file ecvUIManager.cpp.
getAlignment()
Qt::Alignment QUIWidget::getAlignment () const
Definition at line 1131 of file ecvUIManager.cpp.
References alignment.
getBtnMenu()
QToolButton * QUIWidget::getBtnMenu () const
Definition at line 1121 of file ecvUIManager.cpp.
getBtnMenuMax()
QPushButton * QUIWidget::getBtnMenuMax () const
Definition at line 1125 of file ecvUIManager.cpp.
getBtnMenuMClose()
QPushButton * QUIWidget::getBtnMenuMClose () const
Definition at line 1127 of file ecvUIManager.cpp.
getBtnMenuMin()
QPushButton * QUIWidget::getBtnMenuMin () const
Definition at line 1123 of file ecvUIManager.cpp.
getCheckCode()
uchar QUIWidget::getCheckCode (const QByteArray & data) static
Definition at line 509 of file ecvUIManager.cpp.
References data.
getFileName()
QString QUIWidget::getFileName (const QString & filter, QString defaultDir = QCoreApplication::applicationDirPath()) static
Definition at line 949 of file ecvUIManager.cpp.
getFileNames()
QStringList QUIWidget::getFileNames (const QString & filter, QString defaultDir = QCoreApplication::applicationDirPath()) static
Definition at line 954 of file ecvUIManager.cpp.
getFileNameWithExtension()
QString QUIWidget::getFileNameWithExtension (const QString & strFilePath) static
Definition at line 964 of file ecvUIManager.cpp.
getFolderFileNames()
QStringList QUIWidget::getFolderFileNames (const QStringList & filter) static
Definition at line 969 of file ecvUIManager.cpp.
getFolderName()
QString QUIWidget::getFolderName () static
Definition at line 959 of file ecvUIManager.cpp.
getHtml()
static QString QUIWidget::getHtml (const QString & url) static
getLabIco()
QLabel * QUIWidget::getLabIco () const
Definition at line 1117 of file ecvUIManager.cpp.
getLabTitle()
QLabel * QUIWidget::getLabTitle () const
Definition at line 1119 of file ecvUIManager.cpp.
getLocalIP()
static QString QUIWidget::getLocalIP () static
getNetIP()
static QString QUIWidget::getNetIP (const QString & webCode) static
getOrCode()
uchar QUIWidget::getOrCode (const QByteArray & data) static
Definition at line 498 of file ecvUIManager.cpp.
References data, and result.
getQssColor()
void QUIWidget::getQssColor (const QString & qss, QString & textColor, QString & panelColor, QString & borderColor, QString & normalColorStart, QString & normalColorEnd, QString & darkColorStart, QString & darkColorEnd, QString & highColor) static
Definition at line 164 of file ecvUIManager.cpp.
Referenced by setStyle().
getStyle()
Style QUIWidget::getStyle () const
getTitle()
QString QUIWidget::getTitle () const
Definition at line 1129 of file ecvUIManager.cpp.
References title.
getXorEncryptDecrypt()
QString QUIWidget::getXorEncryptDecrypt (const QString & str, char key) static
Definition at line 487 of file ecvUIManager.cpp.
References data, and size.
hexStrToByteArray()
QByteArray QUIWidget::hexStrToByteArray (const QString & str) static
Definition at line 606 of file ecvUIManager.cpp.
References convertHexChar().
intToByte()
QByteArray QUIWidget::intToByte (int i) static
Definition at line 455 of file ecvUIManager.cpp.
References result.
ipLive()
static bool QUIWidget::ipLive (const QString & ip, int port, int timeout = 1000) static
isEmail()
bool QUIWidget::isEmail (const QString & email) static
Definition at line 382 of file ecvUIManager.cpp.
isIP()
bool QUIWidget::isIP (const QString & ip) static
Definition at line 345 of file ecvUIManager.cpp.
isMac()
bool QUIWidget::isMac (const QString & mac) static
Definition at line 358 of file ecvUIManager.cpp.
isTel()
bool QUIWidget::isTel (const QString & tel) static
Definition at line 369 of file ecvUIManager.cpp.
isWebOk()
static bool QUIWidget::isWebOk () static
minimumSizeHint()
QSize QUIWidget::minimumSizeHint () const
Definition at line 1135 of file ecvUIManager.cpp.
newDir()
void QUIWidget::newDir (const QString & dirName) static
Definition at line 46 of file ecvUIManager.cpp.
References appPath().
runWithSystem()
void QUIWidget::runWithSystem (const QString & strName, const QString & strPath, bool autoRun = true) static
Definition at line 328 of file ecvUIManager.cpp.
setAlignment
void QUIWidget::setAlignment (Qt::Alignment alignment) slot
Definition at line 1528 of file ecvUIManager.cpp.
References alignment.
Referenced by main().
setBtnWidth
void QUIWidget::setBtnWidth (int width) slot
Definition at line 1512 of file ecvUIManager.cpp.
References width.
setCode()
void QUIWidget::setCode () static
Definition at line 257 of file ecvUIManager.cpp.
References QTextCodec::codecForName().
Referenced by main().
setFormInCenter()
void QUIWidget::setFormInCenter (QWidget * frm) static
Definition at line 236 of file ecvUIManager.cpp.
References deskHeight(), and deskWidth().
setIcon
void QUIWidget::setIcon (QUIWidget::Widget widget, QChar str, quint32 size = 9) slot
Definition at line 1434 of file ecvUIManager.cpp.
References BtnMenu, BtnMenu_Close, BtnMenu_Max, BtnMenu_Min, BtnMenu_Normal, QUIConfig::IconClose, QUIConfig::IconMax, QUIConfig::IconMenu, QUIConfig::IconMin, QUIConfig::IconNormal, IconHelper::Instance(), Lab_Ico, IconHelper::setIcon(), setIconMain(), and size.
setIconMain
void QUIWidget::setIconMain (QChar str, quint32 size = 9) slot
Definition at line 1455 of file ecvUIManager.cpp.
References QUIConfig::IconMain, QUIMessageBox::Instance(), QUIInputBox::Instance(), IconHelper::Instance(), IconHelper::setIcon(), QUIMessageBox::setIconMain(), QUIInputBox::setIconMain(), and size.
Referenced by setIcon().
setMainWidget
void QUIWidget::setMainWidget (MainWindow * mainWidget) slot
Definition at line 1541 of file ecvUIManager.cpp.
Referenced by main().
setMinHide
void QUIWidget::setMinHide (bool minHide) slot
Definition at line 1535 of file ecvUIManager.cpp.
setOnlyCloseBtn
void QUIWidget::setOnlyCloseBtn () slot
Definition at line 1502 of file ecvUIManager.cpp.
setPixmap
void QUIWidget::setPixmap (QUIWidget::Widget widget, const QString & file, const QSize & size = QSize(32, 32)) slot
Definition at line 1468 of file ecvUIManager.cpp.
References BtnMenu, BtnMenu_Close, BtnMenu_Max, BtnMenu_Min, Lab_Ico, and size.
Referenced by main().
setStyle() [1/4]
void QUIWidget::setStyle (const QString & qssFile, QString & paletteColor, QString & textColor) static
Definition at line 128 of file ecvUIManager.cpp.
setStyle() [2/4]
void QUIWidget::setStyle (const QString & qssFile, QString & textColor, QString & panelColor, QString & borderColor, QString & normalColorStart, QString & normalColorEnd, QString & darkColorStart, QString & darkColorEnd, QString & highColor) static
Definition at line 143 of file ecvUIManager.cpp.
References getQssColor().
setStyle() [3/4]
void QUIWidget::setStyle (QString & qssFile) static
Definition at line 116 of file ecvUIManager.cpp.
setStyle() [4/4]
void QUIWidget::setStyle (QUIWidget::Style style) static
Definition at line 82 of file ecvUIManager.cpp.
References Style_Black, Style_Blue, Style_DarkBlack, Style_DarkBlue, Style_DarkGray, Style_FlatBlack, Style_FlatWhite, Style_Gray, Style_LightBlack, Style_LightBlue, Style_LightGray, Style_PSBlack, and Style_Silvery.
Referenced by main().
setSystemDateTime()
void QUIWidget::setSystemDateTime (const QString & year, const QString & month, const QString & day, const QString & hour, const QString & min, const QString & sec) static
Definition at line 285 of file ecvUIManager.cpp.
setTitle
void QUIWidget::setTitle (const QString & title) slot
Definition at line 1520 of file ecvUIManager.cpp.
References title.
Referenced by main().
setTitleHeight
void QUIWidget::setTitleHeight (int height) slot
Definition at line 1508 of file ecvUIManager.cpp.
References height.
setTranslator()
void QUIWidget::setTranslator (const QString & qmFile = ":/image/qt_zh_CN.qm") static
Definition at line 251 of file ecvUIManager.cpp.
setVisible
void QUIWidget::setVisible (QUIWidget::Widget widget, bool visible = true) slot
Definition at line 1488 of file ecvUIManager.cpp.
References BtnMenu, BtnMenu_Close, BtnMenu_Max, BtnMenu_Min, and Lab_Ico.
Referenced by main().
setWindowLogo
void QUIWidget::setWindowLogo (const QString & icon) slot
Definition at line 1462 of file ecvUIManager.cpp.
showInputBox()
QString QUIWidget::showInputBox (bool & ok, const QString & title, int type = 0, int closeSec = 0, QString defaultValue = QString(), bool pwd = false) static
Definition at line 1098 of file ecvUIManager.cpp.
References QUIInputBox::getValue(), QUIInputBox::setParameter(), title, and type.
showMessageBoxError()
void QUIWidget::showMessageBoxError (const QString & info, int closeSec = 0) static
Definition at line 1087 of file ecvUIManager.cpp.
References QUIMessageBox::Instance(), and QUIMessageBox::setMessage().
showMessageBoxInfo()
void QUIWidget::showMessageBoxInfo (const QString & info, int closeSec = 0) static
Definition at line 1082 of file ecvUIManager.cpp.
References QUIMessageBox::Instance(), and QUIMessageBox::setMessage().
showMessageBoxQuestion()
int QUIWidget::showMessageBoxQuestion (const QString & info) static
Definition at line 1092 of file ecvUIManager.cpp.
References QUIMessageBox::setMessage().
sizeHint()
QSize QUIWidget::sizeHint () const
Definition at line 1133 of file ecvUIManager.cpp.
sleep()
void QUIWidget::sleep (int sec) static
Definition at line 277 of file ecvUIManager.cpp.
strBinToDecimal()
int QUIWidget::strBinToDecimal (const QString & strBin) static
Definition at line 400 of file ecvUIManager.cpp.
strDecimalToDecimal()
int QUIWidget::strDecimalToDecimal (const QString & strDecimal) static
Definition at line 395 of file ecvUIManager.cpp.
strHexToDecimal()
int QUIWidget::strHexToDecimal (const QString & strHex) static
Definition at line 390 of file ecvUIManager.cpp.
Referenced by asciiStrToByteArray(), and strHexToStrBin().
strHexToStrBin()
QString QUIWidget::strHexToStrBin (const QString & strHex) static
Definition at line 405 of file ecvUIManager.cpp.
References strHexToDecimal().
toggleFullScreen
void QUIWidget::toggleFullScreen (bool state) slot
toggles full screen
Definition at line 74 of file ecvUIManager.cpp.
urlToIP()
static QString QUIWidget::urlToIP (const QString & url) static
ushortToByte()
QByteArray QUIWidget::ushortToByte (ushort i) static
Definition at line 473 of file ecvUIManager.cpp.
References result.
writeInfo()
void QUIWidget::writeInfo (const QString & info, const QString & filePath = "log") static
Definition at line 60 of file ecvUIManager.cpp.
References cloudViewer::core::Append(), appName(), appPath(), DATETIME, and NEWLINE.
Property Documentation
alignment
Qt::Alignment QUIWidget::alignment read write
Definition at line 1 of file ecvUIManager.h.
Referenced by getAlignment(), and setAlignment().
title
QString QUIWidget::title read write
Definition at line 1 of file ecvUIManager.h.
Referenced by getTitle(), setTitle(), and showInputBox().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvUIManager.h
/root/ACloudViewer/app/ecvUIManager.cpp