ACloudViewer: ColorScaleElementSliders Class Reference
ColorScaleElementSliders Class Reference
Set of color scale elements (widgets)
#include <ecvColorScaleEditorWidget.h>
Public Member Functions
void addSlider (ColorScaleElementSlider *slider)
Adds a slider element and sort the whole set.
void sort ()
Sorts the set.
void clear ()
Remove all sliders.
void removeAt (int i)
Remove a given slider.
int selected () const
Returns the currently selected slider index (or -1 if none)
int indexOf (ColorScaleElementSlider *slider)
Returns the index of a given slider.
Detailed Description
Set of color scale elements (widgets)
Definition at line 58 of file ecvColorScaleEditorWidget.h.
Member Function Documentation
addSlider()
void ColorScaleElementSliders::addSlider (ColorScaleElementSlider * slider)
Adds a slider element and sort the whole set.
Should be used instead of push_back/push_front!
Definition at line 77 of file ecvColorScaleEditorWidget.cpp.
References sort().
clear()
void ColorScaleElementSliders::clear (void)
Remove all sliders.
Definition at line 90 of file ecvColorScaleEditorWidget.cpp.
indexOf()
int ColorScaleElementSliders::indexOf (ColorScaleElementSlider * slider)
Returns the index of a given slider.
Definition at line 121 of file ecvColorScaleEditorWidget.cpp.
References ecvColor::LookUpTable::at(), and size.
removeAt()
void ColorScaleElementSliders::removeAt (int i)
Remove a given slider.
Definition at line 98 of file ecvColorScaleEditorWidget.cpp.
References ecvColor::LookUpTable::at(), and size.
selected()
int ColorScaleElementSliders::selected () const
Returns the currently selected slider index (or -1 if none)
Definition at line 114 of file ecvColorScaleEditorWidget.cpp.
References ecvColor::LookUpTable::at(), and size.
sort()
void ColorScaleElementSliders::sort ()
Sorts the set.
Definition at line 86 of file ecvColorScaleEditorWidget.cpp.
References ColorScaleElementSlider::IsSmaller().
Referenced by addSlider().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVPluginAPI/include/ecvColorScaleEditorWidget.h
/root/ACloudViewer/libs/CVPluginAPI/src/ecvColorScaleEditorWidget.cpp