ACloudViewer: ccExternalFactory::Container Class Reference
ccExternalFactory::Container Class Reference
A convenience holder for all factories.
#include <ecvExternalFactory.h>
Public Types
typedef QSharedPointer< Container > Shared
Shared pointer type.
Public Member Functions
Container ()
Default constructor.
ccExternalFactory * getFactoryByName (const QString &factoryName) const
Returns factory using its (unique) name as key.
void addFactory (ccExternalFactory *factory)
Adds a new factory to the container.
Static Public Member Functions
static Container::Shared GetUniqueInstance ()
static void SetUniqueInstance (Container::Shared container)
Sets the unqiue static instance of the external factories container.
Protected Attributes
QMap< QString, ccExternalFactory * > m_factories
Set of factories.
Detailed Description
A convenience holder for all factories.
Definition at line 25 of file ecvExternalFactory.h.
Member Typedef Documentation
Shared
typedef QSharedPointer<Container> ccExternalFactory::Container::Shared
Shared pointer type.
Definition at line 43 of file ecvExternalFactory.h.
Constructor & Destructor Documentation
Container()
ccExternalFactory::Container::Container () inline
Default constructor.
Definition at line 28 of file ecvExternalFactory.h.
Member Function Documentation
addFactory()
void ccExternalFactory::Container::addFactory (ccExternalFactory * factory)
Adds a new factory to the container.
Any previously existing factory with the same name will be overwritten.
Definition at line 25 of file ecvExternalFactory.cpp.
References ccExternalFactory::getFactoryName(), and name.
getFactoryByName()
ccExternalFactory * ccExternalFactory::Container::getFactoryByName (const QString & factoryName) const
Returns factory using its (unique) name as key.
Parameters
factoryName unique name
Returns
corresponding factory (or null pointer if not found)
Definition at line 17 of file ecvExternalFactory.cpp.
References m_factories.
GetUniqueInstance()
ccExternalFactory::Container::Shared ccExternalFactory::Container::GetUniqueInstance () static
Returns the unqiue static instance of the external factories container
Definition at line 35 of file ecvExternalFactory.cpp.
References s_externalFactoryContainer().
Referenced by ccPluginManager::loadPlugins(), and ccHObject::New().
SetUniqueInstance()
void ccExternalFactory::Container::SetUniqueInstance (Container::Shared container) static
Sets the unqiue static instance of the external factories container.
A default static instance is provided for convenience but another user defined instance can be declared here instead.
Definition at line 43 of file ecvExternalFactory.cpp.
References s_externalFactoryContainer().
Member Data Documentation
m_factories
QMap<QString, ccExternalFactory*> ccExternalFactory::Container::m_factories protected
Set of factories.
Definition at line 57 of file ecvExternalFactory.h.
Referenced by getFactoryByName().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/ecvExternalFactory.h
/root/ACloudViewer/libs/CV_db/src/ecvExternalFactory.cpp