ACloudViewer: qCork Class Reference
qCork Class Reference
Mes Boolean Operations (CSG) plugin.
#include <qCork.h>
Protected Slots
void doAction ()
Starts main action.
Protected Attributes
QAction * m_action
Associated action.
Detailed Description
Mes Boolean Operations (CSG) plugin.
This plugin is based on Cork: https://github.com/gilbo/cork Required implementation is CC's dedicated fork: https://github.com/cloudcompare/cork
Definition at line 22 of file qCork.h.
Member Function Documentation
doAction
void qCork::doAction () protected slot
Starts main action.
Definition at line 289 of file qCork.cpp.
References BoolOpParameters::app, BoolOpParameters::corkA, BoolOpParameters::corkB, ccCorkDlg::DIFF, doPerformBooleanOp(), FromCorkMesh(), ccObject::getName(), ccCorkDlg::getSelectedOperation(), ccMesh::hasNormals(), ccMesh::hasTriNormals(), ccCorkDlg::INTERSECT, ccCorkDlg::isSwapped(), CV_TYPES::MESH, BoolOpParameters::meshesAreOk, BoolOpParameters::nameA, BoolOpParameters::nameB, ccMesh::normalsShown(), BoolOpParameters::operation, result, s_params, ccObject::setEnabled(), ccCorkDlg::setNames(), ccGenericMesh::showNormals(), cloudViewer::utility::Sleep(), std::swap(), ccCorkDlg::SYM_DIFF, ToCorkMesh(), and ccCorkDlg::UNION.
Member Data Documentation
m_action
QAction* qCork::m_action protected
Associated action.
Definition at line 43 of file qCork.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCork/include/qCork.h
/root/ACloudViewer/plugins/core/Standard/qCork/src/qCork.cpp