ACloudViewer: flann::BoundedHeap< T > Class Template Reference
flann::BoundedHeap< T > Class Template Reference
#include <heap.h>
Public Member Functions
BoundedHeap (size_t capacity)
int size ()
bool empty ()
void clear ()
void insert (const T &value)
bool popMin (T &value)
Detailed Description
template<typename T>
class flann::BoundedHeap< T >
Definition at line 402 of file heap.h.
Constructor & Destructor Documentation
BoundedHeap()
template<typename T > flann::BoundedHeap< T >::BoundedHeap (size_t capacity) inline
Definition at line 407 of file heap.h.
Member Function Documentation
clear()
template<typename T > void flann::BoundedHeap< T >::clear () inline
Clears the heap.
Definition at line 432 of file heap.h.
References flann::IntervalHeap< T >::clear().
empty()
template<typename T > bool flann::BoundedHeap< T >::empty () inline
Tests if the heap is empty Returns: true is heap empty, false otherwise
Definition at line 424 of file heap.h.
References flann::IntervalHeap< T >::empty().
insert()
template<typename T > void flann::BoundedHeap< T >::insert (const T & value) inline
Definition at line 437 of file heap.h.
References flann::IntervalHeap< T >::getMax(), flann::IntervalHeap< T >::insert(), max(), flann::IntervalHeap< T >::popMax(), and flann::IntervalHeap< T >::size().
popMin()
template<typename T > bool flann::BoundedHeap< T >::popMin (T & value) inline
Definition at line 448 of file heap.h.
References flann::IntervalHeap< T >::popMin().
size()
template<typename T > int flann::BoundedHeap< T >::size () inline
Returns: heap size
Definition at line 415 of file heap.h.
References flann::IntervalHeap< T >::size().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/util/heap.h