ACloudViewer: PdmsTools::PdmsCommands::Coordinates Class Reference
PdmsTools::PdmsCommands::Coordinates Class Reference
#include <PdmsTools.h>
Public Member Functions
Coordinates (Token t=PDMS_INVALID_TOKEN)
virtual bool handle (Token t)
virtual bool handle (PointCoordinateType numvalue)
virtual bool isValid () const
bool getVector (CCVector3 &u) const
int getNbComponents (bool onlyset=false) const
Public Member Functions inherited from PdmsTools::PdmsCommands::Command
Command (Token t)
Command (const Command &com)
virtual ~Command ()
virtual bool handle (const char *str)
virtual bool execute (PdmsObjects::GenericItem *&item) const
Public Attributes
DistanceValue coords [3]
int current
Public Attributes inherited from PdmsTools::PdmsCommands::Command
Token command
Additional Inherited Members
Static Public Member Functions inherited from PdmsTools::PdmsCommands::Command
static Command * Create (Token t)
Factory.
Detailed Description
Definition at line 548 of file PdmsTools.h.
Constructor & Destructor Documentation
Coordinates()
PdmsTools::PdmsCommands::Coordinates::Coordinates (Token t = PDMS_INVALID_TOKEN) inline explicit
Definition at line 553 of file PdmsTools.h.
References current.
Member Function Documentation
getNbComponents()
int Coordinates::getNbComponents (bool onlyset = false) const
Definition at line 312 of file PdmsTools.cpp.
References PdmsTools::PdmsToken::isCoordinate().
Referenced by PdmsTools::PdmsCommands::Orientation::axisFromCoords().
getVector()
bool Coordinates::getVector (CCVector3 & u) const
Definition at line 263 of file PdmsTools.cpp.
References PdmsTools::PDMS_DOWN, PdmsTools::PDMS_EST, PdmsTools::PDMS_NORTH, PdmsTools::PDMS_SOUTH, PdmsTools::PDMS_UP, PdmsTools::PDMS_WEST, PdmsTools::PDMS_X, PdmsTools::PDMS_Y, and PdmsTools::PDMS_Z.
Referenced by PdmsTools::PdmsCommands::Orientation::axisFromCoords().
handle() [1/2]
bool Coordinates::handle (PointCoordinateType numvalue) virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 249 of file PdmsTools.cpp.
References PdmsTools::PdmsToken::isCoordinate().
handle() [2/2]
bool Coordinates::handle (Token t) virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 227 of file PdmsTools.cpp.
References PdmsTools::PdmsToken::isCoordinate().
isValid()
bool Coordinates::isValid () const virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 258 of file PdmsTools.cpp.
Member Data Documentation
coords
DistanceValue PdmsTools::PdmsCommands::Coordinates::coords[3]
Definition at line 550 of file PdmsTools.h.
current
int PdmsTools::PdmsCommands::Coordinates::current
Definition at line 551 of file PdmsTools.h.
Referenced by Coordinates().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsTools.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsTools.cpp