ACloudViewer: cloudViewer::visualization::gui::LUTTreeCell Class Reference
cloudViewer::visualization::gui::LUTTreeCell Class Reference
#include <TreeView.h>
Classes
struct Impl
Public Member Functions
LUTTreeCell (const char *text, bool is_checked, const Color &color, std::function< void(bool)> on_enabled, std::function< void(const Color &)> on_color_changed)
~LUTTreeCell ()
std::shared_ptr< Checkbox > GetCheckbox ()
std::shared_ptr< Label > GetLabel ()
std::shared_ptr< ColorEdit > GetColorEdit ()
Size CalcPreferredSize (const LayoutContext &context, const Constraints &constraints) const override
void Layout (const LayoutContext &context) override
Public Member Functions inherited from cloudViewer::visualization::gui::Widget
Widget ()
Widget (const std::vector< std::shared_ptr< Widget >> &children)
virtual ~Widget ()
virtual void AddChild (std::shared_ptr< Widget > child)
virtual const std::vector< std::shared_ptr< Widget > > GetChildren () const
virtual const Rect & GetFrame () const
Returns the frame size in pixels.
virtual void SetFrame (const Rect &f)
virtual const Color & GetBackgroundColor () const
virtual bool IsDefaultBackgroundColor () const
virtual void SetBackgroundColor (const Color &color)
virtual bool IsVisible () const
virtual void SetVisible (bool vis)
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
virtual void SetTooltip (const char *text)
virtual const char * GetTooltip () const
virtual Size CalcMinimumSize (const LayoutContext &context) const
virtual DrawResult Draw (const DrawContext &context)
virtual EventResult Mouse (const MouseEvent &e)
virtual EventResult Key (const KeyEvent &e)
virtual DrawResult Tick (const TickEvent &e)
Additional Inherited Members
Public Types inherited from cloudViewer::visualization::gui::Widget
enum class DrawResult { NONE , REDRAW , RELAYOUT }
enum class EventResult { IGNORED , CONSUMED , DISCARD }
Static Public Attributes inherited from cloudViewer::visualization::gui::Widget
static constexpr int DIM_GROW = 10000
Protected Member Functions inherited from cloudViewer::visualization::gui::Widget
void DrawImGuiPushEnabledState ()
void DrawImGuiPopEnabledState ()
void DrawImGuiTooltip ()
Detailed Description
Definition at line 47 of file TreeView.h.
Constructor & Destructor Documentation
LUTTreeCell()
cloudViewer::visualization::gui::LUTTreeCell::LUTTreeCell (const char * text, bool is_checked, const Color & color, std::function< void(bool)> on_enabled, std::function< void(const Color &)> on_color_changed)
Definition at line 84 of file TreeView.cpp.
References cloudViewer::visualization::gui::Widget::AddChild(), and color.
~LUTTreeCell()
cloudViewer::visualization::gui::LUTTreeCell::~LUTTreeCell ()
Definition at line 105 of file TreeView.cpp.
Member Function Documentation
CalcPreferredSize()
Size cloudViewer::visualization::gui::LUTTreeCell::CalcPreferredSize (const LayoutContext & context, const Constraints & constraints) const override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 115 of file TreeView.cpp.
References context, and max().
GetCheckbox()
std::shared_ptr< Checkbox > cloudViewer::visualization::gui::LUTTreeCell::GetCheckbox ()
Definition at line 107 of file TreeView.cpp.
GetColorEdit()
std::shared_ptr< ColorEdit > cloudViewer::visualization::gui::LUTTreeCell::GetColorEdit ()
Definition at line 113 of file TreeView.cpp.
GetLabel()
std::shared_ptr< Label > cloudViewer::visualization::gui::LUTTreeCell::GetLabel ()
Definition at line 111 of file TreeView.cpp.
Layout()
void cloudViewer::visualization::gui::LUTTreeCell::Layout (const LayoutContext & context) override virtual
Reimplemented from cloudViewer::visualization::gui::Widget.
Definition at line 125 of file TreeView.cpp.
References cloudViewer::utility::ceil(), context, frame, cloudViewer::visualization::gui::Widget::GetFrame(), and max().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/TreeView.h
/root/ACloudViewer/libs/cloudViewer/visualization/gui/TreeView.cpp