ACloudViewer: CoredVectorMeshData< Vertex > Class Template Reference
CoredVectorMeshData< Vertex > Class Template Reference
#include <Geometry.h>
Public Member Functions
CoredVectorMeshData (void)
void resetIterator (void)
int addOutOfCorePoint (const Vertex &p)
int addOutOfCorePoint_s (const Vertex &p)
int addPolygon_s (const std::vector< CoredVertexIndex > &vertices)
int addPolygon_s (const std::vector< int > &vertices)
int nextOutOfCorePoint (Vertex &p)
int nextPolygon (std::vector< CoredVertexIndex > &vertices)
int outOfCorePointCount (void)
int polygonCount (void)
Additional Inherited Members
Public Attributes inherited from CoredMeshData< Vertex >
std::vector< Vertex > inCorePoints
Detailed Description
template<class Vertex>
class CoredVectorMeshData< Vertex >
Definition at line 320 of file Geometry.h.
Constructor & Destructor Documentation
CoredVectorMeshData()
template<class Vertex > CoredVectorMeshData< Vertex >::CoredVectorMeshData (void)
Member Function Documentation
addOutOfCorePoint()
template<class Vertex > int CoredVectorMeshData< Vertex >::addOutOfCorePoint (const Vertex & p) virtual
Implements CoredMeshData< Vertex >.
addOutOfCorePoint_s()
template<class Vertex > int CoredVectorMeshData< Vertex >::addOutOfCorePoint_s (const Vertex & p) virtual
Implements CoredMeshData< Vertex >.
addPolygon_s() [1/2]
template<class Vertex > int CoredVectorMeshData< Vertex >::addPolygon_s (const std::vector< CoredVertexIndex > & vertices) virtual
Implements CoredMeshData< Vertex >.
addPolygon_s() [2/2]
template<class Vertex > int CoredVectorMeshData< Vertex >::addPolygon_s (const std::vector< int > & vertices) virtual
Implements CoredMeshData< Vertex >.
nextOutOfCorePoint()
template<class Vertex > int CoredVectorMeshData< Vertex >::nextOutOfCorePoint (Vertex & p) virtual
Implements CoredMeshData< Vertex >.
Referenced by ExtractMesh().
nextPolygon()
template<class Vertex > int CoredVectorMeshData< Vertex >::nextPolygon (std::vector< CoredVertexIndex > & vertices) virtual
Implements CoredMeshData< Vertex >.
Referenced by ExtractMesh().
outOfCorePointCount()
template<class Vertex > int CoredVectorMeshData< Vertex >::outOfCorePointCount (void) virtual
Implements CoredMeshData< Vertex >.
Referenced by ExtractMesh().
polygonCount()
template<class Vertex > int CoredVectorMeshData< Vertex >::polygonCount (void) virtual
Implements CoredMeshData< Vertex >.
Referenced by ExtractMesh().
resetIterator()
template<class Vertex > void CoredVectorMeshData< Vertex >::resetIterator (void) virtual
Implements CoredMeshData< Vertex >.
Referenced by ExtractMesh().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/Geometry.h