ACloudViewer: VtkUtils::SignalledRunnable Class Reference
VtkUtils::SignalledRunnable Class Reference
#include <signalledrunable.h>
Signals
void finished ()
Public Member Functions
SignalledRunnable ()
Detailed Description
Definition at line 17 of file signalledrunable.h.
Constructor & Destructor Documentation
SignalledRunnable()
VtkUtils::SignalledRunnable::SignalledRunnable ()
Definition at line 12 of file signalledrunable.cpp.
Member Function Documentation
finished
void VtkUtils::SignalledRunnable::finished () signal
Referenced by VtkUtils::ImageProcessorTempl< T >::run(), VtkUtils::DataFilter< Filter, InputDataObject, OutputDataObject >::run(), VtkUtils::ModelToPointsConverter::run(), VtkUtils::ModelToVectorsConverter::run(), VtkUtils::ModelToVtkTableConverter::run(), VtkUtils::PointsReader::run(), VtkUtils::PointsToModelConverter::run(), and VtkUtils::PointsToPolyDataConverter::run().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/signalledrunable.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/signalledrunable.cpp