ACloudViewer: colmap::EssentialMatrixEightPointEstimator Class Reference
colmap::EssentialMatrixEightPointEstimator Class Reference
#include <essential_matrix.h>
Public Types
typedef Eigen::Vector2d X_t
typedef Eigen::Vector2d Y_t
typedef Eigen::Matrix3d M_t
Static Public Member Functions
static std::vector< M_t > Estimate (const std::vector< X_t > &points1, const std::vector< Y_t > &points2)
static void Residuals (const std::vector< X_t > &points1, const std::vector< Y_t > &points2, const M_t &E, std::vector< double > *residuals)
Static Public Attributes
static const int kMinNumSamples = 8
Detailed Description
Definition at line 68 of file essential_matrix.h.
Member Typedef Documentation
M_t
typedef Eigen::Matrix3d colmap::EssentialMatrixEightPointEstimator::M_t
Definition at line 72 of file essential_matrix.h.
X_t
typedef Eigen::Vector2d colmap::EssentialMatrixEightPointEstimator::X_t
Definition at line 70 of file essential_matrix.h.
Y_t
typedef Eigen::Vector2d colmap::EssentialMatrixEightPointEstimator::Y_t
Definition at line 71 of file essential_matrix.h.
Member Function Documentation
Estimate()
std::vector< EssentialMatrixEightPointEstimator::M_t > colmap::EssentialMatrixEightPointEstimator::Estimate (const std::vector< X_t > & points1, const std::vector< Y_t > & points2) static
Definition at line 160 of file essential_matrix.cc.
References colmap::CenterAndNormalizeImagePoints(), x, and y.
Referenced by BOOST_AUTO_TEST_CASE().
Residuals()
void colmap::EssentialMatrixEightPointEstimator::Residuals (const std::vector< X_t > & points1, const std::vector< Y_t > & points2, const M_t & E, std::vector< double > * residuals) static
Definition at line 207 of file essential_matrix.cc.
References colmap::ComputeSquaredSampsonError().
Member Data Documentation
kMinNumSamples
const int colmap::EssentialMatrixEightPointEstimator::kMinNumSamples = 8 static
Definition at line 75 of file essential_matrix.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/estimators/essential_matrix.h
/root/ACloudViewer/libs/Reconstruction/src/estimators/essential_matrix.cc