ACloudViewer: QCPAbstractPlottable Class Reference
QCPAbstractPlottable Class Reference abstract
The abstract base class for all data representing objects in a plot.
#include <qcustomplot.h>
Signals
void selectionChanged (bool selected)
void selectionChanged (const QCPDataSelection &selection)
void selectableChanged (QCP::SelectionType selectable)
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
void layerChanged (QCPLayer *newLayer)
Public Member Functions
QCPAbstractPlottable (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPAbstractPlottable ()
QString name () const
bool antialiasedFill () const
bool antialiasedScatters () const
QPen pen () const
QBrush brush () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
QCP::SelectionType selectable () const
bool selected () const
QCPDataSelection selection () const
QCPSelectionDecorator * selectionDecorator () const
void setName (const QString &name)
void setAntialiasedFill (bool enabled)
void setAntialiasedScatters (bool enabled)
void setPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setKeyAxis (QCPAxis *axis)
void setValueAxis (QCPAxis *axis)
Q_SLOT void setSelectable (QCP::SelectionType selectable)
Q_SLOT void setSelection (QCPDataSelection selection)
void setSelectionDecorator (QCPSelectionDecorator *decorator)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const =0
virtual QCPPlottableInterface1D * interface1D ()
virtual QCPRange getKeyRange (bool &foundRange, QCP::SignDomain inSignDomain=QCP::sdBoth) const =0
virtual QCPRange getValueRange (bool &foundRange, QCP::SignDomain inSignDomain=QCP::sdBoth, const QCPRange &inKeyRange=QCPRange()) const =0
void coordsToPixels (double key, double value, double &x, double &y) const
const QPointF coordsToPixels (double key, double value) const
void pixelsToCoords (double x, double y, double &key, double &value) const
void pixelsToCoords (const QPointF &pixelPos, double &key, double &value) const
void rescaleAxes (bool onlyEnlarge=false) const
void rescaleKeyAxis (bool onlyEnlarge=false) const
void rescaleValueAxis (bool onlyEnlarge=false, bool inKeyRange=false) const
bool addToLegend (QCPLegend *legend)
bool addToLegend ()
bool removeFromLegend (QCPLegend *legend) const
bool removeFromLegend () const
QCPAbstractPlottable (QCPAxis *keyAxis, QCPAxis *valueAxis)
QString name () const
bool antialiasedFill () const
bool antialiasedScatters () const
bool antialiasedErrorBars () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
bool selectable () const
bool selected () const
void setName (const QString &name)
void setAntialiasedFill (bool enabled)
void setAntialiasedScatters (bool enabled)
void setAntialiasedErrorBars (bool enabled)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setKeyAxis (QCPAxis *axis)
void setValueAxis (QCPAxis *axis)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual void clearData ()=0
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const =0
virtual bool addToLegend ()
virtual bool removeFromLegend () const
void rescaleAxes (bool onlyEnlarge=false) const
void rescaleKeyAxis (bool onlyEnlarge=false) const
void rescaleValueAxis (bool onlyEnlarge=false) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
virtual ~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Protected Types
enum SignDomain { sdNegative , sdBoth , sdPositive }
Protected Member Functions
virtual QRect clipRect () const
virtual void draw (QCPPainter *painter)=0
virtual QCP::Interaction selectionCategory () const
void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const =0
void applyFillAntialiasingHint (QCPPainter *painter) const
void applyScattersAntialiasingHint (QCPPainter *painter) const
virtual QRect clipRect () const
virtual void draw (QCPPainter *painter)=0
virtual QCP::Interaction selectionCategory () const
void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const =0
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const =0
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const =0
void coordsToPixels (double key, double value, double &x, double &y) const
const QPointF coordsToPixels (double key, double value) const
void pixelsToCoords (double x, double y, double &key, double &value) const
void pixelsToCoords (const QPointF &pixelPos, double &key, double &value) const
QPen mainPen () const
QBrush mainBrush () const
void applyFillAntialiasingHint (QCPPainter *painter) const
void applyScattersAntialiasingHint (QCPPainter *painter) const
void applyErrorBarsAntialiasingHint (QCPPainter *painter) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual void mousePressEvent (QMouseEvent *event, const QVariant &details)
virtual void mouseMoveEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseReleaseEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseDoubleClickEvent (QMouseEvent *event, const QVariant &details)
virtual void wheelEvent (QWheelEvent *event)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QString mName
bool mAntialiasedFill
bool mAntialiasedScatters
QPen mPen
QBrush mBrush
QPointer< QCPAxis > mKeyAxis
QPointer< QCPAxis > mValueAxis
QCP::SelectionType mSelectable
QCPDataSelection mSelection
QCPSelectionDecorator * mSelectionDecorator
bool mAntialiasedErrorBars
QPen mSelectedPen
QBrush mSelectedBrush
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Detailed Description
The abstract base class for all data representing objects in a plot.
It defines a very basic interface like name, pen, brush, visibility etc. Since this class is abstract, it can't be instantiated. Use one of the subclasses or create a subclass yourself to create new ways of displaying data (see "Creating own plottables" below). Plottables that display one-dimensional data (i.e. data points have a single key dimension and one or multiple values at each key) are based off of the template subclass QCPAbstractPlottable1D, see details there.
All further specifics are in the subclasses, for example:
A normal graph with possibly a line and/or scatter points QCPGraph (typically created with QCustomPlot::addGraph)
A parametric curve: QCPCurve
A bar chart: QCPBars
A statistical box plot: QCPStatisticalBox
A color encoded two-dimensional map: QCPColorMap
An OHLC/Candlestick chart: QCPFinancial
Creating own plottables
Subclassing directly from QCPAbstractPlottable is only recommended if you wish to display two-dimensional data like QCPColorMap, i.e. two logical key dimensions and one (or more) data dimensions. If you want to display data with only one logical key dimension, you should rather derive from QCPAbstractPlottable1D.
If subclassing QCPAbstractPlottable directly, these are the pure virtual functions you must implement:
selectTest
draw
drawLegendIcon
getKeyRange
getValueRange
See the documentation of those functions for what they need to do.
For drawing your plot, you can use the coordsToPixels functions to translate a point in plot coordinates to pixel coordinates. This function is quite convenient, because it takes the orientation of the key and value axes into account for you (x and y are swapped when the key axis is vertical and the value axis horizontal). If you are worried about performance (i.e. you need to translate many points in a loop like QCPGraph), you can directly use QCPAxis::coordToPixel. However, you must then take care about the orientation of the axis yourself.
Here are some important members you inherit from QCPAbstractPlottable:
QCustomPlot *mParentPlot A pointer to the parent QCustomPlot instance. The parent plot is inferred from the axes that are passed in the constructor.
QString mName The name of the plottable.
QPen mPen The generic pen of the plottable. You should use this pen for the most prominent data representing lines in the plottable (e.g QCPGraph uses this pen for its graph lines and scatters)
QBrush mBrush The generic brush of the plottable. You should use this brush for the most prominent fillable structures in the plottable (e.g. QCPGraph uses this brush to control filling under the graph)
QPointer<QCPAxis> mKeyAxis, mValueAxis The key and value axes this plottable is attached to. Call their QCPAxis::coordToPixel functions to translate coordinates to pixels in either the key or value dimension. Make sure to check whether the pointer is null before using it. If one of the axes is null, don't draw the plottable.
QCPSelectionDecorator mSelectionDecorator The currently set selection decorator which specifies how selected data of the plottable shall be drawn and decorated. When drawing your data, you must consult this decorator for the appropriate pen/brush before drawing unselected/selected data segments. Finally, you should call its QCPSelectionDecorator::drawDecoration method at the end of your draw implementation.
QCP::SelectionType mSelectable In which composition, if at all, this plottable's data may be selected. Enforcing this setting on the data selection is done by QCPAbstractPlottable automatically.
QCPDataSelection mSelection Holds the current selection state of the plottable's data, i.e. the selected data ranges (QCPDataRange).
It defines a very basic interface like name, pen, brush, visibility etc. Since this class is abstract, it can't be instantiated. Use one of the subclasses or create a subclass yourself to create new ways of displaying data (see "Creating own plottables" below).
All further specifics are in the subclasses, for example:
A normal graph with possibly a line, scatter points and error bars: QCPGraph (typically created with QCustomPlot::addGraph)
A parametric curve: QCPCurve
A bar chart: QCPBars
A statistical box plot: QCPStatisticalBox
A color encoded two-dimensional map: QCPColorMap
An OHLC/Candlestick chart: QCPFinancial
Creating own plottables
To create an own plottable, you implement a subclass of QCPAbstractPlottable. These are the pure virtual functions, you must implement:
clearData
selectTest
draw
drawLegendIcon
getKeyRange
getValueRange
See the documentation of those functions for what they need to do.
For drawing your plot, you can use the coordsToPixels functions to translate a point in plot coordinates to pixel coordinates. This function is quite convenient, because it takes the orientation of the key and value axes into account for you (x and y are swapped when the key axis is vertical and the value axis horizontal). If you are worried about performance (i.e. you need to translate many points in a loop like QCPGraph), you can directly use QCPAxis::coordToPixel. However, you must then take care about the orientation of the axis yourself.
Here are some important members you inherit from QCPAbstractPlottable:
QCustomPlot *mParentPlot A pointer to the parent QCustomPlot instance. The parent plot is inferred from the axes that are passed in the constructor.
QString mName The name of the plottable.
QPen mPen The generic pen of the plottable. You should use this pen for the most prominent data representing lines in the plottable (e.g QCPGraph uses this pen for its graph lines and scatters)
QPen mSelectedPen The generic pen that should be used when the plottable is selected (hint: mainPen gives you the right pen, depending on selection state).
QBrush mBrush The generic brush of the plottable. You should use this brush for the most prominent fillable structures in the plottable (e.g. QCPGraph uses this brush to control filling under the graph)
QBrush mSelectedBrush The generic brush that should be used when the plottable is selected (hint: mainBrush gives you the right brush, depending on selection state).
QPointer<QCPAxis>mKeyAxis, mValueAxis The key and value axes this plottable is attached to. Call their QCPAxis::coordToPixel functions to translate coordinates to pixels in either the key or value dimension. Make sure to check whether the pointer is null before using it. If one of the axes is null, don't draw the plottable.
bool mSelected indicates whether the plottable is selected or not.
Definition at line 3816 of file qcustomplot.h.
Member Enumeration Documentation
SignDomain
enum QCPAbstractPlottable::SignDomain protected
Represents negative and positive sign domain for passing to getKeyRange and getValueRange.
Enumerator
sdNegative
The negative sign domain, i.e. numbers smaller than zero
sdBoth
Both sign domains, including zero, i.e. all (rational) numbers
sdPositive
The positive sign domain, i.e. numbers greater than zero
Definition at line 1749 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPAbstractPlottable() [1/2]
QCPAbstractPlottable::QCPAbstractPlottable (QCPAxis * keyAxis, QCPAxis * valueAxis)
Constructs an abstract plottable which uses keyAxis as its key axis ("x") and valueAxis as its value axis ("y"). keyAxis and valueAxis must reside in the same QCustomPlot instance and have perpendicular orientations. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
Since QCPAbstractPlottable is an abstract class that defines the basic interface to plottables, it can't be directly instantiated.
You probably want one of the subclasses like QCPGraph or QCPCurve instead.
Definition at line 11099 of file qcustomplot.cpp.
References keyAxis(), QCPLayerable::mParentPlot, QCPAxis::orientation(), QCPLayerable::parentPlot(), QCustomPlot::registerPlottable(), setSelectionDecorator(), and valueAxis().
~QCPAbstractPlottable()
QCPAbstractPlottable::~QCPAbstractPlottable () virtual
Definition at line 11122 of file qcustomplot.cpp.
References mSelectionDecorator.
QCPAbstractPlottable() [2/2]
QCPAbstractPlottable::QCPAbstractPlottable (QCPAxis * keyAxis, QCPAxis * valueAxis)
Member Function Documentation
addToLegend() [1/3]
bool QCPAbstractPlottable::addToLegend ()
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Adds this plottable to the legend of the parent QCustomPlot (QCustomPlot::legend).
See also
removeFromLegend
Adds this plottable to the legend of the parent QCustomPlot (QCustomPlot::legend).
Normally, a QCPPlottableLegendItem is created and inserted into the legend. If the plottable needs a more specialized representation in the legend, this function will take this into account and instead create the specialized subclass of QCPAbstractLegendItem.
Returns true on success, i.e. when the legend exists and a legend item associated with this plottable isn't already in the legend.
See also
removeFromLegend, QCPLegend::addItem
Definition at line 11540 of file qcustomplot.cpp.
References QCustomPlot::legend, and QCPLayerable::mParentPlot.
addToLegend() [2/3]
virtual bool QCPAbstractPlottable::addToLegend () virtual
addToLegend() [3/3]
bool QCPAbstractPlottable::addToLegend (QCPLegend * legend)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Adds this plottable to the specified legend.
Creates a QCPPlottableLegendItem which is inserted into the legend. Returns true on success, i.e. when the legend exists and a legend item associated with this plottable isn't already in the legend.
If the plottable needs a more specialized representation in the legend, you can create a corresponding subclass of QCPPlottableLegendItem and add it to the legend manually instead of calling this method.
See also
removeFromLegend, QCPLegend::addItem
Definition at line 11514 of file qcustomplot.cpp.
References QCPLegend::addItem(), QCPLegend::hasItemWithPlottable(), QCPLayerable::mParentPlot, QCPLayerable::parentPlot(), and QCPPlottableLegendItem.
Referenced by QCustomPlot::addPlottable(), and QCustomPlot::registerPlottable().
antialiasedErrorBars()
bool QCPAbstractPlottable::antialiasedErrorBars () const inline
Definition at line 1703 of file qcustomplot.h.
antialiasedFill() [1/2]
bool QCPAbstractPlottable::antialiasedFill () const inline
Definition at line 3841 of file qcustomplot.h.
antialiasedFill() [2/2]
bool QCPAbstractPlottable::antialiasedFill () const inline
Definition at line 1701 of file qcustomplot.h.
antialiasedScatters() [1/2]
bool QCPAbstractPlottable::antialiasedScatters () const inline
Definition at line 3842 of file qcustomplot.h.
antialiasedScatters() [2/2]
bool QCPAbstractPlottable::antialiasedScatters () const inline
Definition at line 1702 of file qcustomplot.h.
applyDefaultAntialiasingHint() [1/2]
void QCPAbstractPlottable::applyDefaultAntialiasingHint (QCPPainter * painter) const protected virtual
Implements QCPLayerable.
Definition at line 11612 of file qcustomplot.cpp.
References QCP::aePlottables, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
Referenced by QCPColoredBars::draw(), QCPBars::draw(), QCPColorMap::draw(), QCPErrorBars::draw(), QCPCurve::drawCurveLine(), QCPGraph::drawImpulsePlot(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPBars::drawLegendIcon(), QCPStatisticalBox::drawLegendIcon(), QCPColorMap::drawLegendIcon(), QCPErrorBars::drawLegendIcon(), QCPGraph::drawLinePlot(), QCPStatisticalBox::drawMedian(), QCPStatisticalBox::drawQuartileBox(), and QCPStatisticalBox::drawStatisticalBox().
applyDefaultAntialiasingHint() [2/2]
void QCPAbstractPlottable::applyDefaultAntialiasingHint (QCPPainter * painter) const protected virtual
Implements QCPLayerable.
applyErrorBarsAntialiasingHint()
void QCPAbstractPlottable::applyErrorBarsAntialiasingHint (QCPPainter * painter) const protected
Definition at line 7592 of file qcustomplot.cpp.
References QCP::aeErrorBars, QCPLayerable::applyAntialiasingHint(), and mAntialiasedErrorBars.
Referenced by QCPGraph::drawScatterPlot(), and QCPStatisticalBox::drawWhiskers().
applyFillAntialiasingHint() [1/2]
void QCPAbstractPlottable::applyFillAntialiasingHint (QCPPainter * painter) const protected
Definition at line 11629 of file qcustomplot.cpp.
References QCP::aeFills, QCPLayerable::applyAntialiasingHint(), and mAntialiasedFill.
Referenced by QCPColoredBars::draw(), QCPHiddenArea::draw(), QCPCurve::draw(), QCPGraph::drawFill(), QCPGraph::drawLegendIcon(), and QCPCurve::drawLegendIcon().
applyFillAntialiasingHint() [2/2]
void QCPAbstractPlottable::applyFillAntialiasingHint (QCPPainter * painter) const protected
applyScattersAntialiasingHint() [1/2]
void QCPAbstractPlottable::applyScattersAntialiasingHint (QCPPainter * painter) const protected
Definition at line 11645 of file qcustomplot.cpp.
References QCP::aeScatters, QCPLayerable::applyAntialiasingHint(), and mAntialiasedScatters.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPStatisticalBox::drawOutliers(), QCPCurve::drawScatterPlot(), QCPGraph::drawScatterPlot(), and QCPStatisticalBox::drawStatisticalBox().
applyScattersAntialiasingHint() [2/2]
void QCPAbstractPlottable::applyScattersAntialiasingHint (QCPPainter * painter) const protected
brush() [1/2]
QBrush QCPAbstractPlottable::brush () const inline
Definition at line 3844 of file qcustomplot.h.
Referenced by QCPColoredBars::draw(), QCPHiddenArea::draw(), QCPArrow::draw(), setBrush(), QCPFinancial::setBrushNegative(), QCPFinancial::setBrushPositive(), and setSelectedBrush().
brush() [2/2]
QBrush QCPAbstractPlottable::brush () const inline
Definition at line 1706 of file qcustomplot.h.
clearData()
void QCPAbstractPlottable::clearData () pure virtual
Clears all data in the plottable.
Implemented in QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPSelectableCursor, and QCPColoredBars.
clipRect() [1/2]
QRect QCPAbstractPlottable::clipRect () const protected virtual
Reimplemented from QCPLayerable.
Definition at line 11583 of file qcustomplot.cpp.
References mKeyAxis, and mValueAxis.
Referenced by QCPHiddenArea::draw(), QCPArrow::draw(), and QCPColoredBars::rect().
clipRect() [2/2]
virtual QRect QCPAbstractPlottable::clipRect () const protected virtual
Reimplemented from QCPLayerable.
coordsToPixels() [1/4]
const QPointF QCPAbstractPlottable::coordsToPixels (double key, double value) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Transforms the given key and value to pixel coordinates and returns them in a QPointF.
Definition at line 11322 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), keyAxis(), mKeyAxis, mValueAxis, QCPAxis::orientation(), and valueAxis().
coordsToPixels() [2/4]
const QPointF QCPAbstractPlottable::coordsToPixels (double key, double value) const protected
coordsToPixels() [3/4]
void QCPAbstractPlottable::coordsToPixels (double key, double value, double & x, double & y) const
Convenience function for transforming a key/value pair to pixels on the QCustomPlot surface, taking the orientations of the axes associated with this plottable into account (e.g. whether key represents x or y).
key and value are transformed to the coodinates in pixels and are written to x and y.
See also
pixelsToCoords, QCPAxis::coordToPixel
Definition at line 11297 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), keyAxis(), mKeyAxis, mValueAxis, QCPAxis::orientation(), valueAxis(), x, and y.
Referenced by QCPBarsWithText::draw(), QCPColorMap::draw(), QCPStatisticalBox::drawMedian(), QCPStatisticalBox::drawOutliers(), QCPStatisticalBox::drawQuartileBox(), QCPStatisticalBox::drawStatisticalBox(), QCPStatisticalBox::drawWhiskers(), QCPCurve::getCurveData(), QCPCurve::getCurveLines(), QCPCurve::getOptimizedCornerPoints(), QCPStatisticalBox::getQuartileBox(), QCPCurve::getTraverseCornerPoints(), QCPStatisticalBox::getWhiskerBackboneLines(), QCPStatisticalBox::getWhiskerBarLines(), QCPCurve::pointDistance(), and QCPGraph::pointDistance().
coordsToPixels() [4/4]
void QCPAbstractPlottable::coordsToPixels (double key, double value, double & x, double & y) const protected
deselectEvent() [1/2]
void QCPAbstractPlottable::deselectEvent (bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 11688 of file qcustomplot.cpp.
References mSelectable, mSelection, setSelection(), and QCP::stNone.
deselectEvent() [2/2]
virtual void QCPAbstractPlottable::deselectEvent (bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
distSqrToLine()
double QCPAbstractPlottable::distSqrToLine (const QPointF & start, const QPointF & end, const QPointF & point) const protected
Definition at line 7607 of file qcustomplot.cpp.
References a.
Referenced by QCPFinancial::candlestickSelectTest(), QCPFinancial::ohlcSelectTest(), QCPGraph::pointDistance(), and QCPCurve::pointDistance().
draw() [1/2]
virtual void QCPAbstractPlottable::draw (QCPPainter * painter) protected pure virtual
Implements QCPLayerable.
Implemented in QCPBarsWithText, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPErrorBars, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPArrow, QCPHiddenArea, QCPColoredBars, and QCPBarsWithText.
draw() [2/2]
virtual void QCPAbstractPlottable::draw (QCPPainter * painter) protected pure virtual
Implements QCPLayerable.
Implemented in QCPBarsWithText, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPErrorBars, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPArrow, QCPHiddenArea, QCPColoredBars, and QCPBarsWithText.
drawLegendIcon() [1/2]
virtual void QCPAbstractPlottable::drawLegendIcon (QCPPainter * painter, const QRectF & rect) const protected pure virtual
Implemented in QCPSelectableCursor, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPErrorBars, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
Referenced by QCPPlottableLegendItem::draw().
drawLegendIcon() [2/2]
virtual void QCPAbstractPlottable::drawLegendIcon (QCPPainter * painter, const QRectF & rect) const protected pure virtual
Implemented in QCPSelectableCursor, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPErrorBars, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
getKeyRange() [1/2]
QCPRange QCPAbstractPlottable::getKeyRange (bool & foundRange, QCP::SignDomain inSignDomain = QCP::sdBoth) const pure virtual
Returns the coordinate range that all data in this plottable span in the key axis dimension. For logarithmic plots, one can set inSignDomain to either QCP::sdNegative or QCP::sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to QCP::sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to QCP::sdBoth (default). foundRange is an output parameter that indicates whether a range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
Note that foundRange is not the same as QCPRange::validRange, since the range returned by this function may have size zero (e.g. when there is only one data point). In this case foundRange would return true, but the returned range is not a valid range in terms of QCPRange::validRange.
See also
rescaleAxes, getValueRange
Implemented in QCPSelectableCursor, QCPErrorBars, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
Referenced by rescaleKeyAxis().
getKeyRange() [2/2]
virtual QCPRange QCPAbstractPlottable::getKeyRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const protected pure virtual
Implemented in QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
getValueRange() [1/2]
QCPRange QCPAbstractPlottable::getValueRange (bool & foundRange, QCP::SignDomain inSignDomain = QCP::sdBoth, const QCPRange & inKeyRange = QCPRange()) const pure virtual
Returns the coordinate range that the data points in the specified key range (inKeyRange) span in the value axis dimension. For logarithmic plots, one can set inSignDomain to either QCP::sdNegative or QCP::sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to QCP::sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to QCP::sdBoth (default). foundRange is an output parameter that indicates whether a range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
If inKeyRange has both lower and upper bound set to zero (is equal to QCPRange()), all data points are considered, without any restriction on the keys.
Note that foundRange is not the same as QCPRange::validRange, since the range returned by this function may have size zero (e.g. when there is only one data point). In this case foundRange would return true, but the returned range is not a valid range in terms of QCPRange::validRange.
See also
rescaleAxes, getKeyRange
Implemented in QCPSelectableCursor, QCPErrorBars, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
Referenced by rescaleValueAxis().
getValueRange() [2/2]
QCPRange QCPAbstractPlottable::getValueRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const protected pure virtual
called by rescaleAxes functions to get the full data value bounds. For logarithmic plots, one can set inSignDomain to either sdNegative or sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to sdBoth (default). foundRange is an output parameter that indicates whether a range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
Note that foundRange is not the same as QCPRange::validRange, since the range returned by this function may have size zero, which wouldn't count as a valid range.
See also
rescaleAxes, getKeyRange
Implemented in QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
interface1D()
QCPPlottableInterface1D * QCPAbstractPlottable::interface1D () inline virtual
If this plottable is a one-dimensional plottable, i.e. it implements the QCPPlottableInterface1D, returns the this pointer with that type. Otherwise (e.g. in the case of a QCPColorMap) returns zero.
You can use this method to gain read access to data coordinates while holding a pointer to the abstract base class only.
Reimplemented in QCPErrorBars, QCPAbstractPlottable1D< DataType >, QCPAbstractPlottable1D< QCPFinancialData >, QCPAbstractPlottable1D< QCPStatisticalBoxData >, QCPAbstractPlottable1D< QCPGraphData >, QCPAbstractPlottable1D< QCPBarsData >, and QCPAbstractPlottable1D< QCPCurveData >.
Definition at line 3873 of file qcustomplot.h.
Referenced by QCPSelectionDecoratorBracket::drawDecoration(), QCustomPlot::processRectSelection(), and QCPErrorBars::setDataPlottable().
keyAxis() [1/2]
QCPAxis* QCPAbstractPlottable::keyAxis () const inline
Definition at line 3845 of file qcustomplot.h.
Referenced by QCPFinancial::candlestickSelectTest(), coordsToPixels(), QCPBars::dataPixelPosition(), QCPGraph::dataToImpulseLines(), QCPGraph::dataToLines(), QCPGraph::dataToStepCenterLines(), QCPGraph::dataToStepLeftLines(), QCPGraph::dataToStepRightLines(), QCPHiddenArea::draw(), QCPArrow::draw(), QCPStatisticalBox::draw(), QCPColorMap::draw(), QCPFinancial::drawCandlestickPlot(), QCPSelectionDecoratorBracket::drawDecoration(), QCPGraph::drawError(), QCPGraph::drawFill(), QCPFinancial::drawOhlcPlot(), QCPGraph::drawScatterPlot(), QCPBars::getBarPolygon(), QCPBars::getBarRect(), QCPGraph::getChannelFillPolygon(), QCPCurve::getCurveData(), QCPCurve::getCurveLines(), QCPGraph::getFillBasePoint(), QCPGraph::getImpulsePlotData(), QCPGraph::getLinePlotData(), QCPGraph::getOptimizedLineData(), QCPGraph::getOptimizedScatterData(), QCPSelectionDecoratorBracket::getPixelCoordinates(), QCPGraph::getPreparedData(), QCPGraph::getScatters(), QCPCurve::getScatters(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPErrorBars::getVisibleDataBounds(), QCPGraph::getVisibleDataBounds(), QCPBarsGroup::keyPixelOffset(), QCPGraph::lowerFillBasePoint(), QCPBars::moveAbove(), QCPBars::moveBelow(), QCPFinancial::ohlcSelectTest(), pixelsToCoords(), QCPSelectableCursor::pixelToKey(), QCustomPlot::plottableAt(), QCPAbstractPlottable(), QCPGraph::rescaleKeyAxis(), rescaleKeyAxis(), rescaleValueAxis(), QCPFinancial::selectionHitBox(), QCPItemTracer::setGraph(), QCPColorMap::updateLegendIcon(), QCPColorMap::updateMapImage(), and QCPGraph::upperFillBasePoint().
keyAxis() [2/2]
QCPAxis* QCPAbstractPlottable::keyAxis () const inline
Definition at line 1708 of file qcustomplot.h.
mainBrush()
QBrush QCPAbstractPlottable::mainBrush () const protected
Definition at line 7522 of file qcustomplot.cpp.
References mBrush, mSelected, and mSelectedBrush.
Referenced by QCPStatisticalBox::drawQuartileBox().
mainPen()
QPen QCPAbstractPlottable::mainPen () const protected
Definition at line 7513 of file qcustomplot.cpp.
References mPen, mSelected, and mSelectedPen.
Referenced by QCPGraph::drawImpulsePlot(), QCPGraph::drawLinePlot(), QCPStatisticalBox::drawQuartileBox(), and QCPCurve::getCurveData().
name() [1/2]
QString QCPAbstractPlottable::name () const inline
Definition at line 3840 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::draw(), QCPGraph::draw(), QCPCurve::draw(), QCPBars::draw(), QCPStatisticalBox::draw(), QCPErrorBars::draw(), QCPPlottableLegendItem::minimumOuterSizeHint(), QCPPlottableLegendItem::minimumSizeHint(), and setName().
name() [2/2]
QString QCPAbstractPlottable::name () const inline
Definition at line 1700 of file qcustomplot.h.
pen() [1/2]
QPen QCPAbstractPlottable::pen () const inline
Definition at line 3843 of file qcustomplot.h.
Referenced by QCPColoredBars::draw(), QCPHiddenArea::draw(), QCPArrow::draw(), QCPGraph::drawImpulsePlot(), QCPGraph::setErrorPen(), QCPStatisticalBox::setMedianPen(), setPen(), QCPFinancial::setPenNegative(), QCPFinancial::setPenPositive(), setSelectedPen(), QCPStatisticalBox::setWhiskerBarPen(), QCPStatisticalBox::setWhiskerPen(), ccWaveWidget::updateCurveWidth(), and ccHistogramWindow::updateOverlayCurveWidth().
pen() [2/2]
QPen QCPAbstractPlottable::pen () const inline
Definition at line 1704 of file qcustomplot.h.
pixelsToCoords() [1/4]
void QCPAbstractPlottable::pixelsToCoords (const QPointF & pixelPos, double & key, double & value) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns the pixel input pixelPos as plot coordinates key and value.
Definition at line 11373 of file qcustomplot.cpp.
References pixelsToCoords().
pixelsToCoords() [2/4]
void QCPAbstractPlottable::pixelsToCoords (const QPointF & pixelPos, double & key, double & value) const protected
pixelsToCoords() [3/4]
void QCPAbstractPlottable::pixelsToCoords (double x, double y, double & key, double & value) const
Convenience function for transforming a x/y pixel pair on the QCustomPlot surface to plot coordinates, taking the orientations of the axes associated with this plottable into account (e.g. whether key represents x or y).
x and y are transformed to the plot coodinates and are written to key and value.
See also
coordsToPixels, QCPAxis::coordToPixel
Definition at line 11349 of file qcustomplot.cpp.
References keyAxis(), mKeyAxis, mValueAxis, QCPAxis::orientation(), QCPAxis::pixelToCoord(), valueAxis(), x, and y.
Referenced by QCPFinancial::candlestickSelectTest(), pixelsToCoords(), QCPGraph::pointDistance(), and QCPColorMap::selectTest().
pixelsToCoords() [4/4]
void QCPAbstractPlottable::pixelsToCoords (double x, double y, double & key, double & value) const protected
removeFromLegend() [1/3]
bool QCPAbstractPlottable::removeFromLegend () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes the plottable from the legend of the parent QCustomPlot.
See also
addToLegend
Removes the plottable from the legend of the parent QCustomPlot. This means the QCPAbstractLegendItem (usually a QCPPlottableLegendItem) that is associated with this plottable is removed.
Returns true on success, i.e. if the legend exists and a legend item associated with this plottable was found and removed.
See also
addToLegend, QCPLegend::removeItem
Definition at line 11575 of file qcustomplot.cpp.
References QCustomPlot::legend, and QCPLayerable::mParentPlot.
removeFromLegend() [2/3]
virtual bool QCPAbstractPlottable::removeFromLegend () const virtual
removeFromLegend() [3/3]
bool QCPAbstractPlottable::removeFromLegend (QCPLegend * legend) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes the plottable from the specifed legend. This means the QCPPlottableLegendItem that is associated with this plottable is removed.
Returns true on success, i.e. if the legend exists and a legend item associated with this plottable was found and removed.
See also
addToLegend, QCPLegend::removeItem
Definition at line 11557 of file qcustomplot.cpp.
References QCPLegend::itemWithPlottable(), and QCPLegend::removeItem().
Referenced by QCustomPlot::removePlottable(), and WolmanCustomPlot::WolmanCustomPlot().
rescaleAxes() [1/2]
void QCPAbstractPlottable::rescaleAxes (bool onlyEnlarge = false) const
Rescales the key and value axes associated with this plottable to contain all displayed data, so the whole plottable is visible. If the scaling of an axis is logarithmic, rescaleAxes will make sure not to rescale to an illegal range i.e. a range containing different signs and/or zero. Instead it will stay in the current sign domain and ignore all parts of the plottable that lie outside of that domain.
onlyEnlarge makes sure the ranges are only expanded, never reduced. So it's possible to show multiple plottables in their entirety by multiple calls to rescaleAxes where the first call has onlyEnlarge set to false (the default), and all subsequent set to true.
See also
rescaleKeyAxis, rescaleValueAxis, QCustomPlot::rescaleAxes, QCPAxis::rescale
Definition at line 11395 of file qcustomplot.cpp.
References rescaleKeyAxis(), and rescaleValueAxis().
Referenced by AnglesCustomPlot::AnglesCustomPlot(), AnglesCustomPlot::rescale(), and WolmanCustomPlot::WolmanCustomPlot().
rescaleAxes() [2/2]
void QCPAbstractPlottable::rescaleAxes (bool onlyEnlarge = false) const
rescaleKeyAxis() [1/2]
void QCPAbstractPlottable::rescaleKeyAxis (bool onlyEnlarge = false) const
Rescales the key axis of the plottable so the whole plottable is visible.
See rescaleAxes for detailed behaviour.
Definition at line 11405 of file qcustomplot.cpp.
References QCPRange::expand(), getKeyRange(), keyAxis(), QCPRange::lower, mKeyAxis, QCPAxis::range(), QCPAxis::scaleType(), QCP::sdBoth, QCP::sdNegative, QCP::sdPositive, QCPAxis::setRange(), QCPRange::size(), QCPAxis::stLinear, QCPAxis::stLogarithmic, QCPRange::upper, and QCPRange::validRange().
Referenced by rescaleAxes().
rescaleKeyAxis() [2/2]
void QCPAbstractPlottable::rescaleKeyAxis (bool onlyEnlarge = false) const
rescaleValueAxis() [1/2]
void QCPAbstractPlottable::rescaleValueAxis (bool onlyEnlarge = false) const
Rescales the value axis of the plottable so the whole plottable is visible.
Returns true if the axis was actually scaled. This might not be the case if this plottable has an invalid range, e.g. because it has no data points.
See rescaleAxes for detailed behaviour.
Definition at line 7314 of file qcustomplot.cpp.
References QCPRange::expand(), getValueRange(), QCPRange::lower, mValueAxis, QCPAxis::range(), QCPAxis::scaleType(), sdBoth, sdNegative, sdPositive, QCPAxis::setRange(), QCPRange::size(), QCPAxis::stLinear, QCPAxis::stLogarithmic, QCPRange::upper, QCPRange::validRange(), and valueAxis().
rescaleValueAxis() [2/2]
void QCPAbstractPlottable::rescaleValueAxis (bool onlyEnlarge = false, bool inKeyRange = false) const
Rescales the value axis of the plottable so the whole plottable is visible. If inKeyRange is set to true, only the data points which are in the currently visible key axis range are considered.
Returns true if the axis was actually scaled. This might not be the case if this plottable has an invalid range, e.g. because it has no data points.
See rescaleAxes for detailed behaviour.
Definition at line 11456 of file qcustomplot.cpp.
References QCPRange::expand(), getValueRange(), keyAxis(), QCPRange::lower, mKeyAxis, mValueAxis, QCPAxis::range(), QCPAxis::scaleType(), QCP::sdBoth, QCP::sdNegative, QCP::sdPositive, QCPAxis::setRange(), QCPRange::size(), QCPAxis::stLinear, QCPAxis::stLogarithmic, QCPRange::upper, QCPRange::validRange(), and valueAxis().
Referenced by rescaleAxes().
selectable() [1/2]
QCP::SelectionType QCPAbstractPlottable::selectable () const inline
Definition at line 3847 of file qcustomplot.h.
Referenced by QCustomPlot::plottableAt(), and setSelectable().
selectable() [2/2]
bool QCPAbstractPlottable::selectable () const inline
Definition at line 1710 of file qcustomplot.h.
selectableChanged [1/2]
void QCPAbstractPlottable::selectableChanged (bool selectable) signal
This signal is emitted when the selectability of this plottable has changed.
See also
setSelectable
selectableChanged [2/2]
void QCPAbstractPlottable::selectableChanged (QCP::SelectionType selectable) signal
Referenced by setSelectable().
selected() [1/2]
bool QCPAbstractPlottable::selected () const inline
Returns true if there are any data points of the plottable currently selected. Use selection to retrieve the current QCPDataSelection.
Definition at line 3848 of file qcustomplot.h.
Referenced by QCPErrorBars::getDataSegments(), QCustomPlot::selectedGraphs(), QCustomPlot::selectedPlottables(), selectEvent(), setSelectable(), setSelected(), and setSelection().
selected() [2/2]
bool QCPAbstractPlottable::selected () const inline
Definition at line 1711 of file qcustomplot.h.
selectedBrush()
QBrush QCPAbstractPlottable::selectedBrush () const inline
Definition at line 1707 of file qcustomplot.h.
selectedPen()
QPen QCPAbstractPlottable::selectedPen () const inline
Definition at line 1705 of file qcustomplot.h.
selectEvent() [1/2]
void QCPAbstractPlottable::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
Definition at line 11651 of file qcustomplot.cpp.
References QCPDataSelection::contains(), event, mSelectable, mSelection, selected(), setSelection(), QCP::stNone, and QCP::stWhole.
selectEvent() [2/2]
virtual void QCPAbstractPlottable::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) protected virtual
Reimplemented from QCPLayerable.
selection()
QCPDataSelection QCPAbstractPlottable::selection () const inline
Returns a QCPDataSelection encompassing all the data points that are currently selected on this plottable.
See also
selected, setSelection, setSelectable
Definition at line 3849 of file qcustomplot.h.
Referenced by QCPGraph::draw(), QCPCurve::draw(), QCPBars::draw(), QCPStatisticalBox::draw(), QCPFinancial::draw(), QCPErrorBars::draw(), QCPErrorBars::getDataSegments(), and setSelection().
selectionCategory() [1/2]
QCP::Interaction QCPAbstractPlottable::selectionCategory () const protected virtual
Reimplemented from QCPLayerable.
Definition at line 11592 of file qcustomplot.cpp.
References QCP::iSelectPlottables.
selectionCategory() [2/2]
virtual QCP::Interaction QCPAbstractPlottable::selectionCategory () const protected virtual
Reimplemented from QCPLayerable.
selectionChanged [1/3]
void QCPAbstractPlottable::selectionChanged (bool selected) signal
This signal is emitted when the selection state of this plottable has changed, either by user interaction or by a direct call to setSelection. The parameter selected indicates whether there are any points selected or not.
See also
selectionChanged(const QCPDataSelection &selection)
This signal is emitted when the selection state of this plottable has changed, either by user interaction or by a direct call to setSelected.
Referenced by setSelectable(), setSelected(), and setSelection().
selectionChanged [2/3]
void QCPAbstractPlottable::selectionChanged (bool selected) signal
selectionChanged [3/3]
void QCPAbstractPlottable::selectionChanged (const QCPDataSelection & selection) signal
This signal is emitted when the selection state of this plottable has changed, either by user interaction or by a direct call to setSelection. The parameter selection holds the currently selected data ranges.
See also
selectionChanged(bool selected)
selectionDecorator()
QCPSelectionDecorator * QCPAbstractPlottable::selectionDecorator () const inline
Provides access to the selection decorator of this plottable. The selection decorator controls how selected data ranges are drawn (e.g. their pen color and fill), see QCPSelectionDecorator for details.
If you wish to use an own QCPSelectionDecorator subclass, pass an instance of it to setSelectionDecorator.
Definition at line 3850 of file qcustomplot.h.
selectTest() [1/2]
virtual double QCPAbstractPlottable::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const pure virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Reimplemented from QCPLayerable.
Implemented in QCPSelectableCursor, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPErrorBars, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPAbstractPlottable1D< DataType >, QCPAbstractPlottable1D< QCPFinancialData >, QCPAbstractPlottable1D< QCPStatisticalBoxData >, QCPAbstractPlottable1D< QCPGraphData >, QCPAbstractPlottable1D< QCPBarsData >, and QCPAbstractPlottable1D< QCPCurveData >.
Referenced by QCustomPlot::plottableAt().
selectTest() [2/2]
virtual double QCPAbstractPlottable::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const pure virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Reimplemented from QCPLayerable.
Implemented in QCPSelectableCursor, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPErrorBars, QCPFinancial, QCPColorMap, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, QCPAbstractPlottable1D< DataType >, QCPAbstractPlottable1D< QCPFinancialData >, QCPAbstractPlottable1D< QCPStatisticalBoxData >, QCPAbstractPlottable1D< QCPGraphData >, QCPAbstractPlottable1D< QCPBarsData >, and QCPAbstractPlottable1D< QCPCurveData >.
setAntialiasedErrorBars()
void QCPAbstractPlottable::setAntialiasedErrorBars (bool enabled)
Sets whether the error bars of this plottable are drawn antialiased or not.
Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 7124 of file qcustomplot.cpp.
References mAntialiasedErrorBars.
setAntialiasedFill() [1/2]
void QCPAbstractPlottable::setAntialiasedFill (bool enabled)
Sets whether fills of this plottable are drawn antialiased or not.
Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 11143 of file qcustomplot.cpp.
References mAntialiasedFill.
Referenced by ccHistogramWindow::refresh(), and ccWaveWidget::refresh().
setAntialiasedFill() [2/2]
void QCPAbstractPlottable::setAntialiasedFill (bool enabled)
setAntialiasedScatters() [1/2]
void QCPAbstractPlottable::setAntialiasedScatters (bool enabled)
Sets whether the scatter symbols of this plottable are drawn antialiased or not.
Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 11155 of file qcustomplot.cpp.
References mAntialiasedScatters.
setAntialiasedScatters() [2/2]
void QCPAbstractPlottable::setAntialiasedScatters (bool enabled)
setBrush() [1/2]
void QCPAbstractPlottable::setBrush (const QBrush & brush)
The brush is used to draw basic fills of the plottable representation in the plot. The Fill can be a color, gradient or texture, see the usage of QBrush.
For example, the QCPGraph subclass draws the fill under the graph with this brush, when it's not set to Qt::NoBrush.
See also
setPen
Definition at line 11178 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by AnglesCustomPlot::createQCPBars(), QCPArrow::QCPArrow(), QCPCurve::QCPCurve(), QCPErrorBars::QCPErrorBars(), QCPGraph::QCPGraph(), QCPHiddenArea::QCPHiddenArea(), QCPStatisticalBox::QCPStatisticalBox(), ccHistogramWindow::refresh(), ccWaveWidget::refresh(), and QCPArrow::setColor().
setBrush() [2/2]
void QCPAbstractPlottable::setBrush (const QBrush & brush)
setKeyAxis() [1/2]
void QCPAbstractPlottable::setKeyAxis (QCPAxis * axis)
The key axis of a plottable can be set to any axis of a QCustomPlot, as long as it is orthogonal to the plottable's value axis. This function performs no checks to make sure this is the case. The typical mathematical choice is to use the x-axis (QCustomPlot::xAxis) as key axis and the y-axis (QCustomPlot::yAxis) as value axis.
Normally, the key and value axes are set in the constructor of the plottable (or QCustomPlot::addGraph when working with QCPGraphs through the dedicated graph interface).
See also
setValueAxis
Definition at line 11193 of file qcustomplot.cpp.
References mKeyAxis.
setKeyAxis() [2/2]
void QCPAbstractPlottable::setKeyAxis (QCPAxis * axis)
setName() [1/2]
void QCPAbstractPlottable::setName (const QString & name)
The name is the textual representation of this plottable as it is displayed in the legend (QCPLegend). It may contain any UTF-8 characters, including newlines.
Definition at line 11134 of file qcustomplot.cpp.
References mName, and name().
Referenced by QCustomPlot::addGraph(), cvProbeFilter::apply(), ccHistogramWindow::refresh(), and ccWaveWidget::refresh().
setName() [2/2]
void QCPAbstractPlottable::setName (const QString & name)
setPen() [1/2]
void QCPAbstractPlottable::setPen (const QPen & pen)
The pen is used to draw basic lines that make up the plottable representation in the plot.
For example, the QCPGraph subclass draws its graph lines with this pen.
See also
setBrush
Definition at line 11167 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by cvProbeFilter::apply(), AnglesCustomPlot::createQCPBars(), QCPArrow::QCPArrow(), QCPCurve::QCPCurve(), QCPErrorBars::QCPErrorBars(), QCPGraph::QCPGraph(), QCPHiddenArea::QCPHiddenArea(), QCPStatisticalBox::QCPStatisticalBox(), ccHistogramWindow::refresh(), ccWaveWidget::refresh(), ccWaveWidget::updateCurveWidth(), ccHistogramWindow::updateOverlayCurveWidth(), and WolmanCustomPlot::WolmanCustomPlot().
setPen() [2/2]
void QCPAbstractPlottable::setPen (const QPen & pen)
setSelectable() [1/2]
void QCPAbstractPlottable::setSelectable (bool selectable)
Sets whether the user can (de-)select this plottable by clicking on the QCustomPlot surface. (When QCustomPlot::setInteractions contains iSelectPlottables.)
However, even when selectable was set to false, it is possible to set the selection manually, by calling setSelected directly.
See also
setSelected
Definition at line 7209 of file qcustomplot.cpp.
References mSelectable, selectable(), and selectableChanged().
setSelectable() [2/2]
void QCPAbstractPlottable::setSelectable (QCP::SelectionType selectable)
Sets whether and to which granularity this plottable can be selected.
A selection can happen by clicking on the QCustomPlot surface (When QCustomPlot::setInteractions contains QCP::iSelectPlottables), by dragging a selection rect (When QCustomPlot::setSelectionRectMode is QCP::srmSelect), or programmatically by calling setSelection.
See also
setSelection, QCP::SelectionType
Definition at line 11274 of file qcustomplot.cpp.
References QCPDataSelection::enforceType(), mSelectable, mSelection, selectable(), selectableChanged(), selected(), and selectionChanged().
setSelected()
void QCPAbstractPlottable::setSelected (bool selected)
Sets whether this plottable is selected or not. When selected, it uses a different pen and brush to draw its lines and fills, see setSelectedPen and setSelectedBrush.
The entire selection mechanism for plottables is handled automatically when QCustomPlot::setInteractions contains iSelectPlottables. You only need to call this function when you wish to change the selection state manually.
This function can change the selection state even when setSelectable was set to false.
emits the selectionChanged signal when selected is different from the previous selection state.
See also
setSelectable, selectTest
Definition at line 7233 of file qcustomplot.cpp.
References mSelected, selected(), and selectionChanged().
setSelectedBrush()
void QCPAbstractPlottable::setSelectedBrush (const QBrush & brush)
When the plottable is selected, this brush is used to draw fills instead of the normal brush set via setBrush.
See also
setSelected, setSelectable, setSelectedPen, selectTest
Definition at line 7165 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
setSelectedPen()
void QCPAbstractPlottable::setSelectedPen (const QPen & pen)
When the plottable is selected, this pen is used to draw basic lines instead of the normal pen set via setPen.
See also
setSelected, setSelectable, setSelectedBrush, selectTest
Definition at line 7144 of file qcustomplot.cpp.
References mSelectedPen, and pen().
setSelection()
void QCPAbstractPlottable::setSelection (QCPDataSelection selection)
Sets which data ranges of this plottable are selected. Selected data ranges are drawn differently (e.g. color) in the plot. This can be controlled via the selection decorator (see selectionDecorator).
The entire selection mechanism for plottables is handled automatically when QCustomPlot::setInteractions contains iSelectPlottables. You only need to call this function when you wish to change the selection state programmatically.
Using setSelectable you can further specify for each plottable whether and to which granularity it is selectable. If selection is not compatible with the current QCP::SelectionType set via setSelectable, the resulting selection will be adjusted accordingly (see QCPDataSelection::enforceType).
emits the selectionChanged signal when selected is different from the previous selection state.
See also
setSelectable, selectTest
Definition at line 11231 of file qcustomplot.cpp.
References QCPDataSelection::enforceType(), mSelectable, mSelection, selected(), selection(), and selectionChanged().
Referenced by deselectEvent(), and selectEvent().
setSelectionDecorator()
void QCPAbstractPlottable::setSelectionDecorator (QCPSelectionDecorator * decorator)
Use this method to set an own QCPSelectionDecorator (subclass) instance. This allows you to customize the visual representation of selected data ranges further than by using the default QCPSelectionDecorator.
The plottable takes ownership of the decorator.
The currently set decorator can be accessed via selectionDecorator.
Definition at line 11249 of file qcustomplot.cpp.
References mSelectionDecorator, and QCPSelectionDecorator::registerWithPlottable().
Referenced by QCPAbstractPlottable().
setValueAxis() [1/2]
void QCPAbstractPlottable::setValueAxis (QCPAxis * axis)
The value axis of a plottable can be set to any axis of a QCustomPlot, as long as it is orthogonal to the plottable's key axis. This function performs no checks to make sure this is the case. The typical mathematical choice is to use the x-axis (QCustomPlot::xAxis) as key axis and the y-axis (QCustomPlot::yAxis) as value axis.
Normally, the key and value axes are set in the constructor of the plottable (or QCustomPlot::addGraph when working with QCPGraphs through the dedicated graph interface).
See also
setKeyAxis
Definition at line 11208 of file qcustomplot.cpp.
References mValueAxis.
setValueAxis() [2/2]
void QCPAbstractPlottable::setValueAxis (QCPAxis * axis)
valueAxis() [1/2]
QCPAxis* QCPAbstractPlottable::valueAxis () const inline
Definition at line 3846 of file qcustomplot.h.
Referenced by QCPFinancial::candlestickSelectTest(), coordsToPixels(), QCPBars::dataPixelPosition(), QCPGraph::dataToImpulseLines(), QCPGraph::dataToLines(), QCPGraph::dataToStepCenterLines(), QCPGraph::dataToStepLeftLines(), QCPGraph::dataToStepRightLines(), QCPStatisticalBox::draw(), QCPColorMap::draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawError(), QCPFinancial::drawOhlcPlot(), QCPGraph::drawScatterPlot(), QCPBars::getBarPolygon(), QCPBars::getBarRect(), QCPGraph::getChannelFillPolygon(), QCPCurve::getCurveData(), QCPCurve::getCurveLines(), QCPGraph::getFillBasePoint(), QCPGraph::getImpulsePlotData(), QCPGraph::getLinePlotData(), QCPGraph::getOptimizedLineData(), QCPGraph::getOptimizedScatterData(), QCPSelectionDecoratorBracket::getPixelCoordinates(), QCPGraph::getPreparedData(), QCPGraph::getScatters(), QCPCurve::getScatters(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPErrorBars::getVisibleDataBounds(), QCPGraph::getVisibleDataBounds(), QCPGraph::lowerFillBasePoint(), QCPBars::moveAbove(), QCPBars::moveBelow(), QCPFinancial::ohlcSelectTest(), pixelsToCoords(), QCPSelectableCursor::pixelToValue(), QCustomPlot::plottableAt(), QCPAbstractPlottable(), QCPGraph::rescaleValueAxis(), rescaleValueAxis(), QCPFinancial::selectionHitBox(), QCPItemTracer::setGraph(), QCPColorMap::updateLegendIcon(), and QCPGraph::upperFillBasePoint().
valueAxis() [2/2]
QCPAxis* QCPAbstractPlottable::valueAxis () const inline
Definition at line 1709 of file qcustomplot.h.
Member Data Documentation
mAntialiasedErrorBars
bool QCPAbstractPlottable::mAntialiasedErrorBars protected
Definition at line 1762 of file qcustomplot.h.
Referenced by applyErrorBarsAntialiasingHint(), and setAntialiasedErrorBars().
mAntialiasedFill
bool QCPAbstractPlottable::mAntialiasedFill protected
Definition at line 3906 of file qcustomplot.h.
Referenced by applyFillAntialiasingHint(), and setAntialiasedFill().
mAntialiasedScatters
bool QCPAbstractPlottable::mAntialiasedScatters protected
Definition at line 3906 of file qcustomplot.h.
Referenced by applyScattersAntialiasingHint(), and setAntialiasedScatters().
mBrush
QBrush QCPAbstractPlottable::mBrush protected
Definition at line 3908 of file qcustomplot.h.
Referenced by QCPGraph::draw(), QCPCurve::draw(), QCPBars::draw(), QCPStatisticalBox::draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPBars::drawLegendIcon(), QCPStatisticalBox::drawLegendIcon(), QCPFinancial::drawLegendIcon(), mainBrush(), QCPArrow::QCPArrow(), QCPBars::QCPBars(), QCPHiddenArea::QCPHiddenArea(), setBrush(), and QCPArrow::setColor().
mKeyAxis
QPointer< QCPAxis > QCPAbstractPlottable::mKeyAxis protected
Definition at line 3909 of file qcustomplot.h.
Referenced by QCPGraph::addFillBasePoints(), QCPFinancial::candlestickSelectTest(), clipRect(), coordsToPixels(), QCPBars::dataPixelPosition(), QCPGraph::dataToImpulseLines(), QCPGraph::dataToLines(), QCPGraph::dataToStepCenterLines(), QCPGraph::dataToStepLeftLines(), QCPGraph::dataToStepRightLines(), QCPBarsWithText::draw(), QCPColoredBars::draw(), QCPGraph::draw(), QCPBars::draw(), QCPStatisticalBox::draw(), QCPColorMap::draw(), QCPErrorBars::draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawError(), QCPFinancial::drawOhlcPlot(), QCPGraph::drawScatterPlot(), QCPErrorBars::errorBarVisible(), QCPBars::getBarPolygon(), QCPBars::getBarRect(), QCPGraph::getChannelFillPolygon(), QCPCurve::getCurveData(), QCPCurve::getCurveLines(), QCPErrorBars::getErrorBarLines(), QCPGraph::getFillBasePoint(), QCPGraph::getImpulsePlotData(), QCPBars::getKeyRange(), QCPFinancial::getKeyRange(), QCPGraph::getLinePlotData(), QCPGraph::getLines(), QCPGraph::getOptimizedLineData(), QCPCurve::getOptimizedPoint(), QCPGraph::getOptimizedScatterData(), QCPGraph::getOverlappingSegments(), QCPBars::getPixelWidth(), QCPFinancial::getPixelWidth(), QCPGraph::getPreparedData(), QCPGraph::getScatters(), QCPCurve::getScatters(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPCurve::getTraverse(), QCPBars::getVisibleDataBounds(), QCPErrorBars::getVisibleDataBounds(), QCPFinancial::getVisibleDataBounds(), QCPGraph::getVisibleDataBounds(), QCPStatisticalBox::getVisibleDataBounds(), QCPGraph::lowerFillBasePoint(), QCPBars::moveAbove(), QCPBars::moveBelow(), QCPFinancial::ohlcSelectTest(), pixelsToCoords(), QCPErrorBars::pointDistance(), QCPGraph::rescaleKeyAxis(), rescaleKeyAxis(), rescaleValueAxis(), QCPFinancial::selectionHitBox(), QCPGraph::selectTest(), QCPCurve::selectTest(), QCPBars::selectTest(), QCPStatisticalBox::selectTest(), QCPColorMap::selectTest(), QCPFinancial::selectTest(), QCPErrorBars::selectTest(), QCPBars::selectTestRect(), QCPStatisticalBox::selectTestRect(), QCPFinancial::selectTestRect(), QCPErrorBars::selectTestRect(), setKeyAxis(), QCPColorMap::updateMapImage(), and QCPGraph::upperFillBasePoint().
mName
QString QCPAbstractPlottable::mName protected
Definition at line 3905 of file qcustomplot.h.
Referenced by QCPCurve::pointDistance(), and setName().
mPen
QPen QCPAbstractPlottable::mPen protected
Definition at line 3907 of file qcustomplot.h.
Referenced by QCPGraph::draw(), QCPCurve::draw(), QCPBars::draw(), QCPStatisticalBox::draw(), QCPErrorBars::draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPBars::drawLegendIcon(), QCPStatisticalBox::drawLegendIcon(), QCPFinancial::drawLegendIcon(), QCPErrorBars::drawLegendIcon(), QCPFinancial::drawOhlcPlot(), QCPStatisticalBox::drawOutliers(), QCPCurve::drawScatterPlot(), QCPGraph::drawScatterPlot(), QCPStatisticalBox::drawStatisticalBox(), QCPBars::getBarRect(), mainPen(), QCPArrow::QCPArrow(), QCPBars::QCPBars(), QCPHiddenArea::QCPHiddenArea(), and setPen().
mSelectable [1/2]
QCP::SelectionType QCPAbstractPlottable::mSelectable protected
Definition at line 3910 of file qcustomplot.h.
Referenced by deselectEvent(), QCPErrorBars::getDataSegments(), selectEvent(), QCPGraph::selectTest(), QCPCurve::selectTest(), QCPBars::selectTest(), QCPStatisticalBox::selectTest(), QCPColorMap::selectTest(), QCPFinancial::selectTest(), QCPErrorBars::selectTest(), QCPBars::selectTestRect(), QCPStatisticalBox::selectTestRect(), QCPFinancial::selectTestRect(), QCPErrorBars::selectTestRect(), setSelectable(), and setSelection().
mSelectable [2/2]
bool QCPAbstractPlottable::mSelectable protected
Definition at line 1766 of file qcustomplot.h.
mSelected
bool QCPAbstractPlottable::mSelected protected
Definition at line 1766 of file qcustomplot.h.
Referenced by QCPFinancial::drawCandlestickPlot(), QCPFinancial::drawOhlcPlot(), mainBrush(), mainPen(), and setSelected().
mSelectedBrush
QBrush QCPAbstractPlottable::mSelectedBrush protected
Definition at line 1764 of file qcustomplot.h.
Referenced by QCPFinancial::drawCandlestickPlot(), mainBrush(), and setSelectedBrush().
mSelectedPen
QPen QCPAbstractPlottable::mSelectedPen protected
Definition at line 1763 of file qcustomplot.h.
Referenced by QCPFinancial::drawCandlestickPlot(), QCPFinancial::drawOhlcPlot(), mainPen(), and setSelectedPen().
mSelection
QCPDataSelection QCPAbstractPlottable::mSelection protected
Definition at line 3911 of file qcustomplot.h.
Referenced by deselectEvent(), selectEvent(), setSelectable(), and setSelection().
mSelectionDecorator
QCPSelectionDecorator* QCPAbstractPlottable::mSelectionDecorator protected
Definition at line 3912 of file qcustomplot.h.
Referenced by QCPGraph::draw(), QCPCurve::draw(), QCPBars::draw(), QCPStatisticalBox::draw(), QCPFinancial::draw(), QCPErrorBars::draw(), QCPFinancial::drawCandlestickPlot(), QCPFinancial::drawOhlcPlot(), QCPBars::QCPBars(), QCPFinancial::QCPFinancial(), setSelectionDecorator(), and ~QCPAbstractPlottable().
mValueAxis
QPointer< QCPAxis > QCPAbstractPlottable::mValueAxis protected
Definition at line 3909 of file qcustomplot.h.
Referenced by QCPFinancial::candlestickSelectTest(), clipRect(), coordsToPixels(), QCPBars::dataPixelPosition(), QCPGraph::dataToImpulseLines(), QCPGraph::dataToLines(), QCPGraph::dataToStepCenterLines(), QCPGraph::dataToStepLeftLines(), QCPGraph::dataToStepRightLines(), QCPBarsWithText::draw(), QCPColoredBars::draw(), QCPGraph::draw(), QCPBars::draw(), QCPStatisticalBox::draw(), QCPColorMap::draw(), QCPErrorBars::draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawError(), QCPErrorBars::drawLegendIcon(), QCPFinancial::drawOhlcPlot(), QCPGraph::drawScatterPlot(), QCPBars::getBarPolygon(), QCPBars::getBarRect(), QCPGraph::getChannelFillPolygon(), QCPCurve::getCurveData(), QCPCurve::getCurveLines(), QCPErrorBars::getErrorBarLines(), QCPGraph::getFillBasePoint(), QCPGraph::getImpulsePlotData(), QCPGraph::getLinePlotData(), QCPGraph::getOptimizedLineData(), QCPCurve::getOptimizedPoint(), QCPGraph::getOptimizedScatterData(), QCPGraph::getPreparedData(), QCPGraph::getScatters(), QCPCurve::getScatters(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPCurve::getTraverse(), QCPErrorBars::getVisibleDataBounds(), QCPGraph::getVisibleDataBounds(), QCPGraph::lowerFillBasePoint(), QCPBars::moveAbove(), QCPBars::moveBelow(), QCPFinancial::ohlcSelectTest(), pixelsToCoords(), QCPErrorBars::pointDistance(), QCPGraph::rescaleValueAxis(), rescaleValueAxis(), QCPFinancial::selectionHitBox(), QCPGraph::selectTest(), QCPCurve::selectTest(), QCPBars::selectTest(), QCPStatisticalBox::selectTest(), QCPColorMap::selectTest(), QCPFinancial::selectTest(), QCPErrorBars::selectTest(), QCPBars::selectTestRect(), QCPStatisticalBox::selectTestRect(), QCPFinancial::selectTestRect(), QCPErrorBars::selectTestRect(), setValueAxis(), and QCPGraph::upperFillBasePoint().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp