ACloudViewer: QCPItemRect Class Reference
QCPItemRect Class Reference
A rectangle.
#include <qcustomplot.h>
Public Member Functions
QCPItemRect (QCustomPlot *parentPlot)
virtual ~QCPItemRect ()
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
QCPItemRect (QCustomPlot *parentPlot)
virtual ~QCPItemRect ()
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractItem
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
virtual ~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Public Attributes
QCPItemPosition *const topLeft
QCPItemPosition *const bottomRight
QCPItemAnchor *const top
QCPItemAnchor *const topRight
QCPItemAnchor *const right
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeft
QCPItemAnchor *const left
Protected Types
enum AnchorIndex {
aiTop , aiTopRight , aiRight , aiBottom ,
aiBottomLeft , aiLeft , aiTop , aiTopRight ,
aiRight , aiBottom , aiBottomLeft , aiLeft
}
enum AnchorIndex {
aiTop , aiTopRight , aiRight , aiBottom ,
aiBottomLeft , aiLeft , aiTop , aiTopRight ,
aiRight , aiBottom , aiBottomLeft , aiLeft
}
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPosition (int anchorId) const
QPen mainPen () const
QBrush mainBrush () const
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPen mainPen () const
QBrush mainBrush () const
Protected Member Functions inherited from QCPAbstractItem
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double rectDistance (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual void mousePressEvent (QMouseEvent *event, const QVariant &details)
virtual void mouseMoveEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseReleaseEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseDoubleClickEvent (QMouseEvent *event, const QVariant &details)
virtual void wheelEvent (QWheelEvent *event)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
Protected Attributes inherited from QCPAbstractItem
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractItem
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
void layerChanged (QCPLayer *newLayer)
Detailed Description
A rectangle.
Rectangle example. Blue dotted circles are
anchors, solid blue discs are positions."
It has two positions, topLeft and bottomRight, which define the rectangle.
Definition at line 7370 of file qcustomplot.h.
Member Enumeration Documentation
AnchorIndex [1/2]
enum QCPItemRect::AnchorIndex protected
Enumerator
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 7409 of file qcustomplot.h.
AnchorIndex [2/2]
enum QCPItemRect::AnchorIndex protected
Enumerator
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 4058 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemRect() [1/2]
QCPItemRect::QCPItemRect (QCustomPlot * parentPlot) explicit
Creates a rectangle item and sets default values.
The created item is automatically registered with parentPlot. This QCustomPlot instance takes ownership of the item, so do not delete it manually but use QCustomPlot::removeItem() instead.
Creates a rectangle item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 30551 of file qcustomplot.cpp.
References ecvColor::black(), ecvColor::blue(), bottomRight, setBrush(), QCPItemPosition::setCoords(), setPen(), setSelectedBrush(), setSelectedPen(), and topLeft.
~QCPItemRect() [1/2]
QCPItemRect::~QCPItemRect () virtual
Definition at line 30570 of file qcustomplot.cpp.
QCPItemRect() [2/2]
QCPItemRect::QCPItemRect (QCustomPlot * parentPlot)
~QCPItemRect() [2/2]
virtual QCPItemRect::~QCPItemRect () virtual
Member Function Documentation
anchorPixelPoint()
QPointF QCPItemRect::anchorPixelPoint (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 23381 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiLeft, aiRight, aiTop, aiTopRight, bottomRight, QCPItemPosition::pixelPoint(), and topLeft.
anchorPixelPosition()
QPointF QCPItemRect::anchorPixelPosition (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 30637 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiLeft, aiRight, aiTop, aiTopRight, bottomRight, QCPItemPosition::pixelPosition(), and topLeft.
brush() [1/2]
QBrush QCPItemRect::brush () const inline
Definition at line 7385 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
brush() [2/2]
QBrush QCPItemRect::brush () const inline
Definition at line 4034 of file qcustomplot.h.
draw() [1/2]
void QCPItemRect::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
Definition at line 30619 of file qcustomplot.cpp.
References bottomRight, QCPAbstractItem::clipRect(), mainBrush(), mainPen(), QCPItemPosition::pixelPosition(), QCPPainter::setPen(), and topLeft.
draw() [2/2]
virtual void QCPItemRect::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
mainBrush() [1/2]
QBrush QCPItemRect::mainBrush () const protected
Definition at line 30671 of file qcustomplot.cpp.
References mBrush, QCPAbstractItem::mSelected, and mSelectedBrush.
Referenced by draw().
mainBrush() [2/2]
QBrush QCPItemRect::mainBrush () const protected
mainPen() [1/2]
QPen QCPItemRect::mainPen () const protected
Definition at line 30664 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
mainPen() [2/2]
QPen QCPItemRect::mainPen () const protected
pen() [1/2]
QPen QCPItemRect::pen () const inline
Definition at line 7383 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
pen() [2/2]
QPen QCPItemRect::pen () const inline
Definition at line 4032 of file qcustomplot.h.
selectedBrush() [1/2]
QBrush QCPItemRect::selectedBrush () const inline
Definition at line 7386 of file qcustomplot.h.
selectedBrush() [2/2]
QBrush QCPItemRect::selectedBrush () const inline
Definition at line 4035 of file qcustomplot.h.
selectedPen() [1/2]
QPen QCPItemRect::selectedPen () const inline
Definition at line 7384 of file qcustomplot.h.
selectedPen() [2/2]
QPen QCPItemRect::selectedPen () const inline
Definition at line 4033 of file qcustomplot.h.
selectTest() [1/2]
double QCPItemRect::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 30605 of file qcustomplot.cpp.
References bottomRight, mBrush, QCPAbstractItem::mSelectable, QCPItemPosition::pixelPosition(), QCPAbstractItem::rectDistance(), and topLeft.
selectTest() [2/2]
virtual double QCPItemRect::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
setBrush() [1/2]
void QCPItemRect::setBrush (const QBrush & brush)
Sets the brush that will be used to fill the rectangle. To disable filling, set brush to Qt::NoBrush.
See also
setSelectedBrush, setPen
Definition at line 30592 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPItemRect().
setBrush() [2/2]
void QCPItemRect::setBrush (const QBrush & brush)
setPen() [1/2]
void QCPItemRect::setPen (const QPen & pen)
Sets the pen that will be used to draw the line of the rectangle
See also
setSelectedPen, setBrush
Definition at line 30577 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemRect().
setPen() [2/2]
void QCPItemRect::setPen (const QPen & pen)
setSelectedBrush() [1/2]
void QCPItemRect::setSelectedBrush (const QBrush & brush)
Sets the brush that will be used to fill the rectangle when selected. To disable filling, set brush to Qt::NoBrush.
See also
setBrush
Definition at line 30600 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPItemRect().
setSelectedBrush() [2/2]
void QCPItemRect::setSelectedBrush (const QBrush & brush)
setSelectedPen() [1/2]
void QCPItemRect::setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw the line of the rectangle when selected
See also
setPen, setSelected
Definition at line 30584 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemRect().
setSelectedPen() [2/2]
void QCPItemRect::setSelectedPen (const QPen & pen)
Member Data Documentation
bottom
QCPItemAnchor *const QCPItemRect::bottom
Definition at line 7404 of file qcustomplot.h.
bottomLeft
QCPItemAnchor *const QCPItemRect::bottomLeft
Definition at line 7405 of file qcustomplot.h.
bottomRight
QCPItemPosition *const QCPItemRect::bottomRight
Definition at line 7400 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), QCPItemRect(), and selectTest().
left
QCPItemAnchor *const QCPItemRect::left
Definition at line 7406 of file qcustomplot.h.
mBrush
QBrush QCPItemRect::mBrush protected
Definition at line 7420 of file qcustomplot.h.
Referenced by mainBrush(), selectTest(), and setBrush().
mPen
QPen QCPItemRect::mPen protected
Definition at line 7419 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
mSelectedBrush
QBrush QCPItemRect::mSelectedBrush protected
Definition at line 7420 of file qcustomplot.h.
Referenced by mainBrush(), and setSelectedBrush().
mSelectedPen
QPen QCPItemRect::mSelectedPen protected
Definition at line 7419 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
right
QCPItemAnchor *const QCPItemRect::right
Definition at line 7403 of file qcustomplot.h.
top
QCPItemAnchor *const QCPItemRect::top
Definition at line 7401 of file qcustomplot.h.
topLeft
QCPItemPosition *const QCPItemRect::topLeft
Definition at line 7399 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), QCPItemRect(), and selectTest().
topRight
QCPItemAnchor *const QCPItemRect::topRight
Definition at line 7402 of file qcustomplot.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp