ACloudViewer: G3Point::G3PointAction Class Reference
G3Point::G3PointAction Class Reference
#include <G3PointAction.h>
Classes
struct CloudAdaptor
Public Types
using KDTree = nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< float, CloudAdaptor >, CloudAdaptor, 3 >
Public Member Functions
G3PointAction (ccPointCloud *cloud, ecvMainAppInterface *app=nullptr)
~G3PointAction ()
void segment ()
void clusterAndOrClean ()
void getBorders ()
bool cluster ()
void fit ()
void exportResults ()
void plots ()
void showWolman (const Eigen::ArrayXf &d_sample, const Eigen::Array3d &dq_final, const Eigen::Array3d &edq)
bool wolman ()
bool angles ()
bool processNewStacks (std::vector< std::vector< int >> &newStacks, int pointCount)
bool buildStacksFromG3PointLabelSF (cloudViewer::ScalarField *g3PointLabel)
bool merge (XXb &condition)
bool keep (Xb &condition)
bool cleanLabels ()
void clean ()
Static Public Member Functions
static void createAction (ecvMainAppInterface *appInterface)
static void GetG3PointAction (ccPointCloud *cloud, ecvMainAppInterface *app=nullptr)
template<typename T >
static bool EigenArrayToFile (QString name, T array)
Detailed Description
Definition at line 29 of file G3PointAction.h.
Member Typedef Documentation
KDTree
using G3Point::G3PointAction::KDTree = nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor<float, CloudAdaptor>, CloudAdaptor, 3 >
Definition at line 93 of file G3PointAction.h.
Constructor & Destructor Documentation
G3PointAction()
G3Point::G3PointAction::G3PointAction (ccPointCloud * cloud, ecvMainAppInterface * app = nullptr) explicit
Definition at line 56 of file G3PointAction.cpp.
Referenced by GetG3PointAction().
~G3PointAction()
G3Point::G3PointAction::~G3PointAction ()
Definition at line 62 of file G3PointAction.cpp.
Member Function Documentation
angles()
bool G3Point::G3PointAction::angles ()
Definition at line 1257 of file G3PointAction.cpp.
References CVLog::Error(), G3PointDialog::getAnglesNbBins(), ccObject::getName(), GrainsAsEllipsoids::m_center, M_PI, and GrainsAsEllipsoids::m_rotationMatrix.
Referenced by plots().
buildStacksFromG3PointLabelSF()
bool G3Point::G3PointAction::buildStacksFromG3PointLabelSF (cloudViewer::ScalarField * g3PointLabel)
Definition at line 629 of file G3PointAction.cpp.
References cloudViewer::ScalarField::getValue(), processNewStacks(), and cloudViewer::PointCloudTpl< T >::size().
Referenced by fit().
clean()
void G3Point::G3PointAction::clean ()
Definition at line 2094 of file G3PointAction.cpp.
cleanLabels()
bool G3Point::G3PointAction::cleanLabels ()
Definition at line 1317 of file G3PointAction.cpp.
References CVLog::Error(), G3PointDialog::getMaxAngle2(), G3PointDialog::getMinFlatness(), G3PointDialog::getNMin(), cloudViewer::PointCloudTpl< T >::getPoint(), keep(), merge(), points, CVLog::Print(), point::x, and point::y.
Referenced by clusterAndOrClean().
cluster()
bool G3Point::G3PointAction::cluster ()
Definition at line 795 of file G3PointAction.cpp.
References CVLog::Error(), G3PointDialog::getMaxAngle1(), cloudViewer::PointCloudTpl< T >::getPoint(), G3PointDialog::getRadiusFactor(), and CVLog::Print().
Referenced by clusterAndOrClean().
clusterAndOrClean()
void G3Point::G3PointAction::clusterAndOrClean ()
Definition at line 1975 of file G3PointAction.cpp.
References G3PointDialog::cleanIsChecked(), cleanLabels(), cluster(), G3PointDialog::clusterIsChecked(), and CVLog::Error().
createAction()
void G3Point::G3PointAction::createAction (ecvMainAppInterface * appInterface) static
Definition at line 2210 of file G3PointAction.cpp.
References GetG3PointAction(), ccObject::isA(), CV_TYPES::POINT_CLOUD, and ccHObjectCaster::ToPointCloud().
EigenArrayToFile()
template<typename T > bool G3Point::G3PointAction::EigenArrayToFile (QString name, T array) static
Definition at line 787 of file G3PointAction.cpp.
References name.
exportResults()
void G3Point::G3PointAction::exportResults ()
Definition at line 1033 of file G3PointAction.cpp.
References GrainsAsEllipsoids::exportResultsAsCloud().
fit()
void G3Point::G3PointAction::fit ()
Definition at line 976 of file G3PointAction.cpp.
References ccHObject::addChild(), G3PointDialog::allClicked(), buildStacksFromG3PointLabelSF(), G3PointDialog::drawLines(), GrainsAsEllipsoids::drawLines(), G3PointDialog::drawPoints(), GrainsAsEllipsoids::drawPoints(), G3PointDialog::drawSurfaces(), GrainsAsEllipsoids::drawSurfaces(), G3PointDialog::emitSignals(), G3Point::getRandomColors(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), G3PointDialog::glPointSize(), G3PointDialog::onlyOneChanged(), G3PointDialog::onlyOneClicked(), GrainsAsEllipsoids::setGLPointSize(), ccObject::setName(), GrainsAsEllipsoids::setOnlyOne(), G3PointDialog::setOnlyOneMax(), GrainsAsEllipsoids::setTransparency(), GrainsAsEllipsoids::showAll(), GrainsAsEllipsoids::showOnlyOne(), G3PointDialog::transparencyChanged(), and CVLog::Warning().
getBorders()
void G3Point::G3PointAction::getBorders ()
Definition at line 1999 of file G3PointAction.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), ccHObject::DP_PARENT_OF_OTHER, ccObject::getName(), ccHObject::getParent(), ccPointCloud::partialClone(), ccObject::setName(), and cloudViewer::PointCloudTpl< T >::size().
GetG3PointAction()
void G3Point::G3PointAction::GetG3PointAction (ccPointCloud * cloud, ecvMainAppInterface * app = nullptr) static
Definition at line 70 of file G3PointAction.cpp.
References G3PointAction(), ccObject::getName(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), CVLog::Print(), G3PointDisclaimer::show(), and CVLog::Warning().
Referenced by createAction().
keep()
bool G3Point::G3PointAction::keep (Xb & condition)
Definition at line 761 of file G3PointAction.cpp.
References CVLog::Error(), CVLog::Print(), and processNewStacks().
Referenced by cleanLabels().
merge()
bool G3Point::G3PointAction::merge (XXb & condition)
Definition at line 657 of file G3PointAction.cpp.
References CVLog::Error(), CVLog::Print(), processNewStacks(), and cloudViewer::PointCloudTpl< T >::size().
Referenced by cleanLabels().
plots()
void G3Point::G3PointAction::plots ()
Definition at line 1082 of file G3PointAction.cpp.
References angles().
processNewStacks()
bool G3Point::G3PointAction::processNewStacks (std::vector< std::vector< int >> & newStacks, int pointCount)
Definition at line 609 of file G3PointAction.cpp.
References CVLog::Error().
Referenced by buildStacksFromG3PointLabelSF(), keep(), and merge().
segment()
void G3Point::G3PointAction::segment ()
Definition at line 1920 of file G3PointAction.cpp.
References G3PointDialog::enableClusterAndOrClean(), CVLog::Error(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::PointCloudTpl< T >::size(), Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
showWolman()
void G3Point::G3PointAction::showWolman (const Eigen::ArrayXf & d_sample, const Eigen::Array3d & dq_final, const Eigen::Array3d & edq)
Definition at line 1084 of file G3PointAction.cpp.
References ccObject::getName().
Referenced by wolman().
wolman()
bool G3Point::G3PointAction::wolman ()
Definition at line 1094 of file G3PointAction.cpp.
References G3Point::arange(), dist(), CVLog::Error(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::ScalarField::getValue(), G3PointDialog::getWolmanNbIter(), GrainsAsEllipsoids::m_center, GrainsAsEllipsoids::m_cloud, GrainsAsEllipsoids::m_fitNotOK, GrainsAsEllipsoids::m_radii, CVLog::Print(), G3Point::quant(), ecvProgressDialog::setMethodTitle(), showWolman(), cloudViewer::PointCloudTpl< T >::size(), G3Point::std_dev(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qG3Point/include/G3PointAction.h
/root/ACloudViewer/plugins/core/Standard/qG3Point/src/G3PointAction.cpp