ACloudViewer: VtkUtils::ModelToVtkTableConverter Class Reference
VtkUtils::ModelToVtkTableConverter Class Reference
#include <modeltovtktableconverter.h>
Public Member Functions
ModelToVtkTableConverter (TableModel *model)
void setLabels (const QStringList &labels)
QStringList labels () const
void run ()
vtkTable * table () const
Public Member Functions inherited from VtkUtils::SignalledRunnable
SignalledRunnable ()
Additional Inherited Members
Signals inherited from VtkUtils::SignalledRunnable
void finished ()
Detailed Description
Definition at line 16 of file modeltovtktableconverter.h.
Constructor & Destructor Documentation
ModelToVtkTableConverter()
VtkUtils::ModelToVtkTableConverter::ModelToVtkTableConverter (TableModel * model) explicit
Definition at line 19 of file modeltovtktableconverter.cpp.
Member Function Documentation
labels()
QStringList VtkUtils::ModelToVtkTableConverter::labels () const
Definition at line 26 of file modeltovtktableconverter.cpp.
Referenced by setLabels().
run()
void VtkUtils::ModelToVtkTableConverter::run ()
Definition at line 28 of file modeltovtktableconverter.cpp.
References VtkUtils::TableModel::columnCount(), VtkUtils::TableModel::data(), VtkUtils::SignalledRunnable::finished(), VtkUtils::TableModel::rowCount(), and VtkUtils::vtkInitOnce().
setLabels()
void VtkUtils::ModelToVtkTableConverter::setLabels (const QStringList & labels)
Definition at line 22 of file modeltovtktableconverter.cpp.
References labels().
table()
vtkTable * VtkUtils::ModelToVtkTableConverter::table () const
Definition at line 60 of file modeltovtktableconverter.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/modeltovtktableconverter.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/modeltovtktableconverter.cpp