ACloudViewer: vtkPVTrivialProducer Class Reference
vtkPVTrivialProducer Class Reference
#include <vtkPVTrivialProducer.h>
Public Member Functions
vtkTypeMacro (vtkPVTrivialProducer, vtkTrivialProducer)
void PrintSelf (ostream &os, vtkIndent indent) override
void SetOutput (vtkDataObject *output) override
virtual void SetOutput (vtkDataObject *output, double time)
int ProcessRequest (vtkInformation *, vtkInformationVector **, vtkInformationVector *) override
Static Public Member Functions
static vtkPVTrivialProducer * New ()
Protected Member Functions
vtkPVTrivialProducer ()
~vtkPVTrivialProducer () override
Detailed Description
Definition at line 15 of file vtkPVTrivialProducer.h.
Constructor & Destructor Documentation
vtkPVTrivialProducer()
vtkPVTrivialProducer::vtkPVTrivialProducer () protected
Definition at line 50 of file vtkPVTrivialProducer.cxx.
~vtkPVTrivialProducer()
vtkPVTrivialProducer::~vtkPVTrivialProducer () override protected
Definition at line 56 of file vtkPVTrivialProducer.cxx.
Member Function Documentation
New()
static vtkPVTrivialProducer* vtkPVTrivialProducer::New () static
PrintSelf()
void vtkPVTrivialProducer::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 133 of file vtkPVTrivialProducer.cxx.
ProcessRequest()
int vtkPVTrivialProducer::ProcessRequest (vtkInformation * request, vtkInformationVector ** inputVector, vtkInformationVector * outputVector) override
Process upstream/downstream requests trivially. The associated output data object is never modified, but it is queried to fulfill requests.
Definition at line 85 of file vtkPVTrivialProducer.cxx.
SetOutput() [1/2]
void vtkPVTrivialProducer::SetOutput (vtkDataObject * output) override
Set the data object that is "produced" by this producer. It is never really modified.
Definition at line 66 of file vtkPVTrivialProducer.cxx.
Referenced by SetOutput(), and vtkDistributedTrivialProducer::UpdateFromGlobal().
SetOutput() [2/2]
void vtkPVTrivialProducer::SetOutput (vtkDataObject * output, double time) virtual
Set the output data object as well as time information for the requests.
Definition at line 72 of file vtkPVTrivialProducer.cxx.
References SetOutput().
vtkTypeMacro()
vtkPVTrivialProducer::vtkTypeMacro (vtkPVTrivialProducer , vtkTrivialProducer)
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkPVTrivialProducer.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkPVTrivialProducer.cxx