ACloudViewer: ccTraceTool Class Reference
ccTraceTool Class Reference
#include <ccTraceTool.h>
Public Member Functions
ccTraceTool ()
virtual ~ccTraceTool ()
void toolActivated () override
void toolDisactivated () override
void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccPointCloud *cloud, const CCVector3 &P) override
void onNewSelection (const ccHObject::Container &selectedEntities) override
void accept () override
void cancel () override
bool canUndo () override
void undo () override
Public Member Functions inherited from ccTool
virtual ~ccTool ()
void initializeTool (ecvMainAppInterface *app)
virtual void pointPicked (ccHObject *insertPoint, unsigned itemIdx, ccHObject *pickedObject, const CCVector3 &P)
Protected Member Functions
void finishCurrentTrace ()
bool pickupTrace (ccHObject *obj)
Protected Member Functions inherited from ccTool
ccTool ()
Protected Attributes
int m_trace_id
bool m_preExisting = false
bool m_changed = false
bool m_parentPlaneDeleted = false
bool m_childPlaneDeleted = false
bool m_precompute_gradient
bool m_precompute_curvature
Protected Attributes inherited from ccTool
ecvMainAppInterface * m_app
QWidget * m_window
Detailed Description
Definition at line 16 of file ccTraceTool.h.
Constructor & Destructor Documentation
ccTraceTool()
ccTraceTool::ccTraceTool ()
Definition at line 16 of file ccTraceTool.cpp.
~ccTraceTool()
ccTraceTool::~ccTraceTool () virtual
Definition at line 18 of file ccTraceTool.cpp.
Member Function Documentation
accept()
void ccTraceTool::accept () override virtual
Reimplemented from ccTool.
Definition at line 122 of file ccTraceTool.cpp.
References finishCurrentTrace().
Referenced by toolDisactivated().
cancel()
void ccTraceTool::cancel () override virtual
Reimplemented from ccTool.
Definition at line 128 of file ccTraceTool.cpp.
References ecvMainAppInterface::dbRootObject(), ccHObject::find(), ccTool::m_app, m_preExisting, m_trace_id, ecvMainAppInterface::removeFromDB(), and ccMeasurement::setActive().
canUndo()
bool ccTraceTool::canUndo () override virtual
Reimplemented from ccTool.
Definition at line 285 of file ccTraceTool.cpp.
Referenced by ccCompass::setTrace().
finishCurrentTrace()
void ccTraceTool::finishCurrentTrace () protected
Definition at line 162 of file ccTraceTool.cpp.
References ccHObject::addChild(), ecvMainAppInterface::addToDB(), ecvMainAppInterface::dbRootObject(), ccHObject::detachChild(), ecvMainAppInterface::dispToConsole(), ccTrace::finalizePath(), ccHObject::find(), ccTrace::fitPlane(), ccCompass::fitPlanes, ccObject::getName(), ccHObject::getParent(), ccTool::m_app, m_changed, m_childPlaneDeleted, m_parentPlaneDeleted, m_trace_id, ccCompass::mapMode, ecvDisplayTools::RedrawDisplay(), ccHObject::SELECTION_IGNORED, ccMeasurement::setActive(), ecvMainAppInterface::setSelectedInDB(), ccHObject::setSelectionBehavior(), ccDrawableObject::setVisible(), ccGenericMesh::showNormals(), ecvMainAppInterface::STD_CONSOLE_MESSAGE, and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by accept(), onNewSelection(), and pickupTrace().
onNewSelection()
void ccTraceTool::onNewSelection (const ccHObject::Container & selectedEntities) override virtual
Reimplemented from ccTool.
Definition at line 144 of file ccTraceTool.cpp.
References finishCurrentTrace(), m_trace_id, and pickupTrace().
Referenced by toolActivated().
pickupTrace()
bool ccTraceTool::pickupTrace (ccHObject * obj) protected
Definition at line 244 of file ccTraceTool.cpp.
References ccHObject::addChild(), ecvMainAppInterface::addToDB(), ccHObject::detachChild(), finishCurrentTrace(), ccHObject::getChild(), ccHObject::getChildrenNumber(), ccHObject::getParent(), ccObject::getUniqueID(), ccFitPlane::isFitPlane(), ccTool::m_app, m_childPlaneDeleted, m_parentPlaneDeleted, m_preExisting, m_trace_id, ecvMainAppInterface::removeFromDB(), ccMeasurement::setActive(), and ccDrawableObject::setVisible().
Referenced by onNewSelection().
pointPicked()
void ccTraceTool::pointPicked (ccHObject * insertPoint, unsigned itemIdx, ccPointCloud * cloud, const CCVector3 & P) override virtual
Reimplemented from ccTool.
Definition at line 31 of file ccTraceTool.cpp.
References ccHObject::addChild(), ecvMainAppInterface::addToDB(), ccTrace::buildCurvatureCost(), ccTrace::buildGradientCost(), ccTrace::COST_MODE, ccTrace::CURVE, ecvMainAppInterface::dbRootObject(), ecvMainAppInterface::dispToConsole(), ccHObject::find(), ecvMainAppInterface::getMainWindow(), ccObject::getUniqueID(), ccTrace::GRADIENT, ccTrace::insertWaypoint(), ccTrace::isCurvaturePrecomputed(), ccTrace::isGradientPrecomputed(), ccTool::m_app, m_changed, m_precompute_curvature, m_precompute_gradient, m_preExisting, m_trace_id, ccTrace::optimizePath(), ecvMainAppInterface::removeFromDB(), ccMeasurement::setActive(), ccObject::setName(), ecvMainAppInterface::setSelectedInDB(), ccDrawableObject::setVisible(), cloudViewer::ReferenceCloud::size(), ccTrace::undoLast(), ccTrace::waypoint_count(), and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
toolActivated()
void ccTraceTool::toolActivated () override virtual
Reimplemented from ccTool.
Definition at line 21 of file ccTraceTool.cpp.
References ecvMainAppInterface::getSelectedEntities(), ccTool::m_app, and onNewSelection().
toolDisactivated()
void ccTraceTool::toolDisactivated () override virtual
Reimplemented from ccTool.
Definition at line 26 of file ccTraceTool.cpp.
References accept().
undo()
void ccTraceTool::undo () override virtual
Reimplemented from ccTool.
Definition at line 290 of file ccTraceTool.cpp.
References ecvMainAppInterface::dbRootObject(), ccHObject::find(), ccTool::m_app, m_trace_id, ccTrace::optimizePath(), ecvDisplayTools::RedrawDisplay(), and ccTrace::undoLast().
Member Data Documentation
m_changed
bool ccTraceTool::m_changed = false protected
Definition at line 63 of file ccTraceTool.h.
Referenced by finishCurrentTrace(), and pointPicked().
m_childPlaneDeleted
bool ccTraceTool::m_childPlaneDeleted = false protected
Definition at line 67 of file ccTraceTool.h.
Referenced by finishCurrentTrace(), and pickupTrace().
m_parentPlaneDeleted
bool ccTraceTool::m_parentPlaneDeleted = false protected
Definition at line 66 of file ccTraceTool.h.
Referenced by finishCurrentTrace(), and pickupTrace().
m_precompute_curvature
bool ccTraceTool::m_precompute_curvature protected
Initial value:
=
            true
Definition at line 71 of file ccTraceTool.h.
Referenced by pointPicked().
m_precompute_gradient
bool ccTraceTool::m_precompute_gradient protected
Initial value:
=
            true
Definition at line 69 of file ccTraceTool.h.
Referenced by pointPicked().
m_preExisting
bool ccTraceTool::m_preExisting = false protected
Definition at line 61 of file ccTraceTool.h.
Referenced by cancel(), pickupTrace(), and pointPicked().
m_trace_id
int ccTraceTool::m_trace_id protected
Initial value:
=
            -1
Definition at line 58 of file ccTraceTool.h.
Referenced by cancel(), finishCurrentTrace(), onNewSelection(), pickupTrace(), pointPicked(), and undo().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCompass/include/ccTraceTool.h
/root/ACloudViewer/plugins/core/Standard/qCompass/src/ccTraceTool.cpp