ACloudViewer: SiftMatchGPU Class Reference
SiftMatchGPU Class Reference
matcher export
#include <SiftGPU.h>
Public Types
enum SIFTMATCH_LANGUAGE { SIFTMATCH_SAME_AS_SIFTGPU = 0 , SIFTMATCH_GLSL = 2 , SIFTMATCH_CUDA = 3 , SIFTMATCH_CUDA_DEVICE0 = 3 }
Public Member Functions
int CreateContextGL ()
int VerifyContextGL ()
SiftMatchGPU (int max_sift=4096)
virtual void SetLanguage (int gpu_language)
virtual void SetDeviceParam (int argc, char **argv)
virtual bool Allocate (int max_sift, int mbm)
virtual void SetMaxSift (int max_sift)
virtual int GetMaxSift () const
virtual ~SiftMatchGPU ()
virtual void SetDescriptors (int index, int num, const float *descriptors, int id=-1)
virtual void SetDescriptors (int index, int num, const unsigned char *descriptors, int id=-1)
virtual int GetSiftMatch (int max_match, uint32_t match_buffer[][2], float distmax=0.7, float ratiomax=0.8, int mutual_best_match=1)
virtual void SetFeautreLocation (int index, const float *locations, int gap=0)
void SetFeatureLocation (int index, const SiftGPU::SiftKeypoint *keys)
virtual int GetGuidedSiftMatch (int max_match, uint32_t match_buffer[][2], float *H, float *F, float distmax=0.7, float ratiomax=0.8, float hdistmax=32, float fdistmax=16, int mutual_best_match=1)
Public Attributes
int gpu_index = 0
Protected Member Functions
virtual int _CreateContextGL ()
virtual int _VerifyContextGL ()
Protected Attributes
int __max_sift
Detailed Description
matcher export
Definition at line 268 of file SiftGPU.h.
Member Enumeration Documentation
SIFTMATCH_LANGUAGE
enum SiftMatchGPU::SIFTMATCH_LANGUAGE
Enumerator
SIFTMATCH_SAME_AS_SIFTGPU
SIFTMATCH_GLSL
SIFTMATCH_CUDA
SIFTMATCH_CUDA_DEVICE0
Definition at line 271 of file SiftGPU.h.
Constructor & Destructor Documentation
SiftMatchGPU()
SiftMatchGPU::SiftMatchGPU (int max_sift = 4096) explicit
Definition at line 613 of file SiftMatch.cpp.
References __max_sift, max(), and NULL.
~SiftMatchGPU()
SiftMatchGPU::~SiftMatchGPU () virtual
Definition at line 656 of file SiftMatch.cpp.
Member Function Documentation
_CreateContextGL()
int SiftMatchGPU::_CreateContextGL () protected virtual
Definition at line 559 of file SiftMatch.cpp.
References GlobalUtil::CreateWindowEZ(), SIFTMATCH_CUDA, and VerifyContextGL().
Referenced by CreateContextGL().
_VerifyContextGL()
int SiftMatchGPU::_VerifyContextGL () protected virtual
Definition at line 575 of file SiftMatch.cpp.
References __max_sift, GlobalParam::_DeviceIndex, GlobalParam::_GoodOpenGL, GlobalParam::_UseCUDA, GlobalParam::_verbose, GlobalUtil::InitGLParam(), SIFTMATCH_CUDA, SIFTMATCH_GLSL, and SIFTMATCH_SAME_AS_SIFTGPU.
Referenced by VerifyContextGL().
Allocate()
bool SiftMatchGPU::Allocate (int max_sift, int mbm) virtual
Reimplemented in SiftMatchGL.
Definition at line 636 of file SiftMatch.cpp.
References __max_sift, and Allocate().
Referenced by Allocate().
CreateContextGL()
int SiftMatchGPU::CreateContextGL () inline
Definition at line 291 of file SiftGPU.h.
References _CreateContextGL().
GetGuidedSiftMatch()
int SiftMatchGPU::GetGuidedSiftMatch (int max_match, uint32_t match_buffer[][2], float * H, float * F, float distmax = 0.7, float ratiomax = 0.8, float hdistmax = 32, float fdistmax = 16, int mutual_best_match = 1) virtual
Reimplemented in SiftMatchGL.
Definition at line 676 of file SiftMatch.cpp.
References GetGuidedSiftMatch(), GetSiftMatch(), and NULL.
Referenced by GetGuidedSiftMatch().
GetMaxSift()
virtual int SiftMatchGPU::GetMaxSift () const inline virtual
Definition at line 311 of file SiftGPU.h.
References __max_sift.
GetSiftMatch()
int SiftMatchGPU::GetSiftMatch (int max_match, uint32_t match_buffer[][2], float distmax = 0.7, float ratiomax = 0.8, int mutual_best_match = 1) virtual
Reimplemented in SiftMatchGL.
Definition at line 691 of file SiftMatch.cpp.
References GetSiftMatch().
Referenced by GetGuidedSiftMatch(), and GetSiftMatch().
SetDescriptors() [1/2]
void SiftMatchGPU::SetDescriptors (int index, int num, const float * descriptors, int id = -1) virtual
Reimplemented in SiftMatchGL.
Definition at line 666 of file SiftMatch.cpp.
References descriptors, and SetDescriptors().
Referenced by SetDescriptors().
SetDescriptors() [2/2]
void SiftMatchGPU::SetDescriptors (int index, int num, const unsigned char * descriptors, int id = -1) virtual
Reimplemented in SiftMatchGL.
Definition at line 661 of file SiftMatch.cpp.
References descriptors, and SetDescriptors().
SetDeviceParam()
void SiftMatchGPU::SetDeviceParam (int argc, char ** argv) virtual
Definition at line 630 of file SiftMatch.cpp.
References GlobalUtil::SetDeviceParam().
SetFeatureLocation()
void SiftMatchGPU::SetFeatureLocation (int index, const SiftGPU::SiftKeypoint * keys) inline
Definition at line 336 of file SiftGPU.h.
References SetFeautreLocation().
SetFeautreLocation()
void SiftMatchGPU::SetFeautreLocation (int index, const float * locations, int gap = 0) virtual
Reimplemented in SiftMatchGL.
Definition at line 671 of file SiftMatch.cpp.
References SetFeautreLocation().
Referenced by SetFeatureLocation(), and SetFeautreLocation().
SetLanguage()
void SiftMatchGPU::SetLanguage (int gpu_language) virtual
Definition at line 620 of file SiftMatch.cpp.
References GlobalParam::_DeviceIndex, and SIFTMATCH_CUDA.
SetMaxSift()
void SiftMatchGPU::SetMaxSift (int max_sift) virtual
Reimplemented in SiftMatchGL.
Definition at line 646 of file SiftMatch.cpp.
References __max_sift, max(), and SetMaxSift().
Referenced by SetMaxSift().
VerifyContextGL()
int SiftMatchGPU::VerifyContextGL () inline
Definition at line 292 of file SiftGPU.h.
References _VerifyContextGL().
Referenced by _CreateContextGL().
Member Data Documentation
__max_sift
int SiftMatchGPU::__max_sift protected
Definition at line 285 of file SiftGPU.h.
Referenced by _VerifyContextGL(), Allocate(), GetMaxSift(), SiftMatchGL::SetDescriptors(), SetMaxSift(), SiftMatchGL::SetMaxSift(), SiftMatchGL::SiftMatchGL(), and SiftMatchGPU().
gpu_index
int SiftMatchGPU::gpu_index = 0
Definition at line 278 of file SiftGPU.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/SiftGPU.h
/root/ACloudViewer/libs/Reconstruction/lib/SiftGPU/SiftMatch.cpp