ACloudViewer: ecvGenericTransformTool Class Reference
ecvGenericTransformTool Class Reference abstract
Generic Annotation Tool interface.
#include <ecvGenericTransformTool.h>
Public Types
enum RotationMode { R_XYZ , R_X , R_Y , R_Z }
Default constructor.
enum TranslationMOde {
T_X , T_Y , T_Z , T_XY ,
T_XZ , T_ZY , T_XYZ , T_NONE
}
Signals
void tranformMatrix (const ccGLMatrixd &transMatrix)
Public Member Functions
ecvGenericTransformTool ()
virtual ~ecvGenericTransformTool ()=default
ccHObject * getAssociatedEntity ()
virtual void setVisualizer (ecvGenericVisualizer3D *viewer=nullptr)=0
virtual bool setInputData (ccHObject *entity, int viewport=0)
virtual void showInteractor (bool state)=0
virtual bool start ()=0
virtual void stop ()=0
virtual void reset ()=0
virtual void clear ()=0
virtual void setTranlationMode (TranslationMOde mode)=0
virtual void setRotationMode (RotationMode mode)=0
virtual void setScaleEnabled (bool state)=0
virtual void setShearEnabled (bool state)=0
virtual const ccGLMatrixd getFinalTransformation ()=0
virtual void getOutput (std::vector< ccHObject * > &out)=0
Protected Attributes
ccHObject * m_associatedEntity
Detailed Description
Generic Annotation Tool interface.
Definition at line 20 of file ecvGenericTransformTool.h.
Member Enumeration Documentation
RotationMode
enum ecvGenericTransformTool::RotationMode
Default constructor.
Parameters
mode Annotation mode
Enumerator
R_XYZ
R_X
R_Y
R_Z
Definition at line 28 of file ecvGenericTransformTool.h.
TranslationMOde
enum ecvGenericTransformTool::TranslationMOde
Enumerator
T_X
T_Y
T_Z
T_XY
T_XZ
T_ZY
T_XYZ
T_NONE
Definition at line 30 of file ecvGenericTransformTool.h.
Constructor & Destructor Documentation
ecvGenericTransformTool()
ecvGenericTransformTool::ecvGenericTransformTool ()
Definition at line 12 of file ecvGenericTransformTool.cpp.
~ecvGenericTransformTool()
virtual ecvGenericTransformTool::~ecvGenericTransformTool () virtual default
Member Function Documentation
clear()
virtual void ecvGenericTransformTool::clear () pure virtual
Implemented in PclTransformTool.
Referenced by ccGraphicalTransformationTool::clear(), and ccGraphicalTransformationTool::stop().
getAssociatedEntity()
ccHObject* ecvGenericTransformTool::getAssociatedEntity () inline
Definition at line 35 of file ecvGenericTransformTool.h.
Referenced by PclTransformTool::addActors(), and PclTransformTool::setInputData().
getFinalTransformation()
virtual const ccGLMatrixd ecvGenericTransformTool::getFinalTransformation () pure virtual
Implemented in PclTransformTool.
Referenced by ccGraphicalTransformationTool::apply().
getOutput()
virtual void ecvGenericTransformTool::getOutput (std::vector< ccHObject * > & out) pure virtual
Implemented in PclTransformTool.
Referenced by ccGraphicalTransformationTool::exportNewEntities().
reset()
virtual void ecvGenericTransformTool::reset () pure virtual
Implemented in PclTransformTool.
Referenced by ccGraphicalTransformationTool::reset().
setInputData()
bool ecvGenericTransformTool::setInputData (ccHObject * entity, int viewport = 0) virtual
Reimplemented in PclTransformTool.
Definition at line 15 of file ecvGenericTransformTool.cpp.
References m_associatedEntity.
Referenced by PclTransformTool::setInputData(), and ccGraphicalTransformationTool::start().
setRotationMode()
virtual void ecvGenericTransformTool::setRotationMode (RotationMode mode) pure virtual
Implemented in PclTransformTool.
Referenced by ccGraphicalTransformationTool::onRotationModeChanged().
setScaleEnabled()
virtual void ecvGenericTransformTool::setScaleEnabled (bool state) pure virtual
Implemented in PclTransformTool.
Referenced by ccGraphicalTransformationTool::onScaleEnabled().
setShearEnabled()
virtual void ecvGenericTransformTool::setShearEnabled (bool state) pure virtual
Implemented in PclTransformTool.
Referenced by ccGraphicalTransformationTool::onShearEnabled().
setTranlationMode()
virtual void ecvGenericTransformTool::setTranlationMode (TranslationMOde mode) pure virtual
Implemented in PclTransformTool.
Referenced by ccGraphicalTransformationTool::onTranlationModeChanged().
setVisualizer()
virtual void ecvGenericTransformTool::setVisualizer (ecvGenericVisualizer3D * viewer = nullptr) pure virtual
Implemented in PclTransformTool.
showInteractor()
virtual void ecvGenericTransformTool::showInteractor (bool state) pure virtual
Implemented in PclTransformTool.
Referenced by ccGraphicalTransformationTool::pause().
start()
virtual bool ecvGenericTransformTool::start () pure virtual
Implemented in PclTransformTool.
Referenced by ccGraphicalTransformationTool::start().
stop()
virtual void ecvGenericTransformTool::stop () pure virtual
Implemented in PclTransformTool.
Referenced by ccGraphicalTransformationTool::stop().
tranformMatrix
void ecvGenericTransformTool::tranformMatrix (const ccGLMatrixd & transMatrix) signal
Member Data Documentation
m_associatedEntity
ccHObject* ecvGenericTransformTool::m_associatedEntity protected
Definition at line 60 of file ecvGenericTransformTool.h.
Referenced by setInputData().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/ecvGenericTransformTool.h
/root/ACloudViewer/libs/CV_db/src/ecvGenericTransformTool.cpp