ACloudViewer: ccComputeOctreeDlg Class Reference
ccComputeOctreeDlg Class Reference
Dialog for octree computation.
#include <ecvComputeOctreeDlg.h>
Public Types
enum ComputationMode { DEFAULT , MIN_CELL_SIZE , CUSTOM_BBOX }
Computation mode.
Public Member Functions
ccComputeOctreeDlg (const ccBBox &baseBBox, double minCellSize, QWidget *parent=0)
Default constructor.
ComputationMode getMode () const
Returns octree computation mode.
double getMinCellSize () const
Returns cell size at max level.
ccBBox getCustomBBox () const
Returns custom bbox.
Protected Attributes
ccBoundingBoxEditorDlg * m_bbEditorDlg
Associated dialog.
Detailed Description
Dialog for octree computation.
Definition at line 18 of file ecvComputeOctreeDlg.h.
Member Enumeration Documentation
ComputationMode
enum ccComputeOctreeDlg::ComputationMode
Computation mode.
Enumerator
DEFAULT
MIN_CELL_SIZE
CUSTOM_BBOX
Definition at line 28 of file ecvComputeOctreeDlg.h.
Constructor & Destructor Documentation
ccComputeOctreeDlg()
ccComputeOctreeDlg::ccComputeOctreeDlg (const ccBBox & baseBBox, double minCellSize, QWidget * parent = 0)
Default constructor.
Definition at line 16 of file ecvComputeOctreeDlg.cpp.
References ccBoundingBoxEditorDlg::exec(), ccBoundingBoxEditorDlg::forceKeepSquare(), cloudViewer::BoundingBoxTpl< T >::isValid(), m_bbEditorDlg, cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, ccBoundingBoxEditorDlg::setBaseBBox(), and CVLog::Warning().
Member Function Documentation
getCustomBBox()
ccBBox ccComputeOctreeDlg::getCustomBBox () const
Returns custom bbox.
Definition at line 64 of file ecvComputeOctreeDlg.cpp.
References ccBoundingBoxEditorDlg::getBox(), and m_bbEditorDlg.
Referenced by ccEntityAction::computeOctree().
getMinCellSize()
double ccComputeOctreeDlg::getMinCellSize () const
Returns cell size at max level.
Definition at line 60 of file ecvComputeOctreeDlg.cpp.
Referenced by ccEntityAction::computeOctree().
getMode()
ccComputeOctreeDlg::ComputationMode ccComputeOctreeDlg::getMode () const
Returns octree computation mode.
Definition at line 49 of file ecvComputeOctreeDlg.cpp.
References CUSTOM_BBOX, DEFAULT, and MIN_CELL_SIZE.
Referenced by ccEntityAction::computeOctree().
Member Data Documentation
m_bbEditorDlg
ccBoundingBoxEditorDlg* ccComputeOctreeDlg::m_bbEditorDlg protected
Associated dialog.
Definition at line 41 of file ecvComputeOctreeDlg.h.
Referenced by ccComputeOctreeDlg(), and getCustomBBox().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvComputeOctreeDlg.h
/root/ACloudViewer/app/ecvComputeOctreeDlg.cpp