ACloudViewer: cloudViewer::t::io::RSBagReader Class Reference
cloudViewer::t::io::RSBagReader Class Reference
#include <RSBagReader.h>
Public Member Functions
RSBagReader (size_t buffer_size=DEFAULT_BUFFER_SIZE)
RSBagReader (const RSBagReader &)=delete
RSBagReader & operator= (const RSBagReader &)=delete
virtual ~RSBagReader ()
virtual bool IsOpened () const override
Check If the RSBag file is opened.
virtual bool IsEOF () const override
Check if the RSBag file is all read.
virtual bool Open (const std::string &filename) override
virtual void Close () override
Close the opened RSBag playback.
virtual const RGBDVideoMetadata & GetMetadata () const override
Get (read-only) metadata of the playback.
virtual RGBDVideoMetadata & GetMetadata () override
Get reference to the metadata of the RGBD video playback.
virtual bool SeekTimestamp (uint64_t timestamp) override
virtual uint64_t GetTimestamp () const override
Get current timestamp (in us).
virtual t::geometry::RGBDImage NextFrame () override
Copy next frame from the bag file and return the RGBDImage object.
virtual std::string GetFilename () const override
Return filename being read.
virtual void SaveFrames (const std::string &frame_path, uint64_t start_time_us=0, uint64_t end_time_us=UINT64_MAX)
virtual std::string ToString () const
Text description.
Public Member Functions inherited from cloudViewer::t::io::RGBDVideoReader
RGBDVideoReader ()
virtual ~RGBDVideoReader ()
virtual void SaveFrames (const std::string &frame_path, uint64_t start_time_us=0, uint64_t end_time_us=UINT64_MAX)
virtual std::string ToString () const
Text description.
Static Public Attributes
static const size_t DEFAULT_BUFFER_SIZE = 32
Additional Inherited Members
Static Public Member Functions inherited from cloudViewer::t::io::RGBDVideoReader
static std::unique_ptr< RGBDVideoReader > Create (const std::string &filename)
Factory function to create object based on RGBD video file type.
Detailed Description
RealSense Bag file reader.
Only the first color and depth streams from the bag file will be read.
The streams must have the same frame rate.
The color stream must have RGB 8 bit (RGB8/BGR8) pixel format
The depth stream must have 16 bit unsigned int (Z16) pixel format The output is synchronized color and depth frame pairs with the depth frame aligned to the color frame. Unsynchronized frames will be dropped. With alignment, the depth and color frames have the same viewpoint and resolution. See https://intelrealsense.github.io/librealsense/doxygen/rs__sensor_8h.html#ae04b7887ce35d16dbd9d2d295d23aac7 for format documentation
Note: A few frames may be dropped if user code takes a long time (>10 frame intervals) to process a frame.
Definition at line 49 of file RSBagReader.h.
Constructor & Destructor Documentation
RSBagReader() [1/2]
cloudViewer::t::io::RSBagReader::RSBagReader (size_t buffer_size = DEFAULT_BUFFER_SIZE) explicit
Constructor
Parameters
buffer_size (optional) Max number of frames to store in the frame buffer
Definition at line 35 of file RSBagReader.cpp.
RSBagReader() [2/2]
cloudViewer::t::io::RSBagReader::RSBagReader (const RSBagReader &) delete
~RSBagReader()
cloudViewer::t::io::RSBagReader::~RSBagReader () virtual
Definition at line 40 of file RSBagReader.cpp.
References Close(), and IsOpened().
Member Function Documentation
Close()
void cloudViewer::t::io::RSBagReader::Close () override virtual
Close the opened RSBag playback.
Implements cloudViewer::t::io::RGBDVideoReader.
Definition at line 77 of file RSBagReader.cpp.
Referenced by Open(), and ~RSBagReader().
GetFilename()
virtual std::string cloudViewer::t::io::RSBagReader::GetFilename () const inline override virtual
Return filename being read.
Implements cloudViewer::t::io::RGBDVideoReader.
Definition at line 97 of file RSBagReader.h.
GetMetadata() [1/2]
virtual const RGBDVideoMetadata& cloudViewer::t::io::RSBagReader::GetMetadata () const inline override virtual
Get (read-only) metadata of the playback.
Implements cloudViewer::t::io::RGBDVideoReader.
Definition at line 78 of file RSBagReader.h.
GetMetadata() [2/2]
virtual RGBDVideoMetadata& cloudViewer::t::io::RSBagReader::GetMetadata () inline override virtual
Get reference to the metadata of the RGBD video playback.
Implements cloudViewer::t::io::RGBDVideoReader.
Definition at line 83 of file RSBagReader.h.
GetTimestamp()
uint64_t cloudViewer::t::io::RSBagReader::GetTimestamp () const override virtual
Get current timestamp (in us).
Implements cloudViewer::t::io::RGBDVideoReader.
Definition at line 211 of file RSBagReader.cpp.
References IsOpened(), and LogWarning.
IsEOF()
bool cloudViewer::t::io::RSBagReader::IsEOF () const override virtual
Check if the RSBag file is all read.
Implements cloudViewer::t::io::RGBDVideoReader.
Definition at line 167 of file RSBagReader.cpp.
IsOpened()
virtual bool cloudViewer::t::io::RSBagReader::IsOpened () const inline override virtual
Check If the RSBag file is opened.
Implements cloudViewer::t::io::RGBDVideoReader.
Definition at line 64 of file RSBagReader.h.
Referenced by GetTimestamp(), NextFrame(), Open(), SeekTimestamp(), and ~RSBagReader().
NextFrame()
t::geometry::RGBDImage cloudViewer::t::io::RSBagReader::NextFrame () override virtual
Copy next frame from the bag file and return the RGBDImage object.
Implements cloudViewer::t::io::RGBDVideoReader.
Definition at line 169 of file RSBagReader.cpp.
References cloudViewer::t::io::RGBDVideoMetadata::fps_, IsOpened(), LogError, and LogInfo.
Open()
bool cloudViewer::t::io::RSBagReader::Open (const std::string & filename) override virtual
Open an RGBD Video playback.
Parameters
filename Path to the RSBag file.
Implements cloudViewer::t::io::RGBDVideoReader.
Definition at line 44 of file RSBagReader.cpp.
References Close(), cloudViewer::t::io::RGBDVideoMetadata::ConvertFromJsonValue(), error(), cloudViewer::t::io::RealSenseSensorConfig::GetMetadataJson(), cloudViewer::t::io::RealSenseSensorConfig::GetPixelDtypes(), IsOpened(), LogInfo, LogWarning, and profile.
Referenced by SeekTimestamp().
operator=()
RSBagReader& cloudViewer::t::io::RSBagReader::operator= (const RSBagReader &) delete
SaveFrames()
void cloudViewer::t::io::RGBDVideoReader::SaveFrames
Save synchronized and aligned individual frames to subfolders.
Parameters
frame_path Frames will be stored in stream subfolders 'color' and 'depth' here. The intrinsic camera calibration for the color stream will be saved in 'intrinsic.json'.
start_time_us (default 0) Start saving frames from this time (us)
end_time_us (default video length) Save frames till this time (us)
Definition at line 62 of file RGBDVideoReader.cpp.
SeekTimestamp()
bool cloudViewer::t::io::RSBagReader::SeekTimestamp (uint64_t timestamp) override virtual
Seek to the timestamp (in us).
Parameters
timestamp Time in us to seek to.
Implements cloudViewer::t::io::RGBDVideoReader.
Definition at line 192 of file RSBagReader.cpp.
References IsOpened(), LogWarning, Open(), and cloudViewer::t::io::RGBDVideoMetadata::stream_length_usec_.
ToString()
std::string cloudViewer::t::io::RGBDVideoReader::ToString
Text description.
Definition at line 70 of file RGBDVideoReader.cpp.
Member Data Documentation
DEFAULT_BUFFER_SIZE
const size_t cloudViewer::t::io::RSBagReader::DEFAULT_BUFFER_SIZE = 32 static
Definition at line 51 of file RSBagReader.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/t/io/sensor/realsense/RSBagReader.h
/root/ACloudViewer/libs/cloudViewer/t/io/sensor/realsense/RSBagReader.cpp