ACloudViewer: PclUtils::renders::TextureRendererBase Class Reference
PclUtils::renders::TextureRendererBase Class Reference abstract
Base class for all texture renderers.
#include <TextureRendererBase.h>
Public Member Functions
TextureRendererBase ()=default
virtual ~TextureRendererBase ()=default
virtual bool CanHandle (size_t material_count, bool has_pbr_textures, bool has_multiple_map_kd) const =0
Check if this renderer can handle the given material.
virtual RenderingMode GetMode () const =0
Get the rendering mode this renderer implements.
virtual bool Apply (vtkLODActor *actor, const class ccMaterialSet *materials, vtkPolyData *polydata, vtkRenderer *renderer)=0
Apply rendering to actor.
virtual bool Update (vtkActor *actor, const class ccMaterialSet *materials, vtkPolyData *polydata, vtkRenderer *renderer)=0
Update existing actor with new materials.
virtual std::string GetName () const =0
Get renderer name for logging.
Protected Member Functions
void ClearTextures (vtkActor *actor)
Helper: Clear all textures from actor.
bool ValidateActor (vtkActor *actor) const
Helper: Validate actor.
bool ValidateMaterials (const class ccMaterialSet *materials) const
Helper: Validate materials.
Detailed Description
Base class for all texture renderers.
Provides common interface and shared functionality for different rendering modes. Subclasses implement specific rendering logic (PBR, multi-texture, etc.)
Definition at line 48 of file TextureRendererBase.h.
Constructor & Destructor Documentation
TextureRendererBase()
PclUtils::renders::TextureRendererBase::TextureRendererBase () default
~TextureRendererBase()
virtual PclUtils::renders::TextureRendererBase::~TextureRendererBase () virtual default
Member Function Documentation
Apply()
virtual bool PclUtils::renders::TextureRendererBase::Apply (vtkLODActor * actor, const class ccMaterialSet * materials, vtkPolyData * polydata, vtkRenderer * renderer) pure virtual
Apply rendering to actor.
Parameters
actor VTK actor to render
materials Material set
polydata Polygon data (for texture coordinates)
renderer VTK renderer (for lighting setup)
Returns
true on success
Implemented in PclUtils::renders::MultiTextureRenderer, and PclUtils::renders::PBRRenderer.
Referenced by PclUtils::renders::TextureRenderManager::Apply().
CanHandle()
virtual bool PclUtils::renders::TextureRendererBase::CanHandle (size_t material_count, bool has_pbr_textures, bool has_multiple_map_kd) const pure virtual
Check if this renderer can handle the given material.
Parameters
material_count Number of materials
has_pbr_textures Whether material has PBR textures
has_multiple_map_kd Whether material has multiple map_Kd textures
Returns
true if this renderer can handle the material
Implemented in PclUtils::renders::MultiTextureRenderer, and PclUtils::renders::PBRRenderer.
ClearTextures()
void PclUtils::renders::TextureRendererBase::ClearTextures (vtkActor * actor) protected
Helper: Clear all textures from actor.
Definition at line 20 of file TextureRendererBase.cpp.
Referenced by PclUtils::renders::MultiTextureRenderer::Apply().
GetMode()
virtual RenderingMode PclUtils::renders::TextureRendererBase::GetMode () const pure virtual
Get the rendering mode this renderer implements.
Implemented in PclUtils::renders::MultiTextureRenderer, and PclUtils::renders::PBRRenderer.
GetName()
virtual std::string PclUtils::renders::TextureRendererBase::GetName () const pure virtual
Get renderer name for logging.
Implemented in PclUtils::renders::MultiTextureRenderer, and PclUtils::renders::PBRRenderer.
Referenced by PclUtils::renders::TextureRenderManager::Apply(), and PclUtils::renders::TextureRenderManager::Update().
Update()
virtual bool PclUtils::renders::TextureRendererBase::Update (vtkActor * actor, const class ccMaterialSet * materials, vtkPolyData * polydata, vtkRenderer * renderer) pure virtual
Update existing actor with new materials.
Parameters
actor VTK actor to update
materials Material set
polydata Polygon data
renderer VTK renderer
Returns
true on success
Implemented in PclUtils::renders::MultiTextureRenderer, and PclUtils::renders::PBRRenderer.
Referenced by PclUtils::renders::TextureRenderManager::Update().
ValidateActor()
bool PclUtils::renders::TextureRendererBase::ValidateActor (vtkActor * actor) const protected
Helper: Validate actor.
Definition at line 28 of file TextureRendererBase.cpp.
References CVLog::Error().
Referenced by PclUtils::renders::PBRRenderer::Apply(), PclUtils::renders::MultiTextureRenderer::Apply(), PclUtils::renders::PBRRenderer::Update(), and PclUtils::renders::MultiTextureRenderer::Update().
ValidateMaterials()
bool PclUtils::renders::TextureRendererBase::ValidateMaterials (const class ccMaterialSet * materials) const protected
Helper: Validate materials.
Definition at line 36 of file TextureRendererBase.cpp.
References CVLog::Error(), and CVLog::Warning().
Referenced by PclUtils::renders::PBRRenderer::Apply(), PclUtils::renders::MultiTextureRenderer::Apply(), PclUtils::renders::PBRRenderer::Update(), and PclUtils::renders::MultiTextureRenderer::Update().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/PclUtils/renders/base/TextureRendererBase.h
/root/ACloudViewer/libs/PCLEngine/PclUtils/renders/base/TextureRendererBase.cpp