ACloudViewer: ecvViewportParameters Class Reference
ecvViewportParameters Class Reference
Standard parameters for GL displays/viewports.
#include <ecvViewportParameters.h>
Public Member Functions
ecvViewportParameters ()
Default constructor.
ecvViewportParameters (const ecvViewportParameters &params)
Copy constructor.
bool isSerializable () const override
Returns whether object is serializable of not.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
void setPivotPoint (const CCVector3d &P, bool autoUpdateFocal=true)
Sets the pivot point (for object-centered view mode)
const CCVector3d & getPivotPoint () const
Returns the pivot point (for object-centered view mode)
void setCameraCenter (const CCVector3d &C, bool autoUpdateFocal=true)
Sets the camera center.
const CCVector3d & getCameraCenter () const
Returns the camera center.
void setFocalDistance (double distance)
Sets the 'focal' distance.
double getFocalDistance () const
Computes the 'focal' distance.
ccGLMatrixd computeViewMatrix () const
Computes the view matrix.
ccGLMatrixd computeScaleMatrix (const QRect &glViewport) const
Computes the scale matrix.
CCVector3d getViewDir () const
Returns the viewing direction.
CCVector3d getUpDir () const
Returns the up direction.
const CCVector3d & getRotationCenter () const
Returns the view rotation 'center'.
double computeDistanceToHalfWidthRatio () const
Computes the ratio 'distance to half width' (based on the current FOV)
double computeDistanceToWidthRatio () const
Computes the ratio 'distance to width' (based on the current FOV)
double computeWidthAtFocalDist () const
Computes the object 'width' at the 'focal' distance.
double computePixelSize (int glWidth) const
Computes the pixel size at the 'focal' distance.
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Static Public Member Functions
static double IncrementToZNearCoef (int i, int iMax)
static int ZNearCoefToIncrement (double coef, int iMax)
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Public Attributes
ccGLMatrixd viewMat
Visualization matrix (rotation only)
float defaultPointSize
Point size.
float defaultLineWidth
Line width.
float pixelSize
Current pixel size (in 'current unit'/pixel)
float zoom
Current zoom.
bool perspectiveView
Perspective view state.
bool objectCenteredView
double zNearCoef
Theoretical perspective 'zNear' relative position.
double zNear
Actual perspective 'zNear' value.
double zFar
Actual perspective 'zFar' value.
CCVector3d focal
CCVector3d up
float fov_deg
Camera F.O.V. (field of view) in degrees.
float cameraAspectRatio
Camera aspect ratio.
Protected Attributes
double focalDistance
Focal distance.
CCVector3d pivotPoint
Rotation pivot point (for object-centered view modes)
CCVector3d cameraCenter
Camera center.
Additional Inherited Members
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Detailed Description
Standard parameters for GL displays/viewports.
Definition at line 18 of file ecvViewportParameters.h.
Constructor & Destructor Documentation
ecvViewportParameters() [1/2]
ecvViewportParameters::ecvViewportParameters ()
Default constructor.
ecvViewportParameters() [2/2]
ecvViewportParameters::ecvViewportParameters (const ecvViewportParameters & params)
Copy constructor.
Member Function Documentation
computeDistanceToHalfWidthRatio()
double ecvViewportParameters::computeDistanceToHalfWidthRatio () const
Computes the ratio 'distance to half width' (based on the current FOV)
Half width = ratio * distance = tan(fov / 2) * distance
Referenced by define_ccViewPortParameters().
computeDistanceToWidthRatio()
double ecvViewportParameters::computeDistanceToWidthRatio () const
Computes the ratio 'distance to width' (based on the current FOV)
Width = ratio * distance = (2 * tan(fov / 2)) * distance
Referenced by define_ccViewPortParameters().
computePixelSize()
double ecvViewportParameters::computePixelSize (int glWidth) const
Computes the pixel size at the 'focal' distance.
Referenced by define_ccViewPortParameters().
computeScaleMatrix()
ccGLMatrixd ecvViewportParameters::computeScaleMatrix (const QRect & glViewport) const
Computes the scale matrix.
computeViewMatrix()
ccGLMatrixd ecvViewportParameters::computeViewMatrix () const
Computes the view matrix.
Referenced by define_ccViewPortParameters(), and qAnimationDlg::init().
computeWidthAtFocalDist()
double ecvViewportParameters::computeWidthAtFocalDist () const
Computes the object 'width' at the 'focal' distance.
Referenced by define_ccViewPortParameters().
fromFile()
bool ecvViewportParameters::fromFile (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override virtual
Loads data from binary stream.
Parameters
in input file (already opened)
dataVersion file version (for version-specific deserialization)
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Returns
success
Note: When implementing, use dataVersion checks to handle different
versions:
if (dataVersion >= X) { read new field } else { use default value } This ensures forward compatibility with older file formats.
Reimplemented from ccSerializableObject.
getCameraCenter()
const CCVector3d& ecvViewportParameters::getCameraCenter () const inline
Returns the camera center.
Definition at line 46 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
getFocalDistance()
double ecvViewportParameters::getFocalDistance () const inline
Computes the 'focal' distance.
Definition at line 54 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
getPivotPoint()
const CCVector3d& ecvViewportParameters::getPivotPoint () const inline
Returns the pivot point (for object-centered view mode)
Definition at line 39 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
getRotationCenter()
const CCVector3d& ecvViewportParameters::getRotationCenter () const
Returns the view rotation 'center'.
The rotation center is defined as:
the pivot point in object-centered view mode
the camera center in viewer-centered view mode
Referenced by define_ccViewPortParameters().
getUpDir()
CCVector3d ecvViewportParameters::getUpDir () const
Returns the up direction.
This is the vertical direction of the screen (pointing 'upward') in the world coordinate system.
Referenced by define_ccViewPortParameters().
getViewDir()
CCVector3d ecvViewportParameters::getViewDir () const
Returns the viewing direction.
This is the direction normal to the screen (pointing 'forward') in the world coordinate system.
Referenced by define_ccViewPortParameters().
IncrementToZNearCoef()
static double ecvViewportParameters::IncrementToZNearCoef (int i, int iMax) static
Helper: converts an integer (increment) in [0 iMax] to a double (zNear) value in [0.001 1]
isSerializable()
bool ecvViewportParameters::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccSerializableObject.
Definition at line 27 of file ecvViewportParameters.h.
minimumFileVersion()
short ecvViewportParameters::minimumFileVersion () const override virtual
Returns the minimum file version required to save this instance.
To be overridden by subclasses to indicate their minimum required version. This enables the system to determine:
Forward compatibility: newer software can read older files (dataVersion check in fromFile)
Backward compatibility: determine minimum version needed to save current data
Returns
minimum file version required for this object
Implements ccSerializableObject.
setCameraCenter()
void ecvViewportParameters::setCameraCenter (const CCVector3d & C, bool autoUpdateFocal = true)
Sets the camera center.
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
setFocalDistance()
void ecvViewportParameters::setFocalDistance (double distance)
Sets the 'focal' distance.
Warning
changes the camera cener position in object-centered view mode
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
setPivotPoint()
void ecvViewportParameters::setPivotPoint (const CCVector3d & P, bool autoUpdateFocal = true)
Sets the pivot point (for object-centered view mode)
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
toFile()
bool ecvViewportParameters::toFile (QFile & out, short dataVersion) const override virtual
Saves data to binary stream.
Parameters
out output file (already opened)
dataVersion target file version (for forward/backward compatibility)
Returns
success
Reimplemented from ccSerializableObject.
ZNearCoefToIncrement()
static int ecvViewportParameters::ZNearCoefToIncrement (double coef, int iMax) static
Helper: converts a double (zNear) value in ]0 1] to integer increments in [0 iMax]
Member Data Documentation
cameraAspectRatio
float ecvViewportParameters::cameraAspectRatio
Camera aspect ratio.
Definition at line 146 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
cameraCenter
CCVector3d ecvViewportParameters::cameraCenter protected
Camera center.
Definition at line 156 of file ecvViewportParameters.h.
defaultLineWidth
float ecvViewportParameters::defaultLineWidth
Line width.
Definition at line 112 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
defaultPointSize
float ecvViewportParameters::defaultPointSize
Point size.
Definition at line 110 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
focal
CCVector3d ecvViewportParameters::focal
Definition at line 139 of file ecvViewportParameters.h.
focalDistance
double ecvViewportParameters::focalDistance protected
Focal distance.
Definition at line 150 of file ecvViewportParameters.h.
fov_deg
float ecvViewportParameters::fov_deg
Camera F.O.V. (field of view) in degrees.
Definition at line 144 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
objectCenteredView
bool ecvViewportParameters::objectCenteredView
Whether view is centered on displayed scene (true) or on the user eye (false) Always true for ortho. mode.
Definition at line 130 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters().
perspectiveView
bool ecvViewportParameters::perspectiveView
Perspective view state.
Definition at line 125 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters(), ccPointPair::drawMeOnly(), and ccTrace::drawMeOnly().
pivotPoint
CCVector3d ecvViewportParameters::pivotPoint protected
Rotation pivot point (for object-centered view modes)
Definition at line 153 of file ecvViewportParameters.h.
pixelSize
float ecvViewportParameters::pixelSize
Current pixel size (in 'current unit'/pixel)
This scale is valid eveywhere in ortho. mode or at the focal distance in perspective mode. Warning: doesn't take current zoom into account!
Definition at line 119 of file ecvViewportParameters.h.
up
CCVector3d ecvViewportParameters::up
Definition at line 141 of file ecvViewportParameters.h.
viewMat
ccGLMatrixd ecvViewportParameters::viewMat
Visualization matrix (rotation only)
Definition at line 107 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
zFar
double ecvViewportParameters::zFar
Actual perspective 'zFar' value.
Definition at line 137 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters(), ccPointPair::drawMeOnly(), ccTrace::drawMeOnly(), and ViewInterpolate::interpolate().
zNear
double ecvViewportParameters::zNear
Actual perspective 'zNear' value.
Definition at line 135 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
zNearCoef
double ecvViewportParameters::zNearCoef
Theoretical perspective 'zNear' relative position.
Definition at line 133 of file ecvViewportParameters.h.
Referenced by define_ccViewPortParameters(), and ViewInterpolate::interpolate().
zoom
float ecvViewportParameters::zoom
Current zoom.
Definition at line 122 of file ecvViewportParameters.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/eCV_db/include/ecvViewportParameters.h