ACloudViewer: flann::HierarchicalClusteringIndex< Distance > Class Template Reference
flann::HierarchicalClusteringIndex< Distance > Class Template Reference
#include <hierarchical_clustering_index.h>
Public Types
typedef Distance::ElementType ElementType
typedef Distance::ResultType DistanceType
typedef NNIndex< Distance > BaseClass
Public Types inherited from flann::NNIndex< Distance >
typedef Distance::ElementType ElementType
typedef Distance::ResultType DistanceType
Public Member Functions
HierarchicalClusteringIndex (const IndexParams &index_params=HierarchicalClusteringIndexParams(), Distance d=Distance())
HierarchicalClusteringIndex (const Matrix< ElementType > &inputData, const IndexParams &index_params=HierarchicalClusteringIndexParams(), Distance d=Distance())
HierarchicalClusteringIndex (const HierarchicalClusteringIndex &other)
HierarchicalClusteringIndex & operator= (HierarchicalClusteringIndex other)
void initCenterChooser ()
virtual ~HierarchicalClusteringIndex ()
BaseClass * clone () const
int usedMemory () const
void addPoints (const Matrix< ElementType > &points, float rebuild_threshold=2)
Incrementally add points to the index.
flann_algorithm_t getType () const
template<typename Archive >
void serialize (Archive &ar)
void saveIndex (FILE *stream)
void loadIndex (FILE *stream)
void findNeighbors (ResultSet< DistanceType > &result, const ElementType *vec, const SearchParams &searchParams) const
virtual void buildIndex ()
virtual void buildIndex (const Matrix< ElementType > &dataset)
Public Member Functions inherited from flann::NNIndex< Distance >
NNIndex (Distance d)
NNIndex (const IndexParams &params, Distance d)
NNIndex (const NNIndex &other)
virtual ~NNIndex ()
virtual void buildIndex (const Matrix< ElementType > &dataset)
virtual void removePoint (size_t id)
virtual ElementType * getPoint (size_t id)
size_t size () const
size_t veclen () const
IndexParams getParameters () const
template<typename Archive >
void serialize (Archive &ar)
virtual int knnSearch (const Matrix< ElementType > &queries, Matrix< size_t > &indices, Matrix< DistanceType > &dists, size_t knn, const SearchParams &params) const
Perform k-nearest neighbor search.
int knnSearch (const Matrix< ElementType > &queries, Matrix< int > &indices, Matrix< DistanceType > &dists, size_t knn, const SearchParams &params) const
int knnSearch (const Matrix< ElementType > &queries, std::vector< std::vector< size_t > > &indices, std::vector< std::vector< DistanceType > > &dists, size_t knn, const SearchParams &params) const
Perform k-nearest neighbor search.
int knnSearch (const Matrix< ElementType > &queries, std::vector< std::vector< int > > &indices, std::vector< std::vector< DistanceType > > &dists, size_t knn, const SearchParams &params) const
int radiusSearch (const Matrix< ElementType > &queries, Matrix< size_t > &indices, Matrix< DistanceType > &dists, float radius, const SearchParams &params) const
Perform radius search.
int radiusSearch (const Matrix< ElementType > &queries, Matrix< int > &indices, Matrix< DistanceType > &dists, float radius, const SearchParams &params) const
int radiusSearch (const Matrix< ElementType > &queries, std::vector< std::vector< size_t > > &indices, std::vector< std::vector< DistanceType > > &dists, float radius, const SearchParams &params) const
Perform radius search.
int radiusSearch (const Matrix< ElementType > &queries, std::vector< std::vector< int > > &indices, std::vector< std::vector< DistanceType > > &dists, float radius, const SearchParams &params) const
Public Member Functions inherited from flann::IndexBase
virtual ~IndexBase ()
Protected Member Functions
void buildIndexImpl ()
Protected Member Functions inherited from flann::NNIndex< Distance >
size_t id_to_index (size_t id)
void indices_to_ids (const size_t *in, size_t *out, size_t size) const
void setDataset (const Matrix< ElementType > &dataset)
void extendDataset (const Matrix< ElementType > &new_points)
void cleanRemovedPoints ()
void swap (NNIndex &other)
Additional Inherited Members
Protected Attributes inherited from flann::NNIndex< Distance >
Distance distance_
size_t last_id_
size_t size_
size_t size_at_build_
size_t veclen_
IndexParams index_params_
bool removed_
DynamicBitset removed_points_
size_t removed_count_
std::vector< size_t > ids_
std::vector< ElementType * > points_
ElementType * data_ptr_
Detailed Description
template<typename Distance>
class flann::HierarchicalClusteringIndex< Distance >
Hierarchical index
Contains a tree constructed through a hierarchical clustering and other information for indexing a set of points for nearest-neighbour matching.
Definition at line 86 of file hierarchical_clustering_index.h.
Member Typedef Documentation
BaseClass
template<typename Distance > typedef NNIndex<Distance> flann::HierarchicalClusteringIndex< Distance >::BaseClass
Definition at line 92 of file hierarchical_clustering_index.h.
DistanceType
template<typename Distance > typedef Distance::ResultType flann::HierarchicalClusteringIndex< Distance >::DistanceType
Definition at line 90 of file hierarchical_clustering_index.h.
ElementType
template<typename Distance > typedef Distance::ElementType flann::HierarchicalClusteringIndex< Distance >::ElementType
Definition at line 89 of file hierarchical_clustering_index.h.
Constructor & Destructor Documentation
HierarchicalClusteringIndex() [1/3]
template<typename Distance > flann::HierarchicalClusteringIndex< Distance >::HierarchicalClusteringIndex (const IndexParams & index_params = HierarchicalClusteringIndexParams(), Distance d = Distance()) inline
Constructor.
Parameters
index_params
d
Definition at line 100 of file hierarchical_clustering_index.h.
References FLANN_CENTERS_RANDOM, flann::get_param(), flann::NNIndex< Distance >::index_params_, and flann::HierarchicalClusteringIndex< Distance >::initCenterChooser().
Referenced by flann::HierarchicalClusteringIndex< Distance >::clone().
HierarchicalClusteringIndex() [2/3]
template<typename Distance > flann::HierarchicalClusteringIndex< Distance >::HierarchicalClusteringIndex (const Matrix< ElementType > & inputData, const IndexParams & index_params = HierarchicalClusteringIndexParams(), Distance d = Distance()) inline
Index constructor
Params: inputData = dataset with the input features params = parameters passed to the hierarchical k-means algorithm
Definition at line 121 of file hierarchical_clustering_index.h.
References FLANN_CENTERS_RANDOM, flann::get_param(), flann::NNIndex< Distance >::index_params_, flann::HierarchicalClusteringIndex< Distance >::initCenterChooser(), flann::NNIndex< Distance >::setDataset(), and flann::NNIndex< Distance >::veclen_.
HierarchicalClusteringIndex() [3/3]
template<typename Distance > flann::HierarchicalClusteringIndex< Distance >::HierarchicalClusteringIndex (const HierarchicalClusteringIndex< Distance > & other) inline
Definition at line 140 of file hierarchical_clustering_index.h.
References flann::HierarchicalClusteringIndex< Distance >::initCenterChooser().
~HierarchicalClusteringIndex()
template<typename Distance > virtual flann::HierarchicalClusteringIndex< Distance >::~HierarchicalClusteringIndex () inline virtual
Index destructor.
Release the memory used by the index.
Definition at line 187 of file hierarchical_clustering_index.h.
Member Function Documentation
addPoints()
template<typename Distance > void flann::HierarchicalClusteringIndex< Distance >::addPoints (const Matrix< ElementType > & points, float rebuild_threshold = 2) inline virtual
Incrementally add points to the index.
Parameters
points Matrix with points to be added
rebuild_threshold
Reimplemented from flann::NNIndex< Distance >.
Definition at line 209 of file hierarchical_clustering_index.h.
References flann::HierarchicalClusteringIndex< Distance >::buildIndex(), flann::NNIndex< Distance >::extendDataset(), points, flann::NNIndex< Distance >::size_, flann::NNIndex< Distance >::size_at_build_, and flann::NNIndex< Distance >::veclen_.
buildIndex() [1/2]
template<typename Distance > virtual void flann::NNIndex< Distance >::buildIndex inline virtual
Builds the index
Reimplemented from flann::NNIndex< Distance >.
Definition at line 125 of file nn_index.h.
Referenced by flann::HierarchicalClusteringIndex< Distance >::addPoints().
buildIndex() [2/2]
template<typename Distance > virtual void flann::NNIndex< Distance >::buildIndex inline virtual
Builds the index using the specified dataset
Parameters
dataset the dataset to use
Reimplemented from flann::NNIndex< Distance >.
Definition at line 141 of file nn_index.h.
buildIndexImpl()
template<typename Distance > void flann::HierarchicalClusteringIndex< Distance >::buildIndexImpl () inline protected virtual
Builds the index
Implements flann::NNIndex< Distance >.
Definition at line 305 of file hierarchical_clustering_index.h.
References flann::NNIndex< Distance >::size_, and flann::NNIndex< Distance >::veclen_.
clone()
template<typename Distance > BaseClass* flann::HierarchicalClusteringIndex< Distance >::clone () const inline virtual
Implements flann::NNIndex< Distance >.
Definition at line 193 of file hierarchical_clustering_index.h.
References flann::HierarchicalClusteringIndex< Distance >::HierarchicalClusteringIndex().
findNeighbors()
template<typename Distance > void flann::HierarchicalClusteringIndex< Distance >::findNeighbors (ResultSet< DistanceType > & result, const ElementType * vec, const SearchParams & searchParams) const inline virtual
Find set of nearest neighbors to vec. Their indices are stored inside the result object.
Params: result = the result object in which the indices of the nearest-neighbors are stored vec = the vector for which to search the nearest neighbors searchParams = parameters that influence the search algorithm (checks)
Implements flann::NNIndex< Distance >.
Definition at line 290 of file hierarchical_clustering_index.h.
References flann::NNIndex< Distance >::removed_, and result.
getType()
template<typename Distance > flann_algorithm_t flann::HierarchicalClusteringIndex< Distance >::getType () const inline virtual
Implements flann::IndexBase.
Definition at line 229 of file hierarchical_clustering_index.h.
References FLANN_INDEX_HIERARCHICAL.
Referenced by flann::HierarchicalClusteringIndex< Distance >::serialize().
initCenterChooser()
template<typename Distance > void flann::HierarchicalClusteringIndex< Distance >::initCenterChooser () inline
Definition at line 162 of file hierarchical_clustering_index.h.
References flann::NNIndex< Distance >::distance_, FLANN_CENTERS_GONZALES, FLANN_CENTERS_GROUPWISE, FLANN_CENTERS_KMEANSPP, FLANN_CENTERS_RANDOM, and flann::NNIndex< Distance >::points_.
Referenced by flann::HierarchicalClusteringIndex< Distance >::HierarchicalClusteringIndex().
loadIndex()
template<typename Distance > void flann::HierarchicalClusteringIndex< Distance >::loadIndex (FILE * stream) inline virtual
Implements flann::IndexBase.
Definition at line 273 of file hierarchical_clustering_index.h.
operator=()
template<typename Distance > HierarchicalClusteringIndex& flann::HierarchicalClusteringIndex< Distance >::operator= (HierarchicalClusteringIndex< Distance > other) inline
Definition at line 155 of file hierarchical_clustering_index.h.
saveIndex()
template<typename Distance > void flann::HierarchicalClusteringIndex< Distance >::saveIndex (FILE * stream) inline virtual
Implements flann::IndexBase.
Definition at line 266 of file hierarchical_clustering_index.h.
serialize()
template<typename Distance > template<typename Archive > void flann::HierarchicalClusteringIndex< Distance >::serialize (Archive & ar) inline
Definition at line 236 of file hierarchical_clustering_index.h.
References flann::HierarchicalClusteringIndex< Distance >::getType(), and flann::NNIndex< Distance >::index_params_.
usedMemory()
template<typename Distance > int flann::HierarchicalClusteringIndex< Distance >::usedMemory () const inline virtual
Computes the inde memory usage Returns: memory used by the index
Implements flann::IndexBase.
Definition at line 202 of file hierarchical_clustering_index.h.
References flann::PooledAllocator::usedMemory, and flann::PooledAllocator::wastedMemory.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/algorithms/hierarchical_clustering_index.h