ACloudViewer: PclMeasurementTools Class Reference
PclMeasurementTools Class Reference
#include <PclMeasurementTools.h>
Public Member Functions
PclMeasurementTools (MeasurementType type=MeasurementType::DISTANCE_WIDGET)
PclMeasurementTools (ecvGenericVisualizer3D *viewer, MeasurementType type=MeasurementType::DISTANCE_WIDGET)
virtual ~PclMeasurementTools () override
void setVisualizer (ecvGenericVisualizer3D *viewer=nullptr)
virtual bool setInputData (ccHObject *entity) override
Sets the input entity.
virtual bool start () override
Starts the measurement tool.
virtual void reset () override
Resets the measurement tool.
virtual void clear () override
Clears the measurement tool.
virtual QWidget * getMeasurementWidget () override
Returns the measurement widget.
virtual ccHObject * getOutput () const override
Returns the output (if any)
virtual double getMeasurementValue () const override
Get measurement value (distance or angle)
virtual void getPoint1 (double pos[3]) const override
Get point 1 coordinates.
virtual void getPoint2 (double pos[3]) const override
Get point 2 coordinates.
virtual void getCenter (double pos[3]) const override
Get center point coordinates (for angle/protractor)
virtual void setPoint1 (double pos[3]) override
Set point 1 coordinates.
virtual void setPoint2 (double pos[3]) override
Set point 2 coordinates.
virtual void setCenter (double pos[3]) override
Set center point coordinates (for angle/protractor)
virtual void setColor (double r, double g, double b) override
Set measurement color (RGB values in range [0.0, 1.0])
virtual bool getColor (double &r, double &g, double &b) const
virtual void lockInteraction () override
Lock tool interaction (disable VTK widget and UI controls)
virtual void unlockInteraction () override
Unlock tool interaction (enable VTK widget and UI controls)
virtual void setInstanceLabel (const QString &label) override
Set instance label suffix (e.g., "#1", "#2") for display in 3D view.
virtual void setFontFamily (const QString &family) override
virtual void setFontSize (int size) override
Set font size for measurement labels.
virtual void setBold (bool bold) override
Set font bold state for measurement labels.
virtual void setItalic (bool italic) override
Set font italic state for measurement labels.
virtual void setShadow (bool shadow) override
Set font shadow state for measurement labels.
virtual void setFontOpacity (double opacity) override
Set font opacity for measurement labels (0.0 to 1.0)
virtual void setFontColor (double r, double g, double b) override
Set font color for measurement labels (RGB values 0.0-1.0)
QString getFontFamily () const
Get font properties (for UI synchronization)
int getFontSize () const
void getFontColor (double &r, double &g, double &b) const
bool getFontBold () const
bool getFontItalic () const
bool getFontShadow () const
double getFontOpacity () const
QString getHorizontalJustification () const
QString getVerticalJustification () const
virtual void setHorizontalJustification (const QString &justification) override
virtual void setVerticalJustification (const QString &justification) override
virtual void setupShortcuts (QWidget *win) override
Setup keyboard shortcuts bound to the render window widget.
virtual void disableShortcuts () override
Disable keyboard shortcuts (called before tool destruction)
virtual void clearPickingCache () override
Clear picking cache (called when scene/camera changes)
Public Member Functions inherited from ecvGenericMeasurementTools
ecvGenericMeasurementTools (MeasurementType type=MeasurementType::DISTANCE_WIDGET)
Default constructor.
virtual ~ecvGenericMeasurementTools ()
Destructor.
virtual void update ()
Updates the display.
MeasurementType getMeasurementType ()
Protected Member Functions
virtual void initialize () override
Additional Inherited Members
Public Types inherited from ecvGenericMeasurementTools
enum MeasurementType { DISTANCE_WIDGET , CONTOUR_WIDGET , PROTRACTOR_WIDGET }
Signals inherited from ecvGenericMeasurementTools
void measurementChanged ()
Signal sent when the measurement changes.
void pointPickingRequested (int pointIndex)
void pointPickingCancelled ()
Signal sent when point picking is cancelled.
Protected Attributes inherited from ecvGenericMeasurementTools
MeasurementType m_measurementType
ccHObject * m_associatedEntity
Detailed Description
Definition at line 25 of file PclMeasurementTools.h.
Constructor & Destructor Documentation
PclMeasurementTools() [1/2]
PclMeasurementTools::PclMeasurementTools (MeasurementType type = MeasurementType::DISTANCE_WIDGET) explicit
Definition at line 19 of file PclMeasurementTools.cpp.
References initialize().
PclMeasurementTools() [2/2]
PclMeasurementTools::PclMeasurementTools (ecvGenericVisualizer3D * viewer, MeasurementType type = MeasurementType::DISTANCE_WIDGET) explicit
Definition at line 24 of file PclMeasurementTools.cpp.
References initialize(), and setVisualizer().
~PclMeasurementTools()
PclMeasurementTools::~PclMeasurementTools () override virtual
Definition at line 31 of file PclMeasurementTools.cpp.
Member Function Documentation
clear()
void PclMeasurementTools::clear () override virtual
Clears the measurement tool.
Implements ecvGenericMeasurementTools.
Definition at line 132 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::clearAllActor().
clearPickingCache()
void PclMeasurementTools::clearPickingCache () override virtual
Clear picking cache (called when scene/camera changes)
Reimplemented from ecvGenericMeasurementTools.
Definition at line 338 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::clearPickingCache().
disableShortcuts()
void PclMeasurementTools::disableShortcuts () override virtual
Disable keyboard shortcuts (called before tool destruction)
Reimplemented from ecvGenericMeasurementTools.
Definition at line 332 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::disableShortcuts().
getCenter()
void PclMeasurementTools::getCenter (double pos[3]) const override virtual
Get center point coordinates (for angle/protractor)
Implements ecvGenericMeasurementTools.
Definition at line 170 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getCenter().
getColor()
bool PclMeasurementTools::getColor (double & r, double & g, double & b) const virtual
Get measurement color (RGB values in range [0.0, 1.0]) Returns false if not implemented, true if color is retrieved
Definition at line 202 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getColor().
Referenced by ecvMeasurementTool::createMeasurementTool(), ecvMeasurementTool::onColorButtonClicked(), ecvMeasurementTool::setMeasurementTool(), and ecvMeasurementTool::updateUIFromTool().
getFontBold()
bool PclMeasurementTools::getFontBold () const
Definition at line 285 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getFontBold().
Referenced by ecvMeasurementTool::createMeasurementTool(), ecvMeasurementTool::setMeasurementTool(), and ecvMeasurementTool::updateUIFromTool().
getFontColor()
void PclMeasurementTools::getFontColor (double & r, double & g, double & b) const
Definition at line 277 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getFontColor().
Referenced by ecvMeasurementTool::createMeasurementTool(), ecvMeasurementTool::setMeasurementTool(), and ecvMeasurementTool::updateUIFromTool().
getFontFamily()
QString PclMeasurementTools::getFontFamily () const
Get font properties (for UI synchronization)
Definition at line 269 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getFontFamily().
Referenced by ecvMeasurementTool::createMeasurementTool(), ecvMeasurementTool::setMeasurementTool(), and ecvMeasurementTool::updateUIFromTool().
getFontItalic()
bool PclMeasurementTools::getFontItalic () const
Definition at line 289 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getFontItalic().
Referenced by ecvMeasurementTool::createMeasurementTool(), ecvMeasurementTool::setMeasurementTool(), and ecvMeasurementTool::updateUIFromTool().
getFontOpacity()
double PclMeasurementTools::getFontOpacity () const
Definition at line 297 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getFontOpacity().
Referenced by ecvMeasurementTool::createMeasurementTool(), ecvMeasurementTool::setMeasurementTool(), and ecvMeasurementTool::updateUIFromTool().
getFontShadow()
bool PclMeasurementTools::getFontShadow () const
Definition at line 293 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getFontShadow().
Referenced by ecvMeasurementTool::createMeasurementTool(), ecvMeasurementTool::setMeasurementTool(), and ecvMeasurementTool::updateUIFromTool().
getFontSize()
int PclMeasurementTools::getFontSize () const
Definition at line 273 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getFontSize().
Referenced by ecvMeasurementTool::createMeasurementTool(), ecvMeasurementTool::setMeasurementTool(), and ecvMeasurementTool::updateUIFromTool().
getHorizontalJustification()
QString PclMeasurementTools::getHorizontalJustification () const
Definition at line 301 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getHorizontalJustification().
Referenced by ecvMeasurementTool::createMeasurementTool(), ecvMeasurementTool::setMeasurementTool(), and ecvMeasurementTool::updateUIFromTool().
getMeasurementValue()
double PclMeasurementTools::getMeasurementValue () const override virtual
Get measurement value (distance or angle)
Implements ecvGenericMeasurementTools.
Definition at line 147 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getMeasurementValue().
getMeasurementWidget()
QWidget * PclMeasurementTools::getMeasurementWidget () override virtual
Returns the measurement widget.
Implements ecvGenericMeasurementTools.
Definition at line 138 of file PclMeasurementTools.cpp.
getOutput()
ccHObject * PclMeasurementTools::getOutput () const override virtual
Returns the output (if any)
Implements ecvGenericMeasurementTools.
Definition at line 140 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getOutput().
getPoint1()
void PclMeasurementTools::getPoint1 (double pos[3]) const override virtual
Get point 1 coordinates.
Implements ecvGenericMeasurementTools.
Definition at line 154 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getPoint1().
getPoint2()
void PclMeasurementTools::getPoint2 (double pos[3]) const override virtual
Get point 2 coordinates.
Implements ecvGenericMeasurementTools.
Definition at line 162 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getPoint2().
getVerticalJustification()
QString PclMeasurementTools::getVerticalJustification () const
Definition at line 305 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::getVerticalJustification().
Referenced by ecvMeasurementTool::createMeasurementTool(), ecvMeasurementTool::setMeasurementTool(), and ecvMeasurementTool::updateUIFromTool().
initialize()
void PclMeasurementTools::initialize () override protected virtual
Implements ecvGenericMeasurementTools.
Definition at line 38 of file PclMeasurementTools.cpp.
References CVLog::Error(), ecvGenericMeasurementTools::m_measurementType, ecvGenericMeasurementTools::measurementChanged(), cvGenericMeasurementTool::measurementValueChanged(), ecvGenericMeasurementTools::pointPickingCancelled(), cvGenericMeasurementTool::pointPickingCancelled(), ecvGenericMeasurementTools::pointPickingRequested(), cvGenericMeasurementTool::pointPickingRequested(), cvGenericMeasurementTool::setInteractor(), and cvGenericMeasurementTool::setUpViewer().
Referenced by PclMeasurementTools().
lockInteraction()
void PclMeasurementTools::lockInteraction () override virtual
Lock tool interaction (disable VTK widget and UI controls)
Implements ecvGenericMeasurementTools.
Definition at line 209 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::lockInteraction().
reset()
void PclMeasurementTools::reset () override virtual
Resets the measurement tool.
Implements ecvGenericMeasurementTools.
Definition at line 126 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::reset().
setBold()
void PclMeasurementTools::setBold (bool bold) override virtual
Set font bold state for measurement labels.
Implements ecvGenericMeasurementTools.
Definition at line 239 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setBold().
setCenter()
void PclMeasurementTools::setCenter (double pos[3]) override virtual
Set center point coordinates (for angle/protractor)
Implements ecvGenericMeasurementTools.
Definition at line 190 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setCenter().
setColor()
void PclMeasurementTools::setColor (double r, double g, double b) override virtual
Set measurement color (RGB values in range [0.0, 1.0])
Implements ecvGenericMeasurementTools.
Definition at line 196 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setColor().
setFontColor()
void PclMeasurementTools::setFontColor (double r, double g, double b) override virtual
Set font color for measurement labels (RGB values 0.0-1.0)
Implements ecvGenericMeasurementTools.
Definition at line 263 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setFontColor().
setFontFamily()
void PclMeasurementTools::setFontFamily (const QString & family) override virtual
Set font family for measurement labels (e.g., "Arial", "Times New Roman")
Implements ecvGenericMeasurementTools.
Definition at line 227 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setFontFamily().
setFontOpacity()
void PclMeasurementTools::setFontOpacity (double opacity) override virtual
Set font opacity for measurement labels (0.0 to 1.0)
Implements ecvGenericMeasurementTools.
Definition at line 257 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setFontOpacity().
setFontSize()
void PclMeasurementTools::setFontSize (int size) override virtual
Set font size for measurement labels.
Implements ecvGenericMeasurementTools.
Definition at line 233 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setFontSize(), and size.
setHorizontalJustification()
void PclMeasurementTools::setHorizontalJustification (const QString & justification) override virtual
Set horizontal justification for measurement labels ("Left", "Center", "Right")
Implements ecvGenericMeasurementTools.
Definition at line 309 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setHorizontalJustification().
setInputData()
bool PclMeasurementTools::setInputData (ccHObject * entity) override virtual
Sets the input entity.
Implements ecvGenericMeasurementTools.
Definition at line 92 of file PclMeasurementTools.cpp.
References ecvDisplayTools::GetVisualizer3D(), ecvGenericMeasurementTools::m_associatedEntity, cvGenericMeasurementTool::setInput(), and setVisualizer().
setInstanceLabel()
void PclMeasurementTools::setInstanceLabel (const QString & label) override virtual
Set instance label suffix (e.g., "#1", "#2") for display in 3D view.
Implements ecvGenericMeasurementTools.
Definition at line 221 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setInstanceLabel().
setItalic()
void PclMeasurementTools::setItalic (bool italic) override virtual
Set font italic state for measurement labels.
Implements ecvGenericMeasurementTools.
Definition at line 245 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setItalic().
setPoint1()
void PclMeasurementTools::setPoint1 (double pos[3]) override virtual
Set point 1 coordinates.
Implements ecvGenericMeasurementTools.
Definition at line 178 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setPoint1().
setPoint2()
void PclMeasurementTools::setPoint2 (double pos[3]) override virtual
Set point 2 coordinates.
Implements ecvGenericMeasurementTools.
Definition at line 184 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setPoint2().
setShadow()
void PclMeasurementTools::setShadow (bool shadow) override virtual
Set font shadow state for measurement labels.
Implements ecvGenericMeasurementTools.
Definition at line 251 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setShadow().
setupShortcuts()
void PclMeasurementTools::setupShortcuts (QWidget * win) override virtual
Setup keyboard shortcuts bound to the render window widget.
Reimplemented from ecvGenericMeasurementTools.
Definition at line 323 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setupShortcuts(), and CVLog::Warning().
setVerticalJustification()
void PclMeasurementTools::setVerticalJustification (const QString & justification) override virtual
Set vertical justification for measurement labels ("Top", "Center", "Bottom")
Implements ecvGenericMeasurementTools.
Definition at line 316 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::setVerticalJustification().
setVisualizer()
void PclMeasurementTools::setVisualizer (ecvGenericVisualizer3D * viewer = nullptr)
Definition at line 73 of file PclMeasurementTools.cpp.
References PclUtils::PCLVis::getRenderWindowInteractor(), cvGenericMeasurementTool::setInteractor(), cvGenericMeasurementTool::setUpViewer(), and CVLog::Warning().
Referenced by PclMeasurementTools(), setInputData(), and start().
start()
bool PclMeasurementTools::start () override virtual
Starts the measurement tool.
Implements ecvGenericMeasurementTools.
Definition at line 107 of file PclMeasurementTools.cpp.
References PclUtils::PCLVis::getRenderWindowInteractor(), ecvDisplayTools::GetVisualizer3D(), cvGenericMeasurementTool::setInteractor(), setVisualizer(), and cvGenericMeasurementTool::start().
unlockInteraction()
void PclMeasurementTools::unlockInteraction () override virtual
Unlock tool interaction (enable VTK widget and UI controls)
Implements ecvGenericMeasurementTools.
Definition at line 215 of file PclMeasurementTools.cpp.
References cvGenericMeasurementTool::unlockInteraction().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/MeasurementTools/PclMeasurementTools.h
/root/ACloudViewer/libs/PCLEngine/Tools/MeasurementTools/PclMeasurementTools.cpp