ACloudViewer: qCSF Class Reference
qCSF Class Reference
A point-clouds filtering algorithm utilize cloth simulation process.
#include <qCSF.h>
Public Member Functions
qCSF (QObject *parent=nullptr)
Default constructor.
virtual ~qCSF ()=default
virtual void onNewSelection (const ccHObject::Container &selectedEntities) override
virtual QList< QAction * > getActions () override
Get a list of actions for this plugin.
virtual void registerCommands (ccCommandLineInterface *cmd) override
Optional: registers commands (for the command line mode)
Public Member Functions inherited from ccStdPluginInterface
ccStdPluginInterface (const QString &resourcePath=QString())
Default constructor.
virtual ~ccStdPluginInterface () override=default
Destructor.
virtual CC_PLUGIN_TYPE getType () const override
Returns plugin type (standard or OpenGL filter)
virtual void setMainAppInterface (ecvMainAppInterface *app)
Sets application entry point.
virtual ecvMainAppInterface * getMainAppInterface ()
A callback pointer to the main app interface for use by plugins.
virtual void dispToConsole (QString message, ecvMainAppInterface::ConsoleMessageLevel level=ecvMainAppInterface::STD_CONSOLE_MESSAGE)
Shortcut to ecvMainAppInterface::dispToConsole.
Public Member Functions inherited from ccDefaultPluginInterface
virtual ~ccDefaultPluginInterface ()
virtual bool isCore () const override
Is this plugin a core plugin?
virtual QString getName () const override
Returns (short) name (for menu entry, etc.)
virtual QString getDescription () const override
Returns long name/description (for tooltip, etc.)
virtual QIcon getIcon () const override
Returns icon.
virtual ReferenceList getReferences () const override
virtual ContactList getAuthors () const override
virtual ContactList getMaintainers () const override
Public Member Functions inherited from ccPluginInterface
virtual ~ccPluginInterface ()=default
Virtual destructor.
virtual bool start ()
Starts the plugin.
virtual void stop ()
Stops the plugin.
virtual ccExternalFactory * getCustomObjectsFactory () const
Returns the plugin's custom object factory (if any)
Protected Slots
void doAction ()
Slot called when associated ation is triggered.
Protected Attributes
QAction * m_action
Associated action.
Protected Attributes inherited from ccStdPluginInterface
ecvMainAppInterface * m_app
Main application interface.
Additional Inherited Members
Public Types inherited from ccPluginInterface
typedef QList< Contact > ContactList
using ReferenceList = QList< Reference >
Protected Member Functions inherited from ccDefaultPluginInterface
ccDefaultPluginInterface (const QString &resourcePath=QString())
Detailed Description
A point-clouds filtering algorithm utilize cloth simulation process.
Definition at line 13 of file qCSF.h.
Constructor & Destructor Documentation
qCSF()
qCSF::qCSF (QObject * parent = nullptr) explicit
Default constructor.
Definition at line 41 of file qCSF.cpp.
~qCSF()
virtual qCSF::~qCSF () virtual default
Member Function Documentation
doAction
void qCSF::doAction () protected slot
Slot called when associated ation is triggered.
Definition at line 64 of file qCSF.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), ecvMainAppInterface::addToDB(), CSF::Parameters::bSloopSmooth, CSF::Parameters::class_threshold, class_threshold, CSF::Parameters::cloth_resolution, cloth_resolution, ccMesh::computePerVertexNormals(), count, ecvMainAppInterface::dispToConsole(), CSF::do_filtering(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, ecvMainAppInterface::getMainWindow(), ccObject::getName(), cloudViewer::PointCloudTpl< T >::getPoint(), ecvMainAppInterface::getSelectedEntities(), ecvMainAppInterface::haveOneSelection(), ccObject::isA(), CSF::Parameters::iterations, CSF::Parameters::k_nearest_points, ccStdPluginInterface::m_app, MaxIteration, CSF::params, ccPointCloud::partialClone(), CV_TYPES::POINT_CLOUD, cloudViewer::ReferenceCloud::reserve(), CSF::Parameters::rigidness, ccObject::setEnabled(), ccObject::setName(), ccDrawableObject::setVisible(), ccGenericMesh::showNormals(), cloudViewer::PointCloudTpl< T >::size(), ecvMainAppInterface::STD_CONSOLE_MESSAGE, CSF::Parameters::time_step, ecvMainAppInterface::WRN_CONSOLE_MESSAGE, Tuple3Tpl< Type >::x, wl::Point::x, Tuple3Tpl< Type >::y, wl::Point::y, Tuple3Tpl< Type >::z, and wl::Point::z.
Referenced by getActions().
getActions()
QList< QAction * > qCSF::getActions () override virtual
Get a list of actions for this plugin.
Implements ccStdPluginInterface.
Definition at line 52 of file qCSF.cpp.
References doAction(), ccDefaultPluginInterface::getDescription(), ccDefaultPluginInterface::getIcon(), ccDefaultPluginInterface::getName(), and m_action.
onNewSelection()
void qCSF::onNewSelection (const ccHObject::Container & selectedEntities) override virtual
This method is called by the main application whenever the entity selection changes Does nothing by default. Should be re-implemented by the plugin if necessary.
Parameters
selectedEntities currently selected entities
Reimplemented from ccStdPluginInterface.
Definition at line 46 of file qCSF.cpp.
References m_action, and CV_TYPES::POINT_CLOUD.
registerCommands()
void qCSF::registerCommands (ccCommandLineInterface * cmd) override virtual
Optional: registers commands (for the command line mode)
Does nothing by default.
Warning
: don't use keywords that are already used by the main application or other plugins! (use a unique prefix for all commands if possible)
Reimplemented from ccPluginInterface.
Definition at line 256 of file qCSF.cpp.
References ccCommandLineInterface::registerCommand().
Member Data Documentation
m_action
QAction* qCSF::m_action protected
Associated action.
Definition at line 37 of file qCSF.h.
Referenced by getActions(), and onNewSelection().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCSF/include/qCSF.h
/root/ACloudViewer/plugins/core/Standard/qCSF/src/qCSF.cpp