ACloudViewer: ccCompass Class Reference
ccCompass Class Reference
#include <ccCompass.h>
Static Public Attributes
static bool drawName = false
static bool drawStippled = true
static bool drawNormals = true
static bool fitPlanes = true
static int costMode = ccTrace::DARK
static bool mapMode = false
static int mapTo = ccGeoObject::LOWER_BOUNDARY
Protected Slots
void doAction ()
bool startMeasuring ()
bool stopMeasuring (bool finalStop=false)
virtual void onItemPicked (const ccPickingListener::PickedItem &pi) override
void pointPicked (ccHObject *entity, unsigned itemIdx, int x, int y, const CCVector3 &P)
void onClose ()
void onAccept ()
void onSave ()
void onUndo ()
void enableMapMode ()
void enableMeasureMode ()
void setPick ()
void setLineation ()
void setPlane ()
void setTrace ()
void addPinchNode ()
void setThickness ()
void setThickness2 ()
void setYoungerThan ()
void setFollows ()
void setEquivalent ()
void setNote ()
void recalculateSelectedTraces ()
void mergeGeoObjects ()
void fitPlaneToGeoObject ()
void recalculateFitPlanes ()
void estimateStructureNormals ()
void estimateP21 ()
void estimateStrain ()
void convertToPointCloud ()
void distributeSelection ()
void importFoliations ()
void importLineations ()
void exportToSVG ()
void writeToInterior ()
void writeToUpper ()
void writeToLower ()
void addGeoObject (bool singleSurface=false)
void addGeoObjectSS ()
void hideAllPointClouds (ccHObject *o)
void toggleStipple (bool checked)
void recurseStipple (ccHObject *object, bool checked)
void toggleLabels (bool checked)
void recurseLabels (ccHObject *object, bool checked)
void toggleNormals (bool checked)
void recurseNormals (ccHObject *object, bool checked)
void showHelp ()
Protected Member Functions
virtual bool eventFilter (QObject *obj, QEvent *event) override
ccHObject * getInsertPoint ()
void cleanupBeforeToolChange (bool autoRestartPicking=true)
bool startPicking ()
void stopPicking ()
void tryLoading ()
void tryLoading (ccHObject *obj, std::vector< int > *originals, std::vector< ccHObject * > *replacements)
int writePlanes (ccHObject *object, QTextStream *out, const QString &parentName=QString())
int writeTraces (ccHObject *object, QTextStream *out, const QString &parentName=QString())
int writeLineations (ccHObject *object, QTextStream *out, const QString &parentName=QString(), bool thickness=false)
int writeTracesSVG (ccHObject *object, QTextStream *out, int height, float zoom)
int writeToXML (const QString &filename)
int writeObjectXML (ccHObject *object, QXmlStreamWriter *out)
bool madeByMe (ccHObject *object)
Protected Member Functions inherited from ccDefaultPluginInterface
ccDefaultPluginInterface (const QString &resourcePath=QString())
Protected Attributes
QAction * m_action = nullptr
QMainWindow * m_main_window = nullptr
bool m_picking = false
bool m_active = false
ccCompassDlg * m_dlg = nullptr
ccMapDlg * m_mapDlg = nullptr
ccTool * m_activeTool = nullptr
ccFitPlaneTool * m_fitPlaneTool
ccTraceTool * m_traceTool
ccLineationTool * m_lineationTool
ccThicknessTool * m_thicknessTool
ccTopologyTool * m_topologyTool
ccNoteTool * m_noteTool
ccPinchNodeTool * m_pinchNodeTool
ccGeoObject * m_geoObject
int m_geoObject_id = -1
std::vector< int > m_hiddenObjects
QString m_lastGeoObjectName = "GeoObject"
Protected Attributes inherited from ccStdPluginInterface
ecvMainAppInterface * m_app
Main application interface.
Additional Inherited Members
Public Types inherited from ccPluginInterface
typedef QList< Contact > ContactList
using ReferenceList = QList< Reference >
Public Member Functions inherited from ccStdPluginInterface
ccStdPluginInterface (const QString &resourcePath=QString())
Default constructor.
virtual ~ccStdPluginInterface () override=default
Destructor.
virtual CC_PLUGIN_TYPE getType () const override
Returns plugin type (standard or OpenGL filter)
virtual void setMainAppInterface (ecvMainAppInterface *app)
Sets application entry point.
virtual ecvMainAppInterface * getMainAppInterface ()
A callback pointer to the main app interface for use by plugins.
virtual void dispToConsole (QString message, ecvMainAppInterface::ConsoleMessageLevel level=ecvMainAppInterface::STD_CONSOLE_MESSAGE)
Shortcut to ecvMainAppInterface::dispToConsole.
Public Member Functions inherited from ccDefaultPluginInterface
virtual ~ccDefaultPluginInterface ()
virtual bool isCore () const override
Is this plugin a core plugin?
virtual QString getName () const override
Returns (short) name (for menu entry, etc.)
virtual QString getDescription () const override
Returns long name/description (for tooltip, etc.)
virtual QIcon getIcon () const override
Returns icon.
virtual ReferenceList getReferences () const override
virtual ContactList getAuthors () const override
virtual ContactList getMaintainers () const override
Public Member Functions inherited from ccPluginInterface
virtual ~ccPluginInterface ()=default
Virtual destructor.
virtual bool start ()
Starts the plugin.
virtual ccExternalFactory * getCustomObjectsFactory () const
Returns the plugin's custom object factory (if any)
virtual void registerCommands (ccCommandLineInterface *cmd)
Optional: registers commands (for the command line mode)
Public Member Functions inherited from ccPickingListener
virtual ~ccPickingListener ()=default
virtual void onItemPicked (const PickedItem &pi)=0
Method called whenever an item is picked.
Detailed Description
Definition at line 34 of file ccCompass.h.
Member Function Documentation
addGeoObject
void ccCompass::addGeoObject (bool singleSurface = false) protected slot
Definition at line 3608 of file ccCompass.cpp.
References ccHObject::addChild(), ecvMainAppInterface::addToDB(), ecvMainAppInterface::dbRootObject(), ccHObject::getChild(), ecvMainAppInterface::getMainWindow(), ccObject::getName(), ccStdPluginInterface::m_app, m_lastGeoObjectName, name, and ecvMainAppInterface::setSelectedInDB().
Referenced by addGeoObjectSS(), and doAction().
addGeoObjectSS
void ccCompass::addGeoObjectSS () protected slot
Definition at line 3675 of file ccCompass.cpp.
References addGeoObject().
Referenced by doAction().
addPinchNode
void ccCompass::addPinchNode () protected slot
Definition at line 880 of file ccCompass.cpp.
References ccTool::canUndo(), cleanupBeforeToolChange(), m_activeTool, m_dlg, m_pinchNodeTool, ecvDisplayTools::RedrawDisplay(), and ccTool::toolActivated().
Referenced by doAction().
cleanupBeforeToolChange()
void ccCompass::cleanupBeforeToolChange (bool autoRestartPicking = true) protected
Definition at line 772 of file ccCompass.cpp.
References ecvMainAppInterface::dbRootObject(), ccHObject::find(), m_activeTool, ccStdPluginInterface::m_app, m_dlg, m_hiddenObjects, ecvDisplayTools::RedrawDisplay(), ccDrawableObject::setVisible(), startPicking(), and ccTool::toolDisactivated().
Referenced by addPinchNode(), setLineation(), setNote(), setPick(), setPlane(), setThickness(), setTrace(), setYoungerThan(), and stopMeasuring().
convertToPointCloud
void ccCompass::convertToPointCloud () protected slot
Definition at line 3274 of file ccCompass.cpp.
References ccHObject::addChild(), cloudViewer::ScalarField::addElement(), ecvMainAppInterface::addToDB(), cloudViewer::ScalarField::computeMinAndMax(), ecvMainAppInterface::dbRootObject(), ecvMainAppInterface::dispToConsole(), ccHObject::filterChildren(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), cloudViewer::ReferenceCloud::getPoint(), ecvMainAppInterface::getSelectedEntities(), CV_TYPES::HIERARCHY_OBJECT, ccGeoObject::INTERIOR, ccObject::isA(), ccGeoObject::isGeoObject(), ccGeoObject::isSingleSurfaceGeoObject(), ccGeoObject::LOWER_BOUNDARY, ccStdPluginInterface::m_app, points, CV_TYPES::POLY_LINE, cloudViewer::ReferenceCloud::size(), ccGeoObject::UPPER_BOUNDARY, and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by doAction().
distributeSelection
void ccCompass::distributeSelection () protected slot
Definition at line 3399 of file ccCompass.cpp.
References ccHObject::addChild(), ecvMainAppInterface::addToDB(), ecvMainAppInterface::dbRootObject(), ecvMainAppInterface::dispToConsole(), ccHObject::filterChildren(), ccObject::getName(), ccGeoObject::getRegion(), ecvMainAppInterface::getSelectedEntities(), CV_TYPES::HIERARCHY_OBJECT, ccGeoObject::INTERIOR, ccGeoObject::isGeoObject(), ccGeoObject::LOWER_BOUNDARY, ccStdPluginInterface::m_app, ecvMainAppInterface::refreshAll(), ecvMainAppInterface::removeFromDB(), ecvMainAppInterface::updateUI(), ccGeoObject::UPPER_BOUNDARY, and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by doAction().
doAction
void ccCompass::doAction () protected slot
Definition at line 176 of file ccCompass.cpp.
References addGeoObject(), addGeoObjectSS(), addPinchNode(), convertToPointCloud(), ecvMainAppInterface::dispToConsole(), distributeSelection(), enableMapMode(), enableMeasureMode(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, estimateP21(), estimateStrain(), estimateStructureNormals(), exportToSVG(), fitPlaneToGeoObject(), ecvMainAppInterface::getActiveWindow(), ecvDisplayTools::GetCurrentScreen(), ecvMainAppInterface::getMainWindow(), importFoliations(), importLineations(), ccTool::initializeTool(), ccOverlayDialog::linkWith(), ccStdPluginInterface::m_app, ccMapDlg::m_create_geoObject, ccMapDlg::m_create_geoObjectSS, ccCompassDlg::m_distributeSelection, m_dlg, ccCompassDlg::m_equivalent, ccCompassDlg::m_estimateNormals, ccCompassDlg::m_estimateP21, ccCompassDlg::m_estimateStrain, ccCompassDlg::m_fitPlaneToGeoObject, m_fitPlaneTool, ccCompassDlg::m_follows, m_lineationTool, ccCompassDlg::m_loadFoliations, ccCompassDlg::m_loadLineations, m_mapDlg, ccCompassDlg::m_measure_thickness, ccCompassDlg::m_measure_thickness_twoPoint, ccCompassDlg::m_mergeSelected, m_noteTool, ccCompassDlg::m_noteTool, m_pinchNodeTool, ccCompassDlg::m_pinchTool, ccCompassDlg::m_recalculate, ccCompassDlg::m_recalculateFitPlanes, ccCompassDlg::m_showNames, ccCompassDlg::m_showNormals, ccCompassDlg::m_showStippled, m_thicknessTool, ccCompassDlg::m_toPointCloud, m_topologyTool, ccCompassDlg::m_toSVG, m_traceTool, ccCompassDlg::m_youngerThan, mergeGeoObjects(), onAccept(), onClose(), onSave(), onUndo(), recalculateFitPlanes(), recalculateSelectedTraces(), setEquivalent(), setFollows(), setLineation(), setNote(), setPick(), setPlane(), setThickness(), setThickness2(), setTrace(), setYoungerThan(), showHelp(), startMeasuring(), toggleLabels(), toggleNormals(), toggleStipple(), tryLoading(), writeToInterior(), writeToLower(), and writeToUpper().
enableMapMode
void ccCompass::enableMapMode () protected slot
Definition at line 3574 of file ccCompass.cpp.
References ccStdPluginInterface::m_app, m_dlg, m_mapDlg, mapMode, ecvDisplayTools::RedrawDisplay(), ecvMainAppInterface::registerOverlayDialog(), ccOverlayDialog::start(), and ecvMainAppInterface::updateOverlayDialogsPlacement().
Referenced by doAction().
enableMeasureMode
void ccCompass::enableMeasureMode () protected slot
Definition at line 3592 of file ccCompass.cpp.
References ccStdPluginInterface::m_app, m_dlg, m_mapDlg, mapMode, ecvDisplayTools::RedrawDisplay(), ccOverlayDialog::stop(), ecvMainAppInterface::unregisterOverlayDialog(), and ecvMainAppInterface::updateOverlayDialogsPlacement().
Referenced by doAction().
estimateP21
void ccCompass::estimateP21 () protected slot
Definition at line 3027 of file ccCompass.cpp.
References cloudViewer::ScalarField::addElement(), cloudViewer::PointCloudTpl< T >::addPoint(), ccPointCloud::addScalarField(), ccPointCloud::clear(), ccGenericPointCloud::computeOctree(), ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, ccHObject::filterChildren(), ccGeoObject::getGeoObjectRegion(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ecvMainAppInterface::getMainWindow(), cloudViewer::PointCloudTpl< T >::getPoint(), ecvMainAppInterface::getSelectedEntities(), ecvProgressDialog::isCancelRequested(), ccSNECloud::isSNECloud(), ccTrace::isTrace(), ccGeoObject::LOWER_BOUNDARY, ccStdPluginInterface::m_app, CV_TYPES::POINT_CLOUD, CV_TYPES::POLY_LINE, ccPointCloud::reserve(), result, searchR, cloudViewer::PointCloudTpl< T >::setCurrentScalarField(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), cloudViewer::PointCloudTpl< T >::size(), ecvProgressDialog::start(), ecvMainAppInterface::STD_CONSOLE_MESSAGE, subsample, ecvProgressDialog::update(), and ccGeoObject::UPPER_BOUNDARY.
Referenced by doAction().
estimateStrain
void ccCompass::estimateStrain () protected slot
Definition at line 2449 of file ccCompass.cpp.
References ccHObject::addChild(), cloudViewer::ScalarField::addElement(), ecvMainAppInterface::addToDB(), binSize, ecvColor::blue(), buildGraphics, cloudViewer::SquareMatrixTpl< Scalar >::clear(), Jacobi< Scalar >::ComputeEigenValuesAndVectors(), ccScalarField::computeMinAndMax(), Vector3Tpl< Type >::cross(), ecvMainAppInterface::dbRootObject(), ecvMainAppInterface::dispToConsole(), e, ecvMainAppInterface::ERR_CONSOLE_MESSAGE, exag, ccHObject::filterChildren(), ccGeoObject::getGeoObjectParent(), ccGeoObject::getGeoObjectRegion(), ecvMainAppInterface::getMainWindow(), cloudViewer::PointCloudTpl< T >::getPoint(), ccPointCloud::getPointNormal(), cloudViewer::PointCloudTpl< T >::getPointScalarValue(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), ecvMainAppInterface::getSelectedEntities(), cloudViewer::SquareMatrixTpl< Scalar >::getValue(), ecvProgressDialog::isCancelRequested(), ccObject::isEnabled(), ccSNECloud::isSNECloud(), ccTrace::isTrace(), ccGeoObject::LOWER_BOUNDARY, ccStdPluginInterface::m_app, Vector3Tpl< Type >::norm2(), normal, Vector3Tpl< Type >::normalize(), CV_TYPES::POINT_CLOUD, points, CV_TYPES::POLY_LINE, result, ccGenericPrimitive::setColor(), cloudViewer::PointCloudTpl< T >::setCurrentOutScalarField(), ecvProgressDialog::setInfo(), ccObject::setMetaData(), ecvProgressDialog::setMethodTitle(), ccGLMatrixTpl< T >::setTranslation(), cloudViewer::SquareMatrixTpl< Scalar >::setValue(), ccDrawableObject::showColors(), ccGenericMesh::showWired(), cloudViewer::PointCloudTpl< T >::size(), Jacobi< Scalar >::SortEigenValuesAndVectors(), ecvProgressDialog::start(), cloudViewer::SquareMatrixTpl< Scalar >::toGlMatrix(), cloudViewer::SquareMatrixTpl< Scalar >::toIdentity(), cloudViewer::SquareMatrixTpl< Scalar >::transposed(), ecvProgressDialog::update(), ccGeoObject::UPPER_BOUNDARY, useExternalSNE, Tuple3Tpl< Type >::x, x, Tuple3Tpl< Type >::y, y, Tuple3Tpl< Type >::z, and z.
Referenced by doAction().
estimateStructureNormals
void ccCompass::estimateStructureNormals () protected slot
Definition at line 1312 of file ccCompass.cpp.
References cloudViewer::ScalarField::addElement(), ccPointCloud::addNorm(), cloudViewer::PointCloudTpl< T >::addPoint(), ecvMainAppInterface::addToDB(), calcThickness, cloudViewer::ReferenceCloud::clear(), Jacobi< Scalar >::ComputeEigenValuesAndVectors(), cloudViewer::ScalarField::computeMinAndMax(), cloudViewer::DistanceComputationTools::computePoint2PlaneDistance(), count, data, ecvMainAppInterface::dispToConsole(), dof, Vector3Tpl< Type >::dot(), e2, e3, ecvMainAppInterface::ERR_CONSOLE_MESSAGE, ccHObject::filterChildren(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), cloudViewer::Neighbourhood::getLSPlaneX(), ecvMainAppInterface::getMainWindow(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::ReferenceCloud::getPoint(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), ccTrace::getPointNormal(), ccPointCloud::getPointNormal(), ccGeoObject::getRegion(), cloudViewer::PointCloudTpl< T >::getScalarField(), ecvMainAppInterface::getSelectedEntities(), cloudViewer::ScalarField::getValue(), CV_TYPES::HIERARCHY_OBJECT, ecvProgressDialog::isCancelRequested(), ccGeoObject::isGeoObject(), ccPinchNode::isPinchNode(), ccGeoObject::isSingleSurfaceGeoObject(), ccTrace::isTrace(), likPower, logWishart(), logWishSF(), ccGeoObject::LOWER_BOUNDARY, ccStdPluginInterface::m_app, M_PI, cloudViewer::SquareMatrixTpl< Scalar >::m_values, maxsize, minsize, normal, ccPointCloud::normalsHaveChanged(), oversample, points, CV_TYPES::POLY_LINE, prior(), ecvMainAppInterface::refreshAll(), ccPointCloud::reserve(), ccPointCloud::reserveTheNormsTable(), result, ccPointCloud::setCurrentDisplayedScalarField(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), ccObject::setName(), ccPointCloud::setPointNormal(), cloudViewer::ScalarField::setValue(), ccDrawableObject::showSF(), ccPointCloud::shrinkToFit(), cloudViewer::PointCloudTpl< T >::size(), cloudViewer::ReferenceCloud::size(), size, Jacobi< Scalar >::SortEigenValuesAndVectors(), ccPluginInterface::start(), ecvProgressDialog::start(), ecvMainAppInterface::STD_CONSOLE_MESSAGE, ecvProgressDialog::stop(), stride, tcDistance, ecvProgressDialog::update(), ccGeoObject::UPPER_BOUNDARY, ecvMainAppInterface::WRN_CONSOLE_MESSAGE, Tuple3Tpl< Type >::x, X, x, Tuple3Tpl< Type >::y, y, Tuple3Tpl< Type >::z, and z.
Referenced by doAction().
eventFilter()
bool ccCompass::eventFilter (QObject * obj, QEvent * event) override protected virtual
Definition at line 725 of file ccCompass.cpp.
References ccTrace::COST_MODE, costMode, event, fitPlanes, ccCompassDlg::getCostMode(), m_dlg, ccCompassDlg::planeFitMode(), and stopMeasuring().
exportToSVG
void ccCompass::exportToSVG () protected slot
Definition at line 3962 of file ccCompass.cpp.
References count, ecvMainAppInterface::dbRootObject(), ecvMainAppInterface::dispToConsole(), QtCompat::endl(), filename, ccHObject::filterChildren(), ecvDisplayTools::GlHeight(), ecvDisplayTools::GlWidth(), height, ccObject::isA(), ccDrawableObject::isVisible(), ccStdPluginInterface::m_app, m_dlg, CV_TYPES::OBJECT, CV_TYPES::POINT_CLOUD, ccDrawableObject::setVisible(), width, writeTracesSVG(), and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by doAction().
fitPlaneToGeoObject
void ccCompass::fitPlaneToGeoObject () protected slot
Definition at line 1031 of file ccCompass.cpp.
References ccHObject::addChild(), ecvMainAppInterface::addToDB(), ecvMainAppInterface::dbRootObject(), ecvMainAppInterface::dispToConsole(), ccHObject::find(), ccFitPlane::Fit(), ccHObject::getChild(), ccHObject::getChildrenNumber(), cloudViewer::ReferenceCloud::getPoint(), ccGeoObject::getRegion(), ccGeoObject::isSingleSurfaceGeoObject(), ccTrace::isTrace(), ccGeoObject::LOWER_BOUNDARY, ccStdPluginInterface::m_app, m_geoObject_id, points, ccObject::setMetaData(), cloudViewer::ReferenceCloud::size(), ecvMainAppInterface::STD_CONSOLE_MESSAGE, ccGeoObject::UPPER_BOUNDARY, and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by doAction().
getInsertPoint()
ccHObject * ccCompass::getInsertPoint () protected
Definition at line 590 of file ccCompass.cpp.
References ccHObject::addChild(), ecvMainAppInterface::addToDB(), ecvMainAppInterface::dbRootObject(), ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, ccHObject::find(), ccHObject::getChild(), ccObject::getName(), ccGeoObject::getRegion(), ccStdPluginInterface::m_app, m_geoObject, m_geoObject_id, mapMode, mapTo, and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by pointPicked().
hideAllPointClouds
void ccCompass::hideAllPointClouds (ccHObject * o) protected slot
Definition at line 3488 of file ccCompass.cpp.
References ccHObject::getChild(), ccHObject::getChildrenNumber(), ccObject::getUniqueID(), ccObject::isKindOf(), ccDrawableObject::isVisible(), m_hiddenObjects, CV_TYPES::POINT_CLOUD, and ccDrawableObject::setVisible().
Referenced by setPick(), and setYoungerThan().
importFoliations
void ccCompass::importFoliations () protected slot
Definition at line 3706 of file ccCompass.cpp.
References ccHObject::addChild(), ecvMainAppInterface::addToDB(), ccHObject::applyGLTransformation_recursive(), ccNormalVectors::ConvertDipAndDipDirToNormal(), cloudViewer::DegreesToRadians(), ecvMainAppInterface::dispToConsole(), Vector3Tpl< Type >::dot(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, ccGLMatrixTpl< float >::FromToRotation(), ccPlane::getCenter(), ecvMainAppInterface::getMainWindow(), ccPlane::getNormal(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::PointCloudTpl< T >::getScalarFieldName(), ecvMainAppInterface::getSelectedEntities(), ccGLMatrixTpl< T >::getTranslationAsVec3D(), ccGLMatrixTpl< T >::initFromParameters(), ccStdPluginInterface::m_app, PC_ONE, CV_TYPES::POINT_CLOUD, result, rotation, ccGLMatrixTpl< T >::setTranslation(), ccPlane::setXWidth(), ccPlane::setYWidth(), ccDrawableObject::showNameIn3D(), cloudViewer::PointCloudTpl< T >::size(), size, and Tuple3Tpl< Type >::z.
Referenced by doAction().
importLineations
void ccCompass::importLineations () protected slot
Definition at line 3851 of file ccCompass.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), ecvMainAppInterface::addToDB(), cloudViewer::DegreesToRadians(), ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ecvMainAppInterface::getMainWindow(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::PointCloudTpl< T >::getScalarFieldName(), ecvMainAppInterface::getSelectedEntities(), ccStdPluginInterface::m_app, CV_TYPES::POINT_CLOUD, points, result, ccObject::setName(), cloudViewer::PointCloudTpl< T >::size(), size, and ccLineation::updateMetadata().
Referenced by doAction().
madeByMe()
bool ccCompass::madeByMe (ccHObject * object) protected
Definition at line 759 of file ccCompass.cpp.
mergeGeoObjects
void ccCompass::mergeGeoObjects () protected slot
Definition at line 971 of file ccCompass.cpp.
References ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, ccObject::getName(), ccGeoObject::getRegion(), ecvMainAppInterface::getSelectedEntities(), ccGeoObject::INTERIOR, ccGeoObject::isGeoObject(), ccGeoObject::LOWER_BOUNDARY, ccStdPluginInterface::m_app, ecvMainAppInterface::refreshAll(), ecvMainAppInterface::removeFromDB(), ecvMainAppInterface::setSelectedInDB(), ecvMainAppInterface::STD_CONSOLE_MESSAGE, ccHObject::transferChildren(), and ccGeoObject::UPPER_BOUNDARY.
Referenced by doAction().
onAccept
void ccCompass::onAccept () protected slot
Definition at line 752 of file ccCompass.cpp.
References ccTool::accept(), and m_activeTool.
Referenced by doAction().
onClose
void ccCompass::onClose () protected slot
Definition at line 742 of file ccCompass.cpp.
References ccTool::cancel(), m_activeTool, and stopMeasuring().
Referenced by doAction().
onItemPicked
void ccCompass::onItemPicked (const ccPickingListener::PickedItem & pi) override protected virtual slot
Definition at line 669 of file ccCompass.cpp.
References ccPickingListener::PickedItem::clickPoint, ccPickingListener::PickedItem::entity, ccPickingListener::PickedItem::itemIndex, ccPickingListener::PickedItem::P3D, and pointPicked().
onSave
void ccCompass::onSave () protected slot
Definition at line 4118 of file ccCompass.cpp.
References ecvMainAppInterface::dbRootObject(), ecvMainAppInterface::dispToConsole(), QtCompat::endl(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, filename, ccHObject::getChild(), ccStdPluginInterface::m_app, m_dlg, ecvMainAppInterface::STD_CONSOLE_MESSAGE, writeLineations(), writePlanes(), writeToXML(), writeTraces(), and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by doAction().
onUndo
void ccCompass::onUndo () protected slot
Definition at line 765 of file ccCompass.cpp.
References m_activeTool, and ccTool::undo().
Referenced by doAction().
pointPicked
void ccCompass::pointPicked (ccHObject * entity, unsigned itemIdx, int x, int y, const CCVector3 & P) protected slot
Definition at line 675 of file ccCompass.cpp.
References getInsertPoint(), ccObject::isKindOf(), m_activeTool, ccStdPluginInterface::m_app, CV_TYPES::POINT_CLOUD, ccTool::pointPicked(), ecvDisplayTools::RedrawDisplay(), ccObject::setEnabled(), ecvMainAppInterface::setSelectedInDB(), ecvMainAppInterface::updateUI(), and CVLog::Warning().
Referenced by onItemPicked().
recalculateFitPlanes
void ccCompass::recalculateFitPlanes () protected slot
Definition at line 1127 of file ccCompass.cpp.
References ccHObject::addChild(), ecvMainAppInterface::addToDB(), ecvMainAppInterface::dbRootObject(), ccHObject::filterChildren(), ccTrace::fitPlane(), ccHObject::getChild(), ccHObject::getParent(), ccFitPlane::isFitPlane(), ccTrace::isTrace(), ccStdPluginInterface::m_app, and CV_TYPES::PLANE.
Referenced by doAction().
recalculateSelectedTraces
void ccCompass::recalculateSelectedTraces () protected slot
Definition at line 3474 of file ccCompass.cpp.
References ccTrace::COST_MODE, ccCompassDlg::getCostMode(), ecvMainAppInterface::getSelectedEntities(), ccTrace::isTrace(), ccStdPluginInterface::m_app, m_dlg, ccTrace::recalculatePath(), and ecvDisplayTools::RedrawDisplay().
Referenced by doAction().
recurseLabels
void ccCompass::recurseLabels (ccHObject * object, bool checked) protected slot
Definition at line 3531 of file ccCompass.cpp.
References ccHObject::getChild(), ccFitPlane::isFitPlane(), and ccPointPair::isPointPair().
Referenced by toggleLabels().
recurseNormals
void ccCompass::recurseNormals (ccHObject * object, bool checked) protected slot
Definition at line 3552 of file ccCompass.cpp.
References ccHObject::getChild(), ccFitPlane::isFitPlane(), and ccPlanarEntityInterface::showNormalVector().
Referenced by toggleNormals().
recurseStipple
void ccCompass::recurseStipple (ccHObject * object, bool checked) protected slot
Definition at line 3509 of file ccCompass.cpp.
References ccGenericMesh::enableStippling(), ccHObject::getChild(), and ccFitPlane::isFitPlane().
Referenced by toggleStipple().
setEquivalent
void ccCompass::setEquivalent () protected slot
Definition at line 948 of file ccCompass.cpp.
References ccTopologyRelation::EQUIVALENCE, ccTopologyTool::RELATIONSHIP, and setYoungerThan().
Referenced by doAction().
setFollows
void ccCompass::setFollows () protected slot
Definition at line 941 of file ccCompass.cpp.
References ccTopologyRelation::IMMEDIATELY_FOLLOWS, ccTopologyTool::RELATIONSHIP, and setYoungerThan().
Referenced by doAction().
setLineation
void ccCompass::setLineation () protected slot
Definition at line 809 of file ccCompass.cpp.
References cleanupBeforeToolChange(), ecvMainAppInterface::getSelectedEntities(), m_activeTool, ccStdPluginInterface::m_app, m_dlg, m_lineationTool, ecvDisplayTools::RedrawDisplay(), and ccTool::toolActivated().
Referenced by doAction().
setNote
void ccCompass::setNote () protected slot
Definition at line 956 of file ccCompass.cpp.
References ccTool::canUndo(), cleanupBeforeToolChange(), m_activeTool, m_dlg, m_noteTool, ecvDisplayTools::RedrawDisplay(), and ccTool::toolActivated().
Referenced by doAction().
setPick
void ccCompass::setPick () protected slot
Definition at line 864 of file ccCompass.cpp.
References cleanupBeforeToolChange(), ecvMainAppInterface::dbRootObject(), hideAllPointClouds(), m_activeTool, ccStdPluginInterface::m_app, m_dlg, ecvDisplayTools::RedrawDisplay(), and stopPicking().
Referenced by doAction().
setPlane
void ccCompass::setPlane () protected slot
Definition at line 827 of file ccCompass.cpp.
References ccTool::canUndo(), cleanupBeforeToolChange(), ecvMainAppInterface::getSelectedEntities(), m_activeTool, ccStdPluginInterface::m_app, m_dlg, m_fitPlaneTool, ecvDisplayTools::RedrawDisplay(), and ccTool::toolActivated().
Referenced by doAction().
setThickness
void ccCompass::setThickness () protected slot
Definition at line 894 of file ccCompass.cpp.
References ccTool::canUndo(), cleanupBeforeToolChange(), ecvMainAppInterface::getSelectedEntities(), m_activeTool, ccStdPluginInterface::m_app, m_dlg, m_thicknessTool, ecvDisplayTools::RedrawDisplay(), ccTool::toolActivated(), and ccThicknessTool::TWO_POINT_MODE.
Referenced by doAction(), and setThickness2().
setThickness2
void ccCompass::setThickness2 () protected slot
Definition at line 914 of file ccCompass.cpp.
References setThickness(), and ccThicknessTool::TWO_POINT_MODE.
Referenced by doAction().
setTrace
void ccCompass::setTrace () protected slot
Definition at line 845 of file ccCompass.cpp.
References ccTraceTool::canUndo(), cleanupBeforeToolChange(), ecvMainAppInterface::getSelectedEntities(), m_activeTool, ccStdPluginInterface::m_app, m_dlg, m_traceTool, ecvDisplayTools::RedrawDisplay(), and ccTool::toolActivated().
Referenced by doAction().
setYoungerThan
void ccCompass::setYoungerThan () protected slot
Definition at line 920 of file ccCompass.cpp.
References cleanupBeforeToolChange(), ecvMainAppInterface::dbRootObject(), hideAllPointClouds(), m_activeTool, ccStdPluginInterface::m_app, m_dlg, m_topologyTool, ecvDisplayTools::RedrawDisplay(), ccTopologyTool::RELATIONSHIP, stopPicking(), and ccTopologyRelation::YOUNGER_THAN.
Referenced by doAction(), setEquivalent(), and setFollows().
showHelp
void ccCompass::showHelp () protected slot
Definition at line 3567 of file ccCompass.cpp.
References ecvMainAppInterface::getMainWindow(), and ccStdPluginInterface::m_app.
Referenced by doAction().
startMeasuring
bool ccCompass::startMeasuring () protected slot
Definition at line 481 of file ccCompass.cpp.
References ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, ecvMainAppInterface::getActiveWindow(), m_active, m_activeTool, ccStdPluginInterface::m_app, m_dlg, ecvDisplayTools::RedrawDisplay(), ecvMainAppInterface::registerOverlayDialog(), ccOverlayDialog::start(), and ccTool::toolActivated().
Referenced by doAction().
startPicking()
bool ccCompass::startPicking () protected
Definition at line 555 of file ccCompass.cpp.
References ccPickingHub::addListener(), ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, ccStdPluginInterface::m_app, m_picking, and ecvMainAppInterface::pickingHub().
Referenced by cleanupBeforeToolChange().
stopMeasuring
bool ccCompass::stopMeasuring (bool finalStop = false) protected slot
Definition at line 511 of file ccCompass.cpp.
References ccTool::cancel(), cleanupBeforeToolChange(), ecvMainAppInterface::getActiveWindow(), m_active, m_activeTool, ccStdPluginInterface::m_app, m_dlg, m_mapDlg, ecvMainAppInterface::refreshAll(), ccOverlayDialog::stop(), stopPicking(), ccTool::toolDisactivated(), and ecvMainAppInterface::unregisterOverlayDialog().
Referenced by eventFilter(), and onClose().
stopPicking()
void ccCompass::stopPicking () protected
Definition at line 580 of file ccCompass.cpp.
References ccStdPluginInterface::m_app, m_picking, ecvMainAppInterface::pickingHub(), and ccPickingHub::removeListener().
Referenced by setPick(), setYoungerThan(), and stopMeasuring().
toggleLabels
void ccCompass::toggleLabels (bool checked) protected slot
Definition at line 3524 of file ccCompass.cpp.
References ecvMainAppInterface::dbRootObject(), drawName, ccStdPluginInterface::m_app, recurseLabels(), and ecvDisplayTools::RedrawDisplay().
Referenced by doAction().
toggleNormals
void ccCompass::toggleNormals (bool checked) protected slot
Definition at line 3545 of file ccCompass.cpp.
References ecvMainAppInterface::dbRootObject(), drawNormals, ccStdPluginInterface::m_app, recurseNormals(), and ecvDisplayTools::RedrawDisplay().
Referenced by doAction().
toggleStipple
void ccCompass::toggleStipple (bool checked) protected slot
Definition at line 3501 of file ccCompass.cpp.
References ecvMainAppInterface::dbRootObject(), drawStippled, ccStdPluginInterface::m_app, recurseStipple(), and ecvDisplayTools::RedrawDisplay().
Referenced by doAction().
tryLoading() [1/2]
void ccCompass::tryLoading () protected
Definition at line 315 of file ccCompass.cpp.
References ccHObject::addChild(), ecvMainAppInterface::addToDB(), ecvMainAppInterface::dbRootObject(), ccHObject::detachAllChildren(), ccHObject::find(), ccHObject::getChild(), ccHObject::getChildrenNumber(), ecvMainAppInterface::getMainWindow(), ccHObject::getParent(), ccObject::isEnabled(), ccGeoObject::isGeoObject(), ccDrawableObject::isVisible(), ccStdPluginInterface::m_app, ecvMainAppInterface::removeFromDB(), ccGeoObject::setActive(), ccObject::setEnabled(), ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), ccDrawableObject::setVisible(), and ecvProgressDialog::start().
Referenced by doAction(), and tryLoading().
tryLoading() [2/2]
void ccCompass::tryLoading (ccHObject * obj, std::vector< int > * originals, std::vector< ccHObject * > * replacements) protected
Definition at line 375 of file ccCompass.cpp.
References ccHObject::getChild(), ccHObject::getChildrenNumber(), ccObject::getUniqueID(), ccFitPlane::isFitPlane(), ccGeoObject::isGeoObject(), ccLineation::isLineation(), ccNote::isNote(), ccPinchNode::isPinchNode(), ccSNECloud::isSNECloud(), ccThickness::isThickness(), ccTrace::isTrace(), ccStdPluginInterface::m_app, ccPolyline::setWidth(), and tryLoading().
writeLineations()
int ccCompass::writeLineations (ccHObject * object, QTextStream * out, const QString & parentName = QString(), bool thickness = false) protected
Definition at line 4434 of file ccCompass.cpp.
Referenced by onSave().
writeObjectXML()
int ccCompass::writeObjectXML (ccHObject * object, QXmlStreamWriter * out) protected
Definition at line 4523 of file ccCompass.cpp.
Referenced by writeToXML().
writePlanes()
int ccCompass::writePlanes (ccHObject * object, QTextStream * out, const QString & parentName = QString()) protected
Definition at line 4257 of file ccCompass.cpp.
Referenced by onSave().
writeToInterior
void ccCompass::writeToInterior () protected slot
Definition at line 3677 of file ccCompass.cpp.
References ccGeoObject::INTERIOR, m_mapDlg, and mapTo.
Referenced by doAction().
writeToLower
void ccCompass::writeToLower () protected slot
Definition at line 3695 of file ccCompass.cpp.
References ccGeoObject::LOWER_BOUNDARY, m_mapDlg, and mapTo.
Referenced by doAction().
writeToUpper
void ccCompass::writeToUpper () protected slot
Definition at line 3686 of file ccCompass.cpp.
References m_mapDlg, mapTo, and ccGeoObject::UPPER_BOUNDARY.
Referenced by doAction().
writeToXML()
int ccCompass::writeToXML (const QString & filename) protected
Definition at line 4475 of file ccCompass.cpp.
References ecvMainAppInterface::dbRootObject(), ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, filename, ccHObject::getChild(), ccHObject::getChildrenNumber(), ccStdPluginInterface::m_app, ecvMainAppInterface::STD_CONSOLE_MESSAGE, and writeObjectXML().
Referenced by onSave().
writeTraces()
int ccCompass::writeTraces (ccHObject * object, QTextStream * out, const QString & parentName = QString()) protected
Definition at line 4370 of file ccCompass.cpp.
Referenced by onSave().
writeTracesSVG()
int ccCompass::writeTracesSVG (ccHObject * object, QTextStream * out, int height, float zoom) protected
Definition at line 4058 of file ccCompass.cpp.
Referenced by exportToSVG().
Member Data Documentation
costMode
int ccCompass::costMode = ccTrace::DARK static
Definition at line 264 of file ccCompass.h.
Referenced by eventFilter().
drawName
bool ccCompass::drawName = false static
Definition at line 258 of file ccCompass.h.
Referenced by ccFitPlane::ccFitPlane(), ccLineationTool::pointPicked(), and toggleLabels().
drawNormals
bool ccCompass::drawNormals = true static
Definition at line 260 of file ccCompass.h.
Referenced by ccFitPlane::ccFitPlane(), and toggleNormals().
drawStippled
bool ccCompass::drawStippled = true static
Definition at line 259 of file ccCompass.h.
Referenced by ccFitPlane::ccFitPlane(), and toggleStipple().
fitPlanes
bool ccCompass::fitPlanes = true static
Definition at line 263 of file ccCompass.h.
Referenced by eventFilter(), and ccTraceTool::finishCurrentTrace().
m_action
QAction* ccCompass::m_action = nullptr protected
Definition at line 177 of file ccCompass.h.
m_active
bool ccCompass::m_active = false protected
Definition at line 184 of file ccCompass.h.
Referenced by startMeasuring(), and stopMeasuring().
m_activeTool
ccTool* ccCompass::m_activeTool = nullptr protected
Definition at line 191 of file ccCompass.h.
Referenced by addPinchNode(), cleanupBeforeToolChange(), onAccept(), onClose(), onUndo(), pointPicked(), setLineation(), setNote(), setPick(), setPlane(), setThickness(), setTrace(), setYoungerThan(), startMeasuring(), and stopMeasuring().
m_dlg
ccCompassDlg* ccCompass::m_dlg = nullptr protected
Definition at line 187 of file ccCompass.h.
Referenced by addPinchNode(), cleanupBeforeToolChange(), doAction(), enableMapMode(), enableMeasureMode(), eventFilter(), exportToSVG(), onSave(), recalculateSelectedTraces(), setLineation(), setNote(), setPick(), setPlane(), setThickness(), setTrace(), setYoungerThan(), startMeasuring(), and stopMeasuring().
m_fitPlaneTool
ccFitPlaneTool* ccCompass::m_fitPlaneTool protected
Definition at line 192 of file ccCompass.h.
Referenced by doAction(), and setPlane().
m_geoObject
ccGeoObject* ccCompass::m_geoObject protected
Initial value:
=
            nullptr
Definition at line 201 of file ccCompass.h.
Referenced by getInsertPoint().
m_geoObject_id
int ccCompass::m_geoObject_id = -1 protected
Definition at line 203 of file ccCompass.h.
Referenced by fitPlaneToGeoObject(), and getInsertPoint().
m_hiddenObjects
std::vector<int> ccCompass::m_hiddenObjects protected
Definition at line 204 of file ccCompass.h.
Referenced by cleanupBeforeToolChange(), and hideAllPointClouds().
m_lastGeoObjectName
QString ccCompass::m_lastGeoObjectName = "GeoObject" protected
Definition at line 207 of file ccCompass.h.
Referenced by addGeoObject().
m_lineationTool
ccLineationTool* ccCompass::m_lineationTool protected
Definition at line 194 of file ccCompass.h.
Referenced by doAction(), and setLineation().
m_main_window
QMainWindow* ccCompass::m_main_window = nullptr protected
Definition at line 180 of file ccCompass.h.
m_mapDlg
ccMapDlg* ccCompass::m_mapDlg = nullptr protected
Definition at line 188 of file ccCompass.h.
Referenced by doAction(), enableMapMode(), enableMeasureMode(), stopMeasuring(), writeToInterior(), writeToLower(), and writeToUpper().
m_noteTool
ccNoteTool* ccCompass::m_noteTool protected
Definition at line 197 of file ccCompass.h.
Referenced by doAction(), and setNote().
m_picking
bool ccCompass::m_picking = false protected
Definition at line 183 of file ccCompass.h.
Referenced by startPicking(), and stopPicking().
m_pinchNodeTool
ccPinchNodeTool* ccCompass::m_pinchNodeTool protected
Definition at line 198 of file ccCompass.h.
Referenced by addPinchNode(), and doAction().
m_thicknessTool
ccThicknessTool* ccCompass::m_thicknessTool protected
Definition at line 195 of file ccCompass.h.
Referenced by doAction(), and setThickness().
m_topologyTool
ccTopologyTool* ccCompass::m_topologyTool protected
Definition at line 196 of file ccCompass.h.
Referenced by doAction(), and setYoungerThan().
m_traceTool
ccTraceTool* ccCompass::m_traceTool protected
Definition at line 193 of file ccCompass.h.
Referenced by doAction(), and setTrace().
mapMode
bool ccCompass::mapMode = false static
Definition at line 267 of file ccCompass.h.
Referenced by enableMapMode(), enableMeasureMode(), ccTraceTool::finishCurrentTrace(), and getInsertPoint().
mapTo
int ccCompass::mapTo = ccGeoObject::LOWER_BOUNDARY static
Definition at line 268 of file ccCompass.h.
Referenced by getInsertPoint(), writeToInterior(), writeToLower(), and writeToUpper().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCompass/include/ccCompass.h
/root/ACloudViewer/plugins/core/Standard/qCompass/src/ccCompass.cpp