ACloudViewer: colmap::ImageReader Class Reference
colmap::ImageReader Class Reference
#include <image_reader.h>
Public Types
enum class Status {
FAILURE , SUCCESS , IMAGE_EXISTS , BITMAP_ERROR ,
CAMERA_SINGLE_DIM_ERROR , CAMERA_EXIST_DIM_ERROR , CAMERA_PARAM_ERROR
}
Public Member Functions
ImageReader (const ImageReaderOptions &options, Database *database)
Status Next (Camera *camera, Image *image, Bitmap *bitmap, Bitmap *mask)
size_t NextIndex () const
size_t NumImages () const
Detailed Description
Definition at line 74 of file image_reader.h.
Member Enumeration Documentation
Status
enum colmap::ImageReader::Status strong
Enumerator
FAILURE
SUCCESS
IMAGE_EXISTS
BITMAP_ERROR
CAMERA_SINGLE_DIM_ERROR
CAMERA_EXIST_DIM_ERROR
CAMERA_PARAM_ERROR
Definition at line 76 of file image_reader.h.
Constructor & Destructor Documentation
ImageReader()
colmap::ImageReader::ImageReader (const ImageReaderOptions & options, Database * database)
Definition at line 50 of file image_reader.cc.
Member Function Documentation
Next()
ImageReader::Status colmap::ImageReader::Next (Camera * camera, Image * image, Bitmap * bitmap, Bitmap * mask)
Definition at line 86 of file image_reader.cc.
References BITMAP_ERROR, CAMERA_EXIST_DIM_ERROR, CAMERA_PARAM_ERROR, colmap::ImageReaderOptions::camera_params, CAMERA_SINGLE_DIM_ERROR, colmap::Camera::CameraId(), colmap::ImageReaderOptions::default_focal_length_factor, colmap::Bitmap::ExifAltitude(), colmap::Bitmap::ExifCameraModel(), colmap::Bitmap::ExifFocalLength(), colmap::Bitmap::ExifLatitude(), colmap::Bitmap::ExifLongitude(), colmap::ImageReaderOptions::existing_camera_id, colmap::Database::ExistsDescriptors(), colmap::ExistsFile(), colmap::Database::ExistsImageWithName(), colmap::Database::ExistsKeypoints(), colmap::GetParentDir(), colmap::GetRelativePath(), colmap::Camera::Height(), colmap::Bitmap::Height(), image, IMAGE_EXISTS, colmap::ImageReaderOptions::image_list, colmap::ImageReaderOptions::image_path, colmap::Camera::InitializeWithId(), colmap::JoinPaths(), colmap::kInvalidCameraId, colmap::ImageReaderOptions::mask_path, colmap::Camera::ModelId(), colmap::Bitmap::Read(), colmap::Database::ReadCamera(), colmap::Database::ReadImageWithName(), colmap::Camera::SetCameraId(), colmap::Camera::SetHeight(), colmap::Camera::SetPriorFocalLength(), colmap::Camera::SetWidth(), colmap::ImageReaderOptions::single_camera, colmap::ImageReaderOptions::single_camera_per_folder, colmap::ImageReaderOptions::single_camera_per_image, colmap::StringReplace(), SUCCESS, colmap::Camera::VerifyParams(), colmap::Camera::Width(), colmap::Bitmap::Width(), and colmap::Database::WriteCamera().
NextIndex()
size_t colmap::ImageReader::NextIndex () const
Definition at line 260 of file image_reader.cc.
NumImages()
size_t colmap::ImageReader::NumImages () const
Definition at line 262 of file image_reader.cc.
References colmap::ImageReaderOptions::image_list.
Referenced by colmap::SiftFeatureExtractor::SiftFeatureExtractor().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/image_reader.h
/root/ACloudViewer/libs/Reconstruction/src/base/image_reader.cc