ACloudViewer: cloudViewer::core::TensorKey::SliceImpl Class Reference
cloudViewer::core::TensorKey::SliceImpl Class Reference
Public Member Functions
SliceImpl (utility::optional< int64_t > start, utility::optional< int64_t > stop, utility::optional< int64_t > step)
std::shared_ptr< SliceImpl > InstantiateDimSize (int64_t dim_size) const
int64_t GetStart () const
int64_t GetStop () const
int64_t GetStep () const
std::string ToString () const override
Public Member Functions inherited from cloudViewer::core::TensorKey::Impl
Impl (TensorKeyMode mode)
TensorKeyMode GetMode () const
virtual ~Impl ()
Detailed Description
Definition at line 46 of file TensorKey.cpp.
Constructor & Destructor Documentation
SliceImpl()
cloudViewer::core::TensorKey::SliceImpl::SliceImpl (utility::optional< int64_t > start, utility::optional< int64_t > stop, utility::optional< int64_t > step) inline
Definition at line 48 of file TensorKey.cpp.
Member Function Documentation
GetStart()
int64_t cloudViewer::core::TensorKey::SliceImpl::GetStart () const inline
Definition at line 61 of file TensorKey.cpp.
References cloudViewer::utility::optional< T >::has_value(), LogError, and cloudViewer::utility::optional< T >::value().
GetStep()
int64_t cloudViewer::core::TensorKey::SliceImpl::GetStep () const inline
Definition at line 75 of file TensorKey.cpp.
References cloudViewer::utility::optional< T >::has_value(), LogError, and cloudViewer::utility::optional< T >::value().
GetStop()
int64_t cloudViewer::core::TensorKey::SliceImpl::GetStop () const inline
Definition at line 68 of file TensorKey.cpp.
References cloudViewer::utility::optional< T >::has_value(), LogError, and cloudViewer::utility::optional< T >::value().
InstantiateDimSize()
std::shared_ptr<SliceImpl> cloudViewer::core::TensorKey::SliceImpl::InstantiateDimSize (int64_t dim_size) const inline
Definition at line 55 of file TensorKey.cpp.
References cloudViewer::utility::optional< T >::has_value(), and cloudViewer::utility::optional< T >::value().
ToString()
std::string cloudViewer::core::TensorKey::SliceImpl::ToString () const inline override virtual
Implements cloudViewer::core::TensorKey::Impl.
Definition at line 82 of file TensorKey.cpp.
References cloudViewer::utility::optional< T >::has_value(), and cloudViewer::utility::optional< T >::value().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/TensorKey.cpp