ACloudViewer: colmap::Reconstruction Class Reference
colmap::Reconstruction Class Reference
#include <reconstruction.h>
Classes
struct ImagePairStat
Public Member Functions
Reconstruction ()
Reconstruction (const Reconstruction &other)
Reconstruction & operator= (const Reconstruction &other)
size_t NumCameras () const
size_t NumImages () const
size_t NumRegImages () const
size_t NumPoints3D () const
size_t NumImagePairs () const
size_t NumAddedPoints3D () const
const class Camera & Camera (const camera_t camera_id) const
const class Image & Image (const image_t image_id) const
const class Point3D & Point3D (const point3D_t point3D_id) const
const ImagePairStat & ImagePair (const image_pair_t pair_id) const
ImagePairStat & ImagePair (const image_t image_id1, const image_t image_id2)
class Camera & Camera (const camera_t camera_id)
class Image & Image (const image_t image_id)
class Point3D & Point3D (const point3D_t point3D_id)
ImagePairStat & ImagePair (const image_pair_t pair_id)
const ImagePairStat & ImagePair (const image_t image_id1, const image_t image_id2) const
const std::unordered_map< camera_t, class Camera > & Cameras () const
const std::unordered_map< image_t, class Image > & Images () const
const std::vector< image_t > & RegImageIds () const
const std::unordered_map< point3D_t, class Point3D > & Points3D () const
const std::unordered_map< image_pair_t, ImagePairStat > & ImagePairs () const
std::unordered_set< point3D_t > Point3DIds () const
bool ExistsCamera (const camera_t camera_id) const
bool ExistsImage (const image_t image_id) const
bool ExistsPoint3D (const point3D_t point3D_id) const
bool ExistsImagePair (const image_pair_t pair_id) const
void Load (const DatabaseCache &database_cache)
void SetUp (const CorrespondenceGraph *correspondence_graph)
void TearDown ()
void AddCamera (const class Camera &camera)
void AddImage (const class Image &image)
point3D_t AddPoint3D (const Eigen::Vector3d &xyz, const Track &track, const Eigen::Vector3ub &color=Eigen::Vector3ub::Zero())
void AddObservation (const point3D_t point3D_id, const TrackElement &track_el)
point3D_t MergePoints3D (const point3D_t point3D_id1, const point3D_t point3D_id2)
void DeletePoint3D (const point3D_t point3D_id)
void DeleteObservation (const image_t image_id, const point2D_t point2D_idx)
void DeleteAllPoints2DAndPoints3D ()
void RegisterImage (const image_t image_id)
void DeRegisterImage (const image_t image_id)
bool IsImageRegistered (const image_t image_id) const
void Normalize (const double extent=10.0, const double p0=0.1, const double p1=0.9, const bool use_images=true)
Eigen::Vector3d ComputeCentroid (const double p0=0.1, const double p1=0.9) const
std::pair< Eigen::Vector3d, Eigen::Vector3d > ComputeBoundingBox (const double p0=0.0, const double p1=1.0) const
void Transform (const SimilarityTransform3 &tform)
Reconstruction Crop (const std::pair< Eigen::Vector3d, Eigen::Vector3d > &bbox) const
bool Merge (const Reconstruction &reconstruction, const double max_reproj_error)
template<bool kEstimateScale = true>
bool Align (const std::vector< std::string > &image_names, const std::vector< Eigen::Vector3d > &locations, const int min_common_images, SimilarityTransform3 *tform=nullptr)
template<bool kEstimateScale = true>
bool AlignRobust (const std::vector< std::string > &image_names, const std::vector< Eigen::Vector3d > &locations, const int min_common_images, const RANSACOptions &ransac_options, SimilarityTransform3 *tform=nullptr)
const class Image * FindImageWithName (const std::string &name) const
std::vector< image_t > FindCommonRegImageIds (const Reconstruction &reconstruction) const
void TranscribeImageIdsToDatabase (const Database &database)
size_t FilterPoints3D (const double max_reproj_error, const double min_tri_angle, const std::unordered_set< point3D_t > &point3D_ids)
size_t FilterPoints3DInImages (const double max_reproj_error, const double min_tri_angle, const std::unordered_set< image_t > &image_ids)
size_t FilterAllPoints3D (const double max_reproj_error, const double min_tri_angle)
size_t FilterObservationsWithNegativeDepth ()
std::vector< image_t > FilterImages (const double min_focal_length_ratio, const double max_focal_length_ratio, const double max_extra_param)
size_t ComputeNumObservations () const
double ComputeMeanTrackLength () const
double ComputeMeanObservationsPerRegImage () const
double ComputeMeanReprojectionError () const
void Read (const std::string &path)
void Write (const std::string &path) const
void ReadText (const std::string &path)
void ReadBinary (const std::string &path)
void WriteText (const std::string &path) const
void WriteBinary (const std::string &path) const
std::vector< PlyPoint > ConvertToPLY () const
void ImportPLY (const std::string &path)
void ImportPLY (const std::vector< PlyPoint > &ply_points)
bool ExportNVM (const std::string &path, bool skip_distortion=false) const
bool ExportCam (const std::string &path, bool skip_distortion=false) const
bool ExportRecon3D (const std::string &path, bool skip_distortion=false) const
bool ExportBundler (const std::string &path, const std::string &list_path, bool skip_distortion=false) const
void ExportPLY (const std::string &path) const
void ExportVRML (const std::string &images_path, const std::string &points3D_path, const double image_scale, const Eigen::Vector3d &image_rgb) const
bool ExtractColorsForImage (const image_t image_id, const std::string &path)
void ExtractColorsForAllImages (const std::string &path)
void CreateImageDirs (const std::string &path) const
const CorrespondenceGraph * GetCorrespondenceGraph () const
bool HasCorrespondenceGraph () const
Detailed Description
Definition at line 40 of file reconstruction.h.
Constructor & Destructor Documentation
Reconstruction() [1/2]
colmap::Reconstruction::Reconstruction ()
Definition at line 47 of file reconstruction.cc.
Reconstruction() [2/2]
colmap::Reconstruction::Reconstruction (const Reconstruction & other)
Definition at line 50 of file reconstruction.cc.
Member Function Documentation
AddCamera()
void colmap::Reconstruction::AddCamera (const class Camera & camera)
Definition at line 178 of file reconstruction.cc.
References colmap::Camera::CameraId(), ExistsCamera(), and colmap::Camera::VerifyParams().
Referenced by BOOST_AUTO_TEST_CASE(), Crop(), GenerateReconstruction(), Load(), and Merge().
AddImage()
void colmap::Reconstruction::AddImage (const class Image & image)
Definition at line 184 of file reconstruction.cc.
References ExistsImage(), and image.
Referenced by BOOST_AUTO_TEST_CASE(), Crop(), GenerateReconstruction(), Load(), and Merge().
AddObservation()
void colmap::Reconstruction::AddObservation (const point3D_t point3D_id, const TrackElement & track_el)
Definition at line 218 of file reconstruction.cc.
References colmap::Track::AddElement(), image, Image(), colmap::TrackElement::image_id, colmap::TrackElement::point2D_idx, Point3D(), and colmap::Point3D::Track().
Referenced by BOOST_AUTO_TEST_CASE(), GenerateReconstruction(), and colmap::IncrementalMapper::RegisterNextImage().
AddPoint3D()
point3D_t colmap::Reconstruction::AddPoint3D (const Eigen::Vector3d & xyz, const Track & track, const Eigen::Vector3ub & color = Eigen::Vector3ub::Zero())
Definition at line 189 of file reconstruction.cc.
References color, colmap::Track::Elements(), ExistsPoint3D(), image, Image(), colmap::Point3D::SetColor(), colmap::Point3D::SetTrack(), and colmap::Point3D::SetXYZ().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::IncrementalTriangulator::CompleteImage(), Crop(), GeneratePointCloud(), ImportPLY(), Merge(), MergePoints3D(), and colmap::IncrementalMapper::RegisterInitialImagePair().
Align()
template<bool kEstimateScale> bool colmap::Reconstruction::Align (const std::vector< std::string > & image_names, const std::vector< Eigen::Vector3d > & locations, const int min_common_images, SimilarityTransform3 * tform = nullptr)
Definition at line 546 of file reconstruction.h.
References colmap::SimilarityTransform3::Estimate(), FindImageWithName(), image, IsImageRegistered(), and Transform().
Referenced by colmap::RunModelAligner().
AlignRobust()
template<bool kEstimateScale> bool colmap::Reconstruction::AlignRobust (const std::vector< std::string > & image_names, const std::vector< Eigen::Vector3d > & locations, const int min_common_images, const RANSACOptions & ransac_options, SimilarityTransform3 * tform = nullptr)
Definition at line 598 of file reconstruction.h.
References colmap::LORANSAC< Estimator, LocalEstimator, SupportMeasurer, Sampler >::Estimate(), FindImageWithName(), image, IsImageRegistered(), and Transform().
Referenced by colmap::RunModelAligner().
Camera() [1/2]
class Camera & colmap::Reconstruction::Camera (const camera_t camera_id) inline
Definition at line 473 of file reconstruction.h.
Camera() [2/2]
const class Camera & colmap::Reconstruction::Camera (const camera_t camera_id) const inline
Definition at line 450 of file reconstruction.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::IncrementalTriangulator::CompleteImage(), colmap::EstimateManhattanWorldFrame(), ExportBundler(), ExportCam(), ExportNVM(), ExportRecon3D(), FilterImages(), Merge(), colmap::BundleAdjuster::ParameterizeCameras(), colmap::mvs::Model::ReadFromCOLMAP(), colmap::IncrementalMapper::RegisterInitialImagePair(), colmap::IncrementalMapper::RegisterNextImage(), colmap::IncrementalTriangulator::Retriangulate(), SetUp(), colmap::IncrementalTriangulator::TriangulateImage(), and colmap::UndistortReconstruction().
Cameras()
const std::unordered_map< camera_t, Camera > & colmap::Reconstruction::Cameras () const inline
Definition at line 496 of file reconstruction.h.
Referenced by BOOST_AUTO_TEST_CASE(), operator=(), cloudViewer::ModelViewerWidget::ReloadReconstruction(), colmap::ModelViewerWidget::ReloadReconstruction(), and colmap::UndistortReconstruction().
ComputeBoundingBox()
std::pair< Eigen::Vector3d, Eigen::Vector3d > colmap::Reconstruction::ComputeBoundingBox (const double p0 = 0.0, const double p1 = 1.0) const
Definition at line 380 of file reconstruction.cc.
References cloudViewer::core::make_pair().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::RunModelCropper(), and colmap::RunModelSplitter().
ComputeCentroid()
Eigen::Vector3d colmap::Reconstruction::ComputeCentroid (const double p0 = 0.1, const double p1 = 0.9) const
Definition at line 375 of file reconstruction.cc.
Referenced by colmap::AlignToENUPlane(), colmap::AlignToPrincipalPlane(), and BOOST_AUTO_TEST_CASE().
ComputeMeanObservationsPerRegImage()
double colmap::Reconstruction::ComputeMeanObservationsPerRegImage () const
Definition at line 746 of file reconstruction.cc.
References ComputeNumObservations().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::RunModelAnalyzer(), cloudViewer::ReconstructionStatsWidget::Show(), and colmap::ReconstructionStatsWidget::Show().
ComputeMeanReprojectionError()
double colmap::Reconstruction::ComputeMeanReprojectionError () const
Definition at line 755 of file reconstruction.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::RunModelAnalyzer(), cloudViewer::ReconstructionStatsWidget::Show(), and colmap::ReconstructionStatsWidget::Show().
ComputeMeanTrackLength()
double colmap::Reconstruction::ComputeMeanTrackLength () const
Definition at line 738 of file reconstruction.cc.
References ComputeNumObservations().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::RunModelAnalyzer(), cloudViewer::ReconstructionStatsWidget::Show(), and colmap::ReconstructionStatsWidget::Show().
ComputeNumObservations()
size_t colmap::Reconstruction::ComputeNumObservations () const
Definition at line 730 of file reconstruction.cc.
References Image(), and colmap::Image::NumPoints3D().
Referenced by BOOST_AUTO_TEST_CASE(), ComputeMeanObservationsPerRegImage(), ComputeMeanTrackLength(), colmap::RunModelAnalyzer(), colmap::RunPointTriangulator(), cloudViewer::ReconstructionStatsWidget::Show(), and colmap::ReconstructionStatsWidget::Show().
ConvertToPLY()
std::vector< PlyPoint > colmap::Reconstruction::ConvertToPLY () const
Definition at line 813 of file reconstruction.cc.
References colmap::PlyPoint::b, colmap::PlyPoint::g, colmap::PlyPoint::r, colmap::PlyPoint::x, colmap::PlyPoint::y, and colmap::PlyPoint::z.
Referenced by ExportPLY().
CreateImageDirs()
void colmap::Reconstruction::CreateImageDirs (const std::string & path) const
Definition at line 1447 of file reconstruction.cc.
References colmap::CreateDirIfNotExists(), image, colmap::JoinPaths(), cloudViewer::t::geometry::path, and colmap::StringSplit().
Referenced by ExportCam().
Crop()
Reconstruction colmap::Reconstruction::Crop (const std::pair< Eigen::Vector3d, Eigen::Vector3d > & bbox) const
Definition at line 464 of file reconstruction.cc.
References AddCamera(), AddImage(), AddPoint3D(), image, Image(), and RegisterImage().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::RunModelCropper(), and colmap::RunModelSplitter().
DeleteAllPoints2DAndPoints3D()
void colmap::Reconstruction::DeleteAllPoints2DAndPoints3D ()
Definition at line 305 of file reconstruction.cc.
References image, colmap::Image::SetCameraId(), colmap::Image::SetImageId(), colmap::Image::SetName(), colmap::Image::SetNumCorrespondences(), colmap::Image::SetQvec(), colmap::Image::SetQvecPrior(), colmap::Image::SetRegistered(), colmap::Image::SetTvec(), and colmap::Image::SetTvecPrior().
Referenced by colmap::mvs::Model::ReadFromCOLMAP(), and colmap::RunPointTriangulator().
DeleteObservation()
void colmap::Reconstruction::DeleteObservation (const image_t image_id, const point2D_t point2D_idx)
Definition at line 283 of file reconstruction.cc.
References colmap::Track::DeleteElement(), DeletePoint3D(), image, Image(), colmap::Track::Length(), Point3D(), and colmap::Point3D::Track().
Referenced by BOOST_AUTO_TEST_CASE(), DeRegisterImage(), and FilterObservationsWithNegativeDepth().
DeletePoint3D()
void colmap::Reconstruction::DeletePoint3D (const point3D_t point3D_id)
Definition at line 262 of file reconstruction.cc.
References colmap::Track::Elements(), image, Image(), Point3D(), and colmap::Point3D::Track().
Referenced by BOOST_AUTO_TEST_CASE(), DeleteObservation(), MergePoints3D(), and colmap::RunPointFiltering().
DeRegisterImage()
void colmap::Reconstruction::DeRegisterImage (const image_t image_id)
Definition at line 330 of file reconstruction.cc.
References DeleteObservation(), image, and Image().
Referenced by BOOST_AUTO_TEST_CASE(), FilterImages(), colmap::RunImageDeleter(), and colmap::RunImageFilterer().
ExistsCamera()
bool colmap::Reconstruction::ExistsCamera (const camera_t camera_id) const inline
Definition at line 517 of file reconstruction.h.
Referenced by AddCamera(), BOOST_AUTO_TEST_CASE(), colmap::CameraRig::Check(), Load(), and Merge().
ExistsImage()
bool colmap::Reconstruction::ExistsImage (const image_t image_id) const inline
Definition at line 521 of file reconstruction.h.
Referenced by AddImage(), BOOST_AUTO_TEST_CASE(), colmap::CameraRig::Check(), colmap::IncrementalTriangulator::CompleteImage(), FindCommonRegImageIds(), Load(), Merge(), colmap::IncrementalMapper::RegisterNextImage(), colmap::IncrementalTriangulator::Retriangulate(), colmap::RunImageDeleter(), and colmap::IncrementalTriangulator::TriangulateImage().
ExistsImagePair()
bool colmap::Reconstruction::ExistsImagePair (const image_pair_t pair_id) const inline
Definition at line 529 of file reconstruction.h.
ExistsPoint3D()
bool colmap::Reconstruction::ExistsPoint3D (const point3D_t point3D_id) const inline
Definition at line 525 of file reconstruction.h.
Referenced by AddPoint3D(), BOOST_AUTO_TEST_CASE(), and colmap::IncrementalTriangulator::GetModifiedPoints3D().
ExportBundler()
bool colmap::Reconstruction::ExportBundler (const std::string & path, const std::string & list_path, bool skip_distortion = false) const
Definition at line 1137 of file reconstruction.cc.
References Camera(), QtCompat::endl(), colmap::SimpleRadialCameraModel::extra_params_idxs, colmap::RadialCameraModel::extra_params_idxs, image, Image(), colmap::Camera::MeanFocalLength(), colmap::SimplePinholeCameraModel::model_id, colmap::PinholeCameraModel::model_id, colmap::SimpleRadialCameraModel::model_id, colmap::RadialCameraModel::model_id, colmap::Camera::ModelId(), colmap::Camera::Params(), cloudViewer::t::geometry::path, colmap::Camera::PrincipalPointX(), colmap::Camera::PrincipalPointY(), colmap::Point2D::X(), and colmap::Point2D::Y().
Referenced by colmap::RunModelConverter().
ExportCam()
bool colmap::Reconstruction::ExportCam (const std::string & path, bool skip_distortion = false) const
Definition at line 945 of file reconstruction.cc.
References Camera(), CreateImageDirs(), e, QtCompat::endl(), colmap::SimpleRadialCameraModel::extra_params_idxs, colmap::RadialCameraModel::extra_params_idxs, colmap::Camera::FocalLengthIdxs(), colmap::Camera::FocalLengthX(), colmap::Camera::FocalLengthY(), colmap::Camera::Height(), image, Image(), colmap::JoinPaths(), colmap::Camera::MeanFocalLength(), colmap::SimplePinholeCameraModel::model_id, colmap::PinholeCameraModel::model_id, colmap::SimpleRadialCameraModel::model_id, colmap::RadialCameraModel::model_id, colmap::Camera::ModelId(), name, colmap::Camera::Params(), cloudViewer::t::geometry::path, colmap::Camera::PrincipalPointX(), colmap::Camera::PrincipalPointY(), colmap::SplitFileExtension(), and colmap::Camera::Width().
Referenced by colmap::RunModelConverter().
ExportNVM()
bool colmap::Reconstruction::ExportNVM (const std::string & path, bool skip_distortion = false) const
Definition at line 855 of file reconstruction.cc.
References Camera(), QtCompat::endl(), colmap::SimpleRadialCameraModel::extra_params_idxs, image, Image(), colmap::Camera::MeanFocalLength(), colmap::SimplePinholeCameraModel::model_id, colmap::PinholeCameraModel::model_id, colmap::SimpleRadialCameraModel::model_id, colmap::Camera::ModelId(), colmap::Camera::Params(), cloudViewer::t::geometry::path, colmap::Point2D::X(), and colmap::Point2D::Y().
Referenced by colmap::RunModelConverter().
ExportPLY()
void colmap::Reconstruction::ExportPLY (const std::string & path) const
Definition at line 1236 of file reconstruction.cc.
References ConvertToPLY(), cloudViewer::t::geometry::path, and colmap::WriteBinaryPlyPoints().
Referenced by colmap::RunModelConverter(), and colmap::RunModelTransformer().
ExportRecon3D()
bool colmap::Reconstruction::ExportRecon3D (const std::string & path, bool skip_distortion = false) const
Definition at line 1019 of file reconstruction.cc.
References Camera(), colmap::CreateDirIfNotExists(), QtCompat::endl(), colmap::EnsureTrailingSlash(), colmap::SimpleRadialCameraModel::extra_params_idxs, colmap::RadialCameraModel::extra_params_idxs, colmap::Camera::Height(), image, Image(), colmap::Camera::MeanFocalLength(), colmap::SimplePinholeCameraModel::model_id, colmap::PinholeCameraModel::model_id, colmap::SimpleRadialCameraModel::model_id, colmap::RadialCameraModel::model_id, colmap::Camera::ModelId(), colmap::NormalizeQuaternion(), colmap::Camera::Params(), cloudViewer::t::geometry::path, colmap::Camera::PrincipalPointX(), colmap::Camera::PrincipalPointY(), colmap::QuaternionToRotationMatrix(), colmap::StringReplace(), colmap::Camera::Width(), colmap::Point2D::X(), and colmap::Point2D::Y().
Referenced by colmap::RunModelConverter().
ExportVRML()
void colmap::Reconstruction::ExportVRML (const std::string & images_path, const std::string & points3D_path, const double image_scale, const Eigen::Vector3d & image_rgb) const
Definition at line 1244 of file reconstruction.cc.
References QtCompat::endl(), image, and points.
Referenced by colmap::RunModelConverter().
ExtractColorsForAllImages()
void colmap::Reconstruction::ExtractColorsForAllImages (const std::string & path)
Definition at line 1391 of file reconstruction.cc.
References color, QtCompat::endl(), image, Image(), colmap::Bitmap::InterpolateBilinear(), colmap::JoinPaths(), cloudViewer::t::geometry::path, colmap::Bitmap::Read(), and colmap::StringPrintf().
Referenced by colmap::RunColorExtractor(), and colmap::RunPointTriangulator().
ExtractColorsForImage()
bool colmap::Reconstruction::ExtractColorsForImage (const image_t image_id, const std::string & path)
Definition at line 1361 of file reconstruction.cc.
References colmap::BitmapColor< T >::b, color, colmap::Point3D::Color(), colmap::BitmapColor< T >::g, image, Image(), colmap::Bitmap::InterpolateBilinear(), colmap::JoinPaths(), cloudViewer::t::geometry::path, Point3D(), colmap::BitmapColor< T >::r, colmap::Bitmap::Read(), and colmap::Point3D::SetColor().
FilterAllPoints3D()
size_t colmap::Reconstruction::FilterAllPoints3D (const double max_reproj_error, const double min_tri_angle)
Definition at line 670 of file reconstruction.cc.
References Point3DIds().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::IncrementalMapper::FilterPoints(), and colmap::RunPointFiltering().
FilterImages()
std::vector< image_t > colmap::Reconstruction::FilterImages (const double min_focal_length_ratio, const double max_focal_length_ratio, const double max_extra_param)
Definition at line 704 of file reconstruction.cc.
References Camera(), DeRegisterImage(), colmap::Camera::HasBogusParams(), image, Image(), and RegImageIds().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::IncrementalMapper::FilterImages(), and colmap::RunImageFilterer().
FilterObservationsWithNegativeDepth()
size_t colmap::Reconstruction::FilterObservationsWithNegativeDepth ()
Definition at line 684 of file reconstruction.cc.
References DeleteObservation(), colmap::Point2D::HasPoint3D(), colmap::HasPointPositiveDepth(), image, Image(), Point3D(), colmap::Point2D::Point3DId(), and colmap::Point3D::XYZ().
Referenced by colmap::IncrementalMapper::AdjustGlobalBundle(), BOOST_AUTO_TEST_CASE(), and colmap::RunPointTriangulator().
FilterPoints3D()
size_t colmap::Reconstruction::FilterPoints3D (const double max_reproj_error, const double min_tri_angle, const std::unordered_set< point3D_t > & point3D_ids)
Definition at line 642 of file reconstruction.cc.
Referenced by colmap::IncrementalMapper::AdjustLocalBundle(), BOOST_AUTO_TEST_CASE(), and FilterPoints3DInImages().
FilterPoints3DInImages()
size_t colmap::Reconstruction::FilterPoints3DInImages (const double max_reproj_error, const double min_tri_angle, const std::unordered_set< image_t > & image_ids)
Definition at line 654 of file reconstruction.cc.
References FilterPoints3D(), image, and Image().
Referenced by colmap::IncrementalMapper::AdjustLocalBundle(), and BOOST_AUTO_TEST_CASE().
FindCommonRegImageIds()
std::vector< image_t > colmap::Reconstruction::FindCommonRegImageIds (const Reconstruction & reconstruction) const
Definition at line 594 of file reconstruction.cc.
References ExistsImage(), Image(), IsImageRegistered(), and colmap::Image::Name().
Referenced by colmap::ComputeAlignmentBetweenReconstructions(), and colmap::RunModelComparer().
FindImageWithName()
const class Image * colmap::Reconstruction::FindImageWithName (const std::string & name) const
Definition at line 584 of file reconstruction.cc.
References image, and name.
Referenced by Align(), AlignRobust(), BOOST_AUTO_TEST_CASE(), colmap::RunImageDeleter(), colmap::RunImageUndistorter(), and colmap::RunModelAligner().
GetCorrespondenceGraph()
const CorrespondenceGraph * colmap::Reconstruction::GetCorrespondenceGraph () const inline
Definition at line 537 of file reconstruction.h.
Referenced by operator=().
HasCorrespondenceGraph()
bool colmap::Reconstruction::HasCorrespondenceGraph () const inline
Definition at line 541 of file reconstruction.h.
Image() [1/2]
class Image & colmap::Reconstruction::Image (const image_t image_id) inline
Definition at line 477 of file reconstruction.h.
Image() [2/2]
const class Image & colmap::Reconstruction::Image (const image_t image_id) const inline
Definition at line 454 of file reconstruction.h.
Referenced by AddObservation(), AddPoint3D(), colmap::IncrementalMapper::AdjustLocalBundle(), BOOST_AUTO_TEST_CASE(), colmap::CameraRig::Check(), colmap::IncrementalTriangulator::CompleteImage(), colmap::CameraRig::ComputeAbsolutePose(), colmap::ComputeAlignmentBetweenReconstructions(), ComputeNumObservations(), colmap::CameraRig::ComputeRelativePoses(), colmap::CameraRig::ComputeScale(), Crop(), DeleteObservation(), DeletePoint3D(), DeRegisterImage(), colmap::EstimateGravityVectorFromImageOrientation(), colmap::EstimateManhattanWorldFrame(), ExportBundler(), ExportCam(), ExportNVM(), ExportRecon3D(), ExtractColorsForAllImages(), ExtractColorsForImage(), FilterImages(), FilterObservationsWithNegativeDepth(), FilterPoints3DInImages(), FindCommonRegImageIds(), GenerateReconstruction(), IsImageRegistered(), Load(), Merge(), colmap::BundleAdjustmentConfig::NumResiduals(), colmap::mvs::Model::ReadFromCOLMAP(), RegisterImage(), colmap::IncrementalMapper::RegisterInitialImagePair(), colmap::IncrementalMapper::RegisterNextImage(), cloudViewer::ModelViewerWidget::ReloadReconstruction(), colmap::ModelViewerWidget::ReloadReconstruction(), colmap::IncrementalTriangulator::Retriangulate(), colmap::RunImageDeleter(), colmap::RunModelComparer(), colmap::RunPointTriangulator(), SetUp(), colmap::IncrementalTriangulator::TriangulateImage(), and colmap::UndistortReconstruction().
ImagePair() [1/4]
Reconstruction::ImagePairStat & colmap::Reconstruction::ImagePair (const image_pair_t pair_id) inline
Definition at line 485 of file reconstruction.h.
ImagePair() [2/4]
const Reconstruction::ImagePairStat & colmap::Reconstruction::ImagePair (const image_pair_t pair_id) const inline
Definition at line 462 of file reconstruction.h.
ImagePair() [3/4]
Reconstruction::ImagePairStat & colmap::Reconstruction::ImagePair (const image_t image_id1, const image_t image_id2) inline
Definition at line 490 of file reconstruction.h.
References colmap::Database::ImagePairToPairId().
ImagePair() [4/4]
const Reconstruction::ImagePairStat & colmap::Reconstruction::ImagePair (const image_t image_id1, const image_t image_id2) const inline
Definition at line 467 of file reconstruction.h.
References colmap::Database::ImagePairToPairId().
ImagePairs()
const std::unordered_map< image_pair_t, Reconstruction::ImagePairStat > & colmap::Reconstruction::ImagePairs () const inline
Definition at line 513 of file reconstruction.h.
Referenced by operator=(), and colmap::IncrementalTriangulator::Retriangulate().
Images()
const std::unordered_map< image_t, class Image > & colmap::Reconstruction::Images () const inline
Definition at line 500 of file reconstruction.h.
Referenced by colmap::AlignToPrincipalPlane(), BOOST_AUTO_TEST_CASE(), colmap::IncrementalMapper::FindNextImages(), operator=(), colmap::RunImageFilterer(), colmap::RunImageRegistrator(), and colmap::UndistortReconstruction().
ImportPLY() [1/2]
void colmap::Reconstruction::ImportPLY (const std::string & path)
Definition at line 831 of file reconstruction.cc.
References AddPoint3D(), cloudViewer::t::geometry::path, and colmap::ReadPly().
Referenced by colmap::RunModelTransformer(), and colmap::RunStereoFuser().
ImportPLY() [2/2]
void colmap::Reconstruction::ImportPLY (const std::vector< PlyPoint > & ply_points)
Definition at line 845 of file reconstruction.cc.
References AddPoint3D().
IsImageRegistered()
bool colmap::Reconstruction::IsImageRegistered (const image_t image_id) const inline
Definition at line 533 of file reconstruction.h.
References Image(), and colmap::Image::IsRegistered().
Referenced by Align(), AlignRobust(), BOOST_AUTO_TEST_CASE(), and FindCommonRegImageIds().
Load()
void colmap::Reconstruction::Load (const DatabaseCache & database_cache)
Definition at line 83 of file reconstruction.cc.
References AddCamera(), AddImage(), colmap::DatabaseCache::Cameras(), colmap::DatabaseCache::CorrespondenceGraph(), ExistsCamera(), ExistsImage(), image, Image(), colmap::DatabaseCache::Images(), colmap::Image::Name(), colmap::Reconstruction::ImagePairStat::num_total_corrs, colmap::DatabaseCache::NumCameras(), colmap::CorrespondenceGraph::NumCorrespondencesBetweenImages(), colmap::DatabaseCache::NumImages(), colmap::Image::NumPoints2D(), colmap::Image::SetNumCorrespondences(), colmap::Image::SetNumObservations(), and colmap::Image::SetPoints2D().
Referenced by colmap::IncrementalMapper::BeginReconstruction().
Merge()
bool colmap::Reconstruction::Merge (const Reconstruction & reconstruction, const double max_reproj_error)
Definition at line 493 of file reconstruction.cc.
References AddCamera(), colmap::Track::AddElement(), AddImage(), AddPoint3D(), Camera(), colmap::ComputeAlignmentBetweenReconstructions(), ExistsCamera(), ExistsImage(), image, Image(), colmap::Track::Length(), MergePoints3D(), NumRegImages(), colmap::Image::Point2D(), Point3DIds(), Points3D(), RegImageIds(), RegisterImage(), colmap::Image::ResetPoint3DForPoint2D(), colmap::Image::SetRegistered(), colmap::SimilarityTransform3::TransformPoint(), and colmap::SimilarityTransform3::TransformPose().
Referenced by colmap::RunModelMerger().
MergePoints3D()
point3D_t colmap::Reconstruction::MergePoints3D (const point3D_t point3D_id1, const point3D_t point3D_id2)
Definition at line 234 of file reconstruction.cc.
References colmap::Track::AddElements(), AddPoint3D(), colmap::Point3D::Color(), DeletePoint3D(), colmap::Track::Elements(), colmap::Track::Length(), Point3D(), colmap::Track::Reserve(), colmap::Point3D::Track(), and colmap::Point3D::XYZ().
Referenced by BOOST_AUTO_TEST_CASE(), and Merge().
Normalize()
void colmap::Reconstruction::Normalize (const double extent = 10.0, const double p0 = 0.1, const double p1 = 0.9, const bool use_images = true)
Definition at line 347 of file reconstruction.cc.
References colmap::ComposeIdentityQuaternion(), and Transform().
Referenced by colmap::IncrementalMapper::AdjustGlobalBundle(), and BOOST_AUTO_TEST_CASE().
NumAddedPoints3D()
size_t colmap::Reconstruction::NumAddedPoints3D () const inline
Definition at line 448 of file reconstruction.h.
Referenced by operator=().
NumCameras()
size_t colmap::Reconstruction::NumCameras () const inline
Definition at line 436 of file reconstruction.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::RunModelAnalyzer(), cloudViewer::ReconstructionStatsWidget::Show(), and colmap::ReconstructionStatsWidget::Show().
NumImagePairs()
size_t colmap::Reconstruction::NumImagePairs () const inline
Definition at line 444 of file reconstruction.h.
Referenced by BOOST_AUTO_TEST_CASE().
NumImages()
size_t colmap::Reconstruction::NumImages () const inline
Definition at line 438 of file reconstruction.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::RunImageTexturer(), colmap::RunImageUndistorter(), colmap::RunModelAnalyzer(), cloudViewer::ReconstructionStatsWidget::Show(), colmap::ReconstructionStatsWidget::Show(), and TranscribeImageIdsToDatabase().
NumPoints3D()
size_t colmap::Reconstruction::NumPoints3D () const inline
Definition at line 442 of file reconstruction.h.
Referenced by colmap::AlignToPrincipalPlane(), BOOST_AUTO_TEST_CASE(), colmap::mvs::Model::ReadFromCOLMAP(), colmap::RunImageTexturer(), colmap::RunImageUndistorter(), colmap::RunModelAnalyzer(), colmap::RunModelComparer(), colmap::RunModelMerger(), colmap::RunModelSplitter(), colmap::RunModelTransformer(), cloudViewer::ReconstructionStatsWidget::Show(), colmap::ReconstructionStatsWidget::Show(), cloudViewer::ReconstructionManagerWidget::Update(), and colmap::ReconstructionManagerWidget::Update().
NumRegImages()
size_t colmap::Reconstruction::NumRegImages () const inline
Definition at line 440 of file reconstruction.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::EstimateGravityVectorFromImageOrientation(), colmap::EstimateManhattanWorldFrame(), colmap::IncrementalMapper::FilterImages(), Merge(), colmap::mvs::Model::ReadFromCOLMAP(), colmap::IncrementalMapper::RegisterInitialImagePair(), colmap::IncrementalMapper::RegisterNextImage(), colmap::AutomaticReconstructionController::RunDenseMapper(), colmap::RunImageFilterer(), colmap::RunImageRegistrator(), colmap::RunModelAnalyzer(), colmap::RunModelComparer(), colmap::RunModelMerger(), colmap::RunModelSplitter(), colmap::RunPointTriangulator(), cloudViewer::ReconstructionStatsWidget::Show(), colmap::ReconstructionStatsWidget::Show(), cloudViewer::ReconstructionManagerWidget::Update(), and colmap::ReconstructionManagerWidget::Update().
operator=()
Reconstruction & colmap::Reconstruction::operator= (const Reconstruction & other)
Definition at line 59 of file reconstruction.cc.
References Cameras(), GetCorrespondenceGraph(), ImagePairs(), Images(), NumAddedPoints3D(), Points3D(), and RegImageIds().
Point3D() [1/2]
class Point3D & colmap::Reconstruction::Point3D (const point3D_t point3D_id) inline
Definition at line 481 of file reconstruction.h.
Point3D() [2/2]
const class Point3D & colmap::Reconstruction::Point3D (const point3D_t point3D_id) const inline
Definition at line 458 of file reconstruction.h.
Referenced by AddObservation(), colmap::IncrementalMapper::AdjustLocalBundle(), BOOST_AUTO_TEST_CASE(), DeleteObservation(), DeletePoint3D(), ExtractColorsForImage(), FilterObservationsWithNegativeDepth(), MergePoints3D(), colmap::BundleAdjustmentConfig::NumResiduals(), colmap::BundleAdjuster::ParameterizePoints(), colmap::IncrementalMapper::RegisterNextImage(), and colmap::RunPointFiltering().
Point3DIds()
std::unordered_set< point3D_t > colmap::Reconstruction::Point3DIds () const
Definition at line 72 of file reconstruction.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::IncrementalTriangulator::CompleteAllTracks(), FilterAllPoints3D(), Merge(), colmap::IncrementalTriangulator::MergeAllTracks(), and colmap::RunPointFiltering().
Points3D()
const std::unordered_map< point3D_t, Point3D > & colmap::Reconstruction::Points3D () const inline
Definition at line 508 of file reconstruction.h.
Referenced by colmap::AlignToPrincipalPlane(), BOOST_AUTO_TEST_CASE(), GenerateReconstruction(), Merge(), operator=(), colmap::mvs::Model::ReadFromCOLMAP(), cloudViewer::ModelViewerWidget::ReloadReconstruction(), and colmap::ModelViewerWidget::ReloadReconstruction().
Read()
void colmap::Reconstruction::Read (const std::string & path)
Definition at line 772 of file reconstruction.cc.
References colmap::ExistsFile(), colmap::JoinPaths(), cloudViewer::t::geometry::path, ReadBinary(), and ReadText().
Referenced by main(), colmap::mvs::Model::ReadFromCOLMAP(), colmap::RunBundleAdjuster(), colmap::RunColorExtractor(), colmap::RunImageDeleter(), colmap::RunImageFilterer(), colmap::RunImageRectifier(), colmap::RunImageRegistrator(), colmap::RunImageTexturer(), colmap::RunImageUndistorter(), colmap::RunModelAligner(), colmap::RunModelAnalyzer(), colmap::RunModelComparer(), colmap::RunModelConverter(), colmap::RunModelCropper(), colmap::RunModelMerger(), colmap::RunModelOrientationAligner(), colmap::RunModelSplitter(), colmap::RunModelTransformer(), colmap::RunPointFiltering(), colmap::RunPointTriangulator(), colmap::RunRigBundleAdjuster(), and colmap::RunStereoFuser().
ReadBinary()
void colmap::Reconstruction::ReadBinary (const std::string & path)
Definition at line 795 of file reconstruction.cc.
References colmap::JoinPaths(), and cloudViewer::t::geometry::path.
Referenced by Read().
ReadText()
void colmap::Reconstruction::ReadText (const std::string & path)
Definition at line 789 of file reconstruction.cc.
References colmap::JoinPaths(), and cloudViewer::t::geometry::path.
Referenced by Read().
RegImageIds()
const std::vector< image_t > & colmap::Reconstruction::RegImageIds () const inline
Definition at line 504 of file reconstruction.h.
Referenced by colmap::IncrementalMapper::AdjustGlobalBundle(), colmap::IncrementalMapper::BeginReconstruction(), colmap::IncrementalMapper::EndReconstruction(), colmap::EstimateGravityVectorFromImageOrientation(), colmap::EstimateManhattanWorldFrame(), FilterImages(), Merge(), operator=(), colmap::mvs::Model::ReadFromCOLMAP(), cloudViewer::ModelViewerWidget::ReloadReconstruction(), colmap::ModelViewerWidget::ReloadReconstruction(), colmap::RunPointTriangulator(), and colmap::RunRigBundleAdjuster().
RegisterImage()
void colmap::Reconstruction::RegisterImage (const image_t image_id)
Definition at line 322 of file reconstruction.cc.
References image, and Image().
Referenced by BOOST_AUTO_TEST_CASE(), Crop(), GenerateReconstruction(), Merge(), colmap::IncrementalMapper::RegisterInitialImagePair(), and colmap::IncrementalMapper::RegisterNextImage().
SetUp()
void colmap::Reconstruction::SetUp (const CorrespondenceGraph * correspondence_graph)
Definition at line 125 of file reconstruction.cc.
References Camera(), image, and Image().
Referenced by colmap::IncrementalMapper::BeginReconstruction(), and GenerateReconstruction().
TearDown()
void colmap::Reconstruction::TearDown ()
Definition at line 147 of file reconstruction.cc.
Referenced by colmap::IncrementalMapper::EndReconstruction(), and colmap::mvs::Model::ReadFromCOLMAP().
TranscribeImageIdsToDatabase()
void colmap::Reconstruction::TranscribeImageIdsToDatabase (const Database & database)
Definition at line 608 of file reconstruction.cc.
References colmap::Database::ExistsImageWithName(), image, NumImages(), and colmap::Database::ReadImageWithName().
Referenced by colmap::RunPointTriangulator().
Transform()
void colmap::Reconstruction::Transform (const SimilarityTransform3 & tform)
Definition at line 455 of file reconstruction.cc.
References image, colmap::SimilarityTransform3::TransformPoint(), and colmap::SimilarityTransform3::TransformPose().
Referenced by Align(), AlignRobust(), colmap::AlignToENUPlane(), colmap::AlignToPrincipalPlane(), BOOST_AUTO_TEST_CASE(), Normalize(), colmap::RunModelOrientationAligner(), and colmap::RunModelTransformer().
Write()
void colmap::Reconstruction::Write (const std::string & path) const
Definition at line 787 of file reconstruction.cc.
References cloudViewer::t::geometry::path, and WriteBinary().
Referenced by main(), colmap::RunBundleAdjuster(), colmap::RunColorExtractor(), colmap::RunImageDeleter(), colmap::RunImageFilterer(), colmap::RunImageRegistrator(), colmap::RunMapper(), colmap::RunModelAligner(), colmap::RunModelCropper(), colmap::RunModelMerger(), colmap::RunModelOrientationAligner(), colmap::RunModelSplitter(), colmap::RunModelTransformer(), colmap::RunPointFiltering(), colmap::RunPointTriangulator(), and colmap::RunRigBundleAdjuster().
WriteBinary()
void colmap::Reconstruction::WriteBinary (const std::string & path) const
Definition at line 807 of file reconstruction.cc.
References colmap::JoinPaths(), and cloudViewer::t::geometry::path.
Referenced by colmap::RunModelConverter(), colmap::RunStereoFuser(), and Write().
WriteText()
void colmap::Reconstruction::WriteText (const std::string & path) const
Definition at line 801 of file reconstruction.cc.
References colmap::JoinPaths(), and cloudViewer::t::geometry::path.
Referenced by colmap::RunModelConverter(), and colmap::RunStereoFuser().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/reconstruction.h
/root/ACloudViewer/libs/Reconstruction/src/base/reconstruction.cc