ACloudViewer: vtkCommandOptionsXMLParser Class Reference
vtkCommandOptionsXMLParser Class Reference
#include <vtkCommandOptionsXMLParser.h>
Public Member Functions
vtkTypeMacro (vtkCommandOptionsXMLParser, vtkXMLParser)
void PrintSelf (ostream &os, vtkIndent indent) override
void AddBooleanArgument (const char *longarg, int *var, int type=0)
void AddArgument (const char *longarg, int *var, int type=0)
void AddArgument (const char *longarg, char **var, int type=0)
void SetPVOptions (vtkCommandOptions *o)
Static Public Member Functions
static vtkCommandOptionsXMLParser * New ()
Protected Member Functions
vtkCommandOptionsXMLParser ()
~vtkCommandOptionsXMLParser () override
void StartElement (const char *name, const char **atts) override
void EndElement (const char *name) override
void HandleOption (const char **atts)
void HandleProcessType (const char **atts)
virtual void SetProcessType (const char *ptype)
void SetProcessTypeInt (int ptype)
Detailed Description
Definition at line 17 of file vtkCommandOptionsXMLParser.h.
Constructor & Destructor Documentation
vtkCommandOptionsXMLParser()
vtkCommandOptionsXMLParser::vtkCommandOptionsXMLParser () protected
Default constructor.
Definition at line 154 of file vtkCommandOptionsXMLParser.cxx.
~vtkCommandOptionsXMLParser()
vtkCommandOptionsXMLParser::~vtkCommandOptionsXMLParser () override protected
Destructor.
Definition at line 162 of file vtkCommandOptionsXMLParser.cxx.
Member Function Documentation
AddArgument() [1/2]
void vtkCommandOptionsXMLParser::AddArgument (const char * longarg, char ** var, int type = 0)
Definition at line 302 of file vtkCommandOptionsXMLParser.cxx.
References vtkCommandOptionsXMLParserArgumentStructure::CHAR_TYPE, and type.
AddArgument() [2/2]
void vtkCommandOptionsXMLParser::AddArgument (const char * longarg, int * var, int type = 0)
Definition at line 295 of file vtkCommandOptionsXMLParser.cxx.
References vtkCommandOptionsXMLParserArgumentStructure::INT_TYPE, and type.
Referenced by vtkCommandOptions::AddArgument().
AddBooleanArgument()
void vtkCommandOptionsXMLParser::AddBooleanArgument (const char * longarg, int * var, int type = 0)
Add arguments to the xml parser. These should be the long arguments from the vtkCommandOptions class of the form –foo, and pass in the variable that needs to be set with the value.
Definition at line 288 of file vtkCommandOptionsXMLParser.cxx.
References vtkCommandOptionsXMLParserArgumentStructure::BOOL_TYPE, and type.
Referenced by vtkCommandOptions::AddBooleanArgument().
EndElement()
void vtkCommandOptionsXMLParser::EndElement (const char * name) override protected
Definition at line 273 of file vtkCommandOptionsXMLParser.cxx.
References name.
HandleOption()
void vtkCommandOptionsXMLParser::HandleOption (const char ** atts) protected
Definition at line 225 of file vtkCommandOptionsXMLParser.cxx.
References name.
Referenced by StartElement().
HandleProcessType()
void vtkCommandOptionsXMLParser::HandleProcessType (const char ** atts) protected
Definition at line 208 of file vtkCommandOptionsXMLParser.cxx.
References SetProcessType().
Referenced by StartElement().
New()
static vtkCommandOptionsXMLParser* vtkCommandOptionsXMLParser::New () static
Referenced by vtkCommandOptions::vtkCommandOptions().
PrintSelf()
void vtkCommandOptionsXMLParser::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 309 of file vtkCommandOptionsXMLParser.cxx.
SetProcessType()
void vtkCommandOptionsXMLParser::SetProcessType (const char * ptype) protected virtual
Definition at line 63 of file vtkCommandOptionsXMLParser.cxx.
References vtkCommandOptions::EVERYBODY, and SetProcessTypeInt().
Referenced by HandleProcessType().
SetProcessTypeInt()
void vtkCommandOptionsXMLParser::SetProcessTypeInt (int ptype) protected
Definition at line 57 of file vtkCommandOptionsXMLParser.cxx.
Referenced by SetProcessType().
SetPVOptions()
void vtkCommandOptionsXMLParser::SetPVOptions (vtkCommandOptions * o) inline
Definition at line 32 of file vtkCommandOptionsXMLParser.h.
Referenced by vtkCommandOptions::vtkCommandOptions().
StartElement()
void vtkCommandOptionsXMLParser::StartElement (const char * name, const char ** atts) override protected
Definition at line 168 of file vtkCommandOptionsXMLParser.cxx.
References vtkCommandOptions::EVERYBODY, vtkCommandOptions::GetProcessType(), HandleOption(), HandleProcessType(), name, vtkCommandOptions::ParseExtraXMLTag(), and type.
vtkTypeMacro()
vtkCommandOptionsXMLParser::vtkTypeMacro (vtkCommandOptionsXMLParser , vtkXMLParser)
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkCommandOptionsXMLParser.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkCommandOptionsXMLParser.cxx