ACloudViewer: ccGriddedTools Class Reference
ccGriddedTools Class Reference
Tools dedicated to gridded clouds.
#include <ecvGriddedTools.h>
Classes
struct GridParameters
Grid (angular) parameters.
Static Public Member Functions
static bool DetectParameters (const ccPointCloud *cloud, const ccPointCloud::Grid::Shared grid, GridParameters &parameters, bool verbose=false, ccGLMatrix *cloudToSensorTrans=0)
Detects the given grid parameters (angular span, etc.)
static ccGBLSensor * ComputeBestSensor (ccPointCloud *cloud, ccPointCloud::Grid::Shared grid, ccGLMatrix *cloudToSensorTrans=0)
Detailed Description
Tools dedicated to gridded clouds.
Definition at line 17 of file ecvGriddedTools.h.
Member Function Documentation
ComputeBestSensor()
ccGBLSensor * ccGriddedTools::ComputeBestSensor (ccPointCloud * cloud, ccPointCloud::Grid::Shared grid, ccGLMatrix * cloudToSensorTrans = 0) static
Determines the (TLS) sensor parameters from the relative position of gridded points
Parameters
cloud cloud on which to compute the sensor parameters (should be a single grid)
grid scan grid
cloudToSensorTrans transformation from cloud coordinate system to the sensor coordinate system (optional)
Returns
sensor (if successful) or 0 otherwise
Definition at line 310 of file ecvGriddedTools.cpp.
References ccGriddedTools::GridParameters::deltaPhiRad, ccGriddedTools::GridParameters::deltaThetaRad, DetectParameters(), ccGriddedTools::GridParameters::maxPhi, ccGriddedTools::GridParameters::maxRange, ccGriddedTools::GridParameters::maxTheta, ccGriddedTools::GridParameters::minPhi, ccGriddedTools::GridParameters::minTheta, PC_ONE, ccObject::setEnabled(), ccSensor::setGraphicScale(), ccGBLSensor::setPitchRange(), ccGBLSensor::setPitchStep(), ccGBLSensor::setSensorRange(), ccDrawableObject::setVisible(), ccGBLSensor::setYawRange(), ccGBLSensor::setYawStep(), and ccGBLSensor::YAW_THEN_PITCH.
Referenced by PTXFilter::loadFile().
DetectParameters()
bool ccGriddedTools::DetectParameters (const ccPointCloud * cloud, const ccPointCloud::Grid::Shared grid, GridParameters & parameters, bool verbose = false, ccGLMatrix * cloudToSensorTrans = 0) static
Detects the given grid parameters (angular span, etc.)
Parameters
cloud associated cloud
grid scan grid
parameters output parameters
verbose whether the process should output some detailed information in the log/console or not
cloudToSensorTrans transformation from cloud coordinate system to the sensor coordinate system (optional)
Returns
success
Definition at line 19 of file ecvGriddedTools.cpp.
References ccGLMatrixTpl< T >::apply(), ccGriddedTools::GridParameters::deltaPhiRad, ccGriddedTools::GridParameters::deltaThetaRad, cloudViewer::PointCloudTpl< T >::getPoint(), M_PI, ccGriddedTools::GridParameters::maxPhi, ccGriddedTools::GridParameters::maxRange, ccGriddedTools::GridParameters::maxTheta, ccGriddedTools::GridParameters::minPhi, ccGriddedTools::GridParameters::minTheta, Vector3Tpl< Type >::norm(), CVLog::Print(), cloudViewer::RadiansToDegrees(), CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ComputeBestSensor().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CV_db/include/ecvGriddedTools.h
/root/ACloudViewer/libs/CV_db/src/ecvGriddedTools.cpp