ACloudViewer: EuclideanClusterSegmentation Class Reference
EuclideanClusterSegmentation Class Reference
SIFT keypoints extraction.
#include <EuclideanClusterSegmentation.h>
Public Member Functions
EuclideanClusterSegmentation ()
virtual ~EuclideanClusterSegmentation ()
virtual int compute ()
Performs the actual filter job.
Public Member Functions inherited from BasePclModule
BasePclModule (PclModuleDescription desc=PclModuleDescription(), ccPluginInterface *parent_plugin=0)
Default constructor.
QAction * getAction ()
Get the action associated with the button used in menu and toolbar creation.
QString getStatusTip () const
Returns the status tip.
QString getModuleName () const
Returns the name of the filter.
QString getEntryName () const
Returns the entry name.
QIcon getIcon () const
Returns the icon associated with the button.
void setShowProgressBar (bool status)
Sets whether to show a progressbar while computing or not.
std::vector< std::string > getSelectedAvailableScalarFields ()
ccPointCloud * getSelectedEntityAsCCPointCloud () const
Returns the first selected entity as a ccPointCloud.
ccHObject * getSelectedEntityAsCCHObject () const
Returns the first selected entity as a ccHObject.
ccHObject::Container getSelectedThatHaveMetaData (const QString key) const
Get selected object that also have the provided metadata key.
void getAllEntitiesOfType (CV_CLASS_ENUM type, ccHObject::Container &entities)
Returns all the objects in db tree of type "type".
void getAllEntitiesThatHaveMetaData (QString key, ccHObject::Container &entities)
void getSelectedEntitiesThatAreCCPointCloud (ccHObject::Container &entities)
get all entities that are selected and that also are cc_point_cloud
void getSelectedEntitiesThatAre (CV_CLASS_ENUM kind, ccHObject::Container &entities)
int hasSelectedRGB ()
Returns 1 if the first selected entity has RGB info.
int hasSelectedScalarField ()
Returns 1 if the first selected entity has at least one scalar field.
int hasSelectedScalarField (std::string field_name)
int isFirstSelectedCcPointCloud ()
Returns 1 if the first selected object is a ccPointCloud.
virtual void updateSelectedEntities (const ccHObject::Container &selectedEntities)
Updates the internal copy of selected entities.
void setMainAppInterface (ecvMainAppInterface *app)
Sets associated CC application interface (to access DB)
ecvMainAppInterface * getMainAppInterface ()
ccPluginInterface * getParentPlugin () const
Returns the associated parent plugin interface.
Protected Member Functions
virtual int checkSelected ()
Checks if current selection is compliant with the filter.
virtual int openInputDialog ()
virtual void getParametersFromDialog ()
Collects parameters from the filter dialog (if openDialog is successful)
virtual int checkParameters ()
virtual QString getErrorMessage (int errorCode)
Returns the error message corresponding to a given error code.
Protected Member Functions inherited from BasePclModule
virtual int openOutputDialog ()
virtual int start ()
Starts computation.
virtual void initAction ()
Initializes the corresponding action.
void throwError (int errCode)
Protected Attributes
EuclideanClusterDlg * m_dialog
int m_minClusterSize
int m_maxClusterSize
float m_clusterTolerance
bool m_randomClusterColor
Protected Attributes inherited from BasePclModule
QAction * m_action
Forces the Ui to be updated.
ccHObject::Container m_selected
Pointer to the main window.
PclModuleDescription m_desc
Associated dialog.
ecvMainAppInterface * m_app
Associated application interface.
ccPluginInterface * m_parent_plugin
associated parent plugin of the filter
bool m_show_progress
Do we want to show a progress bar when the filter works?
Additional Inherited Members
Signals inherited from BasePclModule
void entityHasChanged (ccHObject *)
Signal emitted when an entity is (visually) modified.
void newEntity (ccHObject *)
Signal emitted when a new entity is created by the filter.
void newErrorMessage (QString)
Signal emitted when a new error message is produced.
Protected Slots inherited from BasePclModule
int performAction ()
Returns is called when the dialog window is accepted.
Detailed Description
SIFT keypoints extraction.
Definition at line 18 of file EuclideanClusterSegmentation.h.
Constructor & Destructor Documentation
EuclideanClusterSegmentation()
EuclideanClusterSegmentation::EuclideanClusterSegmentation ()
Definition at line 30 of file EuclideanClusterSegmentation.cpp.
~EuclideanClusterSegmentation()
EuclideanClusterSegmentation::~EuclideanClusterSegmentation () virtual
Definition at line 43 of file EuclideanClusterSegmentation.cpp.
References m_dialog.
Member Function Documentation
checkParameters()
int EuclideanClusterSegmentation::checkParameters () protected virtual
Checks that the parameters retrieved by getParametersFromDialog are valid Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Returns
1 if parameters are valid (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 78 of file EuclideanClusterSegmentation.cpp.
References m_maxClusterSize, and m_minClusterSize.
checkSelected()
int EuclideanClusterSegmentation::checkSelected () protected virtual
Checks if current selection is compliant with the filter.
If not, an error is returned and computation stops. By default, baseclass method simply checks that selection is composed of one and only one ccPointCloud. This method should be overridden if necessary.
Returns
1 if selection is compliant (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 48 of file EuclideanClusterSegmentation.cpp.
References BasePclModule::isFirstSelectedCcPointCloud().
compute()
int EuclideanClusterSegmentation::compute () virtual
Performs the actual filter job.
This method MUST be re-implemented by derived filter
Returns
1 if successful (error code otherwise)
Implements BasePclModule.
Definition at line 85 of file EuclideanClusterSegmentation.cpp.
References ccHObject::addChild(), count, ecvMainAppInterface::dispToConsole(), ecvMainAppInterface::ERR_CONSOLE_MESSAGE, error(), ccHObject::getChildrenNumber(), ccObject::getName(), ccHObject::getParent(), BasePclModule::getSelectedEntityAsCCPointCloud(), BasePclModule::m_app, m_clusterTolerance, m_maxClusterSize, m_minClusterSize, m_randomClusterColor, BasePclModule::newEntity(), ccObject::setEnabled(), and ccObject::setName().
getErrorMessage()
QString EuclideanClusterSegmentation::getErrorMessage (int errorCode) protected virtual
Returns the error message corresponding to a given error code.
Each filter have a set of possible error message to be used given bt getFilterErrorMessage() Baseclass implementation provides some generic messages.
Note
These messages can be replaced by re-implementing this method and handling the same codes BEFORE calling the baseclass method
Reimplemented from BasePclModule.
Definition at line 154 of file EuclideanClusterSegmentation.cpp.
References BasePclModule::getErrorMessage().
getParametersFromDialog()
void EuclideanClusterSegmentation::getParametersFromDialog () protected virtual
Collects parameters from the filter dialog (if openDialog is successful)
Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Reimplemented from BasePclModule.
Definition at line 67 of file EuclideanClusterSegmentation.cpp.
References m_clusterTolerance, m_dialog, m_maxClusterSize, m_minClusterSize, and m_randomClusterColor.
openInputDialog()
int EuclideanClusterSegmentation::openInputDialog () protected virtual
Opens the input dialog window. Where the user can supply parameters for the computation Automatically called by performAction. Does nothing by default. Must be overridden if a dialog must be displayed.
Returns
1 if dialog has been successfully executed, 0 if canceled, negative error code otherwise
Reimplemented from BasePclModule.
Definition at line 56 of file EuclideanClusterSegmentation.cpp.
References ecvMainAppInterface::getActiveWindow(), BasePclModule::m_app, and m_dialog.
Member Data Documentation
m_clusterTolerance
float EuclideanClusterSegmentation::m_clusterTolerance protected
Definition at line 38 of file EuclideanClusterSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
m_dialog
EuclideanClusterDlg* EuclideanClusterSegmentation::m_dialog protected
Definition at line 34 of file EuclideanClusterSegmentation.h.
Referenced by getParametersFromDialog(), openInputDialog(), and ~EuclideanClusterSegmentation().
m_maxClusterSize
int EuclideanClusterSegmentation::m_maxClusterSize protected
Definition at line 37 of file EuclideanClusterSegmentation.h.
Referenced by checkParameters(), compute(), and getParametersFromDialog().
m_minClusterSize
int EuclideanClusterSegmentation::m_minClusterSize protected
Definition at line 36 of file EuclideanClusterSegmentation.h.
Referenced by checkParameters(), compute(), and getParametersFromDialog().
m_randomClusterColor
bool EuclideanClusterSegmentation::m_randomClusterColor protected
Definition at line 39 of file EuclideanClusterSegmentation.h.
Referenced by compute(), and getParametersFromDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Segmentations/EuclideanClusterSegmentation.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Segmentations/EuclideanClusterSegmentation.cpp