ACloudViewer: cloudViewer::visualization::rendering::Scene Class Reference
cloudViewer::visualization::rendering::Scene Class Reference abstract
#include <Scene.h>
Public Types
enum class GroundPlane { XZ , XY , YZ }
using Transform = Eigen::Transform< float, 3, Eigen::Affine >
Public Member Functions
Scene (Renderer &renderer)
virtual ~Scene ()=default
virtual Scene * Copy ()=0
virtual ViewHandle AddView (std::int32_t x, std::int32_t y, std::uint32_t w, std::uint32_t h)=0
virtual View * GetView (const ViewHandle &view_id) const =0
virtual void SetViewActive (const ViewHandle &view_id, bool is_active)=0
virtual void SetRenderOnce (const ViewHandle &view_id)=0
virtual void RemoveView (const ViewHandle &view_id)=0
virtual void AddCamera (const std::string &camera_name, std::shared_ptr< Camera > cam)=0
virtual void RemoveCamera (const std::string &camera_name)=0
virtual void SetActiveCamera (const std::string &camera_name)=0
virtual bool AddGeometry (const std::string &object_name, const ccHObject &geometry, const MaterialRecord &material, const std::string &downsampled_name="", size_t downsample_threshold=SIZE_MAX)=0
virtual bool AddGeometry (const std::string &object_name, const t::geometry::Geometry &geometry, const MaterialRecord &material, const std::string &downsampled_name="", size_t downsample_threshold=SIZE_MAX)=0
virtual bool AddGeometry (const std::string &object_name, const TriangleMeshModel &model)=0
virtual bool HasGeometry (const std::string &object_name) const =0
virtual void UpdateGeometry (const std::string &object_name, const t::geometry::PointCloud &point_cloud, uint32_t update_flags)=0
virtual void RemoveGeometry (const std::string &object_name)=0
virtual void ShowGeometry (const std::string &object_name, bool show)=0
virtual bool GeometryIsVisible (const std::string &object_name)=0
virtual void OverrideMaterial (const std::string &object_name, const MaterialRecord &material)=0
virtual void GeometryShadows (const std::string &object_name, bool cast_shadows, bool receive_shadows)=0
virtual void SetGeometryCulling (const std::string &object_name, bool enable)=0
virtual void SetGeometryPriority (const std::string &object_name, uint8_t priority)=0
virtual void QueryGeometry (std::vector< std::string > &geometry)=0
virtual void SetGeometryTransform (const std::string &object_name, const Transform &transform)=0
virtual Transform GetGeometryTransform (const std::string &object_name)=0
virtual ccBBox GetGeometryBoundingBox (const std::string &object_name)=0
virtual void OverrideMaterialAll (const MaterialRecord &material, bool shader_only=true)=0
virtual bool AddPointLight (const std::string &light_name, const Eigen::Vector3f &color, const Eigen::Vector3f &position, float intensity, float falloff, bool cast_shadows)=0
virtual bool AddSpotLight (const std::string &light_name, const Eigen::Vector3f &color, const Eigen::Vector3f &position, const Eigen::Vector3f &direction, float intensity, float falloff, float inner_cone_angle, float outer_cone_angle, bool cast_shadows)=0
virtual bool AddDirectionalLight (const std::string &light_name, const Eigen::Vector3f &color, const Eigen::Vector3f &direction, float intensity, bool cast_shadows)=0
virtual Light & GetLight (const std::string &light_name)=0
virtual void RemoveLight (const std::string &light_name)=0
virtual void UpdateLight (const std::string &light_name, const Light &light)=0
virtual void UpdateLightColor (const std::string &light_name, const Eigen::Vector3f &color)=0
virtual void UpdateLightPosition (const std::string &light_name, const Eigen::Vector3f &position)=0
virtual void UpdateLightDirection (const std::string &light_name, const Eigen::Vector3f &direction)=0
virtual void UpdateLightIntensity (const std::string &light_name, float intensity)=0
virtual void UpdateLightFalloff (const std::string &light_name, float falloff)=0
virtual void UpdateLightConeAngles (const std::string &light_name, float inner_cone_angle, float outer_cone_angle)=0
virtual void EnableLightShadow (const std::string &light_name, bool cast_shadows)=0
virtual void SetSunLight (const Eigen::Vector3f &direction, const Eigen::Vector3f &color, float intensity)=0
virtual void EnableSunLight (bool enable)=0
virtual void EnableSunLightShadows (bool enable)=0
virtual void SetSunLightColor (const Eigen::Vector3f &color)=0
virtual Eigen::Vector3f GetSunLightColor ()=0
virtual void SetSunLightIntensity (float intensity)=0
virtual float GetSunLightIntensity ()=0
virtual void SetSunLightDirection (const Eigen::Vector3f &direction)=0
virtual Eigen::Vector3f GetSunLightDirection ()=0
virtual void SetSunAngularRadius (float radius)=0
virtual void SetSunHaloSize (float size)=0
virtual void SetSunHaloFalloff (float falloff)=0
virtual bool SetIndirectLight (const std::string &ibl_name)=0
virtual const std::string & GetIndirectLight ()=0
virtual void EnableIndirectLight (bool enable)=0
virtual void SetIndirectLightIntensity (float intensity)=0
virtual float GetIndirectLightIntensity ()=0
virtual void SetIndirectLightRotation (const Transform &rotation)=0
virtual Transform GetIndirectLightRotation ()=0
virtual void ShowSkybox (bool show)=0
virtual bool GetSkyboxVisible () const =0
virtual void SetBackground (const Eigen::Vector4f &color, const std::shared_ptr< geometry::Image > image=nullptr)=0
virtual void SetBackground (TextureHandle image)=0
virtual void EnableGroundPlane (bool enable, GroundPlane plane)=0
virtual void SetGroundPlaneColor (const Eigen::Vector4f &color)=0
virtual void RenderToImage (std::function< void(std::shared_ptr< geometry::Image >)> callback)=0
Size of image is the size of the window.
virtual void RenderToDepthImage (std::function< void(std::shared_ptr< geometry::Image >)> callback)=0
Size of image is the size of the window.
Static Public Attributes
static const uint32_t kUpdatePointsFlag = (1 << 0)
static const uint32_t kUpdateNormalsFlag = (1 << 1)
static const uint32_t kUpdateColorsFlag = (1 << 2)
static const uint32_t kUpdateUv0Flag = (1 << 3)
Protected Attributes
Renderer & renderer_
Detailed Description
Definition at line 44 of file Scene.h.
Member Typedef Documentation
Transform
using cloudViewer::visualization::rendering::Scene::Transform = Eigen::Transform<float, 3, Eigen::Affine>
Definition at line 55 of file Scene.h.
Member Enumeration Documentation
GroundPlane
enum cloudViewer::visualization::rendering::Scene::GroundPlane strong
Enumerator
XZ
XY
YZ
Definition at line 187 of file Scene.h.
Constructor & Destructor Documentation
Scene()
cloudViewer::visualization::rendering::Scene::Scene (Renderer & renderer) inline
Definition at line 58 of file Scene.h.
~Scene()
virtual cloudViewer::visualization::rendering::Scene::~Scene () virtual default
Member Function Documentation
AddCamera()
virtual void cloudViewer::visualization::rendering::Scene::AddCamera (const std::string & camera_name, std::shared_ptr< Camera > cam) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
AddDirectionalLight()
virtual bool cloudViewer::visualization::rendering::Scene::AddDirectionalLight (const std::string & light_name, const Eigen::Vector3f & color, const Eigen::Vector3f & direction, float intensity, bool cast_shadows) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
AddGeometry() [1/3]
virtual bool cloudViewer::visualization::rendering::Scene::AddGeometry (const std::string & object_name, const ccHObject & geometry, const MaterialRecord & material, const std::string & downsampled_name = "", size_t downsample_threshold = SIZE_MAX) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes(), and cloudViewer::visualization::rendering::LightDirectionInteractorLogic::StartMouseDrag().
AddGeometry() [2/3]
virtual bool cloudViewer::visualization::rendering::Scene::AddGeometry (const std::string & object_name, const t::geometry::Geometry & geometry, const MaterialRecord & material, const std::string & downsampled_name = "", size_t downsample_threshold = SIZE_MAX) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
AddGeometry() [3/3]
virtual bool cloudViewer::visualization::rendering::Scene::AddGeometry (const std::string & object_name, const TriangleMeshModel & model) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
AddPointLight()
virtual bool cloudViewer::visualization::rendering::Scene::AddPointLight (const std::string & light_name, const Eigen::Vector3f & color, const Eigen::Vector3f & position, float intensity, float falloff, bool cast_shadows) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
AddSpotLight()
virtual bool cloudViewer::visualization::rendering::Scene::AddSpotLight (const std::string & light_name, const Eigen::Vector3f & color, const Eigen::Vector3f & position, const Eigen::Vector3f & direction, float intensity, float falloff, float inner_cone_angle, float outer_cone_angle, bool cast_shadows) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
AddView()
virtual ViewHandle cloudViewer::visualization::rendering::Scene::AddView (std::int32_t x, std::int32_t y, std::uint32_t w, std::uint32_t h) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Copy()
virtual Scene* cloudViewer::visualization::rendering::Scene::Copy () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
EnableGroundPlane()
virtual void cloudViewer::visualization::rendering::Scene::EnableGroundPlane (bool enable, GroundPlane plane) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::CloudViewerScene::ShowGroundPlane().
EnableIndirectLight()
virtual void cloudViewer::visualization::rendering::Scene::EnableIndirectLight (bool enable) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
EnableLightShadow()
virtual void cloudViewer::visualization::rendering::Scene::EnableLightShadow (const std::string & light_name, bool cast_shadows) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
EnableSunLight()
virtual void cloudViewer::visualization::rendering::Scene::EnableSunLight (bool enable) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
EnableSunLightShadows()
virtual void cloudViewer::visualization::rendering::Scene::EnableSunLightShadows (bool enable) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
GeometryIsVisible()
virtual bool cloudViewer::visualization::rendering::Scene::GeometryIsVisible (const std::string & object_name) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::CloudViewerScene::GeometryIsVisible(), cloudViewer::visualization::rendering::pybind_rendering_classes(), and cloudViewer::visualization::rendering::ModelInteractorLogic::StartMouseDrag().
GeometryShadows()
virtual void cloudViewer::visualization::rendering::Scene::GeometryShadows (const std::string & object_name, bool cast_shadows, bool receive_shadows) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes(), and cloudViewer::visualization::rendering::LightDirectionInteractorLogic::StartMouseDrag().
GetGeometryBoundingBox()
virtual ccBBox cloudViewer::visualization::rendering::Scene::GetGeometryBoundingBox (const std::string & object_name) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::CloudViewerScene::AddGeometry().
GetGeometryTransform()
virtual Transform cloudViewer::visualization::rendering::Scene::GetGeometryTransform (const std::string & object_name) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::ModelInteractorLogic::Dolly(), and cloudViewer::visualization::rendering::CloudViewerScene::GetGeometryTransform().
GetIndirectLight()
virtual const std::string& cloudViewer::visualization::rendering::Scene::GetIndirectLight () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
GetIndirectLightIntensity()
virtual float cloudViewer::visualization::rendering::Scene::GetIndirectLightIntensity () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
GetIndirectLightRotation()
virtual Transform cloudViewer::visualization::rendering::Scene::GetIndirectLightRotation () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::IBLRotationInteractorLogic::StartMouseDrag().
GetLight()
virtual Light& cloudViewer::visualization::rendering::Scene::GetLight (const std::string & light_name) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
GetSkyboxVisible()
virtual bool cloudViewer::visualization::rendering::Scene::GetSkyboxVisible () const pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::IBLRotationInteractorLogic::StartMouseDrag().
GetSunLightColor()
virtual Eigen::Vector3f cloudViewer::visualization::rendering::Scene::GetSunLightColor () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
GetSunLightDirection()
virtual Eigen::Vector3f cloudViewer::visualization::rendering::Scene::GetSunLightDirection () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::LightDirectionInteractorLogic::StartMouseDrag().
GetSunLightIntensity()
virtual float cloudViewer::visualization::rendering::Scene::GetSunLightIntensity () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
GetView()
virtual View* cloudViewer::visualization::rendering::Scene::GetView (const ViewHandle & view_id) const pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::CloudViewerScene::GetCamera(), and cloudViewer::visualization::rendering::CloudViewerScene::GetView().
HasGeometry()
virtual bool cloudViewer::visualization::rendering::Scene::HasGeometry (const std::string & object_name) const pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::CloudViewerScene::HasGeometry(), and cloudViewer::visualization::rendering::pybind_rendering_classes().
OverrideMaterial()
virtual void cloudViewer::visualization::rendering::Scene::OverrideMaterial (const std::string & object_name, const MaterialRecord & material) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::CloudViewerScene::ModifyGeometryMaterial(), and cloudViewer::visualization::rendering::CloudViewerScene::UpdateMaterial().
OverrideMaterialAll()
virtual void cloudViewer::visualization::rendering::Scene::OverrideMaterialAll (const MaterialRecord & material, bool shader_only = true) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
QueryGeometry()
virtual void cloudViewer::visualization::rendering::Scene::QueryGeometry (std::vector< std::string > & geometry) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
RemoveCamera()
virtual void cloudViewer::visualization::rendering::Scene::RemoveCamera (const std::string & camera_name) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
RemoveGeometry()
virtual void cloudViewer::visualization::rendering::Scene::RemoveGeometry (const std::string & object_name) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::CloudViewerScene::ClearGeometry(), cloudViewer::visualization::rendering::pybind_rendering_classes(), cloudViewer::visualization::rendering::CloudViewerScene::UpdateModelMaterial(), and cloudViewer::visualization::rendering::CloudViewerScene::~CloudViewerScene().
RemoveLight()
virtual void cloudViewer::visualization::rendering::Scene::RemoveLight (const std::string & light_name) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
RemoveView()
virtual void cloudViewer::visualization::rendering::Scene::RemoveView (const ViewHandle & view_id) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
RenderToDepthImage()
virtual void cloudViewer::visualization::rendering::Scene::RenderToDepthImage (std::function< void(std::shared_ptr< geometry::Image >)> callback) pure virtual
Size of image is the size of the window.
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
RenderToImage()
virtual void cloudViewer::visualization::rendering::Scene::RenderToImage (std::function< void(std::shared_ptr< geometry::Image >)> callback) pure virtual
Size of image is the size of the window.
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
SetActiveCamera()
virtual void cloudViewer::visualization::rendering::Scene::SetActiveCamera (const std::string & camera_name) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
SetBackground() [1/2]
virtual void cloudViewer::visualization::rendering::Scene::SetBackground (const Eigen::Vector4f & color, const std::shared_ptr< geometry::Image > image = nullptr) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::CloudViewerScene::SetBackground().
SetBackground() [2/2]
virtual void cloudViewer::visualization::rendering::Scene::SetBackground (TextureHandle image) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
SetGeometryCulling()
virtual void cloudViewer::visualization::rendering::Scene::SetGeometryCulling (const std::string & object_name, bool enable) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
SetGeometryPriority()
virtual void cloudViewer::visualization::rendering::Scene::SetGeometryPriority (const std::string & object_name, uint8_t priority) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
SetGeometryTransform()
virtual void cloudViewer::visualization::rendering::Scene::SetGeometryTransform (const std::string & object_name, const Transform & transform) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::ModelInteractorLogic::Dolly(), cloudViewer::visualization::rendering::ModelInteractorLogic::Pan(), cloudViewer::visualization::rendering::ModelInteractorLogic::Rotate(), cloudViewer::visualization::rendering::ModelInteractorLogic::RotateZ(), cloudViewer::visualization::rendering::LightDirectionInteractorLogic::StartMouseDrag(), and cloudViewer::visualization::rendering::LightDirectionInteractorLogic::UpdateMouseDragUI().
SetGroundPlaneColor()
virtual void cloudViewer::visualization::rendering::Scene::SetGroundPlaneColor (const Eigen::Vector4f & color) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
SetIndirectLight()
virtual bool cloudViewer::visualization::rendering::Scene::SetIndirectLight (const std::string & ibl_name) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
SetIndirectLightIntensity()
virtual void cloudViewer::visualization::rendering::Scene::SetIndirectLightIntensity (float intensity) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
SetIndirectLightRotation()
virtual void cloudViewer::visualization::rendering::Scene::SetIndirectLightRotation (const Transform & rotation) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::IBLRotationInteractorLogic::Rotate(), and cloudViewer::visualization::rendering::IBLRotationInteractorLogic::RotateZ().
SetRenderOnce()
virtual void cloudViewer::visualization::rendering::Scene::SetRenderOnce (const ViewHandle & view_id) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
SetSunAngularRadius()
virtual void cloudViewer::visualization::rendering::Scene::SetSunAngularRadius (float radius) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
SetSunHaloFalloff()
virtual void cloudViewer::visualization::rendering::Scene::SetSunHaloFalloff (float falloff) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
SetSunHaloSize()
virtual void cloudViewer::visualization::rendering::Scene::SetSunHaloSize (float size) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
SetSunLight()
virtual void cloudViewer::visualization::rendering::Scene::SetSunLight (const Eigen::Vector3f & direction, const Eigen::Vector3f & color, float intensity) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
SetSunLightColor()
virtual void cloudViewer::visualization::rendering::Scene::SetSunLightColor (const Eigen::Vector3f & color) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
SetSunLightDirection()
virtual void cloudViewer::visualization::rendering::Scene::SetSunLightDirection (const Eigen::Vector3f & direction) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
SetSunLightIntensity()
virtual void cloudViewer::visualization::rendering::Scene::SetSunLightIntensity (float intensity) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
SetViewActive()
virtual void cloudViewer::visualization::rendering::Scene::SetViewActive (const ViewHandle & view_id, bool is_active) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
ShowGeometry()
virtual void cloudViewer::visualization::rendering::Scene::ShowGeometry (const std::string & object_name, bool show) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::ModelInteractorLogic::EndMouseDrag(), cloudViewer::visualization::rendering::pybind_rendering_classes(), and cloudViewer::visualization::rendering::ModelInteractorLogic::StartMouseDrag().
ShowSkybox()
virtual void cloudViewer::visualization::rendering::Scene::ShowSkybox (bool show) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::IBLRotationInteractorLogic::EndMouseDrag(), cloudViewer::visualization::rendering::CloudViewerScene::ShowSkybox(), and cloudViewer::visualization::rendering::IBLRotationInteractorLogic::StartMouseDrag().
UpdateGeometry()
virtual void cloudViewer::visualization::rendering::Scene::UpdateGeometry (const std::string & object_name, const t::geometry::PointCloud & point_cloud, uint32_t update_flags) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
UpdateLight()
virtual void cloudViewer::visualization::rendering::Scene::UpdateLight (const std::string & light_name, const Light & light) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
UpdateLightColor()
virtual void cloudViewer::visualization::rendering::Scene::UpdateLightColor (const std::string & light_name, const Eigen::Vector3f & color) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
UpdateLightConeAngles()
virtual void cloudViewer::visualization::rendering::Scene::UpdateLightConeAngles (const std::string & light_name, float inner_cone_angle, float outer_cone_angle) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
UpdateLightDirection()
virtual void cloudViewer::visualization::rendering::Scene::UpdateLightDirection (const std::string & light_name, const Eigen::Vector3f & direction) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
UpdateLightFalloff()
virtual void cloudViewer::visualization::rendering::Scene::UpdateLightFalloff (const std::string & light_name, float falloff) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
UpdateLightIntensity()
virtual void cloudViewer::visualization::rendering::Scene::UpdateLightIntensity (const std::string & light_name, float intensity) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
UpdateLightPosition()
virtual void cloudViewer::visualization::rendering::Scene::UpdateLightPosition (const std::string & light_name, const Eigen::Vector3f & position) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentScene.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
Member Data Documentation
kUpdateColorsFlag
const uint32_t cloudViewer::visualization::rendering::Scene::kUpdateColorsFlag = (1 << 2) static
Definition at line 48 of file Scene.h.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes(), and cloudViewer::visualization::rendering::FilamentScene::UpdateGeometry().
kUpdateNormalsFlag
const uint32_t cloudViewer::visualization::rendering::Scene::kUpdateNormalsFlag = (1 << 1) static
Definition at line 47 of file Scene.h.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes(), and cloudViewer::visualization::rendering::FilamentScene::UpdateGeometry().
kUpdatePointsFlag
const uint32_t cloudViewer::visualization::rendering::Scene::kUpdatePointsFlag = (1 << 0) static
Definition at line 46 of file Scene.h.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes(), and cloudViewer::visualization::rendering::FilamentScene::UpdateGeometry().
kUpdateUv0Flag
const uint32_t cloudViewer::visualization::rendering::Scene::kUpdateUv0Flag = (1 << 3) static
Definition at line 49 of file Scene.h.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes(), and cloudViewer::visualization::rendering::FilamentScene::UpdateGeometry().
renderer_
Renderer& cloudViewer::visualization::rendering::Scene::renderer_ protected
Definition at line 200 of file Scene.h.
Referenced by cloudViewer::visualization::rendering::FilamentScene::Copy(), cloudViewer::visualization::rendering::FilamentScene::RenderToDepthImage(), cloudViewer::visualization::rendering::FilamentScene::RenderToImage(), cloudViewer::visualization::rendering::FilamentScene::SetBackground(), and cloudViewer::visualization::rendering::FilamentScene::SetIndirectLight().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/Scene.h