ACloudViewer: ccDisplayOptionsDlg Class Reference
ccDisplayOptionsDlg Class Reference
Dialog to setup display settings.
#include <ecvDisplayOptionsDlg.h>
Public Slots
void changeBackgroundColor ()
Signals
void aspectHasChanged ()
Public Member Functions
ccDisplayOptionsDlg (QWidget *parent)
~ccDisplayOptionsDlg () override
Protected Slots
void changeLightDiffuseColor ()
void changeLightAmbientColor ()
void changeLightSpecularColor ()
void changeMeshFrontDiffuseColor ()
void changeMeshBackDiffuseColor ()
void changeMeshSpecularColor ()
void changePointsColor ()
void changeTextColor ()
void changeLabelBackgroundColor ()
void changeLabelMarkerColor ()
void changeMaxMeshSize (double)
void changeMaxCloudSize (double)
void changeVBOUsage ()
void changeColorScaleRampWidth (int)
void changeBBColor ()
void changeDefaultFontSize (int)
void changeLabelFontSize (int)
void changeNumberPrecision (int)
void changeLabelOpacity (int)
void changeLabelMarkerSize (int)
void changeBBOpacity (double)
void changeBBLineWidth (int)
void changeZoomSpeed (double)
void changeAutoComputeOctreeOption (int)
void changeAppStyle (int)
void changeLogVerbosityLevel (int)
void doAccept ()
void doReject ()
void apply ()
void reset ()
Protected Member Functions
void refresh ()
Refreshes dialog to reflect new parameters values.
Protected Attributes
QColor lightDiffuseColor
QColor lightAmbientColor
QColor lightSpecularColor
QColor meshFrontDiff
QColor meshBackDiff
QColor meshSpecularColor
QColor pointsDefaultCol
QColor textDefaultCol
QColor backgroundCol
QColor labelBackgroundCol
QColor labelMarkerCol
QColor bbDefaultCol
ecvGui::ParamStruct parameters
Current GUI parameters.
ecvOptions options
Current options.
ecvGui::ParamStruct oldParameters
Old parameters (for restore)
ecvOptions oldOptions
Old options (for restore)
int m_defaultAppStyleIndex
Default application style index (for reset)
Detailed Description
Dialog to setup display settings.
Definition at line 31 of file ecvDisplayOptionsDlg.h.
Constructor & Destructor Documentation
ccDisplayOptionsDlg()
ccDisplayOptionsDlg::ccDisplayOptionsDlg (QWidget * parent) explicit
Definition at line 41 of file ecvDisplayOptionsDlg.cpp.
References apply(), changeAppStyle(), changeAutoComputeOctreeOption(), changeBackgroundColor(), changeBBColor(), changeBBLineWidth(), changeBBOpacity(), changeColorScaleRampWidth(), changeDefaultFontSize(), changeLabelBackgroundColor(), changeLabelFontSize(), changeLabelMarkerColor(), changeLabelMarkerSize(), changeLabelOpacity(), changeLightAmbientColor(), changeLightDiffuseColor(), changeLightSpecularColor(), changeLogVerbosityLevel(), changeMaxCloudSize(), changeMaxMeshSize(), changeMeshBackDiffuseColor(), changeMeshFrontDiffuseColor(), changeMeshSpecularColor(), changeNumberPrecision(), changePointsColor(), changeTextColor(), changeVBOUsage(), changeZoomSpeed(), doAccept(), doReject(), ecvOptions::Instance(), oldOptions, oldParameters, options, ecvGui::Parameters(), parameters, refresh(), and reset().
~ccDisplayOptionsDlg()
ccDisplayOptionsDlg::~ccDisplayOptionsDlg () override
Definition at line 176 of file ecvDisplayOptionsDlg.cpp.
Member Function Documentation
apply
void ccDisplayOptionsDlg::apply () protected slot
Definition at line 521 of file ecvDisplayOptionsDlg.cpp.
References aspectHasChanged(), ecvApp, ccHObject::filterChildren(), ecvDisplayTools::GetSceneDB(), ecvOptions::logVerbosityLevel, CV_TYPES::OBJECT, options, parameters, CVLog::Print(), ecvOptions::Set(), ecvGui::Set(), CVLog::SetVerbosityLevel(), and CVLog::VerbosityLevel().
Referenced by ccDisplayOptionsDlg(), and doAccept().
aspectHasChanged
void ccDisplayOptionsDlg::aspectHasChanged () signal
Referenced by apply(), and doReject().
changeAppStyle
void ccDisplayOptionsDlg::changeAppStyle (int index) protected slot
Definition at line 556 of file ecvDisplayOptionsDlg.cpp.
Referenced by ccDisplayOptionsDlg().
changeAutoComputeOctreeOption
void ccDisplayOptionsDlg::changeAutoComputeOctreeOption (int index) protected slot
Definition at line 450 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::autoComputeOctree, and parameters.
Referenced by ccDisplayOptionsDlg().
changeBackgroundColor
void ccDisplayOptionsDlg::changeBackgroundColor () slot
Definition at line 376 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::backgroundCol, backgroundCol, ecvColor::FromQColor(), parameters, and ccQtHelpers::SetButtonColor().
Referenced by ccDisplayOptionsDlg().
changeBBColor
void ccDisplayOptionsDlg::changeBBColor () protected slot
Definition at line 354 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::bbDefaultCol, bbDefaultCol, ecvColor::FromQColor(), parameters, and ccQtHelpers::SetButtonColor().
Referenced by ccDisplayOptionsDlg().
changeBBLineWidth
void ccDisplayOptionsDlg::changeBBLineWidth (int val) protected slot
Definition at line 472 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::bbLineWidth, and parameters.
Referenced by ccDisplayOptionsDlg().
changeBBOpacity
void ccDisplayOptionsDlg::changeBBOpacity (double val) protected slot
Definition at line 467 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::bbOpacity, and parameters.
Referenced by ccDisplayOptionsDlg().
changeColorScaleRampWidth
void ccDisplayOptionsDlg::changeColorScaleRampWidth (int val) protected slot
Definition at line 426 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::colorScaleRampWidth, and parameters.
Referenced by ccDisplayOptionsDlg().
changeDefaultFontSize
void ccDisplayOptionsDlg::changeDefaultFontSize (int val) protected slot
Definition at line 431 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::defaultFontSize, and parameters.
Referenced by ccDisplayOptionsDlg().
changeLabelBackgroundColor
void ccDisplayOptionsDlg::changeLabelBackgroundColor () protected slot
Definition at line 387 of file ecvDisplayOptionsDlg.cpp.
References ecvColor::FromQColor(), ecvGui::ParamStruct::labelBackgroundCol, labelBackgroundCol, parameters, and ccQtHelpers::SetButtonColor().
Referenced by ccDisplayOptionsDlg().
changeLabelFontSize
void ccDisplayOptionsDlg::changeLabelFontSize (int val) protected slot
Definition at line 436 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::labelFontSize, and parameters.
Referenced by ccDisplayOptionsDlg().
changeLabelMarkerColor
void ccDisplayOptionsDlg::changeLabelMarkerColor () protected slot
Definition at line 398 of file ecvDisplayOptionsDlg.cpp.
References ecvColor::FromQColor(), ecvGui::ParamStruct::labelMarkerCol, labelMarkerCol, parameters, and ccQtHelpers::SetButtonColor().
Referenced by ccDisplayOptionsDlg().
changeLabelMarkerSize
void ccDisplayOptionsDlg::changeLabelMarkerSize (int val) protected slot
Definition at line 461 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::labelMarkerSize, and parameters.
Referenced by ccDisplayOptionsDlg().
changeLabelOpacity
void ccDisplayOptionsDlg::changeLabelOpacity (int val) protected slot
Definition at line 456 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::labelOpacity, and parameters.
Referenced by ccDisplayOptionsDlg().
changeLightAmbientColor
void ccDisplayOptionsDlg::changeLightAmbientColor () protected slot
Definition at line 286 of file ecvDisplayOptionsDlg.cpp.
References ecvColor::FromQColoraf(), ecvGui::ParamStruct::lightAmbientColor, lightAmbientColor, parameters, and ccQtHelpers::SetButtonColor().
Referenced by ccDisplayOptionsDlg().
changeLightDiffuseColor
void ccDisplayOptionsDlg::changeLightDiffuseColor () protected slot
Definition at line 277 of file ecvDisplayOptionsDlg.cpp.
References ecvColor::FromQColoraf(), ecvGui::ParamStruct::lightDiffuseColor, lightDiffuseColor, parameters, and ccQtHelpers::SetButtonColor().
Referenced by ccDisplayOptionsDlg().
changeLightSpecularColor
void ccDisplayOptionsDlg::changeLightSpecularColor () protected slot
Definition at line 297 of file ecvDisplayOptionsDlg.cpp.
References ecvColor::FromQColoraf(), ecvGui::ParamStruct::lightSpecularColor, lightSpecularColor, parameters, and ccQtHelpers::SetButtonColor().
Referenced by ccDisplayOptionsDlg().
changeLogVerbosityLevel
void ccDisplayOptionsDlg::changeLogVerbosityLevel (int index) protected slot
Definition at line 561 of file ecvDisplayOptionsDlg.cpp.
References CVLog::LOG_ERROR, ecvOptions::logVerbosityLevel, and options.
Referenced by ccDisplayOptionsDlg().
changeMaxCloudSize
void ccDisplayOptionsDlg::changeMaxCloudSize (double val) protected slot
Definition at line 414 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::minLoDCloudSize, and parameters.
Referenced by ccDisplayOptionsDlg().
changeMaxMeshSize
void ccDisplayOptionsDlg::changeMaxMeshSize (double val) protected slot
Definition at line 410 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::minLoDMeshSize, and parameters.
Referenced by ccDisplayOptionsDlg().
changeMeshBackDiffuseColor
void ccDisplayOptionsDlg::changeMeshBackDiffuseColor () protected slot
Definition at line 320 of file ecvDisplayOptionsDlg.cpp.
References ecvColor::FromQColoraf(), ecvGui::ParamStruct::meshBackDiff, meshBackDiff, parameters, and ccQtHelpers::SetButtonColor().
Referenced by ccDisplayOptionsDlg().
changeMeshFrontDiffuseColor
void ccDisplayOptionsDlg::changeMeshFrontDiffuseColor () protected slot
Definition at line 308 of file ecvDisplayOptionsDlg.cpp.
References ecvColor::FromQColoraf(), ecvGui::ParamStruct::meshFrontDiff, meshFrontDiff, parameters, and ccQtHelpers::SetButtonColor().
Referenced by ccDisplayOptionsDlg().
changeMeshSpecularColor
void ccDisplayOptionsDlg::changeMeshSpecularColor () protected slot
Definition at line 331 of file ecvDisplayOptionsDlg.cpp.
References ecvColor::FromQColoraf(), ecvGui::ParamStruct::meshSpecular, meshSpecularColor, parameters, and ccQtHelpers::SetButtonColor().
Referenced by ccDisplayOptionsDlg().
changeNumberPrecision
void ccDisplayOptionsDlg::changeNumberPrecision (int val) protected slot
Definition at line 441 of file ecvDisplayOptionsDlg.cpp.
References ecvGui::ParamStruct::displayedNumPrecision, and parameters.
Referenced by ccDisplayOptionsDlg().
changePointsColor
void ccDisplayOptionsDlg::changePointsColor () protected slot
Definition at line 343 of file ecvDisplayOptionsDlg.cpp.
References ecvColor::FromQColor(), parameters, ecvGui::ParamStruct::pointsDefaultCol, pointsDefaultCol, and ccQtHelpers::SetButtonColor().
Referenced by ccDisplayOptionsDlg().
changeTextColor
void ccDisplayOptionsDlg::changeTextColor () protected slot
Definition at line 365 of file ecvDisplayOptionsDlg.cpp.
References ecvColor::FromQColor(), parameters, ccQtHelpers::SetButtonColor(), ecvGui::ParamStruct::textDefaultCol, and textDefaultCol.
Referenced by ccDisplayOptionsDlg().
changeVBOUsage
void ccDisplayOptionsDlg::changeVBOUsage () protected slot
Definition at line 418 of file ecvDisplayOptionsDlg.cpp.
References parameters, s_defaultMaxVBOCloudSizeM, and ecvGui::ParamStruct::useVBOs.
Referenced by ccDisplayOptionsDlg().
changeZoomSpeed
void ccDisplayOptionsDlg::changeZoomSpeed (double val) protected slot
Definition at line 446 of file ecvDisplayOptionsDlg.cpp.
References parameters, and ecvGui::ParamStruct::zoomSpeed.
Referenced by ccDisplayOptionsDlg().
doAccept
void ccDisplayOptionsDlg::doAccept () protected slot
Definition at line 625 of file ecvDisplayOptionsDlg.cpp.
References apply(), options, parameters, ecvGui::ParamStruct::toPersistentSettings(), and ecvOptions::toPersistentSettings().
Referenced by ccDisplayOptionsDlg().
doReject
void ccDisplayOptionsDlg::doReject () protected slot
Definition at line 477 of file ecvDisplayOptionsDlg.cpp.
References aspectHasChanged(), ecvApp, ccHObject::filterChildren(), ecvDisplayTools::GetSceneDB(), m_defaultAppStyleIndex, CV_TYPES::OBJECT, oldOptions, oldParameters, ecvOptions::Set(), and ecvGui::Set().
Referenced by ccDisplayOptionsDlg().
refresh()
void ccDisplayOptionsDlg::refresh () protected
Refreshes dialog to reflect new parameters values.
Definition at line 181 of file ecvDisplayOptionsDlg.cpp.
References ecvColor::RgbaTpl< Type >::a, ecvOptions::askForConfirmationBeforeQuitting, ecvGui::ParamStruct::autoComputeOctree, ecvColor::RgbTpl< Type >::b, ecvColor::RgbaTpl< Type >::b, ecvGui::ParamStruct::backgroundCol, backgroundCol, ecvGui::ParamStruct::bbDefaultCol, bbDefaultCol, ecvGui::ParamStruct::bbLineWidth, ecvGui::ParamStruct::bbOpacity, ecvGui::ParamStruct::colorScaleRampWidth, ecvGui::ParamStruct::colorScaleShaderSupported, ecvGui::ParamStruct::colorScaleShowHistogram, ecvGui::ParamStruct::colorScaleUseShader, ecvGui::ParamStruct::decimateCloudOnMove, ecvGui::ParamStruct::decimateMeshOnMove, ecvGui::ParamStruct::defaultFontSize, ecvGui::ParamStruct::displayCross, ecvGui::ParamStruct::displayedNumPrecision, ecvGui::ParamStruct::drawBackgroundGradient, ecvGui::ParamStruct::drawRoundedPoints, ecvColor::RgbTpl< Type >::g, ecvColor::RgbaTpl< Type >::g, ecvGui::ParamStruct::labelBackgroundCol, labelBackgroundCol, ecvGui::ParamStruct::labelFontSize, ecvGui::ParamStruct::labelMarkerCol, labelMarkerCol, ecvGui::ParamStruct::labelMarkerSize, ecvGui::ParamStruct::labelOpacity, ecvGui::ParamStruct::lightAmbientColor, lightAmbientColor, ecvGui::ParamStruct::lightDiffuseColor, lightDiffuseColor, ecvGui::ParamStruct::lightDoubleSided, ecvGui::ParamStruct::lightSpecularColor, lightSpecularColor, CVLog::LOG_WARNING, ecvOptions::logVerbosityLevel, ecvGui::ParamStruct::meshBackDiff, meshBackDiff, ecvGui::ParamStruct::meshFrontDiff, meshFrontDiff, ecvGui::ParamStruct::meshSpecular, meshSpecularColor, ecvGui::ParamStruct::minLoDCloudSize, ecvGui::ParamStruct::minLoDMeshSize, ecvOptions::normalsDisplayedByDefault, options, parameters, ecvGui::ParamStruct::pointsDefaultCol, pointsDefaultCol, ecvColor::RgbTpl< Type >::r, ecvColor::RgbaTpl< Type >::r, ccQtHelpers::SetButtonColor(), ecvGui::ParamStruct::showBBOnSelected, ecvGui::ParamStruct::textDefaultCol, textDefaultCol, ecvOptions::useNativeDialogs, ecvGui::ParamStruct::useVBOs, and ecvGui::ParamStruct::zoomSpeed.
Referenced by ccDisplayOptionsDlg(), and reset().
reset
void ccDisplayOptionsDlg::reset (void) protected slot
Definition at line 509 of file ecvDisplayOptionsDlg.cpp.
References m_defaultAppStyleIndex, options, parameters, refresh(), ecvGui::ParamStruct::reset(), and ecvOptions::reset().
Referenced by ccDisplayOptionsDlg().
Member Data Documentation
backgroundCol
QColor ccDisplayOptionsDlg::backgroundCol protected
Definition at line 93 of file ecvDisplayOptionsDlg.h.
Referenced by changeBackgroundColor(), and refresh().
bbDefaultCol
QColor ccDisplayOptionsDlg::bbDefaultCol protected
Definition at line 96 of file ecvDisplayOptionsDlg.h.
Referenced by changeBBColor(), and refresh().
labelBackgroundCol
QColor ccDisplayOptionsDlg::labelBackgroundCol protected
Definition at line 94 of file ecvDisplayOptionsDlg.h.
Referenced by changeLabelBackgroundColor(), and refresh().
labelMarkerCol
QColor ccDisplayOptionsDlg::labelMarkerCol protected
Definition at line 95 of file ecvDisplayOptionsDlg.h.
Referenced by changeLabelMarkerColor(), and refresh().
lightAmbientColor
QColor ccDisplayOptionsDlg::lightAmbientColor protected
Definition at line 86 of file ecvDisplayOptionsDlg.h.
Referenced by changeLightAmbientColor(), and refresh().
lightDiffuseColor
QColor ccDisplayOptionsDlg::lightDiffuseColor protected
Definition at line 85 of file ecvDisplayOptionsDlg.h.
Referenced by changeLightDiffuseColor(), and refresh().
lightSpecularColor
QColor ccDisplayOptionsDlg::lightSpecularColor protected
Definition at line 87 of file ecvDisplayOptionsDlg.h.
Referenced by changeLightSpecularColor(), and refresh().
m_defaultAppStyleIndex
int ccDisplayOptionsDlg::m_defaultAppStyleIndex protected
Default application style index (for reset)
Definition at line 109 of file ecvDisplayOptionsDlg.h.
Referenced by doReject(), and reset().
meshBackDiff
QColor ccDisplayOptionsDlg::meshBackDiff protected
Definition at line 89 of file ecvDisplayOptionsDlg.h.
Referenced by changeMeshBackDiffuseColor(), and refresh().
meshFrontDiff
QColor ccDisplayOptionsDlg::meshFrontDiff protected
Definition at line 88 of file ecvDisplayOptionsDlg.h.
Referenced by changeMeshFrontDiffuseColor(), and refresh().
meshSpecularColor
QColor ccDisplayOptionsDlg::meshSpecularColor protected
Definition at line 90 of file ecvDisplayOptionsDlg.h.
Referenced by changeMeshSpecularColor(), and refresh().
oldOptions
ecvOptions ccDisplayOptionsDlg::oldOptions protected
Old options (for restore)
Definition at line 106 of file ecvDisplayOptionsDlg.h.
Referenced by ccDisplayOptionsDlg(), and doReject().
oldParameters
ecvGui::ParamStruct ccDisplayOptionsDlg::oldParameters protected
Old parameters (for restore)
Definition at line 104 of file ecvDisplayOptionsDlg.h.
Referenced by ccDisplayOptionsDlg(), and doReject().
options
ecvOptions ccDisplayOptionsDlg::options protected
Current options.
Definition at line 101 of file ecvDisplayOptionsDlg.h.
Referenced by apply(), ccDisplayOptionsDlg(), changeLogVerbosityLevel(), doAccept(), refresh(), and reset().
parameters
ecvGui::ParamStruct ccDisplayOptionsDlg::parameters protected
Current GUI parameters.
Definition at line 99 of file ecvDisplayOptionsDlg.h.
Referenced by apply(), ccDisplayOptionsDlg(), changeAutoComputeOctreeOption(), changeBackgroundColor(), changeBBColor(), changeBBLineWidth(), changeBBOpacity(), changeColorScaleRampWidth(), changeDefaultFontSize(), changeLabelBackgroundColor(), changeLabelFontSize(), changeLabelMarkerColor(), changeLabelMarkerSize(), changeLabelOpacity(), changeLightAmbientColor(), changeLightDiffuseColor(), changeLightSpecularColor(), changeMaxCloudSize(), changeMaxMeshSize(), changeMeshBackDiffuseColor(), changeMeshFrontDiffuseColor(), changeMeshSpecularColor(), changeNumberPrecision(), changePointsColor(), changeTextColor(), changeVBOUsage(), changeZoomSpeed(), doAccept(), refresh(), and reset().
pointsDefaultCol
QColor ccDisplayOptionsDlg::pointsDefaultCol protected
Definition at line 91 of file ecvDisplayOptionsDlg.h.
Referenced by changePointsColor(), and refresh().
textDefaultCol
QColor ccDisplayOptionsDlg::textDefaultCol protected
Definition at line 92 of file ecvDisplayOptionsDlg.h.
Referenced by changeTextColor(), and refresh().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVAppCommon/include/ecvDisplayOptionsDlg.h
/root/ACloudViewer/libs/CVAppCommon/src/ecvDisplayOptionsDlg.cpp