ACloudViewer: ecvProgressDialog Class Reference
ecvProgressDialog Class Reference
Graphical progress indicator (thread-safe)
#include <ecvProgressDialog.h>
Signals
void scheduleRefresh ()
Schedules a call to refresh.
Public Member Functions
ecvProgressDialog (bool cancelButton=false, QWidget *parent=0)
Default constructor.
virtual ~ecvProgressDialog ()
Destructor (virtual)
virtual void update (float percent) override
Notifies the algorithm progress.
virtual void setMethodTitle (const char *methodTitle) override
Notifies the algorithm title.
virtual void setInfo (const char *infoStr) override
Notifies some information about the ongoing process.
virtual bool isCancelRequested () override
Checks if the process should be canceled.
virtual void start () override
virtual void stop () override
Notifies the fact that the process has ended.
virtual void setMethodTitle (QString methodTitle)
setMethodTitle with a QString as argument
virtual void setInfo (QString infoStr)
setInfo with a QString as argument
Public Member Functions inherited from cloudViewer::GenericProgressCallback
virtual ~GenericProgressCallback ()=default
Default destructor.
virtual bool textCanBeEdited () const
Returns whether the dialog title and info can be updated or not.
Protected Slots
void refresh ()
Refreshes the progress.
Protected Attributes
QAtomicInt m_currentValue
Current progress value (percent)
QAtomicInt m_lastRefreshValue
Last displayed progress value (percent)
Detailed Description
Graphical progress indicator (thread-safe)
Implements the GenericProgressCallback interface, in order to be passed to the cloudViewer algorithms (check the cloudViewer documentation for more information about the inherited methods).
Definition at line 27 of file ecvProgressDialog.h.
Constructor & Destructor Documentation
ecvProgressDialog()
ecvProgressDialog::ecvProgressDialog (bool cancelButton = false, QWidget * parent = 0)
Default constructor.
By default, a cancel button is always displayed on the progress interface. It is only possible to activate or deactivate this button. Sadly, the fact that this button is activated doesn't mean it will be possible to stop the ongoing process: it depends only on the client algorithm implementation.
Parameters
cancelButton activates or deactivates the cancel button
parent parent widget
~ecvProgressDialog()
virtual ecvProgressDialog::~ecvProgressDialog () inline virtual
Destructor (virtual)
Definition at line 45 of file ecvProgressDialog.h.
Member Function Documentation
isCancelRequested()
virtual bool ecvProgressDialog::isCancelRequested () inline override virtual
Checks if the process should be canceled.
This method is called by some process from time to time to know if it should halt before its normal ending. This is a way for the client application to cancel an ongoing process (but it won't work with all algorithms). Process results may be incomplete/void. The cancel requirement mechanism must be implemented (typically a simple "cancel()" method that will be called by the client application).
Implements cloudViewer::GenericProgressCallback.
Definition at line 55 of file ecvProgressDialog.h.
Referenced by ccCompass::estimateP21(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), and LasIOFilter::loadFile().
refresh
void ecvProgressDialog::refresh () protected slot
Refreshes the progress.
Should only be called in the main Qt thread! This slot is automatically called by 'update' (in Qt::QueuedConnection mode).
scheduleRefresh
void ecvProgressDialog::scheduleRefresh () signal
Schedules a call to refresh.
setInfo() [1/2]
virtual void ecvProgressDialog::setInfo (const char * infoStr) inline override virtual
Notifies some information about the ongoing process.
The notification is sent by the ongoing algorithm (on the library side).
Parameters
infoStr some textual information about the ongoing process
Implements cloudViewer::GenericProgressCallback.
Definition at line 52 of file ecvProgressDialog.h.
References cloudViewer::GenericProgressCallback::setInfo().
Referenced by qCanupoProcess::Classify(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), DistanceMapGenerationTool::ComputeRadialDist(), qFacets::createFacets(), define_ccProgressDialog(), ccCompass::estimateP21(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), StereogramWidget::init(), LasIOFilter::loadFile(), RDBFilter::loadFile(), LasIOFilter::saveToFile(), TileLasReader(), qCanupoTools::TrainClassifier(), and ccCompass::tryLoading().
setInfo() [2/2]
virtual void ecvProgressDialog::setInfo (QString infoStr) virtual
setInfo with a QString as argument
setMethodTitle() [1/2]
virtual void ecvProgressDialog::setMethodTitle (const char * methodTitle) inline override virtual
Notifies the algorithm title.
The notification is sent by the ongoing algorithm (on the library side).
Parameters
methodTitle the algorithm title
Implements cloudViewer::GenericProgressCallback.
Definition at line 49 of file ecvProgressDialog.h.
References cloudViewer::GenericProgressCallback::setMethodTitle().
Referenced by qCanupoProcess::Classify(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), DistanceMapGenerationTool::ComputeRadialDist(), qFacets::createFacets(), define_ccProgressDialog(), ccCompass::estimateP21(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), StereogramWidget::init(), LasIOFilter::loadFile(), RDBFilter::loadFile(), LasIOFilter::saveToFile(), TileLasReader(), ccCompass::tryLoading(), and G3Point::G3PointAction::wolman().
setMethodTitle() [2/2]
virtual void ecvProgressDialog::setMethodTitle (QString methodTitle) virtual
setMethodTitle with a QString as argument
start()
virtual void ecvProgressDialog::start () override virtual
Notifies the fact that every information has been sent and that the process begins Once start() is called, the progress bar and other informations could be displayed (for example).
Implements cloudViewer::GenericProgressCallback.
Referenced by qCanupoProcess::Classify(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), DistanceMapGenerationTool::ComputeRadialDist(), ccCompass::estimateP21(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), StereogramWidget::init(), LasIOFilter::loadFile(), RDBFilter::loadFile(), LasIOFilter::saveToFile(), TileLasReader(), and ccCompass::tryLoading().
stop()
virtual void ecvProgressDialog::stop () override virtual
Notifies the fact that the process has ended.
Once end() is called, the progress bar and other informations could be hidden (for example).
Implements cloudViewer::GenericProgressCallback.
Referenced by ccCompass::estimateStructureNormals(), and StereogramWidget::init().
update()
virtual void ecvProgressDialog::update (float percent) override virtual
Notifies the algorithm progress.
The notification is sent by the running algorithm (on the library side). This virtual method shouldn't be called too often, as the real process behind it is unspecified and may be time consuming. Ideally it shouldn't be called more than a few hundreds time.
Parameters
percent current progress, between 0.0 and 100.0
Implements cloudViewer::GenericProgressCallback.
Referenced by qVoxFallProcess::Compute(), ccCompass::estimateP21(), ccCompass::estimateStrain(), and ccCompass::estimateStructureNormals().
Member Data Documentation
m_currentValue
QAtomicInt ecvProgressDialog::m_currentValue protected
Current progress value (percent)
Definition at line 80 of file ecvProgressDialog.h.
m_lastRefreshValue
QAtomicInt ecvProgressDialog::m_lastRefreshValue protected
Last displayed progress value (percent)
Definition at line 83 of file ecvProgressDialog.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvProgressDialog.h