ACloudViewer: CoredMeshData< Vertex > Class Template Reference
CoredMeshData< Vertex > Class Template Reference abstract
#include <Geometry.h>
Public Member Functions
virtual void resetIterator (void)=0
virtual int addOutOfCorePoint (const Vertex &p)=0
virtual int addOutOfCorePoint_s (const Vertex &p)=0
virtual int addPolygon_s (const std::vector< CoredVertexIndex > &vertices)=0
virtual int addPolygon_s (const std::vector< int > &vertices)=0
virtual int nextOutOfCorePoint (Vertex &p)=0
virtual int nextPolygon (std::vector< CoredVertexIndex > &vertices)=0
virtual int outOfCorePointCount (void)=0
virtual int polygonCount (void)=0
Public Attributes
std::vector< Vertex > inCorePoints
Detailed Description
template<class Vertex>
class CoredMeshData< Vertex >
Definition at line 301 of file Geometry.h.
Member Function Documentation
addOutOfCorePoint()
template<class Vertex > virtual int CoredMeshData< Vertex >::addOutOfCorePoint (const Vertex & p) pure virtual
Implemented in CoredFileMeshData< Vertex >, and CoredVectorMeshData< Vertex >.
addOutOfCorePoint_s()
template<class Vertex > virtual int CoredMeshData< Vertex >::addOutOfCorePoint_s (const Vertex & p) pure virtual
Implemented in CoredFileMeshData< Vertex >, and CoredVectorMeshData< Vertex >.
addPolygon_s() [1/2]
template<class Vertex > virtual int CoredMeshData< Vertex >::addPolygon_s (const std::vector< CoredVertexIndex > & vertices) pure virtual
Implemented in CoredFileMeshData< Vertex >, and CoredVectorMeshData< Vertex >.
addPolygon_s() [2/2]
template<class Vertex > virtual int CoredMeshData< Vertex >::addPolygon_s (const std::vector< int > & vertices) pure virtual
Implemented in CoredFileMeshData< Vertex >, and CoredVectorMeshData< Vertex >.
nextOutOfCorePoint()
template<class Vertex > virtual int CoredMeshData< Vertex >::nextOutOfCorePoint (Vertex & p) pure virtual
Implemented in CoredFileMeshData< Vertex >, and CoredVectorMeshData< Vertex >.
Referenced by PlyWritePolygons().
nextPolygon()
template<class Vertex > virtual int CoredMeshData< Vertex >::nextPolygon (std::vector< CoredVertexIndex > & vertices) pure virtual
Implemented in CoredFileMeshData< Vertex >, and CoredVectorMeshData< Vertex >.
Referenced by PlyWritePolygons().
outOfCorePointCount()
template<class Vertex > virtual int CoredMeshData< Vertex >::outOfCorePointCount (void) pure virtual
Implemented in CoredFileMeshData< Vertex >, and CoredVectorMeshData< Vertex >.
Referenced by PlyWritePolygons().
polygonCount()
template<class Vertex > virtual int CoredMeshData< Vertex >::polygonCount (void) pure virtual
Implemented in CoredFileMeshData< Vertex >, and CoredVectorMeshData< Vertex >.
Referenced by PlyWritePolygons().
resetIterator()
template<class Vertex > virtual void CoredMeshData< Vertex >::resetIterator (void) pure virtual
Implemented in CoredFileMeshData< Vertex >, and CoredVectorMeshData< Vertex >.
Referenced by PlyWritePolygons().
Member Data Documentation
inCorePoints
template<class Vertex > std::vector< Vertex > CoredMeshData< Vertex >::inCorePoints
Definition at line 304 of file Geometry.h.
Referenced by PlyWritePolygons().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/Geometry.h