ACloudViewer: QCPItemText Class Reference
QCPItemText Class Reference
A text label.
#include <qcustomplot.h>
Public Member Functions
QCPItemText (QCustomPlot *parentPlot)
virtual ~QCPItemText ()
QColor color () const
QColor selectedColor () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QFont font () const
QFont selectedFont () const
QString text () const
Qt::Alignment positionAlignment () const
Qt::Alignment textAlignment () const
double rotation () const
QMargins padding () const
void setColor (const QColor &color)
void setSelectedColor (const QColor &color)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setFont (const QFont &font)
void setSelectedFont (const QFont &font)
void setText (const QString &text)
void setPositionAlignment (Qt::Alignment alignment)
void setTextAlignment (Qt::Alignment alignment)
void setRotation (double degrees)
void setPadding (const QMargins &padding)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
QCPItemText (QCustomPlot *parentPlot)
virtual ~QCPItemText ()
QColor color () const
QColor selectedColor () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QFont font () const
QFont selectedFont () const
QString text () const
Qt::Alignment positionAlignment () const
Qt::Alignment textAlignment () const
double rotation () const
QMargins padding () const
void setColor (const QColor &color)
void setSelectedColor (const QColor &color)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setFont (const QFont &font)
void setSelectedFont (const QFont &font)
void setText (const QString &text)
void setPositionAlignment (Qt::Alignment alignment)
void setTextAlignment (Qt::Alignment alignment)
void setRotation (double degrees)
void setPadding (const QMargins &padding)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Member Functions inherited from QCPAbstractItem
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
Public Member Functions inherited from QCPLayerable
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
virtual ~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
QCPLayerable (QCustomPlot *plot, QString targetLayer=QString(), QCPLayerable *parentLayerable=0)
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayerable * parentLayerable () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Q_SLOT bool setLayer (QCPLayer *layer)
bool setLayer (const QString &layerName)
void setAntialiased (bool enabled)
bool realVisibility () const
Public Attributes
QCPItemPosition *const position
QCPItemAnchor *const topLeft
QCPItemAnchor *const top
QCPItemAnchor *const topRight
QCPItemAnchor *const right
QCPItemAnchor *const bottomRight
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeft
QCPItemAnchor *const left
Protected Types
enum AnchorIndex {
aiTopLeft , aiTop , aiTopRight , aiRight ,
aiBottomRight , aiBottom , aiBottomLeft , aiLeft ,
aiTopLeft , aiTop , aiTopRight , aiRight ,
aiBottomRight , aiBottom , aiBottomLeft , aiLeft
}
enum AnchorIndex {
aiTopLeft , aiTop , aiTopRight , aiRight ,
aiBottomRight , aiBottom , aiBottomLeft , aiLeft ,
aiTopLeft , aiTop , aiTopRight , aiRight ,
aiBottomRight , aiBottom , aiBottomLeft , aiLeft
}
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPosition (int anchorId) const
QPointF getTextDrawPoint (const QPointF &pos, const QRectF &rect, Qt::Alignment positionAlignment) const
QFont mainFont () const
QColor mainColor () const
QPen mainPen () const
QBrush mainBrush () const
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPointF getTextDrawPoint (const QPointF &pos, const QRectF &rect, Qt::Alignment positionAlignment) const
QFont mainFont () const
QColor mainColor () const
QPen mainPen () const
QBrush mainBrush () const
Protected Member Functions inherited from QCPAbstractItem
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double rectDistance (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Member Functions inherited from QCPLayerable
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
virtual void mousePressEvent (QMouseEvent *event, const QVariant &details)
virtual void mouseMoveEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseReleaseEvent (QMouseEvent *event, const QPointF &startPos)
virtual void mouseDoubleClickEvent (QMouseEvent *event, const QVariant &details)
virtual void wheelEvent (QWheelEvent *event)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
virtual void parentPlotInitialized (QCustomPlot *parentPlot)
void initializeParentPlot (QCustomPlot *parentPlot)
void setParentLayerable (QCPLayerable *parentLayerable)
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
Protected Attributes
QColor mColor
QColor mSelectedColor
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
QFont mFont
QFont mSelectedFont
QString mText
Qt::Alignment mPositionAlignment
Qt::Alignment mTextAlignment
double mRotation
QMargins mPadding
Protected Attributes inherited from QCPAbstractItem
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Protected Attributes inherited from QCPLayerable
bool mVisible
QCustomPlot * mParentPlot
QPointer< QCPLayerable > mParentLayerable
QCPLayer * mLayer
bool mAntialiased
Additional Inherited Members
Signals inherited from QCPAbstractItem
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Signals inherited from QCPLayerable
void layerChanged (QCPLayer *newLayer)
void layerChanged (QCPLayer *newLayer)
Detailed Description
A text label.
Text example. Blue dotted circles are anchors,
solid blue discs are positions."
Its position is defined by the member position and the setting of setPositionAlignment. The latter controls which part of the text rect shall be aligned with position.
The text alignment itself (i.e. left, center, right) can be controlled with setTextAlignment.
The text may be rotated around the position point with setRotation.
Definition at line 7436 of file qcustomplot.h.
Member Enumeration Documentation
AnchorIndex [1/2]
enum QCPItemText::AnchorIndex protected
Enumerator
aiTopLeft
aiTop
aiTopRight
aiRight
aiBottomRight
aiBottom
aiBottomLeft
aiLeft
aiTopLeft
aiTop
aiTopRight
aiRight
aiBottomRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 7505 of file qcustomplot.h.
AnchorIndex [2/2]
enum QCPItemText::AnchorIndex protected
Enumerator
aiTopLeft
aiTop
aiTopRight
aiRight
aiBottomRight
aiBottom
aiBottomLeft
aiLeft
aiTopLeft
aiTop
aiTopRight
aiRight
aiBottomRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 4149 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemText() [1/2]
QCPItemText::QCPItemText (QCustomPlot * parentPlot) explicit
Creates a text item and sets default values.
The created item is automatically registered with parentPlot. This QCustomPlot instance takes ownership of the item, so do not delete it manually but use QCustomPlot::removeItem() instead.
Creates a text item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 30706 of file qcustomplot.cpp.
References ecvColor::black(), ecvColor::blue(), position, setBrush(), setColor(), QCPItemPosition::setCoords(), setPen(), setSelectedBrush(), setSelectedColor(), and setSelectedPen().
~QCPItemText() [1/2]
QCPItemText::~QCPItemText () virtual
Definition at line 30731 of file qcustomplot.cpp.
QCPItemText() [2/2]
QCPItemText::QCPItemText (QCustomPlot * parentPlot)
~QCPItemText() [2/2]
virtual QCPItemText::~QCPItemText () virtual
Member Function Documentation
anchorPixelPoint()
QPointF QCPItemText::anchorPixelPoint (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 23644 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiBottomRight, aiLeft, aiRight, aiTop, aiTopLeft, aiTopRight, getTextDrawPoint(), mainFont(), mPadding, mPositionAlignment, mRotation, mText, mTextAlignment, QCPItemPosition::pixelPoint(), and position.
anchorPixelPosition()
QPointF QCPItemText::anchorPixelPosition (int anchorId) const protected virtual
Reimplemented from QCPAbstractItem.
Definition at line 30906 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiBottomRight, aiLeft, aiRight, aiTop, aiTopLeft, aiTopRight, getTextDrawPoint(), mainFont(), mPadding, mPositionAlignment, mRotation, mText, mTextAlignment, QCPItemPosition::pixelPosition(), and position.
brush() [1/2]
QBrush QCPItemText::brush () const inline
Definition at line 7464 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
brush() [2/2]
QBrush QCPItemText::brush () const inline
Definition at line 4108 of file qcustomplot.h.
color() [1/2]
QColor QCPItemText::color () const inline
Definition at line 7460 of file qcustomplot.h.
Referenced by draw(), setColor(), and setSelectedColor().
color() [2/2]
QColor QCPItemText::color () const inline
Definition at line 4104 of file qcustomplot.h.
draw() [1/2]
void QCPItemText::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
Definition at line 30868 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), color(), getTextDrawPoint(), mainBrush(), mainColor(), mainFont(), mainPen(), mPadding, mPositionAlignment, mRotation, mText, mTextAlignment, QCPItemPosition::pixelPosition(), position, and QCPPainter::setPen().
draw() [2/2]
virtual void QCPItemText::draw (QCPPainter * painter) protected virtual
Implements QCPAbstractItem.
font() [1/2]
QFont QCPItemText::font () const inline
Definition at line 7466 of file qcustomplot.h.
Referenced by setFont(), and setSelectedFont().
font() [2/2]
QFont QCPItemText::font () const inline
Definition at line 4110 of file qcustomplot.h.
getTextDrawPoint() [1/2]
QPointF QCPItemText::getTextDrawPoint (const QPointF & pos, const QRectF & rect, Qt::Alignment positionAlignment) const protected
Definition at line 30958 of file qcustomplot.cpp.
References positionAlignment(), and result.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), and selectTest().
getTextDrawPoint() [2/2]
QPointF QCPItemText::getTextDrawPoint (const QPointF & pos, const QRectF & rect, Qt::Alignment positionAlignment) const protected
mainBrush() [1/2]
QBrush QCPItemText::mainBrush () const protected
Definition at line 31007 of file qcustomplot.cpp.
References mBrush, QCPAbstractItem::mSelected, and mSelectedBrush.
Referenced by draw().
mainBrush() [2/2]
QBrush QCPItemText::mainBrush () const protected
mainColor() [1/2]
QColor QCPItemText::mainColor () const protected
Definition at line 30991 of file qcustomplot.cpp.
References mColor, QCPAbstractItem::mSelected, and mSelectedColor.
Referenced by draw().
mainColor() [2/2]
QColor QCPItemText::mainColor () const protected
mainFont() [1/2]
QFont QCPItemText::mainFont () const protected
Definition at line 30982 of file qcustomplot.cpp.
References mFont, QCPAbstractItem::mSelected, and mSelectedFont.
Referenced by anchorPixelPoint(), anchorPixelPosition(), and draw().
mainFont() [2/2]
QFont QCPItemText::mainFont () const protected
mainPen() [1/2]
QPen QCPItemText::mainPen () const protected
Definition at line 31000 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
mainPen() [2/2]
QPen QCPItemText::mainPen () const protected
padding() [1/2]
QMargins QCPItemText::padding () const inline
Definition at line 7472 of file qcustomplot.h.
Referenced by setPadding().
padding() [2/2]
QMargins QCPItemText::padding () const inline
Definition at line 4116 of file qcustomplot.h.
pen() [1/2]
QPen QCPItemText::pen () const inline
Definition at line 7462 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
pen() [2/2]
QPen QCPItemText::pen () const inline
Definition at line 4106 of file qcustomplot.h.
positionAlignment() [1/2]
Qt::Alignment QCPItemText::positionAlignment () const inline
Definition at line 7469 of file qcustomplot.h.
Referenced by getTextDrawPoint().
positionAlignment() [2/2]
Qt::Alignment QCPItemText::positionAlignment () const inline
Definition at line 4113 of file qcustomplot.h.
rotation() [1/2]
double QCPItemText::rotation () const inline
Definition at line 7471 of file qcustomplot.h.
rotation() [2/2]
double QCPItemText::rotation () const inline
Definition at line 4115 of file qcustomplot.h.
selectedBrush() [1/2]
QBrush QCPItemText::selectedBrush () const inline
Definition at line 7465 of file qcustomplot.h.
selectedBrush() [2/2]
QBrush QCPItemText::selectedBrush () const inline
Definition at line 4109 of file qcustomplot.h.
selectedColor() [1/2]
QColor QCPItemText::selectedColor () const inline
Definition at line 7461 of file qcustomplot.h.
selectedColor() [2/2]
QColor QCPItemText::selectedColor () const inline
Definition at line 4105 of file qcustomplot.h.
selectedFont() [1/2]
QFont QCPItemText::selectedFont () const inline
Definition at line 7467 of file qcustomplot.h.
selectedFont() [2/2]
QFont QCPItemText::selectedFont () const inline
Definition at line 4111 of file qcustomplot.h.
selectedPen() [1/2]
QPen QCPItemText::selectedPen () const inline
Definition at line 7463 of file qcustomplot.h.
selectedPen() [2/2]
QPen QCPItemText::selectedPen () const inline
Definition at line 4107 of file qcustomplot.h.
selectTest() [1/2]
double QCPItemText::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 30840 of file qcustomplot.cpp.
References getTextDrawPoint(), mFont, mPadding, mPositionAlignment, mRotation, QCPAbstractItem::mSelectable, mText, mTextAlignment, QCPItemPosition::pixelPosition(), position, and QCPAbstractItem::rectDistance().
selectTest() [2/2]
virtual double QCPItemText::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const virtual
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/ deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
In the case of 1D Plottables (QCPAbstractPlottable1D, like QCPGraph or QCPBars) details will be set to a QCPDataSelection, describing the closest data point to pos.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, mousePressEvent, wheelEvent, QCustomPlot::setInteractions, QCPAbstractPlottable1D::selectTestRect
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
setBrush() [1/2]
void QCPItemText::setBrush (const QBrush & brush)
Sets the brush that will be used do fill the background of the text. To disable the background, set brush to Qt::NoBrush.
See also
setSelectedBrush, setPen, setPadding
Definition at line 30767 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPItemText().
setBrush() [2/2]
void QCPItemText::setBrush (const QBrush & brush)
setColor() [1/2]
void QCPItemText::setColor (const QColor & color)
Sets the color of the text.
Definition at line 30736 of file qcustomplot.cpp.
References color(), and mColor.
Referenced by QCPItemText().
setColor() [2/2]
void QCPItemText::setColor (const QColor & color)
setFont() [1/2]
void QCPItemText::setFont (const QFont & font)
Sets the font of the text.
See also
setSelectedFont, setColor
Definition at line 30784 of file qcustomplot.cpp.
References font(), and mFont.
setFont() [2/2]
void QCPItemText::setFont (const QFont & font)
setPadding() [1/2]
void QCPItemText::setPadding (const QMargins & padding)
Sets the distance between the border of the text rectangle and the text. The appearance (and visibility) of the text rectangle can be controlled with setPen and setBrush.
Definition at line 30837 of file qcustomplot.cpp.
References mPadding, and padding().
setPadding() [2/2]
void QCPItemText::setPadding (const QMargins & padding)
setPen() [1/2]
void QCPItemText::setPen (const QPen & pen)
Sets the pen that will be used do draw a rectangular border around the text. To disable the border, set pen to Qt::NoPen.
See also
setSelectedPen, setBrush, setPadding
Definition at line 30751 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemText().
setPen() [2/2]
void QCPItemText::setPen (const QPen & pen)
setPositionAlignment() [1/2]
void QCPItemText::setPositionAlignment (Qt::Alignment alignment)
Sets which point of the text rect shall be aligned with position.
Examples:
If alignment is Qt::AlignHCenter | Qt::AlignTop, the text will be positioned such that the top of the text rect will be horizontally centered on position.
If alignment is Qt::AlignLeft | Qt::AlignBottom, position will indicate the bottom left corner of the text rect.
If you want to control the alignment of (multi-lined) text within the text rect, use setTextAlignment.
Definition at line 30814 of file qcustomplot.cpp.
References mPositionAlignment.
setPositionAlignment() [2/2]
void QCPItemText::setPositionAlignment (Qt::Alignment alignment)
setRotation() [1/2]
void QCPItemText::setRotation (double degrees)
Sets the angle in degrees by which the text (and the text rectangle, if visible) will be rotated around position.
Definition at line 30830 of file qcustomplot.cpp.
References mRotation.
setRotation() [2/2]
void QCPItemText::setRotation (double degrees)
setSelectedBrush() [1/2]
void QCPItemText::setSelectedBrush (const QBrush & brush)
Sets the brush that will be used do fill the background of the text, when the item is selected. To disable the background, set brush to Qt::NoBrush.
See also
setBrush
Definition at line 30775 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPItemText().
setSelectedBrush() [2/2]
void QCPItemText::setSelectedBrush (const QBrush & brush)
setSelectedColor() [1/2]
void QCPItemText::setSelectedColor (const QColor & color)
Sets the color of the text that will be used when the item is selected.
Definition at line 30741 of file qcustomplot.cpp.
References color(), and mSelectedColor.
Referenced by QCPItemText().
setSelectedColor() [2/2]
void QCPItemText::setSelectedColor (const QColor & color)
setSelectedFont() [1/2]
void QCPItemText::setSelectedFont (const QFont & font)
Sets the font of the text that will be used when the item is selected.
See also
setFont
Definition at line 30791 of file qcustomplot.cpp.
References font(), and mSelectedFont.
setSelectedFont() [2/2]
void QCPItemText::setSelectedFont (const QFont & font)
setSelectedPen() [1/2]
void QCPItemText::setSelectedPen (const QPen & pen)
Sets the pen that will be used do draw a rectangular border around the text, when the item is selected. To disable the border, set pen to Qt::NoPen.
See also
setPen
Definition at line 30759 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemText().
setSelectedPen() [2/2]
void QCPItemText::setSelectedPen (const QPen & pen)
setText() [1/2]
void QCPItemText::setText (const QString & text)
Sets the text that will be displayed. Multi-line texts are supported by inserting a line break character, e.g. '
'.
See also
setFont, setColor, setTextAlignment
Definition at line 30799 of file qcustomplot.cpp.
References mText, and text().
setText() [2/2]
void QCPItemText::setText (const QString & text)
setTextAlignment() [1/2]
void QCPItemText::setTextAlignment (Qt::Alignment alignment)
Controls how (multi-lined) text is aligned inside the text rect (typically Qt::AlignLeft, Qt::AlignCenter or Qt::AlignRight).
Definition at line 30822 of file qcustomplot.cpp.
References mTextAlignment.
setTextAlignment() [2/2]
void QCPItemText::setTextAlignment (Qt::Alignment alignment)
text() [1/2]
QString QCPItemText::text () const inline
Definition at line 7468 of file qcustomplot.h.
Referenced by setText().
text() [2/2]
QString QCPItemText::text () const inline
Definition at line 4112 of file qcustomplot.h.
textAlignment() [1/2]
Qt::Alignment QCPItemText::textAlignment () const inline
Definition at line 7470 of file qcustomplot.h.
textAlignment() [2/2]
Qt::Alignment QCPItemText::textAlignment () const inline
Definition at line 4114 of file qcustomplot.h.
Member Data Documentation
bottom
QCPItemAnchor *const QCPItemText::bottom
Definition at line 7500 of file qcustomplot.h.
bottomLeft
QCPItemAnchor *const QCPItemText::bottomLeft
Definition at line 7501 of file qcustomplot.h.
bottomRight
QCPItemAnchor *const QCPItemText::bottomRight
Definition at line 7499 of file qcustomplot.h.
left
QCPItemAnchor *const QCPItemText::left
Definition at line 7502 of file qcustomplot.h.
mBrush
QBrush QCPItemText::mBrush protected
Definition at line 7519 of file qcustomplot.h.
Referenced by mainBrush(), and setBrush().
mColor
QColor QCPItemText::mColor protected
Definition at line 7517 of file qcustomplot.h.
Referenced by mainColor(), and setColor().
mFont
QFont QCPItemText::mFont protected
Definition at line 7520 of file qcustomplot.h.
Referenced by mainFont(), selectTest(), and setFont().
mPadding
QMargins QCPItemText::mPadding protected
Definition at line 7525 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), selectTest(), and setPadding().
mPen
QPen QCPItemText::mPen protected
Definition at line 7518 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
mPositionAlignment
Qt::Alignment QCPItemText::mPositionAlignment protected
Definition at line 7522 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), selectTest(), and setPositionAlignment().
mRotation
double QCPItemText::mRotation protected
Definition at line 7524 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), selectTest(), and setRotation().
mSelectedBrush
QBrush QCPItemText::mSelectedBrush protected
Definition at line 7519 of file qcustomplot.h.
Referenced by mainBrush(), and setSelectedBrush().
mSelectedColor
QColor QCPItemText::mSelectedColor protected
Definition at line 7517 of file qcustomplot.h.
Referenced by mainColor(), and setSelectedColor().
mSelectedFont
QFont QCPItemText::mSelectedFont protected
Definition at line 7520 of file qcustomplot.h.
Referenced by mainFont(), and setSelectedFont().
mSelectedPen
QPen QCPItemText::mSelectedPen protected
Definition at line 7518 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
mText
QString QCPItemText::mText protected
Definition at line 7521 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), selectTest(), and setText().
mTextAlignment
Qt::Alignment QCPItemText::mTextAlignment protected
Definition at line 7523 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), selectTest(), and setTextAlignment().
position
QCPItemPosition *const QCPItemText::position
Definition at line 7494 of file qcustomplot.h.
Referenced by anchorPixelPoint(), anchorPixelPosition(), draw(), QCPItemText(), and selectTest().
right
QCPItemAnchor *const QCPItemText::right
Definition at line 7498 of file qcustomplot.h.
top
QCPItemAnchor *const QCPItemText::top
Definition at line 7496 of file qcustomplot.h.
topLeft
QCPItemAnchor *const QCPItemText::topLeft
Definition at line 7495 of file qcustomplot.h.
topRight
QCPItemAnchor *const QCPItemText::topRight
Definition at line 7497 of file qcustomplot.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.h
/root/ACloudViewer/app/extern/QCustomPlot/qcustomplot.cpp