ACloudViewer: cvSelectionData Class Reference
cvSelectionData Class Reference
Encapsulates selection data without exposing VTK types.
#include <cvSelectionData.h>
Public Types
enum FieldAssociation { CELLS = 0 , POINTS = 1 }
Field association for selection.
Public Member Functions
cvSelectionData ()
Construct empty selection data.
cvSelectionData (vtkIdTypeArray *vtkArray, int association)
Construct from VTK selection array.
cvSelectionData (const QVector< qint64 > &ids, FieldAssociation association)
Construct from ID vector.
cvSelectionData (const cvSelectionData &other)
Copy constructor.
cvSelectionData & operator= (const cvSelectionData &other)
Assignment operator.
~cvSelectionData ()
Destructor.
bool isEmpty () const
Check if selection is empty.
int count () const
Get number of selected items.
FieldAssociation fieldAssociation () const
Get field association.
QVector< qint64 > ids () const
Get selected IDs as a vector (copy)
vtkSmartPointer< vtkIdTypeArray > vtkArray () const
Get the underlying VTK array (for internal use only)
void clear ()
Clear the selection.
QString fieldTypeString () const
Get human-readable field type string.
void addActorInfo (const cvActorSelectionInfo &info)
Actor/Representation information (ParaView-style)
void setActorInfo (vtkActor *actor, vtkPolyData *polyData, double zValue=1.0)
Set actor information (single actor case)
int actorCount () const
Get number of actors in this selection.
bool hasActorInfo () const
Check if actor information is available.
cvActorSelectionInfo actorInfo (int index=0) const
Get actor info at index.
QVector< cvActorSelectionInfo > actorInfos () const
Get all actor infos.
vtkActor * primaryActor () const
Get the primary (front-most) actor.
vtkPolyData * primaryPolyData () const
Get the primary (front-most) polyData.
void clearActorInfo ()
Clear actor information.
Detailed Description
Encapsulates selection data without exposing VTK types.
This class provides a VTK-independent interface for selection data, hiding the underlying vtkIdTypeArray implementation.
Following ParaView's design pattern, this class can now store information about multiple selected actors/representations along with their selection data.
Definition at line 136 of file cvSelectionData.h.
Member Enumeration Documentation
FieldAssociation
enum cvSelectionData::FieldAssociation
Field association for selection.
Enumerator
CELLS
Selection applies to cells.
POINTS
Selection applies to points.
Definition at line 141 of file cvSelectionData.h.
Constructor & Destructor Documentation
cvSelectionData() [1/4]
cvSelectionData::cvSelectionData ()
Construct empty selection data.
Definition at line 19 of file cvSelectionData.cpp.
cvSelectionData() [2/4]
cvSelectionData::cvSelectionData (vtkIdTypeArray * vtkArray, int association)
Construct from VTK selection array.
Parameters
vtkArray The VTK array (will be deep copied)
association Field association (0=cells, 1=points)
Definition at line 23 of file cvSelectionData.cpp.
References vtkArray().
cvSelectionData() [3/4]
cvSelectionData::cvSelectionData (const QVector< qint64 > & ids, FieldAssociation association)
Construct from ID vector.
Parameters
ids Vector of selected IDs
association Field association
Definition at line 45 of file cvSelectionData.cpp.
References ids().
cvSelectionData() [4/4]
cvSelectionData::cvSelectionData (const cvSelectionData & other)
Copy constructor.
Definition at line 58 of file cvSelectionData.cpp.
~cvSelectionData()
cvSelectionData::~cvSelectionData ()
Destructor.
Definition at line 109 of file cvSelectionData.cpp.
Member Function Documentation
actorCount()
int cvSelectionData::actorCount () const inline
Get number of actors in this selection.
Returns
Number of actors (0 if no actor info stored)
Definition at line 248 of file cvSelectionData.h.
Referenced by cvSelectionPipeline::combineSelections().
actorInfo()
cvActorSelectionInfo cvSelectionData::actorInfo (int index = 0) const
Get actor info at index.
Parameters
index Index in the list (0 = front-most)
Returns
Actor info, or empty struct if index out of range
Note: List is sorted by Z-value (front to back)
Definition at line 173 of file cvSelectionData.cpp.
Referenced by cvSelectionPipeline::combineSelections().
actorInfos()
QVector<cvActorSelectionInfo> cvSelectionData::actorInfos () const inline
Get all actor infos.
Returns
Vector of actor infos, sorted by Z-value (front to back)
Definition at line 268 of file cvSelectionData.h.
addActorInfo()
void cvSelectionData::addActorInfo (const cvActorSelectionInfo & info)
Actor/Representation information (ParaView-style)
These methods provide access to information about which actors/ representations were involved in the selection, similar to ParaView's selectedRepresentations collection.
Add actor information to the selection
Parameters
info Actor selection information
Use this when performing hardware selection or when you need to track which specific actor was selected.
Definition at line 148 of file cvSelectionData.cpp.
References a.
Referenced by cvGenericSelectionTool::createSelectionFromPick().
clear()
void cvSelectionData::clear ()
Clear the selection.
Definition at line 137 of file cvSelectionData.cpp.
Referenced by cvSelectionPropertiesWidget::clearSelection().
clearActorInfo()
void cvSelectionData::clearActorInfo ()
Clear actor information.
Definition at line 191 of file cvSelectionData.cpp.
count()
int cvSelectionData::count () const
Get number of selected items.
Definition at line 119 of file cvSelectionData.cpp.
Referenced by cvSelectionFilter::combineAND(), cvSelectionFilter::combineOR(), cvSelectionAlgebra::complementOf(), cvSelectionAlgebra::differenceOf(), cvViewSelectionManager::expandSelection(), cvSelectionExporter::exportToMesh(), cvSelectionExporter::exportToPointCloud(), cvSelectionAlgebra::extractBoundary(), cvSelectionAlgebra::growPointSelection(), cvSelectionAlgebra::growSelection(), cvSelectionHighlighter::highlightSelection(), cvSelectionAlgebra::intersectionOf(), cvSelectionFilter::invert(), cvSelectionToolController::onSelectionFinished(), cvViewSelectionManager::setCurrentSelection(), cvSelectionAlgebra::shrinkPointSelection(), cvSelectionAlgebra::shrinkSelection(), cvSelectionAlgebra::symmetricDifferenceOf(), and cvSelectionAlgebra::unionOf().
fieldAssociation()
FieldAssociation cvSelectionData::fieldAssociation () const inline
Get field association.
Definition at line 193 of file cvSelectionData.h.
Referenced by cvSelectionAlgebra::areCompatible(), cvSelectionFilter::combineAND(), cvSelectionFilter::combineOR(), cvSelectionPipeline::combineSelections(), cvSelectionAlgebra::complementOf(), cvSelectionAlgebra::expandSelection(), cvSelectionExporter::exportFromSourceCloud(), cvSelectionExporter::exportFromSourceMesh(), cvSelectionExporter::exportToFile(), cvSelectionExporter::exportToMesh(), cvSelectionExporter::exportToPointCloud(), cvSelectionAlgebra::extractBoundary(), cvSelectionExporter::extractSelection(), cvSelectionFilter::filterByArea(), cvSelectionFilter::filterByAttributeComparison(), cvSelectionFilter::filterByAttributeRange(), cvSelectionFilter::filterByBoundingBox(), cvSelectionFilter::filterByDistanceFromPoint(), cvSelectionFilter::filterByNeighborCount(), cvSelectionFilter::filterByNormalAngle(), cvSelectionAlgebra::growPointSelection(), cvSelectionAlgebra::growSelection(), cvSelectionHighlighter::highlightSelection(), cvSelectionFilter::invert(), cvViewSelectionManager::setCurrentSelection(), cvSelectionAlgebra::shrinkPointSelection(), cvSelectionAlgebra::shrinkSelection(), and cvSelectionPropertiesWidget::updateSelection().
fieldTypeString()
QString cvSelectionData::fieldTypeString () const
Get human-readable field type string.
Definition at line 143 of file cvSelectionData.cpp.
References CELLS.
Referenced by cvSelectionHighlighter::highlightSelection(), cvSelectionToolController::onSelectionFinished(), and cvViewSelectionManager::setCurrentSelection().
hasActorInfo()
bool cvSelectionData::hasActorInfo () const inline
Check if actor information is available.
Definition at line 253 of file cvSelectionData.h.
Referenced by cvSelectionAlgebra::expandSelection(), cvRenderViewSelectionReaction::finalizeSelection(), cvSelectionBase::getPolyDataForSelection(), and cvGenericSelectionTool::getPolyDataForSelection().
ids()
QVector< qint64 > cvSelectionData::ids () const
Get selected IDs as a vector (copy)
Definition at line 124 of file cvSelectionData.cpp.
References result.
Referenced by cvSelectionFilter::combineAND(), cvSelectionFilter::combineOR(), cvSelectionAlgebra::complementOf(), cvSelectionData(), cvSelectionAlgebra::differenceOf(), cvSelectionAlgebra::expandSelection(), cvSelectionExporter::exportFromSourceCloud(), cvSelectionExporter::exportFromSourceMesh(), cvSelectionAlgebra::extractBoundary(), cvSelectionFilter::filterByArea(), cvSelectionFilter::filterByAttributeComparison(), cvSelectionFilter::filterByAttributeRange(), cvSelectionFilter::filterByBoundingBox(), cvSelectionFilter::filterByDistanceFromPoint(), cvSelectionFilter::filterByNeighborCount(), cvSelectionFilter::filterByNormalAngle(), cvSelectionAlgebra::growPointSelection(), cvSelectionAlgebra::growSelection(), cvSelectionAlgebra::intersectionOf(), cvSelectionFilter::invert(), cvSelectionAlgebra::shrinkPointSelection(), cvSelectionAlgebra::shrinkSelection(), cvSelectionAlgebra::symmetricDifferenceOf(), cvSelectionAlgebra::unionOf(), and cvSelectionPropertiesWidget::updateSelection().
isEmpty()
bool cvSelectionData::isEmpty () const
Check if selection is empty.
Definition at line 114 of file cvSelectionData.cpp.
Referenced by cvSelectionAnnotationManager::addAnnotation(), cvSelectionAlgebra::areCompatible(), cvSelectionExporter::batchExportToFiles(), cvSelectionFilter::combineAND(), cvSelectionFilter::combineOR(), cvSelectionPipeline::combineSelections(), cvSelectionAlgebra::complementOf(), cvSelectionAlgebra::differenceOf(), cvViewSelectionManager::expandSelection(), cvSelectionAlgebra::expandSelection(), cvSelectionExporter::exportFromSourceCloud(), cvSelectionExporter::exportFromSourceMesh(), cvSelectionExporter::exportNumbered(), cvSelectionExporter::exportToFile(), cvSelectionExporter::exportToMesh(), cvSelectionExporter::exportToPointCloud(), cvSelectionAlgebra::extractBoundary(), cvSelectionExporter::extractSelection(), cvSelectionFilter::filterByArea(), cvSelectionFilter::filterByAttributeComparison(), cvSelectionFilter::filterByAttributeRange(), cvSelectionFilter::filterByBoundingBox(), cvSelectionFilter::filterByDistanceFromPoint(), cvSelectionFilter::filterByNeighborCount(), cvSelectionFilter::filterByNormalAngle(), cvRenderViewSelectionReaction::finalizeSelection(), cvSelectionAlgebra::growPointSelection(), cvSelectionAlgebra::growSelection(), cvGenericSelectionTool::hardwareSelectInRegion(), cvSelectionHighlighter::highlightSelection(), cvSelectionAlgebra::intersectionOf(), cvSelectionFilter::invert(), cvSelectionToolController::onSelectionFinished(), cvSelectionAlgebra::shrinkPointSelection(), cvSelectionAlgebra::shrinkSelection(), cvSelectionAlgebra::symmetricDifferenceOf(), cvSelectionAlgebra::unionOf(), and cvSelectionPropertiesWidget::updateSelection().
operator=()
cvSelectionData & cvSelectionData::operator= (const cvSelectionData & other)
Assignment operator.
Definition at line 81 of file cvSelectionData.cpp.
primaryActor()
vtkActor * cvSelectionData::primaryActor () const
Get the primary (front-most) actor.
Returns
Pointer to primary actor, or nullptr if not available
This is the actor closest to the camera (smallest Z value)
Definition at line 181 of file cvSelectionData.cpp.
Referenced by cvSelectionAlgebra::expandSelection(), and cvRenderViewSelectionReaction::finalizeSelection().
primaryPolyData()
vtkPolyData * cvSelectionData::primaryPolyData () const
Get the primary (front-most) polyData.
Returns
Pointer to primary polyData, or nullptr if not available
Definition at line 186 of file cvSelectionData.cpp.
Referenced by cvSelectionAlgebra::expandSelection(), cvSelectionBase::getPolyDataForSelection(), and cvGenericSelectionTool::getPolyDataForSelection().
setActorInfo()
void cvSelectionData::setActorInfo (vtkActor * actor, vtkPolyData * polyData, double zValue = 1.0)
Set actor information (single actor case)
Parameters
actor The selected actor
polyData The associated polyData
zValue Optional Z-buffer depth value
Definition at line 159 of file cvSelectionData.cpp.
References cvActorSelectionInfo::actor, cvActorSelectionInfo::polyData, and cvActorSelectionInfo::zValue.
Referenced by cvSelectionAlgebra::expandSelection().
vtkArray()
vtkSmartPointer<vtkIdTypeArray> cvSelectionData::vtkArray () const inline
Get the underlying VTK array (for internal use only)
Returns
Smart pointer to VTK array
Definition at line 204 of file cvSelectionData.h.
Referenced by cvSelectionPipeline::combineSelections(), cvSelectionData(), cvSelectionExporter::extractSelection(), cvSelectionHighlighter::highlightSelection(), and cvViewSelectionManager::setCurrentSelection().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvSelectionData.h
/root/ACloudViewer/libs/PCLEngine/Tools/SelectionTools/cvSelectionData.cpp