ACloudViewer: cloudViewer::core::Open3DDLManagedTensor< DLMT > Class Template Reference
cloudViewer::core::Open3DDLManagedTensor< DLMT > Class Template Reference
CloudViewer DLPack Tensor manager.
Static Public Member Functions
static DLMT * Create (const Tensor &o3d_tensor)
static DLDevice getDLPackDevice (const Tensor &o3d_tensor)
static void Deleter (DLMT *arg)
Detailed Description
template<typename DLMT>
class cloudViewer::core::Open3DDLManagedTensor< DLMT >
CloudViewer DLPack Tensor manager.
Definition at line 133 of file Tensor.cpp.
Member Function Documentation
Create()
template<typename DLMT > static DLMT* cloudViewer::core::Open3DDLManagedTensor< DLMT >::Create (const Tensor & o3d_tensor) inline static
DLManagedTensorVersioned* dmlt is destroyed by calling dmlt->deleter(dmlt). The destruction happens when the DLPack python object goes out of scope, and ultimately it decreases the reference count to the actual data buffer (i.e. dmlt.manager_ctx->o3d_tensor_.GetBlob()) by 1.
Definition at line 181 of file Tensor.cpp.
Referenced by cloudViewer::core::Tensor::ToDLPack(), and cloudViewer::core::Tensor::ToDLPackVersioned().
Deleter()
template<typename DLMT > static void cloudViewer::core::Open3DDLManagedTensor< DLMT >::Deleter (DLMT * arg) inline static
Definition at line 208 of file Tensor.cpp.
getDLPackDevice()
template<typename DLMT > static DLDevice cloudViewer::core::Open3DDLManagedTensor< DLMT >::getDLPackDevice (const Tensor & o3d_tensor) inline static
Definition at line 187 of file Tensor.cpp.
References cloudViewer::core::Device::CPU, cloudViewer::core::Device::CUDA, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Device::GetID(), cloudViewer::core::Device::GetType(), kDLCPU, kDLCUDA, kDLOneAPI, LogError, cloudViewer::core::Device::SYCL, and cloudViewer::core::Device::ToString().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/Tensor.cpp