ACloudViewer: History Class Reference
History Class Reference final
Simple history system for the REPL.
#include <PythonRepl.h>
Public Member Functions
History ()=default
void add (QString &&cmd)
size_t size () const
bool empty () const
const QString & older ()
const QString & newer ()
Detailed Description
Simple history system for the REPL.
Definition at line 23 of file PythonRepl.h.
Constructor & Destructor Documentation
History()
History::History () explicit default
Member Function Documentation
add()
void History::add (QString && cmd)
Definition at line 227 of file PythonRepl.cpp.
Referenced by KeyPressEater::eventFilter().
empty()
bool History::empty () const
Definition at line 263 of file PythonRepl.cpp.
Referenced by KeyPressEater::eventFilter().
newer()
const QString & History::newer ()
Definition at line 244 of file PythonRepl.cpp.
References replArrows().
Referenced by KeyPressEater::eventFilter().
older()
const QString & History::older ()
Definition at line 233 of file PythonRepl.cpp.
Referenced by KeyPressEater::eventFilter().
size()
size_t History::size (void) const
Definition at line 268 of file PythonRepl.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonRepl.h
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonRepl.cpp