ACloudViewer: cloudViewer::visualization::MessageProcessor Class Reference
cloudViewer::visualization::MessageProcessor Class Reference
#include <MessageProcessor.h>
Public Types
using OnGeometryFunc = std::function< void(std::shared_ptr< ccHObject >, const std::string &, int, const std::string &)>
Public Member Functions
MessageProcessor (gui::Window *window, OnGeometryFunc on_geometry)
std::shared_ptr< zmq::message_t > ProcessMessage (const io::rpc::messages::Request &req, const io::rpc::messages::SetMeshData &msg, const msgpack::object_handle &obj) override
Public Member Functions inherited from cloudViewer::io::rpc::MessageProcessorBase
MessageProcessorBase ()
Constructs a receiver listening on the specified address.
virtual ~MessageProcessorBase ()
virtual std::shared_ptr< zmq::message_t > ProcessMessage (const messages::Request &req, const messages::GetMeshData &msg, const msgpack::object_handle &obj)
virtual std::shared_ptr< zmq::message_t > ProcessMessage (const messages::Request &req, const messages::SetCameraData &msg, const msgpack::object_handle &obj)
virtual std::shared_ptr< zmq::message_t > ProcessMessage (const messages::Request &req, const messages::SetProperties &msg, const msgpack::object_handle &obj)
virtual std::shared_ptr< zmq::message_t > ProcessMessage (const messages::Request &req, const messages::SetActiveCamera &msg, const msgpack::object_handle &obj)
virtual std::shared_ptr< zmq::message_t > ProcessMessage (const messages::Request &req, const messages::SetTime &msg, const msgpack::object_handle &obj)
Detailed Description
MessageProcessor implementation which interfaces with the CloudViewerScene and a Window.
Definition at line 23 of file MessageProcessor.h.
Member Typedef Documentation
OnGeometryFunc
using cloudViewer::visualization::MessageProcessor::OnGeometryFunc = std::function<void(std::shared_ptr<ccHObject>, const std::string&, int, const std::string&)>
Definition at line 25 of file MessageProcessor.h.
Constructor & Destructor Documentation
MessageProcessor()
cloudViewer::visualization::MessageProcessor::MessageProcessor (gui::Window * window, OnGeometryFunc on_geometry) inline
Definition at line 30 of file MessageProcessor.h.
Member Function Documentation
ProcessMessage()
std::shared_ptr< zmq::message_t > cloudViewer::visualization::MessageProcessor::ProcessMessage (const io::rpc::messages::Request & req, const io::rpc::messages::SetMeshData & msg, const msgpack::object_handle & obj) override virtual
Function for processing a msg.
Parameters
req The Request object that accompanies the msg object.
msg The message to be processed
obj The handle to the object from which the msg was unpacked. Can be used for custom unpacking.
Reimplemented from cloudViewer::io::rpc::MessageProcessorBase.
Definition at line 27 of file MessageProcessor.cpp.
References ccPointCloud::addNorm(), cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::io::rpc::messages::MeshData::CheckMessage(), cloudViewer::io::rpc::messages::Array::CheckNonEmpty(), cloudViewer::io::rpc::messages::Array::CheckType(), cloudViewer::io::rpc::messages::SetMeshData::data, cloudViewer::io::rpc::messages::Status::ErrorProcessingMessage(), cloudViewer::io::rpc::messages::MeshData::faces, Vector3Tpl< PointCoordinateType >::fromArray(), ccPointCloud::hasNormals(), LogInfo, cloudViewer::io::rpc::messages::Array::Ptr(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveThePointsTable(), ccObject::setEnabled(), ccObject::setLocked(), cloudViewer::io::rpc::messages::Array::shape, cloudViewer::io::rpc::messages::Array::type, cloudViewer::io::rpc::messages::TypeStr< double >(), cloudViewer::io::rpc::messages::TypeStr< float >(), cloudViewer::io::rpc::messages::MeshData::vertex_attributes, and cloudViewer::io::rpc::messages::MeshData::vertices.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/MessageProcessor.h
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/MessageProcessor.cpp