ACloudViewer: colmap::Sampler Class Reference
colmap::Sampler Class Reference abstract
#include <sampler.h>
Public Member Functions
Sampler ()
Sampler (const size_t num_samples)
virtual void Initialize (const size_t total_num_samples)=0
virtual size_t MaxNumSamples ()=0
virtual std::vector< size_t > Sample ()=0
template<typename X_t >
void SampleX (const X_t &X, X_t *X_rand)
template<typename X_t , typename Y_t >
void SampleXY (const X_t &X, const Y_t &Y, X_t *X_rand, Y_t *Y_rand)
Detailed Description
Definition at line 18 of file sampler.h.
Constructor & Destructor Documentation
Sampler() [1/2]
colmap::Sampler::Sampler () inline
Definition at line 20 of file sampler.h.
Sampler() [2/2]
colmap::Sampler::Sampler (const size_t num_samples) explicit
Member Function Documentation
Initialize()
virtual void colmap::Sampler::Initialize (const size_t total_num_samples) pure virtual
Implemented in colmap::RandomSampler, colmap::ProgressiveSampler, and colmap::CombinationSampler.
MaxNumSamples()
virtual size_t colmap::Sampler::MaxNumSamples () pure virtual
Implemented in colmap::RandomSampler, colmap::ProgressiveSampler, and colmap::CombinationSampler.
Sample()
virtual std::vector<size_t> colmap::Sampler::Sample () pure virtual
Implemented in colmap::RandomSampler, colmap::ProgressiveSampler, and colmap::CombinationSampler.
Referenced by SampleX(), and SampleXY().
SampleX()
template<typename X_t > void colmap::Sampler::SampleX (const X_t & X, X_t * X_rand)
Definition at line 52 of file sampler.h.
References Sample(), and X.
SampleXY()
template<typename X_t , typename Y_t > void colmap::Sampler::SampleXY (const X_t & X, const Y_t & Y, X_t * X_rand, Y_t * Y_rand)
Definition at line 60 of file sampler.h.
References Sample(), and X.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/optim/sampler.h