ACloudViewer: flann::mpi::Index< Distance > Class Template Reference
flann::mpi::Index< Distance > Class Template Reference
#include <index.h>
Public Member Functions
Index (const std::string &file_name, const std::string &dataset_name, const IndexParams &params)
~Index ()
void buildIndex ()
void knnSearch (const flann::Matrix< ElementType > &queries, flann::Matrix< int > &indices, flann::Matrix< DistanceType > &dists, int knn, const SearchParams &params)
int radiusSearch (const flann::Matrix< ElementType > &query, flann::Matrix< int > &indices, flann::Matrix< DistanceType > &dists, float radius, const SearchParams &params)
int veclen () const
int size () const
IndexParams getIndexParameters ()
Detailed Description
template<typename Distance>
class flann::mpi::Index< Distance >
Definition at line 113 of file index.h.
Constructor & Destructor Documentation
Index()
template<typename Distance > Index::Index (const std::string & file_name, const std::string & dataset_name, const IndexParams & params)
Definition at line 167 of file index.h.
References FLANN_INDEX_SAVED, flann::load_from_file(), offset_, params, and size_.
~Index()
template<typename Distance > Index::~Index
Definition at line 189 of file index.h.
Member Function Documentation
buildIndex()
template<typename Distance > void flann::mpi::Index< Distance >::buildIndex () inline
Definition at line 130 of file index.h.
References flann::Index< Distance >::buildIndex().
Referenced by flann::mpi::Server< Distance >::Server().
getIndexParameters()
template<typename Distance > IndexParams flann::mpi::Index< Distance >::getIndexParameters () inline
Definition at line 159 of file index.h.
References flann::Index< Distance >::getParameters().
knnSearch()
template<typename Distance > void Index::knnSearch (const flann::Matrix< ElementType > & queries, flann::Matrix< int > & indices, flann::Matrix< DistanceType > & dists, int knn, const SearchParams & params)
Definition at line 196 of file index.h.
References flann::Matrix_::cols, flann::mpi::SearchResults< DistanceType >::dists, flann::mpi::SearchResults< DistanceType >::indices, offset_, params, flann::Matrix< T >::ptr(), and flann::Matrix_::rows.
radiusSearch()
template<typename Distance > int Index::radiusSearch (const flann::Matrix< ElementType > & query, flann::Matrix< int > & indices, flann::Matrix< DistanceType > & dists, float radius, const SearchParams & params)
Definition at line 229 of file index.h.
References flann::Matrix_::cols, flann::mpi::SearchResults< DistanceType >::dists, flann::mpi::SearchResults< DistanceType >::indices, min(), offset_, params, flann::Matrix< T >::ptr(), and flann::Matrix_::rows.
size()
template<typename Distance > int flann::mpi::Index< Distance >::size () const inline
Definition at line 154 of file index.h.
References size_.
veclen()
template<typename Distance > int flann::mpi::Index< Distance >::veclen () const inline
Definition at line 149 of file index.h.
References flann::Index< Distance >::veclen().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/mpi/index.h