ACloudViewer: vtkStringList Class Reference
vtkStringList Class Reference
#include <vtkStringList.h>
Classes
class vtkInternals
Public Member Functions
vtkTypeMacro (vtkStringList, vtkObject)
void PrintSelf (ostream &os, vtkIndent indent) override
void AddString (const char *str)
void AddUniqueString (const char *str)
void AddFormattedString (const char *EventString,...)
void RemoveAllItems ()
void SetString (int idx, const char *str)
int GetLength ()
int GetIndex (const char *str)
const char * GetString (int idx)
int GetNumberOfStrings ()
Static Public Member Functions
static vtkStringList * New ()
Protected Member Functions
vtkStringList ()
~vtkStringList () override
Detailed Description
Definition at line 15 of file vtkStringList.h.
Constructor & Destructor Documentation
vtkStringList()
vtkStringList::vtkStringList () protected
Definition at line 34 of file vtkStringList.cxx.
~vtkStringList()
vtkStringList::~vtkStringList () override protected
Definition at line 40 of file vtkStringList.cxx.
Member Function Documentation
AddFormattedString()
void vtkStringList::AddFormattedString (const char * EventString, ...)
Add a command and format it any way you like.
Definition at line 98 of file vtkStringList.cxx.
References AddString(), event, and format.
AddString()
void vtkStringList::AddString (const char * str)
Add a simple string.
Definition at line 76 of file vtkStringList.cxx.
Referenced by AddFormattedString(), and AddUniqueString().
AddUniqueString()
void vtkStringList::AddUniqueString (const char * str)
Definition at line 88 of file vtkStringList.cxx.
References AddString(), and GetIndex().
GetIndex()
int vtkStringList::GetIndex (const char * str)
Get the index of a string.
Definition at line 51 of file vtkStringList.cxx.
References Utils::distance().
Referenced by AddUniqueString().
GetLength()
int vtkStringList::GetLength () inline
Get the length of the list.
Definition at line 47 of file vtkStringList.h.
GetNumberOfStrings()
int vtkStringList::GetNumberOfStrings ()
Returns the number of strings.
Definition at line 127 of file vtkStringList.cxx.
Referenced by PrintSelf().
GetString()
const char * vtkStringList::GetString (int idx)
Get a command from its index.
Definition at line 64 of file vtkStringList.cxx.
References NULL.
Referenced by PrintSelf().
New()
static vtkStringList* vtkStringList::New () static
PrintSelf()
void vtkStringList::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 134 of file vtkStringList.cxx.
References QtCompat::endl(), GetNumberOfStrings(), and GetString().
RemoveAllItems()
void vtkStringList::RemoveAllItems ()
Initialize to empty.
Definition at line 45 of file vtkStringList.cxx.
SetString()
void vtkStringList::SetString (int idx, const char * str)
Random access.
Definition at line 111 of file vtkStringList.cxx.
vtkTypeMacro()
vtkStringList::vtkTypeMacro (vtkStringList , vtkObject)
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkStringList.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkStringList.cxx