ACloudViewer: flann::CompositeIndex< Distance > Class Template Reference
flann::CompositeIndex< Distance > Class Template Reference
#include <composite_index.h>
Public Types
typedef Distance::ElementType ElementType
typedef Distance::ResultType DistanceType
typedef NNIndex< Distance > BaseClass
typedef bool needs_kdtree_distance
Public Types inherited from flann::NNIndex< Distance >
typedef Distance::ElementType ElementType
typedef Distance::ResultType DistanceType
Public Member Functions
CompositeIndex (const IndexParams &params=CompositeIndexParams(), Distance d=Distance())
CompositeIndex (const Matrix< ElementType > &inputData, const IndexParams &params=CompositeIndexParams(), Distance d=Distance())
CompositeIndex (const CompositeIndex &other)
CompositeIndex & operator= (CompositeIndex other)
virtual ~CompositeIndex ()
BaseClass * clone () const
flann_algorithm_t getType () const
size_t size () const
size_t veclen () const
int usedMemory () const
void buildIndex ()
Builds the index.
void addPoints (const Matrix< ElementType > &points, float rebuild_threshold=2)
Incrementally add points to the index.
void removePoint (size_t index)
void saveIndex (FILE *stream)
Saves the index to a stream.
void loadIndex (FILE *stream)
Loads the index from a stream.
void findNeighbors (ResultSet< DistanceType > &result, const ElementType *vec, const SearchParams &searchParams) const
Method that searches for nearest-neighbours.
Public Member Functions inherited from flann::NNIndex< Distance >
NNIndex (Distance d)
NNIndex (const IndexParams &params, Distance d)
NNIndex (const NNIndex &other)
virtual ~NNIndex ()
virtual void buildIndex (const Matrix< ElementType > &dataset)
virtual ElementType * getPoint (size_t id)
size_t size () const
size_t veclen () const
IndexParams getParameters () const
template<typename Archive >
void serialize (Archive &ar)
virtual int knnSearch (const Matrix< ElementType > &queries, Matrix< size_t > &indices, Matrix< DistanceType > &dists, size_t knn, const SearchParams &params) const
Perform k-nearest neighbor search.
int knnSearch (const Matrix< ElementType > &queries, Matrix< int > &indices, Matrix< DistanceType > &dists, size_t knn, const SearchParams &params) const
int knnSearch (const Matrix< ElementType > &queries, std::vector< std::vector< size_t > > &indices, std::vector< std::vector< DistanceType > > &dists, size_t knn, const SearchParams &params) const
Perform k-nearest neighbor search.
int knnSearch (const Matrix< ElementType > &queries, std::vector< std::vector< int > > &indices, std::vector< std::vector< DistanceType > > &dists, size_t knn, const SearchParams &params) const
int radiusSearch (const Matrix< ElementType > &queries, Matrix< size_t > &indices, Matrix< DistanceType > &dists, float radius, const SearchParams &params) const
Perform radius search.
int radiusSearch (const Matrix< ElementType > &queries, Matrix< int > &indices, Matrix< DistanceType > &dists, float radius, const SearchParams &params) const
int radiusSearch (const Matrix< ElementType > &queries, std::vector< std::vector< size_t > > &indices, std::vector< std::vector< DistanceType > > &dists, float radius, const SearchParams &params) const
Perform radius search.
int radiusSearch (const Matrix< ElementType > &queries, std::vector< std::vector< int > > &indices, std::vector< std::vector< DistanceType > > &dists, float radius, const SearchParams &params) const
Public Member Functions inherited from flann::IndexBase
virtual ~IndexBase ()
Protected Member Functions
void swap (CompositeIndex &other)
void buildIndexImpl ()
void freeIndex ()
Protected Member Functions inherited from flann::NNIndex< Distance >
size_t id_to_index (size_t id)
void indices_to_ids (const size_t *in, size_t *out, size_t size) const
void setDataset (const Matrix< ElementType > &dataset)
void extendDataset (const Matrix< ElementType > &new_points)
void cleanRemovedPoints ()
void swap (NNIndex &other)
Additional Inherited Members
Protected Attributes inherited from flann::NNIndex< Distance >
Distance distance_
size_t last_id_
size_t size_
size_t size_at_build_
size_t veclen_
IndexParams index_params_
bool removed_
DynamicBitset removed_points_
size_t removed_count_
std::vector< size_t > ids_
std::vector< ElementType * > points_
ElementType * data_ptr_
Detailed Description
template<typename Distance>
class flann::CompositeIndex< Distance >
This index builds a kd-tree index and a k-means index and performs nearest neighbour search both indexes. This gives a slight boost in search performance as some of the neighbours that are missed by one index are found by the other.
Definition at line 71 of file composite_index.h.
Member Typedef Documentation
BaseClass
template<typename Distance > typedef NNIndex<Distance> flann::CompositeIndex< Distance >::BaseClass
Definition at line 77 of file composite_index.h.
DistanceType
template<typename Distance > typedef Distance::ResultType flann::CompositeIndex< Distance >::DistanceType
Definition at line 75 of file composite_index.h.
ElementType
template<typename Distance > typedef Distance::ElementType flann::CompositeIndex< Distance >::ElementType
Definition at line 74 of file composite_index.h.
needs_kdtree_distance
template<typename Distance > typedef bool flann::CompositeIndex< Distance >::needs_kdtree_distance
Definition at line 79 of file composite_index.h.
Constructor & Destructor Documentation
CompositeIndex() [1/3]
template<typename Distance > flann::CompositeIndex< Distance >::CompositeIndex (const IndexParams & params = CompositeIndexParams(), Distance d = Distance()) inline
Index constructor
Parameters
inputData dataset containing the points to index
params Index parameters
d Distance functor
Returns
Definition at line 88 of file composite_index.h.
References params.
Referenced by flann::CompositeIndex< Distance >::clone().
CompositeIndex() [2/3]
template<typename Distance > flann::CompositeIndex< Distance >::CompositeIndex (const Matrix< ElementType > & inputData, const IndexParams & params = CompositeIndexParams(), Distance d = Distance()) inline
Definition at line 96 of file composite_index.h.
References params.
CompositeIndex() [3/3]
template<typename Distance > flann::CompositeIndex< Distance >::CompositeIndex (const CompositeIndex< Distance > & other) inline
Definition at line 103 of file composite_index.h.
~CompositeIndex()
template<typename Distance > virtual flann::CompositeIndex< Distance >::~CompositeIndex () inline virtual
Definition at line 114 of file composite_index.h.
Member Function Documentation
addPoints()
template<typename Distance > void flann::CompositeIndex< Distance >::addPoints (const Matrix< ElementType > & points, float rebuild_threshold = 2) inline virtual
Incrementally add points to the index.
Parameters
points Matrix with points to be added
rebuild_threshold
Reimplemented from flann::NNIndex< Distance >.
Definition at line 169 of file composite_index.h.
References points.
buildIndex()
template<typename Distance > void flann::CompositeIndex< Distance >::buildIndex () inline virtual
Builds the index.
Reimplemented from flann::NNIndex< Distance >.
Definition at line 161 of file composite_index.h.
References flann::Logger::info().
buildIndexImpl()
template<typename Distance > void flann::CompositeIndex< Distance >::buildIndexImpl () inline protected virtual
Implements flann::NNIndex< Distance >.
Definition at line 218 of file composite_index.h.
clone()
template<typename Distance > BaseClass* flann::CompositeIndex< Distance >::clone () const inline virtual
Implements flann::NNIndex< Distance >.
Definition at line 120 of file composite_index.h.
References flann::CompositeIndex< Distance >::CompositeIndex().
findNeighbors()
template<typename Distance > void flann::CompositeIndex< Distance >::findNeighbors (ResultSet< DistanceType > & result, const ElementType * vec, const SearchParams & searchParams) const inline virtual
Method that searches for nearest-neighbours.
Implements flann::NNIndex< Distance >.
Definition at line 205 of file composite_index.h.
References result.
freeIndex()
template<typename Distance > void flann::CompositeIndex< Distance >::freeIndex () inline protected virtual
Implements flann::NNIndex< Distance >.
Definition at line 223 of file composite_index.h.
getType()
template<typename Distance > flann_algorithm_t flann::CompositeIndex< Distance >::getType () const inline virtual
Returns
The index type
Implements flann::IndexBase.
Definition at line 128 of file composite_index.h.
References FLANN_INDEX_COMPOSITE.
loadIndex()
template<typename Distance > void flann::CompositeIndex< Distance >::loadIndex (FILE * stream) inline virtual
Loads the index from a stream.
Parameters
stream The stream from which the index is loaded
Implements flann::IndexBase.
Definition at line 196 of file composite_index.h.
operator=()
template<typename Distance > CompositeIndex& flann::CompositeIndex< Distance >::operator= (CompositeIndex< Distance > other) inline
Definition at line 108 of file composite_index.h.
References flann::CompositeIndex< Distance >::swap().
removePoint()
template<typename Distance > void flann::CompositeIndex< Distance >::removePoint (size_t id) inline virtual
Remove point from the index
Parameters
index Index of point to be removed
Reimplemented from flann::NNIndex< Distance >.
Definition at line 175 of file composite_index.h.
saveIndex()
template<typename Distance > void flann::CompositeIndex< Distance >::saveIndex (FILE * stream) inline virtual
Saves the index to a stream.
Parameters
stream The stream to save the index to
Implements flann::IndexBase.
Definition at line 186 of file composite_index.h.
size()
template<typename Distance > size_t flann::CompositeIndex< Distance >::size () const inline virtual
Returns
Size of the index
Implements flann::IndexBase.
Definition at line 136 of file composite_index.h.
swap()
template<typename Distance > void flann::CompositeIndex< Distance >::swap (CompositeIndex< Distance > & other) inline protected
Definition at line 212 of file composite_index.h.
References std::swap().
Referenced by flann::CompositeIndex< Distance >::operator=().
usedMemory()
template<typename Distance > int flann::CompositeIndex< Distance >::usedMemory () const inline virtual
Returns
The amount of memory (in bytes) used by the index.
Implements flann::IndexBase.
Definition at line 152 of file composite_index.h.
veclen()
template<typename Distance > size_t flann::CompositeIndex< Distance >::veclen () const inline virtual
Returns
The dimensionality of the features in this index.
Implements flann::IndexBase.
Definition at line 144 of file composite_index.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/algorithms/composite_index.h