ACloudViewer: colmap::SiftCPUFeatureMatcher Class Reference
colmap::SiftCPUFeatureMatcher Class Reference
#include <matching.h>
Public Types
typedef internal::FeatureMatcherData Input
typedef internal::FeatureMatcherData Output
Public Types inherited from colmap::Thread
enum { STARTED_CALLBACK = INT_MIN , FINISHED_CALLBACK }
Public Member Functions
SiftCPUFeatureMatcher (const SiftMatchingOptions &options, FeatureMatcherCache *cache, JobQueue< Input > *input_queue, JobQueue< Output > *output_queue)
Public Member Functions inherited from colmap::FeatureMatcherThread
FeatureMatcherThread (const SiftMatchingOptions &options, FeatureMatcherCache *cache)
void SetMaxNumMatches (const int max_num_matches)
Public Member Functions inherited from colmap::Thread
Thread ()
virtual ~Thread ()=default
virtual void Start ()
virtual void Stop ()
virtual void Pause ()
virtual void Resume ()
virtual void Wait ()
bool IsStarted ()
bool IsStopped ()
bool IsPaused ()
bool IsRunning ()
bool IsFinished ()
void BlockIfPaused ()
bool CheckValidSetup ()
void AddCallback (const int id, const std::function< void()> &func)
const Timer & GetTimer () const
Protected Member Functions
void Run () override
Protected Member Functions inherited from colmap::Thread
void RegisterCallback (const int id)
void Callback (const int id) const
std::thread::id GetThreadId () const
void SignalValidSetup ()
void SignalInvalidSetup ()
Protected Attributes
JobQueue< Input > * input_queue_
JobQueue< Output > * output_queue_
Protected Attributes inherited from colmap::FeatureMatcherThread
SiftMatchingOptions options_
FeatureMatcherCache * cache_
Detailed Description
Definition at line 218 of file matching.h.
Member Typedef Documentation
Input
typedef internal::FeatureMatcherData colmap::SiftCPUFeatureMatcher::Input
Definition at line 220 of file matching.h.
Output
typedef internal::FeatureMatcherData colmap::SiftCPUFeatureMatcher::Output
Definition at line 221 of file matching.h.
Constructor & Destructor Documentation
SiftCPUFeatureMatcher()
colmap::SiftCPUFeatureMatcher::SiftCPUFeatureMatcher (const SiftMatchingOptions & options, FeatureMatcherCache * cache, JobQueue< Input > * input_queue, JobQueue< Output > * output_queue)
Definition at line 374 of file matching.cc.
References colmap::SiftMatchingOptions::Check(), and colmap::FeatureMatcherThread::options_.
Member Function Documentation
Run()
void colmap::SiftCPUFeatureMatcher::Run () override protected virtual
Implements colmap::Thread.
Definition at line 384 of file matching.cc.
References colmap::FeatureMatcherThread::cache_, data, colmap::FeatureMatcherCache::ExistsDescriptors(), colmap::FeatureMatcherCache::GetDescriptors(), input_queue_, colmap::Thread::IsStopped(), colmap::MatchSiftFeaturesCPU(), colmap::FeatureMatcherThread::options_, output_queue_, and colmap::Thread::SignalValidSetup().
Member Data Documentation
input_queue_
JobQueue<Input>* colmap::SiftCPUFeatureMatcher::input_queue_ protected
Definition at line 231 of file matching.h.
Referenced by Run().
output_queue_
JobQueue<Output>* colmap::SiftCPUFeatureMatcher::output_queue_ protected
Definition at line 232 of file matching.h.
Referenced by Run().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/feature/matching.h
/root/ACloudViewer/libs/Reconstruction/src/feature/matching.cc