ACloudViewer: FlowLayout Class Reference
FlowLayout Class Reference
#include <flowlayout.h>
Public Member Functions
FlowLayout (QWidget *parent, int margin=-1, int hSpacing=-1, int vSpacing=-1)
FlowLayout (int margin=-1, int hSpacing=-1, int vSpacing=-1)
~FlowLayout ()
void clear ()
void addItem (QLayoutItem *item) Q_DECL_OVERRIDE
int horizontalSpacing () const
int verticalSpacing () const
Qt::Orientations expandingDirections () const Q_DECL_OVERRIDE
bool hasHeightForWidth () const Q_DECL_OVERRIDE
int heightForWidth (int) const Q_DECL_OVERRIDE
int count () const Q_DECL_OVERRIDE
QLayoutItem * itemAt (int index) const Q_DECL_OVERRIDE
QSize minimumSize () const Q_DECL_OVERRIDE
void setGeometry (const QRect &rect) Q_DECL_OVERRIDE
QSize sizeHint () const Q_DECL_OVERRIDE
QLayoutItem * takeAt (int index) Q_DECL_OVERRIDE
Detailed Description
Definition at line 16 of file flowlayout.h.
Constructor & Destructor Documentation
FlowLayout() [1/2]
FlowLayout::FlowLayout (QWidget * parent, int margin = -1, int hSpacing = -1, int vSpacing = -1) explicit
Definition at line 11 of file flowlayout.cpp.
FlowLayout() [2/2]
FlowLayout::FlowLayout (int margin = -1, int hSpacing = -1, int vSpacing = -1) explicit
Definition at line 16 of file flowlayout.cpp.
~FlowLayout()
FlowLayout::~FlowLayout ()
Definition at line 21 of file flowlayout.cpp.
References clear().
Member Function Documentation
addItem()
void FlowLayout::addItem (QLayoutItem * item)
Definition at line 28 of file flowlayout.cpp.
clear()
void FlowLayout::clear ()
Definition at line 23 of file flowlayout.cpp.
References takeAt().
Referenced by ~FlowLayout().
count()
int FlowLayout::count () const
Definition at line 46 of file flowlayout.cpp.
expandingDirections()
Qt::Orientations FlowLayout::expandingDirections () const
Definition at line 59 of file flowlayout.cpp.
hasHeightForWidth()
bool FlowLayout::hasHeightForWidth () const
Definition at line 67 of file flowlayout.cpp.
heightForWidth()
int FlowLayout::heightForWidth (int width) const
Definition at line 69 of file flowlayout.cpp.
References height, and width.
horizontalSpacing()
int FlowLayout::horizontalSpacing () const
Definition at line 30 of file flowlayout.cpp.
itemAt()
QLayoutItem * FlowLayout::itemAt (int index) const
Definition at line 48 of file flowlayout.cpp.
minimumSize()
QSize FlowLayout::minimumSize () const
Definition at line 81 of file flowlayout.cpp.
References size.
Referenced by sizeHint().
setGeometry()
void FlowLayout::setGeometry (const QRect & rect)
Definition at line 74 of file flowlayout.cpp.
sizeHint()
QSize FlowLayout::sizeHint () const
Definition at line 79 of file flowlayout.cpp.
References minimumSize().
takeAt()
QLayoutItem * FlowLayout::takeAt (int index)
Definition at line 52 of file flowlayout.cpp.
Referenced by clear().
verticalSpacing()
int FlowLayout::verticalSpacing () const
Definition at line 38 of file flowlayout.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/flowlayout.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/flowlayout.cpp