ACloudViewer: ccScalarFieldFromColorDlg Class Reference
ccScalarFieldFromColorDlg Class Reference
#include <ecvScalarFieldFromColorDlg.h>
Public Member Functions
ccScalarFieldFromColorDlg (QWidget *parent=0)
Default constructor.
bool getRStatus ()
Returns if to export R channel as SF.
bool getGStatus ()
Returns if to export G channel as SF.
bool getBStatus ()
Returns if to export B channel as SF.
bool getCompositeStatus ()
Returns if to export Composite channel as SF.
Detailed Description
Dialog to choose 2 scalar fields (SF) and one operation for arithmetics processing
Definition at line 16 of file ecvScalarFieldFromColorDlg.h.
Constructor & Destructor Documentation
ccScalarFieldFromColorDlg()
ccScalarFieldFromColorDlg::ccScalarFieldFromColorDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 20 of file ecvScalarFieldFromColorDlg.cpp.
Member Function Documentation
getBStatus()
bool ccScalarFieldFromColorDlg::getBStatus ()
Returns if to export B channel as SF.
Definition at line 33 of file ecvScalarFieldFromColorDlg.cpp.
Referenced by ccEntityAction::sfFromColor().
getCompositeStatus()
bool ccScalarFieldFromColorDlg::getCompositeStatus ()
Returns if to export Composite channel as SF.
Definition at line 37 of file ecvScalarFieldFromColorDlg.cpp.
Referenced by ccEntityAction::sfFromColor().
getGStatus()
bool ccScalarFieldFromColorDlg::getGStatus ()
Returns if to export G channel as SF.
Definition at line 29 of file ecvScalarFieldFromColorDlg.cpp.
Referenced by ccEntityAction::sfFromColor().
getRStatus()
bool ccScalarFieldFromColorDlg::getRStatus ()
Returns if to export R channel as SF.
Definition at line 25 of file ecvScalarFieldFromColorDlg.cpp.
Referenced by ccEntityAction::sfFromColor().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvScalarFieldFromColorDlg.h
/root/ACloudViewer/app/ecvScalarFieldFromColorDlg.cpp