ACloudViewer: flann::LinearIndex< Distance > Class Template Reference
flann::LinearIndex< Distance > Class Template Reference
#include <linear_index.h>
Public Types
typedef Distance::ElementType ElementType
typedef Distance::ResultType DistanceType
typedef NNIndex< Distance > BaseClass
Public Types inherited from flann::NNIndex< Distance >
typedef Distance::ElementType ElementType
typedef Distance::ResultType DistanceType
Public Member Functions
LinearIndex (const IndexParams &params=LinearIndexParams(), Distance d=Distance())
LinearIndex (const Matrix< ElementType > &input_data, const IndexParams &params=LinearIndexParams(), Distance d=Distance())
LinearIndex (const LinearIndex &other)
LinearIndex & operator= (LinearIndex other)
virtual ~LinearIndex ()
BaseClass * clone () const
void addPoints (const Matrix< ElementType > &points, float rebuild_threshold=2)
Incrementally add points to the index.
flann_algorithm_t getType () const
int usedMemory () const
template<typename Archive >
void serialize (Archive &ar)
void saveIndex (FILE *stream)
void loadIndex (FILE *stream)
void findNeighbors (ResultSet< DistanceType > &resultSet, const ElementType *vec, const SearchParams &) const
Public Member Functions inherited from flann::NNIndex< Distance >
NNIndex (Distance d)
NNIndex (const IndexParams &params, Distance d)
NNIndex (const NNIndex &other)
virtual ~NNIndex ()
virtual void buildIndex ()
virtual void buildIndex (const Matrix< ElementType > &dataset)
virtual void removePoint (size_t id)
virtual ElementType * getPoint (size_t id)
size_t size () const
size_t veclen () const
IndexParams getParameters () const
template<typename Archive >
void serialize (Archive &ar)
virtual int knnSearch (const Matrix< ElementType > &queries, Matrix< size_t > &indices, Matrix< DistanceType > &dists, size_t knn, const SearchParams &params) const
Perform k-nearest neighbor search.
int knnSearch (const Matrix< ElementType > &queries, Matrix< int > &indices, Matrix< DistanceType > &dists, size_t knn, const SearchParams &params) const
int knnSearch (const Matrix< ElementType > &queries, std::vector< std::vector< size_t > > &indices, std::vector< std::vector< DistanceType > > &dists, size_t knn, const SearchParams &params) const
Perform k-nearest neighbor search.
int knnSearch (const Matrix< ElementType > &queries, std::vector< std::vector< int > > &indices, std::vector< std::vector< DistanceType > > &dists, size_t knn, const SearchParams &params) const
int radiusSearch (const Matrix< ElementType > &queries, Matrix< size_t > &indices, Matrix< DistanceType > &dists, float radius, const SearchParams &params) const
Perform radius search.
int radiusSearch (const Matrix< ElementType > &queries, Matrix< int > &indices, Matrix< DistanceType > &dists, float radius, const SearchParams &params) const
int radiusSearch (const Matrix< ElementType > &queries, std::vector< std::vector< size_t > > &indices, std::vector< std::vector< DistanceType > > &dists, float radius, const SearchParams &params) const
Perform radius search.
int radiusSearch (const Matrix< ElementType > &queries, std::vector< std::vector< int > > &indices, std::vector< std::vector< DistanceType > > &dists, float radius, const SearchParams &params) const
Public Member Functions inherited from flann::IndexBase
virtual ~IndexBase ()
Protected Member Functions
void buildIndexImpl ()
void freeIndex ()
Protected Member Functions inherited from flann::NNIndex< Distance >
size_t id_to_index (size_t id)
void indices_to_ids (const size_t *in, size_t *out, size_t size) const
void setDataset (const Matrix< ElementType > &dataset)
void extendDataset (const Matrix< ElementType > &new_points)
void cleanRemovedPoints ()
void swap (NNIndex &other)
Additional Inherited Members
Protected Attributes inherited from flann::NNIndex< Distance >
Distance distance_
size_t last_id_
size_t size_
size_t size_at_build_
size_t veclen_
IndexParams index_params_
bool removed_
DynamicBitset removed_points_
size_t removed_count_
std::vector< size_t > ids_
std::vector< ElementType * > points_
ElementType * data_ptr_
Detailed Description
template<typename Distance>
class flann::LinearIndex< Distance >
Definition at line 49 of file linear_index.h.
Member Typedef Documentation
BaseClass
template<typename Distance > typedef NNIndex<Distance> flann::LinearIndex< Distance >::BaseClass
Definition at line 56 of file linear_index.h.
DistanceType
template<typename Distance > typedef Distance::ResultType flann::LinearIndex< Distance >::DistanceType
Definition at line 54 of file linear_index.h.
ElementType
template<typename Distance > typedef Distance::ElementType flann::LinearIndex< Distance >::ElementType
Definition at line 53 of file linear_index.h.
Constructor & Destructor Documentation
LinearIndex() [1/3]
template<typename Distance > flann::LinearIndex< Distance >::LinearIndex (const IndexParams & params = LinearIndexParams(), Distance d = Distance()) inline
Definition at line 58 of file linear_index.h.
Referenced by flann::LinearIndex< Distance >::clone().
LinearIndex() [2/3]
template<typename Distance > flann::LinearIndex< Distance >::LinearIndex (const Matrix< ElementType > & input_data, const IndexParams & params = LinearIndexParams(), Distance d = Distance()) inline
Definition at line 63 of file linear_index.h.
References flann::NNIndex< Distance >::setDataset().
LinearIndex() [3/3]
template<typename Distance > flann::LinearIndex< Distance >::LinearIndex (const LinearIndex< Distance > & other) inline
Definition at line 69 of file linear_index.h.
~LinearIndex()
template<typename Distance > virtual flann::LinearIndex< Distance >::~LinearIndex () inline virtual
Definition at line 79 of file linear_index.h.
Member Function Documentation
addPoints()
template<typename Distance > void flann::LinearIndex< Distance >::addPoints (const Matrix< ElementType > & points, float rebuild_threshold = 2) inline virtual
Incrementally add points to the index.
Parameters
points Matrix with points to be added
rebuild_threshold
Reimplemented from flann::NNIndex< Distance >.
Definition at line 88 of file linear_index.h.
References flann::NNIndex< Distance >::extendDataset(), points, and flann::NNIndex< Distance >::veclen_.
buildIndexImpl()
template<typename Distance > void flann::LinearIndex< Distance >::buildIndexImpl () inline protected virtual
Implements flann::NNIndex< Distance >.
Definition at line 146 of file linear_index.h.
clone()
template<typename Distance > BaseClass* flann::LinearIndex< Distance >::clone () const inline virtual
Implements flann::NNIndex< Distance >.
Definition at line 83 of file linear_index.h.
References flann::LinearIndex< Distance >::LinearIndex().
findNeighbors()
template<typename Distance > void flann::LinearIndex< Distance >::findNeighbors (ResultSet< DistanceType > & resultSet, const ElementType * vec, const SearchParams &) const inline virtual
Implements flann::NNIndex< Distance >.
Definition at line 129 of file linear_index.h.
References flann::ResultSet< DistanceType >::addPoint(), dist(), flann::NNIndex< Distance >::distance_, flann::NNIndex< Distance >::points_, flann::NNIndex< Distance >::removed_, flann::NNIndex< Distance >::removed_points_, flann::DynamicBitset::test(), and flann::NNIndex< Distance >::veclen_.
freeIndex()
template<typename Distance > void flann::LinearIndex< Distance >::freeIndex () inline protected virtual
Implements flann::NNIndex< Distance >.
Definition at line 151 of file linear_index.h.
getType()
template<typename Distance > flann_algorithm_t flann::LinearIndex< Distance >::getType () const inline virtual
Implements flann::IndexBase.
Definition at line 94 of file linear_index.h.
References FLANN_INDEX_LINEAR.
Referenced by flann::LinearIndex< Distance >::serialize().
loadIndex()
template<typename Distance > void flann::LinearIndex< Distance >::loadIndex (FILE * stream) inline virtual
Implements flann::IndexBase.
Definition at line 123 of file linear_index.h.
operator=()
template<typename Distance > LinearIndex& flann::LinearIndex< Distance >::operator= (LinearIndex< Distance > other) inline
Definition at line 73 of file linear_index.h.
References flann::NNIndex< Distance >::swap().
saveIndex()
template<typename Distance > void flann::LinearIndex< Distance >::saveIndex (FILE * stream) inline virtual
Implements flann::IndexBase.
Definition at line 117 of file linear_index.h.
serialize()
template<typename Distance > template<typename Archive > void flann::LinearIndex< Distance >::serialize (Archive & ar) inline
Definition at line 106 of file linear_index.h.
References flann::LinearIndex< Distance >::getType(), and flann::NNIndex< Distance >::index_params_.
usedMemory()
template<typename Distance > int flann::LinearIndex< Distance >::usedMemory () const inline virtual
Implements flann::IndexBase.
Definition at line 100 of file linear_index.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/algorithms/linear_index.h