ACloudViewer: Mouse3DInput Class Reference
Mouse3DInput Class Reference
3DxWare driver wrapper for 3D mouse handling
#include <Mouse3DInput.h>
Public Types
enum VirtualKey {
V3DK_INVALID = 0 , V3DK_MENU = 1 , V3DK_FIT , V3DK_TOP ,
V3DK_LEFT , V3DK_RIGHT , V3DK_FRONT , V3DK_BOTTOM ,
V3DK_BACK , V3DK_CW , V3DK_CCW , V3DK_ISO1 ,
V3DK_ISO2 , V3DK_1 , V3DK_2 , V3DK_3 ,
V3DK_4 , V3DK_5 , V3DK_6 , V3DK_7 ,
V3DK_8 , V3DK_9 , V3DK_10 , V3DK_ESC ,
V3DK_ALT , V3DK_SHIFT , V3DK_CTRL , V3DK_ROTATE ,
V3DK_PANZOOM , V3DK_DOMINANT , V3DK_PLUS , V3DK_MINUS
}
Default key codes.
enum V3DCMD {
V3DCMD_NOOP = 0 , V3DCMD_MENU_OPTIONS = 1 , V3DCMD_VIEW_FIT = 2 , V3DCMD_VIEW_TOP = 3 ,
V3DCMD_VIEW_LEFT = 4 , V3DCMD_VIEW_RIGHT = 5 , V3DCMD_VIEW_FRONT = 6 , V3DCMD_VIEW_BOTTOM = 7 ,
V3DCMD_VIEW_BACK = 8 , V3DCMD_VIEW_ROLLCW = 9 , V3DCMD_VIEW_ROLLCCW = 10 , V3DCMD_VIEW_ISO1 = 11 ,
V3DCMD_VIEW_ISO2 = 12 , V3DCMD_KEY_F1 = 13 , V3DCMD_KEY_F2 = 14 , V3DCMD_KEY_F3 = 15 ,
V3DCMD_KEY_F4 = 16 , V3DCMD_KEY_F5 = 17 , V3DCMD_KEY_F6 = 18 , V3DCMD_KEY_F7 = 19 ,
V3DCMD_KEY_F8 = 20 , V3DCMD_KEY_F9 = 21 , V3DCMD_KEY_F10 = 22 , V3DCMD_KEY_F11 = 23 ,
V3DCMD_KEY_F12 = 24 , V3DCMD_KEY_ESC = 25 , V3DCMD_KEY_ALT = 26 , V3DCMD_KEY_SHIFT = 27 ,
V3DCMD_KEY_CTRL = 28 , V3DCMD_FILTER_ROTATE = 29 , V3DCMD_FILTER_PANZOOM = 30 , V3DCMD_FILTER_DOMINANT = 31 ,
V3DCMD_SCALE_PLUS = 32 , V3DCMD_SCALE_MINUS = 33 , V3DCMD_VIEW_SPINCW = 34 , V3DCMD_VIEW_SPINCCW = 35 ,
V3DCMD_VIEW_TILTCW = 36 , V3DCMD_VIEW_TILTCCW = 37 , V3DCMD_MENU_POPUP = 38 , V3DCMD_MENU_BUTTONMAPPINGEDITOR = 39 ,
V3DCMD_MENU_ADVANCEDSETTINGSEDITOR = 40 , V3DCMD_MOTIONMACRO_ZOOM = 41 , V3DCMD_MOTIONMACRO_ZOOMOUT_CURSORTOCENTER = 42 , V3DCMD_MOTIONMACRO_ZOOMIN_CURSORTOCENTER = 43 ,
V3DCMD_MOTIONMACRO_ZOOMOUT_CENTERTOCENTER = 44 , V3DCMD_MOTIONMACRO_ZOOMIN_CENTERTOCENTER = 45 , V3DCMD_MOTIONMACRO_ZOOMOUT_CURSORTOCURSOR = 46 , V3DCMD_MOTIONMACRO_ZOOMIN_CURSORTOCURSOR = 47 ,
V3DCMD_VIEW_QZ_IN = 48 , V3DCMD_VIEW_QZ_OUT = 49 , V3DCMD_KEY_ENTER = 50 , V3DCMD_KEY_DELETE = 51 ,
V3DCMD_KEY_F13 = 52 , V3DCMD_KEY_F14 = 53 , V3DCMD_KEY_F15 = 54 , V3DCMD_KEY_F16 = 55 ,
V3DCMD_KEY_F17 = 56 , V3DCMD_KEY_F18 = 57 , V3DCMD_KEY_F19 = 58 , V3DCMD_KEY_F20 = 59 ,
V3DCMD_KEY_F21 = 60 , V3DCMD_KEY_F22 = 61 , V3DCMD_KEY_F23 = 62 , V3DCMD_KEY_F24 = 63 ,
V3DCMD_KEY_F25 = 64 , V3DCMD_KEY_F26 = 65 , V3DCMD_KEY_F27 = 66 , V3DCMD_KEY_F28 = 67 ,
V3DCMD_KEY_F29 = 68 , V3DCMD_KEY_F30 = 69 , V3DCMD_KEY_F31 = 70 , V3DCMD_KEY_F32 = 71 ,
V3DCMD_KEY_F33 = 72 , V3DCMD_KEY_F34 = 73 , V3DCMD_KEY_F35 = 74 , V3DCMD_KEY_F36 = 75 ,
V3DCMD_VIEW_1 = 76 , V3DCMD_VIEW_2 = 77 , V3DCMD_VIEW_3 = 78 , V3DCMD_VIEW_4 = 79 ,
V3DCMD_VIEW_5 = 80 , V3DCMD_VIEW_6 = 81 , V3DCMD_VIEW_7 = 82 , V3DCMD_VIEW_8 = 83 ,
V3DCMD_VIEW_9 = 84 , V3DCMD_VIEW_10 = 85 , V3DCMD_VIEW_11 = 86 , V3DCMD_VIEW_12 = 87 ,
V3DCMD_VIEW_13 = 88 , V3DCMD_VIEW_14 = 89 , V3DCMD_VIEW_15 = 90 , V3DCMD_VIEW_16 = 91 ,
V3DCMD_VIEW_17 = 92 , V3DCMD_VIEW_18 = 93 , V3DCMD_VIEW_19 = 94 , V3DCMD_VIEW_20 = 95 ,
V3DCMD_VIEW_21 = 96 , V3DCMD_VIEW_22 = 97 , V3DCMD_VIEW_23 = 98 , V3DCMD_VIEW_24 = 99 ,
V3DCMD_VIEW_25 = 100 , V3DCMD_VIEW_26 = 101 , V3DCMD_VIEW_27 = 102 , V3DCMD_VIEW_28 = 103 ,
V3DCMD_VIEW_29 = 104 , V3DCMD_VIEW_30 = 105 , V3DCMD_VIEW_31 = 106 , V3DCMD_VIEW_32 = 107 ,
V3DCMD_VIEW_33 = 108 , V3DCMD_VIEW_34 = 109 , V3DCMD_VIEW_35 = 110 , V3DCMD_VIEW_36 = 111 ,
V3DCMD_SAVE_VIEW_1 = 112 , V3DCMD_SAVE_VIEW_2 = 113 , V3DCMD_SAVE_VIEW_3 = 114 , V3DCMD_SAVE_VIEW_4 = 115 ,
V3DCMD_SAVE_VIEW_5 = 116 , V3DCMD_SAVE_VIEW_6 = 117 , V3DCMD_SAVE_VIEW_7 = 118 , V3DCMD_SAVE_VIEW_8 = 119 ,
V3DCMD_SAVE_VIEW_9 = 120 , V3DCMD_SAVE_VIEW_10 = 121 , V3DCMD_SAVE_VIEW_11 = 122 , V3DCMD_SAVE_VIEW_12 = 123 ,
V3DCMD_SAVE_VIEW_13 = 124 , V3DCMD_SAVE_VIEW_14 = 125 , V3DCMD_SAVE_VIEW_15 = 126 , V3DCMD_SAVE_VIEW_16 = 127 ,
V3DCMD_SAVE_VIEW_17 = 128 , V3DCMD_SAVE_VIEW_18 = 129 , V3DCMD_SAVE_VIEW_19 = 130 , V3DCMD_SAVE_VIEW_20 = 131 ,
V3DCMD_SAVE_VIEW_21 = 132 , V3DCMD_SAVE_VIEW_22 = 133 , V3DCMD_SAVE_VIEW_23 = 134 , V3DCMD_SAVE_VIEW_24 = 135 ,
V3DCMD_SAVE_VIEW_25 = 136 , V3DCMD_SAVE_VIEW_26 = 137 , V3DCMD_SAVE_VIEW_27 = 138 , V3DCMD_SAVE_VIEW_28 = 139 ,
V3DCMD_SAVE_VIEW_29 = 140 , V3DCMD_SAVE_VIEW_30 = 141 , V3DCMD_SAVE_VIEW_31 = 142 , V3DCMD_SAVE_VIEW_32 = 143 ,
V3DCMD_SAVE_VIEW_33 = 144 , V3DCMD_SAVE_VIEW_34 = 145 , V3DCMD_SAVE_VIEW_35 = 146 , V3DCMD_SAVE_VIEW_36 = 147 ,
V3DCMD_KEY_TAB = 148 , V3DCMD_KEY_SPACE = 149 , V3DCMD_MENU_1 = 150 , V3DCMD_MENU_2 = 151 ,
V3DCMD_MENU_3 = 152 , V3DCMD_MENU_4 = 153 , V3DCMD_MENU_5 = 154 , V3DCMD_MENU_6 = 155 ,
V3DCMD_MENU_7 = 156 , V3DCMD_MENU_8 = 157 , V3DCMD_MENU_9 = 158 , V3DCMD_MENU_10 = 159 ,
V3DCMD_MENU_11 = 160 , V3DCMD_MENU_12 = 161 , V3DCMD_MENU_13 = 162 , V3DCMD_MENU_14 = 163 ,
V3DCMD_MENU_15 = 164 , V3DCMD_MENU_16 = 165
}
Signals
void sigMove3d (std::vector< float > &motionData)
void sigReleased ()
void sigOn3dmouseKeyDown (int virtualKeyCode)
void sigOn3dmouseCMDKeyDown (int virtualCMDCode)
void sigOn3dmouseKeyUp (int virtualKeyCode)
void sigOn3dmouseCMDKeyUp (int virtualCMDCode)
Public Member Functions
Mouse3DInput (QObject *parent)
Default constructor.
virtual ~Mouse3DInput ()
Destructor.
bool connect (QWidget *mainWidget, QString appName)
Attempts to connect with the 3DxWare driver.
void disconnectDriver ()
Disconnects from the 3DxWare driver.
bool onSiEvent (void *siGetEventData)
Called when a new system message is available.
Static Public Member Functions
static void GetMatrix (const std::vector< float > &motionData, ccGLMatrixd &mat)
Converts 'rotation' part of motion data to a rotation matrix.
static void Apply (const std::vector< float > &motionData, ccGLWindow *win)
Applies motion data to a given 3D window.
Protected Member Functions
virtual void move3d (std::vector< float > &motionData)
Called with the processed motion data when a 3D mouse event is received.
virtual void on3dmouseKeyDown (int virtualKeyCode)
Called when a 3D mouse key is pressed.
virtual void on3dmouseCMDKeyDown (int virtualCMDCode)
Called when a 3D mouse key is pressed after translation to CMD.
virtual void on3dmouseKeyUp (int virtualKeyCode)
Called when a 3D mouse key is released.
virtual void on3dmouseCMDKeyUp (int virtualCMDCode)
Called when a 3D mouse key is released after translation to CMD.
Protected Attributes
void * m_siHandle
3DxWare handle
Detailed Description
3DxWare driver wrapper for 3D mouse handling
Definition at line 43 of file Mouse3DInput.h.
Member Enumeration Documentation
V3DCMD
enum Mouse3DInput::V3DCMD
Enumerator
V3DCMD_NOOP
V3DCMD_MENU_OPTIONS
V3DCMD_VIEW_FIT
V3DCMD_VIEW_TOP
V3DCMD_VIEW_LEFT
V3DCMD_VIEW_RIGHT
V3DCMD_VIEW_FRONT
V3DCMD_VIEW_BOTTOM
V3DCMD_VIEW_BACK
V3DCMD_VIEW_ROLLCW
V3DCMD_VIEW_ROLLCCW
V3DCMD_VIEW_ISO1
V3DCMD_VIEW_ISO2
V3DCMD_KEY_F1
V3DCMD_KEY_F2
V3DCMD_KEY_F3
V3DCMD_KEY_F4
V3DCMD_KEY_F5
V3DCMD_KEY_F6
V3DCMD_KEY_F7
V3DCMD_KEY_F8
V3DCMD_KEY_F9
V3DCMD_KEY_F10
V3DCMD_KEY_F11
V3DCMD_KEY_F12
V3DCMD_KEY_ESC
V3DCMD_KEY_ALT
V3DCMD_KEY_SHIFT
V3DCMD_KEY_CTRL
V3DCMD_FILTER_ROTATE
V3DCMD_FILTER_PANZOOM
V3DCMD_FILTER_DOMINANT
V3DCMD_SCALE_PLUS
V3DCMD_SCALE_MINUS
V3DCMD_VIEW_SPINCW
V3DCMD_VIEW_SPINCCW
V3DCMD_VIEW_TILTCW
V3DCMD_VIEW_TILTCCW
V3DCMD_MENU_POPUP
V3DCMD_MENU_BUTTONMAPPINGEDITOR
V3DCMD_MENU_ADVANCEDSETTINGSEDITOR
V3DCMD_MOTIONMACRO_ZOOM
V3DCMD_MOTIONMACRO_ZOOMOUT_CURSORTOCENTER
V3DCMD_MOTIONMACRO_ZOOMIN_CURSORTOCENTER
V3DCMD_MOTIONMACRO_ZOOMOUT_CENTERTOCENTER
V3DCMD_MOTIONMACRO_ZOOMIN_CENTERTOCENTER
V3DCMD_MOTIONMACRO_ZOOMOUT_CURSORTOCURSOR
V3DCMD_MOTIONMACRO_ZOOMIN_CURSORTOCURSOR
V3DCMD_VIEW_QZ_IN
V3DCMD_VIEW_QZ_OUT
V3DCMD_KEY_ENTER
V3DCMD_KEY_DELETE
V3DCMD_KEY_F13
V3DCMD_KEY_F14
V3DCMD_KEY_F15
V3DCMD_KEY_F16
V3DCMD_KEY_F17
V3DCMD_KEY_F18
V3DCMD_KEY_F19
V3DCMD_KEY_F20
V3DCMD_KEY_F21
V3DCMD_KEY_F22
V3DCMD_KEY_F23
V3DCMD_KEY_F24
V3DCMD_KEY_F25
V3DCMD_KEY_F26
V3DCMD_KEY_F27
V3DCMD_KEY_F28
V3DCMD_KEY_F29
V3DCMD_KEY_F30
V3DCMD_KEY_F31
V3DCMD_KEY_F32
V3DCMD_KEY_F33
V3DCMD_KEY_F34
V3DCMD_KEY_F35
V3DCMD_KEY_F36
V3DCMD_VIEW_1
V3DCMD_VIEW_2
V3DCMD_VIEW_3
V3DCMD_VIEW_4
V3DCMD_VIEW_5
V3DCMD_VIEW_6
V3DCMD_VIEW_7
V3DCMD_VIEW_8
V3DCMD_VIEW_9
V3DCMD_VIEW_10
V3DCMD_VIEW_11
V3DCMD_VIEW_12
V3DCMD_VIEW_13
V3DCMD_VIEW_14
V3DCMD_VIEW_15
V3DCMD_VIEW_16
V3DCMD_VIEW_17
V3DCMD_VIEW_18
V3DCMD_VIEW_19
V3DCMD_VIEW_20
V3DCMD_VIEW_21
V3DCMD_VIEW_22
V3DCMD_VIEW_23
V3DCMD_VIEW_24
V3DCMD_VIEW_25
V3DCMD_VIEW_26
V3DCMD_VIEW_27
V3DCMD_VIEW_28
V3DCMD_VIEW_29
V3DCMD_VIEW_30
V3DCMD_VIEW_31
V3DCMD_VIEW_32
V3DCMD_VIEW_33
V3DCMD_VIEW_34
V3DCMD_VIEW_35
V3DCMD_VIEW_36
V3DCMD_SAVE_VIEW_1
V3DCMD_SAVE_VIEW_2
V3DCMD_SAVE_VIEW_3
V3DCMD_SAVE_VIEW_4
V3DCMD_SAVE_VIEW_5
V3DCMD_SAVE_VIEW_6
V3DCMD_SAVE_VIEW_7
V3DCMD_SAVE_VIEW_8
V3DCMD_SAVE_VIEW_9
V3DCMD_SAVE_VIEW_10
V3DCMD_SAVE_VIEW_11
V3DCMD_SAVE_VIEW_12
V3DCMD_SAVE_VIEW_13
V3DCMD_SAVE_VIEW_14
V3DCMD_SAVE_VIEW_15
V3DCMD_SAVE_VIEW_16
V3DCMD_SAVE_VIEW_17
V3DCMD_SAVE_VIEW_18
V3DCMD_SAVE_VIEW_19
V3DCMD_SAVE_VIEW_20
V3DCMD_SAVE_VIEW_21
V3DCMD_SAVE_VIEW_22
V3DCMD_SAVE_VIEW_23
V3DCMD_SAVE_VIEW_24
V3DCMD_SAVE_VIEW_25
V3DCMD_SAVE_VIEW_26
V3DCMD_SAVE_VIEW_27
V3DCMD_SAVE_VIEW_28
V3DCMD_SAVE_VIEW_29
V3DCMD_SAVE_VIEW_30
V3DCMD_SAVE_VIEW_31
V3DCMD_SAVE_VIEW_32
V3DCMD_SAVE_VIEW_33
V3DCMD_SAVE_VIEW_34
V3DCMD_SAVE_VIEW_35
V3DCMD_SAVE_VIEW_36
V3DCMD_KEY_TAB
V3DCMD_KEY_SPACE
V3DCMD_MENU_1
V3DCMD_MENU_2
V3DCMD_MENU_3
V3DCMD_MENU_4
V3DCMD_MENU_5
V3DCMD_MENU_6
V3DCMD_MENU_7
V3DCMD_MENU_8
V3DCMD_MENU_9
V3DCMD_MENU_10
V3DCMD_MENU_11
V3DCMD_MENU_12
V3DCMD_MENU_13
V3DCMD_MENU_14
V3DCMD_MENU_15
V3DCMD_MENU_16
Definition at line 93 of file Mouse3DInput.h.
VirtualKey
enum Mouse3DInput::VirtualKey
Default key codes.
Enumerator
V3DK_INVALID
V3DK_MENU
V3DK_FIT
V3DK_TOP
V3DK_LEFT
V3DK_RIGHT
V3DK_FRONT
V3DK_BOTTOM
V3DK_BACK
V3DK_CW
V3DK_CCW
V3DK_ISO1
V3DK_ISO2
V3DK_1
V3DK_2
V3DK_3
V3DK_4
V3DK_5
V3DK_6
V3DK_7
V3DK_8
V3DK_9
V3DK_10
V3DK_ESC
V3DK_ALT
V3DK_SHIFT
V3DK_CTRL
V3DK_ROTATE
V3DK_PANZOOM
V3DK_DOMINANT
V3DK_PLUS
V3DK_MINUS
Definition at line 58 of file Mouse3DInput.h.
Constructor & Destructor Documentation
Mouse3DInput()
Mouse3DInput::Mouse3DInput (QObject * parent) explicit
Default constructor.
Definition at line 59 of file Mouse3DInput.cpp.
References s_mouseInputInstance.
~Mouse3DInput()
Mouse3DInput::~Mouse3DInput () virtual
Destructor.
Definition at line 66 of file Mouse3DInput.cpp.
References s_mouseInputInstance.
Member Function Documentation
Apply()
void Mouse3DInput::Apply (const std::vector< float > & motionData, ccGLWindow * win) static
Applies motion data to a given 3D window.
Definition at line 268 of file Mouse3DInput.cpp.
References ecvViewportParameters::computeWidthAtFocalDist(), ccGLMatrixTpl< T >::getColumnAsVec3D(), ecvViewportParameters::getFocalDistance(), GetMatrix(), cloudViewer::GreaterThanEpsilon(), ccGLMatrixTpl< T >::initFromParameters(), ccGLMatrixTpl< T >::inverse(), ecvViewportParameters::objectCenteredView, ecvViewportParameters::perspectiveView, ecvViewportParameters::setFocalDistance(), and X.
connect()
bool Mouse3DInput::connect (QWidget * mainWidget, QString appName)
Attempts to connect with the 3DxWare driver.
Definition at line 73 of file Mouse3DInput.cpp.
References m_siHandle, name, CVLog::Print(), s_rawInputEventFilter, and CVLog::Warning().
disconnectDriver()
void Mouse3DInput::disconnectDriver ()
Disconnects from the 3DxWare driver.
Definition at line 145 of file Mouse3DInput.cpp.
References m_siHandle, and s_rawInputEventFilter.
GetMatrix()
void Mouse3DInput::GetMatrix (const std::vector< float > & motionData, ccGLMatrixd & mat) static
Converts 'rotation' part of motion data to a rotation matrix.
Definition at line 253 of file Mouse3DInput.cpp.
References ccGLMatrixTpl< T >::getColumn().
Referenced by Apply().
move3d()
void Mouse3DInput::move3d (std::vector< float > & motionData) protected virtual
Called with the processed motion data when a 3D mouse event is received.
The default implementation emits a sigMove3d signal with the motion data
Definition at line 233 of file Mouse3DInput.cpp.
References sigMove3d().
Referenced by onSiEvent().
on3dmouseCMDKeyDown()
void Mouse3DInput::on3dmouseCMDKeyDown (int virtualCMDCode) protected virtual
Called when a 3D mouse key is pressed after translation to CMD.
The default implementation emits a sigOn3dmouseKeyDown signal with the key code.
Definition at line 241 of file Mouse3DInput.cpp.
References sigOn3dmouseCMDKeyDown().
Referenced by onSiEvent().
on3dmouseCMDKeyUp()
void Mouse3DInput::on3dmouseCMDKeyUp (int virtualCMDCode) protected virtual
Called when a 3D mouse key is released after translation to CMD.
The default implementation emits a sigOn3dmouseKeyUp signal with the key code.
Definition at line 249 of file Mouse3DInput.cpp.
References sigOn3dmouseCMDKeyUp().
Referenced by onSiEvent().
on3dmouseKeyDown()
void Mouse3DInput::on3dmouseKeyDown (int virtualKeyCode) protected virtual
Called when a 3D mouse key is pressed.
The default implementation emits a sigOn3dmouseKeyDown signal with the key code.
Definition at line 237 of file Mouse3DInput.cpp.
References sigOn3dmouseKeyDown().
Referenced by onSiEvent().
on3dmouseKeyUp()
void Mouse3DInput::on3dmouseKeyUp (int virtualKeyCode) protected virtual
Called when a 3D mouse key is released.
The default implementation emits a sigOn3dmouseKeyUp signal with the key code.
Definition at line 245 of file Mouse3DInput.cpp.
References sigOn3dmouseKeyUp().
Referenced by onSiEvent().
onSiEvent()
bool Mouse3DInput::onSiEvent (void * siGetEventData)
Called when a new system message is available.
For 'internal' use only
3DxWare data event
Definition at line 154 of file Mouse3DInput.cpp.
References c_3dmouseAngularVelocity, m_siHandle, move3d(), on3dmouseCMDKeyDown(), on3dmouseCMDKeyUp(), on3dmouseKeyDown(), on3dmouseKeyUp(), sigReleased(), and V3DCMD_MENU_OPTIONS.
Referenced by RawInputEventFilter::nativeEventFilter().
sigMove3d
void Mouse3DInput::sigMove3d (std::vector< float > & motionData) signal
Referenced by move3d().
sigOn3dmouseCMDKeyDown
void Mouse3DInput::sigOn3dmouseCMDKeyDown (int virtualCMDCode) signal
Referenced by on3dmouseCMDKeyDown().
sigOn3dmouseCMDKeyUp
void Mouse3DInput::sigOn3dmouseCMDKeyUp (int virtualCMDCode) signal
Referenced by on3dmouseCMDKeyUp().
sigOn3dmouseKeyDown
void Mouse3DInput::sigOn3dmouseKeyDown (int virtualKeyCode) signal
Referenced by on3dmouseKeyDown().
sigOn3dmouseKeyUp
void Mouse3DInput::sigOn3dmouseKeyUp (int virtualKeyCode) signal
Referenced by on3dmouseKeyUp().
sigReleased
void Mouse3DInput::sigReleased () signal
Referenced by onSiEvent().
Member Data Documentation
m_siHandle
void* Mouse3DInput::m_siHandle protected
3DxWare handle
Definition at line 315 of file Mouse3DInput.h.
Referenced by connect(), disconnectDriver(), and onSiEvent().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/CVAppCommon/devices/3dConnexion/Mouse3DInput.h
/root/ACloudViewer/libs/CVAppCommon/devices/3dConnexion/Mouse3DInput.cpp