ACloudViewer: cloudViewer::OptionsParser Class Reference
cloudViewer::OptionsParser Class Reference
#include <option_utils.h>
Public Member Functions
OptionsParser ()
~OptionsParser ()
void reset ()
bool parseOptions ()
bool parseOptions (int &argc, char **&argv)
int getArgc () const
char ** getArgv ()
template<typename T >
void registerOption (const std::string &name, const T *option)
void addExtractionOptions (const colmap::ImageReaderOptions &image_reader_options, const colmap::SiftExtractionOptions &sift_extraction_options)
void addMatchingOptions (const colmap::SiftMatchingOptions &sift_matching_options)
void addExhaustiveMatchingOptions (const colmap::SiftMatchingOptions &sift_matching_options, const colmap::ExhaustiveMatchingOptions &exhaustive_matching_options)
void addSequentialMatchingOptions (const colmap::SiftMatchingOptions &sift_matching_options, const colmap::SequentialMatchingOptions &sequential_matching_options)
void addSpatialMatchingOptions (const colmap::SiftMatchingOptions &sift_matching_options, const colmap::SpatialMatchingOptions &spatial_matching_options)
void addTransitiveMatchingOptions (const colmap::SiftMatchingOptions &sift_matching_options, const colmap::TransitiveMatchingOptions &transitive_matching_options)
void addVocabTreeMatchingOptions (const colmap::SiftMatchingOptions &sift_matching_options, const colmap::VocabTreeMatchingOptions &vocab_tree_matching_options)
void addImagePairsMatchingOptions (const colmap::SiftMatchingOptions &sift_matching_options, const colmap::ImagePairsMatchingOptions &image_pairs_matching_options)
void addMapperOptions (const colmap::IncrementalMapperOptions &incremental_mapper_options)
void addBundleAdjustmentOptions (const colmap::BundleAdjustmentOptions &bundle_adjustment_options)
void addPatchMatchStereoOptions (const colmap::mvs::PatchMatchOptions &patch_match_options)
void addStereoFusionOptions (const colmap::mvs::StereoFusionOptions &stereo_fusion_options)
void addPoissonMeshingOptions (const colmap::mvs::PoissonMeshingOptions &poisson_meshing_options)
void addDelaunayMeshingOptions (const colmap::mvs::DelaunayMeshingOptions &delaunay_meshing_options)
Static Public Member Functions
static void ReleaseOptions (int argc, char **argv)
static void SetValue (const std::string &value, int argc_, char **argv_)
Detailed Description
Definition at line 27 of file option_utils.h.
Constructor & Destructor Documentation
OptionsParser()
cloudViewer::OptionsParser::OptionsParser ()
Definition at line 12 of file option_utils.cpp.
References reset().
~OptionsParser()
cloudViewer::OptionsParser::~OptionsParser () inline
Definition at line 30 of file option_utils.h.
References reset().
Member Function Documentation
addBundleAdjustmentOptions()
void cloudViewer::OptionsParser::addBundleAdjustmentOptions (const colmap::BundleAdjustmentOptions & bundle_adjustment_options)
Definition at line 396 of file option_utils.cpp.
References colmap::BundleAdjustmentOptions::refine_extra_params, colmap::BundleAdjustmentOptions::refine_extrinsics, colmap::BundleAdjustmentOptions::refine_focal_length, colmap::BundleAdjustmentOptions::refine_principal_point, registerOption(), and colmap::BundleAdjustmentOptions::solver_options.
Referenced by cloudViewer::BundleAdjustment(), and cloudViewer::RigBundleAdjust().
addDelaunayMeshingOptions()
void cloudViewer::OptionsParser::addDelaunayMeshingOptions (const colmap::mvs::DelaunayMeshingOptions & delaunay_meshing_options)
Definition at line 515 of file option_utils.cpp.
References colmap::mvs::DelaunayMeshingOptions::distance_sigma_factor, colmap::mvs::DelaunayMeshingOptions::max_depth_dist, colmap::mvs::DelaunayMeshingOptions::max_proj_dist, colmap::mvs::DelaunayMeshingOptions::max_side_length_factor, colmap::mvs::DelaunayMeshingOptions::max_side_length_percentile, colmap::mvs::DelaunayMeshingOptions::num_threads, colmap::mvs::DelaunayMeshingOptions::quality_regularization, registerOption(), and colmap::mvs::DelaunayMeshingOptions::visibility_sigma.
Referenced by cloudViewer::MeshDelaunay().
addExhaustiveMatchingOptions()
void cloudViewer::OptionsParser::addExhaustiveMatchingOptions (const colmap::SiftMatchingOptions & sift_matching_options, const colmap::ExhaustiveMatchingOptions & exhaustive_matching_options)
Definition at line 165 of file option_utils.cpp.
References addMatchingOptions(), colmap::ExhaustiveMatchingOptions::block_size, and registerOption().
Referenced by cloudViewer::ExhaustiveMatch().
addExtractionOptions()
void cloudViewer::OptionsParser::addExtractionOptions (const colmap::ImageReaderOptions & image_reader_options, const colmap::SiftExtractionOptions & sift_extraction_options)
Definition at line 82 of file option_utils.cpp.
References colmap::ImageReaderOptions::camera_mask_path, colmap::ImageReaderOptions::camera_model, colmap::ImageReaderOptions::camera_params, colmap::ImageReaderOptions::default_focal_length_factor, colmap::SiftExtractionOptions::domain_size_pooling, colmap::SiftExtractionOptions::dsp_max_scale, colmap::SiftExtractionOptions::dsp_min_scale, colmap::SiftExtractionOptions::dsp_num_scales, colmap::SiftExtractionOptions::edge_threshold, colmap::SiftExtractionOptions::estimate_affine_shape, colmap::ImageReaderOptions::existing_camera_id, colmap::SiftExtractionOptions::first_octave, colmap::SiftExtractionOptions::gpu_index, colmap::ImageReaderOptions::mask_path, colmap::SiftExtractionOptions::max_image_size, colmap::SiftExtractionOptions::max_num_features, colmap::SiftExtractionOptions::max_num_orientations, colmap::SiftExtractionOptions::num_octaves, colmap::SiftExtractionOptions::num_threads, colmap::SiftExtractionOptions::octave_resolution, colmap::SiftExtractionOptions::peak_threshold, registerOption(), colmap::ImageReaderOptions::single_camera, colmap::ImageReaderOptions::single_camera_per_folder, colmap::ImageReaderOptions::single_camera_per_image, colmap::SiftExtractionOptions::upright, and colmap::SiftExtractionOptions::use_gpu.
Referenced by cloudViewer::ExtractFeature(), and cloudViewer::ImportFeature().
addImagePairsMatchingOptions()
void cloudViewer::OptionsParser::addImagePairsMatchingOptions (const colmap::SiftMatchingOptions & sift_matching_options, const colmap::ImagePairsMatchingOptions & image_pairs_matching_options)
Definition at line 387 of file option_utils.cpp.
References addMatchingOptions(), colmap::ImagePairsMatchingOptions::block_size, and registerOption().
addMapperOptions()
void cloudViewer::OptionsParser::addMapperOptions (const colmap::IncrementalMapperOptions & incremental_mapper_options)
Definition at line 250 of file option_utils.cpp.
References colmap::IncrementalMapper::Options::abs_pose_max_error, colmap::IncrementalMapper::Options::abs_pose_min_inlier_ratio, colmap::IncrementalMapper::Options::abs_pose_min_num_inliers, colmap::IncrementalMapperOptions::ba_global_function_tolerance, colmap::IncrementalMapperOptions::ba_global_images_freq, colmap::IncrementalMapperOptions::ba_global_images_ratio, colmap::IncrementalMapperOptions::ba_global_max_num_iterations, colmap::IncrementalMapperOptions::ba_global_max_refinement_change, colmap::IncrementalMapperOptions::ba_global_max_refinements, colmap::IncrementalMapperOptions::ba_global_points_freq, colmap::IncrementalMapperOptions::ba_global_points_ratio, colmap::IncrementalMapperOptions::ba_local_function_tolerance, colmap::IncrementalMapperOptions::ba_local_max_num_iterations, colmap::IncrementalMapperOptions::ba_local_max_refinement_change, colmap::IncrementalMapperOptions::ba_local_max_refinements, colmap::IncrementalMapperOptions::ba_local_num_images, colmap::IncrementalMapperOptions::ba_refine_extra_params, colmap::IncrementalMapperOptions::ba_refine_focal_length, colmap::IncrementalMapperOptions::ba_refine_principal_point, colmap::IncrementalTriangulator::Options::complete_max_reproj_error, colmap::IncrementalTriangulator::Options::complete_max_transitivity, colmap::IncrementalTriangulator::Options::continue_max_angle_error, colmap::IncrementalTriangulator::Options::create_max_angle_error, colmap::IncrementalMapperOptions::extract_colors, colmap::IncrementalMapper::Options::filter_max_reproj_error, colmap::IncrementalMapper::Options::filter_min_tri_angle, colmap::IncrementalMapperOptions::fix_existing_images, colmap::IncrementalTriangulator::Options::ignore_two_view_tracks, colmap::IncrementalMapperOptions::ignore_watermarks, colmap::IncrementalMapperOptions::init_image_id1, colmap::IncrementalMapperOptions::init_image_id2, colmap::IncrementalMapper::Options::init_max_error, colmap::IncrementalMapper::Options::init_max_forward_motion, colmap::IncrementalMapper::Options::init_max_reg_trials, colmap::IncrementalMapper::Options::init_min_num_inliers, colmap::IncrementalMapper::Options::init_min_tri_angle, colmap::IncrementalMapperOptions::init_num_trials, colmap::IncrementalMapper::Options::local_ba_min_tri_angle, colmap::IncrementalMapperOptions::mapper, colmap::IncrementalMapperOptions::max_extra_param, colmap::IncrementalMapperOptions::max_focal_length_ratio, colmap::IncrementalMapperOptions::max_model_overlap, colmap::IncrementalMapperOptions::max_num_models, colmap::IncrementalMapper::Options::max_reg_trials, colmap::IncrementalTriangulator::Options::max_transitivity, colmap::IncrementalTriangulator::Options::merge_max_reproj_error, colmap::IncrementalTriangulator::Options::min_angle, colmap::IncrementalMapperOptions::min_focal_length_ratio, colmap::IncrementalMapperOptions::min_model_size, colmap::IncrementalMapperOptions::min_num_matches, colmap::IncrementalMapperOptions::multiple_models, colmap::IncrementalMapperOptions::num_threads, colmap::IncrementalTriangulator::Options::re_max_angle_error, colmap::IncrementalTriangulator::Options::re_max_trials, colmap::IncrementalTriangulator::Options::re_min_ratio, registerOption(), colmap::IncrementalMapperOptions::snapshot_images_freq, colmap::IncrementalMapperOptions::snapshot_path, and colmap::IncrementalMapperOptions::triangulation.
Referenced by cloudViewer::HierarchicalMapper(), cloudViewer::NormalMapper(), cloudViewer::RegisterImage(), and cloudViewer::TriangulatePoints().
addMatchingOptions()
void cloudViewer::OptionsParser::addMatchingOptions (const colmap::SiftMatchingOptions & sift_matching_options)
Definition at line 137 of file option_utils.cpp.
References colmap::SiftMatchingOptions::confidence, colmap::SiftMatchingOptions::cross_check, colmap::SiftMatchingOptions::gpu_index, colmap::SiftMatchingOptions::guided_matching, colmap::SiftMatchingOptions::max_distance, colmap::SiftMatchingOptions::max_error, colmap::SiftMatchingOptions::max_num_matches, colmap::SiftMatchingOptions::max_num_trials, colmap::SiftMatchingOptions::max_ratio, colmap::SiftMatchingOptions::min_inlier_ratio, colmap::SiftMatchingOptions::min_num_inliers, colmap::SiftMatchingOptions::multiple_models, colmap::SiftMatchingOptions::num_threads, registerOption(), and colmap::SiftMatchingOptions::use_gpu.
Referenced by addExhaustiveMatchingOptions(), addImagePairsMatchingOptions(), addSequentialMatchingOptions(), addSpatialMatchingOptions(), addTransitiveMatchingOptions(), addVocabTreeMatchingOptions(), and cloudViewer::ImportMatches().
addPatchMatchStereoOptions()
void cloudViewer::OptionsParser::addPatchMatchStereoOptions (const colmap::mvs::PatchMatchOptions & patch_match_options)
Definition at line 425 of file option_utils.cpp.
References colmap::mvs::PatchMatchOptions::allow_missing_files, colmap::mvs::PatchMatchOptions::cache_size, colmap::mvs::PatchMatchOptions::depth_max, colmap::mvs::PatchMatchOptions::depth_min, colmap::mvs::PatchMatchOptions::filter, colmap::mvs::PatchMatchOptions::filter_geom_consistency_max_cost, colmap::mvs::PatchMatchOptions::filter_min_ncc, colmap::mvs::PatchMatchOptions::filter_min_num_consistent, colmap::mvs::PatchMatchOptions::filter_min_triangulation_angle, colmap::mvs::PatchMatchOptions::geom_consistency, colmap::mvs::PatchMatchOptions::geom_consistency_max_cost, colmap::mvs::PatchMatchOptions::geom_consistency_regularizer, colmap::mvs::PatchMatchOptions::gpu_index, colmap::mvs::PatchMatchOptions::incident_angle_sigma, colmap::mvs::PatchMatchOptions::max_image_size, colmap::mvs::PatchMatchOptions::min_triangulation_angle, colmap::mvs::PatchMatchOptions::ncc_sigma, colmap::mvs::PatchMatchOptions::num_iterations, colmap::mvs::PatchMatchOptions::num_samples, registerOption(), colmap::mvs::PatchMatchOptions::sigma_color, colmap::mvs::PatchMatchOptions::sigma_spatial, colmap::mvs::PatchMatchOptions::window_radius, colmap::mvs::PatchMatchOptions::window_step, and colmap::mvs::PatchMatchOptions::write_consistency_graph.
Referenced by cloudViewer::StereoPatchMatch().
addPoissonMeshingOptions()
void cloudViewer::OptionsParser::addPoissonMeshingOptions (const colmap::mvs::PoissonMeshingOptions & poisson_meshing_options)
Definition at line 504 of file option_utils.cpp.
References colmap::mvs::PoissonMeshingOptions::color, colmap::mvs::PoissonMeshingOptions::depth, colmap::mvs::PoissonMeshingOptions::num_threads, colmap::mvs::PoissonMeshingOptions::point_weight, registerOption(), and colmap::mvs::PoissonMeshingOptions::trim.
Referenced by cloudViewer::MeshPoisson().
addSequentialMatchingOptions()
void cloudViewer::OptionsParser::addSequentialMatchingOptions (const colmap::SiftMatchingOptions & sift_matching_options, const colmap::SequentialMatchingOptions & sequential_matching_options)
Definition at line 173 of file option_utils.cpp.
References addMatchingOptions(), colmap::SequentialMatchingOptions::loop_detection, colmap::SequentialMatchingOptions::loop_detection_max_num_features, colmap::SequentialMatchingOptions::loop_detection_num_checks, colmap::SequentialMatchingOptions::loop_detection_num_images, colmap::SequentialMatchingOptions::loop_detection_num_nearest_neighbors, colmap::SequentialMatchingOptions::loop_detection_period, colmap::SequentialMatchingOptions::overlap, colmap::SequentialMatchingOptions::quadratic_overlap, registerOption(), and colmap::SequentialMatchingOptions::vocab_tree_path.
Referenced by cloudViewer::SequentialMatch().
addSpatialMatchingOptions()
void cloudViewer::OptionsParser::addSpatialMatchingOptions (const colmap::SiftMatchingOptions & sift_matching_options, const colmap::SpatialMatchingOptions & spatial_matching_options)
Definition at line 225 of file option_utils.cpp.
References addMatchingOptions(), colmap::SpatialMatchingOptions::ignore_z, colmap::SpatialMatchingOptions::is_gps, colmap::SpatialMatchingOptions::max_distance, colmap::SpatialMatchingOptions::max_num_neighbors, and registerOption().
Referenced by cloudViewer::SpatialMatch().
addStereoFusionOptions()
void cloudViewer::OptionsParser::addStereoFusionOptions (const colmap::mvs::StereoFusionOptions & stereo_fusion_options)
Definition at line 478 of file option_utils.cpp.
References colmap::mvs::StereoFusionOptions::cache_size, colmap::mvs::StereoFusionOptions::check_num_images, colmap::mvs::StereoFusionOptions::mask_path, colmap::mvs::StereoFusionOptions::max_depth_error, colmap::mvs::StereoFusionOptions::max_image_size, colmap::mvs::StereoFusionOptions::max_normal_error, colmap::mvs::StereoFusionOptions::max_num_pixels, colmap::mvs::StereoFusionOptions::max_reproj_error, colmap::mvs::StereoFusionOptions::max_traversal_depth, colmap::mvs::StereoFusionOptions::min_num_pixels, colmap::mvs::StereoFusionOptions::num_threads, registerOption(), and colmap::mvs::StereoFusionOptions::use_cache.
Referenced by cloudViewer::StereoFuse().
addTransitiveMatchingOptions()
void cloudViewer::OptionsParser::addTransitiveMatchingOptions (const colmap::SiftMatchingOptions & sift_matching_options, const colmap::TransitiveMatchingOptions & transitive_matching_options)
Definition at line 239 of file option_utils.cpp.
References addMatchingOptions(), colmap::TransitiveMatchingOptions::batch_size, colmap::TransitiveMatchingOptions::num_iterations, and registerOption().
Referenced by cloudViewer::TransitiveMatch().
addVocabTreeMatchingOptions()
void cloudViewer::OptionsParser::addVocabTreeMatchingOptions (const colmap::SiftMatchingOptions & sift_matching_options, const colmap::VocabTreeMatchingOptions & vocab_tree_matching_options)
Definition at line 204 of file option_utils.cpp.
References addMatchingOptions(), colmap::VocabTreeMatchingOptions::match_list_path, colmap::VocabTreeMatchingOptions::max_num_features, colmap::VocabTreeMatchingOptions::num_checks, colmap::VocabTreeMatchingOptions::num_images, colmap::VocabTreeMatchingOptions::num_images_after_verification, colmap::VocabTreeMatchingOptions::num_nearest_neighbors, registerOption(), and colmap::VocabTreeMatchingOptions::vocab_tree_path.
Referenced by cloudViewer::VocabTreeMatch().
getArgc()
int cloudViewer::OptionsParser::getArgc () const inline
Definition at line 39 of file option_utils.h.
Referenced by cloudViewer::AlignModel(), cloudViewer::AlignModelOrientation(), cloudViewer::AnalyzeModel(), cloudViewer::AutomaticReconstruct(), cloudViewer::BuildVocabTree(), cloudViewer::BundleAdjustment(), cloudViewer::CleanDatabase(), cloudViewer::CompareModel(), cloudViewer::ConvertModel(), cloudViewer::CreateDatabase(), cloudViewer::CropModel(), cloudViewer::DeleteImage(), cloudViewer::ExhaustiveMatch(), cloudViewer::ExtractColor(), cloudViewer::ExtractFeature(), cloudViewer::FilterImage(), cloudViewer::FilterPoints(), cloudViewer::GenerateProject(), cloudViewer::GraphicalUserInterface(), cloudViewer::HierarchicalMapper(), cloudViewer::ImportFeature(), cloudViewer::ImportMatches(), cloudViewer::MergeDatabase(), cloudViewer::MergeModel(), cloudViewer::MeshDelaunay(), cloudViewer::MeshPoisson(), cloudViewer::NormalMapper(), cloudViewer::RectifyImage(), cloudViewer::RegisterImage(), cloudViewer::RetrieveVocabTree(), cloudViewer::RigBundleAdjust(), cloudViewer::SequentialMatch(), cloudViewer::SpatialMatch(), cloudViewer::SplitModel(), cloudViewer::StereoFuse(), cloudViewer::StereoPatchMatch(), cloudViewer::TransformModel(), cloudViewer::TransitiveMatch(), cloudViewer::TriangulatePoints(), cloudViewer::UndistortImage(), cloudViewer::UndistortImageStandalone(), and cloudViewer::VocabTreeMatch().
getArgv()
char** cloudViewer::OptionsParser::getArgv () inline
Definition at line 40 of file option_utils.h.
Referenced by cloudViewer::AlignModel(), cloudViewer::AlignModelOrientation(), cloudViewer::AnalyzeModel(), cloudViewer::AutomaticReconstruct(), cloudViewer::BuildVocabTree(), cloudViewer::BundleAdjustment(), cloudViewer::CleanDatabase(), cloudViewer::CompareModel(), cloudViewer::ConvertModel(), cloudViewer::CreateDatabase(), cloudViewer::CropModel(), cloudViewer::DeleteImage(), cloudViewer::ExhaustiveMatch(), cloudViewer::ExtractColor(), cloudViewer::ExtractFeature(), cloudViewer::FilterImage(), cloudViewer::FilterPoints(), cloudViewer::GenerateProject(), cloudViewer::GraphicalUserInterface(), cloudViewer::HierarchicalMapper(), cloudViewer::ImportFeature(), cloudViewer::ImportMatches(), cloudViewer::MergeDatabase(), cloudViewer::MergeModel(), cloudViewer::MeshDelaunay(), cloudViewer::MeshPoisson(), cloudViewer::NormalMapper(), cloudViewer::RectifyImage(), cloudViewer::RegisterImage(), cloudViewer::RetrieveVocabTree(), cloudViewer::RigBundleAdjust(), cloudViewer::SequentialMatch(), cloudViewer::SpatialMatch(), cloudViewer::SplitModel(), cloudViewer::StereoFuse(), cloudViewer::StereoPatchMatch(), cloudViewer::TransformModel(), cloudViewer::TransitiveMatch(), cloudViewer::TriangulatePoints(), cloudViewer::UndistortImage(), cloudViewer::UndistortImageStandalone(), and cloudViewer::VocabTreeMatch().
parseOptions() [1/2]
bool cloudViewer::OptionsParser::parseOptions () inline
Definition at line 34 of file option_utils.h.
Referenced by cloudViewer::AlignModel(), cloudViewer::AlignModelOrientation(), cloudViewer::AnalyzeModel(), cloudViewer::AutomaticReconstruct(), cloudViewer::BuildVocabTree(), cloudViewer::BundleAdjustment(), cloudViewer::CleanDatabase(), cloudViewer::CompareModel(), cloudViewer::ConvertModel(), cloudViewer::CreateDatabase(), cloudViewer::CropModel(), cloudViewer::DeleteImage(), cloudViewer::ExhaustiveMatch(), cloudViewer::ExtractColor(), cloudViewer::ExtractFeature(), cloudViewer::FilterImage(), cloudViewer::FilterPoints(), cloudViewer::GenerateProject(), cloudViewer::GraphicalUserInterface(), cloudViewer::HierarchicalMapper(), cloudViewer::ImportFeature(), cloudViewer::ImportMatches(), cloudViewer::MergeDatabase(), cloudViewer::MergeModel(), cloudViewer::MeshDelaunay(), cloudViewer::MeshPoisson(), cloudViewer::NormalMapper(), cloudViewer::RectifyImage(), cloudViewer::RegisterImage(), cloudViewer::RetrieveVocabTree(), cloudViewer::RigBundleAdjust(), cloudViewer::SequentialMatch(), cloudViewer::SpatialMatch(), cloudViewer::SplitModel(), cloudViewer::StereoFuse(), cloudViewer::StereoPatchMatch(), cloudViewer::TransformModel(), cloudViewer::TransitiveMatch(), cloudViewer::TriangulatePoints(), cloudViewer::UndistortImage(), cloudViewer::UndistortImageStandalone(), and cloudViewer::VocabTreeMatch().
parseOptions() [2/2]
bool cloudViewer::OptionsParser::parseOptions (int & argc, char **& argv)
Definition at line 18 of file option_utils.cpp.
References ReleaseOptions(), SetValue(), and patch::to_string().
registerOption()
template<typename T > void cloudViewer::OptionsParser::registerOption (const std::string & name, const T * option) inline
Definition at line 43 of file option_utils.h.
References QtCompat::endl(), and name.
Referenced by addBundleAdjustmentOptions(), addDelaunayMeshingOptions(), addExhaustiveMatchingOptions(), addExtractionOptions(), addImagePairsMatchingOptions(), addMapperOptions(), addMatchingOptions(), addPatchMatchStereoOptions(), addPoissonMeshingOptions(), addSequentialMatchingOptions(), addSpatialMatchingOptions(), addStereoFusionOptions(), addTransitiveMatchingOptions(), addVocabTreeMatchingOptions(), cloudViewer::AlignModel(), cloudViewer::AlignModelOrientation(), cloudViewer::AnalyzeModel(), cloudViewer::AutomaticReconstruct(), cloudViewer::BuildVocabTree(), cloudViewer::BundleAdjustment(), cloudViewer::CleanDatabase(), cloudViewer::CompareModel(), cloudViewer::ConvertModel(), cloudViewer::CreateDatabase(), cloudViewer::CropModel(), cloudViewer::DeleteImage(), cloudViewer::ExhaustiveMatch(), cloudViewer::ExtractColor(), cloudViewer::ExtractFeature(), cloudViewer::FilterImage(), cloudViewer::FilterPoints(), cloudViewer::GenerateProject(), cloudViewer::GraphicalUserInterface(), cloudViewer::HierarchicalMapper(), cloudViewer::ImportFeature(), cloudViewer::ImportMatches(), cloudViewer::MergeDatabase(), cloudViewer::MergeModel(), cloudViewer::MeshDelaunay(), cloudViewer::MeshPoisson(), cloudViewer::NormalMapper(), cloudViewer::RectifyImage(), cloudViewer::RegisterImage(), cloudViewer::RetrieveVocabTree(), cloudViewer::RigBundleAdjust(), cloudViewer::SequentialMatch(), cloudViewer::SpatialMatch(), cloudViewer::SplitModel(), cloudViewer::StereoFuse(), cloudViewer::StereoPatchMatch(), cloudViewer::TransformModel(), cloudViewer::TransitiveMatch(), cloudViewer::TriangulatePoints(), cloudViewer::UndistortImage(), cloudViewer::UndistortImageStandalone(), and cloudViewer::VocabTreeMatch().
ReleaseOptions()
static void cloudViewer::OptionsParser::ReleaseOptions (int argc, char ** argv) inline static
Definition at line 117 of file option_utils.h.
Referenced by parseOptions().
reset()
void cloudViewer::OptionsParser::reset (void)
Definition at line 74 of file option_utils.cpp.
Referenced by OptionsParser(), and ~OptionsParser().
SetValue()
static void cloudViewer::OptionsParser::SetValue (const std::string & value, int argc_, char ** argv_) inline static
Definition at line 128 of file option_utils.h.
References copy.
Referenced by parseOptions().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/pipelines/option_utils.h
/root/ACloudViewer/libs/Reconstruction/src/pipelines/option_utils.cpp