ACloudViewer: LasSaver Class Reference
LasSaver Class Reference
#include <LasSaver.h>
Classes
struct Parameters
Public Member Functions
LasSaver (ccPointCloud &cloud, Parameters &parameters)
~LasSaver () noexcept
CC_FILE_ERROR open (const QString filePath)
CC_FILE_ERROR saveNextPoint ()
bool savesWaveforms () const
QString getLastError () const
Detailed Description
Definition at line 41 of file LasSaver.h.
Constructor & Destructor Documentation
LasSaver()
LasSaver::LasSaver (ccPointCloud & cloud, Parameters & parameters)
Definition at line 18 of file LasSaver.cpp.
References LasSaver::Parameters::extraFields, ccPointCloud::hasColors(), ccPointCloud::hasFWF(), LasDetails::HasWaveform(), LasExtraScalarField::InitExtraBytesVlr(), LasMetadata::LoadGlobalEncoding(), LasMetadata::LoadProjectUUID(), LasScalarFieldSaver::setExtraFields(), LasScalarFieldSaver::setStandarFields(), LasSaver::Parameters::shouldSaveRGB, LasSaver::Parameters::shouldSaveWaveform, LasDetails::SizeOfVlrs(), LasSaver::Parameters::standardFields, LasExtraScalarField::TotalExtraBytesSize(), and LasExtraScalarField::UpdateByteOffsets().
~LasSaver()
LasSaver::~LasSaver () noexcept
Definition at line 108 of file LasSaver.cpp.
Member Function Documentation
getLastError()
QString LasSaver::getLastError () const
Definition at line 227 of file LasSaver.cpp.
Referenced by LasIOFilter::saveToFile().
open()
CC_FILE_ERROR LasSaver::open (const QString filePath)
Definition at line 118 of file LasSaver.cpp.
References CC_FERR_NO_ERROR, CC_FERR_THIRD_PARTY_LIB_FAILURE, and CVLog::Warning().
Referenced by LasIOFilter::saveToFile().
saveNextPoint()
CC_FILE_ERROR LasSaver::saveNextPoint ()
Definition at line 150 of file LasSaver.cpp.
References CC_FERR_INTERNAL, CC_FERR_NO_ERROR, CC_FERR_NO_SAVE, CC_FERR_THIRD_PARTY_LIB_FAILURE, color, cloudViewer::PointCloudTpl< T >::getPoint(), ccPointCloud::getPointColor(), LasScalarFieldSaver::handleExtraFields(), LasScalarFieldSaver::handleScalarFields(), ccPointCloud::hasColors(), LasDetails::HasRGB(), cloudViewer::PointCloudTpl< T >::size(), ccShiftedObject::toGlobal3d(), CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by LasIOFilter::saveToFile().
savesWaveforms()
bool LasSaver::savesWaveforms () const
Definition at line 222 of file LasSaver.cpp.
Referenced by LasIOFilter::saveToFile().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qLASIO/include/LasSaver.h
/root/ACloudViewer/plugins/core/IO/qLASIO/src/LasSaver.cpp