ACloudViewer: cloudViewer::core::nns::FixedRadiusIndex Class Reference
cloudViewer::core::nns::FixedRadiusIndex Class Reference
FixedRadiusIndex for nearest neighbor range search.
#include <FixedRadiusIndex.h>
Public Member Functions
FixedRadiusIndex ()
Default Constructor.
FixedRadiusIndex (const Tensor &dataset_points, double radius)
Parameterized Constructor.
FixedRadiusIndex (const Tensor &dataset_points, double radius, const Dtype &index_dtype)
~FixedRadiusIndex ()
FixedRadiusIndex (const FixedRadiusIndex &)=delete
FixedRadiusIndex & operator= (const FixedRadiusIndex &)=delete
bool SetTensorData (const Tensor &dataset_points, const Dtype &index_dtype=core::Int64) override
bool SetTensorData (const Tensor &dataset_points, double radius, const Dtype &index_dtype=core::Int64) override
bool SetTensorData (const Tensor &dataset_points, const Tensor &points_row_splits, double radius, const Dtype &index_dtype=core::Int64)
std::pair< Tensor, Tensor > SearchKnn (const Tensor &query_points, int knn) const override
std::tuple< Tensor, Tensor, Tensor > SearchRadius (const Tensor &query_points, const Tensor &radii, bool sort=true) const override
std::tuple< Tensor, Tensor, Tensor > SearchRadius (const Tensor &query_points, double radius, bool sort=true) const override
std::tuple< Tensor, Tensor, Tensor > SearchRadius (const Tensor &query_points, const Tensor &queries_row_splits, double radius, bool sort=true) const
std::tuple< Tensor, Tensor, Tensor > SearchHybrid (const Tensor &query_points, double radius, int max_knn) const override
std::tuple< Tensor, Tensor, Tensor > SearchHybrid (const Tensor &query_points, const Tensor &queries_row_splits, double radius, int max_knn) const
Public Member Functions inherited from cloudViewer::core::nns::NNSIndex
NNSIndex ()
Default Constructor.
virtual ~NNSIndex ()
NNSIndex (const NNSIndex &)=delete
NNSIndex & operator= (const NNSIndex &)=delete
int GetDimension () const
size_t GetDatasetSize () const
Dtype GetDtype () const
Device GetDevice () const
Dtype GetIndexDtype () const
Public Attributes
const double hash_table_size_factor = 1.0 / 32
const int64_t max_hash_tabls_size = 33554432
Protected Attributes
Tensor points_row_splits_
Tensor hash_table_splits_
Tensor hash_table_cell_splits_
Tensor hash_table_index_
Protected Attributes inherited from cloudViewer::core::nns::NNSIndex
Tensor dataset_points_
Dtype index_dtype_
Detailed Description
FixedRadiusIndex for nearest neighbor range search.
Definition at line 382 of file FixedRadiusIndex.h.
Constructor & Destructor Documentation
FixedRadiusIndex() [1/4]
cloudViewer::core::nns::FixedRadiusIndex::FixedRadiusIndex ()
Default Constructor.
Definition at line 19 of file FixedRadiusIndex.cpp.
FixedRadiusIndex() [2/4]
cloudViewer::core::nns::FixedRadiusIndex::FixedRadiusIndex (const Tensor & dataset_points, double radius)
Parameterized Constructor.
Parameters
dataset_points Provides a set of data points as Tensor for KDTree construction.
Definition at line 21 of file FixedRadiusIndex.cpp.
References AssertTensorDtypes, cloudViewer::core::Float32, cloudViewer::core::Float64, and SetTensorData().
FixedRadiusIndex() [3/4]
cloudViewer::core::nns::FixedRadiusIndex::FixedRadiusIndex (const Tensor & dataset_points, double radius, const Dtype & index_dtype)
Definition at line 27 of file FixedRadiusIndex.cpp.
References AssertTensorDtypes, cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Int32, cloudViewer::core::Int64, and SetTensorData().
~FixedRadiusIndex()
cloudViewer::core::nns::FixedRadiusIndex::~FixedRadiusIndex ()
Definition at line 35 of file FixedRadiusIndex.cpp.
FixedRadiusIndex() [4/4]
cloudViewer::core::nns::FixedRadiusIndex::FixedRadiusIndex (const FixedRadiusIndex &) delete
Member Function Documentation
operator=()
FixedRadiusIndex& cloudViewer::core::nns::FixedRadiusIndex::operator= (const FixedRadiusIndex &) delete
SearchHybrid() [1/2]
std::tuple< Tensor, Tensor, Tensor > cloudViewer::core::nns::FixedRadiusIndex::SearchHybrid (const Tensor & query_points, const Tensor & queries_row_splits, double radius, int max_knn) const
Definition at line 196 of file FixedRadiusIndex.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorShape, cloudViewer::core::Tensor::Contiguous(), DISPATCH_FLOAT_INT_DTYPE_TO_TEMPLATE, cloudViewer::core::nns::NNSIndex::GetDevice(), cloudViewer::core::nns::NNSIndex::GetDimension(), cloudViewer::core::nns::NNSIndex::GetDtype(), cloudViewer::core::nns::NNSIndex::GetIndexDtype(), cloudViewer::core::Tensor::GetShape(), HYBRID_PARAMETERS, cloudViewer::core::Int64, cloudViewer::core::Device::IsCUDA(), LogError, cloudViewer::utility::nullopt, points_row_splits_, and cloudViewer::core::Tensor::View().
SearchHybrid() [2/2]
std::tuple< Tensor, Tensor, Tensor > cloudViewer::core::nns::FixedRadiusIndex::SearchHybrid (const Tensor & query_points, double radius, int max_knn) const override virtual
Perform hybrid search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}.
radius Radius.
max_knn Maximum number of neighbor to search per query point.
Returns
Tuple of Tensors, (indices, distances, counts):
indices: Tensor of shape {n, knn}, with dtype Int32.
distances: Tensor of shape {n, knn}, with dtype Float32.
counts: Tensor of shape {n, 1}, with dtype Int32.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 188 of file FixedRadiusIndex.cpp.
References cloudViewer::core::Tensor::GetShape(), and cloudViewer::core::Int64.
SearchKnn()
std::pair<Tensor, Tensor> cloudViewer::core::nns::FixedRadiusIndex::SearchKnn (const Tensor & query_points, int knn) const inline override virtual
Perform K nearest neighbor search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}, same dtype with dataset_points.
knn Number of nearest neighbor to search.
Returns
Pair of Tensors: (indices, distances):
indices: Tensor of shape {n, knn}, with dtype Int32.
distances: Tensor of shape {n, knn}, same dtype with dataset_points.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 415 of file FixedRadiusIndex.h.
References LogError.
SearchRadius() [1/3]
std::tuple< Tensor, Tensor, Tensor > cloudViewer::core::nns::FixedRadiusIndex::SearchRadius (const Tensor & query_points, const Tensor & queries_row_splits, double radius, bool sort = true) const
Definition at line 126 of file FixedRadiusIndex.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorShape, cloudViewer::core::Tensor::Contiguous(), DISPATCH_FLOAT_INT_DTYPE_TO_TEMPLATE, cloudViewer::core::nns::NNSIndex::GetDevice(), cloudViewer::core::nns::NNSIndex::GetDimension(), cloudViewer::core::nns::NNSIndex::GetDtype(), cloudViewer::core::nns::NNSIndex::GetIndexDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Int64, cloudViewer::core::Device::IsCUDA(), LogError, cloudViewer::utility::nullopt, points_row_splits_, RADIUS_PARAMETERS, and cloudViewer::core::Tensor::To().
SearchRadius() [2/3]
std::tuple<Tensor, Tensor, Tensor> cloudViewer::core::nns::FixedRadiusIndex::SearchRadius (const Tensor & query_points, const Tensor & radii, bool sort = true) const inline override virtual
Perform radius search with multiple radii.
Parameters
query_points Query points. Must be 2D, with shape {n, d}, same dtype with dataset_points.
radii list of radius. Must be 1D, with shape {n, }.
Returns
Tuple of Tensors: (indices, distances, num_neighbors):
indices: Tensor of shape {total_num_neighbors,}, dtype Int32.
distances: Tensor of shape {total_num_neighbors,}, same dtype with dataset_points.
num_neighbors: Tensor of shape {n,}, dtype Int32.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 420 of file FixedRadiusIndex.h.
References LogError.
Referenced by SearchRadius().
SearchRadius() [3/3]
std::tuple< Tensor, Tensor, Tensor > cloudViewer::core::nns::FixedRadiusIndex::SearchRadius (const Tensor & query_points, double radius, bool sort = true) const override virtual
Perform radius search.
Parameters
query_points Query points. Must be 2D, with shape {n, d}, same dtype with dataset_points.
radius Radius.
Returns
Tuple of Tensors, (indices, distances, num_neighbors):
indices: Tensor of shape {total_num_neighbors,}, dtype Int32.
distances: Tensor of shape {total_num_neighbors,}, same dtype with dataset_points.
num_neighbors: Tensor of shape {n}, dtype Int32.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 118 of file FixedRadiusIndex.cpp.
References cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Int64, and SearchRadius().
SetTensorData() [1/3]
bool cloudViewer::core::nns::FixedRadiusIndex::SetTensorData (const Tensor & dataset_points, const Dtype & index_dtype = core::Int64) inline override virtual
Set the data for the nearest neighbor search.
Parameters
dataset_points Dataset points for KDTree construction. Must be 2D, with shape {n, d}.
Returns
Returns true if the construction success, otherwise false.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 400 of file FixedRadiusIndex.h.
References LogError.
Referenced by FixedRadiusIndex(), and SetTensorData().
SetTensorData() [2/3]
bool cloudViewer::core::nns::FixedRadiusIndex::SetTensorData (const Tensor & dataset_points, const Tensor & points_row_splits, double radius, const Dtype & index_dtype = core::Int64)
Definition at line 47 of file FixedRadiusIndex.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, cloudViewer::core::nns::BuildSpatialHashTableCPU(), CALL_BUILD, cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::nns::NNSIndex::dataset_points_, cloudViewer::core::Tensor::Empty(), cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::nns::NNSIndex::GetDatasetSize(), cloudViewer::core::nns::NNSIndex::GetDevice(), cloudViewer::core::nns::NNSIndex::GetDtype(), cloudViewer::core::Tensor::GetShape(), hash_table_cell_splits_, hash_table_index_, hash_table_size_factor, hash_table_splits_, cloudViewer::core::nns::NNSIndex::index_dtype_, cloudViewer::core::Int32, cloudViewer::core::Int64, cloudViewer::core::Device::IsCUDA(), cloudViewer::core::Tensor::Item(), LogError, max_hash_tabls_size, points_row_splits_, and cloudViewer::core::UInt32.
SetTensorData() [3/3]
bool cloudViewer::core::nns::FixedRadiusIndex::SetTensorData (const Tensor & dataset_points, double radius, const Dtype & index_dtype = core::Int64) override virtual
Set the data for the nearest neighbor search.
Parameters
dataset_points Dataset points for KDTree construction. Must be 2D, with shape {n, d}.
Returns
Returns true if the construction success, otherwise false.
Implements cloudViewer::core::nns::NNSIndex.
Definition at line 37 of file FixedRadiusIndex.cpp.
References cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Int64, and SetTensorData().
Member Data Documentation
hash_table_cell_splits_
Tensor cloudViewer::core::nns::FixedRadiusIndex::hash_table_cell_splits_ protected
Definition at line 455 of file FixedRadiusIndex.h.
Referenced by SetTensorData().
hash_table_index_
Tensor cloudViewer::core::nns::FixedRadiusIndex::hash_table_index_ protected
Definition at line 456 of file FixedRadiusIndex.h.
Referenced by SetTensorData().
hash_table_size_factor
const double cloudViewer::core::nns::FixedRadiusIndex::hash_table_size_factor = 1.0 / 32
Definition at line 449 of file FixedRadiusIndex.h.
Referenced by SetTensorData().
hash_table_splits_
Tensor cloudViewer::core::nns::FixedRadiusIndex::hash_table_splits_ protected
Definition at line 454 of file FixedRadiusIndex.h.
Referenced by SetTensorData().
max_hash_tabls_size
const int64_t cloudViewer::core::nns::FixedRadiusIndex::max_hash_tabls_size = 33554432
Definition at line 450 of file FixedRadiusIndex.h.
Referenced by SetTensorData().
points_row_splits_
Tensor cloudViewer::core::nns::FixedRadiusIndex::points_row_splits_ protected
Definition at line 453 of file FixedRadiusIndex.h.
Referenced by SearchHybrid(), SearchRadius(), and SetTensorData().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/core/nns/FixedRadiusIndex.h
/root/ACloudViewer/libs/cloudViewer/core/nns/FixedRadiusIndex.cpp