ACloudViewer: colmap::ProgressiveSampler Class Reference
colmap::ProgressiveSampler Class Reference
#include <progressive_sampler.h>
Public Member Functions
ProgressiveSampler (const size_t num_samples)
void Initialize (const size_t total_num_samples) override
size_t MaxNumSamples () override
std::vector< size_t > Sample () override
Public Member Functions inherited from colmap::Sampler
Sampler ()
Sampler (const size_t num_samples)
template<typename X_t >
void SampleX (const X_t &X, X_t *X_rand)
template<typename X_t , typename Y_t >
void SampleXY (const X_t &X, const Y_t &Y, X_t *X_rand, Y_t *Y_rand)
Detailed Description
Definition at line 23 of file progressive_sampler.h.
Constructor & Destructor Documentation
ProgressiveSampler()
colmap::ProgressiveSampler::ProgressiveSampler (const size_t num_samples) explicit
Definition at line 41 of file progressive_sampler.cc.
Member Function Documentation
Initialize()
void colmap::ProgressiveSampler::Initialize (const size_t total_num_samples) override virtual
Implements colmap::Sampler.
Definition at line 49 of file progressive_sampler.cc.
Referenced by BOOST_AUTO_TEST_CASE().
MaxNumSamples()
size_t colmap::ProgressiveSampler::MaxNumSamples () override virtual
Implements colmap::Sampler.
Definition at line 68 of file progressive_sampler.cc.
Referenced by BOOST_AUTO_TEST_CASE().
Sample()
std::vector< size_t > colmap::ProgressiveSampler::Sample () override virtual
Implements colmap::Sampler.
Definition at line 72 of file progressive_sampler.cc.
References cloudViewer::utility::ceil(), and colmap::VectorContainsValue().
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/optim/progressive_sampler.h
/root/ACloudViewer/libs/Reconstruction/src/optim/progressive_sampler.cc