ACloudViewer: PdmsTools::PdmsCommands::DistanceValue Class Reference
PdmsTools::PdmsCommands::DistanceValue Class Reference
#include <PdmsTools.h>
Public Member Functions
DistanceValue (Token t=PDMS_INVALID_TOKEN)
virtual bool handle (Token t)
virtual bool handle (PointCoordinateType numvalue)
PointCoordinateType getValueInWorkingUnit () const
virtual bool execute (PdmsObjects::GenericItem *&item) const
Public Member Functions inherited from PdmsTools::PdmsCommands::NumericalValue
NumericalValue (Token t)
virtual bool isValid () const
virtual PointCoordinateType getValue () const
Public Member Functions inherited from PdmsTools::PdmsCommands::Command
Command (Token t)
Command (const Command &com)
virtual ~Command ()
virtual bool handle (const char *str)
Static Public Member Functions
static void setWorkingUnit (Token wu)
Static Public Member Functions inherited from PdmsTools::PdmsCommands::Command
static Command * Create (Token t)
Factory.
Public Attributes
Token unit
Public Attributes inherited from PdmsTools::PdmsCommands::NumericalValue
PointCoordinateType value
int valueChanges
Public Attributes inherited from PdmsTools::PdmsCommands::Command
Token command
Static Public Attributes
static Token workingUnit = PDMS_MILLIMETRE
Detailed Description
Definition at line 508 of file PdmsTools.h.
Constructor & Destructor Documentation
DistanceValue()
PdmsTools::PdmsCommands::DistanceValue::DistanceValue (Token t = PDMS_INVALID_TOKEN) inline explicit
Definition at line 513 of file PdmsTools.h.
Member Function Documentation
execute()
bool DistanceValue::execute (PdmsObjects::GenericItem *& item) const virtual
Reimplemented from PdmsTools::PdmsCommands::NumericalValue.
Definition at line 123 of file PdmsTools.cpp.
References PdmsTools::PdmsObjects::GenericItem::setValue().
getValueInWorkingUnit()
PointCoordinateType DistanceValue::getValueInWorkingUnit () const
Definition at line 114 of file PdmsTools.cpp.
References PdmsTools::PDMS_METRE, and PdmsTools::PDMS_MILLIMETRE.
handle() [1/2]
virtual bool PdmsTools::PdmsCommands::DistanceValue::handle (PointCoordinateType numvalue) inline virtual
Reimplemented from PdmsTools::PdmsCommands::NumericalValue.
Definition at line 517 of file PdmsTools.h.
References PdmsTools::PdmsCommands::NumericalValue::handle().
handle() [2/2]
bool DistanceValue::handle (Token t) virtual
Reimplemented from PdmsTools::PdmsCommands::Command.
Definition at line 107 of file PdmsTools.cpp.
References PdmsTools::PdmsToken::isUnit().
setWorkingUnit()
static void PdmsTools::PdmsCommands::DistanceValue::setWorkingUnit (Token wu) inline static
Definition at line 515 of file PdmsTools.h.
References workingUnit.
Member Data Documentation
unit
Token PdmsTools::PdmsCommands::DistanceValue::unit
Definition at line 510 of file PdmsTools.h.
workingUnit
Token DistanceValue::workingUnit = PDMS_MILLIMETRE static
Definition at line 511 of file PdmsTools.h.
Referenced by setWorkingUnit().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsTools.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsTools.cpp