ACloudViewer: PclFiltersTool Class Reference
PclFiltersTool Class Reference
#include <PclFiltersTool.h>
Public Member Functions
PclFiltersTool (FilterType type=FilterType::CLIP_FILTER)
PclFiltersTool (ecvGenericVisualizer3D *viewer, FilterType type=FilterType::CLIP_FILTER)
virtual ~PclFiltersTool () override
void setVisualizer (ecvGenericVisualizer3D *viewer=nullptr)
initialize
virtual void showInteractor (bool state) override
virtual ccHObject * getOutput () const override
virtual void getOutput (std::vector< ccHObject * > &outputSlices, std::vector< ccPolyline * > &outputContours) const override
virtual void setNegative (bool state) override
virtual QWidget * getFilterWidget () override
virtual const ccBBox & getBox () override
Returns the box extents.
virtual void setBox (const ccBBox &box) override
Sets the box extents.
virtual void shift (const CCVector3 &v) override
Shifts the current interactor.
virtual void set (const ccBBox &extents, const ccGLMatrix &transformation) override
Manually sets the box parameters.
virtual void get (ccBBox &extents, ccGLMatrix &transformation) override
virtual bool setInputData (ccHObject *entity, int viewport=0) override
virtual void intersectMode () override
virtual void unionMode () override
virtual void trimMode () override
virtual void resetMode () override
virtual bool start () override
clear state before load new cloud and annotation
virtual void reset () override
virtual void restore () override
virtual void clear () override
virtual void showOutline (bool state) override
Whether to show the box or not.
Public Member Functions inherited from ecvGenericFiltersTool
ecvGenericFiltersTool (FilterType mode=FilterType::CLIP_FILTER)
Default constructor.
virtual ~ecvGenericFiltersTool ()=default
Desctructor.
virtual void update ()
FilterType getFilterType ()
Protected Slots
void areaPickingEventProcess (const std::vector< int > &new_selected_slice)
Protected Member Functions
virtual void unregisterFilter () override
virtual void initialize (ecvGenericVisualizer3D *viewer) override
Protected Member Functions inherited from ecvGenericFiltersTool
virtual bool buildUp ()
Builds primitive.
Additional Inherited Members
Public Types inherited from ecvGenericFiltersTool
enum FilterType {
CLIP_FILTER , SLICE_FILTER , DECIMATE_FILTER , ISOSURFACE_FILTER ,
THRESHOLD_FILTER , SMOOTH_FILTER , PROBE_FILTER , STREAMLINE_FILTER ,
GLYPH_FILTER
}
Signals inherited from ecvGenericFiltersTool
void boxModified (const ccBBox *box)
Signal sent each time the box is modified.
Protected Attributes inherited from ecvGenericFiltersTool
bool m_showOutline = false
ccBBox m_box
FilterType m_filterType
ccHObject * m_associatedEntity
Detailed Description
Definition at line 25 of file PclFiltersTool.h.
Constructor & Destructor Documentation
PclFiltersTool() [1/2]
PclFiltersTool::PclFiltersTool (FilterType type = FilterType::CLIP_FILTER) explicit
Definition at line 54 of file PclFiltersTool.cpp.
PclFiltersTool() [2/2]
PclFiltersTool::PclFiltersTool (ecvGenericVisualizer3D * viewer, FilterType type = FilterType::CLIP_FILTER) explicit
Definition at line 57 of file PclFiltersTool.cpp.
References initialize().
~PclFiltersTool()
PclFiltersTool::~PclFiltersTool () override virtual
Definition at line 62 of file PclFiltersTool.cpp.
Member Function Documentation
areaPickingEventProcess
void PclFiltersTool::areaPickingEventProcess (const std::vector< int > & new_selected_slice) protected slot
Definition at line 229 of file PclFiltersTool.cpp.
References a, ecvTools::DiffVector(), PclUtils::PCLVis::getRenderWindowInteractor(), GROUND_POINT, ecvTools::IntersectionVector(), ecvTools::UnionVector(), ecvGenericFiltersTool::update(), and x.
clear()
void PclFiltersTool::clear () override virtual
Implements ecvGenericFiltersTool.
Definition at line 277 of file PclFiltersTool.cpp.
References cvGenericFilter::clearAllActor().
Referenced by unregisterFilter().
get()
void PclFiltersTool::get (ccBBox & extents, ccGLMatrix & transformation) override virtual
Implements ecvGenericFiltersTool.
Definition at line 175 of file PclFiltersTool.cpp.
References ccGLMatrixTpl< T >::data(), and cvGenericFilter::getInteractorInfos().
getBox()
const ccBBox & PclFiltersTool::getBox () override virtual
Returns the box extents.
Implements ecvGenericFiltersTool.
Definition at line 158 of file PclFiltersTool.cpp.
References cvGenericFilter::getInteractorBounds(), and ecvGenericFiltersTool::m_box.
getFilterWidget()
QWidget * PclFiltersTool::getFilterWidget () override virtual
Implements ecvGenericFiltersTool.
Definition at line 154 of file PclFiltersTool.cpp.
getOutput() [1/2]
ccHObject * PclFiltersTool::getOutput () const override virtual
Implements ecvGenericFiltersTool.
Definition at line 138 of file PclFiltersTool.cpp.
References cvGenericFilter::getOutput().
getOutput() [2/2]
void PclFiltersTool::getOutput (std::vector< ccHObject * > & outputSlices, std::vector< ccPolyline * > & outputContours) const override virtual
Implements ecvGenericFiltersTool.
Definition at line 143 of file PclFiltersTool.cpp.
References cvGenericFilter::getOutput().
initialize()
void PclFiltersTool::initialize (ecvGenericVisualizer3D * viewer) override protected virtual
Implements ecvGenericFiltersTool.
Definition at line 70 of file PclFiltersTool.cpp.
References ecvGenericFiltersTool::CLIP_FILTER, ecvGenericFiltersTool::DECIMATE_FILTER, CVLog::Error(), ecvGenericFiltersTool::GLYPH_FILTER, ecvGenericFiltersTool::ISOSURFACE_FILTER, ecvGenericFiltersTool::m_filterType, ecvGenericFiltersTool::PROBE_FILTER, resetMode(), cvGenericFilter::setUpViewer(), setVisualizer(), ecvGenericFiltersTool::SLICE_FILTER, ecvGenericFiltersTool::SMOOTH_FILTER, ecvGenericFiltersTool::STREAMLINE_FILTER, and ecvGenericFiltersTool::THRESHOLD_FILTER.
Referenced by PclFiltersTool().
intersectMode()
void PclFiltersTool::intersectMode () override virtual
Implements ecvGenericFiltersTool.
Definition at line 204 of file PclFiltersTool.cpp.
reset()
void PclFiltersTool::reset (void) override virtual
Implements ecvGenericFiltersTool.
Definition at line 267 of file PclFiltersTool.cpp.
References cvGenericFilter::reset().
resetMode()
void PclFiltersTool::resetMode () override virtual
Implements ecvGenericFiltersTool.
Definition at line 222 of file PclFiltersTool.cpp.
Referenced by initialize(), and unregisterFilter().
restore()
void PclFiltersTool::restore () override virtual
Implements ecvGenericFiltersTool.
Definition at line 272 of file PclFiltersTool.cpp.
References cvGenericFilter::restoreOrigin().
set()
void PclFiltersTool::set (const ccBBox & extents, const ccGLMatrix & transformation) override virtual
Manually sets the box parameters.
Implements ecvGenericFiltersTool.
Definition at line 172 of file PclFiltersTool.cpp.
setBox()
void PclFiltersTool::setBox (const ccBBox & box) override virtual
Sets the box extents.
Implements ecvGenericFiltersTool.
Definition at line 164 of file PclFiltersTool.cpp.
References ecvGenericFiltersTool::m_box.
setInputData()
bool PclFiltersTool::setInputData (ccHObject * entity, int viewport = 0) override virtual
Implements ecvGenericFiltersTool.
Definition at line 182 of file PclFiltersTool.cpp.
References ecvGenericFiltersTool::m_associatedEntity, and cvGenericFilter::setInput().
setNegative()
void PclFiltersTool::setNegative (bool state) override virtual
Implements ecvGenericFiltersTool.
Definition at line 149 of file PclFiltersTool.cpp.
References cvGenericFilter::setNegative().
setVisualizer()
void PclFiltersTool::setVisualizer (ecvGenericVisualizer3D * viewer = nullptr)
initialize
Definition at line 115 of file PclFiltersTool.cpp.
References CVLog::Warning().
Referenced by initialize().
shift()
void PclFiltersTool::shift (const CCVector3 & v) override virtual
Shifts the current interactor.
Implements ecvGenericFiltersTool.
Definition at line 166 of file PclFiltersTool.cpp.
References Vector3Tpl< double >::fromArray(), cvGenericFilter::shift(), and Tuple3Tpl< Type >::u.
showInteractor()
void PclFiltersTool::showInteractor (bool state) override virtual
Implements ecvGenericFiltersTool.
Definition at line 127 of file PclFiltersTool.cpp.
References cvGenericFilter::showInteractor(), and ecvGenericFiltersTool::update().
showOutline()
void PclFiltersTool::showOutline (bool state) override virtual
Whether to show the box or not.
Implements ecvGenericFiltersTool.
Definition at line 133 of file PclFiltersTool.cpp.
References cvGenericFilter::showOutline().
start()
bool PclFiltersTool::start (void) override virtual
clear state before load new cloud and annotation
Implements ecvGenericFiltersTool.
Definition at line 188 of file PclFiltersTool.cpp.
References cvGenericFilter::apply(), and cvGenericFilter::start().
trimMode()
void PclFiltersTool::trimMode () override virtual
Implements ecvGenericFiltersTool.
Definition at line 216 of file PclFiltersTool.cpp.
unionMode()
void PclFiltersTool::unionMode () override virtual
Implements ecvGenericFiltersTool.
Definition at line 210 of file PclFiltersTool.cpp.
unregisterFilter()
void PclFiltersTool::unregisterFilter () override protected virtual
Implements ecvGenericFiltersTool.
Definition at line 195 of file PclFiltersTool.cpp.
References clear(), resetMode(), and ecvGenericFiltersTool::update().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/PclFiltersTool.h
/root/ACloudViewer/libs/PCLEngine/Tools/FilterTools/PclFiltersTool.cpp