ACloudViewer: ccChunk Class Reference
ccChunk Class Reference
Fake chunked array management.
#include <ecvChunk.h>
Static Public Member Functions
static size_t Count (size_t elementCount)
static size_t Size (size_t chunkIndex, size_t elementCount)
static size_t Size (size_t chunkIndex, size_t chunkCount, size_t elementCount)
static size_t StartPos (size_t chunkIndex)
template<typename T >
static T * Start (std::vector< T > &buffer, size_t chunkIndex)
template<typename T >
static const T * Start (const std::vector< T > &buffer, size_t chunkIndex)
template<typename T >
static size_t Count (const std::vector< T > &buffer)
template<typename T >
static size_t Size (size_t chunkIndex, const std::vector< T > &buffer)
Static Public Attributes
static const size_t SIZE_POWER = 16
static const size_t SIZE = (1 << SIZE_POWER)
Detailed Description
Fake chunked array management.
Definition at line 14 of file ecvChunk.h.
Member Function Documentation
Count() [1/2]
template<typename T > static size_t ccChunk::Count (const std::vector< T > & buffer) inline static
Definition at line 47 of file ecvChunk.h.
References Count().
Count() [2/2]
static size_t ccChunk::Count (size_t elementCount) inline static
Definition at line 19 of file ecvChunk.h.
References SIZE, and SIZE_POWER.
Referenced by Count(), and Size().
Size() [1/3]
template<typename T > static size_t ccChunk::Size (size_t chunkIndex, const std::vector< T > & buffer) inline static
Definition at line 51 of file ecvChunk.h.
References Size().
Size() [2/3]
static size_t ccChunk::Size (size_t chunkIndex, size_t chunkCount, size_t elementCount) inline static
Definition at line 28 of file ecvChunk.h.
References SIZE.
Size() [3/3]
static size_t ccChunk::Size (size_t chunkIndex, size_t elementCount) inline static
Definition at line 23 of file ecvChunk.h.
References Count(), and SIZE.
Referenced by Size().
Start() [1/2]
template<typename T > static const T* ccChunk::Start (const std::vector< T > & buffer, size_t chunkIndex) inline static
Definition at line 42 of file ecvChunk.h.
References StartPos().
Start() [2/2]
template<typename T > static T* ccChunk::Start (std::vector< T > & buffer, size_t chunkIndex) inline static
Definition at line 38 of file ecvChunk.h.
References StartPos().
StartPos()
static size_t ccChunk::StartPos (size_t chunkIndex) inline static
Definition at line 34 of file ecvChunk.h.
References SIZE.
Referenced by Start().
Member Data Documentation
SIZE
const size_t ccChunk::SIZE = (1 << SIZE_POWER) static
Definition at line 17 of file ecvChunk.h.
Referenced by Count(), Size(), and StartPos().
SIZE_POWER
const size_t ccChunk::SIZE_POWER = 16 static
Definition at line 16 of file ecvChunk.h.
Referenced by Count().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvChunk.h