ACloudViewer: LasExtraScalarFieldCard Class Reference
LasExtraScalarFieldCard Class Reference
#include <LasExtraScalarFieldCard.h>
Public Member Functions
LasExtraScalarFieldCard (QWidget *parent=nullptr)
void fillFrom (const LasExtraScalarField &field)
void reset ()
LasExtraScalarField::DataType dataType () const
bool fillField (LasExtraScalarField &field, const ccPointCloud &pointCloud) const
Detailed Description
Definition at line 30 of file LasExtraScalarFieldCard.h.
Constructor & Destructor Documentation
LasExtraScalarFieldCard()
LasExtraScalarFieldCard::LasExtraScalarFieldCard (QWidget * parent = nullptr) explicit
Definition at line 13 of file LasExtraScalarFieldCard.cpp.
References LasExtraScalarField::MAX_DESCRIPTION_SIZE, LasExtraScalarField::MAX_NAME_SIZE, and reset().
Member Function Documentation
dataType()
LasExtraScalarField::DataType LasExtraScalarFieldCard::dataType () const
Definition at line 261 of file LasExtraScalarFieldCard.cpp.
Referenced by fillField().
fillField()
bool LasExtraScalarFieldCard::fillField (LasExtraScalarField & field, const ccPointCloud & pointCloud) const
Definition at line 185 of file LasExtraScalarFieldCard.cpp.
References dataType(), LasExtraScalarField::description, LasExtraScalarField::dimensions, cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), LasExtraScalarField::MAX_DESCRIPTION_SIZE, LasExtraScalarField::MAX_NAME_SIZE, LasExtraScalarField::name, LasExtraScalarField::numElements(), LasExtraScalarField::offsets, LasExtraScalarField::One, LasExtraScalarField::scalarFields, LasExtraScalarField::scales, LasExtraScalarField::setOffsetIsRelevant(), LasExtraScalarField::setScaleIsRelevant(), LasExtraScalarField::Three, LasExtraScalarField::Two, LasExtraScalarField::type, and CVLog::Warning().
fillFrom()
void LasExtraScalarFieldCard::fillFrom (const LasExtraScalarField & field)
Definition at line 85 of file LasExtraScalarFieldCard.cpp.
References LasExtraScalarField::ccName, LasExtraScalarField::description, cloudViewer::ScalarField::getName(), LasExtraScalarField::name, LasExtraScalarField::numElements(), LasExtraScalarField::offsetIsRelevant(), LasExtraScalarField::offsets, LasExtraScalarField::scalarFields, LasExtraScalarField::scaleIsRelevant(), LasExtraScalarField::scales, and LasExtraScalarField::type.
reset()
void LasExtraScalarFieldCard::reset (void)
Definition at line 61 of file LasExtraScalarFieldCard.cpp.
Referenced by LasExtraScalarFieldCard().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qLASIO/include/LasExtraScalarFieldCard.h
/root/ACloudViewer/plugins/core/IO/qLASIO/src/LasExtraScalarFieldCard.cpp