ACloudViewer: ccMPlanePoint Class Reference
ccMPlanePoint Class Reference
#include <ccMPlanePoint.h>
Public Member Functions
ccMPlanePoint (cc2DLabel *label)
unsigned int getIndex () const
const CCVector3 & getCoordinates () const
cc2DLabel * getLabel ()
QString getName () const
void setName (const QString &newName)
float getDistance () const
void setDistance (float)
Detailed Description
Definition at line 13 of file ccMPlanePoint.h.
Constructor & Destructor Documentation
ccMPlanePoint()
ccMPlanePoint::ccMPlanePoint (cc2DLabel * label) inline explicit
Definition at line 15 of file ccMPlanePoint.h.
Member Function Documentation
getCoordinates()
const CCVector3 & ccMPlanePoint::getCoordinates () const
Definition at line 17 of file ccMPlanePoint.cpp.
References cc2DLabel::PickedPoint::cloudOrVertices(), getIndex(), cc2DLabel::getPickedPoint(), and cloudViewer::GenericIndexedCloud::getPoint().
getDistance()
float ccMPlanePoint::getDistance () const
Definition at line 29 of file ccMPlanePoint.cpp.
getIndex()
unsigned int ccMPlanePoint::getIndex () const
Definition at line 13 of file ccMPlanePoint.cpp.
References cc2DLabel::getPickedPoint(), and cc2DLabel::PickedPoint::index.
Referenced by getCoordinates().
getLabel()
cc2DLabel * ccMPlanePoint::getLabel ()
Definition at line 21 of file ccMPlanePoint.cpp.
getName()
QString ccMPlanePoint::getName () const
Definition at line 23 of file ccMPlanePoint.cpp.
References cc2DLabel::getName().
setDistance()
void ccMPlanePoint::setDistance (float distance)
Definition at line 31 of file ccMPlanePoint.cpp.
setName()
void ccMPlanePoint::setName (const QString & newName)
Definition at line 25 of file ccMPlanePoint.cpp.
References ccObject::setName().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qMPlane/src/ccMPlanePoint.h
/root/ACloudViewer/plugins/core/Standard/qMPlane/src/ccMPlanePoint.cpp