ACloudViewer: ccCloudLayersDlg Class Reference
ccCloudLayersDlg Class Reference
#include <ccCloudLayersDlg.h>
Public Member Functions
ccCloudLayersDlg (ecvMainAppInterface *app, QWidget *parent=nullptr)
Default constructor.
virtual ~ccCloudLayersDlg ()
Destructor.
bool start () override
inherited from ccOverlayDialog
void stop (bool accepted) override
Stops process/dialog.
void setPointCloud (ccPointCloud *cloud)
Public Member Functions inherited from ccOverlayDialog
ccOverlayDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::FramelessWindowHint|Qt::Tool)
Default constructor.
~ccOverlayDialog () override
Destructor.
virtual bool linkWith (QWidget *win)
Links the overlay dialog with a MDI window.
void reject () override
void addOverridenShortcut (Qt::Key key)
bool started () const
Returns whether the tool is currently started or not.
Additional Inherited Members
Signals inherited from ccOverlayDialog
void processFinished (bool accepted)
Signal emitted when process is finished.
void shortcutTriggered (int key)
Signal emitted when an overridden key shortcut is pressed.
void shown ()
Signal emitted when a 'show' event is detected.
Protected Slots inherited from ccOverlayDialog
virtual void onLinkedWindowDeletion (QObject *object=nullptr)
Slot called when the linked window is deleted (calls 'onClose')
Protected Member Functions inherited from ccOverlayDialog
bool eventFilter (QObject *obj, QEvent *e) override
Protected Attributes inherited from ccOverlayDialog
QWidget * m_associatedWin
Associated (MDI) window.
bool m_processing
Running/processing state.
QList< int > m_overriddenKeys
Overridden keys.
Detailed Description
Definition at line 39 of file ccCloudLayersDlg.h.
Constructor & Destructor Documentation
ccCloudLayersDlg()
ccCloudLayersDlg::ccCloudLayersDlg (ecvMainAppInterface * app, QWidget * parent = nullptr) explicit
Default constructor.
Definition at line 24 of file ccCloudLayersDlg.cpp.
References ccAsprsModel::codeChanged(), ccAsprsModel::colorChanged(), ecvMainAppInterface::getActiveWindow(), and ccDrawableObject::setVisible().
~ccCloudLayersDlg()
ccCloudLayersDlg::~ccCloudLayersDlg () virtual
Destructor.
Definition at line 79 of file ccCloudLayersDlg.cpp.
References setPointCloud().
Member Function Documentation
setPointCloud()
void ccCloudLayersDlg::setPointCloud (ccPointCloud * cloud)
Definition at line 135 of file ccCloudLayersDlg.cpp.
References ccCloudLayersHelper::getScalarFields().
Referenced by qCloudLayers::doAction(), stop(), and ~ccCloudLayersDlg().
start()
bool ccCloudLayersDlg::start () override virtual
inherited from ccOverlayDialog
Reimplemented from ccOverlayDialog.
Definition at line 101 of file ccCloudLayersDlg.cpp.
References ecvMainAppInterface::freezeUI(), ccAsprsModel::load(), ecvDisplayTools::mouseMoved(), ccOverlayDialog::start(), and ecvDisplayTools::TheInstance().
Referenced by qCloudLayers::doAction().
stop()
void ccCloudLayersDlg::stop (bool accepted) override virtual
Stops process/dialog.
Automatically emits the 'processFinished' signal (with input state as argument).
Parameters
accepted process/dialog result
Reimplemented from ccOverlayDialog.
Definition at line 119 of file ccCloudLayersDlg.cpp.
References ecvMainAppInterface::freezeUI(), ccDrawableObject::isVisible(), ccCloudLayersHelper::keepCurrentSFVisible(), setPointCloud(), and ccOverlayDialog::stop().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qCloudLayers/include/ccCloudLayersDlg.h
/root/ACloudViewer/plugins/core/Standard/qCloudLayers/src/ccCloudLayersDlg.cpp