ACloudViewer: cloudViewer::utility::Timer Class Reference
cloudViewer::utility::Timer Class Reference
#include <Timer.h>
Public Member Functions
Timer ()
~Timer ()
void Start ()
void Stop ()
void Print (const std::string &timer_info) const
double GetDurationInSecond () const
double GetDurationInMillisecond () const
std::tuple< int, int, double > GetDurationInHMS () const
Static Public Member Functions
static double GetSystemTimeInMilliseconds ()
Detailed Description
Definition at line 19 of file Timer.h.
Constructor & Destructor Documentation
Timer()
cloudViewer::utility::Timer::Timer ()
~Timer()
cloudViewer::utility::Timer::~Timer ()
Member Function Documentation
GetDurationInHMS()
std::tuple<int, int, double> cloudViewer::utility::Timer::GetDurationInHMS () const
GetDurationInMillisecond()
double cloudViewer::utility::Timer::GetDurationInMillisecond () const
Referenced by cloudViewer::pipelines::registration::GlobalOptimizationGaussNewton::OptimizePoseGraph(), and cloudViewer::pipelines::registration::GlobalOptimizationLevenbergMarquardt::OptimizePoseGraph().
GetDurationInSecond()
double cloudViewer::utility::Timer::GetDurationInSecond () const
GetSystemTimeInMilliseconds()
static double cloudViewer::utility::Timer::GetSystemTimeInMilliseconds () static
Print()
void cloudViewer::utility::Timer::Print (const std::string & timer_info) const
Start()
void cloudViewer::utility::Timer::Start ()
Referenced by cloudViewer::pipelines::registration::GlobalOptimizationGaussNewton::OptimizePoseGraph(), and cloudViewer::pipelines::registration::GlobalOptimizationLevenbergMarquardt::OptimizePoseGraph().
Stop()
void cloudViewer::utility::Timer::Stop ()
Referenced by cloudViewer::pipelines::registration::GlobalOptimizationGaussNewton::OptimizePoseGraph(), and cloudViewer::pipelines::registration::GlobalOptimizationLevenbergMarquardt::OptimizePoseGraph().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/include/Timer.h