ACloudViewer: G3PointPlots Class Reference
G3PointPlots Class Reference
#include <G3PointPlots.h>
Public Member Functions
G3PointPlots (QString title, QWidget *parent=nullptr)
qCC_db
~G3PointPlots ()
void readSettings ()
void addToTabWidget (QWidget *widget)
void closeCurrentWidget ()
template<typename SharedDataContainer >
bool exportToCSV (QString filename, SharedDataContainer container, const Eigen::Array3d *dq_final=nullptr, const Eigen::Array3d *edq=nullptr) const
void onExportToCSV ()
void onExportToImage ()
void closeEvent (QCloseEvent *event) override
Detailed Description
Definition at line 21 of file G3PointPlots.h.
Constructor & Destructor Documentation
G3PointPlots()
G3PointPlots::G3PointPlots (QString title, QWidget * parent = nullptr) explicit
qCC_db
Definition at line 29 of file G3PointPlots.cpp.
References onExportToCSV(), onExportToImage(), and readSettings().
~G3PointPlots()
G3PointPlots::~G3PointPlots ()
Definition at line 43 of file G3PointPlots.cpp.
Member Function Documentation
addToTabWidget()
void G3PointPlots::addToTabWidget (QWidget * widget)
Definition at line 57 of file G3PointPlots.cpp.
References closeCurrentWidget(), AnglesCustomPlot::closeTab(), and WolmanCustomPlot::closeTab().
closeCurrentWidget()
void G3PointPlots::closeCurrentWidget ()
Definition at line 73 of file G3PointPlots.cpp.
Referenced by addToTabWidget().
closeEvent()
void G3PointPlots::closeEvent (QCloseEvent * event) override
Definition at line 45 of file G3PointPlots.cpp.
References event.
exportToCSV()
template<typename SharedDataContainer > bool G3PointPlots::exportToCSV (QString filename, SharedDataContainer container, const Eigen::Array3d * dq_final = nullptr, const Eigen::Array3d * edq = nullptr) const
Definition at line 78 of file G3PointPlots.cpp.
References QtCompat::endl(), CVLog::Print(), and CVLog::Warning().
onExportToCSV()
void G3PointPlots::onExportToCSV ()
Definition at line 126 of file G3PointPlots.cpp.
References WolmanCustomPlot::dataContainer(), ecvFileUtils::defaultDocPath(), WolmanCustomPlot::m_dq_final, and WolmanCustomPlot::m_edq.
Referenced by G3PointPlots().
onExportToImage()
void G3PointPlots::onExportToImage ()
Definition at line 168 of file G3PointPlots.cpp.
References ecvFileUtils::defaultDocPath(), CVLog::Error(), ImageFileFilter::GetSaveFilename(), image, and CVLog::Print().
Referenced by G3PointPlots().
readSettings()
void G3PointPlots::readSettings ()
Definition at line 52 of file G3PointPlots.cpp.
Referenced by G3PointPlots().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qG3Point/include/G3PointPlots.h
/root/ACloudViewer/plugins/core/Standard/qG3Point/src/G3PointPlots.cpp