ACloudViewer: cloudViewer::utility::CompilerInfo Class Reference
cloudViewer::utility::CompilerInfo Class Reference
Compiler information.
#include <CompilerInfo.h>
Public Member Functions
~CompilerInfo ()=default
CompilerInfo (const CompilerInfo &)=delete
void operator= (const CompilerInfo &)=delete
std::string CXXStandard () const
std::string CXXCompilerId () const
std::string CXXCompilerVersion () const
std::string CUDACompilerId () const
std::string CUDACompilerVersion () const
void Print () const
Static Public Member Functions
static CompilerInfo & GetInstance ()
Detailed Description
Compiler information.
Definition at line 16 of file CompilerInfo.h.
Constructor & Destructor Documentation
~CompilerInfo()
cloudViewer::utility::CompilerInfo::~CompilerInfo () default
CompilerInfo()
cloudViewer::utility::CompilerInfo::CompilerInfo (const CompilerInfo &) delete
Member Function Documentation
CUDACompilerId()
std::string cloudViewer::utility::CompilerInfo::CUDACompilerId () const
Definition at line 37 of file CompilerInfo.cpp.
Referenced by Print().
CUDACompilerVersion()
std::string cloudViewer::utility::CompilerInfo::CUDACompilerVersion () const
Definition at line 41 of file CompilerInfo.cpp.
Referenced by Print().
CXXCompilerId()
std::string cloudViewer::utility::CompilerInfo::CXXCompilerId () const
Definition at line 29 of file CompilerInfo.cpp.
Referenced by Print().
CXXCompilerVersion()
std::string cloudViewer::utility::CompilerInfo::CXXCompilerVersion () const
Definition at line 33 of file CompilerInfo.cpp.
Referenced by Print().
CXXStandard()
std::string cloudViewer::utility::CompilerInfo::CXXStandard () const
Definition at line 25 of file CompilerInfo.cpp.
Referenced by Print().
GetInstance()
CompilerInfo & cloudViewer::utility::CompilerInfo::GetInstance () static
Definition at line 20 of file CompilerInfo.cpp.
operator=()
void cloudViewer::utility::CompilerInfo::operator= (const CompilerInfo &) delete
Print()
void cloudViewer::utility::CompilerInfo::Print () const
Definition at line 45 of file CompilerInfo.cpp.
References CUDACompilerId(), CUDACompilerVersion(), CXXCompilerId(), CXXCompilerVersion(), CXXStandard(), and LogInfo.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/utility/CompilerInfo.h
/root/ACloudViewer/libs/cloudViewer/utility/CompilerInfo.cpp