ACloudViewer: PdmsTools::PdmsObjects::Loop Class Reference
PdmsTools::PdmsObjects::Loop Class Reference
Loop.
#include <PdmsTools.h>
Public Member Functions
Loop ()
virtual ~Loop ()
virtual bool push (GenericItem *i)
virtual void remove (GenericItem *i)
virtual Token getType () const
virtual std::pair< int, int > write (std::ostream &output, int nbtabs=0) const
Public Member Functions inherited from PdmsTools::PdmsObjects::DesignElement
DesignElement ()
virtual ~DesignElement ()
virtual bool isDesignElement ()
virtual PointCoordinateType surface () const
Public Member Functions inherited from PdmsTools::PdmsObjects::GenericItem
GenericItem ()
Default constructor.
virtual ~GenericItem ()
Destructor.
virtual bool setPosition (const CCVector3 &p)
virtual bool setOrientation (const CCVector3 &x, const CCVector3 &y, const CCVector3 &z)
virtual bool convertCoordinateSystem ()
virtual GenericItem * getRoot ()
virtual bool isGroupElement ()
virtual bool setValue (Token t, PointCoordinateType value)
virtual GenericItem * scan (const char *str)
virtual bool scan (Token t, std::vector< GenericItem * > &array)
Public Attributes
std::list< Vertex * > loop
Public Attributes inherited from PdmsTools::PdmsObjects::DesignElement
bool negative
std::list< DesignElement * > nelements
Public Attributes inherited from PdmsTools::PdmsObjects::GenericItem
GenericItem * owner
Parent imte.
GenericItem * creator
Creator item.
CCVector3 position
Object position.
CCVector3 orientation [3]
Object orientation (X,Y and Z)
bool isCoordinateSystemUpToDate
Coordinate system update flag.
GenericItem * positionReference
Reference object (position)
GenericItem * orientationReferences [3]
Reference(s) object(s) (orientation)
char name [c_max_str_length]
Name.
Additional Inherited Members
Protected Member Functions inherited from PdmsTools::PdmsObjects::GenericItem
bool isOrientationValid (unsigned i) const
bool completeOrientation ()
Detailed Description
Loop.
Definition at line 414 of file PdmsTools.h.
Constructor & Destructor Documentation
Loop()
PdmsTools::PdmsObjects::Loop::Loop () inline
Definition at line 418 of file PdmsTools.h.
~Loop()
virtual PdmsTools::PdmsObjects::Loop::~Loop () inline virtual
Definition at line 419 of file PdmsTools.h.
References PdmsTools::PdmsObjects::Stack::Destroy(), and loop.
Member Function Documentation
getType()
virtual Token PdmsTools::PdmsObjects::Loop::getType () const inline virtual
Reimplemented from PdmsTools::PdmsObjects::GenericItem.
Definition at line 430 of file PdmsTools.h.
References PdmsTools::PDMS_LOOP.
push()
bool Loop::push (GenericItem * i) virtual
Reimplemented from PdmsTools::PdmsObjects::DesignElement.
Definition at line 1653 of file PdmsTools.cpp.
References PdmsTools::PdmsObjects::GenericItem::getType(), loop, PdmsTools::PdmsObjects::GenericItem::owner, PdmsTools::PDMS_VERTEX, and PdmsTools::PdmsObjects::GenericItem::remove().
remove()
void Loop::remove (GenericItem * i) virtual
Reimplemented from PdmsTools::PdmsObjects::DesignElement.
Definition at line 1663 of file PdmsTools.cpp.
References loop.
write()
std::pair< int, int > Loop::write (std::ostream & output, int nbtabs = 0) const virtual
Implements PdmsTools::PdmsObjects::GenericItem.
Definition at line 1672 of file PdmsTools.cpp.
Member Data Documentation
loop
std::list<Vertex *> PdmsTools::PdmsObjects::Loop::loop
Definition at line 416 of file PdmsTools.h.
Referenced by PDMSFilter::loadFile(), push(), remove(), PdmsTools::PdmsObjects::Extrusion::surface(), and ~Loop().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qCoreIO/include/PDMS/PdmsTools.h
/root/ACloudViewer/plugins/core/IO/qCoreIO/src/PDMS/PdmsTools.cpp