ACloudViewer: ccWaveform Class Reference
ccWaveform Class Reference
Waveform.
#include <ecvWaveform.h>
Public Member Functions
ccWaveform (uint8_t descriptorID=0)
Default constructor.
~ccWaveform () override=default
Destructor.
uint8_t descriptorID () const
Returns the associated descriptor (ID)
void setDescriptorID (uint8_t id)
Sets the associated descriptor (ID)
void setDataDescription (uint64_t dataOffset, uint32_t byteCount)
Describes the waveform data.
uint32_t getRawSample (uint32_t i, const WaveformDescriptor &descriptor, const uint8_t *dataStorage) const
Returns the (raw) value of a given sample.
double getSample (uint32_t i, const WaveformDescriptor &descriptor, const uint8_t *dataStorage) const
Returns the (real) value of a given sample (in volts)
double getRange (double &minVal, double &maxVal, const WaveformDescriptor &descriptor, const uint8_t *dataStorage) const
Returns the range of (real) samples.
bool decodeSamples (std::vector< double > &values, const WaveformDescriptor &descriptor, const uint8_t *dataStorage) const
Decodes the samples and store them in a vector.
bool toASCII (const QString &filename, const WaveformDescriptor &descriptor, const uint8_t *dataStorage) const
Exports (real) samples to an ASCII file.
CCVector3 getSamplePos (float i, const CCVector3 &P0, const WaveformDescriptor &descriptor) const
Returns the sample position in 3D.
uint32_t byteCount () const
Returns the number of allocated bytes.
uint64_t dataOffset () const
Returns the byte offset to waveform data.
void setDataOffset (uint64_t offset)
Sets the byte offset to waveform data.
const uint8_t * data (const uint8_t *dataStorage) const
Gives access to the internal data.
void setBeamDir (const CCVector3f &dir)
Sets the beam direction.
const CCVector3f & beamDir () const
Returns the beam direction.
void setEchoTime_ps (float time_ps)
Set the echo time (in picoseconds)
float echoTime_ps () const
Returns the echo time (in picoseconds)
void applyRigidTransformation (const ccGLMatrix &trans)
Applies a rigid transformation (on the beam direction)
uint8_t returnIndex () const
Returns the return index.
void setReturnIndex (uint8_t index)
Sets the return index.
bool isSerializable () const override
Returns whether object is serializable of not.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Static Public Member Functions
static bool ToASCII (const QString &filename, std::vector< double > &values, uint32_t samplingRate_ps)
Helper: exports a series of values as an ASCII file.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Protected Attributes
uint32_t m_byteCount
Waveform packet size in bytes.
uint64_t m_dataOffset
Byte offset to waveform data.
CCVector3f m_beamDir
Laser beam direction.
float m_echoTime_ps
Return Point location (in picoseconds)
uint8_t m_descriptorID
Wave Packet descriptor index.
uint8_t m_returnIndex
Return index.
Additional Inherited Members
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Detailed Description
Waveform.
Warning
Waveforms do not own their data!
Definition at line 55 of file ecvWaveform.h.
Constructor & Destructor Documentation
ccWaveform()
ccWaveform::ccWaveform (uint8_t descriptorID = 0)
Default constructor.
~ccWaveform()
ccWaveform::~ccWaveform () override default
Destructor.
Member Function Documentation
applyRigidTransformation()
void ccWaveform::applyRigidTransformation (const ccGLMatrix & trans)
Applies a rigid transformation (on the beam direction)
Referenced by define_ccWaveform().
beamDir()
const CCVector3f& ccWaveform::beamDir () const inline
Returns the beam direction.
Definition at line 129 of file ecvWaveform.h.
Referenced by define_ccWaveform(), LasWaveformSaver::handlePoint(), and LASFWFFilter::saveToFile().
byteCount()
uint32_t ccWaveform::byteCount () const inline
Returns the number of allocated bytes.
Definition at line 112 of file ecvWaveform.h.
Referenced by define_ccWaveform(), LasWaveformSaver::handlePoint(), and LASFWFFilter::saveToFile().
data()
const uint8_t* ccWaveform::data (const uint8_t * dataStorage) const inline
Gives access to the internal data.
Definition at line 121 of file ecvWaveform.h.
dataOffset()
uint64_t ccWaveform::dataOffset () const inline
Returns the byte offset to waveform data.
Definition at line 115 of file ecvWaveform.h.
Referenced by define_ccWaveform(), LasWaveformSaver::handlePoint(), and LASFWFFilter::saveToFile().
decodeSamples()
bool ccWaveform::decodeSamples (std::vector< double > & values, const WaveformDescriptor & descriptor, const uint8_t * dataStorage) const
Decodes the samples and store them in a vector.
descriptorID()
uint8_t ccWaveform::descriptorID () const inline
Returns the associated descriptor (ID)
Warning
A value of zero indicates that there is no associated waveform data.
Definition at line 67 of file ecvWaveform.h.
Referenced by define_ccWaveform(), and LasWaveformSaver::handlePoint().
echoTime_ps()
float ccWaveform::echoTime_ps () const inline
Returns the echo time (in picoseconds)
Definition at line 135 of file ecvWaveform.h.
Referenced by define_ccWaveform(), LasWaveformSaver::handlePoint(), and LASFWFFilter::saveToFile().
fromFile()
bool ccWaveform::fromFile (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override virtual
Loads data from binary stream.
Parameters
in input file (already opened)
dataVersion file version (for version-specific deserialization)
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Returns
success
Note: When implementing, use dataVersion checks to handle different
versions:
if (dataVersion >= X) { read new field } else { use default value } This ensures forward compatibility with older file formats.
Reimplemented from ccSerializableObject.
getRange()
double ccWaveform::getRange (double & minVal, double & maxVal, const WaveformDescriptor & descriptor, const uint8_t * dataStorage) const
Returns the range of (real) samples.
getRawSample()
uint32_t ccWaveform::getRawSample (uint32_t i, const WaveformDescriptor & descriptor, const uint8_t * dataStorage) const
Returns the (raw) value of a given sample.
Referenced by define_ccWaveform().
getSample()
double ccWaveform::getSample (uint32_t i, const WaveformDescriptor & descriptor, const uint8_t * dataStorage) const
Returns the (real) value of a given sample (in volts)
getSamplePos()
CCVector3 ccWaveform::getSamplePos (float i, const CCVector3 & P0, const WaveformDescriptor & descriptor) const
Returns the sample position in 3D.
Referenced by define_ccWaveform().
isSerializable()
bool ccWaveform::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccSerializableObject.
Definition at line 146 of file ecvWaveform.h.
minimumFileVersion()
short ccWaveform::minimumFileVersion () const override virtual
Returns the minimum file version required to save this instance.
To be overridden by subclasses to indicate their minimum required version. This enables the system to determine:
Forward compatibility: newer software can read older files (dataVersion check in fromFile)
Backward compatibility: determine minimum version needed to save current data
Returns
minimum file version required for this object
Implements ccSerializableObject.
returnIndex()
uint8_t ccWaveform::returnIndex () const inline
Returns the return index.
Definition at line 141 of file ecvWaveform.h.
Referenced by define_ccWaveform(), and LASFWFFilter::saveToFile().
setBeamDir()
void ccWaveform::setBeamDir (const CCVector3f & dir) inline
Sets the beam direction.
Definition at line 126 of file ecvWaveform.h.
Referenced by define_ccWaveform(), LASFWFFilter::loadFile(), and LasWaveformLoader::loadWaveform().
setDataDescription()
void ccWaveform::setDataDescription (uint64_t dataOffset, uint32_t byteCount)
Describes the waveform data.
Referenced by define_ccWaveform(), LASFWFFilter::loadFile(), and LasWaveformLoader::loadWaveform().
setDataOffset()
void ccWaveform::setDataOffset (uint64_t offset) inline
Sets the byte offset to waveform data.
Definition at line 118 of file ecvWaveform.h.
References offset.
Referenced by define_ccWaveform().
setDescriptorID()
void ccWaveform::setDescriptorID (uint8_t id) inline
Sets the associated descriptor (ID)
Definition at line 70 of file ecvWaveform.h.
Referenced by define_ccWaveform(), LASFWFFilter::loadFile(), and LasWaveformLoader::loadWaveform().
setEchoTime_ps()
void ccWaveform::setEchoTime_ps (float time_ps) inline
Set the echo time (in picoseconds)
Definition at line 132 of file ecvWaveform.h.
Referenced by define_ccWaveform(), LASFWFFilter::loadFile(), and LasWaveformLoader::loadWaveform().
setReturnIndex()
void ccWaveform::setReturnIndex (uint8_t index) inline
Sets the return index.
Definition at line 143 of file ecvWaveform.h.
Referenced by define_ccWaveform(), LASFWFFilter::loadFile(), and LasWaveformLoader::loadWaveform().
toASCII()
bool ccWaveform::toASCII (const QString & filename, const WaveformDescriptor & descriptor, const uint8_t * dataStorage) const
Exports (real) samples to an ASCII file.
Referenced by define_ccWaveform().
ToASCII()
static bool ccWaveform::ToASCII (const QString & filename, std::vector< double > & values, uint32_t samplingRate_ps) static
Helper: exports a series of values as an ASCII file.
Referenced by define_ccWaveform().
toFile()
bool ccWaveform::toFile (QFile & out, short dataVersion) const override virtual
Saves data to binary stream.
Parameters
out output file (already opened)
dataVersion target file version (for forward/backward compatibility)
Returns
success
Reimplemented from ccSerializableObject.
Member Data Documentation
m_beamDir
CCVector3f ccWaveform::m_beamDir protected
Laser beam direction.
Parametric line equation for extrapolating points along the associated waveform: X = X0 + X(t) Y = Y0 + Y(t) Z = Z0 + Z(t)
Definition at line 167 of file ecvWaveform.h.
m_byteCount
uint32_t ccWaveform::m_byteCount protected
Waveform packet size in bytes.
Warning
Not necessarily equal to the number of samples!
Definition at line 158 of file ecvWaveform.h.
m_dataOffset
uint64_t ccWaveform::m_dataOffset protected
Byte offset to waveform data.
Definition at line 161 of file ecvWaveform.h.
m_descriptorID
uint8_t ccWaveform::m_descriptorID protected
Wave Packet descriptor index.
Warning
A value of zero indicates that there is no associated waveform data.
Definition at line 180 of file ecvWaveform.h.
m_echoTime_ps
float ccWaveform::m_echoTime_ps protected
Return Point location (in picoseconds)
The offset in picoseconds from the first digitized value to the location within the waveform packet that the associated return pulse was detected.
Definition at line 174 of file ecvWaveform.h.
m_returnIndex
uint8_t ccWaveform::m_returnIndex protected
Return index.
Definition at line 183 of file ecvWaveform.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvWaveform.h