ACloudViewer: ccConsoleOutput Class Reference
ccConsoleOutput Class Reference
Redirects messages to ACloudViewer's console output.
#include <Consoles.h>
Public Member Functions
ccConsoleOutput ()=default
ccConsoleOutput (const char *prefix)
void write (const char *messagePart)
bool isatty () const
void flush () const
Detailed Description
Redirects messages to ACloudViewer's console output.
Definition at line 76 of file Consoles.h.
Constructor & Destructor Documentation
ccConsoleOutput() [1/2]
ccConsoleOutput::ccConsoleOutput () default
ccConsoleOutput() [2/2]
ccConsoleOutput::ccConsoleOutput (const char * prefix) inline explicit
Definition at line 80 of file Consoles.h.
Member Function Documentation
flush()
void ccConsoleOutput::flush () const inline
Definition at line 99 of file Consoles.h.
References ConsoleWrapper::flush().
Referenced by PYBIND11_EMBEDDED_MODULE().
isatty()
bool ccConsoleOutput::isatty () const inline
Definition at line 94 of file Consoles.h.
Referenced by PYBIND11_EMBEDDED_MODULE().
write()
void ccConsoleOutput::write (const char * messagePart) inline
Definition at line 82 of file Consoles.h.
References CVLog::Warning(), and ConsoleWrapper::write().
Referenced by PYBIND11_EMBEDDED_MODULE().
The documentation for this class was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/Runtime/Consoles.h