ACloudViewer: colmap::FeatureImageViewerWidget Class Reference
colmap::FeatureImageViewerWidget Class Reference
#include <image_viewer_widget.h>
Public Member Functions
FeatureImageViewerWidget (QWidget *parent, const std::string &switch_text)
void ReadAndShowWithKeypoints (const std::string &path, const FeatureKeypoints &keypoints, const std::vector< char > &tri_mask)
void ReadAndShowWithMatches (const std::string &path1, const std::string &path2, const FeatureKeypoints &keypoints1, const FeatureKeypoints &keypoints2, const FeatureMatches &matches)
Public Member Functions inherited from colmap::ImageViewerWidget
ImageViewerWidget (QWidget *parent)
void ShowBitmap (const Bitmap &bitmap)
void ShowPixmap (const QPixmap &pixmap)
void ReadAndShow (const std::string &path)
Protected Member Functions
void ShowOrHide ()
Protected Member Functions inherited from colmap::ImageViewerWidget
void resizeEvent (QResizeEvent *event)
void closeEvent (QCloseEvent *event)
void ZoomIn ()
void ZoomOut ()
void Save ()
Protected Attributes
QPixmap image1_
QPixmap image2_
bool switch_state_
QPushButton * switch_button_
const std::string switch_text_
Protected Attributes inherited from colmap::ImageViewerWidget
QGridLayout * grid_layout_
QHBoxLayout * button_layout_
Detailed Description
Definition at line 58 of file image_viewer_widget.h.
Constructor & Destructor Documentation
FeatureImageViewerWidget()
colmap::FeatureImageViewerWidget::FeatureImageViewerWidget (QWidget * parent, const std::string & switch_text)
Definition at line 155 of file image_viewer_widget.cc.
References colmap::ImageViewerWidget::button_layout_, ShowOrHide(), switch_button_, and switch_text_.
Member Function Documentation
ReadAndShowWithKeypoints()
void colmap::FeatureImageViewerWidget::ReadAndShowWithKeypoints (const std::string & path, const FeatureKeypoints & keypoints, const std::vector< char > & tri_mask)
Definition at line 167 of file image_viewer_widget.cc.
References colmap::BitmapToQImageRGB(), colmap::DrawKeypoints(), QtCompat::endl(), image1_, image2_, ecvColor::magenta(), cloudViewer::t::geometry::path, colmap::Bitmap::Read(), ecvColor::red(), colmap::ImageViewerWidget::ShowPixmap(), and switch_state_.
Referenced by colmap::DatabaseImageViewerWidget::ShowImageWithId().
ReadAndShowWithMatches()
void colmap::FeatureImageViewerWidget::ReadAndShowWithMatches (const std::string & path1, const std::string & path2, const FeatureKeypoints & keypoints1, const FeatureKeypoints & keypoints2, const FeatureMatches & matches)
Definition at line 205 of file image_viewer_widget.cc.
References colmap::BitmapToQImageRGB(), colmap::DrawMatches(), QtCompat::endl(), image1_, image2_, colmap::Bitmap::Read(), colmap::ShowImagesSideBySide(), colmap::ImageViewerWidget::ShowPixmap(), and switch_state_.
Referenced by colmap::TwoViewInfoTab::ShowMatches().
ShowOrHide()
void colmap::FeatureImageViewerWidget::ShowOrHide () protected
Definition at line 230 of file image_viewer_widget.cc.
References image1_, image2_, colmap::ImageViewerWidget::ShowPixmap(), switch_button_, switch_state_, and switch_text_.
Referenced by FeatureImageViewerWidget().
Member Data Documentation
image1_
QPixmap colmap::FeatureImageViewerWidget::image1_ protected
Definition at line 75 of file image_viewer_widget.h.
Referenced by ReadAndShowWithKeypoints(), ReadAndShowWithMatches(), and ShowOrHide().
image2_
QPixmap colmap::FeatureImageViewerWidget::image2_ protected
Definition at line 76 of file image_viewer_widget.h.
Referenced by ReadAndShowWithKeypoints(), ReadAndShowWithMatches(), and ShowOrHide().
switch_button_
QPushButton* colmap::FeatureImageViewerWidget::switch_button_ protected
Definition at line 78 of file image_viewer_widget.h.
Referenced by FeatureImageViewerWidget(), and ShowOrHide().
switch_state_
bool colmap::FeatureImageViewerWidget::switch_state_ protected
Definition at line 77 of file image_viewer_widget.h.
Referenced by ReadAndShowWithKeypoints(), ReadAndShowWithMatches(), and ShowOrHide().
switch_text_
const std::string colmap::FeatureImageViewerWidget::switch_text_ protected
Definition at line 79 of file image_viewer_widget.h.
Referenced by FeatureImageViewerWidget(), and ShowOrHide().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/image_viewer_widget.h
/root/ACloudViewer/libs/Reconstruction/src/ui/image_viewer_widget.cc