ACloudViewer: cloudViewer::visualization::rendering::Renderer Class Reference
cloudViewer::visualization::rendering::Renderer Class Reference abstract
#include <Renderer.h>
Public Member Functions
virtual ~Renderer ()=default
virtual SceneHandle CreateScene ()=0
virtual Scene * GetScene (const SceneHandle &id) const =0
virtual void DestroyScene (const SceneHandle &id)=0
virtual void SetClearColor (const Eigen::Vector4f &color)=0
virtual void UpdateSwapChain ()=0
virtual void UpdateBitmapSwapChain (int width, int height)=0
virtual void BeginFrame ()=0
virtual void Draw ()=0
virtual void RequestReadPixels (int width, int height, std::function< void(std::shared_ptr< core::Tensor >)> callback)=0
virtual void EndFrame ()=0
virtual void SetOnAfterDraw (std::function< void()> callback)=0
virtual MaterialHandle AddMaterial (const ResourceLoadRequest &request)=0
virtual MaterialInstanceHandle AddMaterialInstance (const MaterialHandle &material)=0
virtual MaterialModifier & ModifyMaterial (const MaterialHandle &id)=0
virtual MaterialModifier & ModifyMaterial (const MaterialInstanceHandle &id)=0
virtual void RemoveMaterialInstance (const MaterialInstanceHandle &id)=0
virtual TextureHandle AddTexture (const ResourceLoadRequest &request, bool srgb=false)=0
virtual TextureHandle AddTexture (const std::shared_ptr< geometry::Image > image, bool srgb=false)=0
virtual TextureHandle AddTexture (const t::geometry::Image &image, bool srgb=false)=0
virtual bool UpdateTexture (TextureHandle texture, const std::shared_ptr< geometry::Image > image, bool srgb)=0
virtual bool UpdateTexture (TextureHandle texture, const t::geometry::Image &image, bool srgb)=0
virtual void RemoveTexture (const TextureHandle &id)=0
virtual IndirectLightHandle AddIndirectLight (const ResourceLoadRequest &request)=0
virtual void RemoveIndirectLight (const IndirectLightHandle &id)=0
virtual SkyboxHandle AddSkybox (const ResourceLoadRequest &request)=0
virtual void RemoveSkybox (const SkyboxHandle &id)=0
virtual std::shared_ptr< RenderToBuffer > CreateBufferRenderer ()=0
void RenderToImage (View *view, Scene *scene, std::function< void(std::shared_ptr< geometry::Image >)> cb)
void RenderToDepthImage (View *view, Scene *scene, std::function< void(std::shared_ptr< geometry::Image >)> cb, bool z_in_view_space=false)
Detailed Description
Definition at line 58 of file Renderer.h.
Constructor & Destructor Documentation
~Renderer()
virtual cloudViewer::visualization::rendering::Renderer::~Renderer () virtual default
Member Function Documentation
AddIndirectLight()
virtual IndirectLightHandle cloudViewer::visualization::rendering::Renderer::AddIndirectLight (const ResourceLoadRequest & request) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Referenced by cloudViewer::visualization::rendering::FilamentScene::SetIndirectLight().
AddMaterial()
virtual MaterialHandle cloudViewer::visualization::rendering::Renderer::AddMaterial (const ResourceLoadRequest & request) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
AddMaterialInstance()
virtual MaterialInstanceHandle cloudViewer::visualization::rendering::Renderer::AddMaterialInstance (const MaterialHandle & material) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
AddSkybox()
virtual SkyboxHandle cloudViewer::visualization::rendering::Renderer::AddSkybox (const ResourceLoadRequest & request) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Referenced by cloudViewer::visualization::rendering::FilamentScene::SetIndirectLight().
AddTexture() [1/3]
virtual TextureHandle cloudViewer::visualization::rendering::Renderer::AddTexture (const ResourceLoadRequest & request, bool srgb = false) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Referenced by cloudViewer::visualization::gui::UIImage::CalcDrawParams(), cloudViewer::visualization::rendering::Gradient::GetTextureHandle(), and cloudViewer::visualization::rendering::pybind_rendering_classes().
AddTexture() [2/3]
virtual TextureHandle cloudViewer::visualization::rendering::Renderer::AddTexture (const std::shared_ptr< geometry::Image > image, bool srgb = false) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
AddTexture() [3/3]
virtual TextureHandle cloudViewer::visualization::rendering::Renderer::AddTexture (const t::geometry::Image & image, bool srgb = false) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
BeginFrame()
virtual void cloudViewer::visualization::rendering::Renderer::BeginFrame () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Referenced by cloudViewer::visualization::gui::Application::RenderToDepthImage(), and cloudViewer::visualization::gui::Application::RenderToImage().
CreateBufferRenderer()
virtual std::shared_ptr<RenderToBuffer> cloudViewer::visualization::rendering::Renderer::CreateBufferRenderer () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Referenced by RenderToDepthImage(), and RenderToImage().
CreateScene()
virtual SceneHandle cloudViewer::visualization::rendering::Renderer::CreateScene () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Referenced by cloudViewer::visualization::rendering::CloudViewerScene::CloudViewerScene().
DestroyScene()
virtual void cloudViewer::visualization::rendering::Renderer::DestroyScene (const SceneHandle & id) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Draw()
virtual void cloudViewer::visualization::rendering::Renderer::Draw () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
EndFrame()
virtual void cloudViewer::visualization::rendering::Renderer::EndFrame () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Referenced by cloudViewer::visualization::gui::Application::RenderToDepthImage(), and cloudViewer::visualization::gui::Application::RenderToImage().
GetScene()
virtual Scene* cloudViewer::visualization::rendering::Renderer::GetScene (const SceneHandle & id) const pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Referenced by cloudViewer::visualization::rendering::CloudViewerScene::AddGeometry(), cloudViewer::visualization::rendering::CloudViewerScene::AddModel(), cloudViewer::visualization::rendering::CloudViewerScene::ClearGeometry(), cloudViewer::visualization::rendering::CloudViewerScene::CloudViewerScene(), cloudViewer::visualization::rendering::CloudViewerScene::GeometryIsVisible(), cloudViewer::visualization::rendering::CloudViewerScene::GetCamera(), cloudViewer::visualization::rendering::CloudViewerScene::GetGeometryTransform(), cloudViewer::visualization::rendering::CloudViewerScene::GetScene(), cloudViewer::visualization::rendering::CloudViewerScene::GetView(), cloudViewer::visualization::rendering::CloudViewerScene::HasGeometry(), cloudViewer::visualization::rendering::CloudViewerScene::ModifyGeometryMaterial(), cloudViewer::visualization::rendering::CloudViewerScene::RemoveGeometry(), cloudViewer::visualization::rendering::CloudViewerScene::SetBackground(), cloudViewer::visualization::rendering::CloudViewerScene::SetGeometryTransform(), cloudViewer::visualization::rendering::CloudViewerScene::SetLighting(), cloudViewer::visualization::rendering::CloudViewerScene::ShowAxes(), cloudViewer::visualization::rendering::CloudViewerScene::ShowGroundPlane(), cloudViewer::visualization::rendering::CloudViewerScene::ShowSkybox(), cloudViewer::visualization::rendering::CloudViewerScene::UpdateMaterial(), cloudViewer::visualization::rendering::CloudViewerScene::UpdateModelMaterial(), and cloudViewer::visualization::rendering::CloudViewerScene::~CloudViewerScene().
ModifyMaterial() [1/2]
virtual MaterialModifier& cloudViewer::visualization::rendering::Renderer::ModifyMaterial (const MaterialHandle & id) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Referenced by cloudViewer::visualization::rendering::FilamentScene::SetBackground().
ModifyMaterial() [2/2]
virtual MaterialModifier& cloudViewer::visualization::rendering::Renderer::ModifyMaterial (const MaterialInstanceHandle & id) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
RemoveIndirectLight()
virtual void cloudViewer::visualization::rendering::Renderer::RemoveIndirectLight (const IndirectLightHandle & id) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
RemoveMaterialInstance()
virtual void cloudViewer::visualization::rendering::Renderer::RemoveMaterialInstance (const MaterialInstanceHandle & id) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
RemoveSkybox()
virtual void cloudViewer::visualization::rendering::Renderer::RemoveSkybox (const SkyboxHandle & id) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
RemoveTexture()
virtual void cloudViewer::visualization::rendering::Renderer::RemoveTexture (const TextureHandle & id) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
RenderToDepthImage()
void cloudViewer::visualization::rendering::Renderer::RenderToDepthImage (View * view, Scene * scene, std::function< void(std::shared_ptr< geometry::Image >)> cb, bool z_in_view_space = false)
Definition at line 95 of file Renderer.cpp.
References cloudViewer::visualization::rendering::RenderToBuffer::Buffer::bytes, CreateBufferRenderer(), cloudViewer::visualization::rendering::View::GetCamera(), cloudViewer::visualization::rendering::Camera::GetNear(), cloudViewer::visualization::rendering::View::GetViewport(), cloudViewer::visualization::rendering::RenderToBuffer::Buffer::height, image, infinity(), cloudViewer::visualization::rendering::RenderToBuffer::Buffer::size, and cloudViewer::visualization::rendering::RenderToBuffer::Buffer::width.
Referenced by cloudViewer::visualization::gui::Application::RenderToDepthImage(), and cloudViewer::visualization::rendering::FilamentScene::RenderToDepthImage().
RenderToImage()
void cloudViewer::visualization::rendering::Renderer::RenderToImage (View * view, Scene * scene, std::function< void(std::shared_ptr< geometry::Image >)> cb)
Definition at line 68 of file Renderer.cpp.
References cloudViewer::visualization::rendering::RenderToBuffer::Buffer::bytes, CreateBufferRenderer(), cloudViewer::visualization::rendering::View::GetViewport(), cloudViewer::visualization::rendering::RenderToBuffer::Buffer::height, image, cloudViewer::visualization::rendering::RenderToBuffer::Buffer::size, and cloudViewer::visualization::rendering::RenderToBuffer::Buffer::width.
Referenced by cloudViewer::visualization::gui::Application::RenderToImage(), and cloudViewer::visualization::rendering::FilamentScene::RenderToImage().
RequestReadPixels()
virtual void cloudViewer::visualization::rendering::Renderer::RequestReadPixels (int width, int height, std::function< void(std::shared_ptr< core::Tensor >)> callback) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
SetClearColor()
virtual void cloudViewer::visualization::rendering::Renderer::SetClearColor (const Eigen::Vector4f & color) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Referenced by cloudViewer::visualization::rendering::pybind_rendering_classes().
SetOnAfterDraw()
virtual void cloudViewer::visualization::rendering::Renderer::SetOnAfterDraw (std::function< void()> callback) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
UpdateBitmapSwapChain()
virtual void cloudViewer::visualization::rendering::Renderer::UpdateBitmapSwapChain (int width, int height) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
UpdateSwapChain()
virtual void cloudViewer::visualization::rendering::Renderer::UpdateSwapChain () pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
UpdateTexture() [1/2]
virtual bool cloudViewer::visualization::rendering::Renderer::UpdateTexture (TextureHandle texture, const std::shared_ptr< geometry::Image > image, bool srgb) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
Referenced by cloudViewer::visualization::gui::UIImage::CalcDrawParams(), and cloudViewer::visualization::rendering::pybind_rendering_classes().
UpdateTexture() [2/2]
virtual bool cloudViewer::visualization::rendering::Renderer::UpdateTexture (TextureHandle texture, const t::geometry::Image & image, bool srgb) pure virtual
Implemented in cloudViewer::visualization::rendering::FilamentRenderer.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/Renderer.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/Renderer.cpp