ACloudViewer: vtkPVInteractorStyle Class Reference
vtkPVInteractorStyle Class Reference
#include <vtkPVInteractorStyle.h>
Public Member Functions
vtkTypeMacro (vtkPVInteractorStyle, vtkInteractorStyleTrackballCamera)
void PrintSelf (ostream &os, vtkIndent indent) override
void OnMouseMove () override
void OnLeftButtonDown () override
void OnLeftButtonUp () override
void OnMiddleButtonDown () override
void OnMiddleButtonUp () override
void OnRightButtonDown () override
void OnRightButtonUp () override
void OnKeyDown () override
void OnKeyUp () override
void OnChar () override
void AddManipulator (vtkCameraManipulator *m)
void RemoveAllManipulators ()
vtkGetObjectMacro (CameraManipulators, vtkCollection)
vtkSetVector3Macro (CenterOfRotation, double)
vtkGetVector3Macro (CenterOfRotation, double)
vtkSetMacro (RotationFactor, double)
vtkGetMacro (RotationFactor, double)
virtual vtkCameraManipulator * FindManipulator (int button, int shift, int control)
Static Public Member Functions
static vtkPVInteractorStyle * New ()
static void DollyToPosition (double fact, int *position, vtkRenderer *renderer)
static void TranslateCamera (vtkRenderer *renderer, int toX, int toY, int fromX, int fromY)
Protected Member Functions
vtkPVInteractorStyle ()
~vtkPVInteractorStyle () override
void Dolly (double factor) override
void OnButtonDown (int button, int shift, int control)
void OnButtonUp (int button)
void ResetLights ()
vtkPVInteractorStyle (const vtkPVInteractorStyle &)=delete
void operator= (const vtkPVInteractorStyle &)=delete
Protected Attributes
vtkCameraManipulator * CurrentManipulator
double CenterOfRotation [3]
double RotationFactor
vtkCollection * CameraManipulators
Detailed Description
Definition at line 16 of file vtkPVInteractorStyle.h.
Constructor & Destructor Documentation
vtkPVInteractorStyle() [1/2]
vtkPVInteractorStyle::vtkPVInteractorStyle () protected
Definition at line 32 of file vtkPVInteractorStyle.cxx.
References CameraManipulators, CenterOfRotation, CurrentManipulator, NULL, and RotationFactor.
~vtkPVInteractorStyle()
vtkPVInteractorStyle::~vtkPVInteractorStyle () override protected
Definition at line 42 of file vtkPVInteractorStyle.cxx.
References CameraManipulators, and NULL.
vtkPVInteractorStyle() [2/2]
vtkPVInteractorStyle::vtkPVInteractorStyle (const vtkPVInteractorStyle &) protected delete
Member Function Documentation
AddManipulator()
void vtkPVInteractorStyle::AddManipulator (vtkCameraManipulator * m)
Access to adding or removing manipulators.
Definition at line 55 of file vtkPVInteractorStyle.cxx.
References CameraManipulators.
Dolly()
void vtkPVInteractorStyle::Dolly (double factor) override protected
Definition at line 246 of file vtkPVInteractorStyle.cxx.
References DollyToPosition().
DollyToPosition()
void vtkPVInteractorStyle::DollyToPosition (double fact, int * position, vtkRenderer * renderer) static
Dolly the renderer's camera to a specific point
Definition at line 260 of file vtkPVInteractorStyle.cxx.
References position, and TranslateCamera().
Referenced by Dolly(), and vtkPVTrackballZoomToMouse::OnMouseMove().
FindManipulator()
vtkCameraManipulator * vtkPVInteractorStyle::FindManipulator (int button, int shift, int control) virtual
Returns the chosen manipulator based on the modifiers.
Definition at line 110 of file vtkPVInteractorStyle.cxx.
References CameraManipulators, and NULL.
Referenced by OnButtonDown().
New()
static vtkPVInteractorStyle* vtkPVInteractorStyle::New () static
OnButtonDown()
void vtkPVInteractorStyle::OnButtonDown (int button, int shift, int control) protected
Definition at line 79 of file vtkPVInteractorStyle.cxx.
References CenterOfRotation, CurrentManipulator, FindManipulator(), NULL, vtkCameraManipulator::OnButtonDown(), RotationFactor, and vtkCameraManipulator::StartInteraction().
Referenced by OnLeftButtonDown(), OnMiddleButtonDown(), and OnRightButtonDown().
OnButtonUp()
void vtkPVInteractorStyle::OnButtonUp (int button) protected
Definition at line 143 of file vtkPVInteractorStyle.cxx.
References CurrentManipulator, vtkCameraManipulator::EndInteraction(), NULL, and vtkCameraManipulator::OnButtonUp().
Referenced by OnLeftButtonUp(), OnMiddleButtonUp(), and OnRightButtonUp().
OnChar()
void vtkPVInteractorStyle::OnChar () override
Overrides superclass behaviors to only support the key codes that make sense in a ParaView application.
Definition at line 183 of file vtkPVInteractorStyle.cxx.
OnKeyDown()
void vtkPVInteractorStyle::OnKeyDown () override
Unlike mouse events, these are forwarded to all camera manipulators since we don't have a mechanism to activate a manipulator by key presses currently.
Definition at line 223 of file vtkPVInteractorStyle.cxx.
References CameraManipulators, NULL, and vtkCameraManipulator::OnKeyDown().
OnKeyUp()
void vtkPVInteractorStyle::OnKeyUp () override
Definition at line 235 of file vtkPVInteractorStyle.cxx.
References CameraManipulators, NULL, and vtkCameraManipulator::OnKeyUp().
OnLeftButtonDown()
void vtkPVInteractorStyle::OnLeftButtonDown () override
Definition at line 61 of file vtkPVInteractorStyle.cxx.
References OnButtonDown().
OnLeftButtonUp()
void vtkPVInteractorStyle::OnLeftButtonUp () override
Definition at line 127 of file vtkPVInteractorStyle.cxx.
References OnButtonUp().
OnMiddleButtonDown()
void vtkPVInteractorStyle::OnMiddleButtonDown () override
Definition at line 67 of file vtkPVInteractorStyle.cxx.
References OnButtonDown().
OnMiddleButtonUp()
void vtkPVInteractorStyle::OnMiddleButtonUp () override
Definition at line 132 of file vtkPVInteractorStyle.cxx.
References OnButtonUp().
OnMouseMove()
void vtkPVInteractorStyle::OnMouseMove () override
Event bindings controlling the effects of pressing mouse buttons or moving the mouse.
Definition at line 161 of file vtkPVInteractorStyle.cxx.
References CurrentManipulator, and vtkCameraManipulator::OnMouseMove().
OnRightButtonDown()
void vtkPVInteractorStyle::OnRightButtonDown () override
Definition at line 73 of file vtkPVInteractorStyle.cxx.
References OnButtonDown().
OnRightButtonUp()
void vtkPVInteractorStyle::OnRightButtonUp () override
Definition at line 137 of file vtkPVInteractorStyle.cxx.
References OnButtonUp().
operator=()
void vtkPVInteractorStyle::operator= (const vtkPVInteractorStyle &) protected delete
PrintSelf()
void vtkPVInteractorStyle::PrintSelf (ostream & os, vtkIndent indent) override
Definition at line 346 of file vtkPVInteractorStyle.cxx.
References CameraManipulators, CenterOfRotation, QtCompat::endl(), and RotationFactor.
RemoveAllManipulators()
void vtkPVInteractorStyle::RemoveAllManipulators ()
Removes all manipulators.
Definition at line 49 of file vtkPVInteractorStyle.cxx.
References CameraManipulators.
ResetLights()
void vtkPVInteractorStyle::ResetLights () protected
Definition at line 200 of file vtkPVInteractorStyle.cxx.
References ecvColor::light().
TranslateCamera()
void vtkPVInteractorStyle::TranslateCamera (vtkRenderer * renderer, int toX, int toY, int fromX, int fromY) static
Translate the renderer's camera
Definition at line 314 of file vtkPVInteractorStyle.cxx.
Referenced by DollyToPosition().
vtkGetMacro()
vtkPVInteractorStyle::vtkGetMacro (RotationFactor , double)
vtkGetObjectMacro()
vtkPVInteractorStyle::vtkGetObjectMacro (CameraManipulators , vtkCollection)
Accessor for the collection of camera manipulators.
vtkGetVector3Macro()
vtkPVInteractorStyle::vtkGetVector3Macro (CenterOfRotation , double)
vtkSetMacro()
vtkPVInteractorStyle::vtkSetMacro (RotationFactor , double)
Propagates the rotation factor to the manipulators. This simply sets an internal ivar. It is propagated to a manipulator before the event is sent to it. Also changing the RotationFactor during interaction i.e. after a button press but before a button up has no effect until the next button press.
vtkSetVector3Macro()
vtkPVInteractorStyle::vtkSetVector3Macro (CenterOfRotation , double)
Propagates the center to the manipulators. This simply sets an internal ivar. It is propagated to a manipulator before the event is sent to it. Also changing the CenterOfRotation during interaction i.e. after a button press but before a button up has no effect until the next button press.
vtkTypeMacro()
vtkPVInteractorStyle::vtkTypeMacro (vtkPVInteractorStyle , vtkInteractorStyleTrackballCamera)
Member Data Documentation
CameraManipulators
vtkCollection* vtkPVInteractorStyle::CameraManipulators protected
Definition at line 131 of file vtkPVInteractorStyle.h.
Referenced by AddManipulator(), FindManipulator(), OnKeyDown(), OnKeyUp(), PrintSelf(), RemoveAllManipulators(), vtkPVInteractorStyle(), and ~vtkPVInteractorStyle().
CenterOfRotation
double vtkPVInteractorStyle::CenterOfRotation[3] protected
Definition at line 127 of file vtkPVInteractorStyle.h.
Referenced by OnButtonDown(), PrintSelf(), and vtkPVInteractorStyle().
CurrentManipulator
vtkCameraManipulator* vtkPVInteractorStyle::CurrentManipulator protected
Definition at line 126 of file vtkPVInteractorStyle.h.
Referenced by OnButtonDown(), OnButtonUp(), OnMouseMove(), and vtkPVInteractorStyle().
RotationFactor
double vtkPVInteractorStyle::RotationFactor protected
Definition at line 128 of file vtkPVInteractorStyle.h.
Referenced by OnButtonDown(), PrintSelf(), and vtkPVInteractorStyle().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/InteractionStyle/vtkPVInteractorStyle.h
/root/ACloudViewer/libs/PCLEngine/VTKExtensions/InteractionStyle/vtkPVInteractorStyle.cxx