ACloudViewer: colmap::TwoViewGeometryVerifier Class Reference
colmap::TwoViewGeometryVerifier Class Reference
#include <matching.h>
Public Types
typedef internal::FeatureMatcherData Input
typedef internal::FeatureMatcherData Output
Public Types inherited from colmap::Thread
enum { STARTED_CALLBACK = INT_MIN , FINISHED_CALLBACK }
Public Member Functions
TwoViewGeometryVerifier (const SiftMatchingOptions &options, FeatureMatcherCache *cache, JobQueue< Input > *input_queue, JobQueue< Output > *output_queue)
Public Member Functions inherited from colmap::Thread
Thread ()
virtual ~Thread ()=default
virtual void Start ()
virtual void Stop ()
virtual void Pause ()
virtual void Resume ()
virtual void Wait ()
bool IsStarted ()
bool IsStopped ()
bool IsPaused ()
bool IsRunning ()
bool IsFinished ()
void BlockIfPaused ()
bool CheckValidSetup ()
void AddCallback (const int id, const std::function< void()> &func)
const Timer & GetTimer () const
Protected Member Functions
void Run () override
Protected Member Functions inherited from colmap::Thread
void RegisterCallback (const int id)
void Callback (const int id) const
std::thread::id GetThreadId () const
void SignalValidSetup ()
void SignalInvalidSetup ()
Protected Attributes
const SiftMatchingOptions options_
TwoViewGeometry::Options two_view_geometry_options_
FeatureMatcherCache * cache_
JobQueue< Input > * input_queue_
JobQueue< Output > * output_queue_
Detailed Description
Definition at line 308 of file matching.h.
Member Typedef Documentation
Input
typedef internal::FeatureMatcherData colmap::TwoViewGeometryVerifier::Input
Definition at line 310 of file matching.h.
Output
typedef internal::FeatureMatcherData colmap::TwoViewGeometryVerifier::Output
Definition at line 311 of file matching.h.
Constructor & Destructor Documentation
TwoViewGeometryVerifier()
colmap::TwoViewGeometryVerifier::TwoViewGeometryVerifier (const SiftMatchingOptions & options, FeatureMatcherCache * cache, JobQueue< Input > * input_queue, JobQueue< Output > * output_queue)
Definition at line 656 of file matching.cc.
Member Function Documentation
Run()
void colmap::TwoViewGeometryVerifier::Run () override protected virtual
Implements colmap::Thread.
Definition at line 677 of file matching.cc.
References cache_, data, e, QtCompat::endl(), colmap::FeatureKeypointsToPointsVector(), colmap::FeatureMatcherCache::GetCamera(), colmap::FeatureMatcherCache::GetImage(), colmap::FeatureMatcherCache::GetKeypoints(), input_queue_, colmap::Thread::IsStopped(), colmap::SiftMatchingOptions::min_num_inliers, colmap::SiftMatchingOptions::multiple_models, options_, output_queue_, and two_view_geometry_options_.
Member Data Documentation
cache_
FeatureMatcherCache* colmap::TwoViewGeometryVerifier::cache_ protected
Definition at line 323 of file matching.h.
Referenced by Run().
input_queue_
JobQueue<Input>* colmap::TwoViewGeometryVerifier::input_queue_ protected
Definition at line 324 of file matching.h.
Referenced by Run().
options_
const SiftMatchingOptions colmap::TwoViewGeometryVerifier::options_ protected
Definition at line 321 of file matching.h.
Referenced by Run().
output_queue_
JobQueue<Output>* colmap::TwoViewGeometryVerifier::output_queue_ protected
Definition at line 325 of file matching.h.
Referenced by Run().
two_view_geometry_options_
TwoViewGeometry::Options colmap::TwoViewGeometryVerifier::two_view_geometry_options_ protected
Definition at line 322 of file matching.h.
Referenced by Run().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/feature/matching.h
/root/ACloudViewer/libs/Reconstruction/src/feature/matching.cc