ACloudViewer: FastMarchingForFacetExtraction Class Reference
FastMarchingForFacetExtraction Class Reference
Fast Marching algorithm for planar facets extraction (qFacets plugin)
#include <fastMarchingForFacetExtraction.h>
Classes
class PlanarCell
A Fast Marching grid cell for planar facets extraction.
Public Member Functions
FastMarchingForFacetExtraction ()
Default constructor.
virtual ~FastMarchingForFacetExtraction ()
Destructor.
int init (ccGenericPointCloud *cloud, cloudViewer::DgmOctree *theOctree, unsigned char gridLevel, ScalarType maxError, cloudViewer::DistanceComputationTools::ERROR_MEASURES errorMeasure, bool useRetroProjectionError, cloudViewer::GenericProgressCallback *progressCb=0)
Initializes the grid with a point cloud (and ist corresponding octree)
unsigned updateFlagsTable (ccGenericPointCloud *theCloud, std::vector< unsigned char > &flags, unsigned facetIndex)
Updates a list of point flags, indicating the points alreay processed.
void setPropagateCallback (cloudViewer::GenericProgressCallback *propagateProgressCb)
Sets the propagation progress callback.
virtual int propagate () override
Propagates the front.
virtual bool setSeedCell (const Tuple3i &pos) override
Sets a given cell as "seed".
Public Member Functions inherited from cloudViewer::FastMarching
FastMarching ()
Default constructor.
virtual ~FastMarching ()
Destructor.
virtual void cleanLastPropagation ()
virtual float getTime (Tuple3i &pos, bool absoluteCoordinates=false) const
Returns the front arrival time at a given cell.
virtual void setExtendedConnectivity (bool state)
Sets extended connectivity mode.
Static Public Member Functions
static int ExtractPlanarFacets (ccPointCloud *theCloud, unsigned char octreeLevel, ScalarType maxError, cloudViewer::DistanceComputationTools::ERROR_MEASURES errorMeasure, bool useRetroProjectionError=true, cloudViewer::GenericProgressCallback *progressCb=0, cloudViewer::DgmOctree *_theOctree=0)
Static entry point (helper)
Protected Member Functions
virtual float computeTCoefApprox (cloudViewer::FastMarching::Cell *currentCell, cloudViewer::FastMarching::Cell *neighbourCell) const override
Computes the front acceleration between two cells.
virtual int step () override
Propagates the front (one step)
virtual void initTrialCells () override
Initializes the TRIAL cells list.
virtual bool instantiateGrid (unsigned size) override
Instantiates grid in memory.
ScalarType addCellToCurrentFacet (unsigned index)
Protected Member Functions inherited from cloudViewer::FastMarching
unsigned pos2index (const Tuple3i &pos) const
virtual int initGridWithOctree (DgmOctree *octree, unsigned char gridLevel)
virtual int initGrid (float step, unsigned dim[3])
Intializes the grid with a given step and dimensions.
virtual int initOther ()
virtual float computeT (unsigned index)
Computes the front arrival time at a given cell.
template<class T >
bool instantiateGridTpl (unsigned size)
Grid instantiation helper.
virtual void addTrialCell (unsigned index)
Add a cell to the TRIAL cells list.
virtual void addActiveCell (unsigned index)
Add a cell to the ACTIVE cells list.
virtual void addIgnoredCell (unsigned index)
Add a cell to the IGNORED cells list.
virtual unsigned getNearestTrialCell ()
Returns the TRIAL cell with the smallest front arrival time.
void resetCells (std::vector< unsigned > &list)
Resets the state of cells in a given list.
Protected Attributes
cloudViewer::ReferenceCloud * m_currentFacetPoints
Current facet points.
ScalarType m_currentFacetError
Current facet error.
ScalarType m_maxError
Max facet error.
cloudViewer::DistanceComputationTools::ERROR_MEASURES m_errorMeasure
Error measrue.
bool m_useRetroProjectionError
Whether to use retro-projection error in propagation.
cloudViewer::GenericProgressCallback * m_propagateProgressCb
Propagation progress callback.
unsigned m_propagateProgress
Propagation progress.
Protected Attributes inherited from cloudViewer::FastMarching
std::vector< unsigned > m_activeCells
ACTIVE cells list.
std::vector< unsigned > m_trialCells
TRIAL cells list.
std::vector< unsigned > m_ignoredCells
IGNORED cells lits.
bool m_initialized
Specifiies whether structure is initialized or not.
unsigned m_dx
Grid size along the X dimension.
unsigned m_dy
Grid size along the Y dimension.
unsigned m_dz
Grid size along the Z dimension.
unsigned m_rowSize
Shift for cell access acceleration (Y dimension)
unsigned m_sliceSize
Shift for cell access acceleration (Z dimension)
unsigned m_indexShift
First index of innerbound grid.
unsigned m_gridSize
Grid size.
Cell ** m_theGrid
Grid used to process Fast Marching.
DgmOctree * m_octree
Associated octree.
unsigned char m_gridLevel
Equivalent octree subdivision level.
float m_cellSize
Octree cell size at equivalent subdivision level.
Tuple3i m_minFillIndexes
Octree min fill indexes at 'm_gridLevel'.
unsigned m_numberOfNeighbours
Current number of neighbours (6 or 26)
int m_neighboursIndexShift [26]
Neighbours coordinates shifts in grid.
float m_neighboursDistance [26]
Neighbours distance weight.
Detailed Description
Fast Marching algorithm for planar facets extraction (qFacets plugin)
Extends the FastMarching class.
Definition at line 24 of file fastMarchingForFacetExtraction.h.
Constructor & Destructor Documentation
FastMarchingForFacetExtraction()
FastMarchingForFacetExtraction::FastMarchingForFacetExtraction ()
Default constructor.
Definition at line 26 of file fastMarchingForFacetExtraction.cpp.
~FastMarchingForFacetExtraction()
FastMarchingForFacetExtraction::~FastMarchingForFacetExtraction () virtual
Destructor.
Definition at line 36 of file fastMarchingForFacetExtraction.cpp.
References m_currentFacetPoints.
Member Function Documentation
addCellToCurrentFacet()
ScalarType FastMarchingForFacetExtraction::addCellToCurrentFacet (unsigned index) protected
Adds a given cell's points to the current facet and returns the resulting RMS
Definition at line 356 of file fastMarchingForFacetExtraction.cpp.
References cloudViewer::ReferenceCloud::add(), cloudViewer::DgmOctree::associatedCloud(), FastMarchingForFacetExtraction::PlanarCell::cellCode, ComputeCellStats(), error(), cloudViewer::DgmOctree::getPointsInCell(), m_currentFacetPoints, m_errorMeasure, cloudViewer::FastMarching::m_gridLevel, cloudViewer::FastMarching::m_initialized, cloudViewer::FastMarching::m_octree, cloudViewer::FastMarching::m_theGrid, and cloudViewer::DgmOctree::MAX_OCTREE_LEVEL.
Referenced by setSeedCell(), and step().
computeTCoefApprox()
float FastMarchingForFacetExtraction::computeTCoefApprox (cloudViewer::FastMarching::Cell * currentCell, cloudViewer::FastMarching::Cell * neighbourCell) const override protected virtual
Computes the front acceleration between two cells.
Parameters
currentCell the "central" cell
neighbourCell the other cell
Returns
the front acceleration
oCell->planarError
Implements cloudViewer::FastMarching.
Definition at line 220 of file fastMarchingForFacetExtraction.cpp.
References cloudViewer::DgmOctree::associatedCloud(), FastMarchingForFacetExtraction::PlanarCell::C, FastMarchingForFacetExtraction::PlanarCell::cellCode, cloudViewer::DistanceComputationTools::ComputeCloud2PlaneDistance(), Vector3Tpl< Type >::dot(), fabs(), cloudViewer::DgmOctree::getPointsInCell(), m_errorMeasure, cloudViewer::FastMarching::m_gridLevel, cloudViewer::FastMarching::m_octree, m_useRetroProjectionError, FastMarchingForFacetExtraction::PlanarCell::N, Vector3Tpl< Type >::norm2(), Vector3Tpl< Type >::normalize(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by initTrialCells().
ExtractPlanarFacets()
int FastMarchingForFacetExtraction::ExtractPlanarFacets (ccPointCloud * theCloud, unsigned char octreeLevel, ScalarType maxError, cloudViewer::DistanceComputationTools::ERROR_MEASURES errorMeasure, bool useRetroProjectionError = true, cloudViewer::GenericProgressCallback * progressCb = 0, cloudViewer::DgmOctree * _theOctree = 0) static
Static entry point (helper)
Definition at line 413 of file fastMarchingForFacetExtraction.cpp.
References cloudViewer::DgmOctree::build(), cloudViewer::FastMarching::cleanLastPropagation(), count, cloudViewer::PointCloudTpl< T >::enableScalarField(), CVLog::Error(), cloudViewer::PointCloudTpl< T >::getCurrentOutScalarField(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::DgmOctree::getTheCellPosWhichIncludesThePoint(), init(), min(), octreeLevel, propagate(), result, cloudViewer::GenericProgressCallback::setInfo(), cloudViewer::GenericProgressCallback::setMethodTitle(), cloudViewer::PointCloudTpl< T >::setPointScalarValue(), setPropagateCallback(), setSeedCell(), cloudViewer::PointCloudTpl< T >::size(), cloudViewer::GenericProgressCallback::start(), cloudViewer::GenericProgressCallback::stop(), cloudViewer::GenericProgressCallback::textCanBeEdited(), cloudViewer::GenericProgressCallback::update(), updateFlagsTable(), CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by qFacets::extractFacets().
init()
int FastMarchingForFacetExtraction::init (ccGenericPointCloud * cloud, cloudViewer::DgmOctree * theOctree, unsigned char gridLevel, ScalarType maxError, cloudViewer::DistanceComputationTools::ERROR_MEASURES errorMeasure, bool useRetroProjectionError, cloudViewer::GenericProgressCallback * progressCb = 0)
Initializes the grid with a point cloud (and ist corresponding octree)
The points should be associated to an (active) scalar field. The Fast Marching grid will have the same dimensions as the input octree considered at a given level of subdivision.
Parameters
cloud the point cloud
theOctree the associated octree
gridLevel the level of subdivision
maxError maximum error allowed by 'propagated' facet
errorMeasure error measure
useRetroProjectionError whether to use retro-projection error in propagation
progressCb progeress callback
Returns
a negative value if something went wrong
Definition at line 70 of file fastMarchingForFacetExtraction.cpp.
References cloudViewer::DgmOctree::associatedCloud(), FastMarchingForFacetExtraction::PlanarCell::C, FastMarchingForFacetExtraction::PlanarCell::cellCode, ComputeCellStats(), error(), cloudViewer::DgmOctree::getCellCodes(), cloudViewer::DgmOctree::getCellPos(), cloudViewer::DgmOctree::getPointsInCell(), cloudViewer::FastMarching::initGridWithOctree(), m_errorMeasure, cloudViewer::FastMarching::m_initialized, m_maxError, cloudViewer::FastMarching::m_theGrid, m_useRetroProjectionError, FastMarchingForFacetExtraction::PlanarCell::N, nProgress, cloudViewer::NormalizedProgress::oneStep(), FastMarchingForFacetExtraction::PlanarCell::planarError, cloudViewer::FastMarching::pos2index(), result, cloudViewer::GenericProgressCallback::setInfo(), cloudViewer::GenericProgressCallback::setMethodTitle(), cloudViewer::GenericProgressCallback::start(), cloudViewer::GenericProgressCallback::stop(), cloudViewer::GenericProgressCallback::textCanBeEdited(), and cloudViewer::GenericProgressCallback::update().
Referenced by ExtractPlanarFacets().
initTrialCells()
void FastMarchingForFacetExtraction::initTrialCells () override protected virtual
Initializes the TRIAL cells list.
See the Fast Marching algorithm theory for more information
Reimplemented from cloudViewer::FastMarching.
Definition at line 382 of file fastMarchingForFacetExtraction.cpp.
References cloudViewer::FastMarching::addTrialCell(), computeTCoefApprox(), cloudViewer::FastMarching::Cell::FAR_CELL, cloudViewer::FastMarching::m_activeCells, m_currentFacetError, m_maxError, cloudViewer::FastMarching::m_neighboursDistance, cloudViewer::FastMarching::m_neighboursIndexShift, cloudViewer::FastMarching::m_numberOfNeighbours, cloudViewer::FastMarching::m_theGrid, cloudViewer::FastMarching::Cell::state, and cloudViewer::FastMarching::Cell::T.
Referenced by propagate().
instantiateGrid()
virtual bool FastMarchingForFacetExtraction::instantiateGrid (unsigned size) inline override protected virtual
Instantiates grid in memory.
Grid is also filled with zeros.
Parameters
size grid size
Returns
success
Implements cloudViewer::FastMarching.
Definition at line 108 of file fastMarchingForFacetExtraction.h.
References size.
propagate()
int FastMarchingForFacetExtraction::propagate () override virtual
Propagates the front.
The seeds should have already been initialized
Returns
propagation result (errors = negative values)
Implements cloudViewer::FastMarching.
Definition at line 267 of file fastMarchingForFacetExtraction.cpp.
References initTrialCells(), cloudViewer::GenericProgressCallback::isCancelRequested(), m_propagateProgressCb, result, and step().
Referenced by ExtractPlanarFacets().
setPropagateCallback()
void FastMarchingForFacetExtraction::setPropagateCallback (cloudViewer::GenericProgressCallback * propagateProgressCb) inline
Sets the propagation progress callback.
Definition at line 71 of file fastMarchingForFacetExtraction.h.
References m_propagateProgress, and m_propagateProgressCb.
Referenced by ExtractPlanarFacets().
setSeedCell()
bool FastMarchingForFacetExtraction::setSeedCell (const Tuple3i & pos) override virtual
Sets a given cell as "seed".
Parameters
pos the cell position in the grid (3 integer coordinates)
Returns
whether the cell could be set as a seed or not
Reimplemented from cloudViewer::FastMarching.
Definition at line 333 of file fastMarchingForFacetExtraction.cpp.
References addCellToCurrentFacet(), cloudViewer::DgmOctree::associatedCloud(), m_currentFacetError, m_currentFacetPoints, cloudViewer::FastMarching::m_octree, m_propagateProgress, cloudViewer::FastMarching::pos2index(), cloudViewer::FastMarching::setSeedCell(), and cloudViewer::ReferenceCloud::size().
Referenced by ExtractPlanarFacets().
step()
int FastMarchingForFacetExtraction::step () override protected virtual
Propagates the front (one step)
Returns
a negative value if a problem occurred
Implements cloudViewer::FastMarching.
Definition at line 150 of file fastMarchingForFacetExtraction.cpp.
References cloudViewer::FastMarching::Cell::ACTIVE_CELL, cloudViewer::FastMarching::addActiveCell(), addCellToCurrentFacet(), cloudViewer::FastMarching::addIgnoredCell(), cloudViewer::FastMarching::addTrialCell(), cloudViewer::FastMarching::computeT(), error(), cloudViewer::FastMarching::Cell::FAR_CELL, cloudViewer::ReferenceCloud::getAssociatedCloud(), cloudViewer::FastMarching::getNearestTrialCell(), m_currentFacetError, m_currentFacetPoints, cloudViewer::FastMarching::m_initialized, m_maxError, cloudViewer::FastMarching::m_neighboursIndexShift, cloudViewer::FastMarching::m_numberOfNeighbours, m_propagateProgress, m_propagateProgressCb, cloudViewer::FastMarching::m_theGrid, cloudViewer::ReferenceCloud::resize(), cloudViewer::GenericCloud::size(), cloudViewer::ReferenceCloud::size(), cloudViewer::FastMarching::Cell::state, cloudViewer::FastMarching::Cell::T, cloudViewer::FastMarching::Cell::T_INF(), cloudViewer::FastMarching::Cell::TRIAL_CELL, and cloudViewer::GenericProgressCallback::update().
Referenced by propagate().
updateFlagsTable()
unsigned FastMarchingForFacetExtraction::updateFlagsTable (ccGenericPointCloud * theCloud, std::vector< unsigned char > & flags, unsigned facetIndex)
Updates a list of point flags, indicating the points alreay processed.
Returns
the number of newly flagged points
Definition at line 284 of file fastMarchingForFacetExtraction.cpp.
References cloudViewer::DgmOctree::associatedCloud(), FastMarchingForFacetExtraction::PlanarCell::cellCode, cloudViewer::ReferenceCloud::clear(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), cloudViewer::DgmOctree::getPointsInCell(), cloudViewer::FastMarching::m_activeCells, m_currentFacetPoints, cloudViewer::FastMarching::m_gridLevel, cloudViewer::FastMarching::m_initialized, cloudViewer::FastMarching::m_octree, cloudViewer::FastMarching::m_theGrid, cloudViewer::GenericCloud::setPointScalarValue(), and cloudViewer::ReferenceCloud::size().
Referenced by ExtractPlanarFacets().
Member Data Documentation
m_currentFacetError
ScalarType FastMarchingForFacetExtraction::m_currentFacetError protected
Current facet error.
Definition at line 120 of file fastMarchingForFacetExtraction.h.
Referenced by initTrialCells(), setSeedCell(), and step().
m_currentFacetPoints
cloudViewer::ReferenceCloud* FastMarchingForFacetExtraction::m_currentFacetPoints protected
Current facet points.
Definition at line 117 of file fastMarchingForFacetExtraction.h.
Referenced by addCellToCurrentFacet(), setSeedCell(), step(), updateFlagsTable(), and ~FastMarchingForFacetExtraction().
m_errorMeasure
cloudViewer::DistanceComputationTools::ERROR_MEASURES FastMarchingForFacetExtraction::m_errorMeasure protected
Error measrue.
Definition at line 126 of file fastMarchingForFacetExtraction.h.
Referenced by addCellToCurrentFacet(), computeTCoefApprox(), and init().
m_maxError
ScalarType FastMarchingForFacetExtraction::m_maxError protected
Max facet error.
Definition at line 123 of file fastMarchingForFacetExtraction.h.
Referenced by init(), initTrialCells(), and step().
m_propagateProgress
unsigned FastMarchingForFacetExtraction::m_propagateProgress protected
Propagation progress.
Definition at line 134 of file fastMarchingForFacetExtraction.h.
Referenced by setPropagateCallback(), setSeedCell(), and step().
m_propagateProgressCb
cloudViewer::GenericProgressCallback* FastMarchingForFacetExtraction::m_propagateProgressCb protected
Propagation progress callback.
Definition at line 132 of file fastMarchingForFacetExtraction.h.
Referenced by propagate(), setPropagateCallback(), and step().
m_useRetroProjectionError
bool FastMarchingForFacetExtraction::m_useRetroProjectionError protected
Whether to use retro-projection error in propagation.
Definition at line 129 of file fastMarchingForFacetExtraction.h.
Referenced by computeTCoefApprox(), and init().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qFacets/include/fastMarchingForFacetExtraction.h
/root/ACloudViewer/plugins/core/Standard/qFacets/src/fastMarchingForFacetExtraction.cpp