ACloudViewer: cc2DLabel Class Reference
cc2DLabel Class Reference
2D label (typically attached to points)
#include <ecv2DLabel.h>
Classes
struct LabelInfo1
One-point label info.
struct LabelInfo2
Two-points label info.
struct LabelInfo3
Three-points label info.
struct PickedPoint
Picked point descriptor.
Public Member Functions
cc2DLabel (QString name=QString("label"))
Default constructor.
virtual QString getName () const override
Returns object name.
virtual CV_CLASS_ENUM getClassID () const override
Returns class ID.
virtual bool isSerializable () const override
Returns whether object is serializable of not.
QString getRawName () const
Returns 'raw' name (no replacement of default keywords)
QStringList getLabelContent (int precision) const
Gets label content (as it will be displayed)
QString getTitle (int precision) const
Returns the (3D) label title.
virtual bool acceptClick (int x, int y, Qt::MouseButton button) override
Called on mouse click.
virtual bool move2D (int x, int y, int dx, int dy, int screenWidth, int screenHeight) override
Called on mouse move (for 2D interactors)
void setPosition (float x, float y)
Sets relative position.
const float * getPosition () const
Returns relative position.
void clear (bool ignoreDependencies=false, bool ignoreCaption=true)
Clears label.
void clearLabel (bool ignoreCaption=true)
void updateLabel ()
void update3DLabelView (CC_DRAW_CONTEXT &context, bool updateScreen=true)
void update2DLabelView (CC_DRAW_CONTEXT &context, bool updateScreen=true)
unsigned size () const
Returns current size.
bool addPickedPoint (ccGenericPointCloud *cloud, unsigned pointIndex, bool entityCenter=false)
Adds a point to this label.
bool addPickedPoint (ccGenericMesh *mesh, unsigned triangleIndex, const CCVector2d &uv, bool entityCenter=false)
Adds a point to this label.
void setCollapsed (bool state)
Whether to collapse label or not.
bool isCollapsed () const
Returns whether the label is collapsed or not.
void displayPointLegend (bool state)
Whether to display the point(s) legend (title only)
bool isPointLegendDisplayed () const
Returns whether the point(s) legend is displayed.
void setDisplayedIn2D (bool state)
Whether to display the label in 2D.
bool isDisplayedIn2D () const
Returns whether the label is displayed in 2D.
bool addPickedPoint (const PickedPoint &pp)
Adds a point to this label (direct - handle with care)
const PickedPoint & getPickedPoint (unsigned index) const
Returns a given point.
PickedPoint & getPickedPoint (unsigned index)
Returns a given point.
void setRelativeMarkerScale (float scale)
Sets marker (relative) scale.
bool pointPicking (const CCVector2d &clickPos, const ccGLCameraParameters &camera, int &nearestPointIndex, double &nearestSquareDist) const
Point (marker) picking.
Public Member Functions inherited from ccHObject
ccHObject (QString name=QString())
Default constructor.
ccHObject (const ccHObject &object)
Copy constructor.
virtual ~ccHObject () override
Default destructor.
virtual bool IsEmpty () const
virtual Eigen::Vector3d GetMinBound () const
Returns min bounds for geometry coordinates.
virtual Eigen::Vector2d GetMin2DBound () const
virtual Eigen::Vector3d GetMaxBound () const
Returns max bounds for geometry coordinates.
virtual Eigen::Vector2d GetMax2DBound () const
virtual Eigen::Vector3d GetCenter () const
Returns the center of the geometry coordinates.
virtual ccBBox GetAxisAlignedBoundingBox () const
Returns an axis-aligned bounding box of the geometry.
virtual ecvOrientedBBox GetOrientedBoundingBox () const
virtual ccHObject & Transform (const Eigen::Matrix4d &transformation)
Apply transformation (4x4 matrix) to the geometry coordinates.
virtual ccHObject & Translate (const Eigen::Vector3d &translation, bool relative=true)
Apply translation to the geometry coordinates.
virtual ccHObject & Scale (const double s, const Eigen::Vector3d &center)
Apply scaling to the geometry coordinates. Given a scaling factor , and center , a given point is transformed according to .
virtual ccHObject & Scale (const double s)
virtual ccHObject & Rotate (const Eigen::Matrix3d &R, const Eigen::Vector3d &center)
Apply rotation to the geometry coordinates and normals. Given a rotation matrix , and center , a given point is transformed according to .
virtual ccHObject & Rotate (const Eigen::Matrix3d &R)
QString getViewId () const
CV_CLASS_ENUM getClassID () const override
Returns class ID.
bool isGroup () const
Returns whether the instance is a group.
ccHObject * getParent () const
Returns parent object.
virtual QIcon getIcon () const
Returns the icon associated to this entity.
void addDependency (ccHObject *otherObject, int flags, bool additive=true)
Adds a new dependence (additive or not)
int getDependencyFlagsWith (const ccHObject *otherObject)
Returns the dependency flags with a given object.
void removeDependencyWith (ccHObject *otherObject)
Removes any dependency flags with a given object.
void removeDependencyFlag (ccHObject *otherObject, DEPENDENCY_FLAGS flag)
Removes a given dependency flag.
virtual bool addChild (ccHObject *child, int dependencyFlags=DP_PARENT_OF_OTHER, int insertIndex=-1)
Adds a child.
unsigned getChildrenNumber () const
Returns the number of children.
unsigned int getChildCountRecursive () const
Returns the total number of children under this object recursively.
ccHObject * getChild (unsigned childPos) const
Returns the ith child.
ccHObject * find (unsigned uniqueID)
Finds an entity in this object hierarchy.
unsigned filterChildren (Container &filteredChildren, bool recursive=false, CV_CLASS_ENUM filter=CV_TYPES::OBJECT, bool strict=false) const
Collects the children corresponding to a certain pattern.
void detachChild (ccHObject *child)
Detaches a specific child.
void detachAllChildren ()
Removes a specific child.
void getTypeID_recursive (std::vector< removeInfo > &rmInfos, bool relative)
void getTypeID_recursive (std::vector< hideInfo > &hdInfos, bool relative)
void removeChild (ccHObject *child)
void removeChild (int pos)
Removes a specific child given its index.
void removeAllChildren ()
Removes all children.
int getChildIndex (const ccHObject *aChild) const
Returns child index.
void swapChildren (unsigned firstChildIndex, unsigned secondChildIndex)
Swaps two children.
int getIndex () const
Returns index relatively to its parent or -1 if no parent.
void transferChild (ccHObject *child, ccHObject &newParent)
Transfer a given child to another parent.
void transferChildren (ccHObject &newParent, bool forceFatherDependent=false)
Transfer all children to another parent.
ccHObject * getFirstChild () const
Shortcut: returns first child.
ccHObject * getLastChild () const
Shortcut: returns last child.
bool isAncestorOf (const ccHObject *anObject) const
Returns true if the current object is an ancestor of the specified one.
void removeFromRenderScreen (bool recursive=true)
void hideObject_recursive (bool recursive)
void hideBB (CC_DRAW_CONTEXT context)
void showBB (CC_DRAW_CONTEXT context)
virtual ccBBox getOwnBB (bool withGLFeatures=false)
Returns the entity's own bounding-box.
void setRedrawFlagRecursive (bool redraw=false)
void setForceRedrawRecursive (bool redraw=false)
void setPointSizeRecursive (int pSize)
void setLineWidthRecursive (PointCoordinateType width)
virtual ccBBox getBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the bounding-box of this entity and it's children.
virtual GlobalBoundingBox getOwnGlobalBB (bool withGLFeatures=false)
virtual bool getOwnGlobalBB (CCVector3d &minCorner, CCVector3d &maxCorner)
virtual GlobalBoundingBox getGlobalBB_recursive (bool withGLFeatures=false, bool onlyEnabledChildren=true)
Returns the global bounding-box of this entity and it's children.
virtual ccBBox getDisplayBB_recursive (bool relative)
Returns the bounding-box of this entity and it's children WHEN DISPLAYED.
virtual ccBBox getOwnFitBB (ccGLMatrix &trans)
Returns best-fit bounding-box (if available)
virtual void drawBB (CC_DRAW_CONTEXT &context, const ecvColor::Rgb &col)
Draws the entity (and its children) bounding-box.
void draw (CC_DRAW_CONTEXT &context) override
Draws entity and its children.
void updateNameIn3DRecursive ()
void setHideShowType (CC_DRAW_CONTEXT &context)
void setRemoveType (CC_DRAW_CONTEXT &context)
ENTITY_TYPE getEntityType () const
virtual void redrawDisplay (bool forceRedraw=true, bool only2D=false)
Redraws associated display.
bool getAbsoluteGLTransformation (ccGLMatrix &trans) const
virtual bool isDisplayed () const
Returns whether the object is actually displayed (visible) or not.
virtual bool isBranchEnabled () const
Returns whether the object and all its ancestors are enabled.
virtual void redrawDisplay_recursive (bool p)
virtual void refreshDisplay_recursive (bool p)
virtual void setSelected_recursive (bool p)
virtual void toggleActivation_recursive ()
virtual void toggleVisibility_recursive ()
virtual void toggleColors_recursive ()
virtual void resetGLTransformationHistory_recursive ()
virtual void toggleNormals_recursive ()
virtual void toggleSF_recursive ()
virtual void toggleShowName_recursive ()
unsigned findMaxUniqueID_recursive () const
Returns the max 'unique ID' of this entity and its siblings.
void applyGLTransformation_recursive (const ccGLMatrix *trans=nullptr)
Applies the active OpenGL transformation to the entity (recursive)
virtual void notifyGeometryUpdate ()
bool isSerializable () const override
Returns whether object is serializable of not.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads data from binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFileNoChildren (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap)
Custom version of ccSerializableObject::fromFile.
virtual bool isShareable () const
Returns whether object is shareable or not.
virtual void setSelectionBehavior (SelectionBehavior mode)
Sets selection behavior (when displayed)
virtual SelectionBehavior getSelectionBehavior () const
Returns selection behavior.
virtual unsigned getUniqueIDForDisplay () const
Returns object unqiue ID used for display.
virtual const ccGLMatrix & getGLTransformationHistory () const
Returns the transformation 'history' matrix.
virtual void setGLTransformationHistory (const ccGLMatrix &mat)
Sets the transformation 'history' matrix (handle with care!)
virtual void resetGLTransformationHistory ()
Resets the transformation 'history' matrix.
bool pushDisplayState () override
Pushes the current display state (overridden)
void popDisplayState (bool apply=true) override
Pops the last pushed display state (overridden)
Public Member Functions inherited from ccObject
ccObject (QString name=QString())
Default constructor.
ccObject (const ccObject &object)
Copy constructor.
virtual void setName (const QString &name)
Sets object name.
virtual void setRemoveFlag (bool removeFlag)
Sets removeFlag.
virtual bool getRemoveFlag ()
Returns removeFlag.
virtual unsigned getUniqueID () const
Returns object unique ID.
virtual void setUniqueID (unsigned ID)
Changes unique ID.
virtual bool isEnabled () const
Returns whether the object is enabled or not.
virtual void setEnabled (bool state)
Sets the "enabled" property.
virtual void toggleActivation ()
Toggles the "enabled" property.
virtual bool isLocked () const
Returns whether the object is locked or not.
virtual void setLocked (bool state)
Sets the "enabled" property.
bool isLeaf () const
bool isCustom () const
bool isHierarchy () const
bool isKindOf (CV_CLASS_ENUM type) const
bool isA (CV_CLASS_ENUM type) const
QVariant getMetaData (const QString &key) const
Returns a given associated meta data.
bool removeMetaData (const QString &key)
Removes a given associated meta-data.
void setMetaData (const QString &key, const QVariant &data)
Sets a meta-data element.
void setMetaData (const QVariantMap &dataset, bool overwrite=false)
Sets several meta-data elements at a time.
bool hasMetaData (const QString &key) const
Returns whether a meta-data element with the given key exists or not.
const QVariantMap & metaData () const
Returns meta-data map (const only)
void setBaseName (const QString &baseName)
QString getBaseName () const
void setFullPath (const QString &fullPaht)
QString getFullPath () const
Public Member Functions inherited from ccSerializableObject
virtual ~ccSerializableObject ()=default
Destructor.
Public Member Functions inherited from ccDrawableObject
ccDrawableObject ()
Default constructor.
ccDrawableObject (const ccDrawableObject &object)
Copy constructor.
virtual ~ccDrawableObject ()=default
virtual bool isVisible () const
Returns whether entity is visible or not.
virtual void setVisible (bool state)
Sets entity visibility.
virtual void toggleVisibility ()
Toggles visibility.
virtual bool isRedraw () const
Returns whether entity is to be redraw.
virtual void setRedraw (bool state)
Sets entity redraw mode.
virtual void setForceRedraw (bool state)
Sets force redraw.
virtual void setFixedId (bool state)
virtual bool isFixedId ()
virtual bool isVisibilityLocked () const
Returns whether visibility is locked or not.
virtual void lockVisibility (bool state)
Locks/unlocks visibility.
virtual bool isSelected () const
Returns whether entity is selected or not.
virtual void setSelected (bool state)
Selects/Unselects entity.
virtual void getDrawingParameters (glDrawParams &params) const
Returns main OpenGL parameters for this entity.
virtual bool hasColors () const
Returns whether colors are enabled or not.
virtual bool colorsShown () const
Returns whether colors are shown or not.
virtual void showColors (bool state)
Sets colors visibility.
virtual void toggleColors ()
Toggles colors display state.
virtual bool hasNormals () const
Returns whether normals are enabled or not.
virtual bool normalsShown () const
Returns whether normals are shown or not.
virtual void showNormals (bool state)
Sets normals visibility.
virtual void toggleNormals ()
Toggles normals display state.
virtual bool hasDisplayedScalarField () const
Returns whether an active scalar field is available or not.
virtual bool hasScalarFields () const
Returns whether one or more scalar fields are instantiated.
virtual void showSF (bool state)
Sets active scalarfield visibility.
virtual void toggleSF ()
Toggles SF display state.
virtual bool sfShown () const
Returns whether active scalar field is visible.
virtual void toggleMaterials ()
Toggles material display state.
virtual void showNameIn3D (bool state)
Sets whether name should be displayed in 3D.
virtual bool nameShownIn3D () const
Returns whether name is displayed in 3D or not.
virtual void toggleShowName ()
Toggles name in 3D display state.
virtual bool isColorOverridden () const
virtual const ecvColor::Rgb & getTempColor () const
Returns current temporary (unique) color.
virtual void setTempColor (const ecvColor::Rgb &col, bool autoActivate=true)
Sets current temporary (unique)
virtual void enableTempColor (bool state)
Set temporary color activation state.
virtual float getOpacity () const
virtual void setOpacity (float opacity)
Set opacity activation state.
virtual void setGLTransformation (const ccGLMatrix &trans)
Associates entity with a GL transformation (rotation + translation)
virtual void enableGLTransformation (bool state)
Enables/disables associated GL transformation.
virtual bool isGLTransEnabled () const
Returns whether a GL transformation is enabled or not.
virtual const ccGLMatrix & getGLTransformation () const
Returns associated GL transformation.
virtual void resetGLTransformation ()
Resets associated GL transformation.
virtual void rotateGL (const ccGLMatrix &rotMat)
Multiplies (left) current GL transformation by a rotation matrix.
virtual void translateGL (const CCVector3 &trans)
Translates current GL transformation by a rotation matrix.
virtual void removeAllClipPlanes ()
Removes all clipping planes (if any)
virtual bool addClipPlanes (const ccClipPlane &plane)
Registers a new clipping plane.
virtual void toggleClipPlanes (CC_DRAW_CONTEXT &context, bool enable)
Enables or disables clipping planes (OpenGL)
virtual void applyDisplayState (const DisplayState &state)
Applies a display state.
Public Member Functions inherited from ccInteractor
virtual ~ccInteractor ()=default
virtual bool move3D (const CCVector3d &u)
Called on mouse move (for 3D interactors)
Protected Member Functions
void getLabelInfo1 (LabelInfo1 &info) const
Returns one-point label info.
void getLabelInfo2 (LabelInfo2 &info) const
Gets two-points label info.
void getLabelInfo3 (LabelInfo3 &info) const
Gets three-points label info.
bool toFile_MeOnly (QFile &out, short dataVersion) const override
Save own object data.
short minimumFileVersion_MeOnly () const override
bool fromFile_MeOnly (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Loads own object data.
virtual void drawMeOnly (CC_DRAW_CONTEXT &context) override
Draws the entity only (not its children)
virtual void onDeletionOf (const ccHObject *obj) override
This method is called when another object is deleted.
void drawMeOnly2D (CC_DRAW_CONTEXT &context)
Draws the entity only (not its children) - 2D version.
void clear2Dviews ()
void drawMeOnly3D (CC_DRAW_CONTEXT &context)
Draws the entity only (not its children) - 3D version.
void clear3Dviews ()
void updateName ()
Updates the label 'name'.
Protected Member Functions inherited from ccHObject
virtual void setParent (ccHObject *anObject)
Sets parent object.
virtual void applyGLTransformation (const ccGLMatrix &trans)
Applies a GL transformation to the entity.
virtual void drawNameIn3D ()
Draws the entity name in 3D.
virtual void onUpdateOf (ccHObject *obj)
This method is called when another object (geometry) is updated.
Protected Member Functions inherited from ccObject
virtual bool getFlagState (CV_OBJECT_FLAG flag) const
Returns flag state.
virtual void setFlagState (CV_OBJECT_FLAG flag, bool state)
Sets flag state.
bool toFile (QFile &out, short dataVersion) const override
Saves data to binary stream.
short minimumFileVersion () const override
Returns the minimum file version required to save this instance.
bool fromFile (QFile &in, short dataVersion, int flags, LoadedIDMap &oldToNewIDMap) override
Reimplemented from ccSerializableObject::fromFile.
Static Protected Member Functions
static QString GetSFValueAsString (const LabelInfo1 &info, int precision)
Returns the SF value as a string.
Protected Attributes
std::vector< PickedPoint > m_pickedPoints
Picked points.
bool m_showFullBody
Whether to show full label body or not.
QRect m_labelROI
label ROI
QStringList m_historyMessage
float m_screenPos [2]
close button ROI
int m_lastScreenPos [2]
Label position at last display (absolute)
bool m_dispPointsLegend
Whether to display the point(s) legend.
bool m_dispIn2D
Whether to display the label in 2D.
float m_relMarkerScale
Relative marker scale.
QString m_sphereIdfix
QString m_surfaceIdfix
QString m_contourIdfix
QString m_lineID
Protected Attributes inherited from ccHObject
ccHObject * m_parent
Parent.
Container m_children
Children.
SelectionBehavior m_selectionBehavior
Selection behavior.
std::map< ccHObject *, int > m_dependencies
Dependencies map.
ccGLMatrix m_glTransHistory
Cumulative GL transformation.
bool m_isDeleting
Flag to safely handle dependencies when the object is being deleted.
Protected Attributes inherited from ccObject
QString m_name
Object name.
QString m_baseName
QString m_filePath
bool m_removeFlag
unsigned m_flags
Object flags.
QVariantMap m_metaData
Associated meta-data.
Protected Attributes inherited from ccDrawableObject
bool m_fixedId
bool m_modelRedraw
bool m_forceRedraw
float m_opacity
bool m_visible
Specifies whether the object is visible or not.
bool m_selected
Specifies whether the object is selected or not.
bool m_lockedVisibility
Specifies whether the visibility can be changed by user or not.
bool m_colorsDisplayed
Specifies whether colors should be displayed.
bool m_normalsDisplayed
Specifies whether normals should be displayed.
bool m_sfDisplayed
Specifies whether scalar field should be displayed.
ecvColor::Rgb m_tempColor
Temporary (unique) color.
bool m_colorIsOverridden
Temporary (unique) color activation state.
ccGLMatrix m_glTrans
Current GL transformation.
bool m_glTransEnabled
Current GL transformation activation state.
bool m_showNameIn3D
Whether name is displayed in 3D or not.
CCVector3d m_nameIn3DPos
Last 2D position of the '3D' name.
ccClipPlaneSet m_clipPlanes
Active clipping planes (used for display only)
std::vector< DisplayState::Shared > m_displayStateStack
The stack of pushed display states.
Additional Inherited Members
Public Types inherited from ccHObject
enum DEPENDENCY_FLAGS {
DP_NONE = 0 , DP_NOTIFY_OTHER_ON_DELETE = 1 , DP_NOTIFY_OTHER_ON_UPDATE , DP_DELETE_OTHER = 8 ,
DP_PARENT_OF_OTHER = 24
}
Dependency flags.
enum SelectionBehavior { SELECTION_AA_BBOX , SELECTION_FIT_BBOX , SELECTION_IGNORED }
Behavior when selected.
using Container = std::vector< ccHObject * >
Standard instances container (for children, etc.)
using Shared = QSharedPointer< ccHObject >
Shared pointer.
using SharedContainer = std::vector< Shared >
Shared instances container (for children, etc.)
using GlobalBoundingBox = cloudViewer::BoundingBoxTpl< double >
Global (non-shifted) bounding-box.
Public Types inherited from ccSerializableObject
enum DeserializationFlags { DF_POINT_COORDS_64_BITS , DF_SCALAR_VAL_32_BITS = 2 }
Deserialization flags (bit-field)
typedef QMultiMap< unsigned, unsigned > LoadedIDMap
Map of loaded unique IDs (old ID --> new ID)
Static Public Member Functions inherited from ccHObject
static ccHObject * New (CV_CLASS_ENUM objectType, const char *name=nullptr)
Static factory.
static ccHObject * New (const QString &pluginId, const QString &classId, const char *name=nullptr)
Static factory (version to be used by external plugin factories)
static Eigen::Vector3d ComputeMinBound (const std::vector< Eigen::Vector3d > &points)
Compute min bound of a list points.
static Eigen::Vector3d ComputeMaxBound (const std::vector< Eigen::Vector3d > &points)
Compute max bound of a list points.
static Eigen::Vector3d ComputeCenter (const std::vector< Eigen::Vector3d > &points)
Computer center of a list of points.
static void ResizeAndPaintUniformColor (std::vector< Eigen::Vector3d > &colors, std::size_t size, const Eigen::Vector3d &color)
Resizes the colors vector and paints a uniform color.
static void TransformPoints (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &points)
Transforms all points with the transformation matrix.
static void TransformNormals (const Eigen::Matrix4d &transformation, std::vector< Eigen::Vector3d > &normals)
Transforms the normals with the transformation matrix.
static void TransformCovariances (const Eigen::Matrix4d &transformation, std::vector< Eigen::Matrix3d > &covariances)
Transforms all covariance matrices with the transformation.
static void TranslatePoints (const Eigen::Vector3d &translation, std::vector< Eigen::Vector3d > &points, bool relative)
Apply translation to the geometry coordinates.
static void ScalePoints (const double scale, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Scale the coordinates of all points by the scaling factor scale.
static void RotatePoints (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &points, const Eigen::Vector3d &center)
Rotate all points with the rotation matrix R.
static void RotateNormals (const Eigen::Matrix3d &R, std::vector< Eigen::Vector3d > &normals)
Rotate all normals with the rotation matrix R.
static void RotateCovariances (const Eigen::Matrix3d &R, std::vector< Eigen::Matrix3d > &covariances)
Rotate all covariance matrices with the rotation matrix R.
static Eigen::Matrix3d GetRotationMatrixFromXYZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XYZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYZX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YZX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZXY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZXY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromXZY (const Eigen::Vector3d &rotation)
Get Rotation Matrix from XZY RotationType.
static Eigen::Matrix3d GetRotationMatrixFromZYX (const Eigen::Vector3d &rotation)
Get Rotation Matrix from ZYX RotationType.
static Eigen::Matrix3d GetRotationMatrixFromYXZ (const Eigen::Vector3d &rotation)
Get Rotation Matrix from YXZ RotationType.
static Eigen::Matrix3d GetRotationMatrixFromAxisAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from AxisAngle RotationType.
static Eigen::Matrix3d GetRotationMatrixFromQuaternion (const Eigen::Vector4d &rotation)
Get Rotation Matrix from Quaternion.
static Eigen::Matrix3d GetRotationMatrixFromEulerAngle (const Eigen::Vector3d &rotation)
Get Rotation Matrix from Euler angle.
Static Public Member Functions inherited from ccObject
static unsigned GetCurrentDBVersion ()
Returns current database version.
static void SetUniqueIDGenerator (ccUniqueIDGenerator::Shared generator)
Sets the unique ID generator.
static ccUniqueIDGenerator::Shared GetUniqueIDGenerator ()
Returns the unique ID generator.
static unsigned GetNextUniqueID ()
Returns a new unassigned unique ID.
static unsigned GetLastUniqueID ()
Returns last assigned unique ID.
static CV_CLASS_ENUM ReadClassIDFromFile (QFile &in, short dataVersion)
Helper: reads out class ID from a binary stream.
Static Public Member Functions inherited from ccSerializableObject
static bool WriteError ()
Sends a custom error message (write error) and returns 'false'.
static bool ReadError ()
Sends a custom error message (read error) and returns 'false'.
static bool MemoryError ()
Sends a custom error message (not enough memory) and returns 'false'.
static bool CorruptError ()
Sends a custom error message (corrupted file) and returns 'false'.
Detailed Description
2D label (typically attached to points)
Definition at line 22 of file ecv2DLabel.h.
Constructor & Destructor Documentation
cc2DLabel()
cc2DLabel::cc2DLabel (QString name = QString("label"))
Default constructor.
Member Function Documentation
acceptClick()
virtual bool cc2DLabel::acceptClick (int x, int y, Qt::MouseButton button) override virtual
Called on mouse click.
Reimplemented from ccInteractor.
addPickedPoint() [1/3]
bool cc2DLabel::addPickedPoint (ccGenericMesh * mesh, unsigned triangleIndex, const CCVector2d & uv, bool entityCenter = false)
Adds a point to this label.
Adding a point to a label will automatically make it 'mutate'. 1 point = 'point' label (point position, normal, color, etc.) 2 points = 'vector' label (vertices position, distance) 3 points = "triangle/plane' label (vertices position, area, normal)
Returns
false if 'full'
addPickedPoint() [2/3]
bool cc2DLabel::addPickedPoint (ccGenericPointCloud * cloud, unsigned pointIndex, bool entityCenter = false)
Adds a point to this label.
Adding a point to a label will automatically make it 'mutate'. 1 point = 'point' label (point position, normal, color, etc.) 2 points = 'vector' label (vertices position, distance) 3 points = "triangle/plane' label (vertices position, area, normal)
Returns
false if 'full'
Referenced by CC_ITEM_TREE::createPointLabel2D(), and define_cc2DLabel().
addPickedPoint() [3/3]
bool cc2DLabel::addPickedPoint (const PickedPoint & pp)
Adds a point to this label (direct - handle with care)
clear()
void cc2DLabel::clear (bool ignoreDependencies = false, bool ignoreCaption = true)
Clears label.
Referenced by define_cc2DLabel().
clear2Dviews()
void cc2DLabel::clear2Dviews () protected
clear3Dviews()
void cc2DLabel::clear3Dviews () protected
clearLabel()
void cc2DLabel::clearLabel (bool ignoreCaption = true)
displayPointLegend()
void cc2DLabel::displayPointLegend (bool state) inline
Whether to display the point(s) legend (title only)
Definition at line 108 of file ecv2DLabel.h.
Referenced by CC_ITEM_TREE::createPointLabel2D(), and define_cc2DLabel().
drawMeOnly()
virtual void cc2DLabel::drawMeOnly (CC_DRAW_CONTEXT & context) override protected virtual
Draws the entity only (not its children)
Reimplemented from ccHObject.
drawMeOnly2D()
void cc2DLabel::drawMeOnly2D (CC_DRAW_CONTEXT & context) protected
Draws the entity only (not its children) - 2D version.
drawMeOnly3D()
void cc2DLabel::drawMeOnly3D (CC_DRAW_CONTEXT & context) protected
Draws the entity only (not its children) - 3D version.
fromFile_MeOnly()
bool cc2DLabel::fromFile_MeOnly (QFile & in, short dataVersion, int flags, LoadedIDMap & oldToNewIDMap) override protected virtual
Loads own object data.
Called by 'fromFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
in input file
dataVersion file version
flags deserialization flags (see ccSerializableObject::DeserializationFlags)
oldToNewIDMap map to link old IDs with new IDs
Reimplemented from ccHObject.
getClassID()
virtual CV_CLASS_ENUM cc2DLabel::getClassID () const inline override virtual
Returns class ID.
Implements ccObject.
Definition at line 30 of file ecv2DLabel.h.
References CV_TYPES::LABEL_2D.
getLabelContent()
QStringList cc2DLabel::getLabelContent (int precision) const
Gets label content (as it will be displayed)
Parameters
precision displayed numbers precision
Returns
label body (one string per line)
Referenced by define_cc2DLabel().
getLabelInfo1()
void cc2DLabel::getLabelInfo1 (LabelInfo1 & info) const protected
Returns one-point label info.
getLabelInfo2()
void cc2DLabel::getLabelInfo2 (LabelInfo2 & info) const protected
Gets two-points label info.
getLabelInfo3()
void cc2DLabel::getLabelInfo3 (LabelInfo3 & info) const protected
Gets three-points label info.
getName()
virtual QString cc2DLabel::getName () const override virtual
Returns object name.
Reimplemented from ccObject.
Referenced by ccMPlanePoint::getName().
getPickedPoint() [1/2]
PickedPoint& cc2DLabel::getPickedPoint (unsigned index) inline
Returns a given point.
Definition at line 198 of file ecv2DLabel.h.
getPickedPoint() [2/2]
const PickedPoint& cc2DLabel::getPickedPoint (unsigned index) const inline
Returns a given point.
Definition at line 194 of file ecv2DLabel.h.
Referenced by define_cc2DLabel(), ccMPlanePoint::getCoordinates(), ccMPlanePoint::getIndex(), and MinimumCutSegmentationDlg::updateForeGroundPoint().
getPosition()
const float* cc2DLabel::getPosition () const inline
Returns relative position.
Definition at line 63 of file ecv2DLabel.h.
getRawName()
QString cc2DLabel::getRawName () const inline
Returns 'raw' name (no replacement of default keywords)
Definition at line 36 of file ecv2DLabel.h.
References ccObject::m_name.
Referenced by define_cc2DLabel().
GetSFValueAsString()
static QString cc2DLabel::GetSFValueAsString (const LabelInfo1 & info, int precision) static protected
Returns the SF value as a string.
Handles:
NaN values
shifted SF
getTitle()
QString cc2DLabel::getTitle (int precision) const
Returns the (3D) label title.
Parameters
precision displayed numbers precision
Returns
label title
Referenced by define_cc2DLabel().
isCollapsed()
bool cc2DLabel::isCollapsed () const inline
Returns whether the label is collapsed or not.
Definition at line 105 of file ecv2DLabel.h.
Referenced by define_cc2DLabel().
isDisplayedIn2D()
bool cc2DLabel::isDisplayedIn2D () const inline
Returns whether the label is displayed in 2D.
Definition at line 117 of file ecv2DLabel.h.
Referenced by define_cc2DLabel().
isPointLegendDisplayed()
bool cc2DLabel::isPointLegendDisplayed () const inline
Returns whether the point(s) legend is displayed.
Definition at line 111 of file ecv2DLabel.h.
Referenced by define_cc2DLabel().
isSerializable()
virtual bool cc2DLabel::isSerializable () const inline override virtual
Returns whether object is serializable of not.
Reimplemented from ccSerializableObject.
Definition at line 33 of file ecv2DLabel.h.
minimumFileVersion_MeOnly()
short cc2DLabel::minimumFileVersion_MeOnly () const override protected virtual
Returns the minimum file version required to save this instance's own data To be overloaded (but still called ;) by subclass. Used internally by minimumFileVersion() to compute the overall minimum.
Reimplemented from ccHObject.
move2D()
virtual bool cc2DLabel::move2D (int x, int y, int dx, int dy, int screenWidth, int screenHeight) override virtual
Called on mouse move (for 2D interactors)
Returns
true if a movement occurs
Reimplemented from ccInteractor.
onDeletionOf()
virtual void cc2DLabel::onDeletionOf (const ccHObject * obj) override protected virtual
This method is called when another object is deleted.
For internal use.
Reimplemented from ccHObject.
pointPicking()
bool cc2DLabel::pointPicking (const CCVector2d & clickPos, const ccGLCameraParameters & camera, int & nearestPointIndex, double & nearestSquareDist) const
Point (marker) picking.
setCollapsed()
void cc2DLabel::setCollapsed (bool state) inline
Whether to collapse label or not.
Definition at line 102 of file ecv2DLabel.h.
Referenced by CC_ITEM_TREE::createPointLabel2D(), and define_cc2DLabel().
setDisplayedIn2D()
void cc2DLabel::setDisplayedIn2D (bool state) inline
Whether to display the label in 2D.
Definition at line 114 of file ecv2DLabel.h.
Referenced by CC_ITEM_TREE::createPointLabel2D(), and define_cc2DLabel().
setPosition()
void cc2DLabel::setPosition (float x, float y)
Sets relative position.
Referenced by CC_ITEM_TREE::createPointLabel2D(), and define_cc2DLabel().
setRelativeMarkerScale()
void cc2DLabel::setRelativeMarkerScale (float scale) inline
Sets marker (relative) scale.
Default value: 1.0
Definition at line 205 of file ecv2DLabel.h.
Referenced by define_cc2DLabel().
size()
unsigned cc2DLabel::size () const inline
Returns current size.
Definition at line 74 of file ecv2DLabel.h.
Referenced by define_cc2DLabel().
toFile_MeOnly()
bool cc2DLabel::toFile_MeOnly (QFile & out, short dataVersion) const override protected virtual
Save own object data.
Called by 'toFile' (recursive scheme) To be overloaded (but still called ;) by subclass.
Parameters
out output file
dataVersion target file version for compatibility control
Reimplemented from ccHObject.
update2DLabelView()
void cc2DLabel::update2DLabelView (CC_DRAW_CONTEXT & context, bool updateScreen = true)
update3DLabelView()
void cc2DLabel::update3DLabelView (CC_DRAW_CONTEXT & context, bool updateScreen = true)
updateLabel()
void cc2DLabel::updateLabel ()
updateName()
void cc2DLabel::updateName () protected
Updates the label 'name'.
Member Data Documentation
m_contourIdfix
QString cc2DLabel::m_contourIdfix protected
Definition at line 357 of file ecv2DLabel.h.
m_dispIn2D
bool cc2DLabel::m_dispIn2D protected
Whether to display the label in 2D.
Definition at line 350 of file ecv2DLabel.h.
m_dispPointsLegend
bool cc2DLabel::m_dispPointsLegend protected
Whether to display the point(s) legend.
Definition at line 347 of file ecv2DLabel.h.
m_historyMessage
QStringList cc2DLabel::m_historyMessage protected
Definition at line 335 of file ecv2DLabel.h.
m_labelROI
QRect cc2DLabel::m_labelROI protected
label ROI
ROI is displayed relatively to m_screenPos (projected in displayed screen space). m_screenPos corresponds to its top-left corner. So ROI[1] is the distance to the upper border and ROI[3] is the distance to the lower border (relatively to m_screenPos).
Definition at line 333 of file ecv2DLabel.h.
m_lastScreenPos
int cc2DLabel::m_lastScreenPos[2] protected
Label position at last display (absolute)
Definition at line 344 of file ecv2DLabel.h.
m_lineID
QString cc2DLabel::m_lineID protected
Definition at line 358 of file ecv2DLabel.h.
m_pickedPoints
std::vector<PickedPoint> cc2DLabel::m_pickedPoints protected
Picked points.
Definition at line 318 of file ecv2DLabel.h.
m_relMarkerScale
float cc2DLabel::m_relMarkerScale protected
Relative marker scale.
Definition at line 353 of file ecv2DLabel.h.
m_screenPos
float cc2DLabel::m_screenPos[2] protected
close button ROI
Label position (percentage of screen size)
Definition at line 341 of file ecv2DLabel.h.
m_showFullBody
bool cc2DLabel::m_showFullBody protected
Whether to show full label body or not.
Definition at line 324 of file ecv2DLabel.h.
m_sphereIdfix
QString cc2DLabel::m_sphereIdfix protected
Definition at line 355 of file ecv2DLabel.h.
m_surfaceIdfix
QString cc2DLabel::m_surfaceIdfix protected
Definition at line 356 of file ecv2DLabel.h.
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecv2DLabel.h