ACloudViewer: GeneralFilters Class Reference
GeneralFilters Class Reference
Projection Filter.
#include <GeneralFilters.h>
Public Member Functions
GeneralFilters ()
virtual ~GeneralFilters ()
virtual int compute ()
Performs the actual filter job.
Public Member Functions inherited from BasePclModule
BasePclModule (PclModuleDescription desc=PclModuleDescription(), ccPluginInterface *parent_plugin=0)
Default constructor.
QAction * getAction ()
Get the action associated with the button used in menu and toolbar creation.
QString getStatusTip () const
Returns the status tip.
QString getModuleName () const
Returns the name of the filter.
QString getEntryName () const
Returns the entry name.
QIcon getIcon () const
Returns the icon associated with the button.
void setShowProgressBar (bool status)
Sets whether to show a progressbar while computing or not.
std::vector< std::string > getSelectedAvailableScalarFields ()
ccPointCloud * getSelectedEntityAsCCPointCloud () const
Returns the first selected entity as a ccPointCloud.
ccHObject * getSelectedEntityAsCCHObject () const
Returns the first selected entity as a ccHObject.
ccHObject::Container getSelectedThatHaveMetaData (const QString key) const
Get selected object that also have the provided metadata key.
void getAllEntitiesOfType (CV_CLASS_ENUM type, ccHObject::Container &entities)
Returns all the objects in db tree of type "type".
void getAllEntitiesThatHaveMetaData (QString key, ccHObject::Container &entities)
void getSelectedEntitiesThatAreCCPointCloud (ccHObject::Container &entities)
get all entities that are selected and that also are cc_point_cloud
void getSelectedEntitiesThatAre (CV_CLASS_ENUM kind, ccHObject::Container &entities)
int hasSelectedRGB ()
Returns 1 if the first selected entity has RGB info.
int hasSelectedScalarField ()
Returns 1 if the first selected entity has at least one scalar field.
int hasSelectedScalarField (std::string field_name)
int isFirstSelectedCcPointCloud ()
Returns 1 if the first selected object is a ccPointCloud.
virtual void updateSelectedEntities (const ccHObject::Container &selectedEntities)
Updates the internal copy of selected entities.
void setMainAppInterface (ecvMainAppInterface *app)
Sets associated CC application interface (to access DB)
ecvMainAppInterface * getMainAppInterface ()
ccPluginInterface * getParentPlugin () const
Returns the associated parent plugin interface.
Protected Types
enum FilterType {
PASS_FILTER , CR_FILTER , VOXEL_FILTER , PM_FILTER ,
HULL_FILTER
}
Protected Member Functions
virtual int openInputDialog ()
virtual int checkParameters ()
virtual void getParametersFromDialog ()
Collects parameters from the filter dialog (if openDialog is successful)
virtual QString getErrorMessage (int errorCode)
Returns the error message corresponding to a given error code.
Protected Member Functions inherited from BasePclModule
virtual int checkSelected ()
Checks if current selection is compliant with the filter.
virtual int openOutputDialog ()
virtual int start ()
Starts computation.
virtual void initAction ()
Initializes the corresponding action.
void throwError (int errCode)
Protected Attributes
GeneralFiltersDlg * m_dialog
bool m_keepColors
bool m_hasColors
FilterType m_filterType
QString m_comparisonField
QStringList m_comparisonTypes
float m_minMagnitude
float m_maxMagnitude
bool m_extractRemainings
int m_maxWindowSize
float m_slope
float m_initialDistance
float m_maxDistance
float m_leafSize
ccPolyline * m_polyline
std::vector< CCVector3 > m_boundary
int m_dimension
Protected Attributes inherited from BasePclModule
QAction * m_action
Forces the Ui to be updated.
ccHObject::Container m_selected
Pointer to the main window.
PclModuleDescription m_desc
Associated dialog.
ecvMainAppInterface * m_app
Associated application interface.
ccPluginInterface * m_parent_plugin
associated parent plugin of the filter
bool m_show_progress
Do we want to show a progress bar when the filter works?
Additional Inherited Members
Signals inherited from BasePclModule
void entityHasChanged (ccHObject *)
Signal emitted when an entity is (visually) modified.
void newEntity (ccHObject *)
Signal emitted when a new entity is created by the filter.
void newErrorMessage (QString)
Signal emitted when a new error message is produced.
Protected Slots inherited from BasePclModule
int performAction ()
Returns is called when the dialog window is accepted.
Detailed Description
Projection Filter.
Definition at line 19 of file GeneralFilters.h.
Member Enumeration Documentation
FilterType
enum GeneralFilters::FilterType protected
Enumerator
PASS_FILTER
CR_FILTER
VOXEL_FILTER
PM_FILTER
HULL_FILTER
Definition at line 40 of file GeneralFilters.h.
Constructor & Destructor Documentation
GeneralFilters()
GeneralFilters::GeneralFilters ()
Definition at line 27 of file GeneralFilters.cpp.
~GeneralFilters()
GeneralFilters::~GeneralFilters () virtual
Definition at line 50 of file GeneralFilters.cpp.
References m_dialog.
Member Function Documentation
checkParameters()
int GeneralFilters::checkParameters () protected virtual
Checks that the parameters retrieved by getParametersFromDialog are valid Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Returns
1 if parameters are valid (error code otherwise)
Reimplemented from BasePclModule.
Definition at line 123 of file GeneralFilters.cpp.
References m_maxMagnitude, and m_minMagnitude.
compute()
int GeneralFilters::compute () virtual
Performs the actual filter job.
This method MUST be re-implemented by derived filter
Returns
1 if successful (error code otherwise)
Implements BasePclModule.
Definition at line 130 of file GeneralFilters.cpp.
References ccHObject::addChild(), CR_FILTER, ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccObject::getName(), ccHObject::getParent(), cloudViewer::ReferenceCloud::getPoint(), BasePclModule::getSelectedEntityAsCCPointCloud(), ccPointCloud::hasColors(), ccPointCloud::hasScalarFields(), HULL_FILTER, m_boundary, m_comparisonField, m_comparisonTypes, m_dimension, m_extractRemainings, m_filterType, m_hasColors, m_initialDistance, m_keepColors, m_leafSize, m_maxDistance, m_maxMagnitude, m_maxWindowSize, m_minMagnitude, m_polyline, m_slope, name, BasePclModule::newEntity(), PASS_FILTER, PM_FILTER, ecvColor::Generator::Random(), ccObject::setEnabled(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccObject::setName(), ccPointCloud::setRGBColor(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), cloudViewer::ReferenceCloud::size(), type, VOXEL_FILTER, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
getErrorMessage()
QString GeneralFilters::getErrorMessage (int errorCode) protected virtual
Returns the error message corresponding to a given error code.
Each filter have a set of possible error message to be used given bt getFilterErrorMessage() Baseclass implementation provides some generic messages.
Note
These messages can be replaced by re-implementing this method and handling the same codes BEFORE calling the baseclass method
Reimplemented from BasePclModule.
Definition at line 390 of file GeneralFilters.cpp.
References BasePclModule::getErrorMessage().
getParametersFromDialog()
void GeneralFilters::getParametersFromDialog () protected virtual
Collects parameters from the filter dialog (if openDialog is successful)
Automatically called by performAction. Does nothing by default. Must be overridden if necessary.
Reimplemented from BasePclModule.
Definition at line 64 of file GeneralFilters.cpp.
References GeneralFiltersDlg::getComparisonField(), GeneralFiltersDlg::getComparisonTypes(), GeneralFiltersDlg::getContour(), GeneralFiltersDlg::getPolyline(), m_boundary, m_comparisonField, m_comparisonTypes, m_dialog, m_dimension, m_extractRemainings, m_filterType, m_initialDistance, m_keepColors, m_leafSize, m_maxDistance, m_maxMagnitude, m_maxWindowSize, m_minMagnitude, m_polyline, and m_slope.
openInputDialog()
int GeneralFilters::openInputDialog () protected virtual
Opens the input dialog window. Where the user can supply parameters for the computation Automatically called by performAction. Does nothing by default. Must be overridden if a dialog must be displayed.
Returns
1 if dialog has been successfully executed, 0 if canceled, negative error code otherwise
Reimplemented from BasePclModule.
Definition at line 55 of file GeneralFilters.cpp.
References BasePclModule::m_app, m_dialog, and GeneralFiltersDlg::refreshPolylineComboBox().
Member Data Documentation
m_boundary
std::vector<CCVector3> GeneralFilters::m_boundary protected
Definition at line 69 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
m_comparisonField
QString GeneralFilters::m_comparisonField protected
Definition at line 51 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
m_comparisonTypes
QStringList GeneralFilters::m_comparisonTypes protected
Definition at line 52 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
m_dialog
GeneralFiltersDlg* GeneralFilters::m_dialog protected
Definition at line 34 of file GeneralFilters.h.
Referenced by getParametersFromDialog(), openInputDialog(), and ~GeneralFilters().
m_dimension
int GeneralFilters::m_dimension protected
Definition at line 70 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
m_extractRemainings
bool GeneralFilters::m_extractRemainings protected
Definition at line 57 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
m_filterType
FilterType GeneralFilters::m_filterType protected
Definition at line 48 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
m_hasColors
bool GeneralFilters::m_hasColors protected
Definition at line 38 of file GeneralFilters.h.
Referenced by compute().
m_initialDistance
float GeneralFilters::m_initialDistance protected
Definition at line 60 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
m_keepColors
bool GeneralFilters::m_keepColors protected
Definition at line 36 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
m_leafSize
float GeneralFilters::m_leafSize protected
Definition at line 65 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
m_maxDistance
float GeneralFilters::m_maxDistance protected
Definition at line 61 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
m_maxMagnitude
float GeneralFilters::m_maxMagnitude protected
Definition at line 54 of file GeneralFilters.h.
Referenced by checkParameters(), compute(), and getParametersFromDialog().
m_maxWindowSize
int GeneralFilters::m_maxWindowSize protected
Definition at line 58 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
m_minMagnitude
float GeneralFilters::m_minMagnitude protected
Definition at line 53 of file GeneralFilters.h.
Referenced by checkParameters(), compute(), and getParametersFromDialog().
m_polyline
ccPolyline* GeneralFilters::m_polyline protected
Definition at line 68 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
m_slope
float GeneralFilters::m_slope protected
Definition at line 59 of file GeneralFilters.h.
Referenced by compute(), and getParametersFromDialog().
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/GeneralFilters.h
/root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/GeneralFilters.cpp