ACloudViewer: QuaGzipFile Class Reference
QuaGzipFile Class Reference
GZIP file.
#include <quagzipfile.h>
Public Member Functions
QuaGzipFile ()
Empty constructor.
QuaGzipFile (QObject *parent)
Empty constructor with a parent.
QuaGzipFile (const QString &fileName, QObject *parent=NULL)
Constructor.
virtual ~QuaGzipFile ()
Destructor.
void setFileName (const QString &fileName)
Sets the name of the GZIP file to be opened.
QString getFileName () const
Returns the name of the GZIP file.
virtual bool isSequential () const
Returns true.
virtual bool open (QIODevice::OpenMode mode)
Opens the file.
virtual bool open (int fd, QIODevice::OpenMode mode)
Opens the file.
virtual bool flush ()
Flushes data to file.
virtual void close ()
Closes the file.
Protected Member Functions
virtual qint64 readData (char *data, qint64 maxSize)
Implementation of QIODevice::readData().
virtual qint64 writeData (const char *data, qint64 maxSize)
Implementation of QIODevice::writeData().
Detailed Description
GZIP file.
This class is a wrapper around GZIP file access functions in zlib. Unlike QuaZip classes, it doesn't allow reading from a GZIP file opened as QIODevice, for example, if your GZIP file is in QBuffer. It only provides QIODevice access to a GZIP file contents, but the GZIP file itself must be identified by its name on disk or by descriptor id.
Definition at line 44 of file quagzipfile.h.
Constructor & Destructor Documentation
QuaGzipFile() [1/3]
QuaGzipFile::QuaGzipFile ()
Empty constructor.
Must call setFileName() before trying to open.
Definition at line 88 of file quagzipfile.cpp.
QuaGzipFile() [2/3]
QuaGzipFile::QuaGzipFile (QObject * parent)
Empty constructor with a parent.
Must call setFileName() before trying to open.
Parameters
parent The parent object, as per QObject logic.
Definition at line 90 of file quagzipfile.cpp.
QuaGzipFile() [3/3]
QuaGzipFile::QuaGzipFile (const QString & fileName, QObject * parent = NULL)
Constructor.
Parameters
fileName The name of the GZIP file.
parent The parent object, as per QObject logic.
Definition at line 93 of file quagzipfile.cpp.
~QuaGzipFile()
QuaGzipFile::~QuaGzipFile () virtual
Destructor.
Definition at line 96 of file quagzipfile.cpp.
References close(), and isOpen.
Member Function Documentation
close()
void QuaGzipFile::close () virtual
Closes the file.
Definition at line 131 of file quagzipfile.cpp.
Referenced by ~QuaGzipFile().
flush()
bool QuaGzipFile::flush () virtual
Flushes data to file.
The data is written using Z_SYNC_FLUSH mode. Doesn't make any sense when reading.
Definition at line 129 of file quagzipfile.cpp.
getFileName()
QString QuaGzipFile::getFileName () const
Returns the name of the GZIP file.
Definition at line 107 of file quagzipfile.cpp.
isSequential()
bool QuaGzipFile::isSequential () const virtual
Returns true.
Strictly speaking, zlib supports seeking for GZIP files, but it is poorly implemented, because there is no way to implement it properly. For reading, seeking backwards is very slow, and for writing, it is downright impossible. Therefore, QuaGzipFile does not support seeking at all.
Definition at line 109 of file quagzipfile.cpp.
open() [1/2]
bool QuaGzipFile::open (int fd, QIODevice::OpenMode mode) virtual
Opens the file.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
fd The file descriptor to read/write the GZIP file from/to.
mode Can be either QIODevice::Write or QIODevice::Read. ReadWrite and Append aren't supported.
Definition at line 120 of file quagzipfile.cpp.
References error().
open() [2/2]
bool QuaGzipFile::open (QIODevice::OpenMode mode) virtual
Opens the file.
Parameters
mode Can be either QIODevice::Write or QIODevice::Read. ReadWrite and Append aren't supported.
Definition at line 111 of file quagzipfile.cpp.
References error().
readData()
qint64 QuaGzipFile::readData (char * data, qint64 maxSize) protected virtual
Implementation of QIODevice::readData().
Definition at line 136 of file quagzipfile.cpp.
setFileName()
void QuaGzipFile::setFileName (const QString & fileName)
Sets the name of the GZIP file to be opened.
Definition at line 103 of file quagzipfile.cpp.
writeData()
qint64 QuaGzipFile::writeData (const char * data, qint64 maxSize) protected virtual
Implementation of QIODevice::writeData().
Definition at line 140 of file quagzipfile.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qPhotoscanIO/extern/quazip/quazip/quazip/quagzipfile.h
/root/ACloudViewer/plugins/core/IO/qPhotoscanIO/extern/quazip/quazip/quazip/quagzipfile.cpp