ACloudViewer: qRansacSD Class Reference
qRansacSD Class Reference
#include <qRANSAC_SD.h>
Protected Slots
void doAction ()
Slot called when associated ation is triggered.
Protected Attributes
QAction * m_action
Associated action.
Protected Attributes inherited from ccStdPluginInterface
ecvMainAppInterface * m_app
Main application interface.
Additional Inherited Members
Public Types inherited from ccPluginInterface
typedef QList< Contact > ContactList
using ReferenceList = QList< Reference >
Public Member Functions inherited from ccStdPluginInterface
ccStdPluginInterface (const QString &resourcePath=QString())
Default constructor.
virtual ~ccStdPluginInterface () override=default
Destructor.
virtual CC_PLUGIN_TYPE getType () const override
Returns plugin type (standard or OpenGL filter)
virtual void setMainAppInterface (ecvMainAppInterface *app)
Sets application entry point.
virtual ecvMainAppInterface * getMainAppInterface ()
A callback pointer to the main app interface for use by plugins.
virtual void dispToConsole (QString message, ecvMainAppInterface::ConsoleMessageLevel level=ecvMainAppInterface::STD_CONSOLE_MESSAGE)
Shortcut to ecvMainAppInterface::dispToConsole.
Public Member Functions inherited from ccDefaultPluginInterface
virtual ~ccDefaultPluginInterface ()
virtual bool isCore () const override
Is this plugin a core plugin?
virtual QString getName () const override
Returns (short) name (for menu entry, etc.)
virtual QString getDescription () const override
Returns long name/description (for tooltip, etc.)
virtual QIcon getIcon () const override
Returns icon.
virtual ReferenceList getReferences () const override
virtual ContactList getAuthors () const override
virtual ContactList getMaintainers () const override
Public Member Functions inherited from ccPluginInterface
virtual ~ccPluginInterface ()=default
Virtual destructor.
virtual bool start ()
Starts the plugin.
virtual void stop ()
Stops the plugin.
virtual ccExternalFactory * getCustomObjectsFactory () const
Returns the plugin's custom object factory (if any)
Protected Member Functions inherited from ccDefaultPluginInterface
ccDefaultPluginInterface (const QString &resourcePath=QString())
Detailed Description
Wrapper to Schnabel et al. library for automatic shape detection in point cloud "Efficient RANSAC for Point-Cloud Shape Detection", Ruwen Schnabel, Roland Wahl, and Reinhard Klein, in Computer Graphics Forum (June 2007), 26:2(214-226) http://cg.cs.uni-bonn.de/en/publications/paper-details/schnabel-2007-efficient/
Definition at line 18 of file qRANSAC_SD.h.
Member Function Documentation
doAction
void qRansacSD::doAction () protected slot
Slot called when associated ation is triggered.
Definition at line 121 of file qRANSAC_SD.cpp.
References ecvMainAppInterface::addToDB(), CVLog::Error(), ecvMainAppInterface::getActiveWindow(), cloudViewer::PointCloudTpl< T >::getBoundingBox(), ecvMainAppInterface::getSelectedEntities(), ccObject::isA(), ccStdPluginInterface::m_app, CV_TYPES::POINT_CLOUD, s_maxNormalDev_deg, s_maxRadius, s_minRadius, s_primEnabled, s_proba, s_randomColor, and s_supportPoints.
Member Data Documentation
m_action
QAction* qRansacSD::m_action protected
Associated action.
Definition at line 99 of file qRANSAC_SD.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/qRANSAC_SD/include/qRANSAC_SD.h
/root/ACloudViewer/plugins/core/Standard/qRANSAC_SD/src/qRANSAC_SD.cpp