ACloudViewer: AtomicCounter Class Reference
AtomicCounter Class Reference
Fake QAtomicInt.
Public Member Functions
AtomicCounter ()
int load ()
void store (int value)
int fetchAndAddRelaxed (int add)
Public Attributes
int m_value
Detailed Description
Fake QAtomicInt.
Warning
Not thread safe!
Definition at line 27 of file NormalizedProgress.cpp.
Constructor & Destructor Documentation
AtomicCounter()
AtomicCounter::AtomicCounter () inline
Definition at line 29 of file NormalizedProgress.cpp.
Member Function Documentation
fetchAndAddRelaxed()
int AtomicCounter::fetchAndAddRelaxed (int add) inline
Definition at line 32 of file NormalizedProgress.cpp.
References m_value.
Referenced by cloudViewer::NormalizedProgress::oneStep(), and cloudViewer::NormalizedProgress::steps().
load()
int AtomicCounter::load () inline
Definition at line 30 of file NormalizedProgress.cpp.
References m_value.
Referenced by cloudViewer::NormalizedProgress::scale().
store()
void AtomicCounter::store (int value) inline
Definition at line 31 of file NormalizedProgress.cpp.
References m_value.
Referenced by cloudViewer::NormalizedProgress::reset(), and cloudViewer::NormalizedProgress::scale().
Member Data Documentation
m_value
int AtomicCounter::m_value
Definition at line 37 of file NormalizedProgress.cpp.
Referenced by fetchAndAddRelaxed(), load(), and store().
The documentation for this class was generated from the following file:
/root/ACloudViewer/core/src/NormalizedProgress.cpp