ACloudViewer: colmap::DatabaseImageViewerWidget Class Reference
colmap::DatabaseImageViewerWidget Class Reference
#include <image_viewer_widget.h>
Public Member Functions
DatabaseImageViewerWidget (QWidget *parent, ModelViewerWidget *model_viewer_widget, OptionManager *options)
void ShowImageWithId (const image_t image_id)
Public Member Functions inherited from colmap::FeatureImageViewerWidget
FeatureImageViewerWidget (QWidget *parent, const std::string &switch_text)
void ReadAndShowWithKeypoints (const std::string &path, const FeatureKeypoints &keypoints, const std::vector< char > &tri_mask)
void ReadAndShowWithMatches (const std::string &path1, const std::string &path2, const FeatureKeypoints &keypoints1, const FeatureKeypoints &keypoints2, const FeatureMatches &matches)
Public Member Functions inherited from colmap::ImageViewerWidget
ImageViewerWidget (QWidget *parent)
void ShowBitmap (const Bitmap &bitmap)
void ShowPixmap (const QPixmap &pixmap)
void ReadAndShow (const std::string &path)
Additional Inherited Members
Protected Member Functions inherited from colmap::FeatureImageViewerWidget
void ShowOrHide ()
Protected Member Functions inherited from colmap::ImageViewerWidget
void resizeEvent (QResizeEvent *event)
void closeEvent (QCloseEvent *event)
void ZoomIn ()
void ZoomOut ()
void Save ()
Protected Attributes inherited from colmap::FeatureImageViewerWidget
QPixmap image1_
QPixmap image2_
bool switch_state_
QPushButton * switch_button_
const std::string switch_text_
Protected Attributes inherited from colmap::ImageViewerWidget
QGridLayout * grid_layout_
QHBoxLayout * button_layout_
Detailed Description
Definition at line 82 of file image_viewer_widget.h.
Constructor & Destructor Documentation
DatabaseImageViewerWidget()
colmap::DatabaseImageViewerWidget::DatabaseImageViewerWidget (QWidget * parent, ModelViewerWidget * model_viewer_widget, OptionManager * options)
Definition at line 242 of file image_viewer_widget.cc.
Member Function Documentation
ShowImageWithId()
void colmap::DatabaseImageViewerWidget::ShowImageWithId (const image_t image_id)
Definition at line 338 of file image_viewer_widget.cc.
References colmap::ModelViewerWidget::cameras, colmap::Camera::Height(), image, colmap::OptionManager::image_path, colmap::ModelViewerWidget::images, colmap::JoinPaths(), colmap::Camera::ModelName(), colmap::Camera::ParamsToString(), cloudViewer::t::geometry::path, colmap::FeatureImageViewerWidget::ReadAndShowWithKeypoints(), and colmap::Camera::Width().
Referenced by colmap::ModelViewerWidget::ShowImageInfo().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/ui/image_viewer_widget.h
/root/ACloudViewer/libs/Reconstruction/src/ui/image_viewer_widget.cc