ACloudViewer: ccHistogramWindow Class Reference
ccHistogramWindow Class Reference
Histogram widget.
#include <ecvHistogramWindow.h>
Public Types
enum HISTOGRAM_COLOR_SCHEME { USE_SOLID_COLOR , USE_CUSTOM_COLOR_SCALE , USE_SF_SCALE }
enum class AxisDisplayOption { None = 0x0 , XAxis = 0x01 , YAxis = 0x02 , All = XAxis | YAxis }
enum class SFInteractionMode { None = 0x0 , DisplayRange = 0x01 , SaturationRange = 0x02 , All = DisplayRange | SaturationRange }
Public Types inherited from QCustomPlot
enum LayerInsertMode { limBelow , limAbove , limBelow , limAbove }
enum RefreshPriority {
rpImmediateRefresh , rpQueuedRefresh , rpRefreshHint , rpQueuedReplot ,
rpImmediate , rpQueued , rpHint
}
enum LayerInsertMode { limBelow , limAbove , limBelow , limAbove }
enum RefreshPriority {
rpImmediateRefresh , rpQueuedRefresh , rpRefreshHint , rpQueuedReplot ,
rpImmediate , rpQueued , rpHint
}
Signals
void sfMinDispValChanged (double)
void sfMaxDispValChanged (double)
void sfMinSatValChanged (double)
void sfMaxSatValChanged (double)
Signals inherited from QCustomPlot
void mouseDoubleClick (QMouseEvent *event)
void mousePress (QMouseEvent *event)
void mouseMove (QMouseEvent *event)
void mouseRelease (QMouseEvent *event)
void mouseWheel (QWheelEvent *event)
void plottableClick (QCPAbstractPlottable *plottable, int dataIndex, QMouseEvent *event)
void plottableDoubleClick (QCPAbstractPlottable *plottable, int dataIndex, QMouseEvent *event)
void itemClick (QCPAbstractItem *item, QMouseEvent *event)
void itemDoubleClick (QCPAbstractItem *item, QMouseEvent *event)
void axisClick (QCPAxis *axis, QCPAxis::SelectablePart part, QMouseEvent *event)
void axisDoubleClick (QCPAxis *axis, QCPAxis::SelectablePart part, QMouseEvent *event)
void legendClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
void legendDoubleClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
void selectionChangedByUser ()
void beforeReplot ()
void afterReplot ()
void mouseDoubleClick (QMouseEvent *event)
void mousePress (QMouseEvent *event)
void mouseMove (QMouseEvent *event)
void mouseRelease (QMouseEvent *event)
void mouseWheel (QWheelEvent *event)
void plottableClick (QCPAbstractPlottable *plottable, QMouseEvent *event)
void plottableDoubleClick (QCPAbstractPlottable *plottable, QMouseEvent *event)
void itemClick (QCPAbstractItem *item, QMouseEvent *event)
void itemDoubleClick (QCPAbstractItem *item, QMouseEvent *event)
void axisClick (QCPAxis *axis, QCPAxis::SelectablePart part, QMouseEvent *event)
void axisDoubleClick (QCPAxis *axis, QCPAxis::SelectablePart part, QMouseEvent *event)
void legendClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
void legendDoubleClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
void titleClick (QMouseEvent *event, QCPPlotTitle *title)
void titleDoubleClick (QMouseEvent *event, QCPPlotTitle *title)
void selectionChangedByUser ()
void beforeReplot ()
void afterReplot ()
Public Member Functions
ccHistogramWindow (QWidget *parent=0)
Default constructor.
virtual ~ccHistogramWindow ()
Destructor.
void setTitle (const QString &str)
Sets title.
void setAxisLabels (const QString &xLabel, const QString &yLabel)
Sets axis labels.
void fromSF (ccScalarField *sf, unsigned initialNumberOfClasses=0, bool numberOfClassesCanBeChanged=true, bool showNaNValuesInGrey=true)
Computes histogram from a scalar field.
void fromBinArray (const std::vector< unsigned > &histoValues, double minVal, double maxVal)
void setCurveValues (const std::vector< double > &curveValues)
Sets overlay curve values.
void setColorScheme (HISTOGRAM_COLOR_SCHEME scheme)
Sets how the gradient bars should be colored.
void setSolidColor (QColor color)
Sets solid color.
void setColorScale (ccColorScale::Shared scale)
Sets gradient color scale.
void clear ()
Clears the display.
void refresh ()
Updates the display.
void refreshBars ()
Updates the histogram bars only.
const std::vector< unsigned > & histoValues () const
Returns the current histogram bins.
double minVal () const
Returns the current histogram min value.
double maxVal () const
Returns the current histogram max value.
void setSFInteractionMode (SFInteractionModes modes)
Enables SF interaction mode.
void setAxisDisplayOption (AxisDisplayOptions axisOptions)
void setRefreshAfterResize (bool refreshAfterResize)
void setMinDispValue (double)
void setMaxDispValue (double)
void setMinSatValue (double)
void setMaxSatValue (double)
Public Member Functions inherited from QCustomPlot
QCustomPlot (QWidget *parent=0)
virtual ~QCustomPlot ()
QRect viewport () const
double bufferDevicePixelRatio () const
QPixmap background () const
bool backgroundScaled () const
Qt::AspectRatioMode backgroundScaledMode () const
QCPLayoutGrid * plotLayout () const
QCP::AntialiasedElements antialiasedElements () const
QCP::AntialiasedElements notAntialiasedElements () const
bool autoAddPlottableToLegend () const
const QCP::Interactions interactions () const
int selectionTolerance () const
bool noAntialiasingOnDrag () const
QCP::PlottingHints plottingHints () const
Qt::KeyboardModifier multiSelectModifier () const
QCP::SelectionRectMode selectionRectMode () const
QCPSelectionRect * selectionRect () const
bool openGl () const
void setViewport (const QRect &rect)
void setBufferDevicePixelRatio (double ratio)
void setBackground (const QPixmap &pm)
void setBackground (const QPixmap &pm, bool scaled, Qt::AspectRatioMode mode=Qt::KeepAspectRatioByExpanding)
void setBackground (const QBrush &brush)
void setBackgroundScaled (bool scaled)
void setBackgroundScaledMode (Qt::AspectRatioMode mode)
void setAntialiasedElements (const QCP::AntialiasedElements &antialiasedElements)
void setAntialiasedElement (QCP::AntialiasedElement antialiasedElement, bool enabled=true)
void setNotAntialiasedElements (const QCP::AntialiasedElements &notAntialiasedElements)
void setNotAntialiasedElement (QCP::AntialiasedElement notAntialiasedElement, bool enabled=true)
void setAutoAddPlottableToLegend (bool on)
void setInteractions (const QCP::Interactions &interactions)
void setInteraction (const QCP::Interaction &interaction, bool enabled=true)
void setSelectionTolerance (int pixels)
void setNoAntialiasingOnDrag (bool enabled)
void setPlottingHints (const QCP::PlottingHints &hints)
void setPlottingHint (QCP::PlottingHint hint, bool enabled=true)
void setMultiSelectModifier (Qt::KeyboardModifier modifier)
void setSelectionRectMode (QCP::SelectionRectMode mode)
void setSelectionRect (QCPSelectionRect *selectionRect)
void setOpenGl (bool enabled, int multisampling=16)
QCPAbstractPlottable * plottable (int index)
QCPAbstractPlottable * plottable ()
bool removePlottable (QCPAbstractPlottable *plottable)
bool removePlottable (int index)
int clearPlottables ()
int plottableCount () const
QList< QCPAbstractPlottable * > selectedPlottables () const
QCPAbstractPlottable * plottableAt (const QPointF &pos, bool onlySelectable=false) const
bool hasPlottable (QCPAbstractPlottable *plottable) const
QCPGraph * graph (int index) const
QCPGraph * graph () const
QCPGraph * addGraph (QCPAxis *keyAxis=0, QCPAxis *valueAxis=0)
bool removeGraph (QCPGraph *graph)
bool removeGraph (int index)
int clearGraphs ()
int graphCount () const
QList< QCPGraph * > selectedGraphs () const
QCPAbstractItem * item (int index) const
QCPAbstractItem * item () const
bool removeItem (QCPAbstractItem *item)
bool removeItem (int index)
int clearItems ()
int itemCount () const
QList< QCPAbstractItem * > selectedItems () const
QCPAbstractItem * itemAt (const QPointF &pos, bool onlySelectable=false) const
bool hasItem (QCPAbstractItem *item) const
QCPLayer * layer (const QString &name) const
QCPLayer * layer (int index) const
QCPLayer * currentLayer () const
bool setCurrentLayer (const QString &name)
bool setCurrentLayer (QCPLayer *layer)
int layerCount () const
bool addLayer (const QString &name, QCPLayer *otherLayer=0, LayerInsertMode insertMode=limAbove)
bool removeLayer (QCPLayer *layer)
bool moveLayer (QCPLayer *layer, QCPLayer *otherLayer, LayerInsertMode insertMode=limAbove)
int axisRectCount () const
QCPAxisRect * axisRect (int index=0) const
QList< QCPAxisRect * > axisRects () const
QCPLayoutElement * layoutElementAt (const QPointF &pos) const
QCPAxisRect * axisRectAt (const QPointF &pos) const
Q_SLOT void rescaleAxes (bool onlyVisiblePlottables=false)
QList< QCPAxis * > selectedAxes () const
QList< QCPLegend * > selectedLegends () const
Q_SLOT void deselectAll ()
bool savePdf (const QString &fileName, int width=0, int height=0, QCP::ExportPen exportPen=QCP::epAllowCosmetic, const QString &pdfCreator=QString(), const QString &pdfTitle=QString())
bool savePng (const QString &fileName, int width=0, int height=0, double scale=1.0, int quality=-1, int resolution=96, QCP::ResolutionUnit resolutionUnit=QCP::ruDotsPerInch)
bool saveJpg (const QString &fileName, int width=0, int height=0, double scale=1.0, int quality=-1, int resolution=96, QCP::ResolutionUnit resolutionUnit=QCP::ruDotsPerInch)
bool saveBmp (const QString &fileName, int width=0, int height=0, double scale=1.0, int resolution=96, QCP::ResolutionUnit resolutionUnit=QCP::ruDotsPerInch)
bool saveRastered (const QString &fileName, int width, int height, double scale, const char *format, int quality=-1, int resolution=96, QCP::ResolutionUnit resolutionUnit=QCP::ruDotsPerInch)
QPixmap toPixmap (int width=0, int height=0, double scale=1.0)
void toPainter (QCPPainter *painter, int width=0, int height=0)
Q_SLOT void replot (QCustomPlot::RefreshPriority refreshPriority=QCustomPlot::rpRefreshHint)
QCustomPlot (QWidget *parent=0)
virtual ~QCustomPlot ()
QRect viewport () const
QPixmap background () const
bool backgroundScaled () const
Qt::AspectRatioMode backgroundScaledMode () const
QCPLayoutGrid * plotLayout () const
QCP::AntialiasedElements antialiasedElements () const
QCP::AntialiasedElements notAntialiasedElements () const
bool autoAddPlottableToLegend () const
const QCP::Interactions interactions () const
int selectionTolerance () const
bool noAntialiasingOnDrag () const
QCP::PlottingHints plottingHints () const
Qt::KeyboardModifier multiSelectModifier () const
void setViewport (const QRect &rect)
void setBackground (const QPixmap &pm)
void setBackground (const QPixmap &pm, bool scaled, Qt::AspectRatioMode mode=Qt::KeepAspectRatioByExpanding)
void setBackground (const QBrush &brush)
void setBackgroundScaled (bool scaled)
void setBackgroundScaledMode (Qt::AspectRatioMode mode)
void setAntialiasedElements (const QCP::AntialiasedElements &antialiasedElements)
void setAntialiasedElement (QCP::AntialiasedElement antialiasedElement, bool enabled=true)
void setNotAntialiasedElements (const QCP::AntialiasedElements &notAntialiasedElements)
void setNotAntialiasedElement (QCP::AntialiasedElement notAntialiasedElement, bool enabled=true)
void setAutoAddPlottableToLegend (bool on)
void setInteractions (const QCP::Interactions &interactions)
void setInteraction (const QCP::Interaction &interaction, bool enabled=true)
void setSelectionTolerance (int pixels)
void setNoAntialiasingOnDrag (bool enabled)
void setPlottingHints (const QCP::PlottingHints &hints)
void setPlottingHint (QCP::PlottingHint hint, bool enabled=true)
void setMultiSelectModifier (Qt::KeyboardModifier modifier)
QCPAbstractPlottable * plottable (int index)
QCPAbstractPlottable * plottable ()
bool addPlottable (QCPAbstractPlottable *plottable)
bool removePlottable (QCPAbstractPlottable *plottable)
bool removePlottable (int index)
int clearPlottables ()
int plottableCount () const
QList< QCPAbstractPlottable * > selectedPlottables () const
QCPAbstractPlottable * plottableAt (const QPointF &pos, bool onlySelectable=false) const
bool hasPlottable (QCPAbstractPlottable *plottable) const
QCPGraph * graph (int index) const
QCPGraph * graph () const
QCPGraph * addGraph (QCPAxis *keyAxis=0, QCPAxis *valueAxis=0)
bool removeGraph (QCPGraph *graph)
bool removeGraph (int index)
int clearGraphs ()
int graphCount () const
QList< QCPGraph * > selectedGraphs () const
QCPAbstractItem * item (int index) const
QCPAbstractItem * item () const
bool addItem (QCPAbstractItem *item)
bool removeItem (QCPAbstractItem *item)
bool removeItem (int index)
int clearItems ()
int itemCount () const
QList< QCPAbstractItem * > selectedItems () const
QCPAbstractItem * itemAt (const QPointF &pos, bool onlySelectable=false) const
bool hasItem (QCPAbstractItem *item) const
QCPLayer * layer (const QString &name) const
QCPLayer * layer (int index) const
QCPLayer * currentLayer () const
bool setCurrentLayer (const QString &name)
bool setCurrentLayer (QCPLayer *layer)
int layerCount () const
bool addLayer (const QString &name, QCPLayer *otherLayer=0, LayerInsertMode insertMode=limAbove)
bool removeLayer (QCPLayer *layer)
bool moveLayer (QCPLayer *layer, QCPLayer *otherLayer, LayerInsertMode insertMode=limAbove)
int axisRectCount () const
QCPAxisRect * axisRect (int index=0) const
QList< QCPAxisRect * > axisRects () const
QCPLayoutElement * layoutElementAt (const QPointF &pos) const
Q_SLOT void rescaleAxes (bool onlyVisiblePlottables=false)
QList< QCPAxis * > selectedAxes () const
QList< QCPLegend * > selectedLegends () const
Q_SLOT void deselectAll ()
bool savePdf (const QString &fileName, bool noCosmeticPen=false, int width=0, int height=0, const QString &pdfCreator=QString(), const QString &pdfTitle=QString())
bool savePng (const QString &fileName, int width=0, int height=0, double scale=1.0, int quality=-1)
bool saveJpg (const QString &fileName, int width=0, int height=0, double scale=1.0, int quality=-1)
bool saveBmp (const QString &fileName, int width=0, int height=0, double scale=1.0)
bool saveRastered (const QString &fileName, int width, int height, double scale, const char *format, int quality=-1)
QPixmap toPixmap (int width=0, int height=0, double scale=1.0)
void toPainter (QCPPainter *painter, int width=0, int height=0)
Q_SLOT void replot (QCustomPlot::RefreshPriority refreshPriority=QCustomPlot::rpHint)
Protected Types
enum SELECTABLE_ITEMS {
NONE , LEFT_AREA , RIGHT_AREA , BOTH_AREAS ,
LEFT_ARROW , RIGHT_ARROW , BOTH_ARROWS
}
Selectable items in "SF interaction" mode.
Protected Member Functions
void setNumberOfClasses (size_t n)
Changes the current number of classes.
void mousePressEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void wheelEvent (QWheelEvent *event)
void resizeEvent (QResizeEvent *event)
unsigned getMaxHistoVal ()
Returns current maximum bin size.
bool computeBinArrayFromSF (size_t binCount)
Dynamically computes histogram bins from scalar field.
void updateOverlayCurveWidth (int w, int h)
Updates overlay curve width depending on the widget display size.
Protected Member Functions inherited from QCustomPlot
virtual QSize minimumSizeHint () const
virtual QSize sizeHint () const
virtual void paintEvent (QPaintEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void draw (QCPPainter *painter)
virtual void updateLayout ()
virtual void axisRemoved (QCPAxis *axis)
virtual void legendRemoved (QCPLegend *legend)
virtual Q_SLOT void processRectSelection (QRect rect, QMouseEvent *event)
virtual Q_SLOT void processRectZoom (QRect rect, QMouseEvent *event)
virtual Q_SLOT void processPointSelection (QMouseEvent *event)
bool registerPlottable (QCPAbstractPlottable *plottable)
bool registerGraph (QCPGraph *graph)
bool registerItem (QCPAbstractItem *item)
void updateLayerIndices () const
QCPLayerable * layerableAt (const QPointF &pos, bool onlySelectable, QVariant *selectionDetails=0) const
QList< QCPLayerable * > layerableListAt (const QPointF &pos, bool onlySelectable, QList< QVariant > *selectionDetails=0) const
void drawBackground (QCPPainter *painter)
void setupPaintBuffers ()
QCPAbstractPaintBuffer * createPaintBuffer ()
bool hasInvalidatedPaintBuffers ()
bool setupOpenGl ()
void freeOpenGl ()
virtual QSize minimumSizeHint () const
virtual QSize sizeHint () const
virtual void paintEvent (QPaintEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void draw (QCPPainter *painter)
virtual void axisRemoved (QCPAxis *axis)
virtual void legendRemoved (QCPLegend *legend)
void updateLayerIndices () const
QCPLayerable * layerableAt (const QPointF &pos, bool onlySelectable, QVariant *selectionDetails=0) const
void drawBackground (QCPPainter *painter)
Protected Attributes
QString m_titleStr
QCPTextElement * m_titlePlot
HISTOGRAM_COLOR_SCHEME m_colorScheme
Color scheme.
QColor m_solidColor
Solid color.
ccColorScale::Shared m_colorScale
Gradient color scale.
ccScalarField * m_associatedSF
Associated scalar field.
bool m_numberOfClassesCanBeChanged
bool m_refreshAfterResize
QCPColoredBars * m_histogram
std::vector< unsigned > m_histoValues
double m_minVal
double m_maxVal
unsigned m_maxHistoVal
QCPGraph * m_overlayCurve
Overlay curve.
std::vector< double > m_curveValues
QCPBarsWithText * m_vertBar
bool m_drawVerticalIndicator
double m_verticalIndicatorPositionPercent
QFont m_renderingFont
Rendering font.
AxisDisplayOptions m_axisDisplayOptions
SFInteractionModes m_sfInteractionModes
Which SF interaction modes are enabled.
SELECTABLE_ITEMS m_selectedItem
Currently selected item.
QCPHiddenArea * m_areaLeft
Left greyed area.
double m_areaLeftlastValue
QCPHiddenArea * m_areaRight
Right greyed area.
double m_areaRightlastValue
QCPArrow * m_arrowLeft
Left arrow.
double m_arrowLeftlastValue
QCPArrow * m_arrowRight
Right arrow.
double m_arrowRightlastValue
QPoint m_lastMouseClick
Last mouse click.
Protected Attributes inherited from QCustomPlot
QRect mViewport
double mBufferDevicePixelRatio
QCPLayoutGrid * mPlotLayout
bool mAutoAddPlottableToLegend
QList< QCPAbstractPlottable * > mPlottables
QList< QCPGraph * > mGraphs
QList< QCPAbstractItem * > mItems
QList< QCPLayer * > mLayers
QCP::AntialiasedElements mAntialiasedElements
QCP::AntialiasedElements mNotAntialiasedElements
QCP::Interactions mInteractions
int mSelectionTolerance
bool mNoAntialiasingOnDrag
QBrush mBackgroundBrush
QPixmap mBackgroundPixmap
QPixmap mScaledBackgroundPixmap
bool mBackgroundScaled
Qt::AspectRatioMode mBackgroundScaledMode
QCPLayer * mCurrentLayer
QCP::PlottingHints mPlottingHints
Qt::KeyboardModifier mMultiSelectModifier
QCP::SelectionRectMode mSelectionRectMode
QCPSelectionRect * mSelectionRect
bool mOpenGl
QList< QSharedPointer< QCPAbstractPaintBuffer > > mPaintBuffers
QPoint mMousePressPos
bool mMouseHasMoved
QPointer< QCPLayerable > mMouseEventLayerable
QPointer< QCPLayerable > mMouseSignalLayerable
QVariant mMouseEventLayerableDetails
QVariant mMouseSignalLayerableDetails
bool mReplotting
bool mReplotQueued
int mOpenGlMultisamples
QCP::AntialiasedElements mOpenGlAntialiasedElementsBackup
bool mOpenGlCacheLabelsBackup
QPixmap mPaintBuffer
QPointer< QCPLayoutElement > mMouseEventElement
Additional Inherited Members
Public Attributes inherited from QCustomPlot
QCPAxis * xAxis
QCPAxis * yAxis
QCPAxis * xAxis2
QCPAxis * yAxis2
QCPLegend * legend
Detailed Description
Histogram widget.
Definition at line 28 of file ecvHistogramWindow.h.
Member Enumeration Documentation
AxisDisplayOption
enum ccHistogramWindow::AxisDisplayOption strong
Enumerator
None
XAxis
YAxis
All
Definition at line 111 of file ecvHistogramWindow.h.
HISTOGRAM_COLOR_SCHEME
enum ccHistogramWindow::HISTOGRAM_COLOR_SCHEME
Enumerator
USE_SOLID_COLOR
USE_CUSTOM_COLOR_SCALE
USE_SF_SCALE
Definition at line 75 of file ecvHistogramWindow.h.
SELECTABLE_ITEMS
enum ccHistogramWindow::SELECTABLE_ITEMS protected
Selectable items in "SF interaction" mode.
Enumerator
NONE
LEFT_AREA
RIGHT_AREA
BOTH_AREAS
LEFT_ARROW
RIGHT_ARROW
BOTH_ARROWS
Definition at line 218 of file ecvHistogramWindow.h.
SFInteractionMode
enum ccHistogramWindow::SFInteractionMode strong
Enumerator
None
DisplayRange
SaturationRange
All
Definition at line 120 of file ecvHistogramWindow.h.
Constructor & Destructor Documentation
ccHistogramWindow()
ccHistogramWindow::ccHistogramWindow (QWidget * parent = 0) explicit
Default constructor.
Definition at line 35 of file ecvHistogramWindow.cpp.
References QCP::aeAll, m_renderingFont, QCustomPlot::setAntialiasedElements(), QCustomPlot::setAutoAddPlottableToLegend(), QCPAxis::setSubTickLength(), QCPAxis::setTickLength(), QCustomPlot::xAxis, and QCustomPlot::yAxis.
~ccHistogramWindow()
ccHistogramWindow::~ccHistogramWindow () virtual
Destructor.
Definition at line 85 of file ecvHistogramWindow.cpp.
Member Function Documentation
clear()
void ccHistogramWindow::clear ()
Clears the display.
Definition at line 87 of file ecvHistogramWindow.cpp.
References refresh().
Referenced by ccColorFromScalarDlg::updateChannel(), ccColorLevelsDlg::updateHistogram(), and ccColorFromScalarDlg::updateHistogram().
computeBinArrayFromSF()
bool ccHistogramWindow::computeBinArrayFromSF (size_t binCount) protected
Dynamically computes histogram bins from scalar field.
Definition at line 179 of file ecvHistogramWindow.cpp.
References count, cloudViewer::ScalarField::currentSize(), CVLog::Error(), cloudViewer::utility::floor(), ccScalarField::getHistogram(), cloudViewer::ScalarField::getValue(), m_associatedSF, m_histoValues, m_maxVal, m_minVal, and CVLog::Warning().
Referenced by setNumberOfClasses().
fromBinArray()
void ccHistogramWindow::fromBinArray (const std::vector< unsigned > & histoValues, double minVal, double maxVal)
Creates histogram from a bin array (each bin = number of elements per class) Number of classes can't be modified.
Parameters
histoValues array of bins
minVal minimum value
maxVal maximum value
Returns
success
Definition at line 153 of file ecvHistogramWindow.cpp.
References getMaxHistoVal(), histoValues(), m_histoValues, m_maxHistoVal, m_maxVal, m_minVal, m_numberOfClassesCanBeChanged, maxVal(), minVal(), and CVLog::Warning().
Referenced by ccColorFromScalarDlg::ccColorFromScalarDlg(), ccEntityAction::computeStatParams(), MainWindow::spawnHistogramDialog(), and ccColorLevelsDlg::updateHistogram().
fromSF()
void ccHistogramWindow::fromSF (ccScalarField * sf, unsigned initialNumberOfClasses = 0, bool numberOfClassesCanBeChanged = true, bool showNaNValuesInGrey = true)
Computes histogram from a scalar field.
Number of classes can be freely modified afterwards (if enabled).
Parameters
sf associated scalar field
initialNumberOfClasses initial number of classes
numberOfClassesCanBeChanged whether to allow the user to modify the number of classes
showNaNValuesInGrey show NaN values (in gray)
Returns
success
Definition at line 127 of file ecvHistogramWindow.cpp.
References ccScalarField::displayRange(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), CCShareable::link(), m_associatedSF, m_maxVal, m_minVal, m_numberOfClassesCanBeChanged, CCShareable::release(), setColorScheme(), setNumberOfClasses(), ccScalarField::Range::start(), ccScalarField::Range::stop(), and USE_SF_SCALE.
Referenced by sfEditDlg::fillDialogWith(), ccComparisonDlg::showHisto(), and ccColorFromScalarDlg::updateChannel().
getMaxHistoVal()
unsigned ccHistogramWindow::getMaxHistoVal () protected
Returns current maximum bin size.
Definition at line 245 of file ecvHistogramWindow.cpp.
References m_histoValues, and m_maxHistoVal.
Referenced by fromBinArray(), and setNumberOfClasses().
histoValues()
const std::vector<unsigned>& ccHistogramWindow::histoValues () const inline
Returns the current histogram bins.
Definition at line 102 of file ecvHistogramWindow.h.
References m_histoValues.
Referenced by ccHistogramWindowDlg::exportToCSV(), and fromBinArray().
maxVal()
double ccHistogramWindow::maxVal () const inline
Returns the current histogram max value.
Definition at line 108 of file ecvHistogramWindow.h.
References m_maxVal.
Referenced by ccHistogramWindowDlg::exportToCSV(), fromBinArray(), and refresh().
minVal()
double ccHistogramWindow::minVal () const inline
Returns the current histogram min value.
Definition at line 106 of file ecvHistogramWindow.h.
References m_minVal.
Referenced by ccHistogramWindowDlg::exportToCSV(), fromBinArray(), and refresh().
mouseMoveEvent()
void ccHistogramWindow::mouseMoveEvent (QMouseEvent * event) protected virtual
Reimplemented from QCustomPlot.
Definition at line 710 of file ecvHistogramWindow.cpp.
References BOTH_AREAS, BOTH_ARROWS, QCPSelectableCursor::currentVal(), event, LEFT_AREA, LEFT_ARROW, m_areaLeft, m_areaRight, m_arrowLeft, m_arrowRight, m_drawVerticalIndicator, m_histogram, m_histoValues, m_lastMouseClick, m_selectedItem, m_sfInteractionModes, m_verticalIndicatorPositionPercent, NONE, QCPSelectableCursor::pixelToKey(), QCPColoredBars::rect(), refresh(), RIGHT_AREA, RIGHT_ARROW, setMaxDispValue(), setMaxSatValue(), setMinDispValue(), and setMinSatValue().
Referenced by mousePressEvent().
mousePressEvent()
void ccHistogramWindow::mousePressEvent (QMouseEvent * event) protected virtual
Reimplemented from QCustomPlot.
Definition at line 676 of file ecvHistogramWindow.cpp.
References BOTH_AREAS, BOTH_ARROWS, DisplayRange, event, QCPSelectableCursor::isSelectable(), LEFT_AREA, LEFT_ARROW, m_areaLeft, m_areaRight, m_arrowLeft, m_arrowRight, m_lastMouseClick, m_selectedItem, m_sfInteractionModes, mouseMoveEvent(), NONE, RIGHT_AREA, RIGHT_ARROW, and SaturationRange.
refresh()
void ccHistogramWindow::refresh ()
Updates the display.
Definition at line 323 of file ecvHistogramWindow.cpp.
References QCPLayoutGrid::addElement(), QCustomPlot::addGraph(), QCPBarsWithText::appendText(), ecvColor::RgbTpl< Type >::b, QCustomPlot::clearGraphs(), QCustomPlot::clearPlottables(), colors, ecvColor::darkGrey(), ecvGui::ParamStruct::displayedNumPrecision, DisplayRange, ccScalarField::displayRange(), ecvColor::RgbTpl< Type >::g, ccScalarField::getColor(), ccScalarField::getColorRampSteps(), ccScalarField::getColorScale(), ccColorScalesManager::GetDefaultScale(), height, QCPLayoutGrid::insertRow(), ecvColor::lightGrey(), m_areaLeft, m_areaLeftlastValue, m_areaRight, m_areaRightlastValue, m_arrowLeft, m_arrowLeftlastValue, m_arrowRight, m_arrowRightlastValue, m_associatedSF, m_axisDisplayOptions, m_colorScale, m_colorScheme, m_curveValues, m_drawVerticalIndicator, m_histogram, m_histoValues, m_maxHistoVal, m_maxVal, m_minVal, m_overlayCurve, m_renderingFont, m_sfInteractionModes, m_solidColor, m_titlePlot, m_titleStr, m_vertBar, m_verticalIndicatorPositionPercent, ccScalarField::Range::max(), maxVal(), ccScalarField::Range::min(), minVal(), ecvGui::Parameters(), QCustomPlot::plotLayout(), ecvColor::RgbTpl< Type >::r, ecvColor::red(), QCPLayout::remove(), QCustomPlot::replot(), SaturationRange, ccScalarField::saturationRange(), QCPLayerable::setAntialiased(), QCPAbstractPlottable::setAntialiasedFill(), QCPAbstractPlottable::setBrush(), QCPArrow::setColor(), QCPSelectableCursor::setCurrentVal(), QCPColoredBars::setData(), QCPBars::setData(), QCPGraph::setData(), QCPTextElement::setFont(), QCPAbstractPlottable::setName(), QCPAbstractPlottable::setPen(), QCPAxis::setRange(), QCPSelectableCursor::setRange(), QCPBarsWithText::setText(), QCPBarsWithText::setTextAlignment(), QCPLayerable::setVisible(), QCPBars::setWidth(), ccScalarField::Range::start(), ccScalarField::Range::stop(), ccScalarField::symmetricalScale(), updateOverlayCurveWidth(), USE_CUSTOM_COLOR_SCALE, USE_SF_SCALE, USE_SOLID_COLOR, width, x, XAxis, QCustomPlot::xAxis, y, YAxis, and QCustomPlot::yAxis.
Referenced by clear(), ccEntityAction::computeStatParams(), sfEditDlg::logScaleChanged(), mouseMoveEvent(), resizeEvent(), MainWindow::spawnHistogramDialog(), sfEditDlg::symmetricalScaleChanged(), ccColorLevelsDlg::updateHistogram(), ccColorFromScalarDlg::updateHistogram(), and wheelEvent().
refreshBars()
void ccHistogramWindow::refreshBars ()
Updates the histogram bars only.
Only works if a SF is associated and color scheme is USE_SF_SCALE.
Definition at line 276 of file ecvHistogramWindow.cpp.
References ecvColor::RgbTpl< Type >::b, QCPColoredBars::clearData(), colors, ecvColor::RgbTpl< Type >::g, ccScalarField::getColor(), ccScalarField::getColorScale(), ecvColor::lightGrey(), m_associatedSF, m_colorScheme, m_histogram, m_histoValues, m_maxVal, m_minVal, ecvColor::RgbTpl< Type >::r, QCustomPlot::replot(), QCustomPlot::rpImmediateRefresh, QCPColoredBars::setData(), and USE_SF_SCALE.
Referenced by setMaxDispValue(), setMaxSatValue(), setMinDispValue(), and setMinSatValue().
resizeEvent()
void ccHistogramWindow::resizeEvent (QResizeEvent * event) protected virtual
Reimplemented from QCustomPlot.
Definition at line 667 of file ecvHistogramWindow.cpp.
References event, m_refreshAfterResize, refresh(), QCustomPlot::resizeEvent(), and updateOverlayCurveWidth().
setAxisDisplayOption()
void ccHistogramWindow::setAxisDisplayOption (AxisDisplayOptions axisOptions)
Definition at line 315 of file ecvHistogramWindow.cpp.
References m_axisDisplayOptions.
Referenced by ccColorFromScalarDlg::updateHistogram().
setAxisLabels()
void ccHistogramWindow::setAxisLabels (const QString & xLabel, const QString & yLabel)
Sets axis labels.
Definition at line 108 of file ecvHistogramWindow.cpp.
References QCPAxis::setLabel(), QCPLayerable::setVisible(), QCustomPlot::xAxis, and QCustomPlot::yAxis.
Referenced by ccEntityAction::computeStatParams(), ccComparisonDlg::showHisto(), MainWindow::spawnHistogramDialog(), ccColorLevelsDlg::updateHistogram(), and ccColorFromScalarDlg::updateHistogram().
setColorScale()
void ccHistogramWindow::setColorScale (ccColorScale::Shared scale) inline
Sets gradient color scale.
Only used if color scheme is set to USE_CUSTOM_COLOR_SCALE.
Definition at line 90 of file ecvHistogramWindow.h.
References m_colorScale.
Referenced by ccEntityAction::computeStatParams().
setColorScheme()
void ccHistogramWindow::setColorScheme (HISTOGRAM_COLOR_SCHEME scheme) inline
Sets how the gradient bars should be colored.
Definition at line 81 of file ecvHistogramWindow.h.
References m_colorScheme.
Referenced by ccColorLevelsDlg::ccColorLevelsDlg(), ccEntityAction::computeStatParams(), and fromSF().
setCurveValues()
void ccHistogramWindow::setCurveValues (const std::vector< double > & curveValues)
Sets overlay curve values.
The curve will only appear over an histogram
Parameters
curveValues curve points 'Y' coordinates only (regularly sampled between the min and max histogram values)
Definition at line 170 of file ecvHistogramWindow.cpp.
References m_curveValues, and CVLog::Warning().
Referenced by ccEntityAction::computeStatParams().
setMaxDispValue()
void ccHistogramWindow::setMaxDispValue (double val)
Definition at line 605 of file ecvHistogramWindow.cpp.
References QCPSelectableCursor::currentVal(), m_areaRight, m_areaRightlastValue, m_associatedSF, refreshBars(), QCustomPlot::replot(), QCPSelectableCursor::setCurrentVal(), ccScalarField::setMaxDisplayed(), and sfMaxDispValChanged().
Referenced by sfEditDlg::maxValSBChanged(), and mouseMoveEvent().
setMaxSatValue()
void ccHistogramWindow::setMaxSatValue (double val)
Definition at line 639 of file ecvHistogramWindow.cpp.
References QCPSelectableCursor::currentVal(), m_arrowRight, m_arrowRightlastValue, m_associatedSF, refreshBars(), QCustomPlot::replot(), QCPSelectableCursor::setCurrentVal(), ccScalarField::setSaturationStop(), and sfMaxSatValChanged().
Referenced by ccColorFromScalarDlg::maxChanged(), sfEditDlg::maxSatSBChanged(), mouseMoveEvent(), and ccColorFromScalarDlg::setDefaultSatValuePerChannel().
setMinDispValue()
void ccHistogramWindow::setMinDispValue (double val)
Definition at line 588 of file ecvHistogramWindow.cpp.
References QCPSelectableCursor::currentVal(), m_areaLeft, m_areaLeftlastValue, m_associatedSF, refreshBars(), QCustomPlot::replot(), QCPSelectableCursor::setCurrentVal(), ccScalarField::setMinDisplayed(), and sfMinDispValChanged().
Referenced by sfEditDlg::minValSBChanged(), and mouseMoveEvent().
setMinSatValue()
void ccHistogramWindow::setMinSatValue (double val)
Definition at line 622 of file ecvHistogramWindow.cpp.
References QCPSelectableCursor::currentVal(), m_arrowLeft, m_arrowLeftlastValue, m_associatedSF, refreshBars(), QCustomPlot::replot(), QCPSelectableCursor::setCurrentVal(), ccScalarField::setSaturationStart(), and sfMinSatValChanged().
Referenced by ccColorFromScalarDlg::minChanged(), sfEditDlg::minSatSBChanged(), mouseMoveEvent(), and ccColorFromScalarDlg::setDefaultSatValuePerChannel().
setNumberOfClasses()
void ccHistogramWindow::setNumberOfClasses (size_t n) protected
Changes the current number of classes.
Warning: n should be a multiple of 4.
Definition at line 255 of file ecvHistogramWindow.cpp.
References computeBinArrayFromSF(), getMaxHistoVal(), m_associatedSF, m_histoValues, and m_maxHistoVal.
Referenced by fromSF(), and wheelEvent().
setRefreshAfterResize()
void ccHistogramWindow::setRefreshAfterResize (bool refreshAfterResize)
Definition at line 319 of file ecvHistogramWindow.cpp.
References m_refreshAfterResize.
Referenced by ccColorFromScalarDlg::ccColorFromScalarDlg().
setSFInteractionMode()
void ccHistogramWindow::setSFInteractionMode (SFInteractionModes modes)
Enables SF interaction mode.
Definition at line 311 of file ecvHistogramWindow.cpp.
References m_sfInteractionModes.
Referenced by sfEditDlg::sfEditDlg(), and ccColorFromScalarDlg::updateHistogram().
setSolidColor()
void ccHistogramWindow::setSolidColor (QColor color) inline
Sets solid color.
Only used if color scheme is set to USE_SOLID_COLOR.
Definition at line 87 of file ecvHistogramWindow.h.
References color, and m_solidColor.
Referenced by ccColorLevelsDlg::ccColorLevelsDlg(), and ccColorLevelsDlg::updateHistogram().
setTitle()
void ccHistogramWindow::setTitle (const QString & str)
Sets title.
Definition at line 106 of file ecvHistogramWindow.cpp.
References m_titleStr.
Referenced by ccEntityAction::computeStatParams(), ccComparisonDlg::showHisto(), and MainWindow::spawnHistogramDialog().
sfMaxDispValChanged
void ccHistogramWindow::sfMaxDispValChanged (double) signal
Referenced by setMaxDispValue(), and sfEditDlg::sfEditDlg().
sfMaxSatValChanged
void ccHistogramWindow::sfMaxSatValChanged (double) signal
Referenced by ccColorFromScalarDlg::ccColorFromScalarDlg(), setMaxSatValue(), and sfEditDlg::sfEditDlg().
sfMinDispValChanged
void ccHistogramWindow::sfMinDispValChanged (double) signal
Referenced by setMinDispValue(), and sfEditDlg::sfEditDlg().
sfMinSatValChanged
void ccHistogramWindow::sfMinSatValChanged (double) signal
Referenced by ccColorFromScalarDlg::ccColorFromScalarDlg(), setMinSatValue(), and sfEditDlg::sfEditDlg().
updateOverlayCurveWidth()
void ccHistogramWindow::updateOverlayCurveWidth (int w, int h) protected
Updates overlay curve width depending on the widget display size.
Definition at line 656 of file ecvHistogramWindow.cpp.
References m_overlayCurve, QCPAbstractPlottable::pen(), and QCPAbstractPlottable::setPen().
Referenced by refresh(), and resizeEvent().
wheelEvent()
void ccHistogramWindow::wheelEvent (QWheelEvent * event) protected virtual
Reimplemented from QCustomPlot.
Definition at line 822 of file ecvHistogramWindow.cpp.
References e, m_histoValues, m_numberOfClassesCanBeChanged, qtCompatWheelEventDelta(), refresh(), and setNumberOfClasses().
Member Data Documentation
m_areaLeft
QCPHiddenArea* ccHistogramWindow::m_areaLeft protected
Left greyed area.
Definition at line 231 of file ecvHistogramWindow.h.
Referenced by mouseMoveEvent(), mousePressEvent(), refresh(), and setMinDispValue().
m_areaLeftlastValue
double ccHistogramWindow::m_areaLeftlastValue protected
Definition at line 232 of file ecvHistogramWindow.h.
Referenced by refresh(), and setMinDispValue().
m_areaRight
QCPHiddenArea* ccHistogramWindow::m_areaRight protected
Right greyed area.
Definition at line 234 of file ecvHistogramWindow.h.
Referenced by mouseMoveEvent(), mousePressEvent(), refresh(), and setMaxDispValue().
m_areaRightlastValue
double ccHistogramWindow::m_areaRightlastValue protected
Definition at line 235 of file ecvHistogramWindow.h.
Referenced by refresh(), and setMaxDispValue().
m_arrowLeft
QCPArrow* ccHistogramWindow::m_arrowLeft protected
Left arrow.
Definition at line 238 of file ecvHistogramWindow.h.
Referenced by mouseMoveEvent(), mousePressEvent(), refresh(), and setMinSatValue().
m_arrowLeftlastValue
double ccHistogramWindow::m_arrowLeftlastValue protected
Definition at line 239 of file ecvHistogramWindow.h.
Referenced by refresh(), and setMinSatValue().
m_arrowRight
QCPArrow* ccHistogramWindow::m_arrowRight protected
Right arrow.
Definition at line 241 of file ecvHistogramWindow.h.
Referenced by mouseMoveEvent(), mousePressEvent(), refresh(), and setMaxSatValue().
m_arrowRightlastValue
double ccHistogramWindow::m_arrowRightlastValue protected
Definition at line 242 of file ecvHistogramWindow.h.
Referenced by refresh(), and setMaxSatValue().
m_associatedSF
ccScalarField* ccHistogramWindow::m_associatedSF protected
Associated scalar field.
Definition at line 184 of file ecvHistogramWindow.h.
Referenced by computeBinArrayFromSF(), fromSF(), refresh(), refreshBars(), setMaxDispValue(), setMaxSatValue(), setMinDispValue(), setMinSatValue(), and setNumberOfClasses().
m_axisDisplayOptions
AxisDisplayOptions ccHistogramWindow::m_axisDisplayOptions protected
Definition at line 211 of file ecvHistogramWindow.h.
Referenced by refresh(), and setAxisDisplayOption().
m_colorScale
ccColorScale::Shared ccHistogramWindow::m_colorScale protected
Gradient color scale.
Definition at line 181 of file ecvHistogramWindow.h.
Referenced by refresh(), and setColorScale().
m_colorScheme
HISTOGRAM_COLOR_SCHEME ccHistogramWindow::m_colorScheme protected
Color scheme.
Definition at line 177 of file ecvHistogramWindow.h.
Referenced by refresh(), refreshBars(), and setColorScheme().
m_curveValues
std::vector<double> ccHistogramWindow::m_curveValues protected
Definition at line 201 of file ecvHistogramWindow.h.
Referenced by refresh(), and setCurveValues().
m_drawVerticalIndicator
bool ccHistogramWindow::m_drawVerticalIndicator protected
Definition at line 205 of file ecvHistogramWindow.h.
Referenced by mouseMoveEvent(), and refresh().
m_histogram
QCPColoredBars* ccHistogramWindow::m_histogram protected
Definition at line 193 of file ecvHistogramWindow.h.
Referenced by mouseMoveEvent(), refresh(), and refreshBars().
m_histoValues
std::vector<unsigned> ccHistogramWindow::m_histoValues protected
Definition at line 194 of file ecvHistogramWindow.h.
Referenced by computeBinArrayFromSF(), fromBinArray(), getMaxHistoVal(), histoValues(), mouseMoveEvent(), refresh(), refreshBars(), setNumberOfClasses(), and wheelEvent().
m_lastMouseClick
QPoint ccHistogramWindow::m_lastMouseClick protected
Last mouse click.
Definition at line 245 of file ecvHistogramWindow.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_maxHistoVal
unsigned ccHistogramWindow::m_maxHistoVal protected
Definition at line 197 of file ecvHistogramWindow.h.
Referenced by fromBinArray(), getMaxHistoVal(), refresh(), and setNumberOfClasses().
m_maxVal
double ccHistogramWindow::m_maxVal protected
Definition at line 196 of file ecvHistogramWindow.h.
Referenced by computeBinArrayFromSF(), fromBinArray(), fromSF(), maxVal(), refresh(), and refreshBars().
m_minVal
double ccHistogramWindow::m_minVal protected
Definition at line 195 of file ecvHistogramWindow.h.
Referenced by computeBinArrayFromSF(), fromBinArray(), fromSF(), minVal(), refresh(), and refreshBars().
m_numberOfClassesCanBeChanged
bool ccHistogramWindow::m_numberOfClassesCanBeChanged protected
Only possible with an associated scalar field.
Definition at line 188 of file ecvHistogramWindow.h.
Referenced by fromBinArray(), fromSF(), and wheelEvent().
m_overlayCurve
QCPGraph* ccHistogramWindow::m_overlayCurve protected
Overlay curve.
Definition at line 200 of file ecvHistogramWindow.h.
Referenced by refresh(), and updateOverlayCurveWidth().
m_refreshAfterResize
bool ccHistogramWindow::m_refreshAfterResize protected
Definition at line 190 of file ecvHistogramWindow.h.
Referenced by resizeEvent(), and setRefreshAfterResize().
m_renderingFont
QFont ccHistogramWindow::m_renderingFont protected
Rendering font.
Definition at line 209 of file ecvHistogramWindow.h.
Referenced by ccHistogramWindow(), and refresh().
m_selectedItem
SELECTABLE_ITEMS ccHistogramWindow::m_selectedItem protected
Currently selected item.
Definition at line 228 of file ecvHistogramWindow.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_sfInteractionModes
SFInteractionModes ccHistogramWindow::m_sfInteractionModes protected
Which SF interaction modes are enabled.
Definition at line 215 of file ecvHistogramWindow.h.
Referenced by mouseMoveEvent(), mousePressEvent(), refresh(), and setSFInteractionMode().
m_solidColor
QColor ccHistogramWindow::m_solidColor protected
Solid color.
Definition at line 179 of file ecvHistogramWindow.h.
Referenced by refresh(), and setSolidColor().
m_titlePlot
QCPTextElement* ccHistogramWindow::m_titlePlot protected
Definition at line 174 of file ecvHistogramWindow.h.
Referenced by refresh().
m_titleStr
QString ccHistogramWindow::m_titleStr protected
Definition at line 173 of file ecvHistogramWindow.h.
Referenced by refresh(), and setTitle().
m_vertBar
QCPBarsWithText* ccHistogramWindow::m_vertBar protected
Definition at line 204 of file ecvHistogramWindow.h.
Referenced by refresh().
m_verticalIndicatorPositionPercent
double ccHistogramWindow::m_verticalIndicatorPositionPercent protected
Definition at line 206 of file ecvHistogramWindow.h.
Referenced by mouseMoveEvent(), and refresh().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvHistogramWindow.h
/root/ACloudViewer/app/ecvHistogramWindow.cpp