ACloudViewer: cloudViewer::core::kernel::CPUArgReductionEngine Class Reference
cloudViewer::core::kernel::CPUArgReductionEngine Class Reference
Public Member Functions
CPUArgReductionEngine (const CPUArgReductionEngine &)=delete
CPUArgReductionEngine & operator= (const CPUArgReductionEngine &)=delete
CPUArgReductionEngine (const Indexer &indexer)
template<typename func_t , typename scalar_t >
void Run (const func_t &reduce_func, scalar_t identity)
Static Public Member Functions
template<typename scalar_t , typename func_t >
static void LaunchArgReductionParallelDim (const Indexer &indexer, func_t reduce_func, scalar_t identity)
template<typename scalar_t , typename func_t >
static void LaunchArgReductionKernelTwoPass (const Indexer &indexer, func_t reduce_func, scalar_t identity)
Detailed Description
Definition at line 182 of file ReductionCPU.cpp.
Constructor & Destructor Documentation
CPUArgReductionEngine() [1/2]
cloudViewer::core::kernel::CPUArgReductionEngine::CPUArgReductionEngine (const CPUArgReductionEngine &) delete
CPUArgReductionEngine() [2/2]
cloudViewer::core::kernel::CPUArgReductionEngine::CPUArgReductionEngine (const Indexer & indexer) inline
Definition at line 186 of file ReductionCPU.cpp.
Member Function Documentation
LaunchArgReductionKernelTwoPass()
template<typename scalar_t , typename func_t > static void cloudViewer::core::kernel::CPUArgReductionEngine::LaunchArgReductionKernelTwoPass (const Indexer & indexer, func_t reduce_func, scalar_t identity) inline static
Create num_threads workers to compute partial arg reductions and then reduce to the final results. This only applies to arg reduction op with one output.
Definition at line 232 of file ReductionCPU.cpp.
References cloudViewer::utility::EstimateMaxThreads(), indexer, LogError, and min().
Referenced by Run().
LaunchArgReductionParallelDim()
template<typename scalar_t , typename func_t > static void cloudViewer::core::kernel::CPUArgReductionEngine::LaunchArgReductionParallelDim (const Indexer & indexer, func_t reduce_func, scalar_t identity) inline static
Definition at line 203 of file ReductionCPU.cpp.
References cloudViewer::core::Indexer::GetInputPtr(), cloudViewer::core::Indexer::GetOutputPtr(), indexer, and cloudViewer::core::Indexer::NumWorkloads().
Referenced by Run().
operator=()
CPUArgReductionEngine& cloudViewer::core::kernel::CPUArgReductionEngine::operator= (const CPUArgReductionEngine &) delete
Run()
template<typename func_t , typename scalar_t > void cloudViewer::core::kernel::CPUArgReductionEngine::Run (const func_t & reduce_func, scalar_t identity) inline
Definition at line 189 of file ReductionCPU.cpp.
References LaunchArgReductionKernelTwoPass(), LaunchArgReductionParallelDim(), and cloudViewer::core::Indexer::NumOutputElements().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/core/kernel/ReductionCPU.cpp