ACloudViewer: cloudViewer::visualization::webrtc_server::BitmapTrackSource Class Reference
cloudViewer::visualization::webrtc_server::BitmapTrackSource Class Reference abstract
#include <BitmapTrackSource.h>
Public Member Functions
BitmapTrackSource (bool remote)
void SetState (webrtc::MediaSourceInterface::SourceState new_state)
webrtc::MediaSourceInterface::SourceState state () const override
bool remote () const override
bool is_screencast () const override
absl::optional< bool > needs_denoising () const override
bool GetStats (Stats *stats) override
void AddOrUpdateSink (rtc::VideoSinkInterface< webrtc::VideoFrame > *sink, const rtc::VideoSinkWants &wants) override
void RemoveSink (rtc::VideoSinkInterface< webrtc::VideoFrame > *sink) override
bool SupportsEncodedOutput () const override
void GenerateKeyFrame () override
void AddEncodedSink (rtc::VideoSinkInterface< webrtc::RecordableEncodedFrame > *sink) override
void RemoveEncodedSink (rtc::VideoSinkInterface< webrtc::RecordableEncodedFrame > *sink) override
virtual void OnFrame (const std::shared_ptr< core::Tensor > &frame) override
Protected Member Functions
virtual rtc::VideoSourceInterface< webrtc::VideoFrame > * source ()=0
Detailed Description
Definition at line 61 of file BitmapTrackSource.h.
Constructor & Destructor Documentation
BitmapTrackSource()
cloudViewer::visualization::webrtc_server::BitmapTrackSource::BitmapTrackSource (bool remote) explicit
Definition at line 28 of file BitmapTrackSource.cpp.
Member Function Documentation
AddEncodedSink()
void cloudViewer::visualization::webrtc_server::BitmapTrackSource::AddEncodedSink (rtc::VideoSinkInterface< webrtc::RecordableEncodedFrame > * sink) inline override
Definition at line 79 of file BitmapTrackSource.h.
AddOrUpdateSink()
void cloudViewer::visualization::webrtc_server::BitmapTrackSource::AddOrUpdateSink (rtc::VideoSinkInterface< webrtc::VideoFrame > * sink, const rtc::VideoSinkWants & wants) override
Definition at line 41 of file BitmapTrackSource.cpp.
References source().
GenerateKeyFrame()
void cloudViewer::visualization::webrtc_server::BitmapTrackSource::GenerateKeyFrame () inline override
Definition at line 78 of file BitmapTrackSource.h.
GetStats()
bool cloudViewer::visualization::webrtc_server::BitmapTrackSource::GetStats (Stats * stats) inline override
Definition at line 73 of file BitmapTrackSource.h.
is_screencast()
bool cloudViewer::visualization::webrtc_server::BitmapTrackSource::is_screencast () const inline override
Definition at line 69 of file BitmapTrackSource.h.
needs_denoising()
absl::optional<bool> cloudViewer::visualization::webrtc_server::BitmapTrackSource::needs_denoising () const inline override
Definition at line 70 of file BitmapTrackSource.h.
References cloudViewer::utility::nullopt.
OnFrame()
virtual void cloudViewer::visualization::webrtc_server::BitmapTrackSource::OnFrame (const std::shared_ptr< core::Tensor > & frame) inline override virtual
Reimplemented in cloudViewer::visualization::webrtc_server::ImageTrackSource.
Definition at line 85 of file BitmapTrackSource.h.
References LogError.
remote()
bool cloudViewer::visualization::webrtc_server::BitmapTrackSource::remote () const inline override
Definition at line 68 of file BitmapTrackSource.h.
RemoveEncodedSink()
void cloudViewer::visualization::webrtc_server::BitmapTrackSource::RemoveEncodedSink (rtc::VideoSinkInterface< webrtc::RecordableEncodedFrame > * sink) inline override
Definition at line 81 of file BitmapTrackSource.h.
RemoveSink()
void cloudViewer::visualization::webrtc_server::BitmapTrackSource::RemoveSink (rtc::VideoSinkInterface< webrtc::VideoFrame > * sink) override
Definition at line 48 of file BitmapTrackSource.cpp.
References source().
SetState()
void cloudViewer::visualization::webrtc_server::BitmapTrackSource::SetState (webrtc::MediaSourceInterface::SourceState new_state)
Definition at line 33 of file BitmapTrackSource.cpp.
source()
virtual rtc::VideoSourceInterface<webrtc::VideoFrame>* cloudViewer::visualization::webrtc_server::BitmapTrackSource::source () protected pure virtual
Referenced by AddOrUpdateSink(), and RemoveSink().
state()
webrtc::MediaSourceInterface::SourceState cloudViewer::visualization::webrtc_server::BitmapTrackSource::state () const inline override
Definition at line 65 of file BitmapTrackSource.h.
SupportsEncodedOutput()
bool cloudViewer::visualization::webrtc_server::BitmapTrackSource::SupportsEncodedOutput () const inline override
Definition at line 77 of file BitmapTrackSource.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/webrtc_server/BitmapTrackSource.h
/root/ACloudViewer/libs/cloudViewer/visualization/webrtc_server/BitmapTrackSource.cpp