ACloudViewer: cloudViewer::t::pipelines::registration::TransformationEstimation Class Reference
cloudViewer::t::pipelines::registration::TransformationEstimation Class Reference abstract
#include <TransformationEstimation.h>
Public Member Functions
TransformationEstimation ()
Default Constructor.
virtual ~TransformationEstimation ()
virtual TransformationEstimationType GetTransformationEstimationType () const =0
virtual double ComputeRMSE (const geometry::PointCloud &source, const geometry::PointCloud &target, const core::Tensor &correspondences) const =0
virtual core::Tensor ComputeTransformation (const geometry::PointCloud &source, const geometry::PointCloud &target, const core::Tensor &correspondences, const core::Tensor &current_transform=core::Tensor::Eye(4, core::Float64, core::Device("CPU:0")), const std::size_t iteration=0) const =0
Detailed Description
Base class that estimates a transformation between two point clouds The virtual function ComputeTransformation() must be implemented in subclasses.
Definition at line 53 of file TransformationEstimation.h.
Constructor & Destructor Documentation
TransformationEstimation()
cloudViewer::t::pipelines::registration::TransformationEstimation::TransformationEstimation () inline
Default Constructor.
Definition at line 56 of file TransformationEstimation.h.
~TransformationEstimation()
virtual cloudViewer::t::pipelines::registration::TransformationEstimation::~TransformationEstimation () inline virtual
Definition at line 57 of file TransformationEstimation.h.
Member Function Documentation
ComputeRMSE()
virtual double cloudViewer::t::pipelines::registration::TransformationEstimation::ComputeRMSE (const geometry::PointCloud & source, const geometry::PointCloud & target, const core::Tensor & correspondences) const pure virtual
Compute RMSE between source and target points cloud given correspondences.
Parameters
source Source point cloud. (Float32 or Float64 type).
target Target point cloud. (Float32 or Float64 type).
correspondences Tensor of type Int64 containing indices of corresponding target points, where the value is the target index and the index of the value itself is the source index. It contains -1 as value at index with no correspondence.
Implemented in cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP, cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP, cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane, and cloudViewer::t::pipelines::registration::TransformationEstimationPointToPoint.
ComputeTransformation()
virtual core::Tensor cloudViewer::t::pipelines::registration::TransformationEstimation::ComputeTransformation (const geometry::PointCloud & source, const geometry::PointCloud & target, const core::Tensor & correspondences, const core::Tensor & current_transform = core::Tensor::Eye(4, core::Float64, core::Device("CPU:0")), const std::size_t iteration = 0) const pure virtual
Compute transformation from source to target point cloud given correspondences.
Parameters
source Source point cloud. (Float32 or Float64 type).
target Target point cloud. (Float32 or Float64 type).
correspondences tensor of type Int64 containing indices of corresponding target points, where the value is the target index and the index of the value itself is the source index. It contains -1 as value at index with no correspondence.
current_transform The current pose estimate of ICP.
iteration The current iteration number of the ICP algorithm.
Returns
transformation between source to target, a tensor of shape {4, 4}, type Float64 on CPU device.
Implemented in cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP, cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP, cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane, and cloudViewer::t::pipelines::registration::TransformationEstimationPointToPoint.
Referenced by cloudViewer::t::pipelines::registration::DoSingleScaleICPIterations().
GetTransformationEstimationType()
virtual TransformationEstimationType cloudViewer::t::pipelines::registration::TransformationEstimation::GetTransformationEstimationType () const pure virtual
Implemented in cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP, cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP, cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane, and cloudViewer::t::pipelines::registration::TransformationEstimationPointToPoint.
Referenced by cloudViewer::t::pipelines::registration::AssertInputMultiScaleICP(), and cloudViewer::t::pipelines::registration::InitializePointCloudPyramidForMultiScaleICP().
The documentation for this class was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/t/pipelines/registration/TransformationEstimation.h