ACloudViewer: colmap::CorrespondenceGraph Class Reference
colmap::CorrespondenceGraph Class Reference
#include <correspondence_graph.h>
Classes
struct Correspondence
Public Member Functions
CorrespondenceGraph ()
size_t NumImages () const
size_t NumImagePairs () const
bool ExistsImage (const image_t image_id) const
point2D_t NumObservationsForImage (const image_t image_id) const
point2D_t NumCorrespondencesForImage (const image_t image_id) const
point2D_t NumCorrespondencesBetweenImages (const image_t image_id1, const image_t image_id2) const
std::unordered_map< image_pair_t, point2D_t > NumCorrespondencesBetweenImages () const
void Finalize ()
void AddImage (const image_t image_id, const size_t num_points2D)
void AddCorrespondences (const image_t image_id1, const image_t image_id2, const FeatureMatches &matches)
const std::vector< Correspondence > & FindCorrespondences (const image_t image_id, const point2D_t point2D_idx) const
std::vector< Correspondence > FindTransitiveCorrespondences (const image_t image_id, const point2D_t point2D_idx, const size_t transitivity) const
FeatureMatches FindCorrespondencesBetweenImages (const image_t image_id1, const image_t image_id2) const
bool HasCorrespondences (const image_t image_id, const point2D_t point2D_idx) const
bool IsTwoViewObservation (const image_t image_id, const point2D_t point2D_idx) const
Detailed Description
Definition at line 20 of file correspondence_graph.h.
Constructor & Destructor Documentation
CorrespondenceGraph()
colmap::CorrespondenceGraph::CorrespondenceGraph ()
Definition at line 41 of file correspondence_graph.cc.
Member Function Documentation
AddCorrespondences()
void colmap::CorrespondenceGraph::AddCorrespondences (const image_t image_id1, const image_t image_id2, const FeatureMatches & matches)
Definition at line 77 of file correspondence_graph.cc.
References QtCompat::endl(), colmap::Database::ImagePairToPairId(), and colmap::StringPrintf().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::DatabaseCache::Load().
AddImage()
void colmap::CorrespondenceGraph::AddImage (const image_t image_id, const size_t num_points2D)
Definition at line 71 of file correspondence_graph.cc.
References ExistsImage().
Referenced by colmap::DatabaseCache::AddImage(), BOOST_AUTO_TEST_CASE(), GenerateReconstruction(), and colmap::DatabaseCache::Load().
ExistsImage()
bool colmap::CorrespondenceGraph::ExistsImage (const image_t image_id) const inline
Definition at line 144 of file correspondence_graph.h.
Referenced by AddImage(), and BOOST_AUTO_TEST_CASE().
Finalize()
void colmap::CorrespondenceGraph::Finalize ()
Definition at line 54 of file correspondence_graph.cc.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::DatabaseCache::Load().
FindCorrespondences()
const std::vector< CorrespondenceGraph::Correspondence > & colmap::CorrespondenceGraph::FindCorrespondences (const image_t image_id, const point2D_t point2D_idx) const inline
Definition at line 171 of file correspondence_graph.h.
Referenced by BOOST_AUTO_TEST_CASE(), and FindTransitiveCorrespondences().
FindCorrespondencesBetweenImages()
FeatureMatches colmap::CorrespondenceGraph::FindCorrespondencesBetweenImages (const image_t image_id1, const image_t image_id2) const
Definition at line 224 of file correspondence_graph.cc.
References NumCorrespondencesBetweenImages().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::IncrementalMapper::RegisterInitialImagePair(), and colmap::IncrementalTriangulator::Retriangulate().
FindTransitiveCorrespondences()
std::vector< CorrespondenceGraph::Correspondence > colmap::CorrespondenceGraph::FindTransitiveCorrespondences (const image_t image_id, const point2D_t point2D_idx, const size_t transitivity) const
Definition at line 164 of file correspondence_graph.cc.
References FindCorrespondences(), HasCorrespondences(), image, colmap::CorrespondenceGraph::Correspondence::image_id, and colmap::CorrespondenceGraph::Correspondence::point2D_idx.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::IncrementalMapper::RegisterNextImage().
HasCorrespondences()
bool colmap::CorrespondenceGraph::HasCorrespondences (const image_t image_id, const point2D_t point2D_idx) const inline
Definition at line 176 of file correspondence_graph.h.
Referenced by BOOST_AUTO_TEST_CASE(), and FindTransitiveCorrespondences().
IsTwoViewObservation()
bool colmap::CorrespondenceGraph::IsTwoViewObservation (const image_t image_id, const point2D_t point2D_idx) const
Definition at line 250 of file correspondence_graph.cc.
References image.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::IncrementalTriangulator::CompleteImage().
NumCorrespondencesBetweenImages() [1/2]
std::unordered_map< image_pair_t, point2D_t > colmap::CorrespondenceGraph::NumCorrespondencesBetweenImages () const
Definition at line 44 of file correspondence_graph.cc.
Referenced by FindCorrespondencesBetweenImages().
NumCorrespondencesBetweenImages() [2/2]
point2D_t colmap::CorrespondenceGraph::NumCorrespondencesBetweenImages (const image_t image_id1, const image_t image_id2) const inline
Definition at line 158 of file correspondence_graph.h.
References colmap::Database::ImagePairToPairId().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::Load().
NumCorrespondencesForImage()
point2D_t colmap::CorrespondenceGraph::NumCorrespondencesForImage (const image_t image_id) const inline
Definition at line 153 of file correspondence_graph.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::DatabaseCache::Load().
NumImagePairs()
size_t colmap::CorrespondenceGraph::NumImagePairs () const inline
Definition at line 140 of file correspondence_graph.h.
NumImages()
size_t colmap::CorrespondenceGraph::NumImages () const inline
Definition at line 138 of file correspondence_graph.h.
Referenced by BOOST_AUTO_TEST_CASE().
NumObservationsForImage()
point2D_t colmap::CorrespondenceGraph::NumObservationsForImage (const image_t image_id) const inline
Definition at line 148 of file correspondence_graph.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::DatabaseCache::Load().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/base/correspondence_graph.h
/root/ACloudViewer/libs/Reconstruction/src/base/correspondence_graph.cc