ACloudViewer: MatrixDisplayDlg Class Reference
MatrixDisplayDlg Class Reference
Simple widget to display a 4x4 matrix in various formats.
#include <matrixDisplayDlg.h>
Public Slots
void exportToASCII ()
Exports current matrix to an ASCII file.
void exportToClipboard ()
Exports current matrix to the clipboard.
Public Member Functions
MatrixDisplayDlg (QWidget *parent=0)
Default constructor.
void clear ()
Clears widget.
void fillDialogWith (const ccGLMatrix &mat)
Updates dialog with a given (float) matrix.
void fillDialogWith (const ccGLMatrixd &mat)
Updates dialog with a given (double) matrix.
Protected Member Functions
void fillDialogWith (const CCVector3d &axis, double angle_rad, const CCVector3d &T, int precision)
Fills the second part of the dialog.
Protected Attributes
ccGLMatrixd m_mat
Matrix.
Detailed Description
Simple widget to display a 4x4 matrix in various formats.
Definition at line 17 of file matrixDisplayDlg.h.
Constructor & Destructor Documentation
MatrixDisplayDlg()
MatrixDisplayDlg::MatrixDisplayDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 22 of file matrixDisplayDlg.cpp.
References exportToASCII(), and exportToClipboard().
Member Function Documentation
clear()
void MatrixDisplayDlg::clear ()
Clears widget.
Definition at line 94 of file matrixDisplayDlg.cpp.
References m_mat, and ccGLMatrixTpl< T >::toZero().
Referenced by ccPropertiesTreeDelegate::setEditorData().
exportToASCII
void MatrixDisplayDlg::exportToASCII () slot
Exports current matrix to an ASCII file.
Will display a file selection dialog!
Definition at line 102 of file matrixDisplayDlg.cpp.
References ecvPS::CurrentPath(), ecvFileUtils::defaultDocPath(), CVLog::Error(), ecvPS::LoadFile(), m_mat, CVLog::Print(), and ccGLMatrixTpl< T >::toAsciiFile().
Referenced by MatrixDisplayDlg().
exportToClipboard
void MatrixDisplayDlg::exportToClipboard () slot
Exports current matrix to the clipboard.
Definition at line 128 of file matrixDisplayDlg.cpp.
References m_mat, CVLog::Print(), and ccGLMatrixTpl< T >::toString().
Referenced by MatrixDisplayDlg().
fillDialogWith() [1/3]
void MatrixDisplayDlg::fillDialogWith (const ccGLMatrix & mat)
Updates dialog with a given (float) matrix.
Definition at line 34 of file matrixDisplayDlg.cpp.
References ccGLMatrixTpl< T >::data(), ecvGui::ParamStruct::displayedNumPrecision, Vector3Tpl< double >::fromArray(), ccGLMatrixTpl< T >::getParameters(), m_mat, ecvGui::Parameters(), ccGLMatrixTpl< T >::toString(), and Tuple3Tpl< Type >::u.
Referenced by fillDialogWith(), and ccPropertiesTreeDelegate::setEditorData().
fillDialogWith() [2/3]
void MatrixDisplayDlg::fillDialogWith (const ccGLMatrixd & mat)
Updates dialog with a given (double) matrix.
Definition at line 53 of file matrixDisplayDlg.cpp.
References ecvGui::ParamStruct::displayedNumPrecision, fillDialogWith(), ccGLMatrixTpl< T >::getParameters(), m_mat, ecvGui::Parameters(), and ccGLMatrixTpl< T >::toString().
fillDialogWith() [3/3]
void MatrixDisplayDlg::fillDialogWith (const CCVector3d & axis, double angle_rad, const CCVector3d & T, int precision) protected
Fills the second part of the dialog.
Definition at line 71 of file matrixDisplayDlg.cpp.
References cloudViewer::RadiansToDegrees(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Member Data Documentation
m_mat
ccGLMatrixd MatrixDisplayDlg::m_mat protected
Matrix.
Definition at line 49 of file matrixDisplayDlg.h.
Referenced by clear(), exportToASCII(), exportToClipboard(), and fillDialogWith().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/db_tree/matrixDisplayDlg.h
/root/ACloudViewer/app/db_tree/matrixDisplayDlg.cpp