ACloudViewer: CVTools Class Reference
CVTools Class Reference
#include <CVTools.h>
Static Public Member Functions
static std::string GetFileName (const std::string file_name)
static void TimeStart ()
static QString TimeOff ()
static QString ToNativeSeparators (const QString &path)
static QString ToQString (const std::string &s)
static std::string FromQString (const QString &qs)
static std::string JoinStrVec (const std::vector< std::string > &v, std::string splitor=" ")
static std::string FromUnicode (const QString &qstr)
static QString ToUnicode (const std::string &cstr)
static std::string ExtractDigitAlpha (const std::string &str)
static int TranslateKeyCode (int key)
static bool FileMappingReader (const std::string &filename, void *data, unsigned long &size)
static bool FileMappingWriter (const std::string &filename, const void *data, unsigned long size)
static bool QMappingReader (const std::string &filename, std::vector< size_t > &indices)
static bool QMappingWriter (const std::string &filename, const void *data, std::size_t length)
static std::wstring Char2Wchar (const char *szStr)
static std::string Wchar2Char (const wchar_t *szStr)
Detailed Description
Definition at line 20 of file CVTools.h.
Member Function Documentation
Char2Wchar()
std::wstring CVTools::Char2Wchar (const char * szStr) static
Definition at line 169 of file CVTools.cpp.
ExtractDigitAlpha()
std::string CVTools::ExtractDigitAlpha (const std::string & str) static
Definition at line 80 of file CVTools.cpp.
References e, result, and x.
Referenced by cc2smReader::ConVertToPCLMaterial(), and pcl2cc::FromPCLMaterial().
FileMappingReader()
bool CVTools::FileMappingReader (const std::string & filename, void * data, unsigned long & size) static
Definition at line 181 of file CVTools.cpp.
References data, CVLog::Error(), filename, colmap::GetFileSize(), NULL, size, and CVLog::Warning().
FileMappingWriter()
bool CVTools::FileMappingWriter (const std::string & filename, const void * data, unsigned long size) static
Definition at line 234 of file CVTools.cpp.
References data, CVLog::Error(), filename, NULL, size, and CVLog::Warning().
FromQString()
std::string CVTools::FromQString (const QString & qs) static
Definition at line 100 of file CVTools.cpp.
References FromUnicode().
Referenced by PclTransformTool::addActors(), PclUtils::PCLVis::addScalarBar(), PclUtils::renders::MultiTextureRenderer::Apply(), cloudViewer::io::AutoWriteEntity(), PCLDisplayTools::changeEntityProperties(), cc2smReader::ConVertToPCLMaterial(), PclUtils::PCLVis::displayText(), PCLDisplayTools::displayText(), PclUtils::PCLVis::draw(), PCLDisplayTools::drawBBox(), PCLDisplayTools::drawOrientedBBox(), PCLDisplayTools::drawWidgets(), PCLDisplayTools::getDataAxesGridProperties(), ecvFilterByLabelDlg::getSelectedFilterClasses(), PclUtils::PCLVis::getTransformation(), PclUtils::renders::MaterialConverter::HasPBREncoding(), PCLDisplayTools::hideShowEntities(), ecvAnnotationsTool::importClassesFromFile(), cloudViewer::ReconstructionWidget::iniEnvironment(), PythonInterpreter::initialize(), PcdFilter::loadFile(), PclUtils::renders::TextureLoader::LoadFromCCMaterial(), main(), qAnimationDlg::preview(), PclUtils::PCLVis::removeEntities(), PCLDisplayTools::removeEntities(), qAnimationDlg::render(), PcdFilter::saveToFile(), PCLDisplayTools::setDataAxesGridProperties(), PclAnnotationTool::setInputCloud(), qAnimationDlg::textureAnimationPreview(), qAnimationDlg::textureAnimationRender(), PclUtils::PCLVis::transformEntities(), PCLDisplayTools::updateMeshTextures(), PclUtils::PCLVis::updateNormals(), PclUtils::PCLVis::updateScalarBar(), PclTools::UpdateScalarBar(), PclUtils::PCLVis::updateShadingMode(), and PclUtils::PCLVis::updateTexture().
FromUnicode()
std::string CVTools::FromUnicode (const QString & qstr) static
Definition at line 56 of file CVTools.cpp.
References QtCompatTextCodec::fromUnicode(), CVLog::PrintDebug(), and qtCompatCodecForLocale().
Referenced by FromQString().
GetFileName()
std::string CVTools::GetFileName (const std::string file_name) static
Definition at line 29 of file CVTools.cpp.
JoinStrVec()
std::string CVTools::JoinStrVec (const std::vector< std::string > & v, std::string splitor = " ") static
Definition at line 108 of file CVTools.cpp.
QMappingReader()
bool CVTools::QMappingReader (const std::string & filename, std::vector< size_t > & indices) static
Definition at line 280 of file CVTools.cpp.
References CVLog::Error(), filename, and size.
Referenced by Annotaions::loadAnnotations().
QMappingWriter()
bool CVTools::QMappingWriter (const std::string & filename, const void * data, std::size_t length) static
Definition at line 331 of file CVTools.cpp.
References data, CVLog::Error(), and filename.
Referenced by Annotaions::saveAnnotations().
TimeOff()
QString CVTools::TimeOff () static
Definition at line 39 of file CVTools.cpp.
Referenced by Annotaions::loadAnnotations(), and Annotaions::saveAnnotations().
TimeStart()
void CVTools::TimeStart () static
Definition at line 37 of file CVTools.cpp.
Referenced by Annotaions::loadAnnotations(), and Annotaions::saveAnnotations().
ToNativeSeparators()
QString CVTools::ToNativeSeparators (const QString & path) static
Definition at line 45 of file CVTools.cpp.
References cloudViewer::t::geometry::path.
Referenced by IoUtils::createMaterialSetForMesh(), pcl2cc::FromPCLMaterial(), ccMaterial::loadAndSetTexture(), ccMaterial::loadAndSetTextureMap(), and ccMaterial::setTexture().
ToQString()
QString CVTools::ToQString (const std::string & s) static
Definition at line 92 of file CVTools.cpp.
References ToUnicode().
Referenced by cloudViewer::io::AutoReadEntity(), cloudViewer::io::AutoWriteEntity(), PclAnnotationTool::exportAnnotations(), pcl2cc::FromPCLMaterial(), cloudViewer::ProjectWidget::persistSave(), PclAnnotationTool::setInputCloud(), and ecvAnnotationsTool::updateLabelsCombox().
ToUnicode()
QString CVTools::ToUnicode (const std::string & cstr) static
Definition at line 68 of file CVTools.cpp.
References CVLog::PrintDebug(), qtCompatCodecForLocale(), and QtCompatTextCodec::toUnicode().
Referenced by ToQString().
TranslateKeyCode()
int CVTools::TranslateKeyCode (int key) static
Definition at line 119 of file CVTools.cpp.
Wchar2Char()
std::string CVTools::Wchar2Char (const wchar_t * szStr) static
Definition at line 175 of file CVTools.cpp.
The documentation for this class was generated from the following files:
/root/ACloudViewer/core/include/CVTools.h
/root/ACloudViewer/core/src/CVTools.cpp