ACloudViewer: Widgets::ColorPushButton Class Reference
Widgets::ColorPushButton Class Reference
ColorPushButton, 是对QtColorPicker的扩展.
#include <colorpushbutton.h>
Signals
void colorChanged ()
Signals inherited from Widgets::QtColorPicker
void colorChanged (const QColor &)
Public Member Functions
ColorPushButton (QWidget *parent=0)
构造拾色器按钮类, 初始化拾色器按钮.
~ColorPushButton ()
void setColor (const QColor &c)
QColor color ()
Public Member Functions inherited from Widgets::QtColorPicker
QtColorPicker (QWidget *parent=0, int columns=-1, bool enableColorDialog=true)
~QtColorPicker ()
void insertColor (const QColor &color, const QString &text=QString(), int index=-1)
QColor currentColor () const
QColor color (int index) const
void setColorDialogEnabled (bool enabled)
bool colorDialogEnabled () const
void setStandardColors ()
Additional Inherited Members
Public Slots inherited from Widgets::QtColorPicker
void setCurrentColor (const QColor &col)
Static Public Member Functions inherited from Widgets::QtColorPicker
static QColor GetColor (const QPoint &pos, bool allowCustomColors=true)
Protected Member Functions inherited from Widgets::QtColorPicker
void paintEvent (QPaintEvent *e)
Properties inherited from Widgets::QtColorPicker
bool colorDialog
Whether the ellipsis "..." (more) button is available.
Detailed Description
ColorPushButton, 是对QtColorPicker的扩展.
Definition at line 15 of file colorpushbutton.h.
Constructor & Destructor Documentation
ColorPushButton()
Widgets::ColorPushButton::ColorPushButton (QWidget * parent = 0)
构造拾色器按钮类, 初始化拾色器按钮.
Parameters
parent,父窗口
Definition at line 26 of file colorpushbutton.cpp.
References colorChanged(), Widgets::ColorComboBox::colorList(), Widgets::ColorComboBox::colorNames(), colors, Widgets::ColorComboBox::defaultColorNames(), Widgets::ColorComboBox::defaultColors(), Widgets::QtColorPicker::insertColor(), and Widgets::ColorComboBox::numPredefinedColors().
~ColorPushButton()
Widgets::ColorPushButton::~ColorPushButton ()
Definition at line 43 of file colorpushbutton.cpp.
Member Function Documentation
color()
QColor Widgets::ColorPushButton::color () inline
Definition at line 22 of file colorpushbutton.h.
colorChanged
void Widgets::ColorPushButton::colorChanged () signal
Referenced by ColorPushButton().
setColor()
void Widgets::ColorPushButton::setColor (const QColor & c) inline
Definition at line 21 of file colorpushbutton.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/PCLEngine/VtkUtils/colorpushbutton.h
/root/ACloudViewer/libs/PCLEngine/VtkUtils/colorpushbutton.cpp