ACloudViewer: ccOrthoSectionGenerationDlg Class Reference
ccOrthoSectionGenerationDlg Class Reference
#include <ecvOrthoSectionGenerationDlg.h>
Public Member Functions
ccOrthoSectionGenerationDlg (QWidget *parent=0)
Default constructor.
void setPathLength (double l)
Sets the path legnth.
void setAutoSaveAndRemove (bool state)
Sets whether the generatrix should be automatically saved and removed.
bool autoSaveAndRemove () const
Returns whether the generatrix should be automatically saved and removed.
void setGenerationStep (double s)
Sets the generation step.
void setSectionsWidth (double w)
Sets he sections width.
double getGenerationStep () const
Returns the generation step.
double getSectionsWidth () const
Returns the sections width.
Protected Slots
void onStepChanged (double)
Protected Attributes
double m_pathLength
Path length.
Detailed Description
Dialog for generating orthogonal sections along a path (Section Extraction Tool)
Definition at line 17 of file ecvOrthoSectionGenerationDlg.h.
Constructor & Destructor Documentation
ccOrthoSectionGenerationDlg()
ccOrthoSectionGenerationDlg::ccOrthoSectionGenerationDlg (QWidget * parent = 0) explicit
Default constructor.
Definition at line 13 of file ecvOrthoSectionGenerationDlg.cpp.
References onStepChanged().
Member Function Documentation
autoSaveAndRemove()
bool ccOrthoSectionGenerationDlg::autoSaveAndRemove () const
Returns whether the generatrix should be automatically saved and removed.
Definition at line 36 of file ecvOrthoSectionGenerationDlg.cpp.
getGenerationStep()
double ccOrthoSectionGenerationDlg::getGenerationStep () const
Returns the generation step.
Definition at line 48 of file ecvOrthoSectionGenerationDlg.cpp.
getSectionsWidth()
double ccOrthoSectionGenerationDlg::getSectionsWidth () const
Returns the sections width.
Definition at line 52 of file ecvOrthoSectionGenerationDlg.cpp.
onStepChanged
void ccOrthoSectionGenerationDlg::onStepChanged (double step) protected slot
Definition at line 56 of file ecvOrthoSectionGenerationDlg.cpp.
References count, cloudViewer::utility::floor(), and m_pathLength.
Referenced by ccOrthoSectionGenerationDlg().
setAutoSaveAndRemove()
void ccOrthoSectionGenerationDlg::setAutoSaveAndRemove (bool state)
Sets whether the generatrix should be automatically saved and removed.
Definition at line 32 of file ecvOrthoSectionGenerationDlg.cpp.
setGenerationStep()
void ccOrthoSectionGenerationDlg::setGenerationStep (double s)
Sets the generation step.
Definition at line 40 of file ecvOrthoSectionGenerationDlg.cpp.
setPathLength()
void ccOrthoSectionGenerationDlg::setPathLength (double l)
Sets the path legnth.
Definition at line 25 of file ecvOrthoSectionGenerationDlg.cpp.
References m_pathLength.
setSectionsWidth()
void ccOrthoSectionGenerationDlg::setSectionsWidth (double w)
Sets he sections width.
Definition at line 44 of file ecvOrthoSectionGenerationDlg.cpp.
Member Data Documentation
m_pathLength
double ccOrthoSectionGenerationDlg::m_pathLength protected
Path length.
Definition at line 48 of file ecvOrthoSectionGenerationDlg.h.
Referenced by onStepChanged(), and setPathLength().
The documentation for this class was generated from the following files:
/root/ACloudViewer/app/ecvOrthoSectionGenerationDlg.h
/root/ACloudViewer/app/ecvOrthoSectionGenerationDlg.cpp