ACloudViewer: cloudViewer::visualization::rendering::EngineInstance Class Reference
cloudViewer::visualization::rendering::EngineInstance Class Reference
#include <FilamentEngine.h>
Public Types
enum class RenderingType { kDefault , kOpenGL , kVulkan , kMetal }
Public Member Functions
~EngineInstance ()
Static Public Member Functions
static void SelectBackend (RenderingType type)
static void EnableHeadless ()
static void SetResourcePath (const std::string &resource_path)
static const std::string & GetResourcePath ()
static filament::Engine & GetInstance ()
static FilamentResourceManager & GetResourceManager ()
static void DestroyInstance ()
Detailed Description
Definition at line 22 of file FilamentEngine.h.
Member Enumeration Documentation
RenderingType
enum cloudViewer::visualization::rendering::EngineInstance::RenderingType strong
Enumerator
kDefault
kOpenGL
kVulkan
kMetal
Definition at line 24 of file FilamentEngine.h.
Constructor & Destructor Documentation
~EngineInstance()
cloudViewer::visualization::rendering::EngineInstance::~EngineInstance ()
Definition at line 60 of file FilamentEngine.cpp.
References cloudViewer::visualization::rendering::FilamentResourceManager::DestroyAll().
Member Function Documentation
DestroyInstance()
void cloudViewer::visualization::rendering::EngineInstance::DestroyInstance () static
Destroys the singleton instance, to force Filament cleanup at a specific time. Calling GetInstance() after this will re-create the instance.
Definition at line 76 of file FilamentEngine.cpp.
Referenced by cloudViewer::visualization::gui::Application::Impl::CleanupAfterRunning().
EnableHeadless()
void cloudViewer::visualization::rendering::EngineInstance::EnableHeadless () static
Initialize Engine for headless rendering. Must be called before first access to the Engine (GetInstance).
Definition at line 42 of file FilamentEngine.cpp.
Referenced by cloudViewer::visualization::gui::BitmapWindowSystem::BitmapWindowSystem().
GetInstance()
filament::Engine & cloudViewer::visualization::rendering::EngineInstance::GetInstance () static
Definition at line 54 of file FilamentEngine.cpp.
Referenced by cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::LineSetBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TMeshBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TGaussianSplatBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TLineSetBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::gui::ImguiFilamentBridge::CreateAtlasTextureAlpha8(), cloudViewer::visualization::gui::BitmapWindowSystem::CreateRenderer(), cloudViewer::visualization::gui::GLFWWindowSystem::CreateRenderer(), cloudViewer::visualization::gui::ImguiFilamentBridge::ImguiFilamentBridge(), cloudViewer::visualization::gui::ImguiFilamentBridge::Update(), and cloudViewer::visualization::gui::ImguiFilamentBridge::~ImguiFilamentBridge().
GetResourceManager()
FilamentResourceManager & cloudViewer::visualization::rendering::EngineInstance::GetResourceManager () static
Definition at line 56 of file FilamentEngine.cpp.
Referenced by cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::LineSetBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TMeshBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TGaussianSplatBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::rendering::TLineSetBuffersBuilder::ConstructBuffers(), cloudViewer::visualization::gui::BitmapWindowSystem::CreateRenderer(), cloudViewer::visualization::gui::GLFWWindowSystem::CreateRenderer(), cloudViewer::visualization::rendering::FilamentMaterialModifier::SetTexture(), cloudViewer::visualization::gui::UIImage::UIImage(), and cloudViewer::visualization::gui::ImguiFilamentBridge::Update().
GetResourcePath()
const std::string & cloudViewer::visualization::rendering::EngineInstance::GetResourcePath () static
Definition at line 52 of file FilamentEngine.cpp.
Referenced by cloudViewer::visualization::gui::Application::GetResourcePath(), and cloudViewer::visualization::gui::Application::RunOneTick().
SelectBackend()
void cloudViewer::visualization::rendering::EngineInstance::SelectBackend (RenderingType type) static
Definition at line 40 of file FilamentEngine.cpp.
References type.
Referenced by cloudViewer::visualization::gui::Application::Impl::PrepareForRunning().
SetResourcePath()
void cloudViewer::visualization::rendering::EngineInstance::SetResourcePath (const std::string & resource_path) static
Definition at line 44 of file FilamentEngine.cpp.
References cloudViewer::utility::filesystem::DirectoryExists(), and LogError.
Referenced by cloudViewer::visualization::gui::Application::Initialize().
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentEngine.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/filament/FilamentEngine.cpp