ACloudViewer: colmap::EssentialMatrixFivePointEstimator Class Reference
colmap::EssentialMatrixFivePointEstimator Class Reference
#include <essential_matrix.h>
Public Types
typedef Eigen::Vector2d X_t
typedef Eigen::Vector2d Y_t
typedef Eigen::Matrix3d M_t
Static Public Member Functions
static std::vector< M_t > Estimate (const std::vector< X_t > &points1, const std::vector< Y_t > &points2)
static void Residuals (const std::vector< X_t > &points1, const std::vector< Y_t > &points2, const M_t &E, std::vector< double > *residuals)
Static Public Attributes
static const int kMinNumSamples = 5
Detailed Description
Definition at line 27 of file essential_matrix.h.
Member Typedef Documentation
M_t
typedef Eigen::Matrix3d colmap::EssentialMatrixFivePointEstimator::M_t
Definition at line 31 of file essential_matrix.h.
X_t
typedef Eigen::Vector2d colmap::EssentialMatrixFivePointEstimator::X_t
Definition at line 29 of file essential_matrix.h.
Y_t
typedef Eigen::Vector2d colmap::EssentialMatrixFivePointEstimator::Y_t
Definition at line 30 of file essential_matrix.h.
Member Function Documentation
Estimate()
std::vector< EssentialMatrixFivePointEstimator::M_t > colmap::EssentialMatrixFivePointEstimator::Estimate (const std::vector< X_t > & points1, const std::vector< Y_t > & points2) static
Definition at line 48 of file essential_matrix.cc.
References coeffs(), e, colmap::FindPolynomialRootsCompanionMatrix(), and X.
Residuals()
void colmap::EssentialMatrixFivePointEstimator::Residuals (const std::vector< X_t > & points1, const std::vector< Y_t > & points2, const M_t & E, std::vector< double > * residuals) static
Definition at line 153 of file essential_matrix.cc.
References colmap::ComputeSquaredSampsonError().
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
kMinNumSamples
const int colmap::EssentialMatrixFivePointEstimator::kMinNumSamples = 5 static
Definition at line 34 of file essential_matrix.h.
The documentation for this class was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/estimators/essential_matrix.h
/root/ACloudViewer/libs/Reconstruction/src/estimators/essential_matrix.cc