ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/CloudSamplingTools.cpp File Reference
CloudSamplingTools.cpp File Reference
#include <pybind11/pybind11.h>
#include <CloudSamplingTools.h>
#include <BoundingBox.h>
#include <CVPointCloud.h>
#include <GenericProgressCallback.h>
#include <GeometricalAnalysisTools.h>
#include <ReferenceCloud.h>
Functions
void define_CloudSamplingTools (py::module &cccorelib)
Function Documentation
define_CloudSamplingTools()
void define_CloudSamplingTools (py::module & cccorelib)
Definition at line 21 of file CloudSamplingTools.cpp.
References cloudViewer::CloudSamplingTools::SFModulationParams::a, cloudViewer::CloudSamplingTools::SFModulationParams::b, cloudViewer::CloudSamplingTools::SFModulationParams::enabled, cloudViewer::CloudSamplingTools::noiseFilter(), cloudViewer::CloudSamplingTools::resampleCloudSpatially(), cloudViewer::CloudSamplingTools::resampleCloudWithOctree(), cloudViewer::CloudSamplingTools::resampleCloudWithOctreeAtLevel(), cloudViewer::CloudSamplingTools::sorFilter(), cloudViewer::CloudSamplingTools::subsampleCloudRandomly(), cloudViewer::CloudSamplingTools::subsampleCloudWithOctree(), and cloudViewer::CloudSamplingTools::subsampleCloudWithOctreeAtLevel().
Referenced by define_cccorelib().