ACloudViewer: /root/ACloudViewer/libs/CVViewer/apps/CloudViewerApp/CloudViewerApp.h File Reference
CloudViewerApp.h File Reference
#include <memory>
Namespaces
cloudViewer
Generic file read and write utility for python interface.
cloudViewer::visualizer
Macros
#define WIDTH 1280
#define HEIGHT 960
Functions
int Run (int argc, const char *argv[])
Macro Definition Documentation
HEIGHT
#define HEIGHT 960
Definition at line 15 of file CloudViewerApp.h.
WIDTH
#define WIDTH 1280
Definition at line 14 of file CloudViewerApp.h.
Function Documentation
Run()
int Run (int argc, const char * argv[])
Referenced by BOOST_AUTO_TEST_CASE(), cloudViewer::ThreadControlWidget::StartFunction(), and colmap::ThreadControlWidget::StartFunction().