ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/CmdLineParser.cpp File Reference
CmdLineParser.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "CmdLineParser.h"
Functions
char * GetFileExtension (char *fileName)
char * GetLocalFileName (char *fileName)
void cmdLineParse (int argc, char **argv, int num, cmdLineReadable **readable, int dumpError)
char ** ReadWords (const char *fileName, int &cnt)
Function Documentation
cmdLineParse()
void cmdLineParse (int argc, char ** argv, int num, cmdLineReadable ** readable, int dumpError)
Definition at line 205 of file CmdLineParser.cpp.
References name, and cmdLineReadable::read().
Referenced by PoissonRecon(), and SurfaceTrimmer().
GetFileExtension()
char* GetFileExtension (char * fileName)
Definition at line 165 of file CmdLineParser.cpp.
References NULL.
GetLocalFileName()
char* GetLocalFileName (char * fileName)
Definition at line 185 of file CmdLineParser.cpp.
References name, and NULL.
ReadWords()
char** ReadWords (const char * fileName, int & cnt)
Definition at line 243 of file CmdLineParser.cpp.
References NULL.