ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/CmdLineParser.h File Reference
CmdLineParser.h File Reference
#include <stdarg.h>
#include <string.h>
#include "CmdLineParser.inl"
Classes
class cmdLineReadable
class cmdLineInt
class cmdLineIntArray< Dim >
class cmdLineFloat
class cmdLineFloatArray< Dim >
class cmdLineString
class cmdLineStrings
class cmdLineStringArray< Dim >
Functions
void cmdLineParse (int argc, char **argv, int num, cmdLineReadable **r, int dumpError=1)
char * GetFileExtension (char *fileName)
char * GetLocalFileName (char *fileName)
char ** ReadWords (const char *fileName, int &cnt)
Function Documentation
cmdLineParse()
void cmdLineParse (int argc, char ** argv, int num, cmdLineReadable ** r, int dumpError = 1)
Definition at line 205 of file CmdLineParser.cpp.
References name, and cmdLineReadable::read().
Referenced by PoissonRecon(), and SurfaceTrimmer().
GetFileExtension()
char* GetFileExtension (char * fileName)
Definition at line 165 of file CmdLineParser.cpp.
References NULL.
GetLocalFileName()
char* GetLocalFileName (char * fileName)
Definition at line 185 of file CmdLineParser.cpp.
References name, and NULL.
ReadWords()
char** ReadWords (const char * fileName, int & cnt)
Definition at line 243 of file CmdLineParser.cpp.
References NULL.