ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/coarsen.c File Reference
coarsen.c File Reference
#include "metis.h"
Functions
GraphType * Coarsen2Way (CtrlType *ctrl, GraphType *graph)
Function Documentation
Coarsen2Way()
GraphType* Coarsen2Way (CtrlType * ctrl, GraphType * graph)
Definition at line 19 of file coarsen.c.
References graphdef::adjwgt, COARSEN_FRACTION2, controldef::CoarsenTmr, controldef::CoarsenTo, graphdef::coarser, controldef::CType, DBG_COARSEN, DBG_TIME, controldef::dbglvl, graphdef::finer, graclus_errexit(), idxsum, IFSET, MATCH_HEM, Match_HEM, MATCH_HEMN, Match_HEMN(), MATCH_RM, Match_RM, Match_RM_NVW, MATCH_SHEM, Match_SHEM, MATCH_SHEMKWAY, MATCH_SHEMN, Match_SHEMN(), controldef::maxvwgt, graphdef::nedges, graphdef::nvtxs, starttimer, stoptimer, and graphdef::vwgt.