ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/exe/colmap.cc File Reference
colmap.cc File Reference
#include "exe/database.h"
#include "exe/feature.h"
#include "exe/gui.h"
#include "exe/image.h"
#include "exe/model.h"
#include "exe/mvs.h"
#include "exe/sfm.h"
#include "exe/vocab_tree.h"
#include "util/version.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 93 of file colmap.cc.
References QtCompat::endl(), colmap::InitializeGlog(), colmap::RunAutomaticReconstructor(), colmap::RunBundleAdjuster(), colmap::RunColorExtractor(), colmap::RunDatabaseCleaner(), colmap::RunDatabaseCreator(), colmap::RunDatabaseMerger(), colmap::RunDelaunayMesher(), colmap::RunExhaustiveMatcher(), colmap::RunFeatureExtractor(), colmap::RunFeatureImporter(), colmap::RunGraphicalUserInterface(), colmap::RunHierarchicalMapper(), colmap::RunImageDeleter(), colmap::RunImageFilterer(), colmap::RunImageRectifier(), colmap::RunImageRegistrator(), colmap::RunImageTexturer(), colmap::RunImageUndistorter(), colmap::RunImageUndistorterStandalone(), colmap::RunMapper(), colmap::RunMatchesImporter(), colmap::RunModelAligner(), colmap::RunModelAnalyzer(), colmap::RunModelComparer(), colmap::RunModelConverter(), colmap::RunModelCropper(), colmap::RunModelMerger(), colmap::RunModelOrientationAligner(), colmap::RunModelSplitter(), colmap::RunModelTransformer(), colmap::RunPatchMatchStereo(), colmap::RunPointFiltering(), colmap::RunPointTriangulator(), colmap::RunPoissonMesher(), colmap::RunProjectGenerator(), colmap::RunRigBundleAdjuster(), colmap::RunSequentialMatcher(), colmap::RunSpatialMatcher(), colmap::RunStereoFuser(), colmap::RunTransitiveMatcher(), colmap::RunVocabTreeBuilder(), colmap::RunVocabTreeMatcher(), colmap::RunVocabTreeRetriever(), and colmap::StringPrintf().