ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/ColorScheme.cpp File Reference
ColorScheme.cpp File Reference
#include "ColorScheme.h"
#include <utility>
Functions
static QTextCharFormat FormatHelper (const QColor &color, const QFont::Style style=QFont::Style::StyleNormal, const QFont::Weight weight=QFont::Weight::Normal)
static QTextCharFormat FormatHelper (const QColor &color, QFont::Weight weight)
Variables
static ColorScheme::Vector s_AvailableColorSchemes
Function Documentation
FormatHelper() [1/2]
static QTextCharFormat FormatHelper (const QColor & color, const QFont::Style style = QFont::Style::StyleNormal, const QFont::Weight weight = QFont::Weight::Normal) static
Definition at line 12 of file ColorScheme.cpp.
References color.
Referenced by ColorScheme::Default(), ColorScheme::Dracula(), and FormatHelper().
FormatHelper() [2/2]
static QTextCharFormat FormatHelper (const QColor & color, QFont::Weight weight) static
Definition at line 28 of file ColorScheme.cpp.
References color, and FormatHelper().
Variable Documentation
s_AvailableColorSchemes
ColorScheme::Vector s_AvailableColorSchemes static
Definition at line 111 of file ColorScheme.cpp.
Referenced by ColorScheme::AvailableColorSchemes(), and ColorScheme::ColorSchemeByName().