ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/optim/combination_sampler_test.cc File Reference
combination_sampler_test.cc File Reference
#include "util/testing.h"
#include <unordered_set>
#include "optim/combination_sampler.h"
#include "util/math.h"
Macros
#define TEST_NAME "optim/combination_sampler"
Functions
BOOST_AUTO_TEST_CASE (TestLessSamples)
BOOST_AUTO_TEST_CASE (TestEqualSamples)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "optim/combination_sampler"
Definition at line 32 of file combination_sampler_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (TestEqualSamples)
Definition at line 62 of file combination_sampler_test.cc.
References colmap::CombinationSampler::Initialize(), colmap::CombinationSampler::MaxNumSamples(), and colmap::CombinationSampler::Sample().
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (TestLessSamples)
Definition at line 42 of file combination_sampler_test.cc.
References count, colmap::CombinationSampler::Initialize(), colmap::CombinationSampler::MaxNumSamples(), and colmap::CombinationSampler::Sample().