ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/mvs/consistency_graph_test.cc File Reference
consistency_graph_test.cc File Reference
#include "util/testing.h"
#include "mvs/consistency_graph.h"
Macros
#define TEST_NAME "mvs/consistency_graph_test"
Functions
BOOST_AUTO_TEST_CASE (TestEmpty)
BOOST_AUTO_TEST_CASE (TestPartial)
BOOST_AUTO_TEST_CASE (TestZero)
BOOST_AUTO_TEST_CASE (TestFull)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "mvs/consistency_graph_test"
Definition at line 32 of file consistency_graph_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (TestEmpty)
Definition at line 40 of file consistency_graph_test.cc.
References data, colmap::mvs::ConsistencyGraph::GetImageIdxs(), and colmap::mvs::ConsistencyGraph::GetNumBytes().
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (TestFull)
Definition at line 85 of file consistency_graph_test.cc.
References data, colmap::mvs::ConsistencyGraph::GetImageIdxs(), and colmap::mvs::ConsistencyGraph::GetNumBytes().
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (TestPartial)
Definition at line 55 of file consistency_graph_test.cc.
References data, colmap::mvs::ConsistencyGraph::GetImageIdxs(), and colmap::mvs::ConsistencyGraph::GetNumBytes().
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (TestZero)
Definition at line 71 of file consistency_graph_test.cc.
References data, colmap::mvs::ConsistencyGraph::GetImageIdxs(), and colmap::mvs::ConsistencyGraph::GetNumBytes().