ACloudViewer: /root/ACloudViewer/libs/CVViewer/tools/ConvertPointCloud.cpp File Reference
ConvertPointCloud.cpp File Reference
#include <limits>
#include "CloudViewer.h"
Functions
void PrintHelp ()
void convert (int argc, char **argv, const std::string &file_in, const std::string &file_out)
int main (int argc, char **argv)
Function Documentation
convert()
void convert (int argc, char ** argv, const std::string & file_in, const std::string & file_out)
Definition at line 49 of file ConvertPointCloud.cpp.
References ccPointCloud::ComputeMahalanobisDistance(), cloudViewer::io::CreatePointCloudFromFile(), ccPointCloud::Crop(), ccPointCloud::EstimateNormals(), cloudViewer::utility::GetProgramOptionAsDouble(), cloudViewer::utility::GetProgramOptionAsEigenVectorXd(), cloudViewer::utility::GetProgramOptionAsInt(), ccPointCloud::hasNormals(), LogDebug, LogError, LogInfo, max(), ccPointCloud::OrientNormalsToAlignWithDirection(), ccPointCloud::OrientNormalsTowardsCameraLocation(), pointcloud_ptr, cloudViewer::utility::ProgramOptionExistsAny(), ccPointCloud::SelectByIndex(), cloudViewer::PointCloudTpl< T >::size(), ccPointCloud::UniformDownSample(), ccPointCloud::VoxelDownSample(), and cloudViewer::io::WritePointCloud().
Referenced by pybind11::detail::cloudViewer_optional_caster< T >::load(), pybind11::detail::type_caster< cloudViewer::core::Tensor >::load(), main(), and CommandTreeIso::process().
main()
int main (int argc, char ** argv)
Definition at line 174 of file ConvertPointCloud.cpp.
References convert(), cloudViewer::utility::filesystem::DirectoryExists(), cloudViewer::utility::filesystem::FileExists(), cloudViewer::utility::filesystem::GetFileNameWithoutDirectory(), cloudViewer::utility::GetProgramOptionAsInt(), cloudViewer::utility::filesystem::GetRegularizedDirectoryName(), cloudViewer::utility::filesystem::ListFilesInDirectory(), LogWarning, cloudViewer::utility::filesystem::MakeDirectoryHierarchy(), PrintHelp(), cloudViewer::utility::ProgramOptionExists(), and cloudViewer::utility::SetVerbosityLevel().
PrintHelp()
void PrintHelp ()
Definition at line 12 of file ConvertPointCloud.cpp.
References LogInfo.
Referenced by main().