ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/estimators/coordinate_frame_test.cc File Reference
coordinate_frame_test.cc File Reference
#include "util/testing.h"
#include "estimators/coordinate_frame.h"
#include "base/gps.h"
Macros
#define TEST_NAME "estimators/coordinate_frame"
Functions
BOOST_AUTO_TEST_CASE (TestEstimateGravityVectorFromImageOrientation)
BOOST_AUTO_TEST_CASE (TestEstimateManhattanWorldFrame)
BOOST_AUTO_TEST_CASE (TestAlignToPrincipalPlane)
BOOST_AUTO_TEST_CASE (TestAlignToENUPlane)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "estimators/coordinate_frame"
Definition at line 32 of file coordinate_frame_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (TestAlignToENUPlane)
Definition at line 115 of file coordinate_frame_test.cc.
References colmap::Reconstruction::AddPoint3D(), colmap::AlignToENUPlane(), e, colmap::GPSTransform::EllToXYZ(), QtCompat::endl(), colmap::Reconstruction::Point3D(), points, and colmap::Point3D::XYZ().
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (TestAlignToPrincipalPlane)
Definition at line 55 of file coordinate_frame_test.cc.
References colmap::Reconstruction::AddImage(), colmap::Reconstruction::AddPoint3D(), colmap::AlignToPrincipalPlane(), e, QtCompat::endl(), image, colmap::Reconstruction::Image(), colmap::SimilarityTransform3::Matrix(), colmap::Reconstruction::Point3D(), colmap::Image::ProjectionCenter(), colmap::SimilarityTransform3::Rotation(), and colmap::Point3D::XYZ().
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (TestEstimateGravityVectorFromImageOrientation)
Definition at line 40 of file coordinate_frame_test.cc.
References colmap::EstimateGravityVectorFromImageOrientation().
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (TestEstimateManhattanWorldFrame)
Definition at line 46 of file coordinate_frame_test.cc.
References colmap::EstimateManhattanWorldFrame().