ACloudViewer: /root/ACloudViewer/libs/PCLEngine/Utils/copy.h File Reference
copy.h File Reference
#include <Utils/PCLCloud.h>
#include "qPCL.h"
#include <pcl/PointIndices.h>
Functions
void QPCL_ENGINE_LIB_API copyScalarFields (const ccPointCloud *inCloud, ccPointCloud *outCloud, pcl::PointIndicesPtr &in2outMapping, bool overwrite=true)
Makes a copy of all scalar fields from one cloud to another.
void QPCL_ENGINE_LIB_API copyRGBColors (const ccPointCloud *inCloud, ccPointCloud *outCloud, pcl::PointIndicesPtr &in2outMapping, bool overwrite=true)
Makes a copy of RGB colors from one cloud to another.
Function Documentation
copyRGBColors()
void QPCL_ENGINE_LIB_API copyRGBColors (const ccPointCloud * inCloud, ccPointCloud * outCloud, pcl::PointIndicesPtr & in2outMapping, bool overwrite = true)
Makes a copy of RGB colors from one cloud to another.
Definition at line 72 of file copy.cpp.
References ccPointCloud::addRGBColor(), ccDrawableObject::colorsShown(), ccPointCloud::getPointColor(), ccPointCloud::hasColors(), ccPointCloud::reserveTheRGBTable(), ccDrawableObject::showColors(), and cloudViewer::PointCloudTpl< T >::size().
Referenced by MLSSmoothingUpsampling::compute().
copyScalarFields()
void QPCL_ENGINE_LIB_API copyScalarFields (const ccPointCloud * inCloud, ccPointCloud * outCloud, pcl::PointIndicesPtr & in2outMapping, bool overwrite = true)
Makes a copy of all scalar fields from one cloud to another.
This algorithm simply copy the scalar fields from a cloud to another using the the mapping contained in a pcl::PointIndicesPtr.
Parameters
inCloud the input cloud from which to copy scalars
outCloud the output cloud in which to copy the scalar fields
in2outMapping indices of the input cloud for each point in the output
overwrite you can chose to not overwrite existing fields
Definition at line 14 of file copy.cpp.
References ccPointCloud::addScalarField(), ccScalarField::computeMinAndMax(), cloudViewer::ScalarField::getName(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::ScalarField::getValue(), name, CCShareable::release(), cloudViewer::ScalarField::resizeSafe(), cloudViewer::ScalarField::setValue(), ccDrawableObject::sfShown(), ccDrawableObject::showSF(), and cloudViewer::PointCloudTpl< T >::size().
Referenced by MLSSmoothingUpsampling::compute().