ACloudViewer: /root/ACloudViewer/core/src/WeibullDistribution.cpp File Reference
WeibullDistribution.cpp File Reference
#include <WeibullDistribution.h>
#include <CVMath.h>
#include <GenericCloud.h>
#include <ScalarField.h>
#include <ScalarFieldTools.h>
Functions
static double Gamma_cc (double x)
Function Documentation
Gamma_cc()
static double Gamma_cc (double x) static
Definition at line 24 of file WeibullDistribution.cpp.
References abs(), M_PI, and max().
Referenced by cloudViewer::WeibullDistribution::computeSkewness(), and cloudViewer::WeibullDistribution::setParameters().