ACloudViewer: /root/ACloudViewer/core/src/GeometricalAnalysisTools.cpp File Reference
GeometricalAnalysisTools.cpp File Reference
#include <GeometricalAnalysisTools.h>
#include <CVMath.h>
#include <DgmOctreeReferenceCloud.h>
#include <DistanceComputationTools.h>
#include <GenericProgressCallback.h>
#include <ReferenceCloud.h>
#include <ScalarField.h>
#include <ScalarFieldTools.h>
#include <algorithm>
#include <random>
Functions
static bool Landau_Smith (const std::vector< CCVector2d > &xy, CCVector2d &center, PointCoordinateType &radius)
int dmat_solve (int n, int rhs_num, double a[])
Variables
static double s_UnitSphereVolume = 4.0 * M_PI / 3.0
Function Documentation
dmat_solve()
int dmat_solve (int n, int rhs_num, double a[])
Definition at line 1184 of file GeometricalAnalysisTools.cpp.
References a, and std::swap().
Referenced by cloudViewer::GeometricalAnalysisTools::ComputeSphereFrom4().
Landau_Smith()
static bool Landau_Smith (const std::vector< CCVector2d > & xy, CCVector2d & center, PointCoordinateType & radius) static
Definition at line 934 of file GeometricalAnalysisTools.cpp.
References Vector2Tpl< Type >::x, and Vector2Tpl< Type >::y.
Referenced by cloudViewer::GeometricalAnalysisTools::DetectCircle().
Variable Documentation
s_UnitSphereVolume
double s_UnitSphereVolume = 4.0 * M_PI / 3.0 static
Definition at line 26 of file GeometricalAnalysisTools.cpp.
Referenced by cloudViewer::GeometricalAnalysisTools::ComputeApproxPointsDensityInACellAtLevel(), and cloudViewer::GeometricalAnalysisTools::ComputeCharactersitic().