ACloudViewer: /root/ACloudViewer/core/src/TrueKdTree.cpp File Reference
TrueKdTree.cpp File Reference
#include "TrueKdTree.h"
#include "GenericProgressCallback.h"
#include "Neighbourhood.h"
#include "ParallelSort.h"
Classes
class GetLeavesVisitor
Recursive visitor for TrueKdTree::getLeaves.
Functions
static void InitProgress (GenericProgressCallback *progressCb, unsigned totalCount)
static void UpdateProgress (unsigned increment)
Variables
static std::vector< PointCoordinateType > s_sortedCoordsForSplit
static GenericProgressCallback * s_progressCb = nullptr
static unsigned s_lastProgressCount = 0
static unsigned s_totalProgressCount = 0
static unsigned s_lastProgress = 0
Function Documentation
InitProgress()
static void InitProgress (GenericProgressCallback * progressCb, unsigned totalCount) static
Definition at line 44 of file TrueKdTree.cpp.
References s_lastProgress, s_lastProgressCount, s_progressCb, s_totalProgressCount, cloudViewer::GenericProgressCallback::setInfo(), cloudViewer::GenericProgressCallback::setMethodTitle(), cloudViewer::GenericProgressCallback::start(), and cloudViewer::GenericProgressCallback::textCanBeEdited().
Referenced by cloudViewer::TrueKdTree::build().
UpdateProgress()
static void UpdateProgress (unsigned increment) inline static
Definition at line 62 of file TrueKdTree.cpp.
References s_lastProgress, s_lastProgressCount, s_progressCb, s_totalProgressCount, and cloudViewer::GenericProgressCallback::update().
Referenced by cloudViewer::visualization::GuiVisualizer::LoadGeometry(), and cloudViewer::TrueKdTree::split().
Variable Documentation
s_lastProgress
unsigned s_lastProgress = 0 static
Definition at line 42 of file TrueKdTree.cpp.
Referenced by InitProgress(), and UpdateProgress().
s_lastProgressCount
unsigned s_lastProgressCount = 0 static
Definition at line 40 of file TrueKdTree.cpp.
Referenced by InitProgress(), and UpdateProgress().
s_progressCb
GenericProgressCallback* s_progressCb = nullptr static
Definition at line 39 of file TrueKdTree.cpp.
Referenced by InitProgress(), and UpdateProgress().
s_sortedCoordsForSplit
std::vector<PointCoordinateType> s_sortedCoordsForSplit static
Definition at line 38 of file TrueKdTree.cpp.
Referenced by cloudViewer::TrueKdTree::build(), and cloudViewer::TrueKdTree::split().
s_totalProgressCount
unsigned s_totalProgressCount = 0 static
Definition at line 41 of file TrueKdTree.cpp.
Referenced by InitProgress(), and UpdateProgress().