ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/correspondence_graph_test.cc File Reference
correspondence_graph_test.cc File Reference
#include "util/testing.h"
#include "base/correspondence_graph.h"
Macros
#define TEST_NAME "base/correspondence_graph"
Functions
BOOST_AUTO_TEST_CASE (TestDefault)
BOOST_AUTO_TEST_CASE (TestTwoView)
BOOST_AUTO_TEST_CASE (TestThreeView)
BOOST_AUTO_TEST_CASE (TestOutOfBounds)
BOOST_AUTO_TEST_CASE (TestDuplicate)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/correspondence_graph"
Definition at line 32 of file correspondence_graph_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/5]
BOOST_AUTO_TEST_CASE (TestDefault)
Definition at line 39 of file correspondence_graph_test.cc.
References colmap::CorrespondenceGraph::NumCorrespondencesBetweenImages(), and colmap::CorrespondenceGraph::NumImages().
BOOST_AUTO_TEST_CASE() [2/5]
BOOST_AUTO_TEST_CASE (TestDuplicate)
Definition at line 352 of file correspondence_graph_test.cc.
References colmap::CorrespondenceGraph::AddCorrespondences(), colmap::CorrespondenceGraph::AddImage(), colmap::Database::ImagePairToPairId(), colmap::CorrespondenceGraph::NumCorrespondencesBetweenImages(), and colmap::CorrespondenceGraph::NumCorrespondencesForImage().
BOOST_AUTO_TEST_CASE() [3/5]
BOOST_AUTO_TEST_CASE (TestOutOfBounds)
Definition at line 333 of file correspondence_graph_test.cc.
References colmap::CorrespondenceGraph::AddCorrespondences(), colmap::CorrespondenceGraph::AddImage(), colmap::Database::ImagePairToPairId(), colmap::CorrespondenceGraph::NumCorrespondencesBetweenImages(), and colmap::CorrespondenceGraph::NumCorrespondencesForImage().
BOOST_AUTO_TEST_CASE() [4/5]
BOOST_AUTO_TEST_CASE (TestThreeView)
Definition at line 177 of file correspondence_graph_test.cc.
References colmap::CorrespondenceGraph::AddCorrespondences(), colmap::CorrespondenceGraph::AddImage(), colmap::CorrespondenceGraph::ExistsImage(), colmap::CorrespondenceGraph::Finalize(), colmap::CorrespondenceGraph::FindCorrespondences(), colmap::CorrespondenceGraph::FindTransitiveCorrespondences(), colmap::CorrespondenceGraph::HasCorrespondences(), colmap::Database::ImagePairToPairId(), colmap::CorrespondenceGraph::IsTwoViewObservation(), colmap::CorrespondenceGraph::NumCorrespondencesBetweenImages(), colmap::CorrespondenceGraph::NumCorrespondencesForImage(), colmap::CorrespondenceGraph::NumImages(), and colmap::CorrespondenceGraph::NumObservationsForImage().
BOOST_AUTO_TEST_CASE() [5/5]
BOOST_AUTO_TEST_CASE (TestTwoView)
Definition at line 46 of file correspondence_graph_test.cc.
References colmap::CorrespondenceGraph::AddCorrespondences(), colmap::CorrespondenceGraph::AddImage(), colmap::CorrespondenceGraph::ExistsImage(), colmap::CorrespondenceGraph::Finalize(), colmap::CorrespondenceGraph::FindCorrespondences(), colmap::CorrespondenceGraph::FindCorrespondencesBetweenImages(), colmap::CorrespondenceGraph::FindTransitiveCorrespondences(), colmap::CorrespondenceGraph::HasCorrespondences(), colmap::Database::ImagePairToPairId(), colmap::CorrespondenceGraph::IsTwoViewObservation(), colmap::CorrespondenceGraph::NumCorrespondencesBetweenImages(), colmap::CorrespondenceGraph::NumCorrespondencesForImage(), colmap::CorrespondenceGraph::NumImages(), and colmap::CorrespondenceGraph::NumObservationsForImage().