ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/cost_functions_test.cc File Reference
cost_functions_test.cc File Reference
#include "util/testing.h"
#include "base/camera_models.h"
#include "base/cost_functions.h"
#include "base/pose.h"
Macros
#define TEST_NAME "base/cost_functions"
Functions
BOOST_AUTO_TEST_CASE (TestBundleAdjustmentCostFunction)
BOOST_AUTO_TEST_CASE (TestBundleAdjustmentConstantPoseCostFunction)
BOOST_AUTO_TEST_CASE (TestRigBundleAdjustmentCostFunction)
BOOST_AUTO_TEST_CASE (TestRelativePoseCostFunction)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/cost_functions"
Definition at line 32 of file cost_functions_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (TestBundleAdjustmentConstantPoseCostFunction)
Definition at line 71 of file cost_functions_test.cc.
References colmap::ComposeIdentityQuaternion().
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (TestBundleAdjustmentCostFunction)
Definition at line 41 of file cost_functions_test.cc.
References colmap::BundleAdjustmentCostFunction< CameraModel >::Create().
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (TestRelativePoseCostFunction)
Definition at line 133 of file cost_functions_test.cc.
References colmap::RelativePoseCostFunction::Create().
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (TestRigBundleAdjustmentCostFunction)
Definition at line 100 of file cost_functions_test.cc.
References colmap::RigBundleAdjustmentCostFunction< CameraModel >::Create().