ACloudViewer: /root/ACloudViewer/plugins/core/IO/qPhotoscanIO/extern/quazip/quazip/quazip/crypt.h File Reference
crypt.h File Reference
#include "quazip_global.h"
Macros
#define CRC32(c, b) ((*(pcrc_32_tab + (((int)(c) ^ (b)) & 0xff))) ^ ((c) >> 8))
#define zdecode(pkeys, pcrc_32_tab, c) (update_keys(pkeys, pcrc_32_tab, c ^= decrypt_byte(pkeys, pcrc_32_tab)))
#define zencode(pkeys, pcrc_32_tab, c, t)
Functions
static int decrypt_byte (unsigned long *pkeys, const z_crc_t FAR *pcrc_32_tab)
static int update_keys (unsigned long *pkeys, const z_crc_t FAR *pcrc_32_tab, int c)
static void init_keys (const char *passwd, unsigned long *pkeys, const z_crc_t FAR *pcrc_32_tab)
Macro Definition Documentation
CRC32
#define CRC32 (c, b) ((*(pcrc_32_tab + (((int)(c) ^ (b)) & 0xff))) ^ ((c) >> 8))
Definition at line 32 of file crypt.h.
zdecode
#define zdecode (pkeys, pcrc_32_tab, c) (update_keys(pkeys, pcrc_32_tab, c ^= decrypt_byte(pkeys, pcrc_32_tab)))
Definition at line 80 of file crypt.h.
zencode
#define zencode (pkeys, pcrc_32_tab, c, t)
Value:
    (t = decrypt_byte(pkeys, pcrc_32_tab), update_keys(pkeys, pcrc_32_tab, c), \
     t ^ (c))
Definition at line 83 of file crypt.h.
Function Documentation
decrypt_byte()
static int decrypt_byte (unsigned long * pkeys, const z_crc_t FAR * pcrc_32_tab) static
Definition at line 37 of file crypt.h.
init_keys()
static void init_keys (const char * passwd, unsigned long * pkeys, const z_crc_t FAR * pcrc_32_tab) static
Definition at line 68 of file crypt.h.
References update_keys().
Referenced by unzOpenCurrentFile3().
update_keys()
static int update_keys (unsigned long * pkeys, const z_crc_t FAR * pcrc_32_tab, int c) static
Definition at line 51 of file crypt.h.
References CRC32.
Referenced by init_keys().