ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/FLANN/util/cuda/result_set.h File Reference
result_set.h File Reference
#include <FLANN/util/cuda/heap.h>
#include <limits>
Classes
struct flann::cuda::SingleResultSet< DistanceType >
result set for the 1nn search. Doesn't do any global memory accesses on its own,
struct flann::cuda::GreaterThan< DistanceType >
struct flann::cuda::KnnResultSet< DistanceType, useHeap >
struct flann::cuda::CountingRadiusResultSet< DistanceType >
struct flann::cuda::RadiusKnnResultSet< DistanceType, useHeap >
struct flann::cuda::KnnRadiusResultSet< DistanceType, useHeap >
struct flann::cuda::RadiusResultSet< DistanceType >
Namespaces
flann
flann::cuda
Macros
#define INFINITY infinity()
Functions
__device__ __forceinline__ float infinity ()
Macro Definition Documentation
INFINITY
#define INFINITY infinity()
Definition at line 42 of file result_set.h.
Function Documentation
infinity()
__device__ __forceinline__ float infinity ()
Definition at line 36 of file result_set.h.
Referenced by cloudViewer::t::geometry::RaycastingScene::CPUImpl::CastRays(), cloudViewer::t::geometry::RaycastingScene::CPUImpl::ComputeClosestPoints(), cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBJylanki(), cloudViewer::t::geometry::RaycastingScene::CPUImpl::CountIntersections(), cloudViewer::t::geometry::PointCloud::FarthestPointDownSample(), cloudViewer::visualization::rendering::FilamentCamera::GetViewZ(), cloudViewer::geometry::Line3D::Length(), cloudViewer::geometry::Ray3D::Length(), cloudViewer::t::geometry::RaycastingScene::CPUImpl::ListIntersections(), flann::NNIndex< Distance >::radiusSearch(), cloudViewer::visualization::rendering::Renderer::RenderToDepthImage(), and cloudViewer::t::geometry::RaycastingScene::CPUImpl::TestOcclusions().