ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/FLANN/util/cutil_math.h File Reference
cutil_math.h File Reference
#include "cuda_runtime.h"
#include <math.h>
Typedefs
typedef unsigned int uint
typedef unsigned short ushort
Functions
float fminf (float a, float b)
float fmaxf (float a, float b)
int max (int a, int b)
int min (int a, int b)
float rsqrtf (float x)
__host__ __device__ float2 make_float2 (float s)
__host__ __device__ float2 make_float2 (float3 a)
__host__ __device__ float2 make_float2 (int2 a)
__host__ __device__ float2 make_float2 (uint2 a)
__host__ __device__ int2 make_int2 (int s)
__host__ __device__ int2 make_int2 (int3 a)
__host__ __device__ int2 make_int2 (uint2 a)
__host__ __device__ int2 make_int2 (float2 a)
__host__ __device__ uint2 make_uint2 (uint s)
__host__ __device__ uint2 make_uint2 (uint3 a)
__host__ __device__ uint2 make_uint2 (int2 a)
__host__ __device__ float3 make_float3 (float s)
__host__ __device__ float3 make_float3 (float2 a)
__host__ __device__ float3 make_float3 (float2 a, float s)
__host__ __device__ float3 make_float3 (float4 a)
__host__ __device__ float3 make_float3 (int3 a)
__host__ __device__ float3 make_float3 (uint3 a)
__host__ __device__ int3 make_int3 (int s)
__host__ __device__ int3 make_int3 (int2 a)
__host__ __device__ int3 make_int3 (int2 a, int s)
__host__ __device__ int3 make_int3 (uint3 a)
__host__ __device__ int3 make_int3 (float3 a)
__host__ __device__ uint3 make_uint3 (uint s)
__host__ __device__ uint3 make_uint3 (uint2 a)
__host__ __device__ uint3 make_uint3 (uint2 a, uint s)
__host__ __device__ uint3 make_uint3 (uint4 a)
__host__ __device__ uint3 make_uint3 (int3 a)
__host__ __device__ float4 make_float4 (float s)
__host__ __device__ float4 make_float4 (float3 a)
__host__ __device__ float4 make_float4 (float3 a, float w)
__host__ __device__ float4 make_float4 (int4 a)
__host__ __device__ float4 make_float4 (uint4 a)
__host__ __device__ int4 make_int4 (int s)
__host__ __device__ int4 make_int4 (int3 a)
__host__ __device__ int4 make_int4 (int3 a, int w)
__host__ __device__ int4 make_int4 (uint4 a)
__host__ __device__ int4 make_int4 (float4 a)
__host__ __device__ uint4 make_uint4 (uint s)
__host__ __device__ uint4 make_uint4 (uint3 a)
__host__ __device__ uint4 make_uint4 (uint3 a, uint w)
__host__ __device__ uint4 make_uint4 (int4 a)
__host__ __device__ float2 operator- (float2 &a)
__host__ __device__ int2 operator- (int2 &a)
__host__ __device__ float3 operator- (float3 &a)
__host__ __device__ int3 operator- (int3 &a)
__host__ __device__ float4 operator- (float4 &a)
__host__ __device__ int4 operator- (int4 &a)
__host__ __device__ float2 operator+ (float2 a, float2 b)
__host__ __device__ void operator+= (float2 &a, float2 b)
__host__ __device__ float2 operator+ (float2 a, float b)
__host__ __device__ float2 operator+ (float b, float2 a)
__host__ __device__ void operator+= (float2 &a, float b)
__host__ __device__ int2 operator+ (int2 a, int2 b)
__host__ __device__ void operator+= (int2 &a, int2 b)
__host__ __device__ int2 operator+ (int2 a, int b)
__host__ __device__ int2 operator+ (int b, int2 a)
__host__ __device__ void operator+= (int2 &a, int b)
__host__ __device__ uint2 operator+ (uint2 a, uint2 b)
__host__ __device__ void operator+= (uint2 &a, uint2 b)
__host__ __device__ uint2 operator+ (uint2 a, uint b)
__host__ __device__ uint2 operator+ (uint b, uint2 a)
__host__ __device__ void operator+= (uint2 &a, uint b)
__host__ __device__ float3 operator+ (float3 a, float3 b)
__host__ __device__ void operator+= (float3 &a, float3 b)
__host__ __device__ float3 operator+ (float3 a, float b)
__host__ __device__ void operator+= (float3 &a, float b)
__host__ __device__ int3 operator+ (int3 a, int3 b)
__host__ __device__ void operator+= (int3 &a, int3 b)
__host__ __device__ int3 operator+ (int3 a, int b)
__host__ __device__ void operator+= (int3 &a, int b)
__host__ __device__ uint3 operator+ (uint3 a, uint3 b)
__host__ __device__ void operator+= (uint3 &a, uint3 b)
__host__ __device__ uint3 operator+ (uint3 a, uint b)
__host__ __device__ void operator+= (uint3 &a, uint b)
__host__ __device__ int3 operator+ (int b, int3 a)
__host__ __device__ uint3 operator+ (uint b, uint3 a)
__host__ __device__ float3 operator+ (float b, float3 a)
__host__ __device__ float4 operator+ (float4 a, float4 b)
__host__ __device__ void operator+= (float4 &a, float4 b)
__host__ __device__ float4 operator+ (float4 a, float b)
__host__ __device__ float4 operator+ (float b, float4 a)
__host__ __device__ void operator+= (float4 &a, float b)
__host__ __device__ int4 operator+ (int4 a, int4 b)
__host__ __device__ void operator+= (int4 &a, int4 b)
__host__ __device__ int4 operator+ (int4 a, int b)
__host__ __device__ int4 operator+ (int b, int4 a)
__host__ __device__ void operator+= (int4 &a, int b)
__host__ __device__ uint4 operator+ (uint4 a, uint4 b)
__host__ __device__ void operator+= (uint4 &a, uint4 b)
__host__ __device__ uint4 operator+ (uint4 a, uint b)
__host__ __device__ uint4 operator+ (uint b, uint4 a)
__host__ __device__ void operator+= (uint4 &a, uint b)
__host__ __device__ float2 operator- (float2 a, float2 b)
__host__ __device__ void operator-= (float2 &a, float2 b)
__host__ __device__ float2 operator- (float2 a, float b)
__host__ __device__ float2 operator- (float b, float2 a)
__host__ __device__ void operator-= (float2 &a, float b)
__host__ __device__ int2 operator- (int2 a, int2 b)
__host__ __device__ void operator-= (int2 &a, int2 b)
__host__ __device__ int2 operator- (int2 a, int b)
__host__ __device__ int2 operator- (int b, int2 a)
__host__ __device__ void operator-= (int2 &a, int b)
__host__ __device__ uint2 operator- (uint2 a, uint2 b)
__host__ __device__ void operator-= (uint2 &a, uint2 b)
__host__ __device__ uint2 operator- (uint2 a, uint b)
__host__ __device__ uint2 operator- (uint b, uint2 a)
__host__ __device__ void operator-= (uint2 &a, uint b)
__host__ __device__ float3 operator- (float3 a, float3 b)
__host__ __device__ void operator-= (float3 &a, float3 b)
__host__ __device__ float3 operator- (float3 a, float b)
__host__ __device__ float3 operator- (float b, float3 a)
__host__ __device__ void operator-= (float3 &a, float b)
__host__ __device__ int3 operator- (int3 a, int3 b)
__host__ __device__ void operator-= (int3 &a, int3 b)
__host__ __device__ int3 operator- (int3 a, int b)
__host__ __device__ int3 operator- (int b, int3 a)
__host__ __device__ void operator-= (int3 &a, int b)
__host__ __device__ uint3 operator- (uint3 a, uint3 b)
__host__ __device__ void operator-= (uint3 &a, uint3 b)
__host__ __device__ uint3 operator- (uint3 a, uint b)
__host__ __device__ uint3 operator- (uint b, uint3 a)
__host__ __device__ void operator-= (uint3 &a, uint b)
__host__ __device__ float4 operator- (float4 a, float4 b)
__host__ __device__ void operator-= (float4 &a, float4 b)
__host__ __device__ float4 operator- (float4 a, float b)
__host__ __device__ void operator-= (float4 &a, float b)
__host__ __device__ int4 operator- (int4 a, int4 b)
__host__ __device__ void operator-= (int4 &a, int4 b)
__host__ __device__ int4 operator- (int4 a, int b)
__host__ __device__ int4 operator- (int b, int4 a)
__host__ __device__ void operator-= (int4 &a, int b)
__host__ __device__ uint4 operator- (uint4 a, uint4 b)
__host__ __device__ void operator-= (uint4 &a, uint4 b)
__host__ __device__ uint4 operator- (uint4 a, uint b)
__host__ __device__ uint4 operator- (uint b, uint4 a)
__host__ __device__ void operator-= (uint4 &a, uint b)
__host__ __device__ float2 operator* (float2 a, float2 b)
__host__ __device__ void operator*= (float2 &a, float2 b)
__host__ __device__ float2 operator* (float2 a, float b)
__host__ __device__ float2 operator* (float b, float2 a)
__host__ __device__ void operator*= (float2 &a, float b)
__host__ __device__ int2 operator* (int2 a, int2 b)
__host__ __device__ void operator*= (int2 &a, int2 b)
__host__ __device__ int2 operator* (int2 a, int b)
__host__ __device__ int2 operator* (int b, int2 a)
__host__ __device__ void operator*= (int2 &a, int b)
__host__ __device__ uint2 operator* (uint2 a, uint2 b)
__host__ __device__ void operator*= (uint2 &a, uint2 b)
__host__ __device__ uint2 operator* (uint2 a, uint b)
__host__ __device__ uint2 operator* (uint b, uint2 a)
__host__ __device__ void operator*= (uint2 &a, uint b)
__host__ __device__ float3 operator* (float3 a, float3 b)
__host__ __device__ void operator*= (float3 &a, float3 b)
__host__ __device__ float3 operator* (float3 a, float b)
__host__ __device__ float3 operator* (float b, float3 a)
__host__ __device__ void operator*= (float3 &a, float b)
__host__ __device__ int3 operator* (int3 a, int3 b)
__host__ __device__ void operator*= (int3 &a, int3 b)
__host__ __device__ int3 operator* (int3 a, int b)
__host__ __device__ int3 operator* (int b, int3 a)
__host__ __device__ void operator*= (int3 &a, int b)
__host__ __device__ uint3 operator* (uint3 a, uint3 b)
__host__ __device__ void operator*= (uint3 &a, uint3 b)
__host__ __device__ uint3 operator* (uint3 a, uint b)
__host__ __device__ uint3 operator* (uint b, uint3 a)
__host__ __device__ void operator*= (uint3 &a, uint b)
__host__ __device__ float4 operator* (float4 a, float4 b)
__host__ __device__ void operator*= (float4 &a, float4 b)
__host__ __device__ float4 operator* (float4 a, float b)
__host__ __device__ float4 operator* (float b, float4 a)
__host__ __device__ void operator*= (float4 &a, float b)
__host__ __device__ int4 operator* (int4 a, int4 b)
__host__ __device__ void operator*= (int4 &a, int4 b)
__host__ __device__ int4 operator* (int4 a, int b)
__host__ __device__ int4 operator* (int b, int4 a)
__host__ __device__ void operator*= (int4 &a, int b)
__host__ __device__ uint4 operator* (uint4 a, uint4 b)
__host__ __device__ void operator*= (uint4 &a, uint4 b)
__host__ __device__ uint4 operator* (uint4 a, uint b)
__host__ __device__ uint4 operator* (uint b, uint4 a)
__host__ __device__ void operator*= (uint4 &a, uint b)
__host__ __device__ float2 operator/ (float2 a, float2 b)
__host__ __device__ void operator/= (float2 &a, float2 b)
__host__ __device__ float2 operator/ (float2 a, float b)
__host__ __device__ void operator/= (float2 &a, float b)
__host__ __device__ float2 operator/ (float b, float2 a)
__host__ __device__ float3 operator/ (float3 a, float3 b)
__host__ __device__ void operator/= (float3 &a, float3 b)
__host__ __device__ float3 operator/ (float3 a, float b)
__host__ __device__ void operator/= (float3 &a, float b)
__host__ __device__ float3 operator/ (float b, float3 a)
__host__ __device__ float4 operator/ (float4 a, float4 b)
__host__ __device__ void operator/= (float4 &a, float4 b)
__host__ __device__ float4 operator/ (float4 a, float b)
__host__ __device__ void operator/= (float4 &a, float b)
__host__ __device__ float4 operator/ (float b, float4 a)
__host__ __device__ float2 fminf (float2 a, float2 b)
__host__ __device__ float3 fminf (float3 a, float3 b)
__host__ __device__ float4 fminf (float4 a, float4 b)
__host__ __device__ int2 min (int2 a, int2 b)
__host__ __device__ int3 min (int3 a, int3 b)
__host__ __device__ int4 min (int4 a, int4 b)
__host__ __device__ uint2 min (uint2 a, uint2 b)
__host__ __device__ uint3 min (uint3 a, uint3 b)
__host__ __device__ uint4 min (uint4 a, uint4 b)
__host__ __device__ float2 fmaxf (float2 a, float2 b)
__host__ __device__ float3 fmaxf (float3 a, float3 b)
__host__ __device__ float4 fmaxf (float4 a, float4 b)
__host__ __device__ int2 max (int2 a, int2 b)
__host__ __device__ int3 max (int3 a, int3 b)
__host__ __device__ int4 max (int4 a, int4 b)
__host__ __device__ uint2 max (uint2 a, uint2 b)
__host__ __device__ uint3 max (uint3 a, uint3 b)
__host__ __device__ uint4 max (uint4 a, uint4 b)
__device__ __host__ float lerp (float a, float b, float t)
__device__ __host__ float2 lerp (float2 a, float2 b, float t)
__device__ __host__ float3 lerp (float3 a, float3 b, float t)
__device__ __host__ float4 lerp (float4 a, float4 b, float t)
__device__ __host__ float clamp (float f, float a, float b)
__device__ __host__ int clamp (int f, int a, int b)
__device__ __host__ uint clamp (uint f, uint a, uint b)
__device__ __host__ float2 clamp (float2 v, float a, float b)
__device__ __host__ float2 clamp (float2 v, float2 a, float2 b)
__device__ __host__ float3 clamp (float3 v, float a, float b)
__device__ __host__ float3 clamp (float3 v, float3 a, float3 b)
__device__ __host__ float4 clamp (float4 v, float a, float b)
__device__ __host__ float4 clamp (float4 v, float4 a, float4 b)
__device__ __host__ int2 clamp (int2 v, int a, int b)
__device__ __host__ int2 clamp (int2 v, int2 a, int2 b)
__device__ __host__ int3 clamp (int3 v, int a, int b)
__device__ __host__ int3 clamp (int3 v, int3 a, int3 b)
__device__ __host__ int4 clamp (int4 v, int a, int b)
__device__ __host__ int4 clamp (int4 v, int4 a, int4 b)
__device__ __host__ uint2 clamp (uint2 v, uint a, uint b)
__device__ __host__ uint2 clamp (uint2 v, uint2 a, uint2 b)
__device__ __host__ uint3 clamp (uint3 v, uint a, uint b)
__device__ __host__ uint3 clamp (uint3 v, uint3 a, uint3 b)
__device__ __host__ uint4 clamp (uint4 v, uint a, uint b)
__device__ __host__ uint4 clamp (uint4 v, uint4 a, uint4 b)
__host__ __device__ float dot (float2 a, float2 b)
__host__ __device__ float dot (float3 a, float3 b)
__host__ __device__ float dot (float4 a, float4 b)
__host__ __device__ int dot (int2 a, int2 b)
__host__ __device__ int dot (int3 a, int3 b)
__host__ __device__ int dot (int4 a, int4 b)
__host__ __device__ uint dot (uint2 a, uint2 b)
__host__ __device__ uint dot (uint3 a, uint3 b)
__host__ __device__ uint dot (uint4 a, uint4 b)
__host__ __device__ float length (float2 v)
__host__ __device__ float length (float3 v)
__host__ __device__ float length (float4 v)
__host__ __device__ float2 normalize (float2 v)
__host__ __device__ float3 normalize (float3 v)
__host__ __device__ float4 normalize (float4 v)
__host__ __device__ float2 floorf (float2 v)
__host__ __device__ float3 floorf (float3 v)
__host__ __device__ float4 floorf (float4 v)
__host__ __device__ float fracf (float v)
__host__ __device__ float2 fracf (float2 v)
__host__ __device__ float3 fracf (float3 v)
__host__ __device__ float4 fracf (float4 v)
__host__ __device__ float2 fmodf (float2 a, float2 b)
__host__ __device__ float3 fmodf (float3 a, float3 b)
__host__ __device__ float4 fmodf (float4 a, float4 b)
__host__ __device__ float2 fabs (float2 v)
__host__ __device__ float3 fabs (float3 v)
__host__ __device__ float4 fabs (float4 v)
__host__ __device__ int2 abs (int2 v)
__host__ __device__ int3 abs (int3 v)
__host__ __device__ int4 abs (int4 v)
__host__ __device__ float3 reflect (float3 i, float3 n)
__host__ __device__ float3 cross (float3 a, float3 b)
__device__ __host__ float smoothstep (float a, float b, float x)
__device__ __host__ float2 smoothstep (float2 a, float2 b, float2 x)
__device__ __host__ float3 smoothstep (float3 a, float3 b, float3 x)
__device__ __host__ float4 smoothstep (float4 a, float4 b, float4 x)
Typedef Documentation
uint
typedef unsigned int uint
Definition at line 28 of file cutil_math.h.
ushort
typedef unsigned short ushort
Definition at line 29 of file cutil_math.h.
Function Documentation
abs() [1/3]
__host__ __device__ int2 abs (int2 v) inline
Definition at line 1267 of file cutil_math.h.
References make_int2().
Referenced by cloudViewer::utility::MiniVec< T, N >::abs(), abs(), flann::L1< T >::accum_dist(), flann::MinkowskiDistance< T >::accum_dist(), Balance2Way(), Bnd2WayBalance(), cloudViewer::visualization::gui::NumberEdit::CalcPreferredSize(), cloudViewer::pipelines::odometry::ComputeCorrespondence(), Jacobi< Scalar >::ComputeEigenValuesAndVectors(), cloudViewer::t::geometry::kernel::pointcloud::ComputeEigenvector1(), cloudViewer::ml::impl::ComputeFilterCoordinates(), ComputeKmeansClustering(), cloudViewer::DgmOctree::ComputeMinDistanceToCellBorder(), cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBJylanki(), cloudViewer::visualization::ViewControl::ConvertFromPinholeCameraParameters(), cloudViewer::core::kernel::CPUAbsElementKernel(), cwt2d(), GrainsAsEllipsoids::directFit(), cloudViewer::t::pipelines::registration::DoSingleScaleICPIterations(), ccCompass::estimateStructureNormals(), ccCompass::exportToSVG(), cloudViewer::pipelines::integration::ScalableTSDFVolume::ExtractTriangleMesh(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractTriangleMesh(), cloudViewer::t::pipelines::kernel::FillInRigidAlignmentTermCPU(), cloudViewer::t::pipelines::kernel::FillInSLACAlignmentTermCPU(), TreeIso::Final_seg_pcd(), Cloth::findUnmovablePoint(), FM_2WayEdgeRefine(), FM_2WayNodeBalance(), FM_2WayNodeRefine(), FM_2WayNodeRefine2(), FM_2WayNodeRefine_OneSided(), FM_2WayNodeRefineEqWgt(), General2WayBalance(), cloudViewer::t::geometry::kernel::pointcloud::GetCoordinateSystemOnPlane(), cloudViewer::t::pipelines::kernel::GetJacobianDopplerICP(), cloudViewer::t::pipelines::kernel::odometry::GetJacobianHybrid(), cloudViewer::t::pipelines::kernel::odometry::GetJacobianIntensity(), cloudViewer::t::pipelines::kernel::odometry::GetJacobianPointToPlane(), getMortarMaps(), Cloth::handle_slop_connected(), cloudViewer::t::pipelines::kernel::odometry::HuberDeriv(), cloudViewer::t::pipelines::kernel::odometry::HuberLoss(), ccCompassImport::importFoliations(), cloudViewer::ml::impl::MapCylinderToCube(), cloudViewer::ml::impl::MapSphereToCylinder(), ccMeasurementDevice::measurePointToPlaneDistance(), MinCover_Decompose(), cloudViewer::visualization::VisualizerWithVertexSelection::MouseMoveCallback(), cloudViewer::visualization::gui::Window::OnMouseEvent(), cloudViewer::visualization::gui::PickPointsInteractor::OnPickImageDone(), knncpp::ManhattenDistance< Scalar >::operator()(), knncpp::MinkowskiDistance< Scalar, P >::operator()(), knncpp::ChebyshevDistance< Scalar >::operator()(), flann::L1< T >::operator()(), flann::MinkowskiDistance< T >::operator()(), flann::MaxDistance< T >::operator()(), masc::Feature::PerformMathOp(), ScalarFieldRatioWrapper::pointValue(), Chi2Helper::poz(), Vector3Tpl< Type >::prod(), ecvGenericDisplayTools::Project(), ccCloudLayersHelper::projectCloud(), cloudViewer::t::geometry::kernel::image::PyrDownDepthCPU(), cloudViewer::pipelines::registration::RegistrationICP(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScaleHybrid(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScaleIntensity(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScalePointToPlane(), cloudViewer::visualization::ViewControlWithEditing::Rotate(), ccCompassExport::saveSVG(), ccMeasurementRecorder::setPlane(), cloudViewer::core::linalg::kernel::solve_svd3x3(), sqlite3RegisterBuiltinFunctions(), cloudViewer::visualization::rendering::CameraSphereInteractorLogic::StartMouseDrag(), cloudViewer::SquareMatrixTpl< Scalar >::svd(), Cloth::timeStep(), cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::TransformationEstimationForDopplerICP(), GrainsAsEllipsoids::updateMeshAndLineSet(), Vector3Tpl< Type >::vorthogonal(), cloudViewer::pipelines::registration::L1Loss::Weight(), cloudViewer::pipelines::registration::HuberLoss::Weight(), and cloudViewer::pipelines::registration::TukeyLoss::Weight().
abs() [2/3]
__host__ __device__ int3 abs (int3 v) inline
Definition at line 1271 of file cutil_math.h.
References abs(), and make_int3().
abs() [3/3]
__host__ __device__ int4 abs (int4 v) inline
Definition at line 1275 of file cutil_math.h.
References abs(), and make_int4().
clamp() [1/21]
__device__ __host__ float clamp (float f, float a, float b) inline
Definition at line 1027 of file cutil_math.h.
References fmaxf(), and fminf().
Referenced by clamp(), and smoothstep().
clamp() [2/21]
__device__ __host__ float2 clamp (float2 v, float a, float b) inline
Definition at line 1040 of file cutil_math.h.
References clamp(), and make_float2().
clamp() [3/21]
__device__ __host__ float2 clamp (float2 v, float2 a, float2 b) inline
Definition at line 1044 of file cutil_math.h.
References clamp(), and make_float2().
clamp() [4/21]
__device__ __host__ float3 clamp (float3 v, float a, float b) inline
Definition at line 1048 of file cutil_math.h.
References clamp(), and make_float3().
clamp() [5/21]
__device__ __host__ float3 clamp (float3 v, float3 a, float3 b) inline
Definition at line 1052 of file cutil_math.h.
References clamp(), and make_float3().
clamp() [6/21]
__device__ __host__ float4 clamp (float4 v, float a, float b) inline
Definition at line 1056 of file cutil_math.h.
References clamp(), and make_float4().
clamp() [7/21]
__device__ __host__ float4 clamp (float4 v, float4 a, float4 b) inline
Definition at line 1060 of file cutil_math.h.
References clamp(), and make_float4().
clamp() [8/21]
__device__ __host__ int clamp (int f, int a, int b) inline
Definition at line 1031 of file cutil_math.h.
References max(), and min().
clamp() [9/21]
__device__ __host__ int2 clamp (int2 v, int a, int b) inline
Definition at line 1065 of file cutil_math.h.
References clamp(), and make_int2().
clamp() [10/21]
__device__ __host__ int2 clamp (int2 v, int2 a, int2 b) inline
Definition at line 1069 of file cutil_math.h.
References clamp(), and make_int2().
clamp() [11/21]
__device__ __host__ int3 clamp (int3 v, int a, int b) inline
Definition at line 1073 of file cutil_math.h.
References clamp(), and make_int3().
clamp() [12/21]
__device__ __host__ int3 clamp (int3 v, int3 a, int3 b) inline
Definition at line 1077 of file cutil_math.h.
References clamp(), and make_int3().
clamp() [13/21]
__device__ __host__ int4 clamp (int4 v, int a, int b) inline
Definition at line 1081 of file cutil_math.h.
References clamp(), and make_int4().
clamp() [14/21]
__device__ __host__ int4 clamp (int4 v, int4 a, int4 b) inline
Definition at line 1085 of file cutil_math.h.
References clamp(), and make_int4().
clamp() [15/21]
__device__ __host__ uint clamp (uint f, uint a, uint b) inline
Definition at line 1035 of file cutil_math.h.
References max(), and min().
clamp() [16/21]
__device__ __host__ uint2 clamp (uint2 v, uint a, uint b) inline
Definition at line 1090 of file cutil_math.h.
References clamp(), and make_uint2().
clamp() [17/21]
__device__ __host__ uint2 clamp (uint2 v, uint2 a, uint2 b) inline
Definition at line 1094 of file cutil_math.h.
References clamp(), and make_uint2().
clamp() [18/21]
__device__ __host__ uint3 clamp (uint3 v, uint a, uint b) inline
Definition at line 1098 of file cutil_math.h.
References clamp(), and make_uint3().
clamp() [19/21]
__device__ __host__ uint3 clamp (uint3 v, uint3 a, uint3 b) inline
Definition at line 1102 of file cutil_math.h.
References clamp(), and make_uint3().
clamp() [20/21]
__device__ __host__ uint4 clamp (uint4 v, uint a, uint b) inline
Definition at line 1106 of file cutil_math.h.
References clamp(), and make_uint4().
clamp() [21/21]
__device__ __host__ uint4 clamp (uint4 v, uint4 a, uint4 b) inline
Definition at line 1110 of file cutil_math.h.
References clamp(), and make_uint4().
cross()
__host__ __device__ float3 cross (float3 a, float3 b) inline
Definition at line 1295 of file cutil_math.h.
References make_float3().
Referenced by cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBJylanki(), and cloudViewer::io::IsPointInsidePolygon().
dot() [1/9]
__host__ __device__ float dot (float2 a, float2 b) inline
Definition at line 1119 of file cutil_math.h.
Referenced by qCanupo2DViewDialog::addOrSelectPoint(), cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBJylanki(), cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::ComputeRMSE(), cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::ComputeRMSE(), cloudViewer::pipelines::registration::TransformationEstimationForColoredICP::ComputeTransformation(), cloudViewer::pipelines::registration::TransformationEstimationPointToPlane::ComputeTransformation(), cloudViewer::visualization::ViewControl::ConvertFromPinholeCameraParameters(), ccCompass::estimateStructureNormals(), GramSchmidt(), length(), normalize(), reflect(), pba::ConfigBA::SaveBundleStatistics(), ToLocalAbscissa(), LDATrainer::train(), qCanupoTools::TrainClassifier(), ccLineation::updateMetadata(), and ccThickness::updateMetadata().
dot() [2/9]
__host__ __device__ float dot (float3 a, float3 b) inline
Definition at line 1123 of file cutil_math.h.
dot() [3/9]
__host__ __device__ float dot (float4 a, float4 b) inline
Definition at line 1127 of file cutil_math.h.
dot() [4/9]
__host__ __device__ int dot (int2 a, int2 b) inline
Definition at line 1132 of file cutil_math.h.
dot() [5/9]
__host__ __device__ int dot (int3 a, int3 b) inline
Definition at line 1136 of file cutil_math.h.
dot() [6/9]
__host__ __device__ int dot (int4 a, int4 b) inline
Definition at line 1140 of file cutil_math.h.
dot() [7/9]
__host__ __device__ uint dot (uint2 a, uint2 b) inline
Definition at line 1145 of file cutil_math.h.
dot() [8/9]
__host__ __device__ uint dot (uint3 a, uint3 b) inline
Definition at line 1149 of file cutil_math.h.
dot() [9/9]
__host__ __device__ uint dot (uint4 a, uint4 b) inline
Definition at line 1153 of file cutil_math.h.
fabs() [1/3]
__host__ __device__ float2 fabs (float2 v) inline
Definition at line 1254 of file cutil_math.h.
References make_float2().
Referenced by BetterBalance(), BetterVBalance(), cloudViewer::ml::contrib::BoxOverlap(), qCanupoProcess::Classify(), Classifier::classify2D_checkcondnum(), FacetsClassifier::CommputeHDistBetweenFacets(), Cloud2CloudDist::Compute(), Compute2WayHLoadImbalance(), Compute2WayHLoadImbalanceVec(), ComputeCorePointDescriptor(), ComputeM3C2DistForPoint(), cloudViewer::t::pipelines::kernel::ComputePairFeature(), DistanceMapGenerationTool::ComputeSurfacesAndVolumes(), FastMarchingForFacetExtraction::computeTCoefApprox(), pba::ProgramCPU::ComputeVectorMax(), DistanceMapGenerationTool::ConicalProjectN(), cloudViewer::pipelines::color_map::CreateVertexAndImageVisibility(), double_equal(), StereogramDialog::exportCurrentSelection(), cloudViewer::pipelines::integration::ScalableTSDFVolume::ExtractPointCloud(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractPointCloud(), fabs(), Factor(), qCanupoTools::Fpeq(), ccGLMatrixTpl< T >::FromToRotation(), ccKdTreeForFacetExtraction::FuseCells(), PyramidPacked::GenerateFeatureListCPU(), get_theta(), GetConeProfile(), ccGLMatrixTpl< T >::getParameters(), pba::ProgramCPU::GetRodriguesRotation(), pba::CameraT_< FT >::GetRodriguesRotation(), GramSchmidt(), qM3C2Tools::GuessBestParams(), Cloth::handle_slop_connected(), ccCompass::importFoliations(), cloudViewer::ml::contrib::Intersection(), MCRandom_KWayEdgeRefineHorizontal(), MocFM_2WayEdgeRefine(), MocFM_2WayEdgeRefine2(), MocGeneral2WayBalance(), nfa(), pba::SparseBundleCPU< Float >::NormalizeDataD(), pba::SparseBundleCU::NormalizeDataD(), RefinePointClassif(), DxfProfilesExporter::SaveHorizontalProfiles(), DxfProfilesExporter::SaveVerticalProfiles(), PdmsTools::PdmsObjects::SCylinder::setValue(), PdmsTools::PdmsObjects::CTorus::setValue(), PdmsTools::PdmsObjects::RTorus::setValue(), Solve(), pba::SparseBundleCPU< Float >::SolveNormalEquationPCGB(), pba::SparseBundleCU::SolveNormalEquationPCGB(), pba::SparseBundleCPU< Float >::SolveNormalEquationPCGX(), pba::SparseBundleCU::SolveNormalEquationPCGX(), PdmsTools::PdmsObjects::Dish::surface(), flann::test_index_precision(), flann::test_index_precisions(), qCanupoTools::TrainClassifier(), and StereogramDialog::updateFacetsFilter().
fabs() [2/3]
__host__ __device__ float3 fabs (float3 v) inline
Definition at line 1258 of file cutil_math.h.
References fabs(), and make_float3().
fabs() [3/3]
__host__ __device__ float4 fabs (float4 v) inline
Definition at line 1262 of file cutil_math.h.
References fabs(), and make_float4().
floorf() [1/3]
__host__ __device__ float2 floorf (float2 v) inline
Definition at line 1199 of file cutil_math.h.
References make_float2().
Referenced by cloudViewer::t::geometry::kernel::voxel_grid::EstimateRangeCPU(), cloudViewer::utility::floor(), floorf(), fracf(), and cloudViewer::t::geometry::kernel::voxel_grid::RayCastCPU().
floorf() [2/3]
__host__ __device__ float3 floorf (float3 v) inline
Definition at line 1203 of file cutil_math.h.
References floorf(), and make_float3().
floorf() [3/3]
__host__ __device__ float4 floorf (float4 v) inline
Definition at line 1207 of file cutil_math.h.
References floorf(), and make_float4().
fmaxf() [1/4]
float fmaxf (float a, float b) inline
Definition at line 43 of file cutil_math.h.
Referenced by clamp(), fmaxf(), and cloudViewer::ml::contrib::IoUBev2DWithMinAndMax().
fmaxf() [2/4]
__host__ __device__ float2 fmaxf (float2 a, float2 b) inline
Definition at line 961 of file cutil_math.h.
References fmaxf(), and make_float2().
fmaxf() [3/4]
__host__ __device__ float3 fmaxf (float3 a, float3 b) inline
Definition at line 965 of file cutil_math.h.
References fmaxf(), and make_float3().
fmaxf() [4/4]
__host__ __device__ float4 fmaxf (float4 a, float4 b) inline
Definition at line 969 of file cutil_math.h.
References fmaxf(), and make_float4().
fminf() [1/4]
float fminf (float a, float b) inline
Definition at line 38 of file cutil_math.h.
Referenced by clamp(), and fminf().
fminf() [2/4]
__host__ __device__ float2 fminf (float2 a, float2 b) inline
Definition at line 918 of file cutil_math.h.
References fminf(), and make_float2().
fminf() [3/4]
__host__ __device__ float3 fminf (float3 a, float3 b) inline
Definition at line 922 of file cutil_math.h.
References fminf(), and make_float3().
fminf() [4/4]
__host__ __device__ float4 fminf (float4 a, float4 b) inline
Definition at line 926 of file cutil_math.h.
References fminf(), and make_float4().
fmodf() [1/3]
__host__ __device__ float2 fmodf (float2 a, float2 b) inline
Definition at line 1237 of file cutil_math.h.
References make_float2().
Referenced by fmodf().
fmodf() [2/3]
__host__ __device__ float3 fmodf (float3 a, float3 b) inline
Definition at line 1241 of file cutil_math.h.
References fmodf(), and make_float3().
fmodf() [3/3]
__host__ __device__ float4 fmodf (float4 a, float4 b) inline
Definition at line 1245 of file cutil_math.h.
References fmodf(), and make_float4().
fracf() [1/4]
__host__ __device__ float fracf (float v) inline
Definition at line 1216 of file cutil_math.h.
References floorf().
Referenced by fracf().
fracf() [2/4]
__host__ __device__ float2 fracf (float2 v) inline
Definition at line 1220 of file cutil_math.h.
References fracf(), and make_float2().
fracf() [3/4]
__host__ __device__ float3 fracf (float3 v) inline
Definition at line 1224 of file cutil_math.h.
References fracf(), and make_float3().
fracf() [4/4]
__host__ __device__ float4 fracf (float4 v) inline
Definition at line 1228 of file cutil_math.h.
References fracf(), and make_float4().
length() [1/3]
__host__ __device__ float length (float2 v) inline
Definition at line 1162 of file cutil_math.h.
References dot().
Referenced by cloudViewer::core::HashMap::Activate(), cloudViewer::t::geometry::PointCloud::Append(), e57::BlobNodeImpl::BlobNodeImpl(), knncpp::KDTreeMinkowski< _Scalar, _Dimension, _Distance >::build(), cloudViewer::visualization::rendering::MatrixInteractorLogic::CalcDollyDist(), cloudViewer::io::CreatePointCloudFromMemory(), ccPointPair::drawMeOnly(), ccSNECloud::drawMeOnly(), cloudViewer::core::HashMap::Erase(), extractfilename(), cloudViewer::core::HashMap::Find(), cloudViewer::core::HashMap::GetActiveIndices(), getNTFSTime(), flann::Heap< T >::Heap(), flann::Heap< T >::insert(), cloudViewer::core::HashMap::Insert(), cloudViewer::core::HashMap::InsertImpl(), flann::cuda::heap::is_heap(), pybind11::detail::type_caster< QByteArray >::load(), LZ4_decompress_generic(), LZ4HC_encodeSequence(), flann::cuda::heap::make_heap(), qAnimationDlg::onAutoStepsDurationToggled(), qAnimationDlg::onTotalTimeChanged(), cloudViewer::core::HashMap::PrepareIndicesOutput(), cloudViewer::core::HashMap::PrepareMasksOutput(), cloudViewer::t::geometry::PointCloud::RandomDownSample(), cloudViewer::io::ReadPointCloud(), cloudViewer::io::ReadPointCloudInMemoryFromXYZ(), cloudViewer::t::geometry::PointCloud::SelectByIndex(), cloudViewer::t::geometry::PointCloud::SelectByMask(), WaitingSpinnerWidget::setLineLength(), setNTFSTime(), ccMeasurementRecorder::setPlane(), ViewInterpolate::setSmoothTrajectory(), flann::cuda::heap::sift_down(), sqlite3_str_vappendf(), sqlite3AtoF(), sqlite3Atoi64(), sqlite3RegisterBuiltinFunctions(), cloudViewer::t::geometry::PointCloud::UniformDownSample(), ccLineation::updateMetadata(), ccThickness::updateMetadata(), qAnimationDlg::updateSmoothTrajectoryDurations(), PdmsLexer::valueFromBuffer(), cloudViewer::io::WritePointCloud(), and cloudViewer::io::WritePointCloudInMemoryToXYZ().
length() [2/3]
__host__ __device__ float length (float3 v) inline
Definition at line 1166 of file cutil_math.h.
References dot().
length() [3/3]
__host__ __device__ float length (float4 v) inline
Definition at line 1170 of file cutil_math.h.
References dot().
lerp() [1/4]
__device__ __host__ float lerp (float a, float b, float t) inline
Definition at line 1005 of file cutil_math.h.
lerp() [2/4]
__device__ __host__ float2 lerp (float2 a, float2 b, float t) inline
Definition at line 1009 of file cutil_math.h.
lerp() [3/4]
__device__ __host__ float3 lerp (float3 a, float3 b, float t) inline
Definition at line 1013 of file cutil_math.h.
lerp() [4/4]
__device__ __host__ float4 lerp (float4 a, float4 b, float t) inline
Definition at line 1017 of file cutil_math.h.
make_float2() [1/4]
__host__ __device__ float2 make_float2 (float s) inline
Definition at line 68 of file cutil_math.h.
Referenced by clamp(), fabs(), floorf(), fmaxf(), fminf(), fmodf(), fracf(), make_float2(), operator*(), operator+(), operator-(), operator/(), and smoothstep().
make_float2() [2/4]
__host__ __device__ float2 make_float2 (float3 a) inline
Definition at line 72 of file cutil_math.h.
References make_float2().
make_float2() [3/4]
__host__ __device__ float2 make_float2 (int2 a) inline
Definition at line 76 of file cutil_math.h.
References make_float2().
make_float2() [4/4]
__host__ __device__ float2 make_float2 (uint2 a) inline
Definition at line 80 of file cutil_math.h.
References make_float2().
make_float3() [1/6]
__host__ __device__ float3 make_float3 (float s) inline
Definition at line 115 of file cutil_math.h.
Referenced by clamp(), cross(), fabs(), floorf(), fmaxf(), fminf(), fmodf(), fracf(), make_float3(), operator*(), operator+(), operator-(), operator/(), and smoothstep().
make_float3() [2/6]
__host__ __device__ float3 make_float3 (float2 a) inline
Definition at line 119 of file cutil_math.h.
References make_float3().
make_float3() [3/6]
__host__ __device__ float3 make_float3 (float2 a, float s) inline
Definition at line 123 of file cutil_math.h.
References make_float3().
make_float3() [4/6]
__host__ __device__ float3 make_float3 (float4 a) inline
Definition at line 127 of file cutil_math.h.
References make_float3().
make_float3() [5/6]
__host__ __device__ float3 make_float3 (int3 a) inline
Definition at line 131 of file cutil_math.h.
References make_float3().
make_float3() [6/6]
__host__ __device__ float3 make_float3 (uint3 a) inline
Definition at line 135 of file cutil_math.h.
References make_float3().
make_float4() [1/5]
__host__ __device__ float4 make_float4 (float s) inline
Definition at line 182 of file cutil_math.h.
Referenced by flann::CudaKdTreeBuilder::buildTree(), clamp(), fabs(), floorf(), fmaxf(), fminf(), fmodf(), fracf(), make_float4(), operator*(), operator+(), operator-(), operator/(), and smoothstep().
make_float4() [2/5]
__host__ __device__ float4 make_float4 (float3 a) inline
Definition at line 186 of file cutil_math.h.
References make_float4().
make_float4() [3/5]
__host__ __device__ float4 make_float4 (float3 a, float w) inline
Definition at line 190 of file cutil_math.h.
References make_float4().
make_float4() [4/5]
__host__ __device__ float4 make_float4 (int4 a) inline
Definition at line 194 of file cutil_math.h.
References make_float4().
make_float4() [5/5]
__host__ __device__ float4 make_float4 (uint4 a) inline
Definition at line 198 of file cutil_math.h.
References make_float4().
make_int2() [1/4]
__host__ __device__ int2 make_int2 (float2 a) inline
Definition at line 97 of file cutil_math.h.
References make_int2().
make_int2() [2/4]
__host__ __device__ int2 make_int2 (int s) inline
Definition at line 85 of file cutil_math.h.
Referenced by abs(), clamp(), make_int2(), max(), min(), operator*(), operator+(), and operator-().
make_int2() [3/4]
__host__ __device__ int2 make_int2 (int3 a) inline
Definition at line 89 of file cutil_math.h.
References make_int2().
make_int2() [4/4]
__host__ __device__ int2 make_int2 (uint2 a) inline
Definition at line 93 of file cutil_math.h.
References make_int2().
make_int3() [1/5]
__host__ __device__ int3 make_int3 (float3 a) inline
Definition at line 156 of file cutil_math.h.
References make_int3().
make_int3() [2/5]
__host__ __device__ int3 make_int3 (int s) inline
Definition at line 140 of file cutil_math.h.
Referenced by abs(), clamp(), make_int3(), max(), min(), operator*(), operator+(), and operator-().
make_int3() [3/5]
__host__ __device__ int3 make_int3 (int2 a) inline
Definition at line 144 of file cutil_math.h.
References make_int3().
make_int3() [4/5]
__host__ __device__ int3 make_int3 (int2 a, int s) inline
Definition at line 148 of file cutil_math.h.
References make_int3().
make_int3() [5/5]
__host__ __device__ int3 make_int3 (uint3 a) inline
Definition at line 152 of file cutil_math.h.
References make_int3().
make_int4() [1/5]
__host__ __device__ int4 make_int4 (float4 a) inline
Definition at line 219 of file cutil_math.h.
References make_int4().
make_int4() [2/5]
__host__ __device__ int4 make_int4 (int s) inline
Definition at line 203 of file cutil_math.h.
Referenced by abs(), clamp(), make_int4(), max(), min(), operator*(), operator+(), and operator-().
make_int4() [3/5]
__host__ __device__ int4 make_int4 (int3 a) inline
Definition at line 207 of file cutil_math.h.
References make_int4().
make_int4() [4/5]
__host__ __device__ int4 make_int4 (int3 a, int w) inline
Definition at line 211 of file cutil_math.h.
References make_int4().
make_int4() [5/5]
__host__ __device__ int4 make_int4 (uint4 a) inline
Definition at line 215 of file cutil_math.h.
References make_int4().
make_uint2() [1/3]
__host__ __device__ uint2 make_uint2 (int2 a) inline
Definition at line 110 of file cutil_math.h.
References make_uint2().
make_uint2() [2/3]
__host__ __device__ uint2 make_uint2 (uint s) inline
Definition at line 102 of file cutil_math.h.
Referenced by clamp(), make_uint2(), max(), min(), operator*(), operator+(), and operator-().
make_uint2() [3/3]
__host__ __device__ uint2 make_uint2 (uint3 a) inline
Definition at line 106 of file cutil_math.h.
References make_uint2().
make_uint3() [1/5]
__host__ __device__ uint3 make_uint3 (int3 a) inline
Definition at line 177 of file cutil_math.h.
References make_uint3().
make_uint3() [2/5]
__host__ __device__ uint3 make_uint3 (uint s) inline
Definition at line 161 of file cutil_math.h.
Referenced by clamp(), make_uint3(), max(), min(), operator*(), operator+(), and operator-().
make_uint3() [3/5]
__host__ __device__ uint3 make_uint3 (uint2 a) inline
Definition at line 165 of file cutil_math.h.
References make_uint3().
make_uint3() [4/5]
__host__ __device__ uint3 make_uint3 (uint2 a, uint s) inline
Definition at line 169 of file cutil_math.h.
References make_uint3().
make_uint3() [5/5]
__host__ __device__ uint3 make_uint3 (uint4 a) inline
Definition at line 173 of file cutil_math.h.
References make_uint3().
make_uint4() [1/4]
__host__ __device__ uint4 make_uint4 (int4 a) inline
Definition at line 237 of file cutil_math.h.
References make_uint4().
make_uint4() [2/4]
__host__ __device__ uint4 make_uint4 (uint s) inline
Definition at line 225 of file cutil_math.h.
Referenced by clamp(), make_uint4(), max(), min(), operator*(), operator+(), and operator-().
make_uint4() [3/4]
__host__ __device__ uint4 make_uint4 (uint3 a) inline
Definition at line 229 of file cutil_math.h.
References make_uint4().
make_uint4() [4/4]
__host__ __device__ uint4 make_uint4 (uint3 a, uint w) inline
Definition at line 233 of file cutil_math.h.
References make_uint4().
max() [1/7]
int max (int a, int b) inline
Definition at line 48 of file cutil_math.h.
Referenced by cloudViewer::core::HashMap::Activate(), MeshWrapper< Real >::addColor(), LasSaveDialog::addExtraScalarFieldCard(), Tiler::addPoint(), PyCC::addPointsFromArrays(), cloudViewer::t::geometry::RaycastingScene::AddTriangles(), FastGlobalRegistrationDialog::autoEstimateRadius(), cloudViewer::core::shape_util::BroadcastedShape(), BucketSortKeysInc(), cloudViewer::visualization::Visualizer::BuildUtilities(), cloudViewer::visualization::rendering::MatrixInteractorLogic::CalcDollyDist(), cloudViewer::visualization::gui::UIImage::CalcDrawParams(), cloudViewer::visualization::rendering::Camera::CalcFarPlane(), cloudViewer::visualization::rendering::RotationInteractorLogic::CalcPanVectorWorld(), cloudViewer::visualization::gui::Combobox::CalcPreferredSize(), cloudViewer::visualization::gui::FileDialog::CalcPreferredSize(), cloudViewer::visualization::gui::Label::CalcPreferredSize(), cloudViewer::visualization::gui::Layout1D::CalcPreferredSize(), cloudViewer::visualization::gui::CollapsableVert::CalcPreferredSize(), cloudViewer::visualization::gui::VGrid::CalcPreferredSize(), cloudViewer::visualization::gui::ListView::CalcPreferredSize(), cloudViewer::visualization::gui::NumberEdit::CalcPreferredSize(), cloudViewer::visualization::gui::RadioButton::CalcPreferredSize(), cloudViewer::visualization::gui::StackedWidget::CalcPreferredSize(), cloudViewer::visualization::gui::TabControl::CalcPreferredSize(), cloudViewer::visualization::gui::CheckableTextTreeCell::CalcPreferredSize(), cloudViewer::visualization::gui::LUTTreeCell::CalcPreferredSize(), cloudViewer::visualization::gui::ColormapTreeCell::CalcPreferredSize(), cloudViewer::core::Indexer::CanUse32BitIndexing(), cloudViewer::visualization::ViewControl::ChangeFieldOfView(), cloudViewer::visualization::RenderOption::ChangeLineWidth(), cloudViewer::visualization::RenderOption::ChangePointSize(), pba::SparseBundleCU::CheckRequiredMem(), cloudViewer::ml::impl::CheckVoxelSize(), clamp(), cloudViewer::geometry::Ray3D::ClampParameter(), cloudViewer::geometry::Segment3D::ClampParameter(), flann::KNNSimpleResultSet< DistanceType >::clear(), flann::KNNResultSet< DistanceType >::clear(), flann::KNNResultSet2< DistanceType >::clear(), flann::KNNUniqueResultSet< DistanceType >::clear(), cloudViewer::t::io::ColorToUint8< double >(), cloudViewer::t::io::ColorToUint8< float >(), cloudViewer::t::io::ColorToUint8< std::uint16_t >(), cloudViewer::t::io::ColorToUint8< std::uint32_t >(), qM3C2Process::Compute(), Compute2WayHLoadImbalance(), CP::CutPursuit< T >::compute_reduced_graph(), cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::ComputeAABB(), cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ComputeAABB(), cloudViewer::visualization::rendering::LineSetBuffersBuilder::ComputeAABB(), cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::ComputeAABB(), cloudViewer::visualization::rendering::TLineSetBuffersBuilder::ComputeAABB(), cloudViewer::t::geometry::kernel::pointcloud::ComputeEigenvector1(), cloudViewer::ml::impl::ComputeFilterCoordinates(), ComputeHKWayLoadImbalance(), ComputeLoadImbalance(), ComputeMaxNodeGain(), cloudViewer::t::geometry::ComputeMetricsCommon(), cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBJylanki(), cloudViewer::t::geometry::kernel::uvunwrapping::ComputeUVAtlas(), pba::ProgramCPU::ComputeVectorMax(), cloudViewer::visualization::ViewControl::ConvertFromPinholeCameraParameters(), GLTexImage::CopyFromPBO(), cloudViewer::core::kernel::CPUMaxElementKernel(), cloudViewer::core::kernel::CPUMaxReductionKernel(), DistanceMapGenerationTool::CreateMap(), cloudViewer::t::geometry::kernel::image::CreateNormalMapCPU(), DecodeSensor(), cloudViewer::visualization::RenderOptionWithEditing::DecreaseSphereSize(), define_ccPointCloud(), define_ccSensor(), define_ccWaveform(), qHoughNormals::doAction(), qRansacSD::doAction(), cloudViewer::visualization::gui::ProgressBar::Draw(), cloudViewer::visualization::gui::MenuImgui::Draw(), EliminateSubDomainEdges(), EliminateVolSubDomainEdges(), Eigen_Normal_Estimator::estimate_normals(), ccCompass::estimateP21(), cloudViewer::t::geometry::kernel::pointcloud::EstimatePointWiseNormalsWithFastEigen3x3(), cloudViewer::t::geometry::kernel::voxel_grid::EstimateRangeCPU(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), Execute(), FastGlobalRegistrationDialog::FastGlobalRegistrationDialog(), LasScalarField::Range::ForType(), ecvColor::RgbTpl< Type >::FromEigen(), NumpyCloud::getBoundingBox(), GetBoundingBoxXForm(), getDigits(), cloudViewer::visualization::rendering::FilamentScene::GetGeometryBoundingBox(), LasField::GetLASFields(), cloudViewer::BoundingBoxTpl< T >::getMaxBoxDim(), qM3C2Dialog::getMinPointsForStats(), cloudViewer::core::getNewCapacity(), ecvDisplayTools::GetOptimizedFontSize(), ccMesh::GetOrderedEdge(), ecvDisplayTools::GetPlatformAwareDPIScale(), GetPointXForm(), G3Point::getRandomColors(), PCVContext::GLAccumPixel(), LasScalarFieldSaver::handleScalarFields(), Hsv::Hsv(), iamax(), idxamax(), idxamax_strd(), iidxsort(), iintsort(), iiqst(), ikeysort(), ikeyvalsort(), ccCompass::importFoliations(), ccCompass::importLineations(), PyramidNaive::InitPyramid(), PyramidPacked::InitPyramid(), flann::BoundedHeap< T >::insert(), cloudViewer::core::HashMap::Insert(), cloudViewer::ml::impl::InterpolationVec< T, VECSIZE, InterpolationMode::LINEAR >::Interpolate(), cloudViewer::Grid3D< Type >::intersectWith(), cloudViewer::core::InverseSYCL(), cloudViewer::t::geometry::kernel::pointcloud::IsBoundaryPoints(), keyiqst(), keyvaliqst(), flann::KMeansIndex< Distance >::KMeansIndex(), flann::KNNResultSet< DistanceType >::KNNResultSet(), flann::KNNSimpleResultSet< DistanceType >::KNNSimpleResultSet(), cloudViewer::visualization::gui::Layout1D::Layout(), cloudViewer::visualization::gui::LUTTreeCell::Layout(), cloudViewer::core::LeastSquaresCPU(), cloudViewer::core::LeastSquaresCUDA(), cloudViewer::core::LeastSquaresSYCL(), cloudViewer::visualization::gui::Color::Lightened(), CodeEditor::lineNumberAreaWidth(), LasIOFilter::loadFile(), cloudViewer::visualization::MakeSlider(), max(), max_col(), cloudViewer::visualization::rendering::maxLevelCount(), minmaxStep(), MocIsHBalanced(), pba::SparseBundleCPU< Float >::NonlinearOptimizeLM(), pba::SparseBundleCU::NonlinearOptimizeLM(), pba::SparseBundleCPU< Float >::NormalizeDataD(), pba::SparseBundleCU::NormalizeDataD(), cloudViewer::visualization::gui::PickPointsInteractor::OnPickImageDone(), cloudViewer::BoundingBoxTpl< T >::operator+(), cloudViewer::ml::contrib::OptBlockConfig(), cloudViewer::pipelines::registration::GlobalOptimizationLevenbergMarquardt::OptimizePoseGraph(), cloudViewer::ml::contrib::OptNumThreads(), StereogramWidget::paintEvent(), pba::ConfigBA::ParseParam(), SiftGPU::ParseParam(), masc::ContextBasedFeature::prepare(), qAnimationDlg::preview(), PrintSubDomainGraph(), CommandRANSAC::process(), cloudViewer::t::geometry::kernel::image::PyrDownDepthCPU(), cloudViewer::ml::contrib::RadiusSearch(), cloudViewer::t::geometry::kernel::voxel_grid::RayCastCPU(), E57FileInputStream::readBytes(), cloudViewer::io::ReadModelUsingAssimp(), cloudViewer::io::ReadTriangleMeshFromGLTF(), ecvDisplayTools::HotZone::rect(), RefinePointClassif(), cloudViewer::core::MemoryCache::ReleaseAll(), cloudViewer::visualization::visualizer::O3DVisualizer::Impl::RemoveGeometry(), pba::SparseBundleCU::ReserveStorage(), PyramidGL::ResizeFeatureStorage(), pba::SparseBundleCPU< Float >::RunProfileSteps(), samax(), SampleSphere(), DxfProfilesExporter::SaveHorizontalProfiles(), SaveScan(), LASFWFFilter::saveToFile(), LasIOFilter::saveToFile(), LASFilter::saveToFile(), DxfProfilesExporter::SaveVerticalProfiles(), cloudViewer::core::Scalar::Scalar(), cloudViewer::visualization::ViewControl::Scale(), SelectQueue(), SelectQueue2(), SelectQueueOneWay(), SelectQueueOneWay2(), cloudViewer::visualization::gui::NumberEdit::SetLimits(), SiftMatchGPU::SetMaxSift(), cloudViewer::visualization::gui::ListView::SetMaxVisibleItems(), G3PointDialog::setOnlyOneMax(), qCanupo2DViewDialog::setPickingRadius(), ccMeasurementRecorder::setPlane(), cloudViewer::visualization::rendering::Gradient::SetPoints(), cloudViewer::visualization::RenderOption::SetPointSize(), cloudViewer::visualization::VisualizerWithVertexSelection::SetPointSize(), cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetPointSize(), WaitingSpinnerWidget::setRoundness(), cloudViewer::visualization::gui::Slider::SetValue(), cloudViewer::visualization::ViewControl::SetViewMatrices(), SiftMatchGPU::SiftMatchGPU(), cloudViewer::t::io::DepthNoiseSimulator::Simulate(), siqst(), NumpyCloud::size(), cloudViewer::core::SmallVectorBase< Size_T >::SizeTypeMax(), sqlite3RegisterBuiltinFunctions(), cloudViewer::visualization::rendering::CameraSphereInteractorLogic::StartMouseDrag(), cloudViewer::core::linalg::kernel::svd3x3< double >(), cloudViewer::core::linalg::kernel::svd3x3< float >(), LasOpenDialog::tilingOptions(), DistanceMapGenerationDlg::toggleOverlayGrid(), cloudViewer::t::geometry::PointCloud::ToLegacy(), cloudViewer::t::geometry::TensorMap::ToString(), cloudViewer::visualization::gui::Rect::UnionedWith(), pba::ProgramCPU::UpdateCamera(), DistanceMapGenerationDlg::updateGridSteps(), LasField::UpdateMinPointFormat(), ccScalarField::Range::updateRange(), cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateSelectionSetList(), cloudViewer::t::pipelines::kernel::UpdateSPFHFeature(), cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateTimeUIRange(), DistanceMapGenerationDlg::updateZoom(), LasScalarField::ValueRange(), Vector3Tpl< Type >::vangle_rad(), Vector3Tpl< Type >::vangle_radd(), vdbeSorterOpenTempFile(), cloudViewer::pipelines::registration::HuberLoss::Weight(), cloudViewer::visualization::gui::Window::Window(), cloudViewer::core::shape_util::WrapDim(), e57::CompressedVectorWriterImpl::write(), and cloudViewer::visualization::rendering::CameraInteractorLogic::Zoom().
max() [2/7]
__host__ __device__ int2 max (int2 a, int2 b) inline
Definition at line 974 of file cutil_math.h.
References make_int2(), and max().
max() [3/7]
__host__ __device__ int3 max (int3 a, int3 b) inline
Definition at line 978 of file cutil_math.h.
References make_int3(), and max().
max() [4/7]
__host__ __device__ int4 max (int4 a, int4 b) inline
Definition at line 982 of file cutil_math.h.
References make_int4(), and max().
max() [5/7]
__host__ __device__ uint2 max (uint2 a, uint2 b) inline
Definition at line 987 of file cutil_math.h.
References make_uint2(), and max().
max() [6/7]
__host__ __device__ uint3 max (uint3 a, uint3 b) inline
Definition at line 991 of file cutil_math.h.
References make_uint3(), and max().
max() [7/7]
__host__ __device__ uint4 max (uint4 a, uint4 b) inline
Definition at line 995 of file cutil_math.h.
References make_uint4(), and max().
min() [1/7]
int min (int a, int b) inline
Definition at line 53 of file cutil_math.h.
Referenced by MeshWrapper< Real >::addColor(), Tiler::addPoint(), cloudViewer::core::SmallVectorImpl< T >::assign(), PCVContext::associateToEntity(), cloudViewer::data::BedroomRGBDImages::BedroomRGBDImages(), cloudViewer::visualization::gui::UIImage::CalcDrawParams(), cloudViewer::visualization::gui::Label::CalcPreferredSize(), cloudViewer::visualization::gui::ListView::CalcPreferredSize(), cloudViewer::visualization::Visualizer::CaptureDepthImage(), cloudViewer::visualization::ViewControl::ChangeFieldOfView(), cloudViewer::visualization::RenderOption::ChangeLineWidth(), cloudViewer::visualization::RenderOption::ChangePointSize(), cloudViewer::ml::impl::CheckVoxelSize(), clamp(), cloudViewer::geometry::Segment3D::ClampParameter(), Classifier::classify2D_checkcondnum(), cloudViewer::t::io::ColorToUint8< double >(), cloudViewer::t::io::ColorToUint8< float >(), FacetsClassifier::CommputeHDistBetweenFacets(), compute_precision(), CP::CutPursuit< T >::compute_reduced_graph(), cloudViewer::visualization::rendering::TriangleMeshBuffersBuilder::ComputeAABB(), cloudViewer::visualization::rendering::PointCloudBuffersBuilder::ComputeAABB(), cloudViewer::visualization::rendering::LineSetBuffersBuilder::ComputeAABB(), cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::ComputeAABB(), cloudViewer::visualization::rendering::TLineSetBuffersBuilder::ComputeAABB(), ComputeAverageColor(), pba::ProgramCPU::ComputeDiagonalBlockC(), pba::ProgramCPU::ComputeDiagonalBlockP(), AnglesCustomPlot::computeHistogram(), pba::ProgramCPU::ComputeJacobian(), pba::ProgramCPU::ComputeJtEC(), pba::ProgramCPU::ComputeJtEC_(), pba::ProgramCPU::ComputeJtEP(), pba::ProgramCPU::ComputeJX(), pba::ProgramCPU::ComputeJX_(), cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBJylanki(), pba::ProgramCPU::ComputeProjection(), pba::ProgramCPU::ComputeProjectionX(), pba::ProgramCPU::ComputeSAXPY(), pba::ProgramCPU::ComputeVectorNorm(), cloudViewer::visualization::ViewControl::ConvertFromPinholeCameraParameters(), flann::KNNSimpleResultSet< DistanceType >::copy(), flann::KNNResultSet< DistanceType >::copy(), flann::KNNResultSet2< DistanceType >::copy(), flann::RadiusResultSet< DistanceType >::copy(), flann::KNNRadiusResultSet< DistanceType >::copy(), cloudViewer::t::pipelines::registration::CorrespondencesFromFeatures(), cloudViewer::core::kernel::CPUMinElementKernel(), cloudViewer::core::kernel::CPUMinReductionKernel(), cloudViewer::visualization::rendering::GeometryBuffersBuilder::CreateIndexBuffer(), DistanceMapGenerationTool::CreateMap(), define_ccSensor(), define_ccWaveform(), cloudViewer::t::pipelines::registration::DoSingleScaleICPIterations(), EliminateSubDomainEdges(), EliminateVolSubDomainEdges(), cloudViewer::t::geometry::kernel::pointcloud::EstimatePointWiseNormalsWithFastEigen3x3(), cloudViewer::t::geometry::kernel::voxel_grid::EstimateRangeCPU(), ccCompass::estimateStrain(), ccCompass::estimateStructureNormals(), Execute(), FastMarchingForFacetExtraction::ExtractPlanarFacets(), GLTexImage::FillMargin(), GLTexPacked::FillMargin(), PyramidNaive::FitPyramid(), PyramidPacked::FitPyramid(), LasScalarField::Range::ForType(), ecvColor::RgbTpl< Type >::FromEigen(), PyramidGL::GenerateFeatureListTex(), NumpyCloud::getBoundingBox(), GetBoundingBoxXForm(), getDigits(), PyramidGL::GetFeatureDescriptors(), cloudViewer::visualization::rendering::FilamentScene::GetGeometryBoundingBox(), cloudViewer::BoundingBoxTpl< T >::getMinBoxDim(), ecvDisplayTools::GetOptimizedFontSize(), ccMesh::GetOrderedEdge(), ecvDisplayTools::GetPlatformAwareDPIScale(), GetPointXForm(), qM3C2Tools::GuessBestParams(), LasScalarFieldSaver::handleScalarFields(), Hsv::Hsv(), idxamin(), iidxsort(), iintsort(), ikeysort(), ikeyvalsort(), cloudViewer::visualization::RenderOptionWithEditing::IncreaseSphereSize(), e57::BitpackDecoder::inputProcess(), e57::BitpackIntegerDecoder< RegisterT >::inputProcessAligned(), cloudViewer::pipelines::integration::UniformTSDFVolume::IntegrateWithDepthToCameraDistanceMultiplier(), cloudViewer::ml::impl::InterpolationVec< T, VECSIZE, InterpolationMode::LINEAR >::Interpolate(), cloudViewer::Grid3D< Type >::intersectWith(), cloudViewer::core::shape_util::IsCompatibleBroadcastShape(), flann::LshIndex< Distance >::knnSearch(), flann::NNIndex< Distance >::knnSearch(), cloudViewer::core::kernel::CPUArgReductionEngine::LaunchArgReductionKernelTwoPass(), cloudViewer::visualization::GuiVisualizer::Layout(), cloudViewer::visualization::gui::Color::Lightened(), LASFilter::loadFile(), cloudViewer::data::LoungeRGBDImages::LoungeRGBDImages(), cloudViewer::core::LU(), cloudViewer::core::LUIpiv(), cloudViewer::visualization::MakeSlider(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::max_size(), min(), min_col(), StereogramWidget::mousePressEvent(), pba::ProgramCPU::MultiplyBlockConditionerC(), pba::ProgramCPU::MultiplyBlockConditionerP(), cloudViewer::t::pipelines::registration::MultiScaleICP(), pba::SparseBundleCPU< Float >::NormalizeDataD(), pba::SparseBundleCU::NormalizeDataD(), PyramidGL::NormalizeDescriptor(), cloudViewer::visualization::gui::PickPointsInteractor::OnPickImageDone(), cloudViewer::visualization::gui::Window::OnResize(), flann::KMeansppCenterChooser< Distance >::operator()(), flann::GroupWiseCenterChooser< Distance >::operator()(), cloudViewer::BoundingBoxTpl< T >::operator+(), cloudViewer::ml::contrib::OptBlockConfig(), cloudViewer::pipelines::registration::GlobalOptimizationLevenbergMarquardt::OptimizePoseGraph(), cloudViewer::ml::contrib::OptNumThreads(), StereogramWidget::paintEvent(), SiftGPU::ParseParam(), e57::CheckedFile::physicalToLogical(), e57::BitpackStringEncoder::processRecords(), e57::BitpackIntegerEncoder< RegisterT >::processRecords(), cloudViewer::t::geometry::TriangleMesh::ProjectImagesToAlbedo(), cloudViewer::t::geometry::kernel::image::PyrDownDepthCPU(), flann::mpi::Index< Distance >::radiusSearch(), flann::NNIndex< Distance >::radiusSearch(), e57::CheckedFile::read(), E57FileInputStream::readBytes(), ecvDisplayTools::HotZone::rect(), RefinePointClassif(), cloudViewer::visualization::visualizer::O3DVisualizer::Impl::RemoveGeometry(), cloudViewer::visualization::visualizer::O3DVisualizerSelections::RemoveSet(), PyramidNaive::ResizePyramid(), PyramidPacked::ResizePyramid(), samin(), DxfProfilesExporter::SaveHorizontalProfiles(), SaveScan(), DxfProfilesExporter::SaveVerticalProfiles(), cloudViewer::visualization::ViewControl::Scale(), cloudViewer::core::nns::NanoFlannIndex::SearchKnn(), LasSaveDialog::selectedPointFormat(), LasSaveDialog::selectedVersion(), cloudViewer::visualization::gui::NumberEdit::SetLimits(), cloudViewer::visualization::rendering::Gradient::SetPoints(), cloudViewer::visualization::RenderOption::SetPointSize(), WaitingSpinnerWidget::setRoundness(), cloudViewer::visualization::gui::ListView::SetSelectedIndex(), cloudViewer::visualization::gui::RadioButton::SetSelectedIndex(), cloudViewer::visualization::gui::Slider::SetValue(), cloudViewer::visualization::gui::Window::ShowDialog(), cloudViewer::t::io::DepthNoiseSimulator::Simulate(), ScalarFieldRatioWrapper::size(), NumpyCloud::size(), pba::SparseBundleCPU< Float >::SolveNormalEquationPCGB(), pba::SparseBundleCU::SolveNormalEquationPCGB(), pba::SparseBundleCPU< Float >::SolveNormalEquationPCGX(), pba::SparseBundleCU::SolveNormalEquationPCGX(), sqlite3RegisterBuiltinFunctions(), cloudViewer::visualization::rendering::CameraSphereInteractorLogic::StartMouseDrag(), cloudViewer::core::SVD(), cloudViewer::t::pipelines::slam::Model::SynthesizeModelFrame(), cloudViewer::core::kernel::TestLinalgIntegration(), qCanupoTools::TestVectorsOverlap(), cloudViewer::visualization::rendering::TextureSamplerParameters::TextureSamplerParameters(), TileLasReader(), qCanupoTools::TrainClassifier(), cloudViewer::visualization::gui::Rect::UnionedWith(), cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateSelectionSetList(), cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateTimeUIRange(), Vector3Tpl< Type >::vangle_rad(), Vector3Tpl< Type >::vangle_radd(), cloudViewer::pipelines::registration::TukeyLoss::Weight(), cloudViewer::core::shape_util::WrapDim(), e57::CheckedFile::write(), GLTexPacked::ZeroHistoMargin(), and cloudViewer::visualization::rendering::CameraInteractorLogic::Zoom().
min() [2/7]
__host__ __device__ int2 min (int2 a, int2 b) inline
Definition at line 931 of file cutil_math.h.
References make_int2(), and min().
min() [3/7]
__host__ __device__ int3 min (int3 a, int3 b) inline
Definition at line 935 of file cutil_math.h.
References make_int3(), and min().
min() [4/7]
__host__ __device__ int4 min (int4 a, int4 b) inline
Definition at line 939 of file cutil_math.h.
References make_int4(), and min().
min() [5/7]
__host__ __device__ uint2 min (uint2 a, uint2 b) inline
Definition at line 944 of file cutil_math.h.
References make_uint2(), and min().
min() [6/7]
__host__ __device__ uint3 min (uint3 a, uint3 b) inline
Definition at line 948 of file cutil_math.h.
References make_uint3(), and min().
min() [7/7]
__host__ __device__ uint4 min (uint4 a, uint4 b) inline
Definition at line 952 of file cutil_math.h.
References make_uint4(), and min().
normalize() [1/3]
__host__ __device__ float2 normalize (float2 v) inline
Definition at line 1179 of file cutil_math.h.
References dot(), and rsqrtf().
Referenced by cloudViewer::ml::impl::_CConvBackropFilterCPU(), cloudViewer::ml::impl::_CConvComputeFeaturesCPU(), cloudViewer::ml::impl::_SparseConvBackropFilterCPU(), cloudViewer::ml::impl::_SparseConvComputeFeaturesCPU(), and ccScalarField::getColor().
normalize() [2/3]
__host__ __device__ float3 normalize (float3 v) inline
Definition at line 1184 of file cutil_math.h.
References dot(), and rsqrtf().
normalize() [3/3]
__host__ __device__ float4 normalize (float4 v) inline
Definition at line 1189 of file cutil_math.h.
References dot(), and rsqrtf().
operator*() [1/27]
__host__ __device__ float2 operator* (float b, float2 a) inline
Definition at line 671 of file cutil_math.h.
References make_float2().
operator*() [2/27]
__host__ __device__ float3 operator* (float b, float3 a) inline
Definition at line 734 of file cutil_math.h.
References make_float3().
operator*() [3/27]
__host__ __device__ float4 operator* (float b, float4 a) inline
Definition at line 797 of file cutil_math.h.
References make_float4().
operator*() [4/27]
__host__ __device__ float2 operator* (float2 a, float b) inline
Definition at line 667 of file cutil_math.h.
References make_float2().
operator*() [5/27]
__host__ __device__ float2 operator* (float2 a, float2 b) inline
Definition at line 659 of file cutil_math.h.
References make_float2().
operator*() [6/27]
__host__ __device__ float3 operator* (float3 a, float b) inline
Definition at line 730 of file cutil_math.h.
References make_float3().
operator*() [7/27]
__host__ __device__ float3 operator* (float3 a, float3 b) inline
Definition at line 722 of file cutil_math.h.
References make_float3().
operator*() [8/27]
__host__ __device__ float4 operator* (float4 a, float b) inline
Definition at line 793 of file cutil_math.h.
References make_float4().
operator*() [9/27]
__host__ __device__ float4 operator* (float4 a, float4 b) inline
Definition at line 785 of file cutil_math.h.
References make_float4().
operator*() [10/27]
__host__ __device__ int2 operator* (int b, int2 a) inline
Definition at line 692 of file cutil_math.h.
References make_int2().
operator*() [11/27]
__host__ __device__ int3 operator* (int b, int3 a) inline
Definition at line 755 of file cutil_math.h.
References make_int3().
operator*() [12/27]
__host__ __device__ int4 operator* (int b, int4 a) inline
Definition at line 818 of file cutil_math.h.
References make_int4().
operator*() [13/27]
__host__ __device__ int2 operator* (int2 a, int b) inline
Definition at line 688 of file cutil_math.h.
References make_int2().
operator*() [14/27]
__host__ __device__ int2 operator* (int2 a, int2 b) inline
Definition at line 680 of file cutil_math.h.
References make_int2().
operator*() [15/27]
__host__ __device__ int3 operator* (int3 a, int b) inline
Definition at line 751 of file cutil_math.h.
References make_int3().
operator*() [16/27]
__host__ __device__ int3 operator* (int3 a, int3 b) inline
Definition at line 743 of file cutil_math.h.
References make_int3().
operator*() [17/27]
__host__ __device__ int4 operator* (int4 a, int b) inline
Definition at line 814 of file cutil_math.h.
References make_int4().
operator*() [18/27]
__host__ __device__ int4 operator* (int4 a, int4 b) inline
Definition at line 806 of file cutil_math.h.
References make_int4().
operator*() [19/27]
__host__ __device__ uint2 operator* (uint b, uint2 a) inline
Definition at line 713 of file cutil_math.h.
References make_uint2().
operator*() [20/27]
__host__ __device__ uint3 operator* (uint b, uint3 a) inline
Definition at line 776 of file cutil_math.h.
References make_uint3().
operator*() [21/27]
__host__ __device__ uint4 operator* (uint b, uint4 a) inline
Definition at line 839 of file cutil_math.h.
References make_uint4().
operator*() [22/27]
__host__ __device__ uint2 operator* (uint2 a, uint b) inline
Definition at line 709 of file cutil_math.h.
References make_uint2().
operator*() [23/27]
__host__ __device__ uint2 operator* (uint2 a, uint2 b) inline
Definition at line 701 of file cutil_math.h.
References make_uint2().
operator*() [24/27]
__host__ __device__ uint3 operator* (uint3 a, uint b) inline
Definition at line 772 of file cutil_math.h.
References make_uint3().
operator*() [25/27]
__host__ __device__ uint3 operator* (uint3 a, uint3 b) inline
Definition at line 764 of file cutil_math.h.
References make_uint3().
operator*() [26/27]
__host__ __device__ uint4 operator* (uint4 a, uint b) inline
Definition at line 835 of file cutil_math.h.
References make_uint4().
operator*() [27/27]
__host__ __device__ uint4 operator* (uint4 a, uint4 b) inline
Definition at line 827 of file cutil_math.h.
References make_uint4().
operator*=() [1/18]
__host__ __device__ void operator*= (float2 & a, float b) inline
Definition at line 675 of file cutil_math.h.
operator*=() [2/18]
__host__ __device__ void operator*= (float2 & a, float2 b) inline
Definition at line 663 of file cutil_math.h.
operator*=() [3/18]
__host__ __device__ void operator*= (float3 & a, float b) inline
Definition at line 738 of file cutil_math.h.
operator*=() [4/18]
__host__ __device__ void operator*= (float3 & a, float3 b) inline
Definition at line 726 of file cutil_math.h.
operator*=() [5/18]
__host__ __device__ void operator*= (float4 & a, float b) inline
Definition at line 801 of file cutil_math.h.
operator*=() [6/18]
__host__ __device__ void operator*= (float4 & a, float4 b) inline
Definition at line 789 of file cutil_math.h.
operator*=() [7/18]
__host__ __device__ void operator*= (int2 & a, int b) inline
Definition at line 696 of file cutil_math.h.
operator*=() [8/18]
__host__ __device__ void operator*= (int2 & a, int2 b) inline
Definition at line 684 of file cutil_math.h.
operator*=() [9/18]
__host__ __device__ void operator*= (int3 & a, int b) inline
Definition at line 759 of file cutil_math.h.
operator*=() [10/18]
__host__ __device__ void operator*= (int3 & a, int3 b) inline
Definition at line 747 of file cutil_math.h.
operator*=() [11/18]
__host__ __device__ void operator*= (int4 & a, int b) inline
Definition at line 822 of file cutil_math.h.
operator*=() [12/18]
__host__ __device__ void operator*= (int4 & a, int4 b) inline
Definition at line 810 of file cutil_math.h.
operator*=() [13/18]
__host__ __device__ void operator*= (uint2 & a, uint b) inline
Definition at line 717 of file cutil_math.h.
operator*=() [14/18]
__host__ __device__ void operator*= (uint2 & a, uint2 b) inline
Definition at line 705 of file cutil_math.h.
operator*=() [15/18]
__host__ __device__ void operator*= (uint3 & a, uint b) inline
Definition at line 780 of file cutil_math.h.
operator*=() [16/18]
__host__ __device__ void operator*= (uint3 & a, uint3 b) inline
Definition at line 768 of file cutil_math.h.
operator*=() [17/18]
__host__ __device__ void operator*= (uint4 & a, uint b) inline
Definition at line 843 of file cutil_math.h.
operator*=() [18/18]
__host__ __device__ void operator*= (uint4 & a, uint4 b) inline
Definition at line 831 of file cutil_math.h.
operator+() [1/27]
__host__ __device__ float2 operator+ (float b, float2 a) inline
Definition at line 287 of file cutil_math.h.
References make_float2().
operator+() [2/27]
__host__ __device__ float3 operator+ (float b, float3 a) inline
Definition at line 398 of file cutil_math.h.
References make_float3().
operator+() [3/27]
__host__ __device__ float4 operator+ (float b, float4 a) inline
Definition at line 415 of file cutil_math.h.
References make_float4().
operator+() [4/27]
__host__ __device__ float2 operator+ (float2 a, float b) inline
Definition at line 283 of file cutil_math.h.
References make_float2().
operator+() [5/27]
__host__ __device__ float2 operator+ (float2 a, float2 b) inline
Definition at line 275 of file cutil_math.h.
References make_float2().
operator+() [6/27]
__host__ __device__ float3 operator+ (float3 a, float b) inline
Definition at line 347 of file cutil_math.h.
References make_float3().
operator+() [7/27]
__host__ __device__ float3 operator+ (float3 a, float3 b) inline
Definition at line 339 of file cutil_math.h.
References make_float3().
operator+() [8/27]
__host__ __device__ float4 operator+ (float4 a, float b) inline
Definition at line 411 of file cutil_math.h.
References make_float4().
operator+() [9/27]
__host__ __device__ float4 operator+ (float4 a, float4 b) inline
Definition at line 403 of file cutil_math.h.
References make_float4().
operator+() [10/27]
__host__ __device__ int2 operator+ (int b, int2 a) inline
Definition at line 308 of file cutil_math.h.
References make_int2().
operator+() [11/27]
__host__ __device__ int3 operator+ (int b, int3 a) inline
Definition at line 390 of file cutil_math.h.
References make_int3().
operator+() [12/27]
__host__ __device__ int4 operator+ (int b, int4 a) inline
Definition at line 436 of file cutil_math.h.
References make_int4().
operator+() [13/27]
__host__ __device__ int2 operator+ (int2 a, int b) inline
Definition at line 304 of file cutil_math.h.
References make_int2().
operator+() [14/27]
__host__ __device__ int2 operator+ (int2 a, int2 b) inline
Definition at line 296 of file cutil_math.h.
References make_int2().
operator+() [15/27]
__host__ __device__ int3 operator+ (int3 a, int b) inline
Definition at line 364 of file cutil_math.h.
References make_int3().
operator+() [16/27]
__host__ __device__ int3 operator+ (int3 a, int3 b) inline
Definition at line 356 of file cutil_math.h.
References make_int3().
operator+() [17/27]
__host__ __device__ int4 operator+ (int4 a, int b) inline
Definition at line 432 of file cutil_math.h.
References make_int4().
operator+() [18/27]
__host__ __device__ int4 operator+ (int4 a, int4 b) inline
Definition at line 424 of file cutil_math.h.
References make_int4().
operator+() [19/27]
__host__ __device__ uint2 operator+ (uint b, uint2 a) inline
Definition at line 329 of file cutil_math.h.
References make_uint2().
operator+() [20/27]
__host__ __device__ uint3 operator+ (uint b, uint3 a) inline
Definition at line 394 of file cutil_math.h.
References make_uint3().
operator+() [21/27]
__host__ __device__ uint4 operator+ (uint b, uint4 a) inline
Definition at line 457 of file cutil_math.h.
References make_uint4().
operator+() [22/27]
__host__ __device__ uint2 operator+ (uint2 a, uint b) inline
Definition at line 325 of file cutil_math.h.
References make_uint2().
operator+() [23/27]
__host__ __device__ uint2 operator+ (uint2 a, uint2 b) inline
Definition at line 317 of file cutil_math.h.
References make_uint2().
operator+() [24/27]
__host__ __device__ uint3 operator+ (uint3 a, uint b) inline
Definition at line 381 of file cutil_math.h.
References make_uint3().
operator+() [25/27]
__host__ __device__ uint3 operator+ (uint3 a, uint3 b) inline
Definition at line 373 of file cutil_math.h.
References make_uint3().
operator+() [26/27]
__host__ __device__ uint4 operator+ (uint4 a, uint b) inline
Definition at line 453 of file cutil_math.h.
References make_uint4().
operator+() [27/27]
__host__ __device__ uint4 operator+ (uint4 a, uint4 b) inline
Definition at line 445 of file cutil_math.h.
References make_uint4().
operator+=() [1/18]
__host__ __device__ void operator+= (float2 & a, float b) inline
Definition at line 291 of file cutil_math.h.
operator+=() [2/18]
__host__ __device__ void operator+= (float2 & a, float2 b) inline
Definition at line 279 of file cutil_math.h.
operator+=() [3/18]
__host__ __device__ void operator+= (float3 & a, float b) inline
Definition at line 351 of file cutil_math.h.
operator+=() [4/18]
__host__ __device__ void operator+= (float3 & a, float3 b) inline
Definition at line 343 of file cutil_math.h.
operator+=() [5/18]
__host__ __device__ void operator+= (float4 & a, float b) inline
Definition at line 419 of file cutil_math.h.
operator+=() [6/18]
__host__ __device__ void operator+= (float4 & a, float4 b) inline
Definition at line 407 of file cutil_math.h.
operator+=() [7/18]
__host__ __device__ void operator+= (int2 & a, int b) inline
Definition at line 312 of file cutil_math.h.
operator+=() [8/18]
__host__ __device__ void operator+= (int2 & a, int2 b) inline
Definition at line 300 of file cutil_math.h.
operator+=() [9/18]
__host__ __device__ void operator+= (int3 & a, int b) inline
Definition at line 368 of file cutil_math.h.
operator+=() [10/18]
__host__ __device__ void operator+= (int3 & a, int3 b) inline
Definition at line 360 of file cutil_math.h.
operator+=() [11/18]
__host__ __device__ void operator+= (int4 & a, int b) inline
Definition at line 440 of file cutil_math.h.
operator+=() [12/18]
__host__ __device__ void operator+= (int4 & a, int4 b) inline
Definition at line 428 of file cutil_math.h.
operator+=() [13/18]
__host__ __device__ void operator+= (uint2 & a, uint b) inline
Definition at line 333 of file cutil_math.h.
operator+=() [14/18]
__host__ __device__ void operator+= (uint2 & a, uint2 b) inline
Definition at line 321 of file cutil_math.h.
operator+=() [15/18]
__host__ __device__ void operator+= (uint3 & a, uint b) inline
Definition at line 385 of file cutil_math.h.
operator+=() [16/18]
__host__ __device__ void operator+= (uint3 & a, uint3 b) inline
Definition at line 377 of file cutil_math.h.
operator+=() [17/18]
__host__ __device__ void operator+= (uint4 & a, uint b) inline
Definition at line 461 of file cutil_math.h.
operator+=() [18/18]
__host__ __device__ void operator+= (uint4 & a, uint4 b) inline
Definition at line 449 of file cutil_math.h.
operator-() [1/32]
__host__ __device__ float2 operator- (float b, float2 a) inline
Definition at line 482 of file cutil_math.h.
References make_float2().
operator-() [2/32]
__host__ __device__ float3 operator- (float b, float3 a) inline
Definition at line 545 of file cutil_math.h.
References make_float3().
operator-() [3/32]
__host__ __device__ float2 operator- (float2 & a) inline
Definition at line 246 of file cutil_math.h.
References make_float2().
operator-() [4/32]
__host__ __device__ float2 operator- (float2 a, float b) inline
Definition at line 478 of file cutil_math.h.
References make_float2().
operator-() [5/32]
__host__ __device__ float2 operator- (float2 a, float2 b) inline
Definition at line 470 of file cutil_math.h.
References make_float2().
operator-() [6/32]
__host__ __device__ float3 operator- (float3 & a) inline
Definition at line 254 of file cutil_math.h.
References make_float3().
operator-() [7/32]
__host__ __device__ float3 operator- (float3 a, float b) inline
Definition at line 541 of file cutil_math.h.
References make_float3().
operator-() [8/32]
__host__ __device__ float3 operator- (float3 a, float3 b) inline
Definition at line 533 of file cutil_math.h.
References make_float3().
operator-() [9/32]
__host__ __device__ float4 operator- (float4 & a) inline
Definition at line 262 of file cutil_math.h.
References make_float4().
operator-() [10/32]
__host__ __device__ float4 operator- (float4 a, float b) inline
Definition at line 604 of file cutil_math.h.
References make_float4().
operator-() [11/32]
__host__ __device__ float4 operator- (float4 a, float4 b) inline
Definition at line 596 of file cutil_math.h.
References make_float4().
operator-() [12/32]
__host__ __device__ int2 operator- (int b, int2 a) inline
Definition at line 503 of file cutil_math.h.
References make_int2().
operator-() [13/32]
__host__ __device__ int3 operator- (int b, int3 a) inline
Definition at line 566 of file cutil_math.h.
References make_int3().
operator-() [14/32]
__host__ __device__ int4 operator- (int b, int4 a) inline
Definition at line 625 of file cutil_math.h.
References make_int4().
operator-() [15/32]
__host__ __device__ int2 operator- (int2 & a) inline
Definition at line 250 of file cutil_math.h.
References make_int2().
operator-() [16/32]
__host__ __device__ int2 operator- (int2 a, int b) inline
Definition at line 499 of file cutil_math.h.
References make_int2().
operator-() [17/32]
__host__ __device__ int2 operator- (int2 a, int2 b) inline
Definition at line 491 of file cutil_math.h.
References make_int2().
operator-() [18/32]
__host__ __device__ int3 operator- (int3 & a) inline
Definition at line 258 of file cutil_math.h.
References make_int3().
operator-() [19/32]
__host__ __device__ int3 operator- (int3 a, int b) inline
Definition at line 562 of file cutil_math.h.
References make_int3().
operator-() [20/32]
__host__ __device__ int3 operator- (int3 a, int3 b) inline
Definition at line 554 of file cutil_math.h.
References make_int3().
operator-() [21/32]
__host__ __device__ int4 operator- (int4 & a) inline
Definition at line 266 of file cutil_math.h.
References make_int4().
operator-() [22/32]
__host__ __device__ int4 operator- (int4 a, int b) inline
Definition at line 621 of file cutil_math.h.
References make_int4().
operator-() [23/32]
__host__ __device__ int4 operator- (int4 a, int4 b) inline
Definition at line 613 of file cutil_math.h.
References make_int4().
operator-() [24/32]
__host__ __device__ uint2 operator- (uint b, uint2 a) inline
Definition at line 524 of file cutil_math.h.
References make_uint2().
operator-() [25/32]
__host__ __device__ uint3 operator- (uint b, uint3 a) inline
Definition at line 587 of file cutil_math.h.
References make_uint3().
operator-() [26/32]
__host__ __device__ uint4 operator- (uint b, uint4 a) inline
Definition at line 646 of file cutil_math.h.
References make_uint4().
operator-() [27/32]
__host__ __device__ uint2 operator- (uint2 a, uint b) inline
Definition at line 520 of file cutil_math.h.
References make_uint2().
operator-() [28/32]
__host__ __device__ uint2 operator- (uint2 a, uint2 b) inline
Definition at line 512 of file cutil_math.h.
References make_uint2().
operator-() [29/32]
__host__ __device__ uint3 operator- (uint3 a, uint b) inline
Definition at line 583 of file cutil_math.h.
References make_uint3().
operator-() [30/32]
__host__ __device__ uint3 operator- (uint3 a, uint3 b) inline
Definition at line 575 of file cutil_math.h.
References make_uint3().
operator-() [31/32]
__host__ __device__ uint4 operator- (uint4 a, uint b) inline
Definition at line 642 of file cutil_math.h.
References make_uint4().
operator-() [32/32]
__host__ __device__ uint4 operator- (uint4 a, uint4 b) inline
Definition at line 634 of file cutil_math.h.
References make_uint4().
operator-=() [1/18]
__host__ __device__ void operator-= (float2 & a, float b) inline
Definition at line 486 of file cutil_math.h.
operator-=() [2/18]
__host__ __device__ void operator-= (float2 & a, float2 b) inline
Definition at line 474 of file cutil_math.h.
operator-=() [3/18]
__host__ __device__ void operator-= (float3 & a, float b) inline
Definition at line 549 of file cutil_math.h.
operator-=() [4/18]
__host__ __device__ void operator-= (float3 & a, float3 b) inline
Definition at line 537 of file cutil_math.h.
operator-=() [5/18]
__host__ __device__ void operator-= (float4 & a, float b) inline
Definition at line 608 of file cutil_math.h.
operator-=() [6/18]
__host__ __device__ void operator-= (float4 & a, float4 b) inline
Definition at line 600 of file cutil_math.h.
operator-=() [7/18]
__host__ __device__ void operator-= (int2 & a, int b) inline
Definition at line 507 of file cutil_math.h.
operator-=() [8/18]
__host__ __device__ void operator-= (int2 & a, int2 b) inline
Definition at line 495 of file cutil_math.h.
operator-=() [9/18]
__host__ __device__ void operator-= (int3 & a, int b) inline
Definition at line 570 of file cutil_math.h.
operator-=() [10/18]
__host__ __device__ void operator-= (int3 & a, int3 b) inline
Definition at line 558 of file cutil_math.h.
operator-=() [11/18]
__host__ __device__ void operator-= (int4 & a, int b) inline
Definition at line 629 of file cutil_math.h.
operator-=() [12/18]
__host__ __device__ void operator-= (int4 & a, int4 b) inline
Definition at line 617 of file cutil_math.h.
operator-=() [13/18]
__host__ __device__ void operator-= (uint2 & a, uint b) inline
Definition at line 528 of file cutil_math.h.
operator-=() [14/18]
__host__ __device__ void operator-= (uint2 & a, uint2 b) inline
Definition at line 516 of file cutil_math.h.
operator-=() [15/18]
__host__ __device__ void operator-= (uint3 & a, uint b) inline
Definition at line 591 of file cutil_math.h.
operator-=() [16/18]
__host__ __device__ void operator-= (uint3 & a, uint3 b) inline
Definition at line 579 of file cutil_math.h.
operator-=() [17/18]
__host__ __device__ void operator-= (uint4 & a, uint b) inline
Definition at line 650 of file cutil_math.h.
operator-=() [18/18]
__host__ __device__ void operator-= (uint4 & a, uint4 b) inline
Definition at line 638 of file cutil_math.h.
operator/() [1/9]
__host__ __device__ float2 operator/ (float b, float2 a) inline
Definition at line 868 of file cutil_math.h.
References make_float2().
operator/() [2/9]
__host__ __device__ float3 operator/ (float b, float3 a) inline
Definition at line 889 of file cutil_math.h.
References make_float3().
operator/() [3/9]
__host__ __device__ float4 operator/ (float b, float4 a) inline
Definition at line 910 of file cutil_math.h.
References make_float4().
operator/() [4/9]
__host__ __device__ float2 operator/ (float2 a, float b) inline
Definition at line 860 of file cutil_math.h.
References make_float2().
operator/() [5/9]
__host__ __device__ float2 operator/ (float2 a, float2 b) inline
Definition at line 852 of file cutil_math.h.
References make_float2().
operator/() [6/9]
__host__ __device__ float3 operator/ (float3 a, float b) inline
Definition at line 881 of file cutil_math.h.
References make_float3().
operator/() [7/9]
__host__ __device__ float3 operator/ (float3 a, float3 b) inline
Definition at line 873 of file cutil_math.h.
References make_float3().
operator/() [8/9]
__host__ __device__ float4 operator/ (float4 a, float b) inline
Definition at line 902 of file cutil_math.h.
References make_float4().
operator/() [9/9]
__host__ __device__ float4 operator/ (float4 a, float4 b) inline
Definition at line 894 of file cutil_math.h.
References make_float4().
operator/=() [1/6]
__host__ __device__ void operator/= (float2 & a, float b) inline
Definition at line 864 of file cutil_math.h.
operator/=() [2/6]
__host__ __device__ void operator/= (float2 & a, float2 b) inline
Definition at line 856 of file cutil_math.h.
operator/=() [3/6]
__host__ __device__ void operator/= (float3 & a, float b) inline
Definition at line 885 of file cutil_math.h.
operator/=() [4/6]
__host__ __device__ void operator/= (float3 & a, float3 b) inline
Definition at line 877 of file cutil_math.h.
operator/=() [5/6]
__host__ __device__ void operator/= (float4 & a, float b) inline
Definition at line 906 of file cutil_math.h.
operator/=() [6/6]
__host__ __device__ void operator/= (float4 & a, float4 b) inline
Definition at line 898 of file cutil_math.h.
reflect()
__host__ __device__ float3 reflect (float3 i, float3 n) inline
Definition at line 1286 of file cutil_math.h.
References dot().
rsqrtf()
float rsqrtf (float x) inline
Definition at line 58 of file cutil_math.h.
Referenced by normalize().
smoothstep() [1/4]
__device__ __host__ float smoothstep (float a, float b, float x) inline
Definition at line 1307 of file cutil_math.h.
References clamp().
smoothstep() [2/4]
__device__ __host__ float2 smoothstep (float2 a, float2 b, float2 x) inline
Definition at line 1312 of file cutil_math.h.
References clamp(), and make_float2().
smoothstep() [3/4]
__device__ __host__ float3 smoothstep (float3 a, float3 b, float3 x) inline
Definition at line 1317 of file cutil_math.h.
References clamp(), and make_float3().
smoothstep() [4/4]
__device__ __host__ float4 smoothstep (float4 a, float4 b, float4 x) inline
Definition at line 1322 of file cutil_math.h.
References clamp(), and make_float4().