ACloudViewer: /root/ACloudViewer/libs/CV_db/src/TriangleMeshFactory.cpp File Reference
TriangleMeshFactory.cpp File Reference
#include <IntersectionTest.h>
#include <Logging.h>
#include <Parallel.h>
#include <Eigen/Dense>
#include <algorithm>
#include <numeric>
#include <queue>
#include <random>
#include <tuple>
#include "ecvHObjectCaster.h"
#include "ecvKDTreeFlann.h"
#include "ecvMesh.h"
#include "ecvPointCloud.h"
#include "ecvQhull.h"
Functions
template<typename F >
bool OrientTriangleHelper (const std::vector< Eigen::Vector3i > &triangles, F &swap)
Function Documentation
OrientTriangleHelper()
template<typename F > bool OrientTriangleHelper (const std::vector< Eigen::Vector3i > & triangles, F & swap)
Definition at line 1053 of file TriangleMeshFactory.cpp.
References ccMesh::GetOrderedEdge(), std::swap(), and cloudViewer::utility::swap().
Referenced by ccMesh::IsOrientable(), and ccMesh::OrientTriangles().