ACloudViewer: /root/ACloudViewer/core/include/CVConst.h File Reference
CVConst.h File Reference
#include "CVTypes.h"
#include <cfloat>
#include <cmath>
#include <limits>
Enumerations
enum CC_VIEW_ORIENTATION {
CC_TOP_VIEW , CC_BOTTOM_VIEW , CC_FRONT_VIEW , CC_BACK_VIEW ,
CC_LEFT_VIEW , CC_RIGHT_VIEW , CC_ISO_VIEW_1 , CC_ISO_VIEW_2
}
View orientation.
enum CHAMFER_DISTANCE_TYPE { CHAMFER_111 = 0 , CHAMFER_345 = 1 }
Chamfer distances types.
enum CV_LOCAL_MODEL_TYPES { NO_MODEL = 0 , LS = 1 , TRI = 2 , QUADRIC = 3 }
Variables
constexpr double M_PI = 3.14159265358979323846
Pi.
constexpr double M_PI_2 = 1.57079632679489661923
Pi/2.
constexpr double SQRT_3 = 1.7320508075688772935274463415059
Square root of 3.
constexpr double ZERO_TOLERANCE
Numerical threshold for considering a value as "zero".
constexpr float ZERO_TOLERANCE_F = std::numeric_limits<float>::epsilon()
constexpr double ZERO_TOLERANCE_D = static_cast<double>(ZERO_TOLERANCE_F)
constexpr double ZERO_SQUARED_TOLERANCE_D = ZERO_TOLERANCE_D * ZERO_TOLERANCE_D
constexpr ScalarType ZERO_TOLERANCE_SCALAR
constexpr ScalarType ZERO_TOLERANCE_POINT_COORDINATE
constexpr PointCoordinateType PC_ONE = static_cast<PointCoordinateType>(1.0)
'1' as a PointCoordinateType value
constexpr PointCoordinateType PC_NAN
'NaN' as a PointCoordinateType value
constexpr ScalarType NAN_VALUE = std::numeric_limits<ScalarType>::quiet_NaN()
NaN as a ScalarType value.
constexpr float MIN_POINT_SIZE_F = 1.0f
constexpr float MAX_POINT_SIZE_F = 16.0f
constexpr float MIN_LINE_WIDTH_F = 1.0f
constexpr float MAX_LINE_WIDTH_F = 16.0f
static constexpr float CC_GL_MAX_ZOOM_RATIO = 1.0e6f
static constexpr float CC_GL_MIN_ZOOM_RATIO = 1.0e-6f
constexpr double EPSILON_VALUE = 1.0e-5
constexpr unsigned char POINT_VISIBLE
constexpr unsigned char POINT_HIDDEN
constexpr unsigned char POINT_OUT_OF_RANGE
constexpr unsigned char POINT_OUT_OF_FOV
constexpr unsigned CV_LOCAL_MODEL_MIN_SIZE []
Min number of points to compute local models (see CV_LOCAL_MODEL_TYPES)
Enumeration Type Documentation
CC_VIEW_ORIENTATION
enum CC_VIEW_ORIENTATION
View orientation.
Enumerator
CC_TOP_VIEW
Top view (eye: +Z)
CC_BOTTOM_VIEW
Bottom view
CC_FRONT_VIEW
Front view
CC_BACK_VIEW
Back view
CC_LEFT_VIEW
Left view
CC_RIGHT_VIEW
Right view
CC_ISO_VIEW_1
Isometric view 1: front, right and top
CC_ISO_VIEW_2
Isometric view 2: back, left and top
Definition at line 102 of file CVConst.h.
CHAMFER_DISTANCE_TYPE
enum CHAMFER_DISTANCE_TYPE
Chamfer distances types.
Enumerator
CHAMFER_111
Chamfer distance <1-1-1>
CHAMFER_345
Chamfer distance <3-4-5>
Definition at line 114 of file CVConst.h.
CV_LOCAL_MODEL_TYPES
enum CV_LOCAL_MODEL_TYPES
Types of local models (no model, least square best fitting plan, Delaunay 2D1/2 triangulation, height function)
Enumerator
NO_MODEL
No local model
LS
Least Square best fitting plane
TRI
2.5D Delaunay triangulation
QUADRIC
2.5D quadric function
Definition at line 121 of file CVConst.h.
Variable Documentation
CC_GL_MAX_ZOOM_RATIO
constexpr float CC_GL_MAX_ZOOM_RATIO = 1.0e6f static constexpr
Definition at line 84 of file CVConst.h.
CC_GL_MIN_ZOOM_RATIO
constexpr float CC_GL_MIN_ZOOM_RATIO = 1.0e-6f static constexpr
Definition at line 85 of file CVConst.h.
CV_LOCAL_MODEL_MIN_SIZE
constexpr unsigned CV_LOCAL_MODEL_MIN_SIZE[] constexpr
Initial value:
= {
        1,
        3,
        3,
        6,
}
Min number of points to compute local models (see CV_LOCAL_MODEL_TYPES)
Definition at line 129 of file CVConst.h.
Referenced by define_CCConst().
EPSILON_VALUE
constexpr double EPSILON_VALUE = 1.0e-5 constexpr
Definition at line 87 of file CVConst.h.
Referenced by ecvColor::RgbTpl< Type >::FromEigen().
M_PI
constexpr double M_PI = 3.14159265358979323846 constexpr
Pi.
Definition at line 19 of file CVConst.h.
Referenced by cloudViewer::visualization::ViewControlWithCustomAnimation::AddSpinKeyFrames(), G3Point::G3PointAction::angles(), DistanceMapGenerationDlg::angularUnitChanged(), cloudViewer::visualization::rendering::RotationInteractorLogic::CalcPanVectorWorld(), cloudViewer::visualization::rendering::MatrixInteractorLogic::CalcRotateRadians(), cloudViewer::visualization::rendering::MatrixInteractorLogic::CalcRotateZRadians(), cloudViewer::visualization::ViewControl::CameraLocalRotate(), ccMouseCircle::ccMouseCircle(), Circle::Circle(), DistanceMapGenerationTool::ComputeSurfacesAndVolumes(), ConvertAngleFromRad(), ConvertAngleToRad(), DistanceMapGenerationTool::ConvertCloudToConical(), DistanceMapGenerationTool::ConvertCloudToCylindrical(), DistanceMapGenerationTool::ConvertConicalMapToMesh(), cloudViewer::visualization::ViewControl::ConvertFromPinholeCameraParameters(), DistanceMapGenerationTool::ConvertMapToCloud(), DistanceMapGenerationTool::ConvertProfileToMesh(), cloudViewer::visualization::ViewControl::ConvertToPinholeCameraParameters(), CosSinTable< Count >::CosSinTable(), DistanceMapGenerationTool::CreateMap(), cloudViewer::t::geometry::RaycastingScene::CreateRaysPinhole(), define_ccTorus(), cloudViewer::DegreesToRadians(), ccCompass::estimateStructureNormals(), DistanceMapGenerationDlg::exportProfilesAsDXF(), GrainsAsEllipsoids::initSphereVertices(), cloudViewer::t::geometry::kernel::pointcloud::IsBoundaryPoints(), logWishSF(), cloudViewer::ml::impl::MapCylinderToCube(), optRotY(), cloudViewer::visualization::gl_util::Perspective(), prior(), DistanceMapGenerationTool::ProjectPointOnCone(), cloudViewer::RadiansToDegrees(), cloudViewer::visualization::rendering::CameraSphereInteractorLogic::Rotate(), SampleSphere(), DxfProfilesExporter::SaveHorizontalProfiles(), cloudViewer::visualization::ViewControl::SetProjectionParameters(), PdmsTools::PdmsObjects::CTorus::setValue(), PdmsTools::PdmsObjects::RTorus::setValue(), e57::SphericalBounds::SphericalBounds(), cloudViewer::visualization::rendering::CameraSphereInteractorLogic::StartMouseDrag(), PdmsTools::PdmsObjects::SCylinder::surface(), PdmsTools::PdmsObjects::CTorus::surface(), PdmsTools::PdmsObjects::RTorus::surface(), PdmsTools::PdmsObjects::Dish::surface(), PdmsTools::PdmsObjects::Cone::surface(), ccLineation::updateMetadata(), ccThickness::updateMetadata(), cloudViewer::t::pipelines::kernel::UpdateSPFHFeature(), and cloudViewer::visualization::rendering::CameraInteractorLogic::Zoom().
M_PI_2
constexpr double M_PI_2 = 1.57079632679489661923 constexpr
Pi/2.
Definition at line 24 of file CVConst.h.
Referenced by ccGLMatrixTpl< T >::getParameters().
MAX_LINE_WIDTH_F
constexpr float MAX_LINE_WIDTH_F = 16.0f constexpr
Definition at line 81 of file CVConst.h.
MAX_POINT_SIZE_F
constexpr float MAX_POINT_SIZE_F = 16.0f constexpr
Definition at line 79 of file CVConst.h.
MIN_LINE_WIDTH_F
constexpr float MIN_LINE_WIDTH_F = 1.0f constexpr
Definition at line 80 of file CVConst.h.
MIN_POINT_SIZE_F
constexpr float MIN_POINT_SIZE_F = 1.0f constexpr
Definition at line 78 of file CVConst.h.
NAN_VALUE
constexpr ScalarType NAN_VALUE = std::numeric_limits<ScalarType>::quiet_NaN() constexpr
NaN as a ScalarType value.
Warning
: handle with care!
Definition at line 76 of file CVConst.h.
Referenced by masc::Classifier::classify(), qCanupoProcess::Classify(), qM3C2Process::Compute(), qVoxFallProcess::Compute(), ComputeCorePointDescriptor(), ComputeCorePointNormal(), qM3C2Normals::ComputeCorePointsNormals(), ComputeM3C2DistForPoint(), ComputeMathOpWithNearestNeighbor(), ConfusionMatrix::computeOverallAccuracy(), ConfusionMatrix::computePrecisionRecallF1Score(), DistanceMapGenerationTool::ComputeRadialDist(), qM3C2Tools::ComputeStatistics(), masc::ContextBasedFeature::computeValue(), DistanceMapGenerationTool::ConvertMapToCloud(), define_CCConst(), masc::Classifier::evaluate(), TreeIso::Final_seg_pcd(), TreeIso::Init_seg_pcd(), TreeIso::Intermediate_seg_pcd(), Interquartile(), Median(), cloudViewer::ScalarField::NaN(), masc::Feature::PerformMathOp(), ScalarFieldRatioWrapper::pointValue(), masc::ContextBasedFeature::prepare(), and masc::Feature::PrepareSF().
PC_NAN
constexpr PointCoordinateType PC_NAN constexpr
Initial value:
=
        std::numeric_limits<PointCoordinateType>::quiet_NaN()
'NaN' as a PointCoordinateType value
Warning
: handle with care!
Definition at line 71 of file CVConst.h.
Referenced by define_CCConst().
PC_ONE
constexpr PointCoordinateType PC_ONE = static_cast<PointCoordinateType>(1.0) constexpr
'1' as a PointCoordinateType value
To avoid compiler warnings about 'possible loss of data'
Definition at line 67 of file CVConst.h.
Referenced by qCanupo2DViewDialog::addOrSelectPoint(), PCVContext::associateToEntity(), NurbsCurveFitting::compute(), DistanceMapGenerationTool::ProfileMetaData::computeCloudToSurfaceOriginTrans(), masc::NeighborhoodFeature::computeValue(), DistanceMapGenerationTool::ConvertCloudToConical(), DistanceMapGenerationTool::ConvertCloudToCylindrical(), define_CCConst(), ccPointPair::drawMeOnly(), ccTrace::fitPlane(), GetConeProfile(), ccCompass::importFoliations(), ccCompassImport::importFoliations(), qAnimationDlg::smoothTrajectory(), and DistanceMapGenerationDlg::toggleOverlayGrid().
POINT_HIDDEN
constexpr unsigned char POINT_HIDDEN constexpr
Initial value:
=
        1
Point visibility state: hidden (e.g. behind other points)
Definition at line 94 of file CVConst.h.
Referenced by define_CCConst(), and StereogramDialog::updateFacetsFilter().
POINT_OUT_OF_FOV
constexpr unsigned char POINT_OUT_OF_FOV constexpr
Initial value:
=
        4
Point visibility state: out of field of view
Definition at line 98 of file CVConst.h.
Referenced by define_CCConst().
POINT_OUT_OF_RANGE
constexpr unsigned char POINT_OUT_OF_RANGE constexpr
Initial value:
=
        2
Point visibility state: out of range
Definition at line 96 of file CVConst.h.
Referenced by define_CCConst().
POINT_VISIBLE
constexpr unsigned char POINT_VISIBLE constexpr
Initial value:
=
        0
Point visibility state: visible
Definition at line 92 of file CVConst.h.
Referenced by ccSensor::checkVisibility(), define_CCConst(), ccSNECloud::drawMeOnly(), cloudViewer::GenericCloud::testVisibility(), and StereogramDialog::updateFacetsFilter().
SQRT_3
constexpr double SQRT_3 = 1.7320508075688772935274463415059 constexpr
Square root of 3.
Definition at line 29 of file CVConst.h.
Referenced by define_CCConst(), Factor(), and cloudViewer::DgmOctree::NearestNeighboursSphericalSearchStruct::prepare().
ZERO_SQUARED_TOLERANCE_D
constexpr double ZERO_SQUARED_TOLERANCE_D = ZERO_TOLERANCE_D * ZERO_TOLERANCE_D constexpr
ZERO_SQUARED_TOLERANCE_D is used to set or compare a (square) value to "close to zero".
Definition at line 53 of file CVConst.h.
Referenced by cloudViewer::GreaterThanSquareEpsilon(), and cloudViewer::LessThanSquareEpsilon().
ZERO_TOLERANCE
constexpr double ZERO_TOLERANCE constexpr
Initial value:
=
        std::numeric_limits<double>::epsilon()
Numerical threshold for considering a value as "zero".
Definition at line 37 of file CVConst.h.
Referenced by PCVContext::associateToEntity().
ZERO_TOLERANCE_D
constexpr double ZERO_TOLERANCE_D = static_cast<double>(ZERO_TOLERANCE_F) constexpr
ZERO_TOLERANCE_D is used to set or compare a double variable to "close to zero". It is defined as std::numeric_limits<float>::epsilon() because using std::numeric_limits<double>::epsilon() results in numbers that are too small for our purposes.
Definition at line 49 of file CVConst.h.
Referenced by define_CCConst(), cloudViewer::GreaterThanEpsilon(), and cloudViewer::LessThanEpsilon().
ZERO_TOLERANCE_F
constexpr float ZERO_TOLERANCE_F = std::numeric_limits<float>::epsilon() constexpr
ZERO_TOLERANCE_F is used to set or compare a float variable to "close to zero".
Definition at line 43 of file CVConst.h.
Referenced by define_CCConst(), cloudViewer::GreaterThanEpsilon(), and cloudViewer::LessThanEpsilon().
ZERO_TOLERANCE_POINT_COORDINATE
constexpr ScalarType ZERO_TOLERANCE_POINT_COORDINATE constexpr
Initial value:
=
        std::numeric_limits<PointCoordinateType>::epsilon()
ZERO_TOLERANCE_POINT_COORDINATE is used to set or compare a PointCoordinateType variable to "close to zero".
Definition at line 62 of file CVConst.h.
Referenced by define_CCConst().
ZERO_TOLERANCE_SCALAR
constexpr ScalarType ZERO_TOLERANCE_SCALAR constexpr
Initial value:
=
        std::numeric_limits<ScalarType>::epsilon()
ZERO_TOLERANCE_SCALAR is used to set or compare a ScalarType variable to "close to zero".
Definition at line 57 of file CVConst.h.
Referenced by define_CCConst(), and ccScalarField::Range::updateRange().