ACloudViewer: /root/ACloudViewer/core/src/CVKdTree.cpp File Reference
CVKdTree.cpp File Reference
#include "CVKdTree.h"
#include "GenericIndexedCloud.h"
#include "GenericProgressCallback.h"
#include <algorithm>
Functions
static bool ComparisonX (const unsigned &a, const unsigned &b)
Compares X coordinates of two points designated by their index.
static bool ComparisonY (const unsigned &a, const unsigned &b)
Compares Y coordinates of two points designated by their index.
static bool ComparisonZ (const unsigned &a, const unsigned &b)
Compares Z coordinates of two points designated by their index.
Variables
static cloudViewer::GenericIndexedCloud * s_comparisonCloud = nullptr
Function Documentation
ComparisonX()
static bool ComparisonX (const unsigned & a, const unsigned & b) static
Compares X coordinates of two points designated by their index.
Definition at line 91 of file CVKdTree.cpp.
References a, cloudViewer::GenericIndexedCloud::getPoint(), s_comparisonCloud, and Tuple3Tpl< Type >::x.
Referenced by cloudViewer::KDTree::buildSubTree().
ComparisonY()
static bool ComparisonY (const unsigned & a, const unsigned & b) static
Compares Y coordinates of two points designated by their index.
Definition at line 97 of file CVKdTree.cpp.
References a, cloudViewer::GenericIndexedCloud::getPoint(), s_comparisonCloud, and Tuple3Tpl< Type >::y.
Referenced by cloudViewer::KDTree::buildSubTree().
ComparisonZ()
static bool ComparisonZ (const unsigned & a, const unsigned & b) static
Compares Z coordinates of two points designated by their index.
Definition at line 103 of file CVKdTree.cpp.
References a, cloudViewer::GenericIndexedCloud::getPoint(), s_comparisonCloud, and Tuple3Tpl< Type >::z.
Referenced by cloudViewer::KDTree::buildSubTree().
Variable Documentation
s_comparisonCloud
cloudViewer::GenericIndexedCloud* s_comparisonCloud = nullptr static
Definition at line 88 of file CVKdTree.cpp.
Referenced by cloudViewer::KDTree::buildSubTree(), ComparisonX(), ComparisonY(), and ComparisonZ().