ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/database_cache_test.cc File Reference
database_cache_test.cc File Reference
#include "util/testing.h"
#include "base/database_cache.h"
Macros
#define TEST_NAME "base/database_cache"
Functions
BOOST_AUTO_TEST_CASE (TestEmpty)
BOOST_AUTO_TEST_CASE (TestAddCamera)
BOOST_AUTO_TEST_CASE (TestDegenerateCamera)
BOOST_AUTO_TEST_CASE (TestAddImage)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/database_cache"
Definition at line 32 of file database_cache_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (TestAddCamera)
Definition at line 45 of file database_cache_test.cc.
References colmap::DatabaseCache::AddCamera(), colmap::DatabaseCache::Camera(), colmap::Camera::CameraId(), colmap::DatabaseCache::ExistsCamera(), colmap::Camera::InitializeWithId(), colmap::SimplePinholeCameraModel::model_id, colmap::Camera::ModelId(), colmap::DatabaseCache::NumCameras(), colmap::DatabaseCache::NumImages(), and colmap::Camera::SetCameraId().
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (TestAddImage)
Definition at line 69 of file database_cache_test.cc.
References colmap::DatabaseCache::AddImage(), colmap::DatabaseCache::CorrespondenceGraph(), colmap::CorrespondenceGraph::ExistsImage(), colmap::DatabaseCache::ExistsImage(), image, colmap::DatabaseCache::Image(), colmap::DatabaseCache::NumCameras(), colmap::CorrespondenceGraph::NumCorrespondencesForImage(), colmap::DatabaseCache::NumImages(), colmap::CorrespondenceGraph::NumObservationsForImage(), and colmap::Image::NumPoints2D().
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (TestDegenerateCamera)
Definition at line 58 of file database_cache_test.cc.
References colmap::DatabaseCache::AddCamera(), colmap::DatabaseCache::Camera(), colmap::Camera::CameraId(), colmap::DatabaseCache::ExistsCamera(), colmap::Camera::InitializeWithId(), colmap::Camera::MeanFocalLength(), colmap::SimplePinholeCameraModel::model_id, colmap::DatabaseCache::NumCameras(), and colmap::DatabaseCache::NumImages().
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (TestEmpty)
Definition at line 39 of file database_cache_test.cc.
References colmap::DatabaseCache::NumCameras(), and colmap::DatabaseCache::NumImages().