ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/database_test.cc File Reference
database_test.cc File Reference
#include "util/testing.h"
#include <thread>
#include "base/database.h"
#include "base/pose.h"
Macros
#define TEST_NAME "base/database"
Functions
BOOST_AUTO_TEST_CASE (TestOpenCloseConstructorDestructor)
BOOST_AUTO_TEST_CASE (TestOpenClose)
BOOST_AUTO_TEST_CASE (TestTransaction)
BOOST_AUTO_TEST_CASE (TestTransactionMultiThreaded)
BOOST_AUTO_TEST_CASE (TestEmpty)
BOOST_AUTO_TEST_CASE (TestImagePairToPairId)
BOOST_AUTO_TEST_CASE (TestSwapImagePair)
BOOST_AUTO_TEST_CASE (TestCamera)
BOOST_AUTO_TEST_CASE (TestImage)
BOOST_AUTO_TEST_CASE (TestKeypoints)
BOOST_AUTO_TEST_CASE (TestDescriptors)
BOOST_AUTO_TEST_CASE (TestMatches)
BOOST_AUTO_TEST_CASE (TestTwoViewGeometry)
BOOST_AUTO_TEST_CASE (TestMerge)
Variables
static const std::string kMemoryDatabasePath = ":memory:"
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/database"
Definition at line 32 of file database_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/14]
BOOST_AUTO_TEST_CASE (TestCamera)
Definition at line 119 of file database_test.cc.
References colmap::Camera::CameraId(), colmap::Database::ClearCameras(), colmap::Database::ExistsCamera(), colmap::Camera::FocalLength(), colmap::Camera::InitializeWithName(), kMemoryDatabasePath, colmap::Camera::ModelId(), colmap::Database::NumCameras(), colmap::Camera::PrincipalPointX(), colmap::Camera::PrincipalPointY(), colmap::Database::ReadAllCameras(), colmap::Database::ReadCamera(), colmap::Camera::SetCameraId(), colmap::Camera::SetFocalLength(), colmap::Database::UpdateCamera(), and colmap::Database::WriteCamera().
BOOST_AUTO_TEST_CASE() [2/14]
BOOST_AUTO_TEST_CASE (TestDescriptors)
Definition at line 258 of file database_test.cc.
References colmap::Camera::CameraId(), colmap::Database::ClearDescriptors(), descriptors, image, kMemoryDatabasePath, colmap::Database::MaxNumDescriptors(), colmap::Database::NumDescriptors(), colmap::Database::NumDescriptorsForImage(), colmap::Database::ReadDescriptors(), colmap::Camera::SetCameraId(), colmap::Database::WriteCamera(), colmap::Database::WriteDescriptors(), and colmap::Database::WriteImage().
BOOST_AUTO_TEST_CASE() [3/14]
BOOST_AUTO_TEST_CASE (TestEmpty)
Definition at line 75 of file database_test.cc.
References kMemoryDatabasePath, colmap::Database::MaxNumDescriptors(), colmap::Database::MaxNumKeypoints(), colmap::Database::NumCameras(), colmap::Database::NumDescriptors(), colmap::Database::NumImages(), colmap::Database::NumKeypoints(), colmap::Database::NumMatchedImagePairs(), colmap::Database::NumMatches(), and colmap::Database::NumVerifiedImagePairs().
BOOST_AUTO_TEST_CASE() [4/14]
BOOST_AUTO_TEST_CASE (TestImage)
Definition at line 155 of file database_test.cc.
References colmap::Camera::CameraId(), colmap::Image::CameraId(), colmap::Database::ClearImages(), colmap::Database::ExistsImage(), image, colmap::Image::ImageId(), colmap::Camera::InitializeWithName(), kMemoryDatabasePath, colmap::Database::NumImages(), colmap::Image::QvecPrior(), colmap::Database::ReadAllImages(), colmap::Database::ReadImage(), colmap::Camera::SetCameraId(), colmap::Image::SetImageId(), colmap::Image::SetName(), colmap::Image::TvecPrior(), colmap::Database::UpdateImage(), colmap::Database::WriteCamera(), and colmap::Database::WriteImage().
BOOST_AUTO_TEST_CASE() [5/14]
BOOST_AUTO_TEST_CASE (TestImagePairToPairId)
Definition at line 88 of file database_test.cc.
References colmap::Database::ImagePairToPairId(), colmap::Database::kMaxNumImages, and colmap::Database::PairIdToImagePair().
BOOST_AUTO_TEST_CASE() [6/14]
BOOST_AUTO_TEST_CASE (TestKeypoints)
Definition at line 219 of file database_test.cc.
References colmap::Camera::CameraId(), colmap::Database::ClearKeypoints(), image, kMemoryDatabasePath, colmap::Database::MaxNumKeypoints(), colmap::Database::NumKeypoints(), colmap::Database::NumKeypointsForImage(), colmap::Database::ReadKeypoints(), colmap::Camera::SetCameraId(), colmap::Database::WriteCamera(), colmap::Database::WriteImage(), colmap::Database::WriteKeypoints(), x, and y.
BOOST_AUTO_TEST_CASE() [7/14]
BOOST_AUTO_TEST_CASE (TestMatches)
Definition at line 295 of file database_test.cc.
References colmap::Database::ClearMatches(), colmap::Database::DeleteMatches(), colmap::Database::ImagePairToPairId(), kMemoryDatabasePath, colmap::Database::NumMatches(), colmap::Database::ReadAllMatches(), colmap::Database::ReadMatches(), and colmap::Database::WriteMatches().
BOOST_AUTO_TEST_CASE() [8/14]
BOOST_AUTO_TEST_CASE (TestMerge)
Definition at line 411 of file database_test.cc.
References colmap::Camera::CameraId(), colmap::Database::ClearAllTables(), colmap::Database::ExistsMatches(), image, colmap::Camera::InitializeWithName(), kMemoryDatabasePath, colmap::Database::Merge(), colmap::Database::NumCameras(), colmap::Database::NumDescriptors(), colmap::Database::NumImages(), colmap::Database::NumInlierMatches(), colmap::Database::NumKeypoints(), colmap::Database::NumMatches(), colmap::Database::ReadAllImages(), colmap::Database::ReadDescriptors(), colmap::Database::ReadKeypoints(), colmap::Camera::SetCameraId(), colmap::Database::WriteCamera(), colmap::Database::WriteDescriptors(), colmap::Database::WriteImage(), colmap::Database::WriteKeypoints(), colmap::Database::WriteMatches(), and colmap::Database::WriteTwoViewGeometry().
BOOST_AUTO_TEST_CASE() [9/14]
BOOST_AUTO_TEST_CASE (TestOpenClose)
Definition at line 48 of file database_test.cc.
References colmap::Database::Close(), and kMemoryDatabasePath.
BOOST_AUTO_TEST_CASE() [10/14]
BOOST_AUTO_TEST_CASE (TestOpenCloseConstructorDestructor)
Definition at line 44 of file database_test.cc.
References kMemoryDatabasePath.
BOOST_AUTO_TEST_CASE() [11/14]
BOOST_AUTO_TEST_CASE (TestSwapImagePair)
Definition at line 112 of file database_test.cc.
References colmap::Database::SwapImagePair().
BOOST_AUTO_TEST_CASE() [12/14]
BOOST_AUTO_TEST_CASE (TestTransaction)
Definition at line 53 of file database_test.cc.
References kMemoryDatabasePath.
BOOST_AUTO_TEST_CASE() [13/14]
BOOST_AUTO_TEST_CASE (TestTransactionMultiThreaded)
Definition at line 58 of file database_test.cc.
References kMemoryDatabasePath.
BOOST_AUTO_TEST_CASE() [14/14]
BOOST_AUTO_TEST_CASE (TestTwoViewGeometry)
Definition at line 320 of file database_test.cc.
References colmap::Database::ClearTwoViewGeometries(), colmap::TwoViewGeometry::config, colmap::Database::DeleteInlierMatches(), colmap::TwoViewGeometry::E, colmap::TwoViewGeometry::F, colmap::TwoViewGeometry::H, colmap::Database::ImagePairToPairId(), colmap::TwoViewGeometry::inlier_matches, colmap::InvertPose(), kMemoryDatabasePath, colmap::Database::NumInlierMatches(), colmap::TwoViewGeometry::qvec, colmap::Database::ReadTwoViewGeometries(), colmap::Database::ReadTwoViewGeometry(), colmap::Database::ReadTwoViewGeometryNumInliers(), colmap::TwoViewGeometry::tvec, and colmap::Database::WriteTwoViewGeometry().
Variable Documentation
kMemoryDatabasePath
const std::string kMemoryDatabasePath = ":memory:" static
Definition at line 42 of file database_test.cc.
Referenced by BOOST_AUTO_TEST_CASE().