ACloudViewer: /root/ACloudViewer/libs/CV_io/extern/shapelib/dbfopen.c File Reference
dbfopen.c File Reference
#include "shapefil.h"
#include <math.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include <strings.h>
Macros
#define STRCASECMP(a, b) (strcasecmp(a,b))
#define CPLsprintf sprintf
#define CPLsnprintf snprintf
#define FALSE 0
#define TRUE 1
#define XBASE_FILEHDR_SZ 32
#define HEADER_RECORD_TERMINATOR 0x0D
#define END_OF_FILE_CHARACTER 0x1A
#define CPL_IGNORE_RET_VAL_INT(x) x
#define STATIC_CAST(type, x) ((type)(x))
#define REINTERPRET_CAST(type, x) ((type)(x))
#define CONST_CAST(type, x) ((type)(x))
#define SHPLIB_NULLPTR NULL
Functions
static const char * cvsid_aw ()
static void * SfRealloc (void *pMem, int nNewSize)
static void DBFWriteHeader (DBFHandle psDBF)
static int DBFFlushRecord (DBFHandle psDBF)
static int DBFLoadRecord (DBFHandle psDBF, int iRecord)
void DBFUpdateHeader (DBFHandle psDBF)
void DBFSetLastModifiedDate (DBFHandle psDBF, int nYYSince1900, int nMM, int nDD)
DBFHandle DBFOpen (const char *pszFilename, const char *pszAccess)
static int DBFGetLenWithoutExtension (const char *pszBasename)
DBFHandle DBFOpenLL (const char *pszFilename, const char *pszAccess, SAHooks *psHooks)
void DBFClose (DBFHandle psDBF)
DBFHandle DBFCreate (const char *pszFilename)
DBFHandle DBFCreateEx (const char *pszFilename, const char *pszCodePage)
DBFHandle DBFCreateLL (const char *pszFilename, const char *pszCodePage, SAHooks *psHooks)
int DBFAddField (DBFHandle psDBF, const char *pszFieldName, DBFFieldType eType, int nWidth, int nDecimals)
static char DBFGetNullCharacter (char chType)
int DBFAddNativeFieldType (DBFHandle psDBF, const char *pszFieldName, char chType, int nWidth, int nDecimals)
static void * DBFReadAttribute (DBFHandle psDBF, int hEntity, int iField, char chReqType)
int DBFReadIntegerAttribute (DBFHandle psDBF, int iRecord, int iField)
double DBFReadDoubleAttribute (DBFHandle psDBF, int iRecord, int iField)
const char * DBFReadStringAttribute (DBFHandle psDBF, int iRecord, int iField)
const char * DBFReadLogicalAttribute (DBFHandle psDBF, int iRecord, int iField)
static int DBFIsValueNULL (char chType, const char *pszValue)
int DBFIsAttributeNULL (DBFHandle psDBF, int iRecord, int iField)
int DBFGetFieldCount (DBFHandle psDBF)
int DBFGetRecordCount (DBFHandle psDBF)
DBFFieldType DBFGetFieldInfo (DBFHandle psDBF, int iField, char *pszFieldName, int *pnWidth, int *pnDecimals)
static int DBFWriteAttribute (DBFHandle psDBF, int hEntity, int iField, void *pValue)
int DBFWriteAttributeDirectly (DBFHandle psDBF, int hEntity, int iField, void *pValue)
int DBFWriteDoubleAttribute (DBFHandle psDBF, int iRecord, int iField, double dValue)
int DBFWriteIntegerAttribute (DBFHandle psDBF, int iRecord, int iField, int nValue)
int DBFWriteStringAttribute (DBFHandle psDBF, int iRecord, int iField, const char *pszValue)
int DBFWriteNULLAttribute (DBFHandle psDBF, int iRecord, int iField)
int DBFWriteLogicalAttribute (DBFHandle psDBF, int iRecord, int iField, const char lValue)
int DBFWriteTuple (DBFHandle psDBF, int hEntity, void *pRawTuple)
const char * DBFReadTuple (DBFHandle psDBF, int hEntity)
DBFHandle DBFCloneEmpty (DBFHandle psDBF, const char *pszFilename)
char DBFGetNativeFieldType (DBFHandle psDBF, int iField)
int DBFGetFieldIndex (DBFHandle psDBF, const char *pszFieldName)
int DBFIsRecordDeleted (DBFHandle psDBF, int iShape)
int DBFMarkRecordDeleted (DBFHandle psDBF, int iShape, int bIsDeleted)
const char * DBFGetCodePage (DBFHandle psDBF)
int DBFDeleteField (DBFHandle psDBF, int iField)
int DBFReorderFields (DBFHandle psDBF, int *panMap)
int DBFAlterFieldDefn (DBFHandle psDBF, int iField, const char *pszFieldName, char chType, int nWidth, int nDecimals)
void DBFSetWriteEndOfFileChar (DBFHandle psDBF, int bWriteFlag)
Variables
static const char cpl_cvsid [] = "$Id$"
Macro Definition Documentation
CONST_CAST
#define CONST_CAST (type, x) ((type)(x))
Definition at line 261 of file dbfopen.c.
CPL_IGNORE_RET_VAL_INT
#define CPL_IGNORE_RET_VAL_INT (x) x
Definition at line 250 of file dbfopen.c.
CPLsnprintf
#define CPLsnprintf snprintf
Definition at line 229 of file dbfopen.c.
CPLsprintf
#define CPLsprintf sprintf
Definition at line 228 of file dbfopen.c.
END_OF_FILE_CHARACTER
#define END_OF_FILE_CHARACTER 0x1A
Definition at line 245 of file dbfopen.c.
FALSE
#define FALSE 0
Definition at line 235 of file dbfopen.c.
HEADER_RECORD_TERMINATOR
#define HEADER_RECORD_TERMINATOR 0x0D
Definition at line 242 of file dbfopen.c.
REINTERPRET_CAST
#define REINTERPRET_CAST (type, x) ((type)(x))
Definition at line 260 of file dbfopen.c.
SHPLIB_NULLPTR
#define SHPLIB_NULLPTR NULL
Definition at line 262 of file dbfopen.c.
STATIC_CAST
#define STATIC_CAST (type, x) ((type)(x))
Definition at line 259 of file dbfopen.c.
STRCASECMP
#define STRCASECMP (a, b) (strcasecmp(a,b))
Definition at line 215 of file dbfopen.c.
TRUE
#define TRUE 1
Definition at line 236 of file dbfopen.c.
XBASE_FILEHDR_SZ
#define XBASE_FILEHDR_SZ 32
Definition at line 240 of file dbfopen.c.
Function Documentation
cvsid_aw()
static const char* cvsid_aw () static
Definition at line 232 of file dbfopen.c.
DBFAddField()
int DBFAddField (DBFHandle psDBF, const char * pszFieldName, DBFFieldType eType, int nWidth, int nDecimals)
Definition at line 923 of file dbfopen.c.
References DBFAddNativeFieldType(), FTDate, FTLogical, and FTString.
DBFAddNativeFieldType()
int DBFAddNativeFieldType (DBFHandle psDBF, const char * pszFieldName, char chType, int nWidth, int nDecimals)
Definition at line 970 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFInfo::bWriteEndOfFileChar, DBFFlushRecord(), DBFGetNullCharacter(), DBFUpdateHeader(), END_OF_FILE_CHARACTER, SAHooks::Error, FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SfRealloc(), DBFInfo::sHooks, STATIC_CAST, TRUE, XBASE_FLD_MAX_WIDTH, XBASE_FLDHDR_SZ, and XBASE_FLDNAME_LEN_WRITE.
Referenced by DBFAddField().
DBFAlterFieldDefn()
int DBFAlterFieldDefn (DBFHandle psDBF, int iField, const char * pszFieldName, char chType, int nWidth, int nDecimals)
Definition at line 2194 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFInfo::bWriteEndOfFileChar, DBFFlushRecord(), DBFGetNullCharacter(), DBFIsValueNULL(), DBFUpdateHeader(), END_OF_FILE_CHARACTER, FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SfRealloc(), DBFInfo::sHooks, STATIC_CAST, TRUE, XBASE_FLD_MAX_WIDTH, XBASE_FLDHDR_SZ, and XBASE_FLDNAME_LEN_WRITE.
DBFCloneEmpty()
DBFHandle DBFCloneEmpty (DBFHandle psDBF, const char * pszFilename)
Definition at line 1785 of file dbfopen.c.
References DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFInfo::bWriteEndOfFileChar, DBFClose(), DBFCreateEx(), DBFOpen(), DBFWriteHeader(), DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszHeader, SHPLIB_NULLPTR, STATIC_CAST, TRUE, and XBASE_FLDHDR_SZ.
DBFClose()
void DBFClose (DBFHandle psDBF)
Definition at line 736 of file dbfopen.c.
References DBFInfo::bNoHeader, DBFInfo::bUpdated, CPL_IGNORE_RET_VAL_INT, DBFFlushRecord(), DBFUpdateHeader(), DBFWriteHeader(), SAHooks::FClose, DBFInfo::fp, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, DBFInfo::pszWorkField, DBFInfo::sHooks, and SHPLIB_NULLPTR.
Referenced by DBFCloneEmpty(), and DBFOpenLL().
DBFCreate()
DBFHandle DBFCreate (const char * pszFilename)
Definition at line 786 of file dbfopen.c.
References DBFCreateEx().
DBFCreateEx()
DBFHandle DBFCreateEx (const char * pszFilename, const char * pszCodePage)
Definition at line 799 of file dbfopen.c.
References DBFCreateLL(), and SASetupDefaultHooks().
Referenced by DBFCloneEmpty(), and DBFCreate().
DBFCreateLL()
DBFHandle DBFCreateLL (const char * pszFilename, const char * pszCodePage, SAHooks * psHooks)
Definition at line 816 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, CONST_CAST, DBFGetLenWithoutExtension(), DBFSetLastModifiedDate(), DBFSetWriteEndOfFileChar(), FALSE, SAHooks::FClose, SAHooks::FOpen, DBFInfo::fp, SAHooks::FWrite, DBFInfo::iLanguageDriver, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SAHooks::Remove, DBFInfo::sHooks, SHPLIB_NULLPTR, STATIC_CAST, TRUE, and XBASE_FILEHDR_SZ.
Referenced by DBFCreateEx().
DBFDeleteField()
int DBFDeleteField (DBFHandle psDBF, int iField)
Definition at line 1957 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFInfo::bWriteEndOfFileChar, DBFFlushRecord(), DBFUpdateHeader(), END_OF_FILE_CHARACTER, FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SfRealloc(), DBFInfo::sHooks, STATIC_CAST, TRUE, and XBASE_FLDHDR_SZ.
DBFFlushRecord()
static int DBFFlushRecord (DBFHandle psDBF) static
Definition at line 358 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bWriteEndOfFileChar, END_OF_FILE_CHARACTER, SAHooks::Error, FALSE, DBFInfo::fp, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nCurrentRecord, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, DBFInfo::sHooks, STATIC_CAST, and TRUE.
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFClose(), DBFDeleteField(), DBFLoadRecord(), DBFReorderFields(), DBFUpdateHeader(), DBFWriteAttribute(), DBFWriteAttributeDirectly(), and DBFWriteTuple().
DBFGetCodePage()
const char* DBFGetCodePage (DBFHandle psDBF)
Definition at line 1943 of file dbfopen.c.
References SHPLIB_NULLPTR.
DBFGetFieldCount()
int DBFGetFieldCount (DBFHandle psDBF)
Definition at line 1372 of file dbfopen.c.
References DBFInfo::nFields.
Referenced by DBFGetFieldIndex().
DBFGetFieldIndex()
int DBFGetFieldIndex (DBFHandle psDBF, const char * pszFieldName)
Definition at line 1854 of file dbfopen.c.
References DBFGetFieldCount(), DBFGetFieldInfo(), name, SHPLIB_NULLPTR, STRCASECMP, and XBASE_FLDNAME_LEN_READ.
DBFGetFieldInfo()
DBFFieldType DBFGetFieldInfo (DBFHandle psDBF, int iField, char * pszFieldName, int * pnWidth, int * pnDecimals)
Definition at line 1400 of file dbfopen.c.
References FTDate, FTDouble, FTInteger, FTInvalid, FTLogical, FTString, DBFInfo::nFields, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldSize, DBFInfo::pszHeader, SHPLIB_NULLPTR, STATIC_CAST, XBASE_FLDHDR_SZ, and XBASE_FLDNAME_LEN_READ.
Referenced by DBFGetFieldIndex().
DBFGetLenWithoutExtension()
static int DBFGetLenWithoutExtension (const char * pszBasename) static
Definition at line 504 of file dbfopen.c.
References STATIC_CAST.
Referenced by DBFCreateLL(), and DBFOpenLL().
DBFGetNativeFieldType()
char DBFGetNativeFieldType (DBFHandle psDBF, int iField)
Definition at line 1836 of file dbfopen.c.
References DBFInfo::pachFieldType.
DBFGetNullCharacter()
static char DBFGetNullCharacter (char chType) static
Definition at line 946 of file dbfopen.c.
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), and DBFWriteAttribute().
DBFGetRecordCount()
int DBFGetRecordCount (DBFHandle psDBF)
Definition at line 1385 of file dbfopen.c.
References DBFInfo::nRecords.
DBFIsAttributeNULL()
int DBFIsAttributeNULL (DBFHandle psDBF, int iRecord, int iField)
Definition at line 1352 of file dbfopen.c.
References DBFIsValueNULL(), DBFReadStringAttribute(), DBFInfo::pachFieldType, SHPLIB_NULLPTR, and TRUE.
DBFIsRecordDeleted()
int DBFIsRecordDeleted (DBFHandle psDBF, int iShape)
Definition at line 1876 of file dbfopen.c.
References DBFLoadRecord(), FALSE, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, and TRUE.
DBFIsValueNULL()
static int DBFIsValueNULL (char chType, const char * pszValue) static
Definition at line 1303 of file dbfopen.c.
References FALSE, SHPLIB_NULLPTR, and TRUE.
Referenced by DBFAlterFieldDefn(), and DBFIsAttributeNULL().
DBFLoadRecord()
static int DBFLoadRecord (DBFHandle psDBF, int iRecord) static
Definition at line 400 of file dbfopen.c.
References DBFFlushRecord(), SAHooks::Error, FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, DBFInfo::nCurrentRecord, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::pszCurrentRecord, SEEK_SET, DBFInfo::sHooks, STATIC_CAST, and TRUE.
Referenced by DBFIsRecordDeleted(), DBFMarkRecordDeleted(), DBFReadAttribute(), DBFReadTuple(), DBFWriteAttribute(), DBFWriteAttributeDirectly(), and DBFWriteTuple().
DBFMarkRecordDeleted()
int DBFMarkRecordDeleted (DBFHandle psDBF, int iShape, int bIsDeleted)
Definition at line 1901 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bUpdated, DBFLoadRecord(), FALSE, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, and TRUE.
DBFOpen()
DBFHandle DBFOpen (const char * pszFilename, const char * pszAccess)
Definition at line 490 of file dbfopen.c.
References DBFOpenLL(), and SASetupDefaultHooks().
Referenced by DBFCloneEmpty().
DBFOpenLL()
DBFHandle DBFOpenLL (const char * pszFilename, const char * pszAccess, SAHooks * psHooks)
Definition at line 527 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFClose(), DBFGetLenWithoutExtension(), DBFSetLastModifiedDate(), DBFSetWriteEndOfFileChar(), FALSE, SAHooks::FClose, SAHooks::FOpen, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, HEADER_RECORD_TERMINATOR, DBFInfo::iLanguageDriver, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, REINTERPRET_CAST, SfRealloc(), DBFInfo::sHooks, SHPLIB_NULLPTR, STATIC_CAST, TRUE, XBASE_FILEHDR_SZ, and XBASE_FLDHDR_SZ.
Referenced by DBFOpen().
DBFReadAttribute()
static void* DBFReadAttribute (DBFHandle psDBF, int hEntity, int iField, char chReqType) static
Definition at line 1143 of file dbfopen.c.
References SAHooks::Atof, DBFLoadRecord(), DBFInfo::dfDoubleField, DBFInfo::fieldValue, DBFInfo::nFields, DBFInfo::nIntField, DBFInfo::nRecords, DBFInfo::nWorkFieldLength, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, DBFInfo::pszWorkField, REINTERPRET_CAST, DBFInfo::sHooks, SHPLIB_NULLPTR, and STATIC_CAST.
Referenced by DBFReadDoubleAttribute(), DBFReadIntegerAttribute(), DBFReadLogicalAttribute(), and DBFReadStringAttribute().
DBFReadDoubleAttribute()
double DBFReadDoubleAttribute (DBFHandle psDBF, int iRecord, int iField)
Definition at line 1257 of file dbfopen.c.
References DBFReadAttribute(), SHPLIB_NULLPTR, and STATIC_CAST.
DBFReadIntegerAttribute()
int DBFReadIntegerAttribute (DBFHandle psDBF, int iRecord, int iField)
Definition at line 1237 of file dbfopen.c.
References DBFReadAttribute(), SHPLIB_NULLPTR, and STATIC_CAST.
DBFReadLogicalAttribute()
const char* DBFReadLogicalAttribute (DBFHandle psDBF, int iRecord, int iField)
Definition at line 1290 of file dbfopen.c.
References DBFReadAttribute(), and STATIC_CAST.
DBFReadStringAttribute()
const char* DBFReadStringAttribute (DBFHandle psDBF, int iRecord, int iField)
Definition at line 1277 of file dbfopen.c.
References DBFReadAttribute(), and STATIC_CAST.
Referenced by DBFIsAttributeNULL().
DBFReadTuple()
const char* DBFReadTuple (DBFHandle psDBF, int hEntity)
Definition at line 1766 of file dbfopen.c.
References DBFLoadRecord(), SHPLIB_NULLPTR, and STATIC_CAST.
DBFReorderFields()
int DBFReorderFields (DBFHandle psDBF, int * panMap)
Definition at line 2084 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFFlushRecord(), DBFUpdateHeader(), FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszHeader, DBFInfo::sHooks, STATIC_CAST, TRUE, and XBASE_FLDHDR_SZ.
DBFSetLastModifiedDate()
void DBFSetLastModifiedDate (DBFHandle psDBF, int nYYSince1900, int nMM, int nDD)
Definition at line 476 of file dbfopen.c.
References DBFInfo::nUpdateDay, DBFInfo::nUpdateMonth, and DBFInfo::nUpdateYearSince1900.
Referenced by DBFCreateLL(), and DBFOpenLL().
DBFSetWriteEndOfFileChar()
void DBFSetWriteEndOfFileChar (DBFHandle psDBF, int bWriteFlag)
Definition at line 2432 of file dbfopen.c.
References DBFInfo::bWriteEndOfFileChar.
Referenced by DBFCreateLL(), and DBFOpenLL().
DBFUpdateHeader()
void DBFUpdateHeader (DBFHandle psDBF)
Definition at line 443 of file dbfopen.c.
References DBFInfo::bNoHeader, DBFFlushRecord(), DBFWriteHeader(), SAHooks::FFlush, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nRecords, DBFInfo::nUpdateDay, DBFInfo::nUpdateMonth, DBFInfo::nUpdateYearSince1900, DBFInfo::sHooks, STATIC_CAST, and XBASE_FILEHDR_SZ.
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFClose(), DBFDeleteField(), and DBFReorderFields().
DBFWriteAttribute()
static int DBFWriteAttribute (DBFHandle psDBF, int hEntity, int iField, void * pValue) static
Definition at line 1451 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, CPLsnprintf, DBFFlushRecord(), DBFGetNullCharacter(), DBFLoadRecord(), DBFWriteHeader(), FALSE, DBFInfo::nCurrentRecord, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, REINTERPRET_CAST, SHPLIB_NULLPTR, STATIC_CAST, TRUE, and XBASE_FLD_MAX_WIDTH.
Referenced by DBFWriteDoubleAttribute(), DBFWriteIntegerAttribute(), DBFWriteLogicalAttribute(), DBFWriteNULLAttribute(), and DBFWriteStringAttribute().
DBFWriteAttributeDirectly()
int DBFWriteAttributeDirectly (DBFHandle psDBF, int hEntity, int iField, void * pValue)
Definition at line 1572 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFFlushRecord(), DBFLoadRecord(), DBFWriteHeader(), FALSE, DBFInfo::nCurrentRecord, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, REINTERPRET_CAST, STATIC_CAST, and TRUE.
DBFWriteDoubleAttribute()
int DBFWriteDoubleAttribute (DBFHandle psDBF, int iRecord, int iField, double dValue)
Definition at line 1640 of file dbfopen.c.
References DBFWriteAttribute(), and STATIC_CAST.
DBFWriteHeader()
static void DBFWriteHeader (DBFHandle psDBF) static
Definition at line 290 of file dbfopen.c.
References DBFInfo::bNoHeader, DBFInfo::bWriteEndOfFileChar, END_OF_FILE_CHARACTER, FALSE, DBFInfo::fp, SAHooks::FSeek, SAHooks::FWrite, HEADER_RECORD_TERMINATOR, DBFInfo::iLanguageDriver, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::nUpdateDay, DBFInfo::nUpdateMonth, DBFInfo::nUpdateYearSince1900, DBFInfo::pszHeader, DBFInfo::sHooks, STATIC_CAST, XBASE_FILEHDR_SZ, and XBASE_FLDHDR_SZ.
Referenced by DBFCloneEmpty(), DBFClose(), DBFUpdateHeader(), DBFWriteAttribute(), DBFWriteAttributeDirectly(), and DBFWriteTuple().
DBFWriteIntegerAttribute()
int DBFWriteIntegerAttribute (DBFHandle psDBF, int iRecord, int iField, int nValue)
Definition at line 1654 of file dbfopen.c.
References DBFWriteAttribute(), and STATIC_CAST.
DBFWriteLogicalAttribute()
int DBFWriteLogicalAttribute (DBFHandle psDBF, int iRecord, int iField, const char lValue)
Definition at line 1697 of file dbfopen.c.
References CONST_CAST, DBFWriteAttribute(), and STATIC_CAST.
DBFWriteNULLAttribute()
int DBFWriteNULLAttribute (DBFHandle psDBF, int iRecord, int iField)
Definition at line 1684 of file dbfopen.c.
References DBFWriteAttribute(), and SHPLIB_NULLPTR.
DBFWriteStringAttribute()
int DBFWriteStringAttribute (DBFHandle psDBF, int iRecord, int iField, const char * pszValue)
Definition at line 1670 of file dbfopen.c.
References CONST_CAST, DBFWriteAttribute(), and STATIC_CAST.
DBFWriteTuple()
int DBFWriteTuple (DBFHandle psDBF, int hEntity, void * pRawTuple)
Definition at line 1711 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFFlushRecord(), DBFLoadRecord(), DBFWriteHeader(), FALSE, DBFInfo::nCurrentRecord, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, REINTERPRET_CAST, and TRUE.
SfRealloc()
static void* SfRealloc (void * pMem, int nNewSize) static
Definition at line 272 of file dbfopen.c.
References SHPLIB_NULLPTR.
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFDeleteField(), and DBFOpenLL().
Variable Documentation
cpl_cvsid
const char cpl_cvsid[] = "$Id$" static
Definition at line 232 of file dbfopen.c.