ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/debug.c File Reference
debug.c File Reference
#include "metis.h"
Functions
float ComputeRAsso (GraphType *graph, idxtype *where, int npart)
float ComputeNCut (GraphType *graph, idxtype *where, int npart)
int ComputeCut (GraphType *graph, idxtype *where)
int CheckBnd (GraphType *graph)
int CheckBnd2 (GraphType *graph)
int CheckNodeBnd (GraphType *graph, int onbnd)
int CheckRInfo (RInfoType *rinfo)
int CheckNodePartitionParams (GraphType *graph)
int IsSeparable (GraphType *graph)
Function Documentation
CheckBnd()
int CheckBnd (GraphType * graph)
Definition at line 145 of file debug.c.
References graphdef::adjncy, ASSERT, ASSERTP, graphdef::bndind, graphdef::bndptr, graphdef::nbnd, graphdef::nvtxs, graphdef::where, and graphdef::xadj.
CheckBnd2()
int CheckBnd2 (GraphType * graph)
Definition at line 181 of file debug.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, ASSERTP, graphdef::bndind, graphdef::bndptr, graphdef::nbnd, graphdef::nvtxs, graphdef::where, and graphdef::xadj.
CheckNodeBnd()
int CheckNodeBnd (GraphType * graph, int onbnd)
Definition at line 216 of file debug.c.
References graphdef::adjncy, ASSERTP, graphdef::bndind, graphdef::bndptr, graphdef::nvtxs, graphdef::where, and graphdef::xadj.
CheckNodePartitionParams()
int CheckNodePartitionParams (GraphType * graph)
Definition at line 269 of file debug.c.
References graphdef::adjncy, graphdef::adjwgt, nrinfodef::edegrees, graphdef::nrinfo, graphdef::nvtxs, graphdef::pwgts, graphdef::vwgt, graphdef::where, and graphdef::xadj.
CheckRInfo()
int CheckRInfo (RInfoType * rinfo)
Definition at line 252 of file debug.c.
References ASSERTP, rinfodef::edegrees, rinfodef::ndegrees, and edegreedef::pid.
ComputeCut()
int ComputeCut (GraphType * graph, idxtype * where)
Definition at line 119 of file debug.c.
References graphdef::adjncy, graphdef::adjwgt, NULL, graphdef::nvtxs, and graphdef::xadj.
ComputeNCut()
float ComputeNCut (GraphType * graph, idxtype * where, int npart)
Definition at line 67 of file debug.c.
References graphdef::adjncy, graphdef::adjwgt, idxsmalloc, NULL, graphdef::nvtxs, result, and graphdef::xadj.
Referenced by MLKKMRefine().
ComputeRAsso()
float ComputeRAsso (GraphType * graph, idxtype * where, int npart)
Definition at line 20 of file debug.c.
References graphdef::adjncy, graphdef::adjwgt, clusterSize(), idxsmalloc, NULL, graphdef::nvtxs, result, and graphdef::xadj.
Referenced by MLKKMRefine().
IsSeparable()
int IsSeparable (GraphType * graph)
Definition at line 316 of file debug.c.
References graphdef::adjncy, ASSERTP, graphdef::nvtxs, graphdef::where, and graphdef::xadj.