var dir_90fd98a0ba30abf7a6068a44995d2d6b =
[
    [ "AutoSegmentationTools.cpp", "core_2src_2AutoSegmentationTools_8cpp.html", null ],
    [ "ChamferDistanceTransform.cpp", "core_2src_2ChamferDistanceTransform_8cpp.html", "core_2src_2ChamferDistanceTransform_8cpp" ],
    [ "CloudSamplingTools.cpp", "core_2src_2CloudSamplingTools_8cpp.html", null ],
    [ "Console.cpp", "Console_8cpp.html", "Console_8cpp" ],
    [ "Cpu.cpp", "Cpu_8cpp.html", "Cpu_8cpp" ],
    [ "CPUInfo.cpp", "CPUInfo_8cpp.html", "CPUInfo_8cpp" ],
    [ "CVKdTree.cpp", "CVKdTree_8cpp.html", "CVKdTree_8cpp" ],
    [ "CVLog.cpp", "CVLog_8cpp.html", "CVLog_8cpp" ],
    [ "CVMiscTools.cpp", "CVMiscTools_8cpp.html", "CVMiscTools_8cpp" ],
    [ "CVShareable.cpp", "CVShareable_8cpp.html", null ],
    [ "CVTools.cpp", "CVTools_8cpp.html", null ],
    [ "Delaunay2dMesh.cpp", "Delaunay2dMesh_8cpp.html", null ],
    [ "DgmOctree.cpp", "core_2src_2DgmOctree_8cpp.html", "core_2src_2DgmOctree_8cpp" ],
    [ "DgmOctreeReferenceCloud.cpp", "core_2src_2DgmOctreeReferenceCloud_8cpp.html", null ],
    [ "DistanceComputationTools.cpp", "core_2src_2DistanceComputationTools_8cpp.html", "core_2src_2DistanceComputationTools_8cpp" ],
    [ "Eigen.cpp", "Eigen_8cpp.html", "Eigen_8cpp" ],
    [ "ErrorFunction.cpp", "core_2src_2ErrorFunction_8cpp.html", "core_2src_2ErrorFunction_8cpp" ],
    [ "FastMarching.cpp", "core_2src_2FastMarching_8cpp.html", null ],
    [ "FastMarchingForPropagation.cpp", "FastMarchingForPropagation_8cpp.html", null ],
    [ "FileSystem.cpp", "FileSystem_8cpp.html", "FileSystem_8cpp" ],
    [ "GeometricalAnalysisTools.cpp", "core_2src_2GeometricalAnalysisTools_8cpp.html", "core_2src_2GeometricalAnalysisTools_8cpp" ],
    [ "Helper.cpp", "Helper_8cpp.html", "Helper_8cpp" ],
    [ "IJsonConvertible.cpp", "IJsonConvertible_8cpp.html", "IJsonConvertible_8cpp" ],
    [ "IntersectionTest.cpp", "IntersectionTest_8cpp.html", null ],
    [ "LocalModel.cpp", "core_2src_2LocalModel_8cpp.html", [
      [ "LSLocalModel", "classLSLocalModel.html", "classLSLocalModel" ],
      [ "DelaunayLocalModel", "classDelaunayLocalModel.html", "classDelaunayLocalModel" ],
      [ "QuadricLocalModel", "classQuadricLocalModel.html", "classQuadricLocalModel" ]
    ] ],
    [ "Logging.cpp", "Logging_8cpp.html", "Logging_8cpp" ],
    [ "ManualSegmentationTools.cpp", "core_2src_2ManualSegmentationTools_8cpp.html", "core_2src_2ManualSegmentationTools_8cpp" ],
    [ "MemoryInfo.cpp", "MemoryInfo_8cpp.html", "MemoryInfo_8cpp" ],
    [ "MeshSamplingTools.cpp", "MeshSamplingTools_8cpp.html", null ],
    [ "Neighbourhood.cpp", "Neighbourhood_8cpp.html", null ],
    [ "NormalDistribution.cpp", "core_2src_2NormalDistribution_8cpp.html", null ],
    [ "NormalizedProgress.cpp", "NormalizedProgress_8cpp.html", [
      [ "AtomicCounter", "classAtomicCounter.html", "classAtomicCounter" ]
    ] ],
    [ "OrientedBoundingBox.cpp", "OrientedBoundingBox_8cpp.html", null ],
    [ "Parallel.cpp", "Parallel_8cpp.html", "Parallel_8cpp" ],
    [ "PointProjectionTools.cpp", "core_2src_2PointProjectionTools_8cpp.html", "core_2src_2PointProjectionTools_8cpp" ],
    [ "Polyline.cpp", "core_2src_2Polyline_8cpp.html", null ],
    [ "ReferenceCloud.cpp", "core_2src_2ReferenceCloud_8cpp.html", null ],
    [ "RegistrationTools.cpp", "core_2src_2RegistrationTools_8cpp.html", "core_2src_2RegistrationTools_8cpp" ],
    [ "SaitoSquaredDistanceTransform.cpp", "SaitoSquaredDistanceTransform_8cpp.html", null ],
    [ "ScalarField.cpp", "core_2src_2ScalarField_8cpp.html", null ],
    [ "ScalarFieldTools.cpp", "core_2src_2ScalarFieldTools_8cpp.html", "core_2src_2ScalarFieldTools_8cpp" ],
    [ "SimpleMesh.cpp", "core_2src_2SimpleMesh_8cpp.html", null ],
    [ "StaticVector.cpp", "StaticVector_8cpp.html", "StaticVector_8cpp" ],
    [ "StatisticalTestingTools.cpp", "core_2src_2StatisticalTestingTools_8cpp.html", "core_2src_2StatisticalTestingTools_8cpp" ],
    [ "Timer.cpp", "Timer_8cpp.html", null ],
    [ "TrueKdTree.cpp", "core_2src_2TrueKdTree_8cpp.html", "core_2src_2TrueKdTree_8cpp" ],
    [ "Universe.cpp", "Universe_8cpp.html", null ],
    [ "WeibullDistribution.cpp", "core_2src_2WeibullDistribution_8cpp.html", "core_2src_2WeibullDistribution_8cpp" ]
];