ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qSRA/src/distanceMapGenerationDlg.cpp File Reference
distanceMapGenerationDlg.cpp File Reference
#include "distanceMapGenerationDlg.h"
#include "ccMapWindow.h"
#include "ccSymbolCloud.h"
#include "dxfProfilesExportDlg.h"
#include "dxfProfilesExporter.h"
#include <ecvMainAppInterface.h>
#include <ecvColorScaleEditorDlg.h>
#include <ecvColorScaleSelector.h>
#include <ecvColorScalesManager.h>
#include <ecvRenderToFileDlg.h>
#include <ecvQtHelpers.h>
#include <QtCompat.h>
#include <ecvDisplayTools.h>
#include <ecvFileUtils.h>
#include <ecvPlane.h>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include <ecvScalarField.h>
#include <QColorDialog>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFontMetrics>
#include <QHBoxLayout>
#include <QLocale>
#include <QMainWindow>
#include <QProgressDialog>
#include <QSettings>
#include <QTextStream>
#include <assert.h>
Functions
static double ConvertAngleFromRad (double angle_rad, DistanceMapGenerationDlg::ANGULAR_UNIT destUnit)
static double ConvertAngleToRad (double angle, DistanceMapGenerationDlg::ANGULAR_UNIT srcUnit)
static void SetSpinBoxValues (QDoubleSpinBox *spinBox, int decimals, double minVal, double maxVal, double step, double value)
Variables
static const char XLABEL_CLOUD_NAME [] = "X_Labels"
static const char YLABEL_CLOUD_NAME [] = "Y_Labels"
static const double DEFAULT_LABEL_MARGIN
Function Documentation
ConvertAngleFromRad()
static double ConvertAngleFromRad (double angle_rad, DistanceMapGenerationDlg::ANGULAR_UNIT destUnit) static
Definition at line 62 of file distanceMapGenerationDlg.cpp.
References DistanceMapGenerationDlg::ANG_DEG, DistanceMapGenerationDlg::ANG_GRAD, DistanceMapGenerationDlg::ANG_RAD, M_PI, and cloudViewer::RadiansToDegrees().
Referenced by DistanceMapGenerationDlg::exportMapAsGrid(), DistanceMapGenerationDlg::exportProfilesAsDXF(), DistanceMapGenerationDlg::getSpinboxAngularValue(), DistanceMapGenerationDlg::toggleOverlayGrid(), and DistanceMapGenerationDlg::updateMinAndMaxLimits().
ConvertAngleToRad()
static double ConvertAngleToRad (double angle, DistanceMapGenerationDlg::ANGULAR_UNIT srcUnit) static
Definition at line 78 of file distanceMapGenerationDlg.cpp.
References DistanceMapGenerationDlg::ANG_DEG, DistanceMapGenerationDlg::ANG_GRAD, DistanceMapGenerationDlg::ANG_RAD, cloudViewer::DegreesToRadians(), and M_PI.
Referenced by DistanceMapGenerationDlg::getSpinboxAngularValue().
SetSpinBoxValues()
static void SetSpinBoxValues (QDoubleSpinBox * spinBox, int decimals, double minVal, double maxVal, double step, double value) static
Definition at line 869 of file distanceMapGenerationDlg.cpp.
Referenced by DistanceMapGenerationDlg::angularUnitChanged().
Variable Documentation
DEFAULT_LABEL_MARGIN
const double DEFAULT_LABEL_MARGIN static
Initial value:
=
        20.0
Definition at line 59 of file distanceMapGenerationDlg.cpp.
Referenced by DistanceMapGenerationDlg::DistanceMapGenerationDlg().
XLABEL_CLOUD_NAME
const char XLABEL_CLOUD_NAME[] = "X_Labels" static
Definition at line 57 of file distanceMapGenerationDlg.cpp.
Referenced by DistanceMapGenerationDlg::DistanceMapGenerationDlg().
YLABEL_CLOUD_NAME
const char YLABEL_CLOUD_NAME[] = "Y_Labels" static
Definition at line 58 of file distanceMapGenerationDlg.cpp.
Referenced by DistanceMapGenerationDlg::DistanceMapGenerationDlg().