ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qSRA/src/distanceMapGenerationTool.cpp File Reference
distanceMapGenerationTool.cpp File Reference
#include "distanceMapGenerationTool.h"
#include <ecvMainAppInterface.h>
#include <ecvMesh.h>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <Delaunay2dMesh.h>
#include <QFile>
#include <QMainWindow>
#include <QtCompat.h>
Functions
static double ComputeLatitude_rad (PointCoordinateType x, PointCoordinateType y, PointCoordinateType z)
static bool GetPolylineMetaVector (const ccPolyline *polyline, const QString &key, CCVector3 &P)
static void SetPoylineMetaVector (ccPolyline *polyline, const QString &key, const CCVector3 &P)
Variables
const char PROFILE_ORIGIN_KEY [] = "ProfileOrigin"
const char REVOLUTION_AXIS_KEY [] = "RevolutionAxis"
const char PROFILE_HEIGHT_SHIFT_KEY [] = "ProfileHeightShift"
static const double M_PI_DIV_2 = M_PI / 2
static const double M_PI_DIV_4 = M_PI / 4
Function Documentation
ComputeLatitude_rad()
static double ComputeLatitude_rad (PointCoordinateType x, PointCoordinateType y, PointCoordinateType z) inline static
Definition at line 41 of file distanceMapGenerationTool.cpp.
References M_PI_DIV_2.
Referenced by DistanceMapGenerationTool::ComputeMinAndMaxLatitude_rad(), DistanceMapGenerationTool::ConvertCloudToConical(), and DistanceMapGenerationTool::CreateMap().
GetPolylineMetaVector()
static bool GetPolylineMetaVector (const ccPolyline * polyline, const QString & key, CCVector3 & P) static
Definition at line 54 of file distanceMapGenerationTool.cpp.
References ccObject::getMetaData(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by DistanceMapGenerationTool::GetPoylineAxis(), and DistanceMapGenerationTool::GetPoylineOrigin().
SetPoylineMetaVector()
static void SetPoylineMetaVector (ccPolyline * polyline, const QString & key, const CCVector3 & P) static
Definition at line 76 of file distanceMapGenerationTool.cpp.
References ccObject::setMetaData(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by DistanceMapGenerationTool::SetPoylineAxis(), and DistanceMapGenerationTool::SetPoylineOrigin().
Variable Documentation
M_PI_DIV_2
const double M_PI_DIV_2 = M_PI / 2 static
Definition at line 37 of file distanceMapGenerationTool.cpp.
Referenced by ComputeLatitude_rad(), DistanceMapGenerationTool::ConicalProject(), and DistanceMapGenerationTool::ConicalProjectN().
M_PI_DIV_4
const double M_PI_DIV_4 = M_PI / 4 static
Definition at line 38 of file distanceMapGenerationTool.cpp.
Referenced by DistanceMapGenerationTool::ConicalProject(), and DistanceMapGenerationTool::ConicalProjectN().
PROFILE_HEIGHT_SHIFT_KEY
const char PROFILE_HEIGHT_SHIFT_KEY[] = "ProfileHeightShift"
Definition at line 34 of file distanceMapGenerationTool.cpp.
Referenced by DistanceMapGenerationTool::GetPolylineHeightShift(), and DistanceMapGenerationTool::SetPolylineHeightShift().
PROFILE_ORIGIN_KEY
const char PROFILE_ORIGIN_KEY[] = "ProfileOrigin"
Definition at line 30 of file distanceMapGenerationTool.cpp.
Referenced by DistanceMapGenerationTool::GetPoylineOrigin(), and DistanceMapGenerationTool::SetPoylineOrigin().
REVOLUTION_AXIS_KEY
const char REVOLUTION_AXIS_KEY[] = "RevolutionAxis"
Definition at line 32 of file distanceMapGenerationTool.cpp.
Referenced by DistanceMapGenerationTool::GetPoylineAxis(), DistanceMapGenerationTool::GetPoylineRevolDim(), DistanceMapGenerationTool::SetPoylineAxis(), and DistanceMapGenerationTool::SetPoylineRevolDim().