ACloudViewer: /root/ACloudViewer/plugins/core/IO/qDracoIO/src/DRCFilter.cpp File Reference
DRCFilter.cpp File Reference
#include "../include/DRCFilter.h"
#include "../include/SaveDracoFileDlg.h"
#include <CVLog.h>
#include <ecvMaterialSet.h>
#include <ecvMesh.h>
#include <ecvPointCloud.h>
#include <ecvScalarField.h>
#include <CVPlatform.h>
#include <draco/compression/decode.h>
#include <draco/compression/encode.h>
#include <draco/mesh/mesh.h>
#include <draco/point_cloud/point_cloud.h>
Functions
static CC_FILE_ERROR CCCloudToDraco (const ccGenericPointCloud &ccCloud, draco::PointCloud &dracoCloud)
static CC_FILE_ERROR CCMeshToDraco (ccGenericMesh &ccMesh, draco::Mesh &dracoMesh)
static CC_FILE_ERROR LoadCloud (ccPointCloud &ccCloud, const draco::PointCloud &dracoCloud, FileIOFilter::LoadParameters &parameters)
Function Documentation
CCCloudToDraco()
static CC_FILE_ERROR CCCloudToDraco (const ccGenericPointCloud & ccCloud, draco::PointCloud & dracoCloud) static
Definition at line 48 of file DRCFilter.cpp.
References CC_FERR_NO_ERROR, CC_FERR_NOT_ENOUGH_MEMORY, cloudViewer::ScalarField::getName(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudViewer::GenericIndexedCloud::getPoint(), ccGenericPointCloud::getPointColor(), ccGenericPointCloud::getPointNormal(), cloudViewer::GenericCloud::getPointScalarValue(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::ScalarField::getValue(), ccDrawableObject::hasColors(), ccDrawableObject::hasNormals(), ccDrawableObject::hasScalarFields(), ccObject::isA(), ccShiftedObject::isShifted(), CV_TYPES::POINT_CLOUD, ecvColor::RgbTpl< Type >::rgb, cloudViewer::GenericCloud::size(), ccShiftedObject::toGlobal3d(), Tuple3Tpl< Type >::u, and CVLog::Warning().
Referenced by CCMeshToDraco(), and DRCFilter::saveToFile().
CCMeshToDraco()
static CC_FILE_ERROR CCMeshToDraco (ccGenericMesh & ccMesh, draco::Mesh & dracoMesh) static
Definition at line 192 of file DRCFilter.cpp.
References CC_FERR_BAD_ARGUMENT, CC_FERR_NO_ERROR, CCCloudToDraco(), error(), face, ccMesh::getAssociatedCloud(), ccMesh::getTexCoordinatesTable(), ccMesh::getTriangleVertIndexes(), cloudViewer::GenericCloud::size(), size, ccMesh::size(), and CVLog::Warning().
Referenced by DRCFilter::saveToFile().
LoadCloud()
static CC_FILE_ERROR LoadCloud (ccPointCloud & ccCloud, const draco::PointCloud & dracoCloud, FileIOFilter::LoadParameters & parameters) static
Definition at line 339 of file DRCFilter.cpp.
References cloudViewer::ScalarField::addElement(), ccPointCloud::addNorm(), cloudViewer::PointCloudTpl< T >::addPoint(), ccPointCloud::addRGBColor(), ccPointCloud::addScalarField(), CC_FERR_MALFORMED_FILE, CC_FERR_NO_ERROR, CC_FERR_NO_LOAD, CC_FERR_NOT_ENOUGH_MEMORY, CC_FERR_THIRD_PARTY_LIB_FAILURE, ccScalarField::computeMinAndMax(), Vector3Tpl< float >::fromArray(), FileIOFilter::HandleGlobalShift(), ccPointCloud::reserve(), cloudViewer::ScalarField::reserveSafe(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveTheRGBTable(), ccPointCloud::setCurrentDisplayedScalarField(), ccShiftedObject::setGlobalShift(), ccDrawableObject::showColors(), ccDrawableObject::showNormals(), ccDrawableObject::showSF(), Tuple3Tpl< Type >::u, CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by DRCFilter::loadFile().