ACloudViewer: /root/ACloudViewer/libs/CV_db/src/ecv2DLabel.cpp File Reference
ecv2DLabel.cpp File Reference
#include "ecv2DLabel.h"
#include "ecvBasicTypes.h"
#include "ecvDisplayTools.h"
#include "ecvFacet.h"
#include "ecvGenericPointCloud.h"
#include "ecvHObjectCaster.h"
#include "ecvPointCloud.h"
#include "ecvPolyline.h"
#include "ecvScalarField.h"
#include "ecvSphere.h"
#include <QApplication>
#include <QScreen>
#include <QSharedPointer>
#include <QtCompat.h>
#include <assert.h>
#include <string.h>
#include <algorithm>
Classes
struct Tab
Data table.
Macros
#define DRAW_CONTENT_AS_TAB
Functions
static QSharedPointer< ccSphere > c_unitPointMarker (nullptr)
static QSharedPointer< ccFacet > c_unitTriMarker (nullptr)
void AddPointCoordinates (QStringList &body, unsigned pointIndex, ccGenericPointCloud *cloud, int precision, QString pointName=QString())
Variables
static const QString MathSymbolDelta = "D"
static const QString SEPARATOR = "-"
static const QString CENTER_STRING = QObject::tr("Center")
static const char POINT_INDEX_0 [] = "pi0"
static const char POINT_INDEX_1 [] = "pi1"
static const char POINT_INDEX_2 [] = "pi2"
static const char ENTITY_INDEX_0 [] = "ei0"
static const char ENTITY_INDEX_1 [] = "ei1"
static const char ENTITY_INDEX_2 [] = "ei2"
static const int c_margin = 5
static const int c_tabMarginX = 5
static const int c_tabMarginY = 2
static const int c_arrowBaseSize = 3
static const ecvColor::Rgb c_darkGreen (0, 200, 0)
Macro Definition Documentation
DRAW_CONTENT_AS_TAB
#define DRAW_CONTENT_AS_TAB
Function Documentation
AddPointCoordinates()
void AddPointCoordinates (QStringList & body, unsigned pointIndex, ccGenericPointCloud * cloud, int precision, QString pointName = QString())
Definition at line 567 of file ecv2DLabel.cpp.
References cloudViewer::GenericIndexedCloudPersist::getPointPersistentPtr(), ccShiftedObject::isShifted(), ccShiftedObject::toGlobal3d(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by cc2DLabel::getLabelContent().
c_unitPointMarker()
static QSharedPointer<ccSphere> c_unitPointMarker (nullptr) static
Referenced by cc2DLabel::cc2DLabel(), cc2DLabel::clear3Dviews(), and cc2DLabel::drawMeOnly3D().
c_unitTriMarker()
static QSharedPointer<ccFacet> c_unitTriMarker (nullptr) static
Referenced by cc2DLabel::cc2DLabel(), cc2DLabel::clear3Dviews(), and cc2DLabel::drawMeOnly3D().
Variable Documentation
c_arrowBaseSize
const int c_arrowBaseSize = 3 static
Definition at line 1111 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::drawMeOnly2D().
c_darkGreen
const ecvColor::Rgb c_darkGreen(0, 200, 0) (0 , 200 , 0) static
c_margin
const int c_margin = 5 static
Definition at line 1108 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::drawMeOnly2D(), and DxfProfilesExporter::SaveHorizontalProfiles().
c_tabMarginX
const int c_tabMarginX = 5 static
Definition at line 1109 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::drawMeOnly2D().
c_tabMarginY
const int c_tabMarginY = 2 static
Definition at line 1110 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::drawMeOnly2D().
CENTER_STRING
const QString CENTER_STRING = QObject::tr("Center") static
Definition at line 43 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::PickedPoint::itemTitle(), and cc2DLabel::PickedPoint::prefix().
ENTITY_INDEX_0
const char ENTITY_INDEX_0[] = "ei0" static
Definition at line 47 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::getName(), and cc2DLabel::updateName().
ENTITY_INDEX_1
const char ENTITY_INDEX_1[] = "ei1" static
Definition at line 48 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::getName(), and cc2DLabel::updateName().
ENTITY_INDEX_2
const char ENTITY_INDEX_2[] = "ei2" static
Definition at line 49 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::getName(), and cc2DLabel::updateName().
MathSymbolDelta
const QString MathSymbolDelta = "D" static
Definition at line 36 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::drawMeOnly2D(), and cc2DLabel::getLabelContent().
POINT_INDEX_0
const char POINT_INDEX_0[] = "pi0" static
Definition at line 44 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::getName(), cc2DLabel::getTitle(), and cc2DLabel::updateName().
POINT_INDEX_1
const char POINT_INDEX_1[] = "pi1" static
Definition at line 45 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::getName(), and cc2DLabel::updateName().
POINT_INDEX_2
const char POINT_INDEX_2[] = "pi2" static
Definition at line 46 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::getName(), and cc2DLabel::updateName().
SEPARATOR
const QString SEPARATOR = "-" static
Definition at line 37 of file ecv2DLabel.cpp.
Referenced by cc2DLabel::cc2DLabel(), and cc2DLabel::drawMeOnly3D().