ACloudViewer: /root/ACloudViewer/app/ecvBoundingBoxEditorDlg.cpp File Reference
ecvBoundingBoxEditorDlg.cpp File Reference
#include "ecvBoundingBoxEditorDlg.h"
#include <limits>
#include <QClipboard>
Functions
void MakeSquare (ccBBox &box, int pivotType, int defaultDim=-1)
Variables
static ccBBox s_lastBBox
Function Documentation
MakeSquare()
void MakeSquare (ccBBox & box, int pivotType, int defaultDim = -1)
Definition at line 131 of file ecvBoundingBoxEditorDlg.cpp.
References cloudViewer::BoundingBoxTpl< T >::getCenter(), cloudViewer::BoundingBoxTpl< T >::getDiagVec(), cloudViewer::BoundingBoxTpl< T >::maxCorner(), cloudViewer::BoundingBoxTpl< T >::minCorner(), Tuple3Tpl< Type >::u, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccBoundingBoxEditorDlg::squareModeActivated(), ccBoundingBoxEditorDlg::updateXWidth(), ccBoundingBoxEditorDlg::updateYWidth(), and ccBoundingBoxEditorDlg::updateZWidth().
Variable Documentation
s_lastBBox
ccBBox s_lastBBox static
Definition at line 17 of file ecvBoundingBoxEditorDlg.cpp.
Referenced by ccBoundingBoxEditorDlg::ccBoundingBoxEditorDlg(), ccBoundingBoxEditorDlg::resetToLast(), and ccBoundingBoxEditorDlg::saveBoxAndAccept().