ACloudViewer: /root/ACloudViewer/libs/CV_db/src/ecvColorScale.cpp File Reference
ecvColorScale.cpp File Reference
#include "ecvColorScale.h"
#include <QUuid>
#include <QXmlStreamReader>
#include <QXmlStreamWriter>
#include <QtCompat.h>
#include <CVGeom.h>
#include <CVLog.h>
#include "ecvObject.h"
Functions
static const QString s_xmlACloudViewer ("ACloudViewer")
static const QString s_xmlCloudCompare ("CloudCompare")
static const QString s_xmlColorScaleTitle ("ColorScale")
static const QString s_xmlColorScaleProperties ("Properties")
static const QString s_xmlColorScaleData ("Data")
Variables
constexpr int s_xmlColorScaleVer = 1
Function Documentation
s_xmlACloudViewer()
static const QString s_xmlACloudViewer ("ACloudViewer") static
Referenced by ccColorScale::LoadFromXML(), CommandCrossSection::process(), and ccColorScale::saveAsXML().
s_xmlCloudCompare()
static const QString s_xmlCloudCompare ("CloudCompare") static
Referenced by ccColorScale::LoadFromXML(), and CommandCrossSection::process().
s_xmlColorScaleData()
static const QString s_xmlColorScaleData ("Data") static
Referenced by ccColorScale::LoadFromXML(), and ccColorScale::saveAsXML().
s_xmlColorScaleProperties()
static const QString s_xmlColorScaleProperties ("Properties") static
Referenced by ccColorScale::LoadFromXML(), and ccColorScale::saveAsXML().
s_xmlColorScaleTitle()
static const QString s_xmlColorScaleTitle ("ColorScale") static
Referenced by ccColorScale::LoadFromXML(), and ccColorScale::saveAsXML().
Variable Documentation
s_xmlColorScaleVer
constexpr int s_xmlColorScaleVer = 1 constexpr
Definition at line 30 of file ecvColorScale.cpp.
Referenced by ccColorScale::LoadFromXML(), and ccColorScale::saveAsXML().