ACloudViewer: /root/ACloudViewer/libs/CV_db/src/ecvClipBox.cpp File Reference
ecvClipBox.cpp File Reference
#include "ecvClipBox.h"
#include "ecvCone.h"
#include "ecvCylinder.h"
#include "ecvDisplayTools.h"
#include "ecvHObjectCaster.h"
#include "ecvSphere.h"
#include "ecvTorus.h"
#include <cassert>
Functions
static QSharedPointer< ccCylinder > c_arrowShaft (nullptr)
static QSharedPointer< ccCone > c_arrowHead (nullptr)
static QSharedPointer< ccSphere > c_centralSphere (nullptr)
static QSharedPointer< ccTorus > c_torus (nullptr)
void DrawUnitArrow (int ID, const CCVector3 &start, const CCVector3 &direction, PointCoordinateType scale, const ecvColor::Rgb &col, CC_DRAW_CONTEXT &context)
static void DrawUnitTorus (int ID, const CCVector3 &center, const CCVector3 &direction, PointCoordinateType scale, const ecvColor::Rgb &col, CC_DRAW_CONTEXT &context)
static void DrawUnitCross (int ID, const CCVector3 &center, PointCoordinateType scale, const ecvColor::Rgb &col, CC_DRAW_CONTEXT &context)
static CCVector3d PointToVector (int x, int y, int screenWidth, int screenHeight)
Variables
const ColorCompType c_lightComp = ecvColor::MAX / 2
const ecvColor::Rgb c_lightRed (ecvColor::MAX, c_lightComp, c_lightComp)
const ecvColor::Rgb c_lightGreen (c_lightComp, ecvColor::MAX, c_lightComp)
const ecvColor::Rgb c_lightBlue (c_lightComp, c_lightComp, ecvColor::MAX)
Function Documentation
c_arrowHead()
static QSharedPointer<ccCone> c_arrowHead (nullptr) static
Referenced by DrawUnitArrow().
c_arrowShaft()
static QSharedPointer<ccCylinder> c_arrowShaft (nullptr) static
Referenced by DrawUnitArrow().
c_centralSphere()
static QSharedPointer<ccSphere> c_centralSphere (nullptr) static
c_torus()
static QSharedPointer<ccTorus> c_torus (nullptr) static
Referenced by DrawUnitTorus().
DrawUnitArrow()
void DrawUnitArrow (int ID, const CCVector3 & start, const CCVector3 & direction, PointCoordinateType scale, const ecvColor::Rgb & col, CC_DRAW_CONTEXT & context)
Definition at line 26 of file ecvClipBox.cpp.
References c_arrowHead(), c_arrowShaft(), context, Vector3Tpl< Type >::cross(), ccClipBox::CROSS, Vector3Tpl< Type >::dot(), cloudViewer::RadiansToDegrees(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccClipBox::drawMeOnly(), and DrawUnitCross().
DrawUnitCross()
static void DrawUnitCross (int ID, const CCVector3 & center, PointCoordinateType scale, const ecvColor::Rgb & col, CC_DRAW_CONTEXT & context) static
Definition at line 195 of file ecvClipBox.cpp.
References context, and DrawUnitArrow().
Referenced by ccClipBox::drawMeOnly().
DrawUnitTorus()
static void DrawUnitTorus (int ID, const CCVector3 & center, const CCVector3 & direction, PointCoordinateType scale, const ecvColor::Rgb & col, CC_DRAW_CONTEXT & context) static
Definition at line 102 of file ecvClipBox.cpp.
References c_torus(), context, Vector3Tpl< Type >::cross(), Vector3Tpl< Type >::dot(), M_PI, cloudViewer::RadiansToDegrees(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by ccClipBox::drawMeOnly().
PointToVector()
static CCVector3d PointToVector (int x, int y, int screenWidth, int screenHeight) static
Definition at line 432 of file ecvClipBox.cpp.
References Tuple3Tpl< Type >::x, x, Tuple3Tpl< Type >::y, y, and Tuple3Tpl< Type >::z.
Referenced by ccClipBox::move2D(), and ccClipBox::setClickedPoint().
Variable Documentation
c_lightBlue
const ecvColor::Rgb c_lightBlue(c_lightComp, c_lightComp, ecvColor::MAX) (c_lightComp , c_lightComp , ecvColor::MAX)
Referenced by ccClipBox::drawMeOnly().
c_lightComp
const ColorCompType c_lightComp = ecvColor::MAX / 2
Definition at line 712 of file ecvClipBox.cpp.
c_lightGreen
const ecvColor::Rgb c_lightGreen(c_lightComp, ecvColor::MAX, c_lightComp) (c_lightComp , ecvColor::MAX , c_lightComp)
Referenced by ccClipBox::drawMeOnly().
c_lightRed
const ecvColor::Rgb c_lightRed(ecvColor::MAX, c_lightComp, c_lightComp) (ecvColor::MAX , c_lightComp , c_lightComp)
Referenced by ccClipBox::drawMeOnly().