ACloudViewer: /root/ACloudViewer/app/ecvConsole.cpp File Reference
ecvConsole.cpp File Reference
#include "ecvConsole.h"
#include "MainWindow.h"
#include "ecvHead.h"
#include "ecvPersistentSettings.h"
#include "ecvSettingManager.h"
#include <ecvSingleton.h>
#include <CommonSettings.h>
#include <ecvOptions.h>
#include <QtCompat.h>
#include <QApplication>
#include <QClipboard>
#include <QColor>
#include <QDateTime>
#include <QDir>
#include <QFileInfo>
#include <QKeyEvent>
#include <QMessageBox>
#include <QStandardPaths>
#include <QThread>
#include <QTime>
#include <cassert>
#include <unistd.h>
Functions
void myMessageOutput (QtMsgType type, const QMessageLogContext &context, const QString &msg)
Variables
static ecvSingleton< ecvConsole > s_console
Function Documentation
myMessageOutput()
void myMessageOutput (QtMsgType type, const QMessageLogContext & context, const QString & msg)
Definition at line 109 of file ecvConsole.cpp.
References context, QtCompat::endl(), CVLog::PrintDebug(), ecvConsole::QtMessagesEnabled(), type, and CVLog::Warning().
Referenced by ecvConsole::Init().
Variable Documentation
s_console
ecvSingleton<ecvConsole> s_console static
Definition at line 55 of file ecvConsole.cpp.
Referenced by ecvConsole::Init(), ecvConsole::ReleaseInstance(), and ecvConsole::TheInstance().