ACloudViewer: /root/ACloudViewer/app/db_tree/ecvDBRoot.cpp File Reference
ecvDBRoot.cpp File Reference
#include "ecvDBRoot.h"
#include <QtCompat.h>
#include <QApplication>
#include <QHeaderView>
#include <QInputDialog>
#include <QMenu>
#include <QMessageBox>
#include <QMimeData>
#include <QSettings>
#include <QStandardItemModel>
#include <QTreeView>
#include "MainWindow.h"
#include "ecvProgressDialog.h"
#include "ecvPropertiesTreeDelegate.h"
#include "ecvSelectChildrenDlg.h"
#include <CVLog.h>
#include <CVMiscTools.h>
#include <ecv2DLabel.h>
#include <ecv2DViewportLabel.h>
#include <ecvDisplayTools.h>
#include <ecvFacet.h>
#include <ecvGBLSensor.h>
#include <ecvGenericPointCloud.h>
#include <ecvGenericPrimitive.h>
#include <ecvHObject.h>
#include <ecvHObjectCaster.h>
#include <ecvImage.h>
#include <ecvMaterialSet.h>
#include <ecvMesh.h>
#include <ecvPlane.h>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include <ecvScalarField.h>
#include <ecvPickOneElementDlg.h>
#include <algorithm>
#include <cassert>
#include <cstring>
Classes
class DBRootIcons
Functions
static bool CanDetachCloud (const ccHObject *obj)
Variables
static const int c_propViewLeftColumnWidth = 115
Function Documentation
CanDetachCloud()
static bool CanDetachCloud (const ccHObject * obj) static
Definition at line 63 of file ecvDBRoot.cpp.
References cloudViewer::ReferenceCloud::getAssociatedCloud(), ccGenericMesh::getAssociatedCloud(), ccHObject::getParent(), ccObject::isKindOf(), CV_TYPES::MESH, CV_TYPES::POLY_LINE, ccHObjectCaster::ToGenericMesh(), and ccHObjectCaster::ToPolyline().
Referenced by ccDBRoot::deleteSelectedEntities(), and ccDBRoot::flags().
Variable Documentation
c_propViewLeftColumnWidth
const int c_propViewLeftColumnWidth = 115 static
Definition at line 60 of file ecvDBRoot.cpp.
Referenced by ccDBRoot::showPropertiesView().