ACloudViewer: /root/ACloudViewer/libs/CV_db/src/ecvFastMarchingForNormsDirection.cpp File Reference
ecvFastMarchingForNormsDirection.cpp File Reference
#include "ecvFastMarchingForNormsDirection.h"
#include "CVLog.h"
#include "ecvGenericPointCloud.h"
#include "ecvNormalVectors.h"
#include "ecvOctree.h"
#include "ecvPointCloud.h"
#include "ecvProgressDialog.h"
#include <cassert>
Functions
static CCVector3 ComputeRobustAverageNorm (cloudViewer::ReferenceCloud *subset, ccGenericPointCloud *sourceCloud)
Function Documentation
ComputeRobustAverageNorm()
static CCVector3 ComputeRobustAverageNorm (cloudViewer::ReferenceCloud * subset, ccGenericPointCloud * sourceCloud) static
Definition at line 27 of file ecvFastMarchingForNormsDirection.cpp.
References Vector3Tpl< Type >::dot(), cloudViewer::ReferenceCloud::getAssociatedCloud(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), ccGenericPointCloud::getPointNormal(), ccDrawableObject::hasNormals(), Vector3Tpl< Type >::normalize(), cloudViewer::ReferenceCloud::size(), and sourceCloud.
Referenced by ccFastMarchingForNormsDirection::init().