ACloudViewer: /root/ACloudViewer/libs/eCV_db/include/ecvGLMatrix.h File Reference
ecvGLMatrix.h File Reference
#include "eCV_db.h"
#include "ecvGLMatrixTpl.h"
#include <Eigen.h>
#include <SquareMatrix.h>
Classes
class ccGLMatrix
Float version of ccGLMatrixTpl.
class ccGLMatrixd
Double version of ccGLMatrixTpl.
Functions
template<typename Tin , typename Tout >
ccGLMatrixTpl< Tout > FromCCLibMatrix (const cloudViewer::SquareMatrixTpl< Tin > &R, const Vector3Tpl< Tin > &Tr)
Constructor from a 3x3 rotation matrix R and a vector Tr.
template<typename Tin , typename Tout >
ccGLMatrixTpl< Tout > FromCCLibMatrix (const cloudViewer::SquareMatrixTpl< Tin > &R, const Vector3Tpl< Tin > &Tr, Tin S)
Constructor from a 3x3 rotation matrix R, a vector Tr, a scale S.
template<typename Tin , typename Tout >
ccGLMatrixTpl< Tout > FromCCLibMatrix (const cloudViewer::SquareMatrixTpl< Tin > &R, const Vector3Tpl< Tin > &Tr, const Vector3Tpl< Tin > &rotCenter)
Function Documentation
FromCCLibMatrix() [1/3]
template<typename Tin , typename Tout > ccGLMatrixTpl<Tout> FromCCLibMatrix (const cloudViewer::SquareMatrixTpl< Tin > & R, const Vector3Tpl< Tin > & Tr)
Constructor from a 3x3 rotation matrix R and a vector Tr.
Definition at line 97 of file ecvGLMatrix.h.
References ccGLMatrixTpl< T >::data(), cloudViewer::SquareMatrixTpl< Scalar >::isValid(), cloudViewer::SquareMatrixTpl< Scalar >::m_values, ccGLMatrixTpl< T >::setTranslation(), cloudViewer::SquareMatrixTpl< Scalar >::size(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
FromCCLibMatrix() [2/3]
template<typename Tin , typename Tout > ccGLMatrixTpl<Tout> FromCCLibMatrix (const cloudViewer::SquareMatrixTpl< Tin > & R, const Vector3Tpl< Tin > & Tr, const Vector3Tpl< Tin > & rotCenter)
Constructor from a rotation center G, a 3x3 rotation matrix R and a vector Tr
Definition at line 149 of file ecvGLMatrix.h.
References ccGLMatrixTpl< T >::shiftRotationCenter().
FromCCLibMatrix() [3/3]
template<typename Tin , typename Tout > ccGLMatrixTpl<Tout> FromCCLibMatrix (const cloudViewer::SquareMatrixTpl< Tin > & R, const Vector3Tpl< Tin > & Tr, Tin S)
Constructor from a 3x3 rotation matrix R, a vector Tr, a scale S.
Definition at line 122 of file ecvGLMatrix.h.
References ccGLMatrixTpl< T >::data(), cloudViewer::SquareMatrixTpl< Scalar >::isValid(), cloudViewer::SquareMatrixTpl< Scalar >::m_values, ccGLMatrixTpl< T >::setTranslation(), cloudViewer::SquareMatrixTpl< Scalar >::size(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.