ACloudViewer: /root/ACloudViewer/app/ecvGraphicalSegmentationTool.cpp File Reference
ecvGraphicalSegmentationTool.cpp File Reference
#include "ecvGraphicalSegmentationTool.h"
#include "ecvGraphicalSegmentationOptionsDlg.h"
#include "MainWindow.h"
#include "ecvItemSelectionDlg.h"
#include <ManualSegmentationTools.h>
#include <SquareMatrix.h>
#include <CVLog.h>
#include <ecv2DViewportObject.h>
#include <ecvDisplayTools.h>
#include <ecvGenericPointCloud.h>
#include <ecvHObjectCaster.h>
#include <ecvMesh.h>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include <ecv2DLabel.h>
#include <ecvCameraSensor.h>
#include <ecvGBLSensor.h>
#include <ecvSubMesh.h>
#include <ecvMainAppInterface.h>
#include <QInputDialog>
#include <QMenu>
#include <QMessageBox>
#include <QPushButton>
#include <QSettings>
#include <assert.h>
Functions
static void RemoveUnusedLabelsAndUpdateTheOthers (std::set< cc2DLabel * > &watchedLabels, ccHObject *entity, const std::vector< int > &newIndexesOfRemainingPointsOrTriangles, ecvMainAppInterface *app)
Variables
static unsigned s_polylineExportCount = 0
Function Documentation
RemoveUnusedLabelsAndUpdateTheOthers()
static void RemoveUnusedLabelsAndUpdateTheOthers (std::set< cc2DLabel * > & watchedLabels, ccHObject * entity, const std::vector< int > & newIndexesOfRemainingPointsOrTriangles, ecvMainAppInterface * app) static
Definition at line 1081 of file ecvGraphicalSegmentationTool.cpp.
References cc2DLabel::PickedPoint::entity(), ccHObject::getParent(), cc2DLabel::getPickedPoint(), cc2DLabel::PickedPoint::index, ccHObject::isAncestorOf(), ecvMainAppInterface::putObjectBackIntoDBTree(), ccHObject::removeChild(), ecvMainAppInterface::removeObjectTemporarilyFromDBTree(), and cc2DLabel::size().
Referenced by ccGraphicalSegmentationTool::applySegmentation().
Variable Documentation
s_polylineExportCount
unsigned s_polylineExportCount = 0 static
Definition at line 945 of file ecvGraphicalSegmentationTool.cpp.
Referenced by ccGraphicalSegmentationTool::doExportSegmentationPolyline().