ACloudViewer: /root/ACloudViewer/libs/CV_db/src/ecvGuiParameters.cpp File Reference
ecvGuiParameters.cpp File Reference
#include "ecvGuiParameters.h"
#include "ecvBasicTypes.h"
#include "ecvDisplayTools.h"
#include "ecvSingleton.h"
#include <QSettings>
#include <string.h>
Variables
static ecvSingleton< ecvGui > s_gui
Unique instance of ecvGui.
static int c_fColorArraySize = sizeof(float) * 4
static int c_ubColorArraySize = sizeof(unsigned char) * 3
Variable Documentation
c_fColorArraySize
int c_fColorArraySize = sizeof(float) * 4 static
Definition at line 115 of file ecvGuiParameters.cpp.
Referenced by ecvGui::ParamStruct::fromPersistentSettings(), and ecvGui::ParamStruct::toPersistentSettings().
c_ubColorArraySize
int c_ubColorArraySize = sizeof(unsigned char) * 3 static
Definition at line 116 of file ecvGuiParameters.cpp.
Referenced by ecvGui::ParamStruct::fromPersistentSettings(), and ecvGui::ParamStruct::toPersistentSettings().
s_gui
ecvSingleton<ecvGui> s_gui static
Unique instance of ecvGui.
Definition at line 22 of file ecvGuiParameters.cpp.
Referenced by ecvGui::Parameters(), ecvGui::ReleaseInstance(), ecvGui::Set(), and ecvGui::UpdateParameters().