ACloudViewer: /root/ACloudViewer/libs/CV_db/src/ecvIndexedTransformationBuffer.cpp File Reference
ecvIndexedTransformationBuffer.cpp File Reference
#include "ecvIndexedTransformationBuffer.h"
#include "ecvBBox.h"
#include <ParallelSort.h>
Functions
static bool IndexedSortOperator (const ccIndexedTransformation &a, const ccIndexedTransformation &b)
static bool IndexCompOperator (const ccIndexedTransformation &a, double index)
Function Documentation
IndexCompOperator()
static bool IndexCompOperator (const ccIndexedTransformation & a, double index) static
Definition at line 44 of file ecvIndexedTransformationBuffer.cpp.
References a.
Referenced by ccIndexedTransformationBuffer::findNearest().
IndexedSortOperator()
static bool IndexedSortOperator (const ccIndexedTransformation & a, const ccIndexedTransformation & b) static
Definition at line 39 of file ecvIndexedTransformationBuffer.cpp.
References a, and ccIndexedTransformation::getIndex().
Referenced by ccIndexedTransformationBuffer::findNearest(), and ccIndexedTransformationBuffer::sort().