ACloudViewer: /root/ACloudViewer/libs/CV_db/src/ecvMinimumSpanningTreeForNormsDirection.cpp File Reference
ecvMinimumSpanningTreeForNormsDirection.cpp File Reference
#include "ecvMinimumSpanningTreeForNormsDirection.h"
#include <ReferenceCloud.h>
#include "CVLog.h"
#include "ecvOctree.h"
#include "ecvPointCloud.h"
#include "ecvProgressDialog.h"
#include "ecvScalarField.h"
#include <map>
#include <queue>
#include <set>
#include <vector>
Classes
class Edge
Weighted graph edge.
class Graph
Generic graph structure.
Functions
static bool ResolveNormalsWithMST (ccPointCloud *cloud, ccOctree::Shared &octree, unsigned char level, unsigned kNN, ecvProgressDialog *progressCb=0)
static bool ComputeMSTGraphAtLevel (const cloudViewer::DgmOctree::octreeCell &cell, void **additionalParameters, cloudViewer::NormalizedProgress *nProgress)
Function Documentation
ComputeMSTGraphAtLevel()
static bool ComputeMSTGraphAtLevel (const cloudViewer::DgmOctree::octreeCell & cell, void ** additionalParameters, cloudViewer::NormalizedProgress * nProgress) static
Definition at line 405 of file ecvMinimumSpanningTreeForNormsDirection.cpp.
References Graph::addEdge(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::alreadyVisitedNeighbourhoodSize, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::cellCenter, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::cellPos, cloudViewer::DgmOctree::computeCellCenter(), Vector3Tpl< Type >::dot(), cloudViewer::DgmOctree::findNearestNeighborsStartingFromCell(), cloudViewer::DgmOctree::getCellPos(), cloudViewer::ReferenceCloud::getPoint(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), ccPointCloud::getPointNormal(), cloudViewer::ReferenceCloud::getPointPersistentPtr(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::level, cloudViewer::DgmOctree::octreeCell::level, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::minNumberOfNeighbors, nProgress, cloudViewer::NormalizedProgress::oneStep(), cloudViewer::DgmOctree::octreeCell::parentOctree, cloudViewer::DgmOctree::octreeCell::points, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::pointsInNeighbourhood, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::queryPoint, cloudViewer::ReferenceCloud::size(), and cloudViewer::DgmOctree::octreeCell::truncatedCode.
Referenced by ccMinimumSpanningTreeForNormsDirection::OrientNormals().
ResolveNormalsWithMST()
static bool ResolveNormalsWithMST (ccPointCloud * cloud, ccOctree::Shared & octree, unsigned char level, unsigned kNN, ecvProgressDialog * progressCb = 0) static
Definition at line 130 of file ecvMinimumSpanningTreeForNormsDirection.cpp.
References ccPointCloud::addScalarField(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::alreadyVisitedNeighbourhoodSize, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::cellCenter, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::cellPos, cloudViewer::DgmOctree::computeCellCenter(), ccScalarField::computeMinAndMax(), Vector3Tpl< Type >::dot(), cloudViewer::ScalarField::fill(), cloudViewer::DgmOctree::findNearestNeighborsStartingFromCell(), cloudViewer::PointCloudTpl< T >::getPoint(), ccPointCloud::getPointNormal(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::DgmOctree::getTheCellPosWhichIncludesThePoint(), ccPointCloud::hasNormals(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::level, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::minNumberOfNeighbors, NAN_VALUE, nProgress, octree, cloudViewer::NormalizedProgress::oneStep(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::pointsInNeighbourhood, CVLog::Print(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::queryPoint, ecvColor::Generator::Random(), ecvColor::RgbTpl< Type >::rgb, ccPointCloud::setCurrentDisplayedScalarField(), ccPointCloud::setPointColor(), ccPointCloud::setPointNormal(), ccPointCloud::setRGBColor(), cloudViewer::ScalarField::setValue(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), cloudViewer::PointCloudTpl< T >::size(), Edge::v1(), Edge::v2(), and ecvColor::white().
Referenced by ccMinimumSpanningTreeForNormsDirection::OrientNormals().