ACloudViewer: /root/ACloudViewer/libs/CV_db/src/ecvMesh.cpp File Reference
ecvMesh.cpp File Reference
#include "ecvMesh.h"
#include "ecvBBox.h"
#include "ecvChunk.h"
#include "ecvColorScalesManager.h"
#include "ecvDisplayTools.h"
#include "ecvGenericPointCloud.h"
#include "ecvHObjectCaster.h"
#include "ecvMaterialSet.h"
#include "ecvNormalVectors.h"
#include "ecvOrientedBBox.h"
#include "ecvPointCloud.h"
#include "ecvPolyline.h"
#include "ecvProgressDialog.h"
#include "ecvScalarField.h"
#include "ecvSubMesh.h"
#include <Delaunay2dMesh.h>
#include <Logging.h>
#include <ManualSegmentationTools.h>
#include <Neighbourhood.h>
#include <PointProjectionTools.h>
#include <ReferenceCloud.h>
#include <assert.h>
#include <string.h>
#include <cmath>
Functions
static bool TagDuplicatedVertices (const cloudViewer::DgmOctree::octreeCell &cell, void **additionalParameters, cloudViewer::NormalizedProgress *nProgress)
static qint64 GenerateKey (unsigned edgeIndex1, unsigned edgeIndex2)
Variables
static CCVector3 s_blankNorm (0, 0, 0)
static const unsigned s_defaultSubdivideGrowRate = 50
static PointCoordinateType s_maxSubdivideArea = 1
static QMap< qint64, unsigned > s_alreadyCreatedVertices
Function Documentation
GenerateKey()
static qint64 GenerateKey (unsigned edgeIndex1, unsigned edgeIndex2) static
Definition at line 4336 of file ecvMesh.cpp.
References std::swap().
Referenced by ccMesh::pushSubdivide(), and ccMesh::subdivide().
TagDuplicatedVertices()
static bool TagDuplicatedVertices (const cloudViewer::DgmOctree::octreeCell & cell, void ** additionalParameters, cloudViewer::NormalizedProgress * nProgress) static
Definition at line 582 of file ecvMesh.cpp.
References cloudViewer::DgmOctree::computeCellCenter(), cloudViewer::DgmOctree::findNeighborsInASphereStartingFromCell(), cloudViewer::DgmOctree::getCellPos(), cloudViewer::DgmOctree::getCellSize(), cloudViewer::ReferenceCloud::getPoint(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), cloudViewer::ReferenceCloud::getPointPersistentPtr(), cloudViewer::DgmOctree::NearestNeighboursSearchStruct::level, cloudViewer::DgmOctree::octreeCell::level, nProgress, cloudViewer::NormalizedProgress::oneStep(), cloudViewer::DgmOctree::octreeCell::parentOctree, cloudViewer::DgmOctree::octreeCell::points, cloudViewer::ReferenceCloud::size(), cloudViewer::DgmOctree::octreeCell::truncatedCode, and ZERO_TOLERANCE_F.
Referenced by ccMesh::mergeDuplicatedVertices().
Variable Documentation
s_alreadyCreatedVertices
QMap<qint64, unsigned> s_alreadyCreatedVertices static
Definition at line 4333 of file ecvMesh.cpp.
Referenced by ccMesh::pushSubdivide(), and ccMesh::subdivide().
s_blankNorm
CCVector3 s_blankNorm(0, 0, 0) (0 , 0 , 0) static
Referenced by ccMesh::computePerVertexNormals().
s_defaultSubdivideGrowRate
const unsigned s_defaultSubdivideGrowRate = 50 static
Definition at line 4330 of file ecvMesh.cpp.
Referenced by ccMesh::pushSubdivide().
s_maxSubdivideArea
PointCoordinateType s_maxSubdivideArea = 1 static
Definition at line 4331 of file ecvMesh.cpp.
Referenced by ccMesh::pushSubdivide(), and ccMesh::subdivide().