ACloudViewer: /root/ACloudViewer/app/ecvPointPairRegistrationDlg.cpp File Reference
ecvPointPairRegistrationDlg.cpp File Reference
#include <ecvPointPairRegistrationDlg.h>
#include "MainWindow.h"
#include "ecvAskThreeDoubleValuesDlg.h"
#include <ecvPickingHub.h>
#include <GeometricalAnalysisTools.h>
#include <RegistrationTools.h>
#include <ecv2DLabel.h>
#include <ecvDisplayTools.h>
#include <ecvGenericPointCloud.h>
#include <ecvPointCloud.h>
#include <ecvProgressDialog.h>
#include <ecvSphere.h>
#include <ecvGlobalShiftManager.h>
#include <QMdiSubWindow>
#include <QMessageBox>
#include <QSettings>
#include <QToolButton>
Functions
static void SetEnabled_recursive (ccHObject *ent)
static QToolButton * CreateDeleteButton ()
static cc2DLabel * CreateLabel (cc2DLabel *label, ccPointCloud *cloud, unsigned pointIndex, QString pointName)
static cc2DLabel * CreateLabel (ccPointCloud *cloud, unsigned pointIndex, QString pointName)
Variables
static const int XYZ_COL_INDEX = 0
static const int RMS_COL_INDEX = 3
static const int DEL_BUTTON_COL_INDEX = 4
static const unsigned MIN_PAIRS_COUNT = 3
static QString s_aligned_tooltip
static double s_last_ax = 0
static double s_last_ay = 0
static double s_last_az = 0
static bool s_lastAlignePointIsGlobal = true
static double s_last_rx = 0
static double s_last_ry = 0
static double s_last_rz = 0
static bool s_lastRefPointisGlobal = true
Function Documentation
CreateDeleteButton()
static QToolButton* CreateDeleteButton () static
Definition at line 622 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::addPointToTable().
CreateLabel() [1/2]
static cc2DLabel* CreateLabel (cc2DLabel * label, ccPointCloud * cloud, unsigned pointIndex, QString pointName) static
Definition at line 628 of file ecvPointPairRegistrationDlg.cpp.
References cc2DLabel::addPickedPoint(), cc2DLabel::displayPointLegend(), cc2DLabel::setDisplayedIn2D(), ccObject::setEnabled(), ccObject::setName(), and ccDrawableObject::setVisible().
Referenced by ccPointPairRegistrationDlg::addAlignedPoint(), ccPointPairRegistrationDlg::addReferencePoint(), CreateLabel(), ccPointPairRegistrationDlg::removeAlignedPoint(), and ccPointPairRegistrationDlg::removeRefPoint().
CreateLabel() [2/2]
static cc2DLabel* CreateLabel (ccPointCloud * cloud, unsigned pointIndex, QString pointName) static
Definition at line 643 of file ecvPointPairRegistrationDlg.cpp.
References CreateLabel().
SetEnabled_recursive()
static void SetEnabled_recursive (ccHObject * ent) static
Definition at line 275 of file ecvPointPairRegistrationDlg.cpp.
References ccHObject::getParent(), and ccObject::setEnabled().
Referenced by ccPointPairRegistrationDlg::init().
Variable Documentation
DEL_BUTTON_COL_INDEX
const int DEL_BUTTON_COL_INDEX = 4 static
Definition at line 41 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::addPointToTable(), and ccPointPairRegistrationDlg::onDelButtonPushed().
MIN_PAIRS_COUNT
const unsigned MIN_PAIRS_COUNT = 3 static
Definition at line 44 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::callHornRegistration(), ccPointPairRegistrationDlg::init(), ccPointPairRegistrationDlg::onPointCountChanged(), and ccPointPairRegistrationDlg::updateAlignInfo().
RMS_COL_INDEX
const int RMS_COL_INDEX = 3 static
Definition at line 40 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::callHornRegistration(), and ccPointPairRegistrationDlg::clearRMSColumns().
s_aligned_tooltip
QString s_aligned_tooltip static
Initial value:
= QObject::tr(
        "Whether the point is expressed in the entity original coordinate "
        "system (before being shifted by CV) or not")
Definition at line 422 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::addManualAlignedPoint(), and ccPointPairRegistrationDlg::addManualRefPoint().
s_last_ax
double s_last_ax = 0 static
Definition at line 425 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::addManualAlignedPoint().
s_last_ay
double s_last_ay = 0 static
Definition at line 426 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::addManualAlignedPoint().
s_last_az
double s_last_az = 0 static
Definition at line 427 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::addManualAlignedPoint().
s_last_rx
double s_last_rx = 0 static
Definition at line 457 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::addManualRefPoint().
s_last_ry
double s_last_ry = 0 static
Definition at line 458 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::addManualRefPoint().
s_last_rz
double s_last_rz = 0 static
Definition at line 459 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::addManualRefPoint().
s_lastAlignePointIsGlobal
bool s_lastAlignePointIsGlobal = true static
Definition at line 428 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::addManualAlignedPoint().
s_lastRefPointisGlobal
bool s_lastRefPointisGlobal = true static
Definition at line 460 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::addManualRefPoint().
XYZ_COL_INDEX
const int XYZ_COL_INDEX = 0 static
Definition at line 39 of file ecvPointPairRegistrationDlg.cpp.
Referenced by ccPointPairRegistrationDlg::addPointToTable().