ACloudViewer: /root/ACloudViewer/app/db_tree/ecvPropertiesTreeDelegate.cpp File Reference
ecvPropertiesTreeDelegate.cpp File Reference
#include "ecvPropertiesTreeDelegate.h"
#include "../MainWindow.h"
#include "CommonSettings.h"
#include "ecvAxesGridDialog.h"
#include "ecvColorScaleEditorDlg.h"
#include "ecvColorScaleSelector.h"
#include "ecvFileUtils.h"
#include "ecvOptions.h"
#include "ecvPersistentSettings.h"
#include "ecvSettingManager.h"
#include "ecvTextureFileSelector.h"
#include "matrixDisplayDlg.h"
#include "sfEditDlg.h"
#include <ecv2DLabel.h>
#include <ecv2DViewportLabel.h>
#include <ecv2DViewportObject.h>
#include <ecvAdvancedTypes.h>
#include <ecvCameraSensor.h>
#include <ecvCircle.h>
#include <ecvColorScalesManager.h>
#include <ecvCone.h>
#include <ecvCoordinateSystem.h>
#include <ecvDisc.h>
#include <ecvDisplayTools.h>
#include <ecvDrawContext.h>
#include <ecvFacet.h>
#include <ecvGBLSensor.h>
#include <ecvGenericPrimitive.h>
#include <ecvGuiParameters.h>
#include <ecvHObject.h>
#include <ecvHObjectCaster.h>
#include <ecvImage.h>
#include <ecvIndexedTransformationBuffer.h>
#include <ecvKdTree.h>
#include <ecvMaterialSet.h>
#include <ecvMesh.h>
#include <ecvOctree.h>
#include <ecvOctreeProxy.h>
#include <ecvPlane.h>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include <ecvScalarField.h>
#include <ecvSensor.h>
#include <ecvSphere.h>
#include <ecvSubMesh.h>
#include <QAbstractItemView>
#include <QCheckBox>
#include <QComboBox>
#include <QFileInfo>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QImageReader>
#include <QLineEdit>
#include <QLocale>
#include <QPushButton>
#include <QScrollBar>
#include <QSet>
#include <QSlider>
#include <QSpinBox>
#include <QStandardItemModel>
#include <QToolButton>
#include <QTreeView>
#include <algorithm>
#include <exception>
#include <functional>
#include <assert.h>
#include <cmath>
Functions
constexpr const char * SEPARATOR_STYLESHEET ("QLabel { background-color : darkGray; color : white; }")
QStandardItem * ITEM (QString name, Qt::ItemFlag additionalFlags=Qt::NoItemFlags, ccPropertiesTreeDelegate::CC_PROPERTY_ROLE role=ccPropertiesTreeDelegate::OBJECT_NO_PROPERTY)
QStandardItem * CHECKABLE_ITEM (bool checkState, ccPropertiesTreeDelegate::CC_PROPERTY_ROLE role)
QStandardItem * PERSISTENT_EDITOR (ccPropertiesTreeDelegate::CC_PROPERTY_ROLE role)
void SetDoubleSpinBoxValue (QWidget *editor, double value, bool keyboardTracking=false)
void SetSpinBoxValue (QWidget *editor, int value, bool keyboardTracking=false)
void SetComboBoxIndex (QWidget *editor, int index)
Function Documentation
CHECKABLE_ITEM()
QStandardItem* CHECKABLE_ITEM (bool checkState, ccPropertiesTreeDelegate::CC_PROPERTY_ROLE role)
Definition at line 124 of file ecvPropertiesTreeDelegate.cpp.
References ITEM().
Referenced by ccPropertiesTreeDelegate::fillSFWithPointCloud(), ccPropertiesTreeDelegate::fillWithCameraSensor(), ccPropertiesTreeDelegate::fillWithCoordinateSystem(), ccPropertiesTreeDelegate::fillWithFacet(), ccPropertiesTreeDelegate::fillWithHObject(), ccPropertiesTreeDelegate::fillWithLabel(), ccPropertiesTreeDelegate::fillWithMesh(), ccPropertiesTreeDelegate::fillWithPlanarEntity(), and ccPropertiesTreeDelegate::fillWithTransBuffer().
ITEM()
QStandardItem* ITEM (QString name, Qt::ItemFlag additionalFlags = Qt::NoItemFlags, ccPropertiesTreeDelegate::CC_PROPERTY_ROLE role = ccPropertiesTreeDelegate::OBJECT_NO_PROPERTY)
Definition at line 109 of file ecvPropertiesTreeDelegate.cpp.
References name, and ccPropertiesTreeDelegate::OBJECT_NO_PROPERTY.
Referenced by CHECKABLE_ITEM(), ccPropertiesTreeDelegate::fillSFWithPointCloud(), ccPropertiesTreeDelegate::fillWithCameraSensor(), ccPropertiesTreeDelegate::fillWithCCArray(), ccPropertiesTreeDelegate::fillWithCoordinateSystem(), ccPropertiesTreeDelegate::fillWithFacet(), ccPropertiesTreeDelegate::fillWithGBLSensor(), ccPropertiesTreeDelegate::fillWithHObject(), ccPropertiesTreeDelegate::fillWithImage(), ccPropertiesTreeDelegate::fillWithLabel(), ccPropertiesTreeDelegate::fillWithMaterialSet(), ccPropertiesTreeDelegate::fillWithMesh(), ccPropertiesTreeDelegate::fillWithMetaData(), ccPropertiesTreeDelegate::fillWithPlanarEntity(), ccPropertiesTreeDelegate::fillWithPointCloud(), ccPropertiesTreeDelegate::fillWithPointKdTree(), ccPropertiesTreeDelegate::fillWithPointOctree(), ccPropertiesTreeDelegate::fillWithPolyline(), ccPropertiesTreeDelegate::fillWithPrimitive(), ccPropertiesTreeDelegate::fillWithSensor(), ccPropertiesTreeDelegate::fillWithShareable(), ccPropertiesTreeDelegate::fillWithShifted(), ccPropertiesTreeDelegate::fillWithTransBuffer(), ccPropertiesTreeDelegate::fillWithViewportObject(), ccPropertiesTreeDelegate::fillWithViewProperties(), and PERSISTENT_EDITOR().
PERSISTENT_EDITOR()
QStandardItem* PERSISTENT_EDITOR (ccPropertiesTreeDelegate::CC_PROPERTY_ROLE role)
Definition at line 134 of file ecvPropertiesTreeDelegate.cpp.
References ITEM().
Referenced by ccPropertiesTreeDelegate::fillModel(), ccPropertiesTreeDelegate::fillSFWithPointCloud(), ccPropertiesTreeDelegate::fillWithCoordinateSystem(), ccPropertiesTreeDelegate::fillWithGBLSensor(), ccPropertiesTreeDelegate::fillWithHObject(), ccPropertiesTreeDelegate::fillWithImage(), ccPropertiesTreeDelegate::fillWithMesh(), ccPropertiesTreeDelegate::fillWithPointCloud(), ccPropertiesTreeDelegate::fillWithPointOctree(), ccPropertiesTreeDelegate::fillWithPolyline(), ccPropertiesTreeDelegate::fillWithPrimitive(), ccPropertiesTreeDelegate::fillWithSensor(), ccPropertiesTreeDelegate::fillWithTransBuffer(), ccPropertiesTreeDelegate::fillWithViewportObject(), and ccPropertiesTreeDelegate::fillWithViewProperties().
SEPARATOR_STYLESHEET()
constexpr const char* SEPARATOR_STYLESHEET ("QLabel { background-color : darkGray; color : white; }") constexpr
Referenced by ccPropertiesTreeDelegate::createEditor().
SetComboBoxIndex()
void SetComboBoxIndex (QWidget * editor, int index)
Definition at line 1955 of file ecvPropertiesTreeDelegate.cpp.
Referenced by ccPropertiesTreeDelegate::setEditorData().
SetDoubleSpinBoxValue()
void SetDoubleSpinBoxValue (QWidget * editor, double value, bool keyboardTracking = false)
Definition at line 1931 of file ecvPropertiesTreeDelegate.cpp.
Referenced by ccPropertiesTreeDelegate::setEditorData().
SetSpinBoxValue()
void SetSpinBoxValue (QWidget * editor, int value, bool keyboardTracking = false)
Definition at line 1943 of file ecvPropertiesTreeDelegate.cpp.
Referenced by ccPropertiesTreeDelegate::setEditorData().