ACloudViewer: /root/ACloudViewer/libs/CV_db/src/ecvPlanarEntityInterface.cpp File Reference
ecvPlanarEntityInterface.cpp File Reference
#include "ecvPlanarEntityInterface.h"
#include "ecvCone.h"
#include "ecvCylinder.h"
#include "ecvDisplayTools.h"
#include <QSharedPointer>
Functions
static QSharedPointer< ccCylinder > c_unitNormalSymbol (0)
static QSharedPointer< ccCone > c_unitNormalHeadSymbol (0)
Variables
static const QString SEPARATOR = "_"
Function Documentation
c_unitNormalHeadSymbol()
static QSharedPointer<ccCone> c_unitNormalHeadSymbol (0) static
Referenced by ccPlanarEntityInterface::clearNormalVector(), and ccPlanarEntityInterface::glDrawNormal().
c_unitNormalSymbol()
static QSharedPointer<ccCylinder> c_unitNormalSymbol (0) static
Referenced by ccPlanarEntityInterface::clearNormalVector(), and ccPlanarEntityInterface::glDrawNormal().
Variable Documentation
SEPARATOR
const QString SEPARATOR = "_" static
Definition at line 24 of file ecvPlanarEntityInterface.cpp.
Referenced by ccPlanarEntityInterface::glDrawNormal().