ACloudViewer: /root/ACloudViewer/libs/CV_db/src/ecvPointCloudInterpolator.cpp File Reference
ecvPointCloudInterpolator.cpp File Reference
#include "ecvPointCloudInterpolator.h"
#include "ecvPointCloud.h"
#include "ecvScalarField.h"
#include <DgmOctree.h>
#include <DistanceComputationTools.h>
#include <GenericProgressCallback.h>
Classes
struct SFPair
Functions
bool cellSFInterpolator (const cloudViewer::DgmOctree::octreeCell &cell, void **additionalParameters, cloudViewer::NormalizedProgress *nProgress)
Function Documentation
cellSFInterpolator()
bool cellSFInterpolator (const cloudViewer::DgmOctree::octreeCell & cell, void ** additionalParameters, cloudViewer::NormalizedProgress * nProgress)
Definition at line 27 of file ecvPointCloudInterpolator.cpp.
References cloudViewer::DgmOctree::NearestNeighboursSearchStruct::cellCenter, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::cellPos, cloudViewer::DgmOctree::computeCellCenter(), cloudViewer::DgmOctree::findNearestNeighborsStartingFromCell(), cloudViewer::DgmOctree::findNeighborsInASphereStartingFromCell(), cloudViewer::DgmOctree::getCellPos(), cloudViewer::ReferenceCloud::getPoint(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), cloudViewer::ScalarField::getValue(), ccPointCloudInterpolator::Parameters::K_NEAREST_NEIGHBORS, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::level, cloudViewer::DgmOctree::octreeCell::level, ccPointCloudInterpolator::Parameters::MEDIAN, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::minNumberOfNeighbors, ccPointCloudInterpolator::Parameters::NORMAL_DIST, nProgress, cloudViewer::NormalizedProgress::oneStep(), cloudViewer::DgmOctree::octreeCell::parentOctree, cloudViewer::DgmOctree::PointDescriptor::pointIndex, cloudViewer::DgmOctree::octreeCell::points, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::pointsInNeighbourhood, cloudViewer::DgmOctree::NearestNeighboursSearchStruct::queryPoint, ccPointCloudInterpolator::Parameters::sigma, cloudViewer::ReferenceCloud::size(), cloudViewer::DgmOctree::PointDescriptor::squareDistd, and cloudViewer::DgmOctree::octreeCell::truncatedCode.
Referenced by ccPointCloudInterpolator::InterpolateScalarFieldsFrom().