ACloudViewer: /root/ACloudViewer/app/ecvShortcutDialog.cpp File Reference
ecvShortcutDialog.cpp File Reference
#include "ecvShortcutDialog.h"
#include "ecvPersistentSettings.h"
#include <QAction>
#include <QHeaderView>
#include <QKeySequenceEdit>
#include <QLineEdit>
#include <QMainWindow>
#include <QMenu>
#include <QMenuBar>
#include <QMessageBox>
#include <QSettings>
#include <QTableWidget>
#include <QTableWidgetItem>
Functions
static QString findMenuPathRecursive (QMenu *menu, QAction *targetAction, QStringList path)
static QString getMenuPath (QAction *action, QWidget *parentWidget)
Variables
constexpr int ACTION_NAME_COLUMN = 0
constexpr int KEY_SEQUENCE_COLUMN = 1
Function Documentation
findMenuPathRecursive()
static QString findMenuPathRecursive (QMenu * menu, QAction * targetAction, QStringList path) static
Definition at line 30 of file ecvShortcutDialog.cpp.
References cloudViewer::t::geometry::path, and result.
Referenced by getMenuPath().
getMenuPath()
static QString getMenuPath (QAction * action, QWidget * parentWidget) static
Definition at line 77 of file ecvShortcutDialog.cpp.
References findMenuPathRecursive(), cloudViewer::t::geometry::path, and result.
Referenced by ecvShortcutDialog::ecvShortcutDialog().
Variable Documentation
ACTION_NAME_COLUMN
constexpr int ACTION_NAME_COLUMN = 0 constexpr
Definition at line 26 of file ecvShortcutDialog.cpp.
Referenced by ecvShortcutDialog::ecvShortcutDialog().
KEY_SEQUENCE_COLUMN
constexpr int KEY_SEQUENCE_COLUMN = 1 constexpr
Definition at line 27 of file ecvShortcutDialog.cpp.
Referenced by ecvShortcutDialog::ecvShortcutDialog(), and ecvShortcutDialog::restoreShortcutsFromQSettings().