ACloudViewer: /root/ACloudViewer/app/ecvVolumeCalcTool.cpp File Reference
ecvVolumeCalcTool.cpp File Reference
#include "ecvVolumeCalcTool.h"
#include "MainWindow.h"
#include "ecvBoundingBoxEditorDlg.h"
#include "ecvCommon.h"
#include "ecvIsolines.h"
#include "ecvPersistentSettings.h"
#include <ecvDisplayTools.h>
#include <ecvGenericPointCloud.h>
#include <ecvMesh.h>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <Delaunay2dMesh.h>
#include <PointProjectionTools.h>
#include <QApplication>
#include <QClipboard>
#include <QComboBox>
#include <QLocale>
#include <QMessageBox>
#include <QPushButton>
#include <QSettings>
#include <assert.h>
Functions
bool SendError (const QString &message, QWidget *parentWidget)
Function Documentation
SendError()
bool SendError (const QString & message, QWidget * parentWidget)
Definition at line 490 of file ecvVolumeCalcTool.cpp.
References CVLog::Error(), and CVLog::Warning().
Referenced by ccVolumeCalcTool::ComputeVolume().