ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/CodeEditor/EditorSettings.cpp File Reference
EditorSettings.cpp File Reference
#include "EditorSettings.h"
#include <QPushButton>
#include <QSettings>
Functions
static QString SettingsScopeName ()
Variables
static const auto SHOULD_HIGHLIGHT_SETTINGS_KEY = QStringLiteral("ShouldHighlightCurrentLine")
static const auto COLOR_SCHEME_SETTINGS_KEY = QStringLiteral("ColorSchemeName")
Function Documentation
SettingsScopeName()
static QString SettingsScopeName () static
Definition at line 16 of file EditorSettings.cpp.
Referenced by EditorSettings::loadFromSettings(), and EditorSettings::saveChanges().
Variable Documentation
COLOR_SCHEME_SETTINGS_KEY
const auto COLOR_SCHEME_SETTINGS_KEY = QStringLiteral("ColorSchemeName") static
Definition at line 14 of file EditorSettings.cpp.
Referenced by EditorSettings::loadFromSettings(), and EditorSettings::saveChanges().
SHOULD_HIGHLIGHT_SETTINGS_KEY
const auto SHOULD_HIGHLIGHT_SETTINGS_KEY = QStringLiteral("ShouldHighlightCurrentLine") static
Definition at line 13 of file EditorSettings.cpp.
Referenced by EditorSettings::loadFromSettings(), and EditorSettings::saveChanges().