ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/estimators/essential_matrix_poly.h File Reference
essential_matrix_poly.h File Reference
Functions
for (size_t i=0;i< 36;++i)
Variables
const double * e = E.data()
double e2 [36]
double e3 [36]
a [190]
Function Documentation
for()
for ()
Definition at line 14 of file essential_matrix_poly.h.
References e, e2, and e3.
Referenced by cloudViewer::ml::impl::_SparseConvTransposeComputeFeaturesCPU(), DistanceMapGenerationTool::CreateMap(), cloudViewer::visualization::gui::Layout1D::debug_PrintPreferredSizes(), define_ccQuadric(), ccRasterizeTool::ExportGeoTiff(), cloudViewer::core::nns::MemoryAllocation::Free(), cloudViewer::ml::impl::MemoryAllocation::Free(), cloudViewer::t::geometry::TriangleMesh::RemoveNonManifoldEdges(), cloudViewer::t::geometry::TriangleMesh::SelectByIndex(), ToQByteArray(), LDATrainer::train(), and ccClipBox::update().
Variable Documentation
a
a[115]
Initial value:
= e[33] * e[28] * e[32] - e[33] * e[31] * e[29] +
             e[30] * e[34] * e[29] - e[30] * e[28] * e[35] -
             e[27] * e[32] * e[34] + e[27] * e[31] * e[35]
Definition at line 19 of file essential_matrix_poly.h.
Referenced by cvSelectionData::addActorInfo(), PclUtils::PCLVis::addCaption(), cloudViewer::Universe::addEdge(), AlmostEq(), cloudViewer::ml::op_util::DimXPlus::apply(), cloudViewer::ml::op_util::DimXMinus::apply(), cloudViewer::ml::op_util::DimXMultiply::apply(), cloudViewer::ml::op_util::DimXDivide::apply(), PclAnnotationTool::areaPickingEventProcess(), PclFiltersTool::areaPickingEventProcess(), cvSelectionAlgebra::areCompatible(), cloudViewer::ml::op_util::Dim::assign(), cloudViewer::ml::op_util::DimX< TLeft, TRight, TOp >::assign(), cloudViewer::ml::op_util::DimXPlus::backprop(), cloudViewer::ml::op_util::DimXMinus::backprop(), cloudViewer::ml::op_util::DimXMultiply::backprop(), cloudViewer::ml::op_util::DimXDivide::backprop(), cloudViewer::ml::op_util::DimXOr::backprop(), cvConstrainedPolyLineRepresentation::BuildAngleArc(), CandidateDistAscendingComparison(), cloudViewer::utility::MiniVec< T, N >::cast(), cloudViewer::utility::ceil(), cloudViewer::KDTree::checkNearerPointInSubTree(), cloudViewer::geometry::Line3D::ClosestParameters(), cloudViewer::DgmOctree::IndexAndCode::codeComp(), cvSelectionFilter::combineAND(), cvSelectionFilter::combineOR(), cloudViewer::t::pipelines::slac::ControlGrid::Compactify(), compare_ids(), compare_ints(), ComparisonX(), ComparisonY(), ComparisonZ(), NurbsCurveFitting::compute(), BallPivoting::ComputeBallCenter(), cloudViewer::DistanceComputationTools::computeCloud2MeshDistanceWithOctree(), ccMesh::ComputeEdgeWeightsCot(), Jacobi< Scalar >::ComputeEigenValuesAndVectors2(), cloudViewer::t::pipelines::kernel::ComputeInformationMatrixKernelCPU(), ccHObject::ComputeMaxBound(), ccHObject::ComputeMinBound(), cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBApprox(), cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBJylanki(), ComputeNeighborhood2MeshDistancesWithOctree(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryInformationMatrixCPU(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultHybridCPU(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultIntensityCPU(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultPointToPlaneCPU(), cloudViewer::WeibullDistribution::computeParameters(), cloudViewer::t::pipelines::kernel::ComputePoseColoredICPKernelCPU(), cloudViewer::t::pipelines::kernel::ComputePoseDopplerICPKernelCPU(), cloudViewer::t::pipelines::kernel::ComputePosePointToPlaneKernelCPU(), Annotation::computeScaleAndCenterShift(), DimensionalityScaleParamsComputer::computeScaleParams(), cloudViewer::GeometricalAnalysisTools::ComputeSphereFrom4(), ccEntityAction::computeStatParams(), cloudViewer::core::TensorList::Concatenate(), conjugate(), cloudViewer::core::kernel::CPUAllReductionKernel(), cloudViewer::core::kernel::CPUAnyReductionKernel(), cloudViewer::core::kernel::CPUArgMaxReductionKernel(), cloudViewer::core::kernel::CPUArgMinReductionKernel(), cloudViewer::core::kernel::CPUMaxReductionKernel(), cloudViewer::core::kernel::CPUMinReductionKernel(), cloudViewer::core::kernel::CPUProdReductionKernel(), cloudViewer::core::kernel::CPUSumReductionKernel(), ccMesh::CreateFromPointCloudAlphaShape(), ccBBox::CreateFromPoints(), cloudViewer::ml::contrib::Cross(), define_ccGLMatrixClass(), define_ccPointCloud(), define_KdTree(), ComponentIndexAndSize::DescendingCompOperator(), DescendingLeafSizeComparison(), cvSelectionAlgebra::differenceOf(), ecvTools::DiffVector(), cloudViewer::DgmOctree::PointDescriptor::distComp(), QCPAbstractPlottable::distSqrToLine(), QCPAbstractItem::distSqrToLine(), dmat_solve(), cloudViewer::utility::MiniVec< T, N >::dot(), vtkBoundingRectContextDevice2D::DrawEllipseWedge(), vtkBoundingRectContextDevice2D::DrawEllipticArc(), QCPGraph::drawError(), cloudViewer::io::rpc::messages::EndiannessStr(), cloudViewer::ErrorFunction::erfc(), colmap::P3PEstimator::Estimate(), cvSelectionExporter::extractSelection(), cloudViewer::geometry::TetraMesh::ExtractTriangleMesh(), cloudViewer::FPCSRegistrationTools::FindBase(), BallPivoting::FindCandidateVertex(), cloudViewer::FPCSRegistrationTools::FindCongruentBases(), cloudViewer::KDTree::findNearestNeighbour(), colmap::FindOptimalImageObservations(), colmap::FindQuadraticPolynomialRoots(), cloudViewer::utility::floor(), qCanupoTools::Fpeq(), Tuple4Tpl< Type >::fromArray(), Vector3Tpl< Type >::fromArray(), cloudViewer::io::rpc::messages::Array::FromTensor(), cloudViewer::DgmOctree::getCellDistanceFromBorders(), cloudViewer::FPCSRegistrationTools::Base::getIndex(), cloudViewer::visualization::SelectionPolygon::GetMax2DBound(), cloudViewer::visualization::SelectionPolygon::GetMin2DBound(), getMortarMaps(), cloudViewer::WeibullDistribution::getParameters(), PclUtils::PCLVis::getReasonableClippingRange(), cloudViewer::ml::op_util::GetString(), cloudViewer::visualization::rendering::Gradient::GetTextureHandle(), cloudViewer::ml::op_util::GetValue(), cloudViewer::ml::contrib::grid_subsampling(), ccMesh::hasEigenTextures(), cloudViewer::DgmOctree::IndexAndCode::indexComp(), IndexAndCodeExt::indexComp(), IndexCompOperator(), IndexedSortOperator(), cloudViewer::FPCSRegistrationTools::Base::init(), cloudViewer::ml::impl::InterpolationVec< T, VECSIZE, InterpolationMode::LINEAR >::Interpolate(), cloudViewer::ml::impl::InterpolationVec< T, VECSIZE, InterpolationMode::LINEAR_BORDER >::Interpolate(), cvSelectionAlgebra::intersectionOf(), ecvTools::IntersectionVector(), KNNRegions(), LexicographicSort(), cloudViewer::utility::IntersectionTest::LineSegmentsMinimumDistance(), cloudViewer::loadArrayFromFile(), cloudViewer::loadArrayFromFileIntoArray(), cloudViewer::loadArrayOfArraysFromFile(), STLFilter::loadBinaryFile(), CorePointDescSet::loadFromMSC(), MainWindow::MainWindow(), mode_col(), QVTKWidgetCustom::mouseMoveEvent(), CGAL_Normal_Estimator::My_Triplet< T >::My_Triplet(), cloudViewer::utility::operator!(), vtkPMergeConnected::cmp_ids::operator()(), Vec3::operator*(), cloudViewer::ml::contrib::operator*(), cloudViewer::ml::contrib::PointXYZ::operator*=(), cloudViewer::utility::operator-(), Vec3::operator/(), cloudViewer::ml::op_util::operator==(), ccCameraSensor::orthoRectifyAsCloud(), ccCameraSensor::orthoRectifyAsImage(), ccCameraSensor::OrthoRectifyAsImages(), cvSelectionAlgebra::performOperation(), Chi2Helper::pochisq(), cloudViewer::ml::contrib::PointCmp(), CurveFittingTool::CurveFitting::polynomial2D_fitting(), CurveFittingTool::CurveFitting::polynomial3D_fitting(), CommandStatTest::process(), ccCloudLayersHelper::projectCloud(), QCPDataContainer< DataType >::qcpLessThanSortKey(), cloudViewer::io::ReadTriangleMeshFromOBJ(), ccAsprsModel::refreshData(), cloudViewer::RegistrationTools::RegistrationProcedure(), ccMesh::SamplePointsPoissonDisk(), ccMesh::SamplePointsUniformlyImpl(), cloudViewer::saveArrayOfArraysToFile(), cloudViewer::saveArrayToFile(), MAFilter::saveToFile(), MascaretFilter::saveToFile(), cloudViewer::SaitoSquaredDistanceTransform::SDT_2D(), cloudViewer::SaitoSquaredDistanceTransform::SDT_3D(), QCPItemEllipse::selectTest(), QCPItemBracket::selectTest(), cloudViewer::visualization::rendering::TextureSamplerParameters::SetAnisotropy(), Plane::setCoefficients(), cloudViewer::visualization::gui::Color::SetColor(), cloudViewer::WeibullDistribution::setParameters(), ccMesh::SimplifyQuadricDecimation(), cloudViewer::sizeOfStaticVector(), ccEntityAction::statisticalTest(), PdmsTools::PdmsObjects::Dish::surface(), cvSelectionAlgebra::symmetricDifferenceOf(), cloudViewer::core::kernel::TestLinalgIntegration(), cloudViewer::visualization::gui::Color::ToABGR32(), cloudViewer::Neighbourhood::triangulateFromQuadric(), cvSelectionAlgebra::unionOf(), ecvTools::UnionVector(), PclUtils::PCLVis::updateCaption(), Vector3Tpl< Type >::vcombination(), colmap::retrieval::VoteAndVerify(), and cloudViewer::WeibullDistribution::WeibullDistribution().
e
const double* e = E.data()
Definition at line 10 of file essential_matrix_poly.h.
Referenced by cloudViewer::io::AutoReadEntity(), BOOST_AUTO_TEST_CASE(), cvConstrainedPolyLineRepresentation::BuildAngleArc(), colmap::BundleAdjustmentOptions::BundleAdjustmentOptions(), call_fn(), cloudViewer::t::io::RealSenseSensor::CaptureFrame(), PythonEditor::changeEvent(), ccColorScaleEditorDialog::changeSelectedStepValue(), cloudViewer::ml::contrib::CheckInBox2D(), cloudViewer::geometry::Line3D::ClosestParameters(), PythonHighlighter::CodeElementName(), ccComparisonDlg::computeApproxDistances(), BallPivoting::ComputeBallCenter(), cloudViewer::DistanceComputationTools::computeCloud2MeshDistanceWithOctree(), cloudViewer::Neighbourhood::computeCurvature(), cloudViewer::ml::impl::ComputeFilterCoordinates(), cloudViewer::pipelines::registration::ComputeLinearSystem(), cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBJylanki(), ComputeNeighborhood2MeshDistancesWithOctree(), cloudViewer::pipelines::registration::ComputeResidual(), colmap::CameraRig::ComputeScale(), cloudViewer::pipelines::registration::ComputeZeta(), vtkScalarBarActorCustom::ConfigureTicks(), conjugate(), contourPoly(), contourPoly2(), cloudViewer::utility::filesystem::CopyA(), QCPAxisTickerLog::createTickVector(), BallPivoting::CreateTriangle(), cloudViewer::visualization::gui::Layout1D::debug_PrintPreferredSizes(), colmap::DecomposeHomographyMatrix(), define_pycc(), cloudViewer::visualization::gui::BitmapWindowSystem::DestroyWindow(), cloudViewer::GeometricalAnalysisTools::DetectSphereRobust(), cloudViewer::t::geometry::ipp::Dilate(), colmap::FOVCameraModel::Distortion(), doPerformBooleanOp(), colmap::EpipoleFromEssentialMatrix(), colmap::EssentialMatrixFivePointEstimator::Estimate(), colmap::FundamentalMatrixSevenPointEstimator::Estimate(), colmap::P3PEstimator::Estimate(), ccPointCloud::EstimatePerPointCovariances(), ccCompass::estimateStrain(), ccOverlayDialog::eventFilter(), PythonEditor::eventFilter(), cloudViewer::geometry::Line3D::ExactAABB(), Widgets::ColorPickerPopup::exec(), Execute(), PythonInterpreter::executeFile(), PythonInterpreter::executeFunction(), colmap::Reconstruction::ExportCam(), ccContourExtractor::ExtractConcaveHull2D(), cloudViewer::PointProjectionTools::extractConcaveHull2D(), CVTools::ExtractDigitAlpha(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractPointCloudCPU(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractTriangleMeshCPU(), cloudViewer::t::geometry::ipp::Filter(), cloudViewer::t::geometry::ipp::FilterBilateral(), cvSelectionFilter::filterByAttributeComparison(), cloudViewer::t::geometry::ipp::FilterGaussian(), ccMesh::FilterSmoothLaplacianHelper(), cloudViewer::t::geometry::ipp::FilterSobel(), BallPivoting::FindCandidateVertex(), colmap::FindPolynomialRootsDurandKerner(), Widgets::ColorPickerButton::focusInEvent(), Widgets::ColorPickerButton::focusOutEvent(), for(), QCPAxis::generateAutoTicks(), cvConstrainedPolyLineRepresentation::GetAngle(), getCentroid(), cloudViewer::t::geometry::kernel::pointcloud::GetCoordinateSystemOnPlane(), getDensity(), QCPColorMap::getKeyRange(), getMortarMaps(), PclUtils::PCLVis::getReasonableClippingRange(), QCPBars::getStackedBaseValue(), QCPAxisTicker::getTickStep(), QCPAxisTickerDateTime::getTickStep(), QCPAxisTickerTime::getTickStep(), QCPAxisTickerFixed::getTickStep(), QCPAxisTickerPi::getTickStep(), QCPColorMap::getValueRange(), Widgets::ColorPickerPopup::hideEvent(), colmap::FOVCameraModel::InitializeParams(), cloudViewer::core::linalg::kernel::inverse2x2(), cloudViewer::core::linalg::kernel::inverse3x3(), BallPivoting::IsCompatible(), Quadric::IsInvertible(), colmap::Camera::IsUndistorted(), colmap::BaseCameraModel< CameraModel >::IterativeUndistortion(), cloudViewer::ConjugateGradient< N, Scalar >::iterConjugateGradient(), cloudViewer::visualization::gui::Interactors::Key(), cloudViewer::visualization::gui::PickPointsInteractor::Key(), cloudViewer::visualization::gui::FlyInteractor::Key(), cloudViewer::visualization::gui::PickInteractor::Key(), cloudViewer::visualization::gui::SceneWidget::Key(), cloudViewer::visualization::gui::WidgetProxy::Key(), cloudViewer::VisualizerForAlignment::KeyPressCallback(), Widgets::ColorPickerButton::keyPressEvent(), Widgets::ColorPickerPopup::keyPressEvent(), CodeEditor::keyPressEvent(), Widgets::ColorPickerButton::keyReleaseEvent(), cloudViewer::utility::IntersectionTest::LineSegmentsMinimumDistance(), cloudViewer::utility::IntersectionTest::LinesMinimumDistance(), load_pluginWrappers(), E57Filter::loadFile(), LASFilter::loadFile(), FileIOFilter::LoadFromFile(), PythonPluginManager::loadPluginsFrom(), PythonPluginManager::loadPluginsFromEntryPoints(), logWishart(), main(), cloudViewer::ml::impl::MapCylinderToCube(), cloudViewer::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget(), colmap::MapperBundleAdjustmentOptionsWidget::MapperBundleAdjustmentOptionsWidget(), cloudViewer::ml::impl::MapSphereToCylinder(), cloudViewer::visualization::gui::Interactors::Mouse(), cloudViewer::visualization::gui::Widget::Mouse(), cloudViewer::visualization::gui::PickPointsInteractor::Mouse(), cloudViewer::visualization::gui::RotateSunInteractor::Mouse(), cloudViewer::visualization::gui::RotateIBLInteractor::Mouse(), cloudViewer::visualization::gui::FlyInteractor::Mouse(), cloudViewer::visualization::gui::RotationInteractor::Mouse(), cloudViewer::visualization::gui::RotateModelInteractor::Mouse(), cloudViewer::visualization::gui::RotateCameraInteractor::Mouse(), cloudViewer::visualization::gui::PickInteractor::Mouse(), cloudViewer::visualization::gui::SceneWidget::Mouse(), cloudViewer::visualization::gui::WidgetProxy::Mouse(), SlidersWidget::mouseDoubleClickEvent(), SlidersWidget::mouseMoveEvent(), StereogramWidget::mousePressEvent(), ColorBarWidget::mousePressEvent(), SlidersWidget::mousePressEvent(), Widgets::ColorPickerPopup::mouseReleaseEvent(), cloudViewer::visualization::webrtc_server::WebRTCWindowSystem::OnDataChannelMessage(), cloudViewer::visualization::gui::Window::OnKeyEvent(), cloudViewer::visualization::gui::Window::OnMouseEvent(), cloudViewer::visualization::gui::Window::OnTextInput(), cloudViewer::visualization::gui::Window::OnTickEvent(), Edge::operator<(), ColorScheme::operator[](), cloudViewer::pipelines::registration::GlobalOptimizationLevenbergMarquardt::OptimizePoseGraph(), ccTrace::optimizeSegment(), Widgets::GradientComboBox::paintEvent(), Widgets::ColorPickerButton::paintEvent(), Widgets::QtColorPicker::paintEvent(), ColorBarWidget::paintEvent(), SliderLabelWidget::paintEvent(), Chi2Helper::pochisq(), cloudViewer::utility::IntersectionTest::PointsCoplanar(), cloudViewer::visualization::gui::BitmapWindowSystem::PostKeyEvent(), cloudViewer::visualization::gui::BitmapWindowSystem::PostMouseEvent(), cloudViewer::visualization::gui::PostNativeExposeEvent(), cloudViewer::visualization::gui::BitmapWindowSystem::PostTextInputEvent(), cloudViewer::core::sy::PrintSYCLDevices(), ccCloudLayersHelper::projectCloud(), cloudViewer::t::geometry::TriangleMesh::ProjectImagesToAlbedo(), PythonPlugin::PythonPlugin(), colmap::OptionManager::Read(), cloudViewer::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromSPLAT(), cloudViewer::t::io::ReadPointCloudFromTXT(), cloudViewer::io::ReadPointCloudFromXYZ(), cloudViewer::t::io::ReadPointCloudFromXYZI(), cloudViewer::io::ReadPointCloudFromXYZN(), cloudViewer::io::ReadPointCloudFromXYZRGB(), cloudViewer::io::ReadPointCloudInMemoryFromXYZ(), pcl::visualization::ImageViewer::registerKeyboardCallback(), pcl::visualization::ImageViewer::registerMouseCallback(), qAnimationDlg::render(), QCPColorScale::rescaleDataRange(), cloudViewer::t::geometry::ipp::Resize(), Widgets::GradientComboBox::resizeEvent(), CodeEditor::resizeEvent(), cloudViewer::t::io::RealSenseSensor::ResumeRecord(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScale(), cloudViewer::t::geometry::ipp::RGBToGray(), cloudViewer::t::geometry::OrientedBoundingBox::Rotate(), cloudViewer::AutomaticReconstructionWidget::Run(), colmap::SiftGPUFeatureMatcher::Run(), colmap::TwoViewGeometryVerifier::Run(), QCPRange::sanitizedForLogScale(), MAFilter::saveToFile(), E57Filter::saveToFile(), LASFilter::saveToFile(), ccColorScale::setAbsolute(), cvViewSelectionManager::setCurrentSelection(), setIntersectIdxPixs1D(), PythonPlugin::setMainAppInterface(), cloudViewer::t::geometry::OrientedBoundingBox::SetRotation(), ecvDisplayTools::SetView(), cloudViewer::core::linalg::kernel::solve_svd3x3(), cloudViewer::utility::SolveLinearSystemPSD(), cloudViewer::t::io::RealSenseSensor::StartCapture(), cloudViewer::visualization::GuiVisualizer::StartRPCInterface(), cloudViewer::visualization::visualizer::O3DVisualizer::StartRPCInterface(), TestEstimationWithNumCoords(), TestImageToWorldToImage(), TestWorldToImageToWorld(), cloudViewer::visualization::gui::Interactors::Tick(), cloudViewer::visualization::gui::Widget::Tick(), cloudViewer::visualization::gui::SceneWidget::Tick(), cloudViewer::visualization::gui::WidgetProxy::Tick(), cloudViewer::t::geometry::ipp::To(), cloudViewer::t::geometry::AxisAlignedBoundingBox::ToLegacy(), cloudViewer::t::pipelines::kernel::TransformationToPoseImpl(), cloudViewer::utility::TransformMatrix4dToVector6d(), cloudViewer::utility::IntersectionTest::TriangleTriangle3d(), cloudViewer::Neighbourhood::triangulateFromQuadric(), BallPivoting::TryTriangleSeed(), colmap::FOVCameraModel::Undistortion(), cloudViewer::io::rpc::UnpackStatusFromReply(), cloudViewer::pipelines::registration::UpdateConfidence(), cloudViewer::visualization::gui::FileDialog::Impl::UpdateDirectoryListing(), GrainsAsEllipsoids::updateMeshAndLineSet(), ccLineation::updateMetadata(), ccThickness::updateMetadata(), cloudViewer::pipelines::registration::HuberLoss::Weight(), cloudViewer::pipelines::registration::TukeyLoss::Weight(), ccHistogramWindow::wheelEvent(), Tiler::writeAll(), cloudViewer::io::WritePointCloudInMemoryToXYZ(), cloudViewer::io::WritePointCloudToPTS(), cloudViewer::t::io::WritePointCloudToPTS(), cloudViewer::t::io::WritePointCloudToSPLAT(), cloudViewer::t::io::WritePointCloudToTXT(), cloudViewer::io::WritePointCloudToXYZ(), cloudViewer::t::io::WritePointCloudToXYZI(), cloudViewer::io::WritePointCloudToXYZN(), cloudViewer::io::WritePointCloudToXYZRGB(), and colmap::GPSTransform::XYZToEll().
e2
double e2[36]
Definition at line 12 of file essential_matrix_poly.h.
Referenced by cloudViewer::Neighbourhood::computeMomentOrder1(), BallPivoting::CreateTriangle(), DilateClassifier(), ccCompass::estimateStructureNormals(), for(), ccColorScaleElement::IsSmaller(), ColorScaleElementSlider::IsSmaller(), logWishart(), ccMesh::SubdivideLoop(), cloudViewer::CCMiscTools::TriBoxOverlap(), cloudViewer::CCMiscTools::TriBoxOverlapd(), and BallPivoting::TrySeed().
e3
double e3[36]
Definition at line 13 of file essential_matrix_poly.h.
Referenced by ccCompass::estimateStructureNormals(), for(), and logWishart().