ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/estimators/utils_test.cc File Reference
utils_test.cc File Reference
#include "util/testing.h"
#include "base/essential_matrix.h"
#include "estimators/utils.h"
Macros
#define TEST_NAME "estimators/utils"
Functions
BOOST_AUTO_TEST_CASE (TestCenterAndNormalizeImagePoints)
BOOST_AUTO_TEST_CASE (TestComputeSquaredSampsonError)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "estimators/utils"
Definition at line 32 of file utils_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (TestCenterAndNormalizeImagePoints)
Definition at line 40 of file utils_test.cc.
References colmap::CenterAndNormalizeImagePoints(), e, and points.
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (TestComputeSquaredSampsonError)
Definition at line 63 of file utils_test.cc.
References colmap::ComputeSquaredSampsonError(), and colmap::EssentialMatrixFromPose().