ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/estimators/essential_matrix_test.cc File Reference
essential_matrix_test.cc File Reference
#include "util/testing.h"
#include <Eigen/Core>
#include "base/camera_models.h"
#include "base/essential_matrix.h"
#include "base/pose.h"
#include "base/projection.h"
#include "estimators/essential_matrix.h"
#include "optim/ransac.h"
#include "util/random.h"
Macros
#define TEST_NAME "estimators/essential_matrix"
Functions
BOOST_AUTO_TEST_CASE (TestFivePoint)
BOOST_AUTO_TEST_CASE (TestEightPoint)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "estimators/essential_matrix"
Definition at line 32 of file essential_matrix_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (TestEightPoint)
Definition at line 91 of file essential_matrix_test.cc.
References e, and colmap::EssentialMatrixEightPointEstimator::Estimate().
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (TestFivePoint)
Definition at line 47 of file essential_matrix_test.cc.
References colmap::RANSACOptions::confidence, colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::Estimate(), colmap::RANSACOptions::max_error, colmap::RANSACOptions::min_inlier_ratio, colmap::EssentialMatrixFivePointEstimator::Residuals(), and colmap::SetPRNGSeed().