ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/estmem.c File Reference
estmem.c File Reference
#include "metis.h"
Functions
void METIS_EstimateMemory (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *optype, int *nbytes)
void EstimateCFraction (int nvtxs, idxtype *xadj, idxtype *adjncy, float *vfraction, float *efraction)
int ComputeCoarseGraphSize (int nvtxs, idxtype *xadj, idxtype *adjncy, int cnvtxs, idxtype *cmap, idxtype *match, idxtype *perm)
Function Documentation
ComputeCoarseGraphSize()
int ComputeCoarseGraphSize (int nvtxs, idxtype * xadj, idxtype * adjncy, int cnvtxs, idxtype * cmap, idxtype * match, idxtype * perm)
Definition at line 111 of file estmem.c.
References GKfree, idxsmalloc, and LTERM.
Referenced by EstimateCFraction().
EstimateCFraction()
void EstimateCFraction (int nvtxs, idxtype * xadj, idxtype * adjncy, float * vfraction, float * efraction)
Definition at line 66 of file estmem.c.
References ComputeCoarseGraphSize(), GKfree, idxmalloc, idxsmalloc, LTERM, RandomPermute, and UNMATCHED.
Referenced by METIS_EstimateMemory().
METIS_EstimateMemory()
void METIS_EstimateMemory (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * optype, int * nbytes)
Definition at line 22 of file estmem.c.
References Change2CNumbering, Change2FNumbering2, EstimateCFraction(), InitRandom, NEG_GAINSPAN, and PLUS_GAINSPAN.
Referenced by METIS_ESTIMATEMEMORY(), metis_estimatememory(), metis_estimatememory_(), and metis_estimatememory__().