ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/Factor.cpp File Reference
Factor.cpp File Reference
#include <math.h>
#include "Factor.h"
Functions
int Factor (double a1, double a0, double roots[1][2], double EPS)
int Factor (double a2, double a1, double a0, double roots[2][2], double EPS)
int Factor (double a3, double a2, double a1, double a0, double roots[3][2], double EPS)
double ArcTan2 (double y, double x)
double Angle (const double in[2])
void Sqrt (const double in[2], double out[2])
void Add (const double in1[2], const double in2[2], double out[2])
void Subtract (const double in1[2], const double in2[2], double out[2])
void Multiply (const double in1[2], const double in2[2], double out[2])
void Divide (const double in1[2], const double in2[2], double out[2])
int Factor (double a4, double a3, double a2, double a1, double a0, double roots[4][2], double EPS)
int Solve (const double *eqns, const double *values, double *solutions, int dim)
Function Documentation
Add()
void Add (const double in1[2], const double in2[2], double out[2])
Definition at line 130 of file Factor.cpp.
Referenced by cloudViewer::geometry::AvgColorVoxel::Add(), cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP::ComputeRMSE(), and Factor().
Angle()
double Angle (const double in[2])
Definition at line 120 of file Factor.cpp.
ArcTan2()
double ArcTan2 (double y, double x)
Definition at line 107 of file Factor.cpp.
References PI.
Divide()
void Divide (const double in1[2], const double in2[2], double out[2])
Definition at line 142 of file Factor.cpp.
Referenced by Factor().
Factor() [1/4]
int Factor (double a1, double a0, double roots[1][2], double EPS)
Definition at line 34 of file Factor.cpp.
References cloudViewer::ml::contrib::EPS, and fabs().
Referenced by Factor().
Factor() [2/4]
int Factor (double a2, double a1, double a0, double roots[2][2], double EPS)
Definition at line 40 of file Factor.cpp.
References cloudViewer::ml::contrib::EPS, fabs(), and Factor().
Factor() [3/4]
int Factor (double a3, double a2, double a1, double a0, double roots[3][2], double EPS)
Definition at line 62 of file Factor.cpp.
References cloudViewer::ml::contrib::EPS, fabs(), Factor(), and SQRT_3.
Factor() [4/4]
int Factor (double a4, double a3, double a2, double a1, double a0, double roots[4][2], double EPS)
Definition at line 151 of file Factor.cpp.
References Add(), Divide(), cloudViewer::ml::contrib::EPS, fabs(), Factor(), Sqrt(), and Subtract().
Multiply()
void Multiply (const double in1[2], const double in2[2], double out[2])
Definition at line 138 of file Factor.cpp.
Solve()
int Solve (const double * eqns, const double * values, double * solutions, int dim)
Definition at line 210 of file Factor.cpp.
References fabs().
Sqrt()
void Sqrt (const double in[2], double out[2])
Definition at line 124 of file Factor.cpp.
Referenced by cloudViewer::t::pipelines::slac::ControlGrid::Deform(), and Factor().
Subtract()
void Subtract (const double in1[2], const double in2[2], double out[2])
Definition at line 134 of file Factor.cpp.
Referenced by Factor().