ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/FastGlobalRegistrationFilter.cpp File Reference
FastGlobalRegistrationFilter.cpp File Reference
#include "FastGlobalRegistrationFilter.h"
#include "FastGlobalRegistration.h"
#include "dialogs/FastGlobalRegistrationDlg.h"
#include <Utils/cc2sm.h>
#include <Utils/sm2cc.h>
#include "PclUtils/PCLModules.h"
#include <pcl/features/fpfh_omp.h>
#include <ecvMainAppInterface.h>
#include <ecvPointCloud.h>
#include <QMainWindow>
#include <boost/make_shared.hpp>
Functions
static bool ComputeFeatures (ccPointCloud *cloud, fgr::Features &features, double radius)
static bool ConverFromTo (const ccPointCloud &cloud, fgr::Points &points)
Variables
static constexpr int NoNormals = -11
Function Documentation
ComputeFeatures()
static bool ComputeFeatures (ccPointCloud * cloud, fgr::Features & features, double radius) static
Definition at line 75 of file FastGlobalRegistrationFilter.cpp.
References data, cc2smReader::getAsPointNormal(), cloudViewer::PointCloudTpl< T >::size(), and CVLog::Warning().
Referenced by FastGlobalRegistrationFilter::compute().
ConverFromTo()
static bool ConverFromTo (const ccPointCloud & cloud, fgr::Points & points) static
Definition at line 124 of file FastGlobalRegistrationFilter.cpp.
References cloudViewer::PointCloudTpl< T >::getPoint(), points, cloudViewer::PointCloudTpl< T >::size(), CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by FastGlobalRegistrationFilter::compute().
Variable Documentation
NoNormals
constexpr int NoNormals = -11 static constexpr
Definition at line 35 of file FastGlobalRegistrationFilter.cpp.
Referenced by FastGlobalRegistrationFilter::getErrorMessage().