ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qFacets/src/fastMarchingForFacetExtraction.cpp File Reference
fastMarchingForFacetExtraction.cpp File Reference
#include "fastMarchingForFacetExtraction.h"
#include <ecvGenericPointCloud.h>
#include <ecvOctree.h>
#include <ecvPointCloud.h>
#include <QApplication>
Functions
static bool ComputeCellStats (cloudViewer::ReferenceCloud *subset, CCVector3 &N, CCVector3 &C, ScalarType &error, cloudViewer::DistanceComputationTools::ERROR_MEASURES errorMeasure)
Variables
const int c_3dNeighboursPosShift []
26-connexity neighbouring cells positions (common edges)
Function Documentation
ComputeCellStats()
static bool ComputeCellStats (cloudViewer::ReferenceCloud * subset, CCVector3 & N, CCVector3 & C, ScalarType & error, cloudViewer::DistanceComputationTools::ERROR_MEASURES errorMeasure) static
Definition at line 42 of file fastMarchingForFacetExtraction.cpp.
References cloudViewer::DistanceComputationTools::ComputeCloud2PlaneDistance(), error(), cloudViewer::Neighbourhood::getGravityCenter(), cloudViewer::Neighbourhood::getLSPlane(), and cloudViewer::ReferenceCloud::size().
Referenced by FastMarchingForFacetExtraction::addCellToCurrentFacet(), and FastMarchingForFacetExtraction::init().
Variable Documentation
c_3dNeighboursPosShift
const int c_3dNeighboursPosShift[]
Initial value:
= {
        -1, -1, -1, -1, -1, 0,  -1, -1, 1,  -1, 0,  -1, -1, 0,  0,  -1,
        0,  1,  -1, 1,  -1, -1, 1,  0,  -1, 1,  1,  0,  -1, -1, 0,  -1,
        0,  0,  -1, 1,  0,  0,  -1, 0,  0,  1,  0,  1,  -1, 0,  1,  0,
        0,  1,  1,  1,  -1, -1, 1,  -1, 0,  1,  -1, 1,  1,  0,  -1, 1,
        0,  0,  1,  0,  1,  1,  1,  -1, 1,  1,  0,  1,  1,  1}
26-connexity neighbouring cells positions (common edges)
Definition at line 19 of file fastMarchingForFacetExtraction.cpp.