ACloudViewer: /root/ACloudViewer/plugins/core/IO/qFBXIO/src/FBXFilter.cpp File Reference
FBXFilter.cpp File Reference
#include "FBXFilter.h"
#include <ecvMaterialSet.h>
#include <ecvMesh.h>
#include <ecvNormalVectors.h>
#include <ecvPointCloud.h>
#include <fbxsdk.h>
#include <QDir>
#include <QFileInfo>
#include <QMap>
#include <QMessageBox>
#include <QPushButton>
#include <assert.h>
#include <vector>
Functions
static FbxNode * ToFbxMesh (ccGenericMesh *mesh, FbxScene *pScene, QString filename, size_t meshIndex)
static bool SaveScene (FbxManager *pManager, FbxDocument *pScene, const char *pFilename, int pFileFormat=-1, bool pEmbedMedia=false)
QString SanitizeFBXFormatString (QString format)
QString GetAttributeTypeName (FbxNodeAttribute::EType type)
static ccMesh * FromFbxMesh (FbxMesh *fbxMesh, FileIOFilter::LoadParameters &parameters)
Variables
static const char FBX_SCALE_METADATA_KEY [] = "FBX:ScaleToCM"
static QString s_defaultOutputFormat
Function Documentation
FromFbxMesh()
static ccMesh* FromFbxMesh (FbxMesh * fbxMesh, FileIOFilter::LoadParameters & parameters) static
Definition at line 750 of file FBXFilter.cpp.
References ccHObject::addChild(), ccArray< Type, N, ComponentType >::addElement(), ccMaterialSet::addMaterial(), ccPointCloud::addNorm(), cloudViewer::PointCloudTpl< T >::addPoint(), ccPointCloud::addRGBColor(), ccMesh::addTriangle(), ccMesh::addTriangleMtlIndex(), ccMesh::addTriangleNormalIndexes(), ccMesh::addTriangleTexCoordIndexes(), ccArray< Type, N, ComponentType >::currentSize(), Vector3Tpl< PointCoordinateType >::fromArray(), ccNormalVectors::GetNormIndex(), FileIOFilter::HandleGlobalShift(), ccMesh::hasPerTriangleMtlIndexes(), ecvColor::MAX, normals, CVLog::PrintDebug(), CCShareable::release(), ccHObject::removeChild(), ccMesh::reserve(), ccPointCloud::reserve(), ccMesh::reservePerTriangleMtlIndexes(), ccMesh::reservePerTriangleNormalIndexes(), ccMesh::reservePerTriangleTexCoordIndexes(), ccArray< Type, N, ComponentType >::reserveSafe(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveTheRGBTable(), ecvColor::RgbaTpl< Type >::rgba, ccObject::setEnabled(), ccShiftedObject::setGlobalShift(), ccMesh::setMaterialSet(), ccObject::setName(), ccMesh::setTexCoordinatesTable(), ccMesh::setTriNormsTable(), ccDrawableObject::showColors(), ccGenericMesh::showMaterials(), ccDrawableObject::showNormals(), ccGenericMesh::showNormals(), ccMesh::size(), Tuple3Tpl< Type >::u, uv, CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by FBXFilter::loadFile().
GetAttributeTypeName()
QString GetAttributeTypeName (FbxNodeAttribute::EType type)
Definition at line 700 of file FBXFilter.cpp.
References type.
Referenced by FBXFilter::loadFile().
SanitizeFBXFormatString()
QString SanitizeFBXFormatString (QString format)
Definition at line 461 of file FBXFilter.cpp.
References format.
Referenced by FBXFilter::saveToFile().
SaveScene()
static bool SaveScene (FbxManager * pManager, FbxDocument * pScene, const char * pFilename, int pFileFormat = -1, bool pEmbedMedia = false) static
Definition at line 393 of file FBXFilter.cpp.
References CVLog::Warning().
Referenced by FBXFilter::saveToFile().
ToFbxMesh()
static FbxNode* ToFbxMesh (ccGenericMesh * mesh, FbxScene * pScene, QString filename, size_t meshIndex) static
Definition at line 51 of file FBXFilter.cpp.
References ecvColor::RgbTpl< Type >::b, ecvColor::RgbaTpl< Type >::b, count, ccArray< Type, N, ComponentType >::currentSize(), filename, ecvColor::RgbTpl< Type >::g, ecvColor::RgbaTpl< Type >::g, ccGenericMesh::getAssociatedCloud(), ccMesh::getMaterialSet(), ccObject::getName(), ccNormalVectors::GetNormal(), cloudViewer::GenericIndexedCloud::getPoint(), ccGenericPointCloud::getPointColor(), ccGenericPointCloud::getPointNormal(), ccMesh::getTexCoordinatesTable(), ccMaterial::GetTexture(), ccMesh::getTriangleMtlIndex(), ccMesh::getTriangleNormalIndexes(), ccGenericMesh::getTriangleNormals(), ccMesh::getTriangleTexCoordinatesIndexes(), cloudViewer::GenericIndexedMesh::getTriangleVertIndexes(), ccMesh::getTriNormsTable(), ccArray< Type, N, ComponentType >::getValue(), ccDrawableObject::hasColors(), ccMesh::hasMaterials(), ccDrawableObject::hasNormals(), ccMesh::hasPerTriangleTexCoordIndexes(), ccMesh::hasTextures(), ccGenericMesh::hasTriNormals(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, image, ccObject::isA(), ecvColor::MAX, CV_TYPES::MESH, CVLog::PrintDebug(), ecvColor::RgbTpl< Type >::r, ecvColor::RgbaTpl< Type >::r, cloudViewer::GenericCloud::size(), cloudViewer::GenericMesh::size(), ccMesh::size(), uv, CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by FBXFilter::saveToFile().
Variable Documentation
FBX_SCALE_METADATA_KEY
const char FBX_SCALE_METADATA_KEY[] = "FBX:ScaleToCM" static
Definition at line 31 of file FBXFilter.cpp.
Referenced by FBXFilter::loadFile(), and FBXFilter::saveToFile().
s_defaultOutputFormat
QString s_defaultOutputFormat static
Definition at line 455 of file FBXFilter.cpp.
Referenced by FBXFilter::saveToFile(), and FBXFilter::SetDefaultOutputFormat().