ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/feature/utils_test.cc File Reference
utils_test.cc File Reference
#include "util/testing.h"
#include "feature/utils.h"
Macros
#define TEST_NAME "feature/utils"
Functions
BOOST_AUTO_TEST_CASE (TestFeatureKeypointsToPointsVector)
BOOST_AUTO_TEST_CASE (TestL2NormalizeFeatureDescriptors)
BOOST_AUTO_TEST_CASE (TestL1RootNormalizeFeatureDescriptors)
BOOST_AUTO_TEST_CASE (TestFeatureDescriptorsToUnsignedByte)
BOOST_AUTO_TEST_CASE (TestExtractTopScaleFeatures)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "feature/utils"
Definition at line 32 of file utils_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/5]
BOOST_AUTO_TEST_CASE (TestExtractTopScaleFeatures)
Definition at line 83 of file utils_test.cc.
References descriptors, and colmap::ExtractTopScaleFeatures().
BOOST_AUTO_TEST_CASE() [2/5]
BOOST_AUTO_TEST_CASE (TestFeatureDescriptorsToUnsignedByte)
Definition at line 69 of file utils_test.cc.
References descriptors, and colmap::FeatureDescriptorsToUnsignedByte().
BOOST_AUTO_TEST_CASE() [3/5]
BOOST_AUTO_TEST_CASE (TestFeatureKeypointsToPointsVector)
Definition at line 39 of file utils_test.cc.
References colmap::FeatureKeypointsToPointsVector(), and points.
BOOST_AUTO_TEST_CASE() [4/5]
BOOST_AUTO_TEST_CASE (TestL1RootNormalizeFeatureDescriptors)
Definition at line 59 of file utils_test.cc.
References descriptors, e, and colmap::L1RootNormalizeFeatureDescriptors().
BOOST_AUTO_TEST_CASE() [5/5]
BOOST_AUTO_TEST_CASE (TestL2NormalizeFeatureDescriptors)
Definition at line 49 of file utils_test.cc.
References descriptors, e, and colmap::L2NormalizeFeatureDescriptors().