ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/FLANN/mpi/flann_mpi_client.cpp File Reference
flann_mpi_client.cpp File Reference
#include <stdio.h>
#include <time.h>
#include <cstdlib>
#include <iostream>
#include <FLANN/util/params.h>
#include <FLANN/io/hdf5.h>
#include <FLANN/mpi/client.h>
Macros
#define IF_RANK0 if (world.rank()==0)
Functions
void start_timer (const std::string &message="")
double stop_timer ()
float compute_precision (const flann::Matrix< int > &match, const flann::Matrix< int > &indices)
int main (int argc, char *argv[])
Variables
timeval start_time_
Macro Definition Documentation
IF_RANK0
#define IF_RANK0 if (world.rank()==0)
Definition at line 12 of file flann_mpi_client.cpp.
Function Documentation
compute_precision()
float compute_precision (const flann::Matrix< int > & match, const flann::Matrix< int > & indices)
Definition at line 32 of file flann_mpi_client.cpp.
References flann::Matrix_::cols, count, min(), and flann::Matrix_::rows.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 53 of file flann_mpi_client.cpp.
References compute_precision(), flann::mpi::Client::knnSearch(), flann::load_from_file(), flann::Matrix_::rows, start_timer(), and stop_timer().
start_timer()
void start_timer (const std::string & message = "")
Definition at line 15 of file flann_mpi_client.cpp.
References NULL, and start_time_.
Referenced by main().
stop_timer()
double stop_timer ()
Definition at line 24 of file flann_mpi_client.cpp.
References NULL, and start_time_.
Referenced by main().
Variable Documentation
start_time_
timeval start_time_
Definition at line 14 of file flann_mpi_client.cpp.
Referenced by start_timer(), and stop_timer().