ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/frename.c File Reference
frename.c File Reference
#include "metis.h"
Functions
void METIS_PARTGRAPHRECURSIVE (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void metis_partgraphrecursive (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void metis_partgraphrecursive_ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void metis_partgraphrecursive__ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void METIS_WPARTGRAPHRECURSIVE (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *edgecut, idxtype *part)
void metis_wpartgraphrecursive (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *edgecut, idxtype *part)
void metis_wpartgraphrecursive_ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *edgecut, idxtype *part)
void metis_wpartgraphrecursive__ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *edgecut, idxtype *part)
void METIS_PARTGRAPHKWAY (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void metis_partgraphkway (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void metis_partgraphkway_ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void metis_partgraphkway__ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void METIS_WPARTGRAPHKWAY (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *edgecut, idxtype *part)
void metis_wpartgraphkway (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *edgecut, idxtype *part)
void metis_wpartgraphkway_ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *edgecut, idxtype *part)
void metis_wpartgraphkway__ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *edgecut, idxtype *part)
void METIS_EDGEND (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void metis_edgend (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void metis_edgend_ (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void metis_edgend__ (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void METIS_NODEND (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void metis_nodend (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void metis_nodend_ (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void metis_nodend__ (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void METIS_NODEWND (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void metis_nodewnd (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void metis_nodewnd_ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void metis_nodewnd__ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void METIS_PARTMESHNODAL (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, int *nparts, int *edgecut, idxtype *epart, idxtype *npart)
void metis_partmeshnodal (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, int *nparts, int *edgecut, idxtype *epart, idxtype *npart)
void metis_partmeshnodal_ (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, int *nparts, int *edgecut, idxtype *epart, idxtype *npart)
void metis_partmeshnodal__ (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, int *nparts, int *edgecut, idxtype *epart, idxtype *npart)
void METIS_PARTMESHDUAL (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, int *nparts, int *edgecut, idxtype *epart, idxtype *npart)
void metis_partmeshdual (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, int *nparts, int *edgecut, idxtype *epart, idxtype *npart)
void metis_partmeshdual_ (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, int *nparts, int *edgecut, idxtype *epart, idxtype *npart)
void metis_partmeshdual__ (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, int *nparts, int *edgecut, idxtype *epart, idxtype *npart)
void METIS_MESHTONODAL (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, idxtype *dxadj, idxtype *dadjncy)
void metis_meshtonodal (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, idxtype *dxadj, idxtype *dadjncy)
void metis_meshtonodal_ (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, idxtype *dxadj, idxtype *dadjncy)
void metis_meshtonodal__ (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, idxtype *dxadj, idxtype *dadjncy)
void METIS_MESHTODUAL (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, idxtype *dxadj, idxtype *dadjncy)
void metis_meshtodual (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, idxtype *dxadj, idxtype *dadjncy)
void metis_meshtodual_ (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, idxtype *dxadj, idxtype *dadjncy)
void metis_meshtodual__ (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, idxtype *dxadj, idxtype *dadjncy)
void METIS_ESTIMATEMEMORY (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *optype, int *nbytes)
void metis_estimatememory (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *optype, int *nbytes)
void metis_estimatememory_ (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *optype, int *nbytes)
void metis_estimatememory__ (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *optype, int *nbytes)
void METIS_MCPARTGRAPHRECURSIVE (int *nvtxs, int *ncon, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void metis_mcpartgraphrecursive (int *nvtxs, int *ncon, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void metis_mcpartgraphrecursive_ (int *nvtxs, int *ncon, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void metis_mcpartgraphrecursive__ (int *nvtxs, int *ncon, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void METIS_MCPARTGRAPHKWAY (int *nvtxs, int *ncon, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *rubvec, int *options, int *edgecut, idxtype *part)
void metis_mcpartgraphkway (int *nvtxs, int *ncon, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *rubvec, int *options, int *edgecut, idxtype *part)
void metis_mcpartgraphkway_ (int *nvtxs, int *ncon, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *rubvec, int *options, int *edgecut, idxtype *part)
void metis_mcpartgraphkway__ (int *nvtxs, int *ncon, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *rubvec, int *options, int *edgecut, idxtype *part)
void METIS_PARTGRAPHVKWAY (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *vsize, int *wgtflag, int *numflag, int *nparts, int *options, int *volume, idxtype *part)
void metis_partgraphvkway (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *vsize, int *wgtflag, int *numflag, int *nparts, int *options, int *volume, idxtype *part)
void metis_partgraphvkway_ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *vsize, int *wgtflag, int *numflag, int *nparts, int *options, int *volume, idxtype *part)
void metis_partgraphvkway__ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *vsize, int *wgtflag, int *numflag, int *nparts, int *options, int *volume, idxtype *part)
void METIS_WPARTGRAPHVKWAY (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *vsize, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *volume, idxtype *part)
void metis_wpartgraphvkway (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *vsize, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *volume, idxtype *part)
void metis_wpartgraphvkway_ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *vsize, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *volume, idxtype *part)
void metis_wpartgraphvkway__ (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *vsize, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *volume, idxtype *part)
Function Documentation
METIS_EDGEND()
void METIS_EDGEND (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 93 of file frename.c.
References METIS_EdgeND().
metis_edgend()
void metis_edgend (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 97 of file frename.c.
References METIS_EdgeND().
metis_edgend_()
void metis_edgend_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 101 of file frename.c.
References METIS_EdgeND().
metis_edgend__()
void metis_edgend__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 105 of file frename.c.
References METIS_EdgeND().
METIS_ESTIMATEMEMORY()
void METIS_ESTIMATEMEMORY (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * optype, int * nbytes)
Definition at line 222 of file frename.c.
References METIS_EstimateMemory().
metis_estimatememory()
void metis_estimatememory (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * optype, int * nbytes)
Definition at line 226 of file frename.c.
References METIS_EstimateMemory().
metis_estimatememory_()
void metis_estimatememory_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * optype, int * nbytes)
Definition at line 230 of file frename.c.
References METIS_EstimateMemory().
metis_estimatememory__()
void metis_estimatememory__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * optype, int * nbytes)
Definition at line 234 of file frename.c.
References METIS_EstimateMemory().
METIS_MCPARTGRAPHKWAY()
void METIS_MCPARTGRAPHKWAY (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * rubvec, int * options, int * edgecut, idxtype * part)
Definition at line 259 of file frename.c.
References METIS_mCPartGraphKway().
metis_mcpartgraphkway()
void metis_mcpartgraphkway (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * rubvec, int * options, int * edgecut, idxtype * part)
Definition at line 263 of file frename.c.
References METIS_mCPartGraphKway().
metis_mcpartgraphkway_()
void metis_mcpartgraphkway_ (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * rubvec, int * options, int * edgecut, idxtype * part)
Definition at line 267 of file frename.c.
References METIS_mCPartGraphKway().
metis_mcpartgraphkway__()
void metis_mcpartgraphkway__ (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * rubvec, int * options, int * edgecut, idxtype * part)
Definition at line 271 of file frename.c.
References METIS_mCPartGraphKway().
METIS_MCPARTGRAPHRECURSIVE()
void METIS_MCPARTGRAPHRECURSIVE (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 241 of file frename.c.
References METIS_mCPartGraphRecursive().
metis_mcpartgraphrecursive()
void metis_mcpartgraphrecursive (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 245 of file frename.c.
References METIS_mCPartGraphRecursive().
metis_mcpartgraphrecursive_()
void metis_mcpartgraphrecursive_ (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 249 of file frename.c.
References METIS_mCPartGraphRecursive().
metis_mcpartgraphrecursive__()
void metis_mcpartgraphrecursive__ (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 253 of file frename.c.
References METIS_mCPartGraphRecursive().
METIS_MESHTODUAL()
void METIS_MESHTODUAL (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 204 of file frename.c.
References METIS_MeshToDual().
metis_meshtodual()
void metis_meshtodual (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 208 of file frename.c.
References METIS_MeshToDual().
metis_meshtodual_()
void metis_meshtodual_ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 212 of file frename.c.
References METIS_MeshToDual().
metis_meshtodual__()
void metis_meshtodual__ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 216 of file frename.c.
References METIS_MeshToDual().
METIS_MESHTONODAL()
void METIS_MESHTONODAL (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 186 of file frename.c.
References METIS_MeshToNodal().
metis_meshtonodal()
void metis_meshtonodal (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 190 of file frename.c.
References METIS_MeshToNodal().
metis_meshtonodal_()
void metis_meshtonodal_ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 194 of file frename.c.
References METIS_MeshToNodal().
metis_meshtonodal__()
void metis_meshtonodal__ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 198 of file frename.c.
References METIS_MeshToNodal().
METIS_NODEND()
void METIS_NODEND (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 112 of file frename.c.
References GRACLUS_METIS_NodeND().
metis_nodend()
void metis_nodend (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 116 of file frename.c.
References GRACLUS_METIS_NodeND().
metis_nodend_()
void metis_nodend_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 120 of file frename.c.
References GRACLUS_METIS_NodeND().
metis_nodend__()
void metis_nodend__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 124 of file frename.c.
References GRACLUS_METIS_NodeND().
METIS_NODEWND()
void METIS_NODEWND (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 131 of file frename.c.
References METIS_NodeWND().
metis_nodewnd()
void metis_nodewnd (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 135 of file frename.c.
References METIS_NodeWND().
metis_nodewnd_()
void metis_nodewnd_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 139 of file frename.c.
References METIS_NodeWND().
metis_nodewnd__()
void metis_nodewnd__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 143 of file frename.c.
References METIS_NodeWND().
METIS_PARTGRAPHKWAY()
void METIS_PARTGRAPHKWAY (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 55 of file frename.c.
References METIS_PartGraphKway().
metis_partgraphkway()
void metis_partgraphkway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 59 of file frename.c.
References METIS_PartGraphKway().
metis_partgraphkway_()
void metis_partgraphkway_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 63 of file frename.c.
References METIS_PartGraphKway().
metis_partgraphkway__()
void metis_partgraphkway__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 67 of file frename.c.
References METIS_PartGraphKway().
METIS_PARTGRAPHRECURSIVE()
void METIS_PARTGRAPHRECURSIVE (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 18 of file frename.c.
References METIS_PartGraphRecursive().
metis_partgraphrecursive()
void metis_partgraphrecursive (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 22 of file frename.c.
References METIS_PartGraphRecursive().
metis_partgraphrecursive_()
void metis_partgraphrecursive_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 26 of file frename.c.
References METIS_PartGraphRecursive().
metis_partgraphrecursive__()
void metis_partgraphrecursive__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 30 of file frename.c.
References METIS_PartGraphRecursive().
METIS_PARTGRAPHVKWAY()
void METIS_PARTGRAPHVKWAY (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, int * options, int * volume, idxtype * part)
Definition at line 277 of file frename.c.
References METIS_PartGraphVKway().
metis_partgraphvkway()
void metis_partgraphvkway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, int * options, int * volume, idxtype * part)
Definition at line 281 of file frename.c.
References METIS_PartGraphVKway().
metis_partgraphvkway_()
void metis_partgraphvkway_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, int * options, int * volume, idxtype * part)
Definition at line 285 of file frename.c.
References METIS_PartGraphVKway().
metis_partgraphvkway__()
void metis_partgraphvkway__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, int * options, int * volume, idxtype * part)
Definition at line 289 of file frename.c.
References METIS_PartGraphVKway().
METIS_PARTMESHDUAL()
void METIS_PARTMESHDUAL (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 168 of file frename.c.
References METIS_PartMeshDual().
metis_partmeshdual()
void metis_partmeshdual (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 172 of file frename.c.
References METIS_PartMeshDual().
metis_partmeshdual_()
void metis_partmeshdual_ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 176 of file frename.c.
References METIS_PartMeshDual().
metis_partmeshdual__()
void metis_partmeshdual__ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 180 of file frename.c.
References METIS_PartMeshDual().
METIS_PARTMESHNODAL()
void METIS_PARTMESHNODAL (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 150 of file frename.c.
References METIS_PartMeshNodal().
metis_partmeshnodal()
void metis_partmeshnodal (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 154 of file frename.c.
References METIS_PartMeshNodal().
metis_partmeshnodal_()
void metis_partmeshnodal_ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 158 of file frename.c.
References METIS_PartMeshNodal().
metis_partmeshnodal__()
void metis_partmeshnodal__ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 162 of file frename.c.
References METIS_PartMeshNodal().
METIS_WPARTGRAPHKWAY()
void METIS_WPARTGRAPHKWAY (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 74 of file frename.c.
References METIS_WPartGraphKway().
metis_wpartgraphkway()
void metis_wpartgraphkway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 78 of file frename.c.
References METIS_WPartGraphKway().
metis_wpartgraphkway_()
void metis_wpartgraphkway_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 82 of file frename.c.
References METIS_WPartGraphKway().
metis_wpartgraphkway__()
void metis_wpartgraphkway__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 86 of file frename.c.
References METIS_WPartGraphKway().
METIS_WPARTGRAPHRECURSIVE()
void METIS_WPARTGRAPHRECURSIVE (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 36 of file frename.c.
References METIS_WPartGraphRecursive().
metis_wpartgraphrecursive()
void metis_wpartgraphrecursive (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 40 of file frename.c.
References METIS_WPartGraphRecursive().
metis_wpartgraphrecursive_()
void metis_wpartgraphrecursive_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 44 of file frename.c.
References METIS_WPartGraphRecursive().
metis_wpartgraphrecursive__()
void metis_wpartgraphrecursive__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 48 of file frename.c.
References METIS_WPartGraphRecursive().
METIS_WPARTGRAPHVKWAY()
void METIS_WPARTGRAPHVKWAY (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * volume, idxtype * part)
Definition at line 294 of file frename.c.
References METIS_WPartGraphVKway().
metis_wpartgraphvkway()
void metis_wpartgraphvkway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * volume, idxtype * part)
Definition at line 298 of file frename.c.
References METIS_WPartGraphVKway().
metis_wpartgraphvkway_()
void metis_wpartgraphvkway_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * volume, idxtype * part)
Definition at line 302 of file frename.c.
References METIS_WPartGraphVKway().
metis_wpartgraphvkway__()
void metis_wpartgraphvkway__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * volume, idxtype * part)
Definition at line 306 of file frename.c.
References METIS_WPartGraphVKway().