ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/GenericTriangle.cpp File Reference
GenericTriangle.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <GenericTriangle.h>
Functions
void define_GenericTriangle (py::module &cccorelib)
Function Documentation
define_GenericTriangle()
void define_GenericTriangle (py::module & cccorelib)
Definition at line 17 of file GenericTriangle.cpp.
References cloudViewer::GenericTriangle::_getA(), cloudViewer::GenericTriangle::_getB(), and cloudViewer::GenericTriangle::_getC().
Referenced by define_cccorelib().