ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/GenericDistribution.cpp File Reference
GenericDistribution.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <GenericCloud.h>
#include <GenericDistribution.h>
#include "cccorelib.h"
Functions
void define_GenericDistribution (py::module &cccorelib)
Function Documentation
define_GenericDistribution()
void define_GenericDistribution (py::module & cccorelib)
Definition at line 20 of file GenericDistribution.cpp.
References cloudViewer::GenericDistribution::computeChi2Dist(), cloudViewer::GenericDistribution::computeP(), cloudViewer::GenericDistribution::computeParameters(), cloudViewer::GenericDistribution::computePfromZero(), cloudViewer::GenericDistribution::getName(), and cloudViewer::GenericDistribution::isValid().
Referenced by define_cccorelib().