ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/estimators/generalized_absolute_pose_test.cc File Reference
generalized_absolute_pose_test.cc File Reference
#include "util/testing.h"
#include <array>
#include <Eigen/Core>
#include "base/pose.h"
#include "base/projection.h"
#include "base/similarity_transform.h"
#include "estimators/generalized_absolute_pose.h"
#include "optim/ransac.h"
#include "util/random.h"
Macros
#define TEST_NAME "base/generalized_absolute_pose"
Functions
BOOST_AUTO_TEST_CASE (Estimate)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/generalized_absolute_pose"
Definition at line 32 of file generalized_absolute_pose_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE()
BOOST_AUTO_TEST_CASE (Estimate)
Definition at line 48 of file generalized_absolute_pose_test.cc.
References colmap::ComposeProjectionMatrix(), colmap::ComputeRelativePose(), e, colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::Estimate(), colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::estimator, colmap::RANSACOptions::max_error, and colmap::SetPRNGSeed().