ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/GenericMesh.cpp File Reference
GenericMesh.cpp File Reference
#include <pybind11/pybind11.h>
#include <GenericMesh.h>
#include <GenericTriangle.h>
Functions
void define_GenericMesh (py::module &cccorelib)
Function Documentation
define_GenericMesh()
void define_GenericMesh (py::module & cccorelib)
Definition at line 16 of file GenericMesh.cpp.
References cloudViewer::GenericMesh::_getNextTriangle(), cloudViewer::GenericMesh::forEach(), cloudViewer::GenericMesh::getBoundingBox(), cloudViewer::GenericMesh::placeIteratorAtBeginning(), and cloudViewer::GenericMesh::size().
Referenced by define_cccorelib().