ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/GenericIndexedMesh.cpp File Reference
GenericIndexedMesh.cpp File Reference
#include <pybind11/pybind11.h>
#include <GenericIndexedMesh.h>
#include <GenericMesh.h>
#include <GenericTriangle.h>
Functions
void define_GenericIndexedMesh (py::module &cccorelib)
Function Documentation
define_GenericIndexedMesh()
void define_GenericIndexedMesh (py::module & cccorelib)
Definition at line 17 of file GenericIndexedMesh.cpp.
References cloudViewer::GenericIndexedMesh::_getTriangle(), cloudViewer::GenericIndexedMesh::getNextTriangleVertIndexes(), cloudViewer::VerticesIndexes::i1, cloudViewer::VerticesIndexes::i2, cloudViewer::VerticesIndexes::i3, and size.
Referenced by define_cccorelib().