ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/GenericProgressCallback.cpp File Reference
GenericProgressCallback.cpp File Reference
#include <pybind11/pybind11.h>
#include <GenericProgressCallback.h>
Functions
void define_GenericProgressCallback (py::module &cccorelib)
Function Documentation
define_GenericProgressCallback()
void define_GenericProgressCallback (py::module & cccorelib)
Definition at line 15 of file GenericProgressCallback.cpp.
References cloudViewer::GenericProgressCallback::isCancelRequested(), cloudViewer::NormalizedProgress::oneStep(), cloudViewer::NormalizedProgress::reset(), cloudViewer::NormalizedProgress::scale(), cloudViewer::GenericProgressCallback::setInfo(), cloudViewer::GenericProgressCallback::setMethodTitle(), cloudViewer::GenericProgressCallback::start(), cloudViewer::NormalizedProgress::steps(), cloudViewer::GenericProgressCallback::stop(), cloudViewer::GenericProgressCallback::textCanBeEdited(), and cloudViewer::GenericProgressCallback::update().
Referenced by define_cccorelib().