ACloudViewer: /root/ACloudViewer/libs/cloudViewer/t/geometry/kernel/GeometryMacros.h File Reference
GeometryMacros.h File Reference
#include <cmath>
#include "cloudViewer/core/CUDAUtils.h"
Namespaces
cloudViewer
Generic file read and write utility for python interface.
Macros
#define OPEN3D_ATOMIC_ADD(X, Y) (*X).fetch_add(Y)
#define CLOUDVIEWER_ATOMIC_ADD(X, Y) OPEN3D_ATOMIC_ADD(X, Y)
Functions
template<typename scalar_t , typename T >
CLOUDVIEWER_HOST_DEVICE bool cloudViewer::IsClose (const scalar_t &x, const T &y, const double rtol=1e-4)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE scalar_t cloudViewer::Square (const scalar_t &x)
CLOUDVIEWER_HOST_DEVICE int Sign (int x)
Macro Definition Documentation
CLOUDVIEWER_ATOMIC_ADD
#define CLOUDVIEWER_ATOMIC_ADD (X, Y) OPEN3D_ATOMIC_ADD(X, Y)
Definition at line 44 of file GeometryMacros.h.
OPEN3D_ATOMIC_ADD
#define OPEN3D_ATOMIC_ADD (X, Y) (*X).fetch_add(Y)
Definition at line 39 of file GeometryMacros.h.
Function Documentation
Sign()
CLOUDVIEWER_HOST_DEVICE int Sign (int x) inline
Definition at line 82 of file GeometryMacros.h.
Referenced by cloudViewer::t::geometry::kernel::voxel_grid::DeviceGetLinearIdx(), cloudViewer::t::pipelines::kernel::odometry::HuberDeriv(), and cloudViewer::t::geometry::kernel::voxel_grid::RayCastCPU().