ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/retrieval/geometry_test.cc File Reference
geometry_test.cc File Reference
#include <boost/test/unit_test.hpp>
#include <Eigen/Dense>
#include <iostream>
#include "retrieval/geometry.h"
Macros
#define BOOST_TEST_MAIN
#define BOOST_TEST_MODULE "retrieval/geometry"
Functions
BOOST_AUTO_TEST_CASE (TestIdentity)
BOOST_AUTO_TEST_CASE (TestTranslation)
BOOST_AUTO_TEST_CASE (TestScale)
BOOST_AUTO_TEST_CASE (TestOrientation)
Macro Definition Documentation
BOOST_TEST_MAIN
#define BOOST_TEST_MAIN
Definition at line 32 of file geometry_test.cc.
BOOST_TEST_MODULE
#define BOOST_TEST_MODULE "retrieval/geometry"
Definition at line 33 of file geometry_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (TestIdentity)
Definition at line 43 of file geometry_test.cc.
References e, colmap::retrieval::FeatureGeometry::orientation, colmap::retrieval::FeatureGeometry::scale, colmap::retrieval::FeatureGeometry::TransformFromMatch(), colmap::retrieval::FeatureGeometry::TransformMatrixFromMatch(), x, colmap::retrieval::FeatureGeometry::x, y, and colmap::retrieval::FeatureGeometry::y.
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (TestOrientation)
Definition at line 119 of file geometry_test.cc.
References e, colmap::retrieval::FeatureGeometry::orientation, colmap::retrieval::FeatureGeometry::scale, colmap::retrieval::FeatureGeometry::TransformFromMatch(), and colmap::retrieval::FeatureGeometry::TransformMatrixFromMatch().
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (TestScale)
Definition at line 99 of file geometry_test.cc.
References e, colmap::retrieval::FeatureGeometry::orientation, colmap::retrieval::FeatureGeometry::scale, colmap::retrieval::FeatureGeometry::TransformFromMatch(), and colmap::retrieval::FeatureGeometry::TransformMatrixFromMatch().
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (TestTranslation)
Definition at line 74 of file geometry_test.cc.
References e, colmap::retrieval::FeatureGeometry::orientation, colmap::retrieval::FeatureGeometry::scale, colmap::retrieval::FeatureGeometry::TransformFromMatch(), colmap::retrieval::FeatureGeometry::TransformMatrixFromMatch(), x, colmap::retrieval::FeatureGeometry::x, y, and colmap::retrieval::FeatureGeometry::y.