ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/gps_test.cc File Reference
gps_test.cc File Reference
#include "util/testing.h"
#include "base/gps.h"
Macros
#define TEST_NAME "base/gps"
Functions
BOOST_AUTO_TEST_CASE (TestEllToXYZGRS80)
BOOST_AUTO_TEST_CASE (TestEllToXYZWGS84)
BOOST_AUTO_TEST_CASE (TestXYZToEll_GRS80)
BOOST_AUTO_TEST_CASE (TestXYZToEll_WGS84)
BOOST_AUTO_TEST_CASE (TestXYZToEllToXYZ_GRS80)
BOOST_AUTO_TEST_CASE (TestXYZToEllToXYZ_WGS84)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/gps"
Definition at line 32 of file gps_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/6]
BOOST_AUTO_TEST_CASE (TestEllToXYZGRS80)
Definition at line 39 of file gps_test.cc.
References e, colmap::GPSTransform::EllToXYZ(), and colmap::GPSTransform::GRS80.
BOOST_AUTO_TEST_CASE() [2/6]
BOOST_AUTO_TEST_CASE (TestEllToXYZWGS84)
Definition at line 62 of file gps_test.cc.
References e, colmap::GPSTransform::EllToXYZ(), and colmap::GPSTransform::WGS84.
BOOST_AUTO_TEST_CASE() [3/6]
BOOST_AUTO_TEST_CASE (TestXYZToEll_GRS80)
Definition at line 85 of file gps_test.cc.
References e, colmap::GPSTransform::GRS80, and colmap::GPSTransform::XYZToEll().
BOOST_AUTO_TEST_CASE() [4/6]
BOOST_AUTO_TEST_CASE (TestXYZToEll_WGS84)
Definition at line 108 of file gps_test.cc.
References e, colmap::GPSTransform::WGS84, and colmap::GPSTransform::XYZToEll().
BOOST_AUTO_TEST_CASE() [5/6]
BOOST_AUTO_TEST_CASE (TestXYZToEllToXYZ_GRS80)
Definition at line 131 of file gps_test.cc.
References e, colmap::GPSTransform::EllToXYZ(), colmap::GPSTransform::GRS80, and colmap::GPSTransform::XYZToEll().
BOOST_AUTO_TEST_CASE() [6/6]
BOOST_AUTO_TEST_CASE (TestXYZToEllToXYZ_WGS84)
Definition at line 150 of file gps_test.cc.
References e, colmap::GPSTransform::EllToXYZ(), colmap::GPSTransform::WGS84, and colmap::GPSTransform::XYZToEll().