ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/image_test.cc File Reference
image_test.cc File Reference
#include "util/testing.h"
#include "base/image.h"
Macros
#define TEST_NAME "base/image"
Functions
BOOST_AUTO_TEST_CASE (TestDefault)
BOOST_AUTO_TEST_CASE (TestImageId)
BOOST_AUTO_TEST_CASE (TestName)
BOOST_AUTO_TEST_CASE (TestCameraId)
BOOST_AUTO_TEST_CASE (TestRegistered)
BOOST_AUTO_TEST_CASE (TestNumPoints2D)
BOOST_AUTO_TEST_CASE (TestNumPoints3D)
BOOST_AUTO_TEST_CASE (TestNumObservations)
BOOST_AUTO_TEST_CASE (TestNumCorrespondences)
BOOST_AUTO_TEST_CASE (TestNumVisiblePoints3D)
BOOST_AUTO_TEST_CASE (TestPoint3DVisibilityScore)
BOOST_AUTO_TEST_CASE (TestQvec)
BOOST_AUTO_TEST_CASE (TestQvecPrior)
BOOST_AUTO_TEST_CASE (TestTvec)
BOOST_AUTO_TEST_CASE (TestTvecPrior)
BOOST_AUTO_TEST_CASE (TestPoints2D)
BOOST_AUTO_TEST_CASE (TestPoint3D)
BOOST_AUTO_TEST_CASE (TestNormalizeQvec)
BOOST_AUTO_TEST_CASE (TestProjectionMatrix)
BOOST_AUTO_TEST_CASE (TestInverseProjectionMatrix)
BOOST_AUTO_TEST_CASE (TestRotationMatrix)
BOOST_AUTO_TEST_CASE (TestProjectionCenter)
BOOST_AUTO_TEST_CASE (TestViewingDirection)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/image"
Definition at line 32 of file image_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/23]
BOOST_AUTO_TEST_CASE (TestCameraId)
Definition at line 87 of file image_test.cc.
References image, and colmap::kInvalidCameraId.
BOOST_AUTO_TEST_CASE() [2/23]
BOOST_AUTO_TEST_CASE (TestDefault)
Definition at line 39 of file image_test.cc.
References image, colmap::IsNaN(), colmap::kInvalidCameraId, and colmap::kInvalidImageId.
BOOST_AUTO_TEST_CASE() [3/23]
BOOST_AUTO_TEST_CASE (TestImageId)
Definition at line 71 of file image_test.cc.
References image, and colmap::kInvalidImageId.
BOOST_AUTO_TEST_CASE() [4/23]
BOOST_AUTO_TEST_CASE (TestInverseProjectionMatrix)
Definition at line 350 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [5/23]
BOOST_AUTO_TEST_CASE (TestName)
Definition at line 78 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [6/23]
BOOST_AUTO_TEST_CASE (TestNormalizeQvec)
Definition at line 336 of file image_test.cc.
References e, and image.
BOOST_AUTO_TEST_CASE() [7/23]
BOOST_AUTO_TEST_CASE (TestNumCorrespondences)
Definition at line 128 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [8/23]
BOOST_AUTO_TEST_CASE (TestNumObservations)
Definition at line 121 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [9/23]
BOOST_AUTO_TEST_CASE (TestNumPoints2D)
Definition at line 103 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [10/23]
BOOST_AUTO_TEST_CASE (TestNumPoints3D)
Definition at line 110 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [11/23]
BOOST_AUTO_TEST_CASE (TestNumVisiblePoints3D)
Definition at line 135 of file image_test.cc.
References image, colmap::Camera::SetHeight(), and colmap::Camera::SetWidth().
BOOST_AUTO_TEST_CASE() [12/23]
BOOST_AUTO_TEST_CASE (TestPoint3D)
Definition at line 293 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [13/23]
BOOST_AUTO_TEST_CASE (TestPoint3DVisibilityScore)
Definition at line 157 of file image_test.cc.
References image, colmap::Camera::SetHeight(), and colmap::Camera::SetWidth().
BOOST_AUTO_TEST_CASE() [14/23]
BOOST_AUTO_TEST_CASE (TestPoints2D)
Definition at line 282 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [15/23]
BOOST_AUTO_TEST_CASE (TestProjectionCenter)
Definition at line 361 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [16/23]
BOOST_AUTO_TEST_CASE (TestProjectionMatrix)
Definition at line 345 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [17/23]
BOOST_AUTO_TEST_CASE (TestQvec)
Definition at line 209 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [18/23]
BOOST_AUTO_TEST_CASE (TestQvecPrior)
Definition at line 223 of file image_test.cc.
References image, and colmap::IsNaN().
BOOST_AUTO_TEST_CASE() [19/23]
BOOST_AUTO_TEST_CASE (TestRegistered)
Definition at line 94 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [20/23]
BOOST_AUTO_TEST_CASE (TestRotationMatrix)
Definition at line 356 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [21/23]
BOOST_AUTO_TEST_CASE (TestTvec)
Definition at line 248 of file image_test.cc.
References image.
BOOST_AUTO_TEST_CASE() [22/23]
BOOST_AUTO_TEST_CASE (TestTvecPrior)
Definition at line 261 of file image_test.cc.
References image, and colmap::IsNaN().
BOOST_AUTO_TEST_CASE() [23/23]
BOOST_AUTO_TEST_CASE (TestViewingDirection)
Definition at line 366 of file image_test.cc.
References image.