ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/initpart.c File Reference
initpart.c File Reference
#include "metis.h"
Functions
void Init2WayPartition (CtrlType *ctrl, GraphType *graph, int *tpwgts, float ubfactor)
void InitSeparator (CtrlType *ctrl, GraphType *graph, float ubfactor)
void GrowBisection (CtrlType *ctrl, GraphType *graph, int *tpwgts, float ubfactor)
void GrowBisectionNode (CtrlType *ctrl, GraphType *graph, float ubfactor)
void RandomBisection (CtrlType *ctrl, GraphType *graph, int *tpwgts, float ubfactor)
Function Documentation
GrowBisection()
void GrowBisection (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 82 of file initpart.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, Allocate2WayPartitionMemory, ASSERTP, Balance2Way, controldef::CoarsenTo, Compute2WayPartitionParams, FM_2WayEdgeRefine, GKfree, idxcopy, idxmalloc, idxset, idxsum, INC_DEC, LARGENIPARTS, LTERM, graphdef::mincut, graphdef::nvtxs, RandomInRange, SMALLNIPARTS, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by Init2WayPartition().
GrowBisectionNode()
void GrowBisectionNode (CtrlType * ctrl, GraphType * graph, float ubfactor)
Definition at line 210 of file initpart.c.
References graphdef::adjncy, graphdef::adjwgt, Balance2Way, graphdef::bndind, graphdef::bndptr, controldef::CoarsenTo, Compute2WayNodePartitionParams, Compute2WayPartitionParams, graphdef::ed, FM_2WayEdgeRefine, FM_2WayNodeRefine, GKfree, graphdef::id, idxcopy, idxmalloc, idxset, idxsum, INC_DEC, LARGENIPARTS, LTERM, graphdef::mincut, graphdef::nbnd, graphdef::nrinfo, graphdef::nvtxs, graphdef::pwgts, RandomInRange, graphdef::rdata, SMALLNIPARTS, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by InitSeparator().
Init2WayPartition()
void Init2WayPartition (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 21 of file initpart.c.
References DBG_IPART, DBG_MOVEINFO, DBG_REFINE, DBG_TIME, controldef::dbglvl, graclus_errexit(), GrowBisection(), IFSET, controldef::InitPartTmr, IPART_GGPKL, controldef::IType, graphdef::mincut, RandomBisection(), starttimer, and stoptimer.
InitSeparator()
void InitSeparator (CtrlType * ctrl, GraphType * graph, float ubfactor)
Definition at line 55 of file initpart.c.
References Compute2WayNodePartitionParams, DBG_IPART, DBG_MOVEINFO, DBG_REFINE, DBG_TIME, controldef::dbglvl, GrowBisectionNode(), IFSET, controldef::InitPartTmr, graphdef::mincut, starttimer, and stoptimer.
RandomBisection()
void RandomBisection (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 346 of file initpart.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, Allocate2WayPartitionMemory, ASSERTP, Balance2Way, controldef::CoarsenTo, Compute2WayPartitionParams, FM_2WayEdgeRefine, GKfree, idxcopy, idxmalloc, idxset, idxsum, LARGENIPARTS, LTERM, graphdef::mincut, graphdef::nvtxs, RandomPermute, SMALLNIPARTS, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by Init2WayPartition().