ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/KdTree.cpp File Reference
KdTree.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <CVKdTree.h>
#include <GenericProgressCallback.h>
#include "cccorelib.h"
Functions
void define_KdTree (py::module &cccorelib)
Function Documentation
define_KdTree()
void define_KdTree (py::module & cccorelib)
Definition at line 20 of file KdTree.cpp.
References cloudViewer::KDTree::buildFromCloud(), cloudViewer::KDTree::getAssociatedCloud(), and points.
Referenced by define_cccorelib().