ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qFacets/src/kdTreeForFacetExtraction.cpp File Reference
kdTreeForFacetExtraction.cpp File Reference
#include "kdTreeForFacetExtraction.h"
#include <GenericProgressCallback.h>
#include <ParallelSort.h>
#include <ecvPointCloud.h>
#include <QApplication>
Classes
struct Candidate
Functions
static bool DescendingLeafSizeComparison (const ccKdTree::Leaf *a, const ccKdTree::Leaf *b)
static bool CandidateDistAscendingComparison (const Candidate &a, const Candidate &b)
Function Documentation
CandidateDistAscendingComparison()
static bool CandidateDistAscendingComparison (const Candidate & a, const Candidate & b) static
Definition at line 47 of file kdTreeForFacetExtraction.cpp.
References a, and Candidate::dist.
Referenced by ccKdTreeForFacetExtraction::FuseCells().
DescendingLeafSizeComparison()
static bool DescendingLeafSizeComparison (const ccKdTree::Leaf * a, const ccKdTree::Leaf * b) static
Definition at line 26 of file kdTreeForFacetExtraction.cpp.
References a, cloudViewer::TrueKdTree::Leaf::points, and cloudViewer::ReferenceCloud::size().
Referenced by ccKdTreeForFacetExtraction::FuseCells().