ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/kwayfm.c File Reference
kwayfm.c File Reference
#include "metis.h"
Functions
void Random_KWayEdgeRefine (CtrlType *ctrl, GraphType *graph, int nparts, float *tpwgts, float ubfactor, int npasses, int ffactor)
void Greedy_KWayEdgeRefine (CtrlType *ctrl, GraphType *graph, int nparts, float *tpwgts, float ubfactor, int npasses)
void Greedy_KWayEdgeBalance (CtrlType *ctrl, GraphType *graph, int nparts, float *tpwgts, float ubfactor, int npasses)
Function Documentation
Greedy_KWayEdgeBalance()
void Greedy_KWayEdgeBalance (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses)
Definition at line 452 of file kwayfm.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, cloudViewer::utility::floor(), rinfodef::id, idxamax, idxamin, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, graphdef::pwgts, RandomPermute, graphdef::rinfo, SWAP, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
Greedy_KWayEdgeRefine()
void Greedy_KWayEdgeRefine (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses)
Definition at line 222 of file kwayfm.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, cloudViewer::utility::floor(), rinfodef::id, idxamax, idxamin, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, graphdef::pwgts, RandomPermute, graphdef::rinfo, SWAP, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
Random_KWayEdgeRefine()
void Random_KWayEdgeRefine (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses, int ffactor)
Definition at line 19 of file kwayfm.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, ComputeVolume, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, cloudViewer::utility::floor(), rinfodef::id, idxamax, idxamin, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, graphdef::pwgts, RandomPermute, graphdef::rinfo, SWAP, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.