ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/kwayvolrefine.c File Reference
kwayvolrefine.c File Reference
#include "metis.h"
Functions
void RefineVolKWay (CtrlType *ctrl, GraphType *orggraph, GraphType *graph, int nparts, float *tpwgts, float ubfactor)
void AllocateVolKWayPartitionMemory (CtrlType *ctrl, GraphType *graph, int nparts)
void ComputeVolKWayPartitionParams (CtrlType *ctrl, GraphType *graph, int nparts)
void ComputeKWayVolGains (CtrlType *ctrl, GraphType *graph, int nparts)
void ProjectVolKWayPartition (CtrlType *ctrl, GraphType *graph, int nparts)
void ComputeVolKWayBoundary (CtrlType *ctrl, GraphType *graph, int nparts)
void ComputeVolKWayBalanceBoundary (CtrlType *ctrl, GraphType *graph, int nparts)
Function Documentation
AllocateVolKWayPartitionMemory()
void AllocateVolKWayPartitionMemory (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 107 of file kwayvolrefine.c.
References graphdef::bndind, graphdef::bndptr, idxmalloc, graphdef::nvtxs, graphdef::pwgts, graphdef::rdata, graphdef::vrinfo, and graphdef::where.
Referenced by ProjectVolKWayPartition().
ComputeKWayVolGains()
void ComputeKWayVolGains (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 209 of file kwayvolrefine.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, graphdef::bndind, BNDInsert, graphdef::bndptr, vrinfodef::ed, vrinfodef::edegrees, vedegreedef::gv, vrinfodef::gv, vrinfodef::id, idxset, idxwspacefree, idxwspacemalloc, MAXIDX, graphdef::minvol, graphdef::nbnd, vrinfodef::ndegrees, graphdef::nvtxs, graphdef::vrinfo, graphdef::vsize, graphdef::where, and graphdef::xadj.
Referenced by ComputeVolKWayPartitionParams(), and ProjectVolKWayPartition().
ComputeVolKWayBalanceBoundary()
void ComputeVolKWayBalanceBoundary (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 439 of file kwayvolrefine.c.
References graphdef::bndind, BNDInsert, graphdef::bndptr, vrinfodef::ed, idxset, graphdef::nbnd, graphdef::nvtxs, and graphdef::vrinfo.
Referenced by RefineVolKWay().
ComputeVolKWayBoundary()
void ComputeVolKWayBoundary (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 414 of file kwayvolrefine.c.
References graphdef::bndind, BNDInsert, graphdef::bndptr, vrinfodef::ed, vrinfodef::gv, vrinfodef::id, idxset, graphdef::nbnd, graphdef::nvtxs, and graphdef::vrinfo.
Referenced by RefineVolKWay().
ComputeVolKWayPartitionParams()
void ComputeVolKWayPartitionParams (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 129 of file kwayvolrefine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, workspacedef::cdegree, ComputeKWayVolGains(), vedegreedef::ed, vrinfodef::ed, vrinfodef::edegrees, vedegreedef::gv, vrinfodef::id, idxset, graphdef::mincut, vrinfodef::ndegrees, vedegreedef::ned, vrinfodef::nid, NULL, graphdef::nvtxs, vedegreedef::pid, graphdef::pwgts, workspacedef::vedegrees, graphdef::vrinfo, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by RefineVolKWay().
ProjectVolKWayPartition()
void ProjectVolKWayPartition (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 309 of file kwayvolrefine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, AllocateVolKWayPartitionMemory(), workspacedef::cdegree, graphdef::cmap, graphdef::coarser, ComputeKWayVolGains(), vedegreedef::ed, vrinfodef::ed, vrinfodef::edegrees, FreeGraph, vedegreedef::gv, vrinfodef::id, idxcopy, idxset, idxwspacefree, idxwspacemalloc, graphdef::mincut, vrinfodef::ndegrees, vedegreedef::ned, vrinfodef::nid, NULL, graphdef::nvtxs, vedegreedef::pid, graphdef::pwgts, workspacedef::vedegrees, graphdef::vrinfo, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by RefineVolKWay().
RefineVolKWay()
void RefineVolKWay (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, int nparts, float * tpwgts, float ubfactor)
Definition at line 20 of file kwayvolrefine.c.
References ComputeVolKWayBalanceBoundary(), ComputeVolKWayBoundary(), ComputeVolKWayPartitionParams(), DBG_TIME, controldef::dbglvl, EliminateVolComponents(), EliminateVolSubDomainEdges, graphdef::finer, graphdef::gdata, GKfree, Greedy_KWayVolBalance, Greedy_KWayVolBalanceMConn, IFSET, IsBalanced, LTERM, MALLOC_CHECK, NULL, controldef::ProjectTmr, ProjectVolKWayPartition(), graphdef::pwgts, Random_KWayVolRefine, Random_KWayVolRefineMConn, controldef::RefTmr, controldef::RType, RTYPE_KWAYRANDOM, RTYPE_KWAYRANDOM_MCONN, starttimer, stoptimer, and controldef::UncoarsenTmr.