ACloudViewer: /root/ACloudViewer/plugins/core/IO/qLASFWFIO/src/LASFWFFilter.cpp File Reference
LASFWFFilter.cpp File Reference
#include "LASFWFFilter.h"
#include <CVLog.h>
#include <CVTools.h>
#include <ecvColorScalesManager.h>
#include <ecvHObjectCaster.h>
#include <ecvPointCloud.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <ecvWaveform.h>
#include <LASFields.h>
#include <QCoreApplication>
#include <QFile>
#include <QFileInfo>
#include <QString>
#include <laspoint.hpp>
#include <lasreader_las.hpp>
#include <laswriter_las.hpp>
#include <ui_saveLASFileDlg.h>
#include <assert.h>
#include <string.h>
Classes
struct ExtraLasField
Custom ("Extra bytes") field (EVLR)
class LASSaveDlg
LAS Save dialog.
Functions
static QByteArray ToQByteArray (const LASvlr &vlr)
static bool FromQByteArray (const QByteArray &buffer, LASvlr &vlr)
bool PrepareLASField (ccScalarField *&sf, LasField *lasField, unsigned totalCount, unsigned currentCount, ScalarType defaultValue=0)
Variables
static const char ProjectionVLR [] = "LASF_Projection"
Projection VLR.
static const uint16_t VLR_HEADER_SIZE
VLR buffer header size (in bytes)
Function Documentation
FromQByteArray()
static bool FromQByteArray (const QByteArray & buffer, LASvlr & vlr) static
Definition at line 110 of file LASFWFFilter.cpp.
References VLR_HEADER_SIZE, and CVLog::Warning().
Referenced by LASFWFFilter::saveToFile().
PrepareLASField()
bool PrepareLASField (ccScalarField *& sf, LasField * lasField, unsigned totalCount, unsigned currentCount, ScalarType defaultValue = 0)
Definition at line 807 of file LASFWFFilter.cpp.
References cloudViewer::ScalarField::addElement(), cloudViewer::ScalarField::getName(), LAS_EXTRA, LAS_FIELD_NAMES, CCShareable::link(), CCShareable::release(), cloudViewer::ScalarField::reserveSafe(), LasField::type, and CVLog::Warning().
Referenced by LASFWFFilter::loadFile().
ToQByteArray()
static QByteArray ToQByteArray (const LASvlr & vlr) static
Definition at line 80 of file LASFWFFilter.cpp.
References VLR_HEADER_SIZE.
Referenced by LASFWFFilter::loadFile().
Variable Documentation
ProjectionVLR
const char ProjectionVLR[] = "LASF_Projection" static
Projection VLR.
Definition at line 74 of file LASFWFFilter.cpp.
Referenced by LASFWFFilter::loadFile(), and LASFWFFilter::saveToFile().
VLR_HEADER_SIZE
const uint16_t VLR_HEADER_SIZE static
Initial value:
=
        static_cast<uint16_t>(2 + 16 + 2 + 2 + 32)
VLR buffer header size (in bytes)
Definition at line 77 of file LASFWFFilter.cpp.
Referenced by FromQByteArray(), and ToQByteArray().