ACloudViewer: /root/ACloudViewer/plugins/core/IO/qPDALIO/src/LASFilter.cpp File Reference
LASFilter.cpp File Reference
#include "LASFilter.h"
#include "LASOpenDlg.h"
#include <CVLog.h>
#include <CVMath.h>
#include <ecvHObjectCaster.h>
#include <ecvPointCloud.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include "ecvColorScalesManager.h"
#include <CVPlatform.h>
#include <QFileInfo>
#include <QFuture>
#include <QInputDialog>
#include <QSharedPointer>
#include <QtConcurrent>
#include <memory>
#include <pdal/Dimension.hpp>
#include <pdal/Filter.hpp>
#include <pdal/Options.hpp>
#include <pdal/PointTable.hpp>
#include <pdal/PointView.hpp>
#include <pdal/filters/StreamCallbackFilter.hpp>
#include <pdal/io/BufferReader.hpp>
#include <pdal/io/LasHeader.hpp>
#include <pdal/io/LasReader.hpp>
#include <pdal/io/LasVLR.hpp>
#include <pdal/io/LasWriter.hpp>
#include <ui_saveLASFileDlg.h>
#include <string.h>
#include <bitset>
Classes
struct ExtraLasField
Custom ("Extra bytes") field (EVLR)
class LASSaveDlg
LAS Save dialog.
class Tiler
Class describing the current tiling process.
struct LasCloudChunk
struct ExtraDimDescriptor
Functions
QSharedPointer< LASSaveDlg > s_saveDlg (nullptr)
Semi persistent save dialog.
pdal::Dimension::Id typeToId (LAS_FIELDS sfType, uint8_t pointFormat)
QSharedPointer< LASOpenDlg > s_lasOpenDlg (nullptr)
Variables
static const char s_LAS_SRS_Key []
Function Documentation
s_lasOpenDlg()
QSharedPointer<LASOpenDlg> s_lasOpenDlg (nullptr)
Referenced by LasCloudChunk::createFieldsToLoad(), and LASFilter::loadFile().
s_saveDlg()
QSharedPointer<LASSaveDlg> s_saveDlg (nullptr)
Semi persistent save dialog.
Referenced by LASFWFFilter::saveToFile(), and LASFilter::saveToFile().
typeToId()
pdal::Dimension::Id typeToId (LAS_FIELDS sfType, uint8_t pointFormat)
Definition at line 152 of file LASFilter.cpp.
References LasNames::Classification, LasNames::EdgeOfFlightLine, LasNames::GpsTime, LasNames::Intensity, LAS_BLUE, LAS_CLASSIF_KEYPOINT, LAS_CLASSIF_OVERLAP, LAS_CLASSIF_SYNTHETIC, LAS_CLASSIF_VALUE, LAS_CLASSIF_WITHHELD, LAS_CLASSIFICATION, LAS_EXTRA, LAS_FLIGHT_LINE_EDGE, LAS_GREEN, LAS_INTENSITY, LAS_INVALID, LAS_NUMBER_OF_RETURNS, LAS_POINT_SOURCE_ID, LAS_RED, LAS_RETURN_NUMBER, LAS_SCAN_ANGLE_RANK, LAS_SCAN_DIRECTION, LAS_TIME, LAS_USER_DATA, LAS_X, LAS_Y, LAS_Z, LasNames::NumberOfReturns, LasNames::PointSourceId, LasNames::ReturnNumber, LasNames::ScanAngleRank, LasNames::ScanDirectionFlag, LasNames::UserData, and X.
Referenced by LASFilter::loadFile(), and LASFilter::saveToFile().
Variable Documentation
s_LAS_SRS_Key
const char s_LAS_SRS_Key[] static
Initial value:
=
        "LAS.spatialReference.nosave"
Definition at line 62 of file LASFilter.cpp.
Referenced by LASFilter::loadFile(), and LASFilter::saveToFile().