ACloudViewer: /root/ACloudViewer/plugins/core/IO/qLASIO/src/LasIOFilter.cpp File Reference
LasIOFilter.cpp File Reference
#include "LasIOFilter.h"
#include "LasMetadata.h"
#include "LasOpenDialog.h"
#include "LasSaveDialog.h"
#include "LasSaver.h"
#include "LasScalarFieldLoader.h"
#include "LasScalarFieldSaver.h"
#include "LasVlr.h"
#include "LasWaveformLoader.h"
#include "LasWaveformSaver.h"
#include <GenericProgressCallback.h>
#include <ecvColorScalesManager.h>
#include <ecvPointCloud.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <QDate>
#include <QElapsedTimer>
#include <QFileInfo>
#include <laszip/laszip_api.h>
#include <memory>
#include <numeric>
#include <utility>
Functions
static CCVector3d GetGlobalShift (FileIOFilter::LoadParameters &parameters, bool &preserveCoordinateShift, const CCVector3d &lasOffset, const CCVector3d &firstPoint)
Function Documentation
GetGlobalShift()
static CCVector3d GetGlobalShift (FileIOFilter::LoadParameters & parameters, bool & preserveCoordinateShift, const CCVector3d & lasOffset, const CCVector3d & firstPoint) static
Definition at line 40 of file LasIOFilter.cpp.
References ecvGlobalShiftManager::ALWAYS_DISPLAY_DIALOG, FileIOFilter::LoadParameters::coordinatesShiftEnabled, FileIOFilter::HandleGlobalShift(), ecvGlobalShiftManager::NO_DIALOG, ecvGlobalShiftManager::NO_DIALOG_AUTO_SHIFT, Vector3Tpl< Type >::norm2(), and FileIOFilter::LoadParameters::shiftHandlingMode.
Referenced by LasIOFilter::loadFile().