ACloudViewer: /root/ACloudViewer/plugins/core/IO/qLASIO/include/LasTiler.h File Reference
LasTiler.h File Reference
#include <FileIOFilter.h>
#include <QString>
#include <laszip/laszip_api.h>
Classes
struct LasTilingOptions
Enumerations
enum class LasTilingDimensions { XY , XZ , YZ }
Functions
CC_FILE_ERROR TileLasReader (laszip_POINTER laszipReader, const QString &originName, const LasTilingOptions &options)
Enumeration Type Documentation
LasTilingDimensions
enum LasTilingDimensions strong
Enumerator
XY
XZ
YZ
Definition at line 31 of file LasTiler.h.
Function Documentation
TileLasReader()
CC_FILE_ERROR TileLasReader (laszip_POINTER laszipReader, const QString & originName, const LasTilingOptions & options)
Tiles the cloud that the reader reads into a grid described by the options.
This takes ownership of the reader and takes care of closing and deleting it
Definition at line 14 of file LasTiler.cpp.
References CC_FERR_NO_ERROR, CC_FERR_THIRD_PARTY_LIB_FAILURE, error(), LasTilingOptions::index0(), LasTilingOptions::index1(), min(), LasTilingOptions::numTiles0, LasTilingOptions::numTiles1, cloudViewer::NormalizedProgress::oneStep(), LasTilingOptions::outputDir, CVLog::Print(), seconds, ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), ecvProgressDialog::start(), and CVLog::Warning().
Referenced by LasIOFilter::loadFile().