ACloudViewer: /root/ACloudViewer/plugins/core/IO/qLASIO/src/LasWaveformLoader.cpp File Reference
LasWaveformLoader.cpp File Reference
#include "LasWaveformLoader.h"
#include "LasDetails.h"
#include <QDataStream>
Functions
static bool ParseWavepacketDescriptorVlr (const laszip_vlr_struct &vlr, WaveformDescriptor &descriptor)
static ccPointCloud::FWFDescriptorSet ParseWaveformDescriptorVlrs (const laszip_vlr_struct *vlrs, laszip_U32 numVlrs)
Function Documentation
ParseWaveformDescriptorVlrs()
static ccPointCloud::FWFDescriptorSet ParseWaveformDescriptorVlrs (const laszip_vlr_struct * vlrs, laszip_U32 numVlrs) static
Definition at line 37 of file LasWaveformLoader.cpp.
References descriptors, ParseWavepacketDescriptorVlr(), and CVLog::Warning().
Referenced by LasWaveformLoader::LasWaveformLoader().
ParseWavepacketDescriptorVlr()
static bool ParseWavepacketDescriptorVlr (const laszip_vlr_struct & vlr, WaveformDescriptor & descriptor) static
Definition at line 14 of file LasWaveformLoader.cpp.
References WaveformDescriptor::bitsPerSample, data, WaveformDescriptor::digitizerGain, WaveformDescriptor::digitizerOffset, WaveformDescriptor::numberOfSamples, and WaveformDescriptor::samplingRate_ps.
Referenced by ParseWaveformDescriptorVlrs().