ACloudViewer: /root/ACloudViewer/libs/CV_io/extern/dxflib/examples/writehatch/main.cpp File Reference
main.cpp File Reference
#include "dl_dxf.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 3 of file main.cpp.
References DL_Codes::AC1015, DL_StyleData::bold, DL_WriterA::close(), data, DL_Writer::dxfEOF(), DL_StyleData::italic, M_PI, DL_Dxf::out(), DL_Writer::sectionBlocks(), DL_Writer::sectionEnd(), DL_Writer::sectionEntities(), DL_Writer::sectionTables(), DL_Writer::tableAppid(), DL_Writer::tableEnd(), DL_Writer::tableLayers(), DL_Writer::tableLinetypes(), DL_Writer::tableStyle(), DL_Dxf::writeAppid(), DL_Dxf::writeBlock(), DL_Dxf::writeBlockRecord(), DL_Dxf::writeDimStyle(), DL_Dxf::writeEndBlock(), DL_Dxf::writeHatch1(), DL_Dxf::writeHatch2(), DL_Dxf::writeHatchEdge(), DL_Dxf::writeHatchLoop1(), DL_Dxf::writeHatchLoop2(), DL_Dxf::writeHeader(), DL_Dxf::writeLayer(), DL_Dxf::writeLinetype(), DL_Dxf::writeObjects(), DL_Dxf::writeObjectsEnd(), DL_Dxf::writeStyle(), DL_Dxf::writeUcs(), DL_Dxf::writeView(), and DL_Dxf::writeVPort().