ACloudViewer: /root/ACloudViewer/libs/CV_io/extern/dxflib/examples/readwrite/main.cpp File Reference
main.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include "dl_creationadapter.h"
#include "dl_dxf.h"
#include "test_creationclass.h"
Functions
void usage ()
void testReading (char *file)
void testWriting ()
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 49 of file main.cpp.
References testReading(), testWriting(), and usage().
testReading()
void testReading (char * file)
Definition at line 69 of file main.cpp.
References DL_Dxf::in().
Referenced by main().
testWriting()
void testWriting ()
Definition at line 82 of file main.cpp.
References DL_Codes::AC1015, DL_Codes::black, DL_WriterA::close(), DL_Writer::dxfEOF(), NULL, DL_Dxf::out(), DL_Codes::red, DL_Writer::sectionBlocks(), DL_Writer::sectionEnd(), DL_Writer::sectionEntities(), DL_Writer::sectionTables(), DL_Writer::tableAppid(), DL_Writer::tableEnd(), DL_Writer::tableLayers(), DL_Writer::tableLinetypes(), DL_Writer::tableStyle(), DL_Dxf::writeAppid(), DL_Dxf::writeBlock(), DL_Dxf::writeBlockRecord(), DL_Dxf::writeDimStyle(), DL_Dxf::writeEndBlock(), DL_Dxf::writeHeader(), DL_Dxf::writeLayer(), DL_Dxf::writeLine(), DL_Dxf::writeLinetype(), DL_Dxf::writeObjects(), DL_Dxf::writeObjectsEnd(), DL_Dxf::writePoint(), DL_Dxf::writeStyle(), DL_Dxf::writeUcs(), DL_Dxf::writeView(), and DL_Dxf::writeVPort().
Referenced by main().
usage()
void usage ()
Definition at line 67 of file main.cpp.
Referenced by main().