ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/line_test.cc File Reference
line_test.cc File Reference
#include "util/testing.h"
#include "base/line.h"
Macros
#define TEST_NAME "base/line"
Functions
BOOST_AUTO_TEST_CASE (TestDetectLineSegments)
BOOST_AUTO_TEST_CASE (TestClassifyLineSegmentOrientations)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/line"
Definition at line 32 of file line_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (TestClassifyLineSegmentOrientations)
Definition at line 60 of file line_test.cc.
References colmap::Bitmap::Allocate(), colmap::ClassifyLineSegmentOrientations(), colmap::DetectLineSegments(), colmap::HORIZONTAL, colmap::Bitmap::SetPixel(), colmap::UNDEFINED, and colmap::VERTICAL.
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (TestDetectLineSegments)
Definition at line 39 of file line_test.cc.
References colmap::Bitmap::Allocate(), colmap::DetectLineSegments(), colmap::Bitmap::SetPixel(), and size.