ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/load_plugins.cpp File Reference
load_plugins.cpp File Reference
#include <QCoreApplication>
#include <QDir>
#include <QDirIterator>
#include <QString>
#include <QtGlobal>
#include "casters.h"
#include <pybind11/numpy.h>
#include <pybind11/stl_bind.h>
Functions
QString guessPlatlibdir ()
QString getPluginsWrappersPath ()
void load_pluginWrappers (py::module_ &m)
Variables
const char * MODULE_EXTENSION = ".so"
Function Documentation
getPluginsWrappersPath()
QString getPluginsWrappersPath ()
Definition at line 71 of file load_plugins.cpp.
References guessPlatlibdir().
Referenced by load_pluginWrappers().
guessPlatlibdir()
QString guessPlatlibdir ()
Definition at line 58 of file load_plugins.cpp.
Referenced by getPluginsWrappersPath().
load_pluginWrappers()
void load_pluginWrappers (py::module_ & m)
Definition at line 93 of file load_plugins.cpp.
References e, getPluginsWrappersPath(), Utils::module(), and MODULE_EXTENSION.
Variable Documentation
MODULE_EXTENSION
const char* MODULE_EXTENSION = ".so"
Definition at line 56 of file load_plugins.cpp.
Referenced by load_pluginWrappers().