ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/optim/loransac_test.cc File Reference
loransac_test.cc File Reference
#include "util/testing.h"
#include <Eigen/Core>
#include <Eigen/Geometry>
#include "base/pose.h"
#include "base/similarity_transform.h"
#include "estimators/similarity_transform.h"
#include "optim/loransac.h"
#include "util/random.h"
Macros
#define TEST_NAME "optim/ransac"
Functions
BOOST_AUTO_TEST_CASE (TestReport)
BOOST_AUTO_TEST_CASE (TestSimilarityTransform)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "optim/ransac"
Definition at line 32 of file loransac_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (TestReport)
Definition at line 46 of file loransac_test.cc.
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (TestSimilarityTransform)
Definition at line 57 of file loransac_test.cc.
References colmap::ComposeIdentityQuaternion(), e, colmap::LORANSAC< Estimator, LocalEstimator, SupportMeasurer, Sampler >::Estimate(), colmap::SimilarityTransform3::Matrix(), colmap::RANSACOptions::max_error, colmap::RandomReal(), colmap::SetPRNGSeed(), and colmap::SimilarityTransform3::TransformPoint().