ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/FLANN/ext/lz4hc.c File Reference
lz4hc.c File Reference
#include "lz4hc.h"
#include "lz4.c"
Classes
struct LZ4HC_Data_Structure
Macros
#define LZ4_COMMONDEFS_ONLY
#define DICTIONARY_LOGSIZE 16
#define MAXD (1<<DICTIONARY_LOGSIZE)
#define MAXD_MASK (MAXD - 1)
#define HASH_LOG (DICTIONARY_LOGSIZE-1)
#define HASHTABLESIZE (1 << HASH_LOG)
#define HASH_MASK (HASHTABLESIZE - 1)
#define OPTIMAL_ML (int)((ML_MASK-1)+MINMATCH)
#define HASH_FUNCTION(i) (((i) * 2654435761U) >> ((MINMATCH*8)-HASH_LOG))
#define DELTANEXTU16(p) chainTable[(U16)(p)] /* faster */
#define LZ4HC_DEBUG 0
Enumerations
enum limitedOutput_directive { notLimited = 0 , limitedOutput = 1 , noLimit = 0 , limitedOutput = 1 }
Functions
static U32 LZ4HC_hashPtr (const void *ptr)
static void LZ4HC_init (LZ4HC_Data_Structure *hc4, const BYTE *start)
static void LZ4HC_Insert (LZ4HC_Data_Structure *hc4, const BYTE *ip)
static int LZ4HC_InsertAndFindBestMatch (LZ4HC_Data_Structure *hc4, const BYTE *ip, const BYTE *const iLimit, const BYTE **matchpos, const int maxNbAttempts)
static int LZ4HC_InsertAndGetWiderMatch (LZ4HC_Data_Structure *hc4, const BYTE *const ip, const BYTE *const iLowLimit, const BYTE *const iHighLimit, int longest, const BYTE **matchpos, const BYTE **startpos, const int maxNbAttempts)
static int LZ4HC_encodeSequence (const BYTE **ip, BYTE **op, const BYTE **anchor, int matchLength, const BYTE *const match, limitedOutput_directive limitedOutputBuffer, BYTE *oend)
static int LZ4HC_compress_generic (void *ctxvoid, const char *source, char *dest, int inputSize, int maxOutputSize, int compressionLevel, limitedOutput_directive limit)
int LZ4_sizeofStateHC (void)
int LZ4_compress_HC_extStateHC (void *state, const char *src, char *dst, int srcSize, int maxDstSize, int compressionLevel)
int LZ4_compress_HC (const char *src, char *dst, int srcSize, int maxDstSize, int compressionLevel)
LZ4_streamHC_t * LZ4_createStreamHC (void)
int LZ4_freeStreamHC (LZ4_streamHC_t *LZ4_streamHCPtr)
void LZ4_resetStreamHC (LZ4_streamHC_t *LZ4_streamHCPtr, int compressionLevel)
int LZ4_loadDictHC (LZ4_streamHC_t *LZ4_streamHCPtr, const char *dictionary, int dictSize)
static void LZ4HC_setExternalDict (LZ4HC_Data_Structure *ctxPtr, const BYTE *newBlock)
static int LZ4_compressHC_continue_generic (LZ4HC_Data_Structure *ctxPtr, const char *source, char *dest, int inputSize, int maxOutputSize, limitedOutput_directive limit)
int LZ4_compress_HC_continue (LZ4_streamHC_t *LZ4_streamHCPtr, const char *source, char *dest, int inputSize, int maxOutputSize)
int LZ4_saveDictHC (LZ4_streamHC_t *LZ4_streamHCPtr, char *safeBuffer, int dictSize)
int LZ4_compressHC (const char *src, char *dst, int srcSize)
int LZ4_compressHC_limitedOutput (const char *src, char *dst, int srcSize, int maxDstSize)
int LZ4_compressHC2 (const char *src, char *dst, int srcSize, int cLevel)
int LZ4_compressHC2_limitedOutput (const char *src, char *dst, int srcSize, int maxDstSize, int cLevel)
int LZ4_compressHC_withStateHC (void *state, const char *src, char *dst, int srcSize)
int LZ4_compressHC_limitedOutput_withStateHC (void *state, const char *src, char *dst, int srcSize, int maxDstSize)
int LZ4_compressHC2_withStateHC (void *state, const char *src, char *dst, int srcSize, int cLevel)
int LZ4_compressHC2_limitedOutput_withStateHC (void *state, const char *src, char *dst, int srcSize, int maxDstSize, int cLevel)
int LZ4_compressHC_continue (LZ4_streamHC_t *ctx, const char *src, char *dst, int srcSize)
int LZ4_compressHC_limitedOutput_continue (LZ4_streamHC_t *ctx, const char *src, char *dst, int srcSize, int maxDstSize)
int LZ4_sizeofStreamStateHC (void)
int LZ4_resetStreamStateHC (void *state, char *inputBuffer)
void * LZ4_createHC (char *inputBuffer)
int LZ4_freeHC (void *LZ4HC_Data)
int LZ4_compressHC2_continue (void *LZ4HC_Data, const char *source, char *dest, int inputSize, int compressionLevel)
int LZ4_compressHC2_limitedOutput_continue (void *LZ4HC_Data, const char *source, char *dest, int inputSize, int maxOutputSize, int compressionLevel)
char * LZ4_slideInputBufferHC (void *LZ4HC_Data)
Variables
static const int LZ4HC_compressionLevel_default = 9
static const int g_maxCompressionLevel = 16
Macro Definition Documentation
DELTANEXTU16
#define DELTANEXTU16 (p) chainTable[(U16)(p)] /* faster */
Definition at line 107 of file lz4hc.c.
DICTIONARY_LOGSIZE
#define DICTIONARY_LOGSIZE 16
Definition at line 71 of file lz4hc.c.
HASH_FUNCTION
#define HASH_FUNCTION (i) (((i) * 2654435761U) >> ((MINMATCH*8)-HASH_LOG))
Definition at line 105 of file lz4hc.c.
HASH_LOG
#define HASH_LOG (DICTIONARY_LOGSIZE-1)
Definition at line 75 of file lz4hc.c.
HASH_MASK
#define HASH_MASK (HASHTABLESIZE - 1)
Definition at line 77 of file lz4hc.c.
HASHTABLESIZE
#define HASHTABLESIZE (1 << HASH_LOG)
Definition at line 76 of file lz4hc.c.
LZ4_COMMONDEFS_ONLY
#define LZ4_COMMONDEFS_ONLY
Definition at line 64 of file lz4hc.c.
LZ4HC_DEBUG
#define LZ4HC_DEBUG 0
Definition at line 285 of file lz4hc.c.
MAXD
#define MAXD (1<<DICTIONARY_LOGSIZE)
Definition at line 72 of file lz4hc.c.
MAXD_MASK
#define MAXD_MASK (MAXD - 1)
Definition at line 73 of file lz4hc.c.
OPTIMAL_ML
#define OPTIMAL_ML (int)((ML_MASK-1)+MINMATCH)
Definition at line 79 of file lz4hc.c.
Enumeration Type Documentation
limitedOutput_directive
enum limitedOutput_directive
Enumerator
notLimited
limitedOutput
noLimit
limitedOutput
Definition at line 283 of file lz4hc.c.
Function Documentation
LZ4_compress_HC()
int LZ4_compress_HC (const char * src, char * dst, int srcSize, int maxDstSize, int compressionLevel)
Definition at line 550 of file lz4hc.c.
References LZ4_compress_HC_extStateHC().
Referenced by LZ4_compressHC(), LZ4_compressHC2(), LZ4_compressHC2_limitedOutput(), and LZ4_compressHC_limitedOutput().
LZ4_compress_HC_continue()
int LZ4_compress_HC_continue (LZ4_streamHC_t * LZ4_streamHCPtr, const char * source, char * dest, int inputSize, int maxOutputSize)
Definition at line 641 of file lz4hc.c.
References limitedOutput, LZ4_compressBound(), LZ4_compressHC_continue_generic(), and noLimit.
Referenced by LZ4_compressHC_continue(), and LZ4_compressHC_limitedOutput_continue().
LZ4_compress_HC_extStateHC()
int LZ4_compress_HC_extStateHC (void * state, const char * src, char * dst, int srcSize, int maxDstSize, int compressionLevel)
Definition at line 540 of file lz4hc.c.
References limitedOutput, LZ4_compressBound(), LZ4HC_compress_generic(), LZ4HC_init(), and noLimit.
Referenced by LZ4_compress_HC(), LZ4_compressHC2_limitedOutput_withStateHC(), LZ4_compressHC2_withStateHC(), LZ4_compressHC_limitedOutput_withStateHC(), and LZ4_compressHC_withStateHC().
LZ4_compressHC()
int LZ4_compressHC (const char * src, char * dst, int srcSize)
Definition at line 677 of file lz4hc.c.
References LZ4_compress_HC(), and LZ4_compressBound().
LZ4_compressHC2()
int LZ4_compressHC2 (const char * src, char * dst, int srcSize, int cLevel)
Definition at line 679 of file lz4hc.c.
References LZ4_compress_HC(), and LZ4_compressBound().
LZ4_compressHC2_continue()
int LZ4_compressHC2_continue (void * LZ4HC_Data, const char * source, char * dest, int inputSize, int compressionLevel)
Definition at line 716 of file lz4hc.c.
References LZ4HC_compress_generic(), and noLimit.
LZ4_compressHC2_limitedOutput()
int LZ4_compressHC2_limitedOutput (const char * src, char * dst, int srcSize, int maxDstSize, int cLevel)
Definition at line 680 of file lz4hc.c.
References LZ4_compress_HC().
LZ4_compressHC2_limitedOutput_continue()
int LZ4_compressHC2_limitedOutput_continue (void * LZ4HC_Data, const char * source, char * dest, int inputSize, int maxOutputSize, int compressionLevel)
Definition at line 721 of file lz4hc.c.
References limitedOutput, and LZ4HC_compress_generic().
LZ4_compressHC2_limitedOutput_withStateHC()
int LZ4_compressHC2_limitedOutput_withStateHC (void * state, const char * src, char * dst, int srcSize, int maxDstSize, int cLevel)
Definition at line 684 of file lz4hc.c.
References LZ4_compress_HC_extStateHC().
LZ4_compressHC2_withStateHC()
int LZ4_compressHC2_withStateHC (void * state, const char * src, char * dst, int srcSize, int cLevel)
Definition at line 683 of file lz4hc.c.
References LZ4_compress_HC_extStateHC(), and LZ4_compressBound().
LZ4_compressHC_continue()
int LZ4_compressHC_continue (LZ4_streamHC_t * ctx, const char * src, char * dst, int srcSize)
Definition at line 685 of file lz4hc.c.
References LZ4_compress_HC_continue(), and LZ4_compressBound().
LZ4_compressHC_continue_generic()
static int LZ4_compressHC_continue_generic (LZ4HC_Data_Structure * ctxPtr, const char * source, char * dest, int inputSize, int maxOutputSize, limitedOutput_directive limit) static
Definition at line 604 of file lz4hc.c.
References LZ4HC_Data_Structure::base, LZ4HC_Data_Structure::compressionLevel, LZ4HC_Data_Structure::dictBase, LZ4HC_Data_Structure::dictLimit, LZ4HC_Data_Structure::end, GB, KB, LZ4HC_Data_Structure::lowLimit, LZ4_loadDictHC(), LZ4HC_compress_generic(), LZ4HC_init(), LZ4HC_setExternalDict(), and NULL.
Referenced by LZ4_compress_HC_continue().
LZ4_compressHC_limitedOutput()
int LZ4_compressHC_limitedOutput (const char * src, char * dst, int srcSize, int maxDstSize)
Definition at line 678 of file lz4hc.c.
References LZ4_compress_HC().
LZ4_compressHC_limitedOutput_continue()
int LZ4_compressHC_limitedOutput_continue (LZ4_streamHC_t * ctx, const char * src, char * dst, int srcSize, int maxDstSize)
Definition at line 686 of file lz4hc.c.
References LZ4_compress_HC_continue().
LZ4_compressHC_limitedOutput_withStateHC()
int LZ4_compressHC_limitedOutput_withStateHC (void * state, const char * src, char * dst, int srcSize, int maxDstSize)
Definition at line 682 of file lz4hc.c.
References LZ4_compress_HC_extStateHC().
LZ4_compressHC_withStateHC()
int LZ4_compressHC_withStateHC (void * state, const char * src, char * dst, int srcSize)
Definition at line 681 of file lz4hc.c.
References LZ4_compress_HC_extStateHC(), and LZ4_compressBound().
LZ4_createHC()
void* LZ4_createHC (char * inputBuffer)
Definition at line 701 of file lz4hc.c.
References ALLOCATOR, LZ4HC_init(), and NULL.
LZ4_createStreamHC()
LZ4_streamHC_t* LZ4_createStreamHC (void)
Definition at line 562 of file lz4hc.c.
LZ4_freeHC()
int LZ4_freeHC (void * LZ4HC_Data)
Definition at line 710 of file lz4hc.c.
References FREEMEM.
LZ4_freeStreamHC()
int LZ4_freeStreamHC (LZ4_streamHC_t * LZ4_streamHCPtr)
Definition at line 563 of file lz4hc.c.
LZ4_loadDictHC()
int LZ4_loadDictHC (LZ4_streamHC_t * LZ4_streamHCPtr, const char * dictionary, int dictSize)
Definition at line 574 of file lz4hc.c.
References LZ4HC_Data_Structure::end, KB, LZ4HC_init(), and LZ4HC_Insert().
Referenced by LZ4_compressHC_continue_generic().
LZ4_resetStreamHC()
void LZ4_resetStreamHC (LZ4_streamHC_t * LZ4_streamHCPtr, int compressionLevel)
Definition at line 567 of file lz4hc.c.
References LZ4_STATIC_ASSERT, and NULL.
LZ4_resetStreamStateHC()
int LZ4_resetStreamStateHC (void * state, char * inputBuffer)
Definition at line 693 of file lz4hc.c.
References LZ4HC_init().
LZ4_saveDictHC()
int LZ4_saveDictHC (LZ4_streamHC_t * LZ4_streamHCPtr, char * safeBuffer, int dictSize)
Definition at line 652 of file lz4hc.c.
References LZ4HC_Data_Structure::base, LZ4HC_Data_Structure::dictLimit, LZ4HC_Data_Structure::end, KB, LZ4HC_Data_Structure::lowLimit, and LZ4HC_Data_Structure::nextToUpdate.
Referenced by LZ4_slideInputBufferHC().
LZ4_sizeofStateHC()
int LZ4_sizeofStateHC (void)
Definition at line 538 of file lz4hc.c.
LZ4_sizeofStreamStateHC()
int LZ4_sizeofStreamStateHC (void)
Definition at line 691 of file lz4hc.c.
References LZ4_STREAMHCSIZE.
LZ4_slideInputBufferHC()
char* LZ4_slideInputBufferHC (void * LZ4HC_Data)
Definition at line 726 of file lz4hc.c.
References LZ4HC_Data_Structure::inputBuffer, KB, and LZ4_saveDictHC().
LZ4HC_compress_generic()
static int LZ4HC_compress_generic (void * ctxvoid, const char * source, char * dest, int inputSize, int maxOutputSize, int compressionLevel, limitedOutput_directive limit) static
Definition at line 334 of file lz4hc.c.
References LZ4HC_Data_Structure::end, g_maxCompressionLevel, LASTLITERALS, LZ4HC_compressionLevel_default, LZ4HC_encodeSequence(), LZ4HC_InsertAndFindBestMatch(), LZ4HC_InsertAndGetWiderMatch(), MFLIMIT, MINMATCH, ML_BITS, ML_MASK, NULL, OPTIMAL_ML, and RUN_MASK.
Referenced by LZ4_compress_HC_extStateHC(), LZ4_compressHC2_continue(), LZ4_compressHC2_limitedOutput_continue(), and LZ4_compressHC_continue_generic().
LZ4HC_encodeSequence()
static int LZ4HC_encodeSequence (const BYTE ** ip, BYTE ** op, const BYTE ** anchor, int matchLength, const BYTE *const match, limitedOutput_directive limitedOutputBuffer, BYTE * oend) static
Definition at line 290 of file lz4hc.c.
References LASTLITERALS, length(), LZ4_wildCopy(), LZ4_writeLE16(), MINMATCH, ML_BITS, ML_MASK, and RUN_MASK.
Referenced by LZ4HC_compress_generic().
LZ4HC_hashPtr()
static U32 LZ4HC_hashPtr (const void * ptr) static
Definition at line 109 of file lz4hc.c.
References HASH_FUNCTION, and LZ4_read32().
Referenced by LZ4HC_Insert(), LZ4HC_InsertAndFindBestMatch(), and LZ4HC_InsertAndGetWiderMatch().
LZ4HC_init()
static void LZ4HC_init (LZ4HC_Data_Structure * hc4, const BYTE * start) static
Definition at line 116 of file lz4hc.c.
References LZ4HC_Data_Structure::base, LZ4HC_Data_Structure::chainTable, LZ4HC_Data_Structure::dictBase, LZ4HC_Data_Structure::dictLimit, LZ4HC_Data_Structure::end, LZ4HC_Data_Structure::hashTable, KB, LZ4HC_Data_Structure::lowLimit, MEM_INIT, and LZ4HC_Data_Structure::nextToUpdate.
Referenced by LZ4_compress_HC_extStateHC(), LZ4_compressHC_continue_generic(), LZ4_createHC(), LZ4_loadDictHC(), and LZ4_resetStreamStateHC().
LZ4HC_Insert()
static void LZ4HC_Insert (LZ4HC_Data_Structure * hc4, const BYTE * ip) static
Definition at line 130 of file lz4hc.c.
References LZ4HC_Data_Structure::base, LZ4HC_Data_Structure::chainTable, DELTANEXTU16, LZ4HC_Data_Structure::hashTable, LZ4HC_hashPtr(), MAX_DISTANCE, and LZ4HC_Data_Structure::nextToUpdate.
Referenced by LZ4_loadDictHC(), LZ4HC_InsertAndFindBestMatch(), LZ4HC_InsertAndGetWiderMatch(), and LZ4HC_setExternalDict().
LZ4HC_InsertAndFindBestMatch()
static int LZ4HC_InsertAndFindBestMatch (LZ4HC_Data_Structure * hc4, const BYTE * ip, const BYTE *const iLimit, const BYTE ** matchpos, const int maxNbAttempts) static
Definition at line 152 of file lz4hc.c.
References LZ4HC_Data_Structure::base, LZ4HC_Data_Structure::chainTable, DELTANEXTU16, LZ4HC_Data_Structure::dictBase, LZ4HC_Data_Structure::dictLimit, LZ4HC_Data_Structure::hashTable, KB, LZ4HC_Data_Structure::lowLimit, LZ4_count(), LZ4_read32(), LZ4HC_hashPtr(), LZ4HC_Insert(), and MINMATCH.
Referenced by LZ4HC_compress_generic().
LZ4HC_InsertAndGetWiderMatch()
static int LZ4HC_InsertAndGetWiderMatch (LZ4HC_Data_Structure * hc4, const BYTE *const ip, const BYTE *const iLowLimit, const BYTE *const iHighLimit, int longest, const BYTE ** matchpos, const BYTE ** startpos, const int maxNbAttempts) static
Definition at line 206 of file lz4hc.c.
References LZ4HC_Data_Structure::base, LZ4HC_Data_Structure::chainTable, DELTANEXTU16, LZ4HC_Data_Structure::dictBase, LZ4HC_Data_Structure::dictLimit, LZ4HC_Data_Structure::hashTable, KB, LZ4HC_Data_Structure::lowLimit, LZ4_count(), LZ4_read32(), LZ4HC_hashPtr(), LZ4HC_Insert(), and MINMATCH.
Referenced by LZ4HC_compress_generic().
LZ4HC_setExternalDict()
static void LZ4HC_setExternalDict (LZ4HC_Data_Structure * ctxPtr, const BYTE * newBlock) static
Definition at line 591 of file lz4hc.c.
References LZ4HC_Data_Structure::base, LZ4HC_Data_Structure::dictBase, LZ4HC_Data_Structure::dictLimit, LZ4HC_Data_Structure::end, LZ4HC_Data_Structure::lowLimit, LZ4HC_Insert(), and LZ4HC_Data_Structure::nextToUpdate.
Referenced by LZ4_compressHC_continue_generic().
Variable Documentation
g_maxCompressionLevel
const int g_maxCompressionLevel = 16 static
Definition at line 81 of file lz4hc.c.
Referenced by LZ4HC_compress_generic().
LZ4HC_compressionLevel_default
const int LZ4HC_compressionLevel_default = 9 static
Definition at line 40 of file lz4hc.c.
Referenced by LZ4HC_compress_generic().