ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/FLANN/ext/lz4hc.h File Reference
lz4hc.h File Reference
#include <stddef.h>
Classes
struct LZ4_streamHC_t
Macros
#define LZ4_STREAMHCSIZE 262192
#define LZ4_STREAMHCSIZE_SIZET (LZ4_STREAMHCSIZE / sizeof(size_t))
#define LZ4_DEPRECATE_WARNING_DEFBLOCK
#define LZ4_GCC_VERSION (__GNUC__ * 100 + __GNUC_MINOR__)
#define LZ4_DEPRECATED(message)
Functions
int LZ4_compress_HC (const char *src, char *dst, int srcSize, int maxDstSize, int compressionLevel)
int LZ4_sizeofStateHC (void)
int LZ4_compress_HC_extStateHC (void *state, const char *src, char *dst, int srcSize, int maxDstSize, int compressionLevel)
LZ4_streamHC_t * LZ4_createStreamHC (void)
int LZ4_freeStreamHC (LZ4_streamHC_t *streamHCPtr)
void LZ4_resetStreamHC (LZ4_streamHC_t *streamHCPtr, int compressionLevel)
int LZ4_loadDictHC (LZ4_streamHC_t *streamHCPtr, const char *dictionary, int dictSize)
int LZ4_compress_HC_continue (LZ4_streamHC_t *streamHCPtr, const char *src, char *dst, int srcSize, int maxDstSize)
int LZ4_saveDictHC (LZ4_streamHC_t *streamHCPtr, char *safeBuffer, int maxDictSize)
int LZ4_compressHC (const char *source, char *dest, int inputSize)
int LZ4_compressHC_limitedOutput (const char *source, char *dest, int inputSize, int maxOutputSize)
int LZ4_compressHC2 (const char *source, char *dest, int inputSize, int compressionLevel)
int LZ4_compressHC2_limitedOutput (const char *source, char *dest, int inputSize, int maxOutputSize, int compressionLevel)
int LZ4_compressHC_withStateHC (void *state, const char *source, char *dest, int inputSize)
int LZ4_compressHC_limitedOutput_withStateHC (void *state, const char *source, char *dest, int inputSize, int maxOutputSize)
int LZ4_compressHC2_withStateHC (void *state, const char *source, char *dest, int inputSize, int compressionLevel)
int LZ4_compressHC2_limitedOutput_withStateHC (void *state, const char *source, char *dest, int inputSize, int maxOutputSize, int compressionLevel)
int LZ4_compressHC_continue (LZ4_streamHC_t *LZ4_streamHCPtr, const char *source, char *dest, int inputSize)
int LZ4_compressHC_limitedOutput_continue (LZ4_streamHC_t *LZ4_streamHCPtr, const char *source, char *dest, int inputSize, int maxOutputSize)
void * LZ4_createHC (char *inputBuffer)
char * LZ4_slideInputBufferHC (void *LZ4HC_Data)
int LZ4_freeHC (void *LZ4HC_Data)
int LZ4_compressHC2_continue (void *LZ4HC_Data, const char *source, char *dest, int inputSize, int compressionLevel)
int LZ4_compressHC2_limitedOutput_continue (void *LZ4HC_Data, const char *source, char *dest, int inputSize, int maxOutputSize, int compressionLevel)
int LZ4_sizeofStreamStateHC (void)
int LZ4_resetStreamStateHC (void *state, char *inputBuffer)
Macro Definition Documentation
LZ4_DEPRECATE_WARNING_DEFBLOCK
#define LZ4_DEPRECATE_WARNING_DEFBLOCK
Definition at line 150 of file lz4hc.h.
LZ4_DEPRECATED
#define LZ4_DEPRECATED (message)
Definition at line 160 of file lz4hc.h.
LZ4_GCC_VERSION
#define LZ4_GCC_VERSION (__GNUC__ * 100 + __GNUC_MINOR__)
Definition at line 151 of file lz4hc.h.
LZ4_STREAMHCSIZE
#define LZ4_STREAMHCSIZE 262192
Definition at line 89 of file lz4hc.h.
LZ4_STREAMHCSIZE_SIZET
#define LZ4_STREAMHCSIZE_SIZET (LZ4_STREAMHCSIZE / sizeof(size_t))
Definition at line 90 of file lz4hc.h.
Function Documentation
LZ4_compress_HC()
int LZ4_compress_HC (const char * src, char * dst, int srcSize, int maxDstSize, int compressionLevel)
Definition at line 550 of file lz4hc.c.
References LZ4_compress_HC_extStateHC().
Referenced by LZ4_compressHC(), LZ4_compressHC2(), LZ4_compressHC2_limitedOutput(), and LZ4_compressHC_limitedOutput().
LZ4_compress_HC_continue()
int LZ4_compress_HC_continue (LZ4_streamHC_t * streamHCPtr, const char * src, char * dst, int srcSize, int maxDstSize)
Definition at line 641 of file lz4hc.c.
References limitedOutput, LZ4_compressBound(), LZ4_compressHC_continue_generic(), and noLimit.
Referenced by LZ4_compressHC_continue(), and LZ4_compressHC_limitedOutput_continue().
LZ4_compress_HC_extStateHC()
int LZ4_compress_HC_extStateHC (void * state, const char * src, char * dst, int srcSize, int maxDstSize, int compressionLevel)
Definition at line 540 of file lz4hc.c.
References limitedOutput, LZ4_compressBound(), LZ4HC_compress_generic(), LZ4HC_init(), and noLimit.
Referenced by LZ4_compress_HC(), LZ4_compressHC2_limitedOutput_withStateHC(), LZ4_compressHC2_withStateHC(), LZ4_compressHC_limitedOutput_withStateHC(), and LZ4_compressHC_withStateHC().
LZ4_compressHC()
int LZ4_compressHC (const char * source, char * dest, int inputSize)
Definition at line 677 of file lz4hc.c.
References LZ4_compress_HC(), and LZ4_compressBound().
LZ4_compressHC2()
int LZ4_compressHC2 (const char * source, char * dest, int inputSize, int compressionLevel)
Definition at line 679 of file lz4hc.c.
References LZ4_compress_HC(), and LZ4_compressBound().
LZ4_compressHC2_continue()
int LZ4_compressHC2_continue (void * LZ4HC_Data, const char * source, char * dest, int inputSize, int compressionLevel)
Definition at line 716 of file lz4hc.c.
References LZ4HC_compress_generic(), and noLimit.
LZ4_compressHC2_limitedOutput()
int LZ4_compressHC2_limitedOutput (const char * source, char * dest, int inputSize, int maxOutputSize, int compressionLevel)
Definition at line 680 of file lz4hc.c.
References LZ4_compress_HC().
LZ4_compressHC2_limitedOutput_continue()
int LZ4_compressHC2_limitedOutput_continue (void * LZ4HC_Data, const char * source, char * dest, int inputSize, int maxOutputSize, int compressionLevel)
Definition at line 721 of file lz4hc.c.
References limitedOutput, and LZ4HC_compress_generic().
LZ4_compressHC2_limitedOutput_withStateHC()
int LZ4_compressHC2_limitedOutput_withStateHC (void * state, const char * source, char * dest, int inputSize, int maxOutputSize, int compressionLevel)
Definition at line 684 of file lz4hc.c.
References LZ4_compress_HC_extStateHC().
LZ4_compressHC2_withStateHC()
int LZ4_compressHC2_withStateHC (void * state, const char * source, char * dest, int inputSize, int compressionLevel)
Definition at line 683 of file lz4hc.c.
References LZ4_compress_HC_extStateHC(), and LZ4_compressBound().
LZ4_compressHC_continue()
int LZ4_compressHC_continue (LZ4_streamHC_t * LZ4_streamHCPtr, const char * source, char * dest, int inputSize)
Definition at line 685 of file lz4hc.c.
References LZ4_compress_HC_continue(), and LZ4_compressBound().
LZ4_compressHC_limitedOutput()
int LZ4_compressHC_limitedOutput (const char * source, char * dest, int inputSize, int maxOutputSize)
Definition at line 678 of file lz4hc.c.
References LZ4_compress_HC().
LZ4_compressHC_limitedOutput_continue()
int LZ4_compressHC_limitedOutput_continue (LZ4_streamHC_t * LZ4_streamHCPtr, const char * source, char * dest, int inputSize, int maxOutputSize)
Definition at line 686 of file lz4hc.c.
References LZ4_compress_HC_continue().
LZ4_compressHC_limitedOutput_withStateHC()
int LZ4_compressHC_limitedOutput_withStateHC (void * state, const char * source, char * dest, int inputSize, int maxOutputSize)
Definition at line 682 of file lz4hc.c.
References LZ4_compress_HC_extStateHC().
LZ4_compressHC_withStateHC()
int LZ4_compressHC_withStateHC (void * state, const char * source, char * dest, int inputSize)
Definition at line 681 of file lz4hc.c.
References LZ4_compress_HC_extStateHC(), and LZ4_compressBound().
LZ4_createHC()
void* LZ4_createHC (char * inputBuffer)
Definition at line 701 of file lz4hc.c.
References ALLOCATOR, LZ4HC_init(), and NULL.
LZ4_createStreamHC()
LZ4_streamHC_t* LZ4_createStreamHC (void)
Definition at line 562 of file lz4hc.c.
LZ4_freeHC()
int LZ4_freeHC (void * LZ4HC_Data)
Definition at line 710 of file lz4hc.c.
References FREEMEM.
LZ4_freeStreamHC()
int LZ4_freeStreamHC (LZ4_streamHC_t * streamHCPtr)
Definition at line 563 of file lz4hc.c.
LZ4_loadDictHC()
int LZ4_loadDictHC (LZ4_streamHC_t * streamHCPtr, const char * dictionary, int dictSize)
Definition at line 574 of file lz4hc.c.
References LZ4HC_Data_Structure::end, KB, LZ4HC_init(), and LZ4HC_Insert().
Referenced by LZ4_compressHC_continue_generic().
LZ4_resetStreamHC()
void LZ4_resetStreamHC (LZ4_streamHC_t * streamHCPtr, int compressionLevel)
Definition at line 567 of file lz4hc.c.
References LZ4_STATIC_ASSERT, and NULL.
LZ4_resetStreamStateHC()
int LZ4_resetStreamStateHC (void * state, char * inputBuffer)
Definition at line 693 of file lz4hc.c.
References LZ4HC_init().
LZ4_saveDictHC()
int LZ4_saveDictHC (LZ4_streamHC_t * streamHCPtr, char * safeBuffer, int maxDictSize)
Definition at line 652 of file lz4hc.c.
References LZ4HC_Data_Structure::base, LZ4HC_Data_Structure::dictLimit, LZ4HC_Data_Structure::end, KB, LZ4HC_Data_Structure::lowLimit, and LZ4HC_Data_Structure::nextToUpdate.
Referenced by LZ4_slideInputBufferHC().
LZ4_sizeofStateHC()
int LZ4_sizeofStateHC (void)
Definition at line 538 of file lz4hc.c.
LZ4_sizeofStreamStateHC()
int LZ4_sizeofStreamStateHC (void)
Definition at line 691 of file lz4hc.c.
References LZ4_STREAMHCSIZE.
LZ4_slideInputBufferHC()
char* LZ4_slideInputBufferHC (void * LZ4HC_Data)
Definition at line 726 of file lz4hc.c.
References LZ4HC_Data_Structure::inputBuffer, KB, and LZ4_saveDictHC().