ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/plugins/m3c2/m3c2.cpp File Reference
m3c2.cpp File Reference
#include <pybind11/native_enum.h>
#include <pybind11/pybind11.h>
#include <qM3C2Dialog.h>
#include <qM3C2Process.h>
#include <ecvMainAppInterface.h>
#include <ecvPointCloud.h>
#include <stdexcept>
#include "../../src/casters.h"
Functions
ccPointCloud * ComputeWrapper (const qM3C2Dialog &dlg, bool allowDialogs)
void define_m3c2_plugin (py::module_ &m)
PYBIND11_MODULE (pym3c2, m)
Function Documentation
ComputeWrapper()
ccPointCloud* ComputeWrapper (const qM3C2Dialog & dlg, bool allowDialogs)
Definition at line 24 of file m3c2.cpp.
References qM3C2Process::Compute().
Referenced by define_m3c2_plugin().
define_m3c2_plugin()
void define_m3c2_plugin (py::module_ & m)
Definition at line 49 of file m3c2.cpp.
References ComputeWrapper(), qM3C2Dialog::getCloud1(), qM3C2Dialog::getCloud2(), qM3C2Dialog::getCorePointsCloud(), qM3C2Dialog::getExportOption(), qM3C2Dialog::getMaxThreadCount(), qM3C2Dialog::getNormalsOrientationCloud(), qM3C2Dialog::keepOriginalCloud(), qM3C2Dialog::loadParamsFromFile(), qM3C2Dialog::loadParamsFromPersistentSettings(), qM3C2Dialog::saveParamsToPersistentSettings(), and qM3C2Dialog::setCorePointsCloud().
Referenced by PYBIND11_MODULE().
PYBIND11_MODULE()
PYBIND11_MODULE (pym3c2 , m)
Definition at line 92 of file m3c2.cpp.
References define_m3c2_plugin().