ACloudViewer: /root/ACloudViewer/libs/CVViewer/tools/ManuallyAlignPointCloud/ManuallyAlignPointCloud.cpp File Reference
ManuallyAlignPointCloud.cpp File Reference
#include <pipelines/registration/ColoredICP.h>
#include <visualization/utility/SelectionPolygonVolume.h>
#include <thread>
#include "VisualizerForAlignment.h"
Functions
void PrintTransformation (const Eigen::Matrix4d &transformation)
void PrintHelp ()
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 57 of file ManuallyAlignPointCloud.cpp.
References cloudViewer::visualization::VisualizerWithEditing::AddGeometry(), cloudViewer::VisualizerForAlignment::AddSourceAndTarget(), cloudViewer::visualization::Visualizer::BuildUtilities(), cloudViewer::visualization::VisualizerWithEditing::BuildUtilities(), cloudViewer::io::CreatePointCloudFromFile(), cloudViewer::visualization::Visualizer::CreateVisualizerWindow(), cloudViewer::visualization::Visualizer::DestroyVisualizerWindow(), e, cloudViewer::utility::filesystem::FOpen(), cloudViewer::utility::filesystem::GetFileNameWithoutExtension(), cloudViewer::utility::filesystem::GetFileParentDirectory(), cloudViewer::utility::GetProgramOptionAsDouble(), cloudViewer::utility::GetProgramOptionAsInt(), cloudViewer::utility::GetProgramOptionAsString(), cloudViewer::visualization::Visualizer::GetRenderOption(), LogError, LogInfo, LogWarning, cloudViewer::AlignmentSession::max_correspondence_distance_, cloudViewer::visualization::RenderOption::point_size_, cloudViewer::visualization::Visualizer::PollEvents(), PrintHelp(), PrintTransformation(), cloudViewer::utility::ProgramOptionExists(), cloudViewer::io::ReadIJsonConvertible(), cloudViewer::pipelines::registration::RegistrationICP(), result, cloudViewer::utility::SetVerbosityLevel(), cloudViewer::AlignmentSession::transformation_, voxel_size, cloudViewer::AlignmentSession::voxel_size_, cloudViewer::io::WriteIJsonConvertible(), and cloudViewer::io::WritePointCloud().
PrintHelp()
void PrintHelp ()
Definition at line 32 of file ManuallyAlignPointCloud.cpp.
References LogInfo.
Referenced by main().
PrintTransformation()
void PrintTransformation (const Eigen::Matrix4d & transformation)
Definition at line 15 of file ManuallyAlignPointCloud.cpp.
References LogInfo.
Referenced by main().