ACloudViewer: /root/ACloudViewer/libs/CVViewer/tools/ManuallyCropGeometry.cpp File Reference
ManuallyCropGeometry.cpp File Reference
#include "CloudViewer.h"
Functions
void PrintHelp ()
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 29 of file ManuallyCropGeometry.cpp.
References cloudViewer::visualization::VisualizerWithEditing::AddGeometry(), cloudViewer::io::CreateMeshFromFile(), cloudViewer::io::CreatePointCloudFromFile(), cloudViewer::visualization::Visualizer::CreateVisualizerWindow(), cloudViewer::visualization::Visualizer::DestroyVisualizerWindow(), cloudViewer::utility::filesystem::GetFileParentDirectory(), cloudViewer::utility::GetProgramOptionAsDouble(), cloudViewer::utility::GetProgramOptionAsInt(), cloudViewer::visualization::Visualizer::GetRenderOption(), ccMesh::IsEmpty(), LogWarning, mesh_ptr, cloudViewer::visualization::RenderOption::point_size_, PrintHelp(), cloudViewer::utility::ProgramOptionExists(), cloudViewer::visualization::Visualizer::Run(), cloudViewer::utility::SetVerbosityLevel(), and voxel_size.
PrintHelp()
void PrintHelp ()
Definition at line 10 of file ManuallyCropGeometry.cpp.
References LogInfo, and cloudViewer::PrintCloudViewerVersion().
Referenced by main().