ACloudViewer: /root/ACloudViewer/plugins/core/IO/qCoreIO/src/MascaretFilter.cpp File Reference
MascaretFilter.cpp File Reference
#include "MascaretFilter.h"
#include "ui_saveMascaretFileDlg.h"
#include <CVLog.h>
#include <ecvPolyline.h>
#include <QDialog>
#include <QFile>
#include <QtCompat.h>
#include <cstring>
#include "MascaretFilter.moc"
Classes
class SaveMascaretFileDlg
Mascaret File Save dialog.
Macros
#define SAVE_AS_GEO_MASCARET
Functions
QString MakeMascaretName (QString name)
void ToLocalAbscissa (const CCVector3 &P, const CCVector3 &C, const CCVector3 &U, unsigned char upDir, CCVector2 &localP)
Macro Definition Documentation
SAVE_AS_GEO_MASCARET
#define SAVE_AS_GEO_MASCARET
Function Documentation
MakeMascaretName()
QString MakeMascaretName (QString name)
Definition at line 56 of file MascaretFilter.cpp.
References name.
Referenced by MascaretFilter::saveToFile().
ToLocalAbscissa()
void ToLocalAbscissa (const CCVector3 & P, const CCVector3 & C, const CCVector3 & U, unsigned char upDir, CCVector2 & localP) inline
Definition at line 65 of file MascaretFilter.cpp.
References dot(), Tuple3Tpl< Type >::u, Vector2Tpl< Type >::x, and Vector2Tpl< Type >::y.
Referenced by MascaretFilter::saveToFile().