ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/util/math_test.cc File Reference
math_test.cc File Reference
#include "util/testing.h"
#include "util/math.h"
Macros
#define TEST_NAME "util/math"
Functions
BOOST_AUTO_TEST_CASE (TestSignOfNumber)
BOOST_AUTO_TEST_CASE (TestIsNaN)
BOOST_AUTO_TEST_CASE (TestIsInf)
BOOST_AUTO_TEST_CASE (TestClip)
BOOST_AUTO_TEST_CASE (TestDegToRad)
BOOST_AUTO_TEST_CASE (TestRadToDeg)
BOOST_AUTO_TEST_CASE (TestMedian)
BOOST_AUTO_TEST_CASE (TestPercentile)
BOOST_AUTO_TEST_CASE (TestMean)
BOOST_AUTO_TEST_CASE (TestVariance)
BOOST_AUTO_TEST_CASE (TestStdDev)
BOOST_AUTO_TEST_CASE (TestAnyLessThan)
BOOST_AUTO_TEST_CASE (TestAnyGreaterThan)
BOOST_AUTO_TEST_CASE (TestNextCombination)
BOOST_AUTO_TEST_CASE (TestSigmoid)
BOOST_AUTO_TEST_CASE (TestScaleSigmoid)
BOOST_AUTO_TEST_CASE (TestNChooseK)
BOOST_AUTO_TEST_CASE (TestTruncateCast)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "util/math"
Definition at line 32 of file math_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/18]
BOOST_AUTO_TEST_CASE (TestAnyGreaterThan)
Definition at line 150 of file math_test.cc.
BOOST_AUTO_TEST_CASE() [2/18]
BOOST_AUTO_TEST_CASE (TestAnyLessThan)
Definition at line 141 of file math_test.cc.
BOOST_AUTO_TEST_CASE() [3/18]
BOOST_AUTO_TEST_CASE (TestClip)
Definition at line 64 of file math_test.cc.
References colmap::Clip().
BOOST_AUTO_TEST_CASE() [4/18]
BOOST_AUTO_TEST_CASE (TestDegToRad)
Definition at line 74 of file math_test.cc.
References colmap::DegToRad(), e, and M_PI.
BOOST_AUTO_TEST_CASE() [5/18]
BOOST_AUTO_TEST_CASE (TestIsInf)
Definition at line 55 of file math_test.cc.
References colmap::IsInf().
BOOST_AUTO_TEST_CASE() [6/18]
BOOST_AUTO_TEST_CASE (TestIsNaN)
Definition at line 48 of file math_test.cc.
References colmap::IsNaN().
BOOST_AUTO_TEST_CASE() [7/18]
BOOST_AUTO_TEST_CASE (TestMean)
Definition at line 114 of file math_test.cc.
BOOST_AUTO_TEST_CASE() [8/18]
BOOST_AUTO_TEST_CASE (TestMedian)
Definition at line 88 of file math_test.cc.
BOOST_AUTO_TEST_CASE() [9/18]
BOOST_AUTO_TEST_CASE (TestNChooseK)
Definition at line 199 of file math_test.cc.
References colmap::NChooseK().
BOOST_AUTO_TEST_CASE() [10/18]
BOOST_AUTO_TEST_CASE (TestNextCombination)
Definition at line 159 of file math_test.cc.
References colmap::NextCombination().
BOOST_AUTO_TEST_CASE() [11/18]
BOOST_AUTO_TEST_CASE (TestPercentile)
Definition at line 97 of file math_test.cc.
BOOST_AUTO_TEST_CASE() [12/18]
BOOST_AUTO_TEST_CASE (TestRadToDeg)
Definition at line 81 of file math_test.cc.
References e, M_PI, and colmap::RadToDeg().
BOOST_AUTO_TEST_CASE() [13/18]
BOOST_AUTO_TEST_CASE (TestScaleSigmoid)
Definition at line 193 of file math_test.cc.
References e, and colmap::ScaleSigmoid().
BOOST_AUTO_TEST_CASE() [14/18]
BOOST_AUTO_TEST_CASE (TestSigmoid)
Definition at line 187 of file math_test.cc.
References e, and colmap::Sigmoid().
BOOST_AUTO_TEST_CASE() [15/18]
BOOST_AUTO_TEST_CASE (TestSignOfNumber)
Definition at line 39 of file math_test.cc.
References colmap::SignOfNumber().
BOOST_AUTO_TEST_CASE() [16/18]
BOOST_AUTO_TEST_CASE (TestStdDev)
Definition at line 132 of file math_test.cc.
References e.
BOOST_AUTO_TEST_CASE() [17/18]
BOOST_AUTO_TEST_CASE (TestTruncateCast)
Definition at line 218 of file math_test.cc.
BOOST_AUTO_TEST_CASE() [18/18]
BOOST_AUTO_TEST_CASE (TestVariance)
Definition at line 123 of file math_test.cc.
References e.