ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/memory.c File Reference
memory.c File Reference
#include "metis.h"
Functions
void AllocateWorkSpace (CtrlType *ctrl, GraphType *graph, int nparts)
void FreeWorkSpace (CtrlType *ctrl, GraphType *graph)
int WspaceAvail (CtrlType *ctrl)
idxtype * idxwspacemalloc (CtrlType *ctrl, int n)
void idxwspacefree (CtrlType *ctrl, int n)
float * fwspacemalloc (CtrlType *ctrl, int n)
void fwspacefree (CtrlType *ctrl, int n)
GraphType * CreateGraph (void)
void InitGraph (GraphType *graph)
void FreeGraph (GraphType *graph)
Function Documentation
AllocateWorkSpace()
void AllocateWorkSpace (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 21 of file memory.c.
References workspacedef::auxcore, workspacedef::ccore, workspacedef::core, workspacedef::edegrees, GKmalloc, HTLENGTH, idxmalloc, workspacedef::maxcore, graphdef::ncon, graphdef::nedges, NEG_GAINSPAN, NULL, graphdef::nvtxs, OP_KMETIS, OP_KVMETIS, controldef::optype, PLUS_GAINSPAN, workspacedef::pmat, workspacedef::vedegrees, and controldef::wspace.
CreateGraph()
GraphType* CreateGraph (void)
Definition at line 154 of file memory.c.
References GKmalloc, and InitGraph().
FreeGraph()
void FreeGraph (GraphType * graph)
Definition at line 202 of file memory.c.
References graphdef::gdata, GKfree, LTERM, graphdef::npwgts, graphdef::nvwgt, and graphdef::rdata.
FreeWorkSpace()
void FreeWorkSpace (CtrlType * ctrl, GraphType * graph)
Definition at line 87 of file memory.c.
References workspacedef::core, workspacedef::edegrees, GKfree, LTERM, workspacedef::pmat, workspacedef::vedegrees, and controldef::wspace.
fwspacefree()
void fwspacefree (CtrlType * ctrl, int n)
Definition at line 140 of file memory.c.
References ASSERT, workspacedef::ccore, and controldef::wspace.
Referenced by MCGreedy_KWayEdgeBalanceHorizontal(), MCRandom_KWayEdgeRefineHorizontal(), MocFM_2WayEdgeRefine2(), and MocGeneral2WayBalance2().
fwspacemalloc()
float* fwspacemalloc (CtrlType * ctrl, int n)
Definition at line 128 of file memory.c.
References ASSERT, workspacedef::ccore, workspacedef::core, workspacedef::maxcore, and controldef::wspace.
idxwspacefree()
void idxwspacefree (CtrlType * ctrl, int n)
Definition at line 116 of file memory.c.
References ASSERT, workspacedef::ccore, and controldef::wspace.
idxwspacemalloc()
idxtype* idxwspacemalloc (CtrlType * ctrl, int n)
Definition at line 104 of file memory.c.
References ASSERT, workspacedef::ccore, workspacedef::core, workspacedef::maxcore, and controldef::wspace.
InitGraph()
void InitGraph (GraphType * graph)
Definition at line 170 of file memory.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::bndind, graphdef::bndptr, graphdef::cmap, graphdef::coarser, graphdef::ed, graphdef::finer, graphdef::gdata, graphdef::id, graphdef::label, graphdef::mincut, graphdef::minvol, graphdef::ncon, graphdef::nedges, graphdef::npwgts, graphdef::nrinfo, NULL, graphdef::nvtxs, graphdef::nvwgt, graphdef::pwgts, graphdef::rdata, graphdef::rinfo, graphdef::vrinfo, graphdef::vsize, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by CreateGraph().
WspaceAvail()
int WspaceAvail (CtrlType * ctrl)
Definition at line 95 of file memory.c.
References workspacedef::ccore, workspacedef::maxcore, and controldef::wspace.