ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/mesh.c File Reference
mesh.c File Reference
#include "metis.h"
Functions
void METIS_MeshToDual (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, idxtype *dxadj, idxtype *dadjncy)
void METIS_MeshToNodal (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, idxtype *dxadj, idxtype *dadjncy)
void GENDUALMETIS (int nelmnts, int nvtxs, int etype, idxtype *elmnts, idxtype *dxadj, idxtype *dadjncy)
void TRINODALMETIS (int nelmnts, int nvtxs, idxtype *elmnts, idxtype *dxadj, idxtype *dadjncy)
void TETNODALMETIS (int nelmnts, int nvtxs, idxtype *elmnts, idxtype *dxadj, idxtype *dadjncy)
void HEXNODALMETIS (int nelmnts, int nvtxs, idxtype *elmnts, idxtype *dxadj, idxtype *dadjncy)
void QUADNODALMETIS (int nelmnts, int nvtxs, idxtype *elmnts, idxtype *dxadj, idxtype *dadjncy)
Function Documentation
GENDUALMETIS()
void GENDUALMETIS (int nelmnts, int nvtxs, int etype, idxtype * elmnts, idxtype * dxadj, idxtype * dadjncy)
Definition at line 74 of file mesh.c.
References idxmalloc, idxsmalloc, and MAKECSR.
Referenced by METIS_MeshToDual().
HEXNODALMETIS()
void HEXNODALMETIS (int nelmnts, int nvtxs, idxtype * elmnts, idxtype * dxadj, idxtype * dadjncy)
Definition at line 267 of file mesh.c.
References ASSERT, idxmalloc, idxsmalloc, and MAKECSR.
Referenced by METIS_MeshToNodal().
METIS_MeshToDual()
void METIS_MeshToDual (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 23 of file mesh.c.
References ChangeMesh2CNumbering, ChangeMesh2FNumbering, and GENDUALMETIS().
Referenced by METIS_MESHTODUAL(), metis_meshtodual(), metis_meshtodual_(), metis_meshtodual__(), and METIS_PartMeshDual().
METIS_MeshToNodal()
void METIS_MeshToNodal (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 42 of file mesh.c.
References ChangeMesh2CNumbering, ChangeMesh2FNumbering, HEXNODALMETIS(), QUADNODALMETIS(), TETNODALMETIS(), and TRINODALMETIS().
Referenced by METIS_MESHTONODAL(), metis_meshtonodal(), metis_meshtonodal_(), metis_meshtonodal__(), and METIS_PartMeshNodal().
QUADNODALMETIS()
void QUADNODALMETIS (int nelmnts, int nvtxs, idxtype * elmnts, idxtype * dxadj, idxtype * dadjncy)
Definition at line 340 of file mesh.c.
References ASSERT, idxmalloc, idxsmalloc, and MAKECSR.
Referenced by METIS_MeshToNodal().
TETNODALMETIS()
void TETNODALMETIS (int nelmnts, int nvtxs, idxtype * elmnts, idxtype * dxadj, idxtype * dadjncy)
Definition at line 218 of file mesh.c.
References idxmalloc, idxsmalloc, and MAKECSR.
Referenced by METIS_MeshToNodal().
TRINODALMETIS()
void TRINODALMETIS (int nelmnts, int nvtxs, idxtype * elmnts, idxtype * dxadj, idxtype * dadjncy)
Definition at line 169 of file mesh.c.
References idxmalloc, idxsmalloc, and MAKECSR.
Referenced by METIS_MeshToNodal().