ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/meshpart.c File Reference
meshpart.c File Reference
#include "metis.h"
Functions
void METIS_PartMeshNodal (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, int *nparts, int *edgecut, idxtype *epart, idxtype *npart)
void METIS_PartMeshDual (int *ne, int *nn, idxtype *elmnts, int *etype, int *numflag, int *nparts, int *edgecut, idxtype *epart, idxtype *npart)
Function Documentation
METIS_PartMeshDual()
void METIS_PartMeshDual (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 110 of file meshpart.c.
References ChangeMesh2CNumbering, ChangeMesh2FNumbering2, GKfree, iamax, idxmalloc, idxset, idxsmalloc, LTERM, MAKECSR, METIS_MeshToDual(), METIS_PartGraphKway(), and NULL.
Referenced by METIS_PARTMESHDUAL(), metis_partmeshdual(), metis_partmeshdual_(), and metis_partmeshdual__().
METIS_PartMeshNodal()
void METIS_PartMeshNodal (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 22 of file meshpart.c.
References ChangeMesh2CNumbering, ChangeMesh2FNumbering2, GKfree, iamax, idxmalloc, idxset, idxsmalloc, LTERM, METIS_MeshToNodal(), METIS_PartGraphKway(), and NULL.
Referenced by METIS_PARTMESHNODAL(), metis_partmeshnodal(), metis_partmeshnodal_(), and metis_partmeshnodal__().