ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/mfm2.c File Reference
mfm2.c File Reference
#include "metis.h"
Functions
void MocFM_2WayEdgeRefine2 (CtrlType *ctrl, GraphType *graph, float *tpwgts, float *orgubvec, int npasses)
void SelectQueue2 (int ncon, float *npwgts, float *tpwgts, int *from, int *cnum, PQueueType queues[16][2], float *maxwgt)
int IsBetter2wayBalance (int ncon, float *newbal, float *oldbal, float *ubvec)
Function Documentation
IsBetter2wayBalance()
int IsBetter2wayBalance (int ncon, float * newbal, float * oldbal, float * ubvec)
Definition at line 326 of file mfm2.c.
Referenced by MocFM_2WayEdgeRefine2().
MocFM_2WayEdgeRefine2()
void MocFM_2WayEdgeRefine2 (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * orgubvec, int npasses)
Definition at line 20 of file mfm2.c.
References graphdef::adjncy, graphdef::adjwgt, amax, amin, AreAllBelow, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, Compute2WayHLoadImbalanceVec, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, fabs(), fwspacefree(), fwspacemalloc, graphdef::id, idxset, idxwspacefree, idxwspacemalloc, INC_DEC, IsBetter2wayBalance(), MAXNCON, graphdef::mincut, graphdef::nbnd, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, PLUS_GAINSPAN, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, RandomPermute, samax, saxpy, SelectQueue2(), SWAP, graphdef::where, and graphdef::xadj.
SelectQueue2()
void SelectQueue2 (int ncon, float * npwgts, float * tpwgts, int * from, int * cnum, PQueueType queues[16][2], float * maxwgt)
Definition at line 263 of file mfm2.c.
References max(), PQueueGetKey(), and PQueueGetSize().
Referenced by MocFM_2WayEdgeRefine2().