ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/mfm.c File Reference
mfm.c File Reference
#include "metis.h"
Functions
void MocFM_2WayEdgeRefine (CtrlType *ctrl, GraphType *graph, float *tpwgts, int npasses)
void SelectQueue (int ncon, float *npwgts, float *tpwgts, int *from, int *cnum, PQueueType queues[16][2])
int BetterBalance (int ncon, float *npwgts, float *tpwgts, float *diff)
float Compute2WayHLoadImbalance (int ncon, float *npwgts, float *tpwgts)
void Compute2WayHLoadImbalanceVec (int ncon, float *npwgts, float *tpwgts, float *lbvec)
Function Documentation
BetterBalance()
int BetterBalance (int ncon, float * npwgts, float * tpwgts, float * diff)
Definition at line 303 of file mfm.c.
References fabs(), MAXNCON, and snorm2.
Referenced by MocFM_2WayEdgeRefine().
Compute2WayHLoadImbalance()
float Compute2WayHLoadImbalance (int ncon, float * npwgts, float * tpwgts)
Definition at line 319 of file mfm.c.
References fabs(), and max().
Referenced by MocFM_2WayEdgeRefine().
Compute2WayHLoadImbalanceVec()
void Compute2WayHLoadImbalanceVec (int ncon, float * npwgts, float * tpwgts, float * lbvec)
Definition at line 337 of file mfm.c.
References fabs().
MocFM_2WayEdgeRefine()
void MocFM_2WayEdgeRefine (CtrlType * ctrl, GraphType * graph, float * tpwgts, int npasses)
Definition at line 20 of file mfm.c.
References graphdef::adjncy, graphdef::adjwgt, amax, amin, ASSERT, BetterBalance(), BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, Compute2WayHLoadImbalance(), ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, fabs(), graphdef::id, idxset, idxwspacefree, idxwspacemalloc, INC_DEC, MAXNCON, graphdef::mincut, graphdef::nbnd, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, PLUS_GAINSPAN, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, RandomPermute, samax, saxpy, SelectQueue(), SWAP, graphdef::where, and graphdef::xadj.
SelectQueue()
void SelectQueue (int ncon, float * npwgts, float * tpwgts, int * from, int * cnum, PQueueType queues[16][2])
Definition at line 238 of file mfm.c.
References max(), PQueueGetKey(), and PQueueGetSize().
Referenced by MocFM_2WayEdgeRefine().