ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/mincover.c File Reference
mincover.c File Reference
#include "metis.h"
Macros
#define INCOL 10
#define INROW 20
#define VC 1
#define SC 2
#define HC 3
#define VR 4
#define SR 5
#define HR 6
Functions
void MinCover (idxtype *xadj, idxtype *adjncy, int asize, int bsize, idxtype *cover, int *csize)
int MinCover_Augment (idxtype *xadj, idxtype *adjncy, int col, idxtype *mate, idxtype *flag, idxtype *level, int maxlevel)
void MinCover_Decompose (idxtype *xadj, idxtype *adjncy, int asize, int bsize, idxtype *mate, idxtype *cover, int *csize)
void MinCover_ColDFS (idxtype *xadj, idxtype *adjncy, int root, idxtype *mate, idxtype *where, int flag)
void MinCover_RowDFS (idxtype *xadj, idxtype *adjncy, int root, idxtype *mate, idxtype *where, int flag)
Macro Definition Documentation
HC
#define HC 3
Definition at line 23 of file mincover.c.
HR
#define HR 6
Definition at line 26 of file mincover.c.
INCOL
#define INCOL 10
Definition at line 19 of file mincover.c.
INROW
#define INROW 20
Definition at line 20 of file mincover.c.
SC
#define SC 2
Definition at line 22 of file mincover.c.
SR
#define SR 5
Definition at line 25 of file mincover.c.
VC
#define VC 1
Definition at line 21 of file mincover.c.
VR
#define VR 4
Definition at line 24 of file mincover.c.
Function Documentation
MinCover()
void MinCover (idxtype * xadj, idxtype * adjncy, int asize, int bsize, idxtype * cover, int * csize)
Definition at line 42 of file mincover.c.
References GKfree, idxmalloc, idxsmalloc, LTERM, MinCover_Augment(), and MinCover_Decompose().
MinCover_Augment()
int MinCover_Augment (idxtype * xadj, idxtype * adjncy, int col, idxtype * mate, idxtype * flag, idxtype * level, int maxlevel)
Definition at line 126 of file mincover.c.
Referenced by MinCover().
MinCover_ColDFS()
void MinCover_ColDFS (idxtype * xadj, idxtype * adjncy, int root, idxtype * mate, idxtype * where, int flag)
Definition at line 212 of file mincover.c.
References HC, HR, INCOL, and INROW.
Referenced by MinCover_Decompose().
MinCover_Decompose()
void MinCover_Decompose (idxtype * xadj, idxtype * adjncy, int asize, int bsize, idxtype * mate, idxtype * cover, int * csize)
Definition at line 163 of file mincover.c.
References abs(), HR, idxmalloc, INCOL, INROW, MinCover_ColDFS(), MinCover_RowDFS(), SC, SR, and VC.
Referenced by MinCover().
MinCover_RowDFS()
void MinCover_RowDFS (idxtype * xadj, idxtype * adjncy, int root, idxtype * mate, idxtype * where, int flag)
Definition at line 237 of file mincover.c.
References INCOL, INROW, VC, and VR.
Referenced by MinCover_Decompose().