ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/minitpart2.c File Reference
minitpart2.c File Reference
#include "metis.h"
Functions
void MocInit2WayPartition2 (CtrlType *ctrl, GraphType *graph, float *tpwgts, float *ubvec)
void MocGrowBisection2 (CtrlType *ctrl, GraphType *graph, float *tpwgts, float *ubvec)
void MocGrowBisectionNew2 (CtrlType *ctrl, GraphType *graph, float *tpwgts, float *ubvec)
void MocInit2WayBalance2 (CtrlType *ctrl, GraphType *graph, float *tpwgts, float *ubvec)
int SelectQueueOneWay2 (int ncon, float *pto, PQueueType queues[16][2], float *ubvec)
Function Documentation
MocGrowBisection2()
void MocGrowBisection2 (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 57 of file minitpart2.c.
References graphdef::adjwgt, controldef::CoarsenTo, GKfree, idxcopy, idxmalloc, idxset, idxsum, LARGENIPARTS, LTERM, graphdef::mincut, MocAllocate2WayPartitionMemory, MocBalance2Way2, MocCompute2WayPartitionParams, MocFM_2WayEdgeRefine2, graphdef::nedges, graphdef::nvtxs, RandomInRange, SMALLNIPARTS, and graphdef::where.
Referenced by MocInit2WayPartition2().
MocGrowBisectionNew2()
void MocGrowBisectionNew2 (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 108 of file minitpart2.c.
References graphdef::adjwgt, controldef::CoarsenTo, GKfree, idxcopy, idxmalloc, idxset, idxsum, LARGENIPARTS, LTERM, graphdef::mincut, MocAllocate2WayPartitionMemory, MocCompute2WayPartitionParams, MocFM_2WayEdgeRefine2, MocInit2WayBalance2(), graphdef::nedges, graphdef::nvtxs, RandomInRange, SMALLNIPARTS, and graphdef::where.
Referenced by MocInit2WayPartition2().
MocInit2WayBalance2()
void MocInit2WayBalance2 (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 156 of file minitpart2.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, ASSERTP, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, CheckGraph(), ComputeCut, ComputeLoadImbalance, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, graphdef::id, idxset, idxwspacefree, idxwspacemalloc, INC_DEC, MAXNCON, graphdef::mincut, graphdef::nbnd, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, PLUS_GAINSPAN, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueUpdate, RandomPermute, samax, saxpy, SelectQueueOneWay2(), SWAP, graphdef::where, and graphdef::xadj.
Referenced by MocGrowBisectionNew2().
MocInit2WayPartition2()
void MocInit2WayPartition2 (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 21 of file minitpart2.c.
References DBG_IPART, DBG_MOVEINFO, DBG_REFINE, DBG_TIME, controldef::dbglvl, graclus_errexit(), IFSET, controldef::InitPartTmr, IPART_GGPKL, IPART_RANDOM, controldef::IType, graphdef::mincut, MocGrowBisection2(), MocGrowBisectionNew2(), starttimer, and stoptimer.
SelectQueueOneWay2()
int SelectQueueOneWay2 (int ncon, float * pto, PQueueType queues[16][2], float * ubvec)
Definition at line 330 of file minitpart2.c.
References max(), MAXNCON, PQueueGetKey(), and PQueueGetSize().
Referenced by MocInit2WayBalance2().