ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/util/misc_test.cc File Reference
misc_test.cc File Reference
#include "util/testing.h"
#include "util/misc.h"
Macros
#define TEST_NAME "util/misc"
Functions
BOOST_AUTO_TEST_CASE (TestEnsureTrailingSlash)
BOOST_AUTO_TEST_CASE (TestHasFileExtension)
BOOST_AUTO_TEST_CASE (TestSplitFileExtension)
BOOST_AUTO_TEST_CASE (TestGetPathBaseName)
BOOST_AUTO_TEST_CASE (TestGetParentDir)
BOOST_AUTO_TEST_CASE (TestJoinPaths)
BOOST_AUTO_TEST_CASE (TestVectorContainsValue)
BOOST_AUTO_TEST_CASE (TestVectorContainsDuplicateValues)
BOOST_AUTO_TEST_CASE (TestCSVToVector)
BOOST_AUTO_TEST_CASE (TestVectorToCSV)
BOOST_AUTO_TEST_CASE (TestRemoveCommandLineArgument)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "util/misc"
Definition at line 32 of file misc_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/11]
BOOST_AUTO_TEST_CASE (TestCSVToVector)
Definition at line 160 of file misc_test.cc.
BOOST_AUTO_TEST_CASE() [2/11]
BOOST_AUTO_TEST_CASE (TestEnsureTrailingSlash)
Definition at line 39 of file misc_test.cc.
References colmap::EnsureTrailingSlash().
BOOST_AUTO_TEST_CASE() [3/11]
BOOST_AUTO_TEST_CASE (TestGetParentDir)
Definition at line 109 of file misc_test.cc.
References colmap::GetParentDir().
BOOST_AUTO_TEST_CASE() [4/11]
BOOST_AUTO_TEST_CASE (TestGetPathBaseName)
Definition at line 94 of file misc_test.cc.
References colmap::GetPathBaseName().
BOOST_AUTO_TEST_CASE() [5/11]
BOOST_AUTO_TEST_CASE (TestHasFileExtension)
Definition at line 47 of file misc_test.cc.
References colmap::HasFileExtension().
BOOST_AUTO_TEST_CASE() [6/11]
BOOST_AUTO_TEST_CASE (TestJoinPaths)
Definition at line 117 of file misc_test.cc.
References colmap::JoinPaths().
BOOST_AUTO_TEST_CASE() [7/11]
BOOST_AUTO_TEST_CASE (TestRemoveCommandLineArgument)
Definition at line 193 of file misc_test.cc.
References colmap::RemoveCommandLineArgument().
BOOST_AUTO_TEST_CASE() [8/11]
BOOST_AUTO_TEST_CASE (TestSplitFileExtension)
Definition at line 56 of file misc_test.cc.
References colmap::SplitFileExtension().
BOOST_AUTO_TEST_CASE() [9/11]
BOOST_AUTO_TEST_CASE (TestVectorContainsDuplicateValues)
Definition at line 147 of file misc_test.cc.
BOOST_AUTO_TEST_CASE() [10/11]
BOOST_AUTO_TEST_CASE (TestVectorContainsValue)
Definition at line 142 of file misc_test.cc.
BOOST_AUTO_TEST_CASE() [11/11]
BOOST_AUTO_TEST_CASE (TestVectorToCSV)
Definition at line 187 of file misc_test.cc.