ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/mkmetis.c File Reference
mkmetis.c File Reference
#include "metis.h"
Functions
void METIS_mCPartGraphKway (int *nvtxs, int *ncon, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *rubvec, int *options, int *edgecut, idxtype *part)
int MCMlevelKWayPartitioning (CtrlType *ctrl, GraphType *graph, int nparts, idxtype *part, float *rubvec)
Function Documentation
MCMlevelKWayPartitioning()
int MCMlevelKWayPartitioning (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * part, float * rubvec)
Definition at line 76 of file mkmetis.c.
References DBG_TIME, controldef::dbglvl, IFSET, controldef::InitPartTmr, IPART_RANDOM, MATCH_SBHEM_INFNORM, MCCoarsen2Way, MocAllocateKWayPartitionMemory, graphdef::ncon, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, RTYPE_FM, and starttimer.
Referenced by METIS_mCPartGraphKway().
METIS_mCPartGraphKway()
void METIS_mCPartGraphKway (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * rubvec, int * options, int * edgecut, idxtype * part)
Definition at line 23 of file mkmetis.c.
References AllocateWorkSpace, amax, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, IFSET, InitRandom, InitTimers, controldef::IType, log2_metis, McKMETIS_CTYPE, McKMETIS_DBGLVL, McKMETIS_ITYPE, McKMETIS_RTYPE, MCMlevelKWayPartitioning(), controldef::nmaxvwgt, OP_KMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, and controldef::TotalTmr.
Referenced by METIS_MCPARTGRAPHKWAY(), metis_mcpartgraphkway(), metis_mcpartgraphkway_(), and metis_mcpartgraphkway__().