ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/mkwayrefine.c File Reference
mkwayrefine.c File Reference
#include "metis.h"
Functions
void MocRefineKWayHorizontal (CtrlType *ctrl, GraphType *orggraph, GraphType *graph, int nparts, float *ubvec)
void MocAllocateKWayPartitionMemory (CtrlType *ctrl, GraphType *graph, int nparts)
void MocComputeKWayPartitionParams (CtrlType *ctrl, GraphType *graph, int nparts)
void MocProjectKWayPartition (CtrlType *ctrl, GraphType *graph, int nparts)
void MocComputeKWayBalanceBoundary (CtrlType *ctrl, GraphType *graph, int nparts)
Function Documentation
MocAllocateKWayPartitionMemory()
void MocAllocateKWayPartitionMemory (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 67 of file mkwayrefine.c.
References graphdef::bndind, graphdef::bndptr, fmalloc, idxmalloc, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::rdata, graphdef::rinfo, and graphdef::where.
Referenced by MocProjectKWayPartition().
MocComputeKWayBalanceBoundary()
void MocComputeKWayBalanceBoundary (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 278 of file mkwayrefine.c.
References graphdef::bndind, BNDInsert, graphdef::bndptr, rinfodef::ed, idxset, graphdef::nbnd, graphdef::nvtxs, and graphdef::rinfo.
Referenced by MocRefineKWayHorizontal().
MocComputeKWayPartitionParams()
void MocComputeKWayPartitionParams (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 89 of file mkwayrefine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, rinfodef::id, idxset, graphdef::mincut, graphdef::nbnd, graphdef::ncon, rinfodef::ndegrees, graphdef::npwgts, NULL, graphdef::nvtxs, graphdef::nvwgt, edegreedef::pid, graphdef::rinfo, saxpy, sset, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by MocRefineKWayHorizontal().
MocProjectKWayPartition()
void MocProjectKWayPartition (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 172 of file mkwayrefine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckBnd2, graphdef::cmap, graphdef::coarser, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, FreeGraph, rinfodef::id, idxset, idxwspacefree, idxwspacemalloc, graphdef::mincut, MocAllocateKWayPartitionMemory(), graphdef::nbnd, graphdef::ncon, rinfodef::ndegrees, graphdef::npwgts, NULL, graphdef::nvtxs, edegreedef::pid, graphdef::rinfo, scopy, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by MocRefineKWayHorizontal().
MocRefineKWayHorizontal()
void MocRefineKWayHorizontal (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, int nparts, float * ubvec)
Definition at line 20 of file mkwayrefine.c.
References ComputeKWayBoundary, DBG_TIME, controldef::dbglvl, graphdef::finer, IFSET, MCGreedy_KWayEdgeBalanceHorizontal, MCRandom_KWayEdgeRefineHorizontal, MocComputeKWayBalanceBoundary(), MocComputeKWayPartitionParams(), MocIsHBalanced, MocProjectKWayPartition(), graphdef::ncon, graphdef::npwgts, controldef::ProjectTmr, controldef::RefTmr, starttimer, stoptimer, and controldef::UncoarsenTmr.