ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/mkwayfmh.c File Reference
mkwayfmh.c File Reference
#include "metis.h"
Functions
void MCRandom_KWayEdgeRefineHorizontal (CtrlType *ctrl, GraphType *graph, int nparts, float *orgubvec, int npasses)
void MCGreedy_KWayEdgeBalanceHorizontal (CtrlType *ctrl, GraphType *graph, int nparts, float *ubvec, int npasses)
int AreAllHVwgtsBelow (int ncon, float alpha, float *vwgt1, float beta, float *vwgt2, float *limit)
int AreAllHVwgtsAbove (int ncon, float alpha, float *vwgt1, float beta, float *vwgt2, float *limit)
void ComputeHKWayLoadImbalance (int ncon, int nparts, float *npwgts, float *lbvec)
int MocIsHBalanced (int ncon, int nparts, float *npwgts, float *ubvec)
int IsHBalanceBetterFT (int ncon, int nparts, float *pfrom, float *pto, float *vwgt, float *ubvec)
int IsHBalanceBetterTT (int ncon, int nparts, float *pt1, float *pt2, float *vwgt, float *ubvec)
Function Documentation
AreAllHVwgtsAbove()
int AreAllHVwgtsAbove (int ncon, float alpha, float * vwgt1, float beta, float * vwgt2, float * limit)
Definition at line 529 of file mkwayfmh.c.
Referenced by MCGreedy_KWayEdgeBalanceHorizontal().
AreAllHVwgtsBelow()
int AreAllHVwgtsBelow (int ncon, float alpha, float * vwgt1, float beta, float * vwgt2, float * limit)
Definition at line 512 of file mkwayfmh.c.
Referenced by MCGreedy_KWayEdgeBalanceHorizontal(), and MCRandom_KWayEdgeRefineHorizontal().
ComputeHKWayLoadImbalance()
void ComputeHKWayLoadImbalance (int ncon, int nparts, float * npwgts, float * lbvec)
Definition at line 545 of file mkwayfmh.c.
References max().
Referenced by MCGreedy_KWayEdgeBalanceHorizontal(), and MCRandom_KWayEdgeRefineHorizontal().
IsHBalanceBetterFT()
int IsHBalanceBetterFT (int ncon, int nparts, float * pfrom, float * pto, float * vwgt, float * ubvec)
Definition at line 593 of file mkwayfmh.c.
References amax.
Referenced by MCGreedy_KWayEdgeBalanceHorizontal(), and MCRandom_KWayEdgeRefineHorizontal().
IsHBalanceBetterTT()
int IsHBalanceBetterTT (int ncon, int nparts, float * pt1, float * pt2, float * vwgt, float * ubvec)
Definition at line 641 of file mkwayfmh.c.
Referenced by MCGreedy_KWayEdgeBalanceHorizontal(), and MCRandom_KWayEdgeRefineHorizontal().
MCGreedy_KWayEdgeBalanceHorizontal()
void MCGreedy_KWayEdgeBalanceHorizontal (CtrlType * ctrl, GraphType * graph, int nparts, float * ubvec, int npasses)
Definition at line 257 of file mkwayfmh.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, AreAllHVwgtsAbove(), AreAllHVwgtsBelow(), ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, ComputeHKWayLoadImbalance(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, fwspacefree(), fwspacemalloc, rinfodef::id, idxamax, idxset, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, IsHBalanceBetterFT(), IsHBalanceBetterTT(), MAXNCON, graphdef::mincut, MocIsHBalanced(), graphdef::nbnd, graphdef::ncon, rinfodef::ndegrees, graphdef::npwgts, NULL, graphdef::nvtxs, graphdef::nvwgt, edegreedef::pid, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, RandomPermute, graphdef::rinfo, samax, samin, saxpy, SWAP, graphdef::where, controldef::wspace, and graphdef::xadj.
MCRandom_KWayEdgeRefineHorizontal()
void MCRandom_KWayEdgeRefineHorizontal (CtrlType * ctrl, GraphType * graph, int nparts, float * orgubvec, int npasses)
Definition at line 20 of file mkwayfmh.c.
References graphdef::adjncy, graphdef::adjwgt, amax, AreAllHVwgtsBelow(), ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, ComputeHKWayLoadImbalance(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, fabs(), fwspacefree(), fwspacemalloc, rinfodef::id, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, IsHBalanceBetterFT(), IsHBalanceBetterTT(), MAXNCON, graphdef::mincut, graphdef::nbnd, graphdef::ncon, rinfodef::ndegrees, graphdef::npwgts, NULL, graphdef::nvtxs, graphdef::nvwgt, edegreedef::pid, RandomPermute, graphdef::rinfo, samax, samin, saxpy, SWAP, graphdef::where, controldef::wspace, and graphdef::xadj.
MocIsHBalanced()
int MocIsHBalanced (int ncon, int nparts, float * npwgts, float * ubvec)
Definition at line 565 of file mkwayfmh.c.
References max().
Referenced by MCGreedy_KWayEdgeBalanceHorizontal().