ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/multilevelLib/mlkkm.c File Reference
mlkkm.c File Reference
#include "metisLib/metis.h"
Functions
void MLKKM_PartGraphKway (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *chainlength, int *options, int *edgecut, idxtype *part, int levels)
void MLKKM_WPartGraphKway (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *chainlength, float *tpwgts, int *options, int *edgecut, idxtype *part, int levels)
int MLKKMPartitioning (CtrlType *ctrl, GraphType *graph, int nparts, int chain_length, idxtype *part, float *tpwgts, float ubfactor)
Variables
int spectral_initialization
Function Documentation
MLKKM_PartGraphKway()
void MLKKM_PartGraphKway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * chainlength, int * options, int * edgecut, idxtype * part, int levels)
Definition at line 23 of file mlkkm.c.
References fmalloc, and MLKKM_WPartGraphKway().
MLKKM_WPartGraphKway()
void MLKKM_WPartGraphKway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * chainlength, float * tpwgts, int * options, int * edgecut, idxtype * part, int levels)
Definition at line 44 of file mlkkm.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, cloudViewer::utility::floor(), FreeWorkSpace, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, KMETIS_CTYPE, KMETIS_DBGLVL, KMETIS_ITYPE, KMETIS_RTYPE, controldef::maxvwgt, MLKKMPartitioning(), OP_KMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by MLKKM_PartGraphKway().
MLKKMPartitioning()
int MLKKMPartitioning (CtrlType * ctrl, GraphType * graph, int nparts, int chain_length, idxtype * part, float * tpwgts, float ubfactor)
Definition at line 179 of file mlkkm.c.
References graphdef::adjncy, graphdef::adjwgt, AllocateKWayPartitionMemory, Coarsen2Way, ComputePartitionInfo, DBG_IPART, DBG_KWAYPINFO, DBG_TIME, controldef::dbglvl, graphdef::gdata, GKfree, idxcopy, idxmalloc, IFSET, controldef::InitPartTmr, IPART_GGPKL, LTERM, MATCH_SHEMKWAY, METIS_WPartGraphRecursive(), graphdef::mincut, MLKKMRefine(), graphdef::nvtxs, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, graphdef::rdata, RTYPE_FM, spectral_initialization, starttimer, stoptimer, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by MLKKM_WPartGraphKway().
Variable Documentation
spectral_initialization
int spectral_initialization extern
Definition at line 2 of file metis.c.
Referenced by MLKKMPartitioning().