ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/mmatch.c File Reference
mmatch.c File Reference
#include "metis.h"
Functions
void MCMatch_RM (CtrlType *ctrl, GraphType *graph)
void MCMatch_HEM (CtrlType *ctrl, GraphType *graph)
void MCMatch_SHEM (CtrlType *ctrl, GraphType *graph)
void MCMatch_SHEBM (CtrlType *ctrl, GraphType *graph, int norm)
void MCMatch_SBHEM (CtrlType *ctrl, GraphType *graph, int norm)
float BetterVBalance (int ncon, int norm, float *vwgt, float *u1wgt, float *u2wgt)
int AreAllVwgtsBelowFast (int ncon, float *vwgt1, float *vwgt2, float limit)
Function Documentation
AreAllVwgtsBelowFast()
int AreAllVwgtsBelowFast (int ncon, float * vwgt1, float * vwgt2, float limit)
Definition at line 496 of file mmatch.c.
Referenced by MCMatch_HEM(), MCMatch_RM(), MCMatch_SBHEM(), MCMatch_SHEBM(), and MCMatch_SHEM().
BetterVBalance()
float BetterVBalance (int ncon, int norm, float * vwgt, float * u1wgt, float * u2wgt)
Definition at line 435 of file mmatch.c.
References fabs(), and graclus_errexit().
Referenced by MCMatch_SBHEM(), and MCMatch_SHEBM().
MCMatch_HEM()
void MCMatch_HEM (CtrlType * ctrl, GraphType * graph)
Definition at line 79 of file mmatch.c.
References graphdef::adjncy, graphdef::adjwgt, AreAllVwgtsBelowFast(), graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, graphdef::ncon, controldef::nmaxvwgt, graphdef::nvtxs, graphdef::nvwgt, RandomPermute, starttimer, stoptimer, UNMATCHED, and graphdef::xadj.
MCMatch_RM()
void MCMatch_RM (CtrlType * ctrl, GraphType * graph)
Definition at line 22 of file mmatch.c.
References graphdef::adjncy, graphdef::adjwgt, AreAllVwgtsBelowFast(), graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, graphdef::ncon, controldef::nmaxvwgt, graphdef::nvtxs, graphdef::nvwgt, RandomPermute, starttimer, stoptimer, UNMATCHED, and graphdef::xadj.
MCMatch_SBHEM()
void MCMatch_SBHEM (CtrlType * ctrl, GraphType * graph, int norm)
Definition at line 333 of file mmatch.c.
References graphdef::adjncy, graphdef::adjwgt, AreAllVwgtsBelowFast(), BetterVBalance(), BucketSortKeysInc, graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, graphdef::ncon, controldef::nmaxvwgt, graphdef::nvtxs, graphdef::nvwgt, RandomPermute, starttimer, stoptimer, UNMATCHED, and graphdef::xadj.
MCMatch_SHEBM()
void MCMatch_SHEBM (CtrlType * ctrl, GraphType * graph, int norm)
Definition at line 232 of file mmatch.c.
References graphdef::adjncy, graphdef::adjwgt, AreAllVwgtsBelowFast(), BetterVBalance(), BucketSortKeysInc, graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, graphdef::ncon, controldef::nmaxvwgt, graphdef::nvtxs, graphdef::nvwgt, RandomPermute, starttimer, stoptimer, UNMATCHED, and graphdef::xadj.
MCMatch_SHEM()
void MCMatch_SHEM (CtrlType * ctrl, GraphType * graph)
Definition at line 138 of file mmatch.c.
References graphdef::adjncy, graphdef::adjwgt, AreAllVwgtsBelowFast(), BucketSortKeysInc, graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, graphdef::ncon, controldef::nmaxvwgt, graphdef::nvtxs, graphdef::nvwgt, RandomPermute, starttimer, stoptimer, UNMATCHED, and graphdef::xadj.