ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/mmd.c File Reference
mmd.c File Reference
#include "metis.h"
Functions
void genmmd (int neqns, idxtype *xadj, idxtype *adjncy, idxtype *invp, idxtype *perm, int delta, idxtype *head, idxtype *qsize, idxtype *list, idxtype *marker, int maxint, int *ncsub)
void mmdelm (int mdeg_node, idxtype *xadj, idxtype *adjncy, idxtype *head, idxtype *forward, idxtype *backward, idxtype *qsize, idxtype *list, idxtype *marker, int maxint, int tag)
int mmdint (int neqns, idxtype *xadj, idxtype *adjncy, idxtype *head, idxtype *forward, idxtype *backward, idxtype *qsize, idxtype *list, idxtype *marker)
void mmdnum (int neqns, idxtype *perm, idxtype *invp, idxtype *qsize)
void mmdupd (int ehead, int neqns, idxtype *xadj, idxtype *adjncy, int delta, int *mdeg, idxtype *head, idxtype *forward, idxtype *backward, idxtype *qsize, idxtype *list, idxtype *marker, int maxint, int *tag)
Function Documentation
genmmd()
void genmmd (int neqns, idxtype * xadj, idxtype * adjncy, idxtype * invp, idxtype * perm, int delta, idxtype * head, idxtype * qsize, idxtype * list, idxtype * marker, int maxint, int * ncsub)
Definition at line 53 of file mmd.c.
References mmdelm(), mmdint(), mmdnum(), and mmdupd().
mmdelm()
void mmdelm (int mdeg_node, idxtype * xadj, idxtype * adjncy, idxtype * head, idxtype * forward, idxtype * backward, idxtype * qsize, idxtype * list, idxtype * marker, int maxint, int tag)
Definition at line 171 of file mmd.c.
Referenced by genmmd().
mmdint()
int mmdint (int neqns, idxtype * xadj, idxtype * adjncy, idxtype * head, idxtype * forward, idxtype * backward, idxtype * qsize, idxtype * list, idxtype * marker)
Definition at line 305 of file mmd.c.
Referenced by genmmd().
mmdnum()
void mmdnum (int neqns, idxtype * perm, idxtype * invp, idxtype * qsize)
Definition at line 348 of file mmd.c.
Referenced by genmmd().
mmdupd()
void mmdupd (int ehead, int neqns, idxtype * xadj, idxtype * adjncy, int delta, int * mdeg, idxtype * head, idxtype * forward, idxtype * backward, idxtype * qsize, idxtype * list, idxtype * marker, int maxint, int * tag)
Definition at line 412 of file mmd.c.
Referenced by genmmd().