ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/mpmetis.c File Reference
mpmetis.c File Reference
#include "metis.h"
Functions
void METIS_mCPartGraphRecursive (int *nvtxs, int *ncon, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void METIS_mCHPartGraphRecursive (int *nvtxs, int *ncon, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *ubvec, int *options, int *edgecut, idxtype *part)
int MCMlevelRecursiveBisection (CtrlType *ctrl, GraphType *graph, int nparts, idxtype *part, float ubfactor, int fpart)
int MCHMlevelRecursiveBisection (CtrlType *ctrl, GraphType *graph, int nparts, idxtype *part, float *ubvec, int fpart)
void MCMlevelEdgeBisection (CtrlType *ctrl, GraphType *graph, float *tpwgts, float ubfactor)
void MCHMlevelEdgeBisection (CtrlType *ctrl, GraphType *graph, float *tpwgts, float *ubvec)
Function Documentation
MCHMlevelEdgeBisection()
void MCHMlevelEdgeBisection (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 383 of file mpmetis.c.
References MCCoarsen2Way, MocInit2WayPartition2, and MocRefine2Way2.
Referenced by MCHMlevelRecursiveBisection().
MCHMlevelRecursiveBisection()
int MCHMlevelRecursiveBisection (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * part, float * ubvec, int fpart)
Definition at line 290 of file mpmetis.c.
References amax, fmalloc, graphdef::gdata, GKfree, graphdef::label, LTERM, MCHMlevelEdgeBisection(), MCMlevelEdgeBisection(), graphdef::mincut, graphdef::ncon, graphdef::npwgts, NULL, graphdef::nvtxs, graphdef::nvwgt, graphdef::rdata, SplitGraphPart, and graphdef::where.
Referenced by METIS_mCHPartGraphRecursive().
MCMlevelEdgeBisection()
void MCMlevelEdgeBisection (CtrlType * ctrl, GraphType * graph, float * tpwgts, float ubfactor)
Definition at line 366 of file mpmetis.c.
References MCCoarsen2Way, MocInit2WayPartition, and MocRefine2Way.
Referenced by MCHMlevelRecursiveBisection(), and MCMlevelRecursiveBisection().
MCMlevelRecursiveBisection()
int MCMlevelRecursiveBisection (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * part, float ubfactor, int fpart)
Definition at line 238 of file mpmetis.c.
References graphdef::gdata, GKfree, graphdef::label, LTERM, MCMlevelEdgeBisection(), graphdef::mincut, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, graphdef::rdata, SplitGraphPart, and graphdef::where.
Referenced by METIS_mCPartGraphRecursive().
METIS_mCHPartGraphRecursive()
void METIS_mCHPartGraphRecursive (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * ubvec, int * options, int * edgecut, idxtype * part)
Definition at line 78 of file mpmetis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, fmalloc, FreeWorkSpace, GKfree, IFSET, InitRandom, InitTimers, controldef::IType, LTERM, MCHMlevelRecursiveBisection(), controldef::nmaxvwgt, OP_PMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PMETIS_CTYPE, PMETIS_DBGLVL, PMETIS_ITYPE, PMETIS_RTYPE, PrintTimers, controldef::RType, scopy, SetUpGraph, starttimer, stoptimer, and controldef::TotalTmr.
METIS_mCPartGraphRecursive()
void METIS_mCPartGraphRecursive (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 24 of file mpmetis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, IFSET, InitRandom, InitTimers, controldef::IType, MCMlevelRecursiveBisection(), McPMETIS_CTYPE, McPMETIS_DBGLVL, McPMETIS_ITYPE, McPMETIS_RTYPE, controldef::nmaxvwgt, OP_PMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, and controldef::TotalTmr.
Referenced by METIS_MCPARTGRAPHRECURSIVE(), metis_mcpartgraphrecursive(), metis_mcpartgraphrecursive_(), and metis_mcpartgraphrecursive__().