ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/mrefine.c File Reference
mrefine.c File Reference
#include "metis.h"
Functions
void MocRefine2Way (CtrlType *ctrl, GraphType *orggraph, GraphType *graph, float *tpwgts, float ubfactor)
void MocAllocate2WayPartitionMemory (CtrlType *ctrl, GraphType *graph)
void MocCompute2WayPartitionParams (CtrlType *ctrl, GraphType *graph)
void MocProject2WayPartition (CtrlType *ctrl, GraphType *graph)
Function Documentation
MocAllocate2WayPartitionMemory()
void MocAllocate2WayPartitionMemory (CtrlType * ctrl, GraphType * graph)
Definition at line 70 of file mrefine.c.
References graphdef::bndind, graphdef::bndptr, graphdef::ed, fmalloc, graphdef::id, idxmalloc, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::rdata, and graphdef::where.
Referenced by MocProject2WayPartition().
MocCompute2WayPartitionParams()
void MocCompute2WayPartitionParams (CtrlType * ctrl, GraphType * graph)
Definition at line 91 of file mrefine.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, graphdef::bndind, graphdef::bndptr, graphdef::ed, graphdef::id, idxset, graphdef::mincut, graphdef::nbnd, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, saxpy, sset, graphdef::where, and graphdef::xadj.
Referenced by MocRefine2Way().
MocProject2WayPartition()
void MocProject2WayPartition (CtrlType * ctrl, GraphType * graph)
Definition at line 149 of file mrefine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::bndind, graphdef::bndptr, graphdef::cmap, graphdef::coarser, graphdef::ed, FreeGraph, graphdef::id, idxset, graphdef::mincut, MocAllocate2WayPartitionMemory(), graphdef::nbnd, graphdef::ncon, graphdef::npwgts, NULL, graphdef::nvtxs, scopy, graphdef::where, and graphdef::xadj.
Referenced by MocRefine2Way().
MocRefine2Way()
void MocRefine2Way (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, float * tpwgts, float ubfactor)
Definition at line 20 of file mrefine.c.
References ASSERT, CheckBnd, DBG_TIME, controldef::dbglvl, graphdef::finer, graclus_errexit(), IFSET, MAXNCON, MocBalance2Way, MocCompute2WayPartitionParams(), MocFM_2WayEdgeRefine, MocFM_2WayEdgeRefine2, MocProject2WayPartition(), graphdef::ncon, controldef::ProjectTmr, controldef::RefTmr, controldef::RType, RTYPE_FM, starttimer, stoptimer, and controldef::UncoarsenTmr.