var MultiGridOctreeData_8h =
[
    [ "TreeNodeData", "classTreeNodeData.html", "classTreeNodeData" ],
    [ "VertexData", "classVertexData.html", "classVertexData" ],
    [ "SortedTreeNodes", "classSortedTreeNodes.html", "classSortedTreeNodes" ],
    [ "_Indices", "structSortedTreeNodes_1_1__Indices.html", "structSortedTreeNodes_1_1__Indices" ],
    [ "SliceTableData", "structSortedTreeNodes_1_1SliceTableData.html", "structSortedTreeNodes_1_1SliceTableData" ],
    [ "XSliceTableData", "structSortedTreeNodes_1_1XSliceTableData.html", "structSortedTreeNodes_1_1XSliceTableData" ],
    [ "PointSupportKey", "structPointSupportKey.html", "structPointSupportKey" ],
    [ "ConstPointSupportKey", "structConstPointSupportKey.html", "structConstPointSupportKey" ],
    [ "PointData", "structPointData.html", "structPointData" ],
    [ "SparseNodeData", "structSparseNodeData.html", "structSparseNodeData" ],
    [ "DenseNodeData", "structDenseNodeData.html", "structDenseNodeData" ],
    [ "Stencil", "structStencil.html", "structStencil" ],
    [ "SystemCoefficients", "classSystemCoefficients.html", "classSystemCoefficients" ],
    [ "Octree", "classOctree.html", "classOctree" ],
    [ "ProjectiveData", "structOctree_1_1ProjectiveData.html", "structOctree_1_1ProjectiveData" ],
    [ "_Evaluator", "structOctree_1_1__Evaluator.html", "structOctree_1_1__Evaluator" ],
    [ "IsoEdge", "structOctree_1_1IsoEdge.html", "structOctree_1_1IsoEdge" ],
    [ "FaceEdges", "structOctree_1_1FaceEdges.html", "structOctree_1_1FaceEdges" ],
    [ "SliceValues", "structOctree_1_1SliceValues.html", "structOctree_1_1SliceValues" ],
    [ "XSliceValues", "structOctree_1_1XSliceValues.html", "structOctree_1_1XSliceValues" ],
    [ "SlabValues", "structOctree_1_1SlabValues.html", "structOctree_1_1SlabValues" ],
    [ "DATA_DEGREE", "MultiGridOctreeData_8h.html#a230b4ad47dba86053ddbe2c4c74bb08c", null ],
    [ "FORCE_NEUMANN_FIELD", "MultiGridOctreeData_8h.html#a9940db63f55e0b7350755340880135f9", null ],
    [ "GRADIENT_DOMAIN_SOLUTION", "MultiGridOctreeData_8h.html#af3243a04f2b5b3231e3c411ae0b69bc6", null ],
    [ "MAX_MEMORY_GB", "MultiGridOctreeData_8h.html#a01f0517ecb55fd613c5297f732c0e298", null ],
    [ "NEW_CODE", "MultiGridOctreeData_8h.html#a5d164df1ed3c709f47d6d6f7b4f99bfc", null ],
    [ "NEW_NEW_CODE", "MultiGridOctreeData_8h.html#adc26776b97527b7fd605857518ed9bac", null ],
    [ "NORMAL_DEGREE", "MultiGridOctreeData_8h.html#a2058c780ed915a202cd081d8bca538c8", null ],
    [ "WEIGHT_DEGREE", "MultiGridOctreeData_8h.html#abfcbfbc6264b59a6321fc99df235cdcc", null ],
    [ "omp_get_num_procs", "MultiGridOctreeData_8h.html#a669d6cb8c2e92e8b13df20e9c089f730", null ],
    [ "omp_get_thread_num", "MultiGridOctreeData_8h.html#afd4d1cfdcccf111a8ab472b1fef44d7f", null ],
    [ "Reset", "MultiGridOctreeData_8h.html#a8d02b2753dba105285d01f6bab62aac9", null ]
];