ACloudViewer: colmap::retrieval Namespace Reference
colmap::retrieval Namespace Reference
Classes
struct FeatureGeometryTransform
struct FeatureGeometry
struct FeatureGeometryMatch
class InvertedFile
struct InvertedFileEntry
class InvertedIndex
struct ImageScore
class HammingDistWeightFunctor
class VisualIndex
struct VoteAndVerifyOptions
Functions
int VoteAndVerify (const VoteAndVerifyOptions &options, const std::vector< FeatureGeometryMatch > &matches)
Variables
static const std::string kDefaultVocabTreeUri = ""
Function Documentation
VoteAndVerify()
int colmap::retrieval::VoteAndVerify (const VoteAndVerifyOptions & options, const std::vector< FeatureGeometryMatch > & matches)
Definition at line 208 of file vote_and_verify.cc.
References a, colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::ComputeNumTrials(), colmap::retrieval::VoteAndVerifyOptions::confidence, colmap::AffineTransformEstimator::Estimate(), colmap::AffineTransformEstimator::kMinNumSamples, M_PI, colmap::retrieval::VoteAndVerifyOptions::max_image_size, colmap::retrieval::VoteAndVerifyOptions::max_scale_error, colmap::retrieval::VoteAndVerifyOptions::max_transfer_error, colmap::retrieval::VoteAndVerifyOptions::min_num_votes, colmap::retrieval::VoteAndVerifyOptions::num_angle_bins, colmap::retrieval::VoteAndVerifyOptions::num_scale_bins, colmap::retrieval::VoteAndVerifyOptions::num_trans_bins, colmap::retrieval::VoteAndVerifyOptions::num_transformations, colmap::retrieval::FeatureGeometry::TransformFromMatch(), x, and y.
Referenced by colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::Query().
Variable Documentation
kDefaultVocabTreeUri
const std::string colmap::retrieval::kDefaultVocabTreeUri = "" static
Definition at line 25 of file resources.h.
Referenced by cloudViewer::AutomaticReconstructionWidget::Run(), colmap::RunVocabTreeBuilder(), colmap::RunVocabTreeRetriever(), and cloudViewer::AutomaticReconstructionWidget::showEvent().