ACloudViewer: cloudViewer::system Namespace Reference
cloudViewer::system Namespace Reference
Classes
struct MemoryInfo
Functions
int cpu_clock_by_os ()
Returns the CPU clock, as reported by the OS.
int get_total_cpus ()
Returns the total number of CPUs.
MemoryInfo getMemoryInfo ()
std::ostream & operator<< (std::ostream &os, const MemoryInfo &infos)
unsigned long linuxGetAvailableRam ()
Function Documentation
cpu_clock_by_os()
int cloudViewer::system::cpu_clock_by_os (void)
Returns the CPU clock, as reported by the OS.
Taken from https://github.com/anrieff/libcpuid. Duplicated to avoid the dependency for one function.
Definition at line 62 of file Cpu.cpp.
References result.
Referenced by main().
get_total_cpus()
int cloudViewer::system::get_total_cpus (void)
Returns the total number of CPUs.
Definition at line 133 of file Cpu.cpp.
Referenced by main().
getMemoryInfo()
MemoryInfo cloudViewer::system::getMemoryInfo ()
Definition at line 63 of file MemoryInfo.cpp.
References cloudViewer::system::MemoryInfo::availableRam, count, cloudViewer::system::MemoryInfo::freeRam, cloudViewer::system::MemoryInfo::freeSwap, linuxGetAvailableRam(), max(), NULL, cloudViewer::utility::swap(), cloudViewer::system::MemoryInfo::totalRam, and cloudViewer::system::MemoryInfo::totalSwap.
Referenced by GetTotalMemoryInfo(), and main().
linuxGetAvailableRam()
unsigned long cloudViewer::system::linuxGetAvailableRam ()
Definition at line 43 of file MemoryInfo.cpp.
References max().
Referenced by getMemoryInfo().
operator<<()
std::ostream & cloudViewer::system::operator<< (std::ostream & os, const MemoryInfo & infos)
Definition at line 146 of file MemoryInfo.cpp.
References cloudViewer::system::MemoryInfo::availableRam, QtCompat::endl(), cloudViewer::system::MemoryInfo::freeRam, cloudViewer::system::MemoryInfo::freeSwap, cloudViewer::system::MemoryInfo::totalRam, and cloudViewer::system::MemoryInfo::totalSwap.