ACloudViewer: VtkUtils Namespace Reference
VtkUtils Namespace Reference
Classes
class VtkMultiTextureRenderer
Multi-texture renderer - Efficient and robust multi-texture mesh rendering support.
class AbstractImageProcessor
class ImageProcessorTempl
class AbstractWidgetObserver
class ActorExporter
class AngleWidgetObserver
class BoxWidgetObserver
class ContourPrivate
class Contour
class ContourWidgetObserver
class AbstractDataFilter
class DataFilter
class ClipFilter
class CutterFilter
class SliceFilter
class DecimateProFilter
class SmoothFilter
class StreamTracerFilter
class IsosurfaceFilter
class ExtractEdgesFilter
class TubeFilter
class Delaunay2DFilter
class Glyph3DFilter
class RuledSurfaceFilter
class VertexGlyphFilter
class DistanceWidgetObserver
class DoubleSpinBoxDelegate
class ReaderTempl
class AbstractFileReader
class VtkFileReader
class StlFileReader
class ObjFileReader
class DynaFileReader
class NastranFileReader
class FluentFileReader
class AnsysFileReader
class PlyFileReader
class PdbFileReader
class ImplicitPlaneWidgetObserver
class LineWidgetObserver
class ModelToPointsConverter
class ModelToVectorsConverter
class ModelToVtkTableConverter
class MoveActorInteractorStyle
class MovePointInteractorStyle
struct Point3F
class PointsReader
class PointsToModelConverter
class PointsToPolyDataConverter
class PointWidgetObserver
class SignalBlocker
class SignalledRunnable
class SliderWidgetObserver
class SphereWidgetObserver
class SurfacePrivate
class Surface
class TableModel
struct Vector4F
class VtkPlot2DWidgetPrivate
class VtkPlot2DWidget
class VtkPlot3DWidgetPrivate
class VtkPlot3DWidget
class VtkPlotPieWidgetPrivate
class VtkPlotPieWidget
class VtkPlotWidgetPrivate
class VtkPlotWidget
class SourceSetter
class SourceSetter< vtkSphereSource >
class SourceSetter< vtkConeSource >
class VtkWidgetPrivate
class VtkWidget
Enumerations
enum FilterType {
FT_Clip , FT_Cut , FT_Slice , FT_Isosurface ,
FT_Threshold , FT_Streamline , FT_Smooth , FT_Decimate ,
FT_Count
}
Functions
QString Q_DECL_IMPORT filterName (FilterType type)
static float Getf (const char *s)
static int Geti (const char *s)
vtkStandardNewMacro (MoveActorInteractorStyle)
template<int count>
void layoutRenderers (const QList< vtkRenderer * > &renderers)
template<>
void layoutRenderers< 1 > (const QList< vtkRenderer * > &renderers)
template<>
void layoutRenderers< 2 > (const QList< vtkRenderer * > &renderers)
template<>
void layoutRenderers< 3 > (const QList< vtkRenderer * > &renderers)
template<>
void layoutRenderers< 4 > (const QList< vtkRenderer * > &renderers)
template<>
void layoutRenderers< 5 > (const QList< vtkRenderer * > &renderers)
template<>
void layoutRenderers< 6 > (const QList< vtkRenderer * > &renderers)
template<>
void layoutRenderers< 7 > (const QList< vtkRenderer * > &renderers)
template<>
void layoutRenderers< 8 > (const QList< vtkRenderer * > &renderers)
template<>
void layoutRenderers< 9 > (const QList< vtkRenderer * > &renderers)
template<>
void layoutRenderers< 10 > (const QList< vtkRenderer * > &renderers)
template<>
void layoutRenderers< 11 > (const QList< vtkRenderer * > &renderers)
template<>
void layoutRenderers< 12 > (const QList< vtkRenderer * > &renderers)
QImage vtkImageDataToQImage (vtkImageData *imageData)
void qImageToVtkImage (QImage &img, vtkImageData *imageData)
QImage vtkWidgetSnapshot (QVTKOpenGLNativeWidget *widget)
void exportActorToFile (vtkActor *actor, const QString &outfile)
template<class T >
void vtkInitOnce (T **obj)
template<class T >
void vtkInitOnce (vtkSmartPointer< T > &obj)
template<class T >
void vtkSafeDelete (T *obj)
static vtkActor * createSourceActor (vtkPolyDataAlgorithm *algo)
template<class T >
static vtkActor * createSourceActor (SourceSetter< T > *setter=nullptr)
static vtkActor * createSurfaceActor (const QList< Point3F > &points, const QList< qreal > &scalars=QList< qreal >())
template<class DataObject , class Mapper = vtkPolyDataMapper>
static vtkActor * createActorFromData (DataObject *data)
static int columnCount (int count)
int getDefaultScalarInterpolationForDataSet (vtkDataSet *data)
Enumeration Type Documentation
FilterType
enum VtkUtils::FilterType
Enumerator
FT_Clip
FT_Cut
FT_Slice
FT_Isosurface
FT_Threshold
FT_Streamline
FT_Smooth
FT_Decimate
FT_Count
Definition at line 48 of file datafilter.h.
Function Documentation
columnCount()
static int VtkUtils::columnCount (int count) static
Definition at line 72 of file vtkwidget.cpp.
References count.
createActorFromData()
template<class DataObject , class Mapper = vtkPolyDataMapper> static vtkActor* VtkUtils::createActorFromData (DataObject * data) inline static
Definition at line 135 of file vtkutils.h.
References data, and VTK_CREATE.
createSourceActor() [1/2]
template<class T > static vtkActor* VtkUtils::createSourceActor (SourceSetter< T > * setter = nullptr) inline static
Definition at line 89 of file vtkutils.h.
createSourceActor() [2/2]
static vtkActor* VtkUtils::createSourceActor (vtkPolyDataAlgorithm * algo) inline static
Definition at line 58 of file vtkutils.h.
createSurfaceActor()
static vtkActor* VtkUtils::createSurfaceActor (const QList< Point3F > & points, const QList< qreal > & scalars = QList<qreal>()) static
Definition at line 103 of file vtkutils.h.
References points, scalar, VtkUtils::Point3F::x, VtkUtils::Point3F::y, and VtkUtils::Point3F::z.
exportActorToFile()
void Q_DECL_IMPORT VtkUtils::exportActorToFile (vtkActor * actor, const QString & outfile)
Definition at line 77 of file vtkutils.cpp.
filterName()
QString Q_DECL_IMPORT VtkUtils::filterName (FilterType type)
Definition at line 12 of file datafilter.cpp.
References FT_Clip, FT_Cut, FT_Decimate, FT_Isosurface, FT_Slice, FT_Smooth, FT_Streamline, FT_Threshold, and type.
Referenced by define_qcc_io().
getDefaultScalarInterpolationForDataSet()
int VtkUtils::getDefaultScalarInterpolationForDataSet (vtkDataSet * data)
Definition at line 151 of file vtkwidget.cpp.
References data.
Referenced by VtkUtils::VtkWidget::createActorFromVTKDataSet().
Getf()
static float VtkUtils::Getf (const char * s) static
Definition at line 33 of file filereaderutils.cpp.
Referenced by VtkUtils::NastranFileReader::run().
Geti()
static int VtkUtils::Geti (const char * s) static
Definition at line 87 of file filereaderutils.cpp.
Referenced by VtkUtils::NastranFileReader::run().
layoutRenderers()
template<int count> void VtkUtils::layoutRenderers (const QList< vtkRenderer * > & renderers) inline
Definition at line 17 of file rendererslayoutalgo.h.
layoutRenderers< 1 >()
template<> void VtkUtils::layoutRenderers< 1 > (const QList< vtkRenderer * > & renderers) inline
Definition at line 20 of file rendererslayoutalgo.h.
layoutRenderers< 10 >()
template<> void VtkUtils::layoutRenderers< 10 > (const QList< vtkRenderer * > & renderers) inline
Definition at line 215 of file rendererslayoutalgo.h.
layoutRenderers< 11 >()
template<> void VtkUtils::layoutRenderers< 11 > (const QList< vtkRenderer * > & renderers) inline
Definition at line 249 of file rendererslayoutalgo.h.
layoutRenderers< 12 >()
template<> void VtkUtils::layoutRenderers< 12 > (const QList< vtkRenderer * > & renderers) inline
Definition at line 255 of file rendererslayoutalgo.h.
layoutRenderers< 2 >()
template<> void VtkUtils::layoutRenderers< 2 > (const QList< vtkRenderer * > & renderers) inline
Definition at line 30 of file rendererslayoutalgo.h.
layoutRenderers< 3 >()
template<> void VtkUtils::layoutRenderers< 3 > (const QList< vtkRenderer * > & renderers) inline
Definition at line 43 of file rendererslayoutalgo.h.
layoutRenderers< 4 >()
template<> void VtkUtils::layoutRenderers< 4 > (const QList< vtkRenderer * > & renderers) inline
Definition at line 59 of file rendererslayoutalgo.h.
layoutRenderers< 5 >()
template<> void VtkUtils::layoutRenderers< 5 > (const QList< vtkRenderer * > & renderers) inline
Definition at line 78 of file rendererslayoutalgo.h.
layoutRenderers< 6 >()
template<> void VtkUtils::layoutRenderers< 6 > (const QList< vtkRenderer * > & renderers) inline
Definition at line 100 of file rendererslayoutalgo.h.
layoutRenderers< 7 >()
template<> void VtkUtils::layoutRenderers< 7 > (const QList< vtkRenderer * > & renderers) inline
Definition at line 125 of file rendererslayoutalgo.h.
layoutRenderers< 8 >()
template<> void VtkUtils::layoutRenderers< 8 > (const QList< vtkRenderer * > & renderers) inline
Definition at line 153 of file rendererslayoutalgo.h.
layoutRenderers< 9 >()
template<> void VtkUtils::layoutRenderers< 9 > (const QList< vtkRenderer * > & renderers) inline
Definition at line 183 of file rendererslayoutalgo.h.
qImageToVtkImage()
void Q_DECL_IMPORT VtkUtils::qImageToVtkImage (QImage & img, vtkImageData * imageData)
Definition at line 58 of file vtkutils.cpp.
vtkImageDataToQImage()
QImage Q_DECL_IMPORT VtkUtils::vtkImageDataToQImage (vtkImageData * imageData)
Todo:
retrieve just the UpdateExtent
Definition at line 35 of file vtkutils.cpp.
References height, image, and width.
Referenced by vtkWidgetSnapshot().
vtkInitOnce() [1/2]
template<class T > void VtkUtils::vtkInitOnce (T ** obj)
Definition at line 44 of file vtkutils.h.
Referenced by cvSliceFilter::apply(), cvClipFilter::apply(), cvDecimateFilter::apply(), cvGlyphFilter::apply(), cvIsoSurfaceFilter::apply(), cvProbeFilter::apply(), cvSmoothFilter::apply(), cvStreamlineFilter::apply(), cvThresholdFilter::apply(), VtkUtils::VtkPlot2DWidget::chart(), VtkUtils::VtkPlot3DWidget::chart(), VtkUtils::VtkPlotPieWidget::chart(), QVTKWidgetCustom::defaultRenderer(), VtkUtils::VtkWidget::defaultRenderer(), cvSliceFilter::getOutput(), cvDistanceTool::initTool(), cvProtractorTool::initTool(), VtkUtils::MoveActorInteractorStyle::OnMouseMove(), VtkUtils::VtkFileReader::run(), VtkUtils::StlFileReader::run(), VtkUtils::ObjFileReader::run(), VtkUtils::DynaFileReader::run(), VtkUtils::FluentFileReader::run(), VtkUtils::PlyFileReader::run(), VtkUtils::PdbFileReader::run(), VtkUtils::ModelToVtkTableConverter::run(), VtkUtils::PointsToPolyDataConverter::run(), cvGenericFilter::showOutline(), PclTransformTool::start(), VtkUtils::Surface::surfaceActor(), and cvCutFilter::updateCutWidget().
vtkInitOnce() [2/2]
template<class T > void VtkUtils::vtkInitOnce (vtkSmartPointer< T > & obj)
Definition at line 49 of file vtkutils.h.
vtkSafeDelete()
template<class T > void VtkUtils::vtkSafeDelete (T * obj)
Definition at line 54 of file vtkutils.h.
Referenced by cvGenericFilter::~cvGenericFilter().
vtkStandardNewMacro()
VtkUtils::vtkStandardNewMacro (MoveActorInteractorStyle)
vtkWidgetSnapshot()
QImage Q_DECL_IMPORT VtkUtils::vtkWidgetSnapshot (QVTKOpenGLNativeWidget * widget)
Definition at line 71 of file vtkutils.cpp.
References vtkImageDataToQImage().