ACloudViewer: cloudViewer::reconstruction::vocab_tree Namespace Reference
cloudViewer::reconstruction::vocab_tree Namespace Reference
Functions
void pybind_vocab_tree_methods (py::module &m)
void pybind_vocab_tree (py::module &m)
Variables
static const std::unordered_map< std::string, std::string > map_shared_argument_docstrings
Function Documentation
pybind_vocab_tree()
void cloudViewer::reconstruction::vocab_tree::pybind_vocab_tree (py::module & m)
Definition at line 70 of file vocab_tree.cpp.
References pybind_vocab_tree_methods().
Referenced by cloudViewer::reconstruction::pybind_reconstruction().
pybind_vocab_tree_methods()
void cloudViewer::reconstruction::vocab_tree::pybind_vocab_tree_methods (py::module & m)
Definition at line 49 of file vocab_tree.cpp.
References cloudViewer::docstring::FunctionDocInject(), and map_shared_argument_docstrings.
Referenced by pybind_vocab_tree().
Variable Documentation
map_shared_argument_docstrings
const std::unordered_map<std::string, std::string> cloudViewer::reconstruction::vocab_tree::map_shared_argument_docstrings static
Initial value:
= {
                {"database_path",
                 "Path to database in which to store the extracted data"},
                {"vocab_tree_path", "The vocabulary tree path."},
                {"num_visual_words",
                 "The desired number of visual words, i.e. the number of leaf "
                 "node clusters. Note that the actual number of visual words "
                 "might be less."},
                {"num_checks",
                 "The number of checks in the nearest neighbor search."},
                {"branching",
                 "The branching factor of the hierarchical k-means tree."},
                {"num_iterations",
                 "The number of iterations for the clustering."},
                {"max_num_images", "The maximum number of images."},
                {"database_image_list_path", "The database image list path."},
                {"query_image_list_path", "The query image list path."},
                {"output_index_path", "The output index path."},
                {"max_num_images",
                 "The maximum number of most similar images to retrieve."},
                {"num_neighbors",
                 "The number of nearest neighbor visual words that each "
                 "feature descriptor is assigned to."},
                {"num_images_after_verification",
                 "Whether to perform spatial verification after image "
                 "retrieval."},
                {"max_num_features", "The maximum number of features."}}
Definition at line 21 of file vocab_tree.cpp.
Referenced by pybind_vocab_tree_methods().