ACloudViewer: cloudViewer::data Namespace Reference
cloudViewer::data Namespace Reference
Classes
class Dataset
Base CloudViewer dataset class.
struct DataDescriptor
Infomation about a file to be downloaded.
class DownloadDataset
Dataset class with one or more downloaded file.
class ArmadilloMesh
Data class for ArmadilloMesh contains the ArmadilloMesh.ply from the Stanford 3D Scanning Repository.
class AvocadoModel
Data class for AvocadoModel contains a avocado model file, along with material and PNG format embedded textures.
class BedroomRGBDImages
Data class for BedroomRGBDImages contains a sample set of 21931 color and depth images from Redwood RGBD dataset. Additionally it also contains camera trajectory log, and mesh reconstruction.
class BunnyMesh
Data class for BunnyMesh contains the BunnyMesh.ply from the Stanford 3D Scanning Repository.
class CrateModel
Data class for CrateModel contains a sword model file, along with material and various other texture files. The model file can be accessed using GetPath(), however in order to access the paths to the texture files one may use GetPath(filename) method or get the unordered map of filename to path using GetPathMap().
class DamagedHelmetModel
Data class for DamagedHelmetModel contains a damaged helmet model file, along with material and JPG format embedded textures.
class DemoColoredICPPointClouds
Data class for DemoColoredICPPointClouds contains 2 point clouds of PLY format. This data is used in CloudViewer for Colored-ICP demo.
class DemoCropPointCloud
Data class for DemoCropPointCloud contains a point cloud, and cropped.json (a saved selected polygon volume file). This data is used in CloudViewer for point cloud crop demo.
class DemoCustomVisualization
Data class for DemoCustomVisualization contains an example point-cloud, camera trajectory (json file), rendering options (json file). This data is used in CloudViewer for custom visualization with camera trajectory demo.
class DemoDopplerICPSequence
Data class for DemoDopplerICPSequence contains an example sequence of 100 point clouds with Doppler velocity channel and corresponding ground truth poses. The sequence was generated using the CARLA simulator.
class DemoFeatureMatchingPointClouds
Data class for DemoFeatureMatchingPointClouds contains 2 point cloud fragments and their respective FPFH features and L32D features. This data is used in CloudViewer for point cloud feature matching demo.
class DemoICPPointClouds
Data class for DemoICPPointClouds contains 3 point clouds of binary PCD format. This data is used in CloudViewer for ICP demo.
class DemoPoseGraphOptimization
Data class for DemoPoseGraphOptimization contains an example fragment pose graph, and global pose graph. This data is used in CloudViewer for pose graph optimization demo.
class EaglePointCloud
Data class for EaglePointCloud contains the EaglePointCloud.ply file.
class FlightHelmetModel
Data class for FlightHelmetModel contains a flight helmet model file, along with material and various other texture files. The model file can be accessed using GetPath(), however in order to access the paths to the texture files one may use GetPath(filename) method or get the unordered map of filename to path using GetPathMap().
class JackJackL515Bag
Data class for JackJackL515Bag contains the RealSense L515 JackJackL515Bag.bag file.
class JuneauImage
Data class for JuneauImage contains the JuneauImage.jpg file.
class KnotMesh
Data class for KnotMesh contains the KnotMesh.ply file.
class LivingRoomPointClouds
Dataset class for LivingRoomPointClouds contains 57 point clouds of binary PLY format.
class LoungeRGBDImages
Data class for LoungeRGBDImages contains a sample set of 3000 color and depth images from Stanford Lounge RGBD dataset. Additionally it also contains camera trajectory log, and mesh reconstruction.
class MetalTexture
Data class for MetalTexture contains albedo, normal, roughness and metallic texture files for metal based material.
class MonkeyModel
Data class for MonkeyModel contains a monkey model file, along with material and various other texture files. The model file can be accessed using GetPath(), however in order to access the paths to the texture files one may use GetPath(filename) method or get the unordered map of filename to path using GetPathMap().
class OfficePointClouds
Dataset class for OfficePointClouds contains 53 point clouds of binary PLY format.
class PCDPointCloud
Data class for PCDPointCloud contains the fragment.pcd point cloud mesh from the Redwood Living Room dataset.
class PLYPointCloud
Data class for PLYPointCloud contains the fragment.ply point cloud mesh from the Redwood Living Room dataset.
class PTSPointCloud
Data class for PTSPointCloud contains a sample point-cloud of PTS format.
class PaintedPlasterTexture
Data class for PaintedPlasterTexture contains albedo, normal and roughness texture files for painted plaster based material.
class RedwoodIndoorLivingRoom1
Data class for RedwoodIndoorLivingRoom1, containing dense point cloud, rgb sequence, clean depth sequence, noisy depth sequence, oni sequence, and ground-truth camera trajectory.
class RedwoodIndoorLivingRoom2
Data class for RedwoodIndoorLivingRoom2, containing dense point cloud, rgb sequence, clean depth sequence, noisy depth sequence, oni sequence, and ground-truth camera trajectory.
class RedwoodIndoorOffice1
Data class for RedwoodIndoorOffice1, containing dense point cloud, rgb sequence, clean depth sequence, noisy depth sequence, oni sequence, and ground-truth camera trajectory.
class RedwoodIndoorOffice2
Data class for RedwoodIndoorOffice2, containing dense point cloud, rgb sequence, clean depth sequence, noisy depth sequence, oni sequence, and ground-truth camera trajectory.
class SampleFountainRGBDImages
Data class for SampleFountainRGBDImages contains a sample set of 33 color and depth images from the Fountain RGBD dataset.
class SampleL515Bag
Data class for SampleL515Bag contains the SampleL515Bag.bag file.
class SampleNYURGBDImage
Data class for SampleNYURGBDImage contains a color image NYU_color.ppm and a depth image NYU_depth.pgm sample from NYU RGBD dataset.
class SampleRedwoodRGBDImages
Data class for SampleRedwoodRGBDImages contains a sample set of 5 color and depth images from Redwood RGBD dataset living-room1.
class SampleSUNRGBDImage
Data class for SampleSUNRGBDImage contains a color image SUN_color.jpg and a depth image SUN_depth.png sample from SUN RGBD dataset.
class SampleTUMRGBDImage
Data class for SampleTUMRGBDImage contains a color image TUM_color.png and a depth image TUM_depth.png sample from TUM RGBD dataset.
class SwordModel
Data class for SwordModel contains a sword model file, along with material and various other texture files. The model file can be accessed using GetPath(), however in order to access the paths to the texture files one may use GetPath(filename) method or get the unordered map of filename to path using GetPathMap().
class TerrazzoTexture
Data class for TerrazzoTexture contains albedo, normal and roughness texture files for terrazzo based material.
class TilesTexture
Data class for TilesTexture contains albedo, normal and roughness texture files for tiles based material.
class WoodFloorTexture
Data class for WoodFloorTexture contains albedo, normal and roughness texture files for wooden floor based material.
class WoodTexture
Data class for WoodTexture contains albedo, normal and roughness texture files for wood based material.
class FacetsModel
Data class for FacetsModel contains the facets.bin from the CloudViewer project.
class PolylinesModel
Data class for PolylinesModel contains the polylines.bin from the CloudViewer project.
class BalusterVase
Data class for BalusterVase contains the F1980_baluster_vase.glb from the CloudViewer project.
Functions
std::string LocateDataRoot ()
void SetCustomDownloadsPrefix (const std::string &prefix)
std::string GetCustomDownloadsPrefix ()
std::string CloudViewerDownloadsPrefix ()
Variables
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const std::vector< DataDescriptor > data_descriptors
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const std::vector< DataDescriptor > data_descriptors
static const std::vector< DataDescriptor > data_descriptors
static const std::vector< DataDescriptor > data_descriptors
static const std::vector< DataDescriptor > data_descriptors
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
static const DataDescriptor data_descriptor
Function Documentation
CloudViewerDownloadsPrefix()
std::string cloudViewer::data::CloudViewerDownloadsPrefix ()
Returns the URL prefix for the open3d_downloads's releases. See https://github.com/isl-org/open3d_downloads/releases/ for more info. This is hard-coded to have "/" at the end.
Definition at line 49 of file Dataset.cpp.
GetCustomDownloadsPrefix()
std::string cloudViewer::data::GetCustomDownloadsPrefix ()
Definition at line 47 of file Dataset.cpp.
Referenced by cloudViewer::data::BalusterVase::BalusterVase(), cloudViewer::data::FacetsModel::FacetsModel(), and cloudViewer::data::PolylinesModel::PolylinesModel().
LocateDataRoot()
std::string cloudViewer::data::LocateDataRoot ()
Function to return default data root directory in the following order:
(a) CLOUDVIEWER_DATA_ROOT environment variable. (b) $HOME/cloudViewer_data.
Definition at line 21 of file Dataset.cpp.
References cloudViewer::utility::filesystem::GetHomeDirectory().
Referenced by cloudViewer::data::Dataset::Dataset().
SetCustomDownloadsPrefix()
void cloudViewer::data::SetCustomDownloadsPrefix (const std::string & prefix)
Definition at line 36 of file Dataset.cpp.
References LogError.
Variable Documentation
data_descriptor [1/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220201-data/ArmadilloMesh.ply",
        "9e68ff1b1cc914ed88cd84f6a8235021"}
Definition at line 18 of file ArmadilloMesh.cpp.
Referenced by cloudViewer::data::DownloadDataset::DownloadDataset(), and cloudViewer::data::DownloadDataset::HasDownloaded().
data_descriptor [2/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/AvocadoModel.glb",
        "829f96a0a3a7d5556e0a263ea0699217"}
Definition at line 18 of file AvocadoModel.cpp.
data_descriptor [3/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220201-data/BunnyMesh.ply",
        "568f871d1a221ba6627569f1e6f9a3f2"}
Definition at line 18 of file BunnyMesh.cpp.
data_descriptor [4/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/CrateModel.zip",
        "20413eada103969bb3ca5df9aebc2034"}
Definition at line 18 of file CrateModel.cpp.
data_descriptor [5/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/DamagedHelmetModel.glb",
        "a3af6ad5a8329f22ba08b7f16e4a97d8"}
Definition at line 18 of file DamagedHelmetModel.cpp.
data_descriptor [6/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() +
                "20220201-data/DemoColoredICPPointClouds.zip",
        "bf8d469e892d76f2e69e1213207c0e30"}
Definition at line 18 of file DemoColoredICPPointClouds.cpp.
data_descriptor [7/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220201-data/DemoCropPointCloud.zip",
        "12dbcdddd3f0865d8312929506135e23"}
Definition at line 18 of file DemoCropPointCloud.cpp.
data_descriptor [8/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() +
                "20220301-data/DemoCustomVisualization.zip",
        "04cb716145c51d0119b59c7876249891"}
Definition at line 18 of file DemoCustomVisualization.cpp.
data_descriptor [9/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() +
                "doppler-icp-data/carla-town05-curved-walls.zip",
        "73a9828fb7790481168124c02398ee01"}
Definition at line 73 of file DemoDopplerICPSequence.cpp.
data_descriptor [10/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() +
                "20220201-data/DemoFeatureMatchingPointClouds.zip",
        "02f0703ce0cbf4df78ce2602ae33fc79"}
Definition at line 18 of file DemoFeatureMatchingPointClouds.cpp.
data_descriptor [11/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/DemoICPPointClouds.zip",
        "596cffe5f9c587045e7397ad70754de9"}
Definition at line 18 of file DemoICPPointClouds.cpp.
data_descriptor [12/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() +
                "20220201-data/DemoPoseGraphOptimization.zip",
        "af085b28d79dea7f0a50aef50c96b62c"}
Definition at line 18 of file DemoPoseGraphOptimization.cpp.
data_descriptor [13/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220201-data/EaglePointCloud.ply",
        "e4e6c77bc548e7eb7548542a0220ad78"}
Definition at line 18 of file EaglePointCloud.cpp.
data_descriptor [14/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/FlightHelmetModel.zip",
        "597c3aa8b46955fff1949a8baa768bb4"}
Definition at line 18 of file FlightHelmetModel.cpp.
data_descriptor [15/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/JackJackL515Bag.bag",
        "9f670dc92569b986b739c4179a659176"}
Definition at line 17 of file JackJackL515Bag.cpp.
data_descriptor [16/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220201-data/JuneauImage.jpg",
        "a090f6342893bdf0caefd83c6debbecd"}
Definition at line 18 of file JuneauImage.cpp.
data_descriptor [17/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220201-data/KnotMesh.ply",
        "bfc9f132ecdfb7f9fdc42abf620170fc"}
Definition at line 18 of file KnotMesh.cpp.
data_descriptor [18/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "redwood/livingroom1-fragments-ply.zip",
        "36e0eb23a66ccad6af52c05f8390d33e"}
Definition at line 18 of file LivingRoomPointClouds.cpp.
data_descriptor [19/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/LoungeRGBDImages.zip",
        "cdd307caef898519a8829ce1b6ab9f75"}
Definition at line 18 of file LoungeRGBDImages.cpp.
data_descriptor [20/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/MetalTexture.zip",
        "2b6a17e41157138868a2cd2926eedcc7"}
Definition at line 18 of file MetalTexture.cpp.
data_descriptor [21/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/MonkeyModel.zip",
        "fc330bf4fd8e022c1e5ded76139785d4"}
Definition at line 18 of file MonkeyModel.cpp.
data_descriptor [22/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "redwood/office1-fragments-ply.zip",
        "c519fe0495b3c731ebe38ae3a227ac25"}
Definition at line 18 of file OfficePointClouds.cpp.
data_descriptor [23/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() +
                "20220301-data/PaintedPlasterTexture.zip",
        "344096b29b06f14aac58f9ad73851dc2"}
Definition at line 18 of file PaintedPlasterTexture.cpp.
data_descriptor [24/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220201-data/fragment.pcd",
        "f3a613fd2bdecd699aabdd858fb29606"}
Definition at line 18 of file PCDPointCloud.cpp.
data_descriptor [25/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220201-data/fragment.ply",
        "831ecffd4d7cbbbe02494c5c351aa6e5"}
Definition at line 18 of file PLYPointCloud.cpp.
data_descriptor [26/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/point_cloud_sample1.pts",
        "5c2c618b703d0161e6e333fcbf55a1e9"}
Definition at line 18 of file PTSPointCloud.cpp.
data_descriptor [27/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() +
                "20220201-data/SampleFountainRGBDImages.zip",
        "c6c1b2171099f571e2a78d78675df350"}
Definition at line 18 of file SampleFountainRGBDImages.cpp.
data_descriptor [28/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "xxx/SampleICPPointClouds.zip",
        "9d1ead73e678fa2f51a70a933b0bf017"}
Definition at line 18 of file SampleICPPointClouds.cpp.
data_descriptor [29/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/SampleL515Bag.zip",
        "9770eeb194c78103037dbdbec78b9c8c"}
Definition at line 18 of file SampleL515Bag.cpp.
data_descriptor [30/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220201-data/SampleNYURGBDImage.zip",
        "b0baaf892c7ff9b202eb5fb40c5f7b58"}
Definition at line 18 of file SampleNYURGBDImage.cpp.
data_descriptor [31/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() +
                "20220301-data/SampleRedwoodRGBDImages.zip",
        "43971c5f690c9cfc52dda8c96a0140ee"}
Definition at line 18 of file SampleRedwoodRGBDImages.cpp.
data_descriptor [32/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220201-data/SampleSUNRGBDImage.zip",
        "b1a430586547c8986bdf8b36179a8e67"}
Definition at line 18 of file SampleSUNRGBDImage.cpp.
data_descriptor [33/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220201-data/SampleTUMRGBDImage.zip",
        "91758d42b142dbad7b0d90e857ad47a8"}
Definition at line 18 of file SampleTUMRGBDImage.cpp.
data_descriptor [34/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/SwordModel.zip",
        "eb7df358b5c31c839f03c4b3b4157c04"}
Definition at line 18 of file SwordModel.cpp.
data_descriptor [35/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/TerrazzoTexture.zip",
        "8d67f191fb5d80a27d8110902cac008e"}
Definition at line 18 of file TerrazzoTexture.cpp.
data_descriptor [36/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/TilesTexture.zip",
        "23f47f1e8e1799216724eb0c837c274d"}
Definition at line 18 of file TilesTexture.cpp.
data_descriptor [37/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/WoodFloorTexture.zip",
        "f11b3e50208095e87340049b9ac3c319"}
Definition at line 18 of file WoodFloorTexture.cpp.
data_descriptor [38/38]
const DataDescriptor cloudViewer::data::data_descriptor static
Initial value:
= {
        CloudViewerDownloadsPrefix() + "20220301-data/WoodTexture.zip",
        "28788c7ecc42d78d4d623afbab2301e9"}
Definition at line 18 of file WoodTexture.cpp.
data_descriptors [1/5]
const std::vector<DataDescriptor> cloudViewer::data::data_descriptors static
Initial value:
= {
        {CloudViewerDownloadsPrefix() + "20220301-data/bedroom01.zip",
         "2d1018ceeb72680f5d16b2f419da9bb1"},
        {CloudViewerDownloadsPrefix() + "20220301-data/bedroom02.zip",
         "5e6ffbccc0907dc5acc374aa76a79081"},
        {CloudViewerDownloadsPrefix() + "20220301-data/bedroom03.zip",
         "ebf13b89ec364b1788dd492c27b9b800"},
        {CloudViewerDownloadsPrefix() + "20220301-data/bedroom04.zip",
         "94c0e6c862a54588582b06520946fb15"},
        {CloudViewerDownloadsPrefix() + "20220301-data/bedroom05.zip",
         "54b927edb6fd61838025bc66ed767408"},
}
Definition at line 18 of file BedroomRGBDImages.cpp.
Referenced by cloudViewer::data::DownloadDataset::DownloadDataset().
data_descriptors [2/5]
const std::vector<DataDescriptor> cloudViewer::data::data_descriptors static
Initial value:
= {
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/livingroom.ply.zip",
         "841f32ff6294bb52d5f9574834e0925e"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/livingroom1-color.zip",
         "c23481094ca3859b204d2fcbb4e435a4", "color"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/livingroom1-depth-clean.zip",
         "6867ddac0e7aafe828a218b385f61985", "depth"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/livingroom1-depth-simulated.zip",
         "2fec03a29258a29b9ffedde88fddd676", "depth_noisy"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/livingroom1-traj.txt",
         "601ac4b51aba2455a90aed8aa1158c6a"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/livingroom1.oni.zip",
         "fb201903f211f31ccd01886457bb004c"},
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/dist-model.txt",
         "d8d7b6d29e754c2993a6eba4fd8d89ea"},
}
Definition at line 19 of file RedwoodIndoorLivingRoom1.cpp.
data_descriptors [3/5]
const std::vector<DataDescriptor> cloudViewer::data::data_descriptors static
Initial value:
= {
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/livingroom.ply.zip",
         "841f32ff6294bb52d5f9574834e0925e"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/livingroom2-color.zip",
         "34792f7aa35b6c8b62e394e9372b95d7", "color"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/livingroom2-depth-clean.zip",
         "569c7ba065c3a84de32b0d0844699f43", "depth"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/livingroom2-depth-simulated.zip",
         "cbb4a36b8488448d79ec93c202c0c90e", "depth_noisy"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/livingroom2-traj.txt",
         "193961c018f4c2a753458d5231544036"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/livingroom2.oni.zip",
         "b827aa33cddffc8131d9b25007930137"},
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/dist-model.txt",
         "d8d7b6d29e754c2993a6eba4fd8d89ea"},
}
Definition at line 18 of file RedwoodIndoorLivingRoom2.cpp.
data_descriptors [4/5]
const std::vector<DataDescriptor> cloudViewer::data::data_descriptors static
Initial value:
= {
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/office.ply.zip",
         "ba3640bba38f19c8f2d5e86e045eeae5"},
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/office1-color.zip",
         "6a58750880e83ac5948e0f28de294c04", "color"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/office1-depth-clean.zip",
         "0a952d68eb76e84fad63e362a59f82cd", "depth"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/office1-depth-simulated.zip",
         "7c7e479191d35c2ad1f8ac1c227f4f8d", "depth_noisy"},
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/office1-traj.txt",
         "3fac752ab38a4e8a96d1b5afa535f9f7"},
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/office1.oni.zip",
         "1edd52a60b052fde97b05ae3d628caba"},
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/dist-model.txt",
         "d8d7b6d29e754c2993a6eba4fd8d89ea"},
}
Definition at line 18 of file RedwoodIndoorOffice1.cpp.
data_descriptors [5/5]
const std::vector<DataDescriptor> cloudViewer::data::data_descriptors static
Initial value:
= {
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/office.ply.zip",
         "ba3640bba38f19c8f2d5e86e045eeae5"},
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/office2-color.zip",
         "487cdfacffc8fc8247a5b21e860a3794", "color"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/office2-depth-clean.zip",
         "386203a7a5dae21db6d8430ae36dcc8b", "depth"},
        {CloudViewerDownloadsPrefix() +
                 "augmented-icl-nuim/office2-depth-simulated.zip",
         "13f1c5b7c4f44524fa91f7ba87e44bb5", "depth_noisy"},
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/office2-traj.txt",
         "698f2f09da7d2ed3fcb604889e6f8479"},
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/office2.oni.zip",
         "dcbd567442f29bd6080d74b5a384cd0d"},
        {CloudViewerDownloadsPrefix() + "augmented-icl-nuim/dist-model.txt",
         "d8d7b6d29e754c2993a6eba4fd8d89ea"},
}
Definition at line 18 of file RedwoodIndoorOffice2.cpp.