ACloudViewer: cloudViewer::visualization::gui Namespace Reference
cloudViewer::visualization::gui Namespace Reference
Classes
class Application
class BitmapWindowSystem
class Button
class Checkbox
class Color
class ColorEdit
class Combobox
class Dialog
Base class for dialogs.
struct MouseEvent
struct TickEvent
struct KeyEvent
struct TextInputEvent
class DirEntry
class FileDialog
class FontDescription
class GLFWWindowSystem
struct Point
struct Size
struct Rect
class FontContext
class ImageWidget
class MaterialPool
class ScissorRectKey
class ImguiFilamentBridge
class Label
class Label3D
struct Margins
class Layout1D
class Vert
Lays out widgets vertically.
class CollapsableVert
class ScrollableVert
This a vertical layout that scrolls if it is smaller than its contents.
class Horiz
Lays out widgets horizontally.
class VGrid
class ListView
class Menu
class MenuBase
class MenuImgui
class MenuMacOS
class NumberEdit
class SelectionIndexLookup
class PickPointsInteractor
class ProgressBar
class RadioButton
class RotateSunInteractor
class RotateIBLInteractor
class FlyInteractor
class RotationInteractor
class RotateModelInteractor
class RotateCameraInteractor
class RotateCameraSphereInteractor
class PickInteractor
class Interactors
class SceneWidget
class Slider
class StackedWidget
class TabControl
class Task
class TextEdit
struct Theme
class ToggleSwitch
class CheckableTextTreeCell
class LUTTreeCell
class ColormapTreeCell
class TreeView
class UIImage
class VectorEdit
struct LayoutContext
struct DrawContext
class Widget
class WidgetProxy
Widget container to delegate any widget dynamically.
class WidgetStack
WidgetStack manages multiple widgets in a stack.
class Window
class WindowSystem
class PythonUnlocker
class PyWindow
class PyImageWidget
class PySceneWidget
Typedefs
using FontId = unsigned int
Enumerations
enum class MouseButton {
NONE = 0 , LEFT = (1 << 0) , MIDDLE = (1 << 1) , RIGHT = (1 << 2) ,
BUTTON4 = (1 << 3) , BUTTON5 = (1 << 4)
}
enum class KeyModifier {
NONE = 0 , SHIFT = (1 << 0) , CTRL = (1 << 1) , ALT = (1 << 2) ,
META = (1 << 3)
}
enum KeyName {
KEY_NONE = 0 , KEY_BACKSPACE = 8 , KEY_TAB = 9 , KEY_ENTER = 10 ,
KEY_ESCAPE = 27 , KEY_SPACE = 32 , KEY_EXCLAMATION = 33 , KEY_DOUBLE_QUOTE = 34 ,
KEY_HASH = 35 , KEY_DOLLAR_SIGN = 36 , KEY_PERCENT = 37 , KEY_AMPERSAND = 38 ,
KEY_SINGLE_QUOTE = 39 , KEY_LEFT_PAREN = 40 , KEY_RIGHT_PAREN = 41 , KEY_ASTERISK = 42 ,
KEY_PLUS = 43 , KEY_COMMA = 44 , KEY_MINUS = 45 , KEY_PERIOD = 46 ,
KEY_SLASH = 47 , KEY_0 = 48 , KEY_1 , KEY_2 ,
KEY_3 , KEY_4 , KEY_5 , KEY_6 ,
KEY_7 , KEY_8 , KEY_9 , KEY_COLON = 58 ,
KEY_SEMICOLON = 59 , KEY_LESS_THAN = 60 , KEY_EQUALS = 61 , KEY_GREATER_THAN = 62 ,
KEY_QUESTION_MARK = 63 , KEY_AT = 64 , KEY_LEFT_BRACKET = 91 , KEY_BACKSLASH = 92 ,
KEY_RIGHT_BRACKET = 93 , KEY_CARET = 94 , KEY_UNDERSCORE = 95 , KEY_BACKTICK = 96 ,
KEY_A = 97 , KEY_B , KEY_C , KEY_D ,
KEY_E , KEY_F , KEY_G , KEY_H ,
KEY_I , KEY_J , KEY_K , KEY_L ,
KEY_M , KEY_N , KEY_O , KEY_P ,
KEY_Q , KEY_R , KEY_S , KEY_T ,
KEY_U , KEY_V , KEY_W , KEY_X ,
KEY_Y , KEY_Z , KEY_LEFT_BRACE = 123 , KEY_PIPE = 124 ,
KEY_RIGHT_BRACE = 125 , KEY_TILDE = 126 , KEY_DELETE = 127 , KEY_LSHIFT = 256 ,
KEY_RSHIFT , KEY_LCTRL , KEY_RCTRL , KEY_ALT ,
KEY_META , KEY_CAPSLOCK , KEY_LEFT , KEY_RIGHT ,
KEY_UP , KEY_DOWN , KEY_INSERT , KEY_HOME ,
KEY_END , KEY_PAGEUP , KEY_PAGEDOWN , KEY_F1 = 290 ,
KEY_F2 , KEY_F3 , KEY_F4 , KEY_F5 ,
KEY_F6 , KEY_F7 , KEY_F8 , KEY_F9 ,
KEY_F10 , KEY_F11 , KEY_F12 , KEY_UNKNOWN = 1000
}
enum class BorderShape { NONE = 0 , RECT , ROUNDED_RECT }
enum class Alignment : unsigned int {
LEFT = 1 , HCENTER = 2 , RIGHT = 3 , TOP = (1 << 4) ,
VCENTER = (2 << 4) , BOTTOM = (3 << 4) , CENTER = (2 | (2 << 4))
}
enum class FontStyle { NORMAL = 0 , BOLD = 1 , ITALIC = 2 , BOLD_ITALIC = 3 }
enum class EventCallbackResult { IGNORED = 0 , HANDLED , CONSUMED }
Functions
constexpr Alignment operator| (Alignment x, Alignment y)
static Material * LoadMaterialTemplate (const std::string &path, Engine &engine)
void * GetNativeDrawable (GLFWwindow *glfw_window)
void PostNativeExposeEvent (GLFWwindow *glfw_window)
void ShowNativeAlert (const char *message)
ImVec4 colorToImgui (const Color &color)
uint32_t colorToImguiRGBA (const Color &color)
std::string FindFontPath (std::string font, FontStyle style)
void pybind_gui_events (py::module &m)
void cleanup_filament_atexit ()
void install_cleanup_atexit ()
void InitializeForPython (std::string resource_path, bool headless)
std::shared_ptr< geometry::Image > RenderToImageWithoutWindow (rendering::CloudViewerScene *scene, int width, int height)
std::shared_ptr< geometry::Image > RenderToDepthImageWithoutWindow (rendering::CloudViewerScene *scene, int width, int height, bool z_in_view_space)
void pybind_gui_classes (py::module &m_gui)
void pybind_gui (py::module &m)
Variables
static const char * kUiBlitTexParamName = "albedo"
static const char * kImageTexParamName = "image"
static const int PREFERRED_WRAP_WIDTH_EM = 35
static const Color DEFAULT_COLOR (0, 0, 0, 0)
static const Color DEFAULT_COLOR (0, 0, 0, 1)
static const float EXTRA_PADDING_Y = 1.0f
static const double MIN_FAR_PLANE = 1.0
static const double DELAY_FOR_BEST_RENDERING_SECS = 0.2
static const Color DEFAULT_BGCOLOR (0.001f, 0.001f, 0.001f, 0.0f)
bool g_installed_atexit = false
Typedef Documentation
FontId
using cloudViewer::visualization::gui::FontId = typedef unsigned int
Definition at line 68 of file Gui.h.
Enumeration Type Documentation
Alignment
enum cloudViewer::visualization::gui::Alignment : unsigned int strong
Enumerator
LEFT
HCENTER
RIGHT
TOP
VCENTER
BOTTOM
CENTER
Definition at line 55 of file Gui.h.
BorderShape
enum cloudViewer::visualization::gui::BorderShape strong
Enumerator
NONE
RECT
ROUNDED_RECT
Definition at line 53 of file Gui.h.
EventCallbackResult
enum cloudViewer::visualization::gui::EventCallbackResult strong
Enumerator
IGNORED
HANDLED
CONSUMED
Definition at line 175 of file gui.cpp.
FontStyle
enum cloudViewer::visualization::gui::FontStyle strong
Enumerator
NORMAL
BOLD
ITALIC
BOLD_ITALIC
Definition at line 70 of file Gui.h.
KeyModifier
enum cloudViewer::visualization::gui::KeyModifier strong
Enumerator
NONE
SHIFT
CTRL
ALT
META
Definition at line 37 of file Events.h.
KeyName
enum cloudViewer::visualization::gui::KeyName
Enumerator
KEY_NONE
KEY_BACKSPACE
KEY_TAB
KEY_ENTER
KEY_ESCAPE
KEY_SPACE
KEY_EXCLAMATION
KEY_DOUBLE_QUOTE
KEY_HASH
KEY_DOLLAR_SIGN
KEY_PERCENT
KEY_AMPERSAND
KEY_SINGLE_QUOTE
KEY_LEFT_PAREN
KEY_RIGHT_PAREN
KEY_ASTERISK
KEY_PLUS
KEY_COMMA
KEY_MINUS
KEY_PERIOD
KEY_SLASH
KEY_0
KEY_1
KEY_2
KEY_3
KEY_4
KEY_5
KEY_6
KEY_7
KEY_8
KEY_9
KEY_COLON
KEY_SEMICOLON
KEY_LESS_THAN
KEY_EQUALS
KEY_GREATER_THAN
KEY_QUESTION_MARK
KEY_AT
KEY_LEFT_BRACKET
KEY_BACKSLASH
KEY_RIGHT_BRACKET
KEY_CARET
KEY_UNDERSCORE
KEY_BACKTICK
KEY_A
KEY_B
KEY_C
KEY_D
KEY_E
KEY_F
KEY_G
KEY_H
KEY_I
KEY_J
KEY_K
KEY_L
KEY_M
KEY_N
KEY_O
KEY_P
KEY_Q
KEY_R
KEY_S
KEY_T
KEY_U
KEY_V
KEY_W
KEY_X
KEY_Y
KEY_Z
KEY_LEFT_BRACE
KEY_PIPE
KEY_RIGHT_BRACE
KEY_TILDE
KEY_DELETE
KEY_LSHIFT
KEY_RSHIFT
KEY_LCTRL
KEY_RCTRL
KEY_ALT
KEY_META
KEY_CAPSLOCK
KEY_LEFT
KEY_RIGHT
KEY_UP
KEY_DOWN
KEY_INSERT
KEY_HOME
KEY_END
KEY_PAGEUP
KEY_PAGEDOWN
KEY_F1
KEY_F2
KEY_F3
KEY_F4
KEY_F5
KEY_F6
KEY_F7
KEY_F8
KEY_F9
KEY_F10
KEY_F11
KEY_F12
KEY_UNKNOWN
Definition at line 96 of file Events.h.
MouseButton
enum cloudViewer::visualization::gui::MouseButton strong
Enumerator
NONE
LEFT
MIDDLE
RIGHT
BUTTON4
BUTTON5
Definition at line 26 of file Events.h.
Function Documentation
cleanup_filament_atexit()
void cloudViewer::visualization::gui::cleanup_filament_atexit ()
Definition at line 128 of file gui.cpp.
References cloudViewer::visualization::gui::Application::GetInstance(), and cloudViewer::visualization::gui::Application::OnTerminate().
Referenced by install_cleanup_atexit().
colorToImgui()
ImVec4 cloudViewer::visualization::gui::colorToImgui (const Color & color)
Definition at line 20 of file Util.cpp.
References color.
Referenced by cloudViewer::visualization::gui::Button::Draw(), cloudViewer::visualization::gui::Checkbox::Draw(), cloudViewer::visualization::gui::Combobox::Draw(), cloudViewer::visualization::gui::ImageWidget::Draw(), cloudViewer::visualization::gui::Label::Draw(), cloudViewer::visualization::gui::CollapsableVert::Draw(), cloudViewer::visualization::gui::ScrollableVert::Draw(), cloudViewer::visualization::gui::ListView::Draw(), cloudViewer::visualization::gui::NumberEdit::Draw(), cloudViewer::visualization::gui::RadioButton::Draw(), cloudViewer::visualization::gui::TextEdit::Draw(), cloudViewer::visualization::gui::TreeView::Draw(), cloudViewer::visualization::gui::VectorEdit::Draw(), and cloudViewer::visualization::gui::Window::Window().
colorToImguiRGBA()
uint32_t cloudViewer::visualization::gui::colorToImguiRGBA (const Color & color)
Definition at line 25 of file Util.cpp.
References color.
Referenced by cloudViewer::visualization::gui::ProgressBar::Draw(), cloudViewer::visualization::gui::SceneWidget::Draw(), cloudViewer::visualization::gui::ToggleSwitch::Draw(), and cloudViewer::visualization::gui::TreeView::Draw().
FindFontPath()
std::string cloudViewer::visualization::gui::FindFontPath (std::string font, FontStyle style)
Definition at line 32 of file Util.cpp.
References BOLD, BOLD_ITALIC, cloudViewer::utility::filesystem::FileExists(), filename, cloudViewer::utility::filesystem::FindFilesRecursively(), cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), cloudViewer::utility::filesystem::GetFileNameWithoutDirectory(), cloudViewer::utility::filesystem::GetFileNameWithoutExtension(), cloudViewer::utility::filesystem::GetFileParentDirectory(), ITALIC, NORMAL, and cloudViewer::t::geometry::path.
Referenced by cloudViewer::visualization::gui::Application::SetFont().
GetNativeDrawable()
void * cloudViewer::visualization::gui::GetNativeDrawable (GLFWwindow * glfw_window)
Definition at line 23 of file NativeLinux.cpp.
Referenced by cloudViewer::visualization::gui::GLFWWindowSystem::GetNativeDrawable().
InitializeForPython()
void cloudViewer::visualization::gui::InitializeForPython (std::string resource_path, bool headless)
Definition at line 136 of file gui.cpp.
References cloudViewer::utility::filesystem::GetFileParentDirectory(), cloudViewer::visualization::gui::Application::GetInstance(), cloudViewer::visualization::gui::Application::Initialize(), and install_cleanup_atexit().
Referenced by pybind_gui_classes(), and cloudViewer::visualization::rendering::PyOffscreenRenderer::PyOffscreenRenderer().
install_cleanup_atexit()
void cloudViewer::visualization::gui::install_cleanup_atexit ()
Definition at line 130 of file gui.cpp.
References cleanup_filament_atexit(), and g_installed_atexit.
Referenced by InitializeForPython().
LoadMaterialTemplate()
static Material* cloudViewer::visualization::gui::LoadMaterialTemplate (const std::string & path, Engine & engine) static
Definition at line 57 of file ImguiFilamentBridge.cpp.
References bytes, QtCompat::endl(), cloudViewer::utility::filesystem::FReadToBuffer(), and cloudViewer::t::geometry::path.
Referenced by cloudViewer::visualization::gui::ImguiFilamentBridge::ImguiFilamentBridge().
operator|()
constexpr Alignment cloudViewer::visualization::gui::operator| (Alignment x, Alignment y) constexpr
Definition at line 64 of file Gui.h.
PostNativeExposeEvent()
void cloudViewer::visualization::gui::PostNativeExposeEvent (GLFWwindow * glfw_window)
Definition at line 38 of file NativeLinux.cpp.
Referenced by cloudViewer::visualization::gui::GLFWWindowSystem::PostRedrawEvent().
pybind_gui()
void cloudViewer::visualization::gui::pybind_gui (py::module & m)
Referenced by cloudViewer::visualization::pybind_visualization().
pybind_gui_classes()
void cloudViewer::visualization::gui::pybind_gui_classes (py::module & m_gui)
Definition at line 309 of file gui.cpp.
References cloudViewer::visualization::gui::Window::AddChild(), cloudViewer::visualization::gui::FileDialog::AddFilter(), cloudViewer::visualization::gui::Layout1D::AddFixed(), cloudViewer::visualization::gui::Application::AddFont(), cloudViewer::visualization::gui::Combobox::AddItem(), cloudViewer::visualization::gui::TreeView::AddItem(), cloudViewer::visualization::gui::SceneWidget::AddLabel(), cloudViewer::visualization::gui::Menu::AddSeparator(), cloudViewer::visualization::gui::Layout1D::AddStretch(), cloudViewer::visualization::gui::TabControl::AddTab(), cloudViewer::visualization::gui::TreeView::AddTextItem(), cloudViewer::visualization::gui::FontDescription::AddTypefaceForCodePoints(), cloudViewer::visualization::gui::FontDescription::AddTypefaceForLanguage(), cloudViewer::visualization::gui::Application::AddWindow(), cloudViewer::visualization::gui::UIImage::ANY, cloudViewer::visualization::gui::UIImage::ASPECT, BOLD, BOLD_ITALIC, cloudViewer::visualization::gui::Margins::bottom, cloudViewer::visualization::gui::Widget::CalcPreferredSize(), cloudViewer::visualization::gui::Combobox::ChangeItem(), cloudViewer::visualization::gui::TreeView::Clear(), cloudViewer::visualization::gui::Combobox::ClearItems(), cloudViewer::visualization::gui::Window::Close(), cloudViewer::visualization::gui::Window::CloseDialog(), color, cloudViewer::visualization::gui::Widget::CONSUMED, CONSUMED, context, cloudViewer::visualization::gui::Application::DEFAULT_FONT_ID, cloudViewer::visualization::gui::Theme::default_layout_spacing, cloudViewer::visualization::gui::Theme::default_margin, cloudViewer::visualization::gui::SceneWidget::EnableSceneCaching(), cloudViewer::visualization::gui::Theme::font_size, cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::Color::GetAlpha(), cloudViewer::visualization::gui::Widget::GetBackgroundColor(), cloudViewer::visualization::gui::Color::GetBlue(), cloudViewer::visualization::gui::Rect::GetBottom(), cloudViewer::visualization::gui::TreeView::GetCanSelectItemsWithChildren(), cloudViewer::visualization::gui::SceneWidget::GetCenterOfRotation(), cloudViewer::visualization::gui::CheckableTextTreeCell::GetCheckbox(), cloudViewer::visualization::gui::LUTTreeCell::GetCheckbox(), cloudViewer::visualization::gui::Widget::GetChildren(), cloudViewer::visualization::gui::LUTTreeCell::GetColorEdit(), cloudViewer::visualization::gui::ColormapTreeCell::GetColorEdit(), cloudViewer::visualization::gui::Window::GetContentRect(), cloudViewer::visualization::gui::NumberEdit::GetDecimalPrecision(), cloudViewer::visualization::gui::NumberEdit::GetDoubleValue(), cloudViewer::visualization::gui::Slider::GetDoubleValue(), cloudViewer::visualization::gui::Label::GetFontId(), cloudViewer::visualization::gui::CollapsableVert::GetFontId(), cloudViewer::visualization::gui::Widget::GetFrame(), cloudViewer::visualization::gui::WidgetProxy::GetFrame(), cloudViewer::visualization::gui::Color::GetGreen(), cloudViewer::visualization::gui::Margins::GetHoriz(), cloudViewer::visualization::gui::Button::GetHorizontalPaddingEm(), cloudViewer::visualization::gui::Application::GetInstance(), cloudViewer::visualization::gui::NumberEdit::GetIntValue(), cloudViewer::visualization::gui::Slider::GetIntValue(), cloudViewer::visualization::gui::Button::GetIsOn(), cloudViewer::visualization::gui::ToggleSwitch::GetIsOn(), cloudViewer::visualization::gui::CollapsableVert::GetIsOpen(), cloudViewer::visualization::gui::Button::GetIsToggleable(), cloudViewer::visualization::gui::Combobox::GetItem(), cloudViewer::visualization::gui::TreeView::GetItem(), cloudViewer::visualization::gui::CheckableTextTreeCell::GetLabel(), cloudViewer::visualization::gui::LUTTreeCell::GetLabel(), cloudViewer::visualization::gui::Rect::GetLeft(), cloudViewer::visualization::gui::VGrid::GetMargins(), cloudViewer::visualization::gui::NumberEdit::GetMaximumValue(), cloudViewer::visualization::gui::Slider::GetMaximumValue(), cloudViewer::visualization::gui::Application::GetMenubar(), cloudViewer::visualization::gui::NumberEdit::GetMinimumValue(), cloudViewer::visualization::gui::Slider::GetMinimumValue(), cloudViewer::visualization::gui::ColormapTreeCell::GetNumberEdit(), cloudViewer::visualization::gui::Combobox::GetNumberOfItems(), cloudViewer::visualization::gui::Window::GetOSFrame(), cloudViewer::visualization::gui::TextEdit::GetPlaceholderText(), cloudViewer::visualization::gui::Label3D::GetPosition(), cloudViewer::visualization::gui::Horiz::GetPreferredHeight(), cloudViewer::visualization::gui::Vert::GetPreferredWidth(), cloudViewer::visualization::gui::VGrid::GetPreferredWidth(), cloudViewer::visualization::gui::Color::GetRed(), cloudViewer::visualization::gui::Window::GetRenderer(), cloudViewer::visualization::gui::Application::GetResourcePath(), cloudViewer::visualization::gui::Rect::GetRight(), cloudViewer::visualization::gui::TreeView::GetRootItem(), cloudViewer::visualization::gui::UIImage::GetScaling(), cloudViewer::visualization::gui::Window::GetScaling(), cloudViewer::visualization::gui::SceneWidget::GetScene(), cloudViewer::visualization::gui::Combobox::GetSelectedIndex(), cloudViewer::visualization::gui::ListView::GetSelectedIndex(), cloudViewer::visualization::gui::RadioButton::GetSelectedIndex(), cloudViewer::visualization::gui::StackedWidget::GetSelectedIndex(), cloudViewer::visualization::gui::TreeView::GetSelectedItemId(), cloudViewer::visualization::gui::Combobox::GetSelectedValue(), cloudViewer::visualization::gui::ListView::GetSelectedValue(), cloudViewer::visualization::gui::RadioButton::GetSelectedValue(), cloudViewer::visualization::gui::Window::GetSize(), cloudViewer::visualization::gui::VGrid::GetSpacing(), cloudViewer::visualization::gui::Button::GetText(), cloudViewer::visualization::gui::Label::GetText(), cloudViewer::visualization::gui::Label3D::GetText(), cloudViewer::visualization::gui::CollapsableVert::GetText(), cloudViewer::visualization::gui::TextEdit::GetText(), cloudViewer::visualization::gui::Label::GetTextColor(), cloudViewer::visualization::gui::Label3D::GetTextColor(), cloudViewer::visualization::gui::Window::GetTheme(), cloudViewer::visualization::gui::Window::GetTitle(), cloudViewer::visualization::gui::Widget::GetTooltip(), cloudViewer::visualization::gui::Rect::GetTop(), cloudViewer::visualization::gui::ImageWidget::GetUIImage(), cloudViewer::visualization::gui::ColorEdit::GetValue(), cloudViewer::visualization::gui::ProgressBar::GetValue(), cloudViewer::visualization::gui::VectorEdit::GetValue(), cloudViewer::visualization::gui::Margins::GetVert(), cloudViewer::visualization::gui::Button::GetVerticalPaddingEm(), cloudViewer::visualization::gui::WidgetProxy::GetWidget(), HANDLED, height, cloudViewer::visualization::gui::Size::height, cloudViewer::visualization::gui::Rect::height, cloudViewer::visualization::gui::Widget::Constraints::height, cloudViewer::visualization::gui::Widget::IGNORED, IGNORED, image, InitializeForPython(), cloudViewer::visualization::gui::Window::IsActiveWindow(), cloudViewer::visualization::gui::Checkbox::IsChecked(), cloudViewer::visualization::gui::Widget::IsEnabled(), cloudViewer::visualization::gui::Widget::IsVisible(), cloudViewer::visualization::gui::Window::IsVisible(), ITALIC, cloudViewer::visualization::gui::SceneWidget::Key(), cloudViewer::visualization::gui::PySceneWidget::Key(), cloudViewer::visualization::gui::Margins::left, cloudViewer::visualization::gui::SceneWidget::LookAt(), cloudViewer::visualization::gui::FontDescription::MONOSPACE, cloudViewer::visualization::gui::SceneWidget::Mouse(), cloudViewer::visualization::gui::PySceneWidget::Mouse(), name, cloudViewer::visualization::gui::UIImage::NONE, NORMAL, cloudViewer::visualization::gui::Application::Now(), cloudViewer::visualization::gui::PyWindow::on_layout_, cloudViewer::visualization::gui::FileDialog::OPEN, cloudViewer::t::geometry::path, cloudViewer::visualization::gui::WidgetStack::PopWidget(), cloudViewer::visualization::gui::Window::PostRedraw(), cloudViewer::visualization::gui::Application::PostToMainThread(), cloudViewer::visualization::gui::WidgetStack::PushWidget(), cloudViewer::visualization::gui::Application::Quit(), cloudViewer::visualization::gui::Combobox::RemoveItem(), cloudViewer::visualization::gui::TreeView::RemoveItem(), cloudViewer::visualization::gui::SceneWidget::RemoveLabel(), RenderToImageWithoutWindow(), result, cloudViewer::visualization::gui::Margins::right, cloudViewer::visualization::gui::Application::RunInThread(), cloudViewer::visualization::gui::Application::RunOneTick(), cloudViewer::visualization::gui::FontDescription::SANS_SERIF, cloudViewer::visualization::gui::FileDialog::SAVE, cloudViewer::visualization::gui::SceneWidget::SceneWidget(), cloudViewer::visualization::gui::Widget::SetBackgroundColor(), cloudViewer::visualization::gui::TreeView::SetCanSelectItemsWithChildren(), cloudViewer::visualization::gui::SceneWidget::SetCenterOfRotation(), cloudViewer::visualization::gui::Checkbox::SetChecked(), cloudViewer::visualization::gui::Color::SetColor(), cloudViewer::visualization::gui::NumberEdit::SetDecimalPrecision(), cloudViewer::visualization::gui::Widget::SetEnabled(), cloudViewer::visualization::gui::Window::SetFocusWidget(), cloudViewer::visualization::gui::Application::SetFont(), cloudViewer::visualization::gui::Label::SetFontId(), cloudViewer::visualization::gui::CollapsableVert::SetFontId(), cloudViewer::visualization::gui::Widget::SetFrame(), cloudViewer::visualization::gui::CollapsableVert::SetIsOpen(), cloudViewer::visualization::gui::ListView::SetItems(), cloudViewer::visualization::gui::RadioButton::SetItems(), cloudViewer::visualization::gui::NumberEdit::SetLimits(), cloudViewer::visualization::gui::Slider::SetLimits(), cloudViewer::visualization::gui::ListView::SetMaxVisibleItems(), cloudViewer::visualization::gui::Application::SetMenubar(), cloudViewer::visualization::gui::Window::SetNeedsLayout(), cloudViewer::visualization::gui::Button::SetOn(), cloudViewer::visualization::gui::ToggleSwitch::SetOn(), cloudViewer::visualization::gui::FileDialog::SetOnCancel(), cloudViewer::visualization::gui::Checkbox::SetOnChecked(), cloudViewer::visualization::gui::Button::SetOnClicked(), cloudViewer::visualization::gui::ToggleSwitch::SetOnClicked(), cloudViewer::visualization::gui::Window::SetOnClose(), cloudViewer::visualization::gui::FileDialog::SetOnDone(), cloudViewer::visualization::gui::PyImageWidget::SetOnKey(), cloudViewer::visualization::gui::PySceneWidget::SetOnKey(), cloudViewer::visualization::gui::Window::SetOnKeyEvent(), cloudViewer::visualization::gui::Window::SetOnMenuItemActivated(), cloudViewer::visualization::gui::PyImageWidget::SetOnMouse(), cloudViewer::visualization::gui::PySceneWidget::SetOnMouse(), cloudViewer::visualization::gui::TabControl::SetOnSelectedTabChanged(), cloudViewer::visualization::gui::RadioButton::SetOnSelectionChanged(), cloudViewer::visualization::gui::TreeView::SetOnSelectionChanged(), cloudViewer::visualization::gui::SceneWidget::SetOnSunDirectionChanged(), cloudViewer::visualization::gui::TextEdit::SetOnTextChanged(), cloudViewer::visualization::gui::Window::SetOnTickEvent(), cloudViewer::visualization::gui::WidgetStack::SetOnTop(), cloudViewer::visualization::gui::TextEdit::SetOnValueChanged(), cloudViewer::visualization::gui::ListView::SetOnValueChanged(), cloudViewer::visualization::gui::Combobox::SetOnValueChanged(), cloudViewer::visualization::gui::ColorEdit::SetOnValueChanged(), cloudViewer::visualization::gui::VectorEdit::SetOnValueChanged(), cloudViewer::visualization::gui::NumberEdit::SetOnValueChanged(), cloudViewer::visualization::gui::Slider::SetOnValueChanged(), cloudViewer::visualization::gui::Window::SetOSFrame(), cloudViewer::visualization::gui::FileDialog::SetPath(), cloudViewer::visualization::gui::TextEdit::SetPlaceholderText(), cloudViewer::visualization::gui::Label3D::SetPosition(), cloudViewer::visualization::gui::Horiz::SetPreferredHeight(), cloudViewer::visualization::gui::Vert::SetPreferredWidth(), cloudViewer::visualization::gui::VGrid::SetPreferredWidth(), cloudViewer::visualization::gui::NumberEdit::SetPreferredWidth(), cloudViewer::visualization::gui::UIImage::SetScaling(), cloudViewer::visualization::gui::SceneWidget::SetScene(), cloudViewer::visualization::gui::Combobox::SetSelectedIndex(), cloudViewer::visualization::gui::ListView::SetSelectedIndex(), cloudViewer::visualization::gui::RadioButton::SetSelectedIndex(), cloudViewer::visualization::gui::StackedWidget::SetSelectedIndex(), cloudViewer::visualization::gui::TreeView::SetSelectedItemId(), cloudViewer::visualization::gui::Combobox::SetSelectedValue(), cloudViewer::visualization::gui::Window::SetSize(), cloudViewer::visualization::gui::Button::SetText(), cloudViewer::visualization::gui::Label::SetText(), cloudViewer::visualization::gui::Label3D::SetText(), cloudViewer::visualization::gui::CollapsableVert::SetText(), cloudViewer::visualization::gui::TextEdit::SetText(), cloudViewer::visualization::gui::Label::SetTextColor(), cloudViewer::visualization::gui::Label3D::SetTextColor(), cloudViewer::visualization::gui::Window::SetTitle(), cloudViewer::visualization::gui::Button::SetToggleable(), cloudViewer::visualization::gui::Widget::SetTooltip(), cloudViewer::visualization::gui::ImageWidget::SetUIImage(), cloudViewer::visualization::gui::SceneWidget::SetupCamera(), cloudViewer::visualization::gui::ColorEdit::SetValue(), cloudViewer::visualization::gui::VectorEdit::SetValue(), cloudViewer::visualization::gui::NumberEdit::SetValue(), cloudViewer::visualization::gui::Slider::SetValue(), cloudViewer::visualization::gui::ProgressBar::SetValue(), cloudViewer::visualization::gui::SceneWidget::SetViewControls(), cloudViewer::visualization::gui::Widget::SetVisible(), cloudViewer::visualization::gui::Window::Show(), cloudViewer::visualization::gui::Window::ShowDialog(), cloudViewer::visualization::gui::Window::ShowMenu(), cloudViewer::visualization::gui::Window::ShowMessageBox(), size, cloudViewer::visualization::gui::Window::SizeToFit(), cloudViewer::visualization::TakeOwnership(), theme, cloudViewer::visualization::gui::Margins::top, cloudViewer::visualization::gui::ImageWidget::UpdateImage(), width, cloudViewer::visualization::gui::Size::width, cloudViewer::visualization::gui::Rect::width, cloudViewer::visualization::gui::Widget::Constraints::width, cloudViewer::visualization::gui::Rect::x, and cloudViewer::visualization::gui::Rect::y.
pybind_gui_events()
void cloudViewer::visualization::gui::pybind_gui_events (py::module & m)
Definition at line 19 of file events.cpp.
References ALT, cloudViewer::visualization::gui::MouseEvent::button, BUTTON4, BUTTON5, CTRL, cloudViewer::visualization::gui::KeyEvent::isRepeat, cloudViewer::visualization::gui::KeyEvent::key, KEY_0, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_A, KEY_ALT, KEY_AMPERSAND, KEY_ASTERISK, KEY_AT, KEY_B, KEY_BACKSLASH, KEY_BACKSPACE, KEY_BACKTICK, KEY_C, KEY_CAPSLOCK, KEY_CARET, KEY_COLON, KEY_COMMA, KEY_D, KEY_DELETE, KEY_DOLLAR_SIGN, KEY_DOUBLE_QUOTE, KEY_DOWN, KEY_E, KEY_END, KEY_ENTER, KEY_EQUALS, KEY_ESCAPE, KEY_EXCLAMATION, KEY_F, KEY_F1, KEY_F10, KEY_F11, KEY_F12, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_G, KEY_GREATER_THAN, KEY_H, KEY_HASH, KEY_HOME, KEY_I, KEY_INSERT, KEY_J, KEY_K, KEY_L, KEY_LCTRL, KEY_LEFT, KEY_LEFT_BRACE, KEY_LEFT_BRACKET, KEY_LEFT_PAREN, KEY_LESS_THAN, KEY_LSHIFT, KEY_M, KEY_META, KEY_MINUS, KEY_N, KEY_NONE, KEY_O, KEY_P, KEY_PAGEDOWN, KEY_PAGEUP, KEY_PERCENT, KEY_PERIOD, KEY_PIPE, KEY_PLUS, KEY_Q, KEY_QUESTION_MARK, KEY_R, KEY_RCTRL, KEY_RIGHT, KEY_RIGHT_BRACE, KEY_RIGHT_BRACKET, KEY_RIGHT_PAREN, KEY_RSHIFT, KEY_S, KEY_SEMICOLON, KEY_SINGLE_QUOTE, KEY_SLASH, KEY_SPACE, KEY_T, KEY_TAB, KEY_TILDE, KEY_U, KEY_UNDERSCORE, KEY_UNKNOWN, KEY_UP, KEY_V, KEY_W, KEY_X, KEY_Y, KEY_Z, LEFT, LogWarning, META, MIDDLE, cloudViewer::visualization::gui::MouseEvent::modifiers, cloudViewer::visualization::gui::MouseEvent::move, NONE, RIGHT, SHIFT, cloudViewer::visualization::gui::MouseEvent::type, cloudViewer::visualization::gui::KeyEvent::type, cloudViewer::visualization::gui::MouseEvent::wheel, cloudViewer::visualization::gui::MouseEvent::x, and cloudViewer::visualization::gui::MouseEvent::y.
RenderToDepthImageWithoutWindow()
std::shared_ptr< geometry::Image > cloudViewer::visualization::gui::RenderToDepthImageWithoutWindow (rendering::CloudViewerScene * scene, int width, int height, bool z_in_view_space)
Definition at line 165 of file gui.cpp.
References cloudViewer::visualization::gui::Application::GetInstance(), cloudViewer::visualization::rendering::CloudViewerScene::GetRenderer(), cloudViewer::visualization::rendering::CloudViewerScene::GetScene(), cloudViewer::visualization::rendering::CloudViewerScene::GetView(), height, cloudViewer::visualization::gui::Application::RenderToDepthImage(), and width.
Referenced by cloudViewer::visualization::rendering::PyOffscreenRenderer::RenderToDepthImage().
RenderToImageWithoutWindow()
std::shared_ptr< geometry::Image > cloudViewer::visualization::gui::RenderToImageWithoutWindow (rendering::CloudViewerScene * scene, int width, int height)
Definition at line 158 of file gui.cpp.
References cloudViewer::visualization::gui::Application::GetInstance(), cloudViewer::visualization::rendering::CloudViewerScene::GetRenderer(), cloudViewer::visualization::rendering::CloudViewerScene::GetScene(), cloudViewer::visualization::rendering::CloudViewerScene::GetView(), height, cloudViewer::visualization::gui::Application::RenderToImage(), and width.
Referenced by pybind_gui_classes(), and cloudViewer::visualization::rendering::PyOffscreenRenderer::RenderToImage().
ShowNativeAlert()
void cloudViewer::visualization::gui::ShowNativeAlert (const char * message)
Definition at line 55 of file NativeLinux.cpp.
References cloudViewer::visualization::gui::Application::GetInstance(), and cloudViewer::visualization::gui::Application::ShowMessageBox().
Referenced by cloudViewer::visualization::gui::Application::RunOneTick().
Variable Documentation
DEFAULT_BGCOLOR
const Color cloudViewer::visualization::gui::DEFAULT_BGCOLOR(0.001f, 0.001f, 0.001f, 0.0f) (0. 001f, 0. 001f, 0. 001f, 0. 0f) static
Referenced by cloudViewer::visualization::gui::Widget::IsDefaultBackgroundColor().
DEFAULT_COLOR [1/2]
const Color cloudViewer::visualization::gui::DEFAULT_COLOR(0, 0, 0, 0) (0 , 0 , 0 , 0) static
Referenced by cloudViewer::visualization::gui::Label::Draw().
DEFAULT_COLOR [2/2]
const Color cloudViewer::visualization::gui::DEFAULT_COLOR(0, 0, 0, 1) (0 , 0 , 0 , 1) static
DELAY_FOR_BEST_RENDERING_SECS
const double cloudViewer::visualization::gui::DELAY_FOR_BEST_RENDERING_SECS = 0.2 static
Definition at line 42 of file SceneWidget.cpp.
Referenced by cloudViewer::visualization::gui::SceneWidget::Tick().
EXTRA_PADDING_Y
const float cloudViewer::visualization::gui::EXTRA_PADDING_Y = 1.0f static
Definition at line 25 of file MenuImgui.cpp.
Referenced by cloudViewer::visualization::gui::MenuImgui::CalcHeight(), and cloudViewer::visualization::gui::MenuImgui::DrawMenuBar().
g_installed_atexit
bool cloudViewer::visualization::gui::g_installed_atexit = false
Definition at line 127 of file gui.cpp.
Referenced by install_cleanup_atexit().
kImageTexParamName
const char* cloudViewer::visualization::gui::kImageTexParamName = "image" static
Definition at line 110 of file ImguiFilamentBridge.cpp.
Referenced by cloudViewer::visualization::gui::ImguiFilamentBridge::Update().
kUiBlitTexParamName
const char* cloudViewer::visualization::gui::kUiBlitTexParamName = "albedo" static
Definition at line 109 of file ImguiFilamentBridge.cpp.
Referenced by cloudViewer::visualization::gui::ImguiFilamentBridge::CreateAtlasTextureAlpha8().
MIN_FAR_PLANE
const double cloudViewer::visualization::gui::MIN_FAR_PLANE = 1.0 static
Definition at line 40 of file SceneWidget.cpp.
PREFERRED_WRAP_WIDTH_EM
const int cloudViewer::visualization::gui::PREFERRED_WRAP_WIDTH_EM = 35 static
Definition at line 31 of file Label.cpp.
Referenced by cloudViewer::visualization::gui::Label::CalcPreferredSize().