ACloudViewer: cloudViewer::benchmarks Namespace Reference
cloudViewer::benchmarks Namespace Reference
Classes
class TestKDTreeLine0
class SamplePointsFixture
Functions
core::Tensor Rand (const core::SizeVector &shape, size_t seed, const std::pair< core::Scalar, core::Scalar > &range, core::Dtype dtype, const core::Device &device=core::Device("CPU:0"))
Returns a Tensor with random values within the range range .
static void BM_TestKDTreeLine0 (benchmark::State &state)
BENCHMARK (BM_TestKDTreeLine0) -> Args({1<< 5, 1<< 10}) ->Args({1<< 9, 1<< 11})
MinTime (0.1) -> Ranges({{1<< 0, 1<< 14}, {1<< 16, 1<< 22}})
BENCHMARK_DEFINE_F (SamplePointsFixture, Poisson)(benchmark
BENCHMARK_REGISTER_F (SamplePointsFixture, Poisson) -> Args({123}) ->Args({1000})
BENCHMARK_DEFINE_F (SamplePointsFixture, Uniform)(benchmark
BENCHMARK_REGISTER_F (SamplePointsFixture, Uniform) -> Args({123}) ->Args({1000})
static void BM_TestPCGrid0 (::benchmark::State &state)
static void BM_TestPCGrid0_Args (benchmark::internal::Benchmark *b)
BENCHMARK (BM_TestPCGrid0) -> MinTime(0.1) ->Apply(BM_TestPCGrid0_Args)
Variables
TestKDTreeLine0 testKDTreeLine0
Function Documentation
BENCHMARK() [1/2]
cloudViewer::benchmarks::BENCHMARK (BM_TestKDTreeLine0) -> Args({1<< 5, 1<< 10}) ->Args({1<< 9, 1<< 11})
BENCHMARK() [2/2]
cloudViewer::benchmarks::BENCHMARK (BM_TestPCGrid0) -> MinTime(0.1) ->Apply(BM_TestPCGrid0_Args)
BENCHMARK_DEFINE_F() [1/2]
cloudViewer::benchmarks::BENCHMARK_DEFINE_F (SamplePointsFixture , Poisson)
Definition at line 30 of file SamplePoints.cpp.
BENCHMARK_DEFINE_F() [2/2]
cloudViewer::benchmarks::BENCHMARK_DEFINE_F (SamplePointsFixture , Uniform)
Definition at line 38 of file SamplePoints.cpp.
BENCHMARK_REGISTER_F() [1/2]
cloudViewer::benchmarks::BENCHMARK_REGISTER_F (SamplePointsFixture , Poisson) -> Args({123}) ->Args({1000})
BENCHMARK_REGISTER_F() [2/2]
cloudViewer::benchmarks::BENCHMARK_REGISTER_F (SamplePointsFixture , Uniform) -> Args({123}) ->Args({1000})
BM_TestKDTreeLine0()
static void cloudViewer::benchmarks::BM_TestKDTreeLine0 (benchmark::State & state) static
Definition at line 63 of file KDTreeFlann.cpp.
References cloudViewer::benchmarks::TestKDTreeLine0::search(), cloudViewer::benchmarks::TestKDTreeLine0::setup(), size, and testKDTreeLine0.
BM_TestPCGrid0()
static void cloudViewer::benchmarks::BM_TestPCGrid0 (::benchmark::State & state) static
Definition at line 145 of file PointCloudIO.cpp.
References size.
BM_TestPCGrid0_Args()
static void cloudViewer::benchmarks::BM_TestPCGrid0_Args (benchmark::internal::Benchmark * b) static
Definition at line 154 of file PointCloudIO.cpp.
MinTime()
cloudViewer::benchmarks::MinTime (0. 1) -> Ranges({{1<< 0, 1<< 14}, {1<< 16, 1<< 22}})
Rand()
core::Tensor cloudViewer::benchmarks::Rand (const core::SizeVector & shape, size_t seed, const std::pair< core::Scalar, core::Scalar > & range, core::Dtype dtype, const core::Device & device)
Returns a Tensor with random values within the range range .
Definition at line 23 of file Rand.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, cloudViewer::core::Tensor::Empty(), cloudViewer::utility::EstimateMaxThreads(), cloudViewer::core::TensorIterator::GetPtr(), cloudViewer::core::ParallelFor(), and Utils::random().
Referenced by cloudViewer::core::BinaryEW(), and cloudViewer::core::UnaryEW().
Variable Documentation
testKDTreeLine0
TestKDTreeLine0 cloudViewer::benchmarks::testKDTreeLine0
Definition at line 61 of file KDTreeFlann.cpp.
Referenced by BM_TestKDTreeLine0().