ACloudViewer: cloudViewer::t::pipelines::slam Namespace Reference
cloudViewer::t::pipelines::slam Namespace Reference
Classes
class Frame
Frame is a container class storing an intrinsic matrix and several 2D tensors, from depth map, vertex map, to color map, in a customized way.
class Model
Functions
void pybind_slam (py::module &m)
Variables
static const std::unordered_map< std::string, std::string > map_shared_argument_docstrings
Function Documentation
pybind_slam()
void cloudViewer::t::pipelines::slam::pybind_slam (py::module & m)
Definition at line 57 of file slam.cpp.
References cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::t::pipelines::slam::Model::ExtractPointCloud(), cloudViewer::t::pipelines::slam::Model::ExtractTriangleMesh(), cloudViewer::core::Tensor::Eye(), cloudViewer::core::Float64, frame, cloudViewer::t::pipelines::slam::Model::frame_id_, cloudViewer::t::pipelines::slam::Model::frustum_block_coords_, cloudViewer::t::pipelines::slam::Model::GetCurrentFramePose(), cloudViewer::t::pipelines::slam::Frame::GetData(), cloudViewer::t::pipelines::slam::Frame::GetDataAsImage(), cloudViewer::t::pipelines::slam::Model::GetHashMap(), cloudViewer::t::pipelines::slam::Frame::GetHeight(), cloudViewer::t::pipelines::slam::Frame::GetWidth(), cloudViewer::t::pipelines::slam::Model::Integrate(), map_shared_argument_docstrings, cloudViewer::t::pipelines::odometry::PointToPlane, cloudViewer::t::pipelines::slam::Frame::SetData(), cloudViewer::t::pipelines::slam::Frame::SetDataFromImage(), cloudViewer::t::pipelines::slam::Model::SynthesizeModelFrame(), cloudViewer::t::pipelines::slam::Model::T_frame_to_world_, cloudViewer::t::pipelines::slam::Model::TrackFrameToModel(), cloudViewer::t::pipelines::slam::Model::UpdateFramePose(), and cloudViewer::t::pipelines::slam::Model::voxel_grid_.
Referenced by cloudViewer::t::pipelines::pybind_pipelines().
Variable Documentation
map_shared_argument_docstrings
const std::unordered_map<std::string, std::string> cloudViewer::t::pipelines::slam::map_shared_argument_docstrings static
Definition at line 18 of file slam.cpp.
Referenced by pybind_slam().