ACloudViewer: cloudViewer::reconstruction::options Namespace Reference
cloudViewer::reconstruction::options Namespace Reference
Functions
void pybind_image_reader_options (py::module &m)
void pybind_sift_extraction_options (py::module &m)
void pybind_sift_matching_options (py::module &m)
void pybind_exhaustive_matching_options (py::module &m)
void pybind_sequential_matching_options (py::module &m)
void pybind_vocabtree_matching_options (py::module &m)
void pybind_spatial_matching_options (py::module &m)
void pybind_transitive_matching_options (py::module &m)
void pybind_imagepairs_matching_options (py::module &m)
void pybind_featurepairs_matching_options (py::module &m)
void pybind_bundle_adjustment_options (py::module &m)
void pybind_incremental_triangulator_options (py::module &m)
void pybind_incremental_mapper_options (py::module &m)
void pybind_patch_match_options (py::module &m)
void pybind_stereo_fusion_options (py::module &m)
void pybind_poisson_meshing_options (py::module &m)
void pybind_delaunay_meshing_options (py::module &m)
void pybind_reconstruction_options (py::module &m)
Function Documentation
pybind_bundle_adjustment_options()
void cloudViewer::reconstruction::options::pybind_bundle_adjustment_options (py::module & m)
Definition at line 499 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_delaunay_meshing_options()
void cloudViewer::reconstruction::options::pybind_delaunay_meshing_options (py::module & m)
Definition at line 1211 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_exhaustive_matching_options()
void cloudViewer::reconstruction::options::pybind_exhaustive_matching_options (py::module & m)
Definition at line 299 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_featurepairs_matching_options()
void cloudViewer::reconstruction::options::pybind_featurepairs_matching_options (py::module & m)
Definition at line 480 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_image_reader_options()
void cloudViewer::reconstruction::options::pybind_image_reader_options (py::module & m)
Definition at line 19 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_imagepairs_matching_options()
void cloudViewer::reconstruction::options::pybind_imagepairs_matching_options (py::module & m)
Definition at line 462 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_incremental_mapper_options()
void cloudViewer::reconstruction::options::pybind_incremental_mapper_options (py::module & m)
Definition at line 723 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_incremental_triangulator_options()
void cloudViewer::reconstruction::options::pybind_incremental_triangulator_options (py::module & m)
Definition at line 598 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_patch_match_options()
void cloudViewer::reconstruction::options::pybind_patch_match_options (py::module & m)
Definition at line 1081 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_poisson_meshing_options()
void cloudViewer::reconstruction::options::pybind_poisson_meshing_options (py::module & m)
Definition at line 1168 of file reconstruction_options.cpp.
References color.
Referenced by pybind_reconstruction_options().
pybind_reconstruction_options()
void cloudViewer::reconstruction::options::pybind_reconstruction_options (py::module & m)
Definition at line 1273 of file reconstruction_options.cpp.
References pybind_bundle_adjustment_options(), pybind_delaunay_meshing_options(), pybind_exhaustive_matching_options(), pybind_featurepairs_matching_options(), pybind_image_reader_options(), pybind_imagepairs_matching_options(), pybind_incremental_mapper_options(), pybind_incremental_triangulator_options(), pybind_patch_match_options(), pybind_poisson_meshing_options(), pybind_sequential_matching_options(), pybind_sift_extraction_options(), pybind_sift_matching_options(), pybind_spatial_matching_options(), pybind_stereo_fusion_options(), pybind_transitive_matching_options(), and pybind_vocabtree_matching_options().
Referenced by cloudViewer::reconstruction::pybind_reconstruction().
pybind_sequential_matching_options()
void cloudViewer::reconstruction::options::pybind_sequential_matching_options (py::module & m)
Definition at line 313 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_sift_extraction_options()
void cloudViewer::reconstruction::options::pybind_sift_extraction_options (py::module & m)
Definition at line 109 of file reconstruction_options.cpp.
References L2.
Referenced by pybind_reconstruction_options().
pybind_sift_matching_options()
void cloudViewer::reconstruction::options::pybind_sift_matching_options (py::module & m)
Definition at line 227 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_spatial_matching_options()
void cloudViewer::reconstruction::options::pybind_spatial_matching_options (py::module & m)
Definition at line 416 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_stereo_fusion_options()
void cloudViewer::reconstruction::options::pybind_stereo_fusion_options (py::module & m)
Definition at line 1099 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_transitive_matching_options()
void cloudViewer::reconstruction::options::pybind_transitive_matching_options (py::module & m)
Definition at line 444 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().
pybind_vocabtree_matching_options()
void cloudViewer::reconstruction::options::pybind_vocabtree_matching_options (py::module & m)
Definition at line 374 of file reconstruction_options.cpp.
Referenced by pybind_reconstruction_options().