ACloudViewer: cloudViewer::io::rpc::messages Namespace Reference
cloudViewer::io::rpc::messages Namespace Reference
Classes
struct Array
struct MeshData
struct for storing MeshData, e.g., PointClouds, TriangleMesh, ..
struct SetMeshData
struct GetMeshData
struct for defining a "get_mesh_data" message, which requests mesh data.
struct CameraData
struct for storing camera data
struct SetCameraData
struct SetTime
struct SetActiveCamera
struct SetProperties
struct Request
struct Reply
struct Status
Functions
std::string EndiannessStr ()
template<class T >
std::string TypeStr ()
template<>
std::string TypeStr< float > ()
template<>
std::string TypeStr< double > ()
template<>
std::string TypeStr< int8_t > ()
template<>
std::string TypeStr< int16_t > ()
template<>
std::string TypeStr< int32_t > ()
template<>
std::string TypeStr< int64_t > ()
template<>
std::string TypeStr< uint8_t > ()
template<>
std::string TypeStr< uint16_t > ()
template<>
std::string TypeStr< uint32_t > ()
template<>
std::string TypeStr< uint64_t > ()
Function Documentation
EndiannessStr()
std::string cloudViewer::io::rpc::messages::EndiannessStr () inline
Definition at line 24 of file Messages.h.
Referenced by TypeStr< double >(), TypeStr< float >(), TypeStr< int16_t >(), TypeStr< int32_t >(), TypeStr< int64_t >(), TypeStr< uint16_t >(), TypeStr< uint32_t >(), and TypeStr< uint64_t >().
TypeStr()
template<class T > std::string cloudViewer::io::rpc::messages::TypeStr () inline
Template function for converting types to their string representation. E.g. TypeStr<float>() -> "<f4"
Definition at line 40 of file Messages.h.
TypeStr< double >()
template<> std::string cloudViewer::io::rpc::messages::TypeStr< double > () inline
Definition at line 48 of file Messages.h.
References EndiannessStr().
Referenced by cloudViewer::visualization::MessageProcessor::ProcessMessage().
TypeStr< float >()
template<> std::string cloudViewer::io::rpc::messages::TypeStr< float > () inline
Definition at line 44 of file Messages.h.
References EndiannessStr().
Referenced by cloudViewer::visualization::MessageProcessor::ProcessMessage().
TypeStr< int16_t >()
template<> std::string cloudViewer::io::rpc::messages::TypeStr< int16_t > () inline
Definition at line 56 of file Messages.h.
References EndiannessStr().
TypeStr< int32_t >()
template<> std::string cloudViewer::io::rpc::messages::TypeStr< int32_t > () inline
Definition at line 60 of file Messages.h.
References EndiannessStr().
Referenced by cloudViewer::io::rpc::messages::MeshData::CheckFaces().
TypeStr< int64_t >()
template<> std::string cloudViewer::io::rpc::messages::TypeStr< int64_t > () inline
Definition at line 64 of file Messages.h.
References EndiannessStr().
Referenced by cloudViewer::io::rpc::messages::MeshData::CheckFaces().
TypeStr< int8_t >()
template<> std::string cloudViewer::io::rpc::messages::TypeStr< int8_t > () inline
Definition at line 52 of file Messages.h.
TypeStr< uint16_t >()
template<> std::string cloudViewer::io::rpc::messages::TypeStr< uint16_t > () inline
Definition at line 72 of file Messages.h.
References EndiannessStr().
TypeStr< uint32_t >()
template<> std::string cloudViewer::io::rpc::messages::TypeStr< uint32_t > () inline
Definition at line 76 of file Messages.h.
References EndiannessStr().
TypeStr< uint64_t >()
template<> std::string cloudViewer::io::rpc::messages::TypeStr< uint64_t > () inline
Definition at line 80 of file Messages.h.
References EndiannessStr().
TypeStr< uint8_t >()
template<> std::string cloudViewer::io::rpc::messages::TypeStr< uint8_t > () inline
Definition at line 68 of file Messages.h.