ACloudViewer: cloudViewer::t::pipelines::kernel::odometry Namespace Reference
cloudViewer::t::pipelines::kernel::odometry Namespace Reference
Functions
void ComputeOdometryResultPointToPlane (const core::Tensor &source_vertex_map, const core::Tensor &target_vertex_map, const core::Tensor &target_normal_map, const core::Tensor &intrinsics, const core::Tensor &init_source_to_target, core::Tensor &delta, float &inlier_residual, int &inlier_count, const float depth_outlier_trunc, const float depth_huber_delta)
void ComputeOdometryResultIntensity (const core::Tensor &source_depth, const core::Tensor &target_depth, const core::Tensor &source_intensity, const core::Tensor &target_intensity, const core::Tensor &target_intensity_dx, const core::Tensor &target_intensity_dy, const core::Tensor &source_vertex_map, const core::Tensor &intrinsics, const core::Tensor &init_source_to_target, core::Tensor &delta, float &inlier_residual, int &inlier_count, const float depth_outlier_trunc, const float intensity_huber_delta)
void ComputeOdometryResultHybrid (const core::Tensor &source_depth, const core::Tensor &target_depth, const core::Tensor &source_intensity, const core::Tensor &target_intensity, const core::Tensor &target_depth_dx, const core::Tensor &target_depth_dy, const core::Tensor &target_intensity_dx, const core::Tensor &target_intensity_dy, const core::Tensor &source_vertex_map, const core::Tensor &intrinsics, const core::Tensor &init_source_to_target, core::Tensor &delta, float &inlier_residual, int &inlier_count, const float depth_outlier_trunc, const float depth_huber_delta, const float intensity_huber_delta)
void ComputeOdometryInformationMatrix (const core::Tensor &source_vertex_map, const core::Tensor &target_vertex_map, const core::Tensor &intrinsic, const core::Tensor &source_to_target, const float square_dist_thr, core::Tensor &information)
void ComputeOdometryInformationMatrixCPU (const core::Tensor &source_vertex_map, const core::Tensor &target_vertex_map, const core::Tensor &intrinsic, const core::Tensor &source_to_target, const float square_dist_thr, core::Tensor &information)
void ComputeOdometryResultIntensityCPU (const core::Tensor &source_depth, const core::Tensor &target_depth, const core::Tensor &source_intensity, const core::Tensor &target_intensity, const core::Tensor &target_intensity_dx, const core::Tensor &target_intensity_dy, const core::Tensor &source_vertex_map, const core::Tensor &intrinsics, const core::Tensor &init_source_to_target, core::Tensor &delta, float &inlier_residual, int &inlier_count, const float depth_outlier_trunc, const float intensity_huber_delta)
void ComputeOdometryResultHybridCPU (const core::Tensor &source_depth, const core::Tensor &target_depth, const core::Tensor &source_intensity, const core::Tensor &target_intensity, const core::Tensor &target_depth_dx, const core::Tensor &target_depth_dy, const core::Tensor &target_intensity_dx, const core::Tensor &target_intensity_dy, const core::Tensor &source_vertex_map, const core::Tensor &intrinsics, const core::Tensor &init_source_to_target, core::Tensor &delta, float &inlier_residual, int &inlier_count, const float depth_outlier_trunc, const float depth_huber_delta, const float intensity_huber_delta)
void ComputeOdometryResultPointToPlaneCPU (const core::Tensor &source_vertex_map, const core::Tensor &target_vertex_map, const core::Tensor &target_normal_map, const core::Tensor &intrinsics, const core::Tensor &init_source_to_target, core::Tensor &delta, float &inlier_residual, int &inlier_count, const float depth_outlier_trunc, const float depth_huber_delta)
CLOUDVIEWER_HOST_DEVICE float HuberDeriv (float r, float delta)
CLOUDVIEWER_HOST_DEVICE float HuberLoss (float r, float delta)
CLOUDVIEWER_HOST_DEVICE bool GetJacobianPointToPoint (int x, int y, const float square_dist_thr, const NDArrayIndexer &source_vertex_indexer, const NDArrayIndexer &target_vertex_indexer, const TransformIndexer &ti, float *J_x, float *J_y, float *J_z, float &rx, float &ry, float &rz)
CLOUDVIEWER_HOST_DEVICE bool GetJacobianPointToPlane (int x, int y, const float depth_outlier_trunc, const NDArrayIndexer &source_vertex_indexer, const NDArrayIndexer &target_vertex_indexer, const NDArrayIndexer &target_normal_indexer, const TransformIndexer &ti, float *J_ij, float &r)
CLOUDVIEWER_HOST_DEVICE bool GetJacobianIntensity (int x, int y, const float depth_outlier_trunc, const NDArrayIndexer &source_depth_indexer, const NDArrayIndexer &target_depth_indexer, const NDArrayIndexer &source_intensity_indexer, const NDArrayIndexer &target_intensity_indexer, const NDArrayIndexer &target_intensity_dx_indexer, const NDArrayIndexer &target_intensity_dy_indexer, const NDArrayIndexer &source_vertex_indexer, const TransformIndexer &ti, float *J_I, float &r_I)
CLOUDVIEWER_HOST_DEVICE bool GetJacobianHybrid (int x, int y, const float depth_outlier_trunc, const NDArrayIndexer &source_depth_indexer, const NDArrayIndexer &target_depth_indexer, const NDArrayIndexer &source_intensity_indexer, const NDArrayIndexer &target_intensity_indexer, const NDArrayIndexer &target_depth_dx_indexer, const NDArrayIndexer &target_depth_dy_indexer, const NDArrayIndexer &target_intensity_dx_indexer, const NDArrayIndexer &target_intensity_dy_indexer, const NDArrayIndexer &source_vertex_indexer, const TransformIndexer &ti, float *J_I, float *J_D, float &r_I, float &r_D)
Function Documentation
ComputeOdometryInformationMatrix()
void cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryInformationMatrix (const core::Tensor & source_vertex_map, const core::Tensor & target_vertex_map, const core::Tensor & intrinsic, const core::Tensor & source_to_target, const float square_dist_thr, core::Tensor & information)
Definition at line 195 of file RGBDOdometry.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, AssertTensorShape, ComputeOdometryInformationMatrixCPU(), cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Device::CPU, cloudViewer::core::Device::CUDA, CUDA_CALL, cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Device::GetType(), LogError, and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::t::pipelines::odometry::ComputeOdometryInformationMatrix().
ComputeOdometryInformationMatrixCPU()
void cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryInformationMatrixCPU (const core::Tensor & source_vertex_map, const core::Tensor & target_vertex_map, const core::Tensor & intrinsic, const core::Tensor & source_to_target, const float square_dist_thr, core::Tensor & information)
Definition at line 26 of file RGBDOdometryCPU.cpp.
References cloudViewer::core::Tensor::Empty(), cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), and result.
Referenced by ComputeOdometryInformationMatrix().
ComputeOdometryResultHybrid()
void cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultHybrid (const core::Tensor & source_depth, const core::Tensor & target_depth, const core::Tensor & source_intensity, const core::Tensor & target_intensity, const core::Tensor & target_depth_dx, const core::Tensor & target_depth_dy, const core::Tensor & target_intensity_dx, const core::Tensor & target_intensity_dy, const core::Tensor & source_vertex_map, const core::Tensor & intrinsics, const core::Tensor & init_source_to_target, core::Tensor & delta, float & inlier_residual, int & inlier_count, const float depth_outlier_trunc, const float depth_huber_delta, const float intensity_huber_delta)
Definition at line 126 of file RGBDOdometry.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, AssertTensorShape, ComputeOdometryResultHybridCPU(), cloudViewer::core::Tensor::Contiguous(), CUDA_CALL, cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Device::IsCUDA(), LogError, and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::t::pipelines::odometry::ComputeOdometryResultHybrid().
ComputeOdometryResultHybridCPU()
void cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultHybridCPU (const core::Tensor & source_depth, const core::Tensor & target_depth, const core::Tensor & source_intensity, const core::Tensor & target_intensity, const core::Tensor & target_depth_dx, const core::Tensor & target_depth_dy, const core::Tensor & target_intensity_dx, const core::Tensor & target_intensity_dy, const core::Tensor & source_vertex_map, const core::Tensor & intrinsics, const core::Tensor & init_source_to_target, core::Tensor & delta, float & inlier_residual, int & inlier_count, const float depth_outlier_trunc, const float depth_huber_delta, const float intensity_huber_delta)
Definition at line 207 of file RGBDOdometryCPU.cpp.
References cloudViewer::t::pipelines::kernel::DecodeAndSolve6x6(), cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDevice(), and result.
Referenced by ComputeOdometryResultHybrid().
ComputeOdometryResultIntensity()
void cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultIntensity (const core::Tensor & source_depth, const core::Tensor & target_depth, const core::Tensor & source_intensity, const core::Tensor & target_intensity, const core::Tensor & target_intensity_dx, const core::Tensor & target_intensity_dy, const core::Tensor & source_vertex_map, const core::Tensor & intrinsics, const core::Tensor & init_source_to_target, core::Tensor & delta, float & inlier_residual, int & inlier_count, const float depth_outlier_trunc, const float intensity_huber_delta)
Definition at line 66 of file RGBDOdometry.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, AssertTensorShape, ComputeOdometryResultIntensityCPU(), cloudViewer::core::Tensor::Contiguous(), CUDA_CALL, cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Device::IsCUDA(), LogError, and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::t::pipelines::odometry::ComputeOdometryResultIntensity().
ComputeOdometryResultIntensityCPU()
void cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultIntensityCPU (const core::Tensor & source_depth, const core::Tensor & target_depth, const core::Tensor & source_intensity, const core::Tensor & target_intensity, const core::Tensor & target_intensity_dx, const core::Tensor & target_intensity_dy, const core::Tensor & source_vertex_map, const core::Tensor & intrinsics, const core::Tensor & init_source_to_target, core::Tensor & delta, float & inlier_residual, int & inlier_count, const float depth_outlier_trunc, const float intensity_huber_delta)
Definition at line 110 of file RGBDOdometryCPU.cpp.
References cloudViewer::t::pipelines::kernel::DecodeAndSolve6x6(), cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDevice(), and result.
Referenced by ComputeOdometryResultIntensity().
ComputeOdometryResultPointToPlane()
void cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultPointToPlane (const core::Tensor & source_vertex_map, const core::Tensor & target_vertex_map, const core::Tensor & target_normal_map, const core::Tensor & intrinsics, const core::Tensor & init_source_to_target, core::Tensor & delta, float & inlier_residual, int & inlier_count, const float depth_outlier_trunc, const float depth_huber_delta)
Definition at line 19 of file RGBDOdometry.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, AssertTensorShape, ComputeOdometryResultPointToPlaneCPU(), cloudViewer::core::Tensor::Contiguous(), CUDA_CALL, cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Device::IsCUDA(), LogError, and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::t::pipelines::odometry::ComputeOdometryResultPointToPlane().
ComputeOdometryResultPointToPlaneCPU()
void cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultPointToPlaneCPU (const core::Tensor & source_vertex_map, const core::Tensor & target_vertex_map, const core::Tensor & target_normal_map, const core::Tensor & intrinsics, const core::Tensor & init_source_to_target, core::Tensor & delta, float & inlier_residual, int & inlier_count, const float depth_outlier_trunc, const float depth_huber_delta)
Definition at line 315 of file RGBDOdometryCPU.cpp.
References cloudViewer::t::pipelines::kernel::DecodeAndSolve6x6(), cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDevice(), and result.
Referenced by ComputeOdometryResultPointToPlane().
GetJacobianHybrid()
CLOUDVIEWER_HOST_DEVICE bool cloudViewer::t::pipelines::kernel::odometry::GetJacobianHybrid (int x, int y, const float depth_outlier_trunc, const NDArrayIndexer & source_depth_indexer, const NDArrayIndexer & target_depth_indexer, const NDArrayIndexer & source_intensity_indexer, const NDArrayIndexer & target_intensity_indexer, const NDArrayIndexer & target_depth_dx_indexer, const NDArrayIndexer & target_depth_dy_indexer, const NDArrayIndexer & target_intensity_dx_indexer, const NDArrayIndexer & target_intensity_dy_indexer, const NDArrayIndexer & source_vertex_indexer, const TransformIndexer & ti, float * J_I, float * J_D, float & r_I, float & r_D) inline
Definition at line 233 of file RGBDOdometryJacobianImpl.h.
References abs(), cloudViewer::t::geometry::kernel::TransformIndexer::GetFocalLength(), cloudViewer::t::geometry::kernel::TransformIndexer::Project(), and cloudViewer::t::geometry::kernel::TransformIndexer::RigidTransform().
GetJacobianIntensity()
CLOUDVIEWER_HOST_DEVICE bool cloudViewer::t::pipelines::kernel::odometry::GetJacobianIntensity (int x, int y, const float depth_outlier_trunc, const NDArrayIndexer & source_depth_indexer, const NDArrayIndexer & target_depth_indexer, const NDArrayIndexer & source_intensity_indexer, const NDArrayIndexer & target_intensity_indexer, const NDArrayIndexer & target_intensity_dx_indexer, const NDArrayIndexer & target_intensity_dy_indexer, const NDArrayIndexer & source_vertex_indexer, const TransformIndexer & ti, float * J_I, float & r_I) inline
Definition at line 164 of file RGBDOdometryJacobianImpl.h.
References abs(), cloudViewer::t::geometry::kernel::TransformIndexer::GetFocalLength(), cloudViewer::t::geometry::kernel::TransformIndexer::Project(), and cloudViewer::t::geometry::kernel::TransformIndexer::RigidTransform().
GetJacobianPointToPlane()
CLOUDVIEWER_HOST_DEVICE bool cloudViewer::t::pipelines::kernel::odometry::GetJacobianPointToPlane (int x, int y, const float depth_outlier_trunc, const NDArrayIndexer & source_vertex_indexer, const NDArrayIndexer & target_vertex_indexer, const NDArrayIndexer & target_normal_indexer, const TransformIndexer & ti, float * J_ij, float & r) inline
Definition at line 106 of file RGBDOdometryJacobianImpl.h.
References abs(), cloudViewer::t::geometry::kernel::TransformIndexer::Project(), and cloudViewer::t::geometry::kernel::TransformIndexer::RigidTransform().
GetJacobianPointToPoint()
CLOUDVIEWER_HOST_DEVICE bool cloudViewer::t::pipelines::kernel::odometry::GetJacobianPointToPoint (int x, int y, const float square_dist_thr, const NDArrayIndexer & source_vertex_indexer, const NDArrayIndexer & target_vertex_indexer, const TransformIndexer & ti, float * J_x, float * J_y, float * J_z, float & rx, float & ry, float & rz) inline
Definition at line 39 of file RGBDOdometryJacobianImpl.h.
References cloudViewer::t::geometry::kernel::TransformIndexer::Project(), and cloudViewer::t::geometry::kernel::TransformIndexer::RigidTransform().
HuberDeriv()
CLOUDVIEWER_HOST_DEVICE float cloudViewer::t::pipelines::kernel::odometry::HuberDeriv (float r, float delta) inline
Definition at line 29 of file RGBDOdometryJacobianImpl.h.
References abs(), and Sign().
HuberLoss()
CLOUDVIEWER_HOST_DEVICE float cloudViewer::t::pipelines::kernel::odometry::HuberLoss (float r, float delta) inline
Definition at line 34 of file RGBDOdometryJacobianImpl.h.
References abs().