ACloudViewer: cloudViewer::core Namespace Reference
cloudViewer::core Namespace Reference
Namespaces
cuda
eigen_converter
kernel
linalg
nns
shape_util
sy
tensor_check
tensor_init
Classes
class AdvancedIndexPreprocessor
This class is based on PyTorch's aten/src/ATen/native/Indexing.cpp.
class AdvancedIndexer
class Blob
class CUDAScopedDevice
When CUDA is not enabled, this is a dummy class.
class Device
class IsDevice
class Dtype
struct FunctionTraits
struct FunctionTraits< T ClassType::* >
struct FunctionTraits< ReturnType(ClassType::*)(Args...) const >
struct FunctionTraits< T & >
struct FunctionTraits< T * >
struct FunctionTraits< ReturnType(Args...)>
struct NullaryFunctionTraits
struct UnaryFunctionTraits
struct BinaryFunctionTraits
class CPUHashBackendBufferAccessor
class TBBHashBackend
class CUDAHashBackendBufferAccessor
class SlabHashBackend
class SlabHashBackendImpl
class Slab
class SlabNodeManagerImpl
class SlabNodeManager
struct iterator_t
struct Pair
class StdGPUAllocator
class StdGPUHashBackend
struct ValueExtractor
class DeviceHashBackend
class HashBackendBuffer
class HashMap
class HashSet
struct OffsetCalculator
struct TensorRef
A minimalistic class that reference a Tensor.
class TensorIterator
class Indexer
class IndexerIterator
class MemoryManager
class MemoryManagerDevice
Interface for all concrete memory manager classes.
class MemoryManagerCached
class MemoryManagerCPU
struct SizeOrder
struct PointerOrder
struct VirtualBlock
struct RealBlock
class MemoryCache
class Cacher
class MemoryManagerStatistic
class Scalar
class DynamicSizeVector
class SizeVector
class iterator_range
class SmallVectorBase
struct SmallVectorAlignmentAndSize
Figure out the offset of the first element.
class SmallVectorTemplateCommon
class SmallVectorTemplateBase
class SmallVectorTemplateBase< T, true >
class SmallVectorImpl
struct SmallVectorStorage
struct SmallVectorStorage< T, 0 >
class SmallVector
struct CalculateSmallVectorDefaultInlinedElements
class StdAllocator
class Open3DDLManagedTensor
CloudViewer DLPack Tensor manager.
class Tensor
class TensorKey
TensorKey is used to represent single index, slice or advanced indexing on a Tensor.
class TensorList
Typedefs
using buf_index_t = uint32_t
template<class T >
using SmallVectorSizeType = typename std::conditional< sizeof(T)< 4 &&sizeof(void *) >=8, uint64_t, uint32_t >::type
template<typename RangeType >
using ValueTypeFromRangeType = typename std::remove_const< typename std::remove_reference< decltype(*std::begin(std::declval< RangeType & >()))>::type >::type
Enumerations
enum class HashBackendType { Slab , StdGPU , TBB , Default }
enum class DtypePolicy { NONE , ALL_SAME , INPUT_SAME , INPUT_SAME_OUTPUT_BOOL }
Functions
uint32_t AtomicFetchAddRelaxed (uint32_t *address, uint32_t val)
uint64_t AtomicFetchAddRelaxed (uint64_t *address, uint64_t val)
static Device::DeviceType StringToDeviceType (const std::string &type_colon_id)
static int StringToDeviceId (const std::string &type_colon_id)
void CPUResetHeap (Tensor &heap)
std::shared_ptr< DeviceHashBackend > CreateCPUHashBackend (int64_t init_capacity, const Dtype &key_dtype, const SizeVector &key_element_shape, const std::vector< Dtype > &value_dtypes, const std::vector< SizeVector > &value_element_shapes, const Device &device, const HashBackendType &backend)
Non-templated factory.
template<typename Key , typename Hash , typename Eq >
__global__ void InsertKernelPass0 (SlabHashBackendImpl< Key, Hash, Eq > impl, const void *input_keys, buf_index_t *output_buf_indices, int heap_counter_prev, int64_t count)
Kernels.
template<typename Key , typename Hash , typename Eq >
__global__ void InsertKernelPass1 (SlabHashBackendImpl< Key, Hash, Eq > impl, const void *input_keys, buf_index_t *output_buf_indices, bool *output_masks, int64_t count)
template<typename Key , typename Hash , typename Eq , typename block_t >
__global__ void InsertKernelPass2 (SlabHashBackendImpl< Key, Hash, Eq > impl, const void *const *input_values_soa, buf_index_t *output_buf_indices, bool *output_masks, int64_t count, int64_t n_values)
template<typename Key , typename Hash , typename Eq >
__global__ void FindKernel (SlabHashBackendImpl< Key, Hash, Eq > impl, const void *input_keys, buf_index_t *output_buf_indices, bool *output_masks, int64_t count)
template<typename Key , typename Hash , typename Eq >
__global__ void EraseKernelPass0 (SlabHashBackendImpl< Key, Hash, Eq > impl, const void *input_keys, buf_index_t *output_buf_indices, bool *output_masks, int64_t count)
template<typename Key , typename Hash , typename Eq >
__global__ void EraseKernelPass1 (SlabHashBackendImpl< Key, Hash, Eq > impl, buf_index_t *output_buf_indices, bool *output_masks, int64_t count)
template<typename Key , typename Hash , typename Eq >
__global__ void GetActiveIndicesKernel (SlabHashBackendImpl< Key, Hash, Eq > impl, buf_index_t *output_buf_indices, uint32_t *output_count)
template<typename Key , typename Hash , typename Eq >
__global__ void CountElemsPerBucketKernel (SlabHashBackendImpl< Key, Hash, Eq > impl, int64_t *bucket_elem_counts)
__global__ void CountSlabsPerSuperblockKernel (SlabNodeManagerImpl impl, uint32_t *slabs_per_superblock)
template<typename First , typename Second >
CLOUDVIEWER_HOST_DEVICE Pair< First, Second > make_pair (const First &_first, const Second &_second)
template<typename Key , typename Hash , typename Eq >
__global__ void STDGPUFindKernel (InternalStdGPUHashBackend< Key, Hash, Eq > map, CUDAHashBackendBufferAccessor buffer_accessor, const Key *input_keys, buf_index_t *output_buf_indices, bool *output_masks, int64_t count)
template<typename Key , typename Hash , typename Eq >
__global__ void STDGPUEraseKernel (InternalStdGPUHashBackend< Key, Hash, Eq > map, CUDAHashBackendBufferAccessor buffer_accessor, const Key *input_keys, buf_index_t *output_buf_indices, bool *output_masks, int64_t count)
template<typename Key , typename Hash , typename Eq , typename block_t >
__global__ void STDGPUInsertKernel (InternalStdGPUHashBackend< Key, Hash, Eq > map, CUDAHashBackendBufferAccessor buffer_accessor, const Key *input_keys, const void *const *input_values_soa, buf_index_t *output_buf_indices, bool *output_masks, int64_t count, int64_t n_values)
std::shared_ptr< DeviceHashBackend > CreateDeviceHashBackend (int64_t init_capacity, const Dtype &key_dtype, const SizeVector &key_element_shape, const std::vector< Dtype > &value_dtypes, const std::vector< SizeVector > &value_element_shapes, const Device &device, const HashBackendType &backend)
std::shared_ptr< DeviceHashBackend > CreateCUDAHashBackend (int64_t init_capacity, const Dtype &key_dtype, const SizeVector &key_element_shape, const std::vector< Dtype > &value_dtypes, const std::vector< SizeVector > &value_element_shapes, const Device &device, const HashBackendType &backend)
void AddMM (const Tensor &A, const Tensor &B, Tensor &output, double alpha, double beta)
void AddMMCPU (void *A_data, void *B_data, void *C_data, int64_t m, int64_t k, int64_t n, double alpha, double beta, bool gemmTrA, bool gemmTrB, int lda, int ldb, int ldc, Dtype dtype)
void AddMMCUDA (void *A_data, void *B_data, void *C_data, int64_t m, int64_t k, int64_t n, double alpha, double beta, bool gemmTrA, bool gemmTrB, int lda, int ldb, int ldc, Dtype dtype, const Device &device)
void AddMMSYCL (void *A_data, void *B_data, void *C_data, int64_t m, int64_t k, int64_t n, double alpha, double beta, bool gemmTrA, bool gemmTrB, int lda, int ldb, int ldc, Dtype dtype, const Device &device)
template<typename scalar_t >
void gemm_cpu (CBLAS_LAYOUT layout, CBLAS_TRANSPOSE trans_A, CBLAS_TRANSPOSE trans_B, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT k, scalar_t alpha, const scalar_t *A_data, OPEN3D_CPU_LINALG_INT lda, const scalar_t *B_data, OPEN3D_CPU_LINALG_INT ldb, scalar_t beta, scalar_t *C_data, OPEN3D_CPU_LINALG_INT ldc)
template<>
void gemm_cpu< float > (CBLAS_LAYOUT layout, CBLAS_TRANSPOSE trans_A, CBLAS_TRANSPOSE trans_B, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT k, float alpha, const float *A_data, OPEN3D_CPU_LINALG_INT lda, const float *B_data, OPEN3D_CPU_LINALG_INT ldb, float beta, float *C_data, OPEN3D_CPU_LINALG_INT ldc)
template<>
void gemm_cpu< double > (CBLAS_LAYOUT layout, CBLAS_TRANSPOSE trans_A, CBLAS_TRANSPOSE trans_B, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT k, double alpha, const double *A_data, OPEN3D_CPU_LINALG_INT lda, const double *B_data, OPEN3D_CPU_LINALG_INT ldb, double beta, double *C_data, OPEN3D_CPU_LINALG_INT ldc)
double Det (const Tensor &A)
void Inverse (const Tensor &A, Tensor &output)
Computes A^{-1} with LU factorization, where A is a N x N square matrix.
void InverseCPU (void *A_data, void *ipiv_data, [[maybe_unused]] void *output_data, int64_t n, Dtype dtype, const Device &device)
void InverseCPU (void *A_data, void *ipiv_data, void *output_data, int64_t n, Dtype dtype, const Device &device)
void InverseCUDA (void *A_data, void *ipiv_data, void *output_data, int64_t n, Dtype dtype, const Device &device)
void InverseSYCL (void *A_data, void *ipiv_data, void *output_data, int64_t n, Dtype dtype, const Device &device)
template<typename scalar_t >
OPEN3D_CPU_LINALG_INT getrf_cpu (int layout, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, scalar_t *A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT *ipiv_data)
template<typename scalar_t >
OPEN3D_CPU_LINALG_INT getri_cpu (int layout, OPEN3D_CPU_LINALG_INT n, scalar_t *A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT *ipiv_data)
template<typename scalar_t >
OPEN3D_CPU_LINALG_INT gesv_cpu (int layout, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT m, scalar_t *A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT *ipiv_data, scalar_t *B_data, OPEN3D_CPU_LINALG_INT ldb)
template<typename scalar_t >
OPEN3D_CPU_LINALG_INT gels_cpu (int matrix_layout, char trans, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT nrhs, scalar_t *A_data, OPEN3D_CPU_LINALG_INT lda, scalar_t *B_data, OPEN3D_CPU_LINALG_INT ldb)
template<typename scalar_t >
OPEN3D_CPU_LINALG_INT gesvd_cpu (int matrix_layout, char jobu, char jobvt, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, scalar_t *A_data, OPEN3D_CPU_LINALG_INT lda, scalar_t *S_data, scalar_t *U_data, OPEN3D_CPU_LINALG_INT ldu, scalar_t *VT_data, OPEN3D_CPU_LINALG_INT ldvt, scalar_t *superb)
template<>
OPEN3D_CPU_LINALG_INT getrf_cpu< float > (int layout, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, float *A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT *ipiv_data)
template<>
OPEN3D_CPU_LINALG_INT getrf_cpu< double > (int layout, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, double *A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT *ipiv_data)
template<>
OPEN3D_CPU_LINALG_INT getri_cpu< float > (int layout, OPEN3D_CPU_LINALG_INT n, float *A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT *ipiv_data)
template<>
OPEN3D_CPU_LINALG_INT getri_cpu< double > (int layout, OPEN3D_CPU_LINALG_INT n, double *A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT *ipiv_data)
template<>
OPEN3D_CPU_LINALG_INT gesv_cpu< float > (int layout, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT m, float *A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT *ipiv_data, float *B_data, OPEN3D_CPU_LINALG_INT ldb)
template<>
OPEN3D_CPU_LINALG_INT gesv_cpu< double > (int layout, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT m, double *A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT *ipiv_data, double *B_data, OPEN3D_CPU_LINALG_INT ldb)
template<>
OPEN3D_CPU_LINALG_INT gels_cpu< float > (int layout, char trans, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT nrhs, float *A_data, OPEN3D_CPU_LINALG_INT lda, float *B_data, OPEN3D_CPU_LINALG_INT ldb)
template<>
OPEN3D_CPU_LINALG_INT gels_cpu< double > (int layout, char trans, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT nrhs, double *A_data, OPEN3D_CPU_LINALG_INT lda, double *B_data, OPEN3D_CPU_LINALG_INT ldb)
template<>
OPEN3D_CPU_LINALG_INT gesvd_cpu< float > (int layout, char jobu, char jobvt, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, float *A_data, OPEN3D_CPU_LINALG_INT lda, float *S_data, float *U_data, OPEN3D_CPU_LINALG_INT ldu, float *VT_data, OPEN3D_CPU_LINALG_INT ldvt, float *superb)
template<>
OPEN3D_CPU_LINALG_INT gesvd_cpu< double > (int layout, char jobu, char jobvt, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, double *A_data, OPEN3D_CPU_LINALG_INT lda, double *S_data, double *U_data, OPEN3D_CPU_LINALG_INT ldu, double *VT_data, OPEN3D_CPU_LINALG_INT ldvt, double *superb)
void LeastSquares (const Tensor &A, const Tensor &B, Tensor &X)
Solve AX = B with QR decomposition. A is a full-rank m x n matrix (m >= n).
void LeastSquaresCPU (void *A_data, void *B_data, int64_t m, int64_t n, int64_t k, Dtype dtype, const Device &device)
void LeastSquaresCUDA (void *A_data, void *B_data, int64_t m, int64_t n, int64_t k, Dtype dtype, const Device &device)
void LeastSquaresSYCL (void *A_data, void *B_data, int64_t m, int64_t n, int64_t k, Dtype dtype, const Device &device)
void OPEN3D_LAPACK_CHECK (OPEN3D_CPU_LINALG_INT info, const std::string &msg)
static Tensor GetColPermutation (const Tensor &ipiv, int number_of_indices, int number_of_rows)
static void OutputToPLU (const Tensor &output, Tensor &permutation, Tensor &lower, Tensor &upper, const Tensor &ipiv, const bool permute_l)
void LUIpiv (const Tensor &A, Tensor &ipiv, Tensor &output)
void LU (const Tensor &A, Tensor &permutation, Tensor &lower, Tensor &upper, const bool permute_l)
void LUCPU (void *A_data, void *ipiv_data, int64_t rows, int64_t cols, Dtype dtype, const Device &device)
void LUCUDA (void *A_data, void *ipiv_data, int64_t rows, int64_t cols, Dtype dtype, const Device &device)
void LUSYCL (void *A_data, void *ipiv_data, int64_t m, int64_t n, Dtype dtype, const Device &device)
void Matmul (const Tensor &A, const Tensor &B, Tensor &C)
Computes matrix multiplication C = AB.
void MatmulCPU (void *A_data, void *B_data, void *C_data, int64_t m, int64_t k, int64_t n, Dtype dtype)
void MatmulCUDA (void *A_data, void *B_data, void *C_data, int64_t m, int64_t k, int64_t n, Dtype dtype, const Device &device)
void MatmulSYCL (void *A_data, void *B_data, void *C_data, int64_t m, int64_t k, int64_t n, Dtype dtype, const Device &device)
void Solve (const Tensor &A, const Tensor &B, Tensor &X)
Solve AX = B with LU decomposition. A is a square matrix.
void SolveCPU (void *A_data, void *B_data, void *ipiv_data, int64_t n, int64_t k, Dtype dtype, const Device &device)
void SolveCUDA (void *A_data, void *B_data, void *ipiv_data, int64_t n, int64_t k, Dtype dtype, const Device &device)
void SolveSYCL (void *A_data, void *B_data, void *ipiv_data, int64_t n, int64_t k, Dtype dtype, const Device &device)
void SVD (const Tensor &A, Tensor &U, Tensor &S, Tensor &VT)
void SVDCPU (const void *A_data, void *U_data, void *S_data, void *VT_data, void *superb_data, int64_t m, int64_t n, Dtype dtype, const Device &device)
void SVDCUDA (const void *A_data, void *U_data, void *S_data, void *VT_data, void *superb_data, int64_t m, int64_t n, Dtype dtype, const Device &device)
void SVDSYCL (const void *A_data, void *U_data, void *S_data, void *VT_data, int64_t m, int64_t n, Dtype dtype, const Device &device)
static void CheckInput (const Tensor &A, const int diagonal)
void Triu (const Tensor &A, Tensor &output, const int diagonal)
void Tril (const Tensor &A, Tensor &output, const int diagonal)
void Triul (const Tensor &A, Tensor &upper, Tensor &lower, const int diagonal)
void TriuCPU (const Tensor &A, Tensor &output, const int diagonal)
void TrilCPU (const Tensor &A, Tensor &output, const int diagonal)
void TriulCPU (const Tensor &A, Tensor &upper, Tensor &lower, const int diagonal)
void TriuSYCL (const Tensor &A, Tensor &output, const int diagonal)
void TrilSYCL (const Tensor &A, Tensor &output, const int diagonal)
void TriulSYCL (const Tensor &A, Tensor &upper, Tensor &lower, const int diagonal)
template<typename func_t >
void ParallelForCPU_ (const Device &device, int64_t n, const func_t &func)
Run a function in parallel on CPU.
template<typename func_t >
void ParallelFor (const Device &device, int64_t n, const func_t &func)
template<typename vec_func_t , typename func_t >
void ParallelFor (const Device &device, int64_t n, const func_t &func, const vec_func_t &vec_func)
template<typename Functor , typename... FuncArgs>
void ParallelForSYCL (const Device &device, Indexer indexer, FuncArgs... func_args)
Run a function in parallel with SYCL.
template<typename Functor , typename... FuncArgs>
void ParallelForSYCL (const Device &device, int64_t num_workloads, FuncArgs... func_args)
Run a function in parallel with SYCL.
static void report_size_overflow (size_t MinSize, size_t MaxSize)
static void report_at_maximum_capacity (size_t MaxSize)
template<class Size_T >
static size_t getNewCapacity (size_t MinSize, size_t TSize, size_t OldCapacity)
void * safe_malloc (size_t Sz)
void * safe_realloc (void *Ptr, size_t Sz)
template<typename T , unsigned N>
size_t capacity_in_bytes (const SmallVector< T, N > &X)
template<unsigned Size, typename R >
SmallVector< ValueTypeFromRangeType< R >, Size > to_vector (R &&Range)
template<typename R >
SmallVector< ValueTypeFromRangeType< R >, CalculateSmallVectorDefaultInlinedElements< ValueTypeFromRangeType< R > >::value > to_vector (R &&Range)
static DLDataTypeCode DtypeToDLDataTypeCode (const Dtype &dtype)
static Dtype DLDataTypeToDtype (const DLDataType &dltype)
template<typename T >
Tensor operator+ (T scalar_lhs, const Tensor &rhs)
template<typename T >
Tensor operator- (T scalar_lhs, const Tensor &rhs)
template<typename T >
Tensor operator* (T scalar_lhs, const Tensor &rhs)
template<typename T >
Tensor operator/ (T scalar_lhs, const Tensor &rhs)
void AssertNotSYCL (const Tensor &tensor)
static Tensor ConcatenateImpl (const std::vector< Tensor > &tensors, const int64_t axis)
Tensor Concatenate (const std::vector< Tensor > &tensors, const utility::optional< int64_t > &axis=0)
Concatenates the list of tensors in their order, along the given axis into a new tensor. All the tensors must have same data-type, device, and number of dimensions. All dimensions must be the same, except the dimension along the axis the tensors are to be concatenated. Using Concatenate for a single tensor, the tensor is split along its first dimension (length), and concatenated along the axis.
Tensor Append (const Tensor &self, const Tensor &other, const utility::optional< int64_t > &axis=utility::nullopt)
Appends the two tensors, along the given axis into a new tensor. Both the tensors must have same data-type, device, and number of dimensions. All dimensions must be the same, except the dimension along the axis the tensors are to be appended.
Tensor Maximum (const Tensor &input, const Tensor &other)
Computes the element-wise maximum of input and other. The tensors must have same data type and device.
Tensor Minimum (const Tensor &input, const Tensor &other)
Computes the element-wise minimum of input and other. The tensors must have same data type and device.
static void AssertIsResizable (const TensorList &tensorlist, const std::string &func_name)
Asserts that the tensor list is resizable.
Variables
const Dtype Undefined = Dtype::Undefined
const Dtype Float32 = Dtype::Float32
const Dtype Float64 = Dtype::Float64
const Dtype Int8 = Dtype::Int8
const Dtype Int16 = Dtype::Int16
const Dtype Int32 = Dtype::Int32
const Dtype Int64 = Dtype::Int64
const Dtype UInt8 = Dtype::UInt8
const Dtype UInt16 = Dtype::UInt16
const Dtype UInt32 = Dtype::UInt32
const Dtype UInt64 = Dtype::UInt64
const Dtype Bool = Dtype::Bool
static constexpr uint32_t kWarpSize = 32
static constexpr uint32_t kSuperBlocks = 32
static constexpr uint32_t kBlocksPerSuperBlock = 4
static constexpr uint32_t kBlocksPerSuperBlockInBits = 2
static constexpr uint32_t kSlabsPerBlock = 1024
static constexpr uint32_t kMaxKeyByteSize = 32
static constexpr uint32_t kThreadsPerBlock = 128
static constexpr uint32_t kUIntsPerBlock = kSlabsPerBlock * kWarpSize
static constexpr uint32_t kBitmapsPerSuperBlock
static constexpr uint32_t kUIntsPerSuperBlock
static constexpr uint32_t kSuperBlockMaskBits = 27
static constexpr uint32_t kBlockMaskBits = 10
static constexpr uint32_t kSlabMaskBits = 5
static constexpr uint32_t kSyncLanesMask = 0xFFFFFFFF
static constexpr uint32_t kNodePtrLanesMask = 0x7FFFFFFF
static constexpr uint32_t kNextSlabPtrLaneId = 31
static constexpr uint32_t kHeadSlabAddr = 0xFFFFFFFE
static constexpr uint32_t kEmptySlabAddr = 0xFFFFFFFF
static constexpr uint32_t kEmptyNodeAddr = 0xFFFFFFFF
static constexpr uint32_t kNullAddr = 0xFFFFFFFF
static constexpr uint32_t kNotFoundFlag = 0xFFFFFFFF
static constexpr int64_t MAX_DIMS = 5
static constexpr int64_t MAX_INPUTS = 5
static constexpr int64_t MAX_OUTPUTS = 2
constexpr utility::nullopt_t None {utility::nullopt_t::init()}
Typedef Documentation
buf_index_t
using cloudViewer::core::buf_index_t = typedef uint32_t
Definition at line 44 of file HashBackendBuffer.h.
SmallVectorSizeType
template<class T > using cloudViewer::core::SmallVectorSizeType = typedef typename std::conditional<sizeof(T) < 4 && sizeof(void *) >= 8, uint64_t, uint32_t>::type
Definition at line 136 of file SmallVector.h.
ValueTypeFromRangeType
template<typename RangeType > using cloudViewer::core::ValueTypeFromRangeType = typedef typename std::remove_const< typename std::remove_reference<decltype(*std::begin(std::declval<RangeType &>()))>::type>::type
Definition at line 1344 of file SmallVector.h.
Enumeration Type Documentation
DtypePolicy
enum cloudViewer::core::DtypePolicy strong
Enumerator
NONE
ALL_SAME
INPUT_SAME
INPUT_SAME_OUTPUT_BOOL
Definition at line 200 of file Indexer.h.
HashBackendType
enum cloudViewer::core::HashBackendType strong
Enumerator
Slab
StdGPU
TBB
Default
Definition at line 21 of file HashMap.h.
Function Documentation
AddMM()
void cloudViewer::core::AddMM (const Tensor & A, const Tensor & B, Tensor & C, double alpha, double beta)
Computes matrix multiplication C = alpha * A @ B + beta * C. If matrix A is a (n x m) tensor, and B is a (m x p) tensor, C should have a shape (n x p). alpha and beta are scaling factors on matrix-matrix multiplication and the added matrix input respectively.
Definition at line 17 of file AddMM.cpp.
References AddMMCPU(), AddMMCUDA(), AddMMSYCL(), AssertTensorDevice, AssertTensorDtype, cloudViewer::core::Tensor::Contiguous(), Float32, Float64, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::GetStride(), cloudViewer::core::Tensor::IsContiguous(), cloudViewer::core::Device::IsCUDA(), cloudViewer::core::Device::IsSYCL(), LogError, cloudViewer::core::SmallVectorBase< Size_T >::size(), cloudViewer::core::Tensor::T(), cloudViewer::core::Tensor::To(), and cloudViewer::core::Dtype::ToString().
AddMMCPU()
void cloudViewer::core::AddMMCPU (void * A_data, void * B_data, void * C_data, int64_t m, int64_t k, int64_t n, double alpha, double beta, bool gemmTrA, bool gemmTrB, int lda, int ldb, int ldc, Dtype dtype)
Definition at line 17 of file AddMMCPU.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, and gemm_cpu().
Referenced by AddMM().
AddMMCUDA()
void cloudViewer::core::AddMMCUDA (void * A_data, void * B_data, void * C_data, int64_t m, int64_t k, int64_t n, double alpha, double beta, bool gemmTrA, bool gemmTrB, int lda, int ldb, int ldc, Dtype dtype, const Device & device)
Definition at line 17 of file AddMMCUDA.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, and Runtime::GetInstance().
Referenced by AddMM().
AddMMSYCL()
void cloudViewer::core::AddMMSYCL (void * A_data, void * B_data, void * C_data, int64_t m, int64_t k, int64_t n, double alpha, double beta, bool gemmTrA, bool gemmTrB, int lda, int ldb, int ldc, Dtype dtype, const Device & device)
Definition at line 20 of file AddMMSYCL.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), and cloudViewer::core::sy::SYCLContext::GetInstance().
Referenced by AddMM().
Append()
Tensor cloudViewer::core::Append (const Tensor & self, const Tensor & other, const utility::optional< int64_t > & axis = utility::nullopt)
Appends the two tensors, along the given axis into a new tensor. Both the tensors must have same data-type, device, and number of dimensions. All dimensions must be the same, except the dimension along the axis the tensors are to be appended.
This is the same as NumPy's semantics:
https://numpy.org/doc/stable/reference/generated/numpy.append.html
Example:
Tensor a = Tensor::Init<int64_t>({{0, 1}, {2, 3}});
Tensor b = Tensor::Init<int64_t>({{4, 5}});
Tensor t1 = core::Append(a, b, 0);
// t1:
//  [[0 1],
//   [2 3],
//   [4 5]]
//  Tensor[shape={3, 2}, stride={2, 1}, Int64, CPU:0, 0x55555abc6b00]
Tensor t2 = core::Append(a, b);
// t2:
//  [0 1 2 3 4 5]
//  Tensor[shape={6}, stride={1}, Int64, CPU:0, 0x55555abc6b70]
Parameters
self Values are appended to a copy of this tensor.
other Values of this tensor is appended to the self.
axis [optional] The axis along which values are appended. If axis is not given, both tensors are flattened before use.
Returns
A copy of tensor with values appended to axis. Note that append does not occur in-place: a new array is allocated and filled. If axis is None, out is a flattened tensor.
Definition at line 118 of file TensorFunction.cpp.
References Concatenate().
Referenced by cloudViewer::core::Tensor::Append(), cloudViewer::t::pipelines::registration::CorrespondencesFromFeatures(), and QuaZIODevice::open().
AssertIsResizable()
static void cloudViewer::core::AssertIsResizable (const TensorList & tensorlist, const std::string & func_name) static
Asserts that the tensor list is resizable.
Definition at line 18 of file TensorList.cpp.
References cloudViewer::core::TensorList::IsResizable(), and LogError.
Referenced by cloudViewer::core::TensorList::Clear(), cloudViewer::core::TensorList::Extend(), cloudViewer::core::TensorList::PushBack(), and cloudViewer::core::TensorList::Resize().
AssertNotSYCL()
void cloudViewer::core::AssertNotSYCL (const Tensor & tensor) inline
Definition at line 1429 of file Tensor.h.
References cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Device::IsSYCL(), and LogError.
Referenced by cloudViewer::core::nns::NearestNeighborSearch::NearestNeighborSearch().
AtomicFetchAddRelaxed() [1/2]
uint32_t cloudViewer::core::AtomicFetchAddRelaxed (uint32_t * address, uint32_t val) inline
Adds val to the value stored at address and returns the previous stored value as an atomic operation. This function does not impose any ordering on concurrent memory accesses.
Warning
This function will treat all values as signed integers on Windows!
Definition at line 25 of file Atomic.h.
AtomicFetchAddRelaxed() [2/2]
uint64_t cloudViewer::core::AtomicFetchAddRelaxed (uint64_t * address, uint64_t val) inline
Adds val to the value stored at address and returns the previous stored value as an atomic operation. This function does not impose any ordering on concurrent memory accesses.
Warning
This function will treat all values as signed integers on Windows!
Definition at line 42 of file Atomic.h.
capacity_in_bytes()
template<typename T , unsigned N> size_t cloudViewer::core::capacity_in_bytes (const SmallVector< T, N > & X) inline
Definition at line 1339 of file SmallVector.h.
References X.
CheckInput()
static void cloudViewer::core::CheckInput (const Tensor & A, const int diagonal) static
Definition at line 17 of file Tri.cpp.
References cloudViewer::core::Tensor::GetShape(), LogError, cloudViewer::core::SmallVectorBase< Size_T >::size(), and cloudViewer::core::SizeVector::ToString().
Referenced by Tril(), Triu(), and Triul().
Concatenate()
Tensor cloudViewer::core::Concatenate (const std::vector< Tensor > & tensors, const utility::optional< int64_t > & axis = 0)
Concatenates the list of tensors in their order, along the given axis into a new tensor. All the tensors must have same data-type, device, and number of dimensions. All dimensions must be the same, except the dimension along the axis the tensors are to be concatenated. Using Concatenate for a single tensor, the tensor is split along its first dimension (length), and concatenated along the axis.
This is the same as NumPy's semantics:
https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html
Example:
Tensor a = Tensor::Init<int64_t>({{0, 1}, {2, 3}});
Tensor b = Tensor::Init<int64_t>({{4, 5}});
Tensor c = Tensor::Init<int64_t>({{6, 7}});
Tensor output = core::Concatenate({a, b, c}, 0);
// output:
//  [[0 1],
//   [2 3],
//   [4 5],
//   [6 7]]
//  Tensor[shape={4, 2}, stride={2, 1}, Int64, CPU:0, 0x55555abc6b00]
a = core::Tensor::Init<float>(
        {{{0, 1}, {2, 3}}, {{4, 5}, {6, 7}}, {{8, 9}, {10, 11}}}, device);
output = core::Concatenate({a}, 1);
//  output:
//  [[0, 1, 4, 5, 8, 9],
//   [2, 3, 6, 7, 10, 11]]
//  Tensor[shape={2, 6}, stride={6, 1}, Int64, CPU:0, 0x55555abc6b00]
Parameters
tensors Vector of tensors to be concatenated. If only one tensor is present, the tensor is split along its first dimension (length), and concatenated along the axis.
axis [optional] The axis along which values are concatenated. [Default axis is 0].
Returns
A new tensor with the values of list of tensors concatenated in order, along the given axis.
Definition at line 79 of file TensorFunction.cpp.
References ConcatenateImpl(), cloudViewer::utility::optional< T >::has_value(), LogError, cloudViewer::core::Tensor::Reshape(), and cloudViewer::utility::optional< T >::value().
Referenced by Append(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetBoxPoints(), and cloudViewer::t::io::ReadTriangleMeshUsingASSIMP().
ConcatenateImpl()
static Tensor cloudViewer::core::ConcatenateImpl (const std::vector< Tensor > & tensors, const int64_t axis) static
Definition at line 15 of file TensorFunction.cpp.
References AssertTensorDevice, AssertTensorDtype, LogError, cloudViewer::core::Tensor::NumDims(), cloudViewer::core::SmallVectorTemplateBase< T, bool >::push_back(), cloudViewer::core::Tensor::SetItem(), cloudViewer::core::TensorKey::Slice(), and cloudViewer::core::shape_util::WrapDim().
Referenced by Concatenate().
CountElemsPerBucketKernel()
template<typename Key , typename Hash , typename Eq > __global__ void cloudViewer::core::CountElemsPerBucketKernel (SlabHashBackendImpl< Key, Hash, Eq > impl, int64_t * bucket_elem_counts)
Definition at line 687 of file SlabHashBackendImpl.h.
References cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::bucket_count_, count, cloudViewer::core::SlabNodeManagerImpl::Init(), kEmptyNodeAddr, kEmptySlabAddr, kNextSlabPtrLaneId, kNodePtrLanesMask, kSyncLanesMask, kWarpSize, cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::node_mgr_impl_, cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::SlabEntryPtrFromHead(), and cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::SlabEntryPtrFromNodes().
Referenced by cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::BucketSizes().
CountSlabsPerSuperblockKernel()
__global__ void cloudViewer::core::CountSlabsPerSuperblockKernel (SlabNodeManagerImpl impl, uint32_t * slabs_per_superblock)
Referenced by cloudViewer::core::SlabNodeManager::CountSlabsPerSuperblock().
CPUResetHeap()
void cloudViewer::core::CPUResetHeap (Tensor & heap)
Definition at line 14 of file CPUHashBackendBuffer.cpp.
References cloudViewer::core::Tensor::GetDataPtr(), and cloudViewer::core::Tensor::GetLength().
Referenced by cloudViewer::core::HashBackendBuffer::ResetHeap().
CreateCPUHashBackend()
std::shared_ptr< DeviceHashBackend > cloudViewer::core::CreateCPUHashBackend (int64_t init_capacity, const Dtype & key_dtype, const SizeVector & key_element_shape, const std::vector< Dtype > & value_dtypes, const std::vector< SizeVector > & value_element_shapes, const Device & device, const HashBackendType & backend)
Non-templated factory.
Definition at line 16 of file CreateCPUHashBackend.cpp.
References cloudViewer::core::Dtype::ByteSize(), Default, DISPATCH_DTYPE_AND_DIM_TO_TEMPLATE, LogError, cloudViewer::core::SizeVector::NumElements(), and TBB.
Referenced by CreateDeviceHashBackend().
CreateCUDAHashBackend()
std::shared_ptr<DeviceHashBackend> cloudViewer::core::CreateCUDAHashBackend (int64_t init_capacity, const Dtype & key_dtype, const SizeVector & key_element_shape, const std::vector< Dtype > & value_dtypes, const std::vector< SizeVector > & value_element_shapes, const Device & device, const HashBackendType & backend)
Referenced by CreateDeviceHashBackend().
CreateDeviceHashBackend()
std::shared_ptr< DeviceHashBackend > cloudViewer::core::CreateDeviceHashBackend (int64_t init_capacity, const Dtype & key_dtype, const SizeVector & key_element_shape, const std::vector< Dtype > & value_dtypes, const std::vector< SizeVector > & value_element_shapes, const Device & device, const HashBackendType & backend)
Factory functions:
Default constructor switch is in DeviceHashBackend.cpp
Default CPU constructor is in CPU/CreateCPUHashBackend.cpp
Default CUDA constructor is in CUDA/CreateCUDAHashBackend.cu
Definition at line 18 of file DeviceHashBackend.cpp.
References CreateCPUHashBackend(), CreateCUDAHashBackend(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Device::IsCUDA(), and LogError.
Referenced by cloudViewer::core::HashMap::Init().
Det()
double cloudViewer::core::Det (const Tensor & A)
Definition at line 16 of file Det.cpp.
References AssertTensorDtypes, cloudViewer::core::linalg::kernel::det2x2(), cloudViewer::core::linalg::kernel::det3x3(), DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, Float32, Float64, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), LUIpiv(), and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::core::Tensor::Det().
DLDataTypeToDtype()
static Dtype cloudViewer::core::DLDataTypeToDtype (const DLDataType & dltype) static
Definition at line 57 of file Tensor.cpp.
References DLDataType::bits, DLDataType::code, Float32, Float64, Int16, Int32, Int64, Int8, kDLFloat, kDLInt, kDLUInt, DLDataType::lanes, LogError, UInt16, UInt32, UInt64, UInt8, and Undefined.
Referenced by cloudViewer::core::Tensor::FromDLPack().
DtypeToDLDataTypeCode()
static DLDataTypeCode cloudViewer::core::DtypeToDLDataTypeCode (const Dtype & dtype) static
Definition at line 42 of file Tensor.cpp.
References Float32, Float64, Int16, Int32, Int64, Int8, kDLFloat, kDLInt, kDLUInt, LogError, UInt16, UInt32, UInt64, and UInt8.
EraseKernelPass0()
template<typename Key , typename Hash , typename Eq > __global__ void cloudViewer::core::EraseKernelPass0 (SlabHashBackendImpl< Key, Hash, Eq > impl, const void * input_keys, buf_index_t * output_buf_indices, bool * output_masks, int64_t count)
Definition at line 601 of file SlabHashBackendImpl.h.
References cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::ComputeBucket(), count, cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Erase(), cloudViewer::core::SlabNodeManagerImpl::Init(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::node_mgr_impl_, and result.
Referenced by cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::Erase().
EraseKernelPass1()
template<typename Key , typename Hash , typename Eq > __global__ void cloudViewer::core::EraseKernelPass1 (SlabHashBackendImpl< Key, Hash, Eq > impl, buf_index_t * output_buf_indices, bool * output_masks, int64_t count)
Definition at line 636 of file SlabHashBackendImpl.h.
References cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::buffer_accessor_, count, and cloudViewer::core::CUDAHashBackendBufferAccessor::DeviceFree().
Referenced by cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::Erase().
FindKernel()
template<typename Key , typename Hash , typename Eq > __global__ void cloudViewer::core::FindKernel (SlabHashBackendImpl< Key, Hash, Eq > impl, const void * input_keys, buf_index_t * output_buf_indices, bool * output_masks, int64_t count)
Definition at line 562 of file SlabHashBackendImpl.h.
References cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::ComputeBucket(), count, cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Find(), cloudViewer::core::SlabNodeManagerImpl::Init(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::node_mgr_impl_, and result.
Referenced by cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::Find().
gels_cpu()
template<typename scalar_t > OPEN3D_CPU_LINALG_INT cloudViewer::core::gels_cpu (int matrix_layout, char trans, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT nrhs, scalar_t * A_data, OPEN3D_CPU_LINALG_INT lda, scalar_t * B_data, OPEN3D_CPU_LINALG_INT ldb) inline
Definition at line 52 of file LapackWrapper.h.
References LogError.
gels_cpu< double >()
template<> OPEN3D_CPU_LINALG_INT cloudViewer::core::gels_cpu< double > (int layout, char trans, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT nrhs, double * A_data, OPEN3D_CPU_LINALG_INT lda, double * B_data, OPEN3D_CPU_LINALG_INT ldb) inline
Definition at line 163 of file LapackWrapper.h.
gels_cpu< float >()
template<> OPEN3D_CPU_LINALG_INT cloudViewer::core::gels_cpu< float > (int layout, char trans, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT nrhs, float * A_data, OPEN3D_CPU_LINALG_INT lda, float * B_data, OPEN3D_CPU_LINALG_INT ldb) inline
Definition at line 150 of file LapackWrapper.h.
gemm_cpu()
template<typename scalar_t > void cloudViewer::core::gemm_cpu (CBLAS_LAYOUT layout, CBLAS_TRANSPOSE trans_A, CBLAS_TRANSPOSE trans_B, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT k, scalar_t alpha, const scalar_t * A_data, OPEN3D_CPU_LINALG_INT lda, const scalar_t * B_data, OPEN3D_CPU_LINALG_INT ldb, scalar_t beta, scalar_t * C_data, OPEN3D_CPU_LINALG_INT ldc) inline
Definition at line 19 of file BlasWrapper.h.
References LogError.
Referenced by AddMMCPU().
gemm_cpu< double >()
template<> void cloudViewer::core::gemm_cpu< double > (CBLAS_LAYOUT layout, CBLAS_TRANSPOSE trans_A, CBLAS_TRANSPOSE trans_B, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT k, double alpha, const double * A_data, OPEN3D_CPU_LINALG_INT lda, const double * B_data, OPEN3D_CPU_LINALG_INT ldb, double beta, double * C_data, OPEN3D_CPU_LINALG_INT ldc) inline
Definition at line 56 of file BlasWrapper.h.
gemm_cpu< float >()
template<> void cloudViewer::core::gemm_cpu< float > (CBLAS_LAYOUT layout, CBLAS_TRANSPOSE trans_A, CBLAS_TRANSPOSE trans_B, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT k, float alpha, const float * A_data, OPEN3D_CPU_LINALG_INT lda, const float * B_data, OPEN3D_CPU_LINALG_INT ldb, float beta, float * C_data, OPEN3D_CPU_LINALG_INT ldc) inline
Definition at line 37 of file BlasWrapper.h.
gesv_cpu()
template<typename scalar_t > OPEN3D_CPU_LINALG_INT cloudViewer::core::gesv_cpu (int layout, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT m, scalar_t * A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT * ipiv_data, scalar_t * B_data, OPEN3D_CPU_LINALG_INT ldb) inline
Definition at line 39 of file LapackWrapper.h.
References LogError.
gesv_cpu< double >()
template<> OPEN3D_CPU_LINALG_INT cloudViewer::core::gesv_cpu< double > (int layout, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT m, double * A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT * ipiv_data, double * B_data, OPEN3D_CPU_LINALG_INT ldb) inline
Definition at line 138 of file LapackWrapper.h.
gesv_cpu< float >()
template<> OPEN3D_CPU_LINALG_INT cloudViewer::core::gesv_cpu< float > (int layout, OPEN3D_CPU_LINALG_INT n, OPEN3D_CPU_LINALG_INT m, float * A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT * ipiv_data, float * B_data, OPEN3D_CPU_LINALG_INT ldb) inline
Definition at line 126 of file LapackWrapper.h.
gesvd_cpu()
template<typename scalar_t > OPEN3D_CPU_LINALG_INT cloudViewer::core::gesvd_cpu (int matrix_layout, char jobu, char jobvt, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, scalar_t * A_data, OPEN3D_CPU_LINALG_INT lda, scalar_t * S_data, scalar_t * U_data, OPEN3D_CPU_LINALG_INT ldu, scalar_t * VT_data, OPEN3D_CPU_LINALG_INT ldvt, scalar_t * superb) inline
Definition at line 66 of file LapackWrapper.h.
References LogError.
gesvd_cpu< double >()
template<> OPEN3D_CPU_LINALG_INT cloudViewer::core::gesvd_cpu< double > (int layout, char jobu, char jobvt, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, double * A_data, OPEN3D_CPU_LINALG_INT lda, double * S_data, double * U_data, OPEN3D_CPU_LINALG_INT ldu, double * VT_data, OPEN3D_CPU_LINALG_INT ldvt, double * superb) inline
Definition at line 194 of file LapackWrapper.h.
gesvd_cpu< float >()
template<> OPEN3D_CPU_LINALG_INT cloudViewer::core::gesvd_cpu< float > (int layout, char jobu, char jobvt, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, float * A_data, OPEN3D_CPU_LINALG_INT lda, float * S_data, float * U_data, OPEN3D_CPU_LINALG_INT ldu, float * VT_data, OPEN3D_CPU_LINALG_INT ldvt, float * superb) inline
Definition at line 176 of file LapackWrapper.h.
GetActiveIndicesKernel()
template<typename Key , typename Hash , typename Eq > __global__ void cloudViewer::core::GetActiveIndicesKernel (SlabHashBackendImpl< Key, Hash, Eq > impl, buf_index_t * output_buf_indices, uint32_t * output_count)
Definition at line 647 of file SlabHashBackendImpl.h.
References cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::bucket_count_, cloudViewer::core::SlabNodeManagerImpl::Init(), kEmptyNodeAddr, kEmptySlabAddr, kNextSlabPtrLaneId, kNodePtrLanesMask, kSyncLanesMask, kWarpSize, cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::node_mgr_impl_, cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::SlabEntryPtrFromHead(), and cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::SlabEntryPtrFromNodes().
Referenced by cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::GetActiveIndices().
GetColPermutation()
static Tensor cloudViewer::core::GetColPermutation (const Tensor & ipiv, int number_of_indices, int number_of_rows) static
Definition at line 19 of file LU.cpp.
References cloudViewer::core::Tensor::Arange(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), Int32, Int64, and cloudViewer::core::Tensor::To().
Referenced by OutputToPLU().
getNewCapacity()
template<class Size_T > static size_t cloudViewer::core::getNewCapacity (size_t MinSize, size_t TSize, size_t OldCapacity) static
Definition at line 104 of file SmallVector.cpp.
References max(), and report_size_overflow().
getrf_cpu()
template<typename scalar_t > OPEN3D_CPU_LINALG_INT cloudViewer::core::getrf_cpu (int layout, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, scalar_t * A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT * ipiv_data) inline
Definition at line 18 of file LapackWrapper.h.
References LogError.
getrf_cpu< double >()
template<> OPEN3D_CPU_LINALG_INT cloudViewer::core::getrf_cpu< double > (int layout, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, double * A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT * ipiv_data) inline
Definition at line 95 of file LapackWrapper.h.
getrf_cpu< float >()
template<> OPEN3D_CPU_LINALG_INT cloudViewer::core::getrf_cpu< float > (int layout, OPEN3D_CPU_LINALG_INT m, OPEN3D_CPU_LINALG_INT n, float * A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT * ipiv_data) inline
Definition at line 84 of file LapackWrapper.h.
getri_cpu()
template<typename scalar_t > OPEN3D_CPU_LINALG_INT cloudViewer::core::getri_cpu (int layout, OPEN3D_CPU_LINALG_INT n, scalar_t * A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT * ipiv_data) inline
Definition at line 29 of file LapackWrapper.h.
References LogError.
getri_cpu< double >()
template<> OPEN3D_CPU_LINALG_INT cloudViewer::core::getri_cpu< double > (int layout, OPEN3D_CPU_LINALG_INT n, double * A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT * ipiv_data) inline
Definition at line 116 of file LapackWrapper.h.
getri_cpu< float >()
template<> OPEN3D_CPU_LINALG_INT cloudViewer::core::getri_cpu< float > (int layout, OPEN3D_CPU_LINALG_INT n, float * A_data, OPEN3D_CPU_LINALG_INT lda, OPEN3D_CPU_LINALG_INT * ipiv_data) inline
Definition at line 106 of file LapackWrapper.h.
InsertKernelPass0()
template<typename Key , typename Hash , typename Eq > __global__ void cloudViewer::core::InsertKernelPass0 (SlabHashBackendImpl< Key, Hash, Eq > impl, const void * input_keys, buf_index_t * output_buf_indices, int heap_counter_prev, int64_t count)
Kernels.
Definition at line 474 of file SlabHashBackendImpl.h.
References cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::buffer_accessor_, count, cloudViewer::core::CUDAHashBackendBufferAccessor::GetKeyPtr(), and cloudViewer::core::CUDAHashBackendBufferAccessor::heap_.
Referenced by cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::Insert().
InsertKernelPass1()
template<typename Key , typename Hash , typename Eq > __global__ void cloudViewer::core::InsertKernelPass1 (SlabHashBackendImpl< Key, Hash, Eq > impl, const void * input_keys, buf_index_t * output_buf_indices, bool * output_masks, int64_t count)
Definition at line 493 of file SlabHashBackendImpl.h.
References cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::ComputeBucket(), count, cloudViewer::core::SlabNodeManagerImpl::Init(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Insert(), and cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::node_mgr_impl_.
Referenced by cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::Insert().
InsertKernelPass2()
template<typename Key , typename Hash , typename Eq , typename block_t > __global__ void cloudViewer::core::InsertKernelPass2 (SlabHashBackendImpl< Key, Hash, Eq > impl, const void *const * input_values_soa, buf_index_t * output_buf_indices, bool * output_masks, int64_t count, int64_t n_values)
Definition at line 530 of file SlabHashBackendImpl.h.
References cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::buffer_accessor_, count, cloudViewer::core::CUDAHashBackendBufferAccessor::DeviceFree(), cloudViewer::core::CUDAHashBackendBufferAccessor::GetValuePtr(), and cloudViewer::core::CUDAHashBackendBufferAccessor::value_blocks_per_element_.
Inverse()
void cloudViewer::core::Inverse (const Tensor & A, Tensor & output)
Computes A^{-1} with LU factorization, where A is a N x N square matrix.
Definition at line 18 of file Inverse.cpp.
References AssertTensorDtypes, cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Tensor::Empty(), cloudViewer::core::Tensor::Eye(), Float32, Float64, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), Int32, Int64, InverseCPU(), InverseCUDA(), InverseSYCL(), LogError, OPEN3D_CPU_LINALG_INT, cloudViewer::core::SmallVectorBase< Size_T >::size(), cloudViewer::core::Tensor::T(), cloudViewer::core::Tensor::To(), and cloudViewer::core::Tensor::Zeros().
Referenced by cloudViewer::t::pipelines::kernel::ComputePoseDopplerICP(), and cloudViewer::core::Tensor::Inverse().
InverseCPU() [1/2]
void cloudViewer::core::InverseCPU (void * A_data, void * ipiv_data, [[maybe_unused] ] void * output_data, int64_t n, Dtype dtype, const Device & device)
Referenced by Inverse().
InverseCPU() [2/2]
void cloudViewer::core::InverseCPU (void * A_data, void * ipiv_data, void * output_data, int64_t n, Dtype dtype, const Device & device)
Definition at line 15 of file InverseCPU.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, OPEN3D_CPU_LINALG_INT, and OPEN3D_LAPACK_CHECK().
InverseCUDA()
void cloudViewer::core::InverseCUDA (void * A_data, void * ipiv_data, void * output_data, int64_t n, Dtype dtype, const Device & device)
Definition at line 16 of file InverseCUDA.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, cloudViewer::core::Blob::GetDataPtr(), and Runtime::GetInstance().
Referenced by Inverse().
InverseSYCL()
void cloudViewer::core::InverseSYCL (void * A_data, void * ipiv_data, void * output_data, int64_t n, Dtype dtype, const Device & device)
Definition at line 19 of file InverseSYCL.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, cloudViewer::core::Blob::GetDataPtr(), cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), cloudViewer::core::sy::SYCLContext::GetInstance(), and max().
Referenced by Inverse().
LeastSquares()
void cloudViewer::core::LeastSquares (const Tensor & A, const Tensor & B, Tensor & X)
Solve AX = B with QR decomposition. A is a full-rank m x n matrix (m >= n).
Definition at line 17 of file LeastSquares.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, cloudViewer::core::Tensor::Clone(), Float32, Float64, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Device::IsCUDA(), cloudViewer::core::Device::IsSYCL(), LeastSquaresCPU(), LeastSquaresCUDA(), LeastSquaresSYCL(), LogError, cloudViewer::core::SmallVectorBase< Size_T >::size(), cloudViewer::core::Tensor::Slice(), cloudViewer::core::Tensor::T(), and X.
Referenced by cloudViewer::core::Tensor::LeastSquares().
LeastSquaresCPU()
void cloudViewer::core::LeastSquaresCPU (void * A_data, void * B_data, int64_t m, int64_t n, int64_t k, Dtype dtype, const Device & device)
Definition at line 15 of file LeastSquaresCPU.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, max(), and OPEN3D_LAPACK_CHECK().
Referenced by LeastSquares().
LeastSquaresCUDA()
void cloudViewer::core::LeastSquaresCUDA (void * A_data, void * B_data, int64_t m, int64_t n, int64_t k, Dtype dtype, const Device & device)
Definition at line 24 of file LeastSquaresCUDA.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, cloudViewer::core::Blob::GetDataPtr(), Runtime::GetInstance(), and max().
Referenced by LeastSquares().
LeastSquaresSYCL()
void cloudViewer::core::LeastSquaresSYCL (void * A_data, void * B_data, int64_t m, int64_t n, int64_t k, Dtype dtype, const Device & device)
Definition at line 19 of file LeastSquaresSYCL.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, cloudViewer::core::Blob::GetDataPtr(), cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), cloudViewer::core::sy::SYCLContext::GetInstance(), and max().
Referenced by LeastSquares().
LU()
void cloudViewer::core::LU (const Tensor & A, Tensor & permutation, Tensor & lower, Tensor & upper, const bool permute_l)
Definition at line 126 of file LU.cpp.
References AssertTensorDtypes, Float32, Float64, cloudViewer::core::Tensor::GetShape(), LUIpiv(), min(), OutputToPLU(), and cloudViewer::core::Tensor::Slice().
Referenced by cloudViewer::core::Tensor::LU().
LUCPU()
void cloudViewer::core::LUCPU (void * A_data, void * ipiv_data, int64_t rows, int64_t cols, Dtype dtype, const Device & device)
Definition at line 15 of file LUCPU.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, OPEN3D_CPU_LINALG_INT, and OPEN3D_LAPACK_CHECK().
Referenced by LUIpiv().
LUCUDA()
void cloudViewer::core::LUCUDA (void * A_data, void * ipiv_data, int64_t rows, int64_t cols, Dtype dtype, const Device & device)
Definition at line 15 of file LUCUDA.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, cloudViewer::core::MemoryManager::Free(), Runtime::GetInstance(), and cloudViewer::core::MemoryManager::Malloc().
Referenced by LUIpiv().
LUIpiv()
void cloudViewer::core::LUIpiv (const Tensor & A, Tensor & ipiv, Tensor & output)
Definition at line 62 of file LU.cpp.
References AssertTensorDtypes, cloudViewer::core::Tensor::Clone(), cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Tensor::Empty(), Float32, Float64, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), Int32, Int64, LogError, LogInfo, LUCPU(), LUCUDA(), LUSYCL(), min(), OPEN3D_CPU_LINALG_INT, cloudViewer::core::SmallVectorBase< Size_T >::size(), and cloudViewer::core::Tensor::T().
Referenced by Det(), LU(), and cloudViewer::core::Tensor::LUIpiv().
LUSYCL()
void cloudViewer::core::LUSYCL (void * A_data, void * ipiv_data, int64_t m, int64_t n, Dtype dtype, const Device & device)
Definition at line 19 of file LUSYCL.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, cloudViewer::core::Blob::GetDataPtr(), cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), and cloudViewer::core::sy::SYCLContext::GetInstance().
Referenced by LUIpiv().
make_pair()
template<typename First , typename Second > CLOUDVIEWER_HOST_DEVICE Pair<First, Second> cloudViewer::core::make_pair (const First & _first, const Second & _second)
Definition at line 49 of file SlabTraits.h.
Referenced by cloudViewer::core::HashMap::Activate(), cloudViewer::visualization::rendering::FilamentScene::AddDirectionalLight(), cloudViewer::visualization::rendering::FilamentScene::AddPointLight(), cloudViewer::visualization::rendering::FilamentScene::AddSpotLight(), cloudViewer::t::geometry::BufferRadiusNeighbors(), flann::LshIndex< Distance >::buildIndexImpl(), cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBJylanki(), define_NormalDistribution(), cloudViewer::t::geometry::Image::Dilate(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Erase(), cloudViewer::core::AdvancedIndexPreprocessor::ExpandToCommonShapeExceptZeroDim(), cloudViewer::t::geometry::Image::Filter(), cloudViewer::t::geometry::Image::FilterBilateral(), cloudViewer::t::geometry::Image::FilterGaussian(), cloudViewer::t::geometry::Image::FilterSobel(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Find(), cloudViewer::core::HashMap::Find(), cloudViewer::core::HashSet::Find(), cloudViewer::t::io::RealSenseSensorConfig::get_dtype_channels(), getCentroid(), getCommonPtsIdx(), cloudViewer::camera::PinholeCameraIntrinsic::GetFocalLength(), getKNN(), cloudViewer::geometry::LineSet::GetLineCoordinate(), cloudViewer::camera::PinholeCameraIntrinsic::GetPrincipalPoint(), cloudViewer::t::geometry::VoxelBlockGrid::GetVoxelCoordinatesAndFlattenedIndices(), cloudViewer::core::HashSet::Insert(), cloudViewer::core::HashMap::Insert(), cloudViewer::t::geometry::Image::Resize(), cloudViewer::core::shape_util::Restride(), cloudViewer::t::geometry::Image::RGBToGray(), cloudViewer::pipelines::color_map::RunNonRigidOptimizer(), cloudViewer::pipelines::color_map::RunRigidOptimizer(), cloudViewer::t::pipelines::slac::RunSLACOptimizerForFragments(), cloudViewer::core::nns::KnnIndex::SearchKnn(), cloudViewer::core::nns::NanoFlannIndex::SearchKnn(), cloudViewer::core::AdvancedIndexPreprocessor::ShuffleIndexedDimsToFront(), cloudViewer::t::pipelines::slac::VisualizeGridDeformation(), cloudViewer::t::pipelines::slac::VisualizePointCloudCorrespondences(), cloudViewer::t::pipelines::slac::VisualizePointCloudDeformation(), and cloudViewer::io::WriteTriangleMeshToGLTF().
Matmul()
void cloudViewer::core::Matmul (const Tensor & A, const Tensor & B, Tensor & output)
Computes matrix multiplication C = AB.
Definition at line 17 of file Matmul.cpp.
References AssertTensorDevice, AssertTensorDtype, cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Tensor::Empty(), Float32, Float64, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Device::IsCUDA(), cloudViewer::core::Device::IsSYCL(), LogDebug, LogError, MatmulCPU(), MatmulCUDA(), MatmulSYCL(), cloudViewer::core::SmallVectorBase< Size_T >::size(), cloudViewer::core::Tensor::To(), and cloudViewer::core::Dtype::ToString().
Referenced by cloudViewer::core::Tensor::Matmul().
MatmulCPU()
void cloudViewer::core::MatmulCPU (void * A_data, void * B_data, void * C_data, int64_t m, int64_t k, int64_t n, Dtype dtype)
Definition at line 14 of file MatmulCPU.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE.
Referenced by Matmul().
MatmulCUDA()
void cloudViewer::core::MatmulCUDA (void * A_data, void * B_data, void * C_data, int64_t m, int64_t k, int64_t n, Dtype dtype, const Device & device)
Definition at line 17 of file MatmulCUDA.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, and Runtime::GetInstance().
Referenced by Matmul().
MatmulSYCL()
void cloudViewer::core::MatmulSYCL (void * A_data, void * B_data, void * C_data, int64_t m, int64_t k, int64_t n, Dtype dtype, const Device & device)
Definition at line 19 of file MatmulSYCL.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), and cloudViewer::core::sy::SYCLContext::GetInstance().
Referenced by Matmul().
Maximum()
Tensor cloudViewer::core::Maximum (const Tensor & input, const Tensor & other)
Computes the element-wise maximum of input and other. The tensors must have same data type and device.
If input.GetShape() != other.GetShape(), then they will be broadcasted to a common shape (which becomes the shape of the output).
Parameters
input The input tensor.
other The second input tensor.
Definition at line 124 of file TensorFunction.cpp.
References AssertTensorDevice, AssertTensorDtype, cloudViewer::core::kernel::BinaryEW(), cloudViewer::core::shape_util::BroadcastedShape(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), and cloudViewer::core::kernel::Maximum.
Referenced by cloudViewer::t::geometry::AxisAlignedBoundingBox::operator+=().
Minimum()
Tensor cloudViewer::core::Minimum (const Tensor & input, const Tensor & other)
Computes the element-wise minimum of input and other. The tensors must have same data type and device.
If input.GetShape() != other.GetShape(), then they will be broadcasted to a common shape (which becomes the shape of the output).
Parameters
input The input tensor.
other The second input tensor.
Definition at line 136 of file TensorFunction.cpp.
References AssertTensorDevice, AssertTensorDtype, cloudViewer::core::kernel::BinaryEW(), cloudViewer::core::shape_util::BroadcastedShape(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), and cloudViewer::core::kernel::Minimum.
Referenced by cloudViewer::t::geometry::PointCloud::FarthestPointDownSample(), cloudViewer::t::geometry::AxisAlignedBoundingBox::operator+=(), and StereogramDialog::StereogramDialog().
OPEN3D_LAPACK_CHECK()
void cloudViewer::core::OPEN3D_LAPACK_CHECK (OPEN3D_CPU_LINALG_INT info, const std::string & msg) inline
Definition at line 36 of file LinalgUtils.h.
References LogError.
Referenced by InverseCPU(), LeastSquaresCPU(), LUCPU(), SolveCPU(), and SVDCPU().
operator*()
template<typename T > Tensor cloudViewer::core::operator* (T scalar_lhs, const Tensor & rhs) inline
Definition at line 1420 of file Tensor.h.
operator+()
template<typename T > Tensor cloudViewer::core::operator+ (T scalar_lhs, const Tensor & rhs) inline
Definition at line 1410 of file Tensor.h.
operator-()
template<typename T > Tensor cloudViewer::core::operator- (T scalar_lhs, const Tensor & rhs) inline
Definition at line 1415 of file Tensor.h.
References cloudViewer::core::Tensor::Full(), cloudViewer::core::Tensor::GetDevice(), and cloudViewer::core::Tensor::GetDtype().
operator/()
template<typename T > Tensor cloudViewer::core::operator/ (T scalar_lhs, const Tensor & rhs) inline
Definition at line 1425 of file Tensor.h.
References cloudViewer::core::Tensor::Full(), cloudViewer::core::Tensor::GetDevice(), and cloudViewer::core::Tensor::GetDtype().
OutputToPLU()
static void cloudViewer::core::OutputToPLU (const Tensor & output, Tensor & permutation, Tensor & lower, Tensor & upper, const Tensor & ipiv, const bool permute_l) static
Definition at line 38 of file LU.cpp.
References cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Tensor::Eye(), GetColPermutation(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::IndexGet(), cloudViewer::core::Tensor::Matmul(), cloudViewer::core::Tensor::T(), and Triul().
Referenced by LU().
ParallelFor() [1/2]
template<typename func_t > void cloudViewer::core::ParallelFor (const Device & device, int64_t n, const func_t & func)
Run a function in parallel on CPU or CUDA.
Parameters
device The device for the parallel for loop to run on.
n The number of workloads.
func The function to be executed in parallel. The function should take an int64_t workload index and returns void, i.e., void func(int64_t).
Note
This is optimized for uniform work items, i.e. where each call to func takes the same time.
If you use a lambda function, capture only the required variables instead of all to prevent accidental race conditions. If you want the kernel to be used on both CPU and CUDA, capture the variables by value.
This does not dispatch to SYCL, since SYCL has extra constraints:
Lambdas may capture by value only.
No function pointers / virtual functions. Auto dispatch to SYCL will enforce these conditions even on CPU devices. Use ParallelForSYCL instead.
Definition at line 111 of file ParallelFor.h.
References ParallelForCPU_().
Referenced by cloudViewer::core::kernel::ArangeCPU(), cloudViewer::t::pipelines::kernel::ComputeFPFHFeatureCPU(), cloudViewer::t::geometry::kernel::trianglemesh::ComputeTriangleAreasCPU(), cloudViewer::t::geometry::kernel::trianglemesh::ComputeTriangleNormalsCPU(), cloudViewer::core::kernel::CopyCPU(), cloudViewer::t::geometry::kernel::image::CreateNormalMapCPU(), cloudViewer::t::geometry::kernel::image::CreateVertexMapCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingHybridSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingKNNSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingRadiusSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingHybridSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingKNNSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingRadiusSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateNormalsFromCovariancesCPU(), cloudViewer::t::geometry::kernel::voxel_grid::EstimateRangeCPU(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractPointCloudCPU(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractTriangleMeshCPU(), cloudViewer::t::pipelines::kernel::FillInRigidAlignmentTermCPU(), cloudViewer::t::pipelines::kernel::FillInSLACAlignmentTermCPU(), cloudViewer::t::pipelines::kernel::FillInSLACRegularizerTermCPU(), cloudViewer::t::geometry::kernel::voxel_grid::GetVoxelCoordinatesAndFlattenedIndicesCPU(), cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU(), cloudViewer::core::kernel::LaunchAdvancedIndexerKernel(), cloudViewer::core::kernel::LaunchBinaryEWKernel(), cloudViewer::core::eigen_converter::LaunchIndexFillKernel(), cloudViewer::core::kernel::LaunchUnaryEWKernel(), cloudViewer::t::geometry::kernel::pointcloud::NormalizeNormalsCPU(), cloudViewer::t::geometry::kernel::trianglemesh::NormalizeNormalsCPU(), cloudViewer::t::geometry::kernel::pointcloud::OrientNormalsToAlignWithDirectionCPU(), cloudViewer::t::geometry::kernel::pointcloud::OrientNormalsTowardsCameraLocationCPU(), cloudViewer::t::geometry::kernel::voxel_grid::PointCloudTouchCPU(), cloudViewer::t::geometry::kernel::pointcloud::ProjectCPU(), cloudViewer::t::geometry::kernel::image::PyrDownDepthCPU(), cloudViewer::t::geometry::kernel::voxel_grid::RayCastCPU(), cloudViewer::t::io::ReadTriangleMeshUsingASSIMP(), and cloudViewer::t::io::DepthNoiseSimulator::Simulate().
ParallelFor() [2/2]
template<typename vec_func_t , typename func_t > void cloudViewer::core::ParallelFor (const Device & device, int64_t n, const func_t & func, const vec_func_t & vec_func)
Run a potentially vectorized function in parallel on CPU or CUDA.
Parameters
device The device for the parallel for loop to run on.
n The number of workloads.
func The function to be executed in parallel. The function should take an int64_t workload index and returns void, i.e., void func(int64_t).
vec_func The vectorized function to be executed in parallel. The function should be provided using the CLOUDVIEWER_VECTORIZED macro, e.g., CLOUDVIEWER_VECTORIZED(MyISPCKernel, some_used_variable).
Note
This is optimized for uniform work items, i.e. where each call to func takes the same time.
If you use a lambda function, capture only the required variables instead of all to prevent accidental race conditions. If you want the kernel to be used on both CPU and CUDA, capture the variables by value.
Example:
/* MyFile.cpp */
#ifdef BUILD_ISPC_MODULE
#include "MyFile_ispc.h"
#endif
std::vector<float> v(1000);
float fill_value = 42.0f;
core::ParallelFor(
        core::Device("CPU:0"),
        v.size(),
        [&](int64_t idx) { v[idx] = fill_value; },
        CLOUDVIEWER_VECTORIZED(MyFillKernel, v.data(), fill_value));
/* MyFile.ispc */
#include "cloudViewer/core/ParallelFor.isph"
static inline void MyFillFunction(int64_t idx,
                                  float* uniform v,
                                  uniform float fill_value) {
    v[idx] = fill_value;
}
CLOUDVIEWER_EXPORT_VECTORIZED(MyFillKernel,
                              MyFillFunction,
                              float* uniform,
                              uniform float)
Definition at line 166 of file ParallelFor.h.
References cloudViewer::utility::EstimateMaxThreads(), and ParallelForCPU_().
ParallelForCPU_()
template<typename func_t > void cloudViewer::core::ParallelForCPU_ (const Device & device, int64_t n, const func_t & func)
Run a function in parallel on CPU.
Definition at line 76 of file ParallelFor.h.
References cloudViewer::core::Device::IsCPU(), LogError, and cloudViewer::core::Device::ToString().
Referenced by ParallelFor().
ParallelForSYCL() [1/2]
template<typename Functor , typename... FuncArgs> void cloudViewer::core::ParallelForSYCL (const Device & device, Indexer indexer, FuncArgs... func_args)
Run a function in parallel with SYCL.
TODO: Specify grid size based on device properties
Definition at line 24 of file ParallelForSYCL.h.
References cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), cloudViewer::core::sy::SYCLContext::GetInstance(), indexer, cloudViewer::core::Device::IsSYCL(), LogError, cloudViewer::core::Indexer::NumWorkloads(), and cloudViewer::core::Device::ToString().
Referenced by cloudViewer::core::kernel::BinaryEWSYCL().
ParallelForSYCL() [2/2]
template<typename Functor , typename... FuncArgs> void cloudViewer::core::ParallelForSYCL (const Device & device, int64_t num_workloads, FuncArgs... func_args)
Run a function in parallel with SYCL.
TODO: Specify grid size based on device properties
Definition at line 45 of file ParallelForSYCL.h.
References cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), cloudViewer::core::sy::SYCLContext::GetInstance(), cloudViewer::core::Device::IsSYCL(), LogError, and cloudViewer::core::Device::ToString().
report_at_maximum_capacity()
static void cloudViewer::core::report_at_maximum_capacity (size_t MaxSize) static
Report that this vector is already at maximum capacity. Throws std::length_error or calls report_fatal_error.
Definition at line 91 of file SmallVector.cpp.
References patch::to_string().
report_size_overflow()
static void cloudViewer::core::report_size_overflow (size_t MinSize, size_t MaxSize) static
Report that MinSize doesn't fit into this vector's size type. Throws std::length_error or calls report_fatal_error.
Definition at line 76 of file SmallVector.cpp.
References patch::to_string().
Referenced by getNewCapacity().
safe_malloc()
void* cloudViewer::core::safe_malloc (size_t Sz) inline
Definition at line 58 of file SmallVector.h.
Referenced by cloudViewer::core::SmallVectorBase< Size_T >::grow_pod(), cloudViewer::core::SmallVectorBase< Size_T >::mallocForGrow(), and safe_realloc().
safe_realloc()
void* cloudViewer::core::safe_realloc (void * Ptr, size_t Sz) inline
Definition at line 70 of file SmallVector.h.
References safe_malloc().
Referenced by cloudViewer::core::SmallVectorBase< Size_T >::grow_pod().
Solve()
void cloudViewer::core::Solve (const Tensor & A, const Tensor & B, Tensor & X)
Solve AX = B with LU decomposition. A is a square matrix.
Definition at line 22 of file Solve.cpp.
References AssertTensorDevice, AssertTensorDtype, AssertTensorDtypes, cloudViewer::core::Tensor::Clone(), cloudViewer::core::Tensor::Empty(), Float32, Float64, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), Int32, Int64, LogError, OPEN3D_CPU_LINALG_INT, cloudViewer::core::SmallVectorBase< Size_T >::size(), SolveCPU(), SolveCUDA(), SolveSYCL(), cloudViewer::core::Tensor::T(), and X.
Referenced by cloudViewer::core::Tensor::Solve().
SolveCPU()
void cloudViewer::core::SolveCPU (void * A_data, void * B_data, void * ipiv_data, int64_t n, int64_t k, Dtype dtype, const Device & device)
Definition at line 15 of file SolveCPU.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, OPEN3D_CPU_LINALG_INT, and OPEN3D_LAPACK_CHECK().
Referenced by Solve().
SolveCUDA()
void cloudViewer::core::SolveCUDA (void * A_data, void * B_data, void * ipiv_data, int64_t n, int64_t k, Dtype dtype, const Device & device)
Definition at line 20 of file SolveCUDA.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, cloudViewer::core::Blob::GetDataPtr(), and Runtime::GetInstance().
Referenced by Solve().
SolveSYCL()
void cloudViewer::core::SolveSYCL (void * A_data, void * B_data, void * ipiv_data, int64_t n, int64_t k, Dtype dtype, const Device & device)
Definition at line 19 of file SolveSYCL.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, cloudViewer::core::Blob::GetDataPtr(), cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), and cloudViewer::core::sy::SYCLContext::GetInstance().
Referenced by Solve().
STDGPUEraseKernel()
template<typename Key , typename Hash , typename Eq > __global__ void cloudViewer::core::STDGPUEraseKernel (InternalStdGPUHashBackend< Key, Hash, Eq > map, CUDAHashBackendBufferAccessor buffer_accessor, const Key * input_keys, buf_index_t * output_buf_indices, bool * output_masks, int64_t count)
Definition at line 211 of file StdGPUHashBackend.h.
References count, and cloudViewer::core::CUDAHashBackendBufferAccessor::DeviceFree().
Referenced by cloudViewer::core::StdGPUHashBackend< Key, Hash, Eq >::Erase().
STDGPUFindKernel()
template<typename Key , typename Hash , typename Eq > __global__ void cloudViewer::core::STDGPUFindKernel (InternalStdGPUHashBackend< Key, Hash, Eq > map, CUDAHashBackendBufferAccessor buffer_accessor, const Key * input_keys, buf_index_t * output_buf_indices, bool * output_masks, int64_t count)
Definition at line 178 of file StdGPUHashBackend.h.
References count.
Referenced by cloudViewer::core::StdGPUHashBackend< Key, Hash, Eq >::Find().
STDGPUInsertKernel()
template<typename Key , typename Hash , typename Eq , typename block_t > __global__ void cloudViewer::core::STDGPUInsertKernel (InternalStdGPUHashBackend< Key, Hash, Eq > map, CUDAHashBackendBufferAccessor buffer_accessor, const Key * input_keys, const void *const * input_values_soa, buf_index_t * output_buf_indices, bool * output_masks, int64_t count, int64_t n_values)
Definition at line 305 of file StdGPUHashBackend.h.
References count, cloudViewer::core::CUDAHashBackendBufferAccessor::DeviceAllocate(), cloudViewer::core::CUDAHashBackendBufferAccessor::GetKeyPtr(), cloudViewer::core::CUDAHashBackendBufferAccessor::GetValuePtr(), and cloudViewer::core::CUDAHashBackendBufferAccessor::value_blocks_per_element_.
StringToDeviceId()
static int cloudViewer::core::StringToDeviceId (const std::string & type_colon_id) static
Definition at line 47 of file Device.cpp.
References LogError, and cloudViewer::utility::SplitString().
StringToDeviceType()
static Device::DeviceType cloudViewer::core::StringToDeviceType (const std::string & type_colon_id) static
Definition at line 22 of file Device.cpp.
References cloudViewer::core::Device::CPU, cloudViewer::core::Device::CUDA, LogError, cloudViewer::utility::SplitString(), cloudViewer::core::Device::SYCL, and cloudViewer::utility::ToLower().
SVD()
void cloudViewer::core::SVD (const Tensor & A, Tensor & U, Tensor & S, Tensor & VT)
Computes SVD decomposition A = U S VT, where A is an m x n, U is an m x m, S is a min(m, n), VT is an n x n tensor.
Definition at line 17 of file SVD.cpp.
References AssertTensorDtypes, cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Tensor::Empty(), Float32, Float64, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), LogError, min(), cloudViewer::core::SmallVectorBase< Size_T >::size(), SVDCPU(), SVDCUDA(), SVDSYCL(), and cloudViewer::core::Tensor::T().
Referenced by cloudViewer::core::Tensor::SVD().
SVDCPU()
void cloudViewer::core::SVDCPU (const void * A_data, void * U_data, void * S_data, void * VT_data, void * superb_data, int64_t m, int64_t n, Dtype dtype, const Device & device)
Definition at line 15 of file SVDCPU.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, and OPEN3D_LAPACK_CHECK().
Referenced by SVD().
SVDCUDA()
void cloudViewer::core::SVDCUDA (const void * A_data, void * U_data, void * S_data, void * VT_data, void * superb_data, int64_t m, int64_t n, Dtype dtype, const Device & device)
Definition at line 16 of file SVDCUDA.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, cloudViewer::core::Blob::GetDataPtr(), and Runtime::GetInstance().
Referenced by SVD().
SVDSYCL()
void cloudViewer::core::SVDSYCL (const void * A_data, void * U_data, void * S_data, void * VT_data, int64_t m, int64_t n, Dtype dtype, const Device & device)
Definition at line 19 of file SVDSYCL.cpp.
References DISPATCH_LINALG_DTYPE_TO_TEMPLATE, cloudViewer::core::Blob::GetDataPtr(), cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), and cloudViewer::core::sy::SYCLContext::GetInstance().
Referenced by SVD().
to_vector() [1/2]
template<unsigned Size, typename R > SmallVector<ValueTypeFromRangeType<R>, Size> cloudViewer::core::to_vector (R && Range)
Given a range of type R, iterate the entire range and return a SmallVector with elements of the vector. This is useful, for example, when you want to iterate a range and then sort the results.
Definition at line 1352 of file SmallVector.h.
to_vector() [2/2]
template<typename R > SmallVector<ValueTypeFromRangeType<R>, CalculateSmallVectorDefaultInlinedElements< ValueTypeFromRangeType<R> >::value> cloudViewer::core::to_vector (R && Range)
Definition at line 1359 of file SmallVector.h.
Tril()
void cloudViewer::core::Tril (const Tensor & A, Tensor & output, const int diagonal)
Definition at line 57 of file Tri.cpp.
References CheckInput(), cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Device::IsCUDA(), cloudViewer::core::Device::IsSYCL(), LogError, TrilCPU(), TrilSYCL(), and cloudViewer::core::Tensor::Zeros().
Referenced by cloudViewer::core::Tensor::Tril().
TrilCPU()
void cloudViewer::core::TrilCPU (const Tensor & A, Tensor & output, const int diagonal)
Definition at line 35 of file TriCPU.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, and cloudViewer::core::Tensor::GetDtype().
Referenced by Tril().
TrilSYCL()
void cloudViewer::core::TrilSYCL (const Tensor & A, Tensor & output, const int diagonal)
Definition at line 34 of file TriSYCL.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), and Runtime::GetInstance().
Referenced by Tril().
Triu()
void cloudViewer::core::Triu (const Tensor & A, Tensor & output, const int diagonal)
Definition at line 35 of file Tri.cpp.
References CheckInput(), cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Device::IsCUDA(), cloudViewer::core::Device::IsSYCL(), LogError, TriuCPU(), TriuSYCL(), and cloudViewer::core::Tensor::Zeros().
Referenced by cloudViewer::core::Tensor::Triu().
TriuCPU()
void cloudViewer::core::TriuCPU (const Tensor & A, Tensor & output, const int diagonal)
Definition at line 17 of file TriCPU.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, and cloudViewer::core::Tensor::GetDtype().
Referenced by Triu().
Triul()
void cloudViewer::core::Triul (const Tensor & A, Tensor & upper, Tensor & lower, const int diagonal)
Definition at line 79 of file Tri.cpp.
References CheckInput(), cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Device::IsCUDA(), cloudViewer::core::Device::IsSYCL(), LogError, TriulCPU(), TriulSYCL(), and cloudViewer::core::Tensor::Zeros().
Referenced by OutputToPLU(), and cloudViewer::core::Tensor::Triul().
TriulCPU()
void cloudViewer::core::TriulCPU (const Tensor & A, Tensor & upper, Tensor & lower, const int diagonal)
Definition at line 53 of file TriCPU.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, and cloudViewer::core::Tensor::GetDtype().
Referenced by Triul().
TriulSYCL()
void cloudViewer::core::TriulSYCL (const Tensor & A, Tensor & upper, Tensor & lower, const int diagonal)
Definition at line 52 of file TriSYCL.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), and Runtime::GetInstance().
Referenced by Triul().
TriuSYCL()
void cloudViewer::core::TriuSYCL (const Tensor & A, Tensor & output, const int diagonal)
Definition at line 16 of file TriSYCL.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), and cloudViewer::core::sy::SYCLContext::GetInstance().
Referenced by Triu().
Variable Documentation
Bool
const Dtype cloudViewer::core::Bool = Dtype::Bool
Definition at line 52 of file Dtype.cpp.
Referenced by cloudViewer::core::Tensor::All(), cloudViewer::core::Tensor::Any(), cloudViewer::core::kernel::BinaryEWCPU(), cloudViewer::core::kernel::BinaryEWSYCL(), cloudViewer::t::geometry::PointCloud::ComputeBoundaryPoints(), cloudViewer::t::pipelines::registration::ComputeFPFHFeature(), cloudViewer::t::io::ConvertColorTensorToUint8(), cloudViewer::t::geometry::vtkutils::CreateVtkDataArrayFromTensor(), cloudViewer::t::geometry::npp::Dilate(), cloudViewer::t::geometry::Image::Dilate(), cloudViewer::t::io::DtypeToChar(), cloudViewer::t::geometry::vtkutils::DtypeToVtkType(), cloudViewer::core::Tensor::Eq(), cloudViewer::core::AdvancedIndexPreprocessor::ExpandBoolTensors(), cloudViewer::t::geometry::PointCloud::FarthestPointDownSample(), cloudViewer::core::Tensor::Ge(), cloudViewer::t::io::NumpyArray::GetDtype(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetPointIndicesWithinBoundingBox(), cloudViewer::t::geometry::OrientedBoundingBox::GetPointIndicesWithinBoundingBox(), cloudViewer::t::geometry::kernel::pointcloud::GetPointMaskWithinAABB(), cloudViewer::t::geometry::kernel::pointcloud::GetPointMaskWithinOBB(), cloudViewer::core::Tensor::Gt(), cloudViewer::core::Indexer::Indexer(), cloudViewer::core::Tensor::IndexGet(), cloudViewer::core::Tensor::IndexSet(), cloudViewer::core::Tensor::IsFinite(), cloudViewer::core::Tensor::IsInf(), cloudViewer::core::Tensor::IsNan(), cloudViewer::core::Tensor::Le(), cloudViewer::core::Tensor::LogicalAnd(), cloudViewer::core::Tensor::LogicalNot(), cloudViewer::core::Tensor::LogicalOr(), cloudViewer::core::Tensor::LogicalXor(), cloudViewer::core::Tensor::Lt(), cloudViewer::core::Tensor::Ne(), cloudViewer::core::HashMap::PrepareMasksOutput(), cloudViewer::t::geometry::PointCloud::RemoveNonFinitePoints(), cloudViewer::t::geometry::PointCloud::RemoveStatisticalOutliers(), cloudViewer::t::geometry::TriangleMesh::RemoveUnreferencedVertices(), cloudViewer::t::geometry::Image::Resize(), cloudViewer::core::Tensor::ScalarPtrToString(), cloudViewer::t::geometry::TriangleMesh::SelectByIndex(), cloudViewer::t::geometry::PointCloud::SelectByIndex(), cloudViewer::t::geometry::TriangleMesh::SelectFacesByMask(), cloudViewer::t::geometry::Image::To(), cloudViewer::core::kernel::UnaryEWCPU(), and cloudViewer::t::io::WriteImageToPNG().
Float32
const Dtype cloudViewer::core::Float32 = Dtype::Float32
Definition at line 42 of file Dtype.cpp.
Referenced by AddMM(), cloudViewer::t::geometry::RaycastingScene::AddTriangles(), cloudViewer::io::rpc::ArrayToTensor(), cloudViewer::t::geometry::AxisAlignedBoundingBox::AxisAlignedBoundingBox(), cloudViewer::t::geometry::TriangleMesh::BakeTriangleAttrTextures(), cloudViewer::t::geometry::TriangleMesh::BakeVertexAttrTextures(), cloudViewer::t::geometry::RaycastingScene::CastRays(), cloudViewer::t::geometry::CheckColorTensor(), cloudViewer::t::geometry::CheckDepthTensor(), cloudViewer::t::geometry::TriangleMesh::ClipPlane(), cloudViewer::t::geometry::Image::ClipTransform(), cloudViewer::t::geometry::Image::ColorizeDepth(), cloudViewer::t::geometry::PointCloud::ComputeBoundaryPoints(), cloudViewer::t::geometry::RaycastingScene::ComputeClosestPoints(), cloudViewer::t::geometry::RaycastingScene::ComputeDistance(), cloudViewer::t::geometry::ComputeMetricsCommon(), cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBApprox(), cloudViewer::t::geometry::RaycastingScene::ComputeOccupancy(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryInformationMatrix(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryInformationMatrixCPU(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultHybrid(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultHybridCPU(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultIntensity(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultIntensityCPU(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultPointToPlane(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultPointToPlaneCPU(), cloudViewer::t::geometry::kernel::uvunwrapping::ComputeUVAtlas(), cloudViewer::visualization::rendering::TMeshBuffersBuilder::ConstructBuffers(), cloudViewer::t::pipelines::slac::ControlGrid::ControlGrid(), cloudViewer::t::io::ConvertColorTensorToUint8(), cloudViewer::t::geometry::TriangleMesh::CreateBox(), cloudViewer::t::geometry::LineSet::CreateCameraVisualization(), cloudViewer::t::geometry::AxisAlignedBoundingBox::CreateFromPoints(), cloudViewer::t::geometry::OrientedBoundingBox::CreateFromPoints(), cloudViewer::t::geometry::PointCloud::CreateFromRGBDImage(), cloudViewer::t::geometry::TriangleMesh::CreateIsosurfaces(), cloudViewer::t::geometry::Image::CreateNormalMap(), cloudViewer::t::geometry::RaycastingScene::CreateRaysPinhole(), cloudViewer::t::geometry::TriangleMesh::CreateText(), cloudViewer::t::pipelines::slac::CreateTPCDFromFile(), cloudViewer::t::geometry::Image::CreateVertexMap(), cloudViewer::t::geometry::vtkutils::CreateVtkImageDataFromTensor(), cloudViewer::t::geometry::vtkutils::CreateVtkPointsFromTensor(), cloudViewer::t::io::DepthNoiseSimulator::DepthNoiseSimulator(), cloudViewer::core::Tensor::Det(), Det(), cloudViewer::t::geometry::npp::Dilate(), cloudViewer::t::geometry::Image::Dilate(), DLDataTypeToDtype(), cloudViewer::t::io::DtypeToChar(), DtypeToDLDataTypeCode(), cloudViewer::t::geometry::vtkutils::DtypeToVtkType(), cloudViewer::t::geometry::PointCloud::EstimateColorGradients(), cloudViewer::t::geometry::PointCloud::EstimateNormals(), cloudViewer::t::geometry::kernel::voxel_grid::EstimateRangeCPU(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractPointCloudCPU(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractTriangleMeshCPU(), cloudViewer::t::geometry::vtkutils::ExtrudeLinearPolyData(), cloudViewer::t::geometry::vtkutils::ExtrudeRotationPolyData(), cloudViewer::t::pipelines::kernel::FillInRigidAlignmentTerm(), cloudViewer::t::pipelines::slac::FillInRigidAlignmentTerm(), cloudViewer::t::pipelines::kernel::FillInRigidAlignmentTermCPU(), cloudViewer::t::pipelines::kernel::FillInSLACAlignmentTerm(), cloudViewer::t::pipelines::slac::FillInSLACAlignmentTerm(), cloudViewer::t::pipelines::kernel::FillInSLACRegularizerTerm(), cloudViewer::t::geometry::npp::Filter(), cloudViewer::t::geometry::Image::Filter(), cloudViewer::t::geometry::ipp::Filter(), cloudViewer::t::geometry::npp::FilterBilateral(), cloudViewer::t::geometry::Image::FilterBilateral(), cloudViewer::t::geometry::npp::FilterGaussian(), cloudViewer::t::geometry::Image::FilterGaussian(), cloudViewer::t::geometry::npp::FilterSobel(), cloudViewer::t::geometry::Image::FilterSobel(), cloudViewer::core::nns::FixedRadiusIndex::FixedRadiusIndex(), cloudViewer::t::geometry::TriangleMesh::FromLegacy(), cloudViewer::t::geometry::AxisAlignedBoundingBox::FromLegacy(), cloudViewer::t::geometry::Image::FromLegacy(), cloudViewer::t::geometry::LineSet::FromLegacy(), cloudViewer::t::geometry::OrientedBoundingBox::FromLegacy(), cloudViewer::t::io::NumpyArray::GetDtype(), cloudViewer::t::pipelines::slac::ControlGrid::GetInitPositions(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetPointIndicesWithinBoundingBox(), cloudViewer::t::geometry::OrientedBoundingBox::GetPointIndicesWithinBoundingBox(), cloudViewer::t::geometry::VoxelBlockGrid::GetVoxelCoordinatesAndFlattenedIndices(), cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU(), cloudViewer::core::Tensor::Inverse(), Inverse(), cloudViewer::core::Tensor::IsFinite(), cloudViewer::core::Tensor::IsInf(), cloudViewer::core::Tensor::IsNan(), LeastSquares(), cloudViewer::core::Tensor::LeastSquares(), cloudViewer::t::geometry::RaycastingScene::ListIntersections(), cloudViewer::core::Tensor::LU(), LU(), cloudViewer::core::Tensor::LUIpiv(), LUIpiv(), Matmul(), cloudViewer::core::Tensor::Mean(), cloudViewer::t::geometry::OrientedBoundingBox::OrientedBoundingBox(), cloudViewer::t::io::PackColorsToFloat(), cloudViewer::t::geometry::LineSet::PaintUniformColor(), cloudViewer::t::geometry::PointCloud::PaintUniformColor(), cloudViewer::t::pipelines::slac::ControlGrid::Parameterize(), cloudViewer::t::geometry::kernel::pcapartition::PCAPartition(), cloudViewer::t::pipelines::kernel::PoseToTransformation(), cloudViewer::t::geometry::TriangleMesh::ProjectImagesToAlbedo(), cloudViewer::t::geometry::PointCloud::ProjectToDepthImage(), cloudViewer::t::geometry::PointCloud::ProjectToRGBDImage(), cloudViewer::t::geometry::Image::PyrDownDepth(), cloudViewer::t::io::ReadPointCloudFromPLY(), cloudViewer::t::io::ReadPointCloudFromPTS(), cloudViewer::t::io::ReadPointCloudFromSPLAT(), cloudViewer::t::io::ReadPointCloudFromTXT(), cloudViewer::t::geometry::ipp::Remap(), cloudViewer::t::geometry::npp::Resize(), cloudViewer::t::geometry::Image::Resize(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScaleHybrid(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScaleIntensity(), cloudViewer::t::geometry::Image::RGBToGray(), cloudViewer::t::geometry::npp::RGBToGray(), cloudViewer::t::geometry::OrientedBoundingBox::Rotate(), cloudViewer::t::pipelines::kernel::RtToTransformation(), cloudViewer::t::pipelines::slac::RunRigidOptimizerForFragments(), cloudViewer::t::pipelines::slac::RunSLACOptimizerForFragments(), cloudViewer::t::geometry::TriangleMesh::SamplePointsUniformly(), cloudViewer::t::geometry::kernel::trianglemesh::SamplePointsUniformlyCPU(), cloudViewer::t::geometry::VoxelBlockGrid::Save(), cloudViewer::t::geometry::AxisAlignedBoundingBox::Scale(), cloudViewer::t::geometry::OrientedBoundingBox::Scale(), cloudViewer::t::geometry::OrientedBoundingBox::SetCenter(), cloudViewer::t::geometry::OrientedBoundingBox::SetExtent(), cloudViewer::t::geometry::AxisAlignedBoundingBox::SetMaxBound(), cloudViewer::io::rpc::SetMeshData(), cloudViewer::t::geometry::AxisAlignedBoundingBox::SetMinBound(), cloudViewer::t::io::SetPCDHeaderFieldTypeAndSizeFromDtype(), cloudViewer::t::geometry::OrientedBoundingBox::SetRotation(), cloudViewer::core::nns::NanoFlannIndex::SetTensorData(), cloudViewer::core::nns::KnnIndex::SetTensorData(), cloudViewer::core::nns::FixedRadiusIndex::SetTensorData(), cloudViewer::t::io::DepthNoiseSimulator::Simulate(), cloudViewer::t::geometry::TriangleMesh::SlicePlane(), Solve(), cloudViewer::core::Tensor::Solve(), cloudViewer::core::Tensor::SVD(), SVD(), cloudViewer::t::pipelines::slam::Model::SynthesizeModelFrame(), cloudViewer::visualization::rendering::TGaussianSplatBuffersBuilder::TGaussianSplatBuffersBuilder(), cloudViewer::visualization::rendering::TLineSetBuffersBuilder::TLineSetBuffersBuilder(), cloudViewer::visualization::rendering::TMeshBuffersBuilder::TMeshBuffersBuilder(), cloudViewer::t::geometry::Image::To(), cloudViewer::t::geometry::kernel::image::ToCPU(), cloudViewer::t::geometry::Image::ToLegacy(), cloudViewer::t::pipelines::slac::ControlGrid::Touch(), cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::TPointCloudBuffersBuilder(), cloudViewer::t::geometry::OrientedBoundingBox::Transform(), cloudViewer::t::pipelines::kernel::TransformationToPose(), cloudViewer::t::geometry::AxisAlignedBoundingBox::Translate(), cloudViewer::t::geometry::OrientedBoundingBox::Translate(), cloudViewer::core::kernel::UnaryEW(), cloudViewer::t::geometry::kernel::pointcloud::UnprojectCPU(), cloudViewer::t::pipelines::slac::UpdatePoses(), cloudViewer::t::geometry::PointCloud::VoxelDownSample(), cloudViewer::t::io::WritePCDData(), cloudViewer::t::io::WritePointCloudToPTS(), and cloudViewer::t::io::WritePointCloudToSPLAT().
Float64
const Dtype cloudViewer::core::Float64 = Dtype::Float64
Definition at line 43 of file Dtype.cpp.
Referenced by AddMM(), cloudViewer::io::rpc::ArrayToTensor(), cloudViewer::t::pipelines::registration::AssertInputMultiScaleICP(), cloudViewer::t::geometry::AxisAlignedBoundingBox::AxisAlignedBoundingBox(), cloudViewer::t::geometry::TriangleMesh::ClipPlane(), cloudViewer::t::geometry::PointCloud::ComputeBoundaryPoints(), cloudViewer::t::geometry::PointCloud::ComputeConvexHull(), cloudViewer::t::pipelines::kernel::ComputeInformationMatrix(), cloudViewer::t::pipelines::kernel::ComputeInformationMatrixCPU(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryInformationMatrix(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryInformationMatrixCPU(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultHybrid(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultIntensity(), cloudViewer::t::pipelines::kernel::odometry::ComputeOdometryResultPointToPlane(), cloudViewer::t::pipelines::kernel::ComputePosePointToPlane(), cloudViewer::t::pipelines::registration::ComputeRegistrationResult(), cloudViewer::t::pipelines::registration::TransformationEstimationPointToPoint::ComputeRMSE(), cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane::ComputeRMSE(), cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP::ComputeRMSE(), cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::ComputeRMSE(), cloudViewer::t::pipelines::kernel::ComputeRtPointToPoint(), cloudViewer::t::io::ConvertColorTensorToUint8(), cloudViewer::t::geometry::TriangleMesh::CreateBox(), cloudViewer::t::geometry::PointCloud::CreateFromDepthImage(), cloudViewer::t::geometry::AxisAlignedBoundingBox::CreateFromPoints(), cloudViewer::t::geometry::OrientedBoundingBox::CreateFromPoints(), cloudViewer::t::geometry::TriangleMesh::CreateIsosurfaces(), cloudViewer::t::geometry::RaycastingScene::CreateRaysPinhole(), cloudViewer::t::geometry::TriangleMesh::CreateText(), cloudViewer::t::geometry::kernel::image::CreateVertexMap(), cloudViewer::t::geometry::kernel::image::CreateVertexMapCPU(), cloudViewer::t::geometry::vtkutils::CreateVtkImageDataFromTensor(), cloudViewer::t::geometry::vtkutils::CreateVtkPointsFromTensor(), cloudViewer::t::pipelines::kernel::DecodeAndSolve6x6(), cloudViewer::core::Tensor::Det(), Det(), DLDataTypeToDtype(), cloudViewer::t::pipelines::registration::DoSingleScaleICPIterations(), cloudViewer::t::io::DtypeToChar(), DtypeToDLDataTypeCode(), cloudViewer::t::geometry::vtkutils::DtypeToVtkType(), cloudViewer::t::geometry::PointCloud::EstimateColorGradients(), cloudViewer::t::geometry::PointCloud::EstimateNormals(), cloudViewer::t::geometry::kernel::voxel_grid::EstimateRange(), cloudViewer::t::geometry::vtkutils::ExtrudeLinearPolyData(), cloudViewer::t::geometry::vtkutils::ExtrudeRotationPolyData(), cloudViewer::core::nns::FixedRadiusIndex::FixedRadiusIndex(), cloudViewer::t::geometry::TriangleMesh::FromLegacy(), cloudViewer::t::geometry::AxisAlignedBoundingBox::FromLegacy(), cloudViewer::t::geometry::LineSet::FromLegacy(), cloudViewer::t::geometry::OrientedBoundingBox::FromLegacy(), cloudViewer::t::geometry::PointCloud::FromLegacy(), cloudViewer::t::io::NumpyArray::GetDtype(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetMaxExtent(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetPointIndicesWithinBoundingBox(), cloudViewer::t::geometry::OrientedBoundingBox::GetPointIndicesWithinBoundingBox(), cloudViewer::t::geometry::TriangleMesh::GetSurfaceArea(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetXPercentage(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetYPercentage(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetZPercentage(), cloudViewer::core::Tensor::Inverse(), Inverse(), cloudViewer::t::geometry::InverseTransformation(), cloudViewer::core::Tensor::IsClose(), cloudViewer::core::Tensor::IsFinite(), cloudViewer::core::Tensor::IsInf(), cloudViewer::core::Tensor::IsNan(), LeastSquares(), cloudViewer::core::Tensor::LeastSquares(), cloudViewer::core::Tensor::LU(), LU(), cloudViewer::core::Tensor::LUIpiv(), LUIpiv(), Matmul(), cloudViewer::core::Tensor::Mean(), cloudViewer::t::pipelines::registration::MultiScaleICP(), cloudViewer::t::geometry::OrientedBoundingBox::OrientedBoundingBox(), cloudViewer::t::geometry::LineSet::PaintUniformColor(), cloudViewer::t::geometry::PointCloud::PaintUniformColor(), cloudViewer::t::geometry::kernel::pcapartition::PCAPartition(), cloudViewer::t::pipelines::kernel::PoseToTransformation(), cloudViewer::t::geometry::kernel::pointcloud::Project(), cloudViewer::t::io::ReadPointCloudFromXYZI(), cloudViewer::t::geometry::PointCloud::RemoveStatisticalOutliers(), cloudViewer::t::pipelines::odometry::RGBDOdometryMultiScale(), cloudViewer::t::geometry::OrientedBoundingBox::Rotate(), cloudViewer::t::pipelines::kernel::RtToTransformation(), cloudViewer::t::geometry::AxisAlignedBoundingBox::Scale(), cloudViewer::t::geometry::OrientedBoundingBox::Scale(), cloudViewer::t::geometry::PointCloud::SegmentPlane(), cloudViewer::t::geometry::OrientedBoundingBox::SetCenter(), cloudViewer::t::geometry::AxisAlignedBoundingBox::SetColor(), cloudViewer::t::geometry::OrientedBoundingBox::SetColor(), cloudViewer::t::geometry::OrientedBoundingBox::SetExtent(), cloudViewer::t::geometry::AxisAlignedBoundingBox::SetMaxBound(), cloudViewer::io::rpc::SetMeshData(), cloudViewer::t::geometry::AxisAlignedBoundingBox::SetMinBound(), cloudViewer::t::io::SetPCDHeaderFieldTypeAndSizeFromDtype(), cloudViewer::t::geometry::OrientedBoundingBox::SetRotation(), cloudViewer::core::nns::NanoFlannIndex::SetTensorData(), cloudViewer::core::nns::KnnIndex::SetTensorData(), cloudViewer::core::nns::FixedRadiusIndex::SetTensorData(), cloudViewer::t::geometry::TriangleMesh::SlicePlane(), Solve(), cloudViewer::core::Tensor::Solve(), cloudViewer::core::Tensor::SVD(), SVD(), cloudViewer::core::eigen_converter::TensorToEigenVectorNxVector(), cloudViewer::t::geometry::Image::To(), cloudViewer::t::geometry::kernel::image::ToCPU(), cloudViewer::t::geometry::PointCloud::ToLegacy(), cloudViewer::t::pipelines::slam::Model::TrackFrameToModel(), cloudViewer::t::geometry::OrientedBoundingBox::Transform(), cloudViewer::t::pipelines::kernel::TransformationToPose(), cloudViewer::t::geometry::kernel::TransformIndexer::TransformIndexer(), cloudViewer::t::geometry::AxisAlignedBoundingBox::Translate(), cloudViewer::t::geometry::OrientedBoundingBox::Translate(), cloudViewer::core::kernel::UnaryEW(), cloudViewer::t::geometry::kernel::pointcloud::Unproject(), cloudViewer::t::geometry::AxisAlignedBoundingBox::Volume(), and cloudViewer::t::geometry::OrientedBoundingBox::Volume().
Int16
const Dtype cloudViewer::core::Int16 = Dtype::Int16
Definition at line 45 of file Dtype.cpp.
Referenced by cloudViewer::io::rpc::ArrayToTensor(), DLDataTypeToDtype(), cloudViewer::t::io::DtypeToChar(), DtypeToDLDataTypeCode(), cloudViewer::t::geometry::vtkutils::DtypeToVtkType(), cloudViewer::t::geometry::Image::FilterSobel(), cloudViewer::t::io::NumpyArray::GetDtype(), cloudViewer::t::io::SetPCDHeaderFieldTypeAndSizeFromDtype(), and cloudViewer::t::geometry::kernel::image::ToCPU().
Int32
const Dtype cloudViewer::core::Int32 = Dtype::Int32
Definition at line 46 of file Dtype.cpp.
Referenced by cloudViewer::io::rpc::ArrayToTensor(), cloudViewer::t::geometry::BufferRadiusNeighbors(), cloudViewer::t::geometry::TriangleMesh::ClipPlane(), cloudViewer::t::geometry::PointCloud::ComputeBoundaryPoints(), cloudViewer::t::geometry::PointCloud::ComputeConvexHull(), cloudViewer::t::pipelines::kernel::ComputeFPFHFeature(), cloudViewer::t::pipelines::registration::ComputeFPFHFeature(), cloudViewer::t::pipelines::slac::ControlGrid::ControlGrid(), cloudViewer::t::geometry::TriangleMesh::CreateBox(), cloudViewer::t::geometry::TriangleMesh::CreateText(), cloudViewer::t::geometry::vtkutils::CreateVtkCellArrayFromTensor(), cloudViewer::t::geometry::Image::Dilate(), DLDataTypeToDtype(), cloudViewer::t::io::DtypeToChar(), DtypeToDLDataTypeCode(), cloudViewer::t::geometry::vtkutils::DtypeToVtkType(), cloudViewer::core::StdGPUHashBackend< Key, Hash, Eq >::Erase(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingHybridSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingKNNSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingRadiusSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingHybridSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingKNNSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingRadiusSearchCPU(), cloudViewer::t::geometry::kernel::voxel_grid::EstimateRangeCPU(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractPointCloudCPU(), cloudViewer::t::geometry::VoxelBlockGrid::ExtractTriangleMesh(), cloudViewer::t::geometry::kernel::voxel_grid::ExtractTriangleMeshCPU(), cloudViewer::t::geometry::vtkutils::ExtrudeLinearPolyData(), cloudViewer::t::geometry::vtkutils::ExtrudeRotationPolyData(), cloudViewer::core::nns::FixedRadiusIndex::FixedRadiusIndex(), cloudViewer::t::geometry::TriangleMesh::FromLegacy(), cloudViewer::t::geometry::LineSet::FromLegacy(), GetColPermutation(), cloudViewer::t::io::NumpyArray::GetDtype(), cloudViewer::t::pipelines::slac::ControlGrid::GetNeighborGridMap(), cloudViewer::t::geometry::VoxelBlockGrid::GetUniqueBlockCoordinates(), Inverse(), cloudViewer::ml::contrib::KnnSearch(), LUIpiv(), cloudViewer::t::pipelines::slac::ControlGrid::Parameterize(), cloudViewer::t::geometry::kernel::pcapartition::PCAPartition(), cloudViewer::t::geometry::kernel::voxel_grid::PointCloudTouchCPU(), cloudViewer::core::HashMap::PrepareIndicesOutput(), cloudViewer::ml::contrib::RadiusSearch(), cloudViewer::t::geometry::PointCloud::RemoveDuplicatedPoints(), cloudViewer::t::geometry::VoxelBlockGrid::Save(), cloudViewer::io::rpc::SetMeshData(), cloudViewer::t::io::SetPCDHeaderFieldTypeAndSizeFromDtype(), cloudViewer::core::nns::NanoFlannIndex::SetTensorData(), cloudViewer::core::nns::KnnIndex::SetTensorData(), cloudViewer::core::nns::FixedRadiusIndex::SetTensorData(), cloudViewer::t::geometry::TriangleMesh::SlicePlane(), Solve(), cloudViewer::core::eigen_converter::TensorToEigenVectorNxVector(), cloudViewer::t::geometry::Image::To(), cloudViewer::t::geometry::kernel::image::ToCPU(), cloudViewer::t::pipelines::slac::ControlGrid::Touch(), cloudViewer::t::geometry::kernel::pointcloud::UnprojectCPU(), and cloudViewer::t::geometry::VoxelBlockGrid::VoxelBlockGrid().
Int64
const Dtype cloudViewer::core::Int64 = Dtype::Int64
Definition at line 47 of file Dtype.cpp.
Referenced by cloudViewer::core::Tensor::ArgMax(), cloudViewer::core::Tensor::ArgMin(), cloudViewer::io::rpc::ArrayToTensor(), cloudViewer::t::pipelines::registration::AssertValidCorrespondences(), cloudViewer::t::geometry::TriangleMesh::BakeTriangleAttrTextures(), cloudViewer::t::geometry::BufferRadiusNeighbors(), cloudViewer::t::geometry::TriangleMesh::ClipPlane(), cloudViewer::t::pipelines::slac::ControlGrid::Compactify(), cloudViewer::t::pipelines::kernel::ComputeFPFHFeature(), cloudViewer::t::pipelines::registration::ComputeFPFHFeature(), cloudViewer::t::pipelines::kernel::ComputeFPFHFeatureCPU(), cloudViewer::t::pipelines::registration::ComputeRegistrationResult(), cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP::ComputeRMSE(), cloudViewer::t::pipelines::kernel::ComputeRtPointToPoint(), cloudViewer::t::geometry::kernel::trianglemesh::ComputeTriangleAreasCPU(), cloudViewer::t::geometry::kernel::trianglemesh::ComputeTriangleNormalsCPU(), cloudViewer::t::geometry::kernel::uvunwrapping::ComputeUVAtlas(), cloudViewer::t::geometry::kernel::trianglemesh::ComputeVertexNormalsCPU(), cloudViewer::visualization::rendering::TMeshBuffersBuilder::ConstructBuffers(), cloudViewer::t::pipelines::slac::ConvertCorrespondencesTargetIndexedToCx2Form(), cloudViewer::t::geometry::TriangleMesh::CreateBox(), cloudViewer::t::geometry::TriangleMesh::CreateText(), cloudViewer::t::geometry::vtkutils::CreateVtkCellArrayFromTensor(), cloudViewer::t::pipelines::slac::ControlGrid::Deform(), DLDataTypeToDtype(), cloudViewer::t::io::DtypeToChar(), DtypeToDLDataTypeCode(), cloudViewer::t::geometry::vtkutils::DtypeToVtkType(), cloudViewer::t::geometry::VoxelBlockGrid::ExtractTriangleMesh(), cloudViewer::t::geometry::vtkutils::ExtrudeLinearPolyData(), cloudViewer::t::geometry::vtkutils::ExtrudeRotationPolyData(), cloudViewer::t::pipelines::kernel::FillInRigidAlignmentTermCPU(), cloudViewer::core::nns::FixedRadiusIndex::FixedRadiusIndex(), cloudViewer::t::geometry::TriangleMesh::FromLegacy(), cloudViewer::t::geometry::LineSet::FromLegacy(), GetColPermutation(), cloudViewer::t::pipelines::slac::GetCorrespondenceSetForPointCloudPair(), cloudViewer::t::io::NumpyArray::GetDtype(), cloudViewer::t::pipelines::registration::GetInformationMatrix(), cloudViewer::core::Tensor::GetItem(), cloudViewer::t::geometry::Image::GetMaxBound(), cloudViewer::t::geometry::RGBDImage::GetMaxBound(), cloudViewer::t::geometry::Image::GetMinBound(), cloudViewer::t::geometry::RGBDImage::GetMinBound(), cloudViewer::t::pipelines::slac::ControlGrid::GetNeighborGridMap(), cloudViewer::t::geometry::VoxelBlockGrid::GetVoxelCoordinates(), cloudViewer::t::geometry::VoxelBlockGrid::GetVoxelCoordinatesAndFlattenedIndices(), cloudViewer::t::geometry::VoxelBlockGrid::GetVoxelIndices(), cloudViewer::core::Tensor::IndexAdd_(), Inverse(), LUIpiv(), cloudViewer::core::kernel::NonZeroSYCL(), cloudViewer::t::pipelines::slac::ControlGrid::Parameterize(), cloudViewer::ml::contrib::RadiusSearch(), cloudViewer::t::geometry::PointCloud::RandomDownSample(), cloudViewer::t::geometry::PointCloud::RemoveDuplicatedPoints(), cloudViewer::t::geometry::TriangleMesh::RemoveUnreferencedVertices(), cloudViewer::core::HashMap::Reserve(), cloudViewer::core::AdvancedIndexPreprocessor::RunPreprocess(), cloudViewer::t::pipelines::slac::RunSLACOptimizerForFragments(), cloudViewer::t::geometry::VoxelBlockGrid::Save(), cloudViewer::core::nns::FixedRadiusIndex::SearchHybrid(), cloudViewer::core::nns::KnnIndex::SearchKnn(), cloudViewer::core::nns::NanoFlannIndex::SearchKnn(), cloudViewer::core::nns::NanoFlannIndex::SearchRadius(), cloudViewer::core::nns::FixedRadiusIndex::SearchRadius(), cloudViewer::t::geometry::PointCloud::SegmentPlane(), cloudViewer::t::geometry::TriangleMesh::SelectByIndex(), cloudViewer::t::geometry::PointCloud::SelectByIndex(), cloudViewer::core::Tensor::SetItem(), cloudViewer::io::rpc::SetMeshData(), cloudViewer::t::io::SetPCDHeaderFieldTypeAndSizeFromDtype(), cloudViewer::core::nns::NanoFlannIndex::SetTensorData(), cloudViewer::core::nns::KnnIndex::SetTensorData(), cloudViewer::core::nns::FixedRadiusIndex::SetTensorData(), cloudViewer::t::geometry::TriangleMesh::SlicePlane(), Solve(), cloudViewer::core::HashMap::To(), cloudViewer::t::geometry::kernel::image::ToCPU(), cloudViewer::t::pipelines::slac::VisualizePointCloudDeformation(), cloudViewer::t::pipelines::slac::VisualizePointCloudEmbedding(), cloudViewer::t::geometry::PointCloud::VoxelDownSample(), and cloudViewer::t::io::WriteHashMap().
Int8
const Dtype cloudViewer::core::Int8 = Dtype::Int8
Definition at line 44 of file Dtype.cpp.
Referenced by cloudViewer::io::rpc::ArrayToTensor(), DLDataTypeToDtype(), cloudViewer::t::io::DtypeToChar(), DtypeToDLDataTypeCode(), cloudViewer::t::geometry::vtkutils::DtypeToVtkType(), cloudViewer::t::io::NumpyArray::GetDtype(), cloudViewer::t::io::SetPCDHeaderFieldTypeAndSizeFromDtype(), and cloudViewer::t::geometry::kernel::image::ToCPU().
kBitmapsPerSuperBlock
constexpr uint32_t cloudViewer::core::kBitmapsPerSuperBlock static constexpr
Initial value:
=
        kBlocksPerSuperBlock * kSlabsPerBlock
Definition at line 52 of file SlabMacros.h.
kBlockMaskBits
constexpr uint32_t cloudViewer::core::kBlockMaskBits = 10 static constexpr
Definition at line 62 of file SlabMacros.h.
Referenced by cloudViewer::core::SlabNodeManagerImpl::WarpAllocate().
kBlocksPerSuperBlock
constexpr uint32_t cloudViewer::core::kBlocksPerSuperBlock = 4 static constexpr
Definition at line 38 of file SlabMacros.h.
Referenced by cloudViewer::core::SlabNodeManager::CountSlabsPerSuperblock(), and cloudViewer::core::SlabNodeManager::Reset().
kBlocksPerSuperBlockInBits
constexpr uint32_t cloudViewer::core::kBlocksPerSuperBlockInBits = 2 static constexpr
Definition at line 39 of file SlabMacros.h.
kEmptyNodeAddr
constexpr uint32_t cloudViewer::core::kEmptyNodeAddr = 0xFFFFFFFF static constexpr
Definition at line 73 of file SlabMacros.h.
Referenced by CountElemsPerBucketKernel(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Erase(), GetActiveIndicesKernel(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Insert(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::WarpFindEmpty(), and cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::WarpFindKey().
kEmptySlabAddr
constexpr uint32_t cloudViewer::core::kEmptySlabAddr = 0xFFFFFFFF static constexpr
Definition at line 72 of file SlabMacros.h.
Referenced by CountElemsPerBucketKernel(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Erase(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Find(), GetActiveIndicesKernel(), and cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Insert().
kHeadSlabAddr
constexpr uint32_t cloudViewer::core::kHeadSlabAddr = 0xFFFFFFFE static constexpr
Definition at line 70 of file SlabMacros.h.
Referenced by cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Erase(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Find(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Insert(), and cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::SlabEntryPtr().
kMaxKeyByteSize
constexpr uint32_t cloudViewer::core::kMaxKeyByteSize = 32 static constexpr
Definition at line 43 of file SlabMacros.h.
kNextSlabPtrLaneId
constexpr uint32_t cloudViewer::core::kNextSlabPtrLaneId = 31 static constexpr
Definition at line 68 of file SlabMacros.h.
Referenced by CountElemsPerBucketKernel(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Erase(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Find(), GetActiveIndicesKernel(), and cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Insert().
kNodePtrLanesMask
constexpr uint32_t cloudViewer::core::kNodePtrLanesMask = 0x7FFFFFFF static constexpr
Definition at line 67 of file SlabMacros.h.
Referenced by CountElemsPerBucketKernel(), GetActiveIndicesKernel(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::WarpFindEmpty(), and cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::WarpFindKey().
kNotFoundFlag
constexpr uint32_t cloudViewer::core::kNotFoundFlag = 0xFFFFFFFF static constexpr
Definition at line 76 of file SlabMacros.h.
Referenced by cloudViewer::core::SlabNodeManagerImpl::WarpAllocate().
kNullAddr
constexpr uint32_t cloudViewer::core::kNullAddr = 0xFFFFFFFF static constexpr
Definition at line 74 of file SlabMacros.h.
Referenced by cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Find().
kSlabMaskBits
constexpr uint32_t cloudViewer::core::kSlabMaskBits = 5 static constexpr
Definition at line 63 of file SlabMacros.h.
Referenced by cloudViewer::core::SlabNodeManagerImpl::WarpAllocate().
kSlabsPerBlock
constexpr uint32_t cloudViewer::core::kSlabsPerBlock = 1024 static constexpr
Definition at line 40 of file SlabMacros.h.
Referenced by cloudViewer::core::SlabNodeManagerImpl::FreeUntouched(), cloudViewer::core::SlabNodeManagerImpl::Init(), cloudViewer::core::SlabNodeManager::Reset(), and cloudViewer::core::SlabNodeManagerImpl::WarpAllocate().
kSuperBlockMaskBits
constexpr uint32_t cloudViewer::core::kSuperBlockMaskBits = 27 static constexpr
Definition at line 61 of file SlabMacros.h.
Referenced by cloudViewer::core::SlabNodeManagerImpl::WarpAllocate().
kSuperBlocks
constexpr uint32_t cloudViewer::core::kSuperBlocks = 32 static constexpr
Definition at line 37 of file SlabMacros.h.
Referenced by cloudViewer::core::SlabNodeManager::CountSlabsPerSuperblock(), cloudViewer::core::SlabNodeManager::Reset(), and cloudViewer::core::SlabNodeManager::SlabNodeManager().
kSyncLanesMask
constexpr uint32_t cloudViewer::core::kSyncLanesMask = 0xFFFFFFFF static constexpr
Definition at line 66 of file SlabMacros.h.
Referenced by CountElemsPerBucketKernel(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Erase(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Find(), GetActiveIndicesKernel(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Insert(), cloudViewer::core::SlabNodeManagerImpl::WarpAllocate(), and cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::WarpSyncKey().
kThreadsPerBlock
constexpr uint32_t cloudViewer::core::kThreadsPerBlock = 128 static constexpr
Definition at line 44 of file SlabMacros.h.
Referenced by cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::BucketSizes(), cloudViewer::core::SlabNodeManager::CountSlabsPerSuperblock(), cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::Erase(), cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::Find(), cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::GetActiveIndices(), and cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::Insert().
kUIntsPerBlock
constexpr uint32_t cloudViewer::core::kUIntsPerBlock = kSlabsPerBlock * kWarpSize static constexpr
Definition at line 49 of file SlabMacros.h.
kUIntsPerSuperBlock
constexpr uint32_t cloudViewer::core::kUIntsPerSuperBlock static constexpr
Initial value:
=
        kBlocksPerSuperBlock * kUIntsPerBlock + kBitmapsPerSuperBlock
Definition at line 54 of file SlabMacros.h.
Referenced by cloudViewer::core::SlabNodeManagerImpl::FreeUntouched(), cloudViewer::core::SlabNodeManagerImpl::get_ptr_for_bitmap(), cloudViewer::core::SlabNodeManagerImpl::Init(), cloudViewer::core::SlabNodeManager::Reset(), cloudViewer::core::SlabNodeManager::SlabNodeManager(), and cloudViewer::core::SlabNodeManagerImpl::WarpAllocate().
kWarpSize
constexpr uint32_t cloudViewer::core::kWarpSize = 32 static constexpr
Definition at line 31 of file SlabMacros.h.
Referenced by CountElemsPerBucketKernel(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Erase(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Find(), cloudViewer::core::SlabHashBackend< Key, Hash, Eq >::GetActiveIndices(), GetActiveIndicesKernel(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::Insert(), cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::SlabEntryPtrFromHead(), and cloudViewer::core::SlabHashBackendImpl< Key, Hash, Eq >::WarpSyncKey().
MAX_DIMS
constexpr int64_t cloudViewer::core::MAX_DIMS = 5 static constexpr
Definition at line 38 of file Indexer.h.
Referenced by cloudViewer::core::OffsetCalculator< NARGS, index_t >::get(), cloudViewer::core::Indexer::GetPerOutputIndexer(), cloudViewer::core::OffsetCalculator< NARGS, index_t >::OffsetCalculator(), and cloudViewer::core::TensorRef::TensorRef().
MAX_INPUTS
constexpr int64_t cloudViewer::core::MAX_INPUTS = 5 static constexpr
Definition at line 42 of file Indexer.h.
Referenced by cloudViewer::core::Indexer::Indexer().
MAX_OUTPUTS
constexpr int64_t cloudViewer::core::MAX_OUTPUTS = 2 static constexpr
Definition at line 46 of file Indexer.h.
Referenced by cloudViewer::core::Indexer::Indexer().
None
constexpr utility::nullopt_t cloudViewer::core::None {utility::nullopt_t::init()} constexpr
Definition at line 20 of file TensorKey.h.
Referenced by cloudViewer::t::geometry::TriangleMesh::BakeTriangleAttrTextures(), cloudViewer::t::geometry::TriangleMesh::BakeVertexAttrTextures(), cloudViewer::t::geometry::TriangleMesh::CreateIsosurfaces(), cloudViewer::t::geometry::CreatePointCloudWithNormals(), cloudViewer::t::geometry::vtkutils::CreateVtkCellArrayFromTensor(), cloudViewer::t::geometry::vtkutils::CreateVtkDataArrayFromTensor(), cloudViewer::t::geometry::vtkutils::CreateVtkPointsFromTensor(), cloudViewer::t::geometry::PointCloud::GaussianSplatGetSHOrder(), cloudViewer::core::Tensor::GetItem(), cloudViewer::t::pipelines::slac::ControlGrid::Parameterize(), cloudViewer::t::geometry::TriangleMesh::ProjectImagesToAlbedo(), cloudViewer::core::Tensor::SetItem(), and cloudViewer::t::io::WriteTriangleMeshUsingASSIMP().
UInt16
const Dtype cloudViewer::core::UInt16 = Dtype::UInt16
Definition at line 49 of file Dtype.cpp.
Referenced by cloudViewer::io::rpc::ArrayToTensor(), cloudViewer::t::geometry::CheckDepthTensor(), cloudViewer::t::geometry::Image::ClipTransform(), cloudViewer::t::geometry::Image::ColorizeDepth(), cloudViewer::t::geometry::npp::Dilate(), cloudViewer::t::geometry::Image::Dilate(), DLDataTypeToDtype(), cloudViewer::t::io::DtypeToChar(), DtypeToDLDataTypeCode(), cloudViewer::t::geometry::vtkutils::DtypeToVtkType(), cloudViewer::t::geometry::npp::Filter(), cloudViewer::t::geometry::Image::Filter(), cloudViewer::t::geometry::npp::FilterBilateral(), cloudViewer::t::geometry::Image::FilterBilateral(), cloudViewer::t::geometry::Image::FilterGaussian(), cloudViewer::t::geometry::Image::FromLegacy(), cloudViewer::t::io::RealSenseSensorConfig::get_dtype_channels(), cloudViewer::t::io::NumpyArray::GetDtype(), cloudViewer::t::io::RealSenseSensorConfig::GetPixelDtypes(), cloudViewer::t::io::ReadImageFromPNG(), cloudViewer::t::geometry::npp::Resize(), cloudViewer::t::geometry::Image::Resize(), cloudViewer::t::geometry::Image::RGBToGray(), cloudViewer::t::geometry::npp::RGBToGray(), cloudViewer::t::geometry::TriangleMesh::SamplePointsUniformly(), cloudViewer::t::io::SetPCDHeaderFieldTypeAndSizeFromDtype(), cloudViewer::t::io::SetPNGImageFromImage(), cloudViewer::t::io::DepthNoiseSimulator::Simulate(), cloudViewer::t::geometry::Image::To(), cloudViewer::t::geometry::kernel::image::ToCPU(), cloudViewer::t::geometry::Image::ToLegacy(), cloudViewer::t::io::WriteImageToPNG(), and cloudViewer::t::io::WriteImageToPNGInMemory().
UInt32
const Dtype cloudViewer::core::UInt32 = Dtype::UInt32
Definition at line 50 of file Dtype.cpp.
Referenced by cloudViewer::t::geometry::RaycastingScene::AddTriangles(), cloudViewer::io::rpc::ArrayToTensor(), cloudViewer::t::geometry::TriangleMesh::BakeVertexAttrTextures(), cloudViewer::t::geometry::RaycastingScene::CastRays(), cloudViewer::t::geometry::RaycastingScene::ComputeClosestPoints(), cloudViewer::visualization::rendering::TMeshBuffersBuilder::ConstructBuffers(), DLDataTypeToDtype(), cloudViewer::t::io::DtypeToChar(), DtypeToDLDataTypeCode(), cloudViewer::t::geometry::vtkutils::DtypeToVtkType(), cloudViewer::t::io::NumpyArray::GetDtype(), cloudViewer::core::HashBackendBuffer::HashBackendBuffer(), cloudViewer::t::geometry::RaycastingScene::ListIntersections(), cloudViewer::t::io::SetPCDHeaderFieldTypeAndSizeFromDtype(), cloudViewer::core::nns::FixedRadiusIndex::SetTensorData(), cloudViewer::visualization::rendering::TLineSetBuffersBuilder::TLineSetBuffersBuilder(), and cloudViewer::t::geometry::kernel::image::ToCPU().
UInt64
const Dtype cloudViewer::core::UInt64 = Dtype::UInt64
Definition at line 51 of file Dtype.cpp.
Referenced by cloudViewer::io::rpc::ArrayToTensor(), DLDataTypeToDtype(), cloudViewer::t::io::DtypeToChar(), DtypeToDLDataTypeCode(), cloudViewer::t::geometry::vtkutils::DtypeToVtkType(), cloudViewer::t::io::NumpyArray::GetDtype(), cloudViewer::t::io::SetPCDHeaderFieldTypeAndSizeFromDtype(), and cloudViewer::t::geometry::kernel::image::ToCPU().
UInt8
const Dtype cloudViewer::core::UInt8 = Dtype::UInt8
Definition at line 48 of file Dtype.cpp.
Referenced by cloudViewer::io::rpc::ArrayToTensor(), cloudViewer::t::geometry::CheckColorTensor(), cloudViewer::t::geometry::Image::ColorizeDepth(), cloudViewer::t::io::ConvertColorTensorToUint8(), cloudViewer::t::geometry::vtkutils::CreateVtkImageDataFromTensor(), cloudViewer::t::geometry::ipp::Dilate(), cloudViewer::t::geometry::npp::Dilate(), cloudViewer::t::geometry::Image::Dilate(), DLDataTypeToDtype(), cloudViewer::t::io::DtypeToChar(), DtypeToDLDataTypeCode(), cloudViewer::t::geometry::vtkutils::DtypeToVtkType(), cloudViewer::t::geometry::npp::Filter(), cloudViewer::t::geometry::Image::Filter(), cloudViewer::t::geometry::npp::FilterBilateral(), cloudViewer::t::geometry::Image::FilterBilateral(), cloudViewer::t::geometry::Image::FilterGaussian(), cloudViewer::t::geometry::npp::FilterSobel(), cloudViewer::t::geometry::Image::FilterSobel(), cloudViewer::t::geometry::Image::FromLegacy(), cloudViewer::t::io::RealSenseSensorConfig::get_dtype_channels(), cloudViewer::t::io::NumpyArray::GetDtype(), cloudViewer::t::io::RealSenseSensorConfig::GetPixelDtypes(), cloudViewer::t::geometry::TriangleMesh::ProjectImagesToAlbedo(), cloudViewer::t::io::ReadImageFromJPG(), cloudViewer::t::io::ReadImageFromPNG(), cloudViewer::t::io::ReadPCDData(), cloudViewer::t::io::ReadPointCloudFromPTS(), cloudViewer::visualization::rendering::FilamentRenderer::RequestReadPixels(), cloudViewer::t::geometry::npp::Resize(), cloudViewer::t::geometry::Image::Resize(), cloudViewer::t::geometry::Image::RGBToGray(), cloudViewer::t::geometry::npp::RGBToGray(), cloudViewer::t::geometry::TriangleMesh::SamplePointsUniformly(), cloudViewer::t::io::SetPCDHeaderFieldTypeAndSizeFromDtype(), cloudViewer::visualization::rendering::TLineSetBuffersBuilder::TLineSetBuffersBuilder(), cloudViewer::visualization::rendering::TMeshBuffersBuilder::TMeshBuffersBuilder(), cloudViewer::t::geometry::Image::To(), cloudViewer::t::geometry::kernel::image::ToCPU(), cloudViewer::t::geometry::Image::ToLegacy(), cloudViewer::visualization::rendering::TPointCloudBuffersBuilder::TPointCloudBuffersBuilder(), cloudViewer::t::io::WriteImageToJPG(), cloudViewer::t::io::WriteImageToPNG(), and cloudViewer::t::io::WriteImageToPNGInMemory().
Undefined
const Dtype cloudViewer::core::Undefined = Dtype::Undefined
Definition at line 41 of file Dtype.cpp.
Referenced by cloudViewer::io::rpc::ArrayToTensor(), DLDataTypeToDtype(), cloudViewer::t::io::NumpyArray::GetDtype(), cloudViewer::t::io::ReadPointCloudFromPLY(), and cloudViewer::t::geometry::TriangleMesh::SelectByIndex().