ACloudViewer: cloudViewer::core::sy Namespace Reference
cloudViewer::core::sy Namespace Reference
Classes
struct SYCLDevice
SYCL device properties.
class SYCLContext
Functions
CLOUDVIEWER_DLL_LOCAL std::string GetDeviceTypeName (const sycl::device &device)
int SYCLDemo ()
void PrintSYCLDevices (bool print_all)
bool IsAvailable ()
Returns true if there is at least one SYCL device available.
bool IsDeviceAvailable (const Device &device)
Returns true if the specified SYCL device is available.
std::string GetDeviceType (const Device &device)
std::vector< Device > GetAvailableSYCLDevices ()
Return a list of available SYCL devices.
void enablePersistentJITCache ()
size_t GetDeviceCount ()
Return the number of available SYCL devices.
Function Documentation
enablePersistentJITCache()
void cloudViewer::core::sy::enablePersistentJITCache ()
Enables the JIT cache for SYCL. This sets an environment variable and will affect the entire process and any child processes.
Definition at line 238 of file SYCLUtils.cpp.
References LogInfo.
GetAvailableSYCLDevices()
std::vector< Device > cloudViewer::core::sy::GetAvailableSYCLDevices ()
Return a list of available SYCL devices.
Definition at line 230 of file SYCLUtils.cpp.
References cloudViewer::core::sy::SYCLContext::GetAvailableSYCLDevices(), and cloudViewer::core::sy::SYCLContext::GetInstance().
Referenced by cloudViewer::core::Device::GetAvailableSYCLDevices(), and GetDeviceCount().
GetDeviceCount()
size_t cloudViewer::core::sy::GetDeviceCount () inline
Return the number of available SYCL devices.
Definition at line 48 of file SYCLUtils.h.
References GetAvailableSYCLDevices().
GetDeviceType()
std::string cloudViewer::core::sy::GetDeviceType (const Device & device)
Returns the device type (cpu / gpu / accelerator / custom) of the specified device as a string. Returns empty string if the device is not available.
Definition at line 216 of file SYCLUtils.cpp.
References cloudViewer::core::sy::SYCLDevice::device_type, cloudViewer::core::sy::SYCLContext::GetDeviceProperties(), cloudViewer::core::sy::SYCLContext::GetInstance(), and IsDeviceAvailable().
GetDeviceTypeName()
CLOUDVIEWER_DLL_LOCAL std::string cloudViewer::core::sy::GetDeviceTypeName (const sycl::device & device)
Referenced by cloudViewer::core::sy::SYCLDevice::SYCLDevice().
IsAvailable()
bool cloudViewer::core::sy::IsAvailable ()
Returns true if there is at least one SYCL device available.
Definition at line 200 of file SYCLUtils.cpp.
References cloudViewer::core::sy::SYCLContext::GetInstance(), and cloudViewer::core::sy::SYCLContext::IsAvailable().
IsDeviceAvailable()
bool cloudViewer::core::sy::IsDeviceAvailable (const Device & device)
Returns true if the specified SYCL device is available.
Definition at line 208 of file SYCLUtils.cpp.
References cloudViewer::core::sy::SYCLContext::GetInstance(), and cloudViewer::core::sy::SYCLContext::IsDeviceAvailable().
Referenced by GetDeviceType().
PrintSYCLDevices()
void cloudViewer::core::sy::PrintSYCLDevices (bool print_all = false)
Print available SYCL devices.
Parameters
print_all If true, prints all SYCL devices. Otherwise, prints only devices that are available for CloudViewer.
Definition at line 122 of file SYCLUtils.cpp.
References LogInfo, and LogWarning.
SYCLDemo()
int cloudViewer::core::sy::SYCLDemo ()
Runs simple SYCL test program for sanity checks.
Returns
Retuns 0 if successful.
Definition at line 34 of file SYCLUtils.cpp.
References LogInfo.