ACloudViewer: IoUtils Namespace Reference
IoUtils Namespace Reference
Functions
ccMaterialSet * createMaterialSetForMesh (const aiMesh *inMesh, const QString &inPath, const aiScene *inScene)
ccMesh * newCCMeshFromAIMesh (const aiMesh *inMesh)
ccGLMatrix convertMatrix (const aiMatrix4x4 &inAssimpMatrix)
QVariant convertMetaValueToVariant (aiMetadata *inData, unsigned int inValueIndex)
Function Documentation
convertMatrix()
ccGLMatrix IoUtils::convertMatrix (const aiMatrix4x4 & inAssimpMatrix)
Definition at line 424 of file IoUtils.cpp.
References OPENGL_MATRIX_SIZE.
convertMetaValueToVariant()
QVariant IoUtils::convertMetaValueToVariant (aiMetadata * inData, unsigned int inValueIndex)
Definition at line 440 of file IoUtils.cpp.
createMaterialSetForMesh()
ccMaterialSet * IoUtils::createMaterialSetForMesh (const aiMesh * inMesh, const QString & inPath, const aiScene * inScene)
Definition at line 122 of file IoUtils.cpp.
References ccMaterialSet::addMaterial(), ccMaterial::AMBIENT, ccMaterial::DIFFUSE, ccMaterial::DISPLACEMENT, ccMaterial::EMISSIVE, image, ccMaterial::METALLIC, ccMaterial::NORMAL, ccMaterial::OPACITY, CVLog::PrintDebug(), ccMaterial::REFLECTION, ccMaterial::ROUGHNESS, ccMaterial::SHININESS, ccMaterial::SPECULAR, CVTools::ToNativeSeparators(), and CVLog::Warning().
newCCMeshFromAIMesh()
ccMesh * IoUtils::newCCMeshFromAIMesh (const aiMesh * inMesh)
Definition at line 239 of file IoUtils.cpp.
References ccArray< Type, N, ComponentType >::addElement(), color, colors, face, ccArray< Type, N, ComponentType >::isAllocated(), name, normal, CVLog::Print(), e57::toString(), CVLog::Warning(), point::x, and point::y.