ACloudViewer: cloudViewer::t::pipelines Namespace Reference
cloudViewer::t::pipelines Namespace Reference
Namespaces
kernel
odometry
registration
slac
slam
Functions
void pybind_pipelines (py::module &m)
Function Documentation
pybind_pipelines()
void cloudViewer::t::pipelines::pybind_pipelines (py::module & m)
Definition at line 20 of file pipelines.cpp.
References cloudViewer::t::pipelines::odometry::pybind_odometry(), cloudViewer::t::pipelines::registration::pybind_registration(), cloudViewer::t::pipelines::slac::pybind_slac(), and cloudViewer::t::pipelines::slam::pybind_slam().
Referenced by cloudViewer::t::pybind_t().