ACloudViewer: pba::ProgramCU Namespace Reference
pba::ProgramCU Namespace Reference
Functions
int SetCudaDevice (int device)
size_t GetCudaMemoryCap ()
int CheckErrorCUDA (const char *location)
void FinishWorkCUDA ()
void ClearPreviousError ()
void ResetCurrentDevice ()
void ClearTextureObjectCache ()
void GetBlockConfiguration (unsigned int nblock, unsigned int &bw, unsigned int &bh)
void ComputeSQRT (CuTexImage &tex)
void ComputeRSQRT (CuTexImage &tex)
void ComputeVXY (CuTexImage &texX, CuTexImage &texY, CuTexImage &result, unsigned int part=0, unsigned int skip=0)
void ComputeSAXPY (float a, CuTexImage &texX, CuTexImage &texY, CuTexImage &result)
void ComputeSAX (float a, CuTexImage &texX, CuTexImage &result)
void ComputeSXYPZ (float a, CuTexImage &texX, CuTexImage &texY, CuTexImage &texZ, CuTexImage &result)
float ComputeVectorMax (CuTexImage &vector, CuTexImage &buf)
float ComputeVectorSum (CuTexImage &vector, CuTexImage &buf, int skip)
double ComputeVectorNorm (CuTexImage &vector, CuTexImage &buf)
double ComputeVectorNormW (CuTexImage &vector, CuTexImage &weight, CuTexImage &buf)
double ComputeVectorDot (CuTexImage &vector1, CuTexImage &vector2, CuTexImage &buf)
void UncompressCamera (int ncam, CuTexImage &camera0, CuTexImage &result)
void CompressCamera (int ncam, CuTexImage &camera0, CuTexImage &result)
void UpdateCameraPoint (int ncam, CuTexImage &camera, CuTexImage &point, CuTexImage &delta, CuTexImage &new_camera, CuTexImage &new_point, int mode=0)
void ComputeJacobian (CuTexImage &camera, CuTexImage &point, CuTexImage &jc, CuTexImage &jp, CuTexImage &proj_map, CuTexImage &sj, CuTexImage &meas, CuTexImage &cmlist, bool intrinsic_fixed, int radial_distortion, bool shuffle)
void ComputeProjection (CuTexImage &camera, CuTexImage &point, CuTexImage &meas, CuTexImage &proj_map, CuTexImage &proj, int radial)
void ComputeProjectionX (CuTexImage &camera, CuTexImage &point, CuTexImage &meas, CuTexImage &proj_map, CuTexImage &proj, int radial)
bool ShuffleCameraJacobian (CuTexImage &jc, CuTexImage &map, CuTexImage &result)
void ComputeDiagonal (CuTexImage &jc, CuTexImage &cmap, CuTexImage &jp, CuTexImage &pmap, CuTexImage &cmlist, CuTexImage &jtjd, CuTexImage &jtjdi, bool jc_transpose, int radial, bool add_existing_diagc)
void MultiplyBlockConditioner (int ncam, int npoint, CuTexImage &blocks, CuTexImage &vector, CuTexImage &result, int radial, int mode=0)
void ComputeProjectionQ (CuTexImage &camera, CuTexImage &qmap, CuTexImage &qw, CuTexImage &proj, int offset)
void ComputeJQX (CuTexImage &x, CuTexImage &qmap, CuTexImage &wq, CuTexImage &sj, CuTexImage &jx, int offset)
void ComputeJQtEC (CuTexImage &pe, CuTexImage &qlist, CuTexImage &wq, CuTexImage &sj, CuTexImage &result)
void ComputeDiagonalQ (CuTexImage &qlistw, CuTexImage &sj, CuTexImage &diag)
void ComputeJX (int point_offset, CuTexImage &x, CuTexImage &jc, CuTexImage &jp, CuTexImage &jmap, CuTexImage &result, int mode=0)
void ComputeJtE (CuTexImage &pe, CuTexImage &jc, CuTexImage &cmap, CuTexImage &cmlist, CuTexImage &jp, CuTexImage &pmap, CuTexImage &jte, bool jc_transpose, int mode=0)
void ComputeDiagonalBlock (float lambda, bool dampd, CuTexImage &jc, CuTexImage &cmap, CuTexImage &jp, CuTexImage &pmap, CuTexImage &cmlist, CuTexImage &diag, CuTexImage &blocks, int radial_distortion, bool jc_transpose, bool add_existing_diagc, int mode=0)
void ComputeJX_ (CuTexImage &x, CuTexImage &jx, CuTexImage &camera, CuTexImage &point, CuTexImage &meas, CuTexImage &pjmap, bool intrinsic_fixed, int radial_distortion, int mode=0)
void ComputeJtE_ (CuTexImage &e, CuTexImage &jte, CuTexImage &camera, CuTexImage &point, CuTexImage &meas, CuTexImage &cmap, CuTexImage &cmlist, CuTexImage &pmap, CuTexImage &jmap, CuTexImage &jp, bool intrinsic_fixed, int radial_distortion, int mode=0)
void ComputeDiagonalBlock_ (float lambda, bool dampd, CuTexImage &camera, CuTexImage &point, CuTexImage &meas, CuTexImage &cmap, CuTexImage &cmlist, CuTexImage &pmap, CuTexImage &jmap, CuTexImage &jp, CuTexImage &sj, CuTexImage &diag, CuTexImage &blocks, bool intrinsic_fixed, int radial_distortion, bool add_existing_diagc, int mode=0)
Function Documentation
CheckErrorCUDA()
int pba::ProgramCU::CheckErrorCUDA (const char * location)
ClearPreviousError()
void pba::ProgramCU::ClearPreviousError ()
Referenced by pba::SparseBundleCU::InitializeBundleGPU().
ClearTextureObjectCache()
void pba::ProgramCU::ClearTextureObjectCache ()
Referenced by pba::SparseBundleCU::ReleaseAllocatedData().
CompressCamera()
void pba::ProgramCU::CompressCamera (int ncam, CuTexImage & camera0, CuTexImage & result)
ComputeDiagonal()
void pba::ProgramCU::ComputeDiagonal (CuTexImage & jc, CuTexImage & cmap, CuTexImage & jp, CuTexImage & pmap, CuTexImage & cmlist, CuTexImage & jtjd, CuTexImage & jtjdi, bool jc_transpose, int radial, bool add_existing_diagc)
Referenced by pba::SparseBundleCU::ComputeDiagonal().
ComputeDiagonalBlock()
void pba::ProgramCU::ComputeDiagonalBlock (float lambda, bool dampd, CuTexImage & jc, CuTexImage & cmap, CuTexImage & jp, CuTexImage & pmap, CuTexImage & cmlist, CuTexImage & diag, CuTexImage & blocks, int radial_distortion, bool jc_transpose, bool add_existing_diagc, int mode = 0)
Referenced by pba::SparseBundleCU::ComputeBlockPC().
ComputeDiagonalBlock_()
void pba::ProgramCU::ComputeDiagonalBlock_ (float lambda, bool dampd, CuTexImage & camera, CuTexImage & point, CuTexImage & meas, CuTexImage & cmap, CuTexImage & cmlist, CuTexImage & pmap, CuTexImage & jmap, CuTexImage & jp, CuTexImage & sj, CuTexImage & diag, CuTexImage & blocks, bool intrinsic_fixed, int radial_distortion, bool add_existing_diagc, int mode = 0)
Referenced by pba::SparseBundleCU::ComputeBlockPC().
ComputeDiagonalQ()
void pba::ProgramCU::ComputeDiagonalQ (CuTexImage & qlistw, CuTexImage & sj, CuTexImage & diag)
Referenced by pba::SparseBundleCU::ComputeBlockPC(), and pba::SparseBundleCU::ComputeDiagonal().
ComputeJacobian()
void pba::ProgramCU::ComputeJacobian (CuTexImage & camera, CuTexImage & point, CuTexImage & jc, CuTexImage & jp, CuTexImage & proj_map, CuTexImage & sj, CuTexImage & meas, CuTexImage & cmlist, bool intrinsic_fixed, int radial_distortion, bool shuffle)
Referenced by pba::SparseBundleCU::EvaluateJacobians().
ComputeJQtEC()
void pba::ProgramCU::ComputeJQtEC (CuTexImage & pe, CuTexImage & qlist, CuTexImage & wq, CuTexImage & sj, CuTexImage & result)
Referenced by pba::SparseBundleCU::ComputeJtE().
ComputeJQX()
void pba::ProgramCU::ComputeJQX (CuTexImage & x, CuTexImage & qmap, CuTexImage & wq, CuTexImage & sj, CuTexImage & jx, int offset)
Referenced by pba::SparseBundleCU::ComputeJX().
ComputeJtE()
void pba::ProgramCU::ComputeJtE (CuTexImage & pe, CuTexImage & jc, CuTexImage & cmap, CuTexImage & cmlist, CuTexImage & jp, CuTexImage & pmap, CuTexImage & jte, bool jc_transpose, int mode = 0)
Referenced by pba::SparseBundleCU::ComputeJtE().
ComputeJtE_()
void pba::ProgramCU::ComputeJtE_ (CuTexImage & e, CuTexImage & jte, CuTexImage & camera, CuTexImage & point, CuTexImage & meas, CuTexImage & cmap, CuTexImage & cmlist, CuTexImage & pmap, CuTexImage & jmap, CuTexImage & jp, bool intrinsic_fixed, int radial_distortion, int mode = 0)
Referenced by pba::SparseBundleCU::ComputeJtE().
ComputeJX()
void pba::ProgramCU::ComputeJX (int point_offset, CuTexImage & x, CuTexImage & jc, CuTexImage & jp, CuTexImage & jmap, CuTexImage & result, int mode = 0)
Referenced by pba::SparseBundleCU::ComputeJX().
ComputeJX_()
void pba::ProgramCU::ComputeJX_ (CuTexImage & x, CuTexImage & jx, CuTexImage & camera, CuTexImage & point, CuTexImage & meas, CuTexImage & pjmap, bool intrinsic_fixed, int radial_distortion, int mode = 0)
Referenced by pba::SparseBundleCU::ComputeJX().
ComputeProjection()
void pba::ProgramCU::ComputeProjection (CuTexImage & camera, CuTexImage & point, CuTexImage & meas, CuTexImage & proj_map, CuTexImage & proj, int radial)
Referenced by pba::SparseBundleCU::EvaluateProjection().
ComputeProjectionQ()
void pba::ProgramCU::ComputeProjectionQ (CuTexImage & camera, CuTexImage & qmap, CuTexImage & qw, CuTexImage & proj, int offset)
Referenced by pba::SparseBundleCU::EvaluateProjection(), and pba::SparseBundleCU::EvaluateProjectionX().
ComputeProjectionX()
void pba::ProgramCU::ComputeProjectionX (CuTexImage & camera, CuTexImage & point, CuTexImage & meas, CuTexImage & proj_map, CuTexImage & proj, int radial)
Referenced by pba::SparseBundleCU::EvaluateProjectionX().
ComputeRSQRT()
void pba::ProgramCU::ComputeRSQRT (CuTexImage & tex)
Referenced by pba::SparseBundleCU::PrepareJacobianNormalization().
ComputeSAX()
void pba::ProgramCU::ComputeSAX (float a, CuTexImage & texX, CuTexImage & result)
Referenced by pba::SparseBundleCU::SolveNormalEquationPCGB(), and pba::SparseBundleCU::SolveNormalEquationPCGX().
ComputeSAXPY()
void pba::ProgramCU::ComputeSAXPY (float a, CuTexImage & texX, CuTexImage & texY, CuTexImage & result)
Referenced by pba::SparseBundleCU::RunProfileSteps(), pba::SparseBundleCU::SolveNormalEquationPCGB(), and pba::SparseBundleCU::SolveNormalEquationPCGX().
ComputeSQRT()
void pba::ProgramCU::ComputeSQRT (CuTexImage & tex)
Referenced by pba::SparseBundleCU::PrepareJacobianNormalization().
ComputeSXYPZ()
void pba::ProgramCU::ComputeSXYPZ (float a, CuTexImage & texX, CuTexImage & texY, CuTexImage & texZ, CuTexImage & result)
Referenced by pba::SparseBundleCU::RunProfileSteps(), pba::SparseBundleCU::SolveNormalEquationPCGB(), and pba::SparseBundleCU::SolveNormalEquationPCGX().
ComputeVectorDot()
double pba::ProgramCU::ComputeVectorDot (CuTexImage & vector1, CuTexImage & vector2, CuTexImage & buf)
Referenced by pba::SparseBundleCU::RunProfileSteps(), pba::SparseBundleCU::RunTestIterationLM(), pba::SparseBundleCU::SaveUpdatedSystem(), pba::SparseBundleCU::SolveNormalEquationPCGB(), and pba::SparseBundleCU::SolveNormalEquationPCGX().
ComputeVectorMax()
float pba::ProgramCU::ComputeVectorMax (CuTexImage & vector, CuTexImage & buf)
Referenced by pba::SparseBundleCU::SaveBundleRecord().
ComputeVectorNorm()
double pba::ProgramCU::ComputeVectorNorm (CuTexImage & vector, CuTexImage & buf)
Referenced by pba::SparseBundleCU::EvaluateDeltaNorm(), pba::SparseBundleCU::EvaluateProjection(), pba::SparseBundleCU::EvaluateProjectionX(), pba::SparseBundleCU::RunProfileSteps(), pba::SparseBundleCU::RunTestIterationLM(), pba::SparseBundleCU::SaveBundleRecord(), pba::SparseBundleCU::SaveUpdatedSystem(), pba::SparseBundleCU::SolveNormalEquationPCGB(), and pba::SparseBundleCU::SolveNormalEquationPCGX().
ComputeVectorNormW()
double pba::ProgramCU::ComputeVectorNormW (CuTexImage & vector, CuTexImage & weight, CuTexImage & buf)
Referenced by pba::SparseBundleCU::RunProfileSteps(), pba::SparseBundleCU::SaveUpdatedSystem(), pba::SparseBundleCU::SolveNormalEquationPCGB(), and pba::SparseBundleCU::SolveNormalEquationPCGX().
ComputeVectorSum()
float pba::ProgramCU::ComputeVectorSum (CuTexImage & vector, CuTexImage & buf, int skip)
ComputeVXY()
void pba::ProgramCU::ComputeVXY (CuTexImage & texX, CuTexImage & texY, CuTexImage & result, unsigned int part = 0, unsigned int skip = 0)
Referenced by pba::SparseBundleCU::ComputeJtE(), pba::SparseBundleCU::ComputeJX(), and pba::SparseBundleCU::UpdateCameraPoint().
FinishWorkCUDA()
void pba::ProgramCU::FinishWorkCUDA ()
Referenced by pba::SparseBundleCU::RunProfileSteps().
GetBlockConfiguration()
void pba::ProgramCU::GetBlockConfiguration (unsigned int nblock, unsigned int & bw, unsigned int & bh)
GetCudaMemoryCap()
size_t pba::ProgramCU::GetCudaMemoryCap ()
Referenced by pba::SparseBundleCU::CheckRequiredMem(), and pba::SparseBundleCU::GetMemCapacity().
MultiplyBlockConditioner()
void pba::ProgramCU::MultiplyBlockConditioner (int ncam, int npoint, CuTexImage & blocks, CuTexImage & vector, CuTexImage & result, int radial, int mode = 0)
Referenced by pba::SparseBundleCU::ApplyBlockPC().
ResetCurrentDevice()
void pba::ProgramCU::ResetCurrentDevice ()
Referenced by pba::SparseBundleCU::ReleaseAllocatedData().
SetCudaDevice()
int pba::ProgramCU::SetCudaDevice (int device)
Referenced by pba::SparseBundleCU::GetMemCapacity(), pba::SparseBundleCU::InitializeBundle(), and pba::SparseBundleCU::WarmupDevice().
ShuffleCameraJacobian()
bool pba::ProgramCU::ShuffleCameraJacobian (CuTexImage & jc, CuTexImage & map, CuTexImage & result)
Referenced by pba::SparseBundleCU::EvaluateJacobians(), and pba::SparseBundleCU::RunProfileSteps().
UncompressCamera()
void pba::ProgramCU::UncompressCamera (int ncam, CuTexImage & camera0, CuTexImage & result)
UpdateCameraPoint()
void pba::ProgramCU::UpdateCameraPoint (int ncam, CuTexImage & camera, CuTexImage & point, CuTexImage & delta, CuTexImage & new_camera, CuTexImage & new_point, int mode = 0)
Referenced by pba::SparseBundleCU::UpdateCameraPoint().