ACloudViewer: cloudViewer::t::geometry::ipp Namespace Reference
cloudViewer::t::geometry::ipp Namespace Reference
Functions
void To (const core::Tensor &src_im, core::Tensor &dst_im, double scale, double offset)
void RGBToGray (const core::Tensor &src_im, core::Tensor &dst_im)
void Resize (const core::Tensor &src_im, core::Tensor &dst_im, Image::InterpType interp_type)
void Dilate (const core::Tensor &src_im, core::Tensor &dst_im, int kernel_size)
void Filter (const core::Tensor &src_im, core::Tensor &dst_im, const core::Tensor &kernel)
void FilterBilateral (const core::Tensor &src_im, core::Tensor &dst_im, int kernel_size, float value_sigma, float distance_sigma)
void FilterGaussian (const core::Tensor &src_im, core::Tensor &dst_im, int kernel_size, float sigma)
void FilterSobel (const core::Tensor &src_im, core::Tensor &dst_im_dx, core::Tensor &dst_im_dy, int kernel_size)
void Remap (const core::Tensor &src_im, const core::Tensor &dst2src_xmap, const core::Tensor &dst2src_ymap, core::Tensor &dst_im, Image::InterpType interp_type)
Function Documentation
Dilate()
void cloudViewer::t::geometry::ipp::Dilate (const core::Tensor & src_im, core::Tensor & dst_im, int kernel_size)
Definition at line 133 of file IPPImage.cpp.
References cloudViewer::core::Dtype::ByteSize(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::GetStride(), LogError, cloudViewer::core::Tensor::Ones(), and cloudViewer::core::UInt8.
Referenced by cloudViewer::t::geometry::Image::Dilate().
Filter()
void cloudViewer::t::geometry::ipp::Filter (const core::Tensor & src_im, core::Tensor & dst_im, const core::Tensor & kernel)
Definition at line 170 of file IPPImage.cpp.
References cloudViewer::core::Dtype::ByteSize(), cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::GetStride(), and LogError.
Referenced by cloudViewer::t::geometry::Image::Filter().
FilterBilateral()
void cloudViewer::t::geometry::ipp::FilterBilateral (const core::Tensor & src_im, core::Tensor & dst_im, int kernel_size, float value_sigma, float distance_sigma)
Definition at line 202 of file IPPImage.cpp.
References cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::GetStride(), and LogError.
Referenced by cloudViewer::t::geometry::Image::FilterBilateral().
FilterGaussian()
void cloudViewer::t::geometry::ipp::FilterGaussian (const core::Tensor & src_im, core::Tensor & dst_im, int kernel_size, float sigma)
Definition at line 233 of file IPPImage.cpp.
References cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::GetStride(), and LogError.
Referenced by cloudViewer::t::geometry::Image::FilterGaussian().
FilterSobel()
void cloudViewer::t::geometry::ipp::FilterSobel (const core::Tensor & src_im, core::Tensor & dst_im_dx, core::Tensor & dst_im_dy, int kernel_size)
Definition at line 261 of file IPPImage.cpp.
References cloudViewer::core::Dtype::ByteSize(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::GetStride(), LogError, and cloudViewer::core::Tensor::Neg_().
Referenced by cloudViewer::t::geometry::Image::FilterSobel().
Remap()
void cloudViewer::t::geometry::ipp::Remap (const core::Tensor & src_im, const core::Tensor & dst2src_xmap, const core::Tensor & dst2src_ymap, core::Tensor & dst_im, Image::InterpType interp_type)
Definition at line 311 of file IPPImage.cpp.
References cloudViewer::core::Dtype::ByteSize(), cloudViewer::t::geometry::Image::Cubic, cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::GetStride(), cloudViewer::t::geometry::Image::Lanczos, cloudViewer::t::geometry::Image::Linear, LogError, cloudViewer::t::geometry::Image::Nearest, and cloudViewer::core::Dtype::ToString().
Referenced by cloudViewer::t::geometry::TriangleMesh::ProjectImagesToAlbedo().
Resize()
void cloudViewer::t::geometry::ipp::Resize (const core::Tensor & src_im, core::Tensor & dst_im, Image::InterpType interp_type)
Definition at line 94 of file IPPImage.cpp.
References cloudViewer::t::geometry::Image::Cubic, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::GetStride(), cloudViewer::t::geometry::Image::Lanczos, cloudViewer::t::geometry::Image::Linear, LogError, cloudViewer::t::geometry::Image::Nearest, and cloudViewer::t::geometry::Image::Super.
Referenced by cloudViewer::t::geometry::Image::Resize().
RGBToGray()
void cloudViewer::t::geometry::ipp::RGBToGray (const core::Tensor & src_im, core::Tensor & dst_im)
Definition at line 71 of file IPPImage.cpp.
References cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::GetStride(), and LogError.
Referenced by cloudViewer::t::geometry::Image::RGBToGray().
To()
void cloudViewer::t::geometry::ipp::To (const core::Tensor & src_im, core::Tensor & dst_im, double scale, double offset)
Definition at line 42 of file IPPImage.cpp.
References cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::GetStride(), LogError, and offset.
Referenced by cloudViewer::t::geometry::Image::To().