ACloudViewer: cloudViewer::t::geometry Namespace Reference
cloudViewer::t::geometry Namespace Reference
Namespaces
ipp
kernel
npp
vtkutils
Classes
class AxisAlignedBoundingBox
A bounding box that is aligned along the coordinate axes and defined by the min_bound and max_bound.
class OrientedBoundingBox
A bounding box oriented along an arbitrary frame of reference.
class DrawableGeometry
Mix-in class for geometry types that can be visualized.
class Geometry
The base geometry class.
struct MetricParameters
Holder for various parameters required by metrics.
class Image
The Image class stores image with customizable rows, cols, channels, dtype and device.
class LineSet
A LineSet contains points and lines joining them and optionally attributes on the points and lines.
class PointCloud
A point cloud contains a list of 3D points.
class RaycastingScene
A scene class with basic ray casting and closest point queries.
class RGBDImage
RGBDImage A pair of color and depth images.
class TensorMap
class TriangleMesh
A triangle mesh contains vertices and triangles.
class VoxelBlockGrid
class PyGeometry
Typedefs
using dtype_channels_pairs = std::vector< std::pair< core::Dtype, int64_t > >
Enumerations
enum class Metric { ChamferDistance , HausdorffDistance , FScore }
Metrics for comparing point clouds and triangle meshes.
enum class MethodOBBCreate { PCA , MINIMAL_APPROX , MINIMAL_JYLANKI }
Functions
core::Tensor ComputeMetricsCommon (core::Tensor distance12, core::Tensor distance21, std::vector< Metric > metrics, MetricParameters params)
static PointCloud CreatePointCloudWithNormals (const Image &depth_in, const Image &color_in, const core::Tensor &intrinsics_in, const core::Tensor &extrinsics, float depth_scale, float depth_max, int stride)
static core::Tensor ComputeTriangleAreasHelper (const TriangleMesh &mesh)
template<typename T >
static void UpdateTriangleIndicesByVertexMask (core::Tensor &tris_cpu, const core::Tensor &vertex_mask)
static void CopyAttributesByMasks (TriangleMesh &dst, const TriangleMesh &src, const core::Tensor &vertex_mask, const core::Tensor &tri_mask)
template<typename T , typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value &&std::is_signed< T >::value, T >::type * = nullptr>
static bool IsNegative (T val)
brief Static negative checker for signed integer types
template<typename T >
static Edge< T > GetOrderedEdge (T vidx0, T vidx1)
brief Helper function to get an edge with ordered vertex indices.
template<typename T >
static std::unordered_map< Edge< T >, std::vector< size_t >, utility::hash_tuple< Edge< T > > > GetEdgeToTrianglesMap (const core::Tensor &tris_cpu)
void CheckDepthTensor (const core::Tensor &depth)
void CheckColorTensor (const core::Tensor &color)
void CheckIntrinsicTensor (const core::Tensor &intrinsic)
void CheckExtrinsicTensor (const core::Tensor &extrinsic)
void CheckBlockCoordinates (const core::Tensor &block_coords)
core::Tensor InverseTransformation (const core::Tensor &T)
TODO(wei): find a proper place for such functionalities.
static std::pair< core::Tensor, core::Tensor > BufferRadiusNeighbors (std::shared_ptr< core::HashMap > &hashmap, const core::Tensor &active_buf_indices)
static TensorMap ConstructTensorMap (const core::HashMap &block_hashmap, std::unordered_map< std::string, int > name_attr_map)
void FromLegacyPointCloud (benchmark::State &state, const core::Device &device)
void ToLegacyPointCloud (benchmark::State &state, const core::Device &device)
void LegacyVoxelDownSample (benchmark::State &state, float voxel_size)
void VoxelDownSample (benchmark::State &state, const core::Device &device, float voxel_size, const std::string &reduction)
void LegacyUniformDownSample (benchmark::State &state, size_t k)
void UniformDownSample (benchmark::State &state, const core::Device &device, size_t k)
void LegacyTransform (benchmark::State &state, const int no_use)
void Transform (benchmark::State &state, const core::Device &device)
void SelectByIndex (benchmark::State &state, bool remove_duplicates, const core::Device &device)
void LegacySelectByIndex (benchmark::State &state, const int no_use)
void EstimateNormals (benchmark::State &state, const core::Device &device, const core::Dtype &dtype, const double voxel_size, const utility::optional< int > max_nn, const utility::optional< double > radius)
void LegacyEstimateNormals (benchmark::State &state, const double voxel_size, const cloudViewer::geometry::KDTreeSearchParam &search_param)
void RemoveRadiusOutliers (benchmark::State &state, const core::Device &device, const int nb_points, const double search_radius)
void RemoveStatisticalOutliers (benchmark::State &state, const core::Device &device, const int nb_neighbors)
void ComputeBoundaryPoints (benchmark::State &state, const core::Device &device, const core::Dtype &dtype, const int max_nn, const double radius)
void LegacyRemoveStatisticalOutliers (benchmark::State &state, const int nb_neighbors)
void LegacyRemoveRadiusOutliers (benchmark::State &state, const int nb_points, const double search_radius)
void CropByAxisAlignedBox (benchmark::State &state, const core::Device &device)
void CropByOrientedBox (benchmark::State &state, const core::Device &device)
void LegacyCropByAxisAlignedBox (benchmark::State &state, const int no_use)
void LegacyCropByOrientedBox (benchmark::State &state, const int no_use)
Unit (benchmark::kMillisecond)
BENCHMARK_CAPTURE (VoxelDownSample, kReductionMean_0_01, core::Device("CPU:0"), 0.01, kReductionMean) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (VoxelDownSample, kReductionMean_0_02, core::Device("CPU:0"), 0.08, kReductionMean) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (VoxelDownSample, kReductionMean_0_04, core::Device("CPU:0"), 0.04, kReductionMean) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (VoxelDownSample, kReductionMean_0_08, core::Device("CPU:0"), 0.08, kReductionMean) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (VoxelDownSample, kReductionMean_0_16, core::Device("CPU:0"), 0.16, kReductionMean) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (VoxelDownSample, kReductionMean_0_32, core::Device("CPU:0"), 0.32, kReductionMean) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (SelectByIndex, CPU(remove duplicates), true, core::Device("CPU:0")) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (EstimateNormals, CPU F32 Hybrid[0.02|30|0.06], core::Device("CPU:0"), core::Float32, 0.02, 30, 0.06) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (EstimateNormals, CPU F64 Hybrid[0.02|30|0.06], core::Device("CPU:0"), core::Float64, 0.02, 30, 0.06) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (EstimateNormals, CPU F32 KNN[0.02|30], core::Device("CPU:0"), core::Float32, 0.02, 30, utility::nullopt) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (EstimateNormals, CPU F64 KNN[0.02|30], core::Device("CPU:0"), core::Float64, 0.02, 30, utility::nullopt) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (EstimateNormals, CPU F32 Radius[0.02|0.06], core::Device("CPU:0"), core::Float32, 0.02, utility::nullopt, 0.06) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (EstimateNormals, CPU F64 Radius[0.02|0.06], core::Device("CPU:0"), core::Float64, 0.02, utility::nullopt, 0.06) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (LegacyTransform, CPU, 1) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (LegacySelectByIndex, CPU, 1) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (LegacyEstimateNormals, Legacy Hybrid[0.02|30|0.06], 0.02, cloudViewer::geometry::KDTreeSearchParamHybrid(0.06, 30)) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (LegacyEstimateNormals, Legacy KNN[0.02|30], 0.02, cloudViewer::geometry::KDTreeSearchParamKNN(30)) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (LegacyEstimateNormals, Legacy Radius[0.02|0.06], 0.02, cloudViewer::geometry::KDTreeSearchParamRadius(0.06)) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (RemoveRadiusOutliers, CPU[50|0.05], core::Device("CPU:0"), 50, 0.03) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (ComputeBoundaryPoints, CPU Float32, core::Device("CPU:0"), core::Float32, 30, 0.02) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (ComputeBoundaryPoints, CPU Float64, core::Device("CPU:0"), core::Float64, 30, 0.02) -> Unit(benchmark::kMillisecond)
void IOWriteLegacyPointCloud (benchmark::State &state, const std::string &input_file_path, const std::string &output_file_path, const bool write_ascii, const bool write_compressed)
void IOReadLegacyPointCloud (benchmark::State &state, const std::string &input_file_path)
void IOWriteTensorPointCloud (benchmark::State &state, const std::string &input_file_path, const std::string &output_file_path, const bool write_ascii, const bool write_compressed)
void IOReadTensorPointCloud (benchmark::State &state, const std::string &input_file_path)
BENCHMARK_CAPTURE (IOWriteLegacyPointCloud, PCD_ASCII_UNCOMPRESSED, input_path_pcd, std::string("tensor_")+std::string(std::string("pcd_ascii")+std::string(".pcd")), true, false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadLegacyPointCloud, PCD_ASCII_UNCOMPRESSED, std::string("tensor_")+std::string(std::string("pcd_ascii")+std::string(".pcd"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteTensorPointCloud, PCD_ASCII_UNCOMPRESSED, input_path_pcd, std::string("legacy_")+std::string(std::string("pcd_ascii")+std::string(".pcd")), true, false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadTensorPointCloud, PCD_ASCII_UNCOMPRESSED, std::string("legacy_")+std::string(std::string("pcd_ascii")+std::string(".pcd"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteLegacyPointCloud, PCD_BINARY_UNCOMPRESSED, input_path_pcd, std::string("tensor_")+std::string(std::string("pcd_bin")+std::string(".pcd")), false, false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadLegacyPointCloud, PCD_BINARY_UNCOMPRESSED, std::string("tensor_")+std::string(std::string("pcd_bin")+std::string(".pcd"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteTensorPointCloud, PCD_BINARY_UNCOMPRESSED, input_path_pcd, std::string("legacy_")+std::string(std::string("pcd_bin")+std::string(".pcd")), false, false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadTensorPointCloud, PCD_BINARY_UNCOMPRESSED, std::string("legacy_")+std::string(std::string("pcd_bin")+std::string(".pcd"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteLegacyPointCloud, PCD_BINARY_COMPRESSED, input_path_pcd, std::string("tensor_")+std::string(std::string("pcd_bin_compressed")+std::string(".pcd")), false, true) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadLegacyPointCloud, PCD_BINARY_COMPRESSED, std::string("tensor_")+std::string(std::string("pcd_bin_compressed")+std::string(".pcd"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteTensorPointCloud, PCD_BINARY_COMPRESSED, input_path_pcd, std::string("legacy_")+std::string(std::string("pcd_bin_compressed")+std::string(".pcd")), false, true) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadTensorPointCloud, PCD_BINARY_COMPRESSED, std::string("legacy_")+std::string(std::string("pcd_bin_compressed")+std::string(".pcd"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteLegacyPointCloud, PLY_ASCII_UNCOMPRESSED, input_path_pcd, std::string("tensor_")+std::string(std::string("pcd_ascii")+std::string(".ply")), true, false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadLegacyPointCloud, PLY_ASCII_UNCOMPRESSED, std::string("tensor_")+std::string(std::string("pcd_ascii")+std::string(".ply"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteTensorPointCloud, PLY_ASCII_UNCOMPRESSED, input_path_pcd, std::string("legacy_")+std::string(std::string("pcd_ascii")+std::string(".ply")), true, false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadTensorPointCloud, PLY_ASCII_UNCOMPRESSED, std::string("legacy_")+std::string(std::string("pcd_ascii")+std::string(".ply"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteLegacyPointCloud, PLY_BINARY_UNCOMPRESSED, input_path_pcd, std::string("tensor_")+std::string(std::string("pcd_bin")+std::string(".ply")), false, false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadLegacyPointCloud, PLY_BINARY_UNCOMPRESSED, std::string("tensor_")+std::string(std::string("pcd_bin")+std::string(".ply"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteTensorPointCloud, PLY_BINARY_UNCOMPRESSED, input_path_pcd, std::string("legacy_")+std::string(std::string("pcd_bin")+std::string(".ply")), false, false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadTensorPointCloud, PLY_BINARY_UNCOMPRESSED, std::string("legacy_")+std::string(std::string("pcd_bin")+std::string(".ply"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteLegacyPointCloud, PLY_BINARY_COMPRESSED, input_path_pcd, std::string("tensor_")+std::string(std::string("pcd_bin_compressed")+std::string(".ply")), false, true) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadLegacyPointCloud, PLY_BINARY_COMPRESSED, std::string("tensor_")+std::string(std::string("pcd_bin_compressed")+std::string(".ply"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteTensorPointCloud, PLY_BINARY_COMPRESSED, input_path_pcd, std::string("legacy_")+std::string(std::string("pcd_bin_compressed")+std::string(".ply")), false, true) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadTensorPointCloud, PLY_BINARY_COMPRESSED, std::string("legacy_")+std::string(std::string("pcd_bin_compressed")+std::string(".ply"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteLegacyPointCloud, PTS_ASCII_UNCOMPRESSED, input_path_pcd, std::string("tensor_")+std::string(std::string("pcd_ascii")+std::string(".pts")), true, false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadLegacyPointCloud, PTS_ASCII_UNCOMPRESSED, std::string("tensor_")+std::string(std::string("pcd_ascii")+std::string(".pts"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteTensorPointCloud, PTS_ASCII_UNCOMPRESSED, input_path_pcd, std::string("legacy_")+std::string(std::string("pcd_ascii")+std::string(".pts")), true, false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadTensorPointCloud, PTS_ASCII_UNCOMPRESSED, std::string("legacy_")+std::string(std::string("pcd_ascii")+std::string(".pts"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteLegacyPointCloud, PTS_BINARY_UNCOMPRESSED, input_path_pcd, std::string("tensor_")+std::string(std::string("pcd_bin")+std::string(".pts")), false, false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadLegacyPointCloud, PTS_BINARY_UNCOMPRESSED, std::string("tensor_")+std::string(std::string("pcd_bin")+std::string(".pts"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteTensorPointCloud, PTS_BINARY_UNCOMPRESSED, input_path_pcd, std::string("legacy_")+std::string(std::string("pcd_bin")+std::string(".pts")), false, false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadTensorPointCloud, PTS_BINARY_UNCOMPRESSED, std::string("legacy_")+std::string(std::string("pcd_bin")+std::string(".pts"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteLegacyPointCloud, PTS_BINARY_COMPRESSED, input_path_pcd, std::string("tensor_")+std::string(std::string("pcd_bin_compressed")+std::string(".pts")), false, true) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadLegacyPointCloud, PTS_BINARY_COMPRESSED, std::string("tensor_")+std::string(std::string("pcd_bin_compressed")+std::string(".pts"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOWriteTensorPointCloud, PTS_BINARY_COMPRESSED, input_path_pcd, std::string("legacy_")+std::string(std::string("pcd_bin_compressed")+std::string(".pts")), false, true) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE (IOReadTensorPointCloud, PTS_BINARY_COMPRESSED, std::string("legacy_")+std::string(std::string("pcd_bin_compressed")+std::string(".pts"))) -> Unit(benchmark::kMillisecond)
void IOReadLegacyTriangleMesh (benchmark::State &state, const std::string &input_file_path)
void IOReadTensorTriangleMesh (benchmark::State &state, const std::string &input_file_path)
void pybind_boundingvolume (py::module &m)
void pybind_drawable_geometry (py::module &m)
void pybind_geometry_class (py::module &m)
void pybind_geometry (py::module &m)
void pybind_tensormap (py::module &m)
void pybind_pointcloud (py::module &m)
void pybind_lineset (py::module &m)
void pybind_trianglemesh (py::module &m)
void pybind_image (py::module &m)
void pybind_voxel_block_grid (py::module &m)
void pybind_raycasting_scene (py::module &m)
template<typename Map , typename holder_type = std::unique_ptr<Map>, typename... Args>
static py::class_< Map, holder_type > bind_tensor_map (py::handle scope, const std::string &name, Args &&...args)
Variables
data::PLYPointCloud pointcloud_ply
static const std::string path = pointcloud_ply.GetPath()
const std::string kReductionMean = "mean"
data::PLYPointCloud pointcloud_ply_data
static const std::string input_path_pcd = pointcloud_ply_data.GetPath()
data::KnotMesh knot_data
static const std::unordered_map< std::string, std::string > map_shared_argument_docstrings
static const std::unordered_map< std::string, std::string > map_shared_argument_docstrings
Typedef Documentation
dtype_channels_pairs
using cloudViewer::t::geometry::dtype_channels_pairs = typedef std::vector<std::pair<core::Dtype, int64_t> >
Definition at line 29 of file Image.cpp.
Enumeration Type Documentation
MethodOBBCreate
enum cloudViewer::t::geometry::MethodOBBCreate strong
Enumerator
PCA
Principal Component Analysis.
MINIMAL_APPROX
Minimal OBB approximation.
MINIMAL_JYLANKI
Minimal OBB by Jylanki.
Definition at line 118 of file Geometry.h.
Metric
enum cloudViewer::t::geometry::Metric strong
Metrics for comparing point clouds and triangle meshes.
Enumerator
ChamferDistance
Chamfer Distance.
HausdorffDistance
Hausdorff Distance.
FScore
F-Score.
Definition at line 96 of file Geometry.h.
Function Documentation
BENCHMARK_CAPTURE() [1/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (ComputeBoundaryPoints , CPU Float32, core::Device("CPU:0") , core::Float32 , 30 , 0. 02) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [2/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (ComputeBoundaryPoints , CPU Float64, core::Device("CPU:0") , core::Float64 , 30 , 0. 02) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [3/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (EstimateNormals , CPU F32 Hybrid[0.02|30|0.06], core::Device("CPU:0") , core::Float32 , 0. 02, 30 , 0. 06) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [4/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (EstimateNormals , CPU F32 KNN[0.02|30], core::Device("CPU:0") , core::Float32 , 0. 02, 30 , utility::nullopt) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [5/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (EstimateNormals , CPU F32 Radius[0.02|0.06], core::Device("CPU:0") , core::Float32 , 0. 02, utility::nullopt , 0. 06) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [6/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (EstimateNormals , CPU F64 Hybrid[0.02|30|0.06], core::Device("CPU:0") , core::Float64 , 0. 02, 30 , 0. 06) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [7/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (EstimateNormals , CPU F64 KNN[0.02|30], core::Device("CPU:0") , core::Float64 , 0. 02, 30 , utility::nullopt) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [8/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (EstimateNormals , CPU F64 Radius[0.02|0.06], core::Device("CPU:0") , core::Float64 , 0. 02, utility::nullopt , 0. 06) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [9/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadLegacyPointCloud , PCD_ASCII_UNCOMPRESSED , std::string("tensor_")+std::string(std::string("pcd_ascii")+std::string(".pcd"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [10/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadLegacyPointCloud , PCD_BINARY_COMPRESSED , std::string("tensor_")+std::string(std::string("pcd_bin_compressed")+std::string(".pcd"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [11/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadLegacyPointCloud , PCD_BINARY_UNCOMPRESSED , std::string("tensor_")+std::string(std::string("pcd_bin")+std::string(".pcd"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [12/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadLegacyPointCloud , PLY_ASCII_UNCOMPRESSED , std::string("tensor_")+std::string(std::string("pcd_ascii")+std::string(".ply"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [13/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadLegacyPointCloud , PLY_BINARY_COMPRESSED , std::string("tensor_")+std::string(std::string("pcd_bin_compressed")+std::string(".ply"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [14/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadLegacyPointCloud , PLY_BINARY_UNCOMPRESSED , std::string("tensor_")+std::string(std::string("pcd_bin")+std::string(".ply"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [15/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadLegacyPointCloud , PTS_ASCII_UNCOMPRESSED , std::string("tensor_")+std::string(std::string("pcd_ascii")+std::string(".pts"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [16/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadLegacyPointCloud , PTS_BINARY_COMPRESSED , std::string("tensor_")+std::string(std::string("pcd_bin_compressed")+std::string(".pts"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [17/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadLegacyPointCloud , PTS_BINARY_UNCOMPRESSED , std::string("tensor_")+std::string(std::string("pcd_bin")+std::string(".pts"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [18/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadTensorPointCloud , PCD_ASCII_UNCOMPRESSED , std::string("legacy_")+std::string(std::string("pcd_ascii")+std::string(".pcd"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [19/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadTensorPointCloud , PCD_BINARY_COMPRESSED , std::string("legacy_")+std::string(std::string("pcd_bin_compressed")+std::string(".pcd"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [20/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadTensorPointCloud , PCD_BINARY_UNCOMPRESSED , std::string("legacy_")+std::string(std::string("pcd_bin")+std::string(".pcd"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [21/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadTensorPointCloud , PLY_ASCII_UNCOMPRESSED , std::string("legacy_")+std::string(std::string("pcd_ascii")+std::string(".ply"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [22/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadTensorPointCloud , PLY_BINARY_COMPRESSED , std::string("legacy_")+std::string(std::string("pcd_bin_compressed")+std::string(".ply"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [23/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadTensorPointCloud , PLY_BINARY_UNCOMPRESSED , std::string("legacy_")+std::string(std::string("pcd_bin")+std::string(".ply"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [24/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadTensorPointCloud , PTS_ASCII_UNCOMPRESSED , std::string("legacy_")+std::string(std::string("pcd_ascii")+std::string(".pts"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [25/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadTensorPointCloud , PTS_BINARY_COMPRESSED , std::string("legacy_")+std::string(std::string("pcd_bin_compressed")+std::string(".pts"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [26/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOReadTensorPointCloud , PTS_BINARY_UNCOMPRESSED , std::string("legacy_")+std::string(std::string("pcd_bin")+std::string(".pts"))) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [27/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteLegacyPointCloud , PCD_ASCII_UNCOMPRESSED , input_path_pcd , std::string("tensor_")+std::string(std::string("pcd_ascii")+std::string(".pcd")) , true , false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [28/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteLegacyPointCloud , PCD_BINARY_COMPRESSED , input_path_pcd , std::string("tensor_")+std::string(std::string("pcd_bin_compressed")+std::string(".pcd")) , false , true) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [29/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteLegacyPointCloud , PCD_BINARY_UNCOMPRESSED , input_path_pcd , std::string("tensor_")+std::string(std::string("pcd_bin")+std::string(".pcd")) , false , false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [30/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteLegacyPointCloud , PLY_ASCII_UNCOMPRESSED , input_path_pcd , std::string("tensor_")+std::string(std::string("pcd_ascii")+std::string(".ply")) , true , false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [31/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteLegacyPointCloud , PLY_BINARY_COMPRESSED , input_path_pcd , std::string("tensor_")+std::string(std::string("pcd_bin_compressed")+std::string(".ply")) , false , true) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [32/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteLegacyPointCloud , PLY_BINARY_UNCOMPRESSED , input_path_pcd , std::string("tensor_")+std::string(std::string("pcd_bin")+std::string(".ply")) , false , false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [33/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteLegacyPointCloud , PTS_ASCII_UNCOMPRESSED , input_path_pcd , std::string("tensor_")+std::string(std::string("pcd_ascii")+std::string(".pts")) , true , false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [34/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteLegacyPointCloud , PTS_BINARY_COMPRESSED , input_path_pcd , std::string("tensor_")+std::string(std::string("pcd_bin_compressed")+std::string(".pts")) , false , true) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [35/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteLegacyPointCloud , PTS_BINARY_UNCOMPRESSED , input_path_pcd , std::string("tensor_")+std::string(std::string("pcd_bin")+std::string(".pts")) , false , false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [36/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteTensorPointCloud , PCD_ASCII_UNCOMPRESSED , input_path_pcd , std::string("legacy_")+std::string(std::string("pcd_ascii")+std::string(".pcd")) , true , false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [37/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteTensorPointCloud , PCD_BINARY_COMPRESSED , input_path_pcd , std::string("legacy_")+std::string(std::string("pcd_bin_compressed")+std::string(".pcd")) , false , true) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [38/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteTensorPointCloud , PCD_BINARY_UNCOMPRESSED , input_path_pcd , std::string("legacy_")+std::string(std::string("pcd_bin")+std::string(".pcd")) , false , false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [39/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteTensorPointCloud , PLY_ASCII_UNCOMPRESSED , input_path_pcd , std::string("legacy_")+std::string(std::string("pcd_ascii")+std::string(".ply")) , true , false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [40/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteTensorPointCloud , PLY_BINARY_COMPRESSED , input_path_pcd , std::string("legacy_")+std::string(std::string("pcd_bin_compressed")+std::string(".ply")) , false , true) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [41/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteTensorPointCloud , PLY_BINARY_UNCOMPRESSED , input_path_pcd , std::string("legacy_")+std::string(std::string("pcd_bin")+std::string(".ply")) , false , false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [42/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteTensorPointCloud , PTS_ASCII_UNCOMPRESSED , input_path_pcd , std::string("legacy_")+std::string(std::string("pcd_ascii")+std::string(".pts")) , true , false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [43/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteTensorPointCloud , PTS_BINARY_COMPRESSED , input_path_pcd , std::string("legacy_")+std::string(std::string("pcd_bin_compressed")+std::string(".pts")) , false , true) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [44/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (IOWriteTensorPointCloud , PTS_BINARY_UNCOMPRESSED , input_path_pcd , std::string("legacy_")+std::string(std::string("pcd_bin")+std::string(".pts")) , false , false) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [45/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (LegacyEstimateNormals , Legacy Hybrid[0.02|30|0.06], 0. 02, cloudViewer::geometry::KDTreeSearchParamHybrid(0.06, 30)) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [46/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (LegacyEstimateNormals , Legacy KNN[0.02|30], 0. 02, cloudViewer::geometry::KDTreeSearchParamKNN(30)) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [47/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (LegacyEstimateNormals , Legacy Radius[0.02|0.06], 0. 02, cloudViewer::geometry::KDTreeSearchParamRadius(0.06)) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [48/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (LegacySelectByIndex , CPU , 1) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [49/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (LegacyTransform , CPU , 1) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [50/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (RemoveRadiusOutliers , CPU [50|0.05], core::Device("CPU:0") , 50 , 0. 03) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [51/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (SelectByIndex , CPU(remove duplicates) , true , core::Device("CPU:0")) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [52/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (VoxelDownSample , kReductionMean_0_01 , core::Device("CPU:0") , 0. 01, kReductionMean) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [53/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (VoxelDownSample , kReductionMean_0_02 , core::Device("CPU:0") , 0. 08, kReductionMean) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [54/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (VoxelDownSample , kReductionMean_0_04 , core::Device("CPU:0") , 0. 04, kReductionMean) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [55/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (VoxelDownSample , kReductionMean_0_08 , core::Device("CPU:0") , 0. 08, kReductionMean) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [56/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (VoxelDownSample , kReductionMean_0_16 , core::Device("CPU:0") , 0. 16, kReductionMean) -> Unit(benchmark::kMillisecond)
BENCHMARK_CAPTURE() [57/57]
cloudViewer::t::geometry::BENCHMARK_CAPTURE (VoxelDownSample , kReductionMean_0_32 , core::Device("CPU:0") , 0. 32, kReductionMean) -> Unit(benchmark::kMillisecond)
bind_tensor_map()
template<typename Map , typename holder_type = std::unique_ptr<Map>, typename... Args> static py::class_<Map, holder_type> cloudViewer::t::geometry::bind_tensor_map (py::handle scope, const std::string & name, Args &&... args) static
Definition at line 24 of file tensormap.cpp.
References copy, count, format, cloudViewer::t::geometry::TensorMap::GetReservedKeys(), local, and name.
BufferRadiusNeighbors()
static std::pair<core::Tensor, core::Tensor> cloudViewer::t::geometry::BufferRadiusNeighbors (std::shared_ptr< core::HashMap > & hashmap, const core::Tensor & active_buf_indices) static
Definition at line 23 of file VoxelBlockGrid.cpp.
References cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::IndexGet(), cloudViewer::core::Int32, cloudViewer::core::Int64, cloudViewer::core::make_pair(), cloudViewer::core::Tensor::To(), and cloudViewer::core::Tensor::View().
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::ExtractPointCloud(), and cloudViewer::t::geometry::VoxelBlockGrid::ExtractTriangleMesh().
CheckBlockCoordinates()
void cloudViewer::t::geometry::CheckBlockCoordinates (const core::Tensor & block_coords) inline
Definition at line 69 of file Utility.h.
References cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Dtype::Int32, LogError, and cloudViewer::core::Dtype::ToString().
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::Integrate(), and cloudViewer::t::geometry::VoxelBlockGrid::RayCast().
CheckColorTensor()
void cloudViewer::t::geometry::CheckColorTensor (const core::Tensor & color) inline
Definition at line 27 of file Utility.h.
References color, cloudViewer::core::Float32, LogError, and cloudViewer::core::UInt8.
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::Integrate().
CheckDepthTensor()
void cloudViewer::t::geometry::CheckDepthTensor (const core::Tensor & depth) inline
Definition at line 17 of file Utility.h.
References cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDtype(), LogError, cloudViewer::core::Tensor::NumElements(), cloudViewer::core::Dtype::ToString(), and cloudViewer::core::UInt16.
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::GetUniqueBlockCoordinates(), and cloudViewer::t::geometry::VoxelBlockGrid::Integrate().
CheckExtrinsicTensor()
void cloudViewer::t::geometry::CheckExtrinsicTensor (const core::Tensor & extrinsic) inline
Definition at line 53 of file Utility.h.
References cloudViewer::core::Dtype::Float64, cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::IsContiguous(), LogError, and cloudViewer::core::Dtype::ToString().
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::GetUniqueBlockCoordinates(), cloudViewer::t::geometry::VoxelBlockGrid::Integrate(), and cloudViewer::t::geometry::VoxelBlockGrid::RayCast().
CheckIntrinsicTensor()
void cloudViewer::t::geometry::CheckIntrinsicTensor (const core::Tensor & intrinsic) inline
Definition at line 37 of file Utility.h.
References cloudViewer::core::Dtype::Float64, cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::IsContiguous(), LogError, and cloudViewer::core::Dtype::ToString().
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::GetUniqueBlockCoordinates(), cloudViewer::t::geometry::VoxelBlockGrid::Integrate(), and cloudViewer::t::geometry::VoxelBlockGrid::RayCast().
ComputeBoundaryPoints()
void cloudViewer::t::geometry::ComputeBoundaryPoints (benchmark::State & state, const core::Device & device, const core::Dtype & dtype, const int max_nn, const double radius)
Definition at line 256 of file PointCloud.cpp.
References cloudViewer::t::geometry::PointCloud::ComputeBoundaryPoints(), cloudViewer::t::geometry::PointCloud::GetPointNormals(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), path, pointcloud_ply, cloudViewer::t::io::ReadPointCloud(), cloudViewer::t::geometry::PointCloud::SetPointNormals(), cloudViewer::t::geometry::PointCloud::SetPointPositions(), cloudViewer::t::geometry::PointCloud::To(), and cloudViewer::core::Tensor::To().
ComputeMetricsCommon()
core::Tensor cloudViewer::t::geometry::ComputeMetricsCommon (core::Tensor distance12, core::Tensor distance21, std::vector< Metric > metrics, MetricParameters params)
Common code for computing geometry metrics from pairwise point distances. This function expects Euclidean distances as input and returns the requested metrics between point clouds / meshes.
Definition at line 16 of file Metrics.cpp.
References ChamferDistance, cloudViewer::core::Float32, FScore, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), HausdorffDistance, cloudViewer::core::Tensor::Item(), cloudViewer::core::Tensor::Max(), max(), cloudViewer::core::Tensor::NumElements(), params, and cloudViewer::core::Tensor::Reshape().
Referenced by cloudViewer::t::geometry::PointCloud::ComputeMetrics(), and cloudViewer::t::geometry::TriangleMesh::ComputeMetrics().
ComputeTriangleAreasHelper()
static core::Tensor cloudViewer::t::geometry::ComputeTriangleAreasHelper (const TriangleMesh & mesh) static
Definition at line 316 of file TriangleMesh.cpp.
References cloudViewer::t::geometry::kernel::trianglemesh::ComputeTriangleAreasCPU(), cloudViewer::core::Tensor::Contiguous(), CUDA_CALL, cloudViewer::t::geometry::TriangleMesh::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::TriangleMesh::GetTriangleIndices(), cloudViewer::t::geometry::TriangleMesh::GetVertexPositions(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), and LogError.
Referenced by cloudViewer::t::geometry::TriangleMesh::ComputeTriangleAreas(), and cloudViewer::t::geometry::TriangleMesh::GetSurfaceArea().
ConstructTensorMap()
static TensorMap cloudViewer::t::geometry::ConstructTensorMap (const core::HashMap & block_hashmap, std::unordered_map< std::string, int > name_attr_map) static
Definition at line 54 of file VoxelBlockGrid.cpp.
References cloudViewer::core::HashMap::GetValueTensor(), and name.
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::ExtractPointCloud(), cloudViewer::t::geometry::VoxelBlockGrid::ExtractTriangleMesh(), cloudViewer::t::geometry::VoxelBlockGrid::Integrate(), and cloudViewer::t::geometry::VoxelBlockGrid::RayCast().
CopyAttributesByMasks()
static void cloudViewer::t::geometry::CopyAttributesByMasks (TriangleMesh & dst, const TriangleMesh & src, const core::Tensor & vertex_mask, const core::Tensor & tri_mask) static
A helper to copy mesh attributes.
Parameters
dst destination mesh
src source mesh
vertex_mask vertex mask of the source mesh
tri_mask triangle mask of the source mesh
Definition at line 1153 of file TriangleMesh.cpp.
References cloudViewer::t::geometry::TriangleMesh::GetTriangleAttr(), cloudViewer::t::geometry::TriangleMesh::GetVertexAttr(), cloudViewer::t::geometry::TriangleMesh::HasTriangleAttr(), cloudViewer::t::geometry::TriangleMesh::HasTriangleIndices(), cloudViewer::t::geometry::TriangleMesh::HasVertexAttr(), cloudViewer::t::geometry::TriangleMesh::HasVertexPositions(), cloudViewer::t::geometry::TriangleMesh::SetTriangleAttr(), and cloudViewer::t::geometry::TriangleMesh::SetVertexAttr().
CreatePointCloudWithNormals()
static PointCloud cloudViewer::t::geometry::CreatePointCloudWithNormals (const Image & depth_in, const Image & color_in, const core::Tensor & intrinsics_in, const core::Tensor & extrinsics, float depth_scale, float depth_max, int stride) static
Definition at line 872 of file PointCloud.cpp.
References cloudViewer::core::Tensor::Add_(), cloudViewer::core::Tensor::AllClose(), cloudViewer::t::geometry::Image::ClipTransform(), color, cloudViewer::t::geometry::Image::GetCols(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::t::geometry::Image::GetRows(), cloudViewer::core::Tensor::Inverse(), cloudViewer::core::IsDevice::IsCUDA(), LogError, cloudViewer::core::Tensor::Matmul(), cloudViewer::core::None, cloudViewer::t::geometry::PointCloud::SetPointColors(), and stride.
Referenced by cloudViewer::t::geometry::PointCloud::CreateFromDepthImage(), and cloudViewer::t::geometry::PointCloud::CreateFromRGBDImage().
CropByAxisAlignedBox()
void cloudViewer::t::geometry::CropByAxisAlignedBox (benchmark::State & state, const core::Device & device)
Definition at line 308 of file PointCloud.cpp.
References cloudViewer::t::geometry::PointCloud::Crop(), path, cloudViewer::t::io::ReadPointCloud(), and cloudViewer::t::geometry::PointCloud::To().
CropByOrientedBox()
void cloudViewer::t::geometry::CropByOrientedBox (benchmark::State & state, const core::Device & device)
Definition at line 325 of file PointCloud.cpp.
References cloudViewer::t::geometry::PointCloud::Crop(), cloudViewer::core::Tensor::Eye(), cloudViewer::core::Float32, path, cloudViewer::t::io::ReadPointCloud(), and cloudViewer::t::geometry::PointCloud::To().
EstimateNormals()
void cloudViewer::t::geometry::EstimateNormals (benchmark::State & state, const core::Device & device, const core::Dtype & dtype, const double voxel_size, const utility::optional< int > max_nn, const utility::optional< double > radius)
Definition at line 186 of file PointCloud.cpp.
References cloudViewer::t::geometry::PointCloud::EstimateNormals(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), path, cloudViewer::t::io::ReadPointCloud(), cloudViewer::t::geometry::PointCloud::RemovePointAttr(), cloudViewer::t::geometry::PointCloud::SetPointPositions(), cloudViewer::t::geometry::PointCloud::To(), cloudViewer::core::Tensor::To(), and cloudViewer::t::geometry::PointCloud::VoxelDownSample().
FromLegacyPointCloud()
void cloudViewer::t::geometry::FromLegacyPointCloud (benchmark::State & state, const core::Device & device)
Definition at line 23 of file PointCloud.cpp.
References cloudViewer::core::Float32, cloudViewer::t::geometry::PointCloud::FromLegacy(), ccPointCloud::reserveThePointsTable(), ccPointCloud::reserveTheRGBTable(), ccPointCloud::resize(), and cloudViewer::core::cuda::Synchronize().
GetEdgeToTrianglesMap()
template<typename T > static std::unordered_map<Edge<T>, std::vector<size_t>, utility::hash_tuple<Edge<T> > > cloudViewer::t::geometry::GetEdgeToTrianglesMap (const core::Tensor & tris_cpu) static
Definition at line 1680 of file TriangleMesh.cpp.
References cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetLength(), and GetOrderedEdge().
GetOrderedEdge()
template<typename T > static Edge<T> cloudViewer::t::geometry::GetOrderedEdge (T vidx0, T vidx1) inline static
brief Helper function to get an edge with ordered vertex indices.
Definition at line 1672 of file TriangleMesh.cpp.
Referenced by GetEdgeToTrianglesMap().
InverseTransformation()
core::Tensor cloudViewer::t::geometry::InverseTransformation (const core::Tensor & T) inline
TODO(wei): find a proper place for such functionalities.
Definition at line 77 of file Utility.h.
References AssertTensorDevice, AssertTensorDtype, AssertTensorShape, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::IsContiguous(), and LogError.
Referenced by cloudViewer::t::geometry::kernel::voxel_grid::DepthTouchCPU(), cloudViewer::t::pipelines::slam::Model::Integrate(), cloudViewer::t::geometry::kernel::voxel_grid::RayCastCPU(), cloudViewer::t::pipelines::slam::Model::SynthesizeModelFrame(), and cloudViewer::t::geometry::kernel::pointcloud::UnprojectCPU().
IOReadLegacyPointCloud()
void cloudViewer::t::geometry::IOReadLegacyPointCloud (benchmark::State & state, const std::string & input_file_path)
Definition at line 53 of file PointCloudIO.cpp.
References cloudViewer::io::ReadPointCloud().
IOReadLegacyTriangleMesh()
void cloudViewer::t::geometry::IOReadLegacyTriangleMesh (benchmark::State & state, const std::string & input_file_path)
Definition at line 22 of file TriangleMeshIO.cpp.
References cloudViewer::io::ReadTriangleMesh().
IOReadTensorPointCloud()
void cloudViewer::t::geometry::IOReadTensorPointCloud (benchmark::State & state, const std::string & input_file_path)
Definition at line 85 of file PointCloudIO.cpp.
References cloudViewer::t::io::ReadPointCloud().
IOReadTensorTriangleMesh()
void cloudViewer::t::geometry::IOReadTensorTriangleMesh (benchmark::State & state, const std::string & input_file_path)
Definition at line 32 of file TriangleMeshIO.cpp.
References cloudViewer::t::io::ReadTriangleMesh().
IOWriteLegacyPointCloud()
void cloudViewer::t::geometry::IOWriteLegacyPointCloud (benchmark::State & state, const std::string & input_file_path, const std::string & output_file_path, const bool write_ascii, const bool write_compressed)
Definition at line 31 of file PointCloudIO.cpp.
References cloudViewer::io::ReadPointCloud(), write_ascii, and cloudViewer::io::WritePointCloud().
IOWriteTensorPointCloud()
void cloudViewer::t::geometry::IOWriteTensorPointCloud (benchmark::State & state, const std::string & input_file_path, const std::string & output_file_path, const bool write_ascii, const bool write_compressed)
Definition at line 65 of file PointCloudIO.cpp.
References cloudViewer::t::io::ReadPointCloud(), write_ascii, and cloudViewer::t::io::WritePointCloud().
IsNegative()
template<typename T , typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, bool >::value &&std::is_signed< T >::value, T >::type * = nullptr> static bool cloudViewer::t::geometry::IsNegative (T val) static
brief Static negative checker for signed integer types
brief Overloaded static negative checker for unsigned integer types. It unconditionally returns false, but we need it for template functions.
Definition at line 1232 of file TriangleMesh.cpp.
LegacyCropByAxisAlignedBox()
void cloudViewer::t::geometry::LegacyCropByAxisAlignedBox (benchmark::State & state, const int no_use)
Definition at line 343 of file PointCloud.cpp.
References ccPointCloud::Crop(), path, and cloudViewer::io::ReadPointCloud().
LegacyCropByOrientedBox()
void cloudViewer::t::geometry::LegacyCropByOrientedBox (benchmark::State & state, const int no_use)
Definition at line 358 of file PointCloud.cpp.
References ccPointCloud::Crop(), path, and cloudViewer::io::ReadPointCloud().
LegacyEstimateNormals()
void cloudViewer::t::geometry::LegacyEstimateNormals (benchmark::State & state, const double voxel_size, const cloudViewer::geometry::KDTreeSearchParam & search_param)
Definition at line 208 of file PointCloud.cpp.
References path, cloudViewer::io::ReadPointCloud(), and ccPointCloud::VoxelDownSample().
LegacyRemoveRadiusOutliers()
void cloudViewer::t::geometry::LegacyRemoveRadiusOutliers (benchmark::State & state, const int nb_points, const double search_radius)
Definition at line 292 of file PointCloud.cpp.
References path, cloudViewer::io::ReadPointCloud(), and ccPointCloud::VoxelDownSample().
LegacyRemoveStatisticalOutliers()
void cloudViewer::t::geometry::LegacyRemoveStatisticalOutliers (benchmark::State & state, const int nb_neighbors)
Definition at line 277 of file PointCloud.cpp.
References path, cloudViewer::io::ReadPointCloud(), and ccPointCloud::VoxelDownSample().
LegacySelectByIndex()
void cloudViewer::t::geometry::LegacySelectByIndex (benchmark::State & state, const int no_use)
Definition at line 170 of file PointCloud.cpp.
References path, cloudViewer::io::ReadPointCloud(), ccPointCloud::SelectByIndex(), and cloudViewer::PointCloudTpl< T >::size().
LegacyTransform()
void cloudViewer::t::geometry::LegacyTransform (benchmark::State & state, const int no_use)
Definition at line 112 of file PointCloud.cpp.
References path, cloudViewer::io::ReadPointCloud(), and ccPointCloud::Transform().
LegacyUniformDownSample()
void cloudViewer::t::geometry::LegacyUniformDownSample (benchmark::State & state, size_t k)
Definition at line 87 of file PointCloud.cpp.
References cloudViewer::io::CreatePointCloudFromFile(), and path.
LegacyVoxelDownSample()
void cloudViewer::t::geometry::LegacyVoxelDownSample (benchmark::State & state, float voxel_size)
Definition at line 61 of file PointCloud.cpp.
References cloudViewer::io::CreatePointCloudFromFile(), and path.
pybind_boundingvolume()
void cloudViewer::t::geometry::pybind_boundingvolume (py::module & m)
Definition at line 18 of file boundingvolume.cpp.
References cloudViewer::t::geometry::AxisAlignedBoundingBox::Clone(), cloudViewer::t::geometry::OrientedBoundingBox::Clone(), cloudViewer::t::geometry::OrientedBoundingBox::CreateFromAxisAlignedBoundingBox(), cloudViewer::t::geometry::AxisAlignedBoundingBox::CreateFromPoints(), cloudViewer::t::geometry::OrientedBoundingBox::CreateFromPoints(), cloudViewer::core::Float32, cloudViewer::t::geometry::AxisAlignedBoundingBox::FromLegacy(), cloudViewer::t::geometry::OrientedBoundingBox::FromLegacy(), cloudViewer::t::geometry::OrientedBoundingBox::GetAxisAlignedBoundingBox(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetBoxPoints(), cloudViewer::t::geometry::OrientedBoundingBox::GetBoxPoints(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetCenter(), cloudViewer::t::geometry::OrientedBoundingBox::GetCenter(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetColor(), cloudViewer::t::geometry::OrientedBoundingBox::GetColor(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetExtent(), cloudViewer::t::geometry::OrientedBoundingBox::GetExtent(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetHalfExtent(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetMaxBound(), cloudViewer::t::geometry::OrientedBoundingBox::GetMaxBound(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetMaxExtent(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetMinBound(), cloudViewer::t::geometry::OrientedBoundingBox::GetMinBound(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetOrientedBoundingBox(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetPointIndicesWithinBoundingBox(), cloudViewer::t::geometry::OrientedBoundingBox::GetPointIndicesWithinBoundingBox(), cloudViewer::t::geometry::OrientedBoundingBox::GetRotation(), MINIMAL_APPROX, cloudViewer::utility::nullopt, cloudViewer::t::geometry::OrientedBoundingBox::Rotate(), cloudViewer::t::geometry::AxisAlignedBoundingBox::Scale(), cloudViewer::t::geometry::OrientedBoundingBox::Scale(), cloudViewer::t::geometry::OrientedBoundingBox::SetCenter(), cloudViewer::t::geometry::AxisAlignedBoundingBox::SetColor(), cloudViewer::t::geometry::OrientedBoundingBox::SetColor(), cloudViewer::t::geometry::OrientedBoundingBox::SetExtent(), cloudViewer::t::geometry::AxisAlignedBoundingBox::SetMaxBound(), cloudViewer::t::geometry::AxisAlignedBoundingBox::SetMinBound(), cloudViewer::t::geometry::OrientedBoundingBox::SetRotation(), cloudViewer::t::geometry::AxisAlignedBoundingBox::To(), cloudViewer::t::geometry::OrientedBoundingBox::To(), cloudViewer::t::geometry::AxisAlignedBoundingBox::ToLegacy(), cloudViewer::t::geometry::OrientedBoundingBox::ToLegacy(), cloudViewer::t::geometry::OrientedBoundingBox::Transform(), cloudViewer::t::geometry::AxisAlignedBoundingBox::Translate(), cloudViewer::t::geometry::OrientedBoundingBox::Translate(), cloudViewer::t::geometry::AxisAlignedBoundingBox::Volume(), and cloudViewer::t::geometry::OrientedBoundingBox::Volume().
Referenced by pybind_geometry().
pybind_drawable_geometry()
void cloudViewer::t::geometry::pybind_drawable_geometry (py::module & m)
Definition at line 16 of file drawablegeometry.cpp.
References cloudViewer::t::geometry::DrawableGeometry::GetMaterial(), cloudViewer::t::geometry::DrawableGeometry::HasMaterial(), and cloudViewer::t::geometry::DrawableGeometry::SetMaterial().
Referenced by pybind_geometry().
pybind_geometry()
void cloudViewer::t::geometry::pybind_geometry (py::module & m)
Definition at line 43 of file geometry.cpp.
References ChamferDistance, FScore, HausdorffDistance, MINIMAL_APPROX, MINIMAL_JYLANKI, cloudViewer::t::geometry::MetricParameters::n_sampled_points, PCA, pybind_boundingvolume(), pybind_drawable_geometry(), pybind_geometry_class(), pybind_image(), pybind_lineset(), pybind_pointcloud(), pybind_raycasting_scene(), pybind_tensormap(), pybind_trianglemesh(), pybind_voxel_block_grid(), and cloudViewer::t::geometry::MetricParameters::ToString().
Referenced by cloudViewer::t::pybind_t().
pybind_geometry_class()
void cloudViewer::t::geometry::pybind_geometry_class (py::module & m)
Definition at line 24 of file geometry.cpp.
References cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::t::geometry::Geometry::Clear(), cloudViewer::t::geometry::Geometry::GetDevice(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), and cloudViewer::t::geometry::Geometry::IsEmpty().
Referenced by pybind_geometry().
pybind_image()
void cloudViewer::t::geometry::pybind_image (py::module & m)
Definition at line 56 of file image.cpp.
References cloudViewer::t::geometry::RGBDImage::aligned_, cloudViewer::t::geometry::RGBDImage::AreAligned(), cloudViewer::t::geometry::Image::AsTensor(), cloudViewer::core::Dtype::ByteSize(), cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::t::geometry::Image::Clear(), cloudViewer::t::geometry::RGBDImage::Clear(), cloudViewer::t::geometry::Image::ClipTransform(), cloudViewer::t::geometry::Image::Clone(), cloudViewer::t::geometry::RGBDImage::Clone(), cloudViewer::t::geometry::RGBDImage::color_, cloudViewer::t::geometry::Image::ColorizeDepth(), cloudViewer::t::geometry::Image::CreateNormalMap(), cloudViewer::t::geometry::Image::CreateVertexMap(), cloudViewer::t::geometry::Image::Cubic, cloudViewer::t::geometry::RGBDImage::depth_, cloudViewer::t::geometry::Image::Dilate(), cloudViewer::pybind_utils::DtypeToArrayFormat(), cloudViewer::t::geometry::Image::Filter(), cloudViewer::t::geometry::Image::FilterBilateral(), cloudViewer::t::geometry::Image::FilterGaussian(), cloudViewer::t::geometry::Image::FilterSobel(), cloudViewer::core::Float32, cloudViewer::t::geometry::Image::FromLegacy(), cloudViewer::t::geometry::Image::GetChannels(), cloudViewer::t::geometry::Image::GetCols(), cloudViewer::t::geometry::Image::GetDataPtr(), cloudViewer::t::geometry::Image::GetDevice(), cloudViewer::t::geometry::Image::GetDtype(), cloudViewer::t::geometry::Image::GetMaxBound(), cloudViewer::t::geometry::RGBDImage::GetMaxBound(), cloudViewer::t::geometry::Image::GetMinBound(), cloudViewer::t::geometry::RGBDImage::GetMinBound(), cloudViewer::t::geometry::Image::GetRows(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Tensor::GetStrides(), image, cloudViewer::core::IsDevice::IsCPU(), cloudViewer::t::geometry::Image::IsEmpty(), cloudViewer::t::geometry::RGBDImage::IsEmpty(), cloudViewer::t::geometry::Image::Lanczos, cloudViewer::t::geometry::Image::Linear, cloudViewer::t::geometry::Image::LinearTransform(), LogError, map_shared_argument_docstrings, cloudViewer::t::geometry::Image::Nearest, cloudViewer::core::Tensor::NumDims(), cloudViewer::t::geometry::Image::PyrDown(), cloudViewer::t::geometry::Image::Resize(), cloudViewer::t::geometry::Image::RGBToGray(), cloudViewer::core::SmallVectorBase< Size_T >::size(), cloudViewer::t::geometry::Image::Super, cloudViewer::t::geometry::Image::To(), cloudViewer::t::geometry::RGBDImage::To(), cloudViewer::t::geometry::Image::ToLegacy(), cloudViewer::t::geometry::RGBDImage::ToLegacy(), cloudViewer::t::geometry::Image::ToString(), and cloudViewer::t::geometry::RGBDImage::ToString().
Referenced by pybind_geometry().
pybind_lineset()
void cloudViewer::t::geometry::pybind_lineset (py::module & m)
Definition at line 20 of file lineset.cpp.
References cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::t::geometry::LineSet::Clone(), cloudViewer::t::geometry::LineSet::CreateCameraVisualization(), cloudViewer::t::geometry::LineSet::ExtrudeLinear(), cloudViewer::t::geometry::LineSet::ExtrudeRotation(), cloudViewer::core::Float32, cloudViewer::t::geometry::LineSet::FromLegacy(), cloudViewer::t::geometry::LineSet::GetAxisAlignedBoundingBox(), cloudViewer::t::geometry::LineSet::GetCenter(), cloudViewer::t::geometry::LineSet::GetLineAttr(), cloudViewer::t::geometry::LineSet::GetMaxBound(), cloudViewer::t::geometry::LineSet::GetMinBound(), cloudViewer::t::geometry::LineSet::GetOrientedBoundingBox(), cloudViewer::t::geometry::LineSet::GetPointAttr(), cloudViewer::core::Int64, cloudViewer::core::Device::IsAvailable(), LogError, LogWarning, cloudViewer::t::geometry::LineSet::PaintUniformColor(), cloudViewer::t::geometry::LineSet::Rotate(), cloudViewer::t::geometry::LineSet::Scale(), cloudViewer::t::geometry::LineSet::To(), cloudViewer::t::geometry::LineSet::ToLegacy(), cloudViewer::core::Device::ToString(), cloudViewer::t::geometry::LineSet::ToString(), cloudViewer::t::geometry::LineSet::Transform(), and cloudViewer::t::geometry::LineSet::Translate().
Referenced by pybind_geometry().
pybind_pointcloud()
void cloudViewer::t::geometry::pybind_pointcloud (py::module & m)
Definition at line 49 of file pointcloud.cpp.
References cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::t::geometry::PointCloud::Clone(), cloudViewer::t::geometry::PointCloud::ClusterDBSCAN(), cloudViewer::t::geometry::PointCloud::ComputeBoundaryPoints(), cloudViewer::t::geometry::PointCloud::ComputeConvexHull(), cloudViewer::t::geometry::PointCloud::ComputeMetrics(), cloudViewer::t::geometry::PointCloud::CreateFromDepthImage(), cloudViewer::t::geometry::PointCloud::CreateFromRGBDImage(), cloudViewer::t::geometry::PointCloud::Crop(), cloudViewer::t::geometry::PointCloud::EstimateColorGradients(), cloudViewer::t::geometry::PointCloud::EstimateNormals(), cloudViewer::t::geometry::PointCloud::ExtrudeLinear(), cloudViewer::t::geometry::PointCloud::ExtrudeRotation(), cloudViewer::core::Tensor::Eye(), cloudViewer::t::geometry::PointCloud::FarthestPointDownSample(), cloudViewer::core::Float32, cloudViewer::t::geometry::PointCloud::FromLegacy(), cloudViewer::t::geometry::PointCloud::GetAxisAlignedBoundingBox(), cloudViewer::t::geometry::PointCloud::GetCenter(), cloudViewer::t::geometry::PointCloud::GetDevice(), cloudViewer::t::geometry::PointCloud::GetMaxBound(), cloudViewer::t::geometry::PointCloud::GetMinBound(), cloudViewer::t::geometry::PointCloud::GetOrientedBoundingBox(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::HiddenPointRemoval(), cloudViewer::core::Device::IsAvailable(), LogError, LogWarning, map_shared_argument_docstrings, cloudViewer::t::geometry::PointCloud::NormalizeNormals(), cloudViewer::t::geometry::PointCloud::OrientNormalsConsistentTangentPlane(), cloudViewer::t::geometry::PointCloud::OrientNormalsToAlignWithDirection(), cloudViewer::t::geometry::PointCloud::OrientNormalsTowardsCameraLocation(), cloudViewer::t::geometry::PointCloud::PaintUniformColor(), cloudViewer::t::geometry::PointCloud::PCAPartition(), cloudViewer::t::geometry::PointCloud::ProjectToDepthImage(), cloudViewer::t::geometry::PointCloud::ProjectToRGBDImage(), cloudViewer::t::geometry::PointCloud::RandomDownSample(), cloudViewer::t::geometry::PointCloud::RemoveDuplicatedPoints(), cloudViewer::t::geometry::PointCloud::RemoveNonFinitePoints(), cloudViewer::t::geometry::PointCloud::RemoveRadiusOutliers(), cloudViewer::t::geometry::PointCloud::RemoveStatisticalOutliers(), cloudViewer::t::geometry::PointCloud::Rotate(), cloudViewer::t::geometry::PointCloud::Scale(), cloudViewer::t::geometry::PointCloud::SegmentPlane(), cloudViewer::t::geometry::PointCloud::SelectByIndex(), cloudViewer::t::geometry::PointCloud::SelectByMask(), cloudViewer::t::geometry::PointCloud::To(), cloudViewer::t::geometry::PointCloud::ToLegacy(), cloudViewer::core::Device::ToString(), cloudViewer::t::geometry::PointCloud::ToString(), cloudViewer::t::geometry::PointCloud::Transform(), cloudViewer::t::geometry::PointCloud::Translate(), cloudViewer::t::geometry::PointCloud::UniformDownSample(), and cloudViewer::core::Tensor::Zeros().
Referenced by pybind_geometry().
pybind_raycasting_scene()
void cloudViewer::t::geometry::pybind_raycasting_scene (py::module & m)
Definition at line 16 of file raycasting_scene.cpp.
References cloudViewer::t::geometry::RaycastingScene::AddTriangles(), cloudViewer::t::geometry::RaycastingScene::CastRays(), cloudViewer::t::geometry::RaycastingScene::ComputeClosestPoints(), cloudViewer::t::geometry::RaycastingScene::ComputeDistance(), cloudViewer::t::geometry::RaycastingScene::ComputeOccupancy(), cloudViewer::t::geometry::RaycastingScene::ComputeSignedDistance(), cloudViewer::t::geometry::RaycastingScene::CountIntersections(), cloudViewer::t::geometry::RaycastingScene::CreateRaysPinhole(), infinity(), cloudViewer::t::geometry::RaycastingScene::INVALID_ID(), cloudViewer::t::geometry::RaycastingScene::ListIntersections(), and cloudViewer::t::geometry::RaycastingScene::TestOcclusions().
Referenced by pybind_geometry().
pybind_tensormap()
void cloudViewer::t::geometry::pybind_tensormap (py::module & m)
Definition at line 119 of file tensormap.cpp.
References cloudViewer::t::geometry::TensorMap::AssertSizeSynchronized(), format, cloudViewer::t::geometry::TensorMap::GetPrimaryKey(), cloudViewer::t::geometry::TensorMap::GetReservedKeys(), cloudViewer::t::geometry::TensorMap::IsSizeSynchronized(), LogError, and cloudViewer::t::geometry::TensorMap::ToString().
Referenced by pybind_geometry().
pybind_trianglemesh()
void cloudViewer::t::geometry::pybind_trianglemesh (py::module & m)
Definition at line 25 of file trianglemesh.cpp.
References cloudViewer::t::geometry::TriangleMesh::BakeTriangleAttrTextures(), cloudViewer::t::geometry::TriangleMesh::BakeVertexAttrTextures(), cloudViewer::t::geometry::TriangleMesh::BooleanDifference(), cloudViewer::t::geometry::TriangleMesh::BooleanIntersection(), cloudViewer::t::geometry::TriangleMesh::BooleanUnion(), cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::t::geometry::TriangleMesh::ClipPlane(), cloudViewer::t::geometry::TriangleMesh::Clone(), cloudViewer::t::geometry::TriangleMesh::ComputeConvexHull(), cloudViewer::t::geometry::TriangleMesh::ComputeMetrics(), cloudViewer::t::geometry::TriangleMesh::ComputeTriangleAreas(), cloudViewer::t::geometry::TriangleMesh::ComputeTriangleNormals(), cloudViewer::t::geometry::TriangleMesh::ComputeUVAtlas(), cloudViewer::t::geometry::TriangleMesh::ComputeVertexNormals(), cloudViewer::t::geometry::TriangleMesh::CreateArrow(), cloudViewer::t::geometry::TriangleMesh::CreateBox(), cloudViewer::t::geometry::TriangleMesh::CreateCone(), cloudViewer::t::geometry::TriangleMesh::CreateCoordinateFrame(), cloudViewer::t::geometry::TriangleMesh::CreateCylinder(), cloudViewer::t::geometry::TriangleMesh::CreateIcosahedron(), cloudViewer::t::geometry::TriangleMesh::CreateIsosurfaces(), cloudViewer::t::geometry::TriangleMesh::CreateMobius(), cloudViewer::t::geometry::TriangleMesh::CreateOctahedron(), cloudViewer::t::geometry::TriangleMesh::CreateSphere(), cloudViewer::t::geometry::TriangleMesh::CreateTetrahedron(), cloudViewer::t::geometry::TriangleMesh::CreateText(), cloudViewer::t::geometry::TriangleMesh::CreateTorus(), cloudViewer::t::geometry::TriangleMesh::ExtrudeLinear(), cloudViewer::t::geometry::TriangleMesh::ExtrudeRotation(), cloudViewer::t::geometry::TriangleMesh::FillHoles(), cloudViewer::core::Float32, cloudViewer::t::geometry::TriangleMesh::FromLegacy(), cloudViewer::t::geometry::TriangleMesh::FromTriangleMeshModel(), cloudViewer::t::geometry::TriangleMesh::GetAxisAlignedBoundingBox(), cloudViewer::t::geometry::TriangleMesh::GetCenter(), cloudViewer::t::geometry::TriangleMesh::GetDevice(), cloudViewer::t::geometry::TriangleMesh::GetMaxBound(), cloudViewer::t::geometry::TriangleMesh::GetMinBound(), cloudViewer::t::geometry::TriangleMesh::GetNonManifoldEdges(), cloudViewer::t::geometry::TriangleMesh::GetOrientedBoundingBox(), cloudViewer::t::geometry::TriangleMesh::GetSurfaceArea(), cloudViewer::t::geometry::TriangleMesh::GetTriangleAttr(), cloudViewer::t::geometry::TriangleMesh::GetVertexAttr(), cloudViewer::core::Int64, cloudViewer::core::Device::IsAvailable(), LogError, LogWarning, normal, cloudViewer::t::geometry::TriangleMesh::NormalizeNormals(), cloudViewer::t::geometry::TriangleMesh::PCAPartition(), cloudViewer::t::geometry::TriangleMesh::ProjectImagesToAlbedo(), cloudViewer::t::geometry::TriangleMesh::RemoveNonManifoldEdges(), cloudViewer::t::geometry::TriangleMesh::RemoveUnreferencedVertices(), cloudViewer::t::geometry::TriangleMesh::Rotate(), cloudViewer::t::geometry::TriangleMesh::SamplePointsUniformly(), cloudViewer::t::geometry::TriangleMesh::Scale(), cloudViewer::t::geometry::TriangleMesh::SelectByIndex(), cloudViewer::t::geometry::TriangleMesh::SelectFacesByMask(), cloudViewer::t::geometry::TriangleMesh::SimplifyQuadricDecimation(), cloudViewer::t::geometry::TriangleMesh::To(), cloudViewer::t::geometry::TriangleMesh::ToLegacy(), cloudViewer::core::Device::ToString(), cloudViewer::t::geometry::TriangleMesh::ToString(), cloudViewer::t::geometry::TriangleMesh::Transform(), and cloudViewer::t::geometry::TriangleMesh::Translate().
Referenced by pybind_geometry().
pybind_voxel_block_grid()
void cloudViewer::t::geometry::pybind_voxel_block_grid (py::module & m)
Definition at line 21 of file voxel_block_grid.cpp.
References cloudViewer::t::geometry::VoxelBlockGrid::ExtractPointCloud(), cloudViewer::t::geometry::VoxelBlockGrid::ExtractTriangleMesh(), cloudViewer::t::geometry::VoxelBlockGrid::GetAttribute(), cloudViewer::t::geometry::VoxelBlockGrid::GetHashMap(), cloudViewer::t::geometry::VoxelBlockGrid::GetUniqueBlockCoordinates(), cloudViewer::t::geometry::VoxelBlockGrid::GetVoxelCoordinates(), cloudViewer::t::geometry::VoxelBlockGrid::GetVoxelCoordinatesAndFlattenedIndices(), cloudViewer::t::geometry::VoxelBlockGrid::GetVoxelIndices(), cloudViewer::t::geometry::VoxelBlockGrid::Integrate(), cloudViewer::t::geometry::VoxelBlockGrid::Load(), cloudViewer::t::geometry::VoxelBlockGrid::RayCast(), cloudViewer::t::geometry::VoxelBlockGrid::Save(), and cloudViewer::t::geometry::VoxelBlockGrid::To().
Referenced by pybind_geometry().
RemoveRadiusOutliers()
void cloudViewer::t::geometry::RemoveRadiusOutliers (benchmark::State & state, const core::Device & device, const int nb_points, const double search_radius)
Definition at line 225 of file PointCloud.cpp.
References path, cloudViewer::t::io::ReadPointCloud(), cloudViewer::t::geometry::PointCloud::RemoveRadiusOutliers(), cloudViewer::t::geometry::PointCloud::To(), and cloudViewer::t::geometry::PointCloud::VoxelDownSample().
RemoveStatisticalOutliers()
void cloudViewer::t::geometry::RemoveStatisticalOutliers (benchmark::State & state, const core::Device & device, const int nb_neighbors)
Definition at line 241 of file PointCloud.cpp.
References path, cloudViewer::t::io::ReadPointCloud(), cloudViewer::t::geometry::PointCloud::RemoveStatisticalOutliers(), cloudViewer::t::geometry::PointCloud::To(), and cloudViewer::t::geometry::PointCloud::VoxelDownSample().
SelectByIndex()
void cloudViewer::t::geometry::SelectByIndex (benchmark::State & state, bool remove_duplicates, const core::Device & device)
Definition at line 149 of file PointCloud.cpp.
References cloudViewer::core::Tensor::Arange(), cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::core::Int64, path, cloudViewer::t::io::ReadPointCloud(), cloudViewer::t::geometry::PointCloud::SelectByIndex(), cloudViewer::core::cuda::Synchronize(), and cloudViewer::t::geometry::PointCloud::To().
ToLegacyPointCloud()
void cloudViewer::t::geometry::ToLegacyPointCloud (benchmark::State & state, const core::Device & device)
Definition at line 42 of file PointCloud.cpp.
References cloudViewer::core::Float32, cloudViewer::t::geometry::PointCloud::SetPointColors(), cloudViewer::t::geometry::PointCloud::SetPointPositions(), cloudViewer::core::cuda::Synchronize(), and cloudViewer::t::geometry::PointCloud::ToLegacy().
Transform()
void cloudViewer::t::geometry::Transform (benchmark::State & state, const core::Device & device)
Definition at line 127 of file PointCloud.cpp.
References cloudViewer::core::Tensor::GetDtype(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), path, cloudViewer::t::io::ReadPointCloud(), cloudViewer::core::cuda::Synchronize(), cloudViewer::t::geometry::PointCloud::To(), cloudViewer::t::geometry::kernel::image::To(), and cloudViewer::t::geometry::PointCloud::Transform().
Referenced by pybind11::detail::type_caster< QVariant >::cast(), and cloudViewer::visualization::rendering::CloudViewerScene::SetGeometryTransform().
UniformDownSample()
void cloudViewer::t::geometry::UniformDownSample (benchmark::State & state, const core::Device & device, size_t k)
Definition at line 94 of file PointCloud.cpp.
References path, cloudViewer::t::io::ReadPointCloud(), cloudViewer::core::cuda::Synchronize(), cloudViewer::t::geometry::PointCloud::To(), and cloudViewer::t::geometry::PointCloud::UniformDownSample().
Unit()
cloudViewer::t::geometry::Unit (benchmark::kMillisecond)
UpdateTriangleIndicesByVertexMask()
template<typename T > static void cloudViewer::t::geometry::UpdateTriangleIndicesByVertexMask (core::Tensor & tris_cpu, const core::Tensor & vertex_mask) static
A helper to compute new vertex indices out of vertex mask.
Parameters
tris_cpu CPU tensor with triangle indices to update.
vertex_mask CPU tensor with the mask for vertices.
Definition at line 1132 of file TriangleMesh.cpp.
References cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetLength(), and cloudViewer::utility::InclusivePrefixSum().
VoxelDownSample()
void cloudViewer::t::geometry::VoxelDownSample (benchmark::State & state, const core::Device & device, float voxel_size, const std::string & reduction)
Definition at line 68 of file PointCloud.cpp.
References path, cloudViewer::t::io::ReadPointCloud(), cloudViewer::core::cuda::Synchronize(), cloudViewer::t::geometry::PointCloud::To(), and cloudViewer::t::geometry::PointCloud::VoxelDownSample().
Variable Documentation
input_path_pcd
const std::string cloudViewer::t::geometry::input_path_pcd = pointcloud_ply_data.GetPath() static
Definition at line 29 of file PointCloudIO.cpp.
knot_data
data::KnotMesh cloudViewer::t::geometry::knot_data
Definition at line 20 of file TriangleMeshIO.cpp.
Referenced by cloudViewer::benchmarks::SamplePointsFixture::SetUp().
kReductionMean
const std::string cloudViewer::t::geometry::kReductionMean = "mean"
Definition at line 408 of file PointCloud.cpp.
map_shared_argument_docstrings [1/2]
const std::unordered_map<std::string, std::string> cloudViewer::t::geometry::map_shared_argument_docstrings static
Initial value:
= {
                {"color", "The color image."},
                {"depth", "The depth image."},
                {"aligned",
                 "Are the two images aligned (same viewpoint and resolution)?"},
                {"image", "The Image object."},
                {"tensor",
                 "Tensor of the image. The tensor must be contiguous. The "
                 "tensor must be 2D (rows, cols) or 3D (rows, cols, "
                 "channels)."},
                {"rows",
                 "Number of rows of the image, i.e. image height. rows must be "
                 "non-negative."},
                {"cols",
                 "Number of columns of the image, i.e. image width. cols must "
                 "be non-negative."},
                {"channels",
                 "Number of channels of the image. E.g. for RGB image, "
                 "channels == 3; for grayscale image, channels == 1. channels "
                 "must be greater than 0."},
                {"dtype", "Data type of the image."},
                {"device", "Device where the image is stored."},
                {"scale",
                 "First multiply image pixel values with this factor. "
                 "This should be positive for unsigned dtypes."},
                {"offset", "Then add this factor to all image pixel values."},
                {"kernel_size", "Kernel size for filters and dilations."},
                {"value_sigma", "Standard deviation for the image content."},
                {"distance_sigma",
                 "Standard deviation for the image pixel positions."}}
Definition at line 25 of file image.cpp.
Referenced by pybind_image(), and pybind_pointcloud().
map_shared_argument_docstrings [2/2]
const std::unordered_map<std::string, std::string> cloudViewer::t::geometry::map_shared_argument_docstrings static
Initial value:
= {
                {"rgbd_image",
                 "The input RGBD image should have a uint16_t depth image and  "
                 "RGB image with any DType and the same size."},
                {"depth", "The input depth image should be a uint16_t image."},
                {"intrinsics", "Intrinsic parameters of the camera."},
                {"extrinsics", "Extrinsic parameters of the camera."},
                {"depth_scale", "The depth is scaled by 1 / depth_scale."},
                {"depth_max", "Truncated at depth_max distance."},
                {"stride",
                 "Sampling factor to support coarse point cloud extraction. "
                 "Unless normals are requested, there is no low pass "
                 "filtering, so aliasing is possible for stride>1."},
                {"with_normals",
                 "Also compute normals for the point cloud. If True, the point "
                 "cloud will only contain points with valid normals. If "
                 "normals are requested, the depth map is first filtered to "
                 "ensure smooth normals."},
                {"max_nn",
                 "Neighbor search max neighbors parameter [default = 30]."},
                {"radius",
                 "neighbors search radius parameter to use HybridSearch. "
                 "[Recommended ~1.4x voxel size]."}}
Definition at line 25 of file pointcloud.cpp.
path
const std::string cloudViewer::t::geometry::path = pointcloud_ply.GetPath() static
Definition at line 59 of file PointCloud.cpp.
Referenced by cloudViewer::utility::filesystem::AddIfExist(), cloudViewer::visualization::gui::FileDialog::Impl::CalcCurrentDirectory(), pybind11::detail::path_caster< T >::cast(), ccTranslationManager::ccTranslationManager(), cloudViewer::data::Dataset::CheckPathsExist(), ComputeBoundaryPoints(), IoUtils::createMaterialSetForMesh(), cloudViewer::visualization::rendering::FilamentResourceManager::CreateTexture(), CropByAxisAlignedBox(), CropByOrientedBox(), e57::Decoder::DecoderFactory(), QUIWidget::deleteDirectory(), e57::Encoder::EncoderFactory(), EstimateNormals(), PdmsTools::PdmsCommands::ElementCreation::execute(), cloudViewer::visualization::GuiVisualizer::ExportCurrentImage(), cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ExportCurrentImage(), cloudViewer::visualization::visualizer::O3DVisualizer::ExportCurrentImage(), DistanceMapGenerationDlg::exportMapAsGrid(), extractfilename(), cloudViewer::visualization::gui::FindFontPath(), findMenuPathRecursive(), cloudViewer::utility::filesystem::FReadToBuffer(), PyVenvCfg::FromFile(), PythonPlugin::getActions(), getImageList(), ecvConsole::getLogDirectory(), getMenuPath(), cloudViewer::utility::filesystem::GetPathComponents(), PdmsTools::PdmsCommands::ElementCreation::handle(), cloudViewer::ReconstructionWidget::ImportReconstruction(), ecvTextureFileSelector::init(), cloudViewer::visualization::gui::Application::Initialize(), cloudViewer::utility::filesystem::JoinPath(), LegacyCropByAxisAlignedBox(), LegacyCropByOrientedBox(), LegacyEstimateNormals(), LegacyRemoveRadiusOutliers(), LegacyRemoveStatisticalOutliers(), LegacySelectByIndex(), LegacyTransform(), LegacyUniformDownSample(), LegacyVoxelDownSample(), IcmFilter::LoadCalibratedImages(), IcmFilter::loadFile(), PovFilter::loadFile(), cloudViewer::visualization::GuiVisualizer::LoadGeometry(), cloudViewer::visualization::gui::LoadMaterialTemplate(), DistanceMapGenerationDlg::loadOverlaySymbols(), PythonPluginManager::loadPluginsFrom(), qSRA::loadProfile(), cloudViewer::io::LoadTextures(), cloudViewer::visualization::visualizer::O3DVisualizer::O3DVisualizer(), cloudViewer::visualization::GuiVisualizer::OnDragDropped(), cloudViewer::visualization::GuiVisualizer::OnMenuItemSelected(), ccTrace::optimizeSegment(), e57::ImageFileImpl::pathNameUnparse(), PythonConfig::preparePythonProcess(), CommandExtractCCs::process(), CommandICP::process(), PythonEditor::projectTreeDoubleClicked(), cloudViewer::io::pybind_class_io(), cloudViewer::t::io::pybind_class_io(), cloudViewer::visualization::gui::pybind_gui_classes(), cloudViewer::visualization::pybind_renderoption(), cloudViewer::t::io::pybind_sensor(), cloudViewer::visualization::pybind_visualization_utility_methods(), cloudViewer::visualization::pybind_visualizer(), cloudViewer::ImageViewerWidget::ReadAndShow(), cloudViewer::FeatureImageViewerWidget::ReadAndShowWithKeypoints(), cloudViewer::io::ReadFileGeometryType(), cloudViewer::io::ReadFileGeometryTypePLY(), cloudViewer::data::RedwoodIndoorLivingRoom1::RedwoodIndoorLivingRoom1(), cloudViewer::data::RedwoodIndoorLivingRoom2::RedwoodIndoorLivingRoom2(), cloudViewer::data::RedwoodIndoorOffice1::RedwoodIndoorOffice1(), cloudViewer::data::RedwoodIndoorOffice2::RedwoodIndoorOffice2(), RemoveRadiusOutliers(), RemoveStatisticalOutliers(), cloudViewer::AutomaticReconstructionWidget::Run(), cloudViewer::visualization::app::RunViewer(), CSF::saveGroundPoints(), Cloth::saveMovableToFile(), CSF::saveOffGroundPoints(), Cloth::saveToFile(), SelectByIndex(), cloudViewer::io::rpc::SetActiveCamera(), cloudViewer::ProjectWidget::SetDatabasePath(), cloudViewer::visualization::gui::Application::SetFont(), cloudViewer::visualization::GuiVisualizer::SetIBL(), cloudViewer::visualization::visualizer::O3DVisualizer::SetIBL(), cloudViewer::visualization::GuiVisualizer::Impl::SetIBL(), cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetIBL(), cloudViewer::ProjectWidget::SetImagePath(), cloudViewer::io::rpc::SetLegacyCamera(), cloudViewer::visualization::rendering::CloudViewerScene::SetLighting(), cloudViewer::io::rpc::SetMeshData(), cloudViewer::visualization::gui::FileDialog::SetPath(), ccPluginInfoDlg::setPluginPaths(), cloudViewer::io::rpc::SetPointCloud(), ProjectView::setRootPath(), cloudViewer::io::rpc::SetTriangleMesh(), cloudViewer::PointViewerWidget::Show(), cloudViewer::DatabaseImageViewerWidget::ShowImageWithId(), cloudViewer::utility::filesystem::SplitFileExtension(), PdmsTools::PdmsCommands::ElementCreation::splitPath(), CVTools::ToNativeSeparators(), Transform(), UniformDownSample(), cloudViewer::visualization::gui::FileDialog::Impl::UpdateDirectoryListing(), and VoxelDownSample().
pointcloud_ply
data::PLYPointCloud cloudViewer::t::geometry::pointcloud_ply
Definition at line 58 of file PointCloud.cpp.
Referenced by ComputeBoundaryPoints().
pointcloud_ply_data
data::PLYPointCloud cloudViewer::t::geometry::pointcloud_ply_data
Definition at line 28 of file PointCloudIO.cpp.