ACloudViewer: PyCC Namespace Reference
PyCC Namespace Reference
Functions
void NoOpDelete (void *)
template<class T >
py::array_t< T > SpanAsNumpyArray (T *data, py::array::ShapeContainer shape)
template<class T >
py::array_t< T > SpanAsNumpyArray (T *data, size_t len)
template<class T >
py::array_t< T > VectorAsNumpyArray (std::vector< T > &vector)
template<class PointCloudType >
void addPointsFromArrays (PointCloudType &self, py::array_t< PointCoordinateType > &xs, py::array_t< PointCoordinateType > &ys, py::array_t< PointCoordinateType > &zs)
Function Documentation
addPointsFromArrays()
template<class PointCloudType > void PyCC::addPointsFromArrays (PointCloudType & self, py::array_t< PointCoordinateType > & xs, py::array_t< PointCoordinateType > & ys, py::array_t< PointCoordinateType > & zs)
Definition at line 94 of file wrappers.h.
References max(), and patch::to_string().
Referenced by define_ccPointCloud().
NoOpDelete()
void PyCC::NoOpDelete (void *) inline
Definition at line 72 of file wrappers.h.
Referenced by SpanAsNumpyArray().
SpanAsNumpyArray() [1/2]
template<class T > py::array_t<T> PyCC::SpanAsNumpyArray (T * data, py::array::ShapeContainer shape)
Definition at line 74 of file wrappers.h.
References NoOpDelete().
Referenced by define_ccGLMatrixClass().
SpanAsNumpyArray() [2/2]
template<class T > py::array_t<T> PyCC::SpanAsNumpyArray (T * data, size_t len)
Definition at line 80 of file wrappers.h.
References NoOpDelete().
Referenced by VectorAsNumpyArray().
VectorAsNumpyArray()
template<class T > py::array_t<T> PyCC::VectorAsNumpyArray (std::vector< T > & vector)
Definition at line 86 of file wrappers.h.
References SpanAsNumpyArray().