ACloudViewer: patch Namespace Reference
patch Namespace Reference
Functions
template<typename T >
std::string to_string (const T &n)
Function Documentation
to_string()
template<typename T > std::string patch::to_string (const T & n)
Definition at line 20 of file Common.h.
Referenced by cloudViewer::visualization::rendering::FilamentScene::AddGeometry(), PyCC::addPointsFromArrays(), cloudViewer::data::BedroomRGBDImages::BedroomRGBDImages(), cloudViewer::visualization::gui::Button::Button(), cloudViewer::visualization::gui::Checkbox::Checkbox(), cloudViewer::io::rpc::messages::MeshData::CheckFaces(), cloudViewer::io::rpc::messages::Array::CheckNonEmpty(), cloudViewer::io::rpc::messages::Array::CheckRank(), cloudViewer::ml::op_util::CheckShape(), cloudViewer::io::rpc::messages::Array::CheckShape(), cloudViewer::visualization::gui::ColorEdit::ColorEdit(), cloudViewer::visualization::gui::Combobox::Combobox(), cloudViewer::io::AzureKinectSensorConfig::ConvertFromNativeConfig(), define_ccPointCloud(), define_GenericIndexedCloud(), define_someQtThings(), cloudViewer::data::DemoICPPointClouds::DemoICPPointClouds(), cloudViewer::t::io::RealSenseSensor::EnumerateDevices(), e57::Utilities::errorCodeToString(), cloudViewer::visualization::webrtc_server::WebRTCWindowSystem::Impl::GenerateUID(), cloudViewer::core::HashBackendBuffer::HashBackendBuffer(), cloudViewer::visualization::VisualizerWithEditing::KeyPressCallback(), cloudViewer::visualization::gui::ListView::ListView(), cloudViewer::data::LivingRoomPointClouds::LivingRoomPointClouds(), cloudViewer::data::LoungeRGBDImages::LoungeRGBDImages(), cloudViewer::visualization::visualizer::O3DVisualizerSelections::NewSet(), cloudViewer::visualization::gui::NumberEdit::NumberEdit(), cloudViewer::data::OfficePointClouds::OfficePointClouds(), cloudViewer::io::ArrayAdapter< T >::operator[](), cloudViewer::visualization::VisualizerWithKeyCallback::PrintKeyToString(), cloudViewer::camera::pybind_camera_classes(), cloudViewer::pipelines::registration::pybind_feature(), cloudViewer::pipelines::registration::pybind_global_optimization(), cloudViewer::geometry::pybind_halfedgetrianglemesh(), cloudViewer::geometry::pybind_kdtreeflann(), cloudViewer::geometry::pybind_lineset(), cloudViewer::geometry::pybind_meshbase(), cloudViewer::pipelines::odometry::pybind_odometry_classes(), cloudViewer::geometry::pybind_pointcloud(), cloudViewer::t::pipelines::registration::pybind_registration_class(), cloudViewer::pipelines::registration::pybind_registration_classes(), cloudViewer::pipelines::registration::pybind_robust_kernels(), cloudViewer::geometry::pybind_tetramesh(), cloudViewer::geometry::pybind_voxelgrid(), cloudViewer::visualization::gui::RadioButton::RadioButton(), cloudViewer::t::geometry::RaycastingScene::RaycastingScene(), cloudViewer::core::report_at_maximum_capacity(), cloudViewer::core::report_size_overflow(), cloudViewer::visualization::gui::SceneWidget::SceneWidget(), cloudViewer::visualization::gui::CollapsableVert::SetText(), cloudViewer::t::io::SetTextureMaterialProperty(), cloudViewer::io::rpc::SetTriangleMesh(), cloudViewer::PointViewerWidget::Show(), cloudViewer::OverlappingImagesWidget::ShowMatches(), cloudViewer::visualization::gui::Slider::Slider(), cloudViewer::visualization::gui::TabControl::TabControl(), cloudViewer::visualization::gui::TextEdit::TextEdit(), cloudViewer::visualization::gui::ToggleSwitch::ToggleSwitch(), cloudViewer::core::Device::ToString(), cloudViewer::core::Scalar::ToString(), cloudViewer::ml::op_util::DimValue::ToString(), cloudViewer::t::io::RGBDSensor::ToString(), cloudViewer::ml::op_util::Dim::ToString(), cloudViewer::visualization::gui::VectorEdit::VectorEdit(), and cloudViewer::t::io::WritePointCloudToPLY().