ACloudViewer: ecvColor::LookUpTable Namespace Reference
ecvColor::LookUpTable Namespace Reference
Functions
Rgb at (size_t color_id)
Function Documentation
at()
Rgb ecvColor::LookUpTable::at (size_t color_id)
Referenced by wl::PointCloud::computeBoundingBox(), cloudViewer::ScalarField::computeMinAndMax(), cloudViewer::ScalarField::flagValueAsInvalid(), CorePointDescSet::fromByteArray(), ccArray< Type, N, ComponentType >::getValue(), cloudViewer::ScalarField::getValue(), CorePointDescSet::loadFromMSC(), Train3DMASCDialog::openTraceFile(), CorePointDescSet::setScales(), ccArray< Type, N, ComponentType >::setValue(), cloudViewer::ScalarField::setValue(), ccArray< Type, N, ComponentType >::swap(), cloudViewer::ScalarField::swap(), CorePointDescSet::toByteArray(), and cloudViewer::t::geometry::TensorMap::ToString().