ACloudViewer: cloudViewer::t::geometry::npp Namespace Reference
cloudViewer::t::geometry::npp Namespace Reference
Functions
static NppStreamContext MakeNPPContext ()
void RGBToGray (const core::Tensor &src_im, core::Tensor &dst_im)
void Resize (const cloudViewer::core::Tensor &src_im, cloudViewer::core::Tensor &dst_im, t::geometry::Image::InterpType interp_type)
void Dilate (const core::Tensor &src_im, core::Tensor &dst_im, int kernel_size)
void Filter (const cloudViewer::core::Tensor &src_im, cloudViewer::core::Tensor &dst_im, const cloudViewer::core::Tensor &kernel)
void FilterBilateral (const core::Tensor &src_im, core::Tensor &dst_im, int kernel_size, float value_sigma, float distance_sigma)
void FilterGaussian (const core::Tensor &src_im, core::Tensor &dst_im, int kernel_size, float sigma)
void FilterSobel (const core::Tensor &src_im, core::Tensor &dst_im_dx, core::Tensor &dst_im_dy, int kernel_size)
Function Documentation
Dilate()
void cloudViewer::t::geometry::npp::Dilate (const core::Tensor & src_im, core::Tensor & dst_im, int kernel_size)
Definition at line 178 of file NPPImage.cpp.
References cloudViewer::core::Bool, context, cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), LogError, MakeNPPContext(), NPP_ARGS, cloudViewer::core::Tensor::Ones(), cloudViewer::core::Device::ToString(), cloudViewer::core::UInt16, and cloudViewer::core::UInt8.
Referenced by cloudViewer::t::geometry::Image::Dilate().
Filter()
void cloudViewer::t::geometry::npp::Filter (const cloudViewer::core::Tensor & src_im, cloudViewer::core::Tensor & dst_im, const cloudViewer::core::Tensor & kernel)
Definition at line 246 of file NPPImage.cpp.
References context, cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), LogError, MakeNPPContext(), NPP_ARGS, cloudViewer::core::Tensor::Reverse(), cloudViewer::core::Device::ToString(), cloudViewer::core::UInt16, and cloudViewer::core::UInt8.
Referenced by cloudViewer::t::geometry::Image::Filter(), and FilterGaussian().
FilterBilateral()
void cloudViewer::t::geometry::npp::FilterBilateral (const core::Tensor & src_im, core::Tensor & dst_im, int kernel_size, float value_sigma, float distance_sigma)
Definition at line 319 of file NPPImage.cpp.
References context, cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), LogError, MakeNPPContext(), NPP_ARGS, cloudViewer::core::Device::ToString(), cloudViewer::core::UInt16, and cloudViewer::core::UInt8.
Referenced by cloudViewer::t::geometry::Image::FilterBilateral().
FilterGaussian()
void cloudViewer::t::geometry::npp::FilterGaussian (const core::Tensor & src_im, core::Tensor & dst_im, int kernel_size, float sigma)
Definition at line 378 of file NPPImage.cpp.
References cloudViewer::core::Tensor::Arange(), dist(), cloudViewer::core::Tensor::Exp(), Filter(), cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDevice(), LogError, cloudViewer::core::Tensor::Matmul(), cloudViewer::core::Tensor::Sum(), cloudViewer::core::Tensor::T(), cloudViewer::core::Device::ToString(), and cloudViewer::core::Tensor::View().
Referenced by cloudViewer::t::geometry::Image::FilterGaussian().
FilterSobel()
void cloudViewer::t::geometry::npp::FilterSobel (const core::Tensor & src_im, core::Tensor & dst_im_dx, core::Tensor & dst_im_dy, int kernel_size)
Definition at line 406 of file NPPImage.cpp.
References CLOUDVIEWER_CUDA_CHECK, context, cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), LogError, MakeNPPContext(), cloudViewer::core::Tensor::Neg_(), NPP_ARGS_DX, NPP_ARGS_DY, cloudViewer::core::Device::ToString(), and cloudViewer::core::UInt8.
Referenced by cloudViewer::t::geometry::Image::FilterSobel().
MakeNPPContext()
static NppStreamContext cloudViewer::t::geometry::npp::MakeNPPContext () static
Definition at line 24 of file NPPImage.cpp.
References CLOUDVIEWER_CUDA_CHECK, and context.
Referenced by Dilate(), Filter(), FilterBilateral(), FilterSobel(), Resize(), and RGBToGray().
Resize()
void cloudViewer::t::geometry::npp::Resize (const cloudViewer::core::Tensor & src_im, cloudViewer::core::Tensor & dst_im, t::geometry::Image::InterpType interp_type)
Definition at line 97 of file NPPImage.cpp.
References context, cloudViewer::t::geometry::Image::Cubic, cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::t::geometry::Image::Lanczos, cloudViewer::t::geometry::Image::Linear, LogError, MakeNPPContext(), cloudViewer::t::geometry::Image::Nearest, NPP_ARGS, cloudViewer::t::geometry::Image::Super, cloudViewer::core::Device::ToString(), cloudViewer::core::UInt16, and cloudViewer::core::UInt8.
Referenced by cloudViewer::t::geometry::Image::Resize().
RGBToGray()
void cloudViewer::t::geometry::npp::RGBToGray (const core::Tensor & src_im, core::Tensor & dst_im)
Definition at line 63 of file NPPImage.cpp.
References context, cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), LogError, MakeNPPContext(), NPP_ARGS, cloudViewer::core::Device::ToString(), cloudViewer::core::UInt16, and cloudViewer::core::UInt8.
Referenced by cloudViewer::t::geometry::Image::RGBToGray().