ACloudViewer: poisson Namespace Reference
poisson Namespace Reference
Classes
class CloudViewerData
class CloudViewerPointStream
class CloudViewerVertex
struct FEMTreeProfiler
struct ConstraintDual
struct SystemDual
struct SystemDual< Dim, double >
Functions
template<class Real , unsigned int Dim>
XForm< Real, Dim+1 > GetBoundingBoxXForm (Point< Real, Dim > min, Point< Real, Dim > max, Real scaleFactor)
template<class Real , unsigned int Dim>
XForm< Real, Dim+1 > GetBoundingBoxXForm (Point< Real, Dim > min, Point< Real, Dim > max, Real width, Real scaleFactor, int &depth)
template<class Real , unsigned int Dim>
XForm< Real, Dim+1 > GetPointXForm (InputPointStream< Real, Dim > &stream, Real width, Real scaleFactor, int &depth)
template<class Real , unsigned int Dim>
XForm< Real, Dim+1 > GetPointXForm (InputPointStream< Real, Dim > &stream, Real scaleFactor)
template<typename Vertex , typename Real , typename SetVertexFunction , unsigned int... FEMSigs, typename... SampleData>
void ExtractMesh (float datax, bool linear_fit, UIntPack< FEMSigs... >, std::tuple< SampleData... >, FEMTree< sizeof...(FEMSigs), Real > &tree, const DenseNodeData< Real, UIntPack< FEMSigs... >> &solution, Real isoValue, const std::vector< typename FEMTree< sizeof...(FEMSigs), Real >::PointSample > *samples, std::vector< CloudViewerData > *sampleData, const typename FEMTree< sizeof...(FEMSigs), Real >::template DensityEstimator< WEIGHT_DEGREE > *density, const SetVertexFunction &SetVertex, XForm< Real, sizeof...(FEMSigs)+1 > iXForm, std::shared_ptr< ccMesh > &out_mesh, std::vector< double > &out_densities)
template<class Real , typename... SampleData, unsigned int... FEMSigs>
void Execute (const ccPointCloud &pcd, std::shared_ptr< ccMesh > &out_mesh, std::vector< double > &out_densities, int depth, size_t width, float scale, bool linear_fit, float point_weight, float samples_per_node, UIntPack< FEMSigs... >)
Variables
static const int DATA_DEGREE = 0
static const int WEIGHT_DEGREE = 2
static const int NORMAL_DEGREE = 2
static const int DEFAULT_FEM_DEGREE = 1
static const BoundaryType DEFAULT_FEM_BOUNDARY = BOUNDARY_NEUMANN
static const int DIMENSION = 3
Function Documentation
Execute()
template<class Real , typename... SampleData, unsigned int... FEMSigs> void poisson::Execute (const ccPointCloud & pcd, std::shared_ptr< ccMesh > & out_mesh, std::vector< double > & out_densities, int depth, size_t width, float scale, bool linear_fit, float point_weight, float samples_per_node, UIntPack< FEMSigs... >)
Definition at line 437 of file SurfaceReconstructionPoisson.cpp.
References poisson::FEMTreeProfiler< Dim, Real >::dumpOutput(), LogDebug, LogError, NORMAL_DEGREE, NULL, poisson::FEMTreeProfiler< Dim, Real >::start(), width, and poisson::CloudViewerPointStream< Real >::xform_.
ExtractMesh()
template<typename Vertex , typename Real , typename SetVertexFunction , unsigned int... FEMSigs, typename... SampleData> void poisson::ExtractMesh (float datax, bool linear_fit, UIntPack< FEMSigs... > , std::tuple< SampleData... > , FEMTree< sizeof...(FEMSigs), Real > & tree, const DenseNodeData< Real, UIntPack< FEMSigs... >> & solution, Real isoValue, const std::vector< typename FEMTree< sizeof...(FEMSigs), Real >::PointSample > * samples, std::vector< CloudViewerData > * sampleData, const typename FEMTree< sizeof...(FEMSigs), Real >::template DensityEstimator< WEIGHT_DEGREE > * density, const SetVertexFunction & SetVertex, XForm< Real, sizeof...(FEMSigs)+1 > iXForm, std::shared_ptr< ccMesh > & out_mesh, std::vector< double > & out_densities)
Definition at line 310 of file SurfaceReconstructionPoisson.cpp.
References ccPointCloud::addEigenColor(), ccPointCloud::addEigenNorm(), cloudViewer::PointCloudTpl< T >::addEigenPoint(), cloudViewer::utility::Extract(), LogError, NULL, Vertex< _Real >::point, ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveThePointsTable(), ccPointCloud::reserveTheRGBTable(), poisson::FEMTreeProfiler< Dim, Real >::start(), and ccHObjectCaster::ToPointCloud().
GetBoundingBoxXForm() [1/2]
template<class Real , unsigned int Dim> XForm<Real, Dim + 1> poisson::GetBoundingBoxXForm (Point< Real, Dim > min, Point< Real, Dim > max, Real scaleFactor)
Definition at line 198 of file SurfaceReconstructionPoisson.cpp.
GetBoundingBoxXForm() [2/2]
template<class Real , unsigned int Dim> XForm<Real, Dim + 1> poisson::GetBoundingBoxXForm (Point< Real, Dim > min, Point< Real, Dim > max, Real width, Real scaleFactor, int & depth)
Definition at line 219 of file SurfaceReconstructionPoisson.cpp.
References width.
Referenced by GetPointXForm().
GetPointXForm() [1/2]
template<class Real , unsigned int Dim> XForm<Real, Dim + 1> poisson::GetPointXForm (InputPointStream< Real, Dim > & stream, Real scaleFactor)
Definition at line 260 of file SurfaceReconstructionPoisson.cpp.
References GetBoundingBoxXForm().
GetPointXForm() [2/2]
template<class Real , unsigned int Dim> XForm<Real, Dim + 1> poisson::GetPointXForm (InputPointStream< Real, Dim > & stream, Real width, Real scaleFactor, int & depth)
Definition at line 250 of file SurfaceReconstructionPoisson.cpp.
References GetBoundingBoxXForm(), and width.
Variable Documentation
DATA_DEGREE
const int poisson::DATA_DEGREE = 0 static
Definition at line 47 of file SurfaceReconstructionPoisson.cpp.
DEFAULT_FEM_BOUNDARY
const BoundaryType poisson::DEFAULT_FEM_BOUNDARY = BOUNDARY_NEUMANN static
Definition at line 56 of file SurfaceReconstructionPoisson.cpp.
DEFAULT_FEM_DEGREE
const int poisson::DEFAULT_FEM_DEGREE = 1 static
Definition at line 54 of file SurfaceReconstructionPoisson.cpp.
Referenced by ccMesh::CreateFromPointCloudPoisson(), and PoissonReconLib::Reconstruct().
DIMENSION
const int poisson::DIMENSION = 3 static
Definition at line 58 of file SurfaceReconstructionPoisson.cpp.
Referenced by ccMesh::CreateFromPointCloudPoisson(), and PoissonReconLib::Reconstruct().
NORMAL_DEGREE
const int poisson::NORMAL_DEGREE = 2 static
Definition at line 52 of file SurfaceReconstructionPoisson.cpp.
Referenced by Execute(), and Execute().
WEIGHT_DEGREE
const int poisson::WEIGHT_DEGREE = 2 static
Definition at line 49 of file SurfaceReconstructionPoisson.cpp.