ACloudViewer: cloudViewer::docstring Namespace Reference
cloudViewer::docstring Namespace Reference
Classes
class ArgumentDoc
class FunctionDoc
Functions
void ClassMethodDocInject (py::module &pybind_module, const std::string &class_name, const std::string &function_name, const std::unordered_map< std::string, std::string > &map_parameter_body_docs)
void FunctionDocInject (py::module &pybind_module, const std::string &function_name, const std::unordered_map< std::string, std::string > &map_parameter_body_docs)
Variables
py::handle static_property
Function Documentation
ClassMethodDocInject()
void cloudViewer::docstring::ClassMethodDocInject (py::module & pybind_module, const std::string & class_name, const std::string & function_name, const std::unordered_map< std::string, std::string > & map_parameter_body_docs = std::unordered_map< std::string, std::string >())
Parse pybind docstring to FunctionDoc and inject argument docstrings for class methods.
Definition at line 27 of file docstring.cpp.
References cloudViewer::docstring::ArgumentDoc::body_, LogWarning, cloudViewer::docstring::ArgumentDoc::name_, cloudViewer::docstring::FunctionDoc::overload_docs_, and cloudViewer::docstring::FunctionDoc::ToGoogleDocString().
Referenced by cloudViewer::core::BindTensorCreation(), cloudViewer::data::pybind_armadillo(), cloudViewer::data::pybind_avocado(), cloudViewer::data::pybind_bedroom_rgbd_images(), cloudViewer::geometry::pybind_boundingvolume(), cloudViewer::data::pybind_bunny(), cloudViewer::camera::pybind_camera_classes(), cloudViewer::geometry::pybind_cloudbase(), cloudViewer::pipelines::color_map::pybind_color_map_options(), cloudViewer::core::pybind_core_hashmap(), cloudViewer::core::pybind_core_hashset(), cloudViewer::core::pybind_core_tensor(), cloudViewer::data::pybind_crate(), cloudViewer::data::pybind_damaged_helmet(), cloudViewer::data::pybind_data_classes(), cloudViewer::data::pybind_demo_colored_icp_pointclouds(), cloudViewer::data::pybind_demo_crop_pointcloud(), cloudViewer::data::pybind_demo_custom_visualization(), cloudViewer::data::pybind_demo_doppler_icp_sequence(), cloudViewer::data::pybind_demo_feature_matching_point_clouds(), cloudViewer::data::pybind_demo_icp_pointclouds(), cloudViewer::data::pybind_demo_pose_graph_optimization(), cloudViewer::data::pybind_eagle(), cloudViewer::geometry::pybind_facet(), cloudViewer::pipelines::registration::pybind_feature(), cloudViewer::t::geometry::pybind_geometry_class(), cloudViewer::geometry::pybind_geometry_classes(), cloudViewer::pipelines::registration::pybind_global_optimization(), cloudViewer::geometry::pybind_halfedgetrianglemesh(), cloudViewer::data::pybind_helmet(), cloudViewer::t::geometry::pybind_image(), cloudViewer::pipelines::integration::pybind_integration_classes(), cloudViewer::data::pybind_jackjack_l515_bag(), cloudViewer::data::pybind_juneau(), cloudViewer::geometry::pybind_kdtreeflann(), cloudViewer::data::pybind_knot(), cloudViewer::geometry::pybind_lineset(), cloudViewer::t::geometry::pybind_lineset(), cloudViewer::data::pybind_living_room_point_clouds(), cloudViewer::data::pybind_lounge_rgbd_images(), cloudViewer::geometry::pybind_meshbase(), cloudViewer::data::pybind_metal_texture(), cloudViewer::data::pybind_monkey(), cloudViewer::geometry::pybind_octree(), cloudViewer::data::pybind_office_point_clouds(), cloudViewer::data::pybind_painted_plaster_texture(), cloudViewer::data::pybind_pcd_point_cloud(), cloudViewer::data::pybind_ply_point_cloud(), cloudViewer::geometry::pybind_pointcloud(), cloudViewer::t::geometry::pybind_pointcloud(), cloudViewer::geometry::pybind_polyline(), cloudViewer::geometry::pybind_primitives(), cloudViewer::data::pybind_pts_point_cloud(), cloudViewer::t::pipelines::registration::pybind_registration_class(), cloudViewer::pipelines::registration::pybind_registration_classes(), cloudViewer::visualization::pybind_renderoption(), cloudViewer::pipelines::registration::pybind_robust_kernels(), cloudViewer::data::pybind_sample_fountain_rgbd_images(), cloudViewer::data::pybind_sample_l515_bag(), cloudViewer::data::pybind_sample_nyu_rgbd_image(), cloudViewer::data::pybind_sample_redwood_rgbd_images(), cloudViewer::data::pybind_sample_sun_rgbd_image(), cloudViewer::data::pybind_sample_tum_rgbd_image(), cloudViewer::utility::pybind_scalarfield(), cloudViewer::io::pybind_sensor(), cloudViewer::t::io::pybind_sensor(), cloudViewer::t::pipelines::slam::pybind_slam(), cloudViewer::data::pybind_sword(), cloudViewer::data::pybind_terrazzo_texture(), cloudViewer::geometry::pybind_tetramesh(), cloudViewer::data::pybind_tiles_texture(), cloudViewer::geometry::pybind_trianglemesh(), cloudViewer::t::geometry::pybind_trianglemesh(), cloudViewer::visualization::pybind_viewcontrol(), cloudViewer::visualization::pybind_visualization_utility(), cloudViewer::visualization::pybind_visualizer(), cloudViewer::geometry::pybind_voxelgrid(), cloudViewer::data::pybind_wood_floor_texture(), and cloudViewer::data::pybind_wood_texture().
FunctionDocInject()
void cloudViewer::docstring::FunctionDocInject (py::module & pybind_module, const std::string & function_name, const std::unordered_map< std::string, std::string > & map_parameter_docs = std::unordered_map< std::string, std::string >())
Parse pybind docstring to FunctionDoc and inject argument docstrings for functions.
Definition at line 76 of file docstring.cpp.
References cloudViewer::docstring::ArgumentDoc::body_, LogWarning, cloudViewer::docstring::ArgumentDoc::name_, cloudViewer::docstring::FunctionDoc::overload_docs_, and cloudViewer::docstring::FunctionDoc::ToGoogleDocString().
Referenced by cloudViewer::visualization::app::pybind_app(), cloudViewer::t::io::pybind_class_io(), cloudViewer::reconstruction::database::pybind_database_methods(), cloudViewer::pipelines::registration::pybind_feature_methods(), cloudViewer::reconstruction::feature::pybind_feature_methods(), cloudViewer::pipelines::registration::pybind_global_optimization_methods(), cloudViewer::reconstruction::gui::pybind_gui_methods(), cloudViewer::reconstruction::image::pybind_image_methods(), cloudViewer::geometry::pybind_keypoint_methods(), cloudViewer::utility::pybind_logging(), cloudViewer::reconstruction::model::pybind_model_methods(), cloudViewer::reconstruction::mvs::pybind_multi_views_stereo_methods(), cloudViewer::t::pipelines::odometry::pybind_odometry(), cloudViewer::utility::random::pybind_random(), cloudViewer::t::pipelines::registration::pybind_registration_class(), cloudViewer::io::pybind_rpc(), cloudViewer::reconstruction::sfm::pybind_sfm_methods(), cloudViewer::t::pipelines::slac::pybind_slac(), cloudViewer::visualization::pybind_visualization_utility_methods(), and cloudViewer::reconstruction::vocab_tree::pybind_vocab_tree_methods().
Variable Documentation
static_property
py::handle cloudViewer::docstring::static_property
Initial value:
=
        py::handle((PyObject*)py::detail::get_internals().static_property_type)
Definition at line 24 of file docstring.cpp.
Referenced by cloudViewer::utility::pybind_eigen(), cloudViewer::geometry::pybind_geometry_classes(), and cloudViewer::pipelines::registration::pybind_global_optimization().