ACloudViewer: colmap Namespace Reference
colmap Namespace Reference
Namespaces
internal
mvs
retrieval
Classes
class Camera
class CameraDatabase
struct BaseCameraModel
struct SimplePinholeCameraModel
struct PinholeCameraModel
struct SimpleRadialCameraModel
struct RadialCameraModel
struct OpenCVCameraModel
struct OpenCVFisheyeCameraModel
struct FullOpenCVCameraModel
struct FOVCameraModel
struct SimpleRadialFisheyeCameraModel
struct RadialFisheyeCameraModel
struct ThinPrismFisheyeCameraModel
class CameraRig
class CorrespondenceGraph
class BundleAdjustmentCostFunction
class BundleAdjustmentConstantPoseCostFunction
class RigBundleAdjustmentCostFunction
class RelativePoseCostFunction
class Database
class DatabaseTransaction
class DatabaseCache
class GPSTransform
class MinSTGraphCut
class Image
struct ImageReaderOptions
class ImageReader
struct LineSegment
class Point2D
class Point3D
class Reconstruction
class ReconstructionManager
class SceneClustering
class SimilarityTransform3
struct TrackElement
class Track
struct UndistortCameraOptions
class COLMAPUndistorter
class PMVSUndistorter
class CMPMVSUndistorter
class PureImageUndistorter
class StereoImageRectifier
class VisibilityPyramid
class AutomaticReconstructionController
class BundleAdjustmentController
class HierarchicalMapperController
struct IncrementalMapperOptions
class IncrementalMapperController
struct TexturingOptions
class TexturingReconstruction
class P3PEstimator
class EPNPEstimator
class AffineTransformEstimator
struct ManhattanWorldFrameEstimationOptions
class EssentialMatrixFivePointEstimator
class EssentialMatrixEightPointEstimator
class FundamentalMatrixSevenPointEstimator
class FundamentalMatrixEightPointEstimator
class GP3PEstimator
class GR6PEstimator
class HomographyMatrixEstimator
struct AbsolutePoseEstimationOptions
struct AbsolutePoseRefinementOptions
class SimilarityTransformEstimator
class TranslationTransformEstimator
class TriangulationEstimator
struct EstimateTriangulationOptions
struct TwoViewGeometry
class SiftFeatureExtractor
class FeatureImporter
struct ExhaustiveMatchingOptions
struct SequentialMatchingOptions
struct VocabTreeMatchingOptions
struct SpatialMatchingOptions
struct TransitiveMatchingOptions
struct ImagePairsMatchingOptions
struct FeaturePairsMatchingOptions
class FeatureMatcherCache
class FeatureMatcherThread
class SiftCPUFeatureMatcher
class SiftGPUFeatureMatcher
class GuidedSiftCPUFeatureMatcher
class GuidedSiftGPUFeatureMatcher
class TwoViewGeometryVerifier
class SiftFeatureMatcher
class ExhaustiveFeatureMatcher
class SequentialFeatureMatcher
class VocabTreeFeatureMatcher
class SpatialFeatureMatcher
class TransitiveFeatureMatcher
class ImagePairsFeatureMatcher
class FeaturePairsFeatureMatcher
struct SiftExtractionOptions
struct SiftMatchingOptions
struct FeatureKeypoint
struct FeatureMatch
class BundleAdjustmentConfig
struct BundleAdjustmentOptions
class BundleAdjuster
class RigBundleAdjuster
class CombinationSampler
struct LeastAbsoluteDeviationsOptions
class LORANSAC
class PositiveExponentialParameterization
class ProgressiveSampler
class RandomSampler
struct RANSACOptions
class RANSAC
class Sampler
class SPRT
struct InlierSupportMeasurer
struct MEstimatorSupportMeasurer
class IncrementalMapper
class IncrementalTriangulator
class AutomaticReconstructionWidget
class BundleAdjustmentWidget
class PointColormapBase
class PointColormapPhotometric
class PointColormapError
class PointColormapTrackLen
class PointColormapGroundResolution
class ImageColormapBase
class ImageColormapUniform
class ImageColormapNameFilter
class TwoViewInfoTab
class MatchesTab
class TwoViewGeometriesTab
class OverlappingImagesWidget
class CameraTab
class ImageTab
class DatabaseManagementWidget
class DenseReconstructionOptionsWidget
class DenseReconstructionWidget
class ExtractionWidget
class SIFTExtractionWidget
class ImportFeaturesWidget
class FeatureExtractionWidget
class FeatureMatchingTab
class ExhaustiveMatchingTab
class SequentialMatchingTab
class VocabTreeMatchingTab
class SpatialMatchingTab
class TransitiveMatchingTab
class CustomMatchingTab
class FeatureMatchingWidget
class ImageViewerGraphicsScene
class ImageViewerWidget
class FeatureImageViewerWidget
class DatabaseImageViewerWidget
class LicenseWidget
class LinePainter
class StandardOutputRedirector
class LogWidget
class MainWindow
class MatchMatrixWidget
class ModelViewerWidget
class MovieGrabberWidget
class OptionsWidget
class PointPainter
class PointViewerWidget
class ProjectWidget
class ReconstructionManagerWidget
class MapperGeneralOptionsWidget
class MapperTriangulationOptionsWidget
class MapperRegistrationOptionsWidget
class MapperInitializationOptionsWidget
class MapperBundleAdjustmentOptionsWidget
class MapperFilteringOptionsWidget
class ReconstructionOptionsWidget
class ReconstructionStatsWidget
struct RenderOptions
class RenderOptionsWidget
class ThreadControlWidget
class TrianglePainter
class UndistortionWidget
struct BitmapColor
class Bitmap
class JetColormap
class LRUCache
class ThreadSafeLRUCache
class MemoryConstrainedLRUCache
class CudaTimer
class OpenGLContextManager
class OptionManager
struct PlyPoint
struct PlyMeshVertex
struct PlyMeshFace
struct PlyMesh
class Thread
class ThreadPool
class JobQueue
class Timer
Typedefs
template<int kDim>
using EuclideanTransformEstimator = SimilarityTransformEstimator< kDim, false >
typedef Eigen::Matrix< uint8_t, 1, Eigen::Dynamic, Eigen::RowMajor > FeatureDescriptor
typedef std::vector< FeatureKeypoint > FeatureKeypoints
typedef Eigen::Matrix< uint8_t, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor > FeatureDescriptors
typedef std::vector< FeatureMatch > FeatureMatches
typedef std::vector< std::pair< std::string, float > > camera_make_specs_t
typedef std::unordered_map< std::string, camera_make_specs_t > camera_specs_t
typedef uint32_t camera_t
typedef uint32_t image_t
typedef uint64_t image_pair_t
typedef uint32_t point2D_t
typedef uint64_t point3D_t
Enumerations
enum class LineSegmentOrientation { HORIZONTAL = 1 , VERTICAL = -1 , UNDEFINED = 0 }
enum class CopyType { COPY , HARD_LINK , SOFT_LINK }
Functions
CAMERA_MODEL_CASES std::unordered_map< std::string, int > InitialzeCameraModelNameToId ()
std::unordered_map< int, std::string > InitialzeCameraModelIdToName ()
bool ExistsCameraModelWithName (const std::string &model_name)
bool ExistsCameraModelWithId (const int model_id)
int CameraModelNameToId (const std::string &model_name)
std::string CameraModelIdToName (const int model_id)
std::vector< double > CameraModelInitializeParams (const int model_id, const double focal_length, const size_t width, const size_t height)
std::string CameraModelParamsInfo (const int model_id)
const std::vector< size_t > & CameraModelFocalLengthIdxs (const int model_id)
const std::vector< size_t > & CameraModelPrincipalPointIdxs (const int model_id)
const std::vector< size_t > & CameraModelExtraParamsIdxs (const int model_id)
size_t CameraModelNumParams (const int model_id)
bool CameraModelVerifyParams (const int model_id, const std::vector< double > &params)
bool CameraModelHasBogusParams (const int model_id, const std::vector< double > &params, const size_t width, const size_t height, const double min_focal_length_ratio, const double max_focal_length_ratio, const double max_extra_param)
void CameraModelWorldToImage (const int model_id, const std::vector< double > &params, const double u, const double v, double *x, double *y)
void CameraModelImageToWorld (const int model_id, const std::vector< double > &params, const double x, const double y, double *u, double *v)
double CameraModelImageToWorldThreshold (const int model_id, const std::vector< double > &params, const double threshold)
void DecomposeEssentialMatrix (const Eigen::Matrix3d &E, Eigen::Matrix3d *R1, Eigen::Matrix3d *R2, Eigen::Vector3d *t)
void PoseFromEssentialMatrix (const Eigen::Matrix3d &E, const std::vector< Eigen::Vector2d > &points1, const std::vector< Eigen::Vector2d > &points2, Eigen::Matrix3d *R, Eigen::Vector3d *t, std::vector< Eigen::Vector3d > *points3D)
Eigen::Matrix3d EssentialMatrixFromPose (const Eigen::Matrix3d &R, const Eigen::Vector3d &t)
Eigen::Matrix3d EssentialMatrixFromAbsolutePoses (const Eigen::Matrix3x4d &proj_matrix1, const Eigen::Matrix3x4d &proj_matrix2)
void FindOptimalImageObservations (const Eigen::Matrix3d &E, const Eigen::Vector2d &point1, const Eigen::Vector2d &point2, Eigen::Vector2d *optimal_point1, Eigen::Vector2d *optimal_point2)
Eigen::Vector3d EpipoleFromEssentialMatrix (const Eigen::Matrix3d &E, const bool left_image)
Eigen::Matrix3d InvertEssentialMatrix (const Eigen::Matrix3d &E)
bool RefineEssentialMatrix (const ceres::Solver::Options &options, const std::vector< Eigen::Vector2d > &points1, const std::vector< Eigen::Vector2d > &points2, const std::vector< char > &inlier_mask, Eigen::Matrix3d *E)
void ComputeMinGraphCutStoerWagner (const std::vector< std::pair< int, int >> &edges, const std::vector< int > &weights, int *cut_weight, std::vector< char > *cut_labels)
std::unordered_map< int, int > ComputeNormalizedMinGraphCut (const std::vector< std::pair< int, int >> &edges, const std::vector< int > &weights, const int num_parts)
void DecomposeHomographyMatrix (const Eigen::Matrix3d &H, const Eigen::Matrix3d &K1, const Eigen::Matrix3d &K2, std::vector< Eigen::Matrix3d > *R, std::vector< Eigen::Vector3d > *t, std::vector< Eigen::Vector3d > *n)
void PoseFromHomographyMatrix (const Eigen::Matrix3d &H, const Eigen::Matrix3d &K1, const Eigen::Matrix3d &K2, const std::vector< Eigen::Vector2d > &points1, const std::vector< Eigen::Vector2d > &points2, Eigen::Matrix3d *R, Eigen::Vector3d *t, Eigen::Vector3d *n, std::vector< Eigen::Vector3d > *points3D)
Eigen::Matrix3d HomographyMatrixFromPose (const Eigen::Matrix3d &K1, const Eigen::Matrix3d &K2, const Eigen::Matrix3d &R, const Eigen::Vector3d &t, const Eigen::Vector3d &n, const double d)
std::vector< LineSegment > DetectLineSegments (const Bitmap &bitmap, const double min_length)
std::vector< LineSegmentOrientation > ClassifyLineSegmentOrientations (const std::vector< LineSegment > &segments, const double tolerance)
bool FindLinearPolynomialRoots (const Eigen::VectorXd &coeffs, Eigen::VectorXd *real, Eigen::VectorXd *imag)
bool FindQuadraticPolynomialRoots (const Eigen::VectorXd &coeffs, Eigen::VectorXd *real, Eigen::VectorXd *imag)
bool FindPolynomialRootsDurandKerner (const Eigen::VectorXd &coeffs_all, Eigen::VectorXd *real, Eigen::VectorXd *imag)
bool FindPolynomialRootsCompanionMatrix (const Eigen::VectorXd &coeffs_all, Eigen::VectorXd *real, Eigen::VectorXd *imag)
template<typename T >
T EvaluatePolynomial (const Eigen::VectorXd &coeffs, const T &x)
Eigen::Matrix3d CrossProductMatrix (const Eigen::Vector3d &vector)
void RotationMatrixToEulerAngles (const Eigen::Matrix3d &R, double *rx, double *ry, double *rz)
Eigen::Matrix3d EulerAnglesToRotationMatrix (const double rx, const double ry, const double rz)
Eigen::Vector4d RotationMatrixToQuaternion (const Eigen::Matrix3d &rot_mat)
Eigen::Matrix3d QuaternionToRotationMatrix (const Eigen::Vector4d &qvec)
Eigen::Vector4d NormalizeQuaternion (const Eigen::Vector4d &qvec)
Eigen::Vector4d InvertQuaternion (const Eigen::Vector4d &qvec)
Eigen::Vector4d ConcatenateQuaternions (const Eigen::Vector4d &qvec1, const Eigen::Vector4d &qvec2)
Eigen::Vector3d QuaternionRotatePoint (const Eigen::Vector4d &qvec, const Eigen::Vector3d &point)
Eigen::Vector4d AverageQuaternions (const std::vector< Eigen::Vector4d > &qvecs, const std::vector< double > &weights)
Eigen::Matrix3d RotationFromUnitVectors (const Eigen::Vector3d &vector1, const Eigen::Vector3d &vector2)
Eigen::Vector3d ProjectionCenterFromMatrix (const Eigen::Matrix3x4d &proj_matrix)
Eigen::Vector3d ProjectionCenterFromPose (const Eigen::Vector4d &qvec, const Eigen::Vector3d &tvec)
void ComputeRelativePose (const Eigen::Vector4d &qvec1, const Eigen::Vector3d &tvec1, const Eigen::Vector4d &qvec2, const Eigen::Vector3d &tvec2, Eigen::Vector4d *qvec12, Eigen::Vector3d *tvec12)
void ConcatenatePoses (const Eigen::Vector4d &qvec1, const Eigen::Vector3d &tvec1, const Eigen::Vector4d &qvec2, const Eigen::Vector3d &tvec2, Eigen::Vector4d *qvec12, Eigen::Vector3d *tvec12)
void InvertPose (const Eigen::Vector4d &qvec, const Eigen::Vector3d &tvec, Eigen::Vector4d *inv_qvec, Eigen::Vector3d *inv_tvec)
void InterpolatePose (const Eigen::Vector4d &qvec1, const Eigen::Vector3d &tvec1, const Eigen::Vector4d &qvec2, const Eigen::Vector3d &tvec2, const double t, Eigen::Vector4d *qveci, Eigen::Vector3d *tveci)
Eigen::Vector3d CalculateBaseline (const Eigen::Vector4d &qvec1, const Eigen::Vector3d &tvec1, const Eigen::Vector4d &qvec2, const Eigen::Vector3d &tvec2)
bool CheckCheirality (const Eigen::Matrix3d &R, const Eigen::Vector3d &t, const std::vector< Eigen::Vector2d > &points1, const std::vector< Eigen::Vector2d > &points2, std::vector< Eigen::Vector3d > *points3D)
Eigen::Vector4d ComposeIdentityQuaternion ()
Eigen::Matrix3x4d ComposeProjectionMatrix (const Eigen::Vector4d &qvec, const Eigen::Vector3d &tvec)
Eigen::Matrix3x4d ComposeProjectionMatrix (const Eigen::Matrix3d &R, const Eigen::Vector3d &T)
Eigen::Matrix3x4d InvertProjectionMatrix (const Eigen::Matrix3x4d &proj_matrix)
Eigen::Matrix3d ComputeClosestRotationMatrix (const Eigen::Matrix3d &matrix)
bool DecomposeProjectionMatrix (const Eigen::Matrix3x4d &P, Eigen::Matrix3d *K, Eigen::Matrix3d *R, Eigen::Vector3d *T)
Eigen::Vector2d ProjectPointToImage (const Eigen::Vector3d &point3D, const Eigen::Matrix3x4d &proj_matrix, const Camera &camera)
double CalculateSquaredReprojectionError (const Eigen::Vector2d &point2D, const Eigen::Vector3d &point3D, const Eigen::Vector4d &qvec, const Eigen::Vector3d &tvec, const Camera &camera)
double CalculateSquaredReprojectionError (const Eigen::Vector2d &point2D, const Eigen::Vector3d &point3D, const Eigen::Matrix3x4d &proj_matrix, const Camera &camera)
double CalculateAngularError (const Eigen::Vector2d &point2D, const Eigen::Vector3d &point3D, const Eigen::Vector4d &qvec, const Eigen::Vector3d &tvec, const Camera &camera)
double CalculateAngularError (const Eigen::Vector2d &point2D, const Eigen::Vector3d &point3D, const Eigen::Matrix3x4d &proj_matrix, const Camera &camera)
double CalculateNormalizedAngularError (const Eigen::Vector2d &point2D, const Eigen::Vector3d &point3D, const Eigen::Vector4d &qvec, const Eigen::Vector3d &tvec)
double CalculateNormalizedAngularError (const Eigen::Vector2d &point2D, const Eigen::Vector3d &point3D, const Eigen::Matrix3x4d &proj_matrix)
double CalculateDepth (const Eigen::Matrix3x4d &proj_matrix, const Eigen::Vector3d &point3D)
bool HasPointPositiveDepth (const Eigen::Matrix3x4d &proj_matrix, const Eigen::Vector3d &point3D)
bool ComputeAlignmentBetweenReconstructions (const Reconstruction &src_reconstruction, const Reconstruction &ref_reconstruction, const double min_inlier_observations, const double max_reproj_error, Eigen::Matrix3x4d *alignment)
Eigen::Vector3d TriangulatePoint (const Eigen::Matrix3x4d &proj_matrix1, const Eigen::Matrix3x4d &proj_matrix2, const Eigen::Vector2d &point1, const Eigen::Vector2d &point2)
std::vector< Eigen::Vector3d > TriangulatePoints (const Eigen::Matrix3x4d &proj_matrix1, const Eigen::Matrix3x4d &proj_matrix2, const std::vector< Eigen::Vector2d > &points1, const std::vector< Eigen::Vector2d > &points2)
Eigen::Vector3d TriangulateMultiViewPoint (const std::vector< Eigen::Matrix3x4d > &proj_matrices, const std::vector< Eigen::Vector2d > &points)
Eigen::Vector3d TriangulateOptimalPoint (const Eigen::Matrix3x4d &proj_matrix1, const Eigen::Matrix3x4d &proj_matrix2, const Eigen::Vector2d &point1, const Eigen::Vector2d &point2)
std::vector< Eigen::Vector3d > TriangulateOptimalPoints (const Eigen::Matrix3x4d &proj_matrix1, const Eigen::Matrix3x4d &proj_matrix2, const std::vector< Eigen::Vector2d > &points1, const std::vector< Eigen::Vector2d > &points2)
double CalculateTriangulationAngle (const Eigen::Vector3d &proj_center1, const Eigen::Vector3d &proj_center2, const Eigen::Vector3d &point3D)
std::vector< double > CalculateTriangulationAngles (const Eigen::Vector3d &proj_center1, const Eigen::Vector3d &proj_center2, const std::vector< Eigen::Vector3d > &points3D)
Camera UndistortCamera (const UndistortCameraOptions &options, const Camera &camera)
void UndistortImage (const UndistortCameraOptions &options, const Bitmap &distorted_bitmap, const Camera &distorted_camera, Bitmap *undistorted_bitmap, Camera *undistorted_camera)
void UndistortReconstruction (const UndistortCameraOptions &options, Reconstruction *reconstruction)
void RectifyStereoCameras (const Camera &camera1, const Camera &camera2, const Eigen::Vector4d &qvec, const Eigen::Vector3d &tvec, Eigen::Matrix3d *H1, Eigen::Matrix3d *H2, Eigen::Matrix4d *Q)
void RectifyAndUndistortStereoImages (const UndistortCameraOptions &options, const Bitmap &distorted_image1, const Bitmap &distorted_image2, const Camera &distorted_camera1, const Camera &distorted_camera2, const Eigen::Vector4d &qvec, const Eigen::Vector3d &tvec, Bitmap *undistorted_image1, Bitmap *undistorted_image2, Camera *undistorted_camera, Eigen::Matrix4d *Q)
void WarpImageBetweenCameras (const Camera &source_camera, const Camera &target_camera, const Bitmap &source_image, Bitmap *target_image)
void WarpImageWithHomography (const Eigen::Matrix3d &H, const Bitmap &source_image, Bitmap *target_image)
void WarpImageWithHomographyBetweenCameras (const Eigen::Matrix3d &H, const Camera &source_camera, const Camera &target_camera, const Bitmap &source_image, Bitmap *target_image)
void ResampleImageBilinear (const float *data, const int rows, const int cols, const int new_rows, const int new_cols, float *resampled)
void SmoothImage (const float *data, const int rows, const int cols, const float sigma_r, const float sigma_c, float *smoothed)
void DownsampleImage (const float *data, const int rows, const int cols, const int new_rows, const int new_cols, float *downsampled)
size_t FilterPoints (const IncrementalMapperOptions &options, IncrementalMapper *mapper)
size_t FilterImages (const IncrementalMapperOptions &options, IncrementalMapper *mapper)
size_t CompleteAndMergeTracks (const IncrementalMapperOptions &options, IncrementalMapper *mapper)
Eigen::Vector3d EstimateGravityVectorFromImageOrientation (const Reconstruction &reconstruction, const double max_axis_distance)
Eigen::Matrix3d EstimateManhattanWorldFrame (const ManhattanWorldFrameEstimationOptions &options, const Reconstruction &reconstruction, const std::string &image_path)
void AlignToPrincipalPlane (Reconstruction *recon, SimilarityTransform3 *tform)
void AlignToENUPlane (Reconstruction *recon, SimilarityTransform3 *tform, bool unscaled)
Eigen::Matrix< double, 9, 1 > ComputeDepthsSylvesterCoeffs (const Eigen::Matrix< double, 3, 6 > &K)
bool EstimateAbsolutePose (const AbsolutePoseEstimationOptions &options, const std::vector< Eigen::Vector2d > &points2D, const std::vector< Eigen::Vector3d > &points3D, Eigen::Vector4d *qvec, Eigen::Vector3d *tvec, Camera *camera, size_t *num_inliers, std::vector< char > *inlier_mask)
size_t EstimateRelativePose (const RANSACOptions &ransac_options, const std::vector< Eigen::Vector2d > &points1, const std::vector< Eigen::Vector2d > &points2, Eigen::Vector4d *qvec, Eigen::Vector3d *tvec)
bool RefineAbsolutePose (const AbsolutePoseRefinementOptions &options, const std::vector< char > &inlier_mask, const std::vector< Eigen::Vector2d > &points2D, const std::vector< Eigen::Vector3d > &points3D, Eigen::Vector4d *qvec, Eigen::Vector3d *tvec, Camera *camera)
bool RefineRelativePose (const ceres::Solver::Options &options, const std::vector< Eigen::Vector2d > &points1, const std::vector< Eigen::Vector2d > &points2, Eigen::Vector4d *qvec, Eigen::Vector3d *tvec)
bool EstimateTriangulation (const EstimateTriangulationOptions &options, const std::vector< TriangulationEstimator::PointData > &point_data, const std::vector< TriangulationEstimator::PoseData > &pose_data, std::vector< char > *inlier_mask, Eigen::Vector3d *xyz)
void CenterAndNormalizeImagePoints (const std::vector< Eigen::Vector2d > &points, std::vector< Eigen::Vector2d > *normed_points, Eigen::Matrix3d *matrix)
void ComputeSquaredSampsonError (const std::vector< Eigen::Vector2d > &points1, const std::vector< Eigen::Vector2d > &points2, const Eigen::Matrix3d &E, std::vector< double > *residuals)
void ComputeSquaredReprojectionError (const std::vector< Eigen::Vector2d > &points2D, const std::vector< Eigen::Vector3d > &points3D, const Eigen::Matrix3x4d &proj_matrix, std::vector< double > *residuals)
int RunDatabaseCleaner (int argc, char **argv)
int RunDatabaseCreator (int argc, char **argv)
int RunDatabaseMerger (int argc, char **argv)
int RunFeatureExtractor (int argc, char **argv)
int RunFeatureImporter (int argc, char **argv)
int RunMatchesImporter (int argc, char **argv)
int RunExhaustiveMatcher (int argc, char **argv)
int RunSequentialMatcher (int argc, char **argv)
int RunSpatialMatcher (int argc, char **argv)
int RunTransitiveMatcher (int argc, char **argv)
int RunVocabTreeMatcher (int argc, char **argv)
int RunGraphicalUserInterface (int argc, char **argv)
int RunProjectGenerator (int argc, char **argv)
int RunImageDeleter (int argc, char **argv)
int RunImageFilterer (int argc, char **argv)
int RunImageRectifier (int argc, char **argv)
int RunImageRegistrator (int argc, char **argv)
int RunImageUndistorter (int argc, char **argv)
int RunImageUndistorterStandalone (int argc, char **argv)
int RunImageTexturer (int argc, char **argv)
int RunModelAligner (int argc, char **argv)
int RunModelAnalyzer (int argc, char **argv)
int RunModelComparer (int argc, char **argv)
int RunModelConverter (int argc, char **argv)
int RunModelCropper (int argc, char **argv)
int RunModelMerger (int argc, char **argv)
int RunModelOrientationAligner (int argc, char **argv)
int RunModelSplitter (int argc, char **argv)
int RunModelTransformer (int argc, char **argv)
int RunDelaunayMesher (int argc, char **argv)
int RunPatchMatchStereo (int argc, char **argv)
int RunPoissonMesher (int argc, char **argv)
int RunStereoFuser (int argc, char **argv)
int RunAutomaticReconstructor (int argc, char **argv)
int RunBundleAdjuster (int argc, char **argv)
int RunColorExtractor (int argc, char **argv)
int RunMapper (int argc, char **argv)
int RunHierarchicalMapper (int argc, char **argv)
int RunPointFiltering (int argc, char **argv)
int RunPointTriangulator (int argc, char **argv)
int RunRigBundleAdjuster (int argc, char **argv)
int RunVocabTreeBuilder (int argc, char **argv)
int RunVocabTreeRetriever (int argc, char **argv)
bool ExtractSiftFeaturesCPU (const SiftExtractionOptions &options, const Bitmap &bitmap, FeatureKeypoints *keypoints, FeatureDescriptors *descriptors)
bool ExtractCovariantSiftFeaturesCPU (const SiftExtractionOptions &options, const Bitmap &bitmap, FeatureKeypoints *keypoints, FeatureDescriptors *descriptors)
bool CreateSiftGPUExtractor (const SiftExtractionOptions &options, SiftGPU *sift_gpu)
bool ExtractSiftFeaturesGPU (const SiftExtractionOptions &options, const Bitmap &bitmap, SiftGPU *sift_gpu, FeatureKeypoints *keypoints, FeatureDescriptors *descriptors)
void LoadSiftFeaturesFromTextFile (const std::string &path, FeatureKeypoints *keypoints, FeatureDescriptors *descriptors)
void MatchSiftFeaturesCPUBruteForce (const SiftMatchingOptions &match_options, const FeatureDescriptors &descriptors1, const FeatureDescriptors &descriptors2, FeatureMatches *matches)
void MatchSiftFeaturesCPUFLANN (const SiftMatchingOptions &match_options, const FeatureDescriptors &descriptors1, const FeatureDescriptors &descriptors2, FeatureMatches *matches)
void MatchSiftFeaturesCPU (const SiftMatchingOptions &match_options, const FeatureDescriptors &descriptors1, const FeatureDescriptors &descriptors2, FeatureMatches *matches)
void MatchGuidedSiftFeaturesCPU (const SiftMatchingOptions &match_options, const FeatureKeypoints &keypoints1, const FeatureKeypoints &keypoints2, const FeatureDescriptors &descriptors1, const FeatureDescriptors &descriptors2, TwoViewGeometry *two_view_geometry)
bool CreateSiftGPUMatcher (const SiftMatchingOptions &match_options, SiftMatchGPU *sift_match_gpu)
void MatchSiftFeaturesGPU (const SiftMatchingOptions &match_options, const FeatureDescriptors *descriptors1, const FeatureDescriptors *descriptors2, SiftMatchGPU *sift_match_gpu, FeatureMatches *matches)
void MatchGuidedSiftFeaturesGPU (const SiftMatchingOptions &match_options, const FeatureKeypoints *keypoints1, const FeatureKeypoints *keypoints2, const FeatureDescriptors *descriptors1, const FeatureDescriptors *descriptors2, SiftMatchGPU *sift_match_gpu, TwoViewGeometry *two_view_geometry)
std::vector< Eigen::Vector2d > FeatureKeypointsToPointsVector (const FeatureKeypoints &keypoints)
Eigen::MatrixXf L2NormalizeFeatureDescriptors (const Eigen::MatrixXf &descriptors)
Eigen::MatrixXf L1RootNormalizeFeatureDescriptors (const Eigen::MatrixXf &descriptors)
FeatureDescriptors FeatureDescriptorsToUnsignedByte (const Eigen::MatrixXf &descriptors)
void ExtractTopScaleFeatures (FeatureKeypoints *keypoints, FeatureDescriptors *descriptors, const size_t num_features)
void PrintSolverSummary (const ceres::Solver::Summary &summary)
bool SolveLeastAbsoluteDeviations (const LeastAbsoluteDeviationsOptions &options, const Eigen::SparseMatrix< double > &A, const Eigen::VectorXd &b, Eigen::VectorXd *x)
void SetQuaternionManifold (ceres::Problem *problem, double *quat_xyzw)
void SetSubsetManifold (int size, const std::vector< int > &constant_params, ceres::Problem *problem, double *params)
template<int size>
void SetSphereManifold (ceres::Problem *problem, double *params)
template<int size>
void SetPositiveExponentialManifold (ceres::Problem *problem, double *params)
int ParameterBlockTangentSize (ceres::Problem *problem, const double *param)
Eigen::Matrix4f QMatrixToEigen (const QMatrix4x4 &matrix)
QMatrix4x4 EigenToQMatrix (const Eigen::Matrix4f &matrix)
QImage BitmapToQImageRGB (const Bitmap &bitmap)
QPixmap ShowImagesSideBySide (const QPixmap &image1, const QPixmap &image2)
void DrawKeypoints (QPixmap *pixmap, const FeatureKeypoints &points, const QColor &color)
QPixmap DrawMatches (const QPixmap &image1, const QPixmap &image2, const FeatureKeypoints &points1, const FeatureKeypoints &points2, const FeatureMatches &matches, const QColor &keypoints_color)
template<typename T >
std::ostream & operator<< (std::ostream &output, const BitmapColor< T > &color)
camera_specs_t InitializeCameraSpecs ()
int GetNumCudaDevices ()
void SetBestCudaDevice (const int gpu_index)
void CudaSafeCall (const cudaError_t error, const std::string &file, const int line)
void CudaCheck (const char *file, const int line)
void CudaSyncAndCheck (const char *file, const int line)
bool IsURI (const std::string &uri)
std::filesystem::path GetCachedFilePath (const std::string &uri)
std::filesystem::path MaybeDownloadAndCacheFile (const std::string &uri)
template<typename T >
T ReverseBytes (const T &data)
bool IsLittleEndian ()
bool IsBigEndian ()
template<typename T >
T LittleEndianToNative (const T x)
template<typename T >
T BigEndianToNative (const T x)
template<typename T >
T NativeToLittleEndian (const T x)
template<typename T >
T NativeToBigEndian (const T x)
template<typename T >
T ReadBinaryLittleEndian (std::istream *stream)
template<typename T >
void ReadBinaryLittleEndian (std::istream *stream, std::vector< T > *data)
template<typename T >
void WriteBinaryLittleEndian (std::ostream *stream, const T &data)
template<typename T >
void WriteBinaryLittleEndian (std::ostream *stream, const std::vector< T > &data)
void InitializeGlog (char **argv)
const char * __GetConstFileBaseName (const char *file)
bool __CheckOptionImpl (const char *file, const int line, const bool result, const char *expr_str)
template<typename T1 , typename T2 >
bool __CheckOptionOpImpl (const char *file, const int line, const bool result, const T1 &val1, const T2 &val2, const char *val1_str, const char *val2_str, const char *op_str)
size_t NChooseK (const size_t n, const size_t k)
template<typename T >
int SignOfNumber (const T val)
bool IsNaN (const float x)
bool IsNaN (const double x)
bool IsInf (const float x)
bool IsInf (const double x)
template<typename T >
T Clip (const T &value, const T &low, const T &high)
float DegToRad (const float deg)
double DegToRad (const double deg)
float RadToDeg (const float rad)
double RadToDeg (const double rad)
template<typename T >
double Median (const std::vector< T > &elems)
template<typename T >
double Mean (const std::vector< T > &elems)
template<typename T >
double Variance (const std::vector< T > &elems)
template<typename T >
double StdDev (const std::vector< T > &elems)
template<typename T >
bool AnyLessThan (std::vector< T > elems, T threshold)
template<typename T >
bool AnyGreaterThan (std::vector< T > elems, T threshold)
template<class Iterator >
bool NextCombination (Iterator first, Iterator middle, Iterator last)
template<typename T >
T Sigmoid (const T x, const T alpha=1)
template<typename T >
T ScaleSigmoid (T x, const T alpha=1, const T x0=10)
template<typename T1 , typename T2 >
T2 TruncateCast (const T1 value)
template<typename T >
T Percentile (const std::vector< T > &elems, const double p)
template<typename Derived >
bool IsNaN (const Eigen::MatrixBase< Derived > &x)
template<typename Derived >
bool IsInf (const Eigen::MatrixBase< Derived > &x)
template<typename MatrixType >
void DecomposeMatrixRQ (const MatrixType &A, MatrixType *R, MatrixType *Q)
std::string EnsureTrailingSlash (const std::string &str)
bool HasFileExtension (const std::string &file_name, const std::string &ext)
void SplitFileExtension (const std::string &path, std::string *root, std::string *ext)
void FileCopy (const std::string &src_path, const std::string &dst_path, CopyType type)
bool ExistsFile (const std::string &path)
bool ExistsDir (const std::string &path)
bool ExistsPath (const std::string &path)
void CreateDirIfNotExists (const std::string &path)
std::string GetPathBaseName (const std::string &path)
std::string GetParentDir (const std::string &path)
std::string GetRelativePath (const std::string &from, const std::string &to)
std::vector< std::string > GetFileList (const std::string &path)
std::vector< std::string > GetRecursiveFileList (const std::string &path)
std::vector< std::string > GetDirList (const std::string &path)
std::vector< std::string > GetRecursiveDirList (const std::string &path)
size_t GetFileSize (const std::string &path)
void PrintHeading1 (const std::string &heading)
void PrintHeading2 (const std::string &heading)
template<>
std::vector< std::string > CSVToVector (const std::string &csv)
std::vector< std::string > ReadTextFileLines (const std::string &path)
void RemoveCommandLineArgument (const std::string &arg, int *argc, char **argv)
template<typename... T>
std::string JoinPaths (T const &... paths)
template<typename T >
bool VectorContainsValue (const std::vector< T > &vector, const T value)
template<typename T >
bool VectorContainsDuplicateValues (const std::vector< T > &vector)
template<typename T >
std::string VectorToCSV (const std::vector< T > &values)
template<typename T >
void ReadBinaryBlob (const std::string &path, std::vector< T > *data)
template<typename T >
void WriteBinaryBlob (const std::string &path, const std::vector< T > &data)
void RunThreadWithOpenGLContext (Thread *thread)
void GLError (const char *file, const int line)
std::vector< PlyPoint > ReadPly (const std::string &path)
void WriteTextPlyPoints (const std::string &path, const std::vector< PlyPoint > &points, const bool write_normal, const bool write_rgb)
void WriteBinaryPlyPoints (const std::string &path, const std::vector< PlyPoint > &points, const bool write_normal, const bool write_rgb)
void WriteTextPlyMesh (const std::string &path, const PlyMesh &mesh)
void WriteBinaryPlyMesh (const std::string &path, const PlyMesh &mesh)
void SetPRNGSeed (unsigned seed)
template<typename T >
T RandomInteger (const T min, const T max)
template<typename T >
T RandomReal (const T min, const T max)
template<typename T >
T RandomGaussian (const T mean, const T stddev)
template<typename T >
void Shuffle (const uint32_t num_to_shuffle, std::vector< T > *elems)
int SQLite3CallHelper (const int result_code, const std::string &filename, const int line_number)
std::string StringPrintf (const char *format,...)
std::string StringReplace (const std::string &str, const std::string &old_str, const std::string &new_str)
std::string StringGetAfter (const std::string &str, const std::string &key)
std::vector< std::string > StringSplit (const std::string &str, const std::string &delim)
bool StringStartsWith (const std::string &str, const std::string &prefix)
void StringLeftTrim (std::string *str)
void StringRightTrim (std::string *str)
void StringTrim (std::string *str)
void StringToLower (std::string *str)
void StringToUpper (std::string *str)
bool StringContains (const std::string &str, const std::string &sub_str)
int GetEffectiveNumThreads (const int num_threads)
std::string GetVersionInfo ()
std::string GetBuildInfo ()
Variables
static const std::unordered_map< std::string, int > CAMERA_MODEL_NAME_TO_ID
static const std::unordered_map< int, std::string > CAMERA_MODEL_ID_TO_NAME
static const std::vector< size_t > EMPTY_IDXS
static const int kInvalidCameraModelId = -1
const bool kUseOpenGL = false
thread_local std::unique_ptr< std::mt19937 > PRNG
static int kDefaultPRNGSeed = 0
const camera_t kInvalidCameraId = std::numeric_limits<camera_t>::max()
const image_t kInvalidImageId = std::numeric_limits<image_t>::max()
const image_pair_t kInvalidImagePairId
const point2D_t kInvalidPoint2DIdx = std::numeric_limits<point2D_t>::max()
const point3D_t kInvalidPoint3DId = std::numeric_limits<point3D_t>::max()
Typedef Documentation
camera_make_specs_t
typedef std::vector<std::pair<std::string, float> > colmap::camera_make_specs_t
Definition at line 17 of file camera_specs.h.
camera_specs_t
typedef std::unordered_map<std::string, camera_make_specs_t> colmap::camera_specs_t
Definition at line 18 of file camera_specs.h.
camera_t
typedef uint32_t colmap::camera_t
Definition at line 58 of file types.h.
EuclideanTransformEstimator
template<int kDim> using colmap::EuclideanTransformEstimator = typedef SimilarityTransformEstimator<kDim, false>
Definition at line 27 of file euclidean_transform.h.
FeatureDescriptor
typedef Eigen::Matrix<uint8_t, 1, Eigen::Dynamic, Eigen::RowMajor> colmap::FeatureDescriptor
Definition at line 62 of file types.h.
FeatureDescriptors
typedef Eigen::Matrix<uint8_t, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> colmap::FeatureDescriptors
Definition at line 79 of file types.h.
FeatureKeypoints
typedef std::vector<FeatureKeypoint> colmap::FeatureKeypoints
Definition at line 77 of file types.h.
FeatureMatches
typedef std::vector<FeatureMatch> colmap::FeatureMatches
Definition at line 80 of file types.h.
image_pair_t
typedef uint64_t colmap::image_pair_t
Definition at line 64 of file types.h.
image_t
typedef uint32_t colmap::image_t
Definition at line 61 of file types.h.
point2D_t
typedef uint32_t colmap::point2D_t
Definition at line 67 of file types.h.
point3D_t
typedef uint64_t colmap::point3D_t
Definition at line 72 of file types.h.
Enumeration Type Documentation
CopyType
enum colmap::CopyType strong
Enumerator
COPY
HARD_LINK
SOFT_LINK
Definition at line 27 of file misc.h.
LineSegmentOrientation
enum colmap::LineSegmentOrientation strong
Enumerator
HORIZONTAL
VERTICAL
UNDEFINED
Definition at line 22 of file line.h.
Function Documentation
__CheckOptionImpl()
bool colmap::__CheckOptionImpl (const char * file, const int line, const bool result, const char * expr_str)
Definition at line 51 of file logging.cc.
References __GetConstFileBaseName(), result, and StringPrintf().
__CheckOptionOpImpl()
template<typename T1 , typename T2 > bool colmap::__CheckOptionOpImpl (const char * file, const int line, const bool result, const T1 & val1, const T2 & val2, const char * val1_str, const char * val2_str, const char * op_str)
Definition at line 53 of file logging.h.
References __GetConstFileBaseName(), result, StringPrintf(), and patch::to_string().
__GetConstFileBaseName()
const char * colmap::__GetConstFileBaseName (const char * file)
Definition at line 43 of file logging.cc.
Referenced by __CheckOptionImpl(), and __CheckOptionOpImpl().
AlignToENUPlane()
void colmap::AlignToENUPlane (Reconstruction * recon, SimilarityTransform3 * tform, bool unscaled)
Definition at line 333 of file coordinate_frame.cc.
References ecvColor::LookUpTable::at(), colmap::Reconstruction::ComputeCentroid(), DegToRad(), RotationMatrixToQuaternion(), colmap::SimilarityTransform3::Scale(), colmap::Reconstruction::Transform(), and colmap::GPSTransform::XYZToEll().
Referenced by BOOST_AUTO_TEST_CASE(), and RunModelAligner().
AlignToPrincipalPlane()
void colmap::AlignToPrincipalPlane (Reconstruction * recon, SimilarityTransform3 * tform)
Definition at line 302 of file coordinate_frame.cc.
References colmap::Reconstruction::ComputeCentroid(), colmap::Reconstruction::Images(), colmap::Reconstruction::NumPoints3D(), points, colmap::Reconstruction::Points3D(), colmap::Image::ProjectionCenter(), colmap::Image::Qvec(), RotationMatrixToQuaternion(), colmap::Reconstruction::Transform(), colmap::SimilarityTransform3::TransformPose(), and colmap::Image::Tvec().
Referenced by BOOST_AUTO_TEST_CASE(), and RunModelAligner().
AnyGreaterThan()
template<typename T > bool colmap::AnyGreaterThan (std::vector< T > elems, T threshold)
Definition at line 263 of file math.h.
AnyLessThan()
template<typename T > bool colmap::AnyLessThan (std::vector< T > elems, T threshold)
Definition at line 253 of file math.h.
AverageQuaternions()
Eigen::Vector4d colmap::AverageQuaternions (const std::vector< Eigen::Vector4d > & qvecs, const std::vector< double > & weights)
Definition at line 118 of file pose.cc.
References NormalizeQuaternion().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::CameraRig::ComputeAbsolutePose(), and colmap::CameraRig::ComputeRelativePoses().
BigEndianToNative()
template<typename T > T colmap::BigEndianToNative (const T x)
Definition at line 84 of file endian.h.
References IsBigEndian(), ReverseBytes(), and x.
Referenced by ReadPly().
BitmapToQImageRGB()
QImage colmap::BitmapToQImageRGB (const Bitmap & bitmap)
Definition at line 59 of file qt_utils.cc.
References color, colmap::Bitmap::GetPixel(), colmap::Bitmap::Height(), image, colmap::Bitmap::Width(), x, and y.
Referenced by cloudViewer::FeatureImageViewerWidget::ReadAndShowWithKeypoints(), colmap::FeatureImageViewerWidget::ReadAndShowWithKeypoints(), cloudViewer::FeatureImageViewerWidget::ReadAndShowWithMatches(), colmap::FeatureImageViewerWidget::ReadAndShowWithMatches(), cloudViewer::PointViewerWidget::Show(), colmap::PointViewerWidget::Show(), colmap::ImageViewerWidget::ShowBitmap(), and cloudViewer::ImageViewerWidget::ShowBitmap().
CalculateAngularError() [1/2]
double colmap::CalculateAngularError (const Eigen::Vector2d & point2D, const Eigen::Vector3d & point3D, const Eigen::Matrix3x4d & proj_matrix, const Camera & camera)
Definition at line 160 of file projection.cc.
References CalculateNormalizedAngularError(), and colmap::Camera::ImageToWorld().
CalculateAngularError() [2/2]
double colmap::CalculateAngularError (const Eigen::Vector2d & point2D, const Eigen::Vector3d & point3D, const Eigen::Vector4d & qvec, const Eigen::Vector3d & tvec, const Camera & camera)
Definition at line 151 of file projection.cc.
References CalculateNormalizedAngularError(), and colmap::Camera::ImageToWorld().
Referenced by BOOST_AUTO_TEST_CASE().
CalculateBaseline()
Eigen::Vector3d colmap::CalculateBaseline (const Eigen::Vector4d & qvec1, const Eigen::Vector3d & tvec1, const Eigen::Vector4d & qvec2, const Eigen::Vector3d & tvec2)
Definition at line 216 of file pose.cc.
References ProjectionCenterFromPose().
Referenced by BOOST_AUTO_TEST_CASE().
CalculateDepth()
double colmap::CalculateDepth (const Eigen::Matrix3x4d & proj_matrix, const Eigen::Vector3d & point3D)
Definition at line 185 of file projection.cc.
Referenced by BOOST_AUTO_TEST_CASE(), and CheckCheirality().
CalculateNormalizedAngularError() [1/2]
double colmap::CalculateNormalizedAngularError (const Eigen::Vector2d & point2D, const Eigen::Vector3d & point3D, const Eigen::Matrix3x4d & proj_matrix)
Definition at line 177 of file projection.cc.
CalculateNormalizedAngularError() [2/2]
double colmap::CalculateNormalizedAngularError (const Eigen::Vector2d & point2D, const Eigen::Vector3d & point3D, const Eigen::Vector4d & qvec, const Eigen::Vector3d & tvec)
Definition at line 168 of file projection.cc.
References QuaternionRotatePoint().
Referenced by CalculateAngularError(), and colmap::TriangulationEstimator::Residuals().
CalculateSquaredReprojectionError() [1/2]
double colmap::CalculateSquaredReprojectionError (const Eigen::Vector2d & point2D, const Eigen::Vector3d & point3D, const Eigen::Matrix3x4d & proj_matrix, const Camera & camera)
Definition at line 130 of file projection.cc.
References colmap::Camera::WorldToImage().
CalculateSquaredReprojectionError() [2/2]
double colmap::CalculateSquaredReprojectionError (const Eigen::Vector2d & point2D, const Eigen::Vector3d & point3D, const Eigen::Vector4d & qvec, const Eigen::Vector3d & tvec, const Camera & camera)
Definition at line 111 of file projection.cc.
References QuaternionRotatePoint(), and colmap::Camera::WorldToImage().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::TriangulationEstimator::Residuals().
CalculateTriangulationAngle()
double colmap::CalculateTriangulationAngle (const Eigen::Vector3d & proj_center1, const Eigen::Vector3d & proj_center2, const Eigen::Vector3d & point3D)
Definition at line 122 of file triangulation.cc.
References M_PI.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::mvs::Model::ComputeTriangulationAngles(), colmap::TriangulationEstimator::Estimate(), and colmap::IncrementalMapper::RegisterInitialImagePair().
CalculateTriangulationAngles()
std::vector< double > colmap::CalculateTriangulationAngles (const Eigen::Vector3d & proj_center1, const Eigen::Vector3d & proj_center2, const std::vector< Eigen::Vector3d > & points3D)
Definition at line 147 of file triangulation.cc.
References M_PI.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::TwoViewGeometry::EstimateRelativePose().
CameraModelExtraParamsIdxs()
const std::vector< size_t > & colmap::CameraModelExtraParamsIdxs (const int model_id)
Definition at line 186 of file camera_models.cc.
References CAMERA_MODEL_SWITCH_CASES, and EMPTY_IDXS.
Referenced by colmap::Camera::ExtraParamsIdxs(), and TestModel().
CameraModelFocalLengthIdxs()
const std::vector< size_t > & colmap::CameraModelFocalLengthIdxs (const int model_id)
Definition at line 156 of file camera_models.cc.
References CAMERA_MODEL_SWITCH_CASES, and EMPTY_IDXS.
Referenced by colmap::Camera::FocalLengthIdxs(), and TestModel().
CameraModelHasBogusParams()
bool colmap::CameraModelHasBogusParams (const int model_id, const std::vector< double > & params, const size_t width, const size_t height, const double min_focal_length_ratio, const double max_focal_length_ratio, const double max_extra_param)
Definition at line 233 of file camera_models.cc.
References CAMERA_MODEL_SWITCH_CASES.
Referenced by colmap::Camera::HasBogusParams(), and TestModel().
CameraModelIdToName()
std::string colmap::CameraModelIdToName (const int model_id)
Definition at line 111 of file camera_models.cc.
References CAMERA_MODEL_ID_TO_NAME.
Referenced by colmap::Camera::ModelName(), and TestModel().
CameraModelImageToWorld()
void colmap::CameraModelImageToWorld (const int model_id, const std::vector< double > & params, const double x, const double y, double * u, double * v) inline
Definition at line 1497 of file camera_models.h.
References CAMERA_MODEL_SWITCH_CASES, and colmap::FOVCameraModel::model_id.
Referenced by colmap::Camera::ImageToWorld(), and TestImageToWorldToImage().
CameraModelImageToWorldThreshold()
double colmap::CameraModelImageToWorldThreshold (const int model_id, const std::vector< double > & params, const double threshold) inline
Definition at line 1515 of file camera_models.h.
References CAMERA_MODEL_SWITCH_CASES, and colmap::FOVCameraModel::model_id.
Referenced by colmap::Camera::ImageToWorldThreshold(), and TestModel().
CameraModelInitializeParams()
std::vector< double > colmap::CameraModelInitializeParams (const int model_id, const double focal_length, const size_t width, const size_t height)
Definition at line 120 of file camera_models.cc.
References CAMERA_MODEL_SWITCH_CASES.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Camera::InitializeWithId(), and TestModel().
CameraModelNameToId()
int colmap::CameraModelNameToId (const std::string & model_name)
Definition at line 102 of file camera_models.cc.
References CAMERA_MODEL_NAME_TO_ID, and kInvalidCameraModelId.
Referenced by colmap::ImageReaderOptions::Check(), colmap::Camera::InitializeWithName(), colmap::Camera::SetModelIdFromName(), and TestModel().
CameraModelNumParams()
size_t colmap::CameraModelNumParams (const int model_id)
Definition at line 201 of file camera_models.cc.
References CAMERA_MODEL_SWITCH_CASES.
Referenced by colmap::Camera::SetModelId(), colmap::Camera::SetModelIdFromName(), and TestModel().
CameraModelParamsInfo()
std::string colmap::CameraModelParamsInfo (const int model_id)
Definition at line 139 of file camera_models.cc.
References CAMERA_MODEL_SWITCH_CASES.
Referenced by colmap::Camera::ParamsInfo(), and TestModel().
CameraModelPrincipalPointIdxs()
const std::vector< size_t > & colmap::CameraModelPrincipalPointIdxs (const int model_id)
Definition at line 171 of file camera_models.cc.
References CAMERA_MODEL_SWITCH_CASES, and EMPTY_IDXS.
Referenced by colmap::Camera::PrincipalPointIdxs(), and TestModel().
CameraModelVerifyParams()
bool colmap::CameraModelVerifyParams (const int model_id, const std::vector< double > & params)
Definition at line 215 of file camera_models.cc.
References CAMERA_MODEL_SWITCH_CASES.
Referenced by colmap::ImageReaderOptions::Check(), colmap::Camera::SetParamsFromString(), TestModel(), and colmap::Camera::VerifyParams().
CameraModelWorldToImage()
void colmap::CameraModelWorldToImage (const int model_id, const std::vector< double > & params, const double u, const double v, double * x, double * y) inline
Definition at line 1479 of file camera_models.h.
References CAMERA_MODEL_SWITCH_CASES, and colmap::FOVCameraModel::model_id.
Referenced by TestWorldToImageToWorld(), and colmap::Camera::WorldToImage().
CenterAndNormalizeImagePoints()
void colmap::CenterAndNormalizeImagePoints (const std::vector< Eigen::Vector2d > & points, std::vector< Eigen::Vector2d > * normed_points, Eigen::Matrix3d * matrix)
Definition at line 38 of file utils.cc.
References points.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::EssentialMatrixEightPointEstimator::Estimate(), colmap::FundamentalMatrixEightPointEstimator::Estimate(), and colmap::HomographyMatrixEstimator::Estimate().
CheckCheirality()
bool colmap::CheckCheirality (const Eigen::Matrix3d & R, const Eigen::Vector3d & t, const std::vector< Eigen::Vector2d > & points1, const std::vector< Eigen::Vector2d > & points2, std::vector< Eigen::Vector3d > * points3D)
Definition at line 225 of file pose.cc.
References CalculateDepth(), ComposeProjectionMatrix(), and TriangulatePoint().
Referenced by BOOST_AUTO_TEST_CASE(), PoseFromEssentialMatrix(), and PoseFromHomographyMatrix().
ClassifyLineSegmentOrientations()
std::vector< LineSegmentOrientation > colmap::ClassifyLineSegmentOrientations (const std::vector< LineSegment > & segments, const double tolerance)
Definition at line 79 of file line.cc.
References HORIZONTAL, UNDEFINED, and VERTICAL.
Referenced by BOOST_AUTO_TEST_CASE(), and EstimateManhattanWorldFrame().
Clip()
template<typename T > T colmap::Clip (const T & value, const T & low, const T & high) inline
Definition at line 167 of file math.h.
Referenced by BOOST_AUTO_TEST_CASE(), and UndistortCamera().
CompleteAndMergeTracks()
size_t colmap::CompleteAndMergeTracks (const IncrementalMapperOptions & options, IncrementalMapper * mapper)
Definition at line 163 of file incremental_mapper.cc.
References colmap::IncrementalMapper::CompleteTracks(), QtCompat::endl(), colmap::IncrementalMapper::MergeTracks(), and colmap::IncrementalMapperOptions::Triangulation().
Referenced by RunPointTriangulator().
ComposeIdentityQuaternion()
Eigen::Vector4d colmap::ComposeIdentityQuaternion () inline
Definition at line 209 of file pose.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::CameraRig::ComputeRelativePoses(), GenerateReconstruction(), colmap::Reconstruction::Normalize(), and colmap::IncrementalMapper::RegisterInitialImagePair().
ComposeProjectionMatrix() [1/2]
Eigen::Matrix3x4d colmap::ComposeProjectionMatrix (const Eigen::Matrix3d & R, const Eigen::Vector3d & T)
Definition at line 47 of file projection.cc.
ComposeProjectionMatrix() [2/2]
Eigen::Matrix3x4d colmap::ComposeProjectionMatrix (const Eigen::Vector4d & qvec, const Eigen::Vector3d & tvec)
Definition at line 39 of file projection.cc.
References QuaternionToRotationMatrix().
Referenced by BOOST_AUTO_TEST_CASE(), CheckCheirality(), colmap::Image::InverseProjectionMatrix(), colmap::Image::ProjectionMatrix(), colmap::SimilarityTransform3::SimilarityTransform3(), and colmap::SimilarityTransform3::TransformPose().
ComputeAlignmentBetweenReconstructions()
bool colmap::ComputeAlignmentBetweenReconstructions (const Reconstruction & src_reconstruction, const Reconstruction & ref_reconstruction, const double min_inlier_observations, const double max_reproj_error, Eigen::Matrix3x4d * alignment)
Definition at line 272 of file similarity_transform.cc.
References colmap::LORANSAC< Estimator, LocalEstimator, SupportMeasurer, Sampler >::Estimate(), colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::estimator, colmap::Reconstruction::FindCommonRegImageIds(), colmap::Reconstruction::Image(), colmap::LORANSAC< Estimator, LocalEstimator, SupportMeasurer, Sampler >::local_estimator, colmap::RANSACOptions::max_error, and colmap::RANSACOptions::min_inlier_ratio.
Referenced by colmap::Reconstruction::Merge(), and RunModelComparer().
ComputeClosestRotationMatrix()
Eigen::Matrix3d colmap::ComputeClosestRotationMatrix (const Eigen::Matrix3d & matrix)
Definition at line 62 of file projection.cc.
Referenced by BOOST_AUTO_TEST_CASE(), and DecomposeProjectionMatrix().
ComputeDepthsSylvesterCoeffs()
Eigen::Matrix< double, 9, 1 > colmap::ComputeDepthsSylvesterCoeffs (const Eigen::Matrix< double, 3, 6 > & K)
Definition at line 36 of file generalized_absolute_pose_coeffs.cc.
References coeffs(), and t12.
ComputeMinGraphCutStoerWagner()
void colmap::ComputeMinGraphCutStoerWagner (const std::vector< std::pair< int, int >> & edges, const std::vector< int > & weights, int * cut_weight, std::vector< char > * cut_labels)
Definition at line 150 of file graph_cut.cc.
References vertex_index.
Referenced by BOOST_AUTO_TEST_CASE().
ComputeNormalizedMinGraphCut()
std::unordered_map< int, int > colmap::ComputeNormalizedMinGraphCut (const std::vector< std::pair< int, int >> & edges, const std::vector< int > & weights, const int num_parts)
Definition at line 186 of file graph_cut.cc.
Referenced by BOOST_AUTO_TEST_CASE().
ComputeRelativePose()
void colmap::ComputeRelativePose (const Eigen::Vector4d & qvec1, const Eigen::Vector3d & tvec1, const Eigen::Vector4d & qvec2, const Eigen::Vector3d & tvec2, Eigen::Vector4d * qvec12, Eigen::Vector3d * tvec12)
Definition at line 173 of file pose.cc.
References ConcatenateQuaternions(), InvertQuaternion(), and QuaternionRotatePoint().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::CameraRig::ComputeRelativePoses().
ComputeSquaredReprojectionError()
void colmap::ComputeSquaredReprojectionError (const std::vector< Eigen::Vector2d > & points2D, const std::vector< Eigen::Vector3d > & points3D, const Eigen::Matrix3x4d & proj_matrix, std::vector< double > * residuals)
Definition at line 133 of file utils.cc.
Referenced by colmap::P3PEstimator::Residuals(), and colmap::EPNPEstimator::Residuals().
ComputeSquaredSampsonError()
void colmap::ComputeSquaredSampsonError (const std::vector< Eigen::Vector2d > & points1, const std::vector< Eigen::Vector2d > & points2, const Eigen::Matrix3d & E, std::vector< double > * residuals)
Definition at line 87 of file utils.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::EssentialMatrixFivePointEstimator::Residuals(), colmap::EssentialMatrixEightPointEstimator::Residuals(), colmap::FundamentalMatrixSevenPointEstimator::Residuals(), and colmap::FundamentalMatrixEightPointEstimator::Residuals().
ConcatenatePoses()
void colmap::ConcatenatePoses (const Eigen::Vector4d & qvec1, const Eigen::Vector3d & tvec1, const Eigen::Vector4d & qvec2, const Eigen::Vector3d & tvec2, Eigen::Vector4d * qvec12, Eigen::Vector3d * tvec12)
Definition at line 183 of file pose.cc.
References ConcatenateQuaternions(), and QuaternionRotatePoint().
Referenced by BOOST_AUTO_TEST_CASE().
ConcatenateQuaternions()
Eigen::Vector4d colmap::ConcatenateQuaternions (const Eigen::Vector4d & qvec1, const Eigen::Vector4d & qvec2)
Definition at line 97 of file pose.cc.
References NormalizeQuaternion().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::CameraRig::ComputeAbsolutePose(), ComputeRelativePose(), and ConcatenatePoses().
CreateDirIfNotExists()
void colmap::CreateDirIfNotExists (const std::string & path)
Definition at line 112 of file misc.cc.
References ExistsDir(), and cloudViewer::t::geometry::path.
Referenced by colmap::Reconstruction::CreateImageDirs(), colmap::Reconstruction::ExportRecon3D(), colmap::mvs::ImportPMVSWorkspace(), colmap::AutomaticReconstructionController::RunDenseMapper(), RunImageTexturer(), RunImageUndistorter(), RunImageUndistorterStandalone(), RunModelSplitter(), and colmap::ReconstructionManager::Write().
CreateSiftGPUExtractor()
bool colmap::CreateSiftGPUExtractor (const SiftExtractionOptions & options, SiftGPU * sift_gpu)
Definition at line 776 of file sift.cc.
References colmap::SiftExtractionOptions::Check(), colmap::SiftExtractionOptions::darkness_adaptivity, colmap::SiftExtractionOptions::edge_threshold, colmap::SiftExtractionOptions::first_octave, colmap::SiftExtractionOptions::gpu_index, colmap::SiftExtractionOptions::max_image_size, colmap::SiftExtractionOptions::max_num_features, colmap::SiftExtractionOptions::max_num_orientations, colmap::SiftExtractionOptions::octave_resolution, colmap::SiftExtractionOptions::peak_threshold, patch::to_string(), and colmap::SiftExtractionOptions::upright.
Referenced by BOOST_AUTO_TEST_CASE().
CreateSiftGPUMatcher()
bool colmap::CreateSiftGPUMatcher (const SiftMatchingOptions & match_options, SiftMatchGPU * sift_match_gpu)
Definition at line 1124 of file sift.cc.
References colmap::SiftMatchingOptions::Check(), colmap::SiftMatchingOptions::cross_check, QtCompat::endl(), colmap::SiftMatchingOptions::gpu_index, colmap::SiftMatchingOptions::max_num_matches, and StringPrintf().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::SiftGPUFeatureMatcher::Run().
CrossProductMatrix()
Eigen::Matrix3d colmap::CrossProductMatrix (const Eigen::Vector3d & vector)
Definition at line 41 of file pose.cc.
Referenced by BOOST_AUTO_TEST_CASE(), EssentialMatrixFromPose(), and RotationFromUnitVectors().
CSVToVector()
template<> std::vector< double > colmap::CSVToVector (const std::string & csv)
Definition at line 237 of file misc.cc.
References StringSplit(), and StringTrim().
CudaCheck()
void colmap::CudaCheck (const char * file, const int line)
Definition at line 68 of file cudacc.cc.
References QtCompat::endl(), and StringPrintf().
CudaSafeCall()
void colmap::CudaSafeCall (const cudaError_t error, const std::string & file, const int line)
Definition at line 58 of file cudacc.cc.
References QtCompat::endl(), and StringPrintf().
CudaSyncAndCheck()
void colmap::CudaSyncAndCheck (const char * file, const int line)
Definition at line 78 of file cudacc.cc.
References QtCompat::endl(), and StringPrintf().
DecomposeEssentialMatrix()
void colmap::DecomposeEssentialMatrix (const Eigen::Matrix3d & E, Eigen::Matrix3d * R1, Eigen::Matrix3d * R2, Eigen::Vector3d * t)
Definition at line 41 of file essential_matrix.cc.
Referenced by BOOST_AUTO_TEST_CASE(), and PoseFromEssentialMatrix().
DecomposeHomographyMatrix()
void colmap::DecomposeHomographyMatrix (const Eigen::Matrix3d & H, const Eigen::Matrix3d & K1, const Eigen::Matrix3d & K2, std::vector< Eigen::Matrix3d > * R, std::vector< Eigen::Vector3d > * t, std::vector< Eigen::Vector3d > * n)
Definition at line 65 of file homography_matrix.cc.
References Utils::distance(), e, and SignOfNumber().
Referenced by BOOST_AUTO_TEST_CASE(), and PoseFromHomographyMatrix().
DecomposeMatrixRQ()
template<typename MatrixType > void colmap::DecomposeMatrixRQ (const MatrixType & A, MatrixType * R, MatrixType * Q)
Definition at line 45 of file matrix.h.
Referenced by BOOST_AUTO_TEST_CASE(), and DecomposeProjectionMatrix().
DecomposeProjectionMatrix()
bool colmap::DecomposeProjectionMatrix (const Eigen::Matrix3x4d & P, Eigen::Matrix3d * K, Eigen::Matrix3d * R, Eigen::Vector3d * T)
Definition at line 72 of file projection.cc.
References ComputeClosestRotationMatrix(), and DecomposeMatrixRQ().
Referenced by BOOST_AUTO_TEST_CASE().
DegToRad() [1/2]
double colmap::DegToRad (const double deg) inline
Definition at line 175 of file math.h.
DegToRad() [2/2]
float colmap::DegToRad (const float deg) inline
Definition at line 171 of file math.h.
Referenced by AlignToENUPlane(), BOOST_AUTO_TEST_CASE(), colmap::IncrementalTriangulator::CompleteImage(), colmap::GPSTransform::EllToXYZ(), colmap::mvs::Model::GetMaxOverlappingImages(), colmap::IncrementalMapper::RegisterInitialImagePair(), and cloudViewer::ModelViewerWidget::ZoomScale().
DetectLineSegments()
std::vector< LineSegment > colmap::DetectLineSegments (const Bitmap & bitmap, const double min_length)
Definition at line 42 of file line.cc.
References colmap::Bitmap::CloneAsGrey(), colmap::Bitmap::ConvertToRowMajorArray(), colmap::Bitmap::Height(), colmap::Bitmap::IsGrey(), and colmap::Bitmap::Width().
Referenced by BOOST_AUTO_TEST_CASE(), and EstimateManhattanWorldFrame().
DownsampleImage()
void colmap::DownsampleImage (const float * data, const int rows, const int cols, const int new_rows, const int new_cols, float * downsampled)
Definition at line 226 of file warp.cc.
References data, ResampleImageBilinear(), and SmoothImage().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::mvs::DepthMap::Rescale(), and colmap::mvs::NormalMap::Rescale().
DrawKeypoints()
void colmap::DrawKeypoints (QPixmap * pixmap, const FeatureKeypoints & points, const QColor & color)
Definition at line 86 of file qt_utils.cc.
References color, and points.
Referenced by cloudViewer::FeatureImageViewerWidget::ReadAndShowWithKeypoints(), and colmap::FeatureImageViewerWidget::ReadAndShowWithKeypoints().
DrawMatches()
QPixmap colmap::DrawMatches (const QPixmap & image1, const QPixmap & image2, const FeatureKeypoints & points1, const FeatureKeypoints & points2, const FeatureMatches & matches, const QColor & keypoints_color)
Definition at line 109 of file qt_utils.cc.
References image, ShowImagesSideBySide(), x, and y.
Referenced by cloudViewer::FeatureImageViewerWidget::ReadAndShowWithMatches(), and colmap::FeatureImageViewerWidget::ReadAndShowWithMatches().
EigenToQMatrix()
QMatrix4x4 colmap::EigenToQMatrix (const Eigen::Matrix4f & matrix)
Definition at line 49 of file qt_utils.cc.
EnsureTrailingSlash()
std::string colmap::EnsureTrailingSlash (const std::string & str)
Definition at line 40 of file misc.cc.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::ExportRecon3D().
EpipoleFromEssentialMatrix()
Eigen::Vector3d colmap::EpipoleFromEssentialMatrix (const Eigen::Matrix3d & E, const bool left_image)
Definition at line 142 of file essential_matrix.cc.
References e.
Referenced by BOOST_AUTO_TEST_CASE().
EssentialMatrixFromAbsolutePoses()
Eigen::Matrix3d colmap::EssentialMatrixFromAbsolutePoses (const Eigen::Matrix3x4d & proj_matrix1, const Eigen::Matrix3x4d & proj_matrix2)
Definition at line 95 of file essential_matrix.cc.
References EssentialMatrixFromPose().
Referenced by BOOST_AUTO_TEST_CASE(), and TriangulateOptimalPoint().
EssentialMatrixFromPose()
Eigen::Matrix3d colmap::EssentialMatrixFromPose (const Eigen::Matrix3d & R, const Eigen::Vector3d & t)
Definition at line 90 of file essential_matrix.cc.
References CrossProductMatrix().
Referenced by BOOST_AUTO_TEST_CASE(), EssentialMatrixFromAbsolutePoses(), RefineEssentialMatrix(), and colmap::GR6PEstimator::Residuals().
EstimateAbsolutePose()
bool colmap::EstimateAbsolutePose (const AbsolutePoseEstimationOptions & options, const std::vector< Eigen::Vector2d > & points2D, const std::vector< Eigen::Vector3d > & points3D, Eigen::Vector4d * qvec, Eigen::Vector3d * tvec, Camera * camera, size_t * num_inliers, std::vector< char > * inlier_mask)
Definition at line 79 of file pose.cc.
References colmap::ThreadPool::AddTask(), colmap::AbsolutePoseEstimationOptions::Check(), colmap::AbsolutePoseEstimationOptions::estimate_focal_length, colmap::Camera::FocalLengthIdxs(), IsNaN(), colmap::AbsolutePoseEstimationOptions::max_focal_length_ratio, colmap::AbsolutePoseEstimationOptions::min_focal_length_ratio, colmap::AbsolutePoseEstimationOptions::num_focal_length_samples, colmap::AbsolutePoseEstimationOptions::num_threads, colmap::Camera::Params(), colmap::AbsolutePoseEstimationOptions::ransac_options, and RotationMatrixToQuaternion().
Referenced by colmap::IncrementalMapper::RegisterNextImage().
EstimateGravityVectorFromImageOrientation()
Eigen::Vector3d colmap::EstimateGravityVectorFromImageOrientation (const Reconstruction & reconstruction, const double max_axis_distance)
Definition at line 145 of file coordinate_frame.cc.
References image, colmap::Reconstruction::Image(), colmap::Reconstruction::NumRegImages(), and colmap::Reconstruction::RegImageIds().
Referenced by BOOST_AUTO_TEST_CASE(), and RunModelOrientationAligner().
EstimateManhattanWorldFrame()
Eigen::Matrix3d colmap::EstimateManhattanWorldFrame (const ManhattanWorldFrameEstimationOptions & options, const Reconstruction & reconstruction, const std::string & image_path)
Definition at line 156 of file coordinate_frame.cc.
References colmap::Camera::CalibrationMatrix(), colmap::Reconstruction::Camera(), ClassifyLineSegmentOrientations(), DetectLineSegments(), QtCompat::endl(), colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::Estimate(), frame, HORIZONTAL, image, colmap::Reconstruction::Image(), InvertQuaternion(), JoinPaths(), colmap::ManhattanWorldFrameEstimationOptions::line_orientation_tolerance, colmap::ManhattanWorldFrameEstimationOptions::max_axis_distance, colmap::RANSACOptions::max_error, colmap::UndistortCameraOptions::max_image_size, colmap::ManhattanWorldFrameEstimationOptions::max_image_size, colmap::ManhattanWorldFrameEstimationOptions::max_line_vp_distance, colmap::ManhattanWorldFrameEstimationOptions::min_line_length, colmap::Reconstruction::NumRegImages(), PrintHeading1(), QuaternionRotatePoint(), colmap::Bitmap::Read(), colmap::Reconstruction::RegImageIds(), StringPrintf(), UndistortImage(), and VERTICAL.
Referenced by BOOST_AUTO_TEST_CASE(), and RunModelOrientationAligner().
EstimateRelativePose()
size_t colmap::EstimateRelativePose (const RANSACOptions & ransac_options, const std::vector< Eigen::Vector2d > & points1, const std::vector< Eigen::Vector2d > & points2, Eigen::Vector4d * qvec, Eigen::Vector3d * tvec)
Definition at line 164 of file pose.cc.
References colmap::RANSAC< Estimator, SupportMeasurer, Sampler >::Estimate(), IsNaN(), PoseFromEssentialMatrix(), and RotationMatrixToQuaternion().
EstimateTriangulation()
bool colmap::EstimateTriangulation (const EstimateTriangulationOptions & options, const std::vector< TriangulationEstimator::PointData > & point_data, const std::vector< TriangulationEstimator::PoseData > & pose_data, std::vector< char > * inlier_mask, Eigen::Vector3d * xyz)
Definition at line 132 of file triangulation.cc.
References colmap::EstimateTriangulationOptions::Check(), colmap::EstimateTriangulationOptions::min_tri_angle, colmap::EstimateTriangulationOptions::ransac_options, and colmap::EstimateTriangulationOptions::residual_type.
Referenced by colmap::IncrementalTriangulator::CompleteImage().
EulerAnglesToRotationMatrix()
Eigen::Matrix3d colmap::EulerAnglesToRotationMatrix (const double rx, const double ry, const double rz)
Definition at line 59 of file pose.cc.
Referenced by BOOST_AUTO_TEST_CASE().
EvaluatePolynomial()
template<typename T > T colmap::EvaluatePolynomial (const Eigen::VectorXd & coeffs, const T & x)
Definition at line 68 of file polynomial.h.
References coeffs(), and x.
Referenced by BOOST_AUTO_TEST_CASE().
ExistsCameraModelWithId()
bool colmap::ExistsCameraModelWithId (const int model_id)
Definition at line 98 of file camera_models.cc.
References CAMERA_MODEL_ID_TO_NAME.
Referenced by colmap::Camera::InitializeWithId(), colmap::Camera::SetModelId(), and TestModel().
ExistsCameraModelWithName()
bool colmap::ExistsCameraModelWithName (const std::string & model_name)
Definition at line 94 of file camera_models.cc.
References CAMERA_MODEL_NAME_TO_ID.
Referenced by colmap::ImageReaderOptions::Check(), RunFeatureExtractor(), RunImageUndistorterStandalone(), colmap::Camera::SetModelIdFromName(), and TestModel().
ExistsDir()
bool colmap::ExistsDir (const std::string & path)
Definition at line 104 of file misc.cc.
References cloudViewer::t::geometry::path.
Referenced by colmap::OptionManager::Check(), CreateDirIfNotExists(), cloudViewer::ProjectWidget::IsValid(), cloudViewer::UndistortionWidget::IsValid(), colmap::ProjectWidget::IsValid(), colmap::UndistortionWidget::IsValid(), cloudViewer::AutomaticReconstructionWidget::Run(), colmap::AutomaticReconstructionWidget::Run(), cloudViewer::SIFTExtractionWidget::Run(), cloudViewer::ImportFeaturesWidget::Run(), colmap::ImportFeaturesWidget::Run(), RunBundleAdjuster(), colmap::AutomaticReconstructionController::RunDenseMapper(), RunHierarchicalMapper(), RunImageRegistrator(), RunImageTexturer(), RunMapper(), RunModelComparer(), RunModelCropper(), RunModelSplitter(), RunModelTransformer(), and RunPointTriangulator().
ExistsFile()
bool colmap::ExistsFile (const std::string & path)
Definition at line 100 of file misc.cc.
References cloudViewer::t::geometry::path.
Referenced by colmap::mvs::GenerateCandidate(), colmap::mvs::Workspace::HasBitmap(), colmap::mvs::Workspace::HasDepthMap(), colmap::mvs::Workspace::HasNormalMap(), cloudViewer::ReconstructionWidget::iniEnvironment(), colmap::ImageReader::Next(), colmap::Reconstruction::Read(), colmap::OptionManager::Read(), colmap::Bitmap::Read(), cloudViewer::SequentialMatchingTab::Run(), cloudViewer::VocabTreeMatchingTab::Run(), cloudViewer::CustomMatchingTab::Run(), colmap::SequentialMatchingTab::Run(), colmap::VocabTreeMatchingTab::Run(), colmap::CustomMatchingTab::Run(), RunDatabaseMerger(), colmap::AutomaticReconstructionController::RunDenseMapper(), and RunImageTexturer().
ExistsPath()
bool colmap::ExistsPath (const std::string & path)
Definition at line 108 of file misc.cc.
References cloudViewer::t::geometry::path.
ExtractCovariantSiftFeaturesCPU()
bool colmap::ExtractCovariantSiftFeaturesCPU (const SiftExtractionOptions & options, const Bitmap & bitmap, FeatureKeypoints * keypoints, FeatureDescriptors * descriptors)
Definition at line 599 of file sift.cc.
References colmap::FeatureKeypoint::a11, colmap::FeatureKeypoint::a12, colmap::FeatureKeypoint::a21, colmap::FeatureKeypoint::a22, colmap::SiftExtractionOptions::Check(), colmap::Bitmap::ConvertToRowMajorArray(), colmap::SiftExtractionOptions::darkness_adaptivity, descriptors, colmap::SiftExtractionOptions::domain_size_pooling, colmap::SiftExtractionOptions::dsp_max_scale, colmap::SiftExtractionOptions::dsp_min_scale, colmap::SiftExtractionOptions::dsp_num_scales, colmap::SiftExtractionOptions::edge_threshold, colmap::SiftExtractionOptions::estimate_affine_shape, FeatureDescriptorsToUnsignedByte(), colmap::SiftExtractionOptions::first_octave, colmap::Bitmap::Height(), colmap::Bitmap::IsGrey(), colmap::SiftExtractionOptions::L1_ROOT, L1RootNormalizeFeatureDescriptors(), colmap::SiftExtractionOptions::L2, L2NormalizeFeatureDescriptors(), colmap::SiftExtractionOptions::max_num_features, colmap::SiftExtractionOptions::normalization, colmap::SiftExtractionOptions::octave_resolution, colmap::SiftExtractionOptions::peak_threshold, colmap::SiftExtractionOptions::upright, colmap::Bitmap::Width(), colmap::FeatureKeypoint::x, and colmap::FeatureKeypoint::y.
Referenced by BOOST_AUTO_TEST_CASE().
ExtractSiftFeaturesCPU()
bool colmap::ExtractSiftFeaturesCPU (const SiftExtractionOptions & options, const Bitmap & bitmap, FeatureKeypoints * keypoints, FeatureDescriptors * descriptors)
Definition at line 419 of file sift.cc.
References colmap::SiftExtractionOptions::Check(), colmap::Bitmap::ConvertToRowMajorArray(), colmap::SiftExtractionOptions::darkness_adaptivity, descriptors, colmap::SiftExtractionOptions::domain_size_pooling, colmap::SiftExtractionOptions::edge_threshold, colmap::SiftExtractionOptions::estimate_affine_shape, FeatureDescriptorsToUnsignedByte(), colmap::SiftExtractionOptions::first_octave, colmap::Bitmap::Height(), colmap::Bitmap::IsGrey(), colmap::SiftExtractionOptions::L1_ROOT, L1RootNormalizeFeatureDescriptors(), colmap::SiftExtractionOptions::L2, L2NormalizeFeatureDescriptors(), colmap::SiftExtractionOptions::max_num_features, colmap::SiftExtractionOptions::max_num_orientations, colmap::SiftExtractionOptions::normalization, colmap::SiftExtractionOptions::num_octaves, colmap::SiftExtractionOptions::octave_resolution, colmap::SiftExtractionOptions::peak_threshold, colmap::SiftExtractionOptions::upright, colmap::Bitmap::Width(), x, and y.
Referenced by BOOST_AUTO_TEST_CASE().
ExtractSiftFeaturesGPU()
bool colmap::ExtractSiftFeaturesGPU (const SiftExtractionOptions & options, const Bitmap & bitmap, SiftGPU * sift_gpu, FeatureKeypoints * keypoints, FeatureDescriptors * descriptors)
Definition at line 875 of file sift.cc.
References colmap::SiftExtractionOptions::Check(), colmap::Bitmap::ConvertToRawBits(), descriptors, colmap::SiftExtractionOptions::domain_size_pooling, colmap::SiftExtractionOptions::estimate_affine_shape, FeatureDescriptorsToUnsignedByte(), colmap::SiftExtractionOptions::first_octave, colmap::Bitmap::Height(), colmap::Bitmap::IsGrey(), colmap::SiftExtractionOptions::L1_ROOT, L1RootNormalizeFeatureDescriptors(), colmap::SiftExtractionOptions::L2, L2NormalizeFeatureDescriptors(), colmap::SiftExtractionOptions::max_image_size, colmap::SiftExtractionOptions::normalization, colmap::Bitmap::ScanWidth(), x, and y.
Referenced by BOOST_AUTO_TEST_CASE().
ExtractTopScaleFeatures()
void colmap::ExtractTopScaleFeatures (FeatureKeypoints * keypoints, FeatureDescriptors * descriptors, const size_t num_features)
Definition at line 79 of file utils.cc.
References descriptors.
Referenced by BOOST_AUTO_TEST_CASE(), and RunVocabTreeRetriever().
FeatureDescriptorsToUnsignedByte()
FeatureDescriptors colmap::FeatureDescriptorsToUnsignedByte (const Eigen::MatrixXf & descriptors)
Definition at line 65 of file utils.cc.
References descriptors.
Referenced by BOOST_AUTO_TEST_CASE(), CreateRandomFeatureDescriptors(), ExtractCovariantSiftFeaturesCPU(), ExtractSiftFeaturesCPU(), and ExtractSiftFeaturesGPU().
FeatureKeypointsToPointsVector()
std::vector< Eigen::Vector2d > colmap::FeatureKeypointsToPointsVector (const FeatureKeypoints & keypoints)
Definition at line 38 of file utils.cc.
References points, x, and y.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::DatabaseCache::Load(), and colmap::TwoViewGeometryVerifier::Run().
FileCopy()
void colmap::FileCopy (const std::string & src_path, const std::string & dst_path, CopyType type)
Definition at line 85 of file misc.cc.
References COPY, HARD_LINK, SOFT_LINK, and type.
FilterImages()
size_t colmap::FilterImages (const IncrementalMapperOptions & options, IncrementalMapper * mapper)
Definition at line 156 of file incremental_mapper.cc.
References QtCompat::endl(), colmap::IncrementalMapper::FilterImages(), and colmap::IncrementalMapperOptions::Mapper().
FilterPoints()
size_t colmap::FilterPoints (const IncrementalMapperOptions & options, IncrementalMapper * mapper)
Definition at line 147 of file incremental_mapper.cc.
References QtCompat::endl(), colmap::IncrementalMapper::FilterPoints(), and colmap::IncrementalMapperOptions::Mapper().
Referenced by RunPointTriangulator().
FindLinearPolynomialRoots()
bool colmap::FindLinearPolynomialRoots (const Eigen::VectorXd & coeffs, Eigen::VectorXd * real, Eigen::VectorXd * imag)
Definition at line 65 of file polynomial.cc.
References coeffs().
Referenced by BOOST_AUTO_TEST_CASE(), FindPolynomialRootsCompanionMatrix(), FindPolynomialRootsDurandKerner(), and FindQuadraticPolynomialRoots().
FindOptimalImageObservations()
void colmap::FindOptimalImageObservations (const Eigen::Matrix3d & E, const Eigen::Vector2d & point1, const Eigen::Vector2d & point2, Eigen::Vector2d * optimal_point1, Eigen::Vector2d * optimal_point2)
Definition at line 110 of file essential_matrix.cc.
References a.
Referenced by BOOST_AUTO_TEST_CASE(), and TriangulateOptimalPoint().
FindPolynomialRootsCompanionMatrix()
bool colmap::FindPolynomialRootsCompanionMatrix (const Eigen::VectorXd & coeffs_all, Eigen::VectorXd * real, Eigen::VectorXd * imag)
Definition at line 208 of file polynomial.cc.
References coeffs(), FindLinearPolynomialRoots(), and FindQuadraticPolynomialRoots().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::EssentialMatrixFivePointEstimator::Estimate(), colmap::FundamentalMatrixSevenPointEstimator::Estimate(), and colmap::P3PEstimator::Estimate().
FindPolynomialRootsDurandKerner()
bool colmap::FindPolynomialRootsDurandKerner (const Eigen::VectorXd & coeffs_all, Eigen::VectorXd * real, Eigen::VectorXd * imag)
Definition at line 143 of file polynomial.cc.
References coeffs(), e, FindLinearPolynomialRoots(), and FindQuadraticPolynomialRoots().
Referenced by BOOST_AUTO_TEST_CASE().
FindQuadraticPolynomialRoots()
bool colmap::FindQuadraticPolynomialRoots (const Eigen::VectorXd & coeffs, Eigen::VectorXd * real, Eigen::VectorXd * imag)
Definition at line 86 of file polynomial.cc.
References a, coeffs(), and FindLinearPolynomialRoots().
Referenced by BOOST_AUTO_TEST_CASE(), FindPolynomialRootsCompanionMatrix(), and FindPolynomialRootsDurandKerner().
GetBuildInfo()
std::string colmap::GetBuildInfo ()
Definition at line 40 of file version.cc.
References StringPrintf().
Referenced by colmap::OptionManager::Parse().
GetCachedFilePath()
std::filesystem::path colmap::GetCachedFilePath (const std::string & uri)
Referenced by cloudViewer::AutomaticReconstructionWidget::Run().
GetDirList()
std::vector< std::string > colmap::GetDirList (const std::string & path)
Definition at line 195 of file misc.cc.
References cloudViewer::t::geometry::path.
GetEffectiveNumThreads()
int colmap::GetEffectiveNumThreads (const int num_threads)
Definition at line 269 of file threading.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::BundleAdjustmentOptions::CreateSolverOptions(), colmap::mvs::Workspace::Load(), RunModelSplitter(), colmap::SiftFeatureExtractor::SiftFeatureExtractor(), and colmap::ThreadPool::ThreadPool().
GetFileList()
std::vector< std::string > colmap::GetFileList (const std::string & path)
Definition at line 171 of file misc.cc.
References cloudViewer::t::geometry::path.
GetFileSize()
size_t colmap::GetFileSize (const std::string & path)
Definition at line 219 of file misc.cc.
References cloudViewer::t::geometry::path.
Referenced by CVTools::FileMappingReader().
GetNumCudaDevices()
int colmap::GetNumCudaDevices ()
Definition at line 57 of file cuda.cc.
Referenced by SetBestCudaDevice(), and colmap::SiftFeatureExtractor::SiftFeatureExtractor().
GetParentDir()
std::string colmap::GetParentDir (const std::string & path)
Definition at line 128 of file misc.cc.
References cloudViewer::t::geometry::path.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::OptionManager::Check(), cloudViewer::ProjectWidget::IsValid(), colmap::ProjectWidget::IsValid(), colmap::ImageReader::Next(), and cloudViewer::SIFTExtractionWidget::Run().
GetPathBaseName()
std::string colmap::GetPathBaseName (const std::string & path)
Definition at line 118 of file misc.cc.
References cloudViewer::t::geometry::path, StringReplace(), and StringSplit().
Referenced by BOOST_AUTO_TEST_CASE().
GetRecursiveDirList()
std::vector< std::string > colmap::GetRecursiveDirList (const std::string & path)
Definition at line 207 of file misc.cc.
References cloudViewer::t::geometry::path.
GetRecursiveFileList()
std::vector< std::string > colmap::GetRecursiveFileList (const std::string & path)
Definition at line 183 of file misc.cc.
References cloudViewer::t::geometry::path.
GetRelativePath()
std::string colmap::GetRelativePath (const std::string & from, const std::string & to)
Definition at line 132 of file misc.cc.
References cloudViewer::t::geometry::path.
Referenced by colmap::ImageReader::Next().
GetVersionInfo()
std::string colmap::GetVersionInfo ()
Definition at line 36 of file version.cc.
References StringPrintf().
Referenced by colmap::OptionManager::Parse().
GLError()
void colmap::GLError (const char * file, const int line) inline
Definition at line 83 of file opengl_utils.h.
HasFileExtension()
bool colmap::HasFileExtension (const std::string & file_name, const std::string & ext)
Definition at line 51 of file misc.cc.
References StringToLower().
Referenced by BOOST_AUTO_TEST_CASE(), and RunModelTransformer().
HasPointPositiveDepth()
bool colmap::HasPointPositiveDepth (const Eigen::Matrix3x4d & proj_matrix, const Eigen::Vector3d & point3D)
Definition at line 191 of file projection.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::TriangulationEstimator::Estimate(), colmap::Reconstruction::FilterObservationsWithNegativeDepth(), GenerateReconstruction(), and colmap::IncrementalMapper::RegisterInitialImagePair().
HomographyMatrixFromPose()
Eigen::Matrix3d colmap::HomographyMatrixFromPose (const Eigen::Matrix3d & K1, const Eigen::Matrix3d & K2, const Eigen::Matrix3d & R, const Eigen::Vector3d & t, const Eigen::Vector3d & n, const double d)
Definition at line 214 of file homography_matrix.cc.
Referenced by BOOST_AUTO_TEST_CASE().
InitializeCameraSpecs()
camera_specs_t colmap::InitializeCameraSpecs ()
Definition at line 36 of file camera_specs.cc.
Referenced by BOOST_AUTO_TEST_CASE().
InitializeGlog()
void colmap::InitializeGlog (char ** argv)
Definition at line 36 of file logging.cc.
Referenced by main().
InitialzeCameraModelIdToName()
std::unordered_map<int, std::string> colmap::InitialzeCameraModelIdToName ()
Definition at line 74 of file camera_models.cc.
References CAMERA_MODEL_CASES.
InitialzeCameraModelNameToId()
CAMERA_MODEL_CASES std::unordered_map<std::string, int> colmap::InitialzeCameraModelNameToId ()
Definition at line 60 of file camera_models.cc.
References CAMERA_MODEL_CASES.
InterpolatePose()
void colmap::InterpolatePose (const Eigen::Vector4d & qvec1, const Eigen::Vector3d & tvec1, const Eigen::Vector4d & qvec2, const Eigen::Vector3d & tvec2, const double t, Eigen::Vector4d * qveci, Eigen::Vector3d * tveci)
Definition at line 198 of file pose.cc.
References NormalizeQuaternion().
Referenced by BOOST_AUTO_TEST_CASE().
InvertEssentialMatrix()
Eigen::Matrix3d colmap::InvertEssentialMatrix (const Eigen::Matrix3d & E)
Definition at line 155 of file essential_matrix.cc.
Referenced by BOOST_AUTO_TEST_CASE().
InvertPose()
void colmap::InvertPose (const Eigen::Vector4d & qvec, const Eigen::Vector3d & tvec, Eigen::Vector4d * inv_qvec, Eigen::Vector3d * inv_tvec)
Definition at line 192 of file pose.cc.
References InvertQuaternion(), and QuaternionRotatePoint().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::CameraRig::ComputeAbsolutePose(), and colmap::TwoViewGeometry::Invert().
InvertProjectionMatrix()
Eigen::Matrix3x4d colmap::InvertProjectionMatrix (const Eigen::Matrix3x4d & proj_matrix)
Definition at line 55 of file projection.cc.
References ProjectionCenterFromMatrix().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Image::InverseProjectionMatrix().
InvertQuaternion()
Eigen::Vector4d colmap::InvertQuaternion (const Eigen::Vector4d & qvec)
Definition at line 93 of file pose.cc.
Referenced by BOOST_AUTO_TEST_CASE(), ComputeRelativePose(), EstimateManhattanWorldFrame(), and InvertPose().
IsBigEndian()
bool colmap::IsBigEndian () inline
Definition at line 66 of file endian.h.
Referenced by BigEndianToNative(), BOOST_AUTO_TEST_CASE(), and NativeToBigEndian().
IsInf() [1/3]
bool colmap::IsInf (const double x) inline
Definition at line 164 of file math.h.
References IsNaN(), and x.
IsInf() [2/3]
template<typename Derived > bool colmap::IsInf (const Eigen::MatrixBase< Derived > & x) inline
Definition at line 40 of file matrix.h.
References x.
IsInf() [3/3]
bool colmap::IsInf (const float x) inline
Definition at line 163 of file math.h.
References IsNaN(), and x.
Referenced by BOOST_AUTO_TEST_CASE().
IsLittleEndian()
bool colmap::IsLittleEndian () inline
Definition at line 58 of file endian.h.
Referenced by BOOST_AUTO_TEST_CASE(), cloudViewer::io::rpc::messages::EndiannessStr(), LittleEndianToNative(), and NativeToLittleEndian().
IsNaN() [1/3]
bool colmap::IsNaN (const double x) inline
Definition at line 161 of file math.h.
References x.
IsNaN() [2/3]
template<typename Derived > bool colmap::IsNaN (const Eigen::MatrixBase< Derived > & x) inline
Definition at line 35 of file matrix.h.
References x.
IsNaN() [3/3]
bool colmap::IsNaN (const float x) inline
Definition at line 160 of file math.h.
References x.
Referenced by BOOST_AUTO_TEST_CASE(), EstimateAbsolutePose(), EstimateRelativePose(), colmap::Image::HasQvecPrior(), colmap::Image::HasTvecPrior(), IsInf(), and RotationMatrixToEulerAngles().
IsURI()
bool colmap::IsURI (const std::string & uri)
Referenced by cloudViewer::AutomaticReconstructionWidget::Run().
JoinPaths()
template<typename... T> std::string colmap::JoinPaths (T const &... paths)
Definition at line 128 of file misc.h.
References cloudViewer::t::geometry::path, and result.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Reconstruction::CreateImageDirs(), EstimateManhattanWorldFrame(), colmap::Reconstruction::ExportCam(), colmap::Reconstruction::ExtractColorsForAllImages(), colmap::Reconstruction::ExtractColorsForImage(), colmap::mvs::ImportPMVSWorkspace(), colmap::ImageReader::Next(), colmap::Reconstruction::Read(), colmap::Reconstruction::ReadBinary(), colmap::mvs::Model::ReadFromCOLMAP(), colmap::Reconstruction::ReadText(), colmap::AutomaticReconstructionController::RunDenseMapper(), RunImageTexturer(), RunModelComparer(), RunModelSplitter(), RunStereoFuser(), colmap::PointViewerWidget::Show(), colmap::DatabaseImageViewerWidget::ShowImageWithId(), colmap::TwoViewInfoTab::ShowMatches(), colmap::ReconstructionManager::Write(), colmap::Reconstruction::WriteBinary(), and colmap::Reconstruction::WriteText().
L1RootNormalizeFeatureDescriptors()
Eigen::MatrixXf colmap::L1RootNormalizeFeatureDescriptors (const Eigen::MatrixXf & descriptors)
Definition at line 52 of file utils.cc.
References descriptors.
Referenced by BOOST_AUTO_TEST_CASE(), ExtractCovariantSiftFeaturesCPU(), ExtractSiftFeaturesCPU(), and ExtractSiftFeaturesGPU().
L2NormalizeFeatureDescriptors()
Eigen::MatrixXf colmap::L2NormalizeFeatureDescriptors (const Eigen::MatrixXf & descriptors)
Definition at line 47 of file utils.cc.
References descriptors.
Referenced by BOOST_AUTO_TEST_CASE(), CreateRandomFeatureDescriptors(), ExtractCovariantSiftFeaturesCPU(), ExtractSiftFeaturesCPU(), and ExtractSiftFeaturesGPU().
LittleEndianToNative()
template<typename T > T colmap::LittleEndianToNative (const T x)
Definition at line 75 of file endian.h.
References IsLittleEndian(), ReverseBytes(), and x.
Referenced by ReadBinaryLittleEndian(), and ReadPly().
LoadSiftFeaturesFromTextFile()
void colmap::LoadSiftFeaturesFromTextFile (const std::string & path, FeatureKeypoints * keypoints, FeatureDescriptors * descriptors)
Definition at line 943 of file sift.cc.
References descriptors, cloudViewer::t::geometry::path, x, and y.
MatchGuidedSiftFeaturesCPU()
void colmap::MatchGuidedSiftFeaturesCPU (const SiftMatchingOptions & match_options, const FeatureKeypoints & keypoints1, const FeatureKeypoints & keypoints2, const FeatureDescriptors & descriptors1, const FeatureDescriptors & descriptors2, TwoViewGeometry * two_view_geometry)
Definition at line 1050 of file sift.cc.
References colmap::TwoViewGeometry::CALIBRATED, colmap::SiftMatchingOptions::Check(), colmap::TwoViewGeometry::config, colmap::SiftMatchingOptions::cross_check, colmap::TwoViewGeometry::F, colmap::TwoViewGeometry::H, colmap::TwoViewGeometry::inlier_matches, colmap::SiftMatchingOptions::max_distance, colmap::SiftMatchingOptions::max_error, colmap::SiftMatchingOptions::max_ratio, colmap::TwoViewGeometry::PANORAMIC, colmap::TwoViewGeometry::PLANAR, colmap::TwoViewGeometry::PLANAR_OR_PANORAMIC, and colmap::TwoViewGeometry::UNCALIBRATED.
Referenced by BOOST_AUTO_TEST_CASE().
MatchGuidedSiftFeaturesGPU()
void colmap::MatchGuidedSiftFeaturesGPU (const SiftMatchingOptions & match_options, const FeatureKeypoints * keypoints1, const FeatureKeypoints * keypoints2, const FeatureDescriptors * descriptors1, const FeatureDescriptors * descriptors2, SiftMatchGPU * sift_match_gpu, TwoViewGeometry * two_view_geometry)
Definition at line 1267 of file sift.cc.
References colmap::TwoViewGeometry::CALIBRATED, colmap::SiftMatchingOptions::Check(), colmap::TwoViewGeometry::config, colmap::SiftMatchingOptions::cross_check, QtCompat::endl(), colmap::TwoViewGeometry::F, colmap::TwoViewGeometry::H, colmap::TwoViewGeometry::inlier_matches, colmap::SiftMatchingOptions::max_distance, colmap::SiftMatchingOptions::max_error, colmap::SiftMatchingOptions::max_num_matches, colmap::SiftMatchingOptions::max_ratio, colmap::TwoViewGeometry::PANORAMIC, colmap::TwoViewGeometry::PLANAR, colmap::TwoViewGeometry::PLANAR_OR_PANORAMIC, colmap::TwoViewGeometry::UNCALIBRATED, x, and y.
Referenced by BOOST_AUTO_TEST_CASE().
MatchSiftFeaturesCPU()
void colmap::MatchSiftFeaturesCPU (const SiftMatchingOptions & match_options, const FeatureDescriptors & descriptors1, const FeatureDescriptors & descriptors2, FeatureMatches * matches)
Definition at line 1042 of file sift.cc.
References MatchSiftFeaturesCPUFLANN().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::SiftCPUFeatureMatcher::Run().
MatchSiftFeaturesCPUBruteForce()
void colmap::MatchSiftFeaturesCPUBruteForce (const SiftMatchingOptions & match_options, const FeatureDescriptors & descriptors1, const FeatureDescriptors & descriptors2, FeatureMatches * matches)
Definition at line 998 of file sift.cc.
References colmap::SiftMatchingOptions::Check(), colmap::SiftMatchingOptions::cross_check, colmap::SiftMatchingOptions::max_distance, and colmap::SiftMatchingOptions::max_ratio.
Referenced by BOOST_AUTO_TEST_CASE().
MatchSiftFeaturesCPUFLANN()
void colmap::MatchSiftFeaturesCPUFLANN (const SiftMatchingOptions & match_options, const FeatureDescriptors & descriptors1, const FeatureDescriptors & descriptors2, FeatureMatches * matches)
Definition at line 1013 of file sift.cc.
References colmap::SiftMatchingOptions::Check(), colmap::SiftMatchingOptions::cross_check, colmap::SiftMatchingOptions::max_distance, and colmap::SiftMatchingOptions::max_ratio.
Referenced by BOOST_AUTO_TEST_CASE(), and MatchSiftFeaturesCPU().
MatchSiftFeaturesGPU()
void colmap::MatchSiftFeaturesGPU (const SiftMatchingOptions & match_options, const FeatureDescriptors * descriptors1, const FeatureDescriptors * descriptors2, SiftMatchGPU * sift_match_gpu, FeatureMatches * matches)
Definition at line 1195 of file sift.cc.
References colmap::SiftMatchingOptions::Check(), colmap::SiftMatchingOptions::cross_check, QtCompat::endl(), colmap::SiftMatchingOptions::max_distance, colmap::SiftMatchingOptions::max_num_matches, and colmap::SiftMatchingOptions::max_ratio.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::SiftGPUFeatureMatcher::Run().
MaybeDownloadAndCacheFile()
std::filesystem::path colmap::MaybeDownloadAndCacheFile (const std::string & uri)
Referenced by RunVocabTreeRetriever().
Mean()
template<typename T > double colmap::Mean (const std::vector< T > & elems)
Definition at line 227 of file math.h.
Referenced by BOOST_AUTO_TEST_CASE(), cloudViewer::t::geometry::ComputeMetricsCommon(), cloudViewer::t::geometry::TriangleMesh::PCAPartition(), RunModelAligner(), and Variance().
Median()
template<typename T > double colmap::Median (const std::vector< T > & elems)
Definition at line 189 of file math.h.
Referenced by colmap::retrieval::InvertedFile< kEmbeddingDim >::ComputeHammingEmbedding(), colmap::TwoViewGeometry::EstimateRelativePose(), and RunModelAligner().
NativeToBigEndian()
template<typename T > T colmap::NativeToBigEndian (const T x)
Definition at line 102 of file endian.h.
References IsBigEndian(), ReverseBytes(), and x.
NativeToLittleEndian()
template<typename T > T colmap::NativeToLittleEndian (const T x)
Definition at line 93 of file endian.h.
References IsLittleEndian(), ReverseBytes(), and x.
Referenced by WriteBinaryLittleEndian().
NChooseK()
size_t colmap::NChooseK (const size_t n, const size_t k)
Definition at line 36 of file math.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::IncrementalTriangulator::CompleteImage(), and colmap::CombinationSampler::MaxNumSamples().
NextCombination()
template<class Iterator > bool colmap::NextCombination (Iterator first, Iterator middle, Iterator last)
Definition at line 273 of file math.h.
References ecvColor::middle(), and colmap::internal::NextCombination().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::CombinationSampler::Sample().
NormalizeQuaternion()
Eigen::Vector4d colmap::NormalizeQuaternion (const Eigen::Vector4d & qvec)
Definition at line 82 of file pose.cc.
Referenced by AverageQuaternions(), BOOST_AUTO_TEST_CASE(), ConcatenateQuaternions(), colmap::Reconstruction::ExportRecon3D(), InterpolatePose(), colmap::Image::NormalizeQvec(), ProjectionCenterFromPose(), QuaternionRotatePoint(), QuaternionToRotationMatrix(), RefineAbsolutePose(), RefineRelativePose(), and RunModelComparer().
operator<<()
template<typename T > std::ostream& colmap::operator<< (std::ostream & output, const BitmapColor< T > & color)
Definition at line 239 of file bitmap.h.
References color, and StringPrintf().
ParameterBlockTangentSize()
int colmap::ParameterBlockTangentSize (ceres::Problem * problem, const double * param) inline
Definition at line 166 of file manifold.h.
Percentile()
template<typename T > T colmap::Percentile (const std::vector< T > & elems, const double p)
Definition at line 209 of file math.h.
Referenced by colmap::mvs::Model::ComputeTriangulationAngles(), and colmap::mvs::DepthMap::ToBitmap().
PoseFromEssentialMatrix()
void colmap::PoseFromEssentialMatrix (const Eigen::Matrix3d & E, const std::vector< Eigen::Vector2d > & points1, const std::vector< Eigen::Vector2d > & points2, Eigen::Matrix3d * R, Eigen::Vector3d * t, std::vector< Eigen::Vector3d > * points3D)
Definition at line 63 of file essential_matrix.cc.
References CheckCheirality(), and DecomposeEssentialMatrix().
Referenced by BOOST_AUTO_TEST_CASE(), colmap::TwoViewGeometry::EstimateRelativePose(), EstimateRelativePose(), and RefineEssentialMatrix().
PoseFromHomographyMatrix()
void colmap::PoseFromHomographyMatrix (const Eigen::Matrix3d & H, const Eigen::Matrix3d & K1, const Eigen::Matrix3d & K2, const std::vector< Eigen::Vector2d > & points1, const std::vector< Eigen::Vector2d > & points2, Eigen::Matrix3d * R, Eigen::Vector3d * t, Eigen::Vector3d * n, std::vector< Eigen::Vector3d > * points3D)
Definition at line 186 of file homography_matrix.cc.
References CheckCheirality(), and DecomposeHomographyMatrix().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::TwoViewGeometry::EstimateRelativePose().
PrintHeading1()
void colmap::PrintHeading1 (const std::string & heading)
Definition at line 225 of file misc.cc.
References QtCompat::endl().
Referenced by EstimateManhattanWorldFrame(), RunDatabaseCleaner(), RunImageRegistrator(), RunImageTexturer(), RunImageUndistorter(), RunModelComparer(), RunModelOrientationAligner(), RunModelSplitter(), RunPointTriangulator(), and RunRigBundleAdjuster().
PrintHeading2()
void colmap::PrintHeading2 (const std::string & heading)
Definition at line 231 of file misc.cc.
References QtCompat::endl().
Referenced by colmap::TexturingOptions::Print(), colmap::mvs::StereoFusionOptions::Print(), colmap::mvs::PatchMatchOptions::Print(), colmap::mvs::PatchMatch::Problem::Print(), RefineAbsolutePose(), colmap::mvs::PatchMatch::Run(), RunDatabaseCleaner(), RunModelAligner(), RunModelCropper(), RunModelMerger(), RunModelSplitter(), RunRigBundleAdjuster(), colmap::BundleAdjuster::Solve(), and colmap::RigBundleAdjuster::Solve().
PrintSolverSummary()
void colmap::PrintSolverSummary (const ceres::Solver::Summary & summary)
Definition at line 1243 of file bundle_adjustment.cc.
References QtCompat::endl().
Referenced by RefineAbsolutePose(), colmap::BundleAdjuster::Solve(), and colmap::RigBundleAdjuster::Solve().
ProjectionCenterFromMatrix()
Eigen::Vector3d colmap::ProjectionCenterFromMatrix (const Eigen::Matrix3x4d & proj_matrix)
Definition at line 159 of file pose.cc.
Referenced by BOOST_AUTO_TEST_CASE(), and InvertProjectionMatrix().
ProjectionCenterFromPose()
Eigen::Vector3d colmap::ProjectionCenterFromPose (const Eigen::Vector4d & qvec, const Eigen::Vector3d & tvec)
Definition at line 164 of file pose.cc.
References NormalizeQuaternion().
Referenced by BOOST_AUTO_TEST_CASE(), CalculateBaseline(), colmap::CameraRig::ComputeScale(), and colmap::Image::ProjectionCenter().
ProjectPointToImage()
Eigen::Vector2d colmap::ProjectPointToImage (const Eigen::Vector3d & point3D, const Eigen::Matrix3x4d & proj_matrix, const Camera & camera)
Definition at line 104 of file projection.cc.
References colmap::Camera::WorldToImage().
Referenced by GenerateReconstruction(), cloudViewer::PointViewerWidget::Show(), and colmap::PointViewerWidget::Show().
QMatrixToEigen()
Eigen::Matrix4f colmap::QMatrixToEigen (const QMatrix4x4 & matrix)
Definition at line 39 of file qt_utils.cc.
Referenced by colmap::ModelViewerWidget::ChangeFocusDistance(), colmap::ModelViewerWidget::paintGL(), colmap::ModelViewerWidget::RotateView(), and colmap::ModelViewerWidget::TranslateView().
QuaternionRotatePoint()
Eigen::Vector3d colmap::QuaternionRotatePoint (const Eigen::Vector4d & qvec, const Eigen::Vector3d & point)
Definition at line 110 of file pose.cc.
References NormalizeQuaternion().
Referenced by BOOST_AUTO_TEST_CASE(), CalculateNormalizedAngularError(), CalculateSquaredReprojectionError(), colmap::CameraRig::ComputeAbsolutePose(), ComputeRelativePose(), ConcatenatePoses(), EstimateManhattanWorldFrame(), and InvertPose().
QuaternionToRotationMatrix()
Eigen::Matrix3d colmap::QuaternionToRotationMatrix (const Eigen::Vector4d & qvec)
Definition at line 75 of file pose.cc.
References NormalizeQuaternion().
Referenced by BOOST_AUTO_TEST_CASE(), ComposeProjectionMatrix(), colmap::Reconstruction::ExportRecon3D(), colmap::mvs::Model::ReadFromCOLMAP(), RefineEssentialMatrix(), and colmap::Image::RotationMatrix().
RadToDeg() [1/2]
double colmap::RadToDeg (const double rad) inline
Definition at line 184 of file math.h.
RadToDeg() [2/2]
float colmap::RadToDeg (const float rad) inline
Definition at line 180 of file math.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::ModelViewerWidget::RotateView(), RunModelComparer(), and colmap::GPSTransform::XYZToEll().
RandomGaussian()
template<typename T > T colmap::RandomGaussian (const T mean, const T stddev)
Definition at line 86 of file random.h.
References PRNG, SetPRNGSeed(), and stddev().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::retrieval::InvertedIndex< kDescType, kDescDim, kEmbeddingDim >::GenerateHammingEmbeddingProjection().
RandomInteger()
template<typename T > T colmap::RandomInteger (const T min, const T max)
Definition at line 64 of file random.h.
References PRNG, and SetPRNGSeed().
Referenced by BOOST_AUTO_TEST_CASE().
RandomReal()
template<typename T > T colmap::RandomReal (const T min, const T max)
Definition at line 75 of file random.h.
References PRNG, and SetPRNGSeed().
Referenced by BOOST_AUTO_TEST_CASE(), CreateRandomFeatureDescriptors(), GeneratePointCloud(), and GenerateReconstruction().
ReadBinaryBlob()
template<typename T > void colmap::ReadBinaryBlob (const std::string & path, std::vector< T > * data)
Definition at line 159 of file misc.h.
References data, and cloudViewer::t::geometry::path.
ReadBinaryLittleEndian() [1/2]
template<typename T > T colmap::ReadBinaryLittleEndian (std::istream * stream)
Definition at line 111 of file endian.h.
References LittleEndianToNative().
ReadBinaryLittleEndian() [2/2]
template<typename T > void colmap::ReadBinaryLittleEndian (std::istream * stream, std::vector< T > * data)
Definition at line 118 of file endian.h.
References data.
ReadPly()
std::vector< PlyPoint > colmap::ReadPly (const std::string & path)
Definition at line 43 of file ply.cc.
References colmap::PlyPoint::b, BigEndianToNative(), QtCompat::endl(), colmap::PlyPoint::g, LittleEndianToNative(), colmap::PlyPoint::nx, colmap::PlyPoint::ny, colmap::PlyPoint::nz, cloudViewer::t::geometry::path, points, colmap::PlyPoint::r, StringSplit(), StringTrim(), colmap::PlyPoint::x, colmap::PlyPoint::y, and colmap::PlyPoint::z.
Referenced by colmap::Reconstruction::ImportPLY().
ReadTextFileLines()
std::vector< std::string > colmap::ReadTextFileLines (const std::string & path)
Definition at line 308 of file misc.cc.
References cloudViewer::t::geometry::path, and StringTrim().
Referenced by colmap::mvs::ImportPMVSWorkspace(), RunFeatureExtractor(), RunFeatureImporter(), RunImageDeleter(), RunImageUndistorter(), and RunMapper().
RectifyAndUndistortStereoImages()
void colmap::RectifyAndUndistortStereoImages (const UndistortCameraOptions & options, const Bitmap & distorted_image1, const Bitmap & distorted_image2, const Camera & distorted_camera1, const Camera & distorted_camera2, const Eigen::Vector4d & qvec, const Eigen::Vector3d & tvec, Bitmap * undistorted_image1, Bitmap * undistorted_image2, Camera * undistorted_camera, Eigen::Matrix4d * Q)
Definition at line 1039 of file undistortion.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::CloneMetadata(), colmap::Camera::Height(), colmap::Bitmap::Height(), colmap::Bitmap::IsRGB(), RectifyStereoCameras(), UndistortCamera(), WarpImageWithHomographyBetweenCameras(), colmap::Camera::Width(), and colmap::Bitmap::Width().
RectifyStereoCameras()
void colmap::RectifyStereoCameras (const Camera & camera1, const Camera & camera2, const Eigen::Vector4d & qvec, const Eigen::Vector3d & tvec, Eigen::Matrix3d * H1, Eigen::Matrix3d * H2, Eigen::Matrix4d * Q)
Definition at line 977 of file undistortion.cc.
References colmap::Camera::CalibrationMatrix(), colmap::Camera::MeanFocalLength(), colmap::SimplePinholeCameraModel::model_id, colmap::PinholeCameraModel::model_id, colmap::Camera::ModelId(), colmap::Camera::PrincipalPointX(), and colmap::Camera::PrincipalPointY().
Referenced by BOOST_AUTO_TEST_CASE(), and RectifyAndUndistortStereoImages().
RefineAbsolutePose()
bool colmap::RefineAbsolutePose (const AbsolutePoseRefinementOptions & options, const std::vector< char > & inlier_mask, const std::vector< Eigen::Vector2d > & points2D, const std::vector< Eigen::Vector3d > & points3D, Eigen::Vector4d * qvec, Eigen::Vector3d * tvec, Camera * camera)
Definition at line 203 of file pose.cc.
References CAMERA_MODEL_SWITCH_CASES, colmap::AbsolutePoseRefinementOptions::Check(), data, QtCompat::endl(), colmap::Camera::ExtraParamsIdxs(), colmap::Camera::FocalLengthIdxs(), colmap::AbsolutePoseRefinementOptions::gradient_tolerance, colmap::AbsolutePoseRefinementOptions::loss_function_scale, colmap::AbsolutePoseRefinementOptions::max_num_iterations, colmap::Camera::ModelId(), NormalizeQuaternion(), colmap::Camera::NumParams(), colmap::Camera::ParamsData(), colmap::Camera::PrincipalPointIdxs(), colmap::AbsolutePoseRefinementOptions::print_summary, PrintHeading2(), PrintSolverSummary(), colmap::AbsolutePoseRefinementOptions::refine_extra_params, colmap::AbsolutePoseRefinementOptions::refine_focal_length, SetQuaternionManifold(), SetSubsetManifold(), and cloudViewer::core::Solve().
Referenced by colmap::IncrementalMapper::RegisterNextImage().
RefineEssentialMatrix()
bool colmap::RefineEssentialMatrix (const ceres::Solver::Options & options, const std::vector< Eigen::Vector2d > & points1, const std::vector< Eigen::Vector2d > & points2, const std::vector< char > & inlier_mask, Eigen::Matrix3d * E)
Definition at line 159 of file essential_matrix.cc.
References EssentialMatrixFromPose(), PoseFromEssentialMatrix(), QuaternionToRotationMatrix(), RefineRelativePose(), and RotationMatrixToQuaternion().
Referenced by BOOST_AUTO_TEST_CASE().
RefineRelativePose()
bool colmap::RefineRelativePose (const ceres::Solver::Options & options, const std::vector< Eigen::Vector2d > & points1, const std::vector< Eigen::Vector2d > & points2, Eigen::Vector4d * qvec, Eigen::Vector3d * tvec)
Definition at line 330 of file pose.cc.
References colmap::RelativePoseCostFunction::Create(), NormalizeQuaternion(), SetQuaternionManifold(), and cloudViewer::core::Solve().
Referenced by RefineEssentialMatrix().
RemoveCommandLineArgument()
void colmap::RemoveCommandLineArgument (const std::string & arg, int * argc, char ** argv)
Definition at line 327 of file misc.cc.
Referenced by BOOST_AUTO_TEST_CASE().
ResampleImageBilinear()
void colmap::ResampleImageBilinear (const float * data, const int rows, const int cols, const int new_rows, const int new_cols, float * resampled)
Definition at line 174 of file warp.cc.
References data, and cloudViewer::utility::floor().
Referenced by BOOST_AUTO_TEST_CASE(), and DownsampleImage().
ReverseBytes()
template<typename T > T colmap::ReverseBytes (const T & data)
Definition at line 51 of file endian.h.
References data.
Referenced by BigEndianToNative(), LittleEndianToNative(), NativeToBigEndian(), and NativeToLittleEndian().
RotationFromUnitVectors()
Eigen::Matrix3d colmap::RotationFromUnitVectors (const Eigen::Vector3d & vector1, const Eigen::Vector3d & vector2)
Definition at line 145 of file pose.cc.
References CrossProductMatrix().
Referenced by BOOST_AUTO_TEST_CASE(), and RunModelOrientationAligner().
RotationMatrixToEulerAngles()
void colmap::RotationMatrixToEulerAngles (const Eigen::Matrix3d & R, double * rx, double * ry, double * rz)
Definition at line 48 of file pose.cc.
References IsNaN().
Referenced by BOOST_AUTO_TEST_CASE().
RotationMatrixToQuaternion()
Eigen::Vector4d colmap::RotationMatrixToQuaternion (const Eigen::Matrix3d & rot_mat)
Definition at line 70 of file pose.cc.
Referenced by AlignToENUPlane(), AlignToPrincipalPlane(), BOOST_AUTO_TEST_CASE(), EstimateAbsolutePose(), colmap::TwoViewGeometry::EstimateRelativePose(), EstimateRelativePose(), RefineEssentialMatrix(), colmap::SimilarityTransform3::Rotation(), RunModelOrientationAligner(), and colmap::SimilarityTransform3::TransformPose().
RunAutomaticReconstructor()
int colmap::RunAutomaticReconstructor (int argc, char ** argv)
Definition at line 48 of file sfm.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), colmap::AutomaticReconstructionController::Options::camera_model, colmap::AutomaticReconstructionController::Options::data_type, colmap::AutomaticReconstructionController::DELAUNAY, colmap::AutomaticReconstructionController::Options::dense, colmap::AutomaticReconstructionController::EXTREME, colmap::AutomaticReconstructionController::Options::gpu_index, colmap::AutomaticReconstructionController::HIGH, colmap::AutomaticReconstructionController::Options::image_path, colmap::AutomaticReconstructionController::INDIVIDUAL, colmap::AutomaticReconstructionController::INTERNET, kUseOpenGL, colmap::AutomaticReconstructionController::LOW, colmap::AutomaticReconstructionController::Options::mask_path, colmap::AutomaticReconstructionController::MEDIUM, colmap::AutomaticReconstructionController::Options::mesher, colmap::AutomaticReconstructionController::Options::num_threads, colmap::OptionManager::Parse(), colmap::AutomaticReconstructionController::POISSON, colmap::AutomaticReconstructionController::Options::quality, RunThreadWithOpenGLContext(), colmap::AutomaticReconstructionController::Options::single_camera, colmap::AutomaticReconstructionController::Options::sparse, colmap::Thread::Start(), StringToLower(), colmap::AutomaticReconstructionController::Options::use_gpu, colmap::AutomaticReconstructionController::VIDEO, colmap::AutomaticReconstructionController::Options::vocab_tree_path, colmap::Thread::Wait(), and colmap::AutomaticReconstructionController::Options::workspace_path.
Referenced by cloudViewer::AutomaticReconstruct(), and main().
RunBundleAdjuster()
int colmap::RunBundleAdjuster (int argc, char ** argv)
Definition at line 135 of file sfm.cc.
References colmap::OptionManager::AddBundleAdjustmentOptions(), colmap::OptionManager::AddRequiredOption(), QtCompat::endl(), ExistsDir(), colmap::OptionManager::Parse(), colmap::Reconstruction::Read(), colmap::Thread::Start(), colmap::Thread::Wait(), and colmap::Reconstruction::Write().
Referenced by cloudViewer::BundleAdjustment(), and main().
RunColorExtractor()
int colmap::RunColorExtractor (int argc, char ** argv)
Definition at line 167 of file sfm.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddImageOptions(), colmap::OptionManager::AddRequiredOption(), colmap::Reconstruction::ExtractColorsForAllImages(), colmap::OptionManager::image_path, colmap::OptionManager::Parse(), colmap::Reconstruction::Read(), and colmap::Reconstruction::Write().
Referenced by cloudViewer::ExtractColor(), and main().
RunDatabaseCleaner()
int colmap::RunDatabaseCleaner (int argc, char ** argv)
Definition at line 40 of file database.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddRequiredOption(), colmap::Database::ClearAllTables(), colmap::Database::ClearDescriptors(), colmap::Database::ClearImages(), colmap::Database::ClearKeypoints(), colmap::Database::ClearMatches(), colmap::Database::ClearTwoViewGeometries(), colmap::OptionManager::database_path, QtCompat::endl(), colmap::OptionManager::Parse(), PrintHeading1(), PrintHeading2(), StringToLower(), and type.
Referenced by cloudViewer::CleanDatabase(), and main().
RunDatabaseCreator()
int colmap::RunDatabaseCreator (int argc, char ** argv)
Definition at line 81 of file database.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::database_path, and colmap::OptionManager::Parse().
Referenced by cloudViewer::CreateDatabase(), and main().
RunDatabaseMerger()
int colmap::RunDatabaseMerger (int argc, char ** argv)
Definition at line 91 of file database.cc.
References colmap::OptionManager::AddRequiredOption(), QtCompat::endl(), ExistsFile(), colmap::Database::Merge(), and colmap::OptionManager::Parse().
Referenced by main(), and cloudViewer::MergeDatabase().
RunDelaunayMesher()
int colmap::RunDelaunayMesher (int argc, char ** argv)
Definition at line 43 of file mvs.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddDelaunayMeshingOptions(), colmap::OptionManager::AddRequiredOption(), colmap::OptionManager::delaunay_meshing, QtCompat::endl(), colmap::OptionManager::Parse(), and StringToLower().
Referenced by main(), and cloudViewer::MeshDelaunay().
RunExhaustiveMatcher()
int colmap::RunExhaustiveMatcher (int argc, char ** argv)
Definition at line 286 of file feature.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddExhaustiveMatchingOptions(), colmap::OptionManager::database_path, colmap::OptionManager::exhaustive_matching, kUseOpenGL, colmap::OptionManager::Parse(), RunThreadWithOpenGLContext(), colmap::OptionManager::sift_matching, colmap::Thread::Start(), and colmap::Thread::Wait().
Referenced by cloudViewer::ExhaustiveMatch(), and main().
RunFeatureExtractor()
int colmap::RunFeatureExtractor (int argc, char ** argv)
Definition at line 137 of file feature.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddExtractionOptions(), colmap::OptionManager::AddImageOptions(), colmap::ImageReaderOptions::camera_model, colmap::ImageReaderOptions::camera_params, colmap::ImageReaderOptions::database_path, colmap::OptionManager::database_path, QtCompat::endl(), ExistsCameraModelWithName(), colmap::ImageReaderOptions::image_list, colmap::ImageReaderOptions::image_path, colmap::OptionManager::image_path, colmap::OptionManager::image_reader, kUseOpenGL, colmap::OptionManager::Parse(), ReadTextFileLines(), RunThreadWithOpenGLContext(), colmap::OptionManager::sift_extraction, colmap::Thread::Start(), and colmap::Thread::Wait().
Referenced by cloudViewer::ExtractFeature(), and main().
RunFeatureImporter()
int colmap::RunFeatureImporter (int argc, char ** argv)
Definition at line 196 of file feature.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddExtractionOptions(), colmap::OptionManager::AddImageOptions(), colmap::OptionManager::AddRequiredOption(), colmap::ImageReaderOptions::camera_model, colmap::ImageReaderOptions::camera_params, colmap::ImageReaderOptions::database_path, colmap::OptionManager::database_path, colmap::ImageReaderOptions::image_list, colmap::ImageReaderOptions::image_path, colmap::OptionManager::image_path, colmap::OptionManager::image_reader, colmap::OptionManager::Parse(), ReadTextFileLines(), colmap::Thread::Start(), and colmap::Thread::Wait().
Referenced by cloudViewer::ImportFeature(), and main().
RunGraphicalUserInterface()
int colmap::RunGraphicalUserInterface (int argc, char ** argv)
Definition at line 39 of file gui.cc.
References colmap::OptionManager::AddAllOptions(), colmap::OptionManager::AddDefaultOption(), QtCompat::endl(), colmap::MainWindow::ImportReconstruction(), and colmap::OptionManager::Parse().
Referenced by cloudViewer::GraphicalUserInterface(), and main().
RunHierarchicalMapper()
int colmap::RunHierarchicalMapper (int argc, char ** argv)
Definition at line 262 of file sfm.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddMapperOptions(), colmap::OptionManager::AddRequiredOption(), colmap::HierarchicalMapperController::Options::database_path, QtCompat::endl(), ExistsDir(), colmap::SceneClustering::Options::image_overlap, colmap::HierarchicalMapperController::Options::image_path, colmap::SceneClustering::Options::leaf_max_num_images, colmap::OptionManager::mapper, colmap::HierarchicalMapperController::Options::num_workers, colmap::OptionManager::Parse(), colmap::ReconstructionManager::Size(), colmap::Thread::Start(), colmap::Thread::Wait(), and colmap::ReconstructionManager::Write().
Referenced by cloudViewer::HierarchicalMapper(), and main().
RunImageDeleter()
int colmap::RunImageDeleter (int argc, char ** argv)
Definition at line 78 of file image.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), colmap::Reconstruction::DeRegisterImage(), QtCompat::endl(), colmap::Reconstruction::ExistsImage(), colmap::Reconstruction::FindImageWithName(), image, colmap::Reconstruction::Image(), colmap::OptionManager::Parse(), colmap::Reconstruction::Read(), ReadTextFileLines(), StringPrintf(), and colmap::Reconstruction::Write().
Referenced by cloudViewer::DeleteImage(), and main().
RunImageFilterer()
int colmap::RunImageFilterer (int argc, char ** argv)
Definition at line 156 of file image.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), colmap::Reconstruction::DeRegisterImage(), QtCompat::endl(), colmap::Reconstruction::FilterImages(), image, colmap::Reconstruction::Images(), colmap::Reconstruction::NumRegImages(), colmap::OptionManager::Parse(), colmap::Reconstruction::Read(), StringPrintf(), and colmap::Reconstruction::Write().
Referenced by cloudViewer::FilterImage(), and main().
RunImageRectifier()
int colmap::RunImageRectifier (int argc, char ** argv)
Definition at line 205 of file image.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddImageOptions(), colmap::OptionManager::AddRequiredOption(), colmap::UndistortCameraOptions::blank_pixels, colmap::OptionManager::image_path, colmap::UndistortCameraOptions::max_image_size, colmap::UndistortCameraOptions::max_scale, colmap::UndistortCameraOptions::min_scale, colmap::OptionManager::Parse(), colmap::Reconstruction::Read(), colmap::Thread::Start(), and colmap::Thread::Wait().
Referenced by main(), and cloudViewer::RectifyImage().
RunImageRegistrator()
int colmap::RunImageRegistrator (int argc, char ** argv)
Definition at line 240 of file image.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddMapperOptions(), colmap::OptionManager::AddRequiredOption(), colmap::IncrementalMapper::BeginReconstruction(), colmap::OptionManager::database_path, QtCompat::endl(), colmap::IncrementalMapper::EndReconstruction(), ExistsDir(), image, colmap::Reconstruction::Images(), colmap::DatabaseCache::Load(), colmap::OptionManager::mapper, colmap::Reconstruction::NumRegImages(), colmap::OptionManager::Parse(), PrintHeading1(), colmap::Timer::PrintMinutes(), colmap::Reconstruction::Read(), colmap::IncrementalMapper::RegisterNextImage(), colmap::Timer::Start(), patch::to_string(), and colmap::Reconstruction::Write().
Referenced by main(), and cloudViewer::RegisterImage().
RunImageTexturer()
int colmap::RunImageTexturer (int argc, char ** argv)
Definition at line 497 of file image.cc.
References colmap::OptionManager::AddRequiredOption(), colmap::OptionManager::AddTexturingOptions(), CreateDirIfNotExists(), QtCompat::endl(), ExistsDir(), ExistsFile(), colmap::OptionManager::image_path, JoinPaths(), colmap::Reconstruction::NumImages(), colmap::Reconstruction::NumPoints3D(), colmap::OptionManager::Parse(), PrintHeading1(), colmap::Reconstruction::Read(), colmap::Thread::Start(), StringPrintf(), colmap::OptionManager::texturing, and colmap::Thread::Wait().
Referenced by main().
RunImageUndistorter()
int colmap::RunImageUndistorter (int argc, char ** argv)
Definition at line 311 of file image.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddImageOptions(), colmap::OptionManager::AddRequiredOption(), colmap::UndistortCameraOptions::blank_pixels, COPY, CreateDirIfNotExists(), QtCompat::endl(), colmap::Reconstruction::FindImageWithName(), HARD_LINK, image, colmap::OptionManager::image_path, colmap::UndistortCameraOptions::max_image_size, colmap::UndistortCameraOptions::max_scale, colmap::UndistortCameraOptions::min_scale, colmap::Reconstruction::NumImages(), colmap::Reconstruction::NumPoints3D(), colmap::OptionManager::Parse(), PrintHeading1(), colmap::Reconstruction::Read(), ReadTextFileLines(), colmap::UndistortCameraOptions::roi_max_x, colmap::UndistortCameraOptions::roi_max_y, colmap::UndistortCameraOptions::roi_min_x, colmap::UndistortCameraOptions::roi_min_y, SOFT_LINK, StringPrintf(), and StringToLower().
Referenced by main(), and cloudViewer::UndistortImage().
RunImageUndistorterStandalone()
int colmap::RunImageUndistorterStandalone (int argc, char ** argv)
Definition at line 408 of file image.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddImageOptions(), colmap::OptionManager::AddRequiredOption(), colmap::UndistortCameraOptions::blank_pixels, CreateDirIfNotExists(), QtCompat::endl(), ExistsCameraModelWithName(), colmap::OptionManager::image_path, colmap::UndistortCameraOptions::max_image_size, colmap::UndistortCameraOptions::max_scale, colmap::UndistortCameraOptions::min_scale, colmap::Camera::Params(), colmap::OptionManager::Parse(), colmap::UndistortCameraOptions::roi_max_x, colmap::UndistortCameraOptions::roi_max_y, colmap::UndistortCameraOptions::roi_min_x, colmap::UndistortCameraOptions::roi_min_y, colmap::Camera::SetHeight(), colmap::Camera::SetModelIdFromName(), colmap::Camera::SetWidth(), StringTrim(), and colmap::Camera::VerifyParams().
Referenced by main(), and cloudViewer::UndistortImageStandalone().
RunMapper()
int colmap::RunMapper (int argc, char ** argv)
Definition at line 185 of file sfm.cc.
References colmap::Thread::AddCallback(), colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddImageOptions(), colmap::OptionManager::AddMapperOptions(), colmap::OptionManager::AddRequiredOption(), colmap::OptionManager::database_path, QtCompat::endl(), ExistsDir(), colmap::ReconstructionManager::Get(), colmap::OptionManager::image_path, colmap::IncrementalMapperController::LAST_IMAGE_REG_CALLBACK, colmap::OptionManager::mapper, colmap::OptionManager::Parse(), colmap::ReconstructionManager::Read(), ReadTextFileLines(), colmap::ReconstructionManager::Size(), colmap::Thread::Start(), colmap::Thread::Wait(), and colmap::Reconstruction::Write().
Referenced by main(), and cloudViewer::NormalMapper().
RunMatchesImporter()
int colmap::RunMatchesImporter (int argc, char ** argv)
Definition at line 238 of file feature.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddMatchingOptions(), colmap::OptionManager::AddRequiredOption(), colmap::OptionManager::database_path, kUseOpenGL, colmap::ImagePairsMatchingOptions::match_list_path, colmap::FeaturePairsMatchingOptions::match_list_path, colmap::OptionManager::Parse(), RunThreadWithOpenGLContext(), colmap::OptionManager::sift_matching, and colmap::FeaturePairsMatchingOptions::verify_matches.
Referenced by cloudViewer::ImportMatches(), and main().
RunModelAligner()
int colmap::RunModelAligner (int argc, char ** argv)
Definition at line 196 of file model.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), colmap::Reconstruction::Align(), colmap::Reconstruction::AlignRobust(), AlignToENUPlane(), AlignToPrincipalPlane(), QtCompat::endl(), colmap::Reconstruction::FindImageWithName(), image, colmap::RANSACOptions::max_error, Mean(), Median(), colmap::OptionManager::Parse(), PrintHeading2(), colmap::Reconstruction::Read(), StringPrintf(), StringStartsWith(), StringToLower(), colmap::SimilarityTransform3::Write(), and colmap::Reconstruction::Write().
Referenced by cloudViewer::AlignModel(), and main().
RunModelAnalyzer()
int colmap::RunModelAnalyzer (int argc, char ** argv)
Definition at line 332 of file model.cc.
References colmap::OptionManager::AddRequiredOption(), colmap::Reconstruction::ComputeMeanObservationsPerRegImage(), colmap::Reconstruction::ComputeMeanReprojectionError(), colmap::Reconstruction::ComputeMeanTrackLength(), colmap::Reconstruction::ComputeNumObservations(), QtCompat::endl(), colmap::Reconstruction::NumCameras(), colmap::Reconstruction::NumImages(), colmap::Reconstruction::NumPoints3D(), colmap::Reconstruction::NumRegImages(), colmap::OptionManager::Parse(), cloudViewer::t::geometry::path, colmap::Reconstruction::Read(), and StringPrintf().
Referenced by cloudViewer::AnalyzeModel(), and main().
RunModelComparer()
int colmap::RunModelComparer (int argc, char ** argv)
Definition at line 367 of file model.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), ComputeAlignmentBetweenReconstructions(), QtCompat::endl(), ExistsDir(), colmap::Reconstruction::FindCommonRegImageIds(), colmap::Reconstruction::Image(), JoinPaths(), colmap::SimilarityTransform3::Matrix(), NormalizeQuaternion(), colmap::Reconstruction::NumPoints3D(), colmap::Reconstruction::NumRegImages(), colmap::OptionManager::Parse(), PrintHeading1(), colmap::Image::ProjectionCenter(), colmap::Image::Qvec(), RadToDeg(), colmap::Reconstruction::Read(), StringPrintf(), colmap::SimilarityTransform3::TransformPose(), and colmap::Image::Tvec().
Referenced by cloudViewer::CompareModel(), and main().
RunModelConverter()
int colmap::RunModelConverter (int argc, char ** argv)
Definition at line 463 of file model.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), QtCompat::endl(), colmap::Reconstruction::ExportBundler(), colmap::Reconstruction::ExportCam(), colmap::Reconstruction::ExportNVM(), colmap::Reconstruction::ExportPLY(), colmap::Reconstruction::ExportRecon3D(), colmap::Reconstruction::ExportVRML(), colmap::OptionManager::Parse(), colmap::Reconstruction::Read(), StringToLower(), colmap::Reconstruction::WriteBinary(), and colmap::Reconstruction::WriteText().
Referenced by cloudViewer::ConvertModel(), and main().
RunModelCropper()
int colmap::RunModelCropper (int argc, char ** argv)
Definition at line 509 of file model.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), colmap::Reconstruction::ComputeBoundingBox(), colmap::Reconstruction::Crop(), QtCompat::endl(), ExistsDir(), colmap::SimilarityTransform3::FromFile(), colmap::SimilarityTransform3::Inverse(), colmap::OptionManager::Parse(), PrintHeading2(), colmap::Timer::PrintMinutes(), colmap::Reconstruction::Read(), colmap::Timer::Start(), and colmap::Reconstruction::Write().
Referenced by cloudViewer::CropModel(), and main().
RunModelMerger()
int colmap::RunModelMerger (int argc, char ** argv)
Definition at line 582 of file model.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), QtCompat::endl(), colmap::Reconstruction::Merge(), colmap::Reconstruction::NumPoints3D(), colmap::Reconstruction::NumRegImages(), colmap::OptionManager::Parse(), PrintHeading2(), colmap::Reconstruction::Read(), StringPrintf(), and colmap::Reconstruction::Write().
Referenced by main(), and cloudViewer::MergeModel().
RunModelOrientationAligner()
int colmap::RunModelOrientationAligner (int argc, char ** argv)
Definition at line 628 of file model.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddImageOptions(), colmap::OptionManager::AddRequiredOption(), QtCompat::endl(), EstimateGravityVectorFromImageOrientation(), EstimateManhattanWorldFrame(), frame, colmap::OptionManager::image_path, colmap::ManhattanWorldFrameEstimationOptions::max_image_size, colmap::OptionManager::Parse(), PrintHeading1(), colmap::Reconstruction::Read(), RotationFromUnitVectors(), RotationMatrixToQuaternion(), StringToLower(), colmap::Reconstruction::Transform(), and colmap::Reconstruction::Write().
Referenced by cloudViewer::AlignModelOrientation(), and main().
RunModelSplitter()
int colmap::RunModelSplitter (int argc, char ** argv)
Definition at line 694 of file model.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), colmap::ThreadPool::AddTask(), colmap::Reconstruction::ComputeBoundingBox(), CreateDirIfNotExists(), colmap::Reconstruction::Crop(), QtCompat::endl(), ExistsDir(), colmap::SimilarityTransform3::FromFile(), GetEffectiveNumThreads(), colmap::SimilarityTransform3::Inverse(), JoinPaths(), name, colmap::Reconstruction::NumPoints3D(), colmap::Reconstruction::NumRegImages(), colmap::OptionManager::Parse(), PrintHeading1(), PrintHeading2(), colmap::Timer::PrintMinutes(), colmap::Reconstruction::Read(), colmap::SimilarityTransform3::Scale(), colmap::Timer::Start(), StringPrintf(), StringToLower(), patch::to_string(), colmap::ThreadPool::Wait(), and colmap::Reconstruction::Write().
Referenced by main(), and cloudViewer::SplitModel().
RunModelTransformer()
int colmap::RunModelTransformer (int argc, char ** argv)
Definition at line 879 of file model.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), QtCompat::endl(), ExistsDir(), colmap::Reconstruction::ExportPLY(), colmap::SimilarityTransform3::FromFile(), HasFileExtension(), colmap::Reconstruction::ImportPLY(), colmap::SimilarityTransform3::Inverse(), colmap::Reconstruction::NumPoints3D(), colmap::OptionManager::Parse(), colmap::Reconstruction::Read(), colmap::Reconstruction::Transform(), and colmap::Reconstruction::Write().
Referenced by main(), and cloudViewer::TransformModel().
RunPatchMatchStereo()
int colmap::RunPatchMatchStereo (int argc, char ** argv)
Definition at line 81 of file mvs.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddPatchMatchStereoOptions(), colmap::OptionManager::AddRequiredOption(), QtCompat::endl(), colmap::OptionManager::Parse(), colmap::OptionManager::patch_match_stereo, colmap::Thread::Start(), StringToLower(), and colmap::Thread::Wait().
Referenced by main(), and cloudViewer::StereoPatchMatch().
RunPointFiltering()
int colmap::RunPointFiltering (int argc, char ** argv)
Definition at line 302 of file sfm.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), colmap::Reconstruction::DeletePoint3D(), QtCompat::endl(), colmap::Reconstruction::FilterAllPoints3D(), colmap::Track::Length(), colmap::OptionManager::Parse(), colmap::Reconstruction::Point3D(), colmap::Reconstruction::Point3DIds(), colmap::Reconstruction::Read(), colmap::Point3D::Track(), and colmap::Reconstruction::Write().
Referenced by cloudViewer::FilterPoints(), and main().
RunPointTriangulator()
int colmap::RunPointTriangulator (int argc, char ** argv)
Definition at line 339 of file sfm.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddDefaultOption(), colmap::BundleAdjustmentConfig::AddImage(), colmap::OptionManager::AddImageOptions(), colmap::OptionManager::AddMapperOptions(), colmap::OptionManager::AddRequiredOption(), colmap::IncrementalMapper::BeginReconstruction(), CompleteAndMergeTracks(), colmap::Reconstruction::ComputeNumObservations(), colmap::OptionManager::database_path, colmap::Reconstruction::DeleteAllPoints2DAndPoints3D(), QtCompat::endl(), colmap::IncrementalMapper::EndReconstruction(), ExistsDir(), colmap::Reconstruction::ExtractColorsForAllImages(), colmap::Reconstruction::FilterObservationsWithNegativeDepth(), FilterPoints(), image, colmap::Reconstruction::Image(), colmap::OptionManager::image_path, colmap::DatabaseCache::Load(), colmap::OptionManager::mapper, colmap::Reconstruction::NumRegImages(), colmap::OptionManager::Parse(), PrintHeading1(), colmap::Timer::PrintMinutes(), colmap::Reconstruction::Read(), colmap::Reconstruction::RegImageIds(), colmap::BundleAdjuster::Solve(), colmap::Timer::Start(), StringPrintf(), colmap::Reconstruction::TranscribeImageIdsToDatabase(), colmap::IncrementalMapper::TriangulateImage(), and colmap::Reconstruction::Write().
Referenced by main(), and cloudViewer::TriangulatePoints().
RunPoissonMesher()
int colmap::RunPoissonMesher (int argc, char ** argv)
Definition at line 123 of file mvs.cc.
References colmap::OptionManager::AddPoissonMeshingOptions(), colmap::OptionManager::AddRequiredOption(), colmap::OptionManager::Parse(), colmap::OptionManager::poisson_meshing, and colmap::mvs::PoissonMeshing().
Referenced by main(), and cloudViewer::MeshPoisson().
RunProjectGenerator()
int colmap::RunProjectGenerator (int argc, char ** argv)
Definition at line 76 of file gui.cc.
References colmap::OptionManager::AddAllOptions(), colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), colmap::OptionManager::ModifyForExtremeQuality(), colmap::OptionManager::ModifyForHighQuality(), colmap::OptionManager::ModifyForLowQuality(), colmap::OptionManager::ModifyForMediumQuality(), colmap::OptionManager::Parse(), StringToLower(), and colmap::OptionManager::Write().
Referenced by cloudViewer::GenerateProject(), and main().
RunRigBundleAdjuster()
int colmap::RunRigBundleAdjuster (int argc, char ** argv)
Definition at line 655 of file sfm.cc.
References colmap::OptionManager::AddBundleAdjustmentOptions(), colmap::OptionManager::AddDefaultOption(), colmap::BundleAdjustmentConfig::AddImage(), colmap::OptionManager::AddRequiredOption(), colmap::OptionManager::bundle_adjustment, QtCompat::endl(), colmap::OptionManager::Parse(), PrintHeading1(), PrintHeading2(), colmap::Reconstruction::Read(), colmap::RigBundleAdjuster::Options::refine_relative_poses, colmap::Reconstruction::RegImageIds(), colmap::RigBundleAdjuster::Solve(), colmap::BundleAdjustmentOptions::solver_options, StringPrintf(), and colmap::Reconstruction::Write().
Referenced by main(), and cloudViewer::RigBundleAdjust().
RunSequentialMatcher()
int colmap::RunSequentialMatcher (int argc, char ** argv)
Definition at line 315 of file feature.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddSequentialMatchingOptions(), colmap::OptionManager::database_path, kUseOpenGL, colmap::OptionManager::Parse(), RunThreadWithOpenGLContext(), colmap::OptionManager::sequential_matching, colmap::OptionManager::sift_matching, colmap::Thread::Start(), and colmap::Thread::Wait().
Referenced by main(), and cloudViewer::SequentialMatch().
RunSpatialMatcher()
int colmap::RunSpatialMatcher (int argc, char ** argv)
Definition at line 344 of file feature.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddSpatialMatchingOptions(), colmap::OptionManager::database_path, kUseOpenGL, colmap::OptionManager::Parse(), RunThreadWithOpenGLContext(), colmap::OptionManager::sift_matching, colmap::OptionManager::spatial_matching, colmap::Thread::Start(), and colmap::Thread::Wait().
Referenced by main(), and cloudViewer::SpatialMatch().
RunStereoFuser()
int colmap::RunStereoFuser (int argc, char ** argv)
Definition at line 138 of file mvs.cc.
References colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), colmap::OptionManager::AddStereoFusionOptions(), QtCompat::endl(), colmap::mvs::StereoFusion::GetFusedPoints(), colmap::mvs::StereoFusion::GetFusedPointsVisibility(), colmap::Reconstruction::ImportPLY(), JoinPaths(), colmap::OptionManager::Parse(), colmap::Reconstruction::Read(), colmap::Thread::Start(), colmap::OptionManager::stereo_fusion, StringToLower(), colmap::Thread::Wait(), colmap::Reconstruction::WriteBinary(), WriteBinaryPlyPoints(), colmap::mvs::WritePointsVisibility(), and colmap::Reconstruction::WriteText().
Referenced by main(), and cloudViewer::StereoFuse().
RunThreadWithOpenGLContext()
void colmap::RunThreadWithOpenGLContext (Thread * thread) inline
Definition at line 81 of file opengl_utils.h.
Referenced by BOOST_AUTO_TEST_CASE(), RunAutomaticReconstructor(), RunExhaustiveMatcher(), RunFeatureExtractor(), RunMatchesImporter(), RunSequentialMatcher(), RunSpatialMatcher(), RunTransitiveMatcher(), and RunVocabTreeMatcher().
RunTransitiveMatcher()
int colmap::RunTransitiveMatcher (int argc, char ** argv)
Definition at line 373 of file feature.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddTransitiveMatchingOptions(), colmap::OptionManager::database_path, kUseOpenGL, colmap::OptionManager::Parse(), RunThreadWithOpenGLContext(), colmap::OptionManager::sift_matching, colmap::Thread::Start(), colmap::OptionManager::transitive_matching, and colmap::Thread::Wait().
Referenced by main(), and cloudViewer::TransitiveMatch().
RunVocabTreeBuilder()
int colmap::RunVocabTreeBuilder (int argc, char ** argv)
Definition at line 123 of file vocab_tree.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::BuildOptions::branching, colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::Build(), colmap::OptionManager::database_path, descriptors, QtCompat::endl(), colmap::retrieval::kDefaultVocabTreeUri, colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::BuildOptions::num_checks, colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::BuildOptions::num_iterations, colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::BuildOptions::num_visual_words, colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::NumVisualWords(), colmap::OptionManager::Parse(), and colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::Write().
Referenced by cloudViewer::BuildVocabTree(), and main().
RunVocabTreeMatcher()
int colmap::RunVocabTreeMatcher (int argc, char ** argv)
Definition at line 402 of file feature.cc.
References colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddVocabTreeMatchingOptions(), colmap::OptionManager::database_path, kUseOpenGL, colmap::OptionManager::Parse(), RunThreadWithOpenGLContext(), colmap::OptionManager::sift_matching, colmap::Thread::Start(), colmap::OptionManager::vocab_tree_matching, and colmap::Thread::Wait().
Referenced by main(), and cloudViewer::VocabTreeMatch().
RunVocabTreeRetriever()
int colmap::RunVocabTreeRetriever (int argc, char ** argv)
Definition at line 157 of file vocab_tree.cc.
References colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::Add(), colmap::OptionManager::AddDatabaseOptions(), colmap::OptionManager::AddDefaultOption(), colmap::OptionManager::AddRequiredOption(), colmap::OptionManager::database_path, descriptors, colmap::Timer::ElapsedSeconds(), QtCompat::endl(), ExtractTopScaleFeatures(), image, colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::ImageIndexed(), colmap::retrieval::kDefaultVocabTreeUri, colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::QueryOptions::max_num_images, MaybeDownloadAndCacheFile(), colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::QueryOptions::num_checks, colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::QueryOptions::num_images_after_verification, colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::QueryOptions::num_neighbors, colmap::OptionManager::Parse(), colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::Prepare(), colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::Query(), colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::Read(), colmap::Database::ReadDescriptors(), colmap::Database::ReadKeypoints(), colmap::Timer::Start(), StringPrintf(), and colmap::retrieval::VisualIndex< kDescType, kDescDim, kEmbeddingDim >::Write().
Referenced by main(), and cloudViewer::RetrieveVocabTree().
ScaleSigmoid()
template<typename T > T colmap::ScaleSigmoid (T x, const T alpha = 1, const T x0 = 10)
Definition at line 283 of file math.h.
References Sigmoid(), and x.
Referenced by BOOST_AUTO_TEST_CASE().
SetBestCudaDevice()
void colmap::SetBestCudaDevice (const int gpu_index)
Definition at line 67 of file cuda.cc.
References CUDA_SAFE_CALL, and GetNumCudaDevices().
Referenced by colmap::BundleAdjustmentOptions::CreateSolverOptions().
SetPositiveExponentialManifold()
template<int size> void colmap::SetPositiveExponentialManifold (ceres::Problem * problem, double * params) inline
Definition at line 155 of file manifold.h.
References size.
SetPRNGSeed()
void colmap::SetPRNGSeed (unsigned seed)
Definition at line 40 of file random.cc.
References PRNG.
Referenced by BOOST_AUTO_TEST_CASE(), CreateRandomFeatureDescriptors(), GenerateReconstruction(), RandomGaussian(), RandomInteger(), RandomReal(), and TestVocabTreeType().
SetQuaternionManifold()
void colmap::SetQuaternionManifold (ceres::Problem * problem, double * quat_xyzw) inline
Definition at line 19 of file manifold.h.
Referenced by RefineAbsolutePose(), and RefineRelativePose().
SetSphereManifold()
template<int size> void colmap::SetSphereManifold (ceres::Problem * problem, double * params) inline
Definition at line 44 of file manifold.h.
References size.
SetSubsetManifold()
void colmap::SetSubsetManifold (int size, const std::vector< int > & constant_params, ceres::Problem * problem, double * params) inline
Definition at line 29 of file manifold.h.
References size.
Referenced by colmap::BundleAdjuster::ParameterizeCameras(), and RefineAbsolutePose().
ShowImagesSideBySide()
QPixmap colmap::ShowImagesSideBySide (const QPixmap & image1, const QPixmap & image2)
Definition at line 73 of file qt_utils.cc.
References ecvColor::black(), and image.
Referenced by DrawMatches(), cloudViewer::FeatureImageViewerWidget::ReadAndShowWithMatches(), and colmap::FeatureImageViewerWidget::ReadAndShowWithMatches().
Shuffle()
template<typename T > void colmap::Shuffle (const uint32_t num_to_shuffle, std::vector< T > * elems)
Definition at line 96 of file random.h.
References std::swap().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::RandomSampler::Sample().
Sigmoid()
template<typename T > T colmap::Sigmoid (const T x, const T alpha = 1)
Definition at line 278 of file math.h.
References x.
Referenced by BOOST_AUTO_TEST_CASE(), and ScaleSigmoid().
SignOfNumber()
template<typename T > int colmap::SignOfNumber (const T val)
Definition at line 156 of file math.h.
Referenced by BOOST_AUTO_TEST_CASE(), and DecomposeHomographyMatrix().
SmoothImage()
void colmap::SmoothImage (const float * data, const int rows, const int cols, const float sigma_r, const float sigma_c, float * smoothed)
Definition at line 215 of file warp.cc.
References data.
Referenced by BOOST_AUTO_TEST_CASE(), and DownsampleImage().
SolveLeastAbsoluteDeviations()
bool colmap::SolveLeastAbsoluteDeviations (const LeastAbsoluteDeviationsOptions & options, const Eigen::SparseMatrix< double > & A, const Eigen::VectorXd & b, Eigen::VectorXd * x)
Definition at line 47 of file least_absolute_deviations.cc.
References colmap::LeastAbsoluteDeviationsOptions::absolute_tolerance, colmap::LeastAbsoluteDeviationsOptions::alpha, colmap::LeastAbsoluteDeviationsOptions::max_num_iterations, colmap::LeastAbsoluteDeviationsOptions::relative_tolerance, colmap::LeastAbsoluteDeviationsOptions::rho, x, and z.
Referenced by BOOST_AUTO_TEST_CASE().
SplitFileExtension()
void colmap::SplitFileExtension (const std::string & path, std::string * root, std::string * ext)
Definition at line 64 of file misc.cc.
References cloudViewer::t::geometry::path, and StringSplit().
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::Reconstruction::ExportCam().
SQLite3CallHelper()
int colmap::SQLite3CallHelper (const int result_code, const std::string & filename, const int line_number) inline
Definition at line 18 of file sqlite3_utils.h.
References filename.
StdDev()
template<typename T > double colmap::StdDev (const std::vector< T > & elems)
Definition at line 248 of file math.h.
References Variance().
Referenced by BOOST_AUTO_TEST_CASE().
StringContains()
bool colmap::StringContains (const std::string & str, const std::string & sub_str)
Definition at line 201 of file string.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::ImageColormapNameFilter::ComputeColor(), colmap::CameraDatabase::QuerySensorWidth(), and colmap::OptionManager::Write().
StringGetAfter()
std::string colmap::StringGetAfter (const std::string & str, const std::string & key)
Definition at line 154 of file string.cc.
Referenced by BOOST_AUTO_TEST_CASE().
StringLeftTrim()
void colmap::StringLeftTrim (std::string * str)
Definition at line 178 of file string.cc.
Referenced by BOOST_AUTO_TEST_CASE(), and StringTrim().
StringPrintf()
std::string colmap::StringPrintf (const char * format, ...)
Definition at line 131 of file string.cc.
References format, and result.
Referenced by __CheckOptionImpl(), __CheckOptionOpImpl(), colmap::CorrespondenceGraph::AddCorrespondences(), BOOST_AUTO_TEST_CASE(), CreateSiftGPUMatcher(), CudaCheck(), CudaSafeCall(), CudaSyncAndCheck(), EstimateManhattanWorldFrame(), colmap::Reconstruction::ExtractColorsForAllImages(), colmap::mvs::GenerateCandidate(), GetBuildInfo(), colmap::mvs::Workspace::GetFileName(), GetVersionInfo(), colmap::DatabaseCache::Load(), colmap::mvs::Workspace::Load(), main(), operator<<(), colmap::OptionManager::Parse(), colmap::CudaTimer::Print(), colmap::Timer::PrintHours(), colmap::Timer::PrintMinutes(), colmap::Timer::PrintSeconds(), RunImageDeleter(), RunImageFilterer(), RunImageTexturer(), RunImageUndistorter(), RunModelAligner(), RunModelAnalyzer(), RunModelComparer(), RunModelMerger(), RunModelSplitter(), RunPointTriangulator(), RunRigBundleAdjuster(), RunVocabTreeRetriever(), and colmap::mvs::MvsTexturing::TextureMesh().
StringReplace()
std::string colmap::StringReplace (const std::string & str, const std::string & old_str, const std::string & new_str)
Definition at line 140 of file string.cc.
References position.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Reconstruction::ExportRecon3D(), GetPathBaseName(), colmap::ImageReader::Next(), and colmap::CameraDatabase::QuerySensorWidth().
StringRightTrim()
void colmap::StringRightTrim (std::string * str)
Definition at line 183 of file string.cc.
Referenced by BOOST_AUTO_TEST_CASE(), and StringTrim().
StringSplit()
std::vector< std::string > colmap::StringSplit (const std::string & str, const std::string & delim)
Definition at line 166 of file string.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Reconstruction::CreateImageDirs(), CSVToVector(), GetPathBaseName(), colmap::mvs::ImportPMVSWorkspace(), ReadPly(), and SplitFileExtension().
StringStartsWith()
bool colmap::StringStartsWith (const std::string & str, const std::string & prefix)
Definition at line 173 of file string.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::mvs::ImportPMVSWorkspace(), and RunModelAligner().
StringToLower()
void colmap::StringToLower (std::string * str)
Definition at line 193 of file string.cc.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::Bitmap::ExifLatitude(), colmap::Bitmap::ExifLongitude(), HasFileExtension(), colmap::CameraDatabase::QuerySensorWidth(), colmap::mvs::Model::Read(), RunAutomaticReconstructor(), RunDatabaseCleaner(), RunDelaunayMesher(), RunImageUndistorter(), RunModelAligner(), RunModelConverter(), RunModelOrientationAligner(), RunModelSplitter(), RunPatchMatchStereo(), RunProjectGenerator(), and RunStereoFuser().
StringToUpper()
void colmap::StringToUpper (std::string * str)
Definition at line 197 of file string.cc.
Referenced by BOOST_AUTO_TEST_CASE().
StringTrim()
void colmap::StringTrim (std::string * str)
Definition at line 188 of file string.cc.
References StringLeftTrim(), and StringRightTrim().
Referenced by BOOST_AUTO_TEST_CASE(), CSVToVector(), colmap::Bitmap::ExifLatitude(), colmap::Bitmap::ExifLongitude(), ReadPly(), ReadTextFileLines(), and RunImageUndistorterStandalone().
TriangulateMultiViewPoint()
Eigen::Vector3d colmap::TriangulateMultiViewPoint (const std::vector< Eigen::Matrix3x4d > & proj_matrices, const std::vector< Eigen::Vector2d > & points)
Definition at line 72 of file triangulation.cc.
References points.
Referenced by colmap::TriangulationEstimator::Estimate().
TriangulateOptimalPoint()
Eigen::Vector3d colmap::TriangulateOptimalPoint (const Eigen::Matrix3x4d & proj_matrix1, const Eigen::Matrix3x4d & proj_matrix2, const Eigen::Vector2d & point1, const Eigen::Vector2d & point2)
Definition at line 91 of file triangulation.cc.
References EssentialMatrixFromAbsolutePoses(), FindOptimalImageObservations(), and TriangulatePoint().
TriangulateOptimalPoints()
std::vector< Eigen::Vector3d > colmap::TriangulateOptimalPoints (const Eigen::Matrix3x4d & proj_matrix1, const Eigen::Matrix3x4d & proj_matrix2, const std::vector< Eigen::Vector2d > & points1, const std::vector< Eigen::Vector2d > & points2)
Definition at line 107 of file triangulation.cc.
References TriangulatePoint().
TriangulatePoint()
Eigen::Vector3d colmap::TriangulatePoint (const Eigen::Matrix3x4d & proj_matrix1, const Eigen::Matrix3x4d & proj_matrix2, const Eigen::Vector2d & point1, const Eigen::Vector2d & point2)
Definition at line 39 of file triangulation.cc.
Referenced by BOOST_AUTO_TEST_CASE(), CheckCheirality(), colmap::TriangulationEstimator::Estimate(), colmap::IncrementalMapper::RegisterInitialImagePair(), TriangulateOptimalPoint(), TriangulateOptimalPoints(), and TriangulatePoints().
TriangulatePoints()
std::vector< Eigen::Vector3d > colmap::TriangulatePoints (const Eigen::Matrix3x4d & proj_matrix1, const Eigen::Matrix3x4d & proj_matrix2, const std::vector< Eigen::Vector2d > & points1, const std::vector< Eigen::Vector2d > & points2)
Definition at line 55 of file triangulation.cc.
References TriangulatePoint().
TruncateCast()
template<typename T1 , typename T2 > T2 colmap::TruncateCast (const T1 value)
Definition at line 291 of file math.h.
UndistortCamera()
Camera colmap::UndistortCamera (const UndistortCameraOptions & options, const Camera & camera)
Definition at line 754 of file undistortion.cc.
References colmap::UndistortCameraOptions::blank_pixels, Clip(), colmap::Camera::FocalLength(), colmap::Camera::FocalLengthIdxs(), colmap::Camera::FocalLengthX(), colmap::Camera::FocalLengthY(), colmap::Camera::Height(), colmap::Camera::ImageToWorld(), colmap::UndistortCameraOptions::max_image_size, colmap::UndistortCameraOptions::max_scale, colmap::UndistortCameraOptions::min_scale, colmap::SimplePinholeCameraModel::model_id, colmap::PinholeCameraModel::model_id, colmap::Camera::ModelId(), colmap::Camera::PrincipalPointX(), colmap::Camera::PrincipalPointY(), colmap::Camera::Rescale(), colmap::UndistortCameraOptions::roi_max_x, colmap::UndistortCameraOptions::roi_max_y, colmap::UndistortCameraOptions::roi_min_x, colmap::UndistortCameraOptions::roi_min_y, colmap::Camera::SetFocalLengthX(), colmap::Camera::SetFocalLengthY(), colmap::Camera::SetHeight(), colmap::Camera::SetModelId(), colmap::Camera::SetPrincipalPointX(), colmap::Camera::SetPrincipalPointY(), colmap::Camera::SetWidth(), colmap::Camera::Width(), colmap::Camera::WorldToImage(), x, and y.
Referenced by BOOST_AUTO_TEST_CASE(), RectifyAndUndistortStereoImages(), UndistortImage(), and UndistortReconstruction().
UndistortImage()
void colmap::UndistortImage (const UndistortCameraOptions & options, const Bitmap & distorted_bitmap, const Camera & distorted_camera, Bitmap * undistorted_bitmap, Camera * undistorted_camera)
Definition at line 939 of file undistortion.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::CloneMetadata(), colmap::Camera::Height(), colmap::Bitmap::Height(), colmap::Bitmap::IsRGB(), UndistortCamera(), WarpImageBetweenCameras(), colmap::Camera::Width(), and colmap::Bitmap::Width().
Referenced by BOOST_AUTO_TEST_CASE(), and EstimateManhattanWorldFrame().
UndistortReconstruction()
void colmap::UndistortReconstruction (const UndistortCameraOptions & options, Reconstruction * reconstruction)
Definition at line 956 of file undistortion.cc.
References colmap::Reconstruction::Camera(), colmap::Reconstruction::Cameras(), image, colmap::Reconstruction::Image(), colmap::Reconstruction::Images(), and UndistortCamera().
Referenced by BOOST_AUTO_TEST_CASE().
Variance()
template<typename T > double colmap::Variance (const std::vector< T > & elems)
Definition at line 237 of file math.h.
References Mean().
Referenced by StdDev().
VectorContainsDuplicateValues()
template<typename T > bool colmap::VectorContainsDuplicateValues (const std::vector< T > & vector)
Definition at line 143 of file misc.h.
Referenced by colmap::CameraRig::AddSnapshot(), and colmap::BundleAdjustmentConfig::SetConstantTvec().
VectorContainsValue()
template<typename T > bool colmap::VectorContainsValue (const std::vector< T > & vector, const T value)
Definition at line 136 of file misc.h.
Referenced by colmap::ProgressiveSampler::Sample().
VectorToCSV()
template<typename T > std::string colmap::VectorToCSV (const std::vector< T > & values)
Definition at line 150 of file misc.h.
References patch::to_string().
Referenced by colmap::Camera::ParamsToString(), cloudViewer::CameraTab::Reload(), and colmap::CameraTab::Reload().
WarpImageBetweenCameras()
void colmap::WarpImageBetweenCameras (const Camera & source_camera, const Camera & target_camera, const Bitmap & source_image, Bitmap * target_image)
Definition at line 51 of file warp.cc.
References colmap::Bitmap::Allocate(), color, colmap::Camera::Height(), colmap::Bitmap::Height(), colmap::Camera::ImageToWorld(), colmap::Bitmap::InterpolateBilinear(), colmap::Bitmap::IsRGB(), colmap::Camera::Rescale(), colmap::Bitmap::Rescale(), colmap::Bitmap::SetPixel(), colmap::Camera::Width(), colmap::Bitmap::Width(), colmap::Camera::WorldToImage(), x, and y.
Referenced by BOOST_AUTO_TEST_CASE(), and UndistortImage().
WarpImageWithHomography()
void colmap::WarpImageWithHomography (const Eigen::Matrix3d & H, const Bitmap & source_image, Bitmap * target_image)
Definition at line 98 of file warp.cc.
References color, colmap::Bitmap::Height(), colmap::Bitmap::InterpolateBilinear(), colmap::Bitmap::IsRGB(), colmap::Bitmap::SetPixel(), colmap::Bitmap::Width(), x, and y.
Referenced by BOOST_AUTO_TEST_CASE().
WarpImageWithHomographyBetweenCameras()
void colmap::WarpImageWithHomographyBetweenCameras (const Eigen::Matrix3d & H, const Camera & source_camera, const Camera & target_camera, const Bitmap & source_image, Bitmap * target_image)
Definition at line 124 of file warp.cc.
References colmap::Bitmap::Allocate(), color, colmap::Camera::Height(), colmap::Bitmap::Height(), colmap::Camera::ImageToWorld(), colmap::Bitmap::InterpolateBilinear(), colmap::Bitmap::IsRGB(), colmap::Camera::Rescale(), colmap::Bitmap::Rescale(), colmap::Bitmap::SetPixel(), colmap::Camera::Width(), colmap::Bitmap::Width(), colmap::Camera::WorldToImage(), x, and y.
Referenced by BOOST_AUTO_TEST_CASE(), and RectifyAndUndistortStereoImages().
WriteBinaryBlob()
template<typename T > void colmap::WriteBinaryBlob (const std::string & path, const std::vector< T > & data)
Definition at line 171 of file misc.h.
References data, and cloudViewer::t::geometry::path.
WriteBinaryLittleEndian() [1/2]
template<typename T > void colmap::WriteBinaryLittleEndian (std::ostream * stream, const std::vector< T > & data)
Definition at line 132 of file endian.h.
References data.
WriteBinaryLittleEndian() [2/2]
template<typename T > void colmap::WriteBinaryLittleEndian (std::ostream * stream, const T & data)
Definition at line 125 of file endian.h.
References data, and NativeToLittleEndian().
WriteBinaryPlyMesh()
void colmap::WriteBinaryPlyMesh (const std::string & path, const PlyMesh & mesh)
Definition at line 448 of file ply.cc.
References cloudViewer::t::geometry::path.
WriteBinaryPlyPoints()
void colmap::WriteBinaryPlyPoints (const std::string & path, const std::vector< PlyPoint > & points, const bool write_normal, const bool write_rgb)
Definition at line 369 of file ply.cc.
References cloudViewer::t::geometry::path.
Referenced by colmap::Reconstruction::ExportPLY(), colmap::AutomaticReconstructionController::RunDenseMapper(), and RunStereoFuser().
WriteTextPlyMesh()
void colmap::WriteTextPlyMesh (const std::string & path, const PlyMesh & mesh)
Definition at line 423 of file ply.cc.
References cloudViewer::t::geometry::path.
WriteTextPlyPoints()
void colmap::WriteTextPlyPoints (const std::string & path, const std::vector< PlyPoint > & points, const bool write_normal, const bool write_rgb)
Definition at line 323 of file ply.cc.
References QtCompat::endl(), cloudViewer::t::geometry::path, and points.
Variable Documentation
CAMERA_MODEL_ID_TO_NAME
const std::unordered_map<int, std::string> colmap::CAMERA_MODEL_ID_TO_NAME static
Initial value:
=
    InitialzeCameraModelIdToName()
Definition at line 91 of file camera_models.cc.
Referenced by CameraModelIdToName(), and ExistsCameraModelWithId().
CAMERA_MODEL_NAME_TO_ID
const std::unordered_map<std::string, int> colmap::CAMERA_MODEL_NAME_TO_ID static
Initial value:
=
    InitialzeCameraModelNameToId()
Definition at line 88 of file camera_models.cc.
Referenced by CameraModelNameToId(), and ExistsCameraModelWithName().
EMPTY_IDXS
const std::vector<size_t> colmap::EMPTY_IDXS static
Definition at line 154 of file camera_models.cc.
Referenced by CameraModelExtraParamsIdxs(), CameraModelFocalLengthIdxs(), and CameraModelPrincipalPointIdxs().
kDefaultPRNGSeed
int colmap::kDefaultPRNGSeed = 0 static
Definition at line 21 of file random.h.
Referenced by colmap::OptionManager::AddRandomOptions().
kInvalidCameraId
const camera_t colmap::kInvalidCameraId = std::numeric_limits<camera_t>::max()
Definition at line 75 of file types.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::CameraRig::ComputeRelativePoses(), colmap::Image::HasCamera(), colmap::ImageReader::Next(), and colmap::Image::SetCameraId().
kInvalidCameraModelId
const int colmap::kInvalidCameraModelId = -1 static
Definition at line 55 of file camera_models.h.
Referenced by BOOST_AUTO_TEST_CASE(), and CameraModelNameToId().
kInvalidImageId
const image_t colmap::kInvalidImageId = std::numeric_limits<image_t>::max()
Definition at line 76 of file types.h.
Referenced by BOOST_AUTO_TEST_CASE(), cloudViewer::ModelViewerWidget::ClearReconstruction(), colmap::IncrementalMapper::FindInitialImagePair(), colmap::GuidedSiftGPUFeatureMatcher::GuidedSiftGPUFeatureMatcher(), cloudViewer::ModelViewerWidget::SelectObject(), colmap::ModelViewerWidget::SelectObject(), and colmap::SiftGPUFeatureMatcher::SiftGPUFeatureMatcher().
kInvalidImagePairId
const image_pair_t colmap::kInvalidImagePairId
Initial value:
=
        std::numeric_limits<image_pair_t>::max()
Definition at line 77 of file types.h.
Referenced by colmap::IncrementalMapper::BeginReconstruction().
kInvalidPoint2DIdx
const point2D_t colmap::kInvalidPoint2DIdx = std::numeric_limits<point2D_t>::max()
Definition at line 79 of file types.h.
Referenced by BOOST_AUTO_TEST_CASE().
kInvalidPoint3DId
const point3D_t colmap::kInvalidPoint3DId = std::numeric_limits<point3D_t>::max()
Definition at line 80 of file types.h.
Referenced by BOOST_AUTO_TEST_CASE(), cloudViewer::ModelViewerWidget::ClearReconstruction(), colmap::Point2D::HasPoint3D(), colmap::Image::ResetPoint3DForPoint2D(), cloudViewer::ModelViewerWidget::SelectObject(), colmap::ModelViewerWidget::SelectObject(), colmap::Image::SetPoint3DForPoint2D(), cloudViewer::PointViewerWidget::Show(), and colmap::PointViewerWidget::Show().
kUseOpenGL
const bool colmap::kUseOpenGL = false
Definition at line 25 of file gui.h.
Referenced by RunAutomaticReconstructor(), RunExhaustiveMatcher(), RunFeatureExtractor(), RunMatchesImporter(), RunSequentialMatcher(), RunSpatialMatcher(), RunTransitiveMatcher(), and RunVocabTreeMatcher().
PRNG
thread_local std::unique_ptr< std::mt19937 > colmap::PRNG
Definition at line 38 of file random.cc.
Referenced by BOOST_AUTO_TEST_CASE(), RandomGaussian(), RandomInteger(), RandomReal(), and SetPRNGSeed().