ACloudViewer: LasMetadata Namespace Reference
LasMetadata Namespace Reference
Functions
void SaveMetadataInto (const laszip_header &header, ccPointCloud &pointCloud, const std::vector< LasExtraScalarField > &extraScalarFields)
bool LoadVlrs (const ccPointCloud &pointCloud, LasVlr &vlr)
bool LoadScaleFrom (const ccPointCloud &pointCloud, CCVector3d &scale)
bool LoadOffsetFrom (const ccPointCloud &pointCloud, CCVector3d &offset)
bool LoadLasVersionFrom (const ccPointCloud &pointCloud, LasDetails::LasVersion &version)
bool LoadGlobalEncoding (const ccPointCloud &pointCloud, uint16_t &outGlobalEncoding)
bool LoadProjectUUID (const ccPointCloud &pointCloud, laszip_header &header)
static QString ProjectionVLRToString (const laszip_vlr_struct &vlr)
Converts a vlr to a QByteArray.
Variables
constexpr const char X_SCALE [] = "LAS.scale.x"
constexpr const char Y_SCALE [] = "LAS.scale.y"
constexpr const char Z_SCALE [] = "LAS.scale.z"
constexpr const char X_OFFSET [] = "LAS.offset.x"
constexpr const char Y_OFFSET [] = "LAS.offset.y"
constexpr const char Z_OFFSET [] = "LAS.offset.z"
constexpr const char VERSION_MAJOR [] = "LAS.version.major"
constexpr const char VERSION_MINOR [] = "LAS.version.minor"
constexpr const char POINT_FORMAT [] = "LAS.point_format"
constexpr const char GLOBAL_ENCODING [] = "LAS.global_encoding"
constexpr const char PROJECT_UUID [] = "LAS.project_uuid"
constexpr const char SYSTEM_IDENTIFIER [] = "LAS.system_identifier"
constexpr const char VLRS [] = "LAS.vlrs"
constexpr const char EXTRA_FIELDS [] = "LAS.extra_fields"
static constexpr size_t SYSTEM_IDENTIFIER_SIZE = 32
static const char ProjectionVLR [] = "LASF_Projection"
Projection VLR.
Function Documentation
LoadGlobalEncoding()
bool LasMetadata::LoadGlobalEncoding (const ccPointCloud & pointCloud, uint16_t & outGlobalEncoding)
Definition at line 213 of file LasMetadata.cpp.
References ccObject::getMetaData(), GLOBAL_ENCODING, and CVLog::Warning().
Referenced by LasSaver::LasSaver().
LoadLasVersionFrom()
bool LasMetadata::LoadLasVersionFrom (const ccPointCloud & pointCloud, LasDetails::LasVersion & version)
Definition at line 186 of file LasMetadata.cpp.
References ccObject::getMetaData(), POINT_FORMAT, version, VERSION_MAJOR, and VERSION_MINOR.
Referenced by LasIOFilter::saveToFile().
LoadOffsetFrom()
bool LasMetadata::LoadOffsetFrom (const ccPointCloud & pointCloud, CCVector3d & offset)
Definition at line 171 of file LasMetadata.cpp.
References ccObject::getMetaData(), offset, X_OFFSET, Y_OFFSET, and Z_OFFSET.
Referenced by LasIOFilter::saveToFile().
LoadProjectUUID()
bool LasMetadata::LoadProjectUUID (const ccPointCloud & pointCloud, laszip_header & header)
Definition at line 109 of file LasMetadata.cpp.
References ccObject::getMetaData(), ccObject::hasMetaData(), PROJECT_UUID, and CVLog::Warning().
Referenced by LasSaver::LasSaver().
LoadScaleFrom()
bool LasMetadata::LoadScaleFrom (const ccPointCloud & pointCloud, CCVector3d & scale)
Definition at line 156 of file LasMetadata.cpp.
References ccObject::getMetaData(), Tuple3Tpl< Type >::x, X_SCALE, Tuple3Tpl< Type >::y, Y_SCALE, Tuple3Tpl< Type >::z, and Z_SCALE.
Referenced by LasIOFilter::saveToFile().
LoadVlrs()
bool LasMetadata::LoadVlrs (const ccPointCloud & pointCloud, LasVlr & vlr)
Definition at line 141 of file LasMetadata.cpp.
References ccObject::getMetaData(), ccObject::hasMetaData(), and VLRS.
Referenced by LasIOFilter::saveToFile().
ProjectionVLRToString()
static QString LasMetadata::ProjectionVLRToString (const laszip_vlr_struct & vlr) static
Converts a vlr to a QByteArray.
Definition at line 22 of file LasMetadata.cpp.
References ProjectionVLR, and CVLog::Warning().
Referenced by SaveMetadataInto().
SaveMetadataInto()
void LasMetadata::SaveMetadataInto (const laszip_header & header, ccPointCloud & pointCloud, const std::vector< LasExtraScalarField > & extraScalarFields)
Definition at line 56 of file LasMetadata.cpp.
References LasVlr::extraScalarFields, GLOBAL_ENCODING, POINT_FORMAT, PROJECT_UUID, ProjectionVLR, ProjectionVLRToString(), ccObject::setMetaData(), SYSTEM_IDENTIFIER, SYSTEM_IDENTIFIER_SIZE, VERSION_MAJOR, VERSION_MINOR, VLRS, LasVlr::vlrs, X_OFFSET, X_SCALE, Y_OFFSET, Y_SCALE, Z_OFFSET, and Z_SCALE.
Referenced by LasIOFilter::loadFile().
Variable Documentation
EXTRA_FIELDS
constexpr const char LasMetadata::EXTRA_FIELDS[] = "LAS.extra_fields" constexpr
Definition at line 54 of file LasMetadata.h.
GLOBAL_ENCODING
constexpr const char LasMetadata::GLOBAL_ENCODING[] = "LAS.global_encoding" constexpr
Definition at line 50 of file LasMetadata.h.
Referenced by LoadGlobalEncoding(), and SaveMetadataInto().
POINT_FORMAT
constexpr const char LasMetadata::POINT_FORMAT[] = "LAS.point_format" constexpr
Definition at line 49 of file LasMetadata.h.
Referenced by LoadLasVersionFrom(), and SaveMetadataInto().
PROJECT_UUID
constexpr const char LasMetadata::PROJECT_UUID[] = "LAS.project_uuid" constexpr
Definition at line 51 of file LasMetadata.h.
Referenced by LoadProjectUUID(), and SaveMetadataInto().
ProjectionVLR
const char LasMetadata::ProjectionVLR[] = "LASF_Projection" static
Projection VLR.
Definition at line 19 of file LasMetadata.cpp.
Referenced by ProjectionVLRToString(), and SaveMetadataInto().
SYSTEM_IDENTIFIER
constexpr const char LasMetadata::SYSTEM_IDENTIFIER[] = "LAS.system_identifier" constexpr
Definition at line 52 of file LasMetadata.h.
Referenced by SaveMetadataInto().
SYSTEM_IDENTIFIER_SIZE
constexpr size_t LasMetadata::SYSTEM_IDENTIFIER_SIZE = 32 static constexpr
Definition at line 16 of file LasMetadata.cpp.
Referenced by SaveMetadataInto().
VERSION_MAJOR
constexpr const char LasMetadata::VERSION_MAJOR[] = "LAS.version.major" constexpr
Definition at line 47 of file LasMetadata.h.
Referenced by LoadLasVersionFrom(), and SaveMetadataInto().
VERSION_MINOR
constexpr const char LasMetadata::VERSION_MINOR[] = "LAS.version.minor" constexpr
Definition at line 48 of file LasMetadata.h.
Referenced by LoadLasVersionFrom(), and SaveMetadataInto().
VLRS
constexpr const char LasMetadata::VLRS[] = "LAS.vlrs" constexpr
Definition at line 53 of file LasMetadata.h.
Referenced by LoadVlrs(), and SaveMetadataInto().
X_OFFSET
constexpr const char LasMetadata::X_OFFSET[] = "LAS.offset.x" constexpr
Definition at line 44 of file LasMetadata.h.
Referenced by LoadOffsetFrom(), and SaveMetadataInto().
X_SCALE
constexpr const char LasMetadata::X_SCALE[] = "LAS.scale.x" constexpr
Definition at line 41 of file LasMetadata.h.
Referenced by LoadScaleFrom(), and SaveMetadataInto().
Y_OFFSET
constexpr const char LasMetadata::Y_OFFSET[] = "LAS.offset.y" constexpr
Definition at line 45 of file LasMetadata.h.
Referenced by LoadOffsetFrom(), and SaveMetadataInto().
Y_SCALE
constexpr const char LasMetadata::Y_SCALE[] = "LAS.scale.y" constexpr
Definition at line 42 of file LasMetadata.h.
Referenced by LoadScaleFrom(), and SaveMetadataInto().
Z_OFFSET
constexpr const char LasMetadata::Z_OFFSET[] = "LAS.offset.z" constexpr
Definition at line 46 of file LasMetadata.h.
Referenced by LoadOffsetFrom(), and SaveMetadataInto().
Z_SCALE
constexpr const char LasMetadata::Z_SCALE[] = "LAS.scale.z" constexpr
Definition at line 43 of file LasMetadata.h.
Referenced by LoadScaleFrom(), and SaveMetadataInto().