ACloudViewer: cloudViewer::t::geometry::kernel::pointcloud Namespace Reference
cloudViewer::t::geometry::kernel::pointcloud Namespace Reference
Functions
void Unproject (const core::Tensor &depth, utility::optional< std::reference_wrapper< const core::Tensor >> image_colors, core::Tensor &points, utility::optional< std::reference_wrapper< core::Tensor >> colors, const core::Tensor &intrinsics, const core::Tensor &extrinsics, float depth_scale, float depth_max, int64_t stride)
void Project (core::Tensor &depth, utility::optional< std::reference_wrapper< core::Tensor >> image_colors, const core::Tensor &points, utility::optional< std::reference_wrapper< const core::Tensor >> colors, const core::Tensor &intrinsics, const core::Tensor &extrinsics, float depth_scale, float depth_max)
void GetPointMaskWithinAABB (const core::Tensor &points, const core::Tensor &min_bound, const core::Tensor &max_bound, core::Tensor &mask)
void GetPointMaskWithinOBB (const core::Tensor &points, const core::Tensor &center, const core::Tensor &rotation, const core::Tensor &extent, core::Tensor &mask)
void UnprojectCPU (const core::Tensor &depth, utility::optional< std::reference_wrapper< const core::Tensor >> image_colors, core::Tensor &points, utility::optional< std::reference_wrapper< core::Tensor >> colors, const core::Tensor &intrinsics, const core::Tensor &extrinsics, float depth_scale, float depth_max, int64_t stride)
void ProjectCPU (core::Tensor &depth, utility::optional< std::reference_wrapper< core::Tensor >> image_colors, const core::Tensor &points, utility::optional< std::reference_wrapper< const core::Tensor >> colors, const core::Tensor &intrinsics, const core::Tensor &extrinsics, float depth_scale, float depth_max)
void GetPointMaskWithinAABBCPU (const core::Tensor &points, const core::Tensor &min_bound, const core::Tensor &max_bound, core::Tensor &mask)
void GetPointMaskWithinOBBCPU (const core::Tensor &points, const core::Tensor &center, const core::Tensor &rotation, const core::Tensor &extent, core::Tensor &mask)
void NormalizeNormalsCPU (core::Tensor &normals)
void OrientNormalsToAlignWithDirectionCPU (core::Tensor &normals, const core::Tensor &direction)
void OrientNormalsTowardsCameraLocationCPU (const core::Tensor &points, core::Tensor &normals, const core::Tensor &camera)
void ComputeBoundaryPointsCPU (const core::Tensor &points, const core::Tensor &normals, const core::Tensor &indices, const core::Tensor &counts, core::Tensor &mask, double angle_threshold)
void EstimateCovariancesUsingHybridSearchCPU (const core::Tensor &points, core::Tensor &covariances, const double &radius, const int64_t &max_nn)
void EstimateCovariancesUsingKNNSearchCPU (const core::Tensor &points, core::Tensor &covariances, const int64_t &max_nn)
void EstimateCovariancesUsingRadiusSearchCPU (const core::Tensor &points, core::Tensor &covariances, const double &radius)
void EstimateNormalsFromCovariancesCPU (const core::Tensor &covariances, core::Tensor &normals, const bool has_normals)
void EstimateColorGradientsUsingHybridSearchCPU (const core::Tensor &points, const core::Tensor &normals, const core::Tensor &colors, core::Tensor &color_gradient, const double &radius, const int64_t &max_nn)
void EstimateColorGradientsUsingKNNSearchCPU (const core::Tensor &points, const core::Tensor &normals, const core::Tensor &colors, core::Tensor &color_gradient, const int64_t &max_nn)
void EstimateColorGradientsUsingRadiusSearchCPU (const core::Tensor &points, const core::Tensor &normals, const core::Tensor &colors, core::Tensor &color_gradient, const double &radius)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE void GetCoordinateSystemOnPlane (const scalar_t *query, scalar_t *u, scalar_t *v)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE void Swap (scalar_t *x, scalar_t *y)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE void Heapify (scalar_t *arr, int n, int root)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE void HeapSort (scalar_t *arr, int n)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE bool IsBoundaryPoints (const scalar_t *angles, int counts, double angle_threshold)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE void EstimatePointWiseRobustNormalizedCovarianceKernel (const scalar_t *points_ptr, const int32_t *indices_ptr, const int32_t &indices_count, scalar_t *covariance_ptr)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE void ComputeEigenvector0 (const scalar_t *A, const scalar_t eval0, scalar_t *eigen_vector0)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE void ComputeEigenvector1 (const scalar_t *A, const scalar_t *evec0, const scalar_t eval1, scalar_t *eigen_vector1)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE void EstimatePointWiseNormalsWithFastEigen3x3 (const scalar_t *covariance_ptr, scalar_t *normals_ptr)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE void EstimatePointWiseColorGradientKernel (const scalar_t *points_ptr, const scalar_t *normals_ptr, const scalar_t *colors_ptr, const int32_t &idx_offset, const int32_t *indices_ptr, const int32_t &indices_count, scalar_t *color_gradients_ptr)
Function Documentation
ComputeBoundaryPointsCPU()
void cloudViewer::t::geometry::kernel::pointcloud::ComputeBoundaryPointsCPU (const core::Tensor & points, const core::Tensor & normals, const core::Tensor & indices, const core::Tensor & counts, core::Tensor & mask, double angle_threshold)
Definition at line 422 of file PointCloudImpl.h.
References DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, and points.
Referenced by cloudViewer::t::geometry::PointCloud::ComputeBoundaryPoints().
ComputeEigenvector0()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::pointcloud::ComputeEigenvector0 (const scalar_t * A, const scalar_t eval0, scalar_t * eigen_vector0)
Definition at line 717 of file PointCloudImpl.h.
References cloudViewer::core::linalg::kernel::cross_3x1(), and cloudViewer::core::linalg::kernel::dot_3x1().
ComputeEigenvector1()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::pointcloud::ComputeEigenvector1 (const scalar_t * A, const scalar_t * evec0, const scalar_t eval1, scalar_t * eigen_vector1)
Definition at line 766 of file PointCloudImpl.h.
References abs(), cloudViewer::core::linalg::kernel::cross_3x1(), cloudViewer::core::linalg::kernel::dot_3x1(), cloudViewer::core::linalg::kernel::matmul3x3_3x1(), and max().
EstimateColorGradientsUsingHybridSearchCPU()
void cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingHybridSearchCPU (const core::Tensor & points, const core::Tensor & normals, const core::Tensor & colors, core::Tensor & color_gradient, const double & radius, const int64_t & max_nn)
Definition at line 1138 of file PointCloudImpl.h.
References CLOUDVIEWER_DEVICE, colors, DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, EstimatePointWiseColorGradientKernel(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::nns::NearestNeighborSearch::HybridIndex(), cloudViewer::core::nns::NearestNeighborSearch::HybridSearch(), cloudViewer::core::Int32, LogError, normals, cloudViewer::core::ParallelFor(), points, and cloudViewer::core::cuda::Synchronize().
Referenced by cloudViewer::t::geometry::PointCloud::EstimateColorGradients().
EstimateColorGradientsUsingKNNSearchCPU()
void cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingKNNSearchCPU (const core::Tensor & points, const core::Tensor & normals, const core::Tensor & colors, core::Tensor & color_gradient, const int64_t & max_nn)
Definition at line 1191 of file PointCloudImpl.h.
References CLOUDVIEWER_DEVICE, colors, cloudViewer::core::Tensor::Contiguous(), DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, EstimatePointWiseColorGradientKernel(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Int32, cloudViewer::core::nns::NearestNeighborSearch::KnnIndex(), cloudViewer::core::nns::NearestNeighborSearch::KnnSearch(), LogError, normals, cloudViewer::core::ParallelFor(), points, cloudViewer::core::cuda::Synchronize(), and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::t::geometry::PointCloud::EstimateColorGradients().
EstimateColorGradientsUsingRadiusSearchCPU()
void cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingRadiusSearchCPU (const core::Tensor & points, const core::Tensor & normals, const core::Tensor & colors, core::Tensor & color_gradient, const double & radius)
Definition at line 1247 of file PointCloudImpl.h.
References CLOUDVIEWER_DEVICE, colors, cloudViewer::core::Tensor::Contiguous(), DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, EstimatePointWiseColorGradientKernel(), cloudViewer::core::nns::NearestNeighborSearch::FixedRadiusIndex(), cloudViewer::core::nns::NearestNeighborSearch::FixedRadiusSearch(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Int32, LogError, normals, cloudViewer::core::ParallelFor(), points, cloudViewer::core::cuda::Synchronize(), and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::t::geometry::PointCloud::EstimateColorGradients().
EstimateCovariancesUsingHybridSearchCPU()
void cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingHybridSearchCPU (const core::Tensor & points, core::Tensor & covariances, const double & radius, const int64_t & max_nn)
Definition at line 564 of file PointCloudImpl.h.
References CLOUDVIEWER_DEVICE, DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, EstimatePointWiseRobustNormalizedCovarianceKernel(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::nns::NearestNeighborSearch::HybridIndex(), cloudViewer::core::nns::NearestNeighborSearch::HybridSearch(), cloudViewer::core::Int32, LogError, cloudViewer::core::ParallelFor(), points, and cloudViewer::core::cuda::Synchronize().
Referenced by cloudViewer::t::geometry::PointCloud::EstimateNormals().
EstimateCovariancesUsingKNNSearchCPU()
void cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingKNNSearchCPU (const core::Tensor & points, core::Tensor & covariances, const int64_t & max_nn)
Definition at line 665 of file PointCloudImpl.h.
References CLOUDVIEWER_DEVICE, cloudViewer::core::Tensor::Contiguous(), DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, EstimatePointWiseRobustNormalizedCovarianceKernel(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Int32, cloudViewer::core::nns::NearestNeighborSearch::KnnIndex(), cloudViewer::core::nns::NearestNeighborSearch::KnnSearch(), LogError, cloudViewer::core::ParallelFor(), points, and cloudViewer::core::cuda::Synchronize().
Referenced by cloudViewer::t::geometry::PointCloud::EstimateNormals().
EstimateCovariancesUsingRadiusSearchCPU()
void cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingRadiusSearchCPU (const core::Tensor & points, core::Tensor & covariances, const double & radius)
Definition at line 615 of file PointCloudImpl.h.
References CLOUDVIEWER_DEVICE, DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, EstimatePointWiseRobustNormalizedCovarianceKernel(), cloudViewer::core::nns::NearestNeighborSearch::FixedRadiusIndex(), cloudViewer::core::nns::NearestNeighborSearch::FixedRadiusSearch(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Int32, LogError, cloudViewer::core::ParallelFor(), points, and cloudViewer::core::cuda::Synchronize().
Referenced by cloudViewer::t::geometry::PointCloud::EstimateNormals().
EstimateNormalsFromCovariancesCPU()
void cloudViewer::t::geometry::kernel::pointcloud::EstimateNormalsFromCovariancesCPU (const core::Tensor & covariances, core::Tensor & normals, const bool has_normals)
Definition at line 984 of file PointCloudImpl.h.
References CLOUDVIEWER_DEVICE, DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, has_normals, normals, cloudViewer::core::ParallelFor(), and cloudViewer::core::cuda::Synchronize().
Referenced by cloudViewer::t::geometry::PointCloud::EstimateNormals().
EstimatePointWiseColorGradientKernel()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::pointcloud::EstimatePointWiseColorGradientKernel (const scalar_t * points_ptr, const scalar_t * normals_ptr, const scalar_t * colors_ptr, const int32_t & idx_offset, const int32_t * indices_ptr, const int32_t & indices_count, scalar_t * color_gradients_ptr)
Definition at line 1036 of file PointCloudImpl.h.
References cloudViewer::core::linalg::kernel::solve_svd3x3().
Referenced by EstimateColorGradientsUsingHybridSearchCPU(), EstimateColorGradientsUsingKNNSearchCPU(), and EstimateColorGradientsUsingRadiusSearchCPU().
EstimatePointWiseNormalsWithFastEigen3x3()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::pointcloud::EstimatePointWiseNormalsWithFastEigen3x3 (const scalar_t * covariance_ptr, scalar_t * normals_ptr)
Definition at line 846 of file PointCloudImpl.h.
References max(), and min().
EstimatePointWiseRobustNormalizedCovarianceKernel()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::pointcloud::EstimatePointWiseRobustNormalizedCovarianceKernel (const scalar_t * points_ptr, const int32_t * indices_ptr, const int32_t & indices_count, scalar_t * covariance_ptr)
Definition at line 486 of file PointCloudImpl.h.
Referenced by EstimateCovariancesUsingHybridSearchCPU(), EstimateCovariancesUsingKNNSearchCPU(), and EstimateCovariancesUsingRadiusSearchCPU().
GetCoordinateSystemOnPlane()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::pointcloud::GetCoordinateSystemOnPlane (const scalar_t * query, scalar_t * u, scalar_t * v)
Definition at line 339 of file PointCloudImpl.h.
References abs(), and cloudViewer::core::linalg::kernel::cross_3x1().
GetPointMaskWithinAABB()
void cloudViewer::t::geometry::kernel::pointcloud::GetPointMaskWithinAABB (const core::Tensor & points, const core::Tensor & min_bound, const core::Tensor & max_bound, core::Tensor & mask)
Definition at line 101 of file PointCloud.cpp.
References AssertTensorDtype, AssertTensorShape, cloudViewer::core::Bool, cloudViewer::core::Tensor::Contiguous(), CUDA_CALL, GetPointMaskWithinAABBCPU(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), LogError, and points.
Referenced by cloudViewer::t::geometry::AxisAlignedBoundingBox::GetPointIndicesWithinBoundingBox().
GetPointMaskWithinAABBCPU()
void cloudViewer::t::geometry::kernel::pointcloud::GetPointMaskWithinAABBCPU (const core::Tensor & points, const core::Tensor & min_bound, const core::Tensor & max_bound, core::Tensor & mask)
Definition at line 143 of file PointCloudImpl.h.
References DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, and points.
Referenced by GetPointMaskWithinAABB().
GetPointMaskWithinOBB()
void cloudViewer::t::geometry::kernel::pointcloud::GetPointMaskWithinOBB (const core::Tensor & points, const core::Tensor & center, const core::Tensor & rotation, const core::Tensor & extent, core::Tensor & mask)
Definition at line 126 of file PointCloud.cpp.
References AssertTensorDtype, AssertTensorShape, cloudViewer::core::Bool, cloudViewer::core::Tensor::Contiguous(), CUDA_CALL, GetPointMaskWithinOBBCPU(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), LogError, and points.
Referenced by cloudViewer::t::geometry::OrientedBoundingBox::GetPointIndicesWithinBoundingBox().
GetPointMaskWithinOBBCPU()
void cloudViewer::t::geometry::kernel::pointcloud::GetPointMaskWithinOBBCPU (const core::Tensor & points, const core::Tensor & center, const core::Tensor & rotation, const core::Tensor & extent, core::Tensor & mask)
Definition at line 178 of file PointCloudImpl.h.
References cloudViewer::core::Tensor::Contiguous(), DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::Div(), points, and cloudViewer::core::Tensor::Transpose().
Referenced by GetPointMaskWithinOBB().
Heapify()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::pointcloud::Heapify (scalar_t * arr, int n, int root) inline
Definition at line 373 of file PointCloudImpl.h.
Referenced by HeapSort().
HeapSort()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::pointcloud::HeapSort (scalar_t * arr, int n)
Definition at line 391 of file PointCloudImpl.h.
References Heapify().
IsBoundaryPoints()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE bool cloudViewer::t::geometry::kernel::pointcloud::IsBoundaryPoints (const scalar_t * angles, int counts, double angle_threshold)
Definition at line 401 of file PointCloudImpl.h.
References M_PI, and max().
NormalizeNormalsCPU()
void cloudViewer::t::geometry::kernel::pointcloud::NormalizeNormalsCPU (core::Tensor & normals)
Definition at line 222 of file PointCloudImpl.h.
References CLOUDVIEWER_DEVICE, DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, normals, and cloudViewer::core::ParallelFor().
Referenced by cloudViewer::t::geometry::PointCloud::NormalizeNormals().
OrientNormalsToAlignWithDirectionCPU()
void cloudViewer::t::geometry::kernel::pointcloud::OrientNormalsToAlignWithDirectionCPU (core::Tensor & normals, const core::Tensor & direction)
Definition at line 253 of file PointCloudImpl.h.
References CLOUDVIEWER_DEVICE, DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, cloudViewer::core::linalg::kernel::dot_3x1(), normal, normals, and cloudViewer::core::ParallelFor().
Referenced by cloudViewer::t::geometry::PointCloud::OrientNormalsToAlignWithDirection().
OrientNormalsTowardsCameraLocationCPU()
void cloudViewer::t::geometry::kernel::pointcloud::OrientNormalsTowardsCameraLocationCPU (const core::Tensor & points, core::Tensor & normals, const core::Tensor & camera)
Definition at line 287 of file PointCloudImpl.h.
References CLOUDVIEWER_DEVICE, DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, cloudViewer::core::linalg::kernel::dot_3x1(), normal, normals, cloudViewer::core::ParallelFor(), and points.
Referenced by cloudViewer::t::geometry::PointCloud::OrientNormalsTowardsCameraLocation().
Project()
void cloudViewer::t::geometry::kernel::pointcloud::Project (core::Tensor & depth, utility::optional< std::reference_wrapper< core::Tensor >> image_colors, const core::Tensor & points, utility::optional< std::reference_wrapper< const core::Tensor >> colors, const core::Tensor & intrinsics, const core::Tensor & extrinsics, float depth_scale, float depth_max)
Definition at line 63 of file PointCloud.cpp.
References AssertTensorDevice, AssertTensorShape, colors, cloudViewer::core::Tensor::Contiguous(), CUDA_CALL, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), LogError, points, ProjectCPU(), and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::t::geometry::TriangleMesh::ProjectImagesToAlbedo(), cloudViewer::t::geometry::PointCloud::ProjectToDepthImage(), and cloudViewer::t::geometry::PointCloud::ProjectToRGBDImage().
ProjectCPU()
void cloudViewer::t::geometry::kernel::pointcloud::ProjectCPU (core::Tensor & depth, utility::optional< std::reference_wrapper< core::Tensor >> image_colors, const core::Tensor & points, utility::optional< std::reference_wrapper< const core::Tensor >> colors, const core::Tensor & intrinsics, const core::Tensor & extrinsics, float depth_scale, float depth_max)
Definition at line 18 of file PointCloudCPU.cpp.
References colors, cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr(), has_colors, cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::InBoundary(), cloudViewer::core::ParallelFor(), and points.
Referenced by Project().
Swap()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE void cloudViewer::t::geometry::kernel::pointcloud::Swap (scalar_t * x, scalar_t * y) inline
Definition at line 366 of file PointCloudImpl.h.
Unproject()
void cloudViewer::t::geometry::kernel::pointcloud::Unproject (const core::Tensor & depth, utility::optional< std::reference_wrapper< const core::Tensor >> image_colors, core::Tensor & points, utility::optional< std::reference_wrapper< core::Tensor >> colors, const core::Tensor & intrinsics, const core::Tensor & extrinsics, float depth_scale, float depth_max, int64_t stride)
Definition at line 24 of file PointCloud.cpp.
References AssertTensorDevice, AssertTensorShape, colors, cloudViewer::core::Tensor::Contiguous(), CUDA_CALL, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), LogError, points, stride, cloudViewer::core::Tensor::To(), and UnprojectCPU().
Referenced by cloudViewer::t::geometry::PointCloud::CreateFromDepthImage(), and cloudViewer::t::geometry::PointCloud::CreateFromRGBDImage().
UnprojectCPU()
void cloudViewer::t::geometry::kernel::pointcloud::UnprojectCPU (const core::Tensor & depth, utility::optional< std::reference_wrapper< const core::Tensor >> image_colors, core::Tensor & points, utility::optional< std::reference_wrapper< core::Tensor >> colors, const core::Tensor & intrinsics, const core::Tensor & extrinsics, float depth_scale, float depth_max, int64_t stride)
Definition at line 44 of file PointCloudImpl.h.
References colors, count, DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::Float32, cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetShape(), cloudViewer::core::Int32, cloudViewer::t::geometry::InverseTransformation(), points, and stride.
Referenced by Unproject().