ACloudViewer: G3Point Namespace Reference
G3Point Namespace Reference
Classes
class G3PointAction
Functions
RGBAColorsTableType getRandomColors (size_t randomColorsNumber)
Eigen::VectorXf arange (double start, double stop, double step)
template<typename T >
void myPrint (QString name, T array)
template<typename T1 , typename T2 >
T1::value_type quant (T1 &x, const T2 &q)
template<typename T >
double std_dev (const T &vec)
Function Documentation
arange()
Eigen::VectorXf G3Point::arange (double start, double stop, double step)
Definition at line 1039 of file G3PointAction.cpp.
References cloudViewer::utility::floor().
Referenced by G3Point::G3PointAction::wolman().
getRandomColors()
RGBAColorsTableType G3Point::getRandomColors (size_t randomColorsNumber)
Definition at line 97 of file G3PointAction.cpp.
References ccArray< Type, N, ComponentType >::addElement(), ecvColor::RgbTpl< Type >::b, dist(), CVLog::Error(), ecvColor::RgbTpl< Type >::g, max(), ecvColor::RgbTpl< Type >::r, and ccArray< Type, N, ComponentType >::reserveSafe().
Referenced by G3Point::G3PointAction::fit().
myPrint()
template<typename T > void G3Point::myPrint (QString name, T array)
Definition at line 1051 of file G3PointAction.cpp.
References QtCompat::endl(), and name.
quant()
template<typename T1 , typename T2 > T1::value_type G3Point::quant (T1 & x, const T2 & q)
Definition at line 1061 of file G3PointAction.cpp.
References cloudViewer::utility::ceil(), and cloudViewer::utility::floor().
Referenced by lsd_scale_region(), and G3Point::G3PointAction::wolman().
std_dev()
template<typename T > double G3Point::std_dev (const T & vec)
Definition at line 1076 of file G3PointAction.cpp.
Referenced by cloudViewer::t::geometry::PointCloud::RemoveStatisticalOutliers(), and G3Point::G3PointAction::wolman().