ACloudViewer: cloudViewer::t::geometry::kernel::image Namespace Reference
cloudViewer::t::geometry::kernel::image Namespace Reference
Functions
void To (const core::Tensor &src, core::Tensor &dst, double scale, double offset)
void ClipTransform (const core::Tensor &src, core::Tensor &dst, float scale, float min_value, float max_value, float clip_fill)
void PyrDownDepth (const core::Tensor &src, core::Tensor &dst, float diff_threshold, float invalid_fill)
void CreateVertexMap (const core::Tensor &src, core::Tensor &dst, const core::Tensor &intrinsics, float invalid_fill)
void CreateNormalMap (const core::Tensor &src, core::Tensor &dst, float invalid_fill)
void ColorizeDepth (const core::Tensor &src, core::Tensor &dst, float scale, float min_value, float max_value)
void ToCPU (const core::Tensor &src, core::Tensor &dst, double scale, double offset)
void ClipTransformCPU (const core::Tensor &src, core::Tensor &dst, float scale, float min_value, float max_value, float clip_fill=0.0f)
void PyrDownDepthCPU (const core::Tensor &src, core::Tensor &dst, float diff_threshold, float invalid_fill)
void CreateVertexMapCPU (const core::Tensor &src, core::Tensor &dst, const core::Tensor &intrinsics, float invalid_fill)
void CreateNormalMapCPU (const core::Tensor &src, core::Tensor &dst, float invalid_fill)
void ColorizeDepthCPU (const core::Tensor &src, core::Tensor &dst, float scale, float min_value, float max_value)
Function Documentation
ClipTransform()
void cloudViewer::t::geometry::kernel::image::ClipTransform (const core::Tensor & src, core::Tensor & dst, float scale, float min_value, float max_value, float clip_fill)
Definition at line 31 of file Image.cpp.
References ClipTransformCPU(), CUDA_CALL, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Device::IsCUDA(), and LogError.
Referenced by cloudViewer::t::geometry::Image::ClipTransform().
ClipTransformCPU()
void cloudViewer::t::geometry::kernel::image::ClipTransformCPU (const core::Tensor & src, core::Tensor & dst, float scale, float min_value, float max_value, float clip_fill = 0.0f)
Definition at line 88 of file ImageImpl.h.
References DISPATCH_DTYPE_TO_TEMPLATE.
Referenced by ClipTransform().
ColorizeDepth()
void cloudViewer::t::geometry::kernel::image::ColorizeDepth (const core::Tensor & src, core::Tensor & dst, float scale, float min_value, float max_value)
Definition at line 92 of file Image.cpp.
References ColorizeDepthCPU(), CUDA_CALL, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Device::IsCUDA(), and LogError.
Referenced by cloudViewer::t::geometry::Image::ColorizeDepth().
ColorizeDepthCPU()
void cloudViewer::t::geometry::kernel::image::ColorizeDepthCPU (const core::Tensor & src, core::Tensor & dst, float scale, float min_value, float max_value)
Definition at line 309 of file ImageImpl.h.
References DISPATCH_DTYPE_TO_TEMPLATE.
Referenced by ColorizeDepth().
CreateNormalMap()
void cloudViewer::t::geometry::kernel::image::CreateNormalMap (const core::Tensor & src, core::Tensor & dst, float invalid_fill)
Definition at line 79 of file Image.cpp.
References CreateNormalMapCPU(), CUDA_CALL, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Device::IsCUDA(), and LogError.
Referenced by cloudViewer::t::geometry::Image::CreateNormalMap().
CreateNormalMapCPU()
void cloudViewer::t::geometry::kernel::image::CreateNormalMapCPU (const core::Tensor & src, core::Tensor & dst, float invalid_fill)
Definition at line 244 of file ImageImpl.h.
References CLOUDVIEWER_DEVICE, cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr(), cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetShape(), max(), normal, and cloudViewer::core::ParallelFor().
Referenced by CreateNormalMap().
CreateVertexMap()
void cloudViewer::t::geometry::kernel::image::CreateVertexMap (const core::Tensor & src, core::Tensor & dst, const core::Tensor & intrinsics, float invalid_fill)
Definition at line 62 of file Image.cpp.
References cloudViewer::core::Tensor::Contiguous(), CreateVertexMapCPU(), CUDA_CALL, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Device::IsCUDA(), LogError, and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::t::geometry::Image::CreateVertexMap().
CreateVertexMapCPU()
void cloudViewer::t::geometry::kernel::image::CreateVertexMapCPU (const core::Tensor & src, core::Tensor & dst, const core::Tensor & intrinsics, float invalid_fill)
Definition at line 197 of file ImageImpl.h.
References CLOUDVIEWER_DEVICE, cloudViewer::core::Tensor::Eye(), cloudViewer::core::Float64, cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr(), cloudViewer::core::ParallelFor(), and cloudViewer::t::geometry::kernel::TransformIndexer::Unproject().
Referenced by CreateVertexMap().
PyrDownDepth()
void cloudViewer::t::geometry::kernel::image::PyrDownDepth (const core::Tensor & src, core::Tensor & dst, float diff_threshold, float invalid_fill)
Definition at line 48 of file Image.cpp.
References CUDA_CALL, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Device::IsCUDA(), LogError, and PyrDownDepthCPU().
Referenced by cloudViewer::t::geometry::Image::PyrDownDepth().
PyrDownDepthCPU()
void cloudViewer::t::geometry::kernel::image::PyrDownDepthCPU (const core::Tensor & src, core::Tensor & dst, float diff_threshold, float invalid_fill)
Definition at line 124 of file ImageImpl.h.
References abs(), CLOUDVIEWER_DEVICE, cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr(), cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetShape(), max(), min(), and cloudViewer::core::ParallelFor().
Referenced by PyrDownDepth().
To()
void cloudViewer::t::geometry::kernel::image::To (const core::Tensor & src, core::Tensor & dst, double scale, double offset)
Definition at line 17 of file Image.cpp.
References CUDA_CALL, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Device::IsCUDA(), LogError, offset, and ToCPU().
Referenced by cloudViewer::core::SmallVectorTemplateCommon< T, typename >::assertSafeToAddRange(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterClear(), cloudViewer::t::pipelines::registration::ComputeFPFHFeature(), cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBJylanki(), cloudViewer::t::pipelines::kernel::ComputePoseDopplerICP(), cloudViewer::t::pipelines::registration::ComputeRegistrationResult(), cloudViewer::t::pipelines::registration::TransformationEstimationPointToPoint::ComputeRMSE(), cloudViewer::t::pipelines::registration::TransformationEstimationPointToPlane::ComputeRMSE(), cloudViewer::t::pipelines::registration::TransformationEstimationForColoredICP::ComputeRMSE(), cloudViewer::t::pipelines::registration::TransformationEstimationForDopplerICP::ComputeRMSE(), cloudViewer::t::pipelines::kernel::ComputeRtPointToPoint(), cloudViewer::core::SmallVectorImpl< T >::insert(), cloudViewer::t::pipelines::slac::ControlGrid::Parameterize(), cloudViewer::t::io::DepthNoiseSimulator::Simulate(), cloudViewer::t::geometry::Image::To(), cloudViewer::t::pipelines::slac::UpdatePoses(), and cloudViewer::t::io::WriteHashMap().
ToCPU()
void cloudViewer::t::geometry::kernel::image::ToCPU (const core::Tensor & src, core::Tensor & dst, double scale, double offset)
Definition at line 31 of file ImageImpl.h.
References cloudViewer::core::Float32, cloudViewer::core::Float64, indexer, cloudViewer::core::Int16, cloudViewer::core::Int32, cloudViewer::core::Int64, cloudViewer::core::Int8, LINEAR_SATURATE, cloudViewer::core::NONE, cloudViewer::core::UInt16, cloudViewer::core::UInt32, cloudViewer::core::UInt64, and cloudViewer::core::UInt8.
Referenced by To().