ACloudViewer: ecvFileUtils Namespace Reference
ecvFileUtils Namespace Reference
Functions
QString defaultDocPath ()
Shortcut for getting the documents location path.
Function Documentation
defaultDocPath()
QString ecvFileUtils::defaultDocPath () inline
Shortcut for getting the documents location path.
Definition at line 30 of file ecvFileUtils.h.
Referenced by CSVMatrixOpenDialog::CSVMatrixOpenDialog(), qFacets::exportFacets(), qFacets::exportFacetsInfo(), DistanceMapGenerationDlg::exportMapAsGrid(), DxfProfilesExportDlg::initFromPersistentSettings(), DistanceMapGenerationDlg::loadOverlaySymbols(), qM3C2Dialog::loadParamsFromFile(), qSRA::loadProfile(), G3PointPlots::onExportToCSV(), G3PointPlots::onExportToImage(), and qM3C2Dialog::saveParamsToFile().