ACloudViewer: cloudViewer::reconstruction::feature Namespace Reference
cloudViewer::reconstruction::feature Namespace Reference
Functions
void pybind_feature_methods (py::module &m)
void pybind_feature (py::module &m)
Variables
static const std::unordered_map< std::string, std::string > map_shared_argument_docstrings
Function Documentation
pybind_feature()
void cloudViewer::reconstruction::feature::pybind_feature (py::module & m)
Definition at line 110 of file feature.cpp.
References pybind_feature_methods().
Referenced by cloudViewer::reconstruction::pybind_reconstruction().
pybind_feature_methods()
void cloudViewer::reconstruction::feature::pybind_feature_methods (py::module & m)
Definition at line 38 of file feature.cpp.
References cloudViewer::docstring::FunctionDocInject(), and map_shared_argument_docstrings.
Referenced by pybind_feature().
Variable Documentation
map_shared_argument_docstrings
const std::unordered_map<std::string, std::string> cloudViewer::reconstruction::feature::map_shared_argument_docstrings static
Initial value:
= {
                {"database_path",
                 "Path to database in which to store the extracted data"},
                {"image_path",
                 "Root path to folder which contains the images."},
                {"image_list_path", "The images list file path with ."},
                {"import_path",
                 "Optional list of images to read. "
                 "The list must contain the relative path of the images with "
                 "respect to the image_path"},
                {"camera_mode",
                 "The camera mode like { AUTO = 0, SINGLE = 1, PER_FOLDER = 2, "
                 "PER_IMAGE = 3 }"},
                {"match_list_path", "The matches list directories"},
                {"match_type",
                 "The match type supported {'pairs', 'raw', 'inliers'}"}}
Definition at line 21 of file feature.cpp.
Referenced by pybind_feature_methods().