ACloudViewer: cloudViewer::core::tensor_init Namespace Reference
cloudViewer::core::tensor_init Namespace Reference
Classes
struct NestedInitializerImpl
struct NestedInitializerImpl< T, 0 >
struct InitializerDim
struct InitializerDim< std::initializer_list< L > >
struct InitializerShapeImpl
struct InitializerShapeImpl< 0 >
Typedefs
template<typename T , size_t D>
using NestedInitializerList = typename NestedInitializerImpl< T, D >::type
Functions
template<typename L , size_t... D>
SizeVector InitializerShape (const L &list, std::index_sequence< D... >)
template<typename L >
SizeVector InferShape (const L &list)
template<typename T , typename L >
void NestedCopy (T &&iter, const L &list)
template<typename T , typename L >
void NestedCopy (T &&iter, const std::initializer_list< L > &list)
template<typename T , size_t D>
std::vector< T > ToFlatVector (const SizeVector &shape, const tensor_init::NestedInitializerList< T, D > &nested_list)
Typedef Documentation
NestedInitializerList
template<typename T , size_t D> using cloudViewer::core::tensor_init::NestedInitializerList = typedef typename NestedInitializerImpl<T, D>::type
Definition at line 36 of file TensorInit.h.
Function Documentation
InferShape()
template<typename L > SizeVector cloudViewer::core::tensor_init::InferShape (const L & list)
Definition at line 82 of file TensorInit.h.
References cloudViewer::core::SmallVectorImpl< T >::resize(), and cloudViewer::core::SmallVectorBase< Size_T >::size().
InitializerShape()
template<typename L , size_t... D> SizeVector cloudViewer::core::tensor_init::InitializerShape (const L & list, std::index_sequence< D... >)
Definition at line 76 of file TensorInit.h.
References cloudViewer::core::tensor_init::InitializerShapeImpl< D >::value().
NestedCopy() [1/2]
template<typename T , typename L > void cloudViewer::core::tensor_init::NestedCopy (T && iter, const L & list)
Definition at line 95 of file TensorInit.h.
Referenced by NestedCopy(), and ToFlatVector().
NestedCopy() [2/2]
template<typename T , typename L > void cloudViewer::core::tensor_init::NestedCopy (T && iter, const std::initializer_list< L > & list)
Definition at line 100 of file TensorInit.h.
References NestedCopy().
ToFlatVector()
template<typename T , size_t D> std::vector<T> cloudViewer::core::tensor_init::ToFlatVector (const SizeVector & shape, const tensor_init::NestedInitializerList< T, D > & nested_list)
Definition at line 107 of file TensorInit.h.
References NestedCopy(), and cloudViewer::core::SizeVector::NumElements().