ACloudViewer: Runtime Namespace Reference
Runtime Namespace Reference
Classes
class PythonPluginInterface
Interface that 'class-style' PythonPlugin must implement to be loaded.
class PythonPluginTrampoline
struct RegisteredPlugin
Functions
ccGuiPythonInstance * GetInstance () noexcept
ccCommandLineInterface * GetCmdLineInstance () noexcept
void setMainAppInterfaceInstance (ecvMainAppInterface *appInterface) noexcept(false)
void unsetMainAppInterfaceInstance () noexcept
Unsets the app interface pointer.
void setCmdLineInterfaceInstance (ccCommandLineInterface *cmdLine) noexcept
void unsetCmdLineInterfaceInstance () noexcept
Unsets the pointer to the cmdline app interface.
Variables
static ccGuiPythonInstance * s_pythonInstance {nullptr}
static ccCommandLineInterface * s_cmdLineInstance {nullptr}
Function Documentation
GetCmdLineInstance()
ccCommandLineInterface* Runtime::GetCmdLineInstance () noexcept
Definition at line 77 of file Runtime.cpp.
References s_cmdLineInstance.
Referenced by PYBIND11_EMBEDDED_MODULE().
GetInstance()
ccGuiPythonInstance* Runtime::GetInstance () noexcept
Definition at line 72 of file Runtime.cpp.
References s_pythonInstance.
Referenced by cloudViewer::core::AddMMCUDA(), cloudViewer::visualization::rendering::GeometryBuffersBuilder::CreateIndexBuffer(), cloudViewer::visualization::GetGlobalColorMap(), cloudViewer::core::Cacher::GetInstance(), ecvGenericDisplayTools::GetPerspectiveState(), cloudViewer::core::InverseCUDA(), cloudViewer::core::LeastSquaresCUDA(), cloudViewer::core::LUCUDA(), cloudViewer::core::MatmulCUDA(), cloudViewer::visualization::visualizer::O3DVisualizer::O3DVisualizer(), ecvGenericDisplayTools::Project(), PYBIND11_EMBEDDED_MODULE(), cloudViewer::visualization::SetGlobalColorMap(), cloudViewer::core::SolveCUDA(), cloudViewer::core::SVDCUDA(), ecvGenericDisplayTools::ToDisplayPoint(), ecvGenericDisplayTools::ToWorldPoint(), cloudViewer::core::TrilSYCL(), cloudViewer::core::TriulSYCL(), and ecvGenericDisplayTools::Unproject().
setCmdLineInterfaceInstance()
void Runtime::setCmdLineInterfaceInstance (ccCommandLineInterface * cmdLine) noexcept
Sets the internal pointer to the command line app interface that python script will be able to access in the CMD Line mode
Definition at line 99 of file Runtime.cpp.
References s_cmdLineInstance.
Referenced by PythonPlugin::registerCommands().
setMainAppInterfaceInstance()
void Runtime::setMainAppInterfaceInstance (ecvMainAppInterface * appInterface) noexcept
Sets the internal pointer to the app interface that python scripts will be able to access in GUI mode
Definition at line 82 of file Runtime.cpp.
References s_pythonInstance.
Referenced by PythonPlugin::setMainAppInterface().
unsetCmdLineInterfaceInstance()
void Runtime::unsetCmdLineInterfaceInstance () noexcept
Unsets the pointer to the cmdline app interface.
Definition at line 107 of file Runtime.cpp.
References s_cmdLineInstance.
Referenced by PythonPlugin::~PythonPlugin().
unsetMainAppInterfaceInstance()
void Runtime::unsetMainAppInterfaceInstance () noexcept
Unsets the app interface pointer.
Definition at line 90 of file Runtime.cpp.
References s_pythonInstance.
Referenced by PythonPlugin::~PythonPlugin().
Variable Documentation
s_cmdLineInstance
ccCommandLineInterface* Runtime::s_cmdLineInstance {nullptr} static
Definition at line 70 of file Runtime.cpp.
Referenced by GetCmdLineInstance(), setCmdLineInterfaceInstance(), and unsetCmdLineInterfaceInstance().
s_pythonInstance
ccGuiPythonInstance* Runtime::s_pythonInstance {nullptr} static
Definition at line 68 of file Runtime.cpp.
Referenced by GetInstance(), setMainAppInterfaceInstance(), and unsetMainAppInterfaceInstance().