ACloudViewer: PCLModules Namespace Reference
PCLModules Namespace Reference
Classes
struct ConditionParameters
struct MLSParameters
class FeatureCloud
class TemplateMatching
Enumerations
enum MarchingMethod { HOPPE , RBF }
Functions
int GetRegionGrowing (const PointCloudT::ConstPtr cloud, std::vector< pcl::PointIndices > &clusters, PointCloudRGB::Ptr cloud_segmented, int k, int min_cluster_size, int max_cluster_size, unsigned int neighbour_number, float smoothness_theta, float curvature)
Basic Region Growing.
int GetRegionGrowingRGB (const PointCloudRGB::ConstPtr cloud, std::vector< pcl::PointIndices > &clusters, PointCloudRGB::Ptr cloud_segmented, int min_cluster_size, float neighbors_distance, float point_color_diff, float region_color_diff)
Color based Region Growing.
int GetSACSegmentation (const PointCloudT::ConstPtr cloud, pcl::PointIndices::Ptr inliers, pcl::ModelCoefficients::Ptr coefficients, const int &methodType, const int &modelType, float distanceThreshold, float probability, int maxIterations, float minRadiusLimits, float maxRadiusLimits, float normalDisWeight)
int GridProjection (const PointCloudNormal::ConstPtr &cloudWithNormals, PCLMesh &outMesh, float resolution, int paddingSize, int maxSearchLevel)
int GetPoissonReconstruction (const PointCloudNormal::ConstPtr &cloudWithNormals, PCLMesh &outMesh, int degree, int treeDepth, int isoDivideDepth, int solverDivideDepth, float scale, float samplesPerNode, bool useConfidence, bool useManifold, bool outputPolygons)
int GetGreedyTriangulation (const PointCloudNormal::ConstPtr &cloudWithNormals, PCLMesh &outMesh, int trigulationSearchRadius, float weightingFactor, int maxNearestNeighbors, int maxSurfaceAngle, int minAngle, int maxAngle, bool normalConsistency)
int GetProjection (const PointCloudT::ConstPtr &originCloud, PointCloudT::Ptr &projectedCloud, const pcl::ModelCoefficients::ConstPtr coefficients, const int &modelType)
int GetProjection (const PointCloudT::ConstPtr &originCloud, PointCloudT::Ptr &projectedCloud, float coefficientA, float coefficientB, float coefficientC, float coefficientD, const int &modelType)
template int GetMarchingCubes< PointNT > (const PointCloudNormal::ConstPtr inCloud, const MarchingMethod &marchingMethod, PCLMesh &outMesh, float epsilon, float isoLevel, float gridResolution, float percentageExtendGrid)
template int ComputeNormals< PointT, NormalT > (const PointCloudT::ConstPtr inCloud, CloudNormal::Ptr outcloud, const float radius, const bool useKnn, bool normalConsistency, int maxThreadCount)
template int ComputeNormals< PointRGB, NormalT > (const PointCloudRGB::ConstPtr inCloud, CloudNormal::Ptr outcloud, const float radius, const bool useKnn, bool normalConsistency, int maxThreadCount)
template int ComputeNormals< PointRGBA, NormalT > (const PointCloudRGBA::ConstPtr inCloud, CloudNormal::Ptr outcloud, const float radius, const bool useKnn, bool normalConsistency, int maxThreadCount)
template int ComputeNormals< PointT, PointNT > (const PointCloudT::ConstPtr inCloud, PointCloudNormal::Ptr outcloud, const float radius, const bool useKnn, bool normalConsistency, int maxThreadCount)
template int ComputeNormals< PointRGB, PointNT > (const PointCloudRGB::ConstPtr inCloud, PointCloudNormal::Ptr outcloud, const float radius, const bool useKnn, bool normalConsistency, int maxThreadCount)
template int ComputeNormals< PointRGBA, PointNT > (const PointCloudRGBA::ConstPtr inCloud, PointCloudNormal::Ptr outcloud, const float radius, const bool useKnn, bool normalConsistency, int maxThreadCount)
template int RemoveOutliersStatistical< PCLCloud > (const PCLCloud::ConstPtr inCloud, PCLCloud::Ptr outCloud, int knn, double nSigma)
template int GetConvexHullReconstruction< PointT > (const PointCloudT::ConstPtr inCloud, PCLMesh &outMesh, int dimension)
template int GetConvexHullReconstruction< PointRGB > (const PointCloudRGB::ConstPtr inCloud, PCLMesh &outMesh, int dimension)
template int GetConcaveHullReconstruction< PointT > (const PointCloudT::ConstPtr inCloud, PCLMesh &outMesh, int dimension, float alpha)
template int GetConcaveHullReconstruction< PointRGB > (const PointCloudRGB::ConstPtr inCloud, PCLMesh &outMesh, int dimension, float alpha)
template int CropHullFilter< PointT > (const PointCloudT::ConstPtr inCloud, const PointCloudT::ConstPtr boundingBox, PointCloudT::Ptr outCloud, int dimensions)
template int CropHullFilter< PointRGB > (const PointCloudRGB::ConstPtr inCloud, const PointCloudT::ConstPtr boundingBox, PointCloudRGB::Ptr outCloud, int dimensions)
template int EuclideanCluster< PointT > (const PointCloudT::ConstPtr inCloud, std::vector< pcl::PointIndices > &cluster_indices, float clusterTolerance, int minClusterSize, int maxClusterSize)
template int EuclideanCluster< PointNT > (const PointCloudNormal::ConstPtr inCloud, std::vector< pcl::PointIndices > &cluster_indices, float clusterTolerance, int minClusterSize, int maxClusterSize)
template int ProgressiveMpFilter< PointT > (const PointCloudT::ConstPtr inCloud, pcl::PointIndicesPtr groundIndices, int maxWindowSize, float slope, float initialDistance, float maxDistance)
template int ProgressiveMpFilter< PointRGB > (const PointCloudRGB::ConstPtr inCloud, pcl::PointIndicesPtr groundIndices, int maxWindowSize, float slope, float initialDistance, float maxDistance)
template int ConditionalRemovalFilter< PointNT > (const PointCloudNormal::ConstPtr inCloud, const ConditionParameters &params, PointCloudNormal::Ptr outCloud, bool keepOrganized)
template int SmoothMls< PointT, PointNT > (const PointCloudT::ConstPtr &inCloud, const MLSParameters &params, PointCloudNormal::Ptr &outcloud)
template int EstimateSIFT< pcl::PointXYZI, PointT > (const pcl::PointCloud< pcl::PointXYZI >::ConstPtr inCloud, PointCloudT::Ptr outcloud, int nr_octaves, float min_scale, int nr_scales_per_octave, float min_contrast)
template int EstimateSIFT< PointRGB, PointT > (const PointCloudRGB::ConstPtr inCloud, PointCloudT::Ptr outcloud, int nr_octaves, float min_scale, int nr_scales_per_octave, float min_contrast)
template int EstimateSIFT< PointRGBA, PointT > (const PointCloudRGBA::ConstPtr inCloud, PointCloudT::Ptr outcloud, int nr_octaves, float min_scale, int nr_scales_per_octave, float min_contrast)
template int EstimateShot< PointT, NormalT, pcl::SHOT352 > (const PointCloudT::ConstPtr inCloud, const PointCloudT::ConstPtr keyPoints, const CloudNormal::ConstPtr normals, pcl::PointCloud< pcl::SHOT352 >::Ptr outDescriptors, float searchRadius, int maxThreadCount)
template int EstimateShot< PointRGB, NormalT, pcl::SHOT352 > (const PointCloudRGB::ConstPtr inCloud, const PointCloudRGB::ConstPtr keyPoints, const CloudNormal::ConstPtr normals, pcl::PointCloud< pcl::SHOT352 >::Ptr outDescriptors, float searchRadius, int maxThreadCount)
template int EstimateShot< PointRGBA, NormalT, pcl::SHOT352 > (const PointCloudRGBA::ConstPtr inCloud, const PointCloudRGBA::ConstPtr keyPoints, const CloudNormal::ConstPtr normals, pcl::PointCloud< pcl::SHOT352 >::Ptr outDescriptors, float searchRadius, int maxThreadCount)
template int DONEstimation< PointT, PointNT, PointNT > (const PointCloudT::ConstPtr inCloud, const PointCloudNormal::ConstPtr normalsLargeScale, const PointCloudNormal::ConstPtr normalsSmallScale, PointCloudNormal::Ptr outCloud)
template int DONEstimation< PointRGB, PointNT, PointNT > (const PointCloudRGB::ConstPtr inCloud, const PointCloudNormal::ConstPtr normalsLargeScale, const PointCloudNormal::ConstPtr normalsSmallScale, PointCloudNormal::Ptr outCloud)
template int EstimateLocalReferenceFrame< PointT, NormalT, pcl::ReferenceFrame > (const PointCloudT::ConstPtr inCloud, const PointCloudT::ConstPtr keyPoints, const CloudNormal::ConstPtr normals, pcl::PointCloud< pcl::ReferenceFrame >::Ptr outRF, float searchRadius)
template int EstimateLocalReferenceFrame< PointRGB, NormalT, pcl::ReferenceFrame > (const PointCloudRGB::ConstPtr inCloud, const PointCloudRGB::ConstPtr keyPoints, const CloudNormal::ConstPtr normals, pcl::PointCloud< pcl::ReferenceFrame >::Ptr outRF, float searchRadius)
template int EstimateLocalReferenceFrame< PointRGBA, NormalT, pcl::ReferenceFrame > (const PointCloudRGBA::ConstPtr inCloud, const PointCloudRGBA::ConstPtr keyPoints, const CloudNormal::ConstPtr normals, pcl::PointCloud< pcl::ReferenceFrame >::Ptr outRF, float searchRadius)
template int EstimateHough3DGrouping< PointT, PointT, pcl::ReferenceFrame, pcl::ReferenceFrame > (const PointCloudT::ConstPtr modelKeypoints, const PointCloudT::ConstPtr sceneKeypoints, const pcl::PointCloud< pcl::ReferenceFrame >::ConstPtr modelRF, const pcl::PointCloud< pcl::ReferenceFrame >::ConstPtr sceneRF, const pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> &rotoTranslations, std::vector< pcl::Correspondences > &clusteredCorrs, float houghBinSize, float houghThreshold)
template int EstimateHough3DGrouping< PointRGB, PointRGB, pcl::ReferenceFrame, pcl::ReferenceFrame > (const PointCloudRGB::ConstPtr modelKeypoints, const PointCloudRGB::ConstPtr sceneKeypoints, const pcl::PointCloud< pcl::ReferenceFrame >::ConstPtr modelRF, const pcl::PointCloud< pcl::ReferenceFrame >::ConstPtr sceneRF, const pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> &rotoTranslations, std::vector< pcl::Correspondences > &clusteredCorrs, float houghBinSize, float houghThreshold)
template int EstimateHough3DGrouping< PointRGBA, PointRGBA, pcl::ReferenceFrame, pcl::ReferenceFrame > (const PointCloudRGBA::ConstPtr modelKeypoints, const PointCloudRGBA::ConstPtr sceneKeypoints, const pcl::PointCloud< pcl::ReferenceFrame >::ConstPtr modelRF, const pcl::PointCloud< pcl::ReferenceFrame >::ConstPtr sceneRF, const pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> &rotoTranslations, std::vector< pcl::Correspondences > &clusteredCorrs, float houghBinSize, float houghThreshold)
template int EstimateGeometricConsistencyGrouping< PointT, PointT > (const PointCloudT::ConstPtr modelKeypoints, const PointCloudT::ConstPtr sceneKeypoints, const pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> &rotoTranslations, std::vector< pcl::Correspondences > &clusteredCorrs, float gcSize, float gcThreshold)
template int EstimateGeometricConsistencyGrouping< PointRGB, PointRGB > (const PointCloudRGB::ConstPtr modelKeypoints, const PointCloudRGB::ConstPtr sceneKeypoints, const pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> &rotoTranslations, std::vector< pcl::Correspondences > &clusteredCorrs, float gcSize, float gcThreshold)
template int EstimateGeometricConsistencyGrouping< PointRGBA, PointRGBA > (const PointCloudRGBA::ConstPtr modelKeypoints, const PointCloudRGBA::ConstPtr sceneKeypoints, const pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> &rotoTranslations, std::vector< pcl::Correspondences > &clusteredCorrs, float gcSize, float gcThreshold)
template int EstimateHarris3D< PointT > (const PointCloudT::ConstPtr inCloud, pcl::PointCloud< pcl::PointXYZI >::Ptr outcloud, float normalRadius, float searchRadius)
template int EstimateHarris3D< PointRGB > (const PointCloudRGB::ConstPtr inCloud, pcl::PointCloud< pcl::PointXYZI >::Ptr outcloud, float normalRadius, float searchRadius)
template int EstimateHarris3D< PointRGBA > (const PointCloudRGBA::ConstPtr inCloud, pcl::PointCloud< pcl::PointXYZI >::Ptr outcloud, float normalRadius, float searchRadius)
template int GetUniformSampling< PointT > (const PointCloudT::ConstPtr inCloud, PointCloudT::Ptr outcloud, const float &searchRadius)
template int GetUniformSampling< PointRGB > (const PointCloudRGB::ConstPtr inCloud, PointCloudRGB::Ptr outcloud, const float &searchRadius)
template int GetUniformSampling< PointRGBA > (const PointCloudRGBA::ConstPtr inCloud, PointCloudRGBA::Ptr outcloud, const float &searchRadius)
template int PassThroughFilter< PointT > (const PointCloudT::ConstPtr inCloud, PointCloudT::Ptr outcloud, const QString &filterFieldName, const float &limit_min, const float &limit_max)
template int PassThroughFilter< PointRGB > (const PointCloudRGB::ConstPtr inCloud, PointCloudRGB::Ptr outcloud, const QString &filterFieldName, const float &limit_min, const float &limit_max)
template int PassThroughFilter< PointRGBA > (const PointCloudRGBA::ConstPtr inCloud, PointCloudRGBA::Ptr outcloud, const QString &filterFieldName, const float &limit_min, const float &limit_max)
template int VoxelGridFilter< PointT > (const PointCloudT::ConstPtr inCloud, PointCloudT::Ptr outcloud, const float &leafSizeX, const float &leafSizeY, const float &leafSizeZ)
template int VoxelGridFilter< PointRGB > (const PointCloudRGB::ConstPtr inCloud, PointCloudRGB::Ptr outcloud, const float &leafSizeX, const float &leafSizeY, const float &leafSizeZ)
template int VoxelGridFilter< PointRGBA > (const PointCloudRGBA::ConstPtr inCloud, PointCloudRGBA::Ptr outcloud, const float &leafSizeX, const float &leafSizeY, const float &leafSizeZ)
template int ExtractIndicesFilter< PointT > (const PointCloudT::ConstPtr inCloud, const pcl::PointIndices::ConstPtr inliers, PointCloudT::Ptr outcloud, PointCloudT::Ptr outcloud2)
template int ExtractIndicesFilter< PointRGB > (const PointCloudRGB::ConstPtr inCloud, const pcl::PointIndices::ConstPtr inliers, PointCloudRGB::Ptr outcloud, PointCloudRGB::Ptr outcloud2)
template int ExtractIndicesFilter< PointRGBA > (const PointCloudRGBA::ConstPtr inCloud, const pcl::PointIndices::ConstPtr inliers, PointCloudRGBA::Ptr outcloud, PointCloudRGBA::Ptr outcloud2)
template int GetMinCutSegmentation< PointT > (const PointCloudT::ConstPtr inCloud, std::vector< pcl::PointIndices > &outClusters, PointCloudRGB::Ptr cloud_segmented, const PointT foregroundPoint, int neighboursNumber, float smoothSigma, float backWeightRadius, float foreWeight, const pcl::IndicesConstPtr indices)
template int GetMinCutSegmentation< PointRGB > (const PointCloudRGB::ConstPtr inCloud, std::vector< pcl::PointIndices > &outClusters, PointCloudRGB::Ptr cloud_segmented, const PointRGB foregroundPoint, int neighboursNumber, float smoothSigma, float backWeightRadius, float foreWeight, const pcl::IndicesConstPtr indices)
template int GetBoundaryCloud< PointT, NormalT > (const PointCloudT::ConstPtr inCloud, const CloudNormal::ConstPtr normals, PointCloudT::Ptr boundaryCloud, const float angleThreshold, const float radius, const bool useKnn)
template int GetBoundaryCloud< PointT, PointNT > (const PointCloudT::ConstPtr inCloud, const PointCloudNormal::ConstPtr normals, PointCloudT::Ptr boundaryCloud, const float angleThreshold, const float radius, const bool useKnn)
template int GetBoundaryCloud< PointRGBA, NormalT > (const PointCloudRGBA::ConstPtr inCloud, const CloudNormal::ConstPtr normals, PointCloudRGBA::Ptr boundaryCloud, const float angleThreshold, const float radius, const bool useKnn)
template int GetBoundaryCloud< PointRGBA, PointNT > (const PointCloudRGBA::ConstPtr inCloud, const PointCloudNormal::ConstPtr normals, PointCloudRGBA::Ptr boundaryCloud, const float angleThreshold, const float radius, const bool useKnn)
template bool ICPRegistration< PointT, PointT > (const PointCloudT::ConstPtr targetCloud, const PointCloudT::ConstPtr sourceCloud, PointCloudT::Ptr outRegistered, int ipcMaxIterations, float icpCorrDistance)
template bool ICPRegistration< PointRGB, PointRGB > (const PointCloudRGB::ConstPtr targetCloud, const PointCloudRGB::ConstPtr sourceCloud, PointCloudRGB::Ptr outRegistered, int ipcMaxIterations, float icpCorrDistance)
template<typename PointInT >
int GetMarchingCubes (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, const MarchingMethod &marchingMethod, PCLMesh &outMesh, float epsilon=0.01f, float isoLevel=0.0f, float gridResolution=50, float percentageExtendGrid=0.0f)
template<typename PointInOutT >
int SwapAxis (const typename pcl::PointCloud< PointInOutT >::ConstPtr inCloud, typename pcl::PointCloud< PointInOutT >::Ptr outcloud, const std::string &flag)
template<typename PointInT >
int RemoveNaN (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, typename pcl::PointCloud< PointInT >::Ptr outcloud, std::vector< int > &index)
template<typename PointInT , typename PointOutT >
int EstimateSIFT (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, typename pcl::PointCloud< PointOutT >::Ptr outcloud, int nr_octaves=0, float min_scale=0, int nr_scales_per_octave=0, float min_contrast=0)
Extract SIFT keypoints.
template<typename PointInT , typename NormalType , typename DescriptorType = pcl::SHOT352>
int EstimateShot (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, const typename pcl::PointCloud< PointInT >::ConstPtr keyPoints, const typename pcl::PointCloud< NormalType >::ConstPtr normals, typename pcl::PointCloud< DescriptorType >::Ptr outDescriptors, float searchRadius=0.03f, int maxThreadCount=QThread::idealThreadCount())
template<typename PointInT >
double ComputeCloudResolution (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud)
template<typename PointOutT >
int RemoveOutliersStatistical (const typename PointOutT::ConstPtr inCloud, typename PointOutT::Ptr outCloud, int knn, double nSigma)
template<typename PointInT >
int EuclideanCluster (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, std::vector< pcl::PointIndices > &cluster_indices, float clusterTolerance=0.02f, int minClusterSize=100, int maxClusterSize=250000)
template<typename PointInT >
int ProgressiveMpFilter (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, pcl::PointIndicesPtr groundIndices, int maxWindowSize=20, float slope=1.0f, float initialDistance=0.5f, float maxDistance=3.0f)
template<typename PointInT , typename NormalType , typename PointOutT >
int DONEstimation (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, const typename pcl::PointCloud< NormalType >::ConstPtr normalsLargeScale, const typename pcl::PointCloud< NormalType >::ConstPtr normalsSmallScale, typename pcl::PointCloud< PointOutT >::Ptr outCloud)
template<typename PointInT , typename NormalType , typename RFType = pcl::ReferenceFrame>
int EstimateLocalReferenceFrame (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, const typename pcl::PointCloud< PointInT >::ConstPtr keyPoints, const typename pcl::PointCloud< NormalType >::ConstPtr normals, typename pcl::PointCloud< RFType >::Ptr outRF, float searchRadius=0.015f)
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame>
int EstimateHough3DGrouping (const typename pcl::PointCloud< PointModelT >::ConstPtr modelKeypoints, const typename pcl::PointCloud< PointSceneT >::ConstPtr sceneKeypoints, const typename pcl::PointCloud< PointModelRfT >::ConstPtr modelRF, const typename pcl::PointCloud< PointSceneRfT >::ConstPtr sceneRF, const typename pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> &rotoTranslations, std::vector< pcl::Correspondences > &clusteredCorrs, float houghBinSize=0.01f, float houghThreshold=5.0f)
template<typename PointModelT , typename PointSceneT >
int EstimateGeometricConsistencyGrouping (const typename pcl::PointCloud< PointModelT >::ConstPtr modelKeypoints, const typename pcl::PointCloud< PointSceneT >::ConstPtr sceneKeypoints, const typename pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> &rotoTranslations, std::vector< pcl::Correspondences > &clusteredCorrs, float gcSize=0.01f, float gcThreshold=20.0f)
template<typename PointInT >
int EstimateHarris3D (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, pcl::PointCloud< pcl::PointXYZI >::Ptr outcloud, float normalRadius=0.1f, float searchRadius=0.1f)
template<typename PointInOut >
int GetUniformSampling (const typename pcl::PointCloud< PointInOut >::ConstPtr inCloud, typename pcl::PointCloud< PointInOut >::Ptr outcloud, const float &searchRadius=-1.0f)
template<typename PointInOut >
int ConditionalRemovalFilter (const typename pcl::PointCloud< PointInOut >::ConstPtr inCloud, const ConditionParameters &params, typename pcl::PointCloud< PointInOut >::Ptr outCloud, bool keepOrganized=false)
template<typename PointInT , typename PointOutT >
int SmoothMls (const typename pcl::PointCloud< PointInT >::ConstPtr &inCloud, const MLSParameters &params, typename pcl::PointCloud< PointOutT >::Ptr &outcloud)
template<typename PointInT , typename PointOutT >
int ComputeNormals (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, typename pcl::PointCloud< PointOutT >::Ptr outcloud, const float radius=-1.0f, const bool useKnn=true, bool normalConsistency=false, int maxThreadCount=QThread::idealThreadCount())
template<typename PointInOut >
int PassThroughFilter (const typename pcl::PointCloud< PointInOut >::ConstPtr inCloud, typename pcl::PointCloud< PointInOut >::Ptr outcloud, const QString &filterFieldName="z", const float &limit_min=0.1f, const float &limit_max=1.1f)
template<typename PointInOut >
int VoxelGridFilter (const typename pcl::PointCloud< PointInOut >::ConstPtr inCloud, typename pcl::PointCloud< PointInOut >::Ptr outcloud, const float &leafSizeX=-0.01f, const float &leafSizeY=-0.01f, const float &leafSizeZ=-0.01f)
template<typename PointInOut >
int ExtractIndicesFilter (const typename pcl::PointCloud< PointInOut >::ConstPtr inCloud, const pcl::PointIndices::ConstPtr inliers, typename pcl::PointCloud< PointInOut >::Ptr outcloud=nullptr, typename pcl::PointCloud< PointInOut >::Ptr outcloud2=nullptr)
template<typename PointInT >
int GetConvexHullReconstruction (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, PCLMesh &outMesh, int dimension=3)
template<typename PointInT >
int GetConcaveHullReconstruction (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, PCLMesh &outMesh, int dimension=3, float alpha=0.05f)
template<typename PointInT >
int CropHullFilter (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, const PointCloudT::ConstPtr boundingBox, typename pcl::PointCloud< PointInT >::Ptr outCloud, int dimensions=2)
template<typename PointInT >
int GetMinCutSegmentation (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, std::vector< pcl::PointIndices > &outClusters, PointCloudRGB::Ptr cloud_segmented, const PointInT foregroundPoint, int neighboursNumber=14, float smoothSigma=0.25f, float backWeightRadius=0.8f, float foreWeight=0.5f, const pcl::IndicesConstPtr indices=nullptr)
template<typename PointInOut , typename NormalType >
int GetBoundaryCloud (const typename pcl::PointCloud< PointInOut >::ConstPtr inCloud, const typename pcl::PointCloud< NormalType >::ConstPtr normals, typename pcl::PointCloud< PointInOut >::Ptr boundaryCloud, const float angleThreshold=90.0f, const float radius=-1.0f, const bool useKnn=true)
template<typename PointInT , typename PointOutT >
bool ICPRegistration (const typename pcl::PointCloud< PointInT >::ConstPtr targetCloud, const typename pcl::PointCloud< PointOutT >::ConstPtr sourceCloud, typename pcl::PointCloud< PointOutT >::Ptr outRegistered, int ipcMaxIterations=5, float icpCorrDistance=0.005f)
Enumeration Type Documentation
MarchingMethod
enum PCLModules::MarchingMethod
Enumerator
HOPPE
RBF
Definition at line 216 of file PCLModules.h.
Function Documentation
ComputeCloudResolution()
template<typename PointInT > double PCLModules::ComputeCloudResolution (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud)
Definition at line 695 of file PCLModules.h.
References CVLog::WarningDebug(), and x.
ComputeNormals()
template<typename PointInT , typename PointOutT > int PCLModules::ComputeNormals (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, typename pcl::PointCloud< PointOutT >::Ptr outcloud, const float radius = -1.0f, const bool useKnn = true, bool normalConsistency = false, int maxThreadCount = QThread::idealThreadCount())
NOTE: setting viewpoint is very important, so that we can ensure normals are all pointed in the same direction!
Definition at line 1125 of file PCLModules.h.
ComputeNormals< PointRGB, NormalT >()
template int PCLModules::ComputeNormals< PointRGB, NormalT > (const PointCloudRGB::ConstPtr inCloud, CloudNormal::Ptr outcloud, const float radius, const bool useKnn, bool normalConsistency, int maxThreadCount)
ComputeNormals< PointRGB, PointNT >()
template int PCLModules::ComputeNormals< PointRGB, PointNT > (const PointCloudRGB::ConstPtr inCloud, PointCloudNormal::Ptr outcloud, const float radius, const bool useKnn, bool normalConsistency, int maxThreadCount)
ComputeNormals< PointRGBA, NormalT >()
template int PCLModules::ComputeNormals< PointRGBA, NormalT > (const PointCloudRGBA::ConstPtr inCloud, CloudNormal::Ptr outcloud, const float radius, const bool useKnn, bool normalConsistency, int maxThreadCount)
ComputeNormals< PointRGBA, PointNT >()
template int PCLModules::ComputeNormals< PointRGBA, PointNT > (const PointCloudRGBA::ConstPtr inCloud, PointCloudNormal::Ptr outcloud, const float radius, const bool useKnn, bool normalConsistency, int maxThreadCount)
ComputeNormals< PointT, NormalT >()
template int PCLModules::ComputeNormals< PointT, NormalT > (const PointCloudT::ConstPtr inCloud, CloudNormal::Ptr outcloud, const float radius, const bool useKnn, bool normalConsistency, int maxThreadCount)
Referenced by ProjectionFilter::compute(), MarchingCubeReconstruction::compute(), PCLModules::FeatureCloud::computeSurfaceNormals(), GetRegionGrowing(), and GetSACSegmentation().
ComputeNormals< PointT, PointNT >()
template int PCLModules::ComputeNormals< PointT, PointNT > (const PointCloudT::ConstPtr inCloud, PointCloudNormal::Ptr outcloud, const float radius, const bool useKnn, bool normalConsistency, int maxThreadCount)
Referenced by DONSegmentation::compute().
ConditionalRemovalFilter()
template<typename PointInOut > int PCLModules::ConditionalRemovalFilter (const typename pcl::PointCloud< PointInOut >::ConstPtr inCloud, const ConditionParameters & params, typename pcl::PointCloud< PointInOut >::Ptr outCloud, bool keepOrganized = false)
Definition at line 955 of file PCLModules.h.
References PCLModules::ConditionParameters::ComparisonParam::comparison_type_, PCLModules::ConditionParameters::condition_params_, PCLModules::ConditionParameters::condition_type_, PCLModules::ConditionParameters::ComparisonParam::fieldName_, PCLModules::ConditionParameters::ComparisonParam::max_threshold_, and PCLModules::ConditionParameters::ComparisonParam::min_threshold_.
ConditionalRemovalFilter< PointNT >()
template int PCLModules::ConditionalRemovalFilter< PointNT > (const PointCloudNormal::ConstPtr inCloud, const ConditionParameters & params, PointCloudNormal::Ptr outCloud, bool keepOrganized)
Referenced by DONSegmentation::compute().
CropHullFilter()
template<typename PointInT > int PCLModules::CropHullFilter (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, const PointCloudT::ConstPtr boundingBox, typename pcl::PointCloud< PointInT >::Ptr outCloud, int dimensions = 2)
Definition at line 1296 of file PCLModules.h.
References FROM_PCL_CLOUD, and GetConvexHullReconstruction< PointT >().
CropHullFilter< PointRGB >()
template int PCLModules::CropHullFilter< PointRGB > (const PointCloudRGB::ConstPtr inCloud, const PointCloudT::ConstPtr boundingBox, PointCloudRGB::Ptr outCloud, int dimensions)
Referenced by GeneralFilters::compute().
CropHullFilter< PointT >()
template int PCLModules::CropHullFilter< PointT > (const PointCloudT::ConstPtr inCloud, const PointCloudT::ConstPtr boundingBox, PointCloudT::Ptr outCloud, int dimensions)
Referenced by GeneralFilters::compute().
DONEstimation()
template<typename PointInT , typename NormalType , typename PointOutT > int PCLModules::DONEstimation (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, const typename pcl::PointCloud< NormalType >::ConstPtr normalsLargeScale, const typename pcl::PointCloud< NormalType >::ConstPtr normalsSmallScale, typename pcl::PointCloud< PointOutT >::Ptr outCloud)
Definition at line 804 of file PCLModules.h.
DONEstimation< PointRGB, PointNT, PointNT >()
template int PCLModules::DONEstimation< PointRGB, PointNT, PointNT > (const PointCloudRGB::ConstPtr inCloud, const PointCloudNormal::ConstPtr normalsLargeScale, const PointCloudNormal::ConstPtr normalsSmallScale, PointCloudNormal::Ptr outCloud)
DONEstimation< PointT, PointNT, PointNT >()
template int PCLModules::DONEstimation< PointT, PointNT, PointNT > (const PointCloudT::ConstPtr inCloud, const PointCloudNormal::ConstPtr normalsLargeScale, const PointCloudNormal::ConstPtr normalsSmallScale, PointCloudNormal::Ptr outCloud)
Referenced by DONSegmentation::compute().
EstimateGeometricConsistencyGrouping()
template<typename PointModelT , typename PointSceneT > int PCLModules::EstimateGeometricConsistencyGrouping (const typename pcl::PointCloud< PointModelT >::ConstPtr modelKeypoints, const typename pcl::PointCloud< PointSceneT >::ConstPtr sceneKeypoints, const typename pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> & rotoTranslations, std::vector< pcl::Correspondences > & clusteredCorrs, float gcSize = 0.01f, float gcThreshold = 20.0f)
Definition at line 878 of file PCLModules.h.
Referenced by CorrespondenceMatching::compute().
EstimateGeometricConsistencyGrouping< PointRGB, PointRGB >()
template int PCLModules::EstimateGeometricConsistencyGrouping< PointRGB, PointRGB > (const PointCloudRGB::ConstPtr modelKeypoints, const PointCloudRGB::ConstPtr sceneKeypoints, const pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> & rotoTranslations, std::vector< pcl::Correspondences > & clusteredCorrs, float gcSize, float gcThreshold)
EstimateGeometricConsistencyGrouping< PointRGBA, PointRGBA >()
template int PCLModules::EstimateGeometricConsistencyGrouping< PointRGBA, PointRGBA > (const PointCloudRGBA::ConstPtr modelKeypoints, const PointCloudRGBA::ConstPtr sceneKeypoints, const pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> & rotoTranslations, std::vector< pcl::Correspondences > & clusteredCorrs, float gcSize, float gcThreshold)
EstimateGeometricConsistencyGrouping< PointT, PointT >()
template int PCLModules::EstimateGeometricConsistencyGrouping< PointT, PointT > (const PointCloudT::ConstPtr modelKeypoints, const PointCloudT::ConstPtr sceneKeypoints, const pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> & rotoTranslations, std::vector< pcl::Correspondences > & clusteredCorrs, float gcSize, float gcThreshold)
EstimateHarris3D()
template<typename PointInT > int PCLModules::EstimateHarris3D (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, pcl::PointCloud< pcl::PointXYZI >::Ptr outcloud, float normalRadius = 0.1f, float searchRadius = 0.1f)
Definition at line 901 of file PCLModules.h.
EstimateHarris3D< PointRGB >()
template int PCLModules::EstimateHarris3D< PointRGB > (const PointCloudRGB::ConstPtr inCloud, pcl::PointCloud< pcl::PointXYZI >::Ptr outcloud, float normalRadius, float searchRadius)
EstimateHarris3D< PointRGBA >()
template int PCLModules::EstimateHarris3D< PointRGBA > (const PointCloudRGBA::ConstPtr inCloud, pcl::PointCloud< pcl::PointXYZI >::Ptr outcloud, float normalRadius, float searchRadius)
EstimateHarris3D< PointT >()
template int PCLModules::EstimateHarris3D< PointT > (const PointCloudT::ConstPtr inCloud, pcl::PointCloud< pcl::PointXYZI >::Ptr outcloud, float normalRadius, float searchRadius)
EstimateHough3DGrouping()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> int PCLModules::EstimateHough3DGrouping (const typename pcl::PointCloud< PointModelT >::ConstPtr modelKeypoints, const typename pcl::PointCloud< PointSceneT >::ConstPtr sceneKeypoints, const typename pcl::PointCloud< PointModelRfT >::ConstPtr modelRF, const typename pcl::PointCloud< PointSceneRfT >::ConstPtr sceneRF, const typename pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> & rotoTranslations, std::vector< pcl::Correspondences > & clusteredCorrs, float houghBinSize = 0.01f, float houghThreshold = 5.0f)
Definition at line 848 of file PCLModules.h.
Referenced by CorrespondenceMatching::compute().
EstimateHough3DGrouping< PointRGB, PointRGB, pcl::ReferenceFrame, pcl::ReferenceFrame >()
template int PCLModules::EstimateHough3DGrouping< PointRGB, PointRGB, pcl::ReferenceFrame, pcl::ReferenceFrame > (const PointCloudRGB::ConstPtr modelKeypoints, const PointCloudRGB::ConstPtr sceneKeypoints, const pcl::PointCloud< pcl::ReferenceFrame >::ConstPtr modelRF, const pcl::PointCloud< pcl::ReferenceFrame >::ConstPtr sceneRF, const pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> & rotoTranslations, std::vector< pcl::Correspondences > & clusteredCorrs, float houghBinSize, float houghThreshold)
EstimateHough3DGrouping< PointRGBA, PointRGBA, pcl::ReferenceFrame, pcl::ReferenceFrame >()
template int PCLModules::EstimateHough3DGrouping< PointRGBA, PointRGBA, pcl::ReferenceFrame, pcl::ReferenceFrame > (const PointCloudRGBA::ConstPtr modelKeypoints, const PointCloudRGBA::ConstPtr sceneKeypoints, const pcl::PointCloud< pcl::ReferenceFrame >::ConstPtr modelRF, const pcl::PointCloud< pcl::ReferenceFrame >::ConstPtr sceneRF, const pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> & rotoTranslations, std::vector< pcl::Correspondences > & clusteredCorrs, float houghBinSize, float houghThreshold)
EstimateHough3DGrouping< PointT, PointT, pcl::ReferenceFrame, pcl::ReferenceFrame >()
template int PCLModules::EstimateHough3DGrouping< PointT, PointT, pcl::ReferenceFrame, pcl::ReferenceFrame > (const PointCloudT::ConstPtr modelKeypoints, const PointCloudT::ConstPtr sceneKeypoints, const pcl::PointCloud< pcl::ReferenceFrame >::ConstPtr modelRF, const pcl::PointCloud< pcl::ReferenceFrame >::ConstPtr sceneRF, const pcl::CorrespondencesConstPtr modelSceneCorrs, std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f >> & rotoTranslations, std::vector< pcl::Correspondences > & clusteredCorrs, float houghBinSize, float houghThreshold)
EstimateLocalReferenceFrame()
template<typename PointInT , typename NormalType , typename RFType = pcl::ReferenceFrame> int PCLModules::EstimateLocalReferenceFrame (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, const typename pcl::PointCloud< PointInT >::ConstPtr keyPoints, const typename pcl::PointCloud< NormalType >::ConstPtr normals, typename pcl::PointCloud< RFType >::Ptr outRF, float searchRadius = 0.015f)
Definition at line 827 of file PCLModules.h.
References normals.
Referenced by CorrespondenceMatching::compute().
EstimateLocalReferenceFrame< PointRGB, NormalT, pcl::ReferenceFrame >()
template int PCLModules::EstimateLocalReferenceFrame< PointRGB, NormalT, pcl::ReferenceFrame > (const PointCloudRGB::ConstPtr inCloud, const PointCloudRGB::ConstPtr keyPoints, const CloudNormal::ConstPtr normals, pcl::PointCloud< pcl::ReferenceFrame >::Ptr outRF, float searchRadius)
EstimateLocalReferenceFrame< PointRGBA, NormalT, pcl::ReferenceFrame >()
template int PCLModules::EstimateLocalReferenceFrame< PointRGBA, NormalT, pcl::ReferenceFrame > (const PointCloudRGBA::ConstPtr inCloud, const PointCloudRGBA::ConstPtr keyPoints, const CloudNormal::ConstPtr normals, pcl::PointCloud< pcl::ReferenceFrame >::Ptr outRF, float searchRadius)
EstimateLocalReferenceFrame< PointT, NormalT, pcl::ReferenceFrame >()
template int PCLModules::EstimateLocalReferenceFrame< PointT, NormalT, pcl::ReferenceFrame > (const PointCloudT::ConstPtr inCloud, const PointCloudT::ConstPtr keyPoints, const CloudNormal::ConstPtr normals, pcl::PointCloud< pcl::ReferenceFrame >::Ptr outRF, float searchRadius)
EstimateShot()
template<typename PointInT , typename NormalType , typename DescriptorType = pcl::SHOT352> int PCLModules::EstimateShot (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, const typename pcl::PointCloud< PointInT >::ConstPtr keyPoints, const typename pcl::PointCloud< NormalType >::ConstPtr normals, typename pcl::PointCloud< DescriptorType >::Ptr outDescriptors, float searchRadius = 0.03f, int maxThreadCount = QThread::idealThreadCount())
Definition at line 677 of file PCLModules.h.
References normals.
EstimateShot< PointRGB, NormalT, pcl::SHOT352 >()
template int PCLModules::EstimateShot< PointRGB, NormalT, pcl::SHOT352 > (const PointCloudRGB::ConstPtr inCloud, const PointCloudRGB::ConstPtr keyPoints, const CloudNormal::ConstPtr normals, pcl::PointCloud< pcl::SHOT352 >::Ptr outDescriptors, float searchRadius, int maxThreadCount)
EstimateShot< PointRGBA, NormalT, pcl::SHOT352 >()
template int PCLModules::EstimateShot< PointRGBA, NormalT, pcl::SHOT352 > (const PointCloudRGBA::ConstPtr inCloud, const PointCloudRGBA::ConstPtr keyPoints, const CloudNormal::ConstPtr normals, pcl::PointCloud< pcl::SHOT352 >::Ptr outDescriptors, float searchRadius, int maxThreadCount)
EstimateShot< PointT, NormalT, pcl::SHOT352 >()
template int PCLModules::EstimateShot< PointT, NormalT, pcl::SHOT352 > (const PointCloudT::ConstPtr inCloud, const PointCloudT::ConstPtr keyPoints, const CloudNormal::ConstPtr normals, pcl::PointCloud< pcl::SHOT352 >::Ptr outDescriptors, float searchRadius, int maxThreadCount)
EstimateSIFT()
template<typename PointInT , typename PointOutT > int PCLModules::EstimateSIFT (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, typename pcl::PointCloud< PointOutT >::Ptr outcloud, int nr_octaves = 0, float min_scale = 0, int nr_scales_per_octave = 0, float min_contrast = 0)
Extract SIFT keypoints.
if only the point cloud is given PCL default parameters are used (that are not really good, so please give parameters)
Note
Different types can be passed as input for this function:
PointXYZI
PointNormal
PointXYZRGB
If a PointType with a scale field is passed as output type, scales will be returned together with the return cloud
Definition at line 651 of file PCLModules.h.
EstimateSIFT< pcl::PointXYZI, PointT >()
template int PCLModules::EstimateSIFT< pcl::PointXYZI, PointT > (const pcl::PointCloud< pcl::PointXYZI >::ConstPtr inCloud, PointCloudT::Ptr outcloud, int nr_octaves, float min_scale, int nr_scales_per_octave, float min_contrast)
EstimateSIFT< PointRGB, PointT >()
template int PCLModules::EstimateSIFT< PointRGB, PointT > (const PointCloudRGB::ConstPtr inCloud, PointCloudT::Ptr outcloud, int nr_octaves, float min_scale, int nr_scales_per_octave, float min_contrast)
EstimateSIFT< PointRGBA, PointT >()
template int PCLModules::EstimateSIFT< PointRGBA, PointT > (const PointCloudRGBA::ConstPtr inCloud, PointCloudT::Ptr outcloud, int nr_octaves, float min_scale, int nr_scales_per_octave, float min_contrast)
EuclideanCluster()
template<typename PointInT > int PCLModules::EuclideanCluster (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, std::vector< pcl::PointIndices > & cluster_indices, float clusterTolerance = 0.02f, int minClusterSize = 100, int maxClusterSize = 250000)
Definition at line 762 of file PCLModules.h.
EuclideanCluster< PointNT >()
template int PCLModules::EuclideanCluster< PointNT > (const PointCloudNormal::ConstPtr inCloud, std::vector< pcl::PointIndices > & cluster_indices, float clusterTolerance, int minClusterSize, int maxClusterSize)
Referenced by DONSegmentation::compute().
EuclideanCluster< PointT >()
template int PCLModules::EuclideanCluster< PointT > (const PointCloudT::ConstPtr inCloud, std::vector< pcl::PointIndices > & cluster_indices, float clusterTolerance, int minClusterSize, int maxClusterSize)
Referenced by EuclideanClusterSegmentation::compute().
ExtractIndicesFilter()
template<typename PointInOut > int PCLModules::ExtractIndicesFilter (const typename pcl::PointCloud< PointInOut >::ConstPtr inCloud, const pcl::PointIndices::ConstPtr inliers, typename pcl::PointCloud< PointInOut >::Ptr outcloud = nullptr, typename pcl::PointCloud< PointInOut >::Ptr outcloud2 = nullptr)
Definition at line 1229 of file PCLModules.h.
ExtractIndicesFilter< PointRGB >()
template int PCLModules::ExtractIndicesFilter< PointRGB > (const PointCloudRGB::ConstPtr inCloud, const pcl::PointIndices::ConstPtr inliers, PointCloudRGB::Ptr outcloud, PointCloudRGB::Ptr outcloud2)
Referenced by GeneralFilters::compute().
ExtractIndicesFilter< PointRGBA >()
template int PCLModules::ExtractIndicesFilter< PointRGBA > (const PointCloudRGBA::ConstPtr inCloud, const pcl::PointIndices::ConstPtr inliers, PointCloudRGBA::Ptr outcloud, PointCloudRGBA::Ptr outcloud2)
ExtractIndicesFilter< PointT >()
template int PCLModules::ExtractIndicesFilter< PointT > (const PointCloudT::ConstPtr inCloud, const pcl::PointIndices::ConstPtr inliers, PointCloudT::Ptr outcloud, PointCloudT::Ptr outcloud2)
Referenced by GeneralFilters::compute(), and extractRecursive().
GetBoundaryCloud()
template<typename PointInOut , typename NormalType > int PCLModules::GetBoundaryCloud (const typename pcl::PointCloud< PointInOut >::ConstPtr inCloud, const typename pcl::PointCloud< NormalType >::ConstPtr normals, typename pcl::PointCloud< PointInOut >::Ptr boundaryCloud, const float angleThreshold = 90.0f, const float radius = -1.0f, const bool useKnn = true)
Definition at line 1355 of file PCLModules.h.
References cloudViewer::DegreesToRadians(), and normals.
GetBoundaryCloud< PointRGBA, NormalT >()
template int PCLModules::GetBoundaryCloud< PointRGBA, NormalT > (const PointCloudRGBA::ConstPtr inCloud, const CloudNormal::ConstPtr normals, PointCloudRGBA::Ptr boundaryCloud, const float angleThreshold, const float radius, const bool useKnn)
GetBoundaryCloud< PointRGBA, PointNT >()
template int PCLModules::GetBoundaryCloud< PointRGBA, PointNT > (const PointCloudRGBA::ConstPtr inCloud, const PointCloudNormal::ConstPtr normals, PointCloudRGBA::Ptr boundaryCloud, const float angleThreshold, const float radius, const bool useKnn)
GetBoundaryCloud< PointT, NormalT >()
template int PCLModules::GetBoundaryCloud< PointT, NormalT > (const PointCloudT::ConstPtr inCloud, const CloudNormal::ConstPtr normals, PointCloudT::Ptr boundaryCloud, const float angleThreshold, const float radius, const bool useKnn)
Referenced by ProjectionFilter::compute().
GetBoundaryCloud< PointT, PointNT >()
template int PCLModules::GetBoundaryCloud< PointT, PointNT > (const PointCloudT::ConstPtr inCloud, const PointCloudNormal::ConstPtr normals, PointCloudT::Ptr boundaryCloud, const float angleThreshold, const float radius, const bool useKnn)
GetConcaveHullReconstruction()
template<typename PointInT > int PCLModules::GetConcaveHullReconstruction (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, PCLMesh & outMesh, int dimension = 3, float alpha = 0.05f)
Definition at line 1276 of file PCLModules.h.
References TO_PCL_CLOUD.
GetConcaveHullReconstruction< PointRGB >()
template int PCLModules::GetConcaveHullReconstruction< PointRGB > (const PointCloudRGB::ConstPtr inCloud, PCLMesh & outMesh, int dimension, float alpha)
GetConcaveHullReconstruction< PointT >()
template int PCLModules::GetConcaveHullReconstruction< PointT > (const PointCloudT::ConstPtr inCloud, PCLMesh & outMesh, int dimension, float alpha)
Referenced by ConvexConcaveHullReconstruction::compute().
GetConvexHullReconstruction()
template<typename PointInT > int PCLModules::GetConvexHullReconstruction (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, PCLMesh & outMesh, int dimension = 3)
Definition at line 1252 of file PCLModules.h.
References CVLog::Print(), and TO_PCL_CLOUD.
GetConvexHullReconstruction< PointRGB >()
template int PCLModules::GetConvexHullReconstruction< PointRGB > (const PointCloudRGB::ConstPtr inCloud, PCLMesh & outMesh, int dimension)
GetConvexHullReconstruction< PointT >()
template int PCLModules::GetConvexHullReconstruction< PointT > (const PointCloudT::ConstPtr inCloud, PCLMesh & outMesh, int dimension)
Referenced by ConvexConcaveHullReconstruction::compute(), and CropHullFilter().
GetGreedyTriangulation()
int QPCL_ENGINE_LIB_API PCLModules::GetGreedyTriangulation (const PointCloudNormal::ConstPtr & cloudWithNormals, PCLMesh & outMesh, int trigulationSearchRadius, float weightingFactor, int maxNearestNeighbors, int maxSurfaceAngle, int minAngle, int maxAngle, bool normalConsistency)
Definition at line 270 of file PCLModules.cpp.
References cloudViewer::DegreesToRadians().
Referenced by GreedyTriangulation::compute().
GetMarchingCubes()
template<typename PointInT > int PCLModules::GetMarchingCubes (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, const MarchingMethod & marchingMethod, PCLMesh & outMesh, float epsilon = 0.01f, float isoLevel = 0.0f, float gridResolution = 50, float percentageExtendGrid = 0.0f)
Definition at line 218 of file PCLModules.h.
References HOPPE, and RBF.
GetMarchingCubes< PointNT >()
template int PCLModules::GetMarchingCubes< PointNT > (const PointCloudNormal::ConstPtr inCloud, const MarchingMethod & marchingMethod, PCLMesh & outMesh, float epsilon, float isoLevel, float gridResolution, float percentageExtendGrid)
Referenced by MarchingCubeReconstruction::compute().
GetMinCutSegmentation()
template<typename PointInT > int PCLModules::GetMinCutSegmentation (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, std::vector< pcl::PointIndices > & outClusters, PointCloudRGB::Ptr cloud_segmented, const PointInT foregroundPoint, int neighboursNumber = 14, float smoothSigma = 0.25f, float backWeightRadius = 0.8f, float foreWeight = 0.5f, const pcl::IndicesConstPtr indices = nullptr)
Definition at line 1323 of file PCLModules.h.
GetMinCutSegmentation< PointRGB >()
template int PCLModules::GetMinCutSegmentation< PointRGB > (const PointCloudRGB::ConstPtr inCloud, std::vector< pcl::PointIndices > & outClusters, PointCloudRGB::Ptr cloud_segmented, const PointRGB foregroundPoint, int neighboursNumber, float smoothSigma, float backWeightRadius, float foreWeight, const pcl::IndicesConstPtr indices)
Referenced by MinimumCutSegmentation::compute().
GetMinCutSegmentation< PointT >()
template int PCLModules::GetMinCutSegmentation< PointT > (const PointCloudT::ConstPtr inCloud, std::vector< pcl::PointIndices > & outClusters, PointCloudRGB::Ptr cloud_segmented, const PointT foregroundPoint, int neighboursNumber, float smoothSigma, float backWeightRadius, float foreWeight, const pcl::IndicesConstPtr indices)
Referenced by MinimumCutSegmentation::compute().
GetPoissonReconstruction()
int QPCL_ENGINE_LIB_API PCLModules::GetPoissonReconstruction (const PointCloudNormal::ConstPtr & cloudWithNormals, PCLMesh & outMesh, int degree, int treeDepth, int isoDivideDepth, int solverDivideDepth, float scale, float samplesPerNode, bool useConfidence, bool useManifold, bool outputPolygons)
Definition at line 237 of file PCLModules.cpp.
Referenced by PoissonReconstruction::compute().
GetProjection() [1/2]
int QPCL_ENGINE_LIB_API PCLModules::GetProjection (const PointCloudT::ConstPtr & originCloud, PointCloudT::Ptr & projectedCloud, const pcl::ModelCoefficients::ConstPtr coefficients, const int & modelType)
Definition at line 298 of file PCLModules.cpp.
Referenced by ProjectionFilter::compute(), and GetProjection().
GetProjection() [2/2]
int QPCL_ENGINE_LIB_API PCLModules::GetProjection (const PointCloudT::ConstPtr & originCloud, PointCloudT::Ptr & projectedCloud, float coefficientA, float coefficientB, float coefficientC, float coefficientD, const int & modelType)
Definition at line 316 of file PCLModules.cpp.
References GetProjection().
GetRegionGrowing()
int QPCL_ENGINE_LIB_API PCLModules::GetRegionGrowing (const PointCloudT::ConstPtr cloud, std::vector< pcl::PointIndices > & clusters, PointCloudRGB::Ptr cloud_segmented, int k, int min_cluster_size, int max_cluster_size, unsigned int neighbour_number, float smoothness_theta, float curvature)
Basic Region Growing.
SEGMENTATION
Parameters
cloud
k
min_cluster_size
max_cluster_size
neighbour_number
smoothness_theta
curvature
Returns
Definition at line 46 of file PCLModules.cpp.
References ComputeNormals< PointT, NormalT >(), normals, and CVLog::Print().
Referenced by RegionGrowingSegmentation::compute().
GetRegionGrowingRGB()
int QPCL_ENGINE_LIB_API PCLModules::GetRegionGrowingRGB (const PointCloudRGB::ConstPtr cloud, std::vector< pcl::PointIndices > & clusters, PointCloudRGB::Ptr cloud_segmented, int min_cluster_size, float neighbors_distance, float point_color_diff, float region_color_diff)
Color based Region Growing.
Parameters
cloud
min_cluster_size
neighbors_distance
point_color_diff
region_color_diff
Returns
Definition at line 98 of file PCLModules.cpp.
References CVLog::Print().
Referenced by RegionGrowingSegmentation::compute().
GetSACSegmentation()
int QPCL_ENGINE_LIB_API PCLModules::GetSACSegmentation (const PointCloudT::ConstPtr cloud, pcl::PointIndices::Ptr inliers, pcl::ModelCoefficients::Ptr coefficients, const int & methodType, const int & modelType, float distanceThreshold, float probability, int maxIterations, float minRadiusLimits, float maxRadiusLimits, float normalDisWeight)
Definition at line 142 of file PCLModules.cpp.
References ComputeNormals< PointT, NormalT >().
Referenced by extractRecursive().
GetUniformSampling()
template<typename PointInOut > int PCLModules::GetUniformSampling (const typename pcl::PointCloud< PointInOut >::ConstPtr inCloud, typename pcl::PointCloud< PointInOut >::Ptr outcloud, const float & searchRadius = -1.0f)
Definition at line 916 of file PCLModules.h.
GetUniformSampling< PointRGB >()
template int PCLModules::GetUniformSampling< PointRGB > (const PointCloudRGB::ConstPtr inCloud, PointCloudRGB::Ptr outcloud, const float & searchRadius)
GetUniformSampling< PointRGBA >()
template int PCLModules::GetUniformSampling< PointRGBA > (const PointCloudRGBA::ConstPtr inCloud, PointCloudRGBA::Ptr outcloud, const float & searchRadius)
GetUniformSampling< PointT >()
template int PCLModules::GetUniformSampling< PointT > (const PointCloudT::ConstPtr inCloud, PointCloudT::Ptr outcloud, const float & searchRadius)
GridProjection()
int QPCL_ENGINE_LIB_API PCLModules::GridProjection (const PointCloudNormal::ConstPtr & cloudWithNormals, PCLMesh & outMesh, float resolution, int paddingSize, int maxSearchLevel)
SURFACE
Definition at line 217 of file PCLModules.cpp.
ICPRegistration()
template<typename PointInT , typename PointOutT > bool PCLModules::ICPRegistration (const typename pcl::PointCloud< PointInT >::ConstPtr targetCloud, const typename pcl::PointCloud< PointOutT >::ConstPtr sourceCloud, typename pcl::PointCloud< PointOutT >::Ptr outRegistered, int ipcMaxIterations = 5, float icpCorrDistance = 0.005f)
Definition at line 1400 of file PCLModules.h.
References sourceCloud.
ICPRegistration< PointRGB, PointRGB >()
template bool PCLModules::ICPRegistration< PointRGB, PointRGB > (const PointCloudRGB::ConstPtr targetCloud, const PointCloudRGB::ConstPtr sourceCloud, PointCloudRGB::Ptr outRegistered, int ipcMaxIterations, float icpCorrDistance)
ICPRegistration< PointT, PointT >()
template bool PCLModules::ICPRegistration< PointT, PointT > (const PointCloudT::ConstPtr targetCloud, const PointCloudT::ConstPtr sourceCloud, PointCloudT::Ptr outRegistered, int ipcMaxIterations, float icpCorrDistance)
PassThroughFilter()
template<typename PointInOut > int PCLModules::PassThroughFilter (const typename pcl::PointCloud< PointInOut >::ConstPtr inCloud, typename pcl::PointCloud< PointInOut >::Ptr outcloud, const QString & filterFieldName = "z", const float & limit_min = 0.1f, const float & limit_max = 1.1f)
Definition at line 1179 of file PCLModules.h.
PassThroughFilter< PointRGB >()
template int PCLModules::PassThroughFilter< PointRGB > (const PointCloudRGB::ConstPtr inCloud, PointCloudRGB::Ptr outcloud, const QString & filterFieldName, const float & limit_min, const float & limit_max)
Referenced by GeneralFilters::compute().
PassThroughFilter< PointRGBA >()
template int PCLModules::PassThroughFilter< PointRGBA > (const PointCloudRGBA::ConstPtr inCloud, PointCloudRGBA::Ptr outcloud, const QString & filterFieldName, const float & limit_min, const float & limit_max)
PassThroughFilter< PointT >()
template int PCLModules::PassThroughFilter< PointT > (const PointCloudT::ConstPtr inCloud, PointCloudT::Ptr outcloud, const QString & filterFieldName, const float & limit_min, const float & limit_max)
Referenced by GeneralFilters::compute().
ProgressiveMpFilter()
template<typename PointInT > int PCLModules::ProgressiveMpFilter (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, pcl::PointIndicesPtr groundIndices, int maxWindowSize = 20, float slope = 1.0f, float initialDistance = 0.5f, float maxDistance = 3.0f)
Definition at line 784 of file PCLModules.h.
ProgressiveMpFilter< PointRGB >()
template int PCLModules::ProgressiveMpFilter< PointRGB > (const PointCloudRGB::ConstPtr inCloud, pcl::PointIndicesPtr groundIndices, int maxWindowSize, float slope, float initialDistance, float maxDistance)
Referenced by GeneralFilters::compute().
ProgressiveMpFilter< PointT >()
template int PCLModules::ProgressiveMpFilter< PointT > (const PointCloudT::ConstPtr inCloud, pcl::PointIndicesPtr groundIndices, int maxWindowSize, float slope, float initialDistance, float maxDistance)
Referenced by GeneralFilters::compute().
RemoveNaN()
template<typename PointInT > int PCLModules::RemoveNaN (const typename pcl::PointCloud< PointInT >::ConstPtr inCloud, typename pcl::PointCloud< PointInT >::Ptr outcloud, std::vector< int > & index)
Definition at line 297 of file PCLModules.h.
RemoveOutliersStatistical()
template<typename PointOutT > int PCLModules::RemoveOutliersStatistical (const typename PointOutT::ConstPtr inCloud, typename PointOutT::Ptr outCloud, int knn, double nSigma)
Definition at line 749 of file PCLModules.h.
RemoveOutliersStatistical< PCLCloud >()
template int PCLModules::RemoveOutliersStatistical< PCLCloud > (const PCLCloud::ConstPtr inCloud, PCLCloud::Ptr outCloud, int knn, double nSigma)
Referenced by StatisticalOutliersRemover::compute().
SmoothMls()
template<typename PointInT , typename PointOutT > int PCLModules::SmoothMls (const typename pcl::PointCloud< PointInT >::ConstPtr & inCloud, const MLSParameters & params, typename pcl::PointCloud< PointOutT >::Ptr & outcloud)
Definition at line 1052 of file PCLModules.h.
References PCLModules::MLSParameters::compute_normals_, PCLModules::MLSParameters::dilation_iterations_, PCLModules::MLSParameters::dilation_voxel_size_, cloudViewer::utility::EstimateMaxThreads(), PCLModules::MLSParameters::NONE, PCLModules::MLSParameters::order_, PCLModules::MLSParameters::polynomial_fit_, PCLModules::MLSParameters::RANDOM_UNIFORM_DENSITY, PCLModules::MLSParameters::SAMPLE_LOCAL_PLANE, PCLModules::MLSParameters::search_radius_, PCLModules::MLSParameters::sqr_gauss_param_, PCLModules::MLSParameters::step_point_density_, PCLModules::MLSParameters::upsample_method_, PCLModules::MLSParameters::upsampling_radius_, PCLModules::MLSParameters::upsampling_step_, and PCLModules::MLSParameters::VOXEL_GRID_DILATION.
SmoothMls< PointT, PointNT >()
template int PCLModules::SmoothMls< PointT, PointNT > (const PointCloudT::ConstPtr & inCloud, const MLSParameters & params, PointCloudNormal::Ptr & outcloud)
SwapAxis()
template<typename PointInOutT > int PCLModules::SwapAxis (const typename pcl::PointCloud< PointInOutT >::ConstPtr inCloud, typename pcl::PointCloud< PointInOutT >::Ptr outcloud, const std::string & flag)
Definition at line 263 of file PCLModules.h.
References x, y, and z.
VoxelGridFilter()
template<typename PointInOut > int PCLModules::VoxelGridFilter (const typename pcl::PointCloud< PointInOut >::ConstPtr inCloud, typename pcl::PointCloud< PointInOut >::Ptr outcloud, const float & leafSizeX = -0.01f, const float & leafSizeY = -0.01f, const float & leafSizeZ = -0.01f)
Definition at line 1194 of file PCLModules.h.
References CVLog::Print(), and CVLog::Warning().
VoxelGridFilter< PointRGB >()
template int PCLModules::VoxelGridFilter< PointRGB > (const PointCloudRGB::ConstPtr inCloud, PointCloudRGB::Ptr outcloud, const float & leafSizeX, const float & leafSizeY, const float & leafSizeZ)
Referenced by GeneralFilters::compute().
VoxelGridFilter< PointRGBA >()
template int PCLModules::VoxelGridFilter< PointRGBA > (const PointCloudRGBA::ConstPtr inCloud, PointCloudRGBA::Ptr outcloud, const float & leafSizeX, const float & leafSizeY, const float & leafSizeZ)
VoxelGridFilter< PointT >()
template int PCLModules::VoxelGridFilter< PointT > (const PointCloudT::ConstPtr inCloud, PointCloudT::Ptr outcloud, const float & leafSizeX, const float & leafSizeY, const float & leafSizeZ)
Referenced by GeneralFilters::compute(), ProjectionFilter::compute(), TemplateAlignment::compute(), SACSegmentation::compute(), NurbsCurveFitting::compute(), and NurbsSurfaceReconstruction::compute().