ACloudViewer: ecvTools Namespace Reference
ecvTools Namespace Reference
Functions
static std::vector< int > IntersectionVector (std::vector< int > &a, std::vector< int > &b)
static std::vector< int > UnionVector (std::vector< int > &a, std::vector< int > &b)
static std::vector< int > DiffVector (std::vector< int > a, std::vector< int > b)
static ecvColor::Rgbf TransFormRGB (const ecvColor::Rgb &col)
static ecvColor::Rgbf TransFormRGB (const ecvColor::Rgbf &col)
static ccPolyline * GetPolylines (PCLCloud::Ptr &curve_sm, const QString &name="curve", bool closed=true, const ecvColor::Rgb &color=ecvColor::green)
static void AddPointCloud (ccHObject *ecvGroup, PCLCloud::Ptr sm_cloud, bool &error, QString label, const ccPointCloud *ccCloud=nullptr, bool randomColors=true)
static ccHObject * GetClousterGroup (const ccPointCloud *ccCloud, const PointCloudT::ConstPtr xyzCloud, const std::vector< pcl::PointIndices > &cluster_indices, unsigned minPointsPerComponent, bool randomColors, bool &error)
static ccHObject * GetClousterGroup (const ccPointCloud *ccCloud, const std::vector< std::vector< size_t >> &cluster_indices, unsigned minPointsPerComponent, bool randomColors, bool &error)
static ccHObject * GetSegmentationGroup (const ccPointCloud *ccCloud, const PointCloudT::ConstPtr cloudRemained, const std::vector< PointCloudT::Ptr > &cloudExtractions, bool randomColors, bool &error)
Function Documentation
AddPointCloud()
static void ecvTools::AddPointCloud (ccHObject * ecvGroup, PCLCloud::Ptr sm_cloud, bool & error, QString label, const ccPointCloud * ccCloud = nullptr, bool randomColors = true) static
Definition at line 112 of file ecvTools.h.
References ccHObject::addChild(), pcl2cc::Convert(), ccHObject::getChildrenNumber(), ecvColor::Generator::Random(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccObject::setName(), ccPointCloud::setRGBColor(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), and cloudViewer::PointCloudTpl< T >::size().
Referenced by GetClousterGroup(), and GetSegmentationGroup().
DiffVector()
static std::vector<int> ecvTools::DiffVector (std::vector< int > a, std::vector< int > b) static
Definition at line 45 of file ecvTools.h.
References a.
Referenced by PclAnnotationTool::areaPickingEventProcess(), and PclFiltersTool::areaPickingEventProcess().
GetClousterGroup() [1/2]
static ccHObject* ecvTools::GetClousterGroup (const ccPointCloud * ccCloud, const PointCloudT::ConstPtr xyzCloud, const std::vector< pcl::PointIndices > & cluster_indices, unsigned minPointsPerComponent, bool randomColors, bool & error) static
Definition at line 148 of file ecvTools.h.
References AddPointCloud(), ccHObject::getChildrenNumber(), ccObject::getName(), ccDrawableObject::setVisible(), and TO_PCL_CLOUD.
Referenced by DONSegmentation::compute(), and EuclideanClusterSegmentation::compute().
GetClousterGroup() [2/2]
static ccHObject* ecvTools::GetClousterGroup (const ccPointCloud * ccCloud, const std::vector< std::vector< size_t >> & cluster_indices, unsigned minPointsPerComponent, bool randomColors, bool & error) static
Definition at line 198 of file ecvTools.h.
References ccHObject::addChild(), ccPointCloud::From(), ccHObject::getChildrenNumber(), ccObject::getName(), ecvColor::Generator::Random(), ccObject::setName(), ccPointCloud::setRGBColor(), ccDrawableObject::setVisible(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), and cloudViewer::PointCloudTpl< T >::size().
GetPolylines()
static ccPolyline* ecvTools::GetPolylines (PCLCloud::Ptr & curve_sm, const QString & name = "curve", bool closed = true, const ecvColor::Rgb & color = ecvColor::green) static
Definition at line 69 of file ecvTools.h.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), color, pcl2cc::Convert(), name, ecvColor::red(), cloudViewer::ReferenceCloud::reserve(), cloudViewer::Polyline::setClosed(), ccPolyline::setColor(), ccObject::setName(), ccGenericPointCloud::setPointSize(), ccDrawableObject::setTempColor(), ccDrawableObject::setVisible(), ccDrawableObject::showColors(), and cloudViewer::PointCloudTpl< T >::size().
Referenced by NurbsCurveFitting::compute(), and NurbsSurfaceReconstruction::compute().
GetSegmentationGroup()
static ccHObject* ecvTools::GetSegmentationGroup (const ccPointCloud * ccCloud, const PointCloudT::ConstPtr cloudRemained, const std::vector< PointCloudT::Ptr > & cloudExtractions, bool randomColors, bool & error) static
Definition at line 246 of file ecvTools.h.
References AddPointCloud(), ccHObject::getChildrenNumber(), ccObject::getName(), ccDrawableObject::setVisible(), and TO_PCL_CLOUD.
Referenced by SACSegmentation::compute().
IntersectionVector()
static std::vector<int> ecvTools::IntersectionVector (std::vector< int > & a, std::vector< int > & b) static
Definition at line 30 of file ecvTools.h.
References a.
Referenced by PclAnnotationTool::areaPickingEventProcess(), and PclFiltersTool::areaPickingEventProcess().
TransFormRGB() [1/2]
static ecvColor::Rgbf ecvTools::TransFormRGB (const ecvColor::Rgb & col) static
Definition at line 53 of file ecvTools.h.
References ecvColor::RgbTpl< Type >::b, ecvColor::RgbTpl< Type >::g, and ecvColor::RgbTpl< Type >::r.
Referenced by PCLDisplayTools::changeEntityProperties(), PclUtils::PCLVis::displayText(), PCLDisplayTools::displayText(), PCLDisplayTools::drawBBox(), PCLDisplayTools::drawWidgets(), and PCLDisplayTools::setBackgroundColor().
TransFormRGB() [2/2]
static ecvColor::Rgbf ecvTools::TransFormRGB (const ecvColor::Rgbf & col) static
Definition at line 61 of file ecvTools.h.
References ecvColor::RgbTpl< Type >::b, ecvColor::RgbTpl< Type >::g, and ecvColor::RgbTpl< Type >::r.
UnionVector()
static std::vector<int> ecvTools::UnionVector (std::vector< int > & a, std::vector< int > & b) static
Definition at line 39 of file ecvTools.h.
References a.
Referenced by PclAnnotationTool::areaPickingEventProcess(), and PclFiltersTool::areaPickingEventProcess().