ACloudViewer: cloudViewer::core::kernel Namespace Reference
cloudViewer::core::kernel Namespace Reference
Classes
class CPUReductionEngine
class CPUArgReductionEngine
Enumerations
enum class BinaryEWOpCode {
Add , Sub , Mul , Div ,
Maximum , Minimum , LogicalAnd , LogicalOr ,
LogicalXor , Gt , Lt , Ge ,
Le , Eq , Ne
}
enum class ReductionOpCode {
Sum , Prod , Min , Max ,
ArgMin , ArgMax , All , Any
}
enum class UnaryEWOpCode {
Sqrt , Sin , Cos , Neg ,
Exp , Abs , IsNan , IsInf ,
IsFinite , Floor , Ceil , Round ,
Trunc , LogicalNot
}
Functions
Tensor Arange (const Tensor &start, const Tensor &stop, const Tensor &step)
void ArangeCPU (const Tensor &start, const Tensor &stop, const Tensor &step, Tensor &dst)
void ArangeSYCL (const Tensor &start, const Tensor &stop, const Tensor &step, Tensor &dst)
void BinaryEW (const Tensor &lhs, const Tensor &rhs, Tensor &dst, BinaryEWOpCode op_code)
void BinaryEWCPU (const Tensor &lhs, const Tensor &rhs, Tensor &dst, BinaryEWOpCode op_code)
template<typename src_t , typename dst_t , typename element_func_t >
static void LaunchBinaryEWKernel (const Indexer &indexer, const element_func_t &element_func)
template<typename src_t , typename dst_t , typename element_func_t , typename vec_func_t >
static void LaunchBinaryEWKernel (const Indexer &indexer, const element_func_t &element_func, const vec_func_t &vec_func)
template<typename scalar_t >
static void CPUMaxElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename scalar_t >
static void CPUMinElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename scalar_t >
static void CPUAddElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename scalar_t >
static void CPUSubElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename scalar_t >
static void CPUMulElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename scalar_t >
static void CPUDivElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename src_t , typename dst_t >
static void CPULogicalAndElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename src_t , typename dst_t >
static void CPULogicalOrElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename src_t , typename dst_t >
static void CPULogicalXorElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename src_t , typename dst_t >
static void CPUGtElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename src_t , typename dst_t >
static void CPULtElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename src_t , typename dst_t >
static void CPUGeqElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename src_t , typename dst_t >
static void CPULeqElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename src_t , typename dst_t >
static void CPUEqElementKernel (const void *lhs, const void *rhs, void *dst)
template<typename src_t , typename dst_t >
static void CPUNeqElementKernel (const void *lhs, const void *rhs, void *dst)
void BinaryEWSYCL (const Tensor &lhs, const Tensor &rhs, Tensor &dst, BinaryEWOpCode op_code)
void IndexGet (const Tensor &src, Tensor &dst, const std::vector< Tensor > &index_tensors, const SizeVector &indexed_shape, const SizeVector &indexed_strides)
void IndexSet (const Tensor &src, Tensor &dst, const std::vector< Tensor > &index_tensors, const SizeVector &indexed_shape, const SizeVector &indexed_strides)
void IndexGetCPU (const Tensor &src, Tensor &dst, const std::vector< Tensor > &index_tensors, const SizeVector &indexed_shape, const SizeVector &indexed_strides)
void IndexSetCPU (const Tensor &src, Tensor &dst, const std::vector< Tensor > &index_tensors, const SizeVector &indexed_shape, const SizeVector &indexed_strides)
template<typename func_t >
static void LaunchAdvancedIndexerKernel (const AdvancedIndexer &indexer, const func_t &func)
template<typename scalar_t >
static void CPUCopyElementKernel (const void *src, void *dst)
static void CPUCopyObjectElementKernel (const void *src, void *dst, int64_t object_byte_size)
void IndexGetSYCL (const Tensor &src, Tensor &dst, const std::vector< Tensor > &index_tensors, const SizeVector &indexed_shape, const SizeVector &indexed_strides)
void IndexSetSYCL (const Tensor &src, Tensor &dst, const std::vector< Tensor > &index_tensors, const SizeVector &indexed_shape, const SizeVector &indexed_strides)
void IndexAdd_ (int64_t dim, const Tensor &index, const Tensor &src, Tensor &dst)
void IndexAddCPU_ (int64_t dim, const Tensor &index, const Tensor &src, Tensor &dst)
template<typename func_t >
void LaunchIndexReductionKernel (int64_t dim, const Device &device, const Tensor &index, const Tensor &src, Tensor &dst, const func_t &element_kernel)
template<typename scalar_t >
static CLOUDVIEWER_HOST_DEVICE void CPUSumKernel (const void *src, void *dst)
void IndexAddSYCL_ (int64_t dim, const Tensor &index, const Tensor &src, Tensor &dst)
void TestLinalgIntegration ()
Tensor NonZero (const Tensor &src)
Tensor NonZeroCPU (const Tensor &src)
Tensor NonZeroSYCL (const Tensor &src)
void Reduction (const Tensor &src, Tensor &dst, const SizeVector &dims, bool keepdim, ReductionOpCode op_code)
void ReductionCPU (const Tensor &src, Tensor &dst, const SizeVector &dims, bool keepdim, ReductionOpCode op_code)
template<typename scalar_t >
static scalar_t CPUSumReductionKernel (scalar_t a, scalar_t b)
template<typename scalar_t >
static scalar_t CPUProdReductionKernel (scalar_t a, scalar_t b)
template<typename scalar_t >
static scalar_t CPUMinReductionKernel (scalar_t a, scalar_t b)
template<typename scalar_t >
static scalar_t CPUMaxReductionKernel (scalar_t a, scalar_t b)
static uint8_t CPUAllReductionKernel (uint8_t a, uint8_t b)
static uint8_t CPUAnyReductionKernel (uint8_t a, uint8_t b)
template<typename scalar_t >
static std::pair< int64_t, scalar_t > CPUArgMinReductionKernel (int64_t a_idx, scalar_t a, int64_t b_idx, scalar_t b)
template<typename scalar_t >
static std::pair< int64_t, scalar_t > CPUArgMaxReductionKernel (int64_t a_idx, scalar_t a, int64_t b_idx, scalar_t b)
void ReductionSYCL (const Tensor &src, Tensor &dst, const SizeVector &dims, bool keepdim, ReductionOpCode op_code)
void UnaryEW (const Tensor &src, Tensor &dst, UnaryEWOpCode op_code)
void Copy (const Tensor &src, Tensor &dst)
void UnaryEWCPU (const Tensor &src, Tensor &dst, UnaryEWOpCode op_code)
void CopyCPU (const Tensor &src, Tensor &dst)
template<typename element_func_t >
static void LaunchUnaryEWKernel (const Indexer &indexer, const element_func_t &element_func)
template<typename src_t , typename dst_t , typename element_func_t >
static void LaunchUnaryEWKernel (const Indexer &indexer, const element_func_t &element_func)
template<typename src_t , typename dst_t , typename element_func_t , typename vec_func_t >
static void LaunchUnaryEWKernel (const Indexer &indexer, const element_func_t &element_func, const vec_func_t &vec_func)
template<typename src_t , typename dst_t >
static void CPUCopyElementKernel (const void *src, void *dst)
static void CPUCopyObjectElementKernel (const void *src, void *dst, int64_t object_byte_size)
template<typename scalar_t >
static void CPUSqrtElementKernel (const void *src, void *dst)
template<typename scalar_t >
static void CPUSinElementKernel (const void *src, void *dst)
template<typename scalar_t >
static void CPUCosElementKernel (const void *src, void *dst)
template<typename scalar_t , typename std::enable_if< std::is_integral< scalar_t >::value, int >::type = 0>
static void CPUNegElementKernel (const void *src, void *dst)
template<typename scalar_t >
static void CPUExpElementKernel (const void *src, void *dst)
template<typename scalar_t >
static void CPUAbsElementKernel (const void *src, void *dst)
template<typename scalar_t >
static void CPUIsNanElementKernel (const void *src, void *dst)
template<typename scalar_t >
static void CPUIsInfElementKernel (const void *src, void *dst)
template<typename scalar_t >
static void CPUIsFiniteElementKernel (const void *src, void *dst)
template<typename scalar_t >
static void CPUFloorElementKernel (const void *src, void *dst)
template<typename scalar_t >
static void CPUCeilElementKernel (const void *src, void *dst)
template<typename scalar_t >
static void CPURoundElementKernel (const void *src, void *dst)
template<typename scalar_t >
static void CPUTruncElementKernel (const void *src, void *dst)
template<typename src_t , typename dst_t >
static void CPULogicalNotElementKernel (const void *src, void *dst)
void CopySYCL (const Tensor &src, Tensor &dst)
void UnaryEWSYCL (const Tensor &src, Tensor &dst, UnaryEWOpCode op_code)
Variables
const std::unordered_set< BinaryEWOpCode, utility::hash_enum_class > s_boolean_binary_ew_op_codes
static const std::unordered_set< ReductionOpCode, utility::hash_enum_class > s_regular_reduce_ops
static const std::unordered_set< ReductionOpCode, utility::hash_enum_class > s_arg_reduce_ops
static const std::unordered_set< ReductionOpCode, utility::hash_enum_class > s_boolean_reduce_ops
Enumeration Type Documentation
BinaryEWOpCode
enum cloudViewer::core::kernel::BinaryEWOpCode strong
Enumerator
Add
Sub
Mul
Div
Maximum
Minimum
LogicalAnd
LogicalOr
LogicalXor
Gt
Lt
Ge
Le
Eq
Ne
Definition at line 21 of file BinaryEW.h.
ReductionOpCode
enum cloudViewer::core::kernel::ReductionOpCode strong
Enumerator
Sum
Prod
Min
Max
ArgMin
ArgMax
All
Any
Definition at line 22 of file Reduction.h.
UnaryEWOpCode
enum cloudViewer::core::kernel::UnaryEWOpCode strong
Enumerator
Sqrt
Sin
Cos
Neg
Exp
Abs
IsNan
IsInf
IsFinite
Floor
Ceil
Round
Trunc
LogicalNot
Definition at line 18 of file UnaryEW.h.
Function Documentation
Arange()
Tensor cloudViewer::core::kernel::Arange (const Tensor & start, const Tensor & stop, const Tensor & step)
Definition at line 17 of file Arange.cpp.
References ArangeCPU(), ArangeSYCL(), AssertTensorDevice, AssertTensorShape, cloudViewer::utility::ceil(), DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::Item(), and LogError.
Referenced by cloudViewer::core::Tensor::Arange().
ArangeCPU()
void cloudViewer::core::kernel::ArangeCPU (const Tensor & start, const Tensor & stop, const Tensor & step, Tensor & dst)
Definition at line 17 of file ArangeCPU.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetLength(), cloudViewer::core::Tensor::Item(), and cloudViewer::core::ParallelFor().
Referenced by Arange().
ArangeSYCL()
void cloudViewer::core::kernel::ArangeSYCL (const Tensor & start, const Tensor & stop, const Tensor & step, Tensor & dst)
Definition at line 17 of file ArangeSYCL.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::sy::SYCLContext::GetInstance(), cloudViewer::core::Tensor::GetLength(), and cloudViewer::core::Tensor::Item().
Referenced by Arange().
BinaryEW()
void cloudViewer::core::kernel::BinaryEW (const Tensor & lhs, const Tensor & rhs, Tensor & dst, BinaryEWOpCode op_code)
Definition at line 30 of file BinaryEW.cpp.
References BinaryEWCPU(), BinaryEWSYCL(), cloudViewer::core::shape_util::BroadcastedShape(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), cloudViewer::core::IsDevice::IsSYCL(), LogError, and cloudViewer::core::Device::ToString().
Referenced by cloudViewer::core::Tensor::Add(), cloudViewer::core::Tensor::Add_(), cloudViewer::core::Tensor::Div(), cloudViewer::core::Tensor::Div_(), cloudViewer::core::Tensor::Eq(), cloudViewer::core::Tensor::Eq_(), cloudViewer::core::Tensor::Ge(), cloudViewer::core::Tensor::Ge_(), cloudViewer::core::Tensor::Gt(), cloudViewer::core::Tensor::Gt_(), cloudViewer::core::Tensor::Le(), cloudViewer::core::Tensor::Le_(), cloudViewer::core::Tensor::LogicalAnd(), cloudViewer::core::Tensor::LogicalAnd_(), cloudViewer::core::Tensor::LogicalOr(), cloudViewer::core::Tensor::LogicalOr_(), cloudViewer::core::Tensor::LogicalXor(), cloudViewer::core::Tensor::LogicalXor_(), cloudViewer::core::Tensor::Lt(), cloudViewer::core::Tensor::Lt_(), cloudViewer::core::Maximum(), cloudViewer::core::Minimum(), cloudViewer::core::Tensor::Mul(), cloudViewer::core::Tensor::Mul_(), cloudViewer::core::Tensor::Ne(), cloudViewer::core::Tensor::Ne_(), cloudViewer::core::Tensor::Sub(), and cloudViewer::core::Tensor::Sub_().
BinaryEWCPU()
void cloudViewer::core::kernel::BinaryEWCPU (const Tensor & lhs, const Tensor & rhs, Tensor & dst, BinaryEWOpCode op_code)
Definition at line 154 of file BinaryEWCPU.cpp.
References Add, cloudViewer::core::ALL_SAME, cloudViewer::core::Bool, CLOUDVIEWER_TEMPLATE_VECTORIZED, CPUAddElementKernel(), CPULogicalAndElementKernel(), CPULogicalOrElementKernel(), CPULogicalXorElementKernel(), CPUMulElementKernel(), CPUSubElementKernel(), DISPATCH_DTYPE_TO_TEMPLATE, DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, Div, Eq, Ge, cloudViewer::core::Tensor::GetDtype(), Gt, indexer, cloudViewer::core::INPUT_SAME_OUTPUT_BOOL, Le, LogError, LogicalAnd, LogicalOr, LogicalXor, Lt, Maximum, Minimum, Mul, Ne, s_boolean_binary_ew_op_codes, and Sub.
Referenced by BinaryEW().
BinaryEWSYCL()
void cloudViewer::core::kernel::BinaryEWSYCL (const Tensor & lhs, const Tensor & rhs, Tensor & dst, BinaryEWOpCode op_code)
Definition at line 116 of file BinaryEWSYCL.cpp.
References Add, cloudViewer::core::ALL_SAME, cloudViewer::core::Bool, DISPATCH_DTYPE_TO_TEMPLATE, DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, Div, Eq, Ge, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), Gt, indexer, cloudViewer::core::INPUT_SAME_OUTPUT_BOOL, Le, LogError, LogicalAnd, LogicalOr, LogicalXor, Lt, Maximum, Minimum, Mul, Ne, cloudViewer::core::ParallelForSYCL(), s_boolean_binary_ew_op_codes, and Sub.
Referenced by BinaryEW().
Copy()
void cloudViewer::core::kernel::Copy (const Tensor & src, Tensor & dst)
Definition at line 66 of file UnaryEW.cpp.
References cloudViewer::core::shape_util::CanBeBrocastedToShape(), CopyCPU(), CopySYCL(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Device::IsCUDA(), cloudViewer::core::Device::IsSYCL(), and LogError.
Referenced by cloudViewer::core::Tensor::operator=(), and cloudViewer::core::Tensor::To().
CopyCPU()
void cloudViewer::core::kernel::CopyCPU (const Tensor & src, Tensor & dst)
Definition at line 174 of file UnaryEWCPU.cpp.
References cloudViewer::core::Dtype::ByteSize(), CPUCopyObjectElementKernel(), DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), indexer, cloudViewer::core::Tensor::IsContiguous(), cloudViewer::core::Dtype::IsObject(), LaunchUnaryEWKernel(), cloudViewer::core::MemoryManager::Memcpy(), cloudViewer::core::NONE, cloudViewer::core::SizeVector::NumElements(), cloudViewer::core::Tensor::NumElements(), cloudViewer::core::ParallelFor(), and cloudViewer::core::Tensor::To().
Referenced by Copy().
CopySYCL()
void cloudViewer::core::kernel::CopySYCL (const Tensor & src, Tensor & dst)
Definition at line 131 of file UnaryEWSYCL.cpp.
References cloudViewer::core::Dtype::ByteSize(), cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Tensor::CopyFrom(), DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::sy::SYCLContext::GetInstance(), cloudViewer::core::Tensor::GetShape(), indexer, cloudViewer::core::Tensor::IsContiguous(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Dtype::IsObject(), cloudViewer::core::Device::IsSYCL(), cloudViewer::core::IsDevice::IsSYCL(), LogError, cloudViewer::core::MemoryManager::Memcpy(), cloudViewer::core::NONE, cloudViewer::core::SizeVector::NumElements(), cloudViewer::core::Tensor::NumElements(), cloudViewer::core::Tensor::To(), and cloudViewer::core::Device::ToString().
Referenced by Copy().
CPUAbsElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUAbsElementKernel (const void * src, void * dst) static
Definition at line 121 of file UnaryEWCPU.cpp.
References abs().
Referenced by UnaryEWCPU().
CPUAddElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUAddElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 68 of file BinaryEWCPU.cpp.
Referenced by BinaryEWCPU().
CPUAllReductionKernel()
static uint8_t cloudViewer::core::kernel::CPUAllReductionKernel (uint8_t a, uint8_t b) inline static
Definition at line 42 of file ReductionCPU.cpp.
CPUAnyReductionKernel()
static uint8_t cloudViewer::core::kernel::CPUAnyReductionKernel (uint8_t a, uint8_t b) inline static
Definition at line 46 of file ReductionCPU.cpp.
CPUArgMaxReductionKernel()
template<typename scalar_t > static std::pair<int64_t, scalar_t> cloudViewer::core::kernel::CPUArgMaxReductionKernel (int64_t a_idx, scalar_t a, int64_t b_idx, scalar_t b) inline static
Definition at line 61 of file ReductionCPU.cpp.
CPUArgMinReductionKernel()
template<typename scalar_t > static std::pair<int64_t, scalar_t> cloudViewer::core::kernel::CPUArgMinReductionKernel (int64_t a_idx, scalar_t a, int64_t b_idx, scalar_t b) inline static
Definition at line 51 of file ReductionCPU.cpp.
CPUCeilElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUCeilElementKernel (const void * src, void * dst) static
Definition at line 151 of file UnaryEWCPU.cpp.
References cloudViewer::utility::ceil().
Referenced by UnaryEWCPU().
CPUCopyElementKernel() [1/2]
template<typename scalar_t > static void cloudViewer::core::kernel::CPUCopyElementKernel (const void * src, void * dst) static
Definition at line 30 of file IndexGetSetCPU.cpp.
CPUCopyElementKernel() [2/2]
template<typename src_t , typename dst_t > static void cloudViewer::core::kernel::CPUCopyElementKernel (const void * src, void * dst) static
Definition at line 67 of file UnaryEWCPU.cpp.
CPUCopyObjectElementKernel() [1/2]
static void cloudViewer::core::kernel::CPUCopyObjectElementKernel (const void * src, void * dst, int64_t object_byte_size) static
Definition at line 34 of file IndexGetSetCPU.cpp.
Referenced by CopyCPU(), IndexGetCPU(), and IndexSetCPU().
CPUCopyObjectElementKernel() [2/2]
static void cloudViewer::core::kernel::CPUCopyObjectElementKernel (const void * src, void * dst, int64_t object_byte_size) static
Definition at line 72 of file UnaryEWCPU.cpp.
CPUCosElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUCosElementKernel (const void * src, void * dst) static
Definition at line 93 of file UnaryEWCPU.cpp.
Referenced by UnaryEWCPU().
CPUDivElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUDivElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 86 of file BinaryEWCPU.cpp.
CPUEqElementKernel()
template<typename src_t , typename dst_t > static void cloudViewer::core::kernel::CPUEqElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 143 of file BinaryEWCPU.cpp.
CPUExpElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUExpElementKernel (const void * src, void * dst) static
Definition at line 115 of file UnaryEWCPU.cpp.
Referenced by UnaryEWCPU().
CPUFloorElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUFloorElementKernel (const void * src, void * dst) static
Definition at line 145 of file UnaryEWCPU.cpp.
References cloudViewer::utility::floor().
Referenced by UnaryEWCPU().
CPUGeqElementKernel()
template<typename src_t , typename dst_t > static void cloudViewer::core::kernel::CPUGeqElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 131 of file BinaryEWCPU.cpp.
CPUGtElementKernel()
template<typename src_t , typename dst_t > static void cloudViewer::core::kernel::CPUGtElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 119 of file BinaryEWCPU.cpp.
CPUIsFiniteElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUIsFiniteElementKernel (const void * src, void * dst) static
Definition at line 139 of file UnaryEWCPU.cpp.
CPUIsInfElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUIsInfElementKernel (const void * src, void * dst) static
Definition at line 133 of file UnaryEWCPU.cpp.
CPUIsNanElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUIsNanElementKernel (const void * src, void * dst) static
Definition at line 127 of file UnaryEWCPU.cpp.
Referenced by UnaryEWCPU().
CPULeqElementKernel()
template<typename src_t , typename dst_t > static void cloudViewer::core::kernel::CPULeqElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 137 of file BinaryEWCPU.cpp.
CPULogicalAndElementKernel()
template<typename src_t , typename dst_t > static void cloudViewer::core::kernel::CPULogicalAndElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 92 of file BinaryEWCPU.cpp.
Referenced by BinaryEWCPU().
CPULogicalNotElementKernel()
template<typename src_t , typename dst_t > static void cloudViewer::core::kernel::CPULogicalNotElementKernel (const void * src, void * dst) static
Definition at line 169 of file UnaryEWCPU.cpp.
Referenced by UnaryEWCPU().
CPULogicalOrElementKernel()
template<typename src_t , typename dst_t > static void cloudViewer::core::kernel::CPULogicalOrElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 101 of file BinaryEWCPU.cpp.
Referenced by BinaryEWCPU().
CPULogicalXorElementKernel()
template<typename src_t , typename dst_t > static void cloudViewer::core::kernel::CPULogicalXorElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 110 of file BinaryEWCPU.cpp.
Referenced by BinaryEWCPU().
CPULtElementKernel()
template<typename src_t , typename dst_t > static void cloudViewer::core::kernel::CPULtElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 125 of file BinaryEWCPU.cpp.
CPUMaxElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUMaxElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 56 of file BinaryEWCPU.cpp.
References max().
CPUMaxReductionKernel()
template<typename scalar_t > static scalar_t cloudViewer::core::kernel::CPUMaxReductionKernel (scalar_t a, scalar_t b) inline static
Definition at line 38 of file ReductionCPU.cpp.
References max().
CPUMinElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUMinElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 62 of file BinaryEWCPU.cpp.
References min().
CPUMinReductionKernel()
template<typename scalar_t > static scalar_t cloudViewer::core::kernel::CPUMinReductionKernel (scalar_t a, scalar_t b) inline static
Definition at line 33 of file ReductionCPU.cpp.
References min().
CPUMulElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUMulElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 80 of file BinaryEWCPU.cpp.
Referenced by BinaryEWCPU().
CPUNegElementKernel()
template<typename scalar_t , typename std::enable_if< std::is_integral< scalar_t >::value, int >::type = 0> static void cloudViewer::core::kernel::CPUNegElementKernel (const void * src, void * dst) static
Definition at line 101 of file UnaryEWCPU.cpp.
Referenced by UnaryEWCPU().
CPUNeqElementKernel()
template<typename src_t , typename dst_t > static void cloudViewer::core::kernel::CPUNeqElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 149 of file BinaryEWCPU.cpp.
CPUProdReductionKernel()
template<typename scalar_t > static scalar_t cloudViewer::core::kernel::CPUProdReductionKernel (scalar_t a, scalar_t b) inline static
Definition at line 28 of file ReductionCPU.cpp.
CPURoundElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPURoundElementKernel (const void * src, void * dst) static
Definition at line 157 of file UnaryEWCPU.cpp.
Referenced by UnaryEWCPU().
CPUSinElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUSinElementKernel (const void * src, void * dst) static
Definition at line 87 of file UnaryEWCPU.cpp.
Referenced by UnaryEWCPU().
CPUSqrtElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUSqrtElementKernel (const void * src, void * dst) static
Definition at line 81 of file UnaryEWCPU.cpp.
Referenced by UnaryEWCPU().
CPUSubElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUSubElementKernel (const void * lhs, const void * rhs, void * dst) static
Definition at line 74 of file BinaryEWCPU.cpp.
Referenced by BinaryEWCPU().
CPUSumKernel()
template<typename scalar_t > static CLOUDVIEWER_HOST_DEVICE void cloudViewer::core::kernel::CPUSumKernel (const void * src, void * dst) static
Definition at line 60 of file IndexReductionCPU.cpp.
CPUSumReductionKernel()
template<typename scalar_t > static scalar_t cloudViewer::core::kernel::CPUSumReductionKernel (scalar_t a, scalar_t b) inline static
Definition at line 23 of file ReductionCPU.cpp.
CPUTruncElementKernel()
template<typename scalar_t > static void cloudViewer::core::kernel::CPUTruncElementKernel (const void * src, void * dst) static
Definition at line 163 of file UnaryEWCPU.cpp.
Referenced by UnaryEWCPU().
IndexAdd_()
void cloudViewer::core::kernel::IndexAdd_ (int64_t dim, const Tensor & index, const Tensor & src, Tensor & dst)
Definition at line 16 of file IndexReduction.cpp.
References IndexAddCPU_(), IndexAddSYCL_(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), cloudViewer::core::IsDevice::IsSYCL(), LogError, cloudViewer::core::Tensor::NumDims(), cloudViewer::core::Tensor::Permute(), and cloudViewer::core::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by cloudViewer::core::Tensor::IndexAdd_().
IndexAddCPU_()
void cloudViewer::core::kernel::IndexAddCPU_ (int64_t dim, const Tensor & index, const Tensor & src, Tensor & dst)
Definition at line 66 of file IndexReductionCPU.cpp.
References DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, and cloudViewer::core::Tensor::GetDtype().
Referenced by IndexAdd_().
IndexAddSYCL_()
void cloudViewer::core::kernel::IndexAddSYCL_ (int64_t dim, const Tensor & index, const Tensor & src, Tensor & dst)
Definition at line 19 of file IndexReductionSYCL.cpp.
References DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::sy::SYCLContext::GetInstance(), cloudViewer::core::Tensor::GetShape(), indexer, cloudViewer::core::NONE, and cloudViewer::core::Tensor::NumDims().
Referenced by IndexAdd_().
IndexGet()
void cloudViewer::core::kernel::IndexGet (const Tensor & src, Tensor & dst, const std::vector< Tensor > & index_tensors, const SizeVector & indexed_shape, const SizeVector & indexed_strides)
Definition at line 22 of file IndexGetSet.cpp.
References cloudViewer::core::Tensor::CopyFrom(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), IndexGetCPU(), IndexGetSYCL(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), cloudViewer::core::IsDevice::IsSYCL(), and LogError.
Referenced by cloudViewer::core::Tensor::IndexGet().
IndexGetCPU()
void cloudViewer::core::kernel::IndexGetCPU (const Tensor & src, Tensor & dst, const std::vector< Tensor > & index_tensors, const SizeVector & indexed_shape, const SizeVector & indexed_strides)
Definition at line 42 of file IndexGetSetCPU.cpp.
References cloudViewer::core::Dtype::ByteSize(), CPUCopyObjectElementKernel(), DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, cloudViewer::core::AdvancedIndexer::GET, cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Dtype::IsObject(), and LaunchAdvancedIndexerKernel().
Referenced by IndexGet().
IndexGetSYCL()
void cloudViewer::core::kernel::IndexGetSYCL (const Tensor & src, Tensor & dst, const std::vector< Tensor > & index_tensors, const SizeVector & indexed_shape, const SizeVector & indexed_strides)
Definition at line 18 of file IndexGetSetSYCL.cpp.
References cloudViewer::core::Dtype::ByteSize(), DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, cloudViewer::core::AdvancedIndexer::GET, cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::AdvancedIndexer::GetInputPtr(), cloudViewer::core::sy::SYCLContext::GetInstance(), cloudViewer::core::AdvancedIndexer::GetOutputPtr(), cloudViewer::core::Dtype::IsObject(), and cloudViewer::core::AdvancedIndexer::NumWorkloads().
Referenced by IndexGet().
IndexSet()
void cloudViewer::core::kernel::IndexSet (const Tensor & src, Tensor & dst, const std::vector< Tensor > & index_tensors, const SizeVector & indexed_shape, const SizeVector & indexed_strides)
Definition at line 52 of file IndexGetSet.cpp.
References cloudViewer::core::Tensor::GetDevice(), IndexSetCPU(), IndexSetSYCL(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), cloudViewer::core::IsDevice::IsSYCL(), LogError, and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::core::Tensor::IndexSet().
IndexSetCPU()
void cloudViewer::core::kernel::IndexSetCPU (const Tensor & src, Tensor & dst, const std::vector< Tensor > & index_tensors, const SizeVector & indexed_shape, const SizeVector & indexed_strides)
Definition at line 62 of file IndexGetSetCPU.cpp.
References cloudViewer::core::Dtype::ByteSize(), CPUCopyObjectElementKernel(), DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Dtype::IsObject(), LaunchAdvancedIndexerKernel(), and cloudViewer::core::AdvancedIndexer::SET.
Referenced by IndexSet().
IndexSetSYCL()
void cloudViewer::core::kernel::IndexSetSYCL (const Tensor & src, Tensor & dst, const std::vector< Tensor > & index_tensors, const SizeVector & indexed_shape, const SizeVector & indexed_strides)
Definition at line 46 of file IndexGetSetSYCL.cpp.
References cloudViewer::core::Dtype::ByteSize(), DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, cloudViewer::core::sy::SYCLContext::GetDefaultQueue(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::AdvancedIndexer::GetInputPtr(), cloudViewer::core::sy::SYCLContext::GetInstance(), cloudViewer::core::AdvancedIndexer::GetOutputPtr(), cloudViewer::core::Dtype::IsObject(), cloudViewer::core::AdvancedIndexer::NumWorkloads(), and cloudViewer::core::AdvancedIndexer::SET.
Referenced by IndexSet().
LaunchAdvancedIndexerKernel()
template<typename func_t > static void cloudViewer::core::kernel::LaunchAdvancedIndexerKernel (const AdvancedIndexer & indexer, const func_t & func) static
Definition at line 21 of file IndexGetSetCPU.cpp.
References indexer, and cloudViewer::core::ParallelFor().
Referenced by IndexGetCPU(), and IndexSetCPU().
LaunchBinaryEWKernel() [1/2]
template<typename src_t , typename dst_t , typename element_func_t > static void cloudViewer::core::kernel::LaunchBinaryEWKernel (const Indexer & indexer, const element_func_t & element_func) static
Definition at line 28 of file BinaryEWCPU.cpp.
References indexer, and cloudViewer::core::ParallelFor().
LaunchBinaryEWKernel() [2/2]
template<typename src_t , typename dst_t , typename element_func_t , typename vec_func_t > static void cloudViewer::core::kernel::LaunchBinaryEWKernel (const Indexer & indexer, const element_func_t & element_func, const vec_func_t & vec_func) static
Definition at line 42 of file BinaryEWCPU.cpp.
References indexer, and cloudViewer::core::ParallelFor().
LaunchIndexReductionKernel()
template<typename func_t > void cloudViewer::core::kernel::LaunchIndexReductionKernel (int64_t dim, const Device & device, const Tensor & index, const Tensor & src, Tensor & dst, const func_t & element_kernel)
Definition at line 19 of file IndexReductionCPU.cpp.
References cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetShape(), indexer, cloudViewer::core::NONE, and cloudViewer::core::Tensor::NumDims().
LaunchUnaryEWKernel() [1/3]
template<typename element_func_t > static void cloudViewer::core::kernel::LaunchUnaryEWKernel (const Indexer & indexer, const element_func_t & element_func) static
Definition at line 31 of file UnaryEWCPU.cpp.
References indexer, and cloudViewer::core::ParallelFor().
Referenced by CopyCPU().
LaunchUnaryEWKernel() [2/3]
template<typename src_t , typename dst_t , typename element_func_t > static void cloudViewer::core::kernel::LaunchUnaryEWKernel (const Indexer & indexer, const element_func_t & element_func) static
Definition at line 41 of file UnaryEWCPU.cpp.
References indexer, and cloudViewer::core::ParallelFor().
LaunchUnaryEWKernel() [3/3]
template<typename src_t , typename dst_t , typename element_func_t , typename vec_func_t > static void cloudViewer::core::kernel::LaunchUnaryEWKernel (const Indexer & indexer, const element_func_t & element_func, const vec_func_t & vec_func) static
Definition at line 54 of file UnaryEWCPU.cpp.
References indexer, and cloudViewer::core::ParallelFor().
NonZero()
Tensor cloudViewer::core::kernel::NonZero (const Tensor & src)
Definition at line 19 of file NonZero.cpp.
References cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), cloudViewer::core::IsDevice::IsSYCL(), LogError, NonZeroCPU(), and NonZeroSYCL().
Referenced by cloudViewer::core::Tensor::NonZero(), and cloudViewer::core::Tensor::NonZeroNumpy().
NonZeroCPU()
Tensor cloudViewer::core::kernel::NonZeroCPU (const Tensor & src)
Definition at line 20 of file NonZeroCPU.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, cloudViewer::core::Tensor::GetDtype(), and cloudViewer::core::Tensor::NumElements().
Referenced by NonZero().
NonZeroSYCL()
Tensor cloudViewer::core::kernel::NonZeroSYCL (const Tensor & src)
Definition at line 22 of file NonZeroSYCL.cpp.
References cloudViewer::core::Tensor::Arange(), DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Int64, and cloudViewer::core::Tensor::NumElements().
Referenced by NonZero().
Reduction()
void cloudViewer::core::kernel::Reduction (const Tensor & src, Tensor & dst, const SizeVector & dims, bool keepdim, ReductionOpCode op_code)
Definition at line 16 of file Reduction.cpp.
References cloudViewer::core::Tensor::AsRvalue(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), cloudViewer::core::IsDevice::IsSYCL(), LogError, cloudViewer::core::Tensor::NumDims(), cloudViewer::core::Tensor::NumElements(), ReductionCPU(), cloudViewer::core::shape_util::ReductionShape(), ReductionSYCL(), cloudViewer::core::Tensor::Reshape(), s_arg_reduce_ops, cloudViewer::core::SmallVectorBase< Size_T >::size(), cloudViewer::core::Device::ToString(), and cloudViewer::core::SizeVector::ToString().
Referenced by cloudViewer::core::Tensor::All(), cloudViewer::core::Tensor::Any(), cloudViewer::core::Tensor::ArgMax(), cloudViewer::core::Tensor::ArgMin(), cloudViewer::core::Tensor::Max(), cloudViewer::core::Tensor::Min(), cloudViewer::core::Tensor::Prod(), and cloudViewer::core::Tensor::Sum().
ReductionCPU()
void cloudViewer::core::kernel::ReductionCPU (const Tensor & src, Tensor & dst, const SizeVector & dims, bool keepdim, ReductionOpCode op_code)
Definition at line 278 of file ReductionCPU.cpp.
References cloudViewer::core::ALL_SAME, DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetDtype(), indexer, and s_regular_reduce_ops.
Referenced by Reduction().
ReductionSYCL()
void cloudViewer::core::kernel::ReductionSYCL (const Tensor & src, Tensor & dst, const SizeVector & dims, bool keepdim, ReductionOpCode op_code)
Definition at line 211 of file ReductionSYCL.cpp.
References cloudViewer::core::ALL_SAME, DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), indexer, and s_regular_reduce_ops.
Referenced by Reduction().
TestLinalgIntegration()
void cloudViewer::core::kernel::TestLinalgIntegration ()
Definition at line 21 of file Kernel.cpp.
References LogInfo, and min().
UnaryEW()
void cloudViewer::core::kernel::UnaryEW (const Tensor & src, Tensor & dst, UnaryEWOpCode op_code)
Definition at line 19 of file UnaryEW.cpp.
References cloudViewer::core::shape_util::CanBeBrocastedToShape(), Cos, Exp, cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetShape(), cloudViewer::core::Device::IsCPU(), cloudViewer::core::Device::IsCUDA(), IsFinite, IsInf, IsNan, cloudViewer::core::Device::IsSYCL(), LogError, Sin, Sqrt, cloudViewer::core::Device::ToString(), cloudViewer::core::Dtype::ToString(), UnaryEWCPU(), and UnaryEWSYCL().
Referenced by cloudViewer::core::Tensor::Abs(), cloudViewer::core::Tensor::Abs_(), cloudViewer::core::Tensor::Ceil(), cloudViewer::core::Tensor::Cos(), cloudViewer::core::Tensor::Cos_(), cloudViewer::core::Tensor::Exp(), cloudViewer::core::Tensor::Exp_(), cloudViewer::core::Tensor::Floor(), cloudViewer::core::Tensor::IsFinite(), cloudViewer::core::Tensor::IsInf(), cloudViewer::core::Tensor::IsNan(), cloudViewer::core::Tensor::LogicalNot(), cloudViewer::core::Tensor::LogicalNot_(), cloudViewer::core::Tensor::Neg(), cloudViewer::core::Tensor::Neg_(), cloudViewer::core::Tensor::Round(), cloudViewer::core::Tensor::Sin(), cloudViewer::core::Tensor::Sin_(), cloudViewer::core::Tensor::Sqrt(), cloudViewer::core::Tensor::Sqrt_(), and cloudViewer::core::Tensor::Trunc().
UnaryEWCPU()
void cloudViewer::core::kernel::UnaryEWCPU (const Tensor & src, Tensor & dst, UnaryEWOpCode op_code)
Definition at line 217 of file UnaryEWCPU.cpp.
References Abs, cloudViewer::core::ALL_SAME, cloudViewer::core::Bool, Ceil, CLOUDVIEWER_TEMPLATE_VECTORIZED, Cos, CPUAbsElementKernel(), CPUCeilElementKernel(), CPUCosElementKernel(), CPUExpElementKernel(), CPUFloorElementKernel(), CPUIsNanElementKernel(), CPULogicalNotElementKernel(), CPUNegElementKernel(), CPURoundElementKernel(), CPUSinElementKernel(), CPUSqrtElementKernel(), CPUTruncElementKernel(), DISPATCH_DTYPE_TO_TEMPLATE, DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, Exp, Floor, cloudViewer::core::Tensor::GetDtype(), indexer, cloudViewer::core::INPUT_SAME_OUTPUT_BOOL, IsFinite, IsInf, IsNan, LogError, LogicalNot, Neg, Round, Sin, Sqrt, and Trunc.
Referenced by UnaryEW().
UnaryEWSYCL()
void cloudViewer::core::kernel::UnaryEWSYCL (const Tensor & src, Tensor & dst, UnaryEWOpCode op_code)
Definition at line 199 of file UnaryEWSYCL.cpp.
References Abs, cloudViewer::core::ALL_SAME, Ceil, Cos, DISPATCH_DTYPE_TO_TEMPLATE, DISPATCH_DTYPE_TO_TEMPLATE_WITH_BOOL, Exp, Floor, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), indexer, cloudViewer::core::INPUT_SAME_OUTPUT_BOOL, IsFinite, IsInf, IsNan, LogError, LogicalNot, Neg, Round, Sin, Sqrt, and Trunc.
Referenced by UnaryEW().
Variable Documentation
s_arg_reduce_ops
const std::unordered_set<ReductionOpCode, utility::hash_enum_class> cloudViewer::core::kernel::s_arg_reduce_ops static
Initial value:
= {
                ReductionOpCode::ArgMin,
                ReductionOpCode::ArgMax,
}
Definition at line 41 of file Reduction.h.
Referenced by Reduction().
s_boolean_binary_ew_op_codes
const std::unordered_set< BinaryEWOpCode, utility::hash_enum_class > cloudViewer::core::kernel::s_boolean_binary_ew_op_codes
Initial value:
{
                BinaryEWOpCode::LogicalAnd, BinaryEWOpCode::LogicalOr,
                BinaryEWOpCode::LogicalXor, BinaryEWOpCode::Gt,
                BinaryEWOpCode::Lt,         BinaryEWOpCode::Ge,
                BinaryEWOpCode::Le,         BinaryEWOpCode::Eq,
                BinaryEWOpCode::Ne,
        }
Definition at line 22 of file BinaryEW.cpp.
Referenced by BinaryEWCPU(), and BinaryEWSYCL().
s_boolean_reduce_ops
const std::unordered_set<ReductionOpCode, utility::hash_enum_class> cloudViewer::core::kernel::s_boolean_reduce_ops static
Initial value:
= {
                ReductionOpCode::All,
                ReductionOpCode::Any,
}
Definition at line 46 of file Reduction.h.
s_regular_reduce_ops
const std::unordered_set<ReductionOpCode, utility::hash_enum_class> cloudViewer::core::kernel::s_regular_reduce_ops static
Initial value:
= {
                ReductionOpCode::Sum,
                ReductionOpCode::Prod,
                ReductionOpCode::Min,
                ReductionOpCode::Max,
}
Definition at line 34 of file Reduction.h.
Referenced by ReductionCPU(), and ReductionSYCL().