ACloudViewer: QtCompat Namespace Reference
QtCompat Namespace Reference
Functions
QTextStream & endl (QTextStream &stream)
Variables
constexpr Qt::SplitBehavior SkipEmptyParts = Qt::SkipEmptyParts
constexpr Qt::SplitBehavior KeepEmptyParts = Qt::KeepEmptyParts
Function Documentation
endl()
QTextStream& QtCompat::endl (QTextStream & stream) inline
Definition at line 718 of file QtCompat.h.
Referenced by colmap::CorrespondenceGraph::AddCorrespondences(), BOOST_AUTO_TEST_CASE(), e57::CompressedVectorWriterImpl::close(), colmap::CompleteAndMergeTracks(), colmap::IncrementalTriangulator::CompleteImage(), e57::CompressedVectorReaderImpl::CompressedVectorReaderImpl(), colmap::CameraRig::ComputeRelativePoses(), e57::ImageFileImpl::construct2(), colmap::SceneClustering::Create(), CP::create_CP(), colmap::CreateSiftGPUMatcher(), colmap::CudaCheck(), colmap::CudaSafeCall(), colmap::CudaSyncAndCheck(), cloudViewer::visualization::gui::Layout1D::debug_PrintPreferredSizes(), e57::Decoder::DecoderFactory(), q3DMASCPlugin::doTrainAction(), e57::CompressedVectorReaderImpl::dump(), e57::CompressedVectorWriterImpl::dump(), e57::DecodeChannel::dump(), e57::PacketReadCache::dump(), e57::BlobSectionHeader::dump(), e57::SourceDestBufferImpl::dump(), e57::Encoder::dump(), e57::E57FileHeader::dump(), e57::ImageFileImpl::dump(), e57::NodeImpl::dump(), IndexPacket::dump(), EmptyPacketHeader::dump(), e57::DataPacketHeader::dump(), e57::DataPacket::dump(), e57::CompressedVectorSectionHeader::dump(), e57::BlobNodeImpl::dump(), e57::CompressedVectorNodeImpl::dump(), e57::BitpackEncoder::dump(), e57::BitpackFloatEncoder::dump(), e57::BitpackStringEncoder::dump(), e57::BitpackIntegerEncoder< RegisterT >::dump(), e57::ConstantIntegerEncoder::dump(), e57::FloatNodeImpl::dump(), e57::IntegerNodeImpl::dump(), e57::ScaledIntegerNodeImpl::dump(), e57::StringNodeImpl::dump(), e57::StructureNodeImpl::dump(), e57::VectorNodeImpl::dump(), e57::BitpackDecoder::dump(), e57::BitpackFloatDecoder::dump(), e57::BitpackStringDecoder::dump(), e57::BitpackIntegerDecoder< RegisterT >::dump(), e57::ConstantIntegerDecoder::dump(), e57::Encoder::EncoderFactory(), CGAL_Normal_Estimator::estimate(), PCL_Normal_Estimator< Point, Normal >::estimate(), colmap::EstimateManhattanWorldFrame(), colmap::Reconstruction::ExportBundler(), colmap::Reconstruction::ExportCam(), colmap::Reconstruction::ExportNVM(), colmap::Reconstruction::ExportRecon3D(), ccHistogramWindowDlg::exportToCSV(), G3PointPlots::exportToCSV(), ccCompass::exportToSVG(), colmap::Reconstruction::ExportVRML(), colmap::Reconstruction::ExtractColorsForAllImages(), colmap::FilterImages(), colmap::FilterPoints(), ecvColor::RgbTpl< Type >::FromEigen(), e57::DataPacket::getBytestream(), cloudViewer::gpu::gpuInformationCUDA(), GrainsAsEllipsoids::GrainsAsEllipsoids(), colmap::mvs::ImportPMVSWorkspace(), CP::CutPursuit_KL< T >::init_labels(), e57::BitpackDecoder::inputProcess(), e57::ConstantIntegerDecoder::inputProcess(), e57::BitpackFloatDecoder::inputProcessAligned(), e57::BitpackStringDecoder::inputProcessAligned(), e57::BitpackIntegerDecoder< RegisterT >::inputProcessAligned(), colmap::DatabaseCache::Load(), colmap::mvs::Workspace::Load(), cloudViewer::visualization::gui::LoadMaterialTemplate(), e57::PacketReadCache::lock(), ecvConsole::logMessage(), main(), colmap::MatchGuidedSiftFeaturesGPU(), colmap::MatchSiftFeaturesGPU(), myMessageOutput(), G3Point::myPrint(), Train3DMASCDialog::onExportResults(), VTKExtensions::vtkCustomInteractorStyle::OnKeyDown(), ccCompass::onSave(), ccMPlaneDlgController::onSaveButtonClicked(), cloudViewer::system::operator<<(), ccCameraSensor::OrthoRectifyAsImages(), e57::BitpackEncoder::outputRead(), e57::PacketLock::PacketLock(), colmap::OptionManager::Parse(), e57::ImageFileImpl::pathNameParse(), pc_save(), colmap::mvs::PatchMatch::Problem::Print(), colmap::CudaTimer::Print(), colmap::PrintHeading1(), colmap::PrintHeading2(), colmap::Timer::PrintHours(), colmap::Timer::PrintMinutes(), colmap::Timer::PrintSeconds(), vtkCommandOptions::PrintSelf(), vtkPVTestUtilities::PrintSelf(), vtkPVXMLElement::PrintSelf(), vtkStringList::PrintSelf(), vtkUndoElement::PrintSelf(), vtkUndoStack::PrintSelf(), vtkCameraManipulator::PrintSelf(), VTKExtensions::vtkCustomInteractorStyle::PrintSelf(), vtkPVInteractorStyle::PrintSelf(), vtkPVJoystickFly::PrintSelf(), vtkPVTrackballRotate::PrintSelf(), vtkPVTrackballZoom::PrintSelf(), vtkPVTrackballZoomToMouse::PrintSelf(), vtkBoundedPlaneSource::PrintSelf(), vtkBoundedVolumeSource::PrintSelf(), vtkScalarBarActorCustom::PrintSelf(), vtkScalarBarWidgetCustom::PrintSelf(), colmap::PrintSolverSummary(), PdmsFileSession::printWarning(), CommandComputeMeshVolume::process(), CommandMatchBestFitPlane::process(), CommandICP::process(), CommandVolume25D::process(), e57::BitpackFloatEncoder::processRecords(), e57::BitpackStringEncoder::processRecords(), e57::BitpackIntegerEncoder< RegisterT >::processRecords(), e57::ConstantIntegerEncoder::processRecords(), e57::CompressedVectorReaderImpl::read(), colmap::OptionManager::Read(), cloudViewer::ImageViewerWidget::ReadAndShow(), colmap::ImageViewerWidget::ReadAndShow(), cloudViewer::FeatureImageViewerWidget::ReadAndShowWithKeypoints(), colmap::FeatureImageViewerWidget::ReadAndShowWithKeypoints(), cloudViewer::FeatureImageViewerWidget::ReadAndShowWithMatches(), colmap::FeatureImageViewerWidget::ReadAndShowWithMatches(), e57::PacketReadCache::readPacket(), colmap::ReadPly(), colmap::RefineAbsolutePose(), e57::BitpackIntegerEncoder< RegisterT >::registerFlushToOutput(), colmap::IncrementalMapper::RegisterNextImage(), cloudViewer::OptionsParser::registerOption(), e57::E57Exception::report(), colmap::IncrementalTriangulator::Retriangulate(), rotationMatrixToFile(), VtkUtils::AnsysFileReader::run(), CP::CutPursuit< T >::run(), colmap::SiftGPUFeatureMatcher::Run(), colmap::TwoViewGeometryVerifier::Run(), colmap::RunBundleAdjuster(), colmap::RunDatabaseCleaner(), colmap::RunDatabaseMerger(), colmap::RunDelaunayMesher(), colmap::AutomaticReconstructionController::RunDenseMapper(), colmap::RunFeatureExtractor(), colmap::RunGraphicalUserInterface(), colmap::RunHierarchicalMapper(), colmap::RunImageDeleter(), colmap::RunImageFilterer(), colmap::RunImageRegistrator(), colmap::RunImageTexturer(), colmap::RunImageUndistorter(), colmap::RunImageUndistorterStandalone(), colmap::RunMapper(), colmap::RunModelAligner(), colmap::RunModelAnalyzer(), colmap::RunModelComparer(), colmap::RunModelConverter(), colmap::RunModelCropper(), colmap::RunModelMerger(), colmap::RunModelOrientationAligner(), colmap::RunModelSplitter(), colmap::RunModelTransformer(), colmap::RunPatchMatchStereo(), colmap::RunPointFiltering(), colmap::RunPointTriangulator(), colmap::RunRigBundleAdjuster(), colmap::RunStereoFuser(), colmap::RunVocabTreeBuilder(), colmap::RunVocabTreeRetriever(), ConfusionMatrix::save(), ccMaterialSet::saveAsMTL(), masc::Tools::SaveClassifier(), ccCompassExport::saveCSV(), DistanceMapGenerationTool::SaveMapAsCSVMatrix(), Cloth::saveMovableToFile(), masc::Feature::SaveSources(), ccCompassExport::saveSVG(), ObjFilter::saveToFile(), OFFFilter::saveToFile(), VTKFilter::saveToFile(), SalomeHydroFilter::saveToFile(), SinusxFilter::saveToFile(), HeightProfileFilter::saveToFile(), MascaretFilter::saveToFile(), Cloth::saveToFile(), Train3DMASCDialog::saveTraces(), e57::StructureNodeImpl::set(), CP::set_speed(), vtkDistributedTrivialProducer::SetGlobalOutput(), ecvConsole::setLogFile(), cloudViewer::visualization::gui::GLFWWindowSystem::SetWindowSizePixels(), cloudViewer::PointViewerWidget::Show(), colmap::PointViewerWidget::Show(), colmap::SiftFeatureExtractor::SiftFeatureExtractor(), colmap::BundleAdjuster::Solve(), colmap::RigBundleAdjuster::Solve(), stdVectorToFile(), ccWaveform::ToASCII(), ccGLMatrixTpl< T >::toAsciiFile(), ccIndexedTransformation::toAsciiFile(), cloudViewer::t::geometry::TensorMap::ToString(), colmap::IncrementalTriangulator::TriangulateImage(), e57::CheckedFile::unlink(), e57::PacketReadCache::unlock(), vtkDistributedTrivialProducer::UpdateFromGlobal(), e57::DataPacket::verify(), cloudViewer::visualization::gui::GLFWWindowSystem::WaitEventsTimeout(), WolmanCustomPlot::WolmanCustomPlot(), e57::CompressedVectorWriterImpl::write(), colmap::SimilarityTransform3::Write(), PdmsTools::PdmsObjects::GroupElement::write(), PdmsTools::PdmsObjects::SCylinder::write(), PdmsTools::PdmsObjects::CTorus::write(), PdmsTools::PdmsObjects::RTorus::write(), PdmsTools::PdmsObjects::Dish::write(), PdmsTools::PdmsObjects::Cone::write(), PdmsTools::PdmsObjects::Box::write(), colmap::WriteTextPlyPoints(), e57::CompressedVectorReaderImpl::~CompressedVectorReaderImpl(), e57::CompressedVectorWriterImpl::~CompressedVectorWriterImpl(), and e57::PacketLock::~PacketLock().
Variable Documentation
KeepEmptyParts
constexpr Qt::SplitBehavior QtCompat::KeepEmptyParts = Qt::KeepEmptyParts constexpr
Definition at line 303 of file QtCompat.h.
SkipEmptyParts
constexpr Qt::SplitBehavior QtCompat::SkipEmptyParts = Qt::SkipEmptyParts constexpr
Definition at line 302 of file QtCompat.h.
Referenced by QuaZipDir::cd(), ccColorScaleEditorDialog::checkCustomLabelsList(), DecodeRotation(), DecodeTransformation(), ccColorScaleEditorDialog::exportCustomLabelsList(), ccGLMatrixTpl< T >::FromString(), GetFacetMetaData(), AsciiOpenDlg::getOpenSequence(), qCanupoTrainingDialog::getScales(), CorrespondenceMatchingDialog::getScales(), TemplateAlignmentDialog::getScales(), ProfileLoader::Load(), STLFilter::loadASCIIFile(), AsciiFilter::loadCloudFromFormatedAsciiStream(), CSVMatrixFilter::loadFile(), ObjFilter::loadFile(), OFFFilter::loadFile(), PTXFilter::loadFile(), VTKFilter::loadFile(), SalomeHydroFilter::loadFile(), SinusxFilter::loadFile(), BundlerFilter::loadFileExtended(), ecvShiftAndScaleCloudDlg::loadInfoFromFile(), DistanceMapGenerationDlg::loadOverlaySymbols(), ccMaterialSet::ParseMTL(), Command3DMASCClassif::process(), AsciiOpenDlg::safeSequence(), ecvPrimitiveFactoryDlg::setSpherePositionFromClipboard(), and AsciiOpenDlg::updateTable().