ACloudViewer: cloudViewer::t::geometry::kernel::minimum_obb Namespace Reference
cloudViewer::t::geometry::kernel::minimum_obb Namespace Reference
Functions
OrientedBoundingBox ComputeMinimumOBBJylanki (const core::Tensor &points_, bool robust)
OrientedBoundingBox ComputeMinimumOBBApprox (const core::Tensor &points, bool robust)
Function Documentation
ComputeMinimumOBBApprox()
OrientedBoundingBox cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBApprox (const core::Tensor & points, bool robust)
Fast approximation of the oriented bounding box with the smallest volume. The algorithm makes use of the fact that at least one edge of the convex hull must be collinear with an edge of the minimum bounding box: for each triangle in the convex hull, calculate the minimal axis aligned box in the frame of that triangle. at the end, return the box with the smallest volume found.
Parameters
points A list of points with data type of float32 or float64 (N x 3 tensor, where N must be larger than 3).
robust If set to true uses a more robust method which works in degenerate cases but introduces noise to the points coordinates.
Definition at line 1248 of file MinimumOBB.cpp.
References AssertTensorShape, cloudViewer::t::geometry::PointCloud::ComputeConvexHull(), cloudViewer::core::Tensor::CopyFrom(), cloudViewer::t::geometry::AxisAlignedBoundingBox::CreateFromPoints(), cloudViewer::core::eigen_converter::EigenMatrixToTensor(), cloudViewer::core::Float32, cloudViewer::t::geometry::PointCloud::GetAxisAlignedBoundingBox(), cloudViewer::t::geometry::OrientedBoundingBox::GetCenter(), cloudViewer::t::geometry::OrientedBoundingBox::GetExtent(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetOrientedBoundingBox(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::OrientedBoundingBox::GetRotation(), LogError, cloudViewer::utility::nullopt, points, cloudViewer::core::Tensor::Reshape(), cloudViewer::t::geometry::PointCloud::Rotate(), cloudViewer::t::geometry::OrientedBoundingBox::Rotate(), cloudViewer::core::eigen_converter::TensorToEigenVector3dVector(), cloudViewer::core::eigen_converter::TensorToEigenVector3iVector(), cloudViewer::core::Tensor::To(), cloudViewer::t::geometry::AxisAlignedBoundingBox::Volume(), and cloudViewer::t::geometry::OrientedBoundingBox::Volume().
Referenced by cloudViewer::t::geometry::OrientedBoundingBox::CreateFromPoints().
ComputeMinimumOBBJylanki()
OrientedBoundingBox cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBJylanki (const core::Tensor & points, bool robust)
Creates the oriented bounding box with the smallest volume. This algorithm is inspired by the article "An Exact Algorithm for Finding Minimum Oriented Bounding Boxes" written by Jukka Jylänki. The original implementation can be found at the following address: https://github.com/juj/MathGeoLib/blob/55053da5e3e55a83043af7324944407b174c3724/src/Geometry/OBB.cpp#L987
Parameters
points A list of points with data type of float32 or float64 (N x 3 tensor, where N must be larger than 3).
robust If set to true uses a more robust method which works in degenerate cases but introduces noise to the points coordinates.
Definition at line 55 of file MinimumOBB.cpp.
References abs(), AssertTensorShape, cloudViewer::t::geometry::PointCloud::ComputeConvexHull(), cloudViewer::t::geometry::AxisAlignedBoundingBox::CreateFromPoints(), cross(), dot(), cloudViewer::core::Tensor::GetDevice(), cloudViewer::t::geometry::AxisAlignedBoundingBox::GetOrientedBoundingBox(), cloudViewer::core::Tensor::GetShape(), infinity(), LogError, cloudViewer::core::make_pair(), max(), min(), cloudViewer::utility::nullopt, std::swap(), cloudViewer::core::eigen_converter::TensorToEigenVector3dVector(), cloudViewer::core::eigen_converter::TensorToEigenVector3iVector(), cloudViewer::t::geometry::kernel::image::To(), and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::t::geometry::OrientedBoundingBox::CreateFromPoints().