ACloudViewer: cloudViewer::pipelines::integration Namespace Reference
cloudViewer::pipelines::integration Namespace Reference
Classes
class ScalableTSDFVolume
class TSDFVolume
Base class of the Truncated Signed Distance Function (TSDF) volume.
class UniformTSDFVolume
UniformTSDFVolume implements the classic TSDF volume with uniform voxel grid (Curless and Levoy 1996).
class PyTSDFVolume
Enumerations
enum class TSDFVolumeColorType { NoColor = 0 , RGB8 = 1 , Gray32 = 2 }
Functions
void pybind_integration_classes (py::module &m)
void pybind_integration_methods (py::module &m)
void pybind_integration (py::module &m)
Enumeration Type Documentation
TSDFVolumeColorType
enum cloudViewer::pipelines::integration::TSDFVolumeColorType strong
Enum class for TSDFVolumeColorType
Enumerator
NoColor
No color.
RGB8
8 bit RGB.
Gray32
32 bit GrayScale.
Definition at line 23 of file TSDFVolume.h.
Function Documentation
pybind_integration()
void cloudViewer::pipelines::integration::pybind_integration (py::module & m)
Definition at line 200 of file integration.cpp.
References pybind_integration_classes(), and pybind_integration_methods().
Referenced by cloudViewer::pipelines::pybind_pipelines().
pybind_integration_classes()
void cloudViewer::pipelines::integration::pybind_integration_classes (py::module & m)
Definition at line 40 of file integration.cpp.
References cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::pipelines::integration::TSDFVolume::color_type_, cloudViewer::pipelines::integration::TSDFVolume::ExtractPointCloud(), cloudViewer::pipelines::integration::TSDFVolume::ExtractTriangleMesh(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractVolumeColor(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractVolumeTSDF(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractVoxelGrid(), cloudViewer::pipelines::integration::ScalableTSDFVolume::ExtractVoxelPointCloud(), cloudViewer::pipelines::integration::UniformTSDFVolume::ExtractVoxelPointCloud(), Gray32, cloudViewer::pipelines::integration::UniformTSDFVolume::InjectVolumeColor(), cloudViewer::pipelines::integration::UniformTSDFVolume::InjectVolumeTSDF(), cloudViewer::pipelines::integration::TSDFVolume::Integrate(), length(), cloudViewer::pipelines::integration::UniformTSDFVolume::length_, NoColor, cloudViewer::pipelines::integration::TSDFVolume::Reset(), cloudViewer::pipelines::integration::UniformTSDFVolume::resolution_, RGB8, cloudViewer::pipelines::integration::TSDFVolume::sdf_trunc_, and cloudViewer::pipelines::integration::TSDFVolume::voxel_length_.
Referenced by pybind_integration().
pybind_integration_methods()
void cloudViewer::pipelines::integration::pybind_integration_methods (py::module & m)
Definition at line 196 of file integration.cpp.
Referenced by pybind_integration().