ACloudViewer: Utils Namespace Reference
Utils Namespace Reference
Classes
class ColorSeriesPrivate
class ColorSeries
class ArrayComparator
class ArrayAssigner
class ArrayInitializer
class Normalizer
Typedefs
typedef QList< QColor > ColorList
typedef QList< vtkActor * > ActorList
Functions
static QColor hexToColor (QRgb num)
QString character (int index)
void explorer (const QString &path)
QImage star (const QSize &size)
double random (int low, int high)
void vtkColor (const QColor &clr, double *vtkClr)
QColor qColor (double *pClr)
static void RGB2HSV (float r, float g, float b, float *h, float *s, float *v)
void qColor2HSV (const QColor &clr, double *hsv)
template<class T >
void vtkSafeDelete (T *obj)
template<class T >
void vtkSafeDelete (QList< T * > &objList)
template<typename T >
T boundedValue (const T &value, const T &min, const T &max)
template<typename T >
static double module (T *vector)
template<typename T >
static double distance (T *pot1, T *pot2)
template<typename T >
static void normal (T *inPot1, T *inPot2, T *outPot)
get vector between two points
Typedef Documentation
ActorList
typedef QList<vtkActor*> Utils::ActorList
Definition at line 84 of file utils.h.
ColorList
typedef QList<QColor> Utils::ColorList
Definition at line 12 of file colorseries.cpp.
Function Documentation
boundedValue()
template<typename T > T Utils::boundedValue (const T & value, const T & min, const T & max) inline
Definition at line 98 of file utils.h.
character()
QString Q_DECL_IMPORT Utils::character (int index)
Definition at line 19 of file utils.cpp.
distance()
template<typename T > static double Utils::distance (T * pot1, T * pot2) inline static
Definition at line 111 of file utils.h.
Referenced by ccMeasurementRecorder::addMeasurementPoint(), ccMPlaneDlg::addMeasurementPoint(), cloudViewer::core::SmallVectorImpl< T >::append(), arg_max_col(), arg_min_col(), cloudViewer::pipelines::registration::BenchmarkCreateFromPointCloudBallPivoting(), ConfusionMatrix::compute(), cloudViewer::t::geometry::RaycastingScene::ComputeDistance(), cloudViewer::DistanceComputationTools::computePoint2MeshDistancesWithOctree(), cloudViewer::t::geometry::RaycastingScene::ComputeSignedDistance(), colmap::DecomposeHomographyMatrix(), define_KdTree(), cloudViewer::KDTree::distanceScanTree(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingHybridSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingKNNSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateColorGradientsUsingRadiusSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingHybridSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingKNNSearchCPU(), cloudViewer::t::geometry::kernel::pointcloud::EstimateCovariancesUsingRadiusSearchCPU(), cloudViewer::geometry::EvaluateRANSACBasedOnDistance(), VtkUtils::DistanceWidgetObserver::Execute(), cloudViewer::KDTree::findPointsLyingToDistance(), vtkStringList::GetIndex(), LasSaveDialog::handleComboBoxChange(), cloudViewer::StaticVector< T >::indexOf(), cloudViewer::StaticVector< T >::indexOfNearestSorted(), cloudViewer::core::SmallVectorImpl< T >::insert(), cloudViewer::StaticVector< T >::maxValId(), cloudViewer::StaticVector< T >::minValId(), cloudViewer::core::kernel::NonZeroCPU(), cloudViewer::core::kernel::NonZeroSYCL(), cloudViewer::ml::contrib::ordered_neighbors(), WaitingSpinnerWidget::paintEvent(), cloudViewer::KDTree::radiusSearch(), cloudViewer::t::geometry::TriangleMesh::RemoveNonManifoldEdges(), cloudViewer::t::geometry::PointCloud::RemoveRadiusOutliers(), cloudViewer::geometry::KDTreeFlann::SearchHybrid(), ccPointCloud::SegmentPlane(), knncpp::BruteForce< Scalar, Distance >::setDistance(), knncpp::KDTreeMinkowski< _Scalar, _Dimension, _Distance >::setDistance(), ccMPlanePoint::setDistance(), ecvViewportParameters::setFocalDistance(), Frustum::sphereInFrustum(), cloudViewer::core::TensorList::TensorList(), and ccMeasurementRecorder::updateMeasurement().
explorer()
void Q_DECL_IMPORT Utils::explorer (const QString & path)
Definition at line 25 of file utils.cpp.
References cloudViewer::t::geometry::path.
hexToColor()
static QColor Utils::hexToColor (QRgb num) inline static
Definition at line 14 of file colorseries.cpp.
module()
template<typename T > static double Utils::module (T * vector) inline static
Definition at line 105 of file utils.h.
Referenced by qPCL::addPclModule(), import_pyccRuntime(), and load_pluginWrappers().
normal()
template<typename T > static void Utils::normal (T * inPot1, T * inPot2, T * outPot) inline static
get vector between two points
Definition at line 122 of file utils.h.
qColor()
QColor Q_DECL_IMPORT Utils::qColor (double * pClr)
Definition at line 69 of file utils.cpp.
Referenced by ecvColor::FromQColor(), ecvColor::FromQColora(), ecvColor::FromQColoraf(), ecvColor::FromQColorf(), ecvColor::FromQRgb(), and ecvColor::FromQRgba().
qColor2HSV()
void Q_DECL_IMPORT Utils::qColor2HSV (const QColor & clr, double * hsv)
Definition at line 97 of file utils.cpp.
References float, RGB2HSV(), and vtkColor().
Referenced by cvGenericFilter::createLookupTable(), and QVTKWidgetCustom::createLookupTable().
random()
double Q_DECL_IMPORT Utils::random (int low, int high)
Definition at line 55 of file utils.cpp.
Referenced by cloudViewer::benchmarks::Rand(), and VtkUtils::TableModel::random().
RGB2HSV()
static void Utils::RGB2HSV (float r, float g, float b, float * h, float * s, float * v) static
Definition at line 73 of file utils.cpp.
Referenced by qColor2HSV().
star()
QImage Q_DECL_IMPORT Utils::star (const QSize & size)
Definition at line 34 of file utils.cpp.
References Pi, and size.
vtkColor()
void Q_DECL_IMPORT Utils::vtkColor (const QColor & clr, double * vtkClr)
Definition at line 60 of file utils.cpp.
Referenced by QVTKWidgetCustom::addActor(), VtkUtils::VtkWidget::addActor(), cvGlyphFilter::apply(), PclUtils::PCLVis::GetDataAxesGridProperties(), VtkUtils::MoveActorInteractorStyle::OnMouseMove(), qColor2HSV(), and cvGenericFilter::setOutlineColor().
vtkSafeDelete() [1/2]
template<class T > void Utils::vtkSafeDelete (QList< T * > & objList) inline
Definition at line 92 of file utils.h.
vtkSafeDelete() [2/2]
template<class T > void Utils::vtkSafeDelete (T * obj) inline
Definition at line 87 of file utils.h.