ACloudViewer: cloudViewer::io::k4a_plugin Namespace Reference
cloudViewer::io::k4a_plugin Namespace Reference
Functions
static void * GetDynamicLibHandle (const std::string &lib_name)
k4a_result_t k4a_record_create (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const char *, path, k4a_device_t, device, const k4a_device_configuration_t, device_config, k4a_record_t *, recording_handle), const char *, path, k4a_device_t, device, const k4a_device_configuration_t, device_config, k4a_record_t *, recording_handle))
k4a_result_t k4a_record_add_tag (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle, const char *, name, const char *, value), k4a_record_t, recording_handle, const char *, name, const char *, value))
k4a_result_t k4a_record_add_imu_track (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle), k4a_record_t, recording_handle))
k4a_result_t k4a_record_write_header (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle), k4a_record_t, recording_handle))
k4a_result_t k4a_record_write_capture (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle, k4a_capture_t, capture_handle), k4a_record_t, recording_handle, k4a_capture_t, capture_handle))
k4a_result_t k4a_record_write_imu_sample (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle, k4a_imu_sample_t, imu_sample), k4a_record_t, recording_handle, k4a_imu_sample_t, imu_sample))
k4a_result_t k4a_record_flush (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle), k4a_record_t, recording_handle))
void k4a_record_close (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle), k4a_record_t, recording_handle))
k4a_result_t k4a_playback_open (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const char *, path, k4a_playback_t *, playback_handle), const char *, path, k4a_playback_t *, playback_handle))
k4a_buffer_result_t k4a_playback_get_raw_calibration (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, uint8_t *, data, size_t *, data_size), k4a_playback_t, playback_handle, uint8_t *, data, size_t *, data_size))
k4a_result_t k4a_playback_get_calibration (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_calibration_t *, calibration), k4a_playback_t, playback_handle, k4a_calibration_t *, calibration))
k4a_result_t k4a_playback_get_record_configuration (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_record_configuration_t *, config), k4a_playback_t, playback_handle, k4a_record_configuration_t *, config))
k4a_buffer_result_t k4a_playback_get_tag (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, const char *, name, char *, value, size_t *, value_size), k4a_playback_t, playback_handle, const char *, name, char *, value, size_t *, value_size))
k4a_result_t k4a_playback_set_color_conversion (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_image_format_t, target_format), k4a_playback_t, playback_handle, k4a_image_format_t, target_format))
k4a_stream_result_t k4a_playback_get_next_capture (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_capture_t *, capture_handle), k4a_playback_t, playback_handle, k4a_capture_t *, capture_handle))
k4a_stream_result_t k4a_playback_get_previous_capture (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_capture_t *, capture_handle), k4a_playback_t, playback_handle, k4a_capture_t *, capture_handle))
k4a_stream_result_t k4a_playback_get_next_imu_sample (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_imu_sample_t *, imu_sample), k4a_playback_t, playback_handle, k4a_imu_sample_t *, imu_sample))
k4a_stream_result_t k4a_playback_get_previous_imu_sample (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_imu_sample_t *, imu_sample), k4a_playback_t, playback_handle, k4a_imu_sample_t *, imu_sample))
k4a_result_t k4a_playback_seek_timestamp (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, int64_t, offset_usec, k4a_playback_seek_origin_t, origin), k4a_playback_t, playback_handle, int64_t, offset_usec, k4a_playback_seek_origin_t, origin))
uint64_t k4a_playback_get_last_timestamp_usec (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle), k4a_playback_t, playback_handle))
void k4a_playback_close (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle), k4a_playback_t, playback_handle))
uint32_t k4a_device_get_installed_count (EXTRACT_TYPES_PARAMS(COUNT_ARGS(),))
k4a_result_t k4a_set_debug_message_handler (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_logging_message_cb_t *, message_cb, void *, message_cb_context, k4a_log_level_t, min_level), k4a_logging_message_cb_t *, message_cb, void *, message_cb_context, k4a_log_level_t, min_level))
k4a_result_t k4a_device_open (EXTRACT_TYPES_PARAMS(COUNT_ARGS(uint32_t, index, k4a_device_t *, device_handle), uint32_t, index, k4a_device_t *, device_handle))
void k4a_device_close (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle), k4a_device_t, device_handle))
k4a_wait_result_t k4a_device_get_capture (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_capture_t *, capture_handle, int32_t, timeout_in_ms), k4a_device_t, device_handle, k4a_capture_t *, capture_handle, int32_t, timeout_in_ms))
k4a_wait_result_t k4a_device_get_imu_sample (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_imu_sample_t *, imu_sample, int32_t, timeout_in_ms), k4a_device_t, device_handle, k4a_imu_sample_t *, imu_sample, int32_t, timeout_in_ms))
k4a_result_t k4a_capture_create (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t *, capture_handle), k4a_capture_t *, capture_handle))
void k4a_capture_release (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle), k4a_capture_t, capture_handle))
void k4a_capture_reference (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle), k4a_capture_t, capture_handle))
k4a_image_t k4a_capture_get_color_image (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle), k4a_capture_t, capture_handle))
k4a_image_t k4a_capture_get_depth_image (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle), k4a_capture_t, capture_handle))
k4a_image_t k4a_capture_get_ir_image (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle), k4a_capture_t, capture_handle))
void k4a_capture_set_color_image (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle, k4a_image_t, image_handle), k4a_capture_t, capture_handle, k4a_image_t, image_handle))
void k4a_capture_set_depth_image (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle, k4a_image_t, image_handle), k4a_capture_t, capture_handle, k4a_image_t, image_handle))
void k4a_capture_set_ir_image (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle, k4a_image_t, image_handle), k4a_capture_t, capture_handle, k4a_image_t, image_handle))
void k4a_capture_set_temperature_c (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle, float, temperature_c), k4a_capture_t, capture_handle, float, temperature_c))
float k4a_capture_get_temperature_c (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle), k4a_capture_t, capture_handle))
k4a_result_t k4a_image_create (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_format_t, format, int, width_pixels, int, height_pixels, int, stride_bytes, k4a_image_t *, image_handle), k4a_image_format_t, format, int, width_pixels, int, height_pixels, int, stride_bytes, k4a_image_t *, image_handle))
k4a_result_t k4a_image_create_from_buffer (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_format_t, format, int, width_pixels, int, height_pixels, int, stride_bytes, uint8_t *, buffer, size_t, buffer_size, k4a_memory_destroy_cb_t *, buffer_release_cb, void *, buffer_release_cb_context, k4a_image_t *, image_handle), k4a_image_format_t, format, int, width_pixels, int, height_pixels, int, stride_bytes, uint8_t *, buffer, size_t, buffer_size, k4a_memory_destroy_cb_t *, buffer_release_cb, void *, buffer_release_cb_context, k4a_image_t *, image_handle))
uint8_t * k4a_image_get_buffer (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
size_t k4a_image_get_size (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
k4a_image_format_t k4a_image_get_format (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
int k4a_image_get_width_pixels (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
int k4a_image_get_height_pixels (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
int k4a_image_get_stride_bytes (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
uint64_t k4a_image_get_timestamp_usec (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
uint64_t k4a_image_get_exposure_usec (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
uint32_t k4a_image_get_white_balance (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
uint32_t k4a_image_get_iso_speed (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
void k4a_image_set_timestamp_usec (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle, uint64_t, timestamp_usec), k4a_image_t, image_handle, uint64_t, timestamp_usec))
void k4a_image_set_exposure_time_usec (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle, uint64_t, exposure_usec), k4a_image_t, image_handle, uint64_t, exposure_usec))
void k4a_image_set_white_balance (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle, uint32_t, white_balance), k4a_image_t, image_handle, uint32_t, white_balance))
void k4a_image_set_iso_speed (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle, uint32_t, iso_speed), k4a_image_t, image_handle, uint32_t, iso_speed))
void k4a_image_reference (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
void k4a_image_release (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
k4a_result_t k4a_device_start_cameras (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_device_configuration_t *, config), k4a_device_t, device_handle, k4a_device_configuration_t *, config))
void k4a_device_stop_cameras (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle), k4a_device_t, device_handle))
k4a_result_t k4a_device_start_imu (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle), k4a_device_t, device_handle))
void k4a_device_stop_imu (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle), k4a_device_t, device_handle))
k4a_buffer_result_t k4a_device_get_serialnum (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, char *, serial_number, size_t *, serial_number_size), k4a_device_t, device_handle, char *, serial_number, size_t *, serial_number_size))
k4a_result_t k4a_device_get_version (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_hardware_version_t *, version), k4a_device_t, device_handle, k4a_hardware_version_t *, version))
k4a_result_t k4a_device_get_color_control_capabilities (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_color_control_command_t, command, bool *, supports_auto, int32_t *, min_value, int32_t *, max_value, int32_t *, step_value, int32_t *, default_value, k4a_color_control_mode_t *, default_mode), k4a_device_t, device_handle, k4a_color_control_command_t, command, bool *, supports_auto, int32_t *, min_value, int32_t *, max_value, int32_t *, step_value, int32_t *, default_value, k4a_color_control_mode_t *, default_mode))
k4a_result_t k4a_device_get_color_control (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_color_control_command_t, command, k4a_color_control_mode_t *, mode, int32_t *, value), k4a_device_t, device_handle, k4a_color_control_command_t, command, k4a_color_control_mode_t *, mode, int32_t *, value))
k4a_result_t k4a_device_set_color_control (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_color_control_command_t, command, k4a_color_control_mode_t, mode, int32_t, value), k4a_device_t, device_handle, k4a_color_control_command_t, command, k4a_color_control_mode_t, mode, int32_t, value))
k4a_buffer_result_t k4a_device_get_raw_calibration (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, uint8_t *, data, size_t *, data_size), k4a_device_t, device_handle, uint8_t *, data, size_t *, data_size))
k4a_result_t k4a_device_get_calibration (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, const k4a_depth_mode_t, depth_mode, const k4a_color_resolution_t, color_resolution, k4a_calibration_t *, calibration), k4a_device_t, device_handle, const k4a_depth_mode_t, depth_mode, const k4a_color_resolution_t, color_resolution, k4a_calibration_t *, calibration))
k4a_result_t k4a_device_get_sync_jack (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, bool *, sync_in_jack_connected, bool *, sync_out_jack_connected), k4a_device_t, device_handle, bool *, sync_in_jack_connected, bool *, sync_out_jack_connected))
k4a_result_t k4a_calibration_get_from_raw (EXTRACT_TYPES_PARAMS(COUNT_ARGS(char *, raw_calibration, size_t, raw_calibration_size, const k4a_depth_mode_t, depth_mode, const k4a_color_resolution_t, color_resolution, k4a_calibration_t *, calibration), char *, raw_calibration, size_t, raw_calibration_size, const k4a_depth_mode_t, depth_mode, const k4a_color_resolution_t, color_resolution, k4a_calibration_t *, calibration))
k4a_result_t k4a_calibration_3d_to_3d (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const k4a_calibration_t *, calibration, const k4a_float3_t *, source_point3d_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float3_t *, target_point3d_mm), const k4a_calibration_t *, calibration, const k4a_float3_t *, source_point3d_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float3_t *, target_point3d_mm))
k4a_result_t k4a_calibration_2d_to_3d (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const k4a_calibration_t *, calibration, const k4a_float2_t *, source_point2d, const float, source_depth_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float3_t *, target_point3d_mm, int *, valid), const k4a_calibration_t *, calibration, const k4a_float2_t *, source_point2d, const float, source_depth_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float3_t *, target_point3d_mm, int *, valid))
k4a_result_t k4a_calibration_3d_to_2d (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const k4a_calibration_t *, calibration, const k4a_float3_t *, source_point3d_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float2_t *, target_point2d, int *, valid), const k4a_calibration_t *, calibration, const k4a_float3_t *, source_point3d_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float2_t *, target_point2d, int *, valid))
k4a_result_t k4a_calibration_2d_to_2d (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const k4a_calibration_t *, calibration, const k4a_float2_t *, source_point2d, const float, source_depth_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float2_t *, target_point2d, int *, valid), const k4a_calibration_t *, calibration, const k4a_float2_t *, source_point2d, const float, source_depth_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float2_t *, target_point2d, int *, valid))
k4a_transformation_t k4a_transformation_create (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const k4a_calibration_t *, calibration), const k4a_calibration_t *, calibration))
void k4a_transformation_destroy (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_transformation_t, transformation_handle), k4a_transformation_t, transformation_handle))
k4a_result_t k4a_transformation_depth_image_to_color_camera (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_transformation_t, transformation_handle, const k4a_image_t, depth_image, k4a_image_t, transformed_depth_image), k4a_transformation_t, transformation_handle, const k4a_image_t, depth_image, k4a_image_t, transformed_depth_image))
k4a_result_t k4a_transformation_color_image_to_depth_camera (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_transformation_t, transformation_handle, const k4a_image_t, depth_image, const k4a_image_t, color_image, k4a_image_t, transformed_color_image), k4a_transformation_t, transformation_handle, const k4a_image_t, depth_image, const k4a_image_t, color_image, k4a_image_t, transformed_color_image))
k4a_result_t k4a_transformation_depth_image_to_point_cloud (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_transformation_t, transformation_handle, const k4a_image_t, depth_image, const k4a_calibration_type_t, camera, k4a_image_t, xyz_image), k4a_transformation_t, transformation_handle, const k4a_image_t, depth_image, const k4a_calibration_type_t, camera, k4a_image_t, xyz_image))
k4a_result_t k4a_record_create (const char *path, k4a_device_t device, const k4a_device_configuration_t device_config, k4a_record_t *recording_handle)
k4a_result_t k4a_record_add_tag (k4a_record_t recording_handle, const char *name, const char *value)
k4a_result_t k4a_record_add_imu_track (k4a_record_t recording_handle)
k4a_result_t k4a_record_write_header (k4a_record_t recording_handle)
k4a_result_t k4a_record_write_capture (k4a_record_t recording_handle, k4a_capture_t capture_handle)
k4a_result_t k4a_record_write_imu_sample (k4a_record_t recording_handle, k4a_imu_sample_t imu_sample)
k4a_result_t k4a_record_flush (k4a_record_t recording_handle)
void k4a_record_close (k4a_record_t recording_handle)
k4a_result_t k4a_playback_open (const char *path, k4a_playback_t *playback_handle)
k4a_buffer_result_t k4a_playback_get_raw_calibration (k4a_playback_t playback_handle, uint8_t *data, size_t *data_size)
k4a_result_t k4a_playback_get_calibration (k4a_playback_t playback_handle, k4a_calibration_t *calibration)
k4a_result_t k4a_playback_get_record_configuration (k4a_playback_t playback_handle, k4a_record_configuration_t *config)
k4a_buffer_result_t k4a_playback_get_tag (k4a_playback_t playback_handle, const char *name, char *value, size_t *value_size)
k4a_result_t k4a_playback_set_color_conversion (k4a_playback_t playback_handle, k4a_image_format_t target_format)
k4a_stream_result_t k4a_playback_get_next_capture (k4a_playback_t playback_handle, k4a_capture_t *capture_handle)
k4a_stream_result_t k4a_playback_get_previous_capture (k4a_playback_t playback_handle, k4a_capture_t *capture_handle)
k4a_stream_result_t k4a_playback_get_next_imu_sample (k4a_playback_t playback_handle, k4a_imu_sample_t *imu_sample)
k4a_stream_result_t k4a_playback_get_previous_imu_sample (k4a_playback_t playback_handle, k4a_imu_sample_t *imu_sample)
k4a_result_t k4a_playback_seek_timestamp (k4a_playback_t playback_handle, int64_t offset_usec, k4a_playback_seek_origin_t origin)
uint64_t k4a_playback_get_last_timestamp_usec (k4a_playback_t playback_handle)
void k4a_playback_close (k4a_playback_t playback_handle)
uint32_t k4a_device_get_installed_count (void)
k4a_result_t k4a_set_debug_message_handler (k4a_logging_message_cb_t *message_cb, void *message_cb_context, k4a_log_level_t min_level)
k4a_result_t k4a_device_open (uint32_t index, k4a_device_t *device_handle)
void k4a_device_close (k4a_device_t device_handle)
k4a_wait_result_t k4a_device_get_capture (k4a_device_t device_handle, k4a_capture_t *capture_handle, int32_t timeout_in_ms)
k4a_wait_result_t k4a_device_get_imu_sample (k4a_device_t device_handle, k4a_imu_sample_t *imu_sample, int32_t timeout_in_ms)
k4a_result_t k4a_capture_create (k4a_capture_t *capture_handle)
void k4a_capture_release (k4a_capture_t capture_handle)
void k4a_capture_reference (k4a_capture_t capture_handle)
k4a_image_t k4a_capture_get_color_image (k4a_capture_t capture_handle)
k4a_image_t k4a_capture_get_depth_image (k4a_capture_t capture_handle)
k4a_image_t k4a_capture_get_ir_image (k4a_capture_t capture_handle)
void k4a_capture_set_color_image (k4a_capture_t capture_handle, k4a_image_t image_handle)
void k4a_capture_set_depth_image (k4a_capture_t capture_handle, k4a_image_t image_handle)
void k4a_capture_set_ir_image (k4a_capture_t capture_handle, k4a_image_t image_handle)
void k4a_capture_set_temperature_c (k4a_capture_t capture_handle, float temperature_c)
float k4a_capture_get_temperature_c (k4a_capture_t capture_handle)
k4a_result_t k4a_image_create (k4a_image_format_t format, int width_pixels, int height_pixels, int stride_bytes, k4a_image_t *image_handle)
k4a_result_t k4a_image_create_from_buffer (k4a_image_format_t format, int width_pixels, int height_pixels, int stride_bytes, uint8_t *buffer, size_t buffer_size, k4a_memory_destroy_cb_t *buffer_release_cb, void *buffer_release_cb_context, k4a_image_t *image_handle)
uint8_t * k4a_image_get_buffer (k4a_image_t image_handle)
size_t k4a_image_get_size (k4a_image_t image_handle)
k4a_image_format_t k4a_image_get_format (k4a_image_t image_handle)
int k4a_image_get_width_pixels (k4a_image_t image_handle)
int k4a_image_get_height_pixels (k4a_image_t image_handle)
int k4a_image_get_stride_bytes (k4a_image_t image_handle)
uint64_t k4a_image_get_timestamp_usec (k4a_image_t image_handle)
uint64_t k4a_image_get_exposure_usec (k4a_image_t image_handle)
uint32_t k4a_image_get_white_balance (k4a_image_t image_handle)
uint32_t k4a_image_get_iso_speed (k4a_image_t image_handle)
void k4a_image_set_timestamp_usec (k4a_image_t image_handle, uint64_t timestamp_usec)
void k4a_image_set_exposure_time_usec (k4a_image_t image_handle, uint64_t exposure_usec)
void k4a_image_set_white_balance (k4a_image_t image_handle, uint32_t white_balance)
void k4a_image_set_iso_speed (k4a_image_t image_handle, uint32_t iso_speed)
void k4a_image_reference (k4a_image_t image_handle)
void k4a_image_release (k4a_image_t image_handle)
k4a_result_t k4a_device_start_cameras (k4a_device_t device_handle, k4a_device_configuration_t *config)
void k4a_device_stop_cameras (k4a_device_t device_handle)
k4a_result_t k4a_device_start_imu (k4a_device_t device_handle)
void k4a_device_stop_imu (k4a_device_t device_handle)
k4a_buffer_result_t k4a_device_get_serialnum (k4a_device_t device_handle, char *serial_number, size_t *serial_number_size)
k4a_result_t k4a_device_get_version (k4a_device_t device_handle, k4a_hardware_version_t *version)
k4a_result_t k4a_device_get_color_control_capabilities (k4a_device_t device_handle, k4a_color_control_command_t command, bool *supports_auto, int32_t *min_value, int32_t *max_value, int32_t *step_value, int32_t *default_value, k4a_color_control_mode_t *default_mode)
k4a_result_t k4a_device_get_color_control (k4a_device_t device_handle, k4a_color_control_command_t command, k4a_color_control_mode_t *mode, int32_t *value)
k4a_result_t k4a_device_set_color_control (k4a_device_t device_handle, k4a_color_control_command_t command, k4a_color_control_mode_t mode, int32_t value)
k4a_buffer_result_t k4a_device_get_raw_calibration (k4a_device_t device_handle, uint8_t *data, size_t *data_size)
k4a_result_t k4a_device_get_calibration (k4a_device_t device_handle, const k4a_depth_mode_t depth_mode, const k4a_color_resolution_t color_resolution, k4a_calibration_t *calibration)
k4a_result_t k4a_device_get_sync_jack (k4a_device_t device_handle, bool *sync_in_jack_connected, bool *sync_out_jack_connected)
k4a_result_t k4a_calibration_get_from_raw (char *raw_calibration, size_t raw_calibration_size, const k4a_depth_mode_t depth_mode, const k4a_color_resolution_t color_resolution, k4a_calibration_t *calibration)
k4a_result_t k4a_calibration_3d_to_3d (const k4a_calibration_t *calibration, const k4a_float3_t *source_point3d_mm, const k4a_calibration_type_t source_camera, const k4a_calibration_type_t target_camera, k4a_float3_t *target_point3d_mm)
k4a_result_t k4a_calibration_2d_to_3d (const k4a_calibration_t *calibration, const k4a_float2_t *source_point2d, const float source_depth_mm, const k4a_calibration_type_t source_camera, const k4a_calibration_type_t target_camera, k4a_float3_t *target_point3d_mm, int *valid)
k4a_result_t k4a_calibration_3d_to_2d (const k4a_calibration_t *calibration, const k4a_float3_t *source_point3d_mm, const k4a_calibration_type_t source_camera, const k4a_calibration_type_t target_camera, k4a_float2_t *target_point2d, int *valid)
k4a_result_t k4a_calibration_2d_to_2d (const k4a_calibration_t *calibration, const k4a_float2_t *source_point2d, const float source_depth_mm, const k4a_calibration_type_t source_camera, const k4a_calibration_type_t target_camera, k4a_float2_t *target_point2d, int *valid)
k4a_transformation_t k4a_transformation_create (const k4a_calibration_t *calibration)
void k4a_transformation_destroy (k4a_transformation_t transformation_handle)
k4a_result_t k4a_transformation_depth_image_to_color_camera (k4a_transformation_t transformation_handle, const k4a_image_t depth_image, k4a_image_t transformed_depth_image)
k4a_result_t k4a_transformation_color_image_to_depth_camera (k4a_transformation_t transformation_handle, const k4a_image_t depth_image, const k4a_image_t color_image, k4a_image_t transformed_color_image)
k4a_result_t k4a_transformation_depth_image_to_point_cloud (k4a_transformation_t transformation_handle, const k4a_image_t depth_image, const k4a_calibration_type_t camera, k4a_image_t xyz_image)
Variables
static const std::string k4a_lib_name = "libk4a.so"
static const std::string k4arecord_lib_name = "libk4arecord.so"
Function Documentation
GetDynamicLibHandle()
static void* cloudViewer::io::k4a_plugin::GetDynamicLibHandle (const std::string & lib_name) static
Definition at line 108 of file K4aPlugin.cpp.
References LogDebug, LogError, LogWarning, NULL, and cloudViewer::utility::SplitString().
k4a_calibration_2d_to_2d() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_calibration_2d_to_2d (const k4a_calibration_t * calibration, const k4a_float2_t * source_point2d, const float source_depth_mm, const k4a_calibration_type_t source_camera, const k4a_calibration_type_t target_camera, k4a_float2_t * target_point2d, int * valid)
k4a_calibration_2d_to_2d() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_calibration_2d_to_2d (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const k4a_calibration_t *, calibration, const k4a_float2_t *, source_point2d, const float, source_depth_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float2_t *, target_point2d, int *, valid), const k4a_calibration_t *, calibration, const k4a_float2_t *, source_point2d, const float, source_depth_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float2_t *, target_point2d, int *, valid))
Definition at line 783 of file K4aPlugin.cpp.
k4a_calibration_2d_to_3d() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_calibration_2d_to_3d (const k4a_calibration_t * calibration, const k4a_float2_t * source_point2d, const float source_depth_mm, const k4a_calibration_type_t source_camera, const k4a_calibration_type_t target_camera, k4a_float3_t * target_point3d_mm, int * valid)
k4a_calibration_2d_to_3d() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_calibration_2d_to_3d (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const k4a_calibration_t *, calibration, const k4a_float2_t *, source_point2d, const float, source_depth_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float3_t *, target_point3d_mm, int *, valid), const k4a_calibration_t *, calibration, const k4a_float2_t *, source_point2d, const float, source_depth_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float3_t *, target_point3d_mm, int *, valid))
Definition at line 749 of file K4aPlugin.cpp.
k4a_calibration_3d_to_2d() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_calibration_3d_to_2d (const k4a_calibration_t * calibration, const k4a_float3_t * source_point3d_mm, const k4a_calibration_type_t source_camera, const k4a_calibration_type_t target_camera, k4a_float2_t * target_point2d, int * valid)
k4a_calibration_3d_to_2d() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_calibration_3d_to_2d (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const k4a_calibration_t *, calibration, const k4a_float3_t *, source_point3d_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float2_t *, target_point2d, int *, valid), const k4a_calibration_t *, calibration, const k4a_float3_t *, source_point3d_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float2_t *, target_point2d, int *, valid))
Definition at line 765 of file K4aPlugin.cpp.
k4a_calibration_3d_to_3d() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_calibration_3d_to_3d (const k4a_calibration_t * calibration, const k4a_float3_t * source_point3d_mm, const k4a_calibration_type_t source_camera, const k4a_calibration_type_t target_camera, k4a_float3_t * target_point3d_mm)
k4a_calibration_3d_to_3d() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_calibration_3d_to_3d (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const k4a_calibration_t *, calibration, const k4a_float3_t *, source_point3d_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float3_t *, target_point3d_mm), const k4a_calibration_t *, calibration, const k4a_float3_t *, source_point3d_mm, const k4a_calibration_type_t, source_camera, const k4a_calibration_type_t, target_camera, k4a_float3_t *, target_point3d_mm))
Definition at line 731 of file K4aPlugin.cpp.
k4a_calibration_get_from_raw() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_calibration_get_from_raw (char * raw_calibration, size_t raw_calibration_size, const k4a_depth_mode_t depth_mode, const k4a_color_resolution_t color_resolution, k4a_calibration_t * calibration)
k4a_calibration_get_from_raw() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_calibration_get_from_raw (EXTRACT_TYPES_PARAMS(COUNT_ARGS(char *, raw_calibration, size_t, raw_calibration_size, const k4a_depth_mode_t, depth_mode, const k4a_color_resolution_t, color_resolution, k4a_calibration_t *, calibration), char *, raw_calibration, size_t, raw_calibration_size, const k4a_depth_mode_t, depth_mode, const k4a_color_resolution_t, color_resolution, k4a_calibration_t *, calibration))
Definition at line 717 of file K4aPlugin.cpp.
k4a_capture_create() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_capture_create (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t *, capture_handle), k4a_capture_t *, capture_handle))
Definition at line 393 of file K4aPlugin.cpp.
k4a_capture_create() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_capture_create (k4a_capture_t * capture_handle)
k4a_capture_get_color_image() [1/2]
k4a_image_t cloudViewer::io::k4a_plugin::k4a_capture_get_color_image (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle), k4a_capture_t, capture_handle))
Definition at line 408 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::DecompressCapture().
k4a_capture_get_color_image() [2/2]
k4a_image_t cloudViewer::io::k4a_plugin::k4a_capture_get_color_image (k4a_capture_t capture_handle)
k4a_capture_get_depth_image() [1/2]
k4a_image_t cloudViewer::io::k4a_plugin::k4a_capture_get_depth_image (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle), k4a_capture_t, capture_handle))
Definition at line 414 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::DecompressCapture().
k4a_capture_get_depth_image() [2/2]
k4a_image_t cloudViewer::io::k4a_plugin::k4a_capture_get_depth_image (k4a_capture_t capture_handle)
k4a_capture_get_ir_image() [1/2]
k4a_image_t cloudViewer::io::k4a_plugin::k4a_capture_get_ir_image (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle), k4a_capture_t, capture_handle))
Definition at line 420 of file K4aPlugin.cpp.
k4a_capture_get_ir_image() [2/2]
k4a_image_t cloudViewer::io::k4a_plugin::k4a_capture_get_ir_image (k4a_capture_t capture_handle)
k4a_capture_get_temperature_c() [1/2]
float cloudViewer::io::k4a_plugin::k4a_capture_get_temperature_c (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle), k4a_capture_t, capture_handle))
Definition at line 458 of file K4aPlugin.cpp.
k4a_capture_get_temperature_c() [2/2]
float cloudViewer::io::k4a_plugin::k4a_capture_get_temperature_c (k4a_capture_t capture_handle)
k4a_capture_reference() [1/2]
void cloudViewer::io::k4a_plugin::k4a_capture_reference (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle), k4a_capture_t, capture_handle))
Definition at line 402 of file K4aPlugin.cpp.
k4a_capture_reference() [2/2]
void cloudViewer::io::k4a_plugin::k4a_capture_reference (k4a_capture_t capture_handle)
k4a_capture_release() [1/2]
void cloudViewer::io::k4a_plugin::k4a_capture_release (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle), k4a_capture_t, capture_handle))
Definition at line 396 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::CaptureFrame(), cloudViewer::io::MKVReader::NextFrame(), and cloudViewer::io::AzureKinectRecorder::RecordFrame().
k4a_capture_release() [2/2]
void cloudViewer::io::k4a_plugin::k4a_capture_release (k4a_capture_t capture_handle)
k4a_capture_set_color_image() [1/2]
void cloudViewer::io::k4a_plugin::k4a_capture_set_color_image (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle, k4a_image_t, image_handle), k4a_capture_t, capture_handle, k4a_image_t, image_handle))
Definition at line 428 of file K4aPlugin.cpp.
k4a_capture_set_color_image() [2/2]
void cloudViewer::io::k4a_plugin::k4a_capture_set_color_image (k4a_capture_t capture_handle, k4a_image_t image_handle)
k4a_capture_set_depth_image() [1/2]
void cloudViewer::io::k4a_plugin::k4a_capture_set_depth_image (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle, k4a_image_t, image_handle), k4a_capture_t, capture_handle, k4a_image_t, image_handle))
Definition at line 436 of file K4aPlugin.cpp.
k4a_capture_set_depth_image() [2/2]
void cloudViewer::io::k4a_plugin::k4a_capture_set_depth_image (k4a_capture_t capture_handle, k4a_image_t image_handle)
k4a_capture_set_ir_image() [1/2]
void cloudViewer::io::k4a_plugin::k4a_capture_set_ir_image (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle, k4a_image_t, image_handle), k4a_capture_t, capture_handle, k4a_image_t, image_handle))
Definition at line 444 of file K4aPlugin.cpp.
k4a_capture_set_ir_image() [2/2]
void cloudViewer::io::k4a_plugin::k4a_capture_set_ir_image (k4a_capture_t capture_handle, k4a_image_t image_handle)
k4a_capture_set_temperature_c() [1/2]
void cloudViewer::io::k4a_plugin::k4a_capture_set_temperature_c (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_capture_t, capture_handle, float, temperature_c), k4a_capture_t, capture_handle, float, temperature_c))
Definition at line 452 of file K4aPlugin.cpp.
k4a_capture_set_temperature_c() [2/2]
void cloudViewer::io::k4a_plugin::k4a_capture_set_temperature_c (k4a_capture_t capture_handle, float temperature_c)
k4a_device_close() [1/2]
void cloudViewer::io::k4a_plugin::k4a_device_close (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle), k4a_device_t, device_handle))
Definition at line 367 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::Connect(), cloudViewer::io::AzureKinectSensor::Disconnect(), and cloudViewer::io::AzureKinectSensor::ListDevices().
k4a_device_close() [2/2]
void cloudViewer::io::k4a_plugin::k4a_device_close (k4a_device_t device_handle)
k4a_device_get_calibration() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_get_calibration (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, const k4a_depth_mode_t, depth_mode, const k4a_color_resolution_t, color_resolution, k4a_calibration_t *, calibration), k4a_device_t, device_handle, const k4a_depth_mode_t, depth_mode, const k4a_color_resolution_t, color_resolution, k4a_calibration_t *, calibration))
Definition at line 693 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::Connect().
k4a_device_get_calibration() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_get_calibration (k4a_device_t device_handle, const k4a_depth_mode_t depth_mode, const k4a_color_resolution_t color_resolution, k4a_calibration_t * calibration)
k4a_device_get_capture() [1/2]
k4a_wait_result_t cloudViewer::io::k4a_plugin::k4a_device_get_capture (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_capture_t *, capture_handle, int32_t, timeout_in_ms), k4a_device_t, device_handle, k4a_capture_t *, capture_handle, int32_t, timeout_in_ms))
Definition at line 377 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::CaptureRawFrame().
k4a_device_get_capture() [2/2]
k4a_wait_result_t cloudViewer::io::k4a_plugin::k4a_device_get_capture (k4a_device_t device_handle, k4a_capture_t * capture_handle, int32_t timeout_in_ms)
k4a_device_get_color_control() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_get_color_control (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_color_control_command_t, command, k4a_color_control_mode_t *, mode, int32_t *, value), k4a_device_t, device_handle, k4a_color_control_command_t, command, k4a_color_control_mode_t *, mode, int32_t *, value))
Definition at line 659 of file K4aPlugin.cpp.
k4a_device_get_color_control() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_get_color_control (k4a_device_t device_handle, k4a_color_control_command_t command, k4a_color_control_mode_t * mode, int32_t * value)
k4a_device_get_color_control_capabilities() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_get_color_control_capabilities (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_color_control_command_t, command, bool *, supports_auto, int32_t *, min_value, int32_t *, max_value, int32_t *, step_value, int32_t *, default_value, k4a_color_control_mode_t *, default_mode), k4a_device_t, device_handle, k4a_color_control_command_t, command, bool *, supports_auto, int32_t *, min_value, int32_t *, max_value, int32_t *, step_value, int32_t *, default_value, k4a_color_control_mode_t *, default_mode))
Definition at line 647 of file K4aPlugin.cpp.
k4a_device_get_color_control_capabilities() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_get_color_control_capabilities (k4a_device_t device_handle, k4a_color_control_command_t command, bool * supports_auto, int32_t * min_value, int32_t * max_value, int32_t * step_value, int32_t * default_value, k4a_color_control_mode_t * default_mode)
k4a_device_get_imu_sample() [1/2]
k4a_wait_result_t cloudViewer::io::k4a_plugin::k4a_device_get_imu_sample (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_imu_sample_t *, imu_sample, int32_t, timeout_in_ms), k4a_device_t, device_handle, k4a_imu_sample_t *, imu_sample, int32_t, timeout_in_ms))
Definition at line 387 of file K4aPlugin.cpp.
k4a_device_get_imu_sample() [2/2]
k4a_wait_result_t cloudViewer::io::k4a_plugin::k4a_device_get_imu_sample (k4a_device_t device_handle, k4a_imu_sample_t * imu_sample, int32_t timeout_in_ms)
k4a_device_get_installed_count() [1/2]
uint32_t cloudViewer::io::k4a_plugin::k4a_device_get_installed_count (EXTRACT_TYPES_PARAMS(COUNT_ARGS(),))
Definition at line 346 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::Connect(), and cloudViewer::io::AzureKinectSensor::ListDevices().
k4a_device_get_installed_count() [2/2]
uint32_t cloudViewer::io::k4a_plugin::k4a_device_get_installed_count (void)
k4a_device_get_raw_calibration() [1/2]
k4a_buffer_result_t cloudViewer::io::k4a_plugin::k4a_device_get_raw_calibration (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, uint8_t *, data, size_t *, data_size), k4a_device_t, device_handle, uint8_t *, data, size_t *, data_size))
Definition at line 681 of file K4aPlugin.cpp.
k4a_device_get_raw_calibration() [2/2]
k4a_buffer_result_t cloudViewer::io::k4a_plugin::k4a_device_get_raw_calibration (k4a_device_t device_handle, uint8_t * data, size_t * data_size)
k4a_device_get_serialnum() [1/2]
k4a_buffer_result_t cloudViewer::io::k4a_plugin::k4a_device_get_serialnum (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, char *, serial_number, size_t *, serial_number_size), k4a_device_t, device_handle, char *, serial_number, size_t *, serial_number_size))
Definition at line 619 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::PrintFirmware().
k4a_device_get_serialnum() [2/2]
k4a_buffer_result_t cloudViewer::io::k4a_plugin::k4a_device_get_serialnum (k4a_device_t device_handle, char * serial_number, size_t * serial_number_size)
k4a_device_get_sync_jack() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_get_sync_jack (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, bool *, sync_in_jack_connected, bool *, sync_out_jack_connected), k4a_device_t, device_handle, bool *, sync_in_jack_connected, bool *, sync_out_jack_connected))
Definition at line 703 of file K4aPlugin.cpp.
k4a_device_get_sync_jack() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_get_sync_jack (k4a_device_t device_handle, bool * sync_in_jack_connected, bool * sync_out_jack_connected)
k4a_device_get_version() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_get_version (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_hardware_version_t *, version), k4a_device_t, device_handle, k4a_hardware_version_t *, version))
Definition at line 627 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::PrintFirmware().
k4a_device_get_version() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_get_version (k4a_device_t device_handle, k4a_hardware_version_t * version)
k4a_device_open() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_open (EXTRACT_TYPES_PARAMS(COUNT_ARGS(uint32_t, index, k4a_device_t *, device_handle), uint32_t, index, k4a_device_t *, device_handle))
Definition at line 364 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::Connect(), and cloudViewer::io::AzureKinectSensor::ListDevices().
k4a_device_open() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_open (uint32_t index, k4a_device_t * device_handle)
k4a_device_set_color_control() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_set_color_control (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_color_control_command_t, command, k4a_color_control_mode_t, mode, int32_t, value), k4a_device_t, device_handle, k4a_color_control_command_t, command, k4a_color_control_mode_t, mode, int32_t, value))
Definition at line 671 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::Connect().
k4a_device_set_color_control() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_set_color_control (k4a_device_t device_handle, k4a_color_control_command_t command, k4a_color_control_mode_t mode, int32_t value)
k4a_device_start_cameras() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_start_cameras (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle, k4a_device_configuration_t *, config), k4a_device_t, device_handle, k4a_device_configuration_t *, config))
Definition at line 594 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::Connect().
k4a_device_start_cameras() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_start_cameras (k4a_device_t device_handle, k4a_device_configuration_t * config)
k4a_device_start_imu() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_start_imu (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle), k4a_device_t, device_handle))
Definition at line 606 of file K4aPlugin.cpp.
k4a_device_start_imu() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_device_start_imu (k4a_device_t device_handle)
k4a_device_stop_cameras() [1/2]
void cloudViewer::io::k4a_plugin::k4a_device_stop_cameras (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle), k4a_device_t, device_handle))
Definition at line 600 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::Disconnect().
k4a_device_stop_cameras() [2/2]
void cloudViewer::io::k4a_plugin::k4a_device_stop_cameras (k4a_device_t device_handle)
k4a_device_stop_imu() [1/2]
void cloudViewer::io::k4a_plugin::k4a_device_stop_imu (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_device_t, device_handle), k4a_device_t, device_handle))
Definition at line 609 of file K4aPlugin.cpp.
k4a_device_stop_imu() [2/2]
void cloudViewer::io::k4a_plugin::k4a_device_stop_imu (k4a_device_t device_handle)
k4a_image_create() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_image_create (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_format_t, format, int, width_pixels, int, height_pixels, int, stride_bytes, k4a_image_t *, image_handle), k4a_image_format_t, format, int, width_pixels, int, height_pixels, int, stride_bytes, k4a_image_t *, image_handle))
Definition at line 472 of file K4aPlugin.cpp.
k4a_image_create() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_image_create (k4a_image_format_t format, int width_pixels, int height_pixels, int stride_bytes, k4a_image_t * image_handle)
k4a_image_create_from_buffer() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_image_create_from_buffer (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_format_t, format, int, width_pixels, int, height_pixels, int, stride_bytes, uint8_t *, buffer, size_t, buffer_size, k4a_memory_destroy_cb_t *, buffer_release_cb, void *, buffer_release_cb_context, k4a_image_t *, image_handle), k4a_image_format_t, format, int, width_pixels, int, height_pixels, int, stride_bytes, uint8_t *, buffer, size_t, buffer_size, k4a_memory_destroy_cb_t *, buffer_release_cb, void *, buffer_release_cb_context, k4a_image_t *, image_handle))
Definition at line 494 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::DecompressCapture().
k4a_image_create_from_buffer() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_image_create_from_buffer (k4a_image_format_t format, int width_pixels, int height_pixels, int stride_bytes, uint8_t * buffer, size_t buffer_size, k4a_memory_destroy_cb_t * buffer_release_cb, void * buffer_release_cb_context, k4a_image_t * image_handle)
k4a_image_get_buffer() [1/2]
uint8_t* cloudViewer::io::k4a_plugin::k4a_image_get_buffer (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
Definition at line 497 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::DecompressCapture().
k4a_image_get_buffer() [2/2]
uint8_t* cloudViewer::io::k4a_plugin::k4a_image_get_buffer (k4a_image_t image_handle)
k4a_image_get_exposure_usec() [1/2]
uint64_t cloudViewer::io::k4a_plugin::k4a_image_get_exposure_usec (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
Definition at line 536 of file K4aPlugin.cpp.
k4a_image_get_exposure_usec() [2/2]
uint64_t cloudViewer::io::k4a_plugin::k4a_image_get_exposure_usec (k4a_image_t image_handle)
k4a_image_get_format() [1/2]
k4a_image_format_t cloudViewer::io::k4a_plugin::k4a_image_get_format (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
Definition at line 506 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::DecompressCapture().
k4a_image_get_format() [2/2]
k4a_image_format_t cloudViewer::io::k4a_plugin::k4a_image_get_format (k4a_image_t image_handle)
k4a_image_get_height_pixels() [1/2]
int cloudViewer::io::k4a_plugin::k4a_image_get_height_pixels (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
Definition at line 518 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::DecompressCapture().
k4a_image_get_height_pixels() [2/2]
int cloudViewer::io::k4a_plugin::k4a_image_get_height_pixels (k4a_image_t image_handle)
k4a_image_get_iso_speed() [1/2]
uint32_t cloudViewer::io::k4a_plugin::k4a_image_get_iso_speed (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
Definition at line 548 of file K4aPlugin.cpp.
k4a_image_get_iso_speed() [2/2]
uint32_t cloudViewer::io::k4a_plugin::k4a_image_get_iso_speed (k4a_image_t image_handle)
k4a_image_get_size() [1/2]
size_t cloudViewer::io::k4a_plugin::k4a_image_get_size (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
Definition at line 500 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::DecompressCapture().
k4a_image_get_size() [2/2]
size_t cloudViewer::io::k4a_plugin::k4a_image_get_size (k4a_image_t image_handle)
k4a_image_get_stride_bytes() [1/2]
int cloudViewer::io::k4a_plugin::k4a_image_get_stride_bytes (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
Definition at line 524 of file K4aPlugin.cpp.
k4a_image_get_stride_bytes() [2/2]
int cloudViewer::io::k4a_plugin::k4a_image_get_stride_bytes (k4a_image_t image_handle)
k4a_image_get_timestamp_usec() [1/2]
uint64_t cloudViewer::io::k4a_plugin::k4a_image_get_timestamp_usec (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
Definition at line 530 of file K4aPlugin.cpp.
k4a_image_get_timestamp_usec() [2/2]
uint64_t cloudViewer::io::k4a_plugin::k4a_image_get_timestamp_usec (k4a_image_t image_handle)
k4a_image_get_white_balance() [1/2]
uint32_t cloudViewer::io::k4a_plugin::k4a_image_get_white_balance (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
Definition at line 542 of file K4aPlugin.cpp.
k4a_image_get_white_balance() [2/2]
uint32_t cloudViewer::io::k4a_plugin::k4a_image_get_white_balance (k4a_image_t image_handle)
k4a_image_get_width_pixels() [1/2]
int cloudViewer::io::k4a_plugin::k4a_image_get_width_pixels (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
Definition at line 512 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::DecompressCapture().
k4a_image_get_width_pixels() [2/2]
int cloudViewer::io::k4a_plugin::k4a_image_get_width_pixels (k4a_image_t image_handle)
k4a_image_reference() [1/2]
void cloudViewer::io::k4a_plugin::k4a_image_reference (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
Definition at line 583 of file K4aPlugin.cpp.
k4a_image_reference() [2/2]
void cloudViewer::io::k4a_plugin::k4a_image_reference (k4a_image_t image_handle)
k4a_image_release() [1/2]
void cloudViewer::io::k4a_plugin::k4a_image_release (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle), k4a_image_t, image_handle))
Definition at line 586 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::DecompressCapture().
k4a_image_release() [2/2]
void cloudViewer::io::k4a_plugin::k4a_image_release (k4a_image_t image_handle)
k4a_image_set_exposure_time_usec() [1/2]
void cloudViewer::io::k4a_plugin::k4a_image_set_exposure_time_usec (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle, uint64_t, exposure_usec), k4a_image_t, image_handle, uint64_t, exposure_usec))
Definition at line 564 of file K4aPlugin.cpp.
k4a_image_set_exposure_time_usec() [2/2]
void cloudViewer::io::k4a_plugin::k4a_image_set_exposure_time_usec (k4a_image_t image_handle, uint64_t exposure_usec)
k4a_image_set_iso_speed() [1/2]
void cloudViewer::io::k4a_plugin::k4a_image_set_iso_speed (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle, uint32_t, iso_speed), k4a_image_t, image_handle, uint32_t, iso_speed))
Definition at line 580 of file K4aPlugin.cpp.
k4a_image_set_iso_speed() [2/2]
void cloudViewer::io::k4a_plugin::k4a_image_set_iso_speed (k4a_image_t image_handle, uint32_t iso_speed)
k4a_image_set_timestamp_usec() [1/2]
void cloudViewer::io::k4a_plugin::k4a_image_set_timestamp_usec (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle, uint64_t, timestamp_usec), k4a_image_t, image_handle, uint64_t, timestamp_usec))
Definition at line 556 of file K4aPlugin.cpp.
k4a_image_set_timestamp_usec() [2/2]
void cloudViewer::io::k4a_plugin::k4a_image_set_timestamp_usec (k4a_image_t image_handle, uint64_t timestamp_usec)
k4a_image_set_white_balance() [1/2]
void cloudViewer::io::k4a_plugin::k4a_image_set_white_balance (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_image_t, image_handle, uint32_t, white_balance), k4a_image_t, image_handle, uint32_t, white_balance))
Definition at line 572 of file K4aPlugin.cpp.
k4a_image_set_white_balance() [2/2]
void cloudViewer::io::k4a_plugin::k4a_image_set_white_balance (k4a_image_t image_handle, uint32_t white_balance)
k4a_playback_close() [1/2]
void cloudViewer::io::k4a_plugin::k4a_playback_close (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle), k4a_playback_t, playback_handle))
Definition at line 342 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::MKVReader::Close().
k4a_playback_close() [2/2]
void cloudViewer::io::k4a_plugin::k4a_playback_close (k4a_playback_t playback_handle)
k4a_playback_get_calibration() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_calibration (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_calibration_t *, calibration), k4a_playback_t, playback_handle, k4a_calibration_t *, calibration))
Definition at line 270 of file K4aPlugin.cpp.
k4a_playback_get_calibration() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_calibration (k4a_playback_t playback_handle, k4a_calibration_t * calibration)
k4a_playback_get_last_timestamp_usec() [1/2]
uint64_t cloudViewer::io::k4a_plugin::k4a_playback_get_last_timestamp_usec (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle), k4a_playback_t, playback_handle))
Definition at line 337 of file K4aPlugin.cpp.
k4a_playback_get_last_timestamp_usec() [2/2]
uint64_t cloudViewer::io::k4a_plugin::k4a_playback_get_last_timestamp_usec (k4a_playback_t playback_handle)
k4a_playback_get_next_capture() [1/2]
k4a_stream_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_next_capture (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_capture_t *, capture_handle), k4a_playback_t, playback_handle, k4a_capture_t *, capture_handle))
Definition at line 302 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::MKVReader::NextFrame().
k4a_playback_get_next_capture() [2/2]
k4a_stream_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_next_capture (k4a_playback_t playback_handle, k4a_capture_t * capture_handle)
k4a_playback_get_next_imu_sample() [1/2]
k4a_stream_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_next_imu_sample (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_imu_sample_t *, imu_sample), k4a_playback_t, playback_handle, k4a_imu_sample_t *, imu_sample))
Definition at line 316 of file K4aPlugin.cpp.
k4a_playback_get_next_imu_sample() [2/2]
k4a_stream_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_next_imu_sample (k4a_playback_t playback_handle, k4a_imu_sample_t * imu_sample)
k4a_playback_get_previous_capture() [1/2]
k4a_stream_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_previous_capture (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_capture_t *, capture_handle), k4a_playback_t, playback_handle, k4a_capture_t *, capture_handle))
Definition at line 309 of file K4aPlugin.cpp.
k4a_playback_get_previous_capture() [2/2]
k4a_stream_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_previous_capture (k4a_playback_t playback_handle, k4a_capture_t * capture_handle)
k4a_playback_get_previous_imu_sample() [1/2]
k4a_stream_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_previous_imu_sample (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_imu_sample_t *, imu_sample), k4a_playback_t, playback_handle, k4a_imu_sample_t *, imu_sample))
Definition at line 323 of file K4aPlugin.cpp.
k4a_playback_get_previous_imu_sample() [2/2]
k4a_stream_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_previous_imu_sample (k4a_playback_t playback_handle, k4a_imu_sample_t * imu_sample)
k4a_playback_get_raw_calibration() [1/2]
k4a_buffer_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_raw_calibration (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, uint8_t *, data, size_t *, data_size), k4a_playback_t, playback_handle, uint8_t *, data, size_t *, data_size))
Definition at line 263 of file K4aPlugin.cpp.
k4a_playback_get_raw_calibration() [2/2]
k4a_buffer_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_raw_calibration (k4a_playback_t playback_handle, uint8_t * data, size_t * data_size)
k4a_playback_get_record_configuration() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_record_configuration (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_record_configuration_t *, config), k4a_playback_t, playback_handle, k4a_record_configuration_t *, config))
Definition at line 277 of file K4aPlugin.cpp.
k4a_playback_get_record_configuration() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_record_configuration (k4a_playback_t playback_handle, k4a_record_configuration_t * config)
k4a_playback_get_tag() [1/2]
k4a_buffer_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_tag (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, const char *, name, char *, value, size_t *, value_size), k4a_playback_t, playback_handle, const char *, name, char *, value, size_t *, value_size))
Definition at line 288 of file K4aPlugin.cpp.
k4a_playback_get_tag() [2/2]
k4a_buffer_result_t cloudViewer::io::k4a_plugin::k4a_playback_get_tag (k4a_playback_t playback_handle, const char * name, char * value, size_t * value_size)
k4a_playback_open() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_playback_open (const char * path, k4a_playback_t * playback_handle)
k4a_playback_open() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_playback_open (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const char *, path, k4a_playback_t *, playback_handle), const char *, path, k4a_playback_t *, playback_handle))
Definition at line 254 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::MKVReader::Open().
k4a_playback_seek_timestamp() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_playback_seek_timestamp (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, int64_t, offset_usec, k4a_playback_seek_origin_t, origin), k4a_playback_t, playback_handle, int64_t, offset_usec, k4a_playback_seek_origin_t, origin))
Definition at line 332 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::MKVReader::SeekTimestamp().
k4a_playback_seek_timestamp() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_playback_seek_timestamp (k4a_playback_t playback_handle, int64_t offset_usec, k4a_playback_seek_origin_t origin)
k4a_playback_set_color_conversion() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_playback_set_color_conversion (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_playback_t, playback_handle, k4a_image_format_t, target_format), k4a_playback_t, playback_handle, k4a_image_format_t, target_format))
Definition at line 295 of file K4aPlugin.cpp.
k4a_playback_set_color_conversion() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_playback_set_color_conversion (k4a_playback_t playback_handle, k4a_image_format_t target_format)
k4a_record_add_imu_track() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_add_imu_track (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle), k4a_record_t, recording_handle))
Definition at line 210 of file K4aPlugin.cpp.
k4a_record_add_imu_track() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_add_imu_track (k4a_record_t recording_handle)
k4a_record_add_tag() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_add_tag (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle, const char *, name, const char *, value), k4a_record_t, recording_handle, const char *, name, const char *, value))
Definition at line 204 of file K4aPlugin.cpp.
k4a_record_add_tag() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_add_tag (k4a_record_t recording_handle, const char * name, const char * value)
k4a_record_close() [1/2]
void cloudViewer::io::k4a_plugin::k4a_record_close (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle), k4a_record_t, recording_handle))
Definition at line 244 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::MKVWriter::Close(), and cloudViewer::io::AzureKinectRecorder::CloseRecord().
k4a_record_close() [2/2]
void cloudViewer::io::k4a_plugin::k4a_record_close (k4a_record_t recording_handle)
k4a_record_create() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_create (const char * path, k4a_device_t device, const k4a_device_configuration_t device_config, k4a_record_t * recording_handle)
k4a_record_create() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_create (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const char *, path, k4a_device_t, device, const k4a_device_configuration_t, device_config, k4a_record_t *, recording_handle), const char *, path, k4a_device_t, device, const k4a_device_configuration_t, device_config, k4a_record_t *, recording_handle))
Definition at line 194 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::MKVWriter::Open(), and cloudViewer::io::AzureKinectRecorder::OpenRecord().
k4a_record_flush() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_flush (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle), k4a_record_t, recording_handle))
Definition at line 238 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::MKVWriter::Close(), and cloudViewer::io::AzureKinectRecorder::CloseRecord().
k4a_record_flush() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_flush (k4a_record_t recording_handle)
k4a_record_write_capture() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_write_capture (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle, k4a_capture_t, capture_handle), k4a_record_t, recording_handle, k4a_capture_t, capture_handle))
Definition at line 224 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::MKVWriter::NextFrame(), and cloudViewer::io::AzureKinectRecorder::RecordFrame().
k4a_record_write_capture() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_write_capture (k4a_record_t recording_handle, k4a_capture_t capture_handle)
k4a_record_write_header() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_write_header (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle), k4a_record_t, recording_handle))
Definition at line 216 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectRecorder::OpenRecord(), and cloudViewer::io::MKVWriter::SetMetadata().
k4a_record_write_header() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_write_header (k4a_record_t recording_handle)
k4a_record_write_imu_sample() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_write_imu_sample (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_record_t, recording_handle, k4a_imu_sample_t, imu_sample), k4a_record_t, recording_handle, k4a_imu_sample_t, imu_sample))
Definition at line 232 of file K4aPlugin.cpp.
k4a_record_write_imu_sample() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_record_write_imu_sample (k4a_record_t recording_handle, k4a_imu_sample_t imu_sample)
k4a_set_debug_message_handler() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_set_debug_message_handler (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_logging_message_cb_t *, message_cb, void *, message_cb_context, k4a_log_level_t, min_level), k4a_logging_message_cb_t *, message_cb, void *, message_cb_context, k4a_log_level_t, min_level))
Definition at line 356 of file K4aPlugin.cpp.
k4a_set_debug_message_handler() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_set_debug_message_handler (k4a_logging_message_cb_t * message_cb, void * message_cb_context, k4a_log_level_t min_level)
k4a_transformation_color_image_to_depth_camera() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_transformation_color_image_to_depth_camera (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_transformation_t, transformation_handle, const k4a_image_t, depth_image, const k4a_image_t, color_image, k4a_image_t, transformed_color_image), k4a_transformation_t, transformation_handle, const k4a_image_t, depth_image, const k4a_image_t, color_image, k4a_image_t, transformed_color_image))
Definition at line 817 of file K4aPlugin.cpp.
k4a_transformation_color_image_to_depth_camera() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_transformation_color_image_to_depth_camera (k4a_transformation_t transformation_handle, const k4a_image_t depth_image, const k4a_image_t color_image, k4a_image_t transformed_color_image)
k4a_transformation_create() [1/2]
k4a_transformation_t cloudViewer::io::k4a_plugin::k4a_transformation_create (const k4a_calibration_t * calibration)
k4a_transformation_create() [2/2]
k4a_transformation_t cloudViewer::io::k4a_plugin::k4a_transformation_create (EXTRACT_TYPES_PARAMS(COUNT_ARGS(const k4a_calibration_t *, calibration), const k4a_calibration_t *, calibration))
Definition at line 789 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::Connect().
k4a_transformation_depth_image_to_color_camera() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_transformation_depth_image_to_color_camera (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_transformation_t, transformation_handle, const k4a_image_t, depth_image, k4a_image_t, transformed_depth_image), k4a_transformation_t, transformation_handle, const k4a_image_t, depth_image, k4a_image_t, transformed_depth_image))
Definition at line 805 of file K4aPlugin.cpp.
Referenced by cloudViewer::io::AzureKinectSensor::DecompressCapture().
k4a_transformation_depth_image_to_color_camera() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_transformation_depth_image_to_color_camera (k4a_transformation_t transformation_handle, const k4a_image_t depth_image, k4a_image_t transformed_depth_image)
k4a_transformation_depth_image_to_point_cloud() [1/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_transformation_depth_image_to_point_cloud (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_transformation_t, transformation_handle, const k4a_image_t, depth_image, const k4a_calibration_type_t, camera, k4a_image_t, xyz_image), k4a_transformation_t, transformation_handle, const k4a_image_t, depth_image, const k4a_calibration_type_t, camera, k4a_image_t, xyz_image))
Definition at line 829 of file K4aPlugin.cpp.
k4a_transformation_depth_image_to_point_cloud() [2/2]
k4a_result_t cloudViewer::io::k4a_plugin::k4a_transformation_depth_image_to_point_cloud (k4a_transformation_t transformation_handle, const k4a_image_t depth_image, const k4a_calibration_type_t camera, k4a_image_t xyz_image)
k4a_transformation_destroy() [1/2]
void cloudViewer::io::k4a_plugin::k4a_transformation_destroy (EXTRACT_TYPES_PARAMS(COUNT_ARGS(k4a_transformation_t, transformation_handle), k4a_transformation_t, transformation_handle))
Definition at line 795 of file K4aPlugin.cpp.
k4a_transformation_destroy() [2/2]
void cloudViewer::io::k4a_plugin::k4a_transformation_destroy (k4a_transformation_t transformation_handle)
Variable Documentation
k4a_lib_name
const std::string cloudViewer::io::k4a_plugin::k4a_lib_name = "libk4a.so" static
Definition at line 105 of file K4aPlugin.cpp.
k4arecord_lib_name
const std::string cloudViewer::io::k4a_plugin::k4arecord_lib_name = "libk4arecord.so" static
Definition at line 106 of file K4aPlugin.cpp.