ACloudViewer: e57 Namespace Reference
e57 Namespace Reference
Namespaces
Utilities
Classes
class E57Exception
Object thrown by E57 API functions to communicate the conditions of an error.
class Node
class StructureNode
class VectorNode
class SourceDestBuffer
class CompressedVectorReader
class CompressedVectorWriter
class CompressedVectorNode
class IntegerNode
class ScaledIntegerNode
class FloatNode
class StringNode
class BlobNode
class ImageFile
struct Translation
Defines a rigid body translation in Cartesian coordinates.
struct Quaternion
Represents a rigid body rotation.
struct RigidBodyTransform
Defines a rigid body transform in cartesian coordinates.
struct CartesianBounds
Specifies an axis-aligned box in local cartesian coordinates.
struct SphericalBounds
Stores the bounds of some data in spherical coordinates.
struct IndexBounds
Stores the minimum and maximum of rowIndex, columnIndex, and returnIndex fields for a set of points.
struct IntensityLimits
Specifies the limits for the value of signal intensity that a sensor is capable of producing.
struct ColorLimits
Specifies the limits for the value of red, green, and blue color that a sensor is capable of producing.
struct DateTime
Encodes date and time.
struct E57Root
Stores the top-level information for the XML section of the file.
struct LineGroupRecord
Stores information about a single group of points in a row or column.
struct GroupingByLine
Stores a set of point groups organized by the rowIndex or columnIndex attribute of the PointRecord.
struct PointGroupingSchemes
Supports the division of points within an Data3D into logical groupings.
struct PointStandardizedFieldsAvailable
Used to interrogate if standardized fields are available.
struct Data3D
Stores the top-level information for a single lidar scan.
struct Data3DPointsData_t
Stores pointers to user-provided buffers.
struct VisualReferenceRepresentation
Stores an image that is to be used only as a visual reference.
struct PinholeRepresentation
Stores an image that is mapped from 3D using the pinhole camera projection model.
struct SphericalRepresentation
Stores an image that is mapped from 3D using a spherical projection model.
struct CylindricalRepresentation
Stores an image that is mapped from 3D using a cylindrical projection model.
struct Image2D
Stores an image from a camera.
class Reader
Used for reading of the E57 file with E57 Simple API.
class Writer
Used for writing of the E57 file with E57 Simple API.
class BlobNodeImpl
class BufferView
class CheckedFile
class CompressedVectorNodeImpl
class CompressedVectorReaderImpl
struct SortByBytestreamNumber
class CompressedVectorWriterImpl
struct DecodeChannel
class Decoder
class BitpackDecoder
class BitpackFloatDecoder
class BitpackStringDecoder
class BitpackIntegerDecoder
class ConstantIntegerDecoder
class E57XmlParser
class E57XmlFileInputSource
class Encoder
class BitpackEncoder
class BitpackFloatEncoder
class BitpackStringEncoder
class BitpackIntegerEncoder
class ConstantIntegerEncoder
class FloatNodeImpl
struct NameSpace
struct E57FileHeader
class ImageFileImpl
class IntegerNodeImpl
class NodeImpl
class PacketReadCache
class PacketLock
class DataPacketHeader
class DataPacket
class ReaderImpl
most of the functions follows Reader
class ScaledIntegerNodeImpl
struct BlobSectionHeader
struct CompressedVectorSectionHeader
class SourceDestBufferImpl
class StringNodeImpl
class StructureNodeImpl
class VectorNodeImpl
class WriterImpl
most of the functions follows Writer
Typedefs
using ustring = std::string
UTF-8 encodeded Unicode string.
using ReadChecksumPolicy = int
Specifies the percentage of checksums which are verified when reading an ImageFile (0-100%).
typedef Data3DPointsData_t< float > Data3DPointsData
typedef Data3DPointsData_t< double > Data3DPointsData_d
using ImageFileImplSharedPtr = std::shared_ptr< class ImageFileImpl >
using ImageFileImplWeakPtr = std::weak_ptr< class ImageFileImpl >
using NodeImplSharedPtr = std::shared_ptr< class NodeImpl >
using NodeImplWeakPtr = std::weak_ptr< class NodeImpl >
using StringList = std::vector< std::string >
using StringSet = std::set< std::string >
Enumerations
enum ErrorCode {
E57_SUCCESS = 0 , E57_ERROR_BAD_CV_HEADER = 1 , E57_ERROR_BAD_CV_PACKET = 2 , E57_ERROR_CHILD_INDEX_OUT_OF_BOUNDS = 3 ,
E57_ERROR_SET_TWICE = 4 , E57_ERROR_HOMOGENEOUS_VIOLATION = 5 , E57_ERROR_VALUE_NOT_REPRESENTABLE = 6 , E57_ERROR_SCALED_VALUE_NOT_REPRESENTABLE = 7 ,
E57_ERROR_REAL64_TOO_LARGE = 8 , E57_ERROR_EXPECTING_NUMERIC = 9 , E57_ERROR_EXPECTING_USTRING = 10 , E57_ERROR_INTERNAL = 11 ,
E57_ERROR_BAD_XML_FORMAT = 12 , E57_ERROR_XML_PARSER = 13 , E57_ERROR_BAD_API_ARGUMENT = 14 , E57_ERROR_FILE_IS_READ_ONLY = 15 ,
E57_ERROR_BAD_CHECKSUM = 16 , E57_ERROR_OPEN_FAILED = 17 , E57_ERROR_CLOSE_FAILED = 18 , E57_ERROR_READ_FAILED = 19 ,
E57_ERROR_WRITE_FAILED = 20 , E57_ERROR_LSEEK_FAILED = 21 , E57_ERROR_PATH_UNDEFINED = 22 , E57_ERROR_BAD_BUFFER = 23 ,
E57_ERROR_NO_BUFFER_FOR_ELEMENT = 24 , E57_ERROR_BUFFER_SIZE_MISMATCH = 25 , E57_ERROR_BUFFER_DUPLICATE_PATHNAME = 26 , E57_ERROR_BAD_FILE_SIGNATURE = 27 ,
E57_ERROR_UNKNOWN_FILE_VERSION = 28 , E57_ERROR_BAD_FILE_LENGTH = 29 , E57_ERROR_XML_PARSER_INIT = 30 , E57_ERROR_DUPLICATE_NAMESPACE_PREFIX = 31 ,
E57_ERROR_DUPLICATE_NAMESPACE_URI = 32 , E57_ERROR_BAD_PROTOTYPE = 33 , E57_ERROR_BAD_CODECS = 34 , E57_ERROR_VALUE_OUT_OF_BOUNDS = 35 ,
E57_ERROR_CONVERSION_REQUIRED = 36 , E57_ERROR_BAD_PATH_NAME = 37 , E57_ERROR_NOT_IMPLEMENTED = 38 , E57_ERROR_BAD_NODE_DOWNCAST = 39 ,
E57_ERROR_WRITER_NOT_OPEN = 40 , E57_ERROR_READER_NOT_OPEN = 41 , E57_ERROR_NODE_UNATTACHED = 42 , E57_ERROR_ALREADY_HAS_PARENT = 43 ,
E57_ERROR_DIFFERENT_DEST_IMAGEFILE = 44 , E57_ERROR_IMAGEFILE_NOT_OPEN = 45 , E57_ERROR_BUFFERS_NOT_COMPATIBLE = 46 , E57_ERROR_TOO_MANY_WRITERS = 47 ,
E57_ERROR_TOO_MANY_READERS = 48 , E57_ERROR_BAD_CONFIGURATION = 49 , E57_ERROR_INVARIANCE_VIOLATION = 50
}
Numeric error identifiers used in E57Exception.
enum NodeType {
E57_STRUCTURE = 1 , E57_VECTOR = 2 , E57_COMPRESSED_VECTOR = 3 , E57_INTEGER = 4 ,
E57_SCALED_INTEGER = 5 , E57_FLOAT = 6 , E57_STRING = 7 , E57_BLOB = 8
}
Identifiers for types of E57 elements.
enum FloatPrecision { E57_SINGLE = 1 , E57_DOUBLE = 2 }
The IEEE floating point number precisions supported.
enum MemoryRepresentation {
E57_INT8 = 1 , E57_UINT8 = 2 , E57_INT16 = 3 , E57_UINT16 = 4 ,
E57_INT32 = 5 , E57_UINT32 = 6 , E57_INT64 = 7 , E57_BOOL = 8 ,
E57_REAL32 = 9 , E57_REAL64 = 10 , E57_USTRING = 11
}
Identifies the representations of memory elements API can transfer data to/from.
enum Image2DType { E57_NO_IMAGE = 0 , E57_JPEG_IMAGE = 1 , E57_PNG_IMAGE = 2 , E57_PNG_IMAGE_MASK = 3 }
Identifies the format representation for the image data.
enum Image2DProjection {
E57_NO_PROJECTION = 0 , E57_VISUAL = 1 , E57_PINHOLE = 2 , E57_SPHERICAL = 3 ,
E57_CYLINDRICAL = 4
}
Identifies the representation for the image data.
enum { INDEX_PACKET = 0 , DATA_PACKET , EMPTY_PACKET }
Packet types (in a compressed vector section)
enum { BLOB_SECTION = 0 , COMPRESSED_VECTOR_SECTION }
Functions
std::string generateRandomGUID ()
generates a new random GUID
std::string space (size_t n)
template<class T >
std::string toString (T x)
std::string hexString (uint64_t x)
std::string hexString (uint32_t x)
std::string hexString (uint16_t x)
std::string hexString (uint8_t x)
std::string binaryString (uint64_t x)
std::string binaryString (uint32_t x)
std::string binaryString (uint16_t x)
std::string binaryString (uint8_t x)
std::string hexString (int64_t x)
std::string hexString (int32_t x)
std::string hexString (int16_t x)
std::string hexString (int8_t x)
std::string binaryString (int64_t x)
std::string binaryString (int32_t x)
std::string binaryString (int16_t x)
std::string binaryString (int8_t x)
bool _alreadyReadPacket (const DecodeChannel &channel, uint64_t currentPacketLogicalOffset)
Variables
constexpr ReadChecksumPolicy CHECKSUM_POLICY_NONE = 0
constexpr ReadChecksumPolicy CHECKSUM_POLICY_SPARSE
Do not verify the checksums. (fast)
constexpr ReadChecksumPolicy CHECKSUM_POLICY_HALF
Only verify 25% of the checksums. The last block is always verified.
constexpr ReadChecksumPolicy CHECKSUM_POLICY_ALL = 100
Only verify 50% of the checksums. The last block is always verified.
constexpr char E57_V1_0_URI [] = "http://www.astm.org/COMMIT/E57/2010-e57-v1.0"
Verify all checksums. This is the default. (slow)
constexpr double E57_NOT_SCALED_USE_FLOAT = 0.
Indicates to use FloatNode instead of ScaledIntegerNode in fields that can use both.
constexpr double E57_NOT_SCALED_USE_INTEGER = -1.
Indicates to use ScaledIntegerNode insterad of FloatNode in fields that can use both.
constexpr uint32_t E57_FORMAT_MAJOR = 1
Version numbers of ASTM standard that this library supports.
constexpr uint32_t E57_FORMAT_MINOR = 0
constexpr int DATA_PACKET_MAX = (64 * 1024)
maximum size of CompressedVector binary data packet
Typedef Documentation
Data3DPointsData
typedef Data3DPointsData_t<float> e57::Data3DPointsData
Definition at line 497 of file E57SimpleData.h.
Data3DPointsData_d
typedef Data3DPointsData_t<double> e57::Data3DPointsData_d
Definition at line 498 of file E57SimpleData.h.
ImageFileImplSharedPtr
using e57::ImageFileImplSharedPtr = typedef std::shared_ptr<class ImageFileImpl>
Definition at line 188 of file Common.h.
ImageFileImplWeakPtr
using e57::ImageFileImplWeakPtr = typedef std::weak_ptr<class ImageFileImpl>
Definition at line 189 of file Common.h.
NodeImplSharedPtr
using e57::NodeImplSharedPtr = typedef std::shared_ptr<class NodeImpl>
Definition at line 190 of file Common.h.
NodeImplWeakPtr
using e57::NodeImplWeakPtr = typedef std::weak_ptr<class NodeImpl>
Definition at line 191 of file Common.h.
ReadChecksumPolicy
using e57::ReadChecksumPolicy = typedef int
Specifies the percentage of checksums which are verified when reading an ImageFile (0-100%).
Definition at line 95 of file E57Format.h.
StringList
using e57::StringList = typedef std::vector<std::string>
Definition at line 193 of file Common.h.
StringSet
using e57::StringSet = typedef std::set<std::string>
Definition at line 194 of file Common.h.
ustring
using e57::ustring = typedef std::string
UTF-8 encodeded Unicode string.
Definition at line 54 of file E57Format.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Packet types (in a compressed vector section)
Enumerator
INDEX_PACKET
DATA_PACKET
EMPTY_PACKET
Definition at line 41 of file Packet.h.
anonymous enum
anonymous enum
Enumerator
BLOB_SECTION
COMPRESSED_VECTOR_SECTION
Definition at line 33 of file SectionHeaders.h.
ErrorCode
enum e57::ErrorCode
Numeric error identifiers used in E57Exception.
Enumerator
E57_SUCCESS
operation was successful
E57_ERROR_BAD_CV_HEADER
a CompressedVector binary header was bad
E57_ERROR_BAD_CV_PACKET
a CompressedVector binary packet was bad
E57_ERROR_CHILD_INDEX_OUT_OF_BOUNDS
a numerical index identifying a child was out of bounds
E57_ERROR_SET_TWICE
attempted to set an existing child element to a new value
E57_ERROR_HOMOGENEOUS_VIOLATION
attempted to add an E57 Element that would have made the children of a homogenous Vector have different types
E57_ERROR_VALUE_NOT_REPRESENTABLE
a value could not be represented in the requested type
E57_ERROR_SCALED_VALUE_NOT_REPRESENTABLE
after scaling the result could not be represented in the requested type
E57_ERROR_REAL64_TOO_LARGE
a 64 bit IEEE float was too large to store in a 32 bit IEEE float
E57_ERROR_EXPECTING_NUMERIC
Expecting numeric representation in user's buffer, found ustring.
E57_ERROR_EXPECTING_USTRING
Expecting string representation in user's buffer, found numeric.
E57_ERROR_INTERNAL
An unrecoverable inconsistent internal state was detected.
E57_ERROR_BAD_XML_FORMAT
E57 primitive not encoded in XML correctly.
E57_ERROR_XML_PARSER
XML not well formed.
E57_ERROR_BAD_API_ARGUMENT
bad API function argument provided by user
E57_ERROR_FILE_IS_READ_ONLY
can't modify read only file
E57_ERROR_BAD_CHECKSUM
checksum mismatch, file is corrupted
E57_ERROR_OPEN_FAILED
open() failed
E57_ERROR_CLOSE_FAILED
close() failed
E57_ERROR_READ_FAILED
read() failed
E57_ERROR_WRITE_FAILED
write() failed
E57_ERROR_LSEEK_FAILED
lseek() failed
E57_ERROR_PATH_UNDEFINED
E57 element path well formed but not defined.
E57_ERROR_BAD_BUFFER
bad SourceDestBuffer
E57_ERROR_NO_BUFFER_FOR_ELEMENT
no buffer specified for an element in CompressedVectorNode during write
E57_ERROR_BUFFER_SIZE_MISMATCH
SourceDestBuffers not all same size.
E57_ERROR_BUFFER_DUPLICATE_PATHNAME
duplicate pathname in CompressedVectorNode read/write
E57_ERROR_BAD_FILE_SIGNATURE
file signature not "ASTM-E57"
E57_ERROR_UNKNOWN_FILE_VERSION
incompatible file version
E57_ERROR_BAD_FILE_LENGTH
size in file header not same as actual
E57_ERROR_XML_PARSER_INIT
XML parser failed to initialize.
E57_ERROR_DUPLICATE_NAMESPACE_PREFIX
namespace prefix already defined
E57_ERROR_DUPLICATE_NAMESPACE_URI
namespace URI already defined
E57_ERROR_BAD_PROTOTYPE
bad prototype in CompressedVectorNode
E57_ERROR_BAD_CODECS
bad codecs in CompressedVectorNode
E57_ERROR_VALUE_OUT_OF_BOUNDS
element value out of min/max bounds
E57_ERROR_CONVERSION_REQUIRED
conversion required to assign element value, but not requested
E57_ERROR_BAD_PATH_NAME
E57 path name is not well formed.
E57_ERROR_NOT_IMPLEMENTED
functionality not implemented
E57_ERROR_BAD_NODE_DOWNCAST
bad downcast from Node to specific node type
E57_ERROR_WRITER_NOT_OPEN
CompressedVectorWriter is no longer open.
E57_ERROR_READER_NOT_OPEN
CompressedVectorReader is no longer open.
E57_ERROR_NODE_UNATTACHED
node is not yet attached to tree of ImageFile
E57_ERROR_ALREADY_HAS_PARENT
node already has a parent
E57_ERROR_DIFFERENT_DEST_IMAGEFILE
nodes were constructed with different destImageFiles
E57_ERROR_IMAGEFILE_NOT_OPEN
destImageFile is no longer open
E57_ERROR_BUFFERS_NOT_COMPATIBLE
SourceDestBuffers not compatible with previously given ones.
E57_ERROR_TOO_MANY_WRITERS
too many open CompressedVectorWriters of an ImageFile
E57_ERROR_TOO_MANY_READERS
too many open CompressedVectorReaders of an ImageFile
E57_ERROR_BAD_CONFIGURATION
bad configuration string
E57_ERROR_INVARIANCE_VIOLATION
class invariance constraint violation in debug mode
Definition at line 39 of file E57Exception.h.
FloatPrecision
enum e57::FloatPrecision
The IEEE floating point number precisions supported.
Enumerator
E57_SINGLE
32 bit IEEE floating point number format
E57_DOUBLE
64 bit IEEE floating point number format
Definition at line 70 of file E57Format.h.
Image2DProjection
enum e57::Image2DProjection
Identifies the representation for the image data.
Enumerator
E57_NO_PROJECTION
No representation for the image data is present.
E57_VISUAL
VisualReferenceRepresentation for the image data.
E57_PINHOLE
PinholeRepresentation for the image data.
E57_SPHERICAL
SphericalRepresentation for the image data.
E57_CYLINDRICAL
CylindricalRepresentation for the image data.
Definition at line 644 of file E57SimpleData.h.
Image2DType
enum e57::Image2DType
Identifies the format representation for the image data.
Enumerator
E57_NO_IMAGE
No image data.
E57_JPEG_IMAGE
JPEG format image data.
E57_PNG_IMAGE
PNG format image data.
E57_PNG_IMAGE_MASK
PNG format image mask.
Definition at line 635 of file E57SimpleData.h.
MemoryRepresentation
enum e57::MemoryRepresentation
Identifies the representations of memory elements API can transfer data to/from.
Enumerator
E57_INT8
8 bit signed integer
E57_UINT8
8 bit unsigned integer
E57_INT16
16 bit signed integer
E57_UINT16
16 bit unsigned integer
E57_INT32
32 bit signed integer
E57_UINT32
32 bit unsigned integer
E57_INT64
64 bit signed integer
E57_BOOL
C++ boolean type.
E57_REAL32
C++ float type.
E57_REAL64
C++ double type.
E57_USTRING
Unicode UTF-8 std::string.
Definition at line 78 of file E57Format.h.
NodeType
enum e57::NodeType
Identifiers for types of E57 elements.
Enumerator
E57_STRUCTURE
StructureNode class.
E57_VECTOR
VectorNode class.
E57_COMPRESSED_VECTOR
CompressedVectorNode class.
E57_INTEGER
IntegerNode class.
E57_SCALED_INTEGER
ScaledIntegerNode class.
E57_FLOAT
FloatNode class.
E57_STRING
StringNode class.
E57_BLOB
BlobNode class.
Definition at line 57 of file E57Format.h.
Function Documentation
_alreadyReadPacket()
bool e57::_alreadyReadPacket (const DecodeChannel & channel, uint64_t currentPacketLogicalOffset) inline
Definition at line 330 of file CompressedVectorReaderImpl.cpp.
References e57::DecodeChannel::currentPacketLogicalOffset, and e57::DecodeChannel::isOutputBlocked().
binaryString() [1/8]
std::string e57::binaryString (int16_t x) inline
Definition at line 179 of file Common.h.
References binaryString().
binaryString() [2/8]
std::string e57::binaryString (int32_t x) inline
Definition at line 175 of file Common.h.
References binaryString().
binaryString() [3/8]
std::string e57::binaryString (int64_t x) inline
Definition at line 171 of file Common.h.
References binaryString().
binaryString() [4/8]
std::string e57::binaryString (int8_t x) inline
Definition at line 183 of file Common.h.
References binaryString().
binaryString() [5/8]
std::string e57::binaryString (uint16_t x) inline
Definition at line 133 of file Common.h.
binaryString() [6/8]
std::string e57::binaryString (uint32_t x) inline
Definition at line 122 of file Common.h.
binaryString() [7/8]
std::string e57::binaryString (uint64_t x) inline
Definition at line 111 of file Common.h.
Referenced by binaryString(), e57::BitpackIntegerEncoder< RegisterT >::dump(), e57::BitpackIntegerDecoder< RegisterT >::dump(), e57::BitpackIntegerDecoder< RegisterT >::inputProcessAligned(), and e57::BitpackIntegerEncoder< RegisterT >::processRecords().
binaryString() [8/8]
std::string e57::binaryString (uint8_t x) inline
Definition at line 144 of file Common.h.
generateRandomGUID()
std::string e57::generateRandomGUID ()
generates a new random GUID
Definition at line 11 of file Common.cpp.
Referenced by e57::WriterImpl::NewData3D(), e57::WriterImpl::NewImage2D(), and e57::WriterImpl::WriterImpl().
hexString() [1/8]
std::string e57::hexString (int16_t x) inline
Definition at line 163 of file Common.h.
References hexString().
hexString() [2/8]
std::string e57::hexString (int32_t x) inline
Definition at line 159 of file Common.h.
References hexString().
hexString() [3/8]
std::string e57::hexString (int64_t x) inline
Definition at line 155 of file Common.h.
References hexString().
hexString() [4/8]
std::string e57::hexString (int8_t x) inline
Definition at line 167 of file Common.h.
References hexString().
hexString() [5/8]
std::string e57::hexString (uint16_t x) inline
Definition at line 99 of file Common.h.
hexString() [6/8]
std::string e57::hexString (uint32_t x) inline
Definition at line 93 of file Common.h.
hexString() [7/8]
std::string e57::hexString (uint64_t x) inline
Definition at line 87 of file Common.h.
Referenced by e57::BitpackIntegerEncoder< RegisterT >::dump(), e57::BitpackIntegerDecoder< RegisterT >::dump(), hexString(), and e57::BitpackIntegerEncoder< RegisterT >::processRecords().
hexString() [8/8]
std::string e57::hexString (uint8_t x) inline
Definition at line 105 of file Common.h.
space()
std::string e57::space (size_t n) inline
Create whitespace of given length, for indenting printouts in dump() functions
Definition at line 73 of file Common.h.
Referenced by e57::CompressedVectorReaderImpl::dump(), e57::CompressedVectorWriterImpl::dump(), e57::DecodeChannel::dump(), e57::PacketReadCache::dump(), e57::BlobSectionHeader::dump(), e57::SourceDestBufferImpl::dump(), e57::Encoder::dump(), e57::E57FileHeader::dump(), e57::ImageFileImpl::dump(), e57::NodeImpl::dump(), IndexPacket::dump(), EmptyPacketHeader::dump(), e57::DataPacketHeader::dump(), e57::DataPacket::dump(), e57::CompressedVectorSectionHeader::dump(), e57::BlobNodeImpl::dump(), e57::CompressedVectorNodeImpl::dump(), e57::BitpackEncoder::dump(), e57::BitpackFloatEncoder::dump(), e57::BitpackStringEncoder::dump(), e57::BitpackIntegerEncoder< RegisterT >::dump(), e57::ConstantIntegerEncoder::dump(), e57::FloatNodeImpl::dump(), e57::IntegerNodeImpl::dump(), e57::ScaledIntegerNodeImpl::dump(), e57::StringNodeImpl::dump(), e57::StructureNodeImpl::dump(), e57::VectorNodeImpl::dump(), e57::BitpackDecoder::dump(), e57::BitpackFloatDecoder::dump(), e57::BitpackStringDecoder::dump(), e57::BitpackIntegerDecoder< RegisterT >::dump(), e57::ConstantIntegerDecoder::dump(), CodeEditor::lineNumberAreaWidth(), e57::BlobNodeImpl::writeXml(), e57::CompressedVectorNodeImpl::writeXml(), e57::FloatNodeImpl::writeXml(), e57::IntegerNodeImpl::writeXml(), e57::ScaledIntegerNodeImpl::writeXml(), e57::StringNodeImpl::writeXml(), e57::StructureNodeImpl::writeXml(), and e57::VectorNodeImpl::writeXml().
toString()
template<class T > std::string e57::toString (T x)
Convert number to decimal, hexadecimal, and binary strings (Note hex strings don't have leading zeros).
Definition at line 80 of file Common.h.
Referenced by e57::BlobNode::BlobNode(), e57::NodeImpl::checkBuffers(), e57::SourceDestBufferImpl::checkCompatible(), e57::CheckedFile::close(), e57::CompressedVectorNode::CompressedVectorNode(), e57::CompressedVectorReaderImpl::CompressedVectorReaderImpl(), e57::CompressedVectorWriterImpl::CompressedVectorWriterImpl(), DecodeCamera(), e57::Decoder::DecoderFactory(), e57::ImageFileImpl::decrReaderCount(), e57::ImageFileImpl::decrWriterCount(), e57::BitpackDecoder::destBufferSetNew(), e57::ConstantIntegerDecoder::destBufferSetNew(), e57::PacketReadCache::dump(), e57::DataPacket::dump(), e57::Encoder::EncoderFactory(), JsonRPCPlugin::execute(), e57::CheckedFile::extend(), ccPropertiesTreeDelegate::fillWithCCArray(), ccPropertiesTreeDelegate::fillWithFacet(), ccPropertiesTreeDelegate::fillWithMesh(), ccPropertiesTreeDelegate::fillWithPointCloud(), ccPropertiesTreeDelegate::fillWithPointOctree(), ccPropertiesTreeDelegate::fillWithPolyline(), e57::FloatNode::FloatNode(), e57::FloatNodeImpl::FloatNodeImpl(), ccRasterizeTool::generateImage(), ccRasterizeTool::generateRaster(), e57::StructureNodeImpl::get(), e57::DataPacket::getBytestream(), ccCommandLineParser::getExportFilename(), e57::SourceDestBufferImpl::getNextFloat(), e57::SourceDestBufferImpl::getNextInt64(), GetPythonExeVersion(), ccColorScaleEditorDialog::importScale(), e57::BitpackDecoder::inBufferShiftDown(), e57::BitpackDecoder::inputProcess(), e57::BitpackFloatDecoder::inputProcessAligned(), e57::BitpackStringDecoder::inputProcessAligned(), e57::BitpackIntegerDecoder< RegisterT >::inputProcessAligned(), e57::IntegerNode::IntegerNode(), e57::IntegerNodeImpl::IntegerNodeImpl(), PhotoScanFilter::loadFile(), e57::PacketReadCache::lock(), IoUtils::newCCMeshFromAIMesh(), e57::BitpackEncoder::outBufferShiftDown(), e57::BitpackEncoder::outputRead(), e57::ConstantIntegerEncoder::outputRead(), e57::PacketReadCache::PacketReadCache(), CommandMatchBestFitPlane::process(), CommandICP::process(), CommandVolume25D::process(), e57::BitpackFloatEncoder::processRecords(), e57::BitpackStringEncoder::processRecords(), e57::BitpackIntegerEncoder< RegisterT >::processRecords(), e57::ConstantIntegerEncoder::processRecords(), e57::CompressedVectorReaderImpl::read(), e57::CheckedFile::read(), e57::BlobNodeImpl::read(), e57::CompressedVectorNodeImpl::reader(), e57::PacketReadCache::readPacket(), readRecentFiles(), MAFilter::saveToFile(), e57::ScaledIntegerNode::ScaledIntegerNode(), e57::ScaledIntegerNodeImpl::ScaledIntegerNodeImpl(), e57::StructureNodeImpl::set(), LasOpenDialog::setInfo(), LASOpenDlg::setInfos(), e57::SourceDestBufferImpl::setNextInt64(), e57::BitpackEncoder::sourceBufferSetNew(), e57::ConstantIntegerEncoder::sourceBufferSetNew(), e57::StringNode::StringNode(), e57::StructureNode::StructureNode(), e57::PacketReadCache::unlock(), e57::VectorNode::VectorNode(), e57::CompressedVectorSectionHeader::verify(), EmptyPacketHeader::verify(), e57::DataPacketHeader::verify(), e57::DataPacket::verify(), IndexPacket::verify(), e57::CompressedVectorWriterImpl::write(), e57::BlobNodeImpl::write(), and e57::CompressedVectorNodeImpl::writer().
Variable Documentation
CHECKSUM_POLICY_ALL
constexpr ReadChecksumPolicy e57::CHECKSUM_POLICY_ALL = 100 constexpr
Only verify 50% of the checksums. The last block is always verified.
Definition at line 102 of file E57Format.h.
Referenced by e57::CheckedFile::read().
CHECKSUM_POLICY_HALF
constexpr ReadChecksumPolicy e57::CHECKSUM_POLICY_HALF constexpr
Initial value:
=
      50
Only verify 25% of the checksums. The last block is always verified.
Definition at line 100 of file E57Format.h.
CHECKSUM_POLICY_NONE
constexpr ReadChecksumPolicy e57::CHECKSUM_POLICY_NONE = 0 constexpr
Definition at line 97 of file E57Format.h.
Referenced by e57::CheckedFile::read().
CHECKSUM_POLICY_SPARSE
constexpr ReadChecksumPolicy e57::CHECKSUM_POLICY_SPARSE constexpr
Initial value:
=
      25
Do not verify the checksums. (fast)
Definition at line 98 of file E57Format.h.
Referenced by E57Filter::loadFile().
DATA_PACKET_MAX
constexpr int e57::DATA_PACKET_MAX = (64 * 1024) constexpr
maximum size of CompressedVector binary data packet
Definition at line 49 of file Packet.h.
Referenced by e57::DataPacket::dump(), e57::Encoder::EncoderFactory(), e57::PacketReadCache::readPacket(), and e57::CompressedVectorWriterImpl::write().
E57_FORMAT_MAJOR
constexpr uint32_t e57::E57_FORMAT_MAJOR = 1 constexpr
Version numbers of ASTM standard that this library supports.
Definition at line 10 of file E57Version.h.
Referenced by e57::ImageFileImpl::close(), and e57::Utilities::getVersions().
E57_FORMAT_MINOR
constexpr uint32_t e57::E57_FORMAT_MINOR = 0 constexpr
Definition at line 11 of file E57Version.h.
Referenced by e57::ImageFileImpl::close(), and e57::Utilities::getVersions().
E57_NOT_SCALED_USE_FLOAT
constexpr double e57::E57_NOT_SCALED_USE_FLOAT = 0. constexpr
Indicates to use FloatNode instead of ScaledIntegerNode in fields that can use both.
Definition at line 40 of file E57SimpleData.h.
Referenced by e57::ReaderImpl::ReadData3D().
E57_NOT_SCALED_USE_INTEGER
constexpr double e57::E57_NOT_SCALED_USE_INTEGER = -1. constexpr
Indicates to use ScaledIntegerNode insterad of FloatNode in fields that can use both.
Definition at line 42 of file E57SimpleData.h.
Referenced by e57::ReaderImpl::ReadData3D().
E57_V1_0_URI
constexpr char e57::E57_V1_0_URI[] = "http://www.astm.org/COMMIT/E57/2010-e57-v1.0" constexpr
Verify all checksums. This is the default. (slow)
The URI of ASTM E57 v1.0 standard XML namespace Note that even though this URI does not point to a valid document, the standard (section 8.4.2.3) says that this is the required namespace.
Definition at line 107 of file E57Format.h.
Referenced by E57Filter::saveToFile(), e57::WriterImpl::WriterImpl(), and e57::StructureNodeImpl::writeXml().