ACloudViewer: cloudViewer::t::geometry::kernel::voxel_grid Namespace Reference
cloudViewer::t::geometry::kernel::voxel_grid Namespace Reference
Classes
struct Coord3i
struct Coord3iHash
struct MiniVecCache
Typedefs
using index_t = int
using ArrayIndexer = TArrayIndexer< index_t >
Functions
void PointCloudTouch (std::shared_ptr< core::HashMap > &hashmap, const core::Tensor &points, core::Tensor &voxel_block_coords, index_t voxel_grid_resolution, float voxel_size, float sdf_trunc)
void DepthTouch (std::shared_ptr< core::HashMap > &hashmap, const core::Tensor &depth, const core::Tensor &intrinsic, const core::Tensor &extrinsic, core::Tensor &voxel_block_coords, index_t voxel_grid_resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max, index_t stride)
void GetVoxelCoordinatesAndFlattenedIndices (const core::Tensor &buf_indices, const core::Tensor &block_keys, core::Tensor &voxel_coords, core::Tensor &flattened_indices, index_t block_resolution, float voxel_size)
void Integrate (const core::Tensor &depth, const core::Tensor &color, const core::Tensor &block_indices, const core::Tensor &block_keys, TensorMap &block_value_map, const core::Tensor &depth_intrinsic, const core::Tensor &color_intrinsic, const core::Tensor &extrinsic, index_t resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max)
void EstimateRange (const core::Tensor &block_keys, core::Tensor &range_minmax_map, const core::Tensor &intrinsics, const core::Tensor &extrinsics, int h, int w, int down_factor, int64_t block_resolution, float voxel_size, float depth_min, float depth_max, core::Tensor &fragment_buffer)
void RayCast (std::shared_ptr< core::HashMap > &hashmap, const TensorMap &block_value_map, const core::Tensor &range_map, TensorMap &renderings_map, const core::Tensor &intrinsic, const core::Tensor &extrinsic, index_t h, index_t w, index_t block_resolution, float voxel_size, float depth_scale, float depth_min, float depth_max, float weight_threshold, float trunc_voxel_multiplier, int range_map_down_factor)
void ExtractPointCloud (const core::Tensor &block_indices, const core::Tensor &nb_block_indices, const core::Tensor &nb_block_masks, const core::Tensor &block_keys, const TensorMap &block_value_map, core::Tensor &points, core::Tensor &normals, core::Tensor &colors, index_t block_resolution, float voxel_size, float weight_threshold, int &valid_size)
void ExtractTriangleMesh (const core::Tensor &block_indices, const core::Tensor &inv_block_indices, const core::Tensor &nb_block_indices, const core::Tensor &nb_block_masks, const core::Tensor &block_keys, const TensorMap &block_value_map, core::Tensor &vertices, core::Tensor &triangles, core::Tensor &vertex_normals, core::Tensor &vertex_colors, index_t block_resolution, float voxel_size, float weight_threshold, int &vertex_count)
void PointCloudTouchCPU (std::shared_ptr< core::HashMap > &hashmap, const core::Tensor &points, core::Tensor &voxel_block_coords, index_t voxel_grid_resolution, float voxel_size, float sdf_trunc)
CPU.
void DepthTouchCPU (std::shared_ptr< core::HashMap > &hashmap, const core::Tensor &depth, const core::Tensor &intrinsic, const core::Tensor &extrinsic, core::Tensor &voxel_block_coords, index_t voxel_grid_resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max, index_t stride)
void GetVoxelCoordinatesAndFlattenedIndicesCPU (const core::Tensor &buf_indices, const core::Tensor &block_keys, core::Tensor &voxel_coords, core::Tensor &flattened_indices, index_t block_resolution, float voxel_size)
template<typename input_depth_t , typename input_color_t , typename tsdf_t , typename weight_t , typename color_t >
void IntegrateCPU (const core::Tensor &depth, const core::Tensor &color, const core::Tensor &block_indices, const core::Tensor &block_keys, TensorMap &block_value_map, const core::Tensor &depth_intrinsic, const core::Tensor &color_intrinsic, const core::Tensor &extrinsic, index_t resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max)
void EstimateRangeCPU (const core::Tensor &block_keys, core::Tensor &range_minmax_map, const core::Tensor &intrinsics, const core::Tensor &extrinsics, int h, int w, int down_factor, int64_t block_resolution, float voxel_size, float depth_min, float depth_max, core::Tensor &fragment_buffer)
template<typename tsdf_t , typename weight_t , typename color_t >
void RayCastCPU (std::shared_ptr< core::HashMap > &hashmap, const TensorMap &block_value_map, const core::Tensor &range_map, TensorMap &renderings_map, const core::Tensor &intrinsic, const core::Tensor &extrinsic, index_t h, index_t w, index_t block_resolution, float voxel_size, float depth_scale, float depth_min, float depth_max, float weight_threshold, float trunc_voxel_multiplier, int range_map_down_factor)
template<typename tsdf_t , typename weight_t , typename color_t >
void ExtractPointCloudCPU (const core::Tensor &block_indices, const core::Tensor &nb_block_indices, const core::Tensor &nb_block_masks, const core::Tensor &block_keys, const TensorMap &block_value_map, core::Tensor &points, core::Tensor &normals, core::Tensor &colors, index_t block_resolution, float voxel_size, float weight_threshold, index_t &valid_size)
template<typename tsdf_t , typename weight_t , typename color_t >
void ExtractTriangleMeshCPU (const core::Tensor &block_indices, const core::Tensor &inv_block_indices, const core::Tensor &nb_block_indices, const core::Tensor &nb_block_masks, const core::Tensor &block_keys, const TensorMap &block_value_map, core::Tensor &vertices, core::Tensor &triangles, core::Tensor &vertex_normals, core::Tensor &vertex_colors, index_t block_resolution, float voxel_size, float weight_threshold, index_t &vertex_count)
template void IntegrateCPU< uint16_t, uint8_t, float, uint16_t, uint16_t > (const core::Tensor &depth, const core::Tensor &color, const core::Tensor &indices, const core::Tensor &block_keys, TensorMap &value_tensor_map, const core::Tensor &depth_intrinsic, const core::Tensor &color_intrinsic, const core::Tensor &extrinsic, index_t resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max)
template void IntegrateCPU< uint16_t, uint8_t, float, float, float > (const core::Tensor &depth, const core::Tensor &color, const core::Tensor &indices, const core::Tensor &block_keys, TensorMap &value_tensor_map, const core::Tensor &depth_intrinsic, const core::Tensor &color_intrinsic, const core::Tensor &extrinsic, index_t resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max)
template void IntegrateCPU< float, float, float, uint16_t, uint16_t > (const core::Tensor &depth, const core::Tensor &color, const core::Tensor &indices, const core::Tensor &block_keys, TensorMap &value_tensor_map, const core::Tensor &depth_intrinsic, const core::Tensor &color_intrinsic, const core::Tensor &extrinsic, index_t resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max)
template void IntegrateCPU< float, float, float, float, float > (const core::Tensor &depth, const core::Tensor &color, const core::Tensor &indices, const core::Tensor &block_keys, TensorMap &value_tensor_map, const core::Tensor &depth_intrinsic, const core::Tensor &color_intrinsic, const core::Tensor &extrinsic, index_t resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max)
template void RayCastCPU< float, uint16_t, uint16_t > (std::shared_ptr< core::HashMap > &hashmap, const TensorMap &block_value_map, const core::Tensor &range_map, TensorMap &renderings_map, const core::Tensor &intrinsic, const core::Tensor &extrinsic, index_t h, index_t w, index_t block_resolution, float voxel_size, float depth_scale, float depth_min, float depth_max, float weight_threshold, float trunc_voxel_multiplier, int range_map_down_factor)
template void RayCastCPU< float, float, float > (std::shared_ptr< core::HashMap > &hashmap, const TensorMap &block_value_map, const core::Tensor &range_map, TensorMap &renderings_map, const core::Tensor &intrinsic, const core::Tensor &extrinsic, index_t h, index_t w, index_t block_resolution, float voxel_size, float depth_scale, float depth_min, float depth_max, float weight_threshold, float trunc_voxel_multiplier, int range_map_down_factor)
template void ExtractPointCloudCPU< float, uint16_t, uint16_t > (const core::Tensor &block_indices, const core::Tensor &nb_block_indices, const core::Tensor &nb_block_masks, const core::Tensor &block_keys, const TensorMap &block_value_map, core::Tensor &points, core::Tensor &normals, core::Tensor &colors, index_t block_resolution, float voxel_size, float weight_threshold, index_t &valid_size)
template void ExtractPointCloudCPU< float, float, float > (const core::Tensor &block_indices, const core::Tensor &nb_block_indices, const core::Tensor &nb_block_masks, const core::Tensor &block_keys, const TensorMap &block_value_map, core::Tensor &points, core::Tensor &normals, core::Tensor &colors, index_t block_resolution, float voxel_size, float weight_threshold, index_t &valid_size)
template void ExtractTriangleMeshCPU< float, uint16_t, uint16_t > (const core::Tensor &block_indices, const core::Tensor &inv_block_indices, const core::Tensor &nb_block_indices, const core::Tensor &nb_block_masks, const core::Tensor &block_keys, const TensorMap &block_value_map, core::Tensor &vertices, core::Tensor &triangles, core::Tensor &vertex_normals, core::Tensor &vertex_colors, index_t block_resolution, float voxel_size, float weight_threshold, index_t &vertex_count)
template void ExtractTriangleMeshCPU< float, float, float > (const core::Tensor &block_indices, const core::Tensor &inv_block_indices, const core::Tensor &nb_block_indices, const core::Tensor &nb_block_masks, const core::Tensor &block_keys, const TensorMap &block_value_map, core::Tensor &vertices, core::Tensor &triangles, core::Tensor &vertex_normals, core::Tensor &vertex_colors, index_t block_resolution, float voxel_size, float weight_threshold, index_t &vertex_count)
CLOUDVIEWER_DEVICE index_t DeviceGetLinearIdx (index_t xo, index_t yo, index_t zo, index_t curr_block_idx, index_t resolution, const ArrayIndexer &nb_block_masks_indexer, const ArrayIndexer &nb_block_indices_indexer)
template<typename tsdf_t >
CLOUDVIEWER_DEVICE void DeviceGetNormal (const tsdf_t *tsdf_base_ptr, index_t xo, index_t yo, index_t zo, index_t curr_block_idx, float *n, index_t resolution, const ArrayIndexer &nb_block_masks_indexer, const ArrayIndexer &nb_block_indices_indexer)
Typedef Documentation
ArrayIndexer
using cloudViewer::t::geometry::kernel::voxel_grid::ArrayIndexer = typedef TArrayIndexer<index_t>
Definition at line 32 of file VoxelBlockGridImpl.h.
index_t
typedef int cloudViewer::t::geometry::kernel::voxel_grid::index_t
Definition at line 23 of file VoxelBlockGrid.h.
Function Documentation
DepthTouch()
void cloudViewer::t::geometry::kernel::voxel_grid::DepthTouch (std::shared_ptr< core::HashMap > & hashmap, const core::Tensor & depth, const core::Tensor & intrinsic, const core::Tensor & extrinsic, core::Tensor & voxel_block_coords, index_t voxel_grid_resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max, index_t stride)
Definition at line 42 of file VoxelBlockGrid.cpp.
References CUDA_CALL, DepthTouchCPU(), LogError, and stride.
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::GetUniqueBlockCoordinates().
DepthTouchCPU()
void cloudViewer::t::geometry::kernel::voxel_grid::DepthTouchCPU (std::shared_ptr< core::HashMap > & hashmap, const core::Tensor & depth, const core::Tensor & intrinsic, const core::Tensor & extrinsic, core::Tensor & voxel_block_coords, index_t voxel_grid_resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max, index_t stride)
Definition at line 117 of file VoxelBlockGridCPU.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetDevice(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetShape(), cloudViewer::t::geometry::InverseTransformation(), and stride.
Referenced by DepthTouch().
DeviceGetLinearIdx()
CLOUDVIEWER_DEVICE index_t cloudViewer::t::geometry::kernel::voxel_grid::DeviceGetLinearIdx (index_t xo, index_t yo, index_t zo, index_t curr_block_idx, index_t resolution, const ArrayIndexer & nb_block_masks_indexer, const ArrayIndexer & nb_block_indices_indexer) inline
Definition at line 84 of file VoxelBlockGridImpl.h.
References cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr(), and Sign().
Referenced by DeviceGetNormal(), ExtractPointCloudCPU(), and ExtractTriangleMeshCPU().
DeviceGetNormal()
template<typename tsdf_t > CLOUDVIEWER_DEVICE void cloudViewer::t::geometry::kernel::voxel_grid::DeviceGetNormal (const tsdf_t * tsdf_base_ptr, index_t xo, index_t yo, index_t zo, index_t curr_block_idx, float * n, index_t resolution, const ArrayIndexer & nb_block_masks_indexer, const ArrayIndexer & nb_block_indices_indexer) inline
Definition at line 113 of file VoxelBlockGridImpl.h.
References CLOUDVIEWER_DEVICE, and DeviceGetLinearIdx().
EstimateRange()
void cloudViewer::t::geometry::kernel::voxel_grid::EstimateRange (const core::Tensor & block_keys, core::Tensor & range_minmax_map, const core::Tensor & intrinsics, const core::Tensor & extrinsics, int h, int w, int down_factor, int64_t block_resolution, float voxel_size, float depth_min, float depth_max, core::Tensor & fragment_buffer)
Definition at line 194 of file VoxelBlockGrid.cpp.
References cloudViewer::core::Tensor::Contiguous(), EstimateRangeCPU(), cloudViewer::core::Float64, cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), LogError, and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::RayCast().
EstimateRangeCPU()
void cloudViewer::t::geometry::kernel::voxel_grid::EstimateRangeCPU (const core::Tensor & block_keys, core::Tensor & range_minmax_map, const core::Tensor & intrinsics, const core::Tensor & extrinsics, int h, int w, int down_factor, int64_t block_resolution, float voxel_size, float depth_min, float depth_max, core::Tensor & fragment_buffer)
Definition at line 300 of file VoxelBlockGridImpl.h.
References CLOUDVIEWER_DEVICE, count, cloudViewer::core::Float32, floorf(), cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr(), cloudViewer::core::Int32, LogDebug, LogInfo, LogWarning, max(), min(), offset, OPEN3D_ATOMIC_ADD, cloudViewer::core::ParallelFor(), cloudViewer::t::geometry::kernel::TransformIndexer::Project(), cloudViewer::t::geometry::kernel::TransformIndexer::RigidTransform(), and cloudViewer::core::cuda::Synchronize().
Referenced by EstimateRange().
ExtractPointCloud()
void cloudViewer::t::geometry::kernel::voxel_grid::ExtractPointCloud (const core::Tensor & block_indices, const core::Tensor & nb_block_indices, const core::Tensor & nb_block_masks, const core::Tensor & block_keys, const TensorMap & block_value_map, core::Tensor & points, core::Tensor & normals, core::Tensor & colors, index_t block_resolution, float voxel_size, float weight_threshold, int & valid_size)
Definition at line 284 of file VoxelBlockGrid.cpp.
References colors, cloudViewer::t::geometry::TensorMap::Contains(), DISPATCH_VALUE_DTYPE_TO_TEMPLATE, cloudViewer::core::Dtype::Float32, cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), LogError, normals, and points.
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::ExtractPointCloud().
ExtractPointCloudCPU()
template<typename tsdf_t , typename weight_t , typename color_t > void cloudViewer::t::geometry::kernel::voxel_grid::ExtractPointCloudCPU (const core::Tensor & block_indices, const core::Tensor & nb_block_indices, const core::Tensor & nb_block_masks, const core::Tensor & block_keys, const TensorMap & block_value_map, core::Tensor & points, core::Tensor & normals, core::Tensor & colors, index_t block_resolution, float voxel_size, float weight_threshold, index_t & valid_size)
Coordinate transform
Coordinate transform
Definition at line 1041 of file VoxelBlockGridImpl.h.
References CLOUDVIEWER_DEVICE, colors, count, DeviceGetLinearIdx(), cloudViewer::core::Float32, cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr(), cloudViewer::core::Int32, LogDebug, LogError, normals, OPEN3D_ATOMIC_ADD, cloudViewer::core::ParallelFor(), points, and cloudViewer::core::cuda::Synchronize().
ExtractPointCloudCPU< float, float, float >()
template void cloudViewer::t::geometry::kernel::voxel_grid::ExtractPointCloudCPU< float, float, float > (const core::Tensor & block_indices, const core::Tensor & nb_block_indices, const core::Tensor & nb_block_masks, const core::Tensor & block_keys, const TensorMap & block_value_map, core::Tensor & points, core::Tensor & normals, core::Tensor & colors, index_t block_resolution, float voxel_size, float weight_threshold, index_t & valid_size)
ExtractPointCloudCPU< float, uint16_t, uint16_t >()
template void cloudViewer::t::geometry::kernel::voxel_grid::ExtractPointCloudCPU< float, uint16_t, uint16_t > (const core::Tensor & block_indices, const core::Tensor & nb_block_indices, const core::Tensor & nb_block_masks, const core::Tensor & block_keys, const TensorMap & block_value_map, core::Tensor & points, core::Tensor & normals, core::Tensor & colors, index_t block_resolution, float voxel_size, float weight_threshold, index_t & valid_size)
ExtractTriangleMesh()
void cloudViewer::t::geometry::kernel::voxel_grid::ExtractTriangleMesh (const core::Tensor & block_indices, const core::Tensor & inv_block_indices, const core::Tensor & nb_block_indices, const core::Tensor & nb_block_masks, const core::Tensor & block_keys, const TensorMap & block_value_map, core::Tensor & vertices, core::Tensor & triangles, core::Tensor & vertex_normals, core::Tensor & vertex_colors, index_t block_resolution, float voxel_size, float weight_threshold, int & vertex_count)
Definition at line 334 of file VoxelBlockGrid.cpp.
References cloudViewer::t::geometry::TensorMap::Contains(), DISPATCH_VALUE_DTYPE_TO_TEMPLATE, cloudViewer::core::Dtype::Float32, cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), and LogError.
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::ExtractTriangleMesh().
ExtractTriangleMeshCPU()
template<typename tsdf_t , typename weight_t , typename color_t > void cloudViewer::t::geometry::kernel::voxel_grid::ExtractTriangleMeshCPU (const core::Tensor & block_indices, const core::Tensor & inv_block_indices, const core::Tensor & nb_block_indices, const core::Tensor & nb_block_masks, const core::Tensor & block_keys, const TensorMap & block_value_map, core::Tensor & vertices, core::Tensor & triangles, core::Tensor & vertex_normals, core::Tensor & vertex_colors, index_t block_resolution, float voxel_size, float weight_threshold, index_t & vertex_count)
Definition at line 1303 of file VoxelBlockGridImpl.h.
References CLOUDVIEWER_ASSERT, CLOUDVIEWER_DEVICE, count, DeviceGetLinearIdx(), cloudViewer::core::Float32, cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr(), cloudViewer::core::Int32, LogDebug, LogError, OPEN3D_ATOMIC_ADD, cloudViewer::core::ParallelFor(), and cloudViewer::core::Tensor::Zeros().
ExtractTriangleMeshCPU< float, float, float >()
template void cloudViewer::t::geometry::kernel::voxel_grid::ExtractTriangleMeshCPU< float, float, float > (const core::Tensor & block_indices, const core::Tensor & inv_block_indices, const core::Tensor & nb_block_indices, const core::Tensor & nb_block_masks, const core::Tensor & block_keys, const TensorMap & block_value_map, core::Tensor & vertices, core::Tensor & triangles, core::Tensor & vertex_normals, core::Tensor & vertex_colors, index_t block_resolution, float voxel_size, float weight_threshold, index_t & vertex_count)
ExtractTriangleMeshCPU< float, uint16_t, uint16_t >()
template void cloudViewer::t::geometry::kernel::voxel_grid::ExtractTriangleMeshCPU< float, uint16_t, uint16_t > (const core::Tensor & block_indices, const core::Tensor & inv_block_indices, const core::Tensor & nb_block_indices, const core::Tensor & nb_block_masks, const core::Tensor & block_keys, const TensorMap & block_value_map, core::Tensor & vertices, core::Tensor & triangles, core::Tensor & vertex_normals, core::Tensor & vertex_colors, index_t block_resolution, float voxel_size, float weight_threshold, index_t & vertex_count)
GetVoxelCoordinatesAndFlattenedIndices()
void cloudViewer::t::geometry::kernel::voxel_grid::GetVoxelCoordinatesAndFlattenedIndices (const core::Tensor & buf_indices, const core::Tensor & block_keys, core::Tensor & voxel_coords, core::Tensor & flattened_indices, index_t block_resolution, float voxel_size)
Definition at line 66 of file VoxelBlockGrid.cpp.
References CUDA_CALL, GetVoxelCoordinatesAndFlattenedIndicesCPU(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), and LogError.
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::GetVoxelCoordinatesAndFlattenedIndices().
GetVoxelCoordinatesAndFlattenedIndicesCPU()
void cloudViewer::t::geometry::kernel::voxel_grid::GetVoxelCoordinatesAndFlattenedIndicesCPU (const core::Tensor & buf_indices, const core::Tensor & block_keys, core::Tensor & voxel_coords, core::Tensor & flattened_indices, index_t block_resolution, float voxel_size)
Definition at line 37 of file VoxelBlockGridImpl.h.
References CLOUDVIEWER_DEVICE, and cloudViewer::core::ParallelFor().
Referenced by GetVoxelCoordinatesAndFlattenedIndices().
Integrate()
void cloudViewer::t::geometry::kernel::voxel_grid::Integrate (const core::Tensor & depth, const core::Tensor & color, const core::Tensor & block_indices, const core::Tensor & block_keys, TensorMap & block_value_map, const core::Tensor & depth_intrinsic, const core::Tensor & color_intrinsic, const core::Tensor & extrinsic, index_t resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max)
Definition at line 126 of file VoxelBlockGrid.cpp.
References color, cloudViewer::t::geometry::TensorMap::Contains(), DISPATCH_INPUT_DTYPE_TO_TEMPLATE, DISPATCH_VALUE_DTYPE_TO_TEMPLATE, cloudViewer::core::Dtype::Float32, cloudViewer::core::Tensor::GetDtype(), IntegrateCPU(), cloudViewer::core::IsDevice::IsCPU(), cloudViewer::core::IsDevice::IsCUDA(), LogError, and cloudViewer::core::Dtype::UInt8.
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::Integrate().
IntegrateCPU()
template<typename input_depth_t , typename input_color_t , typename tsdf_t , typename weight_t , typename color_t > void cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU (const core::Tensor & depth, const core::Tensor & color, const core::Tensor & block_indices, const core::Tensor & block_keys, TensorMap & block_value_map, const core::Tensor & depth_intrinsic, const core::Tensor & color_intrinsic, const core::Tensor & extrinsic, index_t resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max)
Coordinate transform
Coordinate transform
Definition at line 148 of file VoxelBlockGridImpl.h.
References CLOUDVIEWER_DEVICE, color, cloudViewer::core::Tensor::Eye(), cloudViewer::core::Float32, cloudViewer::core::Dtype::Float64, cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr(), cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::InBoundary(), LogError, cloudViewer::core::ParallelFor(), cloudViewer::t::geometry::kernel::TransformIndexer::Project(), cloudViewer::t::geometry::kernel::TransformIndexer::RigidTransform(), cloudViewer::core::cuda::Synchronize(), and cloudViewer::t::geometry::kernel::TransformIndexer::Unproject().
Referenced by Integrate().
IntegrateCPU< float, float, float, float, float >()
template void cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU< float, float, float, float, float > (const core::Tensor & depth, const core::Tensor & color, const core::Tensor & indices, const core::Tensor & block_keys, TensorMap & value_tensor_map, const core::Tensor & depth_intrinsic, const core::Tensor & color_intrinsic, const core::Tensor & extrinsic, index_t resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max)
IntegrateCPU< float, float, float, uint16_t, uint16_t >()
template void cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU< float, float, float, uint16_t, uint16_t > (const core::Tensor & depth, const core::Tensor & color, const core::Tensor & indices, const core::Tensor & block_keys, TensorMap & value_tensor_map, const core::Tensor & depth_intrinsic, const core::Tensor & color_intrinsic, const core::Tensor & extrinsic, index_t resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max)
IntegrateCPU< uint16_t, uint8_t, float, float, float >()
template void cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU< uint16_t, uint8_t, float, float, float > (const core::Tensor & depth, const core::Tensor & color, const core::Tensor & indices, const core::Tensor & block_keys, TensorMap & value_tensor_map, const core::Tensor & depth_intrinsic, const core::Tensor & color_intrinsic, const core::Tensor & extrinsic, index_t resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max)
IntegrateCPU< uint16_t, uint8_t, float, uint16_t, uint16_t >()
template void cloudViewer::t::geometry::kernel::voxel_grid::IntegrateCPU< uint16_t, uint8_t, float, uint16_t, uint16_t > (const core::Tensor & depth, const core::Tensor & color, const core::Tensor & indices, const core::Tensor & block_keys, TensorMap & value_tensor_map, const core::Tensor & depth_intrinsic, const core::Tensor & color_intrinsic, const core::Tensor & extrinsic, index_t resolution, float voxel_size, float sdf_trunc, float depth_scale, float depth_max)
PointCloudTouch()
void cloudViewer::t::geometry::kernel::voxel_grid::PointCloudTouch (std::shared_ptr< core::HashMap > & hashmap, const core::Tensor & points, core::Tensor & voxel_block_coords, index_t voxel_grid_resolution, float voxel_size, float sdf_trunc)
Definition at line 25 of file VoxelBlockGrid.cpp.
References CUDA_CALL, LogError, PointCloudTouchCPU(), and points.
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::GetUniqueBlockCoordinates().
PointCloudTouchCPU()
void cloudViewer::t::geometry::kernel::voxel_grid::PointCloudTouchCPU (std::shared_ptr< core::HashMap > & hashmap, const core::Tensor & points, core::Tensor & voxel_block_coords, index_t voxel_grid_resolution, float voxel_size, float sdf_trunc)
CPU.
Definition at line 55 of file VoxelBlockGridCPU.cpp.
References count, cloudViewer::utility::floor(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Int32, LogError, offset, cloudViewer::core::ParallelFor(), and points.
Referenced by PointCloudTouch().
RayCast()
void cloudViewer::t::geometry::kernel::voxel_grid::RayCast (std::shared_ptr< core::HashMap > & hashmap, const TensorMap & block_value_map, const core::Tensor & range_map, TensorMap & renderings_map, const core::Tensor & intrinsic, const core::Tensor & extrinsic, index_t h, index_t w, index_t block_resolution, float voxel_size, float depth_scale, float depth_min, float depth_max, float weight_threshold, float trunc_voxel_multiplier, int range_map_down_factor)
Definition at line 227 of file VoxelBlockGrid.cpp.
References cloudViewer::t::geometry::TensorMap::Contains(), cloudViewer::core::Device::CPU, cloudViewer::core::Device::CUDA, DISPATCH_VALUE_DTYPE_TO_TEMPLATE, cloudViewer::core::Dtype::Float32, and LogError.
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::RayCast().
RayCastCPU()
template<typename tsdf_t , typename weight_t , typename color_t > void cloudViewer::t::geometry::kernel::voxel_grid::RayCastCPU (std::shared_ptr< core::HashMap > & hashmap, const TensorMap & block_value_map, const core::Tensor & range_map, TensorMap & renderings_map, const core::Tensor & intrinsic, const core::Tensor & extrinsic, index_t h, index_t w, index_t block_resolution, float voxel_size, float depth_scale, float depth_min, float depth_max, float weight_threshold, float trunc_voxel_multiplier, int range_map_down_factor)
Definition at line 542 of file VoxelBlockGridImpl.h.
References cloudViewer::t::geometry::kernel::voxel_grid::MiniVecCache::Check(), CLOUDVIEWER_DEVICE, floorf(), cloudViewer::t::geometry::kernel::TArrayIndexer< index_t >::GetDataPtr(), cloudViewer::t::geometry::InverseTransformation(), LogError, max(), cloudViewer::core::ParallelFor(), cloudViewer::t::geometry::kernel::TransformIndexer::RigidTransform(), cloudViewer::t::geometry::kernel::TransformIndexer::Rotate(), Sign(), cloudViewer::core::cuda::Synchronize(), cloudViewer::t::geometry::kernel::TransformIndexer::Unproject(), and cloudViewer::t::geometry::kernel::voxel_grid::MiniVecCache::Update().
RayCastCPU< float, float, float >()
template void cloudViewer::t::geometry::kernel::voxel_grid::RayCastCPU< float, float, float > (std::shared_ptr< core::HashMap > & hashmap, const TensorMap & block_value_map, const core::Tensor & range_map, TensorMap & renderings_map, const core::Tensor & intrinsic, const core::Tensor & extrinsic, index_t h, index_t w, index_t block_resolution, float voxel_size, float depth_scale, float depth_min, float depth_max, float weight_threshold, float trunc_voxel_multiplier, int range_map_down_factor)
RayCastCPU< float, uint16_t, uint16_t >()
template void cloudViewer::t::geometry::kernel::voxel_grid::RayCastCPU< float, uint16_t, uint16_t > (std::shared_ptr< core::HashMap > & hashmap, const TensorMap & block_value_map, const core::Tensor & range_map, TensorMap & renderings_map, const core::Tensor & intrinsic, const core::Tensor & extrinsic, index_t h, index_t w, index_t block_resolution, float voxel_size, float depth_scale, float depth_min, float depth_max, float weight_threshold, float trunc_voxel_multiplier, int range_map_down_factor)