ACloudViewer: cloudViewer::geometry Namespace Reference
cloudViewer::geometry Namespace Reference
Namespaces
keypoint
Classes
class TSDFVoxel
class KDTreeFlann
KDTree with FLANN for nearest neighbor search.
class KDTreeSearchParam
Base class for KDTree search parameters.
class KDTreeSearchParamKNN
KDTree search parameters for pure KNN search.
class KDTreeSearchParamRadius
KDTree search parameters for pure radius search.
class KDTreeSearchParamHybrid
KDTree search parameters for hybrid KNN and radius search.
class ecvMeshBase
ecvMeshBash Class.
class Qhull
class TetraMesh
Tetra mesh contains vertices and tetrahedra represented by the indices to the vertices.
class HalfEdgeTriangleMesh
HalfEdgeTriangleMesh inherits TriangleMesh class with the addition of HalfEdge data structure for each half edge in the mesh as well as related functions.
class Image
The Image class stores image with customizable width, height, num of channels and bytes per channel.
class Line3D
Line3D is a class which derives from Eigen::ParametrizedLine<double, 3> in order to capture the semantic differences between a "line", "ray", and "line segment" for operations in which the difference is important, such as intersection and distance tests. The underlying Eigen object can always be retrieved with the .Line() method.
class Ray3D
A ray is a semantic interpretation of Eigen::ParametrizedLine which has an origin and a direction and extends infinitely only in that specific direction.
class Segment3D
A segment is a semantic interpretation of Eigen::ParametrizedLine which has an origin and an endpoint and exists finitely between them.
class LineSet
LineSet define a sets of lines in 3D. A typical application is to display the point cloud correspondence pairs.
class OctreeNodeInfo
OctreeNode's information.
class OctreeNode
The base class for octree node.
class OctreeInternalNode
OctreeInternalNode class, containing OctreeNode children.
class OctreeInternalPointNode
OctreeInternalPointNode class is an OctreeInternalNode containing a list of indices which is the union of all its children's list of indices.
class OctreeLeafNode
OctreeLeafNode base class.
class OctreeColorLeafNode
OctreeColorLeafNode class is an OctreeLeafNode containing color.
class OctreePointColorLeafNode
OctreePointColorLeafNode class is an OctreeColorLeafNode containing a list of indices corresponding to the point cloud points contained in this leaf node.
class Octree
Octree datastructure.
class RGBDImage
RGBDImage is for a pair of registered color and depth images,.
class Voxel
Base Voxel class, containing grid id and color.
class VoxelGrid
VoxelGrid is a collection of voxels which are aligned in grid.
class AvgColorVoxel
Class to aggregate color values from different votes in one voxel Computes the average color value in the voxel.
class PyOctreeNode
class PyOctreeLeafNode
Typedefs
using AxisAlignedBoundingBox = ::ccBBox
using OrientedBoundingBox = ::ecvOrientedBBox
using Geometry = ::ccHObject
using PointCloud = ::ccPointCloud
using TriangleMesh = ::ccMesh
typedef std::vector< std::shared_ptr< Image > > ImagePyramid
Typedef and functions for ImagePyramid.
typedef std::vector< std::shared_ptr< RGBDImage > > RGBDImagePyramid
Typedef and functions for RGBDImagePyramid.
Functions
void pybind_boundingvolume (py::module &m)
void pybind_cloudbase (py::module &m)
void pybind_cloudbase_methods (py::module &m)
void pybind_facet (py::module &m)
void pybind_facet_methods (py::module &m)
void pybind_geometry_classes (py::module &m)
void pybind_geometry (py::module &m)
void pybind_pointcloud (py::module &m)
void pybind_keypoint (py::module &m)
void pybind_voxelgrid (py::module &m)
void pybind_lineset (py::module &m)
void pybind_meshbase (py::module &m)
void pybind_trianglemesh (py::module &m)
void pybind_primitives (py::module &m)
void pybind_polyline (py::module &m)
void pybind_halfedgetrianglemesh (py::module &m)
void pybind_image (py::module &m)
void pybind_tetramesh (py::module &m)
void pybind_kdtreeflann (py::module &m)
void pybind_pointcloud_methods (py::module &m)
void pybind_voxelgrid_methods (py::module &m)
void pybind_meshbase_methods (py::module &m)
void pybind_trianglemesh_methods (py::module &m)
void pybind_primitives_methods (py::module &m)
void pybind_polyline_methods (py::module &m)
void pybind_lineset_methods (py::module &m)
void pybind_image_methods (py::module &m)
void pybind_octree_methods (py::module &m)
void pybind_octree (py::module &m)
void pybind_half_edge (py::module &m)
void pybind_keypoint_methods (py::module &m)
void pybind_tetramesh_methods (py::module &m)
Variables
static const std::unordered_map< std::string, std::string > map_shared_argument_docstrings
static const std::unordered_map< std::string, std::string > map_octree_argument_docstrings
Typedef Documentation
AxisAlignedBoundingBox
using cloudViewer::geometry::AxisAlignedBoundingBox = typedef ::ccBBox
Definition at line 21 of file BoundingVolume.h.
Geometry
using cloudViewer::geometry::Geometry = typedef ::ccHObject
Definition at line 18 of file Geometry.h.
ImagePyramid
typedef std::vector<std::shared_ptr<Image> > cloudViewer::geometry::ImagePyramid
Typedef and functions for ImagePyramid.
Definition at line 27 of file Image.h.
OrientedBoundingBox
using cloudViewer::geometry::OrientedBoundingBox = typedef ::ecvOrientedBBox
Definition at line 22 of file BoundingVolume.h.
PointCloud
using cloudViewer::geometry::PointCloud = typedef ::ccPointCloud
Definition at line 19 of file PointCloud.h.
RGBDImagePyramid
typedef std::vector<std::shared_ptr<RGBDImage> > cloudViewer::geometry::RGBDImagePyramid
Typedef and functions for RGBDImagePyramid.
Definition at line 19 of file RGBDImage.h.
TriangleMesh
using cloudViewer::geometry::TriangleMesh = typedef ::ccMesh
Definition at line 19 of file TriangleMesh.h.
Function Documentation
pybind_boundingvolume()
void cloudViewer::geometry::pybind_boundingvolume (py::module & m)
Definition at line 21 of file boundingvolume.cpp.
References cloudViewer::BoundingBoxTpl< PointCoordinateType >::addEigen(), cloudViewer::OrientedBoundingBox::center_, cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::clear(), cloudViewer::OrientedBoundingBox::Clear(), cloudViewer::OrientedBoundingBox::color_, cloudViewer::BoundingBoxTpl< PointCoordinateType >::computeVolume(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::containsEigen(), ecvOrientedBBox::CreateFromAxisAlignedBoundingBox(), ccBBox::CreateFromPoints(), ecvOrientedBBox::CreateFromPoints(), cloudViewer::OrientedBoundingBox::extent_, cloudViewer::BoundingBoxTpl< PointCoordinateType >::getBounds(), cloudViewer::OrientedBoundingBox::GetBoxPoints(), ccBBox::GetBoxPoints(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::GetColor(), cloudViewer::OrientedBoundingBox::GetColor(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::getDiagNormd(), cloudViewer::OrientedBoundingBox::GetExtent(), ccBBox::GetExtent(), cloudViewer::OrientedBoundingBox::GetHalfExtent(), ccBBox::GetHalfExtent(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::getMaxBoxDim(), cloudViewer::OrientedBoundingBox::GetMaxExtent(), ccBBox::GetMaxExtent(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::getMinBoxDim(), ccBBox::GetPrintInfo(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::getXPercentage(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::getYPercentage(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::getZPercentage(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::isValid(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::minDistTo(), cloudViewer::OrientedBoundingBox::R_, cloudViewer::BoundingBoxTpl< PointCoordinateType >::SetColor(), cloudViewer::OrientedBoundingBox::SetColor(), ccBBox::SetMaxBounds(), ccBBox::SetMinBounds(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::setValidity(), cloudViewer::BoundingBoxTpl< PointCoordinateType >::volume(), and cloudViewer::OrientedBoundingBox::volume().
Referenced by pybind_geometry().
pybind_cloudbase()
void cloudViewer::geometry::pybind_cloudbase (py::module & m)
Definition at line 30 of file cloudbase.cpp.
References cloudViewer::ReferenceCloud::add(), cloudViewer::ReferenceCloud::addPointIndex(), cloudViewer::ReferenceCloud::capacity(), cloudViewer::docstring::ClassMethodDocInject(), ccGenericPointCloud::clear(), cloudViewer::ReferenceCloud::clear(), ccGenericPointCloud::computeMeanAndCovariance(), cloudViewer::GenericCloud::enableScalarField(), format, cloudViewer::ReferenceCloud::forwardIterator(), Vector3Tpl< double >::fromArray(), Vector3Tpl< PointCoordinateType >::fromArray(), cloudViewer::GenericCloud::getBoundingBox(), cloudViewer::ReferenceCloud::getCurrentPointGlobalIndex(), cloudViewer::ReferenceCloud::getCurrentPointScalarValue(), cloudViewer::GenericCloud::getNextPoint(), ccGenericPointCloud::getPointDisplayedDistance(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), ccGenericPointCloud::getPointNormalIndex(), cloudViewer::GenericCloud::getPointScalarValue(), ccGenericPointCloud::getPointSize(), cloudViewer::GenericCloud::hasPoints(), cloudViewer::ReferenceCloud::invalidateBoundingBox(), ccGenericPointCloud::invertVisibilityArray(), cloudViewer::GenericCloud::isScalarFieldEnabled(), ccGenericPointCloud::isVisibilityTableInstantiated(), LogWarning, cloudViewer::GenericCloud::placeIteratorAtBeginning(), ccGenericPointCloud::refreshBB(), cloudViewer::ReferenceCloud::removeCurrentPointGlobalIndex(), cloudViewer::ReferenceCloud::removePointGlobalIndex(), ccGenericPointCloud::removePoints(), cloudViewer::ReferenceCloud::reserve(), ccGenericPointCloud::resetVisibilityArray(), cloudViewer::ReferenceCloud::resize(), cloudViewer::ReferenceCloud::setCurrentPointScalarValue(), cloudViewer::ReferenceCloud::setPointIndex(), cloudViewer::GenericCloud::setPointScalarValue(), ccGenericPointCloud::setPointSize(), cloudViewer::GenericCloud::size(), cloudViewer::ReferenceCloud::size(), cloudViewer::ReferenceCloud::swap(), cloudViewer::GenericCloud::testVisibility(), ecvColor::RgbTpl< Type >::ToEigen(), and ccGenericPointCloud::unallocateVisibilityArray().
Referenced by pybind_geometry().
pybind_cloudbase_methods()
void cloudViewer::geometry::pybind_cloudbase_methods (py::module & m)
Definition at line 479 of file cloudbase.cpp.
Referenced by pybind_geometry().
pybind_facet()
void cloudViewer::geometry::pybind_facet (py::module & m)
Definition at line 30 of file facet.cpp.
References cloudViewer::docstring::ClassMethodDocInject(), ccFacet::clone(), color, ccPolyline::computeLength(), ccFacet::Create(), format, Vector3Tpl< double >::fromArray(), ecvColor::RgbTpl< Type >::FromEigen(), ccFacet::getCenter(), ccFacet::getContour(), ccFacet::getContourVertices(), ccFacet::getNormalVectorMesh(), ccFacet::getOriginPoints(), ccFacet::getPlaneEquation(), ccFacet::getPolygon(), ccFacet::getRMS(), ccFacet::getSurface(), ccFacet::invertNormal(), LogWarning, name, ccFacet::PaintUniformColor(), ccFacet::setColor(), ccFacet::setContour(), ccFacet::setContourVertices(), ccFacet::setOriginPoints(), ccFacet::setPolygon(), cloudViewer::ReferenceCloud::size(), and ccMesh::size().
Referenced by pybind_geometry().
pybind_facet_methods()
void cloudViewer::geometry::pybind_facet_methods (py::module & m)
Definition at line 237 of file facet.cpp.
Referenced by pybind_geometry().
pybind_geometry()
void cloudViewer::geometry::pybind_geometry (py::module & m)
Definition at line 1021 of file geometry.cpp.
References pybind_boundingvolume(), pybind_cloudbase(), pybind_cloudbase_methods(), pybind_facet(), pybind_facet_methods(), pybind_geometry_classes(), pybind_halfedgetrianglemesh(), pybind_image(), pybind_image_methods(), pybind_kdtreeflann(), pybind_keypoint(), pybind_lineset(), pybind_lineset_methods(), pybind_meshbase(), pybind_meshbase_methods(), pybind_octree(), pybind_octree_methods(), pybind_pointcloud(), pybind_pointcloud_methods(), pybind_polyline(), pybind_polyline_methods(), pybind_primitives(), pybind_primitives_methods(), pybind_tetramesh(), pybind_trianglemesh(), pybind_voxelgrid(), and pybind_voxelgrid_methods().
Referenced by cloudViewer::PYBIND11_MODULE().
pybind_geometry_classes()
void cloudViewer::geometry::pybind_geometry_classes (py::module & m)
Definition at line 57 of file geometry.cpp.
References ccHObject::addChild(), CV_TYPES::BBOX, CV_TYPES::BOX, CV_TYPES::CAMERA_SENSOR, cloudViewer::docstring::ClassMethodDocInject(), color, ccDrawableObject::colorsShown(), CV_TYPES::CONE, CV_TYPES::CUSTOM_H_OBJECT, CV_TYPES::CYLINDER, CV_TYPES::DISH, ccDrawableObject::enableGLTransformation(), ccDrawableObject::enableTempColor(), CV_TYPES::EXTRU, CV_TYPES::FACET, filename, Vector3Tpl< PointCoordinateType >::fromArray(), ecvColor::RgbTpl< Type >::FromEigen(), ccGLMatrixTpl< float >::FromEigenMatrix(), CV_TYPES::GBL_SENSOR, ccHObject::GetAxisAlignedBoundingBox(), ccHObject::GetCenter(), ccHObject::getChild(), ccHObject::getClassID(), ccDrawableObject::getGLTransformation(), ccHObject::GetMax2DBound(), ccHObject::GetMaxBound(), ccHObject::GetMin2DBound(), ccHObject::GetMinBound(), ccObject::getName(), ccDrawableObject::getOpacity(), ccHObject::GetOrientedBoundingBox(), ccHObject::getOwnBB(), ccHObject::getParent(), ccHObject::GetRotationMatrixFromAxisAngle(), ccHObject::GetRotationMatrixFromEulerAngle(), ccHObject::GetRotationMatrixFromQuaternion(), ccHObject::GetRotationMatrixFromXYZ(), ccHObject::GetRotationMatrixFromXZY(), ccHObject::GetRotationMatrixFromYXZ(), ccHObject::GetRotationMatrixFromYZX(), ccHObject::GetRotationMatrixFromZXY(), ccHObject::GetRotationMatrixFromZYX(), ccDrawableObject::getTempColor(), ccObject::getUniqueID(), ccDrawableObject::hasColors(), ccDrawableObject::hasDisplayedScalarField(), ccDrawableObject::hasNormals(), ccDrawableObject::hasScalarFields(), CV_TYPES::IMAGE, CV_TYPES::IMAGE2, ccObject::isA(), ccDrawableObject::isColorOverridden(), ccObject::isCustom(), ccHObject::IsEmpty(), ccDrawableObject::isGLTransEnabled(), ccHObject::isGroup(), ccObject::isHierarchy(), ccObject::isKindOf(), ccObject::isLeaf(), ccDrawableObject::isSelected(), ccHObject::isSerializable(), ccDrawableObject::isVisibilityLocked(), ccDrawableObject::isVisible(), CV_TYPES::LABEL_2D, CV_TYPES::LINESET, ccDrawableObject::lockVisibility(), LogWarning, CV_TYPES::MATERIAL_SET, CV_TYPES::MESH, CV_TYPES::MESH_GROUP, name, ccDrawableObject::nameShownIn3D(), ccDrawableObject::normalsShown(), CV_TYPES::OLD_CYLINDER_ID, CV_TYPES::ORIENTED_BBOX, CV_TYPES::PLANE, CV_TYPES::POINT_CLOUD, CV_TYPES::POINT_KDTREE, CV_TYPES::POINT_OCTREE, CV_TYPES::POINT_OCTREE2, CV_TYPES::POLY_LINE, CV_TYPES::PRIMITIVE, CV_TYPES::QUADRIC, ccHObject::removeAllChildren(), ccHObject::removeChild(), ccDrawableObject::resetGLTransformation(), CV_TYPES::RGBD_IMAGE, ccHObject::Rotate(), ccDrawableObject::rotateGL(), ccHObject::Scale(), CV_TYPES::SENSOR, ccDrawableObject::setGLTransformation(), ccHObject::setLineWidthRecursive(), ccObject::setName(), ccDrawableObject::setOpacity(), ccHObject::setPointSizeRecursive(), ccDrawableObject::setSelected(), ccDrawableObject::setTempColor(), ccObject::setUniqueID(), ccDrawableObject::setVisible(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccDrawableObject::showNameIn3D(), ccDrawableObject::showNormals(), ccDrawableObject::showSF(), CV_TYPES::SPHERE, cloudViewer::docstring::static_property, CV_TYPES::SUB_MESH, CV_TYPES::TETRA_MESH, ccHObjectCaster::To2DLabel(), ccHObjectCaster::To2DViewportLabel(), ccHObjectCaster::To2DViewportObject(), ccHObjectCaster::ToBBox(), ccHObjectCaster::ToBox(), ccHObjectCaster::ToCameraSensor(), ccHObjectCaster::ToCone(), ccHObjectCaster::ToCoordinateSystem(), ccHObjectCaster::ToCylinder(), ccHObjectCaster::ToDish(), ecvColor::RgbTpl< Type >::ToEigen(), ccGLMatrixTpl< float >::ToEigenMatrix4(), ccHObjectCaster::ToExtru(), ccHObjectCaster::ToFacet(), ccHObjectCaster::ToGBLSensor(), ccDrawableObject::toggleColors(), ccDrawableObject::toggleMaterials(), ccDrawableObject::toggleNormals(), ccDrawableObject::toggleSF(), ccDrawableObject::toggleShowName(), ccDrawableObject::toggleVisibility(), ccHObjectCaster::ToImage(), ccHObjectCaster::ToImage2(), ccHObjectCaster::ToKdTree(), ccHObjectCaster::ToLineSet(), ccHObjectCaster::ToMesh(), ccHObjectCaster::ToOctree2(), ccHObjectCaster::ToOctreeProxy(), ccHObjectCaster::ToOrientedBBox(), ccHObjectCaster::ToPlane(), ccHObjectCaster::ToPointCloud(), ccHObjectCaster::ToPolyline(), ccHObjectCaster::ToQuadric(), ccHObjectCaster::ToRGBDImage(), CV_TYPES::TORUS, ccHObjectCaster::ToSensor(), ccHObjectCaster::ToSphere(), ccHObjectCaster::ToSubMesh(), ccHObjectCaster::ToTorus(), ccHObjectCaster::ToTransBuffer(), ccHObjectCaster::ToVoxelGrid(), ccHObject::Transform(), ccHObject::Translate(), ccDrawableObject::translateGL(), CV_TYPES::VIEWPORT_2D_LABEL, CV_TYPES::VIEWPORT_2D_OBJECT, and CV_TYPES::VOXEL_GRID.
Referenced by pybind_geometry().
pybind_half_edge()
void cloudViewer::geometry::pybind_half_edge (py::module & m)
Definition at line 18 of file halfedgemesh.cpp.
References cloudViewer::geometry::HalfEdgeTriangleMesh::HalfEdge::IsBoundary(), cloudViewer::geometry::HalfEdgeTriangleMesh::HalfEdge::next_, cloudViewer::geometry::HalfEdgeTriangleMesh::HalfEdge::triangle_index_, cloudViewer::geometry::HalfEdgeTriangleMesh::HalfEdge::twin_, and cloudViewer::geometry::HalfEdgeTriangleMesh::HalfEdge::vertex_indices_.
Referenced by pybind_halfedgetrianglemesh().
pybind_halfedgetrianglemesh()
void cloudViewer::geometry::pybind_halfedgetrianglemesh (py::module & m)
Definition at line 56 of file halfedgemesh.cpp.
References cloudViewer::geometry::HalfEdgeTriangleMesh::boundaryHalfEdgesFromVertex(), cloudViewer::geometry::HalfEdgeTriangleMesh::boundaryVerticesFromVertex(), cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::geometry::HalfEdgeTriangleMesh::CreateFromTriangleMesh(), cloudViewer::geometry::HalfEdgeTriangleMesh::getBoundaries(), cloudViewer::geometry::HalfEdgeTriangleMesh::half_edges_, cloudViewer::geometry::HalfEdgeTriangleMesh::hasHalfEdges(), cloudViewer::geometry::HalfEdgeTriangleMesh::ordered_half_edge_from_vertex_, pybind_half_edge(), patch::to_string(), cloudViewer::geometry::HalfEdgeTriangleMesh::triangle_normals_, cloudViewer::geometry::HalfEdgeTriangleMesh::triangles_, and cloudViewer::geometry::ecvMeshBase::vertices_.
Referenced by pybind_geometry().
pybind_image()
void cloudViewer::geometry::pybind_image (py::module & m)
Definition at line 40 of file image.cpp.
References format, cloudViewer::geometry::Image::Gaussian3, cloudViewer::geometry::Image::Gaussian5, cloudViewer::geometry::Image::Gaussian7, height, image, cloudViewer::geometry::Image::Prepare(), cloudViewer::geometry::Image::Sobel3Dx, cloudViewer::geometry::Image::Sobel3Dy, and width.
Referenced by pybind_geometry().
pybind_image_methods()
void cloudViewer::geometry::pybind_image_methods (py::module & m)
Definition at line 274 of file image.cpp.
Referenced by pybind_geometry().
pybind_kdtreeflann()
void cloudViewer::geometry::pybind_kdtreeflann (py::module & m)
Definition at line 17 of file kdtreeflann.cpp.
References cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::geometry::KDTreeSearchParam::GetSearchType(), cloudViewer::geometry::KDTreeSearchParam::Hybrid, cloudViewer::geometry::KDTreeSearchParam::Knn, cloudViewer::geometry::KDTreeSearchParamKNN::knn_, cloudViewer::geometry::KDTreeSearchParamHybrid::max_nn_, cloudViewer::geometry::KDTreeFlann::Query(), cloudViewer::geometry::KDTreeSearchParam::Radius, cloudViewer::geometry::KDTreeSearchParamRadius::radius_, cloudViewer::geometry::KDTreeSearchParamHybrid::radius_, cloudViewer::geometry::KDTreeFlann::Search(), cloudViewer::geometry::KDTreeFlann::SearchHybrid(), cloudViewer::geometry::KDTreeFlann::SearchKNN(), cloudViewer::geometry::KDTreeFlann::SearchRadius(), cloudViewer::geometry::KDTreeFlann::SetFeature(), cloudViewer::geometry::KDTreeFlann::SetGeometry(), cloudViewer::geometry::KDTreeFlann::SetMatrixData(), and patch::to_string().
Referenced by pybind_geometry().
pybind_keypoint()
void cloudViewer::geometry::pybind_keypoint (py::module & m)
Definition at line 52 of file keypoint.cpp.
References pybind_keypoint_methods().
Referenced by pybind_geometry().
pybind_keypoint_methods()
void cloudViewer::geometry::pybind_keypoint_methods (py::module & m)
Definition at line 22 of file keypoint.cpp.
References cloudViewer::geometry::keypoint::ComputeISSKeypoints(), and cloudViewer::docstring::FunctionDocInject().
Referenced by pybind_keypoint().
pybind_lineset()
void cloudViewer::geometry::pybind_lineset (py::module & m)
Definition at line 20 of file lineset.cpp.
References cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::geometry::LineSet::colors_, cloudViewer::geometry::LineSet::CreateCameraVisualization(), cloudViewer::geometry::LineSet::CreateFromAxisAlignedBoundingBox(), cloudViewer::geometry::LineSet::CreateFromOrientedBoundingBox(), cloudViewer::geometry::LineSet::CreateFromPointCloudCorrespondences(), cloudViewer::geometry::LineSet::CreateFromTetraMesh(), cloudViewer::geometry::LineSet::CreateFromTriangleMesh(), cloudViewer::geometry::LineSet::GetLineCoordinate(), ccDrawableObject::hasColors(), cloudViewer::geometry::LineSet::HasLines(), cloudViewer::geometry::LineSet::HasPoints(), cloudViewer::camera::PinholeCameraIntrinsic::height_, cloudViewer::camera::PinholeCameraIntrinsic::intrinsic_matrix_, cloudViewer::geometry::LineSet::lines_, cloudViewer::geometry::LineSet::PaintUniformColor(), cloudViewer::geometry::LineSet::points_, patch::to_string(), and cloudViewer::camera::PinholeCameraIntrinsic::width_.
Referenced by pybind_geometry().
pybind_lineset_methods()
void cloudViewer::geometry::pybind_lineset_methods (py::module & m)
Definition at line 129 of file lineset.cpp.
Referenced by pybind_geometry().
pybind_meshbase()
void cloudViewer::geometry::pybind_meshbase (py::module & m)
Definition at line 24 of file meshbase.cpp.
References cloudViewer::GenericTriangle::_getA(), cloudViewer::GenericTriangle::_getB(), cloudViewer::GenericTriangle::_getC(), cloudViewer::GenericMesh::_getNextTriangle(), cloudViewer::GenericMesh::All, cloudViewer::GenericMesh::Average, ccGenericMesh::capacity(), cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::GenericMesh::Color, color, cloudViewer::geometry::ecvMeshBase::ComputeConvexHull(), cloudViewer::DELAUNAY_2D_AXIS_ALIGNED, cloudViewer::DELAUNAY_2D_BEST_LS_PLANE, ccGenericMesh::enableStippling(), Vector3Tpl< double >::fromArray(), cloudViewer::GenericMesh::getBoundingBox(), ccGenericMesh::hasMaterials(), ccGenericMesh::hasTextures(), cloudViewer::GenericMesh::hasTriangles(), ccGenericMesh::hasTriNormals(), cloudViewer::geometry::ecvMeshBase::HasVertexColors(), cloudViewer::geometry::ecvMeshBase::HasVertexNormals(), cloudViewer::geometry::ecvMeshBase::HasVertices(), ccGenericMesh::isShownAsPoints(), ccGenericMesh::isShownAsWire(), LogWarning, ccGenericMesh::materialsShown(), cloudViewer::GenericMesh::Normal, normal, cloudViewer::geometry::ecvMeshBase::NormalizeNormals(), cloudViewer::geometry::ecvMeshBase::PaintUniformColor(), cloudViewer::GenericMesh::placeIteratorAtBeginning(), cloudViewer::GenericMesh::Quadric, ccGenericMesh::refreshBB(), ccGenericMesh::showMaterials(), ccGenericMesh::showPoints(), ccGenericMesh::showTriNorms(), ccGenericMesh::showWired(), cloudViewer::GenericMesh::size(), cloudViewer::GenericMesh::Smoothed, cloudViewer::GenericMesh::Spokes, ccGenericMesh::stipplingEnabled(), patch::to_string(), ecvColor::RgbTpl< Type >::ToEigen(), ccGenericMesh::triNormsShown(), cloudViewer::GenericMesh::Vertex, cloudViewer::geometry::ecvMeshBase::vertex_colors_, vertex_index, cloudViewer::geometry::ecvMeshBase::vertex_normals_, and cloudViewer::geometry::ecvMeshBase::vertices_.
Referenced by pybind_geometry().
pybind_meshbase_methods()
void cloudViewer::geometry::pybind_meshbase_methods (py::module & m)
Definition at line 509 of file meshbase.cpp.
Referenced by pybind_geometry().
pybind_octree()
void cloudViewer::geometry::pybind_octree (py::module & m)
Definition at line 38 of file octree.cpp.
References cloudViewer::geometry::OctreeNodeInfo::child_index_, cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::geometry::OctreeNodeInfo::depth_, cloudViewer::geometry::OctreeNodeInfo::origin_, size, and cloudViewer::geometry::OctreeNodeInfo::size_.
Referenced by pybind_geometry().
pybind_octree_methods()
void cloudViewer::geometry::pybind_octree_methods (py::module & m)
Definition at line 348 of file octree.cpp.
Referenced by pybind_geometry().
pybind_pointcloud()
void cloudViewer::geometry::pybind_pointcloud (py::module & m)
Definition at line 28 of file pointcloud.cpp.
References ccPointCloud::addEigenColors(), ccPointCloud::addEigenNorms(), ccPointCloud::addGreyColor(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::addPoints(), ccPointCloud::addScalarField(), ccPointCloud::append(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::capacity(), cloudViewer::docstring::ClassMethodDocInject(), ccPointCloud::cloneThis(), ccPointCloud::ClusterDBSCAN(), ccPointCloud::colorize(), ccPointCloud::colorsHaveChanged(), ccPointCloud::ComputeConvexHull(), ccPointCloud::computeCPSet(), ccPointCloud::computeGravityCenter(), ccPointCloud::ComputeMahalanobisDistance(), ccPointCloud::ComputeNearestNeighborDistance(), ccPointCloud::ComputePointCloudDistance(), ccPointCloud::ComputeResolution(), ccPointCloud::convertCurrentScalarFieldToColors(), ccPointCloud::convertNormalToDipDirSFs(), ccPointCloud::convertNormalToRGB(), ccPointCloud::convertRGBToGreyScale(), ccPointCloud::covariances_, ccPointCloud::CreateFromDepthImage(), ccPointCloud::CreateFromRGBDImage(), ccPointCloud::Crop(), ccPointCloud::crop2D(), ccPointCloud::deleteAllScalarFields(), ccPointCloud::deleteScalarField(), ccPointCloud::enhanceRGBWithIntensitySF(), ccPointCloud::EstimateCovariances(), ccPointCloud::EstimateNormals(), ccPointCloud::EstimatePerPointCovariances(), ccPointCloud::exportCoordToSF(), ccPointCloud::FarthestPointDownSample(), ccPointCloud::filterPointsByScalarValue(), ccPointCloud::From(), Vector3Tpl< double >::fromArray(), ccPointCloud::getCurrentDisplayedScalarField(), ccPointCloud::getCurrentDisplayedScalarFieldIndex(), cloudViewer::PointCloudTpl< T >::getCurrentInScalarField(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::getCurrentInScalarFieldIndex(), cloudViewer::PointCloudTpl< T >::getCurrentOutScalarField(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::getCurrentOutScalarFieldIndex(), ccPointCloud::getEigenColor(), ccPointCloud::getEigenColors(), ccPointCloud::getEigenNormal(), ccPointCloud::getEigenNormals(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::getEigenPoint(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::getEigenPoints(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::getNumberOfScalarFields(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::PointCloudTpl< T >::getScalarFieldName(), ccPointCloud::HasCovariances(), ccPointCloud::hasSensor(), ccPointCloud::HiddenPointRemoval(), ccPointCloud::hidePointsByScalarValue(), ccPointCloud::interpolateColorsFrom(), ccPointCloud::invalidateBoundingBox(), ccPointCloud::invertNormals(), ccPointCloud::IsEmpty(), ccPolyline::IsEmpty(), LogWarning, name, ccPointCloud::NormalizeNormals(), ccPointCloud::normalsHaveChanged(), ccPointCloud::OrientNormalsConsistentTangentPlane(), ccPointCloud::OrientNormalsToAlignWithDirection(), ccPointCloud::OrientNormalsTowardsCameraLocation(), ccPointCloud::PaintUniformColor(), ccPointCloud::partialClone(), ccPointCloud::pointsHaveChanged(), ccPointCloud::RandomDownSample(), ccPointCloud::RemoveNonFinitePoints(), ccPointCloud::RemoveRadiusOutliers(), ccPointCloud::RemoveStatisticalOutliers(), cloudViewer::PointCloudTpl< T >::renameScalarField(), ccPointCloud::reserve(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveThePointsTable(), ccPointCloud::reserveTheRGBTable(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::reset(), ccPointCloud::resize(), ccPointCloud::resizeTheRGBTable(), result, ccPointCloud::SegmentPlane(), ccPointCloud::SelectByIndex(), ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::setCurrentInScalarField(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::setCurrentOutScalarField(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::setCurrentScalarField(), ccPointCloud::setEigenColor(), ccPointCloud::setEigenNormal(), cloudViewer::PointCloudTpl< ccGenericPointCloud >::setEigenPoint(), ccPointCloud::setRGBColorByBanding(), ccPointCloud::setRGBColorWithCurrentScalarField(), ccPointCloud::sfColorScaleShown(), ccPointCloud::showSFColorsScale(), ccPointCloud::shrinkToFit(), cloudViewer::PointCloudTpl< T >::size(), cloudViewer::ReferenceCloud::size(), patch::to_string(), ccPointCloud::unalloactePoints(), ccPointCloud::unallocateColors(), ccPointCloud::unallocateNorms(), ccPointCloud::UniformDownSample(), ccPointCloud::VoxelDownSample(), and ccPointCloud::VoxelDownSampleAndTrace().
Referenced by pybind_geometry().
pybind_pointcloud_methods()
void cloudViewer::geometry::pybind_pointcloud_methods (py::module & m)
Definition at line 1021 of file pointcloud.cpp.
Referenced by pybind_geometry().
pybind_polyline()
void cloudViewer::geometry::pybind_polyline (py::module & m)
Definition at line 31 of file polyline.cpp.
References ccPolyline::add(), cloudViewer::docstring::ClassMethodDocInject(), ccCircle::clone(), color, ccPolyline::computeLength(), format, ecvColor::RgbTpl< Type >::FromEigen(), ccPolyline::getArrowIndex(), ccPolyline::getArrowLength(), ccCircle::getRadius(), ccCircle::getResolution(), ccPolyline::getVertexMarkerWidth(), ccPolyline::getWidth(), ccUniqueIDGenerator::InvalidUniqueID, ccPolyline::is2DMode(), cloudViewer::Polyline::isClosed(), length(), ccPolyline::needTransform(), ccPolyline::PaintUniformColor(), ccPolyline::segmentCount(), ccPolyline::set2DMode(), cloudViewer::Polyline::setClosed(), ccCircle::setRadius(), ccCircle::setResolution(), ccPolyline::setTransformFlag(), ccPolyline::setVertexMarkerWidth(), ccPolyline::setWidth(), ccPolyline::showArrow(), ccPolyline::showVertices(), cloudViewer::ReferenceCloud::size(), ecvColor::RgbTpl< Type >::ToEigen(), and ccPolyline::verticesShown().
Referenced by pybind_geometry().
pybind_polyline_methods()
void cloudViewer::geometry::pybind_polyline_methods (py::module & m)
Definition at line 277 of file polyline.cpp.
Referenced by pybind_geometry().
pybind_primitives()
void cloudViewer::geometry::pybind_primitives (py::module & m)
Definition at line 37 of file primitives.cpp.
References ccCoordinateSystem::axisLinesAreShown(), ccCoordinateSystem::axisPlanesAreShown(), cloudViewer::docstring::ClassMethodDocInject(), ccMesh::clearTriNormals(), ccGenericPrimitive::clone(), color, ccQuadric::Fit(), ccPlane::flip(), format, Vector3Tpl< PointCoordinateType >::fromArray(), Vector3Tpl< double >::fromArray(), ecvColor::RgbTpl< Type >::FromEigen(), ccGLMatrixTpl< float >::FromEigenMatrix(), ccTorus::getAngleRad(), ccCoordinateSystem::getAxisWidth(), ccDish::getBaseRadius(), ccCone::getBottomCenter(), ccCone::getBottomRadius(), ccPlane::getCenter(), ccBox::getDimensions(), ccCoordinateSystem::getDisplayScale(), ccGenericPrimitive::getDrawingPrecision(), ccPlane::getEquation(), ccQuadric::getEquationCoefs(), ccQuadric::getEquationDims(), ccQuadric::getEquationString(), ccGenericPrimitive::getGLTransformationHistory(), ccCone::getHeight(), ccDish::getHeight(), ccTorus::getInsideRadius(), ccCone::getLargeCenter(), ccCone::getLargeRadius(), ccQuadric::getMaxCorner(), ccQuadric::getMinCorner(), ccPlane::getNormal(), ccCoordinateSystem::getOrigin(), ccTorus::getOutsideRadius(), ccExtru::getProfile(), ccDisc::getRadius(), ccSphere::getRadius(), ccTorus::getRectSection(), ccTorus::getRectSectionHeight(), ccDish::getSecondRadius(), ccCone::getSmallCenter(), ccCone::getSmallRadius(), ccExtru::getThickness(), ccCone::getTopCenter(), ccCone::getTopRadius(), ccGenericPrimitive::getTransformation(), ccGenericPrimitive::getTypeName(), ccPlane::getXWidth(), ccCoordinateSystem::getXYplane(), ccPlane::getYWidth(), ccCoordinateSystem::getYZplane(), ccCoordinateSystem::getZXplane(), ccGenericPrimitive::hasDrawingPrecision(), height, ccCone::isSnoutMode(), LogWarning, M_PI, name, profile, ccQuadric::projectOnQuadric(), ccCoordinateSystem::setAxisWidth(), ccCone::setBottomRadius(), ccGenericPrimitive::setColor(), ccBox::setDimensions(), ccCoordinateSystem::setDisplayScale(), ccGenericPrimitive::setDrawingPrecision(), ccCone::setHeight(), ccDisc::setRadius(), ccSphere::setRadius(), ccCone::setTopRadius(), ccPlane::setXWidth(), ccPlane::setYWidth(), ccCoordinateSystem::ShowAxisLines(), ccCoordinateSystem::ShowAxisPlanes(), ccMesh::size(), ccGLMatrixTpl< double >::ToEigenMatrix4(), width, Vector2Tpl< Type >::x, Tuple3Tpl< Type >::x, Vector2Tpl< Type >::y, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by pybind_geometry().
pybind_primitives_methods()
void cloudViewer::geometry::pybind_primitives_methods (py::module & m)
Definition at line 1029 of file primitives.cpp.
Referenced by pybind_geometry().
pybind_tetramesh()
void cloudViewer::geometry::pybind_tetramesh (py::module & m)
Definition at line 18 of file tetramesh.cpp.
References cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::geometry::TetraMesh::CreateFromPointCloud(), cloudViewer::geometry::TetraMesh::ExtractTriangleMesh(), cloudViewer::geometry::TetraMesh::HasTetras(), cloudViewer::geometry::ecvMeshBase::HasVertices(), cloudViewer::geometry::TetraMesh::RemoveDegenerateTetras(), cloudViewer::geometry::TetraMesh::RemoveDuplicatedTetras(), cloudViewer::geometry::TetraMesh::RemoveDuplicatedVertices(), cloudViewer::geometry::TetraMesh::RemoveUnreferencedVertices(), cloudViewer::geometry::TetraMesh::tetras_, patch::to_string(), and cloudViewer::geometry::ecvMeshBase::vertices_.
Referenced by pybind_geometry().
pybind_tetramesh_methods()
void cloudViewer::geometry::pybind_tetramesh_methods (py::module & m)
Definition at line 99 of file tetramesh.cpp.
pybind_trianglemesh()
void cloudViewer::geometry::pybind_trianglemesh (py::module & m)
Definition at line 23 of file trianglemesh.cpp.
References ccMesh::addEigenVertices(), ccMesh::addTriangleMtlIndex(), ccMesh::addTriangleNormalIndexes(), ccMesh::addTriangles(), ccMesh::addTriangleTexCoordIndexes(), ccMesh::addVertexColors(), ccMesh::addVertexNormals(), ccMesh::adjacency_list_, cloudViewer::GenericMesh::All, ccMesh::arePerTriangleNormalsEnabled(), cloudViewer::GenericMesh::Average, cloudViewer::docstring::ClassMethodDocInject(), ccMesh::clear(), ccMesh::clearTriNormals(), ccMesh::cloneMesh(), ccPointCloud::cloneThis(), ccMesh::ClusterConnectedTriangles(), color, ccMesh::ComputeAdjacencyList(), ccMesh::ComputeConvexHull(), ccMesh::computeNormals(), ccMesh::ComputeTriangleArea(), ccMesh::ComputeTriangleNormals(), ccMesh::ComputeTrianglePlane(), ccMesh::ComputeVertexNormals(), ccMesh::convertMaterialsToVertexColors(), ccMesh::CreateArrow(), ccMesh::CreateBox(), ccMesh::CreateCone(), ccMesh::CreateCoordinateFrame(), ccMesh::CreateCylinder(), ccMesh::CreateFromPointCloudAlphaShape(), ccMesh::CreateFromPointCloudBallPivoting(), ccMesh::CreateFromPointCloudPoisson(), ccMesh::CreateIcosahedron(), ccMesh::CreateMobius(), ccMesh::createNewMeshFromSelection(), ccMesh::CreateOctahedron(), ccMesh::CreatePlane(), ccMesh::CreateSphere(), ccMesh::CreateTetrahedron(), ccMesh::CreateTorus(), ccMesh::Crop(), ccMesh::DeformAsRigidAsPossible(), ccMesh::EulerPoincareCharacteristic(), ccMesh::FilterSharpen(), ccMesh::FilterSmoothLaplacian(), ccMesh::FilterSmoothSimple(), ccMesh::FilterSmoothTaubin(), ccMesh::flipTriangles(), format, ccGLMatrixTpl< float >::FromEigenMatrix(), ccMesh::GetEdgeToTrianglesMap(), ccMesh::GetEdgeToVerticesMap(), ccMesh::getEigenVertices(), ccMesh::GetEigneOrderedTriangle(), ccMesh::GetNonManifoldEdges(), ccMesh::GetNonManifoldVertices(), ccMesh::GetOrderedEdge(), ccMesh::GetSelfIntersectingTriangles(), ccMesh::GetSurfaceArea(), ccMesh::getTriangle(), ccMesh::GetTriangleArea(), ccMesh::getTriangleNorm(), ccMesh::getTriangleNormalIndexes(), ccMesh::getTriangleNorms(), ccMesh::GetTrianglePlane(), ccMesh::getTriangles(), ccMesh::getVertexColor(), ccMesh::getVertexColors(), ccMesh::getVertexNormal(), ccMesh::getVertexNormals(), ccMesh::getVertice(), ccMesh::getVerticeSize(), ccMesh::GetVolume(), ccMesh::hasAdjacencyList(), ccMesh::hasColors(), ccMesh::hasEigenTextures(), ccMesh::hasNormals(), ccMesh::hasPerTriangleMtlIndexes(), ccMesh::hasTriangleMaterialIds(), cloudViewer::GenericMesh::hasTriangles(), ccMesh::hasTriangleUvs(), ccMesh::HasVertices(), infinity(), ccMesh::IsBoundingBoxIntersecting(), ccMesh::IsEdgeManifold(), ccMesh::IsIntersecting(), ccMesh::IsOrientable(), ccMesh::IsSelfIntersecting(), ccMesh::IsVertexManifold(), ccMesh::IsWatertight(), ccMesh::laplacianSmooth(), LogWarning, ccMesh::merge(), ccMesh::MergeCloseVertices(), ccMesh::NormalizeNormals(), ccMesh::OrientTriangles(), ccMesh::PaintUniformColor(), ccMesh::partialClone(), CV_TYPES::POINT_CLOUD, ccMesh::processScalarField(), ccMesh::RemoveDegenerateTriangles(), ccMesh::RemoveDuplicatedTriangles(), ccMesh::RemoveDuplicatedVertices(), ccMesh::RemoveNonManifoldEdges(), ccMesh::removePerTriangleMtlIndexes(), ccMesh::removePerTriangleNormalIndexes(), ccMesh::removePerTriangleTexCoordIndexes(), ccMesh::removeTriangles(), ccMesh::RemoveTrianglesByIndex(), ccMesh::RemoveTrianglesByMask(), ccMesh::RemoveUnreferencedVertices(), ccMesh::RemoveVerticesByIndex(), ccMesh::RemoveVerticesByMask(), ccMesh::reserve(), ccMesh::reservePerTriangleMtlIndexes(), ccMesh::reservePerTriangleNormalIndexes(), ccMesh::reservePerTriangleTexCoordIndexes(), ccMesh::resize(), result, ccMesh::SamplePointsPoissonDisk(), ccMesh::SamplePointsUniformly(), ccMesh::SelectByIndex(), ccMesh::setAssociatedCloud(), ccMesh::setTriangle(), ccMesh::setTriangleMtlIndex(), ccMesh::setTriangleNorm(), ccMesh::setTriangleNormalIndexes(), ccMesh::setTriangleNorms(), ccMesh::setTriangles(), ccMesh::setTriangleTexCoordIndexes(), ccMesh::setVertexColor(), ccMesh::setVertexColors(), ccMesh::setVertexNormal(), ccMesh::setVertice(), ccMesh::shiftTriangleIndexes(), ccMesh::shrinkToFit(), ccMesh::shrinkVertexToFit(), ccMesh::SimplifyQuadricDecimation(), ccMesh::SimplifyVertexClustering(), cloudViewer::PointCloudTpl< T >::size(), ccMesh::size(), ccMesh::subdivide(), ccMesh::SubdivideLoop(), ccMesh::SubdivideMidpoint(), ccMesh::swapTriangles(), ccMesh::textures_, ccHObjectCaster::ToPointCloud(), ccMesh::transformTriNormals(), ccMesh::triangle_material_ids_, ccMesh::triangle_uvs_, ccMesh::Triangulate(), ccMesh::TriangulateTwoPolylines(), and type.
Referenced by pybind_geometry().
pybind_trianglemesh_methods()
void cloudViewer::geometry::pybind_trianglemesh_methods (py::module & m)
Definition at line 1259 of file trianglemesh.cpp.
pybind_voxelgrid()
void cloudViewer::geometry::pybind_voxelgrid (py::module & m)
Definition at line 24 of file voxelgrid.cpp.
References cloudViewer::geometry::VoxelGrid::AddVoxel(), cloudViewer::geometry::VoxelGrid::AVG, cloudViewer::geometry::VoxelGrid::CarveDepthMap(), cloudViewer::geometry::VoxelGrid::CarveSilhouette(), cloudViewer::geometry::VoxelGrid::CheckIfIncluded(), cloudViewer::docstring::ClassMethodDocInject(), color, cloudViewer::geometry::Voxel::color_, cloudViewer::geometry::VoxelGrid::CreateDense(), cloudViewer::geometry::VoxelGrid::CreateFromOctree(), cloudViewer::geometry::VoxelGrid::CreateFromPointCloud(), cloudViewer::geometry::VoxelGrid::CreateFromPointCloudWithinBounds(), cloudViewer::geometry::VoxelGrid::CreateFromTriangleMesh(), cloudViewer::geometry::VoxelGrid::CreateFromTriangleMeshWithinBounds(), cloudViewer::geometry::VoxelGrid::GetVoxel(), cloudViewer::geometry::VoxelGrid::GetVoxels(), cloudViewer::geometry::Voxel::grid_index_, cloudViewer::geometry::VoxelGrid::HasColors(), cloudViewer::geometry::VoxelGrid::HasVoxels(), cloudViewer::geometry::VoxelGrid::MAX, cloudViewer::geometry::VoxelGrid::MIN, cloudViewer::geometry::VoxelGrid::origin_, cloudViewer::geometry::VoxelGrid::RemoveVoxel(), cloudViewer::geometry::VoxelGrid::rotation_, cloudViewer::geometry::VoxelGrid::SUM, patch::to_string(), cloudViewer::geometry::VoxelGrid::ToOctree(), and cloudViewer::geometry::VoxelGrid::voxel_size_.
Referenced by pybind_geometry().
pybind_voxelgrid_methods()
void cloudViewer::geometry::pybind_voxelgrid_methods (py::module & m)
Definition at line 244 of file voxelgrid.cpp.
Referenced by pybind_geometry().
Variable Documentation
map_octree_argument_docstrings
const std::unordered_map<std::string, std::string> cloudViewer::geometry::map_octree_argument_docstrings static
Initial value:
= {
                {"origin", "Origin coordinates."},
                {"size", "Size of the Octree."},
                {"color", "Color of the point."},
                {"point", "Coordinates of the point."},
                {"max_depth", "Maximum depth of the octree."},
                {"point_cloud", "Input point cloud."},
                {"size_expand",
                 "A small expansion size such that the octree is slightly "
                 "bigger than the original point cloud bounds to accomodate "
                 "all points."}}
Definition at line 26 of file octree.cpp.
map_shared_argument_docstrings
const std::unordered_map<std::string, std::string> cloudViewer::geometry::map_shared_argument_docstrings static
Initial value:
= {
                {"color", "The color image."},
                {"convert_rgb_to_intensity",
                 "Whether to convert RGB image to intensity image."},
                {"depth", "The depth image."},
                {"depth_scale",
                 "The ratio to scale depth values. The depth values will first "
                 "be scaled and then truncated."},
                {"depth_trunc",
                 "Depth values larger than ``depth_trunc`` gets truncated to "
                 "0. The depth values will first be scaled and then "
                 "truncated."},
                {"filter_type", "The filter type to be applied."},
                {"image", "The Image object."},
                {"image_pyramid", "The ImagePyramid object"},
                {"num_of_levels ", "Levels of the image pyramid"},
                {"with_gaussian_filter",
                 "When ``True``, image in the pyramid will first be filtered "
                 "by a 3x3 Gaussian kernel before down sampling."}}
Definition at line 20 of file image.cpp.