ACloudViewer: cloudViewer::t::io Namespace Reference
cloudViewer::t::io Namespace Reference
Classes
struct PCLPointField
struct PCDHeader
struct ReadAttributePtr
struct WriteAttributePtr
class DepthNoiseSimulator
class CharVector
class NumpyArray
class RealSenseSensor
RealSense camera discovery, configuration, streaming and recording.
class RealSenseSensorConfig
struct RealSenseValidConfigs
class RSBagReader
class RGBDSensor
Interface class for control of RGBD cameras.
class RGBDVideoMetadata
RGBD video metadata.
class RGBDVideoReader
Enumerations
enum class PCDDataType { ASCII = 0 , BINARY = 1 , BINARY_COMPRESSED = 2 }
enum class SensorType { AZURE_KINECT = 0 , REAL_SENSE = 1 }
Functions
bool ReadTriangleMeshUsingASSIMP (const std::string &filename, geometry::TriangleMesh &mesh, const cloudViewer::io::ReadTriangleMeshOptions &params)
static void SetTextureMaterialProperty (aiMaterial *mat, aiScene *scene, int texture_idx, aiTextureType tt, t::geometry::Image &img)
bool WriteTriangleMeshUsingASSIMP (const std::string &filename, const geometry::TriangleMesh &mesh, const bool write_ascii, const bool compressed, const bool write_vertex_normals, const bool write_vertex_colors, const bool write_triangle_uvs, const bool print_progress)
bool ReadImageFromJPG (const std::string &filename, geometry::Image &image)
bool WriteImageToJPG (const std::string &filename, const geometry::Image &image, int quality)
static core::Dtype GetDtypeFromPCDHeaderField (char type, int size)
static bool InitializeHeader (PCDHeader &header)
static bool ReadPCDHeader (FILE *file, PCDHeader &header)
static void ReadASCIIPCDColorsFromField (ReadAttributePtr &attr, const PCLPointField &field, const char *data_ptr, const int index)
template<typename scalar_t >
static void UnpackASCIIPCDElement (scalar_t &data, const char *data_ptr)=delete
template<>
void UnpackASCIIPCDElement< float > (float &data, const char *data_ptr)
template<>
void UnpackASCIIPCDElement< double > (double &data, const char *data_ptr)
template<>
void UnpackASCIIPCDElement< std::int8_t > (std::int8_t &data, const char *data_ptr)
template<>
void UnpackASCIIPCDElement< std::int16_t > (std::int16_t &data, const char *data_ptr)
template<>
void UnpackASCIIPCDElement< std::int32_t > (std::int32_t &data, const char *data_ptr)
template<>
void UnpackASCIIPCDElement< std::int64_t > (std::int64_t &data, const char *data_ptr)
template<>
void UnpackASCIIPCDElement< std::uint8_t > (std::uint8_t &data, const char *data_ptr)
template<>
void UnpackASCIIPCDElement< std::uint16_t > (std::uint16_t &data, const char *data_ptr)
template<>
void UnpackASCIIPCDElement< std::uint32_t > (std::uint32_t &data, const char *data_ptr)
template<>
void UnpackASCIIPCDElement< std::uint64_t > (std::uint64_t &data, const char *data_ptr)
static void ReadASCIIPCDElementsFromField (ReadAttributePtr &attr, const PCLPointField &field, const char *data_ptr, const int index)
static void ReadBinaryPCDColorsFromField (ReadAttributePtr &attr, const PCLPointField &field, const void *data_ptr, const int index)
static void ReadBinaryPCDElementsFromField (ReadAttributePtr &attr, const PCLPointField &field, const void *data_ptr, const int index)
static bool ReadPCDData (FILE *file, PCDHeader &header, t::geometry::PointCloud &pointcloud, const ReadPointCloudOption &params)
static void SetPCDHeaderFieldTypeAndSizeFromDtype (const core::Dtype &dtype, PCLPointField &field)
static bool GenerateHeader (const t::geometry::PointCloud &pointcloud, const bool write_ascii, const bool compressed, PCDHeader &header)
static bool WritePCDHeader (FILE *file, const PCDHeader &header)
template<typename scalar_t >
static void ColorToUint8 (const scalar_t *input_color, std::uint8_t *output_color)
template<>
void ColorToUint8< float > (const float *input_color, std::uint8_t *output_color)
template<>
void ColorToUint8< double > (const double *input_color, std::uint8_t *output_color)
template<>
void ColorToUint8< std::uint8_t > (const std::uint8_t *input_color, std::uint8_t *output_color)
template<>
void ColorToUint8< std::uint16_t > (const std::uint16_t *input_color, std::uint8_t *output_color)
template<>
void ColorToUint8< std::uint32_t > (const std::uint32_t *input_color, std::uint8_t *output_color)
static core::Tensor PackColorsToFloat (const core::Tensor &colors_contiguous)
template<typename scalar_t >
static int WriteElementDataToFileASCII (const scalar_t &data, FILE *file)=delete
template<>
int WriteElementDataToFileASCII< float > (const float &data, FILE *file)
template<>
int WriteElementDataToFileASCII< double > (const double &data, FILE *file)
template<>
int WriteElementDataToFileASCII< std::int8_t > (const std::int8_t &data, FILE *file)
template<>
int WriteElementDataToFileASCII< std::int16_t > (const std::int16_t &data, FILE *file)
template<>
int WriteElementDataToFileASCII< std::int32_t > (const std::int32_t &data, FILE *file)
template<>
int WriteElementDataToFileASCII< std::int64_t > (const std::int64_t &data, FILE *file)
template<>
int WriteElementDataToFileASCII< std::uint8_t > (const std::uint8_t &data, FILE *file)
template<>
int WriteElementDataToFileASCII< std::uint16_t > (const std::uint16_t &data, FILE *file)
template<>
int WriteElementDataToFileASCII< std::uint32_t > (const std::uint32_t &data, FILE *file)
template<>
int WriteElementDataToFileASCII< std::uint64_t > (const std::uint64_t &data, FILE *file)
static bool WritePCDData (FILE *file, const PCDHeader &header, const geometry::PointCloud &pointcloud, const WritePointCloudOption &params)
bool ReadPointCloudFromPCD (const std::string &filename, t::geometry::PointCloud &pointcloud, const ReadPointCloudOption &params)
bool WritePointCloudToPCD (const std::string &filename, const geometry::PointCloud &pointcloud, const WritePointCloudOption &params)
bool ReadPointCloudFromPLY (const std::string &filename, geometry::PointCloud &pointcloud, const cloudViewer::io::ReadPointCloudOption &params)
bool WritePointCloudToPLY (const std::string &filename, const geometry::PointCloud &pointcloud, const cloudViewer::io::WritePointCloudOption &params)
static void SetPNGImageFromImage (const geometry::Image &image, int quality, png_image &pngimage)
bool ReadImageFromPNG (const std::string &filename, geometry::Image &image)
bool WriteImageToPNG (const std::string &filename, const geometry::Image &image, int quality)
bool WriteImageToPNGInMemory (std::vector< uint8_t > &buffer, const t::geometry::Image &image, int quality)
bool ReadPointCloudFromPTS (const std::string &filename, geometry::PointCloud &pointcloud, const ReadPointCloudOption &params)
core::Tensor ConvertColorTensorToUint8 (const core::Tensor &color_in)
bool WritePointCloudToPTS (const std::string &filename, const geometry::PointCloud &pointcloud, const WritePointCloudOption &params)
bool ReadPointCloudFromSPLAT (const std::string &filename, geometry::PointCloud &pointcloud, const cloudViewer::io::ReadPointCloudOption &params)
bool WritePointCloudToSPLAT (const std::string &filename, const geometry::PointCloud &pointcloud, const cloudViewer::io::WritePointCloudOption &params)
cloudViewer::io::FileGeometry ReadFileGeometryTypeTXT (const std::string &path)
bool ReadPointCloudFromTXT (const std::string &filename, geometry::PointCloud &pointcloud, const cloudViewer::io::ReadPointCloudOption &params)
bool WritePointCloudToTXT (const std::string &filename, const geometry::PointCloud &pointcloud, const cloudViewer::io::WritePointCloudOption &params)
cloudViewer::io::FileGeometry ReadFileGeometryTypeXYZI (const std::string &path)
bool ReadPointCloudFromXYZI (const std::string &filename, geometry::PointCloud &pointcloud, const cloudViewer::io::ReadPointCloudOption &params)
bool WritePointCloudToXYZI (const std::string &filename, const geometry::PointCloud &pointcloud, const cloudViewer::io::WritePointCloudOption &params)
void WriteHashMap (const std::string &file_name, const core::HashMap &hashmap)
core::HashMap ReadHashMap (const std::string &file_name)
std::shared_ptr< geometry::Image > CreateImageFromFile (const std::string &filename)
bool ReadImage (const std::string &filename, geometry::Image &image)
bool WriteImage (const std::string &filename, const geometry::Image &image, int quality)
static char BigEndianChar ()
static char DtypeToChar (const core::Dtype &dtype)
static CharVector CreateNumpyHeader (const core::SizeVector &shape, const core::Dtype &dtype)
static std::tuple< core::SizeVector, char, int64_t, bool > ParsePropertyDict (const std::string &header)
static size_t ParseNpyPreamble (const char *preamble)
static std::tuple< core::SizeVector, char, int64_t, bool > ParseNpyHeaderFromFile (FILE *fp)
static std::tuple< core::SizeVector, char, int64_t, bool > ParseNpyHeaderFromBuffer (const char *buffer)
static std::tuple< size_t, size_t, size_t > ParseZipFooter (FILE *fp)
static void WriteNpzOneTensor (const std::string &file_name, const std::string &tensor_name, const core::Tensor &tensor, bool append)
static void WriteNpzEmpty (const std::string &file_name)
static NumpyArray CreateNumpyArrayFromFile (FILE *fp)
static NumpyArray CreateNumpyArrayFromCompressedFile (FILE *fp, uint32_t num_compressed_bytes, uint32_t num_uncompressed_bytes)
core::Tensor ReadNpy (const std::string &file_name)
void WriteNpy (const std::string &file_name, const core::Tensor &tensor)
std::unordered_map< std::string, core::Tensor > ReadNpz (const std::string &file_name)
void WriteNpz (const std::string &file_name, const std::unordered_map< std::string, core::Tensor > &tensor_map)
std::shared_ptr< geometry::PointCloud > CreatePointCloudFromFile (const std::string &filename, const std::string &format, bool print_progress)
bool ReadPointCloud (const std::string &filename, geometry::PointCloud &pointcloud, const cloudViewer::io::ReadPointCloudOption &params)
bool ReadPointCloud (const std::string &filename, geometry::PointCloud &pointcloud, const std::string &file_format, bool remove_nan_points, bool remove_infinite_points, bool print_progress)
bool WritePointCloud (const std::string &filename, const geometry::PointCloud &pointcloud, const cloudViewer::io::WritePointCloudOption &params)
bool WritePointCloud (const std::string &filename, const geometry::PointCloud &pointcloud, bool write_ascii, bool compressed, bool print_progress)
bool ReadPointCloudFromNPZ (const std::string &filename, geometry::PointCloud &pointcloud, const ReadPointCloudOption &params)
bool WritePointCloudToNPZ (const std::string &filename, const geometry::PointCloud &pointcloud, const WritePointCloudOption &params)
STRINGIFY_ENUM (rs2_stream, { {RS2_STREAM_ANY, "RS2_STREAM_ANY"}, {RS2_STREAM_DEPTH, "RS2_STREAM_DEPTH"}, {RS2_STREAM_COLOR, "RS2_STREAM_COLOR"}, {RS2_STREAM_INFRARED, "RS2_STREAM_INFRARED"}, {RS2_STREAM_FISHEYE, "RS2_STREAM_FISHEYE"}, {RS2_STREAM_GYRO, "RS2_STREAM_GYRO"}, {RS2_STREAM_ACCEL, "RS2_STREAM_ACCEL"}, {RS2_STREAM_GPIO, "RS2_STREAM_GPIO"}, {RS2_STREAM_POSE, "RS2_STREAM_POSE"}, {RS2_STREAM_CONFIDENCE, "RS2_STREAM_CONFIDENCE"} })
RS2 stream types.
STRINGIFY_ENUM (rs2_format, { {RS2_FORMAT_ANY, "RS2_FORMAT_ANY"}, {RS2_FORMAT_Z16, "RS2_FORMAT_Z16"}, {RS2_FORMAT_DISPARITY16, "RS2_FORMAT_DISPARITY16"}, {RS2_FORMAT_XYZ32F, "RS2_FORMAT_XYZ32F"}, {RS2_FORMAT_YUYV, "RS2_FORMAT_YUYV"}, {RS2_FORMAT_RGB8, "RS2_FORMAT_RGB8"}, {RS2_FORMAT_BGR8, "RS2_FORMAT_BGR8"}, {RS2_FORMAT_RGBA8, "RS2_FORMAT_RGBA8"}, {RS2_FORMAT_BGRA8, "RS2_FORMAT_BGRA8"}, {RS2_FORMAT_Y8, "RS2_FORMAT_Y8"}, {RS2_FORMAT_Y16, "RS2_FORMAT_Y16"}, {RS2_FORMAT_RAW10, "RS2_FORMAT_RAW10"}, {RS2_FORMAT_RAW16, "RS2_FORMAT_RAW16"}, {RS2_FORMAT_RAW8, "RS2_FORMAT_RAW8"}, {RS2_FORMAT_UYVY, "RS2_FORMAT_UYVY"}, {RS2_FORMAT_MOTION_RAW, "RS2_FORMAT_MOTION_RAW"}, {RS2_FORMAT_MOTION_XYZ32F, "RS2_FORMAT_MOTION_XYZ32F"}, {RS2_FORMAT_GPIO_RAW, "RS2_FORMAT_GPIO_RAW"}, {RS2_FORMAT_6DOF, "RS2_FORMAT_6DOF"}, {RS2_FORMAT_DISPARITY32, "RS2_FORMAT_DISPARITY32"}, {RS2_FORMAT_Y10BPACK, "RS2_FORMAT_Y10BPACK"}, {RS2_FORMAT_DISTANCE, "RS2_FORMAT_DISTANCE"}, {RS2_FORMAT_MJPEG, "RS2_FORMAT_MJPEG"}, {RS2_FORMAT_Y8I, "RS2_FORMAT_Y8I"}, {RS2_FORMAT_Y12I, "RS2_FORMAT_Y12I"}, {RS2_FORMAT_INZI, "RS2_FORMAT_INZI"}, {RS2_FORMAT_INVI, "RS2_FORMAT_INVI"}, {RS2_FORMAT_W10, "RS2_FORMAT_W10"}, {RS2_FORMAT_Z16H, "RS2_FORMAT_Z16H"} })
RS2 pixel formats.
STRINGIFY_ENUM (rs2_l500_visual_preset, { {RS2_L500_VISUAL_PRESET_DEFAULT, "RS2_L500_VISUAL_PRESET_DEFAULT"}, {RS2_L500_VISUAL_PRESET_CUSTOM, "RS2_L500_VISUAL_PRESET_CUSTOM"}, {RS2_L500_VISUAL_PRESET_NO_AMBIENT, "RS2_L500_VISUAL_PRESET_NO_AMBIENT"}, {RS2_L500_VISUAL_PRESET_LOW_AMBIENT, "RS2_L500_VISUAL_PRESET_LOW_AMBIENT"}, {RS2_L500_VISUAL_PRESET_MAX_RANGE, "RS2_L500_VISUAL_PRESET_MAX_RANGE"}, {RS2_L500_VISUAL_PRESET_SHORT_RANGE, "RS2_L500_VISUAL_PRESET_SHORT_RANGE"} })
RS2 visual presets for L500 devices.
STRINGIFY_ENUM (rs2_rs400_visual_preset, { {RS2_RS400_VISUAL_PRESET_DEFAULT, "RS2_RS400_VISUAL_PRESET_DEFAULT"}, {RS2_RS400_VISUAL_PRESET_CUSTOM, "RS2_RS400_VISUAL_PRESET_CUSTOM"}, {RS2_RS400_VISUAL_PRESET_HAND, "RS2_RS400_VISUAL_PRESET_HAND"}, {RS2_RS400_VISUAL_PRESET_HIGH_ACCURACY, "RS2_RS400_VISUAL_PRESET_HIGH_ACCURACY"}, {RS2_RS400_VISUAL_PRESET_HIGH_DENSITY, "RS2_RS400_VISUAL_PRESET_HIGH_DENSITY"}, {RS2_RS400_VISUAL_PRESET_MEDIUM_DENSITY, "RS2_RS400_VISUAL_PRESET_MEDIUM_DENSITY"}, {RS2_RS400_VISUAL_PRESET_REMOVE_IR_PATTERN, "RS2_RS400_VISUAL_PRESET_REMOVE_IR_PATTERN"} })
RS2 visual presets for RS400 devices.
STRINGIFY_ENUM (rs2_sr300_visual_preset, { {RS2_SR300_VISUAL_PRESET_DEFAULT, "RS2_SR300_VISUAL_PRESET_DEFAULT"}, {RS2_SR300_VISUAL_PRESET_SHORT_RANGE, "RS2_SR300_VISUAL_PRESET_SHORT_RANGE"}, {RS2_SR300_VISUAL_PRESET_LONG_RANGE, "RS2_SR300_VISUAL_PRESET_LONG_RANGE"}, {RS2_SR300_VISUAL_PRESET_BACKGROUND_SEGMENTATION, "RS2_SR300_VISUAL_PRESET_BACKGROUND_SEGMENTATION"}, {RS2_SR300_VISUAL_PRESET_GESTURE_RECOGNITION, "RS2_SR300_VISUAL_PRESET_GESTURE_RECOGNITION"}, {RS2_SR300_VISUAL_PRESET_OBJECT_SCANNING, "RS2_SR300_VISUAL_PRESET_OBJECT_SCANNING"}, {RS2_SR300_VISUAL_PRESET_FACE_ANALYTICS, "RS2_SR300_VISUAL_PRESET_FACE_ANALYTICS"}, {RS2_SR300_VISUAL_PRESET_FACE_LOGIN, "RS2_SR300_VISUAL_PRESET_FACE_LOGIN"}, {RS2_SR300_VISUAL_PRESET_GR_CURSOR, "RS2_SR300_VISUAL_PRESET_GR_CURSOR"}, {RS2_SR300_VISUAL_PRESET_MID_RANGE, "RS2_SR300_VISUAL_PRESET_MID_RANGE"}, {RS2_SR300_VISUAL_PRESET_IR_ONLY, "RS2_SR300_VISUAL_PRESET_IR_ONLY"} })
std::shared_ptr< geometry::TriangleMesh > CreateMeshFromFile (const std::string &filename, bool print_progress)
bool ReadTriangleMesh (const std::string &filename, geometry::TriangleMesh &mesh, cloudViewer::io::ReadTriangleMeshOptions params)
bool WriteTriangleMesh (const std::string &filename, const geometry::TriangleMesh &mesh, bool write_ascii, bool compressed, bool write_vertex_normals, bool write_vertex_colors, bool write_triangle_uvs, bool print_progress)
bool ReadTriangleMeshFromNPZ (const std::string &filename, geometry::TriangleMesh &mesh, const cloudViewer::io::ReadTriangleMeshOptions &params)
bool WriteTriangleMeshToNPZ (const std::string &filename, const geometry::TriangleMesh &mesh, const bool write_ascii, const bool compressed, const bool write_vertex_normals, const bool write_vertex_colors, const bool write_triangle_uvs, const bool print_progress)
Variables
const unsigned int kPostProcessFlags_compulsory
const unsigned int kPostProcessFlags_fast
constexpr int kCloudViewerImageIODefaultQuality = -1
static const std::unordered_map< std::string, std::function< bool(const std::string &, geometry::PointCloud &, const cloudViewer::io::ReadPointCloudOption &)> > file_extension_to_pointcloud_read_function
static const std::unordered_map< std::string, std::function< bool(const std::string &, const geometry::PointCloud &, const cloudViewer::io::WritePointCloudOption &)> > file_extension_to_pointcloud_write_function
static std::unordered_map< std::string, std::string > standard_config
static const std::unordered_map< std::string, std::function< bool(const std::string &, geometry::TriangleMesh &, const cloudViewer::io::ReadTriangleMeshOptions &)> > file_extension_to_trianglemesh_read_function
static const std::unordered_map< std::string, std::function< bool(const std::string &, const geometry::TriangleMesh &, const bool, const bool, const bool, const bool, const bool, const bool)> > file_extension_to_trianglemesh_write_function
Enumeration Type Documentation
PCDDataType
enum cloudViewer::t::io::PCDDataType strong
Enumerator
ASCII
BINARY
BINARY_COMPRESSED
Definition at line 34 of file FilePCD.cpp.
SensorType
enum cloudViewer::t::io::SensorType strong
Enumerator
AZURE_KINECT
REAL_SENSE
Definition at line 24 of file RGBDVideoMetadata.h.
Function Documentation
BigEndianChar()
static char cloudViewer::t::io::BigEndianChar () static
Definition at line 127 of file NumpyIO.cpp.
Referenced by CreateNumpyHeader().
ColorToUint8()
template<typename scalar_t > static void cloudViewer::t::io::ColorToUint8 (const scalar_t * input_color, std::uint8_t * output_color) static
Definition at line 837 of file FilePCD.cpp.
References LogError.
ColorToUint8< double >()
template<> void cloudViewer::t::io::ColorToUint8< double > (const double * input_color, std::uint8_t * output_color)
Definition at line 857 of file FilePCD.cpp.
References max(), and min().
ColorToUint8< float >()
template<> void cloudViewer::t::io::ColorToUint8< float > (const float * input_color, std::uint8_t * output_color)
Definition at line 845 of file FilePCD.cpp.
References max(), and min().
ColorToUint8< std::uint16_t >()
template<> void cloudViewer::t::io::ColorToUint8< std::uint16_t > (const std::uint16_t * input_color, std::uint8_t * output_color)
Definition at line 879 of file FilePCD.cpp.
References max().
ColorToUint8< std::uint32_t >()
template<> void cloudViewer::t::io::ColorToUint8< std::uint32_t > (const std::uint32_t * input_color, std::uint8_t * output_color)
Definition at line 892 of file FilePCD.cpp.
References max().
ColorToUint8< std::uint8_t >()
template<> void cloudViewer::t::io::ColorToUint8< std::uint8_t > (const std::uint8_t * input_color, std::uint8_t * output_color)
Definition at line 870 of file FilePCD.cpp.
ConvertColorTensorToUint8()
core::Tensor cloudViewer::t::io::ConvertColorTensorToUint8 (const core::Tensor & color_in)
Definition at line 178 of file FilePTS.cpp.
References cloudViewer::core::Bool, cloudViewer::core::Tensor::Clip(), cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::Mul(), cloudViewer::core::Tensor::Round(), cloudViewer::core::Tensor::To(), and cloudViewer::core::UInt8.
Referenced by WritePointCloudToPTS().
CreateImageFromFile()
std::shared_ptr< geometry::Image > cloudViewer::t::io::CreateImageFromFile (const std::string & filename)
Factory function to create an image from a file (ImageFactory.cpp) Return an empty image if fail to read the file.
Definition at line 48 of file ImageIO.cpp.
References image, and ReadImage().
CreateMeshFromFile()
std::shared_ptr< geometry::TriangleMesh > cloudViewer::t::io::CreateMeshFromFile (const std::string & filename, bool print_progress = false)
Factory function to create a mesh from a file (TriangleMeshFactory.cpp) Return an empty mesh if fail to read the file.
Definition at line 52 of file TriangleMeshIO.cpp.
References cloudViewer::io::ReadTriangleMeshOptions::print_progress, and ReadTriangleMesh().
CreateNumpyArrayFromCompressedFile()
static NumpyArray cloudViewer::t::io::CreateNumpyArrayFromCompressedFile (FILE * fp, uint32_t num_compressed_bytes, uint32_t num_uncompressed_bytes) static
Definition at line 612 of file NumpyIO.cpp.
References cloudViewer::t::io::CharVector::Data(), cloudViewer::t::io::NumpyArray::GetDataPtr(), LogError, cloudViewer::t::io::NumpyArray::NumBytes(), offset, ParseNpyHeaderFromBuffer(), and type.
Referenced by ReadNpz().
CreateNumpyArrayFromFile()
static NumpyArray cloudViewer::t::io::CreateNumpyArrayFromFile (FILE * fp) static
Definition at line 591 of file NumpyIO.cpp.
References cloudViewer::t::io::NumpyArray::GetDataPtr(), LogError, cloudViewer::t::io::NumpyArray::NumBytes(), ParseNpyHeaderFromFile(), and type.
Referenced by ReadNpy(), and ReadNpz().
CreateNumpyHeader()
static CharVector cloudViewer::t::io::CreateNumpyHeader (const core::SizeVector & shape, const core::Dtype & dtype) static
Definition at line 157 of file NumpyIO.cpp.
References cloudViewer::t::io::CharVector::Append(), BigEndianChar(), cloudViewer::core::Dtype::ByteSize(), DtypeToChar(), format, cloudViewer::core::SmallVectorBase< Size_T >::size(), and cloudViewer::t::io::CharVector::Size().
Referenced by cloudViewer::t::io::NumpyArray::Save(), and WriteNpzOneTensor().
CreatePointCloudFromFile()
std::shared_ptr< geometry::PointCloud > cloudViewer::t::io::CreatePointCloudFromFile (const std::string & filename, const std::string & format = "auto", bool print_progress = false)
Factory function to create a pointcloud from a file Return an empty pointcloud if fail to read the file.
Definition at line 62 of file PointCloudIO.cpp.
References format, and ReadPointCloud().
Referenced by cloudViewer::t::pipelines::slac::PreprocessPointClouds().
DtypeToChar()
static char cloudViewer::t::io::DtypeToChar (const core::Dtype & dtype) static
Definition at line 132 of file NumpyIO.cpp.
References cloudViewer::core::Bool, cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Int16, cloudViewer::core::Int32, cloudViewer::core::Int64, cloudViewer::core::Int8, LogError, cloudViewer::core::Dtype::ToString(), cloudViewer::core::UInt16, cloudViewer::core::UInt32, cloudViewer::core::UInt64, and cloudViewer::core::UInt8.
Referenced by CreateNumpyHeader().
GenerateHeader()
static bool cloudViewer::t::io::GenerateHeader (const t::geometry::PointCloud & pointcloud, const bool write_ascii, const bool compressed, PCDHeader & header) static
Definition at line 684 of file FilePCD.cpp.
References ASCII, BINARY, BINARY_COMPRESSED, cloudViewer::t::io::PCLPointField::count, cloudViewer::t::io::PCDHeader::datatype, cloudViewer::t::io::PCDHeader::elementnum, cloudViewer::t::io::PCDHeader::fields, cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointColors(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), cloudViewer::t::geometry::PointCloud::HasPointPositions(), cloudViewer::t::io::PCDHeader::height, LogWarning, cloudViewer::t::io::PCLPointField::name, cloudViewer::t::io::PCDHeader::points, cloudViewer::t::io::PCDHeader::pointsize, SetPCDHeaderFieldTypeAndSizeFromDtype(), cloudViewer::t::io::PCLPointField::size, cloudViewer::core::SizeVector::ToString(), cloudViewer::t::io::PCLPointField::type, cloudViewer::t::io::PCDHeader::version, and cloudViewer::t::io::PCDHeader::width.
Referenced by cloudViewer::io::WritePointCloudToPCD(), and WritePointCloudToPCD().
GetDtypeFromPCDHeaderField()
static core::Dtype cloudViewer::t::io::GetDtypeFromPCDHeaderField (char type, int size) static
Definition at line 91 of file FilePCD.cpp.
References cloudViewer::core::Dtype::Float32, cloudViewer::core::Dtype::Float64, cloudViewer::core::Dtype::Int16, cloudViewer::core::Dtype::Int32, cloudViewer::core::Dtype::Int64, cloudViewer::core::Dtype::Int8, LogError, size, type, cloudViewer::core::Dtype::UInt16, cloudViewer::core::Dtype::UInt32, cloudViewer::core::Dtype::UInt64, and cloudViewer::core::Dtype::UInt8.
Referenced by InitializeHeader(), ReadASCIIPCDElementsFromField(), and ReadBinaryPCDElementsFromField().
InitializeHeader()
static bool cloudViewer::t::io::InitializeHeader (PCDHeader & header) static
Definition at line 123 of file FilePCD.cpp.
References cloudViewer::t::io::PCDHeader::attr_dtype, cloudViewer::t::io::PCDHeader::fields, GetDtypeFromPCDHeaderField(), cloudViewer::t::io::PCDHeader::has_attr, LogWarning, cloudViewer::t::io::PCDHeader::points, and cloudViewer::t::io::PCDHeader::pointsize.
Referenced by ReadPCDHeader().
PackColorsToFloat()
static core::Tensor cloudViewer::t::io::PackColorsToFloat (const core::Tensor & colors_contiguous) static
Definition at line 904 of file FilePCD.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::Empty(), cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDtype(), and cloudViewer::core::Tensor::GetLength().
Referenced by WritePCDData().
ParseNpyHeaderFromBuffer()
static std::tuple<core::SizeVector, char, int64_t, bool> cloudViewer::t::io::ParseNpyHeaderFromBuffer (const char * buffer) static
Definition at line 325 of file NumpyIO.cpp.
References ParseNpyPreamble(), and ParsePropertyDict().
Referenced by CreateNumpyArrayFromCompressedFile().
ParseNpyHeaderFromFile()
static std::tuple<core::SizeVector, char, int64_t, bool> cloudViewer::t::io::ParseNpyHeaderFromFile (FILE * fp) static
Definition at line 303 of file NumpyIO.cpp.
References cloudViewer::t::io::CharVector::Data(), LogError, ParseNpyPreamble(), and ParsePropertyDict().
Referenced by CreateNumpyArrayFromFile().
ParseNpyPreamble()
static size_t cloudViewer::t::io::ParseNpyPreamble (const char * preamble) static
Definition at line 281 of file NumpyIO.cpp.
References LogError.
Referenced by ParseNpyHeaderFromBuffer(), and ParseNpyHeaderFromFile().
ParsePropertyDict()
static std::tuple<core::SizeVector, char, int64_t, bool> cloudViewer::t::io::ParsePropertyDict (const std::string & header) static
Definition at line 207 of file NumpyIO.cpp.
References cloudViewer::core::SmallVectorImpl< T >::clear(), LogError, cloudViewer::core::SmallVectorTemplateBase< T, bool >::push_back(), and type.
Referenced by ParseNpyHeaderFromBuffer(), and ParseNpyHeaderFromFile().
ParseZipFooter()
static std::tuple<size_t, size_t, size_t> cloudViewer::t::io::ParseZipFooter (FILE * fp) static
Definition at line 331 of file NumpyIO.cpp.
References cloudViewer::t::io::CharVector::Data(), LogError, and SEEK_END.
Referenced by WriteNpzOneTensor().
ReadASCIIPCDColorsFromField()
static void cloudViewer::t::io::ReadASCIIPCDColorsFromField (ReadAttributePtr & attr, const PCLPointField & field, const char * data_ptr, const int index) static
Definition at line 302 of file FilePCD.cpp.
References cloudViewer::t::io::ReadAttributePtr::data_ptr_, cloudViewer::t::io::ReadAttributePtr::row_length_, cloudViewer::t::io::PCLPointField::size, and cloudViewer::t::io::PCLPointField::type.
Referenced by ReadPCDData().
ReadASCIIPCDElementsFromField()
static void cloudViewer::t::io::ReadASCIIPCDElementsFromField (ReadAttributePtr & attr, const PCLPointField & field, const char * data_ptr, const int index) static
Definition at line 407 of file FilePCD.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, GetDtypeFromPCDHeaderField(), cloudViewer::t::io::PCLPointField::size, and cloudViewer::t::io::PCLPointField::type.
Referenced by ReadPCDData().
ReadBinaryPCDColorsFromField()
static void cloudViewer::t::io::ReadBinaryPCDColorsFromField (ReadAttributePtr & attr, const PCLPointField & field, const void * data_ptr, const int index) static
Definition at line 421 of file FilePCD.cpp.
References cloudViewer::t::io::ReadAttributePtr::data_ptr_, cloudViewer::t::io::ReadAttributePtr::row_length_, and cloudViewer::t::io::PCLPointField::size.
Referenced by ReadPCDData().
ReadBinaryPCDElementsFromField()
static void cloudViewer::t::io::ReadBinaryPCDElementsFromField (ReadAttributePtr & attr, const PCLPointField & field, const void * data_ptr, const int index) static
Definition at line 443 of file FilePCD.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, GetDtypeFromPCDHeaderField(), cloudViewer::t::io::PCLPointField::size, and cloudViewer::t::io::PCLPointField::type.
Referenced by ReadPCDData().
ReadFileGeometryTypeTXT()
cloudViewer::io::FileGeometry cloudViewer::t::io::ReadFileGeometryTypeTXT (const std::string & path)
Definition at line 23 of file FileTXT.cpp.
References cloudViewer::io::CONTAINS_POINTS.
ReadFileGeometryTypeXYZI()
cloudViewer::io::FileGeometry cloudViewer::t::io::ReadFileGeometryTypeXYZI (const std::string & path)
Definition at line 24 of file FileXYZI.cpp.
References cloudViewer::io::CONTAINS_POINTS.
ReadHashMap()
core::HashMap cloudViewer::t::io::ReadHashMap (const std::string & filename)
Read a hash map's keys and values from a npz file at 'key' and 'value'. Return a hash map on CPU.
Parameters
filename The npz file name to read from.
Definition at line 48 of file HashMapIO.cpp.
References cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), format, cloudViewer::core::Tensor::GetDtype(), cloudViewer::core::Tensor::GetLength(), cloudViewer::core::Tensor::GetShape(), and ReadNpz().
Referenced by cloudViewer::core::HashMap::Load(), and cloudViewer::core::HashSet::Load().
ReadImage()
bool cloudViewer::t::io::ReadImage (const std::string & filename, geometry::Image & image)
The general entrance for reading an Image from a file The function calls read functions based on the extension name of filename.
Parameters
filename Full path to image. Supported file formats are png, jpg/jpeg.
image An object of type cloudViewer::t::geometry::Image.
Returns
return true if the read function is successful, false otherwise.
Definition at line 55 of file ImageIO.cpp.
References image, and LogWarning.
Referenced by CreateImageFromFile().
ReadImageFromJPG()
bool cloudViewer::t::io::ReadImageFromJPG (const std::string & filename, geometry::Image & image)
Definition at line 41 of file FileJPG.cpp.
References cloudViewer::utility::filesystem::FOpen(), image, LogWarning, cloudViewer::core::MemoryManager::MemcpyFromHost(), NULL, TRUE, and cloudViewer::core::UInt8.
ReadImageFromPNG()
bool cloudViewer::t::io::ReadImageFromPNG (const std::string & filename, geometry::Image & image)
Definition at line 39 of file FilePNG.cpp.
References image, LogWarning, NULL, cloudViewer::core::UInt16, and cloudViewer::core::UInt8.
ReadNpy()
core::Tensor cloudViewer::t::io::ReadNpy (const std::string & file_name)
Read Numpy .npy file to a tensor.
Parameters
file_name The file name to read from.
Definition at line 662 of file NumpyIO.cpp.
References CreateNumpyArrayFromFile(), cloudViewer::utility::filesystem::CFile::GetError(), cloudViewer::utility::filesystem::CFile::GetFILE(), LogError, cloudViewer::utility::filesystem::CFile::Open(), and cloudViewer::t::io::NumpyArray::ToTensor().
Referenced by cloudViewer::core::Tensor::Load().
ReadNpz()
std::unordered_map< std::string, core::Tensor > cloudViewer::t::io::ReadNpz (const std::string & file_name)
Read Numpy .npz file to an unordered_map from string to tensor.
Parameters
file_name The file name to read from.
Definition at line 675 of file NumpyIO.cpp.
References cloudViewer::t::io::CharVector::Begin(), CreateNumpyArrayFromCompressedFile(), CreateNumpyArrayFromFile(), cloudViewer::t::io::CharVector::Data(), cloudViewer::t::io::CharVector::End(), cloudViewer::utility::filesystem::CFile::GetError(), cloudViewer::utility::filesystem::CFile::GetFILE(), LogError, cloudViewer::utility::filesystem::CFile::Open(), and cloudViewer::t::io::NumpyArray::ToTensor().
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::Load(), ReadHashMap(), ReadPointCloudFromNPZ(), and ReadTriangleMeshFromNPZ().
ReadPCDData()
static bool cloudViewer::t::io::ReadPCDData (FILE * file, PCDHeader & header, t::geometry::PointCloud & pointcloud, const ReadPointCloudOption & params) static
Definition at line 457 of file FilePCD.cpp.
References ASCII, cloudViewer::t::io::PCDHeader::attr_dtype, BINARY, BINARY_COMPRESSED, cloudViewer::t::geometry::PointCloud::Clear(), colors, cloudViewer::t::io::PCDHeader::datatype, DEFAULT_IO_BUFFER_SIZE, cloudViewer::t::io::PCDHeader::elementnum, cloudViewer::core::Tensor::Empty(), cloudViewer::t::io::PCDHeader::fields, cloudViewer::utility::CountingProgressReporter::Finish(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointColors(), cloudViewer::t::geometry::PointCloud::GetPointNormals(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::io::PCDHeader::has_attr, LogDebug, LogWarning, params, cloudViewer::t::io::PCDHeader::points, cloudViewer::t::io::PCDHeader::pointsize, ReadASCIIPCDColorsFromField(), ReadASCIIPCDElementsFromField(), ReadBinaryPCDColorsFromField(), ReadBinaryPCDElementsFromField(), cloudViewer::t::geometry::PointCloud::SetPointAttr(), cloudViewer::t::geometry::PointCloud::SetPointColors(), cloudViewer::t::geometry::PointCloud::SetPointNormals(), cloudViewer::t::geometry::PointCloud::SetPointPositions(), cloudViewer::utility::CountingProgressReporter::SetTotal(), cloudViewer::utility::SplitString(), cloudViewer::core::UInt8, and cloudViewer::utility::CountingProgressReporter::Update().
Referenced by cloudViewer::io::ReadPointCloudFromPCD(), and ReadPointCloudFromPCD().
ReadPCDHeader()
static bool cloudViewer::t::io::ReadPCDHeader (FILE * file, PCDHeader & header) static
Definition at line 197 of file FilePCD.cpp.
References ASCII, BINARY, BINARY_COMPRESSED, count_offset, cloudViewer::t::io::PCDHeader::datatype, DEFAULT_IO_BUFFER_SIZE, cloudViewer::t::io::PCDHeader::elementnum, cloudViewer::t::io::PCDHeader::fields, cloudViewer::t::io::PCDHeader::height, InitializeHeader(), LogWarning, offset, cloudViewer::t::io::PCDHeader::points, cloudViewer::t::io::PCDHeader::pointsize, cloudViewer::utility::SplitString(), cloudViewer::t::io::PCDHeader::version, cloudViewer::t::io::PCDHeader::viewpoint, and cloudViewer::t::io::PCDHeader::width.
Referenced by cloudViewer::io::ReadPointCloudFromPCD(), and ReadPointCloudFromPCD().
ReadPointCloud() [1/2]
bool cloudViewer::t::io::ReadPointCloud (const std::string & filename, geometry::PointCloud & pointcloud, const ReadPointCloudOption & params = {})
The general entrance for reading a PointCloud from a file The function calls read functions based on the extension name of filename. See ReadPointCloudOption for additional options you can pass.
Returns
return true if the read function is successful, false otherwise.
Definition at line 72 of file PointCloudIO.cpp.
References file_extension_to_pointcloud_read_function, format, cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), LogDebug, LogError, LogWarning, and params.
Referenced by CreatePointCloudFromFile(), and ReadPointCloud().
ReadPointCloud() [2/2]
bool cloudViewer::t::io::ReadPointCloud (const std::string & filename, geometry::PointCloud & pointcloud, const std::string & file_format, bool remove_nan_points, bool remove_infinite_points, bool print_progress)
Definition at line 112 of file PointCloudIO.cpp.
References format, cloudViewer::io::ReadPointCloudOption::format, cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), ReadPointCloud(), cloudViewer::io::ReadPointCloudOption::remove_infinite_points, cloudViewer::io::ReadPointCloudOption::remove_nan_points, cloudViewer::utility::ToUpper(), and cloudViewer::io::ReadPointCloudOption::update_progress.
ReadPointCloudFromNPZ()
bool cloudViewer::t::io::ReadPointCloudFromNPZ (const std::string & filename, geometry::PointCloud & pointcloud, const ReadPointCloudOption & params)
Definition at line 178 of file PointCloudIO.cpp.
References ReadNpz().
ReadPointCloudFromPCD()
bool cloudViewer::t::io::ReadPointCloudFromPCD (const std::string & filename, t::geometry::PointCloud & pointcloud, const ReadPointCloudOption & params)
Definition at line 1140 of file FilePCD.cpp.
References cloudViewer::t::io::PCDHeader::datatype, cloudViewer::t::io::PCDHeader::fields, cloudViewer::utility::filesystem::FOpen(), cloudViewer::t::io::PCDHeader::has_attr, LogDebug, LogWarning, NULL, params, cloudViewer::t::io::PCDHeader::points, cloudViewer::t::io::PCDHeader::pointsize, ReadPCDData(), and ReadPCDHeader().
ReadPointCloudFromPLY()
bool cloudViewer::t::io::ReadPointCloudFromPLY (const std::string & filename, geometry::PointCloud & pointcloud, const cloudViewer::io::ReadPointCloudOption & params)
Definition at line 176 of file FilePLY.cpp.
References DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::Empty(), cloudViewer::utility::CountingProgressReporter::Finish(), cloudViewer::core::Float32, cloudViewer::t::geometry::PointCloud::GetDevice(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::IsGaussianSplat(), LogDebug, LogError, LogWarning, name, offset, params, cloudViewer::t::geometry::PointCloud::SetPointAttr(), cloudViewer::utility::CountingProgressReporter::SetTotal(), size, stride, type, and cloudViewer::core::Undefined.
ReadPointCloudFromPTS()
bool cloudViewer::t::io::ReadPointCloudFromPTS (const std::string & filename, geometry::PointCloud & pointcloud, const ReadPointCloudOption & params)
Definition at line 23 of file FilePTS.cpp.
References cloudViewer::t::geometry::PointCloud::Clear(), cloudViewer::utility::CountingProgressReporter::Finish(), cloudViewer::core::Float32, format, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::utility::filesystem::CFile::GetFILE(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointColors(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), LogWarning, cloudViewer::utility::filesystem::CFile::Open(), params, cloudViewer::utility::filesystem::CFile::ReadLine(), cloudViewer::t::geometry::PointCloud::SetPointAttr(), cloudViewer::t::geometry::PointCloud::SetPointColors(), cloudViewer::t::geometry::PointCloud::SetPointPositions(), cloudViewer::utility::CountingProgressReporter::SetTotal(), cloudViewer::utility::SplitString(), cloudViewer::core::UInt8, and cloudViewer::utility::CountingProgressReporter::Update().
ReadPointCloudFromSPLAT()
bool cloudViewer::t::io::ReadPointCloudFromSPLAT (const std::string & filename, geometry::PointCloud & pointcloud, const cloudViewer::io::ReadPointCloudOption & params)
Definition at line 84 of file FileSPLAT.cpp.
References cloudViewer::t::geometry::PointCloud::Clear(), cloudViewer::utility::filesystem::CFile::CurPos(), cloudViewer::core::Tensor::Empty(), cloudViewer::utility::CountingProgressReporter::Finish(), cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::utility::filesystem::CFile::GetFileSize(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), LogError, LogWarning, cloudViewer::utility::filesystem::CFile::Open(), params, cloudViewer::utility::filesystem::CFile::ReadData(), cloudViewer::t::geometry::PointCloud::SetPointAttr(), cloudViewer::t::geometry::PointCloud::SetPointPositions(), cloudViewer::utility::CountingProgressReporter::SetTotal(), and cloudViewer::utility::CountingProgressReporter::Update().
ReadPointCloudFromTXT()
bool cloudViewer::t::io::ReadPointCloudFromTXT (const std::string & filename, geometry::PointCloud & pointcloud, const cloudViewer::io::ReadPointCloudOption & params)
Definition at line 27 of file FileTXT.cpp.
References cloudViewer::t::geometry::PointCloud::Clear(), cloudViewer::utility::filesystem::CFile::CurPos(), cloudViewer::utility::CountingProgressReporter::Finish(), cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), cloudViewer::utility::filesystem::CFile::GetFileSize(), cloudViewer::utility::filesystem::CFile::GetNumLines(), LogWarning, cloudViewer::utility::filesystem::CFile::Open(), params, cloudViewer::utility::filesystem::CFile::ReadLine(), cloudViewer::t::geometry::PointCloud::SetPointAttr(), cloudViewer::t::geometry::PointCloud::SetPointPositions(), cloudViewer::utility::CountingProgressReporter::SetTotal(), and cloudViewer::utility::CountingProgressReporter::Update().
ReadPointCloudFromXYZI()
bool cloudViewer::t::io::ReadPointCloudFromXYZI (const std::string & filename, geometry::PointCloud & pointcloud, const cloudViewer::io::ReadPointCloudOption & params)
Definition at line 29 of file FileXYZI.cpp.
References cloudViewer::t::geometry::PointCloud::Clear(), cloudViewer::utility::filesystem::CFile::CurPos(), cloudViewer::utility::CountingProgressReporter::Finish(), cloudViewer::core::Float64, cloudViewer::utility::filesystem::CFile::GetFileSize(), cloudViewer::utility::filesystem::CFile::GetNumLines(), LogWarning, cloudViewer::utility::filesystem::CFile::Open(), params, points, cloudViewer::utility::filesystem::CFile::ReadLine(), cloudViewer::t::geometry::PointCloud::SetPointAttr(), cloudViewer::t::geometry::PointCloud::SetPoints(), cloudViewer::utility::CountingProgressReporter::SetTotal(), and cloudViewer::utility::CountingProgressReporter::Update().
ReadTriangleMesh()
bool cloudViewer::t::io::ReadTriangleMesh (const std::string & filename, geometry::TriangleMesh & mesh, cloudViewer::io::ReadTriangleMeshOptions params = {})
The general entrance for reading a TriangleMesh from a file. The function calls read functions based on the extension name of filename. Supported formats are obj,ply,stl,off,gltf,glb,fbx .
Parameters
filename Path to the mesh file.
mesh Output parameter for the mesh.
params Additional read options to enable post-processing or progress reporting.
Returns
return true if the read function is successful, false otherwise.
Definition at line 74 of file TriangleMeshIO.cpp.
References file_extension_to_trianglemesh_read_function, cloudViewer::t::geometry::TriangleMesh::FromLegacy(), cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::TriangleMesh::GetTriangleIndices(), cloudViewer::t::geometry::TriangleMesh::GetVertexPositions(), cloudViewer::t::geometry::TriangleMesh::HasTriangleIndices(), cloudViewer::t::geometry::TriangleMesh::HasVertexPositions(), LogDebug, LogWarning, params, and cloudViewer::io::ReadTriangleMesh().
Referenced by CreateMeshFromFile().
ReadTriangleMeshFromNPZ()
bool cloudViewer::t::io::ReadTriangleMeshFromNPZ (const std::string & filename, geometry::TriangleMesh & mesh, const cloudViewer::io::ReadTriangleMeshOptions & params)
Definition at line 148 of file TriangleMeshIO.cpp.
References cloudViewer::t::geometry::DrawableGeometry::GetMaterial(), cloudViewer::visualization::rendering::Material::IsValid(), LogWarning, ReadNpz(), cloudViewer::visualization::rendering::Material::SetDefaultProperties(), cloudViewer::visualization::rendering::Material::SetMaterialName(), cloudViewer::visualization::rendering::Material::SetScalarProperty(), cloudViewer::visualization::rendering::Material::SetTextureMap(), cloudViewer::t::geometry::TriangleMesh::SetTriangleAttr(), cloudViewer::t::geometry::TriangleMesh::SetTriangleColors(), cloudViewer::t::geometry::TriangleMesh::SetTriangleIndices(), cloudViewer::t::geometry::TriangleMesh::SetTriangleNormals(), cloudViewer::t::geometry::TriangleMesh::SetVertexAttr(), cloudViewer::t::geometry::TriangleMesh::SetVertexColors(), cloudViewer::t::geometry::TriangleMesh::SetVertexNormals(), and cloudViewer::t::geometry::TriangleMesh::SetVertexPositions().
ReadTriangleMeshUsingASSIMP()
bool cloudViewer::t::io::ReadTriangleMeshUsingASSIMP (const std::string & filename, geometry::TriangleMesh & mesh, const cloudViewer::io::ReadTriangleMeshOptions & params)
Definition at line 46 of file FileASSIMP.cpp.
References cloudViewer::t::geometry::TriangleMesh::Clear(), cloudViewer::core::Concatenate(), cloudViewer::core::Tensor::Empty(), cloudViewer::core::Dtype::Float32, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::IndexGet(), cloudViewer::core::Dtype::Int64, kPostProcessFlags_compulsory, kPostProcessFlags_fast, LogWarning, cloudViewer::core::ParallelFor(), params, cloudViewer::t::geometry::TriangleMesh::SetTriangleAttr(), cloudViewer::t::geometry::TriangleMesh::SetTriangleIndices(), cloudViewer::t::geometry::TriangleMesh::SetVertexColors(), cloudViewer::t::geometry::TriangleMesh::SetVertexNormals(), and cloudViewer::t::geometry::TriangleMesh::SetVertexPositions().
SetPCDHeaderFieldTypeAndSizeFromDtype()
static void cloudViewer::t::io::SetPCDHeaderFieldTypeAndSizeFromDtype (const core::Dtype & dtype, PCLPointField & field) static
Definition at line 647 of file FilePCD.cpp.
References cloudViewer::core::Float32, cloudViewer::core::Float64, cloudViewer::core::Int16, cloudViewer::core::Int32, cloudViewer::core::Int64, cloudViewer::core::Int8, LogError, cloudViewer::t::io::PCLPointField::size, cloudViewer::t::io::PCLPointField::type, cloudViewer::core::UInt16, cloudViewer::core::UInt32, cloudViewer::core::UInt64, and cloudViewer::core::UInt8.
Referenced by GenerateHeader().
SetPNGImageFromImage()
static void cloudViewer::t::io::SetPNGImageFromImage (const geometry::Image & image, int quality, png_image & pngimage) static
Definition at line 18 of file FilePNG.cpp.
References image, and cloudViewer::core::UInt16.
Referenced by WriteImageToPNG(), and WriteImageToPNGInMemory().
SetTextureMaterialProperty()
static void cloudViewer::t::io::SetTextureMaterialProperty (aiMaterial * mat, aiScene * scene, int texture_idx, aiTextureType tt, t::geometry::Image & img) static
Definition at line 180 of file FileASSIMP.cpp.
References patch::to_string(), and WriteImageToPNGInMemory().
Referenced by WriteTriangleMeshUsingASSIMP().
STRINGIFY_ENUM() [1/5]
cloudViewer::t::io::STRINGIFY_ENUM (rs2_format , { {RS2_FORMAT_ANY, "RS2_FORMAT_ANY"}, {RS2_FORMAT_Z16, "RS2_FORMAT_Z16"}, {RS2_FORMAT_DISPARITY16, "RS2_FORMAT_DISPARITY16"}, {RS2_FORMAT_XYZ32F, "RS2_FORMAT_XYZ32F"}, {RS2_FORMAT_YUYV, "RS2_FORMAT_YUYV"}, {RS2_FORMAT_RGB8, "RS2_FORMAT_RGB8"}, {RS2_FORMAT_BGR8, "RS2_FORMAT_BGR8"}, {RS2_FORMAT_RGBA8, "RS2_FORMAT_RGBA8"}, {RS2_FORMAT_BGRA8, "RS2_FORMAT_BGRA8"}, {RS2_FORMAT_Y8, "RS2_FORMAT_Y8"}, {RS2_FORMAT_Y16, "RS2_FORMAT_Y16"}, {RS2_FORMAT_RAW10, "RS2_FORMAT_RAW10"}, {RS2_FORMAT_RAW16, "RS2_FORMAT_RAW16"}, {RS2_FORMAT_RAW8, "RS2_FORMAT_RAW8"}, {RS2_FORMAT_UYVY, "RS2_FORMAT_UYVY"}, {RS2_FORMAT_MOTION_RAW, "RS2_FORMAT_MOTION_RAW"}, {RS2_FORMAT_MOTION_XYZ32F, "RS2_FORMAT_MOTION_XYZ32F"}, {RS2_FORMAT_GPIO_RAW, "RS2_FORMAT_GPIO_RAW"}, {RS2_FORMAT_6DOF, "RS2_FORMAT_6DOF"}, {RS2_FORMAT_DISPARITY32, "RS2_FORMAT_DISPARITY32"}, {RS2_FORMAT_Y10BPACK, "RS2_FORMAT_Y10BPACK"}, {RS2_FORMAT_DISTANCE, "RS2_FORMAT_DISTANCE"}, {RS2_FORMAT_MJPEG, "RS2_FORMAT_MJPEG"}, {RS2_FORMAT_Y8I, "RS2_FORMAT_Y8I"}, {RS2_FORMAT_Y12I, "RS2_FORMAT_Y12I"}, {RS2_FORMAT_INZI, "RS2_FORMAT_INZI"}, {RS2_FORMAT_INVI, "RS2_FORMAT_INVI"}, {RS2_FORMAT_W10, "RS2_FORMAT_W10"}, {RS2_FORMAT_Z16H, "RS2_FORMAT_Z16H"} })
RS2 pixel formats.
STRINGIFY_ENUM() [2/5]
cloudViewer::t::io::STRINGIFY_ENUM (rs2_l500_visual_preset , { {RS2_L500_VISUAL_PRESET_DEFAULT, "RS2_L500_VISUAL_PRESET_DEFAULT"}, {RS2_L500_VISUAL_PRESET_CUSTOM, "RS2_L500_VISUAL_PRESET_CUSTOM"}, {RS2_L500_VISUAL_PRESET_NO_AMBIENT, "RS2_L500_VISUAL_PRESET_NO_AMBIENT"}, {RS2_L500_VISUAL_PRESET_LOW_AMBIENT, "RS2_L500_VISUAL_PRESET_LOW_AMBIENT"}, {RS2_L500_VISUAL_PRESET_MAX_RANGE, "RS2_L500_VISUAL_PRESET_MAX_RANGE"}, {RS2_L500_VISUAL_PRESET_SHORT_RANGE, "RS2_L500_VISUAL_PRESET_SHORT_RANGE"} })
RS2 visual presets for L500 devices.
STRINGIFY_ENUM() [3/5]
cloudViewer::t::io::STRINGIFY_ENUM (rs2_rs400_visual_preset , { {RS2_RS400_VISUAL_PRESET_DEFAULT, "RS2_RS400_VISUAL_PRESET_DEFAULT"}, {RS2_RS400_VISUAL_PRESET_CUSTOM, "RS2_RS400_VISUAL_PRESET_CUSTOM"}, {RS2_RS400_VISUAL_PRESET_HAND, "RS2_RS400_VISUAL_PRESET_HAND"}, {RS2_RS400_VISUAL_PRESET_HIGH_ACCURACY, "RS2_RS400_VISUAL_PRESET_HIGH_ACCURACY"}, {RS2_RS400_VISUAL_PRESET_HIGH_DENSITY, "RS2_RS400_VISUAL_PRESET_HIGH_DENSITY"}, {RS2_RS400_VISUAL_PRESET_MEDIUM_DENSITY, "RS2_RS400_VISUAL_PRESET_MEDIUM_DENSITY"}, {RS2_RS400_VISUAL_PRESET_REMOVE_IR_PATTERN, "RS2_RS400_VISUAL_PRESET_REMOVE_IR_PATTERN"} })
RS2 visual presets for RS400 devices.
STRINGIFY_ENUM() [4/5]
cloudViewer::t::io::STRINGIFY_ENUM (rs2_sr300_visual_preset , { {RS2_SR300_VISUAL_PRESET_DEFAULT, "RS2_SR300_VISUAL_PRESET_DEFAULT"}, {RS2_SR300_VISUAL_PRESET_SHORT_RANGE, "RS2_SR300_VISUAL_PRESET_SHORT_RANGE"}, {RS2_SR300_VISUAL_PRESET_LONG_RANGE, "RS2_SR300_VISUAL_PRESET_LONG_RANGE"}, {RS2_SR300_VISUAL_PRESET_BACKGROUND_SEGMENTATION, "RS2_SR300_VISUAL_PRESET_BACKGROUND_SEGMENTATION"}, {RS2_SR300_VISUAL_PRESET_GESTURE_RECOGNITION, "RS2_SR300_VISUAL_PRESET_GESTURE_RECOGNITION"}, {RS2_SR300_VISUAL_PRESET_OBJECT_SCANNING, "RS2_SR300_VISUAL_PRESET_OBJECT_SCANNING"}, {RS2_SR300_VISUAL_PRESET_FACE_ANALYTICS, "RS2_SR300_VISUAL_PRESET_FACE_ANALYTICS"}, {RS2_SR300_VISUAL_PRESET_FACE_LOGIN, "RS2_SR300_VISUAL_PRESET_FACE_LOGIN"}, {RS2_SR300_VISUAL_PRESET_GR_CURSOR, "RS2_SR300_VISUAL_PRESET_GR_CURSOR"}, {RS2_SR300_VISUAL_PRESET_MID_RANGE, "RS2_SR300_VISUAL_PRESET_MID_RANGE"}, {RS2_SR300_VISUAL_PRESET_IR_ONLY, "RS2_SR300_VISUAL_PRESET_IR_ONLY"} })
STRINGIFY_ENUM() [5/5]
cloudViewer::t::io::STRINGIFY_ENUM (rs2_stream , { {RS2_STREAM_ANY, "RS2_STREAM_ANY"}, {RS2_STREAM_DEPTH, "RS2_STREAM_DEPTH"}, {RS2_STREAM_COLOR, "RS2_STREAM_COLOR"}, {RS2_STREAM_INFRARED, "RS2_STREAM_INFRARED"}, {RS2_STREAM_FISHEYE, "RS2_STREAM_FISHEYE"}, {RS2_STREAM_GYRO, "RS2_STREAM_GYRO"}, {RS2_STREAM_ACCEL, "RS2_STREAM_ACCEL"}, {RS2_STREAM_GPIO, "RS2_STREAM_GPIO"}, {RS2_STREAM_POSE, "RS2_STREAM_POSE"}, {RS2_STREAM_CONFIDENCE, "RS2_STREAM_CONFIDENCE"} })
RS2 stream types.
UnpackASCIIPCDElement()
template<typename scalar_t > static void cloudViewer::t::io::UnpackASCIIPCDElement (scalar_t & data, const char * data_ptr) static delete
UnpackASCIIPCDElement< double >()
template<> void cloudViewer::t::io::UnpackASCIIPCDElement< double > (double & data, const char * data_ptr)
Definition at line 346 of file FilePCD.cpp.
UnpackASCIIPCDElement< float >()
template<> void cloudViewer::t::io::UnpackASCIIPCDElement< float > (float & data, const char * data_ptr)
Definition at line 340 of file FilePCD.cpp.
UnpackASCIIPCDElement< std::int16_t >()
template<> void cloudViewer::t::io::UnpackASCIIPCDElement< std::int16_t > (std::int16_t & data, const char * data_ptr)
Definition at line 359 of file FilePCD.cpp.
UnpackASCIIPCDElement< std::int32_t >()
template<> void cloudViewer::t::io::UnpackASCIIPCDElement< std::int32_t > (std::int32_t & data, const char * data_ptr)
Definition at line 366 of file FilePCD.cpp.
UnpackASCIIPCDElement< std::int64_t >()
template<> void cloudViewer::t::io::UnpackASCIIPCDElement< std::int64_t > (std::int64_t & data, const char * data_ptr)
Definition at line 373 of file FilePCD.cpp.
UnpackASCIIPCDElement< std::int8_t >()
template<> void cloudViewer::t::io::UnpackASCIIPCDElement< std::int8_t > (std::int8_t & data, const char * data_ptr)
Definition at line 352 of file FilePCD.cpp.
UnpackASCIIPCDElement< std::uint16_t >()
template<> void cloudViewer::t::io::UnpackASCIIPCDElement< std::uint16_t > (std::uint16_t & data, const char * data_ptr)
Definition at line 387 of file FilePCD.cpp.
UnpackASCIIPCDElement< std::uint32_t >()
template<> void cloudViewer::t::io::UnpackASCIIPCDElement< std::uint32_t > (std::uint32_t & data, const char * data_ptr)
Definition at line 394 of file FilePCD.cpp.
UnpackASCIIPCDElement< std::uint64_t >()
template<> void cloudViewer::t::io::UnpackASCIIPCDElement< std::uint64_t > (std::uint64_t & data, const char * data_ptr)
Definition at line 401 of file FilePCD.cpp.
UnpackASCIIPCDElement< std::uint8_t >()
template<> void cloudViewer::t::io::UnpackASCIIPCDElement< std::uint8_t > (std::uint8_t & data, const char * data_ptr)
Definition at line 380 of file FilePCD.cpp.
WriteElementDataToFileASCII()
template<typename scalar_t > static int cloudViewer::t::io::WriteElementDataToFileASCII (const scalar_t & data, FILE * file) static delete
WriteElementDataToFileASCII< double >()
template<> int cloudViewer::t::io::WriteElementDataToFileASCII< double > (const double & data, FILE * file)
Definition at line 936 of file FilePCD.cpp.
WriteElementDataToFileASCII< float >()
template<> int cloudViewer::t::io::WriteElementDataToFileASCII< float > (const float & data, FILE * file)
Definition at line 931 of file FilePCD.cpp.
WriteElementDataToFileASCII< std::int16_t >()
template<> int cloudViewer::t::io::WriteElementDataToFileASCII< std::int16_t > (const std::int16_t & data, FILE * file)
Definition at line 947 of file FilePCD.cpp.
WriteElementDataToFileASCII< std::int32_t >()
template<> int cloudViewer::t::io::WriteElementDataToFileASCII< std::int32_t > (const std::int32_t & data, FILE * file)
Definition at line 953 of file FilePCD.cpp.
WriteElementDataToFileASCII< std::int64_t >()
template<> int cloudViewer::t::io::WriteElementDataToFileASCII< std::int64_t > (const std::int64_t & data, FILE * file)
Definition at line 959 of file FilePCD.cpp.
WriteElementDataToFileASCII< std::int8_t >()
template<> int cloudViewer::t::io::WriteElementDataToFileASCII< std::int8_t > (const std::int8_t & data, FILE * file)
Definition at line 941 of file FilePCD.cpp.
WriteElementDataToFileASCII< std::uint16_t >()
template<> int cloudViewer::t::io::WriteElementDataToFileASCII< std::uint16_t > (const std::uint16_t & data, FILE * file)
Definition at line 971 of file FilePCD.cpp.
WriteElementDataToFileASCII< std::uint32_t >()
template<> int cloudViewer::t::io::WriteElementDataToFileASCII< std::uint32_t > (const std::uint32_t & data, FILE * file)
Definition at line 977 of file FilePCD.cpp.
WriteElementDataToFileASCII< std::uint64_t >()
template<> int cloudViewer::t::io::WriteElementDataToFileASCII< std::uint64_t > (const std::uint64_t & data, FILE * file)
Definition at line 983 of file FilePCD.cpp.
WriteElementDataToFileASCII< std::uint8_t >()
template<> int cloudViewer::t::io::WriteElementDataToFileASCII< std::uint8_t > (const std::uint8_t & data, FILE * file)
Definition at line 965 of file FilePCD.cpp.
WriteHashMap()
void cloudViewer::t::io::WriteHashMap (const std::string & filename, const core::HashMap & hashmap)
Save a hash map's keys and values to a npz file at 'key' and 'value'.
Parameters
filename The npz file name to write to.
hashmap HashMap to save.
Definition at line 17 of file HashMapIO.cpp.
References format, cloudViewer::core::HashMap::GetActiveIndices(), cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), cloudViewer::core::HashMap::GetKeyTensor(), cloudViewer::core::HashMap::GetValueTensors(), cloudViewer::core::Tensor::IndexGet(), cloudViewer::core::Int64, cloudViewer::t::geometry::kernel::image::To(), cloudViewer::core::Tensor::To(), and WriteNpz().
Referenced by cloudViewer::core::HashMap::Save(), and cloudViewer::core::HashSet::Save().
WriteImage()
bool cloudViewer::t::io::WriteImage (const std::string & filename, const geometry::Image & image, int quality = kCloudViewerImageIODefaultQuality)
The general entrance for writing an Image to a file The function calls write functions based on the extension name of filename. If the write function supports quality, the parameter will be used. Otherwise it will be ignored.
Parameters
filename Full path to image. Supported file formats are png, jpg/jpeg.
image An object of type cloudViewer::t::geometry::Image.
quality PNG: [0-9] <=2 fast write for storing intermediate data >=3 (default) normal write for balanced speed and file size JPEG: [0-100] Typically in [70,95]. 90 is default (good quality).
Returns
return true if the write function is successful, false otherwise.
Supported file extensions are png, jpg/jpeg. Data type and number of channels depends on the file extension.
PNG: Dtype should be one of core::Bool, core::UInt8, core::UInt16 Supported number of channels are 1, 3, and 4.
JPG: Dtyppe should be core::UInt8 Supported number of channels are 1 and 3.
Definition at line 79 of file ImageIO.cpp.
References cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), image, and LogWarning.
WriteImageToJPG()
bool cloudViewer::t::io::WriteImageToJPG (const std::string & filename, const geometry::Image & image, int quality)
Definition at line 113 of file FileJPG.cpp.
References cloudViewer::utility::filesystem::FOpen(), image, kCloudViewerImageIODefaultQuality, LogWarning, cloudViewer::core::MemoryManager::MemcpyToHost(), NULL, TRUE, and cloudViewer::core::UInt8.
WriteImageToPNG()
bool cloudViewer::t::io::WriteImageToPNG (const std::string & filename, const geometry::Image & image, int quality)
Definition at line 75 of file FilePNG.cpp.
References cloudViewer::core::Bool, image, kCloudViewerImageIODefaultQuality, LogWarning, NULL, SetPNGImageFromImage(), cloudViewer::core::UInt16, and cloudViewer::core::UInt8.
WriteImageToPNGInMemory()
bool cloudViewer::t::io::WriteImageToPNGInMemory (std::vector< uint8_t > & buffer, const t::geometry::Image & image, int quality)
Definition at line 110 of file FilePNG.cpp.
References image, kCloudViewerImageIODefaultQuality, LogWarning, SetPNGImageFromImage(), cloudViewer::core::UInt16, and cloudViewer::core::UInt8.
Referenced by SetTextureMaterialProperty().
WriteNpy()
void cloudViewer::t::io::WriteNpy (const std::string & file_name, const core::Tensor & tensor)
Save a tensor to a Numpy .npy file.
Parameters
file_name The file name to write to.
tensor The tensor to save.
Definition at line 671 of file NumpyIO.cpp.
References cloudViewer::t::io::NumpyArray::Save().
Referenced by cloudViewer::core::Tensor::Save().
WriteNpz()
void cloudViewer::t::io::WriteNpz (const std::string & file_name, const std::unordered_map< std::string, core::Tensor > & tensor_map)
Save a string to tensor map as Numpy .npz file.
Parameters
file_name The file name to write to.
tensor_map The tensor map to save.
Definition at line 759 of file NumpyIO.cpp.
References cloudViewer::core::Tensor::Contiguous(), cloudViewer::core::Tensor::To(), WriteNpzEmpty(), and WriteNpzOneTensor().
Referenced by cloudViewer::t::geometry::VoxelBlockGrid::Save(), WriteHashMap(), WritePointCloudToNPZ(), and WriteTriangleMeshToNPZ().
WriteNpzEmpty()
static void cloudViewer::t::io::WriteNpzEmpty (const std::string & file_name) static
Definition at line 468 of file NumpyIO.cpp.
References cloudViewer::t::io::CharVector::Append(), cloudViewer::t::io::CharVector::Data(), cloudViewer::utility::filesystem::CFile::GetError(), cloudViewer::utility::filesystem::CFile::GetFILE(), LogError, cloudViewer::utility::filesystem::CFile::Open(), and cloudViewer::t::io::CharVector::Size().
Referenced by WriteNpz().
WriteNpzOneTensor()
static void cloudViewer::t::io::WriteNpzOneTensor (const std::string & file_name, const std::string & tensor_name, const core::Tensor & tensor, bool append) static
Definition at line 360 of file NumpyIO.cpp.
References cloudViewer::t::io::CharVector::Append(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::begin(), cloudViewer::t::io::CharVector::Begin(), cloudViewer::core::Dtype::ByteSize(), CreateNumpyHeader(), cloudViewer::t::io::CharVector::Data(), cloudViewer::core::SmallVectorTemplateCommon< T, typename >::end(), cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::core::Tensor::GetDtype(), cloudViewer::utility::filesystem::CFile::GetError(), cloudViewer::utility::filesystem::CFile::GetFILE(), cloudViewer::core::Tensor::GetShape(), LogError, cloudViewer::utility::filesystem::CFile::Open(), ParseZipFooter(), cloudViewer::t::io::CharVector::Resize(), SEEK_SET, and cloudViewer::t::io::CharVector::Size().
Referenced by WriteNpz().
WritePCDData()
static bool cloudViewer::t::io::WritePCDData (FILE * file, const PCDHeader & header, const geometry::PointCloud & pointcloud, const WritePointCloudOption & params) static
Definition at line 988 of file FilePCD.cpp.
References cloudViewer::t::geometry::TensorMap::Contiguous(), cloudViewer::t::io::PCDHeader::datatype, DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::t::io::PCDHeader::fields, cloudViewer::core::Float32, cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointColors(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), cloudViewer::t::geometry::PointCloud::IsEmpty(), LogWarning, PackColorsToFloat(), params, cloudViewer::utility::CountingProgressReporter::SetTotal(), and cloudViewer::utility::CountingProgressReporter::Update().
Referenced by cloudViewer::io::WritePointCloudToPCD(), and WritePointCloudToPCD().
WritePCDHeader()
static bool cloudViewer::t::io::WritePCDHeader (FILE * file, const PCDHeader & header) static
Definition at line 792 of file FilePCD.cpp.
References ASCII, BINARY, BINARY_COMPRESSED, cloudViewer::t::io::PCDHeader::datatype, cloudViewer::t::io::PCDHeader::fields, cloudViewer::t::io::PCDHeader::height, cloudViewer::t::io::PCDHeader::points, cloudViewer::t::io::PCDHeader::version, and cloudViewer::t::io::PCDHeader::width.
Referenced by cloudViewer::io::WritePointCloudToPCD(), and WritePointCloudToPCD().
WritePointCloud() [1/2]
bool cloudViewer::t::io::WritePointCloud (const std::string & filename, const geometry::PointCloud & pointcloud, bool write_ascii, bool compressed, bool print_progress)
Definition at line 158 of file PointCloudIO.cpp.
References cloudViewer::io::WritePointCloudOption::compressed, format, cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), cloudViewer::utility::ToUpper(), cloudViewer::io::WritePointCloudOption::update_progress, cloudViewer::io::WritePointCloudOption::write_ascii, and WritePointCloud().
WritePointCloud() [2/2]
bool cloudViewer::t::io::WritePointCloud (const std::string & filename, const geometry::PointCloud & pointcloud, const WritePointCloudOption & params = {})
The general entrance for writing a PointCloud to a file The function calls write functions based on the extension name of filename. See WritePointCloudOption for additional options you can pass.
Returns
return true if the write function is successful, false otherwise.
Definition at line 135 of file PointCloudIO.cpp.
References file_extension_to_pointcloud_write_function, format, cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::IsEmpty(), LogDebug, params, cloudViewer::t::geometry::PointCloud::To(), cloudViewer::t::geometry::PointCloud::ToLegacy(), and cloudViewer::io::WritePointCloud().
Referenced by cloudViewer::t::pipelines::slac::PreprocessPointClouds(), and WritePointCloud().
WritePointCloudToNPZ()
bool cloudViewer::t::io::WritePointCloudToNPZ (const std::string & filename, const geometry::PointCloud & pointcloud, const WritePointCloudOption & params)
Definition at line 186 of file PointCloudIO.cpp.
References cloudViewer::t::geometry::PointCloud::GetPointAttr(), LogDebug, LogError, params, and WriteNpz().
WritePointCloudToPCD()
bool cloudViewer::t::io::WritePointCloudToPCD (const std::string & filename, const geometry::PointCloud & pointcloud, const WritePointCloudOption & params)
Definition at line 1178 of file FilePCD.cpp.
References AssertTensorDevice, cloudViewer::utility::filesystem::FOpen(), GenerateHeader(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), LogWarning, NULL, params, WritePCDData(), and WritePCDHeader().
WritePointCloudToPLY()
bool cloudViewer::t::io::WritePointCloudToPLY (const std::string & filename, const geometry::PointCloud & pointcloud, const cloudViewer::io::WritePointCloudOption & params)
Definition at line 355 of file FilePLY.cpp.
References cloudViewer::t::geometry::TensorMap::Contiguous(), DISPATCH_DTYPE_TO_TEMPLATE, cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointColors(), cloudViewer::t::geometry::PointCloud::HasPointNormals(), cloudViewer::t::geometry::PointCloud::IsEmpty(), cloudViewer::t::geometry::PointCloud::IsGaussianSplat(), LogDebug, LogWarning, NULL, params, PLY_ASCII, cloudViewer::utility::CountingProgressReporter::SetTotal(), cloudViewer::t::geometry::PointCloud::To(), patch::to_string(), and cloudViewer::utility::CountingProgressReporter::Update().
WritePointCloudToPTS()
bool cloudViewer::t::io::WritePointCloudToPTS (const std::string & filename, const geometry::PointCloud & pointcloud, const WritePointCloudOption & params)
Definition at line 191 of file FilePTS.cpp.
References AssertTensorShape, colors, ConvertColorTensorToUint8(), cloudViewer::utility::CountingProgressReporter::Finish(), cloudViewer::core::Float32, cloudViewer::core::Tensor::GetDataPtr(), cloudViewer::utility::filesystem::CFile::GetFILE(), cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointColors(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::HasPointAttr(), cloudViewer::t::geometry::PointCloud::HasPointColors(), cloudViewer::t::geometry::PointCloud::HasPointPositions(), cloudViewer::t::geometry::PointCloud::IsEmpty(), LogWarning, cloudViewer::utility::filesystem::CFile::Open(), params, cloudViewer::utility::CountingProgressReporter::SetTotal(), cloudViewer::core::Tensor::To(), and cloudViewer::utility::CountingProgressReporter::Update().
WritePointCloudToSPLAT()
bool cloudViewer::t::io::WritePointCloudToSPLAT (const std::string & filename, const geometry::PointCloud & pointcloud, const cloudViewer::io::WritePointCloudOption & params)
Definition at line 207 of file FileSPLAT.cpp.
References color, cloudViewer::t::geometry::TensorMap::Contiguous(), cloudViewer::utility::CountingProgressReporter::Finish(), cloudViewer::core::Float32, cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), cloudViewer::t::geometry::PointCloud::IsEmpty(), cloudViewer::t::geometry::PointCloud::IsGaussianSplat(), LogWarning, params, cloudViewer::utility::CountingProgressReporter::SetTotal(), and cloudViewer::utility::CountingProgressReporter::Update().
WritePointCloudToTXT()
bool cloudViewer::t::io::WritePointCloudToTXT (const std::string & filename, const geometry::PointCloud & pointcloud, const cloudViewer::io::WritePointCloudOption & params)
Definition at line 132 of file FileTXT.cpp.
References cloudViewer::utility::CountingProgressReporter::Finish(), cloudViewer::utility::filesystem::CFile::GetFILE(), cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPointPositions(), LogWarning, cloudViewer::utility::filesystem::CFile::Open(), params, points, cloudViewer::utility::CountingProgressReporter::SetTotal(), and cloudViewer::utility::CountingProgressReporter::Update().
WritePointCloudToXYZI()
bool cloudViewer::t::io::WritePointCloudToXYZI (const std::string & filename, const geometry::PointCloud & pointcloud, const cloudViewer::io::WritePointCloudOption & params)
Definition at line 77 of file FileXYZI.cpp.
References cloudViewer::utility::CountingProgressReporter::Finish(), cloudViewer::utility::filesystem::CFile::GetFILE(), cloudViewer::t::geometry::PointCloud::GetPointAttr(), cloudViewer::t::geometry::PointCloud::GetPoints(), cloudViewer::core::Tensor::GetShape(), cloudViewer::t::geometry::PointCloud::HasPointAttr(), cloudViewer::core::Tensor::Item(), LogWarning, cloudViewer::utility::filesystem::CFile::Open(), params, points, cloudViewer::utility::CountingProgressReporter::SetTotal(), and cloudViewer::utility::CountingProgressReporter::Update().
WriteTriangleMesh()
bool cloudViewer::t::io::WriteTriangleMesh (const std::string & filename, const geometry::TriangleMesh & mesh, bool write_ascii = false, bool compressed = false, bool write_vertex_normals = true, bool write_vertex_colors = true, bool write_triangle_uvs = true, bool print_progress = false)
The general entrance for writing a TriangleMesh to a file The function calls write functions based on the extension name of filename. If the write function supports binary encoding and compression, the later two parameters will be used. Otherwise they will be ignored. At current only .obj format supports uv coordinates (triangle_uvs) and textures.
Returns
return true if the write function is successful, false otherwise.
Definition at line 114 of file TriangleMeshIO.cpp.
References file_extension_to_trianglemesh_write_function, cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), cloudViewer::core::Tensor::GetLength(), cloudViewer::t::geometry::TriangleMesh::GetTriangleIndices(), cloudViewer::t::geometry::TriangleMesh::GetVertexPositions(), LogDebug, LogWarning, cloudViewer::t::geometry::TriangleMesh::ToLegacy(), and cloudViewer::io::WriteTriangleMesh().
WriteTriangleMeshToNPZ()
bool cloudViewer::t::io::WriteTriangleMeshToNPZ (const std::string & filename, const geometry::TriangleMesh & mesh, const bool write_ascii, const bool compressed, const bool write_vertex_normals, const bool write_vertex_colors, const bool write_triangle_uvs, const bool print_progress)
Definition at line 216 of file TriangleMeshIO.cpp.
References cloudViewer::t::geometry::DrawableGeometry::GetMaterial(), cloudViewer::t::geometry::TriangleMesh::GetTriangleAttr(), cloudViewer::t::geometry::TriangleMesh::GetTriangleColors(), cloudViewer::t::geometry::TriangleMesh::GetTriangleIndices(), cloudViewer::t::geometry::TriangleMesh::GetTriangleNormals(), cloudViewer::t::geometry::TriangleMesh::GetVertexAttr(), cloudViewer::t::geometry::TriangleMesh::GetVertexColors(), cloudViewer::t::geometry::TriangleMesh::GetVertexNormals(), cloudViewer::t::geometry::TriangleMesh::GetVertexPositions(), cloudViewer::t::geometry::TriangleMesh::HasTriangleAttr(), cloudViewer::t::geometry::TriangleMesh::HasTriangleColors(), cloudViewer::t::geometry::TriangleMesh::HasTriangleIndices(), cloudViewer::t::geometry::TriangleMesh::HasTriangleNormals(), cloudViewer::t::geometry::TriangleMesh::HasVertexColors(), cloudViewer::t::geometry::TriangleMesh::HasVertexNormals(), cloudViewer::t::geometry::TriangleMesh::HasVertexPositions(), cloudViewer::visualization::rendering::Material::IsValid(), LogWarning, and WriteNpz().
WriteTriangleMeshUsingASSIMP()
bool cloudViewer::t::io::WriteTriangleMeshUsingASSIMP (const std::string & filename, const geometry::TriangleMesh & mesh, const bool write_ascii, const bool compressed, const bool write_vertex_normals, const bool write_vertex_colors, const bool write_triangle_uvs, const bool print_progress)
Definition at line 371 of file FileASSIMP.cpp.
References colors, cloudViewer::core::Tensor::Contiguous(), cloudViewer::t::geometry::TensorMap::Contiguous(), cloudViewer::core::Tensor::Empty(), cloudViewer::core::Dtype::Float32, cloudViewer::visualization::rendering::Material::GetAlbedoMap(), cloudViewer::visualization::rendering::Material::GetAORoughnessMetalMap(), cloudViewer::visualization::rendering::Material::GetBaseClearcoat(), cloudViewer::visualization::rendering::Material::GetBaseClearcoatRoughness(), cloudViewer::visualization::rendering::Material::GetBaseColor(), cloudViewer::visualization::rendering::Material::GetBaseMetallic(), cloudViewer::visualization::rendering::Material::GetBaseRoughness(), cloudViewer::visualization::rendering::Material::GetEmissiveColor(), cloudViewer::core::Tensor::GetItem(), cloudViewer::t::geometry::DrawableGeometry::GetMaterial(), cloudViewer::visualization::rendering::Material::GetMetallicMap(), cloudViewer::visualization::rendering::Material::GetNormalMap(), cloudViewer::visualization::rendering::Material::GetRoughnessMap(), cloudViewer::t::geometry::Image::GetRows(), cloudViewer::core::Tensor::GetShape(), cloudViewer::t::geometry::TriangleMesh::GetTriangleAttr(), cloudViewer::t::geometry::TriangleMesh::GetTriangleIndices(), cloudViewer::t::geometry::TriangleMesh::GetVertexAttr(), cloudViewer::t::geometry::TriangleMesh::GetVertexColors(), cloudViewer::t::geometry::TriangleMesh::GetVertexNormals(), cloudViewer::t::geometry::TriangleMesh::GetVertexPositions(), cloudViewer::visualization::rendering::Material::HasAlbedoMap(), cloudViewer::visualization::rendering::Material::HasAORoughnessMetalMap(), cloudViewer::visualization::rendering::Material::HasBaseClearcoat(), cloudViewer::visualization::rendering::Material::HasBaseClearcoatRoughness(), cloudViewer::visualization::rendering::Material::HasBaseColor(), cloudViewer::visualization::rendering::Material::HasBaseMetallic(), cloudViewer::visualization::rendering::Material::HasBaseRoughness(), cloudViewer::visualization::rendering::Material::HasEmissiveColor(), cloudViewer::t::geometry::DrawableGeometry::HasMaterial(), cloudViewer::visualization::rendering::Material::HasMetallicMap(), cloudViewer::visualization::rendering::Material::HasNormalMap(), cloudViewer::visualization::rendering::Material::HasRoughnessMap(), cloudViewer::t::geometry::TriangleMesh::HasTriangleAttr(), cloudViewer::t::geometry::TriangleMesh::HasTriangleColors(), cloudViewer::t::geometry::TriangleMesh::HasTriangleNormals(), cloudViewer::t::geometry::TriangleMesh::HasVertexAttr(), cloudViewer::t::geometry::TriangleMesh::HasVertexColors(), cloudViewer::t::geometry::TriangleMesh::HasVertexNormals(), cloudViewer::t::geometry::TriangleMesh::HasVertexPositions(), cloudViewer::core::TensorKey::Index(), LogWarning, cloudViewer::core::None, normals, cloudViewer::core::Tensor::Ones(), cloudViewer::t::geometry::TriangleMesh::RemoveVertexAttr(), cloudViewer::core::Tensor::SetItem(), SetTextureMaterialProperty(), cloudViewer::core::TensorKey::Slice(), cloudViewer::core::Tensor::To(), cloudViewer::core::Dtype::UInt32, and cloudViewer::core::Dtype::UInt8.
Variable Documentation
file_extension_to_pointcloud_read_function
const std::unordered_map< std::string, std::function<bool(const std::string &, geometry::PointCloud &, const cloudViewer::io::ReadPointCloudOption &)> > cloudViewer::t::io::file_extension_to_pointcloud_read_function static
Initial value:
{
                {"npz", ReadPointCloudFromNPZ},
                {"xyz", ReadPointCloudFromTXT},
                {"xyzd", ReadPointCloudFromTXT},
                {"xyzi", ReadPointCloudFromTXT},
                {"xyzn", ReadPointCloudFromTXT},
                {"xyzrgb", ReadPointCloudFromTXT},
                {"pcd", ReadPointCloudFromPCD},
                {"ply", ReadPointCloudFromPLY},
                {"splat", ReadPointCloudFromSPLAT},
                {"pts", ReadPointCloudFromPTS},
        }
Definition at line 31 of file PointCloudIO.cpp.
Referenced by ReadPointCloud().
file_extension_to_pointcloud_write_function
const std::unordered_map< std::string, std::function<bool(const std::string &, const geometry::PointCloud &, const cloudViewer::io::WritePointCloudOption &)> > cloudViewer::t::io::file_extension_to_pointcloud_write_function static
Initial value:
{
                {"npz", WritePointCloudToNPZ},
                {"xyz", WritePointCloudToTXT},
                {"xyzd", WritePointCloudToTXT},
                {"xyzi", WritePointCloudToTXT},
                {"xyzn", WritePointCloudToTXT},
                {"xyzrgb", WritePointCloudToTXT},
                {"pcd", WritePointCloudToPCD},
                {"ply", WritePointCloudToPLY},
                {"splat", WritePointCloudToSPLAT},
                {"pts", WritePointCloudToPTS},
        }
Definition at line 49 of file PointCloudIO.cpp.
Referenced by WritePointCloud().
file_extension_to_trianglemesh_read_function
const std::unordered_map< std::string, std::function<bool(const std::string &, geometry::TriangleMesh &, const cloudViewer::io::ReadTriangleMeshOptions &)> > cloudViewer::t::io::file_extension_to_trianglemesh_read_function static
Initial value:
{
                {"npz", ReadTriangleMeshFromNPZ},
                {"stl", ReadTriangleMeshUsingASSIMP},
                {"obj", ReadTriangleMeshUsingASSIMP},
                {"off", ReadTriangleMeshUsingASSIMP},
                {"gltf", ReadTriangleMeshUsingASSIMP},
                {"glb", ReadTriangleMeshUsingASSIMP},
                {"fbx", ReadTriangleMeshUsingASSIMP},
        }
Definition at line 27 of file TriangleMeshIO.cpp.
Referenced by cloudViewer::io::ReadTriangleMesh(), and ReadTriangleMesh().
file_extension_to_trianglemesh_write_function
const std::unordered_map< std::string, std::function<bool(const std::string &, const geometry::TriangleMesh &, const bool, const bool, const bool, const bool, const bool, const bool)> > cloudViewer::t::io::file_extension_to_trianglemesh_write_function static
Initial value:
{
                {"npz", WriteTriangleMeshToNPZ},
                {"glb", WriteTriangleMeshUsingASSIMP},
        }
Definition at line 47 of file TriangleMeshIO.cpp.
Referenced by cloudViewer::io::WriteTriangleMesh(), and WriteTriangleMesh().
kCloudViewerImageIODefaultQuality
constexpr int cloudViewer::t::io::kCloudViewerImageIODefaultQuality = -1 constexpr
Definition at line 33 of file ImageIO.h.
Referenced by WriteImageToJPG(), WriteImageToPNG(), and WriteImageToPNGInMemory().
kPostProcessFlags_compulsory
const unsigned int cloudViewer::t::io::kPostProcessFlags_compulsory
Initial value:
=
        aiProcess_JoinIdenticalVertices | aiProcess_Triangulate |
        aiProcess_SortByPType | aiProcess_PreTransformVertices
Definition at line 37 of file FileASSIMP.cpp.
Referenced by ReadTriangleMeshUsingASSIMP().
kPostProcessFlags_fast
const unsigned int cloudViewer::t::io::kPostProcessFlags_fast
Initial value:
=
        kPostProcessFlags_compulsory | aiProcess_GenNormals |
        aiProcess_GenUVCoords | aiProcess_RemoveRedundantMaterials |
        aiProcess_OptimizeMeshes
Definition at line 41 of file FileASSIMP.cpp.
Referenced by ReadTriangleMeshUsingASSIMP().
standard_config
std::unordered_map<std::string, std::string> cloudViewer::t::io::standard_config static
Initial value:
{
        {"serial", ""},
        {"color_format", "RS2_FORMAT_ANY"},
        {"color_resolution", "0,0"},
        {"depth_format", "RS2_FORMAT_ANY"},
        {"depth_resolution", "0,0"},
        {"fps", "0"},
        {"visual_preset", "VISUAL_PRESET_DEFAULT"}}
Definition at line 134 of file RealSenseSensorConfig.cpp.
Referenced by cloudViewer::t::io::RealSenseSensorConfig::RealSenseSensorConfig().