ACloudViewer: ecvColor Namespace Reference
ecvColor Namespace Reference
Colors namespace.
Namespaces
LookUpTable
Classes
struct is_same_type
struct is_same_type< T1, T1 >
class RgbTpl
RGB color structure.
class RgbaTpl
RGBA color structure.
class Generator
Colors generator.
class Convert
Color space conversion.
Typedefs
using Rgbf = RgbTpl< float >
3 components, float type
using Rgbub = RgbTpl< unsigned char >
3 components, unsigned byte type
using Rgb = RgbTpl< ColorCompType >
3 components, default type
using Rgbaf = RgbaTpl< float >
4 components, float type
using Rgbaub = RgbaTpl< unsigned char >
4 components, unsigned byte type
using Rgba = RgbaTpl< ColorCompType >
4 components, default type
Functions
constexpr Rgb white (MAX, MAX, MAX)
constexpr Rgb lightGrey (static_cast< ColorCompType >(MAX *0.8), static_cast< ColorCompType >(MAX *0.8), static_cast< ColorCompType >(MAX *0.8))
constexpr Rgb darkGrey (MAX/2, MAX/2, MAX/2)
constexpr Rgb red (MAX, 0, 0)
constexpr Rgb green (0, MAX, 0)
constexpr Rgb blue (0, 0, MAX)
constexpr Rgb darkBlue (0, 0, MAX/2)
constexpr Rgb magenta (MAX, 0, MAX)
constexpr Rgb cyan (0, MAX, MAX)
constexpr Rgb orange (MAX, MAX/2, 0)
constexpr Rgb black (0, 0, 0)
constexpr Rgb yellow (MAX, MAX, 0)
constexpr Rgba owhite (MAX, MAX, MAX, OPACITY)
constexpr Rgba olightGrey (static_cast< ColorCompType >(MAX *0.8), static_cast< ColorCompType >(MAX *0.8), static_cast< ColorCompType >(MAX *0.8), OPACITY)
constexpr Rgba odarkGrey (MAX/2, MAX/2, MAX/2, OPACITY)
constexpr Rgba ored (MAX, 0, 0, OPACITY)
constexpr Rgba ogreen (0, MAX, 0, OPACITY)
constexpr Rgba oblue (0, 0, MAX, OPACITY)
constexpr Rgba odarkBlue (0, 0, MAX/2, OPACITY)
constexpr Rgba omagenta (MAX, 0, MAX, OPACITY)
constexpr Rgba ocyan (0, MAX, MAX, OPACITY)
constexpr Rgba oorange (MAX, MAX/2, 0, OPACITY)
constexpr Rgba oblack (0, 0, 0, OPACITY)
constexpr Rgba oyellow (MAX, MAX, 0, OPACITY)
constexpr Rgbaf bright (1.00f, 1.00f, 1.00f, 1.00f)
constexpr Rgbaf lighter (0.83f, 0.83f, 0.83f, 1.00f)
constexpr Rgbaf light (0.66f, 0.66f, 0.66f, 1.00f)
constexpr Rgbaf middle (0.50f, 0.50f, 0.50f, 1.00f)
constexpr Rgbaf dark (0.34f, 0.34f, 0.34f, 1.00f)
constexpr Rgbaf darker (0.17f, 0.17f, 0.17f, 1.00f)
constexpr Rgbaf darkest (0.08f, 0.08f, 0.08f, 1.00f)
constexpr Rgbaf night (0.00f, 0.00f, 0.00f, 1.00F)
constexpr Rgbaf defaultMeshFrontDiff (0.00f, 0.90f, 0.27f, 1.00f)
constexpr Rgbaf defaultMeshBackDiff (0.27f, 0.90f, 0.90f, 1.00f)
constexpr Rgbf defaultViewBkgColor (10/255.0f, 102/255.0f, 151/255.0f)
constexpr Rgbub defaultBkgColor (135, 206, 235)
constexpr Rgbub defaultColor (MAX, MAX, MAX)
constexpr Rgbub defaultLabelBkgColor (MAX, MAX, MAX)
constexpr Rgbub defaultLabelMarkerColor (MAX, 0, MAX)
Rgb FromRgbfToRgb (const Rgbf &color)
Conversion from Rgbf.
Rgb FromRgbafToRgb (const Rgbaf &color)
Conversion from Rgbaf.
Rgba FromRgbToRgba (const Rgb &color)
Conversion from Rgb to Rgba.
Rgb FromRgbaToRgb (const Rgba &color)
Conversion from Rgba to Rgb.
Rgba FromRgbafToRgba (const Rgbaf &color)
Conversion from Rgbaf to Rgba.
Rgbf FromRgb (const Rgb &color)
Rgbf FromRgb (const Rgba &color)
Rgbaf FromRgba (const Rgba &color)
Rgbaf FromRgbub (const Rgbub &color)
Rgb FromQRgb (QRgb qColor)
Conversion from QRgb.
Rgba FromQRgba (QRgb qColor)
Conversion from QRgb'a'.
Rgb FromQColor (QColor qColor)
Conversion from QColor.
Rgba FromQColora (QColor qColor)
Conversion from QColor'a'.
Rgbf FromQColorf (QColor qColor)
Conversion from QColor (floating point)
Rgbaf FromQColoraf (QColor qColor)
Conversion from QColor'a' (floating point)
Variables
constexpr ColorCompType MAX = 255
Max value of a single color component (default type)
constexpr ColorCompType OPACITY = 255
Detailed Description
Colors namespace.
Typedef Documentation
Rgb
using ecvColor::Rgb = typedef RgbTpl<ColorCompType>
3 components, default type
Definition at line 141 of file ecvColorTypes.h.
Rgba
using ecvColor::Rgba = typedef RgbaTpl<ColorCompType>
4 components, default type
Definition at line 196 of file ecvColorTypes.h.
Rgbaf
using ecvColor::Rgbaf = typedef RgbaTpl<float>
4 components, float type
Definition at line 192 of file ecvColorTypes.h.
Rgbaub
using ecvColor::Rgbaub = typedef RgbaTpl<unsigned char>
4 components, unsigned byte type
Definition at line 194 of file ecvColorTypes.h.
Rgbf
using ecvColor::Rgbf = typedef RgbTpl<float>
3 components, float type
Definition at line 137 of file ecvColorTypes.h.
Rgbub
using ecvColor::Rgbub = typedef RgbTpl<unsigned char>
3 components, unsigned byte type
Definition at line 139 of file ecvColorTypes.h.
Function Documentation
black()
constexpr Rgb ecvColor::black (0 , 0 , 0) constexpr
Referenced by ccCloudLayersHelper::apply(), ccColorLevelsDlg::ccColorLevelsDlg(), cc2Point5DimEditor::create2DView(), ccAsprsModel::createNewItem(), ColorScheme::Default(), DistanceMapGenerationDlg::DistanceMapGenerationDlg(), LasScalarFieldLoader::handleRGBValue(), ccContourExtractorDlg::init(), CodeEditor::lineNumberAreaPaintEvent(), LASFWFFilter::loadFile(), LASFilter::loadFile(), ccCloudLayersHelper::moveItem(), StereogramWidget::paintEvent(), ColorScaleElementSlider::paintEvent(), ColorBarWidget::paintEvent(), DxfProfilesExporter::SaveHorizontalProfiles(), DxfProfilesExporter::SaveVerticalProfiles(), ccColorFromScalarDlg::updateColormaps(), and ccColorLevelsDlg::updateHistogram().
blue()
constexpr Rgb ecvColor::blue (0 , 0 , MAX) constexpr
Referenced by ccColorScaleEditorWidget::ccColorScaleEditorWidget(), ccColorScaleEditorDialog::createNewScale(), ColorScheme::Default(), ccCompass::estimateStrain(), LasScalarFieldLoader::handleRGBValue(), HSVDialog::HSVDialog(), LASFilter::loadFile(), HSVDialog::onItemPicked(), ecvConsole::refresh(), ccWaveWidget::refresh(), cloudViewer::visualization::rendering::ColorGradingParams::SetChannelMixer(), qCanupo2DViewDialog::trainClassifier(), qCanupoTools::TrainClassifier(), ccColorFromScalarDlg::updateColormaps(), ccColorLevelsDlg::updateHistogram(), ccPinchNode::updateMetadata(), and HSVDialog::updateValues().
bright()
constexpr Rgbaf ecvColor::bright (1. 00f, 1. 00f, 1. 00f, 1. 00f) constexpr
Referenced by DRCFilter::loadFile().
cyan()
constexpr Rgb ecvColor::cyan (0 , MAX , MAX) constexpr
Referenced by contourPoly(), contourPoly2(), and ccNote::updateMetadata().
dark()
constexpr Rgbaf ecvColor::dark (0. 34f, 0. 34f, 0. 34f, 1. 00f) constexpr
darkBlue()
constexpr Rgb ecvColor::darkBlue (0 , 0 , MAX/ 2) constexpr
Referenced by TemplateAlignment::compute().
darker()
constexpr Rgbaf ecvColor::darker (0. 17f, 0. 17f, 0. 17f, 1. 00f) constexpr
Referenced by DRCFilter::loadFile().
darkest()
constexpr Rgbaf ecvColor::darkest (0. 08f, 0. 08f, 0. 08f, 1. 00f) constexpr
darkGrey()
constexpr Rgb ecvColor::darkGrey (MAX/ 2, MAX/ 2, MAX/ 2) constexpr
Referenced by ccRasterizeTool::addNewContour(), and ccHistogramWindow::refresh().
defaultBkgColor()
constexpr Rgbub ecvColor::defaultBkgColor (135 , 206 , 235) constexpr
defaultColor()
constexpr Rgbub ecvColor::defaultColor (MAX , MAX , MAX) constexpr
defaultLabelBkgColor()
constexpr Rgbub ecvColor::defaultLabelBkgColor (MAX , MAX , MAX) constexpr
Referenced by define_ccDisplayTools(), and ecvDisplayTools::HotZone::HotZone().
defaultLabelMarkerColor()
constexpr Rgbub ecvColor::defaultLabelMarkerColor (MAX , 0 , MAX) constexpr
defaultMeshBackDiff()
constexpr Rgbaf ecvColor::defaultMeshBackDiff (0. 27f, 0. 90f, 0. 90f, 1. 00f) constexpr
defaultMeshFrontDiff()
constexpr Rgbaf ecvColor::defaultMeshFrontDiff (0. 00f, 0. 90f, 0. 27f, 1. 00f) constexpr
defaultViewBkgColor()
constexpr Rgbf ecvColor::defaultViewBkgColor (10/255. 0f, 102/255. 0f, 151/255. 0f) constexpr
FromQColor()
Rgb ecvColor::FromQColor (QColor qColor) inline
Conversion from QColor.
Definition at line 426 of file ecvColorTypes.h.
Referenced by ccCloudLayersHelper::mouseMove(), ccCloudLayersHelper::moveItem(), and ccEntityAction::setColor().
FromQColora()
Rgba ecvColor::FromQColora (QColor qColor) inline
Conversion from QColor'a'.
Definition at line 433 of file ecvColorTypes.h.
Referenced by ccCloudLayersHelper::apply(), and ccColorFromScalarDlg::onApply().
FromQColoraf()
Rgbaf ecvColor::FromQColoraf (QColor qColor) inline
Conversion from QColor'a' (floating point)
Definition at line 447 of file ecvColorTypes.h.
FromQColorf()
Rgbf ecvColor::FromQColorf (QColor qColor) inline
Conversion from QColor (floating point)
Definition at line 441 of file ecvColorTypes.h.
FromQRgb()
Rgb ecvColor::FromQRgb (QRgb qColor) inline
Conversion from QRgb.
Definition at line 411 of file ecvColorTypes.h.
Referenced by CSVMatrixFilter::loadFile().
FromQRgba()
Rgba ecvColor::FromQRgba (QRgb qColor) inline
Conversion from QRgb'a'.
Definition at line 418 of file ecvColorTypes.h.
FromRgb() [1/2]
Rgbf ecvColor::FromRgb (const Rgb & color) inline
Definition at line 386 of file ecvColorTypes.h.
References color, and MAX.
FromRgb() [2/2]
Rgbf ecvColor::FromRgb (const Rgba & color) inline
Definition at line 392 of file ecvColorTypes.h.
References color, and MAX.
FromRgba()
Rgbaf ecvColor::FromRgba (const Rgba & color) inline
Definition at line 398 of file ecvColorTypes.h.
References color, and MAX.
FromRgbafToRgb()
Rgb ecvColor::FromRgbafToRgb (const Rgbaf & color) inline
Conversion from Rgbaf.
Definition at line 365 of file ecvColorTypes.h.
References color, and MAX.
FromRgbafToRgba()
Rgba ecvColor::FromRgbafToRgba (const Rgbaf & color) inline
Conversion from Rgbaf to Rgba.
Definition at line 379 of file ecvColorTypes.h.
References color, and MAX.
FromRgbaToRgb()
Rgb ecvColor::FromRgbaToRgb (const Rgba & color) inline
Conversion from Rgba to Rgb.
Definition at line 374 of file ecvColorTypes.h.
References color.
FromRgbfToRgb()
Rgb ecvColor::FromRgbfToRgb (const Rgbf & color) inline
Conversion from Rgbf.
Definition at line 358 of file ecvColorTypes.h.
References color, and MAX.
FromRgbToRgba()
Rgba ecvColor::FromRgbToRgba (const Rgb & color) inline
Conversion from Rgb to Rgba.
Definition at line 371 of file ecvColorTypes.h.
References color, and MAX.
FromRgbub()
Rgbaf ecvColor::FromRgbub (const Rgbub & color) inline
Definition at line 404 of file ecvColorTypes.h.
References color, and MAX.
green()
constexpr Rgb ecvColor::green (0 , MAX , 0) constexpr
Referenced by ccGraphicalSegmentationTool::ccGraphicalSegmentationTool(), ccTracePolylineTool::ccTracePolylineTool(), qSRA::computeCloud2ProfileRadialDist(), ccPointPair::drawMeOnly(), ccTracePolylineTool::exportLine(), LasScalarFieldLoader::handleRGBValue(), HSVDialog::HSVDialog(), ProfileLoader::Load(), LASFilter::loadFile(), HSVDialog::onItemPicked(), ccTracePolylineTool::onItemPicked(), DxfProfilesExporter::SaveHorizontalProfiles(), DxfProfilesExporter::SaveVerticalProfiles(), cloudViewer::visualization::rendering::ColorGradingParams::SetChannelMixer(), cloudViewer::PointViewerWidget::Show(), ccColorFromScalarDlg::updateColormaps(), ccColorLevelsDlg::updateHistogram(), and HSVDialog::updateValues().
light()
constexpr Rgbaf ecvColor::light (0. 66f, 0. 66f, 0. 66f, 1. 00f) constexpr
Referenced by cloudViewer::visualization::rendering::FilamentScene::AddDirectionalLight(), cloudViewer::visualization::rendering::FilamentScene::AddPointLight(), cloudViewer::visualization::rendering::FilamentScene::AddSpotLight(), cloudViewer::visualization::rendering::FilamentScene::EnableIndirectLight(), cloudViewer::visualization::rendering::FilamentScene::EnableLightShadow(), cloudViewer::visualization::rendering::FilamentScene::GetIndirectLightIntensity(), cloudViewer::visualization::rendering::FilamentScene::GetIndirectLightRotation(), cloudViewer::visualization::rendering::FilamentScene::RemoveLight(), cloudViewer::visualization::rendering::FilamentScene::SetIndirectLight(), cloudViewer::visualization::rendering::FilamentScene::SetIndirectLightIntensity(), cloudViewer::visualization::rendering::FilamentScene::SetIndirectLightRotation(), cloudViewer::visualization::rendering::FilamentScene::UpdateLightColor(), cloudViewer::visualization::rendering::FilamentScene::UpdateLightDirection(), cloudViewer::visualization::rendering::FilamentScene::UpdateLightFalloff(), cloudViewer::visualization::rendering::FilamentScene::UpdateLightIntensity(), and cloudViewer::visualization::rendering::FilamentScene::UpdateLightPosition().
lighter()
constexpr Rgbaf ecvColor::lighter (0. 83f, 0. 83f, 0. 83f, 1. 00f) constexpr
Referenced by AnglesCustomPlot::createQCPBars().
lightGrey()
constexpr Rgb ecvColor::lightGrey (static_cast< ColorCompType > MAX *0.8, static_cast< ColorCompType > MAX *0.8, static_cast< ColorCompType > MAX *0.8) constexpr
Referenced by DistanceMapGenerationTool::ConvertMapToImage(), ccRasterizeTool::generateImage(), ccScalarField::getColor(), ccHistogramWindow::refresh(), ccHistogramWindow::refreshBars(), and qCanupoTools::TrainClassifier().
magenta()
constexpr Rgb ecvColor::magenta (MAX , 0 , MAX) constexpr
Referenced by ColorScheme::Default(), StereogramWidget::paintEvent(), cloudViewer::FeatureImageViewerWidget::ReadAndShowWithKeypoints(), and qCanupo2DViewDialog::resetBoundary().
middle()
constexpr Rgbaf ecvColor::middle (0. 50f, 0. 50f, 0. 50f, 1. 00f) constexpr
night()
constexpr Rgbaf ecvColor::night (0. 00f, 0. 00f, 0. 00f, 1. 00F) constexpr
oblack()
constexpr Rgba ecvColor::oblack (0 , 0 , 0 , OPACITY) constexpr
oblue()
constexpr Rgba ecvColor::oblue (0 , 0 , MAX , OPACITY) constexpr
ocyan()
constexpr Rgba ecvColor::ocyan (0 , MAX , MAX , OPACITY) constexpr
odarkBlue()
constexpr Rgba ecvColor::odarkBlue (0 , 0 , MAX/ 2, OPACITY) constexpr
odarkGrey()
constexpr Rgba ecvColor::odarkGrey (MAX/ 2, MAX/ 2, MAX/ 2, OPACITY) constexpr
ogreen()
constexpr Rgba ecvColor::ogreen (0 , MAX , 0 , OPACITY) constexpr
olightGrey()
constexpr Rgba ecvColor::olightGrey (static_cast< ColorCompType > MAX *0.8, static_cast< ColorCompType > MAX *0.8, static_cast< ColorCompType > MAX *0.8, OPACITY) constexpr
omagenta()
constexpr Rgba ecvColor::omagenta (MAX , 0 , MAX , OPACITY) constexpr
oorange()
constexpr Rgba ecvColor::oorange (MAX , MAX/ 2, 0 , OPACITY) constexpr
orange()
constexpr Rgb ecvColor::orange (MAX , MAX/ 2, 0) constexpr
Referenced by ccPinchNode::updateMetadata().
ored()
constexpr Rgba ecvColor::ored (MAX , 0 , 0 , OPACITY) constexpr
owhite()
constexpr Rgba ecvColor::owhite (MAX , MAX , MAX , OPACITY) constexpr
oyellow()
constexpr Rgba ecvColor::oyellow (MAX , MAX , 0 , OPACITY) constexpr
red()
constexpr Rgb ecvColor::red (MAX , 0 , 0) constexpr
Referenced by ccPointPairRegistrationDlg::addAlignedPoint(), ccAlignDlg::ccAlignDlg(), ccColorScaleEditorWidget::ccColorScaleEditorWidget(), ccOrderChoiceDlg::ccOrderChoiceDlg(), ccRegistrationDlg::ccRegistrationDlg(), ExtractSIFT::compute(), ccColorScaleEditorDialog::createNewScale(), ColorScheme::Default(), ColorScheme::Dracula(), ccContourExtractor::ExtractConcaveHull2D(), FastGlobalRegistrationDialog::FastGlobalRegistrationDialog(), LasScalarFieldLoader::handleRGBValue(), HSVDialog::HSVDialog(), LASFilter::loadFile(), HSVDialog::onItemPicked(), StereogramWidget::paintEvent(), ColorScaleElementSlider::paintEvent(), cloudViewer::FeatureImageViewerWidget::ReadAndShowWithKeypoints(), ecvConsole::refresh(), ccHistogramWindow::refresh(), ccWaveWidget::refresh(), DxfProfilesExporter::SaveHorizontalProfiles(), DxfProfilesExporter::SaveVerticalProfiles(), cloudViewer::visualization::rendering::ColorGradingParams::SetChannelMixer(), ccAlignDlg::setColorsAndLabels(), ccOrderChoiceDlg::setColorsAndLabels(), cloudViewer::PointViewerWidget::Show(), qCanupo2DViewDialog::trainClassifier(), qCanupoTools::TrainClassifier(), ccColorFromScalarDlg::updateColormaps(), ccRegistrationDlg::updateGUI(), FastGlobalRegistrationDialog::updateGUI(), ccColorLevelsDlg::updateHistogram(), ccNote::updateMetadata(), HSVDialog::updateValues(), and WolmanCustomPlot::WolmanCustomPlot().
white()
constexpr Rgb ecvColor::white (MAX , MAX , MAX) constexpr
Referenced by ComputeAverageColor(), cc2Point5DimEditor::create2DView(), ColorScheme::Default(), DistanceMapGenerationDlg::DistanceMapGenerationDlg(), cloudViewer::visualization::GuiSettingsModel::GetCurrentMaterialColor(), ccContourExtractorDlg::init(), ecvAnnotationsTool::onLabelChanged(), ccColorScaleEditorWidget::onPointClicked(), StereogramWidget::paintEvent(), QCPHiddenArea::QCPHiddenArea(), ccEntityAction::setColor(), ccColorFromScalarDlg::updateColormaps(), and ecvAnnotationsTool::updateLabelsCombox().
yellow()
constexpr Rgb ecvColor::yellow (MAX , MAX , 0) constexpr
Referenced by ccPointPairRegistrationDlg::addReferencePoint(), ccAlignDlg::ccAlignDlg(), ccOrderChoiceDlg::ccOrderChoiceDlg(), ccRegistrationDlg::ccRegistrationDlg(), ColorScheme::Default(), ccGraphicalSegmentationTool::doExportSegmentationPolyline(), FastGlobalRegistrationDialog::FastGlobalRegistrationDialog(), ccAlignDlg::setColorsAndLabels(), ccOrderChoiceDlg::setColorsAndLabels(), ccRegistrationDlg::updateGUI(), and FastGlobalRegistrationDialog::updateGUI().
Variable Documentation
MAX
constexpr ColorCompType ecvColor::MAX = 255 constexpr
Max value of a single color component (default type)
Definition at line 34 of file ecvColorTypes.h.
Referenced by ccCloudLayersHelper::apply(), ComputeAverageColor(), GrainsAsEllipsoids::exportResultsAsCloud(), ecvColor::RgbTpl< Type >::FromEigen(), FromFbxMesh(), FromRgb(), FromRgba(), FromRgbafToRgb(), FromRgbafToRgba(), FromRgbfToRgb(), FromRgbToRgba(), FromRgbub(), GetKeyCluster(), ecvColor::Convert::hsl2rgb(), ecvColor::Convert::hsv2rgb(), ccCloudLayersHelper::mouseMove(), ccColorFromScalarDlg::onApply(), ccColorLevelsDlg::onApply(), MAFilter::saveToFile(), GrainsAsEllipsoids::setGrainColorsTable(), ToFbxMesh(), and GrainsAsEllipsoids::updateMeshAndLineSet().
OPACITY
constexpr ColorCompType ecvColor::OPACITY = 255 constexpr
Definition at line 35 of file ecvColorTypes.h.