ACloudViewer: cloudViewer Namespace Reference
cloudViewer Namespace Reference
Generic file read and write utility for python interface.
Namespaces
benchmarks
camera
core
data
geometry
gpu
io
ml
pipelines
ply_lineset_reader
ply_pointcloud_reader
ply_trianglemesh_reader
ply_voxelgrid_reader
system
t
utility
visualization
visualizer
Classes
class AutoSegmentationTools
class BoundingBoxTpl
Bounding box structure.
class ChamferDistanceTransform
Class to compute a Chamfer distance field on a 3D grid.
class CloudSamplingTools
Several point cloud resampling algorithms (octree-based, random, etc.)
class ConjugateGradient
A class to perform a conjugate gradient optimization.
class KDTree
class CCMiscTools
Miscellaneous useful functions (geometrical elements handling)
class PointCloud
class CVToolbox
Empty class - for classification purpose only.
class Delaunay2dMesh
A class to compute and handle a Delaunay 2D mesh on a subset of points.
class DgmOctree
The octree structure used throughout the library.
class DgmOctreeReferenceCloud
A kind of ReferenceCloud based on the DgmOctree::NeighboursSet structure.
class DistanceComputationTools
class ErrorFunction
A class to compute the Error function (erf)
class FastMarching
Fast Marching algorithm (front propagation)
class FastMarchingForPropagation
Fast Marching algorithm for surface front propagation.
class GenericCloud
class GenericDistribution
A generic class to handle a probability distribution.
class GenericIndexedCloud
A generic 3D point cloud with index-based point access.
class GenericIndexedCloudPersist
A generic 3D point cloud with index-based and presistent access to points.
struct VerticesIndexes
Triangle described by the indexes of its 3 vertices.
class GenericIndexedMesh
A generic mesh with index-based vertex access.
class GenericMesh
class GenericOctree
class GenericProgressCallback
class NormalizedProgress
class GenericTriangle
A generic triangle interface.
class GeometricalAnalysisTools
class Grid3D
Simple 3D grid structure.
class LocalModel
Local modelization (generic interface)
class ManualSegmentationTools
Manual segmentation algorithms (inside/outside a polyline, etc.)
class MathTools
Empty class - for classification purpose only.
class MeshSamplingTools
Mesh sampling algorithms.
class Neighbourhood
class NormalDistribution
The Normal/Gaussian statistical distribution.
class OrientedBoundingBox
A bounding box oriented along an arbitrary frame of reference.
class PointCloudTpl
class PointProjectionTools
class Polyline
A simple polyline class.
class ReferenceCloud
A very simple point cloud (no point duplication)
class RegistrationTools
Common point cloud registration algorithms.
class HornRegistrationTools
Horn point cloud registration algorithm.
class ICPRegistrationTools
ICP point cloud registration algorithm (Besl et al.).
class FPCSRegistrationTools
class SaitoSquaredDistanceTransform
class ScalarField
A simple scalar field (to be associated to a point cloud)
struct KMeanClass
A K-mean class position and boundaries.
class ScalarFieldTools
Several scalar field treatment algorithms (gradient, classification, etc.)
class SimpleMesh
A simple mesh structure, with index-based vertex access.
class SimpleRefTriangle
A simple triangle class.
class SimpleTriangle
A simple triangle class.
class SquareMatrixTpl
Square matrix.
class StaticVector
class StatisticalTestingTools
class TrueKdTree
Proper KD-tree implementation.
struct uni_elt
class Universe
Allows to perform labelling by creating node and connecting them.
class WeibullDistribution
The Weibull statistical parametric distribution.
struct TriangleList
List of triangles (indexes)
struct OctreeAndMeshIntersection
class AutomaticReconstructionWidget
class BundleAdjustmentWidget
class AutomaticReconstructionController
class ViewInterpolate
The ViewInterpolate class.
class TwoViewInfoTab
class MatchesTab
class TwoViewGeometriesTab
class OverlappingImagesWidget
class CameraTab
class ImageTab
class DatabaseManagementWidget
class DenseReconstructionOptionsWidget
class DenseReconstructionWidget
class ExtractionWidget
class SIFTExtractionWidget
class ImportFeaturesWidget
class FeatureExtractionWidget
class FeatureMatchingTab
class ExhaustiveMatchingTab
class SequentialMatchingTab
class VocabTreeMatchingTab
class SpatialMatchingTab
class TransitiveMatchingTab
class CustomMatchingTab
class FeatureMatchingWidget
class ImageViewerGraphicsScene
class ImageViewerWidget
class FeatureImageViewerWidget
class DatabaseImageViewerWidget
class StandardOutputRedirector
class LogWidget
class MatchMatrixWidget
class ModelViewerWidget
class MovieGrabberWidget
class PointViewerWidget
class ProjectWidget
class ReconstructionManagerWidget
class MapperGeneralOptionsWidget
class MapperTriangulationOptionsWidget
class MapperRegistrationOptionsWidget
class MapperInitializationOptionsWidget
class MapperBundleAdjustmentOptionsWidget
class MapperFilteringOptionsWidget
class ReconstructionOptionsWidget
class ReconstructionStatsWidget
class ReconstructionWidget
class RenderOptionsWidget
class ThreadControlWidget
class UndistortionWidget
class AlignmentSession
class VisualizerForAlignment
class OptionsParser
Typedefs
using ReferenceCloudContainer = std::vector< ReferenceCloud * >
A standard container to store several subsets of points.
using BoundingBox = BoundingBoxTpl< PointCoordinateType >
Default bounding-box type.
using SquareMatrix = SquareMatrixTpl< PointCoordinateType >
Default CC square matrix type (PointCoordinateType)
using SquareMatrixf = SquareMatrixTpl< float >
Float square matrix type.
using SquareMatrixd = SquareMatrixTpl< double >
Double square matrix type.
using StaticVectorBool = StaticVector< char >
using BundleAdjustmentController = colmap::BundleAdjustmentController
using OptionManager = colmap::OptionManager
using PointColormapBase = colmap::PointColormapBase
using ImageColormapBase = colmap::ImageColormapBase
using RenderOptions = colmap::RenderOptions
using IncrementalMapperController = colmap::IncrementalMapperController
using IncrementalMapperOptions = colmap::IncrementalMapperOptions
using ImageColormapNameFilter = colmap::ImageColormapNameFilter
Enumerations
enum TRIANGULATION_TYPES { DELAUNAY_2D_AXIS_ALIGNED , DELAUNAY_2D_BEST_LS_PLANE = 2 }
Triangulation types.
Functions
void PrintCloudViewerVersion ()
std::string GetCloudViewerVersion ()
std::string GetBuildInfo ()
std::string GetCloudViewerBuildInfo ()
bool LessThanEpsilon (float x)
Test a floating point number against our epsilon (a very small number).
bool LessThanEpsilon (double x)
Test a floating point number against our epsilon (a very small number).
bool GreaterThanEpsilon (float x)
Test a floating point number against our epsilon (a very small number).
bool GreaterThanEpsilon (double x)
Test a floating point number against our epsilon (a very small number).
bool GreaterThanSquareEpsilon (double x)
bool LessThanSquareEpsilon (double x)
float RadiansToDegrees (int radians)
Convert radians to degrees.
float RadiansToDegrees (float radians)
Convert radians to degrees.
double RadiansToDegrees (double radians)
Convert radians to degrees.
float DegreesToRadians (int degrees)
Convert degrees to radians.
float DegreesToRadians (float degrees)
Convert degrees to radians.
double DegreesToRadians (double degrees)
Convert degrees to radians.
template<class T >
int sizeOfStaticVector (const StaticVector< T > *a)
template<class T >
int sizeOfStaticVector (const StaticVector< T > &a)
template<class T >
int indexOf (T *arr, int n, const T &what)
template<class T >
void saveArrayOfArraysToFile (std::string fileName, StaticVector< StaticVector< T > * > *aa)
template<class T >
void saveArrayOfArraysToFile (const std::string fileName, StaticVector< StaticVector< T >> &aa)
template<class T >
StaticVector< StaticVector< T > * > * loadArrayOfArraysFromFile (const std::string &fileName)
template<class T >
void loadArrayOfArraysFromFile (StaticVector< StaticVector< T >> &out_aa, const std::string &fileName)
template<class T >
void saveArrayToFile (const std::string &fileName, const StaticVector< T > &a, bool docompress=true)
template<class T >
void saveArrayToFile (const std::string &fileName, const StaticVector< T > *a, bool docompress=true)
template<class T >
StaticVector< T > * loadArrayFromFile (const std::string &fileName, bool printfWarning=false)
template<class T >
bool loadArrayFromFile (StaticVector< T > &out, const std::string &fileName, bool printfWarning=false)
template<class T >
void loadArrayFromFileIntoArray (StaticVector< T > *a, const std::string &fileName, bool printfWarning=false)
int getArrayLengthFromFile (std::string fileName)
template<class T >
void deleteArrayOfArrays (StaticVector< StaticVector< T > * > **aa)
template<class T >
void deleteArrayOfArrays (StaticVector< StaticVector< T > * > &aa)
template<class T >
StaticVector< StaticVector< T > * > * cloneArrayOfArrays (StaticVector< StaticVector< T > * > *inAOA)
template<class T >
T InterpolateNumber (T start, T end, double interpolationFraction)
template<typename scalar_t , typename T >
CLOUDVIEWER_HOST_DEVICE bool IsClose (const scalar_t &x, const T &y, const double rtol=1e-4)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE scalar_t Square (const scalar_t &x)
int GraphicalUserInterface (const std::string &database_path, const std::string &image_path, const std::string &import_path)
int GenerateProject (const std::string &output_path, const std::string &quality)
int CleanDatabase (const std::string &database_path, const std::string &clean_type)
int CreateDatabase (const std::string &database_path)
int MergeDatabase (const std::string &database_path1, const std::string &database_path2, const std::string &merged_database_path)
int ExtractFeature (const std::string &database_path, const std::string &image_path, const std::string &image_list_path, int camera_mode, const colmap::ImageReaderOptions &image_reader_options, const colmap::SiftExtractionOptions &sift_extraction_options)
int ImportFeature (const std::string &database_path, const std::string &image_path, const std::string &import_path, const std::string &image_list_path, int camera_mode, const colmap::ImageReaderOptions &image_reader_options, const colmap::SiftExtractionOptions &sift_extraction_options)
int ImportMatches (const std::string &database_path, const std::string &match_list_path, const std::string &match_type, const colmap::SiftMatchingOptions &sift_matching_options)
int ExhaustiveMatch (const std::string &database_path, const colmap::SiftMatchingOptions &sift_matching_options, const colmap::ExhaustiveMatchingOptions &exhaustive_matching_options)
int SequentialMatch (const std::string &database_path, const colmap::SiftMatchingOptions &sift_matching_options, const colmap::SequentialMatchingOptions &sequential_matching_options)
int SpatialMatch (const std::string &database_path, const colmap::SiftMatchingOptions &sift_matching_options, const colmap::SpatialMatchingOptions &spatial_matching_options)
int TransitiveMatch (const std::string &database_path, const colmap::SiftMatchingOptions &sift_matching_options, const colmap::TransitiveMatchingOptions &transitive_matching_options)
int VocabTreeMatch (const std::string &database_path, const colmap::SiftMatchingOptions &sift_matching_options, const colmap::VocabTreeMatchingOptions &vocab_tree_matching_options)
int DeleteImage (const std::string &input_path, const std::string &output_path, const std::string &image_ids_path, const std::string &image_names_path)
int FilterImage (const std::string &input_path, const std::string &output_path, double min_focal_length_ratio, double max_focal_length_ratio, double max_extra_param, std::size_t min_num_observations)
int RectifyImage (const std::string &image_path, const std::string &input_path, const std::string &output_path, const std::string &stereo_pairs_list, double blank_pixels, double min_scale, double max_scale, int max_image_size)
int RegisterImage (const std::string &database_path, const std::string &input_path, const std::string &output_path, const colmap::IncrementalMapperOptions &incremental_mapper_options)
int UndistortImage (const std::string &image_path, const std::string &input_path, const std::string &output_path, const std::string &image_list_path, const std::string &output_type, const std::string &copy_policy, int num_patch_match_src_images, double blank_pixels, double min_scale, double max_scale, int max_image_size, double roi_min_x, double roi_min_y, double roi_max_x, double roi_max_y)
int UndistortImageStandalone (const std::string &image_path, const std::string &input_file, const std::string &output_path, double blank_pixels, double min_scale, double max_scale, int max_image_size, double roi_min_x, double roi_min_y, double roi_max_x, double roi_max_y)
int AlignModel (const std::string &input_path, const std::string &output_path, const std::string &database_path, const std::string &ref_images_path, const std::string &transform_path, const std::string &alignment_type, double max_error, int min_common_images, bool robust_alignment, bool estimate_scale)
int AnalyzeModel (const std::string &input_path)
int CompareModel (const std::string &input_path1, const std::string &input_path2, const std::string &output_path, double min_inlier_observations, double max_reproj_error)
int ConvertModel (const std::string &input_path, const std::string &output_path, const std::string &output_type, bool skip_distortion)
int CropModel (const std::string &input_path, const std::string &output_path, const std::string &boundary, const std::string &gps_transform_path)
int MergeModel (const std::string &input_path1, const std::string &input_path2, const std::string &output_path, double max_reproj_error)
int AlignModelOrientation (const std::string &image_path, const std::string &input_path, const std::string &output_path, std::string method, int max_image_size)
int SplitModel (const std::string &input_path, const std::string &output_path, const std::string &split_type, const std::string &split_params, const std::string &gps_transform_path, std::size_t min_reg_images, std::size_t min_num_points, double overlap_ratio, double min_area_ratio, int num_threads)
int TransformModel (const std::string &input_path, const std::string &output_path, const std::string &transform_path, bool is_inverse)
int MeshDelaunay (const std::string &input_path, const std::string &output_path, const std::string &input_type, const colmap::mvs::DelaunayMeshingOptions &delaunay_meshing_options)
int StereoPatchMatch (const std::string &workspace_path, const std::string &config_path, const std::string &workspace_format, const std::string &pmvs_option_name, const colmap::mvs::PatchMatchOptions &patch_match_options)
int MeshPoisson (const std::string &input_path, const std::string &output_path, const colmap::mvs::PoissonMeshingOptions &poisson_meshing_options)
int StereoFuse (const std::string &workspace_path, const std::string &output_path, const std::string &bbox_path, const std::string &stereo_input_type, const std::string &output_type, const std::string &workspace_format, const std::string &pmvs_option_name, const colmap::mvs::StereoFusionOptions &stereo_fusion_options)
int AutomaticReconstruct (const std::string &workspace_path, const std::string &image_path, const std::string &mask_path, const std::string &vocab_tree_path, const std::string &data_type, const std::string &quality, const std::string &mesher, const std::string &camera_model, bool single_camera, bool sparse, bool dense, int num_threads, bool use_gpu, const std::string &gpu_index)
int BundleAdjustment (const std::string &input_path, const std::string &output_path, const colmap::BundleAdjustmentOptions &bundle_adjustment_options)
int ExtractColor (const std::string &image_path, const std::string &input_path, const std::string &output_path)
int NormalMapper (const std::string &database_path, const std::string &image_path, const std::string &input_path, const std::string &output_path, const std::string &image_list_path, const colmap::IncrementalMapperOptions &incremental_mapper_options)
int HierarchicalMapper (const std::string &database_path, const std::string &image_path, const std::string &output_path, int num_workers, int image_overlap, int leaf_max_num_images, const colmap::IncrementalMapperOptions &incremental_mapper_options)
int FilterPoints (const std::string &input_path, const std::string &output_path, std::size_t min_track_len, double max_reproj_error, double min_tri_angle)
int TriangulatePoints (const std::string &database_path, const std::string &image_path, const std::string &input_path, const std::string &output_path, bool clear_points, const colmap::IncrementalMapperOptions &incremental_mapper_options)
int RigBundleAdjust (const std::string &input_path, const std::string &output_path, const std::string &rig_config_path, bool estimate_rig_relative_poses, bool refine_relative_poses, const colmap::BundleAdjustmentOptions &bundle_adjustment_options)
int BuildVocabTree (const std::string &database_path, const std::string &vocab_tree_path, int num_visual_words, int num_checks, int branching, int num_iterations, int max_num_images)
int RetrieveVocabTree (const std::string &database_path, const std::string &vocab_tree_path, const std::string &output_index_path, const std::string &query_image_list_path, const std::string &database_image_list_path, int max_num_images, int num_neighbors, int num_checks, int num_images_after_verification, int max_num_features)
Variables
static const std::string CLOUDVIEWER_VERSION_STR = "3.9.4"
static const std::string CLOUDVIEWER_GIT_COMMIT_ID = "f89b7a10e"
static const std::string CLOUDVIEWER_GIT_COMMIT_DATE = "2026-01-29"
static const double c_erfRelativeError = 1e-12
Relative error for Error Function computation.
const int c_FastMarchingNeighbourPosShift []
Grid neighboring cells positions.
Detailed Description
Generic file read and write utility for python interface.
Gives static access to file loader and writer
Typedef Documentation
BoundingBox
using cloudViewer::BoundingBox = typedef BoundingBoxTpl<PointCoordinateType>
Default bounding-box type.
Definition at line 304 of file BoundingBox.h.
BundleAdjustmentController
using cloudViewer::BundleAdjustmentController = typedef colmap::BundleAdjustmentController
Definition at line 17 of file BundleAdjustmentWidget.cpp.
ImageColormapBase
using cloudViewer::ImageColormapBase = typedef colmap::ImageColormapBase
Definition at line 33 of file ModelViewerWidget.h.
ImageColormapNameFilter
using cloudViewer::ImageColormapNameFilter = typedef colmap::ImageColormapNameFilter
Definition at line 22 of file RenderOptionsWidget.h.
IncrementalMapperController
using cloudViewer::IncrementalMapperController = typedef colmap::IncrementalMapperController
Definition at line 38 of file ReconstructionWidget.h.
IncrementalMapperOptions
using cloudViewer::IncrementalMapperOptions = typedef colmap::IncrementalMapperOptions
Definition at line 39 of file ReconstructionWidget.h.
OptionManager
typedef colmap::OptionManager cloudViewer::OptionManager
Definition at line 19 of file BundleAdjustmentWidget.h.
PointColormapBase
using cloudViewer::PointColormapBase = typedef colmap::PointColormapBase
Definition at line 32 of file ModelViewerWidget.h.
ReferenceCloudContainer
using cloudViewer::ReferenceCloudContainer = typedef std::vector<ReferenceCloud*>
A standard container to store several subsets of points.
Several algorithms of the AutoSegmentationTools toolbox return a collection of subsets of points corresponding to each segmented part. Such a collection is generally stored in this type of container.
Definition at line 28 of file AutoSegmentationTools.h.
RenderOptions
typedef colmap::RenderOptions cloudViewer::RenderOptions
Definition at line 35 of file ModelViewerWidget.h.
SquareMatrix
using cloudViewer::SquareMatrix = typedef SquareMatrixTpl<PointCoordinateType>
Default CC square matrix type (PointCoordinateType)
Definition at line 1020 of file SquareMatrix.h.
SquareMatrixd
using cloudViewer::SquareMatrixd = typedef SquareMatrixTpl<double>
Double square matrix type.
Definition at line 1026 of file SquareMatrix.h.
SquareMatrixf
using cloudViewer::SquareMatrixf = typedef SquareMatrixTpl<float>
Float square matrix type.
Definition at line 1023 of file SquareMatrix.h.
StaticVectorBool
using cloudViewer::StaticVectorBool = typedef StaticVector<char>
Definition at line 145 of file StaticVector.h.
Enumeration Type Documentation
TRIANGULATION_TYPES
enum cloudViewer::TRIANGULATION_TYPES
Triangulation types.
Enumerator
DELAUNAY_2D_AXIS_ALIGNED
Delaunay 2D triangulation in an axis-aligned plane
DELAUNAY_2D_BEST_LS_PLANE
Delaunay 2D with points projected on the best least square fitting plane
Definition at line 22 of file PointProjectionTools.h.
Function Documentation
AlignModel()
int cloudViewer::AlignModel (const std::string & input_path, const std::string & output_path, const std::string & database_path, const std::string & ref_images_path, const std::string & transform_path, const std::string & alignment_type, double max_error, int min_common_images, bool robust_alignment, bool estimate_scale)
Definition at line 15 of file model.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunModelAligner().
AlignModelOrientation()
int cloudViewer::AlignModelOrientation (const std::string & image_path, const std::string & input_path, const std::string & output_path, std::string method, int max_image_size)
Definition at line 109 of file model.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunModelOrientationAligner().
AnalyzeModel()
int cloudViewer::AnalyzeModel (const std::string & input_path)
Definition at line 42 of file model.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunModelAnalyzer().
AutomaticReconstruct()
int cloudViewer::AutomaticReconstruct (const std::string & workspace_path, const std::string & image_path, const std::string & mask_path, const std::string & vocab_tree_path, const std::string & data_type, const std::string & quality, const std::string & mesher, const std::string & camera_model, bool single_camera, bool sparse, bool dense, int num_threads, bool use_gpu, const std::string & gpu_index)
Definition at line 15 of file sfm.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunAutomaticReconstructor().
BuildVocabTree()
int cloudViewer::BuildVocabTree (const std::string & database_path, const std::string & vocab_tree_path, int num_visual_words, int num_checks, int branching, int num_iterations, int max_num_images)
Definition at line 15 of file vocab_tree.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunVocabTreeBuilder().
BundleAdjustment()
int cloudViewer::BundleAdjustment (const std::string & input_path, const std::string & output_path, const colmap::BundleAdjustmentOptions & bundle_adjustment_options)
Definition at line 58 of file sfm.cpp.
References cloudViewer::OptionsParser::addBundleAdjustmentOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunBundleAdjuster().
CleanDatabase()
int cloudViewer::CleanDatabase (const std::string & database_path, const std::string & clean_type)
Definition at line 15 of file database.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunDatabaseCleaner().
cloneArrayOfArrays()
template<class T > StaticVector<StaticVector<T>*>* cloudViewer::cloneArrayOfArrays (StaticVector< StaticVector< T > * > * inAOA)
Definition at line 714 of file StaticVector.h.
References NULL, cloudViewer::StaticVector< T >::push_back(), cloudViewer::StaticVector< T >::push_back_arr(), cloudViewer::StaticVector< T >::reserve(), and size.
CompareModel()
int cloudViewer::CompareModel (const std::string & input_path1, const std::string & input_path2, const std::string & output_path, double min_inlier_observations, double max_reproj_error)
Definition at line 50 of file model.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunModelComparer().
ConvertModel()
int cloudViewer::ConvertModel (const std::string & input_path, const std::string & output_path, const std::string & output_type, bool skip_distortion)
Definition at line 66 of file model.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunModelConverter().
CreateDatabase()
int cloudViewer::CreateDatabase (const std::string & database_path)
Definition at line 26 of file database.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunDatabaseCreator().
CropModel()
int cloudViewer::CropModel (const std::string & input_path, const std::string & output_path, const std::string & boundary, const std::string & gps_transform_path)
Definition at line 81 of file model.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunModelCropper().
DegreesToRadians() [1/3]
double cloudViewer::DegreesToRadians (double degrees) inline
Convert degrees to radians.
Parameters
degrees Degrees to convert
Returns
degrees represented as radians.
Definition at line 116 of file CVMath.h.
References M_PI.
DegreesToRadians() [2/3]
float cloudViewer::DegreesToRadians (float degrees) inline
Convert degrees to radians.
Parameters
degrees Degrees to convert
Returns
degrees represented as radians.
Definition at line 107 of file CVMath.h.
References M_PI.
DegreesToRadians() [3/3]
float cloudViewer::DegreesToRadians (int degrees) inline
Convert degrees to radians.
Parameters
degrees Degrees to convert
Returns
degrees represented as radians.
Definition at line 98 of file CVMath.h.
References M_PI.
Referenced by PdmsTools::PdmsCommands::Orientation::axisFromCoords(), ecvDisplayTools::ComputeActualPixelSize(), ecvViewportParameters::computeDistanceToHalfWidthRatio(), ccPointCloud::computeNormalsWithGrids(), ecvDisplayTools::ComputePerspectiveZoom(), ConvertAngleToRad(), ccNormalVectors::ConvertDipAndDipDirToNormal(), ecvPrimitiveFactoryDlg::createPrimitive(), define_CCMath(), cloudViewer::PointProjectionTools::developCloudOnCone(), ccPolyline::drawMeOnly(), ccKdTreeForFacetExtraction::FuseCells(), ccRasterizeTool::generateHillshade(), PCLModules::GetBoundaryCloud(), PCLModules::GetGreedyTriangulation(), qHoughNormalsDialog::getParameters(), PdmsTools::PdmsCommands::NumericalValue::getValue(), ccCompass::importFoliations(), ccCompassImport::importFoliations(), ccCompass::importLineations(), ccCompassImport::importLineations(), StereogramWidget::init(), QVTKWidgetCustom::mouseMoveEvent(), ccApplyTransformationDlg::onEulerValueChanged(), ccApplyTransformationDlg::onRotAngleValueChanged(), StereogramWidget::paintEvent(), ecvGenericDisplayTools::Perspective(), ecvDisplayTools::SetCameraFovy(), ecvDisplayTools::SetPerspectiveState(), ecvDisplayTools::SetupProjectiveViewport(), ecvDisplayTools::SetViewportParameters(), ccPointCloud::triangulateGrid(), ccPointCloud::unroll(), ccApplyTransformationDlg::updateAll(), ccCamSensorProjectionDlg::updateCamSensor(), ccGBLSensorProjectionDlg::updateGBLSensor(), and ccPlaneEditDlg::updatePlane().
deleteArrayOfArrays() [1/2]
template<class T > void cloudViewer::deleteArrayOfArrays (StaticVector< StaticVector< T > * > & aa)
Definition at line 703 of file StaticVector.h.
deleteArrayOfArrays() [2/2]
template<class T > void cloudViewer::deleteArrayOfArrays (StaticVector< StaticVector< T > * > ** aa)
Definition at line 692 of file StaticVector.h.
DeleteImage()
int cloudViewer::DeleteImage (const std::string & input_path, const std::string & output_path, const std::string & image_ids_path, const std::string & image_names_path)
Definition at line 15 of file image.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunImageDeleter().
ExhaustiveMatch()
int cloudViewer::ExhaustiveMatch (const std::string & database_path, const colmap::SiftMatchingOptions & sift_matching_options, const colmap::ExhaustiveMatchingOptions & exhaustive_matching_options)
Definition at line 69 of file feature.cpp.
References cloudViewer::OptionsParser::addExhaustiveMatchingOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunExhaustiveMatcher().
ExtractColor()
int cloudViewer::ExtractColor (const std::string & image_path, const std::string & input_path, const std::string & output_path)
Definition at line 71 of file sfm.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunColorExtractor().
ExtractFeature()
int cloudViewer::ExtractFeature (const std::string & database_path, const std::string & image_path, const std::string & image_list_path, int camera_mode, const colmap::ImageReaderOptions & image_reader_options, const colmap::SiftExtractionOptions & sift_extraction_options)
Definition at line 15 of file feature.cpp.
References cloudViewer::OptionsParser::addExtractionOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunFeatureExtractor().
FilterImage()
int cloudViewer::FilterImage (const std::string & input_path, const std::string & output_path, double min_focal_length_ratio, double max_focal_length_ratio, double max_extra_param, std::size_t min_num_observations)
Definition at line 31 of file image.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunImageFilterer().
FilterPoints()
int cloudViewer::FilterPoints (const std::string & input_path, const std::string & output_path, std::size_t min_track_len, double max_reproj_error, double min_tri_angle)
Definition at line 123 of file sfm.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunPointFiltering().
GenerateProject()
int cloudViewer::GenerateProject (const std::string & output_path, const std::string & quality)
Definition at line 42 of file application_gui.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunProjectGenerator().
getArrayLengthFromFile()
int cloudViewer::getArrayLengthFromFile (std::string fileName)
Definition at line 14 of file StaticVector.cpp.
References CVLog::Warning().
GetBuildInfo()
std::string cloudViewer::GetBuildInfo ()
Definition at line 20 of file CloudViewerConfig.cpp.
References CLOUDVIEWER_GIT_COMMIT_DATE, and CLOUDVIEWER_GIT_COMMIT_ID.
Referenced by ecvAboutDialog::ecvAboutDialog(), and GetCloudViewerBuildInfo().
GetCloudViewerBuildInfo()
std::string cloudViewer::GetCloudViewerBuildInfo ()
Definition at line 30 of file CloudViewerConfig.cpp.
References GetBuildInfo(), and GetCloudViewerVersion().
GetCloudViewerVersion()
std::string cloudViewer::GetCloudViewerVersion ()
Definition at line 18 of file CloudViewerConfig.cpp.
References CLOUDVIEWER_VERSION.
Referenced by GetCloudViewerBuildInfo().
GraphicalUserInterface()
int cloudViewer::GraphicalUserInterface (const std::string & database_path, const std::string & image_path, const std::string & import_path)
Definition at line 21 of file application_gui.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), InitQtResources(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunGraphicalUserInterface().
GreaterThanEpsilon() [1/2]
bool cloudViewer::GreaterThanEpsilon (double x) inline
Test a floating point number against our epsilon (a very small number).
Parameters
x The number to test
Returns
True if the number is greater than epsilon.
Definition at line 44 of file CVMath.h.
References x, and ZERO_TOLERANCE_D.
GreaterThanEpsilon() [2/2]
bool cloudViewer::GreaterThanEpsilon (float x) inline
Test a floating point number against our epsilon (a very small number).
Parameters
x The number to test
Returns
True if the number is greater than epsilon.
Definition at line 37 of file CVMath.h.
References x, and ZERO_TOLERANCE_F.
Referenced by ccScalarFieldArithmeticsDlg::Apply(), Mouse3DInput::Apply(), cloudViewer::StatisticalTestingTools::computeAdaptativeChi2Dist(), cloudViewer::GeometricalAnalysisTools::ComputeApproxPointsDensityInACellAtLevel(), cloudViewer::DistanceComputationTools::computeCloud2PolylineEquation(), ComputeFacetExtensions(), cloudViewer::WeibullDistribution::ComputeG(), define_CCMath(), cc2DViewportLabel::drawMeOnly(), qFacets::exportFacets(), cloudViewer::WeibullDistribution::FindGRoot(), ccGLMatrixTpl< T >::getParameters(), ccSubsamplingDlg::getSampledCloud(), cloudViewer::DistanceComputationTools::intersectMeshWithOctree(), PdmsTools::PdmsObjects::GenericItem::isOrientationValid(), CommandSubsample::process(), ccGBLSensor::projectNormals(), cloudViewer::ModelViewerWidget::SelectObject(), ecvDisplayTools::SetPerspectiveState(), PdmsTools::PdmsObjects::Dish::surface(), GamepadInput::update(), qAnimationDlg::updateSmoothTrajectoryDurations(), and DistanceMapGenerationDlg::updateZoom().
GreaterThanSquareEpsilon()
bool cloudViewer::GreaterThanSquareEpsilon (double x) inline
Test a (squared) floating point number against our epsilon (a very small number).
Parameters
x The number to test
Returns
True if the number is greater than epsilon.
Definition at line 52 of file CVMath.h.
References x, and ZERO_SQUARED_TOLERANCE_D.
Referenced by cloudViewer::Grid3D< Type >::intersectWith().
HierarchicalMapper()
int cloudViewer::HierarchicalMapper (const std::string & database_path, const std::string & image_path, const std::string & output_path, int num_workers, int image_overlap, int leaf_max_num_images, const colmap::IncrementalMapperOptions & incremental_mapper_options)
Definition at line 102 of file sfm.cpp.
References cloudViewer::OptionsParser::addMapperOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunHierarchicalMapper().
ImportFeature()
int cloudViewer::ImportFeature (const std::string & database_path, const std::string & image_path, const std::string & import_path, const std::string & image_list_path, int camera_mode, const colmap::ImageReaderOptions & image_reader_options, const colmap::SiftExtractionOptions & sift_extraction_options)
Definition at line 34 of file feature.cpp.
References cloudViewer::OptionsParser::addExtractionOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunFeatureImporter().
ImportMatches()
int cloudViewer::ImportMatches (const std::string & database_path, const std::string & match_list_path, const std::string & match_type, const colmap::SiftMatchingOptions & sift_matching_options)
Definition at line 54 of file feature.cpp.
References cloudViewer::OptionsParser::addMatchingOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunMatchesImporter().
indexOf()
template<class T > int cloudViewer::indexOf (T * arr, int n, const T & what)
Definition at line 160 of file StaticVector.h.
Referenced by cloudViewer::StaticVector< T >::indexOfSorted(), and cloudViewer::StaticVector< T >::push_back_distinct().
InterpolateNumber()
template<class T > T cloudViewer::InterpolateNumber (T start, T end, double interpolationFraction)
Definition at line 46 of file ViewInterpolate.cpp.
Referenced by cloudViewer::ViewInterpolate::interpolate().
IsClose()
template<typename scalar_t , typename T > CLOUDVIEWER_HOST_DEVICE bool cloudViewer::IsClose (const scalar_t & x, const T & y, const double rtol = 1e-4)
Definition at line 49 of file GeometryMacros.h.
References x, and y.
LessThanEpsilon() [1/2]
bool cloudViewer::LessThanEpsilon (double x) inline
Test a floating point number against our epsilon (a very small number).
Parameters
x The number to test
Returns
True if the number is less than epsilon.
Definition at line 30 of file CVMath.h.
References x, and ZERO_TOLERANCE_D.
LessThanEpsilon() [2/2]
bool cloudViewer::LessThanEpsilon (float x) inline
Test a floating point number against our epsilon (a very small number).
Parameters
x The number to test
Returns
True if the number is less than epsilon.
Definition at line 23 of file CVMath.h.
References x, and ZERO_TOLERANCE_F.
Referenced by ccPointPairRegistrationDlg::addAlignedPoint(), ccPointPairRegistrationDlg::addReferencePoint(), ccScalarFieldArithmeticsDlg::Apply(), ccCameraSensor::applyViewport(), ccCone::buildUp(), ccDisc::buildUp(), ccPlane::buildUp(), ccTorus::buildUp(), ccPolyline::ccPolyline(), cloudViewer::DistanceComputationTools::computeCloud2PlaneDistanceRMS(), cloudViewer::DistanceComputationTools::computeCloud2PlaneEquation(), cloudViewer::DistanceComputationTools::ComputeCloud2PlaneMaxDistance(), cloudViewer::DistanceComputationTools::ComputeCloud2PlaneRobustMax(), cloudViewer::Neighbourhood::computeLeastSquareBestFittingPlane(), ecvDisplayTools::ComputePerspectiveZoom(), vtk2cc::ConvertToPolyline(), ccCropTool::Crop(), define_CCMath(), cloudViewer::WeibullDistribution::FindGRoot(), ccCameraSensor::fromImageCoordToGlobalCoord(), ccGLMatrixTpl< T >::FromToRotation(), ccRasterizeTool::generateImage(), GetConeProfile(), cvContourTool::getOutput(), qAnimationDlg::onAutoStepsDurationToggled(), qAnimationDlg::onTotalTimeChanged(), CommandCrossSection::process(), cloudViewer::ICPRegistrationTools::Register(), cloudViewer::RegistrationTools::RegistrationProcedure(), cloudViewer::MeshSamplingTools::samplePointsOnMesh(), ccPointCloud::SegmentPlane(), ecvDisplayTools::SetFov(), ccPointCloud::setRGBColorByHeight(), ccRenderingTools::ShowDepthBuffer(), ccMesh::subdivide(), PdmsTools::PdmsObjects::Dish::surface(), ccPointCloud::Translate(), ccGenericMesh::trianglePicking(), cloudViewer::Neighbourhood::triangulateOnPlane(), and ecvDisplayTools::UpdateConstellationCenterAndZoom().
LessThanSquareEpsilon()
bool cloudViewer::LessThanSquareEpsilon (double x) inline
Test a (squared) floating point number against our epsilon (a very small number).
Parameters
x The (squared) number to test
Returns
True if the number is less than epsilon.
Definition at line 62 of file CVMath.h.
References x, and ZERO_SQUARED_TOLERANCE_D.
loadArrayFromFile() [1/2]
template<class T > StaticVector<T>* cloudViewer::loadArrayFromFile (const std::string & fileName, bool printfWarning = false)
Definition at line 468 of file StaticVector.h.
References a, CVLog::Error(), NULL, and CVLog::PrintDebug().
loadArrayFromFile() [2/2]
template<class T > bool cloudViewer::loadArrayFromFile (StaticVector< T > & out, const std::string & fileName, bool printfWarning = false)
Definition at line 555 of file StaticVector.h.
loadArrayFromFileIntoArray()
template<class T > void cloudViewer::loadArrayFromFileIntoArray (StaticVector< T > * a, const std::string & fileName, bool printfWarning = false)
Definition at line 628 of file StaticVector.h.
References a, CVLog::Error(), and CVLog::PrintDebug().
loadArrayOfArraysFromFile() [1/2]
template<class T > StaticVector<StaticVector<T>*>* cloudViewer::loadArrayOfArraysFromFile (const std::string & fileName)
Definition at line 221 of file StaticVector.h.
References a, CVLog::Error(), NULL, CVLog::PrintDebug(), cloudViewer::StaticVector< T >::reserve(), and cloudViewer::StaticVector< T >::resize_with().
loadArrayOfArraysFromFile() [2/2]
template<class T > void cloudViewer::loadArrayOfArraysFromFile (StaticVector< StaticVector< T >> & out_aa, const std::string & fileName)
Definition at line 268 of file StaticVector.h.
References a, CVLog::Error(), and CVLog::PrintDebug().
MergeDatabase()
int cloudViewer::MergeDatabase (const std::string & database_path1, const std::string & database_path2, const std::string & merged_database_path)
Definition at line 34 of file database.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunDatabaseMerger().
MergeModel()
int cloudViewer::MergeModel (const std::string & input_path1, const std::string & input_path2, const std::string & output_path, double max_reproj_error)
Definition at line 95 of file model.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunModelMerger().
MeshDelaunay()
int cloudViewer::MeshDelaunay (const std::string & input_path, const std::string & output_path, const std::string & input_type, const colmap::mvs::DelaunayMeshingOptions & delaunay_meshing_options)
Definition at line 15 of file mvs.cpp.
References cloudViewer::OptionsParser::addDelaunayMeshingOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunDelaunayMesher().
MeshPoisson()
int cloudViewer::MeshPoisson (const std::string & input_path, const std::string & output_path, const colmap::mvs::PoissonMeshingOptions & poisson_meshing_options)
Definition at line 51 of file mvs.cpp.
References cloudViewer::OptionsParser::addPoissonMeshingOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunPoissonMesher().
NormalMapper()
int cloudViewer::NormalMapper (const std::string & database_path, const std::string & image_path, const std::string & input_path, const std::string & output_path, const std::string & image_list_path, const colmap::IncrementalMapperOptions & incremental_mapper_options)
Definition at line 83 of file sfm.cpp.
References cloudViewer::OptionsParser::addMapperOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunMapper().
PrintCloudViewerVersion()
void cloudViewer::PrintCloudViewerVersion ()
Definition at line 14 of file CloudViewerConfig.cpp.
References CLOUDVIEWER_VERSION, and LogInfo.
Referenced by PrintHelp().
RadiansToDegrees() [1/3]
double cloudViewer::RadiansToDegrees (double radians) inline
Convert radians to degrees.
Parameters
radians Radians to convert
Returns
radians represented as degrees.
Definition at line 89 of file CVMath.h.
References M_PI.
RadiansToDegrees() [2/3]
float cloudViewer::RadiansToDegrees (float radians) inline
Convert radians to degrees.
Parameters
radians Radians to convert
Returns
radians represented as degrees.
Definition at line 80 of file CVMath.h.
References M_PI.
RadiansToDegrees() [3/3]
float cloudViewer::RadiansToDegrees (int radians) inline
Convert radians to degrees.
Parameters
radians Radians to convert
Returns
radians represented as degrees.
Definition at line 71 of file CVMath.h.
References M_PI.
Referenced by DistanceMapGenerationDlg::angularUnitChanged(), ccCameraSensor::applyViewport(), ccGBLSensor::computeAutoParameters(), ConvertAngleFromRad(), ccNormalVectors::ConvertNormalToDipAndDipDir(), ccNormalVectors::ConvertNormalToStrikeAndDip(), define_CCMath(), ccGriddedTools::DetectParameters(), DrawUnitArrow(), DrawUnitTorus(), MatrixDisplayDlg::fillDialogWith(), ccPropertiesTreeDelegate::fillWithCameraSensor(), ccPropertiesTreeDelegate::fillWithGBLSensor(), PCLDisplayTools::getCameraFovy(), cc2DLabel::getLabelInfo3(), ccCamSensorProjectionDlg::initWithCamSensor(), ccGBLSensorProjectionDlg::initWithGBLSensor(), IcmFilter::LoadCalibratedImages(), QVTKWidgetCustom::mouseMoveEvent(), StereogramWidget::mousePressEvent(), qHoughNormalsDialog::setParameters(), TransformInfo::setTransformation(), ecvDisplayTools::UpdateDisplayParameters(), PdmsTools::PdmsObjects::SCylinder::write(), PdmsTools::PdmsObjects::CTorus::write(), and PdmsTools::PdmsObjects::RTorus::write().
RectifyImage()
int cloudViewer::RectifyImage (const std::string & image_path, const std::string & input_path, const std::string & output_path, const std::string & stereo_pairs_list, double blank_pixels, double min_scale, double max_scale, int max_image_size)
Definition at line 49 of file image.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunImageRectifier().
RegisterImage()
int cloudViewer::RegisterImage (const std::string & database_path, const std::string & input_path, const std::string & output_path, const colmap::IncrementalMapperOptions & incremental_mapper_options)
Definition at line 71 of file image.cpp.
References cloudViewer::OptionsParser::addMapperOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunImageRegistrator().
RetrieveVocabTree()
int cloudViewer::RetrieveVocabTree (const std::string & database_path, const std::string & vocab_tree_path, const std::string & output_index_path, const std::string & query_image_list_path, const std::string & database_image_list_path, int max_num_images, int num_neighbors, int num_checks, int num_images_after_verification, int max_num_features)
Definition at line 35 of file vocab_tree.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunVocabTreeRetriever().
RigBundleAdjust()
int cloudViewer::RigBundleAdjust (const std::string & input_path, const std::string & output_path, const std::string & rig_config_path, bool estimate_rig_relative_poses, bool refine_relative_poses, const colmap::BundleAdjustmentOptions & bundle_adjustment_options)
Definition at line 159 of file sfm.cpp.
References cloudViewer::OptionsParser::addBundleAdjustmentOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunRigBundleAdjuster().
saveArrayOfArraysToFile() [1/2]
template<class T > void cloudViewer::saveArrayOfArraysToFile (const std::string fileName, StaticVector< StaticVector< T >> & aa)
Definition at line 198 of file StaticVector.h.
References a, and CVLog::PrintDebug().
saveArrayOfArraysToFile() [2/2]
template<class T > void cloudViewer::saveArrayOfArraysToFile (std::string fileName, StaticVector< StaticVector< T > * > * aa)
Definition at line 175 of file StaticVector.h.
References a, NULL, and CVLog::PrintDebug().
saveArrayToFile() [1/2]
template<class T > void cloudViewer::saveArrayToFile (const std::string & fileName, const StaticVector< T > & a, bool docompress = true)
Definition at line 312 of file StaticVector.h.
References a.
saveArrayToFile() [2/2]
template<class T > void cloudViewer::saveArrayToFile (const std::string & fileName, const StaticVector< T > * a, bool docompress = true)
Definition at line 319 of file StaticVector.h.
References a, cloudViewer::utility::filesystem::DirectoryExists(), CVLog::Error(), cloudViewer::utility::filesystem::GetFileParentDirectory(), cloudViewer::utility::filesystem::MakeDirectoryHierarchy(), CVLog::PrintDebug(), and CVLog::Warning().
SequentialMatch()
int cloudViewer::SequentialMatch (const std::string & database_path, const colmap::SiftMatchingOptions & sift_matching_options, const colmap::SequentialMatchingOptions & sequential_matching_options)
Definition at line 82 of file feature.cpp.
References cloudViewer::OptionsParser::addSequentialMatchingOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunSequentialMatcher().
sizeOfStaticVector() [1/2]
template<class T > int cloudViewer::sizeOfStaticVector (const StaticVector< T > & a)
Definition at line 154 of file StaticVector.h.
References a.
sizeOfStaticVector() [2/2]
template<class T > int cloudViewer::sizeOfStaticVector (const StaticVector< T > * a)
Definition at line 148 of file StaticVector.h.
References a.
SpatialMatch()
int cloudViewer::SpatialMatch (const std::string & database_path, const colmap::SiftMatchingOptions & sift_matching_options, const colmap::SpatialMatchingOptions & spatial_matching_options)
Definition at line 95 of file feature.cpp.
References cloudViewer::OptionsParser::addSpatialMatchingOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunSpatialMatcher().
SplitModel()
int cloudViewer::SplitModel (const std::string & input_path, const std::string & output_path, const std::string & split_type, const std::string & split_params, const std::string & gps_transform_path, std::size_t min_reg_images, std::size_t min_num_points, double overlap_ratio, double min_area_ratio, int num_threads)
Definition at line 127 of file model.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunModelSplitter().
Square()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE scalar_t cloudViewer::Square (const scalar_t & x)
Definition at line 56 of file GeometryMacros.h.
References x.
StereoFuse()
int cloudViewer::StereoFuse (const std::string & workspace_path, const std::string & output_path, const std::string & bbox_path, const std::string & stereo_input_type, const std::string & output_type, const std::string & workspace_format, const std::string & pmvs_option_name, const colmap::mvs::StereoFusionOptions & stereo_fusion_options)
Definition at line 64 of file mvs.cpp.
References cloudViewer::OptionsParser::addStereoFusionOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunStereoFuser().
StereoPatchMatch()
int cloudViewer::StereoPatchMatch (const std::string & workspace_path, const std::string & config_path, const std::string & workspace_format, const std::string & pmvs_option_name, const colmap::mvs::PatchMatchOptions & patch_match_options)
Definition at line 32 of file mvs.cpp.
References cloudViewer::OptionsParser::addPatchMatchStereoOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunPatchMatchStereo().
TransformModel()
int cloudViewer::TransformModel (const std::string & input_path, const std::string & output_path, const std::string & transform_path, bool is_inverse)
Definition at line 154 of file model.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunModelTransformer().
TransitiveMatch()
int cloudViewer::TransitiveMatch (const std::string & database_path, const colmap::SiftMatchingOptions & sift_matching_options, const colmap::TransitiveMatchingOptions & transitive_matching_options)
Definition at line 108 of file feature.cpp.
References cloudViewer::OptionsParser::addTransitiveMatchingOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunTransitiveMatcher().
TriangulatePoints()
int cloudViewer::TriangulatePoints (const std::string & database_path, const std::string & image_path, const std::string & input_path, const std::string & output_path, bool clear_points, const colmap::IncrementalMapperOptions & incremental_mapper_options)
Definition at line 139 of file sfm.cpp.
References cloudViewer::OptionsParser::addMapperOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunPointTriangulator().
UndistortImage()
int cloudViewer::UndistortImage (const std::string & image_path, const std::string & input_path, const std::string & output_path, const std::string & image_list_path, const std::string & output_type, const std::string & copy_policy, int num_patch_match_src_images, double blank_pixels, double min_scale, double max_scale, int max_image_size, double roi_min_x, double roi_min_y, double roi_max_x, double roi_max_y)
Definition at line 86 of file image.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunImageUndistorter().
UndistortImageStandalone()
int cloudViewer::UndistortImageStandalone (const std::string & image_path, const std::string & input_file, const std::string & output_path, double blank_pixels, double min_scale, double max_scale, int max_image_size, double roi_min_x, double roi_min_y, double roi_max_x, double roi_max_y)
Definition at line 126 of file image.cpp.
References cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunImageUndistorterStandalone().
VocabTreeMatch()
int cloudViewer::VocabTreeMatch (const std::string & database_path, const colmap::SiftMatchingOptions & sift_matching_options, const colmap::VocabTreeMatchingOptions & vocab_tree_matching_options)
Definition at line 121 of file feature.cpp.
References cloudViewer::OptionsParser::addVocabTreeMatchingOptions(), cloudViewer::OptionsParser::getArgc(), cloudViewer::OptionsParser::getArgv(), cloudViewer::OptionsParser::parseOptions(), cloudViewer::OptionsParser::registerOption(), and colmap::RunVocabTreeMatcher().
Variable Documentation
c_erfRelativeError
const double cloudViewer::c_erfRelativeError = 1e-12 static
Relative error for Error Function computation.
You can adjust it to trade off between accuracy and speed but don't ask for more than 15 figures (assuming usual 52 bit mantissa in a double). Example: 1E-12 <--> calculate 12 significant figures
Definition at line 21 of file ErrorFunction.h.
Referenced by define_ErrorFunction(), and cloudViewer::ErrorFunction::erfc().
c_FastMarchingNeighbourPosShift
const int cloudViewer::c_FastMarchingNeighbourPosShift[]
Initial value:
= {
        0, -1, 0, 1, 0, 0, 0, 1, 0, -1, 0, 0, 0, 0, -1, 0, 0, 1,
        -1, -1, -1, -1, -1, 0, -1, -1, 1, -1, 0, -1, -1, 0, 1, -1, 1, -1, -1, 1,
        0, -1, 1, 1, 0, -1, -1, 0, -1, 1, 0, 1, -1, 0, 1, 1, 1, -1, -1, 1, -1,
        0, 1, -1, 1, 1, 0, -1, 1, 0, 1, 1, 1, -1, 1, 1, 0, 1, 1, 1}
Grid neighboring cells positions.
Definition at line 29 of file FastMarching.h.
Referenced by cloudViewer::FastMarching::computeT(), define_FastMarching(), and cloudViewer::FastMarching::initOther().
CLOUDVIEWER_GIT_COMMIT_DATE
const std::string cloudViewer::CLOUDVIEWER_GIT_COMMIT_DATE = "2026-01-29" static
Definition at line 28 of file CloudViewerConfig.h.
Referenced by GetBuildInfo().
CLOUDVIEWER_GIT_COMMIT_ID
const std::string cloudViewer::CLOUDVIEWER_GIT_COMMIT_ID = "f89b7a10e" static
Definition at line 27 of file CloudViewerConfig.h.
Referenced by GetBuildInfo().
CLOUDVIEWER_VERSION_STR
const std::string cloudViewer::CLOUDVIEWER_VERSION_STR = "3.9.4" static
Definition at line 26 of file CloudViewerConfig.h.