ACloudViewer: cloudViewer::pybind_utils Namespace Reference
cloudViewer::pybind_utils Namespace Reference
Functions
core::Dtype ArrayFormatToDtype (const std::string &format, size_t byte_size)
std::string DtypeToArrayFormat (const core::Dtype &dtype)
Function Documentation
ArrayFormatToDtype()
core::Dtype cloudViewer::pybind_utils::ArrayFormatToDtype (const std::string & format, size_t byte_size)
Definition at line 19 of file pybind_utils.cpp.
References cloudViewer::core::Bool, cloudViewer::core::Float32, cloudViewer::core::Float64, format, cloudViewer::core::Int16, cloudViewer::core::Int32, cloudViewer::core::Int64, cloudViewer::core::Int8, LogError, cloudViewer::core::UInt16, cloudViewer::core::UInt32, cloudViewer::core::UInt64, cloudViewer::core::UInt8, and cloudViewer::core::Undefined.
Referenced by cloudViewer::core::PyArrayToTensor().
DtypeToArrayFormat()
std::string cloudViewer::pybind_utils::DtypeToArrayFormat (const core::Dtype & dtype)
Definition at line 62 of file pybind_utils.cpp.
References cloudViewer::core::Bool, cloudViewer::core::Float32, cloudViewer::core::Float64, format, cloudViewer::core::Int16, cloudViewer::core::Int32, cloudViewer::core::Int64, cloudViewer::core::Int8, LogError, cloudViewer::core::UInt16, cloudViewer::core::UInt32, cloudViewer::core::UInt64, and cloudViewer::core::UInt8.
Referenced by cloudViewer::t::geometry::pybind_image(), and cloudViewer::core::TensorToPyArray().