ACloudViewer: e57::Utilities Namespace Reference
e57::Utilities Namespace Reference
Functions
E57_DLL void getVersions (int &astmMajor, int &astmMinor, std::string &libraryId)
Get the version of ASTM E57 standard that the API implementation supports, and library id string.
E57_DLL std::string errorCodeToString (ErrorCode ecode)
Get short string description of an E57 ErrorCode.
Function Documentation
errorCodeToString()
std::string e57::Utilities::errorCodeToString (ErrorCode ecode)
Get short string description of an E57 ErrorCode.
Parameters
[in] ecode The numeric errorCode from an E57Exception.
The errorCode is translated into a one-line English string.
Returns
English std::string describing error.
Exceptions
No E57Exceptions.
See also
E57Exception::errorCode
Definition at line 291 of file E57Exception.cpp.
References e57::E57_ERROR_ALREADY_HAS_PARENT, e57::E57_ERROR_BAD_API_ARGUMENT, e57::E57_ERROR_BAD_BUFFER, e57::E57_ERROR_BAD_CHECKSUM, e57::E57_ERROR_BAD_CODECS, e57::E57_ERROR_BAD_CONFIGURATION, e57::E57_ERROR_BAD_CV_HEADER, e57::E57_ERROR_BAD_CV_PACKET, e57::E57_ERROR_BAD_FILE_LENGTH, e57::E57_ERROR_BAD_FILE_SIGNATURE, e57::E57_ERROR_BAD_NODE_DOWNCAST, e57::E57_ERROR_BAD_PATH_NAME, e57::E57_ERROR_BAD_PROTOTYPE, e57::E57_ERROR_BAD_XML_FORMAT, e57::E57_ERROR_BUFFER_DUPLICATE_PATHNAME, e57::E57_ERROR_BUFFER_SIZE_MISMATCH, e57::E57_ERROR_BUFFERS_NOT_COMPATIBLE, e57::E57_ERROR_CHILD_INDEX_OUT_OF_BOUNDS, e57::E57_ERROR_CLOSE_FAILED, e57::E57_ERROR_CONVERSION_REQUIRED, e57::E57_ERROR_DIFFERENT_DEST_IMAGEFILE, e57::E57_ERROR_DUPLICATE_NAMESPACE_PREFIX, e57::E57_ERROR_DUPLICATE_NAMESPACE_URI, e57::E57_ERROR_EXPECTING_NUMERIC, e57::E57_ERROR_EXPECTING_USTRING, e57::E57_ERROR_FILE_IS_READ_ONLY, e57::E57_ERROR_HOMOGENEOUS_VIOLATION, e57::E57_ERROR_IMAGEFILE_NOT_OPEN, e57::E57_ERROR_INTERNAL, e57::E57_ERROR_INVARIANCE_VIOLATION, e57::E57_ERROR_LSEEK_FAILED, e57::E57_ERROR_NO_BUFFER_FOR_ELEMENT, e57::E57_ERROR_NODE_UNATTACHED, e57::E57_ERROR_NOT_IMPLEMENTED, e57::E57_ERROR_OPEN_FAILED, e57::E57_ERROR_PATH_UNDEFINED, e57::E57_ERROR_READ_FAILED, e57::E57_ERROR_READER_NOT_OPEN, e57::E57_ERROR_REAL64_TOO_LARGE, e57::E57_ERROR_SCALED_VALUE_NOT_REPRESENTABLE, e57::E57_ERROR_SET_TWICE, e57::E57_ERROR_TOO_MANY_READERS, e57::E57_ERROR_TOO_MANY_WRITERS, e57::E57_ERROR_UNKNOWN_FILE_VERSION, e57::E57_ERROR_VALUE_NOT_REPRESENTABLE, e57::E57_ERROR_VALUE_OUT_OF_BOUNDS, e57::E57_ERROR_WRITE_FAILED, e57::E57_ERROR_WRITER_NOT_OPEN, e57::E57_ERROR_XML_PARSER, e57::E57_ERROR_XML_PARSER_INIT, e57::E57_SUCCESS, and patch::to_string().
Referenced by E57Filter::loadFile(), e57::E57Exception::report(), and E57Filter::saveToFile().
getVersions()
void e57::Utilities::getVersions (int & astmMajor, int & astmMinor, std::string & libraryId)
Get the version of ASTM E57 standard that the API implementation supports, and library id string.
Parameters
[out] astmMajor The major version number of the ASTM E57 standard supported.
[out] astmMinor The minor version number of the ASTM E57 standard supported.
[out] libraryId A string identifying the implementation of the API.
Since the E57 implementation may be dynamically linked underneath the API, the version string for the implementation and the ASTM version that it supports can't be determined at compile-time. This function returns these identifiers from the underlying implementation.
Exceptions
No E57Exceptions.
REVISION_ID should be passed from compiler command line
Definition at line 269 of file E57Exception.cpp.
References e57::E57_FORMAT_MAJOR, and e57::E57_FORMAT_MINOR.
Referenced by E57Filter::saveToFile(), and e57::WriterImpl::WriterImpl().