ACloudViewer: cloudViewer::core::tensor_check Namespace Reference
cloudViewer::core::tensor_check Namespace Reference
Functions
void AssertTensorDtype_ (const char *file, int line, const char *function, const Tensor &tensor, const Dtype &dtype)
void AssertTensorDtypes_ (const char *file, int line, const char *function, const Tensor &tensor, const std::vector< Dtype > &dtypes)
void AssertTensorDevice_ (const char *file, int line, const char *function, const Tensor &tensor, const Device &device)
void AssertTensorShape_ (const char *file, int line, const char *function, const Tensor &tensor, const DynamicSizeVector &shape)
Function Documentation
AssertTensorDevice_()
void cloudViewer::core::tensor_check::AssertTensorDevice_ (const char * file, int line, const char * function, const Tensor & tensor, const Device & device)
Definition at line 58 of file TensorCheck.cpp.
References format, cloudViewer::core::Tensor::GetDevice(), cloudViewer::utility::Logger::LogError_(), and cloudViewer::core::Device::ToString().
AssertTensorDtype_()
void cloudViewer::core::tensor_check::AssertTensorDtype_ (const char * file, int line, const char * function, const Tensor & tensor, const Dtype & dtype)
Definition at line 23 of file TensorCheck.cpp.
References format, cloudViewer::core::Tensor::GetDtype(), cloudViewer::utility::Logger::LogError_(), and cloudViewer::core::Dtype::ToString().
AssertTensorDtypes_()
void cloudViewer::core::tensor_check::AssertTensorDtypes_ (const char * file, int line, const char * function, const Tensor & tensor, const std::vector< Dtype > & dtypes)
Definition at line 37 of file TensorCheck.cpp.
References format, cloudViewer::core::Tensor::GetDtype(), cloudViewer::utility::JoinStrings(), cloudViewer::utility::Logger::LogError_(), and cloudViewer::core::Dtype::ToString().
AssertTensorShape_()
void cloudViewer::core::tensor_check::AssertTensorShape_ (const char * file, int line, const char * function, const Tensor & tensor, const DynamicSizeVector & shape)
Definition at line 72 of file TensorCheck.cpp.
References format, cloudViewer::core::Tensor::GetShape(), cloudViewer::core::SizeVector::IsCompatible(), cloudViewer::core::DynamicSizeVector::IsDynamic(), cloudViewer::utility::Logger::LogError_(), cloudViewer::core::DynamicSizeVector::ToSizeVector(), cloudViewer::core::DynamicSizeVector::ToString(), and cloudViewer::core::SizeVector::ToString().