ACloudViewer: cloudViewer::visualization::app Namespace Reference
cloudViewer::visualization::app Namespace Reference
Functions
void RunViewer (int argc, const char *argv[])
Variables
static const std::string usage = "usage: ./CloudViewer [meshfile|pointcloud]"
static const int width = 1280
static const int height = 960
Function Documentation
RunViewer()
void cloudViewer::visualization::app::RunViewer (int argc, const char * argv[])
Runs CloudViewer Viewer. This function is called when the standalone viewer app is run or when the draw command is called from the command line interface.
Parameters
argc (argument count) is the number of arguments in argv .
argv (argument vector) is the array of arguments stored as character arrays. It contains the path of the calling program (which should be in the same directory as the gui resources folder) as the first argument. The optional second argument is the path of the geometry file to be visualized
Definition at line 26 of file Viewer.cpp.
References cloudViewer::visualization::gui::Application::AddWindow(), cloudViewer::utility::Logger::GetInstance(), cloudViewer::visualization::gui::Application::GetInstance(), cloudViewer::utility::Logger::GetPrintFunction(), height, LogWarning, cloudViewer::t::geometry::path, cloudViewer::utility::Logger::ResetPrintFunction(), cloudViewer::utility::Logger::SetPrintFunction(), usage, and width.
Referenced by main().
Variable Documentation
height
const int cloudViewer::visualization::app::height = 960 static
Definition at line 24 of file Viewer.cpp.
Referenced by RunViewer().
usage
const std::string cloudViewer::visualization::app::usage = "usage: ./CloudViewer [meshfile|pointcloud]" static
Definition at line 22 of file Viewer.cpp.
Referenced by RunViewer().
width
const int cloudViewer::visualization::app::width = 1280 static
Definition at line 23 of file Viewer.cpp.
Referenced by RunViewer().