ACloudViewer: cloudViewer::pipelines::odometry Namespace Reference
cloudViewer::pipelines::odometry Namespace Reference
Classes
class OdometryOption
class RGBDOdometryJacobian
Base class that computes Jacobian from two RGB-D images.
class RGBDOdometryJacobianFromColorTerm
Class to compute Jacobian using color term.
class RGBDOdometryJacobianFromHybridTerm
Class to compute Jacobian using hybrid term.
Typedefs
typedef std::vector< Eigen::Vector4i, utility::Vector4i_allocator > CorrespondenceSetPixelWise
Functions
static std::tuple< geometry::Image, geometry::Image > InitializeCorrespondenceMap (int width, int height)
static void AddElementToCorrespondenceMap (geometry::Image &correspondence_map, geometry::Image &depth_buffer, int u_s, int v_s, int u_t, int v_t, float transformed_d_t)
static void MergeCorrespondenceMaps (geometry::Image &correspondence_map, geometry::Image &depth_buffer, geometry::Image &correspondence_map_part, geometry::Image &depth_buffer_part)
static int CountCorrespondence (const geometry::Image &correspondence_map)
static CorrespondenceSetPixelWise ComputeCorrespondence (const Eigen::Matrix3d intrinsic_matrix, const Eigen::Matrix4d &extrinsic, const geometry::Image &depth_s, const geometry::Image &depth_t, const OdometryOption &option)
static std::shared_ptr< geometry::Image > ConvertDepthImageToXYZImage (const geometry::Image &depth, const Eigen::Matrix3d &intrinsic_matrix)
static std::vector< Eigen::Matrix3d > CreateCameraMatrixPyramid (const camera::PinholeCameraIntrinsic &pinhole_camera_intrinsic, int levels)
static Eigen::Matrix6d CreateInformationMatrix (const Eigen::Matrix4d &extrinsic, const camera::PinholeCameraIntrinsic &pinhole_camera_intrinsic, const geometry::Image &depth_s, const geometry::Image &depth_t, const OdometryOption &option)
static void NormalizeIntensity (geometry::Image &image_s, geometry::Image &image_t, const CorrespondenceSetPixelWise &correspondence)
static std::shared_ptr< geometry::RGBDImage > PackRGBDImage (const geometry::Image &color, const geometry::Image &depth)
static std::shared_ptr< geometry::Image > PreprocessDepth (const geometry::Image &depth_orig, const OdometryOption &option)
static bool CheckImagePair (const geometry::Image &image_s, const geometry::Image &image_t)
static bool IsColorImageRGB (const geometry::Image &image)
static bool CheckRGBDImagePair (const geometry::RGBDImage &source, const geometry::RGBDImage &target)
static std::tuple< std::shared_ptr< geometry::RGBDImage >, std::shared_ptr< geometry::RGBDImage > > InitializeRGBDOdometry (const geometry::RGBDImage &source, const geometry::RGBDImage &target, const camera::PinholeCameraIntrinsic &pinhole_camera_intrinsic, const Eigen::Matrix4d &odo_init, const OdometryOption &option)
static std::tuple< bool, Eigen::Matrix4d > DoSingleIteration (int iter, int level, const geometry::RGBDImage &source, const geometry::RGBDImage &target, const geometry::Image &source_xyz, const geometry::RGBDImage &target_dx, const geometry::RGBDImage &target_dy, const Eigen::Matrix3d intrinsic, const Eigen::Matrix4d &extrinsic_initial, const RGBDOdometryJacobian &jacobian_method, const OdometryOption &option)
static std::tuple< bool, Eigen::Matrix4d > ComputeMultiscale (const geometry::RGBDImage &source, const geometry::RGBDImage &target, const camera::PinholeCameraIntrinsic &pinhole_camera_intrinsic, const Eigen::Matrix4d &extrinsic_initial, const RGBDOdometryJacobian &jacobian_method, const OdometryOption &option)
std::tuple< bool, Eigen::Matrix4d, Eigen::Matrix6d > ComputeRGBDOdometry (const geometry::RGBDImage &source, const geometry::RGBDImage &target, const camera::PinholeCameraIntrinsic &pinhole_camera_intrinsic=camera::PinholeCameraIntrinsic(), const Eigen::Matrix4d &odo_init=Eigen::Matrix4d::Identity(), const RGBDOdometryJacobian &jacobian_method=RGBDOdometryJacobianFromHybridTerm(), const OdometryOption &option=OdometryOption())
Function to estimate 6D rigid motion from two RGBD image pairs.
Typedef Documentation
CorrespondenceSetPixelWise
typedef std::vector<Eigen::Vector4i, utility::Vector4i_allocator> cloudViewer::pipelines::odometry::CorrespondenceSetPixelWise
Definition at line 33 of file RGBDOdometryJacobian.h.
Function Documentation
AddElementToCorrespondenceMap()
static void cloudViewer::pipelines::odometry::AddElementToCorrespondenceMap (geometry::Image & correspondence_map, geometry::Image & depth_buffer, int u_s, int v_s, int u_t, int v_t, float transformed_d_t) inline static
Definition at line 40 of file Odometry.cpp.
References cloudViewer::geometry::Image::PointerAt().
Referenced by ComputeCorrespondence(), and MergeCorrespondenceMaps().
CheckImagePair()
static bool cloudViewer::pipelines::odometry::CheckImagePair (const geometry::Image & image_s, const geometry::Image & image_t) inline static
Definition at line 315 of file Odometry.cpp.
References cloudViewer::geometry::Image::height_, and cloudViewer::geometry::Image::width_.
Referenced by CheckRGBDImagePair().
CheckRGBDImagePair()
static bool cloudViewer::pipelines::odometry::CheckRGBDImagePair (const geometry::RGBDImage & source, const geometry::RGBDImage & target) inline static
Definition at line 325 of file Odometry.cpp.
References cloudViewer::geometry::Image::bytes_per_channel_, CheckImagePair(), cloudViewer::geometry::RGBDImage::color_, cloudViewer::geometry::RGBDImage::depth_, IsColorImageRGB(), and cloudViewer::geometry::Image::num_of_channels_.
Referenced by ComputeRGBDOdometry().
ComputeCorrespondence()
static CorrespondenceSetPixelWise cloudViewer::pipelines::odometry::ComputeCorrespondence (const Eigen::Matrix3d intrinsic_matrix, const Eigen::Matrix4d & extrinsic, const geometry::Image & depth_s, const geometry::Image & depth_t, const OdometryOption & option) static
Definition at line 100 of file Odometry.cpp.
References abs(), AddElementToCorrespondenceMap(), CountCorrespondence(), cloudViewer::geometry::Image::height_, InitializeCorrespondenceMap(), cloudViewer::pipelines::odometry::OdometryOption::max_depth_diff_, MergeCorrespondenceMaps(), cloudViewer::geometry::Image::PointerAt(), and cloudViewer::geometry::Image::width_.
Referenced by CreateInformationMatrix(), DoSingleIteration(), and InitializeRGBDOdometry().
ComputeMultiscale()
static std::tuple<bool, Eigen::Matrix4d> cloudViewer::pipelines::odometry::ComputeMultiscale (const geometry::RGBDImage & source, const geometry::RGBDImage & target, const camera::PinholeCameraIntrinsic & pinhole_camera_intrinsic, const Eigen::Matrix4d & extrinsic_initial, const RGBDOdometryJacobian & jacobian_method, const OdometryOption & option) static
Definition at line 443 of file Odometry.cpp.
References ConvertDepthImageToXYZImage(), CreateCameraMatrixPyramid(), cloudViewer::geometry::RGBDImage::CreatePyramid(), DoSingleIteration(), cloudViewer::geometry::RGBDImage::FilterPyramid(), cloudViewer::pipelines::odometry::OdometryOption::iteration_number_per_pyramid_level_, LogWarning, PackRGBDImage(), cloudViewer::geometry::Image::Sobel3Dx, and cloudViewer::geometry::Image::Sobel3Dy.
Referenced by ComputeRGBDOdometry().
ComputeRGBDOdometry()
std::tuple< bool, Eigen::Matrix4d, Eigen::Matrix6d > cloudViewer::pipelines::odometry::ComputeRGBDOdometry (const geometry::RGBDImage & source, const geometry::RGBDImage & target, const camera::PinholeCameraIntrinsic & pinhole_camera_intrinsic = camera::PinholeCameraIntrinsic(), const Eigen::Matrix4d & odo_init = Eigen::Matrix4d::Identity(), const RGBDOdometryJacobian & jacobian_method = RGBDOdometryJacobianFromHybridTerm(), const OdometryOption & option = OdometryOption())
Function to estimate 6D rigid motion from two RGBD image pairs.
Parameters
source Source RGBD image.
target Target RGBD image.
pinhole_camera_intrinsic Camera intrinsic parameters.
odo_init Initial 4x4 motion matrix estimation.
jacobin_method The odometry Jacobian method to use.
option Odometry hyper parameteres.
Returns
is_success, 4x4 motion matrix, 6x6 information matrix.
Definition at line 501 of file Odometry.cpp.
References CheckRGBDImagePair(), ComputeMultiscale(), CreateInformationMatrix(), InitializeRGBDOdometry(), and LogWarning.
ConvertDepthImageToXYZImage()
static std::shared_ptr<geometry::Image> cloudViewer::pipelines::odometry::ConvertDepthImageToXYZImage (const geometry::Image & depth, const Eigen::Matrix3d & intrinsic_matrix) static
Definition at line 175 of file Odometry.cpp.
References cloudViewer::geometry::Image::bytes_per_channel_, cloudViewer::geometry::Image::height_, LogError, cloudViewer::geometry::Image::num_of_channels_, cloudViewer::geometry::Image::PointerAt(), and cloudViewer::geometry::Image::width_.
Referenced by ComputeMultiscale(), and CreateInformationMatrix().
CountCorrespondence()
static int cloudViewer::pipelines::odometry::CountCorrespondence (const geometry::Image & correspondence_map) static
Definition at line 86 of file Odometry.cpp.
References cloudViewer::geometry::Image::height_, cloudViewer::geometry::Image::PointerAt(), and cloudViewer::geometry::Image::width_.
Referenced by ComputeCorrespondence().
CreateCameraMatrixPyramid()
static std::vector<Eigen::Matrix3d> cloudViewer::pipelines::odometry::CreateCameraMatrixPyramid (const camera::PinholeCameraIntrinsic & pinhole_camera_intrinsic, int levels) static
Definition at line 202 of file Odometry.cpp.
References cloudViewer::camera::PinholeCameraIntrinsic::intrinsic_matrix_.
Referenced by ComputeMultiscale().
CreateInformationMatrix()
static Eigen::Matrix6d cloudViewer::pipelines::odometry::CreateInformationMatrix (const Eigen::Matrix4d & extrinsic, const camera::PinholeCameraIntrinsic & pinhole_camera_intrinsic, const geometry::Image & depth_s, const geometry::Image & depth_t, const OdometryOption & option) static
Definition at line 219 of file Odometry.cpp.
References ComputeCorrespondence(), ConvertDepthImageToXYZImage(), and cloudViewer::camera::PinholeCameraIntrinsic::intrinsic_matrix_.
Referenced by ComputeRGBDOdometry().
DoSingleIteration()
static std::tuple<bool, Eigen::Matrix4d> cloudViewer::pipelines::odometry::DoSingleIteration (int iter, int level, const geometry::RGBDImage & source, const geometry::RGBDImage & target, const geometry::Image & source_xyz, const geometry::RGBDImage & target_dx, const geometry::RGBDImage & target_dy, const Eigen::Matrix3d intrinsic, const Eigen::Matrix4d & extrinsic_initial, const RGBDOdometryJacobian & jacobian_method, const OdometryOption & option) static
Definition at line 398 of file Odometry.cpp.
References ComputeCorrespondence(), cloudViewer::pipelines::odometry::RGBDOdometryJacobian::ComputeJacobianAndResidual(), cloudViewer::geometry::RGBDImage::depth_, LogDebug, LogWarning, and cloudViewer::utility::SolveJacobianSystemAndObtainExtrinsicMatrix().
Referenced by ComputeMultiscale().
InitializeCorrespondenceMap()
static std::tuple<geometry::Image, geometry::Image> cloudViewer::pipelines::odometry::InitializeCorrespondenceMap (int width, int height) static
Definition at line 23 of file Odometry.cpp.
References height, cloudViewer::geometry::Image::height_, cloudViewer::geometry::Image::PointerAt(), cloudViewer::geometry::Image::Prepare(), width, and cloudViewer::geometry::Image::width_.
Referenced by ComputeCorrespondence().
InitializeRGBDOdometry()
static std::tuple<std::shared_ptr<geometry::RGBDImage>, std::shared_ptr<geometry::RGBDImage> > cloudViewer::pipelines::odometry::InitializeRGBDOdometry (const geometry::RGBDImage & source, const geometry::RGBDImage & target, const camera::PinholeCameraIntrinsic & pinhole_camera_intrinsic, const Eigen::Matrix4d & odo_init, const OdometryOption & option) static
Definition at line 362 of file Odometry.cpp.
References cloudViewer::geometry::RGBDImage::color_, ComputeCorrespondence(), cloudViewer::geometry::Image::CreateFloatImage(), cloudViewer::geometry::RGBDImage::depth_, cloudViewer::geometry::Image::Gaussian3, cloudViewer::camera::PinholeCameraIntrinsic::intrinsic_matrix_, IsColorImageRGB(), NormalizeIntensity(), PackRGBDImage(), and PreprocessDepth().
Referenced by ComputeRGBDOdometry().
IsColorImageRGB()
static bool cloudViewer::pipelines::odometry::IsColorImageRGB (const geometry::Image & image) inline static
Definition at line 321 of file Odometry.cpp.
References image.
Referenced by CheckRGBDImagePair(), and InitializeRGBDOdometry().
MergeCorrespondenceMaps()
static void cloudViewer::pipelines::odometry::MergeCorrespondenceMaps (geometry::Image & correspondence_map, geometry::Image & depth_buffer, geometry::Image & correspondence_map_part, geometry::Image & depth_buffer_part) static
Definition at line 67 of file Odometry.cpp.
References AddElementToCorrespondenceMap(), cloudViewer::geometry::Image::height_, cloudViewer::geometry::Image::PointerAt(), and cloudViewer::geometry::Image::width_.
Referenced by ComputeCorrespondence().
NormalizeIntensity()
static void cloudViewer::pipelines::odometry::NormalizeIntensity (geometry::Image & image_s, geometry::Image & image_t, const CorrespondenceSetPixelWise & correspondence) static
Definition at line 269 of file Odometry.cpp.
References cloudViewer::geometry::Image::height_, cloudViewer::geometry::Image::LinearTransform(), LogError, cloudViewer::geometry::Image::PointerAt(), and cloudViewer::geometry::Image::width_.
Referenced by InitializeRGBDOdometry().
PackRGBDImage()
static std::shared_ptr<geometry::RGBDImage> cloudViewer::pipelines::odometry::PackRGBDImage (const geometry::Image & color, const geometry::Image & depth) inline static
Definition at line 294 of file Odometry.cpp.
References color.
Referenced by ComputeMultiscale(), and InitializeRGBDOdometry().
PreprocessDepth()
static std::shared_ptr<geometry::Image> cloudViewer::pipelines::odometry::PreprocessDepth (const geometry::Image & depth_orig, const OdometryOption & option) static
Definition at line 300 of file Odometry.cpp.
References cloudViewer::pipelines::odometry::OdometryOption::max_depth_, and cloudViewer::geometry::Image::PointerAt().
Referenced by InitializeRGBDOdometry().