ACloudViewer: cloudViewer::t::geometry::kernel::transform Namespace Reference
cloudViewer::t::geometry::kernel::transform Namespace Reference
Functions
void TransformPoints (const core::Tensor &transformation, core::Tensor &points)
void TransformNormals (const core::Tensor &transformation, core::Tensor &normals)
void RotatePoints (const core::Tensor &R, core::Tensor &points, const core::Tensor &center)
void RotateNormals (const core::Tensor &R, core::Tensor &normals)
void TransformPointsCPU (const core::Tensor &transformation, core::Tensor &points)
void TransformNormalsCPU (const core::Tensor &transformation, core::Tensor &normals)
void RotatePointsCPU (const core::Tensor &R, core::Tensor &points, const core::Tensor &center)
void RotateNormalsCPU (const core::Tensor &R, core::Tensor &normals)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE void TransformPointsKernel (const scalar_t *transformation_ptr, scalar_t *points_ptr)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE void TransformNormalsKernel (const scalar_t *transformation_ptr, scalar_t *normals_ptr)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE void RotatePointsKernel (const scalar_t *R_ptr, scalar_t *points_ptr, const scalar_t *center)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE void RotateNormalsKernel (const scalar_t *R_ptr, scalar_t *normals_ptr)
Function Documentation
RotateNormals()
void cloudViewer::t::geometry::kernel::transform::RotateNormals (const core::Tensor & R, core::Tensor & normals)
Definition at line 88 of file Transform.cpp.
References AssertTensorShape, cloudViewer::core::Tensor::Contiguous(), CUDA_CALL, LogError, normals, cloudViewer::utility::nullopt, RotateNormalsCPU(), and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::t::geometry::PointCloud::Rotate(), and cloudViewer::t::geometry::TriangleMesh::Rotate().
RotateNormalsCPU()
void cloudViewer::t::geometry::kernel::transform::RotateNormalsCPU (const core::Tensor & R, core::Tensor & normals)
Definition at line 155 of file TransformImpl.h.
References DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, and normals.
Referenced by RotateNormals().
RotateNormalsKernel()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::t::geometry::kernel::transform::RotateNormalsKernel (const scalar_t * R_ptr, scalar_t * normals_ptr)
Definition at line 76 of file TransformImpl.h.
RotatePoints()
void cloudViewer::t::geometry::kernel::transform::RotatePoints (const core::Tensor & R, core::Tensor & points, const core::Tensor & center)
Definition at line 63 of file Transform.cpp.
References AssertTensorShape, cloudViewer::core::Tensor::Contiguous(), CUDA_CALL, LogError, cloudViewer::utility::nullopt, points, RotatePointsCPU(), and cloudViewer::core::Tensor::To().
Referenced by cloudViewer::t::geometry::LineSet::Rotate(), cloudViewer::t::geometry::PointCloud::Rotate(), and cloudViewer::t::geometry::TriangleMesh::Rotate().
RotatePointsCPU()
void cloudViewer::t::geometry::kernel::transform::RotatePointsCPU (const core::Tensor & R, core::Tensor & points, const core::Tensor & center)
Definition at line 133 of file TransformImpl.h.
References DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, and points.
Referenced by RotatePoints().
RotatePointsKernel()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::t::geometry::kernel::transform::RotatePointsKernel (const scalar_t * R_ptr, scalar_t * points_ptr, const scalar_t * center)
Definition at line 62 of file TransformImpl.h.
TransformNormals()
void cloudViewer::t::geometry::kernel::transform::TransformNormals (const core::Tensor & transformation, core::Tensor & normals)
Definition at line 41 of file Transform.cpp.
References AssertTensorShape, cloudViewer::core::Tensor::Contiguous(), CUDA_CALL, LogError, normals, cloudViewer::utility::nullopt, cloudViewer::core::Tensor::To(), and TransformNormalsCPU().
Referenced by cloudViewer::t::geometry::PointCloud::Transform(), and cloudViewer::t::geometry::TriangleMesh::Transform().
TransformNormalsCPU()
void cloudViewer::t::geometry::kernel::transform::TransformNormalsCPU (const core::Tensor & transformation, core::Tensor & normals)
Definition at line 113 of file TransformImpl.h.
References DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, and normals.
Referenced by TransformNormals().
TransformNormalsKernel()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::t::geometry::kernel::transform::TransformNormalsKernel (const scalar_t * transformation_ptr, scalar_t * normals_ptr)
Definition at line 44 of file TransformImpl.h.
TransformPoints()
void cloudViewer::t::geometry::kernel::transform::TransformPoints (const core::Tensor & transformation, core::Tensor & points)
Definition at line 20 of file Transform.cpp.
References AssertTensorShape, cloudViewer::core::Tensor::Contiguous(), CUDA_CALL, LogError, cloudViewer::utility::nullopt, points, cloudViewer::core::Tensor::To(), and TransformPointsCPU().
Referenced by cloudViewer::t::geometry::LineSet::Transform(), cloudViewer::t::geometry::PointCloud::Transform(), and cloudViewer::t::geometry::TriangleMesh::Transform().
TransformPointsCPU()
void cloudViewer::t::geometry::kernel::transform::TransformPointsCPU (const core::Tensor & transformation, core::Tensor & points)
Definition at line 93 of file TransformImpl.h.
References DISPATCH_FLOAT_DTYPE_TO_TEMPLATE, and points.
Referenced by TransformPoints().
TransformPointsKernel()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::t::geometry::kernel::transform::TransformPointsKernel (const scalar_t * transformation_ptr, scalar_t * points_ptr)
Definition at line 19 of file TransformImpl.h.