ACloudViewer: cloudViewer::core::linalg::kernel Namespace Reference
cloudViewer::core::linalg::kernel Namespace Reference
Classes
union un
Functions
template<typename scalar_t >
static CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void matmul3x3_3x1 (const scalar_t &m00, const scalar_t &m01, const scalar_t &m02, const scalar_t &m10, const scalar_t &m11, const scalar_t &m12, const scalar_t &m20, const scalar_t &m21, const scalar_t &m22, const scalar_t &v0, const scalar_t &v1, const scalar_t &v2, scalar_t &o0, scalar_t &o1, scalar_t &o2)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE void matmul3x3_3x1 (const scalar_t *A_3x3, const scalar_t *B_3x1, scalar_t *C_3x1)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void matmul3x3_3x3 (const scalar_t *A_3x3, const scalar_t *B_3x3, scalar_t *C_3x3)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE void cross_3x1 (const scalar_t *A_3x1_input, const scalar_t *B_3x1_input, scalar_t *C_3x1_output)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE scalar_t cross_mag_3x1 (const scalar_t *A_3x1_input, const scalar_t *B_3x1_input)
template<typename scalar_t >
CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE scalar_t dot_3x1 (const scalar_t *A_3x1_input, const scalar_t *B_3x1_input)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE scalar_t det2x2 (const scalar_t *A_2x2)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE scalar_t det3x3 (const scalar_t *A_3x3)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE bool inverse2x2 (const scalar_t *A_2x2, scalar_t *output_2x2)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE bool inverse3x3 (const scalar_t *A_3x3, scalar_t *output_3x3)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void transpose2x2_ (scalar_t *A_2x2)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void transpose2x2 (const scalar_t *A_2x2, scalar_t *output_2x2)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void transpose3x3_ (scalar_t *A_3x3)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void transpose3x3 (const scalar_t *A_3x3, scalar_t *output_3x3)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void transpose4x4_ (scalar_t *A_4x4)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void transpose4x4 (const scalar_t *A_4x4, scalar_t *output_4x4)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void svd3x3 (const scalar_t *A_3x3, scalar_t *U_3x3, scalar_t *S_3x1, scalar_t *V_3x3)
template<>
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void svd3x3< double > (const double *A_3x3, double *U_3x3, double *S_3x1, double *V_3x3)
template<>
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void svd3x3< float > (const float *A_3x3, float *U_3x3, float *S_3x1, float *V_3x3)
template<typename scalar_t >
CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void solve_svd3x3 (const scalar_t *A_3x3, const scalar_t *B_3x1, scalar_t *X_3x1)
Function Documentation
cross_3x1()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::cross_3x1 (const scalar_t * A_3x1_input, const scalar_t * B_3x1_input, scalar_t * C_3x1_output)
Definition at line 62 of file Matrix.h.
Referenced by cloudViewer::t::geometry::kernel::pointcloud::ComputeEigenvector0(), cloudViewer::t::geometry::kernel::pointcloud::ComputeEigenvector1(), cloudViewer::t::pipelines::kernel::ComputePairFeature(), cloudViewer::t::geometry::kernel::trianglemesh::ComputeTriangleNormalsCPU(), cloudViewer::t::geometry::kernel::pointcloud::GetCoordinateSystemOnPlane(), cloudViewer::t::pipelines::kernel::GetJacobianDopplerICP(), and cloudViewer::t::pipelines::kernel::PreComputeForDopplerICP().
cross_mag_3x1()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE scalar_t cloudViewer::core::linalg::kernel::cross_mag_3x1 (const scalar_t * A_3x1_input, const scalar_t * B_3x1_input)
Definition at line 76 of file Matrix.h.
Referenced by cloudViewer::t::geometry::kernel::trianglemesh::ComputeTriangleAreasCPU().
det2x2()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE scalar_t cloudViewer::core::linalg::kernel::det2x2 (const scalar_t * A_2x2)
Definition at line 96 of file Matrix.h.
Referenced by cloudViewer::core::Det().
det3x3()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE scalar_t cloudViewer::core::linalg::kernel::det3x3 (const scalar_t * A_3x3)
Definition at line 102 of file Matrix.h.
Referenced by cloudViewer::core::Det(), cloudViewer::t::pipelines::kernel::FillInSLACRegularizerTermCPU(), inverse2x2(), and inverse3x3().
dot_3x1()
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE scalar_t cloudViewer::core::linalg::kernel::dot_3x1 (const scalar_t * A_3x1_input, const scalar_t * B_3x1_input)
Definition at line 88 of file Matrix.h.
Referenced by cloudViewer::t::geometry::kernel::pointcloud::ComputeEigenvector0(), cloudViewer::t::geometry::kernel::pointcloud::ComputeEigenvector1(), cloudViewer::t::pipelines::kernel::ComputePairFeature(), cloudViewer::t::pipelines::kernel::GetJacobianDopplerICP(), cloudViewer::t::geometry::kernel::pointcloud::OrientNormalsToAlignWithDirectionCPU(), and cloudViewer::t::geometry::kernel::pointcloud::OrientNormalsTowardsCameraLocationCPU().
inverse2x2()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE bool cloudViewer::core::linalg::kernel::inverse2x2 (const scalar_t * A_2x2, scalar_t * output_2x2)
Definition at line 109 of file Matrix.h.
References det3x3(), and e.
inverse3x3()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE bool cloudViewer::core::linalg::kernel::inverse3x3 (const scalar_t * A_3x3, scalar_t * output_3x3)
Definition at line 126 of file Matrix.h.
References det3x3(), and e.
matmul3x3_3x1() [1/2]
template<typename scalar_t > static CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::matmul3x3_3x1 (const scalar_t & m00, const scalar_t & m01, const scalar_t & m02, const scalar_t & m10, const scalar_t & m11, const scalar_t & m12, const scalar_t & m20, const scalar_t & m21, const scalar_t & m22, const scalar_t & v0, const scalar_t & v1, const scalar_t & v2, scalar_t & o0, scalar_t & o1, scalar_t & o2) static
Definition at line 18 of file Matrix.h.
Referenced by cloudViewer::t::geometry::kernel::pointcloud::ComputeEigenvector1(), cloudViewer::t::pipelines::kernel::FillInSLACRegularizerTermCPU(), cloudViewer::t::pipelines::kernel::GetJacobianDopplerICP(), matmul3x3_3x3(), cloudViewer::t::pipelines::kernel::PreComputeForDopplerICP(), and solve_svd3x3().
matmul3x3_3x1() [2/2]
template<typename scalar_t > CLOUDVIEWER_HOST_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::matmul3x3_3x1 (const scalar_t * A_3x3, const scalar_t * B_3x1, scalar_t * C_3x1)
Definition at line 40 of file Matrix.h.
matmul3x3_3x3()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::matmul3x3_3x3 (const scalar_t * A_3x3, const scalar_t * B_3x3, scalar_t * C_3x3)
Definition at line 48 of file Matrix.h.
References matmul3x3_3x1().
Referenced by cloudViewer::t::pipelines::kernel::FillInSLACRegularizerTermCPU(), and solve_svd3x3().
solve_svd3x3()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::solve_svd3x3 (const scalar_t * A_3x3, const scalar_t * B_3x1, scalar_t * X_3x1)
Definition at line 2167 of file SVD3x3.h.
References e, matmul3x3_3x1(), matmul3x3_3x3(), and svd3x3().
Referenced by cloudViewer::t::geometry::kernel::pointcloud::EstimatePointWiseColorGradientKernel().
svd3x3()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::svd3x3 (const scalar_t * A_3x3, scalar_t * U_3x3, scalar_t * S_3x1, scalar_t * V_3x3)
Referenced by cloudViewer::t::pipelines::kernel::FillInSLACRegularizerTermCPU(), and solve_svd3x3().
svd3x3< double >()
template<> CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::svd3x3< double > (const double * A_3x3, double * U_3x3, double * S_3x1, double * V_3x3)
Definition at line 93 of file SVD3x3.h.
References __dadd_rn, __drsqrt_rn, __dsub_rn, cloudViewer::core::linalg::kernel::un< scalar_t >::f, gcosine_pi_over_eight, gfour_gamma_squared, gone, gsine_pi_over_eight, gtiny_number, and cloudViewer::core::linalg::kernel::un< scalar_t >::ui.
svd3x3< float >()
template<> CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::svd3x3< float > (const float * A_3x3, float * U_3x3, float * S_3x1, float * V_3x3)
Definition at line 1130 of file SVD3x3.h.
References __fadd_rn, __frsqrt_rn, __fsub_rn, cloudViewer::core::linalg::kernel::un< scalar_t >::f, gcosine_pi_over_eight, gfour_gamma_squared, gone, gsine_pi_over_eight, gtiny_number, and cloudViewer::core::linalg::kernel::un< scalar_t >::ui.
transpose2x2()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::transpose2x2 (const scalar_t * A_2x2, scalar_t * output_2x2)
Definition at line 156 of file Matrix.h.
transpose2x2_()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::transpose2x2_ (scalar_t * A_2x2)
Definition at line 148 of file Matrix.h.
transpose3x3()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::transpose3x3 (const scalar_t * A_3x3, scalar_t * output_3x3)
Definition at line 179 of file Matrix.h.
transpose3x3_()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::transpose3x3_ (scalar_t * A_3x3)
Definition at line 165 of file Matrix.h.
Referenced by cloudViewer::t::pipelines::kernel::FillInSLACRegularizerTermCPU().
transpose4x4()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::transpose4x4 (const scalar_t * A_4x4, scalar_t * output_4x4)
Definition at line 218 of file Matrix.h.
transpose4x4_()
template<typename scalar_t > CLOUDVIEWER_DEVICE CLOUDVIEWER_FORCE_INLINE void cloudViewer::core::linalg::kernel::transpose4x4_ (scalar_t * A_4x4)
Definition at line 195 of file Matrix.h.