ACloudViewer: cloudViewer::visualization Namespace Reference
cloudViewer::visualization Namespace Reference
Namespaces
app
gl_util
gui
rendering
visualizer
webrtc_server
Classes
class ColorMap
class ColorMapGray
class ColorMapJet
See Matlab's Jet colormap.
class ColorMapSummer
See Matlab's Summer colormap.
class ColorMapWinter
See Matlab's Winter colormap.
class ColorMapHot
struct DrawObject
struct DrawAction
class PointCloudPicker
A utility class to store picked points of a pointcloud.
class SelectionPolygon
class SelectionPolygonVolume
Select a polygon volume for cropping.
class GuiSettingsModel
class GuiSettingsView
class GuiVisualizer
class SmallButton
class SmallToggleButton
class MessageProcessor
class RenderOption
Defines rendering options for visualizer.
class RenderOptionWithEditing
class ViewControl
View controller for visualizer.
class ViewControlWithCustomAnimation
class ViewControlWithEditing
class ViewParameters
class ViewTrajectory
class GLFWContext
GLFW context, handled as a singleton.
class Visualizer
The main Visualizer class.
class VisualizerWithCustomAnimation
class VisualizerWithEditing
Visualizer with editing capabilities.
class VisualizerWithKeyCallback
Visualizer with custom key callack capabilities.
class VisualizerWithVertexSelection
Enumerations
enum MenuId {
FILE_OPEN , FILE_EXPORT_RGB , FILE_QUIT , SETTINGS_LIGHT_AND_MATERIALS ,
HELP_KEYS , HELP_CAMERA , HELP_ABOUT , HELP_CONTACT ,
HELP_DEBUG
}
Functions
const std::shared_ptr< const ColorMap > GetGlobalColorMap ()
Interface functions.
void SetGlobalColorMap (ColorMap::ColorMapOption option)
void Draw (const std::vector< std::shared_ptr< ccHObject >> &geometries, const std::string &window_name, int width, int height, const std::vector< DrawAction > &actions)
void Draw (const std::vector< std::shared_ptr< t::geometry::Geometry >> &tgeometries, const std::string &window_name, int width, int height, const std::vector< DrawAction > &actions)
void Draw (const std::vector< std::shared_ptr< rendering::TriangleMeshModel >> &models, const std::string &window_name, int width, int height, const std::vector< DrawAction > &actions)
void Draw (const std::vector< DrawObject > &objects, const std::string &window_name, int width, int height, const std::vector< DrawAction > &actions)
bool DrawGeometries (const std::vector< std::shared_ptr< const ccHObject >> &geometry_ptrs, const std::string &window_name="cloudViewer", int width=640, int height=480, int left=50, int top=50, bool point_show_normal=false, bool mesh_show_wireframe=false, bool mesh_show_back_face=false, Eigen::Vector3d *lookat=nullptr, Eigen::Vector3d *up=nullptr, Eigen::Vector3d *front=nullptr, double *zoom=nullptr)
Function to draw a list of geometry objects.
bool DrawGeometriesWithCustomAnimation (const std::vector< std::shared_ptr< const ccHObject >> &geometry_ptrs, const std::string &window_name="CloudViewer", int width=640, int height=480, int left=50, int top=50, const std::string &json_filename="")
Function to draw a list of geometry objects with a GUI that supports animation.
bool DrawGeometriesWithAnimationCallback (const std::vector< std::shared_ptr< const ccHObject >> &geometry_ptrs, std::function< bool(Visualizer *)> callback_func, const std::string &window_name="CloudViewer", int width=640, int height=480, int left=50, int top=50)
Function to draw a list of geometry objects with a customized animation callback function.
bool DrawGeometriesWithKeyCallbacks (const std::vector< std::shared_ptr< const ccHObject >> &geometry_ptrs, const std::map< int, std::function< bool(Visualizer *)>> &key_to_callback, const std::string &window_name="CloudViewer", int width=640, int height=480, int left=50, int top=50)
Function to draw a list of geometry.
bool DrawGeometriesWithEditing (const std::vector< std::shared_ptr< const ccHObject >> &geometry_ptrs, const std::string &window_name="CloudViewer", int width=640, int height=480, int left=50, int top=50)
Function to draw a list of geometry.
bool DrawGeometriesWithVertexSelection (const std::vector< std::shared_ptr< const ccHObject >> &geometry_ptrs, const std::string &window_name, int width, int height, int left, int top)
std::shared_ptr< gui::Slider > MakeSlider (const gui::Slider::Type type, const double min, const double max, const double value)
void pybind_o3dvisualizer (py::module &m)
void pybind_renderoption (py::module &m)
void pybind_renderoption_method (py::module &m)
void pybind_visualization_utility (py::module &m)
void pybind_visualization_utility_methods (py::module &m)
void pybind_viewcontrol (py::module &m)
void pybind_viewcontrol_method (py::module &m)
void pybind_visualization (py::module &m)
template<typename T >
std::shared_ptr< T > TakeOwnership (UnownedPointer< T > x)
void pybind_visualizer (py::module &m)
void pybind_visualizer_method (py::module &m)
Variables
static const char * CUSTOM_LIGHTING = "Custom"
const std::string MODEL_NAME = "__model__"
const std::string INSPECT_MODEL_NAME = "__inspect_model__"
const std::string WIREFRAME_NAME = "__wireframe_model__"
static const std::unordered_map< std::string, std::string > map_shared_argument_docstrings
static const std::unordered_map< std::string, std::string > map_view_control_docstrings
static const std::unordered_map< std::string, std::string > map_visualizer_docstrings
Enumeration Type Documentation
MenuId
enum cloudViewer::visualization::MenuId
Enumerator
FILE_OPEN
FILE_EXPORT_RGB
FILE_QUIT
SETTINGS_LIGHT_AND_MATERIALS
HELP_KEYS
HELP_CAMERA
HELP_ABOUT
HELP_CONTACT
HELP_DEBUG
Definition at line 302 of file GuiVisualizer.cpp.
Function Documentation
Draw() [1/4]
void cloudViewer::visualization::Draw (const std::vector< DrawObject > & objects, const std::string & window_name, int width, int height, const std::vector< DrawAction > & actions)
Definition at line 92 of file Draw.cpp.
References cloudViewer::visualization::gui::Application::AddWindow(), cloudViewer::visualization::gui::Application::GetInstance(), height, cloudViewer::visualization::gui::Application::Initialize(), LogWarning, cloudViewer::visualization::gui::Application::Run(), and width.
Draw() [2/4]
void cloudViewer::visualization::Draw (const std::vector< std::shared_ptr< ccHObject >> & geometries, const std::string & window_name, int width, int height, const std::vector< DrawAction > & actions)
Definition at line 45 of file Draw.cpp.
References height, name, and width.
Referenced by Draw().
Draw() [3/4]
void cloudViewer::visualization::Draw (const std::vector< std::shared_ptr< rendering::TriangleMeshModel >> & models, const std::string & window_name, int width, int height, const std::vector< DrawAction > & actions)
Definition at line 76 of file Draw.cpp.
References Draw(), height, name, and width.
Draw() [4/4]
void cloudViewer::visualization::Draw (const std::vector< std::shared_ptr< t::geometry::Geometry >> & tgeometries, const std::string & window_name, int width, int height, const std::vector< DrawAction > & actions)
Definition at line 60 of file Draw.cpp.
References Draw(), height, name, and width.
DrawGeometries()
bool cloudViewer::visualization::DrawGeometries (const std::vector< std::shared_ptr< const ccHObject >> & geometry_ptrs, const std::string & window_name = "cloudViewer", int width = 640, int height = 480, int left = 50, int top = 50, bool point_show_normal = false, bool mesh_show_wireframe = false, bool mesh_show_back_face = false, Eigen::Vector3d * lookat = nullptr, Eigen::Vector3d * up = nullptr, Eigen::Vector3d * front = nullptr, double * zoom = nullptr)
Function to draw a list of geometry objects.
The convenient function of drawing something This function is a wrapper that calls the core functions of Visualizer. This function MUST be called from the main thread. It blocks the main thread until the window is closed.
Parameters
geometry_ptrs List of geometries to be visualized.
window_name The displayed title of the visualization window.
width The width of the visualization window.
height The height of the visualization window.
left margin of the visualization window.
top The top margin of the visualization window.
point_show_normal visualize point normals if set to true.
mesh_show_wireframe visualize mesh wireframe if set to true.
mesh_show_back_face visualize also the back face of the mesh triangles.
lookat The lookat vector of the camera.
up The up vector of the camera.
front The front vector of the camera.
zoom The zoom of the camera.
Definition at line 32 of file DrawGeometry.cpp.
References cloudViewer::visualization::Visualizer::AddGeometry(), cloudViewer::visualization::Visualizer::CreateVisualizerWindow(), cloudViewer::visualization::Visualizer::DestroyVisualizerWindow(), cloudViewer::visualization::Visualizer::GetRenderOption(), cloudViewer::visualization::Visualizer::GetViewControl(), height, LogWarning, cloudViewer::visualization::RenderOption::mesh_show_back_face_, cloudViewer::visualization::RenderOption::mesh_show_wireframe_, cloudViewer::visualization::RenderOption::point_show_normal_, cloudViewer::visualization::Visualizer::Run(), cloudViewer::visualization::ViewControl::SetFront(), cloudViewer::visualization::ViewControl::SetLookat(), cloudViewer::visualization::ViewControl::SetUp(), cloudViewer::visualization::ViewControl::SetZoom(), and width.
Referenced by pybind_visualization_utility_methods(), cloudViewer::t::pipelines::slac::VisualizeGridDeformation(), cloudViewer::t::pipelines::slac::VisualizePointCloudCorrespondences(), and cloudViewer::t::pipelines::slac::VisualizePointCloudDeformation().
DrawGeometriesWithAnimationCallback()
bool cloudViewer::visualization::DrawGeometriesWithAnimationCallback (const std::vector< std::shared_ptr< const ccHObject >> & geometry_ptrs, std::function< bool(Visualizer *)> callback_func, const std::string & window_name = "CloudViewer", int width = 640, int height = 480, int left = 50, int top = 50)
Function to draw a list of geometry objects with a customized animation callback function.
Parameters
geometry_ptrs List of geometries to be visualized.
callback_func Call back function to be triggered at a key press event.
window_name The displayed title of the visualization window.
width The width of the visualization window.
height The height of the visualization window.
left margin of the visualization window.
top The top margin of the visualization window.
Definition at line 130 of file DrawGeometry.cpp.
References cloudViewer::visualization::Visualizer::AddGeometry(), cloudViewer::visualization::Visualizer::CreateVisualizerWindow(), cloudViewer::visualization::Visualizer::DestroyVisualizerWindow(), height, LogWarning, cloudViewer::visualization::Visualizer::RegisterAnimationCallback(), cloudViewer::visualization::Visualizer::Run(), and width.
Referenced by pybind_visualization_utility_methods().
DrawGeometriesWithCustomAnimation()
bool cloudViewer::visualization::DrawGeometriesWithCustomAnimation (const std::vector< std::shared_ptr< const ccHObject >> & geometry_ptrs, const std::string & window_name = "CloudViewer", int width = 640, int height = 480, int left = 50, int top = 50, const std::string & json_filename = "")
Function to draw a list of geometry objects with a GUI that supports animation.
Parameters
geometry_ptrs List of geometries to be visualized.
window_name The displayed title of the visualization window.
width The width of the visualization window.
height The height of the visualization window.
left margin of the visualization window.
top The top margin of the visualization window.
json_filename Camera trajectory json file path for custom animation.
Definition at line 84 of file DrawGeometry.cpp.
References cloudViewer::visualization::Visualizer::AddGeometry(), cloudViewer::visualization::Visualizer::CreateVisualizerWindow(), cloudViewer::visualization::Visualizer::DestroyVisualizerWindow(), cloudViewer::visualization::Visualizer::GetViewControl(), height, LogWarning, cloudViewer::visualization::Visualizer::Run(), cloudViewer::visualization::VisualizerWithCustomAnimation::UpdateWindowTitle(), and width.
Referenced by pybind_visualization_utility_methods().
DrawGeometriesWithEditing()
bool cloudViewer::visualization::DrawGeometriesWithEditing (const std::vector< std::shared_ptr< const ccHObject >> & geometry_ptrs, const std::string & window_name = "CloudViewer", int width = 640, int height = 480, int left = 50, int top = 50)
Function to draw a list of geometry.
Geometry providing user interaction.
Parameters
geometry_ptrs List of geometries to be visualized.
window_name The displayed title of the visualization window.
width The width of the visualization window.
height The height of the visualization window.
left margin of the visualization window.
top The top margin of the visualization window.
Definition at line 199 of file DrawGeometry.cpp.
References cloudViewer::visualization::VisualizerWithEditing::AddGeometry(), cloudViewer::visualization::Visualizer::CreateVisualizerWindow(), cloudViewer::visualization::Visualizer::DestroyVisualizerWindow(), height, LogWarning, cloudViewer::visualization::Visualizer::Run(), and width.
Referenced by pybind_visualization_utility_methods().
DrawGeometriesWithKeyCallbacks()
bool cloudViewer::visualization::DrawGeometriesWithKeyCallbacks (const std::vector< std::shared_ptr< const ccHObject >> & geometry_ptrs, const std::map< int, std::function< bool(Visualizer *)>> & key_to_callback, const std::string & window_name = "CloudViewer", int width = 640, int height = 480, int left = 50, int top = 50)
Function to draw a list of geometry.
Geometry objects with a customized key-callback mapping
Parameters
geometry_ptrs List of geometries to be visualized.
key_to_callback Map of key to call back functions.
window_name The displayed title of the visualization window.
width The width of the visualization window.
height The height of the visualization window.
left margin of the visualization window.
top The top margin of the visualization window.
Definition at line 163 of file DrawGeometry.cpp.
References cloudViewer::visualization::Visualizer::AddGeometry(), cloudViewer::visualization::Visualizer::CreateVisualizerWindow(), cloudViewer::visualization::Visualizer::DestroyVisualizerWindow(), height, LogWarning, cloudViewer::visualization::VisualizerWithKeyCallback::RegisterKeyCallback(), cloudViewer::visualization::Visualizer::Run(), and width.
Referenced by pybind_visualization_utility_methods().
DrawGeometriesWithVertexSelection()
bool cloudViewer::visualization::DrawGeometriesWithVertexSelection (const std::vector< std::shared_ptr< const ccHObject >> & geometry_ptrs, const std::string & window_name, int width, int height, int left, int top)
Definition at line 228 of file DrawGeometry.cpp.
References cloudViewer::visualization::VisualizerWithVertexSelection::AddGeometry(), cloudViewer::visualization::Visualizer::CreateVisualizerWindow(), cloudViewer::visualization::Visualizer::DestroyVisualizerWindow(), height, LogWarning, cloudViewer::visualization::Visualizer::Run(), and width.
Referenced by pybind_visualization_utility_methods().
GetGlobalColorMap()
const std::shared_ptr< const ColorMap > cloudViewer::visualization::GetGlobalColorMap ()
Interface functions.
Definition at line 84 of file ColorMap.cpp.
References Runtime::GetInstance().
MakeSlider()
std::shared_ptr<gui::Slider> cloudViewer::visualization::MakeSlider (const gui::Slider::Type type, const double min, const double max, const double value)
Definition at line 30 of file GuiSettingsView.cpp.
References max(), min(), and type.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
pybind_o3dvisualizer()
void cloudViewer::visualization::pybind_o3dvisualizer (py::module & m)
Definition at line 27 of file o3dvisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::Add3DLabel(), cloudViewer::visualization::visualizer::O3DVisualizer::AddAction(), cloudViewer::visualization::visualizer::O3DVisualizer::AddGeometry(), cloudViewer::visualization::visualizer::O3DVisualizer::Clear3DLabels(), cloudViewer::visualization::gui::Window::Close(), cloudViewer::visualization::gui::Window::CloseDialog(), cloudViewer::visualization::visualizer::O3DVisualizer::DEPTH, cloudViewer::visualization::visualizer::O3DVisualizer::EnableBasicMode(), cloudViewer::visualization::visualizer::O3DVisualizer::ExportCurrentImage(), cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::geometry, cloudViewer::visualization::visualizer::O3DVisualizer::GetAnimationDuration(), cloudViewer::visualization::visualizer::O3DVisualizer::GetAnimationFrameDelay(), cloudViewer::visualization::visualizer::O3DVisualizer::GetAnimationTimeStep(), cloudViewer::visualization::gui::Window::GetContentRect(), cloudViewer::visualization::visualizer::O3DVisualizer::GetGeometry(), cloudViewer::visualization::visualizer::O3DVisualizer::GetGeometryMaterial(), cloudViewer::visualization::visualizer::O3DVisualizer::GetIsAnimating(), cloudViewer::visualization::gui::Window::GetOSFrame(), cloudViewer::visualization::gui::Window::GetScaling(), cloudViewer::visualization::visualizer::O3DVisualizer::GetScene(), cloudViewer::visualization::visualizer::O3DVisualizer::GetSelectionSets(), cloudViewer::visualization::gui::Window::GetSize(), cloudViewer::visualization::gui::Window::GetTitle(), cloudViewer::visualization::gui::Window::GetWebRTCUID(), cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::group, cloudViewer::visualization::visualizer::O3DVisualizerSelections::SelectedIndex::index, cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::is_visible, cloudViewer::visualization::gui::Window::IsVisible(), cloudViewer::visualization::visualizer::O3DVisualizer::ModifyGeometryMaterial(), name, cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::name, cloudViewer::visualization::visualizer::O3DVisualizer::NO_CHANGE, cloudViewer::visualization::visualizer::O3DVisualizer::NORMALS, cloudViewer::visualization::visualizer::O3DVisualizerSelections::SelectedIndex::order, cloudViewer::visualization::visualizer::O3DVisualizerSelections::SelectedIndex::point, cloudViewer::visualization::gui::Window::PostRedraw(), cloudViewer::visualization::visualizer::O3DVisualizer::REDRAW, cloudViewer::visualization::visualizer::O3DVisualizer::RemoveGeometry(), cloudViewer::visualization::visualizer::O3DVisualizer::ResetCameraToDefault(), cloudViewer::visualization::visualizer::O3DVisualizer::SetAnimating(), cloudViewer::visualization::visualizer::O3DVisualizer::SetAnimationDuration(), cloudViewer::visualization::visualizer::O3DVisualizer::SetAnimationFrameDelay(), cloudViewer::visualization::visualizer::O3DVisualizer::SetAnimationTimeStep(), cloudViewer::visualization::visualizer::O3DVisualizer::SetBackground(), cloudViewer::visualization::visualizer::O3DVisualizer::SetCurrentTime(), cloudViewer::visualization::visualizer::O3DVisualizer::SetGroundPlane(), cloudViewer::visualization::visualizer::O3DVisualizer::SetIBL(), cloudViewer::visualization::visualizer::O3DVisualizer::SetIBLIntensity(), cloudViewer::visualization::visualizer::O3DVisualizer::SetLineWidth(), cloudViewer::visualization::visualizer::O3DVisualizer::SetMouseMode(), cloudViewer::visualization::visualizer::O3DVisualizer::SetOnAnimationFrame(), cloudViewer::visualization::visualizer::O3DVisualizer::SetOnAnimationTick(), cloudViewer::visualization::gui::Window::SetOnClose(), cloudViewer::visualization::gui::Window::SetOSFrame(), cloudViewer::visualization::visualizer::O3DVisualizer::SetPanelOpen(), cloudViewer::visualization::visualizer::O3DVisualizer::SetPointSize(), cloudViewer::visualization::visualizer::O3DVisualizer::SetShader(), cloudViewer::visualization::gui::Window::SetSize(), cloudViewer::visualization::gui::Window::SetTitle(), cloudViewer::visualization::visualizer::O3DVisualizer::SetupCamera(), cloudViewer::visualization::gui::Window::Show(), cloudViewer::visualization::visualizer::O3DVisualizer::ShowAxes(), cloudViewer::visualization::gui::Window::ShowDialog(), cloudViewer::visualization::visualizer::O3DVisualizer::ShowGeometry(), cloudViewer::visualization::visualizer::O3DVisualizer::ShowGround(), cloudViewer::visualization::gui::Window::ShowMenu(), cloudViewer::visualization::gui::Window::ShowMessageBox(), cloudViewer::visualization::visualizer::O3DVisualizer::ShowSettings(), cloudViewer::visualization::visualizer::O3DVisualizer::ShowSkybox(), cloudViewer::visualization::gui::Window::SizeToFit(), cloudViewer::visualization::visualizer::O3DVisualizer::STANDARD, cloudViewer::visualization::visualizer::O3DVisualizer::StartRPCInterface(), cloudViewer::visualization::visualizer::O3DVisualizer::StopRPCInterface(), cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::time, cloudViewer::visualization::visualizer::O3DVisualizer::UNLIT, and cloudViewer::visualization::visualizer::O3DVisualizer::UpdateGeometry().
Referenced by pybind_visualization().
pybind_renderoption()
void cloudViewer::visualization::pybind_renderoption (py::module & m)
Definition at line 22 of file renderoption.cpp.
References cloudViewer::visualization::RenderOption::background_color_, cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::visualization::RenderOption::Color, cloudViewer::visualization::RenderOption::Default, filename, cloudViewer::visualization::RenderOption::FlatShade, cloudViewer::visualization::RenderOption::light_on_, cloudViewer::visualization::RenderOption::line_width_, cloudViewer::visualization::RenderOption::mesh_color_option_, cloudViewer::visualization::RenderOption::mesh_shade_option_, cloudViewer::visualization::RenderOption::mesh_show_back_face_, cloudViewer::visualization::RenderOption::mesh_show_wireframe_, cloudViewer::visualization::RenderOption::Normal, cloudViewer::t::geometry::path, cloudViewer::visualization::RenderOption::point_color_option_, cloudViewer::visualization::RenderOption::point_show_normal_, cloudViewer::visualization::RenderOption::point_size_, cloudViewer::io::ReadIJsonConvertible(), cloudViewer::visualization::RenderOption::show_coordinate_frame_, cloudViewer::visualization::RenderOption::SmoothShade, cloudViewer::io::WriteIJsonConvertible(), cloudViewer::visualization::RenderOption::XCoordinate, cloudViewer::visualization::RenderOption::YCoordinate, and cloudViewer::visualization::RenderOption::ZCoordinate.
Referenced by pybind_visualization().
pybind_renderoption_method()
void cloudViewer::visualization::pybind_renderoption_method (py::module & m)
Definition at line 150 of file renderoption.cpp.
Referenced by pybind_visualization().
pybind_viewcontrol()
void cloudViewer::visualization::pybind_viewcontrol (py::module & m)
Definition at line 33 of file viewcontrol.cpp.
References cloudViewer::visualization::ViewControl::CameraLocalRotate(), cloudViewer::visualization::ViewControl::CameraLocalTranslate(), cloudViewer::visualization::ViewControl::ChangeFieldOfView(), cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::visualization::ViewControl::ConvertFromPinholeCameraParameters(), cloudViewer::visualization::ViewControl::ConvertToPinholeCameraParameters(), cloudViewer::visualization::ViewControl::GetFieldOfView(), map_view_control_docstrings, cloudViewer::visualization::ViewControl::ResetCameraLocalRotate(), cloudViewer::visualization::ViewControl::Rotate(), cloudViewer::visualization::ViewControl::Scale(), cloudViewer::visualization::ViewControl::SetConstantZFar(), cloudViewer::visualization::ViewControl::SetConstantZNear(), cloudViewer::visualization::ViewControl::SetFront(), cloudViewer::visualization::ViewControl::SetLookat(), cloudViewer::visualization::ViewControl::SetUp(), cloudViewer::visualization::ViewControl::SetZoom(), cloudViewer::visualization::ViewControl::Translate(), cloudViewer::visualization::ViewControl::UnsetConstantZFar(), and cloudViewer::visualization::ViewControl::UnsetConstantZNear().
Referenced by pybind_visualization().
pybind_viewcontrol_method()
void cloudViewer::visualization::pybind_viewcontrol_method (py::module & m)
Definition at line 127 of file viewcontrol.cpp.
Referenced by pybind_visualization().
pybind_visualization()
void cloudViewer::visualization::pybind_visualization (py::module & m)
Definition at line 22 of file visualization.cpp.
References cloudViewer::visualization::app::pybind_app(), cloudViewer::visualization::gui::pybind_gui(), cloudViewer::visualization::rendering::pybind_material(), pybind_o3dvisualizer(), cloudViewer::visualization::rendering::pybind_rendering(), pybind_renderoption(), pybind_renderoption_method(), pybind_viewcontrol(), pybind_viewcontrol_method(), pybind_visualization_utility(), pybind_visualization_utility_methods(), pybind_visualizer(), pybind_visualizer_method(), and cloudViewer::visualization::webrtc_server::pybind_webrtc_server().
Referenced by cloudViewer::PYBIND11_MODULE().
pybind_visualization_utility()
void cloudViewer::visualization::pybind_visualization_utility (py::module & m)
Definition at line 26 of file utility.cpp.
References cloudViewer::visualization::SelectionPolygonVolume::axis_max_, cloudViewer::visualization::SelectionPolygonVolume::axis_min_, cloudViewer::visualization::SelectionPolygonVolume::bounding_polygon_, cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::visualization::SelectionPolygonVolume::CropInPolygon(), cloudViewer::visualization::SelectionPolygonVolume::CropPointCloud(), cloudViewer::visualization::SelectionPolygonVolume::CropTriangleMesh(), and cloudViewer::visualization::SelectionPolygonVolume::orthogonal_axis_.
Referenced by pybind_visualization().
pybind_visualization_utility_methods()
void cloudViewer::visualization::pybind_visualization_utility_methods (py::module & m)
Definition at line 119 of file utility.cpp.
References cloudViewer::utility::filesystem::ChangeWorkingDirectory(), DrawGeometries(), DrawGeometriesWithAnimationCallback(), DrawGeometriesWithCustomAnimation(), DrawGeometriesWithEditing(), DrawGeometriesWithKeyCallbacks(), DrawGeometriesWithVertexSelection(), filename, cloudViewer::docstring::FunctionDocInject(), cloudViewer::utility::filesystem::GetWorkingDirectory(), cloudViewer::utility::optional< T >::has_value(), height, map_shared_argument_docstrings, cloudViewer::t::geometry::path, cloudViewer::io::ReadIJsonConvertible(), cloudViewer::utility::optional< T >::value(), and width.
Referenced by pybind_visualization().
pybind_visualizer()
void cloudViewer::visualization::pybind_visualizer (py::module & m)
Definition at line 42 of file visualizer.cpp.
References cloudViewer::visualization::Visualizer::AddGeometry(), cloudViewer::visualization::VisualizerWithVertexSelection::AddPickedPoints(), cloudViewer::visualization::Visualizer::CaptureDepthFloatBuffer(), cloudViewer::visualization::Visualizer::CaptureScreenFloatBuffer(), cloudViewer::docstring::ClassMethodDocInject(), cloudViewer::visualization::Visualizer::ClearGeometries(), cloudViewer::visualization::VisualizerWithVertexSelection::ClearPickedPoints(), cloudViewer::visualization::Visualizer::Close(), cloudViewer::visualization::VisualizerWithVertexSelection::PickedPoint::coord, cloudViewer::visualization::Visualizer::CreateVisualizerWindow(), cloudViewer::visualization::Visualizer::DestroyVisualizerWindow(), filename, cloudViewer::visualization::VisualizerWithEditing::GetPickedPoints(), cloudViewer::visualization::VisualizerWithVertexSelection::GetPickedPoints(), cloudViewer::visualization::Visualizer::GetRenderOption(), cloudViewer::visualization::Visualizer::GetViewControl(), cloudViewer::visualization::Visualizer::GetWindowName(), cloudViewer::visualization::VisualizerWithVertexSelection::PickedPoint::index, cloudViewer::visualization::Visualizer::IsFullScreen(), map_visualizer_docstrings, cloudViewer::t::geometry::path, cloudViewer::visualization::VisualizerWithVertexSelection::PickPoints(), cloudViewer::visualization::Visualizer::PollEvents(), cloudViewer::visualization::Visualizer::RegisterAnimationCallback(), cloudViewer::visualization::VisualizerWithKeyCallback::RegisterKeyActionCallback(), cloudViewer::visualization::VisualizerWithKeyCallback::RegisterKeyCallback(), cloudViewer::visualization::VisualizerWithKeyCallback::RegisterMouseButtonCallback(), cloudViewer::visualization::VisualizerWithKeyCallback::RegisterMouseMoveCallback(), cloudViewer::visualization::VisualizerWithKeyCallback::RegisterMouseScrollCallback(), cloudViewer::visualization::VisualizerWithVertexSelection::RegisterSelectionMovedCallback(), cloudViewer::visualization::Visualizer::RemoveGeometry(), cloudViewer::visualization::VisualizerWithVertexSelection::RemovePickedPoints(), cloudViewer::visualization::Visualizer::ResetViewPoint(), cloudViewer::visualization::Visualizer::Run(), cloudViewer::visualization::Visualizer::SetFullScreen(), cloudViewer::visualization::Visualizer::ToggleFullScreen(), cloudViewer::visualization::Visualizer::UpdateGeometry(), and cloudViewer::visualization::Visualizer::UpdateRender().
Referenced by pybind_visualization().
pybind_visualizer_method()
void cloudViewer::visualization::pybind_visualizer_method (py::module & m)
Definition at line 331 of file visualizer.cpp.
Referenced by pybind_visualization().
SetGlobalColorMap()
void cloudViewer::visualization::SetGlobalColorMap (ColorMap::ColorMapOption option)
Definition at line 88 of file ColorMap.cpp.
References Runtime::GetInstance(), cloudViewer::visualization::ColorMap::Gray, cloudViewer::visualization::ColorMap::Hot, cloudViewer::visualization::ColorMap::Jet, cloudViewer::visualization::ColorMap::Summer, and cloudViewer::visualization::ColorMap::Winter.
Referenced by cloudViewer::visualization::Visualizer::KeyPressCallback().
TakeOwnership()
template<typename T > std::shared_ptr<T> cloudViewer::visualization::TakeOwnership (UnownedPointer< T > x)
Definition at line 49 of file visualization.h.
References UnownedPointer< T >::get().
Referenced by cloudViewer::visualization::gui::pybind_gui_classes().
Variable Documentation
CUSTOM_LIGHTING
const char* cloudViewer::visualization::CUSTOM_LIGHTING = "Custom" static
Definition at line 28 of file GuiSettingsView.cpp.
Referenced by cloudViewer::visualization::GuiSettingsView::GuiSettingsView(), and cloudViewer::visualization::GuiSettingsView::Update().
INSPECT_MODEL_NAME
const std::string cloudViewer::visualization::INSPECT_MODEL_NAME = "__inspect_model__"
Definition at line 299 of file GuiVisualizer.cpp.
Referenced by cloudViewer::visualization::GuiVisualizer::Impl::SetBasicModeGeometry().
map_shared_argument_docstrings
const std::unordered_map<std::string, std::string> cloudViewer::visualization::map_shared_argument_docstrings static
Initial value:
= {
                {"callback_function",
                 "Call back function to be triggered at a key press "
                 "event."},
                {"filename", "The file path."},
                {"geometry_list", "List of geometries to be visualized."},
                {"height", "The height of the visualization window."},
                {"key_to_callback", "Map of key to call back functions."},
                {"left", "The left margin of the visualization window."},
                {"optional_view_trajectory_json_file",
                 "Camera trajectory json file path for custom animation."},
                {"top", "The top margin of the visualization window."},
                {"width", "The width of the visualization window."},
                {"point_show_normal",
                 "Visualize point normals if set to true."},
                {"mesh_show_wireframe",
                 "Visualize mesh wireframe if set to true."},
                {"mesh_show_back_face",
                 "Visualize also the back face of the mesh triangles."},
                {"window_name",
                 "The displayed title of the visualization window."},
                {"lookat", "The lookat vector of the camera."},
                {"up", "The up vector of the camera."},
                {"front", "The front vector of the camera."},
                {"zoom", "The zoom of the camera."}}
Definition at line 93 of file utility.cpp.
Referenced by pybind_visualization_utility_methods().
map_view_control_docstrings
const std::unordered_map<std::string, std::string> cloudViewer::visualization::map_view_control_docstrings static
Initial value:
= {
                {"parameter", "The pinhole camera parameter to convert from."},
                {"scale", "Scale ratio."},
                {"x", "Distance the mouse cursor has moved in x-axis."},
                {"y", "Distance the mouse cursor has moved in y-axis."},
                {"xo", "Original point coordinate of the mouse in x-axis."},
                {"yo", "Original point coordinate of the mouse in y-axis."},
                {"step", "The step to change field of view."},
                {"z_near", "The depth of the near z-plane of the visualizer."},
                {"z_far", "The depth of the far z-plane of the visualizer."},
}
Definition at line 21 of file viewcontrol.cpp.
Referenced by pybind_viewcontrol().
map_visualizer_docstrings
const std::unordered_map<std::string, std::string> cloudViewer::visualization::map_visualizer_docstrings static
Initial value:
= {
                {"callback_func", "The call back function."},
                {"depth_scale",
                 "Scale depth value when capturing the depth image."},
                {"do_render", "Set to ``True`` to do render."},
                {"filename", "Path to file."},
                {"geometry", "The ``Geometry`` object."},
                {"height", "Height of window."},
                {"left", "Left margin of the window to the screen."},
                {"top", "Top margin of the window to the screen."},
                {"visible", "Whether the window is visible."},
                {"width", "Width of the window."},
                {"window_name", "Window title name."},
                {"convert_to_world_coordinate",
                 "Set to ``True`` to convert to world coordinates"},
                {"reset_bounding_box",
                 "Set to ``False`` to keep current viewpoint"}}
Definition at line 24 of file visualizer.cpp.
Referenced by pybind_visualizer().
MODEL_NAME
const std::string cloudViewer::visualization::MODEL_NAME = "__model__"
Definition at line 298 of file GuiVisualizer.cpp.
Referenced by cloudViewer::visualization::GuiVisualizer::Impl::SetBasicModeGeometry(), cloudViewer::visualization::GuiVisualizer::SetGeometry(), and cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().
WIREFRAME_NAME
const std::string cloudViewer::visualization::WIREFRAME_NAME = "__wireframe_model__"
Definition at line 300 of file GuiVisualizer.cpp.
Referenced by cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel().