ACloudViewer: PdmsTools::PdmsToken Namespace Reference
PdmsTools::PdmsToken Namespace Reference
Functions
static bool isCommand (Token t)
static bool isDesignElement (Token t)
static bool isGroupElement (Token t)
static bool isElement (Token t)
static bool isCoordinate (Token t)
static bool isParameter (Token t)
static bool isSpaceSystem (Token t)
static bool isUnit (Token t)
Function Documentation
isCommand()
static bool PdmsTools::PdmsToken::isCommand (Token t) static
Definition at line 113 of file PdmsTools.h.
References PdmsTools::PDMS_NAME, and PdmsTools::PDMS_RETURN.
isCoordinate()
static bool PdmsTools::PdmsToken::isCoordinate (Token t) static
Definition at line 123 of file PdmsTools.h.
References PdmsTools::PDMS_EST, and PdmsTools::PDMS_Z.
Referenced by PdmsTools::PdmsCommands::Coordinates::getNbComponents(), PdmsTools::PdmsCommands::Coordinates::handle(), PdmsTools::PdmsCommands::Position::handle(), PdmsTools::PdmsCommands::Orientation::handle(), and PdmsTools::PdmsCommands::Orientation::isValid().
isDesignElement()
static bool PdmsTools::PdmsToken::isDesignElement (Token t) static
Definition at line 114 of file PdmsTools.h.
References PdmsTools::PDMS_SCYLINDER, and PdmsTools::PDMS_VERTEX.
Referenced by PdmsTools::PdmsCommands::Reference::execute(), isElement(), and PdmsTools::PdmsObjects::GroupElement::push().
isElement()
static bool PdmsTools::PdmsToken::isElement (Token t) static
Definition at line 120 of file PdmsTools.h.
References isDesignElement(), and isGroupElement().
Referenced by PdmsTools::PdmsCommands::Reference::handle(), PdmsTools::PdmsCommands::ElementCreation::handle(), and PdmsTools::PdmsCommands::ElementCreation::isValid().
isGroupElement()
static bool PdmsTools::PdmsToken::isGroupElement (Token t) static
Definition at line 117 of file PdmsTools.h.
References PdmsTools::PDMS_GROUP, and PdmsTools::PDMS_SUBSTRUCTURE.
Referenced by PdmsTools::PdmsCommands::Reference::execute(), isElement(), PdmsTools::PdmsCommands::HierarchyNavigation::isValid(), and PdmsTools::PdmsObjects::GroupElement::push().
isParameter()
static bool PdmsTools::PdmsToken::isParameter (Token t) static
Definition at line 124 of file PdmsTools.h.
References PdmsTools::PDMS_BOTTOM_DIAMETER, and PdmsTools::PDMS_DIAMETER.
isSpaceSystem()
static bool PdmsTools::PdmsToken::isSpaceSystem (Token t) static
Definition at line 127 of file PdmsTools.h.
References PdmsTools::PDMS_ORIENTATION, and PdmsTools::PDMS_POSITION.
isUnit()
static bool PdmsTools::PdmsToken::isUnit (Token t) static
Definition at line 130 of file PdmsTools.h.
References PdmsTools::PDMS_METRE, and PdmsTools::PDMS_MILLIMETRE.
Referenced by PdmsTools::PdmsCommands::DistanceValue::handle().