ACloudViewer: ccCompassImport Namespace Reference
ccCompassImport Namespace Reference
Functions
void importFoliations (ecvMainAppInterface *app)
void importLineations (ecvMainAppInterface *app)
Function Documentation
importFoliations()
void ccCompassImport::importFoliations (ecvMainAppInterface * app)
Definition at line 95 of file ccCompassImport.cpp.
References abs(), ccHObject::addChild(), ccHObject::applyGLTransformation_recursive(), ccNormalVectors::ConvertDipAndDipDirToNormal(), cloudViewer::DegreesToRadians(), Vector3Tpl< Type >::dot(), ccGLMatrixTpl< float >::FromToRotation(), ccPlane::getCenter(), ccPlane::getNormal(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::PointCloudTpl< T >::getScalarField(), ccGLMatrixTpl< T >::getTranslationAsVec3D(), ccGLMatrixTpl< T >::initFromParameters(), PC_ONE, CV_TYPES::POINT_CLOUD, result, ccGLMatrixTpl< T >::setTranslation(), ccPlane::setXWidth(), ccPlane::setYWidth(), ccDrawableObject::showNameIn3D(), cloudViewer::PointCloudTpl< T >::size(), size, and Tuple3Tpl< Type >::z.
importLineations()
void ccCompassImport::importLineations (ecvMainAppInterface * app)
Definition at line 209 of file ccCompassImport.cpp.
References ccHObject::addChild(), cloudViewer::ReferenceCloud::addPointIndex(), cloudViewer::DegreesToRadians(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::PointCloudTpl< T >::getScalarField(), CV_TYPES::POINT_CLOUD, points, result, ccObject::setName(), cloudViewer::PointCloudTpl< T >::size(), size, and ccLineation::updateMetadata().