ACloudViewer: flann::serialization Namespace Reference
flann::serialization Namespace Reference
Classes
struct access
struct Serializer
struct Serializer< char >
struct Serializer< unsigned char >
struct Serializer< short >
struct Serializer< unsigned short >
struct Serializer< int >
struct Serializer< unsigned int >
struct Serializer< long >
struct Serializer< unsigned long >
struct Serializer< unsigned long long >
struct Serializer< float >
struct Serializer< double >
struct Serializer< bool >
struct Serializer< std::vector< T > >
struct Serializer< std::map< K, V > >
struct Serializer< T * >
struct Serializer< T[N]>
struct binary_object
struct Serializer< const binary_object >
struct Serializer< binary_object >
struct bool_
class ArchiveBase
class InputArchive
class OutputArchive
class SizeArchive
class SaveArchive
class LoadArchive
Functions
ENUM_SERIALIZER (flann_algorithm_t)
ENUM_SERIALIZER (flann_centers_init_t)
ENUM_SERIALIZER (flann_log_level_t)
ENUM_SERIALIZER (flann_datatype_t)
template<typename Archive , typename T >
void serialize (Archive &ar, T &type)
const binary_object make_binary_object (void *t, size_t size)
Function Documentation
ENUM_SERIALIZER() [1/4]
flann::serialization::ENUM_SERIALIZER (flann_algorithm_t)
ENUM_SERIALIZER() [2/4]
flann::serialization::ENUM_SERIALIZER (flann_centers_init_t)
ENUM_SERIALIZER() [3/4]
flann::serialization::ENUM_SERIALIZER (flann_datatype_t)
ENUM_SERIALIZER() [4/4]
flann::serialization::ENUM_SERIALIZER (flann_log_level_t)
make_binary_object()
const binary_object flann::serialization::make_binary_object (void * t, size_t size) inline
Definition at line 229 of file serialization.h.
References size.
Referenced by flann::NNIndex< Distance >::serialize(), and flann::Matrix_::serialize().
serialize()
template<typename Archive , typename T > void flann::serialization::serialize (Archive & ar, T & type) inline
Definition at line 40 of file serialization.h.
References flann::serialization::access::serialize(), and type.
Referenced by flann::serialization::Serializer< T >::load(), and flann::serialization::Serializer< T >::save().