ACloudViewer: colmap::mvs Namespace Reference
colmap::mvs Namespace Reference
Namespaces
internal
Classes
class ConsistencyGraph
class CudaArrayLayeredTexture
class DepthMap
struct StereoFusionOptions
class StereoFusion
class GpuMat
class GpuMatPRNG
class GpuMatRefImage
struct BilateralWeightComputer
class Image
class Mat
struct PoissonMeshingOptions
struct DelaunayMeshingOptions
struct Model
class NormalMap
struct PatchMatchOptions
class PatchMatch
class PatchMatchController
class PatchMatchCuda
struct TexturePatchCandidate
struct TextureView
struct TexturePatch
class MvsTexturing
class Workspace
class CachedWorkspace
Functions
template<typename T >
void CudaFlipHorizontal (const T *input, T *output, const int width, const int height, const int pitch_input, const int pitch_output)
template<typename T >
void CudaRotate (const T *input, T *output, const int width, const int height, const int pitch_input, const int pitch_output)
template<typename T >
void CudaTranspose (const T *input, T *output, const int width, const int height, const int pitch_input, const int pitch_output)
void WritePointsVisibility (const std::string &path, const std::vector< std::vector< int >> &points_visibility)
void ComputeRelativePose (const float R1[9], const float T1[3], const float R2[9], const float T2[3], float R[9], float T[3])
void ComposeProjectionMatrix (const float K[9], const float R[9], const float T[3], float P[12])
void ComposeInverseProjectionMatrix (const float K[9], const float R[9], const float T[3], float inv_P[12])
void ComputeProjectionCenter (const float R[9], const float T[3], float C[3])
void RotatePose (const float RR[9], float R[9], float T[3])
bool PoissonMeshing (const PoissonMeshingOptions &options, const std::string &input_path, const std::string &output_path)
static TexturePatchCandidate GenerateCandidate (int label, TextureView *texture_view, const std::vector< size_t > &faces, const ccMesh &mesh, ccPointCloud *cloud, bool mesh_is_shifted=false)
void ImportPMVSWorkspace (const Workspace &workspace, const std::string &option_name)
Variables
static const size_t kMaxPatchMatchWindowRadius = 32
Function Documentation
ComposeInverseProjectionMatrix()
void colmap::mvs::ComposeInverseProjectionMatrix (const float K[9], const float R[9], const float T[3], float inv_P[12])
Definition at line 115 of file image.cc.
References ComposeProjectionMatrix().
Referenced by colmap::mvs::Image::Rescale().
ComposeProjectionMatrix()
void colmap::mvs::ComposeProjectionMatrix (const float K[9], const float R[9], const float T[3], float P[12])
Definition at line 106 of file image.cc.
Referenced by ComposeInverseProjectionMatrix(), and colmap::mvs::Image::Rescale().
ComputeProjectionCenter()
void colmap::mvs::ComputeProjectionCenter (const float R[9], const float T[3], float C[3])
Definition at line 125 of file image.cc.
Referenced by colmap::mvs::Model::ComputeTriangulationAngles().
ComputeRelativePose()
void colmap::mvs::ComputeRelativePose (const float R1[9], const float T1[3], const float R2[9], const float T2[3], float R[9], float T[3])
Definition at line 92 of file image.cc.
CudaFlipHorizontal()
template<typename T > void colmap::mvs::CudaFlipHorizontal (const T * input, T * output, const int width, const int height, const int pitch_input, const int pitch_output)
CudaRotate()
template<typename T > void colmap::mvs::CudaRotate (const T * input, T * output, const int width, const int height, const int pitch_input, const int pitch_output)
CudaTranspose()
template<typename T > void colmap::mvs::CudaTranspose (const T * input, T * output, const int width, const int height, const int pitch_input, const int pitch_output)
GenerateCandidate()
static TexturePatchCandidate colmap::mvs::GenerateCandidate (int label, TextureView * texture_view, const std::vector< size_t > & faces, const ccMesh & mesh, ccPointCloud * cloud, bool mesh_is_shifted = false) static
Definition at line 1074 of file texturing.cc.
References cloudViewer::utility::ceil(), colmap::ExistsFile(), cloudViewer::utility::floor(), colmap::mvs::TextureView::GetPixelCoords(), cloudViewer::PointCloudTpl< T >::getPoint(), ccMesh::getTriangleVertIndexes(), height, colmap::mvs::TextureView::height, colmap::mvs::TextureView::image_data, colmap::mvs::TextureView::image_file, colmap::mvs::TexturePatchCandidate::max_x, colmap::mvs::TexturePatchCandidate::max_y, colmap::mvs::TexturePatchCandidate::min_x, colmap::mvs::TexturePatchCandidate::min_y, offset, colmap::StringPrintf(), colmap::mvs::TexturePatchCandidate::texture_patch, ccShiftedObject::toGlobal3d(), width, colmap::mvs::TextureView::width, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
ImportPMVSWorkspace()
void colmap::mvs::ImportPMVSWorkspace (const Workspace & workspace, const std::string & option_name)
Definition at line 227 of file workspace.cc.
References colmap::CreateDirIfNotExists(), QtCompat::endl(), colmap::mvs::Model::GetImageName(), colmap::mvs::Model::GetMaxOverlappingImagesFromPMVS(), colmap::mvs::Workspace::GetModel(), colmap::mvs::Workspace::GetOptions(), colmap::JoinPaths(), colmap::ReadTextFileLines(), colmap::mvs::Workspace::Options::stereo_folder, colmap::StringSplit(), colmap::StringStartsWith(), and colmap::mvs::Workspace::Options::workspace_path.
PoissonMeshing()
bool colmap::mvs::PoissonMeshing (const PoissonMeshingOptions & options, const std::string & input_path, const std::string & output_path)
Definition at line 123 of file meshing.cc.
References colmap::mvs::PoissonMeshingOptions::Check(), colmap::mvs::PoissonMeshingOptions::color, colmap::mvs::PoissonMeshingOptions::depth, colmap::mvs::PoissonMeshingOptions::num_threads, colmap::mvs::PoissonMeshingOptions::point_weight, patch::to_string(), and colmap::mvs::PoissonMeshingOptions::trim.
Referenced by colmap::AutomaticReconstructionController::RunDenseMapper(), and colmap::RunPoissonMesher().
RotatePose()
void colmap::mvs::RotatePose (const float RR[9], float R[9], float T[3])
Definition at line 132 of file image.cc.
WritePointsVisibility()
void colmap::mvs::WritePointsVisibility (const std::string & path, const std::vector< std::vector< int >> & points_visibility)
Definition at line 635 of file fusion.cc.
References cloudViewer::t::geometry::path.
Referenced by colmap::AutomaticReconstructionController::RunDenseMapper(), and colmap::RunStereoFuser().
Variable Documentation
kMaxPatchMatchWindowRadius
const size_t colmap::mvs::kMaxPatchMatchWindowRadius = 32 static
Definition at line 28 of file patch_match.h.
Referenced by colmap::mvs::PatchMatchOptions::Check().