ACloudViewer: cloudViewer::utility::filesystem Namespace Reference
cloudViewer::utility::filesystem Namespace Reference
Classes
class CFile
Functions
template<typename... T>
std::string JoinPaths (T const &...paths)
std::string JoinPath (const std::vector< std::string > &path_components)
std::string JoinPath (const std::string &path_component1, const std::string &path_component2)
std::string GetEnvVar (const std::string &env_var)
std::string GetHomeDirectory ()
Get the HOME directory for the user.
std::string EnsureTrailingSlash (const std::string &str)
bool HasFileExtension (const std::string &file_name, const std::string &ext)
void SplitFileExtension (const std::string &path, std::string *root, std::string *ext)
bool CopyFile (const std::string &from, const std::string &to)
Copy a file.
bool CopyDir (const std::string &from, const std::string &to)
Copy a directory.
bool CopyA (const std::string &src_path, const std::string &dst_path)
bool Copy (const std::string &from, const std::string &to, bool include_parent_dir=false, const std::string &extname="")
Copy a file or directory.
std::string GetFileExtensionInLowerCase (const std::string &filename)
std::string GetFileNameWithoutExtension (const std::string &filename)
std::string GetFileNameWithoutDirectory (const std::string &filename)
std::string GetFileParentDirectory (const std::string &filename)
std::string GetRegularizedDirectoryName (const std::string &directory)
std::string GetFileBaseName (const std::string &filename)
std::string GetWorkingDirectory ()
std::vector< std::string > GetPathComponents (const std::string &path)
std::string GetTempDirectoryPath ()
bool ChangeWorkingDirectory (const std::string &directory)
bool IsFile (const std::string &filename)
bool IsDirectory (const std::string &directory)
bool DirectoryExists (const std::string &directory)
bool DirectoryIsEmpty (const std::string &directory)
bool EnsureDirectory (const std::string &directory_path)
Check if a specified directory specified by directory_path exists. If not, recursively create the directory (and its parents).
bool MakeDirectory (const std::string &directory)
bool MakeDirectoryHierarchy (const std::string &directory)
bool DeleteDirectory (const std::string &directory)
bool FileExists (const std::string &filename)
bool RemoveFile (const std::string &filename)
bool ListDirectory (const std::string &directory, std::vector< std::string > &subdirs, std::vector< std::string > &filenames)
bool ListFilesInDirectory (const std::string &directory, std::vector< std::string > &filenames)
bool ListFilesInDirectoryWithExtension (const std::string &directory, const std::string &extname, std::vector< std::string > &filenames)
std::vector< std::string > FindFilesRecursively (const std::string &directory, std::function< bool(const std::string &)> is_match)
FILE * FOpen (const std::string &filename, const std::string &mode)
std::string GetIOErrorString (const int errnoVal)
bool FReadToBuffer (const std::string &path, std::vector< char > &bytes, std::string *errorStr)
std::string AddIfExist (const std::string &path, const std::vector< std::string > &folder_names)
Function Documentation
AddIfExist()
std::string cloudViewer::utility::filesystem::AddIfExist (const std::string & path, const std::vector< std::string > & folder_names)
ChangeWorkingDirectory()
bool cloudViewer::utility::filesystem::ChangeWorkingDirectory (const std::string & directory)
Referenced by cloudViewer::visualization::gui::FileDialog::OnDone().
Copy()
bool cloudViewer::utility::filesystem::Copy (const std::string & from, const std::string & to, bool include_parent_dir = false, const std::string & extname = "")
Copy a file or directory.
Parameters
from The path to copy from.
to The path to copy to.
include_parent_dir Whether copy parent directory or not.
Returns
If the action is successful.
Referenced by cloudViewer::data::DownloadDataset::DownloadDataset().
CopyA()
bool cloudViewer::utility::filesystem::CopyA (const std::string & src_path, const std::string & dst_path)
CopyDir()
bool cloudViewer::utility::filesystem::CopyDir (const std::string & from, const std::string & to)
Copy a directory.
Parameters
from The path to copy from [Note: not including 'from' folder].
to The path to copy to.
Returns
If the action is successful.
CopyFile()
bool cloudViewer::utility::filesystem::CopyFile (const std::string & from, const std::string & to)
Copy a file.
Parameters
from The file path to copy from.
to The file path to copy to.
Returns
If the action is successful.
DeleteDirectory()
bool cloudViewer::utility::filesystem::DeleteDirectory (const std::string & directory)
DirectoryExists()
bool cloudViewer::utility::filesystem::DirectoryExists (const std::string & directory)
Referenced by cloudViewer::data::DownloadDataset::DownloadDataset(), cloudViewer::utility::DownloadFromURL(), cloudViewer::utility::Extract(), cloudViewer::data::DownloadDataset::HasDownloaded(), cloudViewer::t::io::RealSenseSensor::InitSensor(), cloudViewer::pipelines::color_map::RunNonRigidOptimizer(), cloudViewer::visualization::gui::Application::RunOneTick(), cloudViewer::pipelines::color_map::RunRigidOptimizer(), cloudViewer::saveArrayToFile(), cloudViewer::visualization::gui::FileDialog::SetPath(), and cloudViewer::visualization::rendering::EngineInstance::SetResourcePath().
DirectoryIsEmpty()
bool cloudViewer::utility::filesystem::DirectoryIsEmpty (const std::string & directory)
EnsureDirectory()
bool cloudViewer::utility::filesystem::EnsureDirectory (const std::string & directory_path)
Check if a specified directory specified by directory_path exists. If not, recursively create the directory (and its parents).
Parameters
directory_path Directory path.
Returns
If the directory does exist or its creation is successful.
EnsureTrailingSlash()
std::string cloudViewer::utility::filesystem::EnsureTrailingSlash (const std::string & str)
FileExists()
bool cloudViewer::utility::filesystem::FileExists (const std::string & filename)
Referenced by cloudViewer::data::Dataset::CheckPathsExist(), cloudViewer::utility::DownloadFromURL(), cloudViewer::utility::Extract(), cloudViewer::t::pipelines::slac::FillInRigidAlignmentTerm(), cloudViewer::t::pipelines::slac::FillInSLACAlignmentTerm(), cloudViewer::visualization::gui::FindFontPath(), cloudViewer::utility::GetMD5(), cloudViewer::data::DownloadDataset::HasDownloaded(), cloudViewer::visualization::gui::Application::Initialize(), cloudViewer::t::io::RealSenseSensor::InitSensor(), cloudViewer::t::pipelines::slac::PreprocessPointClouds(), cloudViewer::visualization::gui::Application::RunOneTick(), cloudViewer::t::pipelines::slac::SaveCorrespondencesForPointClouds(), and cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetIBL().
FindFilesRecursively()
std::vector<std::string> cloudViewer::utility::filesystem::FindFilesRecursively (const std::string & directory, std::function< bool(const std::string &)> is_match)
Referenced by cloudViewer::visualization::gui::FindFontPath().
FOpen()
FILE* cloudViewer::utility::filesystem::FOpen (const std::string & filename, const std::string & mode)
Referenced by cloudViewer::t::io::ReadImageFromJPG(), cloudViewer::io::ReadPointCloudFromPCD(), cloudViewer::t::io::ReadPointCloudFromPCD(), cloudViewer::io::ReadTriangleMeshFromSTL(), cloudViewer::t::io::WriteImageToJPG(), cloudViewer::io::WritePointCloudToPCD(), and cloudViewer::t::io::WritePointCloudToPCD().
FReadToBuffer()
bool cloudViewer::utility::filesystem::FReadToBuffer (const std::string & path, std::vector< char > & bytes, std::string * errorStr)
Referenced by cloudViewer::visualization::rendering::FilamentResourceManager::CreateIndirectLight(), cloudViewer::visualization::rendering::FilamentResourceManager::CreateMaterial(), cloudViewer::visualization::rendering::FilamentResourceManager::CreateSkybox(), and cloudViewer::visualization::gui::LoadMaterialTemplate().
GetEnvVar()
std::string cloudViewer::utility::filesystem::GetEnvVar (const std::string & env_var)
GetFileBaseName()
std::string cloudViewer::utility::filesystem::GetFileBaseName (const std::string & filename)
GetFileExtensionInLowerCase()
std::string cloudViewer::utility::filesystem::GetFileExtensionInLowerCase (const std::string & filename)
Referenced by cloudViewer::utility::Extract(), cloudViewer::visualization::gui::FindFontPath(), cloudViewer::utility::IsSupportedCompressedFilePath(), cloudViewer::io::ReadFileGeometryType(), cloudViewer::io::ReadImageWarpingField(), cloudViewer::io::ReadPointCloud(), cloudViewer::t::io::ReadPointCloud(), cloudViewer::t::io::ReadPointCloudFromTXT(), cloudViewer::io::ReadPoseGraph(), cloudViewer::io::ReadTriangleMesh(), cloudViewer::t::io::ReadTriangleMesh(), cloudViewer::io::ReadTriangleMeshFromGLTF(), cloudViewer::t::geometry::VoxelBlockGrid::Save(), cloudViewer::visualization::gui::FileDialog::Impl::UpdateDirectoryListing(), cloudViewer::t::io::WriteHashMap(), cloudViewer::t::io::WriteImage(), cloudViewer::io::WriteImageWarpingField(), cloudViewer::io::WritePointCloud(), cloudViewer::t::io::WritePointCloud(), cloudViewer::t::io::WritePointCloudToTXT(), cloudViewer::io::WritePoseGraph(), cloudViewer::io::WriteTriangleMesh(), cloudViewer::t::io::WriteTriangleMesh(), and cloudViewer::io::WriteTriangleMeshToGLTF().
GetFileNameWithoutDirectory()
std::string cloudViewer::utility::filesystem::GetFileNameWithoutDirectory (const std::string & filename)
Referenced by cloudViewer::data::DownloadDataset::DownloadDataset(), cloudViewer::utility::DownloadFromMirrors(), cloudViewer::utility::DownloadFromURL(), cloudViewer::visualization::gui::FindFontPath(), cloudViewer::visualization::visualizer::O3DVisualizer::Impl::GetListOfIBLs(), cloudViewer::visualization::GuiSettingsView::GuiSettingsView(), cloudViewer::data::DownloadDataset::HasDownloaded(), cloudViewer::io::LoadTextures(), cloudViewer::t::pipelines::slac::PreprocessPointClouds(), cloudViewer::visualization::gui::FileDialog::Impl::UpdateDirectoryListing(), and cloudViewer::io::WriteTriangleMeshToOBJ().
GetFileNameWithoutExtension()
std::string cloudViewer::utility::filesystem::GetFileNameWithoutExtension (const std::string & filename)
Referenced by cloudViewer::visualization::gui::FindFontPath(), cloudViewer::visualization::VisualizerWithEditing::SaveCroppingResult(), and cloudViewer::io::WriteTriangleMeshToOBJ().
GetFileParentDirectory()
std::string cloudViewer::utility::filesystem::GetFileParentDirectory (const std::string & filename)
Referenced by cloudViewer::visualization::gui::FindFontPath(), cloudViewer::t::io::RealSenseSensor::InitSensor(), cloudViewer::io::LoadTextures(), cloudViewer::io::ReadTriangleMeshFromOBJ(), and cloudViewer::saveArrayToFile().
GetHomeDirectory()
std::string cloudViewer::utility::filesystem::GetHomeDirectory ()
Get the HOME directory for the user.
The home directory is determined in the following order:
On Unix:
$HOME
/
On Windows:
USERPROFILE%
HOMEDRIVE%
HOMEPATH%
HOME%
C:/
This is the same logics as used in Qt.
src/corelib/io/qfilesystemengine_win.cpp
src/corelib/io/qfilesystemengine_unix.cpp
Referenced by cloudViewer::data::LocateDataRoot().
GetIOErrorString()
std::string cloudViewer::utility::filesystem::GetIOErrorString (const int errnoVal)
GetPathComponents()
std::vector<std::string> cloudViewer::utility::filesystem::GetPathComponents (const std::string & path)
Referenced by cloudViewer::visualization::gui::FileDialog::SetPath().
GetRegularizedDirectoryName()
std::string cloudViewer::utility::filesystem::GetRegularizedDirectoryName (const std::string & directory)
GetTempDirectoryPath()
std::string cloudViewer::utility::filesystem::GetTempDirectoryPath ()
GetWorkingDirectory()
std::string cloudViewer::utility::filesystem::GetWorkingDirectory ()
Referenced by cloudViewer::visualization::gui::Application::Initialize().
HasFileExtension()
bool cloudViewer::utility::filesystem::HasFileExtension (const std::string & file_name, const std::string & ext)
IsDirectory()
bool cloudViewer::utility::filesystem::IsDirectory (const std::string & directory)
IsFile()
bool cloudViewer::utility::filesystem::IsFile (const std::string & filename)
JoinPath() [1/2]
std::string cloudViewer::utility::filesystem::JoinPath (const std::string & path_component1, const std::string & path_component2)
JoinPath() [2/2]
std::string cloudViewer::utility::filesystem::JoinPath (const std::vector< std::string > & path_components)
JoinPaths()
template<typename... T> std::string cloudViewer::utility::filesystem::JoinPaths (T const &... paths)
Definition at line 23 of file FileSystem.h.
References result, cloudViewer::utility::StringContains(), cloudViewer::utility::StringEndsWith(), cloudViewer::utility::StringReplace(), and cloudViewer::utility::StringReplaceLast().
ListDirectory()
bool cloudViewer::utility::filesystem::ListDirectory (const std::string & directory, std::vector< std::string > & subdirs, std::vector< std::string > & filenames)
Referenced by cloudViewer::visualization::gui::FileDialog::Impl::UpdateDirectoryListing().
ListFilesInDirectory()
bool cloudViewer::utility::filesystem::ListFilesInDirectory (const std::string & directory, std::vector< std::string > & filenames)
Referenced by cloudViewer::visualization::visualizer::O3DVisualizer::Impl::GetListOfIBLs(), and cloudViewer::visualization::GuiSettingsView::GuiSettingsView().
ListFilesInDirectoryWithExtension()
bool cloudViewer::utility::filesystem::ListFilesInDirectoryWithExtension (const std::string & directory, const std::string & extname, std::vector< std::string > & filenames)
MakeDirectory()
bool cloudViewer::utility::filesystem::MakeDirectory (const std::string & directory)
Referenced by cloudViewer::t::pipelines::slac::PreprocessPointClouds(), cloudViewer::t::pipelines::slac::RunRigidOptimizerForFragments(), and cloudViewer::t::pipelines::slac::RunSLACOptimizerForFragments().
MakeDirectoryHierarchy()
bool cloudViewer::utility::filesystem::MakeDirectoryHierarchy (const std::string & directory)
Referenced by cloudViewer::data::DownloadDataset::DownloadDataset(), cloudViewer::utility::DownloadFromURL(), cloudViewer::utility::Extract(), cloudViewer::utility::ExtractCurrentFile(), cloudViewer::t::io::RealSenseSensor::InitSensor(), cloudViewer::visualization::VisualizerWithCustomAnimation::Play(), cloudViewer::pipelines::color_map::RunNonRigidOptimizer(), cloudViewer::pipelines::color_map::RunRigidOptimizer(), cloudViewer::saveArrayToFile(), and cloudViewer::t::io::RGBDVideoReader::SaveFrames().
RemoveFile()
bool cloudViewer::utility::filesystem::RemoveFile (const std::string & filename)
SplitFileExtension()
void cloudViewer::utility::filesystem::SplitFileExtension (const std::string & path, std::string * root, std::string * ext)