ACloudViewer: ccEntityAction Namespace Reference
ccEntityAction Namespace Reference
Enumerations
enum class NORMAL_CONVERSION_DEST { HSV_COLORS , DIP_DIR_SFS }
Normals conversion destinations.
enum class CLEAR_PROPERTY { COLORS = 0 , NORMALS , CURRENT_SCALAR_FIELD , ALL_SCALAR_FIELDS }
enum class TOGGLE_PROPERTY {
ACTIVE = 0 , VISIBLE , COLOR , NORMALS ,
SCALAR_FIELD , MATERIAL , NAME
}
Functions
static QString GetFirstAvailableSFName (const ccPointCloud *cloud, const QString &baseName)
bool setColor (ccHObject::Container selectedEntities, bool colorize, QWidget *parent)
bool rgbToGreyScale (const ccHObject::Container &selectedEntities)
bool setColorGradient (const ccHObject::Container &selectedEntities, QWidget *parent)
bool changeColorLevels (const ccHObject::Container &selectedEntities, QWidget *parent)
bool interpolateColors (const ccHObject::Container &selectedEntities, QWidget *parent)
Interpolate colors from on entity and transfer them to another one.
bool interpolateSFs (const ccHObject::Container &selectedEntities, ecvMainAppInterface *app)
Interpolate scalar fields from on entity and transfer them to another one.
bool convertTextureToColor (const ccHObject::Container &selectedEntities, QWidget *parent)
bool enhanceRGBWithIntensities (const ccHObject::Container &selectedEntities, QWidget *parent)
bool rgbGaussianFilter (const ccHObject::Container &selectedEntities, ccPointCloud::RgbFilterOptions filterParams, QWidget *parent)
bool sfGaussianFilter (const ccHObject::Container &selectedEntities, ccPointCloud::RgbFilterOptions filterParams, QWidget *parent)
bool sfBilateralFilter (const ccHObject::Container &selectedEntities, QWidget *parent)
bool sfConvertToRGB (const ccHObject::Container &selectedEntities, QWidget *parent)
bool sfConvertToRandomRGB (const ccHObject::Container &selectedEntities, QWidget *parent)
bool sfRename (const ccHObject::Container &selectedEntities, QWidget *parent)
bool sfAddIdField (const ccHObject::Container &selectedEntities)
bool importToSF (const ccHObject::Container &selectedEntities, const std::vector< std::vector< ScalarType >> &scalarsVector, const std::string &name)
static PointCoordinateType GetDefaultValueForNaN (PointCoordinateType minSFValue, QWidget *parent)
bool sfSetAsCoord (const ccHObject::Container &selectedEntities, QWidget *parent)
bool exportCoordToSF (const ccHObject::Container &selectedEntities, QWidget *parent)
bool exportNormalToSF (const ccHObject::Container &selectedEntities, QWidget *parent, bool *exportDimensions)
bool sfArithmetic (const ccHObject::Container &selectedEntities, QWidget *parent)
bool sfFromColor (const ccHObject::Container &selectedEntities, QWidget *parent)
bool processMeshSF (const ccHObject::Container &selectedEntities, ccMesh::MESH_SCALAR_FIELD_PROCESS process, QWidget *parent)
bool computeNormals (const ccHObject::Container &selectedEntities, QWidget *parent)
bool invertNormals (const ccHObject::Container &selectedEntities)
bool orientNormalsFM (const ccHObject::Container &selectedEntities, QWidget *parent)
bool orientNormalsMST (const ccHObject::Container &selectedEntities, QWidget *parent)
bool convertNormalsTo (const ccHObject::Container &selectedEntities, NORMAL_CONVERSION_DEST dest)
Converts a cloud's normals.
bool computeOctree (const ccHObject::Container &selectedEntities, QWidget *parent)
bool clearProperty (ccHObject::Container selectedEntities, CLEAR_PROPERTY property, QWidget *parent)
bool toggleProperty (const ccHObject::Container &selectedEntities, TOGGLE_PROPERTY property)
bool statisticalTest (const ccHObject::Container &selectedEntities, QWidget *parent)
bool computeStatParams (const ccHObject::Container &selectedEntities, QWidget *parent)
bool DBScanCluster (const ccHObject::Container &selectedEntities, QWidget *parent)
bool RansacSegmentation (const ccHObject::Container &selectedEntities, ccHObject::Container &outEntities, QWidget *parent)
bool ConvexHull (const ccHObject::Container &selectedEntities, ccHObject::Container &outEntities, QWidget *parent)
bool VoxelSampling (const ccHObject::Container &selectedEntities, ccHObject::Container &outEntities, QWidget *parent)
template<typename T >
void ConvertToScalarType (const std::vector< std::vector< T >> &inputScalars, std::vector< std::vector< ScalarType >> &outputScalars)
Enumeration Type Documentation
CLEAR_PROPERTY
enum ccEntityAction::CLEAR_PROPERTY strong
Enumerator
COLORS
NORMALS
CURRENT_SCALAR_FIELD
ALL_SCALAR_FIELDS
Definition at line 103 of file ecvEntityAction.h.
NORMAL_CONVERSION_DEST
enum ccEntityAction::NORMAL_CONVERSION_DEST strong
Normals conversion destinations.
Enumerator
HSV_COLORS
DIP_DIR_SFS
Definition at line 93 of file ecvEntityAction.h.
TOGGLE_PROPERTY
enum ccEntityAction::TOGGLE_PROPERTY strong
Enumerator
ACTIVE
VISIBLE
COLOR
NORMALS
SCALAR_FIELD
MATERIAL
NAME
Definition at line 113 of file ecvEntityAction.h.
Function Documentation
changeColorLevels()
bool ccEntityAction::changeColorLevels (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 264 of file ecvEntityAction.cpp.
References ecvUtils::DisplayLockedVerticesWarning(), CVLog::Error(), ccObject::getName(), ccPointCloud::hasColors(), and ccHObjectCaster::ToPointCloud().
clearProperty()
bool ccEntityAction::clearProperty (ccHObject::Container selectedEntities, CLEAR_PROPERTY property, QWidget * parent)
Definition at line 2200 of file ecvEntityAction.cpp.
References ALL_SCALAR_FIELDS, ccMesh::clearTriNormals(), COLORS, CURRENT_SCALAR_FIELD, ecvUtils::DisplayLockedVerticesWarning(), ccMesh::getAssociatedCloud(), ccHObject::getParent(), ccDrawableObject::hasColors(), ccDrawableObject::hasDisplayedScalarField(), ccDrawableObject::hasNormals(), ccMesh::hasNormals(), ccDrawableObject::hasScalarFields(), ccMesh::hasTriNormals(), ccObject::isA(), CV_TYPES::MESH, NORMALS, CV_TYPES::POINT_CLOUD, MainWindow::putObjectBackIntoDBTree(), MainWindow::removeObjectTemporarilyFromDBTree(), ccDrawableObject::setRedraw(), ccGenericMesh::showNormals(), ccHObjectCaster::ToGenericPointCloud(), ccHObjectCaster::ToMesh(), and CVLog::Warning().
computeNormals()
bool ccEntityAction::computeNormals (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 1570 of file ecvEntityAction.cpp.
References cloudViewer::PointCloudTpl< T >::addPoint(), ccGLMatrixTpl< T >::data(), CVLog::Error(), ccSensor::getActiveAbsoluteCenter(), ccHObject::getChild(), ccHObject::getChildrenNumber(), ccNormalComputationDlg::getLocalModel(), ccNormalComputationDlg::getMinGridAngle_deg(), ccNormalComputationDlg::getMSTNeighborCount(), ccNormalComputationDlg::getPreferredOrientation(), ccNormalComputationDlg::getRadius(), ccPointCloud::gridCount(), ccNormalVectors::GuessNaiveRadius(), ccPointCloud::hasSensor(), ccGLMatrixTpl< T >::inverse(), ccObject::isKindOf(), LS, CV_TYPES::MESH, ccNormalComputationDlg::orientNormals(), orientNormalsMST(), CV_TYPES::POINT_CLOUD, MainWindow::putObjectBackIntoDBTree(), MainWindow::removeObjectTemporarilyFromDBTree(), ccPointCloud::reserve(), result, CV_TYPES::SENSOR, ccNormalComputationDlg::setCloud(), ccNormalComputationDlg::setLocalModel(), ccNormalComputationDlg::setMinGridAngle_deg(), ccNormalComputationDlg::setMSTNeighborCount(), ccNormalComputationDlg::setPreferredOrientation(), ccNormalComputationDlg::setRadius(), ccHObjectCaster::ToMesh(), ccHObjectCaster::ToSensor(), ccNormalVectors::UNDEFINED, ccNormalComputationDlg::useMSTOrientation(), ccNormalComputationDlg::useScanGridsForComputation(), ccNormalComputationDlg::useScanGridsForOrientation(), and ccNormalComputationDlg::useSensorsForOrientation().
Referenced by ccMesh::SamplePointsUniformlyImpl(), and ecvPoissonReconDlg::start().
computeOctree()
bool ccEntityAction::computeOctree (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 2072 of file ecvEntityAction.cpp.
References cloudViewer::DgmOctree::build(), cloudViewer::DgmOctree::clear(), ccComputeOctreeDlg::CUSTOM_BBOX, ccComputeOctreeDlg::DEFAULT, ecvUtils::DisplayLockedVerticesWarning(), ccComputeOctreeDlg::getCustomBBox(), ccComputeOctreeDlg::getMinCellSize(), ccComputeOctreeDlg::getMode(), ccGenericPointCloud::getOwnBB(), cloudViewer::BoundingBoxTpl< T >::isValid(), cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, cloudViewer::BoundingBoxTpl< T >::maxCorner(), ccComputeOctreeDlg::MIN_CELL_SIZE, cloudViewer::BoundingBoxTpl< T >::minCorner(), octree, CVLog::Print(), MainWindow::putObjectBackIntoDBTree(), MainWindow::removeObjectTemporarilyFromDBTree(), ecvDisplayTools::SetRedrawRecursive(), ccDrawableObject::setVisible(), ccHObjectCaster::ToGenericPointCloud(), CVLog::Warning(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
computeStatParams()
bool ccEntityAction::computeStatParams (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 2493 of file ecvEntityAction.cpp.
References a, ccPickOneElementDlg::addElement(), cloudViewer::utility::ceil(), cloudViewer::StatisticalTestingTools::computeAdaptativeChi2Dist(), cloudViewer::WeibullDistribution::computeMode(), cloudViewer::GenericDistribution::computeParameters(), cloudViewer::WeibullDistribution::computeSkewness(), cloudViewer::ScalarField::countValidValues(), ecvGui::ParamStruct::displayedNumPrecision, ccHistogramWindow::fromBinArray(), ccScalarField::getColorScale(), ccPointCloud::getCurrentDisplayedScalarField(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), cloudViewer::ScalarField::getName(), ccObject::getName(), cloudViewer::GenericDistribution::getName(), cloudViewer::WeibullDistribution::getParameters(), cloudViewer::PointCloudTpl< T >::getPointScalarValue(), ccPickOneElementDlg::getSelectedIndex(), cloudViewer::WeibullDistribution::getValueShift(), normal, ecvGui::Parameters(), CVLog::Print(), ccHistogramWindow::refresh(), ccHistogramWindow::setAxisLabels(), ccHistogramWindow::setColorScale(), ccHistogramWindow::setColorScheme(), ccHistogramWindow::setCurveValues(), ccPickOneElementDlg::setDefaultIndex(), ccHistogramWindow::setTitle(), cloudViewer::PointCloudTpl< T >::size(), ccHObjectCaster::ToPointCloud(), ccHistogramWindow::USE_CUSTOM_COLOR_SCALE, cloudViewer::ScalarField::ValidValue(), CVLog::Warning(), and ccHistogramWindowDlg::window().
convertNormalsTo()
bool ccEntityAction::convertNormalsTo (const ccHObject::Container & selectedEntities, NORMAL_CONVERSION_DEST dest)
Converts a cloud's normals.
Definition at line 1951 of file ecvEntityAction.cpp.
References ccPointCloud::addScalarField(), CC_DEFAULT_DIP_DIR_SF_NAME, CC_DEFAULT_DIP_SF_NAME, ccPointCloud::convertNormalToDipDirSFs(), ccPointCloud::convertNormalToRGB(), ccPointCloud::deleteScalarField(), ccColorScalesManager::DIP_BRYW, DIP_DIR_SFS, ecvUtils::DisplayLockedVerticesWarning(), CVLog::Error(), ccColorScalesManager::GetDefaultScale(), ccObject::getName(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), ccPointCloud::hasNormals(), HSV_COLORS, ccObject::isA(), CV_TYPES::POINT_CLOUD, ccScalarField::setColorScale(), ccPointCloud::setCurrentDisplayedScalarField(), ccDrawableObject::showColors(), ccDrawableObject::showNormals(), ccDrawableObject::showSF(), ccHObjectCaster::ToGenericPointCloud(), and CVLog::Warning().
Referenced by CommandConvertNormalsToDipAndDipDir::process().
convertTextureToColor()
bool ccEntityAction::convertTextureToColor (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 468 of file ecvEntityAction.cpp.
References ccMesh::convertMaterialsToVertexColors(), ccObject::getName(), ccMesh::hasColors(), ccMesh::hasMaterials(), ccDrawableObject::showColors(), ccGenericMesh::showMaterials(), ccDrawableObject::showSF(), ccHObjectCaster::ToMesh(), and CVLog::Warning().
ConvertToScalarType()
template<typename T > void ccEntityAction::ConvertToScalarType (const std::vector< std::vector< T >> & inputScalars, std::vector< std::vector< ScalarType >> & outputScalars)
Definition at line 21 of file ecvEntityAction.h.
ConvexHull()
bool ccEntityAction::ConvexHull (const ccHObject::Container & selectedEntities, ccHObject::Container & outEntities, QWidget * parent)
Definition at line 2794 of file ecvEntityAction.cpp.
References ccHObject::addChild(), ccPointCloud::ComputeConvexHull(), ecvUtils::DisplayLockedVerticesWarning(), ccObject::getName(), ccHObject::getParent(), ccObject::setName(), ccHObjectCaster::ToPointCloud(), and CVLog::Warning().
DBScanCluster()
bool ccEntityAction::DBScanCluster (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 2675 of file ecvEntityAction.cpp.
References ccPointCloud::ClusterDBSCAN(), ccPointCloud::ComputeResolution(), ecvUtils::DisplayLockedVerticesWarning(), CVLog::Error(), ccObject::getName(), importToSF(), CVLog::Print(), and ccHObjectCaster::ToPointCloud().
enhanceRGBWithIntensities()
bool ccEntityAction::enhanceRGBWithIntensities (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 514 of file ecvEntityAction.cpp.
References ccPickOneElementDlg::addElement(), QtCompatRegExpOption::CaseInsensitive, ecvUtils::DisplayLockedVerticesWarning(), ccPointCloud::enhanceRGBWithIntensitySF(), cloudViewer::ScalarField::getName(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), ccPickOneElementDlg::getSelectedIndex(), ccPointCloud::hasColors(), ccPointCloud::hasScalarFields(), ccPickOneElementDlg::setDefaultIndex(), ccHObjectCaster::ToPointCloud(), and CVLog::Warning().
exportCoordToSF()
bool ccEntityAction::exportCoordToSF (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 1304 of file ecvEntityAction.cpp.
References CVLog::Error(), ccPointCloud::exportCoordToSF(), ccExportCoordToSFDlg::exportX(), ccExportCoordToSFDlg::exportY(), ccExportCoordToSFDlg::exportZ(), and ccHObjectCaster::ToPointCloud().
exportNormalToSF()
bool ccEntityAction::exportNormalToSF (const ccHObject::Container & selectedEntities, QWidget * parent, bool * exportDimensions)
Definition at line 1341 of file ecvEntityAction.cpp.
References CVLog::Error(), ccPointCloud::exportNormalToSF(), ccExportCoordToSFDlg::exportX(), ccExportCoordToSFDlg::exportY(), ccExportCoordToSFDlg::exportZ(), ccObject::getName(), ccPointCloud::hasNormals(), ccHObjectCaster::ToPointCloud(), and CVLog::Warning().
Referenced by CommandConvertNormalsToSFs::process().
GetDefaultValueForNaN()
static PointCoordinateType ccEntityAction::GetDefaultValueForNaN (PointCoordinateType minSFValue, QWidget * parent) static
Definition at line 1240 of file ecvEntityAction.cpp.
Referenced by sfSetAsCoord().
GetFirstAvailableSFName()
static QString ccEntityAction::GetFirstAvailableSFName (const ccPointCloud * cloud, const QString & baseName) static
Definition at line 68 of file ecvEntityAction.cpp.
References cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), and name.
Referenced by sfFromColor().
importToSF()
bool ccEntityAction::importToSF (const ccHObject::Container & selectedEntities, const std::vector< std::vector< ScalarType >> & scalarsVector, const std::string & name)
Definition at line 1195 of file ecvEntityAction.cpp.
References ccPointCloud::addScalarField(), cloudViewer::ScalarField::computeMinAndMax(), cloudViewer::ScalarField::currentSize(), ccObject::getName(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), name, ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::ScalarField::setValue(), ccDrawableObject::showSF(), cloudViewer::GenericCloud::size(), cloudViewer::PointCloudTpl< T >::size(), ccHObjectCaster::ToPointCloud(), and CVLog::Warning().
Referenced by DBScanCluster(), ecvAnnotationsTool::exportAnnotationToSF(), and ecvPoissonReconDlg::start().
interpolateColors()
bool ccEntityAction::interpolateColors (const ccHObject::Container & selectedEntities, QWidget * parent)
Interpolate colors from on entity and transfer them to another one.
Definition at line 292 of file ecvEntityAction.cpp.
References CVLog::Error(), ccDrawableObject::hasColors(), ccObject::isA(), CV_TYPES::POINT_CLOUD, ccHObject::setRedrawFlagRecursive(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), std::swap(), and ccHObjectCaster::ToGenericPointCloud().
Referenced by ccRasterizeTool::convertGridToCloud(), cc2Point5DimEditor::convertGridToCloud(), and ccRasterGrid::convertToCloud().
interpolateSFs()
bool ccEntityAction::interpolateSFs (const ccHObject::Container & selectedEntities, ecvMainAppInterface * app)
Interpolate scalar fields from on entity and transfer them to another one.
Definition at line 352 of file ecvEntityAction.cpp.
References ccPointCloudInterpolator::Parameters::algo, CVLog::Error(), cloudViewer::BoundingBoxTpl< T >::getDiagNormd(), ccOrderChoiceDlg::getFirstEntity(), ccInterpolationDlg::getInterpolationAlgorithm(), ccInterpolationDlg::getInterpolationMethod(), ecvMainAppInterface::getMainWindow(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), ccGenericPointCloud::getOwnBB(), cloudViewer::PointCloudTpl< T >::getScalarFieldName(), ccItemSelectionDlg::getSelectedIndexes(), ccPointCloud::hasScalarFields(), ccPointCloudInterpolator::InterpolateScalarFieldsFrom(), ccPointCloudInterpolator::Parameters::knn, ccPointCloudInterpolator::Parameters::method, ccPointCloudInterpolator::Parameters::NORMAL_DIST, ccPointCloudInterpolator::Parameters::RADIUS, ccPointCloudInterpolator::Parameters::radius, ccPointCloud::setCurrentDisplayedScalarField(), ccInterpolationDlg::setInterpolationAlgorithm(), ccInterpolationDlg::setInterpolationMethod(), ccItemSelectionDlg::setItems(), ccHObject::setRedrawFlagRecursive(), ccDrawableObject::showSF(), ccPointCloudInterpolator::Parameters::sigma, std::swap(), and ccHObjectCaster::ToPointCloud().
Referenced by ccRasterizeTool::updateGrid().
invertNormals()
bool ccEntityAction::invertNormals (const ccHObject::Container & selectedEntities)
Definition at line 1818 of file ecvEntityAction.cpp.
References ecvUtils::DisplayLockedVerticesWarning(), ccMesh::hasNormals(), ccPointCloud::hasNormals(), ccMesh::invertNormals(), ccPointCloud::invertNormals(), ccDrawableObject::showNormals(), ccGenericMesh::showNormals(), ccHObjectCaster::ToMesh(), and ccHObjectCaster::ToPointCloud().
orientNormalsFM()
bool ccEntityAction::orientNormalsFM (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 1847 of file ecvEntityAction.cpp.
References CVLog::Error(), ccObject::getName(), ccPointCloud::hasNormals(), cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, ccPointCloud::orientNormalsWithFM(), CV_TYPES::POINT_CLOUD, and CVLog::Warning().
orientNormalsMST()
bool ccEntityAction::orientNormalsMST (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 1899 of file ecvEntityAction.cpp.
References CVLog::Error(), ccObject::getName(), ccPointCloud::hasNormals(), ccPointCloud::orientNormalsWithMST(), CV_TYPES::POINT_CLOUD, and CVLog::Warning().
Referenced by computeNormals().
processMeshSF()
bool ccEntityAction::processMeshSF (const ccHObject::Container & selectedEntities, ccMesh::MESH_SCALAR_FIELD_PROCESS process, QWidget * parent)
Definition at line 1532 of file ecvEntityAction.cpp.
References cloudViewer::ScalarField::computeMinAndMax(), ccMesh::getAssociatedCloud(), ccPointCloud::getCurrentDisplayedScalarFieldIndex(), cloudViewer::PointCloudTpl< T >::getCurrentInScalarField(), ccObject::getName(), ccObject::isA(), CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, CV_TYPES::PRIMITIVE, ccMesh::processScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentScalarField(), ccHObjectCaster::ToMesh(), and CVLog::Warning().
RansacSegmentation()
bool ccEntityAction::RansacSegmentation (const ccHObject::Container & selectedEntities, ccHObject::Container & outEntities, QWidget * parent)
Definition at line 2732 of file ecvEntityAction.cpp.
References ccHObject::addChild(), ecvUtils::DisplayLockedVerticesWarning(), ccPointCloud::From(), ccObject::getName(), ccHObject::getParent(), CVLog::Print(), ccPointCloud::SegmentPlane(), ccObject::setEnabled(), ccObject::setName(), and ccHObjectCaster::ToPointCloud().
rgbGaussianFilter()
bool ccEntityAction::rgbGaussianFilter (const ccHObject::Container & selectedEntities, ccPointCloud::RgbFilterOptions filterParams, QWidget * parent)
Definition at line 610 of file ecvEntityAction.cpp.
References ccPointCloud::addScalarField(), ccPointCloud::applyFilterToRGB(), ccPointCloud::RgbFilterOptions::applyToSFduringRGB, ccPointCloud::RgbFilterOptions::burntOutColorThreshold, ccPointCloud::RgbFilterOptions::commandLine, cloudViewer::ScalarField::computeMinAndMax(), ccGenericPointCloud::computeOctree(), ecvUtils::DisplayLockedVerticesWarning(), CVLog::Error(), ccPointCloud::RgbFilterOptions::filterType, ccPointCloud::getCurrentDisplayedScalarField(), ccPointCloud::getCurrentDisplayedScalarFieldIndex(), cloudViewer::PointCloudTpl< T >::getCurrentOutScalarField(), ccLibAlgorithms::GetDefaultCloudKernelSize(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), cloudViewer::ScalarField::getName(), ccObject::getName(), ccGenericPointCloud::getOctree(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), ccPointCloud::hasColors(), ccPointCloud::hasDisplayedScalarField(), octree, CVLog::Print(), ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentInScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentOutScalarField(), ccDrawableObject::showSF(), ccPointCloud::RgbFilterOptions::sigmaSF, ccPointCloud::RgbFilterOptions::spatialSigma, and ccHObjectCaster::ToPointCloud().
rgbToGreyScale()
bool ccEntityAction::rgbToGreyScale (const ccHObject::Container & selectedEntities)
Definition at line 185 of file ecvEntityAction.cpp.
References ccPointCloud::convertRGBToGreyScale(), ecvUtils::DisplayLockedVerticesWarning(), ccPointCloud::hasColors(), ccObject::isA(), CV_TYPES::POINT_CLOUD, ccHObject::setRedrawFlagRecursive(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), and ccHObjectCaster::ToGenericPointCloud().
setColor()
bool ccEntityAction::setColor (ccHObject::Container selectedEntities, bool colorize, QWidget * parent)
Definition at line 89 of file ecvEntityAction.cpp.
References ecvDisplayTools::ChangeEntityProperties(), ccPointCloud::colorize(), CV_TYPES::FACET, ecvColor::FromQColor(), ccMesh::getAssociatedCloud(), ccHObject::getChild(), ccHObject::getChildrenNumber(), ccPolyline::getColor(), ccObject::getName(), ccHObject::getParent(), CV_TYPES::HIERARCHY_OBJECT, ccObject::isA(), ccHObject::isAncestorOf(), cloudViewer::Polyline::isClosed(), ccObject::isKindOf(), ccObject::isLocked(), CV_TYPES::MESH, CV_TYPES::POINT_CLOUD, CV_TYPES::POLY_LINE, CV_TYPES::PRIMITIVE, ecvDisplayTools::RedrawDisplay(), ccGenericPrimitive::setColor(), ccPolyline::setColor(), ccFacet::setColor(), ccHObject::setRedrawFlagRecursive(), ecvDisplayTools::SetRedrawRecursive(), ccPointCloud::setRGBColor(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), ccHObjectCaster::ToFacet(), ccHObjectCaster::ToPolyline(), ccHObjectCaster::ToPrimitive(), CVLog::Warning(), and ecvColor::white().
Referenced by DistanceMapGenerationDlg::overlayGridColorChanged(), ccFacet::PaintUniformColor(), and ccPolyline::PaintUniformColor().
setColorGradient()
bool ccEntityAction::setColorGradient (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 210 of file ecvEntityAction.cpp.
References ccColorGradientDlg::Banding, ccColorScale::Create(), ccColorGradientDlg::Default, ecvUtils::DisplayLockedVerticesWarning(), ccColorGradientDlg::getBandingFrequency(), ccColorGradientDlg::getColors(), ccColorScalesManager::GetDefaultScale(), ccColorGradientDlg::getDimension(), ccColorGradientDlg::getType(), ccObject::isA(), CV_TYPES::POINT_CLOUD, ccPointCloud::setRGBColorByBanding(), ccPointCloud::setRGBColorByHeight(), ccHObjectCaster::ToGenericPointCloud(), and ccColorGradientDlg::TwoColors.
sfAddIdField()
bool ccEntityAction::sfAddIdField (const ccHObject::Container & selectedEntities)
Definition at line 1164 of file ecvEntityAction.cpp.
References ccPointCloud::addScalarField(), CC_DEFAULT_ID_SF_NAME, cloudViewer::ScalarField::computeMinAndMax(), cloudViewer::ScalarField::currentSize(), cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::ScalarField::setValue(), ccDrawableObject::showSF(), cloudViewer::GenericCloud::size(), cloudViewer::PointCloudTpl< T >::size(), ccHObjectCaster::ToPointCloud(), and CVLog::Warning().
sfArithmetic()
bool ccEntityAction::sfArithmetic (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 1396 of file ecvEntityAction.cpp.
References ccScalarFieldArithmeticsDlg::apply(), ecvUtils::DisplayLockedVerticesWarning(), CVLog::Error(), ccObject::getName(), ccDrawableObject::showSF(), and ccHObjectCaster::ToPointCloud().
sfBilateralFilter()
bool ccEntityAction::sfBilateralFilter (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 1013 of file ecvEntityAction.cpp.
References ccPointCloud::RgbFilterOptions::filterType, and sfGaussianFilter().
sfConvertToRandomRGB()
bool ccEntityAction::sfConvertToRandomRGB (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 1063 of file ecvEntityAction.cpp.
References ccArray< Type, N, ComponentType >::addElement(), cloudViewer::ScalarField::currentSize(), ecvUtils::DisplayLockedVerticesWarning(), CVLog::Error(), ccPointCloud::getCurrentDisplayedScalarField(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), ccArray< Type, N, ComponentType >::getValue(), cloudViewer::ScalarField::getValue(), ecvColor::Generator::Random(), ccArray< Type, N, ComponentType >::reserveSafe(), ccPointCloud::resizeTheRGBTable(), ccPointCloud::setPointColor(), ccHObject::setRedrawFlagRecursive(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), cloudViewer::PointCloudTpl< T >::size(), and ccHObjectCaster::ToPointCloud().
sfConvertToRGB()
bool ccEntityAction::sfConvertToRGB (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 1020 of file ecvEntityAction.cpp.
References ecvUtils::DisplayLockedVerticesWarning(), ccPointCloud::getCurrentDisplayedScalarField(), ccPointCloud::setRGBColorWithCurrentScalarField(), ccDrawableObject::showColors(), and ccHObjectCaster::ToPointCloud().
sfFromColor()
bool ccEntityAction::sfFromColor (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 1426 of file ecvEntityAction.cpp.
References count, fields, ccScalarFieldFromColorDlg::getBStatus(), ccScalarFieldFromColorDlg::getCompositeStatus(), GetFirstAvailableSFName(), ccScalarFieldFromColorDlg::getGStatus(), ccScalarFieldFromColorDlg::getRStatus(), ccPointCloud::hasColors(), CV_TYPES::MESH, CVLog::Print(), rgb, ccHObjectCaster::ToPointCloud(), and CVLog::Warning().
sfGaussianFilter()
bool ccEntityAction::sfGaussianFilter (const ccHObject::Container & selectedEntities, ccPointCloud::RgbFilterOptions filterParams, QWidget * parent)
Definition at line 829 of file ecvEntityAction.cpp.
References ccPointCloud::addScalarField(), cloudViewer::ScalarFieldTools::applyScalarFieldGaussianFilter(), ccPointCloud::RgbFilterOptions::commandLine, cloudViewer::ScalarField::computeMinAndMax(), ccGenericPointCloud::computeOctree(), ecvUtils::DisplayLockedVerticesWarning(), CVLog::Error(), ccPointCloud::RgbFilterOptions::filterType, ccPointCloud::getCurrentDisplayedScalarField(), ccPointCloud::getCurrentDisplayedScalarFieldIndex(), cloudViewer::PointCloudTpl< T >::getCurrentInScalarField(), cloudViewer::PointCloudTpl< T >::getCurrentOutScalarField(), ccLibAlgorithms::GetDefaultCloudKernelSize(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), cloudViewer::ScalarField::getName(), ccObject::getName(), ccGenericPointCloud::getOctree(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), octree, CVLog::Print(), result, ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentInScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentOutScalarField(), ecvProgressDialog::setInfo(), ecvProgressDialog::setMethodTitle(), ccDrawableObject::showSF(), ccPointCloud::RgbFilterOptions::sigmaSF, ccPointCloud::RgbFilterOptions::spatialSigma, ecvProgressDialog::start(), ccHObjectCaster::ToPointCloud(), and CVLog::Warning().
Referenced by sfBilateralFilter().
sfRename()
bool ccEntityAction::sfRename (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 1138 of file ecvEntityAction.cpp.
References ccPointCloud::getCurrentDisplayedScalarField(), cloudViewer::ScalarField::getName(), ccObject::getName(), cloudViewer::ScalarField::setName(), ccHObjectCaster::ToPointCloud(), and CVLog::Warning().
sfSetAsCoord()
bool ccEntityAction::sfSetAsCoord (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 1258 of file ecvEntityAction.cpp.
References cloudViewer::ScalarField::countValidValues(), ccExportCoordToSFDlg::exportX(), ccExportCoordToSFDlg::exportY(), ccExportCoordToSFDlg::exportZ(), ccPointCloud::getCurrentDisplayedScalarField(), GetDefaultValueForNaN(), cloudViewer::ScalarField::getMin(), ccPointCloud::invalidateBoundingBox(), ccObject::isA(), CV_TYPES::MESH, NAN_VALUE, CV_TYPES::POINT_CLOUD, ccPointCloud::setCoordFromSF(), and ccHObjectCaster::ToGenericPointCloud().
statisticalTest()
bool ccEntityAction::statisticalTest (const ccHObject::Container & selectedEntities, QWidget * parent)
Definition at line 2341 of file ecvEntityAction.cpp.
References a, ccPickOneElementDlg::addElement(), ccPointCloud::addScalarField(), CC_CHI2_DISTANCES_DEFAULT_SF_NAME, ccScalarField::computeMinAndMax(), ccGenericPointCloud::computeOctree(), CVLog::Error(), ccPointCloud::getCurrentDisplayedScalarField(), ccPointCloud::getCurrentDisplayedScalarFieldIndex(), cloudViewer::PointCloudTpl< T >::getCurrentInScalarField(), ccObject::getName(), cloudViewer::GenericDistribution::getName(), ccStatisticalTestDlg::getNeighborsNumber(), ccGenericPointCloud::getOctree(), ccStatisticalTestDlg::getParam1(), ccStatisticalTestDlg::getParam2(), ccStatisticalTestDlg::getParam3(), ccStatisticalTestDlg::getProba(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), ccPickOneElementDlg::getSelectedIndex(), CVLog::Print(), ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentInScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentOutScalarField(), ccPickOneElementDlg::setDefaultIndex(), ccScalarField::setMinDisplayed(), cloudViewer::NormalDistribution::setParameters(), cloudViewer::WeibullDistribution::setParameters(), ccScalarField::setSaturationStart(), ccScalarField::setSymmetricalScale(), ccDrawableObject::showSF(), cloudViewer::StatisticalTestingTools::testCloudWithStatisticalModel(), and ccHObjectCaster::ToPointCloud().
toggleProperty()
bool ccEntityAction::toggleProperty (const ccHObject::Container & selectedEntities, TOGGLE_PROPERTY property)
Definition at line 2303 of file ecvEntityAction.cpp.
References ACTIVE, COLOR, ConvertToGroup(), ccHObject::DP_NONE, ccHObject::getChild(), ccHObject::getChildrenNumber(), NAME, NORMALS, SCALAR_FIELD, ccObject::toggleActivation(), ccHObject::toggleColors_recursive(), ccHObject::toggleNormals_recursive(), ccHObject::toggleSF_recursive(), ccHObject::toggleShowName_recursive(), ccHObject::toggleVisibility_recursive(), and VISIBLE.
VoxelSampling()
bool ccEntityAction::VoxelSampling (const ccHObject::Container & selectedEntities, ccHObject::Container & outEntities, QWidget * parent)
Definition at line 2836 of file ecvEntityAction.cpp.
References ccPointCloud::ComputeResolution(), ecvUtils::DisplayLockedVerticesWarning(), and ccHObjectCaster::ToPointCloud().