ACloudViewer: pba Namespace Reference
pba Namespace Reference
Namespaces
ProgramCPU
ProgramCU
Classes
class ConfigBA
class CuTexImage
struct CameraT_
struct Point3D_
struct Point2D
class ParallelBA
class avec
class SparseBundleCPU
class SparseBundleCU
Typedefs
typedef CameraT_< float > CameraT
typedef Point3D_< float > Point3D
typedef ParallelBA *(* NEWPARALLELBAPROC) (ParallelBA::DeviceT)
typedef float float_t
Functions
ParallelBA * NewParallelBA (ParallelBA::DeviceT device)
int ParallelBA_GetVersion ()
ParallelBA * NewSparseBundleCPU (bool dp, const int num_threads)
static size_t upgrade_dimension (size_t sz)
bool LoadModelFile (const char *name, vector< CameraT > &camera_data, vector< Point3D > &point_data, vector< Point2D > &measurements, vector< int > &ptidx, vector< int > &camidx, vector< string > &names, vector< int > &ptc)
void SaveNVM (const char *filename, vector< CameraT > &camera_data, vector< Point3D > &point_data, vector< Point2D > &measurements, vector< int > &ptidx, vector< int > &camidx, vector< string > &names, vector< int > &ptc)
void SaveBundlerModel (const char *filename, vector< CameraT > &camera_data, vector< Point3D > &point_data, vector< Point2D > &measurements, vector< int > &ptidx, vector< int > &camidx)
void AddNoise (vector< CameraT > &camera_data, vector< Point3D > &point_data, float percent)
void AddStableNoise (vector< CameraT > &camera_data, vector< Point3D > &point_data, const vector< int > &ptidx, const vector< int > &camidx, float percent)
bool RemoveInvisiblePoints (vector< CameraT > &camera_data, vector< Point3D > &point_data, vector< int > &ptidx, vector< int > &camidx, vector< Point2D > &measurements, vector< string > &names, vector< int > &ptc)
bool LoadNVM (ifstream &in, vector< CameraT > &camera_data, vector< Point3D > &point_data, vector< Point2D > &measurements, vector< int > &ptidx, vector< int > &camidx, vector< string > &names, vector< int > &ptc)
bool LoadBundlerOut (const char *name, ifstream &in, vector< CameraT > &camera_data, vector< Point3D > &point_data, vector< Point2D > &measurements, vector< int > &ptidx, vector< int > &camidx, vector< string > &names, vector< int > &ptc)
void SaveBundlerOut (const char *filename, vector< CameraT > &camera_data, vector< Point3D > &point_data, vector< Point2D > &measurements, vector< int > &ptidx, vector< int > &camidx, vector< string > &names, vector< int > &ptc)
template<class CameraT , class Point3D >
bool LoadBundlerModel (ifstream &in, vector< CameraT > &camera_data, vector< Point3D > &point_data, vector< Point2D > &measurements, vector< int > &ptidx, vector< int > &camidx)
float random_ratio (float percent)
void ExamineVisiblity (const char *input_filename)
void SaveModelFile (const char *outpath, vector< CameraT > &camera_data, vector< Point3D > &point_data, vector< Point2D > &measurements, vector< int > &ptidx, vector< int > &camidx, vector< string > &names, vector< int > &ptc)
Typedef Documentation
CameraT
typedef CameraT_<float> pba::CameraT
Definition at line 398 of file DataInterface.h.
float_t
typedef float pba::float_t
Definition at line 48 of file SparseBundleCU.cpp.
NEWPARALLELBAPROC
typedef ParallelBA*(* pba::NEWPARALLELBAPROC) (ParallelBA::DeviceT)
Definition at line 148 of file pba.h.
Point3D
typedef Point3D_<float> pba::Point3D
Definition at line 399 of file DataInterface.h.
Function Documentation
AddNoise()
void pba::AddNoise (vector< CameraT > & camera_data, vector< Point3D > & point_data, float percent)
Definition at line 419 of file util.h.
References NULL, and random_ratio().
AddStableNoise()
void pba::AddStableNoise (vector< CameraT > & camera_data, vector< Point3D > & point_data, const vector< int > & ptidx, const vector< int > & camidx, float percent)
Definition at line 442 of file util.h.
References pba::CameraT_< FT >::f, pba::CameraT_< FT >::GetCameraCenter(), pba::CameraT_< FT >::GetRodriguesRotation(), pba::CameraT_< FT >::m, NULL, random_ratio(), pba::CameraT_< FT >::SetCameraCenterAfterRotation(), pba::CameraT_< FT >::SetRodriguesRotation(), pba::CameraT_< FT >::t, and pba::Point3D_< FT >::xyz.
ExamineVisiblity()
void pba::ExamineVisiblity (const char * input_filename)
Definition at line 544 of file util.h.
LoadBundlerModel()
template<class CameraT , class Point3D > bool pba::LoadBundlerModel (ifstream & in, vector< CameraT > & camera_data, vector< Point3D > & point_data, vector< Point2D > & measurements, vector< int > & ptidx, vector< int > & camidx)
Definition at line 313 of file util.h.
LoadBundlerOut()
bool pba::LoadBundlerOut (const char * name, ifstream & in, vector< CameraT > & camera_data, vector< Point3D > & point_data, vector< Point2D > & measurements, vector< int > & ptidx, vector< int > & camidx, vector< string > & names, vector< int > & ptc)
Definition at line 177 of file util.h.
LoadModelFile()
bool pba::LoadModelFile (const char * name, vector< CameraT > & camera_data, vector< Point3D > & point_data, vector< Point2D > & measurements, vector< int > & ptidx, vector< int > & camidx, vector< string > & names, vector< int > & ptc)
Definition at line 394 of file util.h.
References name, and NULL.
LoadNVM()
bool pba::LoadNVM (ifstream & in, vector< CameraT > & camera_data, vector< Point3D > & point_data, vector< Point2D > & measurements, vector< int > & ptidx, vector< int > & camidx, vector< string > & names, vector< int > & ptc)
Definition at line 60 of file util.h.
NewParallelBA()
ParallelBA * pba::NewParallelBA (ParallelBA::DeviceT device)
Definition at line 128 of file pba.cpp.
NewSparseBundleCPU()
ParallelBA * pba::NewSparseBundleCPU (bool dp, const int num_threads)
Definition at line 4360 of file SparseBundleCPU.cpp.
Referenced by pba::ParallelBA::ParallelBA().
ParallelBA_GetVersion()
int pba::ParallelBA_GetVersion ()
Definition at line 132 of file pba.cpp.
random_ratio()
float pba::random_ratio (float percent)
Definition at line 415 of file util.h.
Referenced by AddNoise(), and AddStableNoise().
RemoveInvisiblePoints()
bool pba::RemoveInvisiblePoints (vector< CameraT > & camera_data, vector< Point3D > & point_data, vector< int > & ptidx, vector< int > & camidx, vector< Point2D > & measurements, vector< string > & names, vector< int > & ptc)
modified model.
Definition at line 608 of file util.h.
References pba::CameraT_< FT >::m, pba::CameraT_< FT >::t, and pba::Point3D_< FT >::xyz.
SaveBundlerModel()
void pba::SaveBundlerModel (const char * filename, vector< CameraT > & camera_data, vector< Point3D > & point_data, vector< Point2D > & measurements, vector< int > & ptidx, vector< int > & camidx)
Definition at line 365 of file util.h.
Referenced by SaveModelFile().
SaveBundlerOut()
void pba::SaveBundlerOut (const char * filename, vector< CameraT > & camera_data, vector< Point3D > & point_data, vector< Point2D > & measurements, vector< int > & ptidx, vector< int > & camidx, vector< string > & names, vector< int > & ptc)
Definition at line 268 of file util.h.
References NULL.
Referenced by SaveModelFile().
SaveModelFile()
void pba::SaveModelFile (const char * outpath, vector< CameraT > & camera_data, vector< Point3D > & point_data, vector< Point2D > & measurements, vector< int > & ptidx, vector< int > & camidx, vector< string > & names, vector< int > & ptc)
Definition at line 737 of file util.h.
References NULL, SaveBundlerModel(), SaveBundlerOut(), and SaveNVM().
SaveNVM()
void pba::SaveNVM (const char * filename, vector< CameraT > & camera_data, vector< Point3D > & point_data, vector< Point2D > & measurements, vector< int > & ptidx, vector< int > & camidx, vector< string > & names, vector< int > & ptc)
Definition at line 135 of file util.h.
Referenced by SaveModelFile().
upgrade_dimension()
static size_t pba::upgrade_dimension (size_t sz) static
Definition at line 349 of file SparseBundleCU.cpp.
Referenced by pba::SparseBundleCU::ReserveStorageAuto().