ACloudViewer: cloudViewer::pipelines::color_map Namespace Reference
cloudViewer::pipelines::color_map Namespace Reference
Classes
class ImageWarpingField
struct NonRigidOptimizerOption
struct RigidOptimizerOption
Functions
static std::tuple< float, float, float > Project3DPointAndGetUVDepth (const Eigen::Vector3d X, const camera::PinholeCameraParameters &camera_parameter)
template<typename T >
static std::tuple< bool, T > QueryImageIntensity (const geometry::Image &img, const utility::optional< ImageWarpingField > &optional_warping_field, const Eigen::Vector3d &V, const camera::PinholeCameraParameters &camera_parameter, utility::optional< int > channel, int image_boundary_margin)
std::tuple< std::vector< geometry::Image >, std::vector< geometry::Image >, std::vector< geometry::Image >, std::vector< geometry::Image >, std::vector< geometry::Image > > CreateUtilImagesFromRGBD (const std::vector< geometry::RGBDImage > &images_rgbd)
std::vector< geometry::Image > CreateDepthBoundaryMasks (const std::vector< geometry::Image > &images_depth, double depth_threshold_for_discontinuity_check, int half_dilation_kernel_size_for_discontinuity_map)
std::tuple< std::vector< std::vector< int > >, std::vector< std::vector< int > > > CreateVertexAndImageVisibility (const ccMesh &mesh, const std::vector< geometry::Image > &images_depth, const std::vector< geometry::Image > &images_mask, const camera::PinholeCameraTrajectory &camera_trajectory, double maximum_allowable_depth, double depth_threshold_for_visibility_check)
void SetProxyIntensityForVertex (const ccMesh &mesh, const std::vector< geometry::Image > &images_gray, const utility::optional< std::vector< ImageWarpingField >> &warping_fields, const camera::PinholeCameraTrajectory &camera_trajectory, const std::vector< std::vector< int >> &visibility_vertex_to_image, std::vector< double > &proxy_intensity, int image_boundary_margin)
void SetGeometryColorAverage (ccMesh &mesh, const std::vector< geometry::Image > &images_color, const utility::optional< std::vector< ImageWarpingField >> &warping_fields, const camera::PinholeCameraTrajectory &camera_trajectory, const std::vector< std::vector< int >> &visibility_vertex_to_image, int image_boundary_margin, int invisible_vertex_color_knn)
static std::vector< ImageWarpingField > CreateWarpingFields (const std::vector< geometry::Image > &images, int number_of_vertical_anchors)
template<typename VecInTypeDouble , typename VecInTypeInt , typename MatOutType , typename VecOutType >
static std::tuple< MatOutType, VecOutType, double > ComputeJTJandJTrNonRigid (std::function< void(int, VecInTypeDouble &, double &, VecInTypeInt &)> f, int iteration_num, int nonrigidval, bool verbose)
static void ComputeJacobianAndResidualNonRigid (int row, Eigen::Vector14d &J_r, double &r, Eigen::Vector14i &pattern, const ccMesh &mesh, const std::vector< double > &proxy_intensity, const geometry::Image &images_gray, const geometry::Image &images_dx, const geometry::Image &images_dy, const ImageWarpingField &warping_fields, const Eigen::Matrix4d &intrinsic, const Eigen::Matrix4d &extrinsic, const std::vector< int > &visibility_image_to_vertex, const int image_boundary_margin)
std::pair< ccMesh, camera::PinholeCameraTrajectory > RunNonRigidOptimizer (const ccMesh &mesh, const std::vector< geometry::RGBDImage > &images_rgbd, const camera::PinholeCameraTrajectory &camera_trajectory, const NonRigidOptimizerOption &option)
static void ComputeJacobianAndResidualRigid (int row, Eigen::Vector6d &J_r, double &r, double &w, const ccMesh &mesh, const std::vector< double > &proxy_intensity, const geometry::Image &images_gray, const geometry::Image &images_dx, const geometry::Image &images_dy, const Eigen::Matrix4d &intrinsic, const Eigen::Matrix4d &extrinsic, const std::vector< int > &visibility_image_to_vertex, const int image_boundary_margin)
std::pair< ccMesh, camera::PinholeCameraTrajectory > RunRigidOptimizer (const ccMesh &mesh, const std::vector< geometry::RGBDImage > &images_rgbd, const camera::PinholeCameraTrajectory &camera_trajectory, const RigidOptimizerOption &option)
Function Documentation
ComputeJacobianAndResidualNonRigid()
static void cloudViewer::pipelines::color_map::ComputeJacobianAndResidualNonRigid (int row, Eigen::Vector14d & J_r, double & r, Eigen::Vector14i & pattern, const ccMesh & mesh, const std::vector< double > & proxy_intensity, const geometry::Image & images_gray, const geometry::Image & images_dx, const geometry::Image & images_dy, const ImageWarpingField & warping_fields, const Eigen::Matrix4d & intrinsic, const Eigen::Matrix4d & extrinsic, const std::vector< int > & visibility_image_to_vertex, const int image_boundary_margin) static
Definition at line 104 of file NonRigidOptimizer.cpp.
References cloudViewer::pipelines::color_map::ImageWarpingField::anchor_h_, cloudViewer::pipelines::color_map::ImageWarpingField::anchor_step_, cloudViewer::pipelines::color_map::ImageWarpingField::anchor_w_, cloudViewer::geometry::Image::FloatValueAt(), ccMesh::getVertice(), cloudViewer::pipelines::color_map::ImageWarpingField::QueryFlow(), and cloudViewer::geometry::Image::TestImageBoundary().
Referenced by RunNonRigidOptimizer().
ComputeJacobianAndResidualRigid()
static void cloudViewer::pipelines::color_map::ComputeJacobianAndResidualRigid (int row, Eigen::Vector6d & J_r, double & r, double & w, const ccMesh & mesh, const std::vector< double > & proxy_intensity, const geometry::Image & images_gray, const geometry::Image & images_dx, const geometry::Image & images_dy, const Eigen::Matrix4d & intrinsic, const Eigen::Matrix4d & extrinsic, const std::vector< int > & visibility_image_to_vertex, const int image_boundary_margin) static
Function to compute i-th row of J and r the vector form of J_r is basically 6x1 matrix, but it can be easily extendable to 6xn matrix. See RGBDOdometryJacobianFromHybridTerm for this case.
Definition at line 31 of file RigidOptimizer.cpp.
References cloudViewer::geometry::Image::FloatValueAt(), ccMesh::getVertice(), cloudViewer::geometry::Image::TestImageBoundary(), and uv.
Referenced by RunRigidOptimizer().
ComputeJTJandJTrNonRigid()
template<typename VecInTypeDouble , typename VecInTypeInt , typename MatOutType , typename VecOutType > static std::tuple<MatOutType, VecOutType, double> cloudViewer::pipelines::color_map::ComputeJTJandJTrNonRigid (std::function< void(int, VecInTypeDouble &, double &, VecInTypeInt &)> f, int iteration_num, int nonrigidval, bool verbose) static
Function to compute JTJ and Jtr Input: function pointer f and total number of rows of Jacobian matrix Output: JTJ, JTr, sum of r^2 Note: this function is almost identical to the functions in Utility/Eigen.h/cpp, but this function takes additional multiplication pattern that can produce JTJ having hundreds of rows and columns.
Definition at line 57 of file NonRigidOptimizer.cpp.
References LogDebug.
Referenced by RunNonRigidOptimizer().
CreateDepthBoundaryMasks()
std::vector<geometry::Image> cloudViewer::pipelines::color_map::CreateDepthBoundaryMasks (const std::vector< geometry::Image > & images_depth, double depth_threshold_for_discontinuity_check, int half_dilation_kernel_size_for_discontinuity_map)
Definition at line 104 of file ColorMapUtils.cpp.
References LogDebug.
Referenced by RunNonRigidOptimizer(), and RunRigidOptimizer().
CreateUtilImagesFromRGBD()
std::tuple<std::vector<geometry::Image>, std::vector<geometry::Image>, std::vector<geometry::Image>, std::vector<geometry::Image>, std::vector<geometry::Image> > cloudViewer::pipelines::color_map::CreateUtilImagesFromRGBD (const std::vector< geometry::RGBDImage > & images_rgbd)
Definition at line 80 of file ColorMapUtils.cpp.
References color, cloudViewer::geometry::Image::Gaussian3, cloudViewer::geometry::Image::Sobel3Dx, and cloudViewer::geometry::Image::Sobel3Dy.
Referenced by RunNonRigidOptimizer(), and RunRigidOptimizer().
CreateVertexAndImageVisibility()
std::tuple<std::vector<std::vector<int> >, std::vector<std::vector<int> > > cloudViewer::pipelines::color_map::CreateVertexAndImageVisibility (const ccMesh & mesh, const std::vector< geometry::Image > & images_depth, const std::vector< geometry::Image > & images_mask, const camera::PinholeCameraTrajectory & camera_trajectory, double maximum_allowable_depth, double depth_threshold_for_visibility_check)
Definition at line 121 of file ColorMapUtils.cpp.
References fabs(), ccMesh::getEigenVertices(), ccMesh::getVerticeSize(), LogDebug, cloudViewer::camera::PinholeCameraTrajectory::parameters_, Project3DPointAndGetUVDepth(), and X.
Referenced by RunNonRigidOptimizer(), and RunRigidOptimizer().
CreateWarpingFields()
static std::vector<ImageWarpingField> cloudViewer::pipelines::color_map::CreateWarpingFields (const std::vector< geometry::Image > & images, int number_of_vertical_anchors) static
Definition at line 34 of file NonRigidOptimizer.cpp.
References fields, height, and width.
Referenced by RunNonRigidOptimizer().
Project3DPointAndGetUVDepth()
static std::tuple<float, float, float> cloudViewer::pipelines::color_map::Project3DPointAndGetUVDepth (const Eigen::Vector3d X, const camera::PinholeCameraParameters & camera_parameter) static
Definition at line 25 of file ColorMapUtils.cpp.
References cloudViewer::camera::PinholeCameraParameters::extrinsic_, cloudViewer::camera::PinholeCameraIntrinsic::GetFocalLength(), cloudViewer::camera::PinholeCameraIntrinsic::GetPrincipalPoint(), cloudViewer::camera::PinholeCameraParameters::intrinsic_, and X.
Referenced by CreateVertexAndImageVisibility(), and QueryImageIntensity().
QueryImageIntensity()
template<typename T > static std::tuple<bool, T> cloudViewer::pipelines::color_map::QueryImageIntensity (const geometry::Image & img, const utility::optional< ImageWarpingField > & optional_warping_field, const Eigen::Vector3d & V, const camera::PinholeCameraParameters & camera_parameter, utility::optional< int > channel, int image_boundary_margin) static
Definition at line 40 of file ColorMapUtils.cpp.
References cloudViewer::utility::optional< T >::has_value(), cloudViewer::geometry::Image::PointerAt(), Project3DPointAndGetUVDepth(), cloudViewer::geometry::Image::TestImageBoundary(), and cloudViewer::utility::optional< T >::value().
RunNonRigidOptimizer()
std::pair<ccMesh, camera::PinholeCameraTrajectory> cloudViewer::pipelines::color_map::RunNonRigidOptimizer (const ccMesh & mesh, const std::vector< geometry::RGBDImage > & images_rgbd, const camera::PinholeCameraTrajectory & camera_trajectory, const NonRigidOptimizerOption & option)
Definition at line 204 of file NonRigidOptimizer.cpp.
References ComputeJacobianAndResidualNonRigid(), ComputeJTJandJTrNonRigid(), CreateDepthBoundaryMasks(), CreateUtilImagesFromRGBD(), CreateVertexAndImageVisibility(), CreateWarpingFields(), cloudViewer::pipelines::color_map::NonRigidOptimizerOption::debug_output_dir_, cloudViewer::pipelines::color_map::NonRigidOptimizerOption::depth_threshold_for_discontinuity_check_, cloudViewer::pipelines::color_map::NonRigidOptimizerOption::depth_threshold_for_visibility_check_, cloudViewer::utility::filesystem::DirectoryExists(), format, ccMesh::getVerticeSize(), cloudViewer::pipelines::color_map::NonRigidOptimizerOption::half_dilation_kernel_size_for_discontinuity_map_, cloudViewer::pipelines::color_map::NonRigidOptimizerOption::image_boundary_margin_, cloudViewer::pipelines::color_map::NonRigidOptimizerOption::invisible_vertex_color_knn_, LogDebug, LogError, LogInfo, cloudViewer::core::make_pair(), cloudViewer::utility::filesystem::MakeDirectoryHierarchy(), cloudViewer::pipelines::color_map::NonRigidOptimizerOption::maximum_allowable_depth_, cloudViewer::pipelines::color_map::NonRigidOptimizerOption::maximum_iteration_, cloudViewer::pipelines::color_map::NonRigidOptimizerOption::non_rigid_anchor_point_weight_, cloudViewer::pipelines::color_map::NonRigidOptimizerOption::number_of_vertical_anchors_, cloudViewer::camera::PinholeCameraTrajectory::parameters_, result, SetGeometryColorAverage(), SetProxyIntensityForVertex(), size, cloudViewer::utility::SolveLinearSystemPSD(), cloudViewer::utility::TransformVector6dToMatrix4d(), cloudViewer::io::WriteImage(), cloudViewer::io::WriteImageWarpingField(), cloudViewer::io::WritePinholeCameraTrajectory(), and cloudViewer::io::WriteTriangleMesh().
RunRigidOptimizer()
std::pair<ccMesh, camera::PinholeCameraTrajectory> cloudViewer::pipelines::color_map::RunRigidOptimizer (const ccMesh & mesh, const std::vector< geometry::RGBDImage > & images_rgbd, const camera::PinholeCameraTrajectory & camera_trajectory, const RigidOptimizerOption & option)
Definition at line 74 of file RigidOptimizer.cpp.
References ComputeJacobianAndResidualRigid(), cloudViewer::utility::ComputeJTJandJTr(), CreateDepthBoundaryMasks(), CreateUtilImagesFromRGBD(), CreateVertexAndImageVisibility(), cloudViewer::pipelines::color_map::RigidOptimizerOption::debug_output_dir_, cloudViewer::pipelines::color_map::RigidOptimizerOption::depth_threshold_for_discontinuity_check_, cloudViewer::pipelines::color_map::RigidOptimizerOption::depth_threshold_for_visibility_check_, cloudViewer::utility::filesystem::DirectoryExists(), format, cloudViewer::pipelines::color_map::RigidOptimizerOption::half_dilation_kernel_size_for_discontinuity_map_, cloudViewer::pipelines::color_map::RigidOptimizerOption::image_boundary_margin_, cloudViewer::pipelines::color_map::RigidOptimizerOption::invisible_vertex_color_knn_, LogDebug, LogError, LogInfo, cloudViewer::core::make_pair(), cloudViewer::utility::filesystem::MakeDirectoryHierarchy(), cloudViewer::pipelines::color_map::RigidOptimizerOption::maximum_allowable_depth_, cloudViewer::pipelines::color_map::RigidOptimizerOption::maximum_iteration_, cloudViewer::utility::nullopt, cloudViewer::camera::PinholeCameraTrajectory::parameters_, SetGeometryColorAverage(), SetProxyIntensityForVertex(), size, cloudViewer::utility::SolveJacobianSystemAndObtainExtrinsicMatrix(), cloudViewer::io::WriteImage(), cloudViewer::io::WritePinholeCameraTrajectory(), and cloudViewer::io::WriteTriangleMesh().
SetGeometryColorAverage()
void cloudViewer::pipelines::color_map::SetGeometryColorAverage (ccMesh & mesh, const std::vector< geometry::Image > & images_color, const utility::optional< std::vector< ImageWarpingField >> & warping_fields, const camera::PinholeCameraTrajectory & camera_trajectory, const std::vector< std::vector< int >> & visibility_vertex_to_image, int image_boundary_margin, int invisible_vertex_color_knn)
Definition at line 232 of file ColorMapUtils.cpp.
References ccMesh::getAssociatedCloud(), ccMesh::getVerticeSize(), LogError, ccPointCloud::resizeTheRGBTable(), ccHObjectCaster::ToPointCloud(), and ccPointCloud::unallocateColors().
Referenced by RunNonRigidOptimizer(), and RunRigidOptimizer().
SetProxyIntensityForVertex()
void cloudViewer::pipelines::color_map::SetProxyIntensityForVertex (const ccMesh & mesh, const std::vector< geometry::Image > & images_gray, const utility::optional< std::vector< ImageWarpingField >> & warping_fields, const camera::PinholeCameraTrajectory & camera_trajectory, const std::vector< std::vector< int >> & visibility_vertex_to_image, std::vector< double > & proxy_intensity, int image_boundary_margin)
Definition at line 188 of file ColorMapUtils.cpp.
References ccMesh::getVerticeSize().
Referenced by RunNonRigidOptimizer(), and RunRigidOptimizer().