ACloudViewer: std Namespace Reference
std Namespace Reference
Classes
class vector< Eigen::Vector2d, std::allocator< Eigen::Vector2d > >
class vector< Eigen::Vector4d, std::allocator< Eigen::Vector4d > >
class vector< Eigen::Vector4f, std::allocator< Eigen::Vector4f > >
class vector< Eigen::Matrix2d, std::allocator< Eigen::Matrix2d > >
class vector< Eigen::Matrix2f, std::allocator< Eigen::Matrix2f > >
class vector< Eigen::Matrix4d, std::allocator< Eigen::Matrix4d > >
class vector< Eigen::Matrix4f, std::allocator< Eigen::Matrix4f > >
class vector< Eigen::Affine3d, std::allocator< Eigen::Affine3d > >
class vector< Eigen::Affine3f, std::allocator< Eigen::Affine3f > >
class vector< Eigen::Quaterniond, std::allocator< Eigen::Quaterniond > >
class vector< Eigen::Quaternionf, std::allocator< Eigen::Quaternionf > >
class vector< Eigen::Matrix< float, 3, 4 >, std::allocator< Eigen::Matrix< float, 3, 4 > > >
class vector< Eigen::Matrix< double, 3, 4 >, std::allocator< Eigen::Matrix< double, 3, 4 > > >
struct hash< cloudViewer::utility::optional< T > >
struct hash< cloudViewer::utility::optional< T & > >
struct hash< cloudViewer::core::Device >
struct less< cloudViewer::core::Device >
struct hash< std::pair< uint32_t, uint32_t > >
Functions
template<typename T >
void swap (cloudViewer::core::SmallVectorImpl< T > &LHS, cloudViewer::core::SmallVectorImpl< T > &RHS)
Implement std::swap in terms of SmallVector swap.
template<typename T , unsigned N>
void swap (cloudViewer::core::SmallVector< T, N > &LHS, cloudViewer::core::SmallVector< T, N > &RHS)
Implement std::swap in terms of SmallVector swap.
Function Documentation
swap() [1/2]
template<typename T , unsigned N> void std::swap (cloudViewer::core::SmallVector< T, N > & LHS, cloudViewer::core::SmallVector< T, N > & RHS) inline
Implement std::swap in terms of SmallVector swap.
Definition at line 1377 of file SmallVector.h.
References cloudViewer::core::SmallVectorImpl< T >::swap().
swap() [2/2]
template<typename T > void std::swap (cloudViewer::core::SmallVectorImpl< T > & LHS, cloudViewer::core::SmallVectorImpl< T > & RHS) inline
Implement std::swap in terms of SmallVector swap.
Definition at line 1370 of file SmallVector.h.
References cloudViewer::core::SmallVectorImpl< T >::swap().
Referenced by BallPivotingEdge::AddAdjacentTriangle(), fgr::CApp::AdvancedMatching(), cloudViewer::CloudSamplingTools::applyNoiseFilterAtLevel(), ccVolumeCalcTool::ccVolumeCalcTool(), Classifier::checkRefPoints(), colmap::JobQueue< T >::Clear(), cloudViewer::DistanceComputationTools::ComputeCloud2PlaneRobustMax(), cloudViewer::t::geometry::PointCloud::ComputeConvexHull(), ComputeCorePointNormal(), cloudViewer::MeshSamplingTools::ComputeEdgeKey(), ComputeEdgePoint(), cloudViewer::GeometricalAnalysisTools::ComputeGeomCharacteristicAtLevel(), cloudViewer::t::geometry::kernel::minimum_obb::ComputeMinimumOBBJylanki(), DistanceMapGenerationTool::ComputeSurfacesAndVolumes(), ecvOrientedBBox::CreateFromPoints(), ccMesh::DeformAsRigidAsPossible(), cloudViewer::PointCloudTpl< T >::deleteScalarField(), dmat_solve(), qCork::doAction(), Eigen_Normal_Estimator::estimate_normals(), cloudViewer::DgmOctree::extractCCs(), ccContourExtractor::ExtractConcaveHull2D(), cloudViewer::geometry::TetraMesh::ExtractTriangleMesh(), cloudViewer::pipelines::registration::FastGlobalRegistrationBasedOnFeatureMatching(), ccMesh::FilterSharpen(), ccMesh::FilterSmoothLaplacian(), ccMesh::FilterSmoothSimple(), ccMesh::FilterSmoothTaubin(), cloudViewer::DgmOctree::findNearestNeighborsStartingFromCell(), cloudViewer::DgmOctree::findNeighborsInASphereStartingFromCell(), ccMesh::flipTriangles(), GenerateKey(), ccMesh::GetEigneOrderedTriangle(), ccMesh::GetOrderedTriangle(), cloudViewer::DgmOctree::getPointsInCylindricalNeighbourhoodProgressive(), ccEntityAction::interpolateColors(), ccEntityAction::interpolateSFs(), cloudViewer::SquareMatrixTpl< Scalar >::inv(), ccGLMatrixTpl< T >::invert(), colmap::TwoViewGeometry::Invert(), ObjFilter::loadFile(), ccMesh::MergeCloseVertices(), cc2DLabel::onDeletionOf(), OrientTriangleHelper(), ccMesh::OrientTriangles(), CommandICP::process(), CommandVolume25D::process(), RefinePointClassif(), cloudViewer::core::Indexer::ReorderDimensions(), MascaretFilter::saveToFile(), cloudViewer::ManualSegmentationTools::segmentMeshWithAABox(), ccPointCloud::SegmentPlane(), colmap::Shuffle(), Jacobi< Scalar >::SortEigenValuesAndVectors(), colmap::ThreadPool::Stop(), cloudViewer::SquareMatrixTpl< Scalar >::svd(), LasVlr::Swap(), cloudViewer::utility::optional< T & >::swap(), cloudViewer::utility::optional< T >::swap(), ccArray< Type, N, ComponentType >::swap(), cloudViewer::core::SmallVectorImpl< T >::swap(), cloudViewer::ScalarField::swap(), cloudViewer::ReferenceCloud::swap(), ccHObject::swapChildren(), ccAlignDlg::swapModelAndData(), ccRegistrationDlg::swapModelAndData(), cloudViewer::PointCloudTpl< T >::swapPoints(), qCanupoTools::TrainClassifier(), cloudViewer::SquareMatrixTpl< Scalar >::transpose(), ccGLMatrixTpl< T >::transpose(), and CCShareable::~CCShareable().