ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/NormalDistribution.cpp File Reference
NormalDistribution.cpp File Reference
#include <pybind11/pybind11.h>
#include <GenericCloud.h>
#include <NormalDistribution.h>
#include <iostream>
Functions
void define_NormalDistribution (py::module &cccorelib)
Function Documentation
define_NormalDistribution()
void define_NormalDistribution (py::module & cccorelib)
Definition at line 17 of file NormalDistribution.cpp.
References cloudViewer::NormalDistribution::computeParameters(), cloudViewer::NormalDistribution::computeRobustParameters(), cloudViewer::NormalDistribution::getMu(), cloudViewer::NormalDistribution::getSigma2(), cloudViewer::core::make_pair(), and cloudViewer::NormalDistribution::setParameters().
Referenced by define_cccorelib().