ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/ometis.c File Reference
ometis.c File Reference
#include "metis.h"
Functions
void METIS_EdgeND (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void GRACLUS_METIS_NodeND (int *nvtxs, idxtype *xadj, idxtype *adjncy, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void METIS_NodeWND (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, int *numflag, int *options, idxtype *perm, idxtype *iperm)
void MlevelNestedDissection (CtrlType *ctrl, GraphType *graph, idxtype *order, float ubfactor, int lastvtx)
void MlevelNestedDissectionCC (CtrlType *ctrl, GraphType *graph, idxtype *order, float ubfactor, int lastvtx)
void MlevelNodeBisectionMultiple (CtrlType *ctrl, GraphType *graph, int *tpwgts, float ubfactor)
void MlevelNodeBisection (CtrlType *ctrl, GraphType *graph, int *tpwgts, float ubfactor)
void SplitGraphOrder (CtrlType *ctrl, GraphType *graph, GraphType *lgraph, GraphType *rgraph)
void MMDOrder (CtrlType *ctrl, GraphType *graph, idxtype *order, int lastvtx)
int SplitGraphOrderCC (CtrlType *ctrl, GraphType *graph, GraphType *sgraphs, int ncmps, idxtype *cptr, idxtype *cind)
Function Documentation
GRACLUS_METIS_NodeND()
void GRACLUS_METIS_NodeND (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 79 of file ometis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumberingOrder, controldef::CoarsenTo, CompressGraph, COMPRESSION_FRACTION, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, GKfree, idxcopy, idxmalloc, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, LTERM, controldef::maxvwgt, MlevelNestedDissection(), MlevelNestedDissectionCC(), controldef::nseps, NULL, graphdef::nvtxs, OFLAG_CCMP, OFLAG_COMPRESS, controldef::oflags, ONMETIS_CTYPE, ONMETIS_DBGLVL, ONMETIS_ITYPE, ONMETIS_NSEPS, ONMETIS_OFLAGS, ONMETIS_PFACTOR, ONMETIS_RTYPE, OP_ONMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_NSEPS, OPTION_OFLAGS, OPTION_PFACTOR, OPTION_RTYPE, controldef::optype, ORDER_UNBALANCE_FRACTION, controldef::pfactor, PrintTimers, PruneGraph, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by METIS_NODEND(), metis_nodend(), metis_nodend_(), and metis_nodend__().
METIS_EdgeND()
void METIS_EdgeND (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 22 of file ometis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumberingOrder, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, controldef::maxvwgt, MlevelNestedDissection(), controldef::nseps, NULL, OEMETIS_CTYPE, OEMETIS_DBGLVL, OEMETIS_ITYPE, OEMETIS_RTYPE, controldef::oflags, OP_OEMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, ORDER_UNBALANCE_FRACTION, controldef::pfactor, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by METIS_EDGEND(), metis_edgend(), metis_edgend_(), and metis_edgend__().
METIS_NodeWND()
void METIS_NodeWND (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 204 of file ometis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumberingOrder, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, controldef::maxvwgt, MlevelNestedDissection(), controldef::nseps, NULL, OFLAG_COMPRESS, controldef::oflags, ONMETIS_CTYPE, ONMETIS_DBGLVL, ONMETIS_ITYPE, ONMETIS_RTYPE, OP_ONMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, ORDER_UNBALANCE_FRACTION, controldef::pfactor, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by METIS_NODEWND(), metis_nodewnd(), metis_nodewnd_(), and metis_nodewnd__().
MlevelNestedDissection()
void MlevelNestedDissection (CtrlType * ctrl, GraphType * graph, idxtype * order, float ubfactor, int lastvtx)
Definition at line 263 of file ometis.c.
References graphdef::bndind, ConstructMinCoverSeparator, DBG_SEPINFO, DBG_TIME, controldef::dbglvl, graphdef::gdata, GKfree, idxsum, IFSET, graphdef::label, LTERM, MlevelEdgeBisection, MlevelNodeBisectionMultiple(), MMDOrder(), MMDSWITCH, graphdef::nbnd, graphdef::nvtxs, OP_OEMETIS, OP_ONMETIS, controldef::optype, graphdef::pwgts, graphdef::rdata, controldef::SepTmr, SplitGraphOrder(), starttimer, stoptimer, and graphdef::vwgt.
Referenced by GRACLUS_METIS_NodeND(), METIS_EdgeND(), and METIS_NodeWND().
MlevelNestedDissectionCC()
void MlevelNestedDissectionCC (CtrlType * ctrl, GraphType * graph, idxtype * order, float ubfactor, int lastvtx)
Definition at line 323 of file ometis.c.
References graphdef::bndind, DBG_SEPINFO, controldef::dbglvl, FindComponents, graphdef::gdata, GKfree, GKmalloc, idxmalloc, idxsum, IFSET, graphdef::label, LTERM, MlevelNodeBisectionMultiple(), MMDOrder(), graphdef::nbnd, NULL, graphdef::nvtxs, graphdef::pwgts, graphdef::rdata, SplitGraphOrderCC(), and graphdef::vwgt.
Referenced by GRACLUS_METIS_NodeND().
MlevelNodeBisection()
void MlevelNodeBisection (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 468 of file ometis.c.
References Coarsen2Way, controldef::CoarsenTo, Compute2WayPartitionParams, ConstructSeparator, DBG_TIME, controldef::dbglvl, IFSET, Init2WayPartition, InitSeparator, IPART_GGPKL, IPART_GGPKLNODE, controldef::IType, controldef::maxvwgt, graphdef::nvtxs, Refine2WayNode, controldef::SepTmr, starttimer, and stoptimer.
Referenced by MlevelNodeBisectionMultiple().
MlevelNodeBisectionMultiple()
void MlevelNodeBisectionMultiple (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 386 of file ometis.c.
References Allocate2WayNodePartitionMemory, Coarsen2Way, controldef::CoarsenTo, Compute2WayNodePartitionParams, controldef::CType, GKfree, idxcopy, idxmalloc, LTERM, graphdef::mincut, MlevelNodeBisection(), controldef::nseps, graphdef::nvtxs, OFLAG_COMPRESS, controldef::oflags, graphdef::rdata, Refine2WayNode, and graphdef::where.
Referenced by MlevelNestedDissection(), and MlevelNestedDissectionCC().
MMDOrder()
void MMDOrder (CtrlType * ctrl, GraphType * graph, idxtype * order, int lastvtx)
Definition at line 617 of file ometis.c.
References graphdef::adjncy, genmmd, idxmalloc, graphdef::label, MAXIDX, graphdef::nvtxs, and graphdef::xadj.
Referenced by MlevelNestedDissection(), and MlevelNestedDissectionCC().
SplitGraphOrder()
void SplitGraphOrder (CtrlType * ctrl, GraphType * graph, GraphType * lgraph, GraphType * rgraph)
Definition at line 508 of file ometis.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, graphdef::bndind, graphdef::bndptr, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, graphdef::label, graphdef::nbnd, graphdef::nedges, NULL, graphdef::nvtxs, SetUpSplitGraph, controldef::SplitTmr, starttimer, stoptimer, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by MlevelNestedDissection().
SplitGraphOrderCC()
int SplitGraphOrderCC (CtrlType * ctrl, GraphType * graph, GraphType * sgraphs, int ncmps, idxtype * cptr, idxtype * cind)
Definition at line 663 of file ometis.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, graphdef::bndind, graphdef::bndptr, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, graphdef::label, MMDSWITCH, graphdef::nbnd, graphdef::ncon, graphdef::nedges, NULL, graphdef::nvtxs, RandomPermute, SetUpSplitGraph, controldef::SplitTmr, starttimer, stoptimer, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by MlevelNestedDissectionCC().