ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/parmetis.c File Reference
parmetis.c File Reference
#include "metis.h"
Functions
void METIS_PartGraphKway2 (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void METIS_WPartGraphKway2 (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *edgecut, idxtype *part)
void METIS_NodeNDP (int nvtxs, idxtype *xadj, idxtype *adjncy, int npes, int *options, idxtype *perm, idxtype *iperm, idxtype *sizes)
void MlevelNestedDissectionP (CtrlType *ctrl, GraphType *graph, idxtype *order, int lastvtx, int npes, int cpos, idxtype *sizes)
void METIS_NodeComputeSeparator (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *options, int *sepsize, idxtype *part)
void METIS_EdgeComputeSeparator (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *options, int *sepsize, idxtype *part)
Function Documentation
METIS_EdgeComputeSeparator()
void METIS_EdgeComputeSeparator (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * options, int * sepsize, idxtype * part)
Definition at line 320 of file parmetis.c.
References AllocateWorkSpace, amin, controldef::CoarsenTo, ConstructMinCoverSeparator, controldef::CType, controldef::dbglvl, FreeWorkSpace, graphdef::gdata, GKfree, idxcopy, idxsum, InitRandom, controldef::IType, graphdef::label, LTERM, controldef::maxvwgt, MlevelEdgeBisection, controldef::nseps, controldef::oflags, ONMETIS_CTYPE, ONMETIS_DBGLVL, ONMETIS_ITYPE, ONMETIS_RTYPE, OP_OEMETIS, OP_ONMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, controldef::pfactor, graphdef::pwgts, graphdef::rdata, controldef::RType, SetUpGraph, graphdef::vwgt, and graphdef::where.
METIS_NodeComputeSeparator()
void METIS_NodeComputeSeparator (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * options, int * sepsize, idxtype * part)
Definition at line 262 of file parmetis.c.
References AllocateWorkSpace, amin, controldef::CoarsenTo, controldef::CType, controldef::dbglvl, FreeWorkSpace, graphdef::gdata, GKfree, idxcopy, idxsum, InitRandom, controldef::IType, graphdef::label, LTERM, controldef::maxvwgt, MlevelNodeBisectionMultiple, controldef::nseps, controldef::oflags, ONMETIS_CTYPE, ONMETIS_DBGLVL, ONMETIS_ITYPE, ONMETIS_RTYPE, OP_ONMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, controldef::pfactor, graphdef::pwgts, graphdef::rdata, controldef::RType, SetUpGraph, graphdef::vwgt, and graphdef::where.
METIS_NodeNDP()
void METIS_NodeNDP (int nvtxs, idxtype * xadj, idxtype * adjncy, int npes, int * options, idxtype * perm, idxtype * iperm, idxtype * sizes)
Definition at line 95 of file parmetis.c.
References AllocateWorkSpace, controldef::CoarsenTo, CompressGraph, COMPRESSION_FRACTION, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, GKfree, idxmalloc, idxset, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, LTERM, controldef::maxvwgt, MlevelNestedDissectionP(), controldef::nseps, NULL, graphdef::nvtxs, OFLAG_COMPRESS, controldef::oflags, ONMETIS_CTYPE, ONMETIS_DBGLVL, ONMETIS_ITYPE, ONMETIS_NSEPS, ONMETIS_OFLAGS, ONMETIS_PFACTOR, ONMETIS_RTYPE, OP_ONMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_NSEPS, OPTION_OFLAGS, OPTION_PFACTOR, OPTION_RTYPE, controldef::optype, controldef::pfactor, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
METIS_PartGraphKway2()
void METIS_PartGraphKway2 (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 22 of file parmetis.c.
References fmalloc, and METIS_WPartGraphKway2().
METIS_WPartGraphKway2()
void METIS_WPartGraphKway2 (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 44 of file parmetis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, KMETIS_CTYPE, KMETIS_DBGLVL, KMETIS_ITYPE, KMETIS_RTYPE, controldef::maxvwgt, MlevelKWayPartitioning, OP_KMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by METIS_PartGraphKway2().
MlevelNestedDissectionP()
void MlevelNestedDissectionP (CtrlType * ctrl, GraphType * graph, idxtype * order, int lastvtx, int npes, int cpos, idxtype * sizes)
Definition at line 193 of file parmetis.c.
References graphdef::bndind, DBG_SEPINFO, controldef::dbglvl, graphdef::gdata, GKfree, idxsum, IFSET, graphdef::label, LTERM, MlevelNodeBisectionMultiple, MMDOrder, MMDSWITCH, graphdef::nbnd, graphdef::nvtxs, ORDER_UNBALANCE_FRACTION, graphdef::pwgts, graphdef::rdata, SplitGraphOrder, and graphdef::vwgt.
Referenced by METIS_NodeNDP().