ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qHoughNormals/extern/normals_Hough/normals_Hough/pc_io.h File Reference
pc_io.h File Reference
#include <string>
#include "Eigen/Dense"
Functions
void pc_load (const std::string &filename, Eigen::MatrixX3d &pc)
void pc_save (const std::string &filename, const Eigen::MatrixX3d &pc, const Eigen::MatrixX3d &normals)
Function Documentation
pc_load()
void pc_load (const std::string & filename, Eigen::MatrixX3d & pc)
Definition at line 46 of file pc_io.cpp.
References points.
Referenced by main().
pc_save()
void pc_save (const std::string & filename, const Eigen::MatrixX3d & pc, const Eigen::MatrixX3d & normals)
Definition at line 64 of file pc_io.cpp.
References QtCompat::endl(), and normals.
Referenced by main().