ACloudViewer: /root/ACloudViewer/libs/PCLEngine/Tools/Common/PclTools.cpp File Reference
PclTools.cpp File Reference
#include "PclTools.h"
#include <Utils/cc2sm.h>
#include <Utils/sm2cc.h>
#include "VtkUtils/vtkutils.h"
#include <CVTools.h>
#include <FileSystem.h>
#include <ecvGLMatrix.h>
#include <LineSet.h>
#include <camera/PinholeCameraParameters.h>
#include <camera/PinholeCameraTrajectory.h>
#include <ecvBBox.h>
#include <ecvCameraSensor.h>
#include <ecvColorScale.h>
#include <ecvDisplayTools.h>
#include <ecvGBLSensor.h>
#include <ecvPlane.h>
#include <ecvScalarField.h>
#include <vtkActor.h>
#include <vtkAnnotatedCubeActor.h>
#include <vtkAppendPolyData.h>
#include <vtkAxesActor.h>
#include <vtkCaptionActor2D.h>
#include <vtkCellData.h>
#include <vtkDataSet.h>
#include <vtkDataSetMapper.h>
#include <vtkLODActor.h>
#include <vtkLine.h>
#include <vtkLineSource.h>
#include <vtkPlaneSource.h>
#include <vtkPointData.h>
#include <vtkPoints.h>
#include <vtkPolygon.h>
#include <vtkPropAssembly.h>
#include <vtkProperty.h>
#include <vtkProperty2D.h>
#include <vtkSmartPointer.h>
#include <vtkTextActor.h>
#include <vtkTextProperty.h>
#include <vtkTexture.h>
#include <vtkUnsignedCharArray.h>
#include <vtkUnstructuredGrid.h>
#include <pcl/visualization/vtk/vtkVertexBufferObjectMapper.h>
#include <VTKExtensions/Utility/vtkDiscretizableColorTransferFunctionCustom.h>
#include <VTKExtensions/Views/vtkContext2DScalarBarActor.h>
#include <VTKExtensions/Views/vtkScalarBarActorCustom.h>
#include <VTKExtensions/Views/vtkScalarBarRepresentationCustom.h>
#include <VTKExtensions/Widgets/vtkScalarBarWidgetCustom.h>
#include <pcl/common/transforms.h>
#include <pcl/features/normal_3d.h>
#include <pcl/io/vtk_lib_io.h>
#include <pcl/visualization/pcl_visualizer.h>
Classes
struct vlabel
Typedefs
using vlabelSet = std::list< vlabel >
A set of 'vlabel' structures.
using vlabelPair = std::pair< vlabelSet::iterator, vlabelSet::iterator >
Functions
void ConvertToLogScale (ScalarType &dispMin, ScalarType &dispMax)
static vlabelPair GetVLabelsAround (int y, vlabelSet &set)
Variables
const double c_log10 = log(10.0)
Typedef Documentation
vlabelPair
using vlabelPair = std::pair<vlabelSet::iterator, vlabelSet::iterator>
Definition at line 698 of file PclTools.cpp.
vlabelSet
using vlabelSet = std::list<vlabel>
A set of 'vlabel' structures.
Definition at line 682 of file PclTools.cpp.
Function Documentation
ConvertToLogScale()
void ConvertToLogScale (ScalarType & dispMin, ScalarType & dispMax)
Definition at line 685 of file PclTools.cpp.
Referenced by PclTools::UpdateScalarBar().
GetVLabelsAround()
static vlabelPair GetVLabelsAround (int y, vlabelSet & set) static
Definition at line 700 of file PclTools.cpp.
Referenced by PclTools::UpdateScalarBar().
Variable Documentation
c_log10
const double c_log10 = log(10.0)
Definition at line 665 of file PclTools.cpp.
Referenced by PclTools::UpdateScalarBar().