ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPCV/src/PCV.cpp File Reference
PCV.cpp File Reference
#include "PCV.h"
#include "PCVContext.h"
#include <QString>
#include <assert.h>
#include <string.h>
#include <algorithm>
#include <vector>
Functions
static int gcd (int num1, int num2)
static bool SampleSphere (unsigned N, std::vector< CCVector3 > &dirs)
Sample points on the unit sphere.
Function Documentation
gcd()
static int gcd (int num1, int num2) static
Definition at line 29 of file PCV.cpp.
Referenced by SampleSphere().
SampleSphere()
static bool SampleSphere (unsigned N, std::vector< CCVector3 > & dirs) static
Sample points on the unit sphere.
Transcripted from MATLAB's script "partsphere.m" by Paul Leopardi, 2003-10-13, for UNSW School of Mathematics.
As points are sampled on the unit sphere, they can also be considered as directions. WARNING: returned array is on the user responsibilty!
Parameters
N number of desired sampled directions
[out] dirs set of N points
Returns
success
Definition at line 47 of file PCV.cpp.
References cloudViewer::utility::ceil(), cloudViewer::utility::floor(), gcd(), M_PI, max(), and offset.
Referenced by PCV::GenerateRays().