ACloudViewer: /root/ACloudViewer/plugins/core/IO/qPhotoscanIO/src/PhotoScanFilter.cpp File Reference
PhotoScanFilter.cpp File Reference
#include "PhotoScanFilter.h"
#include <CVLog.h>
#include <QDir>
#include <QFileInfo>
#include <QXmlStreamReader>
#include <QtCompat.h>
#include <ecvCameraSensor.h>
#include <ecvHObject.h>
#include <ecvImage.h>
#include <ecvMesh.h>
#include <ecvPointCloud.h>
#include <ecvProgressDialog.h>
#include <PlyFilter.h>
#include <quazip.h>
#include <quazipfile.h>
#include <assert.h>
#include <string.h>
Classes
struct CameraDesc
struct CloudDesc
struct MeshDesc
Enumerations
enum Sections {
DOCUMENT , CHUNKS , CHUNK , SENSORS ,
CAMERAS , FRAMES , FRAME , TRANSFORM
}
Functions
QString ToName (Sections section)
template<typename T >
bool DecodeRotation (const QString &rotationValues, ccGLMatrixTpl< T > &output)
template<typename T >
bool DecodeTransformation (const QString &transformationValues, ccGLMatrixTpl< T > &output)
static void DisplayCurrentNodeInfo (QXmlStreamReader &stream)
static ccCameraSensor * DecodeSensor (QXmlStreamReader &stream, int &sensorId)
static bool DecodeCamera (QXmlStreamReader &stream, CameraDesc &camera)
static QString CreateTempFile (QuaZip &zip, QString zipFilename)
Enumeration Type Documentation
Sections
enum Sections
Enumerator
DOCUMENT
CHUNKS
CHUNK
SENSORS
CAMERAS
FRAMES
FRAME
TRANSFORM
Definition at line 57 of file PhotoScanFilter.cpp.
Function Documentation
CreateTempFile()
static QString CreateTempFile (QuaZip & zip, QString zipFilename) static
Definition at line 330 of file PhotoScanFilter.cpp.
References QuaZip::setCurrentFile(), and CVLog::Warning().
Referenced by PhotoScanFilter::loadFile().
DecodeCamera()
static bool DecodeCamera (QXmlStreamReader & stream, CameraDesc & camera) static
Definition at line 283 of file PhotoScanFilter.cpp.
References CameraDesc::id, CameraDesc::imageFilename, CameraDesc::sensorId, Vector3Tpl< Type >::toDouble(), e57::toString(), and CameraDesc::trans.
Referenced by PhotoScanFilter::loadFile().
DecodeRotation()
template<typename T > bool DecodeRotation (const QString & rotationValues, ccGLMatrixTpl< T > & output)
Definition at line 94 of file PhotoScanFilter.cpp.
References ccGLMatrixTpl< T >::data(), QtCompat::SkipEmptyParts, and ccGLMatrixTpl< T >::transpose().
DecodeSensor()
static ccCameraSensor* DecodeSensor (QXmlStreamReader & stream, int & sensorId) static
Definition at line 150 of file PhotoScanFilter.cpp.
References ccCameraSensor::ComputeFovRadFromFocalPix(), DisplayCurrentNodeInfo(), height, ccCameraSensor::RadialDistortionParameters::k1, ccCameraSensor::RadialDistortionParameters::k2, ccCameraSensor::ExtendedRadialDistortionParameters::k3, max(), params, ccCameraSensor::setDistortionParameters(), ccObject::setName(), and width.
Referenced by PhotoScanFilter::loadFile().
DecodeTransformation()
template<typename T > bool DecodeTransformation (const QString & transformationValues, ccGLMatrixTpl< T > & output)
Definition at line 117 of file PhotoScanFilter.cpp.
References ccGLMatrixTpl< T >::data(), QtCompat::SkipEmptyParts, and ccGLMatrixTpl< T >::transpose().
DisplayCurrentNodeInfo()
static void DisplayCurrentNodeInfo (QXmlStreamReader & stream) static
Definition at line 139 of file PhotoScanFilter.cpp.
References size, and CVLog::Warning().
Referenced by DecodeSensor().
ToName()
QString ToName (Sections section)
Definition at line 68 of file PhotoScanFilter.cpp.
References CAMERAS, CHUNK, CHUNKS, DOCUMENT, FRAME, FRAMES, SENSORS, and TRANSFORM.
Referenced by PhotoScanFilter::loadFile().