ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/FastMarching.cpp File Reference
FastMarching.cpp File Reference
#include <pybind11/pybind11.h>
#include <FastMarching.h>
#include <FastMarchingForPropagation.h>
#include <GenericCloud.h>
#include <ReferenceCloud.h>
Functions
void define_FastMarching (py::module &cccorelib)
Function Documentation
define_FastMarching()
void define_FastMarching (py::module & cccorelib)
Definition at line 18 of file FastMarching.cpp.
References cloudViewer::c_FastMarchingNeighbourPosShift, cloudViewer::FastMarching::cleanLastPropagation(), cloudViewer::FastMarching::getTime(), cloudViewer::FastMarching::setExtendedConnectivity(), and cloudViewer::FastMarching::setSeedCell().
Referenced by define_cccorelib().