ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Filters/FastGlobalRegistration.cpp File Reference
FastGlobalRegistration.cpp File Reference
#include "FastGlobalRegistration.h"
#include <flann/flann.hpp>
#include <CVLog.h>
#include <Eigen/Geometry>
Namespaces
fgr
Typedefs
typedef flann::Index< flann::L2< float > > fgr::KDTree
typedef std::vector< int > fgr::Indexes
typedef std::vector< float > fgr::Distances
Functions
template<typename T >
static fgr::KDTree BuildKDTree (const vector< T > &data)
template<typename T >
static void SearchKDTree (fgr::KDTree &tree, const T &input, int &nearestIndex, float &smallestSquareDist)
static void TransformPoints (fgr::Points &points, const Eigen::Matrix4f &Trans)
static bool Similar (const Eigen::Vector3f &ACloud1, const Eigen::Vector3f &BCloud1, const Eigen::Vector3f &ACloud2, const Eigen::Vector3f &BCloud2, double maxRelativeScaleDiff)
Variables
static constexpr int ReferenceIndex = 0
static constexpr int AlignedIndex = 1
Function Documentation
BuildKDTree()
template<typename T > static fgr::KDTree BuildKDTree (const vector< T > & data) static
Definition at line 42 of file FastGlobalRegistration.cpp.
References data.
Referenced by fgr::CApp::AdvancedMatching().
SearchKDTree()
template<typename T > static void SearchKDTree (fgr::KDTree & tree, const T & input, int & nearestIndex, float & smallestSquareDist) static
Definition at line 59 of file FastGlobalRegistration.cpp.
Referenced by fgr::CApp::AdvancedMatching().
Similar()
static bool Similar (const Eigen::Vector3f & ACloud1, const Eigen::Vector3f & BCloud1, const Eigen::Vector3f & ACloud2, const Eigen::Vector3f & BCloud2, double maxRelativeScaleDiff) static
Definition at line 90 of file FastGlobalRegistration.cpp.
Referenced by fgr::CApp::AdvancedMatching().
TransformPoints()
static void TransformPoints (fgr::Points & points, const Eigen::Matrix4f & Trans) static
Definition at line 78 of file FastGlobalRegistration.cpp.
References points.
Referenced by fgr::CApp::OptimizePairwise().
Variable Documentation
AlignedIndex
constexpr int AlignedIndex = 1 static constexpr
Definition at line 32 of file FastGlobalRegistration.cpp.
Referenced by fgr::CApp::AdvancedMatching(), fgr::CApp::GetOutputTrans(), and fgr::CApp::OptimizePairwise().
ReferenceIndex
constexpr int ReferenceIndex = 0 static constexpr
Definition at line 31 of file FastGlobalRegistration.cpp.
Referenced by fgr::CApp::AdvancedMatching(), fgr::CApp::GetOutputTrans(), and fgr::CApp::OptimizePairwise().