ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/AutoSegmentationTools.cpp File Reference
AutoSegmentationTools.cpp File Reference
#include <pybind11/pybind11.h>
#include <AutoSegmentationTools.h>
#include <DgmOctree.h>
#include <GenericIndexedCloudPersist.h>
#include <GenericProgressCallback.h>
Functions
void define_AutoSegmentationTools (py::module &cccorelib)
Function Documentation
define_AutoSegmentationTools()
void define_AutoSegmentationTools (py::module & cccorelib)
Definition at line 18 of file AutoSegmentationTools.cpp.
References cloudViewer::AutoSegmentationTools::extractConnectedComponents(), cloudViewer::AutoSegmentationTools::frontPropagationBasedSegmentation(), and cloudViewer::AutoSegmentationTools::labelConnectedComponents().
Referenced by define_cccorelib().