ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/RegistrationTools.cpp File Reference
RegistrationTools.cpp File Reference
#include <pybind11/pybind11.h>
#include <GenericIndexedMesh.h>
#include <GenericProgressCallback.h>
#include <RegistrationTools.h>
Functions
void define_RegistrationTools (py::module &cccorelib)
Function Documentation
define_RegistrationTools()
void define_RegistrationTools (py::module & cccorelib)
Definition at line 17 of file RegistrationTools.cpp.
References cloudViewer::ICPRegistrationTools::Parameters::adjustScale, cloudViewer::HornRegistrationTools::ComputeRMS(), cloudViewer::ICPRegistrationTools::Parameters::convType, cloudViewer::ICPRegistrationTools::Parameters::dataWeights, cloudViewer::ICPRegistrationTools::Parameters::filterOutFarthestPoints, cloudViewer::RegistrationTools::FilterTransformation(), cloudViewer::ICPRegistrationTools::Parameters::finalOverlapRatio, cloudViewer::HornRegistrationTools::FindAbsoluteOrientation(), cloudViewer::ICPRegistrationTools::Parameters::maxThreadCount, cloudViewer::ICPRegistrationTools::Parameters::minRMSDecrease, cloudViewer::ICPRegistrationTools::Parameters::modelWeights, cloudViewer::ICPRegistrationTools::Parameters::nbMaxIterations, cloudViewer::ICPRegistrationTools::Register(), cloudViewer::FPCSRegistrationTools::RegisterClouds(), cloudViewer::ICPRegistrationTools::Parameters::samplingLimit, and cloudViewer::ICPRegistrationTools::Parameters::transformationFilters.
Referenced by define_cccorelib().