ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/PlyFile.cpp File Reference
PlyFile.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "Ply.h"
Classes
union endian_test_type
Macros
#define NO_OTHER_PROPS -1
#define DONT_STORE_PROP 0
#define STORE_PROP 1
#define OTHER_PROP 0
#define NAMED_PROP 1
#define BIG_STRING 4096
Functions
int equal_strings (const char *, const char *)
PlyElement * find_element (PlyFile *, const char *)
PlyProperty * find_property (PlyElement *, const char *, int *)
void write_scalar_type (FILE *, int)
char ** get_words (FILE *, int *, char **)
char ** old_get_words (FILE *, int *)
void write_binary_item (FILE *, int, int, unsigned int, double, int)
void write_ascii_item (FILE *, int, unsigned int, double, int)
double old_write_ascii_item (FILE *, char *, int)
void add_element (PlyFile *, char **)
void add_property (PlyFile *, char **)
void add_comment (PlyFile *, char *)
void add_obj_info (PlyFile *, char *)
void copy_property (PlyProperty *, PlyProperty *)
void store_item (char *, int, int, unsigned int, double)
void get_stored_item (void *, int, int *, unsigned int *, double *)
double get_item_value (char *, int)
void get_ascii_item (char *, int, int *, unsigned int *, double *)
void get_binary_item (FILE *, int, int, int *, unsigned int *, double *)
void ascii_get_element (PlyFile *, char *)
void binary_get_element (PlyFile *, char *)
char * my_alloc (int, int, const char *)
void get_native_binary_type ()
void swap_bytes (char *, int)
void check_types ()
PlyFile * ply_write_custom (FILE *fp, int nelems, const char **elem_names, int file_type)
PlyFile * ply_open_for_writing (char *filename, int nelems, const char **elem_names, int file_type, float *version)
void ply_describe_element (PlyFile *plyfile, char *elem_name, int nelems, int nprops, PlyProperty *prop_list)
void ply_describe_property (PlyFile *plyfile, const char *elem_name, PlyProperty *prop)
void ply_describe_other_properties (PlyFile *plyfile, PlyOtherProp *other, int offset)
void ply_element_count (PlyFile *plyfile, const char *elem_name, int nelems)
void ply_header_complete (PlyFile *plyfile)
void ply_put_element_setup (PlyFile *plyfile, const char *elem_name)
void ply_put_element (PlyFile *plyfile, void *elem_ptr)
void ply_put_comment (PlyFile *plyfile, char *comment)
void ply_put_obj_info (PlyFile *plyfile, char *obj_info)
PlyFile * ply_read_custom (FILE *fp, int *nelems, char ***elem_names)
PlyFile * ply_open_for_reading (char *filename, int *nelems, char ***elem_names, int *file_type, float *version)
PlyProperty ** ply_get_element_description (PlyFile *plyfile, char *elem_name, int *nelems, int *nprops)
void ply_get_element_setup (PlyFile *plyfile, char *elem_name, int nprops, PlyProperty *prop_list)
int ply_get_property (PlyFile *plyfile, char *elem_name, PlyProperty *prop)
void ply_get_element (PlyFile *plyfile, void *elem_ptr)
char ** ply_get_comments (PlyFile *plyfile, int *num_comments)
char ** ply_get_obj_info (PlyFile *plyfile, int *num_obj_info)
void setup_other_props (PlyElement *elem)
PlyOtherProp * ply_get_other_properties (PlyFile *plyfile, char *elem_name, int offset)
PlyOtherElems * ply_get_other_element (PlyFile *plyfile, char *elem_name, int elem_count)
void ply_describe_other_elements (PlyFile *plyfile, PlyOtherElems *other_elems)
void ply_put_other_elements (PlyFile *plyfile)
void ply_free_other_elements (PlyOtherElems *other_elems)
void ply_close_custom (PlyFile *plyfile)
void ply_get_info (PlyFile *ply, float *version, int *file_type)
int get_prop_type (char *type_name)
Variables
const char * type_names []
int ply_type_size []
static int native_binary_type = -1
static int types_checked = 0
Macro Definition Documentation
BIG_STRING
#define BIG_STRING 4096
DONT_STORE_PROP
#define DONT_STORE_PROP 0
Definition at line 95 of file PlyFile.cpp.
NAMED_PROP
#define NAMED_PROP 1
Definition at line 99 of file PlyFile.cpp.
NO_OTHER_PROPS
#define NO_OTHER_PROPS -1
Definition at line 93 of file PlyFile.cpp.
OTHER_PROP
#define OTHER_PROP 0
Definition at line 98 of file PlyFile.cpp.
STORE_PROP
#define STORE_PROP 1
Definition at line 96 of file PlyFile.cpp.
Function Documentation
add_comment()
void add_comment (PlyFile * plyfile, char * line)
Definition at line 2657 of file PlyFile.cpp.
References ply_put_comment().
Referenced by ply_read_custom().
add_element()
void add_element (PlyFile * plyfile, char ** words)
Definition at line 2558 of file PlyFile.cpp.
References _strdup, PlyFile::elems, myalloc, PlyElement::name, PlyFile::nelems, PlyElement::nprops, and PlyElement::num.
Referenced by ply_read_custom().
add_obj_info()
void add_obj_info (PlyFile * plyfile, char * line)
Definition at line 2678 of file PlyFile.cpp.
References ply_put_obj_info().
Referenced by ply_read_custom().
add_property()
void add_property (PlyFile * plyfile, char ** words)
Definition at line 2613 of file PlyFile.cpp.
References _strdup, PlyProperty::count_external, PlyFile::elems, equal_strings(), PlyProperty::external_type, get_prop_type(), PlyProperty::is_list, myalloc, PlyProperty::name, PlyFile::nelems, PlyElement::nprops, and PlyElement::props.
Referenced by ply_read_custom().
ascii_get_element()
void ascii_get_element (PlyFile * plyfile, char * elem_ptr)
Definition at line 1531 of file PlyFile.cpp.
References PlyProperty::count_external, PlyProperty::count_internal, PlyProperty::count_offset, PlyProperty::external_type, PlyFile::fp, get_ascii_item(), get_words(), PlyProperty::internal_type, PlyProperty::is_list, myalloc, NO_OTHER_PROPS, PlyElement::nprops, NULL, PlyProperty::offset, PlyElement::other_offset, PlyElement::other_size, ply_type_size, PlyElement::props, store_item(), PlyElement::store_prop, and PlyFile::which_elem.
Referenced by ply_get_element().
binary_get_element()
void binary_get_element (PlyFile * plyfile, char * elem_ptr)
Definition at line 1652 of file PlyFile.cpp.
References PlyProperty::count_external, PlyProperty::count_internal, PlyProperty::count_offset, PlyProperty::external_type, PlyFile::file_type, PlyFile::fp, get_binary_item(), PlyProperty::internal_type, PlyProperty::is_list, myalloc, NO_OTHER_PROPS, PlyElement::nprops, NULL, PlyProperty::offset, PlyElement::other_offset, PlyElement::other_size, ply_type_size, PlyElement::props, store_item(), PlyElement::store_prop, and PlyFile::which_elem.
Referenced by ply_get_element().
check_types()
void check_types ()
Definition at line 1828 of file PlyFile.cpp.
References PLY_CHAR, PLY_DOUBLE, PLY_FLOAT, PLY_INT, PLY_SHORT, ply_type_size, PLY_UCHAR, PLY_UINT, PLY_USHORT, and types_checked.
Referenced by ply_read_custom(), and ply_write_custom().
copy_property()
void copy_property (PlyProperty * dest, PlyProperty * src)
Definition at line 2695 of file PlyFile.cpp.
References _strdup, PlyProperty::count_external, PlyProperty::count_internal, PlyProperty::count_offset, PlyProperty::external_type, PlyProperty::internal_type, PlyProperty::is_list, PlyProperty::name, and PlyProperty::offset.
Referenced by ply_describe_element(), ply_describe_other_properties(), ply_describe_property(), ply_get_element_description(), and ply_get_other_properties().
equal_strings()
int equal_strings (const char * s1, const char * s2)
Definition at line 1459 of file PlyFile.cpp.
Referenced by add_property(), find_element(), find_property(), get_prop_type(), ply_read_custom(), PlyReadHeader(), and PlyReadPolygons().
find_element()
PlyElement * find_element (PlyFile * plyfile, const char * element)
Definition at line 1484 of file PlyFile.cpp.
References PlyFile::elems, equal_strings(), PlyElement::name, PlyFile::nelems, and NULL.
Referenced by ply_describe_element(), ply_describe_other_properties(), ply_describe_property(), ply_element_count(), ply_get_element_description(), ply_get_element_setup(), ply_get_other_element(), ply_get_other_properties(), ply_get_property(), and ply_put_element_setup().
find_property()
PlyProperty * find_property (PlyElement * elem, const char * prop_name, int * index)
Definition at line 1508 of file PlyFile.cpp.
References equal_strings(), PlyProperty::name, PlyElement::nprops, NULL, and PlyElement::props.
Referenced by ply_get_element_setup(), and ply_get_property().
get_ascii_item()
void get_ascii_item (char * word, int type, int * int_val, unsigned int * uint_val, double * double_val)
Definition at line 2424 of file PlyFile.cpp.
References NULL, PLY_CHAR, PLY_DOUBLE, PLY_FLOAT, PLY_FLOAT_32, PLY_FLOAT_64, PLY_INT, PLY_INT_16, PLY_INT_32, PLY_INT_8, PLY_SHORT, PLY_UCHAR, PLY_UINT, PLY_UINT_16, PLY_UINT_32, PLY_UINT_8, PLY_USHORT, and type.
Referenced by ascii_get_element().
get_binary_item()
void get_binary_item (FILE * fp, int file_type, int type, int * int_val, unsigned int * uint_val, double * double_val)
Definition at line 2330 of file PlyFile.cpp.
References native_binary_type, PLY_CHAR, PLY_DOUBLE, PLY_FLOAT, PLY_FLOAT_32, PLY_FLOAT_64, PLY_INT, PLY_INT_16, PLY_INT_32, PLY_INT_8, PLY_SHORT, ply_type_size, PLY_UCHAR, PLY_UINT, PLY_UINT_16, PLY_UINT_32, PLY_UINT_8, PLY_USHORT, swap_bytes(), and type.
Referenced by binary_get_element().
get_item_value()
double get_item_value (char * item, int type)
Definition at line 1950 of file PlyFile.cpp.
References PLY_CHAR, PLY_DOUBLE, PLY_FLOAT, PLY_FLOAT_32, PLY_FLOAT_64, PLY_INT, PLY_INT_16, PLY_INT_32, PLY_INT_8, PLY_SHORT, PLY_UCHAR, PLY_UINT, PLY_UINT_16, PLY_UINT_32, PLY_UINT_8, PLY_USHORT, and type.
get_native_binary_type()
void get_native_binary_type ()
Definition at line 1804 of file PlyFile.cpp.
References endian_test_type::byte_values, endian_test_type::int_value, native_binary_type, PLY_BINARY_BE, and PLY_BINARY_LE.
Referenced by ply_read_custom(), and ply_write_custom().
get_prop_type()
int get_prop_type (char * type_name)
Definition at line 2591 of file PlyFile.cpp.
References equal_strings(), PLY_END_TYPE, PLY_START_TYPE, and type_names.
Referenced by add_property().
get_stored_item()
void get_stored_item (void * ptr, int type, int * int_val, unsigned int * uint_val, double * double_val)
Definition at line 2252 of file PlyFile.cpp.
References PLY_CHAR, PLY_DOUBLE, PLY_FLOAT, PLY_FLOAT_32, PLY_FLOAT_64, PLY_INT, PLY_INT_16, PLY_INT_32, PLY_INT_8, PLY_SHORT, PLY_UCHAR, PLY_UINT, PLY_UINT_16, PLY_UINT_32, PLY_UINT_8, PLY_USHORT, and type.
Referenced by ply_put_element().
get_words()
char ** get_words (FILE * fp, int * nwords, char ** orig_line)
Definition at line 1862 of file PlyFile.cpp.
References BIG_STRING, myalloc, NULL, and result.
Referenced by ascii_get_element(), and ply_read_custom().
my_alloc()
char * my_alloc (int size, int lnum, const char * fname)
Definition at line 2718 of file PlyFile.cpp.
References size.
old_get_words()
char** old_get_words (FILE * , int *)
old_write_ascii_item()
double old_write_ascii_item (FILE * fp, char * item, int type)
Definition at line 2168 of file PlyFile.cpp.
References PLY_CHAR, PLY_DOUBLE, PLY_FLOAT, PLY_FLOAT_32, PLY_FLOAT_64, PLY_INT, PLY_INT_16, PLY_INT_32, PLY_INT_8, PLY_SHORT, PLY_UCHAR, PLY_UINT, PLY_UINT_16, PLY_UINT_32, PLY_UINT_8, PLY_USHORT, and type.
ply_close_custom()
void ply_close_custom (PlyFile * plyfile)
Definition at line 1425 of file PlyFile.cpp.
References PlyFile::fp.
Referenced by PlyReadHeader(), PlyReadPolygons(), and PlyWritePolygons().
ply_describe_element()
void ply_describe_element (PlyFile * plyfile, char * elem_name, int nelems, int nprops, PlyProperty * prop_list)
Definition at line 294 of file PlyFile.cpp.
References copy_property(), find_element(), myalloc, NAMED_PROP, PlyElement::nprops, NULL, PlyElement::num, PlyElement::props, and PlyElement::store_prop.
ply_describe_other_elements()
void ply_describe_other_elements (PlyFile * plyfile, PlyOtherElems * other_elems)
Definition at line 1333 of file PlyFile.cpp.
References _strdup, OtherElem::elem_count, OtherElem::elem_name, PlyFile::elems, myalloc, PlyElement::name, PlyFile::nelems, PlyElement::nprops, NULL, PlyElement::num, PlyOtherElems::num_elems, offsetof, PlyFile::other_elems, PlyOtherElems::other_list, OtherElem::other_props, ply_describe_other_properties(), and REALLOCN.
ply_describe_other_properties()
void ply_describe_other_properties (PlyFile * plyfile, PlyOtherProp * other, int offset)
Definition at line 385 of file PlyFile.cpp.
References copy_property(), find_element(), myalloc, PlyOtherProp::name, PlyElement::nprops, PlyOtherProp::nprops, NULL, offset, PlyElement::other_offset, OTHER_PROP, PlyElement::other_size, PlyElement::props, PlyOtherProp::props, PlyOtherProp::size, and PlyElement::store_prop.
Referenced by ply_describe_other_elements().
ply_describe_property()
void ply_describe_property (PlyFile * plyfile, const char * elem_name, PlyProperty * prop)
Definition at line 339 of file PlyFile.cpp.
References copy_property(), find_element(), myalloc, NAMED_PROP, PlyElement::nprops, NULL, PlyElement::props, and PlyElement::store_prop.
Referenced by PlyWritePolygons().
ply_element_count()
void ply_element_count (PlyFile * plyfile, const char * elem_name, int nelems)
Definition at line 445 of file PlyFile.cpp.
References find_element(), NULL, and PlyElement::num.
Referenced by PlyWritePolygons().
ply_free_other_elements()
void ply_free_other_elements (PlyOtherElems * other_elems)
Definition at line 1405 of file PlyFile.cpp.
Referenced by PlyReadHeader(), and PlyReadPolygons().
ply_get_comments()
char** ply_get_comments (PlyFile * plyfile, int * num_comments)
Definition at line 1074 of file PlyFile.cpp.
References PlyFile::comments, and PlyFile::num_comments.
ply_get_element()
void ply_get_element (PlyFile * plyfile, void * elem_ptr)
Definition at line 1054 of file PlyFile.cpp.
References ascii_get_element(), binary_get_element(), PlyFile::file_type, and PLY_ASCII.
Referenced by ply_get_other_element(), and PlyReadPolygons().
ply_get_element_description()
PlyProperty** ply_get_element_description (PlyFile * plyfile, char * elem_name, int * nelems, int * nprops)
Definition at line 915 of file PlyFile.cpp.
References copy_property(), find_element(), myalloc, PlyElement::nprops, NULL, PlyElement::num, and PlyElement::props.
Referenced by PlyReadHeader(), and PlyReadPolygons().
ply_get_element_setup()
void ply_get_element_setup (PlyFile * plyfile, char * elem_name, int nprops, PlyProperty * prop_list)
Definition at line 959 of file PlyFile.cpp.
References PlyProperty::count_internal, PlyProperty::count_offset, find_element(), find_property(), PlyProperty::internal_type, name, NULL, PlyProperty::offset, PlyElement::store_prop, STORE_PROP, and PlyFile::which_elem.
ply_get_info()
void ply_get_info (PlyFile * ply, float * version, int * file_type)
Definition at line 1445 of file PlyFile.cpp.
References PlyFile::file_type, NULL, version, and PlyFile::version.
ply_get_obj_info()
char** ply_get_obj_info (PlyFile * plyfile, int * num_obj_info)
Definition at line 1093 of file PlyFile.cpp.
References PlyFile::num_obj_info, and PlyFile::obj_info.
ply_get_other_element()
PlyOtherElems* ply_get_other_element (PlyFile * plyfile, char * elem_name, int elem_count)
Definition at line 1261 of file PlyFile.cpp.
References _strdup, OtherElem::elem_count, OtherElem::elem_name, find_element(), myalloc, NULL, PlyOtherElems::num_elems, offsetof, OtherElem::other_data, PlyFile::other_elems, PlyOtherElems::other_list, OtherElem::other_props, ply_get_element(), and ply_get_other_properties().
Referenced by PlyReadPolygons().
ply_get_other_properties()
PlyOtherProp* ply_get_other_properties (PlyFile * plyfile, char * elem_name, int offset)
Definition at line 1182 of file PlyFile.cpp.
References _strdup, copy_property(), find_element(), myalloc, PlyOtherProp::name, NO_OTHER_PROPS, PlyElement::nprops, PlyOtherProp::nprops, NULL, offset, PlyElement::other_offset, PlyElement::other_size, PlyElement::props, PlyOtherProp::props, setup_other_props(), PlyOtherProp::size, PlyElement::store_prop, and PlyFile::which_elem.
Referenced by ply_get_other_element().
ply_get_property()
int ply_get_property (PlyFile * plyfile, char * elem_name, PlyProperty * prop)
Definition at line 1010 of file PlyFile.cpp.
References PlyProperty::count_internal, PlyProperty::count_offset, find_element(), find_property(), PlyProperty::internal_type, PlyProperty::name, NULL, PlyProperty::offset, PlyElement::store_prop, STORE_PROP, and PlyFile::which_elem.
Referenced by PlyReadHeader(), and PlyReadPolygons().
ply_header_complete()
void ply_header_complete (PlyFile * plyfile)
Definition at line 472 of file PlyFile.cpp.
References PlyFile::comments, PlyProperty::count_external, PlyFile::elems, PlyProperty::external_type, PlyFile::file_type, PlyFile::fp, PlyProperty::is_list, PlyProperty::name, PlyElement::name, PlyFile::nelems, PlyElement::nprops, PlyElement::num, PlyFile::num_comments, PlyFile::num_obj_info, PlyFile::obj_info, PLY_ASCII, PLY_BINARY_BE, PLY_BINARY_LE, PlyElement::props, and write_scalar_type().
Referenced by PlyWritePolygons().
ply_open_for_reading()
PlyFile* ply_open_for_reading (char * filename, int * nelems, char *** elem_names, int * file_type, float * version)
Definition at line 860 of file PlyFile.cpp.
References PlyFile::file_type, myalloc, name, NULL, ply_read_custom(), version, and PlyFile::version.
Referenced by PlyReadHeader(), and PlyReadPolygons().
ply_open_for_writing()
PlyFile* ply_open_for_writing (char * filename, int nelems, const char ** elem_names, int file_type, float * version)
Definition at line 240 of file PlyFile.cpp.
References myalloc, name, NULL, ply_write_custom(), version, and PlyFile::version.
Referenced by PlyWritePolygons().
ply_put_comment()
void ply_put_comment (PlyFile * plyfile, char * comment)
Definition at line 682 of file PlyFile.cpp.
References _strdup, PlyFile::comments, myalloc, and PlyFile::num_comments.
Referenced by add_comment(), and PlyWritePolygons().
ply_put_element()
void ply_put_element (PlyFile * plyfile, void * elem_ptr)
Definition at line 569 of file PlyFile.cpp.
References PlyProperty::count_external, PlyProperty::count_internal, PlyProperty::count_offset, PlyProperty::external_type, PlyFile::file_type, PlyFile::fp, get_stored_item(), PlyProperty::internal_type, PlyProperty::is_list, PlyElement::nprops, PlyProperty::offset, PlyElement::other_offset, OTHER_PROP, PLY_ASCII, ply_type_size, PlyElement::props, PlyElement::store_prop, PlyFile::which_elem, write_ascii_item(), and write_binary_item().
Referenced by ply_put_other_elements(), and PlyWritePolygons().
ply_put_element_setup()
void ply_put_element_setup (PlyFile * plyfile, const char * elem_name)
Definition at line 545 of file PlyFile.cpp.
References find_element(), NULL, and PlyFile::which_elem.
Referenced by ply_put_other_elements(), and PlyWritePolygons().
ply_put_obj_info()
void ply_put_obj_info (PlyFile * plyfile, char * obj_info)
Definition at line 706 of file PlyFile.cpp.
References _strdup, myalloc, PlyFile::num_obj_info, and PlyFile::obj_info.
Referenced by add_obj_info().
ply_put_other_elements()
void ply_put_other_elements (PlyFile * plyfile)
Definition at line 1375 of file PlyFile.cpp.
References OtherElem::elem_count, OtherElem::elem_name, NULL, PlyOtherElems::num_elems, OtherElem::other_data, PlyFile::other_elems, PlyOtherElems::other_list, ply_put_element(), and ply_put_element_setup().
ply_read_custom()
PlyFile* ply_read_custom (FILE * fp, int * nelems, char *** elem_names)
Definition at line 744 of file PlyFile.cpp.
References _strdup, add_comment(), add_element(), add_obj_info(), add_property(), check_types(), PlyFile::comments, DONT_STORE_PROP, PlyFile::elems, equal_strings(), PlyFile::file_type, PlyFile::fp, get_native_binary_type(), get_words(), myalloc, PlyElement::name, native_binary_type, PlyFile::nelems, NO_OTHER_PROPS, PlyElement::nprops, NULL, PlyFile::num_comments, PlyFile::num_obj_info, PlyFile::obj_info, PlyFile::other_elems, PlyElement::other_offset, PLY_ASCII, PLY_BINARY_BE, PLY_BINARY_LE, PlyElement::store_prop, types_checked, and PlyFile::version.
Referenced by ply_open_for_reading().
ply_write_custom()
PlyFile* ply_write_custom (FILE * fp, int nelems, const char ** elem_names, int file_type)
Definition at line 176 of file PlyFile.cpp.
References _strdup, check_types(), PlyFile::elems, PlyFile::file_type, PlyFile::fp, get_native_binary_type(), myalloc, PlyElement::name, native_binary_type, PlyFile::nelems, PlyElement::nprops, NULL, PlyElement::num, PlyFile::num_comments, PlyFile::num_obj_info, PlyFile::other_elems, PLY_BINARY_NATIVE, types_checked, and PlyFile::version.
Referenced by ply_open_for_writing().
setup_other_props()
void setup_other_props (PlyElement * elem)
Definition at line 1111 of file PlyFile.cpp.
References PlyProperty::count_external, PlyProperty::count_internal, PlyProperty::count_offset, PlyProperty::external_type, PlyProperty::internal_type, PlyProperty::is_list, PlyElement::nprops, PlyProperty::offset, PlyElement::other_size, ply_type_size, PlyElement::props, size, and PlyElement::store_prop.
Referenced by ply_get_other_properties().
store_item()
void store_item (char * item, int type, int int_val, unsigned int uint_val, double double_val)
Definition at line 2485 of file PlyFile.cpp.
References PLY_CHAR, PLY_DOUBLE, PLY_FLOAT, PLY_FLOAT_32, PLY_FLOAT_64, PLY_INT, PLY_INT_16, PLY_INT_32, PLY_INT_8, PLY_SHORT, PLY_UCHAR, PLY_UINT, PLY_UINT_16, PLY_UINT_32, PLY_UINT_8, PLY_USHORT, and type.
Referenced by ascii_get_element(), and binary_get_element().
swap_bytes()
void swap_bytes (char * bytes, int num_bytes)
Definition at line 1782 of file PlyFile.cpp.
References bytes.
Referenced by get_binary_item(), and write_binary_item().
write_ascii_item()
void write_ascii_item (FILE * fp, int int_val, unsigned int uint_val, double double_val, int type)
Definition at line 2105 of file PlyFile.cpp.
References PLY_CHAR, PLY_DOUBLE, PLY_FLOAT, PLY_FLOAT_32, PLY_FLOAT_64, PLY_INT, PLY_INT_16, PLY_INT_32, PLY_INT_8, PLY_SHORT, PLY_UCHAR, PLY_UINT, PLY_UINT_16, PLY_UINT_32, PLY_UINT_8, PLY_USHORT, and type.
Referenced by ply_put_element().
write_binary_item()
void write_binary_item (FILE * fp, int file_type, int int_val, unsigned int uint_val, double double_val, int type)
Definition at line 2023 of file PlyFile.cpp.
References native_binary_type, PLY_CHAR, PLY_DOUBLE, PLY_FLOAT, PLY_FLOAT_32, PLY_FLOAT_64, PLY_INT, PLY_INT_16, PLY_INT_32, PLY_INT_8, PLY_SHORT, ply_type_size, PLY_UCHAR, PLY_UINT, PLY_UINT_16, PLY_UINT_32, PLY_UINT_8, PLY_USHORT, swap_bytes(), and type.
Referenced by ply_put_element().
write_scalar_type()
void write_scalar_type (FILE * fp, int code)
Definition at line 1759 of file PlyFile.cpp.
References PLY_END_TYPE, and type_names.
Referenced by ply_header_complete().
Variable Documentation
native_binary_type
int native_binary_type = -1 static
Definition at line 90 of file PlyFile.cpp.
Referenced by get_binary_item(), get_native_binary_type(), ply_read_custom(), ply_write_custom(), and write_binary_item().
ply_type_size
int ply_type_size[]
Initial value:
= {
    0,
    1,
    2,
    4,
    1,
    2,
    4,
    4,
    8,
    1,
    1,
    2,
    2,
    4,
    4,
    4,
    8
}
Definition at line 63 of file PlyFile.cpp.
Referenced by ascii_get_element(), binary_get_element(), check_types(), get_binary_item(), ply_put_element(), setup_other_props(), and write_binary_item().
type_names
const char* type_names[]
Initial value:
= {
    "invalid",
    "char",
    "short",
    "int",
    "uchar",
    "ushort",
    "uint",
    "float",
    "double",
    "int8",
    "uint8",
    "int16",
    "uint16",
    "int32",
    "uint32",
    "float32",
    "float64",
}
Definition at line 41 of file PlyFile.cpp.
Referenced by get_prop_type(), and write_scalar_type().
types_checked
int types_checked = 0 static
Definition at line 91 of file PlyFile.cpp.
Referenced by check_types(), ply_read_custom(), and ply_write_custom().