ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/pmetis.c File Reference
pmetis.c File Reference
#include "metis.h"
Functions
void METIS_PartGraphRecursive (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, int *options, int *edgecut, idxtype *part)
void METIS_WPartGraphRecursive (int *nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt, idxtype *adjwgt, int *wgtflag, int *numflag, int *nparts, float *tpwgts, int *options, int *edgecut, idxtype *part)
int MlevelRecursiveBisection (CtrlType *ctrl, GraphType *graph, int nparts, idxtype *part, float *tpwgts, float ubfactor, int fpart)
void MlevelEdgeBisection (CtrlType *ctrl, GraphType *graph, int *tpwgts, float ubfactor)
void SplitGraphPart (CtrlType *ctrl, GraphType *graph, GraphType *lgraph, GraphType *rgraph)
void SetUpSplitGraph (GraphType *graph, GraphType *sgraph, int snvtxs, int snedges)
Function Documentation
METIS_PartGraphRecursive()
void METIS_PartGraphRecursive (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 22 of file pmetis.c.
References fmalloc, and METIS_WPartGraphRecursive().
Referenced by METIS_PARTGRAPHRECURSIVE(), metis_partgraphrecursive(), metis_partgraphrecursive_(), and metis_partgraphrecursive__().
METIS_WPartGraphRecursive()
void METIS_WPartGraphRecursive (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 45 of file pmetis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, fmalloc, FreeWorkSpace, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, controldef::maxvwgt, MlevelRecursiveBisection(), OP_PMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PMETIS_CTYPE, PMETIS_DBGLVL, PMETIS_ITYPE, PMETIS_RTYPE, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by METIS_PartGraphRecursive(), METIS_WPARTGRAPHRECURSIVE(), metis_wpartgraphrecursive(), metis_wpartgraphrecursive_(), metis_wpartgraphrecursive__(), MlevelKWayPartitioning(), MlevelVolKWayPartitioning(), and MLKKMPartitioning().
MlevelEdgeBisection()
void MlevelEdgeBisection (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 168 of file pmetis.c.
References Coarsen2Way, Init2WayPartition, and Refine2Way.
Referenced by MlevelRecursiveBisection().
MlevelRecursiveBisection()
int MlevelRecursiveBisection (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * part, float * tpwgts, float ubfactor, int fpart)
Definition at line 103 of file pmetis.c.
References cloudViewer::utility::floor(), graphdef::gdata, GKfree, idxsum, graphdef::label, LTERM, graphdef::mincut, MlevelEdgeBisection(), graphdef::nvtxs, graphdef::rdata, SplitGraphPart(), sscale, ssum, graphdef::vwgt, and graphdef::where.
Referenced by METIS_WPartGraphRecursive().
SetUpSplitGraph()
void SetUpSplitGraph (GraphType * graph, GraphType * sgraph, int snvtxs, int snedges)
Definition at line 309 of file pmetis.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::cmap, fmalloc, graphdef::gdata, idxmalloc, InitGraph, graphdef::label, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::nvwgt, graphdef::vwgt, and graphdef::xadj.
SplitGraphPart()
void SplitGraphPart (CtrlType * ctrl, GraphType * graph, GraphType * lgraph, GraphType * rgraph)
Definition at line 190 of file pmetis.c.
Referenced by MlevelRecursiveBisection().