ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/point3d_test.cc File Reference
point3d_test.cc File Reference
#include "util/testing.h"
#include "base/point3d.h"
Macros
#define TEST_NAME "base/point3d"
Functions
BOOST_AUTO_TEST_CASE (TestDefault)
BOOST_AUTO_TEST_CASE (TestXYZ)
BOOST_AUTO_TEST_CASE (TestRGB)
BOOST_AUTO_TEST_CASE (TestError)
BOOST_AUTO_TEST_CASE (TestTrack)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/point3d"
Definition at line 32 of file point3d_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/5]
BOOST_AUTO_TEST_CASE (TestDefault)
Definition at line 39 of file point3d_test.cc.
References colmap::Point3D::Color(), colmap::Point3D::Error(), colmap::Point3D::HasError(), colmap::Track::Length(), colmap::Point3D::Track(), colmap::Point3D::X(), colmap::Point3D::XYZ(), colmap::Point3D::Y(), and colmap::Point3D::Z().
BOOST_AUTO_TEST_CASE() [2/5]
BOOST_AUTO_TEST_CASE (TestError)
Definition at line 90 of file point3d_test.cc.
References colmap::Point3D::Error(), colmap::Point3D::HasError(), and colmap::Point3D::SetError().
BOOST_AUTO_TEST_CASE() [3/5]
BOOST_AUTO_TEST_CASE (TestRGB)
Definition at line 79 of file point3d_test.cc.
References colmap::Point3D::Color(), and colmap::Point3D::SetColor().
BOOST_AUTO_TEST_CASE() [4/5]
BOOST_AUTO_TEST_CASE (TestTrack)
Definition at line 102 of file point3d_test.cc.
References colmap::Track::AddElement(), colmap::Track::Length(), colmap::Point3D::SetTrack(), and colmap::Point3D::Track().
BOOST_AUTO_TEST_CASE() [5/5]
BOOST_AUTO_TEST_CASE (TestXYZ)
Definition at line 55 of file point3d_test.cc.
References colmap::Point3D::SetXYZ(), colmap::Point3D::X(), colmap::Point3D::XYZ(), colmap::Point3D::Y(), and colmap::Point3D::Z().