ACloudViewer: /root/ACloudViewer/plugins/core/Standard/q3DMASC/PointFeature.cpp File Reference
PointFeature.cpp File Reference
#include "PointFeature.h"
#include "q3DMASCTools.h"
#include "../../../core/IO/qLASIO/include/LasDetails.h"
#include <ecvPointCloud.h>
#include <ecvScalarField.h>
#include <WeibullDistribution.h>
#include <assert.h>
#include <QCoreApplication>
#include <QMutex>
Enumerations
enum LAS_FIELDS {
LAS_X = 0 , LAS_Y = 1 , LAS_Z = 2 , LAS_INTENSITY = 3 ,
LAS_RETURN_NUMBER = 4 , LAS_NUMBER_OF_RETURNS = 5 , LAS_SCAN_DIRECTION = 6 , LAS_FLIGHT_LINE_EDGE = 7 ,
LAS_CLASSIFICATION = 8 , LAS_SCAN_ANGLE_RANK = 9 , LAS_USER_DATA = 10 , LAS_POINT_SOURCE_ID = 11 ,
LAS_RED = 12 , LAS_GREEN = 13 , LAS_BLUE = 14 , LAS_TIME = 15 ,
LAS_EXTRA = 16 , LAS_CLASSIF_VALUE = 17 , LAS_CLASSIF_SYNTHETIC = 18 , LAS_CLASSIF_KEYPOINT = 19 ,
LAS_CLASSIF_WITHHELD = 20 , LAS_CLASSIF_OVERLAP = 21 , LAS_INVALID = 255 , LAS_X = 0 ,
LAS_Y = 1 , LAS_Z = 2 , LAS_INTENSITY = 3 , LAS_RETURN_NUMBER = 4 ,
LAS_NUMBER_OF_RETURNS = 5 , LAS_SCAN_DIRECTION = 6 , LAS_FLIGHT_LINE_EDGE = 7 , LAS_CLASSIFICATION = 8 ,
LAS_SCAN_ANGLE_RANK = 9 , LAS_USER_DATA = 10 , LAS_POINT_SOURCE_ID = 11 , LAS_RED = 12 ,
LAS_GREEN = 13 , LAS_BLUE = 14 , LAS_TIME = 15 , LAS_EXTRA = 16 ,
LAS_CLASSIF_VALUE = 17 , LAS_CLASSIF_SYNTHETIC = 18 , LAS_CLASSIF_KEYPOINT = 19 , LAS_CLASSIF_WITHHELD = 20 ,
LAS_CLASSIF_OVERLAP = 21 , LAS_INVALID = 255
}
Functions
static bool ComputeMathOpWithNearestNeighbor (const CorePoints &corePoints, const IScalarFieldWrapper &field1, cloudViewer::ScalarField *outSF, ccPointCloud &cloud2, const IScalarFieldWrapper &field2, masc::Feature::Operation op, QString &error, cloudViewer::GenericProgressCallback *progressCb=nullptr)
Variables
constexpr const char * LAS_FIELD_NAMES [22]
static const char * s_echoRatioSFName = "EchoRat"
static const char * s_NIRSFName = "NIR"
static const char * s_M3C2SFName = "M3C2 distance"
static const char * s_PCVSFName = "Illuminance (PCV)"
static const char * s_normDipSFName = "Norm dip"
static const char * s_normDipDirSFName = "Norm dip dir."
Enumeration Type Documentation
LAS_FIELDS
enum LAS_FIELDS
Enumerator
LAS_X
LAS_Y
LAS_Z
LAS_INTENSITY
LAS_RETURN_NUMBER
LAS_NUMBER_OF_RETURNS
LAS_SCAN_DIRECTION
LAS_FLIGHT_LINE_EDGE
LAS_CLASSIFICATION
LAS_SCAN_ANGLE_RANK
LAS_USER_DATA
LAS_POINT_SOURCE_ID
LAS_RED
LAS_GREEN
LAS_BLUE
LAS_TIME
LAS_EXTRA
LAS_CLASSIF_VALUE
LAS_CLASSIF_SYNTHETIC
LAS_CLASSIF_KEYPOINT
LAS_CLASSIF_WITHHELD
LAS_CLASSIF_OVERLAP
LAS_INVALID
LAS_X
LAS_Y
LAS_Z
LAS_INTENSITY
LAS_RETURN_NUMBER
LAS_NUMBER_OF_RETURNS
LAS_SCAN_DIRECTION
LAS_FLIGHT_LINE_EDGE
LAS_CLASSIFICATION
LAS_SCAN_ANGLE_RANK
LAS_USER_DATA
LAS_POINT_SOURCE_ID
LAS_RED
LAS_GREEN
LAS_BLUE
LAS_TIME
LAS_EXTRA
LAS_CLASSIF_VALUE
LAS_CLASSIF_SYNTHETIC
LAS_CLASSIF_KEYPOINT
LAS_CLASSIF_WITHHELD
LAS_CLASSIF_OVERLAP
LAS_INVALID
Definition at line 22 of file PointFeature.cpp.
Function Documentation
ComputeMathOpWithNearestNeighbor()
static bool ComputeMathOpWithNearestNeighbor (const CorePoints & corePoints, const IScalarFieldWrapper & field1, cloudViewer::ScalarField * outSF, ccPointCloud & cloud2, const IScalarFieldWrapper & field2, masc::Feature::Operation op, QString & error, cloudViewer::GenericProgressCallback * progressCb = nullptr) static
Definition at line 380 of file PointFeature.cpp.
References cloudViewer::ScalarField::computeMinAndMax(), ccGenericPointCloud::computeOctree(), corePoints, error(), cloudViewer::DgmOctree::findBestLevelForAGivenPopulationPerCell(), cloudViewer::DgmOctree::findPointNeighbourhood(), ccObject::getName(), ccGenericPointCloud::getOctree(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, NAN_VALUE, masc::Feature::NO_OPERATION, nProgress, octree, octreeLevel, cloudViewer::NormalizedProgress::oneStep(), masc::Feature::PerformMathOp(), IScalarFieldWrapper::pointValue(), CVLog::Print(), cloudViewer::ScalarField::setValue(), and cloudViewer::GenericCloud::size().
Referenced by masc::PointFeature::prepare().
Variable Documentation
LAS_FIELD_NAMES
constexpr const char* LAS_FIELD_NAMES[22] constexpr
Initial value:
= {
        "X",
        "Y",
        "Z",
        LasNames::Intensity,
        LasNames::ReturnNumber,
        LasNames::NumberOfReturns,
        LasNames::ScanDirectionFlag,
        LasNames::EdgeOfFlightLine,
        LasNames::Classification,
        LasNames::ScanAngleRank,
        LasNames::UserData,
        LasNames::PointSourceId,
        "Red",
        "Green",
        "Blue",
        LasNames::GpsTime,
        "extra",
        "[Classif] Value",
        "[Classif] Synthetic flag",
        "[Classif] Key-point flag",
        "[Classif] Withheld flag",
        "[Classif] Overlap flag",
}
Definition at line 50 of file PointFeature.cpp.
Referenced by masc::PointFeature::checkValidity(), and masc::PointFeature::retrieveField().
s_echoRatioSFName
const char* s_echoRatioSFName = "EchoRat" static
Definition at line 90 of file PointFeature.cpp.
s_M3C2SFName
const char* s_M3C2SFName = "M3C2 distance" static
Definition at line 92 of file PointFeature.cpp.
Referenced by masc::PointFeature::checkValidity(), and masc::PointFeature::retrieveField().
s_NIRSFName
const char* s_NIRSFName = "NIR" static
Definition at line 91 of file PointFeature.cpp.
Referenced by masc::PointFeature::checkValidity(), and masc::PointFeature::retrieveField().
s_normDipDirSFName
const char* s_normDipDirSFName = "Norm dip dir." static
Definition at line 95 of file PointFeature.cpp.
s_normDipSFName
const char* s_normDipSFName = "Norm dip" static
Definition at line 94 of file PointFeature.cpp.
s_PCVSFName
const char* s_PCVSFName = "Illuminance (PCV)" static
Definition at line 93 of file PointFeature.cpp.
Referenced by masc::PointFeature::checkValidity(), and masc::PointFeature::retrieveField().