ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPoissonRecon/extern/Src_CC_wrap/PoissonReconLib.cpp File Reference
PoissonReconLib.cpp File Reference
#include "PoissonReconLib.h"
#include <cassert>
#include "../Src/FEMTree.h"
#include "PointData.h"
Classes
class Vertex< _Real >
class PointStream< Real >
struct FEMTreeProfiler< Dim, Real >
struct ConstraintDual< Dim, Real >
struct SystemDual< Dim, Real >
struct SystemDual< Dim, double >
Functions
template<class Real , unsigned int Dim>
XForm< Real, Dim+1 > GetBoundingBoxXForm (Point< Real, Dim > min, Point< Real, Dim > max, Real scaleFactor)
template<class Real , unsigned int Dim>
XForm< Real, Dim+1 > GetBoundingBoxXForm (Point< Real, Dim > min, Point< Real, Dim > max, Real width, Real scaleFactor, int &depth)
template<class Real , unsigned int Dim>
XForm< Real, Dim+1 > GetPointXForm (InputPointStream< Real, Dim > &stream, Real width, Real scaleFactor, int &depth)
template<class Real , unsigned int Dim>
XForm< Real, Dim+1 > GetPointXForm (InputPointStream< Real, Dim > &stream, Real scaleFactor)
template<typename Vertex , typename Real , typename SetVertexFunction , unsigned int... FEMSigs, typename... SampleData>
void ExtractMesh (const PoissonReconLib::Parameters &params, UIntPack< FEMSigs... >, std::tuple< SampleData... >, FEMTree< sizeof...(FEMSigs), Real > &tree, const DenseNodeData< Real, UIntPack< FEMSigs... >> &solution, Real isoValue, const std::vector< typename FEMTree< sizeof...(FEMSigs), Real >::PointSample > *samples, std::vector< PointData< Real >> *sampleData, const typename FEMTree< sizeof...(FEMSigs), Real >::template DensityEstimator< WEIGHT_DEGREE > *density, const SetVertexFunction &SetVertex, XForm< Real, sizeof...(FEMSigs)+1 > iXForm, PoissonReconLib::IMesh< Real > &out_mesh)
template<class Real , typename... SampleData, unsigned int... FEMSigs>
static bool Execute (PointStream< Real > &pointStream, PoissonReconLib::IMesh< Real > &out_mesh, const PoissonReconLib::Parameters &params, UIntPack< FEMSigs... >)
Function Documentation
Execute()
template<class Real , typename... SampleData, unsigned int... FEMSigs> static bool Execute (PointStream< Real > & pointStream, PoissonReconLib::IMesh< Real > & out_mesh, const PoissonReconLib::Parameters & params, UIntPack< FEMSigs... >) static
Definition at line 374 of file PoissonReconLib.cpp.
References PointData< Real >::normal, NORMAL_DEGREE, params, and PointStream< Real >::xform.
ExtractMesh()
template<typename Vertex , typename Real , typename SetVertexFunction , unsigned int... FEMSigs, typename... SampleData> void ExtractMesh (const PoissonReconLib::Parameters & params, UIntPack< FEMSigs... > , std::tuple< SampleData... > , FEMTree< sizeof...(FEMSigs), Real > & tree, const DenseNodeData< Real, UIntPack< FEMSigs... >> & solution, Real isoValue, const std::vector< typename FEMTree< sizeof...(FEMSigs), Real >::PointSample > * samples, std::vector< PointData< Real >> * sampleData, const typename FEMTree< sizeof...(FEMSigs), Real >::template DensityEstimator< WEIGHT_DEGREE > * density, const SetVertexFunction & SetVertex, XForm< Real, sizeof...(FEMSigs)+1 > iXForm, PoissonReconLib::IMesh< Real > & out_mesh)
Definition at line 284 of file PoissonReconLib.cpp.
References PoissonReconLib::IMesh< Real >::addColor(), PoissonReconLib::IMesh< Real >::addDensity(), PoissonReconLib::IMesh< Real >::addTriangle(), PoissonReconLib::IMesh< Real >::addVertex(), color, PointData< Real >::color, cloudViewer::utility::Extract(), CoredVectorMeshData< Vertex >::nextOutOfCorePoint(), CoredVectorMeshData< Vertex >::nextPolygon(), CoredVectorMeshData< Vertex >::outOfCorePointCount(), params, Vertex< _Real >::point, CoredVectorMeshData< Vertex >::polygonCount(), CoredVectorMeshData< Vertex >::resetIterator(), and Vertex< _Real >::w.
GetBoundingBoxXForm() [1/2]
template<class Real , unsigned int Dim> XForm<Real, Dim + 1> GetBoundingBoxXForm (Point< Real, Dim > min, Point< Real, Dim > max, Real scaleFactor)
Definition at line 166 of file PoissonReconLib.cpp.
References max(), and min().
Referenced by GetPointXForm().
GetBoundingBoxXForm() [2/2]
template<class Real , unsigned int Dim> XForm<Real, Dim + 1> GetBoundingBoxXForm (Point< Real, Dim > min, Point< Real, Dim > max, Real width, Real scaleFactor, int & depth)
Definition at line 188 of file PoissonReconLib.cpp.
References max(), min(), and width.
GetPointXForm() [1/2]
template<class Real , unsigned int Dim> XForm<Real, Dim + 1> GetPointXForm (InputPointStream< Real, Dim > & stream, Real scaleFactor)
Definition at line 230 of file PoissonReconLib.cpp.
References GetBoundingBoxXForm(), max(), and min().
GetPointXForm() [2/2]
template<class Real , unsigned int Dim> XForm<Real, Dim + 1> GetPointXForm (InputPointStream< Real, Dim > & stream, Real width, Real scaleFactor, int & depth)
Definition at line 220 of file PoissonReconLib.cpp.
References GetBoundingBoxXForm(), max(), min(), and width.