ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/Polyline.cpp File Reference
Polyline.cpp File Reference
#include <pybind11/pybind11.h>
#include <Polyline.h>
Functions
void define_Polyline (py::module &cccorelib)
Function Documentation
define_Polyline()
void define_Polyline (py::module & cccorelib)
Definition at line 15 of file Polyline.cpp.
References cloudViewer::Polyline::clear(), cloudViewer::Polyline::isClosed(), and cloudViewer::Polyline::setClosed().
Referenced by define_cccorelib().