ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/pose_test.cc File Reference
pose_test.cc File Reference
#include "util/testing.h"
#include <Eigen/Core>
#include "base/pose.h"
#include "base/projection.h"
#include "util/math.h"
Macros
#define TEST_NAME "base/pose"
Functions
BOOST_AUTO_TEST_CASE (TestCrossProductMatrix)
BOOST_AUTO_TEST_CASE (TestEulerAnglesX)
BOOST_AUTO_TEST_CASE (TestEulerAnglesY)
BOOST_AUTO_TEST_CASE (TestEulerAnglesZ)
BOOST_AUTO_TEST_CASE (TestEulerAnglesXYZ)
BOOST_AUTO_TEST_CASE (TestQuaternionToRotationMatrix)
BOOST_AUTO_TEST_CASE (TestComposeIdentityQuaternion)
BOOST_AUTO_TEST_CASE (TestNormalizeQuaternion)
BOOST_AUTO_TEST_CASE (TestInvertQuaternion)
BOOST_AUTO_TEST_CASE (TestConcatenateQuaternions)
BOOST_AUTO_TEST_CASE (TestQuaternionRotatePoint)
BOOST_AUTO_TEST_CASE (TestAverageQuaternions)
BOOST_AUTO_TEST_CASE (TestRotationFromUnitVectors)
BOOST_AUTO_TEST_CASE (TestPoseFromProjectionMatrix)
BOOST_AUTO_TEST_CASE (TestPoseFromProjectionParameters)
BOOST_AUTO_TEST_CASE (TestComputeRelativePose)
BOOST_AUTO_TEST_CASE (TestConcatenatePoses)
BOOST_AUTO_TEST_CASE (TestInvertPose)
BOOST_AUTO_TEST_CASE (TestInterpolatePose)
BOOST_AUTO_TEST_CASE (TestCalculateBaseline)
BOOST_AUTO_TEST_CASE (TestCheckCheirality)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/pose"
Definition at line 32 of file pose_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/21]
BOOST_AUTO_TEST_CASE (TestAverageQuaternions)
Definition at line 188 of file pose_test.cc.
References colmap::AverageQuaternions(), colmap::ComposeIdentityQuaternion(), and e.
BOOST_AUTO_TEST_CASE() [2/21]
BOOST_AUTO_TEST_CASE (TestCalculateBaseline)
Definition at line 382 of file pose_test.cc.
References colmap::CalculateBaseline(), and e.
BOOST_AUTO_TEST_CASE() [3/21]
BOOST_AUTO_TEST_CASE (TestCheckCheirality)
Definition at line 398 of file pose_test.cc.
References colmap::CheckCheirality().
BOOST_AUTO_TEST_CASE() [4/21]
BOOST_AUTO_TEST_CASE (TestComposeIdentityQuaternion)
Definition at line 117 of file pose_test.cc.
References colmap::ComposeIdentityQuaternion().
BOOST_AUTO_TEST_CASE() [5/21]
BOOST_AUTO_TEST_CASE (TestComputeRelativePose)
Definition at line 272 of file pose_test.cc.
References colmap::ComposeIdentityQuaternion(), colmap::ComputeRelativePose(), and e.
BOOST_AUTO_TEST_CASE() [6/21]
BOOST_AUTO_TEST_CASE (TestConcatenatePoses)
Definition at line 313 of file pose_test.cc.
References colmap::ComposeIdentityQuaternion(), colmap::ComputeRelativePose(), colmap::ConcatenatePoses(), and colmap::NormalizeQuaternion().
BOOST_AUTO_TEST_CASE() [7/21]
BOOST_AUTO_TEST_CASE (TestConcatenateQuaternions)
Definition at line 148 of file pose_test.cc.
References colmap::ComposeIdentityQuaternion(), colmap::ConcatenateQuaternions(), and colmap::InvertQuaternion().
BOOST_AUTO_TEST_CASE() [8/21]
BOOST_AUTO_TEST_CASE (TestCrossProductMatrix)
Definition at line 43 of file pose_test.cc.
References colmap::CrossProductMatrix().
BOOST_AUTO_TEST_CASE() [9/21]
BOOST_AUTO_TEST_CASE (TestEulerAnglesX)
Definition at line 51 of file pose_test.cc.
References e, colmap::EulerAnglesToRotationMatrix(), and colmap::RotationMatrixToEulerAngles().
BOOST_AUTO_TEST_CASE() [10/21]
BOOST_AUTO_TEST_CASE (TestEulerAnglesXYZ)
Definition at line 93 of file pose_test.cc.
References e, colmap::EulerAnglesToRotationMatrix(), and colmap::RotationMatrixToEulerAngles().
BOOST_AUTO_TEST_CASE() [11/21]
BOOST_AUTO_TEST_CASE (TestEulerAnglesY)
Definition at line 65 of file pose_test.cc.
References e, colmap::EulerAnglesToRotationMatrix(), and colmap::RotationMatrixToEulerAngles().
BOOST_AUTO_TEST_CASE() [12/21]
BOOST_AUTO_TEST_CASE (TestEulerAnglesZ)
Definition at line 79 of file pose_test.cc.
References e, colmap::EulerAnglesToRotationMatrix(), and colmap::RotationMatrixToEulerAngles().
BOOST_AUTO_TEST_CASE() [13/21]
BOOST_AUTO_TEST_CASE (TestInterpolatePose)
Definition at line 363 of file pose_test.cc.
References colmap::InterpolatePose().
BOOST_AUTO_TEST_CASE() [14/21]
BOOST_AUTO_TEST_CASE (TestInvertPose)
Definition at line 347 of file pose_test.cc.
References colmap::ComposeIdentityQuaternion(), and colmap::InvertPose().
BOOST_AUTO_TEST_CASE() [15/21]
BOOST_AUTO_TEST_CASE (TestInvertQuaternion)
Definition at line 138 of file pose_test.cc.
References colmap::ComposeIdentityQuaternion(), and colmap::InvertQuaternion().
BOOST_AUTO_TEST_CASE() [16/21]
BOOST_AUTO_TEST_CASE (TestNormalizeQuaternion)
Definition at line 121 of file pose_test.cc.
References colmap::ComposeIdentityQuaternion(), and colmap::NormalizeQuaternion().
BOOST_AUTO_TEST_CASE() [17/21]
BOOST_AUTO_TEST_CASE (TestPoseFromProjectionMatrix)
Definition at line 254 of file pose_test.cc.
References colmap::ComposeProjectionMatrix(), e, colmap::InvertProjectionMatrix(), and colmap::ProjectionCenterFromMatrix().
BOOST_AUTO_TEST_CASE() [18/21]
BOOST_AUTO_TEST_CASE (TestPoseFromProjectionParameters)
Definition at line 263 of file pose_test.cc.
References colmap::ComposeProjectionMatrix(), e, colmap::InvertProjectionMatrix(), and colmap::ProjectionCenterFromPose().
BOOST_AUTO_TEST_CASE() [19/21]
BOOST_AUTO_TEST_CASE (TestQuaternionRotatePoint)
Definition at line 168 of file pose_test.cc.
References colmap::ComposeIdentityQuaternion(), colmap::EulerAnglesToRotationMatrix(), M_PI, colmap::QuaternionRotatePoint(), and colmap::RotationMatrixToQuaternion().
BOOST_AUTO_TEST_CASE() [20/21]
BOOST_AUTO_TEST_CASE (TestQuaternionToRotationMatrix)
Definition at line 107 of file pose_test.cc.
References colmap::EulerAnglesToRotationMatrix(), colmap::QuaternionToRotationMatrix(), and colmap::RotationMatrixToQuaternion().
BOOST_AUTO_TEST_CASE() [21/21]
BOOST_AUTO_TEST_CASE (TestRotationFromUnitVectors)
Definition at line 228 of file pose_test.cc.
References colmap::RotationFromUnitVectors().