ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/pqueue.c File Reference
pqueue.c File Reference
#include "metis.h"
Functions
void PQueueInit (CtrlType *ctrl, PQueueType *queue, int maxnodes, int maxgain)
void PQueueReset (PQueueType *queue)
void PQueueFree (CtrlType *ctrl, PQueueType *queue)
int PQueueGetSize (PQueueType *queue)
int PQueueInsert (PQueueType *queue, int node, int gain)
int PQueueDelete (PQueueType *queue, int node, int gain)
int PQueueUpdate (PQueueType *queue, int node, int oldgain, int newgain)
void PQueueUpdateUp (PQueueType *queue, int node, int oldgain, int newgain)
int PQueueGetMax (PQueueType *queue)
int PQueueSeeMax (PQueueType *queue)
int PQueueGetKey (PQueueType *queue)
int CheckHeap (PQueueType *queue)
Function Documentation
CheckHeap()
int CheckHeap (PQueueType * queue)
Definition at line 551 of file pqueue.c.
References ASSERT, ASSERTP, PQueueType::heap, PQueueType::locator, PQueueType::maxnodes, and PQueueType::nnodes.
Referenced by PQueueDelete(), PQueueGetMax(), PQueueInsert(), PQueueUpdate(), and PQueueUpdateUp().
PQueueDelete()
int PQueueDelete (PQueueType * queue, int node, int gain)
Definition at line 197 of file pqueue.c.
References ASSERT, PQueueType::buckets, CheckHeap(), PQueueType::heap, KeyValueType::key, PQueueType::locator, PQueueType::maxgain, ListNodeType::next, PQueueType::ngainspan, PQueueType::nnodes, PQueueType::nodes, NULL, ListNodeType::prev, PQueueType::type, and KeyValueType::val.
Referenced by PQueueUpdate().
PQueueFree()
void PQueueFree (CtrlType * ctrl, PQueueType * queue)
Definition at line 104 of file pqueue.c.
References PQueueType::buckets, GKfree, idxwspacefree, LTERM, PQueueType::maxnodes, PQueueType::mustfree, PQueueType::ngainspan, PQueueType::nodes, PQueueType::pgainspan, and PQueueType::type.
PQueueGetKey()
int PQueueGetKey (PQueueType * queue)
Definition at line 530 of file pqueue.c.
References PQueueType::heap, KeyValueType::key, PQueueType::maxgain, PQueueType::nnodes, and PQueueType::type.
Referenced by SelectQueue(), SelectQueue2(), SelectQueue3(), and SelectQueueOneWay2().
PQueueGetMax()
int PQueueGetMax (PQueueType * queue)
Definition at line 440 of file pqueue.c.
References ASSERT, PQueueType::buckets, CheckHeap(), PQueueType::heap, ListNodeType::id, KeyValueType::key, PQueueType::locator, PQueueType::maxgain, ListNodeType::next, PQueueType::ngainspan, PQueueType::nnodes, NULL, ListNodeType::prev, PQueueType::type, and KeyValueType::val.
PQueueGetSize()
int PQueueGetSize (PQueueType * queue)
Definition at line 129 of file pqueue.c.
References PQueueType::nnodes.
Referenced by SelectQueue(), SelectQueue2(), SelectQueue3(), SelectQueueOneWay(), and SelectQueueOneWay2().
PQueueInit()
void PQueueInit (CtrlType * ctrl, PQueueType * queue, int maxnodes, int maxgain)
Definition at line 23 of file pqueue.c.
References amin, PQueueType::buckets, PQueueType::heap, ListNodeType::id, idxmalloc, idxset, idxwspacemalloc, PQueueType::locator, PQueueType::maxgain, PQueueType::maxnodes, PQueueType::mustfree, NEG_GAINSPAN, PQueueType::ngainspan, PQueueType::nnodes, PQueueType::nodes, NULL, PQueueType::pgainspan, PLUS_GAINSPAN, PQueueType::type, and WspaceAvail.
PQueueInsert()
int PQueueInsert (PQueueType * queue, int node, int gain)
Definition at line 138 of file pqueue.c.
References ASSERT, PQueueType::buckets, CheckHeap(), PQueueType::heap, KeyValueType::key, PQueueType::locator, PQueueType::maxgain, ListNodeType::next, PQueueType::ngainspan, PQueueType::nnodes, PQueueType::nodes, NULL, ListNodeType::prev, PQueueType::type, and KeyValueType::val.
Referenced by PQueueUpdate().
PQueueReset()
void PQueueReset (PQueueType * queue)
Definition at line 80 of file pqueue.c.
References PQueueType::buckets, idxset, PQueueType::locator, PQueueType::maxgain, PQueueType::maxnodes, PQueueType::ngainspan, PQueueType::nnodes, NULL, PQueueType::pgainspan, and PQueueType::type.
PQueueSeeMax()
int PQueueSeeMax (PQueueType * queue)
Definition at line 511 of file pqueue.c.
References PQueueType::buckets, PQueueType::heap, ListNodeType::id, PQueueType::maxgain, PQueueType::nnodes, PQueueType::type, and KeyValueType::val.
PQueueUpdate()
int PQueueUpdate (PQueueType * queue, int node, int oldgain, int newgain)
Definition at line 293 of file pqueue.c.
References ASSERT, CheckHeap(), PQueueType::heap, KeyValueType::key, PQueueType::locator, PQueueType::nnodes, PQueueDelete(), PQueueInsert(), PQueueType::type, and KeyValueType::val.
PQueueUpdateUp()
void PQueueUpdateUp (PQueueType * queue, int node, int oldgain, int newgain)
Definition at line 367 of file pqueue.c.
References ASSERT, PQueueType::buckets, CheckHeap(), PQueueType::heap, KeyValueType::key, PQueueType::locator, PQueueType::maxgain, ListNodeType::next, PQueueType::ngainspan, PQueueType::nnodes, PQueueType::nodes, NULL, ListNodeType::prev, PQueueType::type, and KeyValueType::val.