ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/projection_test.cc File Reference
projection_test.cc File Reference
#include "util/testing.h"
#include <Eigen/Core>
#include "base/camera_models.h"
#include "base/pose.h"
#include "base/projection.h"
#include "util/math.h"
Macros
#define TEST_NAME "base/projection"
Functions
BOOST_AUTO_TEST_CASE (TestComposeProjectionMatrix)
BOOST_AUTO_TEST_CASE (TestInvertProjectionMatrix)
BOOST_AUTO_TEST_CASE (TestComputeClosestRotationMatrix)
BOOST_AUTO_TEST_CASE (TestDecomposeProjectionMatrix)
BOOST_AUTO_TEST_CASE (TestCalculateSquaredReprojectionError)
BOOST_AUTO_TEST_CASE (TestCalculateAngularError)
BOOST_AUTO_TEST_CASE (TestCalculateDepth)
BOOST_AUTO_TEST_CASE (TestHasPointPositiveDepth)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/projection"
Definition at line 32 of file projection_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/8]
BOOST_AUTO_TEST_CASE (TestCalculateAngularError)
Definition at line 126 of file projection_test.cc.
References colmap::CalculateAngularError(), colmap::ComposeIdentityQuaternion(), colmap::ComposeProjectionMatrix(), e, M_PI, colmap::SimplePinholeCameraModel::model_id, colmap::Camera::Params(), and colmap::Camera::SetModelId().
BOOST_AUTO_TEST_CASE() [2/8]
BOOST_AUTO_TEST_CASE (TestCalculateDepth)
Definition at line 180 of file projection_test.cc.
References colmap::CalculateDepth(), colmap::ComposeProjectionMatrix(), and e.
BOOST_AUTO_TEST_CASE() [3/8]
BOOST_AUTO_TEST_CASE (TestCalculateSquaredReprojectionError)
Definition at line 95 of file projection_test.cc.
References colmap::CalculateSquaredReprojectionError(), colmap::ComposeIdentityQuaternion(), colmap::ComposeProjectionMatrix(), e, colmap::Camera::InitializeWithId(), and colmap::SimplePinholeCameraModel::model_id.
BOOST_AUTO_TEST_CASE() [4/8]
BOOST_AUTO_TEST_CASE (TestComposeProjectionMatrix)
Definition at line 44 of file projection_test.cc.
References colmap::ComposeProjectionMatrix(), e, colmap::EulerAnglesToRotationMatrix(), and colmap::RotationMatrixToQuaternion().
BOOST_AUTO_TEST_CASE() [5/8]
BOOST_AUTO_TEST_CASE (TestComputeClosestRotationMatrix)
Definition at line 70 of file projection_test.cc.
References colmap::ComputeClosestRotationMatrix(), and e.
BOOST_AUTO_TEST_CASE() [6/8]
BOOST_AUTO_TEST_CASE (TestDecomposeProjectionMatrix)
Definition at line 76 of file projection_test.cc.
References colmap::ComposeProjectionMatrix(), colmap::DecomposeProjectionMatrix(), e, and colmap::EulerAnglesToRotationMatrix().
BOOST_AUTO_TEST_CASE() [7/8]
BOOST_AUTO_TEST_CASE (TestHasPointPositiveDepth)
Definition at line 200 of file projection_test.cc.
References colmap::ComposeProjectionMatrix(), and colmap::HasPointPositiveDepth().
BOOST_AUTO_TEST_CASE() [8/8]
BOOST_AUTO_TEST_CASE (TestInvertProjectionMatrix)
Definition at line 59 of file projection_test.cc.
References colmap::ComposeProjectionMatrix(), e, colmap::EulerAnglesToRotationMatrix(), and colmap::InvertProjectionMatrix().