ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/proto.h File Reference
proto.h File Reference
Functions
void Balance2Way (CtrlType *, GraphType *, int *, float)
void Bnd2WayBalance (CtrlType *, GraphType *, int *)
void General2WayBalance (CtrlType *, GraphType *, int *)
void BucketSortKeysInc (int, int, idxtype *, idxtype *, idxtype *)
void CreateCoarseGraph (CtrlType *, GraphType *, int, idxtype *, idxtype *)
void CreateCoarseGraphNoMask (CtrlType *, GraphType *, int, idxtype *, idxtype *)
void CreateCoarseGraph_NVW (CtrlType *, GraphType *, int, idxtype *, idxtype *)
GraphType * SetUpCoarseGraph (GraphType *, int, int)
void ReAdjustMemory (GraphType *, GraphType *, int)
GraphType * Coarsen2Way (CtrlType *, GraphType *)
void CompressGraph (CtrlType *, GraphType *, int, idxtype *, idxtype *, idxtype *, idxtype *)
void PruneGraph (CtrlType *, GraphType *, int, idxtype *, idxtype *, idxtype *, float)
int ComputeCut (GraphType *, idxtype *)
float ComputeRAsso (GraphType *graph, idxtype *where, int npart)
float ComputeNCut (GraphType *, idxtype *, int)
int CheckBnd (GraphType *)
int CheckBnd2 (GraphType *)
int CheckNodeBnd (GraphType *, int)
int CheckRInfo (RInfoType *)
int CheckNodePartitionParams (GraphType *)
int IsSeparable (GraphType *)
void METIS_EstimateMemory (int *, idxtype *, idxtype *, int *, int *, int *)
void EstimateCFraction (int, idxtype *, idxtype *, float *, float *)
int ComputeCoarseGraphSize (int, idxtype *, idxtype *, int, idxtype *, idxtype *, idxtype *)
void FM_2WayEdgeRefine (CtrlType *, GraphType *, int *, int)
void Change2CNumbering (int, idxtype *, idxtype *)
void Change2FNumbering (int, idxtype *, idxtype *, idxtype *)
void Change2FNumbering2 (int, idxtype *, idxtype *)
void Change2FNumberingOrder (int, idxtype *, idxtype *, idxtype *, idxtype *)
void ChangeMesh2CNumbering (int, idxtype *)
void ChangeMesh2FNumbering (int, idxtype *, int, idxtype *, idxtype *)
void ChangeMesh2FNumbering2 (int, idxtype *, int, int, idxtype *, idxtype *)
void METIS_PARTGRAPHRECURSIVE (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void metis_partgraphrecursive (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void metis_partgraphrecursive_ (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void metis_partgraphrecursive__ (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void METIS_WPARTGRAPHRECURSIVE (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void metis_wpartgraphrecursive (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void metis_wpartgraphrecursive_ (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void metis_wpartgraphrecursive__ (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void METIS_PARTGRAPHKWAY (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void metis_partgraphkway (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void metis_partgraphkway_ (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void metis_partgraphkway__ (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void METIS_WPARTGRAPHKWAY (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void metis_wpartgraphkway (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void metis_wpartgraphkway_ (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void metis_wpartgraphkway__ (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void METIS_EDGEND (int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_edgend (int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_edgend_ (int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_edgend__ (int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void METIS_NODEND (int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_nodend (int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_nodend_ (int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_nodend__ (int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void METIS_NODEWND (int *, idxtype *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_nodewnd (int *, idxtype *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_nodewnd_ (int *, idxtype *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_nodewnd__ (int *, idxtype *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void METIS_PARTMESHNODAL (int *, int *, idxtype *, int *, int *, int *, int *, idxtype *, idxtype *)
void metis_partmeshnodal (int *, int *, idxtype *, int *, int *, int *, int *, idxtype *, idxtype *)
void metis_partmeshnodal_ (int *, int *, idxtype *, int *, int *, int *, int *, idxtype *, idxtype *)
void metis_partmeshnodal__ (int *, int *, idxtype *, int *, int *, int *, int *, idxtype *, idxtype *)
void METIS_PARTMESHDUAL (int *, int *, idxtype *, int *, int *, int *, int *, idxtype *, idxtype *)
void metis_partmeshdual (int *, int *, idxtype *, int *, int *, int *, int *, idxtype *, idxtype *)
void metis_partmeshdual_ (int *, int *, idxtype *, int *, int *, int *, int *, idxtype *, idxtype *)
void metis_partmeshdual__ (int *, int *, idxtype *, int *, int *, int *, int *, idxtype *, idxtype *)
void METIS_MESHTONODAL (int *, int *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_meshtonodal (int *, int *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_meshtonodal_ (int *, int *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_meshtonodal__ (int *, int *, idxtype *, int *, int *, idxtype *, idxtype *)
void METIS_MESHTODUAL (int *, int *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_meshtodual (int *, int *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_meshtodual_ (int *, int *, idxtype *, int *, int *, idxtype *, idxtype *)
void metis_meshtodual__ (int *, int *, idxtype *, int *, int *, idxtype *, idxtype *)
void METIS_ESTIMATEMEMORY (int *, idxtype *, idxtype *, int *, int *, int *)
void metis_estimatememory (int *, idxtype *, idxtype *, int *, int *, int *)
void metis_estimatememory_ (int *, idxtype *, idxtype *, int *, int *, int *)
void metis_estimatememory__ (int *, idxtype *, idxtype *, int *, int *, int *)
void METIS_MCPARTGRAPHRECURSIVE (int *, int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void metis_mcpartgraphrecursive (int *, int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void metis_mcpartgraphrecursive_ (int *, int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void metis_mcpartgraphrecursive__ (int *, int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void METIS_MCPARTGRAPHKWAY (int *, int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void metis_mcpartgraphkway (int *, int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void metis_mcpartgraphkway_ (int *, int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void metis_mcpartgraphkway__ (int *, int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void METIS_PARTGRAPHVKWAY (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void metis_partgraphvkway (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void metis_partgraphvkway_ (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void metis_partgraphvkway__ (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void METIS_WPARTGRAPHVKWAY (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void metis_wpartgraphvkway (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void metis_wpartgraphvkway_ (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void metis_wpartgraphvkway__ (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void SetUpGraph (GraphType *, int, int, int, idxtype *, idxtype *, idxtype *, idxtype *, int)
void SetUpGraphKway (GraphType *, int, idxtype *, idxtype *)
void SetUpGraph2 (GraphType *, int, int, idxtype *, idxtype *, float *, idxtype *)
void VolSetUpGraph (GraphType *, int, int, int, idxtype *, idxtype *, idxtype *, idxtype *, int)
void RandomizeGraph (GraphType *)
int IsConnectedSubdomain (CtrlType *, GraphType *, int, int)
int IsConnected (CtrlType *, GraphType *, int)
int IsConnected2 (GraphType *, int)
int FindComponents (CtrlType *, GraphType *, idxtype *, idxtype *)
void Init2WayPartition (CtrlType *, GraphType *, int *, float)
void InitSeparator (CtrlType *, GraphType *, float)
void GrowBisection (CtrlType *, GraphType *, int *, float)
void GrowBisectionNode (CtrlType *, GraphType *, float)
void RandomBisection (CtrlType *, GraphType *, int *, float)
void spectralInit (GraphType *, int, int *, int *)
void MLKKM_PartGraphKway (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, int *, idxtype *, int)
void MLKKM_WPartGraphKway (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, float *, int *, int *, idxtype *, int)
int MLKKMPartitioning (CtrlType *, GraphType *, int, int, idxtype *, float *, float)
void Compute_Weights (CtrlType *ctrl, GraphType *graph, idxtype *w)
void transform_matrix (CtrlType *ctrl, GraphType *graph, idxtype *w, float *adjwgt)
void transform_matrix_half (CtrlType *ctrl, GraphType *graph, idxtype *w, float *adjwgt)
void pingpong (CtrlType *, GraphType *, int, int, float *, float, int)
void Weighted_kernel_k_means (CtrlType *, GraphType *, int, idxtype *, float *, float)
void remove_empty_clusters_l1 (CtrlType *ctrl, GraphType *graph, int nparts, idxtype *w, float *tpwgts, float ubfactor)
void remove_empty_clusters_l2 (CtrlType *ctrl, GraphType *graph, int nparts, idxtype *w, float *tpwgts, float ubfactor)
void MLKKMRefine (CtrlType *, GraphType *, GraphType *, int, int, float *, float)
float onePoint_move (GraphType *graph, int nparts, idxtype *sum, idxtype *squared_sum, idxtype *w, idxtype *self_sim, int **linearTerm, int ii)
void move1Point2EmptyCluster (GraphType *graph, int nparts, idxtype *sum, idxtype *squared_sum, idxtype *w, idxtype *self_sim, int **linearTerm, int k)
int local_search (CtrlType *, GraphType *, int, int, idxtype *, float *, float)
void METIS_PartGraphKway (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void METIS_WPartGraphKway (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
int MlevelKWayPartitioning (CtrlType *, GraphType *, int, idxtype *, float *, float)
void METIS_PartGraphVKway (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void METIS_WPartGraphVKway (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
int MlevelVolKWayPartitioning (CtrlType *, GraphType *, int, idxtype *, float *, float)
void Random_KWayEdgeRefine (CtrlType *, GraphType *, int, float *, float, int, int)
void Greedy_KWayEdgeRefine (CtrlType *, GraphType *, int, float *, float, int)
void Greedy_KWayEdgeBalance (CtrlType *, GraphType *, int, float *, float, int)
void RefineKWay (CtrlType *, GraphType *, GraphType *, int, float *, float)
void AllocateKWayPartitionMemory (CtrlType *, GraphType *, int)
void ComputeKWayPartitionParams (CtrlType *, GraphType *, int)
void ProjectKWayPartition (CtrlType *, GraphType *, int)
int IsBalanced (idxtype *, int, float *, float)
void ComputeKWayBoundary (CtrlType *, GraphType *, int)
void ComputeKWayBalanceBoundary (CtrlType *, GraphType *, int)
void Random_KWayVolRefine (CtrlType *, GraphType *, int, float *, float, int, int)
void Random_KWayVolRefineMConn (CtrlType *, GraphType *, int, float *, float, int, int)
void Greedy_KWayVolBalance (CtrlType *, GraphType *, int, float *, float, int)
void Greedy_KWayVolBalanceMConn (CtrlType *, GraphType *, int, float *, float, int)
void KWayVolUpdate (CtrlType *, GraphType *, int, int, int, idxtype *, idxtype *, idxtype *)
void ComputeKWayVolume (GraphType *, int, idxtype *, idxtype *, idxtype *)
int ComputeVolume (GraphType *, idxtype *)
void CheckVolKWayPartitionParams (CtrlType *, GraphType *, int)
void ComputeVolSubDomainGraph (GraphType *, int, idxtype *, idxtype *)
void EliminateVolSubDomainEdges (CtrlType *, GraphType *, int, float *)
void EliminateVolComponents (CtrlType *, GraphType *, int, float *, float)
void RefineVolKWay (CtrlType *, GraphType *, GraphType *, int, float *, float)
void AllocateVolKWayPartitionMemory (CtrlType *, GraphType *, int)
void ComputeVolKWayPartitionParams (CtrlType *, GraphType *, int)
void ComputeKWayVolGains (CtrlType *, GraphType *, int)
void ProjectVolKWayPartition (CtrlType *, GraphType *, int)
void ComputeVolKWayBoundary (CtrlType *, GraphType *, int)
void ComputeVolKWayBalanceBoundary (CtrlType *, GraphType *, int)
void Match_HEMN (CtrlType *ctrl, GraphType *graph)
void Match_RM (CtrlType *, GraphType *)
void Match_RM_NVW (CtrlType *, GraphType *)
void Match_HEM (CtrlType *, GraphType *)
void Match_SHEM (CtrlType *, GraphType *)
void Match_SHEMN (CtrlType *, GraphType *)
void MocBalance2Way (CtrlType *, GraphType *, float *, float)
void MocGeneral2WayBalance (CtrlType *, GraphType *, float *, float)
void MocBalance2Way2 (CtrlType *, GraphType *, float *, float *)
void MocGeneral2WayBalance2 (CtrlType *, GraphType *, float *, float *)
void SelectQueue3 (int, float *, float *, int *, int *, PQueueType[MAXNCON][2], float *)
GraphType * MCCoarsen2Way (CtrlType *, GraphType *)
void AllocateWorkSpace (CtrlType *, GraphType *, int)
void FreeWorkSpace (CtrlType *, GraphType *)
int WspaceAvail (CtrlType *)
idxtype * idxwspacemalloc (CtrlType *, int)
void idxwspacefree (CtrlType *, int)
float * fwspacemalloc (CtrlType *, int)
void fwspacefree (CtrlType *, int)
GraphType * CreateGraph (void)
void InitGraph (GraphType *)
void FreeGraph (GraphType *)
void METIS_MeshToDual (int *, int *, idxtype *, int *, int *, idxtype *, idxtype *)
void METIS_MeshToNodal (int *, int *, idxtype *, int *, int *, idxtype *, idxtype *)
void GENDUALMETIS (int, int, int, idxtype *, idxtype *, idxtype *adjncy)
void TRINODALMETIS (int, int, idxtype *, idxtype *, idxtype *adjncy)
void TETNODALMETIS (int, int, idxtype *, idxtype *, idxtype *adjncy)
void HEXNODALMETIS (int, int, idxtype *, idxtype *, idxtype *adjncy)
void QUADNODALMETIS (int, int, idxtype *, idxtype *, idxtype *adjncy)
void METIS_PartMeshNodal (int *, int *, idxtype *, int *, int *, int *, int *, idxtype *, idxtype *)
void METIS_PartMeshDual (int *, int *, idxtype *, int *, int *, int *, int *, idxtype *, idxtype *)
void MocFM_2WayEdgeRefine (CtrlType *, GraphType *, float *, int)
void SelectQueue (int, float *, float *, int *, int *, PQueueType[MAXNCON][2])
int BetterBalance (int, float *, float *, float *)
float Compute2WayHLoadImbalance (int, float *, float *)
void Compute2WayHLoadImbalanceVec (int, float *, float *, float *)
void MocFM_2WayEdgeRefine2 (CtrlType *, GraphType *, float *, float *, int)
void SelectQueue2 (int, float *, float *, int *, int *, PQueueType[MAXNCON][2], float *)
int IsBetter2wayBalance (int, float *, float *, float *)
void MinCover (idxtype *, idxtype *, int, int, idxtype *, int *)
int MinCover_Augment (idxtype *, idxtype *, int, idxtype *, idxtype *, idxtype *, int)
void MinCover_Decompose (idxtype *, idxtype *, int, int, idxtype *, idxtype *, int *)
void MinCover_ColDFS (idxtype *, idxtype *, int, idxtype *, idxtype *, int)
void MinCover_RowDFS (idxtype *, idxtype *, int, idxtype *, idxtype *, int)
void MocInit2WayPartition (CtrlType *, GraphType *, float *, float)
void MocGrowBisection (CtrlType *, GraphType *, float *, float)
void MocRandomBisection (CtrlType *, GraphType *, float *, float)
void MocInit2WayBalance (CtrlType *, GraphType *, float *)
int SelectQueueOneWay (int, float *, float *, int, PQueueType[MAXNCON][2])
void MocInit2WayPartition2 (CtrlType *, GraphType *, float *, float *)
void MocGrowBisection2 (CtrlType *, GraphType *, float *, float *)
void MocGrowBisectionNew2 (CtrlType *, GraphType *, float *, float *)
void MocInit2WayBalance2 (CtrlType *, GraphType *, float *, float *)
int SelectQueueOneWay2 (int, float *, PQueueType[MAXNCON][2], float *)
void METIS_mCPartGraphKway (int *, int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
int MCMlevelKWayPartitioning (CtrlType *, GraphType *, int, idxtype *, float *)
void MCRandom_KWayEdgeRefineHorizontal (CtrlType *, GraphType *, int, float *, int)
void MCGreedy_KWayEdgeBalanceHorizontal (CtrlType *, GraphType *, int, float *, int)
int AreAllHVwgtsBelow (int, float, float *, float, float *, float *)
int AreAllHVwgtsAbove (int, float, float *, float, float *, float *)
void ComputeHKWayLoadImbalance (int, int, float *, float *)
int MocIsHBalanced (int, int, float *, float *)
int IsHBalanceBetterFT (int, int, float *, float *, float *, float *)
int IsHBalanceBetterTT (int, int, float *, float *, float *, float *)
void MocRefineKWayHorizontal (CtrlType *, GraphType *, GraphType *, int, float *)
void MocAllocateKWayPartitionMemory (CtrlType *, GraphType *, int)
void MocComputeKWayPartitionParams (CtrlType *, GraphType *, int)
void MocProjectKWayPartition (CtrlType *, GraphType *, int)
void MocComputeKWayBalanceBoundary (CtrlType *, GraphType *, int)
void MCMatch_RM (CtrlType *, GraphType *)
void MCMatch_HEM (CtrlType *, GraphType *)
void MCMatch_SHEM (CtrlType *, GraphType *)
void MCMatch_SHEBM (CtrlType *, GraphType *, int)
void MCMatch_SBHEM (CtrlType *, GraphType *, int)
float BetterVBalance (int, int, float *, float *, float *)
int AreAllVwgtsBelowFast (int, float *, float *, float)
void genmmd (int, idxtype *, idxtype *, idxtype *, idxtype *, int, idxtype *, idxtype *, idxtype *, idxtype *, int, int *)
void mmdelm (int, idxtype *xadj, idxtype *, idxtype *, idxtype *, idxtype *, idxtype *, idxtype *, idxtype *, int, int)
int mmdint (int, idxtype *xadj, idxtype *, idxtype *, idxtype *, idxtype *, idxtype *, idxtype *, idxtype *)
void mmdnum (int, idxtype *, idxtype *, idxtype *)
void mmdupd (int, int, idxtype *, idxtype *, int, int *, idxtype *, idxtype *, idxtype *, idxtype *, idxtype *, idxtype *, int, int *tag)
void METIS_mCPartGraphRecursive (int *, int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void METIS_mCHPartGraphRecursive (int *, int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
int MCMlevelRecursiveBisection (CtrlType *, GraphType *, int, idxtype *, float, int)
int MCHMlevelRecursiveBisection (CtrlType *, GraphType *, int, idxtype *, float *, int)
void MCMlevelEdgeBisection (CtrlType *, GraphType *, float *, float)
void MCHMlevelEdgeBisection (CtrlType *, GraphType *, float *, float *)
void MocRefine2Way (CtrlType *, GraphType *, GraphType *, float *, float)
void MocAllocate2WayPartitionMemory (CtrlType *, GraphType *)
void MocCompute2WayPartitionParams (CtrlType *, GraphType *)
void MocProject2WayPartition (CtrlType *, GraphType *)
void MocRefine2Way2 (CtrlType *, GraphType *, GraphType *, float *, float *)
int AreAllVwgtsBelow (int, float, float *, float, float *, float)
int AreAnyVwgtsBelow (int, float, float *, float, float *, float)
int AreAllVwgtsAbove (int, float, float *, float, float *, float)
float ComputeLoadImbalance (int, int, float *, float *)
int AreAllBelow (int, float *, float *)
void iidxsort (int, idxtype *)
void iintsort (int, int *)
void ikeysort (int, KeyValueType *)
void ikeyvalsort (int, KeyValueType *)
void METIS_EdgeND (int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void GRACLUS_METIS_NodeND (int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void METIS_NodeWND (int *, idxtype *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *)
void MlevelNestedDissection (CtrlType *, GraphType *, idxtype *, float, int)
void MlevelNestedDissectionCC (CtrlType *, GraphType *, idxtype *, float, int)
void MlevelNodeBisectionMultiple (CtrlType *, GraphType *, int *, float)
void MlevelNodeBisection (CtrlType *, GraphType *, int *, float)
void SplitGraphOrder (CtrlType *, GraphType *, GraphType *, GraphType *)
void MMDOrder (CtrlType *, GraphType *, idxtype *, int)
int SplitGraphOrderCC (CtrlType *, GraphType *, GraphType *, int, idxtype *, idxtype *)
void METIS_PartGraphKway2 (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void METIS_WPartGraphKway2 (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
void METIS_NodeNDP (int, idxtype *, idxtype *, int, int *, idxtype *, idxtype *, idxtype *)
void MlevelNestedDissectionP (CtrlType *, GraphType *, idxtype *, int, int, int, idxtype *)
void METIS_NodeComputeSeparator (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, idxtype *)
void METIS_EdgeComputeSeparator (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, idxtype *)
void METIS_PartGraphRecursive (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, int *, int *, idxtype *)
void METIS_WPartGraphRecursive (int *, idxtype *, idxtype *, idxtype *, idxtype *, int *, int *, int *, float *, int *, int *, idxtype *)
int MlevelRecursiveBisection (CtrlType *, GraphType *, int, idxtype *, float *, float, int)
void MlevelEdgeBisection (CtrlType *, GraphType *, int *, float)
void SplitGraphPart (CtrlType *, GraphType *, GraphType *, GraphType *)
void SetUpSplitGraph (GraphType *, GraphType *, int, int)
void PQueueInit (CtrlType *ctrl, PQueueType *, int, int)
void PQueueReset (PQueueType *)
void PQueueFree (CtrlType *ctrl, PQueueType *)
int PQueueGetSize (PQueueType *)
int PQueueInsert (PQueueType *, int, int)
int PQueueDelete (PQueueType *, int, int)
int PQueueUpdate (PQueueType *, int, int, int)
void PQueueUpdateUp (PQueueType *, int, int, int)
int PQueueGetMax (PQueueType *)
int PQueueSeeMax (PQueueType *)
int PQueueGetKey (PQueueType *)
int CheckHeap (PQueueType *)
void Refine2Way (CtrlType *, GraphType *, GraphType *, int *, float ubfactor)
void Allocate2WayPartitionMemory (CtrlType *, GraphType *)
void Compute2WayPartitionParams (CtrlType *, GraphType *)
void Project2WayPartition (CtrlType *, GraphType *)
void ConstructSeparator (CtrlType *, GraphType *, float)
void ConstructMinCoverSeparator0 (CtrlType *, GraphType *, float)
void ConstructMinCoverSeparator (CtrlType *, GraphType *, float)
void FM_2WayNodeRefine (CtrlType *, GraphType *, float, int)
void FM_2WayNodeRefineEqWgt (CtrlType *, GraphType *, int)
void FM_2WayNodeRefine_OneSided (CtrlType *, GraphType *, float, int)
void FM_2WayNodeBalance (CtrlType *, GraphType *, float)
int ComputeMaxNodeGain (int, idxtype *, idxtype *, idxtype *)
void Refine2WayNode (CtrlType *, GraphType *, GraphType *, float)
void Allocate2WayNodePartitionMemory (CtrlType *, GraphType *)
void Compute2WayNodePartitionParams (CtrlType *, GraphType *)
void Project2WayNodePartition (CtrlType *, GraphType *)
void ComputePartitionInfo (GraphType *, int, idxtype *)
void ComputePartitionInfoBipartite (GraphType *, int, idxtype *)
void ComputePartitionBalance (GraphType *, int, idxtype *, float *)
float ComputeElementBalance (int, int, idxtype *)
void Random_KWayEdgeRefineMConn (CtrlType *, GraphType *, int, float *, float, int, int)
void Greedy_KWayEdgeBalanceMConn (CtrlType *, GraphType *, int, float *, float, int)
void PrintSubDomainGraph (GraphType *, int, idxtype *)
void ComputeSubDomainGraph (GraphType *, int, idxtype *, idxtype *)
void EliminateSubDomainEdges (CtrlType *, GraphType *, int, float *)
void MoveGroupMConn (CtrlType *, GraphType *, idxtype *, idxtype *, int, int, int, idxtype *)
void EliminateComponents (CtrlType *, GraphType *, int, float *, float)
void MoveGroup (CtrlType *, GraphType *, int, int, int, idxtype *, idxtype *)
void InitTimers (CtrlType *)
void PrintTimers (CtrlType *)
double seconds (void)
void print_help (char *program_name)
void clusterSize (GraphType *graph, int *clustersize)
void sparse2dense (GraphType *graph, double *dense, float *)
void extractfilename (char *path, char *name)
void graclus_errexit (char *,...)
Chains * chainmalloc (int n, char *msg)
float ** f2malloc (int n, int m, char *msg)
int ** i2malloc (int, int, char *)
int * imalloc (int, char *)
idxtype * idxmalloc (int, char *)
float * fmalloc (int, char *)
int * ismalloc (int, int, char *)
idxtype * idxsmalloc (int, idxtype, char *)
void * GKmalloc (int, char *)
void GKfree (void **,...)
int * iset (int n, int val, int *x)
idxtype * idxset (int n, idxtype val, idxtype *x)
float * sset (int n, float val, float *x)
int iamax (int, int *)
int idxamax (int, idxtype *)
int idxamax_strd (int, idxtype *, int)
int samax (int, float *)
int samax2 (int, float *)
int idxamin (int, idxtype *)
int samin (int, float *)
int idxsum (int, idxtype *)
int idxsum_strd (int, idxtype *, int)
void idxadd (int, idxtype *, idxtype *)
int charsum (int, char *)
int isum (int, int *)
float ssum (int, float *)
float ssum_strd (int n, float *x, int)
void sscale (int n, float, float *x)
float snorm2 (int, float *)
float sdot (int n, float *, float *)
void saxpy (int, float, float *, int, float *, int)
void RandomPermute (int, idxtype *, int)
void RandomInit (int n, int k, idxtype *label)
int ispow2 (int)
void InitRandom (int)
int log2_metis (int)
void ReadCoarsestInit (GraphType *graph, char *filename, int *wgtflag)
void WriteCoarsestGraph (GraphType *graph, char *filename, int *wgtflag)
void CreateGraph_Matlab (GraphType *graph, double *idata, double *jdata, double *edgeval, int vtx, int edges, int *wgtflag)
void ReadGraph (GraphType *, char *, int *)
void WritePartition (char *, idxtype *, int, int)
void WriteMeshPartition (char *, int, int, idxtype *, int, idxtype *)
void WritePermutation (char *, idxtype *, int)
int CheckGraph (GraphType *)
idxtype * ReadMesh (char *, int *, int *, int *)
void WriteGraph (char *, int, idxtype *, idxtype *)
void ComputeFillIn (GraphType *, idxtype *)
idxtype ComputeFillIn2 (GraphType *, idxtype *)
int smbfct (int, idxtype *, idxtype *, idxtype *, idxtype *, idxtype *, int *, idxtype *, idxtype *, int *)
void Test_PartGraph (int, idxtype *, idxtype *)
int VerifyPart (int, idxtype *, idxtype *, idxtype *, idxtype *, int, int, idxtype *)
int VerifyWPart (int, idxtype *, idxtype *, idxtype *, idxtype *, int, float *, int, idxtype *)
void Test_PartGraphV (int, idxtype *, idxtype *)
int VerifyPartV (int, idxtype *, idxtype *, idxtype *, idxtype *, int, int, idxtype *)
int VerifyWPartV (int, idxtype *, idxtype *, idxtype *, idxtype *, int, float *, int, idxtype *)
void Test_PartGraphmC (int, idxtype *, idxtype *)
int VerifyPartmC (int, int, idxtype *, idxtype *, idxtype *, idxtype *, int, float *, int, idxtype *)
void Test_ND (int, idxtype *, idxtype *)
int VerifyND (int, idxtype *, idxtype *)
Function Documentation
Allocate2WayNodePartitionMemory()
void Allocate2WayNodePartitionMemory (CtrlType * ctrl, GraphType * graph)
Definition at line 68 of file srefine.c.
References graphdef::bndind, graphdef::bndptr, idxmalloc, graphdef::nrinfo, graphdef::nvtxs, graphdef::pwgts, graphdef::rdata, and graphdef::where.
Referenced by Project2WayNodePartition().
Allocate2WayPartitionMemory()
void Allocate2WayPartitionMemory (CtrlType * ctrl, GraphType * graph)
Definition at line 58 of file refine.c.
References graphdef::bndind, graphdef::bndptr, graphdef::ed, graphdef::id, idxmalloc, graphdef::nvtxs, graphdef::pwgts, graphdef::rdata, and graphdef::where.
Referenced by Project2WayPartition().
AllocateKWayPartitionMemory()
void AllocateKWayPartitionMemory (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 115 of file kwayrefine.c.
References graphdef::bndind, graphdef::bndptr, idxmalloc, graphdef::nvtxs, graphdef::pwgts, graphdef::rdata, graphdef::rinfo, and graphdef::where.
Referenced by ProjectKWayPartition().
AllocateVolKWayPartitionMemory()
void AllocateVolKWayPartitionMemory (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 107 of file kwayvolrefine.c.
References graphdef::bndind, graphdef::bndptr, idxmalloc, graphdef::nvtxs, graphdef::pwgts, graphdef::rdata, graphdef::vrinfo, and graphdef::where.
Referenced by ProjectVolKWayPartition().
AllocateWorkSpace()
void AllocateWorkSpace (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 21 of file memory.c.
References workspacedef::auxcore, workspacedef::ccore, workspacedef::core, workspacedef::edegrees, GKmalloc, HTLENGTH, idxmalloc, workspacedef::maxcore, graphdef::ncon, graphdef::nedges, NEG_GAINSPAN, NULL, graphdef::nvtxs, OP_KMETIS, OP_KVMETIS, controldef::optype, PLUS_GAINSPAN, workspacedef::pmat, workspacedef::vedegrees, and controldef::wspace.
AreAllBelow()
int AreAllBelow (int ncon, float * v1, float * v2)
Definition at line 92 of file mutil.c.
AreAllHVwgtsAbove()
int AreAllHVwgtsAbove (int ncon, float alpha, float * vwgt1, float beta, float * vwgt2, float * limit)
Definition at line 529 of file mkwayfmh.c.
Referenced by MCGreedy_KWayEdgeBalanceHorizontal().
AreAllHVwgtsBelow()
int AreAllHVwgtsBelow (int ncon, float alpha, float * vwgt1, float beta, float * vwgt2, float * limit)
Definition at line 512 of file mkwayfmh.c.
Referenced by MCGreedy_KWayEdgeBalanceHorizontal(), and MCRandom_KWayEdgeRefineHorizontal().
AreAllVwgtsAbove()
int AreAllVwgtsAbove (int ncon, float alpha, float * vwgt1, float beta, float * vwgt2, float limit)
Definition at line 54 of file mutil.c.
AreAllVwgtsBelow()
int AreAllVwgtsBelow (int ncon, float alpha, float * vwgt1, float beta, float * vwgt2, float limit)
Definition at line 21 of file mutil.c.
AreAllVwgtsBelowFast()
int AreAllVwgtsBelowFast (int ncon, float * vwgt1, float * vwgt2, float limit)
Definition at line 496 of file mmatch.c.
Referenced by MCMatch_HEM(), MCMatch_RM(), MCMatch_SBHEM(), MCMatch_SHEBM(), and MCMatch_SHEM().
AreAnyVwgtsBelow()
int AreAnyVwgtsBelow (int ncon, float alpha, float * vwgt1, float beta, float * vwgt2, float limit)
Definition at line 37 of file mutil.c.
Balance2Way()
void Balance2Way (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 24 of file balance.c.
References abs(), Bnd2WayBalance(), General2WayBalance(), graphdef::nbnd, graphdef::nvtxs, and graphdef::pwgts.
BetterBalance()
int BetterBalance (int ncon, float * npwgts, float * tpwgts, float * diff)
Definition at line 303 of file mfm.c.
References fabs(), MAXNCON, and snorm2.
Referenced by MocFM_2WayEdgeRefine().
BetterVBalance()
float BetterVBalance (int ncon, int norm, float * vwgt, float * u1wgt, float * u2wgt)
Definition at line 435 of file mmatch.c.
References fabs(), and graclus_errexit().
Referenced by MCMatch_SBHEM(), and MCMatch_SHEBM().
Bnd2WayBalance()
void Bnd2WayBalance (CtrlType * ctrl, GraphType * graph, int * tpwgts)
Definition at line 51 of file balance.c.
References abs(), graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, graphdef::id, idxamax, idxset, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, graphdef::nvtxs, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueUpdate, graphdef::pwgts, RandomPermute, SWAP, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by Balance2Way().
BucketSortKeysInc()
void BucketSortKeysInc (int n, int max, idxtype * keys, idxtype * tperm, idxtype * perm)
Definition at line 25 of file bucketsort.c.
References idxsmalloc, MAKECSR, and max().
chainmalloc()
Chains* chainmalloc (int n, char * msg)
Definition at line 121 of file util.c.
References GKmalloc(), and NULL.
Change2CNumbering()
void Change2CNumbering (int nvtxs, idxtype * xadj, idxtype * adjncy)
Definition at line 21 of file fortran.c.
Change2FNumbering()
void Change2FNumbering (int nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vector)
Definition at line 36 of file fortran.c.
Change2FNumbering2()
void Change2FNumbering2 (int nvtxs, idxtype * xadj, idxtype * adjncy)
Definition at line 54 of file fortran.c.
Change2FNumberingOrder()
void Change2FNumberingOrder (int nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * v1, idxtype * v2)
Definition at line 71 of file fortran.c.
ChangeMesh2CNumbering()
void ChangeMesh2CNumbering (int n, idxtype * mesh)
Definition at line 94 of file fortran.c.
ChangeMesh2FNumbering()
void ChangeMesh2FNumbering (int n, idxtype * mesh, int nvtxs, idxtype * xadj, idxtype * adjncy)
Definition at line 107 of file fortran.c.
ChangeMesh2FNumbering2()
void ChangeMesh2FNumbering2 (int n, idxtype * mesh, int ne, int nn, idxtype * epart, idxtype * npart)
Definition at line 127 of file fortran.c.
charsum()
int charsum (int n, char * x)
Definition at line 463 of file util.c.
CheckBnd()
int CheckBnd (GraphType * graph)
Definition at line 145 of file debug.c.
References graphdef::adjncy, ASSERT, ASSERTP, graphdef::bndind, graphdef::bndptr, graphdef::nbnd, graphdef::nvtxs, graphdef::where, and graphdef::xadj.
CheckBnd2()
int CheckBnd2 (GraphType * graph)
Definition at line 181 of file debug.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, ASSERTP, graphdef::bndind, graphdef::bndptr, graphdef::nbnd, graphdef::nvtxs, graphdef::where, and graphdef::xadj.
CheckGraph()
int CheckGraph (GraphType *)
Referenced by MocInit2WayBalance(), and MocInit2WayBalance2().
CheckHeap()
int CheckHeap (PQueueType * queue)
Definition at line 551 of file pqueue.c.
References ASSERT, ASSERTP, PQueueType::heap, PQueueType::locator, PQueueType::maxnodes, and PQueueType::nnodes.
Referenced by PQueueDelete(), PQueueGetMax(), PQueueInsert(), PQueueUpdate(), and PQueueUpdateUp().
CheckNodeBnd()
int CheckNodeBnd (GraphType * graph, int onbnd)
Definition at line 216 of file debug.c.
References graphdef::adjncy, ASSERTP, graphdef::bndind, graphdef::bndptr, graphdef::nvtxs, graphdef::where, and graphdef::xadj.
CheckNodePartitionParams()
int CheckNodePartitionParams (GraphType * graph)
Definition at line 269 of file debug.c.
References graphdef::adjncy, graphdef::adjwgt, nrinfodef::edegrees, graphdef::nrinfo, graphdef::nvtxs, graphdef::pwgts, graphdef::vwgt, graphdef::where, and graphdef::xadj.
CheckRInfo()
int CheckRInfo (RInfoType * rinfo)
Definition at line 252 of file debug.c.
References ASSERTP, rinfodef::edegrees, rinfodef::ndegrees, and edegreedef::pid.
CheckVolKWayPartitionParams()
void CheckVolKWayPartitionParams (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 1219 of file kwayvolfm.c.
References graphdef::adjncy, graphdef::adjwgt, vrinfodef::ed, vrinfodef::edegrees, GKmalloc, vedegreedef::gv, vrinfodef::id, vrinfodef::ndegrees, graphdef::nvtxs, vedegreedef::pid, graphdef::vrinfo, graphdef::vsize, graphdef::where, and graphdef::xadj.
clusterSize()
void clusterSize (GraphType * graph, int * clustersize)
Definition at line 33 of file util.c.
References graphdef::nvtxs, and graphdef::where.
Referenced by ComputeRAsso(), remove_empty_clusters_l1(), and remove_empty_clusters_l2().
Coarsen2Way()
GraphType* Coarsen2Way (CtrlType * ctrl, GraphType * graph)
Definition at line 19 of file coarsen.c.
References graphdef::adjwgt, COARSEN_FRACTION2, controldef::CoarsenTmr, controldef::CoarsenTo, graphdef::coarser, controldef::CType, DBG_COARSEN, DBG_TIME, controldef::dbglvl, graphdef::finer, graclus_errexit(), idxsum, IFSET, MATCH_HEM, Match_HEM, MATCH_HEMN, Match_HEMN(), MATCH_RM, Match_RM, Match_RM_NVW, MATCH_SHEM, Match_SHEM, MATCH_SHEMKWAY, MATCH_SHEMN, Match_SHEMN(), controldef::maxvwgt, graphdef::nedges, graphdef::nvtxs, starttimer, stoptimer, and graphdef::vwgt.
CompressGraph()
void CompressGraph (CtrlType * ctrl, GraphType * graph, int nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * cptr, idxtype * cind)
Definition at line 21 of file compress.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::cmap, COMPRESSION_FRACTION, graphdef::gdata, GKfree, GKmalloc, idxmalloc, idxset, idxsmalloc, ikeysort, InitGraph, KeyValueType::key, graphdef::label, LTERM, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, KeyValueType::val, graphdef::vwgt, and graphdef::xadj.
Compute2WayHLoadImbalance()
float Compute2WayHLoadImbalance (int ncon, float * npwgts, float * tpwgts)
Definition at line 319 of file mfm.c.
References fabs(), and max().
Referenced by MocFM_2WayEdgeRefine().
Compute2WayHLoadImbalanceVec()
void Compute2WayHLoadImbalanceVec (int ncon, float * npwgts, float * tpwgts, float * lbvec)
Definition at line 337 of file mfm.c.
References fabs().
Compute2WayNodePartitionParams()
void Compute2WayNodePartitionParams (CtrlType * ctrl, GraphType * graph)
Definition at line 89 of file srefine.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckNodeBnd, nrinfodef::edegrees, idxset, graphdef::mincut, graphdef::nbnd, graphdef::nrinfo, graphdef::nvtxs, graphdef::pwgts, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by Project2WayNodePartition().
Compute2WayPartitionParams()
void Compute2WayPartitionParams (CtrlType * ctrl, GraphType * graph)
Definition at line 77 of file refine.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, graphdef::bndind, graphdef::bndptr, graphdef::ed, graphdef::id, idxset, idxsum, graphdef::mincut, graphdef::nbnd, graphdef::nvtxs, graphdef::pwgts, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by Refine2Way().
Compute_Weights()
void Compute_Weights (CtrlType * ctrl, GraphType * graph, idxtype * w)
Definition at line 19 of file wkkm.c.
References graphdef::adjwgt, cutType, NULL, graphdef::nvtxs, RASSO, RCUT, and graphdef::xadj.
Referenced by pingpong().
ComputeCoarseGraphSize()
int ComputeCoarseGraphSize (int nvtxs, idxtype * xadj, idxtype * adjncy, int cnvtxs, idxtype * cmap, idxtype * match, idxtype * perm)
Definition at line 111 of file estmem.c.
References GKfree, idxsmalloc, and LTERM.
Referenced by EstimateCFraction().
ComputeCut()
int ComputeCut (GraphType * graph, idxtype * where)
Definition at line 119 of file debug.c.
References graphdef::adjncy, graphdef::adjwgt, NULL, graphdef::nvtxs, and graphdef::xadj.
ComputeElementBalance()
float ComputeElementBalance (int ne, int nparts, idxtype * where)
Definition at line 270 of file stat.c.
References balance(), idxamax, idxsmalloc, and idxsum.
ComputeFillIn()
void ComputeFillIn (GraphType * , idxtype *)
ComputeFillIn2()
idxtype ComputeFillIn2 (GraphType * , idxtype *)
ComputeHKWayLoadImbalance()
void ComputeHKWayLoadImbalance (int ncon, int nparts, float * npwgts, float * lbvec)
Definition at line 545 of file mkwayfmh.c.
References max().
Referenced by MCGreedy_KWayEdgeBalanceHorizontal(), and MCRandom_KWayEdgeRefineHorizontal().
ComputeKWayBalanceBoundary()
void ComputeKWayBalanceBoundary (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 371 of file kwayrefine.c.
References graphdef::bndind, BNDInsert, graphdef::bndptr, rinfodef::ed, idxset, graphdef::nbnd, graphdef::nvtxs, and graphdef::rinfo.
Referenced by RefineKWay().
ComputeKWayBoundary()
void ComputeKWayBoundary (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 346 of file kwayrefine.c.
References graphdef::bndind, BNDInsert, graphdef::bndptr, rinfodef::ed, rinfodef::id, idxset, graphdef::nbnd, graphdef::nvtxs, and graphdef::rinfo.
Referenced by RefineKWay().
ComputeKWayPartitionParams()
void ComputeKWayPartitionParams (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 141 of file kwayrefine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, rinfodef::id, idxset, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, graphdef::pwgts, graphdef::rinfo, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by RefineKWay().
ComputeKWayVolGains()
void ComputeKWayVolGains (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 209 of file kwayvolrefine.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, graphdef::bndind, BNDInsert, graphdef::bndptr, vrinfodef::ed, vrinfodef::edegrees, vedegreedef::gv, vrinfodef::gv, vrinfodef::id, idxset, idxwspacefree, idxwspacemalloc, MAXIDX, graphdef::minvol, graphdef::nbnd, vrinfodef::ndegrees, graphdef::nvtxs, graphdef::vrinfo, graphdef::vsize, graphdef::where, and graphdef::xadj.
Referenced by ComputeVolKWayPartitionParams(), and ProjectVolKWayPartition().
ComputeKWayVolume()
void ComputeKWayVolume (GraphType * graph, int nupd, idxtype * updind, idxtype * marker, idxtype * phtable)
Definition at line 1089 of file kwayvolfm.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, vrinfodef::ed, vrinfodef::edegrees, vedegreedef::gv, vrinfodef::gv, vrinfodef::id, MAXIDX, vrinfodef::ndegrees, graphdef::nvtxs, graphdef::vrinfo, graphdef::vsize, graphdef::where, and graphdef::xadj.
Referenced by KWayVolUpdate().
ComputeLoadImbalance()
float ComputeLoadImbalance (int ncon, int nparts, float * npwgts, float * tpwgts)
Definition at line 70 of file mutil.c.
References max().
ComputeMaxNodeGain()
int ComputeMaxNodeGain (int nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt)
Definition at line 1051 of file sfm.c.
References max().
Referenced by FM_2WayNodeBalance(), FM_2WayNodeRefine(), FM_2WayNodeRefine2(), FM_2WayNodeRefine_OneSided(), and FM_2WayNodeRefineEqWgt().
ComputeNCut()
float ComputeNCut (GraphType * graph, idxtype * where, int npart)
Definition at line 67 of file debug.c.
References graphdef::adjncy, graphdef::adjwgt, idxsmalloc, NULL, graphdef::nvtxs, result, and graphdef::xadj.
Referenced by MLKKMRefine().
ComputePartitionBalance()
void ComputePartitionBalance (GraphType * graph, int nparts, idxtype * where, float * ubvec)
Definition at line 235 of file stat.c.
References balance(), idxamax, idxset, idxsmalloc, idxsum, graphdef::ncon, NULL, graphdef::nvtxs, and graphdef::vwgt.
ComputePartitionInfo()
void ComputePartitionInfo (GraphType * graph, int nparts, idxtype * where)
Definition at line 21 of file stat.c.
References graphdef::adjncy, graphdef::adjwgt, ComputeCut, ComputeVolume, GKfree, idxamax, idxamax_strd, idxamin, idxset, idxsmalloc, idxsum, idxsum_strd, IsConnectedSubdomain, LTERM, graphdef::ncon, NULL, graphdef::nvtxs, graphdef::vwgt, graphdef::where, and graphdef::xadj.
ComputePartitionInfoBipartite()
void ComputePartitionInfoBipartite (GraphType * graph, int nparts, idxtype * where)
Definition at line 130 of file stat.c.
References graphdef::adjncy, graphdef::adjwgt, ComputeCut, ComputeVolume, GKfree, idxamax, idxamax_strd, idxamin, idxset, idxsmalloc, idxsum, idxsum_strd, LTERM, graphdef::ncon, NULL, graphdef::nvtxs, graphdef::vsize, graphdef::vwgt, and graphdef::xadj.
ComputeRAsso()
float ComputeRAsso (GraphType * graph, idxtype * where, int npart)
Definition at line 20 of file debug.c.
References graphdef::adjncy, graphdef::adjwgt, clusterSize(), idxsmalloc, NULL, graphdef::nvtxs, result, and graphdef::xadj.
Referenced by MLKKMRefine().
ComputeSubDomainGraph()
void ComputeSubDomainGraph (GraphType * graph, int nparts, idxtype * pmat, idxtype * ndoms)
Definition at line 676 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, rinfodef::edegrees, idxset, rinfodef::ndegrees, graphdef::nvtxs, graphdef::rinfo, graphdef::where, and graphdef::xadj.
Referenced by EliminateSubDomainEdges(), Greedy_KWayEdgeBalanceMConn(), and Random_KWayEdgeRefineMConn().
ComputeVolKWayBalanceBoundary()
void ComputeVolKWayBalanceBoundary (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 439 of file kwayvolrefine.c.
References graphdef::bndind, BNDInsert, graphdef::bndptr, vrinfodef::ed, idxset, graphdef::nbnd, graphdef::nvtxs, and graphdef::vrinfo.
Referenced by RefineVolKWay().
ComputeVolKWayBoundary()
void ComputeVolKWayBoundary (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 414 of file kwayvolrefine.c.
References graphdef::bndind, BNDInsert, graphdef::bndptr, vrinfodef::ed, vrinfodef::gv, vrinfodef::id, idxset, graphdef::nbnd, graphdef::nvtxs, and graphdef::vrinfo.
Referenced by RefineVolKWay().
ComputeVolKWayPartitionParams()
void ComputeVolKWayPartitionParams (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 129 of file kwayvolrefine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, workspacedef::cdegree, ComputeKWayVolGains(), vedegreedef::ed, vrinfodef::ed, vrinfodef::edegrees, vedegreedef::gv, vrinfodef::id, idxset, graphdef::mincut, vrinfodef::ndegrees, vedegreedef::ned, vrinfodef::nid, NULL, graphdef::nvtxs, vedegreedef::pid, graphdef::pwgts, workspacedef::vedegrees, graphdef::vrinfo, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by RefineVolKWay().
ComputeVolSubDomainGraph()
void ComputeVolSubDomainGraph (GraphType * graph, int nparts, idxtype * pmat, idxtype * ndoms)
Definition at line 1345 of file kwayvolfm.c.
References graphdef::adjncy, graphdef::adjwgt, vrinfodef::edegrees, idxset, vrinfodef::ndegrees, graphdef::nvtxs, graphdef::vrinfo, graphdef::where, and graphdef::xadj.
Referenced by Greedy_KWayVolBalanceMConn(), and Random_KWayVolRefineMConn().
ComputeVolume()
int ComputeVolume (GraphType * graph, idxtype * where)
Definition at line 1180 of file kwayvolfm.c.
References graphdef::adjncy, idxamax, idxsmalloc, NULL, graphdef::nvtxs, graphdef::vsize, graphdef::vwgt, and graphdef::xadj.
ConstructMinCoverSeparator()
void ConstructMinCoverSeparator (CtrlType * ctrl, GraphType * graph, float ubfactor)
Definition at line 178 of file separator.c.
References graphdef::adjncy, Allocate2WayNodePartitionMemory, ASSERT, ASSERTP, graphdef::bndind, graphdef::bndptr, CheckNodePartitionParams, Compute2WayNodePartitionParams, DBG_SEPINFO, controldef::dbglvl, FM_2WayNodeRefine_OneSided, GKfree, idxcopy, idxmalloc, idxset, idxwspacefree, idxwspacemalloc, IFSET, IsSeparable, LTERM, MinCover, graphdef::mincut, graphdef::nbnd, graphdef::nvtxs, graphdef::pwgts, graphdef::rdata, graphdef::where, and graphdef::xadj.
ConstructMinCoverSeparator0()
void ConstructMinCoverSeparator0 (CtrlType * ctrl, GraphType * graph, float ubfactor)
Definition at line 63 of file separator.c.
References graphdef::adjncy, ASSERT, ASSERTP, graphdef::bndind, graphdef::bndptr, DBG_SEPINFO, controldef::dbglvl, GKfree, idxmalloc, idxset, idxwspacefree, idxwspacemalloc, IFSET, IsSeparable, LTERM, MinCover, graphdef::mincut, graphdef::nbnd, graphdef::nvtxs, graphdef::pwgts, graphdef::where, and graphdef::xadj.
ConstructSeparator()
void ConstructSeparator (CtrlType * ctrl, GraphType * graph, float ubfactor)
Definition at line 21 of file separator.c.
References Allocate2WayNodePartitionMemory, ASSERT, graphdef::bndind, CheckNodePartitionParams, Compute2WayNodePartitionParams, FM_2WayNodeRefine, GKfree, idxcopy, idxwspacefree, idxwspacemalloc, IsSeparable, LTERM, graphdef::nbnd, graphdef::nvtxs, graphdef::rdata, graphdef::where, and graphdef::xadj.
CreateCoarseGraph()
void CreateCoarseGraph (CtrlType * ctrl, GraphType * graph, int cnvtxs, idxtype * match, idxtype * perm)
Definition at line 22 of file ccgraph.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERTP, workspacedef::auxcore, graphdef::cmap, controldef::ContractTmr, CreateCoarseGraphNoMask(), DBG_TIME, controldef::dbglvl, HTLENGTH, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::nvwgt, OP_KVMETIS, controldef::optype, ReAdjustMemory(), saxpy, scopy, SetUpCoarseGraph(), starttimer, stoptimer, graphdef::vsize, graphdef::vwgt, controldef::wspace, and graphdef::xadj.
CreateCoarseGraph_NVW()
void CreateCoarseGraph_NVW (CtrlType * ctrl, GraphType * graph, int cnvtxs, idxtype * match, idxtype * perm)
Definition at line 330 of file ccgraph.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERTP, workspacedef::auxcore, graphdef::cmap, controldef::ContractTmr, DBG_TIME, controldef::dbglvl, HTLENGTH, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::nvwgt, ReAdjustMemory(), SetUpCoarseGraph(), starttimer, stoptimer, graphdef::vwgt, controldef::wspace, and graphdef::xadj.
CreateCoarseGraphNoMask()
void CreateCoarseGraphNoMask (CtrlType * ctrl, GraphType * graph, int cnvtxs, idxtype * match, idxtype * perm)
Definition at line 195 of file ccgraph.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, ASSERTP, workspacedef::auxcore, graphdef::cmap, controldef::ContractTmr, DBG_TIME, controldef::dbglvl, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::nvwgt, OP_KVMETIS, controldef::optype, ReAdjustMemory(), saxpy, scopy, SetUpCoarseGraph(), starttimer, stoptimer, graphdef::vsize, graphdef::vwgt, controldef::wspace, and graphdef::xadj.
Referenced by CreateCoarseGraph().
CreateGraph()
GraphType* CreateGraph (void)
Definition at line 154 of file memory.c.
References GKmalloc, and InitGraph().
CreateGraph_Matlab()
void CreateGraph_Matlab (GraphType * graph, double * idata, double * jdata, double * edgeval, int vtx, int edges, int * wgtflag)
EliminateComponents()
void EliminateComponents (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor)
Definition at line 1048 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, idxset, idxsum, idxwspacefree, idxwspacemalloc, INC_DEC, MoveGroup(), graphdef::nvtxs, graphdef::pwgts, graphdef::vwgt, graphdef::where, and graphdef::xadj.
EliminateSubDomainEdges()
void EliminateSubDomainEdges (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts)
Definition at line 721 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, ComputeSubDomainGraph(), GKfree, GKmalloc, idxamax, idxset, idxsum, idxwspacefree, idxwspacemalloc, ikeysort, INC_DEC, KeyValueType::key, LTERM, max(), min(), MoveGroupMConn(), graphdef::nvtxs, workspacedef::pmat, graphdef::pwgts, KeyValueType::val, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
EliminateVolComponents()
void EliminateVolComponents (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor)
Definition at line 1614 of file kwayvolfm.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, GKmalloc, idxset, idxsum, idxwspacefree, idxwspacemalloc, ikeysort, KeyValueType::key, graphdef::mincut, graphdef::minvol, graphdef::nvtxs, graphdef::pwgts, KeyValueType::val, graphdef::vsize, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by RefineVolKWay().
EliminateVolSubDomainEdges()
void EliminateVolSubDomainEdges (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts)
Definition at line 1387 of file kwayvolfm.c.
References graphdef::adjncy, graphdef::adjwgt, GKfree, GKmalloc, idxamax, idxset, idxsum, idxwspacefree, idxwspacemalloc, ikeysort, INC_DEC, KeyValueType::key, LTERM, max(), min(), graphdef::nvtxs, workspacedef::pmat, graphdef::pwgts, KeyValueType::val, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
EstimateCFraction()
void EstimateCFraction (int nvtxs, idxtype * xadj, idxtype * adjncy, float * vfraction, float * efraction)
Definition at line 66 of file estmem.c.
References ComputeCoarseGraphSize(), GKfree, idxmalloc, idxsmalloc, LTERM, RandomPermute, and UNMATCHED.
Referenced by METIS_EstimateMemory().
extractfilename()
void extractfilename (char * path, char * name)
Definition at line 73 of file util.c.
References length(), and name.
f2malloc()
float** f2malloc (int n, int m, char * msg)
Definition at line 132 of file util.c.
References GKmalloc(), and NULL.
FindComponents()
int FindComponents (CtrlType * ctrl, GraphType * graph, idxtype * cptr, idxtype * cind)
Definition at line 554 of file graph.c.
References graphdef::adjncy, graphdef::bndind, idxsmalloc, graphdef::nbnd, graphdef::nvtxs, graphdef::where, and graphdef::xadj.
FM_2WayEdgeRefine()
void FM_2WayEdgeRefine (CtrlType * ctrl, GraphType * graph, int * tpwgts, int npasses)
Definition at line 20 of file fm.c.
References abs(), graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, amax, amin, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, graphdef::id, idxamax, idxset, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, graphdef::nvtxs, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, graphdef::pwgts, RandomPermute, SWAP, graphdef::vwgt, graphdef::where, and graphdef::xadj.
FM_2WayNodeBalance()
void FM_2WayNodeBalance (CtrlType * ctrl, GraphType * graph, float ubfactor)
Definition at line 918 of file sfm.c.
References abs(), graphdef::adjncy, ASSERT, ASSERTP, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckNodeBnd, CheckNodePartitionParams, ComputeMaxNodeGain(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, nrinfodef::edegrees, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, graphdef::mincut, graphdef::nbnd, graphdef::nrinfo, graphdef::nvtxs, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueUpdateUp, graphdef::pwgts, RandomPermute, graphdef::vwgt, graphdef::where, and graphdef::xadj.
FM_2WayNodeRefine()
void FM_2WayNodeRefine (CtrlType * ctrl, GraphType * graph, float ubfactor, int npasses)
Definition at line 21 of file sfm.c.
References abs(), graphdef::adjncy, amin, ASSERT, ASSERTP, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckNodeBnd, CheckNodePartitionParams, ComputeMaxNodeGain(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, nrinfodef::edegrees, idxset, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, graphdef::nrinfo, graphdef::nvtxs, OFLAG_COMPRESS, controldef::oflags, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueSeeMax, PQueueUpdate, graphdef::pwgts, RandomPermute, graphdef::vwgt, graphdef::where, and graphdef::xadj.
FM_2WayNodeRefine_OneSided()
void FM_2WayNodeRefine_OneSided (CtrlType * ctrl, GraphType * graph, float ubfactor, int npasses)
Definition at line 717 of file sfm.c.
References abs(), graphdef::adjncy, amin, ASSERT, ASSERTP, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckNodeBnd, CheckNodePartitionParams, ComputeMaxNodeGain(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, nrinfodef::edegrees, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, graphdef::nrinfo, graphdef::nvtxs, OFLAG_COMPRESS, controldef::oflags, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdateUp, graphdef::pwgts, RandomPermute, graphdef::vwgt, graphdef::where, and graphdef::xadj.
FM_2WayNodeRefineEqWgt()
void FM_2WayNodeRefineEqWgt (CtrlType * ctrl, GraphType * graph, int npasses)
Definition at line 493 of file sfm.c.
References abs(), graphdef::adjncy, amin, ASSERT, ASSERTP, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckNodeBnd, CheckNodePartitionParams, ComputeMaxNodeGain(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, nrinfodef::edegrees, idxset, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, graphdef::nrinfo, graphdef::nvtxs, OFLAG_COMPRESS, controldef::oflags, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueSeeMax, PQueueUpdate, graphdef::pwgts, RandomPermute, graphdef::vwgt, graphdef::where, and graphdef::xadj.
fmalloc()
float* fmalloc (int n, char * msg)
Definition at line 188 of file util.c.
References GKmalloc(), and NULL.
FreeGraph()
void FreeGraph (GraphType * graph)
Definition at line 202 of file memory.c.
References graphdef::gdata, GKfree, LTERM, graphdef::npwgts, graphdef::nvwgt, and graphdef::rdata.
FreeWorkSpace()
void FreeWorkSpace (CtrlType * ctrl, GraphType * graph)
Definition at line 87 of file memory.c.
References workspacedef::core, workspacedef::edegrees, GKfree, LTERM, workspacedef::pmat, workspacedef::vedegrees, and controldef::wspace.
fwspacefree()
void fwspacefree (CtrlType * ctrl, int n)
Definition at line 140 of file memory.c.
References ASSERT, workspacedef::ccore, and controldef::wspace.
Referenced by MCGreedy_KWayEdgeBalanceHorizontal(), MCRandom_KWayEdgeRefineHorizontal(), MocFM_2WayEdgeRefine2(), and MocGeneral2WayBalance2().
fwspacemalloc()
float* fwspacemalloc (CtrlType * ctrl, int n)
Definition at line 128 of file memory.c.
References ASSERT, workspacedef::ccore, workspacedef::core, workspacedef::maxcore, and controldef::wspace.
GENDUALMETIS()
void GENDUALMETIS (int nelmnts, int nvtxs, int etype, idxtype * elmnts, idxtype * dxadj, idxtype * adjncy)
Definition at line 74 of file mesh.c.
References idxmalloc, idxsmalloc, and MAKECSR.
Referenced by METIS_MeshToDual().
General2WayBalance()
void General2WayBalance (CtrlType * ctrl, GraphType * graph, int * tpwgts)
Definition at line 177 of file balance.c.
References abs(), graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, graphdef::id, idxamax, idxset, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, graphdef::nvtxs, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueUpdate, graphdef::pwgts, RandomPermute, SWAP, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by Balance2Way().
genmmd()
void genmmd (int neqns, idxtype * xadj, idxtype * adjncy, idxtype * invp, idxtype * perm, int delta, idxtype * head, idxtype * qsize, idxtype * list, idxtype * marker, int maxint, int * ncsub)
Definition at line 53 of file mmd.c.
References mmdelm(), mmdint(), mmdnum(), and mmdupd().
GKfree()
void GKfree (void ** ptr1, ...)
Definition at line 243 of file util.c.
References LTERM, and NULL.
GKmalloc()
void* GKmalloc (int nbytes, char * msg)
Definition at line 225 of file util.c.
References graclus_errexit(), and NULL.
Referenced by chainmalloc(), f2malloc(), fmalloc(), i2malloc(), idxmalloc(), idxsmalloc(), imalloc(), and ismalloc().
graclus_errexit()
void graclus_errexit (char * f_str, ...)
Definition at line 98 of file util.c.
Referenced by BetterVBalance(), Coarsen2Way(), GKmalloc(), Init2WayPartition(), MCCoarsen2Way(), MocInit2WayPartition(), MocInit2WayPartition2(), MocRefine2Way(), MocRefine2Way2(), and Refine2Way().
GRACLUS_METIS_NodeND()
void GRACLUS_METIS_NodeND (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 79 of file ometis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumberingOrder, controldef::CoarsenTo, CompressGraph, COMPRESSION_FRACTION, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, GKfree, idxcopy, idxmalloc, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, LTERM, controldef::maxvwgt, MlevelNestedDissection(), MlevelNestedDissectionCC(), controldef::nseps, NULL, graphdef::nvtxs, OFLAG_CCMP, OFLAG_COMPRESS, controldef::oflags, ONMETIS_CTYPE, ONMETIS_DBGLVL, ONMETIS_ITYPE, ONMETIS_NSEPS, ONMETIS_OFLAGS, ONMETIS_PFACTOR, ONMETIS_RTYPE, OP_ONMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_NSEPS, OPTION_OFLAGS, OPTION_PFACTOR, OPTION_RTYPE, controldef::optype, ORDER_UNBALANCE_FRACTION, controldef::pfactor, PrintTimers, PruneGraph, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by METIS_NODEND(), metis_nodend(), metis_nodend_(), and metis_nodend__().
Greedy_KWayEdgeBalance()
void Greedy_KWayEdgeBalance (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses)
Definition at line 452 of file kwayfm.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, cloudViewer::utility::floor(), rinfodef::id, idxamax, idxamin, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, graphdef::pwgts, RandomPermute, graphdef::rinfo, SWAP, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
Greedy_KWayEdgeBalanceMConn()
void Greedy_KWayEdgeBalanceMConn (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses)
Definition at line 312 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, ComputeSubDomainGraph(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, rinfodef::id, idxamax, idxamin, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, workspacedef::pmat, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, graphdef::pwgts, RandomPermute, graphdef::rinfo, SWAP, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
Greedy_KWayEdgeRefine()
void Greedy_KWayEdgeRefine (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses)
Definition at line 222 of file kwayfm.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, cloudViewer::utility::floor(), rinfodef::id, idxamax, idxamin, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, graphdef::pwgts, RandomPermute, graphdef::rinfo, SWAP, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
Greedy_KWayVolBalance()
void Greedy_KWayVolBalance (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses)
Definition at line 402 of file kwayvolfm.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, graphdef::bndind, graphdef::bndptr, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, vedegreedef::ed, vrinfodef::ed, vrinfodef::edegrees, GKfree, vedegreedef::gv, vrinfodef::gv, vrinfodef::id, idxamax, idxamin, idxmalloc, idxset, idxsmalloc, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, KWayVolUpdate(), LTERM, graphdef::mincut, graphdef::minvol, graphdef::nbnd, vrinfodef::ndegrees, graphdef::nvtxs, vedegreedef::pid, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, graphdef::pwgts, RandomPermute, graphdef::vrinfo, graphdef::vsize, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Greedy_KWayVolBalanceMConn()
void Greedy_KWayVolBalanceMConn (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses)
Definition at line 556 of file kwayvolfm.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, graphdef::bndind, graphdef::bndptr, ComputeCut, ComputeVolSubDomainGraph(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, vedegreedef::ed, vrinfodef::ed, vrinfodef::edegrees, GKfree, vedegreedef::gv, vrinfodef::gv, vrinfodef::id, idxamax, idxamin, idxmalloc, idxset, idxsmalloc, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, KWayVolUpdate(), LTERM, graphdef::mincut, graphdef::minvol, graphdef::nbnd, vrinfodef::ndegrees, graphdef::nvtxs, vedegreedef::pid, workspacedef::pmat, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, graphdef::pwgts, RandomPermute, graphdef::vrinfo, graphdef::vsize, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
GrowBisection()
void GrowBisection (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 82 of file initpart.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, Allocate2WayPartitionMemory, ASSERTP, Balance2Way, controldef::CoarsenTo, Compute2WayPartitionParams, FM_2WayEdgeRefine, GKfree, idxcopy, idxmalloc, idxset, idxsum, INC_DEC, LARGENIPARTS, LTERM, graphdef::mincut, graphdef::nvtxs, RandomInRange, SMALLNIPARTS, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by Init2WayPartition().
GrowBisectionNode()
void GrowBisectionNode (CtrlType * ctrl, GraphType * graph, float ubfactor)
Definition at line 210 of file initpart.c.
References graphdef::adjncy, graphdef::adjwgt, Balance2Way, graphdef::bndind, graphdef::bndptr, controldef::CoarsenTo, Compute2WayNodePartitionParams, Compute2WayPartitionParams, graphdef::ed, FM_2WayEdgeRefine, FM_2WayNodeRefine, GKfree, graphdef::id, idxcopy, idxmalloc, idxset, idxsum, INC_DEC, LARGENIPARTS, LTERM, graphdef::mincut, graphdef::nbnd, graphdef::nrinfo, graphdef::nvtxs, graphdef::pwgts, RandomInRange, graphdef::rdata, SMALLNIPARTS, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by InitSeparator().
HEXNODALMETIS()
void HEXNODALMETIS (int nelmnts, int nvtxs, idxtype * elmnts, idxtype * dxadj, idxtype * adjncy)
Definition at line 267 of file mesh.c.
References ASSERT, idxmalloc, idxsmalloc, and MAKECSR.
Referenced by METIS_MeshToNodal().
i2malloc()
int** i2malloc (int n, int m, char * msg)
Definition at line 148 of file util.c.
References GKmalloc(), and NULL.
iamax()
int iamax (int n, int * x)
Definition at line 311 of file util.c.
References max().
idxadd()
void idxadd (int n, idxtype * x, idxtype * y)
Definition at line 453 of file util.c.
idxamax()
int idxamax (int n, idxtype * x)
Definition at line 325 of file util.c.
References max().
idxamax_strd()
int idxamax_strd (int n, idxtype * x, int incx)
Definition at line 338 of file util.c.
References max().
idxamin()
int idxamin (int n, idxtype * x)
Definition at line 396 of file util.c.
References min().
idxmalloc()
idxtype* idxmalloc (int n, char * msg)
Definition at line 176 of file util.c.
References GKmalloc(), and NULL.
Referenced by RandomInit().
idxset()
idxtype* idxset (int n, idxtype val, idxtype * x)
Definition at line 282 of file util.c.
Referenced by idxsmalloc().
idxsmalloc()
idxtype* idxsmalloc (int n, idxtype ival, char * msg)
Definition at line 213 of file util.c.
References GKmalloc(), idxset(), and NULL.
idxsum()
int idxsum (int n, idxtype * x)
Definition at line 424 of file util.c.
idxsum_strd()
int idxsum_strd (int n, idxtype * x, int incx)
Definition at line 438 of file util.c.
idxwspacefree()
void idxwspacefree (CtrlType * ctrl, int n)
Definition at line 116 of file memory.c.
References ASSERT, workspacedef::ccore, and controldef::wspace.
idxwspacemalloc()
idxtype* idxwspacemalloc (CtrlType * ctrl, int n)
Definition at line 104 of file memory.c.
References ASSERT, workspacedef::ccore, workspacedef::core, workspacedef::maxcore, and controldef::wspace.
iidxsort()
void iidxsort (int n, idxtype * base)
Definition at line 32 of file myqsort.c.
References max(), min(), siqst(), and THRESH.
iintsort()
void iintsort (int n, int * base)
Definition at line 161 of file myqsort.c.
References iiqst(), max(), min(), and THRESH.
ikeysort()
void ikeysort (int n, KeyValueType * base)
Definition at line 291 of file myqsort.c.
References KeyValueType::key, keyiqst(), max(), min(), and THRESH.
ikeyvalsort()
void ikeyvalsort (int n, KeyValueType * base)
Definition at line 427 of file myqsort.c.
References KeyValueType::key, keyvaliqst(), max(), min(), THRESH, and KeyValueType::val.
imalloc()
int* imalloc (int n, char * msg)
Definition at line 164 of file util.c.
References GKmalloc(), and NULL.
Init2WayPartition()
void Init2WayPartition (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 21 of file initpart.c.
References DBG_IPART, DBG_MOVEINFO, DBG_REFINE, DBG_TIME, controldef::dbglvl, graclus_errexit(), GrowBisection(), IFSET, controldef::InitPartTmr, IPART_GGPKL, controldef::IType, graphdef::mincut, RandomBisection(), starttimer, and stoptimer.
InitGraph()
void InitGraph (GraphType * graph)
Definition at line 170 of file memory.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::bndind, graphdef::bndptr, graphdef::cmap, graphdef::coarser, graphdef::ed, graphdef::finer, graphdef::gdata, graphdef::id, graphdef::label, graphdef::mincut, graphdef::minvol, graphdef::ncon, graphdef::nedges, graphdef::npwgts, graphdef::nrinfo, NULL, graphdef::nvtxs, graphdef::nvwgt, graphdef::pwgts, graphdef::rdata, graphdef::rinfo, graphdef::vrinfo, graphdef::vsize, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by CreateGraph().
InitRandom()
void InitRandom (int seed)
Definition at line 650 of file util.c.
InitSeparator()
void InitSeparator (CtrlType * ctrl, GraphType * graph, float ubfactor)
Definition at line 55 of file initpart.c.
References Compute2WayNodePartitionParams, DBG_IPART, DBG_MOVEINFO, DBG_REFINE, DBG_TIME, controldef::dbglvl, GrowBisectionNode(), IFSET, controldef::InitPartTmr, graphdef::mincut, starttimer, and stoptimer.
InitTimers()
void InitTimers (CtrlType * ctrl)
Definition at line 21 of file timing.c.
References controldef::AuxTmr1, controldef::AuxTmr2, controldef::AuxTmr3, controldef::AuxTmr4, controldef::AuxTmr5, controldef::AuxTmr6, cleartimer, controldef::CoarsenTmr, controldef::ContractTmr, controldef::InitPartTmr, controldef::MatchTmr, controldef::ProjectTmr, controldef::RefTmr, controldef::SepTmr, controldef::SplitTmr, controldef::TotalTmr, and controldef::UncoarsenTmr.
IsBalanced()
int IsBalanced (idxtype * pwgts, int nparts, float * tpwgts, float ubfactor)
Definition at line 329 of file kwayrefine.c.
References idxsum.
Referenced by RefineKWay().
IsBetter2wayBalance()
int IsBetter2wayBalance (int ncon, float * newbal, float * oldbal, float * ubvec)
Definition at line 326 of file mfm2.c.
Referenced by MocFM_2WayEdgeRefine2().
IsConnected()
int IsConnected (CtrlType * ctrl, GraphType * graph, int report)
Definition at line 454 of file graph.c.
References graphdef::adjncy, idxmalloc, idxsmalloc, graphdef::nvtxs, and graphdef::xadj.
IsConnected2()
int IsConnected2 (GraphType * graph, int report)
Definition at line 491 of file graph.c.
References graphdef::adjncy, GKfree, idxmalloc, idxsmalloc, LTERM, graphdef::nvtxs, graphdef::where, and graphdef::xadj.
IsConnectedSubdomain()
int IsConnectedSubdomain (CtrlType * ctrl, GraphType * graph, int pid, int report)
Definition at line 376 of file graph.c.
References graphdef::adjncy, GKfree, idxmalloc, idxsmalloc, LTERM, graphdef::nvtxs, graphdef::vwgt, graphdef::where, and graphdef::xadj.
iset()
int* iset (int n, int val, int * x)
Definition at line 268 of file util.c.
Referenced by ismalloc().
IsHBalanceBetterFT()
int IsHBalanceBetterFT (int ncon, int nparts, float * pfrom, float * pto, float * vwgt, float * ubvec)
Definition at line 593 of file mkwayfmh.c.
References amax.
Referenced by MCGreedy_KWayEdgeBalanceHorizontal(), and MCRandom_KWayEdgeRefineHorizontal().
IsHBalanceBetterTT()
int IsHBalanceBetterTT (int ncon, int nparts, float * pt1, float * pt2, float * vwgt, float * ubvec)
Definition at line 641 of file mkwayfmh.c.
Referenced by MCGreedy_KWayEdgeBalanceHorizontal(), and MCRandom_KWayEdgeRefineHorizontal().
ismalloc()
int* ismalloc (int n, int ival, char * msg)
Definition at line 200 of file util.c.
References GKmalloc(), iset(), and NULL.
ispow2()
int ispow2 (int a)
Definition at line 640 of file util.c.
IsSeparable()
int IsSeparable (GraphType * graph)
Definition at line 316 of file debug.c.
References graphdef::adjncy, ASSERTP, graphdef::nvtxs, graphdef::where, and graphdef::xadj.
isum()
int isum (int n, int * x)
Definition at line 476 of file util.c.
KWayVolUpdate()
void KWayVolUpdate (CtrlType * ctrl, GraphType * graph, int v, int from, int to, idxtype * marker, idxtype * phtable, idxtype * updind)
Definition at line 805 of file kwayvolfm.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, ComputeKWayVolume(), vedegreedef::ed, vrinfodef::ed, vrinfodef::edegrees, vedegreedef::gv, vrinfodef::gv, vrinfodef::id, INC_DEC, graphdef::nbnd, vrinfodef::ndegrees, vedegreedef::ned, vrinfodef::nid, NULL, vedegreedef::pid, SWAP, workspacedef::vedegrees, graphdef::vrinfo, graphdef::vsize, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by Greedy_KWayVolBalance(), Greedy_KWayVolBalanceMConn(), Random_KWayVolRefine(), and Random_KWayVolRefineMConn().
local_search()
int local_search (CtrlType * ctrl, GraphType * graph, int nparts, int chain_length, idxtype * w, float * tpwgts, float ubfactor)
Definition at line 409 of file wkkm.c.
Referenced by pingpong(), and remove_empty_clusters_l1().
log2_metis()
int log2_metis (int a)
Definition at line 663 of file util.c.
Match_HEM()
void Match_HEM (CtrlType * ctrl, GraphType * graph)
Definition at line 281 of file match.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, controldef::maxvwgt, graphdef::nvtxs, RandomPermute, starttimer, stoptimer, UNMATCHED, graphdef::vwgt, and graphdef::xadj.
Match_HEMN()
void Match_HEMN (CtrlType * ctrl, GraphType * graph)
Definition at line 116 of file match.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, controldef::maxvwgt, graphdef::nvtxs, RandomPermute, starttimer, stoptimer, UNMATCHED, graphdef::vwgt, and graphdef::xadj.
Referenced by Coarsen2Way().
Match_RM()
void Match_RM (CtrlType * ctrl, GraphType * graph)
Definition at line 175 of file match.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, controldef::maxvwgt, graphdef::nvtxs, RandomPermute, starttimer, stoptimer, UNMATCHED, graphdef::vwgt, and graphdef::xadj.
Match_RM_NVW()
void Match_RM_NVW (CtrlType * ctrl, GraphType * graph)
Definition at line 228 of file match.c.
References graphdef::adjncy, graphdef::cmap, CreateCoarseGraph_NVW, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, graphdef::nvtxs, RandomPermute, starttimer, stoptimer, UNMATCHED, and graphdef::xadj.
Match_SHEM()
void Match_SHEM (CtrlType * ctrl, GraphType * graph)
Definition at line 337 of file match.c.
References graphdef::adjncy, graphdef::adjwgt, BucketSortKeysInc, graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, controldef::maxvwgt, graphdef::nvtxs, RandomPermute, starttimer, stoptimer, UNMATCHED, graphdef::vwgt, and graphdef::xadj.
Match_SHEMN()
void Match_SHEMN (CtrlType * ctrl, GraphType * graph)
Definition at line 21 of file match.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, BucketSortKeysInc, graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, controldef::maxvwgt, graphdef::nvtxs, RandomPermute, starttimer, stoptimer, UNMATCHED, graphdef::vwgt, and graphdef::xadj.
Referenced by Coarsen2Way().
MCCoarsen2Way()
GraphType* MCCoarsen2Way (CtrlType * ctrl, GraphType * graph)
Definition at line 19 of file mcoarsen.c.
References graphdef::adjwgtsum, COARSEN_FRACTION2, controldef::CoarsenTmr, controldef::CoarsenTo, graphdef::coarser, controldef::CType, DBG_COARSEN, DBG_TIME, controldef::dbglvl, graphdef::finer, graclus_errexit(), idxsum, IFSET, MATCH_HEM, MATCH_RM, MATCH_SBHEM_INFNORM, MATCH_SBHEM_ONENORM, MATCH_SHEBM_INFNORM, MATCH_SHEBM_ONENORM, MATCH_SHEM, MATCH_SHEMKWAY, MCMatch_HEM, MCMatch_RM, MCMatch_SBHEM, MCMatch_SHEBM, MCMatch_SHEM, graphdef::ncon, graphdef::nedges, controldef::nmaxvwgt, graphdef::nvtxs, graphdef::nvwgt, ssum_strd, starttimer, and stoptimer.
MCGreedy_KWayEdgeBalanceHorizontal()
void MCGreedy_KWayEdgeBalanceHorizontal (CtrlType * ctrl, GraphType * graph, int nparts, float * ubvec, int npasses)
Definition at line 257 of file mkwayfmh.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, AreAllHVwgtsAbove(), AreAllHVwgtsBelow(), ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, ComputeHKWayLoadImbalance(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, fwspacefree(), fwspacemalloc, rinfodef::id, idxamax, idxset, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, IsHBalanceBetterFT(), IsHBalanceBetterTT(), MAXNCON, graphdef::mincut, MocIsHBalanced(), graphdef::nbnd, graphdef::ncon, rinfodef::ndegrees, graphdef::npwgts, NULL, graphdef::nvtxs, graphdef::nvwgt, edegreedef::pid, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, RandomPermute, graphdef::rinfo, samax, samin, saxpy, SWAP, graphdef::where, controldef::wspace, and graphdef::xadj.
MCHMlevelEdgeBisection()
void MCHMlevelEdgeBisection (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 383 of file mpmetis.c.
References MCCoarsen2Way, MocInit2WayPartition2, and MocRefine2Way2.
Referenced by MCHMlevelRecursiveBisection().
MCHMlevelRecursiveBisection()
int MCHMlevelRecursiveBisection (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * part, float * ubvec, int fpart)
Definition at line 290 of file mpmetis.c.
References amax, fmalloc, graphdef::gdata, GKfree, graphdef::label, LTERM, MCHMlevelEdgeBisection(), MCMlevelEdgeBisection(), graphdef::mincut, graphdef::ncon, graphdef::npwgts, NULL, graphdef::nvtxs, graphdef::nvwgt, graphdef::rdata, SplitGraphPart, and graphdef::where.
Referenced by METIS_mCHPartGraphRecursive().
MCMatch_HEM()
void MCMatch_HEM (CtrlType * ctrl, GraphType * graph)
Definition at line 79 of file mmatch.c.
References graphdef::adjncy, graphdef::adjwgt, AreAllVwgtsBelowFast(), graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, graphdef::ncon, controldef::nmaxvwgt, graphdef::nvtxs, graphdef::nvwgt, RandomPermute, starttimer, stoptimer, UNMATCHED, and graphdef::xadj.
MCMatch_RM()
void MCMatch_RM (CtrlType * ctrl, GraphType * graph)
Definition at line 22 of file mmatch.c.
References graphdef::adjncy, graphdef::adjwgt, AreAllVwgtsBelowFast(), graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, graphdef::ncon, controldef::nmaxvwgt, graphdef::nvtxs, graphdef::nvwgt, RandomPermute, starttimer, stoptimer, UNMATCHED, and graphdef::xadj.
MCMatch_SBHEM()
void MCMatch_SBHEM (CtrlType * ctrl, GraphType * graph, int norm)
Definition at line 333 of file mmatch.c.
References graphdef::adjncy, graphdef::adjwgt, AreAllVwgtsBelowFast(), BetterVBalance(), BucketSortKeysInc, graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, graphdef::ncon, controldef::nmaxvwgt, graphdef::nvtxs, graphdef::nvwgt, RandomPermute, starttimer, stoptimer, UNMATCHED, and graphdef::xadj.
MCMatch_SHEBM()
void MCMatch_SHEBM (CtrlType * ctrl, GraphType * graph, int norm)
Definition at line 232 of file mmatch.c.
References graphdef::adjncy, graphdef::adjwgt, AreAllVwgtsBelowFast(), BetterVBalance(), BucketSortKeysInc, graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, graphdef::ncon, controldef::nmaxvwgt, graphdef::nvtxs, graphdef::nvwgt, RandomPermute, starttimer, stoptimer, UNMATCHED, and graphdef::xadj.
MCMatch_SHEM()
void MCMatch_SHEM (CtrlType * ctrl, GraphType * graph)
Definition at line 138 of file mmatch.c.
References graphdef::adjncy, graphdef::adjwgt, AreAllVwgtsBelowFast(), BucketSortKeysInc, graphdef::cmap, CreateCoarseGraph, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, controldef::MatchTmr, graphdef::ncon, controldef::nmaxvwgt, graphdef::nvtxs, graphdef::nvwgt, RandomPermute, starttimer, stoptimer, UNMATCHED, and graphdef::xadj.
MCMlevelEdgeBisection()
void MCMlevelEdgeBisection (CtrlType * ctrl, GraphType * graph, float * tpwgts, float ubfactor)
Definition at line 366 of file mpmetis.c.
References MCCoarsen2Way, MocInit2WayPartition, and MocRefine2Way.
Referenced by MCHMlevelRecursiveBisection(), and MCMlevelRecursiveBisection().
MCMlevelKWayPartitioning()
int MCMlevelKWayPartitioning (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * part, float * rubvec)
Definition at line 76 of file mkmetis.c.
References DBG_TIME, controldef::dbglvl, IFSET, controldef::InitPartTmr, IPART_RANDOM, MATCH_SBHEM_INFNORM, MCCoarsen2Way, MocAllocateKWayPartitionMemory, graphdef::ncon, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, RTYPE_FM, and starttimer.
Referenced by METIS_mCPartGraphKway().
MCMlevelRecursiveBisection()
int MCMlevelRecursiveBisection (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * part, float ubfactor, int fpart)
Definition at line 238 of file mpmetis.c.
References graphdef::gdata, GKfree, graphdef::label, LTERM, MCMlevelEdgeBisection(), graphdef::mincut, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, graphdef::rdata, SplitGraphPart, and graphdef::where.
Referenced by METIS_mCPartGraphRecursive().
MCRandom_KWayEdgeRefineHorizontal()
void MCRandom_KWayEdgeRefineHorizontal (CtrlType * ctrl, GraphType * graph, int nparts, float * orgubvec, int npasses)
Definition at line 20 of file mkwayfmh.c.
References graphdef::adjncy, graphdef::adjwgt, amax, AreAllHVwgtsBelow(), ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, ComputeHKWayLoadImbalance(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, fabs(), fwspacefree(), fwspacemalloc, rinfodef::id, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, IsHBalanceBetterFT(), IsHBalanceBetterTT(), MAXNCON, graphdef::mincut, graphdef::nbnd, graphdef::ncon, rinfodef::ndegrees, graphdef::npwgts, NULL, graphdef::nvtxs, graphdef::nvwgt, edegreedef::pid, RandomPermute, graphdef::rinfo, samax, samin, saxpy, SWAP, graphdef::where, controldef::wspace, and graphdef::xadj.
METIS_EdgeComputeSeparator()
void METIS_EdgeComputeSeparator (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * options, int * sepsize, idxtype * part)
Definition at line 320 of file parmetis.c.
References AllocateWorkSpace, amin, controldef::CoarsenTo, ConstructMinCoverSeparator, controldef::CType, controldef::dbglvl, FreeWorkSpace, graphdef::gdata, GKfree, idxcopy, idxsum, InitRandom, controldef::IType, graphdef::label, LTERM, controldef::maxvwgt, MlevelEdgeBisection, controldef::nseps, controldef::oflags, ONMETIS_CTYPE, ONMETIS_DBGLVL, ONMETIS_ITYPE, ONMETIS_RTYPE, OP_OEMETIS, OP_ONMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, controldef::pfactor, graphdef::pwgts, graphdef::rdata, controldef::RType, SetUpGraph, graphdef::vwgt, and graphdef::where.
METIS_EDGEND()
void METIS_EDGEND (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 93 of file frename.c.
References METIS_EdgeND().
metis_edgend()
void metis_edgend (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 97 of file frename.c.
References METIS_EdgeND().
METIS_EdgeND()
void METIS_EdgeND (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 22 of file ometis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumberingOrder, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, controldef::maxvwgt, MlevelNestedDissection(), controldef::nseps, NULL, OEMETIS_CTYPE, OEMETIS_DBGLVL, OEMETIS_ITYPE, OEMETIS_RTYPE, controldef::oflags, OP_OEMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, ORDER_UNBALANCE_FRACTION, controldef::pfactor, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by METIS_EDGEND(), metis_edgend(), metis_edgend_(), and metis_edgend__().
metis_edgend_()
void metis_edgend_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 101 of file frename.c.
References METIS_EdgeND().
metis_edgend__()
void metis_edgend__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 105 of file frename.c.
References METIS_EdgeND().
METIS_EstimateMemory()
void METIS_EstimateMemory (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * optype, int * nbytes)
Definition at line 22 of file estmem.c.
References Change2CNumbering, Change2FNumbering2, EstimateCFraction(), InitRandom, NEG_GAINSPAN, and PLUS_GAINSPAN.
Referenced by METIS_ESTIMATEMEMORY(), metis_estimatememory(), metis_estimatememory_(), and metis_estimatememory__().
METIS_ESTIMATEMEMORY()
void METIS_ESTIMATEMEMORY (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * optype, int * nbytes)
Definition at line 222 of file frename.c.
References METIS_EstimateMemory().
metis_estimatememory()
void metis_estimatememory (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * optype, int * nbytes)
Definition at line 226 of file frename.c.
References METIS_EstimateMemory().
metis_estimatememory_()
void metis_estimatememory_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * optype, int * nbytes)
Definition at line 230 of file frename.c.
References METIS_EstimateMemory().
metis_estimatememory__()
void metis_estimatememory__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * optype, int * nbytes)
Definition at line 234 of file frename.c.
References METIS_EstimateMemory().
METIS_mCHPartGraphRecursive()
void METIS_mCHPartGraphRecursive (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * ubvec, int * options, int * edgecut, idxtype * part)
Definition at line 78 of file mpmetis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, fmalloc, FreeWorkSpace, GKfree, IFSET, InitRandom, InitTimers, controldef::IType, LTERM, MCHMlevelRecursiveBisection(), controldef::nmaxvwgt, OP_PMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PMETIS_CTYPE, PMETIS_DBGLVL, PMETIS_ITYPE, PMETIS_RTYPE, PrintTimers, controldef::RType, scopy, SetUpGraph, starttimer, stoptimer, and controldef::TotalTmr.
METIS_MCPARTGRAPHKWAY()
void METIS_MCPARTGRAPHKWAY (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * rubvec, int * options, int * edgecut, idxtype * part)
Definition at line 259 of file frename.c.
References METIS_mCPartGraphKway().
metis_mcpartgraphkway()
void metis_mcpartgraphkway (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * rubvec, int * options, int * edgecut, idxtype * part)
Definition at line 263 of file frename.c.
References METIS_mCPartGraphKway().
METIS_mCPartGraphKway()
void METIS_mCPartGraphKway (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * rubvec, int * options, int * edgecut, idxtype * part)
Definition at line 23 of file mkmetis.c.
References AllocateWorkSpace, amax, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, IFSET, InitRandom, InitTimers, controldef::IType, log2_metis, McKMETIS_CTYPE, McKMETIS_DBGLVL, McKMETIS_ITYPE, McKMETIS_RTYPE, MCMlevelKWayPartitioning(), controldef::nmaxvwgt, OP_KMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, and controldef::TotalTmr.
Referenced by METIS_MCPARTGRAPHKWAY(), metis_mcpartgraphkway(), metis_mcpartgraphkway_(), and metis_mcpartgraphkway__().
metis_mcpartgraphkway_()
void metis_mcpartgraphkway_ (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * rubvec, int * options, int * edgecut, idxtype * part)
Definition at line 267 of file frename.c.
References METIS_mCPartGraphKway().
metis_mcpartgraphkway__()
void metis_mcpartgraphkway__ (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * rubvec, int * options, int * edgecut, idxtype * part)
Definition at line 271 of file frename.c.
References METIS_mCPartGraphKway().
METIS_MCPARTGRAPHRECURSIVE()
void METIS_MCPARTGRAPHRECURSIVE (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 241 of file frename.c.
References METIS_mCPartGraphRecursive().
metis_mcpartgraphrecursive()
void metis_mcpartgraphrecursive (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 245 of file frename.c.
References METIS_mCPartGraphRecursive().
METIS_mCPartGraphRecursive()
void METIS_mCPartGraphRecursive (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 24 of file mpmetis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, IFSET, InitRandom, InitTimers, controldef::IType, MCMlevelRecursiveBisection(), McPMETIS_CTYPE, McPMETIS_DBGLVL, McPMETIS_ITYPE, McPMETIS_RTYPE, controldef::nmaxvwgt, OP_PMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, and controldef::TotalTmr.
Referenced by METIS_MCPARTGRAPHRECURSIVE(), metis_mcpartgraphrecursive(), metis_mcpartgraphrecursive_(), and metis_mcpartgraphrecursive__().
metis_mcpartgraphrecursive_()
void metis_mcpartgraphrecursive_ (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 249 of file frename.c.
References METIS_mCPartGraphRecursive().
metis_mcpartgraphrecursive__()
void metis_mcpartgraphrecursive__ (int * nvtxs, int * ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 253 of file frename.c.
References METIS_mCPartGraphRecursive().
METIS_MESHTODUAL()
void METIS_MESHTODUAL (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 204 of file frename.c.
References METIS_MeshToDual().
metis_meshtodual()
void metis_meshtodual (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 208 of file frename.c.
References METIS_MeshToDual().
METIS_MeshToDual()
void METIS_MeshToDual (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 23 of file mesh.c.
References ChangeMesh2CNumbering, ChangeMesh2FNumbering, and GENDUALMETIS().
Referenced by METIS_MESHTODUAL(), metis_meshtodual(), metis_meshtodual_(), metis_meshtodual__(), and METIS_PartMeshDual().
metis_meshtodual_()
void metis_meshtodual_ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 212 of file frename.c.
References METIS_MeshToDual().
metis_meshtodual__()
void metis_meshtodual__ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 216 of file frename.c.
References METIS_MeshToDual().
METIS_MESHTONODAL()
void METIS_MESHTONODAL (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 186 of file frename.c.
References METIS_MeshToNodal().
metis_meshtonodal()
void metis_meshtonodal (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 190 of file frename.c.
References METIS_MeshToNodal().
METIS_MeshToNodal()
void METIS_MeshToNodal (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 42 of file mesh.c.
References ChangeMesh2CNumbering, ChangeMesh2FNumbering, HEXNODALMETIS(), QUADNODALMETIS(), TETNODALMETIS(), and TRINODALMETIS().
Referenced by METIS_MESHTONODAL(), metis_meshtonodal(), metis_meshtonodal_(), metis_meshtonodal__(), and METIS_PartMeshNodal().
metis_meshtonodal_()
void metis_meshtonodal_ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 194 of file frename.c.
References METIS_MeshToNodal().
metis_meshtonodal__()
void metis_meshtonodal__ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, idxtype * dxadj, idxtype * dadjncy)
Definition at line 198 of file frename.c.
References METIS_MeshToNodal().
METIS_NodeComputeSeparator()
void METIS_NodeComputeSeparator (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * options, int * sepsize, idxtype * part)
Definition at line 262 of file parmetis.c.
References AllocateWorkSpace, amin, controldef::CoarsenTo, controldef::CType, controldef::dbglvl, FreeWorkSpace, graphdef::gdata, GKfree, idxcopy, idxsum, InitRandom, controldef::IType, graphdef::label, LTERM, controldef::maxvwgt, MlevelNodeBisectionMultiple, controldef::nseps, controldef::oflags, ONMETIS_CTYPE, ONMETIS_DBGLVL, ONMETIS_ITYPE, ONMETIS_RTYPE, OP_ONMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, controldef::pfactor, graphdef::pwgts, graphdef::rdata, controldef::RType, SetUpGraph, graphdef::vwgt, and graphdef::where.
METIS_NODEND()
void METIS_NODEND (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 112 of file frename.c.
References GRACLUS_METIS_NodeND().
metis_nodend()
void metis_nodend (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 116 of file frename.c.
References GRACLUS_METIS_NodeND().
metis_nodend_()
void metis_nodend_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 120 of file frename.c.
References GRACLUS_METIS_NodeND().
metis_nodend__()
void metis_nodend__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 124 of file frename.c.
References GRACLUS_METIS_NodeND().
METIS_NodeNDP()
void METIS_NodeNDP (int nvtxs, idxtype * xadj, idxtype * adjncy, int npes, int * options, idxtype * perm, idxtype * iperm, idxtype * sizes)
Definition at line 95 of file parmetis.c.
References AllocateWorkSpace, controldef::CoarsenTo, CompressGraph, COMPRESSION_FRACTION, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, GKfree, idxmalloc, idxset, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, LTERM, controldef::maxvwgt, MlevelNestedDissectionP(), controldef::nseps, NULL, graphdef::nvtxs, OFLAG_COMPRESS, controldef::oflags, ONMETIS_CTYPE, ONMETIS_DBGLVL, ONMETIS_ITYPE, ONMETIS_NSEPS, ONMETIS_OFLAGS, ONMETIS_PFACTOR, ONMETIS_RTYPE, OP_ONMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_NSEPS, OPTION_OFLAGS, OPTION_PFACTOR, OPTION_RTYPE, controldef::optype, controldef::pfactor, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
METIS_NODEWND()
void METIS_NODEWND (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 131 of file frename.c.
References METIS_NodeWND().
metis_nodewnd()
void metis_nodewnd (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 135 of file frename.c.
References METIS_NodeWND().
METIS_NodeWND()
void METIS_NodeWND (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 204 of file ometis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumberingOrder, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, controldef::maxvwgt, MlevelNestedDissection(), controldef::nseps, NULL, OFLAG_COMPRESS, controldef::oflags, ONMETIS_CTYPE, ONMETIS_DBGLVL, ONMETIS_ITYPE, ONMETIS_RTYPE, OP_ONMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, ORDER_UNBALANCE_FRACTION, controldef::pfactor, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by METIS_NODEWND(), metis_nodewnd(), metis_nodewnd_(), and metis_nodewnd__().
metis_nodewnd_()
void metis_nodewnd_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 139 of file frename.c.
References METIS_NodeWND().
metis_nodewnd__()
void metis_nodewnd__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, int * numflag, int * options, idxtype * perm, idxtype * iperm)
Definition at line 143 of file frename.c.
References METIS_NodeWND().
METIS_PARTGRAPHKWAY()
void METIS_PARTGRAPHKWAY (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 55 of file frename.c.
References METIS_PartGraphKway().
metis_partgraphkway()
void metis_partgraphkway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 59 of file frename.c.
References METIS_PartGraphKway().
METIS_PartGraphKway()
void METIS_PartGraphKway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 22 of file kmetis.c.
References fmalloc, and METIS_WPartGraphKway().
Referenced by METIS_PARTGRAPHKWAY(), metis_partgraphkway(), metis_partgraphkway_(), metis_partgraphkway__(), METIS_PartMeshDual(), and METIS_PartMeshNodal().
METIS_PartGraphKway2()
void METIS_PartGraphKway2 (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 22 of file parmetis.c.
References fmalloc, and METIS_WPartGraphKway2().
metis_partgraphkway_()
void metis_partgraphkway_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 63 of file frename.c.
References METIS_PartGraphKway().
metis_partgraphkway__()
void metis_partgraphkway__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 67 of file frename.c.
References METIS_PartGraphKway().
METIS_PARTGRAPHRECURSIVE()
void METIS_PARTGRAPHRECURSIVE (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 18 of file frename.c.
References METIS_PartGraphRecursive().
metis_partgraphrecursive()
void metis_partgraphrecursive (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 22 of file frename.c.
References METIS_PartGraphRecursive().
METIS_PartGraphRecursive()
void METIS_PartGraphRecursive (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 22 of file pmetis.c.
References fmalloc, and METIS_WPartGraphRecursive().
Referenced by METIS_PARTGRAPHRECURSIVE(), metis_partgraphrecursive(), metis_partgraphrecursive_(), and metis_partgraphrecursive__().
metis_partgraphrecursive_()
void metis_partgraphrecursive_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 26 of file frename.c.
References METIS_PartGraphRecursive().
metis_partgraphrecursive__()
void metis_partgraphrecursive__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * options, int * edgecut, idxtype * part)
Definition at line 30 of file frename.c.
References METIS_PartGraphRecursive().
METIS_PARTGRAPHVKWAY()
void METIS_PARTGRAPHVKWAY (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, int * options, int * volume, idxtype * part)
Definition at line 277 of file frename.c.
References METIS_PartGraphVKway().
metis_partgraphvkway()
void metis_partgraphvkway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, int * options, int * volume, idxtype * part)
Definition at line 281 of file frename.c.
References METIS_PartGraphVKway().
METIS_PartGraphVKway()
void METIS_PartGraphVKway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, int * options, int * volume, idxtype * part)
Definition at line 22 of file kvmetis.c.
References fmalloc, and METIS_WPartGraphVKway().
Referenced by METIS_PARTGRAPHVKWAY(), metis_partgraphvkway(), metis_partgraphvkway_(), and metis_partgraphvkway__().
metis_partgraphvkway_()
void metis_partgraphvkway_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, int * options, int * volume, idxtype * part)
Definition at line 285 of file frename.c.
References METIS_PartGraphVKway().
metis_partgraphvkway__()
void metis_partgraphvkway__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, int * options, int * volume, idxtype * part)
Definition at line 289 of file frename.c.
References METIS_PartGraphVKway().
METIS_PARTMESHDUAL()
void METIS_PARTMESHDUAL (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 168 of file frename.c.
References METIS_PartMeshDual().
metis_partmeshdual()
void metis_partmeshdual (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 172 of file frename.c.
References METIS_PartMeshDual().
METIS_PartMeshDual()
void METIS_PartMeshDual (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 110 of file meshpart.c.
References ChangeMesh2CNumbering, ChangeMesh2FNumbering2, GKfree, iamax, idxmalloc, idxset, idxsmalloc, LTERM, MAKECSR, METIS_MeshToDual(), METIS_PartGraphKway(), and NULL.
Referenced by METIS_PARTMESHDUAL(), metis_partmeshdual(), metis_partmeshdual_(), and metis_partmeshdual__().
metis_partmeshdual_()
void metis_partmeshdual_ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 176 of file frename.c.
References METIS_PartMeshDual().
metis_partmeshdual__()
void metis_partmeshdual__ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 180 of file frename.c.
References METIS_PartMeshDual().
METIS_PARTMESHNODAL()
void METIS_PARTMESHNODAL (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 150 of file frename.c.
References METIS_PartMeshNodal().
metis_partmeshnodal()
void metis_partmeshnodal (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 154 of file frename.c.
References METIS_PartMeshNodal().
METIS_PartMeshNodal()
void METIS_PartMeshNodal (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 22 of file meshpart.c.
References ChangeMesh2CNumbering, ChangeMesh2FNumbering2, GKfree, iamax, idxmalloc, idxset, idxsmalloc, LTERM, METIS_MeshToNodal(), METIS_PartGraphKway(), and NULL.
Referenced by METIS_PARTMESHNODAL(), metis_partmeshnodal(), metis_partmeshnodal_(), and metis_partmeshnodal__().
metis_partmeshnodal_()
void metis_partmeshnodal_ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 158 of file frename.c.
References METIS_PartMeshNodal().
metis_partmeshnodal__()
void metis_partmeshnodal__ (int * ne, int * nn, idxtype * elmnts, int * etype, int * numflag, int * nparts, int * edgecut, idxtype * epart, idxtype * npart)
Definition at line 162 of file frename.c.
References METIS_PartMeshNodal().
METIS_WPARTGRAPHKWAY()
void METIS_WPARTGRAPHKWAY (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 74 of file frename.c.
References METIS_WPartGraphKway().
metis_wpartgraphkway()
void metis_wpartgraphkway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 78 of file frename.c.
References METIS_WPartGraphKway().
METIS_WPartGraphKway()
void METIS_WPartGraphKway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 43 of file kmetis.c.
References AllocateWorkSpace, amax, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, KMETIS_CTYPE, KMETIS_DBGLVL, KMETIS_ITYPE, KMETIS_RTYPE, controldef::maxvwgt, MlevelKWayPartitioning(), OP_KMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by METIS_PartGraphKway(), METIS_WPARTGRAPHKWAY(), metis_wpartgraphkway(), metis_wpartgraphkway_(), and metis_wpartgraphkway__().
METIS_WPartGraphKway2()
void METIS_WPartGraphKway2 (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 44 of file parmetis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, KMETIS_CTYPE, KMETIS_DBGLVL, KMETIS_ITYPE, KMETIS_RTYPE, controldef::maxvwgt, MlevelKWayPartitioning, OP_KMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by METIS_PartGraphKway2().
metis_wpartgraphkway_()
void metis_wpartgraphkway_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 82 of file frename.c.
References METIS_WPartGraphKway().
metis_wpartgraphkway__()
void metis_wpartgraphkway__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 86 of file frename.c.
References METIS_WPartGraphKway().
METIS_WPARTGRAPHRECURSIVE()
void METIS_WPARTGRAPHRECURSIVE (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 36 of file frename.c.
References METIS_WPartGraphRecursive().
metis_wpartgraphrecursive()
void metis_wpartgraphrecursive (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 40 of file frename.c.
References METIS_WPartGraphRecursive().
METIS_WPartGraphRecursive()
void METIS_WPartGraphRecursive (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 45 of file pmetis.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, fmalloc, FreeWorkSpace, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, controldef::maxvwgt, MlevelRecursiveBisection(), OP_PMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PMETIS_CTYPE, PMETIS_DBGLVL, PMETIS_ITYPE, PMETIS_RTYPE, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by METIS_PartGraphRecursive(), METIS_WPARTGRAPHRECURSIVE(), metis_wpartgraphrecursive(), metis_wpartgraphrecursive_(), metis_wpartgraphrecursive__(), MlevelKWayPartitioning(), MlevelVolKWayPartitioning(), and MLKKMPartitioning().
metis_wpartgraphrecursive_()
void metis_wpartgraphrecursive_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 44 of file frename.c.
References METIS_WPartGraphRecursive().
metis_wpartgraphrecursive__()
void metis_wpartgraphrecursive__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * edgecut, idxtype * part)
Definition at line 48 of file frename.c.
References METIS_WPartGraphRecursive().
METIS_WPARTGRAPHVKWAY()
void METIS_WPARTGRAPHVKWAY (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * volume, idxtype * part)
Definition at line 294 of file frename.c.
References METIS_WPartGraphVKway().
metis_wpartgraphvkway()
void metis_wpartgraphvkway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * volume, idxtype * part)
Definition at line 298 of file frename.c.
References METIS_WPartGraphVKway().
METIS_WPartGraphVKway()
void METIS_WPartGraphVKway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * volume, idxtype * part)
Definition at line 43 of file kvmetis.c.
References AllocateWorkSpace, amax, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, FreeWorkSpace, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, KVMETIS_CTYPE, KVMETIS_DBGLVL, KVMETIS_ITYPE, KVMETIS_RTYPE, log2_metis, controldef::maxvwgt, MlevelVolKWayPartitioning(), OP_KVMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PrintTimers, controldef::RType, starttimer, stoptimer, controldef::TotalTmr, VolSetUpGraph, and graphdef::vwgt.
Referenced by METIS_PartGraphVKway(), METIS_WPARTGRAPHVKWAY(), metis_wpartgraphvkway(), metis_wpartgraphvkway_(), and metis_wpartgraphvkway__().
metis_wpartgraphvkway_()
void metis_wpartgraphvkway_ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * volume, idxtype * part)
Definition at line 302 of file frename.c.
References METIS_WPartGraphVKway().
metis_wpartgraphvkway__()
void metis_wpartgraphvkway__ (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int * wgtflag, int * numflag, int * nparts, float * tpwgts, int * options, int * volume, idxtype * part)
Definition at line 306 of file frename.c.
References METIS_WPartGraphVKway().
MinCover()
void MinCover (idxtype * xadj, idxtype * adjncy, int asize, int bsize, idxtype * cover, int * csize)
Definition at line 42 of file mincover.c.
References GKfree, idxmalloc, idxsmalloc, LTERM, MinCover_Augment(), and MinCover_Decompose().
MinCover_Augment()
int MinCover_Augment (idxtype * xadj, idxtype * adjncy, int col, idxtype * mate, idxtype * flag, idxtype * level, int maxlevel)
Definition at line 126 of file mincover.c.
Referenced by MinCover().
MinCover_ColDFS()
void MinCover_ColDFS (idxtype * xadj, idxtype * adjncy, int root, idxtype * mate, idxtype * where, int flag)
Definition at line 212 of file mincover.c.
References HC, HR, INCOL, and INROW.
Referenced by MinCover_Decompose().
MinCover_Decompose()
void MinCover_Decompose (idxtype * xadj, idxtype * adjncy, int asize, int bsize, idxtype * mate, idxtype * cover, int * csize)
Definition at line 163 of file mincover.c.
References abs(), HR, idxmalloc, INCOL, INROW, MinCover_ColDFS(), MinCover_RowDFS(), SC, SR, and VC.
Referenced by MinCover().
MinCover_RowDFS()
void MinCover_RowDFS (idxtype * xadj, idxtype * adjncy, int root, idxtype * mate, idxtype * where, int flag)
Definition at line 237 of file mincover.c.
References INCOL, INROW, VC, and VR.
Referenced by MinCover_Decompose().
MlevelEdgeBisection()
void MlevelEdgeBisection (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 168 of file pmetis.c.
References Coarsen2Way, Init2WayPartition, and Refine2Way.
Referenced by MlevelRecursiveBisection().
MlevelKWayPartitioning()
int MlevelKWayPartitioning (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * part, float * tpwgts, float ubfactor)
Definition at line 94 of file kmetis.c.
References graphdef::adjncy, graphdef::adjwgt, AllocateKWayPartitionMemory, Coarsen2Way, ComputePartitionInfo, DBG_IPART, DBG_KWAYPINFO, DBG_TIME, controldef::dbglvl, graphdef::gdata, GKfree, idxcopy, IFSET, controldef::InitPartTmr, IPART_GGPKL, LTERM, MATCH_SHEMKWAY, METIS_WPartGraphRecursive(), graphdef::mincut, graphdef::nvtxs, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, graphdef::rdata, RefineKWay, RTYPE_FM, starttimer, stoptimer, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by METIS_WPartGraphKway().
MlevelNestedDissection()
void MlevelNestedDissection (CtrlType * ctrl, GraphType * graph, idxtype * order, float ubfactor, int lastvtx)
Definition at line 263 of file ometis.c.
References graphdef::bndind, ConstructMinCoverSeparator, DBG_SEPINFO, DBG_TIME, controldef::dbglvl, graphdef::gdata, GKfree, idxsum, IFSET, graphdef::label, LTERM, MlevelEdgeBisection, MlevelNodeBisectionMultiple(), MMDOrder(), MMDSWITCH, graphdef::nbnd, graphdef::nvtxs, OP_OEMETIS, OP_ONMETIS, controldef::optype, graphdef::pwgts, graphdef::rdata, controldef::SepTmr, SplitGraphOrder(), starttimer, stoptimer, and graphdef::vwgt.
Referenced by GRACLUS_METIS_NodeND(), METIS_EdgeND(), and METIS_NodeWND().
MlevelNestedDissectionCC()
void MlevelNestedDissectionCC (CtrlType * ctrl, GraphType * graph, idxtype * order, float ubfactor, int lastvtx)
Definition at line 323 of file ometis.c.
References graphdef::bndind, DBG_SEPINFO, controldef::dbglvl, FindComponents, graphdef::gdata, GKfree, GKmalloc, idxmalloc, idxsum, IFSET, graphdef::label, LTERM, MlevelNodeBisectionMultiple(), MMDOrder(), graphdef::nbnd, NULL, graphdef::nvtxs, graphdef::pwgts, graphdef::rdata, SplitGraphOrderCC(), and graphdef::vwgt.
Referenced by GRACLUS_METIS_NodeND().
MlevelNestedDissectionP()
void MlevelNestedDissectionP (CtrlType * ctrl, GraphType * graph, idxtype * order, int lastvtx, int npes, int cpos, idxtype * sizes)
Definition at line 193 of file parmetis.c.
References graphdef::bndind, DBG_SEPINFO, controldef::dbglvl, graphdef::gdata, GKfree, idxsum, IFSET, graphdef::label, LTERM, MlevelNodeBisectionMultiple, MMDOrder, MMDSWITCH, graphdef::nbnd, graphdef::nvtxs, ORDER_UNBALANCE_FRACTION, graphdef::pwgts, graphdef::rdata, SplitGraphOrder, and graphdef::vwgt.
Referenced by METIS_NodeNDP().
MlevelNodeBisection()
void MlevelNodeBisection (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 468 of file ometis.c.
References Coarsen2Way, controldef::CoarsenTo, Compute2WayPartitionParams, ConstructSeparator, DBG_TIME, controldef::dbglvl, IFSET, Init2WayPartition, InitSeparator, IPART_GGPKL, IPART_GGPKLNODE, controldef::IType, controldef::maxvwgt, graphdef::nvtxs, Refine2WayNode, controldef::SepTmr, starttimer, and stoptimer.
Referenced by MlevelNodeBisectionMultiple().
MlevelNodeBisectionMultiple()
void MlevelNodeBisectionMultiple (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 386 of file ometis.c.
References Allocate2WayNodePartitionMemory, Coarsen2Way, controldef::CoarsenTo, Compute2WayNodePartitionParams, controldef::CType, GKfree, idxcopy, idxmalloc, LTERM, graphdef::mincut, MlevelNodeBisection(), controldef::nseps, graphdef::nvtxs, OFLAG_COMPRESS, controldef::oflags, graphdef::rdata, Refine2WayNode, and graphdef::where.
Referenced by MlevelNestedDissection(), and MlevelNestedDissectionCC().
MlevelRecursiveBisection()
int MlevelRecursiveBisection (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * part, float * tpwgts, float ubfactor, int fpart)
Definition at line 103 of file pmetis.c.
References cloudViewer::utility::floor(), graphdef::gdata, GKfree, idxsum, graphdef::label, LTERM, graphdef::mincut, MlevelEdgeBisection(), graphdef::nvtxs, graphdef::rdata, SplitGraphPart(), sscale, ssum, graphdef::vwgt, and graphdef::where.
Referenced by METIS_WPartGraphRecursive().
MlevelVolKWayPartitioning()
int MlevelVolKWayPartitioning (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * part, float * tpwgts, float ubfactor)
Definition at line 94 of file kvmetis.c.
References graphdef::adjncy, graphdef::adjwgt, AllocateVolKWayPartitionMemory, Coarsen2Way, ComputePartitionInfo, DBG_IPART, DBG_KWAYPINFO, DBG_TIME, controldef::dbglvl, graphdef::gdata, GKfree, idxcopy, IFSET, controldef::InitPartTmr, IPART_GGPKL, LTERM, MATCH_SHEMKWAY, METIS_WPartGraphRecursive(), graphdef::minvol, graphdef::nvtxs, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, graphdef::rdata, RefineVolKWay, RTYPE_FM, starttimer, stoptimer, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by METIS_WPartGraphVKway().
MLKKM_PartGraphKway()
void MLKKM_PartGraphKway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * chainlength, int * options, int * edgecut, idxtype * part, int levels)
Definition at line 23 of file mlkkm.c.
References fmalloc, and MLKKM_WPartGraphKway().
MLKKM_WPartGraphKway()
void MLKKM_WPartGraphKway (int * nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int * wgtflag, int * numflag, int * nparts, int * chainlength, float * tpwgts, int * options, int * edgecut, idxtype * part, int levels)
Definition at line 44 of file mlkkm.c.
References AllocateWorkSpace, Change2CNumbering, Change2FNumbering, controldef::CoarsenTo, controldef::CType, DBG_TIME, controldef::dbglvl, cloudViewer::utility::floor(), FreeWorkSpace, idxsum, IFSET, InitRandom, InitTimers, controldef::IType, KMETIS_CTYPE, KMETIS_DBGLVL, KMETIS_ITYPE, KMETIS_RTYPE, controldef::maxvwgt, MLKKMPartitioning(), OP_KMETIS, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, controldef::optype, PrintTimers, controldef::RType, SetUpGraph, starttimer, stoptimer, controldef::TotalTmr, and graphdef::vwgt.
Referenced by MLKKM_PartGraphKway().
MLKKMPartitioning()
int MLKKMPartitioning (CtrlType * ctrl, GraphType * graph, int nparts, int chain_length, idxtype * part, float * tpwgts, float ubfactor)
Definition at line 179 of file mlkkm.c.
References graphdef::adjncy, graphdef::adjwgt, AllocateKWayPartitionMemory, Coarsen2Way, ComputePartitionInfo, DBG_IPART, DBG_KWAYPINFO, DBG_TIME, controldef::dbglvl, graphdef::gdata, GKfree, idxcopy, idxmalloc, IFSET, controldef::InitPartTmr, IPART_GGPKL, LTERM, MATCH_SHEMKWAY, METIS_WPartGraphRecursive(), graphdef::mincut, MLKKMRefine(), graphdef::nvtxs, OPTION_CTYPE, OPTION_DBGLVL, OPTION_ITYPE, OPTION_RTYPE, graphdef::rdata, RTYPE_FM, spectral_initialization, starttimer, stoptimer, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by MLKKM_WPartGraphKway().
MLKKMRefine()
void MLKKMRefine (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, int nparts, int chain_length, float * tpwgts, float ubfactor)
Definition at line 1012 of file wkkm.c.
References graphdef::adjwgt, cleartimer, ComputeKWayPartitionParams, ComputeNCut(), ComputeRAsso(), cutType, DBG_TIME, controldef::dbglvl, graphdef::finer, graphdef::gdata, GKfree, idxsmalloc, IFSET, LTERM, NCUT, graphdef::nedges, NULL, graphdef::nvtxs, pingpong(), ProjectKWayPartition, controldef::ProjectTmr, result, starttimer, stoptimer, controldef::UncoarsenTmr, graphdef::vwgt, and graphdef::where.
Referenced by MLKKMPartitioning().
mmdelm()
void mmdelm (int mdeg_node, idxtype * xadj, idxtype * adjncy, idxtype * head, idxtype * forward, idxtype * backward, idxtype * qsize, idxtype * list, idxtype * marker, int maxint, int tag)
Definition at line 171 of file mmd.c.
Referenced by genmmd().
mmdint()
int mmdint (int neqns, idxtype * xadj, idxtype * adjncy, idxtype * head, idxtype * forward, idxtype * backward, idxtype * qsize, idxtype * list, idxtype * marker)
Definition at line 305 of file mmd.c.
Referenced by genmmd().
mmdnum()
void mmdnum (int neqns, idxtype * perm, idxtype * invp, idxtype * qsize)
Definition at line 348 of file mmd.c.
Referenced by genmmd().
MMDOrder()
void MMDOrder (CtrlType * ctrl, GraphType * graph, idxtype * order, int lastvtx)
Definition at line 617 of file ometis.c.
References graphdef::adjncy, genmmd, idxmalloc, graphdef::label, MAXIDX, graphdef::nvtxs, and graphdef::xadj.
Referenced by MlevelNestedDissection(), and MlevelNestedDissectionCC().
mmdupd()
void mmdupd (int ehead, int neqns, idxtype * xadj, idxtype * adjncy, int delta, int * mdeg, idxtype * head, idxtype * forward, idxtype * backward, idxtype * qsize, idxtype * list, idxtype * marker, int maxint, int * tag)
Definition at line 412 of file mmd.c.
Referenced by genmmd().
MocAllocate2WayPartitionMemory()
void MocAllocate2WayPartitionMemory (CtrlType * ctrl, GraphType * graph)
Definition at line 70 of file mrefine.c.
References graphdef::bndind, graphdef::bndptr, graphdef::ed, fmalloc, graphdef::id, idxmalloc, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::rdata, and graphdef::where.
Referenced by MocProject2WayPartition().
MocAllocateKWayPartitionMemory()
void MocAllocateKWayPartitionMemory (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 67 of file mkwayrefine.c.
References graphdef::bndind, graphdef::bndptr, fmalloc, idxmalloc, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::rdata, graphdef::rinfo, and graphdef::where.
Referenced by MocProjectKWayPartition().
MocBalance2Way()
void MocBalance2Way (CtrlType * ctrl, GraphType * graph, float * tpwgts, float lbfactor)
Definition at line 22 of file mbalance.c.
References Compute2WayHLoadImbalance, MocGeneral2WayBalance(), graphdef::ncon, and graphdef::npwgts.
MocBalance2Way2()
void MocBalance2Way2 (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 22 of file mbalance2.c.
References AreAllBelow, Compute2WayHLoadImbalanceVec, MAXNCON, MocGeneral2WayBalance2(), graphdef::ncon, and graphdef::npwgts.
MocCompute2WayPartitionParams()
void MocCompute2WayPartitionParams (CtrlType * ctrl, GraphType * graph)
Definition at line 91 of file mrefine.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, graphdef::bndind, graphdef::bndptr, graphdef::ed, graphdef::id, idxset, graphdef::mincut, graphdef::nbnd, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, saxpy, sset, graphdef::where, and graphdef::xadj.
Referenced by MocRefine2Way().
MocComputeKWayBalanceBoundary()
void MocComputeKWayBalanceBoundary (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 278 of file mkwayrefine.c.
References graphdef::bndind, BNDInsert, graphdef::bndptr, rinfodef::ed, idxset, graphdef::nbnd, graphdef::nvtxs, and graphdef::rinfo.
Referenced by MocRefineKWayHorizontal().
MocComputeKWayPartitionParams()
void MocComputeKWayPartitionParams (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 89 of file mkwayrefine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, rinfodef::id, idxset, graphdef::mincut, graphdef::nbnd, graphdef::ncon, rinfodef::ndegrees, graphdef::npwgts, NULL, graphdef::nvtxs, graphdef::nvwgt, edegreedef::pid, graphdef::rinfo, saxpy, sset, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by MocRefineKWayHorizontal().
MocFM_2WayEdgeRefine()
void MocFM_2WayEdgeRefine (CtrlType * ctrl, GraphType * graph, float * tpwgts, int npasses)
Definition at line 20 of file mfm.c.
References graphdef::adjncy, graphdef::adjwgt, amax, amin, ASSERT, BetterBalance(), BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, Compute2WayHLoadImbalance(), ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, fabs(), graphdef::id, idxset, idxwspacefree, idxwspacemalloc, INC_DEC, MAXNCON, graphdef::mincut, graphdef::nbnd, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, PLUS_GAINSPAN, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, RandomPermute, samax, saxpy, SelectQueue(), SWAP, graphdef::where, and graphdef::xadj.
MocFM_2WayEdgeRefine2()
void MocFM_2WayEdgeRefine2 (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * orgubvec, int npasses)
Definition at line 20 of file mfm2.c.
References graphdef::adjncy, graphdef::adjwgt, amax, amin, AreAllBelow, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, Compute2WayHLoadImbalanceVec, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, fabs(), fwspacefree(), fwspacemalloc, graphdef::id, idxset, idxwspacefree, idxwspacemalloc, INC_DEC, IsBetter2wayBalance(), MAXNCON, graphdef::mincut, graphdef::nbnd, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, PLUS_GAINSPAN, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, RandomPermute, samax, saxpy, SelectQueue2(), SWAP, graphdef::where, and graphdef::xadj.
MocGeneral2WayBalance()
void MocGeneral2WayBalance (CtrlType * ctrl, GraphType * graph, float * tpwgts, float lbfactor)
Definition at line 36 of file mbalance.c.
References graphdef::adjncy, graphdef::adjwgt, amax, amin, ASSERT, BetterBalance, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, Compute2WayHLoadImbalance, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, fabs(), graphdef::id, idxset, idxwspacefree, idxwspacemalloc, INC_DEC, MAXNCON, graphdef::mincut, graphdef::nbnd, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, PLUS_GAINSPAN, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueUpdate, RandomPermute, samax, samax2, saxpy, SelectQueue, SWAP, graphdef::where, and graphdef::xadj.
Referenced by MocBalance2Way().
MocGeneral2WayBalance2()
void MocGeneral2WayBalance2 (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 37 of file mbalance2.c.
References graphdef::adjncy, graphdef::adjwgt, amax, amin, AreAllBelow, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, Compute2WayHLoadImbalanceVec, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, fwspacefree(), fwspacemalloc, graphdef::id, idxset, idxwspacefree, idxwspacemalloc, INC_DEC, IsBetter2wayBalance, MAXNCON, graphdef::mincut, graphdef::nbnd, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, PLUS_GAINSPAN, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueUpdate, RandomPermute, samax, saxpy, SelectQueue3(), SWAP, graphdef::where, and graphdef::xadj.
Referenced by MocBalance2Way2().
MocGrowBisection()
void MocGrowBisection (CtrlType * ctrl, GraphType * graph, float * tpwgts, float ubfactor)
Definition at line 57 of file minitpart.c.
References graphdef::adjwgt, controldef::CoarsenTo, GKfree, idxcopy, idxmalloc, idxset, idxsum, LARGENIPARTS, LTERM, graphdef::mincut, MocAllocate2WayPartitionMemory, MocBalance2Way, MocCompute2WayPartitionParams, MocFM_2WayEdgeRefine, MocInit2WayBalance(), graphdef::nedges, graphdef::nvtxs, RandomInRange, SMALLNIPARTS, and graphdef::where.
Referenced by MocInit2WayPartition().
MocGrowBisection2()
void MocGrowBisection2 (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 57 of file minitpart2.c.
References graphdef::adjwgt, controldef::CoarsenTo, GKfree, idxcopy, idxmalloc, idxset, idxsum, LARGENIPARTS, LTERM, graphdef::mincut, MocAllocate2WayPartitionMemory, MocBalance2Way2, MocCompute2WayPartitionParams, MocFM_2WayEdgeRefine2, graphdef::nedges, graphdef::nvtxs, RandomInRange, SMALLNIPARTS, and graphdef::where.
Referenced by MocInit2WayPartition2().
MocGrowBisectionNew2()
void MocGrowBisectionNew2 (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 108 of file minitpart2.c.
References graphdef::adjwgt, controldef::CoarsenTo, GKfree, idxcopy, idxmalloc, idxset, idxsum, LARGENIPARTS, LTERM, graphdef::mincut, MocAllocate2WayPartitionMemory, MocCompute2WayPartitionParams, MocFM_2WayEdgeRefine2, MocInit2WayBalance2(), graphdef::nedges, graphdef::nvtxs, RandomInRange, SMALLNIPARTS, and graphdef::where.
Referenced by MocInit2WayPartition2().
MocInit2WayBalance()
void MocInit2WayBalance (CtrlType * ctrl, GraphType * graph, float * tpwgts)
Definition at line 178 of file minitpart.c.
References graphdef::adjncy, graphdef::adjwgt, AreAnyVwgtsBelow, ASSERT, ASSERTP, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, CheckGraph(), Compute2WayHLoadImbalance, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, graphdef::id, idxwspacefree, idxwspacemalloc, INC_DEC, MAXNCON, graphdef::mincut, graphdef::nbnd, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, PLUS_GAINSPAN, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueUpdate, RandomPermute, samax, saxpy, SelectQueueOneWay(), SWAP, graphdef::where, and graphdef::xadj.
Referenced by MocGrowBisection().
MocInit2WayBalance2()
void MocInit2WayBalance2 (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 156 of file minitpart2.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, ASSERTP, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckBnd, CheckGraph(), ComputeCut, ComputeLoadImbalance, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, graphdef::ed, graphdef::id, idxset, idxwspacefree, idxwspacemalloc, INC_DEC, MAXNCON, graphdef::mincut, graphdef::nbnd, graphdef::ncon, graphdef::npwgts, graphdef::nvtxs, graphdef::nvwgt, PLUS_GAINSPAN, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueUpdate, RandomPermute, samax, saxpy, SelectQueueOneWay2(), SWAP, graphdef::where, and graphdef::xadj.
Referenced by MocGrowBisectionNew2().
MocInit2WayPartition()
void MocInit2WayPartition (CtrlType * ctrl, GraphType * graph, float * tpwgts, float ubfactor)
Definition at line 21 of file minitpart.c.
References DBG_IPART, DBG_MOVEINFO, DBG_REFINE, DBG_TIME, controldef::dbglvl, graclus_errexit(), IFSET, controldef::InitPartTmr, IPART_GGPKL, IPART_RANDOM, controldef::IType, graphdef::mincut, MocGrowBisection(), MocRandomBisection(), starttimer, stoptimer, and graphdef::where.
MocInit2WayPartition2()
void MocInit2WayPartition2 (CtrlType * ctrl, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 21 of file minitpart2.c.
References DBG_IPART, DBG_MOVEINFO, DBG_REFINE, DBG_TIME, controldef::dbglvl, graclus_errexit(), IFSET, controldef::InitPartTmr, IPART_GGPKL, IPART_RANDOM, controldef::IType, graphdef::mincut, MocGrowBisection2(), MocGrowBisectionNew2(), starttimer, and stoptimer.
MocIsHBalanced()
int MocIsHBalanced (int ncon, int nparts, float * npwgts, float * ubvec)
Definition at line 565 of file mkwayfmh.c.
References max().
Referenced by MCGreedy_KWayEdgeBalanceHorizontal().
MocProject2WayPartition()
void MocProject2WayPartition (CtrlType * ctrl, GraphType * graph)
Definition at line 149 of file mrefine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::bndind, graphdef::bndptr, graphdef::cmap, graphdef::coarser, graphdef::ed, FreeGraph, graphdef::id, idxset, graphdef::mincut, MocAllocate2WayPartitionMemory(), graphdef::nbnd, graphdef::ncon, graphdef::npwgts, NULL, graphdef::nvtxs, scopy, graphdef::where, and graphdef::xadj.
Referenced by MocRefine2Way().
MocProjectKWayPartition()
void MocProjectKWayPartition (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 172 of file mkwayrefine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckBnd2, graphdef::cmap, graphdef::coarser, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, FreeGraph, rinfodef::id, idxset, idxwspacefree, idxwspacemalloc, graphdef::mincut, MocAllocateKWayPartitionMemory(), graphdef::nbnd, graphdef::ncon, rinfodef::ndegrees, graphdef::npwgts, NULL, graphdef::nvtxs, edegreedef::pid, graphdef::rinfo, scopy, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by MocRefineKWayHorizontal().
MocRandomBisection()
void MocRandomBisection (CtrlType * ctrl, GraphType * graph, float * tpwgts, float ubfactor)
Definition at line 105 of file minitpart.c.
References graphdef::adjwgt, controldef::CoarsenTo, GKfree, idxcopy, idxmalloc, idxsum, LARGENIPARTS, LTERM, MAXNCON, graphdef::mincut, MocAllocate2WayPartitionMemory, MocBalance2Way, MocCompute2WayPartitionParams, MocFM_2WayEdgeRefine, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::nvwgt, RandomPermute, samax, SMALLNIPARTS, and graphdef::where.
Referenced by MocInit2WayPartition().
MocRefine2Way()
void MocRefine2Way (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, float * tpwgts, float ubfactor)
Definition at line 20 of file mrefine.c.
References ASSERT, CheckBnd, DBG_TIME, controldef::dbglvl, graphdef::finer, graclus_errexit(), IFSET, MAXNCON, MocBalance2Way, MocCompute2WayPartitionParams(), MocFM_2WayEdgeRefine, MocFM_2WayEdgeRefine2, MocProject2WayPartition(), graphdef::ncon, controldef::ProjectTmr, controldef::RefTmr, controldef::RType, RTYPE_FM, starttimer, stoptimer, and controldef::UncoarsenTmr.
MocRefine2Way2()
void MocRefine2Way2 (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, float * tpwgts, float * ubvec)
Definition at line 20 of file mrefine2.c.
References ASSERT, CheckBnd, DBG_TIME, controldef::dbglvl, graphdef::finer, graclus_errexit(), IFSET, MocBalance2Way2, MocCompute2WayPartitionParams, MocFM_2WayEdgeRefine2, MocProject2WayPartition, controldef::ProjectTmr, controldef::RefTmr, controldef::RType, RTYPE_FM, starttimer, stoptimer, and controldef::UncoarsenTmr.
MocRefineKWayHorizontal()
void MocRefineKWayHorizontal (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, int nparts, float * ubvec)
Definition at line 20 of file mkwayrefine.c.
References ComputeKWayBoundary, DBG_TIME, controldef::dbglvl, graphdef::finer, IFSET, MCGreedy_KWayEdgeBalanceHorizontal, MCRandom_KWayEdgeRefineHorizontal, MocComputeKWayBalanceBoundary(), MocComputeKWayPartitionParams(), MocIsHBalanced, MocProjectKWayPartition(), graphdef::ncon, graphdef::npwgts, controldef::ProjectTmr, controldef::RefTmr, starttimer, stoptimer, and controldef::UncoarsenTmr.
move1Point2EmptyCluster()
void move1Point2EmptyCluster (GraphType * graph, int nparts, idxtype * sum, idxtype * squared_sum, idxtype * w, idxtype * self_sim, int ** linearTerm, int k)
Definition at line 736 of file wkkm.c.
MoveGroup()
void MoveGroup (CtrlType * ctrl, GraphType * graph, int nparts, int to, int gid, idxtype * ptr, idxtype * ind)
Definition at line 1174 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, rinfodef::id, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, graphdef::rinfo, SWAP, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by EliminateComponents().
MoveGroupMConn()
void MoveGroupMConn (CtrlType * ctrl, GraphType * graph, idxtype * ndoms, idxtype * pmat, int nparts, int to, int nind, idxtype * ind)
Definition at line 892 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, rinfodef::id, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, graphdef::rinfo, SWAP, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by EliminateSubDomainEdges().
onePoint_move()
float onePoint_move (GraphType * graph, int nparts, idxtype * sum, idxtype * squared_sum, idxtype * w, idxtype * self_sim, int ** linearTerm, int ii)
Definition at line 608 of file wkkm.c.
pingpong()
void pingpong (CtrlType * ctrl, GraphType * graph, int nparts, int chain_length, float * tpwgts, float ubfactor, int toplevel)
Definition at line 138 of file wkkm.c.
References Compute_Weights(), idxsmalloc, local_search(), MAXITERATIONS, memory_saving, graphdef::nbnd, graphdef::nedges, graphdef::nvtxs, remove_empty_clusters_l1(), remove_empty_clusters_l2(), and Weighted_kernel_k_means().
Referenced by MLKKMRefine().
PQueueDelete()
int PQueueDelete (PQueueType * queue, int node, int gain)
Definition at line 197 of file pqueue.c.
References ASSERT, PQueueType::buckets, CheckHeap(), PQueueType::heap, KeyValueType::key, PQueueType::locator, PQueueType::maxgain, ListNodeType::next, PQueueType::ngainspan, PQueueType::nnodes, PQueueType::nodes, NULL, ListNodeType::prev, PQueueType::type, and KeyValueType::val.
Referenced by PQueueUpdate().
PQueueFree()
void PQueueFree (CtrlType * ctrl, PQueueType * queue)
Definition at line 104 of file pqueue.c.
References PQueueType::buckets, GKfree, idxwspacefree, LTERM, PQueueType::maxnodes, PQueueType::mustfree, PQueueType::ngainspan, PQueueType::nodes, PQueueType::pgainspan, and PQueueType::type.
PQueueGetKey()
int PQueueGetKey (PQueueType * queue)
Definition at line 530 of file pqueue.c.
References PQueueType::heap, KeyValueType::key, PQueueType::maxgain, PQueueType::nnodes, and PQueueType::type.
Referenced by SelectQueue(), SelectQueue2(), SelectQueue3(), and SelectQueueOneWay2().
PQueueGetMax()
int PQueueGetMax (PQueueType * queue)
Definition at line 440 of file pqueue.c.
References ASSERT, PQueueType::buckets, CheckHeap(), PQueueType::heap, ListNodeType::id, KeyValueType::key, PQueueType::locator, PQueueType::maxgain, ListNodeType::next, PQueueType::ngainspan, PQueueType::nnodes, NULL, ListNodeType::prev, PQueueType::type, and KeyValueType::val.
PQueueGetSize()
int PQueueGetSize (PQueueType * queue)
Definition at line 129 of file pqueue.c.
References PQueueType::nnodes.
Referenced by SelectQueue(), SelectQueue2(), SelectQueue3(), SelectQueueOneWay(), and SelectQueueOneWay2().
PQueueInit()
void PQueueInit (CtrlType * ctrl, PQueueType * queue, int maxnodes, int maxgain)
Definition at line 23 of file pqueue.c.
References amin, PQueueType::buckets, PQueueType::heap, ListNodeType::id, idxmalloc, idxset, idxwspacemalloc, PQueueType::locator, PQueueType::maxgain, PQueueType::maxnodes, PQueueType::mustfree, NEG_GAINSPAN, PQueueType::ngainspan, PQueueType::nnodes, PQueueType::nodes, NULL, PQueueType::pgainspan, PLUS_GAINSPAN, PQueueType::type, and WspaceAvail.
PQueueInsert()
int PQueueInsert (PQueueType * queue, int node, int gain)
Definition at line 138 of file pqueue.c.
References ASSERT, PQueueType::buckets, CheckHeap(), PQueueType::heap, KeyValueType::key, PQueueType::locator, PQueueType::maxgain, ListNodeType::next, PQueueType::ngainspan, PQueueType::nnodes, PQueueType::nodes, NULL, ListNodeType::prev, PQueueType::type, and KeyValueType::val.
Referenced by PQueueUpdate().
PQueueReset()
void PQueueReset (PQueueType * queue)
Definition at line 80 of file pqueue.c.
References PQueueType::buckets, idxset, PQueueType::locator, PQueueType::maxgain, PQueueType::maxnodes, PQueueType::ngainspan, PQueueType::nnodes, NULL, PQueueType::pgainspan, and PQueueType::type.
PQueueSeeMax()
int PQueueSeeMax (PQueueType * queue)
Definition at line 511 of file pqueue.c.
References PQueueType::buckets, PQueueType::heap, ListNodeType::id, PQueueType::maxgain, PQueueType::nnodes, PQueueType::type, and KeyValueType::val.
PQueueUpdate()
int PQueueUpdate (PQueueType * queue, int node, int oldgain, int newgain)
Definition at line 293 of file pqueue.c.
References ASSERT, CheckHeap(), PQueueType::heap, KeyValueType::key, PQueueType::locator, PQueueType::nnodes, PQueueDelete(), PQueueInsert(), PQueueType::type, and KeyValueType::val.
PQueueUpdateUp()
void PQueueUpdateUp (PQueueType * queue, int node, int oldgain, int newgain)
Definition at line 367 of file pqueue.c.
References ASSERT, PQueueType::buckets, CheckHeap(), PQueueType::heap, KeyValueType::key, PQueueType::locator, PQueueType::maxgain, ListNodeType::next, PQueueType::ngainspan, PQueueType::nnodes, PQueueType::nodes, NULL, ListNodeType::prev, PQueueType::type, and KeyValueType::val.
print_help()
void print_help (char * program_name)
Definition at line 19 of file util.c.
PrintSubDomainGraph()
void PrintSubDomainGraph (GraphType * graph, int nparts, idxtype * where)
Definition at line 625 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, idxsmalloc, max(), graphdef::nvtxs, and graphdef::xadj.
PrintTimers()
void PrintTimers (CtrlType * ctrl)
Definition at line 46 of file timing.c.
References controldef::AuxTmr1, controldef::AuxTmr2, controldef::AuxTmr3, controldef::CoarsenTmr, controldef::ContractTmr, gettimer, controldef::InitPartTmr, controldef::MatchTmr, controldef::ProjectTmr, controldef::RefTmr, controldef::SepTmr, controldef::SplitTmr, controldef::TotalTmr, and controldef::UncoarsenTmr.
Project2WayNodePartition()
void Project2WayNodePartition (CtrlType * ctrl, GraphType * graph)
Definition at line 144 of file srefine.c.
References Allocate2WayNodePartitionMemory(), ASSERTP, graphdef::cmap, graphdef::coarser, Compute2WayNodePartitionParams(), FreeGraph, NULL, graphdef::nvtxs, and graphdef::where.
Referenced by Refine2WayNode().
Project2WayPartition()
void Project2WayPartition (CtrlType * ctrl, GraphType * graph)
Definition at line 134 of file refine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, Allocate2WayPartitionMemory(), graphdef::bndind, graphdef::bndptr, graphdef::cmap, graphdef::coarser, graphdef::ed, FreeGraph, graphdef::id, idxcopy, idxset, graphdef::mincut, graphdef::nbnd, NULL, graphdef::nvtxs, graphdef::pwgts, graphdef::where, and graphdef::xadj.
Referenced by Refine2Way().
ProjectKWayPartition()
void ProjectKWayPartition (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 222 of file kwayrefine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, AllocateKWayPartitionMemory(), ASSERT, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckBnd2, graphdef::cmap, graphdef::coarser, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, FreeGraph, rinfodef::id, idxcopy, idxset, idxwspacefree, idxwspacemalloc, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, graphdef::pwgts, graphdef::rinfo, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by RefineKWay().
ProjectVolKWayPartition()
void ProjectVolKWayPartition (CtrlType * ctrl, GraphType * graph, int nparts)
Definition at line 309 of file kwayvolrefine.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, AllocateVolKWayPartitionMemory(), workspacedef::cdegree, graphdef::cmap, graphdef::coarser, ComputeKWayVolGains(), vedegreedef::ed, vrinfodef::ed, vrinfodef::edegrees, FreeGraph, vedegreedef::gv, vrinfodef::id, idxcopy, idxset, idxwspacefree, idxwspacemalloc, graphdef::mincut, vrinfodef::ndegrees, vedegreedef::ned, vrinfodef::nid, NULL, graphdef::nvtxs, vedegreedef::pid, graphdef::pwgts, workspacedef::vedegrees, graphdef::vrinfo, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by RefineVolKWay().
PruneGraph()
void PruneGraph (CtrlType * ctrl, GraphType * graph, int nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * iperm, float factor)
Definition at line 160 of file compress.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::cmap, graphdef::gdata, idxmalloc, idxset, InitGraph, graphdef::label, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::vwgt, and graphdef::xadj.
QUADNODALMETIS()
void QUADNODALMETIS (int nelmnts, int nvtxs, idxtype * elmnts, idxtype * dxadj, idxtype * adjncy)
Definition at line 340 of file mesh.c.
References ASSERT, idxmalloc, idxsmalloc, and MAKECSR.
Referenced by METIS_MeshToNodal().
Random_KWayEdgeRefine()
void Random_KWayEdgeRefine (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses, int ffactor)
Definition at line 19 of file kwayfm.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, ComputeVolume, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, cloudViewer::utility::floor(), rinfodef::id, idxamax, idxamin, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, graphdef::pwgts, RandomPermute, graphdef::rinfo, SWAP, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
Random_KWayEdgeRefineMConn()
void Random_KWayEdgeRefineMConn (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses, int ffactor)
Definition at line 22 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, ComputeSubDomainGraph(), ComputeVolume, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, rinfodef::id, idxamax, idxamin, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, workspacedef::pmat, graphdef::pwgts, RandomPermute, graphdef::rinfo, SWAP, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
Random_KWayVolRefine()
void Random_KWayVolRefine (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses, int ffactor)
Definition at line 19 of file kwayvolfm.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, graphdef::bndind, graphdef::bndptr, ComputeCut, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, vedegreedef::ed, vrinfodef::ed, vrinfodef::edegrees, GKfree, vedegreedef::gv, vrinfodef::gv, vrinfodef::id, idxamax, idxamin, idxmalloc, idxsmalloc, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, KWayVolUpdate(), LTERM, graphdef::mincut, graphdef::minvol, graphdef::nbnd, vrinfodef::ndegrees, graphdef::nvtxs, vedegreedef::pid, graphdef::pwgts, RandomPermute, graphdef::vrinfo, graphdef::vsize, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Random_KWayVolRefineMConn()
void Random_KWayVolRefineMConn (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses, int ffactor)
Definition at line 163 of file kwayvolfm.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, graphdef::bndind, graphdef::bndptr, ComputeCut, ComputeVolSubDomainGraph(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, vedegreedef::ed, vrinfodef::ed, vrinfodef::edegrees, GKfree, vedegreedef::gv, vrinfodef::gv, vrinfodef::id, idxamax, idxamin, idxmalloc, idxsmalloc, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, KWayVolUpdate(), LTERM, graphdef::mincut, graphdef::minvol, graphdef::nbnd, vrinfodef::ndegrees, graphdef::nvtxs, vedegreedef::pid, workspacedef::pmat, graphdef::pwgts, RandomPermute, graphdef::vrinfo, graphdef::vsize, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
RandomBisection()
void RandomBisection (CtrlType * ctrl, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 346 of file initpart.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, Allocate2WayPartitionMemory, ASSERTP, Balance2Way, controldef::CoarsenTo, Compute2WayPartitionParams, FM_2WayEdgeRefine, GKfree, idxcopy, idxmalloc, idxset, idxsum, LARGENIPARTS, LTERM, graphdef::mincut, graphdef::nvtxs, RandomPermute, SMALLNIPARTS, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by Init2WayPartition().
RandomInit()
void RandomInit (int n, int k, idxtype * label)
Definition at line 618 of file util.c.
References idxmalloc(), and RandomPermute().
RandomizeGraph()
void RandomizeGraph (GraphType * graph)
Definition at line 352 of file graph.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::nvtxs, RandomInRange, SWAP, and graphdef::xadj.
RandomPermute()
void RandomPermute (int n, idxtype * p, int flag)
Definition at line 576 of file util.c.
Referenced by RandomInit().
ReadCoarsestInit()
void ReadCoarsestInit (GraphType * graph, char * filename, int * wgtflag)
ReadGraph()
void ReadGraph (GraphType * , char * , int *)
ReAdjustMemory()
void ReAdjustMemory (GraphType * graph, GraphType * cgraph, int dovsize)
Definition at line 543 of file ccgraph.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::cmap, graphdef::gdata, idxcopy, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::vsize, graphdef::vwgt, and graphdef::xadj.
Referenced by CreateCoarseGraph(), CreateCoarseGraph_NVW(), and CreateCoarseGraphNoMask().
ReadMesh()
idxtype* ReadMesh (char * , int * , int * , int *)
Refine2Way()
void Refine2Way (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, int * tpwgts, float ubfactor)
Definition at line 20 of file refine.c.
References ASSERT, Balance2Way, CheckBnd, Compute2WayPartitionParams(), DBG_TIME, controldef::dbglvl, graphdef::finer, FM_2WayEdgeRefine, graclus_errexit(), IFSET, Project2WayPartition(), controldef::ProjectTmr, controldef::RefTmr, controldef::RType, starttimer, stoptimer, and controldef::UncoarsenTmr.
Refine2WayNode()
void Refine2WayNode (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, float ubfactor)
Definition at line 21 of file srefine.c.
References DBG_TIME, controldef::dbglvl, graphdef::finer, FM_2WayNodeBalance, FM_2WayNodeRefine, FM_2WayNodeRefine_OneSided, FM_2WayNodeRefineEqWgt, IFSET, Project2WayNodePartition(), controldef::ProjectTmr, controldef::RefTmr, controldef::RType, starttimer, stoptimer, and controldef::UncoarsenTmr.
RefineKWay()
void RefineKWay (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, int nparts, float * tpwgts, float ubfactor)
Definition at line 20 of file kwayrefine.c.
References graphdef::adjwgt, controldef::AuxTmr1, controldef::AuxTmr2, ComputeKWayBalanceBoundary(), ComputeKWayBoundary(), ComputeKWayPartitionParams(), DBG_TIME, controldef::dbglvl, EliminateComponents, EliminateSubDomainEdges, graphdef::finer, graphdef::gdata, GKfree, Greedy_KWayEdgeBalance, Greedy_KWayEdgeBalanceMConn, Greedy_KWayEdgeRefine, idxsmalloc, IFSET, IsBalanced(), LTERM, graphdef::nedges, NULL, graphdef::nvtxs, ProjectKWayPartition(), controldef::ProjectTmr, graphdef::pwgts, Random_KWayEdgeRefine, Random_KWayEdgeRefineMConn, controldef::RefTmr, controldef::RType, RTYPE_KWAYGREEDY, RTYPE_KWAYRANDOM, RTYPE_KWAYRANDOM_MCONN, starttimer, stoptimer, controldef::UncoarsenTmr, and graphdef::vwgt.
RefineVolKWay()
void RefineVolKWay (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, int nparts, float * tpwgts, float ubfactor)
Definition at line 20 of file kwayvolrefine.c.
References ComputeVolKWayBalanceBoundary(), ComputeVolKWayBoundary(), ComputeVolKWayPartitionParams(), DBG_TIME, controldef::dbglvl, EliminateVolComponents(), EliminateVolSubDomainEdges, graphdef::finer, graphdef::gdata, GKfree, Greedy_KWayVolBalance, Greedy_KWayVolBalanceMConn, IFSET, IsBalanced, LTERM, MALLOC_CHECK, NULL, controldef::ProjectTmr, ProjectVolKWayPartition(), graphdef::pwgts, Random_KWayVolRefine, Random_KWayVolRefineMConn, controldef::RefTmr, controldef::RType, RTYPE_KWAYRANDOM, RTYPE_KWAYRANDOM_MCONN, starttimer, stoptimer, and controldef::UncoarsenTmr.
remove_empty_clusters_l1()
void remove_empty_clusters_l1 (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * w, float * tpwgts, float ubfactor)
Definition at line 912 of file wkkm.c.
References clusterSize(), imalloc, and local_search().
Referenced by pingpong().
remove_empty_clusters_l2()
void remove_empty_clusters_l2 (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * w, float * tpwgts, float ubfactor)
Definition at line 929 of file wkkm.c.
References clusterSize(), and imalloc.
Referenced by pingpong().
samax()
int samax (int n, float * x)
Definition at line 354 of file util.c.
References max().
samax2()
int samax2 (int n, float * x)
Definition at line 367 of file util.c.
samin()
int samin (int n, float * x)
Definition at line 410 of file util.c.
References min().
saxpy()
void saxpy (int n, float alpha, float * x, int incx, float * y, int incy)
Definition at line 560 of file util.c.
sdot()
float sdot (int n, float * x, float * y)
Definition at line 545 of file util.c.
References partial.
seconds()
double seconds (void)
Definition at line 69 of file timing.c.
SelectQueue()
void SelectQueue (int , float * , float * , int * , int * , PQueueType [MAXNCON][2])
SelectQueue2()
void SelectQueue2 (int , float * , float * , int * , int * , PQueueType [MAXNCON][2], float *)
SelectQueue3()
void SelectQueue3 (int , float * , float * , int * , int * , PQueueType [MAXNCON][2], float *)
SelectQueueOneWay()
int SelectQueueOneWay (int , float * , float * , int , PQueueType [MAXNCON][2])
SelectQueueOneWay2()
int SelectQueueOneWay2 (int , float * , PQueueType [MAXNCON][2], float *)
SetUpCoarseGraph()
GraphType* SetUpCoarseGraph (GraphType * graph, int cnvtxs, int dovsize)
Definition at line 479 of file ccgraph.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::cmap, graphdef::coarser, CreateGraph, graphdef::finer, fmalloc, graphdef::gdata, idxmalloc, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::nvwgt, graphdef::vsize, graphdef::vwgt, and graphdef::xadj.
Referenced by CreateCoarseGraph(), CreateCoarseGraph_NVW(), and CreateCoarseGraphNoMask().
SetUpGraph()
void SetUpGraph (GraphType * graph, int OpType, int nvtxs, int ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * adjwgt, int wgtflag)
Definition at line 21 of file graph.c.
SetUpGraph2()
void SetUpGraph2 (GraphType * graph, int nvtxs, int ncon, idxtype * xadj, idxtype * adjncy, float * nvwgt, idxtype * adjwgt)
Definition at line 171 of file graph.c.
SetUpGraphKway()
void SetUpGraphKway (GraphType * graph, int nvtxs, idxtype * xadj, idxtype * adjncy)
Definition at line 142 of file graph.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::cmap, graphdef::gdata, idxmalloc, InitGraph, graphdef::ncon, graphdef::nedges, NULL, graphdef::nvtxs, graphdef::vwgt, and graphdef::xadj.
SetUpSplitGraph()
void SetUpSplitGraph (GraphType * graph, GraphType * sgraph, int snvtxs, int snedges)
Definition at line 309 of file pmetis.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, graphdef::cmap, fmalloc, graphdef::gdata, idxmalloc, InitGraph, graphdef::label, graphdef::ncon, graphdef::nedges, graphdef::nvtxs, graphdef::nvwgt, graphdef::vwgt, and graphdef::xadj.
smbfct()
int smbfct (int , idxtype * , idxtype * , idxtype * , idxtype * , idxtype * , int * , idxtype * , idxtype * , int *)
snorm2()
float snorm2 (int n, float * v)
Definition at line 529 of file util.c.
References partial.
sparse2dense()
void sparse2dense (GraphType * graph, double * dense, float * m_adjwgt)
Definition at line 46 of file util.c.
References graphdef::adjncy, graphdef::adjwgt, NULL, graphdef::nvtxs, and graphdef::xadj.
spectralInit()
void spectralInit (GraphType * , int , int * , int *)
SplitGraphOrder()
void SplitGraphOrder (CtrlType * ctrl, GraphType * graph, GraphType * lgraph, GraphType * rgraph)
Definition at line 508 of file ometis.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, graphdef::bndind, graphdef::bndptr, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, graphdef::label, graphdef::nbnd, graphdef::nedges, NULL, graphdef::nvtxs, SetUpSplitGraph, controldef::SplitTmr, starttimer, stoptimer, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by MlevelNestedDissection().
SplitGraphOrderCC()
int SplitGraphOrderCC (CtrlType * ctrl, GraphType * graph, GraphType * sgraphs, int ncmps, idxtype * cptr, idxtype * cind)
Definition at line 663 of file ometis.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, graphdef::bndind, graphdef::bndptr, DBG_TIME, controldef::dbglvl, idxset, idxwspacefree, idxwspacemalloc, IFSET, graphdef::label, MMDSWITCH, graphdef::nbnd, graphdef::ncon, graphdef::nedges, NULL, graphdef::nvtxs, RandomPermute, SetUpSplitGraph, controldef::SplitTmr, starttimer, stoptimer, graphdef::vwgt, graphdef::where, and graphdef::xadj.
Referenced by MlevelNestedDissectionCC().
SplitGraphPart()
void SplitGraphPart (CtrlType * ctrl, GraphType * graph, GraphType * lgraph, GraphType * rgraph)
Definition at line 190 of file pmetis.c.
Referenced by MlevelRecursiveBisection().
sscale()
void sscale (int n, float alpha, float * x)
Definition at line 517 of file util.c.
sset()
float* sset (int n, float val, float * x)
Definition at line 296 of file util.c.
ssum()
float ssum (int n, float * x)
Definition at line 489 of file util.c.
ssum_strd()
float ssum_strd (int n, float * x, int incx)
Definition at line 503 of file util.c.
Test_ND()
void Test_ND (int , idxtype * , idxtype *)
Test_PartGraph()
void Test_PartGraph (int , idxtype * , idxtype *)
Test_PartGraphmC()
void Test_PartGraphmC (int , idxtype * , idxtype *)
Test_PartGraphV()
void Test_PartGraphV (int , idxtype * , idxtype *)
TETNODALMETIS()
void TETNODALMETIS (int nelmnts, int nvtxs, idxtype * elmnts, idxtype * dxadj, idxtype * adjncy)
Definition at line 218 of file mesh.c.
References idxmalloc, idxsmalloc, and MAKECSR.
Referenced by METIS_MeshToNodal().
transform_matrix()
void transform_matrix (CtrlType * ctrl, GraphType * graph, idxtype * w, float * adjwgt)
Definition at line 43 of file wkkm.c.
References graphdef::adjncy, graphdef::adjwgt, cutType, NULL, graphdef::nvtxs, RASSO, and graphdef::xadj.
Referenced by pingpong().
transform_matrix_half()
void transform_matrix_half (CtrlType * ctrl, GraphType * graph, idxtype * w, float * adjwgt)
Definition at line 90 of file wkkm.c.
References graphdef::adjncy, graphdef::adjwgt, cutType, NULL, graphdef::nvtxs, RASSO, and graphdef::xadj.
TRINODALMETIS()
void TRINODALMETIS (int nelmnts, int nvtxs, idxtype * elmnts, idxtype * dxadj, idxtype * adjncy)
Definition at line 169 of file mesh.c.
References idxmalloc, idxsmalloc, and MAKECSR.
Referenced by METIS_MeshToNodal().
VerifyND()
int VerifyND (int , idxtype * , idxtype *)
VerifyPart()
int VerifyPart (int , idxtype * , idxtype * , idxtype * , idxtype * , int , int , idxtype *)
VerifyPartmC()
int VerifyPartmC (int , int , idxtype * , idxtype * , idxtype * , idxtype * , int , float * , int , idxtype *)
VerifyPartV()
int VerifyPartV (int , idxtype * , idxtype * , idxtype * , idxtype * , int , int , idxtype *)
VerifyWPart()
int VerifyWPart (int , idxtype * , idxtype * , idxtype * , idxtype * , int , float * , int , idxtype *)
VerifyWPartV()
int VerifyWPartV (int , idxtype * , idxtype * , idxtype * , idxtype * , int , float * , int , idxtype *)
VolSetUpGraph()
void VolSetUpGraph (GraphType * graph, int OpType, int nvtxs, int ncon, idxtype * xadj, idxtype * adjncy, idxtype * vwgt, idxtype * vsize, int wgtflag)
Definition at line 211 of file graph.c.
Weighted_kernel_k_means()
void Weighted_kernel_k_means (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * w, float * tpwgts, float ubfactor)
Definition at line 183 of file wkkm.c.
Referenced by pingpong().
WriteCoarsestGraph()
void WriteCoarsestGraph (GraphType * graph, char * filename, int * wgtflag)
WriteGraph()
void WriteGraph (char * , int , idxtype * , idxtype *)
WriteMeshPartition()
void WriteMeshPartition (char * , int , int , idxtype * , int , idxtype *)
WritePartition()
void WritePartition (char * , idxtype * , int , int)
WritePermutation()
void WritePermutation (char * , idxtype * , int)
WspaceAvail()
int WspaceAvail (CtrlType * ctrl)
Definition at line 95 of file memory.c.
References workspacedef::ccore, workspacedef::maxcore, and controldef::wspace.