ACloudViewer: /root/ACloudViewer/libs/CV_io/src/PTXFilter.cpp File Reference
PTXFilter.cpp File Reference
#include "PTXFilter.h"
#include <CVLog.h>
#include <ecvColorScalesManager.h>
#include <ecvGBLSensor.h>
#include <ecvGriddedTools.h>
#include <ecvPointCloud.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <QMessageBox>
#include <QTextStream>
#include <QtCompat.h>
#include <cassert>
#include <string>
Functions
void CleanMatrix (ccGLMatrixd &mat)
Variables
const char CC_PTX_INTENSITY_FIELD_NAME [] = "Intensity"
Function Documentation
CleanMatrix()
void CleanMatrix (ccGLMatrixd & mat)
Definition at line 40 of file PTXFilter.cpp.
References Vector3Tpl< Type >::cross(), ccGLMatrixTpl< T >::getColumn(), ccGLMatrixTpl< T >::getTranslationAsVec3D(), Vector3Tpl< Type >::normalize(), and X.
Referenced by PTXFilter::loadFile().
Variable Documentation
CC_PTX_INTENSITY_FIELD_NAME
const char CC_PTX_INTENSITY_FIELD_NAME[] = "Intensity"
Definition at line 32 of file PTXFilter.cpp.
Referenced by PTXFilter::loadFile().