ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/pycc.cpp File Reference
pycc.cpp File Reference
#include <CVTypes.h>
#include <QMainWindow>
#include <QtOpenGLWidgets/QOpenGLWidget>
#include <QProgressDialog>
#include <QWidget>
#include "casters.h"
#include <pybind11/numpy.h>
#include <pybind11/stl_bind.h>
Typedefs
template<class T >
using observer_ptr = std::unique_ptr< T, py::nodelete >
Functions
void define_qcc_db (py::module &)
void define_qcc_io (py::module &)
void load_pluginWrappers (py::module &)
template<typename T >
std::enable_if< std::is_same< T, double >::value, void >::type define_scalar_type (py::module &m)
template<typename T >
std::enable_if< std::is_same< T, float >::value, void >::type define_scalar_type (py::module &m)
void InitQApplication ()
void import_pyccRuntime (py::module &m)
void define_someQtThings (py::module &m)
void define_pycc (py::module &m)
PYBIND11_MODULE (pycc, m)
Typedef Documentation
observer_ptr
template<class T > using observer_ptr = std::unique_ptr<T, py::nodelete>
Definition at line 39 of file pycc.cpp.
Function Documentation
define_pycc()
void define_pycc (py::module & m)
Definition at line 133 of file pycc.cpp.
References define_qcc_db(), define_qcc_io(), define_someQtThings(), import_pyccRuntime(), InitQApplication(), load_pluginWrappers(), CVLog::RegisterInstance(), and CVLog::Warning().
Referenced by PYBIND11_MODULE().
define_qcc_db()
void define_qcc_db (py::module & m)
Definition at line 70 of file qcc_db.cpp.
References ecvColor::RgbaTpl< Type >::a, ecvColor::RgbTpl< Type >::b, ecvColor::RgbaTpl< Type >::b, define_cc2DLabel(), define_ccBBox(), define_ccBox(), define_ccCameraSensor(), define_ccCircle(), define_ccColorScale(), define_ccColorScalesManager(), define_ccCone(), define_ccCylinder(), define_ccDisc(), define_ccDish(), define_ccDisplayTools(), define_ccDrawableObject(), define_ccGBLSensor(), define_ccGenericDisplayTools(), define_ccGenericMesh(), define_ccGenericPointCloud(), define_ccGenericPrimitive(), define_ccGLMatrix(), define_ccIndexedTransformation(), define_ccInteractor(), define_ccLog(), define_ccMesh(), define_ccNormalVectors(), define_ccObject(), define_ccPlane(), define_ccPointCloud(), define_ccPolyline(), define_ccProgressDialog(), define_ccQuadric(), define_ccRasterGrid(), define_ccScalarField(), define_ccSensor(), define_ccSphere(), define_ccSubMesh(), define_ccTorus(), define_ccViewportObject(), define_ccViewPortParameters(), define_ccWaveform(), ecvColor::RgbTpl< Type >::g, ecvColor::RgbaTpl< Type >::g, ecvColor::RgbTpl< Type >::r, and ecvColor::RgbaTpl< Type >::r.
Referenced by define_pycc().
define_qcc_io()
void define_qcc_io (py::module & m)
Definition at line 63 of file qcc_io.cpp.
References FileIOFilter::LoadParameters::alwaysDisplayLoadDialog, FileIOFilter::SaveParameters::alwaysDisplaySaveDialog, FileIOFilter::LoadParameters::autoComputeNormals, CC_FERR_NO_ERROR, FileIOFilter::LoadParameters::coordinatesShift, FileIOFilter::LoadParameters::coordinatesShiftEnabled, error(), filename, FileIOFilter::GetFilters(), FileIOFilter::LoadFromFile(), FileIOFilter::LoadParameters::parentWidget, FileIOFilter::SaveParameters::parentWidget, FileIOFilter::LoadParameters::preserveShiftOnSave, result, FileIOFilter::SaveToFile(), FileIOFilter::LoadParameters::sessionStart, FileIOFilter::LoadParameters::shiftHandlingMode, and ThrowForFileError().
Referenced by define_pycc().
define_scalar_type() [1/2]
template<typename T > std::enable_if<std::is_same<T, double>::value, void>::type define_scalar_type (py::module & m)
Definition at line 43 of file pycc.cpp.
define_scalar_type() [2/2]
template<typename T > std::enable_if<std::is_same<T, float>::value, void>::type define_scalar_type (py::module & m)
Definition at line 49 of file pycc.cpp.
define_someQtThings()
void define_someQtThings (py::module & m)
Definition at line 104 of file pycc.cpp.
References height, patch::to_string(), and width.
Referenced by define_pycc().
import_pyccRuntime()
void import_pyccRuntime (py::module & m)
Definition at line 88 of file pycc.cpp.
Referenced by define_pycc().
InitQApplication()
void InitQApplication ()
Definition at line 64 of file pycc.cpp.
References NULL.
Referenced by define_pycc().
load_pluginWrappers()
void load_pluginWrappers (py::module &)
Referenced by define_pycc().
PYBIND11_MODULE()
PYBIND11_MODULE (pycc , m)
Definition at line 189 of file pycc.cpp.
References define_pycc().