ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonConfig.h File Reference
PythonConfig.h File Reference
#include <QString>
#include <QtGlobal>
#include <QtCompat.h>
#include <memory>
#include <pybind11/pybind11.h>
Classes
struct Version
Simple representation of a SemVer version.
class PythonConfig
class PythonConfigPaths
Functions
constexpr Version PythonVersion (PY_MAJOR_VERSION, PY_MINOR_VERSION, PY_MICRO_VERSION)
Python Version the plugin was compiled against.
Function Documentation
PythonVersion()
constexpr Version PythonVersion (PY_MAJOR_VERSION , PY_MINOR_VERSION , PY_MICRO_VERSION) constexpr
Python Version the plugin was compiled against.
Referenced by PythonInterpreter::initialize(), Version::isCompatibleWithCompiledVersion(), and PythonConfig::validateAndDisplayErrors().