ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonPlugin.cpp File Reference
PythonPlugin.cpp File Reference
#include "PythonPlugin.h"
#include "AboutDialog.h"
#include "CodeEditor/PythonEditor.h"
#include "FileRunner.h"
#include "PackageManager.h"
#include "PythonActionLauncher.h"
#include "PythonRepl.h"
#include "PythonRuntimeSettings.h"
#include "Resources.h"
#include "Runtime/Runtime.h"
#include "Utilities.h"
#include <QDesktopServices>
#include <QMessageBox>
#include <QUrl>
#include <pybind11/pytypes.h>
#include <QDialog>
#include <QFile>
#include <QFileDialog>
#include <QSettings>
#include <algorithm>
#include <ecvCommandLineInterface.h>
Classes
struct PythonPluginCommand
struct PythonPluginCommand::Args
Macros
#define slots Q_SLOTS
#define signals Q_SIGNALS
Functions
static std::unique_ptr< QSettings > LoadSettings ()
static QIcon CreateQIconFromPyObject (const py::object &pyIcon)
template<typename T >
static bool SetIconFromPyObject (T *iconReceiver, const py::object &pyIcon)
Macro Definition Documentation
signals
#define signals Q_SIGNALS
Definition at line 26 of file PythonPlugin.cpp.
slots
#define slots Q_SLOTS
Definition at line 25 of file PythonPlugin.cpp.
Function Documentation
CreateQIconFromPyObject()
static QIcon CreateQIconFromPyObject (const py::object & pyIcon) static
The icon object can be:
str pointing to the file path of the icon's file
bytes the bytes of the icon
(bytes,str`) tuple of bytes and format name
Definition at line 554 of file PythonPlugin.cpp.
References bytes, format, and size.
Referenced by SetIconFromPyObject().
LoadSettings()
static std::unique_ptr<QSettings> LoadSettings () static
Definition at line 121 of file PythonPlugin.cpp.
Referenced by PythonPlugin::getActions(), and PythonPlugin::stop().
SetIconFromPyObject()
template<typename T > static bool SetIconFromPyObject (T * iconReceiver, const py::object & pyIcon) static
Definition at line 618 of file PythonPlugin.cpp.
References CreateQIconFromPyObject().