ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/PythonConfig.cpp File Reference
PythonConfig.cpp File Reference
#include "PythonConfig.h"
#include "Utilities.h"
#include <QApplication>
#include <QDebug>
#include <QDir>
#include <QMessageBox>
#include <QProcess>
#include <QVector>
#include <QtGlobal>
#include <QtCompat.h>
Classes
struct PyVenvCfg
Functions
static Version GetPythonExeVersion (QProcess &pythonProcess)
static QString PathToPythonExecutableInEnv (PythonConfig::Type envType, const QString &envRoot)
Function Documentation
GetPythonExeVersion()
static Version GetPythonExeVersion (QProcess & pythonProcess) static
Definition at line 75 of file PythonConfig.cpp.
References qtCompatCodecForName(), qtCompatSplitRefChar(), qtCompatStringRef(), e57::toString(), and QtCompatTextCodec::toUnicode().
Referenced by PythonConfig::getVersion().
PathToPythonExecutableInEnv()
static QString PathToPythonExecutableInEnv (PythonConfig::Type envType, const QString & envRoot) static
Definition at line 165 of file PythonConfig.cpp.
References PythonConfig::Bundled, PythonConfig::Conda, PythonConfig::System, and PythonConfig::Venv.
Referenced by PythonConfig::fromContainingEnvironment(), PythonConfig::initFromLocation(), and PythonConfig::preparePythonProcess().