ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/CodeEditor/PythonEditor.cpp File Reference
PythonEditor.cpp File Reference
#include "PythonEditor.h"
#include "CodeEditor.h"
#include "PythonInterpreter.h"
#include "ecvMainAppInterface.h"
#include <QtWidgets>
Functions
static QString RecentFilesKey ()
static QString FileKey ()
static QStringList readRecentFiles (QSettings &settings)
static void writeRecentFiles (const QStringList &files, QSettings &settings)
Function Documentation
FileKey()
static QString FileKey () static
Definition at line 23 of file PythonEditor.cpp.
Referenced by readRecentFiles(), and writeRecentFiles().
readRecentFiles()
static QStringList readRecentFiles (QSettings & settings) static
Definition at line 145 of file PythonEditor.cpp.
References count, FileKey(), RecentFilesKey(), result, and e57::toString().
Referenced by PythonEditor::updateRecentFileActions().
RecentFilesKey()
static QString RecentFilesKey () static
Definition at line 18 of file PythonEditor.cpp.
Referenced by readRecentFiles(), and writeRecentFiles().
writeRecentFiles()
static void writeRecentFiles (const QStringList & files, QSettings & settings) static
Definition at line 158 of file PythonEditor.cpp.
References count, FileKey(), and RecentFilesKey().