ACloudViewer: /root/ACloudViewer/plugins/core/Standard/q3DMASC/q3DMASCClassifier.cpp File Reference
q3DMASCClassifier.cpp File Reference
#include "q3DMASCClassifier.h"
#include "ScalarFieldWrappers.h"
#include "q3DMASCTools.h"
#include <CVLog.h>
#include <ecvDisplayTools.h>
#include <ecvPointCloud.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include "../../../core/IO/qPDALIO/include/LASFields.h"
#include <ecvMainAppInterface.h>
#include <QCoreApplication>
#include <QMessageBox>
#include <QProgressDialog>
#include <QtConcurrent>
#include "confusionmatrix.h"
#include "qTrain3DMASCDialog.h"
#include <unistd.h>
Functions
static IScalarFieldWrapper::Shared GetSource (const Feature::Source &fs, const ccPointCloud *cloud)
Function Documentation
GetSource()
static IScalarFieldWrapper::Shared GetSource (const Feature::Source & fs, const ccPointCloud * cloud) static
Definition at line 52 of file q3DMASCClassifier.cpp.
References masc::Feature::Source::Blue, ColorScalarFieldWrapper::Blue, masc::Feature::Source::DimX, DimScalarFieldWrapper::DimX, masc::Feature::Source::DimY, DimScalarFieldWrapper::DimY, masc::Feature::Source::DimZ, DimScalarFieldWrapper::DimZ, cloudViewer::PointCloudTpl< T >::getScalarField(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), masc::Feature::Source::Green, ColorScalarFieldWrapper::Green, masc::Feature::Source::name, masc::Feature::Source::Red, ColorScalarFieldWrapper::Red, masc::Feature::Source::ScalarField, masc::Feature::Source::type, and CVLog::Warning().
Referenced by masc::Classifier::classify(), masc::Classifier::evaluate(), and masc::Classifier::train().