ACloudViewer: /root/ACloudViewer/plugins/core/Standard/q3DMASC/q3DMASCDisclaimerDialog.h File Reference
q3DMASCDisclaimerDialog.h File Reference
#include <ui_classifyDisclaimerDlg.h>
#include <ui_trainDisclaimerDlg.h>
#include <ecvMainAppInterface.h>
#include <QMainWindow>
Classes
class TrainDisclaimerDialog
Dialog for displaying the 3DSMAC/UEB disclaimer.
class ClassifyDisclaimerDialog
Dialog for displaying the M3C2/UEB disclaimer.
Functions
static bool ShowTrainDisclaimer (ecvMainAppInterface *app)
static bool ShowClassifyDisclaimer (ecvMainAppInterface *app)
Variables
static bool s_trainDisclaimerAccepted = false
static bool s_classifyDisclaimerAccepted = false
Function Documentation
ShowClassifyDisclaimer()
static bool ShowClassifyDisclaimer (ecvMainAppInterface * app) static
Definition at line 92 of file q3DMASCDisclaimerDialog.h.
References ecvMainAppInterface::getMainWindow(), and s_classifyDisclaimerAccepted.
Referenced by q3DMASCPlugin::doClassifyAction(), and qCanupoPlugin::doClassifyAction().
ShowTrainDisclaimer()
static bool ShowTrainDisclaimer (ecvMainAppInterface * app) static
Definition at line 50 of file q3DMASCDisclaimerDialog.h.
References ecvMainAppInterface::getMainWindow(), and s_trainDisclaimerAccepted.
Referenced by q3DMASCPlugin::doTrainAction(), and qCanupoPlugin::doTrainAction().
Variable Documentation
s_classifyDisclaimerAccepted
bool s_classifyDisclaimerAccepted = false static
Definition at line 90 of file q3DMASCDisclaimerDialog.h.
Referenced by ShowClassifyDisclaimer().
s_trainDisclaimerAccepted
bool s_trainDisclaimerAccepted = false static
Definition at line 48 of file q3DMASCDisclaimerDialog.h.
Referenced by ShowTrainDisclaimer().