ACloudViewer: /root/ACloudViewer/plugins/core/Standard/q3DMASC/q3DMASCTools.cpp File Reference
q3DMASCTools.cpp File Reference
#include "q3DMASCTools.h"
#include "ContextBasedFeature.h"
#include "DualCloudFeature.h"
#include "NeighborhoodFeature.h"
#include "PointFeature.h"
#include "ecvMainAppInterface.h"
#include <FileIOFilter.h>
#include <ecvPointCloud.h>
#include <ecvScalarField.h>
#include "../../../core/IO/qPDALIO/include/LASFields.h"
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QMutex>
#include <QtCompat.h>
#include <assert.h>
Classes
struct FeaturesAndScales
Functions
bool CheckFeatureUnicity (std::vector< Feature::Shared > &rawFeatures, Feature::Shared feature)
static bool CreateFeaturesFromCommand (const QString &command, QString corePointsRole, int lineNumber, const Tools::NamedClouds &clouds, std::vector< Feature::Shared > &rawFeatures, std::vector< double > &scales)
static bool ReadScales (const QString &command, std::vector< double > &scales, int lineNumber)
static bool ReadCorePoints (const QString &command, const Tools::NamedClouds &clouds, masc::CorePoints &corePoints, int lineNumber)
static bool ReadCloud (const QString &command, Tools::NamedClouds &clouds, const QDir &defaultDir, int lineNumber, FileIOFilter::LoadParameters &loadParameters)
Function Documentation
CheckFeatureUnicity()
bool CheckFeatureUnicity (std::vector< Feature::Shared > & rawFeatures, Feature::Shared feature)
Definition at line 174 of file q3DMASCTools.cpp.
Referenced by CreateFeaturesFromCommand().
CreateFeaturesFromCommand()
static bool CreateFeaturesFromCommand (const QString & command, QString corePointsRole, int lineNumber, const Tools::NamedClouds & clouds, std::vector< Feature::Shared > & rawFeatures, std::vector< double > & scales) static
Definition at line 187 of file q3DMASCTools.cpp.
References CheckFeatureUnicity(), masc::Feature::ContextBasedFeature, masc::Feature::DIVIDE, masc::ContextBasedFeature::FromUpperString(), masc::DualCloudFeature::FromUpperString(), masc::NeighborhoodFeature::FromUpperString(), masc::PointFeature::FromUpperString(), masc::ContextBasedFeature::Invalid, masc::DualCloudFeature::Invalid, masc::NeighborhoodFeature::Invalid, masc::PointFeature::Invalid, masc::Feature::MEAN, masc::Feature::MEDIAN, masc::Feature::MINUS, masc::Feature::MODE, masc::Feature::MULTIPLY, masc::Feature::PLUS, masc::Feature::RANGE, masc::PointFeature::SF, masc::Feature::SKEW, masc::PointFeature::sourceSFIndex, masc::Feature::STD, masc::ContextBasedFeature::ToString(), and CVLog::Warning().
Referenced by masc::Tools::LoadFile().
ReadCloud()
static bool ReadCloud (const QString & command, Tools::NamedClouds & clouds, const QDir & defaultDir, int lineNumber, FileIOFilter::LoadParameters & loadParameters) static
Definition at line 695 of file q3DMASCTools.cpp.
References CC_FERR_NO_ERROR, ccHObject::detachChild(), error(), ccHObject::filterChildren(), ccHObject::getParent(), FileIOFilter::LoadFromFile(), CV_TYPES::POINT_CLOUD, ccObject::setName(), and CVLog::Warning().
Referenced by masc::Tools::LoadFile().
ReadCorePoints()
static bool ReadCorePoints (const QString & command, const Tools::NamedClouds & clouds, masc::CorePoints & corePoints, int lineNumber) static
Definition at line 633 of file q3DMASCTools.cpp.
References corePoints, masc::CorePoints::RANDOM, masc::CorePoints::SPATIAL, and CVLog::Warning().
Referenced by masc::Tools::LoadFile().
ReadScales()
static bool ReadScales (const QString & command, std::vector< double > & scales, int lineNumber) static
Definition at line 569 of file q3DMASCTools.cpp.
References CVLog::Warning().
Referenced by masc::Tools::LoadFile().