ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qAnimation/src/qAnimation.cpp File Reference
qAnimation.cpp File Reference
#include "qAnimation.h"
#include "qAnimationDlg.h"
#include <CVTools.h>
#include <ecv2DViewportObject.h>
#include <ecvDisplayTools.h>
#include <ecvMaterialSet.h>
#include <ecvMesh.h>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include <QMainWindow>
#include <QtGui>
Typedefs
typedef std::vector< cc2DViewportObject * > ViewPortList
typedef std::vector< ccMesh * > MeshList
Functions
static void GetSelectedObjects (const ccHObject::Container &selectedEntities, CV_CLASS_ENUM type, ccHObject::Container &targetObj)
static ViewPortList GetSelectedViewPorts (const ccHObject::Container &selectedEntities)
static MeshList GetSelectedMeshes (const ccHObject::Container &selectedEntities)
Typedef Documentation
MeshList
typedef std::vector<ccMesh *> MeshList
Definition at line 29 of file qAnimation.cpp.
ViewPortList
typedef std::vector<cc2DViewportObject *> ViewPortList
Definition at line 28 of file qAnimation.cpp.
Function Documentation
GetSelectedMeshes()
static MeshList GetSelectedMeshes (const ccHObject::Container & selectedEntities) static
Definition at line 66 of file qAnimation.cpp.
References GetSelectedObjects(), and CV_TYPES::MESH.
GetSelectedObjects()
static void GetSelectedObjects (const ccHObject::Container & selectedEntities, CV_CLASS_ENUM type, ccHObject::Container & targetObj) static
Definition at line 31 of file qAnimation.cpp.
References type.
Referenced by GetSelectedMeshes(), and GetSelectedViewPorts().
GetSelectedViewPorts()
static ViewPortList GetSelectedViewPorts (const ccHObject::Container & selectedEntities) static
Definition at line 50 of file qAnimation.cpp.
References GetSelectedObjects(), and CV_TYPES::VIEWPORT_2D_OBJECT.