ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qAnimation/src/qAnimationDlg.cpp File Reference
qAnimationDlg.cpp File Reference
#include "qAnimationDlg.h"
#include "ViewInterpolate.h"
#include <CVTools.h>
#include <ecv2DViewportObject.h>
#include <ecvDisplayTools.h>
#include <ecvMesh.h>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include <QApplication>
#include <QElapsedTimer>
#include <QFileDialog>
#include <QFileInfo>
#include <QMessageBox>
#include <QProgressDialog>
#include <QSettings>
#include <QtGui>
#include <iomanip>
#include <vector>
#include <algorithm>
#include <unistd.h>
Functions
static const QString s_stepDurationKey ("StepDurationSec")
static const QString s_stepEnabledKey ("StepEnabled")
QStringList getImageList (const QString &path)
Function Documentation
getImageList()
QStringList getImageList (const QString & path)
Definition at line 51 of file qAnimationDlg.cpp.
References data, and cloudViewer::t::geometry::path.
Referenced by qAnimationDlg::onBrowseTexturesButtonClicked(), qAnimationDlg::preview(), qAnimationDlg::qAnimationDlg(), and qAnimationDlg::render().
s_stepDurationKey()
static const QString s_stepDurationKey ("StepDurationSec") static
Referenced by qAnimationDlg::init(), and qAnimationDlg::onAccept().
s_stepEnabledKey()
static const QString s_stepEnabledKey ("StepEnabled") static
Referenced by qAnimationDlg::init(), and qAnimationDlg::onAccept().