ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qCanupo/src/qCanupoProcess.cpp File Reference
qCanupoProcess.cpp File Reference
#include "qCanupoProcess.h"
#include "qCanupoTools.h"
#include <ecvMainAppInterface.h>
#include <CloudSamplingTools.h>
#include <ReferenceCloud.h>
#include <ecvOctree.h>
#include <ecvOctreeProxy.h>
#include <ecvPointCloud.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <QApplication>
#include <QMessageBox>
#include <QStringList>
Functions
float RefinePointClassif (const Classifier &classifier, const float confidence, float &distToBoundary, ccPointCloud *cloud, ccOctree *octree, unsigned char octreeLevel, cloudViewer::GenericIndexedCloudPersist *corePoints, cloudViewer::DgmOctree *corePointsOctree, unsigned char coreOctreeLevel, unsigned coreIndex, PointCoordinateType largestRadius, const std::vector< int > &corePointClasses)
Variables
static const char CANUPO_PER_LEVEL_ADDITIONAL_SF_NAME [] = "CANUPO.(x-y)"
static const char s_canupoMSCMetaData [] = "CanupoMSCData"
Function Documentation
RefinePointClassif()
float RefinePointClassif (const Classifier & classifier, const float confidence, float & distToBoundary, ccPointCloud * cloud, ccOctree * octree, unsigned char octreeLevel, cloudViewer::GenericIndexedCloudPersist * corePoints, cloudViewer::DgmOctree * corePointsOctree, unsigned char coreOctreeLevel, unsigned coreIndex, PointCoordinateType largestRadius, const std::vector< int > & corePointClasses)
Definition at line 42 of file qCanupoProcess.cpp.
References Classifier::class1, Classifier::class2, corePoints, fabs(), cloudViewer::DgmOctree::findPointNeighbourhood(), ccPointCloud::getCurrentDisplayedScalarField(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::PointCloudTpl< T >::getPoint(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), cloudViewer::DgmOctree::getPointsInSphericalNeighbourhood(), cloudViewer::ScalarField::getValue(), max(), min(), octree, octreeLevel, and std::swap().
Referenced by qCanupoProcess::Classify().
Variable Documentation
CANUPO_PER_LEVEL_ADDITIONAL_SF_NAME
const char CANUPO_PER_LEVEL_ADDITIONAL_SF_NAME[] = "CANUPO.(x-y)" static
Definition at line 36 of file qCanupoProcess.cpp.
Referenced by qCanupoProcess::Classify().
s_canupoMSCMetaData
const char s_canupoMSCMetaData[] = "CanupoMSCData" static
Definition at line 39 of file qCanupoProcess.cpp.
Referenced by qCanupoProcess::Classify().