ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_db/qcc_db.cpp File Reference
qcc_db.cpp File Reference
#include <ecvAdvancedTypes.h>
#include <ecvColorTypes.h>
#include <pybind11/pybind11.h>
#include "../../cccorelib/src/wrappers.h"
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
Typedefs
template<class T >
using observer_ptr = std::unique_ptr< T, py::nodelete >
Functions
void define_ccDrawableObject (py::module &)
void define_ccScalarField (py::module &)
void define_ccObject (py::module &)
void define_ccGenericPointCloud (py::module &)
void define_ccPointCloud (py::module &)
void define_ccGenericDisplayTools (py::module &)
void define_ccDisplayTools (py::module &)
void define_ccGenericMesh (py::module &)
void define_ccMesh (py::module &)
void define_ccGBLSensor (py::module &)
void define_ccGenericPrimitive (py::module &)
void define_ccSphere (py::module &)
void define_ccGLMatrix (py::module &)
void define_ccIndexedTransformation (py::module &m)
void define_ccPlane (py::module &)
void define_ccTorus (py::module &)
void define_ccBox (py::module &)
void define_ccDish (py::module &)
void define_ccCone (py::module &)
void define_ccCylinder (py::module &)
void define_ccProgressDialog (py::module &)
void define_ccLog (py::module &)
void define_ccNormalVectors (py::module &)
void define_ccInteractor (py::module &)
void define_cc2DLabel (py::module &)
void define_ccViewPortParameters (py::module &)
void define_ccViewportObject (py::module &)
void define_ccBBox (py::module &)
void define_ccSensor (py::module &m)
void define_ccCameraSensor (py::module &)
void define_ccColorScale (py::module &)
void define_ccColorScalesManager (py::module &)
void define_ccWaveform (py::module &m)
void define_ccSubMesh (py::module &m)
void define_ccRasterGrid (py::module &m)
void define_ccQuadric (py::module &m)
void define_ccPolyline (py::module &m)
void define_ccCircle (py::module &m)
void define_ccDisc (py::module &m)
void define_qcc_db (py::module &m)
Typedef Documentation
observer_ptr
template<class T > using observer_ptr = std::unique_ptr<T, py::nodelete>
Definition at line 63 of file qcc_db.cpp.
Function Documentation
define_cc2DLabel()
void define_cc2DLabel (py::module & m)
Definition at line 21 of file cc2DLabel.cpp.
References cc2DLabel::addPickedPoint(), cc2DLabel::clear(), cc2DLabel::PickedPoint::cloud, cc2DLabel::PickedPoint::cloudOrVertices(), cc2DLabel::displayPointLegend(), cc2DLabel::PickedPoint::entity(), cc2DLabel::PickedPoint::entityCenterPoint, cc2DLabel::getLabelContent(), cc2DLabel::getPickedPoint(), cc2DLabel::PickedPoint::getPointPosition(), cc2DLabel::getRawName(), cc2DLabel::getTitle(), cc2DLabel::PickedPoint::getUniqueID(), cc2DLabel::PickedPoint::index, cc2DLabel::isCollapsed(), cc2DLabel::isDisplayedIn2D(), cc2DLabel::isPointLegendDisplayed(), cc2DLabel::PickedPoint::itemTitle(), cc2DLabel::PickedPoint::mesh, cc2DLabel::PickedPoint::pos2D, cc2DLabel::PickedPoint::prefix(), cc2DLabel::setCollapsed(), cc2DLabel::setDisplayedIn2D(), cc2DLabel::setPosition(), cc2DLabel::setRelativeMarkerScale(), cc2DLabel::size(), and cc2DLabel::PickedPoint::uv.
Referenced by define_qcc_db().
define_ccBBox()
void define_ccBBox (py::module & m)
Definition at line 18 of file ccBBox.cpp.
References ccBBox::draw().
Referenced by define_qcc_db().
define_ccBox()
void define_ccBox (py::module & m)
Definition at line 17 of file ccBox.cpp.
References ccBox::getDimensions(), and ccBox::setDimensions().
Referenced by define_qcc_db().
define_ccCameraSensor()
void define_ccCameraSensor (py::module & m)
Definition at line 20 of file ccCameraSensor.cpp.
References ccCameraSensor::IntrinsicParameters::arrayHeight, ccCameraSensor::IntrinsicParameters::arrayWidth, ccCameraSensor::FrustumInformation::center, data, ccCameraSensor::FrustumInformation::drawFrustum, ccCameraSensor::FrustumInformation::drawSidePlanes, ccCameraSensor::FrustumInformation::frustumCorners, ccCameraSensor::FrustumInformation::frustumHull, ccCameraSensor::getHorizFocal_pix(), ccCameraSensor::getIntrinsicParameters(), ccCameraSensor::IntrinsicParameters::GetKinectDefaults(), ccCameraSensor::LensDistortionParameters::getModel(), ccCameraSensor::getVerticalFov_rad(), ccCameraSensor::IntrinsicParameters::horizFocal_pix(), ccCameraSensor::FrustumInformation::initFrustumCorners(), ccCameraSensor::FrustumInformation::initFrustumHull(), ccCameraSensor::FrustumInformation::isComputed, ccCameraSensor::RadialDistortionParameters::k1, ccCameraSensor::RadialDistortionParameters::k2, ccCameraSensor::ExtendedRadialDistortionParameters::k3, ccCameraSensor::setIntrinsicParameters(), ccCameraSensor::setVertFocal_pix(), ccCameraSensor::setVerticalFov_rad(), ccCameraSensor::IntrinsicParameters::skew, ccCameraSensor::IntrinsicParameters::vertFocal_pix, ccCameraSensor::IntrinsicParameters::vFOV_rad, x, y, z, ccCameraSensor::IntrinsicParameters::zFar_mm, and ccCameraSensor::IntrinsicParameters::zNear_mm.
Referenced by define_qcc_db().
define_ccCircle()
void define_ccCircle (py::module & m)
Definition at line 21 of file ccCircle.cpp.
References ccCircle::clone(), ccCircle::getRadius(), ccCircle::getResolution(), ccUniqueIDGenerator::InvalidUniqueID, ccCircle::setRadius(), and ccCircle::setResolution().
Referenced by define_qcc_db().
define_ccColorScale()
void define_ccColorScale (py::module & m)
Definition at line 21 of file ccColorScale.cpp.
References ccColorScale::clear(), ccColorScale::customLabels(), ccColorScale::DEFAULT_STEPS, ccColorScale::generateNewUuid(), ccColorScaleElement::getColor(), ccColorScale::getColorByIndex(), ccColorScale::getColorByRelativePos(), ccColorScale::getColorByValue(), ccColorScale::getName(), ccColorScaleElement::getRelativePos(), ccColorScale::getRelativePosition(), ccColorScale::getUuid(), ccColorScale::insert(), ccColorScale::isLocked(), ccColorScale::isRelative(), ccColorScaleElement::IsSmaller(), ccColorScale::LoadFromXML(), ccColorScale::MAX_STEPS, ccColorScale::MIN_STEPS, ccColorScale::remove(), ccColorScale::saveAsXML(), ccColorScale::setAbsolute(), ccColorScaleElement::setColor(), ccColorScale::setCustomLabels(), ccColorScale::setLocked(), ccColorScale::setName(), ccColorScale::setRelative(), ccColorScaleElement::setRelativePos(), ccColorScale::setUuid(), ccColorScale::step(), ccColorScale::stepCount(), ccColorScale::Label::text, ccColorScale::update(), and ccColorScale::Label::value.
Referenced by define_qcc_db().
define_ccColorScalesManager()
void define_ccColorScalesManager (py::module & m)
Definition at line 22 of file ccColorScalesManager.cpp.
References ccColorScalesManager::addScale(), ccColorScalesManager::fromPersistentSettings(), ccColorScalesManager::getDefaultScale(), ccColorScalesManager::GetDefaultScale(), ccColorScalesManager::GetDefaultScaleUUID(), ccColorScalesManager::getScale(), ccColorScalesManager::GetUniqueInstance(), ccColorScalesManager::ReleaseUniqueInstance(), ccColorScalesManager::removeScale(), and ccColorScalesManager::toPersistentSettings().
Referenced by define_qcc_db().
define_ccCone()
void define_ccCone (py::module & m)
Definition at line 19 of file ccCone.cpp.
References ccCone::DEFAULT_DRAWING_PRECISION, ccCone::getBottomCenter(), ccCone::getBottomRadius(), ccCone::getHeight(), ccCone::getLargeCenter(), ccCone::getLargeRadius(), ccCone::getSmallCenter(), ccCone::getSmallRadius(), ccCone::getTopCenter(), ccCone::getTopRadius(), ccCone::isSnoutMode(), ccCone::setBottomRadius(), ccCone::setHeight(), and ccCone::setTopRadius().
Referenced by define_qcc_db().
define_ccCylinder()
void define_ccCylinder (py::module & m)
Definition at line 20 of file ccCylinder.cpp.
References ccCylinder::DEFAULT_DRAWING_PRECISION, ccCone::getBottomRadius(), and ccCylinder::setBottomRadius().
Referenced by define_qcc_db().
define_ccDisc()
void define_ccDisc (py::module & m)
Definition at line 21 of file ccDisc.cpp.
References ccDisc::clone(), ccDisc::DEFAULT_DRAWING_PRECISION, ccDisc::getRadius(), and ccDisc::setRadius().
Referenced by define_qcc_db().
define_ccDish()
void define_ccDish (py::module & m)
Definition at line 19 of file ccDish.cpp.
References ccDish::DEFAULT_DRAWING_PRECISION.
Referenced by define_qcc_db().
define_ccDisplayTools()
void define_ccDisplayTools (py::module & m)
Definition at line 21 of file ccDisplayTools.cpp.
References ecvDisplayTools::AddToOwnDB(), ecvGenericDisplayTools::ALIGN_DEFAULT, color, ecvDisplayTools::ComputeActualPixelSize(), ecvColor::defaultLabelBkgColor(), ecvDisplayTools::Deprecate3DLayer(), ecvDisplayTools::Display3DLabel(), ecvDisplayTools::DisplayNewMessage(), ecvDisplayTools::DisplayOverlayEntities(), ecvDisplayTools::DisplayText(), ecvDisplayTools::DoResize(), ecvDisplayTools::GetContext(), ecvDisplayTools::GetDevicePixelRatio(), ecvDisplayTools::GetFontPointSize(), ecvDisplayTools::GetFov(), ecvDisplayTools::GetGLCameraParameters(), ecvDisplayTools::GetInteractionMode(), ecvDisplayTools::GetLabelDisplayFont(), ecvDisplayTools::GetLabelFontPointSize(), ecvDisplayTools::GetMainWindow(), ecvDisplayTools::GetOwnDB(), ecvGenericDisplayTools::GetPerspectiveState(), ecvDisplayTools::GetPickingMode(), ecvDisplayTools::GetPickingRadius(), ecvDisplayTools::GetPivotVisibility(), ecvDisplayTools::GetSceneDB(), ecvDisplayTools::GetScreenSize(), ecvDisplayTools::GetTextDisplayFont(), ecvDisplayTools::GetViewportParameters(), ecvDisplayTools::GetVisibleObjectsBB(), ecvDisplayTools::InvalidateViewport(), ecvDisplayTools::InvalidateVisualization(), ecvDisplayTools::IsPickingModeLocked(), ecvDisplayTools::IsRectangularPickingAllowed(), ecvDisplayTools::LockPickingMode(), ecvDisplayTools::MoveCamera(), ecvDisplayTools::ObjectPerspectiveEnabled(), ecvDisplayTools::RedrawDisplay(), ecvDisplayTools::RefreshDisplay(), ecvDisplayTools::Remove3DLabel(), ecvDisplayTools::RemoveAllWidgets(), ecvDisplayTools::RemoveFromOwnDB(), ecvDisplayTools::RenderText(), ecvDisplayTools::RenderToFile(), ecvDisplayTools::SetCameraPos(), ecvDisplayTools::SetFov(), ecvDisplayTools::SetInteractionMode(), ecvDisplayTools::SetLineWidth(), ecvDisplayTools::SetPerspectiveState(), ecvDisplayTools::SetPickingMode(), ecvDisplayTools::SetPickingRadius(), ecvDisplayTools::SetPivotPoint(), ecvDisplayTools::SetPivotVisibility(), ecvDisplayTools::SetPointSize(), ecvDisplayTools::SetRectangularPickingAllowed(), ecvDisplayTools::SetSceneDB(), ecvDisplayTools::SetupProjectiveViewport(), ecvDisplayTools::SetView(), ecvDisplayTools::SetViewportParameters(), ecvDisplayTools::ShowPivotSymbol(), ecvDisplayTools::ToBeRefreshed(), ecvDisplayTools::ToCenteredGLCoordinates(), ecvDisplayTools::UpdateConstellationCenterAndZoom(), ecvDisplayTools::ViewerPerspectiveEnabled(), x, y, and z.
Referenced by define_qcc_db().
define_ccDrawableObject()
void define_ccDrawableObject (py::module & m)
Definition at line 18 of file ccDrawableObject.cpp.
References ccDrawableObject::addClipPlanes(), ccDrawableObject::colorsShown(), ccDrawableObject::draw(), ccDrawableObject::enableGLTransformation(), ccDrawableObject::getGLTransformation(), ccDrawableObject::getTempColor(), ccDrawableObject::hasColors(), ccDrawableObject::hasDisplayedScalarField(), ccDrawableObject::hasNormals(), ccDrawableObject::hasScalarFields(), ccDrawableObject::isColorOverridden(), ccDrawableObject::isGLTransEnabled(), ccDrawableObject::isSelected(), ccDrawableObject::isVisibilityLocked(), ccDrawableObject::isVisible(), ccDrawableObject::lockVisibility(), ccDrawableObject::nameShownIn3D(), ccDrawableObject::normalsShown(), ccDrawableObject::removeAllClipPlanes(), ccDrawableObject::resetGLTransformation(), ccDrawableObject::rotateGL(), ccDrawableObject::setGLTransformation(), ccDrawableObject::setSelected(), ccDrawableObject::setTempColor(), ccDrawableObject::setVisible(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccDrawableObject::showNameIn3D(), ccDrawableObject::showNormals(), ccDrawableObject::showSF(), ccDrawableObject::toggleClipPlanes(), ccDrawableObject::toggleColors(), ccDrawableObject::toggleMaterials(), ccDrawableObject::toggleNormals(), ccDrawableObject::toggleSF(), ccDrawableObject::toggleShowName(), ccDrawableObject::toggleVisibility(), and ccDrawableObject::translateGL().
Referenced by define_qcc_db().
define_ccGBLSensor()
void define_ccGBLSensor (py::module & m)
Definition at line 18 of file ccGBLSensor.cpp.
References ccGBLSensor::computeAutoParameters(), ccGBLSensor::GetErrorString(), ccGBLSensor::getMaxPitch(), ccGBLSensor::getMaxYaw(), ccGBLSensor::getMinPitch(), ccGBLSensor::getMinYaw(), ccGBLSensor::getPitchStep(), ccGBLSensor::getRotationOrder(), ccGBLSensor::getSensorRange(), ccGBLSensor::getUncertainty(), ccGBLSensor::getYawStep(), ccGBLSensor::pitchIsShifted(), ccGBLSensor::setPitchRange(), ccGBLSensor::setPitchStep(), ccGBLSensor::setRotationOrder(), ccGBLSensor::setSensorRange(), ccGBLSensor::setUncertainty(), ccGBLSensor::setYawRange(), ccGBLSensor::setYawStep(), and ccGBLSensor::yawIsShifted().
Referenced by define_qcc_db().
define_ccGenericDisplayTools()
void define_ccGenericDisplayTools (py::module & m)
Definition at line 22 of file ccGenericDisplayTools.cpp.
References ccGLCameraParameters::fov_deg, ccGLCameraParameters::modelViewMat, ccGLCameraParameters::perspective, ccGLCameraParameters::pixelSize, ccGLCameraParameters::project(), ccGLCameraParameters::projectionMat, and ccGLCameraParameters::unproject().
Referenced by define_qcc_db().
define_ccGenericMesh()
void define_ccGenericMesh (py::module & m)
Definition at line 19 of file ccGenericMesh.cpp.
References ccGenericMesh::capacity(), ccGenericMesh::getAssociatedCloud(), ccGenericMesh::getMaterialSet(), ccGenericMesh::getTexCoordinatesTable(), ccGenericMesh::getTriangleMtlIndex(), ccGenericMesh::hasMaterials(), ccGenericMesh::hasPerTriangleTexCoordIndexes(), ccGenericMesh::hasTextures(), ccGenericMesh::hasTriNormals(), and ccGenericMesh::refreshBB().
Referenced by define_qcc_db().
define_ccGenericPointCloud()
void define_ccGenericPointCloud (py::module & m)
Definition at line 17 of file ccGenericPointCloud.cpp.
References ccGenericPointCloud::clear(), and ccGenericPointCloud::clone().
Referenced by define_qcc_db().
define_ccGenericPrimitive()
void define_ccGenericPrimitive (py::module & m)
Definition at line 21 of file ccGenericPrimitive.cpp.
References ccGenericPrimitive::getDrawingPrecision(), ccGenericPrimitive::getTransformation(), ccGenericPrimitive::getTypeName(), ccGenericPrimitive::hasDrawingPrecision(), ccGenericPrimitive::setColor(), and ccGenericPrimitive::setDrawingPrecision().
Referenced by define_qcc_db().
define_ccGLMatrix()
void define_ccGLMatrix (py::module & m)
Definition at line 121 of file ccGLMatrix.cpp.
Referenced by define_qcc_db().
define_ccIndexedTransformation()
void define_ccIndexedTransformation (py::module & m)
Definition at line 19 of file ccIndexedTransformation.cpp.
References ccIndexedTransformation::getIndex(), ccIndexedTransformation::Interpolate(), ccIndexedTransformation::inverse(), ccIndexedTransformation::setIndex(), and ccIndexedTransformation::transposed().
Referenced by define_qcc_db().
define_ccInteractor()
void define_ccInteractor (py::module & m)
Definition at line 17 of file ccInteractor.cpp.
References ccInteractor::acceptClick(), ccInteractor::move2D(), and ccInteractor::move3D().
Referenced by define_qcc_db().
define_ccLog()
void define_ccLog (py::module & m)
Definition at line 20 of file ccLog.cpp.
References CVLog::Error(), CVLog::LogMessage(), CVLog::Print(), CVLog::TheInstance(), and CVLog::Warning().
Referenced by define_qcc_db().
define_ccMesh()
void define_ccMesh (py::module & m)
Definition at line 20 of file ccMesh.cpp.
References ccMesh::addTriangle(), ccMesh::addTriangles(), and ccMesh::setAssociatedCloud().
Referenced by define_qcc_db().
define_ccNormalVectors()
void define_ccNormalVectors (py::module & m)
Definition at line 19 of file ccNormalVectors.cpp.
References ccNormalVectors::GetNormal(), ccNormalVectors::GetNormIndex(), ccNormalVectors::GetNumberOfVectors(), ccNormalVectors::GetUniqueInstance(), and ccNormalVectors::ReleaseUniqueInstance().
Referenced by define_qcc_db().
define_ccObject()
void define_ccObject (py::module & m)
Definition at line 77 of file ccObject.cpp.
References ccHObject::applyGLTransformation_recursive(), castToFakeOwnedObject(), ccShiftedObject::copyGlobalShiftAndScale(), data, ccHObject::detachAllChildren(), ccHObject::detachChild(), ccHObject::find(), ccHObject::getChildCountRecursive(), ccHObject::getChildIndex(), ccHObject::getChildrenNumber(), ccHObject::getDisplayBB_recursive(), ccHObject::getFirstChild(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccHObject::getGLTransformationHistory(), ccHObject::getIndex(), ccHObject::getLastChild(), ccObject::getMetaData(), ccObject::getName(), ccHObject::getParent(), ccObject::getUniqueID(), ccObject::hasMetaData(), ccHObject::isAncestorOf(), ccObject::isCustom(), ccObject::isEnabled(), ccHObject::isGroup(), ccObject::isHierarchy(), ccObject::isLeaf(), ccObject::isLocked(), ccShiftedObject::isShifted(), ccHObject::notifyGeometryUpdate(), ccObject::removeMetaData(), removePatient(), ccHObject::resetGLTransformationHistory(), setDeletable(), ccObject::setEnabled(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccHObject::setGLTransformationHistory(), ccObject::setLocked(), ccObject::setMetaData(), ccObject::setName(), ccHObject::swapChildren(), and ccObject::toggleActivation().
Referenced by define_qcc_db().
define_ccPlane()
void define_ccPlane (py::module & m)
Definition at line 20 of file ccPlane.cpp.
References ccPlane::Fit(), ccPlane::flip(), ccPlane::getCenter(), ccPlanarEntityInterface::getNormal(), ccPlane::getXWidth(), ccPlane::getYWidth(), ccPlanarEntityInterface::normalVectorIsShown(), ccPlane::setXWidth(), ccPlane::setYWidth(), and ccPlanarEntityInterface::showNormalVector().
Referenced by define_qcc_db().
define_ccPointCloud()
void define_ccPointCloud (py::module & m)
Definition at line 36 of file ccPointCloud.cpp.
References a, ccPointCloud::addNorm(), PyCC::addPointsFromArrays(), ccPointCloud::colorize(), colors, ccPointCloud::computeNormalsWithGrids(), ccPointCloud::computeNormalsWithOctree(), ccPointCloud::crop2D(), DEFINE_POINTCLOUDTPL, ccPointCloud::getCurrentDisplayedScalarField(), ccPointCloud::getCurrentDisplayedScalarFieldIndex(), ccPointCloud::orientNormalsTowardViewPoint(), ccPointCloud::orientNormalsWithFM(), ccPointCloud::orientNormalsWithMST(), ccPointCloud::reserveTheNormsTable(), ccPointCloud::reserveThePointsTable(), ccPointCloud::resizeTheNormsTable(), ccPointCloud::setCurrentDisplayedScalarField(), ccPointCloud::setPointNormal(), ccGenericPointCloud::setPointSize(), ccPointCloud::sfColorScaleShown(), ccPointCloud::showSFColorsScale(), ccPointCloud::shrinkToFit(), size, and patch::to_string().
Referenced by define_qcc_db().
define_ccPolyline()
void define_ccPolyline (py::module & m)
Definition at line 21 of file ccPolyline.cpp.
References ccPolyline::computeLength(), ccPolyline::getColor(), ccPolyline::getVertexMarkerWidth(), ccPolyline::getWidth(), ccPolyline::importParametersFrom(), ccPolyline::is2DMode(), ccPolyline::samplePoints(), ccPolyline::segmentCount(), ccPolyline::set2DMode(), ccPolyline::setColor(), ccPolyline::setForeground(), ccPolyline::setVertexMarkerWidth(), ccPolyline::setWidth(), ccPolyline::showArrow(), ccPolyline::showVertices(), ccPolyline::smoothChaikin(), and ccPolyline::verticesShown().
Referenced by define_qcc_db().
define_ccProgressDialog()
void define_ccProgressDialog (py::module & m)
Definition at line 20 of file ccProgressDialog.cpp.
References ecvProgressDialog::setInfo(), and ecvProgressDialog::setMethodTitle().
Referenced by define_qcc_db().
define_ccQuadric()
void define_ccQuadric (py::module & m)
Definition at line 21 of file ccQuadric.cpp.
References ccQuadric::DEFAULT_DRAWING_PRECISION, ccQuadric::Fit(), for(), ccQuadric::getEquationCoefs(), ccQuadric::getEquationDims(), ccQuadric::getEquationString(), ccQuadric::getMaxCorner(), ccQuadric::getMinCorner(), name, and ccQuadric::projectOnQuadric().
Referenced by define_qcc_db().
define_ccRasterGrid()
void define_ccRasterGrid (py::module & m)
Definition at line 21 of file ccRasterGrid.cpp.
References ccRasterCell::color, ccRasterGrid::computeCellCenter(), ccRasterGrid::computeCellPos(), ccRasterGrid::ComputeGridSize(), ccRasterGrid::convertToCloud(), ccRasterGrid::fillEmptyCells(), ccRasterGrid::fillWith(), ccRasterGrid::GetDefaultFieldName(), ccRasterGrid::gridStep, ccRasterCell::h, ccRasterGrid::hasColors, ccRasterGrid::height, ccRasterGrid::isValid(), ccRasterCell::maxHeight, ccRasterGrid::maxHeight, ccRasterGrid::meanHeight, ccRasterGrid::minCorner, ccRasterCell::minHeight, ccRasterGrid::minHeight, ccRasterCell::nbPoints, ccRasterGrid::nonEmptyCellCount, ccRasterCell::pointIndex, ccRasterGrid::reset(), ccRasterGrid::setValid(), ccRasterGrid::updateCellStats(), ccRasterGrid::updateNonEmptyCellCount(), ccRasterGrid::valid, ccRasterGrid::validCellCount, and ccRasterGrid::width.
Referenced by define_qcc_db().
define_ccScalarField()
void define_ccScalarField (py::module & m)
Definition at line 19 of file ccScalarField.cpp.
References ccScalarField::alwaysShowZero(), ccScalarField::areNaNValuesShownInGrey(), ccScalarField::displayRange(), ccScalarField::getColor(), ccScalarField::getColorRampSteps(), ccScalarField::getColorScale(), ccScalarField::getGlobalShift(), ccScalarField::getHistogram(), ccScalarField::getModificationFlag(), ccScalarField::getValueColor(), ccScalarField::importParametersFrom(), ccScalarField::Range::inbound(), ccScalarField::Range::isInbound(), ccScalarField::Range::isInRange(), ccScalarField::isZeroAlwaysShown(), ccScalarField::logSaturationRange(), ccScalarField::logScale(), ccScalarField::Range::max(), ccScalarField::Range::maxRange(), ccScalarField::mayHaveHiddenValues(), ccScalarField::Range::min(), ccScalarField::Range::range(), ccScalarField::saturationRange(), ccScalarField::Range::setBounds(), ccScalarField::setColorRampSteps(), ccScalarField::setColorScale(), ccScalarField::setGlobalShift(), ccScalarField::setLogScale(), ccScalarField::setMaxDisplayed(), ccScalarField::setMinDisplayed(), ccScalarField::setModificationFlag(), ccScalarField::setSaturationStart(), ccScalarField::setSaturationStop(), ccScalarField::Range::setStart(), ccScalarField::Range::setStop(), ccScalarField::setSymmetricalScale(), ccScalarField::showNaNValuesInGrey(), ccScalarField::Range::start(), ccScalarField::Range::stop(), and ccScalarField::symmetricalScale().
Referenced by define_qcc_db().
define_ccSensor()
void define_ccSensor (py::module & m)
Definition at line 19 of file ccSensor.cpp.
References ccSensor::addPosition(), ccSensor::applyViewport(), ccSensor::checkVisibility(), ccSensor::getAbsoluteTransformation(), ccSensor::getActiveAbsoluteCenter(), ccSensor::getActiveAbsoluteRotation(), ccSensor::getActiveAbsoluteTransformation(), ccSensor::getActiveIndex(), ccSensor::getGraphicScale(), ccSensor::getRigidTransformation(), GROUND_BASED_LIDAR, ccSensor::setActiveIndex(), ccSensor::setGraphicScale(), ccSensor::setRigidTransformation(), and UNKNOWN_SENSOR.
Referenced by define_qcc_db().
define_ccSphere()
void define_ccSphere (py::module & m)
Definition at line 19 of file ccSphere.cpp.
References ccSphere::getRadius(), and ccSphere::setRadius().
Referenced by define_qcc_db().
define_ccSubMesh()
void define_ccSubMesh (py::module & m)
Definition at line 20 of file ccSubMesh.cpp.
References ccSubMesh::addTriangleIndex(), ccSubMesh::clear(), ccSubMesh::forwardIterator(), ccSubMesh::getAssociatedMesh(), ccSubMesh::getCurrentTriGlobalIndex(), ccSubMesh::getTriGlobalIndex(), ccSubMesh::reserve(), ccSubMesh::resize(), ccSubMesh::setAssociatedMesh(), and ccSubMesh::setTriangleIndex().
Referenced by define_qcc_db().
define_ccTorus()
void define_ccTorus (py::module & m)
Definition at line 19 of file ccTorus.cpp.
References ccTorus::DEFAULT_DRAWING_PRECISION, and M_PI.
Referenced by define_qcc_db().
define_ccViewportObject()
void define_ccViewportObject (py::module & m)
Definition at line 20 of file ccViewportObject.cpp.
References cc2DViewportObject::getParameters(), and cc2DViewportObject::setParameters().
Referenced by define_qcc_db().
define_ccViewPortParameters()
void define_ccViewPortParameters (py::module & m)
Definition at line 21 of file ccViewPortParameters.cpp.
References ecvViewportParameters::cameraAspectRatio, ecvViewportParameters::computeDistanceToHalfWidthRatio(), ecvViewportParameters::computeDistanceToWidthRatio(), ecvViewportParameters::computePixelSize(), ecvViewportParameters::computeViewMatrix(), ecvViewportParameters::computeWidthAtFocalDist(), ecvViewportParameters::defaultLineWidth, ecvViewportParameters::defaultPointSize, ecvViewportParameters::fov_deg, ecvViewportParameters::getCameraCenter(), ecvViewportParameters::getFocalDistance(), ecvViewportParameters::getPivotPoint(), ecvViewportParameters::getRotationCenter(), ecvViewportParameters::getUpDir(), ecvViewportParameters::getViewDir(), ecvViewportParameters::objectCenteredView, ecvViewportParameters::perspectiveView, ecvViewportParameters::setCameraCenter(), ecvViewportParameters::setFocalDistance(), ecvViewportParameters::setPivotPoint(), ecvViewportParameters::viewMat, ecvViewportParameters::zFar, ecvViewportParameters::zNear, and ecvViewportParameters::zNearCoef.
Referenced by define_qcc_db().
define_ccWaveform()
void define_ccWaveform (py::module & m)
Definition at line 19 of file ccWaveform.cpp.
References ccWaveform::applyRigidTransformation(), ccWaveform::beamDir(), ccWaveformProxy::beamDir(), WaveformDescriptor::bitsPerSample, ccWaveform::byteCount(), ccWaveformProxy::byteCount(), ccWaveformProxy::data(), ccWaveform::dataOffset(), ccWaveformProxy::descriptor(), ccWaveform::descriptorID(), ccWaveformProxy::descriptorID(), WaveformDescriptor::digitizerGain, WaveformDescriptor::digitizerOffset, ccWaveform::echoTime_ps(), ccWaveformProxy::echoTime_ps(), ccWaveformProxy::getRawSample(), ccWaveform::getRawSample(), ccWaveformProxy::getSamplePos(), ccWaveform::getSamplePos(), ccWaveformProxy::isValid(), WaveformDescriptor::numberOfSamples, ccWaveform::returnIndex(), WaveformDescriptor::samplingRate_ps, ccWaveform::setBeamDir(), ccWaveform::setDataDescription(), ccWaveform::setDataOffset(), ccWaveform::setDescriptorID(), ccWaveform::setEchoTime_ps(), ccWaveform::setReturnIndex(), ccWaveformProxy::toASCII(), ccWaveform::toASCII(), ccWaveform::ToASCII(), and ccWaveformProxy::waveform().
Referenced by define_qcc_db().
define_qcc_db()
void define_qcc_db (py::module & m)
Definition at line 70 of file qcc_db.cpp.
References ecvColor::RgbaTpl< Type >::a, ecvColor::RgbTpl< Type >::b, ecvColor::RgbaTpl< Type >::b, define_cc2DLabel(), define_ccBBox(), define_ccBox(), define_ccCameraSensor(), define_ccCircle(), define_ccColorScale(), define_ccColorScalesManager(), define_ccCone(), define_ccCylinder(), define_ccDisc(), define_ccDish(), define_ccDisplayTools(), define_ccDrawableObject(), define_ccGBLSensor(), define_ccGenericDisplayTools(), define_ccGenericMesh(), define_ccGenericPointCloud(), define_ccGenericPrimitive(), define_ccGLMatrix(), define_ccIndexedTransformation(), define_ccInteractor(), define_ccLog(), define_ccMesh(), define_ccNormalVectors(), define_ccObject(), define_ccPlane(), define_ccPointCloud(), define_ccPolyline(), define_ccProgressDialog(), define_ccQuadric(), define_ccRasterGrid(), define_ccScalarField(), define_ccSensor(), define_ccSphere(), define_ccSubMesh(), define_ccTorus(), define_ccViewportObject(), define_ccViewPortParameters(), define_ccWaveform(), ecvColor::RgbTpl< Type >::g, ecvColor::RgbaTpl< Type >::g, ecvColor::RgbTpl< Type >::r, and ecvColor::RgbaTpl< Type >::r.
Referenced by define_pycc().