ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/pycc/src/qcc_io/qcc_io.cpp File Reference
qcc_io.cpp File Reference
#include "../casters.h"
#include <FileIO.h>
#include <FileIOFilter.h>
#include <QFileInfo>
#include <QWidget>
Functions
static void ThrowForFileError (CC_FILE_ERROR error)
void define_qcc_io (py::module &m)
Function Documentation
define_qcc_io()
void define_qcc_io (py::module & m)
Definition at line 63 of file qcc_io.cpp.
References FileIOFilter::LoadParameters::alwaysDisplayLoadDialog, FileIOFilter::SaveParameters::alwaysDisplaySaveDialog, FileIOFilter::LoadParameters::autoComputeNormals, CC_FERR_NO_ERROR, FileIOFilter::LoadParameters::coordinatesShift, FileIOFilter::LoadParameters::coordinatesShiftEnabled, error(), FileIOFilter::GetFilters(), FileIOFilter::LoadFromFile(), FileIOFilter::LoadParameters::parentWidget, FileIOFilter::SaveParameters::parentWidget, FileIOFilter::LoadParameters::preserveShiftOnSave, result, FileIOFilter::SaveToFile(), FileIOFilter::LoadParameters::sessionStart, FileIOFilter::LoadParameters::shiftHandlingMode, and ThrowForFileError().
Referenced by define_pycc().
ThrowForFileError()
static void ThrowForFileError (CC_FILE_ERROR error) static
Definition at line 18 of file qcc_io.cpp.
References CC_FERR_BAD_ARGUMENT, CC_FERR_BAD_ENTITY_TYPE, CC_FERR_BROKEN_DEPENDENCY_ERROR, CC_FERR_CANCELED_BY_USER, CC_FERR_CONSOLE_ERROR, CC_FERR_FILE_WAS_WRITTEN_BY_UNKNOWN_PLUGIN, CC_FERR_INTERNAL, CC_FERR_MALFORMED_FILE, CC_FERR_NO_ERROR, CC_FERR_NO_LOAD, CC_FERR_NO_SAVE, CC_FERR_NOT_ENOUGH_MEMORY, CC_FERR_NOT_IMPLEMENTED, CC_FERR_READING, CC_FERR_THIRD_PARTY_LIB_EXCEPTION, CC_FERR_THIRD_PARTY_LIB_FAILURE, CC_FERR_UNKNOWN_FILE, CC_FERR_WRITING, CC_FERR_WRONG_FILE_TYPE, and error().
Referenced by define_qcc_io().