ACloudViewer: /root/ACloudViewer/plugins/core/Standard/q3DMASC/qClassify3DMASCDialog.cpp File Reference
qClassify3DMASCDialog.cpp File Reference
#include "qClassify3DMASCDialog.h"
#include <ecvMainAppInterface.h>
#include <ecvPointCloud.h>
#include <QComboBox>
#include <QMainWindow>
#include <QPushButton>
#include <QSettings>
Functions
static ccPointCloud * GetCloudFromCombo (QComboBox *comboBox, ccHObject *dbRoot)
Function Documentation
GetCloudFromCombo()
static ccPointCloud* GetCloudFromCombo (QComboBox * comboBox, ccHObject * dbRoot) static
Definition at line 22 of file qClassify3DMASCDialog.cpp.
References ccHObject::find(), ccObject::isA(), and CV_TYPES::POINT_CLOUD.
Referenced by Classify3DMASCDialog::getClouds().