ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qColorimetricSegmenter/qColorimetricSegmenter.cpp File Reference
qColorimetricSegmenter.cpp File Reference
#include "qColorimetricSegmenter.h"
#include "HSV.h"
#include "HSVDialog.h"
#include "KmeansDlg.h"
#include "QuantiDialog.h"
#include "RgbDialog.h"
#include "ScalarDialog.h"
#include <CVLog.h>
#include <ecvPointCloud.h>
#include <DistanceComputationTools.h>
#include <algorithm>
#include <map>
#include <QMainWindow>
Typedefs
typedef QSharedPointer< cloudViewer::ReferenceCloud > _Region
typedef std::vector< _Region > _RegionSet
typedef std::vector< _RegionSet > SetOfRegionSet
typedef std::map< size_t, std::vector< unsigned > > ClusterMap
Functions
static void ShowDurationNow (const std::chrono::high_resolution_clock::time_point &startTime)
static bool Inside (ColorCompType lower, ColorCompType value, ColorCompType upper)
static bool KNNRegions (ccPointCloud *basePointCloud, const _RegionSet &regions, const _Region &region, unsigned k, _RegionSet &neighbourRegions, unsigned thresholdDistance)
KNNRegions Determines the neighboring regions of a region.
static double ColorimetricalDifference (ecvColor::Rgb c1, ecvColor::Rgb c2)
colorimetricalDifference Compute colorimetrical difference between two RGB color values.
static ecvColor::Rgb ComputeAverageColor (const ccPointCloud &cloud, cloudViewer::ReferenceCloud *subset)
double ColorimetricalDifference (const ccPointCloud &basePointCloud, cloudViewer::ReferenceCloud *c1, cloudViewer::ReferenceCloud *c2)
colorimetricalDifference compute mean colorimetrical difference between two reference clouds. The points in both clouds must be represented in RGB value.
static int FindRegion (const std::vector< _RegionSet > &container, cloudViewer::ReferenceCloud *region)
findRegion Find a given region in a vector of reference clouds.
static bool GetKeyCluster (const ccPointCloud &cloud, size_t clusterPerDim, ClusterMap &clusterMap)
static ecvColor::Rgb ComputeAverageColor (const ccPointCloud &cloud, const std::vector< unsigned > &bucket)
static int ColorDistance (const ecvColor::Rgb &c1, const ecvColor::Rgb &c2)
static ccPointCloud * ComputeKmeansClustering (ccPointCloud *theCloud, unsigned K, int maxIterationCount)
Variables
static const unsigned TNN = 1
static const double TPP = 2.0
static const double TD = 2.0
static const double TRR = 2.0
static const unsigned Min = 2
Typedef Documentation
_Region
typedef QSharedPointer<cloudViewer::ReferenceCloud> _Region
Definition at line 384 of file qColorimetricSegmenter.cpp.
_RegionSet
typedef std::vector<_Region> _RegionSet
Definition at line 385 of file qColorimetricSegmenter.cpp.
ClusterMap
typedef std::map<size_t, std::vector<unsigned> > ClusterMap
Generate nxnxn clusters of points according to their color value (RGB)
Parameters
cloud : the cloud which we work with
clusterPerDim : coefficient uses to split each RGB component Returns a map of nxnxn keys, for each key a vector of the points index in the partition
Definition at line 1029 of file qColorimetricSegmenter.cpp.
SetOfRegionSet
typedef std::vector<_RegionSet> SetOfRegionSet
Definition at line 386 of file qColorimetricSegmenter.cpp.
Function Documentation
ColorDistance()
static int ColorDistance (const ecvColor::Rgb & c1, const ecvColor::Rgb & c2) static
Compute the distance between two colors /!\ the formula can be modified, here it is simple to be as quick as possible
Definition at line 1099 of file qColorimetricSegmenter.cpp.
References ecvColor::RgbTpl< Type >::b, ecvColor::RgbTpl< Type >::g, and ecvColor::RgbTpl< Type >::r.
Referenced by ComputeKmeansClustering().
ColorimetricalDifference() [1/2]
double ColorimetricalDifference (const ccPointCloud & basePointCloud, cloudViewer::ReferenceCloud * c1, cloudViewer::ReferenceCloud * c2)
colorimetricalDifference compute mean colorimetrical difference between two reference clouds. The points in both clouds must be represented in RGB value.
Parameters
basePointCloud The base cloud on which the reference clouds are based.
c1 The first reference cloud.
c2 The second reference cloud.
Returns
Colorimetrical difference.
Definition at line 537 of file qColorimetricSegmenter.cpp.
References ColorimetricalDifference(), and ComputeAverageColor().
ColorimetricalDifference() [2/2]
static double ColorimetricalDifference (ecvColor::Rgb c1, ecvColor::Rgb c2) static
colorimetricalDifference Compute colorimetrical difference between two RGB color values.
Parameters
c1 First color value.
c2 Second color value.
Returns
Colorimetrical difference.
Definition at line 480 of file qColorimetricSegmenter.cpp.
References ecvColor::RgbTpl< Type >::b, ecvColor::RgbTpl< Type >::g, and ecvColor::RgbTpl< Type >::r.
Referenced by ColorimetricalDifference().
ComputeAverageColor() [1/2]
static ecvColor::Rgb ComputeAverageColor (const ccPointCloud & cloud, cloudViewer::ReferenceCloud * subset) static
Compute the average color (RGB)
Parameters
cloud : cloud which contains the points
subset : subset of points Returns average color (RGB)
Definition at line 493 of file qColorimetricSegmenter.cpp.
References ecvColor::RgbTpl< Type >::b, count, ecvColor::RgbTpl< Type >::g, ccPointCloud::getPointColor(), cloudViewer::ReferenceCloud::getPointGlobalIndex(), ecvColor::MAX, min(), ecvColor::RgbTpl< Type >::r, cloudViewer::ReferenceCloud::size(), and ecvColor::white().
Referenced by ColorimetricalDifference(), and ComputeKmeansClustering().
ComputeAverageColor() [2/2]
static ecvColor::Rgb ComputeAverageColor (const ccPointCloud & cloud, const std::vector< unsigned > & bucket) static
Compute the average color (RGB)
Parameters
cloud : cloud which contains the points
bucket : vector of indexes of points Returns average color (RGB)
Definition at line 1066 of file qColorimetricSegmenter.cpp.
References ecvColor::RgbTpl< Type >::b, count, ecvColor::RgbTpl< Type >::g, ccPointCloud::getPointColor(), ecvColor::MAX, min(), ecvColor::RgbTpl< Type >::r, and ecvColor::white().
ComputeKmeansClustering()
static ccPointCloud* ComputeKmeansClustering (ccPointCloud * theCloud, unsigned K, int maxIterationCount) static
K-means algorithm
Parameters
k : k clusters
it : limit of iterations before returns a result Returns a cloud quantified
Definition at line 1193 of file qColorimetricSegmenter.cpp.
References abs(), cloudViewer::utility::ceil(), ccPointCloud::cloneThis(), color, ColorDistance(), ComputeAverageColor(), ccPointCloud::getPointColor(), CVLog::Print(), ccPointCloud::resize(), ccObject::setName(), ccPointCloud::setPointColor(), cloudViewer::PointCloudTpl< T >::size(), and CVLog::Warning().
FindRegion()
static int FindRegion (const std::vector< _RegionSet > & container, cloudViewer::ReferenceCloud * region) static
findRegion Find a given region in a vector of reference clouds.
Parameters
container Container containing all the regions.
region Region to search for in the vector.
Returns
The index of the region if found, -1 in the other case.
Definition at line 635 of file qColorimetricSegmenter.cpp.
GetKeyCluster()
static bool GetKeyCluster (const ccPointCloud & cloud, size_t clusterPerDim, ClusterMap & clusterMap) static
Definition at line 1030 of file qColorimetricSegmenter.cpp.
References ecvColor::RgbTpl< Type >::b, ecvColor::RgbTpl< Type >::g, ccPointCloud::getPointColor(), ecvColor::MAX, ecvColor::RgbTpl< Type >::r, and cloudViewer::PointCloudTpl< T >::size().
Inside()
static bool Inside (ColorCompType lower, ColorCompType value, ColorCompType upper) inline static
Definition at line 43 of file qColorimetricSegmenter.cpp.
KNNRegions()
static bool KNNRegions (ccPointCloud * basePointCloud, const _RegionSet & regions, const _Region & region, unsigned k, _RegionSet & neighbourRegions, unsigned thresholdDistance) static
KNNRegions Determines the neighboring regions of a region.
Parameters
basePointCloud The base cloud containing the points.
regions The list containing all the regions in the base cloud point.
region The region to compare with others.
k Max number of neighbours to find.
neighbours The resulting nearest regions.
thresholdDistance The maximum distance to search for neighbors.
Definition at line 397 of file qColorimetricSegmenter.cpp.
References cloudViewer::DistanceComputationTools::computeCloud2CloudDistances(), params, ccPointCloud::partialClone(), and result.
ShowDurationNow()
static void ShowDurationNow (const std::chrono::high_resolution_clock::time_point & startTime) static
Definition at line 31 of file qColorimetricSegmenter.cpp.
References CVLog::Print().
Variable Documentation
Min
const unsigned Min = 2 static
Definition at line 726 of file qColorimetricSegmenter.cpp.
TD
const double TD = 2.0 static
Definition at line 724 of file qColorimetricSegmenter.cpp.
TNN
const unsigned TNN = 1 static
Definition at line 722 of file qColorimetricSegmenter.cpp.
TPP
const double TPP = 2.0 static
Definition at line 723 of file qColorimetricSegmenter.cpp.
TRR
const double TRR = 2.0 static
Definition at line 725 of file qColorimetricSegmenter.cpp.