ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qCork/src/qCork.cpp File Reference
qCork.cpp File Reference
#include "qCork.h"
#include <ecvMesh.h>
#include <ecvPointCloud.h>
#include "ccCorkDlg.h"
#include <QApplication>
#include <QMainWindow>
#include <QProgressDialog>
#include <QtConcurrentRun>
#include <QtGui>
#include <mesh/corkMesh.h>
#include <time.h>
#include <unistd.h>
Classes
struct BoolOpParameters
Boolean operation parameters (for concurrent run)
Functions
bool ToCorkMesh (const ccMesh *in, CorkMesh &out, ecvMainAppInterface *app=0)
ccMesh * FromCorkMesh (const CorkMesh &in, ecvMainAppInterface *app=0)
bool doPerformBooleanOp ()
Variables
static BoolOpParameters s_params
Function Documentation
doPerformBooleanOp()
bool doPerformBooleanOp ()
Definition at line 204 of file qCork.cpp.
References BoolOpParameters::app, BoolOpParameters::corkA, BoolOpParameters::corkB, ccCorkDlg::DIFF, ecvMainAppInterface::dispToConsole(), e, ccCorkDlg::INTERSECT, BoolOpParameters::meshesAreOk, BoolOpParameters::nameA, BoolOpParameters::nameB, BoolOpParameters::operation, s_params, ccCorkDlg::SYM_DIFF, ccCorkDlg::UNION, and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by qCork::doAction().
FromCorkMesh()
ccMesh* FromCorkMesh (const CorkMesh & in, ecvMainAppInterface * app = 0)
Definition at line 127 of file qCork.cpp.
Referenced by qCork::doAction().
ToCorkMesh()
bool ToCorkMesh (const ccMesh * in, CorkMesh & out, ecvMainAppInterface * app = 0)
Definition at line 62 of file qCork.cpp.
Referenced by qCork::doAction().
Variable Documentation
s_params
BoolOpParameters s_params static
Definition at line 202 of file qCork.cpp.
Referenced by qCork::doAction(), and doPerformBooleanOp().