ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qFacets/src/qFacets.cpp File Reference
qFacets.cpp File Reference
#include "qFacets.h"
#include <exception>
#include "classificationParamsDlg.h"
#include "disclaimerDialog.h"
#include "facetsClassifier.h"
#include "facetsExportDlg.h"
#include "fastMarchingForFacetExtraction.h"
#include "kdTreeForFacetExtraction.h"
#include "stereogramDlg.h"
#include <QElapsedTimer>
#include <QFileInfo>
#include <QInputDialog>
#include <QMessageBox>
#include <QSettings>
#include <QtGui>
#include <QtCompat.h>
#include <CVLog.h>
#include <ShpDBFFields.h>
#include <ecvDisplayTools.h>
#include <ecvFileUtils.h>
#include <ecvHObjectCaster.h>
#include <ecvMesh.h>
#include <ecvOctree.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <ShpFilter.h>
Classes
struct FacetMetaData
Functions
void GetFacetMetaData (ccFacet *facet, FacetMetaData &data)
void ComputeFacetExtensions (CCVector3 &N, ccPolyline *facetContour, double &horizExt, double &vertExt)
Variables
static unsigned s_octreeLevel = 8
static bool s_fmUseRetroProjectionError = false
static unsigned s_minPointsPerFacet = 10
static double s_errorMaxPerFacet = 0.2
static int s_errorMeasureType = 3
static double s_maxEdgeLength = 1.0
static double s_kdTreeFusionMaxAngle_deg = 20.0
static double s_kdTreeFusionMaxRelativeDistance = 1.0
static double s_classifAngleStep = 30.0
static double s_classifMaxDist = 1.0
static double s_stereogramAngleStep = 30.0
static double s_stereogramResolution_deg = 5.0
static ccPointCloud * s_lastCloud = nullptr
static StereogramDialog * s_fcDlg = nullptr
Function Documentation
ComputeFacetExtensions()
void ComputeFacetExtensions (CCVector3 & N, ccPolyline * facetContour, double & horizExt, double & vertExt)
Definition at line 644 of file qFacets.cpp.
References cloudViewer::BoundingBoxTpl< T >::add(), Vector3Tpl< Type >::cross(), Vector3Tpl< Type >::dot(), cloudViewer::ReferenceCloud::getAssociatedCloud(), cloudViewer::BoundingBoxTpl< T >::getDiagVec(), cloudViewer::Neighbourhood::getGravityCenter(), cloudViewer::GenericIndexedCloud::getPoint(), cloudViewer::GreaterThanEpsilon(), Vector3Tpl< Type >::norm2(), Vector3Tpl< Type >::normalize(), cloudViewer::GenericCloud::size(), Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::y.
Referenced by qFacets::exportFacets(), and qFacets::exportFacetsInfo().
GetFacetMetaData()
void GetFacetMetaData (ccFacet * facet, FacetMetaData & data)
Definition at line 611 of file qFacets.cpp.
References FacetMetaData::center, ccNormalVectors::ConvertNormalToDipAndDipDir(), FacetMetaData::dip_deg, FacetMetaData::dipDir_deg, FacetMetaData::facetIndex, FacetMetaData::familyIndex, ccFacet::getCenter(), ccObject::getMetaData(), ccObject::getName(), ccFacet::getNormal(), ccFacet::getRMS(), ccFacet::getSurface(), FacetMetaData::normal, FacetMetaData::rms, s_OriFamilyKey, s_OriSubFamilyKey, QtCompat::SkipEmptyParts, FacetMetaData::subfamilyIndex, and FacetMetaData::surface.
Referenced by qFacets::exportFacets(), and qFacets::exportFacetsInfo().
Variable Documentation
s_classifAngleStep
double s_classifAngleStep = 30.0 static
Definition at line 60 of file qFacets.cpp.
Referenced by qFacets::classifyFacetsByAngle().
s_classifMaxDist
double s_classifMaxDist = 1.0 static
Definition at line 61 of file qFacets.cpp.
Referenced by qFacets::classifyFacetsByAngle().
s_errorMaxPerFacet
double s_errorMaxPerFacet = 0.2 static
Definition at line 53 of file qFacets.cpp.
Referenced by qFacets::extractFacets().
s_errorMeasureType
int s_errorMeasureType = 3 static
Definition at line 54 of file qFacets.cpp.
Referenced by qFacets::extractFacets().
s_fcDlg
StereogramDialog* s_fcDlg = nullptr static
Definition at line 68 of file qFacets.cpp.
Referenced by qFacets::showStereogram().
s_fmUseRetroProjectionError
bool s_fmUseRetroProjectionError = false static
Definition at line 50 of file qFacets.cpp.
Referenced by qFacets::extractFacets().
s_kdTreeFusionMaxAngle_deg
double s_kdTreeFusionMaxAngle_deg = 20.0 static
Definition at line 57 of file qFacets.cpp.
Referenced by qFacets::extractFacets().
s_kdTreeFusionMaxRelativeDistance
double s_kdTreeFusionMaxRelativeDistance = 1.0 static
Definition at line 58 of file qFacets.cpp.
Referenced by qFacets::extractFacets().
s_lastCloud
ccPointCloud* s_lastCloud = nullptr static
Definition at line 65 of file qFacets.cpp.
Referenced by qFacets::extractFacets().
s_maxEdgeLength
double s_maxEdgeLength = 1.0 static
Definition at line 55 of file qFacets.cpp.
Referenced by qFacets::extractFacets().
s_minPointsPerFacet
unsigned s_minPointsPerFacet = 10 static
Definition at line 52 of file qFacets.cpp.
Referenced by qFacets::extractFacets().
s_octreeLevel
unsigned s_octreeLevel = 8 static
Definition at line 49 of file qFacets.cpp.
Referenced by qFacets::extractFacets().
s_stereogramAngleStep
double s_stereogramAngleStep = 30.0 static
Definition at line 63 of file qFacets.cpp.
Referenced by qFacets::classifyFacetsByAngle(), and qFacets::showStereogram().
s_stereogramResolution_deg
double s_stereogramResolution_deg = 5.0 static
Definition at line 64 of file qFacets.cpp.
Referenced by qFacets::showStereogram().