ACloudViewer: /root/ACloudViewer/plugins/core/IO/qPhotoscanIO/extern/quazip/quazip/quazip/qioapi.cpp File Reference
qioapi.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <QIODevice>
#include "ioapi.h"
#include "quazip_global.h"
#include "zlib.h"
Macros
#define SEEK_CUR 1
#define SEEK_END 2
#define SEEK_SET 0
Functions
voidpf call_zopen64 (const zlib_filefunc64_32_def *pfilefunc, voidpf file, int mode)
int call_zseek64 (const zlib_filefunc64_32_def *pfilefunc, voidpf filestream, ZPOS64_T offset, int origin)
ZPOS64_T call_ztell64 (const zlib_filefunc64_32_def *pfilefunc, voidpf filestream)
voidpf qiodevice_open_file_func (voidpf opaque, voidpf file, int mode)
uLong qiodevice_read_file_func (voidpf opaque, voidpf stream, void *buf, uLong size)
uLong qiodevice_write_file_func (voidpf opaque, voidpf stream, const void *buf, uLong size)
uLong qiodevice_tell_file_func (voidpf opaque, voidpf stream)
ZPOS64_T qiodevice64_tell_file_func (voidpf opaque, voidpf stream)
int qiodevice_seek_file_func (voidpf, voidpf stream, uLong offset, int origin)
int qiodevice64_seek_file_func (voidpf, voidpf stream, ZPOS64_T offset, int origin)
int qiodevice_close_file_func (voidpf opaque, voidpf stream)
int qiodevice_fakeclose_file_func (voidpf opaque, voidpf)
int qiodevice_error_file_func (voidpf, voidpf)
void fill_qiodevice_filefunc (zlib_filefunc_def *pzlib_filefunc_def)
void fill_qiodevice64_filefunc (zlib_filefunc64_def *pzlib_filefunc_def)
void fill_zlib_filefunc64_32_def_from_filefunc32 (zlib_filefunc64_32_def *p_filefunc64_32, const zlib_filefunc_def *p_filefunc32)
Macro Definition Documentation
SEEK_CUR
#define SEEK_CUR 1
Definition at line 30 of file qioapi.cpp.
SEEK_END
#define SEEK_END 2
Definition at line 34 of file qioapi.cpp.
SEEK_SET
#define SEEK_SET 0
Definition at line 38 of file qioapi.cpp.
Function Documentation
call_zopen64()
voidpf call_zopen64 (const zlib_filefunc64_32_def * pfilefunc, voidpf file, int mode)
Definition at line 41 of file qioapi.cpp.
References NULL, zlib_filefunc64_def_s::opaque, zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_32_def_s::zopen32_file, and zlib_filefunc64_def_s::zopen64_file.
call_zseek64()
int call_zseek64 (const zlib_filefunc64_32_def * pfilefunc, voidpf filestream, ZPOS64_T offset, int origin)
Definition at line 53 of file qioapi.cpp.
References NULL, offset, zlib_filefunc64_def_s::opaque, zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_32_def_s::zseek32_file, and zlib_filefunc64_def_s::zseek64_file.
call_ztell64()
ZPOS64_T call_ztell64 (const zlib_filefunc64_32_def * pfilefunc, voidpf filestream)
Definition at line 71 of file qioapi.cpp.
References NULL, zlib_filefunc64_def_s::opaque, zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc64_32_def_s::ztell32_file, and zlib_filefunc64_def_s::ztell64_file.
fill_qiodevice64_filefunc()
void fill_qiodevice64_filefunc (zlib_filefunc64_def * pzlib_filefunc_def)
Definition at line 307 of file qioapi.cpp.
References zlib_filefunc64_def_s::opaque, qiodevice64_seek_file_func(), qiodevice64_tell_file_func(), qiodevice_close_file_func(), qiodevice_error_file_func(), qiodevice_fakeclose_file_func(), qiodevice_open_file_func(), qiodevice_read_file_func(), qiodevice_write_file_func(), zlib_filefunc64_def_s::zclose_file, zlib_filefunc64_def_s::zerror_file, zlib_filefunc64_def_s::zfakeclose_file, zlib_filefunc64_def_s::zopen64_file, zlib_filefunc64_def_s::zread_file, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc64_def_s::ztell64_file, and zlib_filefunc64_def_s::zwrite_file.
Referenced by zipOpen3().
fill_qiodevice_filefunc()
void fill_qiodevice_filefunc (zlib_filefunc_def * pzlib_filefunc_def)
Definition at line 296 of file qioapi.cpp.
References zlib_filefunc_def_s::opaque, qiodevice_close_file_func(), qiodevice_error_file_func(), qiodevice_open_file_func(), qiodevice_read_file_func(), qiodevice_seek_file_func(), qiodevice_tell_file_func(), qiodevice_write_file_func(), zlib_filefunc_def_s::zclose_file, zlib_filefunc_def_s::zerror_file, zlib_filefunc_def_s::zopen_file, zlib_filefunc_def_s::zread_file, zlib_filefunc_def_s::zseek_file, zlib_filefunc_def_s::ztell_file, and zlib_filefunc_def_s::zwrite_file.
fill_zlib_filefunc64_32_def_from_filefunc32()
void fill_zlib_filefunc64_32_def_from_filefunc32 (zlib_filefunc64_32_def * p_filefunc64_32, const zlib_filefunc_def * p_filefunc32)
Definition at line 320 of file qioapi.cpp.
References NULL, zlib_filefunc_def_s::opaque, zlib_filefunc64_def_s::opaque, zlib_filefunc_def_s::zclose_file, zlib_filefunc64_def_s::zclose_file, zlib_filefunc_def_s::zerror_file, zlib_filefunc64_def_s::zerror_file, zlib_filefunc64_def_s::zfakeclose_file, zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_32_def_s::zopen32_file, zlib_filefunc64_def_s::zopen64_file, zlib_filefunc_def_s::zopen_file, zlib_filefunc_def_s::zread_file, zlib_filefunc64_def_s::zread_file, zlib_filefunc64_32_def_s::zseek32_file, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc_def_s::zseek_file, zlib_filefunc64_32_def_s::ztell32_file, zlib_filefunc64_def_s::ztell64_file, zlib_filefunc_def_s::ztell_file, zlib_filefunc_def_s::zwrite_file, and zlib_filefunc64_def_s::zwrite_file.
Referenced by unzOpen2(), and zipOpen2().
qiodevice64_seek_file_func()
int qiodevice64_seek_file_func (voidpf , voidpf stream, ZPOS64_T offset, int origin)
Definition at line 234 of file qioapi.cpp.
References offset, ZLIB_FILEFUNC_SEEK_CUR, ZLIB_FILEFUNC_SEEK_END, and ZLIB_FILEFUNC_SEEK_SET.
Referenced by fill_qiodevice64_filefunc().
qiodevice64_tell_file_func()
ZPOS64_T qiodevice64_tell_file_func (voidpf opaque, voidpf stream)
Definition at line 189 of file qioapi.cpp.
Referenced by fill_qiodevice64_filefunc().
qiodevice_close_file_func()
int qiodevice_close_file_func (voidpf opaque, voidpf stream)
Definition at line 267 of file qioapi.cpp.
References NULL.
Referenced by fill_qiodevice64_filefunc(), and fill_qiodevice_filefunc().
qiodevice_error_file_func()
int qiodevice_error_file_func (voidpf , voidpf)
Definition at line 290 of file qioapi.cpp.
Referenced by fill_qiodevice64_filefunc(), and fill_qiodevice_filefunc().
qiodevice_fakeclose_file_func()
int qiodevice_fakeclose_file_func (voidpf opaque, voidpf)
Definition at line 284 of file qioapi.cpp.
Referenced by fill_qiodevice64_filefunc().
qiodevice_open_file_func()
voidpf qiodevice_open_file_func (voidpf opaque, voidpf file, int mode)
Definition at line 94 of file qioapi.cpp.
References NULL, ZLIB_FILEFUNC_MODE_CREATE, ZLIB_FILEFUNC_MODE_EXISTING, ZLIB_FILEFUNC_MODE_READ, and ZLIB_FILEFUNC_MODE_READWRITEFILTER.
Referenced by fill_qiodevice64_filefunc(), and fill_qiodevice_filefunc().
qiodevice_read_file_func()
uLong qiodevice_read_file_func (voidpf opaque, voidpf stream, void * buf, uLong size)
Definition at line 145 of file qioapi.cpp.
References size.
Referenced by fill_qiodevice64_filefunc(), and fill_qiodevice_filefunc().
qiodevice_seek_file_func()
int qiodevice_seek_file_func (voidpf , voidpf stream, uLong offset, int origin)
Definition at line 201 of file qioapi.cpp.
References offset, ZLIB_FILEFUNC_SEEK_CUR, ZLIB_FILEFUNC_SEEK_END, and ZLIB_FILEFUNC_SEEK_SET.
Referenced by fill_qiodevice_filefunc().
qiodevice_tell_file_func()
uLong qiodevice_tell_file_func (voidpf opaque, voidpf stream)
Definition at line 175 of file qioapi.cpp.
Referenced by fill_qiodevice_filefunc().
qiodevice_write_file_func()
uLong qiodevice_write_file_func (voidpf opaque, voidpf stream, const void * buf, uLong size)
Definition at line 160 of file qioapi.cpp.
References size.
Referenced by fill_qiodevice64_filefunc(), and fill_qiodevice_filefunc().