ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qM3C2/src/qM3C2Dialog.cpp File Reference
qM3C2Dialog.cpp File Reference
#include "qM3C2Dialog.h"
#include <ecvFileUtils.h>
#include <ecvPointCloud.h>
#include "ecvMainAppInterface.h"
#include <QComboBox>
#include <QFileDialog>
#include <QFileInfo>
#include <QMainWindow>
#include <QMessageBox>
#include <QThread>
Functions
static QString GetEntityName (ccHObject *obj)
static ccPointCloud * GetCloudFromCombo (QComboBox *comboBox, ccHObject *dbRoot)
bool PopulateSFCombo (QComboBox *combo, const ccPointCloud &cloud, int defaultFieldIndex=-1, QString defaultField=QString())
bool PopulatePMFields (QComboBox *sx, QComboBox *sy, QComboBox *sz, const ccPointCloud &cloud)
Variables
static bool s_firstTimeInit = true
Function Documentation
GetCloudFromCombo()
static ccPointCloud* GetCloudFromCombo (QComboBox * comboBox, ccHObject * dbRoot) static
Definition at line 40 of file qM3C2Dialog.cpp.
References ccHObject::find(), ccObject::isA(), and CV_TYPES::POINT_CLOUD.
Referenced by qM3C2Dialog::getCorePointsCloud(), qM3C2Dialog::getNormalsOrientationCloud(), and qM3C2Dialog::updateNormalComboBox().
GetEntityName()
static QString GetEntityName (ccHObject * obj) static
Definition at line 27 of file qM3C2Dialog.cpp.
References ccObject::getName(), ccObject::getUniqueID(), and name.
Referenced by qM3C2Dialog::qM3C2Dialog(), and qM3C2Dialog::setClouds().
PopulatePMFields()
bool PopulatePMFields (QComboBox * sx, QComboBox * sy, QComboBox * sz, const ccPointCloud & cloud)
Definition at line 166 of file qM3C2Dialog.cpp.
References cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), and PopulateSFCombo().
Referenced by qM3C2Dialog::setupPrecisionMapsTab().
PopulateSFCombo()
bool PopulateSFCombo (QComboBox * combo, const ccPointCloud & cloud, int defaultFieldIndex = -1, QString defaultField = QString())
Definition at line 134 of file qM3C2Dialog.cpp.
References QtCompatRegExpOption::CaseInsensitive, cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), and cloudViewer::PointCloudTpl< T >::getScalarFieldName().
Referenced by PopulatePMFields().
Variable Documentation
s_firstTimeInit
bool s_firstTimeInit = true static
Definition at line 24 of file qM3C2Dialog.cpp.
Referenced by qM3C2Dialog::setClouds().