ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qM3C2/src/qM3C2Tools.cpp File Reference
qM3C2Tools.cpp File Reference
#include "qM3C2Tools.h"
#include <DistanceComputationTools.h>
#include <Jacobi.h>
#include <Neighbourhood.h>
#include <ecvAdvancedTypes.h>
#include <ecvGenericPointCloud.h>
#include <ecvMainAppInterface.h>
#include <ecvNormalVectors.h>
#include <ecvOctree.h>
#include <ecvOctreeProxy.h>
#include <ecvPointCloud.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <QApplication>
#include <QMainWindow>
#include <QProgressDialog>
#include <QtConcurrentMap>
#include <QtCore>
#include <vector>
Functions
void ComputeCorePointNormal (unsigned index)
static void OrientPointNormalWithCloud (unsigned index)
static double Median (const cloudViewer::DgmOctree::NeighboursSet &set, size_t begin=0, size_t count=0)
Computes the median distance of a (sorted) neighbors set.
double Interquartile (const cloudViewer::DgmOctree::NeighboursSet &set)
Computes the interquartile range of a (sorted) neighbors set.
Variables
struct {
cloudViewer::GenericIndexedCloud * corePoints
ccGenericPointCloud * sourceCloud
cloudViewer::DgmOctree * octree
unsigned char octreeLevel
std::vector< PointCoordinateType > radii
NormsIndexesTableType * normCodes
ccScalarField * normalScale
bool invalidNormals
cloudViewer::NormalizedProgress * nProgress
bool processCanceled
} s_corePointsNormalsParams
struct {
NormsIndexesTableType * normsCodes
cloudViewer::GenericIndexedCloud * normCloud
cloudViewer::GenericIndexedCloud * orientationCloud
cloudViewer::NormalizedProgress * nProgress
bool processCanceled
} s_normOriWithCloud
Function Documentation
ComputeCorePointNormal()
void ComputeCorePointNormal (unsigned index)
Definition at line 52 of file qM3C2Tools.cpp.
References cloudViewer::ReferenceCloud::addPointIndex(), cloudViewer::ReferenceCloud::clear(), cloudViewer::Neighbourhood::computeCovarianceMatrix(), Vector3Tpl< PointCoordinateType >::fromArray(), Jacobi< Scalar >::GetMinEigenValueAndVector(), ccNormalVectors::GetNormIndex(), NAN_VALUE, Vector3Tpl< Type >::normalize(), s_corePointsNormalsParams, cloudViewer::ReferenceCloud::size(), std::swap(), Tuple3Tpl< Type >::u, Tuple3Tpl< Type >::x, and Tuple3Tpl< Type >::z.
Referenced by qM3C2Normals::ComputeCorePointsNormals().
Interquartile()
double Interquartile (const cloudViewer::DgmOctree::NeighboursSet & set)
Computes the interquartile range of a (sorted) neighbors set.
Uses Mathworld's definition (http://mathworld.wolfram.com/InterquartileRange.html) as the original m3c2 code by N. Brodu.
Definition at line 474 of file qM3C2Tools.cpp.
References Median(), and NAN_VALUE.
Referenced by qM3C2Tools::ComputeStatistics().
Median()
static double Median (const cloudViewer::DgmOctree::NeighboursSet & set, size_t begin = 0, size_t count = 0) static
Computes the median distance of a (sorted) neighbors set.
Uses the common definition using mid-point average in the even case just as the original m3c2 code by N. Brodu.
Definition at line 450 of file qM3C2Tools.cpp.
References count, and NAN_VALUE.
Referenced by qM3C2Tools::ComputeStatistics(), and Interquartile().
OrientPointNormalWithCloud()
static void OrientPointNormalWithCloud (unsigned index) static
Definition at line 308 of file qM3C2Tools.cpp.
References Vector3Tpl< Type >::dot(), ccNormalVectors::GetNormal(), ccNormalVectors::GetNormIndex(), Vector3Tpl< Type >::norm2(), s_normOriWithCloud, and Tuple3Tpl< Type >::u.
Referenced by qM3C2Normals::UpdateNormalOrientationsWithCloud().
Variable Documentation
corePoints
cloudViewer::GenericIndexedCloud* corePoints
Definition at line 38 of file qM3C2Tools.cpp.
Referenced by qM3C2Normals::ComputeCorePointsNormals().
invalidNormals
bool invalidNormals
Definition at line 45 of file qM3C2Tools.cpp.
Referenced by qM3C2Process::Compute(), and qM3C2Normals::ComputeCorePointsNormals().
normalScale
ccScalarField* normalScale
Definition at line 44 of file qM3C2Tools.cpp.
Referenced by qM3C2Process::Compute(), qM3C2Normals::ComputeCorePointsNormals(), qM3C2Dialog::loadParamsFrom(), and PclUtils::PCLVis::updateNormals().
normCloud
cloudViewer::GenericIndexedCloud* normCloud
Definition at line 300 of file qM3C2Tools.cpp.
Referenced by qM3C2Normals::UpdateNormalOrientationsWithCloud().
normCodes
NormsIndexesTableType* normCodes
Definition at line 43 of file qM3C2Tools.cpp.
normsCodes
NormsIndexesTableType* normsCodes
Definition at line 299 of file qM3C2Tools.cpp.
Referenced by qM3C2Normals::MakeNormalsHorizontal(), and qM3C2Normals::UpdateNormalOrientationsWithCloud().
nProgress
cloudViewer::NormalizedProgress* nProgress
Definition at line 47 of file qM3C2Tools.cpp.
Referenced by qM3C2Normals::ComputeCorePointsNormals(), and qM3C2Normals::UpdateNormalOrientationsWithCloud().
octree
cloudViewer::DgmOctree* octree
Definition at line 40 of file qM3C2Tools.cpp.
octreeLevel
unsigned char octreeLevel
Definition at line 41 of file qM3C2Tools.cpp.
Referenced by qM3C2Normals::ComputeCorePointsNormals().
orientationCloud
cloudViewer::GenericIndexedCloud* orientationCloud
Definition at line 301 of file qM3C2Tools.cpp.
Referenced by qM3C2Process::Compute(), and qM3C2Normals::UpdateNormalOrientationsWithCloud().
processCanceled
bool processCanceled
Definition at line 48 of file qM3C2Tools.cpp.
radii
std::vector<PointCoordinateType> radii
Definition at line 42 of file qM3C2Tools.cpp.
Referenced by cloudViewer::pipelines::registration::BenchmarkCreateFromPointCloudBallPivoting(), qM3C2Process::Compute(), ccMesh::CreateFromPointCloudBallPivoting(), GrainsAsEllipsoids::explicitToImplicit(), GrainsAsEllipsoids::fitEllipsoidToGrain(), GrainsAsEllipsoids::implicitToExplicit(), cloudViewer::core::nns::NearestNeighborSearch::MultiRadiusSearch(), BallPivoting::Run(), cloudViewer::core::nns::NanoFlannIndex::SearchRadius(), and GrainsAsEllipsoids::updateMeshAndLineSet().
struct { ... } s_corePointsNormalsParams
Referenced by ComputeCorePointNormal(), and qM3C2Normals::ComputeCorePointsNormals().
struct { ... } s_normOriWithCloud
Referenced by OrientPointNormalWithCloud(), and qM3C2Normals::UpdateNormalOrientationsWithCloud().
sourceCloud
ccGenericPointCloud* sourceCloud
Definition at line 39 of file qM3C2Tools.cpp.
Referenced by qM3C2Normals::ComputeCorePointsNormals().