ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qSRA/src/qSRA.cpp File Reference
qSRA.cpp File Reference
#include "qSRA.h"
#include "distanceMapGenerationDlg.h"
#include "profileImportDlg.h"
#include "profileLoader.h"
#include <QFile>
#include <QFileInfo>
#include <QMainWindow>
#include <QMessageBox>
#include <QSettings>
#include <QtGui>
#include <ecvCone.h>
#include <ecvDisplayTools.h>
#include <ecvFileUtils.h>
#include <ecvHObjectCaster.h>
#include <ecvMesh.h>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <string.h>
#include <algorithm>
#include <vector>
Functions
const QString QSRA_DEFAULT_CONTAINER_NAME ("Profile(s)")
ccHObject * GetDefaultContainer (ecvMainAppInterface *app)
static ccPolyline * GetConeProfile (ccCone *cone)
Function Documentation
GetConeProfile()
static ccPolyline* GetConeProfile (ccCone * cone) static
Definition at line 240 of file qSRA.cpp.
References ccHObject::addChild(), cloudViewer::PointCloudTpl< T >::addPoint(), cloudViewer::ReferenceCloud::addPointIndex(), CVLog::Error(), ccGLMatrixTpl< float >::FromToRotation(), ccCone::getBottomRadius(), ccGLMatrixTpl< T >::getColumnAsVec3D(), ccCone::getHeight(), ccCone::getTopRadius(), ccGenericPrimitive::getTransformation(), ccGLMatrixTpl< T >::getTranslationAsVec3D(), height, cloudViewer::LessThanEpsilon(), origin, PC_ONE, cloudViewer::ReferenceCloud::reserve(), ccPointCloud::reserve(), cloudViewer::Polyline::setClosed(), ccDrawableObject::setGLTransformation(), DistanceMapGenerationTool::SetPolylineHeightShift(), DistanceMapGenerationTool::SetPoylineAxis(), DistanceMapGenerationTool::SetPoylineOrigin(), DistanceMapGenerationTool::SetPoylineRevolDim(), Tuple3Tpl< Type >::u, and y.
Referenced by qSRA::computeCloud2ProfileRadialDist(), and qSRA::projectCloudDistsInGrid().
GetDefaultContainer()
ccHObject* GetDefaultContainer (ecvMainAppInterface * app)
Definition at line 123 of file qSRA.cpp.
References ecvMainAppInterface::addToDB(), ecvMainAppInterface::dbRootObject(), ccHObject::filterChildren(), CV_TYPES::HIERARCHY_OBJECT, and QSRA_DEFAULT_CONTAINER_NAME().
Referenced by qSRA::loadProfile().
QSRA_DEFAULT_CONTAINER_NAME()
const QString QSRA_DEFAULT_CONTAINER_NAME ("Profile(s)")
Referenced by GetDefaultContainer().