ACloudViewer: /root/ACloudViewer/core/include/QtCompat.h File Reference
QtCompat.h File Reference
#include <QMap>
#include <QMultiMap>
#include <QPoint>
#include <QPointF>
#include <QSet>
#include <QString>
#include <QStringList>
#include <QTextStream>
#include <QVector>
#include <QtGlobal>
#include <QRegularExpression>
#include <QStringView>
#include <Qt>
#include <QRegularExpressionMatch>
#include <QByteArray>
#include <QStringConverter>
#include <QWheelEvent>
#include <QMouseEvent>
#include <QDropEvent>
#include <QVariant>
#include <QPlainTextEdit>
Classes
class QtCompatRegExpWrapper
class QtCompatTextCodec
Namespaces
QtCompatRegExpOption
QtCompat
Macros
#define QTCOMPAT_FONTMETRICS_WIDTH(fm, text) (fm).horizontalAdvance(text)
#define QTCOMPAT_ENDL Qt::endl
Typedefs
using QtCompatRegExp = QRegularExpression
using QtCompatStringRef = QStringView
using QtCompatStringRefList = QList< QStringView >
using QtCompatQTextCodec = QtCompatTextCodec
using QtCompatVariantType = QMetaType::Type
Functions
QRegularExpression qtCompatRegExp (const QString &pattern)
QStringList qtCompatSplit (const QString &str, const QRegularExpression &regex, Qt::SplitBehavior behavior=Qt::KeepEmptyParts)
QStringView qtCompatStringRef (const QString &str) noexcept
QString qtCompatStringRefToString (const QStringView &view)
QStringView qtCompatStringRef (const QString &str, int pos, int n=-1) noexcept
QtCompatStringRefList qtCompatSplitRef (const QString &str, QChar sep)
QStringList qtCompatSplitRegex (const QString &str, const QString &pattern, Qt::SplitBehavior behavior=Qt::KeepEmptyParts)
QString & qtCompatReplace (QString &str, const QRegularExpression &regex, const QString &after)
QString qtCompatReplace (const QString &str, const QRegularExpression &regex, const QString &after)
QString & qtCompatReplace (QString &str, const QString &pattern, const QString &after)
QString qtCompatReplace (const QString &str, const QString &pattern, const QString &after)
QtCompatStringRefList qtCompatSplitRefChar (const QString &str, QChar sep)
bool qtCompatRegExpMatch (const QRegularExpression &regex, const QString &str)
int qtCompatRegExpIndexIn (const QRegularExpression &regex, const QString &str, int offset=0)
int qtCompatRegExpPos (const QRegularExpressionMatch &match, int nth=0) noexcept
QString qtCompatRegExpCap (const QRegularExpressionMatch &match, int nth=0)
int qtCompatRegExpMatchedLength (const QRegularExpressionMatch &match) noexcept
QtCompatTextCodec * qtCompatCodecForLocale ()
QtCompatTextCodec * qtCompatCodecForName (const char *name)
QTextStream & QtCompat::endl (QTextStream &stream)
double qtCompatWheelEventDelta (const QWheelEvent *event) noexcept
QPointF qtCompatWheelEventPos (const QWheelEvent *event) noexcept
QPointF qtCompatMouseEventPos (const QMouseEvent *event) noexcept
QPointF qtCompatMouseEventGlobalPos (const QMouseEvent *event) noexcept
QPoint qtCompatMouseEventPosInt (const QMouseEvent *event) noexcept
QPoint qtCompatMouseEventGlobalPosInt (const QMouseEvent *event) noexcept
QPointF qtCompatDropEventPos (const QDropEvent *event) noexcept
QPoint qtCompatDropEventPosInt (const QDropEvent *event) noexcept
template<typename Key , typename T >
void qtCompatMapInsertMulti (QMap< Key, T > *map, const Key &key, const T &value)
template<typename Key , typename T >
void qtCompatMapInsertMulti (QMultiMap< Key, T > *map, const Key &key, const T &value)
template<typename Key , typename T >
void qtCompatMapUnite (QMap< Key, T > *map, const QMap< Key, T > &other)
template<typename Key , typename T >
void qtCompatMapUnite (QMultiMap< Key, T > *map, const QMultiMap< Key, T > &other)
QMetaType::Type qtCompatVariantType (const QVariant &var) noexcept
bool qtCompatVariantIsValid (const QVariant &var) noexcept
bool qtCompatVariantIsNull (const QVariant &var) noexcept
bool qtCompatVariantIsString (const QVariant &var) noexcept
bool qtCompatVariantIsInt (const QVariant &var) noexcept
bool qtCompatVariantIsDouble (const QVariant &var) noexcept
bool qtCompatVariantIsBool (const QVariant &var) noexcept
bool qtCompatVariantIsList (const QVariant &var) noexcept
bool qtCompatVariantIsMap (const QVariant &var) noexcept
void qtCompatSetTabStopWidth (QPlainTextEdit *edit, int width)
template<typename T >
QSet< T > qtCompatQSetFromVector (const QVector< T > &vec)
template<typename T >
QVector< T > qtCompatQVectorFromSet (const QSet< T > &set)
template<typename T >
QSet< T > qSetFromVector (const QVector< T > &vec)
template<typename T >
QVector< T > qVectorFromSet (const QSet< T > &set)
Variables
constexpr QRegularExpression::PatternOption QtCompatRegExpOption::CaseInsensitive
constexpr QRegularExpression::PatternOption QtCompatRegExpOption::DotMatchesEverything
constexpr QRegularExpression::PatternOption QtCompatRegExpOption::Multiline
constexpr Qt::SplitBehavior QtCompat::SkipEmptyParts = Qt::SkipEmptyParts
constexpr Qt::SplitBehavior QtCompat::KeepEmptyParts = Qt::KeepEmptyParts
Macro Definition Documentation
QTCOMPAT_ENDL
#define QTCOMPAT_ENDL Qt::endl
Definition at line 721 of file QtCompat.h.
QTCOMPAT_FONTMETRICS_WIDTH
#define QTCOMPAT_FONTMETRICS_WIDTH (fm, text) (fm).horizontalAdvance(text)
Definition at line 339 of file QtCompat.h.
Typedef Documentation
QtCompatQTextCodec
using QtCompatQTextCodec = QtCompatTextCodec
Definition at line 689 of file QtCompat.h.
QtCompatRegExp
using QtCompatRegExp = QRegularExpression
Definition at line 170 of file QtCompat.h.
QtCompatStringRef
using QtCompatStringRef = QStringView
Definition at line 227 of file QtCompat.h.
QtCompatStringRefList
using QtCompatStringRefList = QList<QStringView>
Definition at line 228 of file QtCompat.h.
QtCompatVariantType
using QtCompatVariantType = QMetaType::Type
Definition at line 918 of file QtCompat.h.
Function Documentation
qSetFromVector()
template<typename T > QSet<T> qSetFromVector (const QVector< T > & vec) inline
Definition at line 1073 of file QtCompat.h.
References qtCompatQSetFromVector().
qtCompatCodecForLocale()
QtCompatTextCodec* qtCompatCodecForLocale () inline
Definition at line 650 of file QtCompat.h.
Referenced by QTextCodec::codecForLocale(), and qtCompatCodecForName().
qtCompatCodecForName()
QtCompatTextCodec* qtCompatCodecForName (const char * name) inline
Definition at line 657 of file QtCompat.h.
References name, and qtCompatCodecForLocale().
Referenced by QTextCodec::codecForName(), GetPythonExeVersion(), and PythonConfig::initFromPythonExecutable().
qtCompatDropEventPos()
QPointF qtCompatDropEventPos (const QDropEvent * event) inline noexcept
Definition at line 826 of file QtCompat.h.
References event.
qtCompatDropEventPosInt()
QPoint qtCompatDropEventPosInt (const QDropEvent * event) inline noexcept
Definition at line 835 of file QtCompat.h.
qtCompatMapInsertMulti() [1/2]
template<typename Key , typename T > void qtCompatMapInsertMulti (QMap< Key, T > * map, const Key & key, const T & value)
Definition at line 854 of file QtCompat.h.
qtCompatMapInsertMulti() [2/2]
template<typename Key , typename T > void qtCompatMapInsertMulti (QMultiMap< Key, T > * map, const Key & key, const T & value)
Definition at line 864 of file QtCompat.h.
qtCompatMapUnite() [1/2]
template<typename Key , typename T > void qtCompatMapUnite (QMap< Key, T > * map, const QMap< Key, T > & other)
Definition at line 872 of file QtCompat.h.
qtCompatMapUnite() [2/2]
template<typename Key , typename T > void qtCompatMapUnite (QMultiMap< Key, T > * map, const QMultiMap< Key, T > & other)
Definition at line 878 of file QtCompat.h.
qtCompatMouseEventGlobalPos()
QPointF qtCompatMouseEventGlobalPos (const QMouseEvent * event) inline noexcept
Definition at line 788 of file QtCompat.h.
References event.
qtCompatMouseEventGlobalPosInt()
QPoint qtCompatMouseEventGlobalPosInt (const QMouseEvent * event) inline noexcept
Definition at line 807 of file QtCompat.h.
qtCompatMouseEventPos()
QPointF qtCompatMouseEventPos (const QMouseEvent * event) inline noexcept
Definition at line 779 of file QtCompat.h.
References event.
qtCompatMouseEventPosInt()
QPoint qtCompatMouseEventPosInt (const QMouseEvent * event) inline noexcept
Definition at line 797 of file QtCompat.h.
qtCompatQSetFromVector()
template<typename T > QSet<T> qtCompatQSetFromVector (const QVector< T > & vec)
Definition at line 1039 of file QtCompat.h.
References result.
Referenced by qSetFromVector().
qtCompatQVectorFromSet()
template<typename T > QVector<T> qtCompatQVectorFromSet (const QSet< T > & set)
Definition at line 1056 of file QtCompat.h.
References result.
Referenced by qVectorFromSet().
qtCompatRegExp()
QRegularExpression qtCompatRegExp (const QString & pattern) inline
Definition at line 183 of file QtCompat.h.
qtCompatRegExpCap()
QString qtCompatRegExpCap (const QRegularExpressionMatch & match, int nth = 0) inline
Definition at line 466 of file QtCompat.h.
qtCompatRegExpIndexIn()
int qtCompatRegExpIndexIn (const QRegularExpression & regex, const QString & str, int offset = 0) inline
Definition at line 452 of file QtCompat.h.
References offset.
qtCompatRegExpMatch()
bool qtCompatRegExpMatch (const QRegularExpression & regex, const QString & str) inline
Definition at line 446 of file QtCompat.h.
qtCompatRegExpMatchedLength()
int qtCompatRegExpMatchedLength (const QRegularExpressionMatch & match) inline noexcept
Definition at line 472 of file QtCompat.h.
qtCompatRegExpPos()
int qtCompatRegExpPos (const QRegularExpressionMatch & match, int nth = 0) inline noexcept
Definition at line 460 of file QtCompat.h.
qtCompatReplace() [1/4]
QString qtCompatReplace (const QString & str, const QRegularExpression & regex, const QString & after) inline
Definition at line 367 of file QtCompat.h.
References result.
qtCompatReplace() [2/4]
QString qtCompatReplace (const QString & str, const QString & pattern, const QString & after) inline
Definition at line 382 of file QtCompat.h.
References result.
qtCompatReplace() [3/4]
QString& qtCompatReplace (QString & str, const QRegularExpression & regex, const QString & after) inline
Definition at line 361 of file QtCompat.h.
qtCompatReplace() [4/4]
QString& qtCompatReplace (QString & str, const QString & pattern, const QString & after) inline
Definition at line 376 of file QtCompat.h.
qtCompatSetTabStopWidth()
void qtCompatSetTabStopWidth (QPlainTextEdit * edit, int width) inline
Definition at line 1010 of file QtCompat.h.
References width.
Referenced by PythonRepl::setupUI().
qtCompatSplit()
QStringList qtCompatSplit (const QString & str, const QRegularExpression & regex, Qt::SplitBehavior behavior = Qt::KeepEmptyParts) inline
Definition at line 188 of file QtCompat.h.
qtCompatSplitRef()
QtCompatStringRefList qtCompatSplitRef (const QString & str, QChar sep) inline
Definition at line 251 of file QtCompat.h.
References result.
Referenced by qtCompatSplitRefChar().
qtCompatSplitRefChar()
QtCompatStringRefList qtCompatSplitRefChar (const QString & str, QChar sep) inline
Definition at line 430 of file QtCompat.h.
References qtCompatSplitRef().
Referenced by GetPythonExeVersion(), LasSaveDialog::selectedVersion(), and Version::Version().
qtCompatSplitRegex()
QStringList qtCompatSplitRegex (const QString & str, const QString & pattern, Qt::SplitBehavior behavior = Qt::KeepEmptyParts) inline
Definition at line 308 of file QtCompat.h.
Referenced by ccGLMatrixTpl< T >::FromString(), ProfileLoader::Load(), SalomeHydroFilter::loadFile(), SinusxFilter::loadFile(), BundlerFilter::loadFileExtended(), and DistanceMapGenerationDlg::loadOverlaySymbols().
qtCompatStringRef() [1/2]
QStringView qtCompatStringRef (const QString & str) inline noexcept
Definition at line 231 of file QtCompat.h.
Referenced by PyVenvCfg::FromFile(), and GetPythonExeVersion().
qtCompatStringRef() [2/2]
QStringView qtCompatStringRef (const QString & str, int pos, int n = -1) inline noexcept
Definition at line 241 of file QtCompat.h.
qtCompatStringRefToString()
QString qtCompatStringRefToString (const QStringView & view) inline
Definition at line 236 of file QtCompat.h.
Referenced by Version::Version().
qtCompatVariantIsBool()
bool qtCompatVariantIsBool (const QVariant & var) inline noexcept
Definition at line 945 of file QtCompat.h.
qtCompatVariantIsDouble()
bool qtCompatVariantIsDouble (const QVariant & var) inline noexcept
Definition at line 941 of file QtCompat.h.
qtCompatVariantIsInt()
bool qtCompatVariantIsInt (const QVariant & var) inline noexcept
Definition at line 937 of file QtCompat.h.
qtCompatVariantIsList()
bool qtCompatVariantIsList (const QVariant & var) inline noexcept
Definition at line 949 of file QtCompat.h.
qtCompatVariantIsMap()
bool qtCompatVariantIsMap (const QVariant & var) inline noexcept
Definition at line 953 of file QtCompat.h.
qtCompatVariantIsNull()
bool qtCompatVariantIsNull (const QVariant & var) inline noexcept
Definition at line 928 of file QtCompat.h.
qtCompatVariantIsString()
bool qtCompatVariantIsString (const QVariant & var) inline noexcept
Definition at line 933 of file QtCompat.h.
qtCompatVariantIsValid()
bool qtCompatVariantIsValid (const QVariant & var) inline noexcept
Definition at line 924 of file QtCompat.h.
qtCompatVariantType()
QMetaType::Type qtCompatVariantType (const QVariant & var) inline noexcept
Definition at line 920 of file QtCompat.h.
qtCompatWheelEventDelta()
double qtCompatWheelEventDelta (const QWheelEvent * event) inline noexcept
Definition at line 751 of file QtCompat.h.
qtCompatWheelEventPos()
QPointF qtCompatWheelEventPos (const QWheelEvent * event) inline noexcept
Definition at line 760 of file QtCompat.h.
References event.
qVectorFromSet()
template<typename T > QVector<T> qVectorFromSet (const QSet< T > & set) inline
Definition at line 1078 of file QtCompat.h.
References qtCompatQVectorFromSet().