ACloudViewer: /root/ACloudViewer/plugins/core/IO/qPhotoscanIO/extern/quazip/quazip/quazip/quazipnewinfo.cpp File Reference
quazipnewinfo.cpp File Reference
#include "quazipnewinfo.h"
#include <string.h>
#include <QFileInfo>
Functions
static void QuaZipNewInfo_setPermissions (QuaZipNewInfo *info, QFile::Permissions perm, bool isDir, bool isSymLink=false)
template<typename FileInfo >
void QuaZipNewInfo_init (QuaZipNewInfo &self, const FileInfo &existing)
static void setNTFSTime (QByteArray &extra, const QDateTime &time, int position, int fineTicks)
Function Documentation
QuaZipNewInfo_init()
template<typename FileInfo > void QuaZipNewInfo_init (QuaZipNewInfo & self, const FileInfo & existing)
Definition at line 58 of file quazipnewinfo.cpp.
Referenced by QuaZipNewInfo::QuaZipNewInfo().
QuaZipNewInfo_setPermissions()
static void QuaZipNewInfo_setPermissions (QuaZipNewInfo * info, QFile::Permissions perm, bool isDir, bool isSymLink = false) static
Definition at line 31 of file quazipnewinfo.cpp.
References QuaZipNewInfo::externalAttr.
Referenced by QuaZipNewInfo::QuaZipNewInfo(), QuaZipNewInfo::setFilePermissions(), and QuaZipNewInfo::setPermissions().
setNTFSTime()
static void setNTFSTime (QByteArray & extra, const QDateTime & time, int position, int fineTicks) static
Definition at line 129 of file quazipnewinfo.cpp.
References length(), position, QUAZIP_EXTRA_NTFS_MAGIC, QUAZIP_EXTRA_NTFS_TIME_MAGIC, and type.
Referenced by QuaZipNewInfo::setFileNTFSaTime(), QuaZipNewInfo::setFileNTFScTime(), and QuaZipNewInfo::setFileNTFSmTime().