ACloudViewer: /root/ACloudViewer/plugins/core/IO/qPhotoscanIO/extern/quazip/quazip/quazip/quazipfileinfo.cpp File Reference
quazipfileinfo.cpp File Reference
#include "quazipfileinfo.h"
Functions
static QFile::Permissions permissionsFromExternalAttr (quint32 externalAttr)
static QDateTime getNTFSTime (const QByteArray &extra, int position, int *fineTicks)
Function Documentation
getNTFSTime()
static QDateTime getNTFSTime (const QByteArray & extra, int position, int * fineTicks) static
Definition at line 83 of file quazipfileinfo.cpp.
References length(), NULL, position, QUAZIP_EXTRA_NTFS_MAGIC, QUAZIP_EXTRA_NTFS_TIME_MAGIC, and type.
Referenced by QuaZipFileInfo64::getNTFSaTime(), QuaZipFileInfo64::getNTFScTime(), and QuaZipFileInfo64::getNTFSmTime().
permissionsFromExternalAttr()
static QFile::Permissions permissionsFromExternalAttr (quint32 externalAttr) static
Definition at line 27 of file quazipfileinfo.cpp.
Referenced by QuaZipFileInfo::getPermissions(), and QuaZipFileInfo64::getPermissions().