ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qVoxFall/src/qVoxFallDialog.cpp File Reference
qVoxFallDialog.cpp File Reference
#include "qVoxFallDialog.h"
#include <ecvMainAppInterface.h>
#include <ecvQtHelpers.h>
#include <ecvDisplayTools.h>
#include <ecvMesh.h>
#include <QComboBox>
#include <QMainWindow>
#include <QThread>
Functions
static QString GetEntityName (ccHObject *obj)
static ccMesh * GetMeshFromCombo (QComboBox *comboBox, ccHObject *dbRoot)
Function Documentation
GetEntityName()
static QString GetEntityName (ccHObject * obj) static
Definition at line 24 of file qVoxFallDialog.cpp.
References ccObject::getName(), ccObject::getUniqueID(), and name.
Referenced by qVoxFallDialog::setMeshes().
GetMeshFromCombo()
static ccMesh* GetMeshFromCombo (QComboBox * comboBox, ccHObject * dbRoot) static
Definition at line 37 of file qVoxFallDialog.cpp.
References ccHObject::find(), ccObject::isA(), and CV_TYPES::MESH.