ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qVoxFall/src/qVoxFallProcess.cpp File Reference
qVoxFallProcess.cpp File Reference
#include "qVoxFallProcess.h"
#include <atomic>
#include <unordered_set>
#include "qVoxFallDialog.h"
#include "qVoxFallTools.h"
#include <CloudSamplingTools.h>
#include "Grid3D.h"
#include <ecvMainAppInterface.h>
#include <ecvQtHelpers.h>
#include <ecvGenericPointCloud.h>
#include <ecvHObjectCaster.h>
#include <ecvMesh.h>
#include <ecvOctree.h>
#include <ecvOctreeProxy.h>
#include <ecvPointCloud.h>
#include <ecvProgressDialog.h>
#include <ecvScalarField.h>
#include <QApplication>
#include <QElapsedTimer>
#include <QMessageBox>
#include <QtConcurrentMap>
#include <QtCore>
#include <QtGui>
Classes
struct VoxFallParams
Functions
bool InitializeOutputCloud (int voxelCount, GenericProgressCallback *progressCb=nullptr)
void GetVoxelOccupancy (const Tuple3i &cellPos, unsigned n)
void GetVoxelOccupancyBefore (const Tuple3i &cellPos, unsigned n)
bool ClusterEmptySpace (int maxThreads, int voxelCount, GenericProgressCallback *progressCb=nullptr)
bool ComputeClusterVolume (int maxThreads, int clusterCount, ccHObject *clusterGroup=nullptr)
Variables
static const char OCCUPANCY_SF_NAME [] = "Occupancy"
Default name for VoxFall scalar fields.
static const char CLUSTER_SF_NAME [] = "Cluster ID"
static const char CHANGE_TYPE_SF_NAME [] = "Loss/gain"
static const char VOLUME_SF_NAME [] = "Volume (m3)"
static const char UNCERTAINTY_SF_NAME [] = "Uncertainty (%)"
static VoxFallParams s_VoxFallParams
Function Documentation
ClusterEmptySpace()
bool ClusterEmptySpace (int maxThreads, int voxelCount, GenericProgressCallback * progressCb = nullptr)
Definition at line 141 of file qVoxFallProcess.cpp.
References VoxFallParams::clusterLabel, VoxFallParams::clusterSF, VoxFallParams::emptyVoxelCount, qVoxFallTools::FindAdjacents(), cloudViewer::ScalarField::getValue(), qVoxFallTools::Grid2Index(), qVoxFallTools::Index2Grid(), VoxFallParams::isEmpty, VoxFallParams::nbs, NN, nProgress, cloudViewer::NormalizedProgress::oneStep(), s_VoxFallParams, cloudViewer::ScalarField::setValue(), and VoxFallParams::steps.
Referenced by qVoxFallProcess::Compute().
ComputeClusterVolume()
bool ComputeClusterVolume (int maxThreads, int clusterCount, ccHObject * clusterGroup = nullptr)
Definition at line 256 of file qVoxFallProcess.cpp.
References VoxFallParams::bbDims, VoxFallParams::centroid, VoxFallParams::clusterIndices, VoxFallParams::clusterOutterVoxelCount, VoxFallParams::clusters, count, VoxFallParams::currentLabel, error(), VoxFallParams::exportBlocksAsMeshes, VoxFallParams::exportLossGain, qVoxFallTools::Index2Grid(), VoxFallParams::isEmpty, VoxFallParams::maxBound, VoxFallParams::minBound, VoxFallParams::nbs, VoxFallParams::nonEmptyVoxelsVisited, VoxFallParams::nProgress, cloudViewer::NormalizedProgress::oneStep(), VoxFallParams::processCanceled, s_VoxFallParams, VoxFallParams::steps, VoxFallParams::voxelSize, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by qVoxFallProcess::Compute().
GetVoxelOccupancy()
void GetVoxelOccupancy (const Tuple3i & cellPos, unsigned n)
Definition at line 131 of file qVoxFallProcess.cpp.
References qVoxFallTools::Grid2Index(), VoxFallParams::isEmpty, s_VoxFallParams, and VoxFallParams::steps.
Referenced by qVoxFallProcess::Compute().
GetVoxelOccupancyBefore()
void GetVoxelOccupancyBefore (const Tuple3i & cellPos, unsigned n)
Definition at line 136 of file qVoxFallProcess.cpp.
References qVoxFallTools::Grid2Index(), VoxFallParams::isEmptyBefore, s_VoxFallParams, and VoxFallParams::steps.
Referenced by qVoxFallProcess::Compute().
InitializeOutputCloud()
bool InitializeOutputCloud (int voxelCount, GenericProgressCallback * progressCb = nullptr)
Definition at line 98 of file qVoxFallProcess.cpp.
References cloudViewer::PointCloudTpl< T >::addPoint(), qVoxFallTools::Index2Grid(), VoxFallParams::minBound, nProgress, cloudViewer::NormalizedProgress::oneStep(), s_VoxFallParams, VoxFallParams::steps, VoxFallParams::voxelSize, VoxFallParams::voxfall, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Referenced by qVoxFallProcess::Compute().
Variable Documentation
CHANGE_TYPE_SF_NAME
const char CHANGE_TYPE_SF_NAME[] = "Loss/gain" static
Definition at line 54 of file qVoxFallProcess.cpp.
Referenced by qVoxFallProcess::Compute().
CLUSTER_SF_NAME
const char CLUSTER_SF_NAME[] = "Cluster ID" static
Definition at line 53 of file qVoxFallProcess.cpp.
Referenced by qVoxFallProcess::Compute().
OCCUPANCY_SF_NAME
const char OCCUPANCY_SF_NAME[] = "Occupancy" static
Default name for VoxFall scalar fields.
Definition at line 52 of file qVoxFallProcess.cpp.
s_VoxFallParams
VoxFallParams s_VoxFallParams static
Definition at line 96 of file qVoxFallProcess.cpp.
Referenced by ClusterEmptySpace(), qVoxFallProcess::Compute(), ComputeClusterVolume(), GetVoxelOccupancy(), GetVoxelOccupancyBefore(), and InitializeOutputCloud().
UNCERTAINTY_SF_NAME
const char UNCERTAINTY_SF_NAME[] = "Uncertainty (%)" static
Definition at line 56 of file qVoxFallProcess.cpp.
Referenced by qVoxFallProcess::Compute().
VOLUME_SF_NAME
const char VOLUME_SF_NAME[] = "Volume (m3)" static
Definition at line 55 of file qVoxFallProcess.cpp.
Referenced by qVoxFallProcess::Compute().