ACloudViewer: /root/ACloudViewer/libs/PCLEngine/VTKExtensions/Widgets/QVTKWidgetCustom.cpp File Reference
QVTKWidgetCustom.cpp File Reference
#include "QVTKWidgetCustom.h"
#include "VtkUtils/rendererslayoutalgo.h"
#include "VtkUtils/utils.h"
#include "VtkUtils/vtkutils.h"
#include <CVConst.h>
#include <CVLog.h>
#include <CVTools.h>
#include <vtkAbstractPicker.h>
#include <vtkAngleRepresentation2D.h>
#include <vtkAxesActor.h>
#include <vtkCamera.h>
#include <vtkClipPolyData.h>
#include <vtkColorTransferFunction.h>
#include <vtkConeSource.h>
#include <vtkDelaunay2D.h>
#include <vtkGenericOpenGLRenderWindow.h>
#include <vtkIdFilter.h>
#include <vtkImageData.h>
#include <vtkLogoRepresentation.h>
#include <vtkLogoWidget.h>
#include <vtkLookupTable.h>
#include <vtkOrientationMarkerWidget.h>
#include <vtkPNGReader.h>
#include <vtkProperty2D.h>
#include <vtkRenderWindow.h>
#include <vtkRenderer.h>
#include <vtkRendererCollection.h>
#include <vtkScalarBarActor.h>
#include <vtkScalarBarRepresentation.h>
#include <vtkScalarBarWidget.h>
#include <vtkTransform.h>
#include <vtkVertexGlyphFilter.h>
#include <ecvDisplayTools.h>
#include <ecvInteractor.h>
#include <ecvPointCloud.h>
#include <ecvPolyline.h>
#include <QApplication>
#include <QCoreApplication>
#include <QHBoxLayout>
#include <QLayout>
#include <QMainWindow>
#include <QMessageBox>
#include <QMimeData>
#include <QPushButton>
#include <QSettings>
#include <QThread>
#include <QTimer>
#include <QTouchEvent>
#include <QWheelEvent>
#include <QWidget>
#include "ScaleBarWidget.h"
Macros
#define VTK_CREATE(TYPE, NAME) vtkSmartPointer<TYPE> NAME = vtkSmartPointer<TYPE>::New()
Functions
static int columnCount (int count)
bool IsCalledFromMainThread ()
Variables
static const int CC_MAX_PICKING_CLICK_DURATION_MS = 350
Macro Definition Documentation
VTK_CREATE
#define VTK_CREATE (TYPE, NAME) vtkSmartPointer<TYPE> NAME = vtkSmartPointer<TYPE>::New()
Definition at line 76 of file QVTKWidgetCustom.cpp.
Function Documentation
columnCount()
static int columnCount (int count) static
Definition at line 116 of file QVTKWidgetCustom.cpp.
References count.
Referenced by QCPLayoutGrid::elementCount(), and Widgets::ColorPickerPopup::keyPressEvent().
IsCalledFromMainThread()
bool IsCalledFromMainThread ()
Definition at line 281 of file QVTKWidgetCustom.cpp.
Referenced by QVTKWidgetCustom::updateScene().
Variable Documentation
CC_MAX_PICKING_CLICK_DURATION_MS
const int CC_MAX_PICKING_CLICK_DURATION_MS = 350 static
Definition at line 176 of file QVTKWidgetCustom.cpp.
Referenced by QVTKWidgetCustom::mouseReleaseEvent().