ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/util/random_test.cc File Reference
random_test.cc File Reference
#include "util/testing.h"
#include <numeric>
#include "util/math.h"
#include "util/random.h"
Macros
#define TEST_NAME "util/random"
Functions
BOOST_AUTO_TEST_CASE (TestPRNGSeed)
BOOST_AUTO_TEST_CASE (TestRepeatability)
BOOST_AUTO_TEST_CASE (TestRandomInteger)
BOOST_AUTO_TEST_CASE (TestRandomReal)
BOOST_AUTO_TEST_CASE (TestRandomGaussian)
BOOST_AUTO_TEST_CASE (TestShuffleNone)
BOOST_AUTO_TEST_CASE (TestShuffleAll)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "util/random"
Definition at line 32 of file random_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/7]
BOOST_AUTO_TEST_CASE (TestPRNGSeed)
Definition at line 42 of file random_test.cc.
References colmap::PRNG, and colmap::SetPRNGSeed().
BOOST_AUTO_TEST_CASE() [2/7]
BOOST_AUTO_TEST_CASE (TestRandomGaussian)
Definition at line 93 of file random_test.cc.
References e, colmap::Mean(), colmap::RandomGaussian(), colmap::SetPRNGSeed(), and colmap::StdDev().
BOOST_AUTO_TEST_CASE() [3/7]
BOOST_AUTO_TEST_CASE (TestRandomInteger)
Definition at line 77 of file random_test.cc.
References colmap::RandomInteger(), and colmap::SetPRNGSeed().
BOOST_AUTO_TEST_CASE() [4/7]
BOOST_AUTO_TEST_CASE (TestRandomReal)
Definition at line 85 of file random_test.cc.
References colmap::RandomReal(), and colmap::SetPRNGSeed().
BOOST_AUTO_TEST_CASE() [5/7]
BOOST_AUTO_TEST_CASE (TestRepeatability)
Definition at line 50 of file random_test.cc.
References colmap::RandomInteger(), and colmap::SetPRNGSeed().
BOOST_AUTO_TEST_CASE() [6/7]
BOOST_AUTO_TEST_CASE (TestShuffleAll)
Definition at line 118 of file random_test.cc.
References colmap::SetPRNGSeed(), and colmap::Shuffle().
BOOST_AUTO_TEST_CASE() [7/7]
BOOST_AUTO_TEST_CASE (TestShuffleNone)
Definition at line 106 of file random_test.cc.
References colmap::SetPRNGSeed(), and colmap::Shuffle().