ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/reconstruction_manager_test.cc File Reference
reconstruction_manager_test.cc File Reference
#include "util/testing.h"
#include "base/reconstruction_manager.h"
Macros
#define TEST_NAME "base/reconstruction_manager"
Functions
BOOST_AUTO_TEST_CASE (TestEmpty)
BOOST_AUTO_TEST_CASE (TestAddGet)
BOOST_AUTO_TEST_CASE (TestDelete)
BOOST_AUTO_TEST_CASE (TestClear)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/reconstruction_manager"
Definition at line 32 of file reconstruction_manager_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (TestAddGet)
Definition at line 44 of file reconstruction_manager_test.cc.
References colmap::ReconstructionManager::Add(), colmap::ReconstructionManager::Get(), colmap::Reconstruction::NumCameras(), colmap::Reconstruction::NumImages(), colmap::Reconstruction::NumPoints3D(), and colmap::ReconstructionManager::Size().
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (TestClear)
Definition at line 71 of file reconstruction_manager_test.cc.
References colmap::ReconstructionManager::Add(), colmap::ReconstructionManager::Clear(), and colmap::ReconstructionManager::Size().
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (TestDelete)
Definition at line 57 of file reconstruction_manager_test.cc.
References colmap::ReconstructionManager::Add(), colmap::ReconstructionManager::Delete(), and colmap::ReconstructionManager::Size().
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (TestEmpty)
Definition at line 39 of file reconstruction_manager_test.cc.
References colmap::ReconstructionManager::Size().