ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/Runtime/Runtime.cpp File Reference
Runtime.cpp File Reference
#include <pybind11/embed.h>
#include <pybind11/pybind11.h>
#include <QCoreApplication>
#include <QEventLoop>
#include <QtConcurrent>
#include <ecvCommandLineInterface.h>
#include <ecvMainAppInterface.h>
#include "Consoles.h"
#include "Runtime.h"
#include "Threading.h"
#include "ccGuiPythonInstance.h"
Classes
class Runtime::PythonPluginInterface
Interface that 'class-style' PythonPlugin must implement to be loaded.
class Runtime::PythonPluginTrampoline
Namespaces
Runtime
Functions
ccGuiPythonInstance * Runtime::GetInstance () noexcept
ccCommandLineInterface * Runtime::GetCmdLineInstance () noexcept
void Runtime::setMainAppInterfaceInstance (ecvMainAppInterface *appInterface) noexcept(false)
void Runtime::unsetMainAppInterfaceInstance () noexcept
Unsets the app interface pointer.
void Runtime::setCmdLineInterfaceInstance (ccCommandLineInterface *cmdLine) noexcept
void Runtime::unsetCmdLineInterfaceInstance () noexcept
Unsets the pointer to the cmdline app interface.
PYBIND11_EMBEDDED_MODULE (ccinternals, m)
void define_ccGUIPythonInstance (py::module &)
void define_ccCommandLine (py::module &)
PYBIND11_EMBEDDED_MODULE (pycc_runtime, m)
Variables
static ccGuiPythonInstance * Runtime::s_pythonInstance {nullptr}
static ccCommandLineInterface * Runtime::s_cmdLineInstance {nullptr}
Function Documentation
define_ccCommandLine()
void define_ccCommandLine (py::module & m)
Definition at line 23 of file ccCommandLine.cpp.
References CLEntityDesc::basename, CLOUD, ccCommandLineInterface::clouds(), ccCommandLineInterface::GlobalShiftOptions::customGlobalShift, ccCommandLineInterface::exportEntity(), filename, CLEntityDesc::getEntity(), ccCommandLineInterface::getExportFilename(), GROUP, CLGroupDesc::groupEntity, CLEntityDesc::indexInFile, MESH, CLMeshDesc::mesh, ccCommandLineInterface::meshes(), ccCommandLineInterface::GlobalShiftOptions::mode, ccCommandLineInterface::NoOptions, CLEntityDesc::path, CLCloudDesc::pc, ccCommandLineInterface::saveClouds(), and ccCommandLineInterface::saveMeshes().
Referenced by PYBIND11_EMBEDDED_MODULE().
define_ccGUIPythonInstance()
void define_ccGUIPythonInstance (py::module & m)
Definition at line 201 of file ccGuiPythonInstance.cpp.
References ccGuiPythonInstance::addToDB(), ccGuiPythonInstance::app(), ccGuiPythonInstance::dbRootObject(), ccGuiPythonInstance::disableAll(), ccGuiPythonInstance::enableAll(), ccGuiPythonInstance::freezeUI(), ccGuiPythonInstance::getMainWindow(), ccGuiPythonInstance::getSelectedEntities(), ccGuiPythonInstance::haveOneSelection(), ccGuiPythonInstance::haveSelection(), ccGuiPythonInstance::loadFile(), ccGuiPythonInstance::redrawAll(), ccGuiPythonInstance::refreshAll(), ccGuiPythonInstance::removeFromDB(), ccGuiPythonInstance::setSelectedInDB(), and ccGuiPythonInstance::updateUI().
Referenced by PYBIND11_EMBEDDED_MODULE().
PYBIND11_EMBEDDED_MODULE() [1/2]
PYBIND11_EMBEDDED_MODULE (ccinternals , m)
Definition at line 117 of file Runtime.cpp.
References ccConsoleOutput::flush(), ListWidgetConsole::flush(), ccConsoleOutput::isatty(), ListWidgetConsole::isatty(), ccConsoleOutput::write(), and ListWidgetConsole::write().
PYBIND11_EMBEDDED_MODULE() [2/2]
PYBIND11_EMBEDDED_MODULE (pycc_runtime , m)
Definition at line 144 of file Runtime.cpp.
References call_fn(), define_ccCommandLine(), define_ccGUIPythonInstance(), Runtime::PythonPluginInterface::getActions(), Runtime::GetCmdLineInstance(), Runtime::PythonPluginInterface::getIcon(), and Runtime::GetInstance().