ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPCL/PclAlgorithms/Segmentations/SACSegmentation.cpp File Reference
SACSegmentation.cpp File Reference
#include "SACSegmentation.h"
#include <Utils/PCLCloud.h>
#include <Utils/cc2sm.h>
#include <Utils/sm2cc.h>
#include "PclUtils/PCLModules.h"
#include "Tools/Common/ecvTools.h"
#include "dialogs/SACSegmentationDlg.h"
#include <ecvPointCloud.h>
#include <ecvMainAppInterface.h>
#include <QMainWindow>
#include <iostream>
#include <sstream>
Functions
int extractRecursive (PointCloudT::Ptr xyzCloud, PointCloudT::Ptr cloudRemained, std::vector< PointCloudT::Ptr > &cloudExtractions, int maxIterations, float probability, float minRadiusLimits, float maxRadiusLimits, float distanceThreshold, int methodType, int modelType, float normalDisWeight, float maxRemainingRatio, bool exportExtraction, bool recursive=false, ecvMainAppInterface *app=nullptr)
Function Documentation
extractRecursive()
int extractRecursive (PointCloudT::Ptr xyzCloud, PointCloudT::Ptr cloudRemained, std::vector< PointCloudT::Ptr > & cloudExtractions, int maxIterations, float probability, float minRadiusLimits, float maxRadiusLimits, float distanceThreshold, int methodType, int modelType, float normalDisWeight, float maxRemainingRatio, bool exportExtraction, bool recursive = false, ecvMainAppInterface * app = nullptr)
Definition at line 202 of file SACSegmentation.cpp.
References ecvMainAppInterface::dispToConsole(), PCLModules::ExtractIndicesFilter< PointT >(), PCLModules::GetSACSegmentation(), and ecvMainAppInterface::WRN_CONSOLE_MESSAGE.
Referenced by SACSegmentation::compute().