ACloudViewer: /root/ACloudViewer/libs/CV_io/extern/shapelib/safileio.c File Reference
safileio.c File Reference
#include "shapefil.h"
#include <math.h>
#include <limits.h>
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
Functions
static const char * cvsid_aw ()
SAFile SADFOpen (const char *pszFilename, const char *pszAccess)
SAOffset SADFRead (void *p, SAOffset size, SAOffset nmemb, SAFile file)
SAOffset SADFWrite (void *p, SAOffset size, SAOffset nmemb, SAFile file)
SAOffset SADFSeek (SAFile file, SAOffset offset, int whence)
SAOffset SADFTell (SAFile file)
int SADFFlush (SAFile file)
int SADFClose (SAFile file)
int SADRemove (const char *filename)
void SADError (const char *message)
void SASetupDefaultHooks (SAHooks *psHooks)
Variables
static const char cpl_cvsid [] = "$Id$"
Function Documentation
cvsid_aw()
static const char* cvsid_aw () static
Definition at line 77 of file safileio.c.
SADError()
void SADError (const char * message)
Definition at line 174 of file safileio.c.
Referenced by SASetupDefaultHooks().
SADFClose()
int SADFClose (SAFile file)
Definition at line 154 of file safileio.c.
Referenced by SASetupDefaultHooks().
SADFFlush()
int SADFFlush (SAFile file)
Definition at line 144 of file safileio.c.
Referenced by SASetupDefaultHooks().
SADFOpen()
SAFile SADFOpen (const char * pszFilename, const char * pszAccess)
Definition at line 92 of file safileio.c.
Referenced by SASetupDefaultHooks().
SADFRead()
SAOffset SADFRead (void * p, SAOffset size, SAOffset nmemb, SAFile file)
Definition at line 102 of file safileio.c.
References size.
Referenced by SASetupDefaultHooks().
SADFSeek()
SAOffset SADFSeek (SAFile file, SAOffset offset, int whence)
Definition at line 124 of file safileio.c.
References offset.
Referenced by SASetupDefaultHooks().
SADFTell()
SAOffset SADFTell (SAFile file)
Definition at line 134 of file safileio.c.
Referenced by SASetupDefaultHooks().
SADFWrite()
SAOffset SADFWrite (void * p, SAOffset size, SAOffset nmemb, SAFile file)
Definition at line 113 of file safileio.c.
References size.
Referenced by SASetupDefaultHooks().
SADRemove()
int SADRemove (const char * filename)
Definition at line 164 of file safileio.c.
References filename.
Referenced by SASetupDefaultHooks().
SASetupDefaultHooks()
void SASetupDefaultHooks (SAHooks * psHooks)
Definition at line 184 of file safileio.c.
References SAHooks::Atof, SAHooks::Error, SAHooks::FClose, SAHooks::FFlush, SAHooks::FOpen, SAHooks::FRead, SAHooks::FSeek, SAHooks::FTell, SAHooks::FWrite, SAHooks::Remove, SADError(), SADFClose(), SADFFlush(), SADFOpen(), SADFRead(), SADFSeek(), SADFTell(), SADFWrite(), and SADRemove().
Referenced by DBFCreateEx(), DBFOpen(), SHPCreate(), SHPOpen(), SHPOpenDiskTree(), SHPWriteTree(), and SHPWriteTreeLL().
Variable Documentation
cpl_cvsid
const char cpl_cvsid[] = "$Id$" static
Definition at line 77 of file safileio.c.