ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/scene_clustering_test.cc File Reference
scene_clustering_test.cc File Reference
#include "util/testing.h"
#include <set>
#include "base/database.h"
#include "base/scene_clustering.h"
Macros
#define TEST_NAME "base/scene_clustering"
Functions
BOOST_AUTO_TEST_CASE (TestEmpty)
BOOST_AUTO_TEST_CASE (TestOneLevel)
BOOST_AUTO_TEST_CASE (TestTwoLevels)
BOOST_AUTO_TEST_CASE (TestThreeLevels)
BOOST_AUTO_TEST_CASE (TestThreeLevelsMultipleImages)
BOOST_AUTO_TEST_CASE (TestOneOverlap)
BOOST_AUTO_TEST_CASE (TestTwoOverlap)
BOOST_AUTO_TEST_CASE (TestThreeFlatClusters)
BOOST_AUTO_TEST_CASE (TestThreeFlatClustersTwoOverlap)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/scene_clustering"
Definition at line 32 of file scene_clustering_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/9]
BOOST_AUTO_TEST_CASE (TestEmpty)
Definition at line 42 of file scene_clustering_test.cc.
References colmap::SceneClustering::Options::branching, colmap::SceneClustering::Cluster::child_clusters, colmap::SceneClustering::GetLeafClusters(), colmap::SceneClustering::GetRootCluster(), colmap::SceneClustering::Cluster::image_ids, colmap::SceneClustering::Options::image_overlap, colmap::SceneClustering::Options::leaf_max_num_images, and colmap::SceneClustering::Partition().
BOOST_AUTO_TEST_CASE() [2/9]
BOOST_AUTO_TEST_CASE (TestOneLevel)
Definition at line 58 of file scene_clustering_test.cc.
References colmap::SceneClustering::Options::branching, colmap::SceneClustering::Cluster::child_clusters, colmap::SceneClustering::GetLeafClusters(), colmap::SceneClustering::GetRootCluster(), colmap::SceneClustering::Cluster::image_ids, colmap::SceneClustering::Options::image_overlap, colmap::SceneClustering::Options::leaf_max_num_images, and colmap::SceneClustering::Partition().
BOOST_AUTO_TEST_CASE() [3/9]
BOOST_AUTO_TEST_CASE (TestOneOverlap)
Definition at line 150 of file scene_clustering_test.cc.
References colmap::SceneClustering::Options::branching, colmap::SceneClustering::GetLeafClusters(), colmap::SceneClustering::GetRootCluster(), colmap::SceneClustering::Cluster::image_ids, colmap::SceneClustering::Options::image_overlap, colmap::SceneClustering::Options::leaf_max_num_images, and colmap::SceneClustering::Partition().
BOOST_AUTO_TEST_CASE() [4/9]
BOOST_AUTO_TEST_CASE (TestThreeFlatClusters)
Definition at line 218 of file scene_clustering_test.cc.
References colmap::SceneClustering::Options::branching, colmap::SceneClustering::GetLeafClusters(), colmap::SceneClustering::GetRootCluster(), colmap::SceneClustering::Cluster::image_ids, colmap::SceneClustering::Options::image_overlap, colmap::SceneClustering::Options::is_hierarchical, and colmap::SceneClustering::Partition().
BOOST_AUTO_TEST_CASE() [5/9]
BOOST_AUTO_TEST_CASE (TestThreeFlatClustersTwoOverlap)
Definition at line 258 of file scene_clustering_test.cc.
References colmap::SceneClustering::Options::branching, colmap::SceneClustering::GetLeafClusters(), colmap::SceneClustering::GetRootCluster(), colmap::SceneClustering::Cluster::image_ids, colmap::SceneClustering::Options::image_overlap, colmap::SceneClustering::Options::is_hierarchical, and colmap::SceneClustering::Partition().
BOOST_AUTO_TEST_CASE() [6/9]
BOOST_AUTO_TEST_CASE (TestThreeLevels)
Definition at line 98 of file scene_clustering_test.cc.
References colmap::SceneClustering::Options::branching, colmap::SceneClustering::GetLeafClusters(), colmap::SceneClustering::GetRootCluster(), colmap::SceneClustering::Cluster::image_ids, colmap::SceneClustering::Options::image_overlap, colmap::SceneClustering::Options::leaf_max_num_images, and colmap::SceneClustering::Partition().
BOOST_AUTO_TEST_CASE() [7/9]
BOOST_AUTO_TEST_CASE (TestThreeLevelsMultipleImages)
Definition at line 123 of file scene_clustering_test.cc.
References colmap::SceneClustering::Options::branching, colmap::SceneClustering::GetLeafClusters(), colmap::SceneClustering::GetRootCluster(), colmap::SceneClustering::Cluster::image_ids, colmap::SceneClustering::Options::image_overlap, colmap::SceneClustering::Options::leaf_max_num_images, and colmap::SceneClustering::Partition().
BOOST_AUTO_TEST_CASE() [8/9]
BOOST_AUTO_TEST_CASE (TestTwoLevels)
Definition at line 78 of file scene_clustering_test.cc.
References colmap::SceneClustering::Options::branching, colmap::SceneClustering::Cluster::child_clusters, colmap::SceneClustering::GetLeafClusters(), colmap::SceneClustering::GetRootCluster(), colmap::SceneClustering::Cluster::image_ids, colmap::SceneClustering::Options::image_overlap, colmap::SceneClustering::Options::leaf_max_num_images, and colmap::SceneClustering::Partition().
BOOST_AUTO_TEST_CASE() [9/9]
BOOST_AUTO_TEST_CASE (TestTwoOverlap)
Definition at line 183 of file scene_clustering_test.cc.
References colmap::SceneClustering::Options::branching, colmap::SceneClustering::GetLeafClusters(), colmap::SceneClustering::GetRootCluster(), colmap::SceneClustering::Cluster::image_ids, colmap::SceneClustering::Options::image_overlap, colmap::SceneClustering::Options::leaf_max_num_images, and colmap::SceneClustering::Partition().