ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/sfm.c File Reference
sfm.c File Reference
#include "metis.h"
Functions
void FM_2WayNodeRefine (CtrlType *ctrl, GraphType *graph, float ubfactor, int npasses)
void FM_2WayNodeRefine2 (CtrlType *ctrl, GraphType *graph, float ubfactor, int npasses)
void FM_2WayNodeRefineEqWgt (CtrlType *ctrl, GraphType *graph, int npasses)
void FM_2WayNodeRefine_OneSided (CtrlType *ctrl, GraphType *graph, float ubfactor, int npasses)
void FM_2WayNodeBalance (CtrlType *ctrl, GraphType *graph, float ubfactor)
int ComputeMaxNodeGain (int nvtxs, idxtype *xadj, idxtype *adjncy, idxtype *vwgt)
Function Documentation
ComputeMaxNodeGain()
int ComputeMaxNodeGain (int nvtxs, idxtype * xadj, idxtype * adjncy, idxtype * vwgt)
Definition at line 1051 of file sfm.c.
References max().
Referenced by FM_2WayNodeBalance(), FM_2WayNodeRefine(), FM_2WayNodeRefine2(), FM_2WayNodeRefine_OneSided(), and FM_2WayNodeRefineEqWgt().
FM_2WayNodeBalance()
void FM_2WayNodeBalance (CtrlType * ctrl, GraphType * graph, float ubfactor)
Definition at line 918 of file sfm.c.
References abs(), graphdef::adjncy, ASSERT, ASSERTP, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckNodeBnd, CheckNodePartitionParams, ComputeMaxNodeGain(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, nrinfodef::edegrees, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, graphdef::mincut, graphdef::nbnd, graphdef::nrinfo, graphdef::nvtxs, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueUpdateUp, graphdef::pwgts, RandomPermute, graphdef::vwgt, graphdef::where, and graphdef::xadj.
FM_2WayNodeRefine()
void FM_2WayNodeRefine (CtrlType * ctrl, GraphType * graph, float ubfactor, int npasses)
Definition at line 21 of file sfm.c.
References abs(), graphdef::adjncy, amin, ASSERT, ASSERTP, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckNodeBnd, CheckNodePartitionParams, ComputeMaxNodeGain(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, nrinfodef::edegrees, idxset, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, graphdef::nrinfo, graphdef::nvtxs, OFLAG_COMPRESS, controldef::oflags, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueSeeMax, PQueueUpdate, graphdef::pwgts, RandomPermute, graphdef::vwgt, graphdef::where, and graphdef::xadj.
FM_2WayNodeRefine2()
void FM_2WayNodeRefine2 (CtrlType * ctrl, GraphType * graph, float ubfactor, int npasses)
Definition at line 256 of file sfm.c.
References abs(), graphdef::adjncy, amin, ASSERT, ASSERTP, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckNodeBnd, CheckNodePartitionParams, ComputeMaxNodeGain(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, nrinfodef::edegrees, idxset, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, graphdef::nrinfo, graphdef::nvtxs, OFLAG_COMPRESS, controldef::oflags, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueSeeMax, PQueueUpdate, graphdef::pwgts, RandomPermute, graphdef::vwgt, graphdef::where, and graphdef::xadj.
FM_2WayNodeRefine_OneSided()
void FM_2WayNodeRefine_OneSided (CtrlType * ctrl, GraphType * graph, float ubfactor, int npasses)
Definition at line 717 of file sfm.c.
References abs(), graphdef::adjncy, amin, ASSERT, ASSERTP, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckNodeBnd, CheckNodePartitionParams, ComputeMaxNodeGain(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, nrinfodef::edegrees, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, graphdef::nrinfo, graphdef::nvtxs, OFLAG_COMPRESS, controldef::oflags, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdateUp, graphdef::pwgts, RandomPermute, graphdef::vwgt, graphdef::where, and graphdef::xadj.
FM_2WayNodeRefineEqWgt()
void FM_2WayNodeRefineEqWgt (CtrlType * ctrl, GraphType * graph, int npasses)
Definition at line 493 of file sfm.c.
References abs(), graphdef::adjncy, amin, ASSERT, ASSERTP, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, CheckNodeBnd, CheckNodePartitionParams, ComputeMaxNodeGain(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, nrinfodef::edegrees, idxset, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, graphdef::nrinfo, graphdef::nvtxs, OFLAG_COMPRESS, controldef::oflags, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueSeeMax, PQueueUpdate, graphdef::pwgts, RandomPermute, graphdef::vwgt, graphdef::where, and graphdef::xadj.