ACloudViewer: /root/ACloudViewer/libs/CV_io/extern/shapelib/shapefil.h File Reference
shapefil.h File Reference
#include <stdio.h>
Classes
struct SAHooks
struct SHPInfo
struct tagSHPObject
struct shape_tree_node
struct SHPTree
struct DBFInfo
Macros
#define TRIM_DBF_WHITESPACE
#define DISABLE_MULTIPATCH_MEASURE
#define SHPAPI_CALL
#define SHPAPI_CALL1(x) x SHPAPI_CALL
#define SHP_CVSID(string)
#define SHPT_NULL 0
#define SHPT_POINT 1
#define SHPT_ARC 3
#define SHPT_POLYGON 5
#define SHPT_MULTIPOINT 8
#define SHPT_POINTZ 11
#define SHPT_ARCZ 13
#define SHPT_POLYGONZ 15
#define SHPT_MULTIPOINTZ 18
#define SHPT_POINTM 21
#define SHPT_ARCM 23
#define SHPT_POLYGONM 25
#define SHPT_MULTIPOINTM 28
#define SHPT_MULTIPATCH 31
#define SHPP_TRISTRIP 0
#define SHPP_TRIFAN 1
#define SHPP_OUTERRING 2
#define SHPP_INNERRING 3
#define SHPP_FIRSTRING 4
#define SHPP_RING 5
#define MAX_SUBNODE 4
#define MAX_DEFAULT_TREE_DEPTH 12
#define XBASE_FLDHDR_SZ 32
#define XBASE_FLDNAME_LEN_READ 11
#define XBASE_FLDNAME_LEN_WRITE 10
#define XBASE_FLD_MAX_WIDTH 255
Typedefs
typedef int * SAFile
typedef unsigned long SAOffset
typedef struct tagSHPObject SHPObject
typedef SHPInfo * SHPHandle
typedef struct shape_tree_node SHPTreeNode
typedef struct SHPDiskTreeInfo * SHPTreeDiskHandle
typedef struct SBNSearchInfo * SBNSearchHandle
typedef DBFInfo * DBFHandle
Enumerations
enum DBFFieldType {
FTString , FTInteger , FTDouble , FTLogical ,
FTDate , FTInvalid
}
Functions
void SASetupDefaultHooks (SAHooks *psHooks)
SHPHandle SHPOpen (const char *pszShapeFile, const char *pszAccess)
SHPHandle SHPOpenLL (const char *pszShapeFile, const char *pszAccess, SAHooks *psHooks)
SHPHandle SHPOpenLLEx (const char *pszShapeFile, const char *pszAccess, SAHooks *psHooks, int bRestoreSHX)
int SHPRestoreSHX (const char *pszShapeFile, const char *pszAccess, SAHooks *psHooks)
void SHPSetFastModeReadObject (SHPHandle hSHP, int bFastMode)
SHPHandle SHPCreate (const char *pszShapeFile, int nShapeType)
SHPHandle SHPCreateLL (const char *pszShapeFile, int nShapeType, SAHooks *psHooks)
void SHPGetInfo (SHPHandle hSHP, int *pnEntities, int *pnShapeType, double *padfMinBound, double *padfMaxBound)
SHPObject * SHPReadObject (SHPHandle hSHP, int iShape)
int SHPWriteObject (SHPHandle hSHP, int iShape, SHPObject *psObject)
void SHPDestroyObject (SHPObject *psObject)
void SHPComputeExtents (SHPObject *psObject)
SHPObject * SHPCreateObject (int nSHPType, int nShapeId, int nParts, const int *panPartStart, const int *panPartType, int nVertices, const double *padfX, const double *padfY, const double *padfZ, const double *padfM)
SHPObject * SHPCreateSimpleObject (int nSHPType, int nVertices, const double *padfX, const double *padfY, const double *padfZ)
int SHPRewindObject (SHPHandle hSHP, SHPObject *psObject)
void SHPClose (SHPHandle hSHP)
void SHPWriteHeader (SHPHandle hSHP)
const char * SHPTypeName (int nSHPType)
const char * SHPPartTypeName (int nPartType)
SHPTree * SHPCreateTree (SHPHandle hSHP, int nDimension, int nMaxDepth, double *padfBoundsMin, double *padfBoundsMax)
void SHPDestroyTree (SHPTree *hTree)
int SHPWriteTree (SHPTree *hTree, const char *pszFilename)
int SHPTreeAddShapeId (SHPTree *hTree, SHPObject *psObject)
int SHPTreeRemoveShapeId (SHPTree *hTree, int nShapeId)
void SHPTreeTrimExtraNodes (SHPTree *hTree)
int * SHPTreeFindLikelyShapes (SHPTree *hTree, double *padfBoundsMin, double *padfBoundsMax, int *)
int SHPCheckBoundsOverlap (double *, double *, double *, double *, int)
int * SHPSearchDiskTree (FILE *fp, double *padfBoundsMin, double *padfBoundsMax, int *pnShapeCount)
SHPTreeDiskHandle SHPOpenDiskTree (const char *pszQIXFilename, SAHooks *psHooks)
void SHPCloseDiskTree (SHPTreeDiskHandle hDiskTree)
int * SHPSearchDiskTreeEx (SHPTreeDiskHandle hDiskTree, double *padfBoundsMin, double *padfBoundsMax, int *pnShapeCount)
int SHPWriteTreeLL (SHPTree *hTree, const char *pszFilename, SAHooks *psHooks)
SBNSearchHandle SBNOpenDiskTree (const char *pszSBNFilename, SAHooks *psHooks)
void SBNCloseDiskTree (SBNSearchHandle hSBN)
int * SBNSearchDiskTree (SBNSearchHandle hSBN, double *padfBoundsMin, double *padfBoundsMax, int *pnShapeCount)
int * SBNSearchDiskTreeInteger (SBNSearchHandle hSBN, int bMinX, int bMinY, int bMaxX, int bMaxY, int *pnShapeCount)
void SBNSearchFreeIds (int *panShapeId)
DBFHandle DBFOpen (const char *pszDBFFile, const char *pszAccess)
DBFHandle DBFOpenLL (const char *pszDBFFile, const char *pszAccess, SAHooks *psHooks)
DBFHandle DBFCreate (const char *pszDBFFile)
DBFHandle DBFCreateEx (const char *pszDBFFile, const char *pszCodePage)
DBFHandle DBFCreateLL (const char *pszDBFFile, const char *pszCodePage, SAHooks *psHooks)
int DBFGetFieldCount (DBFHandle psDBF)
int DBFGetRecordCount (DBFHandle psDBF)
int DBFAddField (DBFHandle hDBF, const char *pszFieldName, DBFFieldType eType, int nWidth, int nDecimals)
int DBFAddNativeFieldType (DBFHandle hDBF, const char *pszFieldName, char chType, int nWidth, int nDecimals)
int DBFDeleteField (DBFHandle hDBF, int iField)
int DBFReorderFields (DBFHandle psDBF, int *panMap)
int DBFAlterFieldDefn (DBFHandle psDBF, int iField, const char *pszFieldName, char chType, int nWidth, int nDecimals)
DBFFieldType DBFGetFieldInfo (DBFHandle psDBF, int iField, char *pszFieldName, int *pnWidth, int *pnDecimals)
int DBFGetFieldIndex (DBFHandle psDBF, const char *pszFieldName)
int DBFReadIntegerAttribute (DBFHandle hDBF, int iShape, int iField)
double DBFReadDoubleAttribute (DBFHandle hDBF, int iShape, int iField)
const char * DBFReadStringAttribute (DBFHandle hDBF, int iShape, int iField)
const char * DBFReadLogicalAttribute (DBFHandle hDBF, int iShape, int iField)
int DBFIsAttributeNULL (DBFHandle hDBF, int iShape, int iField)
int DBFWriteIntegerAttribute (DBFHandle hDBF, int iShape, int iField, int nFieldValue)
int DBFWriteDoubleAttribute (DBFHandle hDBF, int iShape, int iField, double dFieldValue)
int DBFWriteStringAttribute (DBFHandle hDBF, int iShape, int iField, const char *pszFieldValue)
int DBFWriteNULLAttribute (DBFHandle hDBF, int iShape, int iField)
int DBFWriteLogicalAttribute (DBFHandle hDBF, int iShape, int iField, const char lFieldValue)
int DBFWriteAttributeDirectly (DBFHandle psDBF, int hEntity, int iField, void *pValue)
const char * DBFReadTuple (DBFHandle psDBF, int hEntity)
int DBFWriteTuple (DBFHandle psDBF, int hEntity, void *pRawTuple)
int DBFIsRecordDeleted (DBFHandle psDBF, int iShape)
int DBFMarkRecordDeleted (DBFHandle psDBF, int iShape, int bIsDeleted)
DBFHandle DBFCloneEmpty (DBFHandle psDBF, const char *pszFilename)
void DBFClose (DBFHandle hDBF)
void DBFUpdateHeader (DBFHandle hDBF)
char DBFGetNativeFieldType (DBFHandle hDBF, int iField)
const char * DBFGetCodePage (DBFHandle psDBF)
void DBFSetLastModifiedDate (DBFHandle psDBF, int nYYSince1900, int nMM, int nDD)
void DBFSetWriteEndOfFileChar (DBFHandle psDBF, int bWriteFlag)
Macro Definition Documentation
DISABLE_MULTIPATCH_MEASURE
#define DISABLE_MULTIPATCH_MEASURE
Definition at line 209 of file shapefil.h.
MAX_DEFAULT_TREE_DEPTH
#define MAX_DEFAULT_TREE_DEPTH 12
Definition at line 486 of file shapefil.h.
MAX_SUBNODE
#define MAX_SUBNODE 4
Definition at line 483 of file shapefil.h.
SHP_CVSID
#define SHP_CVSID (string)
Value:
    static const char cpl_cvsid[] = string; \
    static const char *cvsid_aw() { return (cvsid_aw() ? NULL : cpl_cvsid); }
Definition at line 267 of file shapefil.h.
SHPAPI_CALL
#define SHPAPI_CALL
Definition at line 250 of file shapefil.h.
SHPAPI_CALL1
#define SHPAPI_CALL1 (x) x SHPAPI_CALL
Definition at line 255 of file shapefil.h.
SHPP_FIRSTRING
#define SHPP_FIRSTRING 4
Definition at line 375 of file shapefil.h.
SHPP_INNERRING
#define SHPP_INNERRING 3
Definition at line 374 of file shapefil.h.
SHPP_OUTERRING
#define SHPP_OUTERRING 2
Definition at line 373 of file shapefil.h.
SHPP_RING
#define SHPP_RING 5
Definition at line 376 of file shapefil.h.
SHPP_TRIFAN
#define SHPP_TRIFAN 1
Definition at line 372 of file shapefil.h.
SHPP_TRISTRIP
#define SHPP_TRISTRIP 0
Definition at line 371 of file shapefil.h.
SHPT_ARC
#define SHPT_ARC 3
Definition at line 353 of file shapefil.h.
SHPT_ARCM
#define SHPT_ARCM 23
Definition at line 361 of file shapefil.h.
SHPT_ARCZ
#define SHPT_ARCZ 13
Definition at line 357 of file shapefil.h.
SHPT_MULTIPATCH
#define SHPT_MULTIPATCH 31
Definition at line 364 of file shapefil.h.
SHPT_MULTIPOINT
#define SHPT_MULTIPOINT 8
Definition at line 355 of file shapefil.h.
SHPT_MULTIPOINTM
#define SHPT_MULTIPOINTM 28
Definition at line 363 of file shapefil.h.
SHPT_MULTIPOINTZ
#define SHPT_MULTIPOINTZ 18
Definition at line 359 of file shapefil.h.
SHPT_NULL
#define SHPT_NULL 0
Definition at line 351 of file shapefil.h.
SHPT_POINT
#define SHPT_POINT 1
Definition at line 352 of file shapefil.h.
SHPT_POINTM
#define SHPT_POINTM 21
Definition at line 360 of file shapefil.h.
SHPT_POINTZ
#define SHPT_POINTZ 11
Definition at line 356 of file shapefil.h.
SHPT_POLYGON
#define SHPT_POLYGON 5
Definition at line 354 of file shapefil.h.
SHPT_POLYGONM
#define SHPT_POLYGONM 25
Definition at line 362 of file shapefil.h.
SHPT_POLYGONZ
#define SHPT_POLYGONZ 15
Definition at line 358 of file shapefil.h.
TRIM_DBF_WHITESPACE
#define TRIM_DBF_WHITESPACE
Definition at line 202 of file shapefil.h.
XBASE_FLD_MAX_WIDTH
#define XBASE_FLD_MAX_WIDTH 255
Definition at line 646 of file shapefil.h.
XBASE_FLDHDR_SZ
#define XBASE_FLDHDR_SZ 32
Definition at line 640 of file shapefil.h.
XBASE_FLDNAME_LEN_READ
#define XBASE_FLDNAME_LEN_READ 11
Definition at line 642 of file shapefil.h.
XBASE_FLDNAME_LEN_WRITE
#define XBASE_FLDNAME_LEN_WRITE 10
Definition at line 644 of file shapefil.h.
Typedef Documentation
DBFHandle
typedef DBFInfo* DBFHandle
Definition at line 628 of file shapefil.h.
SAFile
typedef int* SAFile
Definition at line 287 of file shapefil.h.
SAOffset
typedef unsigned long SAOffset
Definition at line 290 of file shapefil.h.
SBNSearchHandle
typedef struct SBNSearchInfo* SBNSearchHandle
Definition at line 560 of file shapefil.h.
SHPHandle
typedef SHPInfo* SHPHandle
Definition at line 346 of file shapefil.h.
SHPObject
typedef struct tagSHPObject SHPObject
Definition at line 307 of file shapefil.h.
SHPTreeDiskHandle
typedef struct SHPDiskTreeInfo* SHPTreeDiskHandle
Definition at line 540 of file shapefil.h.
SHPTreeNode
typedef struct shape_tree_node SHPTreeNode
Enumeration Type Documentation
DBFFieldType
enum DBFFieldType
Enumerator
FTString
FTInteger
FTDouble
FTLogical
FTDate
FTInvalid
Definition at line 630 of file shapefil.h.
Function Documentation
DBFAddField()
int DBFAddField (DBFHandle hDBF, const char * pszFieldName, DBFFieldType eType, int nWidth, int nDecimals)
Definition at line 923 of file dbfopen.c.
References DBFAddNativeFieldType(), FTDate, FTLogical, and FTString.
DBFAddNativeFieldType()
int DBFAddNativeFieldType (DBFHandle hDBF, const char * pszFieldName, char chType, int nWidth, int nDecimals)
Definition at line 970 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFInfo::bWriteEndOfFileChar, DBFFlushRecord(), DBFGetNullCharacter(), DBFUpdateHeader(), END_OF_FILE_CHARACTER, SAHooks::Error, FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SfRealloc(), DBFInfo::sHooks, STATIC_CAST, TRUE, XBASE_FLD_MAX_WIDTH, XBASE_FLDHDR_SZ, and XBASE_FLDNAME_LEN_WRITE.
Referenced by DBFAddField().
DBFAlterFieldDefn()
int DBFAlterFieldDefn (DBFHandle psDBF, int iField, const char * pszFieldName, char chType, int nWidth, int nDecimals)
Definition at line 2194 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFInfo::bWriteEndOfFileChar, DBFFlushRecord(), DBFGetNullCharacter(), DBFIsValueNULL(), DBFUpdateHeader(), END_OF_FILE_CHARACTER, FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SfRealloc(), DBFInfo::sHooks, STATIC_CAST, TRUE, XBASE_FLD_MAX_WIDTH, XBASE_FLDHDR_SZ, and XBASE_FLDNAME_LEN_WRITE.
DBFCloneEmpty()
DBFHandle DBFCloneEmpty (DBFHandle psDBF, const char * pszFilename)
Definition at line 1785 of file dbfopen.c.
References DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFInfo::bWriteEndOfFileChar, DBFClose(), DBFCreateEx(), DBFOpen(), DBFWriteHeader(), DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszHeader, SHPLIB_NULLPTR, STATIC_CAST, TRUE, and XBASE_FLDHDR_SZ.
DBFClose()
void DBFClose (DBFHandle hDBF)
Definition at line 736 of file dbfopen.c.
References DBFInfo::bNoHeader, DBFInfo::bUpdated, CPL_IGNORE_RET_VAL_INT, DBFFlushRecord(), DBFUpdateHeader(), DBFWriteHeader(), SAHooks::FClose, DBFInfo::fp, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, DBFInfo::pszWorkField, DBFInfo::sHooks, and SHPLIB_NULLPTR.
Referenced by DBFCloneEmpty(), and DBFOpenLL().
DBFCreate()
DBFHandle DBFCreate (const char * pszDBFFile)
Definition at line 786 of file dbfopen.c.
References DBFCreateEx().
DBFCreateEx()
DBFHandle DBFCreateEx (const char * pszDBFFile, const char * pszCodePage)
Definition at line 799 of file dbfopen.c.
References DBFCreateLL(), and SASetupDefaultHooks().
Referenced by DBFCloneEmpty(), and DBFCreate().
DBFCreateLL()
DBFHandle DBFCreateLL (const char * pszDBFFile, const char * pszCodePage, SAHooks * psHooks)
Definition at line 816 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, CONST_CAST, DBFGetLenWithoutExtension(), DBFSetLastModifiedDate(), DBFSetWriteEndOfFileChar(), FALSE, SAHooks::FClose, SAHooks::FOpen, DBFInfo::fp, SAHooks::FWrite, DBFInfo::iLanguageDriver, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SAHooks::Remove, DBFInfo::sHooks, SHPLIB_NULLPTR, STATIC_CAST, TRUE, and XBASE_FILEHDR_SZ.
Referenced by DBFCreateEx().
DBFDeleteField()
int DBFDeleteField (DBFHandle hDBF, int iField)
Definition at line 1957 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFInfo::bWriteEndOfFileChar, DBFFlushRecord(), DBFUpdateHeader(), END_OF_FILE_CHARACTER, FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SfRealloc(), DBFInfo::sHooks, STATIC_CAST, TRUE, and XBASE_FLDHDR_SZ.
DBFGetCodePage()
const char* DBFGetCodePage (DBFHandle psDBF)
Definition at line 1943 of file dbfopen.c.
References SHPLIB_NULLPTR.
DBFGetFieldCount()
int DBFGetFieldCount (DBFHandle psDBF)
Definition at line 1372 of file dbfopen.c.
References DBFInfo::nFields.
Referenced by DBFGetFieldIndex().
DBFGetFieldIndex()
int DBFGetFieldIndex (DBFHandle psDBF, const char * pszFieldName)
Definition at line 1854 of file dbfopen.c.
References DBFGetFieldCount(), DBFGetFieldInfo(), name, SHPLIB_NULLPTR, STRCASECMP, and XBASE_FLDNAME_LEN_READ.
DBFGetFieldInfo()
DBFFieldType DBFGetFieldInfo (DBFHandle psDBF, int iField, char * pszFieldName, int * pnWidth, int * pnDecimals)
Definition at line 1400 of file dbfopen.c.
References FTDate, FTDouble, FTInteger, FTInvalid, FTLogical, FTString, DBFInfo::nFields, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldSize, DBFInfo::pszHeader, SHPLIB_NULLPTR, STATIC_CAST, XBASE_FLDHDR_SZ, and XBASE_FLDNAME_LEN_READ.
Referenced by DBFGetFieldIndex().
DBFGetNativeFieldType()
char DBFGetNativeFieldType (DBFHandle hDBF, int iField)
Definition at line 1836 of file dbfopen.c.
References DBFInfo::pachFieldType.
DBFGetRecordCount()
int DBFGetRecordCount (DBFHandle psDBF)
Definition at line 1385 of file dbfopen.c.
References DBFInfo::nRecords.
DBFIsAttributeNULL()
int DBFIsAttributeNULL (DBFHandle hDBF, int iShape, int iField)
Definition at line 1352 of file dbfopen.c.
References DBFIsValueNULL(), DBFReadStringAttribute(), DBFInfo::pachFieldType, SHPLIB_NULLPTR, and TRUE.
DBFIsRecordDeleted()
int DBFIsRecordDeleted (DBFHandle psDBF, int iShape)
Definition at line 1876 of file dbfopen.c.
References DBFLoadRecord(), FALSE, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, and TRUE.
DBFMarkRecordDeleted()
int DBFMarkRecordDeleted (DBFHandle psDBF, int iShape, int bIsDeleted)
Definition at line 1901 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bUpdated, DBFLoadRecord(), FALSE, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, and TRUE.
DBFOpen()
DBFHandle DBFOpen (const char * pszDBFFile, const char * pszAccess)
Definition at line 490 of file dbfopen.c.
References DBFOpenLL(), and SASetupDefaultHooks().
Referenced by DBFCloneEmpty().
DBFOpenLL()
DBFHandle DBFOpenLL (const char * pszDBFFile, const char * pszAccess, SAHooks * psHooks)
Definition at line 527 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFClose(), DBFGetLenWithoutExtension(), DBFSetLastModifiedDate(), DBFSetWriteEndOfFileChar(), FALSE, SAHooks::FClose, SAHooks::FOpen, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, HEADER_RECORD_TERMINATOR, DBFInfo::iLanguageDriver, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, REINTERPRET_CAST, SfRealloc(), DBFInfo::sHooks, SHPLIB_NULLPTR, STATIC_CAST, TRUE, XBASE_FILEHDR_SZ, and XBASE_FLDHDR_SZ.
Referenced by DBFOpen().
DBFReadDoubleAttribute()
double DBFReadDoubleAttribute (DBFHandle hDBF, int iShape, int iField)
Definition at line 1257 of file dbfopen.c.
References DBFReadAttribute(), SHPLIB_NULLPTR, and STATIC_CAST.
DBFReadIntegerAttribute()
int DBFReadIntegerAttribute (DBFHandle hDBF, int iShape, int iField)
Definition at line 1237 of file dbfopen.c.
References DBFReadAttribute(), SHPLIB_NULLPTR, and STATIC_CAST.
DBFReadLogicalAttribute()
const char* DBFReadLogicalAttribute (DBFHandle hDBF, int iShape, int iField)
Definition at line 1290 of file dbfopen.c.
References DBFReadAttribute(), and STATIC_CAST.
DBFReadStringAttribute()
const char* DBFReadStringAttribute (DBFHandle hDBF, int iShape, int iField)
Definition at line 1277 of file dbfopen.c.
References DBFReadAttribute(), and STATIC_CAST.
Referenced by DBFIsAttributeNULL().
DBFReadTuple()
const char* DBFReadTuple (DBFHandle psDBF, int hEntity)
Definition at line 1766 of file dbfopen.c.
References DBFLoadRecord(), SHPLIB_NULLPTR, and STATIC_CAST.
DBFReorderFields()
int DBFReorderFields (DBFHandle psDBF, int * panMap)
Definition at line 2084 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFFlushRecord(), DBFUpdateHeader(), FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszHeader, DBFInfo::sHooks, STATIC_CAST, TRUE, and XBASE_FLDHDR_SZ.
DBFSetLastModifiedDate()
void DBFSetLastModifiedDate (DBFHandle psDBF, int nYYSince1900, int nMM, int nDD)
Definition at line 476 of file dbfopen.c.
References DBFInfo::nUpdateDay, DBFInfo::nUpdateMonth, and DBFInfo::nUpdateYearSince1900.
Referenced by DBFCreateLL(), and DBFOpenLL().
DBFSetWriteEndOfFileChar()
void DBFSetWriteEndOfFileChar (DBFHandle psDBF, int bWriteFlag)
Definition at line 2432 of file dbfopen.c.
References DBFInfo::bWriteEndOfFileChar.
Referenced by DBFCreateLL(), and DBFOpenLL().
DBFUpdateHeader()
void DBFUpdateHeader (DBFHandle hDBF)
Definition at line 443 of file dbfopen.c.
References DBFInfo::bNoHeader, DBFFlushRecord(), DBFWriteHeader(), SAHooks::FFlush, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nRecords, DBFInfo::nUpdateDay, DBFInfo::nUpdateMonth, DBFInfo::nUpdateYearSince1900, DBFInfo::sHooks, STATIC_CAST, and XBASE_FILEHDR_SZ.
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFClose(), DBFDeleteField(), and DBFReorderFields().
DBFWriteAttributeDirectly()
int DBFWriteAttributeDirectly (DBFHandle psDBF, int hEntity, int iField, void * pValue)
Definition at line 1572 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFFlushRecord(), DBFLoadRecord(), DBFWriteHeader(), FALSE, DBFInfo::nCurrentRecord, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, REINTERPRET_CAST, STATIC_CAST, and TRUE.
DBFWriteDoubleAttribute()
int DBFWriteDoubleAttribute (DBFHandle hDBF, int iShape, int iField, double dFieldValue)
Definition at line 1640 of file dbfopen.c.
References DBFWriteAttribute(), and STATIC_CAST.
DBFWriteIntegerAttribute()
int DBFWriteIntegerAttribute (DBFHandle hDBF, int iShape, int iField, int nFieldValue)
Definition at line 1654 of file dbfopen.c.
References DBFWriteAttribute(), and STATIC_CAST.
DBFWriteLogicalAttribute()
int DBFWriteLogicalAttribute (DBFHandle hDBF, int iShape, int iField, const char lFieldValue)
Definition at line 1697 of file dbfopen.c.
References CONST_CAST, DBFWriteAttribute(), and STATIC_CAST.
DBFWriteNULLAttribute()
int DBFWriteNULLAttribute (DBFHandle hDBF, int iShape, int iField)
Definition at line 1684 of file dbfopen.c.
References DBFWriteAttribute(), and SHPLIB_NULLPTR.
DBFWriteStringAttribute()
int DBFWriteStringAttribute (DBFHandle hDBF, int iShape, int iField, const char * pszFieldValue)
Definition at line 1670 of file dbfopen.c.
References CONST_CAST, DBFWriteAttribute(), and STATIC_CAST.
DBFWriteTuple()
int DBFWriteTuple (DBFHandle psDBF, int hEntity, void * pRawTuple)
Definition at line 1711 of file dbfopen.c.
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFFlushRecord(), DBFLoadRecord(), DBFWriteHeader(), FALSE, DBFInfo::nCurrentRecord, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, REINTERPRET_CAST, and TRUE.
SASetupDefaultHooks()
void SASetupDefaultHooks (SAHooks * psHooks)
Definition at line 184 of file safileio.c.
References SAHooks::Atof, SAHooks::Error, SAHooks::FClose, SAHooks::FFlush, SAHooks::FOpen, SAHooks::FRead, SAHooks::FSeek, SAHooks::FTell, SAHooks::FWrite, SAHooks::Remove, SADError(), SADFClose(), SADFFlush(), SADFOpen(), SADFRead(), SADFSeek(), SADFTell(), SADFWrite(), and SADRemove().
Referenced by DBFCreateEx(), DBFOpen(), SHPCreate(), SHPOpen(), SHPOpenDiskTree(), SHPWriteTree(), and SHPWriteTreeLL().
SBNCloseDiskTree()
void SBNCloseDiskTree (SBNSearchHandle hSBN)
SBNOpenDiskTree()
SBNSearchHandle SBNOpenDiskTree (const char * pszSBNFilename, SAHooks * psHooks)
SBNSearchDiskTree()
int* SBNSearchDiskTree (SBNSearchHandle hSBN, double * padfBoundsMin, double * padfBoundsMax, int * pnShapeCount)
SBNSearchDiskTreeInteger()
int* SBNSearchDiskTreeInteger (SBNSearchHandle hSBN, int bMinX, int bMinY, int bMaxX, int bMaxY, int * pnShapeCount)
SBNSearchFreeIds()
void SBNSearchFreeIds (int * panShapeId)
SHPCheckBoundsOverlap()
int SHPCheckBoundsOverlap (double * padfBox1Min, double * padfBox1Max, double * padfBox2Min, double * padfBox2Max, int nDimension)
Definition at line 378 of file shptree.c.
References FALSE, and TRUE.
Referenced by SHPSearchDiskTreeNode(), and SHPTreeCollectShapeIds().
SHPClose()
void SHPClose (SHPHandle hSHP)
Definition at line 1149 of file shpopen.c.
References SHPInfo::bUpdated, SAHooks::FClose, SHPInfo::fpSHP, SHPInfo::fpSHX, SHPInfo::pabyObjectBuf, SHPInfo::pabyRec, SHPInfo::panRecOffset, SHPInfo::panRecSize, SHPInfo::psCachedObject, SHPInfo::sHooks, SHPLIB_NULLPTR, and SHPWriteHeader().
Referenced by SHPOpenLL().
SHPCloseDiskTree()
void SHPCloseDiskTree (SHPTreeDiskHandle hDiskTree)
Definition at line 873 of file shptree.c.
References SAHooks::FClose, SHPDiskTreeInfo::fpQIX, SHPDiskTreeInfo::sHooks, and SHPLIB_NULLPTR.
SHPComputeExtents()
void SHPComputeExtents (SHPObject * psObject)
Definition at line 1431 of file shpopen.c.
References tagSHPObject::dfMMax, tagSHPObject::dfMMin, tagSHPObject::dfXMax, tagSHPObject::dfXMin, tagSHPObject::dfYMax, tagSHPObject::dfYMin, tagSHPObject::dfZMax, tagSHPObject::dfZMin, MAX, MIN, tagSHPObject::nVertices, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, and tagSHPObject::padfZ.
Referenced by SHPCreateObject().
SHPCreate()
SHPHandle SHPCreate (const char * pszShapeFile, int nShapeType)
Definition at line 1249 of file shpopen.c.
References SASetupDefaultHooks(), and SHPCreateLL().
SHPCreateLL()
SHPHandle SHPCreateLL (const char * pszShapeFile, int nShapeType, SAHooks * psHooks)
Definition at line 1267 of file shpopen.c.
References bBigEndian, ByteCopy, SAHooks::Error, FALSE, SAHooks::FClose, SAHooks::FOpen, SAHooks::FWrite, SHPGetLenWithoutExtension(), SHPLIB_NULLPTR, SHPOpenLL(), STATIC_CAST, SwapWord(), and TRUE.
Referenced by SHPCreate().
SHPCreateObject()
SHPObject* SHPCreateObject (int nSHPType, int nShapeId, int nParts, const int * panPartStart, const int * panPartType, int nVertices, const double * padfX, const double * padfY, const double * padfZ, const double * padfM)
Definition at line 1469 of file shpopen.c.
References tagSHPObject::bMeasureIsUsed, FALSE, MAX, tagSHPObject::nParts, tagSHPObject::nShapeId, tagSHPObject::nSHPType, tagSHPObject::nVertices, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, tagSHPObject::padfZ, tagSHPObject::panPartStart, tagSHPObject::panPartType, SHPComputeExtents(), SHPLIB_NULLPTR, SHPP_RING, SHPT_ARC, SHPT_ARCM, SHPT_ARCZ, SHPT_MULTIPATCH, SHPT_MULTIPOINTM, SHPT_MULTIPOINTZ, SHPT_POINTM, SHPT_POINTZ, SHPT_POLYGON, SHPT_POLYGONM, SHPT_POLYGONZ, STATIC_CAST, and TRUE.
Referenced by SHPCreateSimpleObject().
SHPCreateSimpleObject()
SHPObject* SHPCreateSimpleObject (int nSHPType, int nVertices, const double * padfX, const double * padfY, const double * padfZ)
Definition at line 1587 of file shpopen.c.
References SHPCreateObject(), and SHPLIB_NULLPTR.
SHPCreateTree()
SHPTree* SHPCreateTree (SHPHandle hSHP, int nDimension, int nMaxDepth, double * padfBoundsMin, double * padfBoundsMax)
Definition at line 217 of file shptree.c.
References shape_tree_node::adfBoundsMax, shape_tree_node::adfBoundsMin, SHPTree::hSHP, MAX_DEFAULT_TREE_DEPTH, SHPTree::nDimension, SHPTree::nMaxDepth, SHPTree::nTotalCount, SHPTree::psRoot, SHPDestroyObject(), SHPGetInfo(), SHPLIB_NULLPTR, SHPReadObject(), SHPTreeAddShapeId(), SHPTreeNodeCreate(), and STATIC_CAST.
SHPDestroyObject()
void SHPDestroyObject (SHPObject * psObject)
Definition at line 2902 of file shpopen.c.
References tagSHPObject::bFastModeReadObject, FALSE, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, tagSHPObject::padfZ, tagSHPObject::panPartStart, tagSHPObject::panPartType, and SHPLIB_NULLPTR.
Referenced by SHPCreateTree(), SHPDestroyTreeNode(), and SHPReadObject().
SHPDestroyTree()
void SHPDestroyTree (SHPTree * hTree)
Definition at line 364 of file shptree.c.
References SHPTree::psRoot, and SHPDestroyTreeNode().
SHPGetInfo()
void SHPGetInfo (SHPHandle hSHP, int * pnEntities, int * pnShapeType, double * padfMinBound, double * padfMaxBound)
Definition at line 1217 of file shpopen.c.
References SHPInfo::adBoundsMax, SHPInfo::adBoundsMin, SHPInfo::nRecords, SHPInfo::nShapeType, and SHPLIB_NULLPTR.
Referenced by SHPCreateTree().
SHPOpen()
SHPHandle SHPOpen (const char * pszShapeFile, const char * pszAccess)
Definition at line 561 of file shpopen.c.
References SASetupDefaultHooks(), and SHPOpenLL().
SHPOpenDiskTree()
SHPTreeDiskHandle SHPOpenDiskTree (const char * pszQIXFilename, SAHooks * psHooks)
Definition at line 847 of file shptree.c.
References SAHooks::FOpen, SHPDiskTreeInfo::fpQIX, SASetupDefaultHooks(), SHPDiskTreeInfo::sHooks, SHPLIB_NULLPTR, and STATIC_CAST.
SHPOpenLL()
SHPHandle SHPOpenLL (const char * pszShapeFile, const char * pszAccess, SAHooks * psHooks)
Definition at line 599 of file shpopen.c.
References SHPInfo::adBoundsMax, SHPInfo::adBoundsMin, bBigEndian, SHPInfo::bUpdated, SAHooks::Error, FALSE, SAHooks::FClose, SAHooks::FOpen, SHPInfo::fpSHP, SHPInfo::fpSHX, SAHooks::FRead, SAHooks::FSeek, SAHooks::FTell, MAX, SHPInfo::nFileSize, SHPInfo::nMaxRecords, SHPInfo::nRecords, SHPInfo::nShapeType, SHPInfo::panRecOffset, SHPInfo::panRecSize, SHPInfo::sHooks, SHPClose(), SHPGetLenWithoutExtension(), SHPLIB_NULLPTR, STATIC_CAST, SwapWord(), and TRUE.
Referenced by SHPCreateLL(), SHPOpen(), and SHPOpenLLEx().
SHPOpenLLEx()
SHPHandle SHPOpenLLEx (const char * pszShapeFile, const char * pszAccess, SAHooks * psHooks, int bRestoreSHX)
Definition at line 942 of file shpopen.c.
References SHPLIB_NULLPTR, SHPOpenLL(), and SHPRestoreSHX().
SHPPartTypeName()
const char* SHPPartTypeName (int nPartType)
Definition at line 2869 of file shpopen.c.
References SHPP_FIRSTRING, SHPP_INNERRING, SHPP_OUTERRING, SHPP_RING, SHPP_TRIFAN, and SHPP_TRISTRIP.
SHPReadObject()
SHPObject* SHPReadObject (SHPHandle hSHP, int iShape)
Definition at line 2092 of file shpopen.c.
References bBigEndian, tagSHPObject::bFastModeReadObject, tagSHPObject::bMeasureIsUsed, tagSHPObject::dfMMax, tagSHPObject::dfMMin, tagSHPObject::dfXMax, tagSHPObject::dfXMin, tagSHPObject::dfYMax, tagSHPObject::dfYMin, tagSHPObject::dfZMax, tagSHPObject::dfZMin, FALSE, tagSHPObject::nParts, tagSHPObject::nShapeId, tagSHPObject::nSHPType, tagSHPObject::nVertices, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, tagSHPObject::padfZ, tagSHPObject::panPartStart, tagSHPObject::panPartType, SfRealloc(), SHPAllocBuffer(), SHPDestroyObject(), SHPLIB_NULLPTR, SHPP_RING, SHPReallocObjectBufIfNecessary(), SHPT_ARC, SHPT_ARCM, SHPT_ARCZ, SHPT_MULTIPATCH, SHPT_MULTIPOINT, SHPT_MULTIPOINTM, SHPT_MULTIPOINTZ, SHPT_POINT, SHPT_POINTM, SHPT_POINTZ, SHPT_POLYGON, SHPT_POLYGONM, SHPT_POLYGONZ, STATIC_CAST, SwapWord(), and TRUE.
Referenced by SHPCreateTree().
SHPRestoreSHX()
int SHPRestoreSHX (const char * pszShapeFile, const char * pszAccess, SAHooks * psHooks)
Definition at line 966 of file shpopen.c.
References bBigEndian, SAHooks::Error, FALSE, SAHooks::FClose, SAHooks::FOpen, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, SHPGetLenWithoutExtension(), SHPLIB_NULLPTR, STATIC_CAST, SwapWord(), and TRUE.
Referenced by SHPOpenLLEx().
SHPRewindObject()
int SHPRewindObject (SHPHandle hSHP, SHPObject * psObject)
Definition at line 3030 of file shpopen.c.
References tagSHPObject::nParts, tagSHPObject::nSHPType, tagSHPObject::nVertices, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, tagSHPObject::padfZ, tagSHPObject::panPartStart, SHPGetPartVertexCount(), SHPRewindIsInnerRing(), SHPT_POLYGON, SHPT_POLYGONM, and SHPT_POLYGONZ.
SHPSearchDiskTree()
int* SHPSearchDiskTree (FILE * fp, double * padfBoundsMin, double * padfBoundsMax, int * pnShapeCount)
Definition at line 1048 of file shptree.c.
References SHPDiskTreeInfo::fpQIX, SAHooks::FRead, SAHooks::FSeek, REINTERPRET_CAST, SHPDiskTreeInfo::sHooks, SHPSearchDiskTreeEx(), SHPTreeReadLibc(), and SHPTreeSeekLibc().
SHPSearchDiskTreeEx()
int* SHPSearchDiskTreeEx (SHPTreeDiskHandle hDiskTree, double * padfBoundsMin, double * padfBoundsMax, int * pnShapeCount)
Definition at line 1070 of file shptree.c.
References bBigEndian, compare_ints(), FALSE, SHPDiskTreeInfo::fpQIX, SAHooks::FRead, SAHooks::FSeek, REINTERPRET_CAST, SEEK_SET, SHPDiskTreeInfo::sHooks, SHPLIB_NULLPTR, SHPSearchDiskTreeNode(), STATIC_CAST, and TRUE.
Referenced by SHPSearchDiskTree().
SHPSetFastModeReadObject()
void SHPSetFastModeReadObject (SHPHandle hSHP, int bFastMode)
Definition at line 1196 of file shpopen.c.
References SHPInfo::bFastModeReadObject, SHPInfo::psCachedObject, SHPLIB_NULLPTR, and STATIC_CAST.
SHPTreeAddShapeId()
int SHPTreeAddShapeId (SHPTree * hTree, SHPObject * psObject)
Definition at line 631 of file shptree.c.
References SHPTree::nDimension, SHPTree::nMaxDepth, SHPTree::nTotalCount, SHPTree::psRoot, and SHPTreeNodeAddShapeId().
Referenced by SHPCreateTree().
SHPTreeFindLikelyShapes()
int* SHPTreeFindLikelyShapes (SHPTree * hTree, double * padfBoundsMin, double * padfBoundsMax, int * pnShapeCount)
Definition at line 716 of file shptree.c.
References compare_ints(), SHPLIB_NULLPTR, and SHPTreeCollectShapeIds().
SHPTreeRemoveShapeId()
int SHPTreeRemoveShapeId (SHPTree * hTree, int nShapeId)
SHPTreeTrimExtraNodes()
void SHPTreeTrimExtraNodes (SHPTree * hTree)
Definition at line 810 of file shptree.c.
References SHPTree::psRoot, and SHPTreeNodeTrim().
SHPTypeName()
const char* SHPTypeName (int nSHPType)
Definition at line 2812 of file shpopen.c.
References SHPT_ARC, SHPT_ARCM, SHPT_ARCZ, SHPT_MULTIPATCH, SHPT_MULTIPOINT, SHPT_MULTIPOINTM, SHPT_MULTIPOINTZ, SHPT_NULL, SHPT_POINT, SHPT_POINTM, SHPT_POINTZ, SHPT_POLYGON, SHPT_POLYGONM, and SHPT_POLYGONZ.
SHPWriteHeader()
void SHPWriteHeader (SHPHandle hSHP)
Definition at line 417 of file shpopen.c.
References SHPInfo::adBoundsMax, SHPInfo::adBoundsMin, bBigEndian, ByteCopy, SAHooks::Error, SAHooks::FFlush, SHPInfo::fpSHP, SHPInfo::fpSHX, SAHooks::FSeek, SAHooks::FWrite, SHPInfo::nFileSize, SHPInfo::nRecords, SHPInfo::nShapeType, SHPInfo::panRecOffset, SHPInfo::panRecSize, SHPInfo::sHooks, SHPLIB_NULLPTR, STATIC_CAST, and SwapWord().
Referenced by SHPClose().
SHPWriteObject()
int SHPWriteObject (SHPHandle hSHP, int iShape, SHPObject * psObject)
Definition at line 1604 of file shpopen.c.
References _SHPSetBounds(), SHPInfo::adBoundsMax, SHPInfo::adBoundsMin, bBigEndian, tagSHPObject::bMeasureIsUsed, SHPInfo::bUpdated, ByteCopy, tagSHPObject::dfMMax, tagSHPObject::dfMMin, tagSHPObject::dfZMax, tagSHPObject::dfZMin, DISABLE_MULTIPATCH_MEASURE, SAHooks::Error, FALSE, SHPInfo::fpSHP, SAHooks::FSeek, SAHooks::FWrite, MAX, MIN, SHPInfo::nFileSize, SHPInfo::nMaxRecords, tagSHPObject::nParts, SHPInfo::nRecords, SHPInfo::nShapeType, tagSHPObject::nSHPType, tagSHPObject::nVertices, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, tagSHPObject::padfZ, tagSHPObject::panPartStart, tagSHPObject::panPartType, SHPInfo::panRecOffset, SHPInfo::panRecSize, SfRealloc(), SHPInfo::sHooks, SHPLIB_NULLPTR, SHPT_ARC, SHPT_ARCM, SHPT_ARCZ, SHPT_MULTIPATCH, SHPT_MULTIPOINT, SHPT_MULTIPOINTM, SHPT_MULTIPOINTZ, SHPT_NULL, SHPT_POINT, SHPT_POINTM, SHPT_POINTZ, SHPT_POLYGON, SHPT_POLYGONM, SHPT_POLYGONZ, STATIC_CAST, SwapWord(), and TRUE.
SHPWriteTree()
int SHPWriteTree (SHPTree * hTree, const char * pszFilename)
Definition at line 1210 of file shptree.c.
References filename, SASetupDefaultHooks(), SHPDiskTreeInfo::sHooks, and SHPWriteTreeLL().
SHPWriteTreeLL()
int SHPWriteTreeLL (SHPTree * hTree, const char * pszFilename, SAHooks * psHooks)
Definition at line 1223 of file shptree.c.
References bBigEndian, FALSE, SAHooks::FClose, filename, SAHooks::FOpen, SAHooks::FWrite, SHPTree::nMaxDepth, SHPTree::nTotalCount, SHPTree::psRoot, REINTERPRET_CAST, SASetupDefaultHooks(), SHPDiskTreeInfo::sHooks, SHPLIB_NULLPTR, SHPWriteTreeNode(), and TRUE.
Referenced by SHPWriteTree().