ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/feature/sift_test.cc File Reference
sift_test.cc File Reference
#include "util/testing.h"
#include "exe/gui.h"
#include "SiftGPU/SiftGPU.h"
#include "feature/sift.h"
#include "feature/utils.h"
#include "util/math.h"
#include "util/opengl_utils.h"
#include "util/random.h"
Macros
#define TEST_NAME "feature/sift_test"
Functions
void CreateImageWithSquare (const int size, Bitmap *bitmap)
BOOST_AUTO_TEST_CASE (TestExtractSiftFeaturesCPU)
BOOST_AUTO_TEST_CASE (TestExtractCovariantSiftFeaturesCPU)
BOOST_AUTO_TEST_CASE (TestExtractCovariantAffineSiftFeaturesCPU)
BOOST_AUTO_TEST_CASE (TestExtractCovariantDSPSiftFeaturesCPU)
BOOST_AUTO_TEST_CASE (TestExtractCovariantAffineDSPSiftFeaturesCPU)
BOOST_AUTO_TEST_CASE (TestExtractSiftFeaturesGPU)
FeatureDescriptors CreateRandomFeatureDescriptors (const size_t num_features)
void CheckEqualMatches (const FeatureMatches &matches1, const FeatureMatches &matches2)
BOOST_AUTO_TEST_CASE (TestCreateSiftGPUMatcherOpenGL)
BOOST_AUTO_TEST_CASE (TestCreateSiftGPUMatcherCUDA)
BOOST_AUTO_TEST_CASE (TestMatchSiftFeaturesCPU)
BOOST_AUTO_TEST_CASE (TestMatchSiftFeaturesCPUFLANNvsBruteForce)
BOOST_AUTO_TEST_CASE (TestMatchGuidedSiftFeaturesCPU)
BOOST_AUTO_TEST_CASE (TestMatchSiftFeaturesGPU)
BOOST_AUTO_TEST_CASE (TestMatchSiftFeaturesCPUvsGPU)
BOOST_AUTO_TEST_CASE (TestMatchGuidedSiftFeaturesGPU)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "feature/sift_test"
Definition at line 32 of file sift_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/14]
BOOST_AUTO_TEST_CASE (TestCreateSiftGPUMatcherCUDA)
Definition at line 294 of file sift_test.cc.
References colmap::CreateSiftGPUMatcher(), colmap::SiftMatchingOptions::gpu_index, and colmap::SiftMatchingOptions::max_num_matches.
BOOST_AUTO_TEST_CASE() [2/14]
BOOST_AUTO_TEST_CASE (TestCreateSiftGPUMatcherOpenGL)
Definition at line 268 of file sift_test.cc.
References colmap::CreateSiftGPUMatcher(), colmap::OpenGLContextManager::HasOpenGL(), colmap::SiftMatchingOptions::max_num_matches, Run(), and colmap::RunThreadWithOpenGLContext().
BOOST_AUTO_TEST_CASE() [3/14]
BOOST_AUTO_TEST_CASE (TestExtractCovariantAffineDSPSiftFeaturesCPU)
Definition at line 168 of file sift_test.cc.
References CreateImageWithSquare(), descriptors, colmap::SiftExtractionOptions::domain_size_pooling, colmap::SiftExtractionOptions::estimate_affine_shape, colmap::ExtractCovariantSiftFeaturesCPU(), colmap::Bitmap::Height(), M_PI, colmap::Bitmap::Width(), x, and y.
BOOST_AUTO_TEST_CASE() [4/14]
BOOST_AUTO_TEST_CASE (TestExtractCovariantAffineSiftFeaturesCPU)
Definition at line 112 of file sift_test.cc.
References CreateImageWithSquare(), descriptors, colmap::SiftExtractionOptions::estimate_affine_shape, colmap::ExtractCovariantSiftFeaturesCPU(), colmap::Bitmap::Height(), M_PI, colmap::Bitmap::Width(), x, and y.
BOOST_AUTO_TEST_CASE() [5/14]
BOOST_AUTO_TEST_CASE (TestExtractCovariantDSPSiftFeaturesCPU)
Definition at line 140 of file sift_test.cc.
References CreateImageWithSquare(), descriptors, colmap::SiftExtractionOptions::domain_size_pooling, colmap::ExtractCovariantSiftFeaturesCPU(), colmap::Bitmap::Height(), M_PI, colmap::Bitmap::Width(), x, and y.
BOOST_AUTO_TEST_CASE() [6/14]
BOOST_AUTO_TEST_CASE (TestExtractCovariantSiftFeaturesCPU)
Definition at line 86 of file sift_test.cc.
References CreateImageWithSquare(), descriptors, colmap::ExtractCovariantSiftFeaturesCPU(), colmap::Bitmap::Height(), M_PI, colmap::Bitmap::Width(), x, and y.
BOOST_AUTO_TEST_CASE() [7/14]
BOOST_AUTO_TEST_CASE (TestExtractSiftFeaturesCPU)
Definition at line 60 of file sift_test.cc.
References CreateImageWithSquare(), descriptors, colmap::ExtractSiftFeaturesCPU(), colmap::Bitmap::Height(), M_PI, colmap::Bitmap::Width(), x, and y.
BOOST_AUTO_TEST_CASE() [8/14]
BOOST_AUTO_TEST_CASE (TestExtractSiftFeaturesGPU)
Definition at line 197 of file sift_test.cc.
References CreateImageWithSquare(), colmap::CreateSiftGPUExtractor(), descriptors, colmap::ExtractSiftFeaturesGPU(), colmap::OpenGLContextManager::HasOpenGL(), colmap::Bitmap::Height(), M_PI, Run(), colmap::RunThreadWithOpenGLContext(), colmap::Bitmap::Width(), x, and y.
BOOST_AUTO_TEST_CASE() [9/14]
BOOST_AUTO_TEST_CASE (TestMatchGuidedSiftFeaturesCPU)
Definition at line 438 of file sift_test.cc.
References colmap::TwoViewGeometry::config, CreateRandomFeatureDescriptors(), colmap::TwoViewGeometry::H, colmap::TwoViewGeometry::inlier_matches, colmap::MatchGuidedSiftFeaturesCPU(), and colmap::TwoViewGeometry::PLANAR_OR_PANORAMIC.
BOOST_AUTO_TEST_CASE() [10/14]
BOOST_AUTO_TEST_CASE (TestMatchGuidedSiftFeaturesGPU)
Definition at line 691 of file sift_test.cc.
References colmap::TwoViewGeometry::config, CreateRandomFeatureDescriptors(), colmap::CreateSiftGPUMatcher(), colmap::TwoViewGeometry::H, colmap::OpenGLContextManager::HasOpenGL(), colmap::TwoViewGeometry::inlier_matches, colmap::MatchGuidedSiftFeaturesGPU(), colmap::SiftMatchingOptions::max_num_matches, colmap::TwoViewGeometry::PLANAR_OR_PANORAMIC, Run(), and colmap::RunThreadWithOpenGLContext().
BOOST_AUTO_TEST_CASE() [11/14]
BOOST_AUTO_TEST_CASE (TestMatchSiftFeaturesCPU)
Definition at line 304 of file sift_test.cc.
References CreateRandomFeatureDescriptors(), and colmap::MatchSiftFeaturesCPU().
BOOST_AUTO_TEST_CASE() [12/14]
BOOST_AUTO_TEST_CASE (TestMatchSiftFeaturesCPUFLANNvsBruteForce)
Definition at line 331 of file sift_test.cc.
References CheckEqualMatches(), CreateRandomFeatureDescriptors(), colmap::SiftMatchingOptions::cross_check, colmap::FeatureDescriptorsToUnsignedByte(), colmap::L2NormalizeFeatureDescriptors(), colmap::MatchSiftFeaturesCPUBruteForce(), colmap::MatchSiftFeaturesCPUFLANN(), colmap::SiftMatchingOptions::max_num_matches, and colmap::SiftMatchingOptions::max_ratio.
BOOST_AUTO_TEST_CASE() [13/14]
BOOST_AUTO_TEST_CASE (TestMatchSiftFeaturesCPUvsGPU)
Definition at line 559 of file sift_test.cc.
References CheckEqualMatches(), CreateRandomFeatureDescriptors(), colmap::CreateSiftGPUMatcher(), colmap::SiftMatchingOptions::cross_check, colmap::FeatureDescriptorsToUnsignedByte(), colmap::OpenGLContextManager::HasOpenGL(), colmap::L2NormalizeFeatureDescriptors(), colmap::MatchSiftFeaturesCPU(), colmap::MatchSiftFeaturesGPU(), colmap::SiftMatchingOptions::max_num_matches, colmap::SiftMatchingOptions::max_ratio, Run(), and colmap::RunThreadWithOpenGLContext().
BOOST_AUTO_TEST_CASE() [14/14]
BOOST_AUTO_TEST_CASE (TestMatchSiftFeaturesGPU)
Definition at line 484 of file sift_test.cc.
References CreateRandomFeatureDescriptors(), colmap::CreateSiftGPUMatcher(), colmap::OpenGLContextManager::HasOpenGL(), colmap::MatchSiftFeaturesGPU(), colmap::SiftMatchingOptions::max_num_matches, Run(), and colmap::RunThreadWithOpenGLContext().
CheckEqualMatches()
void CheckEqualMatches (const FeatureMatches & matches1, const FeatureMatches & matches2)
Definition at line 259 of file sift_test.cc.
Referenced by BOOST_AUTO_TEST_CASE().
CreateImageWithSquare()
void CreateImageWithSquare (const int size, Bitmap * bitmap)
Definition at line 50 of file sift_test.cc.
References colmap::Bitmap::Allocate(), colmap::Bitmap::Fill(), colmap::Bitmap::SetPixel(), and size.
Referenced by BOOST_AUTO_TEST_CASE().
CreateRandomFeatureDescriptors()
FeatureDescriptors CreateRandomFeatureDescriptors (const size_t num_features)
Definition at line 247 of file sift_test.cc.
References descriptors, colmap::FeatureDescriptorsToUnsignedByte(), colmap::L2NormalizeFeatureDescriptors(), colmap::RandomReal(), and colmap::SetPRNGSeed().
Referenced by BOOST_AUTO_TEST_CASE().