ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/similarity_transform_test.cc File Reference
similarity_transform_test.cc File Reference
#include "util/testing.h"
#include <Eigen/Core>
#include "base/pose.h"
#include "base/similarity_transform.h"
#include <fstream>
Macros
#define TEST_NAME "base/similarity_transform"
Functions
BOOST_AUTO_TEST_CASE (TestDefaultInitialization)
BOOST_AUTO_TEST_CASE (TestInitialization)
void TestEstimationWithNumCoords (const size_t num_coords)
BOOST_AUTO_TEST_CASE (TestEstimation)
BOOST_AUTO_TEST_CASE (TestFromFile)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/similarity_transform"
Definition at line 32 of file similarity_transform_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (TestDefaultInitialization)
Definition at line 44 of file similarity_transform_test.cc.
References colmap::SimilarityTransform3::Rotation(), colmap::SimilarityTransform3::Scale(), and colmap::SimilarityTransform3::Translation().
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (TestEstimation)
Definition at line 99 of file similarity_transform_test.cc.
References TestEstimationWithNumCoords().
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (TestFromFile)
Definition at line 104 of file similarity_transform_test.cc.
References cloudViewer::t::geometry::path.
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (TestInitialization)
Definition at line 59 of file similarity_transform_test.cc.
References e, colmap::NormalizeQuaternion(), colmap::SimilarityTransform3::Rotation(), colmap::SimilarityTransform3::Scale(), and colmap::SimilarityTransform3::Translation().
TestEstimationWithNumCoords()
void TestEstimationWithNumCoords (const size_t num_coords)
Definition at line 77 of file similarity_transform_test.cc.
References e, colmap::SimilarityTransform3::Estimate(), colmap::SimilarityTransform3::Matrix(), and colmap::SimilarityTransform3::TransformPoint().
Referenced by BOOST_AUTO_TEST_CASE().