ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/SQLite/sqlite3.h File Reference
sqlite3.h File Reference
#include <stdarg.h>
Classes
struct sqlite3_file
struct sqlite3_io_methods
struct sqlite3_vfs
struct sqlite3_mem_methods
struct sqlite3_module
struct sqlite3_index_info
struct sqlite3_index_info::sqlite3_index_constraint
struct sqlite3_index_info::sqlite3_index_orderby
struct sqlite3_index_info::sqlite3_index_constraint_usage
struct sqlite3_vtab
struct sqlite3_vtab_cursor
struct sqlite3_mutex_methods
struct sqlite3_pcache_page
struct sqlite3_pcache_methods2
struct sqlite3_pcache_methods
struct sqlite3_snapshot
struct sqlite3_rtree_geometry
struct sqlite3_rtree_query_info
struct Fts5PhraseIter
struct Fts5ExtensionApi
struct fts5_tokenizer
struct fts5_api
Macros
#define SQLITE_EXTERN extern
#define SQLITE_API
#define SQLITE_CDECL
#define SQLITE_APICALL
#define SQLITE_STDCALL SQLITE_APICALL
#define SQLITE_CALLBACK
#define SQLITE_SYSAPI
#define SQLITE_DEPRECATED
#define SQLITE_EXPERIMENTAL
#define SQLITE_VERSION "3.32.3"
#define SQLITE_VERSION_NUMBER 3032003
#define SQLITE_SOURCE_ID "2020-06-18 14:00:33 7ebdfa80be8e8e73324b8d66b3460222eb74c7e9dfd655b48d6ca7e1933cc8fd"
#define SQLITE_OK 0 /* Successful result */
#define SQLITE_ERROR 1 /* Generic error */
#define SQLITE_INTERNAL 2 /* Internal logic error in SQLite */
#define SQLITE_PERM 3 /* Access permission denied */
#define SQLITE_ABORT 4 /* Callback routine requested an abort */
#define SQLITE_BUSY 5 /* The database file is locked */
#define SQLITE_LOCKED 6 /* A table in the database is locked */
#define SQLITE_NOMEM 7 /* A malloc() failed */
#define SQLITE_READONLY 8 /* Attempt to write a readonly database */
#define SQLITE_INTERRUPT 9 /* Operation terminated by sqlite3_interrupt()*/
#define SQLITE_IOERR 10 /* Some kind of disk I/O error occurred */
#define SQLITE_CORRUPT 11 /* The database disk image is malformed */
#define SQLITE_NOTFOUND 12 /* Unknown opcode in sqlite3_file_control() */
#define SQLITE_FULL 13 /* Insertion failed because database is full */
#define SQLITE_CANTOPEN 14 /* Unable to open the database file */
#define SQLITE_PROTOCOL 15 /* Database lock protocol error */
#define SQLITE_EMPTY 16 /* Internal use only */
#define SQLITE_SCHEMA 17 /* The database schema changed */
#define SQLITE_TOOBIG 18 /* String or BLOB exceeds size limit */
#define SQLITE_CONSTRAINT 19 /* Abort due to constraint violation */
#define SQLITE_MISMATCH 20 /* Data type mismatch */
#define SQLITE_MISUSE 21 /* Library used incorrectly */
#define SQLITE_NOLFS 22 /* Uses OS features not supported on host */
#define SQLITE_AUTH 23 /* Authorization denied */
#define SQLITE_FORMAT 24 /* Not used */
#define SQLITE_RANGE 25 /* 2nd parameter to sqlite3_bind out of range */
#define SQLITE_NOTADB 26 /* File opened that is not a database file */
#define SQLITE_NOTICE 27 /* Notifications from sqlite3_log() */
#define SQLITE_WARNING 28 /* Warnings from sqlite3_log() */
#define SQLITE_ROW 100 /* sqlite3_step() has another row ready */
#define SQLITE_DONE 101 /* sqlite3_step() has finished executing */
#define SQLITE_ERROR_MISSING_COLLSEQ (SQLITE_ERROR | (1<<8))
#define SQLITE_ERROR_RETRY (SQLITE_ERROR | (2<<8))
#define SQLITE_ERROR_SNAPSHOT (SQLITE_ERROR | (3<<8))
#define SQLITE_IOERR_READ (SQLITE_IOERR | (1<<8))
#define SQLITE_IOERR_SHORT_READ (SQLITE_IOERR | (2<<8))
#define SQLITE_IOERR_WRITE (SQLITE_IOERR | (3<<8))
#define SQLITE_IOERR_FSYNC (SQLITE_IOERR | (4<<8))
#define SQLITE_IOERR_DIR_FSYNC (SQLITE_IOERR | (5<<8))
#define SQLITE_IOERR_TRUNCATE (SQLITE_IOERR | (6<<8))
#define SQLITE_IOERR_FSTAT (SQLITE_IOERR | (7<<8))
#define SQLITE_IOERR_UNLOCK (SQLITE_IOERR | (8<<8))
#define SQLITE_IOERR_RDLOCK (SQLITE_IOERR | (9<<8))
#define SQLITE_IOERR_DELETE (SQLITE_IOERR | (10<<8))
#define SQLITE_IOERR_BLOCKED (SQLITE_IOERR | (11<<8))
#define SQLITE_IOERR_NOMEM (SQLITE_IOERR | (12<<8))
#define SQLITE_IOERR_ACCESS (SQLITE_IOERR | (13<<8))
#define SQLITE_IOERR_CHECKRESERVEDLOCK (SQLITE_IOERR | (14<<8))
#define SQLITE_IOERR_LOCK (SQLITE_IOERR | (15<<8))
#define SQLITE_IOERR_CLOSE (SQLITE_IOERR | (16<<8))
#define SQLITE_IOERR_DIR_CLOSE (SQLITE_IOERR | (17<<8))
#define SQLITE_IOERR_SHMOPEN (SQLITE_IOERR | (18<<8))
#define SQLITE_IOERR_SHMSIZE (SQLITE_IOERR | (19<<8))
#define SQLITE_IOERR_SHMLOCK (SQLITE_IOERR | (20<<8))
#define SQLITE_IOERR_SHMMAP (SQLITE_IOERR | (21<<8))
#define SQLITE_IOERR_SEEK (SQLITE_IOERR | (22<<8))
#define SQLITE_IOERR_DELETE_NOENT (SQLITE_IOERR | (23<<8))
#define SQLITE_IOERR_MMAP (SQLITE_IOERR | (24<<8))
#define SQLITE_IOERR_GETTEMPPATH (SQLITE_IOERR | (25<<8))
#define SQLITE_IOERR_CONVPATH (SQLITE_IOERR | (26<<8))
#define SQLITE_IOERR_VNODE (SQLITE_IOERR | (27<<8))
#define SQLITE_IOERR_AUTH (SQLITE_IOERR | (28<<8))
#define SQLITE_IOERR_BEGIN_ATOMIC (SQLITE_IOERR | (29<<8))
#define SQLITE_IOERR_COMMIT_ATOMIC (SQLITE_IOERR | (30<<8))
#define SQLITE_IOERR_ROLLBACK_ATOMIC (SQLITE_IOERR | (31<<8))
#define SQLITE_IOERR_DATA (SQLITE_IOERR | (32<<8))
#define SQLITE_LOCKED_SHAREDCACHE (SQLITE_LOCKED | (1<<8))
#define SQLITE_LOCKED_VTAB (SQLITE_LOCKED | (2<<8))
#define SQLITE_BUSY_RECOVERY (SQLITE_BUSY | (1<<8))
#define SQLITE_BUSY_SNAPSHOT (SQLITE_BUSY | (2<<8))
#define SQLITE_BUSY_TIMEOUT (SQLITE_BUSY | (3<<8))
#define SQLITE_CANTOPEN_NOTEMPDIR (SQLITE_CANTOPEN | (1<<8))
#define SQLITE_CANTOPEN_ISDIR (SQLITE_CANTOPEN | (2<<8))
#define SQLITE_CANTOPEN_FULLPATH (SQLITE_CANTOPEN | (3<<8))
#define SQLITE_CANTOPEN_CONVPATH (SQLITE_CANTOPEN | (4<<8))
#define SQLITE_CANTOPEN_DIRTYWAL (SQLITE_CANTOPEN | (5<<8)) /* Not Used */
#define SQLITE_CANTOPEN_SYMLINK (SQLITE_CANTOPEN | (6<<8))
#define SQLITE_CORRUPT_VTAB (SQLITE_CORRUPT | (1<<8))
#define SQLITE_CORRUPT_SEQUENCE (SQLITE_CORRUPT | (2<<8))
#define SQLITE_CORRUPT_INDEX (SQLITE_CORRUPT | (3<<8))
#define SQLITE_READONLY_RECOVERY (SQLITE_READONLY | (1<<8))
#define SQLITE_READONLY_CANTLOCK (SQLITE_READONLY | (2<<8))
#define SQLITE_READONLY_ROLLBACK (SQLITE_READONLY | (3<<8))
#define SQLITE_READONLY_DBMOVED (SQLITE_READONLY | (4<<8))
#define SQLITE_READONLY_CANTINIT (SQLITE_READONLY | (5<<8))
#define SQLITE_READONLY_DIRECTORY (SQLITE_READONLY | (6<<8))
#define SQLITE_ABORT_ROLLBACK (SQLITE_ABORT | (2<<8))
#define SQLITE_CONSTRAINT_CHECK (SQLITE_CONSTRAINT | (1<<8))
#define SQLITE_CONSTRAINT_COMMITHOOK (SQLITE_CONSTRAINT | (2<<8))
#define SQLITE_CONSTRAINT_FOREIGNKEY (SQLITE_CONSTRAINT | (3<<8))
#define SQLITE_CONSTRAINT_FUNCTION (SQLITE_CONSTRAINT | (4<<8))
#define SQLITE_CONSTRAINT_NOTNULL (SQLITE_CONSTRAINT | (5<<8))
#define SQLITE_CONSTRAINT_PRIMARYKEY (SQLITE_CONSTRAINT | (6<<8))
#define SQLITE_CONSTRAINT_TRIGGER (SQLITE_CONSTRAINT | (7<<8))
#define SQLITE_CONSTRAINT_UNIQUE (SQLITE_CONSTRAINT | (8<<8))
#define SQLITE_CONSTRAINT_VTAB (SQLITE_CONSTRAINT | (9<<8))
#define SQLITE_CONSTRAINT_ROWID (SQLITE_CONSTRAINT |(10<<8))
#define SQLITE_CONSTRAINT_PINNED (SQLITE_CONSTRAINT |(11<<8))
#define SQLITE_NOTICE_RECOVER_WAL (SQLITE_NOTICE | (1<<8))
#define SQLITE_NOTICE_RECOVER_ROLLBACK (SQLITE_NOTICE | (2<<8))
#define SQLITE_WARNING_AUTOINDEX (SQLITE_WARNING | (1<<8))
#define SQLITE_AUTH_USER (SQLITE_AUTH | (1<<8))
#define SQLITE_OK_LOAD_PERMANENTLY (SQLITE_OK | (1<<8))
#define SQLITE_OK_SYMLINK (SQLITE_OK | (2<<8))
#define SQLITE_OPEN_READONLY 0x00000001 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_READWRITE 0x00000002 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_CREATE 0x00000004 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_DELETEONCLOSE 0x00000008 /* VFS only */
#define SQLITE_OPEN_EXCLUSIVE 0x00000010 /* VFS only */
#define SQLITE_OPEN_AUTOPROXY 0x00000020 /* VFS only */
#define SQLITE_OPEN_URI 0x00000040 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_MEMORY 0x00000080 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_MAIN_DB 0x00000100 /* VFS only */
#define SQLITE_OPEN_TEMP_DB 0x00000200 /* VFS only */
#define SQLITE_OPEN_TRANSIENT_DB 0x00000400 /* VFS only */
#define SQLITE_OPEN_MAIN_JOURNAL 0x00000800 /* VFS only */
#define SQLITE_OPEN_TEMP_JOURNAL 0x00001000 /* VFS only */
#define SQLITE_OPEN_SUBJOURNAL 0x00002000 /* VFS only */
#define SQLITE_OPEN_MASTER_JOURNAL 0x00004000 /* VFS only */
#define SQLITE_OPEN_NOMUTEX 0x00008000 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_FULLMUTEX 0x00010000 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_SHAREDCACHE 0x00020000 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_PRIVATECACHE 0x00040000 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_WAL 0x00080000 /* VFS only */
#define SQLITE_OPEN_NOFOLLOW 0x01000000 /* Ok for sqlite3_open_v2() */
#define SQLITE_IOCAP_ATOMIC 0x00000001
#define SQLITE_IOCAP_ATOMIC512 0x00000002
#define SQLITE_IOCAP_ATOMIC1K 0x00000004
#define SQLITE_IOCAP_ATOMIC2K 0x00000008
#define SQLITE_IOCAP_ATOMIC4K 0x00000010
#define SQLITE_IOCAP_ATOMIC8K 0x00000020
#define SQLITE_IOCAP_ATOMIC16K 0x00000040
#define SQLITE_IOCAP_ATOMIC32K 0x00000080
#define SQLITE_IOCAP_ATOMIC64K 0x00000100
#define SQLITE_IOCAP_SAFE_APPEND 0x00000200
#define SQLITE_IOCAP_SEQUENTIAL 0x00000400
#define SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN 0x00000800
#define SQLITE_IOCAP_POWERSAFE_OVERWRITE 0x00001000
#define SQLITE_IOCAP_IMMUTABLE 0x00002000
#define SQLITE_IOCAP_BATCH_ATOMIC 0x00004000
#define SQLITE_LOCK_NONE 0
#define SQLITE_LOCK_SHARED 1
#define SQLITE_LOCK_RESERVED 2
#define SQLITE_LOCK_PENDING 3
#define SQLITE_LOCK_EXCLUSIVE 4
#define SQLITE_SYNC_NORMAL 0x00002
#define SQLITE_SYNC_FULL 0x00003
#define SQLITE_SYNC_DATAONLY 0x00010
#define SQLITE_FCNTL_LOCKSTATE 1
#define SQLITE_FCNTL_GET_LOCKPROXYFILE 2
#define SQLITE_FCNTL_SET_LOCKPROXYFILE 3
#define SQLITE_FCNTL_LAST_ERRNO 4
#define SQLITE_FCNTL_SIZE_HINT 5
#define SQLITE_FCNTL_CHUNK_SIZE 6
#define SQLITE_FCNTL_FILE_POINTER 7
#define SQLITE_FCNTL_SYNC_OMITTED 8
#define SQLITE_FCNTL_WIN32_AV_RETRY 9
#define SQLITE_FCNTL_PERSIST_WAL 10
#define SQLITE_FCNTL_OVERWRITE 11
#define SQLITE_FCNTL_VFSNAME 12
#define SQLITE_FCNTL_POWERSAFE_OVERWRITE 13
#define SQLITE_FCNTL_PRAGMA 14
#define SQLITE_FCNTL_BUSYHANDLER 15
#define SQLITE_FCNTL_TEMPFILENAME 16
#define SQLITE_FCNTL_MMAP_SIZE 18
#define SQLITE_FCNTL_TRACE 19
#define SQLITE_FCNTL_HAS_MOVED 20
#define SQLITE_FCNTL_SYNC 21
#define SQLITE_FCNTL_COMMIT_PHASETWO 22
#define SQLITE_FCNTL_WIN32_SET_HANDLE 23
#define SQLITE_FCNTL_WAL_BLOCK 24
#define SQLITE_FCNTL_ZIPVFS 25
#define SQLITE_FCNTL_RBU 26
#define SQLITE_FCNTL_VFS_POINTER 27
#define SQLITE_FCNTL_JOURNAL_POINTER 28
#define SQLITE_FCNTL_WIN32_GET_HANDLE 29
#define SQLITE_FCNTL_PDB 30
#define SQLITE_FCNTL_BEGIN_ATOMIC_WRITE 31
#define SQLITE_FCNTL_COMMIT_ATOMIC_WRITE 32
#define SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE 33
#define SQLITE_FCNTL_LOCK_TIMEOUT 34
#define SQLITE_FCNTL_DATA_VERSION 35
#define SQLITE_FCNTL_SIZE_LIMIT 36
#define SQLITE_FCNTL_CKPT_DONE 37
#define SQLITE_FCNTL_RESERVE_BYTES 38
#define SQLITE_FCNTL_CKPT_START 39
#define SQLITE_GET_LOCKPROXYFILE SQLITE_FCNTL_GET_LOCKPROXYFILE
#define SQLITE_SET_LOCKPROXYFILE SQLITE_FCNTL_SET_LOCKPROXYFILE
#define SQLITE_LAST_ERRNO SQLITE_FCNTL_LAST_ERRNO
#define SQLITE_ACCESS_EXISTS 0
#define SQLITE_ACCESS_READWRITE 1 /* Used by PRAGMA temp_store_directory */
#define SQLITE_ACCESS_READ 2 /* Unused */
#define SQLITE_SHM_UNLOCK 1
#define SQLITE_SHM_LOCK 2
#define SQLITE_SHM_SHARED 4
#define SQLITE_SHM_EXCLUSIVE 8
#define SQLITE_SHM_NLOCK 8
#define SQLITE_CONFIG_SINGLETHREAD 1 /* nil */
#define SQLITE_CONFIG_MULTITHREAD 2 /* nil */
#define SQLITE_CONFIG_SERIALIZED 3 /* nil */
#define SQLITE_CONFIG_MALLOC 4 /* sqlite3_mem_methods* */
#define SQLITE_CONFIG_GETMALLOC 5 /* sqlite3_mem_methods* */
#define SQLITE_CONFIG_SCRATCH 6 /* No longer used */
#define SQLITE_CONFIG_PAGECACHE 7 /* void*, int sz, int N */
#define SQLITE_CONFIG_HEAP 8 /* void*, int nByte, int min */
#define SQLITE_CONFIG_MEMSTATUS 9 /* boolean */
#define SQLITE_CONFIG_MUTEX 10 /* sqlite3_mutex_methods* */
#define SQLITE_CONFIG_GETMUTEX 11 /* sqlite3_mutex_methods* */
#define SQLITE_CONFIG_LOOKASIDE 13 /* int int */
#define SQLITE_CONFIG_PCACHE 14 /* no-op */
#define SQLITE_CONFIG_GETPCACHE 15 /* no-op */
#define SQLITE_CONFIG_LOG 16 /* xFunc, void* */
#define SQLITE_CONFIG_URI 17 /* int */
#define SQLITE_CONFIG_PCACHE2 18 /* sqlite3_pcache_methods2* */
#define SQLITE_CONFIG_GETPCACHE2 19 /* sqlite3_pcache_methods2* */
#define SQLITE_CONFIG_COVERING_INDEX_SCAN 20 /* int */
#define SQLITE_CONFIG_SQLLOG 21 /* xSqllog, void* */
#define SQLITE_CONFIG_MMAP_SIZE 22 /* sqlite3_int64, sqlite3_int64 */
#define SQLITE_CONFIG_WIN32_HEAPSIZE 23 /* int nByte */
#define SQLITE_CONFIG_PCACHE_HDRSZ 24 /* int *psz */
#define SQLITE_CONFIG_PMASZ 25 /* unsigned int szPma */
#define SQLITE_CONFIG_STMTJRNL_SPILL 26 /* int nByte */
#define SQLITE_CONFIG_SMALL_MALLOC 27 /* boolean */
#define SQLITE_CONFIG_SORTERREF_SIZE 28 /* int nByte */
#define SQLITE_CONFIG_MEMDB_MAXSIZE 29 /* sqlite3_int64 */
#define SQLITE_DBCONFIG_MAINDBNAME 1000 /* const char* */
#define SQLITE_DBCONFIG_LOOKASIDE 1001 /* void* int int */
#define SQLITE_DBCONFIG_ENABLE_FKEY 1002 /* int int* */
#define SQLITE_DBCONFIG_ENABLE_TRIGGER 1003 /* int int* */
#define SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER 1004 /* int int* */
#define SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION 1005 /* int int* */
#define SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE 1006 /* int int* */
#define SQLITE_DBCONFIG_ENABLE_QPSG 1007 /* int int* */
#define SQLITE_DBCONFIG_TRIGGER_EQP 1008 /* int int* */
#define SQLITE_DBCONFIG_RESET_DATABASE 1009 /* int int* */
#define SQLITE_DBCONFIG_DEFENSIVE 1010 /* int int* */
#define SQLITE_DBCONFIG_WRITABLE_SCHEMA 1011 /* int int* */
#define SQLITE_DBCONFIG_LEGACY_ALTER_TABLE 1012 /* int int* */
#define SQLITE_DBCONFIG_DQS_DML 1013 /* int int* */
#define SQLITE_DBCONFIG_DQS_DDL 1014 /* int int* */
#define SQLITE_DBCONFIG_ENABLE_VIEW 1015 /* int int* */
#define SQLITE_DBCONFIG_LEGACY_FILE_FORMAT 1016 /* int int* */
#define SQLITE_DBCONFIG_TRUSTED_SCHEMA 1017 /* int int* */
#define SQLITE_DBCONFIG_MAX 1017 /* Largest DBCONFIG */
#define SQLITE_DENY 1 /* Abort the SQL statement with an error */
#define SQLITE_IGNORE 2 /* Don't allow access, but don't generate an error */
#define SQLITE_CREATE_INDEX 1 /* Index Name Table Name */
#define SQLITE_CREATE_TABLE 2 /* Table Name NULL */
#define SQLITE_CREATE_TEMP_INDEX 3 /* Index Name Table Name */
#define SQLITE_CREATE_TEMP_TABLE 4 /* Table Name NULL */
#define SQLITE_CREATE_TEMP_TRIGGER 5 /* Trigger Name Table Name */
#define SQLITE_CREATE_TEMP_VIEW 6 /* View Name NULL */
#define SQLITE_CREATE_TRIGGER 7 /* Trigger Name Table Name */
#define SQLITE_CREATE_VIEW 8 /* View Name NULL */
#define SQLITE_DELETE 9 /* Table Name NULL */
#define SQLITE_DROP_INDEX 10 /* Index Name Table Name */
#define SQLITE_DROP_TABLE 11 /* Table Name NULL */
#define SQLITE_DROP_TEMP_INDEX 12 /* Index Name Table Name */
#define SQLITE_DROP_TEMP_TABLE 13 /* Table Name NULL */
#define SQLITE_DROP_TEMP_TRIGGER 14 /* Trigger Name Table Name */
#define SQLITE_DROP_TEMP_VIEW 15 /* View Name NULL */
#define SQLITE_DROP_TRIGGER 16 /* Trigger Name Table Name */
#define SQLITE_DROP_VIEW 17 /* View Name NULL */
#define SQLITE_INSERT 18 /* Table Name NULL */
#define SQLITE_PRAGMA 19 /* Pragma Name 1st arg or NULL */
#define SQLITE_READ 20 /* Table Name Column Name */
#define SQLITE_SELECT 21 /* NULL NULL */
#define SQLITE_TRANSACTION 22 /* Operation NULL */
#define SQLITE_UPDATE 23 /* Table Name Column Name */
#define SQLITE_ATTACH 24 /* Filename NULL */
#define SQLITE_DETACH 25 /* Database Name NULL */
#define SQLITE_ALTER_TABLE 26 /* Database Name Table Name */
#define SQLITE_REINDEX 27 /* Index Name NULL */
#define SQLITE_ANALYZE 28 /* Table Name NULL */
#define SQLITE_CREATE_VTABLE 29 /* Table Name Module Name */
#define SQLITE_DROP_VTABLE 30 /* Table Name Module Name */
#define SQLITE_FUNCTION 31 /* NULL Function Name */
#define SQLITE_SAVEPOINT 32 /* Operation Savepoint Name */
#define SQLITE_COPY 0 /* No longer used */
#define SQLITE_RECURSIVE 33 /* NULL NULL */
#define SQLITE_TRACE_STMT 0x01
#define SQLITE_TRACE_PROFILE 0x02
#define SQLITE_TRACE_ROW 0x04
#define SQLITE_TRACE_CLOSE 0x08
#define SQLITE_LIMIT_LENGTH 0
#define SQLITE_LIMIT_SQL_LENGTH 1
#define SQLITE_LIMIT_COLUMN 2
#define SQLITE_LIMIT_EXPR_DEPTH 3
#define SQLITE_LIMIT_COMPOUND_SELECT 4
#define SQLITE_LIMIT_VDBE_OP 5
#define SQLITE_LIMIT_FUNCTION_ARG 6
#define SQLITE_LIMIT_ATTACHED 7
#define SQLITE_LIMIT_LIKE_PATTERN_LENGTH 8
#define SQLITE_LIMIT_VARIABLE_NUMBER 9
#define SQLITE_LIMIT_TRIGGER_DEPTH 10
#define SQLITE_LIMIT_WORKER_THREADS 11
#define SQLITE_PREPARE_PERSISTENT 0x01
#define SQLITE_PREPARE_NORMALIZE 0x02
#define SQLITE_PREPARE_NO_VTAB 0x04
#define SQLITE_INTEGER 1
#define SQLITE_FLOAT 2
#define SQLITE_BLOB 4
#define SQLITE_NULL 5
#define SQLITE_TEXT 3
#define SQLITE3_TEXT 3
#define SQLITE_UTF8 1 /* IMP: R-37514-35566 */
#define SQLITE_UTF16LE 2 /* IMP: R-03371-37637 */
#define SQLITE_UTF16BE 3 /* IMP: R-51971-34154 */
#define SQLITE_UTF16 4 /* Use native byte order */
#define SQLITE_ANY 5 /* Deprecated */
#define SQLITE_UTF16_ALIGNED 8 /* sqlite3_create_collation only */
#define SQLITE_DETERMINISTIC 0x000000800
#define SQLITE_DIRECTONLY 0x000080000
#define SQLITE_SUBTYPE 0x000100000
#define SQLITE_INNOCUOUS 0x000200000
#define SQLITE_STATIC ((sqlite3_destructor_type)0)
#define SQLITE_TRANSIENT ((sqlite3_destructor_type)-1)
#define SQLITE_WIN32_DATA_DIRECTORY_TYPE 1
#define SQLITE_WIN32_TEMP_DIRECTORY_TYPE 2
#define SQLITE_INDEX_SCAN_UNIQUE 1 /* Scan visits at most 1 row */
#define SQLITE_INDEX_CONSTRAINT_EQ 2
#define SQLITE_INDEX_CONSTRAINT_GT 4
#define SQLITE_INDEX_CONSTRAINT_LE 8
#define SQLITE_INDEX_CONSTRAINT_LT 16
#define SQLITE_INDEX_CONSTRAINT_GE 32
#define SQLITE_INDEX_CONSTRAINT_MATCH 64
#define SQLITE_INDEX_CONSTRAINT_LIKE 65
#define SQLITE_INDEX_CONSTRAINT_GLOB 66
#define SQLITE_INDEX_CONSTRAINT_REGEXP 67
#define SQLITE_INDEX_CONSTRAINT_NE 68
#define SQLITE_INDEX_CONSTRAINT_ISNOT 69
#define SQLITE_INDEX_CONSTRAINT_ISNOTNULL 70
#define SQLITE_INDEX_CONSTRAINT_ISNULL 71
#define SQLITE_INDEX_CONSTRAINT_IS 72
#define SQLITE_INDEX_CONSTRAINT_FUNCTION 150
#define SQLITE_MUTEX_FAST 0
#define SQLITE_MUTEX_RECURSIVE 1
#define SQLITE_MUTEX_STATIC_MASTER 2
#define SQLITE_MUTEX_STATIC_MEM 3 /* sqlite3_malloc() */
#define SQLITE_MUTEX_STATIC_MEM2 4 /* NOT USED */
#define SQLITE_MUTEX_STATIC_OPEN 4 /* sqlite3BtreeOpen() */
#define SQLITE_MUTEX_STATIC_PRNG 5 /* sqlite3_randomness() */
#define SQLITE_MUTEX_STATIC_LRU 6 /* lru page list */
#define SQLITE_MUTEX_STATIC_LRU2 7 /* NOT USED */
#define SQLITE_MUTEX_STATIC_PMEM 7 /* sqlite3PageMalloc() */
#define SQLITE_MUTEX_STATIC_APP1 8 /* For use by application */
#define SQLITE_MUTEX_STATIC_APP2 9 /* For use by application */
#define SQLITE_MUTEX_STATIC_APP3 10 /* For use by application */
#define SQLITE_MUTEX_STATIC_VFS1 11 /* For use by built-in VFS */
#define SQLITE_MUTEX_STATIC_VFS2 12 /* For use by extension VFS */
#define SQLITE_MUTEX_STATIC_VFS3 13 /* For use by application VFS */
#define SQLITE_TESTCTRL_FIRST 5
#define SQLITE_TESTCTRL_PRNG_SAVE 5
#define SQLITE_TESTCTRL_PRNG_RESTORE 6
#define SQLITE_TESTCTRL_PRNG_RESET 7 /* NOT USED */
#define SQLITE_TESTCTRL_BITVEC_TEST 8
#define SQLITE_TESTCTRL_FAULT_INSTALL 9
#define SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS 10
#define SQLITE_TESTCTRL_PENDING_BYTE 11
#define SQLITE_TESTCTRL_ASSERT 12
#define SQLITE_TESTCTRL_ALWAYS 13
#define SQLITE_TESTCTRL_RESERVE 14 /* NOT USED */
#define SQLITE_TESTCTRL_OPTIMIZATIONS 15
#define SQLITE_TESTCTRL_ISKEYWORD 16 /* NOT USED */
#define SQLITE_TESTCTRL_SCRATCHMALLOC 17 /* NOT USED */
#define SQLITE_TESTCTRL_INTERNAL_FUNCTIONS 17
#define SQLITE_TESTCTRL_LOCALTIME_FAULT 18
#define SQLITE_TESTCTRL_EXPLAIN_STMT 19 /* NOT USED */
#define SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD 19
#define SQLITE_TESTCTRL_NEVER_CORRUPT 20
#define SQLITE_TESTCTRL_VDBE_COVERAGE 21
#define SQLITE_TESTCTRL_BYTEORDER 22
#define SQLITE_TESTCTRL_ISINIT 23
#define SQLITE_TESTCTRL_SORTER_MMAP 24
#define SQLITE_TESTCTRL_IMPOSTER 25
#define SQLITE_TESTCTRL_PARSER_COVERAGE 26
#define SQLITE_TESTCTRL_RESULT_INTREAL 27
#define SQLITE_TESTCTRL_PRNG_SEED 28
#define SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS 29
#define SQLITE_TESTCTRL_LAST 29 /* Largest TESTCTRL */
#define SQLITE_STATUS_MEMORY_USED 0
#define SQLITE_STATUS_PAGECACHE_USED 1
#define SQLITE_STATUS_PAGECACHE_OVERFLOW 2
#define SQLITE_STATUS_SCRATCH_USED 3 /* NOT USED */
#define SQLITE_STATUS_SCRATCH_OVERFLOW 4 /* NOT USED */
#define SQLITE_STATUS_MALLOC_SIZE 5
#define SQLITE_STATUS_PARSER_STACK 6
#define SQLITE_STATUS_PAGECACHE_SIZE 7
#define SQLITE_STATUS_SCRATCH_SIZE 8 /* NOT USED */
#define SQLITE_STATUS_MALLOC_COUNT 9
#define SQLITE_DBSTATUS_LOOKASIDE_USED 0
#define SQLITE_DBSTATUS_CACHE_USED 1
#define SQLITE_DBSTATUS_SCHEMA_USED 2
#define SQLITE_DBSTATUS_STMT_USED 3
#define SQLITE_DBSTATUS_LOOKASIDE_HIT 4
#define SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE 5
#define SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL 6
#define SQLITE_DBSTATUS_CACHE_HIT 7
#define SQLITE_DBSTATUS_CACHE_MISS 8
#define SQLITE_DBSTATUS_CACHE_WRITE 9
#define SQLITE_DBSTATUS_DEFERRED_FKS 10
#define SQLITE_DBSTATUS_CACHE_USED_SHARED 11
#define SQLITE_DBSTATUS_CACHE_SPILL 12
#define SQLITE_DBSTATUS_MAX 12 /* Largest defined DBSTATUS */
#define SQLITE_STMTSTATUS_FULLSCAN_STEP 1
#define SQLITE_STMTSTATUS_SORT 2
#define SQLITE_STMTSTATUS_AUTOINDEX 3
#define SQLITE_STMTSTATUS_VM_STEP 4
#define SQLITE_STMTSTATUS_REPREPARE 5
#define SQLITE_STMTSTATUS_RUN 6
#define SQLITE_STMTSTATUS_MEMUSED 99
#define SQLITE_CHECKPOINT_PASSIVE 0 /* Do as much as possible w/o blocking */
#define SQLITE_CHECKPOINT_FULL 1 /* Wait for writers, then checkpoint */
#define SQLITE_CHECKPOINT_RESTART 2 /* Like FULL but wait for for readers */
#define SQLITE_CHECKPOINT_TRUNCATE 3 /* Like RESTART but also truncate WAL */
#define SQLITE_VTAB_CONSTRAINT_SUPPORT 1
#define SQLITE_VTAB_INNOCUOUS 2
#define SQLITE_VTAB_DIRECTONLY 3
#define SQLITE_ROLLBACK 1
#define SQLITE_FAIL 3
#define SQLITE_REPLACE 5
#define SQLITE_SCANSTAT_NLOOP 0
#define SQLITE_SCANSTAT_NVISIT 1
#define SQLITE_SCANSTAT_EST 2
#define SQLITE_SCANSTAT_NAME 3
#define SQLITE_SCANSTAT_EXPLAIN 4
#define SQLITE_SCANSTAT_SELECTID 5
#define SQLITE_SERIALIZE_NOCOPY 0x001 /* Do no memory allocations */
#define SQLITE_DESERIALIZE_FREEONCLOSE 1 /* Call sqlite3_free() on close */
#define SQLITE_DESERIALIZE_RESIZEABLE 2 /* Resize using sqlite3_realloc64() */
#define SQLITE_DESERIALIZE_READONLY 4 /* Database is read-only */
#define _SQLITE3RTREE_H_
#define NOT_WITHIN 0 /* Object completely outside of query region */
#define PARTLY_WITHIN 1 /* Object partially overlaps query region */
#define FULLY_WITHIN 2 /* Object fully contained within query region */
#define _FTS5_H
#define FTS5_TOKENIZE_QUERY 0x0001
#define FTS5_TOKENIZE_PREFIX 0x0002
#define FTS5_TOKENIZE_DOCUMENT 0x0004
#define FTS5_TOKENIZE_AUX 0x0008
#define FTS5_TOKEN_COLOCATED 0x0001 /* Same position as prev. token */
Typedefs
typedef struct sqlite3 sqlite3
typedef long long int sqlite_int64
typedef unsigned long long int sqlite_uint64
typedef sqlite_int64 sqlite3_int64
typedef sqlite_uint64 sqlite3_uint64
typedef int(* sqlite3_callback) (void *, int, char **, char **)
typedef struct sqlite3_file sqlite3_file
typedef struct sqlite3_io_methods sqlite3_io_methods
typedef struct sqlite3_mutex sqlite3_mutex
typedef struct sqlite3_api_routines sqlite3_api_routines
typedef struct sqlite3_vfs sqlite3_vfs
typedef void(* sqlite3_syscall_ptr) (void)
typedef struct sqlite3_mem_methods sqlite3_mem_methods
typedef struct sqlite3_stmt sqlite3_stmt
typedef struct sqlite3_value sqlite3_value
typedef struct sqlite3_context sqlite3_context
typedef void(* sqlite3_destructor_type) (void *)
typedef struct sqlite3_vtab sqlite3_vtab
typedef struct sqlite3_index_info sqlite3_index_info
typedef struct sqlite3_vtab_cursor sqlite3_vtab_cursor
typedef struct sqlite3_module sqlite3_module
typedef struct sqlite3_blob sqlite3_blob
typedef struct sqlite3_mutex_methods sqlite3_mutex_methods
typedef struct sqlite3_str sqlite3_str
typedef struct sqlite3_pcache sqlite3_pcache
typedef struct sqlite3_pcache_page sqlite3_pcache_page
typedef struct sqlite3_pcache_methods2 sqlite3_pcache_methods2
typedef struct sqlite3_pcache_methods sqlite3_pcache_methods
typedef struct sqlite3_backup sqlite3_backup
typedef struct sqlite3_snapshot sqlite3_snapshot
typedef struct sqlite3_rtree_geometry sqlite3_rtree_geometry
typedef struct sqlite3_rtree_query_info sqlite3_rtree_query_info
typedef double sqlite3_rtree_dbl
typedef struct Fts5ExtensionApi Fts5ExtensionApi
typedef struct Fts5Context Fts5Context
typedef struct Fts5PhraseIter Fts5PhraseIter
typedef void(* fts5_extension_function) (const Fts5ExtensionApi *pApi, Fts5Context *pFts, sqlite3_context *pCtx, int nVal, sqlite3_value **apVal)
typedef struct Fts5Tokenizer Fts5Tokenizer
typedef struct fts5_tokenizer fts5_tokenizer
typedef struct fts5_api fts5_api
Functions
const char * sqlite3_libversion (void)
const char * sqlite3_sourceid (void)
int sqlite3_libversion_number (void)
int sqlite3_compileoption_used (const char *zOptName)
const char * sqlite3_compileoption_get (int N)
int sqlite3_threadsafe (void)
int sqlite3_close (sqlite3 *)
int sqlite3_close_v2 (sqlite3 *)
int sqlite3_exec (sqlite3 *, const char *sql, int(*callback)(void *, int, char **, char **), void *, char **errmsg)
int sqlite3_initialize (void)
int sqlite3_shutdown (void)
int sqlite3_os_init (void)
int sqlite3_os_end (void)
int sqlite3_config (int,...)
int sqlite3_db_config (sqlite3 *, int op,...)
int sqlite3_extended_result_codes (sqlite3 *, int onoff)
sqlite3_int64 sqlite3_last_insert_rowid (sqlite3 *)
void sqlite3_set_last_insert_rowid (sqlite3 *, sqlite3_int64)
int sqlite3_changes (sqlite3 *)
int sqlite3_total_changes (sqlite3 *)
void sqlite3_interrupt (sqlite3 *)
int sqlite3_complete (const char *sql)
int sqlite3_complete16 (const void *sql)
int sqlite3_busy_handler (sqlite3 *, int(*)(void *, int), void *)
int sqlite3_busy_timeout (sqlite3 *, int ms)
int sqlite3_get_table (sqlite3 *db, const char *zSql, char ***pazResult, int *pnRow, int *pnColumn, char **pzErrmsg)
void sqlite3_free_table (char **result)
char * sqlite3_mprintf (const char *,...)
char * sqlite3_vmprintf (const char *, va_list)
char * sqlite3_snprintf (int, char *, const char *,...)
char * sqlite3_vsnprintf (int, char *, const char *, va_list)
void * sqlite3_malloc (int)
void * sqlite3_malloc64 (sqlite3_uint64)
void * sqlite3_realloc (void *, int)
void * sqlite3_realloc64 (void *, sqlite3_uint64)
void sqlite3_free (void *)
sqlite3_uint64 sqlite3_msize (void *)
sqlite3_int64 sqlite3_memory_used (void)
sqlite3_int64 sqlite3_memory_highwater (int resetFlag)
void sqlite3_randomness (int N, void *P)
int sqlite3_set_authorizer (sqlite3 *, int(*xAuth)(void *, int, const char *, const char *, const char *, const char *), void *pUserData)
void * sqlite3_trace (sqlite3 *, void(*xTrace)(void *, const char *), void *)
void * sqlite3_profile (sqlite3 *, void(*xProfile)(void *, const char *, sqlite3_uint64), void *)
int sqlite3_trace_v2 (sqlite3 *, unsigned uMask, int(*xCallback)(unsigned, void *, void *, void *), void *pCtx)
void sqlite3_progress_handler (sqlite3 *, int, int(*)(void *), void *)
int sqlite3_open (const char *filename, sqlite3 **ppDb)
int sqlite3_open16 (const void *filename, sqlite3 **ppDb)
int sqlite3_open_v2 (const char *filename, sqlite3 **ppDb, int flags, const char *zVfs)
const char * sqlite3_uri_parameter (const char *zFilename, const char *zParam)
int sqlite3_uri_boolean (const char *zFile, const char *zParam, int bDefault)
sqlite3_int64 sqlite3_uri_int64 (const char *, const char *, sqlite3_int64)
const char * sqlite3_uri_key (const char *zFilename, int N)
const char * sqlite3_filename_database (const char *)
const char * sqlite3_filename_journal (const char *)
const char * sqlite3_filename_wal (const char *)
sqlite3_file * sqlite3_database_file_object (const char *)
char * sqlite3_create_filename (const char *zDatabase, const char *zJournal, const char *zWal, int nParam, const char **azParam)
void sqlite3_free_filename (char *)
int sqlite3_errcode (sqlite3 *db)
int sqlite3_extended_errcode (sqlite3 *db)
const char * sqlite3_errmsg (sqlite3 *)
const void * sqlite3_errmsg16 (sqlite3 *)
const char * sqlite3_errstr (int)
int sqlite3_limit (sqlite3 *, int id, int newVal)
int sqlite3_prepare (sqlite3 *db, const char *zSql, int nByte, sqlite3_stmt **ppStmt, const char **pzTail)
int sqlite3_prepare_v2 (sqlite3 *db, const char *zSql, int nByte, sqlite3_stmt **ppStmt, const char **pzTail)
int sqlite3_prepare_v3 (sqlite3 *db, const char *zSql, int nByte, unsigned int prepFlags, sqlite3_stmt **ppStmt, const char **pzTail)
int sqlite3_prepare16 (sqlite3 *db, const void *zSql, int nByte, sqlite3_stmt **ppStmt, const void **pzTail)
int sqlite3_prepare16_v2 (sqlite3 *db, const void *zSql, int nByte, sqlite3_stmt **ppStmt, const void **pzTail)
int sqlite3_prepare16_v3 (sqlite3 *db, const void *zSql, int nByte, unsigned int prepFlags, sqlite3_stmt **ppStmt, const void **pzTail)
const char * sqlite3_sql (sqlite3_stmt *pStmt)
char * sqlite3_expanded_sql (sqlite3_stmt *pStmt)
const char * sqlite3_normalized_sql (sqlite3_stmt *pStmt)
int sqlite3_stmt_readonly (sqlite3_stmt *pStmt)
int sqlite3_stmt_isexplain (sqlite3_stmt *pStmt)
int sqlite3_stmt_busy (sqlite3_stmt *)
int sqlite3_bind_blob (sqlite3_stmt *, int, const void *, int n, void(*)(void *))
int sqlite3_bind_blob64 (sqlite3_stmt *, int, const void *, sqlite3_uint64, void(*)(void *))
int sqlite3_bind_double (sqlite3_stmt *, int, double)
int sqlite3_bind_int (sqlite3_stmt *, int, int)
int sqlite3_bind_int64 (sqlite3_stmt *, int, sqlite3_int64)
int sqlite3_bind_null (sqlite3_stmt *, int)
int sqlite3_bind_text (sqlite3_stmt *, int, const char *, int, void(*)(void *))
int sqlite3_bind_text16 (sqlite3_stmt *, int, const void *, int, void(*)(void *))
int sqlite3_bind_text64 (sqlite3_stmt *, int, const char *, sqlite3_uint64, void(*)(void *), unsigned char encoding)
int sqlite3_bind_value (sqlite3_stmt *, int, const sqlite3_value *)
int sqlite3_bind_pointer (sqlite3_stmt *, int, void *, const char *, void(*)(void *))
int sqlite3_bind_zeroblob (sqlite3_stmt *, int, int n)
int sqlite3_bind_zeroblob64 (sqlite3_stmt *, int, sqlite3_uint64)
int sqlite3_bind_parameter_count (sqlite3_stmt *)
const char * sqlite3_bind_parameter_name (sqlite3_stmt *, int)
int sqlite3_bind_parameter_index (sqlite3_stmt *, const char *zName)
int sqlite3_clear_bindings (sqlite3_stmt *)
int sqlite3_column_count (sqlite3_stmt *pStmt)
const char * sqlite3_column_name (sqlite3_stmt *, int N)
const void * sqlite3_column_name16 (sqlite3_stmt *, int N)
const char * sqlite3_column_database_name (sqlite3_stmt *, int)
const void * sqlite3_column_database_name16 (sqlite3_stmt *, int)
const char * sqlite3_column_table_name (sqlite3_stmt *, int)
const void * sqlite3_column_table_name16 (sqlite3_stmt *, int)
const char * sqlite3_column_origin_name (sqlite3_stmt *, int)
const void * sqlite3_column_origin_name16 (sqlite3_stmt *, int)
const char * sqlite3_column_decltype (sqlite3_stmt *, int)
const void * sqlite3_column_decltype16 (sqlite3_stmt *, int)
int sqlite3_step (sqlite3_stmt *)
int sqlite3_data_count (sqlite3_stmt *pStmt)
const void * sqlite3_column_blob (sqlite3_stmt *, int iCol)
double sqlite3_column_double (sqlite3_stmt *, int iCol)
int sqlite3_column_int (sqlite3_stmt *, int iCol)
sqlite3_int64 sqlite3_column_int64 (sqlite3_stmt *, int iCol)
const unsigned char * sqlite3_column_text (sqlite3_stmt *, int iCol)
const void * sqlite3_column_text16 (sqlite3_stmt *, int iCol)
sqlite3_value * sqlite3_column_value (sqlite3_stmt *, int iCol)
int sqlite3_column_bytes (sqlite3_stmt *, int iCol)
int sqlite3_column_bytes16 (sqlite3_stmt *, int iCol)
int sqlite3_column_type (sqlite3_stmt *, int iCol)
int sqlite3_finalize (sqlite3_stmt *pStmt)
int sqlite3_reset (sqlite3_stmt *pStmt)
int sqlite3_create_function (sqlite3 *db, const char *zFunctionName, int nArg, int eTextRep, void *pApp, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *))
int sqlite3_create_function16 (sqlite3 *db, const void *zFunctionName, int nArg, int eTextRep, void *pApp, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *))
int sqlite3_create_function_v2 (sqlite3 *db, const char *zFunctionName, int nArg, int eTextRep, void *pApp, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *), void(*xDestroy)(void *))
int sqlite3_create_window_function (sqlite3 *db, const char *zFunctionName, int nArg, int eTextRep, void *pApp, void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *), void(*xValue)(sqlite3_context *), void(*xInverse)(sqlite3_context *, int, sqlite3_value **), void(*xDestroy)(void *))
int sqlite3_aggregate_count (sqlite3_context *)
int sqlite3_expired (sqlite3_stmt *)
int sqlite3_transfer_bindings (sqlite3_stmt *, sqlite3_stmt *)
int sqlite3_global_recover (void)
void sqlite3_thread_cleanup (void)
int sqlite3_memory_alarm (void(*)(void *, sqlite3_int64, int), void *, sqlite3_int64)
const void * sqlite3_value_blob (sqlite3_value *)
double sqlite3_value_double (sqlite3_value *)
int sqlite3_value_int (sqlite3_value *)
sqlite3_int64 sqlite3_value_int64 (sqlite3_value *)
void * sqlite3_value_pointer (sqlite3_value *, const char *)
const unsigned char * sqlite3_value_text (sqlite3_value *)
const void * sqlite3_value_text16 (sqlite3_value *)
const void * sqlite3_value_text16le (sqlite3_value *)
const void * sqlite3_value_text16be (sqlite3_value *)
int sqlite3_value_bytes (sqlite3_value *)
int sqlite3_value_bytes16 (sqlite3_value *)
int sqlite3_value_type (sqlite3_value *)
int sqlite3_value_numeric_type (sqlite3_value *)
int sqlite3_value_nochange (sqlite3_value *)
int sqlite3_value_frombind (sqlite3_value *)
unsigned int sqlite3_value_subtype (sqlite3_value *)
sqlite3_value * sqlite3_value_dup (const sqlite3_value *)
void sqlite3_value_free (sqlite3_value *)
void * sqlite3_aggregate_context (sqlite3_context *, int nBytes)
void * sqlite3_user_data (sqlite3_context *)
sqlite3 * sqlite3_context_db_handle (sqlite3_context *)
void * sqlite3_get_auxdata (sqlite3_context *, int N)
void sqlite3_set_auxdata (sqlite3_context *, int N, void *, void(*)(void *))
void sqlite3_result_blob (sqlite3_context *, const void *, int, void(*)(void *))
void sqlite3_result_blob64 (sqlite3_context *, const void *, sqlite3_uint64, void(*)(void *))
void sqlite3_result_double (sqlite3_context *, double)
void sqlite3_result_error (sqlite3_context *, const char *, int)
void sqlite3_result_error16 (sqlite3_context *, const void *, int)
void sqlite3_result_error_toobig (sqlite3_context *)
void sqlite3_result_error_nomem (sqlite3_context *)
void sqlite3_result_error_code (sqlite3_context *, int)
void sqlite3_result_int (sqlite3_context *, int)
void sqlite3_result_int64 (sqlite3_context *, sqlite3_int64)
void sqlite3_result_null (sqlite3_context *)
void sqlite3_result_text (sqlite3_context *, const char *, int, void(*)(void *))
void sqlite3_result_text64 (sqlite3_context *, const char *, sqlite3_uint64, void(*)(void *), unsigned char encoding)
void sqlite3_result_text16 (sqlite3_context *, const void *, int, void(*)(void *))
void sqlite3_result_text16le (sqlite3_context *, const void *, int, void(*)(void *))
void sqlite3_result_text16be (sqlite3_context *, const void *, int, void(*)(void *))
void sqlite3_result_value (sqlite3_context *, sqlite3_value *)
void sqlite3_result_pointer (sqlite3_context *, void *, const char *, void(*)(void *))
void sqlite3_result_zeroblob (sqlite3_context *, int n)
int sqlite3_result_zeroblob64 (sqlite3_context *, sqlite3_uint64 n)
void sqlite3_result_subtype (sqlite3_context *, unsigned int)
int sqlite3_create_collation (sqlite3 *, const char *zName, int eTextRep, void *pArg, int(*xCompare)(void *, int, const void *, int, const void *))
int sqlite3_create_collation_v2 (sqlite3 *, const char *zName, int eTextRep, void *pArg, int(*xCompare)(void *, int, const void *, int, const void *), void(*xDestroy)(void *))
int sqlite3_create_collation16 (sqlite3 *, const void *zName, int eTextRep, void *pArg, int(*xCompare)(void *, int, const void *, int, const void *))
int sqlite3_collation_needed (sqlite3 *, void *, void(*)(void *, sqlite3 *, int eTextRep, const char *))
int sqlite3_collation_needed16 (sqlite3 *, void *, void(*)(void *, sqlite3 *, int eTextRep, const void *))
int sqlite3_sleep (int)
int sqlite3_win32_set_directory (unsigned long type, void *zValue)
int sqlite3_win32_set_directory8 (unsigned long type, const char *zValue)
int sqlite3_win32_set_directory16 (unsigned long type, const void *zValue)
int sqlite3_get_autocommit (sqlite3 *)
sqlite3 * sqlite3_db_handle (sqlite3_stmt *)
const char * sqlite3_db_filename (sqlite3 *db, const char *zDbName)
int sqlite3_db_readonly (sqlite3 *db, const char *zDbName)
sqlite3_stmt * sqlite3_next_stmt (sqlite3 *pDb, sqlite3_stmt *pStmt)
void * sqlite3_commit_hook (sqlite3 *, int(*)(void *), void *)
void * sqlite3_rollback_hook (sqlite3 *, void(*)(void *), void *)
void * sqlite3_update_hook (sqlite3 *, void(*)(void *, int, char const *, char const *, sqlite3_int64), void *)
int sqlite3_enable_shared_cache (int)
int sqlite3_release_memory (int)
int sqlite3_db_release_memory (sqlite3 *)
sqlite3_int64 sqlite3_soft_heap_limit64 (sqlite3_int64 N)
sqlite3_int64 sqlite3_hard_heap_limit64 (sqlite3_int64 N)
void sqlite3_soft_heap_limit (int N)
int sqlite3_table_column_metadata (sqlite3 *db, const char *zDbName, const char *zTableName, const char *zColumnName, char const **pzDataType, char const **pzCollSeq, int *pNotNull, int *pPrimaryKey, int *pAutoinc)
int sqlite3_load_extension (sqlite3 *db, const char *zFile, const char *zProc, char **pzErrMsg)
int sqlite3_enable_load_extension (sqlite3 *db, int onoff)
int sqlite3_auto_extension (void(*xEntryPoint)(void))
int sqlite3_cancel_auto_extension (void(*xEntryPoint)(void))
void sqlite3_reset_auto_extension (void)
int sqlite3_create_module (sqlite3 *db, const char *zName, const sqlite3_module *p, void *pClientData)
int sqlite3_create_module_v2 (sqlite3 *db, const char *zName, const sqlite3_module *p, void *pClientData, void(*xDestroy)(void *))
int sqlite3_drop_modules (sqlite3 *db, const char **azKeep)
int sqlite3_declare_vtab (sqlite3 *, const char *zSQL)
int sqlite3_overload_function (sqlite3 *, const char *zFuncName, int nArg)
int sqlite3_blob_open (sqlite3 *, const char *zDb, const char *zTable, const char *zColumn, sqlite3_int64 iRow, int flags, sqlite3_blob **ppBlob)
int sqlite3_blob_reopen (sqlite3_blob *, sqlite3_int64)
int sqlite3_blob_close (sqlite3_blob *)
int sqlite3_blob_bytes (sqlite3_blob *)
int sqlite3_blob_read (sqlite3_blob *, void *Z, int N, int iOffset)
int sqlite3_blob_write (sqlite3_blob *, const void *z, int n, int iOffset)
sqlite3_vfs * sqlite3_vfs_find (const char *zVfsName)
int sqlite3_vfs_register (sqlite3_vfs *, int makeDflt)
int sqlite3_vfs_unregister (sqlite3_vfs *)
sqlite3_mutex * sqlite3_mutex_alloc (int)
void sqlite3_mutex_free (sqlite3_mutex *)
void sqlite3_mutex_enter (sqlite3_mutex *)
int sqlite3_mutex_try (sqlite3_mutex *)
void sqlite3_mutex_leave (sqlite3_mutex *)
int sqlite3_mutex_held (sqlite3_mutex *)
int sqlite3_mutex_notheld (sqlite3_mutex *)
sqlite3_mutex * sqlite3_db_mutex (sqlite3 *)
int sqlite3_file_control (sqlite3 *, const char *zDbName, int op, void *)
int sqlite3_test_control (int op,...)
int sqlite3_keyword_count (void)
int sqlite3_keyword_name (int, const char **, int *)
int sqlite3_keyword_check (const char *, int)
sqlite3_str * sqlite3_str_new (sqlite3 *)
char * sqlite3_str_finish (sqlite3_str *)
void sqlite3_str_appendf (sqlite3_str *, const char *zFormat,...)
void sqlite3_str_vappendf (sqlite3_str *, const char *zFormat, va_list)
void sqlite3_str_append (sqlite3_str *, const char *zIn, int N)
void sqlite3_str_appendall (sqlite3_str *, const char *zIn)
void sqlite3_str_appendchar (sqlite3_str *, int N, char C)
void sqlite3_str_reset (sqlite3_str *)
int sqlite3_str_errcode (sqlite3_str *)
int sqlite3_str_length (sqlite3_str *)
char * sqlite3_str_value (sqlite3_str *)
int sqlite3_status (int op, int *pCurrent, int *pHighwater, int resetFlag)
int sqlite3_status64 (int op, sqlite3_int64 *pCurrent, sqlite3_int64 *pHighwater, int resetFlag)
int sqlite3_db_status (sqlite3 *, int op, int *pCur, int *pHiwtr, int resetFlg)
int sqlite3_stmt_status (sqlite3_stmt *, int op, int resetFlg)
sqlite3_backup * sqlite3_backup_init (sqlite3 *pDest, const char *zDestName, sqlite3 *pSource, const char *zSourceName)
int sqlite3_backup_step (sqlite3_backup *p, int nPage)
int sqlite3_backup_finish (sqlite3_backup *p)
int sqlite3_backup_remaining (sqlite3_backup *p)
int sqlite3_backup_pagecount (sqlite3_backup *p)
int sqlite3_unlock_notify (sqlite3 *pBlocked, void(*xNotify)(void **apArg, int nArg), void *pNotifyArg)
int sqlite3_stricmp (const char *, const char *)
int sqlite3_strnicmp (const char *, const char *, int)
int sqlite3_strglob (const char *zGlob, const char *zStr)
int sqlite3_strlike (const char *zGlob, const char *zStr, unsigned int cEsc)
void sqlite3_log (int iErrCode, const char *zFormat,...)
void * sqlite3_wal_hook (sqlite3 *, int(*)(void *, sqlite3 *, const char *, int), void *)
int sqlite3_wal_autocheckpoint (sqlite3 *db, int N)
int sqlite3_wal_checkpoint (sqlite3 *db, const char *zDb)
int sqlite3_wal_checkpoint_v2 (sqlite3 *db, const char *zDb, int eMode, int *pnLog, int *pnCkpt)
int sqlite3_vtab_config (sqlite3 *, int op,...)
int sqlite3_vtab_on_conflict (sqlite3 *)
int sqlite3_vtab_nochange (sqlite3_context *)
const char * sqlite3_vtab_collation (sqlite3_index_info *, int)
int sqlite3_stmt_scanstatus (sqlite3_stmt *pStmt, int idx, int iScanStatusOp, void *pOut)
void sqlite3_stmt_scanstatus_reset (sqlite3_stmt *)
int sqlite3_db_cacheflush (sqlite3 *)
int sqlite3_system_errno (sqlite3 *)
int sqlite3_snapshot_get (sqlite3 *db, const char *zSchema, sqlite3_snapshot **ppSnapshot)
int sqlite3_snapshot_open (sqlite3 *db, const char *zSchema, sqlite3_snapshot *pSnapshot)
void sqlite3_snapshot_free (sqlite3_snapshot *)
int sqlite3_snapshot_cmp (sqlite3_snapshot *p1, sqlite3_snapshot *p2)
int sqlite3_snapshot_recover (sqlite3 *db, const char *zDb)
unsigned char * sqlite3_serialize (sqlite3 *db, const char *zSchema, sqlite3_int64 *piSize, unsigned int mFlags)
int sqlite3_deserialize (sqlite3 *db, const char *zSchema, unsigned char *pData, sqlite3_int64 szDb, sqlite3_int64 szBuf, unsigned mFlags)
int sqlite3_rtree_geometry_callback (sqlite3 *db, const char *zGeom, int(*xGeom)(sqlite3_rtree_geometry *, int, sqlite3_rtree_dbl *, int *), void *pContext)
int sqlite3_rtree_query_callback (sqlite3 *db, const char *zQueryFunc, int(*xQueryFunc)(sqlite3_rtree_query_info *), void *pContext, void(*xDestructor)(void *))
Variables
const char sqlite3_version []
char * sqlite3_temp_directory
char * sqlite3_data_directory
Macro Definition Documentation
_FTS5_H
#define _FTS5_H
Definition at line 11614 of file sqlite3.h.
_SQLITE3RTREE_H_
#define _SQLITE3RTREE_H_
Definition at line 9826 of file sqlite3.h.
FTS5_TOKEN_COLOCATED
#define FTS5_TOKEN_COLOCATED 0x0001 /* Same position as prev. token */
Definition at line 12118 of file sqlite3.h.
FTS5_TOKENIZE_AUX
#define FTS5_TOKENIZE_AUX 0x0008
Definition at line 12114 of file sqlite3.h.
FTS5_TOKENIZE_DOCUMENT
#define FTS5_TOKENIZE_DOCUMENT 0x0004
Definition at line 12113 of file sqlite3.h.
FTS5_TOKENIZE_PREFIX
#define FTS5_TOKENIZE_PREFIX 0x0002
Definition at line 12112 of file sqlite3.h.
FTS5_TOKENIZE_QUERY
#define FTS5_TOKENIZE_QUERY 0x0001
Definition at line 12111 of file sqlite3.h.
FULLY_WITHIN
#define FULLY_WITHIN 2 /* Object fully contained within query region */
Definition at line 9920 of file sqlite3.h.
NOT_WITHIN
#define NOT_WITHIN 0 /* Object completely outside of query region */
Definition at line 9918 of file sqlite3.h.
PARTLY_WITHIN
#define PARTLY_WITHIN 1 /* Object partially overlaps query region */
Definition at line 9919 of file sqlite3.h.
SQLITE3_TEXT
#define SQLITE3_TEXT 3
Definition at line 4750 of file sqlite3.h.
SQLITE_ABORT
#define SQLITE_ABORT 4 /* Callback routine requested an abort */
Definition at line 426 of file sqlite3.h.
SQLITE_ABORT_ROLLBACK
#define SQLITE_ABORT_ROLLBACK (SQLITE_ABORT | (2<<8))
Definition at line 527 of file sqlite3.h.
SQLITE_ACCESS_EXISTS
#define SQLITE_ACCESS_EXISTS 0
Definition at line 1425 of file sqlite3.h.
SQLITE_ACCESS_READ
#define SQLITE_ACCESS_READ 2 /* Unused */
Definition at line 1427 of file sqlite3.h.
SQLITE_ACCESS_READWRITE
#define SQLITE_ACCESS_READWRITE 1 /* Used by PRAGMA temp_store_directory */
Definition at line 1426 of file sqlite3.h.
SQLITE_ALTER_TABLE
#define SQLITE_ALTER_TABLE 26 /* Database Name Table Name */
Definition at line 3095 of file sqlite3.h.
SQLITE_ANALYZE
#define SQLITE_ANALYZE 28 /* Table Name NULL */
Definition at line 3097 of file sqlite3.h.
SQLITE_ANY
#define SQLITE_ANY 5 /* Deprecated */
Definition at line 5206 of file sqlite3.h.
SQLITE_API
#define SQLITE_API
Definition at line 52 of file sqlite3.h.
SQLITE_APICALL
#define SQLITE_APICALL
Definition at line 58 of file sqlite3.h.
SQLITE_ATTACH
#define SQLITE_ATTACH 24 /* Filename NULL */
Definition at line 3093 of file sqlite3.h.
SQLITE_AUTH
#define SQLITE_AUTH 23 /* Authorization denied */
Definition at line 445 of file sqlite3.h.
SQLITE_AUTH_USER
#define SQLITE_AUTH_USER (SQLITE_AUTH | (1<<8))
Definition at line 542 of file sqlite3.h.
SQLITE_BLOB
#define SQLITE_BLOB 4
Definition at line 4743 of file sqlite3.h.
SQLITE_BUSY
#define SQLITE_BUSY 5 /* The database file is locked */
Definition at line 427 of file sqlite3.h.
SQLITE_BUSY_RECOVERY
#define SQLITE_BUSY_RECOVERY (SQLITE_BUSY | (1<<8))
Definition at line 509 of file sqlite3.h.
SQLITE_BUSY_SNAPSHOT
#define SQLITE_BUSY_SNAPSHOT (SQLITE_BUSY | (2<<8))
Definition at line 510 of file sqlite3.h.
SQLITE_BUSY_TIMEOUT
#define SQLITE_BUSY_TIMEOUT (SQLITE_BUSY | (3<<8))
Definition at line 511 of file sqlite3.h.
SQLITE_CALLBACK
#define SQLITE_CALLBACK
Definition at line 64 of file sqlite3.h.
SQLITE_CANTOPEN
#define SQLITE_CANTOPEN 14 /* Unable to open the database file */
Definition at line 436 of file sqlite3.h.
SQLITE_CANTOPEN_CONVPATH
#define SQLITE_CANTOPEN_CONVPATH (SQLITE_CANTOPEN | (4<<8))
Definition at line 515 of file sqlite3.h.
SQLITE_CANTOPEN_DIRTYWAL
#define SQLITE_CANTOPEN_DIRTYWAL (SQLITE_CANTOPEN | (5<<8)) /* Not Used */
Definition at line 516 of file sqlite3.h.
SQLITE_CANTOPEN_FULLPATH
#define SQLITE_CANTOPEN_FULLPATH (SQLITE_CANTOPEN | (3<<8))
Definition at line 514 of file sqlite3.h.
SQLITE_CANTOPEN_ISDIR
#define SQLITE_CANTOPEN_ISDIR (SQLITE_CANTOPEN | (2<<8))
Definition at line 513 of file sqlite3.h.
SQLITE_CANTOPEN_NOTEMPDIR
#define SQLITE_CANTOPEN_NOTEMPDIR (SQLITE_CANTOPEN | (1<<8))
Definition at line 512 of file sqlite3.h.
SQLITE_CANTOPEN_SYMLINK
#define SQLITE_CANTOPEN_SYMLINK (SQLITE_CANTOPEN | (6<<8))
Definition at line 517 of file sqlite3.h.
SQLITE_CDECL
#define SQLITE_CDECL
Definition at line 55 of file sqlite3.h.
SQLITE_CHECKPOINT_FULL
#define SQLITE_CHECKPOINT_FULL 1 /* Wait for writers, then checkpoint */
Definition at line 9083 of file sqlite3.h.
SQLITE_CHECKPOINT_PASSIVE
#define SQLITE_CHECKPOINT_PASSIVE 0 /* Do as much as possible w/o blocking */
Definition at line 9082 of file sqlite3.h.
SQLITE_CHECKPOINT_RESTART
#define SQLITE_CHECKPOINT_RESTART 2 /* Like FULL but wait for for readers */
Definition at line 9084 of file sqlite3.h.
SQLITE_CHECKPOINT_TRUNCATE
#define SQLITE_CHECKPOINT_TRUNCATE 3 /* Like RESTART but also truncate WAL */
Definition at line 9085 of file sqlite3.h.
SQLITE_CONFIG_COVERING_INDEX_SCAN
#define SQLITE_CONFIG_COVERING_INDEX_SCAN 20 /* int */
Definition at line 2046 of file sqlite3.h.
SQLITE_CONFIG_GETMALLOC
#define SQLITE_CONFIG_GETMALLOC 5 /* sqlite3_mem_methods* */
Definition at line 2031 of file sqlite3.h.
SQLITE_CONFIG_GETMUTEX
#define SQLITE_CONFIG_GETMUTEX 11 /* sqlite3_mutex_methods* */
Definition at line 2037 of file sqlite3.h.
SQLITE_CONFIG_GETPCACHE
#define SQLITE_CONFIG_GETPCACHE 15 /* no-op */
Definition at line 2041 of file sqlite3.h.
SQLITE_CONFIG_GETPCACHE2
#define SQLITE_CONFIG_GETPCACHE2 19 /* sqlite3_pcache_methods2* */
Definition at line 2045 of file sqlite3.h.
SQLITE_CONFIG_HEAP
#define SQLITE_CONFIG_HEAP 8 /* void*, int nByte, int min */
Definition at line 2034 of file sqlite3.h.
SQLITE_CONFIG_LOG
#define SQLITE_CONFIG_LOG 16 /* xFunc, void* */
Definition at line 2042 of file sqlite3.h.
SQLITE_CONFIG_LOOKASIDE
#define SQLITE_CONFIG_LOOKASIDE 13 /* int int */
Definition at line 2039 of file sqlite3.h.
SQLITE_CONFIG_MALLOC
#define SQLITE_CONFIG_MALLOC 4 /* sqlite3_mem_methods* */
Definition at line 2030 of file sqlite3.h.
SQLITE_CONFIG_MEMDB_MAXSIZE
#define SQLITE_CONFIG_MEMDB_MAXSIZE 29 /* sqlite3_int64 */
Definition at line 2055 of file sqlite3.h.
SQLITE_CONFIG_MEMSTATUS
#define SQLITE_CONFIG_MEMSTATUS 9 /* boolean */
Definition at line 2035 of file sqlite3.h.
SQLITE_CONFIG_MMAP_SIZE
#define SQLITE_CONFIG_MMAP_SIZE 22 /* sqlite3_int64, sqlite3_int64 */
Definition at line 2048 of file sqlite3.h.
SQLITE_CONFIG_MULTITHREAD
#define SQLITE_CONFIG_MULTITHREAD 2 /* nil */
Definition at line 2028 of file sqlite3.h.
SQLITE_CONFIG_MUTEX
#define SQLITE_CONFIG_MUTEX 10 /* sqlite3_mutex_methods* */
Definition at line 2036 of file sqlite3.h.
SQLITE_CONFIG_PAGECACHE
#define SQLITE_CONFIG_PAGECACHE 7 /* void*, int sz, int N */
Definition at line 2033 of file sqlite3.h.
SQLITE_CONFIG_PCACHE
#define SQLITE_CONFIG_PCACHE 14 /* no-op */
Definition at line 2040 of file sqlite3.h.
SQLITE_CONFIG_PCACHE2
#define SQLITE_CONFIG_PCACHE2 18 /* sqlite3_pcache_methods2* */
Definition at line 2044 of file sqlite3.h.
SQLITE_CONFIG_PCACHE_HDRSZ
#define SQLITE_CONFIG_PCACHE_HDRSZ 24 /* int *psz */
Definition at line 2050 of file sqlite3.h.
SQLITE_CONFIG_PMASZ
#define SQLITE_CONFIG_PMASZ 25 /* unsigned int szPma */
Definition at line 2051 of file sqlite3.h.
SQLITE_CONFIG_SCRATCH
#define SQLITE_CONFIG_SCRATCH 6 /* No longer used */
Definition at line 2032 of file sqlite3.h.
SQLITE_CONFIG_SERIALIZED
#define SQLITE_CONFIG_SERIALIZED 3 /* nil */
Definition at line 2029 of file sqlite3.h.
SQLITE_CONFIG_SINGLETHREAD
#define SQLITE_CONFIG_SINGLETHREAD 1 /* nil */
Definition at line 2027 of file sqlite3.h.
SQLITE_CONFIG_SMALL_MALLOC
#define SQLITE_CONFIG_SMALL_MALLOC 27 /* boolean */
Definition at line 2053 of file sqlite3.h.
SQLITE_CONFIG_SORTERREF_SIZE
#define SQLITE_CONFIG_SORTERREF_SIZE 28 /* int nByte */
Definition at line 2054 of file sqlite3.h.
SQLITE_CONFIG_SQLLOG
#define SQLITE_CONFIG_SQLLOG 21 /* xSqllog, void* */
Definition at line 2047 of file sqlite3.h.
SQLITE_CONFIG_STMTJRNL_SPILL
#define SQLITE_CONFIG_STMTJRNL_SPILL 26 /* int nByte */
Definition at line 2052 of file sqlite3.h.
SQLITE_CONFIG_URI
#define SQLITE_CONFIG_URI 17 /* int */
Definition at line 2043 of file sqlite3.h.
SQLITE_CONFIG_WIN32_HEAPSIZE
#define SQLITE_CONFIG_WIN32_HEAPSIZE 23 /* int nByte */
Definition at line 2049 of file sqlite3.h.
SQLITE_CONSTRAINT
#define SQLITE_CONSTRAINT 19 /* Abort due to constraint violation */
Definition at line 441 of file sqlite3.h.
SQLITE_CONSTRAINT_CHECK
#define SQLITE_CONSTRAINT_CHECK (SQLITE_CONSTRAINT | (1<<8))
Definition at line 528 of file sqlite3.h.
SQLITE_CONSTRAINT_COMMITHOOK
#define SQLITE_CONSTRAINT_COMMITHOOK (SQLITE_CONSTRAINT | (2<<8))
Definition at line 529 of file sqlite3.h.
SQLITE_CONSTRAINT_FOREIGNKEY
#define SQLITE_CONSTRAINT_FOREIGNKEY (SQLITE_CONSTRAINT | (3<<8))
Definition at line 530 of file sqlite3.h.
SQLITE_CONSTRAINT_FUNCTION
#define SQLITE_CONSTRAINT_FUNCTION (SQLITE_CONSTRAINT | (4<<8))
Definition at line 531 of file sqlite3.h.
SQLITE_CONSTRAINT_NOTNULL
#define SQLITE_CONSTRAINT_NOTNULL (SQLITE_CONSTRAINT | (5<<8))
Definition at line 532 of file sqlite3.h.
SQLITE_CONSTRAINT_PINNED
#define SQLITE_CONSTRAINT_PINNED (SQLITE_CONSTRAINT |(11<<8))
Definition at line 538 of file sqlite3.h.
SQLITE_CONSTRAINT_PRIMARYKEY
#define SQLITE_CONSTRAINT_PRIMARYKEY (SQLITE_CONSTRAINT | (6<<8))
Definition at line 533 of file sqlite3.h.
SQLITE_CONSTRAINT_ROWID
#define SQLITE_CONSTRAINT_ROWID (SQLITE_CONSTRAINT |(10<<8))
Definition at line 537 of file sqlite3.h.
SQLITE_CONSTRAINT_TRIGGER
#define SQLITE_CONSTRAINT_TRIGGER (SQLITE_CONSTRAINT | (7<<8))
Definition at line 534 of file sqlite3.h.
SQLITE_CONSTRAINT_UNIQUE
#define SQLITE_CONSTRAINT_UNIQUE (SQLITE_CONSTRAINT | (8<<8))
Definition at line 535 of file sqlite3.h.
SQLITE_CONSTRAINT_VTAB
#define SQLITE_CONSTRAINT_VTAB (SQLITE_CONSTRAINT | (9<<8))
Definition at line 536 of file sqlite3.h.
SQLITE_COPY
#define SQLITE_COPY 0 /* No longer used */
Definition at line 3102 of file sqlite3.h.
SQLITE_CORRUPT
#define SQLITE_CORRUPT 11 /* The database disk image is malformed */
Definition at line 433 of file sqlite3.h.
SQLITE_CORRUPT_INDEX
#define SQLITE_CORRUPT_INDEX (SQLITE_CORRUPT | (3<<8))
Definition at line 520 of file sqlite3.h.
SQLITE_CORRUPT_SEQUENCE
#define SQLITE_CORRUPT_SEQUENCE (SQLITE_CORRUPT | (2<<8))
Definition at line 519 of file sqlite3.h.
SQLITE_CORRUPT_VTAB
#define SQLITE_CORRUPT_VTAB (SQLITE_CORRUPT | (1<<8))
Definition at line 518 of file sqlite3.h.
SQLITE_CREATE_INDEX
#define SQLITE_CREATE_INDEX 1 /* Index Name Table Name */
Definition at line 3070 of file sqlite3.h.
SQLITE_CREATE_TABLE
#define SQLITE_CREATE_TABLE 2 /* Table Name NULL */
Definition at line 3071 of file sqlite3.h.
SQLITE_CREATE_TEMP_INDEX
#define SQLITE_CREATE_TEMP_INDEX 3 /* Index Name Table Name */
Definition at line 3072 of file sqlite3.h.
SQLITE_CREATE_TEMP_TABLE
#define SQLITE_CREATE_TEMP_TABLE 4 /* Table Name NULL */
Definition at line 3073 of file sqlite3.h.
SQLITE_CREATE_TEMP_TRIGGER
#define SQLITE_CREATE_TEMP_TRIGGER 5 /* Trigger Name Table Name */
Definition at line 3074 of file sqlite3.h.
SQLITE_CREATE_TEMP_VIEW
#define SQLITE_CREATE_TEMP_VIEW 6 /* View Name NULL */
Definition at line 3075 of file sqlite3.h.
SQLITE_CREATE_TRIGGER
#define SQLITE_CREATE_TRIGGER 7 /* Trigger Name Table Name */
Definition at line 3076 of file sqlite3.h.
SQLITE_CREATE_VIEW
#define SQLITE_CREATE_VIEW 8 /* View Name NULL */
Definition at line 3077 of file sqlite3.h.
SQLITE_CREATE_VTABLE
#define SQLITE_CREATE_VTABLE 29 /* Table Name Module Name */
Definition at line 3098 of file sqlite3.h.
SQLITE_DBCONFIG_DEFENSIVE
#define SQLITE_DBCONFIG_DEFENSIVE 1010 /* int int* */
Definition at line 2337 of file sqlite3.h.
SQLITE_DBCONFIG_DQS_DDL
#define SQLITE_DBCONFIG_DQS_DDL 1014 /* int int* */
Definition at line 2341 of file sqlite3.h.
SQLITE_DBCONFIG_DQS_DML
#define SQLITE_DBCONFIG_DQS_DML 1013 /* int int* */
Definition at line 2340 of file sqlite3.h.
SQLITE_DBCONFIG_ENABLE_FKEY
#define SQLITE_DBCONFIG_ENABLE_FKEY 1002 /* int int* */
Definition at line 2329 of file sqlite3.h.
SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER
#define SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER 1004 /* int int* */
Definition at line 2331 of file sqlite3.h.
SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION
#define SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION 1005 /* int int* */
Definition at line 2332 of file sqlite3.h.
SQLITE_DBCONFIG_ENABLE_QPSG
#define SQLITE_DBCONFIG_ENABLE_QPSG 1007 /* int int* */
Definition at line 2334 of file sqlite3.h.
SQLITE_DBCONFIG_ENABLE_TRIGGER
#define SQLITE_DBCONFIG_ENABLE_TRIGGER 1003 /* int int* */
Definition at line 2330 of file sqlite3.h.
SQLITE_DBCONFIG_ENABLE_VIEW
#define SQLITE_DBCONFIG_ENABLE_VIEW 1015 /* int int* */
Definition at line 2342 of file sqlite3.h.
SQLITE_DBCONFIG_LEGACY_ALTER_TABLE
#define SQLITE_DBCONFIG_LEGACY_ALTER_TABLE 1012 /* int int* */
Definition at line 2339 of file sqlite3.h.
SQLITE_DBCONFIG_LEGACY_FILE_FORMAT
#define SQLITE_DBCONFIG_LEGACY_FILE_FORMAT 1016 /* int int* */
Definition at line 2343 of file sqlite3.h.
SQLITE_DBCONFIG_LOOKASIDE
#define SQLITE_DBCONFIG_LOOKASIDE 1001 /* void* int int */
Definition at line 2328 of file sqlite3.h.
SQLITE_DBCONFIG_MAINDBNAME
#define SQLITE_DBCONFIG_MAINDBNAME 1000 /* const char* */
Definition at line 2327 of file sqlite3.h.
SQLITE_DBCONFIG_MAX
#define SQLITE_DBCONFIG_MAX 1017 /* Largest DBCONFIG */
Definition at line 2345 of file sqlite3.h.
SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE
#define SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE 1006 /* int int* */
Definition at line 2333 of file sqlite3.h.
SQLITE_DBCONFIG_RESET_DATABASE
#define SQLITE_DBCONFIG_RESET_DATABASE 1009 /* int int* */
Definition at line 2336 of file sqlite3.h.
SQLITE_DBCONFIG_TRIGGER_EQP
#define SQLITE_DBCONFIG_TRIGGER_EQP 1008 /* int int* */
Definition at line 2335 of file sqlite3.h.
SQLITE_DBCONFIG_TRUSTED_SCHEMA
#define SQLITE_DBCONFIG_TRUSTED_SCHEMA 1017 /* int int* */
Definition at line 2344 of file sqlite3.h.
SQLITE_DBCONFIG_WRITABLE_SCHEMA
#define SQLITE_DBCONFIG_WRITABLE_SCHEMA 1011 /* int int* */
Definition at line 2338 of file sqlite3.h.
SQLITE_DBSTATUS_CACHE_HIT
#define SQLITE_DBSTATUS_CACHE_HIT 7
Definition at line 8150 of file sqlite3.h.
SQLITE_DBSTATUS_CACHE_MISS
#define SQLITE_DBSTATUS_CACHE_MISS 8
Definition at line 8151 of file sqlite3.h.
SQLITE_DBSTATUS_CACHE_SPILL
#define SQLITE_DBSTATUS_CACHE_SPILL 12
Definition at line 8155 of file sqlite3.h.
SQLITE_DBSTATUS_CACHE_USED
#define SQLITE_DBSTATUS_CACHE_USED 1
Definition at line 8144 of file sqlite3.h.
SQLITE_DBSTATUS_CACHE_USED_SHARED
#define SQLITE_DBSTATUS_CACHE_USED_SHARED 11
Definition at line 8154 of file sqlite3.h.
SQLITE_DBSTATUS_CACHE_WRITE
#define SQLITE_DBSTATUS_CACHE_WRITE 9
Definition at line 8152 of file sqlite3.h.
SQLITE_DBSTATUS_DEFERRED_FKS
#define SQLITE_DBSTATUS_DEFERRED_FKS 10
Definition at line 8153 of file sqlite3.h.
SQLITE_DBSTATUS_LOOKASIDE_HIT
#define SQLITE_DBSTATUS_LOOKASIDE_HIT 4
Definition at line 8147 of file sqlite3.h.
SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL
#define SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL 6
Definition at line 8149 of file sqlite3.h.
SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE
#define SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE 5
Definition at line 8148 of file sqlite3.h.
SQLITE_DBSTATUS_LOOKASIDE_USED
#define SQLITE_DBSTATUS_LOOKASIDE_USED 0
Definition at line 8143 of file sqlite3.h.
SQLITE_DBSTATUS_MAX
#define SQLITE_DBSTATUS_MAX 12 /* Largest defined DBSTATUS */
Definition at line 8156 of file sqlite3.h.
SQLITE_DBSTATUS_SCHEMA_USED
#define SQLITE_DBSTATUS_SCHEMA_USED 2
Definition at line 8145 of file sqlite3.h.
SQLITE_DBSTATUS_STMT_USED
#define SQLITE_DBSTATUS_STMT_USED 3
Definition at line 8146 of file sqlite3.h.
SQLITE_DELETE
#define SQLITE_DELETE 9 /* Table Name NULL */
Definition at line 3078 of file sqlite3.h.
SQLITE_DENY
#define SQLITE_DENY 1 /* Abort the SQL statement with an error */
Definition at line 3047 of file sqlite3.h.
SQLITE_DEPRECATED
#define SQLITE_DEPRECATED
Definition at line 83 of file sqlite3.h.
SQLITE_DESERIALIZE_FREEONCLOSE
#define SQLITE_DESERIALIZE_FREEONCLOSE 1 /* Call sqlite3_free() on close */
Definition at line 9794 of file sqlite3.h.
SQLITE_DESERIALIZE_READONLY
#define SQLITE_DESERIALIZE_READONLY 4 /* Database is read-only */
Definition at line 9796 of file sqlite3.h.
SQLITE_DESERIALIZE_RESIZEABLE
#define SQLITE_DESERIALIZE_RESIZEABLE 2 /* Resize using sqlite3_realloc64() */
Definition at line 9795 of file sqlite3.h.
SQLITE_DETACH
#define SQLITE_DETACH 25 /* Database Name NULL */
Definition at line 3094 of file sqlite3.h.
SQLITE_DETERMINISTIC
#define SQLITE_DETERMINISTIC 0x000000800
Definition at line 5274 of file sqlite3.h.
SQLITE_DIRECTONLY
#define SQLITE_DIRECTONLY 0x000080000
Definition at line 5275 of file sqlite3.h.
SQLITE_DONE
#define SQLITE_DONE 101 /* sqlite3_step() has finished executing */
Definition at line 452 of file sqlite3.h.
SQLITE_DROP_INDEX
#define SQLITE_DROP_INDEX 10 /* Index Name Table Name */
Definition at line 3079 of file sqlite3.h.
SQLITE_DROP_TABLE
#define SQLITE_DROP_TABLE 11 /* Table Name NULL */
Definition at line 3080 of file sqlite3.h.
SQLITE_DROP_TEMP_INDEX
#define SQLITE_DROP_TEMP_INDEX 12 /* Index Name Table Name */
Definition at line 3081 of file sqlite3.h.
SQLITE_DROP_TEMP_TABLE
#define SQLITE_DROP_TEMP_TABLE 13 /* Table Name NULL */
Definition at line 3082 of file sqlite3.h.
SQLITE_DROP_TEMP_TRIGGER
#define SQLITE_DROP_TEMP_TRIGGER 14 /* Trigger Name Table Name */
Definition at line 3083 of file sqlite3.h.
SQLITE_DROP_TEMP_VIEW
#define SQLITE_DROP_TEMP_VIEW 15 /* View Name NULL */
Definition at line 3084 of file sqlite3.h.
SQLITE_DROP_TRIGGER
#define SQLITE_DROP_TRIGGER 16 /* Trigger Name Table Name */
Definition at line 3085 of file sqlite3.h.
SQLITE_DROP_VIEW
#define SQLITE_DROP_VIEW 17 /* View Name NULL */
Definition at line 3086 of file sqlite3.h.
SQLITE_DROP_VTABLE
#define SQLITE_DROP_VTABLE 30 /* Table Name Module Name */
Definition at line 3099 of file sqlite3.h.
SQLITE_EMPTY
#define SQLITE_EMPTY 16 /* Internal use only */
Definition at line 438 of file sqlite3.h.
SQLITE_ERROR
#define SQLITE_ERROR 1 /* Generic error */
Definition at line 423 of file sqlite3.h.
SQLITE_ERROR_MISSING_COLLSEQ
#define SQLITE_ERROR_MISSING_COLLSEQ (SQLITE_ERROR | (1<<8))
Definition at line 472 of file sqlite3.h.
SQLITE_ERROR_RETRY
#define SQLITE_ERROR_RETRY (SQLITE_ERROR | (2<<8))
Definition at line 473 of file sqlite3.h.
SQLITE_ERROR_SNAPSHOT
#define SQLITE_ERROR_SNAPSHOT (SQLITE_ERROR | (3<<8))
Definition at line 474 of file sqlite3.h.
SQLITE_EXPERIMENTAL
#define SQLITE_EXPERIMENTAL
Definition at line 84 of file sqlite3.h.
SQLITE_EXTERN
#define SQLITE_EXTERN extern
Definition at line 49 of file sqlite3.h.
SQLITE_FAIL
#define SQLITE_FAIL 3
Definition at line 9233 of file sqlite3.h.
SQLITE_FCNTL_BEGIN_ATOMIC_WRITE
#define SQLITE_FCNTL_BEGIN_ATOMIC_WRITE 31
Definition at line 1157 of file sqlite3.h.
SQLITE_FCNTL_BUSYHANDLER
#define SQLITE_FCNTL_BUSYHANDLER 15
Definition at line 1142 of file sqlite3.h.
SQLITE_FCNTL_CHUNK_SIZE
#define SQLITE_FCNTL_CHUNK_SIZE 6
Definition at line 1133 of file sqlite3.h.
SQLITE_FCNTL_CKPT_DONE
#define SQLITE_FCNTL_CKPT_DONE 37
Definition at line 1163 of file sqlite3.h.
SQLITE_FCNTL_CKPT_START
#define SQLITE_FCNTL_CKPT_START 39
Definition at line 1165 of file sqlite3.h.
SQLITE_FCNTL_COMMIT_ATOMIC_WRITE
#define SQLITE_FCNTL_COMMIT_ATOMIC_WRITE 32
Definition at line 1158 of file sqlite3.h.
SQLITE_FCNTL_COMMIT_PHASETWO
#define SQLITE_FCNTL_COMMIT_PHASETWO 22
Definition at line 1148 of file sqlite3.h.
SQLITE_FCNTL_DATA_VERSION
#define SQLITE_FCNTL_DATA_VERSION 35
Definition at line 1161 of file sqlite3.h.
SQLITE_FCNTL_FILE_POINTER
#define SQLITE_FCNTL_FILE_POINTER 7
Definition at line 1134 of file sqlite3.h.
SQLITE_FCNTL_GET_LOCKPROXYFILE
#define SQLITE_FCNTL_GET_LOCKPROXYFILE 2
Definition at line 1129 of file sqlite3.h.
SQLITE_FCNTL_HAS_MOVED
#define SQLITE_FCNTL_HAS_MOVED 20
Definition at line 1146 of file sqlite3.h.
SQLITE_FCNTL_JOURNAL_POINTER
#define SQLITE_FCNTL_JOURNAL_POINTER 28
Definition at line 1154 of file sqlite3.h.
SQLITE_FCNTL_LAST_ERRNO
#define SQLITE_FCNTL_LAST_ERRNO 4
Definition at line 1131 of file sqlite3.h.
SQLITE_FCNTL_LOCK_TIMEOUT
#define SQLITE_FCNTL_LOCK_TIMEOUT 34
Definition at line 1160 of file sqlite3.h.
SQLITE_FCNTL_LOCKSTATE
#define SQLITE_FCNTL_LOCKSTATE 1
Definition at line 1128 of file sqlite3.h.
SQLITE_FCNTL_MMAP_SIZE
#define SQLITE_FCNTL_MMAP_SIZE 18
Definition at line 1144 of file sqlite3.h.
SQLITE_FCNTL_OVERWRITE
#define SQLITE_FCNTL_OVERWRITE 11
Definition at line 1138 of file sqlite3.h.
SQLITE_FCNTL_PDB
#define SQLITE_FCNTL_PDB 30
Definition at line 1156 of file sqlite3.h.
SQLITE_FCNTL_PERSIST_WAL
#define SQLITE_FCNTL_PERSIST_WAL 10
Definition at line 1137 of file sqlite3.h.
SQLITE_FCNTL_POWERSAFE_OVERWRITE
#define SQLITE_FCNTL_POWERSAFE_OVERWRITE 13
Definition at line 1140 of file sqlite3.h.
SQLITE_FCNTL_PRAGMA
#define SQLITE_FCNTL_PRAGMA 14
Definition at line 1141 of file sqlite3.h.
SQLITE_FCNTL_RBU
#define SQLITE_FCNTL_RBU 26
Definition at line 1152 of file sqlite3.h.
SQLITE_FCNTL_RESERVE_BYTES
#define SQLITE_FCNTL_RESERVE_BYTES 38
Definition at line 1164 of file sqlite3.h.
SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE
#define SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE 33
Definition at line 1159 of file sqlite3.h.
SQLITE_FCNTL_SET_LOCKPROXYFILE
#define SQLITE_FCNTL_SET_LOCKPROXYFILE 3
Definition at line 1130 of file sqlite3.h.
SQLITE_FCNTL_SIZE_HINT
#define SQLITE_FCNTL_SIZE_HINT 5
Definition at line 1132 of file sqlite3.h.
SQLITE_FCNTL_SIZE_LIMIT
#define SQLITE_FCNTL_SIZE_LIMIT 36
Definition at line 1162 of file sqlite3.h.
SQLITE_FCNTL_SYNC
#define SQLITE_FCNTL_SYNC 21
Definition at line 1147 of file sqlite3.h.
SQLITE_FCNTL_SYNC_OMITTED
#define SQLITE_FCNTL_SYNC_OMITTED 8
Definition at line 1135 of file sqlite3.h.
SQLITE_FCNTL_TEMPFILENAME
#define SQLITE_FCNTL_TEMPFILENAME 16
Definition at line 1143 of file sqlite3.h.
SQLITE_FCNTL_TRACE
#define SQLITE_FCNTL_TRACE 19
Definition at line 1145 of file sqlite3.h.
SQLITE_FCNTL_VFS_POINTER
#define SQLITE_FCNTL_VFS_POINTER 27
Definition at line 1153 of file sqlite3.h.
SQLITE_FCNTL_VFSNAME
#define SQLITE_FCNTL_VFSNAME 12
Definition at line 1139 of file sqlite3.h.
SQLITE_FCNTL_WAL_BLOCK
#define SQLITE_FCNTL_WAL_BLOCK 24
Definition at line 1150 of file sqlite3.h.
SQLITE_FCNTL_WIN32_AV_RETRY
#define SQLITE_FCNTL_WIN32_AV_RETRY 9
Definition at line 1136 of file sqlite3.h.
SQLITE_FCNTL_WIN32_GET_HANDLE
#define SQLITE_FCNTL_WIN32_GET_HANDLE 29
Definition at line 1155 of file sqlite3.h.
SQLITE_FCNTL_WIN32_SET_HANDLE
#define SQLITE_FCNTL_WIN32_SET_HANDLE 23
Definition at line 1149 of file sqlite3.h.
SQLITE_FCNTL_ZIPVFS
#define SQLITE_FCNTL_ZIPVFS 25
Definition at line 1151 of file sqlite3.h.
SQLITE_FLOAT
#define SQLITE_FLOAT 2
Definition at line 4742 of file sqlite3.h.
SQLITE_FORMAT
#define SQLITE_FORMAT 24 /* Not used */
Definition at line 446 of file sqlite3.h.
SQLITE_FULL
#define SQLITE_FULL 13 /* Insertion failed because database is full */
Definition at line 435 of file sqlite3.h.
SQLITE_FUNCTION
#define SQLITE_FUNCTION 31 /* NULL Function Name */
Definition at line 3100 of file sqlite3.h.
SQLITE_GET_LOCKPROXYFILE
#define SQLITE_GET_LOCKPROXYFILE SQLITE_FCNTL_GET_LOCKPROXYFILE
Definition at line 1168 of file sqlite3.h.
SQLITE_IGNORE
#define SQLITE_IGNORE 2 /* Don't allow access, but don't generate an error */
Definition at line 3048 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_EQ
#define SQLITE_INDEX_CONSTRAINT_EQ 2
Definition at line 6897 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_FUNCTION
#define SQLITE_INDEX_CONSTRAINT_FUNCTION 150
Definition at line 6911 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_GE
#define SQLITE_INDEX_CONSTRAINT_GE 32
Definition at line 6901 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_GLOB
#define SQLITE_INDEX_CONSTRAINT_GLOB 66
Definition at line 6904 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_GT
#define SQLITE_INDEX_CONSTRAINT_GT 4
Definition at line 6898 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_IS
#define SQLITE_INDEX_CONSTRAINT_IS 72
Definition at line 6910 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_ISNOT
#define SQLITE_INDEX_CONSTRAINT_ISNOT 69
Definition at line 6907 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_ISNOTNULL
#define SQLITE_INDEX_CONSTRAINT_ISNOTNULL 70
Definition at line 6908 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_ISNULL
#define SQLITE_INDEX_CONSTRAINT_ISNULL 71
Definition at line 6909 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_LE
#define SQLITE_INDEX_CONSTRAINT_LE 8
Definition at line 6899 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_LIKE
#define SQLITE_INDEX_CONSTRAINT_LIKE 65
Definition at line 6903 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_LT
#define SQLITE_INDEX_CONSTRAINT_LT 16
Definition at line 6900 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_MATCH
#define SQLITE_INDEX_CONSTRAINT_MATCH 64
Definition at line 6902 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_NE
#define SQLITE_INDEX_CONSTRAINT_NE 68
Definition at line 6906 of file sqlite3.h.
SQLITE_INDEX_CONSTRAINT_REGEXP
#define SQLITE_INDEX_CONSTRAINT_REGEXP 67
Definition at line 6905 of file sqlite3.h.
SQLITE_INDEX_SCAN_UNIQUE
#define SQLITE_INDEX_SCAN_UNIQUE 1 /* Scan visits at most 1 row */
Definition at line 6887 of file sqlite3.h.
SQLITE_INNOCUOUS
#define SQLITE_INNOCUOUS 0x000200000
Definition at line 5277 of file sqlite3.h.
SQLITE_INSERT
#define SQLITE_INSERT 18 /* Table Name NULL */
Definition at line 3087 of file sqlite3.h.
SQLITE_INTEGER
#define SQLITE_INTEGER 1
Definition at line 4741 of file sqlite3.h.
SQLITE_INTERNAL
#define SQLITE_INTERNAL 2 /* Internal logic error in SQLite */
Definition at line 424 of file sqlite3.h.
SQLITE_INTERRUPT
#define SQLITE_INTERRUPT 9 /* Operation terminated by sqlite3_interrupt()*/
Definition at line 431 of file sqlite3.h.
SQLITE_IOCAP_ATOMIC
#define SQLITE_IOCAP_ATOMIC 0x00000001
Definition at line 610 of file sqlite3.h.
SQLITE_IOCAP_ATOMIC16K
#define SQLITE_IOCAP_ATOMIC16K 0x00000040
Definition at line 616 of file sqlite3.h.
SQLITE_IOCAP_ATOMIC1K
#define SQLITE_IOCAP_ATOMIC1K 0x00000004
Definition at line 612 of file sqlite3.h.
SQLITE_IOCAP_ATOMIC2K
#define SQLITE_IOCAP_ATOMIC2K 0x00000008
Definition at line 613 of file sqlite3.h.
SQLITE_IOCAP_ATOMIC32K
#define SQLITE_IOCAP_ATOMIC32K 0x00000080
Definition at line 617 of file sqlite3.h.
SQLITE_IOCAP_ATOMIC4K
#define SQLITE_IOCAP_ATOMIC4K 0x00000010
Definition at line 614 of file sqlite3.h.
SQLITE_IOCAP_ATOMIC512
#define SQLITE_IOCAP_ATOMIC512 0x00000002
Definition at line 611 of file sqlite3.h.
SQLITE_IOCAP_ATOMIC64K
#define SQLITE_IOCAP_ATOMIC64K 0x00000100
Definition at line 618 of file sqlite3.h.
SQLITE_IOCAP_ATOMIC8K
#define SQLITE_IOCAP_ATOMIC8K 0x00000020
Definition at line 615 of file sqlite3.h.
SQLITE_IOCAP_BATCH_ATOMIC
#define SQLITE_IOCAP_BATCH_ATOMIC 0x00004000
Definition at line 624 of file sqlite3.h.
SQLITE_IOCAP_IMMUTABLE
#define SQLITE_IOCAP_IMMUTABLE 0x00002000
Definition at line 623 of file sqlite3.h.
SQLITE_IOCAP_POWERSAFE_OVERWRITE
#define SQLITE_IOCAP_POWERSAFE_OVERWRITE 0x00001000
Definition at line 622 of file sqlite3.h.
SQLITE_IOCAP_SAFE_APPEND
#define SQLITE_IOCAP_SAFE_APPEND 0x00000200
Definition at line 619 of file sqlite3.h.
SQLITE_IOCAP_SEQUENTIAL
#define SQLITE_IOCAP_SEQUENTIAL 0x00000400
Definition at line 620 of file sqlite3.h.
SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN
#define SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN 0x00000800
Definition at line 621 of file sqlite3.h.
SQLITE_IOERR
#define SQLITE_IOERR 10 /* Some kind of disk I/O error occurred */
Definition at line 432 of file sqlite3.h.
SQLITE_IOERR_ACCESS
#define SQLITE_IOERR_ACCESS (SQLITE_IOERR | (13<<8))
Definition at line 487 of file sqlite3.h.
SQLITE_IOERR_AUTH
#define SQLITE_IOERR_AUTH (SQLITE_IOERR | (28<<8))
Definition at line 502 of file sqlite3.h.
SQLITE_IOERR_BEGIN_ATOMIC
#define SQLITE_IOERR_BEGIN_ATOMIC (SQLITE_IOERR | (29<<8))
Definition at line 503 of file sqlite3.h.
SQLITE_IOERR_BLOCKED
#define SQLITE_IOERR_BLOCKED (SQLITE_IOERR | (11<<8))
Definition at line 485 of file sqlite3.h.
SQLITE_IOERR_CHECKRESERVEDLOCK
#define SQLITE_IOERR_CHECKRESERVEDLOCK (SQLITE_IOERR | (14<<8))
Definition at line 488 of file sqlite3.h.
SQLITE_IOERR_CLOSE
#define SQLITE_IOERR_CLOSE (SQLITE_IOERR | (16<<8))
Definition at line 490 of file sqlite3.h.
SQLITE_IOERR_COMMIT_ATOMIC
#define SQLITE_IOERR_COMMIT_ATOMIC (SQLITE_IOERR | (30<<8))
Definition at line 504 of file sqlite3.h.
SQLITE_IOERR_CONVPATH
#define SQLITE_IOERR_CONVPATH (SQLITE_IOERR | (26<<8))
Definition at line 500 of file sqlite3.h.
SQLITE_IOERR_DATA
#define SQLITE_IOERR_DATA (SQLITE_IOERR | (32<<8))
Definition at line 506 of file sqlite3.h.
SQLITE_IOERR_DELETE
#define SQLITE_IOERR_DELETE (SQLITE_IOERR | (10<<8))
Definition at line 484 of file sqlite3.h.
SQLITE_IOERR_DELETE_NOENT
#define SQLITE_IOERR_DELETE_NOENT (SQLITE_IOERR | (23<<8))
Definition at line 497 of file sqlite3.h.
SQLITE_IOERR_DIR_CLOSE
#define SQLITE_IOERR_DIR_CLOSE (SQLITE_IOERR | (17<<8))
Definition at line 491 of file sqlite3.h.
SQLITE_IOERR_DIR_FSYNC
#define SQLITE_IOERR_DIR_FSYNC (SQLITE_IOERR | (5<<8))
Definition at line 479 of file sqlite3.h.
SQLITE_IOERR_FSTAT
#define SQLITE_IOERR_FSTAT (SQLITE_IOERR | (7<<8))
Definition at line 481 of file sqlite3.h.
SQLITE_IOERR_FSYNC
#define SQLITE_IOERR_FSYNC (SQLITE_IOERR | (4<<8))
Definition at line 478 of file sqlite3.h.
SQLITE_IOERR_GETTEMPPATH
#define SQLITE_IOERR_GETTEMPPATH (SQLITE_IOERR | (25<<8))
Definition at line 499 of file sqlite3.h.
SQLITE_IOERR_LOCK
#define SQLITE_IOERR_LOCK (SQLITE_IOERR | (15<<8))
Definition at line 489 of file sqlite3.h.
SQLITE_IOERR_MMAP
#define SQLITE_IOERR_MMAP (SQLITE_IOERR | (24<<8))
Definition at line 498 of file sqlite3.h.
SQLITE_IOERR_NOMEM
#define SQLITE_IOERR_NOMEM (SQLITE_IOERR | (12<<8))
Definition at line 486 of file sqlite3.h.
SQLITE_IOERR_RDLOCK
#define SQLITE_IOERR_RDLOCK (SQLITE_IOERR | (9<<8))
Definition at line 483 of file sqlite3.h.
SQLITE_IOERR_READ
#define SQLITE_IOERR_READ (SQLITE_IOERR | (1<<8))
Definition at line 475 of file sqlite3.h.
SQLITE_IOERR_ROLLBACK_ATOMIC
#define SQLITE_IOERR_ROLLBACK_ATOMIC (SQLITE_IOERR | (31<<8))
Definition at line 505 of file sqlite3.h.
SQLITE_IOERR_SEEK
#define SQLITE_IOERR_SEEK (SQLITE_IOERR | (22<<8))
Definition at line 496 of file sqlite3.h.
SQLITE_IOERR_SHMLOCK
#define SQLITE_IOERR_SHMLOCK (SQLITE_IOERR | (20<<8))
Definition at line 494 of file sqlite3.h.
SQLITE_IOERR_SHMMAP
#define SQLITE_IOERR_SHMMAP (SQLITE_IOERR | (21<<8))
Definition at line 495 of file sqlite3.h.
SQLITE_IOERR_SHMOPEN
#define SQLITE_IOERR_SHMOPEN (SQLITE_IOERR | (18<<8))
Definition at line 492 of file sqlite3.h.
SQLITE_IOERR_SHMSIZE
#define SQLITE_IOERR_SHMSIZE (SQLITE_IOERR | (19<<8))
Definition at line 493 of file sqlite3.h.
SQLITE_IOERR_SHORT_READ
#define SQLITE_IOERR_SHORT_READ (SQLITE_IOERR | (2<<8))
Definition at line 476 of file sqlite3.h.
SQLITE_IOERR_TRUNCATE
#define SQLITE_IOERR_TRUNCATE (SQLITE_IOERR | (6<<8))
Definition at line 480 of file sqlite3.h.
SQLITE_IOERR_UNLOCK
#define SQLITE_IOERR_UNLOCK (SQLITE_IOERR | (8<<8))
Definition at line 482 of file sqlite3.h.
SQLITE_IOERR_VNODE
#define SQLITE_IOERR_VNODE (SQLITE_IOERR | (27<<8))
Definition at line 501 of file sqlite3.h.
SQLITE_IOERR_WRITE
#define SQLITE_IOERR_WRITE (SQLITE_IOERR | (3<<8))
Definition at line 477 of file sqlite3.h.
SQLITE_LAST_ERRNO
#define SQLITE_LAST_ERRNO SQLITE_FCNTL_LAST_ERRNO
Definition at line 1170 of file sqlite3.h.
SQLITE_LIMIT_ATTACHED
#define SQLITE_LIMIT_ATTACHED 7
Definition at line 3901 of file sqlite3.h.
SQLITE_LIMIT_COLUMN
#define SQLITE_LIMIT_COLUMN 2
Definition at line 3896 of file sqlite3.h.
SQLITE_LIMIT_COMPOUND_SELECT
#define SQLITE_LIMIT_COMPOUND_SELECT 4
Definition at line 3898 of file sqlite3.h.
SQLITE_LIMIT_EXPR_DEPTH
#define SQLITE_LIMIT_EXPR_DEPTH 3
Definition at line 3897 of file sqlite3.h.
SQLITE_LIMIT_FUNCTION_ARG
#define SQLITE_LIMIT_FUNCTION_ARG 6
Definition at line 3900 of file sqlite3.h.
SQLITE_LIMIT_LENGTH
#define SQLITE_LIMIT_LENGTH 0
Definition at line 3894 of file sqlite3.h.
SQLITE_LIMIT_LIKE_PATTERN_LENGTH
#define SQLITE_LIMIT_LIKE_PATTERN_LENGTH 8
Definition at line 3902 of file sqlite3.h.
SQLITE_LIMIT_SQL_LENGTH
#define SQLITE_LIMIT_SQL_LENGTH 1
Definition at line 3895 of file sqlite3.h.
SQLITE_LIMIT_TRIGGER_DEPTH
#define SQLITE_LIMIT_TRIGGER_DEPTH 10
Definition at line 3904 of file sqlite3.h.
SQLITE_LIMIT_VARIABLE_NUMBER
#define SQLITE_LIMIT_VARIABLE_NUMBER 9
Definition at line 3903 of file sqlite3.h.
SQLITE_LIMIT_VDBE_OP
#define SQLITE_LIMIT_VDBE_OP 5
Definition at line 3899 of file sqlite3.h.
SQLITE_LIMIT_WORKER_THREADS
#define SQLITE_LIMIT_WORKER_THREADS 11
Definition at line 3905 of file sqlite3.h.
SQLITE_LOCK_EXCLUSIVE
#define SQLITE_LOCK_EXCLUSIVE 4
Definition at line 637 of file sqlite3.h.
SQLITE_LOCK_NONE
#define SQLITE_LOCK_NONE 0
Definition at line 633 of file sqlite3.h.
SQLITE_LOCK_PENDING
#define SQLITE_LOCK_PENDING 3
Definition at line 636 of file sqlite3.h.
SQLITE_LOCK_RESERVED
#define SQLITE_LOCK_RESERVED 2
Definition at line 635 of file sqlite3.h.
SQLITE_LOCK_SHARED
#define SQLITE_LOCK_SHARED 1
Definition at line 634 of file sqlite3.h.
SQLITE_LOCKED
#define SQLITE_LOCKED 6 /* A table in the database is locked */
Definition at line 428 of file sqlite3.h.
SQLITE_LOCKED_SHAREDCACHE
#define SQLITE_LOCKED_SHAREDCACHE (SQLITE_LOCKED | (1<<8))
Definition at line 507 of file sqlite3.h.
SQLITE_LOCKED_VTAB
#define SQLITE_LOCKED_VTAB (SQLITE_LOCKED | (2<<8))
Definition at line 508 of file sqlite3.h.
SQLITE_MISMATCH
#define SQLITE_MISMATCH 20 /* Data type mismatch */
Definition at line 442 of file sqlite3.h.
SQLITE_MISUSE
#define SQLITE_MISUSE 21 /* Library used incorrectly */
Definition at line 443 of file sqlite3.h.
SQLITE_MUTEX_FAST
#define SQLITE_MUTEX_FAST 0
Definition at line 7579 of file sqlite3.h.
SQLITE_MUTEX_RECURSIVE
#define SQLITE_MUTEX_RECURSIVE 1
Definition at line 7580 of file sqlite3.h.
SQLITE_MUTEX_STATIC_APP1
#define SQLITE_MUTEX_STATIC_APP1 8 /* For use by application */
Definition at line 7589 of file sqlite3.h.
SQLITE_MUTEX_STATIC_APP2
#define SQLITE_MUTEX_STATIC_APP2 9 /* For use by application */
Definition at line 7590 of file sqlite3.h.
SQLITE_MUTEX_STATIC_APP3
#define SQLITE_MUTEX_STATIC_APP3 10 /* For use by application */
Definition at line 7591 of file sqlite3.h.
SQLITE_MUTEX_STATIC_LRU
#define SQLITE_MUTEX_STATIC_LRU 6 /* lru page list */
Definition at line 7586 of file sqlite3.h.
SQLITE_MUTEX_STATIC_LRU2
#define SQLITE_MUTEX_STATIC_LRU2 7 /* NOT USED */
Definition at line 7587 of file sqlite3.h.
SQLITE_MUTEX_STATIC_MASTER
#define SQLITE_MUTEX_STATIC_MASTER 2
Definition at line 7581 of file sqlite3.h.
SQLITE_MUTEX_STATIC_MEM
#define SQLITE_MUTEX_STATIC_MEM 3 /* sqlite3_malloc() */
Definition at line 7582 of file sqlite3.h.
SQLITE_MUTEX_STATIC_MEM2
#define SQLITE_MUTEX_STATIC_MEM2 4 /* NOT USED */
Definition at line 7583 of file sqlite3.h.
SQLITE_MUTEX_STATIC_OPEN
#define SQLITE_MUTEX_STATIC_OPEN 4 /* sqlite3BtreeOpen() */
Definition at line 7584 of file sqlite3.h.
SQLITE_MUTEX_STATIC_PMEM
#define SQLITE_MUTEX_STATIC_PMEM 7 /* sqlite3PageMalloc() */
Definition at line 7588 of file sqlite3.h.
SQLITE_MUTEX_STATIC_PRNG
#define SQLITE_MUTEX_STATIC_PRNG 5 /* sqlite3_randomness() */
Definition at line 7585 of file sqlite3.h.
SQLITE_MUTEX_STATIC_VFS1
#define SQLITE_MUTEX_STATIC_VFS1 11 /* For use by built-in VFS */
Definition at line 7592 of file sqlite3.h.
SQLITE_MUTEX_STATIC_VFS2
#define SQLITE_MUTEX_STATIC_VFS2 12 /* For use by extension VFS */
Definition at line 7593 of file sqlite3.h.
SQLITE_MUTEX_STATIC_VFS3
#define SQLITE_MUTEX_STATIC_VFS3 13 /* For use by application VFS */
Definition at line 7594 of file sqlite3.h.
SQLITE_NOLFS
#define SQLITE_NOLFS 22 /* Uses OS features not supported on host */
Definition at line 444 of file sqlite3.h.
SQLITE_NOMEM
#define SQLITE_NOMEM 7 /* A malloc() failed */
Definition at line 429 of file sqlite3.h.
SQLITE_NOTADB
#define SQLITE_NOTADB 26 /* File opened that is not a database file */
Definition at line 448 of file sqlite3.h.
SQLITE_NOTFOUND
#define SQLITE_NOTFOUND 12 /* Unknown opcode in sqlite3_file_control() */
Definition at line 434 of file sqlite3.h.
SQLITE_NOTICE
#define SQLITE_NOTICE 27 /* Notifications from sqlite3_log() */
Definition at line 449 of file sqlite3.h.
SQLITE_NOTICE_RECOVER_ROLLBACK
#define SQLITE_NOTICE_RECOVER_ROLLBACK (SQLITE_NOTICE | (2<<8))
Definition at line 540 of file sqlite3.h.
SQLITE_NOTICE_RECOVER_WAL
#define SQLITE_NOTICE_RECOVER_WAL (SQLITE_NOTICE | (1<<8))
Definition at line 539 of file sqlite3.h.
SQLITE_NULL
#define SQLITE_NULL 5
Definition at line 4744 of file sqlite3.h.
SQLITE_OK
#define SQLITE_OK 0 /* Successful result */
Definition at line 421 of file sqlite3.h.
SQLITE_OK_LOAD_PERMANENTLY
#define SQLITE_OK_LOAD_PERMANENTLY (SQLITE_OK | (1<<8))
Definition at line 543 of file sqlite3.h.
SQLITE_OK_SYMLINK
#define SQLITE_OK_SYMLINK (SQLITE_OK | (2<<8))
Definition at line 544 of file sqlite3.h.
SQLITE_OPEN_AUTOPROXY
#define SQLITE_OPEN_AUTOPROXY 0x00000020 /* VFS only */
Definition at line 558 of file sqlite3.h.
SQLITE_OPEN_CREATE
#define SQLITE_OPEN_CREATE 0x00000004 /* Ok for sqlite3_open_v2() */
Definition at line 555 of file sqlite3.h.
SQLITE_OPEN_DELETEONCLOSE
#define SQLITE_OPEN_DELETEONCLOSE 0x00000008 /* VFS only */
Definition at line 556 of file sqlite3.h.
SQLITE_OPEN_EXCLUSIVE
#define SQLITE_OPEN_EXCLUSIVE 0x00000010 /* VFS only */
Definition at line 557 of file sqlite3.h.
SQLITE_OPEN_FULLMUTEX
#define SQLITE_OPEN_FULLMUTEX 0x00010000 /* Ok for sqlite3_open_v2() */
Definition at line 569 of file sqlite3.h.
SQLITE_OPEN_MAIN_DB
#define SQLITE_OPEN_MAIN_DB 0x00000100 /* VFS only */
Definition at line 561 of file sqlite3.h.
SQLITE_OPEN_MAIN_JOURNAL
#define SQLITE_OPEN_MAIN_JOURNAL 0x00000800 /* VFS only */
Definition at line 564 of file sqlite3.h.
SQLITE_OPEN_MASTER_JOURNAL
#define SQLITE_OPEN_MASTER_JOURNAL 0x00004000 /* VFS only */
Definition at line 567 of file sqlite3.h.
SQLITE_OPEN_MEMORY
#define SQLITE_OPEN_MEMORY 0x00000080 /* Ok for sqlite3_open_v2() */
Definition at line 560 of file sqlite3.h.
SQLITE_OPEN_NOFOLLOW
#define SQLITE_OPEN_NOFOLLOW 0x01000000 /* Ok for sqlite3_open_v2() */
Definition at line 573 of file sqlite3.h.
SQLITE_OPEN_NOMUTEX
#define SQLITE_OPEN_NOMUTEX 0x00008000 /* Ok for sqlite3_open_v2() */
Definition at line 568 of file sqlite3.h.
SQLITE_OPEN_PRIVATECACHE
#define SQLITE_OPEN_PRIVATECACHE 0x00040000 /* Ok for sqlite3_open_v2() */
Definition at line 571 of file sqlite3.h.
SQLITE_OPEN_READONLY
#define SQLITE_OPEN_READONLY 0x00000001 /* Ok for sqlite3_open_v2() */
Definition at line 553 of file sqlite3.h.
SQLITE_OPEN_READWRITE
#define SQLITE_OPEN_READWRITE 0x00000002 /* Ok for sqlite3_open_v2() */
Definition at line 554 of file sqlite3.h.
SQLITE_OPEN_SHAREDCACHE
#define SQLITE_OPEN_SHAREDCACHE 0x00020000 /* Ok for sqlite3_open_v2() */
Definition at line 570 of file sqlite3.h.
SQLITE_OPEN_SUBJOURNAL
#define SQLITE_OPEN_SUBJOURNAL 0x00002000 /* VFS only */
Definition at line 566 of file sqlite3.h.
SQLITE_OPEN_TEMP_DB
#define SQLITE_OPEN_TEMP_DB 0x00000200 /* VFS only */
Definition at line 562 of file sqlite3.h.
SQLITE_OPEN_TEMP_JOURNAL
#define SQLITE_OPEN_TEMP_JOURNAL 0x00001000 /* VFS only */
Definition at line 565 of file sqlite3.h.
SQLITE_OPEN_TRANSIENT_DB
#define SQLITE_OPEN_TRANSIENT_DB 0x00000400 /* VFS only */
Definition at line 563 of file sqlite3.h.
SQLITE_OPEN_URI
#define SQLITE_OPEN_URI 0x00000040 /* Ok for sqlite3_open_v2() */
Definition at line 559 of file sqlite3.h.
SQLITE_OPEN_WAL
#define SQLITE_OPEN_WAL 0x00080000 /* VFS only */
Definition at line 572 of file sqlite3.h.
SQLITE_PERM
#define SQLITE_PERM 3 /* Access permission denied */
Definition at line 425 of file sqlite3.h.
SQLITE_PRAGMA
#define SQLITE_PRAGMA 19 /* Pragma Name 1st arg or NULL */
Definition at line 3088 of file sqlite3.h.
SQLITE_PREPARE_NO_VTAB
#define SQLITE_PREPARE_NO_VTAB 0x04
Definition at line 3944 of file sqlite3.h.
SQLITE_PREPARE_NORMALIZE
#define SQLITE_PREPARE_NORMALIZE 0x02
Definition at line 3943 of file sqlite3.h.
SQLITE_PREPARE_PERSISTENT
#define SQLITE_PREPARE_PERSISTENT 0x01
Definition at line 3942 of file sqlite3.h.
SQLITE_PROTOCOL
#define SQLITE_PROTOCOL 15 /* Database lock protocol error */
Definition at line 437 of file sqlite3.h.
SQLITE_RANGE
#define SQLITE_RANGE 25 /* 2nd parameter to sqlite3_bind out of range */
Definition at line 447 of file sqlite3.h.
SQLITE_READ
#define SQLITE_READ 20 /* Table Name Column Name */
Definition at line 3089 of file sqlite3.h.
SQLITE_READONLY
#define SQLITE_READONLY 8 /* Attempt to write a readonly database */
Definition at line 430 of file sqlite3.h.
SQLITE_READONLY_CANTINIT
#define SQLITE_READONLY_CANTINIT (SQLITE_READONLY | (5<<8))
Definition at line 525 of file sqlite3.h.
SQLITE_READONLY_CANTLOCK
#define SQLITE_READONLY_CANTLOCK (SQLITE_READONLY | (2<<8))
Definition at line 522 of file sqlite3.h.
SQLITE_READONLY_DBMOVED
#define SQLITE_READONLY_DBMOVED (SQLITE_READONLY | (4<<8))
Definition at line 524 of file sqlite3.h.
SQLITE_READONLY_DIRECTORY
#define SQLITE_READONLY_DIRECTORY (SQLITE_READONLY | (6<<8))
Definition at line 526 of file sqlite3.h.
SQLITE_READONLY_RECOVERY
#define SQLITE_READONLY_RECOVERY (SQLITE_READONLY | (1<<8))
Definition at line 521 of file sqlite3.h.
SQLITE_READONLY_ROLLBACK
#define SQLITE_READONLY_ROLLBACK (SQLITE_READONLY | (3<<8))
Definition at line 523 of file sqlite3.h.
SQLITE_RECURSIVE
#define SQLITE_RECURSIVE 33 /* NULL NULL */
Definition at line 3103 of file sqlite3.h.
SQLITE_REINDEX
#define SQLITE_REINDEX 27 /* Index Name NULL */
Definition at line 3096 of file sqlite3.h.
SQLITE_REPLACE
#define SQLITE_REPLACE 5
Definition at line 9235 of file sqlite3.h.
SQLITE_ROLLBACK
#define SQLITE_ROLLBACK 1
Definition at line 9231 of file sqlite3.h.
SQLITE_ROW
#define SQLITE_ROW 100 /* sqlite3_step() has another row ready */
Definition at line 451 of file sqlite3.h.
SQLITE_SAVEPOINT
#define SQLITE_SAVEPOINT 32 /* Operation Savepoint Name */
Definition at line 3101 of file sqlite3.h.
SQLITE_SCANSTAT_EST
#define SQLITE_SCANSTAT_EST 2
Definition at line 9286 of file sqlite3.h.
SQLITE_SCANSTAT_EXPLAIN
#define SQLITE_SCANSTAT_EXPLAIN 4
Definition at line 9288 of file sqlite3.h.
SQLITE_SCANSTAT_NAME
#define SQLITE_SCANSTAT_NAME 3
Definition at line 9287 of file sqlite3.h.
SQLITE_SCANSTAT_NLOOP
#define SQLITE_SCANSTAT_NLOOP 0
Definition at line 9284 of file sqlite3.h.
SQLITE_SCANSTAT_NVISIT
#define SQLITE_SCANSTAT_NVISIT 1
Definition at line 9285 of file sqlite3.h.
SQLITE_SCANSTAT_SELECTID
#define SQLITE_SCANSTAT_SELECTID 5
Definition at line 9289 of file sqlite3.h.
SQLITE_SCHEMA
#define SQLITE_SCHEMA 17 /* The database schema changed */
Definition at line 439 of file sqlite3.h.
SQLITE_SELECT
#define SQLITE_SELECT 21 /* NULL NULL */
Definition at line 3090 of file sqlite3.h.
SQLITE_SERIALIZE_NOCOPY
#define SQLITE_SERIALIZE_NOCOPY 0x001 /* Do no memory allocations */
Definition at line 9733 of file sqlite3.h.
SQLITE_SET_LOCKPROXYFILE
#define SQLITE_SET_LOCKPROXYFILE SQLITE_FCNTL_SET_LOCKPROXYFILE
Definition at line 1169 of file sqlite3.h.
SQLITE_SHM_EXCLUSIVE
#define SQLITE_SHM_EXCLUSIVE 8
Definition at line 1454 of file sqlite3.h.
SQLITE_SHM_LOCK
#define SQLITE_SHM_LOCK 2
Definition at line 1452 of file sqlite3.h.
SQLITE_SHM_NLOCK
#define SQLITE_SHM_NLOCK 8
Definition at line 1464 of file sqlite3.h.
SQLITE_SHM_SHARED
#define SQLITE_SHM_SHARED 4
Definition at line 1453 of file sqlite3.h.
SQLITE_SHM_UNLOCK
#define SQLITE_SHM_UNLOCK 1
Definition at line 1451 of file sqlite3.h.
SQLITE_SOURCE_ID
#define SQLITE_SOURCE_ID "2020-06-18 14:00:33 7ebdfa80be8e8e73324b8d66b3460222eb74c7e9dfd655b48d6ca7e1933cc8fd"
Definition at line 128 of file sqlite3.h.
SQLITE_STATIC
#define SQLITE_STATIC ((sqlite3_destructor_type)0)
Definition at line 5620 of file sqlite3.h.
SQLITE_STATUS_MALLOC_COUNT
#define SQLITE_STATUS_MALLOC_COUNT 9
Definition at line 8005 of file sqlite3.h.
SQLITE_STATUS_MALLOC_SIZE
#define SQLITE_STATUS_MALLOC_SIZE 5
Definition at line 8001 of file sqlite3.h.
SQLITE_STATUS_MEMORY_USED
#define SQLITE_STATUS_MEMORY_USED 0
Definition at line 7996 of file sqlite3.h.
SQLITE_STATUS_PAGECACHE_OVERFLOW
#define SQLITE_STATUS_PAGECACHE_OVERFLOW 2
Definition at line 7998 of file sqlite3.h.
SQLITE_STATUS_PAGECACHE_SIZE
#define SQLITE_STATUS_PAGECACHE_SIZE 7
Definition at line 8003 of file sqlite3.h.
SQLITE_STATUS_PAGECACHE_USED
#define SQLITE_STATUS_PAGECACHE_USED 1
Definition at line 7997 of file sqlite3.h.
SQLITE_STATUS_PARSER_STACK
#define SQLITE_STATUS_PARSER_STACK 6
Definition at line 8002 of file sqlite3.h.
SQLITE_STATUS_SCRATCH_OVERFLOW
#define SQLITE_STATUS_SCRATCH_OVERFLOW 4 /* NOT USED */
Definition at line 8000 of file sqlite3.h.
SQLITE_STATUS_SCRATCH_SIZE
#define SQLITE_STATUS_SCRATCH_SIZE 8 /* NOT USED */
Definition at line 8004 of file sqlite3.h.
SQLITE_STATUS_SCRATCH_USED
#define SQLITE_STATUS_SCRATCH_USED 3 /* NOT USED */
Definition at line 7999 of file sqlite3.h.
SQLITE_STDCALL
#define SQLITE_STDCALL SQLITE_APICALL
Definition at line 61 of file sqlite3.h.
SQLITE_STMTSTATUS_AUTOINDEX
#define SQLITE_STMTSTATUS_AUTOINDEX 3
Definition at line 8242 of file sqlite3.h.
SQLITE_STMTSTATUS_FULLSCAN_STEP
#define SQLITE_STMTSTATUS_FULLSCAN_STEP 1
Definition at line 8240 of file sqlite3.h.
SQLITE_STMTSTATUS_MEMUSED
#define SQLITE_STMTSTATUS_MEMUSED 99
Definition at line 8246 of file sqlite3.h.
SQLITE_STMTSTATUS_REPREPARE
#define SQLITE_STMTSTATUS_REPREPARE 5
Definition at line 8244 of file sqlite3.h.
SQLITE_STMTSTATUS_RUN
#define SQLITE_STMTSTATUS_RUN 6
Definition at line 8245 of file sqlite3.h.
SQLITE_STMTSTATUS_SORT
#define SQLITE_STMTSTATUS_SORT 2
Definition at line 8241 of file sqlite3.h.
SQLITE_STMTSTATUS_VM_STEP
#define SQLITE_STMTSTATUS_VM_STEP 4
Definition at line 8243 of file sqlite3.h.
SQLITE_SUBTYPE
#define SQLITE_SUBTYPE 0x000100000
Definition at line 5276 of file sqlite3.h.
SQLITE_SYNC_DATAONLY
#define SQLITE_SYNC_DATAONLY 0x00010
Definition at line 667 of file sqlite3.h.
SQLITE_SYNC_FULL
#define SQLITE_SYNC_FULL 0x00003
Definition at line 666 of file sqlite3.h.
SQLITE_SYNC_NORMAL
#define SQLITE_SYNC_NORMAL 0x00002
Definition at line 665 of file sqlite3.h.
SQLITE_SYSAPI
#define SQLITE_SYSAPI
Definition at line 67 of file sqlite3.h.
SQLITE_TESTCTRL_ALWAYS
#define SQLITE_TESTCTRL_ALWAYS 13
Definition at line 7690 of file sqlite3.h.
SQLITE_TESTCTRL_ASSERT
#define SQLITE_TESTCTRL_ASSERT 12
Definition at line 7689 of file sqlite3.h.
SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS
#define SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS 10
Definition at line 7687 of file sqlite3.h.
SQLITE_TESTCTRL_BITVEC_TEST
#define SQLITE_TESTCTRL_BITVEC_TEST 8
Definition at line 7685 of file sqlite3.h.
SQLITE_TESTCTRL_BYTEORDER
#define SQLITE_TESTCTRL_BYTEORDER 22
Definition at line 7701 of file sqlite3.h.
SQLITE_TESTCTRL_EXPLAIN_STMT
#define SQLITE_TESTCTRL_EXPLAIN_STMT 19 /* NOT USED */
Definition at line 7697 of file sqlite3.h.
SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS
#define SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS 29
Definition at line 7708 of file sqlite3.h.
SQLITE_TESTCTRL_FAULT_INSTALL
#define SQLITE_TESTCTRL_FAULT_INSTALL 9
Definition at line 7686 of file sqlite3.h.
SQLITE_TESTCTRL_FIRST
#define SQLITE_TESTCTRL_FIRST 5
Definition at line 7681 of file sqlite3.h.
SQLITE_TESTCTRL_IMPOSTER
#define SQLITE_TESTCTRL_IMPOSTER 25
Definition at line 7704 of file sqlite3.h.
SQLITE_TESTCTRL_INTERNAL_FUNCTIONS
#define SQLITE_TESTCTRL_INTERNAL_FUNCTIONS 17
Definition at line 7695 of file sqlite3.h.
SQLITE_TESTCTRL_ISINIT
#define SQLITE_TESTCTRL_ISINIT 23
Definition at line 7702 of file sqlite3.h.
SQLITE_TESTCTRL_ISKEYWORD
#define SQLITE_TESTCTRL_ISKEYWORD 16 /* NOT USED */
Definition at line 7693 of file sqlite3.h.
SQLITE_TESTCTRL_LAST
#define SQLITE_TESTCTRL_LAST 29 /* Largest TESTCTRL */
Definition at line 7709 of file sqlite3.h.
SQLITE_TESTCTRL_LOCALTIME_FAULT
#define SQLITE_TESTCTRL_LOCALTIME_FAULT 18
Definition at line 7696 of file sqlite3.h.
SQLITE_TESTCTRL_NEVER_CORRUPT
#define SQLITE_TESTCTRL_NEVER_CORRUPT 20
Definition at line 7699 of file sqlite3.h.
SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD
#define SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD 19
Definition at line 7698 of file sqlite3.h.
SQLITE_TESTCTRL_OPTIMIZATIONS
#define SQLITE_TESTCTRL_OPTIMIZATIONS 15
Definition at line 7692 of file sqlite3.h.
SQLITE_TESTCTRL_PARSER_COVERAGE
#define SQLITE_TESTCTRL_PARSER_COVERAGE 26
Definition at line 7705 of file sqlite3.h.
SQLITE_TESTCTRL_PENDING_BYTE
#define SQLITE_TESTCTRL_PENDING_BYTE 11
Definition at line 7688 of file sqlite3.h.
SQLITE_TESTCTRL_PRNG_RESET
#define SQLITE_TESTCTRL_PRNG_RESET 7 /* NOT USED */
Definition at line 7684 of file sqlite3.h.
SQLITE_TESTCTRL_PRNG_RESTORE
#define SQLITE_TESTCTRL_PRNG_RESTORE 6
Definition at line 7683 of file sqlite3.h.
SQLITE_TESTCTRL_PRNG_SAVE
#define SQLITE_TESTCTRL_PRNG_SAVE 5
Definition at line 7682 of file sqlite3.h.
SQLITE_TESTCTRL_PRNG_SEED
#define SQLITE_TESTCTRL_PRNG_SEED 28
Definition at line 7707 of file sqlite3.h.
SQLITE_TESTCTRL_RESERVE
#define SQLITE_TESTCTRL_RESERVE 14 /* NOT USED */
Definition at line 7691 of file sqlite3.h.
SQLITE_TESTCTRL_RESULT_INTREAL
#define SQLITE_TESTCTRL_RESULT_INTREAL 27
Definition at line 7706 of file sqlite3.h.
SQLITE_TESTCTRL_SCRATCHMALLOC
#define SQLITE_TESTCTRL_SCRATCHMALLOC 17 /* NOT USED */
Definition at line 7694 of file sqlite3.h.
SQLITE_TESTCTRL_SORTER_MMAP
#define SQLITE_TESTCTRL_SORTER_MMAP 24
Definition at line 7703 of file sqlite3.h.
SQLITE_TESTCTRL_VDBE_COVERAGE
#define SQLITE_TESTCTRL_VDBE_COVERAGE 21
Definition at line 7700 of file sqlite3.h.
SQLITE_TEXT
#define SQLITE_TEXT 3
Definition at line 4748 of file sqlite3.h.
SQLITE_TOOBIG
#define SQLITE_TOOBIG 18 /* String or BLOB exceeds size limit */
Definition at line 440 of file sqlite3.h.
SQLITE_TRACE_CLOSE
#define SQLITE_TRACE_CLOSE 0x08
Definition at line 3197 of file sqlite3.h.
SQLITE_TRACE_PROFILE
#define SQLITE_TRACE_PROFILE 0x02
Definition at line 3195 of file sqlite3.h.
SQLITE_TRACE_ROW
#define SQLITE_TRACE_ROW 0x04
Definition at line 3196 of file sqlite3.h.
SQLITE_TRACE_STMT
#define SQLITE_TRACE_STMT 0x01
Definition at line 3194 of file sqlite3.h.
SQLITE_TRANSACTION
#define SQLITE_TRANSACTION 22 /* Operation NULL */
Definition at line 3091 of file sqlite3.h.
SQLITE_TRANSIENT
#define SQLITE_TRANSIENT ((sqlite3_destructor_type)-1)
Definition at line 5621 of file sqlite3.h.
SQLITE_UPDATE
#define SQLITE_UPDATE 23 /* Table Name Column Name */
Definition at line 3092 of file sqlite3.h.
SQLITE_UTF16
#define SQLITE_UTF16 4 /* Use native byte order */
Definition at line 5205 of file sqlite3.h.
SQLITE_UTF16_ALIGNED
#define SQLITE_UTF16_ALIGNED 8 /* sqlite3_create_collation only */
Definition at line 5207 of file sqlite3.h.
SQLITE_UTF16BE
#define SQLITE_UTF16BE 3 /* IMP: R-51971-34154 */
Definition at line 5204 of file sqlite3.h.
SQLITE_UTF16LE
#define SQLITE_UTF16LE 2 /* IMP: R-03371-37637 */
Definition at line 5203 of file sqlite3.h.
SQLITE_UTF8
#define SQLITE_UTF8 1 /* IMP: R-37514-35566 */
Definition at line 5202 of file sqlite3.h.
SQLITE_VERSION
#define SQLITE_VERSION "3.32.3"
Definition at line 126 of file sqlite3.h.
SQLITE_VERSION_NUMBER
#define SQLITE_VERSION_NUMBER 3032003
Definition at line 127 of file sqlite3.h.
SQLITE_VTAB_CONSTRAINT_SUPPORT
#define SQLITE_VTAB_CONSTRAINT_SUPPORT 1
Definition at line 9169 of file sqlite3.h.
SQLITE_VTAB_DIRECTONLY
#define SQLITE_VTAB_DIRECTONLY 3
Definition at line 9171 of file sqlite3.h.
SQLITE_VTAB_INNOCUOUS
#define SQLITE_VTAB_INNOCUOUS 2
Definition at line 9170 of file sqlite3.h.
SQLITE_WARNING
#define SQLITE_WARNING 28 /* Warnings from sqlite3_log() */
Definition at line 450 of file sqlite3.h.
SQLITE_WARNING_AUTOINDEX
#define SQLITE_WARNING_AUTOINDEX (SQLITE_WARNING | (1<<8))
Definition at line 541 of file sqlite3.h.
SQLITE_WIN32_DATA_DIRECTORY_TYPE
#define SQLITE_WIN32_DATA_DIRECTORY_TYPE 1
Definition at line 6105 of file sqlite3.h.
SQLITE_WIN32_TEMP_DIRECTORY_TYPE
#define SQLITE_WIN32_TEMP_DIRECTORY_TYPE 2
Definition at line 6106 of file sqlite3.h.
Typedef Documentation
fts5_api
typedef struct fts5_api fts5_api
Definition at line 11632 of file sqlite3.h.
fts5_extension_function
typedef void(* fts5_extension_function) (const Fts5ExtensionApi *pApi, Fts5Context *pFts, sqlite3_context *pCtx, int nVal, sqlite3_value **apVal)
Definition at line 11632 of file sqlite3.h.
fts5_tokenizer
typedef struct fts5_tokenizer fts5_tokenizer
Definition at line 11632 of file sqlite3.h.
Fts5Context
typedef struct Fts5Context Fts5Context
Definition at line 9877 of file sqlite3.h.
Fts5ExtensionApi
typedef struct Fts5ExtensionApi Fts5ExtensionApi
Definition at line 9877 of file sqlite3.h.
Fts5PhraseIter
typedef struct Fts5PhraseIter Fts5PhraseIter
Definition at line 9877 of file sqlite3.h.
Fts5Tokenizer
typedef struct Fts5Tokenizer Fts5Tokenizer
Definition at line 11632 of file sqlite3.h.
sqlite3
typedef struct sqlite3 sqlite3
Definition at line 233 of file sqlite3.h.
sqlite3_api_routines
typedef struct sqlite3_api_routines sqlite3_api_routines
Definition at line 402 of file sqlite3.h.
sqlite3_backup
typedef struct sqlite3_backup sqlite3_backup
Definition at line 8183 of file sqlite3.h.
sqlite3_blob
typedef struct sqlite3_blob sqlite3_blob
Definition at line 7050 of file sqlite3.h.
sqlite3_callback
typedef int(* sqlite3_callback) (void *, int, char **, char **)
Definition at line 338 of file sqlite3.h.
sqlite3_context
typedef struct sqlite3_context sqlite3_context
Definition at line 4200 of file sqlite3.h.
sqlite3_destructor_type
typedef void(* sqlite3_destructor_type) (void *)
Definition at line 5619 of file sqlite3.h.
sqlite3_file
typedef struct sqlite3_file sqlite3_file
Definition at line 402 of file sqlite3.h.
sqlite3_index_info
typedef struct sqlite3_index_info sqlite3_index_info
Definition at line 6673 of file sqlite3.h.
sqlite3_int64
typedef sqlite_int64 sqlite3_int64
Definition at line 281 of file sqlite3.h.
sqlite3_io_methods
typedef struct sqlite3_io_methods sqlite3_io_methods
Definition at line 402 of file sqlite3.h.
sqlite3_mem_methods
typedef struct sqlite3_mem_methods sqlite3_mem_methods
Definition at line 1597 of file sqlite3.h.
sqlite3_module
typedef struct sqlite3_module sqlite3_module
Definition at line 6673 of file sqlite3.h.
sqlite3_mutex
typedef struct sqlite3_mutex sqlite3_mutex
Definition at line 402 of file sqlite3.h.
sqlite3_mutex_methods
typedef struct sqlite3_mutex_methods sqlite3_mutex_methods
Definition at line 7455 of file sqlite3.h.
sqlite3_pcache
typedef struct sqlite3_pcache sqlite3_pcache
Definition at line 8183 of file sqlite3.h.
sqlite3_pcache_methods
typedef struct sqlite3_pcache_methods sqlite3_pcache_methods
Definition at line 8183 of file sqlite3.h.
sqlite3_pcache_methods2
typedef struct sqlite3_pcache_methods2 sqlite3_pcache_methods2
Definition at line 8183 of file sqlite3.h.
sqlite3_pcache_page
typedef struct sqlite3_pcache_page sqlite3_pcache_page
Definition at line 8183 of file sqlite3.h.
sqlite3_rtree_dbl
typedef double sqlite3_rtree_dbl
Definition at line 9842 of file sqlite3.h.
sqlite3_rtree_geometry
typedef struct sqlite3_rtree_geometry sqlite3_rtree_geometry
Definition at line 9764 of file sqlite3.h.
sqlite3_rtree_query_info
typedef struct sqlite3_rtree_query_info sqlite3_rtree_query_info
Definition at line 9764 of file sqlite3.h.
sqlite3_snapshot
typedef struct sqlite3_snapshot sqlite3_snapshot
sqlite3_stmt
typedef struct sqlite3_stmt sqlite3_stmt
Definition at line 3768 of file sqlite3.h.
sqlite3_str
typedef struct sqlite3_str sqlite3_str
Definition at line 7760 of file sqlite3.h.
sqlite3_syscall_ptr
typedef void(* sqlite3_syscall_ptr) (void)
Definition at line 1365 of file sqlite3.h.
sqlite3_uint64
typedef sqlite_uint64 sqlite3_uint64
Definition at line 282 of file sqlite3.h.
sqlite3_value
typedef struct sqlite3_value sqlite3_value
Definition at line 4200 of file sqlite3.h.
sqlite3_vfs
typedef struct sqlite3_vfs sqlite3_vfs
Definition at line 402 of file sqlite3.h.
sqlite3_vtab
typedef struct sqlite3_vtab sqlite3_vtab
Definition at line 6673 of file sqlite3.h.
sqlite3_vtab_cursor
typedef struct sqlite3_vtab_cursor sqlite3_vtab_cursor
Definition at line 6673 of file sqlite3.h.
sqlite_int64
typedef long long int sqlite_int64
Definition at line 278 of file sqlite3.h.
sqlite_uint64
typedef unsigned long long int sqlite_uint64
Definition at line 279 of file sqlite3.h.
Function Documentation
sqlite3_aggregate_context()
void* sqlite3_aggregate_context (sqlite3_context * p, int nBytes)
Definition at line 83672 of file sqlite3.c.
References createAggContext(), sqlite3_value::db, sqlite3_value::flags, MEM_Agg, sqlite3::mutex, sqlite3_context::pFunc, sqlite3_context::pMem, sqlite3_context::pOut, sqlite3_mutex_held(), testcase, FuncDef::xFinalize, and sqlite3_value::z.
Referenced by countInverse(), minmaxStep(), ntileStepFunc(), rankStepFunc(), row_numberValueFunc(), and sumStep().
sqlite3_aggregate_count()
int sqlite3_aggregate_count (sqlite3_context * p)
Definition at line 83774 of file sqlite3.c.
References sqlite3_value::n, sqlite3_context::pFunc, sqlite3_context::pMem, and FuncDef::xFinalize.
sqlite3_auto_extension()
int sqlite3_auto_extension (void(*)(void) xEntryPoint)
Definition at line 124653 of file sqlite3.c.
References sqlite3_initialize(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_realloc64(), sqlite3MutexAlloc(), SQLITE_MUTEX_STATIC_MASTER, SQLITE_NOMEM_BKPT, SQLITE_OK, wsdAutoext, and wsdAutoextInit.
sqlite3_backup_finish()
int sqlite3_backup_finish (sqlite3_backup * p)
Definition at line 75445 of file sqlite3.c.
Referenced by sqlite3BtreeCopyFile().
sqlite3_backup_init()
sqlite3_backup* sqlite3_backup_init (sqlite3 * pDest, const char * zDestName, sqlite3 * pSource, const char * zSourceName)
Definition at line 75011 of file sqlite3.c.
References checkReadTransaction(), findBtree(), sqlite3_backup::iNext, sqlite3_backup::isAttached, sqlite3::mutex, Btree::nBackup, sqlite3_backup::pDest, sqlite3_backup::pDestDb, sqlite3_backup::pSrc, sqlite3_backup::pSrcDb, sqlite3_free(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3Error(), sqlite3ErrorWithMsg(), sqlite3MallocZero(), sqlite3SafetyCheckOk(), SQLITE_ERROR, SQLITE_MISUSE_BKPT, SQLITE_NOMEM_BKPT, and SQLITE_OK.
sqlite3_backup_pagecount()
int sqlite3_backup_pagecount (sqlite3_backup * p)
Definition at line 75513 of file sqlite3.c.
sqlite3_backup_remaining()
int sqlite3_backup_remaining (sqlite3_backup * p)
Definition at line 75499 of file sqlite3.c.
sqlite3_backup_step()
int sqlite3_backup_step (sqlite3_backup * p, int nPage)
Definition at line 75191 of file sqlite3.c.
Referenced by sqlite3BtreeCopyFile().
sqlite3_bind_blob()
int sqlite3_bind_blob (sqlite3_stmt * pStmt, int i, const void * zData, int n, void(*)(void *) xDel)
Definition at line 84195 of file sqlite3.c.
sqlite3_bind_blob64()
int sqlite3_bind_blob64 (sqlite3_stmt * pStmt, int i, const void * zData, sqlite3_uint64 nData, void(*)(void *) xDel)
Definition at line 84207 of file sqlite3.c.
References bindText(), and SQLITE_MISUSE_BKPT.
sqlite3_bind_double()
int sqlite3_bind_double (sqlite3_stmt * pStmt, int i, double rValue)
Definition at line 84221 of file sqlite3.c.
References invokeValueDestructor().
sqlite3_bind_int()
int sqlite3_bind_int (sqlite3_stmt * p, int i, int iValue)
Definition at line 84231 of file sqlite3.c.
References Vdbe::aVar, Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave(), and sqlite3VdbeMemSetDouble().
sqlite3_bind_int64()
int sqlite3_bind_int64 (sqlite3_stmt * pStmt, int i, sqlite3_int64 iValue)
Definition at line 84234 of file sqlite3.c.
sqlite3_bind_null()
int sqlite3_bind_null (sqlite3_stmt * pStmt, int i)
Definition at line 84244 of file sqlite3.c.
References Vdbe::aVar, Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave(), and sqlite3VdbeMemSetInt64().
sqlite3_bind_parameter_count()
int sqlite3_bind_parameter_count (sqlite3_stmt * pStmt)
Definition at line 84367 of file sqlite3.c.
sqlite3_bind_parameter_index()
int sqlite3_bind_parameter_index (sqlite3_stmt * pStmt, const char * zName)
Definition at line 84393 of file sqlite3.c.
References nName, Vdbe::pVList, sqlite3VListNameToNum(), and zName.
sqlite3_bind_parameter_name()
const char* sqlite3_bind_parameter_name (sqlite3_stmt * pStmt, int i)
Definition at line 84378 of file sqlite3.c.
References Vdbe::pVList, and sqlite3VListNumToName().
sqlite3_bind_pointer()
int sqlite3_bind_pointer (sqlite3_stmt * pStmt, int i, void * pPtr, const char * zPTtype, void(*)(void *) xDestructor)
Definition at line 84253 of file sqlite3.c.
sqlite3_bind_text()
int sqlite3_bind_text (sqlite3_stmt * pStmt, int i, const char * zData, int nData, void(*)(void *) xDel)
Definition at line 84271 of file sqlite3.c.
sqlite3_bind_text16()
int sqlite3_bind_text16 (sqlite3_stmt * pStmt, int i, const void * zData, int nData, void(*)(void *) xDel)
Definition at line 84297 of file sqlite3.c.
sqlite3_bind_text64()
int sqlite3_bind_text64 (sqlite3_stmt * pStmt, int i, const char * zData, sqlite3_uint64 nData, void(*)(void *) xDel, unsigned char encoding)
Definition at line 84280 of file sqlite3.c.
References bindText(), and SQLITE_UTF8.
sqlite3_bind_value()
int sqlite3_bind_value (sqlite3_stmt * pStmt, int i, const sqlite3_value * pValue)
Definition at line 84307 of file sqlite3.c.
References bindText(), and SQLITE_UTF16NATIVE.
sqlite3_bind_zeroblob()
int sqlite3_bind_zeroblob (sqlite3_stmt * pStmt, int i, int n)
Definition at line 84338 of file sqlite3.c.
sqlite3_bind_zeroblob64()
int sqlite3_bind_zeroblob64 (sqlite3_stmt * pStmt, int i, sqlite3_uint64 n)
Definition at line 84348 of file sqlite3.c.
References Vdbe::aVar, Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave(), and sqlite3VdbeMemSetZeroBlob().
sqlite3_blob_bytes()
int sqlite3_blob_bytes (sqlite3_blob * pBlob)
Definition at line 93617 of file sqlite3.c.
References Incrblob::nByte, and Incrblob::pStmt.
sqlite3_blob_close()
int sqlite3_blob_close (sqlite3_blob * pBlob)
Definition at line 93506 of file sqlite3.c.
sqlite3_blob_open()
int sqlite3_blob_open (sqlite3 * db, const char * zDb, const char * zTable, const char * zColumn, sqlite3_int64 iRow, int flags, sqlite3_blob ** ppBlob)
Definition at line 93273 of file sqlite3.c.
sqlite3_blob_read()
int sqlite3_blob_read (sqlite3_blob * pBlob, void * Z, int N, int iOffset)
Definition at line 93600 of file sqlite3.c.
sqlite3_blob_reopen()
int sqlite3_blob_reopen (sqlite3_blob * pBlob, sqlite3_int64 iRow)
Definition at line 93632 of file sqlite3.c.
sqlite3_blob_write()
int sqlite3_blob_write (sqlite3_blob * pBlob, const void * z, int n, int iOffset)
Definition at line 93607 of file sqlite3.c.
sqlite3_busy_handler()
int sqlite3_busy_handler (sqlite3 * db, int(*)(void *, int) xBusy, void * pArg)
Definition at line 162012 of file sqlite3.c.
Referenced by sqlite3_busy_timeout().
sqlite3_busy_timeout()
int sqlite3_busy_timeout (sqlite3 * db, int ms)
Definition at line 162066 of file sqlite3.c.
References sqlite3_busy_handler(), sqlite3SafetyCheckOk(), SQLITE_MISUSE_BKPT, and sqliteDefaultBusyCallback().
sqlite3_cancel_auto_extension()
int sqlite3_cancel_auto_extension (void(*)(void) xEntryPoint)
Definition at line 124700 of file sqlite3.c.
References sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3MutexAlloc(), SQLITE_MUTEX_STATIC_MASTER, wsdAutoext, and wsdAutoextInit.
sqlite3_changes()
int sqlite3_changes (sqlite3 * db)
Definition at line 161417 of file sqlite3.c.
Referenced by changes().
sqlite3_clear_bindings()
int sqlite3_clear_bindings (sqlite3_stmt * pStmt)
Definition at line 82932 of file sqlite3.c.
sqlite3_close()
int sqlite3_close (sqlite3 * db)
Definition at line 161581 of file sqlite3.c.
sqlite3_close_v2()
int sqlite3_close_v2 (sqlite3 * db)
Definition at line 161582 of file sqlite3.c.
References sqlite3Close().
sqlite3_collation_needed()
int sqlite3_collation_needed (sqlite3 * db, void * pCollNeededArg, void(*)(void *, sqlite3 *, int eTextRep, const char *) xCollNeeded)
Definition at line 163842 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pCollNeededArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3SafetyCheckOk(), SQLITE_MISUSE_BKPT, SQLITE_OK, sqlite3::xCollNeeded, and sqlite3::xCollNeeded16.
sqlite3_collation_needed16()
int sqlite3_collation_needed16 (sqlite3 * db, void * pCollNeededArg, void(*)(void *, sqlite3 *, int eTextRep, const void *) xCollNeeded16)
Definition at line 163863 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pCollNeededArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3SafetyCheckOk(), SQLITE_MISUSE_BKPT, SQLITE_OK, sqlite3::xCollNeeded, and sqlite3::xCollNeeded16.
sqlite3_column_blob()
const void* sqlite3_column_blob (sqlite3_stmt * pStmt, int iCol)
Definition at line 83896 of file sqlite3.c.
sqlite3_column_bytes()
int sqlite3_column_bytes (sqlite3_stmt * pStmt, int iCol)
Definition at line 83906 of file sqlite3.c.
sqlite3_column_bytes16()
int sqlite3_column_bytes16 (sqlite3_stmt * pStmt, int iCol)
Definition at line 83911 of file sqlite3.c.
sqlite3_column_count()
int sqlite3_column_count (sqlite3_stmt * pStmt)
Definition at line 83783 of file sqlite3.c.
Referenced by columnName(), and sqlite3_exec().
sqlite3_column_database_name()
const char* sqlite3_column_database_name (sqlite3_stmt * , int)
sqlite3_column_database_name16()
const void* sqlite3_column_database_name16 (sqlite3_stmt * , int)
sqlite3_column_decltype()
const char* sqlite3_column_decltype (sqlite3_stmt * pStmt, int N)
Definition at line 84046 of file sqlite3.c.
sqlite3_column_decltype16()
const void* sqlite3_column_decltype16 (sqlite3_stmt * pStmt, int N)
Definition at line 84050 of file sqlite3.c.
References COLNAME_DECLTYPE, and columnName().
sqlite3_column_double()
double sqlite3_column_double (sqlite3_stmt * pStmt, int iCol)
Definition at line 83916 of file sqlite3.c.
sqlite3_column_int()
int sqlite3_column_int (sqlite3_stmt * pStmt, int iCol)
Definition at line 83921 of file sqlite3.c.
sqlite3_column_int64()
sqlite3_int64 sqlite3_column_int64 (sqlite3_stmt * pStmt, int iCol)
Definition at line 83926 of file sqlite3.c.
sqlite3_column_name()
const char* sqlite3_column_name (sqlite3_stmt * pStmt, int N)
Definition at line 84023 of file sqlite3.c.
Referenced by sqlite3_exec().
sqlite3_column_name16()
const void* sqlite3_column_name16 (sqlite3_stmt * pStmt, int N)
Definition at line 84027 of file sqlite3.c.
References COLNAME_NAME, and columnName().
sqlite3_column_origin_name()
const char* sqlite3_column_origin_name (sqlite3_stmt * , int)
sqlite3_column_origin_name16()
const void* sqlite3_column_origin_name16 (sqlite3_stmt * , int)
sqlite3_column_table_name()
const char* sqlite3_column_table_name (sqlite3_stmt * , int)
sqlite3_column_table_name16()
const void* sqlite3_column_table_name16 (sqlite3_stmt * , int)
sqlite3_column_text()
const unsigned char* sqlite3_column_text (sqlite3_stmt * pStmt, int iCol)
Definition at line 83931 of file sqlite3.c.
Referenced by execSql(), and sqlite3_exec().
sqlite3_column_text16()
const void* sqlite3_column_text16 (sqlite3_stmt * pStmt, int iCol)
Definition at line 83946 of file sqlite3.c.
sqlite3_column_type()
int sqlite3_column_type (sqlite3_stmt * pStmt, int iCol)
Definition at line 83952 of file sqlite3.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_text16().
Referenced by sqlite3_exec().
sqlite3_column_value()
sqlite3_value* sqlite3_column_value (sqlite3_stmt * pStmt, int iCol)
Definition at line 83936 of file sqlite3.c.
sqlite3_commit_hook()
void* sqlite3_commit_hook (sqlite3 * db, int(*)(void *) xCallback, void * pArg)
Definition at line 162491 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pCommitArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3SafetyCheckOk(), SQLITE_MISUSE_BKPT, and sqlite3::xCommitCallback.
sqlite3_compileoption_get()
const char* sqlite3_compileoption_get (int N)
Definition at line 164915 of file sqlite3.c.
sqlite3_compileoption_used()
int sqlite3_compileoption_used (const char * zOptName)
Definition at line 164882 of file sqlite3.c.
References sqlite3CompileOptions(), sqlite3IsIdChar(), sqlite3Strlen30(), sqlite3StrNICmp, and SQLITE_MISUSE_BKPT.
Referenced by compileoptionusedFunc().
sqlite3_complete()
int sqlite3_complete (const char * sql)
Definition at line 160044 of file sqlite3.c.
References IdChar, sqlite3StrNICmp, SQLITE_MISUSE_BKPT, tkCREATE, tkEND, tkEXPLAIN, tkOTHER, tkSEMI, tkTEMP, tkTRIGGER, and tkWS.
Referenced by sqlite3_complete16().
sqlite3_complete16()
int sqlite3_complete16 (const void * sql)
Definition at line 160209 of file sqlite3.c.
References sqlite3_complete(), sqlite3_initialize(), sqlite3ValueFree(), sqlite3ValueNew(), sqlite3ValueSetStr(), sqlite3ValueText(), SQLITE_NOMEM_BKPT, SQLITE_STATIC, SQLITE_UTF16NATIVE, and SQLITE_UTF8.
sqlite3_config()
int sqlite3_config (int op, ...)
Definition at line 160760 of file sqlite3.c.
References sqlite3GlobalConfig, sqlite3HeaderSizeBtree(), sqlite3HeaderSizePcache(), sqlite3HeaderSizePcache1(), sqlite3MemSetDefault(), sqlite3PCacheSetDefault(), SQLITE_CONFIG_COVERING_INDEX_SCAN, SQLITE_CONFIG_GETMALLOC, SQLITE_CONFIG_GETMUTEX, SQLITE_CONFIG_GETPCACHE, SQLITE_CONFIG_GETPCACHE2, SQLITE_CONFIG_HEAP, SQLITE_CONFIG_LOG, SQLITE_CONFIG_LOOKASIDE, SQLITE_CONFIG_MALLOC, SQLITE_CONFIG_MEMDB_MAXSIZE, SQLITE_CONFIG_MEMSTATUS, SQLITE_CONFIG_MMAP_SIZE, SQLITE_CONFIG_MULTITHREAD, SQLITE_CONFIG_MUTEX, SQLITE_CONFIG_PAGECACHE, SQLITE_CONFIG_PCACHE, SQLITE_CONFIG_PCACHE2, SQLITE_CONFIG_PCACHE_HDRSZ, SQLITE_CONFIG_PMASZ, SQLITE_CONFIG_SERIALIZED, SQLITE_CONFIG_SINGLETHREAD, SQLITE_CONFIG_SMALL_MALLOC, SQLITE_CONFIG_SORTERREF_SIZE, SQLITE_CONFIG_SQLLOG, SQLITE_CONFIG_STMTJRNL_SPILL, SQLITE_CONFIG_URI, SQLITE_CONFIG_WIN32_HEAPSIZE, SQLITE_DEFAULT_MMAP_SIZE, SQLITE_DEFAULT_SORTERREF_SIZE, SQLITE_ERROR, SQLITE_MAX_MMAP_SIZE, SQLITE_MISUSE_BKPT, and SQLITE_OK.
Referenced by main(), main_init(), sqlite3MemSetDefault(), sqlite3MemTraceDeactivate(), and verify_uninitialized().
sqlite3_context_db_handle()
sqlite3* sqlite3_context_db_handle (sqlite3_context * p)
Definition at line 83599 of file sqlite3.c.
References sqlite3_value::db, and sqlite3_context::pOut.
Referenced by attachFunc(), changes(), contextMalloc(), detachFunc(), likeFunc(), loadExt(), renameColumnFunc(), renameEditSql(), renameTableFunc(), renameTableTest(), replaceFunc(), statInit(), strftimeFunc(), and substrFunc().
sqlite3_create_collation()
int sqlite3_create_collation (sqlite3 * db, const char * zName, int eTextRep, void * pArg, int(*)(void *, int, const void *, int, const void *) xCompare)
Definition at line 163774 of file sqlite3.c.
sqlite3_create_collation16()
int sqlite3_create_collation16 (sqlite3 * db, const void * zName, int eTextRep, void * pArg, int(*)(void *, int, const void *, int, const void *) xCompare)
Definition at line 163812 of file sqlite3.c.
sqlite3_create_collation_v2()
int sqlite3_create_collation_v2 (sqlite3 * db, const char * zName, int eTextRep, void * pArg, int(*)(void *, int, const void *, int, const void *) xCompare, void(*)(void *) xDestroy)
Definition at line 163787 of file sqlite3.c.
sqlite3_create_filename()
char* sqlite3_create_filename (const char * zDatabase, const char * zJournal, const char * zWal, int nParam, const char ** azParam)
Definition at line 164570 of file sqlite3.c.
References appendText(), and sqlite3_malloc64().
sqlite3_create_function()
int sqlite3_create_function (sqlite3 * db, const char * zFunctionName, int nArg, int eTextRep, void * pApp, void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal)
Definition at line 162271 of file sqlite3.c.
sqlite3_create_function16()
int sqlite3_create_function16 (sqlite3 * db, const void * zFunctionName, int nArg, int eTextRep, void * pApp, void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal)
Definition at line 162315 of file sqlite3.c.
References createFunctionApi().
sqlite3_create_function_v2()
int sqlite3_create_function_v2 (sqlite3 * db, const char * zFunctionName, int nArg, int eTextRep, void * pApp, void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal, void(*)(void *) xDestroy)
Definition at line 162284 of file sqlite3.c.
References createFunctionApi().
Referenced by sqlite3_overload_function().
sqlite3_create_module()
int sqlite3_create_module (sqlite3 * db, const char * zName, const sqlite3_module * p, void * pClientData)
Definition at line 139056 of file sqlite3.c.
sqlite3_create_module_v2()
int sqlite3_create_module_v2 (sqlite3 * db, const char * zName, const sqlite3_module * p, void * pClientData, void(*)(void *) xDestroy)
Definition at line 139071 of file sqlite3.c.
sqlite3_create_window_function()
int sqlite3_create_window_function (sqlite3 * db, const char * zFunctionName, int nArg, int eTextRep, void * pApp, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal, void(*)(sqlite3_context *) xValue, void(*)(sqlite3_context *, int, sqlite3_value **) xInverse, void(*)(void *) xDestroy)
Definition at line 162298 of file sqlite3.c.
References createFunctionApi().
sqlite3_data_count()
int sqlite3_data_count (sqlite3_stmt * pStmt)
Definition at line 83792 of file sqlite3.c.
sqlite3_database_file_object()
sqlite3_file* sqlite3_database_file_object (const char * zName)
Definition at line 56629 of file sqlite3.c.
References Pager::fd, and zName.
sqlite3_db_cacheflush()
int sqlite3_db_cacheflush (sqlite3 * db)
Definition at line 161216 of file sqlite3.c.
sqlite3_db_config()
int sqlite3_db_config (sqlite3 * db, int op, ...)
Definition at line 161245 of file sqlite3.c.
sqlite3_db_filename()
const char* sqlite3_db_filename (sqlite3 * db, const char * zDbName)
Definition at line 164713 of file sqlite3.c.
sqlite3_db_handle()
sqlite3* sqlite3_db_handle (sqlite3_stmt * pStmt)
Definition at line 84451 of file sqlite3.c.
sqlite3_db_mutex()
sqlite3_mutex* sqlite3_db_mutex (sqlite3 * db)
Definition at line 161178 of file sqlite3.c.
sqlite3_db_readonly()
int sqlite3_db_readonly (sqlite3 * db, const char * zDbName)
Definition at line 164729 of file sqlite3.c.
sqlite3_db_release_memory()
int sqlite3_db_release_memory (sqlite3 * db)
Definition at line 161192 of file sqlite3.c.
sqlite3_db_status()
int sqlite3_db_status (sqlite3 * db, int op, int * pCur, int * pHiwtr, int resetFlg)
Definition at line 21470 of file sqlite3.c.
sqlite3_declare_vtab()
int sqlite3_declare_vtab (sqlite3 * db, const char * zSQL)
Definition at line 139743 of file sqlite3.c.
References Table::aCol, VtabCtx::bDeclared, Parse::db, Parse::eParseMode, HasRowid, IsVirtual, sqlite3::mallocFailed, sqlite3::mutex, Table::nCol, Parse::nQueryLoop, PARSE_MODE_DECLARE_VTAB, PARSE_MODE_NORMAL, Table::pIndex, VTable::pMod, Module::pModule, Parse::pNewTable, Index::pNext, Table::pSelect, VtabCtx::pTab, Index::pTable, Parse::pVdbe, sqlite3::pVtabCtx, VtabCtx::pVTable, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ApiExit(), sqlite3DbFree(), sqlite3DeleteTable(), sqlite3Error(), sqlite3ErrorWithMsg(), sqlite3ParserReset(), sqlite3PrimaryKeyIndex(), sqlite3RunParser(), sqlite3SafetyCheckOk(), sqlite3VdbeFinalize(), SQLITE_ERROR, SQLITE_MISUSE, SQLITE_MISUSE_BKPT, SQLITE_OK, Table::tabFlags, TF_NoVisibleRowid, TF_WithoutRowid, and sqlite3_module::xUpdate.
sqlite3_deserialize()
int sqlite3_deserialize (sqlite3 * db, const char * zSchema, unsigned char * pData, sqlite3_int64 szDb, sqlite3_int64 szBuf, unsigned mFlags)
sqlite3_drop_modules()
int sqlite3_drop_modules (sqlite3 * db, const char ** azKeep)
Definition at line 139088 of file sqlite3.c.
sqlite3_enable_load_extension()
int sqlite3_enable_load_extension (sqlite3 * db, int onoff)
Definition at line 124607 of file sqlite3.c.
Referenced by open_db().
sqlite3_enable_shared_cache()
int sqlite3_enable_shared_cache (int enable)
Definition at line 64421 of file sqlite3.c.
References sqlite3GlobalConfig, and SQLITE_OK.
sqlite3_errcode()
int sqlite3_errcode (sqlite3 * db)
Definition at line 162888 of file sqlite3.c.
References sqlite3SafetyCheckSickOrOk(), and SQLITE_MISUSE_BKPT.
Referenced by openDatabase().
sqlite3_errmsg()
const char* sqlite3_errmsg (sqlite3 * db)
Definition at line 162818 of file sqlite3.c.
Referenced by blobSeekToRow(), execSqlF(), sqlite3_exec(), and sqlite3InitCallback().
sqlite3_errmsg16()
const void* sqlite3_errmsg16 (sqlite3 * db)
Definition at line 162846 of file sqlite3.c.
References sqlite3::errCode, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::pErr, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_value_text16(), sqlite3ErrorWithMsg(), sqlite3ErrStr(), sqlite3OomClear(), and sqlite3SafetyCheckSickOrOk().
sqlite3_errstr()
const char* sqlite3_errstr (int rc)
Definition at line 162915 of file sqlite3.c.
References sqlite3ErrStr().
sqlite3_exec()
int sqlite3_exec (sqlite3 * db, const char * sql, int(*)(void *, int, char **, char **) callback, void * pArg, char ** errmsg)
Definition at line 123155 of file sqlite3.c.
References sqlite3::errMask, sqlite3::flags, sqlite3::mutex, sqlite3_column_count(), sqlite3_column_name(), sqlite3_column_text(), sqlite3_column_type(), sqlite3_errmsg(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_prepare_v2(), sqlite3_step(), sqlite3ApiExit(), sqlite3DbFree(), sqlite3DbMallocRaw(), sqlite3DbStrDup(), sqlite3Error(), sqlite3Isspace, sqlite3OomFault(), sqlite3SafetyCheckOk(), sqlite3VdbeFinalize(), SQLITE_ABORT, SQLITE_DONE, SQLITE_MISUSE_BKPT, SQLITE_NOMEM, SQLITE_NOMEM_BKPT, SQLITE_NULL, SQLITE_NullCallback, SQLITE_OK, and SQLITE_ROW.
Referenced by sqlite3_get_table(), sqlite3AnalysisLoad(), and sqlite3InitOne().
sqlite3_expanded_sql()
char* sqlite3_expanded_sql (sqlite3_stmt * pStmt)
Definition at line 84550 of file sqlite3.c.
References Vdbe::db, sqlite3::mutex, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_sql(), and sqlite3VdbeExpandSql().
sqlite3_expired()
int sqlite3_expired (sqlite3_stmt * pStmt)
Definition at line 82813 of file sqlite3.c.
References Vdbe::expired.
sqlite3_extended_errcode()
int sqlite3_extended_errcode (sqlite3 * db)
Definition at line 162897 of file sqlite3.c.
sqlite3_extended_result_codes()
int sqlite3_extended_result_codes (sqlite3 * db, int onoff)
Definition at line 164103 of file sqlite3.c.
sqlite3_file_control()
int sqlite3_file_control (sqlite3 * db, const char * zDbName, int op, void * pArg)
Definition at line 164116 of file sqlite3.c.
sqlite3_filename_database()
const char* sqlite3_filename_database (const char * zFilename)
Definition at line 164679 of file sqlite3.c.
sqlite3_filename_journal()
const char* sqlite3_filename_journal (const char * zFilename)
Definition at line 164682 of file sqlite3.c.
References databaseName().
sqlite3_filename_wal()
const char* sqlite3_filename_wal (const char * zFilename)
Definition at line 164691 of file sqlite3.c.
References sqlite3Strlen30().
sqlite3_finalize()
int sqlite3_finalize (sqlite3_stmt * pStmt)
Definition at line 82884 of file sqlite3.c.
References checkProfileCallback, Vdbe::db, sqlite3::mutex, sqlite3_mutex_enter(), sqlite3ApiExit(), sqlite3LeaveMutexAndCloseZombie(), sqlite3VdbeFinalize(), SQLITE_MISUSE_BKPT, SQLITE_OK, and vdbeSafety().
Referenced by blobSeekToRow(), and sqlite3InitCallback().
sqlite3_free()
void sqlite3_free (void * p)
Definition at line 27647 of file sqlite3.c.
Referenced by attachFunc(), btreeRestoreCursorPosition(), charFunc(), clearAllSharedCacheTableLocks(), closeUnixFile(), fillInUnixFile(), findInodeInfo(), loadExt(), openDatabase(), pager_delmaster(), pcache1Destroy(), pcache1ResizeHash(), pthreadMutexFree(), quoteFunc(), rehash(), releaseAllSavepoints(), releaseInodeInfo(), renameColumnParseError(), renameEditSql(), replaceFunc(), saveCursorKey(), setupLookaside(), sqlite3_backup_init(), sqlite3_free_filename(), sqlite3_get_table(), sqlite3_get_table_cb(), sqlite3_overload_function(), sqlite3AnalysisLoad(), sqlite3AutoLoadExtensions(), sqlite3BitvecBuiltinTest(), sqlite3BtreeIntegrityCheck(), sqlite3BtreeMovetoUnpacked(), sqlite3BtreeOpen(), sqlite3InvalidFunction(), sqlite3LeaveMutexAndCloseZombie(), sqlite3LoadExtension(), sqlite3NotPureFunc(), sqlite3OsInit(), sqlite3PagerClose(), sqlite3PagerOpen(), sqlite3RunParser(), sqlite3VdbeList(), sqlite3VdbeMemGrow(), sqlite3VtabImportErrmsg(), sqlite3WalOpen(), statGet(), unixFullPathname(), unixOpen(), unixOpenSharedMemory(), unixShmPurge(), unixShmUnmap(), vdbePmaWriterFinish(), vdbeSorterListToPMA(), vtabBestIndex(), vtabCallConstructor(), walBeginShmUnreliable(), walIndexRecover(), walIteratorInit(), walRewriteChecksums(), whereLoopAddVirtual(), and whereLoopAddVirtualOne().
sqlite3_free_filename()
void sqlite3_free_filename (char * p)
Definition at line 164606 of file sqlite3.c.
References databaseName(), and sqlite3_free().
Referenced by attachFunc(), and sqlite3ParseUri().
sqlite3_free_table()
void sqlite3_free_table (char ** result)
Definition at line 135986 of file sqlite3.c.
Referenced by sqlite3_get_table().
sqlite3_get_autocommit()
int sqlite3_get_autocommit (sqlite3 * db)
Definition at line 163896 of file sqlite3.c.
References sqlite3::autoCommit, sqlite3SafetyCheckOk(), and SQLITE_MISUSE_BKPT.
sqlite3_get_auxdata()
void* sqlite3_get_auxdata (sqlite3_context * pCtx, int N)
Definition at line 83693 of file sqlite3.c.
References sqlite3_value::db, AuxData::iAuxArg, AuxData::iAuxOp, sqlite3_context::iOp, sqlite3::mutex, AuxData::pAux, Vdbe::pAuxData, AuxData::pNextAux, sqlite3_context::pOut, sqlite3_context::pVdbe, and sqlite3_mutex_held().
sqlite3_get_table()
int sqlite3_get_table (sqlite3 * db, const char * zSql, char *** pazResult, int * pnRow, int * pnColumn, char ** pzErrmsg)
Definition at line 135917 of file sqlite3.c.
References TabResult::azResult, sqlite3::errCode, TabResult::nAlloc, TabResult::nColumn, TabResult::nData, TabResult::nRow, TabResult::rc, sqlite3_exec(), sqlite3_free(), sqlite3_free_table(), sqlite3_get_table_cb(), sqlite3_malloc64(), sqlite3_mprintf(), sqlite3Realloc(), sqlite3SafetyCheckOk(), SQLITE_ABORT, SQLITE_INT_TO_PTR, SQLITE_MISUSE_BKPT, SQLITE_NOMEM, SQLITE_NOMEM_BKPT, SQLITE_OK, and TabResult::zErrMsg.
sqlite3_global_recover()
int sqlite3_global_recover (void)
Definition at line 163885 of file sqlite3.c.
References SQLITE_OK.
sqlite3_hard_heap_limit64()
sqlite3_int64 sqlite3_hard_heap_limit64 (sqlite3_int64 N)
Definition at line 27404 of file sqlite3.c.
References mem0, sqlite3_initialize(), sqlite3_mutex_enter(), and sqlite3_mutex_leave().
sqlite3_initialize()
int sqlite3_initialize (void)
Definition at line 160531 of file sqlite3.c.
References MUTEX_LOGIC, sqlite3_mutex_enter(), sqlite3_mutex_free(), sqlite3_mutex_leave(), sqlite3BuiltinFunctions, sqlite3GlobalConfig, sqlite3IsNaN(), sqlite3MallocInit(), sqlite3MemoryBarrier(), sqlite3MutexAlloc(), sqlite3MutexInit(), sqlite3OsInit(), sqlite3PCacheBufferSetup(), sqlite3PcacheInitialize(), sqlite3RegisterBuiltinFunctions(), SQLITE_MUTEX_RECURSIVE, SQLITE_MUTEX_STATIC_MASTER, SQLITE_NOMEM_BKPT, SQLITE_OK, and SQLITE_PTRSIZE.
Referenced by main(), openDatabase(), sqlite3_auto_extension(), sqlite3_complete16(), sqlite3_hard_heap_limit64(), sqlite3_soft_heap_limit64(), sqlite3_vfs_find(), and sqlite3_vfs_register().
sqlite3_interrupt()
void sqlite3_interrupt (sqlite3 * db)
Definition at line 162083 of file sqlite3.c.
sqlite3_keyword_check()
int sqlite3_keyword_check (const char * zName, int nName)
Definition at line 159214 of file sqlite3.c.
sqlite3_keyword_count()
int sqlite3_keyword_count (void)
Definition at line 159213 of file sqlite3.c.
sqlite3_keyword_name()
int sqlite3_keyword_name (int i, const char ** pzName, int * pnName)
Definition at line 159207 of file sqlite3.c.
References keywordCode(), and TK_ID.
sqlite3_last_insert_rowid()
sqlite3_int64 sqlite3_last_insert_rowid (sqlite3 * db)
Definition at line 161389 of file sqlite3.c.
sqlite3_libversion()
const char* sqlite3_libversion (void)
Definition at line 160439 of file sqlite3.c.
References sqlite3_version.
sqlite3_libversion_number()
int sqlite3_libversion_number (void)
Definition at line 160452 of file sqlite3.c.
sqlite3_limit()
int sqlite3_limit (sqlite3 * db, int id, int newVal)
Definition at line 163063 of file sqlite3.c.
References aHardLimit, sqlite3::aLimit, sqlite3SafetyCheckOk(), SQLITE_LIMIT_ATTACHED, SQLITE_LIMIT_COLUMN, SQLITE_LIMIT_COMPOUND_SELECT, SQLITE_LIMIT_EXPR_DEPTH, SQLITE_LIMIT_FUNCTION_ARG, SQLITE_LIMIT_LENGTH, SQLITE_LIMIT_LIKE_PATTERN_LENGTH, SQLITE_LIMIT_SQL_LENGTH, SQLITE_LIMIT_TRIGGER_DEPTH, SQLITE_LIMIT_VARIABLE_NUMBER, SQLITE_LIMIT_VDBE_OP, SQLITE_LIMIT_WORKER_THREADS, SQLITE_MAX_ATTACHED, SQLITE_MAX_COLUMN, SQLITE_MAX_COMPOUND_SELECT, SQLITE_MAX_EXPR_DEPTH, SQLITE_MAX_FUNCTION_ARG, SQLITE_MAX_LENGTH, SQLITE_MAX_LIKE_PATTERN_LENGTH, SQLITE_MAX_SQL_LENGTH, SQLITE_MAX_TRIGGER_DEPTH, SQLITE_MAX_VARIABLE_NUMBER, SQLITE_MAX_VDBE_OP, SQLITE_MAX_WORKER_THREADS, SQLITE_MISUSE_BKPT, and SQLITE_N_LIMIT.
sqlite3_load_extension()
int sqlite3_load_extension (sqlite3 * db, const char * zFile, const char * zProc, char ** pzErrMsg)
Definition at line 124576 of file sqlite3.c.
Referenced by loadExt().
sqlite3_log()
void sqlite3_log (int iErrCode, const char * zFormat, ...)
Definition at line 29356 of file sqlite3.c.
Referenced by constructAutomaticIndex(), errlogFunc(), logBadConnection(), lookupName(), pager_playback(), robust_open(), sqlite3CorruptError(), sqlite3MemMalloc(), sqlite3MemRealloc(), sqlite3PcacheFetchStress(), sqlite3RunParser(), unixLogErrorAtLine(), vdbeCommit(), vdbeUnbind(), verifyDbFile(), and walIndexRecover().
sqlite3_malloc()
void* sqlite3_malloc (int n)
Definition at line 27570 of file sqlite3.c.
Referenced by sqlite3OsInit(), unixFullPathname(), and walRewriteChecksums().
sqlite3_malloc64()
void* sqlite3_malloc64 (sqlite3_uint64 n)
Definition at line 27576 of file sqlite3.c.
Referenced by charFunc(), fillInUnixFile(), findInodeInfo(), sqlite3_create_filename(), sqlite3_get_table(), sqlite3_get_table_cb(), sqlite3BitvecBuiltinTest(), sqlite3LoadExtension(), sqlite3ParseUri(), unixOpen(), unixOpenSharedMemory(), unixShmMap(), walBeginShmUnreliable(), walIndexRecover(), and walIteratorInit().
sqlite3_memory_alarm()
int sqlite3_memory_alarm (void(*)(void *, sqlite3_int64, int) , void * , sqlite3_int64)
sqlite3_memory_highwater()
sqlite3_int64 sqlite3_memory_highwater (int resetFlag)
Definition at line 27476 of file sqlite3.c.
References sqlite3_status64(), and SQLITE_STATUS_MEMORY_USED.
sqlite3_memory_used()
sqlite3_int64 sqlite3_memory_used (void)
Definition at line 27465 of file sqlite3.c.
sqlite3_mprintf()
char* sqlite3_mprintf (const char * zFormat, ...)
Definition at line 29280 of file sqlite3.c.
Referenced by renameColumnParseError(), sqlite3_get_table(), sqlite3_get_table_cb(), sqlite3_overload_function(), sqlite3AuthReadCol(), sqlite3InvalidFunction(), sqlite3LoadExtension(), sqlite3NotPureFunc(), sqlite3ParseUri(), and unixOpen().
sqlite3_msize()
sqlite3_uint64 sqlite3_msize (void * p)
Definition at line 27638 of file sqlite3.c.
sqlite3_mutex_alloc()
sqlite3_mutex* sqlite3_mutex_alloc (int id)
Definition at line 25877 of file sqlite3.c.
Referenced by findInodeInfo(), and unixOpenSharedMemory().
sqlite3_mutex_enter()
void sqlite3_mutex_enter (sqlite3_mutex * p)
Definition at line 25909 of file sqlite3.c.
References sqlite3GlobalConfig.
Referenced by backupUpdate(), columnMem(), columnName(), createFunctionApi(), createModule(), findReusableFd(), lockBtreeMutex(), openDatabase(), osLocaltime(), pcache1Alloc(), posixUnlock(), releaseInodeInfo(), removeFromSharingList(), sqlite3_auto_extension(), sqlite3_backup_init(), sqlite3_cancel_auto_extension(), sqlite3_collation_needed(), sqlite3_collation_needed16(), sqlite3_commit_hook(), sqlite3_declare_vtab(), sqlite3_errmsg16(), sqlite3_exec(), sqlite3_expanded_sql(), sqlite3_finalize(), sqlite3_hard_heap_limit64(), sqlite3_initialize(), sqlite3_next_stmt(), sqlite3_overload_function(), sqlite3_profile(), sqlite3_progress_handler(), sqlite3_reset(), sqlite3_set_authorizer(), sqlite3_soft_heap_limit64(), sqlite3_step(), sqlite3_table_column_metadata(), sqlite3_trace(), sqlite3_vfs_find(), sqlite3_vfs_register(), sqlite3_vtab_config(), sqlite3AutoLoadExtensions(), sqlite3BtreeOpen(), sqlite3Malloc(), sqlite3Prepare16(), sqlite3RunParser(), unixCheckReservedLock(), unixLeaveMutex(), unixLock(), unixOpenSharedMemory(), unixShmLock(), unixShmMap(), unixShmUnmap(), and vdbeUnbind().
sqlite3_mutex_free()
void sqlite3_mutex_free (sqlite3_mutex * p)
Definition at line 25898 of file sqlite3.c.
Referenced by releaseInodeInfo(), removeFromSharingList(), sqlite3_initialize(), sqlite3LeaveMutexAndCloseZombie(), and unixShmPurge().
sqlite3_mutex_held()
int sqlite3_mutex_held (sqlite3_mutex *)
sqlite3_mutex_leave()
void sqlite3_mutex_leave (sqlite3_mutex * p)
Definition at line 25935 of file sqlite3.c.
References sqlite3GlobalConfig.
Referenced by backupUpdate(), columnMallocFailure(), columnName(), createModule(), findReusableFd(), osLocaltime(), pcache1Alloc(), posixUnlock(), releaseInodeInfo(), removeFromSharingList(), sqlite3_auto_extension(), sqlite3_backup_init(), sqlite3_bind_int(), sqlite3_bind_null(), sqlite3_bind_zeroblob64(), sqlite3_cancel_auto_extension(), sqlite3_collation_needed(), sqlite3_collation_needed16(), sqlite3_commit_hook(), sqlite3_declare_vtab(), sqlite3_errmsg16(), sqlite3_exec(), sqlite3_expanded_sql(), sqlite3_hard_heap_limit64(), sqlite3_initialize(), sqlite3_next_stmt(), sqlite3_overload_function(), sqlite3_profile(), sqlite3_progress_handler(), sqlite3_reset(), sqlite3_set_authorizer(), sqlite3_soft_heap_limit64(), sqlite3_step(), sqlite3_table_column_metadata(), sqlite3_trace(), sqlite3_vfs_find(), sqlite3_vfs_register(), sqlite3_vtab_config(), sqlite3AutoLoadExtensions(), sqlite3BtreeOpen(), sqlite3LeaveMutexAndCloseZombie(), sqlite3Malloc(), sqlite3Prepare16(), sqlite3RunParser(), unixCheckReservedLock(), unixLock(), unixOpenSharedMemory(), unixShmLock(), unixShmMap(), unixShmUnmap(), and vdbeUnbind().
sqlite3_mutex_notheld()
int sqlite3_mutex_notheld (sqlite3_mutex *)
sqlite3_mutex_try()
int sqlite3_mutex_try (sqlite3_mutex * p)
Definition at line 25920 of file sqlite3.c.
References sqlite3GlobalConfig, and SQLITE_OK.
Referenced by btreeLockCarefully().
sqlite3_next_stmt()
sqlite3_stmt* sqlite3_next_stmt (sqlite3 * pDb, sqlite3_stmt * pStmt)
Definition at line 84485 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pVdbe, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3SafetyCheckOk(), and SQLITE_MISUSE_BKPT.
sqlite3_normalized_sql()
const char* sqlite3_normalized_sql (sqlite3_stmt * pStmt)
sqlite3_open()
int sqlite3_open (const char * filename, sqlite3 ** ppDb)
Definition at line 163715 of file sqlite3.c.
sqlite3_open16()
int sqlite3_open16 (const void * filename, sqlite3 ** ppDb)
Definition at line 163735 of file sqlite3.c.
sqlite3_open_v2()
int sqlite3_open_v2 (const char * filename, sqlite3 ** ppDb, int flags, const char * zVfs)
Definition at line 163722 of file sqlite3.c.
References openDatabase(), SQLITE_OPEN_CREATE, and SQLITE_OPEN_READWRITE.
sqlite3_os_end()
int sqlite3_os_end (void)
Definition at line 41385 of file sqlite3.c.
References SQLITE_OK, and unixBigLock.
Referenced by sqlite3_shutdown().
sqlite3_os_init()
int sqlite3_os_init (void)
Definition at line 41285 of file sqlite3.c.
References ArraySize, aSyscall, dotlockIoFinder, nolockIoFinder, posixIoFinder, sqlite3_vfs_register(), sqlite3MutexAlloc(), SQLITE_MUTEX_STATIC_VFS1, SQLITE_OK, unixBigLock, and UNIXVFS.
Referenced by sqlite3OsInit().
sqlite3_overload_function()
int sqlite3_overload_function (sqlite3 * db, const char * zFuncName, int nArg)
Definition at line 162377 of file sqlite3.c.
References sqlite3::mutex, sqlite3_create_function_v2(), sqlite3_free(), sqlite3_mprintf(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3FindFunction(), sqlite3InvalidFunction(), sqlite3SafetyCheckOk(), SQLITE_MISUSE_BKPT, SQLITE_NOMEM, SQLITE_OK, SQLITE_UTF8, and zName.
Referenced by sqlite3RegisterPerConnectionBuiltinFunctions().
sqlite3_prepare()
int sqlite3_prepare (sqlite3 * db, const char * zSql, int nByte, sqlite3_stmt ** ppStmt, const char ** pzTail)
Definition at line 128790 of file sqlite3.c.
sqlite3_prepare16()
int sqlite3_prepare16 (sqlite3 * db, const void * zSql, int nByte, sqlite3_stmt ** ppStmt, const void ** pzTail)
Definition at line 128906 of file sqlite3.c.
sqlite3_prepare16_v2()
int sqlite3_prepare16_v2 (sqlite3 * db, const void * zSql, int nByte, sqlite3_stmt ** ppStmt, const void ** pzTail)
Definition at line 128918 of file sqlite3.c.
References sqlite3Prepare16(), and SQLITE_OK.
sqlite3_prepare16_v3()
int sqlite3_prepare16_v3 (sqlite3 * db, const void * zSql, int nByte, unsigned int prepFlags, sqlite3_stmt ** ppStmt, const void ** pzTail)
Definition at line 128930 of file sqlite3.c.
sqlite3_prepare_v2()
int sqlite3_prepare_v2 (sqlite3 * db, const char * zSql, int nByte, sqlite3_stmt ** ppStmt, const char ** pzTail)
Definition at line 128802 of file sqlite3.c.
References sqlite3LockAndPrepare(), and SQLITE_OK.
Referenced by execSql(), and sqlite3_exec().
sqlite3_prepare_v3()
int sqlite3_prepare_v3 (sqlite3 * db, const char * zSql, int nByte, unsigned int prepFlags, sqlite3_stmt ** ppStmt, const char ** pzTail)
Definition at line 128820 of file sqlite3.c.
sqlite3_profile()
void* sqlite3_profile (sqlite3 * db, void(*)(void *, const char *, sqlite3_uint64) xProfile, void * pArg)
Definition at line 162461 of file sqlite3.c.
References sqlite3::mTrace, sqlite3::mutex, sqlite3::pProfileArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3SafetyCheckOk(), SQLITE_MISUSE_BKPT, SQLITE_TRACE_NONLEGACY_MASK, SQLITE_TRACE_XPROFILE, and sqlite3::xProfile.
sqlite3_progress_handler()
void sqlite3_progress_handler (sqlite3 * db, int nOps, int(*)(void *) xProgress, void * pArg)
Definition at line 162035 of file sqlite3.c.
References sqlite3::mutex, sqlite3::nProgressOps, sqlite3::pProgressArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3SafetyCheckOk(), SQLITE_MISUSE_BKPT, and sqlite3::xProgress.
sqlite3_randomness()
void sqlite3_randomness (int N, void * P)
Definition at line 30217 of file sqlite3.c.
Referenced by randomFunc(), sqlite3BitvecBuiltinTest(), sqlite3ColumnsFromExprList(), unixGetTempname(), unixOpen(), vdbeCommit(), walCheckpoint(), walRestartLog(), and writeJournalHdr().
sqlite3_realloc()
void* sqlite3_realloc (void * pOld, int n)
Definition at line 27774 of file sqlite3.c.
Referenced by unixShmMap().
sqlite3_realloc64()
void* sqlite3_realloc64 (void * pOld, sqlite3_uint64 n)
Definition at line 27781 of file sqlite3.c.
Referenced by sqlite3_auto_extension().
sqlite3_release_memory()
int sqlite3_release_memory (int n)
Definition at line 27290 of file sqlite3.c.
References UNUSED_PARAMETER.
sqlite3_reset()
int sqlite3_reset (sqlite3_stmt * pStmt)
Definition at line 82911 of file sqlite3.c.
References checkProfileCallback, Vdbe::db, sqlite3::errMask, sqlite3::mutex, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ApiExit(), sqlite3VdbeReset(), sqlite3VdbeRewind(), and SQLITE_OK.
Referenced by sqlite3_step(), and sqlite3Step().
sqlite3_reset_auto_extension()
void sqlite3_reset_auto_extension (void)
Definition at line 124725 of file sqlite3.c.
Referenced by sqlite3_shutdown().
sqlite3_result_blob()
void sqlite3_result_blob (sqlite3_context * pCtx, const void * z, int n, void(*)(void *) xDel)
Definition at line 83183 of file sqlite3.c.
Referenced by statGet().
sqlite3_result_blob64()
void sqlite3_result_blob64 (sqlite3_context * pCtx, const void * z, sqlite3_uint64 n, void(*)(void *) xDel)
Definition at line 83193 of file sqlite3.c.
References sqlite3_value::db, sqlite3::mutex, sqlite3_context::pOut, setResultStrOrError(), and sqlite3_mutex_held().
Referenced by substrFunc().
sqlite3_result_double()
void sqlite3_result_double (sqlite3_context * pCtx, double rVal)
Definition at line 83207 of file sqlite3.c.
References invokeValueDestructor().
Referenced by absFunc(), and juliandayFunc().
sqlite3_result_error()
void sqlite3_result_error (sqlite3_context * pCtx, const char * z, int n)
Definition at line 83211 of file sqlite3.c.
Referenced by absFunc(), attachFunc(), detachFunc(), likeFunc(), loadExt(), localtimeOffset(), ntileStepFunc(), renameColumnParseError(), sqlite3InvalidFunction(), and sqlite3NotPureFunc().
sqlite3_result_error16()
void sqlite3_result_error16 (sqlite3_context * pCtx, const void * z, int n)
Definition at line 83217 of file sqlite3.c.
References sqlite3_value::db, sqlite3_context::isError, sqlite3::mutex, sqlite3_context::pOut, sqlite3_mutex_held(), sqlite3VdbeMemSetStr(), SQLITE_ERROR, SQLITE_TRANSIENT, and SQLITE_UTF8.
sqlite3_result_error_code()
void sqlite3_result_error_code (sqlite3_context * pCtx, int errCode)
Definition at line 83324 of file sqlite3.c.
References SQLITE_TOOBIG.
Referenced by attachFunc(), renameColumnFunc(), and renameTableFunc().
sqlite3_result_error_nomem()
void sqlite3_result_error_nomem (sqlite3_context * pCtx)
Definition at line 83344 of file sqlite3.c.
Referenced by charFunc(), contextMalloc(), instrFunc(), replaceFunc(), statGet(), statInit(), and strftimeFunc().
sqlite3_result_error_toobig()
void sqlite3_result_error_toobig (sqlite3_context * pCtx)
Definition at line 83336 of file sqlite3.c.
Referenced by contextMalloc(), invokeValueDestructor(), replaceFunc(), and strftimeFunc().
sqlite3_result_int()
void sqlite3_result_int (sqlite3_context * pCtx, int iVal)
Definition at line 83223 of file sqlite3.c.
References sqlite3_value::db, sqlite3_context::isError, sqlite3::mutex, sqlite3_context::pOut, sqlite3_mutex_held(), sqlite3VdbeMemSetStr(), SQLITE_ERROR, SQLITE_TRANSIENT, and SQLITE_UTF16NATIVE.
Referenced by changes(), compileoptionusedFunc(), instrFunc(), likeFunc(), and renameTableTest().
sqlite3_result_int64()
void sqlite3_result_int64 (sqlite3_context * pCtx, sqlite3_int64 iVal)
Definition at line 83227 of file sqlite3.c.
Referenced by absFunc(), countInverse(), randomFunc(), and statGet().
sqlite3_result_null()
void sqlite3_result_null (sqlite3_context * pCtx)
Definition at line 83231 of file sqlite3.c.
Referenced by absFunc().
sqlite3_result_pointer()
void sqlite3_result_pointer (sqlite3_context * pCtx, void * pPtr, const char * zPType, void(*)(void *) xDestructor)
Definition at line 83235 of file sqlite3.c.
sqlite3_result_subtype()
void sqlite3_result_subtype (sqlite3_context * pCtx, unsigned int eSubtype)
Definition at line 83247 of file sqlite3.c.
sqlite3_result_text()
void sqlite3_result_text (sqlite3_context * pCtx, const char * z, int n, void(*)(void *) xDel)
Definition at line 83253 of file sqlite3.c.
References sqlite3_value::db, sqlite3_value::eSubtype, sqlite3_value::flags, MEM_Subtype, sqlite3::mutex, sqlite3_context::pOut, and sqlite3_mutex_held().
Referenced by dateFunc(), datetimeFunc(), quoteFunc(), renameEditSql(), replaceFunc(), sourceidFunc(), statGet(), strftimeFunc(), and timeFunc().
sqlite3_result_text16()
void sqlite3_result_text16 (sqlite3_context * pCtx, const void * z, int n, void(*)(void *) xDel)
Definition at line 83279 of file sqlite3.c.
sqlite3_result_text16be()
void sqlite3_result_text16be (sqlite3_context * pCtx, const void * z, int n, void(*)(void *) xDel)
Definition at line 83288 of file sqlite3.c.
References sqlite3_value::db, sqlite3::mutex, sqlite3_context::pOut, setResultStrOrError(), sqlite3_mutex_held(), and SQLITE_UTF16NATIVE.
sqlite3_result_text16le()
void sqlite3_result_text16le (sqlite3_context * pCtx, const void * z, int n, void(*)(void *) xDel)
Definition at line 83297 of file sqlite3.c.
References sqlite3_value::db, sqlite3::mutex, sqlite3_context::pOut, setResultStrOrError(), sqlite3_mutex_held(), and SQLITE_UTF16BE.
sqlite3_result_text64()
void sqlite3_result_text64 (sqlite3_context * pCtx, const char * z, sqlite3_uint64 n, void(*)(void *) xDel, unsigned char encoding)
Definition at line 83262 of file sqlite3.c.
References sqlite3_value::db, sqlite3::mutex, sqlite3_context::pOut, setResultStrOrError(), sqlite3_mutex_held(), and SQLITE_UTF8.
Referenced by charFunc(), and substrFunc().
sqlite3_result_value()
void sqlite3_result_value (sqlite3_context * pCtx, sqlite3_value * pValue)
Definition at line 83307 of file sqlite3.c.
References sqlite3_value::db, sqlite3::mutex, sqlite3_context::pOut, setResultStrOrError(), sqlite3_mutex_held(), and SQLITE_UTF16LE.
Referenced by last_valueFinalizeFunc(), nullifFunc(), quoteFunc(), and replaceFunc().
sqlite3_result_zeroblob()
void sqlite3_result_zeroblob (sqlite3_context * pCtx, int n)
Definition at line 83311 of file sqlite3.c.
sqlite3_result_zeroblob64()
int sqlite3_result_zeroblob64 (sqlite3_context * pCtx, sqlite3_uint64 n)
Definition at line 83315 of file sqlite3.c.
sqlite3_rollback_hook()
void* sqlite3_rollback_hook (sqlite3 * db, void(*)(void *) xCallback, void * pArg)
Definition at line 162541 of file sqlite3.c.
sqlite3_rtree_geometry_callback()
int sqlite3_rtree_geometry_callback (sqlite3 * db, const char * zGeom, int(*)(sqlite3_rtree_geometry *, int, sqlite3_rtree_dbl *, int *) xGeom, void * pContext)
sqlite3_rtree_query_callback()
int sqlite3_rtree_query_callback (sqlite3 * db, const char * zQueryFunc, int(*)(sqlite3_rtree_query_info *) xQueryFunc, void * pContext, void(*)(void *) xDestructor)
sqlite3_serialize()
unsigned char* sqlite3_serialize (sqlite3 * db, const char * zSchema, sqlite3_int64 * piSize, unsigned int mFlags)
sqlite3_set_authorizer()
int sqlite3_set_authorizer (sqlite3 * db, int(*)(void *, int, const char *, const char *, const char *, const char *) xAuth, void * pUserData)
Definition at line 109931 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pAuthArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ExpirePreparedStatements(), sqlite3SafetyCheckOk(), SQLITE_MISUSE_BKPT, SQLITE_OK, and sqlite3::xAuth.
sqlite3_set_auxdata()
void sqlite3_set_auxdata (sqlite3_context * pCtx, int N, void * pAux, void(*)(void *) xDelete)
Definition at line 83721 of file sqlite3.c.
References sqlite3_value::db, Vdbe::db, AuxData::iAuxArg, AuxData::iAuxOp, sqlite3_context::iOp, sqlite3_context::isError, sqlite3::mutex, AuxData::pAux, Vdbe::pAuxData, AuxData::pNextAux, sqlite3_context::pOut, sqlite3_context::pVdbe, sqlite3_mutex_held(), sqlite3DbMallocZero(), and AuxData::xDeleteAux.
sqlite3_set_last_insert_rowid()
void sqlite3_set_last_insert_rowid (sqlite3 * db, sqlite3_int64 iRowid)
Definition at line 161402 of file sqlite3.c.
sqlite3_shutdown()
int sqlite3_shutdown (void)
Definition at line 160706 of file sqlite3.c.
References sqlite3_data_directory, sqlite3_os_end(), sqlite3_reset_auto_extension(), sqlite3_temp_directory, sqlite3GlobalConfig, sqlite3MallocEnd(), sqlite3MutexEnd(), sqlite3PcacheShutdown(), and SQLITE_OK.
Referenced by main().
sqlite3_sleep()
int sqlite3_sleep (int ms)
Definition at line 164087 of file sqlite3.c.
sqlite3_snapshot_cmp()
int sqlite3_snapshot_cmp (sqlite3_snapshot * p1, sqlite3_snapshot * p2)
sqlite3_snapshot_free()
void sqlite3_snapshot_free (sqlite3_snapshot *)
sqlite3_snapshot_get()
int sqlite3_snapshot_get (sqlite3 * db, const char * zSchema, sqlite3_snapshot ** ppSnapshot)
sqlite3_snapshot_open()
int sqlite3_snapshot_open (sqlite3 * db, const char * zSchema, sqlite3_snapshot * pSnapshot)
sqlite3_snapshot_recover()
int sqlite3_snapshot_recover (sqlite3 * db, const char * zDb)
sqlite3_snprintf()
char* sqlite3_snprintf (int n, char * zBuf, const char * zFormat, ...)
Definition at line 29320 of file sqlite3.c.
Referenced by createTableStmt(), dateFunc(), datetimeFunc(), detachFunc(), fillInUnixFile(), openDirectory(), quoteFunc(), sqlite3LoadExtension(), statGet(), strftimeFunc(), timeFunc(), unixGetTempname(), unixOpenSharedMemory(), and vdbeCommit().
sqlite3_soft_heap_limit()
void sqlite3_soft_heap_limit (int N)
Definition at line 27387 of file sqlite3.c.
sqlite3_soft_heap_limit64()
sqlite3_int64 sqlite3_soft_heap_limit64 (sqlite3_int64 N)
Definition at line 27362 of file sqlite3.c.
References AtomicStore, mem0, sqlite3_initialize(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3StatusValue(), and SQLITE_STATUS_MEMORY_USED.
sqlite3_sourceid()
const char* sqlite3_sourceid (void)
Definition at line 229780 of file sqlite3.c.
References SQLITE_SOURCE_ID.
Referenced by sourceidFunc(), and sqlite3CorruptError().
sqlite3_sql()
const char* sqlite3_sql (sqlite3_stmt * pStmt)
Definition at line 84536 of file sqlite3.c.
Referenced by sqlite3_expanded_sql(), and sqlite3Reprepare().
sqlite3_status()
int sqlite3_status (int op, int * pCurrent, int * pHighwater, int resetFlag)
Definition at line 21427 of file sqlite3.c.
sqlite3_status64()
int sqlite3_status64 (int op, sqlite3_int64 * pCurrent, sqlite3_int64 * pHighwater, int resetFlag)
Definition at line 21402 of file sqlite3.c.
Referenced by sqlite3_memory_highwater().
sqlite3_step()
int sqlite3_step (sqlite3_stmt * pStmt)
Definition at line 83535 of file sqlite3.c.
References Vdbe::db, Vdbe::doingRerun, Vdbe::expired, sqlite3::mallocFailed, sqlite3::mutex, Vdbe::pc, sqlite3::pErr, Vdbe::rc, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_reset(), sqlite3_value_text(), sqlite3ApiExit(), sqlite3DbFree(), sqlite3DbStrDup(), sqlite3Reprepare(), sqlite3Step(), SQLITE_MAX_SCHEMA_RETRY, SQLITE_MISUSE_BKPT, SQLITE_NOMEM_BKPT, SQLITE_OK, SQLITE_SCHEMA, vdbeSafetyNotNull(), and Vdbe::zErrMsg.
Referenced by blobSeekToRow(), execSql(), and sqlite3_exec().
sqlite3_stmt_busy()
int sqlite3_stmt_busy (sqlite3_stmt * pStmt)
Definition at line 84474 of file sqlite3.c.
sqlite3_stmt_isexplain()
int sqlite3_stmt_isexplain (sqlite3_stmt * pStmt)
Definition at line 84467 of file sqlite3.c.
sqlite3_stmt_readonly()
int sqlite3_stmt_readonly (sqlite3_stmt * pStmt)
Definition at line 84459 of file sqlite3.c.
sqlite3_stmt_scanstatus()
int sqlite3_stmt_scanstatus (sqlite3_stmt * pStmt, int idx, int iScanStatusOp, void * pOut)
sqlite3_stmt_scanstatus_reset()
void sqlite3_stmt_scanstatus_reset (sqlite3_stmt *)
sqlite3_stmt_status()
int sqlite3_stmt_status (sqlite3_stmt * pStmt, int op, int resetFlg)
Definition at line 84506 of file sqlite3.c.
sqlite3_str_append()
void sqlite3_str_append (sqlite3_str * p, const char * zIn, int N)
Definition at line 29080 of file sqlite3.c.
Referenced by explainAppendTerm(), explainIndexRange(), sqlite3_str_vappendf(), sqlite3RunParser(), sqlite3VdbeDisplayP4(), and sqlite3WhereExplainOneScan().
sqlite3_str_appendall()
void sqlite3_str_appendall (sqlite3_str * p, const char * zIn)
Definition at line 29097 of file sqlite3.c.
Referenced by explainAppendTerm(), sqlite3_str_vappendf(), sqlite3VdbeDisplayP4(), and sqlite3WhereExplainOneScan().
sqlite3_str_appendchar()
void sqlite3_str_appendchar (sqlite3_str * p, int N, char C)
Definition at line 29052 of file sqlite3.c.
Referenced by sqlite3_str_vappendf().
sqlite3_str_appendf()
void sqlite3_str_appendf (sqlite3_str * p, const char * zFormat, ...)
Definition at line 29397 of file sqlite3.c.
References sqlite3_str_vappendf().
Referenced by explainIndexRange(), sqlite3RunParser(), sqlite3VdbeDisplayP4(), sqlite3WhereExplainOneScan(), and vdbeMemRenderNum().
sqlite3_str_errcode()
int sqlite3_str_errcode (sqlite3_str * p)
Definition at line 29154 of file sqlite3.c.
sqlite3_str_finish()
char* sqlite3_str_finish (sqlite3_str * p)
Definition at line 29142 of file sqlite3.c.
References SQLITE_NOMEM.
Referenced by sqlite3RunParser().
sqlite3_str_length()
int sqlite3_str_length (sqlite3_str * p)
Definition at line 29159 of file sqlite3.c.
References sqlite3_str::accError, and SQLITE_NOMEM.
sqlite3_str_new()
sqlite3_str* sqlite3_str_new (sqlite3 * db)
Definition at line 29208 of file sqlite3.c.
Referenced by sqlite3RunParser().
sqlite3_str_reset()
void sqlite3_str_reset (sqlite3_str * p)
Definition at line 29173 of file sqlite3.c.
Referenced by sqlite3BtreeIntegrityCheck(), and sqlite3StrAccumEnlarge().
sqlite3_str_value()
char* sqlite3_str_value (sqlite3_str * p)
Definition at line 29164 of file sqlite3.c.
References sqlite3_str::nChar.
sqlite3_str_vappendf()
void sqlite3_str_vappendf (sqlite3_str * pAccum, const char * zFormat, va_list ap)
Definition at line 28298 of file sqlite3.c.
References SrcList::a, sqlite3_str::accError, aDigits, aPrefix, ArraySize, arRound, et_info::base, et_info::charset, sqlite3_str::db, et_getdigit(), etBUFSIZE, etCHARX, etDECIMAL, etDYNSTRING, etEXP, etFLOAT, etGENERIC, etINVALID, etORDINAL, etPERCENT, etPOINTER, etRADIX, etSIZE, etSQLESCAPE, etSQLESCAPE2, etSQLESCAPE3, etSRCLIST, etSTRING, etTOKEN, FLAG_SIGNED, et_info::flags, fmtinfo, getDoubleArg(), getIntArg(), getTextArg(), length(), LONGDOUBLE_TYPE, MAX, sqlite3_str::mxAlloc, Token::n, sqlite3_str::nAlloc, sqlite3_str::nChar, et_info::prefix, sqlite3_str::printfFlags, printfTempBuf(), SMALLEST_INT64, sqlite3_str_append(), sqlite3_str_appendall(), sqlite3_str_appendchar(), sqlite3DbFree(), sqlite3DbMallocSize(), sqlite3IsNaN(), SQLITE_FP_PRECISION_LIMIT, SQLITE_PRINTF_INTERNAL, SQLITE_PRINTF_MALLOCED, SQLITE_PRINTF_SQLFUNC, SQLITE_SKIP_UTF8, testcase, et_info::type, width, Token::z, and sqlite3_str::zText.
Referenced by renderLogMsg(), and sqlite3_str_appendf().
sqlite3_strglob()
int sqlite3_strglob (const char * zGlob, const char * zStr)
Definition at line 117557 of file sqlite3.c.
Referenced by decodeIntArray().
sqlite3_stricmp()
int sqlite3_stricmp (const char * zLeft, const char * zRight)
Definition at line 31416 of file sqlite3.c.
Referenced by analysisLoader(), isSelfJoinView(), lookupName(), parseModifier(), renameColumnElistNames(), renameColumnFunc(), renameColumnIdlistNames(), renameTableFunc(), resolveAsName(), sqlite3AddColumn(), sqlite3CheckObjectName(), sqlite3ExprCompare(), sqlite3FindDbName(), sqlite3FkCheck(), sqlite3FkRequired(), sqlite3GenerateRowDelete(), xferCompatibleIndex(), and xferOptimization().
sqlite3_strlike()
int sqlite3_strlike (const char * zGlob, const char * zStr, unsigned int cEsc)
Definition at line 117565 of file sqlite3.c.
sqlite3_strnicmp()
int sqlite3_strnicmp (const char * zLeft, const char * zRight, int N)
Definition at line 31443 of file sqlite3.c.
Referenced by codeInteger(), execSql(), parseModifier(), sqlite3InitCallback(), sqlite3IsShadowTableOf(), sqlite3LoadExtension(), sqlite3LocateTable(), sqlite3PragmaVtabRegister(), and yy_reduce().
sqlite3_system_errno()
int sqlite3_system_errno (sqlite3 * db)
Definition at line 162906 of file sqlite3.c.
sqlite3_table_column_metadata()
int sqlite3_table_column_metadata (sqlite3 * db, const char * zDbName, const char * zTableName, const char * zColumnName, char const ** pzDataType, char const ** pzCollSeq, int * pNotNull, int * pPrimaryKey, int * pAutoinc)
Definition at line 163969 of file sqlite3.c.
References Table::aCol, COLFLAG_PRIMKEY, Column::colFlags, HasRowid, Table::iPKey, sqlite3::mutex, Table::nCol, Column::notNull, Table::pSelect, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ApiExit(), sqlite3BtreeEnterAll(), sqlite3BtreeLeaveAll(), sqlite3ColumnType(), sqlite3DbFree(), sqlite3ErrorWithMsg(), sqlite3FindTable(), sqlite3Init(), sqlite3IsRowid(), sqlite3MPrintf(), sqlite3SafetyCheckOk(), sqlite3StrBINARY, sqlite3StrICmp(), SQLITE_ERROR, SQLITE_MISUSE_BKPT, SQLITE_OK, Table::tabFlags, TF_Autoincrement, Column::zColl, and Column::zName.
sqlite3_test_control()
int sqlite3_test_control (int op, ...)
Definition at line 164164 of file sqlite3.c.
sqlite3_thread_cleanup()
void sqlite3_thread_cleanup (void)
Definition at line 163961 of file sqlite3.c.
sqlite3_threadsafe()
int sqlite3_threadsafe (void)
Definition at line 160458 of file sqlite3.c.
References SQLITE_VERSION_NUMBER.
sqlite3_total_changes()
int sqlite3_total_changes (sqlite3 * db)
Definition at line 161430 of file sqlite3.c.
sqlite3_trace()
void* sqlite3_trace (sqlite3 * db, void(*)(void *, const char *) xTrace, void * pArg)
Definition at line 162410 of file sqlite3.c.
References sqlite3::mTrace, sqlite3::mutex, sqlite3::pTraceArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3SafetyCheckOk(), SQLITE_MISUSE_BKPT, SQLITE_TRACE_LEGACY, and sqlite3::xTrace.
sqlite3_trace_v2()
int sqlite3_trace_v2 (sqlite3 * db, unsigned uMask, int(*)(unsigned, void *, void *, void *) xCallback, void * pCtx)
Definition at line 162431 of file sqlite3.c.
sqlite3_transfer_bindings()
int sqlite3_transfer_bindings (sqlite3_stmt * pFromStmt, sqlite3_stmt * pToStmt)
Definition at line 84427 of file sqlite3.c.
References Vdbe::expired, Vdbe::expmask, Vdbe::nVar, Vdbe::prepFlags, sqlite3TransferBindings(), SQLITE_ERROR, and SQLITE_PREPARE_SAVESQL.
sqlite3_unlock_notify()
int sqlite3_unlock_notify (sqlite3 * pBlocked, void(*)(void **apArg, int nArg) xNotify, void * pNotifyArg)
sqlite3_update_hook()
void* sqlite3_update_hook (sqlite3 * db, void(*)(void *, int, char const *, char const *, sqlite3_int64) xCallback, void * pArg)
Definition at line 162516 of file sqlite3.c.
sqlite3_uri_boolean()
int sqlite3_uri_boolean (const char * zFile, const char * zParam, int bDefault)
Definition at line 164647 of file sqlite3.c.
Referenced by fillInUnixFile(), sqlite3PagerOpen(), and unixOpenSharedMemory().
sqlite3_uri_int64()
sqlite3_int64 sqlite3_uri_int64 (const char * zFilename, const char * zParam, sqlite3_int64 bDflt)
Definition at line 164656 of file sqlite3.c.
sqlite3_uri_key()
const char* sqlite3_uri_key (const char * zFilename, int N)
Definition at line 164633 of file sqlite3.c.
sqlite3_uri_parameter()
const char* sqlite3_uri_parameter (const char * zFilename, const char * zParam)
Definition at line 164624 of file sqlite3.c.
References databaseName().
Referenced by findCreateFileMode().
sqlite3_user_data()
void* sqlite3_user_data (sqlite3_context * p)
Definition at line 83584 of file sqlite3.c.
References sqlite3_context::pFunc, and FuncDef::pUserData.
Referenced by likeFunc(), minmaxStep(), and sqlite3InvalidFunction().
sqlite3_value_blob()
const void* sqlite3_value_blob (sqlite3_value * pVal)
Definition at line 82957 of file sqlite3.c.
References ExpandBlob, sqlite3_value::flags, MEM_Blob, MEM_Null, MEM_Str, SQLITE_OK, and sqlite3_value::z.
Referenced by instrFunc(), quoteFunc(), statGet(), statPush(), and substrFunc().
sqlite3_value_bytes()
int sqlite3_value_bytes (sqlite3_value * pVal)
Definition at line 82970 of file sqlite3.c.
Referenced by instrFunc(), isDate(), likeFunc(), quoteFunc(), replaceFunc(), statPush(), and substrFunc().
sqlite3_value_bytes16()
int sqlite3_value_bytes16 (sqlite3_value * pVal)
Definition at line 82973 of file sqlite3.c.
sqlite3_value_double()
double sqlite3_value_double (sqlite3_value * pVal)
Definition at line 82976 of file sqlite3.c.
References sqlite3ValueBytes(), and SQLITE_UTF8.
Referenced by absFunc(), isDate(), and quoteFunc().
sqlite3_value_dup()
sqlite3_value* sqlite3_value_dup (const sqlite3_value * pOrig)
Definition at line 83117 of file sqlite3.c.
References sqlite3_value::flags, and MEM_FromBind.
Referenced by instrFunc().
sqlite3_value_free()
void sqlite3_value_free (sqlite3_value * pOld)
Definition at line 83140 of file sqlite3.c.
Referenced by instrFunc(), and last_valueValueFunc().
sqlite3_value_frombind()
int sqlite3_value_frombind (sqlite3_value * pVal)
Definition at line 83111 of file sqlite3.c.
References sqlite3_value::flags, MEM_Null, and MEM_Zero.
sqlite3_value_int()
int sqlite3_value_int (sqlite3_value * pVal)
Definition at line 82979 of file sqlite3.c.
References sqlite3ValueBytes(), and SQLITE_UTF16NATIVE.
Referenced by compileoptiongetFunc(), errlogFunc(), renameColumnFunc(), renameTableFunc(), renameTableTest(), statGet(), statInit(), statPush(), substrFunc(), and windowExprGtZero().
sqlite3_value_int64()
sqlite3_int64 sqlite3_value_int64 (sqlite3_value * pVal)
Definition at line 82982 of file sqlite3.c.
References sqlite3VdbeRealValue().
Referenced by absFunc(), charFunc(), ntileStepFunc(), statInit(), statPush(), and sumStep().
sqlite3_value_nochange()
int sqlite3_value_nochange (sqlite3_value * pVal)
Definition at line 83106 of file sqlite3.c.
Referenced by sqlite3_vtab_nochange(), and sqlite3VdbeMemExpandBlob().
sqlite3_value_numeric_type()
int sqlite3_value_numeric_type (sqlite3_value * pVal)
Definition at line 85445 of file sqlite3.c.
References applyNumericAffinity(), eType, sqlite3_value_type(), and SQLITE_TEXT.
Referenced by sumStep().
sqlite3_value_pointer()
void* sqlite3_value_pointer (sqlite3_value * pVal, const char * zPType)
Definition at line 82989 of file sqlite3.c.
sqlite3_value_subtype()
unsigned int sqlite3_value_subtype (sqlite3_value * pVal)
Definition at line 82985 of file sqlite3.c.
References sqlite3VdbeIntValue().
sqlite3_value_text()
const unsigned char* sqlite3_value_text (sqlite3_value * pVal)
Definition at line 83002 of file sqlite3.c.
References sqlite3_value::z.
Referenced by attachFunc(), columnName(), compileoptionusedFunc(), detachFunc(), errlogFunc(), exprCompareVariable(), instrFunc(), isDate(), isLikeOrGlob(), likeFunc(), loadExt(), quoteFunc(), renameColumnFunc(), renameColumnParseError(), renameTableFunc(), renameTableTest(), replaceFunc(), sqlite3_step(), strftimeFunc(), and substrFunc().
sqlite3_value_text16()
const void* sqlite3_value_text16 (sqlite3_value * pVal)
Definition at line 83006 of file sqlite3.c.
Referenced by columnName(), sqlite3_column_type(), and sqlite3_errmsg16().
sqlite3_value_text16be()
const void* sqlite3_value_text16be (sqlite3_value * pVal)
Definition at line 83009 of file sqlite3.c.
sqlite3_value_text16le()
const void* sqlite3_value_text16le (sqlite3_value * pVal)
Definition at line 83012 of file sqlite3.c.
References sqlite3ValueText(), and SQLITE_UTF16NATIVE.
sqlite3_value_type()
int sqlite3_value_type (sqlite3_value * pVal)
Definition at line 83020 of file sqlite3.c.
Referenced by absFunc(), exprCompareVariable(), instrFunc(), isDate(), isLikeOrGlob(), likeFunc(), minmaxStep(), quoteFunc(), replaceFunc(), sqlite3_value_numeric_type(), statPush(), and substrFunc().
sqlite3_vfs_find()
sqlite3_vfs* sqlite3_vfs_find (const char * zVfsName)
Definition at line 23262 of file sqlite3.c.
References sqlite3_vfs::pNext, sqlite3_initialize(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3MutexAlloc(), SQLITE_MUTEX_STATIC_MASTER, vfsList, and sqlite3_vfs::zName.
Referenced by attachFunc(), and sqlite3ParseUri().
sqlite3_vfs_register()
int sqlite3_vfs_register (sqlite3_vfs * pVfs, int makeDflt)
Definition at line 23308 of file sqlite3.c.
References MUTEX_LOGIC, sqlite3_vfs::pNext, sqlite3_initialize(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3MutexAlloc(), SQLITE_MISUSE_BKPT, SQLITE_MUTEX_STATIC_MASTER, SQLITE_OK, vfsList, and vfsUnlink().
Referenced by sqlite3_os_init().
sqlite3_vfs_unregister()
int sqlite3_vfs_unregister (sqlite3_vfs * pVfs)
Definition at line 23336 of file sqlite3.c.
sqlite3_vmprintf()
char* sqlite3_vmprintf (const char * zFormat, va_list ap)
Definition at line 29256 of file sqlite3.c.
sqlite3_vsnprintf()
char* sqlite3_vsnprintf (int n, char * zBuf, const char * zFormat, va_list ap)
Definition at line 29305 of file sqlite3.c.
References SQLITE_MISUSE_BKPT.
sqlite3_vtab_collation()
const char* sqlite3_vtab_collation (sqlite3_index_info * pIdxInfo, int iCons)
Definition at line 148291 of file sqlite3.c.
References WhereClause::a, sqlite3_index_info::aConstraint, sqlite3_index_info::sqlite3_index_constraint::iTermOffset, WhereTerm::pExpr, Expr::pLeft, HiddenIndexInfo::pParse, HiddenIndexInfo::pWC, sqlite3ExprCompareCollSeq(), sqlite3StrBINARY, and CollSeq::zName.
sqlite3_vtab_config()
int sqlite3_vtab_config (sqlite3 * db, int op, ...)
Definition at line 140225 of file sqlite3.c.
References VTable::bConstraint, VTable::eVtabRisk, IsVirtual, sqlite3::mutex, VtabCtx::pTab, sqlite3::pVtabCtx, VtabCtx::pVTable, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3Error(), sqlite3SafetyCheckOk(), SQLITE_MISUSE_BKPT, SQLITE_OK, SQLITE_VTAB_CONSTRAINT_SUPPORT, SQLITE_VTAB_DIRECTONLY, SQLITE_VTAB_INNOCUOUS, SQLITE_VTABRISK_High, and SQLITE_VTABRISK_Low.
sqlite3_vtab_nochange()
int sqlite3_vtab_nochange (sqlite3_context * p)
Definition at line 83618 of file sqlite3.c.
References sqlite3_context::pOut, and sqlite3_value_nochange().
sqlite3_vtab_on_conflict()
int sqlite3_vtab_on_conflict (sqlite3 * db)
Definition at line 140207 of file sqlite3.c.
References OE_Abort, OE_Fail, OE_Ignore, OE_Replace, OE_Rollback, sqlite3SafetyCheckOk(), SQLITE_ABORT, SQLITE_FAIL, SQLITE_IGNORE, SQLITE_MISUSE_BKPT, SQLITE_REPLACE, SQLITE_ROLLBACK, and sqlite3::vtabOnConflict.
sqlite3_wal_autocheckpoint()
int sqlite3_wal_autocheckpoint (sqlite3 * db, int N)
Definition at line 162616 of file sqlite3.c.
References sqlite3_wal_hook(), sqlite3SafetyCheckOk(), sqlite3WalDefaultHook(), SQLITE_INT_TO_PTR, SQLITE_MISUSE_BKPT, SQLITE_OK, and UNUSED_PARAMETER.
sqlite3_wal_checkpoint()
int sqlite3_wal_checkpoint (sqlite3 * db, const char * zDb)
Definition at line 162726 of file sqlite3.c.
References sqlite3_wal_checkpoint_v2(), and SQLITE_CHECKPOINT_PASSIVE.
Referenced by sqlite3WalDefaultHook().
sqlite3_wal_checkpoint_v2()
int sqlite3_wal_checkpoint_v2 (sqlite3 * db, const char * zDb, int eMode, int * pnLog, int * pnCkpt)
Definition at line 162664 of file sqlite3.c.
Referenced by sqlite3_wal_checkpoint().
sqlite3_wal_hook()
void* sqlite3_wal_hook (sqlite3 * db, int(*)(void *, sqlite3 *, const char *, int) xCallback, void * pArg)
Definition at line 162637 of file sqlite3.c.
Referenced by sqlite3_wal_autocheckpoint().
sqlite3_win32_set_directory()
int sqlite3_win32_set_directory (unsigned long type, void * zValue)
sqlite3_win32_set_directory16()
int sqlite3_win32_set_directory16 (unsigned long type, const void * zValue)
sqlite3_win32_set_directory8()
int sqlite3_win32_set_directory8 (unsigned long type, const char * zValue)
Variable Documentation
sqlite3_data_directory
char* sqlite3_data_directory extern
Definition at line 7110 of file sqlite3.c.
Referenced by sqlite3_shutdown().
sqlite3_temp_directory
char* sqlite3_temp_directory extern
Definition at line 7073 of file sqlite3.c.
Referenced by sqlite3_shutdown().
sqlite3_version
const char sqlite3_version[] extern
Definition at line 1201 of file sqlite3.c.
Referenced by sqlite3_libversion().