ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/wrapper/cccorelib/src/StatisticalTestingTools.cpp File Reference
StatisticalTestingTools.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <GenericCloud.h>
#include <GenericDistribution.h>
#include <GenericIndexedCloudPersist.h>
#include <GenericProgressCallback.h>
#include <StatisticalTestingTools.h>
Functions
void define_StatisticalTestingTools (py::module &cccorelib)
Function Documentation
define_StatisticalTestingTools()
void define_StatisticalTestingTools (py::module & cccorelib)
Definition at line 21 of file StatisticalTestingTools.cpp.
References cloudViewer::StatisticalTestingTools::computeAdaptativeChi2Dist(), cloudViewer::StatisticalTestingTools::computeChi2Fractile(), cloudViewer::StatisticalTestingTools::computeChi2Probability(), and cloudViewer::StatisticalTestingTools::testCloudWithStatisticalModel().
Referenced by define_cccorelib().