ACloudViewer: cloudViewer::visualization::gui::SceneWidget::Impl Struct Reference
cloudViewer::visualization::gui::SceneWidget::Impl Struct Reference
Public Member Functions
void UpdateFromIntrinsicMatrix (const Rect &frame)
void UpdateFarPlane (const Rect &frame, float verticalFoV)
Public Attributes
std::string id_
std::shared_ptr< rendering::CloudViewerScene > scene_
ccBBox bounds_
std::shared_ptr< Interactors > controls_
std::function< void(const Eigen::Vector3f &)> on_light_dir_changed_
std::function< void(rendering::Camera *)> on_camera_changed_
int buttons_down_ = 0
double last_fast_time_ = 0.0
bool frame_rect_changed_ = false
SceneWidget::Quality current_render_quality_ = SceneWidget::Quality::BEST
bool scene_caching_enabled_ = false
std::vector< Eigen::Vector2i > ui_lines_
std::unordered_set< std::shared_ptr< Label3D > > labels_3d_
struct {
Eigen::Matrix3d matrix
float width = 1.0f
float height = 1.0f
bool is_using = false
} intrinsics_
Detailed Description
Definition at line 746 of file SceneWidget.cpp.
Member Function Documentation
UpdateFarPlane()
void cloudViewer::visualization::gui::SceneWidget::Impl::UpdateFarPlane (const Rect & frame, float verticalFoV) inline
Definition at line 785 of file SceneWidget.cpp.
References cloudViewer::visualization::rendering::Camera::CalcFarPlane(), cloudViewer::visualization::rendering::Camera::CalcNearPlane(), frame, and cloudViewer::visualization::rendering::Camera::Vertical.
UpdateFromIntrinsicMatrix()
void cloudViewer::visualization::gui::SceneWidget::Impl::UpdateFromIntrinsicMatrix (const Rect & frame) inline
Definition at line 767 of file SceneWidget.cpp.
References cloudViewer::visualization::rendering::Camera::CalcFarPlane(), cloudViewer::visualization::rendering::Camera::CalcNearPlane(), and frame.
Member Data Documentation
bounds_
ccBBox cloudViewer::visualization::gui::SceneWidget::Impl::bounds_
Definition at line 749 of file SceneWidget.cpp.
buttons_down_
int cloudViewer::visualization::gui::SceneWidget::Impl::buttons_down_ = 0
Definition at line 753 of file SceneWidget.cpp.
controls_
std::shared_ptr<Interactors> cloudViewer::visualization::gui::SceneWidget::Impl::controls_
Definition at line 750 of file SceneWidget.cpp.
current_render_quality_
SceneWidget::Quality cloudViewer::visualization::gui::SceneWidget::Impl::current_render_quality_ = SceneWidget::Quality::BEST
Definition at line 756 of file SceneWidget.cpp.
frame_rect_changed_
bool cloudViewer::visualization::gui::SceneWidget::Impl::frame_rect_changed_ = false
Definition at line 755 of file SceneWidget.cpp.
height
float cloudViewer::visualization::gui::SceneWidget::Impl::height = 1.0f
Definition at line 763 of file SceneWidget.cpp.
id_
std::string cloudViewer::visualization::gui::SceneWidget::Impl::id_
Definition at line 747 of file SceneWidget.cpp.
struct { ... } cloudViewer::visualization::gui::SceneWidget::Impl::intrinsics_
is_using
bool cloudViewer::visualization::gui::SceneWidget::Impl::is_using = false
Definition at line 764 of file SceneWidget.cpp.
labels_3d_
std::unordered_set<std::shared_ptr<Label3D> > cloudViewer::visualization::gui::SceneWidget::Impl::labels_3d_
Definition at line 759 of file SceneWidget.cpp.
last_fast_time_
double cloudViewer::visualization::gui::SceneWidget::Impl::last_fast_time_ = 0.0
Definition at line 754 of file SceneWidget.cpp.
matrix
Eigen::Matrix3d cloudViewer::visualization::gui::SceneWidget::Impl::matrix
Definition at line 761 of file SceneWidget.cpp.
on_camera_changed_
std::function<void(rendering::Camera*)> cloudViewer::visualization::gui::SceneWidget::Impl::on_camera_changed_
Definition at line 752 of file SceneWidget.cpp.
on_light_dir_changed_
std::function<void(const Eigen::Vector3f&)> cloudViewer::visualization::gui::SceneWidget::Impl::on_light_dir_changed_
Definition at line 751 of file SceneWidget.cpp.
scene_
std::shared_ptr<rendering::CloudViewerScene> cloudViewer::visualization::gui::SceneWidget::Impl::scene_
Definition at line 748 of file SceneWidget.cpp.
scene_caching_enabled_
bool cloudViewer::visualization::gui::SceneWidget::Impl::scene_caching_enabled_ = false
Definition at line 757 of file SceneWidget.cpp.
ui_lines_
std::vector<Eigen::Vector2i> cloudViewer::visualization::gui::SceneWidget::Impl::ui_lines_
Definition at line 758 of file SceneWidget.cpp.
width
float cloudViewer::visualization::gui::SceneWidget::Impl::width = 1.0f
Definition at line 762 of file SceneWidget.cpp.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/SceneWidget.cpp