ACloudViewer: LasScalarField::Range Struct Reference
LasScalarField::Range Struct Reference
#include <LasScalarField.h>
Public Member Functions
template<class T >
constexpr Range (T minValue, T maxValue)
Static Public Member Functions
template<class T >
static constexpr Range ForType ()
Shortcut to create a Range from a native type like uint16_t.
static Range ForBitCount (uint8_t numBits)
Public Attributes
ScalarType min = 0
ScalarType max = 0
Detailed Description
Represents an inclusive range of value from a minimum to a maximum.
This is used to be able to detect and inform users from possible data loss.
Definition at line 70 of file LasScalarField.h.
Constructor & Destructor Documentation
Range()
template<class T > constexpr LasScalarField::Range::Range (T minValue, T maxValue) inline constexpr
Creates a new Range given the min and max value.
These values are converted to ScalarType
Definition at line 76 of file LasScalarField.h.
Referenced by ForBitCount(), and ForType().
Member Function Documentation
ForBitCount()
static Range LasScalarField::Range::ForBitCount (uint8_t numBits) inline static
Definition at line 89 of file LasScalarField.h.
References Range().
Referenced by LasScalarField::ValueRange().
ForType()
template<class T > static constexpr Range LasScalarField::Range::ForType () inline static constexpr
Shortcut to create a Range from a native type like uint16_t.
Definition at line 84 of file LasScalarField.h.
References max(), min(), and Range().
Member Data Documentation
max
ScalarType LasScalarField::Range::max = 0
Definition at line 95 of file LasScalarField.h.
Referenced by LasSaveDialog::handleComboBoxChange(), and LasDetails::SelectBestVersion().
min
ScalarType LasScalarField::Range::min = 0
Definition at line 94 of file LasScalarField.h.
Referenced by LasSaveDialog::handleComboBoxChange().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/plugins/core/IO/qLASIO/include/LasScalarField.h