ACloudViewer: CP::CutPursuit_KL< T > Struct Template Reference
CP::CutPursuit_KL< T > Struct Template Reference
#include <CutPursuit_KL.h>
Public Member Functions
std::pair< T, T > compute_energy () override
size_t split () override
void init_labels (std::vector< bool > &binary_label)
void compute_centers (VectorOfCentroids< T > &centers, const std::vector< bool > &binary_label)
void set_capacities (const VectorOfCentroids< T > &centers)
std::pair< std::vector< T >, T > compute_value (const uint32_t &i_com) override
std::pair< std::vector< T >, T > compute_merge_gain (const VertexDescriptor< T > &comp1, const VertexDescriptor< T > &comp2) override
Public Member Functions inherited from CP::CutPursuit< T >
CutPursuit (uint32_t nbVertex=1)
std::pair< std::vector< T >, std::vector< T > > run ()
void initialize ()
void compute_reduced_value ()
size_t activate_edges (bool allows_saturation=true)
void reduce ()
void compute_connected_components ()
std::vector< VertexDescriptor< T > > connected_comp_from_root (const VertexDescriptor< T > &root, const size_t &size_comp, std::vector< bool > &vertices_seen, std::vector< bool > &edges_seen)
void compute_reduced_graph ()
uint32_t merge (bool is_cutoff)
void cutoff ()
void saturateComponent (const uint32_t &ind_com)
Additional Inherited Members
Public Attributes inherited from CP::CutPursuit< T >
Graph< T > main_graph
Graph< T > reduced_graph
std::vector< std::vector< VertexDescriptor< T > > > components
std::vector< VertexDescriptor< T > > root_vertex
std::vector< bool > saturated_components
std::vector< std::vector< EdgeDescriptor > > borders
VertexDescriptor< T > source
VertexDescriptor< T > sink
uint32_t dim
uint32_t nVertex
uint32_t nEdge
CP::VertexIterator< T > lastIterator
CPparameter< T > parameter
Detailed Description
template<typename T>
struct CP::CutPursuit_KL< T >
Definition at line 14 of file CutPursuit_KL.h.
Member Function Documentation
compute_centers()
template<typename T > void CP::CutPursuit_KL< T >::compute_centers (VectorOfCentroids< T > & centers, const std::vector< bool > & binary_label) inline
Definition at line 371 of file CutPursuit_KL.h.
References VectorOfCentroids< T >::centroids, CP::CutPursuit< T >::components, CP::CutPursuit< T >::dim, CP::CutPursuit< T >::main_graph, CP::CutPursuit< T >::saturateComponent(), CP::CutPursuit< T >::saturated_components, and vertex_index.
Referenced by CP::CutPursuit_KL< T >::split().
compute_energy()
template<typename T > std::pair<T, T> CP::CutPursuit_KL< T >::compute_energy () inline override virtual
Reimplemented from CP::CutPursuit< T >.
Definition at line 15 of file CutPursuit_KL.h.
References CP::CutPursuit< T >::dim, CP::CutPursuit< T >::lastIterator, CP::CutPursuit< T >::main_graph, and CP::CutPursuit< T >::parameter.
compute_merge_gain()
template<typename T > std::pair<std::vector<T>, T> CP::CutPursuit_KL< T >::compute_merge_gain (const VertexDescriptor< T > & comp1, const VertexDescriptor< T > & comp2) inline override virtual
Reimplemented from CP::CutPursuit< T >.
Definition at line 583 of file CutPursuit_KL.h.
References CP::CutPursuit< T >::dim, CP::CutPursuit< T >::parameter, and CP::CutPursuit< T >::reduced_graph.
compute_value()
template<typename T > std::pair<std::vector<T>, T> CP::CutPursuit_KL< T >::compute_value (const uint32_t & i_com) inline override virtual
Reimplemented from CP::CutPursuit< T >.
Definition at line 545 of file CutPursuit_KL.h.
References CP::CutPursuit< T >::components, CP::CutPursuit< T >::dim, and CP::CutPursuit< T >::main_graph.
init_labels()
template<typename T > void CP::CutPursuit_KL< T >::init_labels (std::vector< bool > & binary_label) inline
Definition at line 125 of file CutPursuit_KL.h.
References CP::CutPursuit< T >::components, CP::CutPursuit< T >::dim, QtCompat::endl(), CP::CutPursuit< T >::main_graph, CP::CutPursuit< T >::parameter, flann::random_sample(), CP::CutPursuit< T >::saturated_components, and vertex_index.
Referenced by CP::CutPursuit_KL< T >::split().
set_capacities()
template<typename T > void CP::CutPursuit_KL< T >::set_capacities (const VectorOfCentroids< T > & centers) inline
Definition at line 455 of file CutPursuit_KL.h.
References VectorOfCentroids< T >::centroids, CP::CutPursuit< T >::components, CP::CutPursuit< T >::dim, CP::CutPursuit< T >::main_graph, CP::CutPursuit< T >::parameter, CP::CutPursuit< T >::saturated_components, CP::CutPursuit< T >::sink, and CP::CutPursuit< T >::source.
Referenced by CP::CutPursuit_KL< T >::split().
split()
template<typename T > size_t CP::CutPursuit_KL< T >::split () inline override virtual
Reimplemented from CP::CutPursuit< T >.
Definition at line 61 of file CutPursuit_KL.h.
References CP::CutPursuit< T >::activate_edges(), CP::CutPursuit< T >::components, CP::CutPursuit_KL< T >::compute_centers(), CP::CutPursuit< T >::dim, CP::CutPursuit_KL< T >::init_labels(), CP::CutPursuit< T >::main_graph, CP::CutPursuit< T >::nVertex, CP::CutPursuit< T >::parameter, CP::CutPursuit< T >::saturated_components, CP::CutPursuit_KL< T >::set_capacities(), CP::CutPursuit< T >::sink, CP::CutPursuit< T >::source, TimeStack::tic(), and vertex_index.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qTreeIso/include/CutPursuit_KL.h