ACloudViewer: CommandExtractCCs Struct Reference
CommandExtractCCs Struct Reference
#include <ecvCommandLineCommands.h>
Public Member Functions
CommandExtractCCs ()
bool process (ccCommandLineInterface &cmd) override
Main process.
Public Member Functions inherited from ccCommandLineInterface::Command
Command (const QString &name, const QString &keyword)
Default constructor.
virtual ~Command ()=default
Additional Inherited Members
Public Types inherited from ccCommandLineInterface::Command
using Shared = QSharedPointer< Command >
Shared type.
Public Attributes inherited from ccCommandLineInterface::Command
QString m_name
Command name.
QString m_keyword
Command keyword.
Detailed Description
Definition at line 82 of file ecvCommandLineCommands.h.
Constructor & Destructor Documentation
CommandExtractCCs()
CommandExtractCCs::CommandExtractCCs ()
Definition at line 1297 of file ecvCommandLineCommands.cpp.
Member Function Documentation
process()
bool CommandExtractCCs::process (ccCommandLineInterface & cmd) override virtual
Main process.
Implements ccCommandLineInterface::Command.
Definition at line 1301 of file ecvCommandLineCommands.cpp.
References ccPointCloud::addScalarField(), ccCommandLineInterface::arguments(), ccCommandLineInterface::autoSaveMode(), CC_CONNECTED_COMPONENTS_DEFAULT_LABEL_NAME, cloudViewer::ReferenceCloud::clear(), ccCommandLineInterface::clouds(), COMMAND_EXTRACT_CC, COMMAND_OPEN, cloudViewer::ScalarField::computeMinAndMax(), ccPointCloud::deleteScalarField(), ccCommandLineInterface::error(), ccCommandLineInterface::exportEntity(), cloudViewer::AutoSegmentationTools::extractConnectedComponents(), cloudViewer::PointCloudTpl< T >::getCurrentInScalarField(), ccShiftedObject::getGlobalScale(), ccShiftedObject::getGlobalShift(), ccObject::getName(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), cloudViewer::AutoSegmentationTools::labelConnectedComponents(), cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, octreeLevel, ccPointCloud::partialClone(), cloudViewer::t::geometry::path, ccCommandLineInterface::print(), cloudViewer::PointCloudTpl< T >::setCurrentScalarField(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccObject::setName(), ccCommandLineInterface::silentMode(), cloudViewer::ReferenceCloud::size(), ccCommandLineInterface::warning(), and ccCommandLineInterface::widgetParent().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/app/ecvCommandLineCommands.h
/root/ACloudViewer/app/ecvCommandLineCommands.cpp