ACloudViewer: e57::BlobSectionHeader Struct Reference
e57::BlobSectionHeader Struct Reference
#include <SectionHeaders.h>
Public Member Functions
void dump (int indent=0, std::ostream &os=std::cout)
Public Attributes
const uint8_t sectionId = BLOB_SECTION
uint8_t reserved1 [7] = {}
uint64_t sectionLogicalLength = 0
Detailed Description
Definition at line 39 of file SectionHeaders.h.
Member Function Documentation
dump()
void e57::BlobSectionHeader::dump (int indent = 0, std::ostream & os = std::cout)
Definition at line 33 of file SectionHeaders.cpp.
References QtCompat::endl(), sectionId, sectionLogicalLength, and e57::space().
Referenced by e57::BlobNodeImpl::BlobNodeImpl().
Member Data Documentation
reserved1
uint8_t e57::BlobSectionHeader::reserved1[7] = {}
Definition at line 43 of file SectionHeaders.h.
sectionId
const uint8_t e57::BlobSectionHeader::sectionId = BLOB_SECTION
Definition at line 41 of file SectionHeaders.h.
Referenced by dump().
sectionLogicalLength
uint64_t e57::BlobSectionHeader::sectionLogicalLength = 0
Definition at line 44 of file SectionHeaders.h.
Referenced by e57::BlobNodeImpl::BlobNodeImpl(), and dump().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qE57IO/extern/libE57Format/src/SectionHeaders.h
/root/ACloudViewer/plugins/core/IO/qE57IO/extern/libE57Format/src/SectionHeaders.cpp