ACloudViewer: Runtime::RegisteredPlugin Struct Reference
Runtime::RegisteredPlugin Struct Reference
#include <Runtime.h>
Classes
struct Action
Static Public Member Functions
static RegisteredPlugin InstanciatePlugin (pybind11::object class_type, const QString &name) noexcept(false)
Instanciate a plugin with a known name.
static RegisteredPlugin InstanciatePlugin (pybind11::object class_type) noexcept(false)
Public Attributes
QString name
pybind11::object instance
std::vector< Action > actions
pybind11::object mainIcon
Detailed Description
Definition at line 21 of file Runtime.h.
Member Function Documentation
InstanciatePlugin() [1/2]
static RegisteredPlugin Runtime::RegisteredPlugin::InstanciatePlugin (pybind11::object class_type) inline static noexcept
Instanciate a plugin with an unknown name. In this case the name will be infered from the python class name.
Definition at line 60 of file Runtime.h.
References InstanciatePlugin(), and name.
InstanciatePlugin() [2/2]
static RegisteredPlugin Runtime::RegisteredPlugin::InstanciatePlugin (pybind11::object class_type, const QString & name) inline static noexcept
Instanciate a plugin with a known name.
Definition at line 40 of file Runtime.h.
References actions, instance, mainIcon, and name.
Referenced by InstanciatePlugin(), PythonPluginManager::loadPluginsFrom(), and PythonPluginManager::loadPluginsFromEntryPoints().
Member Data Documentation
actions
std::vector<Action> Runtime::RegisteredPlugin::actions
Definition at line 68 of file Runtime.h.
Referenced by PluginListModel::data(), PluginListModel::handleDoubleClick(), InstanciatePlugin(), and PluginListModel::rowCount().
instance
pybind11::object Runtime::RegisteredPlugin::instance
Definition at line 67 of file Runtime.h.
Referenced by InstanciatePlugin().
mainIcon
pybind11::object Runtime::RegisteredPlugin::mainIcon
Definition at line 69 of file Runtime.h.
Referenced by InstanciatePlugin().
name
QString Runtime::RegisteredPlugin::name
Definition at line 66 of file Runtime.h.
Referenced by InstanciatePlugin().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/Runtime/Runtime.h