ACloudViewer: colmap::mvs::Model Struct Reference
colmap::mvs::Model Struct Reference
#include <model.h>
Classes
struct Point
Public Member Functions
void Read (const std::string &path, const std::string &format)
void ReadFromCOLMAP (const std::string &path, const std::string &sparse_path="sparse", const std::string &images_path="images")
void ReadFromPMVS (const std::string &path)
int GetImageIdx (const std::string &name) const
std::string GetImageName (const int image_idx) const
std::vector< std::vector< int > > GetMaxOverlappingImages (const size_t num_images, const double min_triangulation_angle) const
const std::vector< std::vector< int > > & GetMaxOverlappingImagesFromPMVS () const
std::vector< std::pair< float, float > > ComputeDepthRanges () const
std::vector< std::map< int, int > > ComputeSharedPoints () const
std::vector< std::map< int, float > > ComputeTriangulationAngles (const float percentile=50) const
Public Attributes
std::vector< Image > images
std::vector< Point > points
Detailed Description
Definition at line 26 of file model.h.
Member Function Documentation
ComputeDepthRanges()
std::vector< std::pair< float, float > > colmap::mvs::Model::ComputeDepthRanges () const
Definition at line 196 of file model.cc.
References image, images, points, and X.
ComputeSharedPoints()
std::vector< std::map< int, int > > colmap::mvs::Model::ComputeSharedPoints () const
Definition at line 238 of file model.cc.
References images, and points.
Referenced by GetMaxOverlappingImages().
ComputeTriangulationAngles()
std::vector< std::map< int, float > > colmap::mvs::Model::ComputeTriangulationAngles (const float percentile = 50) const
Definition at line 255 of file model.cc.
References colmap::CalculateTriangulationAngle(), colmap::mvs::ComputeProjectionCenter(), image, images, colmap::Percentile(), and points.
Referenced by GetMaxOverlappingImages().
GetImageIdx()
int colmap::mvs::Model::GetImageIdx (const std::string & name) const
Definition at line 127 of file model.cc.
References name.
Referenced by colmap::mvs::Workspace::Load().
GetImageName()
std::string colmap::mvs::Model::GetImageName (const int image_idx) const
Definition at line 133 of file model.cc.
Referenced by colmap::mvs::Workspace::GetFileName(), and colmap::mvs::ImportPMVSWorkspace().
GetMaxOverlappingImages()
std::vector< std::vector< int > > colmap::mvs::Model::GetMaxOverlappingImages (const size_t num_images, const double min_triangulation_angle) const
Definition at line 139 of file model.cc.
References ComputeSharedPoints(), ComputeTriangulationAngles(), colmap::DegToRad(), image, and images.
GetMaxOverlappingImagesFromPMVS()
const std::vector< std::vector< int > > & colmap::mvs::Model::GetMaxOverlappingImagesFromPMVS () const
Definition at line 191 of file model.cc.
Referenced by colmap::mvs::ImportPMVSWorkspace().
Read()
void colmap::mvs::Model::Read (const std::string & path, const std::string & format)
Definition at line 44 of file model.cc.
References format, cloudViewer::t::geometry::path, ReadFromCOLMAP(), ReadFromPMVS(), and colmap::StringToLower().
ReadFromCOLMAP()
void colmap::mvs::Model::ReadFromCOLMAP (const std::string & path, const std::string & sparse_path = "sparse", const std::string & images_path = "images")
Definition at line 56 of file model.cc.
References colmap::Reconstruction::Camera(), colmap::Reconstruction::DeleteAllPoints2DAndPoints3D(), image, colmap::Reconstruction::Image(), images, colmap::JoinPaths(), colmap::Reconstruction::NumPoints3D(), colmap::Reconstruction::NumRegImages(), cloudViewer::t::geometry::path, points, colmap::Reconstruction::Points3D(), colmap::QuaternionToRotationMatrix(), colmap::Reconstruction::Read(), colmap::Reconstruction::RegImageIds(), colmap::Reconstruction::TearDown(), colmap::mvs::Model::Point::track, colmap::mvs::Model::Point::x, colmap::mvs::Model::Point::y, and colmap::mvs::Model::Point::z.
Referenced by Read().
ReadFromPMVS()
void colmap::mvs::Model::ReadFromPMVS (const std::string & path)
Definition at line 117 of file model.cc.
References cloudViewer::t::geometry::path.
Referenced by Read().
Member Data Documentation
images
std::vector<Image> colmap::mvs::Model::images
Definition at line 72 of file model.h.
Referenced by ComputeDepthRanges(), ComputeSharedPoints(), ComputeTriangulationAngles(), colmap::mvs::CachedWorkspace::GetBitmap(), colmap::mvs::Workspace::GetBitmapPath(), colmap::mvs::CachedWorkspace::GetDepthMap(), GetMaxOverlappingImages(), colmap::mvs::CachedWorkspace::GetNormalMap(), colmap::mvs::Workspace::Load(), and ReadFromCOLMAP().
points
std::vector<Point> colmap::mvs::Model::points
Definition at line 73 of file model.h.
Referenced by ComputeDepthRanges(), ComputeSharedPoints(), ComputeTriangulationAngles(), and ReadFromCOLMAP().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/mvs/model.h
/root/ACloudViewer/libs/Reconstruction/src/mvs/model.cc