ACloudViewer: colmap::MEstimatorSupportMeasurer::Support Struct Reference
colmap::MEstimatorSupportMeasurer::Support Struct Reference
#include <support_measurement.h>
Public Attributes
size_t num_inliers = 0
double score = std::numeric_limits<double>::max()
Detailed Description
Definition at line 39 of file support_measurement.h.
Member Data Documentation
num_inliers
size_t colmap::MEstimatorSupportMeasurer::Support::num_inliers = 0
Definition at line 41 of file support_measurement.h.
Referenced by BOOST_AUTO_TEST_CASE(), and colmap::MEstimatorSupportMeasurer::Evaluate().
score
double colmap::MEstimatorSupportMeasurer::Support::score = std::numeric_limits<double>::max()
Definition at line 44 of file support_measurement.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::MEstimatorSupportMeasurer::Compare(), and colmap::MEstimatorSupportMeasurer::Evaluate().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/optim/support_measurement.h