ACloudViewer: cloudViewer::ml::op_util::DimXMinus Struct Reference
cloudViewer::ml::op_util::DimXMinus Struct Reference
#include <ShapeChecking.h>
Static Public Member Functions
static bool constant ()
static int64_t apply (int64_t a, int64_t b)
template<class T1 , class T2 >
static bool backprop (int64_t ans, T1 a, T2 b)
static std::string ToString ()
Detailed Description
Definition at line 140 of file ShapeChecking.h.
Member Function Documentation
apply()
static int64_t cloudViewer::ml::op_util::DimXMinus::apply (int64_t a, int64_t b) inline static
Definition at line 142 of file ShapeChecking.h.
backprop()
template<class T1 , class T2 > static bool cloudViewer::ml::op_util::DimXMinus::backprop (int64_t ans, T1 a, T2 b) inline static
Definition at line 145 of file ShapeChecking.h.
References cloudViewer::ml::op_util::GetString(), and ToString().
constant()
static bool cloudViewer::ml::op_util::DimXMinus::constant () inline static
Definition at line 141 of file ShapeChecking.h.
ToString()
static std::string cloudViewer::ml::op_util::DimXMinus::ToString () inline static
Definition at line 158 of file ShapeChecking.h.
Referenced by backprop().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/ml/ShapeChecking.h