ACloudViewer: masc::CorePoints Struct Reference
masc::CorePoints Struct Reference
Core points descriptor.
#include <CorePoints.h>
Public Types
enum SubSamplingMethod { NONE , RANDOM , SPATIAL }
Public Member Functions
unsigned size () const
Return the size.
unsigned originIndex (unsigned i) const
Return the point index.
bool prepare (cloudViewer::GenericProgressCallback *progressCb=nullptr)
Prepares the selection (must be called once)
Public Attributes
ccPointCloud * origin = nullptr
Origin cloud.
ccPointCloud * cloud = nullptr
Core points cloud.
QString role
Core points 'role'.
QSharedPointer< cloudViewer::ReferenceCloud > selection
SubSamplingMethod selectionMethod = NONE
double selectionParam = std::numeric_limits<double>::quiet_NaN()
Detailed Description
Core points descriptor.
Definition at line 39 of file CorePoints.h.
Member Enumeration Documentation
SubSamplingMethod
enum masc::CorePoints::SubSamplingMethod
Enumerator
NONE
RANDOM
SPATIAL
Definition at line 58 of file CorePoints.h.
Member Function Documentation
originIndex()
unsigned masc::CorePoints::originIndex (unsigned i) const inline
Return the point index.
Definition at line 52 of file CorePoints.h.
References selection.
prepare()
bool CorePoints::prepare (cloudViewer::GenericProgressCallback * progressCb = nullptr)
Prepares the selection (must be called once)
Definition at line 21 of file CorePoints.cpp.
References cloud, ccGenericPointCloud::computeOctree(), cloudViewer::CloudSamplingTools::SFModulationParams::enabled, ccGenericPointCloud::getOctree(), NONE, origin, ccPointCloud::partialClone(), RANDOM, cloudViewer::CloudSamplingTools::resampleCloudSpatially(), selection, selectionMethod, selectionParam, cloudViewer::PointCloudTpl< T >::size(), SPATIAL, cloudViewer::CloudSamplingTools::subsampleCloudRandomly(), and CVLog::Warning().
size()
unsigned masc::CorePoints::size (void) const inline
Return the size.
Definition at line 50 of file CorePoints.h.
References cloud, and cloudViewer::PointCloudTpl< T >::size().
Member Data Documentation
cloud
ccPointCloud* masc::CorePoints::cloud = nullptr
Core points cloud.
Definition at line 44 of file CorePoints.h.
Referenced by q3DMASCPlugin::doTrainAction(), prepare(), and size().
origin
ccPointCloud* masc::CorePoints::origin = nullptr
Origin cloud.
Definition at line 41 of file CorePoints.h.
Referenced by q3DMASCPlugin::doTrainAction(), and prepare().
role
QString masc::CorePoints::role
Core points 'role'.
Definition at line 47 of file CorePoints.h.
Referenced by q3DMASCPlugin::doTrainAction().
selection
QSharedPointer<cloudViewer::ReferenceCloud> masc::CorePoints::selection
Definition at line 57 of file CorePoints.h.
Referenced by originIndex(), and prepare().
selectionMethod
SubSamplingMethod masc::CorePoints::selectionMethod = NONE
Definition at line 59 of file CorePoints.h.
Referenced by prepare().
selectionParam
double masc::CorePoints::selectionParam = std::numeric_limits<double>::quiet_NaN()
Definition at line 60 of file CorePoints.h.
Referenced by prepare().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/plugins/core/Standard/q3DMASC/CorePoints.h
/root/ACloudViewer/plugins/core/Standard/q3DMASC/CorePoints.cpp