ACloudViewer: poisson::FEMTreeProfiler< Dim, Real > Struct Template Reference
poisson::FEMTreeProfiler< Dim, Real > Struct Template Reference
Public Member Functions
FEMTreeProfiler (FEMTree< Dim, Real > &t)
void start (void)
void dumpOutput (const char *header) const
Public Attributes
FEMTree< Dim, Real > & tree
double t
Detailed Description
template<unsigned int Dim, class Real>
struct poisson::FEMTreeProfiler< Dim, Real >
Definition at line 172 of file SurfaceReconstructionPoisson.cpp.
Constructor & Destructor Documentation
FEMTreeProfiler()
template<unsigned int Dim, class Real > poisson::FEMTreeProfiler< Dim, Real >::FEMTreeProfiler (FEMTree< Dim, Real > & t) inline
Definition at line 176 of file SurfaceReconstructionPoisson.cpp.
Member Function Documentation
dumpOutput()
template<unsigned int Dim, class Real > void poisson::FEMTreeProfiler< Dim, Real >::dumpOutput (const char * header) const inline
Definition at line 180 of file SurfaceReconstructionPoisson.cpp.
References LogDebug.
Referenced by poisson::Execute().
start()
template<unsigned int Dim, class Real > void poisson::FEMTreeProfiler< Dim, Real >::start (void) inline
Definition at line 177 of file SurfaceReconstructionPoisson.cpp.
Referenced by poisson::Execute(), and poisson::ExtractMesh().
Member Data Documentation
t
template<unsigned int Dim, class Real > double poisson::FEMTreeProfiler< Dim, Real >::t
Definition at line 174 of file SurfaceReconstructionPoisson.cpp.
tree
template<unsigned int Dim, class Real > FEMTree<Dim, Real>& poisson::FEMTreeProfiler< Dim, Real >::tree
Definition at line 173 of file SurfaceReconstructionPoisson.cpp.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/CV_db/src/SurfaceReconstructionPoisson.cpp