ACloudViewer: PlyColorVertex< Real >::_PlyColorVertex Struct Reference
PlyColorVertex< Real >::_PlyColorVertex Struct Reference
#include <Ply.h>
Public Member Functions
_PlyColorVertex (void)
_PlyColorVertex (Point3D< Real > p, Point3D< Real > c)
_PlyColorVertex (PlyColorVertex< Real > p)
operator PlyColorVertex< Real > ()
_PlyColorVertex operator+ (_PlyColorVertex p) const
_PlyColorVertex operator- (_PlyColorVertex p) const
template<class _Real >
_PlyColorVertex operator* (_Real s) const
template<class _Real >
_PlyColorVertex operator/ (_Real s) const
_PlyColorVertex & operator+= (_PlyColorVertex p)
_PlyColorVertex & operator-= (_PlyColorVertex p)
template<class _Real >
_PlyColorVertex & operator*= (_Real s)
template<class _Real >
_PlyColorVertex & operator/= (_Real s)
Public Attributes
Point3D< Real > point
Point3D< Real > color
Detailed Description
template<class Real>
struct PlyColorVertex< Real >::_PlyColorVertex
Definition at line 374 of file Ply.h.
Constructor & Destructor Documentation
_PlyColorVertex() [1/3]
template<class Real > PlyColorVertex< Real >::_PlyColorVertex::_PlyColorVertex (void) inline
Definition at line 377 of file Ply.h.
Referenced by PlyColorVertex< Real >::_PlyColorVertex::operator*(), PlyColorVertex< Real >::_PlyColorVertex::operator+(), PlyColorVertex< Real >::_PlyColorVertex::operator-(), and PlyColorVertex< Real >::_PlyColorVertex::operator/().
_PlyColorVertex() [2/3]
template<class Real > PlyColorVertex< Real >::_PlyColorVertex::_PlyColorVertex (Point3D< Real > p, Point3D< Real > c) inline
Definition at line 378 of file Ply.h.
_PlyColorVertex() [3/3]
template<class Real > PlyColorVertex< Real >::_PlyColorVertex::_PlyColorVertex (PlyColorVertex< Real > p) inline
Definition at line 379 of file Ply.h.
References PlyColorVertex< Real >::_PlyColorVertex::color, PlyColorVertex< Real >::color, and PlyColorVertex< Real >::point.
Member Function Documentation
operator PlyColorVertex< Real >()
template<class Real > PlyColorVertex< Real >::_PlyColorVertex::operator PlyColorVertex< Real > () inline
Definition at line 380 of file Ply.h.
References PlyColorVertex< Real >::_PlyColorVertex::color, PlyColorVertex< Real >::color, PlyColorVertex< Real >::_PlyColorVertex::point, and PlyColorVertex< Real >::point.
operator*()
template<class Real > template<class _Real > _PlyColorVertex PlyColorVertex< Real >::_PlyColorVertex::operator* (_Real s) const inline
Definition at line 390 of file Ply.h.
References PlyColorVertex< Real >::_PlyColorVertex::_PlyColorVertex(), and PlyColorVertex< Real >::_PlyColorVertex::color.
operator*=()
template<class Real > template<class _Real > _PlyColorVertex& PlyColorVertex< Real >::_PlyColorVertex::operator*= (_Real s) inline
Definition at line 394 of file Ply.h.
References PlyColorVertex< Real >::_PlyColorVertex::color.
operator+()
template<class Real > _PlyColorVertex PlyColorVertex< Real >::_PlyColorVertex::operator+ (_PlyColorVertex p) const inline
Definition at line 388 of file Ply.h.
References PlyColorVertex< Real >::_PlyColorVertex::_PlyColorVertex(), PlyColorVertex< Real >::_PlyColorVertex::color, and PlyColorVertex< Real >::_PlyColorVertex::point.
operator+=()
template<class Real > _PlyColorVertex& PlyColorVertex< Real >::_PlyColorVertex::operator+= (_PlyColorVertex p) inline
Definition at line 392 of file Ply.h.
References PlyColorVertex< Real >::_PlyColorVertex::color, and PlyColorVertex< Real >::_PlyColorVertex::point.
operator-()
template<class Real > _PlyColorVertex PlyColorVertex< Real >::_PlyColorVertex::operator- (_PlyColorVertex p) const inline
Definition at line 389 of file Ply.h.
References PlyColorVertex< Real >::_PlyColorVertex::_PlyColorVertex(), PlyColorVertex< Real >::_PlyColorVertex::color, and PlyColorVertex< Real >::_PlyColorVertex::point.
operator-=()
template<class Real > _PlyColorVertex& PlyColorVertex< Real >::_PlyColorVertex::operator-= (_PlyColorVertex p) inline
Definition at line 393 of file Ply.h.
References PlyColorVertex< Real >::_PlyColorVertex::color, and PlyColorVertex< Real >::_PlyColorVertex::point.
operator/()
template<class Real > template<class _Real > _PlyColorVertex PlyColorVertex< Real >::_PlyColorVertex::operator/ (_Real s) const inline
Definition at line 391 of file Ply.h.
References PlyColorVertex< Real >::_PlyColorVertex::_PlyColorVertex(), and PlyColorVertex< Real >::_PlyColorVertex::color.
operator/=()
template<class Real > template<class _Real > _PlyColorVertex& PlyColorVertex< Real >::_PlyColorVertex::operator/= (_Real s) inline
Definition at line 395 of file Ply.h.
References PlyColorVertex< Real >::_PlyColorVertex::color.
Member Data Documentation
color
template<class Real > Point3D< Real > PlyColorVertex< Real >::_PlyColorVertex::color
Definition at line 376 of file Ply.h.
Referenced by PlyColorVertex< Real >::_PlyColorVertex::_PlyColorVertex(), PlyColorVertex< Real >::_PlyColorVertex::operator PlyColorVertex< Real >(), PlyColorVertex< Real >::_PlyColorVertex::operator*(), PlyColorVertex< Real >::_PlyColorVertex::operator*=(), PlyColorVertex< Real >::_PlyColorVertex::operator+(), PlyColorVertex< Real >::_PlyColorVertex::operator+=(), PlyColorVertex< Real >::_PlyColorVertex::operator-(), PlyColorVertex< Real >::_PlyColorVertex::operator-=(), PlyColorVertex< Real >::_PlyColorVertex::operator/(), and PlyColorVertex< Real >::_PlyColorVertex::operator/=().
point
template<class Real > Point3D< Real > PlyColorVertex< Real >::_PlyColorVertex::point
Definition at line 376 of file Ply.h.
Referenced by PlyColorVertex< Real >::_PlyColorVertex::operator PlyColorVertex< Real >(), PlyColorVertex< Real >::_PlyColorVertex::operator+(), PlyColorVertex< Real >::_PlyColorVertex::operator+=(), PlyColorVertex< Real >::_PlyColorVertex::operator-(), and PlyColorVertex< Real >::_PlyColorVertex::operator-=().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/Ply.h