ACloudViewer: cloudViewer::visualization::gui::Application::Impl Struct Reference
cloudViewer::visualization::gui::Application::Impl Struct Reference
Classes
struct Posted
Public Member Functions
void InitWindowSystem ()
void PrepareForRunning ()
void CleanupAfterRunning ()
Public Attributes
bool is_initialized_ = false
std::shared_ptr< WindowSystem > window_system_
std::vector< FontDescription > fonts_
Theme theme_
double last_time_ = 0.0
bool is_ws_initialized_ = false
bool is_running_ = false
bool should_quit_ = false
std::shared_ptr< Menu > menubar_
std::unordered_set< std::shared_ptr< Window > > windows_
std::unordered_set< std::shared_ptr< Window > > windows_to_be_destroyed_
std::list< Task > running_tasks_
std::mutex posted_lock_
std::vector< Posted > posted_
Detailed Description
Definition at line 111 of file Application.cpp.
Member Function Documentation
CleanupAfterRunning()
void cloudViewer::visualization::gui::Application::Impl::CleanupAfterRunning () inline
Definition at line 159 of file Application.cpp.
References cloudViewer::visualization::rendering::EngineInstance::DestroyInstance(), is_ws_initialized_, and window_system_.
InitWindowSystem()
void cloudViewer::visualization::gui::Application::Impl::InitWindowSystem () inline
Definition at line 137 of file Application.cpp.
References is_ws_initialized_, and window_system_.
Referenced by PrepareForRunning().
PrepareForRunning()
void cloudViewer::visualization::gui::Application::Impl::PrepareForRunning () inline
Definition at line 148 of file Application.cpp.
References InitWindowSystem(), and cloudViewer::visualization::rendering::EngineInstance::SelectBackend().
Member Data Documentation
fonts_
std::vector<FontDescription> cloudViewer::visualization::gui::Application::Impl::fonts_
Definition at line 114 of file Application.cpp.
is_initialized_
bool cloudViewer::visualization::gui::Application::Impl::is_initialized_ = false
Definition at line 112 of file Application.cpp.
is_running_
bool cloudViewer::visualization::gui::Application::Impl::is_running_ = false
Definition at line 118 of file Application.cpp.
is_ws_initialized_
bool cloudViewer::visualization::gui::Application::Impl::is_ws_initialized_ = false
Definition at line 117 of file Application.cpp.
Referenced by CleanupAfterRunning(), and InitWindowSystem().
last_time_
double cloudViewer::visualization::gui::Application::Impl::last_time_ = 0.0
Definition at line 116 of file Application.cpp.
menubar_
std::shared_ptr<Menu> cloudViewer::visualization::gui::Application::Impl::menubar_
Definition at line 121 of file Application.cpp.
posted_
std::vector<Posted> cloudViewer::visualization::gui::Application::Impl::posted_
Definition at line 134 of file Application.cpp.
posted_lock_
std::mutex cloudViewer::visualization::gui::Application::Impl::posted_lock_
Definition at line 133 of file Application.cpp.
running_tasks_
std::list<Task> cloudViewer::visualization::gui::Application::Impl::running_tasks_
Definition at line 125 of file Application.cpp.
should_quit_
bool cloudViewer::visualization::gui::Application::Impl::should_quit_ = false
Definition at line 119 of file Application.cpp.
theme_
Theme cloudViewer::visualization::gui::Application::Impl::theme_
Definition at line 115 of file Application.cpp.
window_system_
std::shared_ptr<WindowSystem> cloudViewer::visualization::gui::Application::Impl::window_system_
Definition at line 113 of file Application.cpp.
Referenced by CleanupAfterRunning(), and InitWindowSystem().
windows_
std::unordered_set<std::shared_ptr<Window> > cloudViewer::visualization::gui::Application::Impl::windows_
Definition at line 122 of file Application.cpp.
windows_to_be_destroyed_
std::unordered_set<std::shared_ptr<Window> > cloudViewer::visualization::gui::Application::Impl::windows_to_be_destroyed_
Definition at line 123 of file Application.cpp.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/Application.cpp