ACloudViewer: CommandStatTest Struct Reference
CommandStatTest Struct Reference
#include <ecvCommandLineCommands.h>
Public Member Functions
CommandStatTest ()
bool process (ccCommandLineInterface &cmd) override
Main process.
Public Member Functions inherited from ccCommandLineInterface::Command
Command (const QString &name, const QString &keyword)
Default constructor.
virtual ~Command ()=default
Additional Inherited Members
Public Types inherited from ccCommandLineInterface::Command
using Shared = QSharedPointer< Command >
Shared type.
Public Attributes inherited from ccCommandLineInterface::Command
QString m_name
Command name.
QString m_keyword
Command keyword.
Detailed Description
Definition at line 288 of file ecvCommandLineCommands.h.
Constructor & Destructor Documentation
CommandStatTest()
CommandStatTest::CommandStatTest ()
Definition at line 3944 of file ecvCommandLineCommands.cpp.
Member Function Documentation
process()
bool CommandStatTest::process (ccCommandLineInterface & cmd) override virtual
Main process.
Implements ccCommandLineInterface::Command.
Definition at line 3948 of file ecvCommandLineCommands.cpp.
References ccPointCloud::addScalarField(), ccCommandLineInterface::arguments(), ccCommandLineInterface::autoSaveMode(), CC_CHI2_DISTANCES_DEFAULT_SF_NAME, ccCommandLineInterface::clouds(), COMMAND_STAT_TEST, ccScalarField::computeMinAndMax(), ccGenericPointCloud::computeOctree(), ccCommandLineInterface::error(), ccCommandLineInterface::exportEntity(), cloudViewer::PointCloudTpl< T >::getCurrentInScalarField(), cloudViewer::PointCloudTpl< T >::getCurrentOutScalarField(), ccObject::getName(), cloudViewer::GenericDistribution::getName(), ccGenericPointCloud::getOctree(), cloudViewer::PointCloudTpl< T >::getScalarFieldIndexByName(), ccCommandLineInterface::print(), ccPointCloud::setCurrentDisplayedScalarField(), cloudViewer::PointCloudTpl< T >::setCurrentInScalarField(), ccScalarField::setMinDisplayed(), cloudViewer::NormalDistribution::setParameters(), cloudViewer::WeibullDistribution::setParameters(), ccScalarField::setSaturationStart(), ccScalarField::setSymmetricalScale(), ccDrawableObject::showSF(), ccCommandLineInterface::silentMode(), size, cloudViewer::StatisticalTestingTools::testCloudWithStatisticalModel(), and ccCommandLineInterface::widgetParent().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/app/ecvCommandLineCommands.h
/root/ACloudViewer/app/ecvCommandLineCommands.cpp