ACloudViewer: flann::anyimpl::base_any_policy Struct Reference
flann::anyimpl::base_any_policy Struct Reference abstract
#include <any.h>
Public Member Functions
virtual void static_delete (void **x)=0
virtual void copy_from_value (void const *src, void **dest)=0
virtual void clone (void *const *src, void **dest)=0
virtual void move (void *const *src, void **dest)=0
virtual void * get_value (void **src)=0
virtual const void * get_value (void *const *src)=0
virtual ::size_t get_size ()=0
virtual const std::type_info & type ()=0
virtual void print (std::ostream &out, void *const *src)=0
Detailed Description
Definition at line 40 of file any.h.
Member Function Documentation
clone()
virtual void flann::anyimpl::base_any_policy::clone (void *const * src, void ** dest) pure virtual
Implemented in flann::anyimpl::big_any_policy< T >, and flann::anyimpl::small_any_policy< T >.
Referenced by flann::any::assign().
copy_from_value()
virtual void flann::anyimpl::base_any_policy::copy_from_value (void const * src, void ** dest) pure virtual
Implemented in flann::anyimpl::big_any_policy< T >, and flann::anyimpl::small_any_policy< T >.
Referenced by flann::any::assign().
get_size()
virtual ::size_t flann::anyimpl::base_any_policy::get_size () pure virtual
Implemented in flann::anyimpl::typed_base_any_policy< T >.
get_value() [1/2]
virtual void* flann::anyimpl::base_any_policy::get_value (void ** src) pure virtual
Implemented in flann::anyimpl::big_any_policy< T >, and flann::anyimpl::small_any_policy< T >.
Referenced by flann::any::cast().
get_value() [2/2]
virtual const void* flann::anyimpl::base_any_policy::get_value (void *const * src) pure virtual
Implemented in flann::anyimpl::big_any_policy< T >, and flann::anyimpl::small_any_policy< T >.
move()
virtual void flann::anyimpl::base_any_policy::move (void *const * src, void ** dest) pure virtual
Implemented in flann::anyimpl::big_any_policy< T >, and flann::anyimpl::small_any_policy< T >.
print()
virtual void flann::anyimpl::base_any_policy::print (std::ostream & out, void *const * src) pure virtual
Implemented in flann::anyimpl::big_any_policy< T >, and flann::anyimpl::small_any_policy< T >.
static_delete()
virtual void flann::anyimpl::base_any_policy::static_delete (void ** x) pure virtual
Implemented in flann::anyimpl::big_any_policy< T >, and flann::anyimpl::small_any_policy< T >.
Referenced by flann::any::reset(), and flann::any::~any().
type()
virtual const std::type_info& flann::anyimpl::base_any_policy::type () pure virtual
Implemented in flann::anyimpl::typed_base_any_policy< T >.
Referenced by flann::any::cast(), flann::any::compatible(), flann::any::empty(), flann::any::has_type(), and flann::any::type().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/util/any.h