ACloudViewer: cloudViewer::visualization::GuiVisualizer::Impl Struct Reference
cloudViewer::visualization::GuiVisualizer::Impl Struct Reference
Classes
struct Settings
Public Member Functions
void InitializeMaterials (rendering::Renderer &renderer, const std::string &resource_path)
void SetMaterialsToDefault ()
bool SetIBL (rendering::Renderer &renderer, const std::string &path)
void SetMouseControls (gui::Window &window, gui::SceneWidget::Controls mode)
void ModifyMaterialForBasicMode (rendering::MaterialRecord &basic_mat)
void SetBasicModeGeometry (bool enable)
void SetBasicMode (bool enable)
void UpdateFromModel (rendering::Renderer &renderer, bool material_changed)
Public Attributes
GuiVisualizer * visualizer_
std::shared_ptr< gui::SceneWidget > scene_wgt_
std::shared_ptr< gui::VGrid > help_keys_
std::shared_ptr< gui::VGrid > help_camera_
std::shared_ptr< io::rpc::ZMQReceiver > receiver_
std::shared_ptr< MessageProcessor > message_processor_
struct cloudViewer::visualization::GuiVisualizer::Impl::Settings settings_
rendering::TriangleMeshModel loaded_model_
rendering::TriangleMeshModel basic_model_
std::shared_ptr< geometry::LineSet > wireframe_model_
std::shared_ptr< geometry::PointCloud > loaded_pcd_
int app_menu_custom_items_index_ = -1
std::shared_ptr< gui::Menu > app_menu_
bool sun_follows_camera_ = false
bool basic_mode_enabled_ = false
bool wireframe_enabled_ = false
Detailed Description
Definition at line 314 of file GuiVisualizer.cpp.
Member Function Documentation
InitializeMaterials()
void cloudViewer::visualization::GuiVisualizer::Impl::InitializeMaterials (rendering::Renderer & renderer, const std::string & resource_path) inline
Definition at line 349 of file GuiVisualizer.cpp.
References cloudViewer::visualization::GuiSettingsModel::GetCurrentMaterials(), cloudViewer::visualization::GuiVisualizer::Impl::Settings::lit_material_, cloudViewer::visualization::GuiVisualizer::Impl::Settings::model_, settings_, cloudViewer::visualization::rendering::MaterialRecord::shader, and cloudViewer::visualization::GuiVisualizer::Impl::Settings::unlit_material_.
ModifyMaterialForBasicMode()
void cloudViewer::visualization::GuiVisualizer::Impl::ModifyMaterialForBasicMode (rendering::MaterialRecord & basic_mat) inline
Definition at line 400 of file GuiVisualizer.cpp.
References cloudViewer::visualization::rendering::MaterialRecord::albedo_img, cloudViewer::visualization::rendering::MaterialRecord::ao_img, cloudViewer::visualization::rendering::MaterialRecord::base_anisotropy, cloudViewer::visualization::rendering::MaterialRecord::base_clearcoat, cloudViewer::visualization::rendering::MaterialRecord::base_color, cloudViewer::visualization::rendering::MaterialRecord::base_metallic, cloudViewer::visualization::rendering::MaterialRecord::base_reflectance, cloudViewer::visualization::rendering::MaterialRecord::base_roughness, cloudViewer::visualization::rendering::MaterialRecord::metallic_img, cloudViewer::visualization::rendering::MaterialRecord::normal_img, cloudViewer::visualization::rendering::MaterialRecord::reflectance_img, cloudViewer::visualization::rendering::MaterialRecord::roughness_img, cloudViewer::visualization::rendering::MaterialRecord::sRGB_color, and cloudViewer::visualization::rendering::MaterialRecord::sRGB_vertex_color.
Referenced by SetBasicModeGeometry().
SetBasicMode()
void cloudViewer::visualization::GuiVisualizer::Impl::SetBasicMode (bool enable) inline
Definition at line 451 of file GuiVisualizer.cpp.
References cloudViewer::visualization::rendering::View::kPCF, scene_wgt_, and SetBasicModeGeometry().
Referenced by UpdateFromModel().
SetBasicModeGeometry()
void cloudViewer::visualization::GuiVisualizer::Impl::SetBasicModeGeometry (bool enable) inline
Definition at line 418 of file GuiVisualizer.cpp.
References basic_model_, cloudViewer::visualization::INSPECT_MODEL_NAME, loaded_model_, cloudViewer::visualization::rendering::TriangleMeshModel::materials_, cloudViewer::visualization::rendering::TriangleMeshModel::meshes_, cloudViewer::visualization::MODEL_NAME, ModifyMaterialForBasicMode(), and scene_wgt_.
Referenced by SetBasicMode().
SetIBL()
bool cloudViewer::visualization::GuiVisualizer::Impl::SetIBL (rendering::Renderer & renderer, const std::string & path) inline
Definition at line 368 of file GuiVisualizer.cpp.
References cloudViewer::visualization::GuiSettingsModel::DEFAULT_IBL, cloudViewer::visualization::gui::Application::GetInstance(), and scene_wgt_.
SetMaterialsToDefault()
void cloudViewer::visualization::GuiVisualizer::Impl::SetMaterialsToDefault () inline
Definition at line 359 of file GuiVisualizer.cpp.
References cloudViewer::visualization::GuiVisualizer::Impl::Settings::model_, cloudViewer::visualization::GuiSettingsModel::SetMaterialsToDefault(), settings_, and cloudViewer::visualization::GuiVisualizer::Impl::Settings::view_.
SetMouseControls()
void cloudViewer::visualization::GuiVisualizer::Impl::SetMouseControls (gui::Window & window, gui::SceneWidget::Controls mode) inline
Definition at line 388 of file GuiVisualizer.cpp.
References scene_wgt_, cloudViewer::visualization::gui::Window::SetFocusWidget(), settings_, cloudViewer::visualization::GuiVisualizer::Impl::Settings::wgt_mouse_arcball, cloudViewer::visualization::GuiVisualizer::Impl::Settings::wgt_mouse_fly, cloudViewer::visualization::GuiVisualizer::Impl::Settings::wgt_mouse_ibl, cloudViewer::visualization::GuiVisualizer::Impl::Settings::wgt_mouse_model, and cloudViewer::visualization::GuiVisualizer::Impl::Settings::wgt_mouse_sun.
UpdateFromModel()
void cloudViewer::visualization::GuiVisualizer::Impl::UpdateFromModel (rendering::Renderer & renderer, bool material_changed) inline
Definition at line 472 of file GuiVisualizer.cpp.
References cloudViewer::visualization::rendering::MaterialRecord::base_color, basic_mode_enabled_, cloudViewer::visualization::rendering::View::Color, cloudViewer::geometry::LineSet::CreateFromTriangleMesh(), cloudViewer::visualization::rendering::View::Depth, cloudViewer::visualization::rendering::MaterialRecord::emissive_color, cloudViewer::visualization::GuiSettingsModel::GetBackgroundColor(), cloudViewer::visualization::GuiSettingsModel::GetBasicMode(), cloudViewer::visualization::GuiSettingsModel::GetCurrentMaterials(), cloudViewer::visualization::GuiSettingsModel::GetLighting(), cloudViewer::visualization::GuiSettingsModel::GetMaterialType(), cloudViewer::visualization::GuiSettingsModel::GetShowAxes(), cloudViewer::visualization::GuiSettingsModel::GetShowGround(), cloudViewer::visualization::GuiSettingsModel::GetShowSkybox(), cloudViewer::visualization::GuiSettingsModel::GetUserWantsEstimateNormals(), cloudViewer::visualization::GuiSettingsModel::GetWireframeMode(), cloudViewer::visualization::rendering::MaterialRecord::line_width, loaded_model_, loaded_pcd_, cloudViewer::visualization::GuiSettingsModel::MATERIAL_FROM_FILE_NAME, cloudViewer::visualization::rendering::TriangleMeshModel::meshes_, cloudViewer::visualization::GuiVisualizer::Impl::Settings::model_, cloudViewer::visualization::MODEL_NAME, cloudViewer::visualization::rendering::View::Normals, scene_wgt_, SetBasicMode(), settings_, cloudViewer::visualization::rendering::MaterialRecord::shader, wireframe_enabled_, wireframe_model_, cloudViewer::visualization::WIREFRAME_NAME, and cloudViewer::visualization::rendering::Scene::XZ.
Member Data Documentation
app_menu_
std::shared_ptr<gui::Menu> cloudViewer::visualization::GuiVisualizer::Impl::app_menu_
Definition at line 343 of file GuiVisualizer.cpp.
app_menu_custom_items_index_
int cloudViewer::visualization::GuiVisualizer::Impl::app_menu_custom_items_index_ = -1
Definition at line 342 of file GuiVisualizer.cpp.
basic_mode_enabled_
bool cloudViewer::visualization::GuiVisualizer::Impl::basic_mode_enabled_ = false
Definition at line 346 of file GuiVisualizer.cpp.
Referenced by UpdateFromModel().
basic_model_
rendering::TriangleMeshModel cloudViewer::visualization::GuiVisualizer::Impl::basic_model_
Definition at line 339 of file GuiVisualizer.cpp.
Referenced by SetBasicModeGeometry().
help_camera_
std::shared_ptr<gui::VGrid> cloudViewer::visualization::GuiVisualizer::Impl::help_camera_
Definition at line 319 of file GuiVisualizer.cpp.
help_keys_
std::shared_ptr<gui::VGrid> cloudViewer::visualization::GuiVisualizer::Impl::help_keys_
Definition at line 318 of file GuiVisualizer.cpp.
loaded_model_
rendering::TriangleMeshModel cloudViewer::visualization::GuiVisualizer::Impl::loaded_model_
Definition at line 338 of file GuiVisualizer.cpp.
Referenced by SetBasicModeGeometry(), and UpdateFromModel().
loaded_pcd_
std::shared_ptr<geometry::PointCloud> cloudViewer::visualization::GuiVisualizer::Impl::loaded_pcd_
Definition at line 341 of file GuiVisualizer.cpp.
Referenced by UpdateFromModel().
message_processor_
std::shared_ptr<MessageProcessor> cloudViewer::visualization::GuiVisualizer::Impl::message_processor_
Definition at line 321 of file GuiVisualizer.cpp.
receiver_
std::shared_ptr<io::rpc::ZMQReceiver> cloudViewer::visualization::GuiVisualizer::Impl::receiver_
Definition at line 320 of file GuiVisualizer.cpp.
scene_wgt_
std::shared_ptr<gui::SceneWidget> cloudViewer::visualization::GuiVisualizer::Impl::scene_wgt_
Definition at line 317 of file GuiVisualizer.cpp.
Referenced by SetBasicMode(), SetBasicModeGeometry(), SetIBL(), SetMouseControls(), and UpdateFromModel().
settings_
struct cloudViewer::visualization::GuiVisualizer::Impl::Settings cloudViewer::visualization::GuiVisualizer::Impl::settings_
Referenced by InitializeMaterials(), SetMaterialsToDefault(), SetMouseControls(), and UpdateFromModel().
sun_follows_camera_
bool cloudViewer::visualization::GuiVisualizer::Impl::sun_follows_camera_ = false
Definition at line 345 of file GuiVisualizer.cpp.
visualizer_
GuiVisualizer* cloudViewer::visualization::GuiVisualizer::Impl::visualizer_
Definition at line 315 of file GuiVisualizer.cpp.
wireframe_enabled_
bool cloudViewer::visualization::GuiVisualizer::Impl::wireframe_enabled_ = false
Definition at line 347 of file GuiVisualizer.cpp.
Referenced by UpdateFromModel().
wireframe_model_
std::shared_ptr<geometry::LineSet> cloudViewer::visualization::GuiVisualizer::Impl::wireframe_model_
Definition at line 340 of file GuiVisualizer.cpp.
Referenced by UpdateFromModel().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/GuiVisualizer.cpp