ACloudViewer: cloudViewer::io::rpc::messages::Status Struct Reference
cloudViewer::io::rpc::messages::Status Struct Reference
#include <Messages.h>
Public Member Functions
Status ()
Status (int code, const std::string &str)
MSGPACK_DEFINE_MAP (code, str)
Static Public Member Functions
static std::string MsgId ()
static Status OK ()
static Status ErrorUnsupportedMsgId ()
static Status ErrorUnpackingFailed ()
static Status ErrorProcessingMessage ()
Public Attributes
int32_t code
return code. 0 means everything is OK.
std::string str
string representation of the code
Detailed Description
struct for defining a "status" message, which will be used for returning error codes or returning code 0 if the call does not return something else.
Definition at line 522 of file Messages.h.
Constructor & Destructor Documentation
Status() [1/2]
cloudViewer::io::rpc::messages::Status::Status () inline
Definition at line 525 of file Messages.h.
Referenced by ErrorProcessingMessage(), ErrorUnpackingFailed(), ErrorUnsupportedMsgId(), and OK().
Status() [2/2]
cloudViewer::io::rpc::messages::Status::Status (int code, const std::string & str) inline
Definition at line 526 of file Messages.h.
Member Function Documentation
ErrorProcessingMessage()
static Status cloudViewer::io::rpc::messages::Status::ErrorProcessingMessage () inline static
Definition at line 534 of file Messages.h.
References Status().
Referenced by cloudViewer::visualization::MessageProcessor::ProcessMessage().
ErrorUnpackingFailed()
static Status cloudViewer::io::rpc::messages::Status::ErrorUnpackingFailed () inline static
Definition at line 531 of file Messages.h.
References Status().
ErrorUnsupportedMsgId()
static Status cloudViewer::io::rpc::messages::Status::ErrorUnsupportedMsgId () inline static
Definition at line 528 of file Messages.h.
References Status().
MsgId()
static std::string cloudViewer::io::rpc::messages::Status::MsgId () inline static
Definition at line 523 of file Messages.h.
Referenced by cloudViewer::io::rpc::UnpackStatusFromReply().
MSGPACK_DEFINE_MAP()
cloudViewer::io::rpc::messages::Status::MSGPACK_DEFINE_MAP (code , str)
OK()
static Status cloudViewer::io::rpc::messages::Status::OK () inline static
Definition at line 527 of file Messages.h.
References Status().
Member Data Documentation
code
int32_t cloudViewer::io::rpc::messages::Status::code
return code. 0 means everything is OK.
Definition at line 539 of file Messages.h.
Referenced by cloudViewer::io::rpc::GetStatusCodeAndStr().
str
std::string cloudViewer::io::rpc::messages::Status::str
string representation of the code
Definition at line 541 of file Messages.h.
Referenced by cloudViewer::io::rpc::GetStatusCodeAndStr().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/io/rpc/Messages.h