ACloudViewer: CommandRANSAC Struct Reference
CommandRANSAC Struct Reference
#include <qRANSAC_SD_Commands.h>
Public Member Functions
CommandRANSAC ()
virtual bool process (ccCommandLineInterface &cmd) override
Main process.
bool makePathIfPossible (ccCommandLineInterface &cmd, const QString &param, QString *outputPath, bool *performOutput)
Public Member Functions inherited from ccCommandLineInterface::Command
Command (const QString &name, const QString &keyword)
Default constructor.
virtual ~Command ()=default
Additional Inherited Members
Public Types inherited from ccCommandLineInterface::Command
using Shared = QSharedPointer< Command >
Shared type.
Public Attributes inherited from ccCommandLineInterface::Command
QString m_name
Command name.
QString m_keyword
Command keyword.
Detailed Description
Definition at line 49 of file qRANSAC_SD_Commands.h.
Constructor & Destructor Documentation
CommandRANSAC()
CommandRANSAC::CommandRANSAC () inline
Definition at line 50 of file qRANSAC_SD_Commands.h.
Member Function Documentation
makePathIfPossible()
bool CommandRANSAC::makePathIfPossible (ccCommandLineInterface & cmd, const QString & param, QString * outputPath, bool * performOutput) inline
Definition at line 452 of file qRANSAC_SD_Commands.h.
References ccCommandLineInterface::arguments(), COMMAND_RANSAC, ccCommandLineInterface::error(), and ccCommandLineInterface::print().
Referenced by process().
process()
virtual bool CommandRANSAC::process (ccCommandLineInterface & cmd) inline override virtual
Main process.
Implements ccCommandLineInterface::Command.
Definition at line 54 of file qRANSAC_SD_Commands.h.
References ccCommandLineInterface::arguments(), ccCommandLineInterface::autoSaveMode(), BITMAP_EPSILON_ABSOLUTE, BITMAP_EPSILON_PERCENTAGE_OF_SCALE, ccCommandLineInterface::clouds(), COMMAND_RANSAC, CV_TYPES::CONE, count, CV_TYPES::CYLINDER, ENABLE_PRIMITIVE, EPSILON_ABSOLUTE, EPSILON_PERCENTAGE_OF_SCALE, ccCommandLineInterface::error(), ccCommandLineInterface::exportEntity(), ccHObject::filterChildren(), ccObject::getName(), makePathIfPossible(), max(), MAX_NORMAL_DEV, CV_TYPES::MESH, ccCommandLineInterface::meshes(), OUT_CLOUD_DIR, OUT_GROUP_DIR, OUT_MESH_DIR, OUT_PAIR_DIR, OUT_RANDOM_COLOR, OUTPUT_GROUPED, OUTPUT_INDIVIDUAL_PAIRED_CLOUD_PRIMITIVE, OUTPUT_INDIVIDUAL_PRIMITIVES, OUTPUT_INDIVIDUAL_SUBCLOUDS, params, CV_TYPES::PLANE, PRIM_CONE, PRIM_CYLINDER, PRIM_PLANE, PRIM_SPHERE, PRIM_TORUS, ccCommandLineInterface::print(), PROBABILITY, ccCommandLineInterface::silentMode(), CV_TYPES::SPHERE, SUPPORT_POINTS, ccHObjectCaster::ToMesh(), ccHObjectCaster::ToPointCloud(), CV_TYPES::TORUS, and ccCommandLineInterface::warning().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qRANSAC_SD/include/qRANSAC_SD_Commands.h