ACloudViewer: ccPointPairRegistrationDlg::EntityContexts Struct Reference
ccPointPairRegistrationDlg::EntityContexts Struct Reference
Set of contexts.
#include <ecvPointPairRegistrationDlg.h>
Public Member Functions
void fill (const ccHObject::Container &entities)
void restoreAll ()
Public Attributes
bool isShifted
CCVector3d shift
Detailed Description
Set of contexts.
Definition at line 163 of file ecvPointPairRegistrationDlg.h.
Member Function Documentation
fill()
void ccPointPairRegistrationDlg::EntityContexts::fill (const ccHObject::Container & entities)
Definition at line 150 of file ecvPointPairRegistrationDlg.cpp.
References ccPointPairRegistrationDlg::clear(), ccShiftedObject::getGlobalShift(), ccShiftedObject::isShifted(), and ccHObjectCaster::ToShifted().
Referenced by ccPointPairRegistrationDlg::init().
restoreAll()
void ccPointPairRegistrationDlg::EntityContexts::restoreAll () inline
Definition at line 166 of file ecvPointPairRegistrationDlg.h.
References ccPointPairRegistrationDlg::EntityContext::restore().
Referenced by ccPointPairRegistrationDlg::linkWith().
Member Data Documentation
isShifted
bool ccPointPairRegistrationDlg::EntityContexts::isShifted
Definition at line 170 of file ecvPointPairRegistrationDlg.h.
Referenced by ccPointPairRegistrationDlg::addManualAlignedPoint(), and ccPointPairRegistrationDlg::addManualRefPoint().
shift
CCVector3d ccPointPairRegistrationDlg::EntityContexts::shift
Definition at line 171 of file ecvPointPairRegistrationDlg.h.
The documentation for this struct was generated from the following files:
/root/ACloudViewer/app/ecvPointPairRegistrationDlg.h
/root/ACloudViewer/app/ecvPointPairRegistrationDlg.cpp