ACloudViewer: colmap::BaseCameraModel< CameraModel > Struct Template Reference
colmap::BaseCameraModel< CameraModel > Struct Template Reference
#include <camera_models.h>
Static Public Member Functions
template<typename T >
static bool HasBogusParams (const std::vector< T > &params, const size_t width, const size_t height, const T min_focal_length_ratio, const T max_focal_length_ratio, const T max_extra_param)
template<typename T >
static bool HasBogusFocalLength (const std::vector< T > &params, const size_t width, const size_t height, const T min_focal_length_ratio, const T max_focal_length_ratio)
template<typename T >
static bool HasBogusPrincipalPoint (const std::vector< T > &params, const size_t width, const size_t height)
template<typename T >
static bool HasBogusExtraParams (const std::vector< T > &params, const T max_extra_param)
template<typename T >
static T ImageToWorldThreshold (const T *params, const T threshold)
template<typename T >
static void IterativeUndistortion (const T *params, T *u, T *v)
Detailed Description
template<typename CameraModel>
struct colmap::BaseCameraModel< CameraModel >
Definition at line 124 of file camera_models.h.
Member Function Documentation
HasBogusExtraParams()
template<typename CameraModel > template<typename T > bool colmap::BaseCameraModel< CameraModel >::HasBogusExtraParams (const std::vector< T > & params, const T max_extra_param) inline static
Definition at line 512 of file camera_models.h.
HasBogusFocalLength()
template<typename CameraModel > template<typename T > bool colmap::BaseCameraModel< CameraModel >::HasBogusFocalLength (const std::vector< T > & params, const size_t width, const size_t height, const T min_focal_length_ratio, const T max_focal_length_ratio) inline static
Definition at line 482 of file camera_models.h.
References height, and width.
HasBogusParams()
template<typename CameraModel > template<typename T > bool colmap::BaseCameraModel< CameraModel >::HasBogusParams (const std::vector< T > & params, const size_t width, const size_t height, const T min_focal_length_ratio, const T max_focal_length_ratio, const T max_extra_param) inline static
Definition at line 457 of file camera_models.h.
References colmap::BaseCameraModel< FOVCameraModel >::HasBogusExtraParams(), colmap::BaseCameraModel< FOVCameraModel >::HasBogusFocalLength(), colmap::BaseCameraModel< FOVCameraModel >::HasBogusPrincipalPoint(), height, and width.
HasBogusPrincipalPoint()
template<typename CameraModel > template<typename T > bool colmap::BaseCameraModel< CameraModel >::HasBogusPrincipalPoint (const std::vector< T > & params, const size_t width, const size_t height) inline static
Definition at line 503 of file camera_models.h.
References height, and width.
ImageToWorldThreshold()
template<typename CameraModel > template<typename T > T colmap::BaseCameraModel< CameraModel >::ImageToWorldThreshold (const T * params, const T threshold) inline static
Definition at line 525 of file camera_models.h.
IterativeUndistortion()
template<typename CameraModel > template<typename T > void colmap::BaseCameraModel< CameraModel >::IterativeUndistortion (const T * params, T * u, T * v) inline static
Definition at line 537 of file camera_models.h.
References e, and x.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/base/camera_models.h