ACloudViewer: Edge Class Reference
Edge Class Reference
Weighted graph edge.
Public Types
typedef std::pair< unsigned, unsigned > Key
Unique edge key type.
Public Member Functions
Edge ()
Edge (const VertexIterator &A, unsigned _nearestPointIndex, float _nearestPointSquareDist)
bool operator< (const Edge &e) const
Edge ()
Edge (const VertexIterator &A, unsigned _nearestPointIndex, float _nearestPointSquareDist)
bool operator< (const Edge &e) const
Edge (unsigned v1, unsigned v2, float weight)
Default constructor.
bool operator< (const Edge &other) const
Strict weak ordering operator (required by std::priority_queue)
const unsigned & v1 () const
Returns first vertex (index)
const unsigned & v2 () const
Returns second vertex (index)
Static Public Member Functions
static Key ConstructKey (unsigned v1, unsigned v2)
Returns the unique key of an edge (no vertex order)
Public Attributes
VertexIterator itA
unsigned nearestPointIndex
float nearestPointSquareDist
Protected Attributes
Key m_key
Unique key.
float m_weight
Associated weight.
Detailed Description
Weighted graph edge.
Definition at line 491 of file PointProjectionTools.cpp.
Member Typedef Documentation
Key
typedef std::pair<unsigned, unsigned> Edge::Key
Unique edge key type.
Definition at line 30 of file ecvMinimumSpanningTreeForNormsDirection.cpp.
Constructor & Destructor Documentation
Edge() [1/5]
Edge::Edge () inline
Definition at line 492 of file PointProjectionTools.cpp.
Edge() [2/5]
Edge::Edge (const VertexIterator & A, unsigned _nearestPointIndex, float _nearestPointSquareDist) inline
Definition at line 494 of file PointProjectionTools.cpp.
Edge() [3/5]
Edge::Edge () inline
Definition at line 45 of file ecvContourExtractor.cpp.
Edge() [4/5]
Edge::Edge (const VertexIterator & A, unsigned _nearestPointIndex, float _nearestPointSquareDist) inline
Definition at line 47 of file ecvContourExtractor.cpp.
Edge() [5/5]
Edge::Edge (unsigned v1, unsigned v2, float weight) inline
Default constructor.
Definition at line 38 of file ecvMinimumSpanningTreeForNormsDirection.cpp.
References m_weight.
Member Function Documentation
ConstructKey()
static Key Edge::ConstructKey (unsigned v1, unsigned v2) inline static
Returns the unique key of an edge (no vertex order)
Definition at line 33 of file ecvMinimumSpanningTreeForNormsDirection.cpp.
References cloudViewer::core::make_pair(), v1(), and v2().
Referenced by Graph::addEdge(), and Graph::weight().
operator<() [1/3]
bool Edge::operator< (const Edge & e) const inline
Definition at line 55 of file ecvContourExtractor.cpp.
References e, and nearestPointSquareDist.
operator<() [2/3]
bool Edge::operator< (const Edge & e) const inline
Definition at line 502 of file PointProjectionTools.cpp.
References e.
operator<() [3/3]
bool Edge::operator< (const Edge & other) const inline
Strict weak ordering operator (required by std::priority_queue)
Definition at line 44 of file ecvMinimumSpanningTreeForNormsDirection.cpp.
References m_weight.
v1()
const unsigned& Edge::v1 () const inline
Returns first vertex (index)
Definition at line 49 of file ecvMinimumSpanningTreeForNormsDirection.cpp.
References m_key.
Referenced by ConstructKey(), and ResolveNormalsWithMST().
v2()
const unsigned& Edge::v2 () const inline
Returns second vertex (index)
Definition at line 51 of file ecvMinimumSpanningTreeForNormsDirection.cpp.
References m_key.
Referenced by ConstructKey(), and ResolveNormalsWithMST().
Member Data Documentation
itA
VertexIterator Edge::itA
Definition at line 506 of file PointProjectionTools.cpp.
m_key
Key Edge::m_key protected
Unique key.
Definition at line 55 of file ecvMinimumSpanningTreeForNormsDirection.cpp.
Referenced by v1(), and v2().
m_weight
float Edge::m_weight protected
Associated weight.
Definition at line 58 of file ecvMinimumSpanningTreeForNormsDirection.cpp.
Referenced by Edge(), and operator<().
nearestPointIndex
unsigned Edge::nearestPointIndex
Definition at line 507 of file PointProjectionTools.cpp.
nearestPointSquareDist
float Edge::nearestPointSquareDist
Definition at line 508 of file PointProjectionTools.cpp.
Referenced by operator<().
The documentation for this class was generated from the following files:
/root/ACloudViewer/core/src/PointProjectionTools.cpp
/root/ACloudViewer/libs/CV_db/src/ecvMinimumSpanningTreeForNormsDirection.cpp
/root/ACloudViewer/app/ecvContourExtractor.cpp