ACloudViewer: SAHooks Struct Reference
SAHooks Struct Reference
#include <shapefil.h>
Public Attributes
SAFile(* FOpen)(const char *filename, const char *access)
SAOffset(* FRead)(void *p, SAOffset size, SAOffset nmemb, SAFile file)
SAOffset(* FWrite)(void *p, SAOffset size, SAOffset nmemb, SAFile file)
SAOffset(* FSeek)(SAFile file, SAOffset offset, int whence)
SAOffset(* FTell)(SAFile file)
int(* FFlush)(SAFile file)
int(* FClose)(SAFile file)
int(* Remove)(const char *filename)
void(* Error)(const char *message)
double(* Atof)(const char *str)
Detailed Description
Definition at line 293 of file shapefil.h.
Member Data Documentation
Atof
double(* SAHooks::Atof) (const char *str)
Definition at line 304 of file shapefil.h.
Referenced by DBFReadAttribute(), and SASetupDefaultHooks().
Error
void(* SAHooks::Error) (const char *message)
Definition at line 303 of file shapefil.h.
Referenced by DBFAddNativeFieldType(), DBFFlushRecord(), DBFLoadRecord(), SASetupDefaultHooks(), SHPCreateLL(), SHPOpenLL(), SHPRestoreSHX(), SHPSearchDiskTreeNode(), SHPWriteHeader(), and SHPWriteObject().
FClose
int(* SAHooks::FClose) (SAFile file)
Definition at line 300 of file shapefil.h.
Referenced by DBFClose(), DBFCreateLL(), DBFOpenLL(), SASetupDefaultHooks(), SHPClose(), SHPCloseDiskTree(), SHPCreateLL(), SHPOpenLL(), SHPRestoreSHX(), and SHPWriteTreeLL().
FFlush
int(* SAHooks::FFlush) (SAFile file)
Definition at line 299 of file shapefil.h.
Referenced by DBFUpdateHeader(), SASetupDefaultHooks(), and SHPWriteHeader().
FOpen
SAFile(* SAHooks::FOpen) (const char *filename, const char *access)
Definition at line 294 of file shapefil.h.
Referenced by DBFCreateLL(), DBFOpenLL(), SASetupDefaultHooks(), SHPCreateLL(), SHPOpenDiskTree(), SHPOpenLL(), SHPRestoreSHX(), and SHPWriteTreeLL().
FRead
SAOffset(* SAHooks::FRead) (void *p, SAOffset size, SAOffset nmemb, SAFile file)
Definition at line 295 of file shapefil.h.
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFDeleteField(), DBFLoadRecord(), DBFOpenLL(), DBFReorderFields(), DBFUpdateHeader(), SASetupDefaultHooks(), SHPOpenLL(), SHPRestoreSHX(), SHPSearchDiskTree(), SHPSearchDiskTreeEx(), and SHPSearchDiskTreeNode().
FSeek
SAOffset(* SAHooks::FSeek) (SAFile file, SAOffset offset, int whence)
Definition at line 297 of file shapefil.h.
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFDeleteField(), DBFFlushRecord(), DBFLoadRecord(), DBFOpenLL(), DBFReorderFields(), DBFUpdateHeader(), DBFWriteHeader(), SASetupDefaultHooks(), SHPOpenLL(), SHPRestoreSHX(), SHPSearchDiskTree(), SHPSearchDiskTreeEx(), SHPSearchDiskTreeNode(), SHPWriteHeader(), and SHPWriteObject().
FTell
SAOffset(* SAHooks::FTell) (SAFile file)
Definition at line 298 of file shapefil.h.
Referenced by SASetupDefaultHooks(), and SHPOpenLL().
FWrite
SAOffset(* SAHooks::FWrite) (void *p, SAOffset size, SAOffset nmemb, SAFile file)
Definition at line 296 of file shapefil.h.
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFCreateLL(), DBFDeleteField(), DBFFlushRecord(), DBFReorderFields(), DBFUpdateHeader(), DBFWriteHeader(), SASetupDefaultHooks(), SHPCreateLL(), SHPRestoreSHX(), SHPWriteHeader(), SHPWriteObject(), SHPWriteTreeLL(), and SHPWriteTreeNode().
Remove
int(* SAHooks::Remove) (const char *filename)
Definition at line 301 of file shapefil.h.
Referenced by DBFCreateLL(), and SASetupDefaultHooks().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/CV_io/extern/shapelib/shapefil.h