ACloudViewer: flann::Hamming< T > Struct Template Reference
flann::Hamming< T > Struct Template Reference
#include <dist.h>
Public Types
typedef T ElementType
typedef unsigned int ResultType
Public Member Functions
unsigned int popcnt32 (uint32_t n) const
unsigned int popcnt64 (uint64_t n) const
template<typename Iterator1 , typename Iterator2 >
ResultType operator() (Iterator1 a, Iterator2 b, size_t size, ResultType=0) const
Detailed Description
template<typename T>
struct flann::Hamming< T >
Definition at line 529 of file dist.h.
Member Typedef Documentation
ElementType
template<typename T > typedef T flann::Hamming< T >::ElementType
Definition at line 531 of file dist.h.
ResultType
template<typename T > typedef unsigned int flann::Hamming< T >::ResultType
Definition at line 532 of file dist.h.
Member Function Documentation
operator()()
template<typename T > template<typename Iterator1 , typename Iterator2 > ResultType flann::Hamming< T >::operator() (Iterator1 a, Iterator2 b, size_t size, ResultType = 0) const inline
Definition at line 551 of file dist.h.
References flann::Hamming< T >::popcnt32(), flann::Hamming< T >::popcnt64(), result, and size.
popcnt32()
template<typename T > unsigned int flann::Hamming< T >::popcnt32 (uint32_t n) const inline
This is popcount_3() from: http://en.wikipedia.org/wiki/Hamming_weight
Definition at line 536 of file dist.h.
Referenced by flann::Hamming< T >::operator()().
popcnt64()
template<typename T > unsigned int flann::Hamming< T >::popcnt64 (uint64_t n) const inline
Definition at line 543 of file dist.h.
Referenced by flann::Hamming< T >::operator()().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/FLANN/algorithms/dist.h