ACloudViewer: cloudViewer::visualization::rendering::REHandle< entityType > Struct Template Reference
cloudViewer::visualization::rendering::REHandle< entityType > Struct Template Reference
#include <RendererHandle.h>
Public Member Functions
REHandle ()
REHandle (const REHandle &other)
REHandle (std::uint16_t id)
REHandle & operator= (const REHandle &other)
Public Member Functions inherited from cloudViewer::visualization::rendering::REHandle_abstract
size_t Hash () const
bool operator== (const REHandle_abstract &other) const
bool operator!= (const REHandle_abstract &other) const
bool operator< (const REHandle_abstract &other) const
operator bool () const
REHandle_abstract ()
std::uint16_t GetId () const
Static Public Member Functions
static REHandle Next ()
static REHandle Concretize (const REHandle_abstract &abstract)
Static Public Member Functions inherited from cloudViewer::visualization::rendering::REHandle_abstract
static const char * TypeToString (EntityType type)
Static Public Attributes
static const REHandle kBad
Static Public Attributes inherited from cloudViewer::visualization::rendering::REHandle_abstract
static const std::uint16_t kBadId = 0
Additional Inherited Members
Public Attributes inherited from cloudViewer::visualization::rendering::REHandle_abstract
const EntityType type = EntityType::None
Protected Member Functions inherited from cloudViewer::visualization::rendering::REHandle_abstract
REHandle_abstract (const EntityType aType, const std::uint16_t aId)
Protected Attributes inherited from cloudViewer::visualization::rendering::REHandle_abstract
std::uint16_t id = kBadId
Static Protected Attributes inherited from cloudViewer::visualization::rendering::REHandle_abstract
static std::array< std::uint16_t, static_cast< size_t >EntityType::Count)> uid_table
Detailed Description
template<EntityType entityType>
struct cloudViewer::visualization::rendering::REHandle< entityType >
Definition at line 90 of file RendererHandle.h.
Constructor & Destructor Documentation
REHandle() [1/3]
template<EntityType entityType> cloudViewer::visualization::rendering::REHandle< entityType >::REHandle () inline
Definition at line 113 of file RendererHandle.h.
Referenced by cloudViewer::visualization::rendering::REHandle< entityType >::Concretize(), and cloudViewer::visualization::rendering::REHandle< entityType >::Next().
REHandle() [2/3]
template<EntityType entityType> cloudViewer::visualization::rendering::REHandle< entityType >::REHandle (const REHandle< entityType > & other) inline
Definition at line 114 of file RendererHandle.h.
REHandle() [3/3]
template<EntityType entityType> cloudViewer::visualization::rendering::REHandle< entityType >::REHandle (std::uint16_t id) inline explicit
Definition at line 116 of file RendererHandle.h.
Member Function Documentation
Concretize()
template<EntityType entityType> static REHandle cloudViewer::visualization::rendering::REHandle< entityType >::Concretize (const REHandle_abstract & abstract) inline static
Definition at line 104 of file RendererHandle.h.
References cloudViewer::visualization::rendering::REHandle_abstract::GetId(), cloudViewer::visualization::rendering::REHandle< entityType >::REHandle(), and cloudViewer::visualization::rendering::REHandle_abstract::type.
Next()
template<EntityType entityType> static REHandle cloudViewer::visualization::rendering::REHandle< entityType >::Next () inline static
Definition at line 93 of file RendererHandle.h.
References cloudViewer::visualization::rendering::REHandle_abstract::kBadId, cloudViewer::visualization::rendering::REHandle< entityType >::REHandle(), and cloudViewer::visualization::rendering::REHandle_abstract::uid_table.
operator=()
template<EntityType entityType> REHandle& cloudViewer::visualization::rendering::REHandle< entityType >::operator= (const REHandle< entityType > & other) inline
Definition at line 118 of file RendererHandle.h.
References cloudViewer::visualization::rendering::REHandle_abstract::id.
Member Data Documentation
kBad
template<EntityType entityType> const REHandle< entityType > cloudViewer::visualization::rendering::REHandle< entityType >::kBad static
Definition at line 91 of file RendererHandle.h.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/RendererHandle.h