ACloudViewer: cloudViewer::io::rpc::messages::MeshData Struct Reference
cloudViewer::io::rpc::messages::MeshData Struct Reference
struct for storing MeshData, e.g., PointClouds, TriangleMesh, ..
#include <Messages.h>
Public Member Functions
void SetO3DTypeToPointCloud ()
void SetO3DTypeToLineSet ()
void SetO3DTypeToTriangleMesh ()
bool O3DTypeIsPointCloud () const
bool O3DTypeIsLineSet () const
bool O3DTypeIsTriangleMesh () const
bool CheckVertices (std::string &errstr) const
bool CheckFaces (std::string &errstr) const
bool CheckO3DType (std::string &errstr) const
bool CheckMessage (std::string &errstr) const
MSGPACK_DEFINE_MAP (o3d_type, vertices, vertex_attributes, faces, face_attributes, lines, line_attributes, material, material_scalar_attributes, material_vector_attributes, texture_maps)
Static Public Member Functions
static std::string MsgId ()
Public Attributes
std::string o3d_type
Array vertices
shape must be [num_verts,3]
std::map< std::string, Array > vertex_attributes
Array faces
std::map< std::string, Array > face_attributes
stores arbitrary attributes for each face
Array lines
std::map< std::string, Array > line_attributes
stores arbitrary attributes for each line
std::string material = ""
Material for DrawableGeometry.
std::map< std::string, float > material_scalar_attributes
Material scalar properties.
std::map< std::string, std::array< float, 4 > > material_vector_attributes
Material vector[4] properties.
std::map< std::string, Array > texture_maps
map of arrays that can be interpreted as textures
Detailed Description
struct for storing MeshData, e.g., PointClouds, TriangleMesh, ..
Definition at line 255 of file Messages.h.
Member Function Documentation
CheckFaces()
bool cloudViewer::io::rpc::messages::MeshData::CheckFaces (std::string & errstr) const inline
Definition at line 317 of file Messages.h.
References cloudViewer::io::rpc::messages::Array::CheckNonEmpty(), cloudViewer::io::rpc::messages::Array::CheckRank(), cloudViewer::io::rpc::messages::Array::CheckType(), faces, cloudViewer::io::rpc::messages::Array::shape, patch::to_string(), cloudViewer::io::rpc::messages::TypeStr< int32_t >(), and cloudViewer::io::rpc::messages::TypeStr< int64_t >().
Referenced by CheckMessage().
CheckMessage()
bool cloudViewer::io::rpc::messages::MeshData::CheckMessage (std::string & errstr) const inline
Definition at line 368 of file Messages.h.
References CheckFaces(), CheckO3DType(), and CheckVertices().
Referenced by cloudViewer::io::rpc::MeshDataToGeometry(), cloudViewer::visualization::MessageProcessor::ProcessMessage(), and cloudViewer::io::rpc::SetMeshData().
CheckO3DType()
bool cloudViewer::io::rpc::messages::MeshData::CheckO3DType (std::string & errstr) const inline
Definition at line 355 of file Messages.h.
References o3d_type, O3DTypeIsLineSet(), O3DTypeIsPointCloud(), and O3DTypeIsTriangleMesh().
Referenced by CheckMessage().
CheckVertices()
bool cloudViewer::io::rpc::messages::MeshData::CheckVertices (std::string & errstr) const inline
Definition at line 308 of file Messages.h.
References cloudViewer::io::rpc::messages::Array::CheckNonEmpty(), cloudViewer::io::rpc::messages::Array::CheckShape(), cloudViewer::io::rpc::messages::Array::shape, and vertices.
Referenced by CheckMessage().
MsgId()
static std::string cloudViewer::io::rpc::messages::MeshData::MsgId () inline static
Definition at line 256 of file Messages.h.
MSGPACK_DEFINE_MAP()
cloudViewer::io::rpc::messages::MeshData::MSGPACK_DEFINE_MAP (o3d_type , vertices , vertex_attributes , faces , face_attributes , lines , line_attributes , material , material_scalar_attributes , material_vector_attributes , texture_maps)
O3DTypeIsLineSet()
bool cloudViewer::io::rpc::messages::MeshData::O3DTypeIsLineSet () const inline
Definition at line 305 of file Messages.h.
References o3d_type.
Referenced by CheckO3DType(), and cloudViewer::io::rpc::MeshDataToGeometry().
O3DTypeIsPointCloud()
bool cloudViewer::io::rpc::messages::MeshData::O3DTypeIsPointCloud () const inline
Definition at line 304 of file Messages.h.
References o3d_type.
Referenced by CheckO3DType(), and cloudViewer::io::rpc::MeshDataToGeometry().
O3DTypeIsTriangleMesh()
bool cloudViewer::io::rpc::messages::MeshData::O3DTypeIsTriangleMesh () const inline
Definition at line 306 of file Messages.h.
References o3d_type.
Referenced by CheckO3DType(), and cloudViewer::io::rpc::MeshDataToGeometry().
SetO3DTypeToLineSet()
void cloudViewer::io::rpc::messages::MeshData::SetO3DTypeToLineSet () inline
Definition at line 301 of file Messages.h.
References o3d_type.
Referenced by cloudViewer::io::rpc::GeometryToMeshData().
SetO3DTypeToPointCloud()
void cloudViewer::io::rpc::messages::MeshData::SetO3DTypeToPointCloud () inline
Definition at line 300 of file Messages.h.
References o3d_type.
Referenced by cloudViewer::io::rpc::GeometryToMeshData().
SetO3DTypeToTriangleMesh()
void cloudViewer::io::rpc::messages::MeshData::SetO3DTypeToTriangleMesh () inline
Definition at line 302 of file Messages.h.
References o3d_type.
Referenced by cloudViewer::io::rpc::GeometryToMeshData(), and cloudViewer::io::rpc::SetTriangleMesh().
Member Data Documentation
face_attributes
std::map<std::string, Array> cloudViewer::io::rpc::messages::MeshData::face_attributes
stores arbitrary attributes for each face
Definition at line 278 of file Messages.h.
Referenced by cloudViewer::io::rpc::GeometryToMeshData(), cloudViewer::io::rpc::MeshDataToGeometry(), cloudViewer::io::rpc::SetMeshData(), and cloudViewer::io::rpc::SetTriangleMesh().
faces
Array cloudViewer::io::rpc::messages::MeshData::faces
This array stores vertex indices to define faces. The array can be of rank 1 or 2. An array of rank 2 with shape [num_faces,n] defines num_faces n-gons. If the rank of the array is 1 then polys of different lengths are stored sequentially. Each polygon is stored as a sequence 'n i1 i2 ... in' with n>=3. The type of the array must be int32_t or int64_t
Definition at line 276 of file Messages.h.
Referenced by CheckFaces(), cloudViewer::io::rpc::GeometryToMeshData(), cloudViewer::io::rpc::MeshDataToGeometry(), cloudViewer::visualization::MessageProcessor::ProcessMessage(), cloudViewer::io::rpc::SetMeshData(), and cloudViewer::io::rpc::SetTriangleMesh().
line_attributes
std::map<std::string, Array> cloudViewer::io::rpc::messages::MeshData::line_attributes
stores arbitrary attributes for each line
Definition at line 289 of file Messages.h.
Referenced by cloudViewer::io::rpc::GeometryToMeshData(), cloudViewer::io::rpc::MeshDataToGeometry(), and cloudViewer::io::rpc::SetMeshData().
lines
Array cloudViewer::io::rpc::messages::MeshData::lines
This array stores vertex indices to define lines. The array can be of rank 1 or 2. An array of rank 2 with shape [num_lines,n] defines num_lines linestrips with n vertices. If the rank of the array is 1 then linestrips with different number of vertices are stored sequentially. Each linestrip is stored as a sequence 'n i1 i2 ... in' with n>=2. The type of the array must be int32_t or int64_t
Definition at line 287 of file Messages.h.
Referenced by cloudViewer::io::rpc::GeometryToMeshData(), cloudViewer::io::rpc::MeshDataToGeometry(), and cloudViewer::io::rpc::SetMeshData().
material
std::string cloudViewer::io::rpc::messages::MeshData::material = ""
Material for DrawableGeometry.
Definition at line 292 of file Messages.h.
Referenced by cloudViewer::io::rpc::AddMaterialToMeshData(), cloudViewer::io::rpc::GetMaterialFromMeshData(), and cloudViewer::io::rpc::SetMeshData().
material_scalar_attributes
std::map<std::string, float> cloudViewer::io::rpc::messages::MeshData::material_scalar_attributes
Material scalar properties.
Definition at line 294 of file Messages.h.
Referenced by cloudViewer::io::rpc::AddMaterialToMeshData(), cloudViewer::io::rpc::GetMaterialFromMeshData(), and cloudViewer::io::rpc::SetMeshData().
material_vector_attributes
std::map<std::string, std::array<float, 4> > cloudViewer::io::rpc::messages::MeshData::material_vector_attributes
Material vector[4] properties.
Definition at line 296 of file Messages.h.
Referenced by cloudViewer::io::rpc::AddMaterialToMeshData(), cloudViewer::io::rpc::GetMaterialFromMeshData(), and cloudViewer::io::rpc::SetMeshData().
o3d_type
std::string cloudViewer::io::rpc::messages::MeshData::o3d_type
The original CloudViewer geometry type from which the MeshData object has been created. This is one of "PointCloud", "LineSet", "TriangleMesh". If this field is empty CloudViewer will infer the type based on the presence of lines and faces.
Definition at line 262 of file Messages.h.
Referenced by CheckO3DType(), O3DTypeIsLineSet(), O3DTypeIsPointCloud(), O3DTypeIsTriangleMesh(), cloudViewer::io::rpc::SetMeshData(), SetO3DTypeToLineSet(), SetO3DTypeToPointCloud(), SetO3DTypeToTriangleMesh(), and cloudViewer::io::rpc::SetTriangleMesh().
texture_maps
std::map<std::string, Array> cloudViewer::io::rpc::messages::MeshData::texture_maps
map of arrays that can be interpreted as textures
Definition at line 298 of file Messages.h.
Referenced by cloudViewer::io::rpc::AddMaterialToMeshData(), cloudViewer::io::rpc::GetMaterialFromMeshData(), cloudViewer::io::rpc::SetMeshData(), and cloudViewer::io::rpc::SetTriangleMesh().
vertex_attributes
std::map<std::string, Array> cloudViewer::io::rpc::messages::MeshData::vertex_attributes
stores arbitrary attributes for each vertex, hence the first dim must be num_verts
Definition at line 268 of file Messages.h.
Referenced by cloudViewer::io::rpc::GeometryToMeshData(), cloudViewer::io::rpc::MeshDataToGeometry(), cloudViewer::visualization::MessageProcessor::ProcessMessage(), cloudViewer::io::rpc::SetMeshData(), cloudViewer::io::rpc::SetPointCloud(), and cloudViewer::io::rpc::SetTriangleMesh().
vertices
Array cloudViewer::io::rpc::messages::MeshData::vertices
shape must be [num_verts,3]
Definition at line 265 of file Messages.h.
Referenced by CheckVertices(), cloudViewer::io::rpc::GeometryToMeshData(), cloudViewer::io::rpc::MeshDataToGeometry(), cloudViewer::visualization::MessageProcessor::ProcessMessage(), cloudViewer::io::rpc::SetMeshData(), cloudViewer::io::rpc::SetPointCloud(), and cloudViewer::io::rpc::SetTriangleMesh().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/io/rpc/Messages.h