ACloudViewer: CommandRasterize Struct Reference
CommandRasterize Struct Reference
#include <ecvCommandRaster.h>
Public Member Functions
CommandRasterize ()
bool process (ccCommandLineInterface &cmd) override
Main process.
Public Member Functions inherited from ccCommandLineInterface::Command
Command (const QString &name, const QString &keyword)
Default constructor.
virtual ~Command ()=default
Additional Inherited Members
Public Types inherited from ccCommandLineInterface::Command
using Shared = QSharedPointer< Command >
Shared type.
Public Attributes inherited from ccCommandLineInterface::Command
QString m_name
Command name.
QString m_keyword
Command keyword.
Detailed Description
Definition at line 12 of file ecvCommandRaster.h.
Constructor & Destructor Documentation
CommandRasterize()
CommandRasterize::CommandRasterize ()
Definition at line 88 of file ecvCommandRaster.cpp.
Member Function Documentation
process()
bool CommandRasterize::process (ccCommandLineInterface & cmd) override virtual
Main process.
Implements ccCommandLineInterface::Command.
Definition at line 91 of file ecvCommandRaster.cpp.
References ccHObject::addChild(), ccCommandLineInterface::addTimestamp(), ccRasterizeTool::ExportBands::allSFs, ccCommandLineInterface::arguments(), ccCommandLineInterface::autoSaveMode(), CLEntityDesc::basename, ccCommandLineInterface::clouds(), ccDrawableObject::colorsShown(), COMMAND_GRID_OUTPUT_CLOUD, COMMAND_GRID_OUTPUT_MESH, COMMAND_GRID_OUTPUT_RASTER_RGB, COMMAND_GRID_OUTPUT_RASTER_Z, COMMAND_GRID_STEP, COMMAND_GRID_VERT_DIR, COMMAND_RASTER_CUSTOM_HEIGHT, COMMAND_RASTER_FILL_EMPTY_CELLS, COMMAND_RASTER_PROJ_TYPE, COMMAND_RASTER_RESAMPLE, COMMAND_RASTER_SF_PROJ_TYPE, ccRasterGrid::ComputeGridSize(), cloudViewer::PointProjectionTools::computeTriangulation(), ccRasterGrid::convertToCloud(), cloudViewer::DELAUNAY_2D_AXIS_ALIGNED, ccCommandLineInterface::error(), ccCommandLineInterface::exportEntity(), ccRasterizeTool::ExportGeoTiff(), ccRasterGrid::FILL_CUSTOM_HEIGHT, ccRasterGrid::fillEmptyCells(), ccRasterGrid::fillWith(), Vector3Tpl< double >::fromArray(), GetEmptyCellFillingStrategy(), ccCommandLineInterface::getExportFilename(), ccObject::getName(), ccBBox::getOwnBB(), GetProjectionType(), ccPointCloud::hasScalarFields(), ccRasterizeTool::ExportBands::height, ccRasterGrid::height, ccRasterGrid::init(), ccRasterGrid::INTERPOLATE_DELAUNAY, ccCommandLineInterface::IsCommand(), ccRasterGrid::LEAVE_EMPTY, ccRasterGrid::maxHeight, CLMeshDesc::mesh, ccCommandLineInterface::meshes(), cloudViewer::BoundingBoxTpl< T >::minCorner(), ccRasterGrid::minHeight, CLEntityDesc::path, ccRasterGrid::PER_CELL_VALUE, ccCommandLineInterface::print(), ccRasterGrid::PROJ_AVERAGE_VALUE, ccRasterizeTool::ExportBands::rgb, ccPointCloud::setCurrentDisplayedScalarField(), ccObject::setEnabled(), ccShiftedObject::setGlobalScale(), ccShiftedObject::setGlobalShift(), ccObject::setName(), ccDrawableObject::setVisible(), ccDrawableObject::sfShown(), ccDrawableObject::showColors(), ccDrawableObject::showSF(), ccCommandLineInterface::silentMode(), Tuple3Tpl< Type >::u, CVLog::Warning(), ccCommandLineInterface::warning(), ccCommandLineInterface::widgetParent(), and ccRasterGrid::width.
The documentation for this struct was generated from the following files:
/root/ACloudViewer/app/ecvCommandRaster.h
/root/ACloudViewer/app/ecvCommandRaster.cpp