ACloudViewer: Command3DMASCClassif Struct Reference
Command3DMASCClassif Struct Reference
#include <q3DMASCCommands.h>
Public Member Functions
Command3DMASCClassif ()
virtual bool process (ccCommandLineInterface &cmd) override
Main process.
Public Member Functions inherited from ccCommandLineInterface::Command
Command (const QString &name, const QString &keyword)
Default constructor.
virtual ~Command ()=default
Additional Inherited Members
Public Types inherited from ccCommandLineInterface::Command
using Shared = QSharedPointer< Command >
Shared type.
Public Attributes inherited from ccCommandLineInterface::Command
QString m_name
Command name.
QString m_keyword
Command keyword.
Detailed Description
Definition at line 49 of file q3DMASCCommands.h.
Constructor & Destructor Documentation
Command3DMASCClassif()
Command3DMASCClassif::Command3DMASCClassif () inline
Definition at line 50 of file q3DMASCCommands.h.
Member Function Documentation
process()
virtual bool Command3DMASCClassif::process (ccCommandLineInterface & cmd) inline override virtual
Main process.
Implements ccCommandLineInterface::Command.
Definition at line 54 of file q3DMASCCommands.h.
References ccCommandLineInterface::arguments(), ccCommandLineInterface::autoSaveMode(), masc::Classifier::classify(), ccCommandLineInterface::clouds(), COMMAND_3DMASC_CLASSIFY, COMMAND_3DMASC_KEEP_ATTRIBS, COMMAND_3DMASC_ONLY_FEATURES, COMMAND_3DMASC_SKIP_FEATURES, corePoints, ccCommandLineInterface::error(), ccCommandLineInterface::exportEntity(), masc::Feature::ExtractSources(), ccCommandLineInterface::IsCommand(), masc::Tools::LoadClassifierCloudLabels(), masc::Tools::LoadFile(), masc::Feature::LoadSources(), masc::Tools::PrepareFeatures(), ccCommandLineInterface::print(), SFCollector::releaseSFs(), masc::Feature::SaveSources(), ccCommandLineInterface::silentMode(), QtCompat::SkipEmptyParts, and ccCommandLineInterface::widgetParent().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/q3DMASC/q3DMASCCommands.h