ACloudViewer: colmap::mvs::TextureView Struct Reference
colmap::mvs::TextureView Struct Reference
#include <texturing.h>
Public Member Functions
TextureView (std::size_t id, const std::string &image_file, const Eigen::Matrix3f &projection, const Eigen::Matrix4f &world_to_cam, const Eigen::Vector3f &pos, const Eigen::Vector3f &viewdir, int width, int height)
Eigen::Vector2f GetPixelCoords (const Eigen::Vector3f &vertex) const
bool ValidPixel (const Eigen::Vector2f &pixel) const
bool Inside (const Eigen::Vector3f &v1, const Eigen::Vector3f &v2, const Eigen::Vector3f &v3) const
Public Attributes
std::size_t id
std::string image_file
int width
int height
Eigen::Matrix3f projection
Eigen::Matrix4f world_to_cam
Eigen::Vector3f pos
Eigen::Vector3f viewdir
std::shared_ptr< QImage > image_data
Detailed Description
Definition at line 37 of file texturing.h.
Constructor & Destructor Documentation
TextureView()
colmap::mvs::TextureView::TextureView (std::size_t id, const std::string & image_file, const Eigen::Matrix3f & projection, const Eigen::Matrix4f & world_to_cam, const Eigen::Vector3f & pos, const Eigen::Vector3f & viewdir, int width, int height)
Definition at line 54 of file texturing.cc.
Member Function Documentation
GetPixelCoords()
Eigen::Vector2f colmap::mvs::TextureView::GetPixelCoords (const Eigen::Vector3f & vertex) const
Definition at line 71 of file texturing.cc.
References projection, and world_to_cam.
Referenced by colmap::mvs::GenerateCandidate(), and Inside().
Inside()
bool colmap::mvs::TextureView::Inside (const Eigen::Vector3f & v1, const Eigen::Vector3f & v2, const Eigen::Vector3f & v3) const
Definition at line 105 of file texturing.cc.
References GetPixelCoords(), and ValidPixel().
ValidPixel()
bool colmap::mvs::TextureView::ValidPixel (const Eigen::Vector2f & pixel) const
Definition at line 100 of file texturing.cc.
References height, and width.
Referenced by Inside().
Member Data Documentation
height
int colmap::mvs::TextureView::height
Definition at line 41 of file texturing.h.
Referenced by colmap::mvs::GenerateCandidate(), and ValidPixel().
id
std::size_t colmap::mvs::TextureView::id
Definition at line 38 of file texturing.h.
image_data
std::shared_ptr<QImage> colmap::mvs::TextureView::image_data mutable
Definition at line 48 of file texturing.h.
Referenced by colmap::mvs::GenerateCandidate().
image_file
std::string colmap::mvs::TextureView::image_file
Definition at line 39 of file texturing.h.
Referenced by colmap::mvs::GenerateCandidate().
pos
Eigen::Vector3f colmap::mvs::TextureView::pos
Definition at line 44 of file texturing.h.
projection
Eigen::Matrix3f colmap::mvs::TextureView::projection
Definition at line 42 of file texturing.h.
Referenced by GetPixelCoords().
viewdir
Eigen::Vector3f colmap::mvs::TextureView::viewdir
Definition at line 45 of file texturing.h.
width
int colmap::mvs::TextureView::width
Definition at line 40 of file texturing.h.
Referenced by colmap::mvs::GenerateCandidate(), and ValidPixel().
world_to_cam
Eigen::Matrix4f colmap::mvs::TextureView::world_to_cam
Definition at line 43 of file texturing.h.
Referenced by GetPixelCoords().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/libs/Reconstruction/src/mvs/texturing.h
/root/ACloudViewer/libs/Reconstruction/src/mvs/texturing.cc