ACloudViewer: ccGLCameraParameters Struct Reference
ccGLCameraParameters Struct Reference
OpenGL camera parameters.
#include <ecvGenericDisplayTools.h>
Public Member Functions
ccGLCameraParameters ()
bool project (const CCVector3d &input3D, CCVector3d &output2D, bool *inFrustum=nullptr) const
Projects a 3D point in 2D (+ normalized 'z' coordinate)
bool project (const CCVector3 &input3D, CCVector3d &output2D, bool *inFrustum=nullptr) const
Projects a 3D point in 2D (+ normalized 'z' coordinate)
bool unproject (const CCVector3d &input2D, CCVector3d &output3D) const
Unprojects a 2D point (+ normalized 'z' coordinate) in 3D.
bool unproject (const CCVector3 &input2D, CCVector3d &output3D) const
Unprojects a 2D point (+ normalized 'z' coordinate) in 3D.
Public Attributes
ccGLMatrixd modelViewMat
Model view matrix (GL_MODELVIEW)
ccGLMatrixd projectionMat
Projection matrix (GL_PROJECTION)
int viewport [4]
Viewport (GL_VIEWPORT)
bool perspective
Perspective mode.
float fov_deg
F.O.V. (in degrees) - perspective mode only.
float pixelSize
Pixel size (i.e. zoom) - non perspective mode only.
Detailed Description
OpenGL camera parameters.
Definition at line 554 of file ecvGenericDisplayTools.h.
Constructor & Destructor Documentation
ccGLCameraParameters()
ccGLCameraParameters::ccGLCameraParameters () inline
Definition at line 555 of file ecvGenericDisplayTools.h.
Member Function Documentation
project() [1/2]
bool ccGLCameraParameters::project (const CCVector3 & input3D, CCVector3d & output2D, bool * inFrustum = nullptr) const inline
Projects a 3D point in 2D (+ normalized 'z' coordinate)
Definition at line 569 of file ecvGenericDisplayTools.h.
References Tuple3Tpl< Type >::data().
project() [2/2]
bool ccGLCameraParameters::project (const CCVector3d & input3D, CCVector3d & output2D, bool * inFrustum = nullptr) const inline
Projects a 3D point in 2D (+ normalized 'z' coordinate)
Definition at line 561 of file ecvGenericDisplayTools.h.
References Tuple3Tpl< Type >::data().
Referenced by define_ccGenericDisplayTools(), and ccSymbolCloud::drawMeOnly().
unproject() [1/2]
bool ccGLCameraParameters::unproject (const CCVector3 & input2D, CCVector3d & output3D) const inline
Unprojects a 2D point (+ normalized 'z' coordinate) in 3D.
Definition at line 585 of file ecvGenericDisplayTools.h.
References Tuple3Tpl< Type >::data().
unproject() [2/2]
bool ccGLCameraParameters::unproject (const CCVector3d & input2D, CCVector3d & output3D) const inline
Unprojects a 2D point (+ normalized 'z' coordinate) in 3D.
Definition at line 578 of file ecvGenericDisplayTools.h.
References Tuple3Tpl< Type >::data().
Referenced by define_ccGenericDisplayTools(), and qCanupo2DViewDialog::getClickPos().
Member Data Documentation
fov_deg
float ccGLCameraParameters::fov_deg
F.O.V. (in degrees) - perspective mode only.
Definition at line 601 of file ecvGenericDisplayTools.h.
Referenced by define_ccGenericDisplayTools().
modelViewMat
ccGLMatrixd ccGLCameraParameters::modelViewMat
Model view matrix (GL_MODELVIEW)
Definition at line 593 of file ecvGenericDisplayTools.h.
Referenced by define_ccGenericDisplayTools(), ccPointPair::drawMeOnly(), ccTrace::drawMeOnly(), and ccCloudLayersHelper::projectCloud().
perspective
bool ccGLCameraParameters::perspective
Perspective mode.
Definition at line 599 of file ecvGenericDisplayTools.h.
Referenced by define_ccGenericDisplayTools().
pixelSize
float ccGLCameraParameters::pixelSize
Pixel size (i.e. zoom) - non perspective mode only.
Definition at line 603 of file ecvGenericDisplayTools.h.
Referenced by define_ccGenericDisplayTools().
projectionMat
ccGLMatrixd ccGLCameraParameters::projectionMat
Projection matrix (GL_PROJECTION)
Definition at line 595 of file ecvGenericDisplayTools.h.
Referenced by define_ccGenericDisplayTools().
viewport
int ccGLCameraParameters::viewport[4]
Viewport (GL_VIEWPORT)
Definition at line 597 of file ecvGenericDisplayTools.h.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvGenericDisplayTools.h