ACloudViewer: CP::CutPursuit_Linear< T > Struct Template Reference
CP::CutPursuit_Linear< T > Struct Template Reference
#include <CutPursuit_Linear.h>
Public Member Functions
CutPursuit_Linear (uint32_t nbVertex=1)
std::pair< T, T > compute_energy () override
size_t split () override
void compute_corners (std::vector< std::vector< uint32_t >> &corners)
std::pair< uint32_t, uint32_t > find_corner (const uint32_t &i_com)
void set_capacities (const std::vector< std::vector< uint32_t >> &corners)
std::pair< std::vector< T >, T > compute_value (const uint32_t &i_com) override
std::pair< std::vector< T >, T > compute_merge_gain (const VertexDescriptor< T > &comp1, const VertexDescriptor< T > &comp2) override
Public Member Functions inherited from CP::CutPursuit< T >
CutPursuit (uint32_t nbVertex=1)
std::pair< std::vector< T >, std::vector< T > > run ()
void initialize ()
void compute_reduced_value ()
size_t activate_edges (bool allows_saturation=true)
void reduce ()
void compute_connected_components ()
std::vector< VertexDescriptor< T > > connected_comp_from_root (const VertexDescriptor< T > &root, const size_t &size_comp, std::vector< bool > &vertices_seen, std::vector< bool > &edges_seen)
void compute_reduced_graph ()
uint32_t merge (bool is_cutoff)
void cutoff ()
void saturateComponent (const uint32_t &ind_com)
Public Attributes
std::vector< std::vector< T > > componentVector
Public Attributes inherited from CP::CutPursuit< T >
Graph< T > main_graph
Graph< T > reduced_graph
std::vector< std::vector< VertexDescriptor< T > > > components
std::vector< VertexDescriptor< T > > root_vertex
std::vector< bool > saturated_components
std::vector< std::vector< EdgeDescriptor > > borders
VertexDescriptor< T > source
VertexDescriptor< T > sink
uint32_t dim
uint32_t nVertex
uint32_t nEdge
CP::VertexIterator< T > lastIterator
CPparameter< T > parameter
Detailed Description
template<typename T>
struct CP::CutPursuit_Linear< T >
Definition at line 14 of file CutPursuit_Linear.h.
Constructor & Destructor Documentation
CutPursuit_Linear()
template<typename T > CP::CutPursuit_Linear< T >::CutPursuit_Linear (uint32_t nbVertex = 1) inline
Definition at line 19 of file CutPursuit_Linear.h.
Member Function Documentation
compute_corners()
template<typename T > void CP::CutPursuit_Linear< T >::compute_corners (std::vector< std::vector< uint32_t >> & corners) inline
Definition at line 90 of file CutPursuit_Linear.h.
References CP::CutPursuit< T >::components, CP::CutPursuit_Linear< T >::find_corner(), and CP::CutPursuit< T >::saturated_components.
Referenced by CP::CutPursuit_Linear< T >::split().
compute_energy()
template<typename T > std::pair<T, T> CP::CutPursuit_Linear< T >::compute_energy () inline override virtual
Reimplemented from CP::CutPursuit< T >.
Definition at line 23 of file CutPursuit_Linear.h.
References CP::CutPursuit< T >::dim, CP::CutPursuit< T >::lastIterator, and CP::CutPursuit< T >::main_graph.
compute_merge_gain()
template<typename T > std::pair<std::vector<T>, T> CP::CutPursuit_Linear< T >::compute_merge_gain (const VertexDescriptor< T > & comp1, const VertexDescriptor< T > & comp2) inline override virtual
Reimplemented from CP::CutPursuit< T >.
Definition at line 275 of file CutPursuit_Linear.h.
References CP::CutPursuit< T >::dim, CP::CutPursuit< T >::reduced_graph, and vertex_index.
compute_value()
template<typename T > std::pair<std::vector<T>, T> CP::CutPursuit_Linear< T >::compute_value (const uint32_t & i_com) inline override virtual
Reimplemented from CP::CutPursuit< T >.
Definition at line 219 of file CutPursuit_Linear.h.
References CP::CutPursuit< T >::components, CP::CutPursuit< T >::dim, and CP::CutPursuit< T >::main_graph.
find_corner()
template<typename T > std::pair<uint32_t, uint32_t> CP::CutPursuit_Linear< T >::find_corner (const uint32_t & i_com) inline
Definition at line 110 of file CutPursuit_Linear.h.
References CP::CutPursuit< T >::components, CP::CutPursuit< T >::dim, and CP::CutPursuit< T >::main_graph.
Referenced by CP::CutPursuit_Linear< T >::compute_corners().
set_capacities()
template<typename T > void CP::CutPursuit_Linear< T >::set_capacities (const std::vector< std::vector< uint32_t >> & corners) inline
Definition at line 145 of file CutPursuit_Linear.h.
References CP::CutPursuit< T >::components, CP::CutPursuit< T >::main_graph, CP::CutPursuit< T >::saturated_components, CP::CutPursuit< T >::sink, and CP::CutPursuit< T >::source.
Referenced by CP::CutPursuit_Linear< T >::split().
split()
template<typename T > size_t CP::CutPursuit_Linear< T >::split () inline override virtual
Reimplemented from CP::CutPursuit< T >.
Definition at line 61 of file CutPursuit_Linear.h.
References CP::CutPursuit< T >::activate_edges(), CP::CutPursuit< T >::components, CP::CutPursuit_Linear< T >::compute_corners(), CP::CutPursuit< T >::main_graph, CP::CutPursuit_Linear< T >::set_capacities(), CP::CutPursuit< T >::sink, CP::CutPursuit< T >::source, and vertex_index.
Member Data Documentation
componentVector
template<typename T > std::vector<std::vector<T> > CP::CutPursuit_Linear< T >::componentVector
Definition at line 15 of file CutPursuit_Linear.h.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qTreeIso/include/CutPursuit_Linear.h