ACloudViewer: cloudViewer::visualization::visualizer::O3DVisualizer::Impl Struct Reference
cloudViewer::visualization::visualizer::O3DVisualizer::Impl Struct Reference
Public Member Functions
void Construct (O3DVisualizer *w)
void MakeSettingsUI ()
void AddGeometry (const std::string &name, std::shared_ptr< geometry::Geometry > geom, std::shared_ptr< t::geometry::Geometry > tgeom, std::shared_ptr< rendering::TriangleMeshModel > model, const rendering::MaterialRecord *material, const std::string &group, double time, bool is_visible)
void UpdateGeometry (const std::string &name, std::shared_ptr< t::geometry::Geometry > tgeom, uint32_t update_flags)
void RemoveGeometry (const std::string &name)
void ShowGeometry (const std::string &name, bool show)
O3DVisualizer::DrawObject GetGeometry (const std::string &name) const
MaterialRecord GetGeometryMaterial (const std::string &name)
void ModifyGeometryMaterial (const std::string &name, const MaterialRecord *material)
void CreateInspectionModeMaterial (MaterialRecord &inspect_mat, bool pcd=false)
std::shared_ptr< ccMesh > DuplicateGeometryForInspection (std::shared_ptr< ccMesh > mesh)
void UpdateGeometryForInspectionMode (bool enable)
void UpdateGeometryForWireframeMode (bool enable)
void Add3DLabel (const Eigen::Vector3f &pos, const char *text)
void Clear3DLabels ()
void SetupCamera (float fov, const Eigen::Vector3f &center, const Eigen::Vector3f &eye, const Eigen::Vector3f &up)
void SetupCamera (const camera::PinholeCameraIntrinsic &intrinsic, const Eigen::Matrix4d &extrinsic)
void SetupCamera (const Eigen::Matrix3d &intrinsic, const Eigen::Matrix4d &extrinsic, int intrinsic_width_px, int intrinsic_height_px)
void ResetCameraToDefault ()
void SetBackground (const Eigen::Vector4f &bg_color, std::shared_ptr< geometry::Image > bg_image)
void ShowSettings (bool show, bool cancel_auto_show=true)
void ShowSkybox (bool show)
void ShowAxes (bool show)
void ShowGround (bool show)
void SetGroundPlane (rendering::Scene::GroundPlane plane)
void EnableSunFollowsCamera (bool enable)
void EnableInspectionRelatedUI (bool enable)
void EnableBasicMode (bool enable)
void EnableWireframeMode (bool enable)
void SetPointSize (int px)
void SetLineWidth (int px)
void SetShader (O3DVisualizer::Shader shader)
void OverrideMaterial (const std::string &name, const MaterialRecord &original_material, O3DVisualizer::Shader shader)
float ConvertToScaledPixels (int px)
const char * GetShaderString (O3DVisualizer::Shader shader)
void SetIBL (std::string path)
void SetIBLIntensity (float intensity)
void SetLightingProfile (const LightingProfile &profile)
void SetMouseMode (SceneWidget::Controls mode)
void SetPanelOpen (const std::string &name, bool open)
void SetPicking ()
std::vector< O3DVisualizerSelections::SelectionSet > GetSelectionSets () const
void SetCurrentTime (double t)
void SetAnimating (bool is_animating)
void SetOnAnimationTick (O3DVisualizer &o3dvis, std::function< TickResult(O3DVisualizer &, double, double)> cb)
void SetUIState (const UIState &new_state)
void AddGroup (const std::string &group)
void EnableGroup (const std::string &group, bool enable)
void AddObjectToTree (const DrawObject &o)
void UpdateObjectTree ()
void UpdateTimeUIRange ()
void UpdateTimeUI ()
void UpdateGeometryVisibility (const DrawObject &o)
bool IsGeometryVisible (const DrawObject &o)
void NewSelectionSet ()
void RemoveSelectionSet (int index)
void SelectSelectionSet (int index)
void UpdateSelectionSetList ()
void UpdateSelectableGeometry ()
bool OnAnimationTick ()
void UpdateAnimationTickClockTime (double now)
void ExportCurrentImage (const std::string &path)
void OnAbout ()
void OnExportRGB ()
void OnClose ()
void OnToggleSettings ()
std::string UniquifyName (const std::string &name)
Eigen::Vector4f CalcDefaultUnlitColor ()
std::vector< std::string > GetListOfIBLs ()
Public Attributes
std::set< std::string > added_names_
std::set< std::string > added_groups_
std::vector< DrawObject > objects_
std::vector< DrawObject > inspection_objects_
std::vector< DrawObject > wireframe_objects_
std::shared_ptr< O3DVisualizerSelections > selections_
bool polygon_selection_unselects_ = false
bool selections_need_update_ = true
std::function< void(double)> on_animation_
std::function< bool()> on_animation_tick_
std::shared_ptr< io::rpc::ZMQReceiver > receiver_
std::shared_ptr< MessageProcessor > message_processor_
UIState ui_state_
bool can_auto_show_settings_ = true
bool was_using_sun_follows_cam_ = false
double min_time_ = 0.0
double max_time_ = 0.0
double start_animation_clock_time_ = 0.0
double next_animation_tick_clock_time_ = 0.0
double last_animation_tick_clock_time_ = 0.0
Window * window_ = nullptr
SceneWidget * scene_ = nullptr
struct {
Menu * actions_menu
std::unordered_map< int, std::function< void(O3DVisualizer &)> > menuid2action
Vert * panel
CollapsableVert * mouse_panel
TabControl * mouse_tab
Vert * view_panel
SceneWidget::Controls view_mouse_mode
std::map< SceneWidget::Controls, Button * > mouse_buttons
Vert * pick_panel
Horiz * polygon_selection_panel
Button * new_selection_set
Button * delete_selection_set
ListView * selection_sets
CollapsableVert * scene_panel
Checkbox * show_skybox
Checkbox * show_axes
Checkbox * show_ground
Checkbox * basic_mode
Checkbox * wireframe_mode
Combobox * ground_plane
ColorEdit * bg_color
Slider * point_size
Combobox * shader
Combobox * lighting
CollapsableVert * light_panel
Checkbox * use_ibl
Checkbox * use_sun
Combobox * ibl_names
Slider * ibl_intensity
Slider * sun_intensity
Checkbox * sun_follows_camera
VectorEdit * sun_dir
ColorEdit * sun_color
CollapsableVert * geometries_panel
TreeView * geometries
std::map< std::string, TreeView::ItemId > group2itemid
std::map< std::string, TreeView::ItemId > object2itemid
EmptyIfHiddenVert * time_panel
Slider * time_slider
NumberEdit * time_edit
SmallToggleButton * play
EmptyIfHiddenVert * actions_panel
ButtonList * actions
} settings
Detailed Description
Definition at line 283 of file O3DVisualizer.cpp.
Member Function Documentation
Add3DLabel()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::Add3DLabel (const Eigen::Vector3f & pos, const char * text) inline
Definition at line 1332 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::AddLabel().
AddGeometry()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::AddGeometry (const std::string & name, std::shared_ptr< geometry::Geometry > geom, std::shared_ptr< t::geometry::Geometry > tgeom, std::shared_ptr< rendering::TriangleMeshModel > model, const rendering::MaterialRecord * material, const std::string & group, double time, bool is_visible) inline
Definition at line 836 of file O3DVisualizer.cpp.
References cloudViewer::visualization::rendering::MaterialRecord::base_color, has_colors, has_normals, cloudViewer::visualization::rendering::MaterialRecord::line_width, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::line_width, octree, cloudViewer::visualization::rendering::MaterialRecord::point_size, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::point_size, and cloudViewer::visualization::rendering::MaterialRecord::shader.
AddGroup()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::AddGroup (const std::string & group) inline
Definition at line 1887 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::enabled_groups.
AddObjectToTree()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::AddObjectToTree (const DrawObject & o) inline
Definition at line 1936 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::group, cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::is_visible, name, cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::name, and cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::time.
CalcDefaultUnlitColor()
Eigen::Vector4f cloudViewer::visualization::visualizer::O3DVisualizer::Impl::CalcDefaultUnlitColor () inline
Definition at line 2198 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::bg_color.
Clear3DLabels()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::Clear3DLabels () inline
Definition at line 1336 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ClearLabels().
Construct()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::Construct (O3DVisualizer * w) inline
Definition at line 373 of file O3DVisualizer.cpp.
ConvertToScaledPixels()
float cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ConvertToScaledPixels (int px) inline
Definition at line 1607 of file O3DVisualizer.cpp.
CreateInspectionModeMaterial()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::CreateInspectionModeMaterial (MaterialRecord & inspect_mat, bool pcd = false) inline
Definition at line 1168 of file O3DVisualizer.cpp.
References cloudViewer::visualization::rendering::MaterialRecord::albedo_img, cloudViewer::visualization::rendering::MaterialRecord::ao_img, cloudViewer::visualization::rendering::MaterialRecord::base_anisotropy, cloudViewer::visualization::rendering::MaterialRecord::base_clearcoat, cloudViewer::visualization::rendering::MaterialRecord::base_color, cloudViewer::visualization::rendering::MaterialRecord::base_metallic, cloudViewer::visualization::rendering::MaterialRecord::base_reflectance, cloudViewer::visualization::rendering::MaterialRecord::base_roughness, cloudViewer::visualization::rendering::MaterialRecord::metallic_img, cloudViewer::visualization::rendering::MaterialRecord::normal_img, cloudViewer::visualization::rendering::MaterialRecord::reflectance_img, cloudViewer::visualization::rendering::MaterialRecord::roughness_img, and cloudViewer::visualization::rendering::MaterialRecord::shader.
DuplicateGeometryForInspection()
std::shared_ptr<ccMesh> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::DuplicateGeometryForInspection (std::shared_ptr< ccMesh > mesh) inline
Definition at line 1197 of file O3DVisualizer.cpp.
EnableBasicMode()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::EnableBasicMode (bool enable) inline
Definition at line 1474 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::sun_follows_camera.
EnableGroup()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::EnableGroup (const std::string & group, bool enable) inline
Definition at line 1914 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::enabled_groups.
EnableInspectionRelatedUI()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::EnableInspectionRelatedUI (bool enable) inline
Definition at line 1459 of file O3DVisualizer.cpp.
EnableSunFollowsCamera()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::EnableSunFollowsCamera (bool enable) inline
Definition at line 1441 of file O3DVisualizer.cpp.
References cloudViewer::visualization::rendering::Camera::GetForwardVector(), cloudViewer::visualization::gui::SceneWidget::GetScene(), cloudViewer::visualization::gui::SceneWidget::SetOnCameraChanged(), cloudViewer::visualization::gui::SceneWidget::SetSunInteractorEnabled(), and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::sun_dir.
EnableWireframeMode()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::EnableWireframeMode (bool enable) inline
Definition at line 1514 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), and cloudViewer::visualization::gui::SceneWidget::GetScene().
ExportCurrentImage()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ExportCurrentImage (const std::string & path) inline
Definition at line 2101 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::EnableSceneCaching(), cloudViewer::visualization::gui::SceneWidget::GetScene(), image, cloudViewer::visualization::gui::Window::ShowMessageBox(), and cloudViewer::io::WriteImage().
GetGeometry()
O3DVisualizer::DrawObject cloudViewer::visualization::visualizer::O3DVisualizer::Impl::GetGeometry (const std::string & name) const inline
Definition at line 1139 of file O3DVisualizer.cpp.
References name.
GetGeometryMaterial()
MaterialRecord cloudViewer::visualization::visualizer::O3DVisualizer::Impl::GetGeometryMaterial (const std::string & name) inline
Definition at line 1148 of file O3DVisualizer.cpp.
References name.
GetListOfIBLs()
std::vector<std::string> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::GetListOfIBLs () inline
Definition at line 2209 of file O3DVisualizer.cpp.
References cloudViewer::utility::filesystem::GetFileNameWithoutDirectory(), cloudViewer::visualization::gui::Application::GetInstance(), cloudViewer::visualization::gui::Application::GetResourcePath(), cloudViewer::utility::filesystem::ListFilesInDirectory(), and name.
GetSelectionSets()
std::vector<O3DVisualizerSelections::SelectionSet> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::GetSelectionSets () const inline
Definition at line 1726 of file O3DVisualizer.cpp.
GetShaderString()
const char* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::GetShaderString (O3DVisualizer::Shader shader) inline
Definition at line 1611 of file O3DVisualizer.cpp.
References LogWarning.
IsGeometryVisible()
bool cloudViewer::visualization::visualizer::O3DVisualizer::Impl::IsGeometryVisible (const DrawObject & o) inline
Definition at line 2004 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::current_time, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::enabled_groups, cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::group, cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::is_visible, cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::time, and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::time_step.
MakeSettingsUI()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::MakeSettingsUI () inline
Definition at line 411 of file O3DVisualizer.cpp.
ModifyGeometryMaterial()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ModifyGeometryMaterial (const std::string & name, const MaterialRecord * material) inline
Definition at line 1157 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::GetScene(), and name.
NewSelectionSet()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::NewSelectionSet () inline
Definition at line 2014 of file O3DVisualizer.cpp.
OnAbout()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::OnAbout () inline
Definition at line 2116 of file O3DVisualizer.cpp.
References theme.
OnAnimationTick()
bool cloudViewer::visualization::visualizer::O3DVisualizer::Impl::OnAnimationTick () inline
Definition at line 2087 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::current_time, cloudViewer::visualization::gui::Application::GetInstance(), cloudViewer::visualization::gui::Application::Now(), and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::time_step.
OnClose()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::OnClose () inline
Definition at line 2177 of file O3DVisualizer.cpp.
OnExportRGB()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::OnExportRGB () inline
Definition at line 2164 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::FileDialog::SAVE.
OnToggleSettings()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::OnToggleSettings () inline
Definition at line 2179 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::show_settings.
OverrideMaterial()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::OverrideMaterial (const std::string & name, const MaterialRecord & original_material, O3DVisualizer::Shader shader) inline
Definition at line 1589 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::GetScene(), name, and cloudViewer::visualization::rendering::MaterialRecord::shader.
RemoveGeometry()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::RemoveGeometry (const std::string & name) inline
Definition at line 1067 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::enabled_groups, cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), max(), min(), name, and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::point_size.
RemoveSelectionSet()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::RemoveSelectionSet (int index) inline
Definition at line 2020 of file O3DVisualizer.cpp.
ResetCameraToDefault()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ResetCameraToDefault () inline
Definition at line 1363 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), and cloudViewer::visualization::gui::SceneWidget::SetupCamera().
SelectSelectionSet()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SelectSelectionSet (int index) inline
Definition at line 2031 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw().
SetAnimating()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetAnimating (bool is_animating) inline
Definition at line 1746 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::current_time, cloudViewer::visualization::gui::Application::GetInstance(), cloudViewer::visualization::visualizer::O3DVisualizer::UIState::is_animating, and cloudViewer::visualization::gui::Application::Now().
SetBackground()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetBackground (const Eigen::Vector4f & bg_color, std::shared_ptr< geometry::Image > bg_image) inline
Definition at line 1369 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::bg_color, cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::scene_shader.
SetCurrentTime()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetCurrentTime (double t) inline
Definition at line 1731 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::current_time.
SetGroundPlane()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetGroundPlane (rendering::Scene::GroundPlane plane) inline
Definition at line 1425 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), cloudViewer::visualization::visualizer::O3DVisualizer::UIState::ground_plane, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::show_ground, cloudViewer::visualization::rendering::Scene::XY, and cloudViewer::visualization::rendering::Scene::XZ.
SetIBL()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetIBL (std::string path) inline
Definition at line 1629 of file O3DVisualizer.cpp.
References cloudViewer::utility::filesystem::FileExists(), cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::Application::GetInstance(), cloudViewer::visualization::gui::SceneWidget::GetScene(), cloudViewer::visualization::visualizer::O3DVisualizer::UIState::ibl_path, and LogWarning.
SetIBLIntensity()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetIBLIntensity (float intensity) inline
Definition at line 1663 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::ibl_intensity.
SetLightingProfile()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetLightingProfile (const LightingProfile & profile) inline
Definition at line 1668 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::GetScene(), cloudViewer::visualization::visualizer::O3DVisualizer::UIState::ibl_intensity, profile, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::sun_color, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::sun_dir, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::sun_intensity, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::use_ibl, and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::use_sun.
SetLineWidth()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetLineWidth (int px) inline
Definition at line 1557 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::visualizer::O3DVisualizer::UIState::line_width, and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::scene_shader.
SetMouseMode()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetMouseMode (SceneWidget::Controls mode) inline
Definition at line 1687 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::mouse_mode, and cloudViewer::visualization::gui::SceneWidget::SetViewControls().
SetOnAnimationTick()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetOnAnimationTick (O3DVisualizer & o3dvis, std::function< TickResult(O3DVisualizer &, double, double)> cb) inline
Definition at line 1772 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::Application::GetInstance(), cloudViewer::visualization::gui::Application::Now(), and result.
SetPanelOpen()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetPanelOpen (const std::string & name, bool open) inline
Definition at line 1704 of file O3DVisualizer.cpp.
References name.
SetPicking()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetPicking () inline
Definition at line 1716 of file O3DVisualizer.cpp.
SetPointSize()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetPointSize (int px) inline
Definition at line 1530 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), max(), cloudViewer::visualization::visualizer::O3DVisualizer::UIState::point_size, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::scene_shader, and cloudViewer::visualization::gui::SceneWidget::SetPickablePointSize().
SetShader()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetShader (O3DVisualizer::Shader shader) inline
Definition at line 1575 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::scene_shader.
SetUIState()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetUIState (const UIState & new_state) inline
Definition at line 1796 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::bg_color, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::enabled_groups, cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), cloudViewer::visualization::visualizer::O3DVisualizer::UIState::ibl_intensity, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::ibl_path, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::is_animating, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::line_width, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::point_size, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::scene_shader, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::show_axes, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::show_ground, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::show_settings, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::show_skybox, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::sun_color, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::sun_dir, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::sun_follows_camera, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::sun_intensity, cloudViewer::visualization::visualizer::O3DVisualizer::UIState::use_ibl, and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::use_sun.
SetupCamera() [1/3]
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetupCamera (const camera::PinholeCameraIntrinsic & intrinsic, const Eigen::Matrix4d & extrinsic) inline
Definition at line 1346 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), and cloudViewer::visualization::gui::SceneWidget::SetupCamera().
SetupCamera() [2/3]
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetupCamera (const Eigen::Matrix3d & intrinsic, const Eigen::Matrix4d & extrinsic, int intrinsic_width_px, int intrinsic_height_px) inline
Definition at line 1353 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), and cloudViewer::visualization::gui::SceneWidget::SetupCamera().
SetupCamera() [3/3]
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::SetupCamera (float fov, const Eigen::Vector3f & center, const Eigen::Vector3f & eye, const Eigen::Vector3f & up) inline
Definition at line 1338 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), and cloudViewer::visualization::gui::SceneWidget::LookAt().
ShowAxes()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ShowAxes (bool show) inline
Definition at line 1411 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::show_axes.
ShowGeometry()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ShowGeometry (const std::string & name, bool show) inline
Definition at line 1111 of file O3DVisualizer.cpp.
References name.
ShowGround()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ShowGround (bool show) inline
Definition at line 1418 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), cloudViewer::visualization::visualizer::O3DVisualizer::UIState::ground_plane, and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::show_ground.
ShowSettings()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ShowSettings (bool show, bool cancel_auto_show = true) inline
Definition at line 1391 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::Application::GetInstance(), cloudViewer::visualization::gui::Application::GetMenubar(), and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::show_settings.
ShowSkybox()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ShowSkybox (bool show) inline
Definition at line 1404 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), and cloudViewer::visualization::visualizer::O3DVisualizer::UIState::show_skybox.
UniquifyName()
std::string cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UniquifyName (const std::string & name) inline
Definition at line 2181 of file O3DVisualizer.cpp.
References name.
UpdateAnimationTickClockTime()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateAnimationTickClockTime (double now) inline
Definition at line 2097 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::frame_delay.
UpdateGeometry()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateGeometry (const std::string & name, std::shared_ptr< t::geometry::Geometry > tgeom, uint32_t update_flags) inline
Definition at line 1050 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), LogWarning, and name.
UpdateGeometryForInspectionMode()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateGeometryForInspectionMode (bool enable) inline
Definition at line 1206 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::GetScene(), and CV_TYPES::POINT_CLOUD.
UpdateGeometryForWireframeMode()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateGeometryForWireframeMode (bool enable) inline
Definition at line 1259 of file O3DVisualizer.cpp.
References cloudViewer::visualization::rendering::MaterialRecord::base_color, cloudViewer::geometry::LineSet::CreateFromTriangleMesh(), cloudViewer::visualization::rendering::MaterialRecord::emissive_color, cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::geometry, cloudViewer::visualization::gui::SceneWidget::GetScene(), cloudViewer::visualization::rendering::MaterialRecord::line_width, cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::material, CV_TYPES::MESH, cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::name, cloudViewer::visualization::rendering::MaterialRecord::shader, and cloudViewer::t::geometry::TriangleMesh::ToLegacy().
UpdateGeometryVisibility()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateGeometryVisibility (const DrawObject & o) inline
Definition at line 1999 of file O3DVisualizer.cpp.
References cloudViewer::visualization::gui::SceneWidget::ForceRedraw(), cloudViewer::visualization::gui::SceneWidget::GetScene(), and cloudViewer::visualization::visualizer::O3DVisualizer::DrawObject::name.
UpdateObjectTree()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateObjectTree () inline
Definition at line 1970 of file O3DVisualizer.cpp.
UpdateSelectableGeometry()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateSelectableGeometry () inline
Definition at line 2055 of file O3DVisualizer.cpp.
UpdateSelectionSetList()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateSelectionSetList () inline
Definition at line 2037 of file O3DVisualizer.cpp.
References max(), and min().
UpdateTimeUI()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateTimeUI () inline
Definition at line 1994 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::current_time.
UpdateTimeUIRange()
void cloudViewer::visualization::visualizer::O3DVisualizer::Impl::UpdateTimeUIRange () inline
Definition at line 1982 of file O3DVisualizer.cpp.
References cloudViewer::visualization::visualizer::O3DVisualizer::UIState::current_time, max(), and min().
Member Data Documentation
actions
ButtonList* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::actions
Definition at line 370 of file O3DVisualizer.cpp.
actions_menu
Menu* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::actions_menu
Definition at line 314 of file O3DVisualizer.cpp.
actions_panel
EmptyIfHiddenVert* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::actions_panel
Definition at line 369 of file O3DVisualizer.cpp.
added_groups_
std::set<std::string> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::added_groups_
Definition at line 285 of file O3DVisualizer.cpp.
added_names_
std::set<std::string> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::added_names_
Definition at line 284 of file O3DVisualizer.cpp.
basic_mode
Checkbox* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::basic_mode
Definition at line 334 of file O3DVisualizer.cpp.
bg_color
ColorEdit* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::bg_color
Definition at line 337 of file O3DVisualizer.cpp.
can_auto_show_settings_
bool cloudViewer::visualization::visualizer::O3DVisualizer::Impl::can_auto_show_settings_ = true
Definition at line 298 of file O3DVisualizer.cpp.
delete_selection_set
Button* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::delete_selection_set
Definition at line 327 of file O3DVisualizer.cpp.
geometries
TreeView* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::geometries
Definition at line 353 of file O3DVisualizer.cpp.
geometries_panel
CollapsableVert* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::geometries_panel
Definition at line 352 of file O3DVisualizer.cpp.
ground_plane
Combobox* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ground_plane
Definition at line 336 of file O3DVisualizer.cpp.
group2itemid
std::map<std::string, TreeView::ItemId> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::group2itemid
Definition at line 355 of file O3DVisualizer.cpp.
ibl_intensity
Slider* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ibl_intensity
Definition at line 346 of file O3DVisualizer.cpp.
ibl_names
Combobox* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ibl_names
Definition at line 345 of file O3DVisualizer.cpp.
inspection_objects_
std::vector<DrawObject> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::inspection_objects_
Definition at line 287 of file O3DVisualizer.cpp.
last_animation_tick_clock_time_
double cloudViewer::visualization::visualizer::O3DVisualizer::Impl::last_animation_tick_clock_time_ = 0.0
Definition at line 305 of file O3DVisualizer.cpp.
light_panel
CollapsableVert* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::light_panel
Definition at line 342 of file O3DVisualizer.cpp.
lighting
Combobox* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::lighting
Definition at line 340 of file O3DVisualizer.cpp.
max_time_
double cloudViewer::visualization::visualizer::O3DVisualizer::Impl::max_time_ = 0.0
Definition at line 302 of file O3DVisualizer.cpp.
menuid2action
std::unordered_map<int, std::function<void(O3DVisualizer &)> > cloudViewer::visualization::visualizer::O3DVisualizer::Impl::menuid2action
Definition at line 316 of file O3DVisualizer.cpp.
message_processor_
std::shared_ptr<MessageProcessor> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::message_processor_
Definition at line 295 of file O3DVisualizer.cpp.
min_time_
double cloudViewer::visualization::visualizer::O3DVisualizer::Impl::min_time_ = 0.0
Definition at line 301 of file O3DVisualizer.cpp.
mouse_buttons
std::map<SceneWidget::Controls, Button *> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::mouse_buttons
Definition at line 323 of file O3DVisualizer.cpp.
mouse_panel
CollapsableVert* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::mouse_panel
Definition at line 319 of file O3DVisualizer.cpp.
mouse_tab
TabControl* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::mouse_tab
Definition at line 320 of file O3DVisualizer.cpp.
new_selection_set
Button* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::new_selection_set
Definition at line 326 of file O3DVisualizer.cpp.
next_animation_tick_clock_time_
double cloudViewer::visualization::visualizer::O3DVisualizer::Impl::next_animation_tick_clock_time_ = 0.0
Definition at line 304 of file O3DVisualizer.cpp.
object2itemid
std::map<std::string, TreeView::ItemId> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::object2itemid
Definition at line 357 of file O3DVisualizer.cpp.
objects_
std::vector<DrawObject> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::objects_
Definition at line 286 of file O3DVisualizer.cpp.
on_animation_
std::function<void(double)> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::on_animation_
Definition at line 292 of file O3DVisualizer.cpp.
on_animation_tick_
std::function<bool()> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::on_animation_tick_
Definition at line 293 of file O3DVisualizer.cpp.
panel
Vert* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::panel
Definition at line 318 of file O3DVisualizer.cpp.
pick_panel
Vert* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::pick_panel
Definition at line 324 of file O3DVisualizer.cpp.
play
SmallToggleButton* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::play
Definition at line 367 of file O3DVisualizer.cpp.
point_size
Slider* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::point_size
Definition at line 338 of file O3DVisualizer.cpp.
polygon_selection_panel
Horiz* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::polygon_selection_panel
Definition at line 325 of file O3DVisualizer.cpp.
polygon_selection_unselects_
bool cloudViewer::visualization::visualizer::O3DVisualizer::Impl::polygon_selection_unselects_ = false
Definition at line 290 of file O3DVisualizer.cpp.
receiver_
std::shared_ptr<io::rpc::ZMQReceiver> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::receiver_
Definition at line 294 of file O3DVisualizer.cpp.
scene_
SceneWidget* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::scene_ = nullptr
Definition at line 308 of file O3DVisualizer.cpp.
scene_panel
CollapsableVert* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::scene_panel
Definition at line 330 of file O3DVisualizer.cpp.
selection_sets
ListView* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::selection_sets
Definition at line 328 of file O3DVisualizer.cpp.
selections_
std::shared_ptr<O3DVisualizerSelections> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::selections_
Definition at line 289 of file O3DVisualizer.cpp.
selections_need_update_
bool cloudViewer::visualization::visualizer::O3DVisualizer::Impl::selections_need_update_ = true
Definition at line 291 of file O3DVisualizer.cpp.
struct { ... } cloudViewer::visualization::visualizer::O3DVisualizer::Impl::settings
shader
Combobox* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::shader
Definition at line 339 of file O3DVisualizer.cpp.
show_axes
Checkbox* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::show_axes
Definition at line 332 of file O3DVisualizer.cpp.
show_ground
Checkbox* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::show_ground
Definition at line 333 of file O3DVisualizer.cpp.
show_skybox
Checkbox* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::show_skybox
Definition at line 331 of file O3DVisualizer.cpp.
start_animation_clock_time_
double cloudViewer::visualization::visualizer::O3DVisualizer::Impl::start_animation_clock_time_ = 0.0
Definition at line 303 of file O3DVisualizer.cpp.
sun_color
ColorEdit* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::sun_color
Definition at line 350 of file O3DVisualizer.cpp.
sun_dir
VectorEdit* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::sun_dir
Definition at line 349 of file O3DVisualizer.cpp.
sun_follows_camera
Checkbox* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::sun_follows_camera
Definition at line 348 of file O3DVisualizer.cpp.
sun_intensity
Slider* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::sun_intensity
Definition at line 347 of file O3DVisualizer.cpp.
time_edit
NumberEdit* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::time_edit
Definition at line 366 of file O3DVisualizer.cpp.
time_panel
EmptyIfHiddenVert* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::time_panel
Definition at line 364 of file O3DVisualizer.cpp.
time_slider
Slider* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::time_slider
Definition at line 365 of file O3DVisualizer.cpp.
ui_state_
UIState cloudViewer::visualization::visualizer::O3DVisualizer::Impl::ui_state_
Definition at line 297 of file O3DVisualizer.cpp.
use_ibl
Checkbox* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::use_ibl
Definition at line 343 of file O3DVisualizer.cpp.
use_sun
Checkbox* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::use_sun
Definition at line 344 of file O3DVisualizer.cpp.
view_mouse_mode
SceneWidget::Controls cloudViewer::visualization::visualizer::O3DVisualizer::Impl::view_mouse_mode
Definition at line 322 of file O3DVisualizer.cpp.
view_panel
Vert* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::view_panel
Definition at line 321 of file O3DVisualizer.cpp.
was_using_sun_follows_cam_
bool cloudViewer::visualization::visualizer::O3DVisualizer::Impl::was_using_sun_follows_cam_ = false
Definition at line 299 of file O3DVisualizer.cpp.
window_
Window* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::window_ = nullptr
Definition at line 307 of file O3DVisualizer.cpp.
wireframe_mode
Checkbox* cloudViewer::visualization::visualizer::O3DVisualizer::Impl::wireframe_mode
Definition at line 335 of file O3DVisualizer.cpp.
wireframe_objects_
std::vector<DrawObject> cloudViewer::visualization::visualizer::O3DVisualizer::Impl::wireframe_objects_
Definition at line 288 of file O3DVisualizer.cpp.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/visualizer/O3DVisualizer.cpp