ACloudViewer: TransformInfo Struct Reference
TransformInfo Struct Reference
#include <ecvDrawContext.h>
Classes
struct RotateParam
Public Member Functions
void setPostion (const CCVector3 &pos)
bool isApplyTransform () const
void setTransformation (const ccGLMatrixd &transform, bool updateTranslation=true, bool useEuler=false)
void setTransformation (const ccGLMatrix &transform, bool updateTranslation=true, bool useEuler=true)
void setRotation (double zAngle, double yAngle, double xAngle)
void setRotation (double zyxAngle[3])
void setRotation (double angle, double x, double y, double z)
void setRotation (double angle, const CCVector3 &axis)
void setRotation (double angle, const CCVector3d &axis)
void setScale (const CCVector3 &scale)
void setTranslationStart (const CCVector3 &trans)
void setTranslationEnd (const CCVector3 &trans)
Public Attributes
RotateParam rotateParam
bool isRotate = false
bool applyEuler = true
bool isScale = false
bool isTranslate = false
bool isPositionChanged = false
double quaternion [4]
CCVector3d eulerZYX
CCVector3 scaleXYZ
the x y z scale
CCVector3 transVecStart
CCVector3 transVecEnd
CCVector3 position
Detailed Description
Definition at line 200 of file ecvDrawContext.h.
Member Function Documentation
isApplyTransform()
bool TransformInfo::isApplyTransform () const inline
Definition at line 230 of file ecvDrawContext.h.
setPostion()
void TransformInfo::setPostion (const CCVector3 & pos) inline
Definition at line 225 of file ecvDrawContext.h.
References position.
setRotation() [1/5]
void TransformInfo::setRotation (double angle, const CCVector3 & axis) inline
Definition at line 292 of file ecvDrawContext.h.
References TransformInfo::RotateParam::angle, and TransformInfo::RotateParam::rotAxis.
setRotation() [2/5]
void TransformInfo::setRotation (double angle, const CCVector3d & axis) inline
Definition at line 298 of file ecvDrawContext.h.
References TransformInfo::RotateParam::angle, Vector3Tpl< PointCoordinateType >::fromArray(), TransformInfo::RotateParam::rotAxis, and Tuple3Tpl< Type >::u.
setRotation() [3/5]
void TransformInfo::setRotation (double angle, double x, double y, double z) inline
Definition at line 289 of file ecvDrawContext.h.
setRotation() [4/5]
void TransformInfo::setRotation (double zAngle, double yAngle, double xAngle) inline
Definition at line 278 of file ecvDrawContext.h.
setRotation() [5/5]
void TransformInfo::setRotation (double zyxAngle[3]) inline
Definition at line 285 of file ecvDrawContext.h.
setScale()
void TransformInfo::setScale (const CCVector3 & scale) inline
Definition at line 305 of file ecvDrawContext.h.
Referenced by ccPointPair::drawMeOnly(), and ccTrace::drawMeOnly().
setTransformation() [1/2]
void TransformInfo::setTransformation (const ccGLMatrix & transform, bool updateTranslation = true, bool useEuler = true) inline
Definition at line 271 of file ecvDrawContext.h.
References ccGLMatrixTpl< T >::data().
setTransformation() [2/2]
void TransformInfo::setTransformation (const ccGLMatrixd & transform, bool updateTranslation = true, bool useEuler = false) inline
Definition at line 234 of file ecvDrawContext.h.
References Vector3Tpl< PointCoordinateType >::fromArray(), ccGLMatrixTpl< T >::getParameters(), ccGLMatrixTpl< T >::getTranslationAsVec3D(), cloudViewer::RadiansToDegrees(), ccGLMatrixTpl< T >::toEulerAngle(), and Tuple3Tpl< Type >::u.
Referenced by ccPointPair::drawMeOnly().
setTranslationEnd()
void TransformInfo::setTranslationEnd (const CCVector3 & trans) inline
Definition at line 313 of file ecvDrawContext.h.
Referenced by ccPointPair::drawMeOnly().
setTranslationStart()
void TransformInfo::setTranslationStart (const CCVector3 & trans) inline
Definition at line 309 of file ecvDrawContext.h.
Referenced by ccPointPair::drawMeOnly(), and ccTrace::drawMeOnly().
Member Data Documentation
applyEuler
bool TransformInfo::applyEuler = true
Definition at line 208 of file ecvDrawContext.h.
eulerZYX
CCVector3d TransformInfo::eulerZYX
Definition at line 215 of file ecvDrawContext.h.
isPositionChanged
bool TransformInfo::isPositionChanged = false
Definition at line 211 of file ecvDrawContext.h.
isRotate
bool TransformInfo::isRotate = false
Definition at line 207 of file ecvDrawContext.h.
isScale
bool TransformInfo::isScale = false
Definition at line 209 of file ecvDrawContext.h.
isTranslate
bool TransformInfo::isTranslate = false
Definition at line 210 of file ecvDrawContext.h.
position
CCVector3 TransformInfo::position
Definition at line 223 of file ecvDrawContext.h.
quaternion
double TransformInfo::quaternion[4]
Definition at line 213 of file ecvDrawContext.h.
rotateParam
RotateParam TransformInfo::rotateParam
Definition at line 206 of file ecvDrawContext.h.
scaleXYZ
CCVector3 TransformInfo::scaleXYZ
the x y z scale
Definition at line 218 of file ecvDrawContext.h.
transVecEnd
CCVector3 TransformInfo::transVecEnd
Definition at line 221 of file ecvDrawContext.h.
transVecStart
CCVector3 TransformInfo::transVecStart
Definition at line 220 of file ecvDrawContext.h.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvDrawContext.h