ACloudViewer: Bitvec Struct Reference
Bitvec Struct Reference
Public Attributes
u32 iSize
u32 nSet
u32 iDivisor
union {
u8 aBitmap [((((512 -(3 *sizeof(u32)))/sizeof(Bitvec
*)) *sizeof(Bitvec *))/sizeof(u8))]
u32 aHash [((((512 -(3 *sizeof(u32)))/sizeof(Bitvec
*)) *sizeof(Bitvec *))/sizeof(u32))]
Bitvec * apSub [((((512 -(3 *sizeof(u32)))/sizeof(Bitvec
*)) *sizeof(Bitvec *))/sizeof(Bitvec *))]
} u
Detailed Description
Definition at line 48465 of file sqlite3.c.
Member Data Documentation
aBitmap
u8 Bitvec::aBitmap[((((512 -(3 *sizeof(u32)))/sizeof(Bitvec *)) *sizeof(Bitvec *))/sizeof(u8))]
Definition at line 48475 of file sqlite3.c.
Referenced by sqlite3BitvecClear(), sqlite3BitvecSet(), and sqlite3BitvecTestNotNull().
aHash
u32 Bitvec::aHash[((((512 -(3 *sizeof(u32)))/sizeof(Bitvec *)) *sizeof(Bitvec *))/sizeof(u32))]
Definition at line 48476 of file sqlite3.c.
Referenced by sqlite3BitvecClear(), sqlite3BitvecSet(), and sqlite3BitvecTestNotNull().
apSub
Bitvec* Bitvec::apSub[((((512 -(3 *sizeof(u32)))/sizeof(Bitvec *)) *sizeof(Bitvec *))/sizeof(Bitvec *))]
Definition at line 48477 of file sqlite3.c.
Referenced by sqlite3BitvecClear(), sqlite3BitvecSet(), and sqlite3BitvecTestNotNull().
iDivisor
u32 Bitvec::iDivisor
Definition at line 48470 of file sqlite3.c.
Referenced by sqlite3BitvecClear(), sqlite3BitvecSet(), and sqlite3BitvecTestNotNull().
iSize
u32 Bitvec::iSize
Definition at line 48466 of file sqlite3.c.
Referenced by sqlite3BitvecClear(), sqlite3BitvecCreate(), sqlite3BitvecSet(), and sqlite3BitvecTestNotNull().
nSet
u32 Bitvec::nSet
Definition at line 48467 of file sqlite3.c.
Referenced by sqlite3BitvecClear(), and sqlite3BitvecSet().
union { ... } Bitvec::u
Referenced by sqlite3BitvecClear(), sqlite3BitvecSet(), and sqlite3BitvecTestNotNull().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/SQLite/sqlite3.c