ACloudViewer: ecvDisplayTools::HotZone Struct Reference
ecvDisplayTools::HotZone Struct Reference
Precomputed stuff for the 'hot zone'.
#include <ecvDisplayTools.h>
Public Member Functions
HotZone (QWidget *win)
QRect rect (bool clickableItemsVisible, bool bubbleViewModeEnabled, bool fullScreenEnabled) const
Public Attributes
QFont font
int textHeight
int yTextBottomLineShift
unsigned char color [3]
QString bbv_label
QRect bbv_labelRect
int bbv_totalWidth
QString fs_label
QRect fs_labelRect
int fs_totalWidth
QString psi_label
QRect psi_labelRect
int psi_totalWidth
QString lsi_label
QRect lsi_labelRect
int lsi_totalWidth
int margin
int iconSize
QPoint topCorner
qreal pixelDeviceRatio
Detailed Description
Precomputed stuff for the 'hot zone'.
Definition at line 236 of file ecvDisplayTools.h.
Constructor & Destructor Documentation
HotZone()
ecvDisplayTools::HotZone::HotZone (QWidget * win) inline explicit
Definition at line 279 of file ecvDisplayTools.h.
References ecvColor::RgbTpl< Type >::b, color, ecvColor::defaultLabelBkgColor(), ecvColor::RgbTpl< Type >::g, and ecvColor::RgbTpl< Type >::r.
Member Function Documentation
rect()
QRect ecvDisplayTools::HotZone::rect (bool clickableItemsVisible, bool bubbleViewModeEnabled, bool fullScreenEnabled) const inline
Definition at line 341 of file ecvDisplayTools.h.
References max(), and min().
Member Data Documentation
bbv_label
QString ecvDisplayTools::HotZone::bbv_label
Definition at line 247 of file ecvDisplayTools.h.
bbv_labelRect
QRect ecvDisplayTools::HotZone::bbv_labelRect
Definition at line 249 of file ecvDisplayTools.h.
bbv_totalWidth
int ecvDisplayTools::HotZone::bbv_totalWidth
Definition at line 251 of file ecvDisplayTools.h.
color
unsigned char ecvDisplayTools::HotZone::color[3]
Definition at line 244 of file ecvDisplayTools.h.
font
QFont ecvDisplayTools::HotZone::font
Definition at line 238 of file ecvDisplayTools.h.
fs_label
QString ecvDisplayTools::HotZone::fs_label
Definition at line 254 of file ecvDisplayTools.h.
fs_labelRect
QRect ecvDisplayTools::HotZone::fs_labelRect
Definition at line 256 of file ecvDisplayTools.h.
fs_totalWidth
int ecvDisplayTools::HotZone::fs_totalWidth
Definition at line 258 of file ecvDisplayTools.h.
iconSize
int ecvDisplayTools::HotZone::iconSize
Definition at line 275 of file ecvDisplayTools.h.
lsi_label
QString ecvDisplayTools::HotZone::lsi_label
Definition at line 268 of file ecvDisplayTools.h.
lsi_labelRect
QRect ecvDisplayTools::HotZone::lsi_labelRect
Definition at line 270 of file ecvDisplayTools.h.
lsi_totalWidth
int ecvDisplayTools::HotZone::lsi_totalWidth
Definition at line 272 of file ecvDisplayTools.h.
margin
int ecvDisplayTools::HotZone::margin
Definition at line 274 of file ecvDisplayTools.h.
pixelDeviceRatio
qreal ecvDisplayTools::HotZone::pixelDeviceRatio
Definition at line 277 of file ecvDisplayTools.h.
psi_label
QString ecvDisplayTools::HotZone::psi_label
Definition at line 261 of file ecvDisplayTools.h.
psi_labelRect
QRect ecvDisplayTools::HotZone::psi_labelRect
Definition at line 263 of file ecvDisplayTools.h.
psi_totalWidth
int ecvDisplayTools::HotZone::psi_totalWidth
Definition at line 265 of file ecvDisplayTools.h.
textHeight
int ecvDisplayTools::HotZone::textHeight
Definition at line 240 of file ecvDisplayTools.h.
topCorner
QPoint ecvDisplayTools::HotZone::topCorner
Definition at line 276 of file ecvDisplayTools.h.
yTextBottomLineShift
int ecvDisplayTools::HotZone::yTextBottomLineShift
Definition at line 242 of file ecvDisplayTools.h.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvDisplayTools.h