ACloudViewer: ccTracePolylineTool::SegmentGLParams Struct Reference
ccTracePolylineTool::SegmentGLParams Struct Reference
Viewport parameters (used for picking)
#include <ecvTracePolylineTool.h>
Public Member Functions
SegmentGLParams ()
SegmentGLParams (int x, int y)
Public Attributes
ccGLCameraParameters params
CCVector2d clickPos
Detailed Description
Viewport parameters (used for picking)
Definition at line 81 of file ecvTracePolylineTool.h.
Constructor & Destructor Documentation
SegmentGLParams() [1/2]
ccTracePolylineTool::SegmentGLParams::SegmentGLParams () inline
Definition at line 82 of file ecvTracePolylineTool.h.
SegmentGLParams() [2/2]
ccTracePolylineTool::SegmentGLParams::SegmentGLParams (int x, int y)
Definition at line 42 of file ecvTracePolylineTool.cpp.
References clickPos, ecvDisplayTools::GetCurrentScreen(), ecvDisplayTools::GetGLCameraParameters(), params, ecvDisplayTools::ToVtkCoordinates(), Tuple3Tpl< Type >::x, x, Tuple3Tpl< Type >::y, and y.
Member Data Documentation
clickPos
CCVector2d ccTracePolylineTool::SegmentGLParams::clickPos
Definition at line 85 of file ecvTracePolylineTool.h.
Referenced by SegmentGLParams().
params
ccGLCameraParameters ccTracePolylineTool::SegmentGLParams::params
Definition at line 84 of file ecvTracePolylineTool.h.
Referenced by SegmentGLParams().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/app/ecvTracePolylineTool.h
/root/ACloudViewer/app/ecvTracePolylineTool.cpp