ACloudViewer: LasField Struct Reference
LasField Struct Reference
LAS field descriptor.
#include <LASFields.h>
Public Types
typedef QSharedPointer< LasField > Shared
Shared type.
Public Member Functions
LasField (LAS_FIELDS fieldType=LAS_INVALID, double defaultVal=0, double min=0.0, double max=-1.0, uint8_t _minPointFormat=0)
Default constructor.
virtual QString getName () const
Returns official field name.
double getSafeValue (unsigned index) const
Static Public Member Functions
static bool GetLASFields (ccPointCloud *cloud, std::vector< LasField > &fieldsToSave, uint8_t &minPointFormat)
Returns the (compliant) LAS fields in a point cloud.
static unsigned GetFormatRecordLength (uint8_t pointFormat)
static uint8_t VersionMinorForPointFormat (uint8_t pointFormat)
static uint8_t UpdateMinPointFormat (uint8_t minPointFormat, bool withRGB, bool withFWF, bool allowLegacyFormats=true)
static QString SanitizeString (const QString &str)
static QString DesanitizeString (const QString &str)
Public Attributes
LAS_FIELDS type
ccScalarField * sf
double firstValue
double minValue
double maxValue
double defaultValue
uint8_t minPointFormat
Detailed Description
LAS field descriptor.
Definition at line 89 of file LASFields.h.
Member Typedef Documentation
Shared
typedef QSharedPointer<LasField> LasField::Shared
Shared type.
Definition at line 91 of file LASFields.h.
Constructor & Destructor Documentation
LasField()
LasField::LasField (LAS_FIELDS fieldType = LAS_INVALID, double defaultVal = 0, double min = 0.0, double max = -1.0, uint8_t _minPointFormat = 0) inline
Default constructor.
Definition at line 94 of file LASFields.h.
Member Function Documentation
DesanitizeString()
static QString LasField::DesanitizeString (const QString & str) inline static
Definition at line 308 of file LASFields.h.
Referenced by LASFilter::loadFile().
GetFormatRecordLength()
static unsigned LasField::GetFormatRecordLength (uint8_t pointFormat) inline static
Definition at line 199 of file LASFields.h.
Referenced by LASFWFFilter::saveToFile().
GetLASFields()
static bool LasField::GetLASFields (ccPointCloud * cloud, std::vector< LasField > & fieldsToSave, uint8_t & minPointFormat) inline static
Returns the (compliant) LAS fields in a point cloud.
Definition at line 113 of file LASFields.h.
References ccScalarField::getGlobalShift(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getName(), getName(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), cloudViewer::PointCloudTpl< T >::getScalarField(), LAS_CLASSIF_KEYPOINT, LAS_CLASSIF_OVERLAP, LAS_CLASSIF_SYNTHETIC, LAS_CLASSIF_VALUE, LAS_CLASSIF_WITHHELD, LAS_CLASSIFICATION, LAS_FLIGHT_LINE_EDGE, LAS_INTENSITY, LAS_NUMBER_OF_RETURNS, LAS_POINT_SOURCE_ID, LAS_RETURN_NUMBER, LAS_SCAN_ANGLE_RANK, LAS_SCAN_DIRECTION, LAS_TIME, LAS_USER_DATA, max(), maxValue, minPointFormat, minValue, sf, and CVLog::Warning().
Referenced by LASFWFFilter::saveToFile(), and LASFilter::saveToFile().
getName()
virtual QString LasField::getName () const inline virtual
Returns official field name.
Reimplemented in ExtraLasField, and ExtraLasField.
Definition at line 108 of file LASFields.h.
References LAS_FIELD_NAMES, LAS_INVALID, and type.
Referenced by GetLASFields().
getSafeValue()
double LasField::getSafeValue (unsigned index) const inline
Definition at line 316 of file LASFields.h.
References defaultValue, cloudViewer::ScalarField::getValue(), sf, and cloudViewer::ScalarField::ValidValue().
SanitizeString()
static QString LasField::SanitizeString (const QString & str) inline static
Definition at line 296 of file LASFields.h.
UpdateMinPointFormat()
static uint8_t LasField::UpdateMinPointFormat (uint8_t minPointFormat, bool withRGB, bool withFWF, bool allowLegacyFormats = true) inline static
Definition at line 233 of file LASFields.h.
References max(), and minPointFormat.
Referenced by LASFWFFilter::saveToFile(), and LASFilter::saveToFile().
VersionMinorForPointFormat()
static uint8_t LasField::VersionMinorForPointFormat (uint8_t pointFormat) inline static
Definition at line 229 of file LASFields.h.
Referenced by LASFWFFilter::saveToFile().
Member Data Documentation
defaultValue
double LasField::defaultValue
Definition at line 337 of file LASFields.h.
Referenced by getSafeValue().
firstValue
double LasField::firstValue
Definition at line 334 of file LASFields.h.
maxValue
double LasField::maxValue
Definition at line 336 of file LASFields.h.
Referenced by GetLASFields().
minPointFormat
uint8_t LasField::minPointFormat
Definition at line 338 of file LASFields.h.
Referenced by GetLASFields(), and UpdateMinPointFormat().
minValue
double LasField::minValue
Definition at line 335 of file LASFields.h.
Referenced by GetLASFields().
sf
ccScalarField* LasField::sf
Definition at line 333 of file LASFields.h.
Referenced by ExtraLasField::ExtraLasField(), GetLASFields(), and getSafeValue().
type
LAS_FIELDS LasField::type
Definition at line 332 of file LASFields.h.
Referenced by getName(), and PrepareLASField().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/plugins/core/IO/qPDALIO/include/LASFields.h