ACloudViewer: cloudViewer::visualization::rendering::REHandle_abstract Struct Reference
cloudViewer::visualization::rendering::REHandle_abstract Struct Reference
#include <RendererHandle.h>
Public Member Functions
size_t Hash () const
bool operator== (const REHandle_abstract &other) const
bool operator!= (const REHandle_abstract &other) const
bool operator< (const REHandle_abstract &other) const
operator bool () const
REHandle_abstract ()
std::uint16_t GetId () const
Static Public Member Functions
static const char * TypeToString (EntityType type)
Public Attributes
const EntityType type = EntityType::None
Static Public Attributes
static const std::uint16_t kBadId = 0
Protected Member Functions
REHandle_abstract (const EntityType aType, const std::uint16_t aId)
Protected Attributes
std::uint16_t id = kBadId
Static Protected Attributes
static std::array< std::uint16_t, static_cast< size_t >EntityType::Count)> uid_table
Detailed Description
Definition at line 47 of file RendererHandle.h.
Constructor & Destructor Documentation
REHandle_abstract() [1/2]
cloudViewer::visualization::rendering::REHandle_abstract::REHandle_abstract () inline
Definition at line 71 of file RendererHandle.h.
REHandle_abstract() [2/2]
cloudViewer::visualization::rendering::REHandle_abstract::REHandle_abstract (const EntityType aType, const std::uint16_t aId) inline protected
Definition at line 76 of file RendererHandle.h.
Member Function Documentation
GetId()
std::uint16_t cloudViewer::visualization::rendering::REHandle_abstract::GetId () const inline
Definition at line 73 of file RendererHandle.h.
References id.
Referenced by cloudViewer::visualization::rendering::REHandle< entityType >::Concretize(), and cloudViewer::visualization::rendering::operator<<().
Hash()
size_t cloudViewer::visualization::rendering::REHandle_abstract::Hash () const inline
Definition at line 53 of file RendererHandle.h.
References type.
Referenced by operator<(), and cloudViewer::visualization::rendering::operator<<().
operator bool()
cloudViewer::visualization::rendering::REHandle_abstract::operator bool () const inline explicit
Definition at line 69 of file RendererHandle.h.
References kBadId.
operator!=()
bool cloudViewer::visualization::rendering::REHandle_abstract::operator!= (const REHandle_abstract & other) const inline
Definition at line 61 of file RendererHandle.h.
References operator==().
operator<()
bool cloudViewer::visualization::rendering::REHandle_abstract::operator< (const REHandle_abstract & other) const inline
Definition at line 65 of file RendererHandle.h.
References Hash().
operator==()
bool cloudViewer::visualization::rendering::REHandle_abstract::operator== (const REHandle_abstract & other) const inline
Definition at line 57 of file RendererHandle.h.
References id, and type.
Referenced by operator!=().
TypeToString()
const char * cloudViewer::visualization::rendering::REHandle_abstract::TypeToString (EntityType type) static
Definition at line 25 of file RendererHandle.cpp.
References cloudViewer::visualization::rendering::Count, and type.
Referenced by cloudViewer::visualization::rendering::FilamentResourceManager::Destroy(), and cloudViewer::visualization::rendering::operator<<().
Member Data Documentation
id
std::uint16_t cloudViewer::visualization::rendering::REHandle_abstract::id = kBadId protected
Definition at line 82 of file RendererHandle.h.
Referenced by GetId(), cloudViewer::visualization::rendering::REHandle< entityType >::operator=(), and operator==().
kBadId
const std::uint16_t cloudViewer::visualization::rendering::REHandle_abstract::kBadId = 0 static
Definition at line 50 of file RendererHandle.h.
Referenced by cloudViewer::visualization::rendering::REHandle< entityType >::Next(), and operator bool().
type
const EntityType cloudViewer::visualization::rendering::REHandle_abstract::type = EntityType::None
Definition at line 51 of file RendererHandle.h.
Referenced by cloudViewer::visualization::rendering::REHandle< entityType >::Concretize(), Hash(), cloudViewer::visualization::rendering::operator<<(), operator==(), and TypeToString().
uid_table
std::array< std::uint16_t, static_cast< size_t >EntityType::Count)> cloudViewer::visualization::rendering::REHandle_abstract::uid_table static protected
Definition at line 80 of file RendererHandle.h.
Referenced by cloudViewer::visualization::rendering::REHandle< entityType >::Next().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/RendererHandle.h
/root/ACloudViewer/libs/cloudViewer/visualization/rendering/RendererHandle.cpp