ACloudViewer: colmap::FOVCameraModel Struct Reference
colmap::FOVCameraModel Struct Reference
#include <camera_models.h>
Static Public Member Functions
static int InitializeModelId ()
static std::string InitializeModelName ()
static size_t InitializeNumParams ()
static std::string InitializeParamsInfo ()
static std::vector< size_t > InitializeFocalLengthIdxs ()
static std::vector< size_t > InitializePrincipalPointIdxs ()
static std::vector< size_t > InitializeExtraParamsIdxs ()
static std::vector< double > InitializeParams (const double focal_length, const size_t width, const size_t height)
template<typename T >
static void WorldToImage (const T *params, const T u, const T v, T *x, T *y)
template<typename T >
static void ImageToWorld (const T *params, const T x, const T y, T *u, T *v)
template<typename T >
static void Distortion (const T *extra_params, const T u, const T v, T *du, T *dv)
template<typename T >
static void Undistortion (const T *extra_params, const T u, const T v, T *du, T *dv)
Static Public Member Functions inherited from colmap::BaseCameraModel< FOVCameraModel >
static bool HasBogusParams (const std::vector< T > &params, const size_t width, const size_t height, const T min_focal_length_ratio, const T max_focal_length_ratio, const T max_extra_param)
static bool HasBogusFocalLength (const std::vector< T > &params, const size_t width, const size_t height, const T min_focal_length_ratio, const T max_focal_length_ratio)
static bool HasBogusPrincipalPoint (const std::vector< T > &params, const size_t width, const size_t height)
static bool HasBogusExtraParams (const std::vector< T > &params, const T max_extra_param)
static T ImageToWorldThreshold (const T *params, const T threshold)
static void IterativeUndistortion (const T *params, T *u, T *v)
Static Public Attributes
static const int kModelId = 7
static const size_t kNumParams = 5
static const int model_id
static const std::string model_name
static const size_t num_params
static const std::string params_info
static const std::vector< size_t > focal_length_idxs
static const std::vector< size_t > principal_point_idxs
static const std::vector< size_t > extra_params_idxs
Detailed Description
Definition at line 275 of file camera_models.h.
Member Function Documentation
Distortion()
template<typename T > void colmap::FOVCameraModel::Distortion (const T * extra_params, const T u, const T v, T * du, T * dv) static
Definition at line 1132 of file camera_models.h.
References e.
Referenced by colmap::SimpleRadialCameraModel::WorldToImage(), colmap::RadialCameraModel::WorldToImage(), colmap::OpenCVCameraModel::WorldToImage(), colmap::OpenCVFisheyeCameraModel::WorldToImage(), colmap::FullOpenCVCameraModel::WorldToImage(), WorldToImage(), colmap::SimpleRadialFisheyeCameraModel::WorldToImage(), colmap::RadialFisheyeCameraModel::WorldToImage(), and colmap::ThinPrismFisheyeCameraModel::WorldToImage().
ImageToWorld()
template<typename T > void colmap::FOVCameraModel::ImageToWorld (const T * params, const T x, const T y, T * u, T * v) static
Definition at line 1116 of file camera_models.h.
References Undistortion(), x, and y.
InitializeExtraParamsIdxs()
std::vector< size_t > colmap::FOVCameraModel::InitializeExtraParamsIdxs () inline static
Definition at line 1091 of file camera_models.h.
InitializeFocalLengthIdxs()
std::vector< size_t > colmap::FOVCameraModel::InitializeFocalLengthIdxs () inline static
Definition at line 1083 of file camera_models.h.
InitializeModelId()
static int colmap::FOVCameraModel::InitializeModelId () inline static
Definition at line 276 of file camera_models.h.
InitializeModelName()
static std::string colmap::FOVCameraModel::InitializeModelName () inline static
Definition at line 276 of file camera_models.h.
InitializeNumParams()
static size_t colmap::FOVCameraModel::InitializeNumParams () inline static
Definition at line 276 of file camera_models.h.
InitializeParams()
std::vector< double > colmap::FOVCameraModel::InitializeParams (const double focal_length, const size_t width, const size_t height) inline static
Definition at line 1093 of file camera_models.h.
References e, height, and width.
InitializeParamsInfo()
std::string colmap::FOVCameraModel::InitializeParamsInfo () inline static
Definition at line 1079 of file camera_models.h.
InitializePrincipalPointIdxs()
std::vector< size_t > colmap::FOVCameraModel::InitializePrincipalPointIdxs () inline static
Definition at line 1087 of file camera_models.h.
Undistortion()
template<typename T > void colmap::FOVCameraModel::Undistortion (const T * extra_params, const T u, const T v, T * du, T * dv) static
Definition at line 1172 of file camera_models.h.
References e.
Referenced by ImageToWorld().
WorldToImage()
template<typename T > void colmap::FOVCameraModel::WorldToImage (const T * params, const T u, const T v, T * x, T * y) static
Definition at line 1100 of file camera_models.h.
References Distortion(), x, and y.
Member Data Documentation
extra_params_idxs
const std::vector<size_t> colmap::FOVCameraModel::extra_params_idxs static
Definition at line 276 of file camera_models.h.
focal_length_idxs
const std::vector<size_t> colmap::FOVCameraModel::focal_length_idxs static
Definition at line 276 of file camera_models.h.
kModelId
const int colmap::FOVCameraModel::kModelId = 7 static
Definition at line 276 of file camera_models.h.
kNumParams
const size_t colmap::FOVCameraModel::kNumParams = 5 static
Definition at line 276 of file camera_models.h.
model_id
const int colmap::FOVCameraModel::model_id static
Definition at line 276 of file camera_models.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::CameraModelImageToWorld(), colmap::CameraModelImageToWorldThreshold(), and colmap::CameraModelWorldToImage().
model_name
const std::string colmap::FOVCameraModel::model_name static
Definition at line 276 of file camera_models.h.
num_params
const size_t colmap::FOVCameraModel::num_params static
Definition at line 276 of file camera_models.h.
params_info
const std::string colmap::FOVCameraModel::params_info static
Definition at line 276 of file camera_models.h.
principal_point_idxs
const std::vector<size_t> colmap::FOVCameraModel::principal_point_idxs static
Definition at line 276 of file camera_models.h.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/base/camera_models.h