ACloudViewer: ccInnerRect2DFinder::Rect Struct Reference
ccInnerRect2DFinder::Rect Struct Reference
2D rectangle
#include <ecvInnerRect2DFinder.h>
Public Member Functions
Rect ()
Rect (double _x0, double _y0, double _x1, double _y1)
double width () const
double height () const
double area () const
Public Attributes
double x0
double y0
double x1
double y1
Detailed Description
2D rectangle
Definition at line 28 of file ecvInnerRect2DFinder.h.
Constructor & Destructor Documentation
Rect() [1/2]
ccInnerRect2DFinder::Rect::Rect () inline
Definition at line 29 of file ecvInnerRect2DFinder.h.
Rect() [2/2]
ccInnerRect2DFinder::Rect::Rect (double _x0, double _y0, double _x1, double _y1) inline
Definition at line 30 of file ecvInnerRect2DFinder.h.
Member Function Documentation
area()
double ccInnerRect2DFinder::Rect::area (void) const inline
Definition at line 37 of file ecvInnerRect2DFinder.h.
References height(), and width().
Referenced by ccInnerRect2DFinder::findBiggestRect().
height()
double ccInnerRect2DFinder::Rect::height () const inline
Definition at line 36 of file ecvInnerRect2DFinder.h.
References y0, and y1.
Referenced by area(), and ccInnerRect2DFinder::process().
width()
double ccInnerRect2DFinder::Rect::width () const inline
Definition at line 35 of file ecvInnerRect2DFinder.h.
References x0, and x1.
Referenced by area(), and ccInnerRect2DFinder::process().
Member Data Documentation
x0
double ccInnerRect2DFinder::Rect::x0
Definition at line 33 of file ecvInnerRect2DFinder.h.
Referenced by ccInnerRect2DFinder::init(), ccInnerRect2DFinder::process(), and width().
x1
double ccInnerRect2DFinder::Rect::x1
Definition at line 33 of file ecvInnerRect2DFinder.h.
Referenced by ccInnerRect2DFinder::init(), ccInnerRect2DFinder::process(), and width().
y0
double ccInnerRect2DFinder::Rect::y0
Definition at line 33 of file ecvInnerRect2DFinder.h.
Referenced by height(), ccInnerRect2DFinder::init(), and ccInnerRect2DFinder::process().
y1
double ccInnerRect2DFinder::Rect::y1
Definition at line 33 of file ecvInnerRect2DFinder.h.
Referenced by height(), ccInnerRect2DFinder::init(), and ccInnerRect2DFinder::process().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/app/ecvInnerRect2DFinder.h