ACloudViewer: XForm4x4< Real > Struct Template Reference
XForm4x4< Real > Struct Template Reference
#include <Geometry.h>
Public Member Functions
XForm4x4 (void)
Real & operator() (int i, int j)
const Real & operator() (int i, int j) const
template<class _Real >
Point3D< _Real > operator* (const Point3D< _Real > &p) const
XForm4x4 operator* (const XForm4x4 &m) const
XForm4x4 transpose (void) const
Real subDeterminant (int i, int j) const
Real determinant (void) const
XForm4x4 inverse (void) const
Static Public Member Functions
static XForm4x4 Identity (void)
Public Attributes
Real coords [4][4]
Detailed Description
template<class Real>
struct XForm4x4< Real >
Definition at line 116 of file Geometry.h.
Constructor & Destructor Documentation
XForm4x4()
template<class Real > XForm4x4< Real >::XForm4x4 (void) inline
Definition at line 119 of file Geometry.h.
References XForm4x4< Real >::coords.
Member Function Documentation
determinant()
template<class Real > Real XForm4x4< Real >::determinant (void) const inline
Definition at line 157 of file Geometry.h.
References XForm4x4< Real >::coords, and XForm4x4< Real >::subDeterminant().
Referenced by XForm4x4< Real >::inverse().
Identity()
template<class Real > static XForm4x4 XForm4x4< Real >::Identity (void) inline static
Definition at line 120 of file Geometry.h.
inverse()
template<class Real > XForm4x4 XForm4x4< Real >::inverse (void) const inline
Definition at line 158 of file Geometry.h.
References XForm4x4< Real >::coords, XForm4x4< Real >::determinant(), and XForm4x4< Real >::subDeterminant().
Referenced by operator*().
operator()() [1/2]
template<class Real > Real& XForm4x4< Real >::operator() (int i, int j) inline
Definition at line 126 of file Geometry.h.
References XForm4x4< Real >::coords.
operator()() [2/2]
template<class Real > const Real& XForm4x4< Real >::operator() (int i, int j) const inline
Definition at line 127 of file Geometry.h.
References XForm4x4< Real >::coords.
operator*() [1/2]
template<class Real > template<class _Real > Point3D< _Real > XForm4x4< Real >::operator* (const Point3D< _Real > & p) const inline
Definition at line 128 of file Geometry.h.
References XForm4x4< Real >::coords.
operator*() [2/2]
template<class Real > XForm4x4 XForm4x4< Real >::operator* (const XForm4x4< Real > & m) const inline
Definition at line 138 of file Geometry.h.
References XForm4x4< Real >::coords.
subDeterminant()
template<class Real > Real XForm4x4< Real >::subDeterminant (int i, int j) const inline
Definition at line 150 of file Geometry.h.
References XForm4x4< Real >::coords, and XForm3x3< Real >::determinant().
Referenced by XForm4x4< Real >::determinant(), and XForm4x4< Real >::inverse().
transpose()
template<class Real > XForm4x4 XForm4x4< Real >::transpose (void) const inline
Definition at line 144 of file Geometry.h.
References XForm4x4< Real >::coords.
Referenced by operator*().
Member Data Documentation
coords
template<class Real > Real XForm4x4< Real >::coords[4][4]
Definition at line 118 of file Geometry.h.
Referenced by XForm4x4< Real >::determinant(), XForm4x4< Real >::inverse(), XForm4x4< Real >::operator()(), XForm4x4< Real >::operator*(), XForm4x4< Real >::subDeterminant(), XForm4x4< Real >::transpose(), and XForm4x4< Real >::XForm4x4().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/Geometry.h