ACloudViewer: XForm3x3< Real > Struct Template Reference
XForm3x3< Real > Struct Template Reference
#include <Geometry.h>
Public Member Functions
XForm3x3 (void)
Real & operator() (int i, int j)
const Real & operator() (int i, int j) const
template<class _Real >
Point3D< _Real > operator* (const Point3D< _Real > &p) const
XForm3x3 operator* (const XForm3x3 &m) const
XForm3x3 transpose (void) const
Real subDeterminant (int i, int j) const
Real determinant (void) const
XForm3x3 inverse (void) const
Static Public Member Functions
static XForm3x3 Identity (void)
Public Attributes
Real coords [3][3]
Detailed Description
template<class Real>
struct XForm3x3< Real >
Definition at line 69 of file Geometry.h.
Constructor & Destructor Documentation
XForm3x3()
template<class Real > XForm3x3< Real >::XForm3x3 (void) inline
Definition at line 72 of file Geometry.h.
References XForm3x3< Real >::coords.
Member Function Documentation
determinant()
template<class Real > Real XForm3x3< Real >::determinant (void) const inline
Definition at line 105 of file Geometry.h.
References XForm3x3< Real >::coords, and XForm3x3< Real >::subDeterminant().
Referenced by XForm3x3< Real >::inverse(), and XForm4x4< Real >::subDeterminant().
Identity()
template<class Real > static XForm3x3 XForm3x3< Real >::Identity (void) inline static
Definition at line 73 of file Geometry.h.
inverse()
template<class Real > XForm3x3 XForm3x3< Real >::inverse (void) const inline
Definition at line 106 of file Geometry.h.
References XForm3x3< Real >::coords, XForm3x3< Real >::determinant(), and XForm3x3< Real >::subDeterminant().
operator()() [1/2]
template<class Real > Real& XForm3x3< Real >::operator() (int i, int j) inline
Definition at line 79 of file Geometry.h.
References XForm3x3< Real >::coords.
operator()() [2/2]
template<class Real > const Real& XForm3x3< Real >::operator() (int i, int j) const inline
Definition at line 80 of file Geometry.h.
References XForm3x3< Real >::coords.
operator*() [1/2]
template<class Real > template<class _Real > Point3D< _Real > XForm3x3< Real >::operator* (const Point3D< _Real > & p) const inline
Definition at line 81 of file Geometry.h.
References XForm3x3< Real >::coords.
operator*() [2/2]
template<class Real > XForm3x3 XForm3x3< Real >::operator* (const XForm3x3< Real > & m) const inline
Definition at line 87 of file Geometry.h.
References XForm3x3< Real >::coords.
subDeterminant()
template<class Real > Real XForm3x3< Real >::subDeterminant (int i, int j) const inline
Definition at line 99 of file Geometry.h.
References XForm3x3< Real >::coords.
Referenced by XForm3x3< Real >::determinant(), and XForm3x3< Real >::inverse().
transpose()
template<class Real > XForm3x3 XForm3x3< Real >::transpose (void) const inline
Definition at line 93 of file Geometry.h.
References XForm3x3< Real >::coords.
Member Data Documentation
coords
template<class Real > Real XForm3x3< Real >::coords[3][3]
Definition at line 71 of file Geometry.h.
Referenced by XForm3x3< Real >::determinant(), XForm3x3< Real >::inverse(), XForm3x3< Real >::operator()(), XForm3x3< Real >::operator*(), XForm3x3< Real >::subDeterminant(), XForm3x3< Real >::transpose(), and XForm3x3< Real >::XForm3x3().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/lib/PoissonRecon/Geometry.h