ACloudViewer: CommandSubsample Struct Reference
CommandSubsample Struct Reference
#include <ecvCommandLineCommands.h>
Public Member Functions
CommandSubsample ()
bool process (ccCommandLineInterface &cmd) override
Main process.
Public Member Functions inherited from ccCommandLineInterface::Command
Command (const QString &name, const QString &keyword)
Default constructor.
virtual ~Command ()=default
Additional Inherited Members
Public Types inherited from ccCommandLineInterface::Command
using Shared = QSharedPointer< Command >
Shared type.
Public Attributes inherited from ccCommandLineInterface::Command
QString m_name
Command name.
QString m_keyword
Command keyword.
Detailed Description
Definition at line 76 of file ecvCommandLineCommands.h.
Constructor & Destructor Documentation
CommandSubsample()
CommandSubsample::CommandSubsample ()
Definition at line 965 of file ecvCommandLineCommands.cpp.
Member Function Documentation
process()
bool CommandSubsample::process (ccCommandLineInterface & cmd) override virtual
Main process.
Implements ccCommandLineInterface::Command.
Definition at line 969 of file ecvCommandLineCommands.cpp.
References cloudViewer::CloudSamplingTools::SFModulationParams::a, ccCommandLineInterface::arguments(), ccCommandLineInterface::autoSaveMode(), cloudViewer::CloudSamplingTools::SFModulationParams::b, ccCommandLineInterface::clouds(), COMMAND_OPEN, COMMAND_SET_ACTIVE_SF, COMMAND_SUBSAMPLE, count, cloudViewer::ScalarField::countValidValues(), cloudViewer::CloudSamplingTools::SFModulationParams::enabled, ccCommandLineInterface::error(), ccCommandLineInterface::exportEntity(), cloudViewer::ScalarField::getMax(), cloudViewer::ScalarField::getMin(), cloudViewer::ScalarField::getName(), ccObject::getName(), cloudViewer::GreaterThanEpsilon(), cloudViewer::DgmOctree::MAX_OCTREE_LEVEL, NAN_VALUE, octreeLevel, OPTION_USE_ACTIVE_SF, ccPointCloud::partialClone(), ccCommandLineInterface::print(), ccCommandLineInterface::progressDialog(), cloudViewer::CloudSamplingTools::resampleCloudSpatially(), result, ccCommandLineInterface::silentMode(), cloudViewer::ReferenceCloud::size(), size, cloudViewer::CloudSamplingTools::subsampleCloudRandomly(), cloudViewer::CloudSamplingTools::subsampleCloudWithOctreeAtLevel(), cloudViewer::ScalarField::ValidValue(), ccCommandLineInterface::warning(), and ccCommandLineInterface::widgetParent().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/app/ecvCommandLineCommands.h
/root/ACloudViewer/app/ecvCommandLineCommands.cpp