ACloudViewer: colmap::InlierSupportMeasurer::Support Struct Reference
colmap::InlierSupportMeasurer::Support Struct Reference
#include <support_measurement.h>
Public Attributes
size_t num_inliers = 0
double residual_sum = std::numeric_limits<double>::max()
Detailed Description
Definition at line 20 of file support_measurement.h.
Member Data Documentation
num_inliers
size_t colmap::InlierSupportMeasurer::Support::num_inliers = 0
Definition at line 22 of file support_measurement.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::InlierSupportMeasurer::Compare(), and colmap::InlierSupportMeasurer::Evaluate().
residual_sum
double colmap::InlierSupportMeasurer::Support::residual_sum = std::numeric_limits<double>::max()
Definition at line 25 of file support_measurement.h.
Referenced by BOOST_AUTO_TEST_CASE(), colmap::InlierSupportMeasurer::Compare(), and colmap::InlierSupportMeasurer::Evaluate().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/Reconstruction/src/optim/support_measurement.h