ACloudViewer: LasWaveformSaver Struct Reference
LasWaveformSaver Struct Reference
#include <LasWaveformSaver.h>
Public Member Functions
LasWaveformSaver (const ccPointCloud &pointCloud) noexcept
void handlePoint (size_t index, laszip_point &point)
Detailed Description
Definition at line 35 of file LasWaveformSaver.h.
Constructor & Destructor Documentation
LasWaveformSaver()
LasWaveformSaver::LasWaveformSaver (const ccPointCloud & pointCloud) noexcept
Definition at line 14 of file LasWaveformSaver.cpp.
Member Function Documentation
handlePoint()
void LasWaveformSaver::handlePoint (size_t index, laszip_point & point)
Definition at line 20 of file LasWaveformSaver.cpp.
References ccWaveform::beamDir(), ccWaveform::byteCount(), ccWaveform::dataOffset(), ccWaveform::descriptorID(), ccWaveform::echoTime_ps(), cloudViewer::PointCloudTpl< T >::size(), LasDetails::EvlrHeader::SIZE, ccPointCloud::waveforms(), Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
The documentation for this struct was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qLASIO/include/LasWaveformSaver.h
/root/ACloudViewer/plugins/core/IO/qLASIO/src/LasWaveformSaver.cpp