ACloudViewer: ccRasterGrid Struct Reference
ccRasterGrid Struct Reference
Raster grid type.
#include <ecvRasterGrid.h>
Public Types
enum ExportableFields {
PER_CELL_VALUE , PER_CELL_COUNT , PER_CELL_MIN_VALUE , PER_CELL_MAX_VALUE ,
PER_CELL_AVG_VALUE , PER_CELL_VALUE_STD_DEV , PER_CELL_VALUE_RANGE , PER_CELL_MEDIAN_VALUE ,
PER_CELL_PERCENTILE_VALUE , PER_CELL_UNIQUE_COUNT_VALUE , PER_CELL_INVALID
}
Exportable fields.
enum ProjectionType {
PROJ_MINIMUM_VALUE = 0 , PROJ_AVERAGE_VALUE = 1 , PROJ_MAXIMUM_VALUE = 2 , PROJ_MEDIAN_VALUE = 3 ,
PROJ_INVERSE_VAR_VALUE = 4 , INVALID_PROJECTION_TYPE = 255
}
Types of projection.
enum class InterpolationType { NONE = 0 , DELAUNAY = 1 }
Types of interpolation.
enum EmptyCellFillOption {
LEAVE_EMPTY = 0 , FILL_MINIMUM_HEIGHT = 1 , FILL_MAXIMUM_HEIGHT = 2 , FILL_CUSTOM_HEIGHT = 3 ,
FILL_AVERAGE_HEIGHT = 4 , INTERPOLATE_DELAUNAY = 5 , KRIGING = 6
}
Option for handling empty cells.
using Row = std::vector< ccRasterCell >
Row.
using SF = std::vector< double >
Scalar field.
Public Member Functions
ccRasterGrid ()
Default constructor.
virtual ~ccRasterGrid ()
Destructor.
bool init (unsigned w, unsigned h, double gridStep, const CCVector3d &minCorner)
Initializes / resets the grid.
void clear ()
Clears the grid.
void reset ()
Resets the grid.
ccPointCloud * convertToCloud (const std::vector< ExportableFields > &exportedFields, bool interpolateSF, bool interpolateColors, bool resampleInputCloudXY, bool resampleInputCloudZ, ccGenericPointCloud *inputCloud, unsigned char Z, const ccBBox &box, bool fillEmptyCells, double emptyCellsHeight, bool exportToOriginalCS) const
Converts the grid to a cloud with scalar field(s)
bool fillWith (ccGenericPointCloud *cloud, unsigned char projectionDimension, ProjectionType projectionType, bool interpolateEmptyCells, ProjectionType sfInterpolation=INVALID_PROJECTION_TYPE, ecvProgressDialog *progressDialog=nullptr)
Fills the grid with a point cloud.
void fillEmptyCells (EmptyCellFillOption fillEmptyCellsStrategy, double customCellHeight=0)
Fills the empty cell (for all strategies but 'INTERPOLATE_DELAUNAY')
unsigned updateNonEmptyCellCount ()
Updates the number of non-empty cells.
void updateCellStats ()
Updates the statistics about the cells.
void setValid (bool state)
Sets valid.
bool isValid () const
Returns whether the grid is 'valid' or not.
std::pair< int, int > computeCellPos (const CCVector3 &P, unsigned char X, unsigned char Y) const
Computes the position of the cell that includes a given point.
CCVector2d computeCellCenter (int i, int j, unsigned char X, unsigned char Y) const
Computes the position of the center of a given cell.
Static Public Member Functions
static bool ComputeGridSize (unsigned char Z, const ccBBox &box, double gridStep, unsigned &width, unsigned &height)
Computes the raster size for a given bounding-box.
static QString GetDefaultFieldName (ExportableFields field)
Returns the default name of a given field.
static InterpolationType InterpolationTypeFromEmptyCellFillOption (EmptyCellFillOption option)
Public Attributes
std::vector< Row > rows
All cells.
std::vector< SF > scalarFields
Associated scalar fields.
unsigned width
Number of columns.
unsigned height
Number of rows.
double gridStep
Grid step ('pixel' size)
CCVector3d minCorner
Min corner (3D)
double minHeight
Min height (computed on the NON-EMPTY or INTERPOLATED cells)
double maxHeight
Max height (computed on the NON-EMPTY or INTERPOLATED cells)
double meanHeight
Average height (computed on the NON-EMPTY or INTERPOLATED cells)
unsigned nonEmptyCellCount
Number of NON-EMPTY cells.
unsigned validCellCount
Number of VALID cells.
bool hasColors
Whether the (average) colors are available or not.
bool valid
Whether the grid is valid/up-to-date.
Detailed Description
Raster grid type.
Definition at line 53 of file ecvRasterGrid.h.
Member Typedef Documentation
Row
using ccRasterGrid::Row = std::vector<ccRasterCell>
Row.
Definition at line 190 of file ecvRasterGrid.h.
SF
using ccRasterGrid::SF = std::vector<double>
Scalar field.
Definition at line 196 of file ecvRasterGrid.h.
Member Enumeration Documentation
EmptyCellFillOption
enum ccRasterGrid::EmptyCellFillOption
Option for handling empty cells.
Enumerator
LEAVE_EMPTY
FILL_MINIMUM_HEIGHT
FILL_MAXIMUM_HEIGHT
FILL_CUSTOM_HEIGHT
FILL_AVERAGE_HEIGHT
INTERPOLATE_DELAUNAY
KRIGING
Definition at line 137 of file ecvRasterGrid.h.
ExportableFields
enum ccRasterGrid::ExportableFields
Exportable fields.
Enumerator
PER_CELL_VALUE
PER_CELL_COUNT
PER_CELL_MIN_VALUE
PER_CELL_MAX_VALUE
PER_CELL_AVG_VALUE
PER_CELL_VALUE_STD_DEV
PER_CELL_VALUE_RANGE
PER_CELL_MEDIAN_VALUE
PER_CELL_PERCENTILE_VALUE
PER_CELL_UNIQUE_COUNT_VALUE
PER_CELL_INVALID
Definition at line 79 of file ecvRasterGrid.h.
InterpolationType
enum ccRasterGrid::InterpolationType strong
Types of interpolation.
Enumerator
NONE
DELAUNAY
Definition at line 122 of file ecvRasterGrid.h.
ProjectionType
enum ccRasterGrid::ProjectionType
Types of projection.
Enumerator
PROJ_MINIMUM_VALUE
PROJ_AVERAGE_VALUE
PROJ_MAXIMUM_VALUE
PROJ_MEDIAN_VALUE
PROJ_INVERSE_VAR_VALUE
INVALID_PROJECTION_TYPE
Definition at line 112 of file ecvRasterGrid.h.
Constructor & Destructor Documentation
ccRasterGrid()
ccRasterGrid::ccRasterGrid ()
Default constructor.
~ccRasterGrid()
virtual ccRasterGrid::~ccRasterGrid () virtual
Destructor.
Member Function Documentation
clear()
void ccRasterGrid::clear ()
Clears the grid.
computeCellCenter()
CCVector2d ccRasterGrid::computeCellCenter (int i, int j, unsigned char X, unsigned char Y) const inline
Computes the position of the center of a given cell.
Definition at line 181 of file ecvRasterGrid.h.
References Vector2Tpl< Type >::u, and X.
Referenced by define_ccRasterGrid().
computeCellPos()
std::pair<int, int> ccRasterGrid::computeCellPos (const CCVector3 & P, unsigned char X, unsigned char Y) const inline
Computes the position of the cell that includes a given point.
Definition at line 168 of file ecvRasterGrid.h.
References Vector3Tpl< double >::fromArray(), Tuple3Tpl< Type >::u, and X.
Referenced by define_ccRasterGrid().
ComputeGridSize()
static bool ccRasterGrid::ComputeGridSize (unsigned char Z, const ccBBox & box, double gridStep, unsigned & width, unsigned & height) static
Computes the raster size for a given bounding-box.
Referenced by define_ccRasterGrid().
convertToCloud()
ccPointCloud* ccRasterGrid::convertToCloud (const std::vector< ExportableFields > & exportedFields, bool interpolateSF, bool interpolateColors, bool resampleInputCloudXY, bool resampleInputCloudZ, ccGenericPointCloud * inputCloud, unsigned char Z, const ccBBox & box, bool fillEmptyCells, double emptyCellsHeight, bool exportToOriginalCS) const
Converts the grid to a cloud with scalar field(s)
Referenced by define_ccRasterGrid().
fillEmptyCells()
void ccRasterGrid::fillEmptyCells (EmptyCellFillOption fillEmptyCellsStrategy, double customCellHeight = 0)
Fills the empty cell (for all strategies but 'INTERPOLATE_DELAUNAY')
Referenced by define_ccRasterGrid().
fillWith()
bool ccRasterGrid::fillWith (ccGenericPointCloud * cloud, unsigned char projectionDimension, ProjectionType projectionType, bool interpolateEmptyCells, ProjectionType sfInterpolation = INVALID_PROJECTION_TYPE, ecvProgressDialog * progressDialog = nullptr)
Fills the grid with a point cloud.
Since version 2.8, we now use the "PixelIsArea" convention by default (as GDAL) This means that the height is computed at the center of the grid cell.
Referenced by define_ccRasterGrid().
GetDefaultFieldName()
static QString ccRasterGrid::GetDefaultFieldName (ExportableFields field) static
Returns the default name of a given field.
Referenced by define_ccRasterGrid().
init()
bool ccRasterGrid::init (unsigned w, unsigned h, double gridStep, const CCVector3d & minCorner)
Initializes / resets the grid.
InterpolationTypeFromEmptyCellFillOption()
static InterpolationType ccRasterGrid::InterpolationTypeFromEmptyCellFillOption (EmptyCellFillOption option) static
Converts the empty cells fill option to the corresponding interpolation type
isValid()
bool ccRasterGrid::isValid () const inline
Returns whether the grid is 'valid' or not.
Definition at line 165 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
reset()
void ccRasterGrid::reset ()
Resets the grid.
Referenced by define_ccRasterGrid().
setValid()
void ccRasterGrid::setValid (bool state) inline
Sets valid.
Definition at line 163 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
updateCellStats()
void ccRasterGrid::updateCellStats ()
Updates the statistics about the cells.
Referenced by define_ccRasterGrid().
updateNonEmptyCellCount()
unsigned ccRasterGrid::updateNonEmptyCellCount ()
Updates the number of non-empty cells.
Referenced by define_ccRasterGrid().
Member Data Documentation
gridStep
double ccRasterGrid::gridStep
Grid step ('pixel' size)
Definition at line 206 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
hasColors
bool ccRasterGrid::hasColors
Whether the (average) colors are available or not.
Definition at line 222 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
height
unsigned ccRasterGrid::height
Number of rows.
Definition at line 204 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
maxHeight
double ccRasterGrid::maxHeight
Max height (computed on the NON-EMPTY or INTERPOLATED cells)
Definition at line 213 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
meanHeight
double ccRasterGrid::meanHeight
Average height (computed on the NON-EMPTY or INTERPOLATED cells)
Definition at line 215 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
minCorner
CCVector3d ccRasterGrid::minCorner
Min corner (3D)
Definition at line 208 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
minHeight
double ccRasterGrid::minHeight
Min height (computed on the NON-EMPTY or INTERPOLATED cells)
Definition at line 211 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
nonEmptyCellCount
unsigned ccRasterGrid::nonEmptyCellCount
Number of NON-EMPTY cells.
Definition at line 217 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
rows
std::vector<Row> ccRasterGrid::rows
All cells.
Definition at line 193 of file ecvRasterGrid.h.
scalarFields
std::vector<SF> ccRasterGrid::scalarFields
Associated scalar fields.
Definition at line 199 of file ecvRasterGrid.h.
valid
bool ccRasterGrid::valid
Whether the grid is valid/up-to-date.
Definition at line 225 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
validCellCount
unsigned ccRasterGrid::validCellCount
Number of VALID cells.
Definition at line 219 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
width
unsigned ccRasterGrid::width
Number of columns.
Definition at line 202 of file ecvRasterGrid.h.
Referenced by define_ccRasterGrid().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/CV_db/include/ecvRasterGrid.h