ACloudViewer: CommandDist Struct Reference
CommandDist Struct Reference
#include <ecvCommandLineCommands.h>
Public Member Functions
CommandDist (bool cloud2meshDist, const QString &name, const QString &keyword)
bool process (ccCommandLineInterface &cmd) override
Main process.
Public Member Functions inherited from ccCommandLineInterface::Command
Command (const QString &name, const QString &keyword)
Default constructor.
virtual ~Command ()=default
Public Attributes
bool m_cloud2meshDist
Public Attributes inherited from ccCommandLineInterface::Command
QString m_name
Command name.
QString m_keyword
Command keyword.
Additional Inherited Members
Public Types inherited from ccCommandLineInterface::Command
using Shared = QSharedPointer< Command >
Shared type.
Detailed Description
Definition at line 264 of file ecvCommandLineCommands.h.
Constructor & Destructor Documentation
CommandDist()
CommandDist::CommandDist (bool cloud2meshDist, const QString & name, const QString & keyword)
Definition at line 3591 of file ecvCommandLineCommands.cpp.
Member Function Documentation
process()
bool CommandDist::process (ccCommandLineInterface & cmd) override virtual
Main process.
Implements ccCommandLineInterface::Command.
Definition at line 3597 of file ecvCommandLineCommands.cpp.
References ccComparisonDlg::applyAndExit(), ccCommandLineInterface::arguments(), ccCommandLineInterface::autoSaveMode(), CLEntityDesc::basename, ccComparisonDlg::cancelAndExit(), ccComparisonDlg::CLOUDCLOUD_DIST, ccComparisonDlg::CLOUDMESH_DIST, ccCommandLineInterface::clouds(), COMMAND_C2C_LOCAL_MODEL, COMMAND_C2C_SPLIT_XYZ, COMMAND_C2M_DIST_FLIP_NORMALS, COMMAND_C2X_MAX_DISTANCE, COMMAND_C2X_OCTREE_LEVEL, COMMAND_MAX_THREAD_COUNT, ccComparisonDlg::computeDistances(), ccCommandLineInterface::error(), ccCommandLineInterface::exportEntity(), ccComparisonDlg::initDialog(), ccCommandLineInterface::IsCommand(), m_cloud2meshDist, ccCommandLineInterface::meshes(), octreeLevel, ccCommandLineInterface::print(), ccCommandLineInterface::warning(), and ccCommandLineInterface::widgetParent().
Member Data Documentation
m_cloud2meshDist
bool CommandDist::m_cloud2meshDist
Definition at line 271 of file ecvCommandLineCommands.h.
Referenced by process().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/app/ecvCommandLineCommands.h
/root/ACloudViewer/app/ecvCommandLineCommands.cpp