ACloudViewer: cloudViewer::visualization::gui::FileDialog::Impl Struct Reference
cloudViewer::visualization::gui::FileDialog::Impl Struct Reference
Public Member Functions
const DirEntry & GetSelectedEntry ()
void UpdateDirectoryListing ()
std::string CalcCurrentDirectory () const
void UpdateOk ()
Public Attributes
Mode mode_
std::vector< DirEntry > entries_
std::shared_ptr< TextEdit > filename_
std::shared_ptr< Combobox > dirtree_
std::shared_ptr< ListView > filelist_
std::shared_ptr< Combobox > filter_
std::unordered_map< int, std::unordered_set< std::string > > filter_idx_2_filter
std::shared_ptr< Horiz > filter_row_
std::shared_ptr< Button > ok_
std::shared_ptr< Button > cancel_
std::function< void()> on_cancel_
std::function< void(const char *)> on_done_
Detailed Description
Definition at line 106 of file FileDialog.cpp.
Member Function Documentation
CalcCurrentDirectory()
std::string cloudViewer::visualization::gui::FileDialog::Impl::CalcCurrentDirectory () const inline
Definition at line 190 of file FileDialog.cpp.
References dirtree_.
Referenced by UpdateDirectoryListing().
GetSelectedEntry()
const DirEntry& cloudViewer::visualization::gui::FileDialog::Impl::GetSelectedEntry () inline
Definition at line 121 of file FileDialog.cpp.
References entries_, and filelist_.
UpdateDirectoryListing()
void cloudViewer::visualization::gui::FileDialog::Impl::UpdateDirectoryListing () inline
Definition at line 132 of file FileDialog.cpp.
References CalcCurrentDirectory(), entries_, filelist_, filename_, filter_, filter_idx_2_filter, cloudViewer::utility::filesystem::GetFileExtensionInLowerCase(), cloudViewer::utility::filesystem::GetFileNameWithoutDirectory(), cloudViewer::utility::filesystem::ListDirectory(), mode_, cloudViewer::visualization::gui::FileDialog::OPEN, and UpdateOk().
UpdateOk()
void cloudViewer::visualization::gui::FileDialog::Impl::UpdateOk () inline
Definition at line 207 of file FileDialog.cpp.
References filename_, and ok_.
Referenced by UpdateDirectoryListing().
Member Data Documentation
cancel_
std::shared_ptr<Button> cloudViewer::visualization::gui::FileDialog::Impl::cancel_
Definition at line 117 of file FileDialog.cpp.
dirtree_
std::shared_ptr<Combobox> cloudViewer::visualization::gui::FileDialog::Impl::dirtree_
Definition at line 110 of file FileDialog.cpp.
Referenced by CalcCurrentDirectory().
entries_
std::vector<DirEntry> cloudViewer::visualization::gui::FileDialog::Impl::entries_
Definition at line 108 of file FileDialog.cpp.
Referenced by GetSelectedEntry(), and UpdateDirectoryListing().
filelist_
std::shared_ptr<ListView> cloudViewer::visualization::gui::FileDialog::Impl::filelist_
Definition at line 111 of file FileDialog.cpp.
Referenced by GetSelectedEntry(), and UpdateDirectoryListing().
filename_
std::shared_ptr<TextEdit> cloudViewer::visualization::gui::FileDialog::Impl::filename_
Definition at line 109 of file FileDialog.cpp.
Referenced by UpdateDirectoryListing(), and UpdateOk().
filter_
std::shared_ptr<Combobox> cloudViewer::visualization::gui::FileDialog::Impl::filter_
Definition at line 112 of file FileDialog.cpp.
Referenced by UpdateDirectoryListing().
filter_idx_2_filter
std::unordered_map<int, std::unordered_set<std::string> > cloudViewer::visualization::gui::FileDialog::Impl::filter_idx_2_filter
Definition at line 114 of file FileDialog.cpp.
Referenced by UpdateDirectoryListing().
filter_row_
std::shared_ptr<Horiz> cloudViewer::visualization::gui::FileDialog::Impl::filter_row_
Definition at line 115 of file FileDialog.cpp.
mode_
Mode cloudViewer::visualization::gui::FileDialog::Impl::mode_
Definition at line 107 of file FileDialog.cpp.
Referenced by UpdateDirectoryListing().
ok_
std::shared_ptr<Button> cloudViewer::visualization::gui::FileDialog::Impl::ok_
Definition at line 116 of file FileDialog.cpp.
Referenced by UpdateOk().
on_cancel_
std::function<void()> cloudViewer::visualization::gui::FileDialog::Impl::on_cancel_
Definition at line 118 of file FileDialog.cpp.
on_done_
std::function<void(const char *)> cloudViewer::visualization::gui::FileDialog::Impl::on_done_
Definition at line 119 of file FileDialog.cpp.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/cloudViewer/visualization/gui/FileDialog.cpp