ACloudViewer: ccPointPairRegistrationDlg::EntityContext Struct Reference
ccPointPairRegistrationDlg::EntityContext Struct Reference
Original cloud context.
#include <ecvPointPairRegistrationDlg.h>
Public Member Functions
EntityContext (ccHObject *ent)
Default constructor.
void restore ()
Restores cloud original state.
Public Attributes
ccHObject * entity
bool wasVisible
bool wasEnabled
bool wasSelected
Detailed Description
Original cloud context.
Definition at line 149 of file ecvPointPairRegistrationDlg.h.
Constructor & Destructor Documentation
EntityContext()
ccPointPairRegistrationDlg::EntityContext::EntityContext (ccHObject * ent) explicit
Default constructor.
Definition at line 132 of file ecvPointPairRegistrationDlg.cpp.
Member Function Documentation
restore()
void ccPointPairRegistrationDlg::EntityContext::restore ()
Restores cloud original state.
Definition at line 138 of file ecvPointPairRegistrationDlg.cpp.
References ecvDisplayTools::GetMainScreen(), ecvDisplayTools::RedrawDisplay(), and ecvDisplayTools::SetRedrawRecursive().
Referenced by ccPointPairRegistrationDlg::EntityContexts::restoreAll().
Member Data Documentation
entity
ccHObject* ccPointPairRegistrationDlg::EntityContext::entity
Definition at line 156 of file ecvPointPairRegistrationDlg.h.
wasEnabled
bool ccPointPairRegistrationDlg::EntityContext::wasEnabled
Definition at line 158 of file ecvPointPairRegistrationDlg.h.
wasSelected
bool ccPointPairRegistrationDlg::EntityContext::wasSelected
Definition at line 159 of file ecvPointPairRegistrationDlg.h.
wasVisible
bool ccPointPairRegistrationDlg::EntityContext::wasVisible
Definition at line 157 of file ecvPointPairRegistrationDlg.h.
The documentation for this struct was generated from the following files:
/root/ACloudViewer/app/ecvPointPairRegistrationDlg.h
/root/ACloudViewer/app/ecvPointPairRegistrationDlg.cpp