ACloudViewer: CommandICP Struct Reference
CommandICP Struct Reference
#include <ecvCommandLineCommands.h>
Public Member Functions
CommandICP ()
bool process (ccCommandLineInterface &cmd) override
Main process.
Public Member Functions inherited from ccCommandLineInterface::Command
Command (const QString &name, const QString &keyword)
Default constructor.
virtual ~Command ()=default
Additional Inherited Members
Public Types inherited from ccCommandLineInterface::Command
using Shared = QSharedPointer< Command >
Shared type.
Public Attributes inherited from ccCommandLineInterface::Command
QString m_name
Command name.
QString m_keyword
Command keyword.
Detailed Description
Definition at line 318 of file ecvCommandLineCommands.h.
Constructor & Destructor Documentation
CommandICP()
CommandICP::CommandICP ()
Definition at line 4592 of file ecvCommandLineCommands.cpp.
Member Function Documentation
process()
bool CommandICP::process (ccCommandLineInterface & cmd) override virtual
Main process.
Implements ccCommandLineInterface::Command.
Definition at line 4595 of file ecvCommandLineCommands.cpp.
References ccCommandLineInterface::addTimestamp(), cloudViewer::ICPRegistrationTools::Parameters::adjustScale, ccHObject::applyGLTransformation_recursive(), ccCommandLineInterface::arguments(), ccCommandLineInterface::autoSaveMode(), CLEntityDesc::basename, ccCommandLineInterface::clouds(), COMMAND_ICP_ADJUST_SCALE, COMMAND_ICP_ENABLE_FARTHEST_REMOVAL, COMMAND_ICP_ITERATION_COUNT, COMMAND_ICP_MIN_ERROR_DIIF, COMMAND_ICP_OVERLAP, COMMAND_ICP_RANDOM_SAMPLING_LIMIT, COMMAND_ICP_REFERENCE_IS_FIRST, COMMAND_ICP_ROT, COMMAND_ICP_USE_DATA_SF_AS_WEIGHT, COMMAND_ICP_USE_MODEL_SF_AS_WEIGHT, COMMAND_MAX_THREAD_COUNT, cloudViewer::ICPRegistrationTools::Parameters::convType, QtCompat::endl(), ccCommandLineInterface::error(), ccCommandLineInterface::exportEntity(), cloudViewer::ICPRegistrationTools::Parameters::filterOutFarthestPoints, cloudViewer::ICPRegistrationTools::Parameters::finalOverlapRatio, CLEntityDesc::getEntity(), ccObject::getName(), cloudViewer::PointCloudTpl< T >::getNumberOfScalarFields(), ccRegistrationTools::ICP(), ccCommandLineInterface::IsCommand(), cloudViewer::ICPRegistrationTools::MAX_ERROR_CONVERGENCE, cloudViewer::ICPRegistrationTools::MAX_ITER_CONVERGENCE, cloudViewer::ICPRegistrationTools::Parameters::maxThreadCount, ccCommandLineInterface::meshes(), cloudViewer::ICPRegistrationTools::Parameters::minRMSDecrease, cloudViewer::ICPRegistrationTools::Parameters::nbMaxIterations, cloudViewer::ICPRegistrationTools::NO_NORMAL, cloudViewer::ICPRegistrationTools::Parameters::normalsMatching, ccCommandLineInterface::numericalPrecision(), OPTION_LAST, cloudViewer::t::geometry::path, ccCommandLineInterface::print(), cloudViewer::ICPRegistrationTools::Parameters::samplingLimit, ccPointCloud::setCurrentDisplayedScalarField(), std::swap(), ccHObjectCaster::ToPointCloud(), ccGLMatrixTpl< T >::toString(), e57::toString(), cloudViewer::ICPRegistrationTools::Parameters::transformationFilters, cloudViewer::ICPRegistrationTools::Parameters::useC2MSignedDistances, and ccCommandLineInterface::widgetParent().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/app/ecvCommandLineCommands.h
/root/ACloudViewer/app/ecvCommandLineCommands.cpp