ACloudViewer: LasWaveformLoader Struct Reference
LasWaveformLoader Struct Reference
#include <LasWaveformLoader.h>
Public Member Functions
LasWaveformLoader (const laszip_header_struct &laszipHeader, const QString &lasFilename, ccPointCloud &pointCloud)
void loadWaveform (ccPointCloud &pointCloud, const laszip_point &currentPoint) const
Public Attributes
unsigned fwfDataCount {0}
unsigned fwfDataOffset {0}
bool isPointFormatExtended {false}
ccPointCloud::FWFDescriptorSet descriptors
Detailed Description
Definition at line 35 of file LasWaveformLoader.h.
Constructor & Destructor Documentation
LasWaveformLoader()
LasWaveformLoader::LasWaveformLoader (const laszip_header_struct & laszipHeader, const QString & lasFilename, ccPointCloud & pointCloud)
Definition at line 61 of file LasWaveformLoader.cpp.
References cloudViewer::PointCloudTpl< T >::capacity(), descriptors, ccPointCloud::fwfData(), fwfDataCount, fwfDataOffset, LasDetails::EvlrHeader::isWaveFormDataPackets(), ParseWaveformDescriptorVlrs(), CVLog::Print(), LasDetails::EvlrHeader::recordLength, LasDetails::EvlrHeader::SIZE, CVLog::Warning(), and ccPointCloud::waveforms().
Member Function Documentation
loadWaveform()
void LasWaveformLoader::loadWaveform (ccPointCloud & pointCloud, const laszip_point & currentPoint) const
Definition at line 169 of file LasWaveformLoader.cpp.
References descriptors, fwfDataCount, fwfDataOffset, ccPointCloud::fwfDescriptors(), isPointFormatExtended, ccWaveform::setBeamDir(), ccWaveform::setDataDescription(), ccWaveform::setDescriptorID(), ccWaveform::setEchoTime_ps(), ccWaveform::setReturnIndex(), cloudViewer::PointCloudTpl< T >::size(), CVLog::Warning(), and ccPointCloud::waveforms().
Member Data Documentation
descriptors
ccPointCloud::FWFDescriptorSet LasWaveformLoader::descriptors
Definition at line 46 of file LasWaveformLoader.h.
Referenced by LasWaveformLoader(), and loadWaveform().
fwfDataCount
unsigned LasWaveformLoader::fwfDataCount {0}
Definition at line 43 of file LasWaveformLoader.h.
Referenced by LasWaveformLoader(), and loadWaveform().
fwfDataOffset
unsigned LasWaveformLoader::fwfDataOffset {0}
Definition at line 44 of file LasWaveformLoader.h.
Referenced by LasWaveformLoader(), and loadWaveform().
isPointFormatExtended
bool LasWaveformLoader::isPointFormatExtended {false}
Definition at line 45 of file LasWaveformLoader.h.
Referenced by loadWaveform().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qLASIO/include/LasWaveformLoader.h
/root/ACloudViewer/plugins/core/IO/qLASIO/src/LasWaveformLoader.cpp