ACloudViewer: CommandTreeIso Struct Reference
CommandTreeIso Struct Reference
qTreeIso command line processor
#include <qTreeIsoCommands.h>
Public Member Functions
CommandTreeIso ()
bool process (ccCommandLineInterface &cmd) override
Detailed Description
qTreeIso command line processor
Definition at line 59 of file qTreeIsoCommands.h.
Constructor & Destructor Documentation
CommandTreeIso()
CommandTreeIso::CommandTreeIso () inline
Definition at line 60 of file qTreeIsoCommands.h.
Member Function Documentation
process()
bool CommandTreeIso::process (ccCommandLineInterface & cmd) inline override
Definition at line 63 of file qTreeIsoCommands.h.
References COMMAND_DECIMATE_RESOLUTION1, COMMAND_DECIMATE_RESOLUTION2, COMMAND_K1, COMMAND_K2, COMMAND_LAMBDA1, COMMAND_LAMBDA2, COMMAND_MAX_GAP, COMMAND_RHO, COMMAND_VERTICAL_OVERLAP_WEIGHT, cloudViewer::utility::detail_::convert(), count, TreeIso::Final_seg_pcd(), TreeIso::Init_seg_pcd(), and TreeIso::Intermediate_seg_pcd().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/plugins/core/Standard/qTreeIso/include/qTreeIsoCommands.h