ACloudViewer: LasVlr Struct Reference
LasVlr Struct Reference
#include <LasVlr.h>
Public Member Functions
LasVlr ()=default
LasVlr (const laszip_header &header)
LasVlr (const LasVlr &rhs)
LasVlr & operator= (LasVlr rhs)
QString toString () const
laszip_U32 numVlrs () const
Static Public Member Functions
static void Swap (LasVlr &lhs, LasVlr &rhs) noexcept
Public Attributes
std::vector< laszip_vlr_struct > vlrs
std::vector< LasExtraScalarField > extraScalarFields
Detailed Description
Definition at line 37 of file LasVlr.h.
Constructor & Destructor Documentation
LasVlr() [1/3]
LasVlr::LasVlr () default
LasVlr() [2/3]
LasVlr::LasVlr (const laszip_header & header) explicit
Definition at line 20 of file LasVlr.cpp.
References LasDetails::CloneVlrInto(), LasDetails::IsExtraBytesVlr(), LasDetails::IsLaszipVlr(), numVlrs(), and vlrs.
LasVlr() [3/3]
LasVlr::LasVlr (const LasVlr & rhs)
Definition at line 49 of file LasVlr.cpp.
References LasDetails::CloneVlrInto(), numVlrs(), and vlrs.
Member Function Documentation
numVlrs()
laszip_U32 LasVlr::numVlrs () const inline
Definition at line 52 of file LasVlr.h.
References vlrs.
Referenced by LasVlr().
operator=()
LasVlr & LasVlr::operator= (LasVlr rhs)
Definition at line 43 of file LasVlr.cpp.
References Swap().
Swap()
void LasVlr::Swap (LasVlr & lhs, LasVlr & rhs) static noexcept
Definition at line 62 of file LasVlr.cpp.
References std::swap().
Referenced by operator=().
toString()
QString LasVlr::toString () const inline
Definition at line 47 of file LasVlr.h.
References vlrs.
Referenced by LasPlugin::LasPlugin().
Member Data Documentation
extraScalarFields
std::vector<LasExtraScalarField> LasVlr::extraScalarFields
Definition at line 121 of file LasVlr.h.
Referenced by LasMetadata::SaveMetadataInto(), and LasIOFilter::saveToFile().
vlrs
std::vector<laszip_vlr_struct> LasVlr::vlrs
Definition at line 120 of file LasVlr.h.
Referenced by LasVlr(), numVlrs(), LasMetadata::SaveMetadataInto(), and toString().
The documentation for this struct was generated from the following files:
/root/ACloudViewer/plugins/core/IO/qLASIO/include/LasVlr.h
/root/ACloudViewer/plugins/core/IO/qLASIO/src/LasVlr.cpp