ACloudViewer: LasCloudChunk Struct Reference
LasCloudChunk Struct Reference
Public Member Functions
LasCloudChunk ()
ccPointCloud * getLoadedCloud () const
bool hasColors () const
bool reserveSize (unsigned nbPoints)
void createFieldsToLoad (const IdList &extraFieldsToLoad, const StringList &extraNamesToLoad)
void addLasFieldsToCloud ()
Public Attributes
ccPointCloud * loadedCloud
std::vector< LasField::Shared > lasFields
unsigned size
Detailed Description
Definition at line 835 of file LASFilter.cpp.
Constructor & Destructor Documentation
LasCloudChunk()
LasCloudChunk::LasCloudChunk () inline
Definition at line 836 of file LASFilter.cpp.
Member Function Documentation
addLasFieldsToCloud()
void LasCloudChunk::addLasFieldsToCloud () inline
Definition at line 926 of file LASFilter.cpp.
References ccPointCloud::addScalarField(), ccColorScalesManager::GetDefaultScale(), ccColorScalesManager::GREY, ccPointCloud::hasColors(), ccPointCloud::hasDisplayedScalarField(), LAS_CLASSIF_KEYPOINT, LAS_CLASSIF_OVERLAP, LAS_CLASSIF_SYNTHETIC, LAS_CLASSIF_VALUE, LAS_CLASSIF_WITHHELD, LAS_CLASSIFICATION, LAS_EXTRA, LAS_FIELD_NAMES, LAS_INTENSITY, LAS_NUMBER_OF_RETURNS, LAS_RETURN_NUMBER, lasFields, loadedCloud, ccPointCloud::setCurrentDisplayedScalarField(), ccDrawableObject::showSF(), and CVLog::Warning().
createFieldsToLoad()
void LasCloudChunk::createFieldsToLoad (const IdList & extraFieldsToLoad, const StringList & extraNamesToLoad) inline
Definition at line 855 of file LASFilter.cpp.
References LAS_CLASSIF_KEYPOINT, LAS_CLASSIF_OVERLAP, LAS_CLASSIF_SYNTHETIC, LAS_CLASSIF_VALUE, LAS_CLASSIF_WITHHELD, LAS_CLASSIFICATION, LAS_FLIGHT_LINE_EDGE, LAS_INTENSITY, LAS_NUMBER_OF_RETURNS, LAS_POINT_SOURCE_ID, LAS_RETURN_NUMBER, LAS_SCAN_ANGLE_RANK, LAS_SCAN_DIRECTION, LAS_TIME, LAS_USER_DATA, lasFields, name, and s_lasOpenDlg().
Referenced by LASFilter::loadFile().
getLoadedCloud()
ccPointCloud* LasCloudChunk::getLoadedCloud () const inline
Definition at line 842 of file LASFilter.cpp.
References loadedCloud.
Referenced by LASFilter::loadFile().
hasColors()
bool LasCloudChunk::hasColors () const inline
Definition at line 844 of file LASFilter.cpp.
References ccPointCloud::hasColors(), and loadedCloud.
reserveSize()
bool LasCloudChunk::reserveSize (unsigned nbPoints) inline
Definition at line 846 of file LASFilter.cpp.
References loadedCloud, ccPointCloud::reserveThePointsTable(), and size.
Referenced by LASFilter::loadFile().
Member Data Documentation
lasFields
std::vector<LasField::Shared> LasCloudChunk::lasFields
Definition at line 839 of file LASFilter.cpp.
Referenced by addLasFieldsToCloud(), createFieldsToLoad(), and LASFilter::loadFile().
loadedCloud
ccPointCloud* LasCloudChunk::loadedCloud
Definition at line 838 of file LASFilter.cpp.
Referenced by addLasFieldsToCloud(), getLoadedCloud(), hasColors(), LASFilter::loadFile(), and reserveSize().
size
unsigned LasCloudChunk::size
Definition at line 840 of file LASFilter.cpp.
Referenced by reserveSize().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/plugins/core/IO/qPDALIO/src/LASFilter.cpp