ACloudViewer: EmptyPacketHeader Struct Reference
EmptyPacketHeader Struct Reference
Public Member Functions
void verify (unsigned bufferLength=0) const
void dump (int indent=0, std::ostream &os=std::cout) const
Public Attributes
const uint8_t packetType = EMPTY_PACKET
uint8_t reserved1 = 0
uint16_t packetLogicalLengthMinus1 = 0
Detailed Description
Definition at line 60 of file Packet.cpp.
Member Function Documentation
dump()
void EmptyPacketHeader::dump (int indent = 0, std::ostream & os = std::cout) const
Definition at line 721 of file Packet.cpp.
References QtCompat::endl(), and e57::space().
Referenced by e57::PacketReadCache::dump().
verify()
void EmptyPacketHeader::verify (unsigned bufferLength = 0) const
Verify that packet is correct type
Check packetLength is at least large enough to hold header
Check packet length is multiple of 4
Check actual packet length is large enough.
Definition at line 693 of file Packet.cpp.
References e57::E57_ERROR_BAD_CV_PACKET, E57_EXCEPTION2, e57::EMPTY_PACKET, and e57::toString().
Referenced by e57::PacketReadCache::readPacket().
Member Data Documentation
packetLogicalLengthMinus1
uint16_t EmptyPacketHeader::packetLogicalLengthMinus1 = 0
Definition at line 65 of file Packet.cpp.
Referenced by e57::PacketReadCache::readPacket().
packetType
const uint8_t EmptyPacketHeader::packetType = EMPTY_PACKET
Definition at line 62 of file Packet.cpp.
Referenced by e57::PacketReadCache::dump(), and e57::PacketReadCache::readPacket().
reserved1
uint8_t EmptyPacketHeader::reserved1 = 0
Definition at line 64 of file Packet.cpp.
The documentation for this struct was generated from the following file:
/root/ACloudViewer/plugins/core/IO/qE57IO/extern/libE57Format/src/Packet.cpp