ACloudViewer: Ray< T > Struct Template Reference
Ray< T > Struct Template Reference
Simple Ray structure.
#include <RayAndBox.h>
Public Member Functions
Ray (const Vector3Tpl< T > &rayAxis, const Vector3Tpl< T > &rayOrigin)
double radialSquareDistance (const Vector3Tpl< T > &P) const
double squareDistanceToOrigin (const Vector3Tpl< T > &P) const
void squareDistances (const Vector3Tpl< T > &P, double &radial, double &toOrigin) const
Public Attributes
Vector3Tpl< T > dir
Vector3Tpl< T > origin
Vector3Tpl< T > invDir
Tuple3i sign
Detailed Description
template<typename T>
struct Ray< T >
Simple Ray structure.
Definition at line 14 of file RayAndBox.h.
Constructor & Destructor Documentation
Ray()
template<typename T > Ray< T >::Ray (const Vector3Tpl< T > & rayAxis, const Vector3Tpl< T > & rayOrigin) inline
Definition at line 15 of file RayAndBox.h.
References Ray< T >::dir, Ray< T >::invDir, Vector3Tpl< Type >::normalize(), Ray< T >::sign, Tuple3Tpl< Type >::x, Tuple3Tpl< Type >::y, and Tuple3Tpl< Type >::z.
Member Function Documentation
radialSquareDistance()
template<typename T > double Ray< T >::radialSquareDistance (const Vector3Tpl< T > & P) const inline
Definition at line 25 of file RayAndBox.h.
References Vector3Tpl< Type >::cross(), Ray< T >::dir, Vector3Tpl< Type >::norm2d(), and Ray< T >::origin.
squareDistances()
template<typename T > void Ray< T >::squareDistances (const Vector3Tpl< T > & P, double & radial, double & toOrigin) const inline
Definition at line 35 of file RayAndBox.h.
References Vector3Tpl< Type >::cross(), Ray< T >::dir, Vector3Tpl< Type >::norm2d(), and Ray< T >::origin.
squareDistanceToOrigin()
template<typename T > double Ray< T >::squareDistanceToOrigin (const Vector3Tpl< T > & P) const inline
Definition at line 30 of file RayAndBox.h.
References Vector3Tpl< Type >::norm2d(), and Ray< T >::origin.
Member Data Documentation
dir
template<typename T > Vector3Tpl<T> Ray< T >::dir
Definition at line 43 of file RayAndBox.h.
Referenced by Ray< T >::radialSquareDistance(), Ray< T >::Ray(), and Ray< T >::squareDistances().
invDir
template<typename T > Vector3Tpl<T> Ray< T >::invDir
Definition at line 44 of file RayAndBox.h.
Referenced by AABB< T >::intersects(), and Ray< T >::Ray().
origin
template<typename T > Vector3Tpl<T> Ray< T >::origin
Definition at line 43 of file RayAndBox.h.
Referenced by AABB< T >::intersects(), Ray< T >::radialSquareDistance(), Ray< T >::squareDistances(), and Ray< T >::squareDistanceToOrigin().
sign
template<typename T > Tuple3i Ray< T >::sign
Definition at line 45 of file RayAndBox.h.
Referenced by AABB< T >::intersects(), and Ray< T >::Ray().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/core/include/RayAndBox.h