ACloudViewer: cloudViewer::io::ReadPointCloudOption Struct Reference
cloudViewer::io::ReadPointCloudOption Struct Reference
Optional parameters to ReadPointCloud.
#include <FileIO.h>
Public Member Functions
ReadPointCloudOption (std::string format="auto", bool remove_nan_points=false, bool remove_infinite_points=false, bool print_progress=false, std::function< bool(double)> update_progress={})
ReadPointCloudOption (std::function< bool(double)> up)
Public Attributes
std::string format
bool remove_nan_points
Whether to remove all points that have nan.
bool remove_infinite_points
Whether to remove all points that have +-inf.
bool print_progress
std::function< bool(double)> update_progress
Detailed Description
Optional parameters to ReadPointCloud.
Definition at line 39 of file FileIO.h.
Constructor & Destructor Documentation
ReadPointCloudOption() [1/2]
cloudViewer::io::ReadPointCloudOption::ReadPointCloudOption (std::string format = "auto", bool remove_nan_points = false, bool remove_infinite_points = false, bool print_progress = false, std::function< bool(double)> update_progress = {}) inline
Definition at line 40 of file FileIO.h.
ReadPointCloudOption() [2/2]
cloudViewer::io::ReadPointCloudOption::ReadPointCloudOption (std::function< bool(double)> up) inline
Definition at line 53 of file FileIO.h.
Member Data Documentation
format
std::string cloudViewer::io::ReadPointCloudOption::format
Specifies what format the contents of the file are (and what loader to use), default "auto" means to go off of file extension. Note: "auto" is incompatible when reading directly from memory.
Definition at line 60 of file FileIO.h.
Referenced by cloudViewer::io::ReadPointCloud(), and cloudViewer::t::io::ReadPointCloud().
print_progress
bool cloudViewer::io::ReadPointCloudOption::print_progress
Print progress to stdout about loading progress. Also see update_progress if you want to have your own progress indicators or to be able to cancel loading.
Definition at line 68 of file FileIO.h.
remove_infinite_points
bool cloudViewer::io::ReadPointCloudOption::remove_infinite_points
Whether to remove all points that have +-inf.
Definition at line 64 of file FileIO.h.
Referenced by cloudViewer::io::ReadPointCloud(), and cloudViewer::t::io::ReadPointCloud().
remove_nan_points
bool cloudViewer::io::ReadPointCloudOption::remove_nan_points
Whether to remove all points that have nan.
Definition at line 62 of file FileIO.h.
Referenced by cloudViewer::io::ReadPointCloud(), and cloudViewer::t::io::ReadPointCloud().
update_progress
std::function<bool(double)> cloudViewer::io::ReadPointCloudOption::update_progress
Callback to invoke as reading is progressing, parameter is percentage completion (0.-100.) return true indicates to continue loading, false means to try to stop loading and cleanup
Definition at line 72 of file FileIO.h.
Referenced by cloudViewer::visualization::GuiVisualizer::LoadGeometry(), cloudViewer::io::ReadPointCloud(), and cloudViewer::t::io::ReadPointCloud().
The documentation for this struct was generated from the following file:
/root/ACloudViewer/libs/eCV_io/include/FileIO.h