ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/metisLib/subdomains.c File Reference
subdomains.c File Reference
#include "metis.h"
Functions
void Random_KWayEdgeRefineMConn (CtrlType *ctrl, GraphType *graph, int nparts, float *tpwgts, float ubfactor, int npasses, int ffactor)
void Greedy_KWayEdgeBalanceMConn (CtrlType *ctrl, GraphType *graph, int nparts, float *tpwgts, float ubfactor, int npasses)
void PrintSubDomainGraph (GraphType *graph, int nparts, idxtype *where)
void ComputeSubDomainGraph (GraphType *graph, int nparts, idxtype *pmat, idxtype *ndoms)
void EliminateSubDomainEdges (CtrlType *ctrl, GraphType *graph, int nparts, float *tpwgts)
void MoveGroupMConn (CtrlType *ctrl, GraphType *graph, idxtype *ndoms, idxtype *pmat, int nparts, int to, int nind, idxtype *ind)
void EliminateComponents (CtrlType *ctrl, GraphType *graph, int nparts, float *tpwgts, float ubfactor)
void MoveGroup (CtrlType *ctrl, GraphType *graph, int nparts, int to, int gid, idxtype *ptr, idxtype *ind)
Function Documentation
ComputeSubDomainGraph()
void ComputeSubDomainGraph (GraphType * graph, int nparts, idxtype * pmat, idxtype * ndoms)
Definition at line 676 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, rinfodef::edegrees, idxset, rinfodef::ndegrees, graphdef::nvtxs, graphdef::rinfo, graphdef::where, and graphdef::xadj.
Referenced by EliminateSubDomainEdges(), Greedy_KWayEdgeBalanceMConn(), and Random_KWayEdgeRefineMConn().
EliminateComponents()
void EliminateComponents (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor)
Definition at line 1048 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, idxset, idxsum, idxwspacefree, idxwspacemalloc, INC_DEC, MoveGroup(), graphdef::nvtxs, graphdef::pwgts, graphdef::vwgt, graphdef::where, and graphdef::xadj.
EliminateSubDomainEdges()
void EliminateSubDomainEdges (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts)
Definition at line 721 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, ComputeSubDomainGraph(), GKfree, GKmalloc, idxamax, idxset, idxsum, idxwspacefree, idxwspacemalloc, ikeysort, INC_DEC, KeyValueType::key, LTERM, max(), min(), MoveGroupMConn(), graphdef::nvtxs, workspacedef::pmat, graphdef::pwgts, KeyValueType::val, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
Greedy_KWayEdgeBalanceMConn()
void Greedy_KWayEdgeBalanceMConn (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses)
Definition at line 312 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, graphdef::adjwgtsum, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, ComputeSubDomainGraph(), DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, rinfodef::id, idxamax, idxamin, idxset, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, workspacedef::pmat, PQueueDelete, PQueueFree, PQueueGetMax, PQueueInit, PQueueInsert, PQueueReset, PQueueUpdate, graphdef::pwgts, RandomPermute, graphdef::rinfo, SWAP, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.
MoveGroup()
void MoveGroup (CtrlType * ctrl, GraphType * graph, int nparts, int to, int gid, idxtype * ptr, idxtype * ind)
Definition at line 1174 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, rinfodef::id, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, graphdef::rinfo, SWAP, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by EliminateComponents().
MoveGroupMConn()
void MoveGroupMConn (CtrlType * ctrl, GraphType * graph, idxtype * ndoms, idxtype * pmat, int nparts, int to, int nind, idxtype * ind)
Definition at line 892 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, rinfodef::id, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, graphdef::rinfo, SWAP, graphdef::where, controldef::wspace, and graphdef::xadj.
Referenced by EliminateSubDomainEdges().
PrintSubDomainGraph()
void PrintSubDomainGraph (GraphType * graph, int nparts, idxtype * where)
Definition at line 625 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, idxsmalloc, max(), graphdef::nvtxs, and graphdef::xadj.
Random_KWayEdgeRefineMConn()
void Random_KWayEdgeRefineMConn (CtrlType * ctrl, GraphType * graph, int nparts, float * tpwgts, float ubfactor, int npasses, int ffactor)
Definition at line 22 of file subdomains.c.
References graphdef::adjncy, graphdef::adjwgt, ASSERT, BNDDelete, graphdef::bndind, BNDInsert, graphdef::bndptr, workspacedef::cdegree, CheckRInfo, ComputeCut, ComputeSubDomainGraph(), ComputeVolume, DBG_MOVEINFO, DBG_REFINE, controldef::dbglvl, edegreedef::ed, rinfodef::ed, workspacedef::edegrees, rinfodef::edegrees, rinfodef::id, idxamax, idxamin, idxsum, idxwspacefree, idxwspacemalloc, IFSET, INC_DEC, graphdef::mincut, graphdef::nbnd, rinfodef::ndegrees, NULL, graphdef::nvtxs, edegreedef::pid, workspacedef::pmat, graphdef::pwgts, RandomPermute, graphdef::rinfo, SWAP, graphdef::vwgt, graphdef::where, controldef::wspace, and graphdef::xadj.