ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/optim/support_measurement_test.cc File Reference
support_measurement_test.cc File Reference
#include "util/testing.h"
#include <unordered_set>
#include "optim/support_measurement.h"
#include "util/math.h"
Macros
#define TEST_NAME "optim/support_measurement"
Functions
BOOST_AUTO_TEST_CASE (TestInlierSupportMeasuremer)
BOOST_AUTO_TEST_CASE (TestMEstimatorSupportMeasurer)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "optim/support_measurement"
Definition at line 32 of file support_measurement_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (TestInlierSupportMeasuremer)
Definition at line 42 of file support_measurement_test.cc.
References colmap::InlierSupportMeasurer::Compare(), colmap::InlierSupportMeasurer::Evaluate(), colmap::InlierSupportMeasurer::Support::num_inliers, and colmap::InlierSupportMeasurer::Support::residual_sum.
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (TestMEstimatorSupportMeasurer)
Definition at line 70 of file support_measurement_test.cc.
References colmap::MEstimatorSupportMeasurer::Compare(), colmap::MEstimatorSupportMeasurer::Evaluate(), colmap::MEstimatorSupportMeasurer::Support::num_inliers, and colmap::MEstimatorSupportMeasurer::Support::score.