ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/util/threading_test.cc File Reference
threading_test.cc File Reference
#include "util/testing.h"
#include "util/logging.h"
#include "util/threading.h"
Macros
#define TEST_NAME "util/threading"
Functions
BOOST_AUTO_TEST_CASE (TestThreadWait)
BOOST_AUTO_TEST_CASE (TestThreadPause)
BOOST_AUTO_TEST_CASE (TestThreadPauseStop)
BOOST_AUTO_TEST_CASE (TestThreadRestart)
BOOST_AUTO_TEST_CASE (TestThreadValidSetup)
BOOST_AUTO_TEST_CASE (TestThreadInvalidSetup)
BOOST_AUTO_TEST_CASE (TestCallback)
BOOST_AUTO_TEST_CASE (TestDefaultCallback)
BOOST_AUTO_TEST_CASE (TestThreadPoolNoArgNoReturn)
BOOST_AUTO_TEST_CASE (TestThreadPoolArgNoReturn)
BOOST_AUTO_TEST_CASE (TestThreadPoolNoArgReturn)
BOOST_AUTO_TEST_CASE (TestThreadPoolArgReturn)
BOOST_AUTO_TEST_CASE (TestThreadPoolStop)
BOOST_AUTO_TEST_CASE (TestThreadPoolWait)
BOOST_AUTO_TEST_CASE (TestThreadPoolWaitEverytime)
BOOST_AUTO_TEST_CASE (TestThreadPoolGetThreadIndex)
BOOST_AUTO_TEST_CASE (TestJobQueueSingleProducerSingleConsumer)
BOOST_AUTO_TEST_CASE (TestJobQueueSingleProducerSingleConsumerMaxNumJobs)
BOOST_AUTO_TEST_CASE (TestJobQueueMultipleProducerSingleConsumer)
BOOST_AUTO_TEST_CASE (TestJobQueueSingleProducerMultipleConsumer)
BOOST_AUTO_TEST_CASE (TestJobQueueMultipleProducerMultipleConsumer)
BOOST_AUTO_TEST_CASE (TestJobQueueWait)
BOOST_AUTO_TEST_CASE (TestJobQueueStopProducer)
BOOST_AUTO_TEST_CASE (TestJobQueueStopConsumer)
BOOST_AUTO_TEST_CASE (TestJobQueueClear)
BOOST_AUTO_TEST_CASE (TestGetEffectiveNumThreads)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "util/threading"
Definition at line 32 of file threading_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/26]
BOOST_AUTO_TEST_CASE (TestCallback)
Definition at line 388 of file threading_test.cc.
References Run().
BOOST_AUTO_TEST_CASE() [2/26]
BOOST_AUTO_TEST_CASE (TestDefaultCallback)
Definition at line 451 of file threading_test.cc.
References Run().
BOOST_AUTO_TEST_CASE() [3/26]
BOOST_AUTO_TEST_CASE (TestGetEffectiveNumThreads)
Definition at line 894 of file threading_test.cc.
References colmap::GetEffectiveNumThreads().
BOOST_AUTO_TEST_CASE() [4/26]
BOOST_AUTO_TEST_CASE (TestJobQueueClear)
Definition at line 884 of file threading_test.cc.
References colmap::JobQueue< T >::Clear(), colmap::JobQueue< T >::Push(), and colmap::JobQueue< T >::Size().
BOOST_AUTO_TEST_CASE() [5/26]
BOOST_AUTO_TEST_CASE (TestJobQueueMultipleProducerMultipleConsumer)
Definition at line 764 of file threading_test.cc.
References colmap::JobQueue< T >::Pop(), colmap::JobQueue< T >::Push(), and colmap::JobQueue< T >::Size().
BOOST_AUTO_TEST_CASE() [6/26]
BOOST_AUTO_TEST_CASE (TestJobQueueMultipleProducerSingleConsumer)
Definition at line 697 of file threading_test.cc.
References colmap::JobQueue< T >::Pop(), colmap::JobQueue< T >::Push(), and colmap::JobQueue< T >::Size().
BOOST_AUTO_TEST_CASE() [7/26]
BOOST_AUTO_TEST_CASE (TestJobQueueSingleProducerMultipleConsumer)
Definition at line 729 of file threading_test.cc.
References colmap::JobQueue< T >::Pop(), colmap::JobQueue< T >::Push(), and colmap::JobQueue< T >::Size().
BOOST_AUTO_TEST_CASE() [8/26]
BOOST_AUTO_TEST_CASE (TestJobQueueSingleProducerSingleConsumer)
Definition at line 647 of file threading_test.cc.
References colmap::JobQueue< T >::Pop(), colmap::JobQueue< T >::Push(), and colmap::JobQueue< T >::Size().
BOOST_AUTO_TEST_CASE() [9/26]
BOOST_AUTO_TEST_CASE (TestJobQueueSingleProducerSingleConsumerMaxNumJobs)
Definition at line 672 of file threading_test.cc.
References colmap::JobQueue< T >::Pop(), colmap::JobQueue< T >::Push(), and colmap::JobQueue< T >::Size().
BOOST_AUTO_TEST_CASE() [10/26]
BOOST_AUTO_TEST_CASE (TestJobQueueStopConsumer)
Definition at line 857 of file threading_test.cc.
References colmap::JobQueue< T >::Job::IsValid(), colmap::JobQueue< T >::Pop(), colmap::JobQueue< T >::Push(), colmap::JobQueue< T >::Size(), and colmap::JobQueue< T >::Stop().
BOOST_AUTO_TEST_CASE() [11/26]
BOOST_AUTO_TEST_CASE (TestJobQueueStopProducer)
Definition at line 834 of file threading_test.cc.
References colmap::JobQueue< T >::Job::IsValid(), colmap::JobQueue< T >::Pop(), colmap::JobQueue< T >::Push(), colmap::JobQueue< T >::Size(), and colmap::JobQueue< T >::Stop().
BOOST_AUTO_TEST_CASE() [12/26]
BOOST_AUTO_TEST_CASE (TestJobQueueWait)
Definition at line 806 of file threading_test.cc.
References colmap::JobQueue< T >::Job::IsValid(), colmap::JobQueue< T >::Pop(), colmap::JobQueue< T >::Push(), colmap::JobQueue< T >::Size(), and colmap::JobQueue< T >::Wait().
BOOST_AUTO_TEST_CASE() [13/26]
BOOST_AUTO_TEST_CASE (TestThreadInvalidSetup)
Definition at line 345 of file threading_test.cc.
References Run().
BOOST_AUTO_TEST_CASE() [14/26]
BOOST_AUTO_TEST_CASE (TestThreadPause)
Definition at line 115 of file threading_test.cc.
References Run().
BOOST_AUTO_TEST_CASE() [15/26]
BOOST_AUTO_TEST_CASE (TestThreadPauseStop)
Definition at line 179 of file threading_test.cc.
References Run().
BOOST_AUTO_TEST_CASE() [16/26]
BOOST_AUTO_TEST_CASE (TestThreadPoolArgNoReturn)
Definition at line 507 of file threading_test.cc.
References colmap::ThreadPool::AddTask().
BOOST_AUTO_TEST_CASE() [17/26]
BOOST_AUTO_TEST_CASE (TestThreadPoolArgReturn)
Definition at line 541 of file threading_test.cc.
References colmap::ThreadPool::AddTask().
BOOST_AUTO_TEST_CASE() [18/26]
BOOST_AUTO_TEST_CASE (TestThreadPoolGetThreadIndex)
Definition at line 627 of file threading_test.cc.
References colmap::ThreadPool::AddTask(), colmap::ThreadPool::GetThreadIndex(), result, and colmap::ThreadPool::Wait().
BOOST_AUTO_TEST_CASE() [19/26]
BOOST_AUTO_TEST_CASE (TestThreadPoolNoArgNoReturn)
Definition at line 487 of file threading_test.cc.
References colmap::ThreadPool::AddTask().
BOOST_AUTO_TEST_CASE() [20/26]
BOOST_AUTO_TEST_CASE (TestThreadPoolNoArgReturn)
Definition at line 526 of file threading_test.cc.
References colmap::ThreadPool::AddTask().
BOOST_AUTO_TEST_CASE() [21/26]
BOOST_AUTO_TEST_CASE (TestThreadPoolStop)
Definition at line 561 of file threading_test.cc.
References colmap::ThreadPool::AddTask(), and colmap::ThreadPool::Stop().
BOOST_AUTO_TEST_CASE() [22/26]
BOOST_AUTO_TEST_CASE (TestThreadPoolWait)
Definition at line 583 of file threading_test.cc.
References colmap::ThreadPool::AddTask(), result, and colmap::ThreadPool::Wait().
BOOST_AUTO_TEST_CASE() [23/26]
BOOST_AUTO_TEST_CASE (TestThreadPoolWaitEverytime)
Definition at line 603 of file threading_test.cc.
References colmap::ThreadPool::AddTask(), and colmap::ThreadPool::Wait().
BOOST_AUTO_TEST_CASE() [24/26]
BOOST_AUTO_TEST_CASE (TestThreadRestart)
Definition at line 263 of file threading_test.cc.
References Run().
BOOST_AUTO_TEST_CASE() [25/26]
BOOST_AUTO_TEST_CASE (TestThreadValidSetup)
Definition at line 302 of file threading_test.cc.
References Run().
BOOST_AUTO_TEST_CASE() [26/26]
BOOST_AUTO_TEST_CASE (TestThreadWait)
Definition at line 78 of file threading_test.cc.
References Run().