ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/track_test.cc File Reference
track_test.cc File Reference
#include "util/testing.h"
#include "base/track.h"
Macros
#define TEST_NAME "base/track"
Functions
BOOST_AUTO_TEST_CASE (TestTrackElement)
BOOST_AUTO_TEST_CASE (TestDefault)
BOOST_AUTO_TEST_CASE (TestSetElements)
BOOST_AUTO_TEST_CASE (TestAddElement)
BOOST_AUTO_TEST_CASE (TestDeleteElement)
BOOST_AUTO_TEST_CASE (TestReserve)
BOOST_AUTO_TEST_CASE (TestCompress)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/track"
Definition at line 32 of file track_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/7]
BOOST_AUTO_TEST_CASE (TestAddElement)
Definition at line 70 of file track_test.cc.
References colmap::Track::AddElement(), colmap::Track::AddElements(), colmap::Track::Element(), colmap::Track::Elements(), colmap::TrackElement::image_id, colmap::Track::Length(), and colmap::TrackElement::point2D_idx.
BOOST_AUTO_TEST_CASE() [2/7]
BOOST_AUTO_TEST_CASE (TestCompress)
Definition at line 125 of file track_test.cc.
References colmap::Track::AddElement(), colmap::Track::Compress(), colmap::Track::DeleteElement(), and colmap::Track::Elements().
BOOST_AUTO_TEST_CASE() [3/7]
BOOST_AUTO_TEST_CASE (TestDefault)
Definition at line 45 of file track_test.cc.
References colmap::Track::Elements(), and colmap::Track::Length().
BOOST_AUTO_TEST_CASE() [4/7]
BOOST_AUTO_TEST_CASE (TestDeleteElement)
Definition at line 95 of file track_test.cc.
References colmap::Track::AddElement(), colmap::Track::DeleteElement(), colmap::Track::Element(), colmap::Track::Elements(), colmap::TrackElement::image_id, colmap::Track::Length(), and colmap::TrackElement::point2D_idx.
BOOST_AUTO_TEST_CASE() [5/7]
BOOST_AUTO_TEST_CASE (TestReserve)
Definition at line 119 of file track_test.cc.
References colmap::Track::Elements(), and colmap::Track::Reserve().
BOOST_AUTO_TEST_CASE() [6/7]
BOOST_AUTO_TEST_CASE (TestSetElements)
Definition at line 51 of file track_test.cc.
References colmap::Track::Element(), colmap::Track::Elements(), colmap::TrackElement::image_id, colmap::Track::Length(), colmap::TrackElement::point2D_idx, and colmap::Track::SetElements().
BOOST_AUTO_TEST_CASE() [7/7]
BOOST_AUTO_TEST_CASE (TestTrackElement)
Definition at line 39 of file track_test.cc.
References colmap::TrackElement::image_id, colmap::kInvalidImageId, colmap::kInvalidPoint2DIdx, and colmap::TrackElement::point2D_idx.