ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qCanupo/include/trainer.h File Reference
trainer.h File Reference
#include <vector>
#include <dlib/matrix.h>
#include <dlib/svm.h>
Classes
class LDATrainer
Functions
static void GramSchmidt (dlib::matrix< LDATrainer::sample_type, 0, 1 > &basis, LDATrainer::sample_type &newX)
Gram-Schmidt process to re-orthonormalise the basis.
static void ComputeReferencePoints (Classifier::Point2D &refpt_pos, Classifier::Point2D &refpt_neg, const std::vector< float > &proj1, const std::vector< float > &proj2, const std::vector< float > &labels, unsigned *_npos=0, unsigned *_nneg=0)
Compute pos. and neg. reference points.
static bool DilateClassifier (Classifier &classifier, std::vector< float > &proj1, std::vector< float > &proj2, const std::vector< float > &labels, const std::vector< LDATrainer::sample_type > &samples, LDATrainer &trainer, LDATrainer &orthoTrainer)
Function Documentation
ComputeReferencePoints()
static void ComputeReferencePoints (Classifier::Point2D & refpt_pos, Classifier::Point2D & refpt_neg, const std::vector< float > & proj1, const std::vector< float > & proj2, const std::vector< float > & labels, unsigned * _npos = 0, unsigned * _nneg = 0) static
Compute pos. and neg. reference points.
Definition at line 248 of file trainer.h.
Referenced by DilateClassifier(), and qCanupoTools::TrainClassifier().
DilateClassifier()
static bool DilateClassifier (Classifier & classifier, std::vector< float > & proj1, std::vector< float > & proj2, const std::vector< float > & labels, const std::vector< LDATrainer::sample_type > & samples, LDATrainer & trainer, LDATrainer & orthoTrainer) static
Experimental (same as Brodu's code): dilatation to highlight the internal data structure
Definition at line 279 of file trainer.h.
References Classifier::axisScaleRatio, ComputeReferencePoints(), Vector2Tpl< Type >::dot(), LDATrainer::m_weights, Vector2Tpl< Type >::normalize(), LDATrainer::predict(), Classifier::refPointNeg, Classifier::refPointPos, Classifier::weightsAxis1, Classifier::weightsAxis2, Vector2Tpl< Type >::x, and Vector2Tpl< Type >::y.
Referenced by qCanupoTools::TrainClassifier().
GramSchmidt()
static void GramSchmidt (dlib::matrix< LDATrainer::sample_type, 0, 1 > & basis, LDATrainer::sample_type & newX) static
Gram-Schmidt process to re-orthonormalise the basis.
Definition at line 215 of file trainer.h.
References dot(), and fabs().
Referenced by qCanupoTools::TrainClassifier().