ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/estimators/translation_transform_test.cc File Reference
translation_transform_test.cc File Reference
#include "util/testing.h"
#include <Eigen/Core>
#include "estimators/translation_transform.h"
#include "optim/ransac.h"
#include "util/random.h"
Macros
#define TEST_NAME "estimators/translation_transform"
Functions
BOOST_AUTO_TEST_CASE (TestEstimate)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "estimators/translation_transform"
Definition at line 32 of file translation_transform_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE()
BOOST_AUTO_TEST_CASE (TestEstimate)
Definition at line 43 of file translation_transform_test.cc.
References e, colmap::TranslationTransformEstimator< kDim >::Estimate(), colmap::RandomReal(), colmap::TranslationTransformEstimator< kDim >::Residuals(), and colmap::SetPRNGSeed().