ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/triangulation_test.cc File Reference
triangulation_test.cc File Reference
#include "util/testing.h"
#include <Eigen/Core>
#include "base/similarity_transform.h"
#include "base/triangulation.h"
Macros
#define TEST_NAME "base/triangulation"
Functions
BOOST_AUTO_TEST_CASE (TestTriangulatePoint)
BOOST_AUTO_TEST_CASE (TestCalculateTriangulationAngle)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/triangulation"
Definition at line 32 of file triangulation_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (TestCalculateTriangulationAngle)
Definition at line 80 of file triangulation_test.cc.
References colmap::CalculateTriangulationAngle(), colmap::CalculateTriangulationAngles(), and e.
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (TestTriangulatePoint)
Definition at line 42 of file triangulation_test.cc.
References e, colmap::SimilarityTransform3::Matrix(), and colmap::TriangulatePoint().