ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/feature/types_test.cc File Reference
types_test.cc File Reference
#include "util/testing.h"
#include <unordered_set>
#include "feature/types.h"
#include "util/math.h"
Macros
#define TEST_NAME "feature/types"
Functions
BOOST_AUTO_TEST_CASE (TestFeatureKeypoints)
BOOST_AUTO_TEST_CASE (TestFeatureDescriptors)
BOOST_AUTO_TEST_CASE (TestFeatureMatches)
BOOST_AUTO_TEST_CASE (TestFeatureMatchHashing)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "feature/types"
Definition at line 32 of file types_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (TestFeatureDescriptors)
Definition at line 215 of file types_test.cc.
References descriptors.
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (TestFeatureKeypoints)
Definition at line 42 of file types_test.cc.
References colmap::FeatureKeypoint::a11, colmap::FeatureKeypoint::a12, colmap::FeatureKeypoint::a21, colmap::FeatureKeypoint::a22, colmap::FeatureKeypoint::ComputeOrientation(), colmap::FeatureKeypoint::ComputeScale(), colmap::FeatureKeypoint::ComputeScaleX(), colmap::FeatureKeypoint::ComputeScaleY(), colmap::FeatureKeypoint::ComputeShear(), e, colmap::FeatureKeypoint::FromParameters(), M_PI, colmap::FeatureKeypoint::Rescale(), x, colmap::FeatureKeypoint::x, y, and colmap::FeatureKeypoint::y.
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (TestFeatureMatches)
Definition at line 227 of file types_test.cc.
References colmap::kInvalidPoint2DIdx, colmap::FeatureMatch::point2D_idx1, and colmap::FeatureMatch::point2D_idx2.
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (TestFeatureMatchHashing)
Definition at line 237 of file types_test.cc.
References cloudViewer::core::make_pair().