ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/undistortion_test.cc File Reference
undistortion_test.cc File Reference
#include "util/testing.h"
#include "base/pose.h"
#include "base/undistortion.h"
Macros
#define TEST_NAME "base/undistortion"
Functions
BOOST_AUTO_TEST_CASE (TestUndistortCamera)
BOOST_AUTO_TEST_CASE (TestUndistortCameraBlankPixels)
BOOST_AUTO_TEST_CASE (TestUndistortCameraNoBlankPixels)
BOOST_AUTO_TEST_CASE (TestUndistortReconstruction)
BOOST_AUTO_TEST_CASE (TestRectifyStereoCameras)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/undistortion"
Definition at line 32 of file undistortion_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/5]
BOOST_AUTO_TEST_CASE (TestRectifyStereoCameras)
Definition at line 216 of file undistortion_test.cc.
References e, colmap::EulerAnglesToRotationMatrix(), colmap::Camera::InitializeWithName(), colmap::RectifyStereoCameras(), colmap::RotationMatrixToQuaternion(), and colmap::Camera::SetCameraId().
BOOST_AUTO_TEST_CASE() [2/5]
BOOST_AUTO_TEST_CASE (TestUndistortCamera)
Definition at line 40 of file undistortion_test.cc.
References colmap::UndistortCameraOptions::blank_pixels, colmap::Camera::FocalLengthX(), colmap::Camera::FocalLengthY(), colmap::Camera::Height(), colmap::Camera::InitializeWithName(), colmap::UndistortCameraOptions::max_scale, colmap::Camera::ModelName(), colmap::Camera::Params(), colmap::Camera::PrincipalPointX(), colmap::Camera::PrincipalPointY(), colmap::UndistortCameraOptions::roi_max_x, colmap::UndistortCameraOptions::roi_max_y, colmap::UndistortCameraOptions::roi_min_x, colmap::UndistortCameraOptions::roi_min_y, colmap::UndistortCamera(), and colmap::Camera::Width().
BOOST_AUTO_TEST_CASE() [3/5]
BOOST_AUTO_TEST_CASE (TestUndistortCameraBlankPixels)
Definition at line 103 of file undistortion_test.cc.
References colmap::Bitmap::Allocate(), colmap::UndistortCameraOptions::blank_pixels, color, colmap::Bitmap::Fill(), colmap::Camera::FocalLengthX(), colmap::Camera::FocalLengthY(), colmap::Bitmap::GetPixel(), colmap::Camera::Height(), colmap::Bitmap::Height(), colmap::Camera::InitializeWithName(), colmap::Camera::ModelName(), colmap::Camera::Params(), colmap::Camera::PrincipalPointX(), colmap::Camera::PrincipalPointY(), colmap::UndistortImage(), colmap::Camera::Width(), colmap::Bitmap::Width(), x, and y.
BOOST_AUTO_TEST_CASE() [4/5]
BOOST_AUTO_TEST_CASE (TestUndistortCameraNoBlankPixels)
Definition at line 143 of file undistortion_test.cc.
References colmap::Bitmap::Allocate(), colmap::UndistortCameraOptions::blank_pixels, color, colmap::Bitmap::Fill(), colmap::Camera::FocalLengthX(), colmap::Camera::FocalLengthY(), colmap::Bitmap::GetPixel(), colmap::Camera::Height(), colmap::Bitmap::Height(), colmap::Camera::InitializeWithName(), colmap::Camera::ModelName(), colmap::Camera::Params(), colmap::Camera::PrincipalPointX(), colmap::Camera::PrincipalPointY(), colmap::UndistortImage(), colmap::Camera::Width(), colmap::Bitmap::Width(), x, and y.
BOOST_AUTO_TEST_CASE() [5/5]
BOOST_AUTO_TEST_CASE (TestUndistortReconstruction)
Definition at line 180 of file undistortion_test.cc.
References colmap::Reconstruction::AddCamera(), colmap::Reconstruction::AddImage(), colmap::Reconstruction::Cameras(), image, colmap::Reconstruction::Images(), colmap::Camera::InitializeWithName(), colmap::Camera::ModelName(), colmap::Camera::Params(), colmap::Reconstruction::RegisterImage(), colmap::Camera::SetCameraId(), patch::to_string(), and colmap::UndistortReconstruction().