ACloudViewer: /root/ACloudViewer/plugins/core/Standard/qPythonRuntime/src/Utilities.h File Reference
Utilities.h File Reference
#include <QString>
#include <Python.h>
#include <CVLog.h>
Classes
class ccLogger< level >
class PluginLogger< level >
Typedefs
using ccVerbose = ccLogger< CVLog::MessageLevelFlags::LOG_VERBOSE >
using ccPrint = ccLogger< CVLog::MessageLevelFlags::LOG_STANDARD >
using ccPrintHigh = ccLogger< CVLog::MessageLevelFlags::LOG_IMPORTANT >
using ccWarning = ccLogger< CVLog::MessageLevelFlags::LOG_WARNING >
using ccError = ccLogger< CVLog::MessageLevelFlags::LOG_ERROR >
using plgVerbose = PluginLogger< CVLog::LOG_VERBOSE >
using plgPrint = PluginLogger< CVLog::LOG_STANDARD >
using plgPrintHigh = PluginLogger< CVLog::LOG_IMPORTANT >
using plgWarning = PluginLogger< CVLog::LOG_WARNING >
using plgError = PluginLogger< CVLog::LOG_ERROR >
Functions
wchar_t * QStringToWcharArray (const QString &string)
Returns a newly allocated wchar_t array (null terminated) from a QString.
void LogPythonPath ()
Logs the PYTHON_PATH the log console of ACloudViewer.
void LogPythonHome ()
Logs the PYTHON_HOME the log console of ACloudViewer.
Typedef Documentation
ccError
using ccError = ccLogger<CVLog::MessageLevelFlags::LOG_ERROR>
Definition at line 74 of file Utilities.h.
ccPrint
using ccPrint = ccLogger<CVLog::MessageLevelFlags::LOG_STANDARD>
Definition at line 71 of file Utilities.h.
ccPrintHigh
using ccPrintHigh = ccLogger<CVLog::MessageLevelFlags::LOG_IMPORTANT>
Definition at line 72 of file Utilities.h.
ccVerbose
using ccVerbose = ccLogger<CVLog::MessageLevelFlags::LOG_VERBOSE>
Definition at line 70 of file Utilities.h.
ccWarning
using ccWarning = ccLogger<CVLog::MessageLevelFlags::LOG_WARNING>
Definition at line 73 of file Utilities.h.
plgError
using plgError = PluginLogger<CVLog::LOG_ERROR>
Definition at line 103 of file Utilities.h.
plgPrint
using plgPrint = PluginLogger<CVLog::LOG_STANDARD>
Definition at line 100 of file Utilities.h.
plgPrintHigh
using plgPrintHigh = PluginLogger<CVLog::LOG_IMPORTANT>
Definition at line 101 of file Utilities.h.
plgVerbose
using plgVerbose = PluginLogger<CVLog::LOG_VERBOSE>
Definition at line 99 of file Utilities.h.
plgWarning
using plgWarning = PluginLogger<CVLog::LOG_WARNING>
Definition at line 102 of file Utilities.h.
Function Documentation
LogPythonHome()
void LogPythonHome () inline
Logs the PYTHON_HOME the log console of ACloudViewer.
Definition at line 140 of file Utilities.h.
References CVLog::Print().
Referenced by PythonPlugin::setMainAppInterface().
LogPythonPath()
void LogPythonPath () inline
Logs the PYTHON_PATH the log console of ACloudViewer.
Definition at line 116 of file Utilities.h.
References CVLog::Print().
Referenced by PythonPlugin::setMainAppInterface().
QStringToWcharArray()
wchar_t* QStringToWcharArray (const QString & string) inline
Returns a newly allocated wchar_t array (null terminated) from a QString.
Definition at line 106 of file Utilities.h.
References size.
Referenced by PythonPluginCommand::Args::parseFrom(), and PythonConfig::pythonCompatiblePaths().