ACloudViewer: /root/ACloudViewer/libs/CVViewer/tools/ViewGeometry.cpp File Reference
ViewGeometry.cpp File Reference
#include "CloudViewer.h"
Functions
void PrintHelp ()
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 49 of file ViewGeometry.cpp.
References cloudViewer::visualization::Visualizer::AddGeometry(), ccMesh::ComputeVertexNormals(), ccPointCloud::CreateFromDepthImage(), cloudViewer::io::CreateImageFromFile(), cloudViewer::io::CreateLineSetFromFile(), cloudViewer::io::CreateMeshFromFile(), cloudViewer::io::CreatePointCloudFromFile(), cloudViewer::visualization::Visualizer::CreateVisualizerWindow(), cloudViewer::io::CreateVoxelGridFromFile(), cloudViewer::visualization::Visualizer::DestroyVisualizerWindow(), cloudViewer::camera::PinholeCameraParameters::extrinsic_, cloudViewer::utility::GetProgramOptionAsInt(), cloudViewer::utility::GetProgramOptionAsString(), cloudViewer::visualization::Visualizer::GetRenderOption(), cloudViewer::visualization::Visualizer::GetViewControl(), cloudViewer::visualization::Visualizer::HasGeometry(), height, cloudViewer::camera::PinholeCameraParameters::intrinsic_, LogWarning, mesh_ptr, cloudViewer::visualization::VisualizerWithCustomAnimation::Play(), cloudViewer::visualization::RenderOption::point_size_, pointcloud_ptr, PrintHelp(), cloudViewer::utility::ProgramOptionExists(), cloudViewer::io::ReadIJsonConvertible(), cloudViewer::visualization::Visualizer::Run(), cloudViewer::camera::PinholeCameraIntrinsic::SetIntrinsics(), cloudViewer::utility::SetVerbosityLevel(), cloudViewer::visualization::RenderOption::show_coordinate_frame_, cloudViewer::PointCloudTpl< T >::size(), and width.
PrintHelp()
void PrintHelp ()
Definition at line 10 of file ViewGeometry.cpp.
References LogInfo.
Referenced by main().