ACloudViewer: /root/ACloudViewer/libs/PCLEngine/VTKExtensions/Core/vtkPVXMLElement.cxx File Reference
vtkPVXMLElement.cxx File Reference
#include "vtkPVXMLElement.h"
#include "vtkCollection.h"
#include "vtkObjectFactory.h"
#include "vtkSmartPointer.h"
#include <ctype.h>
#include <sstream>
#include <string>
#include <vector>
Macros
#define SNPRINTF snprintf
Functions
vtkStandardNewMacro (vtkPVXMLElement)
static bool vtkIsSpace (const std::string &str)
template<class T >
int vtkPVXMLVectorAttributeParse (const char *str, int length, T *data)
Macro Definition Documentation
SNPRINTF
#define SNPRINTF snprintf
Definition at line 30 of file vtkPVXMLElement.cxx.
Function Documentation
vtkIsSpace()
static bool vtkIsSpace (const std::string & str) static
Definition at line 43 of file vtkPVXMLElement.cxx.
Referenced by vtkPVXMLElement::PrintXML().
vtkPVXMLVectorAttributeParse()
template<class T > int vtkPVXMLVectorAttributeParse (const char * str, int length, T * data)
Definition at line 484 of file vtkPVXMLElement.cxx.
References data.
Referenced by vtkPVXMLElement::GetCharacterDataAsVector(), and vtkPVXMLElement::GetVectorAttribute().
vtkStandardNewMacro()
vtkStandardNewMacro (vtkPVXMLElement)