ACloudViewer: /root/ACloudViewer/libs/Reconstruction/src/base/warp_test.cc File Reference
warp_test.cc File Reference
#include "util/testing.h"
#include "base/warp.h"
#include "util/random.h"
Macros
#define TEST_NAME "base/warp"
Functions
BOOST_AUTO_TEST_CASE (TestIdenticalCameras)
BOOST_AUTO_TEST_CASE (TestShiftedCameras)
BOOST_AUTO_TEST_CASE (TestWarpImageWithHomographyIdentity)
BOOST_AUTO_TEST_CASE (TestWarpImageWithHomographyTransposed)
BOOST_AUTO_TEST_CASE (TestWarpImageWithHomographyBetweenCamerasIdentity)
BOOST_AUTO_TEST_CASE (TestWarpImageWithHomographyBetweenCamerasTransposed)
BOOST_AUTO_TEST_CASE (TestResampleImageBilinear)
BOOST_AUTO_TEST_CASE (TestSmoothImage)
BOOST_AUTO_TEST_CASE (TestDownsampleImage)
Macro Definition Documentation
TEST_NAME
#define TEST_NAME "base/warp"
Definition at line 32 of file warp_test.cc.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/9]
BOOST_AUTO_TEST_CASE (TestDownsampleImage)
Definition at line 256 of file warp_test.cc.
References colmap::DownsampleImage(), e, and image.
BOOST_AUTO_TEST_CASE() [2/9]
BOOST_AUTO_TEST_CASE (TestIdenticalCameras)
Definition at line 91 of file warp_test.cc.
References colmap::Camera::InitializeWithName(), and colmap::WarpImageBetweenCameras().
BOOST_AUTO_TEST_CASE() [3/9]
BOOST_AUTO_TEST_CASE (TestResampleImageBilinear)
Definition at line 222 of file warp_test.cc.
References image, and colmap::ResampleImageBilinear().
BOOST_AUTO_TEST_CASE() [4/9]
BOOST_AUTO_TEST_CASE (TestShiftedCameras)
Definition at line 109 of file warp_test.cc.
References color, colmap::Bitmap::GetPixel(), colmap::Bitmap::Height(), colmap::Camera::InitializeWithName(), colmap::Camera::SetPrincipalPointX(), colmap::WarpImageBetweenCameras(), colmap::Bitmap::Width(), x, and y.
BOOST_AUTO_TEST_CASE() [5/9]
BOOST_AUTO_TEST_CASE (TestSmoothImage)
Definition at line 237 of file warp_test.cc.
References e, image, and colmap::SmoothImage().
BOOST_AUTO_TEST_CASE() [6/9]
BOOST_AUTO_TEST_CASE (TestWarpImageWithHomographyBetweenCamerasIdentity)
Definition at line 173 of file warp_test.cc.
References colmap::Bitmap::Allocate(), colmap::Camera::InitializeWithName(), and colmap::WarpImageWithHomographyBetweenCameras().
BOOST_AUTO_TEST_CASE() [7/9]
BOOST_AUTO_TEST_CASE (TestWarpImageWithHomographyBetweenCamerasTransposed)
Definition at line 197 of file warp_test.cc.
References colmap::Bitmap::Allocate(), colmap::Camera::InitializeWithName(), and colmap::WarpImageWithHomographyBetweenCameras().
BOOST_AUTO_TEST_CASE() [8/9]
BOOST_AUTO_TEST_CASE (TestWarpImageWithHomographyIdentity)
Definition at line 136 of file warp_test.cc.
References colmap::Bitmap::Allocate(), and colmap::WarpImageWithHomography().
BOOST_AUTO_TEST_CASE() [9/9]
BOOST_AUTO_TEST_CASE (TestWarpImageWithHomographyTransposed)
Definition at line 154 of file warp_test.cc.
References colmap::Bitmap::Allocate(), and colmap::WarpImageWithHomography().