ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/multilevelLib/wkkm_old.c File Reference
wkkm_old.c File Reference
#include "metis.h"
Functions
void Compute_Weights (CtrlType *ctrl, GraphType *graph, idxtype *w)
void transform_matrix (CtrlType *ctrl, GraphType *graph, idxtype *w, float *m_adjwgt)
void transform_matrix_half (CtrlType *ctrl, GraphType *graph, idxtype *w, float *m_adjwgt)
void pingpong (CtrlType *ctrl, GraphType *graph, int nparts, int chain_length, float *tpwgts, float ubfactor)
void Weighted_kernel_k_means (CtrlType *ctrl, GraphType *graph, int nparts, idxtype *w, float *m_adjwgt, float *tpwgts, float ubfactor)
int local_search (CtrlType *ctrl, GraphType *graph, int nparts, int chain_length, idxtype *w, float *m_adjwgt, float *tpwgts, float ubfactor)
void MLKKMRefine (CtrlType *ctrl, GraphType *orggraph, GraphType *graph, int nparts, int chain_length, float *tpwgts, float ubfactor)
Variables
int cutType
Function Documentation
Compute_Weights()
void Compute_Weights (CtrlType * ctrl, GraphType * graph, idxtype * w)
Definition at line 19 of file wkkm_old.c.
References graphdef::adjwgt, cutType, NULL, graphdef::nvtxs, RASSO, RCUT, and graphdef::xadj.
Referenced by pingpong().
local_search()
int local_search (CtrlType * ctrl, GraphType * graph, int nparts, int chain_length, idxtype * w, float * m_adjwgt, float * tpwgts, float ubfactor)
Definition at line 312 of file wkkm_old.c.
Referenced by pingpong().
MLKKMRefine()
void MLKKMRefine (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, int nparts, int chain_length, float * tpwgts, float ubfactor)
Definition at line 464 of file wkkm_old.c.
References graphdef::adjwgt, cleartimer, ComputeKWayPartitionParams, ComputeNCut(), ComputeRAsso(), cutType, DBG_TIME, controldef::dbglvl, graphdef::finer, graphdef::gdata, GKfree, idxsmalloc, IFSET, LTERM, NCUT, graphdef::nedges, NULL, graphdef::nvtxs, pingpong(), ProjectKWayPartition, controldef::ProjectTmr, result, starttimer, stoptimer, controldef::UncoarsenTmr, graphdef::vwgt, and graphdef::where.
Referenced by MLKKMPartitioning().
pingpong()
void pingpong (CtrlType * ctrl, GraphType * graph, int nparts, int chain_length, float * tpwgts, float ubfactor)
Definition at line 138 of file wkkm_old.c.
References Compute_Weights(), fmalloc, idxsmalloc, local_search(), MAXITERATIONS, graphdef::nedges, graphdef::nvtxs, transform_matrix(), and Weighted_kernel_k_means().
Referenced by MLKKMRefine().
transform_matrix()
void transform_matrix (CtrlType * ctrl, GraphType * graph, idxtype * w, float * m_adjwgt)
Definition at line 43 of file wkkm_old.c.
References graphdef::adjncy, graphdef::adjwgt, cutType, NULL, graphdef::nvtxs, RASSO, and graphdef::xadj.
Referenced by pingpong().
transform_matrix_half()
void transform_matrix_half (CtrlType * ctrl, GraphType * graph, idxtype * w, float * m_adjwgt)
Definition at line 90 of file wkkm_old.c.
References graphdef::adjncy, graphdef::adjwgt, cutType, NULL, graphdef::nvtxs, RASSO, and graphdef::xadj.
Weighted_kernel_k_means()
void Weighted_kernel_k_means (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * w, float * m_adjwgt, float * tpwgts, float ubfactor)
Definition at line 170 of file wkkm_old.c.
Referenced by pingpong().
Variable Documentation
cutType
int cutType extern
Definition at line 3 of file metis.c.
Referenced by Compute_Weights(), transform_matrix(), and transform_matrix_half().