ACloudViewer: /root/ACloudViewer/libs/Reconstruction/lib/Graclus/multilevelLib/wkkm.c File Reference
wkkm.c File Reference
#include "metisLib/metis.h"
#include <float.h>
Functions
void Compute_Weights (CtrlType *ctrl, GraphType *graph, idxtype *w)
void transform_matrix (CtrlType *ctrl, GraphType *graph, idxtype *w, float *m_adjwgt)
void transform_matrix_half (CtrlType *ctrl, GraphType *graph, idxtype *w, float *m_adjwgt)
void pingpong (CtrlType *ctrl, GraphType *graph, int nparts, int chain_length, float *tpwgts, float ubfactor, int toplevel)
void Weighted_kernel_k_means (CtrlType *ctrl, GraphType *graph, int nparts, idxtype *w, float *tpwgts, float ubfactor)
int local_search (CtrlType *ctrl, GraphType *graph, int nparts, int chain_length, idxtype *w, float *tpwgts, float ubfactor)
float onePoint_move (GraphType *graph, int nparts, idxtype *sum, idxtype *squared_sum, idxtype *w, idxtype *self_sim, int **linearTerm, int ii)
void move1Point2EmptyCluster (GraphType *graph, int nparts, idxtype *sum, idxtype *squared_sum, idxtype *w, idxtype *self_sim, int **linearTerm, int k)
void remove_empty_clusters_l1 (CtrlType *ctrl, GraphType *graph, int nparts, idxtype *w, float *tpwgts, float ubfactor)
void remove_empty_clusters_l2 (CtrlType *ctrl, GraphType *graph, int nparts, idxtype *w, float *tpwgts, float ubfactor)
void MLKKMRefine (CtrlType *ctrl, GraphType *orggraph, GraphType *graph, int nparts, int chain_length, float *tpwgts, float ubfactor)
Variables
int cutType
int memory_saving
int boundary_points
Function Documentation
Compute_Weights()
void Compute_Weights (CtrlType * ctrl, GraphType * graph, idxtype * w)
Definition at line 19 of file wkkm.c.
Referenced by pingpong().
local_search()
int local_search (CtrlType * ctrl, GraphType * graph, int nparts, int chain_length, idxtype * w, float * tpwgts, float ubfactor)
Definition at line 409 of file wkkm.c.
Referenced by pingpong(), and remove_empty_clusters_l1().
MLKKMRefine()
void MLKKMRefine (CtrlType * ctrl, GraphType * orggraph, GraphType * graph, int nparts, int chain_length, float * tpwgts, float ubfactor)
Definition at line 1012 of file wkkm.c.
move1Point2EmptyCluster()
void move1Point2EmptyCluster (GraphType * graph, int nparts, idxtype * sum, idxtype * squared_sum, idxtype * w, idxtype * self_sim, int ** linearTerm, int k)
Definition at line 736 of file wkkm.c.
onePoint_move()
float onePoint_move (GraphType * graph, int nparts, idxtype * sum, idxtype * squared_sum, idxtype * w, idxtype * self_sim, int ** linearTerm, int ii)
Definition at line 608 of file wkkm.c.
pingpong()
void pingpong (CtrlType * ctrl, GraphType * graph, int nparts, int chain_length, float * tpwgts, float ubfactor, int toplevel)
Definition at line 138 of file wkkm.c.
Referenced by MLKKMRefine().
remove_empty_clusters_l1()
void remove_empty_clusters_l1 (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * w, float * tpwgts, float ubfactor)
Definition at line 912 of file wkkm.c.
Referenced by pingpong().
remove_empty_clusters_l2()
void remove_empty_clusters_l2 (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * w, float * tpwgts, float ubfactor)
Definition at line 929 of file wkkm.c.
Referenced by pingpong().
transform_matrix()
void transform_matrix (CtrlType * ctrl, GraphType * graph, idxtype * w, float * m_adjwgt)
Definition at line 43 of file wkkm.c.
transform_matrix_half()
void transform_matrix_half (CtrlType * ctrl, GraphType * graph, idxtype * w, float * m_adjwgt)
Definition at line 90 of file wkkm.c.
Weighted_kernel_k_means()
void Weighted_kernel_k_means (CtrlType * ctrl, GraphType * graph, int nparts, idxtype * w, float * tpwgts, float ubfactor)
Definition at line 183 of file wkkm.c.
Referenced by pingpong().
Variable Documentation
boundary_points
int boundary_points
Definition at line 17 of file wkkm.c.
cutType
int cutType extern
Definition at line 3 of file metis.c.
Referenced by Compute_Weights(), MLKKMRefine(), transform_matrix(), and transform_matrix_half().
memory_saving
int memory_saving
Definition at line 17 of file wkkm.c.
Referenced by pingpong().