ACloudViewer: /root/ACloudViewer/plugins/core/IO/qPhotoscanIO/extern/quazip/quazip/quazip/zip.h File Reference
zip.h File Reference
#include "zlib.h"
#include "ioapi.h"
Classes
struct tm_zip_s
struct zip_fileinfo
Macros
#define Z_BZIP2ED 12
#define ZIP_OK (0)
#define ZIP_EOF (0)
#define ZIP_ERRNO (Z_ERRNO)
#define ZIP_PARAMERROR (-102)
#define ZIP_BADZIPFILE (-103)
#define ZIP_INTERNALERROR (-104)
#define ZIP_WRITE_DATA_DESCRIPTOR 0x8u
#define ZIP_AUTO_CLOSE 0x1u
#define ZIP_SEQUENTIAL 0x2u
#define ZIP_DEFAULT_FLAGS (ZIP_AUTO_CLOSE | ZIP_WRITE_DATA_DESCRIPTOR)
#define DEF_MEM_LEVEL MAX_MEM_LEVEL
#define APPEND_STATUS_CREATE (0)
#define APPEND_STATUS_CREATEAFTER (1)
#define APPEND_STATUS_ADDINZIP (2)
Typedefs
typedef voidp zipFile
typedef struct tm_zip_s tm_zip
typedef const char * zipcharpc
Functions
zipFile ZEXPORT zipOpen _Z_OF ((voidpf file, int append))
zipFile ZEXPORT zipOpen2 _Z_OF ((voidpf file, int append, zipcharpc *globalcomment, zlib_filefunc_def *pzlib_filefunc_def))
zipFile ZEXPORT zipOpen2_64 _Z_OF ((voidpf file, int append, zipcharpc *globalcomment, zlib_filefunc64_def *pzlib_filefunc_def))
zipFile ZEXPORT zipOpen3 (voidpf file, int append, zipcharpc *globalcomment, zlib_filefunc64_32_def *pzlib_filefunc64_32_def, unsigned flags)
int ZEXPORT zipOpenNewFileInZip _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level))
int ZEXPORT zipOpenNewFileInZip64 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int zip64))
int ZEXPORT zipOpenNewFileInZip2 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw))
int ZEXPORT zipOpenNewFileInZip2_64 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int zip64))
int ZEXPORT zipOpenNewFileInZip3 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting))
int ZEXPORT zipOpenNewFileInZip3_64 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting, int zip64))
int ZEXPORT zipOpenNewFileInZip4 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting, uLong versionMadeBy, uLong flagBase))
int ZEXPORT zipOpenNewFileInZip4_64 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting, uLong versionMadeBy, uLong flagBase, int zip64))
int ZEXPORT zipWriteInFileInZip _Z_OF ((zipFile file, const void *buf, unsigned len))
int ZEXPORT zipCloseFileInZip _Z_OF ((zipFile file))
int ZEXPORT zipCloseFileInZipRaw _Z_OF ((zipFile file, uLong uncompressed_size, uLong crc32))
int ZEXPORT zipCloseFileInZipRaw64 _Z_OF ((zipFile file, ZPOS64_T uncompressed_size, uLong crc32))
int ZEXPORT zipClose _Z_OF ((zipFile file, const char *global_comment))
int ZEXPORT zipRemoveExtraInfoBlock _Z_OF ((char *pData, int *dataLen, short sHeader))
int ZEXPORT zipSetFlags (zipFile file, unsigned flags)
int ZEXPORT zipClearFlags (zipFile file, unsigned flags)
Macro Definition Documentation
APPEND_STATUS_ADDINZIP
#define APPEND_STATUS_ADDINZIP (2)
Definition at line 128 of file zip.h.
APPEND_STATUS_CREATE
#define APPEND_STATUS_CREATE (0)
Definition at line 126 of file zip.h.
APPEND_STATUS_CREATEAFTER
#define APPEND_STATUS_CREATEAFTER (1)
Definition at line 127 of file zip.h.
DEF_MEM_LEVEL
#define DEF_MEM_LEVEL MAX_MEM_LEVEL
Definition at line 99 of file zip.h.
Z_BZIP2ED
#define Z_BZIP2ED 12
Definition at line 70 of file zip.h.
ZIP_AUTO_CLOSE
#define ZIP_AUTO_CLOSE 0x1u
Definition at line 91 of file zip.h.
ZIP_BADZIPFILE
#define ZIP_BADZIPFILE (-103)
Definition at line 87 of file zip.h.
ZIP_DEFAULT_FLAGS
#define ZIP_DEFAULT_FLAGS (ZIP_AUTO_CLOSE | ZIP_WRITE_DATA_DESCRIPTOR)
Definition at line 93 of file zip.h.
ZIP_EOF
#define ZIP_EOF (0)
Definition at line 84 of file zip.h.
ZIP_ERRNO
#define ZIP_ERRNO (Z_ERRNO)
Definition at line 85 of file zip.h.
ZIP_INTERNALERROR
#define ZIP_INTERNALERROR (-104)
Definition at line 88 of file zip.h.
ZIP_OK
#define ZIP_OK (0)
Definition at line 83 of file zip.h.
ZIP_PARAMERROR
#define ZIP_PARAMERROR (-102)
Definition at line 86 of file zip.h.
ZIP_SEQUENTIAL
#define ZIP_SEQUENTIAL 0x2u
Definition at line 92 of file zip.h.
ZIP_WRITE_DATA_DESCRIPTOR
#define ZIP_WRITE_DATA_DESCRIPTOR 0x8u
Definition at line 90 of file zip.h.
Typedef Documentation
tm_zip
typedef struct tm_zip_s tm_zip
zipcharpc
typedef const char* zipcharpc
Definition at line 124 of file zip.h.
zipFile
typedef voidp zipFile
Definition at line 80 of file zip.h.
Function Documentation
_Z_OF() [1/17]
int ZEXPORT zipRemoveExtraInfoBlock _Z_OF ((char *pData, int *dataLen, short sHeader))
_Z_OF() [2/17]
zipFile ZEXPORT zipOpen _Z_OF ((voidpf file, int append))
_Z_OF() [3/17]
zipFile ZEXPORT zipOpen2_64 _Z_OF ((voidpf file, int append, zipcharpc *globalcomment, zlib_filefunc64_def *pzlib_filefunc_def))
_Z_OF() [4/17]
zipFile ZEXPORT zipOpen2 _Z_OF ((voidpf file, int append, zipcharpc *globalcomment, zlib_filefunc_def *pzlib_filefunc_def))
_Z_OF() [5/17]
int ZEXPORT zipCloseFileInZip _Z_OF ((zipFile file))
_Z_OF() [6/17]
int ZEXPORT zipOpenNewFileInZip _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level))
_Z_OF() [7/17]
int ZEXPORT zipOpenNewFileInZip2 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw))
_Z_OF() [8/17]
int ZEXPORT zipOpenNewFileInZip3 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting))
_Z_OF() [9/17]
int ZEXPORT zipOpenNewFileInZip3_64 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting, int zip64))
_Z_OF() [10/17]
int ZEXPORT zipOpenNewFileInZip4 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting, uLong versionMadeBy, uLong flagBase))
_Z_OF() [11/17]
int ZEXPORT zipOpenNewFileInZip4_64 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting, uLong versionMadeBy, uLong flagBase, int zip64))
_Z_OF() [12/17]
int ZEXPORT zipOpenNewFileInZip2_64 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int zip64))
_Z_OF() [13/17]
int ZEXPORT zipOpenNewFileInZip64 _Z_OF ((zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int zip64))
_Z_OF() [14/17]
int ZEXPORT zipClose _Z_OF ((zipFile file, const char *global_comment))
_Z_OF() [15/17]
int ZEXPORT zipWriteInFileInZip _Z_OF ((zipFile file, const void *buf, unsigned len))
_Z_OF() [16/17]
int ZEXPORT zipCloseFileInZipRaw _Z_OF ((zipFile file, uLong uncompressed_size, uLong crc32))
_Z_OF() [17/17]
int ZEXPORT zipCloseFileInZipRaw64 _Z_OF ((zipFile file, ZPOS64_T uncompressed_size, uLong crc32))
zipClearFlags()
int ZEXPORT zipClearFlags (zipFile file, unsigned flags)
Definition at line 2085 of file zip.c.
References zip64_internal::flags, NULL, ZIP_OK, ZIP_PARAMERROR, ZIP_SEQUENTIAL, and ZIP_WRITE_DATA_DESCRIPTOR.
Referenced by QuaZipFile::open().
zipOpen3()
zipFile ZEXPORT zipOpen3 (voidpf file, int append, zipcharpc * globalcomment, zlib_filefunc64_32_def * pzlib_filefunc64_32_def, unsigned flags)
Definition at line 862 of file zip.c.
References zip64_internal::add_position_when_writting_offset, ALLOC, APPEND_STATUS_ADDINZIP, APPEND_STATUS_CREATE, APPEND_STATUS_CREATEAFTER, zip64_internal::begin_pos, zip64_internal::central_dir, zip64_internal::ci, zip64_internal::filestream, fill_qiodevice64_filefunc(), zip64_internal::flags, zip64_internal::globalcomment, zip64_internal::in_opened_file_inzip, init_linkedlist(), LoadCentralDirectoryRecord(), NULL, zip64_internal::number_entry, SEEK_END, curfile64_info::stream_initialised, TRYFREE, zip64_internal::z_filefunc, ZCLOSE64, ZFAKECLOSE64, zlib_filefunc64_32_def_s::zfile_func64, ZIP_AUTO_CLOSE, ZIP_OK, ZLIB_FILEFUNC_MODE_CREATE, ZLIB_FILEFUNC_MODE_EXISTING, ZLIB_FILEFUNC_MODE_READ, ZLIB_FILEFUNC_MODE_WRITE, ZOPEN64, zlib_filefunc64_32_def_s::zseek32_file, ZSEEK64, zlib_filefunc64_32_def_s::ztell32_file, and ZTELL64.
Referenced by zipOpen(), zipOpen2(), zipOpen2_64(), and zipOpen64().
zipSetFlags()
int ZEXPORT zipSetFlags (zipFile file, unsigned flags)
Definition at line 2071 of file zip.c.
References zip64_internal::flags, NULL, ZIP_OK, ZIP_PARAMERROR, ZIP_SEQUENTIAL, and ZIP_WRITE_DATA_DESCRIPTOR.
Referenced by QuaZipFile::open().