ACloudViewer: /root/ACloudViewer/plugins/core/IO/qPhotoscanIO/extern/quazip/quazip/quazip/zip.c File Reference
zip.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "zlib.h"
#include "zip.h"
#include <errno.h>
#include "crypt.h"
Classes
struct linkedlist_datablock_internal_s
struct linkedlist_data_s
struct curfile64_info
struct zip64_internal
Macros
#define local static
#define VERSIONMADEBY (0x031e) /* best for standard pkware crypt */
#define Z_BUFSIZE (64*1024) /* (16384) */
#define Z_MAXFILENAMEINZIP (256)
#define ALLOC(size) (malloc(size))
#define TRYFREE(p) {if (p) free(p);}
#define MAKEULONG64(a, b) ((ZPOS64_T)(((unsigned long)(a)) | ((ZPOS64_T)((unsigned long)(b))) << 32))
#define SEEK_CUR 1
#define SEEK_END 2
#define SEEK_SET 0
#define SIZEDATA_INDATABLOCK (4096-(4*4))
#define LOCALHEADERMAGIC (0x04034b50)
#define DESCRIPTORHEADERMAGIC (0x08074b50)
#define CENTRALHEADERMAGIC (0x02014b50)
#define ENDHEADERMAGIC (0x06054b50)
#define ZIP64ENDHEADERMAGIC (0x6064b50)
#define ZIP64ENDLOCHEADERMAGIC (0x7064b50)
#define FLAG_LOCALHEADER_OFFSET (0x06)
#define CRC_LOCALHEADER_OFFSET (0x0e)
#define SIZECENTRALHEADER (0x2e) /* 46 */
#define INCLUDECRYPTINGCODE_IFCRYPTALLOWED
#define BUFREADCOMMENT (0x400)
Typedefs
typedef uLongf z_crc_t
typedef struct linkedlist_datablock_internal_s linkedlist_datablock_internal
typedef struct linkedlist_data_s linkedlist_data
Functions
static linkedlist_datablock_internal * allocate_new_datablock ()
static void free_datablock (linkedlist_datablock_internal *ldi)
static void init_linkedlist (linkedlist_data *ll)
static void free_linkedlist (linkedlist_data *ll)
static int add_data_in_datablock (linkedlist_data *ll, const void *buf, uLong len)
static int zip64local_putValue _Z_OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T x, int nbByte))
static int zip64local_putValue (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T x, int nbByte)
static void zip64local_putValue_inmemory _Z_OF ((void *dest, ZPOS64_T x, int nbByte))
static void zip64local_putValue_inmemory (void *dest, ZPOS64_T x, int nbByte)
static uLong zip64local_TmzDateToDosDate (const tm_zip *ptm)
static int zip64local_getByte _Z_OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, int *pi))
static int zip64local_getByte (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, int *pi)
static int zip64local_getShort _Z_OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, uLong *pX))
static int zip64local_getShort (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, uLong *pX)
static int zip64local_getLong (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, uLong *pX)
static int zip64local_getLong64 _Z_OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T *pX))
static int zip64local_getLong64 (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T *pX)
static ZPOS64_T zip64local_SearchCentralDir _Z_OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream))
static ZPOS64_T zip64local_SearchCentralDir (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream)
static ZPOS64_T zip64local_SearchCentralDir64 (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream)
int LoadCentralDirectoryRecord (zip64_internal *pziinit)
zipFile ZEXPORT zipOpen3 (voidpf file, int append, zipcharpc *globalcomment, zlib_filefunc64_32_def *pzlib_filefunc64_32_def, unsigned flags)
zipFile ZEXPORT zipOpen2 (voidpf file, int append, zipcharpc *globalcomment, zlib_filefunc_def *pzlib_filefunc32_def)
zipFile ZEXPORT zipOpen2_64 (voidpf file, int append, zipcharpc *globalcomment, zlib_filefunc64_def *pzlib_filefunc_def)
zipFile ZEXPORT zipOpen (voidpf file, int append)
zipFile ZEXPORT zipOpen64 (voidpf file, int append)
int Write_LocalFileHeader (zip64_internal *zi, const char *filename, uInt size_extrafield_local, const void *extrafield_local, uLong version_to_extract)
int ZEXPORT zipOpenNewFileInZip4_64 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting, uLong versionMadeBy, uLong flagBase, int zip64)
int ZEXPORT zipOpenNewFileInZip4 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting, uLong versionMadeBy, uLong flagBase)
int ZEXPORT zipOpenNewFileInZip3 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting)
int ZEXPORT zipOpenNewFileInZip3_64 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char *password, uLong crcForCrypting, int zip64)
int ZEXPORT zipOpenNewFileInZip2 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw)
int ZEXPORT zipOpenNewFileInZip2_64 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int raw, int zip64)
int ZEXPORT zipOpenNewFileInZip64 (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level, int zip64)
int ZEXPORT zipOpenNewFileInZip (zipFile file, const char *filename, const zip_fileinfo *zipfi, const void *extrafield_local, uInt size_extrafield_local, const void *extrafield_global, uInt size_extrafield_global, const char *comment, int method, int level)
static int zip64FlushWriteBuffer (zip64_internal *zi)
int ZEXPORT zipWriteInFileInZip (zipFile file, const void *buf, unsigned int len)
int ZEXPORT zipCloseFileInZipRaw (zipFile file, uLong uncompressed_size, uLong crc32)
int ZEXPORT zipCloseFileInZipRaw64 (zipFile file, ZPOS64_T uncompressed_size, uLong crc32)
int ZEXPORT zipCloseFileInZip (zipFile file)
int Write_Zip64EndOfCentralDirectoryLocator (zip64_internal *zi, ZPOS64_T zip64eocd_pos_inzip)
int Write_Zip64EndOfCentralDirectoryRecord (zip64_internal *zi, uLong size_centraldir, ZPOS64_T centraldir_pos_inzip)
int Write_EndOfCentralDirectoryRecord (zip64_internal *zi, uLong size_centraldir, ZPOS64_T centraldir_pos_inzip)
int Write_GlobalComment (zip64_internal *zi, const char *global_comment)
int ZEXPORT zipClose (zipFile file, const char *global_comment)
int ZEXPORT zipRemoveExtraInfoBlock (char *pData, int *dataLen, short sHeader)
int ZEXPORT zipSetFlags (zipFile file, unsigned flags)
int ZEXPORT zipClearFlags (zipFile file, unsigned flags)
Variables
const char zip_copyright [] =" zip 1.01 Copyright 1998-2004 Gilles Vollant - http://www.winimage.com/zLibDll"
Macro Definition Documentation
ALLOC
#define ALLOC (size) (malloc(size))
Definition at line 68 of file zip.c.
BUFREADCOMMENT
#define BUFREADCOMMENT (0x400)
Definition at line 481 of file zip.c.
CENTRALHEADERMAGIC
#define CENTRALHEADERMAGIC (0x02014b50)
Definition at line 111 of file zip.c.
CRC_LOCALHEADER_OFFSET
#define CRC_LOCALHEADER_OFFSET (0x0e)
Definition at line 117 of file zip.c.
DESCRIPTORHEADERMAGIC
#define DESCRIPTORHEADERMAGIC (0x08074b50)
Definition at line 110 of file zip.c.
ENDHEADERMAGIC
#define ENDHEADERMAGIC (0x06054b50)
Definition at line 112 of file zip.c.
FLAG_LOCALHEADER_OFFSET
#define FLAG_LOCALHEADER_OFFSET (0x06)
Definition at line 116 of file zip.c.
INCLUDECRYPTINGCODE_IFCRYPTALLOWED
#define INCLUDECRYPTINGCODE_IFCRYPTALLOWED
Definition at line 194 of file zip.c.
local
#define local static
Definition at line 51 of file zip.c.
LOCALHEADERMAGIC
#define LOCALHEADERMAGIC (0x04034b50)
Definition at line 109 of file zip.c.
MAKEULONG64
#define MAKEULONG64 (a, b) ((ZPOS64_T)(((unsigned long)(a)) | ((ZPOS64_T)((unsigned long)(b))) << 32))
Definition at line 83 of file zip.c.
SEEK_CUR
#define SEEK_CUR 1
Definition at line 86 of file zip.c.
SEEK_END
#define SEEK_END 2
Definition at line 90 of file zip.c.
SEEK_SET
#define SEEK_SET 0
Definition at line 94 of file zip.c.
SIZECENTRALHEADER
#define SIZECENTRALHEADER (0x2e) /* 46 */
Definition at line 119 of file zip.c.
SIZEDATA_INDATABLOCK
#define SIZEDATA_INDATABLOCK (4096-(4*4))
Definition at line 107 of file zip.c.
TRYFREE
#define TRYFREE (p) {if (p) free(p);}
Definition at line 71 of file zip.c.
VERSIONMADEBY
#define VERSIONMADEBY (0x031e) /* best for standard pkware crypt */
Definition at line 56 of file zip.c.
Z_BUFSIZE
#define Z_BUFSIZE (64*1024) /* (16384) */
Definition at line 60 of file zip.c.
Z_MAXFILENAMEINZIP
#define Z_MAXFILENAMEINZIP (256)
Definition at line 64 of file zip.c.
ZIP64ENDHEADERMAGIC
#define ZIP64ENDHEADERMAGIC (0x6064b50)
Definition at line 113 of file zip.c.
ZIP64ENDLOCHEADERMAGIC
#define ZIP64ENDLOCHEADERMAGIC (0x7064b50)
Definition at line 114 of file zip.c.
Typedef Documentation
linkedlist_data
typedef struct linkedlist_data_s linkedlist_data
linkedlist_datablock_internal
typedef struct linkedlist_datablock_internal_s linkedlist_datablock_internal
z_crc_t
typedef uLongf z_crc_t
Definition at line 34 of file zip.c.
Function Documentation
_Z_OF() [1/6]
static ZPOS64_T zip64local_SearchCentralDir _Z_OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream)) static
_Z_OF() [2/6]
static int zip64local_getByte _Z_OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, int *pi)) static
_Z_OF() [3/6]
static int zip64local_getShort _Z_OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, uLong *pX)) static
_Z_OF() [4/6]
static int zip64local_getLong64 _Z_OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T *pX)) static
_Z_OF() [5/6]
static int zip64local_putValue _Z_OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T x, int nbByte)) static
_Z_OF() [6/6]
static void zip64local_putValue_inmemory _Z_OF ((void *dest, ZPOS64_T x, int nbByte)) static
add_data_in_datablock()
static int add_data_in_datablock (linkedlist_data * ll, const void * buf, uLong len) static
Definition at line 234 of file zip.c.
References allocate_new_datablock(), linkedlist_datablock_internal_s::avail_in_this_block, linkedlist_datablock_internal_s::data, linkedlist_datablock_internal_s::filled_in_this_block, linkedlist_data_s::first_block, linkedlist_data_s::last_block, linkedlist_datablock_internal_s::next_datablock, NULL, ZIP_INTERNALERROR, and ZIP_OK.
Referenced by LoadCentralDirectoryRecord(), and zipCloseFileInZipRaw64().
allocate_new_datablock()
static linkedlist_datablock_internal* allocate_new_datablock () static
Definition at line 198 of file zip.c.
References ALLOC, linkedlist_datablock_internal_s::avail_in_this_block, linkedlist_datablock_internal_s::filled_in_this_block, linkedlist_datablock_internal_s::next_datablock, NULL, and SIZEDATA_INDATABLOCK.
Referenced by add_data_in_datablock().
free_datablock()
static void free_datablock (linkedlist_datablock_internal * ldi) static
Definition at line 212 of file zip.c.
References linkedlist_datablock_internal_s::next_datablock, NULL, and TRYFREE.
Referenced by free_linkedlist().
free_linkedlist()
static void free_linkedlist (linkedlist_data * ll) static
Definition at line 227 of file zip.c.
References linkedlist_data_s::first_block, free_datablock(), linkedlist_data_s::last_block, and NULL.
Referenced by zipClose().
init_linkedlist()
static void init_linkedlist (linkedlist_data * ll) static
Definition at line 222 of file zip.c.
References linkedlist_data_s::first_block, linkedlist_data_s::last_block, and NULL.
Referenced by zipOpen3().
LoadCentralDirectoryRecord()
int LoadCentralDirectoryRecord (zip64_internal * pziinit)
Definition at line 649 of file zip.c.
References add_data_in_datablock(), zip64_internal::add_position_when_writting_offset, ALLOC, zip64_internal::begin_pos, zip64_internal::central_dir, zip64_internal::filestream, zip64_internal::flags, zip64_internal::globalcomment, zip64_internal::number_entry, SIZEDATA_INDATABLOCK, TRYFREE, zip64_internal::z_filefunc, ZCLOSE64, ZFAKECLOSE64, zip64local_getLong(), zip64local_getLong64(), zip64local_getShort(), zip64local_SearchCentralDir(), zip64local_SearchCentralDir64(), ZIP_AUTO_CLOSE, ZIP_BADZIPFILE, ZIP_ERRNO, ZIP_OK, ZLIB_FILEFUNC_SEEK_SET, ZREAD64, and ZSEEK64.
Referenced by zipOpen3().
Write_EndOfCentralDirectoryRecord()
int Write_EndOfCentralDirectoryRecord (zip64_internal * zi, uLong size_centraldir, ZPOS64_T centraldir_pos_inzip)
Definition at line 1870 of file zip.c.
References zip64_internal::add_position_when_writting_offset, ENDHEADERMAGIC, zip64_internal::filestream, zip64_internal::number_entry, zip64_internal::z_filefunc, zip64local_putValue(), and ZIP_OK.
Referenced by zipClose().
Write_GlobalComment()
int Write_GlobalComment (zip64_internal * zi, const char * global_comment)
Definition at line 1918 of file zip.c.
References zip64_internal::filestream, NULL, zip64_internal::z_filefunc, zip64local_putValue(), ZIP_ERRNO, ZIP_OK, and ZWRITE64.
Referenced by zipClose().
Write_LocalFileHeader()
int Write_LocalFileHeader (zip64_internal * zi, const char * filename, uInt size_extrafield_local, const void * extrafield_local, uLong version_to_extract)
Definition at line 977 of file zip.c.
References zip64_internal::ci, curfile64_info::dosDate, zip64_internal::filestream, curfile64_info::flag, LOCALHEADERMAGIC, curfile64_info::method, curfile64_info::pos_zip64extrainfo, zip64_internal::z_filefunc, curfile64_info::zip64, zip64local_putValue(), ZIP_ERRNO, ZIP_OK, ZTELL64, and ZWRITE64.
Referenced by zipOpenNewFileInZip4_64().
Write_Zip64EndOfCentralDirectoryLocator()
int Write_Zip64EndOfCentralDirectoryLocator (zip64_internal * zi, ZPOS64_T zip64eocd_pos_inzip)
Definition at line 1809 of file zip.c.
References zip64_internal::add_position_when_writting_offset, zip64_internal::filestream, zip64_internal::z_filefunc, ZIP64ENDLOCHEADERMAGIC, zip64local_putValue(), and ZIP_OK.
Referenced by zipClose().
Write_Zip64EndOfCentralDirectoryRecord()
int Write_Zip64EndOfCentralDirectoryRecord (zip64_internal * zi, uLong size_centraldir, ZPOS64_T centraldir_pos_inzip)
Definition at line 1831 of file zip.c.
References zip64_internal::add_position_when_writting_offset, zip64_internal::filestream, zip64_internal::number_entry, zip64_internal::z_filefunc, ZIP64ENDHEADERMAGIC, zip64local_putValue(), and ZIP_OK.
Referenced by zipClose().
zip64FlushWriteBuffer()
static int zip64FlushWriteBuffer (zip64_internal * zi) static
Definition at line 1403 of file zip.c.
References curfile64_info::buffered_data, zip64_internal::ci, curfile64_info::encrypt, zip64_internal::filestream, curfile64_info::keys, curfile64_info::method, curfile64_info::pcrc_32_tab, curfile64_info::pos_in_buffered_data, curfile64_info::stream, curfile64_info::totalCompressedData, curfile64_info::totalUncompressedData, Z_BZIP2ED, zip64_internal::z_filefunc, zencode, ZIP_ERRNO, ZIP_OK, and ZWRITE64.
Referenced by zipCloseFileInZipRaw64(), and zipWriteInFileInZip().
zip64local_getByte()
static int zip64local_getByte (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, int * pi) static
Definition at line 358 of file zip.c.
References ZERROR64, ZIP_EOF, ZIP_ERRNO, ZIP_OK, and ZREAD64.
Referenced by zip64local_getLong(), zip64local_getLong64(), and zip64local_getShort().
zip64local_getLong()
static int zip64local_getLong (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, uLong * pX) static
Definition at line 404 of file zip.c.
References zip64local_getByte(), and ZIP_OK.
Referenced by LoadCentralDirectoryRecord(), and zip64local_SearchCentralDir64().
zip64local_getLong64()
static int zip64local_getLong64 (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, ZPOS64_T * pX) static
Definition at line 435 of file zip.c.
References zip64local_getByte(), and ZIP_OK.
Referenced by LoadCentralDirectoryRecord(), and zip64local_SearchCentralDir64().
zip64local_getShort()
static int zip64local_getShort (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, uLong * pX) static
Definition at line 382 of file zip.c.
References zip64local_getByte(), and ZIP_OK.
Referenced by LoadCentralDirectoryRecord().
zip64local_putValue()
static int zip64local_putValue (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, ZPOS64_T x, int nbByte) static
Definition at line 296 of file zip.c.
References ZIP_ERRNO, ZIP_OK, and ZWRITE64.
Referenced by Write_EndOfCentralDirectoryRecord(), Write_GlobalComment(), Write_LocalFileHeader(), Write_Zip64EndOfCentralDirectoryLocator(), Write_Zip64EndOfCentralDirectoryRecord(), and zipCloseFileInZipRaw64().
zip64local_putValue_inmemory()
static void zip64local_putValue_inmemory (void * dest, ZPOS64_T x, int nbByte) static
Definition at line 320 of file zip.c.
Referenced by zipCloseFileInZipRaw64(), and zipOpenNewFileInZip4_64().
zip64local_SearchCentralDir()
static ZPOS64_T zip64local_SearchCentralDir (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream) static
Definition at line 489 of file zip.c.
References ALLOC, BUFREADCOMMENT, NULL, TRYFREE, ZLIB_FILEFUNC_SEEK_END, ZLIB_FILEFUNC_SEEK_SET, ZREAD64, ZSEEK64, and ZTELL64.
Referenced by LoadCentralDirectoryRecord().
zip64local_SearchCentralDir64()
static ZPOS64_T zip64local_SearchCentralDir64 (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream) static
Definition at line 551 of file zip.c.
References ALLOC, BUFREADCOMMENT, NULL, TRYFREE, zip64local_getLong(), zip64local_getLong64(), ZIP_OK, ZLIB_FILEFUNC_SEEK_END, ZLIB_FILEFUNC_SEEK_SET, ZREAD64, ZSEEK64, and ZTELL64.
Referenced by LoadCentralDirectoryRecord().
zip64local_TmzDateToDosDate()
static uLong zip64local_TmzDateToDosDate (const tm_zip * ptm) static
Definition at line 341 of file zip.c.
References tm_zip_s::tm_hour, tm_zip_s::tm_mday, tm_zip_s::tm_min, tm_zip_s::tm_mon, tm_zip_s::tm_sec, and tm_zip_s::tm_year.
Referenced by zipOpenNewFileInZip4_64().
zipClearFlags()
int ZEXPORT zipClearFlags (zipFile file, unsigned flags)
Definition at line 2085 of file zip.c.
References zip64_internal::flags, NULL, ZIP_OK, ZIP_PARAMERROR, ZIP_SEQUENTIAL, and ZIP_WRITE_DATA_DESCRIPTOR.
Referenced by QuaZipFile::open().
zipClose()
int ZEXPORT zipClose (zipFile file, const char * global_comment)
Definition at line 1936 of file zip.c.
References zip64_internal::add_position_when_writting_offset, zip64_internal::central_dir, linkedlist_datablock_internal_s::data, zip64_internal::filestream, linkedlist_datablock_internal_s::filled_in_this_block, linkedlist_data_s::first_block, zip64_internal::flags, free_linkedlist(), zip64_internal::globalcomment, zip64_internal::in_opened_file_inzip, linkedlist_datablock_internal_s::next_datablock, NULL, zip64_internal::number_entry, TRYFREE, Write_EndOfCentralDirectoryRecord(), Write_GlobalComment(), Write_Zip64EndOfCentralDirectoryLocator(), Write_Zip64EndOfCentralDirectoryRecord(), zip64_internal::z_filefunc, ZCLOSE64, ZFAKECLOSE64, ZIP_AUTO_CLOSE, ZIP_ERRNO, ZIP_OK, ZIP_PARAMERROR, zipCloseFileInZip(), ZTELL64, and ZWRITE64.
Referenced by QuaZip::close().
zipCloseFileInZip()
int ZEXPORT zipCloseFileInZip (zipFile file)
Definition at line 1804 of file zip.c.
References zipCloseFileInZipRaw().
Referenced by QuaZipFile::close(), zipClose(), and zipOpenNewFileInZip4_64().
zipCloseFileInZipRaw()
int ZEXPORT zipCloseFileInZipRaw (zipFile file, uLong uncompressed_size, uLong crc32)
Definition at line 1543 of file zip.c.
References zipCloseFileInZipRaw64().
Referenced by zipCloseFileInZip().
zipCloseFileInZipRaw64()
int ZEXPORT zipCloseFileInZipRaw64 (zipFile file, ZPOS64_T uncompressed_size, uLong crc32)
Definition at line 1548 of file zip.c.
References add_data_in_datablock(), curfile64_info::buffered_data, zip64_internal::central_dir, curfile64_info::central_header, zip64_internal::ci, curfile64_info::crc32, curfile64_info::crypt_header_size, DESCRIPTORHEADERMAGIC, zip64_internal::filestream, curfile64_info::flag, zip64_internal::flags, zip64_internal::in_opened_file_inzip, curfile64_info::method, NULL, zip64_internal::number_entry, curfile64_info::pos_in_buffered_data, curfile64_info::pos_local_header, curfile64_info::pos_zip64extrainfo, curfile64_info::raw, curfile64_info::size_centralExtra, curfile64_info::size_centralExtraFree, curfile64_info::size_centralheader, curfile64_info::stream, curfile64_info::stream_initialised, curfile64_info::totalCompressedData, curfile64_info::totalUncompressedData, Z_BUFSIZE, Z_BZIP2ED, zip64_internal::z_filefunc, curfile64_info::zip64, zip64FlushWriteBuffer(), zip64local_putValue(), zip64local_putValue_inmemory(), ZIP_BADZIPFILE, ZIP_ERRNO, ZIP_OK, ZIP_PARAMERROR, ZIP_SEQUENTIAL, ZLIB_FILEFUNC_SEEK_SET, ZSEEK64, and ZTELL64.
Referenced by QuaZipFile::close(), and zipCloseFileInZipRaw().
zipOpen()
zipFile ZEXPORT zipOpen (voidpf file, int append)
Definition at line 967 of file zip.c.
References NULL, ZIP_DEFAULT_FLAGS, and zipOpen3().
zipOpen2()
zipFile ZEXPORT zipOpen2 (voidpf file, int append, zipcharpc * globalcomment, zlib_filefunc_def * pzlib_filefunc32_def)
Definition at line 939 of file zip.c.
References fill_zlib_filefunc64_32_def_from_filefunc32(), NULL, ZIP_DEFAULT_FLAGS, and zipOpen3().
zipOpen2_64()
zipFile ZEXPORT zipOpen2_64 (voidpf file, int append, zipcharpc * globalcomment, zlib_filefunc64_def * pzlib_filefunc_def)
Definition at line 951 of file zip.c.
References NULL, zlib_filefunc64_32_def_s::zfile_func64, ZIP_DEFAULT_FLAGS, zipOpen3(), zlib_filefunc64_32_def_s::zseek32_file, and zlib_filefunc64_32_def_s::ztell32_file.
zipOpen3()
zipFile ZEXPORT zipOpen3 (voidpf file, int append, zipcharpc * globalcomment, zlib_filefunc64_32_def * pzlib_filefunc64_32_def, unsigned flags)
Definition at line 862 of file zip.c.
References zip64_internal::add_position_when_writting_offset, ALLOC, APPEND_STATUS_ADDINZIP, APPEND_STATUS_CREATE, APPEND_STATUS_CREATEAFTER, zip64_internal::begin_pos, zip64_internal::central_dir, zip64_internal::ci, zip64_internal::filestream, fill_qiodevice64_filefunc(), zip64_internal::flags, zip64_internal::globalcomment, zip64_internal::in_opened_file_inzip, init_linkedlist(), LoadCentralDirectoryRecord(), NULL, zip64_internal::number_entry, SEEK_END, curfile64_info::stream_initialised, TRYFREE, zip64_internal::z_filefunc, ZCLOSE64, ZFAKECLOSE64, zlib_filefunc64_32_def_s::zfile_func64, ZIP_AUTO_CLOSE, ZIP_OK, ZLIB_FILEFUNC_MODE_CREATE, ZLIB_FILEFUNC_MODE_EXISTING, ZLIB_FILEFUNC_MODE_READ, ZLIB_FILEFUNC_MODE_WRITE, ZOPEN64, zlib_filefunc64_32_def_s::zseek32_file, ZSEEK64, zlib_filefunc64_32_def_s::ztell32_file, and ZTELL64.
Referenced by zipOpen(), zipOpen2(), zipOpen2_64(), and zipOpen64().
zipOpen64()
zipFile ZEXPORT zipOpen64 (voidpf file, int append)
Definition at line 972 of file zip.c.
References NULL, ZIP_DEFAULT_FLAGS, and zipOpen3().
zipOpenNewFileInZip()
int ZEXPORT zipOpenNewFileInZip (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level)
Definition at line 1390 of file zip.c.
References DEF_MEM_LEVEL, NULL, VERSIONMADEBY, and zipOpenNewFileInZip4_64().
zipOpenNewFileInZip2()
int ZEXPORT zipOpenNewFileInZip2 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int raw)
Definition at line 1351 of file zip.c.
References DEF_MEM_LEVEL, NULL, VERSIONMADEBY, and zipOpenNewFileInZip4_64().
zipOpenNewFileInZip2_64()
int ZEXPORT zipOpenNewFileInZip2_64 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int raw, int zip64)
Definition at line 1364 of file zip.c.
References DEF_MEM_LEVEL, NULL, VERSIONMADEBY, and zipOpenNewFileInZip4_64().
zipOpenNewFileInZip3()
int ZEXPORT zipOpenNewFileInZip3 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char * password, uLong crcForCrypting)
Definition at line 1321 of file zip.c.
References VERSIONMADEBY, and zipOpenNewFileInZip4_64().
zipOpenNewFileInZip3_64()
int ZEXPORT zipOpenNewFileInZip3_64 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char * password, uLong crcForCrypting, int zip64)
Definition at line 1336 of file zip.c.
References VERSIONMADEBY, and zipOpenNewFileInZip4_64().
Referenced by QuaZipFile::open().
zipOpenNewFileInZip4()
int ZEXPORT zipOpenNewFileInZip4 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char * password, uLong crcForCrypting, uLong versionMadeBy, uLong flagBase)
Definition at line 1305 of file zip.c.
References zipOpenNewFileInZip4_64().
zipOpenNewFileInZip4_64()
int ZEXPORT zipOpenNewFileInZip4_64 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int raw, int windowBits, int memLevel, int strategy, const char * password, uLong crcForCrypting, uLong versionMadeBy, uLong flagBase, int zip64)
Definition at line 1077 of file zip.c.
References zip64_internal::add_position_when_writting_offset, ALLOC, curfile64_info::buffered_data, curfile64_info::central_header, CENTRALHEADERMAGIC, zip64_internal::ci, curfile64_info::crc32, curfile64_info::crypt_header_size, curfile64_info::dosDate, zip_fileinfo::dosDate, curfile64_info::encrypt, zip_fileinfo::external_fa, zip64_internal::filestream, curfile64_info::flag, zip64_internal::flags, zip64_internal::in_opened_file_inzip, zip_fileinfo::internal_fa, curfile64_info::keys, curfile64_info::method, NULL, curfile64_info::pcrc_32_tab, curfile64_info::pos_in_buffered_data, curfile64_info::pos_local_header, curfile64_info::pos_zip64extrainfo, curfile64_info::raw, curfile64_info::size_centralExtra, curfile64_info::size_centralExtraFree, curfile64_info::size_centralheader, SIZECENTRALHEADER, curfile64_info::stream, curfile64_info::stream_initialised, zip_fileinfo::tmz_date, curfile64_info::totalCompressedData, curfile64_info::totalUncompressedData, Write_LocalFileHeader(), Z_BUFSIZE, Z_BZIP2ED, zip64_internal::z_filefunc, curfile64_info::zip64, zip64local_putValue_inmemory(), zip64local_TmzDateToDosDate(), ZIP_ERRNO, ZIP_INTERNALERROR, ZIP_OK, ZIP_PARAMERROR, ZIP_SEQUENTIAL, ZIP_WRITE_DATA_DESCRIPTOR, zipCloseFileInZip(), ZTELL64, and ZWRITE64.
Referenced by zipOpenNewFileInZip(), zipOpenNewFileInZip2(), zipOpenNewFileInZip2_64(), zipOpenNewFileInZip3(), zipOpenNewFileInZip3_64(), zipOpenNewFileInZip4(), and zipOpenNewFileInZip64().
zipOpenNewFileInZip64()
int ZEXPORT zipOpenNewFileInZip64 (zipFile file, const char * filename, const zip_fileinfo * zipfi, const void * extrafield_local, uInt size_extrafield_local, const void * extrafield_global, uInt size_extrafield_global, const char * comment, int method, int level, int zip64)
Definition at line 1377 of file zip.c.
References DEF_MEM_LEVEL, NULL, VERSIONMADEBY, and zipOpenNewFileInZip4_64().
zipRemoveExtraInfoBlock()
int ZEXPORT zipRemoveExtraInfoBlock (char * pData, int * dataLen, short sHeader)
Definition at line 2013 of file zip.c.
References ALLOC, NULL, size, TRYFREE, ZIP_ERRNO, ZIP_OK, and ZIP_PARAMERROR.
zipSetFlags()
int ZEXPORT zipSetFlags (zipFile file, unsigned flags)
Definition at line 2071 of file zip.c.
References zip64_internal::flags, NULL, ZIP_OK, ZIP_PARAMERROR, ZIP_SEQUENTIAL, and ZIP_WRITE_DATA_DESCRIPTOR.
Referenced by QuaZipFile::open().
zipWriteInFileInZip()
int ZEXPORT zipWriteInFileInZip (zipFile file, const void * buf, unsigned int len)
Definition at line 1442 of file zip.c.
References curfile64_info::buffered_data, zip64_internal::ci, curfile64_info::crc32, zip64_internal::in_opened_file_inzip, curfile64_info::method, NULL, curfile64_info::pos_in_buffered_data, curfile64_info::raw, curfile64_info::stream, Z_BUFSIZE, Z_BZIP2ED, zip64FlushWriteBuffer(), ZIP_ERRNO, ZIP_OK, and ZIP_PARAMERROR.
Referenced by QuaZipFile::writeData().
Variable Documentation
zip_copyright
const char zip_copyright[] =" zip 1.01 Copyright 1998-2004 Gilles Vollant - http://www.winimage.com/zLibDll"
Definition at line 104 of file zip.c.