ARG VTK_VERSION
ARG PCL_VERSION
ARG CUDA_VERSION
ARG UBUNTU_VERSION
FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION}

# For bash-specific commands
SHELL ["/bin/bash", "-c"]

# FROM nvidia/opengl:1.2-glvnd-devel-ubuntu${UBUNTU_VERSION}
# FROM gezp/ubuntu-nomachine:${UBUNTU_VERSION}-cu${CUDA_VERSION}
LABEL maintainer="ACloudViewer Team ludahai19@163.com"

# Env vars for the nvidia-container-runtime.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
ENV CMAKE_VERSION=cmake-3.24.4-linux-x86_64
ENV SUDO=command

# Execute with nvidia docker (https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0))
# docker run -it --runtime=nvidia cloudviewer-deps

ENV REFRESHED_AT=2023-06-04\
    CLOUDVIEWER_DEV=/opt/ACloudViewer \
    DEBIAN_FRONTEND=noninteractive

# cloudViewer Jupyter dependencies
RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list \
&& apt-get clean && apt-get update --fix-missing -y

# Dependencies: basic
# Update apt and install libs needed by Qt, pcl and vtk
RUN apt-get install apt-utils software-properties-common tzdata --fix-missing -y \
    && apt-key adv --fetch-keys https://apt.kitware.com/keys/kitware-archive-latest.asc \
    && apt-add-repository --yes "deb https://apt.kitware.com/ubuntu/ $(lsb_release -c --short) main" \
    && apt-get update --fix-missing -y \
    && apt-get install --fix-missing -yq --no-install-recommends \
        build-essential \
        git  \
        cmake \
        wget \
        curl \
        vim \
        tree \
        apt-file \
        net-tools \
        mesa-utils \
        # for opencv
        libavcodec-dev \
        libavformat-dev \
        libswscale-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        # for colmap
        libatlas-base-dev \
        # for package
        zip \
        unzip \
        locate \
        automake \
        xorg-dev \
        libxi-dev \
        openmpi-bin \
        openmpi-common \
        gfortran \
        ninja-build \
        libgtest-dev \
        libusb-dev \
        freeglut3-dev \
        pkg-config \
        libpcap-dev \
        clang-format \
        graphviz \
        nasm \
        flex \
        fontconfig \
        mono-complete \
        # for pcl
        libopenni-dev \
        libopenni2-dev \
        libjsoncpp-dev \
        # libgdal-dev \
        # libcgal-dev \
        libusb-1.0-0-dev \
        libeigen3-dev \
        libboost-all-dev \
        libglew-dev \
        'libqhull*' \
        libqhull-dev \
        libflann1.9 \
        libflann-dev \
        # for QT
        libxcb-xkb1 \
        libxcb-shape0 \
        libxcb-randr0 \
        libxcb-icccm4 \
        libxcb-image0 \
        libxcb-keysyms1 \
        libxcb-xinerama0 \
        libxkbcommon-x11-0 \
        libxcb-render-util0

# C++ dependencies
WORKDIR /opt
COPY ./util/install_deps_ubuntu.sh /opt
RUN /opt/install_deps_ubuntu.sh assume-yes

# ACloudViewer Jupyter dependencies
RUN mkdir -p /etc/apt/keyrings \
 && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
 | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main" \
 | tee /etc/apt/sources.list.d/nodesource.list \
 && apt-get update \
 && apt-get install -y nodejs \
 && node --version \
 && npm install -g yarn \
 && yarn --version

# deploy package installer
WORKDIR /opt
COPY docker_files/QtIFW-4.6.1-linux-amd.zip /opt
RUN unzip QtIFW-4.6.1-linux-amd.zip && rm -rf QtIFW-4.6.1-linux-amd.zip
ENV PATH="/opt/QtIFW-4.6.1-linux-amd/bin:$PATH"

# Install Miniconda3
WORKDIR /opt
COPY docker_files/Miniconda3-latest-Linux-x86_64.sh /opt
RUN sh -c '/bin/echo -e "\nyes\n\nyes" | sh Miniconda3-latest-Linux-x86_64.sh' \
    && echo -e "\ny" && /root/miniconda3/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ \
    && /root/miniconda3/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ \
    && /root/miniconda3/bin/conda config --set show_channel_urls yes \
    && /root/miniconda3/bin/pip install --upgrade pip \
    && rm Miniconda3-latest-Linux-x86_64.sh
ENV PATH="/root/miniconda3/bin:$PATH"
# fix ubuntu2204 and conda library conflicts about incorrect link issues from ibffi.so.7 to libffi.so.8.1.0
RUN echo -e "\ny" | conda install libffi==3.3

WORKDIR /root
