ARG CLOUDVIEWER_VERSION
ARG VTK_VERSION
ARG PCL_VERSION
ARG CUDA_VERSION
ARG UBUNTU_VERSION
FROM cloudviewer-deps:${CLOUDVIEWER_VERSION}-ubuntu${UBUNTU_VERSION}-cuda${CUDA_VERSION}
LABEL maintainer="AliceVision Team ludahai19@163.com"

# Env vars for the nvidia-container-runtime.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all

# Execute with nvidia docker (https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0))
# docker run -it --runtime nvidia -p 10022:22 -p 14000:4000 --name cloudViewer -v</path/to/your/data>:/data cloudviewer:develop-ubuntu18.04-cuda101
# ssh -p 10022 -X root@<docker host> /opt/ACloudViewer # Password is 'toor'
# export DISPLAY=:0 # DISPLAY must be consistent with host

ENV ACloudViewer_DEV=/opt/ACloudViewer \
    ACloudViewer_BUILD=/opt/ACloudViewer/build \
    ACloudViewer_INSTALL=/Users/asher/develop/code/github/macos_install \
    BUNDLE_CLOUDVIEWER_ML=/opt/ACloudViewer/CloudViewer-ML \
    QT_DIR=/opt/Qt5.14.2/5.14.2/gcc_64 \
    PATH="${PATH}:${BUNDLE_CLOUDVIEWER_ML}"

COPY . ${ACloudViewer_DEV}/ACloudViewer

WORKDIR ${ACloudViewer_BUILD}

RUN rm -rf ${ACloudViewer_DEV}/ACloudViewer/docker_files \
    && mv /usr/lib/x86_64-linux-gnu/libQt5* /tmp/

# Build ACloudViewer whl package
RUN cmake "${ACloudViewer_DEV}/ACloudViewer" \
            -DDEVELOPER_BUILD=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_JUPYTER_EXTENSION=ON \
            -DBUILD_LIBREALSENSE=ON \
            -DBUILD_AZURE_KINECT=ON \
            -DBUILD_BENCHMARKS=OFF \
            -DWITH_OPENMP=ON \
            -DBUILD_CUDA_MODULE=ON \
            -DBUILD_PYTORCH_OPS=ON \
            -DBUILD_TENSORFLOW_OPS=OFF \
            -DGLIBCXX_USE_CXX11_ABI=OFF \
            #-DBUNDLE_CLOUDVIEWER_ML=ON \
            #-DCLOUDVIEWER_ML_ROOT="${BUNDLE_CLOUDVIEWER_ML}" \
            #-DTHIRD_PARTY_DOWNLOAD_DIR=/opt/ACloudViewer/thirdparties \
            -DPYTHON_EXECUTABLE=/root/miniconda3/bin/python3.6 \
            -DPYTHON_IN_PATH=/root/miniconda3/bin/python3.6 \
            -DPYTHON_LIBRARY=/root/miniconda3/lib/libpython3.6m.so \
            -DQT_QMAKE_EXECUTABLE:PATH=${QT_DIR}/bin/qmake \
            -DCMAKE_PREFIX_PATH:PATH=${QT_DIR}/lib/cmake \
            -DCMAKE_INSTALL_PREFIX=${ACloudViewer_INSTALL}

RUN make "-j$(nproc)" pip-package \
    #&& make "-j$(nproc)" install-pip-package \
    #&& make "-j$(nproc)" conda-package \
    && make install "-j$(nproc)"

# Build ACloudViewer GUI platform
RUN cmake "${ACloudViewer_DEV}/ACloudViewer" \
            -DDEVELOPER_BUILD=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_JUPYTER_EXTENSION=OFF \
            -DBUILD_LIBREALSENSE=OFF \
            -DBUILD_AZURE_KINECT=OFF \
            -DBUILD_BENCHMARKS=OFF \
            -DWITH_IPPICV=OFF \
            -DUSE_SIMD=ON \
            -DWITH_SIMD=ON \
            -DWITH_OPENMP=ON \
            -DBUILD_CUDA_MODULE=OFF \
            -DBUILD_PYTORCH_OPS=OFF \
            -DBUILD_TENSORFLOW_OPS=OFF \
            -DBUNDLE_CLOUDVIEWER_ML=OFF \
            -DGLIBCXX_USE_CXX11_ABI=ON \
            -DCVCORELIB_USE_CGAL=ON \
            -DCVCORELIB_SHARED=ON \
            -DCVCORELIB_USE_QT_CONCURRENT=ON \
            -DBUILD_RECONSTRUCTION=ON \
            -DOPTION_USE_GDAL=OFF \
            -DOPTION_USE_DXF_LIB=ON \
            -DOPTION_USE_RANSAC_LIB=ON \
            -DOPTION_USE_SHAPE_LIB=ON \
            -DPLUGIN_IO_QADDITIONAL=ON \
            -DPLUGIN_IO_QCORE=ON \
            -DPLUGIN_IO_QCSV_MATRIX=ON \
            -DPLUGIN_IO_QE57=ON \
            -DPLUGIN_IO_QMESH=ON \
            -DPLUGIN_IO_QPDAL=OFF \
            -DPLUGIN_IO_QLAS=ON \
            -DPLUGIN_IO_QPHOTOSCAN=ON \
            -DPLUGIN_IO_QDRACO=ON \
            -DPLUGIN_IO_QSTEP=OFF \
            -DPLUGIN_IO_QFBX=OFF \
            -DPLUGIN_IO_QRDB=OFF \
            -DPLUGIN_IO_QRDB_FETCH_DEPENDENCY=OFF \
            -DPLUGIN_STANDARD_QCANUPO=OFF \
            -DPLUGIN_STANDARD_QCORK=OFF \
            -DPLUGIN_STANDARD_QPCV=OFF \
            -DPLUGIN_STANDARD_QANIMATION=ON \
            -DQANIMATION_WITH_FFMPEG_SUPPORT=ON \
            -DPLUGIN_STANDARD_MASONRY_QAUTO_SEG=ON \
            -DPLUGIN_STANDARD_MASONRY_QMANUAL_SEG=ON \
            -DPLUGIN_STANDARD_QCOLORIMETRIC_SEGMENTER=ON \
            -DPLUGIN_STANDARD_QCOMPASS=ON \
            -DPLUGIN_STANDARD_QCSF=ON \
            -DPLUGIN_STANDARD_QFACETS=ON \
            -DPLUGIN_STANDARD_QCLOUDLAYERS=ON \
            -DPLUGIN_STANDARD_QHOUGH_NORMALS=ON \
            -DPLUGIN_STANDARD_QM3C2=ON \
            -DPLUGIN_STANDARD_QMPLANE=ON \
            -DPLUGIN_STANDARD_QPCL=ON \
            -DPLUGIN_STANDARD_QJSONRPC=ON \
            -DPLUGIN_STANDARD_QPOISSON_RECON=ON \
            -DPOISSON_RECON_WITH_OPEN_MP=ON \
            -DPLUGIN_STANDARD_QRANSAC_SD=ON \
            -DPLUGIN_STANDARD_QSRA=ON \
            -DGLIBCXX_USE_CXX11_ABI=1 \
            # -DTHIRD_PARTY_DOWNLOAD_DIR=/opt/ACloudViewer/thirdparties \
            # -DPYTHON_EXECUTABLE=/root/miniconda3/bin/python3.8 \
            # -DPYTHON_IN_PATH=/root/miniconda3/bin/python3.8 \
            # -DPYTHON_LIBRARY=/root/miniconda3/lib/libpython3.8.so \
            # -DQT_QMAKE_EXECUTABLE:PATH=${QT_DIR}/bin/qmake \
            # -DCMAKE_PREFIX_PATH:PATH=${QT_DIR}/lib/cmake \
            -DCMAKE_INSTALL_PREFIX=${ACloudViewer_INSTALL}

RUN make "-j$(nproc)" \
    && make install "-j$(nproc)" \
    && rm -rf ${ACloudViewer_BUILD}

WORKDIR /

ENV LD_LIBRARY_PATH="/opt/Qt5.14.2/5.14.2/gcc_64/lib:$LD_LIBRARY_PATH"
EXPOSE 22 4000
ENTRYPOINT ["/nxserver.sh"]