ARG EROWCLOUDVIEWER_VERSION
ARG VTK_VERSION
ARG PCL_VERSION
ARG CUDA_VERSION
ARG UBUNTU_VERSION
FROM cloudviewer-deps:${EROWCLOUDVIEWER_VERSION}-ubuntu${UBUNTU_VERSION}-cuda${CUDA_VERSION}
LABEL maintainer="AliceVision Team ludahai19@163.com"

# Execute with nvidia docker (https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0))
# docker run -it --runtime nvidia -p 2222:22 --name cloudViewer -v</path/to/your/data>:/data cloudviewer:develop-ubuntu18.04-cuda10.2
# ssh -p 2222 -X root@<docker host> /opt/ErowCloudViewer # Password is 'cloudviewer'

ENV EROWCLOUDVIEWER_DEV=/opt/ErowCloudViewer \
    EROWCLOUDVIEWER_BUILD=/opt/ErowCloudViewer/build \
    EROWCLOUDVIEWER_INSTALL=/opt/ErowCloudViewer/install \
    BUNDLE_CLOUDVIEWER_ML=/opt/ErowCloudViewer/CloudViewer-ML \
    AV_INSTALL=/opt/AliceVision_install \
    QT_DIR=/opt/Qt5.14.2/5.14.2/gcc_64 \
    PATH="${PATH}:${BUNDLE_CLOUDVIEWER_ML}"

COPY . ${EROWCLOUDVIEWER_DEV}/ErowCloudViewer

WORKDIR ${EROWCLOUDVIEWER_BUILD}

# fix conflicts between python object.h and qt head file
RUN sed -i "s/PyType_Slot \*slots/PyType_Slot \*_slots/g" /root/miniconda3/include/python3.6m/object.h

# Build ErowCloudViewer plugins
RUN cmakWhlOptions=(-DDEVELOPER_BUILD=OFF
                    -DCMAKE_BUILD_TYPE=Release
                    -DBUILD_JUPYTER_EXTENSION=ON
                    -DBUILD_LIBREALSENSE=ON
                    -DBUILD_AZURE_KINECT=ON
                    -DBUILD_RPC_INTERFACE=ON
                    -DBUILD_BENCHMARKS=OFF
                    -DWITH_OPENMP=ON
                    -DBUILD_CUDA_MODULE=ON
                    -DBUILD_PYTORCH_OPS=ON
                    -DBUILD_TENSORFLOW_OPS=ON
                    -DGLIBCXX_USE_CXX11_ABI=OFF
                    #-DBUNDLE_CLOUDVIEWER_ML=ON
                    #-DCLOUDVIEWER_ML_ROOT="${BUNDLE_CLOUDVIEWER_ML}"
                    #-DTHIRD_PARTY_DOWNLOAD_DIR=/opt/ErowCloudViewer/thirdparties
                    -DPYTHON_EXECUTABLE=/root/miniconda3/bin/python3.6
                    -DPYTHON_IN_PATH=/root/miniconda3/bin/python3.6
                    -DPYTHON_LIBRARY=/root/miniconda3/lib/libpython3.6m.so
                    -DQT_QMAKE_EXECUTABLE:PATH=${QT_DIR}/bin/qmake
                    -DCMAKE_PREFIX_PATH:PATH=${QT_DIR}/lib/cmake
                    )

RUN cmake "${EROWCLOUDVIEWER_DEV}/ErowCloudViewer" \
          "${cmakWhlOptions[@]}" \
          -DCMAKE_INSTALL_PREFIX=${EROWCLOUDVIEWER_INSTALL}

RUN make "-j$(nproc)" pip-package \
    #&& make "-j$(nproc)" install-pip-package \
    #&& make "-j$(nproc)" conda-package \
    && make install "-j$(nproc)"


RUN cmakGuiOptions=(-DDEVELOPER_BUILD=OFF
                    -DCMAKE_BUILD_TYPE=Release
                    -DBUILD_JUPYTER_EXTENSION=ON
                    -DBUILD_LIBREALSENSE=ON
                    -DBUILD_AZURE_KINECT=ON
                    -DBUILD_RPC_INTERFACE=ON
                    -DBUILD_BENCHMARKS=OFF
                    -DWITH_OPENMP=ON
                    -DBUILD_CUDA_MODULE=OFF
                    -DBUILD_PYTORCH_OPS=OFF
                    -DBUILD_TENSORFLOW_OPS=OFF
                    -DBUNDLE_CLOUDVIEWER_ML=OFF
                    -DGLIBCXX_USE_CXX11_ABI=ON
                    -DCVCORELIB_USE_CGAL=ON
                    -DCVCORELIB_SHARED=ON
                    -DCVCORELIB_USE_QT_CONCURRENT=ON
                    -DOPTION_USE_DXF_LIB=ON
                    -DOPTION_USE_RANSAC_LIB=ON
                    -DOPTION_USE_SHAPE_LIB=ON
                    -DPLUGIN_IO_QADDITIONAL=ON
                    -DPLUGIN_IO_QCORE=ON
                    -DPLUGIN_IO_QCSV_MATRIX=ON
                    -DPLUGIN_IO_QE57=ON
                    -DPLUGIN_IO_QMESH=ON
                    -DPLUGIN_IO_QPDAL=ON
                    -DPLUGIN_IO_QPHOTOSCAN=ON
                    -DPLUGIN_IO_QRDB=ON
                    -DPLUGIN_IO_QRDB_FETCH_DEPENDENCY=ON
                    -DPLUGIN_STANDARD_MASONRY_QAUTO_SEG=ON
                    -DPLUGIN_STANDARD_MASONRY_QMANUAL_SEG=ON
                    -DPLUGIN_STANDARD_QANIMATION=ON
                    -DPLUGIN_STANDARD_QCANUPO=ON
                    -DPLUGIN_STANDARD_QCOLORIMETRIC_SEGMENTER=ON
                    -DPLUGIN_STANDARD_QCOMPASS=ON
                    -DPLUGIN_STANDARD_QCSF=ON
                    -DPLUGIN_STANDARD_QFACETS=ON
                    -DPLUGIN_STANDARD_QHOUGH_NORMALS=ON
                    -DPLUGIN_STANDARD_QM3C2=ON
                    -DPLUGIN_STANDARD_QMPLANE=ON
                    -DPLUGIN_STANDARD_QPCL=ON
                    -DPLUGIN_STANDARD_QPOISSON_RECON=ON
                    -DPOISSON_RECON_WITH_OPEN_MP=ON
                    -DPLUGIN_STANDARD_QRANSAC_SD=ON
                    -DPLUGIN_STANDARD_QSRA=ON
                    #-DTHIRD_PARTY_DOWNLOAD_DIR=/opt/ErowCloudViewer/thirdparties
                    -DPYTHON_EXECUTABLE=/root/miniconda3/bin/python3.6
                    -DPYTHON_IN_PATH=/root/miniconda3/bin/python3.6
                    -DPYTHON_LIBRARY=/root/miniconda3/lib/libpython3.6m.so
                    -DQT_QMAKE_EXECUTABLE:PATH=${QT_DIR}/bin/qmake
                    -DCMAKE_PREFIX_PATH:PATH=${QT_DIR}/lib/cmake
                    )

RUN cmake "${EROWCLOUDVIEWER_DEV}/ErowCloudViewer" \
          "${cmakGuiOptions[@]}" \
          -DCMAKE_INSTALL_PREFIX=${EROWCLOUDVIEWER_INSTALL}

RUN make "-j$(nproc)" \
    && make install "-j$(nproc)" \
    && rm -rf ${EROWCLOUDVIEWER_BUILD}

WORKDIR /root