ARG CLOUDVIEWER_VERSION
ARG VTK_VERSION
ARG PCL_VERSION
ARG CUDA_VERSION
ARG UBUNTU_VERSION
ARG DEPENDENCY_IMAGE_NAME
FROM ${DEPENDENCY_IMAGE_NAME}:${CLOUDVIEWER_VERSION}-ubuntu${UBUNTU_VERSION}-cuda${CUDA_VERSION}
LABEL maintainer="AliceVision Team ludahai19@163.com"

# Env vars for the nvidia-container-runtime.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all

# Miniconda requires bash as the default shell.
SHELL ["/bin/bash", "-c"]

ENV ACloudViewer_DEV=/root \
    ACloudViewer_BUILD=/root/ACloudViewer/build \
    ACloudViewer_INSTALL=/root/install

ENV PATH="/root/miniconda3/bin:$PATH"
ENV CLOUDVIEWER_ML_ROOT=/root/CloudViewer-ML
RUN git clone https://github.com/Asher-1/CloudViewer-ML.git ${CLOUDVIEWER_ML_ROOT}

COPY . ${ACloudViewer_DEV}/ACloudViewer
WORKDIR ${ACloudViewer_DEV}/ACloudViewer

RUN mkdir -p ${ACloudViewer_INSTALL}

# Build cloudViewer wheels for python3.8-3.11
RUN rm -rf ${ACloudViewer_BUILD}/* && ./docker/build_cloudviewer_whl_conda.sh 3.8
RUN rm -rf ${ACloudViewer_BUILD}/* && ./docker/build_cloudviewer_whl_conda.sh 3.9
RUN rm -rf ${ACloudViewer_BUILD}/* && ./docker/build_cloudviewer_whl_conda.sh 3.10
RUN rm -rf ${ACloudViewer_BUILD}/* && ./docker/build_cloudviewer_whl_conda.sh 3.11

# Build ACloudViewer app installer
RUN rm -rf ${ACloudViewer_BUILD}/* && ./docker/build_gui_app_conda.sh 3.8

WORKDIR ${ACloudViewer_DEV}/ACloudViewer
