[CmdletBinding()]
param(
    [string]$Version = $(if ($env:VULKAN_SDK_VERSION) { $env:VULKAN_SDK_VERSION } else { "1.4.350.0" }),
    [string]$InstallRoot,
    [switch]$Force,
    [switch]$SkipProfile
)

$ErrorActionPreference = "Stop"

if (-not $InstallRoot) {
    $InstallRoot = Join-Path ${env:ProgramData} "ACloudViewer\VulkanSDK\$Version"
}

$LocalRoot = if ($env:ACLOUDVIEWER_LOCAL_ROOT) {
    $env:ACLOUDVIEWER_LOCAL_ROOT
} else {
    Join-Path $env:LOCALAPPDATA "acloudviewer"
}
$EnvScript = Join-Path $LocalRoot "acloudviewer-vulkan-env.ps1"

$defaultSha256 = "855b27ba05d2d8119c5114c5d4ff870ca38f2c632b11e1bb9923b9b7e6ecfe7b"
$sha256 = if ($Version -eq "1.4.350.0") {
    $defaultSha256
} elseif ($env:VULKAN_SDK_SHA256) {
    $env:VULKAN_SDK_SHA256
} else {
    throw "Set VULKAN_SDK_SHA256 when overriding VULKAN_SDK_VERSION."
}

$glslc = Join-Path $InstallRoot "Bin\glslc.exe"
$spirvHeader = Join-Path $InstallRoot "Include\spirv\unified1\spirv.hpp"
$vulkanLibrary = Join-Path $InstallRoot "Lib\vulkan-1.lib"

if ($Force -or -not (Test-Path $glslc) -or -not (Test-Path $spirvHeader) -or -not (Test-Path $vulkanLibrary)) {
    $workDir = Join-Path ([System.IO.Path]::GetTempPath()) "acloudviewer-vulkan-$Version"
    $installer = Join-Path $workDir "vulkan_sdk.exe"
    Remove-Item $workDir -Recurse -Force -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Force -Path $workDir | Out-Null

    $uri = "https://sdk.lunarg.com/sdk/download/$Version/windows/vulkan_sdk.exe"
    Write-Host "Downloading Vulkan SDK $Version from $uri"
    Invoke-WebRequest -Uri $uri -OutFile $installer
    $actualSha256 = (Get-FileHash -Algorithm SHA256 $installer).Hash.ToLowerInvariant()
    if ($actualSha256 -ne $sha256.ToLowerInvariant()) {
        throw "Vulkan SDK SHA256 mismatch: got $actualSha256, expected $sha256"
    }

    $arguments = @(
        "--root", $InstallRoot,
        "--accept-licenses",
        "--default-answer",
        "--confirm-command",
        "install",
        "copy_only=1"
    )
    $process = Start-Process -FilePath $installer -ArgumentList $arguments -Wait -PassThru -NoNewWindow
    if ($process.ExitCode -ne 0) {
        throw "Vulkan SDK installer failed with exit code $($process.ExitCode)"
    }
    Remove-Item $workDir -Recurse -Force
}

foreach ($path in @($glslc, $spirvHeader, $vulkanLibrary)) {
    if (-not (Test-Path $path)) {
        throw "Incomplete Vulkan SDK installation; missing $path"
    }
}

New-Item -ItemType Directory -Force -Path $LocalRoot | Out-Null
@(
    "# Generated by util/install_vulkan_sdk_windows.ps1 — do not edit by hand."
    "`$env:ACLOUDVIEWER_LOCAL_ROOT = '$LocalRoot'"
    "`$env:VULKAN_SDK = '$InstallRoot'"
    "`$env:ACLOUDVIEWER_GLSLC = '$glslc'"
    "`$env:ACLOUDVIEWER_SPIRV_INCLUDE_DIR = '$InstallRoot\Include'"
    "`$env:PATH = '$InstallRoot\Bin;' + `$env:PATH"
) | Set-Content -Path $EnvScript -Encoding UTF8

if (-not $SkipProfile) {
    $profilePath = $PROFILE.CurrentUserAllHosts
    $marker = "# >>> acloudviewer-vulkan >>>"
    if (-not (Test-Path $profilePath) -or -not (Select-String -Path $profilePath -SimpleMatch -Quiet $marker)) {
        New-Item -ItemType File -Force -Path $profilePath | Out-Null
        @(
            ""
            $marker
            ". '$EnvScript'"
            "# <<< acloudviewer-vulkan <<<"
        ) | Add-Content -Path $profilePath -Encoding UTF8
        Write-Host "Appended Vulkan env hook to $profilePath"
    }
}

if ($env:GITHUB_ENV) {
    @(
        "VULKAN_SDK=$InstallRoot"
        "ACLOUDVIEWER_GLSLC=$glslc"
        "ACLOUDVIEWER_SPIRV_INCLUDE_DIR=$InstallRoot\Include"
        "ACLOUDVIEWER_LOCAL_ROOT=$LocalRoot"
    ) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
}
if ($env:GITHUB_PATH) {
    (Join-Path $InstallRoot "Bin") | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
}

Write-Host "Vulkan SDK ready: $InstallRoot"
Write-Host "  env script: $EnvScript"
Write-Host "  glslc: $glslc"
Write-Host "  SPIR-V headers: $spirvHeader"
Write-Host "  import library: $vulkanLibrary"
Write-Host "For a new PowerShell session run: . '$EnvScript'"
& $glslc --version
