[CmdletBinding()]
param(
    [switch]$SkipProfile
)

$ErrorActionPreference = "Stop"

function Resolve-VulkanSdkPath {
    param([string]$Root)

    if (-not $Root) {
        throw "VULKAN_SDK is empty."
    }

    $candidates = @(
        $Root,
        (Join-Path $Root "x86_64")
    )
    foreach ($candidate in @($candidates)) {
        $header = Join-Path $candidate "Include\vulkan\vulkan_core.h"
        if (-not (Test-Path $header)) {
            $header = Join-Path $candidate "include\vulkan\vulkan_core.h"
        }
        if (Test-Path $header) {
            return $candidate
        }
    }
    throw "Vulkan headers not found under VULKAN_SDK=$Root"
}

function Resolve-GlslcPath {
    param([string]$SdkRoot)

    foreach ($dir in @("Bin", "bin")) {
        $candidate = Join-Path $SdkRoot "$dir\glslc.exe"
        if (Test-Path $candidate) {
            return $candidate
        }
    }
    throw "glslc.exe not found under $SdkRoot"
}

function Resolve-SpirvIncludeDir {
    param([string]$SdkRoot)

    foreach ($dir in @("Include", "include")) {
        $header = Join-Path $SdkRoot "$dir\spirv\unified1\spirv.hpp"
        if (Test-Path $header) {
            return (Join-Path $SdkRoot $dir)
        }
    }
    throw "SPIR-V headers not found under $SdkRoot"
}

function Resolve-VulkanImportLib {
    param([string]$SdkRoot)

    foreach ($dir in @("Lib", "lib")) {
        $candidate = Join-Path $SdkRoot "$dir\vulkan-1.lib"
        if (Test-Path $candidate) {
            return $candidate
        }
    }
    throw "vulkan-1.lib not found under $SdkRoot"
}

if (-not $env:VULKAN_SDK) {
    throw "VULKAN_SDK is not set. Install the SDK first or run util/install_vulkan_sdk_windows.ps1."
}

$SdkRoot = Resolve-VulkanSdkPath -Root $env:VULKAN_SDK
$glslc = Resolve-GlslcPath -SdkRoot $SdkRoot
$spirvInclude = Resolve-SpirvIncludeDir -SdkRoot $SdkRoot
$vulkanLib = Resolve-VulkanImportLib -SdkRoot $SdkRoot

$LocalRoot = if ($env:ACLOUDVIEWER_LOCAL_ROOT) {
    $env:ACLOUDVIEWER_LOCAL_ROOT
} else {
    Join-Path $env:LOCALAPPDATA "acloudviewer"
}
$EnvScript = Join-Path $LocalRoot "acloudviewer-vulkan-env.ps1"
$binDir = Split-Path $glslc -Parent

New-Item -ItemType Directory -Force -Path $LocalRoot | Out-Null
@(
    '# Generated by util/sync_vulkan_env_from_sdk.ps1 - do not edit by hand.'
    "`$env:ACLOUDVIEWER_LOCAL_ROOT = '$LocalRoot'"
    "`$env:VULKAN_SDK = '$SdkRoot'"
    "`$env:ACLOUDVIEWER_GLSLC = '$glslc'"
    "`$env:ACLOUDVIEWER_SPIRV_INCLUDE_DIR = '$spirvInclude'"
    "`$env:PATH = '$binDir;' + `$env:PATH"
) | Set-Content -Path $EnvScript -Encoding UTF8

$skipProfileHook = $SkipProfile.IsPresent -or $env:GITHUB_ACTIONS
if (-not $skipProfileHook) {
    $profilePath = $PROFILE.CurrentUserAllHosts
    $markerBegin = '# acloudviewer-vulkan-begin'
    $markerEnd = '# acloudviewer-vulkan-end'
    if (-not (Test-Path $profilePath) -or -not (Select-String -Path $profilePath -SimpleMatch -Quiet $markerBegin)) {
        New-Item -ItemType File -Force -Path $profilePath | Out-Null
        @(
            ''
            $markerBegin
            ". '$EnvScript'"
            $markerEnd
        ) | Add-Content -Path $profilePath -Encoding UTF8
        Write-Host "Appended Vulkan env hook to $profilePath"
    }
}

if ($env:GITHUB_ENV) {
    @(
        "VULKAN_SDK=$SdkRoot"
        "ACLOUDVIEWER_GLSLC=$glslc"
        "ACLOUDVIEWER_SPIRV_INCLUDE_DIR=$spirvInclude"
        "ACLOUDVIEWER_LOCAL_ROOT=$LocalRoot"
    ) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
}
if ($env:GITHUB_PATH) {
    $binDir | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
}

Write-Host "Vulkan SDK ready: $SdkRoot"
Write-Host "  env script: $EnvScript"
Write-Host "  glslc: $glslc"
Write-Host "  SPIR-V headers: $spirvInclude"
Write-Host "  import library: $vulkanLib"
Write-Host "For a new PowerShell session run: . '$EnvScript'"
& $glslc --version
