#!/usr/bin/env bash
# Write ~/.local/share/acloudviewer/acloudviewer-vulkan-env.sh from an existing VULKAN_SDK tree.
# Used after humbletim/install-vulkan-sdk in CI, or when VULKAN_SDK is already on disk.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${script_dir}/acloudviewer_vulkan_env_common.sh"

ACLOUDVIEWER_LOCAL_ROOT="$(acloudviewer_vulkan_local_root)"
ENV_SCRIPT="$(acloudviewer_vulkan_env_script_path)"
UPDATE_BASHRC="${ACLOUDVIEWER_UPDATE_BASHRC:-1}"
if [[ -n "${GITHUB_ACTIONS:-}" ]]; then
    UPDATE_BASHRC=0
fi

resolve_existing_vulkan_sdk() {
    local candidate="$1"
    local sub root header

    for sub in "" "${VULKAN_SDK_VERSION:-}" macOS x86_64; do
        root="${candidate}"
        if [[ -n "${sub}" ]]; then
            root="${candidate}/${sub}"
        fi
        header="${root}/include/vulkan/vulkan_core.h"
        if [[ -f "${header}" ]]; then
            printf '%s\n' "${root}"
            return 0
        fi
    done

    local setup_script
    setup_script="$(find "${candidate}" -maxdepth 4 -name setup-env.sh -type f -print -quit 2>/dev/null || true)"
    if [[ -n "${setup_script}" ]]; then
        resolve_vulkan_sdk_from_setup_script "${setup_script}"
        return 0
    fi

    header="$(find "${candidate}" -path '*/include/vulkan/vulkan_core.h' -print -quit 2>/dev/null || true)"
    if [[ -n "${header}" ]]; then
        root="$(cd "$(dirname "${header}")/../.." && pwd)"
        printf '%s\n' "${root}"
        return 0
    fi
    return 1
}

if [[ -z "${VULKAN_SDK:-}" ]]; then
    echo "ERROR: VULKAN_SDK is not set. Install the SDK first or run util/install_vulkan_sdk_macos.sh." >&2
    exit 1
fi

echo "Resolving Vulkan SDK from VULKAN_SDK=${VULKAN_SDK}" >&2
VULKAN_SDK="$(resolve_existing_vulkan_sdk "${VULKAN_SDK}")" || {
    echo "ERROR: Vulkan headers not found under VULKAN_SDK=${VULKAN_SDK:-}." >&2
    echo "macOS CI: humbletim/install-vulkan-sdk should flatten macOS/* into \$VULKAN_SDK (include/, bin/, lib/)." >&2
    echo "Windows CI: use util/install_vulkan_sdk_windows.ps1 (SDK >= 1.4.313 needs silent install, not 7z)." >&2
    exit 1
}
echo "Resolved VULKAN_SDK=${VULKAN_SDK}" >&2
glslc_path="${VULKAN_SDK}/bin/glslc"
if [[ ! -x "${glslc_path}" ]]; then
    glslc_path="$(command -v glslc || true)"
fi
spirv_header="${VULKAN_SDK}/include/spirv/unified1/spirv.hpp"
moltenvk_icd="$(find "${VULKAN_SDK}/share/vulkan/icd.d" \
    -maxdepth 1 -iname '*moltenvk*.json' -type f -print -quit 2>/dev/null || true)"

if [[ -z "${glslc_path}" || ! -x "${glslc_path}" || ! -f "${spirv_header}" ]]; then
    echo "ERROR: incomplete Vulkan SDK at ${VULKAN_SDK}." >&2
    exit 1
fi

mkdir -p "${ACLOUDVIEWER_LOCAL_ROOT}"
{
    printf '# Generated by util/sync_vulkan_env_from_sdk.sh - do not edit by hand.\n'
    printf 'export ACLOUDVIEWER_LOCAL_ROOT="%s"\n' "${ACLOUDVIEWER_LOCAL_ROOT}"
    printf 'export VULKAN_SDK="%s"\n' "${VULKAN_SDK}"
    printf 'export PATH="%s/bin:${PATH}"\n' "${VULKAN_SDK}"
    printf 'export ACLOUDVIEWER_GLSLC="%s"\n' "${glslc_path}"
    printf 'export ACLOUDVIEWER_SPIRV_INCLUDE_DIR="%s/include"\n' "${VULKAN_SDK}"
    printf 'export DYLD_LIBRARY_PATH="%s/lib${DYLD_LIBRARY_PATH:+:${DYLD_LIBRARY_PATH}}"\n' "${VULKAN_SDK}"
    if [[ -n "${moltenvk_icd}" ]]; then
        printf 'export VK_ADD_DRIVER_FILES="%s"\n' "${moltenvk_icd}"
    fi
} >"${ENV_SCRIPT}"

if [[ -n "${GITHUB_ENV:-}" ]]; then
    {
        echo "VULKAN_SDK=${VULKAN_SDK}"
        echo "ACLOUDVIEWER_GLSLC=${glslc_path}"
        echo "ACLOUDVIEWER_SPIRV_INCLUDE_DIR=${VULKAN_SDK}/include"
        echo "ACLOUDVIEWER_LOCAL_ROOT=${ACLOUDVIEWER_LOCAL_ROOT}"
        echo "DYLD_LIBRARY_PATH=${VULKAN_SDK}/lib${DYLD_LIBRARY_PATH:+:${DYLD_LIBRARY_PATH}}"
        if [[ -n "${moltenvk_icd}" ]]; then
            echo "VK_ADD_DRIVER_FILES=${moltenvk_icd}"
        fi
    } >>"${GITHUB_ENV}"
fi
if [[ -n "${GITHUB_PATH:-}" ]]; then
    echo "${VULKAN_SDK}/bin" >>"${GITHUB_PATH}"
fi

append_bashrc_vulkan_hook "${ENV_SCRIPT}" "${UPDATE_BASHRC}"

echo "Vulkan SDK ready: ${VULKAN_SDK}"
echo "  env script: ${ENV_SCRIPT}"
echo "  glslc: ${glslc_path}"
echo "  SPIR-V headers: ${spirv_header}"
if [[ -n "${moltenvk_icd}" ]]; then
    echo "  MoltenVK ICD: ${moltenvk_icd}"
fi
"${glslc_path}" --version
