// ----------------------------------------------------------------------------
// -                        CloudViewer: www.cloudViewer.org                  -
// ----------------------------------------------------------------------------
// Copyright (c) 2018-2024 www.cloudViewer.org
// SPDX-License-Identifier: MIT
// ----------------------------------------------------------------------------
//
// Numeric gate for the LingBot-Map windowed long-sequence orchestration:
// the C++ stitcher must reproduce the official Python pipeline (ggml_demo.py
// numpy port, upstream-verified against inference_windowed) on deterministic
// synthetic data. Golden values are generated by gen_stitch_golden.py.

#include <cmath>
#include <cstdio>
#include <cstdlib>

#include "LingbotWindowStitcher.h"
#include "lingbot_window_stitch_golden.h"

using namespace lingbot_stitch;

namespace {

int g_failures = 0;

void expectNear(float actual,
                float expected,
                float absTol,
                float relTol,
                const char* what) {
    const float diff = std::fabs(actual - expected);
    if (diff <= absTol || diff <= relTol * std::fabs(expected)) return;
    std::fprintf(stderr, "FAIL %s: actual %.9g expected %.9g\n", what, actual,
                 expected);
    ++g_failures;
}

void expectArraysNear(const float* actual,
                      const float* expected,
                      size_t n,
                      const char* what) {
    for (size_t i = 0; i < n; ++i) {
        const float diff = std::fabs(actual[i] - expected[i]);
        if (std::isnan(actual[i]) && std::isnan(expected[i])) continue;
        if (diff <= 1e-6f || diff <= 2e-5f * std::fabs(expected[i])) continue;
        std::fprintf(stderr, "FAIL %s[%zu]: actual %.9g expected %.9g\n", what,
                     i, actual[i], expected[i]);
        ++g_failures;
        return;  // one report per array keeps the log readable
    }
}

WindowData windowFromGolden(int start,
                            int frames,
                            const float* poseEnc,
                            const float* depth,
                            const float* conf,
                            const float* c2w,
                            const float* intr) {
    WindowData w;
    w.start = start;
    w.frames = frames;
    w.width = kGoldenW;
    w.height = kGoldenH;
    const size_t plane = static_cast<size_t>(kGoldenW) * kGoldenH;
    w.poseEnc.assign(poseEnc,
                     poseEnc + static_cast<size_t>(frames) * kPoseEncSize);
    w.depth.assign(depth, depth + static_cast<size_t>(frames) * plane);
    w.depthConf.assign(conf, conf + static_cast<size_t>(frames) * plane);
    w.c2w.assign(c2w, c2w + static_cast<size_t>(frames) * kC2WSize);
    w.intrinsics.assign(intr,
                        intr + static_cast<size_t>(frames) * kIntrinsicsSize);
    return w;
}

}  // namespace

int main() {
    // ---- quat -> mat -> quat round trip against rotation.py ----
    for (int c = 0; c < kQuatCases; ++c) {
        float mat[9];
        quatToMat(kQuatIn + static_cast<size_t>(c) * 4, mat);
        expectArraysNear(mat, kQuatMat + static_cast<size_t>(c) * 9, 9,
                         "quatToMat");
        float back[4];
        matToQuat(mat, back);
        expectArraysNear(back, kQuatBack + static_cast<size_t>(c) * 4, 4,
                         "matToQuat");
    }

    // ---- two-window chain ----
    {
        const WindowPlan plan = planWindows(kTwoWinTotal, kTwoWinWindowSize,
                                            kTwoWinOverlap, /*scaleFrames=*/8);
        if (plan.windows.size() != 2 ||
            plan.windows[0] != std::make_pair(0, 16) ||
            plan.windows[1] != std::make_pair(8, 20) || plan.effOverlap != 8) {
            std::fprintf(stderr, "FAIL TwoWin plan\n");
            ++g_failures;
        }
        WindowData w0 = windowFromGolden(0, 16, kTwoWinWin0PoseEnc,
                                         kTwoWinWin0Depth, kTwoWinWin0Conf,
                                         kTwoWinWin0C2w, kTwoWinWin0Intr);
        WindowData w1 = windowFromGolden(8, 12, kTwoWinWin1PoseEnc,
                                         kTwoWinWin1Depth, kTwoWinWin1Conf,
                                         kTwoWinWin1C2w, kTwoWinWin1Intr);
        const Similarity sim = pairwiseAlignment(w0, w1, kTwoWinOverlap);
        expectNear(sim.s, kTwoWinAlign0S, 1e-7f, 2e-5f, "TwoWin align s");
        expectArraysNear(sim.R, kTwoWinAlign0R, 9, "TwoWin align R");
        expectArraysNear(sim.t, kTwoWinAlign0T, 3, "TwoWin align t");
        warpWindow(w1, sim);
        expectArraysNear(w1.poseEnc.data(), kTwoWinWarped1PoseEnc,
                         12 * kPoseEncSize, "TwoWin warped pose_enc");
        expectArraysNear(w1.depth.data(), kTwoWinWarped1Depth,
                         12 * kGoldenW * kGoldenH, "TwoWin warped depth");
        expectArraysNear(w1.c2w.data(), kTwoWinWarped1C2w, 12 * kC2WSize,
                         "TwoWin warped c2w");
        std::vector<WindowData> windows;
        windows.push_back(std::move(w0));
        windows.push_back(std::move(w1));
        const WindowData merged = stitchWindows(windows, kTwoWinOverlap);
        if (merged.frames != kTwoWinMergedFrames) {
            std::fprintf(stderr, "FAIL TwoWin merged frames %d != %d\n",
                         merged.frames, kTwoWinMergedFrames);
            ++g_failures;
        }
        expectArraysNear(
                merged.poseEnc.data(), kTwoWinMergedPoseEnc,
                static_cast<size_t>(kTwoWinMergedFrames) * kPoseEncSize,
                "TwoWin merged pose_enc");
        expectArraysNear(
                merged.depth.data(), kTwoWinMergedDepth,
                static_cast<size_t>(kTwoWinMergedFrames) * kGoldenW * kGoldenH,
                "TwoWin merged depth");
        expectArraysNear(merged.c2w.data(), kTwoWinMergedC2w,
                         static_cast<size_t>(kTwoWinMergedFrames) * kC2WSize,
                         "TwoWin merged c2w");
        expectArraysNear(
                merged.intrinsics.data(), kTwoWinMergedIntr,
                static_cast<size_t>(kTwoWinMergedFrames) * kIntrinsicsSize,
                "TwoWin merged intrinsics");
    }

    // ---- three-window chained alignment (prev = warped[-1]) ----
    {
        WindowData w0 = windowFromGolden(0, 16, kThreeWinWin0PoseEnc,
                                         kThreeWinWin0Depth, kThreeWinWin0Conf,
                                         kThreeWinWin0C2w, kThreeWinWin0Intr);
        WindowData w1 = windowFromGolden(8, 16, kThreeWinWin1PoseEnc,
                                         kThreeWinWin1Depth, kThreeWinWin1Conf,
                                         kThreeWinWin1C2w, kThreeWinWin1Intr);
        WindowData w2 = windowFromGolden(16, 14, kThreeWinWin2PoseEnc,
                                         kThreeWinWin2Depth, kThreeWinWin2Conf,
                                         kThreeWinWin2C2w, kThreeWinWin2Intr);
        const Similarity sim1 = pairwiseAlignment(w0, w1, kThreeWinOverlap);
        expectNear(sim1.s, kThreeWinAlign0S, 1e-7f, 2e-5f, "ThreeWin align0 s");
        expectArraysNear(sim1.R, kThreeWinAlign0R, 9, "ThreeWin align0 R");
        expectArraysNear(sim1.t, kThreeWinAlign0T, 3, "ThreeWin align0 t");
        warpWindow(w1, sim1);
        expectArraysNear(w1.poseEnc.data(), kThreeWinWarped1PoseEnc,
                         16 * kPoseEncSize, "ThreeWin warped1 pose_enc");
        expectArraysNear(w1.c2w.data(), kThreeWinWarped1C2w, 16 * kC2WSize,
                         "ThreeWin warped1 c2w");
        const Similarity sim2 = pairwiseAlignment(w1, w2, kThreeWinOverlap);
        expectNear(sim2.s, kThreeWinAlign1S, 1e-7f, 2e-5f, "ThreeWin align1 s");
        expectArraysNear(sim2.R, kThreeWinAlign1R, 9, "ThreeWin align1 R");
        expectArraysNear(sim2.t, kThreeWinAlign1T, 3, "ThreeWin align1 t");
        warpWindow(w2, sim2);
        expectArraysNear(w2.poseEnc.data(), kThreeWinWarped2PoseEnc,
                         14 * kPoseEncSize, "ThreeWin warped2 pose_enc");
        std::vector<WindowData> windows;
        windows.push_back(std::move(w0));
        windows.push_back(std::move(w1));
        windows.push_back(std::move(w2));
        const WindowData merged = stitchWindows(windows, kThreeWinOverlap);
        if (merged.frames != kThreeWinMergedFrames) {
            std::fprintf(stderr, "FAIL ThreeWin merged frames %d != %d\n",
                         merged.frames, kThreeWinMergedFrames);
            ++g_failures;
        }
        expectArraysNear(
                merged.poseEnc.data(), kThreeWinMergedPoseEnc,
                static_cast<size_t>(kThreeWinMergedFrames) * kPoseEncSize,
                "ThreeWin merged pose_enc");
        expectArraysNear(merged.depth.data(), kThreeWinMergedDepth,
                         static_cast<size_t>(kThreeWinMergedFrames) * kGoldenW *
                                 kGoldenH,
                         "ThreeWin merged depth");
        expectArraysNear(merged.c2w.data(), kThreeWinMergedC2w,
                         static_cast<size_t>(kThreeWinMergedFrames) * kC2WSize,
                         "ThreeWin merged c2w");
    }

    if (g_failures != 0) {
        std::fprintf(stderr, "test_lingbot_window_stitch: %d FAILURES\n",
                     g_failures);
        return 1;
    }
    std::fprintf(stderr, "test_lingbot_window_stitch: PASS\n");
    return 0;
}
