// ----------------------------------------------------------------------------
// -                        CloudViewer: www.cloudViewer.org                  -
// ----------------------------------------------------------------------------
// Copyright (c) 2018-2024 www.cloudViewer.org
// SPDX-License-Identifier: MIT
// ----------------------------------------------------------------------------

#pragma once

#include <QColor>
#include <QImage>
#include <QPoint>
#include <QPointF>
#include <QString>
#include <QVector>
#include <QWidget>

//! Native QPainter-based 2D distance map widget for the qSRA plugin.
/** This widget renders the "unrolled" radial distance map of a Surface of
    Revolution (SoR) analysis. It replaces the previous VTK/OpenGL-based view
    to avoid OpenGL context conflicts in embedded Qt dialogs.

    The map shows radial deviations as a color-coded image, with:
    - X axis: angular position (longitude) or height
    - Y axis: height or angular position
    - Grid overlay with labels
    - Color scale bar showing the scalar field range
    - Overlay symbols (e.g. imported measurement points)

    Supports interactive pan (middle-drag) and zoom (mouse wheel).
**/
class qSRAMapWidget : public QWidget {
    Q_OBJECT

public:
    explicit qSRAMapWidget(QWidget* parent = nullptr);

    //! Set the map image (generated by
    //! DistanceMapGenerationTool::ConvertMapToImage)
    void setMapImage(const QImage& image);

    //! Set the map extents in world coordinates (for axis labels and grid)
    void setMapBounds(double xMin, double xMax, double yMin, double yMax);

    // --- Grid overlay ---
    void setGridVisible(bool visible);
    void setGridColor(const QColor& color);
    void setGridSteps(double xStep, double yStep);

    //! An axis label with its world-coordinate position
    struct Label {
        double position = 0.0;  //!< world coordinate (angle or height)
        QString text;           //!< display text
    };
    //! Set X-axis labels (bottom)
    void setXLabels(const QVector<Label>& labels);
    //! Set Y-axis labels (left)
    void setYLabels(const QVector<Label>& labels);
    //! Set font size for axis labels
    void setLabelFontSize(int size);

    //! An overlay symbol point (e.g. imported from measurement file)
    struct Symbol {
        double x = 0.0, y = 0.0;  //!< position in map world coordinates
        QString label;            //!< optional text label
        QColor color = Qt::red;   //!< symbol color
        double size = 10.0;       //!< symbol size in pixels
    };
    //! Set overlay symbols (replaces any existing ones)
    void setOverlaySymbols(const QVector<Symbol>& symbols);
    //! Remove all overlay symbols
    void clearOverlaySymbols();

    // --- Color scale bar (right side) ---
    //! Set color scale parameters and bar image
    void setColorScale(double minVal, double maxVal, const QImage& scaleBar);
    //! Toggle color scale bar visibility
    void setColorScaleVisible(bool visible);

    //! Auto-fit the view to show the entire map with margins
    void zoomFit();

    //! Export the current view as a QImage (for "Export as Image" feature)
    QImage exportAsImage() const;

signals:
    //! Emitted when the view transform changes (pan/zoom)
    void viewChanged();

protected:
    void paintEvent(QPaintEvent* event) override;
    void mousePressEvent(QMouseEvent* event) override;
    void mouseReleaseEvent(QMouseEvent* event) override;
    void mouseMoveEvent(QMouseEvent* event) override;
    void wheelEvent(QWheelEvent* event) override;
    void resizeEvent(QResizeEvent* event) override;

private:
    //! Compute the map drawing rectangle within the widget (respecting margins)
    QRectF mapViewport(int widgetWidth, int widgetHeight) const;
    //! Convert world coordinates to screen pixel coordinates
    QPointF worldToScreen(double wx,
                          double wy,
                          int widgetWidth,
                          int widgetHeight) const;
    //! Convert screen pixel coordinates to world coordinates
    QPointF screenToWorld(double sx,
                          double sy,
                          int widgetWidth,
                          int widgetHeight) const;
    //! Main painting routine (draws map, grid, labels, scale, symbols)
    void paintContent(QPainter& painter,
                      int widgetWidth,
                      int widgetHeight) const;

    QImage m_mapImage;    //!< the distance map raster image
    double m_xMin = 0.0;  //!< map X extent (min)
    double m_xMax = 1.0;  //!< map X extent (max)
    double m_yMin = 0.0;  //!< map Y extent (min)
    double m_yMax = 1.0;  //!< map Y extent (max)

    // View transform: screen = (world - center) * scale + viewport_center
    double m_centerX = 0.5;  //!< view center X in world coordinates
    double m_centerY = 0.5;  //!< view center Y in world coordinates
    double m_scale = 1.0;    //!< zoom scale factor

    // Grid settings
    bool m_gridVisible = true;
    QColor m_gridColor = Qt::gray;
    double m_gridXStep = 1.0;
    double m_gridYStep = 1.0;

    // Axis labels
    QVector<Label> m_xLabels;
    QVector<Label> m_yLabels;
    int m_labelFontSize = 10;

    // Overlay symbols (imported measurement points)
    QVector<Symbol> m_overlaySymbols;

    // Color scale bar
    bool m_colorScaleVisible = true;
    QImage m_colorScaleBar;  //!< vertical gradient image
    double m_scaleMinVal = 0.0;
    double m_scaleMaxVal = 1.0;

    // Interactive pan state
    bool m_panning = false;
    QPoint m_lastMousePos;

    // Layout margins (pixels)
    static constexpr int MARGIN_LEFT = 60;    //!< space for Y-axis labels
    static constexpr int MARGIN_BOTTOM = 30;  //!< space for X-axis labels
    static constexpr int MARGIN_RIGHT = 80;   //!< space for color scale bar
    static constexpr int MARGIN_TOP = 10;     //!< top padding
};
